<a href="https://colab.research.google.com/github/brien60/Stock-LSTM/blob/SLOT/SLOT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Setup

### Imports

In [1]:
import torch
from torch import nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, random_split
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence

from pathlib import Path
import json
import re

import sentencepiece as sp
from collections import Counter

import pandas as pd

from tqdm import tqdm

import os

import wandb

try:
  import optuna
  from optuna.integration.wandb import WeightsAndBiasesCallback

except:
  !pip install -q optuna
  !pip install -q optuna-integration[wandb]
  import optuna
  from optuna.integration.wandb import WeightsAndBiasesCallback


import time

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.9/400.9 kB 31.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 9.3 MB/s eta 0:00:00

### Colab Setup Code

In [2]:
!git clone -q --branch SLOT https://github.com/brien60/Stock-LSTM.git
%cd Stock-LSTM/
!unzip -q data.zip -d /content/Stock-LSTM/data

/content/Stock-LSTM

### Constants

In [117]:
torch.manual_seed(42)
torch.cuda.manual_seed(42)
device = "cuda" if torch.cuda.is_available() else "cpu"

if device == "cuda":
    os.environ["CUDA_LAUNCH_BLOCKING"] = "1"


dataset = "acl18"
dataset_dir = Path(dataset.upper())

data_dir = Path(f"data/{dataset}")

tweet_dir = data_dir / "tweet"
price_dir = data_dir / "price"

tweet_files_list = list(tweet_dir.rglob("*/*"))
list.sort(tweet_files_list)

stock_names = [stock.name for stock in list(tweet_dir.rglob("*")) if stock.is_dir()]
list.sort(stock_names)

num_stocks = len(stock_names)

json_file = dataset_dir / "all_tweets.jsonl"
spm_file = dataset_dir / "spm/slot_tweet_spm.model"
tokens_file = dataset_dir / "all_tweets_tokenized.jsonl"


vocab_size = 10_000

window_size = 25

num_epochs = 150
batch_size = 1024

## SLOT Overview

SLOT (Self-supervised Learning of Tweets for Capturing Multi-level Price Trends) aims to address
1. the sparsity of tweets, with the number of tweets being heavily biased towards the most popular stocks.
2. the fact that tweets have noisy information that are often irrelevant to the actual stock movement.

The first problem was addressed by having SLOT learn the stock and tweet embeddings in the same vector space through self-supervised learning. This allows the use of any tweet for even unpopular stocks.

To tackle the second problem, SLOT uses tweets to learn multi-level relationships between stocks, rather than using them as direct evidence for stock prediction (e.g. positive sentiment = up).

## Attention LSTM

In [4]:

class ALSTM(nn.Module):
    def __init__(self, input_size, hidden_size, dropout):
        super().__init__()
        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            batch_first=True,
        )
        self.dropout = nn.Dropout(dropout)
        self.ln = nn.Linear(hidden_size, hidden_size)
        self.tanh = nn.Tanh()
        self.u = nn.Parameter(data=torch.randn(hidden_size))


    def forward(self, x):
        # x: (batch, seq_len, input_size)

        # output: (batch, seq_len, hidden_size)
        # h_n, c_n : (num_layers, batch, hidden_size)
        output, (h_n, c_n) = self.lstm(x)
        output = self.dropout(output)
        output = self.tanh(self.ln(output))

        # query: u, key: output, values: output
        attn_scores = torch.matmul(output, self.u) # (batch, seq_len, hidden_size) @ (hidden_size) -> (batch, seq_len)
        weights = attn_scores / attn_scores.sum(dim=1, keepdim=True)
        weights = weights.unsqueeze(dim=-1) # (batch, seq_len, 1)

        # (batch, seq_len, 1) * (batch, seq_len, hidden_size) -> (batch, seq_len, hidden_size)
        # (batch, seq_len, hidden_size) -> (batch, hidden_size)
        h_attn = (weights * output).sum(dim=1)

        # (batch, hidden_size) || (batch, hidden_size) -> (batch, 2*hidden_size)
        h_out = torch.cat((h_n[0], h_attn), dim=1) # both the general summary and the attention

        return h_out

## Price Features

The price features that compose a feature vector $x_{st}$ are
- Price movements in a day: *c_open, c_high, c_low*
- Price movements between days: *n_close, n_adj_close*
- Long-term movements: *5_day, 10_day, ... , 30_day*

So the daily prices of days $t-29$ to $t$ are used to generate each $x_{st}$

These features have already been calculated and normalized in the csv files.

### Extracting features data

In [17]:
data_files_list = list(price_dir.rglob("*.csv"))

data_list = []

price_features = []
labels = []

for i, stock_file in enumerate(data_files_list):
    stock = stock_file.stem
    df = pd.read_csv(stock_file)
    # columns = [
    #     f'{stock}_c_open', f'{stock}_c_high', f'{stock}_c_low',
    #     f'{stock}_n_close', f'{stock}_n_adj_close',
    #     f'{stock}_adj_sum_5', f'{stock}_adj_sum_10', f'{stock}_adj_sum_15',
    #     f'{stock}_adj_sum_20', f'{stock}_adj_sum_25', f'{stock}_adj_sum_30',
    #     f'{stock}_label', f'{stock}_closing_price_for_label'
    # ]

    # price_features.extend(columns[:-2])
    # labels.append(columns[-2])

    # if i != 0:
    # df.drop(columns=['date'], inplace=True)
    # else:
        # columns = ['date'] + columns

    # df.columns = columns

    df['label'] = df['label'].shift(-1)
    df = df.dropna()

    data_list.append(df)

# combined_df = pd.concat(data_list, axis=1)
# combined_df = combined_df.dropna()

# combined_df
data_list[0]

,date,c_open,c_high,c_low,n_close,n_adj_close,adj_sum_5,adj_sum_10,adj_sum_15,adj_sum_20,adj_sum_25,adj_sum_30,label,closing_price_for_label
0,2013-06-03,0.315221,0.403677,-1.789139,-0.162949,-0.162949,-0.060053,0.693978,0.254750,-1.822094,-3.904163,-5.357703,0.0,802.619995
1,2013-06-04,0.259175,1.541274,-0.580953,-0.489646,-0.489646,0.290475,0.640925,0.925432,-0.888392,-2.934205,-4.442024,0.0,798.690002
2,2013-06-05,0.307984,1.697046,-0.062854,-0.399404,-0.399404,0.773852,0.661597,1.366688,-0.048146,-2.044601,-3.668510,1.0,795.500000
3,2013-06-06,-1.371144,0.016132,-2.345207,1.307357,1.307357,-0.567319,-0.539772,0.059806,-0.899804,-2.753595,-4.476944,1.0,805.900024
4,2013-06-07,-0.767961,0.341721,-1.388943,1.309094,1.309094,-1.545472,-1.667586,-1.099477,-1.696860,-3.478622,-5.281647,1.0,816.450012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,2015-12-23,0.387002,0.461272,-0.924911,0.122119,0.122119,0.569325,1.461315,1.426054,0.687537,0.405953,0.525282,0.0,1279.050049
647,2015-12-24,0.426532,0.585205,-0.083258,-0.467543,-0.467543,0.402810,1.675324,1.865783,1.267805,0.860538,0.849525,0.0,1273.069946
648,2015-12-28,-0.468983,0.139834,-1.552288,-0.008639,-0.008639,0.211791,1.586934,1.730458,1.386417,0.832519,0.750746,1.0,1272.959961
649,2015-12-29,-1.873466,0.122848,-1.949479,2.312725,2.312725,-1.643583,-0.674679,-0.569208,-0.699787,-1.382650,-1.514770,-1.0,1302.400024
650,2015-12-30,0.763285,0.970400,-0.084558,-1.016584,-1.016584,-0.452390,0.077257,0.375384,0.345881,-0.292752,-0.445668,-1.0,1289.160034

### Remove Dates

In [18]:
for df in data_list:
    df.drop(columns=['date'], inplace=True)

data_list[0]

,c_open,c_high,c_low,n_close,n_adj_close,adj_sum_5,adj_sum_10,adj_sum_15,adj_sum_20,adj_sum_25,adj_sum_30,label,closing_price_for_label
0,0.315221,0.403677,-1.789139,-0.162949,-0.162949,-0.060053,0.693978,0.254750,-1.822094,-3.904163,-5.357703,0.0,802.619995
1,0.259175,1.541274,-0.580953,-0.489646,-0.489646,0.290475,0.640925,0.925432,-0.888392,-2.934205,-4.442024,0.0,798.690002
2,0.307984,1.697046,-0.062854,-0.399404,-0.399404,0.773852,0.661597,1.366688,-0.048146,-2.044601,-3.668510,1.0,795.500000
3,-1.371144,0.016132,-2.345207,1.307357,1.307357,-0.567319,-0.539772,0.059806,-0.899804,-2.753595,-4.476944,1.0,805.900024
4,-0.767961,0.341721,-1.388943,1.309094,1.309094,-1.545472,-1.667586,-1.099477,-1.696860,-3.478622,-5.281647,1.0,816.450012
...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,0.387002,0.461272,-0.924911,0.122119,0.122119,0.569325,1.461315,1.426054,0.687537,0.405953,0.525282,0.0,1279.050049
647,0.426532,0.585205,-0.083258,-0.467543,-0.467543,0.402810,1.675324,1.865783,1.267805,0.860538,0.849525,0.0,1273.069946
648,-0.468983,0.139834,-1.552288,-0.008639,-0.008639,0.211791,1.586934,1.730458,1.386417,0.832519,0.750746,1.0,1272.959961
649,-1.873466,0.122848,-1.949479,2.312725,2.312725,-1.643583,-0.674679,-0.569208,-0.699787,-1.382650,-1.514770,-1.0,1302.400024
650,0.763285,0.970400,-0.084558,-1.016584,-1.016584,-0.452390,0.077257,0.375384,0.345881,-0.292752,-0.445668,-1.0,1289.160034

### Make X and y tensors

In [19]:
columns = data_list[0].columns.to_list()
price_features = columns[: -2]
labels = columns[-2]

In [119]:
X_st = [
    torch.tensor(df[price_features].to_numpy(), dtype=torch.float)
    for df in data_list
]
y = [
    torch.tensor(df[labels].to_numpy(), dtype=torch.float)
    for df in data_list
]

X_st = torch.stack(X_st).transpose(0, 1).to(device)
y = torch.stack(y).transpose(0, 1).to(device)

y = torch.sign(y)

X_st[0, :5], X_st.shape, y, y.shape

(tensor([[ 0.3152,  0.4037, -1.7891, -0.1629, -0.1629, -0.0601,  0.6940,  0.2548,
          -1.8221, -3.9042, -5.3577],
         [-0.3088,  0.6176, -1.4998,  0.3541,  0.3541, -0.9793, -2.8275, -3.6965,
          -3.8730, -4.0141, -4.0494],
         [-1.5480,  0.3031, -2.3598,  1.6170,  1.6170, -0.1256,  1.0089,  1.7204,
           1.6346,  1.9394,  1.9236],
         [-1.0971,  0.1097, -2.3039,  0.9972,  0.9972,  0.1097,  0.8256,  1.2379,
           0.9010,  0.7537,  0.2670],
         [ 1.4930,  2.1386, -1.9268, -1.3926, -1.3926,  3.9988,  4.7059,  5.6074,
           5.6017,  5.6725,  6.4114]], device='cuda:0'),
 torch.Size([651, 87, 11]),
 tensor([[ 0.,  0., -1.,  ..., -1.,  0., -1.],
         [ 0., -1., -1.,  ..., -1., -1., -1.],
         [ 1.,  1.,  1.,  ...,  1.,  0.,  0.],
         ...,
         [ 1.,  1.,  1.,  ...,  1.,  1.,  1.],
         [-1.,  0.,  0.,  ...,  0.,  0.,  0.],
         [-1.,  1., -1.,  ..., -1., -1., -1.]], device='cuda:0'),
 torch.Size([651, 87]))

## Self-supervised Learning of Embeddings

The goal is to learn tweet (h_e) and stock (h_s) embeddings in the same semantic space, that is, learning the embeddings together such that one embedding can be used to query for the other.
- a stock embedding and the embedding of tweet relevant to it are close together (higher dot product)
- stocks that are frequently co-mentioned will have similar embeddings; this naturally groups together stocks in the same industry/sector.
- solves problem of tweet sparsity; the model can associate stocks with tweets that don't directly mention it as long as they are close in vector space.

This was done by training for stock identification: predict the mentioned stock in a tweet when the stock symbol is masked.

Every tweet is tokenized with Sentence Piece and then the tokens that correspond to the stock the tweet mentions are masked with the special token MASK.
- "Thank you Apple for the new iPhone." -> "Thank you [MASK] for the new iPhone."

### Stock Identification Model

Use a BiLSTM (need to understand the context on both sides of the mask token).
- Using a transformer risks overfitting.

The stock embedding is a learnable parameter.

The hidden state vector generated at the masked token is used as the tweet embedding because it
- captures the immediate left (via the forward LSTM) and right context (via the backward LSTM) of the tweet, making it exactly what we need for stock identification,
- and it is the part of the tweet that most connects to mentioned stock.

### Write raw data to json

In [ ]:

buffer = []
buffer_size = 100_000
lines = 0

with open(json_file, "w", encoding="utf-8") as out:
    for tweet_file in tweet_files_list:

        with open(tweet_file, "r", encoding="utf-8") as f:


            for line in f:
                tweet = json.loads(line)

                json_tweet = {
                    "date": tweet_file.stem,
                    "stock": tweet_file.parent.name,
                    "tweet": tweet["text"].replace("\n", " ")
                }

                buffer.append(json.dumps(json_tweet))

                if len(buffer) >= buffer_size:
                    out.write("\n".join(buffer) + "\n")
                    lines += len(buffer)

                    buffer.clear()

                    print(f"{lines} lines written")

    if buffer:
        lines += len(buffer)
        out.write("\n".join(buffer) + "\n")
        print(f"{lines} lines written")

print("All tweets written")

100000 lines written
119844 lines written
All tweets written

### Txt file for sp training

In [ ]:
input_file = json_file
output_file = dataset_dir / "tweets_for_sp.txt"

with open(input_file, "r", encoding="utf-8") as f, open(output_file, "w", encoding="utf-8") as out:
    for line in f:
        tweet = json.loads(line)
        out.write(tweet["tweet"] + "\n")

### SPM Training

In [ ]:
spm_file = dataset_dir / "spm/slot_tweet_spm"
vocab_size = 10_000

sp.SentencePieceTrainer.train(
    input=output_file,
    model_prefix=spm_file,
    vocab_size=vocab_size,
    model_type="unigram",
    character_coverage=1.0,
    input_sentence_size=lines,
    shuffle_input_sentence=True,
    user_defined_symbols=["<MASK>", "<PAD>", "<UNK>"]
)

spm_file = str(spm_file.with_suffix(".model"))

In [5]:
slot_spm = sp.SentencePieceProcessor()
slot_spm.load(str(spm_file))

mask_id = slot_spm.piece_to_id("<MASK>")
pad_id = slot_spm.piece_to_id("<PAD>")
unk_id = slot_spm.piece_to_id("<UNK>")

mask_id, pad_id, unk_id

(3, 4, 5)

### Create tokenized jsonl

In [6]:
all_dates = []

for tweet_file in tweet_files_list:
        date = tweet_file.stem
        all_dates.append(date)


all_dates = sorted(dict.fromkeys(all_dates))

start_date, end_date = "2014-02-19", "2015-12-31"
start_date_idx, end_date_idx = all_dates.index(start_date), all_dates.index(end_date)

all_dates = all_dates[start_date_idx : end_date_idx + 1]

num_dates = len(all_dates)
num_dates, all_dates

(651,
 ['2014-02-19',
  '2014-02-20',
  '2014-02-21',
  '2014-02-22',
  '2014-02-23',
  '2014-02-24',
  '2014-02-25',
  '2014-02-26',
  '2014-02-27',
  '2014-02-28',
  '2014-03-01',
  '2014-03-02',
  '2014-03-03',
  '2014-03-04',
  '2014-03-05',
  '2014-03-06',
  '2014-03-07',
  '2014-03-08',
  '2014-03-09',
  '2014-03-10',
  '2014-03-11',
  '2014-03-12',
  '2014-03-13',
  '2014-03-14',
  '2014-03-15',
  '2014-03-16',
  '2014-03-17',
  '2014-03-18',
  '2014-03-19',
  '2014-03-20',
  '2014-03-21',
  '2014-03-22',
  '2014-03-23',
  '2014-03-24',
  '2014-03-25',
  '2014-03-26',
  '2014-03-27',
  '2014-03-28',
  '2014-03-29',
  '2014-03-30',
  '2014-03-31',
  '2014-04-01',
  '2014-04-02',
  '2014-04-03',
  '2014-04-04',
  '2014-04-05',
  '2014-04-06',
  '2014-04-07',
  '2014-04-08',
  '2014-04-09',
  '2014-04-10',
  '2014-04-11',
  '2014-04-12',
  '2014-04-13',
  '2014-04-14',
  '2014-04-15',
  '2014-04-16',
  '2014-04-17',
  '2014-04-18',
  '2014-04-19',
  '2014-04-20',
  '2014-04-21',
  '2014-04-22',
  '2014-04-23',
  '2014-04-24',
  '2014-04-25',
  '2014-04-26',
  '2014-04-27',
  '2014-04-28',
  '2014-04-29',
  '2014-04-30',
  '2014-05-01',
  '2014-05-02',
  '2014-05-03',
  '2014-05-04',
  '2014-05-05',
  '2014-05-06',
  '2014-05-07',
  '2014-05-08',
  '2014-05-09',
  '2014-05-10',
  '2014-05-11',
  '2014-05-12',
  '2014-05-13',
  '2014-05-14',
  '2014-05-15',
  '2014-05-16',
  '2014-05-17',
  '2014-05-18',
  '2014-05-19',
  '2014-05-20',
  '2014-05-21',
  '2014-05-22',
  '2014-05-23',
  '2014-05-24',
  '2014-05-25',
  '2014-05-26',
  '2014-05-27',
  '2014-05-28',
  '2014-05-29',
  '2014-05-30',
  '2014-05-31',
  '2014-06-01',
  '2014-06-02',
  '2014-06-03',
  '2014-06-04',
  '2014-06-05',
  '2014-06-06',
  '2014-06-07',
  '2014-06-08',
  '2014-06-09',
  '2014-06-10',
  '2014-06-11',
  '2014-06-12',
  '2014-06-13',
  '2014-06-14',
  '2014-06-15',
  '2014-06-16',
  '2014-06-18',
  '2014-06-19',
  '2014-06-20',
  '2014-06-21',
  '2014-06-22',
  '2014-06-23',
  '2014-06-24',
  '2014-06-25',
  '2014-06-26',
  '2014-06-27',
  '2014-06-28',
  '2014-06-29',
  '2014-06-30',
  '2014-07-01',
  '2014-07-02',
  '2014-07-03',
  '2014-07-04',
  '2014-07-05',
  '2014-07-06',
  '2014-07-07',
  '2014-07-08',
  '2014-07-09',
  '2014-07-10',
  '2014-07-11',
  '2014-07-12',
  '2014-07-13',
  '2014-07-14',
  '2014-07-15',
  '2014-07-16',
  '2014-07-17',
  '2014-07-18',
  '2014-07-19',
  '2014-07-20',
  '2014-07-21',
  '2014-07-22',
  '2014-07-23',
  '2014-07-24',
  '2014-07-25',
  '2014-07-26',
  '2014-07-27',
  '2014-07-28',
  '2014-07-29',
  '2014-07-30',
  '2014-07-31',
  '2014-08-01',
  '2014-08-02',
  '2014-08-03',
  '2014-08-04',
  '2014-08-05',
  '2014-08-07',
  '2014-08-08',
  '2014-08-09',
  '2014-08-10',
  '2014-08-11',
  '2014-08-12',
  '2014-08-13',
  '2014-08-14',
  '2014-08-15',
  '2014-08-16',
  '2014-08-17',
  '2014-08-18',
  '2014-08-19',
  '2014-08-20',
  '2014-08-21',
  '2014-08-22',
  '2014-08-23',
  '2014-08-24',
  '2014-08-25',
  '2014-08-26',
  '2014-08-27',
  '2014-08-28',
  '2014-08-29',
  '2014-08-30',
  '2014-08-31',
  '2014-09-01',
  '2014-09-02',
  '2014-09-03',
  '2014-09-04',
  '2014-09-05',
  '2014-09-06',
  '2014-09-07',
  '2014-09-08',
  '2014-09-09',
  '2014-09-10',
  '2014-09-11',
  '2014-09-12',
  '2014-09-13',
  '2014-09-14',
  '2014-09-15',
  '2014-09-16',
  '2014-09-17',
  '2014-09-18',
  '2014-09-19',
  '2014-09-20',
  '2014-09-21',
  '2014-09-22',
  '2014-09-23',
  '2014-09-29',
  '2014-09-30',
  '2014-10-01',
  '2014-10-02',
  '2014-10-03',
  '2014-10-04',
  '2014-10-05',
  '2014-10-06',
  '2014-10-07',
  '2014-10-08',
  '2014-10-09',
  '2014-10-10',
  '2014-10-11',
  '2014-10-12',
  '2014-10-13',
  '2014-10-14',
  '2014-10-15',
  '2014-10-16',
  '2014-10-17',
  '2014-10-18',
  '2014-10-19',
  '2014-10-20',
  '2014-10-21',
  '2014-10-22',
  '2014-10-23',
  '2014-10-24',
  '2014-10-25',
  '2014-10-26',
  '2014-10-27',
  '2014-10-28',
  '2014-10-29',
  '2014-10-30',
  '2014-10-31',
  '2014-11-01',
  '2014-11-02',
  '2014-11-03',
  '2014-11-04',
  '2014-11-05',
  '2014-11-06',
  '2014-11-07',
  '2014-11-08',
  '2014-11-09',
  '2014-11-14',
  '2014-11-23',
  '2014-11-24',
  '2014-11-25',
  '2014-11-26',
  '2014-11-27',
  '2014-11-28',
  '2014-11-29',
  '2014-11-30',
  '2014-12-01',
  '2014-12-02',
  '2014-12-03',
  '2014-12-04',
  '2014-12-05',
  '2014-12-06',
  '2014-12-07',
  '2014-12-08',
  '2014-12-09',
  '2014-12-10',
  '2014-12-11',
  '2014-12-12',
  '2014-12-13',
  '2014-12-14',
  '2014-12-15',
  '2014-12-16',
  '2014-12-17',
  '2014-12-18',
  '2014-12-19',
  '2014-12-21',
  '2014-12-22',
  '2014-12-23',
  '2014-12-24',
  '2014-12-25',
  '2014-12-26',
  '2014-12-27',
  '2014-12-28',
  '2014-12-29',
  '2014-12-30',
  '2014-12-31',
  '2015-01-01',
  '2015-01-02',
  '2015-01-03',
  '2015-01-04',
  '2015-01-05',
  '2015-01-06',
  '2015-01-07',
  '2015-01-08',
  '2015-01-09',
  '2015-01-10',
  '2015-01-11',
  '2015-01-12',
  '2015-01-13',
  '2015-01-14',
  '2015-01-15',
  '2015-01-16',
  '2015-01-17',
  '2015-01-18',
  '2015-01-19',
  '2015-01-20',
  '2015-01-21',
  '2015-01-22',
  '2015-01-23',
  '2015-01-24',
  '2015-01-25',
  '2015-01-26',
  '2015-01-27',
  '2015-01-28',
  '2015-01-29',
  '2015-01-30',
  '2015-01-31',
  '2015-02-01',
  '2015-02-02',
  '2015-02-03',
  '2015-02-04',
  '2015-02-05',
  '2015-02-06',
  '2015-02-07',
  '2015-02-08',
  '2015-02-09',
  '2015-02-10',
  '2015-02-11',
  '2015-02-12',
  '2015-02-13',
  '2015-02-14',
  '2015-02-15',
  '2015-02-16',
  '2015-02-17',
  '2015-02-18',
  '2015-02-19',
  '2015-02-20',
  '2015-02-21',
  '2015-02-22',
  '2015-02-23',
  '2015-02-24',
  '2015-02-25',
  '2015-02-26',
  '2015-02-27',
  '2015-02-28',
  '2015-03-01',
  '2015-03-02',
  '2015-03-03',
  '2015-03-04',
  '2015-03-05',
  '2015-03-06',
  '2015-03-07',
  '2015-03-09',
  '2015-03-10',
  '2015-03-11',
  '2015-03-12',
  '2015-03-13',
  '2015-03-14',
  '2015-03-15',
  '2015-03-16',
  '2015-03-17',
  '2015-03-18',
  '2015-03-19',
  '2015-03-20',
  '2015-03-21',
  '2015-03-22',
  '2015-03-23',
  '2015-03-24',
  '2015-03-25',
  '2015-03-26',
  '2015-03-27',
  '2015-03-28',
  '2015-03-29',
  '2015-03-30',
  '2015-03-31',
  '2015-04-01',
  '2015-04-02',
  '2015-04-03',
  '2015-04-04',
  '2015-04-05',
  '2015-04-06',
  '2015-04-07',
  '2015-04-08',
  '2015-04-09',
  '2015-04-10',
  '2015-04-11',
  '2015-04-12',
  '2015-04-13',
  '2015-04-14',
  '2015-04-15',
  '2015-04-16',
  '2015-04-17',
  '2015-04-18',
  '2015-04-19',
  '2015-04-20',
  '2015-04-21',
  '2015-04-22',
  '2015-04-23',
  '2015-04-24',
  '2015-04-25',
  '2015-04-26',
  '2015-04-27',
  '2015-04-28',
  '2015-04-29',
  '2015-04-30',
  '2015-05-01',
  '2015-05-02',
  '2015-05-03',
  '2015-05-04',
  '2015-05-05',
  '2015-05-06',
  '2015-05-07',
  '2015-05-08',
  '2015-05-09',
  '2015-05-10',
  '2015-05-11',
  '2015-05-12',
  '2015-05-13',
  '2015-05-14',
  '2015-05-15',
  '2015-05-16',
  '2015-05-17',
  '2015-05-18',
  '2015-05-19',
  '2015-05-20',
  '2015-05-21',
  '2015-05-22',
  '2015-05-23',
  '2015-05-24',
  '2015-05-25',
  '2015-05-26',
  '2015-05-27',
  '2015-05-28',
  '2015-05-29',
  '2015-05-30',
  '2015-05-31',
  '2015-06-01',
  '2015-06-02',
  '2015-06-03',
  '2015-06-04',
  '2015-06-06',
  '2015-06-07',
  '2015-06-08',
  '2015-06-09',
  '2015-06-10',
  '2015-06-11',
  '2015-06-12',
  '2015-06-13',
  '2015-06-14',
  '2015-06-15',
  '2015-06-16',
  '2015-06-17',
  '2015-06-18',
  '2015-06-19',
  '2015-06-20',
  '2015-06-21',
  '2015-06-22',
  '2015-06-24',
  '2015-06-25',
  '2015-06-26',
  '2015-06-27',
  '2015-06-28',
  '2015-06-29',
  '2015-06-30',
  '2015-07-01',
  '2015-07-02',
  '2015-07-03',
  '2015-07-04',
  '2015-07-05',
  '2015-07-06',
  '2015-07-07',
  '2015-07-09',
  '2015-07-10',
  '2015-07-11',
  '2015-07-12',
  '2015-07-13',
  '2015-07-14',
  '2015-07-15',
  '2015-07-16',
  '2015-07-17',
  '2015-07-18',
  '2015-07-19',
  '2015-07-20',
  '2015-07-21',
  '2015-07-22',
  '2015-07-23',
  '2015-07-24',
  '2015-07-25',
  '2015-07-26',
  '2015-07-27',
  '2015-07-28',
  '2015-07-29',
  '2015-07-30',
  '2015-07-31',
  '2015-08-01',
  '2015-08-02',
  '2015-08-03',
  '2015-08-04',
  '2015-08-05',
  '2015-08-06',
  '2015-08-07',
  '2015-08-08',
  '2015-08-09',
  '2015-08-10',
  '2015-08-11',
  '2015-08-12',
  '2015-08-13',
  '2015-08-14',
  '2015-08-16',
  '2015-08-17',
  '2015-08-18',
  '2015-08-19',
  '2015-08-20',
  '2015-08-21',
  '2015-08-22',
  '2015-08-23',
  '2015-08-24',
  '2015-08-25',
  '2015-08-26',
  '2015-08-27',
  '2015-08-28',
  '2015-08-29',
  '2015-08-30',
  '2015-08-31',
  '2015-09-01',
  '2015-09-02',
  '2015-09-03',
  '2015-09-04',
  '2015-09-05',
  '2015-09-06',
  '2015-09-07',
  '2015-09-08',
  '2015-09-09',
  '2015-09-10',
  '2015-09-11',
  '2015-09-12',
  '2015-09-13',
  '2015-09-14',
  '2015-09-15',
  '2015-09-16',
  '2015-09-19',
  '2015-09-20',
  '2015-09-21',
  '2015-09-22',
  '2015-09-23',
  '2015-09-24',
  '2015-09-25',
  '2015-09-26',
  '2015-09-27',
  '2015-09-28',
  '2015-09-29',
  '2015-09-30',
  '2015-10-01',
  '2015-10-02',
  '2015-10-03',
  '2015-10-04',
  '2015-10-05',
  '2015-10-06',
  '2015-10-07',
  '2015-10-08',
  '2015-10-09',
  '2015-10-10',
  '2015-10-11',
  '2015-10-12',
  '2015-10-13',
  '2015-10-14',
  '2015-10-15',
  '2015-10-16',
  '2015-10-17',
  '2015-10-18',
  '2015-10-19',
  '2015-10-20',
  '2015-10-21',
  '2015-10-22',
  '2015-10-23',
  '2015-10-24',
  '2015-10-25',
  '2015-10-26',
  '2015-10-27',
  '2015-10-28',
  '2015-10-29',
  '2015-10-30',
  '2015-10-31',
  '2015-11-01',
  '2015-11-02',
  '2015-11-03',
  '2015-11-04',
  '2015-11-05',
  '2015-11-06',
  '2015-11-07',
  '2015-11-08',
  '2015-11-09',
  '2015-11-10',
  '2015-11-11',
  '2015-11-12',
  '2015-11-13',
  '2015-11-14',
  '2015-11-15',
  '2015-11-16',
  '2015-11-17',
  '2015-11-18',
  '2015-11-19',
  '2015-11-20',
  '2015-11-21',
  '2015-11-22',
  '2015-11-23',
  '2015-11-24',
  '2015-11-25',
  '2015-11-26',
  '2015-11-28',
  '2015-11-29',
  '2015-11-30',
  '2015-12-01',
  '2015-12-02',
  '2015-12-03',
  '2015-12-04',
  '2015-12-05',
  '2015-12-06',
  '2015-12-07',
  '2015-12-08',
  '2015-12-09',
  '2015-12-10',
  '2015-12-11',
  '2015-12-12',
  '2015-12-13',
  '2015-12-14',
  '2015-12-15',
  '2015-12-17',
  '2015-12-19',
  '2015-12-20',
  '2015-12-21',
  '2015-12-22',
  '2015-12-23',
  '2015-12-24',
  '2015-12-25',
  '2015-12-26',
  '2015-12-27',
  '2015-12-28',
  '2015-12-29',
  '2015-12-30',
  '2015-12-31'])

In [7]:
stock_ids = [i for i in range(len(stock_names))]
stock_name_to_ids = dict(zip(stock_names, stock_ids))
stock_name_to_ids

{'AAPL': 0,
 'ABB': 1,
 'ABBV': 2,
 'AEP': 3,
 'AGFS': 4,
 'AMGN': 5,
 'AMZN': 6,
 'BA': 7,
 'BABA': 8,
 'BAC': 9,
 'BBL': 10,
 'BCH': 11,
 'BHP': 12,
 'BP': 13,
 'BRK-A': 14,
 'BSAC': 15,
 'BUD': 16,
 'C': 17,
 'CAT': 18,
 'CELG': 19,
 'CHL': 20,
 'CHTR': 21,
 'CMCSA': 22,
 'CODI': 23,
 'CSCO': 24,
 'CVX': 25,
 'D': 26,
 'DHR': 27,
 'DIS': 28,
 'DUK': 29,
 'EXC': 30,
 'FB': 31,
 'GD': 32,
 'GE': 33,
 'GOOG': 34,
 'HD': 35,
 'HON': 36,
 'HRG': 37,
 'HSBC': 38,
 'IEP': 39,
 'INTC': 40,
 'JNJ': 41,
 'JPM': 42,
 'KO': 43,
 'LMT': 44,
 'MA': 45,
 'MCD': 46,
 'MDT': 47,
 'MMM': 48,
 'MO': 49,
 'MRK': 50,
 'MSFT': 51,
 'NEE': 52,
 'NGG': 53,
 'NVS': 54,
 'ORCL': 55,
 'PCG': 56,
 'PCLN': 57,
 'PEP': 58,
 'PFE': 59,
 'PG': 60,
 'PICO': 61,
 'PM': 62,
 'PPL': 63,
 'PTR': 64,
 'RDS-B': 65,
 'REX': 66,
 'SLB': 67,
 'SNP': 68,
 'SNY': 69,
 'SO': 70,
 'SPLP': 71,
 'SRE': 72,
 'T': 73,
 'TM': 74,
 'TOT': 75,
 'TSM': 76,
 'UL': 77,
 'UN': 78,
 'UNH': 79,
 'UPS': 80,
 'UTX': 81,
 'V': 82,
 'VZ': 83,
 'WFC': 84,
 'WMT': 85,
 'XOM': 86}

In [ ]:
tokens_file = dataset_dir / "all_tweets_tokenized.jsonl"
bad_data_file = dataset_dir / "bad_data.jsonl"

buffer = []
buffer_size = 100_000
lines = 0


with open(json_file, "r", encoding="utf-8") as f, open(tokens_file, "w", encoding="utf-8") as o, open(bad_data_file, "w", encoding="utf-8") as b:
    for line in f:

        entry = json.loads(line)

        stock_name = entry["stock"]
        tweet = entry["tweet"]
        date = entry["date"]


        patterns = [
            rf"\${stock_name}(?=\s|$|\W)", # strict match
            rf"\${stock_name}" # loose match
        ]

        success = False
        for pattern in patterns:
            masked_tweet = re.sub(pattern, "<MASK>", tweet, flags=re.IGNORECASE)
            masked_tweet_tokenized = slot_spm.encode(masked_tweet)

            if mask_id in masked_tweet_tokenized:
                mask_idx = masked_tweet_tokenized.index(mask_id)
                success = True
                break

        if not success:
            bad_entry = {
                "stock": stock_name,
                "tweet": slot_spm.decode(masked_tweet_tokenized)
            }
            b.write(json.dumps(bad_entry) + "\n")
            continue

        # masked_tweet_tokenized = [
        #     tok if tok not in rare_tokens else unk_id
        #     for tok in masked_tweet_tokenized
        # ]


        tokenized_tweet = {
            "date": date,
            "tweet": masked_tweet_tokenized,
            "stock_id": stock_name_to_ids[stock_name],
            "mask_idx": mask_idx
        }


        buffer.append(json.dumps(tokenized_tweet))

        if len(buffer) >= buffer_size:
            o.write("\n".join(buffer) + "\n")
            lines += len(buffer)
            buffer.clear()

            print(f"{lines} lines written")

    if buffer:
        o.write("\n".join(buffer) + "\n")
        lines += len(buffer)
        print(f"{lines} lines written")

100000 lines written
119768 lines written

### Put all the data into lists

In [8]:

tweet_tokens_by_date = [[] for i in range(num_dates)]
mask_indices_by_date = [[] for i in range(num_dates)]


tweet_tokens = []
mask_indices = []
y = []

with open(tokens_file, "r") as f:
    for line in f:
        entry = json.loads(line)

        tokens = [int(tok) for tok in entry["tweet"]]
        idx = entry["mask_idx"]

        tweet_tokens.append(tokens)
        mask_indices.append(idx)
        y.append(entry["stock_id"])

        if entry["date"] in all_dates:
            date = all_dates.index(entry["date"])
            tweet_tokens_by_date[date].append(tokens)
            mask_indices_by_date[date].append(idx)

In [9]:
for i in range(5):
    print(all_dates[i] + ":", tweet_tokens_by_date[i])
    print(all_dates[i] + ":", mask_indices_by_date[i])
    print()

2014-02-19: [[18, 7, 14, 12, 10, 13, 9, 183, 49, 300, 35, 7, 3, 16, 6, 2101, 1470, 1464, 17, 257, 35, 397, 11, 1745, 48, 1800, 11, 5043, 53, 26, 2242, 2118, 1184, 368, 57, 7789, 414, 16, 1384, 820, 8], [7, 3, 35, 233, 939, 426, 381, 95, 137, 3241, 58, 22, 60, 47, 11, 180, 15, 650, 3447, 238, 33, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [749, 37, 835, 79, 2801, 82, 7, 1887, 358, 200, 876, 6, 6241, 6, 4321, 6, 29, 7, 3, 9, 431, 8], [7, 3, 276, 88, 250, 22, 401, 1920, 93, 3295, 20, 5283], [18, 7, 14, 12, 10, 13, 1072, 196, 8150, 3233, 40, 82, 157, 1725, 27, 6, 1362, 17, 6, 254, 7, 3, 9, 4634, 9, 120, 7187, 9, 5414, 9, 1525, 1228, 122, 8], [18, 7, 14, 12, 10, 13, 1072, 196, 8150, 3233, 40, 82, 157, 1725, 27, 6, 1362, 17, 6, 254, 7, 3, 9, 4634, 9, 120, 7187, 9, 5414, 9, 1525, 1228, 122, 8], [8, 367, 228, 3128, 2779, 28, 27, 60, 37, 4345, 1739, 16, 277, 256, 16, 363, 28, 23, 1242, 244, 33, 8, 6, 7476, 6, 131, 7, 3, 6, 55], [7, 3, 35, 825, 4663, 1356, 2323, 66, 798, 89, 447, 11], [18, 7, 14, 12, 10, 13, 1072, 196, 8150, 3233, 40, 82, 157, 1725, 27, 6, 1362, 17, 6, 254, 7, 3, 9, 4634, 9, 120, 7187, 9, 5414, 9, 1525, 1228, 122, 8], [9, 63, 597, 11, 335, 105, 184, 6, 755, 6, 4568, 6, 433, 7, 3, 9, 1028, 8], [7, 3, 221, 100, 7, 14, 12, 10, 13, 8, 7, 19, 11], [7, 3, 221, 100, 7, 14, 12, 10, 13, 8, 7, 19, 11], [18, 7, 14, 12, 10, 13, 4851, 967, 46, 1066, 6864, 7099, 57, 7, 15, 94, 15, 229, 8, 7, 3], [7, 3, 68, 334, 25, 82, 1753, 4140, 35, 8, 8], [7, 14, 12, 10, 13, 5278, 2573, 11, 354, 167, 22, 1719, 3088, 41, 7300, 7, 3, 1613, 455, 52, 1017, 34, 6456, 46, 252, 1647, 11, 394, 28, 222, 445, 330, 70, 238, 811, 15], [18, 7, 14, 12, 10, 13, 1072, 196, 8150, 3233, 40, 82, 157, 1725, 27, 6, 1362, 17, 6, 254, 7, 3, 9, 4634, 9, 120, 7187, 9, 5414, 9, 1525, 1228, 122, 8], [7, 3, 297, 35, 797, 150, 25, 906, 6242, 1892, 272, 901, 11, 506, 20, 151, 202, 5527, 797, 150, 1023, 8], [288, 28, 15, 82, 9, 1076, 2172, 460, 41, 1622, 765, 143, 15, 44, 945, 76, 40, 162, 236, 1313, 697, 1519, 44, 8, 6, 51, 6, 29, 7, 3], [7, 3, 1391, 20, 2721, 57, 4104, 3311, 304, 2015, 1248, 1859, 1749, 8], [1242, 242, 2974, 70, 5768, 1822, 20, 1162, 1263, 8, 6, 74, 6, 38, 1046, 15, 6, 1381, 7, 3], [193, 113, 45, 36, 111, 114, 264, 257, 154, 733, 26, 1729, 228, 6, 74, 413, 317, 356, 26, 7, 3, 4161, 69, 4478, 15, 114, 8], [709, 475, 16, 3114, 222, 125, 25, 11, 330, 842, 81, 91, 7298, 15, 3224, 2270, 179, 194, 34, 8, 49, 7, 3, 8], [7, 3, 221, 100, 2695, 2048, 1315, 16, 8, 1030, 666, 101, 697, 2126, 1471, 142, 81, 138, 16, 72, 265, 797, 150, 69, 28, 15, 359, 3330, 11], [8, 367, 228, 3128, 2779, 28, 27, 60, 37, 4345, 1739, 16, 277, 256, 16, 363, 28, 23, 1242, 244, 33, 8, 6, 7476, 7, 3, 6, 19, 6, 55], [7, 3, 11, 35, 5655, 674, 792, 4407, 34, 2585, 703, 8], [851, 1554, 711, 1164, 319, 1816, 705, 38, 2866, 57, 285, 34, 421, 17, 195, 1835, 176, 1613, 2000, 1475, 812, 7, 3, 8], [7, 3, 285, 34, 421, 173, 48, 67, 53, 90, 16, 202, 28, 15, 201, 27, 285, 34, 421, 39, 8], [7, 3, 287, 723, 737, 884, 43, 37, 994, 5206, 321, 737, 1230, 11, 1781, 200, 737, 1230, 11, 1296, 287, 737, 2164, 11, 316, 392, 737, 1230, 11, 1280, 360, 737, 1556, 1745, 1544, 8], [563, 1485, 517, 62, 408, 1799, 2486, 408, 26, 24, 3488, 161, 3, 2407, 17, 7, 5571, 498, 156, 43, 1380, 229, 743, 75, 17, 40, 1799, 238, 863, 619, 2029, 493, 354, 457, 1200, 129, 354, 871, 15, 17, 2116, 81, 1463, 145, 568, 146, 229, 17, 568, 2113, 39], [375, 2754, 3398, 3245, 193, 5965, 6062, 70, 83, 170, 2548, 2341, 15, 170, 1337, 15, 711, 255, 7, 3, 2105, 30, 2757, 8, 48, 1532, 165, 605, 170, 7, 14, 12, 10, 13], [7, 3, 730, 47, 11, 3924, 15, 61, 425, 27, 621, 2293, 408, 173, 11, 48, 4685, 53, 8], [639, 76, 71, 242, 160, 17, 1670, 222, 145, 2244, 1020, 999, 2215, 240, 239, 100, 278, 46, 105, 96, 426, 1540, 11, 7, 3, 8], [335, 24, 201, 7, 3, 6, 4562, 6, 142, 75, 6, 2332, 810, 8], [7, 3, 439, 11, 38, 11, 38, 11, 20, 379, 669, 26, 1093, 2141, 6107, 180, 8], [546, 28, 15, 123, 3109, 5283, 267, 137, 267, 17, 243, 41, 69, 25, 214, 39, 8, 7, 3, 9, 2702], [7, 3, 35, 41, 4394, 24, 320, 15, 516, 1069, 565, 39, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [196, 2010, 27, 7, 3, 8], [7, 3, 35, 546, 2100, 15, 3165, 3322, 2704, 15, 27, 685, 2673, 1012, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [6, 1750, 6, 83, 7, 3, 8], [5650, 16, 466, 8236, 57, 6, 1754, 8, 6, 102, 7, 3, 6, 526], [1000, 41, 185, 342, 15, 7, 2826, 492, 7, 39, 15, 73, 3682, 919, 39, 3], [1313, 3338, 73, 556, 44, 9, 289, 3338, 1417, 418, 2834, 9, 54, 11, 54, 11, 54, 9, 3, 9, 258, 1105, 9, 153, 4195, 52, 9, 3915, 304, 2809, 8], [162, 89, 391, 26, 7, 3, 6, 4025, 6, 1100, 6, 895, 251, 8], [639, 46, 156, 1191, 26, 6, 1484, 23, 6, 1690, 6, 259, 7, 3, 68, 1036, 8], [9, 42, 20, 214, 6, 5499, 6, 4464, 6, 1653, 7, 3, 9, 1003, 8], [60, 1657, 7, 15, 94, 15, 229, 4851, 6864, 7099, 7, 3, 9, 661, 8], [7, 3, 3407, 24, 3275, 26, 72, 265, 106, 59, 11], [327, 447, 1057, 26, 7, 3, 143, 88, 3959, 69, 257, 11, 4708, 337, 11], [7, 14, 12, 10, 13, 7, 14, 12, 10, 13, 1808, 17, 7, 3, 447, 1353, 27, 2965, 2420, 11, 1000, 41, 6, 51, 2826, 143, 50, 991, 394, 107, 92, 447, 146, 15, 330, 70, 400, 568], [104, 14, 12, 10, 13, 104, 14, 12, 10, 13, 110, 7, 3, 22, 1739, 5738, 71, 1353, 130, 65, 326, 1245, 3677, 160, 1691, 39, 3682, 65, 326, 1245, 601, 363, 28, 23, 3928, 213, 27, 7, 1564, 69, 6324], [18, 7, 14, 12, 10, 13, 7, 3, 20, 1235, 1353, 27, 240, 2965, 291], [18, 7, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [18, 7, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [7, 3, 257, 132, 40, 373, 3453, 11], [18, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [18, 7, 14, 12, 10, 13, 2524, 25, 38, 5644, 170, 7, 3, 9, 661, 6977, 85, 35, 258, 859, 5353, 3399, 212, 3215, 2111, 566, 290, 4249, 1079, 25, 354, 1151, 170, 1353, 966, 2965, 43, 48, 3538, 384, 25, 38, 5644, 53, 33], [18, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [110, 447, 1353, 27, 2965, 4463, 7, 3, 8], [3877, 145, 406, 406, 7, 14, 12, 10, 13, 746, 16, 110, 20, 61, 1353, 27, 240, 2965, 291, 568, 40, 49, 7, 3, 476], [18, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3, 1685, 229, 2299, 17, 1471, 4013, 2783, 1076, 605, 15, 651, 307, 3203, 4533, 15, 170, 1353, 11], [1031, 18, 16, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [18, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [68, 363, 28, 23, 151, 209, 7, 3, 210, 6597, 91, 1353, 3008, 11, 11, 480, 2932, 3450, 1733, 17, 243, 202, 487, 39, 68, 4662, 69, 210, 92, 393, 2078, 58, 11, 11, 480, 5192, 7, 1570, 4618, 11], [18, 7, 14, 12, 10, 13, 3877, 5324, 2299, 44, 389, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [18, 7, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 7, 3, 521, 15, 2965, 43, 27, 367, 1230, 15, 1679, 23, 1568, 202, 28, 15, 5640, 11, 1710, 36, 202, 39, 2492, 11, 110, 521, 15, 2965, 43, 27, 367, 733, 215, 1353, 11], [8024, 93, 7, 3, 3044, 748, 291, 39, 11, 33, 2436, 50, 105, 34, 186, 5296, 3422], [18, 7, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 5422, 7, 3, 49, 3093, 245, 1633, 11, 1394, 41, 1174, 1797, 11, 224, 1837, 328, 1059, 694, 4276, 2080, 165, 301, 3166], [18, 7, 14, 12, 10, 13, 110, 1535, 1739, 5738, 71, 1353, 17, 66, 61, 27, 6, 174, 43, 22, 568, 1414, 1964, 43, 22, 110, 194, 7, 3, 6, 31], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 7, 3, 6295, 15, 3125, 26, 90, 141, 110, 66, 61, 1353, 4060, 1152, 46, 685, 8, 8], [1198, 17, 350, 4577, 17, 938, 28, 15, 193, 1833, 11, 141, 1959, 1392, 28, 23, 538, 447, 76, 7, 3, 49], [18, 7, 14, 12, 10, 13, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 739, 16, 8, 7, 3], [18, 7, 14, 12, 10, 13, 389, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3, 476, 492, 7, 3934, 44], [18, 7, 14, 12, 10, 13, 90, 240, 1353, 6, 908, 291, 1632, 2055, 110, 194, 257, 3125, 22, 245, 37, 4133, 196, 11, 8, 7, 3], [746, 16, 7, 14, 12, 10, 13, 20, 1235, 7, 14, 12, 10, 13, 27, 240, 2965, 291, 11, 541, 7, 3], [18, 7, 14, 12, 10, 13, 194, 34, 110, 1218, 233, 3590, 20, 6, 2624, 11, 1204, 22, 245, 37, 4133, 196, 245, 90, 34, 1353, 383, 11, 8, 7, 3], [1377, 2660, 41, 209, 24, 1353, 1929, 264, 4295, 57, 7, 3, 7, 11], [18, 7, 14, 12, 10, 13, 18, 7, 14, 12, 10, 13, 71, 2154, 34, 1353, 17, 7, 3, 8031, 58, 97, 1304, 34, 24, 771, 4060, 1152, 46, 88, 48, 4249, 590, 30, 46, 20, 72, 221, 53, 8], [2682, 20, 159, 693, 44, 7, 3, 6, 64, 6, 226, 6, 203, 6, 42], [110, 47, 7, 16, 7, 3253, 3230, 1865, 41, 3551, 142, 1330, 2660, 58, 27, 7, 2402, 1633, 22, 627, 423, 5407, 590, 28, 15, 1701, 8, 7, 3], [18, 7, 14, 12, 10, 13, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 739, 16, 8, 7, 3], [18, 7, 14, 12, 10, 13, 746, 16, 110, 28, 15, 5905, 2965, 291, 1353, 2154, 16, 1964, 43, 22, 7, 3, 194, 17, 6, 174, 43, 22, 568, 11, 8], [18, 7, 14, 12, 10, 13, 110, 49, 4494, 26, 90, 34, 1353, 383, 33, 7, 3, 8, 8], [18, 7, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [18, 7, 14, 12, 10, 13, 110, 49, 4494, 26, 90, 34, 1353, 383, 33, 7, 3, 8, 8], [18, 7, 14, 12, 10, 13, 110, 447, 1353, 27, 2965, 43, 8, 7, 3], [1838, 3935, 2491, 9917, 2583, 608, 572, 3073, 2970, 1838, 1495, 2490, 9917, 2556, 2971, 8567, 7, 1462, 458, 2491, 470, 3073, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [18, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [9, 661, 7, 3, 1837, 9, 6059, 27, 6, 908, 43], [18, 7, 14, 12, 10, 13, 110, 49, 4494, 26, 90, 34, 1353, 383, 33, 7, 3, 8, 8], [3541, 57, 7, 14, 12, 10, 13, 2110, 39, 2327, 339, 2116, 323, 1353, 132, 698, 962, 7, 3, 9, 6059, 9, 4356, 5497], [7, 2592, 18, 7, 14, 12, 10, 13, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 739, 16, 8, 7, 3], [18, 7, 14, 12, 10, 13, 18, 7, 14, 12, 10, 13, 110, 48, 3, 53, 5037, 1353, 27, 89, 301, 486, 28, 15, 814, 64, 53, 88, 361, 57, 241, 729, 169, 11], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [7, 14, 12, 10, 13, 1235, 15, 7, 14, 12, 10, 13, 27, 2965, 291, 8, 7, 3], [820, 3697, 170, 423, 2782, 7, 774, 3215, 25, 2061, 7, 3, 796, 3667, 1792, 255, 355, 1030, 3216, 1402], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 90, 240, 1353, 6, 908, 291, 1632, 2055, 110, 194, 257, 3125, 22, 245, 37, 4133, 196, 11, 8, 7, 3], [18, 7, 14, 12, 10, 13, 90, 240, 1353, 6, 908, 291, 1632, 2055, 110, 194, 257, 3125, 22, 245, 37, 4133, 196, 11, 8, 7, 3], [236, 260, 26, 6, 3521, 7, 3, 6, 30, 62, 6, 897, 388, 95, 8], [645, 689, 215, 7, 16, 821, 683, 176, 68, 1012, 20, 4849, 6, 316, 2305, 462, 22, 3513, 17, 1019, 8, 7, 3], [749, 37, 835, 79, 2801, 82, 7, 1887, 358, 200, 876, 6, 6241, 6, 4321, 7, 3, 6, 19, 9, 431, 8], [40, 631, 1816, 7, 3, 705, 127, 2709, 33], [7, 3, 121, 714, 3663, 15, 6, 2539, 462, 40, 4367, 15, 323, 2640, 7, 3324, 16, 121, 714, 3663, 15, 6, 2539, 462, 40, 108, 33, 8], [286, 27, 24, 201, 1081, 165, 150, 6, 80, 6, 6751, 6, 1690, 7, 3, 313, 117, 8], [22, 24, 7, 3, 648, 717, 435, 396, 27, 132, 11, 1204], [18, 7, 14, 12, 10, 13, 121, 396, 7, 5350, 3124, 37, 4215, 518, 367, 28, 5661, 4083, 15, 11, 28, 28, 789, 17, 1463, 145, 44, 369, 9, 1883, 229, 27, 7, 14, 12, 10, 13, 7, 3, 7730, 8], [1096, 125, 3076, 7347, 141, 78, 4958, 30, 20, 2742, 5882, 812, 34, 121, 5629, 16, 7, 15, 11, 280, 11, 17, 5633, 6439, 17, 5015, 313, 17, 683, 6143, 1761, 40, 8159, 7, 432, 3661, 11, 7, 3], [288, 28, 15, 82, 9, 1076, 2172, 460, 41, 1622, 765, 143, 15, 44, 945, 76, 40, 162, 236, 1313, 697, 1519, 44, 8, 6, 51, 7, 3, 6, 19], [286, 20, 1682, 2983, 150, 6, 3051, 7, 3, 6, 142, 30, 1099, 6, 543, 9, 936, 8], [7, 3, 35, 230, 16, 2125, 248, 2899, 15, 116, 2343, 1024, 141, 619, 46, 1243, 4492, 7, 3544, 697, 2047, 54, 2505, 1697, 33, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [196, 2010, 27, 7, 3, 8], [7, 3, 35, 464, 16, 1000, 180, 15, 1096, 125, 8207, 39, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 35, 303, 7, 1973, 1590, 16, 530, 65, 45, 36, 530, 378, 11, 355, 138, 6944, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 202, 7313, 15, 26, 604, 573, 1763, 27, 426, 8], [162, 89, 391, 26, 7, 3, 6, 4967, 6, 38, 52, 438, 6, 2384, 313, 117, 8], [7, 3, 1246, 2408, 93, 621, 11, 52, 11, 767, 2401, 22, 7, 2570, 7, 2572, 8], [7, 3, 836, 37, 942, 5077, 6136, 5264, 7512, 2529, 7, 3136, 1256, 2622, 174, 1384, 194, 48, 5540, 53, 8], [7, 3, 35, 1867, 1908, 474, 1595, 22, 25, 2577, 1561, 71, 4006, 4540, 238, 33, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 1867, 1908, 4799, 68, 43, 38, 37, 791, 662, 6234, 46, 1598, 3164, 46, 2373, 27, 59, 8], [7, 14, 12, 10, 13, 217, 1013, 17, 243, 69, 264, 7, 3, 367, 15, 727, 616, 23, 33], [7, 3, 2333, 1361, 27, 640, 62, 408, 3435, 732, 28, 15, 968, 8], [7, 3, 1538, 111, 1243, 697, 3600, 2174, 319, 20, 2100, 1052, 1611, 3942, 7810, 1424, 160, 59, 8], [7, 3, 3405, 3924, 15, 104, 929, 130, 425, 27, 1171, 65, 45, 36, 146, 48, 204, 53, 8], [7, 3, 202, 60, 210, 1357, 93, 288, 40, 121, 8], [7, 14, 12, 10, 13, 7, 14, 12, 10, 13, 1808, 17, 6, 21, 447, 1353, 27, 2965, 2420, 11, 1000, 41, 7, 3, 2826, 143, 50, 991, 394, 107, 92, 447, 146, 15, 330, 70, 400, 568], [288, 28, 15, 82, 9, 1076, 2172, 460, 41, 1622, 765, 143, 15, 44, 945, 76, 40, 162, 236, 1313, 697, 1519, 44, 8, 7, 3, 6, 29, 6, 19], [2240, 17, 7, 2745, 1090, 394, 28, 222, 4024, 5823, 1996, 46, 218, 1519, 15, 34, 244, 851, 182, 7, 5019, 1042, 7, 3, 6, 2745], [7, 3, 35, 5810, 7582, 6629, 15, 1569, 462, 20, 724, 953, 1577, 5717, 22, 2988, 698, 40, 33, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [286, 27, 24, 201, 1081, 165, 150, 7, 3, 6, 6751, 6, 1690, 6, 29, 313, 117, 8], [7, 3, 239, 3428, 1613, 7652, 176, 169, 37, 6980, 46, 6042, 1255, 5547, 15, 17, 2421, 15, 8], [898, 79, 20, 159, 6, 2961, 6, 4579, 6, 175, 83, 7, 3, 9, 1011, 148, 8], [18, 7, 14, 12, 10, 13, 247, 91, 6521, 20, 392, 26, 6047, 6883, 15, 27, 7, 1554, 86, 493, 7, 7148, 3088, 8, 9, 4292, 9, 7148, 7, 3], [7, 3, 161, 23, 65, 45, 36, 24, 6016, 3328, 37, 2016, 8], [185, 79, 20, 159, 7, 3, 6, 4614, 6, 5620, 6, 4328, 9, 99, 8], [7, 3, 82, 57, 113, 45, 36, 23, 20, 617, 493, 3914, 5521, 468, 2332, 4307, 27, 2431, 71, 972, 3807, 26, 265, 3060, 8], [807, 2485, 2106, 7, 1238, 272, 3704, 2833, 138, 4796, 7914, 247, 821, 20, 145, 653, 23, 2339, 91, 557, 406, 2485, 757, 25, 125, 7, 30, 6690, 3, 807, 2485, 3006, 7, 1252, 3258, 497, 1195, 5546, 621, 238, 7, 101, 1135, 525, 1041, 4653, 673, 4834, 2754, 7914, 83, 4231, 83, 2485, 757], [18, 7, 14, 12, 10, 13, 7, 14, 12, 10, 13, 7, 14, 12, 10, 13, 1679, 846, 307, 4861, 438, 839, 468, 3720, 3720, 3, 919, 120], [7, 3, 49, 723, 737, 884, 43, 37, 994, 5206, 321, 737, 163, 8210, 200, 737, 163, 8210, 287, 737, 1966, 5311, 392, 737, 1966, 5480, 360, 6329, 1190, 1105, 2709, 8], [7, 3, 463, 28, 15, 299, 35, 296, 2897, 173, 48, 4971, 634, 5020, 8159, 830, 165, 2842, 3010, 743, 59, 8], [7, 3, 35, 202, 180, 15, 201, 27, 5655, 674, 792, 39, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 76, 15, 4953, 15, 497, 1551, 390, 41, 2026, 5306, 15, 27, 1241, 698, 34, 2669, 3440, 8], [2264, 3542, 65, 45, 36, 6429, 23, 3568, 17, 8267, 125, 5993, 40, 992, 1430, 5977, 1307, 23, 1436, 23, 15, 59, 7, 3, 8], [7, 3, 1293, 79, 16, 945, 1062, 3258, 4996, 518, 513, 11, 17, 2833, 1427, 617, 215, 17, 2930, 513, 17, 40, 59, 8], [7, 3, 9, 4904, 1468, 1024, 2841, 34, 3615, 194, 1137, 20, 92, 3919, 20, 9, 1985, 83, 73, 1076, 1824, 8], [7, 3, 807, 3965, 37, 540, 336, 7, 2989, 3241, 46, 28, 57, 696, 34, 6031, 5044, 1902], [7, 3, 7, 7842, 857, 2022, 3891, 493, 39, 3830, 1107, 20, 337, 17, 602, 37, 540, 8], [5650, 16, 466, 8236, 57, 6, 1754, 8, 7, 3, 6, 139, 6, 526]]
2014-02-19: [12, 1, 18, 1, 21, 21, 27, 1, 21, 14, 1, 1, 20, 1, 16, 21, 1, 29, 1, 19, 20, 22, 1, 25, 1, 22, 1, 1, 12, 19, 1, 24, 4, 1, 18, 1, 4, 1, 5, 11, 15, 18, 5, 13, 11, 11, 1, 5, 13, 12, 7, 17, 17, 1, 19, 12, 19, 7, 23, 19, 21, 19, 7, 26, 17, 35, 7, 3, 17, 35, 35, 8, 28, 35, 35, 7, 20, 19, 24, 26, 21, 30, 11, 18, 6, 28, 19, 21, 16, 17, 16, 14, 35, 19, 3, 16, 18, 21, 14, 35, 17, 11, 35, 26, 26, 6, 22, 16, 4, 1, 14, 3, 38, 38, 27, 8, 1, 4, 1, 1, 1, 5, 1, 1, 1, 1, 12, 1, 1, 1, 1, 23, 25, 23, 1, 8, 1, 12, 29, 1, 5, 1, 28, 25, 1, 1, 1, 1, 23, 1, 1, 1, 1, 9]


### Pad the token data and shuffle

In [10]:
max_len = max(len(tweet) for tweet in tweet_tokens)


X = [tweet + [pad_id] * (max_len - len(tweet))
    for tweet in tweet_tokens]


X = torch.tensor(X, dtype=torch.long)
y = torch.tensor(y, dtype=torch.long)
mask_indices = torch.tensor(mask_indices, dtype=torch.long)

perm = torch.randperm(X.size(0))
X, y, mask_indices = X[perm], y[perm], mask_indices[perm]

X, X.shape, y, y.shape, mask_indices, mask_indices.shape

(tensor([[  25, 1091, 1369,  ...,    4,    4,    4],
         [  18,    7,   14,  ...,    4,    4,    4],
         [  18,    7,   14,  ...,    4,    4,    4],
         ...,
         [  78,   50,    7,  ...,    4,    4,    4],
         [ 184,  121,   41,  ...,    4,    4,    4],
         [   6, 1330,   49,  ...,    4,    4,    4]]),
 torch.Size([119768, 147]),
 tensor([ 8, 59, 73,  ..., 26,  0, 18]),
 torch.Size([119768]),
 tensor([24, 20, 10,  ...,  7, 14, 20]),
 torch.Size([119768]))

In [11]:
# (num_dates, num_tweets_for_that_date, seq_len)
X_by_date = [
    torch.tensor(
        [tweet + [pad_id] * (max_len - len(tweet)) for tweet in tweet_tokens_by_date[d]],
        dtype=torch.long
    )
    for d in range(num_dates)
]

mask_indices_by_date = [
    torch.tensor(mask_indices_by_date[d], dtype=torch.long)
    for d in range(num_dates)
]

X_by_date[0], X_by_date[0].shape, mask_indices_by_date[0], mask_indices_by_date[0].shape

(tensor([[  18,    7,   14,  ...,    4,    4,    4],
         [   7,    3,   35,  ...,    4,    4,    4],
         [ 749,   37,  835,  ...,    4,    4,    4],
         ...,
         [   7,    3,  807,  ...,    4,    4,    4],
         [   7,    3,    7,  ...,    4,    4,    4],
         [5650,   16,  466,  ...,    4,    4,    4]]),
 torch.Size([154, 147]),
 tensor([12,  1, 18,  1, 21, 21, 27,  1, 21, 14,  1,  1, 20,  1, 16, 21,  1, 29,
          1, 19, 20, 22,  1, 25,  1, 22,  1,  1, 12, 19,  1, 24,  4,  1, 18,  1,
          4,  1,  5, 11, 15, 18,  5, 13, 11, 11,  1,  5, 13, 12,  7, 17, 17,  1,
         19, 12, 19,  7, 23, 19, 21, 19,  7, 26, 17, 35,  7,  3, 17, 35, 35,  8,
         28, 35, 35,  7, 20, 19, 24, 26, 21, 30, 11, 18,  6, 28, 19, 21, 16, 17,
         16, 14, 35, 19,  3, 16, 18, 21, 14, 35, 17, 11, 35, 26, 26,  6, 22, 16,
          4,  1, 14,  3, 38, 38, 27,  8,  1,  4,  1,  1,  1,  5,  1,  1,  1,  1,
         12,  1,  1,  1,  1, 23, 25, 23,  1,  8,  1, 12, 29,  1,  5,  1, 28, 25,
          1,  1,  1,  1, 23,  1,  1,  1,  1,  9]),
 torch.Size([154]))

### Train/val/test split

In [ ]:
data_len = len(y)

train_end = int(data_len * 0.90)
val_end = int(data_len * 1.00)

X_train, y_train, mask_train = X[ : train_end], y[ : train_end], mask_indices[ : train_end]
X_val, y_val, mask_val = X[train_end : val_end], y[train_end : val_end], mask_indices[train_end : val_end]
# X_test, y_test, mask_test = X[val_end : ], y[val_end : ], mask_indices[val_end : ]

print(f"X_train shape: {X_train.shape}. y_train shape: {y_train.shape}")
print(f"X_val shape: {X_val.shape}. y_val shape: {y_val.shape}")
# print(f"X_test shape: {X_test.shape}. y_test shape: {y_test.shape}")

mask_train.shape, mask_val.shape #, mask_test.shape

X_train shape: torch.Size([107791, 147]). y_train shape: torch.Size([107791])
X_val shape: torch.Size([11977, 147]). y_val shape: torch.Size([11977])

(torch.Size([107791]), torch.Size([11977]))

### Datasets

In [ ]:
class SLOTTokensDataset(Dataset):
    def __init__(self, x, y, mask_idx):
        self.x = x
        self.y = y
        self.mask_idx = mask_idx

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx], self.mask_idx[idx]

In [ ]:
train_dataset = SLOTTokensDataset(X_train, y_train, mask_train)
val_dataset = SLOTTokensDataset(X_val, y_val, mask_val)
# test_dataset = SLOTTokensDataset(X_test, y_test, mask_test)

train_dataset[0]

(tensor([  25, 1091, 1369,   68,   28,   54,  883, 4367,   15,   26,   37,    6,
           64,   17,    6, 1164,   17,    6, 4474,   17,    6, 4895,   17,    7,
            3,   17,    6, 2241,   11,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4]),
 tensor(8),
 tensor(24))

In [ ]:
train_size = int(0.5 * len(train_dataset))
val_size = int(0.5 * len(val_dataset))


train_subset, _ = random_split(train_dataset, [train_size, len(train_dataset) - train_size])
val_subset, _ = random_split(val_dataset, [val_size, len(val_dataset) - val_size])

len(train_subset), len(val_subset)

(53895, 5988)

### Model Definition

In [12]:

class StockIdentification(nn.Module):
    def __init__(self, num_stocks, embd_size, hidden_size, vocab_size, dropout, temp):
        super().__init__()
        self.H = hidden_size
        self.temp = temp


        self.stock_embd = nn.Embedding(num_embeddings=num_stocks, embedding_dim=2*hidden_size)


        self.token_embd = nn.Embedding(num_embeddings=vocab_size,
                                       embedding_dim=embd_size,
                                       padding_idx=pad_id)


        self.bi_lstm = nn.LSTM(
            input_size=embd_size,
            hidden_size=hidden_size,
            bidirectional=True,
            batch_first=True,
        )

        self.dropout = nn.Dropout(dropout)

        self.init_weights()

    def init_weights(self):
        nn.init.normal_(self.token_embd.weight, mean=0.0, std=0.01)
        nn.init.normal_(self.stock_embd.weight, mean=0.0, std=0.01)

        for name, param in self.bi_lstm.named_parameters():
            if "bias" in name:
                nn.init.zeros_(param)
                # set forget gate bias to 1
                # [i, f, g, o]
                param.data[self.H : 2*self.H].fill_(1.0)
            elif "weight_ih" in name:
                nn.init.kaiming_normal_(param)
            elif "weight_hh" in name:
                nn.init.orthogonal_(param)


    def forward(self, x, mask_indices):
        # x: (B, T)
        # mask_indices: (B,). The index of the <MASK> token for each tweet
        batch_size = x.size(0)
        token_embs = self.token_embd(x) # (B, T, embd_size)
        token_embs = self.dropout(token_embs)

        seq_lengths = (x != pad_id).sum(dim=-1).to("cpu")
        packed_token_embs = pack_padded_sequence(token_embs, seq_lengths, batch_first=True, enforce_sorted=False)

        # output: (B, T, 2*hidden_size)
        # h_n, c_n : (2*num_layers, B, hidden_size)
        output, (h_n, c_n) = self.bi_lstm(packed_token_embs)

        output, _ = pad_packed_sequence(output, batch_first=True)

        output = self.dropout(output)

        h_e = output[torch.arange(batch_size), mask_indices] # (B, 2*hidden_size)

        h_s = self.stock_embd.weight # (num_stocks, 2*hidden_size)
        h_e = F.normalize(h_e, dim=-1)
        h_s = F.normalize(h_s, dim=-1)
        logits = torch.matmul(h_e, h_s.T) #  (B, 2*hidden_size) @ (2*hidden_size, num_stocks) -> (B, num_stocks)


        return logits / self.temp, h_e, h_s

### Evaluation Functions

In [ ]:
stock_id_to_name = {v: k for k, v in stock_name_to_ids.items()}

stock_queries = ["AAPL", "FB", "BA", "BAC"]
stock_query_ids = [stock_name_to_ids[name] for name in stock_queries]

In [ ]:
tweet_files_stocks = [tweet.parent.name for tweet in tweet_files_list]
stock_counts = Counter(tweet_files_stocks)

stock_counts = torch.tensor([value for value in stock_counts.values()], dtype=torch.long)
stock_counts = stock_counts.to(device)

N = stock_counts.sum()
inv_freq = N / stock_counts
weights = torch.log1p(inv_freq)
weights = weights / weights.mean()
weights

tensor([0.7389, 1.1751, 0.8591, 1.0505, 1.6898, 0.8491, 0.7453, 0.8261, 0.8199,
        0.7714, 1.1916, 1.5983, 0.9514, 0.8787, 1.5644, 1.4985, 1.0618, 0.7638,
        0.8325, 0.8124, 1.0836, 1.0068, 0.8787, 1.3758, 0.7979, 0.8165, 0.7540,
        1.0836, 0.7962, 1.0179, 1.0078, 0.7399, 0.9836, 0.7882, 0.7432, 0.8452,
        1.0039, 1.3697, 1.1417, 1.1992, 0.7800, 0.8052, 0.7840, 0.8095, 0.9309,
        0.8662, 0.8055, 0.9605, 0.8977, 0.8954, 0.8371, 0.7546, 1.0296, 1.3420,
        0.9793, 0.8752, 1.0618, 0.7815, 0.9069, 0.8172, 0.8577, 1.4402, 0.9898,
        1.0697, 1.2761, 1.8615, 1.1966, 0.9198, 1.3884, 1.0158, 0.9810, 1.6389,
        1.1436, 0.7422, 1.0554, 1.0822, 1.1065, 1.2124, 1.1684, 0.8866, 0.9567,
        0.9256, 0.8063, 0.8199, 0.8289, 0.8055, 0.7918], device='cuda:0')

In [ ]:
def evaluate(logits, stock_labels):
    # stock_labels: (B,)
    loss = F.cross_entropy(logits, stock_labels, weight=weights)

    stock_pred = torch.argmax(logits, dim=-1) # (B,)
    acc = (stock_pred == stock_labels).float().mean()

    return loss, acc

In [ ]:
def stock_cosine_similarities(model):

    h_s = model.stock_embd.weight # (num_stocks, embd_size)

    h_s_normalized = h_s / h_s.norm(dim=1, keepdim=True)
    h_s_sim = h_s_normalized @ h_s_normalized.T # (num_stocks, embd_size) @ (embd_size, num_stocks) -> (num_stocks, num_stocks)

    # n = h_s_sim.size(0)
    h_s_sim.fill_diagonal_(float("-inf")) # h_s_sim[i][i] = -inf

    h_s_sim = h_s_sim[stock_query_ids] # (4, num_stocks)
    _, top3_indices = torch.topk(h_s_sim, k=3, dim=-1) # (4, 3)


    for query_idx, query in enumerate(stock_queries):
        print(f"\n{query}: ", end="")
        for neigh_idx in top3_indices[query_idx]:
            print(stock_id_to_name[int(neigh_idx.item())], end=", ")


def tweet_embedding_quality(model):

    tweet1 = "<MASK> iphone 6s spec leaks look good. excited. might even buy one." # $AAPL
    tweet2 = "rt AT_USER <MASK> $pep $dps $mnst traditional soft drinks in decline." # $KO

    eval_X = [slot_spm.encode(tweet1), slot_spm.encode(tweet2)]

    max_len = max(len(tweet) for tweet in eval_X)

    eval_X = [tweet + [pad_id] * (max_len - len(tweet)) for tweet in eval_X]

    eval_mask_indices = torch.tensor([eval_X[0].index(mask_id), eval_X[1].index(mask_id)])
    eval_X = torch.tensor(eval_X, dtype=torch.long)

    eval_X, eval_mask_indices = eval_X.to(device), eval_mask_indices.to(device)
    eval_logits, _, _ = model(eval_X, eval_mask_indices)

    eval_preds = F.softmax(eval_logits, dim=-1)
    _, eval_top3_indices = torch.topk(eval_preds, k=3, dim=-1)

    for i, stock in enumerate(eval_top3_indices):
        print()
        for pred in stock:
            print(f"{stock_id_to_name[pred.item()]}: {eval_preds[i][pred.item()].item():.2%}", end = " | ")

### Training Loop

In [ ]:

num_epochs = 50

def objective(trial):

    torch.manual_seed(42)
    torch.cuda.manual_seed(42)

    lr = 0.00248
    batch_size = 256
    embd_size = 128
    hidden_size = 254

    # lr = trial.suggest_float("lr", 1e-5, 1e-2, log=True)
    # batch_size = trial.suggest_categorical("batch_size", [64, 128, 256, 512])
    # embd_size = trial.suggest_categorical("embd_size", [64, 128, 256])
    # hidden_size =  trial.suggest_int("hidden_size", 32, 256)
    # dropout = trial.suggest_float("dropout", 0.0, 0.5)
    # temp = trial.suggest_float("temp", 0.1, 1.0)

    dropout = 0.439
    temp = 0.13356

    # dropout = 0.1
    # temp = 0.25

    wandb.init(
        project="stock_identification_final_test",
        name=f"trial_{trial.number}",
        config={
            "lr": lr,
            "batch_size": batch_size,
            "embd_size": embd_size,
            "hidden_size": hidden_size,
            "dropout": dropout,
            "temp": temp,
            "dataset": "ACL18"
        },
    )

    model = StockIdentification(
        num_stocks=num_stocks,
        embd_size=embd_size,
        hidden_size=hidden_size,
        vocab_size=vocab_size,
        dropout=dropout,
        temp=temp,
    )

    model = model.to(device)



    optimizer = torch.optim.AdamW(params = model.parameters(), lr=lr, weight_decay=1e-3)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(optimizer, T_0=10, T_mult=2, eta_min=1e-6)
    # scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer=optimizer, T_max=num_epochs, eta_min=1e-6)

    train_dataloader = DataLoader(train_subset, batch_size, shuffle=True)
    val_dataloader = DataLoader(val_subset, batch_size, shuffle=False)


    best_val_acc = 0.0

    for epoch in range(num_epochs):
        train_loss = 0.0
        train_acc = 0.0


        model.train()
        for i, (X, y, mask_indices) in enumerate(train_dataloader):
            X, y, mask_indices = X.to(device), y.to(device).to(torch.long), mask_indices.to(device)


            logits, _, _ = model(X, mask_indices) # (B, num_stocks)

            loss, acc = evaluate(logits, y)

            train_loss += loss.detach().item()
            train_acc += acc.item()


            optimizer.zero_grad()

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

            optimizer.step()

            # if i % 300 == 0:
                # print(f"Step: {i:04d} | Train loss: {loss:.4f} | Train acc: {100*acc:.2f}%")



        train_loss /= len(train_dataloader)
        train_acc /= len(train_dataloader)

        val_loss = 0.0
        val_acc = 0.0



        model.eval()
        with torch.inference_mode():
            for j, (X_val, y_val, mask_indices_val) in enumerate(val_dataloader):


                X_val, y_val, mask_indices_val = X_val.to(device), y_val.to(device), mask_indices_val.to(device)

                logits_val, _, _ = model(X_val, mask_indices_val)
                loss, acc = evaluate(logits_val, y_val)

                val_loss += loss.detach().item()
                val_acc += acc.item()

            val_loss /= len(val_dataloader)
            val_acc /= len(val_dataloader)

            best_val_acc = max(best_val_acc, val_acc)


        stock_cosine_similarities(model)
        tweet_embedding_quality(model)


        scheduler.step()

        print(f"\nEpoch: {epoch} | Train loss: {train_loss:.4f} | Train acc: {100*train_acc:.2f}% | Val loss: {val_loss:.4f} | Val acc: {100*val_acc:.2f}%")
        print(f"Learning rate: {optimizer.param_groups[0]['lr']:6f}")

        wandb.log({
            "train_loss": train_loss,
            "train_acc": train_acc,
            "val_loss": val_loss,
            "val_acc": val_acc,
            "best_val_acc": best_val_acc
        })

        trial.report(best_val_acc, step=epoch)
        if trial.should_prune():
            wandb.finish()
            raise optuna.TrialPruned()


        if epoch == 38:
            torch.save(model.state_dict(), dataset_dir / "best_model.pth")


    wandb.finish()
    return best_val_acc


study = optuna.create_study(direction="maximize", pruner=optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=5))
study.optimize(objective, n_trials = 1)

NameError: name 'optuna' is not defined

### Analyze Embedding Quality

In [13]:
# torch.save(model.state_dict(), dataset_dir / "best_model.pth")


# embd_size = 128
# hidden_size = 254
# dropout = 0.439
# temp = 0.13356

embd_size = 128
hidden_size = 64
dropout = 0.1
temp = 0.25


model = StockIdentification(
    num_stocks=num_stocks,
    embd_size=embd_size,
    hidden_size=hidden_size,
    vocab_size=vocab_size,
    dropout=dropout,
    temp=temp
).to(device)

model.load_state_dict(torch.load(dataset_dir / "best_model (1).pth", map_location=device))

In [ ]:
torch.manual_seed(42)
torch.cuda.manual_seed(42)

stock_cosine_similarities(model)
print()
tweet_embedding_quality(model)

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, HON,
BAC: WFC, JPM, C,

AAPL: 31.37% | FB: 9.29% | GOOG: 6.47% |
KO: 7.64% | PEP: 4.92% | MCD: 3.15% |

## Stock Movement Prediction

### Global Trend with Attention

The global trend vector is generated by weighting the price features of stocks based on their popularity in tweets.

The average of all tweet embeddings at day $t$ ($g_t$) is used as the query vector.

The key vector is $h_s$, and the value vector is $x_{st}$.

$$
o_t = \sum_{s' \in S} \alpha_{st} x_{st}\;\; \text {where} \;\; \alpha_{st} = \frac{\exp(g_t^\top h_s)}{\sum_{s' \in S} \exp(g_t^\top h_{s'})}
$$

In [14]:
# g_t = torch.load(dataset_dir / "g_t.pt", map_location=device)
# all_tweet_embs = torch.load(dataset_dir / "all_tweet_embs", map_location=device)



all_tweet_embs = []

model.eval()
with torch.inference_mode():
    for d in tqdm(range(num_dates)):
        tweets = X_by_date[d].to(device)
        indices = mask_indices_by_date[d].to(device)

        _, h_e, _ = model(tweets, indices)
        all_tweet_embs.append(h_e)

g_t = torch.stack([torch.mean(h_e, dim=0) for h_e in all_tweet_embs])

torch.save(g_t, dataset_dir / "g_t.pt")
torch.save(all_tweet_embs, dataset_dir / "all_tweet_embs")
g_t.shape # (num_days, 2*hidden_size)

100%|██████████| 651/651 [00:05<00:00, 110.38it/s]

torch.Size([651, 128])

In [ ]:
# a_st (num_days, num_stocks) @ x_st (num_days, num_stocks, num_features) -> o_t (num_days, num_features)
# g_t (num_days, 2*hidden_size)  @ h_s.T (2*hidden_size, num_stocks) -> a_st (num_days, num_stocks)

In [15]:
h_s = model.stock_embd.weight.detach()

attn_scores = torch.matmul(g_t, h_s.T)

a_st = F.softmax(attn_scores, dim=-1)

a_st = a_st.unsqueeze(1)
a_st.shape

torch.Size([651, 1, 87])

In [21]:
o_t = torch.matmul(a_st, X_st).squeeze(1)
o_t = o_t.unsqueeze(1).expand(-1, X_st.size(1), -1)
o_t.shape

torch.Size([651, 87, 11])

### Local Similarities between Stocks

Two steps of attention

1. Attention to find tweets (on the target day) relevant to each target stock. Produces l_st, a weighted sum of the tweets for that day based on their relevance to the target stock.
    - Q: h_s
    - K: h_e
    - V: h_e

2. Attention to find stocks most relevant to l_st, and aggregate the price features based on relevance.
    - Q: l_st
    - K: h_s
    - V: x_st

This is preferable to doing h_s @ h_s.T because it will yield different results based on the day.
- Say $AAPL is doing a collaboration with $MSFT on some day, the attention score for AAPL/MSFT should be higher than usual.

h_s (num_stocks, hidden_size) @ h_e.T (hidden_size, num_tweets_that_day) -> a_e (num_stocks num_tweets_that_day)

a_e (num_stocks num_tweets_that_day) @ h_e (num_tweets_that_day, hidden_size) -> l_st (num_stocks, hidden_size)

In [22]:
l_st = []

for d in range(len(all_tweet_embs)):
    h_e = all_tweet_embs[d]
    a_e = torch.matmul(h_s, h_e.T).softmax(dim=-1)
    l_st.append(torch.matmul(a_e, h_e))

l_st = torch.stack(l_st)
l_st.shape

torch.Size([651, 87, 128])

l_st (num_days, num_stocks, hidden_size) @ h_s.T (hidden_size, num_stocks) -> a_st (num_days, num_stocks, num_stocks)

a_st (num_days, num_stocks, num_stocks) @ X_st (num_days, num_stocks, num_features) -> c_st (num_days, num_stocks, num_features)

In [23]:
a_st = torch.matmul(l_st, h_s.T).softmax(dim=-1)
c_st = torch.matmul(a_st, X_st)

c_st.shape

torch.Size([651, 87, 11])

### Windows

In [89]:
def create_windows(input, labels=False):
    if (labels):
        windows_list = [input[t+1] for t in range(window_size - 1, num_dates-1)]
    else:
        windows_list = [input[t-window_size+1 : t+1] for t in range(window_size - 1, num_dates-1)]

    # input: (num_windows, seq_len, num_stocks, features)
    # labels: (num_windows, num_stocks)
    windows = torch.stack(windows_list)

    if labels:
        windows = windows.reshape(-1)

    else:
        windows=windows.reshape(-1, windows.size(1), windows.size(-1))

    return windows

In [120]:
X_windowed, o_windowed, c_windowed = create_windows(X_st), create_windows(o_t), create_windows(c_st)
y_windowed = create_windows(y, labels=True)

X_windowed.shape, o_windowed.shape, c_windowed.shape, y_windowed.shape

(torch.Size([54462, 25, 11]),
 torch.Size([54462, 25, 11]),
 torch.Size([54462, 25, 11]),
 torch.Size([54462]))

In [121]:
mask = y_windowed != 0

X_windowed = X_windowed[mask]
o_windowed = o_windowed[mask]
c_windowed = c_windowed[mask]
y_windowed = y_windowed[mask]


X_windowed.shape, o_windowed.shape, c_windowed.shape, y_windowed.shape

(torch.Size([33153, 25, 11]),
 torch.Size([33153, 25, 11]),
 torch.Size([33153, 25, 11]),
 torch.Size([33153]))

### Train/Val/Test Split

In [122]:
data_len = len(y_windowed)

train_end = int(data_len * 0.80)
val_end = int(data_len * 0.90)

X_train, o_train, c_train, y_train = X_windowed[: train_end], o_windowed[: train_end], c_windowed[: train_end], y_windowed[: train_end]
X_val, o_val, c_val, y_val = X_windowed[train_end : val_end], o_windowed[train_end : val_end], c_windowed[train_end :val_end], y_windowed[train_end : val_end]
X_test, o_test, c_test, y_test = X_windowed[val_end :], o_windowed[val_end :], c_windowed[val_end :], y_windowed[val_end :]

print(f"X_train shape: {X_train.shape}. y_train shape: {y_train.shape}")
print(f"X_val shape: {X_val.shape}. y_val shape: {y_val.shape}")
print(f"X_test shape: {X_test.shape}. y_test shape: {y_test.shape}")

X_train shape: torch.Size([26522, 25, 11]). y_train shape: torch.Size([26522])
X_val shape: torch.Size([3315, 25, 11]). y_val shape: torch.Size([3315])
X_test shape: torch.Size([3316, 25, 11]). y_test shape: torch.Size([3316])

### Multi-Feature Dataset

In [123]:
class MultiFeatureDataset(Dataset):
    def __init__(self, x, o, c, y):
        super().__init__()
        self.x = x; self.o = o; self.c = c
        self.y = y

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.o[idx], self.c[idx], self.y[idx]

In [124]:
train_dataset = MultiFeatureDataset(X_train, o_train, c_train, y_train)
val_dataset = MultiFeatureDataset(X_val, o_val, c_val, y_val)
test_dataset = MultiFeatureDataset(X_test, o_test, c_test, y_test)

### DataLoaders

In [125]:
train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=False)
val_dataloader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
test_dataloader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)
len(train_dataloader)

26

In [126]:
X, o, c, y = next(iter(train_dataloader))
X.shape

torch.Size([1024, 25, 11])

### SLOT Model Code

In [127]:
class SLOT(nn.Module):
    def __init__(self, input_size, hidden_size, dropout, output_size = 1):
        super().__init__()
        self.ln = nn.Linear(3*input_size, input_size)
        self.alstm = ALSTM(input_size=input_size, hidden_size=hidden_size, dropout=dropout)
        self.dropout = nn.Dropout(dropout)
        self.ln_f = nn.Linear(hidden_size*2, output_size)



    def forward(self, X_st, o_t, c_st):
        # X_st, o_t, c_st: (batch, seq_len, input_size)
        final_input = torch.cat((X_st, o_t, c_st), dim=-1) # (batch, seq_len, 3*input_size)
        final_input = self.ln(final_input) # (batch, seq_len, input_size)

        h_out = self.alstm(final_input) # (batch, 2*hidden_size)
        h_out = self.dropout(h_out)
        y_pred = self.ln_f(h_out) # (batch, output_size)

        return y_pred.squeeze(-1)

### Training Helper Functions

In [128]:
def evaluate(logits, y):
  # logits: (batch,)
  # y: (batch, )
  B = logits.size(0)

  loss = torch.clamp(1 - y * logits, min=0).mean()

  preds = torch.sign(logits) # (batch,)

  TP = ((y == 1) & (preds == 1)).sum().float()
  TN = ((y == -1) & (preds == -1)).sum().float()
  FP = ((y == -1) & (preds == 1)).sum().float()
  FN = ((y == 1) & (preds == -1)).sum().float()

  MCC = (TP * TN - FP * FN) / torch.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN) + 1e-8)

  acc = (preds == y).float().mean()

  return loss, acc.item(), MCC.item()

In [129]:
def training_loop(lr, hidden_size, weight_decay, dropout, use_existing=False):
  torch.manual_seed(42)
  torch.cuda.manual_seed(42)

  model = SLOT(
      input_size=len(price_features),
      hidden_size=hidden_size,
      dropout=dropout
  ).to(device)


  if use_existing:
    model.load_state_dict(torch.load(dataset_dir / "best_SLOT_model.pth", map_location=device))

  optimizer = torch.optim.AdamW(params = model.parameters(), lr=lr, weight_decay=weight_decay)
  scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer=optimizer, T_max=num_epochs, eta_min=1e-6)


  best_MCC = -float("inf")
  epochs_no_improve = 0
  patience = 50

  for epoch in range(num_epochs):
    train_loss = 0.0
    train_acc = 0.0



    model.train()
    for i, (X, o, c, y) in enumerate(train_dataloader):


        X, o, c, y = X.to(device), o.to(device), c.to(device), y.to(device)

        logits = model(X, o, c) # (batch, output_size)

        loss, acc, _ = evaluate(logits, y)

        train_loss += loss.detach().item()
        train_acc += acc

        optimizer.zero_grad()
        loss.backward()

        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

        optimizer.step()


    train_loss /= len(train_dataloader)
    train_acc /= len(train_dataloader)



    val_loss = 0.0
    val_acc = 0.

    MCC = 0.0


    model.eval()

    with torch.inference_mode():
        for i, (X_val, o_val, c_val, y_val) in enumerate(val_dataloader):

            X_val, o_val, c_val, y_val = X_val.to(device), o_val.to(device), c_val.to(device), y_val.to(device)

            logits = model(X_val, o_val, c_val)

            loss, acc, mcc = evaluate(logits, y_val)

            val_loss += loss.item()
            val_acc += acc
            MCC += mcc


        val_loss /= len(val_dataloader)
        val_acc /= len(val_dataloader)
        MCC /= len(val_dataloader)

    if MCC > best_MCC:
          best_MCC = MCC
          epochs_no_improve = 0
    else:
        epochs_no_improve += 1


    if epochs_no_improve >= patience:
        break

    # wandb.log({
    #     "MCC:": MCC,
    #     "train_loss": train_loss,
    #     "train_acc": train_acc,
    #     "val_loss": val_loss,
    #     "val_acc": val_acc,
    # })

    scheduler.step()

    print(f"Epoch: {epoch:03d} | MCC: {MCC:4f} | Train loss: {train_loss:.4f} | Train acc: {100*train_acc:.2f}% | Val loss: {val_loss:.4f} | Val acc: {100*val_acc:.2f}% | LR: {optimizer.param_groups[0]['lr']:6f}")

    # if epoch == 84:
    #   torch.save(model.state_dict(), "best_SLOT_model.pth")
    #   break

  # wandb.log({
  #     "best_MCC": best_MCC
  # })

  # wandb.finish()
  torch.save(model.state_dict(), "best_SLOT_model.pth")

  return best_MCC

### Training Loop

In [131]:
def objective(trial):

    lr = trial.suggest_float("lr", 1e-4, 1e-2, log=True)
    hidden_size =  trial.suggest_int("hidden_size", 16, 128)
    dropout = trial.suggest_float("dropout", 0.0, 0.5)
    weight_decay = trial.suggest_float("weight_decay", 1e-4, 1e-1, log=True)

    wandb.init(
    project="SLOT_MCC",
    name=f"trial_{trial.number}",
    config={
            "lr": lr,
            "hidden_size": hidden_size,
            "dropout": dropout,
            "weight_decay": weight_decay,
        },
    )

    return training_loop(trial, lr, hidden_size, dropout, weight_decay)


# study = optuna.create_study(
#     direction="maximize",
#     study_name="SLOT_MCC",
#     storage="sqlite:///optuna_study.db",
#     load_if_exists=True
# )
# study.optimize(objective, n_trials = 200)


lr = 0.0017333313943154057
hidden_size = 53
dropout = 0.4816155085292496
weight_decay = 0.0014864124854921702

# lr = 5e-2
# hidden_size = 8
# dropout = 0.0
# weight_decay = 5e-4



training_loop(lr, hidden_size, dropout, weight_decay)

Epoch: 000 | MCC: 0.021576 | Train loss: 1.0006 | Train acc: 49.71% | Val loss: 1.0052 | Val acc: 47.91% | LR: 0.001733
Epoch: 001 | MCC: 0.016507 | Train loss: 0.9996 | Train acc: 50.59% | Val loss: 0.9985 | Val acc: 51.33% | LR: 0.001733
Epoch: 002 | MCC: 0.006795 | Train loss: 1.0003 | Train acc: 50.90% | Val loss: 0.9936 | Val acc: 51.88% | LR: 0.001732
Epoch: 003 | MCC: -0.007902 | Train loss: 1.0057 | Train acc: 50.80% | Val loss: 0.9946 | Val acc: 54.30% | LR: 0.001730
Epoch: 004 | MCC: 0.006918 | Train loss: 0.9962 | Train acc: 50.46% | Val loss: 0.9821 | Val acc: 56.20% | LR: 0.001729
Epoch: 005 | MCC: -0.001140 | Train loss: 0.9945 | Train acc: 50.63% | Val loss: 0.9814 | Val acc: 55.15% | LR: 0.001727
Epoch: 006 | MCC: 0.005683 | Train loss: 0.9950 | Train acc: 50.53% | Val loss: 0.9873 | Val acc: 53.58% | LR: 0.001724
Epoch: 007 | MCC: 0.008232 | Train loss: 1.0077 | Train acc: 50.40% | Val loss: 0.9908 | Val acc: 52.36% | LR: 0.001721
Epoch: 008 | MCC: 0.011145 | Train loss: 0.9970 | Train acc: 50.48% | Val loss: 0.9787 | Val acc: 54.36% | LR: 0.001718
Epoch: 009 | MCC: 0.017785 | Train loss: 0.9956 | Train acc: 50.51% | Val loss: 0.9738 | Val acc: 55.94% | LR: 0.001714
Epoch: 010 | MCC: 0.005147 | Train loss: 0.9965 | Train acc: 50.89% | Val loss: 0.9738 | Val acc: 56.00% | LR: 0.001710
Epoch: 011 | MCC: 0.010255 | Train loss: 0.9961 | Train acc: 50.86% | Val loss: 0.9661 | Val acc: 56.30% | LR: 0.001706
Epoch: 012 | MCC: 0.012156 | Train loss: 0.9956 | Train acc: 50.45% | Val loss: 0.9556 | Val acc: 56.51% | LR: 0.001701
Epoch: 013 | MCC: 0.014003 | Train loss: 0.9937 | Train acc: 50.96% | Val loss: 0.9367 | Val acc: 56.61% | LR: 0.001696
Epoch: 014 | MCC: 0.010683 | Train loss: 0.9910 | Train acc: 50.55% | Val loss: 0.9054 | Val acc: 56.37% | LR: 0.001691
Epoch: 015 | MCC: 0.014729 | Train loss: 0.9903 | Train acc: 49.83% | Val loss: 0.9301 | Val acc: 54.19% | LR: 0.001685
Epoch: 016 | MCC: 0.019747 | Train loss: 0.9925 | Train acc: 50.86% | Val loss: 0.9190 | Val acc: 55.78% | LR: 0.001679
Epoch: 017 | MCC: 0.007225 | Train loss: 0.9889 | Train acc: 51.00% | Val loss: 0.8800 | Val acc: 56.87% | LR: 0.001673
Epoch: 018 | MCC: 0.003326 | Train loss: 0.9880 | Train acc: 51.09% | Val loss: 0.9015 | Val acc: 56.34% | LR: 0.001666
Epoch: 019 | MCC: 0.010704 | Train loss: 0.9907 | Train acc: 51.04% | Val loss: 0.9084 | Val acc: 57.28% | LR: 0.001658
Epoch: 020 | MCC: 0.009223 | Train loss: 0.9875 | Train acc: 51.02% | Val loss: 0.8799 | Val acc: 57.39% | LR: 0.001651
Epoch: 021 | MCC: 0.026585 | Train loss: 1.0016 | Train acc: 50.73% | Val loss: 0.9145 | Val acc: 55.05% | LR: 0.001643
Epoch: 022 | MCC: 0.007906 | Train loss: 0.9933 | Train acc: 50.89% | Val loss: 0.9074 | Val acc: 56.62% | LR: 0.001635
Epoch: 023 | MCC: 0.016717 | Train loss: 0.9913 | Train acc: 50.98% | Val loss: 0.8831 | Val acc: 56.64% | LR: 0.001626
Epoch: 024 | MCC: 0.028670 | Train loss: 0.9932 | Train acc: 50.43% | Val loss: 0.9121 | Val acc: 56.98% | LR: 0.001617
Epoch: 025 | MCC: 0.028016 | Train loss: 0.9913 | Train acc: 50.51% | Val loss: 0.9436 | Val acc: 56.80% | LR: 0.001608
Epoch: 026 | MCC: 0.012928 | Train loss: 0.9889 | Train acc: 50.66% | Val loss: 0.9287 | Val acc: 56.88% | LR: 0.001598
Epoch: 027 | MCC: 0.003819 | Train loss: 0.9862 | Train acc: 50.57% | Val loss: 0.9105 | Val acc: 56.73% | LR: 0.001589
Epoch: 028 | MCC: 0.000102 | Train loss: 0.9929 | Train acc: 50.51% | Val loss: 0.9127 | Val acc: 56.56% | LR: 0.001578
Epoch: 029 | MCC: 0.011203 | Train loss: 0.9913 | Train acc: 50.60% | Val loss: 0.9208 | Val acc: 56.74% | LR: 0.001568
Epoch: 030 | MCC: 0.005829 | Train loss: 0.9922 | Train acc: 50.70% | Val loss: 0.9010 | Val acc: 57.09% | LR: 0.001557
Epoch: 031 | MCC: -0.003531 | Train loss: 0.9912 | Train acc: 50.61% | Val loss: 0.9092 | Val acc: 56.61% | LR: 0.001546
Epoch: 032 | MCC: 0.002078 | Train loss: 0.9913 | Train acc: 50.55% | Val loss: 0.8854 | Val acc: 56.68% | LR: 0.001535
Epoch: 033 | MCC: 0.007876 | Train loss: 0.9936 | Train acc: 50.42% | Val loss: 0.9659 | Val acc: 52.87% | LR: 0.001523
Epoch: 034 | MCC: 0.005759 | Train loss: 0.9918 | Train acc: 50.51% | Val loss: 0.9296 | Val acc: 55.60% | LR: 0.001511
Epoch: 035 | MCC: 0.009336 | Train loss: 0.9912 | Train acc: 50.53% | Val loss: 0.9131 | Val acc: 55.96% | LR: 0.001499
Epoch: 036 | MCC: 0.010555 | Train loss: 0.9912 | Train acc: 50.62% | Val loss: 0.9025 | Val acc: 56.03% | LR: 0.001486
Epoch: 037 | MCC: 0.008645 | Train loss: 0.9895 | Train acc: 50.62% | Val loss: 0.9364 | Val acc: 56.01% | LR: 0.001473
Epoch: 038 | MCC: 0.012811 | Train loss: 0.9889 | Train acc: 50.60% | Val loss: 0.8839 | Val acc: 56.26% | LR: 0.001460
Epoch: 039 | MCC: 0.002160 | Train loss: 0.9891 | Train acc: 50.61% | Val loss: 0.8785 | Val acc: 56.48% | LR: 0.001447
Epoch: 040 | MCC: 0.015023 | Train loss: 0.9888 | Train acc: 50.62% | Val loss: 0.8878 | Val acc: 56.42% | LR: 0.001433
Epoch: 041 | MCC: 0.017762 | Train loss: 0.9902 | Train acc: 50.49% | Val loss: 0.9084 | Val acc: 56.83% | LR: 0.001419
Epoch: 042 | MCC: 0.015653 | Train loss: 0.9897 | Train acc: 50.57% | Val loss: 0.9217 | Val acc: 56.30% | LR: 0.001405
Epoch: 043 | MCC: 0.015042 | Train loss: 0.9878 | Train acc: 50.67% | Val loss: 0.8965 | Val acc: 56.38% | LR: 0.001391
Epoch: 044 | MCC: 0.011611 | Train loss: 0.9909 | Train acc: 50.61% | Val loss: 0.8858 | Val acc: 56.78% | LR: 0.001376
Epoch: 045 | MCC: 0.009209 | Train loss: 0.9915 | Train acc: 50.67% | Val loss: 0.8845 | Val acc: 56.85% | LR: 0.001361
Epoch: 046 | MCC: 0.006609 | Train loss: 0.9912 | Train acc: 50.65% | Val loss: 0.8788 | Val acc: 56.83% | LR: 0.001346
Epoch: 047 | MCC: 0.007541 | Train loss: 0.9894 | Train acc: 50.70% | Val loss: 0.8787 | Val acc: 56.82% | LR: 0.001331
Epoch: 048 | MCC: 0.011707 | Train loss: 0.9938 | Train acc: 50.66% | Val loss: 0.8784 | Val acc: 57.15% | LR: 0.001316
Epoch: 049 | MCC: 0.005430 | Train loss: 0.9902 | Train acc: 50.58% | Val loss: 0.9223 | Val acc: 55.30% | LR: 0.001300
Epoch: 050 | MCC: 0.021651 | Train loss: 0.9973 | Train acc: 49.97% | Val loss: 0.9267 | Val acc: 55.21% | LR: 0.001284
Epoch: 051 | MCC: 0.005917 | Train loss: 0.9936 | Train acc: 50.33% | Val loss: 0.9037 | Val acc: 57.30% | LR: 0.001268
Epoch: 052 | MCC: 0.006993 | Train loss: 0.9913 | Train acc: 50.56% | Val loss: 0.8889 | Val acc: 58.00% | LR: 0.001252
Epoch: 053 | MCC: 0.012243 | Train loss: 0.9925 | Train acc: 50.20% | Val loss: 0.8778 | Val acc: 57.63% | LR: 0.001236
Epoch: 054 | MCC: 0.003530 | Train loss: 0.9904 | Train acc: 50.59% | Val loss: 0.8748 | Val acc: 56.88% | LR: 0.001219
Epoch: 055 | MCC: 0.001295 | Train loss: 0.9898 | Train acc: 50.70% | Val loss: 0.8711 | Val acc: 56.90% | LR: 0.001203
Epoch: 056 | MCC: 0.001324 | Train loss: 0.9892 | Train acc: 50.62% | Val loss: 0.8714 | Val acc: 56.82% | LR: 0.001186
Epoch: 057 | MCC: 0.010292 | Train loss: 0.9889 | Train acc: 50.68% | Val loss: 0.8808 | Val acc: 57.00% | LR: 0.001169
Epoch: 058 | MCC: 0.008183 | Train loss: 0.9912 | Train acc: 50.61% | Val loss: 0.8997 | Val acc: 56.93% | LR: 0.001152
Epoch: 059 | MCC: 0.006932 | Train loss: 0.9888 | Train acc: 50.72% | Val loss: 0.8867 | Val acc: 56.80% | LR: 0.001135
Epoch: 060 | MCC: 0.006646 | Train loss: 0.9882 | Train acc: 50.60% | Val loss: 0.8740 | Val acc: 56.57% | LR: 0.001118
Epoch: 061 | MCC: 0.008949 | Train loss: 0.9880 | Train acc: 50.65% | Val loss: 0.8775 | Val acc: 56.79% | LR: 0.001100
Epoch: 062 | MCC: 0.023286 | Train loss: 0.9883 | Train acc: 50.69% | Val loss: 0.8799 | Val acc: 57.21% | LR: 0.001083
Epoch: 063 | MCC: 0.013189 | Train loss: 0.9873 | Train acc: 50.63% | Val loss: 0.8670 | Val acc: 57.02% | LR: 0.001065
Epoch: 064 | MCC: 0.001540 | Train loss: 0.9884 | Train acc: 50.62% | Val loss: 0.8787 | Val acc: 56.54% | LR: 0.001047
Epoch: 065 | MCC: 0.001206 | Train loss: 0.9890 | Train acc: 50.61% | Val loss: 0.8873 | Val acc: 56.62% | LR: 0.001029
Epoch: 066 | MCC: 0.010679 | Train loss: 0.9870 | Train acc: 50.63% | Val loss: 0.8766 | Val acc: 56.61% | LR: 0.001012
Epoch: 067 | MCC: 0.008680 | Train loss: 0.9884 | Train acc: 50.71% | Val loss: 0.8782 | Val acc: 56.60% | LR: 0.000994
Epoch: 068 | MCC: 0.000618 | Train loss: 0.9890 | Train acc: 50.65% | Val loss: 0.8837 | Val acc: 56.66% | LR: 0.000976
Epoch: 069 | MCC: 0.006058 | Train loss: 0.9875 | Train acc: 50.75% | Val loss: 0.8750 | Val acc: 56.62% | LR: 0.000958
Epoch: 070 | MCC: 0.003781 | Train loss: 0.9878 | Train acc: 50.74% | Val loss: 0.8757 | Val acc: 56.81% | LR: 0.000940
Epoch: 071 | MCC: 0.004873 | Train loss: 0.9869 | Train acc: 50.69% | Val loss: 0.8893 | Val acc: 56.90% | LR: 0.000922
Epoch: 072 | MCC: 0.006981 | Train loss: 0.9862 | Train acc: 50.73% | Val loss: 0.8786 | Val acc: 56.83% | LR: 0.000903
Epoch: 073 | MCC: 0.007174 | Train loss: 0.9866 | Train acc: 50.79% | Val loss: 0.8744 | Val acc: 56.72% | LR: 0.000885

0.02866955567151308

In [132]:
torch.manual_seed(42)
torch.cuda.manual_seed(42)


model = SLOT(
    input_size=len(price_features),
    hidden_size=hidden_size,
    dropout=dropout
).to(device)

model.load_state_dict(torch.load("best_SLOT_model.pth", map_location=device))

test_loss = 0.0
test_acc = 0.0
test_mcc = 0.0

model.eval()

with torch.inference_mode():
    for X_test, o_test, c_test, y_test in test_dataloader:

        X_test, o_test, c_test, y_test = X_test.to(device), o_test.to(device), c_test.to(device), y_test.to(device)

        logits = model(X_test, o_test, c_test)
        loss, acc, mcc = evaluate(logits, y_test)

        test_loss += loss.item()
        test_acc += acc
        test_mcc += mcc


    test_loss /= len(test_dataloader)
    test_acc /= len(test_dataloader)
    test_mcc /= len(test_dataloader)

print(f"Test MCC: {test_mcc:.4f} | Test loss: {test_loss:.4f} | Test acc: {100*test_acc:.2f}%")

Test MCC: 0.0306 | Test loss: 0.9701 | Test acc: 51.93%