<a href="https://colab.research.google.com/github/brien60/Stock-LSTM/blob/SLOT/SLOT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Setup

### Imports

In [5]:
import torch
from torch import nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, random_split
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence

from pathlib import Path
import json
import re

import sentencepiece as sp
from collections import Counter

import pandas as pd

from tqdm import tqdm

import os

import wandb

try:
  import optuna
  from optuna.integration.wandb import WeightsAndBiasesCallback

except:
  !pip install -q optuna
  !pip install -q optuna-integration[wandb]
  import optuna
  from optuna.integration.wandb import WeightsAndBiasesCallback


import time

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.9/400.9 kB 13.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 4.9 MB/s eta 0:00:00

### Colab Setup Code

In [3]:
!git clone -q --branch SLOT https://github.com/brien60/Stock-LSTM.git
%cd Stock-LSTM/;
!unzip -q data.zip -d /content/Stock-LSTM/data

/content/Stock-LSTM

### Constants

In [6]:
torch.manual_seed(42)
torch.cuda.manual_seed(42)
device = "cuda" if torch.cuda.is_available() else "cpu"

if device == "cuda":
    os.environ["CUDA_LAUNCH_BLOCKING"] = "1"


dataset = "acl18"
dataset_dir = Path(dataset.upper())

data_dir = Path(f"data/{dataset}")

tweet_dir = data_dir / "tweet"
price_dir = data_dir / "price"

tweet_files_list = list(tweet_dir.rglob("*/*"))
list.sort(tweet_files_list)

stock_names = [stock.name for stock in list(tweet_dir.rglob("*")) if stock.is_dir()]
list.sort(stock_names)

num_stocks = len(stock_names)

json_file = dataset_dir / "all_tweets.jsonl"
spm_file = dataset_dir / "spm/slot_tweet_spm.model"
tokens_file = dataset_dir / "all_tweets_tokenized.jsonl"


vocab_size = 10_000

window_size = 15

num_epochs = 150
batch_size = 1024

## SLOT Overview

SLOT (Self-supervised Learning of Tweets for Capturing Multi-level Price Trends) aims to address
1. the sparsity of tweets, with the number of tweets being heavily biased towards the most popular stocks.
2. the fact that tweets have noisy information that are often irrelevant to the actual stock movement.

The first problem was addressed by having SLOT learn the stock and tweet embeddings in the same vector space through self-supervised learning. This allows the use of any tweet for even unpopular stocks.

To tackle the second problem, SLOT uses tweets to learn multi-level relationships between stocks, rather than using them as direct evidence for stock prediction (e.g. positive sentiment = up).

## Attention LSTM

In [7]:

class ALSTM(nn.Module):
    def __init__(self, input_size, hidden_size, dropout):
        super().__init__()
        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            batch_first=True,
        )
        self.dropout = nn.Dropout(dropout)
        self.ln = nn.Linear(hidden_size, hidden_size)
        self.tanh = nn.Tanh()
        self.u = nn.Parameter(data=torch.randn(hidden_size))


    def forward(self, x):
        # x: (batch, seq_len, input_size)

        # output: (batch, seq_len, hidden_size)
        # h_n, c_n : (num_layers, batch, hidden_size)
        output, (h_n, c_n) = self.lstm(x)
        output = self.dropout(output)
        output = self.tanh(self.ln(output))

        # query: u, key: output, values: output
        attn_scores = torch.matmul(output, self.u) # (batch, seq_len, hidden_size) @ (hidden_size) -> (batch, seq_len)
        weights = attn_scores / attn_scores.sum(dim=1, keepdim=True)
        weights = weights.unsqueeze(dim=-1) # (batch, seq_len, 1)

        # (batch, seq_len, 1) * (batch, seq_len, hidden_size) -> (batch, seq_len, hidden_size)
        # (batch, seq_len, hidden_size) -> (batch, hidden_size)
        h_attn = (weights * output).sum(dim=1)

        # (batch, hidden_size) || (batch, hidden_size) -> (batch, 2*hidden_size)
        h_out = torch.cat((h_n[0], h_attn), dim=1) # both the general summary and the attention

        return h_out

## Price Features

The price features that compose a feature vector $x_{st}$ are
- Price movements in a day: *c_open, c_high, c_low*
- Price movements between days: *n_close, n_adj_close*
- Long-term movements: *5_day, 10_day, ... , 30_day*

So the daily prices of days $t-29$ to $t$ are used to generate each $x_{st}$

These features have already been calculated and normalized in the csv files.

### Extracting features data

In [8]:
data_files_list = list(price_dir.rglob("*.csv"))

data_list = []

price_features = []
labels = []

for i, stock_file in enumerate(data_files_list):
    stock = stock_file.stem
    df = pd.read_csv(stock_file)
    # columns = [
    #     f'{stock}_c_open', f'{stock}_c_high', f'{stock}_c_low',
    #     f'{stock}_n_close', f'{stock}_n_adj_close',
    #     f'{stock}_adj_sum_5', f'{stock}_adj_sum_10', f'{stock}_adj_sum_15',
    #     f'{stock}_adj_sum_20', f'{stock}_adj_sum_25', f'{stock}_adj_sum_30',
    #     f'{stock}_label', f'{stock}_closing_price_for_label'
    # ]

    # price_features.extend(columns[:-2])
    # labels.append(columns[-2])

    # if i != 0:
    # df.drop(columns=['date'], inplace=True)
    # else:
        # columns = ['date'] + columns

    # df.columns = columns

    df['label'] = df['label'].shift(-1)
    df = df.dropna()

    data_list.append(df)

# combined_df = pd.concat(data_list, axis=1)
# combined_df = combined_df.dropna()

# combined_df
data_list[0]

,date,c_open,c_high,c_low,n_close,n_adj_close,adj_sum_5,adj_sum_10,adj_sum_15,adj_sum_20,adj_sum_25,adj_sum_30,label,closing_price_for_label
0,2013-06-03,-1.214238,0.266138,-1.746504,0.940224,0.940235,0.705257,2.985694,4.059658,4.426977,4.753823,4.341868,0.0,52.789917
1,2013-06-04,-0.364961,0.481082,-0.431322,0.266138,0.266140,-0.378239,2.058720,3.405215,3.863629,4.272719,4.057722,-1.0,52.930412
2,2013-06-05,1.264045,1.264045,-0.210675,-5.507631,-2.249839,1.420411,3.612428,5.159974,5.862468,6.343023,6.305304,1.0,51.739563
3,2013-06-06,-1.399203,0.069100,-1.623768,1.632722,1.632725,-0.220305,1.444585,2.984755,3.850856,4.354486,4.506555,1.0,52.584328
4,2013-06-07,-0.532373,0.051517,-0.824317,0.587324,0.587319,-0.577936,0.466718,2.000242,2.996097,3.518573,3.820407,-1.0,52.893166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,2015-12-23,-0.915336,0.171624,-0.915336,2.132634,2.132654,-1.507447,-1.610425,-1.708631,-1.345122,-0.980543,-1.164651,0.0,71.066559
647,2015-12-24,-0.427660,0.242341,-0.427660,0.328946,0.328937,-1.550962,-1.736281,-1.852223,-1.694942,-1.272907,-1.393520,0.0,71.300323
648,2015-12-28,-0.442790,0.114266,-0.542781,-0.199574,-0.199571,-0.848450,-1.339811,-1.517880,-1.507645,-1.105674,-1.121229,1.0,71.158028
649,2015-12-29,-0.536043,0.141062,-0.578364,1.256966,1.256954,-1.416272,-2.199176,-2.527854,-2.628715,-2.342892,-2.205345,0.0,72.052452
650,2015-12-30,0.396100,0.509276,-0.056578,-0.282134,-0.282125,-0.506431,-1.584379,-2.055922,-2.283913,-2.024612,-1.846342,-1.0,71.849174

### Remove Dates

In [9]:
for df in data_list:
    df.drop(columns=['date'], inplace=True)

data_list[0]

,c_open,c_high,c_low,n_close,n_adj_close,adj_sum_5,adj_sum_10,adj_sum_15,adj_sum_20,adj_sum_25,adj_sum_30,label,closing_price_for_label
0,-1.214238,0.266138,-1.746504,0.940224,0.940235,0.705257,2.985694,4.059658,4.426977,4.753823,4.341868,0.0,52.789917
1,-0.364961,0.481082,-0.431322,0.266138,0.266140,-0.378239,2.058720,3.405215,3.863629,4.272719,4.057722,-1.0,52.930412
2,1.264045,1.264045,-0.210675,-5.507631,-2.249839,1.420411,3.612428,5.159974,5.862468,6.343023,6.305304,1.0,51.739563
3,-1.399203,0.069100,-1.623768,1.632722,1.632725,-0.220305,1.444585,2.984755,3.850856,4.354486,4.506555,1.0,52.584328
4,-0.532373,0.051517,-0.824317,0.587324,0.587319,-0.577936,0.466718,2.000242,2.996097,3.518573,3.820407,-1.0,52.893166
...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,-0.915336,0.171624,-0.915336,2.132634,2.132654,-1.507447,-1.610425,-1.708631,-1.345122,-0.980543,-1.164651,0.0,71.066559
647,-0.427660,0.242341,-0.427660,0.328946,0.328937,-1.550962,-1.736281,-1.852223,-1.694942,-1.272907,-1.393520,0.0,71.300323
648,-0.442790,0.114266,-0.542781,-0.199574,-0.199571,-0.848450,-1.339811,-1.517880,-1.507645,-1.105674,-1.121229,1.0,71.158028
649,-0.536043,0.141062,-0.578364,1.256966,1.256954,-1.416272,-2.199176,-2.527854,-2.628715,-2.342892,-2.205345,0.0,72.052452
650,0.396100,0.509276,-0.056578,-0.282134,-0.282125,-0.506431,-1.584379,-2.055922,-2.283913,-2.024612,-1.846342,-1.0,71.849174

### Make X and y tensors

In [10]:
columns = data_list[0].columns.to_list()
price_features = columns[: -2]
labels = columns[-2]

In [38]:
X_st = [
    torch.tensor(df[price_features].to_numpy(), dtype=torch.float)
    for df in data_list
]
y = [
    torch.tensor(df[labels].to_numpy(), dtype=torch.float)
    for df in data_list
]

X_st = torch.stack(X_st).transpose(0, 1).to(device)
y = torch.stack(y).transpose(0, 1).to(device)

y = torch.sign(y)

X_st[0, :5], X_st.shape, y, y.shape

(tensor([[-1.2142,  0.2661, -1.7465,  0.9402,  0.9402,  0.7053,  2.9857,  4.0597,
           4.4270,  4.7538,  4.3419],
         [ 1.0034,  1.0034, -1.7828, -0.3393, -0.3393,  0.7310,  0.9604,  1.0948,
           0.2320, -1.4926, -2.5590],
         [-0.6284,  0.0898, -1.1131,  1.5312,  1.5312, -0.2118,  0.9975,  1.2685,
           1.1894,  0.5511, -0.4571],
         [-1.3699,  0.1588, -1.4294,  1.7370,  1.7370, -0.8338, -1.2656, -2.1878,
          -3.2687, -4.4262, -5.5260],
         [ 2.8821,  3.4217, -1.1023, -2.1461, -2.1461,  1.2148,  1.6910,  2.3330,
           3.2499,  3.5939,  3.6049]], device='cuda:0'),
 torch.Size([651, 87, 11]),
 tensor([[ 0.,  1.,  0.,  ..., -1.,  0.,  1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [ 1., -1.,  0.,  ...,  1.,  1.,  1.],
         ...,
         [ 1.,  1.,  1.,  ...,  1.,  1.,  0.],
         [ 0., -1., -1.,  ..., -1.,  0., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.]], device='cuda:0'),
 torch.Size([651, 87]))

## Self-supervised Learning of Embeddings

The goal is to learn tweet (h_e) and stock (h_s) embeddings in the same semantic space, that is, learning the embeddings together such that one embedding can be used to query for the other.
- a stock embedding and the embedding of tweet relevant to it are close together (higher dot product)
- stocks that are frequently co-mentioned will have similar embeddings; this naturally groups together stocks in the same industry/sector.
- solves problem of tweet sparsity; the model can associate stocks with tweets that don't directly mention it as long as they are close in vector space.

This was done by training for stock identification: predict the mentioned stock in a tweet when the stock symbol is masked.

Every tweet is tokenized with Sentence Piece and then the tokens that correspond to the stock the tweet mentions are masked with the special token MASK.
- "Thank you Apple for the new iPhone." -> "Thank you [MASK] for the new iPhone."

### Stock Identification Model

Use a BiLSTM (need to understand the context on both sides of the mask token).
- Using a transformer risks overfitting.

The stock embedding is a learnable parameter.

The hidden state vector generated at the masked token is used as the tweet embedding because it
- captures the immediate left (via the forward LSTM) and right context (via the backward LSTM) of the tweet, making it exactly what we need for stock identification,
- and it is the part of the tweet that most connects to mentioned stock.

### Write raw data to json

In [ ]:

buffer = []
buffer_size = 100_000
lines = 0

with open(json_file, "w", encoding="utf-8") as out:
    for tweet_file in tweet_files_list:

        with open(tweet_file, "r", encoding="utf-8") as f:


            for line in f:
                tweet = json.loads(line)

                json_tweet = {
                    "date": tweet_file.stem,
                    "stock": tweet_file.parent.name,
                    "tweet": tweet["text"].replace("\n", " ")
                }

                buffer.append(json.dumps(json_tweet))

                if len(buffer) >= buffer_size:
                    out.write("\n".join(buffer) + "\n")
                    lines += len(buffer)

                    buffer.clear()

                    print(f"{lines} lines written")

    if buffer:
        lines += len(buffer)
        out.write("\n".join(buffer) + "\n")
        print(f"{lines} lines written")

print("All tweets written")

100000 lines written
119844 lines written
All tweets written

### Txt file for sp training

In [ ]:
input_file = json_file
output_file = dataset_dir / "tweets_for_sp.txt"

with open(input_file, "r", encoding="utf-8") as f, open(output_file, "w", encoding="utf-8") as out:
    for line in f:
        tweet = json.loads(line)
        out.write(tweet["tweet"] + "\n")

### SPM Training

In [ ]:
spm_file = dataset_dir / "spm/slot_tweet_spm"
vocab_size = 10_000

sp.SentencePieceTrainer.train(
    input=output_file,
    model_prefix=spm_file,
    vocab_size=vocab_size,
    model_type="unigram",
    character_coverage=1.0,
    input_sentence_size=lines,
    shuffle_input_sentence=True,
    user_defined_symbols=["<MASK>", "<PAD>", "<UNK>"]
)

spm_file = str(spm_file.with_suffix(".model"))

In [12]:
slot_spm = sp.SentencePieceProcessor()
slot_spm.load(str(spm_file))

mask_id = slot_spm.piece_to_id("<MASK>")
pad_id = slot_spm.piece_to_id("<PAD>")
unk_id = slot_spm.piece_to_id("<UNK>")

mask_id, pad_id, unk_id

(3, 4, 5)

### Create tokenized jsonl

In [13]:
all_dates = []

for tweet_file in tweet_files_list:
        date = tweet_file.stem
        all_dates.append(date)


all_dates = sorted(dict.fromkeys(all_dates))

start_date, end_date = "2014-02-19", "2015-12-31"
start_date_idx, end_date_idx = all_dates.index(start_date), all_dates.index(end_date)

all_dates = all_dates[start_date_idx : end_date_idx + 1]

num_dates = len(all_dates)
num_dates, all_dates

(651,
 ['2014-02-19',
  '2014-02-20',
  '2014-02-21',
  '2014-02-22',
  '2014-02-23',
  '2014-02-24',
  '2014-02-25',
  '2014-02-26',
  '2014-02-27',
  '2014-02-28',
  '2014-03-01',
  '2014-03-02',
  '2014-03-03',
  '2014-03-04',
  '2014-03-05',
  '2014-03-06',
  '2014-03-07',
  '2014-03-08',
  '2014-03-09',
  '2014-03-10',
  '2014-03-11',
  '2014-03-12',
  '2014-03-13',
  '2014-03-14',
  '2014-03-15',
  '2014-03-16',
  '2014-03-17',
  '2014-03-18',
  '2014-03-19',
  '2014-03-20',
  '2014-03-21',
  '2014-03-22',
  '2014-03-23',
  '2014-03-24',
  '2014-03-25',
  '2014-03-26',
  '2014-03-27',
  '2014-03-28',
  '2014-03-29',
  '2014-03-30',
  '2014-03-31',
  '2014-04-01',
  '2014-04-02',
  '2014-04-03',
  '2014-04-04',
  '2014-04-05',
  '2014-04-06',
  '2014-04-07',
  '2014-04-08',
  '2014-04-09',
  '2014-04-10',
  '2014-04-11',
  '2014-04-12',
  '2014-04-13',
  '2014-04-14',
  '2014-04-15',
  '2014-04-16',
  '2014-04-17',
  '2014-04-18',
  '2014-04-19',
  '2014-04-20',
  '2014-04-21',
  '2014-04-22',
  '2014-04-23',
  '2014-04-24',
  '2014-04-25',
  '2014-04-26',
  '2014-04-27',
  '2014-04-28',
  '2014-04-29',
  '2014-04-30',
  '2014-05-01',
  '2014-05-02',
  '2014-05-03',
  '2014-05-04',
  '2014-05-05',
  '2014-05-06',
  '2014-05-07',
  '2014-05-08',
  '2014-05-09',
  '2014-05-10',
  '2014-05-11',
  '2014-05-12',
  '2014-05-13',
  '2014-05-14',
  '2014-05-15',
  '2014-05-16',
  '2014-05-17',
  '2014-05-18',
  '2014-05-19',
  '2014-05-20',
  '2014-05-21',
  '2014-05-22',
  '2014-05-23',
  '2014-05-24',
  '2014-05-25',
  '2014-05-26',
  '2014-05-27',
  '2014-05-28',
  '2014-05-29',
  '2014-05-30',
  '2014-05-31',
  '2014-06-01',
  '2014-06-02',
  '2014-06-03',
  '2014-06-04',
  '2014-06-05',
  '2014-06-06',
  '2014-06-07',
  '2014-06-08',
  '2014-06-09',
  '2014-06-10',
  '2014-06-11',
  '2014-06-12',
  '2014-06-13',
  '2014-06-14',
  '2014-06-15',
  '2014-06-16',
  '2014-06-18',
  '2014-06-19',
  '2014-06-20',
  '2014-06-21',
  '2014-06-22',
  '2014-06-23',
  '2014-06-24',
  '2014-06-25',
  '2014-06-26',
  '2014-06-27',
  '2014-06-28',
  '2014-06-29',
  '2014-06-30',
  '2014-07-01',
  '2014-07-02',
  '2014-07-03',
  '2014-07-04',
  '2014-07-05',
  '2014-07-06',
  '2014-07-07',
  '2014-07-08',
  '2014-07-09',
  '2014-07-10',
  '2014-07-11',
  '2014-07-12',
  '2014-07-13',
  '2014-07-14',
  '2014-07-15',
  '2014-07-16',
  '2014-07-17',
  '2014-07-18',
  '2014-07-19',
  '2014-07-20',
  '2014-07-21',
  '2014-07-22',
  '2014-07-23',
  '2014-07-24',
  '2014-07-25',
  '2014-07-26',
  '2014-07-27',
  '2014-07-28',
  '2014-07-29',
  '2014-07-30',
  '2014-07-31',
  '2014-08-01',
  '2014-08-02',
  '2014-08-03',
  '2014-08-04',
  '2014-08-05',
  '2014-08-07',
  '2014-08-08',
  '2014-08-09',
  '2014-08-10',
  '2014-08-11',
  '2014-08-12',
  '2014-08-13',
  '2014-08-14',
  '2014-08-15',
  '2014-08-16',
  '2014-08-17',
  '2014-08-18',
  '2014-08-19',
  '2014-08-20',
  '2014-08-21',
  '2014-08-22',
  '2014-08-23',
  '2014-08-24',
  '2014-08-25',
  '2014-08-26',
  '2014-08-27',
  '2014-08-28',
  '2014-08-29',
  '2014-08-30',
  '2014-08-31',
  '2014-09-01',
  '2014-09-02',
  '2014-09-03',
  '2014-09-04',
  '2014-09-05',
  '2014-09-06',
  '2014-09-07',
  '2014-09-08',
  '2014-09-09',
  '2014-09-10',
  '2014-09-11',
  '2014-09-12',
  '2014-09-13',
  '2014-09-14',
  '2014-09-15',
  '2014-09-16',
  '2014-09-17',
  '2014-09-18',
  '2014-09-19',
  '2014-09-20',
  '2014-09-21',
  '2014-09-22',
  '2014-09-23',
  '2014-09-29',
  '2014-09-30',
  '2014-10-01',
  '2014-10-02',
  '2014-10-03',
  '2014-10-04',
  '2014-10-05',
  '2014-10-06',
  '2014-10-07',
  '2014-10-08',
  '2014-10-09',
  '2014-10-10',
  '2014-10-11',
  '2014-10-12',
  '2014-10-13',
  '2014-10-14',
  '2014-10-15',
  '2014-10-16',
  '2014-10-17',
  '2014-10-18',
  '2014-10-19',
  '2014-10-20',
  '2014-10-21',
  '2014-10-22',
  '2014-10-23',
  '2014-10-24',
  '2014-10-25',
  '2014-10-26',
  '2014-10-27',
  '2014-10-28',
  '2014-10-29',
  '2014-10-30',
  '2014-10-31',
  '2014-11-01',
  '2014-11-02',
  '2014-11-03',
  '2014-11-04',
  '2014-11-05',
  '2014-11-06',
  '2014-11-07',
  '2014-11-08',
  '2014-11-09',
  '2014-11-14',
  '2014-11-23',
  '2014-11-24',
  '2014-11-25',
  '2014-11-26',
  '2014-11-27',
  '2014-11-28',
  '2014-11-29',
  '2014-11-30',
  '2014-12-01',
  '2014-12-02',
  '2014-12-03',
  '2014-12-04',
  '2014-12-05',
  '2014-12-06',
  '2014-12-07',
  '2014-12-08',
  '2014-12-09',
  '2014-12-10',
  '2014-12-11',
  '2014-12-12',
  '2014-12-13',
  '2014-12-14',
  '2014-12-15',
  '2014-12-16',
  '2014-12-17',
  '2014-12-18',
  '2014-12-19',
  '2014-12-21',
  '2014-12-22',
  '2014-12-23',
  '2014-12-24',
  '2014-12-25',
  '2014-12-26',
  '2014-12-27',
  '2014-12-28',
  '2014-12-29',
  '2014-12-30',
  '2014-12-31',
  '2015-01-01',
  '2015-01-02',
  '2015-01-03',
  '2015-01-04',
  '2015-01-05',
  '2015-01-06',
  '2015-01-07',
  '2015-01-08',
  '2015-01-09',
  '2015-01-10',
  '2015-01-11',
  '2015-01-12',
  '2015-01-13',
  '2015-01-14',
  '2015-01-15',
  '2015-01-16',
  '2015-01-17',
  '2015-01-18',
  '2015-01-19',
  '2015-01-20',
  '2015-01-21',
  '2015-01-22',
  '2015-01-23',
  '2015-01-24',
  '2015-01-25',
  '2015-01-26',
  '2015-01-27',
  '2015-01-28',
  '2015-01-29',
  '2015-01-30',
  '2015-01-31',
  '2015-02-01',
  '2015-02-02',
  '2015-02-03',
  '2015-02-04',
  '2015-02-05',
  '2015-02-06',
  '2015-02-07',
  '2015-02-08',
  '2015-02-09',
  '2015-02-10',
  '2015-02-11',
  '2015-02-12',
  '2015-02-13',
  '2015-02-14',
  '2015-02-15',
  '2015-02-16',
  '2015-02-17',
  '2015-02-18',
  '2015-02-19',
  '2015-02-20',
  '2015-02-21',
  '2015-02-22',
  '2015-02-23',
  '2015-02-24',
  '2015-02-25',
  '2015-02-26',
  '2015-02-27',
  '2015-02-28',
  '2015-03-01',
  '2015-03-02',
  '2015-03-03',
  '2015-03-04',
  '2015-03-05',
  '2015-03-06',
  '2015-03-07',
  '2015-03-09',
  '2015-03-10',
  '2015-03-11',
  '2015-03-12',
  '2015-03-13',
  '2015-03-14',
  '2015-03-15',
  '2015-03-16',
  '2015-03-17',
  '2015-03-18',
  '2015-03-19',
  '2015-03-20',
  '2015-03-21',
  '2015-03-22',
  '2015-03-23',
  '2015-03-24',
  '2015-03-25',
  '2015-03-26',
  '2015-03-27',
  '2015-03-28',
  '2015-03-29',
  '2015-03-30',
  '2015-03-31',
  '2015-04-01',
  '2015-04-02',
  '2015-04-03',
  '2015-04-04',
  '2015-04-05',
  '2015-04-06',
  '2015-04-07',
  '2015-04-08',
  '2015-04-09',
  '2015-04-10',
  '2015-04-11',
  '2015-04-12',
  '2015-04-13',
  '2015-04-14',
  '2015-04-15',
  '2015-04-16',
  '2015-04-17',
  '2015-04-18',
  '2015-04-19',
  '2015-04-20',
  '2015-04-21',
  '2015-04-22',
  '2015-04-23',
  '2015-04-24',
  '2015-04-25',
  '2015-04-26',
  '2015-04-27',
  '2015-04-28',
  '2015-04-29',
  '2015-04-30',
  '2015-05-01',
  '2015-05-02',
  '2015-05-03',
  '2015-05-04',
  '2015-05-05',
  '2015-05-06',
  '2015-05-07',
  '2015-05-08',
  '2015-05-09',
  '2015-05-10',
  '2015-05-11',
  '2015-05-12',
  '2015-05-13',
  '2015-05-14',
  '2015-05-15',
  '2015-05-16',
  '2015-05-17',
  '2015-05-18',
  '2015-05-19',
  '2015-05-20',
  '2015-05-21',
  '2015-05-22',
  '2015-05-23',
  '2015-05-24',
  '2015-05-25',
  '2015-05-26',
  '2015-05-27',
  '2015-05-28',
  '2015-05-29',
  '2015-05-30',
  '2015-05-31',
  '2015-06-01',
  '2015-06-02',
  '2015-06-03',
  '2015-06-04',
  '2015-06-06',
  '2015-06-07',
  '2015-06-08',
  '2015-06-09',
  '2015-06-10',
  '2015-06-11',
  '2015-06-12',
  '2015-06-13',
  '2015-06-14',
  '2015-06-15',
  '2015-06-16',
  '2015-06-17',
  '2015-06-18',
  '2015-06-19',
  '2015-06-20',
  '2015-06-21',
  '2015-06-22',
  '2015-06-24',
  '2015-06-25',
  '2015-06-26',
  '2015-06-27',
  '2015-06-28',
  '2015-06-29',
  '2015-06-30',
  '2015-07-01',
  '2015-07-02',
  '2015-07-03',
  '2015-07-04',
  '2015-07-05',
  '2015-07-06',
  '2015-07-07',
  '2015-07-09',
  '2015-07-10',
  '2015-07-11',
  '2015-07-12',
  '2015-07-13',
  '2015-07-14',
  '2015-07-15',
  '2015-07-16',
  '2015-07-17',
  '2015-07-18',
  '2015-07-19',
  '2015-07-20',
  '2015-07-21',
  '2015-07-22',
  '2015-07-23',
  '2015-07-24',
  '2015-07-25',
  '2015-07-26',
  '2015-07-27',
  '2015-07-28',
  '2015-07-29',
  '2015-07-30',
  '2015-07-31',
  '2015-08-01',
  '2015-08-02',
  '2015-08-03',
  '2015-08-04',
  '2015-08-05',
  '2015-08-06',
  '2015-08-07',
  '2015-08-08',
  '2015-08-09',
  '2015-08-10',
  '2015-08-11',
  '2015-08-12',
  '2015-08-13',
  '2015-08-14',
  '2015-08-16',
  '2015-08-17',
  '2015-08-18',
  '2015-08-19',
  '2015-08-20',
  '2015-08-21',
  '2015-08-22',
  '2015-08-23',
  '2015-08-24',
  '2015-08-25',
  '2015-08-26',
  '2015-08-27',
  '2015-08-28',
  '2015-08-29',
  '2015-08-30',
  '2015-08-31',
  '2015-09-01',
  '2015-09-02',
  '2015-09-03',
  '2015-09-04',
  '2015-09-05',
  '2015-09-06',
  '2015-09-07',
  '2015-09-08',
  '2015-09-09',
  '2015-09-10',
  '2015-09-11',
  '2015-09-12',
  '2015-09-13',
  '2015-09-14',
  '2015-09-15',
  '2015-09-16',
  '2015-09-19',
  '2015-09-20',
  '2015-09-21',
  '2015-09-22',
  '2015-09-23',
  '2015-09-24',
  '2015-09-25',
  '2015-09-26',
  '2015-09-27',
  '2015-09-28',
  '2015-09-29',
  '2015-09-30',
  '2015-10-01',
  '2015-10-02',
  '2015-10-03',
  '2015-10-04',
  '2015-10-05',
  '2015-10-06',
  '2015-10-07',
  '2015-10-08',
  '2015-10-09',
  '2015-10-10',
  '2015-10-11',
  '2015-10-12',
  '2015-10-13',
  '2015-10-14',
  '2015-10-15',
  '2015-10-16',
  '2015-10-17',
  '2015-10-18',
  '2015-10-19',
  '2015-10-20',
  '2015-10-21',
  '2015-10-22',
  '2015-10-23',
  '2015-10-24',
  '2015-10-25',
  '2015-10-26',
  '2015-10-27',
  '2015-10-28',
  '2015-10-29',
  '2015-10-30',
  '2015-10-31',
  '2015-11-01',
  '2015-11-02',
  '2015-11-03',
  '2015-11-04',
  '2015-11-05',
  '2015-11-06',
  '2015-11-07',
  '2015-11-08',
  '2015-11-09',
  '2015-11-10',
  '2015-11-11',
  '2015-11-12',
  '2015-11-13',
  '2015-11-14',
  '2015-11-15',
  '2015-11-16',
  '2015-11-17',
  '2015-11-18',
  '2015-11-19',
  '2015-11-20',
  '2015-11-21',
  '2015-11-22',
  '2015-11-23',
  '2015-11-24',
  '2015-11-25',
  '2015-11-26',
  '2015-11-28',
  '2015-11-29',
  '2015-11-30',
  '2015-12-01',
  '2015-12-02',
  '2015-12-03',
  '2015-12-04',
  '2015-12-05',
  '2015-12-06',
  '2015-12-07',
  '2015-12-08',
  '2015-12-09',
  '2015-12-10',
  '2015-12-11',
  '2015-12-12',
  '2015-12-13',
  '2015-12-14',
  '2015-12-15',
  '2015-12-17',
  '2015-12-19',
  '2015-12-20',
  '2015-12-21',
  '2015-12-22',
  '2015-12-23',
  '2015-12-24',
  '2015-12-25',
  '2015-12-26',
  '2015-12-27',
  '2015-12-28',
  '2015-12-29',
  '2015-12-30',
  '2015-12-31'])

In [14]:
stock_ids = [i for i in range(len(stock_names))]
stock_name_to_ids = dict(zip(stock_names, stock_ids))
stock_name_to_ids

{'AAPL': 0,
 'ABB': 1,
 'ABBV': 2,
 'AEP': 3,
 'AGFS': 4,
 'AMGN': 5,
 'AMZN': 6,
 'BA': 7,
 'BABA': 8,
 'BAC': 9,
 'BBL': 10,
 'BCH': 11,
 'BHP': 12,
 'BP': 13,
 'BRK-A': 14,
 'BSAC': 15,
 'BUD': 16,
 'C': 17,
 'CAT': 18,
 'CELG': 19,
 'CHL': 20,
 'CHTR': 21,
 'CMCSA': 22,
 'CODI': 23,
 'CSCO': 24,
 'CVX': 25,
 'D': 26,
 'DHR': 27,
 'DIS': 28,
 'DUK': 29,
 'EXC': 30,
 'FB': 31,
 'GD': 32,
 'GE': 33,
 'GOOG': 34,
 'HD': 35,
 'HON': 36,
 'HRG': 37,
 'HSBC': 38,
 'IEP': 39,
 'INTC': 40,
 'JNJ': 41,
 'JPM': 42,
 'KO': 43,
 'LMT': 44,
 'MA': 45,
 'MCD': 46,
 'MDT': 47,
 'MMM': 48,
 'MO': 49,
 'MRK': 50,
 'MSFT': 51,
 'NEE': 52,
 'NGG': 53,
 'NVS': 54,
 'ORCL': 55,
 'PCG': 56,
 'PCLN': 57,
 'PEP': 58,
 'PFE': 59,
 'PG': 60,
 'PICO': 61,
 'PM': 62,
 'PPL': 63,
 'PTR': 64,
 'RDS-B': 65,
 'REX': 66,
 'SLB': 67,
 'SNP': 68,
 'SNY': 69,
 'SO': 70,
 'SPLP': 71,
 'SRE': 72,
 'T': 73,
 'TM': 74,
 'TOT': 75,
 'TSM': 76,
 'UL': 77,
 'UN': 78,
 'UNH': 79,
 'UPS': 80,
 'UTX': 81,
 'V': 82,
 'VZ': 83,
 'WFC': 84,
 'WMT': 85,
 'XOM': 86}

In [ ]:
tokens_file = dataset_dir / "all_tweets_tokenized.jsonl"
bad_data_file = dataset_dir / "bad_data.jsonl"

buffer = []
buffer_size = 100_000
lines = 0


with open(json_file, "r", encoding="utf-8") as f, open(tokens_file, "w", encoding="utf-8") as o, open(bad_data_file, "w", encoding="utf-8") as b:
    for line in f:

        entry = json.loads(line)

        stock_name = entry["stock"]
        tweet = entry["tweet"]
        date = entry["date"]


        patterns = [
            rf"\${stock_name}(?=\s|$|\W)", # strict match
            rf"\${stock_name}" # loose match
        ]

        success = False
        for pattern in patterns:
            masked_tweet = re.sub(pattern, "<MASK>", tweet, flags=re.IGNORECASE)
            masked_tweet_tokenized = slot_spm.encode(masked_tweet)

            if mask_id in masked_tweet_tokenized:
                mask_idx = masked_tweet_tokenized.index(mask_id)
                success = True
                break

        if not success:
            bad_entry = {
                "stock": stock_name,
                "tweet": slot_spm.decode(masked_tweet_tokenized)
            }
            b.write(json.dumps(bad_entry) + "\n")
            continue

        # masked_tweet_tokenized = [
        #     tok if tok not in rare_tokens else unk_id
        #     for tok in masked_tweet_tokenized
        # ]


        tokenized_tweet = {
            "date": date,
            "tweet": masked_tweet_tokenized,
            "stock_id": stock_name_to_ids[stock_name],
            "mask_idx": mask_idx
        }


        buffer.append(json.dumps(tokenized_tweet))

        if len(buffer) >= buffer_size:
            o.write("\n".join(buffer) + "\n")
            lines += len(buffer)
            buffer.clear()

            print(f"{lines} lines written")

    if buffer:
        o.write("\n".join(buffer) + "\n")
        lines += len(buffer)
        print(f"{lines} lines written")

100000 lines written
119768 lines written

### Put all the data into lists

In [15]:

tweet_tokens_by_date = [[] for i in range(num_dates)]
mask_indices_by_date = [[] for i in range(num_dates)]


tweet_tokens = []
mask_indices = []
y = []

with open(tokens_file, "r") as f:
    for line in f:
        entry = json.loads(line)

        tokens = [int(tok) for tok in entry["tweet"]]
        idx = entry["mask_idx"]

        tweet_tokens.append(tokens)
        mask_indices.append(idx)
        y.append(entry["stock_id"])

        if entry["date"] in all_dates:
            date = all_dates.index(entry["date"])
            tweet_tokens_by_date[date].append(tokens)
            mask_indices_by_date[date].append(idx)

In [16]:
for i in range(5):
    print(all_dates[i] + ":", tweet_tokens_by_date[i])
    print(all_dates[i] + ":", mask_indices_by_date[i])
    print()

2014-02-19: [[18, 7, 14, 12, 10, 13, 9, 183, 49, 300, 35, 7, 3, 16, 6, 2101, 1470, 1464, 17, 257, 35, 397, 11, 1745, 48, 1800, 11, 5043, 53, 26, 2242, 2118, 1184, 368, 57, 7789, 414, 16, 1384, 820, 8], [7, 3, 35, 233, 939, 426, 381, 95, 137, 3241, 58, 22, 60, 47, 11, 180, 15, 650, 3447, 238, 33, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [749, 37, 835, 79, 2801, 82, 7, 1887, 358, 200, 876, 6, 6241, 6, 4321, 6, 29, 7, 3, 9, 431, 8], [7, 3, 276, 88, 250, 22, 401, 1920, 93, 3295, 20, 5283], [18, 7, 14, 12, 10, 13, 1072, 196, 8150, 3233, 40, 82, 157, 1725, 27, 6, 1362, 17, 6, 254, 7, 3, 9, 4634, 9, 120, 7187, 9, 5414, 9, 1525, 1228, 122, 8], [18, 7, 14, 12, 10, 13, 1072, 196, 8150, 3233, 40, 82, 157, 1725, 27, 6, 1362, 17, 6, 254, 7, 3, 9, 4634, 9, 120, 7187, 9, 5414, 9, 1525, 1228, 122, 8], [8, 367, 228, 3128, 2779, 28, 27, 60, 37, 4345, 1739, 16, 277, 256, 16, 363, 28, 23, 1242, 244, 33, 8, 6, 7476, 6, 131, 7, 3, 6, 55], [7, 3, 35, 825, 4663, 1356, 2323, 66, 798, 89, 447, 11], [18, 7, 14, 12, 10, 13, 1072, 196, 8150, 3233, 40, 82, 157, 1725, 27, 6, 1362, 17, 6, 254, 7, 3, 9, 4634, 9, 120, 7187, 9, 5414, 9, 1525, 1228, 122, 8], [9, 63, 597, 11, 335, 105, 184, 6, 755, 6, 4568, 6, 433, 7, 3, 9, 1028, 8], [7, 3, 221, 100, 7, 14, 12, 10, 13, 8, 7, 19, 11], [7, 3, 221, 100, 7, 14, 12, 10, 13, 8, 7, 19, 11], [18, 7, 14, 12, 10, 13, 4851, 967, 46, 1066, 6864, 7099, 57, 7, 15, 94, 15, 229, 8, 7, 3], [7, 3, 68, 334, 25, 82, 1753, 4140, 35, 8, 8], [7, 14, 12, 10, 13, 5278, 2573, 11, 354, 167, 22, 1719, 3088, 41, 7300, 7, 3, 1613, 455, 52, 1017, 34, 6456, 46, 252, 1647, 11, 394, 28, 222, 445, 330, 70, 238, 811, 15], [18, 7, 14, 12, 10, 13, 1072, 196, 8150, 3233, 40, 82, 157, 1725, 27, 6, 1362, 17, 6, 254, 7, 3, 9, 4634, 9, 120, 7187, 9, 5414, 9, 1525, 1228, 122, 8], [7, 3, 297, 35, 797, 150, 25, 906, 6242, 1892, 272, 901, 11, 506, 20, 151, 202, 5527, 797, 150, 1023, 8], [288, 28, 15, 82, 9, 1076, 2172, 460, 41, 1622, 765, 143, 15, 44, 945, 76, 40, 162, 236, 1313, 697, 1519, 44, 8, 6, 51, 6, 29, 7, 3], [7, 3, 1391, 20, 2721, 57, 4104, 3311, 304, 2015, 1248, 1859, 1749, 8], [1242, 242, 2974, 70, 5768, 1822, 20, 1162, 1263, 8, 6, 74, 6, 38, 1046, 15, 6, 1381, 7, 3], [193, 113, 45, 36, 111, 114, 264, 257, 154, 733, 26, 1729, 228, 6, 74, 413, 317, 356, 26, 7, 3, 4161, 69, 4478, 15, 114, 8], [709, 475, 16, 3114, 222, 125, 25, 11, 330, 842, 81, 91, 7298, 15, 3224, 2270, 179, 194, 34, 8, 49, 7, 3, 8], [7, 3, 221, 100, 2695, 2048, 1315, 16, 8, 1030, 666, 101, 697, 2126, 1471, 142, 81, 138, 16, 72, 265, 797, 150, 69, 28, 15, 359, 3330, 11], [8, 367, 228, 3128, 2779, 28, 27, 60, 37, 4345, 1739, 16, 277, 256, 16, 363, 28, 23, 1242, 244, 33, 8, 6, 7476, 7, 3, 6, 19, 6, 55], [7, 3, 11, 35, 5655, 674, 792, 4407, 34, 2585, 703, 8], [851, 1554, 711, 1164, 319, 1816, 705, 38, 2866, 57, 285, 34, 421, 17, 195, 1835, 176, 1613, 2000, 1475, 812, 7, 3, 8], [7, 3, 285, 34, 421, 173, 48, 67, 53, 90, 16, 202, 28, 15, 201, 27, 285, 34, 421, 39, 8], [7, 3, 287, 723, 737, 884, 43, 37, 994, 5206, 321, 737, 1230, 11, 1781, 200, 737, 1230, 11, 1296, 287, 737, 2164, 11, 316, 392, 737, 1230, 11, 1280, 360, 737, 1556, 1745, 1544, 8], [563, 1485, 517, 62, 408, 1799, 2486, 408, 26, 24, 3488, 161, 3, 2407, 17, 7, 5571, 498, 156, 43, 1380, 229, 743, 75, 17, 40, 1799, 238, 863, 619, 2029, 493, 354, 457, 1200, 129, 354, 871, 15, 17, 2116, 81, 1463, 145, 568, 146, 229, 17, 568, 2113, 39], [375, 2754, 3398, 3245, 193, 5965, 6062, 70, 83, 170, 2548, 2341, 15, 170, 1337, 15, 711, 255, 7, 3, 2105, 30, 2757, 8, 48, 1532, 165, 605, 170, 7, 14, 12, 10, 13], [7, 3, 730, 47, 11, 3924, 15, 61, 425, 27, 621, 2293, 408, 173, 11, 48, 4685, 53, 8], [639, 76, 71, 242, 160, 17, 1670, 222, 145, 2244, 1020, 999, 2215, 240, 239, 100, 278, 46, 105, 96, 426, 1540, 11, 7, 3, 8], [335, 24, 201, 7, 3, 6, 4562, 6, 142, 75, 6, 2332, 810, 8], [7, 3, 439, 11, 38, 11, 38, 11, 20, 379, 669, 26, 1093, 2141, 6107, 180, 8], [546, 28, 15, 123, 3109, 5283, 267, 137, 267, 17, 243, 41, 69, 25, 214, 39, 8, 7, 3, 9, 2702], [7, 3, 35, 41, 4394, 24, 320, 15, 516, 1069, 565, 39, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [196, 2010, 27, 7, 3, 8], [7, 3, 35, 546, 2100, 15, 3165, 3322, 2704, 15, 27, 685, 2673, 1012, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [6, 1750, 6, 83, 7, 3, 8], [5650, 16, 466, 8236, 57, 6, 1754, 8, 6, 102, 7, 3, 6, 526], [1000, 41, 185, 342, 15, 7, 2826, 492, 7, 39, 15, 73, 3682, 919, 39, 3], [1313, 3338, 73, 556, 44, 9, 289, 3338, 1417, 418, 2834, 9, 54, 11, 54, 11, 54, 9, 3, 9, 258, 1105, 9, 153, 4195, 52, 9, 3915, 304, 2809, 8], [162, 89, 391, 26, 7, 3, 6, 4025, 6, 1100, 6, 895, 251, 8], [639, 46, 156, 1191, 26, 6, 1484, 23, 6, 1690, 6, 259, 7, 3, 68, 1036, 8], [9, 42, 20, 214, 6, 5499, 6, 4464, 6, 1653, 7, 3, 9, 1003, 8], [60, 1657, 7, 15, 94, 15, 229, 4851, 6864, 7099, 7, 3, 9, 661, 8], [7, 3, 3407, 24, 3275, 26, 72, 265, 106, 59, 11], [327, 447, 1057, 26, 7, 3, 143, 88, 3959, 69, 257, 11, 4708, 337, 11], [7, 14, 12, 10, 13, 7, 14, 12, 10, 13, 1808, 17, 7, 3, 447, 1353, 27, 2965, 2420, 11, 1000, 41, 6, 51, 2826, 143, 50, 991, 394, 107, 92, 447, 146, 15, 330, 70, 400, 568], [104, 14, 12, 10, 13, 104, 14, 12, 10, 13, 110, 7, 3, 22, 1739, 5738, 71, 1353, 130, 65, 326, 1245, 3677, 160, 1691, 39, 3682, 65, 326, 1245, 601, 363, 28, 23, 3928, 213, 27, 7, 1564, 69, 6324], [18, 7, 14, 12, 10, 13, 7, 3, 20, 1235, 1353, 27, 240, 2965, 291], [18, 7, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [18, 7, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [7, 3, 257, 132, 40, 373, 3453, 11], [18, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [18, 7, 14, 12, 10, 13, 2524, 25, 38, 5644, 170, 7, 3, 9, 661, 6977, 85, 35, 258, 859, 5353, 3399, 212, 3215, 2111, 566, 290, 4249, 1079, 25, 354, 1151, 170, 1353, 966, 2965, 43, 48, 3538, 384, 25, 38, 5644, 53, 33], [18, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [110, 447, 1353, 27, 2965, 4463, 7, 3, 8], [3877, 145, 406, 406, 7, 14, 12, 10, 13, 746, 16, 110, 20, 61, 1353, 27, 240, 2965, 291, 568, 40, 49, 7, 3, 476], [18, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3, 1685, 229, 2299, 17, 1471, 4013, 2783, 1076, 605, 15, 651, 307, 3203, 4533, 15, 170, 1353, 11], [1031, 18, 16, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [18, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [68, 363, 28, 23, 151, 209, 7, 3, 210, 6597, 91, 1353, 3008, 11, 11, 480, 2932, 3450, 1733, 17, 243, 202, 487, 39, 68, 4662, 69, 210, 92, 393, 2078, 58, 11, 11, 480, 5192, 7, 1570, 4618, 11], [18, 7, 14, 12, 10, 13, 3877, 5324, 2299, 44, 389, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [18, 7, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 7, 3, 521, 15, 2965, 43, 27, 367, 1230, 15, 1679, 23, 1568, 202, 28, 15, 5640, 11, 1710, 36, 202, 39, 2492, 11, 110, 521, 15, 2965, 43, 27, 367, 733, 215, 1353, 11], [8024, 93, 7, 3, 3044, 748, 291, 39, 11, 33, 2436, 50, 105, 34, 186, 5296, 3422], [18, 7, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 5422, 7, 3, 49, 3093, 245, 1633, 11, 1394, 41, 1174, 1797, 11, 224, 1837, 328, 1059, 694, 4276, 2080, 165, 301, 3166], [18, 7, 14, 12, 10, 13, 110, 1535, 1739, 5738, 71, 1353, 17, 66, 61, 27, 6, 174, 43, 22, 568, 1414, 1964, 43, 22, 110, 194, 7, 3, 6, 31], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 7, 3, 6295, 15, 3125, 26, 90, 141, 110, 66, 61, 1353, 4060, 1152, 46, 685, 8, 8], [1198, 17, 350, 4577, 17, 938, 28, 15, 193, 1833, 11, 141, 1959, 1392, 28, 23, 538, 447, 76, 7, 3, 49], [18, 7, 14, 12, 10, 13, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 739, 16, 8, 7, 3], [18, 7, 14, 12, 10, 13, 389, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3, 476, 492, 7, 3934, 44], [18, 7, 14, 12, 10, 13, 90, 240, 1353, 6, 908, 291, 1632, 2055, 110, 194, 257, 3125, 22, 245, 37, 4133, 196, 11, 8, 7, 3], [746, 16, 7, 14, 12, 10, 13, 20, 1235, 7, 14, 12, 10, 13, 27, 240, 2965, 291, 11, 541, 7, 3], [18, 7, 14, 12, 10, 13, 194, 34, 110, 1218, 233, 3590, 20, 6, 2624, 11, 1204, 22, 245, 37, 4133, 196, 245, 90, 34, 1353, 383, 11, 8, 7, 3], [1377, 2660, 41, 209, 24, 1353, 1929, 264, 4295, 57, 7, 3, 7, 11], [18, 7, 14, 12, 10, 13, 18, 7, 14, 12, 10, 13, 71, 2154, 34, 1353, 17, 7, 3, 8031, 58, 97, 1304, 34, 24, 771, 4060, 1152, 46, 88, 48, 4249, 590, 30, 46, 20, 72, 221, 53, 8], [2682, 20, 159, 693, 44, 7, 3, 6, 64, 6, 226, 6, 203, 6, 42], [110, 47, 7, 16, 7, 3253, 3230, 1865, 41, 3551, 142, 1330, 2660, 58, 27, 7, 2402, 1633, 22, 627, 423, 5407, 590, 28, 15, 1701, 8, 7, 3], [18, 7, 14, 12, 10, 13, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 739, 16, 8, 7, 3], [18, 7, 14, 12, 10, 13, 746, 16, 110, 28, 15, 5905, 2965, 291, 1353, 2154, 16, 1964, 43, 22, 7, 3, 194, 17, 6, 174, 43, 22, 568, 11, 8], [18, 7, 14, 12, 10, 13, 110, 49, 4494, 26, 90, 34, 1353, 383, 33, 7, 3, 8, 8], [18, 7, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [18, 7, 14, 12, 10, 13, 110, 49, 4494, 26, 90, 34, 1353, 383, 33, 7, 3, 8, 8], [18, 7, 14, 12, 10, 13, 110, 447, 1353, 27, 2965, 43, 8, 7, 3], [1838, 3935, 2491, 9917, 2583, 608, 572, 3073, 2970, 1838, 1495, 2490, 9917, 2556, 2971, 8567, 7, 1462, 458, 2491, 470, 3073, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [18, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [9, 661, 7, 3, 1837, 9, 6059, 27, 6, 908, 43], [18, 7, 14, 12, 10, 13, 110, 49, 4494, 26, 90, 34, 1353, 383, 33, 7, 3, 8, 8], [3541, 57, 7, 14, 12, 10, 13, 2110, 39, 2327, 339, 2116, 323, 1353, 132, 698, 962, 7, 3, 9, 6059, 9, 4356, 5497], [7, 2592, 18, 7, 14, 12, 10, 13, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 739, 16, 8, 7, 3], [18, 7, 14, 12, 10, 13, 18, 7, 14, 12, 10, 13, 110, 48, 3, 53, 5037, 1353, 27, 89, 301, 486, 28, 15, 814, 64, 53, 88, 361, 57, 241, 729, 169, 11], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [7, 14, 12, 10, 13, 1235, 15, 7, 14, 12, 10, 13, 27, 2965, 291, 8, 7, 3], [820, 3697, 170, 423, 2782, 7, 774, 3215, 25, 2061, 7, 3, 796, 3667, 1792, 255, 355, 1030, 3216, 1402], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 90, 240, 1353, 6, 908, 291, 1632, 2055, 110, 194, 257, 3125, 22, 245, 37, 4133, 196, 11, 8, 7, 3], [18, 7, 14, 12, 10, 13, 90, 240, 1353, 6, 908, 291, 1632, 2055, 110, 194, 257, 3125, 22, 245, 37, 4133, 196, 11, 8, 7, 3], [236, 260, 26, 6, 3521, 7, 3, 6, 30, 62, 6, 897, 388, 95, 8], [645, 689, 215, 7, 16, 821, 683, 176, 68, 1012, 20, 4849, 6, 316, 2305, 462, 22, 3513, 17, 1019, 8, 7, 3], [749, 37, 835, 79, 2801, 82, 7, 1887, 358, 200, 876, 6, 6241, 6, 4321, 7, 3, 6, 19, 9, 431, 8], [40, 631, 1816, 7, 3, 705, 127, 2709, 33], [7, 3, 121, 714, 3663, 15, 6, 2539, 462, 40, 4367, 15, 323, 2640, 7, 3324, 16, 121, 714, 3663, 15, 6, 2539, 462, 40, 108, 33, 8], [286, 27, 24, 201, 1081, 165, 150, 6, 80, 6, 6751, 6, 1690, 7, 3, 313, 117, 8], [22, 24, 7, 3, 648, 717, 435, 396, 27, 132, 11, 1204], [18, 7, 14, 12, 10, 13, 121, 396, 7, 5350, 3124, 37, 4215, 518, 367, 28, 5661, 4083, 15, 11, 28, 28, 789, 17, 1463, 145, 44, 369, 9, 1883, 229, 27, 7, 14, 12, 10, 13, 7, 3, 7730, 8], [1096, 125, 3076, 7347, 141, 78, 4958, 30, 20, 2742, 5882, 812, 34, 121, 5629, 16, 7, 15, 11, 280, 11, 17, 5633, 6439, 17, 5015, 313, 17, 683, 6143, 1761, 40, 8159, 7, 432, 3661, 11, 7, 3], [288, 28, 15, 82, 9, 1076, 2172, 460, 41, 1622, 765, 143, 15, 44, 945, 76, 40, 162, 236, 1313, 697, 1519, 44, 8, 6, 51, 7, 3, 6, 19], [286, 20, 1682, 2983, 150, 6, 3051, 7, 3, 6, 142, 30, 1099, 6, 543, 9, 936, 8], [7, 3, 35, 230, 16, 2125, 248, 2899, 15, 116, 2343, 1024, 141, 619, 46, 1243, 4492, 7, 3544, 697, 2047, 54, 2505, 1697, 33, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [196, 2010, 27, 7, 3, 8], [7, 3, 35, 464, 16, 1000, 180, 15, 1096, 125, 8207, 39, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 35, 303, 7, 1973, 1590, 16, 530, 65, 45, 36, 530, 378, 11, 355, 138, 6944, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 202, 7313, 15, 26, 604, 573, 1763, 27, 426, 8], [162, 89, 391, 26, 7, 3, 6, 4967, 6, 38, 52, 438, 6, 2384, 313, 117, 8], [7, 3, 1246, 2408, 93, 621, 11, 52, 11, 767, 2401, 22, 7, 2570, 7, 2572, 8], [7, 3, 836, 37, 942, 5077, 6136, 5264, 7512, 2529, 7, 3136, 1256, 2622, 174, 1384, 194, 48, 5540, 53, 8], [7, 3, 35, 1867, 1908, 474, 1595, 22, 25, 2577, 1561, 71, 4006, 4540, 238, 33, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 1867, 1908, 4799, 68, 43, 38, 37, 791, 662, 6234, 46, 1598, 3164, 46, 2373, 27, 59, 8], [7, 14, 12, 10, 13, 217, 1013, 17, 243, 69, 264, 7, 3, 367, 15, 727, 616, 23, 33], [7, 3, 2333, 1361, 27, 640, 62, 408, 3435, 732, 28, 15, 968, 8], [7, 3, 1538, 111, 1243, 697, 3600, 2174, 319, 20, 2100, 1052, 1611, 3942, 7810, 1424, 160, 59, 8], [7, 3, 3405, 3924, 15, 104, 929, 130, 425, 27, 1171, 65, 45, 36, 146, 48, 204, 53, 8], [7, 3, 202, 60, 210, 1357, 93, 288, 40, 121, 8], [7, 14, 12, 10, 13, 7, 14, 12, 10, 13, 1808, 17, 6, 21, 447, 1353, 27, 2965, 2420, 11, 1000, 41, 7, 3, 2826, 143, 50, 991, 394, 107, 92, 447, 146, 15, 330, 70, 400, 568], [288, 28, 15, 82, 9, 1076, 2172, 460, 41, 1622, 765, 143, 15, 44, 945, 76, 40, 162, 236, 1313, 697, 1519, 44, 8, 7, 3, 6, 29, 6, 19], [2240, 17, 7, 2745, 1090, 394, 28, 222, 4024, 5823, 1996, 46, 218, 1519, 15, 34, 244, 851, 182, 7, 5019, 1042, 7, 3, 6, 2745], [7, 3, 35, 5810, 7582, 6629, 15, 1569, 462, 20, 724, 953, 1577, 5717, 22, 2988, 698, 40, 33, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [286, 27, 24, 201, 1081, 165, 150, 7, 3, 6, 6751, 6, 1690, 6, 29, 313, 117, 8], [7, 3, 239, 3428, 1613, 7652, 176, 169, 37, 6980, 46, 6042, 1255, 5547, 15, 17, 2421, 15, 8], [898, 79, 20, 159, 6, 2961, 6, 4579, 6, 175, 83, 7, 3, 9, 1011, 148, 8], [18, 7, 14, 12, 10, 13, 247, 91, 6521, 20, 392, 26, 6047, 6883, 15, 27, 7, 1554, 86, 493, 7, 7148, 3088, 8, 9, 4292, 9, 7148, 7, 3], [7, 3, 161, 23, 65, 45, 36, 24, 6016, 3328, 37, 2016, 8], [185, 79, 20, 159, 7, 3, 6, 4614, 6, 5620, 6, 4328, 9, 99, 8], [7, 3, 82, 57, 113, 45, 36, 23, 20, 617, 493, 3914, 5521, 468, 2332, 4307, 27, 2431, 71, 972, 3807, 26, 265, 3060, 8], [807, 2485, 2106, 7, 1238, 272, 3704, 2833, 138, 4796, 7914, 247, 821, 20, 145, 653, 23, 2339, 91, 557, 406, 2485, 757, 25, 125, 7, 30, 6690, 3, 807, 2485, 3006, 7, 1252, 3258, 497, 1195, 5546, 621, 238, 7, 101, 1135, 525, 1041, 4653, 673, 4834, 2754, 7914, 83, 4231, 83, 2485, 757], [18, 7, 14, 12, 10, 13, 7, 14, 12, 10, 13, 7, 14, 12, 10, 13, 1679, 846, 307, 4861, 438, 839, 468, 3720, 3720, 3, 919, 120], [7, 3, 49, 723, 737, 884, 43, 37, 994, 5206, 321, 737, 163, 8210, 200, 737, 163, 8210, 287, 737, 1966, 5311, 392, 737, 1966, 5480, 360, 6329, 1190, 1105, 2709, 8], [7, 3, 463, 28, 15, 299, 35, 296, 2897, 173, 48, 4971, 634, 5020, 8159, 830, 165, 2842, 3010, 743, 59, 8], [7, 3, 35, 202, 180, 15, 201, 27, 5655, 674, 792, 39, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 76, 15, 4953, 15, 497, 1551, 390, 41, 2026, 5306, 15, 27, 1241, 698, 34, 2669, 3440, 8], [2264, 3542, 65, 45, 36, 6429, 23, 3568, 17, 8267, 125, 5993, 40, 992, 1430, 5977, 1307, 23, 1436, 23, 15, 59, 7, 3, 8], [7, 3, 1293, 79, 16, 945, 1062, 3258, 4996, 518, 513, 11, 17, 2833, 1427, 617, 215, 17, 2930, 513, 17, 40, 59, 8], [7, 3, 9, 4904, 1468, 1024, 2841, 34, 3615, 194, 1137, 20, 92, 3919, 20, 9, 1985, 83, 73, 1076, 1824, 8], [7, 3, 807, 3965, 37, 540, 336, 7, 2989, 3241, 46, 28, 57, 696, 34, 6031, 5044, 1902], [7, 3, 7, 7842, 857, 2022, 3891, 493, 39, 3830, 1107, 20, 337, 17, 602, 37, 540, 8], [5650, 16, 466, 8236, 57, 6, 1754, 8, 7, 3, 6, 139, 6, 526]]
2014-02-19: [12, 1, 18, 1, 21, 21, 27, 1, 21, 14, 1, 1, 20, 1, 16, 21, 1, 29, 1, 19, 20, 22, 1, 25, 1, 22, 1, 1, 12, 19, 1, 24, 4, 1, 18, 1, 4, 1, 5, 11, 15, 18, 5, 13, 11, 11, 1, 5, 13, 12, 7, 17, 17, 1, 19, 12, 19, 7, 23, 19, 21, 19, 7, 26, 17, 35, 7, 3, 17, 35, 35, 8, 28, 35, 35, 7, 20, 19, 24, 26, 21, 30, 11, 18, 6, 28, 19, 21, 16, 17, 16, 14, 35, 19, 3, 16, 18, 21, 14, 35, 17, 11, 35, 26, 26, 6, 22, 16, 4, 1, 14, 3, 38, 38, 27, 8, 1, 4, 1, 1, 1, 5, 1, 1, 1, 1, 12, 1, 1, 1, 1, 23, 25, 23, 1, 8, 1, 12, 29, 1, 5, 1, 28, 25, 1, 1, 1, 1, 23, 1, 1, 1, 1, 9]


### Pad the token data and shuffle

In [17]:
max_len = max(len(tweet) for tweet in tweet_tokens)


X = [tweet + [pad_id] * (max_len - len(tweet))
    for tweet in tweet_tokens]


X = torch.tensor(X, dtype=torch.long)
y = torch.tensor(y, dtype=torch.long)
mask_indices = torch.tensor(mask_indices, dtype=torch.long)

perm = torch.randperm(X.size(0))
X, y, mask_indices = X[perm], y[perm], mask_indices[perm]

X, X.shape, y, y.shape, mask_indices, mask_indices.shape

(tensor([[  25, 1091, 1369,  ...,    4,    4,    4],
         [  18,    7,   14,  ...,    4,    4,    4],
         [  18,    7,   14,  ...,    4,    4,    4],
         ...,
         [  78,   50,    7,  ...,    4,    4,    4],
         [ 184,  121,   41,  ...,    4,    4,    4],
         [   6, 1330,   49,  ...,    4,    4,    4]]),
 torch.Size([119768, 147]),
 tensor([ 8, 59, 73,  ..., 26,  0, 18]),
 torch.Size([119768]),
 tensor([24, 20, 10,  ...,  7, 14, 20]),
 torch.Size([119768]))

In [18]:
# (num_dates, num_tweets_for_that_date, seq_len)
X_by_date = [
    torch.tensor(
        [tweet + [pad_id] * (max_len - len(tweet)) for tweet in tweet_tokens_by_date[d]],
        dtype=torch.long
    )
    for d in range(num_dates)
]

mask_indices_by_date = [
    torch.tensor(mask_indices_by_date[d], dtype=torch.long)
    for d in range(num_dates)
]

X_by_date[0], X_by_date[0].shape, mask_indices_by_date[0], mask_indices_by_date[0].shape

(tensor([[  18,    7,   14,  ...,    4,    4,    4],
         [   7,    3,   35,  ...,    4,    4,    4],
         [ 749,   37,  835,  ...,    4,    4,    4],
         ...,
         [   7,    3,  807,  ...,    4,    4,    4],
         [   7,    3,    7,  ...,    4,    4,    4],
         [5650,   16,  466,  ...,    4,    4,    4]]),
 torch.Size([154, 147]),
 tensor([12,  1, 18,  1, 21, 21, 27,  1, 21, 14,  1,  1, 20,  1, 16, 21,  1, 29,
          1, 19, 20, 22,  1, 25,  1, 22,  1,  1, 12, 19,  1, 24,  4,  1, 18,  1,
          4,  1,  5, 11, 15, 18,  5, 13, 11, 11,  1,  5, 13, 12,  7, 17, 17,  1,
         19, 12, 19,  7, 23, 19, 21, 19,  7, 26, 17, 35,  7,  3, 17, 35, 35,  8,
         28, 35, 35,  7, 20, 19, 24, 26, 21, 30, 11, 18,  6, 28, 19, 21, 16, 17,
         16, 14, 35, 19,  3, 16, 18, 21, 14, 35, 17, 11, 35, 26, 26,  6, 22, 16,
          4,  1, 14,  3, 38, 38, 27,  8,  1,  4,  1,  1,  1,  5,  1,  1,  1,  1,
         12,  1,  1,  1,  1, 23, 25, 23,  1,  8,  1, 12, 29,  1,  5,  1, 28, 25,
          1,  1,  1,  1, 23,  1,  1,  1,  1,  9]),
 torch.Size([154]))

### Train/val/test split

In [19]:
data_len = len(y)

train_end = int(data_len * 0.90)
val_end = int(data_len * 1.00)

X_train, y_train, mask_train = X[ : train_end], y[ : train_end], mask_indices[ : train_end]
X_val, y_val, mask_val = X[train_end : val_end], y[train_end : val_end], mask_indices[train_end : val_end]
# X_test, y_test, mask_test = X[val_end : ], y[val_end : ], mask_indices[val_end : ]

print(f"X_train shape: {X_train.shape}. y_train shape: {y_train.shape}")
print(f"X_val shape: {X_val.shape}. y_val shape: {y_val.shape}")
# print(f"X_test shape: {X_test.shape}. y_test shape: {y_test.shape}")

mask_train.shape, mask_val.shape #, mask_test.shape

X_train shape: torch.Size([107791, 147]). y_train shape: torch.Size([107791])
X_val shape: torch.Size([11977, 147]). y_val shape: torch.Size([11977])

(torch.Size([107791]), torch.Size([11977]))

### Datasets

In [ ]:
class SLOTTokensDataset(Dataset):
    def __init__(self, x, y, mask_idx):
        self.x = x
        self.y = y
        self.mask_idx = mask_idx

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx], self.mask_idx[idx]

In [ ]:
train_dataset = SLOTTokensDataset(X_train, y_train, mask_train)
val_dataset = SLOTTokensDataset(X_val, y_val, mask_val)
# test_dataset = SLOTTokensDataset(X_test, y_test, mask_test)

train_dataset[0]

(tensor([  25, 1091, 1369,   68,   28,   54,  883, 4367,   15,   26,   37,    6,
           64,   17,    6, 1164,   17,    6, 4474,   17,    6, 4895,   17,    7,
            3,   17,    6, 2241,   11,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4]),
 tensor(8),
 tensor(24))

In [ ]:
train_size = int(0.5 * len(train_dataset))
val_size = int(0.5 * len(val_dataset))


train_subset, _ = random_split(train_dataset, [train_size, len(train_dataset) - train_size])
val_subset, _ = random_split(val_dataset, [val_size, len(val_dataset) - val_size])

len(train_subset), len(val_subset)

(53895, 5988)

### Model Definition

In [20]:

class StockIdentification(nn.Module):
    def __init__(self, num_stocks, embd_size, hidden_size, vocab_size, dropout, temp):
        super().__init__()
        self.H = hidden_size
        self.temp = temp


        self.stock_embd = nn.Embedding(num_embeddings=num_stocks, embedding_dim=2*hidden_size)


        self.token_embd = nn.Embedding(num_embeddings=vocab_size,
                                       embedding_dim=embd_size,
                                       padding_idx=pad_id)


        self.bi_lstm = nn.LSTM(
            input_size=embd_size,
            hidden_size=hidden_size,
            bidirectional=True,
            batch_first=True,
        )

        self.dropout = nn.Dropout(dropout)

        self.init_weights()

    def init_weights(self):
        nn.init.normal_(self.token_embd.weight, mean=0.0, std=0.01)
        nn.init.normal_(self.stock_embd.weight, mean=0.0, std=0.01)

        for name, param in self.bi_lstm.named_parameters():
            if "bias" in name:
                nn.init.zeros_(param)
                # set forget gate bias to 1
                # [i, f, g, o]
                param.data[self.H : 2*self.H].fill_(1.0)
            elif "weight_ih" in name:
                nn.init.kaiming_normal_(param)
            elif "weight_hh" in name:
                nn.init.orthogonal_(param)


    def forward(self, x, mask_indices):
        # x: (B, T)
        # mask_indices: (B,). The index of the <MASK> token for each tweet
        batch_size = x.size(0)
        token_embs = self.token_embd(x) # (B, T, embd_size)
        token_embs = self.dropout(token_embs)

        seq_lengths = (x != pad_id).sum(dim=-1).to("cpu")
        packed_token_embs = pack_padded_sequence(token_embs, seq_lengths, batch_first=True, enforce_sorted=False)

        # output: (B, T, 2*hidden_size)
        # h_n, c_n : (2*num_layers, B, hidden_size)
        output, (h_n, c_n) = self.bi_lstm(packed_token_embs)

        output, _ = pad_packed_sequence(output, batch_first=True)

        output = self.dropout(output)

        h_e = output[torch.arange(batch_size), mask_indices] # (B, 2*hidden_size)

        h_s = self.stock_embd.weight # (num_stocks, 2*hidden_size)
        h_e = F.normalize(h_e, dim=-1)
        h_s = F.normalize(h_s, dim=-1)
        logits = torch.matmul(h_e, h_s.T) #  (B, 2*hidden_size) @ (2*hidden_size, num_stocks) -> (B, num_stocks)


        return logits / self.temp, h_e, h_s

### Evaluation Functions

In [21]:
stock_id_to_name = {v: k for k, v in stock_name_to_ids.items()}

stock_queries = ["AAPL", "FB", "BA", "BAC"]
stock_query_ids = [stock_name_to_ids[name] for name in stock_queries]

In [22]:
tweet_files_stocks = [tweet.parent.name for tweet in tweet_files_list]
stock_counts = Counter(tweet_files_stocks)

stock_counts = torch.tensor([value for value in stock_counts.values()], dtype=torch.long)
stock_counts = stock_counts.to(device)

N = stock_counts.sum()
inv_freq = N / stock_counts
weights = torch.log1p(inv_freq)
weights = weights / weights.mean()
weights

tensor([0.7389, 1.1751, 0.8591, 1.0505, 1.6898, 0.8491, 0.7453, 0.8261, 0.8199,
        0.7714, 1.1916, 1.5983, 0.9514, 0.8787, 1.5644, 1.4985, 1.0618, 0.7638,
        0.8325, 0.8124, 1.0836, 1.0068, 0.8787, 1.3758, 0.7979, 0.8165, 0.7540,
        1.0836, 0.7962, 1.0179, 1.0078, 0.7399, 0.9836, 0.7882, 0.7432, 0.8452,
        1.0039, 1.3697, 1.1417, 1.1992, 0.7800, 0.8052, 0.7840, 0.8095, 0.9309,
        0.8662, 0.8055, 0.9605, 0.8977, 0.8954, 0.8371, 0.7546, 1.0296, 1.3420,
        0.9793, 0.8752, 1.0618, 0.7815, 0.9069, 0.8172, 0.8577, 1.4402, 0.9898,
        1.0697, 1.2761, 1.8615, 1.1966, 0.9198, 1.3884, 1.0158, 0.9810, 1.6389,
        1.1436, 0.7422, 1.0554, 1.0822, 1.1065, 1.2124, 1.1684, 0.8866, 0.9567,
        0.9256, 0.8063, 0.8199, 0.8289, 0.8055, 0.7918], device='cuda:0')

In [23]:
def evaluate(logits, stock_labels):
    # stock_labels: (B,)
    loss = F.cross_entropy(logits, stock_labels, weight=weights)

    stock_pred = torch.argmax(logits, dim=-1) # (B,)
    acc = (stock_pred == stock_labels).float().mean()

    return loss, acc

In [24]:
def stock_cosine_similarities(model):

    h_s = model.stock_embd.weight # (num_stocks, embd_size)

    h_s_normalized = h_s / h_s.norm(dim=1, keepdim=True)
    h_s_sim = h_s_normalized @ h_s_normalized.T # (num_stocks, embd_size) @ (embd_size, num_stocks) -> (num_stocks, num_stocks)

    # n = h_s_sim.size(0)
    h_s_sim.fill_diagonal_(float("-inf")) # h_s_sim[i][i] = -inf

    h_s_sim = h_s_sim[stock_query_ids] # (4, num_stocks)
    _, top3_indices = torch.topk(h_s_sim, k=3, dim=-1) # (4, 3)


    for query_idx, query in enumerate(stock_queries):
        print(f"\n{query}: ", end="")
        for neigh_idx in top3_indices[query_idx]:
            print(stock_id_to_name[int(neigh_idx.item())], end=", ")


def tweet_embedding_quality(model):

    tweet1 = "<MASK> iphone 6s spec leaks look good. excited. might even buy one." # $AAPL
    tweet2 = "rt AT_USER <MASK> $pep $dps $mnst traditional soft drinks in decline." # $KO

    eval_X = [slot_spm.encode(tweet1), slot_spm.encode(tweet2)]

    max_len = max(len(tweet) for tweet in eval_X)

    eval_X = [tweet + [pad_id] * (max_len - len(tweet)) for tweet in eval_X]

    eval_mask_indices = torch.tensor([eval_X[0].index(mask_id), eval_X[1].index(mask_id)])
    eval_X = torch.tensor(eval_X, dtype=torch.long)

    eval_X, eval_mask_indices = eval_X.to(device), eval_mask_indices.to(device)
    eval_logits, _, _ = model(eval_X, eval_mask_indices)

    eval_preds = F.softmax(eval_logits, dim=-1)
    _, eval_top3_indices = torch.topk(eval_preds, k=3, dim=-1)

    for i, stock in enumerate(eval_top3_indices):
        print()
        for pred in stock:
            print(f"{stock_id_to_name[pred.item()]}: {eval_preds[i][pred.item()].item():.2%}", end = " | ")

### Training Loop

In [1]:

num_epochs = 50

def objective(trial):

    torch.manual_seed(42)
    torch.cuda.manual_seed(42)

    lr = 0.00248
    batch_size = 256
    embd_size = 128
    hidden_size = 254

    # lr = trial.suggest_float("lr", 1e-5, 1e-2, log=True)
    # batch_size = trial.suggest_categorical("batch_size", [64, 128, 256, 512])
    # embd_size = trial.suggest_categorical("embd_size", [64, 128, 256])
    # hidden_size =  trial.suggest_int("hidden_size", 32, 256)
    # dropout = trial.suggest_float("dropout", 0.0, 0.5)
    # temp = trial.suggest_float("temp", 0.1, 1.0)

    dropout = 0.439
    temp = 0.13356

    # dropout = 0.1
    # temp = 0.25

    wandb.init(
        project="stock_identification_final_test",
        name=f"trial_{trial.number}",
        config={
            "lr": lr,
            "batch_size": batch_size,
            "embd_size": embd_size,
            "hidden_size": hidden_size,
            "dropout": dropout,
            "temp": temp,
            "dataset": "ACL18"
        },
    )

    model = StockIdentification(
        num_stocks=num_stocks,
        embd_size=embd_size,
        hidden_size=hidden_size,
        vocab_size=vocab_size,
        dropout=dropout,
        temp=temp,
    )

    model = model.to(device)



    optimizer = torch.optim.AdamW(params = model.parameters(), lr=lr, weight_decay=1e-3)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(optimizer, T_0=10, T_mult=2, eta_min=1e-6)
    # scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer=optimizer, T_max=num_epochs, eta_min=1e-6)

    train_dataloader = DataLoader(train_subset, batch_size, shuffle=True)
    val_dataloader = DataLoader(val_subset, batch_size, shuffle=False)


    best_val_acc = 0.0

    for epoch in range(num_epochs):
        train_loss = 0.0
        train_acc = 0.0


        model.train()
        for i, (X, y, mask_indices) in enumerate(train_dataloader):
            X, y, mask_indices = X.to(device), y.to(device).to(torch.long), mask_indices.to(device)


            logits, _, _ = model(X, mask_indices) # (B, num_stocks)

            loss, acc = evaluate(logits, y)

            train_loss += loss.detach().item()
            train_acc += acc.item()


            optimizer.zero_grad()

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

            optimizer.step()

            # if i % 300 == 0:
                # print(f"Step: {i:04d} | Train loss: {loss:.4f} | Train acc: {100*acc:.2f}%")



        train_loss /= len(train_dataloader)
        train_acc /= len(train_dataloader)

        val_loss = 0.0
        val_acc = 0.0



        model.eval()
        with torch.inference_mode():
            for j, (X_val, y_val, mask_indices_val) in enumerate(val_dataloader):


                X_val, y_val, mask_indices_val = X_val.to(device), y_val.to(device), mask_indices_val.to(device)

                logits_val, _, _ = model(X_val, mask_indices_val)
                loss, acc = evaluate(logits_val, y_val)

                val_loss += loss.detach().item()
                val_acc += acc.item()

            val_loss /= len(val_dataloader)
            val_acc /= len(val_dataloader)

            best_val_acc = max(best_val_acc, val_acc)


        stock_cosine_similarities(model)
        tweet_embedding_quality(model)


        scheduler.step()

        print(f"\nEpoch: {epoch} | Train loss: {train_loss:.4f} | Train acc: {100*train_acc:.2f}% | Val loss: {val_loss:.4f} | Val acc: {100*val_acc:.2f}%")
        print(f"Learning rate: {optimizer.param_groups[0]['lr']:6f}")

        wandb.log({
            "train_loss": train_loss,
            "train_acc": train_acc,
            "val_loss": val_loss,
            "val_acc": val_acc,
            "best_val_acc": best_val_acc
        })

        trial.report(best_val_acc, step=epoch)
        if trial.should_prune():
            wandb.finish()
            raise optuna.TrialPruned()


        if epoch == 38:
            torch.save(model.state_dict(), dataset_dir / "best_model.pth")


    wandb.finish()
    return best_val_acc


study = optuna.create_study(direction="maximize", pruner=optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=5))
study.optimize(objective, n_trials = 1)

NameError: name 'optuna' is not defined

### Analyze Embedding Quality

In [25]:
# torch.save(model.state_dict(), dataset_dir / "best_model.pth")


embd_size = 128
hidden_size = 254
dropout = 0.439
temp = 0.13356

# embd_size = 128
# hidden_size = 64
# dropout = 0.1
# temp = 0.25



model = StockIdentification(
    num_stocks=num_stocks,
    embd_size=embd_size,
    hidden_size=hidden_size,
    vocab_size=vocab_size,
    dropout=dropout,
    temp=temp
).to(device)

model.load_state_dict(torch.load(dataset_dir / "best_model.pth", map_location=device))

In [28]:
torch.manual_seed(42)
torch.cuda.manual_seed(42)

stock_cosine_similarities(model)
print()
tweet_embedding_quality(model)

AAPL: FB, GOOG, MSFT,
FB: GOOG, AAPL, AMZN,
BA: LMT, HON, UTX,
BAC: WFC, JPM, C,

AAPL: 58.72% | AMZN: 5.91% | FB: 4.07% |
KO: 29.39% | PEP: 13.96% | JNJ: 1.85% |

## Stock Movement Prediction

### Global Trend with Attention

The global trend vector is generated by weighting the price features of stocks based on their popularity in tweets.

The average of all tweet embeddings at day $t$ ($g_t$) is used as the query vector.

The key vector is $h_s$, and the value vector is $x_{st}$.

$$
o_t = \sum_{s' \in S} \alpha_{st} x_{st}\;\; \text {where} \;\; \alpha_{st} = \frac{\exp(g_t^\top h_s)}{\sum_{s' \in S} \exp(g_t^\top h_{s'})}
$$

In [30]:
# g_t = torch.load(dataset_dir / "g_t.pt", map_location=device)
# all_tweet_embs = torch.load(dataset_dir / "all_tweet_embs", map_location=device)



all_tweet_embs = []

model.eval()
with torch.inference_mode():
    for d in tqdm(range(num_dates)):
        tweets = X_by_date[d].to(device)
        indices = mask_indices_by_date[d].to(device)

        _, h_e, _ = model(tweets, indices)
        all_tweet_embs.append(h_e)

g_t = torch.stack([torch.mean(h_e, dim=0) for h_e in all_tweet_embs])

torch.save(g_t, dataset_dir / "g_t.pt")
torch.save(all_tweet_embs, dataset_dir / "all_tweet_embs")
g_t.shape # (num_days, 2*hidden_size)

100%|██████████| 651/651 [00:07<00:00, 82.37it/s]

torch.Size([651, 508])

In [ ]:
# a_st (num_days, num_stocks) @ x_st (num_days, num_stocks, num_features) -> o_t (num_days, num_features)
# g_t (num_days, 2*hidden_size)  @ h_s.T (2*hidden_size, num_stocks) -> a_st (num_days, num_stocks)

In [31]:
h_s = model.stock_embd.weight.detach()

attn_scores = torch.matmul(g_t, h_s.T)

a_st = F.softmax(attn_scores, dim=-1)

a_st = a_st.unsqueeze(1)
a_st.shape

torch.Size([651, 1, 87])

In [32]:
o_t = torch.matmul(a_st, X_st).squeeze(1)
o_t = o_t.unsqueeze(1).expand(-1, X_st.size(1), -1)
o_t.shape

torch.Size([651, 87, 11])

### Local Similarities between Stocks

Two steps of attention

1. Attention to find tweets (on the target day) relevant to each target stock. Produces l_st, a weighted sum of the tweets for that day based on their relevance to the target stock.
    - Q: h_s
    - K: h_e
    - V: h_e

2. Attention to find stocks most relevant to l_st, and aggregate the price features based on relevance.
    - Q: l_st
    - K: h_s
    - V: x_st

This is preferable to doing h_s @ h_s.T because it will yield different results based on the day.
- Say $AAPL is doing a collaboration with $MSFT on some day, the attention score for AAPL/MSFT should be higher than usual.

h_s (num_stocks, hidden_size) @ h_e.T (hidden_size, num_tweets_that_day) -> a_e (num_stocks num_tweets_that_day)

a_e (num_stocks num_tweets_that_day) @ h_e (num_tweets_that_day, hidden_size) -> l_st (num_stocks, hidden_size)

In [34]:
l_st = []

for d in range(len(all_tweet_embs)):
    h_e = all_tweet_embs[d]
    a_e = torch.matmul(h_s, h_e.T).softmax(dim=-1)
    l_st.append(torch.matmul(a_e, h_e))

l_st = torch.stack(l_st)
l_st.shape

torch.Size([651, 87, 508])

l_st (num_days, num_stocks, hidden_size) @ h_s.T (hidden_size, num_stocks) -> a_st (num_days, num_stocks, num_stocks)

a_st (num_days, num_stocks, num_stocks) @ X_st (num_days, num_stocks, num_features) -> c_st (num_days, num_stocks, num_features)

In [35]:
a_st = torch.matmul(l_st, h_s.T).softmax(dim=-1)
c_st = torch.matmul(a_st, X_st)

c_st.shape

torch.Size([651, 87, 11])

### Windows

In [36]:
def create_windows(input, labels=False):
    if (labels):
        windows_list = [input[t+1] for t in range(window_size - 1, num_dates-1)]
    else:
        windows_list = [input[t-window_size+1 : t+1] for t in range(window_size - 1, num_dates-1)]

    # input: (num_windows, seq_len, num_stocks, features)
    # labels: (num_windows, num_stocks)
    windows = torch.stack(windows_list)

    if labels:
        windows = windows.reshape(-1)

    else:
        windows=windows.reshape(-1, windows.size(1), windows.size(-1))

    return windows

In [39]:
X_windowed, o_windowed, c_windowed = create_windows(X_st), create_windows(o_t), create_windows(c_st)
y_windowed = create_windows(y, labels=True)

X_windowed.shape, o_windowed.shape, c_windowed.shape, y_windowed.shape

(torch.Size([55332, 15, 11]),
 torch.Size([55332, 15, 11]),
 torch.Size([55332, 15, 11]),
 torch.Size([55332]))

In [40]:
mask = y_windowed != 0

X_windowed = X_windowed[mask]
o_windowed = o_windowed[mask]
c_windowed = c_windowed[mask]
y_windowed = y_windowed[mask]


X_windowed.shape, o_windowed.shape, c_windowed.shape, y_windowed.shape

(torch.Size([33711, 15, 11]),
 torch.Size([33711, 15, 11]),
 torch.Size([33711, 15, 11]),
 torch.Size([33711]))

### Train/Val/Test Split

In [41]:
data_len = len(y_windowed)

train_end = int(data_len * 0.70)
val_end = int(data_len * 0.85)

X_train, o_train, c_train, y_train = X_windowed[: train_end], o_windowed[: train_end], c_windowed[: train_end], y_windowed[: train_end]
X_val, o_val, c_val, y_val = X_windowed[train_end : val_end], o_windowed[train_end : val_end], c_windowed[train_end :val_end], y_windowed[train_end : val_end]
X_test, o_test, c_test, y_test = X_windowed[val_end :], o_windowed[val_end :], c_windowed[val_end :], y_windowed[val_end :]

print(f"X_train shape: {X_train.shape}. y_train shape: {y_train.shape}")
print(f"X_val shape: {X_val.shape}. y_val shape: {y_val.shape}")
print(f"X_test shape: {X_test.shape}. y_test shape: {y_test.shape}")

X_train shape: torch.Size([23597, 15, 11]). y_train shape: torch.Size([23597])
X_val shape: torch.Size([5057, 15, 11]). y_val shape: torch.Size([5057])
X_test shape: torch.Size([5057, 15, 11]). y_test shape: torch.Size([5057])

### Multi-Feature Dataset

In [42]:
class MultiFeatureDataset(Dataset):
    def __init__(self, x, o, c, y):
        super().__init__()
        self.x = x; self.o = o; self.c = c
        self.y = y

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.o[idx], self.c[idx], self.y[idx]

In [43]:
train_dataset = MultiFeatureDataset(X_train, o_train, c_train, y_train)
val_dataset = MultiFeatureDataset(X_val, o_val, c_val, y_val)
test_dataset = MultiFeatureDataset(X_test, o_test, c_test, y_test)

### DataLoaders

In [44]:
train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_dataloader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
test_dataloader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)
len(train_dataloader)

24

In [45]:
X, o, c, y = next(iter(train_dataloader))
X.shape

torch.Size([1024, 15, 11])

### SLOT Model Code

In [46]:
class SLOT(nn.Module):
    def __init__(self, input_size, hidden_size, dropout, output_size = 1):
        super().__init__()
        self.ln = nn.Linear(3*input_size, input_size)
        self.alstm = ALSTM(input_size=input_size, hidden_size=hidden_size, dropout=dropout)
        self.dropout = nn.Dropout(dropout)
        self.ln_f = nn.Linear(hidden_size*2, output_size)



    def forward(self, X_st, o_t, c_st):
        # X_st, o_t, c_st: (batch, seq_len, input_size)
        final_input = torch.cat((X_st, o_t, c_st), dim=-1) # (batch, seq_len, 3*input_size)
        final_input = self.ln(final_input) # (batch, seq_len, input_size)

        h_out = self.alstm(final_input) # (batch, 2*hidden_size)
        h_out = self.dropout(h_out)
        y_pred = self.ln_f(h_out) # (batch, output_size)

        return y_pred.squeeze(-1)

### Training Helper Functions

In [47]:
def evaluate(logits, y):
  # logits: (batch,)
  # y: (batch, )
  B = logits.size(0)

  loss = torch.clamp(1 - y * logits, min=0).mean()

  preds = torch.sign(logits) # (batch,)
  acc = (preds == y).float().mean().detach()

  return loss, acc.item()

In [58]:
def training_loop(trial, lr, hidden_size, weight_decay, dropout, use_existing=False):
  torch.manual_seed(42)
  torch.cuda.manual_seed(42)

  model = SLOT(
      input_size=len(price_features),
      hidden_size=hidden_size,
      dropout=dropout
  ).to(device)


  if use_existing:
    model.load_state_dict(torch.load(dataset_dir / "best_SLOT_model.pth", map_location=device))

  optimizer = torch.optim.AdamW(params = model.parameters(), lr=lr, weight_decay=weight_decay)
  scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer=optimizer, T_max=num_epochs, eta_min=1e-6)


  best_val_acc = 0.0
  best_train_acc = 0.0

  for epoch in range(num_epochs):
    train_loss = 0.0
    train_acc = 0.0



    model.train()
    for i, (X, o, c, y) in enumerate(train_dataloader):


        X, o, c, y = X.to(device), o.to(device), c.to(device), y.to(device)

        logits = model(X, o, c) # (batch, output_size)

        loss, acc = evaluate(logits, y)

        train_loss += loss.detach().item()
        train_acc += acc

        optimizer.zero_grad()
        loss.backward()

        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

        optimizer.step()


    train_loss /= len(train_dataloader)
    train_acc /= len(train_dataloader)



    val_loss = 0.0
    val_acc = 0.0


    model.eval()

    with torch.inference_mode():
        for i, (X_val, o_val, c_val, y_val) in enumerate(val_dataloader):

            X_val, o_val, c_val, y_val = X_val.to(device), o_val.to(device), c_val.to(device), y_val.to(device)

            logits = model(X_val, o_val, c_val)

            loss, acc = evaluate(logits, y_val)

            val_loss += loss.item()
            val_acc += acc


        val_loss /= len(val_dataloader)
        val_acc /= len(val_dataloader)

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        best_train_acc = train_acc

    wandb.log({
        "train_loss": train_loss,
        "train_acc": train_acc,
        "val_loss": val_loss,
        "val_acc": val_acc,
        "best_val_acc": best_val_acc,
        "best_train_acc": best_train_acc
    })

    scheduler.step()

    print(f"Epoch: {epoch:03d} | Train loss: {train_loss:.4f} | Train acc: {100*train_acc:.2f}% | Val loss: {val_loss:.4f} | Val acc: {100*val_acc:.2f}% | LR: {optimizer.param_groups[0]['lr']:6f}")



    # trial.report(best_val_acc, step=epoch)
    # if trial.should_prune():
    #     wandb.finish()
    #     raise optuna.TrialPruned()


  wandb.finish()
  return best_train_acc, best_val_acc

### Training Loop

In [61]:
def objective(trial):

    lr = trial.suggest_float("lr", 1e-4, 1e-2, log=True)
    hidden_size =  trial.suggest_int("hidden_size", 32, 256)
    dropout = trial.suggest_float("dropout", 0.0, 0.5)
    weight_decay = trial.suggest_float("weight_decay", 0.0, 1.0)

    wandb.init(
    project="SLOT_Train",
    name=f"trial_{trial.number}",
    config={
            "lr": lr,
            "hidden_size": hidden_size,
            "dropout": dropout,
            "weight_decay": weight_decay,
        },
    )

    return training_loop(trial, lr, hidden_size, dropout, weight_decay)


study = optuna.create_study(directions=["maximize", "maximize"])
study.optimize(objective, n_trials = 50)

[I 2025-09-23 01:28:06,596] A new study created in memory with name: no-name-c0aeb0db-82de-4754-a83a-6595afb93686

Epoch: 000 | Train loss: 1.0171 | Train acc: 50.00% | Val loss: 0.9823 | Val acc: 54.06% | LR: 0.002255
Epoch: 001 | Train loss: 0.9989 | Train acc: 50.08% | Val loss: 0.9791 | Val acc: 54.19% | LR: 0.002254
Epoch: 002 | Train loss: 0.9965 | Train acc: 50.82% | Val loss: 0.9923 | Val acc: 50.37% | LR: 0.002253
Epoch: 003 | Train loss: 0.9899 | Train acc: 50.30% | Val loss: 1.0402 | Val acc: 46.86% | LR: 0.002251
Epoch: 004 | Train loss: 0.9923 | Train acc: 51.10% | Val loss: 0.9989 | Val acc: 50.03% | LR: 0.002249
Epoch: 005 | Train loss: 0.9963 | Train acc: 50.30% | Val loss: 0.9697 | Val acc: 51.95% | LR: 0.002246
Epoch: 006 | Train loss: 0.9905 | Train acc: 51.04% | Val loss: 1.0096 | Val acc: 49.68% | LR: 0.002243
Epoch: 007 | Train loss: 0.9844 | Train acc: 51.12% | Val loss: 1.0208 | Val acc: 48.59% | LR: 0.002239
Epoch: 008 | Train loss: 0.9884 | Train acc: 50.99% | Val loss: 0.9520 | Val acc: 52.92% | LR: 0.002235
Epoch: 009 | Train loss: 0.9848 | Train acc: 51.07% | Val loss: 0.9689 | Val acc: 52.84% | LR: 0.002230
Epoch: 010 | Train loss: 0.9968 | Train acc: 50.31% | Val loss: 0.9834 | Val acc: 51.33% | LR: 0.002225
Epoch: 011 | Train loss: 0.9893 | Train acc: 50.79% | Val loss: 0.9918 | Val acc: 50.67% | LR: 0.002219
Epoch: 012 | Train loss: 0.9862 | Train acc: 50.93% | Val loss: 1.0059 | Val acc: 50.10% | LR: 0.002213
Epoch: 013 | Train loss: 0.9891 | Train acc: 50.68% | Val loss: 0.9926 | Val acc: 50.49% | LR: 0.002207
Epoch: 014 | Train loss: 0.9950 | Train acc: 50.58% | Val loss: 0.9711 | Val acc: 51.51% | LR: 0.002200
Epoch: 015 | Train loss: 0.9852 | Train acc: 51.09% | Val loss: 0.9773 | Val acc: 51.30% | LR: 0.002192
Epoch: 016 | Train loss: 0.9987 | Train acc: 50.31% | Val loss: 1.1092 | Val acc: 52.25% | LR: 0.002184
Epoch: 017 | Train loss: 1.5718 | Train acc: 51.10% | Val loss: 1.0493 | Val acc: 50.99% | LR: 0.002176
Epoch: 018 | Train loss: 1.0020 | Train acc: 50.44% | Val loss: 0.9854 | Val acc: 52.99% | LR: 0.002167
Epoch: 019 | Train loss: 0.9933 | Train acc: 50.65% | Val loss: 1.1080 | Val acc: 52.67% | LR: 0.002157
Epoch: 020 | Train loss: 0.9985 | Train acc: 50.35% | Val loss: 0.9869 | Val acc: 52.64% | LR: 0.002148
Epoch: 021 | Train loss: 0.9959 | Train acc: 51.53% | Val loss: 0.9701 | Val acc: 53.29% | LR: 0.002137
Epoch: 022 | Train loss: 0.9894 | Train acc: 50.88% | Val loss: 0.9556 | Val acc: 53.05% | LR: 0.002127
Epoch: 023 | Train loss: 0.9886 | Train acc: 50.51% | Val loss: 0.9539 | Val acc: 52.90% | LR: 0.002115
Epoch: 024 | Train loss: 0.9881 | Train acc: 50.96% | Val loss: 0.9628 | Val acc: 53.03% | LR: 0.002104
Epoch: 025 | Train loss: 0.9990 | Train acc: 49.94% | Val loss: 0.9977 | Val acc: 51.59% | LR: 0.002092
Epoch: 026 | Train loss: 0.9928 | Train acc: 50.52% | Val loss: 0.9815 | Val acc: 51.86% | LR: 0.002079
Epoch: 027 | Train loss: 0.9935 | Train acc: 50.06% | Val loss: 0.9666 | Val acc: 52.35% | LR: 0.002066
Epoch: 028 | Train loss: 0.9936 | Train acc: 50.34% | Val loss: 0.9717 | Val acc: 52.14% | LR: 0.002053
Epoch: 029 | Train loss: 0.9844 | Train acc: 51.36% | Val loss: 0.9689 | Val acc: 52.16% | LR: 0.002040
Epoch: 030 | Train loss: 0.9869 | Train acc: 50.73% | Val loss: 0.9797 | Val acc: 52.06% | LR: 0.002025
Epoch: 031 | Train loss: 0.9909 | Train acc: 50.91% | Val loss: 0.9691 | Val acc: 52.54% | LR: 0.002011
Epoch: 032 | Train loss: 0.9786 | Train acc: 51.23% | Val loss: 0.9696 | Val acc: 52.37% | LR: 0.001996
Epoch: 033 | Train loss: 0.9928 | Train acc: 50.56% | Val loss: 0.9829 | Val acc: 51.96% | LR: 0.001981
Epoch: 034 | Train loss: 0.9776 | Train acc: 51.57% | Val loss: 0.9700 | Val acc: 52.44% | LR: 0.001965
Epoch: 035 | Train loss: 0.9883 | Train acc: 50.94% | Val loss: 0.9679 | Val acc: 52.74% | LR: 0.001949
Epoch: 036 | Train loss: 0.9889 | Train acc: 50.89% | Val loss: 0.9841 | Val acc: 52.36% | LR: 0.001933
Epoch: 037 | Train loss: 0.9804 | Train acc: 51.41% | Val loss: 0.9714 | Val acc: 52.41% | LR: 0.001916
Epoch: 038 | Train loss: 0.9905 | Train acc: 50.42% | Val loss: 0.9708 | Val acc: 52.46% | LR: 0.001899
Epoch: 039 | Train loss: 0.9877 | Train acc: 50.67% | Val loss: 0.9649 | Val acc: 52.66% | LR: 0.001882
Epoch: 040 | Train loss: 0.9934 | Train acc: 50.49% | Val loss: 1.0348 | Val acc: 51.27% | LR: 0.001864
Epoch: 041 | Train loss: 0.9963 | Train acc: 51.18% | Val loss: 0.9516 | Val acc: 54.09% | LR: 0.001846
Epoch: 042 | Train loss: 0.9886 | Train acc: 51.25% | Val loss: 1.0018 | Val acc: 51.39% | LR: 0.001828
Epoch: 043 | Train loss: 0.9888 | Train acc: 51.29% | Val loss: 1.0025 | Val acc: 49.35% | LR: 0.001809
Epoch: 044 | Train loss: 0.9986 | Train acc: 49.73% | Val loss: 0.9935 | Val acc: 50.06% | LR: 0.001790
Epoch: 045 | Train loss: 0.9823 | Train acc: 51.34% | Val loss: 0.9963 | Val acc: 50.05% | LR: 0.001771
Epoch: 046 | Train loss: 0.9805 | Train acc: 51.76% | Val loss: 0.9930 | Val acc: 49.87% | LR: 0.001752
Epoch: 047 | Train loss: 0.9856 | Train acc: 51.18% | Val loss: 1.0012 | Val acc: 50.06% | LR: 0.001732
Epoch: 048 | Train loss: 0.9828 | Train acc: 51.51% | Val loss: 0.9746 | Val acc: 51.23% | LR: 0.001712
Epoch: 049 | Train loss: 0.9884 | Train acc: 50.79% | Val loss: 1.0091 | Val acc: 51.36% | LR: 0.001691
Epoch: 050 | Train loss: 0.9840 | Train acc: 51.32% | Val loss: 0.9784 | Val acc: 51.34% | LR: 0.001671
Epoch: 051 | Train loss: 0.9885 | Train acc: 50.99% | Val loss: 0.9842 | Val acc: 51.25% | LR: 0.001650
Epoch: 052 | Train loss: 0.9965 | Train acc: 50.56% | Val loss: 0.9831 | Val acc: 51.10% | LR: 0.001629
Epoch: 053 | Train loss: 0.9886 | Train acc: 50.85% | Val loss: 0.9641 | Val acc: 51.60% | LR: 0.001608
Epoch: 054 | Train loss: 0.9810 | Train acc: 51.44% | Val loss: 0.9715 | Val acc: 51.55% | LR: 0.001586
Epoch: 055 | Train loss: 0.9908 | Train acc: 50.26% | Val loss: 0.9836 | Val acc: 51.19% | LR: 0.001565
Epoch: 056 | Train loss: 0.9869 | Train acc: 50.86% | Val loss: 0.9867 | Val acc: 51.15% | LR: 0.001543
Epoch: 057 | Train loss: 0.9854 | Train acc: 51.31% | Val loss: 0.9891 | Val acc: 51.02% | LR: 0.001521
Epoch: 058 | Train loss: 0.9856 | Train acc: 50.95% | Val loss: 0.9971 | Val acc: 50.66% | LR: 0.001498
Epoch: 059 | Train loss: 0.9866 | Train acc: 50.89% | Val loss: 1.0017 | Val acc: 50.48% | LR: 0.001476
Epoch: 060 | Train loss: 0.9914 | Train acc: 50.05% | Val loss: 1.0003 | Val acc: 50.62% | LR: 0.001454
Epoch: 061 | Train loss: 0.9941 | Train acc: 50.89% | Val loss: 0.9983 | Val acc: 50.70% | LR: 0.001431
Epoch: 062 | Train loss: 0.9874 | Train acc: 50.78% | Val loss: 0.9860 | Val acc: 50.78% | LR: 0.001408
Epoch: 063 | Train loss: 0.9853 | Train acc: 50.96% | Val loss: 0.9753 | Val acc: 51.59% | LR: 0.001385
Epoch: 064 | Train loss: 0.9918 | Train acc: 50.54% | Val loss: 0.9941 | Val acc: 51.33% | LR: 0.001362
Epoch: 065 | Train loss: 0.9863 | Train acc: 50.98% | Val loss: 0.9931 | Val acc: 51.39% | LR: 0.001339
Epoch: 066 | Train loss: 0.9878 | Train acc: 51.47% | Val loss: 1.0330 | Val acc: 46.01% | LR: 0.001316
Epoch: 067 | Train loss: 0.9947 | Train acc: 50.49% | Val loss: 0.9816 | Val acc: 51.74% | LR: 0.001293
Epoch: 068 | Train loss: 0.9931 | Train acc: 50.43% | Val loss: 0.9780 | Val acc: 51.66% | LR: 0.001269
Epoch: 069 | Train loss: 0.9960 | Train acc: 50.20% | Val loss: 1.0008 | Val acc: 51.60% | LR: 0.001246
Epoch: 070 | Train loss: 1.0006 | Train acc: 49.99% | Val loss: 0.9929 | Val acc: 51.68% | LR: 0.001222
Epoch: 071 | Train loss: 0.9945 | Train acc: 50.64% | Val loss: 0.9737 | Val acc: 51.65% | LR: 0.001199
Epoch: 072 | Train loss: 0.9954 | Train acc: 50.30% | Val loss: 0.9890 | Val acc: 51.44% | LR: 0.001175
Epoch: 073 | Train loss: 0.9832 | Train acc: 51.52% | Val loss: 0.9753 | Val acc: 51.29% | LR: 0.001151
Epoch: 074 | Train loss: 0.9873 | Train acc: 51.02% | Val loss: 0.9735 | Val acc: 51.54% | LR: 0.001128
Epoch: 075 | Train loss: 0.9859 | Train acc: 51.30% | Val loss: 0.9757 | Val acc: 51.46% | LR: 0.001104
Epoch: 076 | Train loss: 0.9877 | Train acc: 51.03% | Val loss: 0.9726 | Val acc: 51.79% | LR: 0.001081
Epoch: 077 | Train loss: 0.9868 | Train acc: 50.85% | Val loss: 0.9666 | Val acc: 52.24% | LR: 0.001057
Epoch: 078 | Train loss: 0.9866 | Train acc: 50.87% | Val loss: 0.9803 | Val acc: 51.28% | LR: 0.001034
Epoch: 079 | Train loss: 0.9861 | Train acc: 51.02% | Val loss: 0.9877 | Val acc: 50.47% | LR: 0.001010
Epoch: 080 | Train loss: 0.9925 | Train acc: 50.50% | Val loss: 0.9808 | Val acc: 51.09% | LR: 0.000987
Epoch: 081 | Train loss: 0.9848 | Train acc: 51.39% | Val loss: 0.9843 | Val acc: 51.33% | LR: 0.000963
Epoch: 082 | Train loss: 0.9882 | Train acc: 50.83% | Val loss: 0.9819 | Val acc: 51.05% | LR: 0.000940
Epoch: 083 | Train loss: 0.9866 | Train acc: 50.90% | Val loss: 0.9797 | Val acc: 51.24% | LR: 0.000917
Epoch: 084 | Train loss: 0.9837 | Train acc: 51.11% | Val loss: 0.9865 | Val acc: 50.83% | LR: 0.000894
Epoch: 085 | Train loss: 0.9881 | Train acc: 50.68% | Val loss: 0.9817 | Val acc: 51.05% | LR: 0.000871
Epoch: 086 | Train loss: 0.9840 | Train acc: 50.91% | Val loss: 0.9821 | Val acc: 50.92% | LR: 0.000848
Epoch: 087 | Train loss: 0.9845 | Train acc: 51.05% | Val loss: 0.9662 | Val acc: 52.76% | LR: 0.000825
Epoch: 088 | Train loss: 0.9922 | Train acc: 50.41% | Val loss: 0.9800 | Val acc: 51.08% | LR: 0.000802
Epoch: 089 | Train loss: 0.9926 | Train acc: 50.49% | Val loss: 0.9810 | Val acc: 51.42% | LR: 0.000780
Epoch: 090 | Train loss: 0.9833 | Train acc: 51.41% | Val loss: 0.9770 | Val acc: 51.90% | LR: 0.000757
Epoch: 091 | Train loss: 0.9854 | Train acc: 51.18% | Val loss: 0.9733 | Val acc: 51.86% | LR: 0.000735
Epoch: 092 | Train loss: 0.9888 | Train acc: 50.87% | Val loss: 0.9736 | Val acc: 51.91% | LR: 0.000713
Epoch: 093 | Train loss: 0.9813 | Train acc: 51.55% | Val loss: 0.9695 | Val acc: 52.17% | LR: 0.000691
Epoch: 094 | Train loss: 0.9848 | Train acc: 51.08% | Val loss: 0.9652 | Val acc: 52.10% | LR: 0.000670
Epoch: 095 | Train loss: 0.9868 | Train acc: 50.90% | Val loss: 0.9777 | Val acc: 51.69% | LR: 0.000648
Epoch: 096 | Train loss: 0.9845 | Train acc: 51.05% | Val loss: 0.9859 | Val acc: 50.88% | LR: 0.000627
Epoch: 097 | Train loss: 0.9856 | Train acc: 50.84% | Val loss: 0.9848 | Val acc: 50.80% | LR: 0.000606
Epoch: 098 | Train loss: 0.9841 | Train acc: 51.21% | Val loss: 0.9908 | Val acc: 50.72% | LR: 0.000585
Epoch: 099 | Train loss: 0.9781 | Train acc: 51.59% | Val loss: 0.9803 | Val acc: 51.40% | LR: 0.000564
Epoch: 100 | Train loss: 0.9943 | Train acc: 50.40% | Val loss: 0.9738 | Val acc: 52.01% | LR: 0.000544
Epoch: 101 | Train loss: 0.9844 | Train acc: 51.31% | Val loss: 0.9647 | Val acc: 51.83% | LR: 0.000524
Epoch: 102 | Train loss: 0.9826 | Train acc: 51.29% | Val loss: 0.9670 | Val acc: 52.14% | LR: 0.000504
Epoch: 103 | Train loss: 0.9756 | Train acc: 51.65% | Val loss: 0.9787 | Val acc: 51.83% | LR: 0.000485
Epoch: 104 | Train loss: 0.9787 | Train acc: 51.42% | Val loss: 0.9702 | Val acc: 51.93% | LR: 0.000466
Epoch: 105 | Train loss: 0.9801 | Train acc: 51.27% | Val loss: 0.9664 | Val acc: 52.12% | LR: 0.000447
Epoch: 106 | Train loss: 0.9850 | Train acc: 51.00% | Val loss: 0.9704 | Val acc: 52.05% | LR: 0.000428
Epoch: 107 | Train loss: 0.9790 | Train acc: 51.22% | Val loss: 0.9641 | Val acc: 52.15% | LR: 0.000410
Epoch: 108 | Train loss: 0.9815 | Train acc: 51.21% | Val loss: 0.9640 | Val acc: 52.25% | LR: 0.000392
Epoch: 109 | Train loss: 0.9828 | Train acc: 51.03% | Val loss: 0.9649 | Val acc: 52.24% | LR: 0.000374
Epoch: 110 | Train loss: 0.9840 | Train acc: 51.23% | Val loss: 0.9694 | Val acc: 52.05% | LR: 0.000356
Epoch: 111 | Train loss: 0.9889 | Train acc: 50.97% | Val loss: 0.9694 | Val acc: 52.28% | LR: 0.000339
Epoch: 112 | Train loss: 0.9878 | Train acc: 50.71% | Val loss: 0.9664 | Val acc: 51.97% | LR: 0.000323
Epoch: 113 | Train loss: 0.9883 | Train acc: 50.85% | Val loss: 0.9674 | Val acc: 52.40% | LR: 0.000306
Epoch: 114 | Train loss: 0.9851 | Train acc: 51.05% | Val loss: 0.9736 | Val acc: 52.20% | LR: 0.000290
Epoch: 115 | Train loss: 0.9838 | Train acc: 51.07% | Val loss: 0.9639 | Val acc: 52.40% | LR: 0.000275
Epoch: 116 | Train loss: 0.9846 | Train acc: 51.06% | Val loss: 0.9616 | Val acc: 52.34% | LR: 0.000260
Epoch: 117 | Train loss: 0.9830 | Train acc: 51.06% | Val loss: 0.9669 | Val acc: 52.20% | LR: 0.000245
Epoch: 118 | Train loss: 0.9883 | Train acc: 50.78% | Val loss: 0.9668 | Val acc: 52.33% | LR: 0.000230
Epoch: 119 | Train loss: 0.9775 | Train acc: 51.53% | Val loss: 0.9639 | Val acc: 52.34% | LR: 0.000216
Epoch: 120 | Train loss: 0.9758 | Train acc: 51.66% | Val loss: 0.9703 | Val acc: 52.30% | LR: 0.000203
Epoch: 121 | Train loss: 0.9833 | Train acc: 50.96% | Val loss: 0.9669 | Val acc: 52.30% | LR: 0.000189
Epoch: 122 | Train loss: 0.9853 | Train acc: 50.89% | Val loss: 0.9628 | Val acc: 52.36% | LR: 0.000176
Epoch: 123 | Train loss: 0.9832 | Train acc: 51.08% | Val loss: 0.9648 | Val acc: 52.29% | LR: 0.000164
Epoch: 124 | Train loss: 0.9831 | Train acc: 51.06% | Val loss: 0.9629 | Val acc: 52.40% | LR: 0.000152
Epoch: 125 | Train loss: 0.9888 | Train acc: 50.70% | Val loss: 0.9667 | Val acc: 52.33% | LR: 0.000140
Epoch: 126 | Train loss: 0.9894 | Train acc: 50.63% | Val loss: 0.9640 | Val acc: 52.30% | LR: 0.000129
Epoch: 127 | Train loss: 0.9836 | Train acc: 51.08% | Val loss: 0.9648 | Val acc: 52.34% | LR: 0.000119
Epoch: 128 | Train loss: 0.9819 | Train acc: 51.04% | Val loss: 0.9649 | Val acc: 52.24% | LR: 0.000108
Epoch: 129 | Train loss: 0.9835 | Train acc: 51.08% | Val loss: 0.9641 | Val acc: 52.31% | LR: 0.000098
Epoch: 130 | Train loss: 0.9830 | Train acc: 50.90% | Val loss: 0.9645 | Val acc: 52.20% | LR: 0.000089
Epoch: 131 | Train loss: 0.9842 | Train acc: 50.98% | Val loss: 0.9650 | Val acc: 52.28% | LR: 0.000080
Epoch: 132 | Train loss: 0.9828 | Train acc: 51.16% | Val loss: 0.9654 | Val acc: 52.28% | LR: 0.000072
Epoch: 133 | Train loss: 0.9768 | Train acc: 51.42% | Val loss: 0.9635 | Val acc: 52.30% | LR: 0.000064
Epoch: 134 | Train loss: 0.9761 | Train acc: 51.60% | Val loss: 0.9651 | Val acc: 52.23% | LR: 0.000056
Epoch: 135 | Train loss: 0.9805 | Train acc: 51.07% | Val loss: 0.9656 | Val acc: 52.28% | LR: 0.000049
Epoch: 136 | Train loss: 0.9871 | Train acc: 50.81% | Val loss: 0.9646 | Val acc: 52.28% | LR: 0.000043
Epoch: 137 | Train loss: 0.9781 | Train acc: 51.43% | Val loss: 0.9647 | Val acc: 52.26% | LR: 0.000036
Epoch: 138 | Train loss: 0.9824 | Train acc: 51.07% | Val loss: 0.9642 | Val acc: 52.25% | LR: 0.000031
Epoch: 139 | Train loss: 0.9825 | Train acc: 51.07% | Val loss: 0.9643 | Val acc: 52.24% | LR: 0.000026
Epoch: 140 | Train loss: 0.9772 | Train acc: 51.52% | Val loss: 0.9655 | Val acc: 52.20% | LR: 0.000021
Epoch: 141 | Train loss: 0.9819 | Train acc: 50.98% | Val loss: 0.9650 | Val acc: 52.24% | LR: 0.000017
Epoch: 142 | Train loss: 0.9842 | Train acc: 50.98% | Val loss: 0.9657 | Val acc: 52.26% | LR: 0.000013
Epoch: 143 | Train loss: 0.9788 | Train acc: 51.33% | Val loss: 0.9653 | Val acc: 52.26% | LR: 0.000010
Epoch: 144 | Train loss: 0.9766 | Train acc: 51.34% | Val loss: 0.9647 | Val acc: 52.24% | LR: 0.000007
Epoch: 145 | Train loss: 0.9826 | Train acc: 51.07% | Val loss: 0.9651 | Val acc: 52.26% | LR: 0.000005
Epoch: 146 | Train loss: 0.9821 | Train acc: 51.07% | Val loss: 0.9650 | Val acc: 52.24% | LR: 0.000003
Epoch: 147 | Train loss: 0.9847 | Train acc: 50.98% | Val loss: 0.9649 | Val acc: 52.24% | LR: 0.000002
Epoch: 148 | Train loss: 0.9791 | Train acc: 51.33% | Val loss: 0.9649 | Val acc: 52.24% | LR: 0.000001
Epoch: 149 | Train loss: 0.9759 | Train acc: 51.51% | Val loss: 0.9649 | Val acc: 52.24% | LR: 0.000001

[I 2025-09-23 01:32:06,253] Trial 0 finished with value: 0.5418909788131714 and parameters: {'lr': 0.0022547784782830133, 'hidden_size': 176, 'dropout': 0.2084342266361669, 'weight_decay': 0.3187740167865155}. Best is trial 0 with value: 0.5418909788131714.

Epoch: 000 | Train loss: 1.0039 | Train acc: 49.68% | Val loss: 1.0211 | Val acc: 45.95% | LR: 0.008645
Epoch: 001 | Train loss: 1.0022 | Train acc: 50.84% | Val loss: 0.9969 | Val acc: 49.25% | LR: 0.008642
Epoch: 002 | Train loss: 1.0093 | Train acc: 50.96% | Val loss: 1.3615 | Val acc: 48.73% | LR: 0.008637
Epoch: 003 | Train loss: 1.0007 | Train acc: 50.62% | Val loss: 0.9934 | Val acc: 50.97% | LR: 0.008631
Epoch: 004 | Train loss: 1.0012 | Train acc: 50.60% | Val loss: 1.0757 | Val acc: 49.85% | LR: 0.008622
Epoch: 005 | Train loss: 0.9917 | Train acc: 50.97% | Val loss: 1.0167 | Val acc: 50.11% | LR: 0.008612
Epoch: 006 | Train loss: 0.9959 | Train acc: 50.69% | Val loss: 1.0104 | Val acc: 49.19% | LR: 0.008599
Epoch: 007 | Train loss: 0.9922 | Train acc: 51.20% | Val loss: 1.0135 | Val acc: 51.49% | LR: 0.008585
Epoch: 008 | Train loss: 0.9921 | Train acc: 51.13% | Val loss: 1.0175 | Val acc: 47.60% | LR: 0.008569
Epoch: 009 | Train loss: 0.9970 | Train acc: 51.23% | Val loss: 1.0197 | Val acc: 47.50% | LR: 0.008551
Epoch: 010 | Train loss: 1.0014 | Train acc: 50.50% | Val loss: 1.0953 | Val acc: 49.57% | LR: 0.008531
Epoch: 011 | Train loss: 0.9981 | Train acc: 50.62% | Val loss: 1.0005 | Val acc: 49.79% | LR: 0.008510
Epoch: 012 | Train loss: 0.9932 | Train acc: 50.67% | Val loss: 1.0326 | Val acc: 51.36% | LR: 0.008486
Epoch: 013 | Train loss: 1.4130 | Train acc: 50.65% | Val loss: 1.0069 | Val acc: 50.20% | LR: 0.008461
Epoch: 014 | Train loss: 1.2810 | Train acc: 50.08% | Val loss: 3.0483 | Val acc: 50.37% | LR: 0.008434
Epoch: 015 | Train loss: 0.9996 | Train acc: 50.18% | Val loss: 1.0437 | Val acc: 46.24% | LR: 0.008405
Epoch: 016 | Train loss: 1.0122 | Train acc: 50.17% | Val loss: 1.1475 | Val acc: 49.99% | LR: 0.008375
Epoch: 017 | Train loss: 1.0911 | Train acc: 50.27% | Val loss: 1.0699 | Val acc: 46.79% | LR: 0.008342
Epoch: 018 | Train loss: 0.9952 | Train acc: 50.68% | Val loss: 1.0221 | Val acc: 47.80% | LR: 0.008308
Epoch: 019 | Train loss: 1.0160 | Train acc: 50.30% | Val loss: 0.9575 | Val acc: 54.05% | LR: 0.008272
Epoch: 020 | Train loss: 0.9941 | Train acc: 50.39% | Val loss: 0.9697 | Val acc: 52.70% | LR: 0.008234
Epoch: 021 | Train loss: 0.9961 | Train acc: 50.39% | Val loss: 0.9690 | Val acc: 53.19% | LR: 0.008195
Epoch: 022 | Train loss: 0.9938 | Train acc: 50.89% | Val loss: 0.9773 | Val acc: 54.05% | LR: 0.008154
Epoch: 023 | Train loss: 1.0100 | Train acc: 50.33% | Val loss: 1.0081 | Val acc: 50.17% | LR: 0.008111
Epoch: 024 | Train loss: 0.9951 | Train acc: 50.16% | Val loss: 1.1216 | Val acc: 45.87% | LR: 0.008067
Epoch: 025 | Train loss: 0.9881 | Train acc: 51.16% | Val loss: 1.0640 | Val acc: 46.70% | LR: 0.008021
Epoch: 026 | Train loss: 0.9978 | Train acc: 50.37% | Val loss: 1.0484 | Val acc: 46.07% | LR: 0.007973
Epoch: 027 | Train loss: 0.9916 | Train acc: 50.59% | Val loss: 0.9994 | Val acc: 50.66% | LR: 0.007924
Epoch: 028 | Train loss: 0.9927 | Train acc: 50.38% | Val loss: 0.9863 | Val acc: 53.50% | LR: 0.007873
Epoch: 029 | Train loss: 0.9921 | Train acc: 50.82% | Val loss: 0.9823 | Val acc: 52.15% | LR: 0.007820
Epoch: 030 | Train loss: 0.9908 | Train acc: 51.34% | Val loss: 1.0823 | Val acc: 46.07% | LR: 0.007766
Epoch: 031 | Train loss: 0.9896 | Train acc: 51.11% | Val loss: 0.9960 | Val acc: 50.22% | LR: 0.007711
Epoch: 032 | Train loss: 0.9937 | Train acc: 50.62% | Val loss: 0.9913 | Val acc: 51.15% | LR: 0.007654
Epoch: 033 | Train loss: 0.9882 | Train acc: 50.83% | Val loss: 0.9496 | Val acc: 53.93% | LR: 0.007595
Epoch: 034 | Train loss: 0.9928 | Train acc: 50.56% | Val loss: 1.0076 | Val acc: 49.34% | LR: 0.007535
Epoch: 035 | Train loss: 0.9906 | Train acc: 51.00% | Val loss: 0.9838 | Val acc: 51.60% | LR: 0.007474
Epoch: 036 | Train loss: 0.9921 | Train acc: 50.96% | Val loss: 0.9774 | Val acc: 53.98% | LR: 0.007412
Epoch: 037 | Train loss: 0.9927 | Train acc: 51.01% | Val loss: 0.9988 | Val acc: 49.91% | LR: 0.007348
Epoch: 038 | Train loss: 0.9870 | Train acc: 51.09% | Val loss: 1.0118 | Val acc: 48.66% | LR: 0.007282
Epoch: 039 | Train loss: 0.9891 | Train acc: 51.02% | Val loss: 1.0043 | Val acc: 49.71% | LR: 0.007216
Epoch: 040 | Train loss: 0.9886 | Train acc: 50.56% | Val loss: 1.0457 | Val acc: 47.38% | LR: 0.007148
Epoch: 041 | Train loss: 0.9874 | Train acc: 50.93% | Val loss: 1.0600 | Val acc: 47.62% | LR: 0.007079
Epoch: 042 | Train loss: 0.9873 | Train acc: 51.27% | Val loss: 1.0035 | Val acc: 49.62% | LR: 0.007008
Epoch: 043 | Train loss: 0.9842 | Train acc: 51.37% | Val loss: 0.9807 | Val acc: 51.61% | LR: 0.006937
Epoch: 044 | Train loss: 0.9900 | Train acc: 51.01% | Val loss: 0.9693 | Val acc: 52.24% | LR: 0.006864
Epoch: 045 | Train loss: 0.9829 | Train acc: 51.41% | Val loss: 0.9902 | Val acc: 50.44% | LR: 0.006790
Epoch: 046 | Train loss: 0.9892 | Train acc: 50.75% | Val loss: 0.9948 | Val acc: 52.50% | LR: 0.006715
Epoch: 047 | Train loss: 0.9970 | Train acc: 50.34% | Val loss: 0.9833 | Val acc: 51.94% | LR: 0.006639
Epoch: 048 | Train loss: 0.9888 | Train acc: 50.68% | Val loss: 0.9686 | Val acc: 52.84% | LR: 0.006562
Epoch: 049 | Train loss: 0.9867 | Train acc: 51.34% | Val loss: 1.0048 | Val acc: 50.33% | LR: 0.006485
Epoch: 050 | Train loss: 0.9841 | Train acc: 51.94% | Val loss: 1.0167 | Val acc: 49.16% | LR: 0.006406
Epoch: 051 | Train loss: 0.9836 | Train acc: 51.44% | Val loss: 1.0088 | Val acc: 49.57% | LR: 0.006326
Epoch: 052 | Train loss: 0.9746 | Train acc: 51.84% | Val loss: 1.0060 | Val acc: 50.67% | LR: 0.006245
Epoch: 053 | Train loss: 0.9874 | Train acc: 51.12% | Val loss: 0.9816 | Val acc: 51.91% | LR: 0.006164
Epoch: 054 | Train loss: 0.9811 | Train acc: 51.41% | Val loss: 1.0716 | Val acc: 49.71% | LR: 0.006081
Epoch: 055 | Train loss: 0.9934 | Train acc: 51.17% | Val loss: 1.0607 | Val acc: 50.28% | LR: 0.005998
Epoch: 056 | Train loss: 1.0016 | Train acc: 50.07% | Val loss: 1.0260 | Val acc: 47.85% | LR: 0.005915
Epoch: 057 | Train loss: 0.9990 | Train acc: 50.22% | Val loss: 1.0034 | Val acc: 49.75% | LR: 0.005830
Epoch: 058 | Train loss: 0.9930 | Train acc: 51.13% | Val loss: 1.0206 | Val acc: 48.60% | LR: 0.005745
Epoch: 059 | Train loss: 0.9914 | Train acc: 51.07% | Val loss: 1.0215 | Val acc: 47.91% | LR: 0.005659
Epoch: 060 | Train loss: 1.0016 | Train acc: 50.58% | Val loss: 1.0008 | Val acc: 50.01% | LR: 0.005573
Epoch: 061 | Train loss: 0.9934 | Train acc: 50.57% | Val loss: 1.0018 | Val acc: 50.20% | LR: 0.005486
Epoch: 062 | Train loss: 0.9909 | Train acc: 51.19% | Val loss: 1.0128 | Val acc: 48.38% | LR: 0.005398
Epoch: 063 | Train loss: 0.9901 | Train acc: 51.07% | Val loss: 0.9895 | Val acc: 51.39% | LR: 0.005310
Epoch: 064 | Train loss: 0.9836 | Train acc: 51.37% | Val loss: 0.9898 | Val acc: 51.05% | LR: 0.005222
Epoch: 065 | Train loss: 0.9836 | Train acc: 51.21% | Val loss: 1.0013 | Val acc: 50.19% | LR: 0.005133
Epoch: 066 | Train loss: 0.9928 | Train acc: 50.57% | Val loss: 1.0421 | Val acc: 48.06% | LR: 0.005044
Epoch: 067 | Train loss: 0.9885 | Train acc: 51.40% | Val loss: 0.9912 | Val acc: 50.96% | LR: 0.004955
Epoch: 068 | Train loss: 0.9904 | Train acc: 50.74% | Val loss: 0.9874 | Val acc: 51.78% | LR: 0.004865
Epoch: 069 | Train loss: 0.9848 | Train acc: 51.15% | Val loss: 1.0361 | Val acc: 48.90% | LR: 0.004775
Epoch: 070 | Train loss: 0.9759 | Train acc: 52.19% | Val loss: 1.0222 | Val acc: 49.58% | LR: 0.004685
Epoch: 071 | Train loss: 0.9804 | Train acc: 51.38% | Val loss: 1.0194 | Val acc: 49.64% | LR: 0.004595
Epoch: 072 | Train loss: 0.9837 | Train acc: 51.38% | Val loss: 0.9894 | Val acc: 51.31% | LR: 0.004504
Epoch: 073 | Train loss: 0.9714 | Train acc: 52.34% | Val loss: 1.0204 | Val acc: 49.40% | LR: 0.004414
Epoch: 074 | Train loss: 0.9707 | Train acc: 51.83% | Val loss: 0.9909 | Val acc: 51.13% | LR: 0.004323
Epoch: 075 | Train loss: 0.9688 | Train acc: 52.17% | Val loss: 0.9940 | Val acc: 51.06% | LR: 0.004233
Epoch: 076 | Train loss: 0.9734 | Train acc: 52.23% | Val loss: 0.9899 | Val acc: 51.48% | LR: 0.004142
Epoch: 077 | Train loss: 0.9722 | Train acc: 52.00% | Val loss: 1.0131 | Val acc: 50.13% | LR: 0.004052
Epoch: 078 | Train loss: 0.9674 | Train acc: 52.17% | Val loss: 1.0090 | Val acc: 50.77% | LR: 0.003962
Epoch: 079 | Train loss: 0.9702 | Train acc: 52.35% | Val loss: 1.0364 | Val acc: 48.77% | LR: 0.003872
Epoch: 080 | Train loss: 0.9668 | Train acc: 52.05% | Val loss: 1.0037 | Val acc: 50.82% | LR: 0.003782
Epoch: 081 | Train loss: 0.9665 | Train acc: 52.16% | Val loss: 1.0042 | Val acc: 50.98% | LR: 0.003692
Epoch: 082 | Train loss: 0.9568 | Train acc: 53.01% | Val loss: 1.0196 | Val acc: 49.98% | LR: 0.003603
Epoch: 083 | Train loss: 0.9622 | Train acc: 53.13% | Val loss: 1.0184 | Val acc: 49.38% | LR: 0.003513
Epoch: 084 | Train loss: 0.9613 | Train acc: 53.17% | Val loss: 1.0425 | Val acc: 48.99% | LR: 0.003425
Epoch: 085 | Train loss: 0.9607 | Train acc: 52.88% | Val loss: 1.0275 | Val acc: 49.62% | LR: 0.003336
Epoch: 086 | Train loss: 0.9529 | Train acc: 53.15% | Val loss: 1.0251 | Val acc: 50.38% | LR: 0.003248
Epoch: 087 | Train loss: 0.9545 | Train acc: 52.90% | Val loss: 1.0309 | Val acc: 49.54% | LR: 0.003161
Epoch: 088 | Train loss: 0.9635 | Train acc: 52.22% | Val loss: 1.0209 | Val acc: 50.59% | LR: 0.003074
Epoch: 089 | Train loss: 0.9654 | Train acc: 52.53% | Val loss: 1.0267 | Val acc: 50.51% | LR: 0.002988
Epoch: 090 | Train loss: 0.9569 | Train acc: 52.86% | Val loss: 1.0602 | Val acc: 48.43% | LR: 0.002902
Epoch: 091 | Train loss: 0.9605 | Train acc: 52.89% | Val loss: 1.0592 | Val acc: 49.12% | LR: 0.002817
Epoch: 092 | Train loss: 0.9513 | Train acc: 53.28% | Val loss: 1.0582 | Val acc: 49.66% | LR: 0.002732
Epoch: 093 | Train loss: 0.9533 | Train acc: 53.09% | Val loss: 1.0511 | Val acc: 49.11% | LR: 0.002648
Epoch: 094 | Train loss: 0.9529 | Train acc: 53.11% | Val loss: 1.0541 | Val acc: 49.34% | LR: 0.002565
Epoch: 095 | Train loss: 0.9504 | Train acc: 53.27% | Val loss: 1.0414 | Val acc: 49.63% | LR: 0.002483
Epoch: 096 | Train loss: 0.9473 | Train acc: 53.35% | Val loss: 1.0356 | Val acc: 50.38% | LR: 0.002401
Epoch: 097 | Train loss: 0.9511 | Train acc: 53.17% | Val loss: 1.0429 | Val acc: 49.90% | LR: 0.002321
Epoch: 098 | Train loss: 0.9543 | Train acc: 52.62% | Val loss: 1.0821 | Val acc: 48.98% | LR: 0.002241
Epoch: 099 | Train loss: 0.9526 | Train acc: 53.01% | Val loss: 1.0432 | Val acc: 49.68% | LR: 0.002162
Epoch: 100 | Train loss: 0.9409 | Train acc: 53.87% | Val loss: 1.0555 | Val acc: 49.76% | LR: 0.002084
Epoch: 101 | Train loss: 0.9431 | Train acc: 53.55% | Val loss: 1.0456 | Val acc: 50.37% | LR: 0.002007
Epoch: 102 | Train loss: 0.9445 | Train acc: 53.42% | Val loss: 1.0575 | Val acc: 49.54% | LR: 0.001931
Epoch: 103 | Train loss: 0.9421 | Train acc: 53.71% | Val loss: 1.0594 | Val acc: 49.00% | LR: 0.001857
Epoch: 104 | Train loss: 0.9386 | Train acc: 53.93% | Val loss: 1.0535 | Val acc: 49.77% | LR: 0.001783
Epoch: 105 | Train loss: 0.9378 | Train acc: 53.81% | Val loss: 1.0667 | Val acc: 48.56% | LR: 0.001710
Epoch: 106 | Train loss: 0.9352 | Train acc: 53.96% | Val loss: 1.0635 | Val acc: 49.36% | LR: 0.001639
Epoch: 107 | Train loss: 0.9407 | Train acc: 53.65% | Val loss: 1.0743 | Val acc: 48.65% | LR: 0.001568
Epoch: 108 | Train loss: 0.9285 | Train acc: 54.25% | Val loss: 1.0575 | Val acc: 49.51% | LR: 0.001499
Epoch: 109 | Train loss: 0.9387 | Train acc: 53.73% | Val loss: 1.0629 | Val acc: 48.87% | LR: 0.001431
Epoch: 110 | Train loss: 0.9464 | Train acc: 53.30% | Val loss: 1.0619 | Val acc: 49.42% | LR: 0.001364
Epoch: 111 | Train loss: 0.9314 | Train acc: 54.02% | Val loss: 1.0721 | Val acc: 49.32% | LR: 0.001299
Epoch: 112 | Train loss: 0.9417 | Train acc: 53.54% | Val loss: 1.0674 | Val acc: 49.20% | LR: 0.001235
Epoch: 113 | Train loss: 0.9353 | Train acc: 53.81% | Val loss: 1.0547 | Val acc: 50.15% | LR: 0.001172
Epoch: 114 | Train loss: 0.9290 | Train acc: 54.03% | Val loss: 1.0727 | Val acc: 49.19% | LR: 0.001111
Epoch: 115 | Train loss: 0.9323 | Train acc: 54.22% | Val loss: 1.0675 | Val acc: 49.57% | LR: 0.001051
Epoch: 116 | Train loss: 0.9322 | Train acc: 54.08% | Val loss: 1.0754 | Val acc: 48.82% | LR: 0.000993
Epoch: 117 | Train loss: 0.9336 | Train acc: 53.95% | Val loss: 1.0812 | Val acc: 48.90% | LR: 0.000936
Epoch: 118 | Train loss: 0.9306 | Train acc: 54.23% | Val loss: 1.0694 | Val acc: 49.42% | LR: 0.000880
Epoch: 119 | Train loss: 0.9324 | Train acc: 54.09% | Val loss: 1.0777 | Val acc: 48.72% | LR: 0.000826
Epoch: 120 | Train loss: 0.9392 | Train acc: 53.56% | Val loss: 1.0747 | Val acc: 49.36% | LR: 0.000774
Epoch: 121 | Train loss: 0.9358 | Train acc: 53.69% | Val loss: 1.0697 | Val acc: 49.73% | LR: 0.000723
Epoch: 122 | Train loss: 0.9345 | Train acc: 53.87% | Val loss: 1.0748 | Val acc: 49.45% | LR: 0.000674
Epoch: 123 | Train loss: 0.9287 | Train acc: 54.24% | Val loss: 1.0719 | Val acc: 49.43% | LR: 0.000626
Epoch: 124 | Train loss: 0.9326 | Train acc: 53.84% | Val loss: 1.0825 | Val acc: 49.09% | LR: 0.000580
Epoch: 125 | Train loss: 0.9313 | Train acc: 53.96% | Val loss: 1.0719 | Val acc: 49.77% | LR: 0.000536
Epoch: 126 | Train loss: 0.9344 | Train acc: 53.89% | Val loss: 1.0750 | Val acc: 49.50% | LR: 0.000493
Epoch: 127 | Train loss: 0.9309 | Train acc: 53.83% | Val loss: 1.0793 | Val acc: 49.09% | LR: 0.000452
Epoch: 128 | Train loss: 0.9286 | Train acc: 54.02% | Val loss: 1.0776 | Val acc: 49.37% | LR: 0.000412
Epoch: 129 | Train loss: 0.9264 | Train acc: 54.28% | Val loss: 1.0730 | Val acc: 49.53% | LR: 0.000375
Epoch: 130 | Train loss: 0.9379 | Train acc: 53.53% | Val loss: 1.0744 | Val acc: 49.66% | LR: 0.000339
Epoch: 131 | Train loss: 0.9235 | Train acc: 54.53% | Val loss: 1.0813 | Val acc: 49.24% | LR: 0.000305
Epoch: 132 | Train loss: 0.9337 | Train acc: 53.74% | Val loss: 1.0798 | Val acc: 49.30% | LR: 0.000272
Epoch: 133 | Train loss: 0.9269 | Train acc: 54.27% | Val loss: 1.0834 | Val acc: 49.05% | LR: 0.000241
Epoch: 134 | Train loss: 0.9364 | Train acc: 53.52% | Val loss: 1.0817 | Val acc: 49.15% | LR: 0.000213
Epoch: 135 | Train loss: 0.9302 | Train acc: 54.08% | Val loss: 1.0830 | Val acc: 49.29% | LR: 0.000185
Epoch: 136 | Train loss: 0.9325 | Train acc: 54.01% | Val loss: 1.0815 | Val acc: 49.38% | LR: 0.000160
Epoch: 137 | Train loss: 0.9334 | Train acc: 53.76% | Val loss: 1.0825 | Val acc: 49.19% | LR: 0.000137
Epoch: 138 | Train loss: 0.9321 | Train acc: 53.62% | Val loss: 1.0838 | Val acc: 49.13% | LR: 0.000115
Epoch: 139 | Train loss: 0.9213 | Train acc: 54.74% | Val loss: 1.0834 | Val acc: 49.29% | LR: 0.000095
Epoch: 140 | Train loss: 0.9363 | Train acc: 53.45% | Val loss: 1.0830 | Val acc: 49.15% | LR: 0.000078
Epoch: 141 | Train loss: 0.9290 | Train acc: 54.10% | Val loss: 1.0827 | Val acc: 49.21% | LR: 0.000062
Epoch: 142 | Train loss: 0.9278 | Train acc: 54.20% | Val loss: 1.0819 | Val acc: 49.19% | LR: 0.000047
Epoch: 143 | Train loss: 0.9279 | Train acc: 54.23% | Val loss: 1.0818 | Val acc: 49.29% | LR: 0.000035
Epoch: 144 | Train loss: 0.9338 | Train acc: 53.59% | Val loss: 1.0810 | Val acc: 49.23% | LR: 0.000025
Epoch: 145 | Train loss: 0.9252 | Train acc: 54.48% | Val loss: 1.0810 | Val acc: 49.27% | LR: 0.000016
Epoch: 146 | Train loss: 0.9290 | Train acc: 54.05% | Val loss: 1.0809 | Val acc: 49.31% | LR: 0.000010
Epoch: 147 | Train loss: 0.9238 | Train acc: 54.50% | Val loss: 1.0810 | Val acc: 49.33% | LR: 0.000005
Epoch: 148 | Train loss: 0.9270 | Train acc: 54.29% | Val loss: 1.0810 | Val acc: 49.29% | LR: 0.000002
Epoch: 149 | Train loss: 0.9308 | Train acc: 54.05% | Val loss: 1.0810 | Val acc: 49.29% | LR: 0.000001

[I 2025-09-23 01:34:19,527] Trial 1 finished with value: 0.5404949307441711 and parameters: {'lr': 0.00864568265593978, 'hidden_size': 114, 'dropout': 0.023361394900304533, 'weight_decay': 0.187120847643112}. Best is trial 0 with value: 0.5418909788131714.

Epoch: 000 | Train loss: 1.0036 | Train acc: 50.29% | Val loss: 1.0020 | Val acc: 52.90% | LR: 0.000448
Epoch: 001 | Train loss: 0.9924 | Train acc: 50.59% | Val loss: 0.9907 | Val acc: 54.20% | LR: 0.000448
Epoch: 002 | Train loss: 0.9886 | Train acc: 51.06% | Val loss: 0.9977 | Val acc: 54.57% | LR: 0.000448
Epoch: 003 | Train loss: 0.9916 | Train acc: 51.18% | Val loss: 1.0097 | Val acc: 53.68% | LR: 0.000447
Epoch: 004 | Train loss: 0.9903 | Train acc: 50.72% | Val loss: 0.9814 | Val acc: 52.92% | LR: 0.000447
Epoch: 005 | Train loss: 0.9976 | Train acc: 50.47% | Val loss: 0.9645 | Val acc: 53.49% | LR: 0.000446
Epoch: 006 | Train loss: 0.9943 | Train acc: 50.79% | Val loss: 0.9755 | Val acc: 53.83% | LR: 0.000446
Epoch: 007 | Train loss: 0.9906 | Train acc: 50.87% | Val loss: 0.9697 | Val acc: 54.21% | LR: 0.000445
Epoch: 008 | Train loss: 1.0014 | Train acc: 50.05% | Val loss: 0.9690 | Val acc: 54.40% | LR: 0.000444
Epoch: 009 | Train loss: 0.9908 | Train acc: 50.82% | Val loss: 0.9684 | Val acc: 54.55% | LR: 0.000443
Epoch: 010 | Train loss: 0.9824 | Train acc: 51.37% | Val loss: 0.9704 | Val acc: 53.82% | LR: 0.000442
Epoch: 011 | Train loss: 0.9896 | Train acc: 50.86% | Val loss: 0.9753 | Val acc: 53.30% | LR: 0.000441
Epoch: 012 | Train loss: 0.9954 | Train acc: 50.37% | Val loss: 0.9795 | Val acc: 52.41% | LR: 0.000440
Epoch: 013 | Train loss: 0.9916 | Train acc: 50.61% | Val loss: 0.9848 | Val acc: 51.41% | LR: 0.000438
Epoch: 014 | Train loss: 0.9848 | Train acc: 51.13% | Val loss: 0.9922 | Val acc: 50.69% | LR: 0.000437
Epoch: 015 | Train loss: 0.9830 | Train acc: 51.47% | Val loss: 0.9964 | Val acc: 50.15% | LR: 0.000436
Epoch: 016 | Train loss: 0.9855 | Train acc: 50.82% | Val loss: 0.9968 | Val acc: 50.01% | LR: 0.000434
Epoch: 017 | Train loss: 0.9834 | Train acc: 51.28% | Val loss: 1.0015 | Val acc: 50.22% | LR: 0.000432
Epoch: 018 | Train loss: 0.9902 | Train acc: 50.65% | Val loss: 1.0011 | Val acc: 49.35% | LR: 0.000431
Epoch: 019 | Train loss: 0.9830 | Train acc: 51.22% | Val loss: 1.0080 | Val acc: 49.48% | LR: 0.000429
Epoch: 020 | Train loss: 0.9944 | Train acc: 50.95% | Val loss: 0.9670 | Val acc: 52.80% | LR: 0.000427
Epoch: 021 | Train loss: 1.0017 | Train acc: 50.46% | Val loss: 0.9817 | Val acc: 53.31% | LR: 0.000425
Epoch: 022 | Train loss: 0.9940 | Train acc: 50.73% | Val loss: 0.9894 | Val acc: 53.67% | LR: 0.000423
Epoch: 023 | Train loss: 1.0001 | Train acc: 50.69% | Val loss: 0.9717 | Val acc: 53.95% | LR: 0.000420
Epoch: 024 | Train loss: 0.9878 | Train acc: 51.28% | Val loss: 0.9693 | Val acc: 53.39% | LR: 0.000418
Epoch: 025 | Train loss: 0.9923 | Train acc: 50.73% | Val loss: 0.9750 | Val acc: 52.35% | LR: 0.000416
Epoch: 026 | Train loss: 0.9946 | Train acc: 50.41% | Val loss: 0.9609 | Val acc: 52.76% | LR: 0.000413
Epoch: 027 | Train loss: 0.9881 | Train acc: 50.90% | Val loss: 0.9545 | Val acc: 53.74% | LR: 0.000411
Epoch: 028 | Train loss: 0.9834 | Train acc: 51.25% | Val loss: 0.9525 | Val acc: 53.78% | LR: 0.000408
Epoch: 029 | Train loss: 0.9965 | Train acc: 50.19% | Val loss: 0.9579 | Val acc: 53.66% | LR: 0.000405
Epoch: 030 | Train loss: 0.9915 | Train acc: 50.76% | Val loss: 0.9747 | Val acc: 52.36% | LR: 0.000403
Epoch: 031 | Train loss: 0.9897 | Train acc: 50.65% | Val loss: 0.9809 | Val acc: 50.92% | LR: 0.000400
Epoch: 032 | Train loss: 0.9889 | Train acc: 50.57% | Val loss: 0.9873 | Val acc: 50.65% | LR: 0.000397
Epoch: 033 | Train loss: 0.9867 | Train acc: 50.95% | Val loss: 0.9657 | Val acc: 52.45% | LR: 0.000394
Epoch: 034 | Train loss: 0.9840 | Train acc: 51.20% | Val loss: 0.9726 | Val acc: 52.42% | LR: 0.000391
Epoch: 035 | Train loss: 0.9818 | Train acc: 51.04% | Val loss: 0.9737 | Val acc: 52.16% | LR: 0.000387
Epoch: 036 | Train loss: 0.9897 | Train acc: 49.87% | Val loss: 0.9697 | Val acc: 52.53% | LR: 0.000384
Epoch: 037 | Train loss: 0.9963 | Train acc: 49.90% | Val loss: 0.9728 | Val acc: 52.34% | LR: 0.000381
Epoch: 038 | Train loss: 0.9882 | Train acc: 50.45% | Val loss: 0.9707 | Val acc: 52.44% | LR: 0.000378
Epoch: 039 | Train loss: 0.9872 | Train acc: 50.48% | Val loss: 0.9743 | Val acc: 51.96% | LR: 0.000374
Epoch: 040 | Train loss: 0.9960 | Train acc: 50.40% | Val loss: 0.9806 | Val acc: 51.17% | LR: 0.000371
Epoch: 041 | Train loss: 0.9853 | Train acc: 51.30% | Val loss: 0.9971 | Val acc: 51.24% | LR: 0.000367
Epoch: 042 | Train loss: 4.5893 | Train acc: 50.88% | Val loss: 0.9930 | Val acc: 51.76% | LR: 0.000363
Epoch: 043 | Train loss: 1.0321 | Train acc: 51.16% | Val loss: 0.9898 | Val acc: 51.15% | LR: 0.000360
Epoch: 044 | Train loss: 0.9870 | Train acc: 51.47% | Val loss: 0.9812 | Val acc: 51.38% | LR: 0.000356
Epoch: 045 | Train loss: 0.9849 | Train acc: 51.49% | Val loss: 0.9780 | Val acc: 51.34% | LR: 0.000352
Epoch: 046 | Train loss: 0.9858 | Train acc: 51.15% | Val loss: 0.9722 | Val acc: 51.21% | LR: 0.000348
Epoch: 047 | Train loss: 0.9901 | Train acc: 50.68% | Val loss: 0.9730 | Val acc: 51.81% | LR: 0.000344
Epoch: 048 | Train loss: 0.9884 | Train acc: 50.72% | Val loss: 0.9788 | Val acc: 51.40% | LR: 0.000340
Epoch: 049 | Train loss: 0.9877 | Train acc: 51.09% | Val loss: 0.9756 | Val acc: 51.63% | LR: 0.000336
Epoch: 050 | Train loss: 0.9914 | Train acc: 50.68% | Val loss: 0.9753 | Val acc: 51.69% | LR: 0.000332
Epoch: 051 | Train loss: 0.9853 | Train acc: 51.03% | Val loss: 0.9753 | Val acc: 51.64% | LR: 0.000328
Epoch: 052 | Train loss: 0.9880 | Train acc: 50.73% | Val loss: 0.9748 | Val acc: 51.77% | LR: 0.000324
Epoch: 053 | Train loss: 0.9878 | Train acc: 51.01% | Val loss: 0.9714 | Val acc: 51.80% | LR: 0.000320
Epoch: 054 | Train loss: 0.9828 | Train acc: 51.05% | Val loss: 0.9737 | Val acc: 51.76% | LR: 0.000315
Epoch: 055 | Train loss: 0.9822 | Train acc: 51.17% | Val loss: 0.9728 | Val acc: 51.37% | LR: 0.000311
Epoch: 056 | Train loss: 0.9872 | Train acc: 50.93% | Val loss: 0.9732 | Val acc: 51.23% | LR: 0.000307
Epoch: 057 | Train loss: 0.9830 | Train acc: 51.19% | Val loss: 0.9708 | Val acc: 51.51% | LR: 0.000302
Epoch: 058 | Train loss: 0.9889 | Train acc: 50.85% | Val loss: 0.9741 | Val acc: 51.57% | LR: 0.000298
Epoch: 059 | Train loss: 0.9868 | Train acc: 51.00% | Val loss: 0.9757 | Val acc: 51.43% | LR: 0.000294
Epoch: 060 | Train loss: 0.9798 | Train acc: 51.60% | Val loss: 0.9757 | Val acc: 51.25% | LR: 0.000289
Epoch: 061 | Train loss: 0.9874 | Train acc: 50.80% | Val loss: 0.9764 | Val acc: 51.59% | LR: 0.000285
Epoch: 062 | Train loss: 0.9875 | Train acc: 50.91% | Val loss: 0.9810 | Val acc: 51.81% | LR: 0.000280
Epoch: 063 | Train loss: 0.9817 | Train acc: 51.20% | Val loss: 0.9616 | Val acc: 52.82% | LR: 0.000276
Epoch: 064 | Train loss: 0.9822 | Train acc: 51.01% | Val loss: 0.9740 | Val acc: 52.83% | LR: 0.000271
Epoch: 065 | Train loss: 0.9838 | Train acc: 51.00% | Val loss: 0.9572 | Val acc: 53.02% | LR: 0.000266
Epoch: 066 | Train loss: 0.9920 | Train acc: 50.40% | Val loss: 0.9548 | Val acc: 53.05% | LR: 0.000262
Epoch: 067 | Train loss: 0.9858 | Train acc: 50.78% | Val loss: 0.9569 | Val acc: 53.01% | LR: 0.000257
Epoch: 068 | Train loss: 0.9884 | Train acc: 50.80% | Val loss: 0.9567 | Val acc: 52.99% | LR: 0.000253
Epoch: 069 | Train loss: 0.9830 | Train acc: 51.15% | Val loss: 0.9595 | Val acc: 53.02% | LR: 0.000248
Epoch: 070 | Train loss: 0.9799 | Train acc: 51.24% | Val loss: 0.9622 | Val acc: 52.94% | LR: 0.000243
Epoch: 071 | Train loss: 0.9847 | Train acc: 50.97% | Val loss: 0.9807 | Val acc: 52.19% | LR: 0.000239
Epoch: 072 | Train loss: 0.9904 | Train acc: 50.35% | Val loss: 0.9696 | Val acc: 52.09% | LR: 0.000234
Epoch: 073 | Train loss: 0.9850 | Train acc: 50.88% | Val loss: 0.9705 | Val acc: 52.28% | LR: 0.000229
Epoch: 074 | Train loss: 0.9846 | Train acc: 50.74% | Val loss: 0.9640 | Val acc: 52.46% | LR: 0.000225
Epoch: 075 | Train loss: 0.9799 | Train acc: 51.18% | Val loss: 0.9690 | Val acc: 52.42% | LR: 0.000220
Epoch: 076 | Train loss: 0.9878 | Train acc: 50.91% | Val loss: 0.9660 | Val acc: 52.73% | LR: 0.000215
Epoch: 077 | Train loss: 0.9879 | Train acc: 50.47% | Val loss: 0.9676 | Val acc: 52.77% | LR: 0.000210
Epoch: 078 | Train loss: 0.9859 | Train acc: 50.65% | Val loss: 0.9656 | Val acc: 52.65% | LR: 0.000206
Epoch: 079 | Train loss: 0.9828 | Train acc: 51.19% | Val loss: 0.9697 | Val acc: 52.45% | LR: 0.000201
Epoch: 080 | Train loss: 0.9842 | Train acc: 50.94% | Val loss: 0.9652 | Val acc: 52.68% | LR: 0.000196
Epoch: 081 | Train loss: 0.9876 | Train acc: 50.74% | Val loss: 0.9682 | Val acc: 52.52% | LR: 0.000192
Epoch: 082 | Train loss: 0.9885 | Train acc: 50.64% | Val loss: 0.9700 | Val acc: 52.39% | LR: 0.000187
Epoch: 083 | Train loss: 0.9856 | Train acc: 50.90% | Val loss: 0.9692 | Val acc: 52.76% | LR: 0.000183
Epoch: 084 | Train loss: 0.9880 | Train acc: 50.80% | Val loss: 0.9635 | Val acc: 53.09% | LR: 0.000178
Epoch: 085 | Train loss: 0.9906 | Train acc: 50.45% | Val loss: 0.9630 | Val acc: 52.89% | LR: 0.000173
Epoch: 086 | Train loss: 0.9801 | Train acc: 51.19% | Val loss: 0.9668 | Val acc: 52.86% | LR: 0.000169
Epoch: 087 | Train loss: 0.9894 | Train acc: 50.49% | Val loss: 0.9693 | Val acc: 52.47% | LR: 0.000164
Epoch: 088 | Train loss: 0.9812 | Train acc: 51.02% | Val loss: 0.9712 | Val acc: 52.02% | LR: 0.000160
Epoch: 089 | Train loss: 0.9777 | Train acc: 51.39% | Val loss: 0.9780 | Val acc: 51.91% | LR: 0.000155
Epoch: 090 | Train loss: 0.9790 | Train acc: 51.42% | Val loss: 0.9828 | Val acc: 51.52% | LR: 0.000151
Epoch: 091 | Train loss: 0.9828 | Train acc: 51.25% | Val loss: 0.9853 | Val acc: 51.28% | LR: 0.000147
Epoch: 092 | Train loss: 0.9891 | Train acc: 50.56% | Val loss: 0.9809 | Val acc: 51.72% | LR: 0.000142
Epoch: 093 | Train loss: 0.9890 | Train acc: 50.75% | Val loss: 0.9762 | Val acc: 51.81% | LR: 0.000138
Epoch: 094 | Train loss: 0.9826 | Train acc: 51.18% | Val loss: 0.9907 | Val acc: 52.03% | LR: 0.000134
Epoch: 095 | Train loss: 0.9863 | Train acc: 50.95% | Val loss: 0.9733 | Val acc: 52.03% | LR: 0.000129
Epoch: 096 | Train loss: 0.9850 | Train acc: 50.99% | Val loss: 0.9778 | Val acc: 51.84% | LR: 0.000125
Epoch: 097 | Train loss: 0.9844 | Train acc: 51.00% | Val loss: 0.9814 | Val acc: 51.81% | LR: 0.000121
Epoch: 098 | Train loss: 0.9880 | Train acc: 50.83% | Val loss: 0.9936 | Val acc: 51.72% | LR: 0.000117
Epoch: 099 | Train loss: 0.9835 | Train acc: 50.95% | Val loss: 0.9795 | Val acc: 51.71% | LR: 0.000113
Epoch: 100 | Train loss: 0.9859 | Train acc: 50.95% | Val loss: 0.9917 | Val acc: 51.69% | LR: 0.000109
Epoch: 101 | Train loss: 0.9870 | Train acc: 50.81% | Val loss: 0.9762 | Val acc: 52.08% | LR: 0.000105
Epoch: 102 | Train loss: 0.9812 | Train acc: 51.05% | Val loss: 0.9744 | Val acc: 51.99% | LR: 0.000101
Epoch: 103 | Train loss: 0.9845 | Train acc: 50.78% | Val loss: 0.9746 | Val acc: 51.92% | LR: 0.000097
Epoch: 104 | Train loss: 0.9827 | Train acc: 50.92% | Val loss: 0.9767 | Val acc: 51.97% | LR: 0.000093
Epoch: 105 | Train loss: 0.9775 | Train acc: 51.39% | Val loss: 0.9763 | Val acc: 51.75% | LR: 0.000089
Epoch: 106 | Train loss: 0.9863 | Train acc: 50.75% | Val loss: 0.9784 | Val acc: 51.89% | LR: 0.000086
Epoch: 107 | Train loss: 0.9847 | Train acc: 50.91% | Val loss: 0.9770 | Val acc: 51.67% | LR: 0.000082
Epoch: 108 | Train loss: 0.9902 | Train acc: 50.38% | Val loss: 0.9839 | Val acc: 51.62% | LR: 0.000078
Epoch: 109 | Train loss: 0.9856 | Train acc: 51.20% | Val loss: 0.9786 | Val acc: 51.77% | LR: 0.000075
Epoch: 110 | Train loss: 0.9832 | Train acc: 51.12% | Val loss: 0.9784 | Val acc: 51.79% | LR: 0.000072
Epoch: 111 | Train loss: 0.9803 | Train acc: 51.28% | Val loss: 0.9750 | Val acc: 51.79% | LR: 0.000068
Epoch: 112 | Train loss: 0.9757 | Train acc: 51.55% | Val loss: 0.9749 | Val acc: 51.73% | LR: 0.000065
Epoch: 113 | Train loss: 0.9796 | Train acc: 51.26% | Val loss: 0.9763 | Val acc: 51.77% | LR: 0.000062
Epoch: 114 | Train loss: 0.9856 | Train acc: 50.83% | Val loss: 0.9756 | Val acc: 51.75% | LR: 0.000058
Epoch: 115 | Train loss: 0.9767 | Train acc: 51.45% | Val loss: 0.9757 | Val acc: 51.73% | LR: 0.000055
Epoch: 116 | Train loss: 0.9852 | Train acc: 50.92% | Val loss: 0.9761 | Val acc: 51.71% | LR: 0.000052
Epoch: 117 | Train loss: 0.9820 | Train acc: 51.03% | Val loss: 0.9762 | Val acc: 51.71% | LR: 0.000049
Epoch: 118 | Train loss: 0.9821 | Train acc: 50.85% | Val loss: 0.9785 | Val acc: 51.63% | LR: 0.000046
Epoch: 119 | Train loss: 0.9865 | Train acc: 50.83% | Val loss: 0.9838 | Val acc: 51.65% | LR: 0.000044
Epoch: 120 | Train loss: 0.9746 | Train acc: 51.71% | Val loss: 0.9761 | Val acc: 51.54% | LR: 0.000041
Epoch: 121 | Train loss: 0.9757 | Train acc: 51.53% | Val loss: 0.9756 | Val acc: 51.54% | LR: 0.000038
Epoch: 122 | Train loss: 0.9841 | Train acc: 51.01% | Val loss: 0.9758 | Val acc: 51.52% | LR: 0.000036
Epoch: 123 | Train loss: 0.9832 | Train acc: 51.00% | Val loss: 0.9785 | Val acc: 51.52% | LR: 0.000033
Epoch: 124 | Train loss: 0.9826 | Train acc: 51.01% | Val loss: 0.9760 | Val acc: 51.60% | LR: 0.000031
Epoch: 125 | Train loss: 0.9799 | Train acc: 51.11% | Val loss: 0.9770 | Val acc: 51.60% | LR: 0.000029
Epoch: 126 | Train loss: 0.9805 | Train acc: 51.26% | Val loss: 0.9772 | Val acc: 51.50% | LR: 0.000026
Epoch: 127 | Train loss: 0.9859 | Train acc: 50.75% | Val loss: 0.9770 | Val acc: 51.54% | LR: 0.000024
Epoch: 128 | Train loss: 0.9795 | Train acc: 51.28% | Val loss: 0.9812 | Val acc: 51.54% | LR: 0.000022
Epoch: 129 | Train loss: 0.9833 | Train acc: 50.93% | Val loss: 0.9795 | Val acc: 51.48% | LR: 0.000020
Epoch: 130 | Train loss: 0.9796 | Train acc: 51.20% | Val loss: 0.9775 | Val acc: 51.60% | LR: 0.000018
Epoch: 131 | Train loss: 0.9844 | Train acc: 50.91% | Val loss: 0.9891 | Val acc: 51.60% | LR: 0.000017
Epoch: 132 | Train loss: 0.9852 | Train acc: 50.92% | Val loss: 0.9809 | Val acc: 51.54% | LR: 0.000015
Epoch: 133 | Train loss: 0.9844 | Train acc: 50.84% | Val loss: 0.9764 | Val acc: 51.64% | LR: 0.000013
Epoch: 134 | Train loss: 0.9750 | Train acc: 51.53% | Val loss: 0.9772 | Val acc: 51.58% | LR: 0.000012
Epoch: 135 | Train loss: 0.9841 | Train acc: 50.93% | Val loss: 0.9824 | Val acc: 51.52% | LR: 0.000011
Epoch: 136 | Train loss: 0.9862 | Train acc: 50.84% | Val loss: 0.9794 | Val acc: 51.52% | LR: 0.000009
Epoch: 137 | Train loss: 0.9836 | Train acc: 50.94% | Val loss: 0.9775 | Val acc: 51.62% | LR: 0.000008
Epoch: 138 | Train loss: 0.9764 | Train acc: 51.48% | Val loss: 0.9776 | Val acc: 51.50% | LR: 0.000007
Epoch: 139 | Train loss: 0.9846 | Train acc: 50.83% | Val loss: 0.9774 | Val acc: 51.52% | LR: 0.000006
Epoch: 140 | Train loss: 0.9858 | Train acc: 50.75% | Val loss: 0.9770 | Val acc: 51.52% | LR: 0.000005
Epoch: 141 | Train loss: 0.9859 | Train acc: 50.76% | Val loss: 0.9784 | Val acc: 51.56% | LR: 0.000004
Epoch: 142 | Train loss: 0.9801 | Train acc: 51.11% | Val loss: 0.9841 | Val acc: 51.50% | LR: 0.000003
Epoch: 143 | Train loss: 0.9785 | Train acc: 51.30% | Val loss: 0.9769 | Val acc: 51.48% | LR: 0.000003
Epoch: 144 | Train loss: 0.9842 | Train acc: 51.01% | Val loss: 0.9769 | Val acc: 51.58% | LR: 0.000002
Epoch: 145 | Train loss: 0.9789 | Train acc: 51.12% | Val loss: 0.9778 | Val acc: 51.50% | LR: 0.000002
Epoch: 146 | Train loss: 0.9832 | Train acc: 51.01% | Val loss: 0.9766 | Val acc: 51.50% | LR: 0.000001
Epoch: 147 | Train loss: 0.9848 | Train acc: 50.85% | Val loss: 0.9765 | Val acc: 51.48% | LR: 0.000001
Epoch: 148 | Train loss: 0.9826 | Train acc: 51.03% | Val loss: 0.9766 | Val acc: 51.48% | LR: 0.000001
Epoch: 149 | Train loss: 0.9760 | Train acc: 51.47% | Val loss: 0.9804 | Val acc: 51.44% | LR: 0.000001

[I 2025-09-23 01:36:26,814] Trial 2 finished with value: 0.5457171559333801 and parameters: {'lr': 0.00044801856866603647, 'hidden_size': 221, 'dropout': 0.42942585756865936, 'weight_decay': 0.3472210953957966}. Best is trial 2 with value: 0.5457171559333801.

Epoch: 000 | Train loss: 1.0378 | Train acc: 50.39% | Val loss: 1.0037 | Val acc: 45.67% | LR: 0.000264
Epoch: 001 | Train loss: 1.0045 | Train acc: 49.57% | Val loss: 1.0134 | Val acc: 49.14% | LR: 0.000264
Epoch: 002 | Train loss: 0.9926 | Train acc: 50.69% | Val loss: 1.0046 | Val acc: 49.47% | LR: 0.000264
Epoch: 003 | Train loss: 0.9931 | Train acc: 50.86% | Val loss: 0.9998 | Val acc: 49.96% | LR: 0.000264
Epoch: 004 | Train loss: 0.9948 | Train acc: 50.71% | Val loss: 0.9985 | Val acc: 50.86% | LR: 0.000264
Epoch: 005 | Train loss: 0.9958 | Train acc: 50.66% | Val loss: 0.9982 | Val acc: 50.72% | LR: 0.000263
Epoch: 006 | Train loss: 0.9946 | Train acc: 51.08% | Val loss: 0.9971 | Val acc: 51.03% | LR: 0.000263
Epoch: 007 | Train loss: 0.9924 | Train acc: 51.16% | Val loss: 0.9962 | Val acc: 51.11% | LR: 0.000263
Epoch: 008 | Train loss: 0.9926 | Train acc: 51.25% | Val loss: 0.9951 | Val acc: 51.49% | LR: 0.000262
Epoch: 009 | Train loss: 0.9875 | Train acc: 51.32% | Val loss: 0.9939 | Val acc: 51.31% | LR: 0.000262
Epoch: 010 | Train loss: 0.9850 | Train acc: 51.42% | Val loss: 0.9913 | Val acc: 51.48% | LR: 0.000261
Epoch: 011 | Train loss: 0.9979 | Train acc: 50.70% | Val loss: 0.9863 | Val acc: 51.96% | LR: 0.000260
Epoch: 012 | Train loss: 0.9904 | Train acc: 50.84% | Val loss: 0.9812 | Val acc: 51.87% | LR: 0.000260
Epoch: 013 | Train loss: 0.9860 | Train acc: 51.05% | Val loss: 0.9822 | Val acc: 51.62% | LR: 0.000259
Epoch: 014 | Train loss: 0.9887 | Train acc: 51.03% | Val loss: 0.9852 | Val acc: 50.98% | LR: 0.000258
Epoch: 015 | Train loss: 0.9854 | Train acc: 51.38% | Val loss: 0.9894 | Val acc: 50.91% | LR: 0.000257
Epoch: 016 | Train loss: 0.9878 | Train acc: 51.03% | Val loss: 0.9926 | Val acc: 50.70% | LR: 0.000256
Epoch: 017 | Train loss: 0.9833 | Train acc: 51.44% | Val loss: 1.0015 | Val acc: 49.79% | LR: 0.000255
Epoch: 018 | Train loss: 0.9816 | Train acc: 51.36% | Val loss: 1.0004 | Val acc: 49.81% | LR: 0.000254
Epoch: 019 | Train loss: 0.9889 | Train acc: 50.75% | Val loss: 0.9996 | Val acc: 49.81% | LR: 0.000253
Epoch: 020 | Train loss: 0.9838 | Train acc: 51.11% | Val loss: 1.0082 | Val acc: 48.63% | LR: 0.000252
Epoch: 021 | Train loss: 0.9889 | Train acc: 50.90% | Val loss: 1.0137 | Val acc: 48.51% | LR: 0.000251
Epoch: 022 | Train loss: 0.9924 | Train acc: 50.42% | Val loss: 1.0145 | Val acc: 48.46% | LR: 0.000249
Epoch: 023 | Train loss: 0.9857 | Train acc: 51.14% | Val loss: 1.0133 | Val acc: 48.82% | LR: 0.000248
Epoch: 024 | Train loss: 0.9820 | Train acc: 51.12% | Val loss: 1.0175 | Val acc: 48.42% | LR: 0.000247
Epoch: 025 | Train loss: 0.9839 | Train acc: 51.04% | Val loss: 1.0161 | Val acc: 48.66% | LR: 0.000245
Epoch: 026 | Train loss: 0.9900 | Train acc: 50.89% | Val loss: 1.0144 | Val acc: 48.65% | LR: 0.000244
Epoch: 027 | Train loss: 0.9854 | Train acc: 51.08% | Val loss: 1.0037 | Val acc: 49.54% | LR: 0.000242
Epoch: 028 | Train loss: 0.9890 | Train acc: 50.91% | Val loss: 1.0136 | Val acc: 49.00% | LR: 0.000241
Epoch: 029 | Train loss: 0.9845 | Train acc: 51.26% | Val loss: 1.0253 | Val acc: 48.12% | LR: 0.000239
Epoch: 030 | Train loss: 0.9860 | Train acc: 50.95% | Val loss: 1.0113 | Val acc: 49.29% | LR: 0.000238
Epoch: 031 | Train loss: 0.9812 | Train acc: 51.23% | Val loss: 1.0204 | Val acc: 48.62% | LR: 0.000236
Epoch: 032 | Train loss: 0.9810 | Train acc: 51.27% | Val loss: 1.0123 | Val acc: 49.18% | LR: 0.000234
Epoch: 033 | Train loss: 0.9774 | Train acc: 51.64% | Val loss: 1.0025 | Val acc: 49.69% | LR: 0.000232
Epoch: 034 | Train loss: 0.9825 | Train acc: 51.27% | Val loss: 1.0058 | Val acc: 49.39% | LR: 0.000231
Epoch: 035 | Train loss: 0.9809 | Train acc: 51.29% | Val loss: 1.0058 | Val acc: 49.49% | LR: 0.000229
Epoch: 036 | Train loss: 0.9786 | Train acc: 51.46% | Val loss: 1.0124 | Val acc: 49.47% | LR: 0.000227
Epoch: 037 | Train loss: 0.9833 | Train acc: 51.08% | Val loss: 1.0116 | Val acc: 49.47% | LR: 0.000225
Epoch: 038 | Train loss: 0.9870 | Train acc: 50.76% | Val loss: 0.9992 | Val acc: 49.80% | LR: 0.000223
Epoch: 039 | Train loss: 0.9822 | Train acc: 51.10% | Val loss: 1.0097 | Val acc: 49.36% | LR: 0.000221
Epoch: 040 | Train loss: 0.9789 | Train acc: 51.39% | Val loss: 1.0211 | Val acc: 48.76% | LR: 0.000219
Epoch: 041 | Train loss: 0.9833 | Train acc: 50.99% | Val loss: 1.0138 | Val acc: 49.13% | LR: 0.000217
Epoch: 042 | Train loss: 0.9760 | Train acc: 51.49% | Val loss: 1.0050 | Val acc: 49.34% | LR: 0.000215
Epoch: 043 | Train loss: 0.9849 | Train acc: 50.94% | Val loss: 1.0092 | Val acc: 49.29% | LR: 0.000212
Epoch: 044 | Train loss: 0.9828 | Train acc: 50.97% | Val loss: 1.0137 | Val acc: 49.05% | LR: 0.000210
Epoch: 045 | Train loss: 0.9803 | Train acc: 51.33% | Val loss: 1.0110 | Val acc: 49.39% | LR: 0.000208
Epoch: 046 | Train loss: 0.9822 | Train acc: 51.29% | Val loss: 1.0228 | Val acc: 48.65% | LR: 0.000206
Epoch: 047 | Train loss: 0.9831 | Train acc: 50.99% | Val loss: 1.0153 | Val acc: 48.78% | LR: 0.000203
Epoch: 048 | Train loss: 0.9835 | Train acc: 51.10% | Val loss: 1.0013 | Val acc: 49.30% | LR: 0.000201
Epoch: 049 | Train loss: 0.9756 | Train acc: 51.49% | Val loss: 0.9939 | Val acc: 49.93% | LR: 0.000199
Epoch: 050 | Train loss: 0.9856 | Train acc: 50.87% | Val loss: 1.0057 | Val acc: 49.38% | LR: 0.000196
Epoch: 051 | Train loss: 0.9877 | Train acc: 50.78% | Val loss: 1.0054 | Val acc: 49.36% | LR: 0.000194
Epoch: 052 | Train loss: 0.9902 | Train acc: 50.64% | Val loss: 1.0093 | Val acc: 49.32% | LR: 0.000191
Epoch: 053 | Train loss: 0.9817 | Train acc: 51.27% | Val loss: 1.0063 | Val acc: 49.17% | LR: 0.000189
Epoch: 054 | Train loss: 0.9787 | Train acc: 51.41% | Val loss: 0.9987 | Val acc: 49.58% | LR: 0.000186
Epoch: 055 | Train loss: 0.9759 | Train acc: 51.55% | Val loss: 0.9915 | Val acc: 50.45% | LR: 0.000184
Epoch: 056 | Train loss: 0.9781 | Train acc: 51.37% | Val loss: 0.9955 | Val acc: 50.07% | LR: 0.000181
Epoch: 057 | Train loss: 0.9840 | Train acc: 50.99% | Val loss: 0.9876 | Val acc: 50.79% | LR: 0.000179
Epoch: 058 | Train loss: 0.9839 | Train acc: 50.96% | Val loss: 0.9971 | Val acc: 50.25% | LR: 0.000176
Epoch: 059 | Train loss: 0.9816 | Train acc: 51.06% | Val loss: 0.9911 | Val acc: 50.25% | LR: 0.000173
Epoch: 060 | Train loss: 0.9768 | Train acc: 51.49% | Val loss: 0.9801 | Val acc: 51.38% | LR: 0.000171
Epoch: 061 | Train loss: 0.9790 | Train acc: 51.19% | Val loss: 1.0002 | Val acc: 49.90% | LR: 0.000168
Epoch: 062 | Train loss: 0.9843 | Train acc: 50.90% | Val loss: 0.9887 | Val acc: 50.55% | LR: 0.000165
Epoch: 063 | Train loss: 0.9895 | Train acc: 50.68% | Val loss: 0.9921 | Val acc: 50.49% | LR: 0.000163
Epoch: 064 | Train loss: 0.9794 | Train acc: 51.23% | Val loss: 0.9860 | Val acc: 50.84% | LR: 0.000160
Epoch: 065 | Train loss: 0.9691 | Train acc: 51.96% | Val loss: 0.9884 | Val acc: 50.92% | LR: 0.000157
Epoch: 066 | Train loss: 0.9868 | Train acc: 50.72% | Val loss: 0.9831 | Val acc: 50.99% | LR: 0.000155
Epoch: 067 | Train loss: 0.9810 | Train acc: 51.18% | Val loss: 0.9912 | Val acc: 50.57% | LR: 0.000152
Epoch: 068 | Train loss: 0.9723 | Train acc: 51.90% | Val loss: 0.9842 | Val acc: 51.03% | LR: 0.000149
Epoch: 069 | Train loss: 0.9683 | Train acc: 52.10% | Val loss: 0.9861 | Val acc: 50.73% | LR: 0.000146
Epoch: 070 | Train loss: 0.9856 | Train acc: 50.90% | Val loss: 0.9875 | Val acc: 50.92% | LR: 0.000144
Epoch: 071 | Train loss: 0.9837 | Train acc: 51.00% | Val loss: 0.9872 | Val acc: 50.81% | LR: 0.000141
Epoch: 072 | Train loss: 0.9783 | Train acc: 51.29% | Val loss: 0.9890 | Val acc: 50.57% | LR: 0.000138
Epoch: 073 | Train loss: 0.9816 | Train acc: 51.07% | Val loss: 0.9869 | Val acc: 50.84% | LR: 0.000135
Epoch: 074 | Train loss: 0.9848 | Train acc: 50.81% | Val loss: 0.9897 | Val acc: 50.63% | LR: 0.000133
Epoch: 075 | Train loss: 0.9818 | Train acc: 51.00% | Val loss: 0.9845 | Val acc: 50.78% | LR: 0.000130
Epoch: 076 | Train loss: 0.9879 | Train acc: 50.66% | Val loss: 0.9903 | Val acc: 50.57% | LR: 0.000127
Epoch: 077 | Train loss: 0.9873 | Train acc: 50.71% | Val loss: 0.9829 | Val acc: 50.87% | LR: 0.000124
Epoch: 078 | Train loss: 0.9858 | Train acc: 50.63% | Val loss: 0.9860 | Val acc: 50.67% | LR: 0.000122
Epoch: 079 | Train loss: 0.9810 | Train acc: 50.90% | Val loss: 0.9896 | Val acc: 50.67% | LR: 0.000119
Epoch: 080 | Train loss: 0.9858 | Train acc: 50.71% | Val loss: 0.9832 | Val acc: 50.71% | LR: 0.000116
Epoch: 081 | Train loss: 0.9811 | Train acc: 51.15% | Val loss: 0.9836 | Val acc: 50.90% | LR: 0.000113
Epoch: 082 | Train loss: 0.9814 | Train acc: 51.08% | Val loss: 0.9825 | Val acc: 50.98% | LR: 0.000111
Epoch: 083 | Train loss: 0.9739 | Train acc: 51.81% | Val loss: 0.9912 | Val acc: 50.59% | LR: 0.000108
Epoch: 084 | Train loss: 0.9760 | Train acc: 51.58% | Val loss: 0.9912 | Val acc: 50.44% | LR: 0.000105
Epoch: 085 | Train loss: 0.9791 | Train acc: 51.18% | Val loss: 0.9846 | Val acc: 50.73% | LR: 0.000103
Epoch: 086 | Train loss: 0.9713 | Train acc: 51.87% | Val loss: 0.9790 | Val acc: 51.16% | LR: 0.000100
Epoch: 087 | Train loss: 0.9809 | Train acc: 51.17% | Val loss: 0.9848 | Val acc: 50.77% | LR: 0.000097
Epoch: 088 | Train loss: 0.9736 | Train acc: 51.80% | Val loss: 0.9874 | Val acc: 50.61% | LR: 0.000095
Epoch: 089 | Train loss: 0.9819 | Train acc: 50.99% | Val loss: 0.9882 | Val acc: 50.65% | LR: 0.000092
Epoch: 090 | Train loss: 0.9813 | Train acc: 50.90% | Val loss: 0.9887 | Val acc: 50.70% | LR: 0.000089
Epoch: 091 | Train loss: 0.9800 | Train acc: 51.21% | Val loss: 0.9859 | Val acc: 50.80% | LR: 0.000087
Epoch: 092 | Train loss: 0.9756 | Train acc: 51.69% | Val loss: 0.9876 | Val acc: 50.69% | LR: 0.000084
Epoch: 093 | Train loss: 0.9800 | Train acc: 51.16% | Val loss: 0.9865 | Val acc: 50.73% | LR: 0.000082
Epoch: 094 | Train loss: 0.9808 | Train acc: 51.06% | Val loss: 0.9868 | Val acc: 50.68% | LR: 0.000079
Epoch: 095 | Train loss: 0.9790 | Train acc: 51.18% | Val loss: 0.9870 | Val acc: 50.69% | LR: 0.000077
Epoch: 096 | Train loss: 0.9742 | Train acc: 51.52% | Val loss: 0.9864 | Val acc: 50.69% | LR: 0.000074
Epoch: 097 | Train loss: 0.9804 | Train acc: 51.16% | Val loss: 0.9907 | Val acc: 50.49% | LR: 0.000072
Epoch: 098 | Train loss: 0.9774 | Train acc: 51.38% | Val loss: 0.9872 | Val acc: 50.75% | LR: 0.000069
Epoch: 099 | Train loss: 0.9832 | Train acc: 50.82% | Val loss: 0.9872 | Val acc: 50.77% | LR: 0.000067
Epoch: 100 | Train loss: 0.9759 | Train acc: 51.42% | Val loss: 0.9884 | Val acc: 50.62% | LR: 0.000064
Epoch: 101 | Train loss: 0.9751 | Train acc: 51.53% | Val loss: 0.9833 | Val acc: 50.87% | LR: 0.000062
Epoch: 102 | Train loss: 0.9722 | Train acc: 51.72% | Val loss: 0.9893 | Val acc: 50.65% | LR: 0.000060
Epoch: 103 | Train loss: 0.9817 | Train acc: 51.18% | Val loss: 0.9909 | Val acc: 50.43% | LR: 0.000058
Epoch: 104 | Train loss: 0.9803 | Train acc: 50.92% | Val loss: 0.9853 | Val acc: 50.77% | LR: 0.000055
Epoch: 105 | Train loss: 0.9709 | Train acc: 51.71% | Val loss: 0.9832 | Val acc: 50.95% | LR: 0.000053
Epoch: 106 | Train loss: 0.9844 | Train acc: 51.01% | Val loss: 0.9869 | Val acc: 50.63% | LR: 0.000051
Epoch: 107 | Train loss: 0.9784 | Train acc: 51.19% | Val loss: 0.9861 | Val acc: 50.78% | LR: 0.000049
Epoch: 108 | Train loss: 0.9805 | Train acc: 51.11% | Val loss: 0.9853 | Val acc: 50.78% | LR: 0.000047
Epoch: 109 | Train loss: 0.9731 | Train acc: 51.55% | Val loss: 0.9902 | Val acc: 50.47% | LR: 0.000045
Epoch: 110 | Train loss: 0.9780 | Train acc: 51.11% | Val loss: 0.9857 | Val acc: 50.78% | LR: 0.000043
Epoch: 111 | Train loss: 0.9792 | Train acc: 51.46% | Val loss: 0.9890 | Val acc: 50.55% | LR: 0.000041
Epoch: 112 | Train loss: 0.9730 | Train acc: 51.46% | Val loss: 0.9862 | Val acc: 50.74% | LR: 0.000039
Epoch: 113 | Train loss: 0.9695 | Train acc: 51.82% | Val loss: 0.9868 | Val acc: 50.70% | LR: 0.000037
Epoch: 114 | Train loss: 0.9807 | Train acc: 51.13% | Val loss: 0.9865 | Val acc: 50.78% | LR: 0.000035
Epoch: 115 | Train loss: 0.9815 | Train acc: 51.12% | Val loss: 0.9904 | Val acc: 50.49% | LR: 0.000033
Epoch: 116 | Train loss: 0.9785 | Train acc: 51.30% | Val loss: 0.9875 | Val acc: 50.72% | LR: 0.000031
Epoch: 117 | Train loss: 0.9764 | Train acc: 51.38% | Val loss: 0.9880 | Val acc: 50.72% | LR: 0.000029
Epoch: 118 | Train loss: 0.9750 | Train acc: 51.47% | Val loss: 0.9872 | Val acc: 50.72% | LR: 0.000028
Epoch: 119 | Train loss: 0.9821 | Train acc: 50.86% | Val loss: 0.9856 | Val acc: 50.76% | LR: 0.000026
Epoch: 120 | Train loss: 0.9785 | Train acc: 51.20% | Val loss: 0.9883 | Val acc: 50.60% | LR: 0.000025
Epoch: 121 | Train loss: 0.9829 | Train acc: 50.86% | Val loss: 0.9853 | Val acc: 50.71% | LR: 0.000023
Epoch: 122 | Train loss: 0.9807 | Train acc: 51.02% | Val loss: 0.9883 | Val acc: 50.64% | LR: 0.000022
Epoch: 123 | Train loss: 0.9694 | Train acc: 51.92% | Val loss: 0.9871 | Val acc: 50.72% | LR: 0.000020
Epoch: 124 | Train loss: 0.9697 | Train acc: 51.83% | Val loss: 0.9861 | Val acc: 50.78% | LR: 0.000019
Epoch: 125 | Train loss: 0.9804 | Train acc: 51.03% | Val loss: 0.9901 | Val acc: 50.57% | LR: 0.000017
Epoch: 126 | Train loss: 0.9762 | Train acc: 51.30% | Val loss: 0.9867 | Val acc: 50.78% | LR: 0.000016
Epoch: 127 | Train loss: 0.9757 | Train acc: 51.47% | Val loss: 0.9869 | Val acc: 50.78% | LR: 0.000015
Epoch: 128 | Train loss: 0.9726 | Train acc: 51.56% | Val loss: 0.9882 | Val acc: 50.72% | LR: 0.000014
Epoch: 129 | Train loss: 0.9753 | Train acc: 51.57% | Val loss: 0.9877 | Val acc: 50.74% | LR: 0.000012
Epoch: 130 | Train loss: 0.9842 | Train acc: 50.87% | Val loss: 0.9878 | Val acc: 50.74% | LR: 0.000011
Epoch: 131 | Train loss: 0.9734 | Train acc: 51.57% | Val loss: 0.9874 | Val acc: 50.74% | LR: 0.000010
Epoch: 132 | Train loss: 0.9763 | Train acc: 51.57% | Val loss: 0.9875 | Val acc: 50.72% | LR: 0.000009
Epoch: 133 | Train loss: 0.9761 | Train acc: 51.48% | Val loss: 0.9875 | Val acc: 50.72% | LR: 0.000008
Epoch: 134 | Train loss: 0.9774 | Train acc: 51.31% | Val loss: 0.9877 | Val acc: 50.74% | LR: 0.000007
Epoch: 135 | Train loss: 0.9803 | Train acc: 51.04% | Val loss: 0.9881 | Val acc: 50.70% | LR: 0.000007
Epoch: 136 | Train loss: 0.9769 | Train acc: 51.40% | Val loss: 0.9878 | Val acc: 50.72% | LR: 0.000006
Epoch: 137 | Train loss: 0.9751 | Train acc: 51.31% | Val loss: 0.9875 | Val acc: 50.72% | LR: 0.000005
Epoch: 138 | Train loss: 0.9781 | Train acc: 51.39% | Val loss: 0.9876 | Val acc: 50.72% | LR: 0.000004
Epoch: 139 | Train loss: 0.9780 | Train acc: 51.22% | Val loss: 0.9873 | Val acc: 50.74% | LR: 0.000004
Epoch: 140 | Train loss: 0.9782 | Train acc: 51.13% | Val loss: 0.9872 | Val acc: 50.72% | LR: 0.000003
Epoch: 141 | Train loss: 0.9724 | Train acc: 51.66% | Val loss: 0.9876 | Val acc: 50.74% | LR: 0.000003
Epoch: 142 | Train loss: 0.9799 | Train acc: 51.22% | Val loss: 0.9877 | Val acc: 50.74% | LR: 0.000002
Epoch: 143 | Train loss: 0.9805 | Train acc: 51.13% | Val loss: 0.9874 | Val acc: 50.72% | LR: 0.000002
Epoch: 144 | Train loss: 0.9767 | Train acc: 51.31% | Val loss: 0.9874 | Val acc: 50.72% | LR: 0.000002
Epoch: 145 | Train loss: 0.9773 | Train acc: 51.40% | Val loss: 0.9874 | Val acc: 50.72% | LR: 0.000001
Epoch: 146 | Train loss: 0.9737 | Train acc: 51.48% | Val loss: 0.9873 | Val acc: 50.72% | LR: 0.000001
Epoch: 147 | Train loss: 0.9782 | Train acc: 51.31% | Val loss: 0.9874 | Val acc: 50.72% | LR: 0.000001
Epoch: 148 | Train loss: 0.9797 | Train acc: 51.04% | Val loss: 0.9874 | Val acc: 50.72% | LR: 0.000001
Epoch: 149 | Train loss: 0.9759 | Train acc: 51.48% | Val loss: 0.9875 | Val acc: 50.72% | LR: 0.000001

[I 2025-09-23 01:40:47,685] Trial 3 finished with value: 0.5195775985717773 and parameters: {'lr': 0.0002644067224157414, 'hidden_size': 182, 'dropout': 0.4651232796800554, 'weight_decay': 0.4965378991886281}. Best is trial 2 with value: 0.5457171559333801.

Epoch: 000 | Train loss: 0.9980 | Train acc: 50.89% | Val loss: 1.0014 | Val acc: 46.86% | LR: 0.000101
Epoch: 001 | Train loss: 1.0452 | Train acc: 50.65% | Val loss: 1.0007 | Val acc: 48.59% | LR: 0.000101
Epoch: 002 | Train loss: 0.9981 | Train acc: 50.80% | Val loss: 0.9985 | Val acc: 50.44% | LR: 0.000101
Epoch: 003 | Train loss: 0.9948 | Train acc: 51.12% | Val loss: 0.9976 | Val acc: 50.88% | LR: 0.000101
Epoch: 004 | Train loss: 0.9953 | Train acc: 50.70% | Val loss: 0.9948 | Val acc: 51.02% | LR: 0.000101
Epoch: 005 | Train loss: 0.9932 | Train acc: 50.94% | Val loss: 0.9906 | Val acc: 51.68% | LR: 0.000101
Epoch: 006 | Train loss: 0.9914 | Train acc: 51.02% | Val loss: 0.9863 | Val acc: 51.67% | LR: 0.000100
Epoch: 007 | Train loss: 0.9862 | Train acc: 51.07% | Val loss: 0.9778 | Val acc: 52.56% | LR: 0.000100
Epoch: 008 | Train loss: 0.9860 | Train acc: 51.28% | Val loss: 0.9829 | Val acc: 51.23% | LR: 0.000100
Epoch: 009 | Train loss: 0.9817 | Train acc: 51.19% | Val loss: 0.9876 | Val acc: 50.90% | LR: 0.000100
Epoch: 010 | Train loss: 0.9863 | Train acc: 50.91% | Val loss: 0.9900 | Val acc: 50.76% | LR: 0.000100
Epoch: 011 | Train loss: 0.9912 | Train acc: 50.86% | Val loss: 0.9925 | Val acc: 50.71% | LR: 0.000099
Epoch: 012 | Train loss: 0.9826 | Train acc: 51.08% | Val loss: 0.9937 | Val acc: 50.61% | LR: 0.000099
Epoch: 013 | Train loss: 0.9823 | Train acc: 51.22% | Val loss: 0.9990 | Val acc: 49.96% | LR: 0.000099
Epoch: 014 | Train loss: 0.9850 | Train acc: 50.89% | Val loss: 1.0004 | Val acc: 49.88% | LR: 0.000099
Epoch: 015 | Train loss: 0.9831 | Train acc: 51.19% | Val loss: 1.0040 | Val acc: 49.74% | LR: 0.000098
Epoch: 016 | Train loss: 0.9794 | Train acc: 51.52% | Val loss: 1.0063 | Val acc: 49.19% | LR: 0.000098
Epoch: 017 | Train loss: 0.9952 | Train acc: 50.45% | Val loss: 1.0061 | Val acc: 49.33% | LR: 0.000098
Epoch: 018 | Train loss: 0.9835 | Train acc: 51.08% | Val loss: 1.0060 | Val acc: 49.27% | LR: 0.000097
Epoch: 019 | Train loss: 0.9868 | Train acc: 50.96% | Val loss: 1.0061 | Val acc: 49.53% | LR: 0.000097
Epoch: 020 | Train loss: 0.9827 | Train acc: 51.23% | Val loss: 1.0068 | Val acc: 49.35% | LR: 0.000096
Epoch: 021 | Train loss: 0.9848 | Train acc: 50.97% | Val loss: 1.0059 | Val acc: 49.39% | LR: 0.000096
Epoch: 022 | Train loss: 0.9843 | Train acc: 51.13% | Val loss: 1.0063 | Val acc: 49.35% | LR: 0.000095
Epoch: 023 | Train loss: 0.9889 | Train acc: 50.87% | Val loss: 1.0081 | Val acc: 49.31% | LR: 0.000095
Epoch: 024 | Train loss: 0.9842 | Train acc: 51.06% | Val loss: 1.0059 | Val acc: 49.35% | LR: 0.000094
Epoch: 025 | Train loss: 0.9906 | Train acc: 50.52% | Val loss: 1.0069 | Val acc: 49.37% | LR: 0.000094
Epoch: 026 | Train loss: 0.9810 | Train acc: 51.07% | Val loss: 1.0027 | Val acc: 49.59% | LR: 0.000093
Epoch: 027 | Train loss: 0.9816 | Train acc: 51.16% | Val loss: 1.0055 | Val acc: 49.59% | LR: 0.000093
Epoch: 028 | Train loss: 0.9823 | Train acc: 51.23% | Val loss: 1.0069 | Val acc: 49.41% | LR: 0.000092
Epoch: 029 | Train loss: 0.9910 | Train acc: 50.61% | Val loss: 1.0030 | Val acc: 49.59% | LR: 0.000091
Epoch: 030 | Train loss: 0.9839 | Train acc: 51.15% | Val loss: 1.0069 | Val acc: 49.37% | LR: 0.000091
Epoch: 031 | Train loss: 0.9742 | Train acc: 51.74% | Val loss: 1.0085 | Val acc: 49.33% | LR: 0.000090
Epoch: 032 | Train loss: 0.9912 | Train acc: 50.40% | Val loss: 1.0085 | Val acc: 49.32% | LR: 0.000090
Epoch: 033 | Train loss: 0.9828 | Train acc: 50.97% | Val loss: 1.0078 | Val acc: 49.32% | LR: 0.000089
Epoch: 034 | Train loss: 0.9843 | Train acc: 51.13% | Val loss: 1.0019 | Val acc: 49.47% | LR: 0.000088
Epoch: 035 | Train loss: 0.9893 | Train acc: 50.53% | Val loss: 0.9931 | Val acc: 49.96% | LR: 0.000087
Epoch: 036 | Train loss: 0.9827 | Train acc: 51.07% | Val loss: 1.0044 | Val acc: 49.32% | LR: 0.000087
Epoch: 037 | Train loss: 0.9878 | Train acc: 50.68% | Val loss: 1.0073 | Val acc: 49.17% | LR: 0.000086
Epoch: 038 | Train loss: 0.9899 | Train acc: 50.61% | Val loss: 1.0067 | Val acc: 49.21% | LR: 0.000085
Epoch: 039 | Train loss: 0.9836 | Train acc: 50.86% | Val loss: 1.0096 | Val acc: 49.23% | LR: 0.000084
Epoch: 040 | Train loss: 0.9818 | Train acc: 51.14% | Val loss: 1.0089 | Val acc: 49.27% | LR: 0.000084
Epoch: 041 | Train loss: 0.9759 | Train acc: 51.68% | Val loss: 1.0134 | Val acc: 49.03% | LR: 0.000083
Epoch: 042 | Train loss: 0.9837 | Train acc: 51.06% | Val loss: 1.0161 | Val acc: 48.97% | LR: 0.000082
Epoch: 043 | Train loss: 0.9811 | Train acc: 51.08% | Val loss: 1.0154 | Val acc: 49.01% | LR: 0.000081
Epoch: 044 | Train loss: 0.9880 | Train acc: 50.71% | Val loss: 1.0111 | Val acc: 49.24% | LR: 0.000080
Epoch: 045 | Train loss: 0.9767 | Train acc: 51.84% | Val loss: 1.0156 | Val acc: 48.95% | LR: 0.000080
Epoch: 046 | Train loss: 0.9826 | Train acc: 51.08% | Val loss: 1.0151 | Val acc: 48.87% | LR: 0.000079
Epoch: 047 | Train loss: 0.9819 | Train acc: 51.18% | Val loss: 1.0150 | Val acc: 48.91% | LR: 0.000078
Epoch: 048 | Train loss: 0.9842 | Train acc: 50.92% | Val loss: 1.0213 | Val acc: 48.24% | LR: 0.000077
Epoch: 049 | Train loss: 0.9868 | Train acc: 50.93% | Val loss: 1.0268 | Val acc: 47.97% | LR: 0.000076
Epoch: 050 | Train loss: 0.9871 | Train acc: 50.82% | Val loss: 1.0235 | Val acc: 48.28% | LR: 0.000075
Epoch: 051 | Train loss: 0.9849 | Train acc: 51.00% | Val loss: 1.0157 | Val acc: 48.74% | LR: 0.000074
Epoch: 052 | Train loss: 0.9826 | Train acc: 51.07% | Val loss: 1.0184 | Val acc: 48.44% | LR: 0.000073
Epoch: 053 | Train loss: 0.9782 | Train acc: 51.48% | Val loss: 1.0266 | Val acc: 48.19% | LR: 0.000072
Epoch: 054 | Train loss: 0.9843 | Train acc: 50.94% | Val loss: 1.0149 | Val acc: 48.84% | LR: 0.000071
Epoch: 055 | Train loss: 0.9823 | Train acc: 51.00% | Val loss: 1.0129 | Val acc: 48.92% | LR: 0.000070
Epoch: 056 | Train loss: 0.9840 | Train acc: 50.82% | Val loss: 1.0128 | Val acc: 48.94% | LR: 0.000069
Epoch: 057 | Train loss: 0.9818 | Train acc: 51.02% | Val loss: 1.0133 | Val acc: 48.91% | LR: 0.000068
Epoch: 058 | Train loss: 0.9799 | Train acc: 51.36% | Val loss: 1.0192 | Val acc: 48.53% | LR: 0.000067
Epoch: 059 | Train loss: 0.9854 | Train acc: 50.83% | Val loss: 1.0227 | Val acc: 48.67% | LR: 0.000066
Epoch: 060 | Train loss: 0.9788 | Train acc: 51.36% | Val loss: 1.0199 | Val acc: 48.55% | LR: 0.000065
Epoch: 061 | Train loss: 0.9763 | Train acc: 51.52% | Val loss: 1.0182 | Val acc: 48.53% | LR: 0.000064
Epoch: 062 | Train loss: 0.9832 | Train acc: 50.72% | Val loss: 1.0173 | Val acc: 48.63% | LR: 0.000063
Epoch: 063 | Train loss: 0.9881 | Train acc: 50.65% | Val loss: 1.0126 | Val acc: 48.83% | LR: 0.000062
Epoch: 064 | Train loss: 0.9835 | Train acc: 51.01% | Val loss: 1.0175 | Val acc: 48.71% | LR: 0.000061
Epoch: 065 | Train loss: 0.9834 | Train acc: 51.09% | Val loss: 1.0175 | Val acc: 48.69% | LR: 0.000060
Epoch: 066 | Train loss: 0.9795 | Train acc: 51.28% | Val loss: 1.0122 | Val acc: 49.01% | LR: 0.000059
Epoch: 067 | Train loss: 0.9784 | Train acc: 51.45% | Val loss: 1.0099 | Val acc: 49.14% | LR: 0.000058
Epoch: 068 | Train loss: 0.9797 | Train acc: 51.08% | Val loss: 1.0112 | Val acc: 49.25% | LR: 0.000057
Epoch: 069 | Train loss: 0.9792 | Train acc: 51.35% | Val loss: 1.0150 | Val acc: 48.81% | LR: 0.000056
Epoch: 070 | Train loss: 0.9832 | Train acc: 51.08% | Val loss: 1.0153 | Val acc: 48.77% | LR: 0.000055
Epoch: 071 | Train loss: 0.9826 | Train acc: 51.01% | Val loss: 1.0190 | Val acc: 48.90% | LR: 0.000054
Epoch: 072 | Train loss: 0.9815 | Train acc: 51.01% | Val loss: 1.0189 | Val acc: 48.92% | LR: 0.000053
Epoch: 073 | Train loss: 0.9849 | Train acc: 50.83% | Val loss: 1.0177 | Val acc: 49.00% | LR: 0.000052
Epoch: 074 | Train loss: 0.9813 | Train acc: 51.06% | Val loss: 1.0141 | Val acc: 49.07% | LR: 0.000051
Epoch: 075 | Train loss: 0.9758 | Train acc: 51.47% | Val loss: 1.0093 | Val acc: 49.16% | LR: 0.000050
Epoch: 076 | Train loss: 0.9754 | Train acc: 51.43% | Val loss: 1.0149 | Val acc: 49.24% | LR: 0.000049
Epoch: 077 | Train loss: 0.9836 | Train acc: 50.99% | Val loss: 1.0138 | Val acc: 49.09% | LR: 0.000048
Epoch: 078 | Train loss: 0.9808 | Train acc: 51.08% | Val loss: 1.0114 | Val acc: 49.37% | LR: 0.000047
Epoch: 079 | Train loss: 0.9797 | Train acc: 51.40% | Val loss: 1.0155 | Val acc: 49.40% | LR: 0.000046
Epoch: 080 | Train loss: 0.9839 | Train acc: 50.83% | Val loss: 1.0149 | Val acc: 49.22% | LR: 0.000045
Epoch: 081 | Train loss: 0.9801 | Train acc: 51.18% | Val loss: 1.0123 | Val acc: 49.40% | LR: 0.000044
Epoch: 082 | Train loss: 0.9796 | Train acc: 51.18% | Val loss: 1.0142 | Val acc: 49.57% | LR: 0.000043
Epoch: 083 | Train loss: 0.9847 | Train acc: 50.94% | Val loss: 1.0184 | Val acc: 49.29% | LR: 0.000042
Epoch: 084 | Train loss: 0.9875 | Train acc: 50.62% | Val loss: 1.0180 | Val acc: 49.21% | LR: 0.000041
Epoch: 085 | Train loss: 0.9735 | Train acc: 51.94% | Val loss: 1.0155 | Val acc: 49.38% | LR: 0.000040
Epoch: 086 | Train loss: 0.9836 | Train acc: 50.97% | Val loss: 1.0153 | Val acc: 49.20% | LR: 0.000039
Epoch: 087 | Train loss: 0.9760 | Train acc: 51.50% | Val loss: 1.0140 | Val acc: 49.20% | LR: 0.000038
Epoch: 088 | Train loss: 0.9827 | Train acc: 51.04% | Val loss: 1.0132 | Val acc: 49.34% | LR: 0.000037
Epoch: 089 | Train loss: 0.9797 | Train acc: 51.25% | Val loss: 1.0147 | Val acc: 49.06% | LR: 0.000036
Epoch: 090 | Train loss: 0.9761 | Train acc: 51.51% | Val loss: 1.0170 | Val acc: 48.96% | LR: 0.000035
Epoch: 091 | Train loss: 0.9784 | Train acc: 51.43% | Val loss: 1.0151 | Val acc: 49.00% | LR: 0.000034
Epoch: 092 | Train loss: 0.9827 | Train acc: 50.87% | Val loss: 1.0143 | Val acc: 49.06% | LR: 0.000033
Epoch: 093 | Train loss: 0.9817 | Train acc: 51.09% | Val loss: 1.0170 | Val acc: 48.70% | LR: 0.000032
Epoch: 094 | Train loss: 0.9779 | Train acc: 51.41% | Val loss: 1.0168 | Val acc: 48.76% | LR: 0.000031
Epoch: 095 | Train loss: 0.9792 | Train acc: 51.08% | Val loss: 1.0168 | Val acc: 48.76% | LR: 0.000030
Epoch: 096 | Train loss: 0.9877 | Train acc: 50.65% | Val loss: 1.0161 | Val acc: 48.72% | LR: 0.000029
Epoch: 097 | Train loss: 0.9858 | Train acc: 50.91% | Val loss: 1.0150 | Val acc: 48.86% | LR: 0.000028
Epoch: 098 | Train loss: 0.9815 | Train acc: 51.08% | Val loss: 1.0123 | Val acc: 49.34% | LR: 0.000027
Epoch: 099 | Train loss: 0.9841 | Train acc: 50.80% | Val loss: 1.0155 | Val acc: 48.88% | LR: 0.000026
Epoch: 100 | Train loss: 0.9765 | Train acc: 51.51% | Val loss: 1.0164 | Val acc: 48.92% | LR: 0.000025
Epoch: 101 | Train loss: 0.9797 | Train acc: 51.15% | Val loss: 1.0145 | Val acc: 49.06% | LR: 0.000024
Epoch: 102 | Train loss: 0.9781 | Train acc: 51.37% | Val loss: 1.0173 | Val acc: 48.80% | LR: 0.000023
Epoch: 103 | Train loss: 0.9844 | Train acc: 50.73% | Val loss: 1.0162 | Val acc: 48.72% | LR: 0.000022
Epoch: 104 | Train loss: 0.9837 | Train acc: 50.81% | Val loss: 1.0123 | Val acc: 49.04% | LR: 0.000022
Epoch: 105 | Train loss: 0.9805 | Train acc: 51.09% | Val loss: 1.0131 | Val acc: 48.96% | LR: 0.000021
Epoch: 106 | Train loss: 0.9861 | Train acc: 50.89% | Val loss: 1.0152 | Val acc: 48.92% | LR: 0.000020
Epoch: 107 | Train loss: 0.9799 | Train acc: 51.18% | Val loss: 1.0157 | Val acc: 48.78% | LR: 0.000019
Epoch: 108 | Train loss: 0.9835 | Train acc: 50.76% | Val loss: 1.0135 | Val acc: 49.00% | LR: 0.000018
Epoch: 109 | Train loss: 0.9804 | Train acc: 51.08% | Val loss: 1.0176 | Val acc: 48.67% | LR: 0.000018
Epoch: 110 | Train loss: 0.9820 | Train acc: 51.03% | Val loss: 1.0180 | Val acc: 48.60% | LR: 0.000017
Epoch: 111 | Train loss: 0.9819 | Train acc: 51.11% | Val loss: 1.0188 | Val acc: 48.60% | LR: 0.000016
Epoch: 112 | Train loss: 0.9822 | Train acc: 50.94% | Val loss: 1.0188 | Val acc: 48.43% | LR: 0.000015
Epoch: 113 | Train loss: 0.9784 | Train acc: 51.37% | Val loss: 1.0176 | Val acc: 48.65% | LR: 0.000015
Epoch: 114 | Train loss: 0.9852 | Train acc: 50.65% | Val loss: 1.0183 | Val acc: 48.41% | LR: 0.000014
Epoch: 115 | Train loss: 0.9851 | Train acc: 50.83% | Val loss: 1.0167 | Val acc: 48.72% | LR: 0.000013
Epoch: 116 | Train loss: 0.9810 | Train acc: 51.08% | Val loss: 1.0166 | Val acc: 48.82% | LR: 0.000012
Epoch: 117 | Train loss: 0.9782 | Train acc: 51.34% | Val loss: 1.0154 | Val acc: 49.00% | LR: 0.000012
Epoch: 118 | Train loss: 0.9840 | Train acc: 50.71% | Val loss: 1.0159 | Val acc: 48.92% | LR: 0.000011
Epoch: 119 | Train loss: 0.9786 | Train acc: 51.16% | Val loss: 1.0149 | Val acc: 49.04% | LR: 0.000011
Epoch: 120 | Train loss: 0.9767 | Train acc: 51.42% | Val loss: 1.0173 | Val acc: 48.88% | LR: 0.000010
Epoch: 121 | Train loss: 0.9759 | Train acc: 51.35% | Val loss: 1.0165 | Val acc: 48.88% | LR: 0.000009
Epoch: 122 | Train loss: 0.9740 | Train acc: 51.61% | Val loss: 1.0156 | Val acc: 49.00% | LR: 0.000009
Epoch: 123 | Train loss: 0.9774 | Train acc: 51.42% | Val loss: 1.0147 | Val acc: 49.10% | LR: 0.000008
Epoch: 124 | Train loss: 0.9827 | Train acc: 50.99% | Val loss: 1.0160 | Val acc: 48.94% | LR: 0.000008
Epoch: 125 | Train loss: 0.9754 | Train acc: 51.60% | Val loss: 1.0161 | Val acc: 48.92% | LR: 0.000007
Epoch: 126 | Train loss: 0.9776 | Train acc: 51.35% | Val loss: 1.0167 | Val acc: 48.84% | LR: 0.000007
Epoch: 127 | Train loss: 0.9754 | Train acc: 51.44% | Val loss: 1.0164 | Val acc: 48.88% | LR: 0.000006
Epoch: 128 | Train loss: 0.9778 | Train acc: 51.29% | Val loss: 1.0172 | Val acc: 48.84% | LR: 0.000006
Epoch: 129 | Train loss: 0.9749 | Train acc: 51.44% | Val loss: 1.0172 | Val acc: 48.84% | LR: 0.000005
Epoch: 130 | Train loss: 0.9776 | Train acc: 51.35% | Val loss: 1.0170 | Val acc: 48.84% | LR: 0.000005
Epoch: 131 | Train loss: 0.9821 | Train acc: 50.92% | Val loss: 1.0174 | Val acc: 48.84% | LR: 0.000005
Epoch: 132 | Train loss: 0.9801 | Train acc: 51.19% | Val loss: 1.0172 | Val acc: 48.84% | LR: 0.000004
Epoch: 133 | Train loss: 0.9826 | Train acc: 50.93% | Val loss: 1.0174 | Val acc: 48.84% | LR: 0.000004
Epoch: 134 | Train loss: 0.9812 | Train acc: 50.84% | Val loss: 1.0175 | Val acc: 48.86% | LR: 0.000003
Epoch: 135 | Train loss: 0.9830 | Train acc: 51.03% | Val loss: 1.0174 | Val acc: 48.84% | LR: 0.000003
Epoch: 136 | Train loss: 0.9807 | Train acc: 51.21% | Val loss: 1.0176 | Val acc: 48.86% | LR: 0.000003
Epoch: 137 | Train loss: 0.9705 | Train acc: 51.81% | Val loss: 1.0171 | Val acc: 48.84% | LR: 0.000003
Epoch: 138 | Train loss: 0.9692 | Train acc: 51.99% | Val loss: 1.0170 | Val acc: 48.84% | LR: 0.000002
Epoch: 139 | Train loss: 0.9729 | Train acc: 51.71% | Val loss: 1.0171 | Val acc: 48.84% | LR: 0.000002
Epoch: 140 | Train loss: 0.9790 | Train acc: 51.37% | Val loss: 1.0171 | Val acc: 48.84% | LR: 0.000002
Epoch: 141 | Train loss: 0.9759 | Train acc: 51.37% | Val loss: 1.0172 | Val acc: 48.84% | LR: 0.000002
Epoch: 142 | Train loss: 0.9841 | Train acc: 50.74% | Val loss: 1.0171 | Val acc: 48.84% | LR: 0.000002
Epoch: 143 | Train loss: 0.9751 | Train acc: 51.47% | Val loss: 1.0170 | Val acc: 48.84% | LR: 0.000001
Epoch: 144 | Train loss: 0.9762 | Train acc: 51.38% | Val loss: 1.0171 | Val acc: 48.84% | LR: 0.000001
Epoch: 145 | Train loss: 0.9716 | Train acc: 51.82% | Val loss: 1.0170 | Val acc: 48.84% | LR: 0.000001
Epoch: 146 | Train loss: 0.9772 | Train acc: 51.46% | Val loss: 1.0169 | Val acc: 48.84% | LR: 0.000001
Epoch: 147 | Train loss: 0.9746 | Train acc: 51.72% | Val loss: 1.0169 | Val acc: 48.84% | LR: 0.000001
Epoch: 148 | Train loss: 0.9752 | Train acc: 51.35% | Val loss: 1.0169 | Val acc: 48.84% | LR: 0.000001
Epoch: 149 | Train loss: 0.9787 | Train acc: 51.28% | Val loss: 1.0169 | Val acc: 48.84% | LR: 0.000001

[I 2025-09-23 01:44:54,673] Trial 4 finished with value: 0.5256418347358703 and parameters: {'lr': 0.00010101707974419627, 'hidden_size': 179, 'dropout': 0.22808099945390464, 'weight_decay': 0.2819901643839031}. Best is trial 2 with value: 0.5457171559333801.

Epoch: 000 | Train loss: 1.0792 | Train acc: 49.90% | Val loss: 0.9548 | Val acc: 54.05% | LR: 0.008014
Epoch: 001 | Train loss: 0.9965 | Train acc: 50.17% | Val loss: 0.9942 | Val acc: 51.82% | LR: 0.008012
Epoch: 002 | Train loss: 1.0000 | Train acc: 49.81% | Val loss: 0.9843 | Val acc: 51.61% | LR: 0.008007
Epoch: 003 | Train loss: 0.9898 | Train acc: 51.03% | Val loss: 0.9745 | Val acc: 52.02% | LR: 0.008001
Epoch: 004 | Train loss: 0.9966 | Train acc: 50.68% | Val loss: 1.0178 | Val acc: 49.60% | LR: 0.007993
Epoch: 005 | Train loss: 0.9925 | Train acc: 50.26% | Val loss: 0.9398 | Val acc: 54.57% | LR: 0.007984
Epoch: 006 | Train loss: 0.9929 | Train acc: 50.48% | Val loss: 0.9521 | Val acc: 54.30% | LR: 0.007972
Epoch: 007 | Train loss: 1.0127 | Train acc: 50.52% | Val loss: 1.0045 | Val acc: 50.54% | LR: 0.007959
Epoch: 008 | Train loss: 1.0410 | Train acc: 50.49% | Val loss: 0.9933 | Val acc: 53.73% | LR: 0.007944
Epoch: 009 | Train loss: 1.0186 | Train acc: 49.47% | Val loss: 0.9332 | Val acc: 54.05% | LR: 0.007928
Epoch: 010 | Train loss: 1.0906 | Train acc: 49.39% | Val loss: 0.9554 | Val acc: 54.05% | LR: 0.007909
Epoch: 011 | Train loss: 0.9968 | Train acc: 50.65% | Val loss: 0.9386 | Val acc: 54.13% | LR: 0.007889
Epoch: 012 | Train loss: 1.0126 | Train acc: 49.95% | Val loss: 14.2078 | Val acc: 55.06% | LR: 0.007868
Epoch: 013 | Train loss: 0.9965 | Train acc: 50.35% | Val loss: 0.9488 | Val acc: 54.05% | LR: 0.007844
Epoch: 014 | Train loss: 0.9968 | Train acc: 50.62% | Val loss: 0.9587 | Val acc: 54.05% | LR: 0.007819
Epoch: 015 | Train loss: 1.0065 | Train acc: 50.57% | Val loss: 1.0739 | Val acc: 45.95% | LR: 0.007792
Epoch: 016 | Train loss: 1.0265 | Train acc: 49.61% | Val loss: 0.9817 | Val acc: 53.50% | LR: 0.007764
Epoch: 017 | Train loss: 0.9948 | Train acc: 50.95% | Val loss: 1.0090 | Val acc: 47.32% | LR: 0.007734
Epoch: 018 | Train loss: 0.9976 | Train acc: 50.43% | Val loss: 0.9768 | Val acc: 54.36% | LR: 0.007702
Epoch: 019 | Train loss: 1.0033 | Train acc: 51.21% | Val loss: 1.0864 | Val acc: 45.95% | LR: 0.007669
Epoch: 020 | Train loss: 1.0010 | Train acc: 49.93% | Val loss: 1.0158 | Val acc: 48.79% | LR: 0.007634
Epoch: 021 | Train loss: 0.9950 | Train acc: 50.14% | Val loss: 0.9749 | Val acc: 50.62% | LR: 0.007597
Epoch: 022 | Train loss: 0.9963 | Train acc: 50.68% | Val loss: 1.0371 | Val acc: 47.27% | LR: 0.007559
Epoch: 023 | Train loss: 0.9904 | Train acc: 50.93% | Val loss: 0.9926 | Val acc: 48.48% | LR: 0.007520
Epoch: 024 | Train loss: 0.9900 | Train acc: 50.86% | Val loss: 1.0251 | Val acc: 47.64% | LR: 0.007478
Epoch: 025 | Train loss: 0.9936 | Train acc: 50.60% | Val loss: 1.0213 | Val acc: 47.81% | LR: 0.007436
Epoch: 026 | Train loss: 0.9972 | Train acc: 50.72% | Val loss: 1.0220 | Val acc: 47.58% | LR: 0.007391
Epoch: 027 | Train loss: 0.9941 | Train acc: 51.06% | Val loss: 1.0034 | Val acc: 49.98% | LR: 0.007346
Epoch: 028 | Train loss: 0.9895 | Train acc: 51.24% | Val loss: 1.0173 | Val acc: 48.15% | LR: 0.007299
Epoch: 029 | Train loss: 0.9972 | Train acc: 50.10% | Val loss: 1.0444 | Val acc: 46.48% | LR: 0.007250
Epoch: 030 | Train loss: 0.9968 | Train acc: 50.63% | Val loss: 1.0156 | Val acc: 48.01% | LR: 0.007200
Epoch: 031 | Train loss: 0.9901 | Train acc: 50.78% | Val loss: 1.0144 | Val acc: 48.21% | LR: 0.007148
Epoch: 032 | Train loss: 0.9930 | Train acc: 50.66% | Val loss: 0.9926 | Val acc: 51.33% | LR: 0.007096
Epoch: 033 | Train loss: 0.9979 | Train acc: 50.50% | Val loss: 1.0328 | Val acc: 46.13% | LR: 0.007041
Epoch: 034 | Train loss: 1.0027 | Train acc: 50.24% | Val loss: 0.9782 | Val acc: 49.34% | LR: 0.006986
Epoch: 035 | Train loss: 0.9976 | Train acc: 50.67% | Val loss: 0.9909 | Val acc: 54.27% | LR: 0.006929
Epoch: 036 | Train loss: 1.0216 | Train acc: 51.12% | Val loss: 0.9957 | Val acc: 50.98% | LR: 0.006871
Epoch: 037 | Train loss: 1.0096 | Train acc: 50.16% | Val loss: 1.0505 | Val acc: 49.15% | LR: 0.006812
Epoch: 038 | Train loss: 1.0006 | Train acc: 51.00% | Val loss: 0.9994 | Val acc: 49.74% | LR: 0.006751
Epoch: 039 | Train loss: 1.0085 | Train acc: 50.11% | Val loss: 1.0148 | Val acc: 50.70% | LR: 0.006689
Epoch: 040 | Train loss: 0.9943 | Train acc: 50.72% | Val loss: 0.9709 | Val acc: 53.73% | LR: 0.006626
Epoch: 041 | Train loss: 0.9942 | Train acc: 50.45% | Val loss: 0.9974 | Val acc: 50.83% | LR: 0.006562
Epoch: 042 | Train loss: 1.0035 | Train acc: 50.13% | Val loss: 0.9663 | Val acc: 54.34% | LR: 0.006497
Epoch: 043 | Train loss: 1.0016 | Train acc: 50.03% | Val loss: 0.9792 | Val acc: 52.34% | LR: 0.006431
Epoch: 044 | Train loss: 1.0005 | Train acc: 49.96% | Val loss: 1.0044 | Val acc: 49.59% | LR: 0.006363
Epoch: 045 | Train loss: 1.0045 | Train acc: 49.60% | Val loss: 1.0164 | Val acc: 47.60% | LR: 0.006295
Epoch: 046 | Train loss: 0.9955 | Train acc: 50.80% | Val loss: 1.0136 | Val acc: 49.19% | LR: 0.006226
Epoch: 047 | Train loss: 0.9931 | Train acc: 50.75% | Val loss: 0.9655 | Val acc: 54.51% | LR: 0.006155
Epoch: 048 | Train loss: 0.9928 | Train acc: 51.30% | Val loss: 1.0322 | Val acc: 47.53% | LR: 0.006084
Epoch: 049 | Train loss: 0.9926 | Train acc: 50.72% | Val loss: 0.9682 | Val acc: 54.13% | LR: 0.006012
Epoch: 050 | Train loss: 1.0322 | Train acc: 50.22% | Val loss: 0.9881 | Val acc: 52.59% | LR: 0.005939
Epoch: 051 | Train loss: 0.9929 | Train acc: 50.63% | Val loss: 0.9790 | Val acc: 53.62% | LR: 0.005865
Epoch: 052 | Train loss: 0.9963 | Train acc: 50.52% | Val loss: 0.9727 | Val acc: 52.84% | LR: 0.005790
Epoch: 053 | Train loss: 0.9934 | Train acc: 51.04% | Val loss: 0.9721 | Val acc: 52.94% | LR: 0.005714
Epoch: 054 | Train loss: 0.9994 | Train acc: 50.45% | Val loss: 0.9935 | Val acc: 51.26% | LR: 0.005638
Epoch: 055 | Train loss: 0.9944 | Train acc: 50.99% | Val loss: 1.0617 | Val acc: 45.93% | LR: 0.005561
Epoch: 056 | Train loss: 0.9951 | Train acc: 50.49% | Val loss: 1.0354 | Val acc: 46.33% | LR: 0.005483
Epoch: 057 | Train loss: 0.9894 | Train acc: 50.97% | Val loss: 1.0160 | Val acc: 48.11% | LR: 0.005405
Epoch: 058 | Train loss: 0.9948 | Train acc: 50.86% | Val loss: 1.0200 | Val acc: 49.06% | LR: 0.005326
Epoch: 059 | Train loss: 0.9912 | Train acc: 51.07% | Val loss: 0.9869 | Val acc: 52.43% | LR: 0.005246
Epoch: 060 | Train loss: 0.9899 | Train acc: 51.06% | Val loss: 0.9391 | Val acc: 53.73% | LR: 0.005166
Epoch: 061 | Train loss: 0.9937 | Train acc: 50.70% | Val loss: 1.0052 | Val acc: 49.15% | LR: 0.005086
Epoch: 062 | Train loss: 0.9877 | Train acc: 51.40% | Val loss: 0.9752 | Val acc: 53.37% | LR: 0.005005
Epoch: 063 | Train loss: 0.9935 | Train acc: 50.55% | Val loss: 0.9644 | Val acc: 53.50% | LR: 0.004923
Epoch: 064 | Train loss: 0.9916 | Train acc: 51.00% | Val loss: 1.0031 | Val acc: 49.66% | LR: 0.004841
Epoch: 065 | Train loss: 0.9847 | Train acc: 51.02% | Val loss: 0.9957 | Val acc: 50.27% | LR: 0.004759
Epoch: 066 | Train loss: 0.9915 | Train acc: 50.90% | Val loss: 0.9894 | Val acc: 50.25% | LR: 0.004676
Epoch: 067 | Train loss: 0.9929 | Train acc: 50.79% | Val loss: 0.9923 | Val acc: 50.63% | LR: 0.004593
Epoch: 068 | Train loss: 0.9889 | Train acc: 50.40% | Val loss: 0.9578 | Val acc: 52.83% | LR: 0.004510
Epoch: 069 | Train loss: 0.9900 | Train acc: 51.11% | Val loss: 0.9860 | Val acc: 50.72% | LR: 0.004427
Epoch: 070 | Train loss: 0.9959 | Train acc: 50.34% | Val loss: 0.9995 | Val acc: 50.55% | LR: 0.004343
Epoch: 071 | Train loss: 0.9830 | Train acc: 51.23% | Val loss: 0.9570 | Val acc: 53.87% | LR: 0.004260
Epoch: 072 | Train loss: 1.0048 | Train acc: 50.80% | Val loss: 0.9920 | Val acc: 51.04% | LR: 0.004176
Epoch: 073 | Train loss: 0.9928 | Train acc: 50.40% | Val loss: 0.9900 | Val acc: 50.96% | LR: 0.004092
Epoch: 074 | Train loss: 0.9881 | Train acc: 51.20% | Val loss: 1.0009 | Val acc: 49.82% | LR: 0.004008
Epoch: 075 | Train loss: 0.9865 | Train acc: 51.23% | Val loss: 0.9843 | Val acc: 51.49% | LR: 0.003924
Epoch: 076 | Train loss: 0.9793 | Train acc: 51.84% | Val loss: 1.0031 | Val acc: 49.33% | LR: 0.003840
Epoch: 077 | Train loss: 0.9873 | Train acc: 50.90% | Val loss: 0.9904 | Val acc: 50.47% | LR: 0.003757
Epoch: 078 | Train loss: 0.9924 | Train acc: 50.75% | Val loss: 0.9813 | Val acc: 51.33% | LR: 0.003673
Epoch: 079 | Train loss: 0.9924 | Train acc: 50.45% | Val loss: 0.9716 | Val acc: 51.55% | LR: 0.003589
Epoch: 080 | Train loss: 0.9868 | Train acc: 51.20% | Val loss: 0.9644 | Val acc: 51.92% | LR: 0.003506
Epoch: 081 | Train loss: 0.9977 | Train acc: 50.65% | Val loss: 0.9661 | Val acc: 51.68% | LR: 0.003423
Epoch: 082 | Train loss: 0.9905 | Train acc: 50.35% | Val loss: 0.9692 | Val acc: 52.75% | LR: 0.003340
Epoch: 083 | Train loss: 0.9835 | Train acc: 51.28% | Val loss: 1.0123 | Val acc: 48.64% | LR: 0.003257
Epoch: 084 | Train loss: 0.9888 | Train acc: 50.88% | Val loss: 0.9814 | Val acc: 50.51% | LR: 0.003175
Epoch: 085 | Train loss: 0.9843 | Train acc: 51.04% | Val loss: 0.9760 | Val acc: 51.17% | LR: 0.003093
Epoch: 086 | Train loss: 0.9834 | Train acc: 51.44% | Val loss: 1.0291 | Val acc: 48.68% | LR: 0.003012
Epoch: 087 | Train loss: 0.9866 | Train acc: 50.71% | Val loss: 1.0110 | Val acc: 49.52% | LR: 0.002931
Epoch: 088 | Train loss: 1.0012 | Train acc: 50.29% | Val loss: 0.9754 | Val acc: 50.80% | LR: 0.002850
Epoch: 089 | Train loss: 0.9834 | Train acc: 51.25% | Val loss: 1.0715 | Val acc: 48.39% | LR: 0.002770
Epoch: 090 | Train loss: 0.9835 | Train acc: 51.32% | Val loss: 1.0378 | Val acc: 49.08% | LR: 0.002690
Epoch: 091 | Train loss: 0.9877 | Train acc: 50.83% | Val loss: 1.0389 | Val acc: 49.08% | LR: 0.002611
Epoch: 092 | Train loss: 0.9886 | Train acc: 51.08% | Val loss: 1.0071 | Val acc: 49.56% | LR: 0.002533
Epoch: 093 | Train loss: 0.9861 | Train acc: 51.18% | Val loss: 1.0256 | Val acc: 49.42% | LR: 0.002455
Epoch: 094 | Train loss: 0.9870 | Train acc: 51.13% | Val loss: 1.0076 | Val acc: 49.22% | LR: 0.002378
Epoch: 095 | Train loss: 0.9849 | Train acc: 51.27% | Val loss: 0.9969 | Val acc: 49.27% | LR: 0.002302
Epoch: 096 | Train loss: 0.9891 | Train acc: 50.77% | Val loss: 0.9904 | Val acc: 49.33% | LR: 0.002226
Epoch: 097 | Train loss: 0.9879 | Train acc: 51.15% | Val loss: 1.0149 | Val acc: 49.22% | LR: 0.002152
Epoch: 098 | Train loss: 0.9823 | Train acc: 51.36% | Val loss: 1.0003 | Val acc: 49.34% | LR: 0.002078
Epoch: 099 | Train loss: 0.9861 | Train acc: 50.96% | Val loss: 1.0029 | Val acc: 49.49% | LR: 0.002005
Epoch: 100 | Train loss: 0.9877 | Train acc: 50.80% | Val loss: 0.9912 | Val acc: 51.16% | LR: 0.001932
Epoch: 101 | Train loss: 0.9895 | Train acc: 50.76% | Val loss: 0.9445 | Val acc: 53.64% | LR: 0.001861
Epoch: 102 | Train loss: 0.9811 | Train acc: 51.34% | Val loss: 0.9476 | Val acc: 53.62% | LR: 0.001791
Epoch: 103 | Train loss: 0.9935 | Train acc: 50.52% | Val loss: 0.9765 | Val acc: 52.42% | LR: 0.001721
Epoch: 104 | Train loss: 0.9910 | Train acc: 50.71% | Val loss: 0.9553 | Val acc: 52.77% | LR: 0.001653
Epoch: 105 | Train loss: 0.9951 | Train acc: 50.55% | Val loss: 0.9690 | Val acc: 52.75% | LR: 0.001585
Epoch: 106 | Train loss: 0.9887 | Train acc: 51.37% | Val loss: 0.9875 | Val acc: 52.56% | LR: 0.001519
Epoch: 107 | Train loss: 0.9901 | Train acc: 50.48% | Val loss: 0.9512 | Val acc: 52.70% | LR: 0.001454
Epoch: 108 | Train loss: 0.9870 | Train acc: 51.02% | Val loss: 0.9723 | Val acc: 52.41% | LR: 0.001390
Epoch: 109 | Train loss: 0.9876 | Train acc: 50.92% | Val loss: 0.9639 | Val acc: 53.18% | LR: 0.001327
Epoch: 110 | Train loss: 0.9824 | Train acc: 51.19% | Val loss: 0.9478 | Val acc: 53.34% | LR: 0.001265
Epoch: 111 | Train loss: 0.9845 | Train acc: 51.00% | Val loss: 0.9478 | Val acc: 53.04% | LR: 0.001204
Epoch: 112 | Train loss: 0.9886 | Train acc: 50.85% | Val loss: 0.9514 | Val acc: 53.08% | LR: 0.001145
Epoch: 113 | Train loss: 0.9837 | Train acc: 51.19% | Val loss: 0.9442 | Val acc: 53.17% | LR: 0.001087
Epoch: 114 | Train loss: 0.9899 | Train acc: 50.72% | Val loss: 0.9459 | Val acc: 53.42% | LR: 0.001030
Epoch: 115 | Train loss: 0.9812 | Train acc: 51.26% | Val loss: 0.9544 | Val acc: 52.89% | LR: 0.000975
Epoch: 116 | Train loss: 0.9810 | Train acc: 51.29% | Val loss: 0.9594 | Val acc: 52.69% | LR: 0.000921
Epoch: 117 | Train loss: 0.9849 | Train acc: 50.95% | Val loss: 0.9488 | Val acc: 53.08% | LR: 0.000868
Epoch: 118 | Train loss: 0.9858 | Train acc: 50.75% | Val loss: 0.9485 | Val acc: 53.12% | LR: 0.000816
Epoch: 119 | Train loss: 0.9865 | Train acc: 50.86% | Val loss: 0.9511 | Val acc: 52.92% | LR: 0.000766
Epoch: 120 | Train loss: 0.9856 | Train acc: 50.98% | Val loss: 0.9578 | Val acc: 52.65% | LR: 0.000718
Epoch: 121 | Train loss: 0.9793 | Train acc: 51.32% | Val loss: 0.9563 | Val acc: 52.66% | LR: 0.000671
Epoch: 122 | Train loss: 0.9798 | Train acc: 51.22% | Val loss: 0.9629 | Val acc: 52.67% | LR: 0.000625
Epoch: 123 | Train loss: 0.9792 | Train acc: 51.14% | Val loss: 0.9572 | Val acc: 52.67% | LR: 0.000581
Epoch: 124 | Train loss: 0.9875 | Train acc: 50.70% | Val loss: 0.9566 | Val acc: 52.51% | LR: 0.000538
Epoch: 125 | Train loss: 0.9898 | Train acc: 50.61% | Val loss: 0.9608 | Val acc: 52.67% | LR: 0.000497
Epoch: 126 | Train loss: 0.9864 | Train acc: 50.80% | Val loss: 0.9562 | Val acc: 52.65% | LR: 0.000457
Epoch: 127 | Train loss: 0.9773 | Train acc: 51.41% | Val loss: 0.9585 | Val acc: 52.71% | LR: 0.000419
Epoch: 128 | Train loss: 0.9785 | Train acc: 51.29% | Val loss: 0.9522 | Val acc: 52.93% | LR: 0.000382
Epoch: 129 | Train loss: 0.9785 | Train acc: 51.27% | Val loss: 0.9540 | Val acc: 53.03% | LR: 0.000347
Epoch: 130 | Train loss: 0.9823 | Train acc: 51.14% | Val loss: 0.9520 | Val acc: 52.85% | LR: 0.000314
Epoch: 131 | Train loss: 0.9789 | Train acc: 51.23% | Val loss: 0.9541 | Val acc: 52.89% | LR: 0.000282
Epoch: 132 | Train loss: 0.9849 | Train acc: 50.78% | Val loss: 0.9531 | Val acc: 52.95% | LR: 0.000252
Epoch: 133 | Train loss: 0.9719 | Train acc: 51.75% | Val loss: 0.9537 | Val acc: 52.99% | LR: 0.000224
Epoch: 134 | Train loss: 0.9849 | Train acc: 50.79% | Val loss: 0.9548 | Val acc: 52.85% | LR: 0.000197
Epoch: 135 | Train loss: 0.9747 | Train acc: 51.60% | Val loss: 0.9545 | Val acc: 52.85% | LR: 0.000172
Epoch: 136 | Train loss: 0.9749 | Train acc: 51.60% | Val loss: 0.9543 | Val acc: 52.85% | LR: 0.000149
Epoch: 137 | Train loss: 0.9901 | Train acc: 50.54% | Val loss: 0.9533 | Val acc: 52.93% | LR: 0.000127
Epoch: 138 | Train loss: 0.9797 | Train acc: 51.24% | Val loss: 0.9524 | Val acc: 52.93% | LR: 0.000107
Epoch: 139 | Train loss: 0.9761 | Train acc: 51.42% | Val loss: 0.9539 | Val acc: 52.95% | LR: 0.000089
Epoch: 140 | Train loss: 0.9741 | Train acc: 51.60% | Val loss: 0.9530 | Val acc: 52.95% | LR: 0.000072
Epoch: 141 | Train loss: 0.9793 | Train acc: 51.24% | Val loss: 0.9533 | Val acc: 52.95% | LR: 0.000057
Epoch: 142 | Train loss: 0.9845 | Train acc: 50.89% | Val loss: 0.9535 | Val acc: 52.91% | LR: 0.000044
Epoch: 143 | Train loss: 0.9762 | Train acc: 51.51% | Val loss: 0.9530 | Val acc: 52.95% | LR: 0.000033
Epoch: 144 | Train loss: 0.9817 | Train acc: 51.07% | Val loss: 0.9530 | Val acc: 52.95% | LR: 0.000023
Epoch: 145 | Train loss: 0.9785 | Train acc: 51.24% | Val loss: 0.9529 | Val acc: 52.95% | LR: 0.000015
Epoch: 146 | Train loss: 0.9682 | Train acc: 51.86% | Val loss: 0.9529 | Val acc: 52.95% | LR: 0.000009
Epoch: 147 | Train loss: 0.9774 | Train acc: 51.33% | Val loss: 0.9529 | Val acc: 52.95% | LR: 0.000005
Epoch: 148 | Train loss: 0.9868 | Train acc: 50.63% | Val loss: 0.9529 | Val acc: 52.95% | LR: 0.000002
Epoch: 149 | Train loss: 0.9797 | Train acc: 51.33% | Val loss: 0.9529 | Val acc: 52.95% | LR: 0.000001

[I 2025-09-23 01:48:06,320] Trial 5 finished with value: 0.5506223201751709 and parameters: {'lr': 0.008015237423051982, 'hidden_size': 142, 'dropout': 0.19667522860961106, 'weight_decay': 0.27048935338647373}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.2658 | Train acc: 50.25% | Val loss: 0.9987 | Val acc: 53.01% | LR: 0.002914
Epoch: 001 | Train loss: 1.0048 | Train acc: 49.55% | Val loss: 0.9956 | Val acc: 54.26% | LR: 0.002913
Epoch: 002 | Train loss: 1.0041 | Train acc: 49.65% | Val loss: 0.9981 | Val acc: 50.66% | LR: 0.002911
Epoch: 003 | Train loss: 0.9980 | Train acc: 50.65% | Val loss: 0.9991 | Val acc: 49.86% | LR: 0.002909
Epoch: 004 | Train loss: 0.9977 | Train acc: 50.36% | Val loss: 0.9972 | Val acc: 49.70% | LR: 0.002906
Epoch: 005 | Train loss: 1.0011 | Train acc: 50.32% | Val loss: 0.9785 | Val acc: 52.44% | LR: 0.002903
Epoch: 006 | Train loss: 1.6443 | Train acc: 50.78% | Val loss: 0.9941 | Val acc: 51.38% | LR: 0.002898
Epoch: 007 | Train loss: 1.0303 | Train acc: 49.79% | Val loss: 1.0166 | Val acc: 51.10% | LR: 0.002894
Epoch: 008 | Train loss: 0.9964 | Train acc: 50.41% | Val loss: 1.0079 | Val acc: 51.44% | LR: 0.002888
Epoch: 009 | Train loss: 1.0087 | Train acc: 50.77% | Val loss: 0.9904 | Val acc: 53.18% | LR: 0.002882
Epoch: 010 | Train loss: 1.0076 | Train acc: 50.31% | Val loss: 0.9926 | Val acc: 52.31% | LR: 0.002876
Epoch: 011 | Train loss: 1.0028 | Train acc: 49.98% | Val loss: 1.0017 | Val acc: 51.42% | LR: 0.002868
Epoch: 012 | Train loss: 0.9985 | Train acc: 49.92% | Val loss: 0.9816 | Val acc: 53.69% | LR: 0.002860
Epoch: 013 | Train loss: 0.9964 | Train acc: 50.72% | Val loss: 0.9783 | Val acc: 54.10% | LR: 0.002852
Epoch: 014 | Train loss: 1.0015 | Train acc: 50.60% | Val loss: 0.9874 | Val acc: 53.69% | LR: 0.002843
Epoch: 015 | Train loss: 1.0009 | Train acc: 50.17% | Val loss: 0.9891 | Val acc: 53.05% | LR: 0.002833
Epoch: 016 | Train loss: 0.9944 | Train acc: 50.70% | Val loss: 0.9905 | Val acc: 52.83% | LR: 0.002823
Epoch: 017 | Train loss: 0.9944 | Train acc: 50.59% | Val loss: 0.9834 | Val acc: 53.19% | LR: 0.002812
Epoch: 018 | Train loss: 0.9959 | Train acc: 50.66% | Val loss: 0.9784 | Val acc: 53.41% | LR: 0.002800
Epoch: 019 | Train loss: 1.0021 | Train acc: 50.56% | Val loss: 0.9889 | Val acc: 53.16% | LR: 0.002788
Epoch: 020 | Train loss: 0.9904 | Train acc: 51.26% | Val loss: 0.9811 | Val acc: 53.56% | LR: 0.002775
Epoch: 021 | Train loss: 0.9935 | Train acc: 50.96% | Val loss: 1.0600 | Val acc: 53.13% | LR: 0.002762
Epoch: 022 | Train loss: 0.9971 | Train acc: 50.83% | Val loss: 1.0005 | Val acc: 51.97% | LR: 0.002748
Epoch: 023 | Train loss: 0.9938 | Train acc: 50.65% | Val loss: 0.9879 | Val acc: 52.51% | LR: 0.002734
Epoch: 024 | Train loss: 0.9940 | Train acc: 50.91% | Val loss: 0.9877 | Val acc: 53.50% | LR: 0.002719
Epoch: 025 | Train loss: 0.9903 | Train acc: 50.72% | Val loss: 0.9908 | Val acc: 53.52% | LR: 0.002703
Epoch: 026 | Train loss: 0.9917 | Train acc: 50.82% | Val loss: 0.9906 | Val acc: 53.18% | LR: 0.002687
Epoch: 027 | Train loss: 0.9951 | Train acc: 50.34% | Val loss: 0.9970 | Val acc: 51.92% | LR: 0.002671
Epoch: 028 | Train loss: 0.9966 | Train acc: 50.58% | Val loss: 0.9886 | Val acc: 54.20% | LR: 0.002654
Epoch: 029 | Train loss: 0.9918 | Train acc: 51.16% | Val loss: 0.9993 | Val acc: 51.17% | LR: 0.002636
Epoch: 030 | Train loss: 0.9941 | Train acc: 50.69% | Val loss: 1.0000 | Val acc: 51.75% | LR: 0.002618
Epoch: 031 | Train loss: 0.9897 | Train acc: 51.26% | Val loss: 1.0027 | Val acc: 50.75% | LR: 0.002599
Epoch: 032 | Train loss: 0.9999 | Train acc: 50.03% | Val loss: 1.0031 | Val acc: 50.66% | LR: 0.002580
Epoch: 033 | Train loss: 0.9967 | Train acc: 50.43% | Val loss: 1.0710 | Val acc: 52.43% | LR: 0.002560
Epoch: 034 | Train loss: 0.9932 | Train acc: 50.99% | Val loss: 0.9851 | Val acc: 53.81% | LR: 0.002540
Epoch: 035 | Train loss: 0.9958 | Train acc: 50.41% | Val loss: 0.9795 | Val acc: 54.27% | LR: 0.002519
Epoch: 036 | Train loss: 0.9896 | Train acc: 51.66% | Val loss: 0.9843 | Val acc: 53.98% | LR: 0.002498
Epoch: 037 | Train loss: 0.9939 | Train acc: 50.77% | Val loss: 0.9853 | Val acc: 53.88% | LR: 0.002477
Epoch: 038 | Train loss: 0.9942 | Train acc: 50.75% | Val loss: 0.9857 | Val acc: 53.18% | LR: 0.002455
Epoch: 039 | Train loss: 0.9942 | Train acc: 50.73% | Val loss: 0.9944 | Val acc: 50.65% | LR: 0.002432
Epoch: 040 | Train loss: 1.0007 | Train acc: 50.25% | Val loss: 0.9931 | Val acc: 51.23% | LR: 0.002409
Epoch: 041 | Train loss: 0.9985 | Train acc: 50.17% | Val loss: 0.9818 | Val acc: 53.39% | LR: 0.002386
Epoch: 042 | Train loss: 0.9966 | Train acc: 50.77% | Val loss: 0.9901 | Val acc: 51.67% | LR: 0.002362
Epoch: 043 | Train loss: 0.9937 | Train acc: 51.00% | Val loss: 0.9924 | Val acc: 51.00% | LR: 0.002338
Epoch: 044 | Train loss: 0.9903 | Train acc: 51.12% | Val loss: 1.0062 | Val acc: 48.64% | LR: 0.002314
Epoch: 045 | Train loss: 0.9949 | Train acc: 50.78% | Val loss: 1.0076 | Val acc: 48.54% | LR: 0.002289
Epoch: 046 | Train loss: 0.9971 | Train acc: 50.44% | Val loss: 1.0132 | Val acc: 47.76% | LR: 0.002264
Epoch: 047 | Train loss: 1.4045 | Train acc: 50.23% | Val loss: 1.0059 | Val acc: 49.65% | LR: 0.002238
Epoch: 048 | Train loss: 1.4864 | Train acc: 50.96% | Val loss: 1.0055 | Val acc: 50.08% | LR: 0.002212
Epoch: 049 | Train loss: 1.2867 | Train acc: 50.56% | Val loss: 1.0130 | Val acc: 46.95% | LR: 0.002186
Epoch: 050 | Train loss: 1.0287 | Train acc: 50.25% | Val loss: 1.0048 | Val acc: 49.49% | LR: 0.002159
Epoch: 051 | Train loss: 0.9902 | Train acc: 50.72% | Val loss: 1.0084 | Val acc: 48.50% | LR: 0.002132
Epoch: 052 | Train loss: 0.9896 | Train acc: 51.34% | Val loss: 1.0080 | Val acc: 49.38% | LR: 0.002105
Epoch: 053 | Train loss: 1.0006 | Train acc: 49.97% | Val loss: 1.0113 | Val acc: 48.39% | LR: 0.002078
Epoch: 054 | Train loss: 0.9908 | Train acc: 50.86% | Val loss: 1.0178 | Val acc: 45.83% | LR: 0.002050
Epoch: 055 | Train loss: 1.0033 | Train acc: 50.34% | Val loss: 1.0249 | Val acc: 45.95% | LR: 0.002022
Epoch: 056 | Train loss: 0.9928 | Train acc: 50.43% | Val loss: 1.0101 | Val acc: 47.09% | LR: 0.001994
Epoch: 057 | Train loss: 0.9900 | Train acc: 50.30% | Val loss: 1.0091 | Val acc: 47.39% | LR: 0.001965
Epoch: 058 | Train loss: 0.9932 | Train acc: 51.01% | Val loss: 1.0077 | Val acc: 47.93% | LR: 0.001937
Epoch: 059 | Train loss: 0.9909 | Train acc: 50.82% | Val loss: 1.0025 | Val acc: 49.36% | LR: 0.001908
Epoch: 060 | Train loss: 0.9921 | Train acc: 50.86% | Val loss: 1.0098 | Val acc: 48.31% | LR: 0.001878
Epoch: 061 | Train loss: 0.9928 | Train acc: 50.63% | Val loss: 1.0109 | Val acc: 48.21% | LR: 0.001849
Epoch: 062 | Train loss: 0.9923 | Train acc: 50.65% | Val loss: 1.0057 | Val acc: 49.40% | LR: 0.001820
Epoch: 063 | Train loss: 0.9880 | Train acc: 50.71% | Val loss: 1.0035 | Val acc: 49.38% | LR: 0.001790
Epoch: 064 | Train loss: 0.9909 | Train acc: 50.65% | Val loss: 1.0083 | Val acc: 48.27% | LR: 0.001760
Epoch: 065 | Train loss: 0.9864 | Train acc: 51.05% | Val loss: 1.0082 | Val acc: 48.10% | LR: 0.001730
Epoch: 066 | Train loss: 0.9898 | Train acc: 50.70% | Val loss: 1.0175 | Val acc: 46.56% | LR: 0.001700
Epoch: 067 | Train loss: 1.0039 | Train acc: 49.61% | Val loss: 1.0189 | Val acc: 47.62% | LR: 0.001670
Epoch: 068 | Train loss: 0.9956 | Train acc: 50.36% | Val loss: 1.0164 | Val acc: 47.72% | LR: 0.001640
Epoch: 069 | Train loss: 0.9904 | Train acc: 50.73% | Val loss: 1.0136 | Val acc: 48.09% | LR: 0.001610
Epoch: 070 | Train loss: 0.9947 | Train acc: 50.38% | Val loss: 1.0191 | Val acc: 47.34% | LR: 0.001579
Epoch: 071 | Train loss: 0.9976 | Train acc: 50.26% | Val loss: 1.0159 | Val acc: 47.91% | LR: 0.001549
Epoch: 072 | Train loss: 0.9932 | Train acc: 50.43% | Val loss: 1.0127 | Val acc: 47.93% | LR: 0.001519
Epoch: 073 | Train loss: 0.9868 | Train acc: 51.38% | Val loss: 1.0168 | Val acc: 46.54% | LR: 0.001488
Epoch: 074 | Train loss: 0.9894 | Train acc: 51.01% | Val loss: 1.0204 | Val acc: 45.93% | LR: 0.001458
Epoch: 075 | Train loss: 0.9908 | Train acc: 50.92% | Val loss: 1.0179 | Val acc: 45.85% | LR: 0.001427
Epoch: 076 | Train loss: 0.9856 | Train acc: 51.04% | Val loss: 1.0152 | Val acc: 47.87% | LR: 0.001397
Epoch: 077 | Train loss: 0.9918 | Train acc: 50.76% | Val loss: 1.0153 | Val acc: 48.03% | LR: 0.001366
Epoch: 078 | Train loss: 0.9881 | Train acc: 50.82% | Val loss: 1.0119 | Val acc: 48.23% | LR: 0.001336
Epoch: 079 | Train loss: 0.9910 | Train acc: 50.84% | Val loss: 1.0134 | Val acc: 48.09% | LR: 0.001305
Epoch: 080 | Train loss: 0.9830 | Train acc: 51.12% | Val loss: 1.0186 | Val acc: 47.60% | LR: 0.001275
Epoch: 081 | Train loss: 0.9889 | Train acc: 51.04% | Val loss: 1.0169 | Val acc: 47.54% | LR: 0.001245
Epoch: 082 | Train loss: 0.9927 | Train acc: 50.56% | Val loss: 1.0256 | Val acc: 46.05% | LR: 0.001215
Epoch: 083 | Train loss: 0.9934 | Train acc: 50.65% | Val loss: 1.0270 | Val acc: 46.15% | LR: 0.001185
Epoch: 084 | Train loss: 0.9876 | Train acc: 50.97% | Val loss: 1.0258 | Val acc: 45.89% | LR: 0.001155
Epoch: 085 | Train loss: 0.9863 | Train acc: 51.05% | Val loss: 1.0230 | Val acc: 46.91% | LR: 0.001125
Epoch: 086 | Train loss: 0.9933 | Train acc: 50.49% | Val loss: 1.0278 | Val acc: 45.97% | LR: 0.001095
Epoch: 087 | Train loss: 0.9954 | Train acc: 50.43% | Val loss: 1.0218 | Val acc: 47.34% | LR: 0.001066
Epoch: 088 | Train loss: 0.9918 | Train acc: 50.52% | Val loss: 1.0256 | Val acc: 46.03% | LR: 0.001037
Epoch: 089 | Train loss: 0.9900 | Train acc: 50.90% | Val loss: 1.0258 | Val acc: 46.64% | LR: 0.001007
Epoch: 090 | Train loss: 0.9905 | Train acc: 50.71% | Val loss: 1.0291 | Val acc: 45.85% | LR: 0.000979
Epoch: 091 | Train loss: 0.9840 | Train acc: 51.26% | Val loss: 1.0294 | Val acc: 46.05% | LR: 0.000950
Epoch: 092 | Train loss: 0.9908 | Train acc: 50.63% | Val loss: 1.0334 | Val acc: 45.93% | LR: 0.000921
Epoch: 093 | Train loss: 0.9936 | Train acc: 50.44% | Val loss: 1.0295 | Val acc: 46.05% | LR: 0.000893
Epoch: 094 | Train loss: 0.9872 | Train acc: 51.05% | Val loss: 1.0277 | Val acc: 46.30% | LR: 0.000865
Epoch: 095 | Train loss: 0.9962 | Train acc: 50.28% | Val loss: 1.0293 | Val acc: 46.13% | LR: 0.000837
Epoch: 096 | Train loss: 0.9866 | Train acc: 50.97% | Val loss: 1.0272 | Val acc: 46.32% | LR: 0.000810
Epoch: 097 | Train loss: 0.9939 | Train acc: 50.45% | Val loss: 1.0281 | Val acc: 45.95% | LR: 0.000783
Epoch: 098 | Train loss: 0.9937 | Train acc: 50.46% | Val loss: 1.0255 | Val acc: 46.34% | LR: 0.000756
Epoch: 099 | Train loss: 0.9856 | Train acc: 51.02% | Val loss: 1.0211 | Val acc: 47.01% | LR: 0.000729
Epoch: 100 | Train loss: 0.9967 | Train acc: 50.26% | Val loss: 1.0220 | Val acc: 46.71% | LR: 0.000703
Epoch: 101 | Train loss: 0.9819 | Train acc: 51.38% | Val loss: 1.0235 | Val acc: 46.62% | LR: 0.000677
Epoch: 102 | Train loss: 0.9887 | Train acc: 50.86% | Val loss: 1.0287 | Val acc: 46.30% | LR: 0.000651
Epoch: 103 | Train loss: 0.9799 | Train acc: 51.48% | Val loss: 1.0260 | Val acc: 46.75% | LR: 0.000626
Epoch: 104 | Train loss: 0.9910 | Train acc: 50.69% | Val loss: 1.0251 | Val acc: 47.23% | LR: 0.000601
Epoch: 105 | Train loss: 0.9932 | Train acc: 50.60% | Val loss: 1.0262 | Val acc: 46.36% | LR: 0.000577
Epoch: 106 | Train loss: 0.9888 | Train acc: 50.71% | Val loss: 1.0242 | Val acc: 47.05% | LR: 0.000553
Epoch: 107 | Train loss: 0.9852 | Train acc: 51.12% | Val loss: 1.0258 | Val acc: 46.77% | LR: 0.000529
Epoch: 108 | Train loss: 0.9991 | Train acc: 50.17% | Val loss: 1.0269 | Val acc: 46.69% | LR: 0.000506
Epoch: 109 | Train loss: 0.9862 | Train acc: 50.93% | Val loss: 1.0219 | Val acc: 47.36% | LR: 0.000483
Epoch: 110 | Train loss: 0.9828 | Train acc: 51.18% | Val loss: 1.0239 | Val acc: 47.05% | LR: 0.000460
Epoch: 111 | Train loss: 0.9900 | Train acc: 50.83% | Val loss: 1.0261 | Val acc: 46.34% | LR: 0.000438
Epoch: 112 | Train loss: 0.9850 | Train acc: 51.04% | Val loss: 1.0230 | Val acc: 46.89% | LR: 0.000417
Epoch: 113 | Train loss: 0.9870 | Train acc: 50.85% | Val loss: 1.0249 | Val acc: 46.63% | LR: 0.000396
Epoch: 114 | Train loss: 0.9840 | Train acc: 51.07% | Val loss: 1.0240 | Val acc: 46.87% | LR: 0.000375
Epoch: 115 | Train loss: 0.9824 | Train acc: 51.20% | Val loss: 1.0243 | Val acc: 46.67% | LR: 0.000355
Epoch: 116 | Train loss: 0.9853 | Train acc: 50.99% | Val loss: 1.0247 | Val acc: 46.73% | LR: 0.000335
Epoch: 117 | Train loss: 0.9896 | Train acc: 50.74% | Val loss: 1.0255 | Val acc: 46.73% | LR: 0.000316
Epoch: 118 | Train loss: 0.9889 | Train acc: 50.80% | Val loss: 1.0254 | Val acc: 46.69% | LR: 0.000297
Epoch: 119 | Train loss: 0.9850 | Train acc: 51.08% | Val loss: 1.0262 | Val acc: 46.61% | LR: 0.000279
Epoch: 120 | Train loss: 0.9919 | Train acc: 50.51% | Val loss: 1.0268 | Val acc: 46.67% | LR: 0.000261
Epoch: 121 | Train loss: 0.9866 | Train acc: 50.88% | Val loss: 1.0281 | Val acc: 46.54% | LR: 0.000244
Epoch: 122 | Train loss: 0.9858 | Train acc: 50.97% | Val loss: 1.0266 | Val acc: 46.83% | LR: 0.000228
Epoch: 123 | Train loss: 0.9904 | Train acc: 50.51% | Val loss: 1.0295 | Val acc: 46.32% | LR: 0.000212
Epoch: 124 | Train loss: 0.9949 | Train acc: 50.47% | Val loss: 1.0261 | Val acc: 46.85% | LR: 0.000196
Epoch: 125 | Train loss: 0.9947 | Train acc: 50.35% | Val loss: 1.0258 | Val acc: 46.67% | LR: 0.000181
Epoch: 126 | Train loss: 0.9864 | Train acc: 50.91% | Val loss: 1.0211 | Val acc: 47.20% | LR: 0.000167
Epoch: 127 | Train loss: 0.9915 | Train acc: 50.56% | Val loss: 1.0228 | Val acc: 47.11% | LR: 0.000153
Epoch: 128 | Train loss: 0.9910 | Train acc: 50.47% | Val loss: 1.0234 | Val acc: 47.04% | LR: 0.000140
Epoch: 129 | Train loss: 0.9914 | Train acc: 50.50% | Val loss: 1.0251 | Val acc: 46.93% | LR: 0.000127
Epoch: 130 | Train loss: 0.9834 | Train acc: 51.07% | Val loss: 1.0254 | Val acc: 46.89% | LR: 0.000115
Epoch: 131 | Train loss: 0.9862 | Train acc: 51.07% | Val loss: 1.0254 | Val acc: 46.83% | LR: 0.000103
Epoch: 132 | Train loss: 0.9882 | Train acc: 50.91% | Val loss: 1.0269 | Val acc: 46.65% | LR: 0.000092
Epoch: 133 | Train loss: 0.9960 | Train acc: 50.30% | Val loss: 1.0279 | Val acc: 46.52% | LR: 0.000082
Epoch: 134 | Train loss: 0.9943 | Train acc: 50.39% | Val loss: 1.0276 | Val acc: 46.63% | LR: 0.000072
Epoch: 135 | Train loss: 0.9873 | Train acc: 51.01% | Val loss: 1.0271 | Val acc: 46.63% | LR: 0.000063
Epoch: 136 | Train loss: 0.9885 | Train acc: 50.78% | Val loss: 1.0264 | Val acc: 46.71% | LR: 0.000055
Epoch: 137 | Train loss: 0.9832 | Train acc: 51.11% | Val loss: 1.0265 | Val acc: 46.69% | LR: 0.000047
Epoch: 138 | Train loss: 0.9771 | Train acc: 51.50% | Val loss: 1.0266 | Val acc: 46.69% | LR: 0.000039
Epoch: 139 | Train loss: 0.9887 | Train acc: 50.81% | Val loss: 1.0267 | Val acc: 46.69% | LR: 0.000033
Epoch: 140 | Train loss: 0.9883 | Train acc: 50.88% | Val loss: 1.0265 | Val acc: 46.85% | LR: 0.000027
Epoch: 141 | Train loss: 0.9862 | Train acc: 50.97% | Val loss: 1.0265 | Val acc: 46.85% | LR: 0.000021
Epoch: 142 | Train loss: 0.9887 | Train acc: 50.66% | Val loss: 1.0266 | Val acc: 46.83% | LR: 0.000017
Epoch: 143 | Train loss: 0.9871 | Train acc: 50.91% | Val loss: 1.0267 | Val acc: 46.79% | LR: 0.000012
Epoch: 144 | Train loss: 0.9833 | Train acc: 51.11% | Val loss: 1.0269 | Val acc: 46.67% | LR: 0.000009
Epoch: 145 | Train loss: 0.9920 | Train acc: 50.58% | Val loss: 1.0269 | Val acc: 46.67% | LR: 0.000006
Epoch: 146 | Train loss: 0.9847 | Train acc: 51.13% | Val loss: 1.0269 | Val acc: 46.67% | LR: 0.000004
Epoch: 147 | Train loss: 0.9831 | Train acc: 51.17% | Val loss: 1.0269 | Val acc: 46.67% | LR: 0.000002
Epoch: 148 | Train loss: 0.9928 | Train acc: 50.67% | Val loss: 1.0269 | Val acc: 46.67% | LR: 0.000001
Epoch: 149 | Train loss: 0.9838 | Train acc: 51.14% | Val loss: 1.0269 | Val acc: 46.67% | LR: 0.000001

[I 2025-09-23 01:49:44,239] Trial 6 finished with value: 0.5426689743995666 and parameters: {'lr': 0.00291402471504545, 'hidden_size': 34, 'dropout': 0.017455314865651217, 'weight_decay': 0.8084932106771979}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.2807 | Train acc: 50.10% | Val loss: 1.0006 | Val acc: 51.75% | LR: 0.000145
Epoch: 001 | Train loss: 1.0591 | Train acc: 49.81% | Val loss: 0.9995 | Val acc: 51.63% | LR: 0.000145
Epoch: 002 | Train loss: 1.0009 | Train acc: 50.52% | Val loss: 1.0010 | Val acc: 51.99% | LR: 0.000145
Epoch: 003 | Train loss: 1.0143 | Train acc: 49.92% | Val loss: 0.9991 | Val acc: 51.33% | LR: 0.000145
Epoch: 004 | Train loss: 1.0007 | Train acc: 50.51% | Val loss: 1.0056 | Val acc: 49.86% | LR: 0.000145
Epoch: 005 | Train loss: 1.0019 | Train acc: 49.45% | Val loss: 1.0009 | Val acc: 48.72% | LR: 0.000144
Epoch: 006 | Train loss: 1.0000 | Train acc: 50.55% | Val loss: 1.0009 | Val acc: 49.49% | LR: 0.000144
Epoch: 007 | Train loss: 0.9985 | Train acc: 50.60% | Val loss: 1.0066 | Val acc: 49.76% | LR: 0.000144
Epoch: 008 | Train loss: 1.0057 | Train acc: 50.35% | Val loss: 1.0010 | Val acc: 49.84% | LR: 0.000144
Epoch: 009 | Train loss: 0.9915 | Train acc: 51.10% | Val loss: 0.9983 | Val acc: 50.91% | LR: 0.000143
Epoch: 010 | Train loss: 0.9980 | Train acc: 50.18% | Val loss: 1.0318 | Val acc: 51.10% | LR: 0.000143
Epoch: 011 | Train loss: 0.9944 | Train acc: 50.97% | Val loss: 1.0035 | Val acc: 50.96% | LR: 0.000143
Epoch: 012 | Train loss: 0.9928 | Train acc: 50.95% | Val loss: 1.0071 | Val acc: 50.86% | LR: 0.000142
Epoch: 013 | Train loss: 1.0023 | Train acc: 50.23% | Val loss: 1.0167 | Val acc: 52.06% | LR: 0.000142
Epoch: 014 | Train loss: 0.9902 | Train acc: 51.28% | Val loss: 1.0059 | Val acc: 53.05% | LR: 0.000142
Epoch: 015 | Train loss: 0.9965 | Train acc: 51.04% | Val loss: 1.0004 | Val acc: 51.33% | LR: 0.000141
Epoch: 016 | Train loss: 0.9988 | Train acc: 50.60% | Val loss: 1.0095 | Val acc: 51.30% | LR: 0.000141
Epoch: 017 | Train loss: 1.0974 | Train acc: 50.87% | Val loss: 1.0050 | Val acc: 51.88% | LR: 0.000140
Epoch: 018 | Train loss: 0.9899 | Train acc: 51.23% | Val loss: 1.0035 | Val acc: 51.42% | LR: 0.000139
Epoch: 019 | Train loss: 0.9985 | Train acc: 50.64% | Val loss: 1.0018 | Val acc: 51.55% | LR: 0.000139
Epoch: 020 | Train loss: 0.9947 | Train acc: 51.08% | Val loss: 1.0164 | Val acc: 51.69% | LR: 0.000138
Epoch: 021 | Train loss: 0.9959 | Train acc: 50.96% | Val loss: 1.0033 | Val acc: 52.04% | LR: 0.000138
Epoch: 022 | Train loss: 1.0038 | Train acc: 50.57% | Val loss: 1.0100 | Val acc: 52.44% | LR: 0.000137
Epoch: 023 | Train loss: 1.0008 | Train acc: 51.18% | Val loss: 1.0731 | Val acc: 52.40% | LR: 0.000136
Epoch: 024 | Train loss: 0.9919 | Train acc: 50.66% | Val loss: 0.9957 | Val acc: 53.00% | LR: 0.000135
Epoch: 025 | Train loss: 0.9887 | Train acc: 51.35% | Val loss: 1.0051 | Val acc: 52.79% | LR: 0.000135
Epoch: 026 | Train loss: 0.9938 | Train acc: 51.24% | Val loss: 0.9958 | Val acc: 52.48% | LR: 0.000134
Epoch: 027 | Train loss: 1.0013 | Train acc: 50.65% | Val loss: 1.0076 | Val acc: 51.69% | LR: 0.000133
Epoch: 028 | Train loss: 0.9994 | Train acc: 50.43% | Val loss: 0.9983 | Val acc: 52.35% | LR: 0.000132
Epoch: 029 | Train loss: 0.9972 | Train acc: 50.67% | Val loss: 0.9926 | Val acc: 52.57% | LR: 0.000131
Epoch: 030 | Train loss: 0.9941 | Train acc: 51.09% | Val loss: 1.0032 | Val acc: 52.90% | LR: 0.000130
Epoch: 031 | Train loss: 0.9930 | Train acc: 51.17% | Val loss: 1.0054 | Val acc: 52.12% | LR: 0.000129
Epoch: 032 | Train loss: 0.9866 | Train acc: 51.45% | Val loss: 1.0153 | Val acc: 52.36% | LR: 0.000129
Epoch: 033 | Train loss: 0.9920 | Train acc: 51.20% | Val loss: 1.0147 | Val acc: 52.72% | LR: 0.000128
Epoch: 034 | Train loss: 1.0019 | Train acc: 51.16% | Val loss: 0.9926 | Val acc: 52.70% | LR: 0.000127
Epoch: 035 | Train loss: 1.0012 | Train acc: 50.66% | Val loss: 0.9962 | Val acc: 52.37% | LR: 0.000126
Epoch: 036 | Train loss: 0.9955 | Train acc: 51.01% | Val loss: 0.9910 | Val acc: 52.99% | LR: 0.000124
Epoch: 037 | Train loss: 1.0014 | Train acc: 50.28% | Val loss: 0.9920 | Val acc: 53.27% | LR: 0.000123
Epoch: 038 | Train loss: 0.9903 | Train acc: 51.04% | Val loss: 0.9879 | Val acc: 53.43% | LR: 0.000122
Epoch: 039 | Train loss: 1.0013 | Train acc: 50.72% | Val loss: 0.9907 | Val acc: 53.52% | LR: 0.000121
Epoch: 040 | Train loss: 1.0009 | Train acc: 50.41% | Val loss: 1.0516 | Val acc: 53.84% | LR: 0.000120
Epoch: 041 | Train loss: 1.0135 | Train acc: 50.25% | Val loss: 0.9943 | Val acc: 53.48% | LR: 0.000119
Epoch: 042 | Train loss: 0.9986 | Train acc: 50.41% | Val loss: 1.0518 | Val acc: 53.70% | LR: 0.000118
Epoch: 043 | Train loss: 0.9950 | Train acc: 50.75% | Val loss: 0.9781 | Val acc: 53.67% | LR: 0.000117
Epoch: 044 | Train loss: 0.9956 | Train acc: 50.66% | Val loss: 0.9806 | Val acc: 53.67% | LR: 0.000115
Epoch: 045 | Train loss: 0.9863 | Train acc: 51.04% | Val loss: 0.9780 | Val acc: 53.77% | LR: 0.000114
Epoch: 046 | Train loss: 0.9900 | Train acc: 50.98% | Val loss: 0.9762 | Val acc: 53.89% | LR: 0.000113
Epoch: 047 | Train loss: 0.9925 | Train acc: 50.86% | Val loss: 0.9725 | Val acc: 53.91% | LR: 0.000112
Epoch: 048 | Train loss: 0.9911 | Train acc: 50.90% | Val loss: 0.9712 | Val acc: 54.11% | LR: 0.000110
Epoch: 049 | Train loss: 0.9914 | Train acc: 50.78% | Val loss: 0.9733 | Val acc: 53.95% | LR: 0.000109
Epoch: 050 | Train loss: 0.9912 | Train acc: 50.90% | Val loss: 0.9716 | Val acc: 53.87% | LR: 0.000108
Epoch: 051 | Train loss: 0.9851 | Train acc: 51.22% | Val loss: 0.9717 | Val acc: 53.95% | LR: 0.000106
Epoch: 052 | Train loss: 0.9938 | Train acc: 50.82% | Val loss: 0.9731 | Val acc: 53.69% | LR: 0.000105
Epoch: 053 | Train loss: 0.9958 | Train acc: 50.47% | Val loss: 0.9727 | Val acc: 53.75% | LR: 0.000104
Epoch: 054 | Train loss: 0.9968 | Train acc: 50.41% | Val loss: 0.9717 | Val acc: 53.81% | LR: 0.000102
Epoch: 055 | Train loss: 0.9904 | Train acc: 51.16% | Val loss: 0.9723 | Val acc: 53.85% | LR: 0.000101
Epoch: 056 | Train loss: 0.9933 | Train acc: 50.51% | Val loss: 0.9720 | Val acc: 53.75% | LR: 0.000100
Epoch: 057 | Train loss: 0.9910 | Train acc: 50.98% | Val loss: 0.9730 | Val acc: 53.74% | LR: 0.000098
Epoch: 058 | Train loss: 0.9956 | Train acc: 50.76% | Val loss: 0.9725 | Val acc: 53.74% | LR: 0.000097
Epoch: 059 | Train loss: 0.9897 | Train acc: 50.89% | Val loss: 0.9721 | Val acc: 53.70% | LR: 0.000095
Epoch: 060 | Train loss: 0.9906 | Train acc: 50.82% | Val loss: 0.9730 | Val acc: 53.84% | LR: 0.000094
Epoch: 061 | Train loss: 0.9920 | Train acc: 50.70% | Val loss: 0.9721 | Val acc: 53.72% | LR: 0.000092
Epoch: 062 | Train loss: 0.9898 | Train acc: 50.81% | Val loss: 0.9726 | Val acc: 53.68% | LR: 0.000091
Epoch: 063 | Train loss: 0.9946 | Train acc: 50.54% | Val loss: 0.9718 | Val acc: 53.60% | LR: 0.000089
Epoch: 064 | Train loss: 0.9907 | Train acc: 50.90% | Val loss: 0.9716 | Val acc: 53.52% | LR: 0.000088
Epoch: 065 | Train loss: 0.9888 | Train acc: 51.02% | Val loss: 0.9713 | Val acc: 53.58% | LR: 0.000087
Epoch: 066 | Train loss: 0.9924 | Train acc: 50.46% | Val loss: 0.9712 | Val acc: 53.56% | LR: 0.000085
Epoch: 067 | Train loss: 0.9887 | Train acc: 51.23% | Val loss: 0.9730 | Val acc: 53.28% | LR: 0.000084
Epoch: 068 | Train loss: 0.9914 | Train acc: 50.79% | Val loss: 0.9725 | Val acc: 53.42% | LR: 0.000082
Epoch: 069 | Train loss: 0.9933 | Train acc: 50.49% | Val loss: 0.9747 | Val acc: 53.26% | LR: 0.000081
Epoch: 070 | Train loss: 1.0014 | Train acc: 50.31% | Val loss: 0.9793 | Val acc: 53.02% | LR: 0.000079
Epoch: 071 | Train loss: 0.9911 | Train acc: 50.98% | Val loss: 0.9741 | Val acc: 52.98% | LR: 0.000078
Epoch: 072 | Train loss: 0.9945 | Train acc: 50.64% | Val loss: 0.9825 | Val acc: 53.07% | LR: 0.000076
Epoch: 073 | Train loss: 0.9876 | Train acc: 51.08% | Val loss: 0.9854 | Val acc: 53.05% | LR: 0.000075
Epoch: 074 | Train loss: 0.9920 | Train acc: 50.63% | Val loss: 0.9739 | Val acc: 53.09% | LR: 0.000073
Epoch: 075 | Train loss: 0.9942 | Train acc: 51.22% | Val loss: 0.9755 | Val acc: 52.65% | LR: 0.000072
Epoch: 076 | Train loss: 0.9888 | Train acc: 51.23% | Val loss: 0.9759 | Val acc: 52.71% | LR: 0.000070
Epoch: 077 | Train loss: 0.9904 | Train acc: 50.86% | Val loss: 0.9832 | Val acc: 52.57% | LR: 0.000069
Epoch: 078 | Train loss: 0.9996 | Train acc: 50.33% | Val loss: 0.9805 | Val acc: 52.43% | LR: 0.000067
Epoch: 079 | Train loss: 0.9946 | Train acc: 50.94% | Val loss: 0.9864 | Val acc: 52.44% | LR: 0.000066
Epoch: 080 | Train loss: 0.9920 | Train acc: 50.79% | Val loss: 0.9819 | Val acc: 52.02% | LR: 0.000064
Epoch: 081 | Train loss: 1.0400 | Train acc: 51.29% | Val loss: 0.9841 | Val acc: 51.87% | LR: 0.000063
Epoch: 082 | Train loss: 0.9905 | Train acc: 50.73% | Val loss: 0.9947 | Val acc: 52.05% | LR: 0.000061
Epoch: 083 | Train loss: 0.9889 | Train acc: 51.07% | Val loss: 0.9857 | Val acc: 51.80% | LR: 0.000060
Epoch: 084 | Train loss: 1.0123 | Train acc: 50.46% | Val loss: 1.0184 | Val acc: 52.06% | LR: 0.000058
Epoch: 085 | Train loss: 0.9966 | Train acc: 50.71% | Val loss: 0.9911 | Val acc: 52.07% | LR: 0.000057
Epoch: 086 | Train loss: 0.9943 | Train acc: 50.82% | Val loss: 1.1043 | Val acc: 51.98% | LR: 0.000055
Epoch: 087 | Train loss: 0.9966 | Train acc: 51.44% | Val loss: 0.9997 | Val acc: 51.93% | LR: 0.000054
Epoch: 088 | Train loss: 1.0095 | Train acc: 50.46% | Val loss: 1.7891 | Val acc: 51.76% | LR: 0.000052
Epoch: 089 | Train loss: 0.9969 | Train acc: 50.90% | Val loss: 1.0017 | Val acc: 51.54% | LR: 0.000051
Epoch: 090 | Train loss: 0.9879 | Train acc: 50.83% | Val loss: 1.0326 | Val acc: 51.72% | LR: 0.000049
Epoch: 091 | Train loss: 0.9984 | Train acc: 51.10% | Val loss: 0.9881 | Val acc: 51.62% | LR: 0.000048
Epoch: 092 | Train loss: 0.9998 | Train acc: 50.52% | Val loss: 1.0091 | Val acc: 51.40% | LR: 0.000047
Epoch: 093 | Train loss: 1.0013 | Train acc: 50.65% | Val loss: 0.9906 | Val acc: 51.47% | LR: 0.000045
Epoch: 094 | Train loss: 1.0051 | Train acc: 50.81% | Val loss: 0.9966 | Val acc: 51.48% | LR: 0.000044
Epoch: 095 | Train loss: 0.9998 | Train acc: 50.67% | Val loss: 1.0339 | Val acc: 51.48% | LR: 0.000042
Epoch: 096 | Train loss: 0.9945 | Train acc: 50.81% | Val loss: 1.0044 | Val acc: 51.56% | LR: 0.000041
Epoch: 097 | Train loss: 1.3297 | Train acc: 51.00% | Val loss: 0.9948 | Val acc: 51.72% | LR: 0.000040
Epoch: 098 | Train loss: 0.9962 | Train acc: 50.95% | Val loss: 1.0035 | Val acc: 51.60% | LR: 0.000038
Epoch: 099 | Train loss: 0.9937 | Train acc: 51.38% | Val loss: 0.9998 | Val acc: 51.73% | LR: 0.000037
Epoch: 100 | Train loss: 0.9922 | Train acc: 50.98% | Val loss: 0.9980 | Val acc: 51.69% | LR: 0.000036
Epoch: 101 | Train loss: 0.9932 | Train acc: 50.61% | Val loss: 1.0061 | Val acc: 51.91% | LR: 0.000034
Epoch: 102 | Train loss: 0.9943 | Train acc: 50.80% | Val loss: 1.0171 | Val acc: 51.71% | LR: 0.000033
Epoch: 103 | Train loss: 0.9952 | Train acc: 51.06% | Val loss: 0.9863 | Val acc: 51.87% | LR: 0.000032
Epoch: 104 | Train loss: 0.9883 | Train acc: 50.95% | Val loss: 1.0377 | Val acc: 52.18% | LR: 0.000031
Epoch: 105 | Train loss: 0.9881 | Train acc: 50.97% | Val loss: 0.9823 | Val acc: 51.97% | LR: 0.000029
Epoch: 106 | Train loss: 0.9935 | Train acc: 50.45% | Val loss: 0.9826 | Val acc: 52.36% | LR: 0.000028
Epoch: 107 | Train loss: 0.9923 | Train acc: 50.91% | Val loss: 0.9963 | Val acc: 52.27% | LR: 0.000027
Epoch: 108 | Train loss: 0.9973 | Train acc: 50.78% | Val loss: 1.0111 | Val acc: 51.99% | LR: 0.000026
Epoch: 109 | Train loss: 0.9948 | Train acc: 50.26% | Val loss: 0.9880 | Val acc: 52.09% | LR: 0.000025
Epoch: 110 | Train loss: 0.9994 | Train acc: 51.43% | Val loss: 0.9895 | Val acc: 51.93% | LR: 0.000024
Epoch: 111 | Train loss: 0.9976 | Train acc: 50.56% | Val loss: 0.9853 | Val acc: 52.27% | LR: 0.000023
Epoch: 112 | Train loss: 1.0069 | Train acc: 51.17% | Val loss: 0.9877 | Val acc: 51.93% | LR: 0.000022
Epoch: 113 | Train loss: 0.9893 | Train acc: 51.14% | Val loss: 0.9993 | Val acc: 52.11% | LR: 0.000021
Epoch: 114 | Train loss: 0.9919 | Train acc: 51.08% | Val loss: 0.9954 | Val acc: 52.00% | LR: 0.000020
Epoch: 115 | Train loss: 0.9924 | Train acc: 50.91% | Val loss: 0.9876 | Val acc: 52.12% | LR: 0.000019
Epoch: 116 | Train loss: 0.9925 | Train acc: 50.96% | Val loss: 0.9892 | Val acc: 51.62% | LR: 0.000018
Epoch: 117 | Train loss: 0.9891 | Train acc: 51.82% | Val loss: 0.9850 | Val acc: 51.62% | LR: 0.000017
Epoch: 118 | Train loss: 0.9858 | Train acc: 51.43% | Val loss: 0.9877 | Val acc: 51.45% | LR: 0.000016
Epoch: 119 | Train loss: 0.9972 | Train acc: 50.60% | Val loss: 0.9904 | Val acc: 51.59% | LR: 0.000015
Epoch: 120 | Train loss: 0.9961 | Train acc: 50.64% | Val loss: 0.9992 | Val acc: 51.55% | LR: 0.000014
Epoch: 121 | Train loss: 0.9927 | Train acc: 51.08% | Val loss: 1.0061 | Val acc: 51.71% | LR: 0.000013
Epoch: 122 | Train loss: 0.9933 | Train acc: 50.96% | Val loss: 0.9985 | Val acc: 51.39% | LR: 0.000012
Epoch: 123 | Train loss: 0.9969 | Train acc: 51.04% | Val loss: 0.9891 | Val acc: 51.80% | LR: 0.000011
Epoch: 124 | Train loss: 0.9839 | Train acc: 51.35% | Val loss: 0.9868 | Val acc: 51.45% | LR: 0.000011
Epoch: 125 | Train loss: 0.9930 | Train acc: 50.75% | Val loss: 1.0008 | Val acc: 51.53% | LR: 0.000010
Epoch: 126 | Train loss: 0.9939 | Train acc: 50.69% | Val loss: 0.9855 | Val acc: 51.65% | LR: 0.000009
Epoch: 127 | Train loss: 1.0009 | Train acc: 50.64% | Val loss: 1.5102 | Val acc: 51.53% | LR: 0.000009
Epoch: 128 | Train loss: 0.9943 | Train acc: 51.10% | Val loss: 0.9942 | Val acc: 51.57% | LR: 0.000008
Epoch: 129 | Train loss: 0.9915 | Train acc: 50.98% | Val loss: 0.9990 | Val acc: 51.43% | LR: 0.000007
Epoch: 130 | Train loss: 0.9939 | Train acc: 50.78% | Val loss: 0.9890 | Val acc: 51.63% | LR: 0.000007
Epoch: 131 | Train loss: 0.9872 | Train acc: 51.13% | Val loss: 0.9988 | Val acc: 51.47% | LR: 0.000006
Epoch: 132 | Train loss: 0.9888 | Train acc: 50.85% | Val loss: 1.0060 | Val acc: 51.62% | LR: 0.000006
Epoch: 133 | Train loss: 0.9940 | Train acc: 50.81% | Val loss: 0.9878 | Val acc: 51.58% | LR: 0.000005
Epoch: 134 | Train loss: 0.9929 | Train acc: 50.93% | Val loss: 1.0014 | Val acc: 51.47% | LR: 0.000005
Epoch: 135 | Train loss: 0.9877 | Train acc: 51.40% | Val loss: 1.1381 | Val acc: 51.70% | LR: 0.000004
Epoch: 136 | Train loss: 0.9933 | Train acc: 50.86% | Val loss: 1.0576 | Val acc: 51.80% | LR: 0.000004
Epoch: 137 | Train loss: 0.9870 | Train acc: 51.27% | Val loss: 1.0207 | Val acc: 51.64% | LR: 0.000003
Epoch: 138 | Train loss: 0.9980 | Train acc: 50.76% | Val loss: 0.9918 | Val acc: 51.53% | LR: 0.000003
Epoch: 139 | Train loss: 0.9919 | Train acc: 50.89% | Val loss: 0.9931 | Val acc: 51.59% | LR: 0.000003
Epoch: 140 | Train loss: 0.9938 | Train acc: 51.01% | Val loss: 0.9956 | Val acc: 51.49% | LR: 0.000002
Epoch: 141 | Train loss: 0.9938 | Train acc: 50.50% | Val loss: 1.1251 | Val acc: 51.51% | LR: 0.000002
Epoch: 142 | Train loss: 0.9949 | Train acc: 50.74% | Val loss: 0.9859 | Val acc: 51.58% | LR: 0.000002
Epoch: 143 | Train loss: 0.9890 | Train acc: 51.04% | Val loss: 0.9908 | Val acc: 51.49% | LR: 0.000002
Epoch: 144 | Train loss: 0.9927 | Train acc: 51.07% | Val loss: 0.9933 | Val acc: 51.41% | LR: 0.000001
Epoch: 145 | Train loss: 0.9955 | Train acc: 50.59% | Val loss: 0.9890 | Val acc: 51.41% | LR: 0.000001
Epoch: 146 | Train loss: 0.9908 | Train acc: 51.03% | Val loss: 0.9971 | Val acc: 51.39% | LR: 0.000001
Epoch: 147 | Train loss: 0.9969 | Train acc: 50.15% | Val loss: 0.9901 | Val acc: 51.43% | LR: 0.000001
Epoch: 148 | Train loss: 0.9875 | Train acc: 51.37% | Val loss: 0.9905 | Val acc: 51.35% | LR: 0.000001
Epoch: 149 | Train loss: 0.9937 | Train acc: 50.68% | Val loss: 0.9883 | Val acc: 51.35% | LR: 0.000001

[I 2025-09-23 01:53:52,535] Trial 7 finished with value: 0.5410617709159851 and parameters: {'lr': 0.00014506437632316667, 'hidden_size': 172, 'dropout': 0.018370496099335054, 'weight_decay': 0.5594378385457865}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.1651 | Train acc: 50.39% | Val loss: 1.0016 | Val acc: 48.42% | LR: 0.000259
Epoch: 001 | Train loss: 1.0154 | Train acc: 49.70% | Val loss: 1.0015 | Val acc: 46.64% | LR: 0.000259
Epoch: 002 | Train loss: 1.0116 | Train acc: 49.40% | Val loss: 1.0024 | Val acc: 45.96% | LR: 0.000259
Epoch: 003 | Train loss: 1.0030 | Train acc: 50.15% | Val loss: 1.0024 | Val acc: 45.96% | LR: 0.000258
Epoch: 004 | Train loss: 1.0018 | Train acc: 49.96% | Val loss: 1.0028 | Val acc: 45.99% | LR: 0.000258
Epoch: 005 | Train loss: 1.0103 | Train acc: 48.99% | Val loss: 1.0025 | Val acc: 46.01% | LR: 0.000258
Epoch: 006 | Train loss: 1.0042 | Train acc: 50.10% | Val loss: 1.0021 | Val acc: 46.46% | LR: 0.000258
Epoch: 007 | Train loss: 1.0008 | Train acc: 49.86% | Val loss: 1.0020 | Val acc: 46.42% | LR: 0.000257
Epoch: 008 | Train loss: 0.9948 | Train acc: 50.60% | Val loss: 1.0017 | Val acc: 46.64% | LR: 0.000257
Epoch: 009 | Train loss: 0.9984 | Train acc: 50.52% | Val loss: 1.0017 | Val acc: 46.89% | LR: 0.000256
Epoch: 010 | Train loss: 0.9989 | Train acc: 50.01% | Val loss: 1.0013 | Val acc: 47.83% | LR: 0.000256
Epoch: 011 | Train loss: 1.0005 | Train acc: 50.89% | Val loss: 1.0017 | Val acc: 47.50% | LR: 0.000255
Epoch: 012 | Train loss: 0.9913 | Train acc: 51.04% | Val loss: 1.0013 | Val acc: 47.88% | LR: 0.000254
Epoch: 013 | Train loss: 0.9963 | Train acc: 50.68% | Val loss: 1.0008 | Val acc: 48.18% | LR: 0.000253
Epoch: 014 | Train loss: 0.9974 | Train acc: 50.30% | Val loss: 1.0007 | Val acc: 48.35% | LR: 0.000253
Epoch: 015 | Train loss: 0.9922 | Train acc: 51.08% | Val loss: 1.0000 | Val acc: 48.85% | LR: 0.000252
Epoch: 016 | Train loss: 0.9958 | Train acc: 50.47% | Val loss: 0.9995 | Val acc: 49.20% | LR: 0.000251
Epoch: 017 | Train loss: 0.9986 | Train acc: 50.33% | Val loss: 0.9985 | Val acc: 49.52% | LR: 0.000250
Epoch: 018 | Train loss: 0.9953 | Train acc: 50.56% | Val loss: 0.9978 | Val acc: 49.81% | LR: 0.000249
Epoch: 019 | Train loss: 0.9982 | Train acc: 50.76% | Val loss: 0.9975 | Val acc: 50.00% | LR: 0.000248
Epoch: 020 | Train loss: 0.9937 | Train acc: 50.70% | Val loss: 0.9944 | Val acc: 50.33% | LR: 0.000247
Epoch: 021 | Train loss: 0.9944 | Train acc: 50.92% | Val loss: 0.9904 | Val acc: 50.52% | LR: 0.000245
Epoch: 022 | Train loss: 0.9956 | Train acc: 50.54% | Val loss: 0.9867 | Val acc: 50.71% | LR: 0.000244
Epoch: 023 | Train loss: 0.9974 | Train acc: 50.43% | Val loss: 0.9914 | Val acc: 50.37% | LR: 0.000243
Epoch: 024 | Train loss: 0.9894 | Train acc: 50.86% | Val loss: 0.9901 | Val acc: 50.64% | LR: 0.000242
Epoch: 025 | Train loss: 0.9924 | Train acc: 50.53% | Val loss: 0.9905 | Val acc: 50.45% | LR: 0.000240
Epoch: 026 | Train loss: 0.9850 | Train acc: 51.30% | Val loss: 0.9911 | Val acc: 50.31% | LR: 0.000239
Epoch: 027 | Train loss: 0.9899 | Train acc: 51.03% | Val loss: 0.9947 | Val acc: 50.05% | LR: 0.000237
Epoch: 028 | Train loss: 0.9864 | Train acc: 51.30% | Val loss: 0.9957 | Val acc: 49.79% | LR: 0.000236
Epoch: 029 | Train loss: 0.9952 | Train acc: 50.39% | Val loss: 1.0001 | Val acc: 49.28% | LR: 0.000234
Epoch: 030 | Train loss: 0.9920 | Train acc: 50.82% | Val loss: 0.9986 | Val acc: 49.60% | LR: 0.000233
Epoch: 031 | Train loss: 0.9912 | Train acc: 51.08% | Val loss: 1.0030 | Val acc: 48.92% | LR: 0.000231
Epoch: 032 | Train loss: 0.9909 | Train acc: 51.09% | Val loss: 1.0015 | Val acc: 49.23% | LR: 0.000229
Epoch: 033 | Train loss: 0.9854 | Train acc: 51.19% | Val loss: 1.0010 | Val acc: 49.29% | LR: 0.000228
Epoch: 034 | Train loss: 0.9896 | Train acc: 50.79% | Val loss: 1.0059 | Val acc: 48.71% | LR: 0.000226
Epoch: 035 | Train loss: 0.9874 | Train acc: 50.85% | Val loss: 1.0089 | Val acc: 48.63% | LR: 0.000224
Epoch: 036 | Train loss: 0.9906 | Train acc: 51.25% | Val loss: 1.0131 | Val acc: 48.51% | LR: 0.000222
Epoch: 037 | Train loss: 0.9880 | Train acc: 50.87% | Val loss: 1.0135 | Val acc: 48.44% | LR: 0.000220
Epoch: 038 | Train loss: 0.9850 | Train acc: 51.53% | Val loss: 1.0123 | Val acc: 48.55% | LR: 0.000218
Epoch: 039 | Train loss: 0.9903 | Train acc: 50.88% | Val loss: 1.0112 | Val acc: 48.49% | LR: 0.000216
Epoch: 040 | Train loss: 0.9930 | Train acc: 50.82% | Val loss: 1.0177 | Val acc: 48.10% | LR: 0.000214
Epoch: 041 | Train loss: 0.9863 | Train acc: 50.75% | Val loss: 1.0170 | Val acc: 48.28% | LR: 0.000212
Epoch: 042 | Train loss: 0.9909 | Train acc: 51.20% | Val loss: 1.0115 | Val acc: 48.71% | LR: 0.000210
Epoch: 043 | Train loss: 0.9877 | Train acc: 51.15% | Val loss: 1.0143 | Val acc: 48.55% | LR: 0.000208
Epoch: 044 | Train loss: 0.9885 | Train acc: 51.13% | Val loss: 1.0119 | Val acc: 48.59% | LR: 0.000206
Epoch: 045 | Train loss: 0.9932 | Train acc: 50.25% | Val loss: 1.0119 | Val acc: 48.73% | LR: 0.000204
Epoch: 046 | Train loss: 0.9962 | Train acc: 50.37% | Val loss: 1.0144 | Val acc: 48.60% | LR: 0.000201
Epoch: 047 | Train loss: 0.9895 | Train acc: 51.29% | Val loss: 1.0115 | Val acc: 48.61% | LR: 0.000199
Epoch: 048 | Train loss: 0.9897 | Train acc: 51.24% | Val loss: 1.0116 | Val acc: 48.61% | LR: 0.000197
Epoch: 049 | Train loss: 0.9941 | Train acc: 50.86% | Val loss: 1.0001 | Val acc: 49.20% | LR: 0.000194
Epoch: 050 | Train loss: 0.9858 | Train acc: 51.27% | Val loss: 1.0017 | Val acc: 49.22% | LR: 0.000192
Epoch: 051 | Train loss: 0.9867 | Train acc: 51.02% | Val loss: 1.0128 | Val acc: 48.84% | LR: 0.000190
Epoch: 052 | Train loss: 0.9875 | Train acc: 50.83% | Val loss: 1.0048 | Val acc: 49.19% | LR: 0.000187
Epoch: 053 | Train loss: 0.9912 | Train acc: 50.71% | Val loss: 1.0032 | Val acc: 49.16% | LR: 0.000185
Epoch: 054 | Train loss: 0.9910 | Train acc: 50.91% | Val loss: 0.9998 | Val acc: 49.61% | LR: 0.000182
Epoch: 055 | Train loss: 0.9900 | Train acc: 51.04% | Val loss: 0.9974 | Val acc: 49.87% | LR: 0.000180
Epoch: 056 | Train loss: 0.9839 | Train acc: 51.57% | Val loss: 1.0018 | Val acc: 49.41% | LR: 0.000177
Epoch: 057 | Train loss: 0.9885 | Train acc: 50.96% | Val loss: 0.9924 | Val acc: 50.25% | LR: 0.000175
Epoch: 058 | Train loss: 0.9848 | Train acc: 51.21% | Val loss: 0.9991 | Val acc: 49.75% | LR: 0.000172
Epoch: 059 | Train loss: 0.9880 | Train acc: 51.00% | Val loss: 0.9982 | Val acc: 49.91% | LR: 0.000170
Epoch: 060 | Train loss: 0.9897 | Train acc: 50.85% | Val loss: 0.9920 | Val acc: 50.35% | LR: 0.000167
Epoch: 061 | Train loss: 0.9851 | Train acc: 51.06% | Val loss: 0.9996 | Val acc: 49.66% | LR: 0.000165
Epoch: 062 | Train loss: 0.9912 | Train acc: 51.05% | Val loss: 0.9997 | Val acc: 49.89% | LR: 0.000162
Epoch: 063 | Train loss: 0.9877 | Train acc: 51.08% | Val loss: 1.0018 | Val acc: 49.62% | LR: 0.000159
Epoch: 064 | Train loss: 0.9957 | Train acc: 50.56% | Val loss: 1.0001 | Val acc: 49.62% | LR: 0.000157
Epoch: 065 | Train loss: 0.9914 | Train acc: 50.63% | Val loss: 1.0076 | Val acc: 49.64% | LR: 0.000154
Epoch: 066 | Train loss: 0.9831 | Train acc: 51.66% | Val loss: 0.9947 | Val acc: 50.05% | LR: 0.000151
Epoch: 067 | Train loss: 0.9843 | Train acc: 51.30% | Val loss: 0.9958 | Val acc: 50.13% | LR: 0.000149
Epoch: 068 | Train loss: 0.9858 | Train acc: 50.97% | Val loss: 1.0051 | Val acc: 49.08% | LR: 0.000146
Epoch: 069 | Train loss: 0.9908 | Train acc: 50.73% | Val loss: 1.0099 | Val acc: 48.88% | LR: 0.000143
Epoch: 070 | Train loss: 0.9826 | Train acc: 51.54% | Val loss: 1.0074 | Val acc: 48.96% | LR: 0.000141
Epoch: 071 | Train loss: 0.9874 | Train acc: 51.43% | Val loss: 0.9902 | Val acc: 50.30% | LR: 0.000138
Epoch: 072 | Train loss: 0.9815 | Train acc: 51.53% | Val loss: 1.0004 | Val acc: 49.69% | LR: 0.000135
Epoch: 073 | Train loss: 0.9817 | Train acc: 51.19% | Val loss: 0.9955 | Val acc: 49.79% | LR: 0.000133
Epoch: 074 | Train loss: 0.9835 | Train acc: 51.21% | Val loss: 0.9878 | Val acc: 50.62% | LR: 0.000130
Epoch: 075 | Train loss: 0.9811 | Train acc: 51.66% | Val loss: 1.0064 | Val acc: 49.26% | LR: 0.000127
Epoch: 076 | Train loss: 0.9858 | Train acc: 51.11% | Val loss: 1.0009 | Val acc: 49.32% | LR: 0.000125
Epoch: 077 | Train loss: 0.9834 | Train acc: 51.50% | Val loss: 0.9974 | Val acc: 49.47% | LR: 0.000122
Epoch: 078 | Train loss: 0.9760 | Train acc: 51.92% | Val loss: 1.0028 | Val acc: 49.38% | LR: 0.000119
Epoch: 079 | Train loss: 0.9846 | Train acc: 51.33% | Val loss: 0.9916 | Val acc: 50.18% | LR: 0.000116
Epoch: 080 | Train loss: 0.9871 | Train acc: 51.01% | Val loss: 1.0037 | Val acc: 49.46% | LR: 0.000114
Epoch: 081 | Train loss: 0.9839 | Train acc: 51.19% | Val loss: 1.0003 | Val acc: 49.50% | LR: 0.000111
Epoch: 082 | Train loss: 0.9808 | Train acc: 51.38% | Val loss: 0.9919 | Val acc: 50.06% | LR: 0.000108
Epoch: 083 | Train loss: 0.9858 | Train acc: 51.15% | Val loss: 0.9876 | Val acc: 50.48% | LR: 0.000106
Epoch: 084 | Train loss: 0.9871 | Train acc: 50.91% | Val loss: 0.9935 | Val acc: 49.92% | LR: 0.000103
Epoch: 085 | Train loss: 0.9775 | Train acc: 51.56% | Val loss: 0.9919 | Val acc: 50.02% | LR: 0.000101
Epoch: 086 | Train loss: 0.9864 | Train acc: 51.00% | Val loss: 0.9912 | Val acc: 50.24% | LR: 0.000098
Epoch: 087 | Train loss: 0.9834 | Train acc: 51.08% | Val loss: 0.9921 | Val acc: 50.06% | LR: 0.000095
Epoch: 088 | Train loss: 0.9833 | Train acc: 50.86% | Val loss: 0.9983 | Val acc: 49.53% | LR: 0.000093
Epoch: 089 | Train loss: 0.9851 | Train acc: 51.12% | Val loss: 0.9799 | Val acc: 50.90% | LR: 0.000090
Epoch: 090 | Train loss: 0.9796 | Train acc: 51.49% | Val loss: 0.9893 | Val acc: 50.49% | LR: 0.000088
Epoch: 091 | Train loss: 0.9811 | Train acc: 51.61% | Val loss: 0.9855 | Val acc: 50.80% | LR: 0.000085
Epoch: 092 | Train loss: 0.9861 | Train acc: 51.07% | Val loss: 0.9800 | Val acc: 51.02% | LR: 0.000082
Epoch: 093 | Train loss: 0.9839 | Train acc: 51.16% | Val loss: 0.9912 | Val acc: 50.43% | LR: 0.000080
Epoch: 094 | Train loss: 0.9869 | Train acc: 50.94% | Val loss: 0.9897 | Val acc: 50.59% | LR: 0.000078
Epoch: 095 | Train loss: 0.9840 | Train acc: 51.42% | Val loss: 0.9838 | Val acc: 50.97% | LR: 0.000075
Epoch: 096 | Train loss: 0.9879 | Train acc: 51.08% | Val loss: 0.9860 | Val acc: 50.64% | LR: 0.000073
Epoch: 097 | Train loss: 0.9832 | Train acc: 51.37% | Val loss: 0.9862 | Val acc: 50.62% | LR: 0.000070
Epoch: 098 | Train loss: 0.9805 | Train acc: 51.31% | Val loss: 0.9744 | Val acc: 51.24% | LR: 0.000068
Epoch: 099 | Train loss: 0.9788 | Train acc: 51.67% | Val loss: 0.9967 | Val acc: 50.07% | LR: 0.000065
Epoch: 100 | Train loss: 0.9812 | Train acc: 51.23% | Val loss: 0.9723 | Val acc: 51.52% | LR: 0.000063
Epoch: 101 | Train loss: 0.9852 | Train acc: 51.07% | Val loss: 0.9830 | Val acc: 51.03% | LR: 0.000061
Epoch: 102 | Train loss: 0.9867 | Train acc: 51.46% | Val loss: 0.9782 | Val acc: 51.13% | LR: 0.000059
Epoch: 103 | Train loss: 0.9758 | Train acc: 51.99% | Val loss: 0.9850 | Val acc: 50.85% | LR: 0.000056
Epoch: 104 | Train loss: 0.9842 | Train acc: 51.12% | Val loss: 0.9782 | Val acc: 51.16% | LR: 0.000054
Epoch: 105 | Train loss: 0.9837 | Train acc: 51.51% | Val loss: 0.9833 | Val acc: 50.93% | LR: 0.000052
Epoch: 106 | Train loss: 0.9859 | Train acc: 51.14% | Val loss: 0.9781 | Val acc: 51.10% | LR: 0.000050
Epoch: 107 | Train loss: 0.9834 | Train acc: 51.30% | Val loss: 0.9795 | Val acc: 50.98% | LR: 0.000048
Epoch: 108 | Train loss: 0.9796 | Train acc: 51.43% | Val loss: 0.9846 | Val acc: 50.95% | LR: 0.000046
Epoch: 109 | Train loss: 0.9771 | Train acc: 51.78% | Val loss: 0.9847 | Val acc: 50.93% | LR: 0.000044
Epoch: 110 | Train loss: 0.9853 | Train acc: 51.05% | Val loss: 0.9806 | Val acc: 51.04% | LR: 0.000042
Epoch: 111 | Train loss: 0.9815 | Train acc: 51.20% | Val loss: 0.9887 | Val acc: 50.45% | LR: 0.000040
Epoch: 112 | Train loss: 0.9804 | Train acc: 51.32% | Val loss: 0.9831 | Val acc: 50.92% | LR: 0.000038
Epoch: 113 | Train loss: 0.9811 | Train acc: 51.59% | Val loss: 0.9829 | Val acc: 50.98% | LR: 0.000036
Epoch: 114 | Train loss: 0.9826 | Train acc: 51.00% | Val loss: 0.9787 | Val acc: 51.04% | LR: 0.000034
Epoch: 115 | Train loss: 0.9847 | Train acc: 51.32% | Val loss: 0.9861 | Val acc: 50.81% | LR: 0.000032
Epoch: 116 | Train loss: 0.9817 | Train acc: 50.99% | Val loss: 0.9806 | Val acc: 51.18% | LR: 0.000031
Epoch: 117 | Train loss: 0.9874 | Train acc: 50.92% | Val loss: 0.9803 | Val acc: 51.06% | LR: 0.000029
Epoch: 118 | Train loss: 0.9813 | Train acc: 51.22% | Val loss: 0.9780 | Val acc: 51.18% | LR: 0.000027
Epoch: 119 | Train loss: 0.9818 | Train acc: 51.26% | Val loss: 0.9845 | Val acc: 50.95% | LR: 0.000026
Epoch: 120 | Train loss: 0.9777 | Train acc: 51.64% | Val loss: 0.9797 | Val acc: 51.04% | LR: 0.000024
Epoch: 121 | Train loss: 0.9848 | Train acc: 51.40% | Val loss: 0.9821 | Val acc: 51.03% | LR: 0.000023
Epoch: 122 | Train loss: 0.9874 | Train acc: 51.22% | Val loss: 0.9802 | Val acc: 51.02% | LR: 0.000021
Epoch: 123 | Train loss: 0.9817 | Train acc: 51.23% | Val loss: 0.9813 | Val acc: 51.10% | LR: 0.000020
Epoch: 124 | Train loss: 0.9783 | Train acc: 51.11% | Val loss: 0.9802 | Val acc: 51.02% | LR: 0.000018
Epoch: 125 | Train loss: 0.9819 | Train acc: 51.34% | Val loss: 0.9799 | Val acc: 51.04% | LR: 0.000017
Epoch: 126 | Train loss: 0.9834 | Train acc: 51.10% | Val loss: 0.9789 | Val acc: 51.18% | LR: 0.000016
Epoch: 127 | Train loss: 0.9790 | Train acc: 51.39% | Val loss: 0.9800 | Val acc: 51.06% | LR: 0.000014
Epoch: 128 | Train loss: 0.9774 | Train acc: 51.64% | Val loss: 0.9796 | Val acc: 51.18% | LR: 0.000013
Epoch: 129 | Train loss: 0.9794 | Train acc: 51.69% | Val loss: 0.9778 | Val acc: 51.37% | LR: 0.000012
Epoch: 130 | Train loss: 0.9859 | Train acc: 51.30% | Val loss: 0.9786 | Val acc: 51.25% | LR: 0.000011
Epoch: 131 | Train loss: 0.9836 | Train acc: 50.81% | Val loss: 0.9781 | Val acc: 51.18% | LR: 0.000010
Epoch: 132 | Train loss: 0.9721 | Train acc: 52.07% | Val loss: 0.9793 | Val acc: 51.20% | LR: 0.000009
Epoch: 133 | Train loss: 0.9852 | Train acc: 50.91% | Val loss: 0.9775 | Val acc: 51.18% | LR: 0.000008
Epoch: 134 | Train loss: 0.9826 | Train acc: 51.30% | Val loss: 0.9780 | Val acc: 51.25% | LR: 0.000007
Epoch: 135 | Train loss: 0.9804 | Train acc: 51.56% | Val loss: 0.9788 | Val acc: 51.18% | LR: 0.000007
Epoch: 136 | Train loss: 0.9832 | Train acc: 51.00% | Val loss: 0.9778 | Val acc: 51.26% | LR: 0.000006
Epoch: 137 | Train loss: 0.9889 | Train acc: 50.98% | Val loss: 0.9777 | Val acc: 51.22% | LR: 0.000005
Epoch: 138 | Train loss: 0.9859 | Train acc: 51.26% | Val loss: 0.9781 | Val acc: 51.25% | LR: 0.000004
Epoch: 139 | Train loss: 0.9814 | Train acc: 51.41% | Val loss: 0.9787 | Val acc: 51.25% | LR: 0.000004
Epoch: 140 | Train loss: 0.9838 | Train acc: 51.12% | Val loss: 0.9776 | Val acc: 51.21% | LR: 0.000003
Epoch: 141 | Train loss: 0.9820 | Train acc: 51.20% | Val loss: 0.9778 | Val acc: 51.25% | LR: 0.000003
Epoch: 142 | Train loss: 0.9797 | Train acc: 51.37% | Val loss: 0.9780 | Val acc: 51.32% | LR: 0.000002
Epoch: 143 | Train loss: 0.9841 | Train acc: 51.14% | Val loss: 0.9782 | Val acc: 51.25% | LR: 0.000002
Epoch: 144 | Train loss: 0.9806 | Train acc: 51.40% | Val loss: 0.9781 | Val acc: 51.29% | LR: 0.000002
Epoch: 145 | Train loss: 0.9851 | Train acc: 51.28% | Val loss: 0.9777 | Val acc: 51.25% | LR: 0.000001
Epoch: 146 | Train loss: 0.9823 | Train acc: 50.93% | Val loss: 0.9781 | Val acc: 51.29% | LR: 0.000001
Epoch: 147 | Train loss: 0.9827 | Train acc: 51.33% | Val loss: 0.9778 | Val acc: 51.25% | LR: 0.000001
Epoch: 148 | Train loss: 0.9890 | Train acc: 50.51% | Val loss: 0.9777 | Val acc: 51.25% | LR: 0.000001
Epoch: 149 | Train loss: 0.9826 | Train acc: 51.15% | Val loss: 0.9778 | Val acc: 51.25% | LR: 0.000001

[I 2025-09-23 01:57:59,128] Trial 8 finished with value: 0.5152392566204071 and parameters: {'lr': 0.000258908967753991, 'hidden_size': 171, 'dropout': 0.3585761815327256, 'weight_decay': 0.8793696150377786}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.1093 | Train acc: 49.23% | Val loss: 1.0064 | Val acc: 45.93% | LR: 0.000167
Epoch: 001 | Train loss: 1.0022 | Train acc: 50.48% | Val loss: 1.0132 | Val acc: 46.00% | LR: 0.000167
Epoch: 002 | Train loss: 1.0047 | Train acc: 50.18% | Val loss: 1.0072 | Val acc: 46.29% | LR: 0.000167
Epoch: 003 | Train loss: 1.0000 | Train acc: 50.20% | Val loss: 1.0058 | Val acc: 46.05% | LR: 0.000167
Epoch: 004 | Train loss: 1.0038 | Train acc: 49.47% | Val loss: 1.0065 | Val acc: 45.99% | LR: 0.000167
Epoch: 005 | Train loss: 1.0038 | Train acc: 50.09% | Val loss: 1.0067 | Val acc: 46.17% | LR: 0.000167
Epoch: 006 | Train loss: 0.9996 | Train acc: 50.31% | Val loss: 1.0052 | Val acc: 46.53% | LR: 0.000166
Epoch: 007 | Train loss: 0.9942 | Train acc: 50.81% | Val loss: 1.0036 | Val acc: 46.48% | LR: 0.000166
Epoch: 008 | Train loss: 0.9938 | Train acc: 50.95% | Val loss: 1.0041 | Val acc: 46.27% | LR: 0.000166
Epoch: 009 | Train loss: 0.9966 | Train acc: 50.63% | Val loss: 1.0035 | Val acc: 46.60% | LR: 0.000165
Epoch: 010 | Train loss: 1.0040 | Train acc: 49.95% | Val loss: 1.0029 | Val acc: 46.62% | LR: 0.000165
Epoch: 011 | Train loss: 0.9970 | Train acc: 50.37% | Val loss: 1.0025 | Val acc: 46.78% | LR: 0.000165
Epoch: 012 | Train loss: 1.0015 | Train acc: 50.49% | Val loss: 1.0025 | Val acc: 47.09% | LR: 0.000164
Epoch: 013 | Train loss: 0.9955 | Train acc: 50.85% | Val loss: 1.0024 | Val acc: 47.22% | LR: 0.000164
Epoch: 014 | Train loss: 0.9995 | Train acc: 50.25% | Val loss: 1.0020 | Val acc: 47.26% | LR: 0.000163
Epoch: 015 | Train loss: 0.9955 | Train acc: 50.75% | Val loss: 1.0008 | Val acc: 47.77% | LR: 0.000163
Epoch: 016 | Train loss: 1.0095 | Train acc: 50.17% | Val loss: 1.0046 | Val acc: 47.82% | LR: 0.000162
Epoch: 017 | Train loss: 1.0078 | Train acc: 50.33% | Val loss: 1.0037 | Val acc: 48.35% | LR: 0.000161
Epoch: 018 | Train loss: 0.9985 | Train acc: 50.79% | Val loss: 1.0007 | Val acc: 47.86% | LR: 0.000161
Epoch: 019 | Train loss: 1.0022 | Train acc: 50.03% | Val loss: 1.0002 | Val acc: 48.39% | LR: 0.000160
Epoch: 020 | Train loss: 3.0747 | Train acc: 50.42% | Val loss: 0.9999 | Val acc: 48.57% | LR: 0.000159
Epoch: 021 | Train loss: 1.0369 | Train acc: 50.71% | Val loss: 1.0037 | Val acc: 49.03% | LR: 0.000159
Epoch: 022 | Train loss: 0.9946 | Train acc: 50.86% | Val loss: 0.9983 | Val acc: 49.18% | LR: 0.000158
Epoch: 023 | Train loss: 1.0027 | Train acc: 50.73% | Val loss: 0.9977 | Val acc: 49.48% | LR: 0.000157
Epoch: 024 | Train loss: 1.0030 | Train acc: 50.34% | Val loss: 0.9979 | Val acc: 49.74% | LR: 0.000156
Epoch: 025 | Train loss: 0.9955 | Train acc: 50.80% | Val loss: 0.9962 | Val acc: 50.30% | LR: 0.000155
Epoch: 026 | Train loss: 1.0004 | Train acc: 50.28% | Val loss: 0.9994 | Val acc: 50.03% | LR: 0.000154
Epoch: 027 | Train loss: 0.9951 | Train acc: 50.38% | Val loss: 1.0005 | Val acc: 50.13% | LR: 0.000153
Epoch: 028 | Train loss: 0.9939 | Train acc: 50.85% | Val loss: 0.9966 | Val acc: 50.27% | LR: 0.000152
Epoch: 029 | Train loss: 0.9957 | Train acc: 50.99% | Val loss: 0.9948 | Val acc: 50.65% | LR: 0.000151
Epoch: 030 | Train loss: 0.9957 | Train acc: 50.92% | Val loss: 0.9960 | Val acc: 50.63% | LR: 0.000150
Epoch: 031 | Train loss: 0.9967 | Train acc: 51.09% | Val loss: 0.9940 | Val acc: 50.67% | LR: 0.000149
Epoch: 032 | Train loss: 0.9917 | Train acc: 50.88% | Val loss: 0.9948 | Val acc: 50.81% | LR: 0.000148
Epoch: 033 | Train loss: 0.9983 | Train acc: 50.88% | Val loss: 0.9928 | Val acc: 50.87% | LR: 0.000147
Epoch: 034 | Train loss: 0.9973 | Train acc: 50.37% | Val loss: 0.9921 | Val acc: 51.07% | LR: 0.000146
Epoch: 035 | Train loss: 0.9895 | Train acc: 50.99% | Val loss: 0.9913 | Val acc: 51.35% | LR: 0.000145
Epoch: 036 | Train loss: 1.0286 | Train acc: 51.00% | Val loss: 0.9912 | Val acc: 51.30% | LR: 0.000144
Epoch: 037 | Train loss: 0.9896 | Train acc: 50.93% | Val loss: 0.9904 | Val acc: 51.34% | LR: 0.000142
Epoch: 038 | Train loss: 0.9965 | Train acc: 50.89% | Val loss: 0.9915 | Val acc: 51.43% | LR: 0.000141
Epoch: 039 | Train loss: 0.9943 | Train acc: 51.01% | Val loss: 1.0144 | Val acc: 51.70% | LR: 0.000140
Epoch: 040 | Train loss: 0.9930 | Train acc: 50.64% | Val loss: 0.9869 | Val acc: 51.47% | LR: 0.000138
Epoch: 041 | Train loss: 0.9933 | Train acc: 50.40% | Val loss: 0.9793 | Val acc: 52.25% | LR: 0.000137
Epoch: 042 | Train loss: 0.9993 | Train acc: 50.78% | Val loss: 0.9783 | Val acc: 52.81% | LR: 0.000136
Epoch: 043 | Train loss: 0.9937 | Train acc: 50.91% | Val loss: 0.9762 | Val acc: 52.86% | LR: 0.000134
Epoch: 044 | Train loss: 0.9931 | Train acc: 50.99% | Val loss: 0.9743 | Val acc: 53.15% | LR: 0.000133
Epoch: 045 | Train loss: 0.9903 | Train acc: 51.26% | Val loss: 0.9749 | Val acc: 53.23% | LR: 0.000132
Epoch: 046 | Train loss: 0.9913 | Train acc: 51.21% | Val loss: 0.9761 | Val acc: 53.06% | LR: 0.000130
Epoch: 047 | Train loss: 0.9947 | Train acc: 50.89% | Val loss: 0.9843 | Val acc: 52.32% | LR: 0.000129
Epoch: 048 | Train loss: 0.9906 | Train acc: 51.34% | Val loss: 0.9800 | Val acc: 52.03% | LR: 0.000127
Epoch: 049 | Train loss: 0.9915 | Train acc: 50.75% | Val loss: 0.9802 | Val acc: 52.74% | LR: 0.000126
Epoch: 050 | Train loss: 0.9868 | Train acc: 51.22% | Val loss: 0.9844 | Val acc: 53.06% | LR: 0.000124
Epoch: 051 | Train loss: 0.9930 | Train acc: 50.82% | Val loss: 0.9779 | Val acc: 53.05% | LR: 0.000123
Epoch: 052 | Train loss: 0.9935 | Train acc: 50.70% | Val loss: 0.9754 | Val acc: 53.59% | LR: 0.000121
Epoch: 053 | Train loss: 0.9908 | Train acc: 51.03% | Val loss: 0.9732 | Val acc: 53.79% | LR: 0.000120
Epoch: 054 | Train loss: 0.9947 | Train acc: 51.10% | Val loss: 0.9736 | Val acc: 53.87% | LR: 0.000118
Epoch: 055 | Train loss: 0.9912 | Train acc: 51.34% | Val loss: 0.9742 | Val acc: 53.62% | LR: 0.000116
Epoch: 056 | Train loss: 0.9926 | Train acc: 50.32% | Val loss: 0.9712 | Val acc: 53.72% | LR: 0.000115
Epoch: 057 | Train loss: 0.9918 | Train acc: 51.08% | Val loss: 0.9725 | Val acc: 53.68% | LR: 0.000113
Epoch: 058 | Train loss: 0.9959 | Train acc: 51.11% | Val loss: 0.9719 | Val acc: 54.04% | LR: 0.000111
Epoch: 059 | Train loss: 1.0019 | Train acc: 50.60% | Val loss: 0.9706 | Val acc: 54.07% | LR: 0.000110
Epoch: 060 | Train loss: 0.9923 | Train acc: 50.56% | Val loss: 0.9705 | Val acc: 53.85% | LR: 0.000108
Epoch: 061 | Train loss: 0.9936 | Train acc: 50.08% | Val loss: 0.9703 | Val acc: 53.70% | LR: 0.000106
Epoch: 062 | Train loss: 0.9884 | Train acc: 51.23% | Val loss: 0.9724 | Val acc: 53.51% | LR: 0.000105
Epoch: 063 | Train loss: 0.9869 | Train acc: 51.35% | Val loss: 0.9730 | Val acc: 53.65% | LR: 0.000103
Epoch: 064 | Train loss: 0.9968 | Train acc: 50.68% | Val loss: 0.9782 | Val acc: 53.44% | LR: 0.000101
Epoch: 065 | Train loss: 0.9946 | Train acc: 50.80% | Val loss: 0.9731 | Val acc: 53.42% | LR: 0.000100
Epoch: 066 | Train loss: 0.9917 | Train acc: 50.93% | Val loss: 0.9738 | Val acc: 53.34% | LR: 0.000098
Epoch: 067 | Train loss: 0.9860 | Train acc: 51.28% | Val loss: 0.9768 | Val acc: 53.24% | LR: 0.000096
Epoch: 068 | Train loss: 0.9920 | Train acc: 50.46% | Val loss: 0.9757 | Val acc: 53.19% | LR: 0.000095
Epoch: 069 | Train loss: 0.9914 | Train acc: 51.24% | Val loss: 0.9759 | Val acc: 53.16% | LR: 0.000093
Epoch: 070 | Train loss: 0.9981 | Train acc: 49.89% | Val loss: 0.9764 | Val acc: 52.80% | LR: 0.000091
Epoch: 071 | Train loss: 0.9912 | Train acc: 50.74% | Val loss: 0.9772 | Val acc: 52.76% | LR: 0.000089
Epoch: 072 | Train loss: 0.9915 | Train acc: 50.75% | Val loss: 0.9789 | Val acc: 52.65% | LR: 0.000088
Epoch: 073 | Train loss: 0.9896 | Train acc: 50.99% | Val loss: 0.9779 | Val acc: 52.41% | LR: 0.000086
Epoch: 074 | Train loss: 0.9931 | Train acc: 51.25% | Val loss: 0.9789 | Val acc: 52.52% | LR: 0.000084
Epoch: 075 | Train loss: 0.9892 | Train acc: 51.24% | Val loss: 0.9851 | Val acc: 52.15% | LR: 0.000082
Epoch: 076 | Train loss: 0.9933 | Train acc: 50.63% | Val loss: 0.9811 | Val acc: 51.91% | LR: 0.000081
Epoch: 077 | Train loss: 0.9886 | Train acc: 50.85% | Val loss: 0.9820 | Val acc: 51.94% | LR: 0.000079
Epoch: 078 | Train loss: 0.9925 | Train acc: 50.75% | Val loss: 0.9816 | Val acc: 51.86% | LR: 0.000077
Epoch: 079 | Train loss: 0.9932 | Train acc: 50.46% | Val loss: 0.9819 | Val acc: 51.87% | LR: 0.000075
Epoch: 080 | Train loss: 0.9931 | Train acc: 50.77% | Val loss: 0.9822 | Val acc: 51.89% | LR: 0.000074
Epoch: 081 | Train loss: 0.9851 | Train acc: 51.07% | Val loss: 0.9834 | Val acc: 51.50% | LR: 0.000072
Epoch: 082 | Train loss: 0.9972 | Train acc: 50.40% | Val loss: 0.9845 | Val acc: 51.44% | LR: 0.000070
Epoch: 083 | Train loss: 0.9930 | Train acc: 50.53% | Val loss: 0.9851 | Val acc: 51.31% | LR: 0.000069
Epoch: 084 | Train loss: 0.9902 | Train acc: 51.27% | Val loss: 0.9859 | Val acc: 51.31% | LR: 0.000067
Epoch: 085 | Train loss: 0.9909 | Train acc: 50.77% | Val loss: 0.9864 | Val acc: 51.28% | LR: 0.000065
Epoch: 086 | Train loss: 0.9875 | Train acc: 51.06% | Val loss: 0.9860 | Val acc: 51.26% | LR: 0.000063
Epoch: 087 | Train loss: 0.9900 | Train acc: 51.36% | Val loss: 0.9868 | Val acc: 51.14% | LR: 0.000062
Epoch: 088 | Train loss: 0.9934 | Train acc: 50.65% | Val loss: 0.9873 | Val acc: 51.02% | LR: 0.000060
Epoch: 089 | Train loss: 0.9918 | Train acc: 50.88% | Val loss: 0.9881 | Val acc: 51.10% | LR: 0.000058
Epoch: 090 | Train loss: 0.9926 | Train acc: 50.80% | Val loss: 0.9892 | Val acc: 51.05% | LR: 0.000057
Epoch: 091 | Train loss: 0.9928 | Train acc: 50.85% | Val loss: 0.9882 | Val acc: 51.05% | LR: 0.000055
Epoch: 092 | Train loss: 0.9923 | Train acc: 50.75% | Val loss: 0.9879 | Val acc: 51.05% | LR: 0.000054
Epoch: 093 | Train loss: 0.9829 | Train acc: 51.62% | Val loss: 0.9886 | Val acc: 50.99% | LR: 0.000052
Epoch: 094 | Train loss: 0.9878 | Train acc: 51.22% | Val loss: 0.9893 | Val acc: 50.99% | LR: 0.000050
Epoch: 095 | Train loss: 0.9886 | Train acc: 50.43% | Val loss: 0.9895 | Val acc: 50.99% | LR: 0.000049
Epoch: 096 | Train loss: 0.9867 | Train acc: 50.66% | Val loss: 0.9898 | Val acc: 50.82% | LR: 0.000047
Epoch: 097 | Train loss: 0.9911 | Train acc: 50.81% | Val loss: 0.9899 | Val acc: 50.86% | LR: 0.000046
Epoch: 098 | Train loss: 0.9909 | Train acc: 51.20% | Val loss: 0.9905 | Val acc: 50.80% | LR: 0.000044
Epoch: 099 | Train loss: 0.9834 | Train acc: 51.76% | Val loss: 0.9907 | Val acc: 50.80% | LR: 0.000043
Epoch: 100 | Train loss: 0.9934 | Train acc: 50.51% | Val loss: 0.9911 | Val acc: 50.78% | LR: 0.000041
Epoch: 101 | Train loss: 0.9910 | Train acc: 50.83% | Val loss: 0.9926 | Val acc: 50.52% | LR: 0.000040
Epoch: 102 | Train loss: 0.9885 | Train acc: 51.19% | Val loss: 0.9928 | Val acc: 50.48% | LR: 0.000038
Epoch: 103 | Train loss: 0.9847 | Train acc: 51.23% | Val loss: 0.9926 | Val acc: 50.58% | LR: 0.000037
Epoch: 104 | Train loss: 0.9869 | Train acc: 50.86% | Val loss: 0.9929 | Val acc: 50.68% | LR: 0.000035
Epoch: 105 | Train loss: 0.9865 | Train acc: 50.96% | Val loss: 0.9931 | Val acc: 50.72% | LR: 0.000034
Epoch: 106 | Train loss: 0.9897 | Train acc: 50.74% | Val loss: 0.9934 | Val acc: 50.62% | LR: 0.000032
Epoch: 107 | Train loss: 0.9872 | Train acc: 51.09% | Val loss: 0.9937 | Val acc: 50.54% | LR: 0.000031
Epoch: 108 | Train loss: 0.9879 | Train acc: 51.32% | Val loss: 0.9944 | Val acc: 50.36% | LR: 0.000030
Epoch: 109 | Train loss: 0.9913 | Train acc: 50.74% | Val loss: 0.9972 | Val acc: 50.24% | LR: 0.000029
Epoch: 110 | Train loss: 0.9847 | Train acc: 51.22% | Val loss: 1.0017 | Val acc: 50.15% | LR: 0.000027
Epoch: 111 | Train loss: 0.9923 | Train acc: 50.78% | Val loss: 0.9949 | Val acc: 50.19% | LR: 0.000026
Epoch: 112 | Train loss: 0.9915 | Train acc: 50.87% | Val loss: 0.9953 | Val acc: 50.17% | LR: 0.000025
Epoch: 113 | Train loss: 0.9942 | Train acc: 50.82% | Val loss: 0.9972 | Val acc: 50.02% | LR: 0.000024
Epoch: 114 | Train loss: 0.9911 | Train acc: 50.92% | Val loss: 0.9955 | Val acc: 50.07% | LR: 0.000022
Epoch: 115 | Train loss: 0.9891 | Train acc: 50.77% | Val loss: 0.9956 | Val acc: 49.99% | LR: 0.000021
Epoch: 116 | Train loss: 0.9895 | Train acc: 51.21% | Val loss: 0.9958 | Val acc: 49.95% | LR: 0.000020
Epoch: 117 | Train loss: 0.9866 | Train acc: 51.36% | Val loss: 0.9957 | Val acc: 49.95% | LR: 0.000019
Epoch: 118 | Train loss: 0.9895 | Train acc: 50.66% | Val loss: 0.9959 | Val acc: 49.99% | LR: 0.000018
Epoch: 119 | Train loss: 0.9836 | Train acc: 51.29% | Val loss: 0.9960 | Val acc: 49.97% | LR: 0.000017
Epoch: 120 | Train loss: 0.9793 | Train acc: 51.56% | Val loss: 0.9971 | Val acc: 49.99% | LR: 0.000016
Epoch: 121 | Train loss: 0.9900 | Train acc: 50.66% | Val loss: 0.9974 | Val acc: 50.01% | LR: 0.000015
Epoch: 122 | Train loss: 0.9930 | Train acc: 50.19% | Val loss: 0.9967 | Val acc: 50.05% | LR: 0.000014
Epoch: 123 | Train loss: 0.9908 | Train acc: 50.98% | Val loss: 1.0164 | Val acc: 50.03% | LR: 0.000013
Epoch: 124 | Train loss: 0.9891 | Train acc: 51.05% | Val loss: 0.9980 | Val acc: 50.03% | LR: 0.000012
Epoch: 125 | Train loss: 0.9942 | Train acc: 50.46% | Val loss: 0.9981 | Val acc: 49.97% | LR: 0.000011
Epoch: 126 | Train loss: 0.9927 | Train acc: 50.77% | Val loss: 0.9976 | Val acc: 49.93% | LR: 0.000010
Epoch: 127 | Train loss: 0.9907 | Train acc: 50.75% | Val loss: 1.1700 | Val acc: 49.77% | LR: 0.000010
Epoch: 128 | Train loss: 0.9905 | Train acc: 51.08% | Val loss: 0.9980 | Val acc: 49.67% | LR: 0.000009
Epoch: 129 | Train loss: 0.9917 | Train acc: 50.63% | Val loss: 0.9979 | Val acc: 49.69% | LR: 0.000008
Epoch: 130 | Train loss: 0.9911 | Train acc: 50.42% | Val loss: 0.9990 | Val acc: 49.64% | LR: 0.000007
Epoch: 131 | Train loss: 0.9928 | Train acc: 50.49% | Val loss: 0.9987 | Val acc: 49.71% | LR: 0.000007
Epoch: 132 | Train loss: 0.9917 | Train acc: 51.00% | Val loss: 0.9986 | Val acc: 49.73% | LR: 0.000006
Epoch: 133 | Train loss: 0.9892 | Train acc: 51.19% | Val loss: 0.9992 | Val acc: 49.73% | LR: 0.000006
Epoch: 134 | Train loss: 0.9873 | Train acc: 51.45% | Val loss: 1.4692 | Val acc: 49.73% | LR: 0.000005
Epoch: 135 | Train loss: 0.9870 | Train acc: 50.67% | Val loss: 0.9994 | Val acc: 49.75% | LR: 0.000005
Epoch: 136 | Train loss: 0.9961 | Train acc: 50.28% | Val loss: 1.0085 | Val acc: 49.73% | LR: 0.000004
Epoch: 137 | Train loss: 0.9863 | Train acc: 51.05% | Val loss: 1.0039 | Val acc: 49.75% | LR: 0.000004
Epoch: 138 | Train loss: 0.9904 | Train acc: 50.47% | Val loss: 0.9985 | Val acc: 49.77% | LR: 0.000003
Epoch: 139 | Train loss: 0.9880 | Train acc: 50.84% | Val loss: 0.9985 | Val acc: 49.77% | LR: 0.000003
Epoch: 140 | Train loss: 0.9844 | Train acc: 51.49% | Val loss: 0.9986 | Val acc: 49.77% | LR: 0.000002
Epoch: 141 | Train loss: 0.9892 | Train acc: 51.17% | Val loss: 0.9986 | Val acc: 49.79% | LR: 0.000002
Epoch: 142 | Train loss: 0.9914 | Train acc: 50.78% | Val loss: 0.9986 | Val acc: 49.77% | LR: 0.000002
Epoch: 143 | Train loss: 0.9853 | Train acc: 51.12% | Val loss: 0.9987 | Val acc: 49.77% | LR: 0.000002
Epoch: 144 | Train loss: 0.9846 | Train acc: 51.13% | Val loss: 0.9986 | Val acc: 49.77% | LR: 0.000001
Epoch: 145 | Train loss: 0.9922 | Train acc: 50.65% | Val loss: 0.9987 | Val acc: 49.73% | LR: 0.000001
Epoch: 146 | Train loss: 0.9865 | Train acc: 50.96% | Val loss: 0.9987 | Val acc: 49.77% | LR: 0.000001
Epoch: 147 | Train loss: 0.9895 | Train acc: 50.74% | Val loss: 0.9987 | Val acc: 49.69% | LR: 0.000001
Epoch: 148 | Train loss: 0.9879 | Train acc: 50.94% | Val loss: 0.9987 | Val acc: 49.73% | LR: 0.000001
Epoch: 149 | Train loss: 0.9868 | Train acc: 51.23% | Val loss: 0.9987 | Val acc: 49.73% | LR: 0.000001

[I 2025-09-23 02:02:03,376] Trial 9 finished with value: 0.5407479643821717 and parameters: {'lr': 0.0001672682788039695, 'hidden_size': 176, 'dropout': 0.43582524140882206, 'weight_decay': 0.7863511142609031}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.0024 | Train acc: 49.69% | Val loss: 0.9722 | Val acc: 51.64% | LR: 0.006948
Epoch: 001 | Train loss: 0.9931 | Train acc: 50.69% | Val loss: 1.0445 | Val acc: 47.55% | LR: 0.006946
Epoch: 002 | Train loss: 1.0013 | Train acc: 50.37% | Val loss: 1.0488 | Val acc: 45.95% | LR: 0.006942
Epoch: 003 | Train loss: 0.9988 | Train acc: 50.04% | Val loss: 0.9332 | Val acc: 54.05% | LR: 0.006936
Epoch: 004 | Train loss: 1.0056 | Train acc: 49.70% | Val loss: 1.0003 | Val acc: 49.44% | LR: 0.006930
Epoch: 005 | Train loss: 1.0010 | Train acc: 50.42% | Val loss: 0.9979 | Val acc: 50.32% | LR: 0.006921
Epoch: 006 | Train loss: 0.9996 | Train acc: 50.19% | Val loss: 0.9784 | Val acc: 51.69% | LR: 0.006911
Epoch: 007 | Train loss: 0.9892 | Train acc: 51.06% | Val loss: 0.9637 | Val acc: 53.89% | LR: 0.006900
Epoch: 008 | Train loss: 0.9929 | Train acc: 50.74% | Val loss: 0.9946 | Val acc: 50.19% | LR: 0.006887
Epoch: 009 | Train loss: 0.9929 | Train acc: 50.76% | Val loss: 0.9985 | Val acc: 50.16% | LR: 0.006873
Epoch: 010 | Train loss: 0.9912 | Train acc: 51.03% | Val loss: 1.0281 | Val acc: 47.60% | LR: 0.006857
Epoch: 011 | Train loss: 1.0006 | Train acc: 50.15% | Val loss: 1.0015 | Val acc: 50.60% | LR: 0.006839
Epoch: 012 | Train loss: 0.9964 | Train acc: 50.45% | Val loss: 1.0120 | Val acc: 50.49% | LR: 0.006821
Epoch: 013 | Train loss: 1.0009 | Train acc: 50.27% | Val loss: 0.9995 | Val acc: 50.19% | LR: 0.006800
Epoch: 014 | Train loss: 0.9977 | Train acc: 51.12% | Val loss: 0.9857 | Val acc: 50.61% | LR: 0.006779
Epoch: 015 | Train loss: 0.9994 | Train acc: 50.83% | Val loss: 0.9697 | Val acc: 51.41% | LR: 0.006755
Epoch: 016 | Train loss: 0.9923 | Train acc: 50.60% | Val loss: 1.0351 | Val acc: 46.11% | LR: 0.006731
Epoch: 017 | Train loss: 0.9989 | Train acc: 50.28% | Val loss: 1.1179 | Val acc: 48.30% | LR: 0.006705
Epoch: 018 | Train loss: 0.9910 | Train acc: 50.68% | Val loss: 1.6341 | Val acc: 51.47% | LR: 0.006677
Epoch: 019 | Train loss: 0.9942 | Train acc: 50.47% | Val loss: 0.9944 | Val acc: 50.90% | LR: 0.006648
Epoch: 020 | Train loss: 0.9957 | Train acc: 50.64% | Val loss: 0.9810 | Val acc: 53.59% | LR: 0.006618
Epoch: 021 | Train loss: 0.9948 | Train acc: 50.53% | Val loss: 0.9667 | Val acc: 53.08% | LR: 0.006586
Epoch: 022 | Train loss: 0.9957 | Train acc: 50.37% | Val loss: 1.0237 | Val acc: 46.19% | LR: 0.006553
Epoch: 023 | Train loss: 0.9885 | Train acc: 51.06% | Val loss: 1.0278 | Val acc: 45.95% | LR: 0.006519
Epoch: 024 | Train loss: 0.9944 | Train acc: 50.67% | Val loss: 1.0485 | Val acc: 45.95% | LR: 0.006483
Epoch: 025 | Train loss: 0.9981 | Train acc: 50.42% | Val loss: 1.0108 | Val acc: 48.24% | LR: 0.006446
Epoch: 026 | Train loss: 0.9931 | Train acc: 50.76% | Val loss: 0.9635 | Val acc: 52.34% | LR: 0.006408
Epoch: 027 | Train loss: 0.9919 | Train acc: 50.88% | Val loss: 0.9753 | Val acc: 52.33% | LR: 0.006368
Epoch: 028 | Train loss: 0.9889 | Train acc: 51.09% | Val loss: 1.0227 | Val acc: 52.56% | LR: 0.006327
Epoch: 029 | Train loss: 0.9983 | Train acc: 50.49% | Val loss: 0.9572 | Val acc: 53.18% | LR: 0.006285
Epoch: 030 | Train loss: 0.9904 | Train acc: 50.73% | Val loss: 0.9559 | Val acc: 52.81% | LR: 0.006242
Epoch: 031 | Train loss: 0.9910 | Train acc: 50.72% | Val loss: 0.9572 | Val acc: 53.57% | LR: 0.006197
Epoch: 032 | Train loss: 0.9867 | Train acc: 51.18% | Val loss: 0.9931 | Val acc: 52.25% | LR: 0.006151
Epoch: 033 | Train loss: 0.9842 | Train acc: 50.95% | Val loss: 0.9571 | Val acc: 53.21% | LR: 0.006104
Epoch: 034 | Train loss: 0.9883 | Train acc: 50.68% | Val loss: 0.9767 | Val acc: 54.34% | LR: 0.006056
Epoch: 035 | Train loss: 0.9931 | Train acc: 50.56% | Val loss: 0.9800 | Val acc: 53.68% | LR: 0.006007
Epoch: 036 | Train loss: 0.9931 | Train acc: 50.44% | Val loss: 0.9577 | Val acc: 54.32% | LR: 0.005957
Epoch: 037 | Train loss: 0.9888 | Train acc: 51.01% | Val loss: 0.9398 | Val acc: 54.15% | LR: 0.005905
Epoch: 038 | Train loss: 0.9903 | Train acc: 50.67% | Val loss: 0.9910 | Val acc: 52.70% | LR: 0.005853
Epoch: 039 | Train loss: 0.9914 | Train acc: 50.62% | Val loss: 0.9810 | Val acc: 53.17% | LR: 0.005799
Epoch: 040 | Train loss: 0.9902 | Train acc: 50.75% | Val loss: 0.9784 | Val acc: 53.57% | LR: 0.005745
Epoch: 041 | Train loss: 0.9831 | Train acc: 51.30% | Val loss: 0.9572 | Val acc: 53.67% | LR: 0.005689
Epoch: 042 | Train loss: 0.9889 | Train acc: 50.89% | Val loss: 0.9803 | Val acc: 51.88% | LR: 0.005633
Epoch: 043 | Train loss: 0.9830 | Train acc: 51.11% | Val loss: 0.9825 | Val acc: 52.92% | LR: 0.005575
Epoch: 044 | Train loss: 0.9875 | Train acc: 51.02% | Val loss: 0.9779 | Val acc: 52.38% | LR: 0.005517
Epoch: 045 | Train loss: 0.9885 | Train acc: 50.85% | Val loss: 0.9886 | Val acc: 52.05% | LR: 0.005457
Epoch: 046 | Train loss: 0.9879 | Train acc: 50.87% | Val loss: 0.9594 | Val acc: 52.84% | LR: 0.005397
Epoch: 047 | Train loss: 0.9851 | Train acc: 51.04% | Val loss: 0.9829 | Val acc: 52.45% | LR: 0.005336
Epoch: 048 | Train loss: 0.9815 | Train acc: 51.36% | Val loss: 0.9883 | Val acc: 52.32% | LR: 0.005274
Epoch: 049 | Train loss: 0.9914 | Train acc: 50.68% | Val loss: 0.9706 | Val acc: 52.37% | LR: 0.005212
Epoch: 050 | Train loss: 0.9884 | Train acc: 50.99% | Val loss: 0.9767 | Val acc: 52.49% | LR: 0.005148
Epoch: 051 | Train loss: 0.9844 | Train acc: 51.08% | Val loss: 0.9570 | Val acc: 53.30% | LR: 0.005084
Epoch: 052 | Train loss: 0.9863 | Train acc: 50.74% | Val loss: 0.9698 | Val acc: 52.37% | LR: 0.005019
Epoch: 053 | Train loss: 0.9898 | Train acc: 50.92% | Val loss: 0.9799 | Val acc: 52.44% | LR: 0.004954
Epoch: 054 | Train loss: 0.9859 | Train acc: 50.90% | Val loss: 0.9646 | Val acc: 52.61% | LR: 0.004888
Epoch: 055 | Train loss: 0.9817 | Train acc: 51.57% | Val loss: 0.9971 | Val acc: 51.82% | LR: 0.004821
Epoch: 056 | Train loss: 0.9910 | Train acc: 50.67% | Val loss: 0.9733 | Val acc: 52.57% | LR: 0.004754
Epoch: 057 | Train loss: 0.9922 | Train acc: 50.44% | Val loss: 0.9716 | Val acc: 52.70% | LR: 0.004686
Epoch: 058 | Train loss: 0.9856 | Train acc: 51.14% | Val loss: 0.9814 | Val acc: 52.35% | LR: 0.004617
Epoch: 059 | Train loss: 0.9785 | Train acc: 51.39% | Val loss: 0.9714 | Val acc: 52.76% | LR: 0.004548
Epoch: 060 | Train loss: 0.9833 | Train acc: 51.04% | Val loss: 0.9958 | Val acc: 50.14% | LR: 0.004479
Epoch: 061 | Train loss: 0.9831 | Train acc: 51.31% | Val loss: 0.9519 | Val acc: 52.97% | LR: 0.004409
Epoch: 062 | Train loss: 0.9921 | Train acc: 50.48% | Val loss: 0.9536 | Val acc: 52.80% | LR: 0.004339
Epoch: 063 | Train loss: 0.9878 | Train acc: 51.15% | Val loss: 0.9837 | Val acc: 52.96% | LR: 0.004268
Epoch: 064 | Train loss: 0.9919 | Train acc: 50.98% | Val loss: 0.9652 | Val acc: 52.61% | LR: 0.004197
Epoch: 065 | Train loss: 0.9834 | Train acc: 51.33% | Val loss: 0.9818 | Val acc: 51.66% | LR: 0.004126
Epoch: 066 | Train loss: 0.9818 | Train acc: 51.18% | Val loss: 0.9647 | Val acc: 52.66% | LR: 0.004054
Epoch: 067 | Train loss: 0.9796 | Train acc: 51.34% | Val loss: 0.9672 | Val acc: 52.51% | LR: 0.003982
Epoch: 068 | Train loss: 0.9901 | Train acc: 50.90% | Val loss: 0.9959 | Val acc: 51.23% | LR: 0.003910
Epoch: 069 | Train loss: 0.9900 | Train acc: 51.31% | Val loss: 0.9712 | Val acc: 51.56% | LR: 0.003838
Epoch: 070 | Train loss: 0.9921 | Train acc: 50.78% | Val loss: 0.9991 | Val acc: 48.59% | LR: 0.003765
Epoch: 071 | Train loss: 0.9932 | Train acc: 51.04% | Val loss: 1.1212 | Val acc: 48.23% | LR: 0.003693
Epoch: 072 | Train loss: 0.9964 | Train acc: 50.40% | Val loss: 1.0022 | Val acc: 48.88% | LR: 0.003620
Epoch: 073 | Train loss: 0.9892 | Train acc: 51.34% | Val loss: 1.0320 | Val acc: 48.85% | LR: 0.003548
Epoch: 074 | Train loss: 0.9913 | Train acc: 51.11% | Val loss: 1.0521 | Val acc: 47.87% | LR: 0.003475
Epoch: 075 | Train loss: 0.9979 | Train acc: 50.25% | Val loss: 1.0760 | Val acc: 46.74% | LR: 0.003402
Epoch: 076 | Train loss: 0.9922 | Train acc: 51.05% | Val loss: 1.0743 | Val acc: 49.27% | LR: 0.003329
Epoch: 077 | Train loss: 0.9929 | Train acc: 50.72% | Val loss: 1.0151 | Val acc: 49.29% | LR: 0.003257
Epoch: 078 | Train loss: 0.9916 | Train acc: 50.49% | Val loss: 1.0455 | Val acc: 50.10% | LR: 0.003184
Epoch: 079 | Train loss: 0.9858 | Train acc: 51.09% | Val loss: 1.0133 | Val acc: 49.30% | LR: 0.003112
Epoch: 080 | Train loss: 1.0001 | Train acc: 50.37% | Val loss: 1.0040 | Val acc: 49.87% | LR: 0.003039
Epoch: 081 | Train loss: 1.0117 | Train acc: 50.67% | Val loss: 0.9934 | Val acc: 50.07% | LR: 0.002967
Epoch: 082 | Train loss: 0.9940 | Train acc: 50.67% | Val loss: 0.9923 | Val acc: 51.85% | LR: 0.002895
Epoch: 083 | Train loss: 0.9940 | Train acc: 50.67% | Val loss: 0.9844 | Val acc: 50.65% | LR: 0.002824
Epoch: 084 | Train loss: 0.9916 | Train acc: 50.68% | Val loss: 0.9893 | Val acc: 50.79% | LR: 0.002753
Epoch: 085 | Train loss: 0.9870 | Train acc: 51.07% | Val loss: 0.9972 | Val acc: 50.60% | LR: 0.002682
Epoch: 086 | Train loss: 0.9887 | Train acc: 50.89% | Val loss: 0.9811 | Val acc: 49.95% | LR: 0.002611
Epoch: 087 | Train loss: 0.9787 | Train acc: 51.26% | Val loss: 0.9935 | Val acc: 50.13% | LR: 0.002541
Epoch: 088 | Train loss: 0.9887 | Train acc: 51.07% | Val loss: 1.0022 | Val acc: 50.27% | LR: 0.002471
Epoch: 089 | Train loss: 0.9909 | Train acc: 50.71% | Val loss: 0.9889 | Val acc: 50.47% | LR: 0.002401
Epoch: 090 | Train loss: 0.9780 | Train acc: 51.31% | Val loss: 0.9906 | Val acc: 50.43% | LR: 0.002332
Epoch: 091 | Train loss: 0.9867 | Train acc: 50.89% | Val loss: 0.9903 | Val acc: 50.27% | LR: 0.002264
Epoch: 092 | Train loss: 0.9793 | Train acc: 51.33% | Val loss: 1.0133 | Val acc: 49.69% | LR: 0.002196
Epoch: 093 | Train loss: 0.9884 | Train acc: 50.73% | Val loss: 1.0101 | Val acc: 49.13% | LR: 0.002129
Epoch: 094 | Train loss: 0.9885 | Train acc: 50.82% | Val loss: 1.0045 | Val acc: 49.93% | LR: 0.002062
Epoch: 095 | Train loss: 0.9784 | Train acc: 51.41% | Val loss: 1.0091 | Val acc: 49.69% | LR: 0.001996
Epoch: 096 | Train loss: 0.9840 | Train acc: 51.06% | Val loss: 1.0029 | Val acc: 49.75% | LR: 0.001930
Epoch: 097 | Train loss: 0.9881 | Train acc: 50.71% | Val loss: 0.9955 | Val acc: 49.64% | LR: 0.001865
Epoch: 098 | Train loss: 0.9806 | Train acc: 51.15% | Val loss: 1.0050 | Val acc: 49.64% | LR: 0.001801
Epoch: 099 | Train loss: 0.9900 | Train acc: 50.60% | Val loss: 1.0065 | Val acc: 49.43% | LR: 0.001738
Epoch: 100 | Train loss: 0.9816 | Train acc: 51.17% | Val loss: 1.0146 | Val acc: 48.90% | LR: 0.001675
Epoch: 101 | Train loss: 0.9832 | Train acc: 50.93% | Val loss: 1.0105 | Val acc: 49.20% | LR: 0.001613
Epoch: 102 | Train loss: 0.9855 | Train acc: 50.92% | Val loss: 1.0046 | Val acc: 49.27% | LR: 0.001552
Epoch: 103 | Train loss: 0.9844 | Train acc: 50.86% | Val loss: 1.0021 | Val acc: 49.20% | LR: 0.001492
Epoch: 104 | Train loss: 0.9808 | Train acc: 51.15% | Val loss: 1.0056 | Val acc: 49.36% | LR: 0.001433
Epoch: 105 | Train loss: 0.9892 | Train acc: 50.71% | Val loss: 1.0031 | Val acc: 49.49% | LR: 0.001375
Epoch: 106 | Train loss: 0.9855 | Train acc: 50.84% | Val loss: 1.0043 | Val acc: 49.52% | LR: 0.001317
Epoch: 107 | Train loss: 0.9783 | Train acc: 51.33% | Val loss: 0.9994 | Val acc: 49.49% | LR: 0.001261
Epoch: 108 | Train loss: 0.9773 | Train acc: 51.30% | Val loss: 0.9994 | Val acc: 49.55% | LR: 0.001205
Epoch: 109 | Train loss: 0.9822 | Train acc: 51.05% | Val loss: 1.0105 | Val acc: 48.84% | LR: 0.001150
Epoch: 110 | Train loss: 0.9793 | Train acc: 51.14% | Val loss: 1.0125 | Val acc: 48.86% | LR: 0.001097
Epoch: 111 | Train loss: 0.9816 | Train acc: 51.09% | Val loss: 1.0091 | Val acc: 48.74% | LR: 0.001044
Epoch: 112 | Train loss: 0.9849 | Train acc: 50.82% | Val loss: 1.0292 | Val acc: 47.80% | LR: 0.000993
Epoch: 113 | Train loss: 0.9817 | Train acc: 51.00% | Val loss: 1.0124 | Val acc: 49.47% | LR: 0.000943
Epoch: 114 | Train loss: 0.9860 | Train acc: 50.93% | Val loss: 1.0159 | Val acc: 48.99% | LR: 0.000893
Epoch: 115 | Train loss: 0.9870 | Train acc: 50.71% | Val loss: 1.0190 | Val acc: 49.00% | LR: 0.000845
Epoch: 116 | Train loss: 0.9835 | Train acc: 51.20% | Val loss: 1.0131 | Val acc: 49.96% | LR: 0.000798
Epoch: 117 | Train loss: 0.9873 | Train acc: 50.74% | Val loss: 0.9946 | Val acc: 51.11% | LR: 0.000752
Epoch: 118 | Train loss: 0.9826 | Train acc: 51.20% | Val loss: 0.9875 | Val acc: 51.17% | LR: 0.000708
Epoch: 119 | Train loss: 0.9858 | Train acc: 50.89% | Val loss: 0.9836 | Val acc: 51.37% | LR: 0.000664
Epoch: 120 | Train loss: 0.9857 | Train acc: 50.93% | Val loss: 0.9874 | Val acc: 51.12% | LR: 0.000622
Epoch: 121 | Train loss: 0.9805 | Train acc: 51.26% | Val loss: 0.9836 | Val acc: 51.28% | LR: 0.000581
Epoch: 122 | Train loss: 0.9811 | Train acc: 51.14% | Val loss: 0.9904 | Val acc: 51.15% | LR: 0.000542
Epoch: 123 | Train loss: 0.9886 | Train acc: 50.65% | Val loss: 0.9904 | Val acc: 51.27% | LR: 0.000503
Epoch: 124 | Train loss: 0.9823 | Train acc: 51.04% | Val loss: 0.9824 | Val acc: 51.34% | LR: 0.000466
Epoch: 125 | Train loss: 0.9768 | Train acc: 51.37% | Val loss: 0.9909 | Val acc: 51.32% | LR: 0.000431
Epoch: 126 | Train loss: 0.9812 | Train acc: 51.06% | Val loss: 0.9867 | Val acc: 51.23% | LR: 0.000396
Epoch: 127 | Train loss: 0.9784 | Train acc: 51.13% | Val loss: 0.9893 | Val acc: 51.23% | LR: 0.000363
Epoch: 128 | Train loss: 0.9765 | Train acc: 51.49% | Val loss: 0.9873 | Val acc: 51.23% | LR: 0.000332
Epoch: 129 | Train loss: 0.9830 | Train acc: 50.91% | Val loss: 0.9913 | Val acc: 51.15% | LR: 0.000301
Epoch: 130 | Train loss: 0.9826 | Train acc: 51.09% | Val loss: 0.9850 | Val acc: 51.29% | LR: 0.000272
Epoch: 131 | Train loss: 0.9815 | Train acc: 50.97% | Val loss: 0.9896 | Val acc: 51.31% | LR: 0.000245
Epoch: 132 | Train loss: 0.9812 | Train acc: 51.25% | Val loss: 0.9873 | Val acc: 51.31% | LR: 0.000219
Epoch: 133 | Train loss: 0.9836 | Train acc: 50.92% | Val loss: 0.9850 | Val acc: 51.33% | LR: 0.000194
Epoch: 134 | Train loss: 0.9811 | Train acc: 51.06% | Val loss: 0.9856 | Val acc: 51.34% | LR: 0.000171
Epoch: 135 | Train loss: 0.9776 | Train acc: 51.31% | Val loss: 0.9844 | Val acc: 51.32% | LR: 0.000149
Epoch: 136 | Train loss: 0.9788 | Train acc: 51.23% | Val loss: 0.9849 | Val acc: 51.34% | LR: 0.000129
Epoch: 137 | Train loss: 0.9774 | Train acc: 51.34% | Val loss: 0.9873 | Val acc: 51.32% | LR: 0.000110
Epoch: 138 | Train loss: 0.9797 | Train acc: 51.24% | Val loss: 0.9860 | Val acc: 51.36% | LR: 0.000093
Epoch: 139 | Train loss: 0.9791 | Train acc: 51.34% | Val loss: 0.9857 | Val acc: 51.36% | LR: 0.000077
Epoch: 140 | Train loss: 0.9786 | Train acc: 51.33% | Val loss: 0.9853 | Val acc: 51.38% | LR: 0.000063
Epoch: 141 | Train loss: 0.9803 | Train acc: 51.16% | Val loss: 0.9851 | Val acc: 51.36% | LR: 0.000050
Epoch: 142 | Train loss: 0.9865 | Train acc: 50.79% | Val loss: 0.9854 | Val acc: 51.36% | LR: 0.000038
Epoch: 143 | Train loss: 0.9833 | Train acc: 50.99% | Val loss: 0.9854 | Val acc: 51.36% | LR: 0.000028
Epoch: 144 | Train loss: 0.9750 | Train acc: 51.31% | Val loss: 0.9854 | Val acc: 51.36% | LR: 0.000020
Epoch: 145 | Train loss: 0.9689 | Train acc: 51.93% | Val loss: 0.9856 | Val acc: 51.36% | LR: 0.000013
Epoch: 146 | Train loss: 0.9770 | Train acc: 51.41% | Val loss: 0.9856 | Val acc: 51.36% | LR: 0.000008
Epoch: 147 | Train loss: 0.9853 | Train acc: 50.90% | Val loss: 0.9856 | Val acc: 51.36% | LR: 0.000004
Epoch: 148 | Train loss: 0.9734 | Train acc: 51.57% | Val loss: 0.9856 | Val acc: 51.36% | LR: 0.000002
Epoch: 149 | Train loss: 0.9829 | Train acc: 50.95% | Val loss: 0.9856 | Val acc: 51.36% | LR: 0.000001

[I 2025-09-23 02:04:21,738] Trial 10 finished with value: 0.5433734059333801 and parameters: {'lr': 0.0069485738674285695, 'hidden_size': 100, 'dropout': 0.14066118474803413, 'weight_decay': 0.08217290048590709}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 0.9988 | Train acc: 51.00% | Val loss: 1.0009 | Val acc: 49.41% | LR: 0.000700
Epoch: 001 | Train loss: 0.9940 | Train acc: 51.14% | Val loss: 0.9954 | Val acc: 51.80% | LR: 0.000700
Epoch: 002 | Train loss: 0.9953 | Train acc: 50.59% | Val loss: 0.9727 | Val acc: 53.09% | LR: 0.000699
Epoch: 003 | Train loss: 0.9960 | Train acc: 50.29% | Val loss: 0.9525 | Val acc: 53.93% | LR: 0.000699
Epoch: 004 | Train loss: 0.9938 | Train acc: 50.74% | Val loss: 0.9640 | Val acc: 54.18% | LR: 0.000698
Epoch: 005 | Train loss: 0.9924 | Train acc: 50.90% | Val loss: 0.9710 | Val acc: 53.75% | LR: 0.000697
Epoch: 006 | Train loss: 0.9955 | Train acc: 50.40% | Val loss: 0.9646 | Val acc: 53.35% | LR: 0.000696
Epoch: 007 | Train loss: 0.9882 | Train acc: 51.19% | Val loss: 0.9715 | Val acc: 51.95% | LR: 0.000695
Epoch: 008 | Train loss: 0.9941 | Train acc: 50.31% | Val loss: 0.9729 | Val acc: 51.85% | LR: 0.000694
Epoch: 009 | Train loss: 0.9898 | Train acc: 50.64% | Val loss: 0.9754 | Val acc: 51.75% | LR: 0.000692
Epoch: 010 | Train loss: 1.0139 | Train acc: 50.94% | Val loss: 0.9726 | Val acc: 52.11% | LR: 0.000691
Epoch: 011 | Train loss: 0.9914 | Train acc: 50.83% | Val loss: 0.9672 | Val acc: 52.76% | LR: 0.000689
Epoch: 012 | Train loss: 0.9837 | Train acc: 51.28% | Val loss: 0.9864 | Val acc: 51.60% | LR: 0.000687
Epoch: 013 | Train loss: 0.9929 | Train acc: 50.50% | Val loss: 1.0506 | Val acc: 47.56% | LR: 0.000685
Epoch: 014 | Train loss: 1.0014 | Train acc: 50.06% | Val loss: 1.0852 | Val acc: 48.93% | LR: 0.000683
Epoch: 015 | Train loss: 1.0013 | Train acc: 50.24% | Val loss: 1.0064 | Val acc: 50.08% | LR: 0.000681
Epoch: 016 | Train loss: 0.9967 | Train acc: 50.97% | Val loss: 1.0004 | Val acc: 50.47% | LR: 0.000678
Epoch: 017 | Train loss: 0.9864 | Train acc: 51.46% | Val loss: 1.0023 | Val acc: 50.88% | LR: 0.000675
Epoch: 018 | Train loss: 0.9992 | Train acc: 50.35% | Val loss: 0.9929 | Val acc: 50.83% | LR: 0.000673
Epoch: 019 | Train loss: 0.9917 | Train acc: 50.82% | Val loss: 0.9894 | Val acc: 51.08% | LR: 0.000670
Epoch: 020 | Train loss: 0.9914 | Train acc: 50.65% | Val loss: 0.9903 | Val acc: 50.76% | LR: 0.000667
Epoch: 021 | Train loss: 0.9949 | Train acc: 50.40% | Val loss: 0.9891 | Val acc: 50.80% | LR: 0.000664
Epoch: 022 | Train loss: 0.9914 | Train acc: 50.82% | Val loss: 0.9878 | Val acc: 51.03% | LR: 0.000660
Epoch: 023 | Train loss: 0.9886 | Train acc: 50.77% | Val loss: 0.9883 | Val acc: 50.67% | LR: 0.000657
Epoch: 024 | Train loss: 0.9870 | Train acc: 50.84% | Val loss: 0.9924 | Val acc: 50.49% | LR: 0.000653
Epoch: 025 | Train loss: 0.9928 | Train acc: 50.63% | Val loss: 1.0015 | Val acc: 50.22% | LR: 0.000649
Epoch: 026 | Train loss: 0.9925 | Train acc: 50.67% | Val loss: 0.9988 | Val acc: 50.22% | LR: 0.000646
Epoch: 027 | Train loss: 0.9849 | Train acc: 51.22% | Val loss: 1.0067 | Val acc: 49.56% | LR: 0.000642
Epoch: 028 | Train loss: 0.9933 | Train acc: 50.57% | Val loss: 1.0192 | Val acc: 49.05% | LR: 0.000638
Epoch: 029 | Train loss: 0.9964 | Train acc: 50.18% | Val loss: 1.0094 | Val acc: 49.35% | LR: 0.000633
Epoch: 030 | Train loss: 0.9783 | Train acc: 51.51% | Val loss: 1.0092 | Val acc: 49.25% | LR: 0.000629
Epoch: 031 | Train loss: 0.9919 | Train acc: 50.58% | Val loss: 1.0141 | Val acc: 49.39% | LR: 0.000624
Epoch: 032 | Train loss: 0.9840 | Train acc: 51.06% | Val loss: 1.0030 | Val acc: 49.69% | LR: 0.000620
Epoch: 033 | Train loss: 0.9811 | Train acc: 51.46% | Val loss: 1.0040 | Val acc: 49.69% | LR: 0.000615
Epoch: 034 | Train loss: 0.9869 | Train acc: 51.07% | Val loss: 1.0023 | Val acc: 49.66% | LR: 0.000610
Epoch: 035 | Train loss: 0.9875 | Train acc: 50.77% | Val loss: 1.0041 | Val acc: 49.63% | LR: 0.000605
Epoch: 036 | Train loss: 0.9900 | Train acc: 50.81% | Val loss: 1.0098 | Val acc: 49.53% | LR: 0.000600
Epoch: 037 | Train loss: 0.9923 | Train acc: 50.54% | Val loss: 0.9992 | Val acc: 49.77% | LR: 0.000595
Epoch: 038 | Train loss: 0.9833 | Train acc: 51.26% | Val loss: 0.9900 | Val acc: 49.82% | LR: 0.000590
Epoch: 039 | Train loss: 0.9866 | Train acc: 51.03% | Val loss: 0.9983 | Val acc: 50.23% | LR: 0.000584
Epoch: 040 | Train loss: 0.9828 | Train acc: 50.96% | Val loss: 0.9986 | Val acc: 50.14% | LR: 0.000579
Epoch: 041 | Train loss: 0.9798 | Train acc: 51.31% | Val loss: 0.9986 | Val acc: 50.39% | LR: 0.000573
Epoch: 042 | Train loss: 0.9863 | Train acc: 51.00% | Val loss: 1.1193 | Val acc: 51.14% | LR: 0.000568
Epoch: 043 | Train loss: 0.9880 | Train acc: 50.65% | Val loss: 0.9663 | Val acc: 51.99% | LR: 0.000562
Epoch: 044 | Train loss: 0.9901 | Train acc: 51.05% | Val loss: 0.9685 | Val acc: 52.09% | LR: 0.000556
Epoch: 045 | Train loss: 0.9857 | Train acc: 51.13% | Val loss: 0.9501 | Val acc: 53.59% | LR: 0.000550
Epoch: 046 | Train loss: 1.0121 | Train acc: 50.82% | Val loss: 0.9394 | Val acc: 54.45% | LR: 0.000544
Epoch: 047 | Train loss: 0.9854 | Train acc: 51.01% | Val loss: 0.9399 | Val acc: 54.28% | LR: 0.000538
Epoch: 048 | Train loss: 0.9872 | Train acc: 50.83% | Val loss: 0.9564 | Val acc: 53.02% | LR: 0.000532
Epoch: 049 | Train loss: 0.9849 | Train acc: 51.03% | Val loss: 0.9486 | Val acc: 53.46% | LR: 0.000525
Epoch: 050 | Train loss: 0.9835 | Train acc: 51.29% | Val loss: 0.9540 | Val acc: 53.85% | LR: 0.000519
Epoch: 051 | Train loss: 0.9838 | Train acc: 51.21% | Val loss: 0.9458 | Val acc: 53.62% | LR: 0.000512
Epoch: 052 | Train loss: 0.9873 | Train acc: 50.85% | Val loss: 0.9489 | Val acc: 53.68% | LR: 0.000506
Epoch: 053 | Train loss: 0.9866 | Train acc: 51.03% | Val loss: 0.9406 | Val acc: 53.70% | LR: 0.000499
Epoch: 054 | Train loss: 0.9916 | Train acc: 50.84% | Val loss: 0.9366 | Val acc: 54.42% | LR: 0.000493
Epoch: 055 | Train loss: 0.9826 | Train acc: 51.10% | Val loss: 0.9461 | Val acc: 54.19% | LR: 0.000486
Epoch: 056 | Train loss: 0.9888 | Train acc: 50.73% | Val loss: 0.9457 | Val acc: 54.00% | LR: 0.000479
Epoch: 057 | Train loss: 0.9827 | Train acc: 51.27% | Val loss: 0.9422 | Val acc: 54.32% | LR: 0.000472
Epoch: 058 | Train loss: 0.9887 | Train acc: 50.83% | Val loss: 0.9539 | Val acc: 53.47% | LR: 0.000465
Epoch: 059 | Train loss: 0.9937 | Train acc: 50.54% | Val loss: 0.9486 | Val acc: 53.17% | LR: 0.000459
Epoch: 060 | Train loss: 0.9777 | Train acc: 51.52% | Val loss: 0.9468 | Val acc: 53.94% | LR: 0.000452
Epoch: 061 | Train loss: 0.9902 | Train acc: 50.70% | Val loss: 0.9447 | Val acc: 54.02% | LR: 0.000445
Epoch: 062 | Train loss: 0.9966 | Train acc: 50.08% | Val loss: 0.9837 | Val acc: 54.03% | LR: 0.000437
Epoch: 063 | Train loss: 0.9887 | Train acc: 51.07% | Val loss: 0.9644 | Val acc: 53.04% | LR: 0.000430
Epoch: 064 | Train loss: 0.9839 | Train acc: 51.08% | Val loss: 0.9678 | Val acc: 52.68% | LR: 0.000423
Epoch: 065 | Train loss: 0.9841 | Train acc: 51.31% | Val loss: 0.9646 | Val acc: 52.36% | LR: 0.000416
Epoch: 066 | Train loss: 0.9828 | Train acc: 51.22% | Val loss: 0.9766 | Val acc: 52.18% | LR: 0.000409
Epoch: 067 | Train loss: 0.9865 | Train acc: 50.79% | Val loss: 0.9611 | Val acc: 52.73% | LR: 0.000402
Epoch: 068 | Train loss: 0.9915 | Train acc: 50.55% | Val loss: 0.9783 | Val acc: 53.00% | LR: 0.000394
Epoch: 069 | Train loss: 0.9896 | Train acc: 50.89% | Val loss: 0.9655 | Val acc: 52.46% | LR: 0.000387
Epoch: 070 | Train loss: 0.9892 | Train acc: 50.71% | Val loss: 0.9721 | Val acc: 52.00% | LR: 0.000380
Epoch: 071 | Train loss: 0.9863 | Train acc: 50.89% | Val loss: 0.9723 | Val acc: 51.70% | LR: 0.000372
Epoch: 072 | Train loss: 0.9817 | Train acc: 51.28% | Val loss: 0.9722 | Val acc: 51.56% | LR: 0.000365
Epoch: 073 | Train loss: 0.9787 | Train acc: 51.32% | Val loss: 0.9760 | Val acc: 51.48% | LR: 0.000358
Epoch: 074 | Train loss: 0.9872 | Train acc: 50.92% | Val loss: 0.9719 | Val acc: 51.40% | LR: 0.000351
Epoch: 075 | Train loss: 0.9843 | Train acc: 50.93% | Val loss: 0.9788 | Val acc: 51.24% | LR: 0.000343
Epoch: 076 | Train loss: 0.9849 | Train acc: 50.92% | Val loss: 0.9725 | Val acc: 51.89% | LR: 0.000336
Epoch: 077 | Train loss: 0.9808 | Train acc: 51.24% | Val loss: 0.9769 | Val acc: 51.79% | LR: 0.000329
Epoch: 078 | Train loss: 0.9867 | Train acc: 50.82% | Val loss: 0.9771 | Val acc: 51.30% | LR: 0.000321
Epoch: 079 | Train loss: 0.9860 | Train acc: 50.92% | Val loss: 0.9740 | Val acc: 51.83% | LR: 0.000314
Epoch: 080 | Train loss: 0.9732 | Train acc: 51.57% | Val loss: 0.9650 | Val acc: 52.17% | LR: 0.000307
Epoch: 081 | Train loss: 0.9829 | Train acc: 51.09% | Val loss: 0.9708 | Val acc: 51.88% | LR: 0.000299
Epoch: 082 | Train loss: 0.9825 | Train acc: 50.90% | Val loss: 0.9729 | Val acc: 51.86% | LR: 0.000292
Epoch: 083 | Train loss: 0.9832 | Train acc: 51.08% | Val loss: 0.9719 | Val acc: 51.94% | LR: 0.000285
Epoch: 084 | Train loss: 0.9817 | Train acc: 51.19% | Val loss: 0.9775 | Val acc: 51.77% | LR: 0.000278
Epoch: 085 | Train loss: 0.9851 | Train acc: 50.90% | Val loss: 0.9760 | Val acc: 51.83% | LR: 0.000271
Epoch: 086 | Train loss: 0.9804 | Train acc: 51.19% | Val loss: 0.9761 | Val acc: 51.55% | LR: 0.000264
Epoch: 087 | Train loss: 0.9874 | Train acc: 50.77% | Val loss: 0.9762 | Val acc: 51.67% | LR: 0.000257
Epoch: 088 | Train loss: 0.9888 | Train acc: 50.69% | Val loss: 0.9751 | Val acc: 51.77% | LR: 0.000249
Epoch: 089 | Train loss: 0.9780 | Train acc: 51.46% | Val loss: 0.9744 | Val acc: 51.61% | LR: 0.000243
Epoch: 090 | Train loss: 0.9839 | Train acc: 50.92% | Val loss: 0.9755 | Val acc: 51.83% | LR: 0.000236
Epoch: 091 | Train loss: 0.9856 | Train acc: 50.82% | Val loss: 0.9722 | Val acc: 51.81% | LR: 0.000229
Epoch: 092 | Train loss: 0.9899 | Train acc: 50.65% | Val loss: 0.9795 | Val acc: 51.77% | LR: 0.000222
Epoch: 093 | Train loss: 0.9821 | Train acc: 51.01% | Val loss: 0.9716 | Val acc: 51.79% | LR: 0.000215
Epoch: 094 | Train loss: 0.9821 | Train acc: 51.00% | Val loss: 0.9728 | Val acc: 51.77% | LR: 0.000208
Epoch: 095 | Train loss: 0.9930 | Train acc: 50.30% | Val loss: 0.9752 | Val acc: 51.77% | LR: 0.000202
Epoch: 096 | Train loss: 0.9870 | Train acc: 51.00% | Val loss: 0.9735 | Val acc: 51.93% | LR: 0.000195
Epoch: 097 | Train loss: 0.9829 | Train acc: 51.07% | Val loss: 0.9784 | Val acc: 51.61% | LR: 0.000189
Epoch: 098 | Train loss: 0.9875 | Train acc: 50.76% | Val loss: 0.9804 | Val acc: 51.43% | LR: 0.000182
Epoch: 099 | Train loss: 0.9874 | Train acc: 50.76% | Val loss: 0.9850 | Val acc: 51.61% | LR: 0.000176
Epoch: 100 | Train loss: 0.9766 | Train acc: 51.37% | Val loss: 0.9853 | Val acc: 51.55% | LR: 0.000169
Epoch: 101 | Train loss: 0.9797 | Train acc: 51.29% | Val loss: 0.9760 | Val acc: 51.61% | LR: 0.000163
Epoch: 102 | Train loss: 0.9842 | Train acc: 51.10% | Val loss: 0.9774 | Val acc: 51.59% | LR: 0.000157
Epoch: 103 | Train loss: 0.9826 | Train acc: 51.01% | Val loss: 0.9716 | Val acc: 52.02% | LR: 0.000151
Epoch: 104 | Train loss: 0.9883 | Train acc: 50.64% | Val loss: 0.9696 | Val acc: 51.97% | LR: 0.000145
Epoch: 105 | Train loss: 0.9844 | Train acc: 51.00% | Val loss: 0.9714 | Val acc: 51.95% | LR: 0.000139
Epoch: 106 | Train loss: 0.9830 | Train acc: 50.98% | Val loss: 0.9702 | Val acc: 52.05% | LR: 0.000133
Epoch: 107 | Train loss: 0.9850 | Train acc: 50.87% | Val loss: 0.9691 | Val acc: 52.13% | LR: 0.000128
Epoch: 108 | Train loss: 0.9838 | Train acc: 50.98% | Val loss: 0.9705 | Val acc: 52.11% | LR: 0.000122
Epoch: 109 | Train loss: 0.9901 | Train acc: 50.52% | Val loss: 0.9686 | Val acc: 52.07% | LR: 0.000117
Epoch: 110 | Train loss: 0.9803 | Train acc: 51.14% | Val loss: 0.9662 | Val acc: 52.33% | LR: 0.000111
Epoch: 111 | Train loss: 0.9823 | Train acc: 51.13% | Val loss: 0.9653 | Val acc: 52.52% | LR: 0.000106
Epoch: 112 | Train loss: 0.9804 | Train acc: 51.13% | Val loss: 0.9633 | Val acc: 52.56% | LR: 0.000101
Epoch: 113 | Train loss: 0.9868 | Train acc: 50.77% | Val loss: 0.9666 | Val acc: 52.29% | LR: 0.000096
Epoch: 114 | Train loss: 0.9831 | Train acc: 50.88% | Val loss: 0.9656 | Val acc: 52.40% | LR: 0.000091
Epoch: 115 | Train loss: 0.9792 | Train acc: 51.24% | Val loss: 0.9663 | Val acc: 52.31% | LR: 0.000086
Epoch: 116 | Train loss: 0.9853 | Train acc: 50.90% | Val loss: 0.9665 | Val acc: 52.29% | LR: 0.000081
Epoch: 117 | Train loss: 0.9867 | Train acc: 50.71% | Val loss: 0.9673 | Val acc: 52.25% | LR: 0.000077
Epoch: 118 | Train loss: 0.9858 | Train acc: 50.80% | Val loss: 0.9668 | Val acc: 52.36% | LR: 0.000072
Epoch: 119 | Train loss: 0.9856 | Train acc: 50.80% | Val loss: 0.9691 | Val acc: 52.19% | LR: 0.000068
Epoch: 120 | Train loss: 0.9856 | Train acc: 50.79% | Val loss: 0.9693 | Val acc: 52.21% | LR: 0.000064
Epoch: 121 | Train loss: 0.9835 | Train acc: 50.97% | Val loss: 0.9688 | Val acc: 52.18% | LR: 0.000059
Epoch: 122 | Train loss: 0.9941 | Train acc: 50.35% | Val loss: 0.9682 | Val acc: 52.26% | LR: 0.000055
Epoch: 123 | Train loss: 0.9855 | Train acc: 50.90% | Val loss: 0.9689 | Val acc: 52.27% | LR: 0.000052
Epoch: 124 | Train loss: 0.9837 | Train acc: 50.89% | Val loss: 0.9682 | Val acc: 52.20% | LR: 0.000048
Epoch: 125 | Train loss: 0.9790 | Train acc: 51.25% | Val loss: 0.9739 | Val acc: 52.20% | LR: 0.000044
Epoch: 126 | Train loss: 0.9820 | Train acc: 50.98% | Val loss: 0.9681 | Val acc: 52.25% | LR: 0.000041
Epoch: 127 | Train loss: 0.9899 | Train acc: 50.54% | Val loss: 0.9676 | Val acc: 52.23% | LR: 0.000037
Epoch: 128 | Train loss: 0.9834 | Train acc: 50.99% | Val loss: 0.9682 | Val acc: 52.23% | LR: 0.000034
Epoch: 129 | Train loss: 0.9845 | Train acc: 50.82% | Val loss: 0.9670 | Val acc: 52.23% | LR: 0.000031
Epoch: 130 | Train loss: 0.9859 | Train acc: 50.82% | Val loss: 0.9681 | Val acc: 52.29% | LR: 0.000028
Epoch: 131 | Train loss: 0.9891 | Train acc: 50.65% | Val loss: 0.9682 | Val acc: 52.25% | LR: 0.000026
Epoch: 132 | Train loss: 0.9864 | Train acc: 50.74% | Val loss: 0.9681 | Val acc: 52.27% | LR: 0.000023
Epoch: 133 | Train loss: 0.9792 | Train acc: 51.18% | Val loss: 0.9693 | Val acc: 52.31% | LR: 0.000020
Epoch: 134 | Train loss: 0.9861 | Train acc: 50.74% | Val loss: 0.9689 | Val acc: 52.35% | LR: 0.000018
Epoch: 135 | Train loss: 0.9781 | Train acc: 51.18% | Val loss: 0.9686 | Val acc: 52.31% | LR: 0.000016
Epoch: 136 | Train loss: 0.9858 | Train acc: 50.82% | Val loss: 0.9692 | Val acc: 52.29% | LR: 0.000014
Epoch: 137 | Train loss: 0.9787 | Train acc: 51.27% | Val loss: 0.9691 | Val acc: 52.29% | LR: 0.000012
Epoch: 138 | Train loss: 0.9871 | Train acc: 50.74% | Val loss: 0.9684 | Val acc: 52.31% | LR: 0.000010
Epoch: 139 | Train loss: 0.9849 | Train acc: 50.83% | Val loss: 0.9684 | Val acc: 52.35% | LR: 0.000009
Epoch: 140 | Train loss: 0.9815 | Train acc: 51.00% | Val loss: 0.9690 | Val acc: 52.31% | LR: 0.000007
Epoch: 141 | Train loss: 0.9863 | Train acc: 50.82% | Val loss: 0.9691 | Val acc: 52.31% | LR: 0.000006
Epoch: 142 | Train loss: 0.9789 | Train acc: 51.27% | Val loss: 0.9692 | Val acc: 52.31% | LR: 0.000005
Epoch: 143 | Train loss: 0.9807 | Train acc: 51.10% | Val loss: 0.9690 | Val acc: 52.31% | LR: 0.000004
Epoch: 144 | Train loss: 0.9858 | Train acc: 50.74% | Val loss: 0.9689 | Val acc: 52.31% | LR: 0.000003
Epoch: 145 | Train loss: 0.9799 | Train acc: 51.09% | Val loss: 0.9689 | Val acc: 52.31% | LR: 0.000002
Epoch: 146 | Train loss: 0.9797 | Train acc: 51.18% | Val loss: 0.9689 | Val acc: 52.31% | LR: 0.000002
Epoch: 147 | Train loss: 0.9915 | Train acc: 50.39% | Val loss: 0.9689 | Val acc: 52.31% | LR: 0.000001
Epoch: 148 | Train loss: 0.9853 | Train acc: 50.83% | Val loss: 0.9690 | Val acc: 52.31% | LR: 0.000001
Epoch: 149 | Train loss: 0.9829 | Train acc: 51.01% | Val loss: 0.9690 | Val acc: 52.31% | LR: 0.000001

[I 2025-09-23 02:06:31,660] Trial 11 finished with value: 0.5445485353469849 and parameters: {'lr': 0.0007000206900872654, 'hidden_size': 246, 'dropout': 0.32970746336483897, 'weight_decay': 0.45891255608354714}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 0.9979 | Train acc: 50.82% | Val loss: 0.9908 | Val acc: 52.11% | LR: 0.000745
Epoch: 001 | Train loss: 0.9835 | Train acc: 51.19% | Val loss: 1.0017 | Val acc: 49.86% | LR: 0.000745
Epoch: 002 | Train loss: 0.9813 | Train acc: 51.16% | Val loss: 0.9988 | Val acc: 50.06% | LR: 0.000744
Epoch: 003 | Train loss: 0.9780 | Train acc: 51.60% | Val loss: 1.1999 | Val acc: 50.27% | LR: 0.000744
Epoch: 004 | Train loss: 0.9979 | Train acc: 50.15% | Val loss: 0.9997 | Val acc: 49.86% | LR: 0.000743
Epoch: 005 | Train loss: 1.3305 | Train acc: 51.40% | Val loss: 0.9560 | Val acc: 53.01% | LR: 0.000742
Epoch: 006 | Train loss: 0.9864 | Train acc: 51.24% | Val loss: 0.9289 | Val acc: 54.53% | LR: 0.000741
Epoch: 007 | Train loss: 0.9917 | Train acc: 50.62% | Val loss: 0.9432 | Val acc: 53.94% | LR: 0.000740
Epoch: 008 | Train loss: 0.9862 | Train acc: 50.86% | Val loss: 0.9638 | Val acc: 53.44% | LR: 0.000738
Epoch: 009 | Train loss: 0.9819 | Train acc: 51.26% | Val loss: 0.9837 | Val acc: 51.13% | LR: 0.000737
Epoch: 010 | Train loss: 0.9878 | Train acc: 50.41% | Val loss: 0.9947 | Val acc: 50.98% | LR: 0.000735
Epoch: 011 | Train loss: 0.9870 | Train acc: 50.64% | Val loss: 1.0424 | Val acc: 49.29% | LR: 0.000733
Epoch: 012 | Train loss: 0.9851 | Train acc: 51.12% | Val loss: 1.0147 | Val acc: 49.57% | LR: 0.000731
Epoch: 013 | Train loss: 0.9865 | Train acc: 50.89% | Val loss: 1.1630 | Val acc: 49.35% | LR: 0.000729
Epoch: 014 | Train loss: 0.9780 | Train acc: 51.37% | Val loss: 1.0001 | Val acc: 50.23% | LR: 0.000727
Epoch: 015 | Train loss: 0.9965 | Train acc: 50.86% | Val loss: 0.9868 | Val acc: 50.80% | LR: 0.000724
Epoch: 016 | Train loss: 0.9783 | Train acc: 51.53% | Val loss: 0.9887 | Val acc: 50.82% | LR: 0.000722
Epoch: 017 | Train loss: 0.9839 | Train acc: 51.07% | Val loss: 0.9906 | Val acc: 50.54% | LR: 0.000719
Epoch: 018 | Train loss: 0.9830 | Train acc: 50.96% | Val loss: 1.0069 | Val acc: 50.22% | LR: 0.000716
Epoch: 019 | Train loss: 0.9870 | Train acc: 51.03% | Val loss: 1.0076 | Val acc: 50.26% | LR: 0.000713
Epoch: 020 | Train loss: 0.9841 | Train acc: 50.99% | Val loss: 1.0232 | Val acc: 49.43% | LR: 0.000710
Epoch: 021 | Train loss: 0.9806 | Train acc: 51.29% | Val loss: 1.0124 | Val acc: 49.45% | LR: 0.000706
Epoch: 022 | Train loss: 0.9802 | Train acc: 51.16% | Val loss: 1.0185 | Val acc: 49.37% | LR: 0.000703
Epoch: 023 | Train loss: 0.9755 | Train acc: 51.51% | Val loss: 1.0256 | Val acc: 49.10% | LR: 0.000699
Epoch: 024 | Train loss: 0.9804 | Train acc: 51.26% | Val loss: 0.9913 | Val acc: 50.01% | LR: 0.000695
Epoch: 025 | Train loss: 0.9841 | Train acc: 51.00% | Val loss: 1.0063 | Val acc: 49.91% | LR: 0.000691
Epoch: 026 | Train loss: 0.9847 | Train acc: 50.92% | Val loss: 1.0038 | Val acc: 50.03% | LR: 0.000687
Epoch: 027 | Train loss: 0.9857 | Train acc: 51.00% | Val loss: 1.0193 | Val acc: 49.89% | LR: 0.000683
Epoch: 028 | Train loss: 0.9829 | Train acc: 51.06% | Val loss: 0.9993 | Val acc: 49.99% | LR: 0.000679
Epoch: 029 | Train loss: 0.9830 | Train acc: 50.98% | Val loss: 1.0022 | Val acc: 49.85% | LR: 0.000674
Epoch: 030 | Train loss: 0.9826 | Train acc: 50.97% | Val loss: 1.0006 | Val acc: 49.99% | LR: 0.000669
Epoch: 031 | Train loss: 0.9887 | Train acc: 50.71% | Val loss: 1.0017 | Val acc: 50.01% | LR: 0.000665
Epoch: 032 | Train loss: 0.9774 | Train acc: 51.43% | Val loss: 1.0025 | Val acc: 50.17% | LR: 0.000660
Epoch: 033 | Train loss: 0.9909 | Train acc: 50.48% | Val loss: 0.9946 | Val acc: 50.01% | LR: 0.000655
Epoch: 034 | Train loss: 0.9785 | Train acc: 51.28% | Val loss: 1.0042 | Val acc: 49.99% | LR: 0.000650
Epoch: 035 | Train loss: 0.9821 | Train acc: 51.05% | Val loss: 0.9887 | Val acc: 50.43% | LR: 0.000644
Epoch: 036 | Train loss: 0.9934 | Train acc: 50.40% | Val loss: 0.9928 | Val acc: 50.58% | LR: 0.000639
Epoch: 037 | Train loss: 0.9891 | Train acc: 50.71% | Val loss: 0.9860 | Val acc: 50.89% | LR: 0.000633
Epoch: 038 | Train loss: 0.9894 | Train acc: 50.38% | Val loss: 0.9819 | Val acc: 51.12% | LR: 0.000628
Epoch: 039 | Train loss: 0.9858 | Train acc: 51.11% | Val loss: 0.9735 | Val acc: 51.64% | LR: 0.000622
Epoch: 040 | Train loss: 0.9946 | Train acc: 50.22% | Val loss: 0.9758 | Val acc: 51.50% | LR: 0.000616
Epoch: 041 | Train loss: 0.9830 | Train acc: 51.05% | Val loss: 0.9822 | Val acc: 51.12% | LR: 0.000610
Epoch: 042 | Train loss: 0.9888 | Train acc: 50.60% | Val loss: 0.9840 | Val acc: 51.22% | LR: 0.000604
Epoch: 043 | Train loss: 0.9897 | Train acc: 50.64% | Val loss: 0.9820 | Val acc: 51.30% | LR: 0.000598
Epoch: 044 | Train loss: 0.9844 | Train acc: 50.82% | Val loss: 0.9786 | Val acc: 51.32% | LR: 0.000592
Epoch: 045 | Train loss: 0.9897 | Train acc: 50.38% | Val loss: 0.9884 | Val acc: 51.10% | LR: 0.000585
Epoch: 046 | Train loss: 0.9914 | Train acc: 50.43% | Val loss: 0.9836 | Val acc: 51.28% | LR: 0.000579
Epoch: 047 | Train loss: 0.9794 | Train acc: 51.24% | Val loss: 0.9803 | Val acc: 51.28% | LR: 0.000572
Epoch: 048 | Train loss: 0.9881 | Train acc: 50.64% | Val loss: 0.9846 | Val acc: 51.32% | LR: 0.000566
Epoch: 049 | Train loss: 0.9866 | Train acc: 50.71% | Val loss: 0.9747 | Val acc: 51.55% | LR: 0.000559
Epoch: 050 | Train loss: 0.9795 | Train acc: 51.36% | Val loss: 0.9735 | Val acc: 51.56% | LR: 0.000552
Epoch: 051 | Train loss: 0.9862 | Train acc: 50.82% | Val loss: 0.9726 | Val acc: 51.46% | LR: 0.000545
Epoch: 052 | Train loss: 0.9854 | Train acc: 50.86% | Val loss: 0.9791 | Val acc: 51.21% | LR: 0.000538
Epoch: 053 | Train loss: 0.9812 | Train acc: 51.13% | Val loss: 0.9918 | Val acc: 51.21% | LR: 0.000531
Epoch: 054 | Train loss: 0.9765 | Train acc: 51.42% | Val loss: 0.9767 | Val acc: 51.36% | LR: 0.000524
Epoch: 055 | Train loss: 0.9918 | Train acc: 50.52% | Val loss: 0.9825 | Val acc: 51.02% | LR: 0.000517
Epoch: 056 | Train loss: 0.9925 | Train acc: 50.39% | Val loss: 0.9818 | Val acc: 51.02% | LR: 0.000510
Epoch: 057 | Train loss: 0.9887 | Train acc: 50.64% | Val loss: 0.9834 | Val acc: 51.00% | LR: 0.000503
Epoch: 058 | Train loss: 0.9888 | Train acc: 50.66% | Val loss: 0.9846 | Val acc: 51.06% | LR: 0.000495
Epoch: 059 | Train loss: 0.9871 | Train acc: 50.74% | Val loss: 0.9848 | Val acc: 50.96% | LR: 0.000488
Epoch: 060 | Train loss: 0.9806 | Train acc: 51.04% | Val loss: 0.9789 | Val acc: 51.31% | LR: 0.000481
Epoch: 061 | Train loss: 0.9848 | Train acc: 50.84% | Val loss: 0.9777 | Val acc: 51.31% | LR: 0.000473
Epoch: 062 | Train loss: 0.9851 | Train acc: 50.81% | Val loss: 0.9794 | Val acc: 51.19% | LR: 0.000466
Epoch: 063 | Train loss: 0.9876 | Train acc: 50.67% | Val loss: 0.9804 | Val acc: 51.23% | LR: 0.000458
Epoch: 064 | Train loss: 0.9879 | Train acc: 50.69% | Val loss: 0.9818 | Val acc: 51.17% | LR: 0.000450
Epoch: 065 | Train loss: 0.9774 | Train acc: 51.31% | Val loss: 0.9801 | Val acc: 51.27% | LR: 0.000443
Epoch: 066 | Train loss: 0.9865 | Train acc: 50.69% | Val loss: 0.9796 | Val acc: 51.37% | LR: 0.000435
Epoch: 067 | Train loss: 0.9812 | Train acc: 50.96% | Val loss: 0.9841 | Val acc: 51.17% | LR: 0.000427
Epoch: 068 | Train loss: 0.9804 | Train acc: 51.16% | Val loss: 0.9836 | Val acc: 51.28% | LR: 0.000420
Epoch: 069 | Train loss: 0.9864 | Train acc: 50.72% | Val loss: 0.9972 | Val acc: 50.91% | LR: 0.000412
Epoch: 070 | Train loss: 0.9830 | Train acc: 51.12% | Val loss: 1.0132 | Val acc: 50.29% | LR: 0.000404
Epoch: 071 | Train loss: 0.9876 | Train acc: 50.74% | Val loss: 1.0423 | Val acc: 48.21% | LR: 0.000396
Epoch: 072 | Train loss: 0.9864 | Train acc: 50.92% | Val loss: 1.0373 | Val acc: 48.71% | LR: 0.000389
Epoch: 073 | Train loss: 0.9740 | Train acc: 51.81% | Val loss: 1.0229 | Val acc: 49.01% | LR: 0.000381
Epoch: 074 | Train loss: 0.9793 | Train acc: 51.33% | Val loss: 1.0107 | Val acc: 49.31% | LR: 0.000373
Epoch: 075 | Train loss: 0.9846 | Train acc: 51.18% | Val loss: 1.0008 | Val acc: 50.35% | LR: 0.000365
Epoch: 076 | Train loss: 0.9843 | Train acc: 50.84% | Val loss: 1.0002 | Val acc: 50.65% | LR: 0.000357
Epoch: 077 | Train loss: 0.9822 | Train acc: 51.03% | Val loss: 1.0027 | Val acc: 50.59% | LR: 0.000350
Epoch: 078 | Train loss: 0.9857 | Train acc: 50.67% | Val loss: 1.0196 | Val acc: 50.39% | LR: 0.000342
Epoch: 079 | Train loss: 0.9845 | Train acc: 51.14% | Val loss: 1.0039 | Val acc: 50.33% | LR: 0.000334
Epoch: 080 | Train loss: 0.9895 | Train acc: 50.60% | Val loss: 1.0022 | Val acc: 50.32% | LR: 0.000326
Epoch: 081 | Train loss: 0.9896 | Train acc: 50.59% | Val loss: 0.9997 | Val acc: 50.47% | LR: 0.000319
Epoch: 082 | Train loss: 0.9836 | Train acc: 50.95% | Val loss: 0.9988 | Val acc: 50.46% | LR: 0.000311
Epoch: 083 | Train loss: 0.9765 | Train acc: 51.37% | Val loss: 1.0030 | Val acc: 50.35% | LR: 0.000303
Epoch: 084 | Train loss: 0.9917 | Train acc: 51.03% | Val loss: 1.0039 | Val acc: 50.30% | LR: 0.000296
Epoch: 085 | Train loss: 0.9894 | Train acc: 50.60% | Val loss: 1.0041 | Val acc: 50.36% | LR: 0.000288
Epoch: 086 | Train loss: 0.9842 | Train acc: 50.86% | Val loss: 1.0017 | Val acc: 50.28% | LR: 0.000281
Epoch: 087 | Train loss: 0.9867 | Train acc: 50.69% | Val loss: 1.0085 | Val acc: 50.37% | LR: 0.000273
Epoch: 088 | Train loss: 0.9830 | Train acc: 51.01% | Val loss: 0.9991 | Val acc: 50.63% | LR: 0.000266
Epoch: 089 | Train loss: 0.9768 | Train acc: 51.27% | Val loss: 1.0043 | Val acc: 50.62% | LR: 0.000258
Epoch: 090 | Train loss: 0.9880 | Train acc: 50.58% | Val loss: 0.9964 | Val acc: 50.66% | LR: 0.000251
Epoch: 091 | Train loss: 0.9818 | Train acc: 51.02% | Val loss: 1.0022 | Val acc: 50.48% | LR: 0.000243
Epoch: 092 | Train loss: 0.9848 | Train acc: 50.85% | Val loss: 1.0032 | Val acc: 50.82% | LR: 0.000236
Epoch: 093 | Train loss: 0.9854 | Train acc: 50.81% | Val loss: 0.9942 | Val acc: 50.79% | LR: 0.000229
Epoch: 094 | Train loss: 0.9830 | Train acc: 50.99% | Val loss: 0.9970 | Val acc: 50.68% | LR: 0.000222
Epoch: 095 | Train loss: 0.9853 | Train acc: 50.66% | Val loss: 0.9989 | Val acc: 50.63% | LR: 0.000215
Epoch: 096 | Train loss: 0.9839 | Train acc: 50.91% | Val loss: 0.9928 | Val acc: 50.65% | LR: 0.000208
Epoch: 097 | Train loss: 0.9860 | Train acc: 50.73% | Val loss: 1.0010 | Val acc: 50.75% | LR: 0.000201
Epoch: 098 | Train loss: 0.9821 | Train acc: 51.06% | Val loss: 1.0021 | Val acc: 50.94% | LR: 0.000194
Epoch: 099 | Train loss: 0.9775 | Train acc: 51.18% | Val loss: 1.2661 | Val acc: 50.69% | LR: 0.000187
Epoch: 100 | Train loss: 0.9889 | Train acc: 50.61% | Val loss: 0.9988 | Val acc: 50.78% | LR: 0.000180
Epoch: 101 | Train loss: 0.9733 | Train acc: 51.51% | Val loss: 0.9978 | Val acc: 50.87% | LR: 0.000174
Epoch: 102 | Train loss: 0.9796 | Train acc: 51.16% | Val loss: 0.9958 | Val acc: 50.88% | LR: 0.000167
Epoch: 103 | Train loss: 0.9778 | Train acc: 51.24% | Val loss: 0.9987 | Val acc: 50.78% | LR: 0.000161
Epoch: 104 | Train loss: 0.9842 | Train acc: 50.82% | Val loss: 0.9988 | Val acc: 50.74% | LR: 0.000154
Epoch: 105 | Train loss: 0.9747 | Train acc: 51.53% | Val loss: 1.0014 | Val acc: 50.88% | LR: 0.000148
Epoch: 106 | Train loss: 0.9858 | Train acc: 50.72% | Val loss: 1.0006 | Val acc: 50.69% | LR: 0.000142
Epoch: 107 | Train loss: 0.9917 | Train acc: 50.41% | Val loss: 0.9974 | Val acc: 50.56% | LR: 0.000136
Epoch: 108 | Train loss: 1.1592 | Train acc: 51.46% | Val loss: 1.0042 | Val acc: 50.55% | LR: 0.000130
Epoch: 109 | Train loss: 0.9834 | Train acc: 50.88% | Val loss: 1.0013 | Val acc: 50.52% | LR: 0.000124
Epoch: 110 | Train loss: 0.9864 | Train acc: 50.82% | Val loss: 1.0026 | Val acc: 50.63% | LR: 0.000118
Epoch: 111 | Train loss: 0.9837 | Train acc: 50.79% | Val loss: 0.9982 | Val acc: 50.65% | LR: 0.000113
Epoch: 112 | Train loss: 0.9871 | Train acc: 50.71% | Val loss: 0.9988 | Val acc: 50.77% | LR: 0.000107
Epoch: 113 | Train loss: 0.9798 | Train acc: 51.25% | Val loss: 1.0083 | Val acc: 50.73% | LR: 0.000102
Epoch: 114 | Train loss: 0.9799 | Train acc: 51.25% | Val loss: 0.9990 | Val acc: 50.81% | LR: 0.000097
Epoch: 115 | Train loss: 0.9813 | Train acc: 50.97% | Val loss: 0.9976 | Val acc: 50.77% | LR: 0.000091
Epoch: 116 | Train loss: 0.9911 | Train acc: 50.46% | Val loss: 1.1201 | Val acc: 50.77% | LR: 0.000086
Epoch: 117 | Train loss: 0.9833 | Train acc: 50.97% | Val loss: 0.9990 | Val acc: 50.82% | LR: 0.000081
Epoch: 118 | Train loss: 0.9815 | Train acc: 51.05% | Val loss: 0.9953 | Val acc: 50.89% | LR: 0.000077
Epoch: 119 | Train loss: 0.9848 | Train acc: 50.89% | Val loss: 0.9957 | Val acc: 50.87% | LR: 0.000072
Epoch: 120 | Train loss: 0.9853 | Train acc: 50.79% | Val loss: 0.9952 | Val acc: 50.83% | LR: 0.000068
Epoch: 121 | Train loss: 0.9832 | Train acc: 50.79% | Val loss: 0.9956 | Val acc: 50.87% | LR: 0.000063
Epoch: 122 | Train loss: 0.9860 | Train acc: 50.62% | Val loss: 0.9958 | Val acc: 50.89% | LR: 0.000059
Epoch: 123 | Train loss: 0.9873 | Train acc: 50.62% | Val loss: 0.9963 | Val acc: 50.85% | LR: 0.000055
Epoch: 124 | Train loss: 0.9799 | Train acc: 50.97% | Val loss: 0.9961 | Val acc: 50.87% | LR: 0.000051
Epoch: 125 | Train loss: 0.9751 | Train acc: 51.42% | Val loss: 0.9960 | Val acc: 50.85% | LR: 0.000047
Epoch: 126 | Train loss: 0.9895 | Train acc: 50.43% | Val loss: 0.9964 | Val acc: 50.90% | LR: 0.000043
Epoch: 127 | Train loss: 0.9894 | Train acc: 50.52% | Val loss: 0.9965 | Val acc: 50.90% | LR: 0.000040
Epoch: 128 | Train loss: 0.9760 | Train acc: 51.32% | Val loss: 0.9962 | Val acc: 50.90% | LR: 0.000036
Epoch: 129 | Train loss: 0.9703 | Train acc: 51.59% | Val loss: 0.9960 | Val acc: 50.91% | LR: 0.000033
Epoch: 130 | Train loss: 0.9892 | Train acc: 50.44% | Val loss: 0.9962 | Val acc: 50.91% | LR: 0.000030
Epoch: 131 | Train loss: 0.9831 | Train acc: 50.80% | Val loss: 0.9960 | Val acc: 50.91% | LR: 0.000027
Epoch: 132 | Train loss: 0.9869 | Train acc: 50.64% | Val loss: 0.9960 | Val acc: 50.91% | LR: 0.000024
Epoch: 133 | Train loss: 0.9744 | Train acc: 51.43% | Val loss: 0.9960 | Val acc: 50.91% | LR: 0.000022
Epoch: 134 | Train loss: 0.9809 | Train acc: 50.99% | Val loss: 0.9956 | Val acc: 50.91% | LR: 0.000019
Epoch: 135 | Train loss: 0.9805 | Train acc: 50.99% | Val loss: 0.9959 | Val acc: 50.90% | LR: 0.000017
Epoch: 136 | Train loss: 0.9904 | Train acc: 50.29% | Val loss: 0.9958 | Val acc: 50.87% | LR: 0.000015
Epoch: 137 | Train loss: 0.9818 | Train acc: 50.91% | Val loss: 0.9959 | Val acc: 50.88% | LR: 0.000013
Epoch: 138 | Train loss: 0.9790 | Train acc: 51.10% | Val loss: 0.9957 | Val acc: 50.84% | LR: 0.000011
Epoch: 139 | Train loss: 0.9795 | Train acc: 51.09% | Val loss: 0.9956 | Val acc: 50.84% | LR: 0.000009
Epoch: 140 | Train loss: 0.9771 | Train acc: 51.36% | Val loss: 0.9956 | Val acc: 50.86% | LR: 0.000008
Epoch: 141 | Train loss: 0.9886 | Train acc: 50.46% | Val loss: 0.9956 | Val acc: 50.86% | LR: 0.000006
Epoch: 142 | Train loss: 0.9796 | Train acc: 51.09% | Val loss: 0.9956 | Val acc: 50.86% | LR: 0.000005
Epoch: 143 | Train loss: 0.9717 | Train acc: 51.53% | Val loss: 0.9956 | Val acc: 50.86% | LR: 0.000004
Epoch: 144 | Train loss: 0.9847 | Train acc: 50.73% | Val loss: 0.9956 | Val acc: 50.86% | LR: 0.000003
Epoch: 145 | Train loss: 0.9854 | Train acc: 50.73% | Val loss: 0.9957 | Val acc: 50.86% | LR: 0.000002
Epoch: 146 | Train loss: 0.9742 | Train acc: 51.36% | Val loss: 0.9956 | Val acc: 50.82% | LR: 0.000002
Epoch: 147 | Train loss: 0.9728 | Train acc: 51.45% | Val loss: 0.9956 | Val acc: 50.82% | LR: 0.000001
Epoch: 148 | Train loss: 0.9808 | Train acc: 51.00% | Val loss: 0.9957 | Val acc: 50.82% | LR: 0.000001
Epoch: 149 | Train loss: 0.9781 | Train acc: 51.27% | Val loss: 0.9957 | Val acc: 50.82% | LR: 0.000001

[I 2025-09-23 02:08:49,036] Trial 12 finished with value: 0.5452592611312866 and parameters: {'lr': 0.0007450825408658105, 'hidden_size': 254, 'dropout': 0.13377228706889238, 'weight_decay': 0.034847127816064916}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 0.9954 | Train acc: 50.61% | Val loss: 0.9960 | Val acc: 50.10% | LR: 0.001715
Epoch: 001 | Train loss: 0.9921 | Train acc: 50.97% | Val loss: 0.9910 | Val acc: 50.20% | LR: 0.001714
Epoch: 002 | Train loss: 0.9907 | Train acc: 50.99% | Val loss: 1.0304 | Val acc: 49.09% | LR: 0.001714
Epoch: 003 | Train loss: 0.9985 | Train acc: 51.04% | Val loss: 0.9636 | Val acc: 54.32% | LR: 0.001712
Epoch: 004 | Train loss: 1.0006 | Train acc: 50.08% | Val loss: 0.9592 | Val acc: 53.95% | LR: 0.001711
Epoch: 005 | Train loss: 0.9981 | Train acc: 50.44% | Val loss: 0.9591 | Val acc: 54.13% | LR: 0.001708
Epoch: 006 | Train loss: 0.9974 | Train acc: 50.73% | Val loss: 0.9539 | Val acc: 54.66% | LR: 0.001706
Epoch: 007 | Train loss: 0.9951 | Train acc: 50.50% | Val loss: 0.9544 | Val acc: 54.95% | LR: 0.001703
Epoch: 008 | Train loss: 0.9932 | Train acc: 50.53% | Val loss: 0.9544 | Val acc: 54.68% | LR: 0.001700
Epoch: 009 | Train loss: 0.9905 | Train acc: 51.63% | Val loss: 0.9654 | Val acc: 54.24% | LR: 0.001697
Epoch: 010 | Train loss: 0.9885 | Train acc: 50.92% | Val loss: 0.9661 | Val acc: 53.12% | LR: 0.001693
Epoch: 011 | Train loss: 0.9870 | Train acc: 51.02% | Val loss: 0.9796 | Val acc: 51.62% | LR: 0.001688
Epoch: 012 | Train loss: 0.9882 | Train acc: 51.16% | Val loss: 0.9840 | Val acc: 50.67% | LR: 0.001684
Epoch: 013 | Train loss: 0.9935 | Train acc: 50.84% | Val loss: 0.9871 | Val acc: 50.48% | LR: 0.001679
Epoch: 014 | Train loss: 0.9887 | Train acc: 50.93% | Val loss: 0.9892 | Val acc: 50.15% | LR: 0.001673
Epoch: 015 | Train loss: 0.9891 | Train acc: 50.97% | Val loss: 1.0155 | Val acc: 49.24% | LR: 0.001668
Epoch: 016 | Train loss: 0.9911 | Train acc: 50.33% | Val loss: 0.9991 | Val acc: 49.95% | LR: 0.001661
Epoch: 017 | Train loss: 0.9899 | Train acc: 50.97% | Val loss: 0.9919 | Val acc: 51.11% | LR: 0.001655
Epoch: 018 | Train loss: 0.9866 | Train acc: 50.87% | Val loss: 0.9990 | Val acc: 50.01% | LR: 0.001648
Epoch: 019 | Train loss: 0.9884 | Train acc: 51.04% | Val loss: 1.0486 | Val acc: 47.44% | LR: 0.001641
Epoch: 020 | Train loss: 0.9859 | Train acc: 51.04% | Val loss: 0.9963 | Val acc: 50.69% | LR: 0.001634
Epoch: 021 | Train loss: 0.9861 | Train acc: 50.88% | Val loss: 0.9914 | Val acc: 50.28% | LR: 0.001626
Epoch: 022 | Train loss: 0.9861 | Train acc: 50.58% | Val loss: 1.0024 | Val acc: 49.91% | LR: 0.001618
Epoch: 023 | Train loss: 1.0044 | Train acc: 50.83% | Val loss: 1.2354 | Val acc: 49.75% | LR: 0.001609
Epoch: 024 | Train loss: 1.0027 | Train acc: 50.47% | Val loss: 0.9814 | Val acc: 53.76% | LR: 0.001600
Epoch: 025 | Train loss: 1.0012 | Train acc: 50.48% | Val loss: 0.9580 | Val acc: 54.20% | LR: 0.001591
Epoch: 026 | Train loss: 0.9997 | Train acc: 49.88% | Val loss: 0.9870 | Val acc: 55.03% | LR: 0.001582
Epoch: 027 | Train loss: 0.9995 | Train acc: 50.37% | Val loss: 0.9805 | Val acc: 54.58% | LR: 0.001572
Epoch: 028 | Train loss: 1.0087 | Train acc: 49.80% | Val loss: 1.0393 | Val acc: 45.97% | LR: 0.001562
Epoch: 029 | Train loss: 1.0032 | Train acc: 49.94% | Val loss: 1.0026 | Val acc: 45.97% | LR: 0.001552
Epoch: 030 | Train loss: 0.9992 | Train acc: 50.51% | Val loss: 0.9959 | Val acc: 54.07% | LR: 0.001541
Epoch: 031 | Train loss: 0.9994 | Train acc: 49.87% | Val loss: 1.0619 | Val acc: 45.95% | LR: 0.001530
Epoch: 032 | Train loss: 0.9959 | Train acc: 50.70% | Val loss: 1.0045 | Val acc: 45.95% | LR: 0.001519
Epoch: 033 | Train loss: 0.9983 | Train acc: 50.41% | Val loss: 0.9653 | Val acc: 54.05% | LR: 0.001507
Epoch: 034 | Train loss: 0.9954 | Train acc: 50.42% | Val loss: 0.9970 | Val acc: 54.32% | LR: 0.001495
Epoch: 035 | Train loss: 0.9948 | Train acc: 50.76% | Val loss: 0.9814 | Val acc: 54.05% | LR: 0.001483
Epoch: 036 | Train loss: 1.0026 | Train acc: 49.29% | Val loss: 1.0070 | Val acc: 45.95% | LR: 0.001471
Epoch: 037 | Train loss: 0.9987 | Train acc: 49.97% | Val loss: 1.0317 | Val acc: 45.95% | LR: 0.001458
Epoch: 038 | Train loss: 0.9962 | Train acc: 50.72% | Val loss: 0.9738 | Val acc: 54.05% | LR: 0.001445
Epoch: 039 | Train loss: 0.9963 | Train acc: 50.39% | Val loss: 1.0475 | Val acc: 45.95% | LR: 0.001432
Epoch: 040 | Train loss: 0.9960 | Train acc: 50.48% | Val loss: 0.9812 | Val acc: 54.11% | LR: 0.001418
Epoch: 041 | Train loss: 0.9912 | Train acc: 50.91% | Val loss: 1.0188 | Val acc: 45.95% | LR: 0.001404
Epoch: 042 | Train loss: 0.9980 | Train acc: 50.20% | Val loss: 1.0078 | Val acc: 45.95% | LR: 0.001391
Epoch: 043 | Train loss: 0.9985 | Train acc: 50.01% | Val loss: 0.9997 | Val acc: 50.15% | LR: 0.001376
Epoch: 044 | Train loss: 0.9937 | Train acc: 50.81% | Val loss: 1.0062 | Val acc: 46.56% | LR: 0.001362
Epoch: 045 | Train loss: 0.9937 | Train acc: 50.69% | Val loss: 0.9942 | Val acc: 52.84% | LR: 0.001347
Epoch: 046 | Train loss: 0.9920 | Train acc: 50.70% | Val loss: 1.0394 | Val acc: 45.95% | LR: 0.001332
Epoch: 047 | Train loss: 0.9924 | Train acc: 50.48% | Val loss: 0.9416 | Val acc: 54.05% | LR: 0.001317
Epoch: 048 | Train loss: 1.0026 | Train acc: 49.89% | Val loss: 1.0317 | Val acc: 45.95% | LR: 0.001302
Epoch: 049 | Train loss: 0.9925 | Train acc: 50.72% | Val loss: 1.0169 | Val acc: 46.05% | LR: 0.001287
Epoch: 050 | Train loss: 0.9927 | Train acc: 50.64% | Val loss: 0.9993 | Val acc: 49.54% | LR: 0.001271
Epoch: 051 | Train loss: 0.9904 | Train acc: 51.01% | Val loss: 0.9695 | Val acc: 51.73% | LR: 0.001255
Epoch: 052 | Train loss: 0.9915 | Train acc: 50.49% | Val loss: 1.0015 | Val acc: 49.84% | LR: 0.001239
Epoch: 053 | Train loss: 0.9885 | Train acc: 50.73% | Val loss: 1.0423 | Val acc: 47.96% | LR: 0.001223
Epoch: 054 | Train loss: 0.9931 | Train acc: 50.44% | Val loss: 0.9661 | Val acc: 51.75% | LR: 0.001207
Epoch: 055 | Train loss: 0.9855 | Train acc: 50.98% | Val loss: 1.0026 | Val acc: 49.42% | LR: 0.001190
Epoch: 056 | Train loss: 0.9861 | Train acc: 51.06% | Val loss: 1.0187 | Val acc: 48.04% | LR: 0.001174
Epoch: 057 | Train loss: 0.9935 | Train acc: 50.62% | Val loss: 1.0591 | Val acc: 46.21% | LR: 0.001157
Epoch: 058 | Train loss: 0.9839 | Train acc: 50.98% | Val loss: 0.9474 | Val acc: 53.26% | LR: 0.001140
Epoch: 059 | Train loss: 0.9902 | Train acc: 50.75% | Val loss: 0.9643 | Val acc: 52.64% | LR: 0.001123
Epoch: 060 | Train loss: 0.9810 | Train acc: 51.52% | Val loss: 0.9756 | Val acc: 51.91% | LR: 0.001106
Epoch: 061 | Train loss: 0.9837 | Train acc: 51.26% | Val loss: 0.9655 | Val acc: 52.26% | LR: 0.001089
Epoch: 062 | Train loss: 0.9810 | Train acc: 52.03% | Val loss: 0.9954 | Val acc: 50.15% | LR: 0.001071
Epoch: 063 | Train loss: 0.9894 | Train acc: 51.10% | Val loss: 1.0058 | Val acc: 49.82% | LR: 0.001054
Epoch: 064 | Train loss: 0.9862 | Train acc: 50.90% | Val loss: 0.9695 | Val acc: 51.90% | LR: 0.001036
Epoch: 065 | Train loss: 0.9872 | Train acc: 50.97% | Val loss: 0.9668 | Val acc: 52.36% | LR: 0.001019
Epoch: 066 | Train loss: 0.9960 | Train acc: 50.44% | Val loss: 0.9747 | Val acc: 52.27% | LR: 0.001001
Epoch: 067 | Train loss: 0.9869 | Train acc: 50.74% | Val loss: 0.9705 | Val acc: 52.09% | LR: 0.000983
Epoch: 068 | Train loss: 0.9822 | Train acc: 51.27% | Val loss: 0.9635 | Val acc: 52.78% | LR: 0.000966
Epoch: 069 | Train loss: 0.9928 | Train acc: 50.44% | Val loss: 0.9678 | Val acc: 52.47% | LR: 0.000948
Epoch: 070 | Train loss: 0.9808 | Train acc: 51.04% | Val loss: 0.9743 | Val acc: 51.87% | LR: 0.000930
Epoch: 071 | Train loss: 0.9819 | Train acc: 51.07% | Val loss: 0.9552 | Val acc: 53.54% | LR: 0.000912
Epoch: 072 | Train loss: 0.9873 | Train acc: 50.96% | Val loss: 0.9729 | Val acc: 52.61% | LR: 0.000894
Epoch: 073 | Train loss: 0.9852 | Train acc: 50.88% | Val loss: 1.0090 | Val acc: 49.66% | LR: 0.000876
Epoch: 074 | Train loss: 0.9875 | Train acc: 50.87% | Val loss: 1.0074 | Val acc: 49.79% | LR: 0.000858
Epoch: 075 | Train loss: 0.9797 | Train acc: 51.44% | Val loss: 0.9984 | Val acc: 50.31% | LR: 0.000840
Epoch: 076 | Train loss: 0.9848 | Train acc: 51.09% | Val loss: 0.9811 | Val acc: 51.36% | LR: 0.000822
Epoch: 077 | Train loss: 0.9798 | Train acc: 51.48% | Val loss: 0.9745 | Val acc: 51.77% | LR: 0.000804
Epoch: 078 | Train loss: 0.9865 | Train acc: 50.95% | Val loss: 0.9816 | Val acc: 51.43% | LR: 0.000786
Epoch: 079 | Train loss: 0.9781 | Train acc: 51.37% | Val loss: 0.9779 | Val acc: 51.57% | LR: 0.000769
Epoch: 080 | Train loss: 0.9829 | Train acc: 51.00% | Val loss: 0.9701 | Val acc: 51.95% | LR: 0.000751
Epoch: 081 | Train loss: 0.9876 | Train acc: 50.81% | Val loss: 0.9863 | Val acc: 51.08% | LR: 0.000733
Epoch: 082 | Train loss: 0.9850 | Train acc: 50.99% | Val loss: 0.9598 | Val acc: 52.80% | LR: 0.000715
Epoch: 083 | Train loss: 0.9885 | Train acc: 50.81% | Val loss: 0.9748 | Val acc: 52.11% | LR: 0.000698
Epoch: 084 | Train loss: 0.9803 | Train acc: 51.27% | Val loss: 0.9771 | Val acc: 51.77% | LR: 0.000680
Epoch: 085 | Train loss: 0.9930 | Train acc: 50.92% | Val loss: 1.0158 | Val acc: 48.53% | LR: 0.000662
Epoch: 086 | Train loss: 0.9993 | Train acc: 50.22% | Val loss: 1.0176 | Val acc: 48.40% | LR: 0.000645
Epoch: 087 | Train loss: 0.9897 | Train acc: 51.06% | Val loss: 0.9856 | Val acc: 51.48% | LR: 0.000628
Epoch: 088 | Train loss: 0.9810 | Train acc: 51.46% | Val loss: 0.9815 | Val acc: 51.52% | LR: 0.000610
Epoch: 089 | Train loss: 0.9876 | Train acc: 50.68% | Val loss: 0.9960 | Val acc: 50.41% | LR: 0.000593
Epoch: 090 | Train loss: 0.9818 | Train acc: 51.32% | Val loss: 1.0063 | Val acc: 49.65% | LR: 0.000576
Epoch: 091 | Train loss: 0.9802 | Train acc: 51.13% | Val loss: 1.0311 | Val acc: 48.10% | LR: 0.000559
Epoch: 092 | Train loss: 0.9892 | Train acc: 50.63% | Val loss: 0.9853 | Val acc: 51.25% | LR: 0.000543
Epoch: 093 | Train loss: 0.9890 | Train acc: 50.75% | Val loss: 0.9940 | Val acc: 50.54% | LR: 0.000526
Epoch: 094 | Train loss: 0.9794 | Train acc: 51.16% | Val loss: 0.9895 | Val acc: 50.64% | LR: 0.000509
Epoch: 095 | Train loss: 0.9801 | Train acc: 51.18% | Val loss: 1.0032 | Val acc: 49.91% | LR: 0.000493
Epoch: 096 | Train loss: 0.9722 | Train acc: 51.78% | Val loss: 0.9837 | Val acc: 51.31% | LR: 0.000477
Epoch: 097 | Train loss: 0.9786 | Train acc: 51.42% | Val loss: 0.9876 | Val acc: 51.47% | LR: 0.000461
Epoch: 098 | Train loss: 0.9865 | Train acc: 50.96% | Val loss: 0.9740 | Val acc: 51.78% | LR: 0.000445
Epoch: 099 | Train loss: 0.9815 | Train acc: 51.27% | Val loss: 0.9809 | Val acc: 51.43% | LR: 0.000430
Epoch: 100 | Train loss: 0.9820 | Train acc: 51.16% | Val loss: 0.9804 | Val acc: 51.45% | LR: 0.000414
Epoch: 101 | Train loss: 0.9826 | Train acc: 51.06% | Val loss: 0.9853 | Val acc: 51.21% | LR: 0.000399
Epoch: 102 | Train loss: 0.9767 | Train acc: 51.62% | Val loss: 0.9874 | Val acc: 51.15% | LR: 0.000384
Epoch: 103 | Train loss: 0.9823 | Train acc: 51.07% | Val loss: 0.9793 | Val acc: 51.34% | LR: 0.000369
Epoch: 104 | Train loss: 0.9848 | Train acc: 50.90% | Val loss: 0.9852 | Val acc: 51.09% | LR: 0.000354
Epoch: 105 | Train loss: 0.9779 | Train acc: 51.38% | Val loss: 0.9796 | Val acc: 51.50% | LR: 0.000340
Epoch: 106 | Train loss: 0.9760 | Train acc: 51.48% | Val loss: 0.9817 | Val acc: 51.12% | LR: 0.000326
Epoch: 107 | Train loss: 0.9847 | Train acc: 50.94% | Val loss: 0.9852 | Val acc: 51.17% | LR: 0.000312
Epoch: 108 | Train loss: 0.9837 | Train acc: 51.06% | Val loss: 0.9753 | Val acc: 51.78% | LR: 0.000298
Epoch: 109 | Train loss: 0.9791 | Train acc: 51.25% | Val loss: 0.9761 | Val acc: 51.52% | LR: 0.000285
Epoch: 110 | Train loss: 0.9821 | Train acc: 51.01% | Val loss: 0.9813 | Val acc: 51.29% | LR: 0.000271
Epoch: 111 | Train loss: 0.9780 | Train acc: 51.29% | Val loss: 0.9776 | Val acc: 51.49% | LR: 0.000258
Epoch: 112 | Train loss: 0.9862 | Train acc: 50.70% | Val loss: 0.9790 | Val acc: 51.20% | LR: 0.000246
Epoch: 113 | Train loss: 0.9802 | Train acc: 51.21% | Val loss: 0.9825 | Val acc: 51.23% | LR: 0.000233
Epoch: 114 | Train loss: 0.9788 | Train acc: 51.19% | Val loss: 0.9824 | Val acc: 51.25% | LR: 0.000221
Epoch: 115 | Train loss: 0.9803 | Train acc: 51.21% | Val loss: 0.9776 | Val acc: 51.35% | LR: 0.000209
Epoch: 116 | Train loss: 0.9751 | Train acc: 51.67% | Val loss: 0.9775 | Val acc: 51.49% | LR: 0.000198
Epoch: 117 | Train loss: 0.9764 | Train acc: 51.48% | Val loss: 0.9835 | Val acc: 51.19% | LR: 0.000186
Epoch: 118 | Train loss: 0.9869 | Train acc: 50.77% | Val loss: 0.9754 | Val acc: 51.68% | LR: 0.000175
Epoch: 119 | Train loss: 0.9907 | Train acc: 50.44% | Val loss: 0.9799 | Val acc: 51.41% | LR: 0.000165
Epoch: 120 | Train loss: 0.9774 | Train acc: 51.42% | Val loss: 0.9760 | Val acc: 51.54% | LR: 0.000154
Epoch: 121 | Train loss: 0.9774 | Train acc: 51.30% | Val loss: 0.9786 | Val acc: 51.38% | LR: 0.000144
Epoch: 122 | Train loss: 0.9809 | Train acc: 51.21% | Val loss: 0.9755 | Val acc: 51.56% | LR: 0.000134
Epoch: 123 | Train loss: 0.9824 | Train acc: 51.18% | Val loss: 0.9756 | Val acc: 51.60% | LR: 0.000125
Epoch: 124 | Train loss: 0.9821 | Train acc: 51.04% | Val loss: 0.9766 | Val acc: 51.46% | LR: 0.000116
Epoch: 125 | Train loss: 0.9827 | Train acc: 50.99% | Val loss: 0.9762 | Val acc: 51.42% | LR: 0.000107
Epoch: 126 | Train loss: 0.9783 | Train acc: 51.33% | Val loss: 0.9787 | Val acc: 51.34% | LR: 0.000099
Epoch: 127 | Train loss: 0.9810 | Train acc: 51.08% | Val loss: 0.9791 | Val acc: 51.38% | LR: 0.000090
Epoch: 128 | Train loss: 0.9794 | Train acc: 51.25% | Val loss: 0.9779 | Val acc: 51.38% | LR: 0.000083
Epoch: 129 | Train loss: 0.9797 | Train acc: 51.16% | Val loss: 0.9789 | Val acc: 51.26% | LR: 0.000075
Epoch: 130 | Train loss: 0.9711 | Train acc: 51.69% | Val loss: 0.9794 | Val acc: 51.28% | LR: 0.000068
Epoch: 131 | Train loss: 0.9869 | Train acc: 50.82% | Val loss: 0.9781 | Val acc: 51.28% | LR: 0.000061
Epoch: 132 | Train loss: 0.9843 | Train acc: 50.90% | Val loss: 0.9784 | Val acc: 51.24% | LR: 0.000055
Epoch: 133 | Train loss: 0.9862 | Train acc: 50.91% | Val loss: 0.9781 | Val acc: 51.26% | LR: 0.000049
Epoch: 134 | Train loss: 0.9772 | Train acc: 51.34% | Val loss: 0.9787 | Val acc: 51.38% | LR: 0.000043
Epoch: 135 | Train loss: 0.9762 | Train acc: 51.52% | Val loss: 0.9785 | Val acc: 51.30% | LR: 0.000038
Epoch: 136 | Train loss: 0.9816 | Train acc: 51.16% | Val loss: 0.9779 | Val acc: 51.36% | LR: 0.000033
Epoch: 137 | Train loss: 0.9776 | Train acc: 51.34% | Val loss: 0.9776 | Val acc: 51.34% | LR: 0.000028
Epoch: 138 | Train loss: 0.9749 | Train acc: 51.53% | Val loss: 0.9781 | Val acc: 51.32% | LR: 0.000024
Epoch: 139 | Train loss: 0.9764 | Train acc: 51.42% | Val loss: 0.9781 | Val acc: 51.34% | LR: 0.000020
Epoch: 140 | Train loss: 0.9747 | Train acc: 51.62% | Val loss: 0.9779 | Val acc: 51.32% | LR: 0.000016
Epoch: 141 | Train loss: 0.9777 | Train acc: 51.36% | Val loss: 0.9775 | Val acc: 51.34% | LR: 0.000013
Epoch: 142 | Train loss: 0.9828 | Train acc: 51.01% | Val loss: 0.9779 | Val acc: 51.34% | LR: 0.000010
Epoch: 143 | Train loss: 0.9856 | Train acc: 50.82% | Val loss: 0.9779 | Val acc: 51.34% | LR: 0.000008
Epoch: 144 | Train loss: 0.9733 | Train acc: 51.62% | Val loss: 0.9780 | Val acc: 51.34% | LR: 0.000006
Epoch: 145 | Train loss: 0.9704 | Train acc: 51.79% | Val loss: 0.9777 | Val acc: 51.32% | LR: 0.000004
Epoch: 146 | Train loss: 0.9784 | Train acc: 51.37% | Val loss: 0.9778 | Val acc: 51.34% | LR: 0.000003
Epoch: 147 | Train loss: 0.9845 | Train acc: 50.91% | Val loss: 0.9778 | Val acc: 51.34% | LR: 0.000002
Epoch: 148 | Train loss: 0.9839 | Train acc: 51.00% | Val loss: 0.9778 | Val acc: 51.34% | LR: 0.000001
Epoch: 149 | Train loss: 0.9730 | Train acc: 51.53% | Val loss: 0.9778 | Val acc: 51.34% | LR: 0.000001

[I 2025-09-23 02:10:55,525] Trial 13 finished with value: 0.5502573013305664 and parameters: {'lr': 0.0017152437529012739, 'hidden_size': 220, 'dropout': 0.3129122705079912, 'weight_decay': 0.35694560115886725}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.0055 | Train acc: 49.94% | Val loss: 0.9900 | Val acc: 54.48% | LR: 0.001883
Epoch: 001 | Train loss: 0.9999 | Train acc: 50.06% | Val loss: 0.9652 | Val acc: 55.01% | LR: 0.001883
Epoch: 002 | Train loss: 0.9907 | Train acc: 51.21% | Val loss: 0.9811 | Val acc: 51.03% | LR: 0.001882
Epoch: 003 | Train loss: 0.9877 | Train acc: 51.31% | Val loss: 1.0155 | Val acc: 48.65% | LR: 0.001880
Epoch: 004 | Train loss: 0.9918 | Train acc: 50.92% | Val loss: 1.0053 | Val acc: 49.55% | LR: 0.001878
Epoch: 005 | Train loss: 0.9868 | Train acc: 51.48% | Val loss: 1.0032 | Val acc: 49.63% | LR: 0.001876
Epoch: 006 | Train loss: 0.9878 | Train acc: 51.26% | Val loss: 1.0006 | Val acc: 50.00% | LR: 0.001873
Epoch: 007 | Train loss: 0.9938 | Train acc: 50.75% | Val loss: 0.9908 | Val acc: 50.23% | LR: 0.001870
Epoch: 008 | Train loss: 0.9846 | Train acc: 51.47% | Val loss: 1.0522 | Val acc: 47.39% | LR: 0.001867
Epoch: 009 | Train loss: 0.9932 | Train acc: 50.50% | Val loss: 1.0113 | Val acc: 49.52% | LR: 0.001863
Epoch: 010 | Train loss: 0.9952 | Train acc: 50.65% | Val loss: 1.0162 | Val acc: 49.59% | LR: 0.001859
Epoch: 011 | Train loss: 0.9912 | Train acc: 50.86% | Val loss: 0.9995 | Val acc: 50.04% | LR: 0.001854
Epoch: 012 | Train loss: 0.9898 | Train acc: 51.05% | Val loss: 1.0152 | Val acc: 48.51% | LR: 0.001849
Epoch: 013 | Train loss: 0.9917 | Train acc: 50.73% | Val loss: 1.0246 | Val acc: 47.92% | LR: 0.001843
Epoch: 014 | Train loss: 0.9885 | Train acc: 51.29% | Val loss: 1.0734 | Val acc: 49.89% | LR: 0.001837
Epoch: 015 | Train loss: 1.0017 | Train acc: 50.52% | Val loss: 1.0364 | Val acc: 45.74% | LR: 0.001831
Epoch: 016 | Train loss: 1.0013 | Train acc: 50.60% | Val loss: 1.0074 | Val acc: 48.78% | LR: 0.001824
Epoch: 017 | Train loss: 0.9938 | Train acc: 50.74% | Val loss: 1.0029 | Val acc: 49.26% | LR: 0.001817
Epoch: 018 | Train loss: 0.9891 | Train acc: 51.07% | Val loss: 1.0063 | Val acc: 49.15% | LR: 0.001810
Epoch: 019 | Train loss: 0.9925 | Train acc: 50.71% | Val loss: 0.9965 | Val acc: 49.95% | LR: 0.001802
Epoch: 020 | Train loss: 0.9897 | Train acc: 50.70% | Val loss: 1.0084 | Val acc: 49.31% | LR: 0.001794
Epoch: 021 | Train loss: 0.9854 | Train acc: 51.04% | Val loss: 0.9903 | Val acc: 50.18% | LR: 0.001785
Epoch: 022 | Train loss: 0.9880 | Train acc: 50.92% | Val loss: 0.9952 | Val acc: 50.36% | LR: 0.001776
Epoch: 023 | Train loss: 0.9836 | Train acc: 51.03% | Val loss: 1.0163 | Val acc: 49.01% | LR: 0.001767
Epoch: 024 | Train loss: 0.9907 | Train acc: 50.79% | Val loss: 0.9540 | Val acc: 53.45% | LR: 0.001757
Epoch: 025 | Train loss: 0.9923 | Train acc: 50.71% | Val loss: 0.9659 | Val acc: 53.37% | LR: 0.001747
Epoch: 026 | Train loss: 0.9933 | Train acc: 50.88% | Val loss: 0.9718 | Val acc: 52.91% | LR: 0.001737
Epoch: 027 | Train loss: 0.9886 | Train acc: 50.87% | Val loss: 0.9794 | Val acc: 51.94% | LR: 0.001726
Epoch: 028 | Train loss: 0.9889 | Train acc: 50.98% | Val loss: 0.9730 | Val acc: 52.65% | LR: 0.001715
Epoch: 029 | Train loss: 0.9890 | Train acc: 51.06% | Val loss: 0.9644 | Val acc: 52.66% | LR: 0.001704
Epoch: 030 | Train loss: 0.9852 | Train acc: 51.34% | Val loss: 0.9813 | Val acc: 51.70% | LR: 0.001692
Epoch: 031 | Train loss: 0.9912 | Train acc: 50.52% | Val loss: 0.9802 | Val acc: 51.49% | LR: 0.001680
Epoch: 032 | Train loss: 0.9877 | Train acc: 51.01% | Val loss: 0.9872 | Val acc: 51.13% | LR: 0.001667
Epoch: 033 | Train loss: 0.9906 | Train acc: 50.79% | Val loss: 0.9936 | Val acc: 50.66% | LR: 0.001655
Epoch: 034 | Train loss: 0.9848 | Train acc: 50.99% | Val loss: 1.0014 | Val acc: 50.19% | LR: 0.001642
Epoch: 035 | Train loss: 0.9849 | Train acc: 51.14% | Val loss: 1.0007 | Val acc: 49.88% | LR: 0.001628
Epoch: 036 | Train loss: 0.9864 | Train acc: 50.89% | Val loss: 1.0042 | Val acc: 50.30% | LR: 0.001615
Epoch: 037 | Train loss: 0.9854 | Train acc: 51.09% | Val loss: 0.9886 | Val acc: 51.11% | LR: 0.001601
Epoch: 038 | Train loss: 0.9846 | Train acc: 50.98% | Val loss: 1.0043 | Val acc: 49.74% | LR: 0.001587
Epoch: 039 | Train loss: 0.9838 | Train acc: 51.23% | Val loss: 1.0144 | Val acc: 48.38% | LR: 0.001572
Epoch: 040 | Train loss: 0.9894 | Train acc: 50.56% | Val loss: 1.0383 | Val acc: 47.34% | LR: 0.001557
Epoch: 041 | Train loss: 0.9811 | Train acc: 51.23% | Val loss: 1.0345 | Val acc: 47.73% | LR: 0.001542
Epoch: 042 | Train loss: 0.9812 | Train acc: 51.18% | Val loss: 1.0285 | Val acc: 48.38% | LR: 0.001527
Epoch: 043 | Train loss: 0.9848 | Train acc: 51.34% | Val loss: 0.9959 | Val acc: 50.22% | LR: 0.001511
Epoch: 044 | Train loss: 0.9844 | Train acc: 51.17% | Val loss: 1.0007 | Val acc: 49.63% | LR: 0.001495
Epoch: 045 | Train loss: 0.9905 | Train acc: 50.77% | Val loss: 0.9954 | Val acc: 50.30% | LR: 0.001479
Epoch: 046 | Train loss: 0.9858 | Train acc: 51.02% | Val loss: 0.9962 | Val acc: 50.28% | LR: 0.001463
Epoch: 047 | Train loss: 0.9825 | Train acc: 51.29% | Val loss: 0.9786 | Val acc: 51.72% | LR: 0.001447
Epoch: 048 | Train loss: 0.9788 | Train acc: 51.48% | Val loss: 1.0240 | Val acc: 48.48% | LR: 0.001430
Epoch: 049 | Train loss: 0.9847 | Train acc: 50.98% | Val loss: 1.0098 | Val acc: 49.18% | LR: 0.001413
Epoch: 050 | Train loss: 0.9887 | Train acc: 50.91% | Val loss: 1.0503 | Val acc: 46.46% | LR: 0.001396
Epoch: 051 | Train loss: 0.9972 | Train acc: 50.39% | Val loss: 1.0563 | Val acc: 46.05% | LR: 0.001378
Epoch: 052 | Train loss: 0.9941 | Train acc: 50.42% | Val loss: 0.9791 | Val acc: 51.40% | LR: 0.001361
Epoch: 053 | Train loss: 0.9848 | Train acc: 51.15% | Val loss: 0.9879 | Val acc: 51.12% | LR: 0.001343
Epoch: 054 | Train loss: 0.9839 | Train acc: 51.22% | Val loss: 0.9928 | Val acc: 50.39% | LR: 0.001325
Epoch: 055 | Train loss: 0.9805 | Train acc: 51.48% | Val loss: 0.9995 | Val acc: 50.15% | LR: 0.001307
Epoch: 056 | Train loss: 0.9807 | Train acc: 51.32% | Val loss: 1.0005 | Val acc: 50.13% | LR: 0.001289
Epoch: 057 | Train loss: 0.9886 | Train acc: 50.53% | Val loss: 0.9958 | Val acc: 50.34% | LR: 0.001270
Epoch: 058 | Train loss: 0.9796 | Train acc: 51.39% | Val loss: 1.0018 | Val acc: 49.96% | LR: 0.001252
Epoch: 059 | Train loss: 0.9876 | Train acc: 50.83% | Val loss: 1.0060 | Val acc: 49.66% | LR: 0.001233
Epoch: 060 | Train loss: 0.9829 | Train acc: 51.13% | Val loss: 1.0131 | Val acc: 49.32% | LR: 0.001214
Epoch: 061 | Train loss: 0.9793 | Train acc: 51.27% | Val loss: 0.9978 | Val acc: 49.83% | LR: 0.001195
Epoch: 062 | Train loss: 0.9846 | Train acc: 51.20% | Val loss: 0.9965 | Val acc: 50.22% | LR: 0.001176
Epoch: 063 | Train loss: 0.9835 | Train acc: 50.85% | Val loss: 1.0038 | Val acc: 50.03% | LR: 0.001157
Epoch: 064 | Train loss: 0.9878 | Train acc: 50.96% | Val loss: 1.0060 | Val acc: 49.86% | LR: 0.001138
Epoch: 065 | Train loss: 0.9830 | Train acc: 51.54% | Val loss: 1.0012 | Val acc: 50.24% | LR: 0.001119
Epoch: 066 | Train loss: 0.9843 | Train acc: 51.06% | Val loss: 1.0012 | Val acc: 50.08% | LR: 0.001099
Epoch: 067 | Train loss: 0.9804 | Train acc: 51.41% | Val loss: 0.9976 | Val acc: 50.34% | LR: 0.001080
Epoch: 068 | Train loss: 0.9787 | Train acc: 51.42% | Val loss: 0.9920 | Val acc: 50.40% | LR: 0.001060
Epoch: 069 | Train loss: 0.9862 | Train acc: 51.00% | Val loss: 0.9952 | Val acc: 49.87% | LR: 0.001041
Epoch: 070 | Train loss: 0.9870 | Train acc: 50.65% | Val loss: 0.9899 | Val acc: 50.29% | LR: 0.001021
Epoch: 071 | Train loss: 0.9808 | Train acc: 51.28% | Val loss: 0.9956 | Val acc: 50.18% | LR: 0.001001
Epoch: 072 | Train loss: 0.9750 | Train acc: 51.71% | Val loss: 0.9953 | Val acc: 50.24% | LR: 0.000982
Epoch: 073 | Train loss: 0.9845 | Train acc: 51.08% | Val loss: 0.9930 | Val acc: 50.48% | LR: 0.000962
Epoch: 074 | Train loss: 0.9798 | Train acc: 51.53% | Val loss: 0.9878 | Val acc: 51.16% | LR: 0.000942
Epoch: 075 | Train loss: 0.9810 | Train acc: 51.10% | Val loss: 0.9952 | Val acc: 50.36% | LR: 0.000923
Epoch: 076 | Train loss: 0.9786 | Train acc: 51.44% | Val loss: 0.9705 | Val acc: 51.74% | LR: 0.000903
Epoch: 077 | Train loss: 0.9890 | Train acc: 50.66% | Val loss: 0.9729 | Val acc: 51.72% | LR: 0.000883
Epoch: 078 | Train loss: 0.9901 | Train acc: 50.52% | Val loss: 0.9850 | Val acc: 51.05% | LR: 0.000863
Epoch: 079 | Train loss: 0.9872 | Train acc: 50.96% | Val loss: 0.9868 | Val acc: 50.90% | LR: 0.000844
Epoch: 080 | Train loss: 0.9843 | Train acc: 50.82% | Val loss: 0.9893 | Val acc: 50.86% | LR: 0.000824
Epoch: 081 | Train loss: 0.9815 | Train acc: 51.48% | Val loss: 0.9939 | Val acc: 50.38% | LR: 0.000805
Epoch: 082 | Train loss: 0.9808 | Train acc: 51.20% | Val loss: 0.9875 | Val acc: 50.72% | LR: 0.000785
Epoch: 083 | Train loss: 0.9857 | Train acc: 50.75% | Val loss: 0.9871 | Val acc: 50.99% | LR: 0.000766
Epoch: 084 | Train loss: 0.9828 | Train acc: 51.28% | Val loss: 0.9845 | Val acc: 50.84% | LR: 0.000747
Epoch: 085 | Train loss: 0.9873 | Train acc: 50.80% | Val loss: 0.9831 | Val acc: 50.89% | LR: 0.000727
Epoch: 086 | Train loss: 0.9887 | Train acc: 50.65% | Val loss: 0.9732 | Val acc: 51.72% | LR: 0.000708
Epoch: 087 | Train loss: 0.9819 | Train acc: 51.20% | Val loss: 0.9766 | Val acc: 51.32% | LR: 0.000689
Epoch: 088 | Train loss: 0.9790 | Train acc: 51.26% | Val loss: 0.9892 | Val acc: 50.71% | LR: 0.000670
Epoch: 089 | Train loss: 0.9811 | Train acc: 51.21% | Val loss: 0.9907 | Val acc: 50.58% | LR: 0.000651
Epoch: 090 | Train loss: 0.9837 | Train acc: 51.05% | Val loss: 0.9771 | Val acc: 51.42% | LR: 0.000633
Epoch: 091 | Train loss: 0.9765 | Train acc: 51.57% | Val loss: 0.9941 | Val acc: 50.34% | LR: 0.000614
Epoch: 092 | Train loss: 0.9840 | Train acc: 50.92% | Val loss: 0.9844 | Val acc: 50.87% | LR: 0.000596
Epoch: 093 | Train loss: 0.9820 | Train acc: 51.11% | Val loss: 0.9907 | Val acc: 50.58% | LR: 0.000577
Epoch: 094 | Train loss: 0.9816 | Train acc: 51.30% | Val loss: 0.9814 | Val acc: 51.14% | LR: 0.000559
Epoch: 095 | Train loss: 0.9806 | Train acc: 51.13% | Val loss: 0.9831 | Val acc: 50.97% | LR: 0.000541
Epoch: 096 | Train loss: 0.9779 | Train acc: 51.45% | Val loss: 0.9812 | Val acc: 51.13% | LR: 0.000524
Epoch: 097 | Train loss: 0.9866 | Train acc: 50.69% | Val loss: 0.9890 | Val acc: 50.79% | LR: 0.000506
Epoch: 098 | Train loss: 0.9772 | Train acc: 51.66% | Val loss: 0.9859 | Val acc: 50.71% | LR: 0.000489
Epoch: 099 | Train loss: 0.9745 | Train acc: 51.59% | Val loss: 0.9794 | Val acc: 51.20% | LR: 0.000472
Epoch: 100 | Train loss: 0.9746 | Train acc: 51.56% | Val loss: 0.9724 | Val acc: 51.69% | LR: 0.000455
Epoch: 101 | Train loss: 0.9760 | Train acc: 51.35% | Val loss: 0.9933 | Val acc: 50.32% | LR: 0.000438
Epoch: 102 | Train loss: 0.9804 | Train acc: 51.28% | Val loss: 0.9768 | Val acc: 51.54% | LR: 0.000421
Epoch: 103 | Train loss: 0.9763 | Train acc: 51.37% | Val loss: 0.9757 | Val acc: 51.42% | LR: 0.000405
Epoch: 104 | Train loss: 0.9834 | Train acc: 50.98% | Val loss: 0.9768 | Val acc: 51.40% | LR: 0.000389
Epoch: 105 | Train loss: 0.9801 | Train acc: 51.17% | Val loss: 0.9741 | Val acc: 51.51% | LR: 0.000373
Epoch: 106 | Train loss: 0.9849 | Train acc: 51.19% | Val loss: 0.9774 | Val acc: 51.45% | LR: 0.000358
Epoch: 107 | Train loss: 0.9766 | Train acc: 51.49% | Val loss: 0.9783 | Val acc: 51.43% | LR: 0.000342
Epoch: 108 | Train loss: 0.9783 | Train acc: 51.32% | Val loss: 0.9748 | Val acc: 51.47% | LR: 0.000327
Epoch: 109 | Train loss: 0.9854 | Train acc: 50.89% | Val loss: 0.9751 | Val acc: 51.49% | LR: 0.000312
Epoch: 110 | Train loss: 0.9788 | Train acc: 51.27% | Val loss: 0.9761 | Val acc: 51.37% | LR: 0.000298
Epoch: 111 | Train loss: 0.9780 | Train acc: 51.50% | Val loss: 0.9785 | Val acc: 51.21% | LR: 0.000284
Epoch: 112 | Train loss: 0.9782 | Train acc: 51.44% | Val loss: 0.9736 | Val acc: 51.51% | LR: 0.000270
Epoch: 113 | Train loss: 0.9755 | Train acc: 51.54% | Val loss: 0.9790 | Val acc: 51.10% | LR: 0.000256
Epoch: 114 | Train loss: 0.9814 | Train acc: 51.08% | Val loss: 0.9800 | Val acc: 51.07% | LR: 0.000243
Epoch: 115 | Train loss: 0.9817 | Train acc: 51.17% | Val loss: 0.9799 | Val acc: 51.09% | LR: 0.000230
Epoch: 116 | Train loss: 0.9695 | Train acc: 51.89% | Val loss: 0.9786 | Val acc: 51.11% | LR: 0.000217
Epoch: 117 | Train loss: 0.9728 | Train acc: 51.77% | Val loss: 0.9816 | Val acc: 51.09% | LR: 0.000205
Epoch: 118 | Train loss: 0.9837 | Train acc: 51.01% | Val loss: 0.9811 | Val acc: 51.15% | LR: 0.000193
Epoch: 119 | Train loss: 0.9825 | Train acc: 51.01% | Val loss: 0.9802 | Val acc: 51.25% | LR: 0.000181
Epoch: 120 | Train loss: 0.9858 | Train acc: 50.82% | Val loss: 0.9805 | Val acc: 51.01% | LR: 0.000169
Epoch: 121 | Train loss: 0.9745 | Train acc: 51.53% | Val loss: 0.9816 | Val acc: 51.21% | LR: 0.000158
Epoch: 122 | Train loss: 0.9774 | Train acc: 51.30% | Val loss: 0.9818 | Val acc: 51.09% | LR: 0.000148
Epoch: 123 | Train loss: 0.9845 | Train acc: 51.02% | Val loss: 0.9804 | Val acc: 51.11% | LR: 0.000137
Epoch: 124 | Train loss: 0.9774 | Train acc: 51.38% | Val loss: 0.9817 | Val acc: 51.01% | LR: 0.000127
Epoch: 125 | Train loss: 0.9786 | Train acc: 51.21% | Val loss: 0.9797 | Val acc: 51.03% | LR: 0.000117
Epoch: 126 | Train loss: 0.9762 | Train acc: 51.57% | Val loss: 0.9800 | Val acc: 51.19% | LR: 0.000108
Epoch: 127 | Train loss: 0.9809 | Train acc: 51.20% | Val loss: 0.9801 | Val acc: 51.11% | LR: 0.000099
Epoch: 128 | Train loss: 0.9857 | Train acc: 50.87% | Val loss: 0.9794 | Val acc: 51.15% | LR: 0.000091
Epoch: 129 | Train loss: 0.9723 | Train acc: 51.75% | Val loss: 0.9804 | Val acc: 51.13% | LR: 0.000082
Epoch: 130 | Train loss: 0.9726 | Train acc: 51.76% | Val loss: 0.9792 | Val acc: 51.17% | LR: 0.000075
Epoch: 131 | Train loss: 0.9760 | Train acc: 51.31% | Val loss: 0.9801 | Val acc: 51.13% | LR: 0.000067
Epoch: 132 | Train loss: 0.9669 | Train acc: 52.02% | Val loss: 0.9790 | Val acc: 51.17% | LR: 0.000060
Epoch: 133 | Train loss: 0.9800 | Train acc: 51.31% | Val loss: 0.9797 | Val acc: 51.11% | LR: 0.000053
Epoch: 134 | Train loss: 0.9792 | Train acc: 51.23% | Val loss: 0.9795 | Val acc: 51.13% | LR: 0.000047
Epoch: 135 | Train loss: 0.9804 | Train acc: 51.32% | Val loss: 0.9793 | Val acc: 51.17% | LR: 0.000041
Epoch: 136 | Train loss: 0.9782 | Train acc: 51.32% | Val loss: 0.9792 | Val acc: 51.19% | LR: 0.000036
Epoch: 137 | Train loss: 0.9830 | Train acc: 51.05% | Val loss: 0.9797 | Val acc: 51.15% | LR: 0.000031
Epoch: 138 | Train loss: 0.9759 | Train acc: 51.59% | Val loss: 0.9796 | Val acc: 51.17% | LR: 0.000026
Epoch: 139 | Train loss: 0.9653 | Train acc: 52.12% | Val loss: 0.9793 | Val acc: 51.17% | LR: 0.000022
Epoch: 140 | Train loss: 0.9805 | Train acc: 51.14% | Val loss: 0.9791 | Val acc: 51.21% | LR: 0.000018
Epoch: 141 | Train loss: 0.9792 | Train acc: 51.23% | Val loss: 0.9792 | Val acc: 51.17% | LR: 0.000014
Epoch: 142 | Train loss: 0.9759 | Train acc: 51.50% | Val loss: 0.9793 | Val acc: 51.17% | LR: 0.000011
Epoch: 143 | Train loss: 0.9814 | Train acc: 51.14% | Val loss: 0.9791 | Val acc: 51.17% | LR: 0.000008
Epoch: 144 | Train loss: 0.9784 | Train acc: 51.23% | Val loss: 0.9791 | Val acc: 51.17% | LR: 0.000006
Epoch: 145 | Train loss: 0.9810 | Train acc: 51.14% | Val loss: 0.9791 | Val acc: 51.17% | LR: 0.000004
Epoch: 146 | Train loss: 0.9684 | Train acc: 52.03% | Val loss: 0.9790 | Val acc: 51.23% | LR: 0.000003
Epoch: 147 | Train loss: 0.9775 | Train acc: 51.32% | Val loss: 0.9790 | Val acc: 51.23% | LR: 0.000002
Epoch: 148 | Train loss: 0.9785 | Train acc: 51.23% | Val loss: 0.9790 | Val acc: 51.23% | LR: 0.000001
Epoch: 149 | Train loss: 0.9715 | Train acc: 51.94% | Val loss: 0.9790 | Val acc: 51.23% | LR: 0.000001

[I 2025-09-23 02:13:58,333] Trial 14 finished with value: 0.5501292705535888 and parameters: {'lr': 0.0018834436816170788, 'hidden_size': 129, 'dropout': 0.31136928127389235, 'weight_decay': 0.5981558228988189}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.0078 | Train acc: 50.03% | Val loss: 1.0787 | Val acc: 46.95% | LR: 0.004637
Epoch: 001 | Train loss: 1.0362 | Train acc: 50.75% | Val loss: 1.2097 | Val acc: 46.68% | LR: 0.004635
Epoch: 002 | Train loss: 0.9983 | Train acc: 50.49% | Val loss: 1.0126 | Val acc: 46.09% | LR: 0.004633
Epoch: 003 | Train loss: 0.9996 | Train acc: 50.24% | Val loss: 1.0183 | Val acc: 47.72% | LR: 0.004629
Epoch: 004 | Train loss: 0.9964 | Train acc: 50.80% | Val loss: 0.9518 | Val acc: 53.88% | LR: 0.004625
Epoch: 005 | Train loss: 0.9967 | Train acc: 50.36% | Val loss: 0.9363 | Val acc: 54.53% | LR: 0.004619
Epoch: 006 | Train loss: 0.9975 | Train acc: 50.51% | Val loss: 1.0192 | Val acc: 47.81% | LR: 0.004613
Epoch: 007 | Train loss: 0.9892 | Train acc: 50.78% | Val loss: 1.0616 | Val acc: 47.25% | LR: 0.004605
Epoch: 008 | Train loss: 0.9954 | Train acc: 50.75% | Val loss: 0.9671 | Val acc: 54.05% | LR: 0.004596
Epoch: 009 | Train loss: 0.9924 | Train acc: 50.76% | Val loss: 1.0650 | Val acc: 45.95% | LR: 0.004587
Epoch: 010 | Train loss: 0.9944 | Train acc: 50.71% | Val loss: 0.9775 | Val acc: 54.05% | LR: 0.004576
Epoch: 011 | Train loss: 0.9948 | Train acc: 50.54% | Val loss: 0.9564 | Val acc: 54.05% | LR: 0.004565
Epoch: 012 | Train loss: 0.9908 | Train acc: 50.99% | Val loss: 1.0115 | Val acc: 48.08% | LR: 0.004552
Epoch: 013 | Train loss: 0.9886 | Train acc: 50.96% | Val loss: 1.0078 | Val acc: 48.78% | LR: 0.004539
Epoch: 014 | Train loss: 0.9897 | Train acc: 50.72% | Val loss: 1.0089 | Val acc: 49.47% | LR: 0.004524
Epoch: 015 | Train loss: 0.9861 | Train acc: 51.09% | Val loss: 1.0064 | Val acc: 50.33% | LR: 0.004509
Epoch: 016 | Train loss: 0.9918 | Train acc: 50.56% | Val loss: 0.9686 | Val acc: 52.16% | LR: 0.004492
Epoch: 017 | Train loss: 0.9826 | Train acc: 51.26% | Val loss: 1.0066 | Val acc: 49.79% | LR: 0.004475
Epoch: 018 | Train loss: 0.9866 | Train acc: 51.32% | Val loss: 0.9958 | Val acc: 49.80% | LR: 0.004456
Epoch: 019 | Train loss: 0.9881 | Train acc: 50.79% | Val loss: 0.9882 | Val acc: 51.41% | LR: 0.004437
Epoch: 020 | Train loss: 0.9907 | Train acc: 50.34% | Val loss: 0.9630 | Val acc: 52.50% | LR: 0.004417
Epoch: 021 | Train loss: 0.9851 | Train acc: 51.48% | Val loss: 0.9546 | Val acc: 52.70% | LR: 0.004396
Epoch: 022 | Train loss: 0.9838 | Train acc: 50.97% | Val loss: 0.9820 | Val acc: 51.15% | LR: 0.004374
Epoch: 023 | Train loss: 0.9853 | Train acc: 51.13% | Val loss: 1.0258 | Val acc: 48.55% | LR: 0.004351
Epoch: 024 | Train loss: 0.9857 | Train acc: 51.31% | Val loss: 1.0448 | Val acc: 45.87% | LR: 0.004327
Epoch: 025 | Train loss: 0.9981 | Train acc: 50.49% | Val loss: 1.0548 | Val acc: 46.04% | LR: 0.004302
Epoch: 026 | Train loss: 0.9946 | Train acc: 50.51% | Val loss: 0.9635 | Val acc: 54.05% | LR: 0.004277
Epoch: 027 | Train loss: 1.0013 | Train acc: 49.90% | Val loss: 1.0292 | Val acc: 45.78% | LR: 0.004250
Epoch: 028 | Train loss: 1.0000 | Train acc: 50.31% | Val loss: 1.0261 | Val acc: 45.80% | LR: 0.004223
Epoch: 029 | Train loss: 0.9925 | Train acc: 50.49% | Val loss: 0.9952 | Val acc: 51.99% | LR: 0.004195
Epoch: 030 | Train loss: 0.9982 | Train acc: 50.17% | Val loss: 1.0399 | Val acc: 45.95% | LR: 0.004166
Epoch: 031 | Train loss: 0.9937 | Train acc: 50.46% | Val loss: 1.0126 | Val acc: 48.80% | LR: 0.004136
Epoch: 032 | Train loss: 0.9896 | Train acc: 51.15% | Val loss: 0.9682 | Val acc: 51.95% | LR: 0.004105
Epoch: 033 | Train loss: 0.9788 | Train acc: 51.46% | Val loss: 1.0245 | Val acc: 48.79% | LR: 0.004074
Epoch: 034 | Train loss: 0.9928 | Train acc: 50.59% | Val loss: 0.9880 | Val acc: 51.04% | LR: 0.004042
Epoch: 035 | Train loss: 0.9866 | Train acc: 50.92% | Val loss: 0.9767 | Val acc: 51.42% | LR: 0.004009
Epoch: 036 | Train loss: 0.9886 | Train acc: 50.79% | Val loss: 0.9707 | Val acc: 51.62% | LR: 0.003976
Epoch: 037 | Train loss: 0.9883 | Train acc: 51.01% | Val loss: 0.9874 | Val acc: 50.89% | LR: 0.003941
Epoch: 038 | Train loss: 0.9926 | Train acc: 50.71% | Val loss: 0.9673 | Val acc: 52.10% | LR: 0.003906
Epoch: 039 | Train loss: 0.9855 | Train acc: 51.10% | Val loss: 1.0085 | Val acc: 50.02% | LR: 0.003870
Epoch: 040 | Train loss: 0.9890 | Train acc: 51.13% | Val loss: 1.1327 | Val acc: 51.07% | LR: 0.003834
Epoch: 041 | Train loss: 0.9885 | Train acc: 51.25% | Val loss: 1.0302 | Val acc: 47.68% | LR: 0.003797
Epoch: 042 | Train loss: 0.9850 | Train acc: 51.12% | Val loss: 1.0025 | Val acc: 49.65% | LR: 0.003759
Epoch: 043 | Train loss: 0.9857 | Train acc: 51.18% | Val loss: 0.9938 | Val acc: 50.28% | LR: 0.003721
Epoch: 044 | Train loss: 0.9870 | Train acc: 51.22% | Val loss: 1.0383 | Val acc: 47.15% | LR: 0.003682
Epoch: 045 | Train loss: 0.9883 | Train acc: 51.12% | Val loss: 0.9853 | Val acc: 50.80% | LR: 0.003642
Epoch: 046 | Train loss: 0.9862 | Train acc: 51.08% | Val loss: 0.9791 | Val acc: 51.66% | LR: 0.003602
Epoch: 047 | Train loss: 0.9816 | Train acc: 51.23% | Val loss: 1.0063 | Val acc: 50.06% | LR: 0.003561
Epoch: 048 | Train loss: 0.9875 | Train acc: 50.85% | Val loss: 1.0146 | Val acc: 49.22% | LR: 0.003520
Epoch: 049 | Train loss: 0.9848 | Train acc: 51.14% | Val loss: 0.9927 | Val acc: 50.84% | LR: 0.003478
Epoch: 050 | Train loss: 0.9919 | Train acc: 50.38% | Val loss: 0.9814 | Val acc: 50.89% | LR: 0.003436
Epoch: 051 | Train loss: 0.9886 | Train acc: 50.54% | Val loss: 1.0156 | Val acc: 49.60% | LR: 0.003393
Epoch: 052 | Train loss: 0.9895 | Train acc: 50.61% | Val loss: 0.9926 | Val acc: 51.30% | LR: 0.003350
Epoch: 053 | Train loss: 0.9862 | Train acc: 51.18% | Val loss: 0.9661 | Val acc: 52.11% | LR: 0.003306
Epoch: 054 | Train loss: 0.9917 | Train acc: 50.62% | Val loss: 0.9951 | Val acc: 51.03% | LR: 0.003262
Epoch: 055 | Train loss: 0.9801 | Train acc: 51.74% | Val loss: 1.0137 | Val acc: 49.14% | LR: 0.003218
Epoch: 056 | Train loss: 0.9841 | Train acc: 51.40% | Val loss: 1.0145 | Val acc: 48.77% | LR: 0.003173
Epoch: 057 | Train loss: 0.9793 | Train acc: 51.24% | Val loss: 0.9948 | Val acc: 50.47% | LR: 0.003127
Epoch: 058 | Train loss: 0.9815 | Train acc: 51.20% | Val loss: 1.0114 | Val acc: 49.40% | LR: 0.003082
Epoch: 059 | Train loss: 0.9707 | Train acc: 51.72% | Val loss: 1.0202 | Val acc: 48.88% | LR: 0.003036
Epoch: 060 | Train loss: 0.9904 | Train acc: 50.67% | Val loss: 0.9996 | Val acc: 50.18% | LR: 0.002989
Epoch: 061 | Train loss: 0.9820 | Train acc: 51.07% | Val loss: 1.0085 | Val acc: 49.62% | LR: 0.002943
Epoch: 062 | Train loss: 0.9820 | Train acc: 51.06% | Val loss: 1.0205 | Val acc: 48.81% | LR: 0.002896
Epoch: 063 | Train loss: 0.9725 | Train acc: 51.71% | Val loss: 1.0078 | Val acc: 49.58% | LR: 0.002849
Epoch: 064 | Train loss: 0.9865 | Train acc: 50.84% | Val loss: 1.0024 | Val acc: 49.75% | LR: 0.002801
Epoch: 065 | Train loss: 0.9808 | Train acc: 51.28% | Val loss: 0.9919 | Val acc: 50.74% | LR: 0.002754
Epoch: 066 | Train loss: 0.9825 | Train acc: 51.09% | Val loss: 0.9987 | Val acc: 50.36% | LR: 0.002706
Epoch: 067 | Train loss: 0.9792 | Train acc: 51.17% | Val loss: 1.0001 | Val acc: 50.11% | LR: 0.002658
Epoch: 068 | Train loss: 0.9854 | Train acc: 50.96% | Val loss: 0.9841 | Val acc: 50.95% | LR: 0.002610
Epoch: 069 | Train loss: 0.9753 | Train acc: 51.65% | Val loss: 0.9724 | Val acc: 52.61% | LR: 0.002562
Epoch: 070 | Train loss: 0.9796 | Train acc: 51.44% | Val loss: 0.9948 | Val acc: 50.79% | LR: 0.002513
Epoch: 071 | Train loss: 0.9854 | Train acc: 50.85% | Val loss: 0.9847 | Val acc: 50.80% | LR: 0.002465
Epoch: 072 | Train loss: 0.9828 | Train acc: 51.13% | Val loss: 1.0127 | Val acc: 50.03% | LR: 0.002416
Epoch: 073 | Train loss: 0.9887 | Train acc: 50.74% | Val loss: 0.9862 | Val acc: 51.14% | LR: 0.002368
Epoch: 074 | Train loss: 0.9884 | Train acc: 50.73% | Val loss: 0.9489 | Val acc: 53.84% | LR: 0.002319
Epoch: 075 | Train loss: 0.9897 | Train acc: 50.35% | Val loss: 0.9458 | Val acc: 54.49% | LR: 0.002271
Epoch: 076 | Train loss: 0.9862 | Train acc: 50.84% | Val loss: 0.9665 | Val acc: 52.06% | LR: 0.002222
Epoch: 077 | Train loss: 1.0274 | Train acc: 50.84% | Val loss: 0.9511 | Val acc: 52.84% | LR: 0.002174
Epoch: 078 | Train loss: 1.0317 | Train acc: 50.99% | Val loss: 1.0238 | Val acc: 48.02% | LR: 0.002125
Epoch: 079 | Train loss: 2.5145 | Train acc: 50.11% | Val loss: 1.0671 | Val acc: 45.95% | LR: 0.002077
Epoch: 080 | Train loss: 0.9983 | Train acc: 50.43% | Val loss: 1.0412 | Val acc: 45.95% | LR: 0.002029
Epoch: 081 | Train loss: 0.9943 | Train acc: 50.52% | Val loss: 1.0300 | Val acc: 45.95% | LR: 0.001981
Epoch: 082 | Train loss: 0.9929 | Train acc: 50.51% | Val loss: 1.0452 | Val acc: 45.95% | LR: 0.001933
Epoch: 083 | Train loss: 0.9916 | Train acc: 50.61% | Val loss: 1.0285 | Val acc: 45.95% | LR: 0.001885
Epoch: 084 | Train loss: 1.0008 | Train acc: 50.12% | Val loss: 1.0226 | Val acc: 47.13% | LR: 0.001837
Epoch: 085 | Train loss: 0.9956 | Train acc: 50.57% | Val loss: 1.0095 | Val acc: 48.43% | LR: 0.001790
Epoch: 086 | Train loss: 0.9910 | Train acc: 50.73% | Val loss: 0.9884 | Val acc: 49.78% | LR: 0.001743
Epoch: 087 | Train loss: 0.9926 | Train acc: 50.48% | Val loss: 0.9853 | Val acc: 49.85% | LR: 0.001696
Epoch: 088 | Train loss: 0.9815 | Train acc: 51.23% | Val loss: 0.9870 | Val acc: 49.74% | LR: 0.001649
Epoch: 089 | Train loss: 0.9793 | Train acc: 51.40% | Val loss: 0.9938 | Val acc: 50.04% | LR: 0.001603
Epoch: 090 | Train loss: 0.9866 | Train acc: 50.87% | Val loss: 1.0056 | Val acc: 49.58% | LR: 0.001557
Epoch: 091 | Train loss: 0.9813 | Train acc: 51.33% | Val loss: 1.0003 | Val acc: 49.47% | LR: 0.001511
Epoch: 092 | Train loss: 0.9868 | Train acc: 50.87% | Val loss: 0.9972 | Val acc: 49.83% | LR: 0.001466
Epoch: 093 | Train loss: 0.9818 | Train acc: 51.24% | Val loss: 0.9936 | Val acc: 50.42% | LR: 0.001421
Epoch: 094 | Train loss: 0.9849 | Train acc: 51.00% | Val loss: 1.0149 | Val acc: 48.93% | LR: 0.001376
Epoch: 095 | Train loss: 0.9890 | Train acc: 50.94% | Val loss: 0.9708 | Val acc: 51.57% | LR: 0.001332
Epoch: 096 | Train loss: 0.9846 | Train acc: 50.95% | Val loss: 1.0054 | Val acc: 49.41% | LR: 0.001288
Epoch: 097 | Train loss: 0.9807 | Train acc: 51.12% | Val loss: 0.9897 | Val acc: 50.52% | LR: 0.001245
Epoch: 098 | Train loss: 0.9826 | Train acc: 51.08% | Val loss: 0.9835 | Val acc: 50.96% | LR: 0.001202
Epoch: 099 | Train loss: 0.9896 | Train acc: 50.70% | Val loss: 0.9853 | Val acc: 50.67% | LR: 0.001160
Epoch: 100 | Train loss: 0.9774 | Train acc: 51.31% | Val loss: 0.9854 | Val acc: 50.78% | LR: 0.001118
Epoch: 101 | Train loss: 0.9850 | Train acc: 50.83% | Val loss: 1.0042 | Val acc: 50.25% | LR: 0.001077
Epoch: 102 | Train loss: 0.9795 | Train acc: 51.33% | Val loss: 0.9900 | Val acc: 50.33% | LR: 0.001036
Epoch: 103 | Train loss: 0.9804 | Train acc: 51.08% | Val loss: 0.9870 | Val acc: 50.63% | LR: 0.000996
Epoch: 104 | Train loss: 0.9752 | Train acc: 51.55% | Val loss: 0.9903 | Val acc: 50.20% | LR: 0.000957
Epoch: 105 | Train loss: 0.9848 | Train acc: 50.91% | Val loss: 0.9899 | Val acc: 50.57% | LR: 0.000918
Epoch: 106 | Train loss: 0.9785 | Train acc: 51.23% | Val loss: 0.9873 | Val acc: 50.76% | LR: 0.000879
Epoch: 107 | Train loss: 0.9732 | Train acc: 51.64% | Val loss: 0.9927 | Val acc: 50.55% | LR: 0.000842
Epoch: 108 | Train loss: 0.9758 | Train acc: 51.38% | Val loss: 0.9959 | Val acc: 50.25% | LR: 0.000804
Epoch: 109 | Train loss: 0.9693 | Train acc: 51.82% | Val loss: 0.9836 | Val acc: 50.81% | LR: 0.000768
Epoch: 110 | Train loss: 0.9691 | Train acc: 51.93% | Val loss: 0.9980 | Val acc: 50.29% | LR: 0.000732
Epoch: 111 | Train loss: 0.9808 | Train acc: 51.04% | Val loss: 0.9921 | Val acc: 50.23% | LR: 0.000697
Epoch: 112 | Train loss: 0.9790 | Train acc: 51.24% | Val loss: 0.9977 | Val acc: 50.09% | LR: 0.000663
Epoch: 113 | Train loss: 0.9735 | Train acc: 51.56% | Val loss: 0.9964 | Val acc: 50.31% | LR: 0.000629
Epoch: 114 | Train loss: 0.9834 | Train acc: 50.94% | Val loss: 0.9992 | Val acc: 50.30% | LR: 0.000596
Epoch: 115 | Train loss: 0.9765 | Train acc: 51.50% | Val loss: 0.9914 | Val acc: 50.47% | LR: 0.000564
Epoch: 116 | Train loss: 0.9845 | Train acc: 51.02% | Val loss: 0.9892 | Val acc: 50.57% | LR: 0.000533
Epoch: 117 | Train loss: 0.9831 | Train acc: 50.97% | Val loss: 0.9954 | Val acc: 50.39% | LR: 0.000502
Epoch: 118 | Train loss: 0.9742 | Train acc: 51.44% | Val loss: 0.9883 | Val acc: 50.67% | LR: 0.000473
Epoch: 119 | Train loss: 0.9734 | Train acc: 51.68% | Val loss: 0.9920 | Val acc: 50.52% | LR: 0.000444
Epoch: 120 | Train loss: 0.9800 | Train acc: 51.05% | Val loss: 0.9897 | Val acc: 50.71% | LR: 0.000416
Epoch: 121 | Train loss: 0.9675 | Train acc: 51.90% | Val loss: 0.9875 | Val acc: 50.48% | LR: 0.000388
Epoch: 122 | Train loss: 0.9730 | Train acc: 51.64% | Val loss: 0.9887 | Val acc: 50.46% | LR: 0.000362
Epoch: 123 | Train loss: 0.9774 | Train acc: 51.34% | Val loss: 0.9945 | Val acc: 50.58% | LR: 0.000336
Epoch: 124 | Train loss: 0.9763 | Train acc: 51.36% | Val loss: 0.9924 | Val acc: 50.54% | LR: 0.000312
Epoch: 125 | Train loss: 0.9771 | Train acc: 51.28% | Val loss: 0.9894 | Val acc: 50.70% | LR: 0.000288
Epoch: 126 | Train loss: 0.9784 | Train acc: 51.17% | Val loss: 0.9907 | Val acc: 50.71% | LR: 0.000265
Epoch: 127 | Train loss: 0.9758 | Train acc: 51.36% | Val loss: 0.9927 | Val acc: 50.55% | LR: 0.000243
Epoch: 128 | Train loss: 0.9728 | Train acc: 51.56% | Val loss: 0.9944 | Val acc: 50.33% | LR: 0.000222
Epoch: 129 | Train loss: 0.9808 | Train acc: 51.01% | Val loss: 0.9963 | Val acc: 50.36% | LR: 0.000201
Epoch: 130 | Train loss: 0.9811 | Train acc: 51.11% | Val loss: 0.9896 | Val acc: 50.40% | LR: 0.000182
Epoch: 131 | Train loss: 0.9787 | Train acc: 51.23% | Val loss: 0.9911 | Val acc: 50.28% | LR: 0.000164
Epoch: 132 | Train loss: 0.9732 | Train acc: 51.67% | Val loss: 0.9935 | Val acc: 50.22% | LR: 0.000146
Epoch: 133 | Train loss: 0.9738 | Train acc: 51.48% | Val loss: 0.9944 | Val acc: 50.34% | LR: 0.000130
Epoch: 134 | Train loss: 0.9691 | Train acc: 51.83% | Val loss: 0.9947 | Val acc: 50.42% | LR: 0.000114
Epoch: 135 | Train loss: 0.9737 | Train acc: 51.56% | Val loss: 0.9949 | Val acc: 50.26% | LR: 0.000100
Epoch: 136 | Train loss: 0.9762 | Train acc: 51.37% | Val loss: 0.9944 | Val acc: 50.27% | LR: 0.000086
Epoch: 137 | Train loss: 0.9764 | Train acc: 51.39% | Val loss: 0.9948 | Val acc: 50.31% | LR: 0.000074
Epoch: 138 | Train loss: 0.9794 | Train acc: 51.11% | Val loss: 0.9955 | Val acc: 50.52% | LR: 0.000062
Epoch: 139 | Train loss: 0.9718 | Train acc: 51.67% | Val loss: 0.9955 | Val acc: 50.52% | LR: 0.000052
Epoch: 140 | Train loss: 0.9833 | Train acc: 50.86% | Val loss: 0.9954 | Val acc: 50.32% | LR: 0.000042
Epoch: 141 | Train loss: 0.9807 | Train acc: 51.03% | Val loss: 0.9955 | Val acc: 50.41% | LR: 0.000033
Epoch: 142 | Train loss: 0.9816 | Train acc: 50.95% | Val loss: 0.9954 | Val acc: 50.36% | LR: 0.000026
Epoch: 143 | Train loss: 0.9723 | Train acc: 51.59% | Val loss: 0.9949 | Val acc: 50.21% | LR: 0.000019
Epoch: 144 | Train loss: 0.9756 | Train acc: 51.41% | Val loss: 0.9946 | Val acc: 50.28% | LR: 0.000014
Epoch: 145 | Train loss: 0.9805 | Train acc: 51.08% | Val loss: 0.9945 | Val acc: 50.28% | LR: 0.000009
Epoch: 146 | Train loss: 0.9842 | Train acc: 50.88% | Val loss: 0.9944 | Val acc: 50.25% | LR: 0.000006
Epoch: 147 | Train loss: 0.9767 | Train acc: 51.33% | Val loss: 0.9945 | Val acc: 50.28% | LR: 0.000003
Epoch: 148 | Train loss: 0.9776 | Train acc: 51.16% | Val loss: 0.9945 | Val acc: 50.28% | LR: 0.000002
Epoch: 149 | Train loss: 0.9769 | Train acc: 51.34% | Val loss: 0.9945 | Val acc: 50.28% | LR: 0.000001

[I 2025-09-23 02:15:50,888] Trial 15 finished with value: 0.5452592611312866 and parameters: {'lr': 0.004637477112927384, 'hidden_size': 83, 'dropout': 0.16787038307087987, 'weight_decay': 0.18618491817037586}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 0.9964 | Train acc: 50.65% | Val loss: 1.0054 | Val acc: 46.82% | LR: 0.001186
Epoch: 001 | Train loss: 0.9900 | Train acc: 51.31% | Val loss: 1.0136 | Val acc: 48.06% | LR: 0.001185
Epoch: 002 | Train loss: 0.9897 | Train acc: 50.84% | Val loss: 1.0044 | Val acc: 48.89% | LR: 0.001185
Epoch: 003 | Train loss: 0.9890 | Train acc: 50.78% | Val loss: 0.9919 | Val acc: 50.86% | LR: 0.001184
Epoch: 004 | Train loss: 0.9948 | Train acc: 50.74% | Val loss: 1.0132 | Val acc: 48.46% | LR: 0.001183
Epoch: 005 | Train loss: 0.9890 | Train acc: 50.87% | Val loss: 0.9892 | Val acc: 50.91% | LR: 0.001181
Epoch: 006 | Train loss: 0.9873 | Train acc: 51.37% | Val loss: 0.9885 | Val acc: 50.55% | LR: 0.001179
Epoch: 007 | Train loss: 0.9894 | Train acc: 50.72% | Val loss: 1.0041 | Val acc: 49.59% | LR: 0.001178
Epoch: 008 | Train loss: 0.9849 | Train acc: 51.23% | Val loss: 0.9964 | Val acc: 50.03% | LR: 0.001175
Epoch: 009 | Train loss: 0.9830 | Train acc: 51.18% | Val loss: 0.9965 | Val acc: 49.84% | LR: 0.001173
Epoch: 010 | Train loss: 0.9843 | Train acc: 51.07% | Val loss: 1.0043 | Val acc: 49.64% | LR: 0.001170
Epoch: 011 | Train loss: 0.9773 | Train acc: 51.45% | Val loss: 1.0077 | Val acc: 49.35% | LR: 0.001167
Epoch: 012 | Train loss: 0.9816 | Train acc: 51.36% | Val loss: 1.0323 | Val acc: 48.61% | LR: 0.001164
Epoch: 013 | Train loss: 0.9907 | Train acc: 50.79% | Val loss: 0.9781 | Val acc: 52.14% | LR: 0.001161
Epoch: 014 | Train loss: 1.0038 | Train acc: 50.97% | Val loss: 0.9652 | Val acc: 53.92% | LR: 0.001157
Epoch: 015 | Train loss: 0.9925 | Train acc: 50.81% | Val loss: 1.0395 | Val acc: 46.01% | LR: 0.001153
Epoch: 016 | Train loss: 0.9944 | Train acc: 50.51% | Val loss: 0.9508 | Val acc: 53.69% | LR: 0.001149
Epoch: 017 | Train loss: 0.9982 | Train acc: 50.51% | Val loss: 1.0396 | Val acc: 49.27% | LR: 0.001144
Epoch: 018 | Train loss: 0.9906 | Train acc: 50.68% | Val loss: 1.0284 | Val acc: 45.95% | LR: 0.001140
Epoch: 019 | Train loss: 0.9942 | Train acc: 50.44% | Val loss: 1.0216 | Val acc: 45.95% | LR: 0.001135
Epoch: 020 | Train loss: 0.9938 | Train acc: 50.57% | Val loss: 0.9940 | Val acc: 50.06% | LR: 0.001129
Epoch: 021 | Train loss: 0.9907 | Train acc: 50.88% | Val loss: 0.9813 | Val acc: 52.26% | LR: 0.001124
Epoch: 022 | Train loss: 0.9909 | Train acc: 50.78% | Val loss: 0.9738 | Val acc: 53.20% | LR: 0.001118
Epoch: 023 | Train loss: 0.9884 | Train acc: 51.10% | Val loss: 0.9663 | Val acc: 52.20% | LR: 0.001113
Epoch: 024 | Train loss: 0.9962 | Train acc: 50.59% | Val loss: 0.9810 | Val acc: 51.58% | LR: 0.001106
Epoch: 025 | Train loss: 0.9928 | Train acc: 50.60% | Val loss: 0.9976 | Val acc: 50.46% | LR: 0.001100
Epoch: 026 | Train loss: 0.9895 | Train acc: 50.84% | Val loss: 0.9755 | Val acc: 51.53% | LR: 0.001094
Epoch: 027 | Train loss: 0.9879 | Train acc: 50.76% | Val loss: 0.9913 | Val acc: 50.35% | LR: 0.001087
Epoch: 028 | Train loss: 0.9887 | Train acc: 50.77% | Val loss: 0.9871 | Val acc: 50.84% | LR: 0.001080
Epoch: 029 | Train loss: 0.9878 | Train acc: 50.58% | Val loss: 1.0032 | Val acc: 50.52% | LR: 0.001073
Epoch: 030 | Train loss: 0.9888 | Train acc: 50.90% | Val loss: 1.0139 | Val acc: 49.30% | LR: 0.001065
Epoch: 031 | Train loss: 0.9811 | Train acc: 51.21% | Val loss: 0.9886 | Val acc: 51.86% | LR: 0.001058
Epoch: 032 | Train loss: 0.9816 | Train acc: 51.44% | Val loss: 0.9521 | Val acc: 52.93% | LR: 0.001050
Epoch: 033 | Train loss: 0.9877 | Train acc: 50.74% | Val loss: 0.9288 | Val acc: 54.66% | LR: 0.001042
Epoch: 034 | Train loss: 0.9875 | Train acc: 50.76% | Val loss: 0.9396 | Val acc: 53.90% | LR: 0.001034
Epoch: 035 | Train loss: 0.9855 | Train acc: 50.75% | Val loss: 0.9458 | Val acc: 53.53% | LR: 0.001025
Epoch: 036 | Train loss: 0.9939 | Train acc: 50.45% | Val loss: 0.9345 | Val acc: 54.72% | LR: 0.001017
Epoch: 037 | Train loss: 0.9898 | Train acc: 50.87% | Val loss: 0.9405 | Val acc: 54.46% | LR: 0.001008
Epoch: 038 | Train loss: 0.9824 | Train acc: 51.66% | Val loss: 0.9482 | Val acc: 53.50% | LR: 0.000999
Epoch: 039 | Train loss: 0.9874 | Train acc: 50.89% | Val loss: 0.9768 | Val acc: 51.76% | LR: 0.000990
Epoch: 040 | Train loss: 0.9881 | Train acc: 50.71% | Val loss: 1.0298 | Val acc: 48.01% | LR: 0.000980
Epoch: 041 | Train loss: 0.9827 | Train acc: 51.21% | Val loss: 1.0307 | Val acc: 48.62% | LR: 0.000971
Epoch: 042 | Train loss: 0.9897 | Train acc: 50.66% | Val loss: 1.0641 | Val acc: 46.27% | LR: 0.000961
Epoch: 043 | Train loss: 1.0001 | Train acc: 50.08% | Val loss: 1.0627 | Val acc: 46.13% | LR: 0.000952
Epoch: 044 | Train loss: 0.9850 | Train acc: 51.17% | Val loss: 1.0509 | Val acc: 46.85% | LR: 0.000942
Epoch: 045 | Train loss: 0.9900 | Train acc: 50.67% | Val loss: 1.0680 | Val acc: 46.39% | LR: 0.000932
Epoch: 046 | Train loss: 0.9913 | Train acc: 50.97% | Val loss: 1.0611 | Val acc: 46.10% | LR: 0.000921
Epoch: 047 | Train loss: 0.9893 | Train acc: 50.68% | Val loss: 1.0209 | Val acc: 47.89% | LR: 0.000911
Epoch: 048 | Train loss: 0.9824 | Train acc: 51.31% | Val loss: 1.0110 | Val acc: 49.22% | LR: 0.000900
Epoch: 049 | Train loss: 0.9816 | Train acc: 51.20% | Val loss: 0.9968 | Val acc: 49.90% | LR: 0.000890
Epoch: 050 | Train loss: 0.9821 | Train acc: 51.19% | Val loss: 0.9922 | Val acc: 50.32% | LR: 0.000879
Epoch: 051 | Train loss: 0.9877 | Train acc: 50.97% | Val loss: 0.9927 | Val acc: 50.20% | LR: 0.000868
Epoch: 052 | Train loss: 0.9862 | Train acc: 50.90% | Val loss: 1.0070 | Val acc: 49.61% | LR: 0.000857
Epoch: 053 | Train loss: 0.9836 | Train acc: 51.18% | Val loss: 1.0234 | Val acc: 48.72% | LR: 0.000846
Epoch: 054 | Train loss: 0.9900 | Train acc: 50.58% | Val loss: 1.0722 | Val acc: 46.05% | LR: 0.000834
Epoch: 055 | Train loss: 0.9900 | Train acc: 50.81% | Val loss: 1.0630 | Val acc: 45.97% | LR: 0.000823
Epoch: 056 | Train loss: 0.9810 | Train acc: 51.18% | Val loss: 1.0513 | Val acc: 47.04% | LR: 0.000811
Epoch: 057 | Train loss: 0.9848 | Train acc: 51.07% | Val loss: 1.0436 | Val acc: 47.49% | LR: 0.000800
Epoch: 058 | Train loss: 0.9841 | Train acc: 50.95% | Val loss: 1.0319 | Val acc: 48.09% | LR: 0.000788
Epoch: 059 | Train loss: 0.9833 | Train acc: 51.08% | Val loss: 1.0308 | Val acc: 48.25% | LR: 0.000776
Epoch: 060 | Train loss: 0.9738 | Train acc: 51.74% | Val loss: 1.0432 | Val acc: 47.64% | LR: 0.000765
Epoch: 061 | Train loss: 0.9815 | Train acc: 51.23% | Val loss: 1.0386 | Val acc: 47.82% | LR: 0.000753
Epoch: 062 | Train loss: 0.9710 | Train acc: 51.88% | Val loss: 1.0162 | Val acc: 48.55% | LR: 0.000741
Epoch: 063 | Train loss: 0.9870 | Train acc: 50.98% | Val loss: 1.0151 | Val acc: 49.07% | LR: 0.000729
Epoch: 064 | Train loss: 0.9866 | Train acc: 50.77% | Val loss: 1.0176 | Val acc: 48.82% | LR: 0.000717
Epoch: 065 | Train loss: 0.9830 | Train acc: 51.16% | Val loss: 1.0330 | Val acc: 48.15% | LR: 0.000704
Epoch: 066 | Train loss: 0.9900 | Train acc: 50.59% | Val loss: 1.0402 | Val acc: 47.75% | LR: 0.000692
Epoch: 067 | Train loss: 0.9857 | Train acc: 50.95% | Val loss: 1.0268 | Val acc: 48.49% | LR: 0.000680
Epoch: 068 | Train loss: 0.9778 | Train acc: 51.34% | Val loss: 0.9976 | Val acc: 50.02% | LR: 0.000668
Epoch: 069 | Train loss: 0.9882 | Train acc: 50.61% | Val loss: 0.9978 | Val acc: 50.08% | LR: 0.000655
Epoch: 070 | Train loss: 0.9838 | Train acc: 50.97% | Val loss: 0.9976 | Val acc: 50.11% | LR: 0.000643
Epoch: 071 | Train loss: 0.9771 | Train acc: 51.24% | Val loss: 1.0053 | Val acc: 50.00% | LR: 0.000631
Epoch: 072 | Train loss: 0.9840 | Train acc: 51.06% | Val loss: 1.0168 | Val acc: 49.20% | LR: 0.000618
Epoch: 073 | Train loss: 0.9822 | Train acc: 50.99% | Val loss: 1.0333 | Val acc: 48.34% | LR: 0.000606
Epoch: 074 | Train loss: 0.9868 | Train acc: 50.83% | Val loss: 1.0271 | Val acc: 48.52% | LR: 0.000593
Epoch: 075 | Train loss: 0.9773 | Train acc: 51.70% | Val loss: 1.0252 | Val acc: 48.43% | LR: 0.000581
Epoch: 076 | Train loss: 0.9826 | Train acc: 51.06% | Val loss: 1.0501 | Val acc: 47.04% | LR: 0.000569
Epoch: 077 | Train loss: 0.9741 | Train acc: 51.52% | Val loss: 1.0264 | Val acc: 48.52% | LR: 0.000556
Epoch: 078 | Train loss: 0.9850 | Train acc: 50.92% | Val loss: 1.0305 | Val acc: 48.23% | LR: 0.000544
Epoch: 079 | Train loss: 0.9803 | Train acc: 51.09% | Val loss: 1.0305 | Val acc: 48.38% | LR: 0.000531
Epoch: 080 | Train loss: 0.9818 | Train acc: 50.96% | Val loss: 1.0216 | Val acc: 48.88% | LR: 0.000519
Epoch: 081 | Train loss: 0.9837 | Train acc: 50.89% | Val loss: 1.0224 | Val acc: 48.66% | LR: 0.000507
Epoch: 082 | Train loss: 0.9801 | Train acc: 51.18% | Val loss: 1.0371 | Val acc: 47.94% | LR: 0.000495
Epoch: 083 | Train loss: 0.9847 | Train acc: 50.96% | Val loss: 1.0440 | Val acc: 47.57% | LR: 0.000482
Epoch: 084 | Train loss: 0.9765 | Train acc: 51.40% | Val loss: 1.0522 | Val acc: 47.31% | LR: 0.000470
Epoch: 085 | Train loss: 0.9840 | Train acc: 50.95% | Val loss: 1.0358 | Val acc: 48.07% | LR: 0.000458
Epoch: 086 | Train loss: 0.9867 | Train acc: 50.60% | Val loss: 1.0403 | Val acc: 47.88% | LR: 0.000446
Epoch: 087 | Train loss: 0.9814 | Train acc: 51.23% | Val loss: 1.0345 | Val acc: 48.11% | LR: 0.000434
Epoch: 088 | Train loss: 0.9778 | Train acc: 51.41% | Val loss: 1.0368 | Val acc: 47.98% | LR: 0.000422
Epoch: 089 | Train loss: 0.9881 | Train acc: 50.67% | Val loss: 1.0491 | Val acc: 47.19% | LR: 0.000410
Epoch: 090 | Train loss: 0.9793 | Train acc: 51.28% | Val loss: 1.0646 | Val acc: 46.52% | LR: 0.000399
Epoch: 091 | Train loss: 0.9797 | Train acc: 51.08% | Val loss: 1.0446 | Val acc: 47.65% | LR: 0.000387
Epoch: 092 | Train loss: 0.9907 | Train acc: 50.44% | Val loss: 1.0467 | Val acc: 47.14% | LR: 0.000375
Epoch: 093 | Train loss: 0.9836 | Train acc: 50.92% | Val loss: 1.0574 | Val acc: 46.87% | LR: 0.000364
Epoch: 094 | Train loss: 0.9831 | Train acc: 51.00% | Val loss: 1.0476 | Val acc: 47.19% | LR: 0.000352
Epoch: 095 | Train loss: 0.9834 | Train acc: 50.91% | Val loss: 1.0509 | Val acc: 47.15% | LR: 0.000341
Epoch: 096 | Train loss: 0.9763 | Train acc: 51.61% | Val loss: 1.0490 | Val acc: 47.14% | LR: 0.000330
Epoch: 097 | Train loss: 0.9784 | Train acc: 51.38% | Val loss: 1.0435 | Val acc: 47.58% | LR: 0.000319
Epoch: 098 | Train loss: 0.9849 | Train acc: 50.89% | Val loss: 1.0397 | Val acc: 47.56% | LR: 0.000308
Epoch: 099 | Train loss: 0.9815 | Train acc: 51.18% | Val loss: 1.0367 | Val acc: 48.02% | LR: 0.000297
Epoch: 100 | Train loss: 0.9819 | Train acc: 51.10% | Val loss: 1.0418 | Val acc: 47.78% | LR: 0.000287
Epoch: 101 | Train loss: 0.9832 | Train acc: 50.89% | Val loss: 1.0484 | Val acc: 47.28% | LR: 0.000276
Epoch: 102 | Train loss: 0.9733 | Train acc: 51.69% | Val loss: 1.0529 | Val acc: 47.14% | LR: 0.000266
Epoch: 103 | Train loss: 0.9774 | Train acc: 51.24% | Val loss: 1.0514 | Val acc: 47.14% | LR: 0.000255
Epoch: 104 | Train loss: 0.9824 | Train acc: 50.84% | Val loss: 1.0463 | Val acc: 47.37% | LR: 0.000245
Epoch: 105 | Train loss: 0.9808 | Train acc: 51.21% | Val loss: 1.0448 | Val acc: 47.55% | LR: 0.000235
Epoch: 106 | Train loss: 0.9767 | Train acc: 51.39% | Val loss: 1.0342 | Val acc: 48.04% | LR: 0.000225
Epoch: 107 | Train loss: 0.9842 | Train acc: 50.88% | Val loss: 1.0329 | Val acc: 48.12% | LR: 0.000216
Epoch: 108 | Train loss: 0.9802 | Train acc: 51.13% | Val loss: 1.0373 | Val acc: 48.00% | LR: 0.000206
Epoch: 109 | Train loss: 0.9790 | Train acc: 51.15% | Val loss: 1.0346 | Val acc: 48.00% | LR: 0.000197
Epoch: 110 | Train loss: 0.9833 | Train acc: 50.90% | Val loss: 1.0384 | Val acc: 47.94% | LR: 0.000188
Epoch: 111 | Train loss: 0.9749 | Train acc: 51.43% | Val loss: 1.0386 | Val acc: 47.80% | LR: 0.000179
Epoch: 112 | Train loss: 0.9878 | Train acc: 50.55% | Val loss: 1.0373 | Val acc: 47.96% | LR: 0.000170
Epoch: 113 | Train loss: 0.9770 | Train acc: 51.27% | Val loss: 1.0408 | Val acc: 47.86% | LR: 0.000162
Epoch: 114 | Train loss: 0.9804 | Train acc: 51.17% | Val loss: 1.0388 | Val acc: 47.90% | LR: 0.000153
Epoch: 115 | Train loss: 0.9815 | Train acc: 51.18% | Val loss: 1.0387 | Val acc: 47.84% | LR: 0.000145
Epoch: 116 | Train loss: 0.9757 | Train acc: 51.62% | Val loss: 1.0395 | Val acc: 47.78% | LR: 0.000137
Epoch: 117 | Train loss: 0.9736 | Train acc: 51.53% | Val loss: 1.0406 | Val acc: 47.86% | LR: 0.000129
Epoch: 118 | Train loss: 0.9859 | Train acc: 50.73% | Val loss: 1.0386 | Val acc: 47.84% | LR: 0.000122
Epoch: 119 | Train loss: 0.9902 | Train acc: 50.39% | Val loss: 1.0414 | Val acc: 47.74% | LR: 0.000114
Epoch: 120 | Train loss: 0.9767 | Train acc: 51.36% | Val loss: 1.0392 | Val acc: 47.88% | LR: 0.000107
Epoch: 121 | Train loss: 0.9776 | Train acc: 51.36% | Val loss: 1.0418 | Val acc: 47.69% | LR: 0.000100
Epoch: 122 | Train loss: 0.9802 | Train acc: 51.17% | Val loss: 1.0400 | Val acc: 47.82% | LR: 0.000093
Epoch: 123 | Train loss: 0.9805 | Train acc: 51.18% | Val loss: 1.0414 | Val acc: 47.76% | LR: 0.000087
Epoch: 124 | Train loss: 0.9827 | Train acc: 50.92% | Val loss: 1.0398 | Val acc: 47.80% | LR: 0.000080
Epoch: 125 | Train loss: 0.9823 | Train acc: 50.92% | Val loss: 1.0407 | Val acc: 47.78% | LR: 0.000074
Epoch: 126 | Train loss: 0.9781 | Train acc: 51.19% | Val loss: 1.0409 | Val acc: 47.78% | LR: 0.000068
Epoch: 127 | Train loss: 0.9815 | Train acc: 51.01% | Val loss: 1.0408 | Val acc: 47.78% | LR: 0.000063
Epoch: 128 | Train loss: 0.9797 | Train acc: 51.19% | Val loss: 1.0406 | Val acc: 47.88% | LR: 0.000057
Epoch: 129 | Train loss: 0.9793 | Train acc: 51.19% | Val loss: 1.0399 | Val acc: 47.88% | LR: 0.000052
Epoch: 130 | Train loss: 0.9762 | Train acc: 51.46% | Val loss: 1.0403 | Val acc: 47.88% | LR: 0.000047
Epoch: 131 | Train loss: 0.9859 | Train acc: 50.75% | Val loss: 1.0404 | Val acc: 47.80% | LR: 0.000043
Epoch: 132 | Train loss: 0.9865 | Train acc: 50.75% | Val loss: 1.0399 | Val acc: 47.84% | LR: 0.000038
Epoch: 133 | Train loss: 0.9839 | Train acc: 50.92% | Val loss: 1.0400 | Val acc: 47.88% | LR: 0.000034
Epoch: 134 | Train loss: 0.9796 | Train acc: 51.19% | Val loss: 1.0403 | Val acc: 47.88% | LR: 0.000030
Epoch: 135 | Train loss: 0.9758 | Train acc: 51.46% | Val loss: 1.0401 | Val acc: 47.86% | LR: 0.000026
Epoch: 136 | Train loss: 0.9814 | Train acc: 51.10% | Val loss: 1.0400 | Val acc: 47.88% | LR: 0.000023
Epoch: 137 | Train loss: 0.9772 | Train acc: 51.37% | Val loss: 1.0398 | Val acc: 47.88% | LR: 0.000020
Epoch: 138 | Train loss: 0.9775 | Train acc: 51.37% | Val loss: 1.0400 | Val acc: 47.86% | LR: 0.000017
Epoch: 139 | Train loss: 0.9770 | Train acc: 51.37% | Val loss: 1.0402 | Val acc: 47.86% | LR: 0.000014
Epoch: 140 | Train loss: 0.9791 | Train acc: 51.37% | Val loss: 1.0402 | Val acc: 47.86% | LR: 0.000011
Epoch: 141 | Train loss: 0.9794 | Train acc: 51.19% | Val loss: 1.0399 | Val acc: 47.88% | LR: 0.000009
Epoch: 142 | Train loss: 0.9821 | Train acc: 50.92% | Val loss: 1.0399 | Val acc: 47.88% | LR: 0.000007
Epoch: 143 | Train loss: 0.9857 | Train acc: 50.75% | Val loss: 1.0399 | Val acc: 47.86% | LR: 0.000006
Epoch: 144 | Train loss: 0.9749 | Train acc: 51.46% | Val loss: 1.0398 | Val acc: 47.88% | LR: 0.000004
Epoch: 145 | Train loss: 0.9715 | Train acc: 51.72% | Val loss: 1.0398 | Val acc: 47.88% | LR: 0.000003
Epoch: 146 | Train loss: 0.9801 | Train acc: 51.10% | Val loss: 1.0398 | Val acc: 47.88% | LR: 0.000002
Epoch: 147 | Train loss: 0.9800 | Train acc: 51.01% | Val loss: 1.0398 | Val acc: 47.88% | LR: 0.000002
Epoch: 148 | Train loss: 0.9886 | Train acc: 50.57% | Val loss: 1.0398 | Val acc: 47.88% | LR: 0.000001
Epoch: 149 | Train loss: 0.9739 | Train acc: 51.46% | Val loss: 1.0398 | Val acc: 47.88% | LR: 0.000001

[I 2025-09-23 02:18:22,291] Trial 16 finished with value: 0.5471995830535888 and parameters: {'lr': 0.0011858153010561399, 'hidden_size': 220, 'dropout': 0.27274696115635294, 'weight_decay': 0.4070566688296278}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.0018 | Train acc: 50.20% | Val loss: 1.0053 | Val acc: 50.91% | LR: 0.004216
Epoch: 001 | Train loss: 1.0094 | Train acc: 49.75% | Val loss: 1.0002 | Val acc: 48.94% | LR: 0.004215
Epoch: 002 | Train loss: 1.1099 | Train acc: 49.41% | Val loss: 1.0148 | Val acc: 46.33% | LR: 0.004213
Epoch: 003 | Train loss: 1.0483 | Train acc: 50.70% | Val loss: 1.0161 | Val acc: 46.66% | LR: 0.004209
Epoch: 004 | Train loss: 0.9998 | Train acc: 50.52% | Val loss: 0.9923 | Val acc: 51.23% | LR: 0.004205
Epoch: 005 | Train loss: 0.9991 | Train acc: 50.14% | Val loss: 1.0333 | Val acc: 45.97% | LR: 0.004200
Epoch: 006 | Train loss: 1.0007 | Train acc: 50.08% | Val loss: 1.0076 | Val acc: 48.41% | LR: 0.004194
Epoch: 007 | Train loss: 0.9942 | Train acc: 50.57% | Val loss: 0.9656 | Val acc: 51.87% | LR: 0.004187
Epoch: 008 | Train loss: 0.9999 | Train acc: 50.13% | Val loss: 0.9749 | Val acc: 51.87% | LR: 0.004179
Epoch: 009 | Train loss: 0.9933 | Train acc: 50.66% | Val loss: 0.9809 | Val acc: 51.99% | LR: 0.004171
Epoch: 010 | Train loss: 0.9939 | Train acc: 50.49% | Val loss: 1.0601 | Val acc: 46.40% | LR: 0.004161
Epoch: 011 | Train loss: 0.9911 | Train acc: 50.99% | Val loss: 0.9881 | Val acc: 51.28% | LR: 0.004151
Epoch: 012 | Train loss: 0.9912 | Train acc: 51.21% | Val loss: 0.9933 | Val acc: 53.00% | LR: 0.004139
Epoch: 013 | Train loss: 1.0005 | Train acc: 50.17% | Val loss: 0.9887 | Val acc: 54.05% | LR: 0.004127
Epoch: 014 | Train loss: 0.9972 | Train acc: 50.14% | Val loss: 1.0049 | Val acc: 46.31% | LR: 0.004114
Epoch: 015 | Train loss: 1.0028 | Train acc: 50.21% | Val loss: 0.9891 | Val acc: 54.32% | LR: 0.004100
Epoch: 016 | Train loss: 0.9982 | Train acc: 50.53% | Val loss: 1.0078 | Val acc: 47.87% | LR: 0.004085
Epoch: 017 | Train loss: 1.0037 | Train acc: 50.37% | Val loss: 1.0095 | Val acc: 49.17% | LR: 0.004069
Epoch: 018 | Train loss: 0.9923 | Train acc: 50.90% | Val loss: 0.9737 | Val acc: 52.41% | LR: 0.004052
Epoch: 019 | Train loss: 0.9975 | Train acc: 50.33% | Val loss: 1.0227 | Val acc: 48.53% | LR: 0.004035
Epoch: 020 | Train loss: 0.9887 | Train acc: 50.67% | Val loss: 1.0277 | Val acc: 48.65% | LR: 0.004016
Epoch: 021 | Train loss: 1.0009 | Train acc: 51.16% | Val loss: 0.9647 | Val acc: 52.59% | LR: 0.003997
Epoch: 022 | Train loss: 0.9894 | Train acc: 51.37% | Val loss: 0.9569 | Val acc: 54.12% | LR: 0.003977
Epoch: 023 | Train loss: 0.9978 | Train acc: 50.68% | Val loss: 0.9451 | Val acc: 54.05% | LR: 0.003956
Epoch: 024 | Train loss: 1.0011 | Train acc: 50.75% | Val loss: 0.9521 | Val acc: 53.24% | LR: 0.003934
Epoch: 025 | Train loss: 0.9909 | Train acc: 50.70% | Val loss: 0.9814 | Val acc: 51.26% | LR: 0.003912
Epoch: 026 | Train loss: 0.9928 | Train acc: 50.85% | Val loss: 0.9869 | Val acc: 51.03% | LR: 0.003889
Epoch: 027 | Train loss: 0.9906 | Train acc: 50.85% | Val loss: 0.9791 | Val acc: 50.93% | LR: 0.003865
Epoch: 028 | Train loss: 0.9933 | Train acc: 50.95% | Val loss: 0.9945 | Val acc: 50.57% | LR: 0.003840
Epoch: 029 | Train loss: 0.9995 | Train acc: 49.92% | Val loss: 0.9628 | Val acc: 52.85% | LR: 0.003814
Epoch: 030 | Train loss: 0.9955 | Train acc: 50.65% | Val loss: 0.9945 | Val acc: 50.59% | LR: 0.003788
Epoch: 031 | Train loss: 0.9994 | Train acc: 50.08% | Val loss: 0.9888 | Val acc: 51.31% | LR: 0.003761
Epoch: 032 | Train loss: 0.9902 | Train acc: 50.83% | Val loss: 1.0039 | Val acc: 50.37% | LR: 0.003733
Epoch: 033 | Train loss: 0.9920 | Train acc: 50.74% | Val loss: 0.9795 | Val acc: 51.19% | LR: 0.003705
Epoch: 034 | Train loss: 0.9901 | Train acc: 50.74% | Val loss: 0.9852 | Val acc: 51.32% | LR: 0.003675
Epoch: 035 | Train loss: 0.9973 | Train acc: 50.19% | Val loss: 0.9857 | Val acc: 51.14% | LR: 0.003645
Epoch: 036 | Train loss: 0.9859 | Train acc: 51.20% | Val loss: 1.0203 | Val acc: 48.69% | LR: 0.003615
Epoch: 037 | Train loss: 0.9996 | Train acc: 50.84% | Val loss: 1.0584 | Val acc: 46.17% | LR: 0.003584
Epoch: 038 | Train loss: 0.9863 | Train acc: 51.84% | Val loss: 0.9915 | Val acc: 50.42% | LR: 0.003552
Epoch: 039 | Train loss: 0.9951 | Train acc: 50.73% | Val loss: 1.0132 | Val acc: 49.14% | LR: 0.003519
Epoch: 040 | Train loss: 0.9989 | Train acc: 49.92% | Val loss: 0.9933 | Val acc: 50.38% | LR: 0.003486
Epoch: 041 | Train loss: 0.9940 | Train acc: 50.75% | Val loss: 1.0094 | Val acc: 49.14% | LR: 0.003453
Epoch: 042 | Train loss: 1.0074 | Train acc: 49.39% | Val loss: 0.9722 | Val acc: 53.93% | LR: 0.003418
Epoch: 043 | Train loss: 0.9923 | Train acc: 50.79% | Val loss: 0.9640 | Val acc: 52.76% | LR: 0.003383
Epoch: 044 | Train loss: 0.9885 | Train acc: 51.01% | Val loss: 0.9638 | Val acc: 52.58% | LR: 0.003348
Epoch: 045 | Train loss: 0.9933 | Train acc: 50.49% | Val loss: 0.9755 | Val acc: 53.09% | LR: 0.003312
Epoch: 046 | Train loss: 0.9882 | Train acc: 51.30% | Val loss: 0.9677 | Val acc: 52.31% | LR: 0.003275
Epoch: 047 | Train loss: 0.9919 | Train acc: 50.91% | Val loss: 0.9639 | Val acc: 52.76% | LR: 0.003238
Epoch: 048 | Train loss: 0.9925 | Train acc: 50.58% | Val loss: 0.9803 | Val acc: 51.46% | LR: 0.003201
Epoch: 049 | Train loss: 0.9915 | Train acc: 50.73% | Val loss: 0.9758 | Val acc: 51.72% | LR: 0.003163
Epoch: 050 | Train loss: 0.9934 | Train acc: 50.73% | Val loss: 0.9777 | Val acc: 52.07% | LR: 0.003124
Epoch: 051 | Train loss: 1.0044 | Train acc: 50.44% | Val loss: 0.9366 | Val acc: 54.22% | LR: 0.003085
Epoch: 052 | Train loss: 0.9951 | Train acc: 50.83% | Val loss: 0.9576 | Val acc: 52.99% | LR: 0.003046
Epoch: 053 | Train loss: 1.0003 | Train acc: 50.00% | Val loss: 0.9730 | Val acc: 54.22% | LR: 0.003006
Epoch: 054 | Train loss: 0.9980 | Train acc: 50.40% | Val loss: 0.9752 | Val acc: 54.22% | LR: 0.002966
Epoch: 055 | Train loss: 0.9969 | Train acc: 50.57% | Val loss: 1.0060 | Val acc: 45.97% | LR: 0.002926
Epoch: 056 | Train loss: 0.9962 | Train acc: 50.84% | Val loss: 0.9885 | Val acc: 53.50% | LR: 0.002885
Epoch: 057 | Train loss: 0.9940 | Train acc: 50.34% | Val loss: 0.9785 | Val acc: 54.17% | LR: 0.002844
Epoch: 058 | Train loss: 0.9986 | Train acc: 50.58% | Val loss: 1.0107 | Val acc: 45.95% | LR: 0.002802
Epoch: 059 | Train loss: 1.0006 | Train acc: 50.12% | Val loss: 0.9871 | Val acc: 53.50% | LR: 0.002760
Epoch: 060 | Train loss: 0.9980 | Train acc: 50.36% | Val loss: 0.9926 | Val acc: 51.70% | LR: 0.002718
Epoch: 061 | Train loss: 0.9976 | Train acc: 50.20% | Val loss: 0.9800 | Val acc: 53.25% | LR: 0.002676
Epoch: 062 | Train loss: 0.9936 | Train acc: 50.93% | Val loss: 1.0199 | Val acc: 49.05% | LR: 0.002633
Epoch: 063 | Train loss: 1.0013 | Train acc: 50.77% | Val loss: 0.9512 | Val acc: 54.45% | LR: 0.002590
Epoch: 064 | Train loss: 0.9964 | Train acc: 50.51% | Val loss: 0.9815 | Val acc: 51.50% | LR: 0.002547
Epoch: 065 | Train loss: 0.9891 | Train acc: 50.98% | Val loss: 0.9580 | Val acc: 52.71% | LR: 0.002504
Epoch: 066 | Train loss: 0.9884 | Train acc: 50.98% | Val loss: 0.9903 | Val acc: 50.55% | LR: 0.002460
Epoch: 067 | Train loss: 0.9879 | Train acc: 50.72% | Val loss: 0.9911 | Val acc: 50.89% | LR: 0.002417
Epoch: 068 | Train loss: 0.9880 | Train acc: 50.94% | Val loss: 1.0026 | Val acc: 50.17% | LR: 0.002373
Epoch: 069 | Train loss: 0.9894 | Train acc: 51.00% | Val loss: 0.9556 | Val acc: 53.24% | LR: 0.002329
Epoch: 070 | Train loss: 0.9908 | Train acc: 50.99% | Val loss: 0.9913 | Val acc: 50.00% | LR: 0.002285
Epoch: 071 | Train loss: 0.9880 | Train acc: 51.01% | Val loss: 0.9955 | Val acc: 49.85% | LR: 0.002241
Epoch: 072 | Train loss: 0.9851 | Train acc: 50.48% | Val loss: 0.9748 | Val acc: 51.77% | LR: 0.002197
Epoch: 073 | Train loss: 0.9818 | Train acc: 51.54% | Val loss: 0.9548 | Val acc: 54.07% | LR: 0.002153
Epoch: 074 | Train loss: 0.9862 | Train acc: 51.05% | Val loss: 0.9399 | Val acc: 53.73% | LR: 0.002109
Epoch: 075 | Train loss: 0.9832 | Train acc: 51.23% | Val loss: 0.9763 | Val acc: 53.33% | LR: 0.002065
Epoch: 076 | Train loss: 0.9930 | Train acc: 50.33% | Val loss: 0.9519 | Val acc: 53.10% | LR: 0.002021
Epoch: 077 | Train loss: 0.9918 | Train acc: 50.88% | Val loss: 0.9595 | Val acc: 53.12% | LR: 0.001977
Epoch: 078 | Train loss: 0.9886 | Train acc: 50.81% | Val loss: 0.9724 | Val acc: 52.15% | LR: 0.001933
Epoch: 079 | Train loss: 0.9887 | Train acc: 51.13% | Val loss: 0.9613 | Val acc: 52.88% | LR: 0.001889
Epoch: 080 | Train loss: 0.9885 | Train acc: 51.27% | Val loss: 0.9674 | Val acc: 53.25% | LR: 0.001845
Epoch: 081 | Train loss: 0.9969 | Train acc: 50.32% | Val loss: 0.9635 | Val acc: 52.58% | LR: 0.001801
Epoch: 082 | Train loss: 0.9783 | Train acc: 51.92% | Val loss: 0.9577 | Val acc: 53.00% | LR: 0.001757
Epoch: 083 | Train loss: 0.9831 | Train acc: 51.45% | Val loss: 0.9615 | Val acc: 52.63% | LR: 0.001714
Epoch: 084 | Train loss: 0.9850 | Train acc: 51.12% | Val loss: 0.9739 | Val acc: 52.00% | LR: 0.001671
Epoch: 085 | Train loss: 0.9905 | Train acc: 50.78% | Val loss: 0.9638 | Val acc: 52.61% | LR: 0.001628
Epoch: 086 | Train loss: 0.9916 | Train acc: 50.51% | Val loss: 0.9521 | Val acc: 53.23% | LR: 0.001585
Epoch: 087 | Train loss: 0.9832 | Train acc: 51.52% | Val loss: 0.9612 | Val acc: 52.85% | LR: 0.001542
Epoch: 088 | Train loss: 0.9934 | Train acc: 50.13% | Val loss: 0.9561 | Val acc: 52.84% | LR: 0.001500
Epoch: 089 | Train loss: 0.9905 | Train acc: 50.75% | Val loss: 0.9555 | Val acc: 53.08% | LR: 0.001458
Epoch: 090 | Train loss: 0.9920 | Train acc: 50.25% | Val loss: 0.9546 | Val acc: 52.70% | LR: 0.001416
Epoch: 091 | Train loss: 0.9887 | Train acc: 51.06% | Val loss: 0.9679 | Val acc: 52.20% | LR: 0.001374
Epoch: 092 | Train loss: 0.9870 | Train acc: 51.20% | Val loss: 0.9652 | Val acc: 52.14% | LR: 0.001333
Epoch: 093 | Train loss: 0.9845 | Train acc: 50.81% | Val loss: 0.9638 | Val acc: 52.34% | LR: 0.001292
Epoch: 094 | Train loss: 0.9959 | Train acc: 50.71% | Val loss: 0.9323 | Val acc: 54.70% | LR: 0.001252
Epoch: 095 | Train loss: 0.9903 | Train acc: 51.37% | Val loss: 0.9327 | Val acc: 54.74% | LR: 0.001211
Epoch: 096 | Train loss: 0.9855 | Train acc: 51.11% | Val loss: 0.9331 | Val acc: 54.75% | LR: 0.001172
Epoch: 097 | Train loss: 0.9906 | Train acc: 50.44% | Val loss: 0.9395 | Val acc: 54.13% | LR: 0.001132
Epoch: 098 | Train loss: 0.9842 | Train acc: 51.30% | Val loss: 0.9774 | Val acc: 51.71% | LR: 0.001093
Epoch: 099 | Train loss: 0.9827 | Train acc: 51.42% | Val loss: 0.9772 | Val acc: 51.53% | LR: 0.001055
Epoch: 100 | Train loss: 0.9903 | Train acc: 50.62% | Val loss: 0.9877 | Val acc: 50.95% | LR: 0.001017
Epoch: 101 | Train loss: 0.9822 | Train acc: 51.23% | Val loss: 0.9778 | Val acc: 51.53% | LR: 0.000979
Epoch: 102 | Train loss: 0.9889 | Train acc: 50.66% | Val loss: 0.9597 | Val acc: 52.60% | LR: 0.000942
Epoch: 103 | Train loss: 0.9873 | Train acc: 50.98% | Val loss: 0.9492 | Val acc: 53.33% | LR: 0.000906
Epoch: 104 | Train loss: 0.9794 | Train acc: 51.46% | Val loss: 0.9540 | Val acc: 52.88% | LR: 0.000870
Epoch: 105 | Train loss: 0.9774 | Train acc: 51.39% | Val loss: 0.9703 | Val acc: 51.93% | LR: 0.000834
Epoch: 106 | Train loss: 0.9789 | Train acc: 51.85% | Val loss: 0.9576 | Val acc: 52.65% | LR: 0.000800
Epoch: 107 | Train loss: 0.9891 | Train acc: 50.83% | Val loss: 0.9724 | Val acc: 51.77% | LR: 0.000765
Epoch: 108 | Train loss: 0.9891 | Train acc: 50.80% | Val loss: 0.9775 | Val acc: 51.43% | LR: 0.000732
Epoch: 109 | Train loss: 0.9863 | Train acc: 51.06% | Val loss: 0.9767 | Val acc: 51.50% | LR: 0.000698
Epoch: 110 | Train loss: 0.9917 | Train acc: 50.52% | Val loss: 0.9806 | Val acc: 51.12% | LR: 0.000666
Epoch: 111 | Train loss: 0.9932 | Train acc: 50.67% | Val loss: 0.9814 | Val acc: 51.11% | LR: 0.000634
Epoch: 112 | Train loss: 0.9885 | Train acc: 50.89% | Val loss: 0.9775 | Val acc: 51.32% | LR: 0.000603
Epoch: 113 | Train loss: 0.9862 | Train acc: 51.10% | Val loss: 0.9724 | Val acc: 51.63% | LR: 0.000572
Epoch: 114 | Train loss: 0.9827 | Train acc: 51.18% | Val loss: 0.9765 | Val acc: 51.44% | LR: 0.000542
Epoch: 115 | Train loss: 0.9914 | Train acc: 50.66% | Val loss: 0.9774 | Val acc: 51.40% | LR: 0.000513
Epoch: 116 | Train loss: 0.9795 | Train acc: 51.31% | Val loss: 0.9715 | Val acc: 51.81% | LR: 0.000485
Epoch: 117 | Train loss: 0.9831 | Train acc: 50.99% | Val loss: 0.9734 | Val acc: 51.55% | LR: 0.000457
Epoch: 118 | Train loss: 0.9880 | Train acc: 50.97% | Val loss: 0.9740 | Val acc: 51.75% | LR: 0.000430
Epoch: 119 | Train loss: 0.9759 | Train acc: 51.83% | Val loss: 0.9734 | Val acc: 51.60% | LR: 0.000404
Epoch: 120 | Train loss: 0.9832 | Train acc: 51.25% | Val loss: 0.9601 | Val acc: 52.32% | LR: 0.000378
Epoch: 121 | Train loss: 0.9862 | Train acc: 50.92% | Val loss: 0.9565 | Val acc: 52.66% | LR: 0.000353
Epoch: 122 | Train loss: 0.9849 | Train acc: 51.00% | Val loss: 0.9669 | Val acc: 52.01% | LR: 0.000329
Epoch: 123 | Train loss: 0.9805 | Train acc: 51.60% | Val loss: 0.9710 | Val acc: 51.77% | LR: 0.000306
Epoch: 124 | Train loss: 0.9873 | Train acc: 51.02% | Val loss: 0.9667 | Val acc: 51.96% | LR: 0.000283
Epoch: 125 | Train loss: 0.9839 | Train acc: 51.10% | Val loss: 0.9616 | Val acc: 52.30% | LR: 0.000262
Epoch: 126 | Train loss: 0.9801 | Train acc: 51.19% | Val loss: 0.9606 | Val acc: 52.40% | LR: 0.000241
Epoch: 127 | Train loss: 0.9900 | Train acc: 50.81% | Val loss: 0.9611 | Val acc: 52.38% | LR: 0.000221
Epoch: 128 | Train loss: 0.9826 | Train acc: 51.35% | Val loss: 0.9671 | Val acc: 52.11% | LR: 0.000202
Epoch: 129 | Train loss: 0.9845 | Train acc: 50.92% | Val loss: 0.9712 | Val acc: 51.83% | LR: 0.000183
Epoch: 130 | Train loss: 0.9792 | Train acc: 51.61% | Val loss: 0.9724 | Val acc: 51.67% | LR: 0.000166
Epoch: 131 | Train loss: 0.9834 | Train acc: 51.01% | Val loss: 0.9672 | Val acc: 51.93% | LR: 0.000149
Epoch: 132 | Train loss: 0.9800 | Train acc: 51.38% | Val loss: 0.9693 | Val acc: 51.83% | LR: 0.000133
Epoch: 133 | Train loss: 0.9809 | Train acc: 51.10% | Val loss: 0.9695 | Val acc: 51.85% | LR: 0.000118
Epoch: 134 | Train loss: 0.9767 | Train acc: 51.45% | Val loss: 0.9688 | Val acc: 51.89% | LR: 0.000104
Epoch: 135 | Train loss: 0.9814 | Train acc: 51.28% | Val loss: 0.9689 | Val acc: 51.89% | LR: 0.000091
Epoch: 136 | Train loss: 0.9793 | Train acc: 51.21% | Val loss: 0.9655 | Val acc: 52.15% | LR: 0.000079
Epoch: 137 | Train loss: 0.9766 | Train acc: 51.48% | Val loss: 0.9667 | Val acc: 52.03% | LR: 0.000067
Epoch: 138 | Train loss: 0.9772 | Train acc: 51.56% | Val loss: 0.9671 | Val acc: 52.01% | LR: 0.000057
Epoch: 139 | Train loss: 0.9862 | Train acc: 50.85% | Val loss: 0.9670 | Val acc: 52.01% | LR: 0.000047
Epoch: 140 | Train loss: 0.9796 | Train acc: 51.29% | Val loss: 0.9664 | Val acc: 52.01% | LR: 0.000038
Epoch: 141 | Train loss: 0.9826 | Train acc: 51.12% | Val loss: 0.9663 | Val acc: 52.01% | LR: 0.000031
Epoch: 142 | Train loss: 0.9858 | Train acc: 51.03% | Val loss: 0.9665 | Val acc: 52.01% | LR: 0.000024
Epoch: 143 | Train loss: 0.9893 | Train acc: 50.59% | Val loss: 0.9665 | Val acc: 52.01% | LR: 0.000018
Epoch: 144 | Train loss: 0.9771 | Train acc: 51.74% | Val loss: 0.9664 | Val acc: 52.01% | LR: 0.000013
Epoch: 145 | Train loss: 0.9820 | Train acc: 51.21% | Val loss: 0.9664 | Val acc: 52.01% | LR: 0.000008
Epoch: 146 | Train loss: 0.9744 | Train acc: 51.83% | Val loss: 0.9665 | Val acc: 52.01% | LR: 0.000005
Epoch: 147 | Train loss: 0.9796 | Train acc: 51.21% | Val loss: 0.9664 | Val acc: 52.01% | LR: 0.000003
Epoch: 148 | Train loss: 0.9844 | Train acc: 50.94% | Val loss: 0.9665 | Val acc: 52.01% | LR: 0.000001
Epoch: 149 | Train loss: 0.9783 | Train acc: 51.21% | Val loss: 0.9665 | Val acc: 52.01% | LR: 0.000001

[I 2025-09-23 02:21:33,344] Trial 17 finished with value: 0.5475294351577759 and parameters: {'lr': 0.004216772952176789, 'hidden_size': 140, 'dropout': 0.3735269047729084, 'weight_decay': 0.6667550962690072}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 0.9981 | Train acc: 50.59% | Val loss: 0.9983 | Val acc: 51.63% | LR: 0.001432
Epoch: 001 | Train loss: 0.9829 | Train acc: 51.35% | Val loss: 0.9987 | Val acc: 50.99% | LR: 0.001432
Epoch: 002 | Train loss: 0.9954 | Train acc: 50.53% | Val loss: 0.9982 | Val acc: 51.93% | LR: 0.001431
Epoch: 003 | Train loss: 0.9966 | Train acc: 50.59% | Val loss: 0.9950 | Val acc: 52.38% | LR: 0.001430
Epoch: 004 | Train loss: 0.9879 | Train acc: 51.19% | Val loss: 0.9892 | Val acc: 53.04% | LR: 0.001428
Epoch: 005 | Train loss: 0.9844 | Train acc: 51.01% | Val loss: 0.9550 | Val acc: 54.20% | LR: 0.001427
Epoch: 006 | Train loss: 0.9854 | Train acc: 50.98% | Val loss: 0.9784 | Val acc: 51.82% | LR: 0.001424
Epoch: 007 | Train loss: 0.9897 | Train acc: 50.84% | Val loss: 0.9863 | Val acc: 50.51% | LR: 0.001422
Epoch: 008 | Train loss: 0.9918 | Train acc: 50.63% | Val loss: 1.0051 | Val acc: 48.84% | LR: 0.001419
Epoch: 009 | Train loss: 0.9812 | Train acc: 51.27% | Val loss: 0.9949 | Val acc: 50.03% | LR: 0.001417
Epoch: 010 | Train loss: 0.9843 | Train acc: 50.95% | Val loss: 1.0232 | Val acc: 47.96% | LR: 0.001413
Epoch: 011 | Train loss: 0.9818 | Train acc: 51.05% | Val loss: 1.0183 | Val acc: 49.12% | LR: 0.001410
Epoch: 012 | Train loss: 0.9930 | Train acc: 50.75% | Val loss: 1.0043 | Val acc: 49.97% | LR: 0.001406
Epoch: 013 | Train loss: 0.9880 | Train acc: 50.79% | Val loss: 0.9893 | Val acc: 50.62% | LR: 0.001402
Epoch: 014 | Train loss: 0.9890 | Train acc: 50.56% | Val loss: 0.9984 | Val acc: 50.03% | LR: 0.001397
Epoch: 015 | Train loss: 0.9853 | Train acc: 51.05% | Val loss: 1.0006 | Val acc: 50.27% | LR: 0.001392
Epoch: 016 | Train loss: 0.9779 | Train acc: 51.35% | Val loss: 1.0081 | Val acc: 49.85% | LR: 0.001387
Epoch: 017 | Train loss: 0.9840 | Train acc: 51.00% | Val loss: 1.0054 | Val acc: 49.91% | LR: 0.001382
Epoch: 018 | Train loss: 0.9839 | Train acc: 51.04% | Val loss: 0.9905 | Val acc: 50.52% | LR: 0.001376
Epoch: 019 | Train loss: 0.9747 | Train acc: 51.67% | Val loss: 0.9923 | Val acc: 50.46% | LR: 0.001370
Epoch: 020 | Train loss: 0.9810 | Train acc: 51.16% | Val loss: 1.0104 | Val acc: 49.68% | LR: 0.001364
Epoch: 021 | Train loss: 0.9886 | Train acc: 50.81% | Val loss: 0.9970 | Val acc: 50.38% | LR: 0.001358
Epoch: 022 | Train loss: 0.9736 | Train acc: 51.64% | Val loss: 0.9912 | Val acc: 50.49% | LR: 0.001351
Epoch: 023 | Train loss: 0.9772 | Train acc: 51.59% | Val loss: 1.0048 | Val acc: 49.76% | LR: 0.001344
Epoch: 024 | Train loss: 0.9815 | Train acc: 51.09% | Val loss: 0.9913 | Val acc: 50.72% | LR: 0.001336
Epoch: 025 | Train loss: 0.9818 | Train acc: 51.08% | Val loss: 0.9948 | Val acc: 50.27% | LR: 0.001329
Epoch: 026 | Train loss: 0.9794 | Train acc: 51.36% | Val loss: 0.9963 | Val acc: 50.46% | LR: 0.001321
Epoch: 027 | Train loss: 0.9850 | Train acc: 51.03% | Val loss: 0.9943 | Val acc: 50.51% | LR: 0.001313
Epoch: 028 | Train loss: 1.0106 | Train acc: 51.16% | Val loss: 1.0107 | Val acc: 49.75% | LR: 0.001304
Epoch: 029 | Train loss: 0.9937 | Train acc: 50.63% | Val loss: 0.9991 | Val acc: 50.14% | LR: 0.001295
Epoch: 030 | Train loss: 0.9940 | Train acc: 50.99% | Val loss: 1.0039 | Val acc: 49.81% | LR: 0.001287
Epoch: 031 | Train loss: 0.9860 | Train acc: 51.24% | Val loss: 1.0270 | Val acc: 48.41% | LR: 0.001277
Epoch: 032 | Train loss: 0.9867 | Train acc: 51.54% | Val loss: 1.0192 | Val acc: 48.28% | LR: 0.001268
Epoch: 033 | Train loss: 1.0142 | Train acc: 50.11% | Val loss: 1.0553 | Val acc: 46.30% | LR: 0.001258
Epoch: 034 | Train loss: 0.9953 | Train acc: 50.45% | Val loss: 1.0206 | Val acc: 46.06% | LR: 0.001248
Epoch: 035 | Train loss: 1.0034 | Train acc: 49.83% | Val loss: 1.0178 | Val acc: 46.82% | LR: 0.001238
Epoch: 036 | Train loss: 0.9944 | Train acc: 50.60% | Val loss: 1.0057 | Val acc: 46.39% | LR: 0.001228
Epoch: 037 | Train loss: 0.9888 | Train acc: 51.03% | Val loss: 0.9919 | Val acc: 53.92% | LR: 0.001217
Epoch: 038 | Train loss: 0.9949 | Train acc: 50.53% | Val loss: 0.9523 | Val acc: 54.63% | LR: 0.001206
Epoch: 039 | Train loss: 0.9953 | Train acc: 50.43% | Val loss: 0.9396 | Val acc: 54.28% | LR: 0.001195
Epoch: 040 | Train loss: 0.9916 | Train acc: 50.77% | Val loss: 0.9486 | Val acc: 54.14% | LR: 0.001184
Epoch: 041 | Train loss: 0.9894 | Train acc: 50.66% | Val loss: 0.9402 | Val acc: 54.40% | LR: 0.001173
Epoch: 042 | Train loss: 0.9964 | Train acc: 50.33% | Val loss: 0.9575 | Val acc: 54.36% | LR: 0.001161
Epoch: 043 | Train loss: 0.9951 | Train acc: 50.23% | Val loss: 0.9687 | Val acc: 54.50% | LR: 0.001149
Epoch: 044 | Train loss: 0.9918 | Train acc: 50.48% | Val loss: 0.9608 | Val acc: 54.44% | LR: 0.001137
Epoch: 045 | Train loss: 0.9821 | Train acc: 51.32% | Val loss: 0.9530 | Val acc: 54.75% | LR: 0.001125
Epoch: 046 | Train loss: 0.9907 | Train acc: 50.58% | Val loss: 0.9600 | Val acc: 54.87% | LR: 0.001113
Epoch: 047 | Train loss: 0.9881 | Train acc: 50.85% | Val loss: 0.9835 | Val acc: 52.22% | LR: 0.001100
Epoch: 048 | Train loss: 0.9885 | Train acc: 50.69% | Val loss: 0.9664 | Val acc: 53.25% | LR: 0.001087
Epoch: 049 | Train loss: 0.9833 | Train acc: 51.26% | Val loss: 0.9955 | Val acc: 49.38% | LR: 0.001074
Epoch: 050 | Train loss: 0.9905 | Train acc: 50.64% | Val loss: 0.9854 | Val acc: 50.73% | LR: 0.001061
Epoch: 051 | Train loss: 0.9873 | Train acc: 51.05% | Val loss: 0.9973 | Val acc: 50.62% | LR: 0.001048
Epoch: 052 | Train loss: 0.9908 | Train acc: 50.66% | Val loss: 1.0495 | Val acc: 45.64% | LR: 0.001035
Epoch: 053 | Train loss: 0.9929 | Train acc: 50.56% | Val loss: 0.9670 | Val acc: 51.57% | LR: 0.001021
Epoch: 054 | Train loss: 0.9867 | Train acc: 51.04% | Val loss: 0.9894 | Val acc: 50.38% | LR: 0.001008
Epoch: 055 | Train loss: 0.9791 | Train acc: 51.42% | Val loss: 1.0113 | Val acc: 49.34% | LR: 0.000994
Epoch: 056 | Train loss: 0.9828 | Train acc: 51.08% | Val loss: 1.0360 | Val acc: 47.70% | LR: 0.000980
Epoch: 057 | Train loss: 0.9815 | Train acc: 51.30% | Val loss: 1.0141 | Val acc: 49.15% | LR: 0.000966
Epoch: 058 | Train loss: 0.9852 | Train acc: 50.88% | Val loss: 1.0150 | Val acc: 49.39% | LR: 0.000952
Epoch: 059 | Train loss: 0.9812 | Train acc: 51.13% | Val loss: 1.0101 | Val acc: 49.54% | LR: 0.000938
Epoch: 060 | Train loss: 0.9776 | Train acc: 51.36% | Val loss: 1.0073 | Val acc: 49.77% | LR: 0.000923
Epoch: 061 | Train loss: 0.9875 | Train acc: 50.80% | Val loss: 0.9815 | Val acc: 51.16% | LR: 0.000909
Epoch: 062 | Train loss: 0.9892 | Train acc: 50.54% | Val loss: 1.0114 | Val acc: 49.72% | LR: 0.000895
Epoch: 063 | Train loss: 0.9796 | Train acc: 51.26% | Val loss: 0.9937 | Val acc: 50.64% | LR: 0.000880
Epoch: 064 | Train loss: 0.9735 | Train acc: 51.66% | Val loss: 0.9934 | Val acc: 50.70% | LR: 0.000865
Epoch: 065 | Train loss: 0.9811 | Train acc: 51.24% | Val loss: 0.9869 | Val acc: 50.96% | LR: 0.000851
Epoch: 066 | Train loss: 0.9728 | Train acc: 51.62% | Val loss: 0.9918 | Val acc: 50.72% | LR: 0.000836
Epoch: 067 | Train loss: 0.9727 | Train acc: 51.69% | Val loss: 0.9842 | Val acc: 51.04% | LR: 0.000821
Epoch: 068 | Train loss: 0.9761 | Train acc: 51.43% | Val loss: 1.0203 | Val acc: 48.89% | LR: 0.000806
Epoch: 069 | Train loss: 0.9842 | Train acc: 50.98% | Val loss: 0.9954 | Val acc: 50.51% | LR: 0.000791
Epoch: 070 | Train loss: 0.9796 | Train acc: 51.18% | Val loss: 1.0368 | Val acc: 47.83% | LR: 0.000776
Epoch: 071 | Train loss: 0.9848 | Train acc: 50.83% | Val loss: 1.0555 | Val acc: 46.87% | LR: 0.000762
Epoch: 072 | Train loss: 0.9884 | Train acc: 50.62% | Val loss: 1.0331 | Val acc: 48.26% | LR: 0.000747
Epoch: 073 | Train loss: 0.9911 | Train acc: 50.39% | Val loss: 1.0305 | Val acc: 48.44% | LR: 0.000732
Epoch: 074 | Train loss: 0.9823 | Train acc: 51.06% | Val loss: 1.0193 | Val acc: 48.78% | LR: 0.000717
Epoch: 075 | Train loss: 0.9801 | Train acc: 51.19% | Val loss: 1.0144 | Val acc: 49.10% | LR: 0.000702
Epoch: 076 | Train loss: 0.9819 | Train acc: 51.10% | Val loss: 1.0123 | Val acc: 49.22% | LR: 0.000687
Epoch: 077 | Train loss: 0.9840 | Train acc: 50.90% | Val loss: 1.0201 | Val acc: 48.90% | LR: 0.000672
Epoch: 078 | Train loss: 0.9802 | Train acc: 51.13% | Val loss: 1.0263 | Val acc: 48.61% | LR: 0.000657
Epoch: 079 | Train loss: 0.9778 | Train acc: 51.24% | Val loss: 1.0506 | Val acc: 47.32% | LR: 0.000642
Epoch: 080 | Train loss: 0.9801 | Train acc: 51.15% | Val loss: 1.0221 | Val acc: 48.62% | LR: 0.000627
Epoch: 081 | Train loss: 0.9771 | Train acc: 51.51% | Val loss: 1.0340 | Val acc: 48.12% | LR: 0.000612
Epoch: 082 | Train loss: 0.9794 | Train acc: 51.25% | Val loss: 1.0466 | Val acc: 47.47% | LR: 0.000597
Epoch: 083 | Train loss: 0.9938 | Train acc: 50.27% | Val loss: 1.0340 | Val acc: 48.22% | LR: 0.000582
Epoch: 084 | Train loss: 0.9808 | Train acc: 51.04% | Val loss: 1.0282 | Val acc: 48.55% | LR: 0.000568
Epoch: 085 | Train loss: 0.9798 | Train acc: 51.05% | Val loss: 1.0357 | Val acc: 47.92% | LR: 0.000553
Epoch: 086 | Train loss: 0.9815 | Train acc: 51.05% | Val loss: 1.0334 | Val acc: 48.20% | LR: 0.000539
Epoch: 087 | Train loss: 0.9733 | Train acc: 51.67% | Val loss: 1.0363 | Val acc: 48.02% | LR: 0.000524
Epoch: 088 | Train loss: 0.9803 | Train acc: 51.14% | Val loss: 1.0409 | Val acc: 47.69% | LR: 0.000510
Epoch: 089 | Train loss: 0.9870 | Train acc: 50.75% | Val loss: 1.0318 | Val acc: 48.06% | LR: 0.000495
Epoch: 090 | Train loss: 0.9777 | Train acc: 51.25% | Val loss: 1.0536 | Val acc: 46.79% | LR: 0.000481
Epoch: 091 | Train loss: 0.9843 | Train acc: 50.91% | Val loss: 1.0409 | Val acc: 47.88% | LR: 0.000467
Epoch: 092 | Train loss: 0.9836 | Train acc: 50.87% | Val loss: 1.0591 | Val acc: 46.58% | LR: 0.000453
Epoch: 093 | Train loss: 0.9825 | Train acc: 51.05% | Val loss: 1.0400 | Val acc: 47.81% | LR: 0.000439
Epoch: 094 | Train loss: 0.9743 | Train acc: 51.60% | Val loss: 1.0489 | Val acc: 47.22% | LR: 0.000426
Epoch: 095 | Train loss: 0.9774 | Train acc: 51.33% | Val loss: 1.0383 | Val acc: 47.81% | LR: 0.000412
Epoch: 096 | Train loss: 0.9727 | Train acc: 51.70% | Val loss: 1.0473 | Val acc: 47.49% | LR: 0.000398
Epoch: 097 | Train loss: 0.9812 | Train acc: 51.15% | Val loss: 1.0496 | Val acc: 47.24% | LR: 0.000385
Epoch: 098 | Train loss: 0.9775 | Train acc: 51.19% | Val loss: 1.0346 | Val acc: 48.14% | LR: 0.000372
Epoch: 099 | Train loss: 0.9821 | Train acc: 51.04% | Val loss: 1.0654 | Val acc: 46.36% | LR: 0.000359
Epoch: 100 | Train loss: 0.9835 | Train acc: 50.96% | Val loss: 1.0210 | Val acc: 48.81% | LR: 0.000346
Epoch: 101 | Train loss: 0.9812 | Train acc: 51.12% | Val loss: 1.0146 | Val acc: 49.15% | LR: 0.000333
Epoch: 102 | Train loss: 0.9779 | Train acc: 51.26% | Val loss: 1.0094 | Val acc: 49.41% | LR: 0.000321
Epoch: 103 | Train loss: 0.9816 | Train acc: 51.08% | Val loss: 1.0120 | Val acc: 49.25% | LR: 0.000308
Epoch: 104 | Train loss: 0.9844 | Train acc: 50.92% | Val loss: 1.0150 | Val acc: 49.25% | LR: 0.000296
Epoch: 105 | Train loss: 0.9755 | Train acc: 51.46% | Val loss: 1.0138 | Val acc: 49.09% | LR: 0.000284
Epoch: 106 | Train loss: 0.9896 | Train acc: 50.51% | Val loss: 1.0146 | Val acc: 49.21% | LR: 0.000272
Epoch: 107 | Train loss: 0.9830 | Train acc: 50.94% | Val loss: 1.0162 | Val acc: 49.13% | LR: 0.000260
Epoch: 108 | Train loss: 0.9800 | Train acc: 51.10% | Val loss: 1.0238 | Val acc: 48.65% | LR: 0.000249
Epoch: 109 | Train loss: 0.9846 | Train acc: 50.85% | Val loss: 1.0212 | Val acc: 48.83% | LR: 0.000238
Epoch: 110 | Train loss: 0.9867 | Train acc: 50.79% | Val loss: 1.0128 | Val acc: 49.24% | LR: 0.000227
Epoch: 111 | Train loss: 0.9863 | Train acc: 50.86% | Val loss: 1.0116 | Val acc: 49.11% | LR: 0.000216
Epoch: 112 | Train loss: 0.9785 | Train acc: 51.29% | Val loss: 1.0154 | Val acc: 49.17% | LR: 0.000205
Epoch: 113 | Train loss: 0.9761 | Train acc: 51.42% | Val loss: 1.0153 | Val acc: 49.03% | LR: 0.000195
Epoch: 114 | Train loss: 0.9852 | Train acc: 50.90% | Val loss: 1.0143 | Val acc: 49.05% | LR: 0.000185
Epoch: 115 | Train loss: 0.9781 | Train acc: 51.24% | Val loss: 1.0161 | Val acc: 48.99% | LR: 0.000175
Epoch: 116 | Train loss: 0.9806 | Train acc: 51.07% | Val loss: 1.0160 | Val acc: 49.09% | LR: 0.000165
Epoch: 117 | Train loss: 0.9731 | Train acc: 51.52% | Val loss: 1.0165 | Val acc: 48.99% | LR: 0.000156
Epoch: 118 | Train loss: 0.9771 | Train acc: 51.29% | Val loss: 1.0151 | Val acc: 49.01% | LR: 0.000147
Epoch: 119 | Train loss: 0.9828 | Train acc: 50.98% | Val loss: 1.0166 | Val acc: 48.93% | LR: 0.000138
Epoch: 120 | Train loss: 0.9769 | Train acc: 51.33% | Val loss: 1.0135 | Val acc: 49.18% | LR: 0.000129
Epoch: 121 | Train loss: 0.9808 | Train acc: 51.16% | Val loss: 1.0174 | Val acc: 49.04% | LR: 0.000121
Epoch: 122 | Train loss: 0.9816 | Train acc: 51.08% | Val loss: 1.0160 | Val acc: 49.06% | LR: 0.000112
Epoch: 123 | Train loss: 0.9843 | Train acc: 50.91% | Val loss: 1.0158 | Val acc: 49.09% | LR: 0.000104
Epoch: 124 | Train loss: 0.9833 | Train acc: 50.92% | Val loss: 1.0163 | Val acc: 49.01% | LR: 0.000097
Epoch: 125 | Train loss: 0.9754 | Train acc: 51.45% | Val loss: 1.0167 | Val acc: 49.10% | LR: 0.000090
Epoch: 126 | Train loss: 0.9744 | Train acc: 51.45% | Val loss: 1.0168 | Val acc: 49.08% | LR: 0.000082
Epoch: 127 | Train loss: 0.9805 | Train acc: 51.19% | Val loss: 1.0159 | Val acc: 49.07% | LR: 0.000076
Epoch: 128 | Train loss: 0.9758 | Train acc: 51.44% | Val loss: 1.0160 | Val acc: 49.12% | LR: 0.000069
Epoch: 129 | Train loss: 0.9783 | Train acc: 51.27% | Val loss: 1.0165 | Val acc: 49.09% | LR: 0.000063
Epoch: 130 | Train loss: 0.9791 | Train acc: 51.18% | Val loss: 1.0168 | Val acc: 49.04% | LR: 0.000057
Epoch: 131 | Train loss: 0.9777 | Train acc: 51.27% | Val loss: 1.0166 | Val acc: 49.07% | LR: 0.000051
Epoch: 132 | Train loss: 0.9841 | Train acc: 50.92% | Val loss: 1.0164 | Val acc: 49.09% | LR: 0.000046
Epoch: 133 | Train loss: 0.9778 | Train acc: 51.19% | Val loss: 1.0164 | Val acc: 49.07% | LR: 0.000041
Epoch: 134 | Train loss: 0.9808 | Train acc: 51.10% | Val loss: 1.0168 | Val acc: 49.07% | LR: 0.000036
Epoch: 135 | Train loss: 0.9773 | Train acc: 51.36% | Val loss: 1.0167 | Val acc: 49.07% | LR: 0.000032
Epoch: 136 | Train loss: 0.9850 | Train acc: 50.83% | Val loss: 1.0163 | Val acc: 49.10% | LR: 0.000027
Epoch: 137 | Train loss: 0.9772 | Train acc: 51.37% | Val loss: 1.0162 | Val acc: 49.10% | LR: 0.000023
Epoch: 138 | Train loss: 0.9729 | Train acc: 51.54% | Val loss: 1.0164 | Val acc: 49.10% | LR: 0.000020
Epoch: 139 | Train loss: 0.9820 | Train acc: 51.01% | Val loss: 1.0164 | Val acc: 49.10% | LR: 0.000017
Epoch: 140 | Train loss: 0.9798 | Train acc: 51.10% | Val loss: 1.0164 | Val acc: 49.10% | LR: 0.000014
Epoch: 141 | Train loss: 0.9798 | Train acc: 51.19% | Val loss: 1.0164 | Val acc: 49.10% | LR: 0.000011
Epoch: 142 | Train loss: 0.9795 | Train acc: 51.19% | Val loss: 1.0164 | Val acc: 49.10% | LR: 0.000009
Epoch: 143 | Train loss: 0.9720 | Train acc: 51.63% | Val loss: 1.0164 | Val acc: 49.10% | LR: 0.000007
Epoch: 144 | Train loss: 0.9836 | Train acc: 50.92% | Val loss: 1.0164 | Val acc: 49.12% | LR: 0.000005
Epoch: 145 | Train loss: 0.9879 | Train acc: 50.66% | Val loss: 1.0164 | Val acc: 49.12% | LR: 0.000004
Epoch: 146 | Train loss: 0.9838 | Train acc: 50.92% | Val loss: 1.0163 | Val acc: 49.12% | LR: 0.000002
Epoch: 147 | Train loss: 0.9750 | Train acc: 51.46% | Val loss: 1.0163 | Val acc: 49.12% | LR: 0.000002
Epoch: 148 | Train loss: 0.9750 | Train acc: 51.46% | Val loss: 1.0163 | Val acc: 49.12% | LR: 0.000001
Epoch: 149 | Train loss: 0.9770 | Train acc: 51.28% | Val loss: 1.0163 | Val acc: 49.12% | LR: 0.000001

[I 2025-09-23 02:23:29,083] Trial 18 finished with value: 0.5486563920974732 and parameters: {'lr': 0.0014321494075194728, 'hidden_size': 65, 'dropout': 0.2698550231706687, 'weight_decay': 0.19451177194909317}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.4045 | Train acc: 50.22% | Val loss: 0.9932 | Val acc: 54.05% | LR: 0.004654
Epoch: 001 | Train loss: 1.0400 | Train acc: 49.37% | Val loss: 1.0135 | Val acc: 45.95% | LR: 0.004652
Epoch: 002 | Train loss: 1.0132 | Train acc: 50.37% | Val loss: 1.0017 | Val acc: 48.08% | LR: 0.004650
Epoch: 003 | Train loss: 1.0230 | Train acc: 49.47% | Val loss: 0.9974 | Val acc: 51.39% | LR: 0.004646
Epoch: 004 | Train loss: 1.0202 | Train acc: 49.88% | Val loss: 0.9996 | Val acc: 49.34% | LR: 0.004642
Epoch: 005 | Train loss: 1.0167 | Train acc: 49.89% | Val loss: 1.0024 | Val acc: 48.71% | LR: 0.004636
Epoch: 006 | Train loss: 1.0103 | Train acc: 50.72% | Val loss: 0.9878 | Val acc: 53.84% | LR: 0.004629
Epoch: 007 | Train loss: 1.0085 | Train acc: 50.32% | Val loss: 0.9953 | Val acc: 51.44% | LR: 0.004622
Epoch: 008 | Train loss: 1.0183 | Train acc: 49.30% | Val loss: 0.9928 | Val acc: 53.44% | LR: 0.004613
Epoch: 009 | Train loss: 1.0230 | Train acc: 49.16% | Val loss: 1.0024 | Val acc: 46.88% | LR: 0.004603
Epoch: 010 | Train loss: 1.0370 | Train acc: 50.08% | Val loss: 0.9940 | Val acc: 53.65% | LR: 0.004593
Epoch: 011 | Train loss: 1.0099 | Train acc: 50.10% | Val loss: 0.9975 | Val acc: 53.85% | LR: 0.004581
Epoch: 012 | Train loss: 1.0172 | Train acc: 50.42% | Val loss: 0.9914 | Val acc: 54.32% | LR: 0.004569
Epoch: 013 | Train loss: 1.0192 | Train acc: 50.02% | Val loss: 0.9907 | Val acc: 53.65% | LR: 0.004555
Epoch: 014 | Train loss: 1.0103 | Train acc: 50.73% | Val loss: 1.0049 | Val acc: 46.02% | LR: 0.004540
Epoch: 015 | Train loss: 1.0215 | Train acc: 49.86% | Val loss: 0.9977 | Val acc: 50.90% | LR: 0.004525
Epoch: 016 | Train loss: 1.0108 | Train acc: 49.90% | Val loss: 1.0050 | Val acc: 49.04% | LR: 0.004508
Epoch: 017 | Train loss: 1.0099 | Train acc: 50.40% | Val loss: 1.0007 | Val acc: 49.55% | LR: 0.004491
Epoch: 018 | Train loss: 1.0157 | Train acc: 49.85% | Val loss: 1.0002 | Val acc: 50.07% | LR: 0.004472
Epoch: 019 | Train loss: 1.0150 | Train acc: 49.78% | Val loss: 1.0001 | Val acc: 49.24% | LR: 0.004453
Epoch: 020 | Train loss: 1.0110 | Train acc: 49.87% | Val loss: 1.0034 | Val acc: 48.20% | LR: 0.004433
Epoch: 021 | Train loss: 1.0083 | Train acc: 50.37% | Val loss: 1.0067 | Val acc: 46.29% | LR: 0.004412
Epoch: 022 | Train loss: 1.0113 | Train acc: 49.91% | Val loss: 1.0010 | Val acc: 49.08% | LR: 0.004389
Epoch: 023 | Train loss: 1.0060 | Train acc: 50.74% | Val loss: 0.9990 | Val acc: 51.01% | LR: 0.004366
Epoch: 024 | Train loss: 1.0184 | Train acc: 49.94% | Val loss: 1.0039 | Val acc: 46.86% | LR: 0.004343
Epoch: 025 | Train loss: 1.0153 | Train acc: 49.95% | Val loss: 0.9943 | Val acc: 53.47% | LR: 0.004318
Epoch: 026 | Train loss: 1.0111 | Train acc: 49.82% | Val loss: 1.0109 | Val acc: 45.83% | LR: 0.004292
Epoch: 027 | Train loss: 1.0166 | Train acc: 49.77% | Val loss: 0.9916 | Val acc: 54.03% | LR: 0.004266
Epoch: 028 | Train loss: 1.0118 | Train acc: 49.87% | Val loss: 1.0094 | Val acc: 45.97% | LR: 0.004238
Epoch: 029 | Train loss: 1.0158 | Train acc: 49.40% | Val loss: 0.9984 | Val acc: 49.95% | LR: 0.004210
Epoch: 030 | Train loss: 1.0114 | Train acc: 49.72% | Val loss: 0.9945 | Val acc: 53.41% | LR: 0.004181
Epoch: 031 | Train loss: 1.0146 | Train acc: 50.36% | Val loss: 0.9986 | Val acc: 49.84% | LR: 0.004151
Epoch: 032 | Train loss: 1.0669 | Train acc: 50.49% | Val loss: 1.0023 | Val acc: 47.05% | LR: 0.004120
Epoch: 033 | Train loss: 1.0252 | Train acc: 50.01% | Val loss: 1.0030 | Val acc: 46.21% | LR: 0.004089
Epoch: 034 | Train loss: 1.0164 | Train acc: 49.77% | Val loss: 1.0200 | Val acc: 45.80% | LR: 0.004057
Epoch: 035 | Train loss: 1.0243 | Train acc: 50.46% | Val loss: 0.9969 | Val acc: 52.69% | LR: 0.004024
Epoch: 036 | Train loss: 1.0933 | Train acc: 49.85% | Val loss: 1.0073 | Val acc: 45.98% | LR: 0.003990
Epoch: 037 | Train loss: 1.0338 | Train acc: 49.38% | Val loss: 0.9961 | Val acc: 52.96% | LR: 0.003955
Epoch: 038 | Train loss: 1.0229 | Train acc: 50.09% | Val loss: 1.0238 | Val acc: 45.99% | LR: 0.003920
Epoch: 039 | Train loss: 1.0149 | Train acc: 49.53% | Val loss: 1.0016 | Val acc: 49.02% | LR: 0.003884
Epoch: 040 | Train loss: 1.0212 | Train acc: 49.82% | Val loss: 0.9858 | Val acc: 54.05% | LR: 0.003848
Epoch: 041 | Train loss: 1.0522 | Train acc: 49.90% | Val loss: 1.0043 | Val acc: 46.11% | LR: 0.003811
Epoch: 042 | Train loss: 1.0220 | Train acc: 49.31% | Val loss: 1.0050 | Val acc: 46.88% | LR: 0.003773
Epoch: 043 | Train loss: 1.0156 | Train acc: 49.91% | Val loss: 0.9878 | Val acc: 54.07% | LR: 0.003734
Epoch: 044 | Train loss: 1.0176 | Train acc: 49.62% | Val loss: 0.9834 | Val acc: 54.40% | LR: 0.003695
Epoch: 045 | Train loss: 1.0072 | Train acc: 50.66% | Val loss: 0.9881 | Val acc: 54.70% | LR: 0.003655
Epoch: 046 | Train loss: 1.0083 | Train acc: 50.28% | Val loss: 0.9978 | Val acc: 51.83% | LR: 0.003615
Epoch: 047 | Train loss: 1.0096 | Train acc: 49.95% | Val loss: 0.9970 | Val acc: 52.44% | LR: 0.003574
Epoch: 048 | Train loss: 1.0058 | Train acc: 50.94% | Val loss: 1.0006 | Val acc: 48.80% | LR: 0.003533
Epoch: 049 | Train loss: 1.0105 | Train acc: 49.69% | Val loss: 0.9966 | Val acc: 53.33% | LR: 0.003491
Epoch: 050 | Train loss: 1.0124 | Train acc: 49.39% | Val loss: 1.0103 | Val acc: 45.95% | LR: 0.003448
Epoch: 051 | Train loss: 1.0054 | Train acc: 50.17% | Val loss: 0.9960 | Val acc: 52.91% | LR: 0.003406
Epoch: 052 | Train loss: 1.0128 | Train acc: 49.80% | Val loss: 0.9935 | Val acc: 53.76% | LR: 0.003362
Epoch: 053 | Train loss: 1.0099 | Train acc: 49.80% | Val loss: 1.0096 | Val acc: 45.95% | LR: 0.003318
Epoch: 054 | Train loss: 1.0134 | Train acc: 49.75% | Val loss: 0.9906 | Val acc: 54.09% | LR: 0.003274
Epoch: 055 | Train loss: 1.0119 | Train acc: 50.03% | Val loss: 0.9933 | Val acc: 54.45% | LR: 0.003229
Epoch: 056 | Train loss: 1.0057 | Train acc: 50.24% | Val loss: 0.9996 | Val acc: 49.87% | LR: 0.003184
Epoch: 057 | Train loss: 1.0109 | Train acc: 49.99% | Val loss: 0.9993 | Val acc: 50.08% | LR: 0.003139
Epoch: 058 | Train loss: 1.0050 | Train acc: 50.16% | Val loss: 1.0047 | Val acc: 47.36% | LR: 0.003093
Epoch: 059 | Train loss: 1.0006 | Train acc: 50.39% | Val loss: 1.0009 | Val acc: 49.24% | LR: 0.003047
Epoch: 060 | Train loss: 1.0078 | Train acc: 50.50% | Val loss: 1.0043 | Val acc: 47.37% | LR: 0.003000
Epoch: 061 | Train loss: 1.0112 | Train acc: 49.38% | Val loss: 0.9964 | Val acc: 51.86% | LR: 0.002953
Epoch: 062 | Train loss: 1.0106 | Train acc: 49.44% | Val loss: 0.9922 | Val acc: 53.42% | LR: 0.002906
Epoch: 063 | Train loss: 1.0025 | Train acc: 50.74% | Val loss: 1.0021 | Val acc: 48.37% | LR: 0.002859
Epoch: 064 | Train loss: 0.9993 | Train acc: 50.22% | Val loss: 0.9972 | Val acc: 50.37% | LR: 0.002811
Epoch: 065 | Train loss: 1.0050 | Train acc: 50.13% | Val loss: 0.9891 | Val acc: 52.45% | LR: 0.002764
Epoch: 066 | Train loss: 1.0035 | Train acc: 49.74% | Val loss: 1.0007 | Val acc: 49.90% | LR: 0.002716
Epoch: 067 | Train loss: 1.0001 | Train acc: 50.60% | Val loss: 0.9987 | Val acc: 49.46% | LR: 0.002668
Epoch: 068 | Train loss: 1.0456 | Train acc: 49.59% | Val loss: 1.0013 | Val acc: 48.73% | LR: 0.002619
Epoch: 069 | Train loss: 1.0031 | Train acc: 50.19% | Val loss: 1.0034 | Val acc: 47.42% | LR: 0.002571
Epoch: 070 | Train loss: 0.9943 | Train acc: 50.82% | Val loss: 0.9936 | Val acc: 53.27% | LR: 0.002522
Epoch: 071 | Train loss: 1.0050 | Train acc: 50.05% | Val loss: 0.9874 | Val acc: 54.06% | LR: 0.002474
Epoch: 072 | Train loss: 1.0039 | Train acc: 50.53% | Val loss: 0.9938 | Val acc: 52.31% | LR: 0.002425
Epoch: 073 | Train loss: 1.0056 | Train acc: 50.22% | Val loss: 0.9933 | Val acc: 51.90% | LR: 0.002376
Epoch: 074 | Train loss: 0.9937 | Train acc: 51.07% | Val loss: 0.9936 | Val acc: 51.10% | LR: 0.002328
Epoch: 075 | Train loss: 1.0060 | Train acc: 50.23% | Val loss: 1.0007 | Val acc: 49.68% | LR: 0.002279
Epoch: 076 | Train loss: 1.0090 | Train acc: 49.89% | Val loss: 1.0094 | Val acc: 46.40% | LR: 0.002230
Epoch: 077 | Train loss: 1.0001 | Train acc: 50.87% | Val loss: 1.0101 | Val acc: 45.97% | LR: 0.002182
Epoch: 078 | Train loss: 0.9961 | Train acc: 50.78% | Val loss: 0.9984 | Val acc: 49.80% | LR: 0.002133
Epoch: 079 | Train loss: 1.0048 | Train acc: 49.84% | Val loss: 1.0018 | Val acc: 49.15% | LR: 0.002084
Epoch: 080 | Train loss: 1.0008 | Train acc: 50.51% | Val loss: 1.0011 | Val acc: 49.12% | LR: 0.002036
Epoch: 081 | Train loss: 1.0021 | Train acc: 50.40% | Val loss: 0.9997 | Val acc: 49.32% | LR: 0.001988
Epoch: 082 | Train loss: 0.9953 | Train acc: 50.99% | Val loss: 1.0054 | Val acc: 47.70% | LR: 0.001940
Epoch: 083 | Train loss: 0.9991 | Train acc: 50.57% | Val loss: 1.0024 | Val acc: 48.10% | LR: 0.001892
Epoch: 084 | Train loss: 1.0074 | Train acc: 50.04% | Val loss: 0.9986 | Val acc: 48.77% | LR: 0.001844
Epoch: 085 | Train loss: 1.0031 | Train acc: 49.94% | Val loss: 0.9955 | Val acc: 49.58% | LR: 0.001796
Epoch: 086 | Train loss: 1.0030 | Train acc: 49.90% | Val loss: 0.9939 | Val acc: 50.14% | LR: 0.001749
Epoch: 087 | Train loss: 1.0012 | Train acc: 50.22% | Val loss: 0.9966 | Val acc: 49.78% | LR: 0.001702
Epoch: 088 | Train loss: 0.9985 | Train acc: 50.50% | Val loss: 1.0004 | Val acc: 49.61% | LR: 0.001655
Epoch: 089 | Train loss: 0.9942 | Train acc: 51.08% | Val loss: 0.9979 | Val acc: 49.69% | LR: 0.001609
Epoch: 090 | Train loss: 1.0006 | Train acc: 50.47% | Val loss: 0.9917 | Val acc: 51.84% | LR: 0.001562
Epoch: 091 | Train loss: 1.0007 | Train acc: 49.89% | Val loss: 0.9967 | Val acc: 49.72% | LR: 0.001517
Epoch: 092 | Train loss: 0.9932 | Train acc: 51.13% | Val loss: 1.0009 | Val acc: 48.95% | LR: 0.001471
Epoch: 093 | Train loss: 0.9938 | Train acc: 51.11% | Val loss: 1.0039 | Val acc: 48.89% | LR: 0.001426
Epoch: 094 | Train loss: 0.9976 | Train acc: 50.16% | Val loss: 1.0029 | Val acc: 48.71% | LR: 0.001381
Epoch: 095 | Train loss: 1.0051 | Train acc: 49.80% | Val loss: 1.0017 | Val acc: 48.68% | LR: 0.001337
Epoch: 096 | Train loss: 1.0045 | Train acc: 50.21% | Val loss: 1.0003 | Val acc: 48.86% | LR: 0.001293
Epoch: 097 | Train loss: 0.9954 | Train acc: 50.76% | Val loss: 1.0042 | Val acc: 48.56% | LR: 0.001250
Epoch: 098 | Train loss: 0.9976 | Train acc: 50.05% | Val loss: 1.0046 | Val acc: 48.61% | LR: 0.001207
Epoch: 099 | Train loss: 1.0023 | Train acc: 50.13% | Val loss: 0.9951 | Val acc: 49.93% | LR: 0.001164
Epoch: 100 | Train loss: 0.9932 | Train acc: 51.36% | Val loss: 0.9995 | Val acc: 49.14% | LR: 0.001122
Epoch: 101 | Train loss: 0.9969 | Train acc: 50.93% | Val loss: 1.0059 | Val acc: 48.41% | LR: 0.001081
Epoch: 102 | Train loss: 0.9991 | Train acc: 49.95% | Val loss: 1.0028 | Val acc: 48.37% | LR: 0.001040
Epoch: 103 | Train loss: 1.0030 | Train acc: 49.31% | Val loss: 0.9961 | Val acc: 49.32% | LR: 0.001000
Epoch: 104 | Train loss: 0.9992 | Train acc: 50.25% | Val loss: 0.9975 | Val acc: 49.02% | LR: 0.000960
Epoch: 105 | Train loss: 0.9954 | Train acc: 50.90% | Val loss: 1.0008 | Val acc: 48.54% | LR: 0.000921
Epoch: 106 | Train loss: 0.9957 | Train acc: 50.37% | Val loss: 1.0014 | Val acc: 48.39% | LR: 0.000882
Epoch: 107 | Train loss: 1.0000 | Train acc: 50.30% | Val loss: 0.9967 | Val acc: 49.01% | LR: 0.000845
Epoch: 108 | Train loss: 0.9964 | Train acc: 50.08% | Val loss: 0.9993 | Val acc: 48.61% | LR: 0.000807
Epoch: 109 | Train loss: 0.9958 | Train acc: 50.59% | Val loss: 1.0022 | Val acc: 48.21% | LR: 0.000771
Epoch: 110 | Train loss: 0.9939 | Train acc: 50.53% | Val loss: 1.0038 | Val acc: 48.09% | LR: 0.000735
Epoch: 111 | Train loss: 0.9975 | Train acc: 50.37% | Val loss: 1.0053 | Val acc: 47.74% | LR: 0.000700
Epoch: 112 | Train loss: 0.9933 | Train acc: 50.69% | Val loss: 1.0029 | Val acc: 48.31% | LR: 0.000665
Epoch: 113 | Train loss: 0.9956 | Train acc: 50.64% | Val loss: 1.0026 | Val acc: 48.51% | LR: 0.000632
Epoch: 114 | Train loss: 0.9917 | Train acc: 50.89% | Val loss: 1.0051 | Val acc: 47.97% | LR: 0.000599
Epoch: 115 | Train loss: 0.9933 | Train acc: 50.74% | Val loss: 1.0044 | Val acc: 48.09% | LR: 0.000566
Epoch: 116 | Train loss: 0.9983 | Train acc: 50.39% | Val loss: 1.0026 | Val acc: 48.49% | LR: 0.000535
Epoch: 117 | Train loss: 1.0029 | Train acc: 49.79% | Val loss: 1.0080 | Val acc: 47.81% | LR: 0.000504
Epoch: 118 | Train loss: 0.9955 | Train acc: 50.32% | Val loss: 1.0074 | Val acc: 47.56% | LR: 0.000474
Epoch: 119 | Train loss: 1.0003 | Train acc: 50.08% | Val loss: 1.0043 | Val acc: 48.27% | LR: 0.000445
Epoch: 120 | Train loss: 0.9957 | Train acc: 50.60% | Val loss: 1.0032 | Val acc: 48.35% | LR: 0.000417
Epoch: 121 | Train loss: 0.9950 | Train acc: 50.59% | Val loss: 1.0007 | Val acc: 48.61% | LR: 0.000390
Epoch: 122 | Train loss: 0.9965 | Train acc: 50.78% | Val loss: 1.0002 | Val acc: 48.92% | LR: 0.000363
Epoch: 123 | Train loss: 0.9969 | Train acc: 50.25% | Val loss: 0.9983 | Val acc: 48.87% | LR: 0.000338
Epoch: 124 | Train loss: 0.9945 | Train acc: 50.38% | Val loss: 0.9987 | Val acc: 48.88% | LR: 0.000313
Epoch: 125 | Train loss: 1.0016 | Train acc: 50.63% | Val loss: 0.9987 | Val acc: 48.86% | LR: 0.000289
Epoch: 126 | Train loss: 0.9943 | Train acc: 51.23% | Val loss: 0.9990 | Val acc: 48.87% | LR: 0.000266
Epoch: 127 | Train loss: 0.9895 | Train acc: 51.00% | Val loss: 0.9995 | Val acc: 48.81% | LR: 0.000244
Epoch: 128 | Train loss: 0.9978 | Train acc: 50.21% | Val loss: 0.9993 | Val acc: 48.83% | LR: 0.000222
Epoch: 129 | Train loss: 0.9954 | Train acc: 50.63% | Val loss: 0.9990 | Val acc: 48.85% | LR: 0.000202
Epoch: 130 | Train loss: 0.9926 | Train acc: 50.76% | Val loss: 0.9979 | Val acc: 48.82% | LR: 0.000183
Epoch: 131 | Train loss: 0.9961 | Train acc: 50.69% | Val loss: 0.9975 | Val acc: 48.86% | LR: 0.000164
Epoch: 132 | Train loss: 0.9926 | Train acc: 50.91% | Val loss: 0.9968 | Val acc: 48.84% | LR: 0.000147
Epoch: 133 | Train loss: 0.9896 | Train acc: 51.60% | Val loss: 0.9966 | Val acc: 48.82% | LR: 0.000130
Epoch: 134 | Train loss: 0.9902 | Train acc: 50.81% | Val loss: 0.9969 | Val acc: 48.80% | LR: 0.000115
Epoch: 135 | Train loss: 0.9952 | Train acc: 50.71% | Val loss: 0.9971 | Val acc: 48.82% | LR: 0.000100
Epoch: 136 | Train loss: 0.9953 | Train acc: 50.74% | Val loss: 0.9980 | Val acc: 48.81% | LR: 0.000087
Epoch: 137 | Train loss: 0.9978 | Train acc: 50.58% | Val loss: 0.9984 | Val acc: 48.71% | LR: 0.000074
Epoch: 138 | Train loss: 0.9970 | Train acc: 50.19% | Val loss: 0.9983 | Val acc: 48.71% | LR: 0.000062
Epoch: 139 | Train loss: 0.9903 | Train acc: 51.18% | Val loss: 0.9983 | Val acc: 48.71% | LR: 0.000052
Epoch: 140 | Train loss: 0.9868 | Train acc: 51.75% | Val loss: 0.9985 | Val acc: 48.75% | LR: 0.000042
Epoch: 141 | Train loss: 0.9930 | Train acc: 50.74% | Val loss: 0.9985 | Val acc: 48.73% | LR: 0.000034
Epoch: 142 | Train loss: 0.9956 | Train acc: 50.66% | Val loss: 0.9985 | Val acc: 48.75% | LR: 0.000026
Epoch: 143 | Train loss: 0.9924 | Train acc: 50.96% | Val loss: 0.9985 | Val acc: 48.77% | LR: 0.000019
Epoch: 144 | Train loss: 0.9908 | Train acc: 51.29% | Val loss: 0.9986 | Val acc: 48.73% | LR: 0.000014
Epoch: 145 | Train loss: 0.9947 | Train acc: 50.57% | Val loss: 0.9987 | Val acc: 48.69% | LR: 0.000009
Epoch: 146 | Train loss: 0.9976 | Train acc: 50.70% | Val loss: 0.9987 | Val acc: 48.69% | LR: 0.000006
Epoch: 147 | Train loss: 0.9883 | Train acc: 51.37% | Val loss: 0.9987 | Val acc: 48.73% | LR: 0.000003
Epoch: 148 | Train loss: 0.9914 | Train acc: 51.27% | Val loss: 0.9987 | Val acc: 48.73% | LR: 0.000002
Epoch: 149 | Train loss: 0.9964 | Train acc: 50.76% | Val loss: 0.9987 | Val acc: 48.73% | LR: 0.000001

[I 2025-09-23 02:25:40,098] Trial 19 finished with value: 0.5469914674758911 and parameters: {'lr': 0.004654261841861048, 'hidden_size': 206, 'dropout': 0.0777685160252286, 'weight_decay': 0.9668357435245012}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.0323 | Train acc: 50.17% | Val loss: 0.9928 | Val acc: 51.41% | LR: 0.002915
Epoch: 001 | Train loss: 0.9908 | Train acc: 51.08% | Val loss: 0.9485 | Val acc: 54.05% | LR: 0.002914
Epoch: 002 | Train loss: 0.9937 | Train acc: 50.47% | Val loss: 0.9841 | Val acc: 52.13% | LR: 0.002912
Epoch: 003 | Train loss: 0.9970 | Train acc: 50.14% | Val loss: 0.9814 | Val acc: 50.90% | LR: 0.002910
Epoch: 004 | Train loss: 0.9919 | Train acc: 50.58% | Val loss: 1.0090 | Val acc: 48.71% | LR: 0.002907
Epoch: 005 | Train loss: 0.9951 | Train acc: 50.46% | Val loss: 1.0424 | Val acc: 47.97% | LR: 0.002903
Epoch: 006 | Train loss: 0.9931 | Train acc: 50.49% | Val loss: 1.0111 | Val acc: 48.98% | LR: 0.002899
Epoch: 007 | Train loss: 0.9977 | Train acc: 50.70% | Val loss: 1.0220 | Val acc: 47.93% | LR: 0.002895
Epoch: 008 | Train loss: 0.9934 | Train acc: 50.76% | Val loss: 1.0301 | Val acc: 47.85% | LR: 0.002889
Epoch: 009 | Train loss: 0.9895 | Train acc: 51.02% | Val loss: 0.9930 | Val acc: 50.01% | LR: 0.002883
Epoch: 010 | Train loss: 0.9780 | Train acc: 51.71% | Val loss: 1.0125 | Val acc: 49.91% | LR: 0.002876
Epoch: 011 | Train loss: 0.9906 | Train acc: 50.89% | Val loss: 1.0120 | Val acc: 48.24% | LR: 0.002869
Epoch: 012 | Train loss: 0.9933 | Train acc: 50.17% | Val loss: 1.0174 | Val acc: 49.32% | LR: 0.002861
Epoch: 013 | Train loss: 0.9888 | Train acc: 51.17% | Val loss: 1.0113 | Val acc: 49.73% | LR: 0.002853
Epoch: 014 | Train loss: 0.9901 | Train acc: 50.82% | Val loss: 0.9654 | Val acc: 52.34% | LR: 0.002844
Epoch: 015 | Train loss: 0.9928 | Train acc: 50.38% | Val loss: 0.9855 | Val acc: 50.58% | LR: 0.002834
Epoch: 016 | Train loss: 0.9856 | Train acc: 51.18% | Val loss: 0.9949 | Val acc: 50.07% | LR: 0.002824
Epoch: 017 | Train loss: 0.9871 | Train acc: 51.09% | Val loss: 0.9941 | Val acc: 50.06% | LR: 0.002813
Epoch: 018 | Train loss: 0.9855 | Train acc: 51.00% | Val loss: 0.9868 | Val acc: 50.66% | LR: 0.002801
Epoch: 019 | Train loss: 0.9836 | Train acc: 51.04% | Val loss: 0.9894 | Val acc: 50.98% | LR: 0.002789
Epoch: 020 | Train loss: 0.9855 | Train acc: 51.03% | Val loss: 0.9985 | Val acc: 50.04% | LR: 0.002776
Epoch: 021 | Train loss: 0.9855 | Train acc: 51.13% | Val loss: 1.0125 | Val acc: 49.34% | LR: 0.002763
Epoch: 022 | Train loss: 0.9850 | Train acc: 50.94% | Val loss: 1.0631 | Val acc: 46.33% | LR: 0.002749
Epoch: 023 | Train loss: 0.9834 | Train acc: 51.09% | Val loss: 1.0086 | Val acc: 49.27% | LR: 0.002735
Epoch: 024 | Train loss: 0.9989 | Train acc: 49.66% | Val loss: 0.9938 | Val acc: 49.48% | LR: 0.002720
Epoch: 025 | Train loss: 0.9898 | Train acc: 51.39% | Val loss: 0.9961 | Val acc: 49.73% | LR: 0.002704
Epoch: 026 | Train loss: 0.9809 | Train acc: 51.48% | Val loss: 0.9991 | Val acc: 50.53% | LR: 0.002688
Epoch: 027 | Train loss: 0.9908 | Train acc: 50.47% | Val loss: 0.9750 | Val acc: 51.59% | LR: 0.002671
Epoch: 028 | Train loss: 0.9861 | Train acc: 50.64% | Val loss: 0.9684 | Val acc: 51.74% | LR: 0.002654
Epoch: 029 | Train loss: 0.9877 | Train acc: 50.37% | Val loss: 0.9751 | Val acc: 51.46% | LR: 0.002637
Epoch: 030 | Train loss: 0.9829 | Train acc: 50.91% | Val loss: 0.9801 | Val acc: 51.38% | LR: 0.002618
Epoch: 031 | Train loss: 0.9849 | Train acc: 51.15% | Val loss: 0.9746 | Val acc: 51.48% | LR: 0.002600
Epoch: 032 | Train loss: 0.9910 | Train acc: 50.34% | Val loss: 0.9748 | Val acc: 51.51% | LR: 0.002581
Epoch: 033 | Train loss: 0.9786 | Train acc: 51.52% | Val loss: 0.9795 | Val acc: 51.44% | LR: 0.002561
Epoch: 034 | Train loss: 0.9943 | Train acc: 50.05% | Val loss: 0.9762 | Val acc: 51.56% | LR: 0.002541
Epoch: 035 | Train loss: 0.9877 | Train acc: 50.70% | Val loss: 0.9683 | Val acc: 52.15% | LR: 0.002520
Epoch: 036 | Train loss: 0.9890 | Train acc: 50.88% | Val loss: 0.9752 | Val acc: 51.52% | LR: 0.002499
Epoch: 037 | Train loss: 0.9815 | Train acc: 51.34% | Val loss: 0.9720 | Val acc: 51.28% | LR: 0.002477
Epoch: 038 | Train loss: 0.9856 | Train acc: 51.24% | Val loss: 0.9749 | Val acc: 51.42% | LR: 0.002455
Epoch: 039 | Train loss: 0.9865 | Train acc: 51.33% | Val loss: 0.9822 | Val acc: 51.07% | LR: 0.002433
Epoch: 040 | Train loss: 1.3244 | Train acc: 50.44% | Val loss: 1.0144 | Val acc: 49.46% | LR: 0.002410
Epoch: 041 | Train loss: 0.9893 | Train acc: 50.94% | Val loss: 1.0112 | Val acc: 50.13% | LR: 0.002387
Epoch: 042 | Train loss: 0.9835 | Train acc: 51.48% | Val loss: 1.0100 | Val acc: 52.25% | LR: 0.002363
Epoch: 043 | Train loss: 0.9970 | Train acc: 50.66% | Val loss: 0.9776 | Val acc: 51.62% | LR: 0.002339
Epoch: 044 | Train loss: 0.9816 | Train acc: 51.23% | Val loss: 0.9718 | Val acc: 51.59% | LR: 0.002314
Epoch: 045 | Train loss: 0.9860 | Train acc: 50.97% | Val loss: 0.9909 | Val acc: 51.75% | LR: 0.002289
Epoch: 046 | Train loss: 0.9915 | Train acc: 50.99% | Val loss: 1.0146 | Val acc: 49.56% | LR: 0.002264
Epoch: 047 | Train loss: 0.9954 | Train acc: 50.74% | Val loss: 1.0535 | Val acc: 45.95% | LR: 0.002239
Epoch: 048 | Train loss: 1.0008 | Train acc: 49.94% | Val loss: 1.0162 | Val acc: 49.51% | LR: 0.002213
Epoch: 049 | Train loss: 0.9918 | Train acc: 50.62% | Val loss: 1.0001 | Val acc: 49.51% | LR: 0.002186
Epoch: 050 | Train loss: 1.0011 | Train acc: 50.54% | Val loss: 1.1442 | Val acc: 53.07% | LR: 0.002160
Epoch: 051 | Train loss: 0.9973 | Train acc: 50.82% | Val loss: 1.0588 | Val acc: 46.05% | LR: 0.002133
Epoch: 052 | Train loss: 0.9891 | Train acc: 51.19% | Val loss: 1.0257 | Val acc: 49.77% | LR: 0.002106
Epoch: 053 | Train loss: 0.9929 | Train acc: 50.75% | Val loss: 0.9777 | Val acc: 51.84% | LR: 0.002078
Epoch: 054 | Train loss: 0.9932 | Train acc: 50.82% | Val loss: 0.9923 | Val acc: 50.80% | LR: 0.002051
Epoch: 055 | Train loss: 0.9798 | Train acc: 51.61% | Val loss: 0.9981 | Val acc: 50.59% | LR: 0.002023
Epoch: 056 | Train loss: 0.9930 | Train acc: 50.71% | Val loss: 1.0130 | Val acc: 49.15% | LR: 0.001994
Epoch: 057 | Train loss: 0.9901 | Train acc: 50.65% | Val loss: 0.9791 | Val acc: 49.66% | LR: 0.001966
Epoch: 058 | Train loss: 0.9921 | Train acc: 50.80% | Val loss: 1.0093 | Val acc: 49.58% | LR: 0.001937
Epoch: 059 | Train loss: 0.9897 | Train acc: 50.67% | Val loss: 1.0163 | Val acc: 49.07% | LR: 0.001908
Epoch: 060 | Train loss: 0.9853 | Train acc: 51.31% | Val loss: 1.0089 | Val acc: 48.86% | LR: 0.001879
Epoch: 061 | Train loss: 0.9914 | Train acc: 50.65% | Val loss: 1.0113 | Val acc: 49.54% | LR: 0.001850
Epoch: 062 | Train loss: 0.9875 | Train acc: 51.12% | Val loss: 1.0057 | Val acc: 49.07% | LR: 0.001820
Epoch: 063 | Train loss: 0.9905 | Train acc: 50.75% | Val loss: 1.0013 | Val acc: 49.42% | LR: 0.001791
Epoch: 064 | Train loss: 0.9848 | Train acc: 51.14% | Val loss: 1.0046 | Val acc: 49.59% | LR: 0.001761
Epoch: 065 | Train loss: 0.9853 | Train acc: 51.11% | Val loss: 1.0008 | Val acc: 49.73% | LR: 0.001731
Epoch: 066 | Train loss: 0.9886 | Train acc: 51.09% | Val loss: 1.0145 | Val acc: 49.16% | LR: 0.001701
Epoch: 067 | Train loss: 0.9927 | Train acc: 50.75% | Val loss: 0.9950 | Val acc: 49.28% | LR: 0.001671
Epoch: 068 | Train loss: 0.9797 | Train acc: 51.39% | Val loss: 1.0261 | Val acc: 49.48% | LR: 0.001641
Epoch: 069 | Train loss: 0.9905 | Train acc: 50.79% | Val loss: 1.0062 | Val acc: 49.56% | LR: 0.001610
Epoch: 070 | Train loss: 0.9861 | Train acc: 50.88% | Val loss: 0.9931 | Val acc: 49.60% | LR: 0.001580
Epoch: 071 | Train loss: 0.9846 | Train acc: 51.64% | Val loss: 1.0202 | Val acc: 49.60% | LR: 0.001549
Epoch: 072 | Train loss: 0.9828 | Train acc: 51.25% | Val loss: 1.0024 | Val acc: 49.38% | LR: 0.001519
Epoch: 073 | Train loss: 0.9891 | Train acc: 50.70% | Val loss: 1.0139 | Val acc: 49.51% | LR: 0.001488
Epoch: 074 | Train loss: 0.9857 | Train acc: 50.88% | Val loss: 1.0064 | Val acc: 49.51% | LR: 0.001458
Epoch: 075 | Train loss: 0.9820 | Train acc: 51.25% | Val loss: 1.0105 | Val acc: 49.53% | LR: 0.001427
Epoch: 076 | Train loss: 0.9856 | Train acc: 50.89% | Val loss: 1.0050 | Val acc: 49.67% | LR: 0.001397
Epoch: 077 | Train loss: 0.9855 | Train acc: 50.88% | Val loss: 1.0118 | Val acc: 49.65% | LR: 0.001366
Epoch: 078 | Train loss: 0.9741 | Train acc: 51.85% | Val loss: 1.0025 | Val acc: 49.65% | LR: 0.001336
Epoch: 079 | Train loss: 0.9811 | Train acc: 51.22% | Val loss: 1.0027 | Val acc: 49.67% | LR: 0.001306
Epoch: 080 | Train loss: 0.9849 | Train acc: 51.41% | Val loss: 0.9938 | Val acc: 49.69% | LR: 0.001275
Epoch: 081 | Train loss: 0.9828 | Train acc: 51.14% | Val loss: 1.0037 | Val acc: 49.70% | LR: 0.001245
Epoch: 082 | Train loss: 0.9837 | Train acc: 50.84% | Val loss: 0.9930 | Val acc: 49.69% | LR: 0.001215
Epoch: 083 | Train loss: 0.9847 | Train acc: 51.14% | Val loss: 1.0059 | Val acc: 49.87% | LR: 0.001185
Epoch: 084 | Train loss: 0.9846 | Train acc: 50.98% | Val loss: 1.0030 | Val acc: 49.98% | LR: 0.001155
Epoch: 085 | Train loss: 0.9847 | Train acc: 50.98% | Val loss: 0.9966 | Val acc: 49.98% | LR: 0.001125
Epoch: 086 | Train loss: 0.9910 | Train acc: 50.74% | Val loss: 1.0028 | Val acc: 49.96% | LR: 0.001096
Epoch: 087 | Train loss: 0.9895 | Train acc: 50.81% | Val loss: 0.9948 | Val acc: 50.19% | LR: 0.001066
Epoch: 088 | Train loss: 0.9816 | Train acc: 51.26% | Val loss: 1.0161 | Val acc: 50.13% | LR: 0.001037
Epoch: 089 | Train loss: 0.9868 | Train acc: 50.81% | Val loss: 0.9908 | Val acc: 49.85% | LR: 0.001008
Epoch: 090 | Train loss: 0.9874 | Train acc: 50.80% | Val loss: 1.0018 | Val acc: 49.79% | LR: 0.000979
Epoch: 091 | Train loss: 0.9834 | Train acc: 51.17% | Val loss: 1.0079 | Val acc: 49.74% | LR: 0.000950
Epoch: 092 | Train loss: 0.9827 | Train acc: 51.18% | Val loss: 0.9981 | Val acc: 49.78% | LR: 0.000922
Epoch: 093 | Train loss: 0.9940 | Train acc: 50.39% | Val loss: 1.0028 | Val acc: 49.78% | LR: 0.000893
Epoch: 094 | Train loss: 0.9818 | Train acc: 51.18% | Val loss: 1.0030 | Val acc: 49.73% | LR: 0.000865
Epoch: 095 | Train loss: 0.9891 | Train acc: 50.59% | Val loss: 1.0102 | Val acc: 49.30% | LR: 0.000838
Epoch: 096 | Train loss: 0.9873 | Train acc: 50.78% | Val loss: 1.0117 | Val acc: 49.15% | LR: 0.000810
Epoch: 097 | Train loss: 0.9771 | Train acc: 51.43% | Val loss: 1.0078 | Val acc: 49.54% | LR: 0.000783
Epoch: 098 | Train loss: 0.9855 | Train acc: 50.83% | Val loss: 1.0073 | Val acc: 49.51% | LR: 0.000756
Epoch: 099 | Train loss: 0.9830 | Train acc: 51.19% | Val loss: 1.0117 | Val acc: 49.51% | LR: 0.000729
Epoch: 100 | Train loss: 0.9813 | Train acc: 51.10% | Val loss: 1.0061 | Val acc: 49.55% | LR: 0.000703
Epoch: 101 | Train loss: 0.9738 | Train acc: 51.63% | Val loss: 1.0124 | Val acc: 49.48% | LR: 0.000677
Epoch: 102 | Train loss: 0.9731 | Train acc: 51.64% | Val loss: 1.0075 | Val acc: 49.50% | LR: 0.000652
Epoch: 103 | Train loss: 0.9881 | Train acc: 50.75% | Val loss: 1.0087 | Val acc: 49.50% | LR: 0.000626
Epoch: 104 | Train loss: 0.9814 | Train acc: 51.10% | Val loss: 1.0079 | Val acc: 49.48% | LR: 0.000602
Epoch: 105 | Train loss: 0.9897 | Train acc: 50.57% | Val loss: 1.0074 | Val acc: 49.50% | LR: 0.000577
Epoch: 106 | Train loss: 0.9807 | Train acc: 51.28% | Val loss: 1.0108 | Val acc: 49.48% | LR: 0.000553
Epoch: 107 | Train loss: 0.9790 | Train acc: 51.19% | Val loss: 1.0089 | Val acc: 49.48% | LR: 0.000529
Epoch: 108 | Train loss: 0.9851 | Train acc: 50.75% | Val loss: 1.0084 | Val acc: 49.48% | LR: 0.000506
Epoch: 109 | Train loss: 0.9814 | Train acc: 51.02% | Val loss: 1.0109 | Val acc: 49.48% | LR: 0.000483
Epoch: 110 | Train loss: 0.9774 | Train acc: 51.28% | Val loss: 1.0100 | Val acc: 49.48% | LR: 0.000461
Epoch: 111 | Train loss: 0.9776 | Train acc: 51.28% | Val loss: 1.0077 | Val acc: 49.50% | LR: 0.000439
Epoch: 112 | Train loss: 0.9775 | Train acc: 51.36% | Val loss: 1.0087 | Val acc: 49.42% | LR: 0.000417
Epoch: 113 | Train loss: 0.9767 | Train acc: 51.36% | Val loss: 1.0119 | Val acc: 49.44% | LR: 0.000396
Epoch: 114 | Train loss: 0.9844 | Train acc: 50.92% | Val loss: 1.0098 | Val acc: 49.44% | LR: 0.000375
Epoch: 115 | Train loss: 0.9762 | Train acc: 51.36% | Val loss: 1.0114 | Val acc: 49.44% | LR: 0.000355
Epoch: 116 | Train loss: 0.9814 | Train acc: 51.01% | Val loss: 1.0096 | Val acc: 49.42% | LR: 0.000335
Epoch: 117 | Train loss: 0.9830 | Train acc: 50.92% | Val loss: 1.0114 | Val acc: 49.42% | LR: 0.000316
Epoch: 118 | Train loss: 0.9832 | Train acc: 50.92% | Val loss: 1.0098 | Val acc: 49.46% | LR: 0.000297
Epoch: 119 | Train loss: 0.9952 | Train acc: 50.31% | Val loss: 1.0106 | Val acc: 49.46% | LR: 0.000279
Epoch: 120 | Train loss: 0.9838 | Train acc: 50.93% | Val loss: 1.0112 | Val acc: 49.44% | LR: 0.000262
Epoch: 121 | Train loss: 0.9825 | Train acc: 50.92% | Val loss: 1.0115 | Val acc: 49.42% | LR: 0.000244
Epoch: 122 | Train loss: 0.9852 | Train acc: 50.82% | Val loss: 1.0135 | Val acc: 49.25% | LR: 0.000228
Epoch: 123 | Train loss: 0.9882 | Train acc: 50.62% | Val loss: 1.0172 | Val acc: 49.05% | LR: 0.000212
Epoch: 124 | Train loss: 0.9820 | Train acc: 51.14% | Val loss: 1.0197 | Val acc: 48.97% | LR: 0.000196
Epoch: 125 | Train loss: 0.9882 | Train acc: 50.77% | Val loss: 1.0189 | Val acc: 48.93% | LR: 0.000181
Epoch: 126 | Train loss: 0.9787 | Train acc: 51.23% | Val loss: 1.0176 | Val acc: 49.07% | LR: 0.000167
Epoch: 127 | Train loss: 0.9819 | Train acc: 51.06% | Val loss: 1.0150 | Val acc: 49.25% | LR: 0.000153
Epoch: 128 | Train loss: 0.9782 | Train acc: 51.24% | Val loss: 1.0139 | Val acc: 49.29% | LR: 0.000140
Epoch: 129 | Train loss: 0.9931 | Train acc: 50.36% | Val loss: 1.0128 | Val acc: 49.35% | LR: 0.000127
Epoch: 130 | Train loss: 0.9862 | Train acc: 50.71% | Val loss: 1.0102 | Val acc: 49.46% | LR: 0.000115
Epoch: 131 | Train loss: 0.9866 | Train acc: 50.73% | Val loss: 1.0108 | Val acc: 49.41% | LR: 0.000103
Epoch: 132 | Train loss: 0.9758 | Train acc: 51.35% | Val loss: 1.0113 | Val acc: 49.43% | LR: 0.000092
Epoch: 133 | Train loss: 0.9800 | Train acc: 51.09% | Val loss: 1.0114 | Val acc: 49.39% | LR: 0.000082
Epoch: 134 | Train loss: 0.9773 | Train acc: 51.27% | Val loss: 1.0096 | Val acc: 49.48% | LR: 0.000072
Epoch: 135 | Train loss: 0.9790 | Train acc: 51.25% | Val loss: 1.0118 | Val acc: 49.41% | LR: 0.000063
Epoch: 136 | Train loss: 0.9826 | Train acc: 50.98% | Val loss: 1.0128 | Val acc: 49.33% | LR: 0.000055
Epoch: 137 | Train loss: 0.9783 | Train acc: 51.25% | Val loss: 1.0129 | Val acc: 49.33% | LR: 0.000047
Epoch: 138 | Train loss: 0.9713 | Train acc: 51.60% | Val loss: 1.0130 | Val acc: 49.33% | LR: 0.000039
Epoch: 139 | Train loss: 0.9868 | Train acc: 50.72% | Val loss: 1.0130 | Val acc: 49.33% | LR: 0.000033
Epoch: 140 | Train loss: 0.9767 | Train acc: 51.35% | Val loss: 1.0128 | Val acc: 49.33% | LR: 0.000027
Epoch: 141 | Train loss: 0.9806 | Train acc: 51.08% | Val loss: 1.0127 | Val acc: 49.33% | LR: 0.000021
Epoch: 142 | Train loss: 0.9884 | Train acc: 50.64% | Val loss: 1.0126 | Val acc: 49.33% | LR: 0.000017
Epoch: 143 | Train loss: 0.9871 | Train acc: 50.73% | Val loss: 1.0127 | Val acc: 49.33% | LR: 0.000012
Epoch: 144 | Train loss: 0.9874 | Train acc: 50.73% | Val loss: 1.0127 | Val acc: 49.33% | LR: 0.000009
Epoch: 145 | Train loss: 0.9748 | Train acc: 51.35% | Val loss: 1.0127 | Val acc: 49.33% | LR: 0.000006
Epoch: 146 | Train loss: 0.9806 | Train acc: 51.08% | Val loss: 1.0127 | Val acc: 49.33% | LR: 0.000004
Epoch: 147 | Train loss: 0.9807 | Train acc: 51.08% | Val loss: 1.0128 | Val acc: 49.33% | LR: 0.000002
Epoch: 148 | Train loss: 0.9763 | Train acc: 51.35% | Val loss: 1.0128 | Val acc: 49.33% | LR: 0.000001
Epoch: 149 | Train loss: 0.9868 | Train acc: 50.64% | Val loss: 1.0128 | Val acc: 49.33% | LR: 0.000001

[I 2025-09-23 02:28:48,640] Trial 20 finished with value: 0.5404949307441711 and parameters: {'lr': 0.00291491158385195, 'hidden_size': 150, 'dropout': 0.19171114904330547, 'weight_decay': 0.25279928938562835}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.0057 | Train acc: 50.01% | Val loss: 1.0038 | Val acc: 47.59% | LR: 0.001811
Epoch: 001 | Train loss: 0.9942 | Train acc: 50.74% | Val loss: 0.9992 | Val acc: 49.61% | LR: 0.001811
Epoch: 002 | Train loss: 1.0084 | Train acc: 50.25% | Val loss: 1.0091 | Val acc: 50.64% | LR: 0.001810
Epoch: 003 | Train loss: 0.9993 | Train acc: 50.52% | Val loss: 0.9875 | Val acc: 51.78% | LR: 0.001808
Epoch: 004 | Train loss: 1.0013 | Train acc: 49.97% | Val loss: 1.0113 | Val acc: 48.49% | LR: 0.001806
Epoch: 005 | Train loss: 0.9985 | Train acc: 50.49% | Val loss: 0.9873 | Val acc: 52.66% | LR: 0.001804
Epoch: 006 | Train loss: 0.9997 | Train acc: 50.51% | Val loss: 1.0140 | Val acc: 46.54% | LR: 0.001802
Epoch: 007 | Train loss: 1.0005 | Train acc: 50.00% | Val loss: 1.0015 | Val acc: 50.29% | LR: 0.001799
Epoch: 008 | Train loss: 0.9982 | Train acc: 50.90% | Val loss: 1.0205 | Val acc: 46.36% | LR: 0.001795
Epoch: 009 | Train loss: 0.9963 | Train acc: 50.93% | Val loss: 0.9950 | Val acc: 51.01% | LR: 0.001792
Epoch: 010 | Train loss: 0.9993 | Train acc: 50.36% | Val loss: 1.0041 | Val acc: 49.68% | LR: 0.001787
Epoch: 011 | Train loss: 0.9976 | Train acc: 50.51% | Val loss: 1.0056 | Val acc: 49.41% | LR: 0.001783
Epoch: 012 | Train loss: 0.9987 | Train acc: 50.88% | Val loss: 1.0056 | Val acc: 48.15% | LR: 0.001778
Epoch: 013 | Train loss: 1.0005 | Train acc: 50.43% | Val loss: 1.0100 | Val acc: 48.74% | LR: 0.001773
Epoch: 014 | Train loss: 0.9929 | Train acc: 51.14% | Val loss: 1.0385 | Val acc: 47.80% | LR: 0.001767
Epoch: 015 | Train loss: 0.9985 | Train acc: 50.18% | Val loss: 1.0024 | Val acc: 50.43% | LR: 0.001761
Epoch: 016 | Train loss: 0.9913 | Train acc: 50.66% | Val loss: 1.0069 | Val acc: 49.47% | LR: 0.001755
Epoch: 017 | Train loss: 0.9952 | Train acc: 50.99% | Val loss: 1.0160 | Val acc: 49.46% | LR: 0.001748
Epoch: 018 | Train loss: 0.9965 | Train acc: 50.57% | Val loss: 1.0016 | Val acc: 50.88% | LR: 0.001741
Epoch: 019 | Train loss: 0.9939 | Train acc: 50.77% | Val loss: 0.9937 | Val acc: 51.27% | LR: 0.001733
Epoch: 020 | Train loss: 0.9983 | Train acc: 50.14% | Val loss: 0.9715 | Val acc: 51.23% | LR: 0.001725
Epoch: 021 | Train loss: 1.0133 | Train acc: 50.30% | Val loss: 1.0215 | Val acc: 49.96% | LR: 0.001717
Epoch: 022 | Train loss: 1.0010 | Train acc: 50.78% | Val loss: 0.9801 | Val acc: 52.12% | LR: 0.001708
Epoch: 023 | Train loss: 0.9962 | Train acc: 51.01% | Val loss: 1.0061 | Val acc: 48.72% | LR: 0.001699
Epoch: 024 | Train loss: 0.9990 | Train acc: 50.13% | Val loss: 1.0241 | Val acc: 47.98% | LR: 0.001690
Epoch: 025 | Train loss: 0.9970 | Train acc: 50.12% | Val loss: 1.0230 | Val acc: 47.85% | LR: 0.001680
Epoch: 026 | Train loss: 0.9998 | Train acc: 50.35% | Val loss: 1.0184 | Val acc: 47.91% | LR: 0.001670
Epoch: 027 | Train loss: 0.9885 | Train acc: 51.19% | Val loss: 1.0030 | Val acc: 48.19% | LR: 0.001660
Epoch: 028 | Train loss: 0.9909 | Train acc: 50.60% | Val loss: 0.9681 | Val acc: 51.26% | LR: 0.001649
Epoch: 029 | Train loss: 0.9940 | Train acc: 50.30% | Val loss: 1.0055 | Val acc: 48.78% | LR: 0.001638
Epoch: 030 | Train loss: 0.9911 | Train acc: 50.67% | Val loss: 1.0071 | Val acc: 48.22% | LR: 0.001627
Epoch: 031 | Train loss: 0.9918 | Train acc: 50.92% | Val loss: 1.0093 | Val acc: 47.58% | LR: 0.001616
Epoch: 032 | Train loss: 0.9891 | Train acc: 50.87% | Val loss: 1.0323 | Val acc: 46.17% | LR: 0.001604
Epoch: 033 | Train loss: 0.9916 | Train acc: 50.60% | Val loss: 0.9982 | Val acc: 49.22% | LR: 0.001591
Epoch: 034 | Train loss: 0.9924 | Train acc: 50.76% | Val loss: 1.0114 | Val acc: 47.88% | LR: 0.001579
Epoch: 035 | Train loss: 0.9916 | Train acc: 50.61% | Val loss: 1.0158 | Val acc: 47.74% | LR: 0.001566
Epoch: 036 | Train loss: 0.9900 | Train acc: 50.62% | Val loss: 0.9991 | Val acc: 49.14% | LR: 0.001553
Epoch: 037 | Train loss: 0.9850 | Train acc: 51.51% | Val loss: 1.0260 | Val acc: 47.45% | LR: 0.001540
Epoch: 038 | Train loss: 0.9924 | Train acc: 50.54% | Val loss: 1.0015 | Val acc: 49.78% | LR: 0.001526
Epoch: 039 | Train loss: 0.9896 | Train acc: 50.97% | Val loss: 1.0198 | Val acc: 48.09% | LR: 0.001512
Epoch: 040 | Train loss: 0.9889 | Train acc: 50.94% | Val loss: 1.0170 | Val acc: 48.12% | LR: 0.001498
Epoch: 041 | Train loss: 0.9898 | Train acc: 50.98% | Val loss: 1.0143 | Val acc: 48.98% | LR: 0.001483
Epoch: 042 | Train loss: 0.9884 | Train acc: 50.78% | Val loss: 0.9976 | Val acc: 49.99% | LR: 0.001468
Epoch: 043 | Train loss: 0.9891 | Train acc: 51.03% | Val loss: 0.9552 | Val acc: 52.91% | LR: 0.001453
Epoch: 044 | Train loss: 0.9887 | Train acc: 50.97% | Val loss: 1.0325 | Val acc: 47.51% | LR: 0.001438
Epoch: 045 | Train loss: 0.9870 | Train acc: 50.95% | Val loss: 1.0175 | Val acc: 48.40% | LR: 0.001423
Epoch: 046 | Train loss: 0.9924 | Train acc: 50.85% | Val loss: 0.9580 | Val acc: 51.71% | LR: 0.001407
Epoch: 047 | Train loss: 0.9915 | Train acc: 50.85% | Val loss: 0.9848 | Val acc: 52.21% | LR: 0.001391
Epoch: 048 | Train loss: 0.9869 | Train acc: 50.91% | Val loss: 0.9720 | Val acc: 51.98% | LR: 0.001375
Epoch: 049 | Train loss: 0.9883 | Train acc: 51.11% | Val loss: 1.0046 | Val acc: 48.58% | LR: 0.001359
Epoch: 050 | Train loss: 0.9870 | Train acc: 51.12% | Val loss: 0.9610 | Val acc: 52.09% | LR: 0.001342
Epoch: 051 | Train loss: 0.9987 | Train acc: 50.29% | Val loss: 0.9900 | Val acc: 50.24% | LR: 0.001326
Epoch: 052 | Train loss: 0.9872 | Train acc: 51.22% | Val loss: 0.9892 | Val acc: 49.98% | LR: 0.001309
Epoch: 053 | Train loss: 0.9861 | Train acc: 51.39% | Val loss: 1.0036 | Val acc: 48.58% | LR: 0.001292
Epoch: 054 | Train loss: 0.9883 | Train acc: 51.15% | Val loss: 1.0117 | Val acc: 48.11% | LR: 0.001274
Epoch: 055 | Train loss: 0.9815 | Train acc: 51.31% | Val loss: 1.0013 | Val acc: 49.18% | LR: 0.001257
Epoch: 056 | Train loss: 0.9906 | Train acc: 50.47% | Val loss: 0.9777 | Val acc: 50.51% | LR: 0.001239
Epoch: 057 | Train loss: 0.9887 | Train acc: 50.52% | Val loss: 0.9613 | Val acc: 52.28% | LR: 0.001222
Epoch: 058 | Train loss: 0.9874 | Train acc: 51.04% | Val loss: 0.9850 | Val acc: 50.66% | LR: 0.001204
Epoch: 059 | Train loss: 0.9887 | Train acc: 51.35% | Val loss: 1.0435 | Val acc: 46.48% | LR: 0.001186
Epoch: 060 | Train loss: 1.0010 | Train acc: 50.33% | Val loss: 1.0463 | Val acc: 46.05% | LR: 0.001168
Epoch: 061 | Train loss: 0.9940 | Train acc: 50.65% | Val loss: 1.0416 | Val acc: 45.95% | LR: 0.001150
Epoch: 062 | Train loss: 0.9931 | Train acc: 51.03% | Val loss: 1.0208 | Val acc: 45.95% | LR: 0.001131
Epoch: 063 | Train loss: 0.9955 | Train acc: 50.41% | Val loss: 1.0474 | Val acc: 45.97% | LR: 0.001113
Epoch: 064 | Train loss: 0.9930 | Train acc: 50.45% | Val loss: 1.0442 | Val acc: 45.97% | LR: 0.001094
Epoch: 065 | Train loss: 0.9911 | Train acc: 50.44% | Val loss: 1.0071 | Val acc: 45.97% | LR: 0.001076
Epoch: 066 | Train loss: 0.9951 | Train acc: 50.40% | Val loss: 1.0077 | Val acc: 45.97% | LR: 0.001057
Epoch: 067 | Train loss: 0.9921 | Train acc: 50.66% | Val loss: 0.9995 | Val acc: 53.00% | LR: 0.001038
Epoch: 068 | Train loss: 0.9944 | Train acc: 50.65% | Val loss: 0.9931 | Val acc: 53.65% | LR: 0.001020
Epoch: 069 | Train loss: 1.0035 | Train acc: 49.69% | Val loss: 0.9865 | Val acc: 53.92% | LR: 0.001001
Epoch: 070 | Train loss: 0.9952 | Train acc: 50.59% | Val loss: 0.9651 | Val acc: 54.18% | LR: 0.000982
Epoch: 071 | Train loss: 0.9884 | Train acc: 51.17% | Val loss: 0.9659 | Val acc: 53.84% | LR: 0.000963
Epoch: 072 | Train loss: 0.9958 | Train acc: 50.83% | Val loss: 0.9579 | Val acc: 54.24% | LR: 0.000944
Epoch: 073 | Train loss: 0.9951 | Train acc: 50.59% | Val loss: 0.9602 | Val acc: 53.29% | LR: 0.000925
Epoch: 074 | Train loss: 0.9886 | Train acc: 50.87% | Val loss: 0.9462 | Val acc: 53.62% | LR: 0.000906
Epoch: 075 | Train loss: 0.9848 | Train acc: 51.31% | Val loss: 1.0014 | Val acc: 49.75% | LR: 0.000887
Epoch: 076 | Train loss: 0.9874 | Train acc: 50.81% | Val loss: 0.9726 | Val acc: 52.17% | LR: 0.000868
Epoch: 077 | Train loss: 0.9875 | Train acc: 51.24% | Val loss: 0.9524 | Val acc: 53.21% | LR: 0.000849
Epoch: 078 | Train loss: 0.9832 | Train acc: 51.36% | Val loss: 0.9523 | Val acc: 53.20% | LR: 0.000830
Epoch: 079 | Train loss: 0.9770 | Train acc: 51.75% | Val loss: 0.9643 | Val acc: 52.25% | LR: 0.000812
Epoch: 080 | Train loss: 0.9809 | Train acc: 51.49% | Val loss: 0.9808 | Val acc: 51.57% | LR: 0.000793
Epoch: 081 | Train loss: 0.9822 | Train acc: 51.15% | Val loss: 0.9909 | Val acc: 50.63% | LR: 0.000774
Epoch: 082 | Train loss: 0.9837 | Train acc: 51.33% | Val loss: 0.9578 | Val acc: 52.43% | LR: 0.000755
Epoch: 083 | Train loss: 0.9816 | Train acc: 51.50% | Val loss: 1.0264 | Val acc: 48.19% | LR: 0.000737
Epoch: 084 | Train loss: 0.9884 | Train acc: 50.83% | Val loss: 1.0225 | Val acc: 47.76% | LR: 0.000718
Epoch: 085 | Train loss: 0.9833 | Train acc: 51.11% | Val loss: 1.0229 | Val acc: 48.14% | LR: 0.000699
Epoch: 086 | Train loss: 0.9931 | Train acc: 50.59% | Val loss: 1.0159 | Val acc: 48.02% | LR: 0.000681
Epoch: 087 | Train loss: 0.9865 | Train acc: 51.02% | Val loss: 1.0049 | Val acc: 48.71% | LR: 0.000663
Epoch: 088 | Train loss: 0.9916 | Train acc: 50.69% | Val loss: 1.0117 | Val acc: 48.37% | LR: 0.000645
Epoch: 089 | Train loss: 0.9873 | Train acc: 50.83% | Val loss: 1.0198 | Val acc: 47.76% | LR: 0.000626
Epoch: 090 | Train loss: 0.9841 | Train acc: 51.16% | Val loss: 0.9590 | Val acc: 51.94% | LR: 0.000609
Epoch: 091 | Train loss: 0.9838 | Train acc: 51.13% | Val loss: 0.9808 | Val acc: 51.21% | LR: 0.000591
Epoch: 092 | Train loss: 0.9779 | Train acc: 51.55% | Val loss: 0.9533 | Val acc: 52.92% | LR: 0.000573
Epoch: 093 | Train loss: 0.9811 | Train acc: 51.36% | Val loss: 0.9522 | Val acc: 52.89% | LR: 0.000555
Epoch: 094 | Train loss: 0.9863 | Train acc: 50.97% | Val loss: 0.9574 | Val acc: 52.68% | LR: 0.000538
Epoch: 095 | Train loss: 0.9810 | Train acc: 51.33% | Val loss: 0.9694 | Val acc: 52.03% | LR: 0.000521
Epoch: 096 | Train loss: 0.9856 | Train acc: 50.96% | Val loss: 0.9534 | Val acc: 52.95% | LR: 0.000504
Epoch: 097 | Train loss: 0.9845 | Train acc: 51.21% | Val loss: 0.9642 | Val acc: 52.34% | LR: 0.000487
Epoch: 098 | Train loss: 0.9769 | Train acc: 51.48% | Val loss: 0.9596 | Val acc: 52.45% | LR: 0.000470
Epoch: 099 | Train loss: 0.9809 | Train acc: 51.32% | Val loss: 0.9717 | Val acc: 51.69% | LR: 0.000454
Epoch: 100 | Train loss: 0.9864 | Train acc: 50.94% | Val loss: 0.9774 | Val acc: 51.58% | LR: 0.000437
Epoch: 101 | Train loss: 0.9829 | Train acc: 51.15% | Val loss: 0.9560 | Val acc: 52.74% | LR: 0.000421
Epoch: 102 | Train loss: 0.9853 | Train acc: 51.01% | Val loss: 0.9733 | Val acc: 51.71% | LR: 0.000405
Epoch: 103 | Train loss: 0.9853 | Train acc: 51.00% | Val loss: 0.9686 | Val acc: 51.90% | LR: 0.000390
Epoch: 104 | Train loss: 0.9806 | Train acc: 51.40% | Val loss: 0.9684 | Val acc: 51.62% | LR: 0.000374
Epoch: 105 | Train loss: 0.9799 | Train acc: 51.33% | Val loss: 0.9652 | Val acc: 51.81% | LR: 0.000359
Epoch: 106 | Train loss: 0.9847 | Train acc: 50.91% | Val loss: 0.9810 | Val acc: 51.16% | LR: 0.000344
Epoch: 107 | Train loss: 0.9885 | Train acc: 50.78% | Val loss: 0.9434 | Val acc: 53.11% | LR: 0.000329
Epoch: 108 | Train loss: 0.9850 | Train acc: 51.15% | Val loss: 0.9670 | Val acc: 51.97% | LR: 0.000315
Epoch: 109 | Train loss: 0.9641 | Train acc: 52.49% | Val loss: 0.9635 | Val acc: 51.94% | LR: 0.000300
Epoch: 110 | Train loss: 0.9759 | Train acc: 51.63% | Val loss: 0.9590 | Val acc: 52.34% | LR: 0.000287
Epoch: 111 | Train loss: 0.9811 | Train acc: 51.15% | Val loss: 0.9558 | Val acc: 52.48% | LR: 0.000273
Epoch: 112 | Train loss: 0.9861 | Train acc: 50.99% | Val loss: 0.9755 | Val acc: 51.29% | LR: 0.000259
Epoch: 113 | Train loss: 0.9776 | Train acc: 51.53% | Val loss: 0.9478 | Val acc: 52.87% | LR: 0.000246
Epoch: 114 | Train loss: 0.9774 | Train acc: 51.46% | Val loss: 0.9655 | Val acc: 51.99% | LR: 0.000234
Epoch: 115 | Train loss: 0.9760 | Train acc: 51.68% | Val loss: 0.9592 | Val acc: 52.15% | LR: 0.000221
Epoch: 116 | Train loss: 0.9701 | Train acc: 51.89% | Val loss: 0.9609 | Val acc: 52.17% | LR: 0.000209
Epoch: 117 | Train loss: 0.9824 | Train acc: 51.08% | Val loss: 0.9587 | Val acc: 52.45% | LR: 0.000197
Epoch: 118 | Train loss: 0.9770 | Train acc: 51.63% | Val loss: 0.9650 | Val acc: 51.95% | LR: 0.000185
Epoch: 119 | Train loss: 0.9749 | Train acc: 51.54% | Val loss: 0.9599 | Val acc: 52.23% | LR: 0.000174
Epoch: 120 | Train loss: 0.9810 | Train acc: 51.36% | Val loss: 0.9592 | Val acc: 52.18% | LR: 0.000163
Epoch: 121 | Train loss: 0.9766 | Train acc: 51.48% | Val loss: 0.9649 | Val acc: 51.97% | LR: 0.000152
Epoch: 122 | Train loss: 0.9834 | Train acc: 51.22% | Val loss: 0.9660 | Val acc: 51.89% | LR: 0.000142
Epoch: 123 | Train loss: 0.9752 | Train acc: 51.53% | Val loss: 0.9644 | Val acc: 51.81% | LR: 0.000132
Epoch: 124 | Train loss: 0.9749 | Train acc: 51.54% | Val loss: 0.9590 | Val acc: 52.26% | LR: 0.000122
Epoch: 125 | Train loss: 0.9784 | Train acc: 51.47% | Val loss: 0.9613 | Val acc: 52.06% | LR: 0.000113
Epoch: 126 | Train loss: 0.9817 | Train acc: 51.14% | Val loss: 0.9560 | Val acc: 52.24% | LR: 0.000104
Epoch: 127 | Train loss: 0.9772 | Train acc: 51.46% | Val loss: 0.9615 | Val acc: 52.07% | LR: 0.000095
Epoch: 128 | Train loss: 0.9763 | Train acc: 51.56% | Val loss: 0.9606 | Val acc: 52.05% | LR: 0.000087
Epoch: 129 | Train loss: 0.9805 | Train acc: 51.23% | Val loss: 0.9576 | Val acc: 52.20% | LR: 0.000079
Epoch: 130 | Train loss: 0.9807 | Train acc: 51.23% | Val loss: 0.9603 | Val acc: 52.16% | LR: 0.000072
Epoch: 131 | Train loss: 0.9649 | Train acc: 52.13% | Val loss: 0.9594 | Val acc: 52.18% | LR: 0.000065
Epoch: 132 | Train loss: 0.9670 | Train acc: 52.12% | Val loss: 0.9581 | Val acc: 52.24% | LR: 0.000058
Epoch: 133 | Train loss: 0.9748 | Train acc: 51.57% | Val loss: 0.9604 | Val acc: 52.15% | LR: 0.000051
Epoch: 134 | Train loss: 0.9788 | Train acc: 51.43% | Val loss: 0.9582 | Val acc: 52.24% | LR: 0.000045
Epoch: 135 | Train loss: 0.9827 | Train acc: 51.06% | Val loss: 0.9592 | Val acc: 52.10% | LR: 0.000040
Epoch: 136 | Train loss: 0.9687 | Train acc: 51.95% | Val loss: 0.9589 | Val acc: 52.22% | LR: 0.000034
Epoch: 137 | Train loss: 0.9812 | Train acc: 51.13% | Val loss: 0.9598 | Val acc: 52.18% | LR: 0.000029
Epoch: 138 | Train loss: 0.9821 | Train acc: 51.05% | Val loss: 0.9597 | Val acc: 52.06% | LR: 0.000025
Epoch: 139 | Train loss: 0.9777 | Train acc: 51.32% | Val loss: 0.9596 | Val acc: 52.06% | LR: 0.000021
Epoch: 140 | Train loss: 0.9771 | Train acc: 51.43% | Val loss: 0.9595 | Val acc: 52.04% | LR: 0.000017
Epoch: 141 | Train loss: 0.9753 | Train acc: 51.51% | Val loss: 0.9588 | Val acc: 52.14% | LR: 0.000014
Epoch: 142 | Train loss: 0.9767 | Train acc: 51.42% | Val loss: 0.9593 | Val acc: 52.08% | LR: 0.000011
Epoch: 143 | Train loss: 0.9737 | Train acc: 51.59% | Val loss: 0.9585 | Val acc: 52.20% | LR: 0.000008
Epoch: 144 | Train loss: 0.9759 | Train acc: 51.52% | Val loss: 0.9587 | Val acc: 52.08% | LR: 0.000006
Epoch: 145 | Train loss: 0.9782 | Train acc: 51.35% | Val loss: 0.9588 | Val acc: 52.10% | LR: 0.000004
Epoch: 146 | Train loss: 0.9650 | Train acc: 52.15% | Val loss: 0.9590 | Val acc: 52.10% | LR: 0.000003
Epoch: 147 | Train loss: 0.9848 | Train acc: 51.00% | Val loss: 0.9589 | Val acc: 52.10% | LR: 0.000002
Epoch: 148 | Train loss: 0.9782 | Train acc: 51.34% | Val loss: 0.9588 | Val acc: 52.16% | LR: 0.000001
Epoch: 149 | Train loss: 0.9737 | Train acc: 51.79% | Val loss: 0.9588 | Val acc: 52.16% | LR: 0.000001

[I 2025-09-23 02:31:50,263] Trial 21 finished with value: 0.5423807859420776 and parameters: {'lr': 0.0018113748744362536, 'hidden_size': 130, 'dropout': 0.3085285182639085, 'weight_decay': 0.6132693551508526}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.0187 | Train acc: 49.70% | Val loss: 0.9992 | Val acc: 51.72% | LR: 0.000924
Epoch: 001 | Train loss: 1.0035 | Train acc: 51.06% | Val loss: 1.0033 | Val acc: 50.15% | LR: 0.000924
Epoch: 002 | Train loss: 0.9970 | Train acc: 51.33% | Val loss: 1.0214 | Val acc: 47.61% | LR: 0.000923
Epoch: 003 | Train loss: 0.9948 | Train acc: 50.86% | Val loss: 1.0197 | Val acc: 48.37% | LR: 0.000923
Epoch: 004 | Train loss: 0.9912 | Train acc: 50.95% | Val loss: 1.0213 | Val acc: 48.21% | LR: 0.000922
Epoch: 005 | Train loss: 0.9949 | Train acc: 50.50% | Val loss: 1.0183 | Val acc: 48.66% | LR: 0.000921
Epoch: 006 | Train loss: 0.9960 | Train acc: 50.67% | Val loss: 1.0220 | Val acc: 48.51% | LR: 0.000919
Epoch: 007 | Train loss: 0.9959 | Train acc: 50.34% | Val loss: 1.0154 | Val acc: 48.79% | LR: 0.000918
Epoch: 008 | Train loss: 0.9961 | Train acc: 50.67% | Val loss: 1.0080 | Val acc: 49.42% | LR: 0.000916
Epoch: 009 | Train loss: 0.9949 | Train acc: 50.84% | Val loss: 1.0004 | Val acc: 50.36% | LR: 0.000914
Epoch: 010 | Train loss: 1.0090 | Train acc: 50.74% | Val loss: 1.0093 | Val acc: 49.08% | LR: 0.000912
Epoch: 011 | Train loss: 0.9987 | Train acc: 50.34% | Val loss: 1.0194 | Val acc: 49.60% | LR: 0.000910
Epoch: 012 | Train loss: 0.9890 | Train acc: 51.29% | Val loss: 1.0203 | Val acc: 49.20% | LR: 0.000907
Epoch: 013 | Train loss: 1.0052 | Train acc: 50.64% | Val loss: 1.0333 | Val acc: 47.69% | LR: 0.000905
Epoch: 014 | Train loss: 0.9936 | Train acc: 50.41% | Val loss: 1.0182 | Val acc: 48.60% | LR: 0.000902
Epoch: 015 | Train loss: 0.9897 | Train acc: 50.85% | Val loss: 1.0122 | Val acc: 49.05% | LR: 0.000899
Epoch: 016 | Train loss: 0.9925 | Train acc: 50.90% | Val loss: 1.0182 | Val acc: 49.51% | LR: 0.000895
Epoch: 017 | Train loss: 0.9986 | Train acc: 50.40% | Val loss: 1.0681 | Val acc: 48.17% | LR: 0.000892
Epoch: 018 | Train loss: 0.9995 | Train acc: 50.05% | Val loss: 1.1305 | Val acc: 49.20% | LR: 0.000888
Epoch: 019 | Train loss: 0.9879 | Train acc: 51.27% | Val loss: 1.0101 | Val acc: 49.57% | LR: 0.000884
Epoch: 020 | Train loss: 0.9860 | Train acc: 51.53% | Val loss: 1.0263 | Val acc: 49.29% | LR: 0.000880
Epoch: 021 | Train loss: 0.9912 | Train acc: 50.75% | Val loss: 1.0331 | Val acc: 49.39% | LR: 0.000876
Epoch: 022 | Train loss: 0.9941 | Train acc: 50.75% | Val loss: 1.1157 | Val acc: 49.21% | LR: 0.000872
Epoch: 023 | Train loss: 0.9983 | Train acc: 51.01% | Val loss: 1.0015 | Val acc: 50.79% | LR: 0.000867
Epoch: 024 | Train loss: 0.9857 | Train acc: 51.43% | Val loss: 1.0001 | Val acc: 51.34% | LR: 0.000862
Epoch: 025 | Train loss: 0.9849 | Train acc: 51.15% | Val loss: 0.9868 | Val acc: 51.75% | LR: 0.000858
Epoch: 026 | Train loss: 0.9843 | Train acc: 50.94% | Val loss: 0.9902 | Val acc: 51.33% | LR: 0.000852
Epoch: 027 | Train loss: 0.9949 | Train acc: 50.55% | Val loss: 0.9734 | Val acc: 53.16% | LR: 0.000847
Epoch: 028 | Train loss: 0.9875 | Train acc: 51.17% | Val loss: 0.9772 | Val acc: 51.37% | LR: 0.000842
Epoch: 029 | Train loss: 0.9910 | Train acc: 50.54% | Val loss: 0.9759 | Val acc: 51.19% | LR: 0.000836
Epoch: 030 | Train loss: 0.9879 | Train acc: 51.19% | Val loss: 0.9810 | Val acc: 51.61% | LR: 0.000830
Epoch: 031 | Train loss: 0.9893 | Train acc: 51.07% | Val loss: 0.9846 | Val acc: 51.14% | LR: 0.000824
Epoch: 032 | Train loss: 0.9897 | Train acc: 50.83% | Val loss: 0.9649 | Val acc: 52.35% | LR: 0.000818
Epoch: 033 | Train loss: 0.9915 | Train acc: 50.61% | Val loss: 0.9672 | Val acc: 52.34% | LR: 0.000812
Epoch: 034 | Train loss: 0.9864 | Train acc: 50.98% | Val loss: 0.9487 | Val acc: 53.30% | LR: 0.000806
Epoch: 035 | Train loss: 0.9807 | Train acc: 51.25% | Val loss: 0.9502 | Val acc: 53.87% | LR: 0.000799
Epoch: 036 | Train loss: 0.9921 | Train acc: 50.64% | Val loss: 0.9467 | Val acc: 53.90% | LR: 0.000793
Epoch: 037 | Train loss: 0.9874 | Train acc: 50.85% | Val loss: 0.9507 | Val acc: 54.01% | LR: 0.000786
Epoch: 038 | Train loss: 0.9878 | Train acc: 51.05% | Val loss: 0.9410 | Val acc: 54.56% | LR: 0.000779
Epoch: 039 | Train loss: 0.9890 | Train acc: 50.74% | Val loss: 0.9647 | Val acc: 54.14% | LR: 0.000772
Epoch: 040 | Train loss: 0.9854 | Train acc: 51.03% | Val loss: 0.9557 | Val acc: 54.19% | LR: 0.000764
Epoch: 041 | Train loss: 0.9870 | Train acc: 51.11% | Val loss: 0.9666 | Val acc: 53.05% | LR: 0.000757
Epoch: 042 | Train loss: 0.9864 | Train acc: 51.01% | Val loss: 0.9789 | Val acc: 51.52% | LR: 0.000749
Epoch: 043 | Train loss: 0.9912 | Train acc: 50.60% | Val loss: 0.9776 | Val acc: 51.62% | LR: 0.000742
Epoch: 044 | Train loss: 0.9849 | Train acc: 51.25% | Val loss: 0.9863 | Val acc: 51.19% | LR: 0.000734
Epoch: 045 | Train loss: 0.9831 | Train acc: 51.07% | Val loss: 0.9823 | Val acc: 51.15% | LR: 0.000726
Epoch: 046 | Train loss: 0.9898 | Train acc: 50.72% | Val loss: 0.9851 | Val acc: 51.09% | LR: 0.000718
Epoch: 047 | Train loss: 0.9854 | Train acc: 50.87% | Val loss: 0.9829 | Val acc: 51.09% | LR: 0.000710
Epoch: 048 | Train loss: 0.9849 | Train acc: 51.02% | Val loss: 0.9807 | Val acc: 51.09% | LR: 0.000702
Epoch: 049 | Train loss: 0.9892 | Train acc: 50.80% | Val loss: 0.9901 | Val acc: 50.96% | LR: 0.000694
Epoch: 050 | Train loss: 0.9859 | Train acc: 50.98% | Val loss: 0.9873 | Val acc: 51.10% | LR: 0.000685
Epoch: 051 | Train loss: 0.9887 | Train acc: 50.78% | Val loss: 0.9824 | Val acc: 51.19% | LR: 0.000677
Epoch: 052 | Train loss: 0.9870 | Train acc: 50.87% | Val loss: 0.9830 | Val acc: 51.09% | LR: 0.000668
Epoch: 053 | Train loss: 0.9796 | Train acc: 51.39% | Val loss: 1.0159 | Val acc: 51.03% | LR: 0.000659
Epoch: 054 | Train loss: 0.9893 | Train acc: 50.93% | Val loss: 1.0191 | Val acc: 50.62% | LR: 0.000650
Epoch: 055 | Train loss: 1.0016 | Train acc: 51.05% | Val loss: 1.0028 | Val acc: 50.35% | LR: 0.000642
Epoch: 056 | Train loss: 0.9913 | Train acc: 50.32% | Val loss: 1.0004 | Val acc: 50.45% | LR: 0.000633
Epoch: 057 | Train loss: 0.9923 | Train acc: 50.35% | Val loss: 0.9826 | Val acc: 51.10% | LR: 0.000624
Epoch: 058 | Train loss: 0.9855 | Train acc: 50.92% | Val loss: 0.9992 | Val acc: 50.72% | LR: 0.000614
Epoch: 059 | Train loss: 0.9897 | Train acc: 50.65% | Val loss: 0.9954 | Val acc: 50.54% | LR: 0.000605
Epoch: 060 | Train loss: 0.9860 | Train acc: 50.68% | Val loss: 0.9953 | Val acc: 50.52% | LR: 0.000596
Epoch: 061 | Train loss: 1.0071 | Train acc: 50.61% | Val loss: 1.0035 | Val acc: 50.12% | LR: 0.000587
Epoch: 062 | Train loss: 0.9841 | Train acc: 50.92% | Val loss: 0.9983 | Val acc: 50.33% | LR: 0.000577
Epoch: 063 | Train loss: 0.9876 | Train acc: 50.88% | Val loss: 0.9994 | Val acc: 50.20% | LR: 0.000568
Epoch: 064 | Train loss: 0.9867 | Train acc: 50.87% | Val loss: 0.9932 | Val acc: 50.50% | LR: 0.000559
Epoch: 065 | Train loss: 0.9849 | Train acc: 51.13% | Val loss: 0.9966 | Val acc: 50.19% | LR: 0.000549
Epoch: 066 | Train loss: 0.9864 | Train acc: 50.71% | Val loss: 0.9929 | Val acc: 50.00% | LR: 0.000540
Epoch: 067 | Train loss: 0.9908 | Train acc: 50.69% | Val loss: 0.9967 | Val acc: 50.18% | LR: 0.000530
Epoch: 068 | Train loss: 0.9832 | Train acc: 51.42% | Val loss: 0.9935 | Val acc: 49.97% | LR: 0.000521
Epoch: 069 | Train loss: 0.9914 | Train acc: 50.59% | Val loss: 0.9912 | Val acc: 50.29% | LR: 0.000511
Epoch: 070 | Train loss: 0.9835 | Train acc: 51.34% | Val loss: 1.2631 | Val acc: 50.42% | LR: 0.000501
Epoch: 071 | Train loss: 0.9814 | Train acc: 51.02% | Val loss: 0.9941 | Val acc: 49.98% | LR: 0.000492
Epoch: 072 | Train loss: 0.9840 | Train acc: 50.88% | Val loss: 0.9943 | Val acc: 49.96% | LR: 0.000482
Epoch: 073 | Train loss: 0.9847 | Train acc: 51.03% | Val loss: 0.9950 | Val acc: 49.92% | LR: 0.000472
Epoch: 074 | Train loss: 0.9833 | Train acc: 51.00% | Val loss: 0.9912 | Val acc: 50.44% | LR: 0.000463
Epoch: 075 | Train loss: 0.9869 | Train acc: 50.74% | Val loss: 0.9946 | Val acc: 50.12% | LR: 0.000453
Epoch: 076 | Train loss: 0.9873 | Train acc: 50.74% | Val loss: 0.9998 | Val acc: 50.02% | LR: 0.000443
Epoch: 077 | Train loss: 0.9807 | Train acc: 51.34% | Val loss: 0.9935 | Val acc: 49.94% | LR: 0.000434
Epoch: 078 | Train loss: 0.9870 | Train acc: 50.63% | Val loss: 0.9921 | Val acc: 50.02% | LR: 0.000424
Epoch: 079 | Train loss: 0.9819 | Train acc: 51.29% | Val loss: 0.9908 | Val acc: 50.26% | LR: 0.000414
Epoch: 080 | Train loss: 0.9801 | Train acc: 51.53% | Val loss: 1.0072 | Val acc: 50.06% | LR: 0.000405
Epoch: 081 | Train loss: 0.9839 | Train acc: 50.98% | Val loss: 0.9909 | Val acc: 50.14% | LR: 0.000395
Epoch: 082 | Train loss: 0.9862 | Train acc: 50.90% | Val loss: 1.0056 | Val acc: 50.13% | LR: 0.000386
Epoch: 083 | Train loss: 0.9855 | Train acc: 50.88% | Val loss: 0.9991 | Val acc: 49.98% | LR: 0.000376
Epoch: 084 | Train loss: 0.9976 | Train acc: 50.18% | Val loss: 0.9982 | Val acc: 50.12% | LR: 0.000367
Epoch: 085 | Train loss: 0.9871 | Train acc: 50.90% | Val loss: 0.9994 | Val acc: 50.16% | LR: 0.000357
Epoch: 086 | Train loss: 0.9858 | Train acc: 50.78% | Val loss: 0.9989 | Val acc: 50.26% | LR: 0.000348
Epoch: 087 | Train loss: 0.9826 | Train acc: 51.18% | Val loss: 0.9997 | Val acc: 50.26% | LR: 0.000339
Epoch: 088 | Train loss: 0.9920 | Train acc: 50.61% | Val loss: 0.9924 | Val acc: 50.34% | LR: 0.000329
Epoch: 089 | Train loss: 0.9870 | Train acc: 50.88% | Val loss: 0.9930 | Val acc: 50.22% | LR: 0.000320
Epoch: 090 | Train loss: 0.9885 | Train acc: 50.49% | Val loss: 1.0176 | Val acc: 50.16% | LR: 0.000311
Epoch: 091 | Train loss: 0.9850 | Train acc: 51.08% | Val loss: 1.0055 | Val acc: 49.96% | LR: 0.000302
Epoch: 092 | Train loss: 0.9928 | Train acc: 50.69% | Val loss: 0.9972 | Val acc: 49.96% | LR: 0.000293
Epoch: 093 | Train loss: 0.9809 | Train acc: 51.22% | Val loss: 0.9967 | Val acc: 49.69% | LR: 0.000284
Epoch: 094 | Train loss: 0.9836 | Train acc: 50.92% | Val loss: 0.9934 | Val acc: 50.08% | LR: 0.000275
Epoch: 095 | Train loss: 0.9875 | Train acc: 50.71% | Val loss: 0.9971 | Val acc: 50.13% | LR: 0.000266
Epoch: 096 | Train loss: 0.9841 | Train acc: 50.80% | Val loss: 0.9982 | Val acc: 50.20% | LR: 0.000257
Epoch: 097 | Train loss: 0.9851 | Train acc: 51.01% | Val loss: 0.9913 | Val acc: 50.55% | LR: 0.000249
Epoch: 098 | Train loss: 0.9815 | Train acc: 51.15% | Val loss: 0.9955 | Val acc: 50.26% | LR: 0.000240
Epoch: 099 | Train loss: 0.9887 | Train acc: 50.78% | Val loss: 0.9954 | Val acc: 50.27% | LR: 0.000232
Epoch: 100 | Train loss: 0.9881 | Train acc: 50.77% | Val loss: 0.9940 | Val acc: 50.31% | LR: 0.000224
Epoch: 101 | Train loss: 0.9866 | Train acc: 50.81% | Val loss: 0.9965 | Val acc: 50.04% | LR: 0.000215
Epoch: 102 | Train loss: 0.9878 | Train acc: 50.90% | Val loss: 1.0010 | Val acc: 49.50% | LR: 0.000207
Epoch: 103 | Train loss: 0.9776 | Train acc: 51.28% | Val loss: 0.9954 | Val acc: 49.91% | LR: 0.000199
Epoch: 104 | Train loss: 0.9843 | Train acc: 51.12% | Val loss: 0.9988 | Val acc: 49.91% | LR: 0.000191
Epoch: 105 | Train loss: 0.9868 | Train acc: 50.87% | Val loss: 1.0027 | Val acc: 49.76% | LR: 0.000184
Epoch: 106 | Train loss: 0.9821 | Train acc: 51.12% | Val loss: 0.9957 | Val acc: 49.76% | LR: 0.000176
Epoch: 107 | Train loss: 0.9853 | Train acc: 51.07% | Val loss: 1.0001 | Val acc: 49.69% | LR: 0.000168
Epoch: 108 | Train loss: 0.9888 | Train acc: 50.69% | Val loss: 0.9951 | Val acc: 49.87% | LR: 0.000161
Epoch: 109 | Train loss: 0.9785 | Train acc: 51.32% | Val loss: 0.9959 | Val acc: 49.93% | LR: 0.000154
Epoch: 110 | Train loss: 0.9838 | Train acc: 50.84% | Val loss: 1.0273 | Val acc: 50.05% | LR: 0.000147
Epoch: 111 | Train loss: 0.9852 | Train acc: 50.85% | Val loss: 0.9983 | Val acc: 49.71% | LR: 0.000140
Epoch: 112 | Train loss: 0.9877 | Train acc: 50.90% | Val loss: 0.9973 | Val acc: 49.81% | LR: 0.000133
Epoch: 113 | Train loss: 0.9970 | Train acc: 50.08% | Val loss: 1.0022 | Val acc: 49.91% | LR: 0.000126
Epoch: 114 | Train loss: 0.9884 | Train acc: 50.63% | Val loss: 0.9972 | Val acc: 49.85% | LR: 0.000120
Epoch: 115 | Train loss: 0.9779 | Train acc: 51.46% | Val loss: 1.0015 | Val acc: 49.82% | LR: 0.000113
Epoch: 116 | Train loss: 0.9879 | Train acc: 50.81% | Val loss: 1.0033 | Val acc: 50.17% | LR: 0.000107
Epoch: 117 | Train loss: 0.9861 | Train acc: 50.81% | Val loss: 0.9974 | Val acc: 49.72% | LR: 0.000101
Epoch: 118 | Train loss: 0.9896 | Train acc: 50.73% | Val loss: 1.0022 | Val acc: 49.18% | LR: 0.000095
Epoch: 119 | Train loss: 0.9904 | Train acc: 50.75% | Val loss: 1.0022 | Val acc: 49.42% | LR: 0.000089
Epoch: 120 | Train loss: 0.9873 | Train acc: 50.76% | Val loss: 0.9992 | Val acc: 49.75% | LR: 0.000084
Epoch: 121 | Train loss: 0.9931 | Train acc: 50.25% | Val loss: 0.9990 | Val acc: 49.78% | LR: 0.000078
Epoch: 122 | Train loss: 0.9787 | Train acc: 51.43% | Val loss: 1.0050 | Val acc: 49.75% | LR: 0.000073
Epoch: 123 | Train loss: 0.9828 | Train acc: 51.08% | Val loss: 1.0396 | Val acc: 49.75% | LR: 0.000068
Epoch: 124 | Train loss: 0.9834 | Train acc: 51.16% | Val loss: 1.0015 | Val acc: 49.83% | LR: 0.000063
Epoch: 125 | Train loss: 0.9890 | Train acc: 50.62% | Val loss: 1.0051 | Val acc: 49.65% | LR: 0.000058
Epoch: 126 | Train loss: 0.9877 | Train acc: 50.72% | Val loss: 1.0041 | Val acc: 49.73% | LR: 0.000054
Epoch: 127 | Train loss: 0.9892 | Train acc: 50.88% | Val loss: 0.9961 | Val acc: 49.90% | LR: 0.000049
Epoch: 128 | Train loss: 0.9828 | Train acc: 51.13% | Val loss: 0.9975 | Val acc: 49.88% | LR: 0.000045
Epoch: 129 | Train loss: 0.9857 | Train acc: 50.86% | Val loss: 0.9958 | Val acc: 49.98% | LR: 0.000041
Epoch: 130 | Train loss: 0.9874 | Train acc: 50.66% | Val loss: 1.0031 | Val acc: 49.68% | LR: 0.000037
Epoch: 131 | Train loss: 0.9815 | Train acc: 51.15% | Val loss: 1.0037 | Val acc: 49.82% | LR: 0.000033
Epoch: 132 | Train loss: 0.9821 | Train acc: 51.03% | Val loss: 0.9994 | Val acc: 49.86% | LR: 0.000030
Epoch: 133 | Train loss: 0.9705 | Train acc: 51.83% | Val loss: 0.9999 | Val acc: 49.80% | LR: 0.000027
Epoch: 134 | Train loss: 0.9813 | Train acc: 51.20% | Val loss: 0.9996 | Val acc: 49.84% | LR: 0.000024
Epoch: 135 | Train loss: 0.9821 | Train acc: 51.04% | Val loss: 1.0010 | Val acc: 49.76% | LR: 0.000021
Epoch: 136 | Train loss: 0.9877 | Train acc: 50.78% | Val loss: 1.0102 | Val acc: 49.84% | LR: 0.000018
Epoch: 137 | Train loss: 0.9809 | Train acc: 51.03% | Val loss: 1.0060 | Val acc: 49.84% | LR: 0.000016
Epoch: 138 | Train loss: 0.9828 | Train acc: 51.03% | Val loss: 1.0000 | Val acc: 49.80% | LR: 0.000013
Epoch: 139 | Train loss: 0.9873 | Train acc: 50.78% | Val loss: 0.9990 | Val acc: 49.84% | LR: 0.000011
Epoch: 140 | Train loss: 0.9819 | Train acc: 51.04% | Val loss: 0.9990 | Val acc: 49.86% | LR: 0.000009
Epoch: 141 | Train loss: 0.9870 | Train acc: 50.95% | Val loss: 0.9992 | Val acc: 49.80% | LR: 0.000007
Epoch: 142 | Train loss: 0.9844 | Train acc: 50.87% | Val loss: 0.9990 | Val acc: 49.80% | LR: 0.000006
Epoch: 143 | Train loss: 0.9861 | Train acc: 50.76% | Val loss: 0.9991 | Val acc: 49.86% | LR: 0.000005
Epoch: 144 | Train loss: 0.9835 | Train acc: 51.09% | Val loss: 1.0005 | Val acc: 49.86% | LR: 0.000004
Epoch: 145 | Train loss: 0.9869 | Train acc: 50.87% | Val loss: 0.9998 | Val acc: 49.86% | LR: 0.000003
Epoch: 146 | Train loss: 0.9904 | Train acc: 50.31% | Val loss: 1.0007 | Val acc: 49.88% | LR: 0.000002
Epoch: 147 | Train loss: 0.9854 | Train acc: 50.84% | Val loss: 1.0026 | Val acc: 49.86% | LR: 0.000001
Epoch: 148 | Train loss: 0.9812 | Train acc: 51.20% | Val loss: 1.0040 | Val acc: 49.86% | LR: 0.000001
Epoch: 149 | Train loss: 0.9871 | Train acc: 50.75% | Val loss: 1.0010 | Val acc: 49.86% | LR: 0.000001

[I 2025-09-23 02:34:01,540] Trial 22 finished with value: 0.5455858588218689 and parameters: {'lr': 0.0009243402666103192, 'hidden_size': 120, 'dropout': 0.3020272468359896, 'weight_decay': 0.41193257254033055}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.3235 | Train acc: 50.56% | Val loss: 1.0436 | Val acc: 45.95% | LR: 0.006344
Epoch: 001 | Train loss: 1.0104 | Train acc: 49.80% | Val loss: 1.0027 | Val acc: 49.01% | LR: 0.006342
Epoch: 002 | Train loss: 1.0064 | Train acc: 49.83% | Val loss: 1.0045 | Val acc: 48.10% | LR: 0.006339
Epoch: 003 | Train loss: 1.0034 | Train acc: 50.49% | Val loss: 0.9637 | Val acc: 54.61% | LR: 0.006334
Epoch: 004 | Train loss: 0.9915 | Train acc: 51.24% | Val loss: 0.9880 | Val acc: 50.51% | LR: 0.006328
Epoch: 005 | Train loss: 0.9992 | Train acc: 50.76% | Val loss: 0.9842 | Val acc: 50.68% | LR: 0.006320
Epoch: 006 | Train loss: 1.0002 | Train acc: 50.57% | Val loss: 1.0077 | Val acc: 48.67% | LR: 0.006311
Epoch: 007 | Train loss: 0.9965 | Train acc: 50.59% | Val loss: 0.9951 | Val acc: 51.30% | LR: 0.006301
Epoch: 008 | Train loss: 0.9947 | Train acc: 50.27% | Val loss: 0.9785 | Val acc: 53.12% | LR: 0.006289
Epoch: 009 | Train loss: 1.0011 | Train acc: 51.07% | Val loss: 0.9836 | Val acc: 51.99% | LR: 0.006276
Epoch: 010 | Train loss: 1.0077 | Train acc: 50.95% | Val loss: 1.0017 | Val acc: 50.79% | LR: 0.006261
Epoch: 011 | Train loss: 1.0051 | Train acc: 50.24% | Val loss: 1.0143 | Val acc: 47.68% | LR: 0.006245
Epoch: 012 | Train loss: 0.9984 | Train acc: 50.78% | Val loss: 0.9870 | Val acc: 51.87% | LR: 0.006228
Epoch: 013 | Train loss: 0.9939 | Train acc: 50.84% | Val loss: 0.9768 | Val acc: 51.62% | LR: 0.006210
Epoch: 014 | Train loss: 1.0020 | Train acc: 50.51% | Val loss: 0.9771 | Val acc: 51.84% | LR: 0.006190
Epoch: 015 | Train loss: 0.9965 | Train acc: 50.46% | Val loss: 0.9821 | Val acc: 51.28% | LR: 0.006169
Epoch: 016 | Train loss: 0.9992 | Train acc: 50.75% | Val loss: 0.9739 | Val acc: 51.74% | LR: 0.006146
Epoch: 017 | Train loss: 1.0382 | Train acc: 51.44% | Val loss: 0.9879 | Val acc: 52.76% | LR: 0.006122
Epoch: 018 | Train loss: 1.0068 | Train acc: 49.90% | Val loss: 0.9925 | Val acc: 50.64% | LR: 0.006097
Epoch: 019 | Train loss: 1.0108 | Train acc: 50.06% | Val loss: 0.9464 | Val acc: 54.05% | LR: 0.006071
Epoch: 020 | Train loss: 1.0067 | Train acc: 50.25% | Val loss: 0.9782 | Val acc: 54.47% | LR: 0.006043
Epoch: 021 | Train loss: 0.9965 | Train acc: 51.03% | Val loss: 0.9940 | Val acc: 50.96% | LR: 0.006014
Epoch: 022 | Train loss: 1.0034 | Train acc: 50.01% | Val loss: 0.9826 | Val acc: 54.09% | LR: 0.005984
Epoch: 023 | Train loss: 1.0032 | Train acc: 50.07% | Val loss: 0.9912 | Val acc: 50.11% | LR: 0.005953
Epoch: 024 | Train loss: 1.0051 | Train acc: 49.61% | Val loss: 0.9910 | Val acc: 49.77% | LR: 0.005920
Epoch: 025 | Train loss: 0.9939 | Train acc: 50.75% | Val loss: 0.9903 | Val acc: 49.73% | LR: 0.005886
Epoch: 026 | Train loss: 0.9988 | Train acc: 50.29% | Val loss: 0.9927 | Val acc: 49.42% | LR: 0.005851
Epoch: 027 | Train loss: 0.9955 | Train acc: 51.07% | Val loss: 0.9788 | Val acc: 52.62% | LR: 0.005815
Epoch: 028 | Train loss: 0.9966 | Train acc: 50.69% | Val loss: 0.9608 | Val acc: 54.93% | LR: 0.005778
Epoch: 029 | Train loss: 0.9981 | Train acc: 50.63% | Val loss: 0.9543 | Val acc: 54.64% | LR: 0.005739
Epoch: 030 | Train loss: 0.9993 | Train acc: 50.51% | Val loss: 0.9905 | Val acc: 51.55% | LR: 0.005700
Epoch: 031 | Train loss: 0.9944 | Train acc: 50.80% | Val loss: 1.0095 | Val acc: 48.57% | LR: 0.005659
Epoch: 032 | Train loss: 0.9979 | Train acc: 50.85% | Val loss: 0.9997 | Val acc: 50.73% | LR: 0.005617
Epoch: 033 | Train loss: 0.9969 | Train acc: 51.07% | Val loss: 0.9541 | Val acc: 53.28% | LR: 0.005574
Epoch: 034 | Train loss: 0.9983 | Train acc: 51.08% | Val loss: 1.0520 | Val acc: 45.95% | LR: 0.005530
Epoch: 035 | Train loss: 0.9995 | Train acc: 50.54% | Val loss: 0.9427 | Val acc: 54.10% | LR: 0.005485
Epoch: 036 | Train loss: 1.0018 | Train acc: 49.73% | Val loss: 1.0219 | Val acc: 45.95% | LR: 0.005439
Epoch: 037 | Train loss: 1.0027 | Train acc: 49.79% | Val loss: 1.0027 | Val acc: 49.38% | LR: 0.005392
Epoch: 038 | Train loss: 1.0049 | Train acc: 50.04% | Val loss: 0.9975 | Val acc: 49.53% | LR: 0.005344
Epoch: 039 | Train loss: 0.9939 | Train acc: 50.62% | Val loss: 0.9661 | Val acc: 54.30% | LR: 0.005295
Epoch: 040 | Train loss: 1.0045 | Train acc: 50.29% | Val loss: 0.9627 | Val acc: 54.38% | LR: 0.005246
Epoch: 041 | Train loss: 1.0008 | Train acc: 50.54% | Val loss: 0.9760 | Val acc: 52.71% | LR: 0.005195
Epoch: 042 | Train loss: 0.9986 | Train acc: 50.46% | Val loss: 1.0029 | Val acc: 49.65% | LR: 0.005143
Epoch: 043 | Train loss: 1.0106 | Train acc: 49.58% | Val loss: 0.9866 | Val acc: 50.17% | LR: 0.005091
Epoch: 044 | Train loss: 1.0034 | Train acc: 49.98% | Val loss: 0.9757 | Val acc: 54.40% | LR: 0.005037
Epoch: 045 | Train loss: 1.0043 | Train acc: 49.77% | Val loss: 0.9646 | Val acc: 52.22% | LR: 0.004983
Epoch: 046 | Train loss: 1.0072 | Train acc: 50.01% | Val loss: 1.0052 | Val acc: 51.88% | LR: 0.004928
Epoch: 047 | Train loss: 0.9960 | Train acc: 50.84% | Val loss: 1.0588 | Val acc: 45.95% | LR: 0.004873
Epoch: 048 | Train loss: 0.9972 | Train acc: 50.52% | Val loss: 0.9497 | Val acc: 53.84% | LR: 0.004816
Epoch: 049 | Train loss: 0.9993 | Train acc: 49.97% | Val loss: 1.0008 | Val acc: 49.73% | LR: 0.004759
Epoch: 050 | Train loss: 1.0072 | Train acc: 49.74% | Val loss: 0.9866 | Val acc: 52.84% | LR: 0.004701
Epoch: 051 | Train loss: 0.9965 | Train acc: 50.56% | Val loss: 0.9637 | Val acc: 53.07% | LR: 0.004643
Epoch: 052 | Train loss: 1.0070 | Train acc: 49.72% | Val loss: 0.9676 | Val acc: 54.08% | LR: 0.004583
Epoch: 053 | Train loss: 1.0001 | Train acc: 50.28% | Val loss: 0.9606 | Val acc: 54.87% | LR: 0.004524
Epoch: 054 | Train loss: 0.9966 | Train acc: 50.76% | Val loss: 0.9577 | Val acc: 54.89% | LR: 0.004463
Epoch: 055 | Train loss: 0.9960 | Train acc: 50.37% | Val loss: 0.9745 | Val acc: 54.51% | LR: 0.004402
Epoch: 056 | Train loss: 1.0032 | Train acc: 50.35% | Val loss: 0.9823 | Val acc: 52.62% | LR: 0.004341
Epoch: 057 | Train loss: 0.9995 | Train acc: 49.98% | Val loss: 0.9432 | Val acc: 54.04% | LR: 0.004279
Epoch: 058 | Train loss: 1.0005 | Train acc: 50.49% | Val loss: 1.0226 | Val acc: 49.80% | LR: 0.004216
Epoch: 059 | Train loss: 0.9982 | Train acc: 50.17% | Val loss: 0.9881 | Val acc: 52.15% | LR: 0.004153
Epoch: 060 | Train loss: 0.9985 | Train acc: 49.80% | Val loss: 0.9944 | Val acc: 49.56% | LR: 0.004090
Epoch: 061 | Train loss: 1.0001 | Train acc: 50.19% | Val loss: 1.0174 | Val acc: 49.53% | LR: 0.004026
Epoch: 062 | Train loss: 1.0010 | Train acc: 50.50% | Val loss: 1.0076 | Val acc: 50.93% | LR: 0.003962
Epoch: 063 | Train loss: 1.0610 | Train acc: 50.39% | Val loss: 1.0234 | Val acc: 45.95% | LR: 0.003897
Epoch: 064 | Train loss: 0.9936 | Train acc: 50.56% | Val loss: 0.9779 | Val acc: 53.76% | LR: 0.003832
Epoch: 065 | Train loss: 1.0040 | Train acc: 49.46% | Val loss: 0.9451 | Val acc: 54.40% | LR: 0.003767
Epoch: 066 | Train loss: 0.9968 | Train acc: 50.38% | Val loss: 0.9781 | Val acc: 52.49% | LR: 0.003702
Epoch: 067 | Train loss: 1.0094 | Train acc: 49.29% | Val loss: 0.9717 | Val acc: 54.97% | LR: 0.003636
Epoch: 068 | Train loss: 1.0022 | Train acc: 49.76% | Val loss: 0.9741 | Val acc: 53.54% | LR: 0.003571
Epoch: 069 | Train loss: 0.9907 | Train acc: 50.98% | Val loss: 0.9762 | Val acc: 52.82% | LR: 0.003505
Epoch: 070 | Train loss: 0.9935 | Train acc: 51.13% | Val loss: 0.9814 | Val acc: 51.67% | LR: 0.003438
Epoch: 071 | Train loss: 0.9957 | Train acc: 50.27% | Val loss: 0.9974 | Val acc: 51.03% | LR: 0.003372
Epoch: 072 | Train loss: 0.9940 | Train acc: 50.72% | Val loss: 1.0034 | Val acc: 48.98% | LR: 0.003306
Epoch: 073 | Train loss: 0.9939 | Train acc: 50.73% | Val loss: 1.0329 | Val acc: 47.25% | LR: 0.003239
Epoch: 074 | Train loss: 0.9941 | Train acc: 50.74% | Val loss: 0.9887 | Val acc: 51.34% | LR: 0.003173
Epoch: 075 | Train loss: 0.9903 | Train acc: 50.60% | Val loss: 1.0251 | Val acc: 47.79% | LR: 0.003107
Epoch: 076 | Train loss: 0.9923 | Train acc: 51.15% | Val loss: 1.0048 | Val acc: 49.07% | LR: 0.003040
Epoch: 077 | Train loss: 0.9929 | Train acc: 50.71% | Val loss: 1.0027 | Val acc: 48.93% | LR: 0.002974
Epoch: 078 | Train loss: 0.9937 | Train acc: 50.93% | Val loss: 1.0017 | Val acc: 49.09% | LR: 0.002908
Epoch: 079 | Train loss: 0.9980 | Train acc: 50.13% | Val loss: 1.0209 | Val acc: 48.94% | LR: 0.002841
Epoch: 080 | Train loss: 0.9903 | Train acc: 50.88% | Val loss: 1.0054 | Val acc: 49.21% | LR: 0.002775
Epoch: 081 | Train loss: 0.9855 | Train acc: 51.39% | Val loss: 1.0184 | Val acc: 48.48% | LR: 0.002710
Epoch: 082 | Train loss: 0.9934 | Train acc: 50.90% | Val loss: 1.0082 | Val acc: 48.72% | LR: 0.002644
Epoch: 083 | Train loss: 0.9902 | Train acc: 50.57% | Val loss: 0.9851 | Val acc: 51.96% | LR: 0.002579
Epoch: 084 | Train loss: 0.9945 | Train acc: 50.84% | Val loss: 0.9765 | Val acc: 52.10% | LR: 0.002513
Epoch: 085 | Train loss: 0.9935 | Train acc: 50.86% | Val loss: 0.9758 | Val acc: 52.69% | LR: 0.002449
Epoch: 086 | Train loss: 0.9857 | Train acc: 51.53% | Val loss: 0.9697 | Val acc: 52.76% | LR: 0.002384
Epoch: 087 | Train loss: 0.9907 | Train acc: 50.64% | Val loss: 0.9983 | Val acc: 52.07% | LR: 0.002320
Epoch: 088 | Train loss: 1.0059 | Train acc: 50.69% | Val loss: 0.9744 | Val acc: 52.92% | LR: 0.002256
Epoch: 089 | Train loss: 1.0194 | Train acc: 49.69% | Val loss: 1.0029 | Val acc: 52.59% | LR: 0.002193
Epoch: 090 | Train loss: 1.0052 | Train acc: 50.54% | Val loss: 0.9837 | Val acc: 52.99% | LR: 0.002130
Epoch: 091 | Train loss: 0.9975 | Train acc: 51.36% | Val loss: 0.9762 | Val acc: 52.54% | LR: 0.002067
Epoch: 092 | Train loss: 0.9953 | Train acc: 51.33% | Val loss: 0.9683 | Val acc: 53.13% | LR: 0.002005
Epoch: 093 | Train loss: 0.9981 | Train acc: 50.37% | Val loss: 0.9790 | Val acc: 53.09% | LR: 0.001944
Epoch: 094 | Train loss: 0.9931 | Train acc: 50.71% | Val loss: 0.9923 | Val acc: 51.49% | LR: 0.001883
Epoch: 095 | Train loss: 1.0019 | Train acc: 50.40% | Val loss: 0.9903 | Val acc: 53.74% | LR: 0.001822
Epoch: 096 | Train loss: 0.9965 | Train acc: 50.79% | Val loss: 0.9812 | Val acc: 52.25% | LR: 0.001763
Epoch: 097 | Train loss: 0.9996 | Train acc: 50.66% | Val loss: 1.1047 | Val acc: 49.13% | LR: 0.001703
Epoch: 098 | Train loss: 1.0010 | Train acc: 50.80% | Val loss: 1.0311 | Val acc: 50.52% | LR: 0.001645
Epoch: 099 | Train loss: 1.0037 | Train acc: 49.93% | Val loss: 1.0231 | Val acc: 48.41% | LR: 0.001587
Epoch: 100 | Train loss: 1.0035 | Train acc: 50.17% | Val loss: 1.0568 | Val acc: 48.99% | LR: 0.001530
Epoch: 101 | Train loss: 1.0026 | Train acc: 50.52% | Val loss: 0.9669 | Val acc: 54.39% | LR: 0.001473
Epoch: 102 | Train loss: 0.9971 | Train acc: 50.55% | Val loss: 0.9887 | Val acc: 52.22% | LR: 0.001418
Epoch: 103 | Train loss: 0.9978 | Train acc: 50.98% | Val loss: 3.8350 | Val acc: 52.46% | LR: 0.001363
Epoch: 104 | Train loss: 0.9986 | Train acc: 50.79% | Val loss: 0.9876 | Val acc: 52.60% | LR: 0.001309
Epoch: 105 | Train loss: 0.9886 | Train acc: 51.49% | Val loss: 1.0011 | Val acc: 52.23% | LR: 0.001255
Epoch: 106 | Train loss: 1.0014 | Train acc: 50.09% | Val loss: 0.9661 | Val acc: 53.04% | LR: 0.001203
Epoch: 107 | Train loss: 0.9959 | Train acc: 50.79% | Val loss: 0.9611 | Val acc: 53.88% | LR: 0.001151
Epoch: 108 | Train loss: 0.9980 | Train acc: 50.59% | Val loss: 0.9917 | Val acc: 52.51% | LR: 0.001100
Epoch: 109 | Train loss: 0.9881 | Train acc: 50.97% | Val loss: 0.9988 | Val acc: 50.36% | LR: 0.001051
Epoch: 110 | Train loss: 0.9921 | Train acc: 50.63% | Val loss: 0.9904 | Val acc: 51.46% | LR: 0.001002
Epoch: 111 | Train loss: 0.9926 | Train acc: 50.86% | Val loss: 0.9742 | Val acc: 53.15% | LR: 0.000954
Epoch: 112 | Train loss: 0.9947 | Train acc: 50.52% | Val loss: 0.9731 | Val acc: 53.35% | LR: 0.000907
Epoch: 113 | Train loss: 0.9947 | Train acc: 50.89% | Val loss: 0.9825 | Val acc: 52.72% | LR: 0.000861
Epoch: 114 | Train loss: 0.9914 | Train acc: 50.83% | Val loss: 0.9610 | Val acc: 53.63% | LR: 0.000816
Epoch: 115 | Train loss: 0.9940 | Train acc: 50.78% | Val loss: 0.9878 | Val acc: 52.48% | LR: 0.000772
Epoch: 116 | Train loss: 0.9902 | Train acc: 50.80% | Val loss: 0.9616 | Val acc: 53.70% | LR: 0.000729
Epoch: 117 | Train loss: 0.9940 | Train acc: 50.64% | Val loss: 0.9656 | Val acc: 53.39% | LR: 0.000687
Epoch: 118 | Train loss: 0.9889 | Train acc: 51.35% | Val loss: 0.9729 | Val acc: 52.90% | LR: 0.000646
Epoch: 119 | Train loss: 0.9911 | Train acc: 50.78% | Val loss: 0.9708 | Val acc: 52.92% | LR: 0.000607
Epoch: 120 | Train loss: 0.9853 | Train acc: 51.28% | Val loss: 0.9602 | Val acc: 53.73% | LR: 0.000568
Epoch: 121 | Train loss: 0.9913 | Train acc: 50.71% | Val loss: 0.9493 | Val acc: 53.98% | LR: 0.000531
Epoch: 122 | Train loss: 0.9948 | Train acc: 50.65% | Val loss: 0.9650 | Val acc: 53.73% | LR: 0.000495
Epoch: 123 | Train loss: 0.9925 | Train acc: 50.83% | Val loss: 0.9649 | Val acc: 52.96% | LR: 0.000460
Epoch: 124 | Train loss: 0.9829 | Train acc: 51.20% | Val loss: 0.9642 | Val acc: 53.02% | LR: 0.000426
Epoch: 125 | Train loss: 0.9840 | Train acc: 51.49% | Val loss: 0.9655 | Val acc: 52.61% | LR: 0.000393
Epoch: 126 | Train loss: 0.9846 | Train acc: 51.37% | Val loss: 0.9535 | Val acc: 53.76% | LR: 0.000362
Epoch: 127 | Train loss: 0.9863 | Train acc: 51.03% | Val loss: 0.9593 | Val acc: 53.16% | LR: 0.000332
Epoch: 128 | Train loss: 0.9919 | Train acc: 50.56% | Val loss: 0.9528 | Val acc: 53.87% | LR: 0.000303
Epoch: 129 | Train loss: 0.9853 | Train acc: 50.96% | Val loss: 0.9588 | Val acc: 53.27% | LR: 0.000275
Epoch: 130 | Train loss: 0.9892 | Train acc: 50.88% | Val loss: 0.9603 | Val acc: 53.47% | LR: 0.000249
Epoch: 131 | Train loss: 0.9830 | Train acc: 51.21% | Val loss: 0.9602 | Val acc: 52.86% | LR: 0.000224
Epoch: 132 | Train loss: 0.9877 | Train acc: 51.00% | Val loss: 0.9604 | Val acc: 52.66% | LR: 0.000200
Epoch: 133 | Train loss: 0.9852 | Train acc: 51.14% | Val loss: 0.9694 | Val acc: 53.04% | LR: 0.000177
Epoch: 134 | Train loss: 0.9906 | Train acc: 50.71% | Val loss: 0.9566 | Val acc: 53.46% | LR: 0.000156
Epoch: 135 | Train loss: 0.9830 | Train acc: 51.27% | Val loss: 0.9560 | Val acc: 53.42% | LR: 0.000136
Epoch: 136 | Train loss: 0.9897 | Train acc: 50.88% | Val loss: 0.9629 | Val acc: 52.60% | LR: 0.000118
Epoch: 137 | Train loss: 0.9811 | Train acc: 51.35% | Val loss: 0.9549 | Val acc: 53.42% | LR: 0.000101
Epoch: 138 | Train loss: 0.9829 | Train acc: 51.28% | Val loss: 0.9567 | Val acc: 53.44% | LR: 0.000085
Epoch: 139 | Train loss: 0.9817 | Train acc: 51.37% | Val loss: 0.9518 | Val acc: 53.56% | LR: 0.000070
Epoch: 140 | Train loss: 0.9798 | Train acc: 51.42% | Val loss: 0.9550 | Val acc: 53.38% | LR: 0.000057
Epoch: 141 | Train loss: 0.9824 | Train acc: 51.10% | Val loss: 0.9541 | Val acc: 53.44% | LR: 0.000045
Epoch: 142 | Train loss: 0.9817 | Train acc: 51.35% | Val loss: 0.9506 | Val acc: 53.44% | LR: 0.000035
Epoch: 143 | Train loss: 0.9900 | Train acc: 50.83% | Val loss: 0.9515 | Val acc: 53.48% | LR: 0.000026
Epoch: 144 | Train loss: 0.9860 | Train acc: 51.22% | Val loss: 0.9516 | Val acc: 53.48% | LR: 0.000018
Epoch: 145 | Train loss: 0.9841 | Train acc: 51.29% | Val loss: 0.9521 | Val acc: 53.46% | LR: 0.000012
Epoch: 146 | Train loss: 0.9807 | Train acc: 51.36% | Val loss: 0.9521 | Val acc: 53.46% | LR: 0.000007
Epoch: 147 | Train loss: 0.9842 | Train acc: 51.12% | Val loss: 0.9519 | Val acc: 53.54% | LR: 0.000004
Epoch: 148 | Train loss: 0.9814 | Train acc: 51.30% | Val loss: 0.9521 | Val acc: 53.46% | LR: 0.000002
Epoch: 149 | Train loss: 0.9853 | Train acc: 51.40% | Val loss: 0.9521 | Val acc: 53.46% | LR: 0.000001

[I 2025-09-23 02:37:45,706] Trial 23 finished with value: 0.5497258424758911 and parameters: {'lr': 0.006344985284009179, 'hidden_size': 158, 'dropout': 0.38919009424470485, 'weight_decay': 0.6621680552769151}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.0327 | Train acc: 50.51% | Val loss: 1.0043 | Val acc: 52.88% | LR: 0.001912
Epoch: 001 | Train loss: 0.9981 | Train acc: 50.26% | Val loss: 0.9702 | Val acc: 54.24% | LR: 0.001912
Epoch: 002 | Train loss: 0.9903 | Train acc: 50.67% | Val loss: 0.9997 | Val acc: 49.73% | LR: 0.001911
Epoch: 003 | Train loss: 0.9914 | Train acc: 50.93% | Val loss: 0.9951 | Val acc: 51.54% | LR: 0.001909
Epoch: 004 | Train loss: 0.9968 | Train acc: 50.65% | Val loss: 0.9924 | Val acc: 50.94% | LR: 0.001907
Epoch: 005 | Train loss: 0.9939 | Train acc: 50.73% | Val loss: 0.9844 | Val acc: 51.60% | LR: 0.001905
Epoch: 006 | Train loss: 0.9973 | Train acc: 50.00% | Val loss: 1.0106 | Val acc: 48.21% | LR: 0.001902
Epoch: 007 | Train loss: 0.9860 | Train acc: 50.80% | Val loss: 1.0002 | Val acc: 49.37% | LR: 0.001899
Epoch: 008 | Train loss: 0.9934 | Train acc: 50.58% | Val loss: 1.0078 | Val acc: 49.22% | LR: 0.001896
Epoch: 009 | Train loss: 0.9978 | Train acc: 50.19% | Val loss: 1.0065 | Val acc: 49.63% | LR: 0.001892
Epoch: 010 | Train loss: 0.9851 | Train acc: 51.59% | Val loss: 1.0100 | Val acc: 49.31% | LR: 0.001887
Epoch: 011 | Train loss: 0.9863 | Train acc: 51.44% | Val loss: 1.0059 | Val acc: 49.47% | LR: 0.001883
Epoch: 012 | Train loss: 0.9884 | Train acc: 51.05% | Val loss: 0.9943 | Val acc: 49.67% | LR: 0.001877
Epoch: 013 | Train loss: 0.9926 | Train acc: 50.80% | Val loss: 0.9579 | Val acc: 53.65% | LR: 0.001872
Epoch: 014 | Train loss: 0.9936 | Train acc: 50.73% | Val loss: 0.9674 | Val acc: 53.13% | LR: 0.001866
Epoch: 015 | Train loss: 0.9893 | Train acc: 50.83% | Val loss: 0.9957 | Val acc: 50.70% | LR: 0.001859
Epoch: 016 | Train loss: 0.9874 | Train acc: 51.02% | Val loss: 0.9934 | Val acc: 50.60% | LR: 0.001853
Epoch: 017 | Train loss: 0.9845 | Train acc: 51.00% | Val loss: 0.9772 | Val acc: 51.66% | LR: 0.001845
Epoch: 018 | Train loss: 0.9882 | Train acc: 51.13% | Val loss: 0.9976 | Val acc: 50.53% | LR: 0.001838
Epoch: 019 | Train loss: 0.9860 | Train acc: 51.07% | Val loss: 0.9959 | Val acc: 50.45% | LR: 0.001830
Epoch: 020 | Train loss: 0.9964 | Train acc: 50.37% | Val loss: 1.0133 | Val acc: 49.16% | LR: 0.001822
Epoch: 021 | Train loss: 0.9846 | Train acc: 51.01% | Val loss: 1.0023 | Val acc: 49.88% | LR: 0.001813
Epoch: 022 | Train loss: 0.9888 | Train acc: 51.09% | Val loss: 1.0041 | Val acc: 49.87% | LR: 0.001804
Epoch: 023 | Train loss: 0.9808 | Train acc: 51.43% | Val loss: 1.0079 | Val acc: 49.83% | LR: 0.001794
Epoch: 024 | Train loss: 0.9838 | Train acc: 51.36% | Val loss: 1.0043 | Val acc: 49.35% | LR: 0.001784
Epoch: 025 | Train loss: 0.9820 | Train acc: 51.58% | Val loss: 1.0263 | Val acc: 48.69% | LR: 0.001774
Epoch: 026 | Train loss: 0.9830 | Train acc: 51.21% | Val loss: 1.0259 | Val acc: 47.97% | LR: 0.001764
Epoch: 027 | Train loss: 0.9882 | Train acc: 50.93% | Val loss: 1.0239 | Val acc: 48.43% | LR: 0.001753
Epoch: 028 | Train loss: 0.9865 | Train acc: 50.98% | Val loss: 1.0344 | Val acc: 47.62% | LR: 0.001742
Epoch: 029 | Train loss: 0.9834 | Train acc: 51.24% | Val loss: 1.0329 | Val acc: 48.15% | LR: 0.001730
Epoch: 030 | Train loss: 0.9882 | Train acc: 50.78% | Val loss: 1.0299 | Val acc: 48.13% | LR: 0.001718
Epoch: 031 | Train loss: 0.9856 | Train acc: 51.22% | Val loss: 1.0270 | Val acc: 48.15% | LR: 0.001706
Epoch: 032 | Train loss: 0.9815 | Train acc: 51.44% | Val loss: 1.0292 | Val acc: 47.95% | LR: 0.001693
Epoch: 033 | Train loss: 0.9908 | Train acc: 50.80% | Val loss: 1.0408 | Val acc: 47.48% | LR: 0.001680
Epoch: 034 | Train loss: 0.9877 | Train acc: 50.75% | Val loss: 1.0266 | Val acc: 48.28% | LR: 0.001667
Epoch: 035 | Train loss: 0.9924 | Train acc: 50.32% | Val loss: 1.0352 | Val acc: 47.55% | LR: 0.001653
Epoch: 036 | Train loss: 0.9828 | Train acc: 51.14% | Val loss: 1.0449 | Val acc: 47.47% | LR: 0.001640
Epoch: 037 | Train loss: 0.9810 | Train acc: 51.44% | Val loss: 1.0241 | Val acc: 47.96% | LR: 0.001625
Epoch: 038 | Train loss: 0.9881 | Train acc: 51.05% | Val loss: 1.0472 | Val acc: 46.58% | LR: 0.001611
Epoch: 039 | Train loss: 0.9826 | Train acc: 51.80% | Val loss: 1.0336 | Val acc: 48.00% | LR: 0.001596
Epoch: 040 | Train loss: 0.9826 | Train acc: 51.41% | Val loss: 1.0247 | Val acc: 48.30% | LR: 0.001581
Epoch: 041 | Train loss: 0.9836 | Train acc: 51.37% | Val loss: 1.0193 | Val acc: 48.67% | LR: 0.001566
Epoch: 042 | Train loss: 0.9863 | Train acc: 51.10% | Val loss: 1.0200 | Val acc: 48.37% | LR: 0.001550
Epoch: 043 | Train loss: 0.9900 | Train acc: 50.85% | Val loss: 1.0031 | Val acc: 49.03% | LR: 0.001535
Epoch: 044 | Train loss: 0.9904 | Train acc: 50.70% | Val loss: 1.0161 | Val acc: 48.89% | LR: 0.001519
Epoch: 045 | Train loss: 0.9832 | Train acc: 51.35% | Val loss: 1.0427 | Val acc: 47.63% | LR: 0.001502
Epoch: 046 | Train loss: 0.9831 | Train acc: 51.41% | Val loss: 1.0068 | Val acc: 49.61% | LR: 0.001486
Epoch: 047 | Train loss: 0.9807 | Train acc: 51.40% | Val loss: 1.0328 | Val acc: 48.16% | LR: 0.001469
Epoch: 048 | Train loss: 0.9868 | Train acc: 50.97% | Val loss: 1.0400 | Val acc: 46.95% | LR: 0.001452
Epoch: 049 | Train loss: 0.9867 | Train acc: 50.91% | Val loss: 1.0195 | Val acc: 48.63% | LR: 0.001435
Epoch: 050 | Train loss: 0.9893 | Train acc: 50.83% | Val loss: 1.0249 | Val acc: 48.46% | LR: 0.001417
Epoch: 051 | Train loss: 0.9823 | Train acc: 51.60% | Val loss: 1.0292 | Val acc: 48.18% | LR: 0.001400
Epoch: 052 | Train loss: 0.9831 | Train acc: 51.03% | Val loss: 1.0313 | Val acc: 47.75% | LR: 0.001382
Epoch: 053 | Train loss: 0.9862 | Train acc: 51.21% | Val loss: 1.0310 | Val acc: 47.63% | LR: 0.001364
Epoch: 054 | Train loss: 1.0132 | Train acc: 51.48% | Val loss: 1.0365 | Val acc: 47.20% | LR: 0.001346
Epoch: 055 | Train loss: 0.9799 | Train acc: 51.37% | Val loss: 1.0099 | Val acc: 49.33% | LR: 0.001327
Epoch: 056 | Train loss: 0.9897 | Train acc: 50.65% | Val loss: 0.9996 | Val acc: 49.66% | LR: 0.001309
Epoch: 057 | Train loss: 0.9852 | Train acc: 51.12% | Val loss: 0.9808 | Val acc: 50.85% | LR: 0.001290
Epoch: 058 | Train loss: 0.9859 | Train acc: 51.14% | Val loss: 0.9862 | Val acc: 51.12% | LR: 0.001271
Epoch: 059 | Train loss: 0.9856 | Train acc: 51.20% | Val loss: 1.0354 | Val acc: 47.53% | LR: 0.001252
Epoch: 060 | Train loss: 0.9823 | Train acc: 51.32% | Val loss: 1.0171 | Val acc: 48.82% | LR: 0.001233
Epoch: 061 | Train loss: 0.9940 | Train acc: 50.41% | Val loss: 0.9695 | Val acc: 52.29% | LR: 0.001214
Epoch: 062 | Train loss: 0.9877 | Train acc: 50.95% | Val loss: 0.9258 | Val acc: 54.40% | LR: 0.001194
Epoch: 063 | Train loss: 0.9852 | Train acc: 51.00% | Val loss: 0.9492 | Val acc: 53.29% | LR: 0.001175
Epoch: 064 | Train loss: 0.9827 | Train acc: 51.35% | Val loss: 0.9546 | Val acc: 52.91% | LR: 0.001155
Epoch: 065 | Train loss: 0.9851 | Train acc: 50.99% | Val loss: 0.9761 | Val acc: 51.59% | LR: 0.001136
Epoch: 066 | Train loss: 0.9772 | Train acc: 51.70% | Val loss: 0.9709 | Val acc: 51.95% | LR: 0.001116
Epoch: 067 | Train loss: 0.9840 | Train acc: 51.16% | Val loss: 0.9543 | Val acc: 52.85% | LR: 0.001096
Epoch: 068 | Train loss: 0.9891 | Train acc: 50.79% | Val loss: 0.9618 | Val acc: 52.71% | LR: 0.001077
Epoch: 069 | Train loss: 0.9863 | Train acc: 50.99% | Val loss: 0.9569 | Val acc: 52.67% | LR: 0.001057
Epoch: 070 | Train loss: 0.9877 | Train acc: 50.79% | Val loss: 0.9453 | Val acc: 53.46% | LR: 0.001037
Epoch: 071 | Train loss: 0.9878 | Train acc: 50.88% | Val loss: 0.9509 | Val acc: 53.27% | LR: 0.001017
Epoch: 072 | Train loss: 0.9875 | Train acc: 51.08% | Val loss: 0.9497 | Val acc: 53.49% | LR: 0.000997
Epoch: 073 | Train loss: 0.9828 | Train acc: 51.23% | Val loss: 0.9500 | Val acc: 53.57% | LR: 0.000977
Epoch: 074 | Train loss: 0.9779 | Train acc: 51.42% | Val loss: 0.9583 | Val acc: 53.15% | LR: 0.000957
Epoch: 075 | Train loss: 0.9855 | Train acc: 51.15% | Val loss: 0.9614 | Val acc: 52.92% | LR: 0.000937
Epoch: 076 | Train loss: 0.9850 | Train acc: 50.97% | Val loss: 0.9577 | Val acc: 52.78% | LR: 0.000917
Epoch: 077 | Train loss: 0.9860 | Train acc: 51.00% | Val loss: 0.9560 | Val acc: 53.33% | LR: 0.000897
Epoch: 078 | Train loss: 0.9911 | Train acc: 50.70% | Val loss: 0.9541 | Val acc: 53.13% | LR: 0.000877
Epoch: 079 | Train loss: 0.9847 | Train acc: 51.24% | Val loss: 0.9579 | Val acc: 53.21% | LR: 0.000857
Epoch: 080 | Train loss: 0.9860 | Train acc: 51.05% | Val loss: 0.9580 | Val acc: 52.87% | LR: 0.000837
Epoch: 081 | Train loss: 0.9856 | Train acc: 50.98% | Val loss: 0.9502 | Val acc: 53.39% | LR: 0.000817
Epoch: 082 | Train loss: 0.9815 | Train acc: 51.38% | Val loss: 0.9386 | Val acc: 54.26% | LR: 0.000797
Epoch: 083 | Train loss: 0.9894 | Train acc: 50.59% | Val loss: 0.9394 | Val acc: 54.16% | LR: 0.000778
Epoch: 084 | Train loss: 0.9797 | Train acc: 51.38% | Val loss: 0.9463 | Val acc: 53.83% | LR: 0.000758
Epoch: 085 | Train loss: 0.9809 | Train acc: 51.31% | Val loss: 0.9470 | Val acc: 53.98% | LR: 0.000739
Epoch: 086 | Train loss: 0.9786 | Train acc: 51.51% | Val loss: 0.9430 | Val acc: 53.86% | LR: 0.000719
Epoch: 087 | Train loss: 0.9954 | Train acc: 50.31% | Val loss: 0.9451 | Val acc: 53.58% | LR: 0.000700
Epoch: 088 | Train loss: 0.9819 | Train acc: 51.16% | Val loss: 0.9360 | Val acc: 54.11% | LR: 0.000681
Epoch: 089 | Train loss: 0.9855 | Train acc: 50.97% | Val loss: 0.9448 | Val acc: 53.86% | LR: 0.000661
Epoch: 090 | Train loss: 0.9871 | Train acc: 50.87% | Val loss: 0.9476 | Val acc: 53.63% | LR: 0.000642
Epoch: 091 | Train loss: 0.9811 | Train acc: 51.22% | Val loss: 0.9396 | Val acc: 53.95% | LR: 0.000624
Epoch: 092 | Train loss: 0.9888 | Train acc: 50.65% | Val loss: 0.9457 | Val acc: 53.75% | LR: 0.000605
Epoch: 093 | Train loss: 0.9863 | Train acc: 50.73% | Val loss: 0.9450 | Val acc: 53.62% | LR: 0.000586
Epoch: 094 | Train loss: 0.9822 | Train acc: 51.18% | Val loss: 0.9411 | Val acc: 53.95% | LR: 0.000568
Epoch: 095 | Train loss: 0.9826 | Train acc: 51.14% | Val loss: 0.9405 | Val acc: 54.11% | LR: 0.000550
Epoch: 096 | Train loss: 0.9775 | Train acc: 51.47% | Val loss: 0.9454 | Val acc: 53.53% | LR: 0.000532
Epoch: 097 | Train loss: 0.9799 | Train acc: 51.58% | Val loss: 0.9547 | Val acc: 53.02% | LR: 0.000514
Epoch: 098 | Train loss: 0.9910 | Train acc: 50.47% | Val loss: 0.9463 | Val acc: 53.40% | LR: 0.000496
Epoch: 099 | Train loss: 0.9774 | Train acc: 51.59% | Val loss: 0.9527 | Val acc: 53.09% | LR: 0.000479
Epoch: 100 | Train loss: 0.9795 | Train acc: 51.47% | Val loss: 0.9442 | Val acc: 53.64% | LR: 0.000462
Epoch: 101 | Train loss: 0.9875 | Train acc: 50.65% | Val loss: 0.9512 | Val acc: 53.10% | LR: 0.000445
Epoch: 102 | Train loss: 0.9807 | Train acc: 51.21% | Val loss: 0.9572 | Val acc: 52.90% | LR: 0.000428
Epoch: 103 | Train loss: 0.9782 | Train acc: 51.42% | Val loss: 0.9550 | Val acc: 52.95% | LR: 0.000411
Epoch: 104 | Train loss: 0.9771 | Train acc: 51.43% | Val loss: 0.9437 | Val acc: 53.60% | LR: 0.000395
Epoch: 105 | Train loss: 0.9805 | Train acc: 51.18% | Val loss: 0.9470 | Val acc: 53.49% | LR: 0.000379
Epoch: 106 | Train loss: 0.9788 | Train acc: 51.45% | Val loss: 0.9472 | Val acc: 53.40% | LR: 0.000363
Epoch: 107 | Train loss: 0.9793 | Train acc: 51.27% | Val loss: 0.9474 | Val acc: 53.36% | LR: 0.000348
Epoch: 108 | Train loss: 0.9886 | Train acc: 50.66% | Val loss: 0.9467 | Val acc: 53.42% | LR: 0.000332
Epoch: 109 | Train loss: 0.9812 | Train acc: 51.10% | Val loss: 0.9523 | Val acc: 53.05% | LR: 0.000317
Epoch: 110 | Train loss: 0.9840 | Train acc: 51.04% | Val loss: 0.9564 | Val acc: 52.75% | LR: 0.000302
Epoch: 111 | Train loss: 0.9742 | Train acc: 51.69% | Val loss: 0.9504 | Val acc: 53.14% | LR: 0.000288
Epoch: 112 | Train loss: 0.9877 | Train acc: 50.74% | Val loss: 0.9554 | Val acc: 52.89% | LR: 0.000274
Epoch: 113 | Train loss: 0.9788 | Train acc: 51.28% | Val loss: 0.9522 | Val acc: 53.07% | LR: 0.000260
Epoch: 114 | Train loss: 0.9856 | Train acc: 50.93% | Val loss: 0.9524 | Val acc: 53.01% | LR: 0.000246
Epoch: 115 | Train loss: 0.9704 | Train acc: 51.91% | Val loss: 0.9511 | Val acc: 52.97% | LR: 0.000233
Epoch: 116 | Train loss: 0.9804 | Train acc: 51.26% | Val loss: 0.9531 | Val acc: 52.83% | LR: 0.000220
Epoch: 117 | Train loss: 0.9829 | Train acc: 51.10% | Val loss: 0.9448 | Val acc: 53.40% | LR: 0.000208
Epoch: 118 | Train loss: 0.9823 | Train acc: 51.00% | Val loss: 0.9499 | Val acc: 53.25% | LR: 0.000195
Epoch: 119 | Train loss: 0.9768 | Train acc: 51.46% | Val loss: 0.9521 | Val acc: 53.20% | LR: 0.000184
Epoch: 120 | Train loss: 0.9876 | Train acc: 50.84% | Val loss: 0.9481 | Val acc: 53.34% | LR: 0.000172
Epoch: 121 | Train loss: 0.9801 | Train acc: 51.27% | Val loss: 0.9465 | Val acc: 53.36% | LR: 0.000161
Epoch: 122 | Train loss: 0.9797 | Train acc: 51.09% | Val loss: 0.9511 | Val acc: 53.12% | LR: 0.000150
Epoch: 123 | Train loss: 0.9824 | Train acc: 50.92% | Val loss: 0.9423 | Val acc: 53.58% | LR: 0.000139
Epoch: 124 | Train loss: 0.9845 | Train acc: 50.98% | Val loss: 0.9472 | Val acc: 53.46% | LR: 0.000129
Epoch: 125 | Train loss: 0.9852 | Train acc: 50.92% | Val loss: 0.9455 | Val acc: 53.53% | LR: 0.000119
Epoch: 126 | Train loss: 0.9873 | Train acc: 50.84% | Val loss: 0.9492 | Val acc: 53.32% | LR: 0.000110
Epoch: 127 | Train loss: 0.9891 | Train acc: 50.66% | Val loss: 0.9480 | Val acc: 53.46% | LR: 0.000101
Epoch: 128 | Train loss: 0.9955 | Train acc: 50.14% | Val loss: 0.9490 | Val acc: 53.32% | LR: 0.000092
Epoch: 129 | Train loss: 0.9805 | Train acc: 51.19% | Val loss: 0.9478 | Val acc: 53.34% | LR: 0.000084
Epoch: 130 | Train loss: 0.9873 | Train acc: 50.66% | Val loss: 0.9456 | Val acc: 53.34% | LR: 0.000076
Epoch: 131 | Train loss: 0.9759 | Train acc: 51.46% | Val loss: 0.9458 | Val acc: 53.36% | LR: 0.000068
Epoch: 132 | Train loss: 0.9861 | Train acc: 50.85% | Val loss: 0.9470 | Val acc: 53.35% | LR: 0.000061
Epoch: 133 | Train loss: 0.9825 | Train acc: 51.02% | Val loss: 0.9480 | Val acc: 53.38% | LR: 0.000054
Epoch: 134 | Train loss: 0.9823 | Train acc: 51.11% | Val loss: 0.9487 | Val acc: 53.36% | LR: 0.000048
Epoch: 135 | Train loss: 0.9796 | Train acc: 51.29% | Val loss: 0.9485 | Val acc: 53.36% | LR: 0.000042
Epoch: 136 | Train loss: 0.9818 | Train acc: 51.02% | Val loss: 0.9475 | Val acc: 53.38% | LR: 0.000036
Epoch: 137 | Train loss: 0.9752 | Train acc: 51.47% | Val loss: 0.9472 | Val acc: 53.35% | LR: 0.000031
Epoch: 138 | Train loss: 0.9865 | Train acc: 50.85% | Val loss: 0.9477 | Val acc: 53.33% | LR: 0.000026
Epoch: 139 | Train loss: 0.9845 | Train acc: 50.94% | Val loss: 0.9479 | Val acc: 53.31% | LR: 0.000022
Epoch: 140 | Train loss: 0.9787 | Train acc: 51.29% | Val loss: 0.9477 | Val acc: 53.35% | LR: 0.000018
Epoch: 141 | Train loss: 0.9788 | Train acc: 51.38% | Val loss: 0.9477 | Val acc: 53.31% | LR: 0.000014
Epoch: 142 | Train loss: 0.9792 | Train acc: 51.38% | Val loss: 0.9475 | Val acc: 53.30% | LR: 0.000011
Epoch: 143 | Train loss: 0.9806 | Train acc: 51.20% | Val loss: 0.9478 | Val acc: 53.30% | LR: 0.000009
Epoch: 144 | Train loss: 0.9777 | Train acc: 51.29% | Val loss: 0.9478 | Val acc: 53.31% | LR: 0.000006
Epoch: 145 | Train loss: 0.9833 | Train acc: 50.94% | Val loss: 0.9476 | Val acc: 53.30% | LR: 0.000004
Epoch: 146 | Train loss: 0.9768 | Train acc: 51.38% | Val loss: 0.9476 | Val acc: 53.30% | LR: 0.000003
Epoch: 147 | Train loss: 0.9794 | Train acc: 51.21% | Val loss: 0.9476 | Val acc: 53.30% | LR: 0.000002
Epoch: 148 | Train loss: 0.9774 | Train acc: 51.56% | Val loss: 0.9475 | Val acc: 53.30% | LR: 0.000001
Epoch: 149 | Train loss: 0.9821 | Train acc: 51.03% | Val loss: 0.9475 | Val acc: 53.30% | LR: 0.000001

[I 2025-09-23 02:39:54,819] Trial 24 finished with value: 0.5439754009246827 and parameters: {'lr': 0.0019125305134877928, 'hidden_size': 98, 'dropout': 0.2485729134468548, 'weight_decay': 0.5702919905501668}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 0.9994 | Train acc: 50.98% | Val loss: 0.9993 | Val acc: 51.54% | LR: 0.000433
Epoch: 001 | Train loss: 0.9975 | Train acc: 50.80% | Val loss: 0.9983 | Val acc: 50.77% | LR: 0.000433
Epoch: 002 | Train loss: 0.9918 | Train acc: 50.82% | Val loss: 0.9966 | Val acc: 51.08% | LR: 0.000433
Epoch: 003 | Train loss: 0.9891 | Train acc: 51.22% | Val loss: 0.9920 | Val acc: 51.43% | LR: 0.000433
Epoch: 004 | Train loss: 0.9916 | Train acc: 50.74% | Val loss: 0.9858 | Val acc: 50.78% | LR: 0.000432
Epoch: 005 | Train loss: 0.9907 | Train acc: 50.88% | Val loss: 0.9903 | Val acc: 50.85% | LR: 0.000432
Epoch: 006 | Train loss: 0.9863 | Train acc: 50.87% | Val loss: 0.9923 | Val acc: 50.56% | LR: 0.000431
Epoch: 007 | Train loss: 0.9864 | Train acc: 50.92% | Val loss: 0.9997 | Val acc: 49.88% | LR: 0.000430
Epoch: 008 | Train loss: 0.9875 | Train acc: 50.91% | Val loss: 0.9897 | Val acc: 50.28% | LR: 0.000430
Epoch: 009 | Train loss: 0.9820 | Train acc: 51.17% | Val loss: 0.9995 | Val acc: 49.83% | LR: 0.000429
Epoch: 010 | Train loss: 0.9910 | Train acc: 50.80% | Val loss: 1.0079 | Val acc: 49.49% | LR: 0.000428
Epoch: 011 | Train loss: 0.9839 | Train acc: 51.18% | Val loss: 1.0118 | Val acc: 49.39% | LR: 0.000427
Epoch: 012 | Train loss: 0.9848 | Train acc: 50.98% | Val loss: 1.0089 | Val acc: 49.35% | LR: 0.000426
Epoch: 013 | Train loss: 0.9812 | Train acc: 51.25% | Val loss: 1.0104 | Val acc: 49.43% | LR: 0.000424
Epoch: 014 | Train loss: 0.9783 | Train acc: 51.38% | Val loss: 1.0005 | Val acc: 49.52% | LR: 0.000423
Epoch: 015 | Train loss: 0.9802 | Train acc: 51.31% | Val loss: 1.0308 | Val acc: 48.37% | LR: 0.000421
Epoch: 016 | Train loss: 0.9870 | Train acc: 50.99% | Val loss: 1.0320 | Val acc: 48.47% | LR: 0.000420
Epoch: 017 | Train loss: 0.9879 | Train acc: 50.99% | Val loss: 1.0133 | Val acc: 49.38% | LR: 0.000418
Epoch: 018 | Train loss: 0.9848 | Train acc: 51.16% | Val loss: 1.0502 | Val acc: 47.37% | LR: 0.000417
Epoch: 019 | Train loss: 0.9916 | Train acc: 50.48% | Val loss: 1.0640 | Val acc: 45.97% | LR: 0.000415
Epoch: 020 | Train loss: 0.9896 | Train acc: 50.78% | Val loss: 1.0490 | Val acc: 45.95% | LR: 0.000413
Epoch: 021 | Train loss: 0.9893 | Train acc: 50.70% | Val loss: 1.0573 | Val acc: 45.95% | LR: 0.000411
Epoch: 022 | Train loss: 0.9893 | Train acc: 50.61% | Val loss: 1.0495 | Val acc: 45.97% | LR: 0.000409
Epoch: 023 | Train loss: 0.9917 | Train acc: 50.51% | Val loss: 1.0460 | Val acc: 46.01% | LR: 0.000407
Epoch: 024 | Train loss: 0.9925 | Train acc: 50.37% | Val loss: 1.0504 | Val acc: 45.95% | LR: 0.000405
Epoch: 025 | Train loss: 0.9898 | Train acc: 50.55% | Val loss: 1.0467 | Val acc: 45.66% | LR: 0.000402
Epoch: 026 | Train loss: 0.9864 | Train acc: 50.75% | Val loss: 1.0402 | Val acc: 46.07% | LR: 0.000400
Epoch: 027 | Train loss: 0.9927 | Train acc: 50.21% | Val loss: 1.0401 | Val acc: 46.01% | LR: 0.000397
Epoch: 028 | Train loss: 0.9935 | Train acc: 50.45% | Val loss: 1.0330 | Val acc: 46.83% | LR: 0.000395
Epoch: 029 | Train loss: 0.9880 | Train acc: 51.04% | Val loss: 1.0300 | Val acc: 47.15% | LR: 0.000392
Epoch: 030 | Train loss: 0.9861 | Train acc: 51.07% | Val loss: 1.0229 | Val acc: 47.60% | LR: 0.000390
Epoch: 031 | Train loss: 0.9976 | Train acc: 50.71% | Val loss: 1.0209 | Val acc: 47.46% | LR: 0.000387
Epoch: 032 | Train loss: 0.9847 | Train acc: 51.09% | Val loss: 1.0072 | Val acc: 49.10% | LR: 0.000384
Epoch: 033 | Train loss: 0.9872 | Train acc: 50.79% | Val loss: 1.0100 | Val acc: 48.93% | LR: 0.000381
Epoch: 034 | Train loss: 0.9842 | Train acc: 51.20% | Val loss: 1.0121 | Val acc: 48.63% | LR: 0.000378
Epoch: 035 | Train loss: 0.9884 | Train acc: 50.73% | Val loss: 1.0181 | Val acc: 48.11% | LR: 0.000375
Epoch: 036 | Train loss: 0.9825 | Train acc: 51.15% | Val loss: 1.0171 | Val acc: 48.57% | LR: 0.000372
Epoch: 037 | Train loss: 0.9840 | Train acc: 50.98% | Val loss: 1.0188 | Val acc: 48.63% | LR: 0.000369
Epoch: 038 | Train loss: 0.9897 | Train acc: 50.54% | Val loss: 1.0212 | Val acc: 48.47% | LR: 0.000365
Epoch: 039 | Train loss: 0.9886 | Train acc: 50.63% | Val loss: 1.0201 | Val acc: 48.49% | LR: 0.000362
Epoch: 040 | Train loss: 0.9915 | Train acc: 50.36% | Val loss: 1.0262 | Val acc: 48.16% | LR: 0.000359
Epoch: 041 | Train loss: 0.9807 | Train acc: 51.32% | Val loss: 1.0225 | Val acc: 48.55% | LR: 0.000355
Epoch: 042 | Train loss: 0.9873 | Train acc: 50.74% | Val loss: 1.0208 | Val acc: 48.49% | LR: 0.000352
Epoch: 043 | Train loss: 0.9836 | Train acc: 50.95% | Val loss: 1.0219 | Val acc: 48.55% | LR: 0.000348
Epoch: 044 | Train loss: 0.9811 | Train acc: 51.11% | Val loss: 1.0212 | Val acc: 48.53% | LR: 0.000344
Epoch: 045 | Train loss: 0.9846 | Train acc: 51.03% | Val loss: 1.0242 | Val acc: 48.31% | LR: 0.000341
Epoch: 046 | Train loss: 0.9824 | Train acc: 51.07% | Val loss: 1.0286 | Val acc: 48.14% | LR: 0.000337
Epoch: 047 | Train loss: 0.9818 | Train acc: 51.38% | Val loss: 1.0192 | Val acc: 48.73% | LR: 0.000333
Epoch: 048 | Train loss: 0.9762 | Train acc: 51.41% | Val loss: 1.0180 | Val acc: 48.87% | LR: 0.000329
Epoch: 049 | Train loss: 0.9841 | Train acc: 50.95% | Val loss: 1.0253 | Val acc: 48.59% | LR: 0.000325
Epoch: 050 | Train loss: 0.9798 | Train acc: 51.32% | Val loss: 1.0255 | Val acc: 48.28% | LR: 0.000321
Epoch: 051 | Train loss: 0.9819 | Train acc: 51.27% | Val loss: 1.0195 | Val acc: 48.70% | LR: 0.000317
Epoch: 052 | Train loss: 0.9832 | Train acc: 51.08% | Val loss: 1.0164 | Val acc: 48.77% | LR: 0.000313
Epoch: 053 | Train loss: 0.9827 | Train acc: 51.11% | Val loss: 1.0190 | Val acc: 48.71% | LR: 0.000309
Epoch: 054 | Train loss: 0.9852 | Train acc: 50.87% | Val loss: 1.0161 | Val acc: 48.91% | LR: 0.000305
Epoch: 055 | Train loss: 0.9799 | Train acc: 51.27% | Val loss: 1.0284 | Val acc: 48.14% | LR: 0.000301
Epoch: 056 | Train loss: 0.9857 | Train acc: 50.83% | Val loss: 1.0325 | Val acc: 47.97% | LR: 0.000297
Epoch: 057 | Train loss: 0.9823 | Train acc: 51.18% | Val loss: 1.0180 | Val acc: 48.84% | LR: 0.000293
Epoch: 058 | Train loss: 0.9842 | Train acc: 51.00% | Val loss: 1.0198 | Val acc: 48.71% | LR: 0.000288
Epoch: 059 | Train loss: 0.9837 | Train acc: 51.01% | Val loss: 1.0222 | Val acc: 48.65% | LR: 0.000284
Epoch: 060 | Train loss: 0.9844 | Train acc: 51.05% | Val loss: 1.0173 | Val acc: 48.82% | LR: 0.000280
Epoch: 061 | Train loss: 0.9766 | Train acc: 51.47% | Val loss: 1.0244 | Val acc: 48.69% | LR: 0.000275
Epoch: 062 | Train loss: 0.9787 | Train acc: 51.30% | Val loss: 1.0115 | Val acc: 49.21% | LR: 0.000271
Epoch: 063 | Train loss: 0.9858 | Train acc: 50.89% | Val loss: 1.0194 | Val acc: 48.78% | LR: 0.000267
Epoch: 064 | Train loss: 0.9805 | Train acc: 51.18% | Val loss: 1.0145 | Val acc: 49.05% | LR: 0.000262
Epoch: 065 | Train loss: 0.9813 | Train acc: 51.12% | Val loss: 1.0130 | Val acc: 49.15% | LR: 0.000258
Epoch: 066 | Train loss: 0.9817 | Train acc: 51.03% | Val loss: 1.0312 | Val acc: 48.15% | LR: 0.000253
Epoch: 067 | Train loss: 0.9802 | Train acc: 51.06% | Val loss: 1.0326 | Val acc: 48.08% | LR: 0.000249
Epoch: 068 | Train loss: 0.9842 | Train acc: 50.97% | Val loss: 1.0255 | Val acc: 48.44% | LR: 0.000244
Epoch: 069 | Train loss: 0.9803 | Train acc: 51.13% | Val loss: 1.0233 | Val acc: 48.69% | LR: 0.000240
Epoch: 070 | Train loss: 0.9836 | Train acc: 51.00% | Val loss: 1.0151 | Val acc: 49.01% | LR: 0.000235
Epoch: 071 | Train loss: 0.9833 | Train acc: 50.98% | Val loss: 1.0238 | Val acc: 48.43% | LR: 0.000231
Epoch: 072 | Train loss: 0.9798 | Train acc: 51.23% | Val loss: 1.0237 | Val acc: 48.57% | LR: 0.000226
Epoch: 073 | Train loss: 0.9710 | Train acc: 51.86% | Val loss: 1.0223 | Val acc: 48.57% | LR: 0.000222
Epoch: 074 | Train loss: 0.9807 | Train acc: 51.14% | Val loss: 1.0191 | Val acc: 48.67% | LR: 0.000217
Epoch: 075 | Train loss: 0.9736 | Train acc: 51.75% | Val loss: 1.0210 | Val acc: 48.67% | LR: 0.000213
Epoch: 076 | Train loss: 0.9854 | Train acc: 50.84% | Val loss: 1.0236 | Val acc: 48.47% | LR: 0.000208
Epoch: 077 | Train loss: 0.9873 | Train acc: 50.80% | Val loss: 1.0258 | Val acc: 48.39% | LR: 0.000204
Epoch: 078 | Train loss: 0.9842 | Train acc: 50.97% | Val loss: 1.0265 | Val acc: 48.29% | LR: 0.000199
Epoch: 079 | Train loss: 0.9827 | Train acc: 50.96% | Val loss: 1.0258 | Val acc: 48.29% | LR: 0.000195
Epoch: 080 | Train loss: 0.9774 | Train acc: 51.34% | Val loss: 1.0239 | Val acc: 48.51% | LR: 0.000190
Epoch: 081 | Train loss: 0.9821 | Train acc: 51.07% | Val loss: 1.0234 | Val acc: 48.53% | LR: 0.000186
Epoch: 082 | Train loss: 0.9760 | Train acc: 51.54% | Val loss: 1.0255 | Val acc: 48.34% | LR: 0.000181
Epoch: 083 | Train loss: 0.9744 | Train acc: 51.54% | Val loss: 1.0236 | Val acc: 48.39% | LR: 0.000177
Epoch: 084 | Train loss: 0.9821 | Train acc: 50.92% | Val loss: 1.0245 | Val acc: 48.45% | LR: 0.000172
Epoch: 085 | Train loss: 0.9804 | Train acc: 51.17% | Val loss: 1.0243 | Val acc: 48.59% | LR: 0.000168
Epoch: 086 | Train loss: 0.9904 | Train acc: 50.53% | Val loss: 1.0227 | Val acc: 48.49% | LR: 0.000163
Epoch: 087 | Train loss: 0.9750 | Train acc: 51.43% | Val loss: 1.0245 | Val acc: 48.29% | LR: 0.000159
Epoch: 088 | Train loss: 0.9920 | Train acc: 50.39% | Val loss: 1.0230 | Val acc: 48.49% | LR: 0.000155
Epoch: 089 | Train loss: 0.9842 | Train acc: 50.91% | Val loss: 1.0262 | Val acc: 48.37% | LR: 0.000150
Epoch: 090 | Train loss: 0.9859 | Train acc: 50.71% | Val loss: 1.0233 | Val acc: 48.45% | LR: 0.000146
Epoch: 091 | Train loss: 0.9843 | Train acc: 50.94% | Val loss: 1.0202 | Val acc: 48.71% | LR: 0.000142
Epoch: 092 | Train loss: 0.9841 | Train acc: 50.87% | Val loss: 1.0262 | Val acc: 48.25% | LR: 0.000138
Epoch: 093 | Train loss: 0.9812 | Train acc: 50.99% | Val loss: 1.0258 | Val acc: 48.41% | LR: 0.000133
Epoch: 094 | Train loss: 0.9861 | Train acc: 50.76% | Val loss: 1.0262 | Val acc: 48.33% | LR: 0.000129
Epoch: 095 | Train loss: 0.9797 | Train acc: 51.36% | Val loss: 1.0242 | Val acc: 48.53% | LR: 0.000125
Epoch: 096 | Train loss: 0.9751 | Train acc: 51.54% | Val loss: 1.0264 | Val acc: 48.34% | LR: 0.000121
Epoch: 097 | Train loss: 0.9817 | Train acc: 50.95% | Val loss: 1.0263 | Val acc: 48.35% | LR: 0.000117
Epoch: 098 | Train loss: 0.9797 | Train acc: 51.12% | Val loss: 1.0282 | Val acc: 48.30% | LR: 0.000113
Epoch: 099 | Train loss: 0.9722 | Train acc: 51.62% | Val loss: 1.0226 | Val acc: 48.75% | LR: 0.000109
Epoch: 100 | Train loss: 0.9846 | Train acc: 50.87% | Val loss: 1.0225 | Val acc: 48.55% | LR: 0.000105
Epoch: 101 | Train loss: 0.9768 | Train acc: 51.38% | Val loss: 1.0251 | Val acc: 48.37% | LR: 0.000101
Epoch: 102 | Train loss: 0.9838 | Train acc: 50.92% | Val loss: 1.0261 | Val acc: 48.30% | LR: 0.000098
Epoch: 103 | Train loss: 0.9823 | Train acc: 51.02% | Val loss: 1.0228 | Val acc: 48.43% | LR: 0.000094
Epoch: 104 | Train loss: 0.9752 | Train acc: 51.39% | Val loss: 1.0259 | Val acc: 48.46% | LR: 0.000090
Epoch: 105 | Train loss: 0.9725 | Train acc: 51.56% | Val loss: 1.0244 | Val acc: 48.56% | LR: 0.000087
Epoch: 106 | Train loss: 0.9672 | Train acc: 52.01% | Val loss: 1.0251 | Val acc: 48.49% | LR: 0.000083
Epoch: 107 | Train loss: 0.9791 | Train acc: 51.30% | Val loss: 1.0239 | Val acc: 48.52% | LR: 0.000079
Epoch: 108 | Train loss: 0.9818 | Train acc: 51.12% | Val loss: 1.0268 | Val acc: 48.54% | LR: 0.000076
Epoch: 109 | Train loss: 0.9798 | Train acc: 51.12% | Val loss: 1.0255 | Val acc: 48.46% | LR: 0.000073
Epoch: 110 | Train loss: 0.9858 | Train acc: 50.78% | Val loss: 1.0250 | Val acc: 48.54% | LR: 0.000069
Epoch: 111 | Train loss: 0.9841 | Train acc: 50.88% | Val loss: 1.0247 | Val acc: 48.50% | LR: 0.000066
Epoch: 112 | Train loss: 0.9789 | Train acc: 51.22% | Val loss: 1.0256 | Val acc: 48.56% | LR: 0.000063
Epoch: 113 | Train loss: 0.9765 | Train acc: 51.33% | Val loss: 1.0237 | Val acc: 48.56% | LR: 0.000060
Epoch: 114 | Train loss: 0.9751 | Train acc: 51.40% | Val loss: 1.0265 | Val acc: 48.46% | LR: 0.000057
Epoch: 115 | Train loss: 0.9836 | Train acc: 50.96% | Val loss: 1.0271 | Val acc: 48.64% | LR: 0.000054
Epoch: 116 | Train loss: 0.9727 | Train acc: 51.60% | Val loss: 1.0244 | Val acc: 48.68% | LR: 0.000051
Epoch: 117 | Train loss: 0.9797 | Train acc: 51.13% | Val loss: 1.0260 | Val acc: 48.59% | LR: 0.000048
Epoch: 118 | Train loss: 0.9787 | Train acc: 51.15% | Val loss: 1.0255 | Val acc: 48.58% | LR: 0.000045
Epoch: 119 | Train loss: 0.9681 | Train acc: 51.85% | Val loss: 1.0250 | Val acc: 48.64% | LR: 0.000042
Epoch: 120 | Train loss: 0.9771 | Train acc: 51.32% | Val loss: 1.0244 | Val acc: 48.56% | LR: 0.000040
Epoch: 121 | Train loss: 0.9822 | Train acc: 51.07% | Val loss: 1.0241 | Val acc: 48.72% | LR: 0.000037
Epoch: 122 | Train loss: 0.9796 | Train acc: 51.15% | Val loss: 1.0246 | Val acc: 48.76% | LR: 0.000035
Epoch: 123 | Train loss: 0.9758 | Train acc: 51.51% | Val loss: 1.0245 | Val acc: 48.68% | LR: 0.000032
Epoch: 124 | Train loss: 0.9797 | Train acc: 51.15% | Val loss: 1.0247 | Val acc: 48.62% | LR: 0.000030
Epoch: 125 | Train loss: 0.9758 | Train acc: 51.41% | Val loss: 1.0247 | Val acc: 48.62% | LR: 0.000028
Epoch: 126 | Train loss: 0.9782 | Train acc: 51.24% | Val loss: 1.0242 | Val acc: 48.74% | LR: 0.000026
Epoch: 127 | Train loss: 0.9786 | Train acc: 51.24% | Val loss: 1.0249 | Val acc: 48.72% | LR: 0.000024
Epoch: 128 | Train loss: 0.9753 | Train acc: 51.42% | Val loss: 1.0249 | Val acc: 48.76% | LR: 0.000022
Epoch: 129 | Train loss: 0.9784 | Train acc: 51.24% | Val loss: 1.0245 | Val acc: 48.70% | LR: 0.000020
Epoch: 130 | Train loss: 0.9737 | Train acc: 51.59% | Val loss: 1.0241 | Val acc: 48.70% | LR: 0.000018
Epoch: 131 | Train loss: 0.9825 | Train acc: 50.98% | Val loss: 1.0242 | Val acc: 48.60% | LR: 0.000016
Epoch: 132 | Train loss: 0.9778 | Train acc: 51.33% | Val loss: 1.0237 | Val acc: 48.74% | LR: 0.000015
Epoch: 133 | Train loss: 0.9788 | Train acc: 51.24% | Val loss: 1.0240 | Val acc: 48.74% | LR: 0.000013
Epoch: 134 | Train loss: 0.9764 | Train acc: 51.42% | Val loss: 1.0243 | Val acc: 48.60% | LR: 0.000012
Epoch: 135 | Train loss: 0.9802 | Train acc: 51.24% | Val loss: 1.0242 | Val acc: 48.76% | LR: 0.000010
Epoch: 136 | Train loss: 0.9745 | Train acc: 51.42% | Val loss: 1.0240 | Val acc: 48.76% | LR: 0.000009
Epoch: 137 | Train loss: 0.9718 | Train acc: 51.60% | Val loss: 1.0243 | Val acc: 48.74% | LR: 0.000008
Epoch: 138 | Train loss: 0.9709 | Train acc: 51.69% | Val loss: 1.0244 | Val acc: 48.78% | LR: 0.000007
Epoch: 139 | Train loss: 0.9813 | Train acc: 50.98% | Val loss: 1.0244 | Val acc: 48.76% | LR: 0.000006
Epoch: 140 | Train loss: 0.9800 | Train acc: 51.16% | Val loss: 1.0244 | Val acc: 48.76% | LR: 0.000005
Epoch: 141 | Train loss: 0.9753 | Train acc: 51.34% | Val loss: 1.0245 | Val acc: 48.68% | LR: 0.000004
Epoch: 142 | Train loss: 0.9831 | Train acc: 50.98% | Val loss: 1.0245 | Val acc: 48.68% | LR: 0.000003
Epoch: 143 | Train loss: 0.9867 | Train acc: 50.63% | Val loss: 1.0245 | Val acc: 48.74% | LR: 0.000003
Epoch: 144 | Train loss: 0.9756 | Train acc: 51.51% | Val loss: 1.0245 | Val acc: 48.72% | LR: 0.000002
Epoch: 145 | Train loss: 0.9780 | Train acc: 51.24% | Val loss: 1.0244 | Val acc: 48.74% | LR: 0.000002
Epoch: 146 | Train loss: 0.9696 | Train acc: 51.87% | Val loss: 1.0245 | Val acc: 48.78% | LR: 0.000001
Epoch: 147 | Train loss: 0.9777 | Train acc: 51.24% | Val loss: 1.0244 | Val acc: 48.74% | LR: 0.000001
Epoch: 148 | Train loss: 0.9810 | Train acc: 51.07% | Val loss: 1.0244 | Val acc: 48.78% | LR: 0.000001
Epoch: 149 | Train loss: 0.9796 | Train acc: 51.16% | Val loss: 1.0244 | Val acc: 48.74% | LR: 0.000001

[I 2025-09-23 02:43:02,544] Trial 25 finished with value: 0.5153735995292663 and parameters: {'lr': 0.00043350696262212796, 'hidden_size': 140, 'dropout': 0.3418456368214172, 'weight_decay': 0.3904668460872028}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.0081 | Train acc: 50.79% | Val loss: 1.2422 | Val acc: 48.11% | LR: 0.009900
Epoch: 001 | Train loss: 1.0054 | Train acc: 50.30% | Val loss: 0.9511 | Val acc: 53.65% | LR: 0.009896
Epoch: 002 | Train loss: 1.0102 | Train acc: 49.57% | Val loss: 0.9740 | Val acc: 52.69% | LR: 0.009891
Epoch: 003 | Train loss: 0.9962 | Train acc: 50.74% | Val loss: 0.9967 | Val acc: 51.47% | LR: 0.009883
Epoch: 004 | Train loss: 0.9984 | Train acc: 50.45% | Val loss: 0.9741 | Val acc: 52.25% | LR: 0.009874
Epoch: 005 | Train loss: 1.0081 | Train acc: 49.32% | Val loss: 0.9896 | Val acc: 51.98% | LR: 0.009862
Epoch: 006 | Train loss: 0.9971 | Train acc: 50.26% | Val loss: 1.0319 | Val acc: 47.43% | LR: 0.009848
Epoch: 007 | Train loss: 0.9937 | Train acc: 50.31% | Val loss: 1.0039 | Val acc: 50.53% | LR: 0.009831
Epoch: 008 | Train loss: 1.0034 | Train acc: 49.86% | Val loss: 1.0256 | Val acc: 45.95% | LR: 0.009813
Epoch: 009 | Train loss: 0.9923 | Train acc: 50.87% | Val loss: 0.9934 | Val acc: 50.82% | LR: 0.009793
Epoch: 010 | Train loss: 0.9884 | Train acc: 51.81% | Val loss: 0.9788 | Val acc: 51.37% | LR: 0.009770
Epoch: 011 | Train loss: 1.0035 | Train acc: 49.87% | Val loss: 0.9903 | Val acc: 50.93% | LR: 0.009745
Epoch: 012 | Train loss: 0.9903 | Train acc: 50.47% | Val loss: 0.9636 | Val acc: 51.78% | LR: 0.009718
Epoch: 013 | Train loss: 0.9922 | Train acc: 50.85% | Val loss: 0.9749 | Val acc: 51.25% | LR: 0.009690
Epoch: 014 | Train loss: 0.9857 | Train acc: 51.26% | Val loss: 0.9705 | Val acc: 52.02% | LR: 0.009659
Epoch: 015 | Train loss: 0.9934 | Train acc: 50.44% | Val loss: 1.0794 | Val acc: 45.95% | LR: 0.009625
Epoch: 016 | Train loss: 1.0001 | Train acc: 50.09% | Val loss: 0.9832 | Val acc: 53.28% | LR: 0.009590
Epoch: 017 | Train loss: 0.9985 | Train acc: 50.24% | Val loss: 1.0507 | Val acc: 45.95% | LR: 0.009553
Epoch: 018 | Train loss: 1.0010 | Train acc: 49.83% | Val loss: 1.0052 | Val acc: 50.17% | LR: 0.009514
Epoch: 019 | Train loss: 0.9853 | Train acc: 51.22% | Val loss: 0.9641 | Val acc: 52.06% | LR: 0.009473
Epoch: 020 | Train loss: 1.0160 | Train acc: 50.14% | Val loss: 1.0545 | Val acc: 49.04% | LR: 0.009430
Epoch: 021 | Train loss: 1.0382 | Train acc: 50.44% | Val loss: 1.0790 | Val acc: 45.95% | LR: 0.009385
Epoch: 022 | Train loss: 1.0026 | Train acc: 49.62% | Val loss: 1.0531 | Val acc: 45.95% | LR: 0.009338
Epoch: 023 | Train loss: 1.0345 | Train acc: 49.41% | Val loss: 1.0145 | Val acc: 45.95% | LR: 0.009289
Epoch: 024 | Train loss: 1.0166 | Train acc: 50.26% | Val loss: 0.9434 | Val acc: 53.48% | LR: 0.009238
Epoch: 025 | Train loss: 1.0019 | Train acc: 50.54% | Val loss: 0.9799 | Val acc: 51.63% | LR: 0.009185
Epoch: 026 | Train loss: 0.9978 | Train acc: 50.20% | Val loss: 0.9646 | Val acc: 54.03% | LR: 0.009130
Epoch: 027 | Train loss: 0.9947 | Train acc: 50.10% | Val loss: 0.9493 | Val acc: 54.03% | LR: 0.009074
Epoch: 028 | Train loss: 0.9960 | Train acc: 50.34% | Val loss: 1.0276 | Val acc: 48.09% | LR: 0.009016
Epoch: 029 | Train loss: 0.9962 | Train acc: 50.83% | Val loss: 0.9607 | Val acc: 52.47% | LR: 0.008955
Epoch: 030 | Train loss: 0.9853 | Train acc: 51.15% | Val loss: 0.9995 | Val acc: 51.81% | LR: 0.008894
Epoch: 031 | Train loss: 0.9924 | Train acc: 50.58% | Val loss: 1.0894 | Val acc: 51.78% | LR: 0.008830
Epoch: 032 | Train loss: 0.9965 | Train acc: 50.30% | Val loss: 0.9630 | Val acc: 52.99% | LR: 0.008765
Epoch: 033 | Train loss: 1.0118 | Train acc: 50.35% | Val loss: 0.9814 | Val acc: 52.07% | LR: 0.008698
Epoch: 034 | Train loss: 1.0040 | Train acc: 50.03% | Val loss: 0.9768 | Val acc: 51.91% | LR: 0.008629
Epoch: 035 | Train loss: 0.9935 | Train acc: 50.45% | Val loss: 0.9767 | Val acc: 52.62% | LR: 0.008559
Epoch: 036 | Train loss: 0.9957 | Train acc: 50.11% | Val loss: 0.9769 | Val acc: 52.59% | LR: 0.008487
Epoch: 037 | Train loss: 0.9893 | Train acc: 50.84% | Val loss: 0.9691 | Val acc: 52.25% | LR: 0.008414
Epoch: 038 | Train loss: 0.9924 | Train acc: 50.66% | Val loss: 0.9773 | Val acc: 50.32% | LR: 0.008339
Epoch: 039 | Train loss: 0.9999 | Train acc: 49.72% | Val loss: 0.9820 | Val acc: 50.61% | LR: 0.008263
Epoch: 040 | Train loss: 0.9838 | Train acc: 51.07% | Val loss: 0.9721 | Val acc: 52.14% | LR: 0.008185
Epoch: 041 | Train loss: 0.9894 | Train acc: 50.75% | Val loss: 0.9638 | Val acc: 51.90% | LR: 0.008106
Epoch: 042 | Train loss: 0.9892 | Train acc: 51.05% | Val loss: 0.9687 | Val acc: 51.65% | LR: 0.008026
Epoch: 043 | Train loss: 0.9890 | Train acc: 51.01% | Val loss: 1.0483 | Val acc: 47.71% | LR: 0.007944
Epoch: 044 | Train loss: 0.9988 | Train acc: 49.99% | Val loss: 1.0431 | Val acc: 46.61% | LR: 0.007860
Epoch: 045 | Train loss: 0.9971 | Train acc: 50.57% | Val loss: 0.9696 | Val acc: 52.26% | LR: 0.007776
Epoch: 046 | Train loss: 0.9912 | Train acc: 50.26% | Val loss: 1.0132 | Val acc: 46.27% | LR: 0.007690
Epoch: 047 | Train loss: 1.0027 | Train acc: 50.01% | Val loss: 0.9699 | Val acc: 51.38% | LR: 0.007603
Epoch: 048 | Train loss: 0.9907 | Train acc: 50.91% | Val loss: 1.0095 | Val acc: 50.20% | LR: 0.007515
Epoch: 049 | Train loss: 0.9887 | Train acc: 51.02% | Val loss: 0.9768 | Val acc: 50.83% | LR: 0.007426
Epoch: 050 | Train loss: 0.9943 | Train acc: 50.57% | Val loss: 0.9661 | Val acc: 51.35% | LR: 0.007336
Epoch: 051 | Train loss: 0.9835 | Train acc: 51.34% | Val loss: 0.9796 | Val acc: 50.91% | LR: 0.007244
Epoch: 052 | Train loss: 0.9918 | Train acc: 50.53% | Val loss: 1.0009 | Val acc: 50.41% | LR: 0.007152
Epoch: 053 | Train loss: 0.9960 | Train acc: 50.94% | Val loss: 0.9780 | Val acc: 50.98% | LR: 0.007058
Epoch: 054 | Train loss: 0.9869 | Train acc: 50.95% | Val loss: 1.0089 | Val acc: 50.03% | LR: 0.006964
Epoch: 055 | Train loss: 0.9999 | Train acc: 50.41% | Val loss: 0.9843 | Val acc: 50.49% | LR: 0.006869
Epoch: 056 | Train loss: 0.9930 | Train acc: 50.29% | Val loss: 0.9886 | Val acc: 50.70% | LR: 0.006773
Epoch: 057 | Train loss: 1.0010 | Train acc: 50.30% | Val loss: 1.0230 | Val acc: 49.03% | LR: 0.006676
Epoch: 058 | Train loss: 1.0098 | Train acc: 50.17% | Val loss: 1.0080 | Val acc: 48.07% | LR: 0.006579
Epoch: 059 | Train loss: 0.9980 | Train acc: 50.43% | Val loss: 0.9614 | Val acc: 53.91% | LR: 0.006481
Epoch: 060 | Train loss: 0.9981 | Train acc: 50.60% | Val loss: 1.0007 | Val acc: 50.21% | LR: 0.006382
Epoch: 061 | Train loss: 0.9956 | Train acc: 50.54% | Val loss: 1.0011 | Val acc: 50.01% | LR: 0.006282
Epoch: 062 | Train loss: 0.9910 | Train acc: 50.84% | Val loss: 0.9665 | Val acc: 54.30% | LR: 0.006182
Epoch: 063 | Train loss: 0.9924 | Train acc: 50.52% | Val loss: 1.0104 | Val acc: 49.48% | LR: 0.006081
Epoch: 064 | Train loss: 1.0255 | Train acc: 50.21% | Val loss: 0.9369 | Val acc: 54.54% | LR: 0.005980
Epoch: 065 | Train loss: 0.9969 | Train acc: 50.51% | Val loss: 0.9605 | Val acc: 54.11% | LR: 0.005878
Epoch: 066 | Train loss: 1.0017 | Train acc: 50.28% | Val loss: 0.9625 | Val acc: 53.06% | LR: 0.005776
Epoch: 067 | Train loss: 0.9893 | Train acc: 51.04% | Val loss: 0.9973 | Val acc: 51.40% | LR: 0.005674
Epoch: 068 | Train loss: 0.9841 | Train acc: 51.13% | Val loss: 0.9978 | Val acc: 50.54% | LR: 0.005571
Epoch: 069 | Train loss: 0.9846 | Train acc: 51.21% | Val loss: 1.0304 | Val acc: 48.18% | LR: 0.005468
Epoch: 070 | Train loss: 0.9867 | Train acc: 50.72% | Val loss: 0.9360 | Val acc: 54.33% | LR: 0.005365
Epoch: 071 | Train loss: 0.9820 | Train acc: 51.00% | Val loss: 0.9492 | Val acc: 53.03% | LR: 0.005262
Epoch: 072 | Train loss: 0.9830 | Train acc: 51.12% | Val loss: 0.9894 | Val acc: 50.86% | LR: 0.005158
Epoch: 073 | Train loss: 0.9812 | Train acc: 51.16% | Val loss: 0.9995 | Val acc: 49.95% | LR: 0.005055
Epoch: 074 | Train loss: 0.9791 | Train acc: 51.47% | Val loss: 0.9995 | Val acc: 50.43% | LR: 0.004951
Epoch: 075 | Train loss: 0.9833 | Train acc: 51.18% | Val loss: 1.0000 | Val acc: 50.45% | LR: 0.004847
Epoch: 076 | Train loss: 0.9806 | Train acc: 51.32% | Val loss: 1.0021 | Val acc: 50.45% | LR: 0.004744
Epoch: 077 | Train loss: 0.9864 | Train acc: 51.20% | Val loss: 1.0430 | Val acc: 47.64% | LR: 0.004640
Epoch: 078 | Train loss: 1.0171 | Train acc: 50.66% | Val loss: 1.0604 | Val acc: 47.50% | LR: 0.004537
Epoch: 079 | Train loss: 1.0191 | Train acc: 50.78% | Val loss: 0.9897 | Val acc: 50.65% | LR: 0.004433
Epoch: 080 | Train loss: 0.9869 | Train acc: 51.14% | Val loss: 1.0077 | Val acc: 49.88% | LR: 0.004331
Epoch: 081 | Train loss: 0.9827 | Train acc: 51.30% | Val loss: 1.0039 | Val acc: 50.00% | LR: 0.004228
Epoch: 082 | Train loss: 0.9865 | Train acc: 50.50% | Val loss: 0.9970 | Val acc: 49.89% | LR: 0.004125
Epoch: 083 | Train loss: 0.9913 | Train acc: 50.46% | Val loss: 1.0112 | Val acc: 49.15% | LR: 0.004023
Epoch: 084 | Train loss: 0.9927 | Train acc: 50.87% | Val loss: 0.9937 | Val acc: 49.62% | LR: 0.003922
Epoch: 085 | Train loss: 0.9961 | Train acc: 50.13% | Val loss: 1.0295 | Val acc: 48.91% | LR: 0.003821
Epoch: 086 | Train loss: 0.9898 | Train acc: 50.73% | Val loss: 1.0106 | Val acc: 48.89% | LR: 0.003720
Epoch: 087 | Train loss: 0.9820 | Train acc: 50.91% | Val loss: 1.0196 | Val acc: 48.92% | LR: 0.003620
Epoch: 088 | Train loss: 0.9895 | Train acc: 50.38% | Val loss: 1.0136 | Val acc: 49.08% | LR: 0.003520
Epoch: 089 | Train loss: 0.9929 | Train acc: 50.81% | Val loss: 1.0207 | Val acc: 49.02% | LR: 0.003421
Epoch: 090 | Train loss: 0.9841 | Train acc: 51.10% | Val loss: 1.0136 | Val acc: 49.10% | LR: 0.003323
Epoch: 091 | Train loss: 0.9869 | Train acc: 50.69% | Val loss: 1.0233 | Val acc: 48.42% | LR: 0.003226
Epoch: 092 | Train loss: 0.9824 | Train acc: 51.34% | Val loss: 1.0210 | Val acc: 48.45% | LR: 0.003129
Epoch: 093 | Train loss: 0.9830 | Train acc: 51.09% | Val loss: 1.0221 | Val acc: 48.47% | LR: 0.003033
Epoch: 094 | Train loss: 0.9828 | Train acc: 51.26% | Val loss: 1.0199 | Val acc: 48.53% | LR: 0.002938
Epoch: 095 | Train loss: 0.9801 | Train acc: 51.36% | Val loss: 1.0253 | Val acc: 48.72% | LR: 0.002843
Epoch: 096 | Train loss: 0.9851 | Train acc: 50.99% | Val loss: 1.0160 | Val acc: 48.68% | LR: 0.002750
Epoch: 097 | Train loss: 0.9823 | Train acc: 51.08% | Val loss: 1.0200 | Val acc: 48.53% | LR: 0.002658
Epoch: 098 | Train loss: 0.9868 | Train acc: 50.79% | Val loss: 1.0235 | Val acc: 48.49% | LR: 0.002566
Epoch: 099 | Train loss: 0.9821 | Train acc: 51.16% | Val loss: 1.0173 | Val acc: 48.59% | LR: 0.002476
Epoch: 100 | Train loss: 0.9864 | Train acc: 50.91% | Val loss: 1.0222 | Val acc: 48.47% | LR: 0.002387
Epoch: 101 | Train loss: 0.9844 | Train acc: 50.98% | Val loss: 1.0273 | Val acc: 48.88% | LR: 0.002299
Epoch: 102 | Train loss: 0.9845 | Train acc: 50.91% | Val loss: 1.0127 | Val acc: 48.92% | LR: 0.002212
Epoch: 103 | Train loss: 0.9857 | Train acc: 50.73% | Val loss: 1.0211 | Val acc: 48.61% | LR: 0.002126
Epoch: 104 | Train loss: 0.9770 | Train acc: 51.44% | Val loss: 1.0174 | Val acc: 48.80% | LR: 0.002041
Epoch: 105 | Train loss: 0.9739 | Train acc: 51.53% | Val loss: 1.0194 | Val acc: 48.82% | LR: 0.001958
Epoch: 106 | Train loss: 0.9787 | Train acc: 51.27% | Val loss: 1.0234 | Val acc: 48.88% | LR: 0.001876
Epoch: 107 | Train loss: 0.9804 | Train acc: 51.27% | Val loss: 1.0174 | Val acc: 48.96% | LR: 0.001796
Epoch: 108 | Train loss: 0.9804 | Train acc: 51.18% | Val loss: 1.0078 | Val acc: 49.57% | LR: 0.001717
Epoch: 109 | Train loss: 0.9831 | Train acc: 50.91% | Val loss: 1.0029 | Val acc: 49.62% | LR: 0.001639
Epoch: 110 | Train loss: 0.9818 | Train acc: 51.28% | Val loss: 1.0114 | Val acc: 49.49% | LR: 0.001562
Epoch: 111 | Train loss: 0.9840 | Train acc: 50.95% | Val loss: 1.0003 | Val acc: 49.78% | LR: 0.001488
Epoch: 112 | Train loss: 0.9748 | Train acc: 51.51% | Val loss: 0.9869 | Val acc: 50.62% | LR: 0.001414
Epoch: 113 | Train loss: 0.9835 | Train acc: 50.91% | Val loss: 0.9637 | Val acc: 51.76% | LR: 0.001343
Epoch: 114 | Train loss: 0.9859 | Train acc: 50.84% | Val loss: 0.9464 | Val acc: 52.82% | LR: 0.001272
Epoch: 115 | Train loss: 0.9819 | Train acc: 51.23% | Val loss: 0.9923 | Val acc: 52.68% | LR: 0.001204
Epoch: 116 | Train loss: 0.9888 | Train acc: 50.77% | Val loss: 0.9347 | Val acc: 54.83% | LR: 0.001137
Epoch: 117 | Train loss: 0.9917 | Train acc: 50.54% | Val loss: 0.9207 | Val acc: 54.40% | LR: 0.001072
Epoch: 118 | Train loss: 0.9886 | Train acc: 50.68% | Val loss: 0.9263 | Val acc: 54.17% | LR: 0.001008
Epoch: 119 | Train loss: 0.9935 | Train acc: 50.38% | Val loss: 0.9362 | Val acc: 54.06% | LR: 0.000946
Epoch: 120 | Train loss: 0.9853 | Train acc: 50.97% | Val loss: 0.9149 | Val acc: 54.64% | LR: 0.000886
Epoch: 121 | Train loss: 0.9845 | Train acc: 50.86% | Val loss: 0.9283 | Val acc: 54.67% | LR: 0.000828
Epoch: 122 | Train loss: 0.9890 | Train acc: 50.71% | Val loss: 0.9214 | Val acc: 54.67% | LR: 0.000772
Epoch: 123 | Train loss: 0.9979 | Train acc: 50.08% | Val loss: 0.9222 | Val acc: 54.57% | LR: 0.000717
Epoch: 124 | Train loss: 0.9974 | Train acc: 50.23% | Val loss: 0.9225 | Val acc: 54.69% | LR: 0.000664
Epoch: 125 | Train loss: 0.9972 | Train acc: 50.06% | Val loss: 0.9316 | Val acc: 54.13% | LR: 0.000613
Epoch: 126 | Train loss: 1.0008 | Train acc: 50.16% | Val loss: 0.9285 | Val acc: 54.23% | LR: 0.000564
Epoch: 127 | Train loss: 0.9918 | Train acc: 50.55% | Val loss: 0.9418 | Val acc: 53.99% | LR: 0.000517
Epoch: 128 | Train loss: 0.9951 | Train acc: 50.26% | Val loss: 0.9412 | Val acc: 54.01% | LR: 0.000472
Epoch: 129 | Train loss: 0.9929 | Train acc: 50.35% | Val loss: 0.9398 | Val acc: 54.01% | LR: 0.000429
Epoch: 130 | Train loss: 0.9994 | Train acc: 50.00% | Val loss: 0.9398 | Val acc: 54.01% | LR: 0.000388
Epoch: 131 | Train loss: 0.9957 | Train acc: 50.09% | Val loss: 0.9376 | Val acc: 54.01% | LR: 0.000349
Epoch: 132 | Train loss: 0.9901 | Train acc: 50.53% | Val loss: 0.9376 | Val acc: 54.01% | LR: 0.000311
Epoch: 133 | Train loss: 0.9923 | Train acc: 50.35% | Val loss: 0.9379 | Val acc: 54.01% | LR: 0.000276
Epoch: 134 | Train loss: 0.9953 | Train acc: 50.18% | Val loss: 0.9392 | Val acc: 54.01% | LR: 0.000243
Epoch: 135 | Train loss: 0.9882 | Train acc: 50.71% | Val loss: 0.9390 | Val acc: 54.01% | LR: 0.000212
Epoch: 136 | Train loss: 0.9889 | Train acc: 50.71% | Val loss: 0.9354 | Val acc: 54.01% | LR: 0.000183
Epoch: 137 | Train loss: 0.9927 | Train acc: 50.35% | Val loss: 0.9365 | Val acc: 54.01% | LR: 0.000157
Epoch: 138 | Train loss: 0.9973 | Train acc: 50.00% | Val loss: 0.9360 | Val acc: 54.01% | LR: 0.000132
Epoch: 139 | Train loss: 0.9884 | Train acc: 50.62% | Val loss: 0.9353 | Val acc: 54.01% | LR: 0.000109
Epoch: 140 | Train loss: 0.9960 | Train acc: 50.18% | Val loss: 0.9359 | Val acc: 54.01% | LR: 0.000089
Epoch: 141 | Train loss: 0.9848 | Train acc: 51.06% | Val loss: 0.9357 | Val acc: 54.01% | LR: 0.000070
Epoch: 142 | Train loss: 0.9897 | Train acc: 50.62% | Val loss: 0.9363 | Val acc: 54.01% | LR: 0.000054
Epoch: 143 | Train loss: 0.9883 | Train acc: 50.71% | Val loss: 0.9359 | Val acc: 54.01% | LR: 0.000040
Epoch: 144 | Train loss: 0.9960 | Train acc: 50.18% | Val loss: 0.9358 | Val acc: 54.01% | LR: 0.000028
Epoch: 145 | Train loss: 0.9915 | Train acc: 50.53% | Val loss: 0.9356 | Val acc: 54.01% | LR: 0.000018
Epoch: 146 | Train loss: 0.9929 | Train acc: 50.35% | Val loss: 0.9354 | Val acc: 54.01% | LR: 0.000011
Epoch: 147 | Train loss: 0.9975 | Train acc: 50.00% | Val loss: 0.9354 | Val acc: 54.01% | LR: 0.000005
Epoch: 148 | Train loss: 0.9911 | Train acc: 50.53% | Val loss: 0.9354 | Val acc: 54.01% | LR: 0.000002
Epoch: 149 | Train loss: 0.9907 | Train acc: 50.44% | Val loss: 0.9354 | Val acc: 54.01% | LR: 0.000001

[I 2025-09-23 02:44:51,472] Trial 26 finished with value: 0.5483330368995667 and parameters: {'lr': 0.009900797537007596, 'hidden_size': 67, 'dropout': 0.40085103835787445, 'weight_decay': 0.12084918635956132}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.0762 | Train acc: 49.90% | Val loss: 1.0035 | Val acc: 47.80% | LR: 0.003863
Epoch: 001 | Train loss: 1.2559 | Train acc: 50.13% | Val loss: 0.9903 | Val acc: 51.47% | LR: 0.003862
Epoch: 002 | Train loss: 1.0307 | Train acc: 49.66% | Val loss: 1.0157 | Val acc: 49.63% | LR: 0.003860
Epoch: 003 | Train loss: 1.0184 | Train acc: 50.28% | Val loss: 0.9811 | Val acc: 54.22% | LR: 0.003857
Epoch: 004 | Train loss: 1.1421 | Train acc: 49.84% | Val loss: 0.9620 | Val acc: 54.30% | LR: 0.003853
Epoch: 005 | Train loss: 1.0100 | Train acc: 50.29% | Val loss: 1.0119 | Val acc: 45.91% | LR: 0.003849
Epoch: 006 | Train loss: 1.0121 | Train acc: 49.96% | Val loss: 0.9581 | Val acc: 54.21% | LR: 0.003843
Epoch: 007 | Train loss: 1.0148 | Train acc: 49.64% | Val loss: 1.0113 | Val acc: 45.95% | LR: 0.003837
Epoch: 008 | Train loss: 1.0056 | Train acc: 50.19% | Val loss: 1.0184 | Val acc: 45.95% | LR: 0.003830
Epoch: 009 | Train loss: 1.0008 | Train acc: 50.33% | Val loss: 0.9946 | Val acc: 53.10% | LR: 0.003822
Epoch: 010 | Train loss: 0.9933 | Train acc: 51.23% | Val loss: 0.9931 | Val acc: 53.58% | LR: 0.003813
Epoch: 011 | Train loss: 1.0008 | Train acc: 50.48% | Val loss: 1.0234 | Val acc: 47.31% | LR: 0.003803
Epoch: 012 | Train loss: 1.0041 | Train acc: 50.86% | Val loss: 0.9833 | Val acc: 52.45% | LR: 0.003793
Epoch: 013 | Train loss: 1.0036 | Train acc: 50.81% | Val loss: 0.9804 | Val acc: 52.73% | LR: 0.003781
Epoch: 014 | Train loss: 0.9933 | Train acc: 51.02% | Val loss: 1.0000 | Val acc: 52.60% | LR: 0.003769
Epoch: 015 | Train loss: 0.9981 | Train acc: 50.56% | Val loss: 0.9848 | Val acc: 52.13% | LR: 0.003756
Epoch: 016 | Train loss: 1.0021 | Train acc: 50.41% | Val loss: 0.9817 | Val acc: 52.36% | LR: 0.003743
Epoch: 017 | Train loss: 0.9964 | Train acc: 50.32% | Val loss: 0.9647 | Val acc: 52.61% | LR: 0.003728
Epoch: 018 | Train loss: 0.9967 | Train acc: 51.36% | Val loss: 1.0230 | Val acc: 48.59% | LR: 0.003713
Epoch: 019 | Train loss: 0.9999 | Train acc: 50.11% | Val loss: 0.9936 | Val acc: 50.67% | LR: 0.003697
Epoch: 020 | Train loss: 0.9935 | Train acc: 51.23% | Val loss: 0.9866 | Val acc: 50.91% | LR: 0.003680
Epoch: 021 | Train loss: 0.9974 | Train acc: 51.01% | Val loss: 0.9920 | Val acc: 51.21% | LR: 0.003662
Epoch: 022 | Train loss: 0.9928 | Train acc: 50.40% | Val loss: 0.9618 | Val acc: 52.08% | LR: 0.003644
Epoch: 023 | Train loss: 0.9932 | Train acc: 50.93% | Val loss: 0.9807 | Val acc: 51.71% | LR: 0.003625
Epoch: 024 | Train loss: 0.9921 | Train acc: 51.09% | Val loss: 0.9834 | Val acc: 51.70% | LR: 0.003605
Epoch: 025 | Train loss: 0.9937 | Train acc: 50.71% | Val loss: 0.9849 | Val acc: 51.88% | LR: 0.003585
Epoch: 026 | Train loss: 0.9910 | Train acc: 51.49% | Val loss: 0.9998 | Val acc: 50.55% | LR: 0.003563
Epoch: 027 | Train loss: 0.9957 | Train acc: 50.49% | Val loss: 0.9918 | Val acc: 50.63% | LR: 0.003541
Epoch: 028 | Train loss: 0.9960 | Train acc: 50.02% | Val loss: 1.0045 | Val acc: 49.17% | LR: 0.003518
Epoch: 029 | Train loss: 1.0028 | Train acc: 50.13% | Val loss: 0.9925 | Val acc: 53.85% | LR: 0.003495
Epoch: 030 | Train loss: 0.9931 | Train acc: 50.99% | Val loss: 1.0004 | Val acc: 51.57% | LR: 0.003471
Epoch: 031 | Train loss: 1.0026 | Train acc: 50.10% | Val loss: 1.0041 | Val acc: 48.93% | LR: 0.003446
Epoch: 032 | Train loss: 1.0090 | Train acc: 49.12% | Val loss: 0.9712 | Val acc: 53.84% | LR: 0.003421
Epoch: 033 | Train loss: 1.0032 | Train acc: 50.13% | Val loss: 0.9836 | Val acc: 53.87% | LR: 0.003395
Epoch: 034 | Train loss: 0.9901 | Train acc: 51.20% | Val loss: 0.9388 | Val acc: 53.55% | LR: 0.003368
Epoch: 035 | Train loss: 0.9965 | Train acc: 50.60% | Val loss: 0.9830 | Val acc: 52.91% | LR: 0.003340
Epoch: 036 | Train loss: 0.9941 | Train acc: 50.87% | Val loss: 1.0052 | Val acc: 49.07% | LR: 0.003312
Epoch: 037 | Train loss: 0.9949 | Train acc: 51.17% | Val loss: 0.9727 | Val acc: 52.21% | LR: 0.003284
Epoch: 038 | Train loss: 0.9973 | Train acc: 50.78% | Val loss: 0.9934 | Val acc: 49.84% | LR: 0.003255
Epoch: 039 | Train loss: 0.9921 | Train acc: 50.92% | Val loss: 0.9725 | Val acc: 51.61% | LR: 0.003225
Epoch: 040 | Train loss: 0.9993 | Train acc: 51.04% | Val loss: 0.9961 | Val acc: 50.78% | LR: 0.003195
Epoch: 041 | Train loss: 1.0061 | Train acc: 50.34% | Val loss: 0.9512 | Val acc: 53.15% | LR: 0.003164
Epoch: 042 | Train loss: 0.9926 | Train acc: 50.59% | Val loss: 0.9708 | Val acc: 51.93% | LR: 0.003132
Epoch: 043 | Train loss: 0.9920 | Train acc: 51.36% | Val loss: 0.9819 | Val acc: 51.44% | LR: 0.003100
Epoch: 044 | Train loss: 0.9981 | Train acc: 50.75% | Val loss: 0.9735 | Val acc: 52.30% | LR: 0.003068
Epoch: 045 | Train loss: 0.9953 | Train acc: 50.36% | Val loss: 0.9614 | Val acc: 52.85% | LR: 0.003035
Epoch: 046 | Train loss: 0.9965 | Train acc: 50.67% | Val loss: 0.9758 | Val acc: 51.28% | LR: 0.003001
Epoch: 047 | Train loss: 0.9926 | Train acc: 51.13% | Val loss: 0.9838 | Val acc: 50.84% | LR: 0.002967
Epoch: 048 | Train loss: 0.9881 | Train acc: 51.07% | Val loss: 1.0104 | Val acc: 48.90% | LR: 0.002933
Epoch: 049 | Train loss: 0.9968 | Train acc: 50.30% | Val loss: 0.9904 | Val acc: 50.30% | LR: 0.002898
Epoch: 050 | Train loss: 0.9936 | Train acc: 50.80% | Val loss: 0.9895 | Val acc: 50.50% | LR: 0.002863
Epoch: 051 | Train loss: 0.9953 | Train acc: 50.93% | Val loss: 1.0084 | Val acc: 49.39% | LR: 0.002827
Epoch: 052 | Train loss: 0.9918 | Train acc: 50.86% | Val loss: 0.9851 | Val acc: 51.49% | LR: 0.002791
Epoch: 053 | Train loss: 0.9960 | Train acc: 50.90% | Val loss: 0.9896 | Val acc: 50.42% | LR: 0.002755
Epoch: 054 | Train loss: 0.9918 | Train acc: 50.77% | Val loss: 0.9986 | Val acc: 50.04% | LR: 0.002718
Epoch: 055 | Train loss: 0.9860 | Train acc: 50.93% | Val loss: 0.9794 | Val acc: 51.00% | LR: 0.002681
Epoch: 056 | Train loss: 0.9895 | Train acc: 50.55% | Val loss: 0.9954 | Val acc: 50.49% | LR: 0.002643
Epoch: 057 | Train loss: 0.9945 | Train acc: 50.52% | Val loss: 0.9855 | Val acc: 50.84% | LR: 0.002606
Epoch: 058 | Train loss: 0.9841 | Train acc: 51.83% | Val loss: 0.9680 | Val acc: 53.14% | LR: 0.002568
Epoch: 059 | Train loss: 1.1036 | Train acc: 50.64% | Val loss: 0.9929 | Val acc: 49.57% | LR: 0.002529
Epoch: 060 | Train loss: 0.9939 | Train acc: 50.77% | Val loss: 0.9998 | Val acc: 46.99% | LR: 0.002491
Epoch: 061 | Train loss: 1.0053 | Train acc: 50.13% | Val loss: 0.9693 | Val acc: 54.05% | LR: 0.002452
Epoch: 062 | Train loss: 1.0031 | Train acc: 49.48% | Val loss: 1.0251 | Val acc: 45.56% | LR: 0.002413
Epoch: 063 | Train loss: 0.9983 | Train acc: 50.57% | Val loss: 1.0008 | Val acc: 50.08% | LR: 0.002373
Epoch: 064 | Train loss: 0.9936 | Train acc: 51.22% | Val loss: 1.0083 | Val acc: 49.15% | LR: 0.002334
Epoch: 065 | Train loss: 0.9958 | Train acc: 50.79% | Val loss: 1.0365 | Val acc: 46.78% | LR: 0.002294
Epoch: 066 | Train loss: 0.9978 | Train acc: 50.51% | Val loss: 1.0132 | Val acc: 45.99% | LR: 0.002255
Epoch: 067 | Train loss: 1.0065 | Train acc: 49.68% | Val loss: 1.0239 | Val acc: 45.95% | LR: 0.002215
Epoch: 068 | Train loss: 0.9912 | Train acc: 50.81% | Val loss: 0.9878 | Val acc: 51.57% | LR: 0.002175
Epoch: 069 | Train loss: 0.9888 | Train acc: 51.16% | Val loss: 0.9840 | Val acc: 52.58% | LR: 0.002134
Epoch: 070 | Train loss: 0.9933 | Train acc: 50.50% | Val loss: 0.9828 | Val acc: 52.14% | LR: 0.002094
Epoch: 071 | Train loss: 0.9936 | Train acc: 50.74% | Val loss: 1.0077 | Val acc: 50.30% | LR: 0.002054
Epoch: 072 | Train loss: 0.9948 | Train acc: 50.23% | Val loss: 0.9718 | Val acc: 52.12% | LR: 0.002013
Epoch: 073 | Train loss: 0.9922 | Train acc: 50.86% | Val loss: 0.9814 | Val acc: 51.84% | LR: 0.001973
Epoch: 074 | Train loss: 0.9844 | Train acc: 51.31% | Val loss: 0.9458 | Val acc: 54.49% | LR: 0.001932
Epoch: 075 | Train loss: 0.9883 | Train acc: 50.95% | Val loss: 0.9924 | Val acc: 49.99% | LR: 0.001892
Epoch: 076 | Train loss: 0.9883 | Train acc: 51.05% | Val loss: 0.9902 | Val acc: 50.09% | LR: 0.001852
Epoch: 077 | Train loss: 0.9906 | Train acc: 51.21% | Val loss: 0.9852 | Val acc: 50.80% | LR: 0.001811
Epoch: 078 | Train loss: 0.9822 | Train acc: 51.21% | Val loss: 0.9833 | Val acc: 51.22% | LR: 0.001771
Epoch: 079 | Train loss: 0.9883 | Train acc: 50.85% | Val loss: 0.9808 | Val acc: 50.93% | LR: 0.001731
Epoch: 080 | Train loss: 0.9899 | Train acc: 50.60% | Val loss: 0.9694 | Val acc: 52.27% | LR: 0.001690
Epoch: 081 | Train loss: 0.9933 | Train acc: 50.86% | Val loss: 0.9618 | Val acc: 52.81% | LR: 0.001650
Epoch: 082 | Train loss: 0.9904 | Train acc: 51.10% | Val loss: 0.9693 | Val acc: 51.92% | LR: 0.001610
Epoch: 083 | Train loss: 0.9937 | Train acc: 50.60% | Val loss: 0.9912 | Val acc: 50.35% | LR: 0.001571
Epoch: 084 | Train loss: 0.9897 | Train acc: 50.79% | Val loss: 1.0018 | Val acc: 50.42% | LR: 0.001531
Epoch: 085 | Train loss: 0.9918 | Train acc: 51.09% | Val loss: 0.9768 | Val acc: 51.10% | LR: 0.001491
Epoch: 086 | Train loss: 0.9898 | Train acc: 50.60% | Val loss: 0.9761 | Val acc: 51.61% | LR: 0.001452
Epoch: 087 | Train loss: 0.9810 | Train acc: 51.65% | Val loss: 0.9697 | Val acc: 51.73% | LR: 0.001413
Epoch: 088 | Train loss: 0.9906 | Train acc: 50.58% | Val loss: 0.9989 | Val acc: 49.65% | LR: 0.001374
Epoch: 089 | Train loss: 0.9850 | Train acc: 50.89% | Val loss: 0.9556 | Val acc: 53.44% | LR: 0.001336
Epoch: 090 | Train loss: 0.9928 | Train acc: 50.40% | Val loss: 0.9438 | Val acc: 53.63% | LR: 0.001297
Epoch: 091 | Train loss: 0.9872 | Train acc: 51.17% | Val loss: 0.9704 | Val acc: 51.85% | LR: 0.001259
Epoch: 092 | Train loss: 0.9929 | Train acc: 50.36% | Val loss: 0.9608 | Val acc: 52.31% | LR: 0.001221
Epoch: 093 | Train loss: 0.9840 | Train acc: 51.36% | Val loss: 0.9518 | Val acc: 53.34% | LR: 0.001184
Epoch: 094 | Train loss: 0.9856 | Train acc: 51.02% | Val loss: 0.9549 | Val acc: 53.61% | LR: 0.001147
Epoch: 095 | Train loss: 0.9849 | Train acc: 51.05% | Val loss: 0.9740 | Val acc: 51.23% | LR: 0.001110
Epoch: 096 | Train loss: 0.9830 | Train acc: 51.07% | Val loss: 0.9721 | Val acc: 51.87% | LR: 0.001074
Epoch: 097 | Train loss: 0.9864 | Train acc: 50.83% | Val loss: 0.9527 | Val acc: 52.67% | LR: 0.001038
Epoch: 098 | Train loss: 0.9859 | Train acc: 51.15% | Val loss: 0.9534 | Val acc: 52.73% | LR: 0.001002
Epoch: 099 | Train loss: 0.9831 | Train acc: 51.32% | Val loss: 0.9590 | Val acc: 53.11% | LR: 0.000967
Epoch: 100 | Train loss: 0.9822 | Train acc: 51.41% | Val loss: 0.9337 | Val acc: 53.95% | LR: 0.000932
Epoch: 101 | Train loss: 0.9869 | Train acc: 50.98% | Val loss: 0.9653 | Val acc: 51.93% | LR: 0.000898
Epoch: 102 | Train loss: 0.9830 | Train acc: 51.69% | Val loss: 0.9572 | Val acc: 52.48% | LR: 0.000864
Epoch: 103 | Train loss: 0.9948 | Train acc: 50.57% | Val loss: 1.2285 | Val acc: 52.96% | LR: 0.000830
Epoch: 104 | Train loss: 1.0144 | Train acc: 51.30% | Val loss: 1.0002 | Val acc: 49.98% | LR: 0.000797
Epoch: 105 | Train loss: 0.9913 | Train acc: 50.54% | Val loss: 0.9898 | Val acc: 51.18% | LR: 0.000765
Epoch: 106 | Train loss: 0.9932 | Train acc: 50.63% | Val loss: 0.9910 | Val acc: 51.03% | LR: 0.000733
Epoch: 107 | Train loss: 0.9887 | Train acc: 51.49% | Val loss: 1.0495 | Val acc: 50.92% | LR: 0.000701
Epoch: 108 | Train loss: 0.9868 | Train acc: 51.08% | Val loss: 0.9920 | Val acc: 50.60% | LR: 0.000670
Epoch: 109 | Train loss: 0.9856 | Train acc: 51.18% | Val loss: 1.0012 | Val acc: 50.36% | LR: 0.000640
Epoch: 110 | Train loss: 0.9860 | Train acc: 50.99% | Val loss: 0.9998 | Val acc: 50.07% | LR: 0.000610
Epoch: 111 | Train loss: 0.9951 | Train acc: 50.16% | Val loss: 1.0005 | Val acc: 50.25% | LR: 0.000581
Epoch: 112 | Train loss: 0.9917 | Train acc: 50.62% | Val loss: 1.0065 | Val acc: 49.88% | LR: 0.000552
Epoch: 113 | Train loss: 0.9967 | Train acc: 50.50% | Val loss: 0.9977 | Val acc: 50.37% | LR: 0.000524
Epoch: 114 | Train loss: 0.9922 | Train acc: 50.56% | Val loss: 1.0018 | Val acc: 50.79% | LR: 0.000497
Epoch: 115 | Train loss: 0.9870 | Train acc: 50.88% | Val loss: 0.9947 | Val acc: 50.88% | LR: 0.000470
Epoch: 116 | Train loss: 0.9913 | Train acc: 50.67% | Val loss: 0.9947 | Val acc: 50.78% | LR: 0.000444
Epoch: 117 | Train loss: 0.9858 | Train acc: 51.00% | Val loss: 0.9928 | Val acc: 50.89% | LR: 0.000419
Epoch: 118 | Train loss: 0.9844 | Train acc: 51.33% | Val loss: 0.9923 | Val acc: 50.84% | LR: 0.000394
Epoch: 119 | Train loss: 0.9918 | Train acc: 51.06% | Val loss: 0.9891 | Val acc: 50.78% | LR: 0.000370
Epoch: 120 | Train loss: 0.9882 | Train acc: 50.69% | Val loss: 0.9990 | Val acc: 50.74% | LR: 0.000346
Epoch: 121 | Train loss: 0.9879 | Train acc: 50.83% | Val loss: 0.9928 | Val acc: 50.78% | LR: 0.000324
Epoch: 122 | Train loss: 0.9885 | Train acc: 50.79% | Val loss: 0.9901 | Val acc: 50.70% | LR: 0.000302
Epoch: 123 | Train loss: 0.9858 | Train acc: 50.85% | Val loss: 1.0005 | Val acc: 50.72% | LR: 0.000280
Epoch: 124 | Train loss: 0.9804 | Train acc: 51.30% | Val loss: 0.9914 | Val acc: 51.00% | LR: 0.000260
Epoch: 125 | Train loss: 0.9852 | Train acc: 51.09% | Val loss: 0.9957 | Val acc: 50.74% | LR: 0.000240
Epoch: 126 | Train loss: 0.9863 | Train acc: 51.03% | Val loss: 0.9930 | Val acc: 50.74% | LR: 0.000221
Epoch: 127 | Train loss: 0.9855 | Train acc: 51.25% | Val loss: 0.9941 | Val acc: 50.76% | LR: 0.000202
Epoch: 128 | Train loss: 0.9886 | Train acc: 50.81% | Val loss: 0.9921 | Val acc: 50.72% | LR: 0.000185
Epoch: 129 | Train loss: 0.9851 | Train acc: 50.87% | Val loss: 0.9937 | Val acc: 50.77% | LR: 0.000168
Epoch: 130 | Train loss: 0.9832 | Train acc: 51.40% | Val loss: 0.9942 | Val acc: 50.72% | LR: 0.000152
Epoch: 131 | Train loss: 0.9847 | Train acc: 51.06% | Val loss: 0.9936 | Val acc: 50.72% | LR: 0.000137
Epoch: 132 | Train loss: 0.9862 | Train acc: 51.03% | Val loss: 0.9946 | Val acc: 50.73% | LR: 0.000122
Epoch: 133 | Train loss: 0.9912 | Train acc: 50.79% | Val loss: 0.9932 | Val acc: 50.77% | LR: 0.000108
Epoch: 134 | Train loss: 0.9853 | Train acc: 50.86% | Val loss: 0.9924 | Val acc: 50.75% | LR: 0.000096
Epoch: 135 | Train loss: 0.9851 | Train acc: 50.98% | Val loss: 0.9916 | Val acc: 50.75% | LR: 0.000083
Epoch: 136 | Train loss: 0.9823 | Train acc: 51.12% | Val loss: 0.9927 | Val acc: 50.77% | LR: 0.000072
Epoch: 137 | Train loss: 0.9783 | Train acc: 51.53% | Val loss: 0.9926 | Val acc: 50.75% | LR: 0.000062
Epoch: 138 | Train loss: 0.9780 | Train acc: 51.49% | Val loss: 0.9944 | Val acc: 50.77% | LR: 0.000052
Epoch: 139 | Train loss: 0.9848 | Train acc: 50.87% | Val loss: 0.9934 | Val acc: 50.79% | LR: 0.000043
Epoch: 140 | Train loss: 0.9767 | Train acc: 51.62% | Val loss: 0.9953 | Val acc: 50.75% | LR: 0.000035
Epoch: 141 | Train loss: 0.9867 | Train acc: 50.79% | Val loss: 0.9935 | Val acc: 50.79% | LR: 0.000028
Epoch: 142 | Train loss: 0.9831 | Train acc: 51.18% | Val loss: 0.9934 | Val acc: 50.79% | LR: 0.000022
Epoch: 143 | Train loss: 0.9879 | Train acc: 50.70% | Val loss: 0.9935 | Val acc: 50.77% | LR: 0.000016
Epoch: 144 | Train loss: 0.9839 | Train acc: 51.09% | Val loss: 0.9936 | Val acc: 50.77% | LR: 0.000012
Epoch: 145 | Train loss: 0.9875 | Train acc: 50.93% | Val loss: 0.9936 | Val acc: 50.77% | LR: 0.000008
Epoch: 146 | Train loss: 0.9850 | Train acc: 50.94% | Val loss: 0.9937 | Val acc: 50.77% | LR: 0.000005
Epoch: 147 | Train loss: 0.9838 | Train acc: 51.11% | Val loss: 0.9938 | Val acc: 50.77% | LR: 0.000003
Epoch: 148 | Train loss: 0.9824 | Train acc: 51.26% | Val loss: 0.9938 | Val acc: 50.77% | LR: 0.000001
Epoch: 149 | Train loss: 0.9808 | Train acc: 51.15% | Val loss: 0.9938 | Val acc: 50.77% | LR: 0.000001

[I 2025-09-23 02:47:14,125] Trial 27 finished with value: 0.5448783874511719 and parameters: {'lr': 0.00386390149554239, 'hidden_size': 207, 'dropout': 0.2908724864354718, 'weight_decay': 0.7221164185880671}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 0.9981 | Train acc: 50.39% | Val loss: 0.9863 | Val acc: 51.10% | LR: 0.002660
Epoch: 001 | Train loss: 0.9903 | Train acc: 51.05% | Val loss: 0.9834 | Val acc: 51.27% | LR: 0.002659
Epoch: 002 | Train loss: 0.9922 | Train acc: 50.97% | Val loss: 0.9678 | Val acc: 53.12% | LR: 0.002657
Epoch: 003 | Train loss: 7.3021 | Train acc: 50.71% | Val loss: 0.9889 | Val acc: 51.50% | LR: 0.002655
Epoch: 004 | Train loss: 0.9994 | Train acc: 50.98% | Val loss: 0.9999 | Val acc: 49.71% | LR: 0.002653
Epoch: 005 | Train loss: 0.9937 | Train acc: 51.28% | Val loss: 1.0124 | Val acc: 48.21% | LR: 0.002650
Epoch: 006 | Train loss: 1.0039 | Train acc: 49.64% | Val loss: 0.9911 | Val acc: 51.50% | LR: 0.002646
Epoch: 007 | Train loss: 0.9955 | Train acc: 50.92% | Val loss: 0.9759 | Val acc: 51.41% | LR: 0.002641
Epoch: 008 | Train loss: 0.9954 | Train acc: 50.60% | Val loss: 0.9832 | Val acc: 51.39% | LR: 0.002636
Epoch: 009 | Train loss: 0.9913 | Train acc: 50.77% | Val loss: 0.9842 | Val acc: 50.48% | LR: 0.002631
Epoch: 010 | Train loss: 0.9916 | Train acc: 51.00% | Val loss: 0.9922 | Val acc: 50.22% | LR: 0.002625
Epoch: 011 | Train loss: 0.9862 | Train acc: 50.81% | Val loss: 0.9883 | Val acc: 50.88% | LR: 0.002618
Epoch: 012 | Train loss: 0.9919 | Train acc: 50.72% | Val loss: 0.9930 | Val acc: 50.41% | LR: 0.002611
Epoch: 013 | Train loss: 0.9867 | Train acc: 51.39% | Val loss: 0.9906 | Val acc: 50.49% | LR: 0.002603
Epoch: 014 | Train loss: 0.9927 | Train acc: 50.73% | Val loss: 1.0074 | Val acc: 49.59% | LR: 0.002595
Epoch: 015 | Train loss: 0.9888 | Train acc: 51.13% | Val loss: 1.0008 | Val acc: 49.89% | LR: 0.002586
Epoch: 016 | Train loss: 0.9894 | Train acc: 50.68% | Val loss: 1.0087 | Val acc: 49.65% | LR: 0.002577
Epoch: 017 | Train loss: 0.9851 | Train acc: 51.17% | Val loss: 0.9968 | Val acc: 50.00% | LR: 0.002567
Epoch: 018 | Train loss: 0.9865 | Train acc: 51.52% | Val loss: 0.9974 | Val acc: 50.21% | LR: 0.002556
Epoch: 019 | Train loss: 0.9847 | Train acc: 51.04% | Val loss: 0.9646 | Val acc: 52.20% | LR: 0.002545
Epoch: 020 | Train loss: 0.9858 | Train acc: 51.31% | Val loss: 1.0247 | Val acc: 48.56% | LR: 0.002533
Epoch: 021 | Train loss: 0.9919 | Train acc: 50.84% | Val loss: 1.0232 | Val acc: 48.88% | LR: 0.002521
Epoch: 022 | Train loss: 0.9903 | Train acc: 50.78% | Val loss: 1.0082 | Val acc: 49.07% | LR: 0.002509
Epoch: 023 | Train loss: 0.9932 | Train acc: 51.07% | Val loss: 0.9766 | Val acc: 53.48% | LR: 0.002496
Epoch: 024 | Train loss: 1.0118 | Train acc: 50.25% | Val loss: 1.0519 | Val acc: 50.97% | LR: 0.002482
Epoch: 025 | Train loss: 1.0059 | Train acc: 50.37% | Val loss: 0.9919 | Val acc: 50.73% | LR: 0.002468
Epoch: 026 | Train loss: 1.0080 | Train acc: 50.14% | Val loss: 1.0046 | Val acc: 50.56% | LR: 0.002453
Epoch: 027 | Train loss: 0.9946 | Train acc: 50.53% | Val loss: 1.0125 | Val acc: 50.52% | LR: 0.002438
Epoch: 028 | Train loss: 0.9870 | Train acc: 51.34% | Val loss: 0.9732 | Val acc: 51.34% | LR: 0.002422
Epoch: 029 | Train loss: 0.9891 | Train acc: 51.02% | Val loss: 0.9973 | Val acc: 51.99% | LR: 0.002406
Epoch: 030 | Train loss: 0.9958 | Train acc: 50.81% | Val loss: 1.0233 | Val acc: 50.39% | LR: 0.002389
Epoch: 031 | Train loss: 0.9925 | Train acc: 51.05% | Val loss: 1.0043 | Val acc: 50.35% | LR: 0.002372
Epoch: 032 | Train loss: 0.9890 | Train acc: 51.32% | Val loss: 1.0041 | Val acc: 50.52% | LR: 0.002355
Epoch: 033 | Train loss: 0.9900 | Train acc: 51.13% | Val loss: 1.0329 | Val acc: 49.87% | LR: 0.002337
Epoch: 034 | Train loss: 1.0049 | Train acc: 50.72% | Val loss: 1.0107 | Val acc: 49.51% | LR: 0.002319
Epoch: 035 | Train loss: 0.9957 | Train acc: 50.78% | Val loss: 1.0041 | Val acc: 49.01% | LR: 0.002300
Epoch: 036 | Train loss: 1.0011 | Train acc: 50.70% | Val loss: 1.1397 | Val acc: 48.90% | LR: 0.002280
Epoch: 037 | Train loss: 0.9994 | Train acc: 50.59% | Val loss: 1.0057 | Val acc: 49.31% | LR: 0.002261
Epoch: 038 | Train loss: 0.9920 | Train acc: 50.79% | Val loss: 1.0049 | Val acc: 49.29% | LR: 0.002241
Epoch: 039 | Train loss: 0.9952 | Train acc: 50.65% | Val loss: 1.0117 | Val acc: 49.84% | LR: 0.002220
Epoch: 040 | Train loss: 0.9939 | Train acc: 50.95% | Val loss: 1.0040 | Val acc: 50.34% | LR: 0.002199
Epoch: 041 | Train loss: 0.9889 | Train acc: 51.08% | Val loss: 1.0310 | Val acc: 46.87% | LR: 0.002178
Epoch: 042 | Train loss: 0.9923 | Train acc: 50.69% | Val loss: 1.0157 | Val acc: 49.34% | LR: 0.002156
Epoch: 043 | Train loss: 0.9903 | Train acc: 50.86% | Val loss: 1.0240 | Val acc: 49.22% | LR: 0.002134
Epoch: 044 | Train loss: 0.9962 | Train acc: 50.60% | Val loss: 1.0049 | Val acc: 49.42% | LR: 0.002112
Epoch: 045 | Train loss: 0.9865 | Train acc: 50.95% | Val loss: 0.9838 | Val acc: 49.69% | LR: 0.002089
Epoch: 046 | Train loss: 0.9975 | Train acc: 50.15% | Val loss: 0.9901 | Val acc: 49.53% | LR: 0.002066
Epoch: 047 | Train loss: 0.9990 | Train acc: 50.29% | Val loss: 1.0126 | Val acc: 49.43% | LR: 0.002043
Epoch: 048 | Train loss: 0.9873 | Train acc: 51.05% | Val loss: 0.9972 | Val acc: 49.44% | LR: 0.002019
Epoch: 049 | Train loss: 0.9895 | Train acc: 50.73% | Val loss: 0.9864 | Val acc: 49.73% | LR: 0.001995
Epoch: 050 | Train loss: 0.9842 | Train acc: 51.27% | Val loss: 0.9922 | Val acc: 49.63% | LR: 0.001971
Epoch: 051 | Train loss: 0.9897 | Train acc: 50.90% | Val loss: 0.9988 | Val acc: 49.71% | LR: 0.001946
Epoch: 052 | Train loss: 0.9836 | Train acc: 51.15% | Val loss: 1.0044 | Val acc: 49.61% | LR: 0.001922
Epoch: 053 | Train loss: 0.9864 | Train acc: 50.84% | Val loss: 1.0026 | Val acc: 49.53% | LR: 0.001897
Epoch: 054 | Train loss: 0.9864 | Train acc: 51.05% | Val loss: 1.0031 | Val acc: 49.55% | LR: 0.001871
Epoch: 055 | Train loss: 0.9952 | Train acc: 50.59% | Val loss: 1.0029 | Val acc: 49.55% | LR: 0.001846
Epoch: 056 | Train loss: 0.9884 | Train acc: 50.81% | Val loss: 1.0074 | Val acc: 49.67% | LR: 0.001820
Epoch: 057 | Train loss: 0.9910 | Train acc: 50.44% | Val loss: 1.0000 | Val acc: 49.69% | LR: 0.001794
Epoch: 058 | Train loss: 0.9799 | Train acc: 51.63% | Val loss: 1.0075 | Val acc: 49.67% | LR: 0.001768
Epoch: 059 | Train loss: 0.9917 | Train acc: 50.62% | Val loss: 1.0025 | Val acc: 49.65% | LR: 0.001741
Epoch: 060 | Train loss: 0.9905 | Train acc: 50.84% | Val loss: 1.0044 | Val acc: 49.65% | LR: 0.001715
Epoch: 061 | Train loss: 0.9925 | Train acc: 50.78% | Val loss: 1.0043 | Val acc: 49.83% | LR: 0.001688
Epoch: 062 | Train loss: 0.9842 | Train acc: 51.15% | Val loss: 1.0095 | Val acc: 49.67% | LR: 0.001661
Epoch: 063 | Train loss: 0.9913 | Train acc: 50.90% | Val loss: 0.9971 | Val acc: 49.89% | LR: 0.001634
Epoch: 064 | Train loss: 0.9845 | Train acc: 51.07% | Val loss: 1.0035 | Val acc: 49.93% | LR: 0.001607
Epoch: 065 | Train loss: 0.9843 | Train acc: 51.08% | Val loss: 1.0075 | Val acc: 49.91% | LR: 0.001580
Epoch: 066 | Train loss: 0.9932 | Train acc: 50.54% | Val loss: 0.9932 | Val acc: 49.95% | LR: 0.001552
Epoch: 067 | Train loss: 0.9891 | Train acc: 50.59% | Val loss: 0.9986 | Val acc: 49.87% | LR: 0.001525
Epoch: 068 | Train loss: 0.9892 | Train acc: 50.81% | Val loss: 1.0062 | Val acc: 49.75% | LR: 0.001497
Epoch: 069 | Train loss: 0.9853 | Train acc: 50.92% | Val loss: 1.0070 | Val acc: 49.75% | LR: 0.001469
Epoch: 070 | Train loss: 0.9802 | Train acc: 51.40% | Val loss: 1.0054 | Val acc: 49.77% | LR: 0.001442
Epoch: 071 | Train loss: 0.9900 | Train acc: 50.61% | Val loss: 0.9943 | Val acc: 49.95% | LR: 0.001414
Epoch: 072 | Train loss: 0.9828 | Train acc: 51.49% | Val loss: 0.9995 | Val acc: 49.93% | LR: 0.001386
Epoch: 073 | Train loss: 0.9786 | Train acc: 51.33% | Val loss: 1.0071 | Val acc: 49.85% | LR: 0.001358
Epoch: 074 | Train loss: 0.9823 | Train acc: 51.04% | Val loss: 1.0089 | Val acc: 49.55% | LR: 0.001330
Epoch: 075 | Train loss: 0.9816 | Train acc: 51.41% | Val loss: 1.0054 | Val acc: 49.69% | LR: 0.001303
Epoch: 076 | Train loss: 0.9850 | Train acc: 51.16% | Val loss: 1.0022 | Val acc: 49.83% | LR: 0.001275
Epoch: 077 | Train loss: 0.9900 | Train acc: 50.78% | Val loss: 1.0091 | Val acc: 49.71% | LR: 0.001247
Epoch: 078 | Train loss: 0.9784 | Train acc: 51.53% | Val loss: 1.0128 | Val acc: 49.61% | LR: 0.001219
Epoch: 079 | Train loss: 0.9869 | Train acc: 50.92% | Val loss: 1.0043 | Val acc: 49.59% | LR: 0.001192
Epoch: 080 | Train loss: 0.9772 | Train acc: 51.43% | Val loss: 1.0111 | Val acc: 49.55% | LR: 0.001164
Epoch: 081 | Train loss: 0.9881 | Train acc: 50.76% | Val loss: 1.0080 | Val acc: 49.65% | LR: 0.001136
Epoch: 082 | Train loss: 0.9799 | Train acc: 51.28% | Val loss: 1.0094 | Val acc: 49.59% | LR: 0.001109
Epoch: 083 | Train loss: 0.9805 | Train acc: 51.08% | Val loss: 1.0101 | Val acc: 49.58% | LR: 0.001081
Epoch: 084 | Train loss: 0.9763 | Train acc: 51.74% | Val loss: 1.0125 | Val acc: 49.34% | LR: 0.001054
Epoch: 085 | Train loss: 0.9768 | Train acc: 51.49% | Val loss: 1.0106 | Val acc: 49.36% | LR: 0.001027
Epoch: 086 | Train loss: 0.9798 | Train acc: 51.31% | Val loss: 1.0123 | Val acc: 49.43% | LR: 0.001000
Epoch: 087 | Train loss: 0.9810 | Train acc: 51.33% | Val loss: 1.0100 | Val acc: 49.42% | LR: 0.000973
Epoch: 088 | Train loss: 0.9836 | Train acc: 51.18% | Val loss: 1.0052 | Val acc: 49.44% | LR: 0.000946
Epoch: 089 | Train loss: 0.9846 | Train acc: 51.15% | Val loss: 1.0034 | Val acc: 49.59% | LR: 0.000920
Epoch: 090 | Train loss: 0.9887 | Train acc: 50.71% | Val loss: 1.0201 | Val acc: 48.77% | LR: 0.000893
Epoch: 091 | Train loss: 0.9826 | Train acc: 51.21% | Val loss: 1.0077 | Val acc: 49.55% | LR: 0.000867
Epoch: 092 | Train loss: 0.9802 | Train acc: 51.29% | Val loss: 1.0132 | Val acc: 49.06% | LR: 0.000841
Epoch: 093 | Train loss: 0.9836 | Train acc: 51.11% | Val loss: 1.0149 | Val acc: 48.89% | LR: 0.000815
Epoch: 094 | Train loss: 0.9877 | Train acc: 50.85% | Val loss: 1.0106 | Val acc: 49.26% | LR: 0.000790
Epoch: 095 | Train loss: 0.9833 | Train acc: 51.20% | Val loss: 1.0105 | Val acc: 49.08% | LR: 0.000764
Epoch: 096 | Train loss: 0.9796 | Train acc: 51.38% | Val loss: 1.0142 | Val acc: 48.83% | LR: 0.000739
Epoch: 097 | Train loss: 0.9794 | Train acc: 51.30% | Val loss: 1.0120 | Val acc: 49.26% | LR: 0.000715
Epoch: 098 | Train loss: 0.9906 | Train acc: 50.49% | Val loss: 1.0122 | Val acc: 49.00% | LR: 0.000690
Epoch: 099 | Train loss: 0.9736 | Train acc: 51.91% | Val loss: 1.0158 | Val acc: 48.69% | LR: 0.000666
Epoch: 100 | Train loss: 0.9787 | Train acc: 51.41% | Val loss: 1.0148 | Val acc: 48.75% | LR: 0.000642
Epoch: 101 | Train loss: 0.9838 | Train acc: 51.06% | Val loss: 1.0180 | Val acc: 48.73% | LR: 0.000618
Epoch: 102 | Train loss: 0.9811 | Train acc: 51.23% | Val loss: 1.0109 | Val acc: 49.20% | LR: 0.000595
Epoch: 103 | Train loss: 0.9826 | Train acc: 51.14% | Val loss: 1.0201 | Val acc: 48.53% | LR: 0.000572
Epoch: 104 | Train loss: 0.9809 | Train acc: 51.33% | Val loss: 1.0334 | Val acc: 47.44% | LR: 0.000549
Epoch: 105 | Train loss: 0.9836 | Train acc: 51.18% | Val loss: 1.0240 | Val acc: 48.03% | LR: 0.000527
Epoch: 106 | Train loss: 0.9894 | Train acc: 50.76% | Val loss: 1.0329 | Val acc: 47.15% | LR: 0.000505
Epoch: 107 | Train loss: 0.9873 | Train acc: 50.77% | Val loss: 1.0171 | Val acc: 48.37% | LR: 0.000483
Epoch: 108 | Train loss: 0.9770 | Train acc: 51.59% | Val loss: 1.0117 | Val acc: 48.75% | LR: 0.000462
Epoch: 109 | Train loss: 0.9815 | Train acc: 51.24% | Val loss: 1.0077 | Val acc: 49.10% | LR: 0.000441
Epoch: 110 | Train loss: 0.9921 | Train acc: 50.37% | Val loss: 1.0114 | Val acc: 48.92% | LR: 0.000420
Epoch: 111 | Train loss: 0.9811 | Train acc: 51.27% | Val loss: 1.0122 | Val acc: 48.94% | LR: 0.000400
Epoch: 112 | Train loss: 0.9841 | Train acc: 51.00% | Val loss: 1.0113 | Val acc: 48.94% | LR: 0.000381
Epoch: 113 | Train loss: 0.9820 | Train acc: 51.11% | Val loss: 1.0110 | Val acc: 49.02% | LR: 0.000361
Epoch: 114 | Train loss: 0.9850 | Train acc: 50.95% | Val loss: 1.0096 | Val acc: 49.06% | LR: 0.000342
Epoch: 115 | Train loss: 0.9794 | Train acc: 51.47% | Val loss: 1.0128 | Val acc: 48.95% | LR: 0.000324
Epoch: 116 | Train loss: 0.9792 | Train acc: 51.35% | Val loss: 1.0110 | Val acc: 48.98% | LR: 0.000306
Epoch: 117 | Train loss: 0.9842 | Train acc: 51.02% | Val loss: 1.0112 | Val acc: 49.04% | LR: 0.000289
Epoch: 118 | Train loss: 0.9800 | Train acc: 51.21% | Val loss: 1.0130 | Val acc: 49.02% | LR: 0.000272
Epoch: 119 | Train loss: 0.9815 | Train acc: 51.11% | Val loss: 1.0112 | Val acc: 49.10% | LR: 0.000255
Epoch: 120 | Train loss: 0.9873 | Train acc: 50.86% | Val loss: 1.0121 | Val acc: 49.20% | LR: 0.000239
Epoch: 121 | Train loss: 0.9814 | Train acc: 51.13% | Val loss: 1.0141 | Val acc: 49.04% | LR: 0.000223
Epoch: 122 | Train loss: 0.9797 | Train acc: 51.22% | Val loss: 1.0132 | Val acc: 49.14% | LR: 0.000208
Epoch: 123 | Train loss: 0.9784 | Train acc: 51.40% | Val loss: 1.0148 | Val acc: 49.02% | LR: 0.000193
Epoch: 124 | Train loss: 0.9824 | Train acc: 51.03% | Val loss: 1.0113 | Val acc: 49.16% | LR: 0.000179
Epoch: 125 | Train loss: 0.9861 | Train acc: 50.86% | Val loss: 1.0123 | Val acc: 49.25% | LR: 0.000165
Epoch: 126 | Train loss: 0.9886 | Train acc: 50.76% | Val loss: 1.0129 | Val acc: 49.16% | LR: 0.000152
Epoch: 127 | Train loss: 0.9785 | Train acc: 51.13% | Val loss: 1.0123 | Val acc: 49.25% | LR: 0.000140
Epoch: 128 | Train loss: 0.9785 | Train acc: 51.23% | Val loss: 1.0123 | Val acc: 49.23% | LR: 0.000128
Epoch: 129 | Train loss: 0.9812 | Train acc: 51.31% | Val loss: 1.0121 | Val acc: 49.37% | LR: 0.000116
Epoch: 130 | Train loss: 0.9858 | Train acc: 50.76% | Val loss: 1.0126 | Val acc: 49.29% | LR: 0.000105
Epoch: 131 | Train loss: 0.9744 | Train acc: 51.65% | Val loss: 1.0116 | Val acc: 49.31% | LR: 0.000094
Epoch: 132 | Train loss: 0.9825 | Train acc: 50.94% | Val loss: 1.0135 | Val acc: 49.05% | LR: 0.000084
Epoch: 133 | Train loss: 0.9795 | Train acc: 51.30% | Val loss: 1.0135 | Val acc: 49.19% | LR: 0.000075
Epoch: 134 | Train loss: 0.9899 | Train acc: 50.49% | Val loss: 1.0131 | Val acc: 49.21% | LR: 0.000066
Epoch: 135 | Train loss: 0.9771 | Train acc: 51.39% | Val loss: 1.0129 | Val acc: 49.21% | LR: 0.000058
Epoch: 136 | Train loss: 0.9817 | Train acc: 51.13% | Val loss: 1.0130 | Val acc: 49.21% | LR: 0.000050
Epoch: 137 | Train loss: 0.9805 | Train acc: 51.05% | Val loss: 1.0131 | Val acc: 49.17% | LR: 0.000043
Epoch: 138 | Train loss: 0.9834 | Train acc: 50.87% | Val loss: 1.0128 | Val acc: 49.25% | LR: 0.000036
Epoch: 139 | Train loss: 0.9699 | Train acc: 51.91% | Val loss: 1.0128 | Val acc: 49.23% | LR: 0.000030
Epoch: 140 | Train loss: 0.9880 | Train acc: 50.50% | Val loss: 1.0128 | Val acc: 49.13% | LR: 0.000025
Epoch: 141 | Train loss: 0.9775 | Train acc: 51.29% | Val loss: 1.0124 | Val acc: 49.23% | LR: 0.000020
Epoch: 142 | Train loss: 0.9764 | Train acc: 51.40% | Val loss: 1.0123 | Val acc: 49.19% | LR: 0.000015
Epoch: 143 | Train loss: 0.9758 | Train acc: 51.49% | Val loss: 1.0123 | Val acc: 49.19% | LR: 0.000011
Epoch: 144 | Train loss: 0.9900 | Train acc: 50.50% | Val loss: 1.0123 | Val acc: 49.23% | LR: 0.000008
Epoch: 145 | Train loss: 0.9803 | Train acc: 51.30% | Val loss: 1.0122 | Val acc: 49.23% | LR: 0.000006
Epoch: 146 | Train loss: 0.9761 | Train acc: 51.40% | Val loss: 1.0121 | Val acc: 49.23% | LR: 0.000004
Epoch: 147 | Train loss: 0.9748 | Train acc: 51.58% | Val loss: 1.0122 | Val acc: 49.23% | LR: 0.000002
Epoch: 148 | Train loss: 0.9786 | Train acc: 51.30% | Val loss: 1.0122 | Val acc: 49.23% | LR: 0.000001
Epoch: 149 | Train loss: 0.9847 | Train acc: 50.94% | Val loss: 1.0122 | Val acc: 49.23% | LR: 0.000001

[I 2025-09-23 02:49:26,642] Trial 28 finished with value: 0.5347638010978699 and parameters: {'lr': 0.0026599914753217347, 'hidden_size': 114, 'dropout': 0.08663362065407848, 'weight_decay': 0.4900933821057213}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 0.9969 | Train acc: 50.56% | Val loss: 1.0326 | Val acc: 46.32% | LR: 0.001532
Epoch: 001 | Train loss: 0.9995 | Train acc: 51.22% | Val loss: 1.0188 | Val acc: 46.03% | LR: 0.001532
Epoch: 002 | Train loss: 0.9886 | Train acc: 50.95% | Val loss: 1.0317 | Val acc: 46.03% | LR: 0.001531
Epoch: 003 | Train loss: 0.9989 | Train acc: 49.88% | Val loss: 0.9899 | Val acc: 51.23% | LR: 0.001530
Epoch: 004 | Train loss: 0.9916 | Train acc: 51.12% | Val loss: 1.0030 | Val acc: 49.78% | LR: 0.001528
Epoch: 005 | Train loss: 0.9848 | Train acc: 51.20% | Val loss: 0.9867 | Val acc: 50.59% | LR: 0.001526
Epoch: 006 | Train loss: 0.9856 | Train acc: 51.55% | Val loss: 0.9915 | Val acc: 51.50% | LR: 0.001524
Epoch: 007 | Train loss: 0.9844 | Train acc: 51.12% | Val loss: 1.0019 | Val acc: 50.31% | LR: 0.001522
Epoch: 008 | Train loss: 0.9840 | Train acc: 51.18% | Val loss: 1.0101 | Val acc: 49.60% | LR: 0.001519
Epoch: 009 | Train loss: 0.9884 | Train acc: 50.91% | Val loss: 1.0074 | Val acc: 50.02% | LR: 0.001516
Epoch: 010 | Train loss: 0.9889 | Train acc: 50.94% | Val loss: 1.0183 | Val acc: 49.05% | LR: 0.001512
Epoch: 011 | Train loss: 0.9788 | Train acc: 51.55% | Val loss: 0.9982 | Val acc: 50.36% | LR: 0.001508
Epoch: 012 | Train loss: 0.9815 | Train acc: 51.33% | Val loss: 1.0047 | Val acc: 50.08% | LR: 0.001504
Epoch: 013 | Train loss: 0.9824 | Train acc: 51.21% | Val loss: 1.0309 | Val acc: 48.69% | LR: 0.001500
Epoch: 014 | Train loss: 0.9898 | Train acc: 50.71% | Val loss: 1.0575 | Val acc: 46.40% | LR: 0.001495
Epoch: 015 | Train loss: 0.9814 | Train acc: 51.21% | Val loss: 1.0292 | Val acc: 48.39% | LR: 0.001490
Epoch: 016 | Train loss: 0.9857 | Train acc: 51.19% | Val loss: 1.0400 | Val acc: 47.47% | LR: 0.001484
Epoch: 017 | Train loss: 0.9796 | Train acc: 51.39% | Val loss: 0.9819 | Val acc: 51.00% | LR: 0.001478
Epoch: 018 | Train loss: 0.9764 | Train acc: 51.41% | Val loss: 0.9947 | Val acc: 50.36% | LR: 0.001472
Epoch: 019 | Train loss: 0.9777 | Train acc: 51.58% | Val loss: 0.9976 | Val acc: 50.17% | LR: 0.001466
Epoch: 020 | Train loss: 0.9929 | Train acc: 50.58% | Val loss: 1.0342 | Val acc: 48.50% | LR: 0.001459
Epoch: 021 | Train loss: 0.9890 | Train acc: 51.09% | Val loss: 1.0154 | Val acc: 48.49% | LR: 0.001452
Epoch: 022 | Train loss: 0.9946 | Train acc: 49.88% | Val loss: 1.0303 | Val acc: 48.44% | LR: 0.001445
Epoch: 023 | Train loss: 0.9934 | Train acc: 50.62% | Val loss: 1.0068 | Val acc: 50.13% | LR: 0.001438
Epoch: 024 | Train loss: 0.9915 | Train acc: 50.11% | Val loss: 0.9907 | Val acc: 50.66% | LR: 0.001430
Epoch: 025 | Train loss: 0.9861 | Train acc: 50.87% | Val loss: 1.0252 | Val acc: 48.63% | LR: 0.001422
Epoch: 026 | Train loss: 0.9883 | Train acc: 50.99% | Val loss: 1.0248 | Val acc: 48.49% | LR: 0.001413
Epoch: 027 | Train loss: 0.9873 | Train acc: 51.14% | Val loss: 0.9959 | Val acc: 49.26% | LR: 0.001404
Epoch: 028 | Train loss: 0.9878 | Train acc: 50.85% | Val loss: 0.9886 | Val acc: 50.26% | LR: 0.001395
Epoch: 029 | Train loss: 0.9852 | Train acc: 51.20% | Val loss: 1.0010 | Val acc: 49.98% | LR: 0.001386
Epoch: 030 | Train loss: 0.9849 | Train acc: 51.07% | Val loss: 0.9872 | Val acc: 50.68% | LR: 0.001376
Epoch: 031 | Train loss: 0.9826 | Train acc: 51.23% | Val loss: 1.0008 | Val acc: 50.40% | LR: 0.001367
Epoch: 032 | Train loss: 0.9820 | Train acc: 51.29% | Val loss: 1.0011 | Val acc: 50.17% | LR: 0.001357
Epoch: 033 | Train loss: 0.9872 | Train acc: 50.58% | Val loss: 1.0003 | Val acc: 50.21% | LR: 0.001346
Epoch: 034 | Train loss: 0.9855 | Train acc: 50.99% | Val loss: 0.9997 | Val acc: 49.79% | LR: 0.001336
Epoch: 035 | Train loss: 0.9827 | Train acc: 51.35% | Val loss: 1.0114 | Val acc: 49.68% | LR: 0.001325
Epoch: 036 | Train loss: 0.9786 | Train acc: 51.48% | Val loss: 1.0015 | Val acc: 49.93% | LR: 0.001314
Epoch: 037 | Train loss: 0.9791 | Train acc: 51.17% | Val loss: 1.0212 | Val acc: 48.76% | LR: 0.001302
Epoch: 038 | Train loss: 0.9884 | Train acc: 50.78% | Val loss: 0.9980 | Val acc: 49.99% | LR: 0.001291
Epoch: 039 | Train loss: 0.9773 | Train acc: 51.45% | Val loss: 0.9909 | Val acc: 50.66% | LR: 0.001279
Epoch: 040 | Train loss: 0.9796 | Train acc: 51.37% | Val loss: 1.0092 | Val acc: 50.02% | LR: 0.001267
Epoch: 041 | Train loss: 0.9793 | Train acc: 51.35% | Val loss: 1.0063 | Val acc: 50.06% | LR: 0.001255
Epoch: 042 | Train loss: 0.9849 | Train acc: 50.86% | Val loss: 1.0006 | Val acc: 50.18% | LR: 0.001242
Epoch: 043 | Train loss: 0.9841 | Train acc: 50.92% | Val loss: 0.9976 | Val acc: 50.20% | LR: 0.001230
Epoch: 044 | Train loss: 0.9894 | Train acc: 50.64% | Val loss: 0.9960 | Val acc: 50.16% | LR: 0.001217
Epoch: 045 | Train loss: 0.9764 | Train acc: 51.45% | Val loss: 0.9914 | Val acc: 50.74% | LR: 0.001204
Epoch: 046 | Train loss: 0.9955 | Train acc: 50.15% | Val loss: 0.9938 | Val acc: 50.58% | LR: 0.001190
Epoch: 047 | Train loss: 0.9797 | Train acc: 51.28% | Val loss: 1.0074 | Val acc: 50.08% | LR: 0.001177
Epoch: 048 | Train loss: 0.9836 | Train acc: 51.10% | Val loss: 0.9796 | Val acc: 51.09% | LR: 0.001163
Epoch: 049 | Train loss: 0.9898 | Train acc: 50.69% | Val loss: 0.9846 | Val acc: 50.89% | LR: 0.001149
Epoch: 050 | Train loss: 0.9901 | Train acc: 50.76% | Val loss: 0.9903 | Val acc: 50.68% | LR: 0.001135
Epoch: 051 | Train loss: 0.9826 | Train acc: 50.97% | Val loss: 0.9865 | Val acc: 50.91% | LR: 0.001121
Epoch: 052 | Train loss: 0.9783 | Train acc: 51.59% | Val loss: 0.9897 | Val acc: 50.82% | LR: 0.001107
Epoch: 053 | Train loss: 0.9815 | Train acc: 51.15% | Val loss: 0.9923 | Val acc: 50.56% | LR: 0.001093
Epoch: 054 | Train loss: 0.9797 | Train acc: 51.40% | Val loss: 0.9879 | Val acc: 50.86% | LR: 0.001078
Epoch: 055 | Train loss: 0.9798 | Train acc: 51.29% | Val loss: 0.9913 | Val acc: 50.79% | LR: 0.001063
Epoch: 056 | Train loss: 1.1612 | Train acc: 50.84% | Val loss: 1.0369 | Val acc: 48.74% | LR: 0.001048
Epoch: 057 | Train loss: 0.9889 | Train acc: 51.01% | Val loss: 1.0320 | Val acc: 49.10% | LR: 0.001033
Epoch: 058 | Train loss: 0.9867 | Train acc: 51.06% | Val loss: 1.0583 | Val acc: 49.37% | LR: 0.001018
Epoch: 059 | Train loss: 0.9826 | Train acc: 51.24% | Val loss: 1.0454 | Val acc: 49.09% | LR: 0.001003
Epoch: 060 | Train loss: 0.9771 | Train acc: 51.76% | Val loss: 1.0285 | Val acc: 49.04% | LR: 0.000988
Epoch: 061 | Train loss: 0.9953 | Train acc: 50.61% | Val loss: 1.0137 | Val acc: 49.84% | LR: 0.000973
Epoch: 062 | Train loss: 0.9795 | Train acc: 51.45% | Val loss: 1.2885 | Val acc: 50.66% | LR: 0.000957
Epoch: 063 | Train loss: 0.9879 | Train acc: 50.95% | Val loss: 1.0122 | Val acc: 50.34% | LR: 0.000941
Epoch: 064 | Train loss: 0.9897 | Train acc: 50.76% | Val loss: 1.0068 | Val acc: 50.37% | LR: 0.000926
Epoch: 065 | Train loss: 0.9867 | Train acc: 50.88% | Val loss: 1.0219 | Val acc: 50.29% | LR: 0.000910
Epoch: 066 | Train loss: 0.9906 | Train acc: 50.94% | Val loss: 0.9999 | Val acc: 50.11% | LR: 0.000894
Epoch: 067 | Train loss: 0.9845 | Train acc: 51.10% | Val loss: 1.0106 | Val acc: 50.08% | LR: 0.000878
Epoch: 068 | Train loss: 0.9829 | Train acc: 51.28% | Val loss: 1.0255 | Val acc: 49.84% | LR: 0.000863
Epoch: 069 | Train loss: 0.9865 | Train acc: 51.24% | Val loss: 1.0057 | Val acc: 49.39% | LR: 0.000847
Epoch: 070 | Train loss: 0.9889 | Train acc: 50.94% | Val loss: 1.0146 | Val acc: 49.50% | LR: 0.000831
Epoch: 071 | Train loss: 0.9896 | Train acc: 50.83% | Val loss: 1.0048 | Val acc: 49.51% | LR: 0.000815
Epoch: 072 | Train loss: 1.0007 | Train acc: 50.89% | Val loss: 1.0216 | Val acc: 49.70% | LR: 0.000799
Epoch: 073 | Train loss: 0.9839 | Train acc: 51.15% | Val loss: 1.0298 | Val acc: 50.12% | LR: 0.000783
Epoch: 074 | Train loss: 0.9920 | Train acc: 50.54% | Val loss: 1.0093 | Val acc: 49.72% | LR: 0.000767
Epoch: 075 | Train loss: 0.9816 | Train acc: 51.25% | Val loss: 1.0331 | Val acc: 49.87% | LR: 0.000751
Epoch: 076 | Train loss: 0.9862 | Train acc: 51.14% | Val loss: 1.0008 | Val acc: 49.76% | LR: 0.000735
Epoch: 077 | Train loss: 0.9823 | Train acc: 51.19% | Val loss: 0.9994 | Val acc: 49.81% | LR: 0.000719
Epoch: 078 | Train loss: 0.9867 | Train acc: 50.90% | Val loss: 1.0146 | Val acc: 49.81% | LR: 0.000703
Epoch: 079 | Train loss: 0.9807 | Train acc: 51.44% | Val loss: 1.0231 | Val acc: 49.71% | LR: 0.000687
Epoch: 080 | Train loss: 0.9826 | Train acc: 51.03% | Val loss: 0.9848 | Val acc: 50.26% | LR: 0.000671
Epoch: 081 | Train loss: 0.9854 | Train acc: 51.07% | Val loss: 0.9866 | Val acc: 50.53% | LR: 0.000655
Epoch: 082 | Train loss: 0.9955 | Train acc: 50.89% | Val loss: 0.9866 | Val acc: 50.64% | LR: 0.000639
Epoch: 083 | Train loss: 0.9915 | Train acc: 50.80% | Val loss: 0.9881 | Val acc: 50.71% | LR: 0.000623
Epoch: 084 | Train loss: 0.9818 | Train acc: 51.13% | Val loss: 0.9874 | Val acc: 50.60% | LR: 0.000607
Epoch: 085 | Train loss: 0.9853 | Train acc: 50.94% | Val loss: 0.9896 | Val acc: 50.71% | LR: 0.000592
Epoch: 086 | Train loss: 0.9843 | Train acc: 50.92% | Val loss: 0.9913 | Val acc: 50.67% | LR: 0.000576
Epoch: 087 | Train loss: 0.9889 | Train acc: 50.66% | Val loss: 0.9957 | Val acc: 50.59% | LR: 0.000561
Epoch: 088 | Train loss: 0.9941 | Train acc: 50.43% | Val loss: 1.0132 | Val acc: 50.07% | LR: 0.000545
Epoch: 089 | Train loss: 0.9873 | Train acc: 50.94% | Val loss: 0.9860 | Val acc: 50.46% | LR: 0.000530
Epoch: 090 | Train loss: 0.9855 | Train acc: 50.94% | Val loss: 0.9793 | Val acc: 50.78% | LR: 0.000515
Epoch: 091 | Train loss: 0.9787 | Train acc: 51.28% | Val loss: 0.9820 | Val acc: 50.72% | LR: 0.000500
Epoch: 092 | Train loss: 0.9835 | Train acc: 51.04% | Val loss: 0.9847 | Val acc: 50.68% | LR: 0.000485
Epoch: 093 | Train loss: 0.9890 | Train acc: 50.77% | Val loss: 0.9886 | Val acc: 50.58% | LR: 0.000470
Epoch: 094 | Train loss: 0.9797 | Train acc: 51.25% | Val loss: 0.9965 | Val acc: 50.30% | LR: 0.000455
Epoch: 095 | Train loss: 0.9865 | Train acc: 50.60% | Val loss: 0.9988 | Val acc: 50.29% | LR: 0.000441
Epoch: 096 | Train loss: 0.9892 | Train acc: 50.85% | Val loss: 0.9952 | Val acc: 50.24% | LR: 0.000426
Epoch: 097 | Train loss: 0.9872 | Train acc: 50.74% | Val loss: 1.0033 | Val acc: 50.11% | LR: 0.000412
Epoch: 098 | Train loss: 0.9813 | Train acc: 51.07% | Val loss: 1.0080 | Val acc: 49.63% | LR: 0.000398
Epoch: 099 | Train loss: 0.9796 | Train acc: 51.30% | Val loss: 1.0089 | Val acc: 49.73% | LR: 0.000384
Epoch: 100 | Train loss: 0.9776 | Train acc: 51.45% | Val loss: 1.0158 | Val acc: 49.11% | LR: 0.000370
Epoch: 101 | Train loss: 0.9776 | Train acc: 51.34% | Val loss: 1.0210 | Val acc: 49.09% | LR: 0.000356
Epoch: 102 | Train loss: 0.9756 | Train acc: 51.54% | Val loss: 1.0127 | Val acc: 49.25% | LR: 0.000343
Epoch: 103 | Train loss: 0.9882 | Train acc: 50.59% | Val loss: 1.0168 | Val acc: 49.08% | LR: 0.000330
Epoch: 104 | Train loss: 0.9854 | Train acc: 50.94% | Val loss: 1.0132 | Val acc: 49.14% | LR: 0.000317
Epoch: 105 | Train loss: 0.9803 | Train acc: 51.17% | Val loss: 1.0092 | Val acc: 49.20% | LR: 0.000304
Epoch: 106 | Train loss: 0.9812 | Train acc: 51.09% | Val loss: 1.0143 | Val acc: 49.05% | LR: 0.000291
Epoch: 107 | Train loss: 0.9913 | Train acc: 50.40% | Val loss: 1.0172 | Val acc: 48.86% | LR: 0.000279
Epoch: 108 | Train loss: 0.9766 | Train acc: 51.45% | Val loss: 1.0153 | Val acc: 49.13% | LR: 0.000266
Epoch: 109 | Train loss: 0.9869 | Train acc: 50.79% | Val loss: 1.0194 | Val acc: 48.93% | LR: 0.000254
Epoch: 110 | Train loss: 0.9799 | Train acc: 51.24% | Val loss: 1.0167 | Val acc: 49.14% | LR: 0.000243
Epoch: 111 | Train loss: 0.9809 | Train acc: 51.18% | Val loss: 1.0183 | Val acc: 48.87% | LR: 0.000231
Epoch: 112 | Train loss: 0.9808 | Train acc: 51.17% | Val loss: 1.0210 | Val acc: 48.97% | LR: 0.000220
Epoch: 113 | Train loss: 0.9803 | Train acc: 51.10% | Val loss: 1.0196 | Val acc: 48.89% | LR: 0.000209
Epoch: 114 | Train loss: 0.9771 | Train acc: 51.35% | Val loss: 1.0187 | Val acc: 48.87% | LR: 0.000198
Epoch: 115 | Train loss: 0.9877 | Train acc: 50.73% | Val loss: 1.0194 | Val acc: 48.85% | LR: 0.000187
Epoch: 116 | Train loss: 0.9754 | Train acc: 51.46% | Val loss: 1.0235 | Val acc: 48.93% | LR: 0.000177
Epoch: 117 | Train loss: 0.9781 | Train acc: 51.27% | Val loss: 1.0208 | Val acc: 48.93% | LR: 0.000167
Epoch: 118 | Train loss: 0.9825 | Train acc: 51.02% | Val loss: 1.0224 | Val acc: 48.91% | LR: 0.000157
Epoch: 119 | Train loss: 0.9869 | Train acc: 50.67% | Val loss: 1.0200 | Val acc: 48.81% | LR: 0.000147
Epoch: 120 | Train loss: 0.9820 | Train acc: 50.93% | Val loss: 1.0205 | Val acc: 48.83% | LR: 0.000138
Epoch: 121 | Train loss: 0.9831 | Train acc: 51.02% | Val loss: 1.0188 | Val acc: 48.89% | LR: 0.000129
Epoch: 122 | Train loss: 0.9853 | Train acc: 50.85% | Val loss: 1.0170 | Val acc: 48.85% | LR: 0.000120
Epoch: 123 | Train loss: 0.9903 | Train acc: 50.48% | Val loss: 1.0196 | Val acc: 48.91% | LR: 0.000112
Epoch: 124 | Train loss: 0.9849 | Train acc: 50.85% | Val loss: 1.0201 | Val acc: 48.83% | LR: 0.000104
Epoch: 125 | Train loss: 0.9814 | Train acc: 51.12% | Val loss: 1.0195 | Val acc: 48.83% | LR: 0.000096
Epoch: 126 | Train loss: 0.9751 | Train acc: 51.38% | Val loss: 1.0191 | Val acc: 48.89% | LR: 0.000088
Epoch: 127 | Train loss: 0.9936 | Train acc: 50.32% | Val loss: 1.0197 | Val acc: 48.89% | LR: 0.000081
Epoch: 128 | Train loss: 0.9800 | Train acc: 51.20% | Val loss: 1.0195 | Val acc: 48.83% | LR: 0.000074
Epoch: 129 | Train loss: 0.9741 | Train acc: 51.47% | Val loss: 1.0198 | Val acc: 48.85% | LR: 0.000067
Epoch: 130 | Train loss: 0.9785 | Train acc: 51.20% | Val loss: 1.0206 | Val acc: 48.84% | LR: 0.000061
Epoch: 131 | Train loss: 0.9794 | Train acc: 51.20% | Val loss: 1.0209 | Val acc: 48.82% | LR: 0.000055
Epoch: 132 | Train loss: 0.9764 | Train acc: 51.30% | Val loss: 1.0210 | Val acc: 48.87% | LR: 0.000049
Epoch: 133 | Train loss: 0.9759 | Train acc: 51.39% | Val loss: 1.0210 | Val acc: 48.84% | LR: 0.000044
Epoch: 134 | Train loss: 0.9861 | Train acc: 50.76% | Val loss: 1.0207 | Val acc: 48.84% | LR: 0.000038
Epoch: 135 | Train loss: 0.9845 | Train acc: 50.87% | Val loss: 1.0210 | Val acc: 48.89% | LR: 0.000034
Epoch: 136 | Train loss: 0.9842 | Train acc: 50.86% | Val loss: 1.0199 | Val acc: 48.89% | LR: 0.000029
Epoch: 137 | Train loss: 0.9750 | Train acc: 51.48% | Val loss: 1.0588 | Val acc: 48.88% | LR: 0.000025
Epoch: 138 | Train loss: 0.9739 | Train acc: 51.48% | Val loss: 1.0203 | Val acc: 48.85% | LR: 0.000021
Epoch: 139 | Train loss: 0.9780 | Train acc: 51.22% | Val loss: 1.0203 | Val acc: 48.95% | LR: 0.000018
Epoch: 140 | Train loss: 0.9845 | Train acc: 50.87% | Val loss: 1.0201 | Val acc: 48.97% | LR: 0.000015
Epoch: 141 | Train loss: 0.9714 | Train acc: 51.66% | Val loss: 1.0202 | Val acc: 48.97% | LR: 0.000012
Epoch: 142 | Train loss: 0.9777 | Train acc: 51.22% | Val loss: 1.0204 | Val acc: 48.97% | LR: 0.000009
Epoch: 143 | Train loss: 0.9767 | Train acc: 51.31% | Val loss: 1.0205 | Val acc: 48.97% | LR: 0.000007
Epoch: 144 | Train loss: 0.9746 | Train acc: 51.48% | Val loss: 1.0206 | Val acc: 48.97% | LR: 0.000005
Epoch: 145 | Train loss: 0.9796 | Train acc: 51.23% | Val loss: 1.0206 | Val acc: 48.97% | LR: 0.000004
Epoch: 146 | Train loss: 0.9808 | Train acc: 51.12% | Val loss: 1.0205 | Val acc: 48.97% | LR: 0.000003
Epoch: 147 | Train loss: 0.9809 | Train acc: 51.04% | Val loss: 1.0205 | Val acc: 48.97% | LR: 0.000002
Epoch: 148 | Train loss: 0.9706 | Train acc: 51.75% | Val loss: 1.0205 | Val acc: 48.97% | LR: 0.000001
Epoch: 149 | Train loss: 0.9876 | Train acc: 50.60% | Val loss: 1.0205 | Val acc: 48.95% | LR: 0.000001

[I 2025-09-23 02:51:49,552] Trial 29 finished with value: 0.5150150835514069 and parameters: {'lr': 0.0015322390255295163, 'hidden_size': 200, 'dropout': 0.20709929550233697, 'weight_decay': 0.26152083057196807}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.0252 | Train acc: 49.70% | Val loss: 0.9991 | Val acc: 53.41% | LR: 0.000543
Epoch: 001 | Train loss: 0.9967 | Train acc: 50.37% | Val loss: 0.9972 | Val acc: 54.20% | LR: 0.000543
Epoch: 002 | Train loss: 1.0199 | Train acc: 50.77% | Val loss: 0.9990 | Val acc: 50.21% | LR: 0.000543
Epoch: 003 | Train loss: 0.9856 | Train acc: 51.08% | Val loss: 1.0017 | Val acc: 48.38% | LR: 0.000542
Epoch: 004 | Train loss: 0.9891 | Train acc: 51.02% | Val loss: 1.0050 | Val acc: 48.37% | LR: 0.000542
Epoch: 005 | Train loss: 0.9940 | Train acc: 50.76% | Val loss: 1.0041 | Val acc: 49.58% | LR: 0.000541
Epoch: 006 | Train loss: 0.9891 | Train acc: 51.09% | Val loss: 0.9971 | Val acc: 49.91% | LR: 0.000540
Epoch: 007 | Train loss: 0.9930 | Train acc: 50.46% | Val loss: 1.0005 | Val acc: 49.70% | LR: 0.000539
Epoch: 008 | Train loss: 0.9881 | Train acc: 50.91% | Val loss: 1.0008 | Val acc: 49.94% | LR: 0.000538
Epoch: 009 | Train loss: 0.9882 | Train acc: 50.87% | Val loss: 1.0067 | Val acc: 49.41% | LR: 0.000537
Epoch: 010 | Train loss: 0.9881 | Train acc: 50.94% | Val loss: 1.0176 | Val acc: 47.81% | LR: 0.000536
Epoch: 011 | Train loss: 0.9883 | Train acc: 51.06% | Val loss: 1.0027 | Val acc: 49.56% | LR: 0.000535
Epoch: 012 | Train loss: 0.9888 | Train acc: 50.79% | Val loss: 1.0180 | Val acc: 48.21% | LR: 0.000533
Epoch: 013 | Train loss: 0.9939 | Train acc: 50.75% | Val loss: 0.9933 | Val acc: 50.18% | LR: 0.000532
Epoch: 014 | Train loss: 0.9843 | Train acc: 50.96% | Val loss: 0.9788 | Val acc: 51.60% | LR: 0.000530
Epoch: 015 | Train loss: 0.9841 | Train acc: 51.04% | Val loss: 0.9901 | Val acc: 50.12% | LR: 0.000528
Epoch: 016 | Train loss: 0.9923 | Train acc: 50.53% | Val loss: 0.9846 | Val acc: 50.56% | LR: 0.000526
Epoch: 017 | Train loss: 0.9843 | Train acc: 51.38% | Val loss: 1.0123 | Val acc: 49.62% | LR: 0.000524
Epoch: 018 | Train loss: 0.9774 | Train acc: 51.68% | Val loss: 1.0112 | Val acc: 49.60% | LR: 0.000522
Epoch: 019 | Train loss: 0.9953 | Train acc: 50.26% | Val loss: 0.9872 | Val acc: 50.57% | LR: 0.000520
Epoch: 020 | Train loss: 0.9836 | Train acc: 51.18% | Val loss: 1.0065 | Val acc: 49.64% | LR: 0.000517
Epoch: 021 | Train loss: 0.9774 | Train acc: 51.57% | Val loss: 1.0110 | Val acc: 49.30% | LR: 0.000515
Epoch: 022 | Train loss: 0.9865 | Train acc: 50.75% | Val loss: 1.0312 | Val acc: 47.80% | LR: 0.000512
Epoch: 023 | Train loss: 0.9837 | Train acc: 51.26% | Val loss: 0.9899 | Val acc: 50.10% | LR: 0.000510
Epoch: 024 | Train loss: 0.9836 | Train acc: 51.06% | Val loss: 0.9696 | Val acc: 51.56% | LR: 0.000507
Epoch: 025 | Train loss: 0.9826 | Train acc: 51.14% | Val loss: 1.0510 | Val acc: 47.01% | LR: 0.000504
Epoch: 026 | Train loss: 0.9858 | Train acc: 50.69% | Val loss: 1.0064 | Val acc: 49.69% | LR: 0.000501
Epoch: 027 | Train loss: 0.9751 | Train acc: 51.53% | Val loss: 1.0349 | Val acc: 48.09% | LR: 0.000498
Epoch: 028 | Train loss: 0.9912 | Train acc: 50.58% | Val loss: 1.0001 | Val acc: 49.82% | LR: 0.000495
Epoch: 029 | Train loss: 0.9819 | Train acc: 51.21% | Val loss: 1.0177 | Val acc: 48.74% | LR: 0.000491
Epoch: 030 | Train loss: 0.9835 | Train acc: 50.96% | Val loss: 1.0202 | Val acc: 48.59% | LR: 0.000488
Epoch: 031 | Train loss: 0.9868 | Train acc: 50.86% | Val loss: 1.0278 | Val acc: 48.25% | LR: 0.000484
Epoch: 032 | Train loss: 0.9824 | Train acc: 51.08% | Val loss: 1.0083 | Val acc: 49.44% | LR: 0.000481
Epoch: 033 | Train loss: 0.9798 | Train acc: 51.17% | Val loss: 0.9912 | Val acc: 50.47% | LR: 0.000477
Epoch: 034 | Train loss: 0.9848 | Train acc: 50.94% | Val loss: 0.9790 | Val acc: 51.40% | LR: 0.000473
Epoch: 035 | Train loss: 0.9855 | Train acc: 50.94% | Val loss: 1.0192 | Val acc: 49.22% | LR: 0.000470
Epoch: 036 | Train loss: 0.9848 | Train acc: 50.84% | Val loss: 1.0042 | Val acc: 49.80% | LR: 0.000466
Epoch: 037 | Train loss: 0.9836 | Train acc: 51.06% | Val loss: 1.0042 | Val acc: 49.84% | LR: 0.000462
Epoch: 038 | Train loss: 0.9800 | Train acc: 50.98% | Val loss: 1.0041 | Val acc: 49.68% | LR: 0.000458
Epoch: 039 | Train loss: 0.9752 | Train acc: 51.56% | Val loss: 1.0338 | Val acc: 48.36% | LR: 0.000453
Epoch: 040 | Train loss: 0.9823 | Train acc: 51.01% | Val loss: 0.9974 | Val acc: 50.13% | LR: 0.000449
Epoch: 041 | Train loss: 0.9876 | Train acc: 50.63% | Val loss: 1.0214 | Val acc: 48.93% | LR: 0.000445
Epoch: 042 | Train loss: 0.9795 | Train acc: 51.44% | Val loss: 1.0169 | Val acc: 49.07% | LR: 0.000440
Epoch: 043 | Train loss: 0.9804 | Train acc: 51.16% | Val loss: 1.0069 | Val acc: 49.76% | LR: 0.000436
Epoch: 044 | Train loss: 0.9747 | Train acc: 51.46% | Val loss: 1.0069 | Val acc: 49.45% | LR: 0.000431
Epoch: 045 | Train loss: 0.9834 | Train acc: 50.86% | Val loss: 0.9801 | Val acc: 51.27% | LR: 0.000427
Epoch: 046 | Train loss: 0.9781 | Train acc: 51.33% | Val loss: 0.9990 | Val acc: 49.91% | LR: 0.000422
Epoch: 047 | Train loss: 0.9827 | Train acc: 50.82% | Val loss: 1.0235 | Val acc: 48.76% | LR: 0.000417
Epoch: 048 | Train loss: 0.9860 | Train acc: 50.81% | Val loss: 0.9965 | Val acc: 50.04% | LR: 0.000412
Epoch: 049 | Train loss: 0.9752 | Train acc: 51.76% | Val loss: 0.9926 | Val acc: 50.65% | LR: 0.000408
Epoch: 050 | Train loss: 0.9825 | Train acc: 51.00% | Val loss: 1.0308 | Val acc: 48.31% | LR: 0.000403
Epoch: 051 | Train loss: 0.9815 | Train acc: 51.10% | Val loss: 0.9935 | Val acc: 50.48% | LR: 0.000398
Epoch: 052 | Train loss: 0.9812 | Train acc: 51.05% | Val loss: 1.0331 | Val acc: 48.51% | LR: 0.000393
Epoch: 053 | Train loss: 0.9825 | Train acc: 50.90% | Val loss: 0.9917 | Val acc: 50.73% | LR: 0.000387
Epoch: 054 | Train loss: 0.9787 | Train acc: 51.47% | Val loss: 0.9984 | Val acc: 50.19% | LR: 0.000382
Epoch: 055 | Train loss: 0.9792 | Train acc: 51.16% | Val loss: 1.0315 | Val acc: 48.28% | LR: 0.000377
Epoch: 056 | Train loss: 0.9786 | Train acc: 51.23% | Val loss: 1.0223 | Val acc: 48.86% | LR: 0.000372
Epoch: 057 | Train loss: 0.9811 | Train acc: 51.23% | Val loss: 1.0692 | Val acc: 48.31% | LR: 0.000367
Epoch: 058 | Train loss: 0.9835 | Train acc: 51.08% | Val loss: 1.0024 | Val acc: 49.92% | LR: 0.000361
Epoch: 059 | Train loss: 0.9858 | Train acc: 50.84% | Val loss: 0.9945 | Val acc: 50.31% | LR: 0.000356
Epoch: 060 | Train loss: 0.9835 | Train acc: 51.02% | Val loss: 1.0036 | Val acc: 49.72% | LR: 0.000350
Epoch: 061 | Train loss: 0.9815 | Train acc: 51.21% | Val loss: 1.0106 | Val acc: 49.12% | LR: 0.000345
Epoch: 062 | Train loss: 0.9812 | Train acc: 51.34% | Val loss: 1.0140 | Val acc: 49.15% | LR: 0.000339
Epoch: 063 | Train loss: 0.9778 | Train acc: 51.31% | Val loss: 0.9767 | Val acc: 51.19% | LR: 0.000334
Epoch: 064 | Train loss: 0.9918 | Train acc: 50.38% | Val loss: 0.9899 | Val acc: 50.60% | LR: 0.000328
Epoch: 065 | Train loss: 0.9894 | Train acc: 50.73% | Val loss: 1.0290 | Val acc: 48.34% | LR: 0.000323
Epoch: 066 | Train loss: 0.9942 | Train acc: 50.38% | Val loss: 1.0720 | Val acc: 46.05% | LR: 0.000317
Epoch: 067 | Train loss: 0.9944 | Train acc: 50.57% | Val loss: 1.0643 | Val acc: 46.50% | LR: 0.000312
Epoch: 068 | Train loss: 0.9940 | Train acc: 50.36% | Val loss: 1.0379 | Val acc: 47.76% | LR: 0.000306
Epoch: 069 | Train loss: 0.9943 | Train acc: 50.38% | Val loss: 1.0525 | Val acc: 46.73% | LR: 0.000300
Epoch: 070 | Train loss: 0.9902 | Train acc: 50.83% | Val loss: 1.0151 | Val acc: 46.86% | LR: 0.000295
Epoch: 071 | Train loss: 0.9888 | Train acc: 50.69% | Val loss: 1.1241 | Val acc: 47.60% | LR: 0.000289
Epoch: 072 | Train loss: 0.9904 | Train acc: 50.72% | Val loss: 1.0143 | Val acc: 46.83% | LR: 0.000283
Epoch: 073 | Train loss: 0.9817 | Train acc: 50.99% | Val loss: 1.0112 | Val acc: 46.68% | LR: 0.000278
Epoch: 074 | Train loss: 0.9947 | Train acc: 50.45% | Val loss: 1.0091 | Val acc: 46.90% | LR: 0.000272
Epoch: 075 | Train loss: 0.9955 | Train acc: 50.27% | Val loss: 1.0226 | Val acc: 46.36% | LR: 0.000266
Epoch: 076 | Train loss: 0.9873 | Train acc: 50.65% | Val loss: 1.0156 | Val acc: 47.19% | LR: 0.000261
Epoch: 077 | Train loss: 0.9970 | Train acc: 50.35% | Val loss: 1.0181 | Val acc: 47.96% | LR: 0.000255
Epoch: 078 | Train loss: 0.9904 | Train acc: 50.84% | Val loss: 1.0027 | Val acc: 50.08% | LR: 0.000249
Epoch: 079 | Train loss: 0.9868 | Train acc: 51.08% | Val loss: 1.0208 | Val acc: 48.89% | LR: 0.000244
Epoch: 080 | Train loss: 0.9850 | Train acc: 51.27% | Val loss: 0.9970 | Val acc: 52.00% | LR: 0.000238
Epoch: 081 | Train loss: 0.9944 | Train acc: 50.65% | Val loss: 1.0241 | Val acc: 49.96% | LR: 0.000232
Epoch: 082 | Train loss: 0.9779 | Train acc: 51.66% | Val loss: 1.0330 | Val acc: 48.64% | LR: 0.000227
Epoch: 083 | Train loss: 0.9814 | Train acc: 51.35% | Val loss: 1.0430 | Val acc: 47.74% | LR: 0.000221
Epoch: 084 | Train loss: 0.9865 | Train acc: 51.00% | Val loss: 1.0573 | Val acc: 46.01% | LR: 0.000216
Epoch: 085 | Train loss: 0.9840 | Train acc: 51.03% | Val loss: 1.0394 | Val acc: 47.50% | LR: 0.000210
Epoch: 086 | Train loss: 0.9836 | Train acc: 50.96% | Val loss: 1.0653 | Val acc: 48.23% | LR: 0.000205
Epoch: 087 | Train loss: 0.9852 | Train acc: 51.15% | Val loss: 1.0308 | Val acc: 48.58% | LR: 0.000199
Epoch: 088 | Train loss: 0.9810 | Train acc: 51.29% | Val loss: 1.0262 | Val acc: 48.86% | LR: 0.000194
Epoch: 089 | Train loss: 0.9831 | Train acc: 51.11% | Val loss: 1.0496 | Val acc: 47.42% | LR: 0.000188
Epoch: 090 | Train loss: 0.9831 | Train acc: 51.04% | Val loss: 1.0455 | Val acc: 47.63% | LR: 0.000183
Epoch: 091 | Train loss: 0.9824 | Train acc: 51.08% | Val loss: 1.0343 | Val acc: 47.95% | LR: 0.000178
Epoch: 092 | Train loss: 0.9814 | Train acc: 51.14% | Val loss: 1.0506 | Val acc: 46.73% | LR: 0.000172
Epoch: 093 | Train loss: 0.9870 | Train acc: 50.76% | Val loss: 1.0602 | Val acc: 46.09% | LR: 0.000167
Epoch: 094 | Train loss: 0.9919 | Train acc: 50.42% | Val loss: 1.0578 | Val acc: 46.01% | LR: 0.000162
Epoch: 095 | Train loss: 0.9840 | Train acc: 51.10% | Val loss: 1.0475 | Val acc: 46.24% | LR: 0.000157
Epoch: 096 | Train loss: 0.9902 | Train acc: 50.68% | Val loss: 1.0404 | Val acc: 47.67% | LR: 0.000152
Epoch: 097 | Train loss: 0.9880 | Train acc: 50.88% | Val loss: 1.0399 | Val acc: 47.58% | LR: 0.000146
Epoch: 098 | Train loss: 0.9846 | Train acc: 51.00% | Val loss: 1.0352 | Val acc: 47.91% | LR: 0.000141
Epoch: 099 | Train loss: 0.9807 | Train acc: 51.21% | Val loss: 1.0236 | Val acc: 48.52% | LR: 0.000137
Epoch: 100 | Train loss: 0.9756 | Train acc: 51.64% | Val loss: 1.0304 | Val acc: 49.55% | LR: 0.000132
Epoch: 101 | Train loss: 0.9816 | Train acc: 51.23% | Val loss: 1.0244 | Val acc: 48.72% | LR: 0.000127
Epoch: 102 | Train loss: 0.9870 | Train acc: 50.85% | Val loss: 1.0148 | Val acc: 49.35% | LR: 0.000122
Epoch: 103 | Train loss: 0.9731 | Train acc: 51.65% | Val loss: 1.0138 | Val acc: 49.44% | LR: 0.000117
Epoch: 104 | Train loss: 0.9751 | Train acc: 51.57% | Val loss: 1.0216 | Val acc: 49.59% | LR: 0.000113
Epoch: 105 | Train loss: 0.9840 | Train acc: 50.94% | Val loss: 1.0157 | Val acc: 49.58% | LR: 0.000108
Epoch: 106 | Train loss: 0.9795 | Train acc: 51.19% | Val loss: 1.0094 | Val acc: 49.41% | LR: 0.000104
Epoch: 107 | Train loss: 0.9853 | Train acc: 50.77% | Val loss: 1.0094 | Val acc: 49.50% | LR: 0.000099
Epoch: 108 | Train loss: 0.9810 | Train acc: 51.23% | Val loss: 1.0107 | Val acc: 49.42% | LR: 0.000095
Epoch: 109 | Train loss: 0.9913 | Train acc: 50.44% | Val loss: 1.0672 | Val acc: 49.70% | LR: 0.000091
Epoch: 110 | Train loss: 0.9792 | Train acc: 51.12% | Val loss: 1.0101 | Val acc: 49.57% | LR: 0.000087
Epoch: 111 | Train loss: 0.9743 | Train acc: 51.41% | Val loss: 1.0329 | Val acc: 49.19% | LR: 0.000082
Epoch: 112 | Train loss: 0.9807 | Train acc: 51.22% | Val loss: 1.0124 | Val acc: 49.37% | LR: 0.000078
Epoch: 113 | Train loss: 0.9790 | Train acc: 51.25% | Val loss: 1.0138 | Val acc: 49.29% | LR: 0.000074
Epoch: 114 | Train loss: 0.9843 | Train acc: 50.87% | Val loss: 1.0170 | Val acc: 49.35% | LR: 0.000071
Epoch: 115 | Train loss: 0.9727 | Train acc: 51.77% | Val loss: 1.0175 | Val acc: 49.01% | LR: 0.000067
Epoch: 116 | Train loss: 0.9809 | Train acc: 50.88% | Val loss: 1.0139 | Val acc: 49.45% | LR: 0.000063
Epoch: 117 | Train loss: 0.9786 | Train acc: 51.31% | Val loss: 1.0118 | Val acc: 49.41% | LR: 0.000060
Epoch: 118 | Train loss: 0.9865 | Train acc: 50.71% | Val loss: 1.0129 | Val acc: 49.33% | LR: 0.000056
Epoch: 119 | Train loss: 0.9731 | Train acc: 51.66% | Val loss: 1.0125 | Val acc: 49.33% | LR: 0.000053
Epoch: 120 | Train loss: 0.9812 | Train acc: 51.14% | Val loss: 1.0129 | Val acc: 49.29% | LR: 0.000049
Epoch: 121 | Train loss: 0.9771 | Train acc: 51.32% | Val loss: 1.0179 | Val acc: 48.89% | LR: 0.000046
Epoch: 122 | Train loss: 0.9755 | Train acc: 51.60% | Val loss: 1.0151 | Val acc: 49.07% | LR: 0.000043
Epoch: 123 | Train loss: 0.9803 | Train acc: 51.05% | Val loss: 1.0935 | Val acc: 48.96% | LR: 0.000040
Epoch: 124 | Train loss: 0.9704 | Train acc: 51.87% | Val loss: 1.0146 | Val acc: 49.03% | LR: 0.000037
Epoch: 125 | Train loss: 0.9818 | Train acc: 51.16% | Val loss: 1.0413 | Val acc: 48.88% | LR: 0.000035
Epoch: 126 | Train loss: 0.9801 | Train acc: 51.24% | Val loss: 1.0113 | Val acc: 49.27% | LR: 0.000032
Epoch: 127 | Train loss: 0.9831 | Train acc: 50.96% | Val loss: 1.0504 | Val acc: 48.98% | LR: 0.000029
Epoch: 128 | Train loss: 0.9900 | Train acc: 50.53% | Val loss: 1.0153 | Val acc: 48.98% | LR: 0.000027
Epoch: 129 | Train loss: 0.9711 | Train acc: 51.70% | Val loss: 1.0130 | Val acc: 49.06% | LR: 0.000024
Epoch: 130 | Train loss: 0.9829 | Train acc: 50.98% | Val loss: 1.0146 | Val acc: 48.96% | LR: 0.000022
Epoch: 131 | Train loss: 0.9752 | Train acc: 51.50% | Val loss: 1.0133 | Val acc: 49.04% | LR: 0.000020
Epoch: 132 | Train loss: 0.9786 | Train acc: 51.24% | Val loss: 1.0145 | Val acc: 48.90% | LR: 0.000018
Epoch: 133 | Train loss: 0.9840 | Train acc: 50.96% | Val loss: 1.0259 | Val acc: 48.97% | LR: 0.000016
Epoch: 134 | Train loss: 0.9815 | Train acc: 51.16% | Val loss: 1.0222 | Val acc: 48.92% | LR: 0.000014
Epoch: 135 | Train loss: 0.9816 | Train acc: 51.14% | Val loss: 1.0229 | Val acc: 48.97% | LR: 0.000013
Epoch: 136 | Train loss: 0.9698 | Train acc: 51.77% | Val loss: 1.0167 | Val acc: 48.96% | LR: 0.000011
Epoch: 137 | Train loss: 0.9867 | Train acc: 50.61% | Val loss: 1.0170 | Val acc: 49.04% | LR: 0.000010
Epoch: 138 | Train loss: 0.9810 | Train acc: 51.14% | Val loss: 1.0167 | Val acc: 49.10% | LR: 0.000008
Epoch: 139 | Train loss: 0.9723 | Train acc: 51.68% | Val loss: 1.0220 | Val acc: 48.98% | LR: 0.000007
Epoch: 140 | Train loss: 0.9732 | Train acc: 51.59% | Val loss: 1.0174 | Val acc: 49.06% | LR: 0.000006
Epoch: 141 | Train loss: 0.9767 | Train acc: 51.41% | Val loss: 1.0198 | Val acc: 49.00% | LR: 0.000005
Epoch: 142 | Train loss: 0.9752 | Train acc: 51.32% | Val loss: 1.0167 | Val acc: 49.02% | LR: 0.000004
Epoch: 143 | Train loss: 0.9903 | Train acc: 50.53% | Val loss: 1.0233 | Val acc: 49.02% | LR: 0.000003
Epoch: 144 | Train loss: 0.9849 | Train acc: 50.88% | Val loss: 1.0201 | Val acc: 49.02% | LR: 0.000002
Epoch: 145 | Train loss: 0.9841 | Train acc: 50.88% | Val loss: 1.0158 | Val acc: 49.00% | LR: 0.000002
Epoch: 146 | Train loss: 0.9797 | Train acc: 51.14% | Val loss: 1.0168 | Val acc: 48.98% | LR: 0.000002
Epoch: 147 | Train loss: 0.9802 | Train acc: 51.15% | Val loss: 1.0176 | Val acc: 49.00% | LR: 0.000001
Epoch: 148 | Train loss: 0.9805 | Train acc: 51.06% | Val loss: 1.0222 | Val acc: 49.00% | LR: 0.000001
Epoch: 149 | Train loss: 0.9716 | Train acc: 51.67% | Val loss: 1.0168 | Val acc: 49.00% | LR: 0.000001

[I 2025-09-23 02:54:02,312] Trial 30 finished with value: 0.5419838547706604 and parameters: {'lr': 0.0005431179512618696, 'hidden_size': 193, 'dropout': 0.23636887806118756, 'weight_decay': 0.3379850602437091}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.0014 | Train acc: 50.57% | Val loss: 0.9873 | Val acc: 53.28% | LR: 0.006791
Epoch: 001 | Train loss: 1.0244 | Train acc: 49.80% | Val loss: 1.0304 | Val acc: 45.95% | LR: 0.006789
Epoch: 002 | Train loss: 1.0015 | Train acc: 50.52% | Val loss: 1.0132 | Val acc: 46.39% | LR: 0.006785
Epoch: 003 | Train loss: 1.0051 | Train acc: 50.17% | Val loss: 1.0440 | Val acc: 45.95% | LR: 0.006780
Epoch: 004 | Train loss: 1.0135 | Train acc: 49.70% | Val loss: 1.0037 | Val acc: 48.65% | LR: 0.006773
Epoch: 005 | Train loss: 0.9993 | Train acc: 50.89% | Val loss: 1.0277 | Val acc: 46.21% | LR: 0.006765
Epoch: 006 | Train loss: 1.0067 | Train acc: 50.05% | Val loss: 1.0099 | Val acc: 47.84% | LR: 0.006756
Epoch: 007 | Train loss: 0.9943 | Train acc: 50.91% | Val loss: 0.9747 | Val acc: 53.47% | LR: 0.006745
Epoch: 008 | Train loss: 1.0081 | Train acc: 50.74% | Val loss: 0.9679 | Val acc: 52.00% | LR: 0.006732
Epoch: 009 | Train loss: 0.9994 | Train acc: 51.08% | Val loss: 1.0351 | Val acc: 45.95% | LR: 0.006718
Epoch: 010 | Train loss: 1.0048 | Train acc: 51.05% | Val loss: 1.0319 | Val acc: 45.95% | LR: 0.006702
Epoch: 011 | Train loss: 1.0097 | Train acc: 50.23% | Val loss: 0.9763 | Val acc: 54.02% | LR: 0.006685
Epoch: 012 | Train loss: 1.0079 | Train acc: 49.95% | Val loss: 0.9931 | Val acc: 50.35% | LR: 0.006667
Epoch: 013 | Train loss: 0.9939 | Train acc: 50.69% | Val loss: 0.9660 | Val acc: 52.02% | LR: 0.006647
Epoch: 014 | Train loss: 1.0007 | Train acc: 50.45% | Val loss: 0.9776 | Val acc: 52.37% | LR: 0.006626
Epoch: 015 | Train loss: 0.9980 | Train acc: 50.46% | Val loss: 0.9789 | Val acc: 52.83% | LR: 0.006603
Epoch: 016 | Train loss: 0.9918 | Train acc: 50.92% | Val loss: 1.0014 | Val acc: 49.60% | LR: 0.006579
Epoch: 017 | Train loss: 1.0117 | Train acc: 50.95% | Val loss: 1.0571 | Val acc: 45.95% | LR: 0.006554
Epoch: 018 | Train loss: 1.0365 | Train acc: 49.57% | Val loss: 1.0049 | Val acc: 45.95% | LR: 0.006527
Epoch: 019 | Train loss: 1.0063 | Train acc: 50.20% | Val loss: 0.9491 | Val acc: 54.05% | LR: 0.006499
Epoch: 020 | Train loss: 1.0236 | Train acc: 49.96% | Val loss: 0.9559 | Val acc: 54.05% | LR: 0.006469
Epoch: 021 | Train loss: 1.0128 | Train acc: 49.49% | Val loss: 0.9578 | Val acc: 54.05% | LR: 0.006438
Epoch: 022 | Train loss: 1.0121 | Train acc: 49.56% | Val loss: 1.0204 | Val acc: 45.95% | LR: 0.006406
Epoch: 023 | Train loss: 0.9974 | Train acc: 50.79% | Val loss: 0.9605 | Val acc: 54.05% | LR: 0.006372
Epoch: 024 | Train loss: 1.0065 | Train acc: 49.43% | Val loss: 1.0001 | Val acc: 49.61% | LR: 0.006337
Epoch: 025 | Train loss: 0.9978 | Train acc: 50.31% | Val loss: 0.9974 | Val acc: 49.04% | LR: 0.006301
Epoch: 026 | Train loss: 0.9967 | Train acc: 50.32% | Val loss: 1.0169 | Val acc: 46.19% | LR: 0.006263
Epoch: 027 | Train loss: 0.9958 | Train acc: 51.30% | Val loss: 0.9996 | Val acc: 50.36% | LR: 0.006225
Epoch: 028 | Train loss: 1.0021 | Train acc: 50.67% | Val loss: 0.9689 | Val acc: 54.22% | LR: 0.006185
Epoch: 029 | Train loss: 1.1385 | Train acc: 50.15% | Val loss: 1.0582 | Val acc: 48.77% | LR: 0.006144
Epoch: 030 | Train loss: 0.9941 | Train acc: 51.21% | Val loss: 1.0011 | Val acc: 50.56% | LR: 0.006101
Epoch: 031 | Train loss: 1.0043 | Train acc: 50.05% | Val loss: 1.0138 | Val acc: 50.10% | LR: 0.006058
Epoch: 032 | Train loss: 1.0055 | Train acc: 50.15% | Val loss: 1.0025 | Val acc: 51.23% | LR: 0.006013
Epoch: 033 | Train loss: 1.0056 | Train acc: 49.94% | Val loss: 0.9716 | Val acc: 50.31% | LR: 0.005967
Epoch: 034 | Train loss: 0.9963 | Train acc: 50.33% | Val loss: 0.9654 | Val acc: 50.63% | LR: 0.005920
Epoch: 035 | Train loss: 0.9996 | Train acc: 50.63% | Val loss: 0.9849 | Val acc: 50.95% | LR: 0.005872
Epoch: 036 | Train loss: 0.9925 | Train acc: 50.99% | Val loss: 0.9839 | Val acc: 51.95% | LR: 0.005823
Epoch: 037 | Train loss: 0.9951 | Train acc: 50.48% | Val loss: 0.9722 | Val acc: 52.81% | LR: 0.005772
Epoch: 038 | Train loss: 0.9963 | Train acc: 50.53% | Val loss: 0.9834 | Val acc: 52.79% | LR: 0.005721
Epoch: 039 | Train loss: 0.9957 | Train acc: 50.71% | Val loss: 0.9911 | Val acc: 50.65% | LR: 0.005669
Epoch: 040 | Train loss: 1.0064 | Train acc: 49.71% | Val loss: 0.9869 | Val acc: 51.19% | LR: 0.005615
Epoch: 041 | Train loss: 0.9955 | Train acc: 50.83% | Val loss: 0.9778 | Val acc: 51.51% | LR: 0.005561
Epoch: 042 | Train loss: 0.9967 | Train acc: 51.05% | Val loss: 0.9878 | Val acc: 51.42% | LR: 0.005506
Epoch: 043 | Train loss: 0.9957 | Train acc: 50.53% | Val loss: 0.9885 | Val acc: 51.03% | LR: 0.005449
Epoch: 044 | Train loss: 0.9951 | Train acc: 51.14% | Val loss: 0.9885 | Val acc: 50.66% | LR: 0.005392
Epoch: 045 | Train loss: 0.9974 | Train acc: 50.77% | Val loss: 0.9918 | Val acc: 50.77% | LR: 0.005334
Epoch: 046 | Train loss: 0.9909 | Train acc: 50.98% | Val loss: 0.9923 | Val acc: 49.66% | LR: 0.005276
Epoch: 047 | Train loss: 1.0117 | Train acc: 50.18% | Val loss: 0.9798 | Val acc: 54.23% | LR: 0.005216
Epoch: 048 | Train loss: 0.9963 | Train acc: 50.73% | Val loss: 0.9780 | Val acc: 49.89% | LR: 0.005156
Epoch: 049 | Train loss: 1.0003 | Train acc: 50.25% | Val loss: 0.9988 | Val acc: 50.65% | LR: 0.005094
Epoch: 050 | Train loss: 0.9950 | Train acc: 50.57% | Val loss: 0.9836 | Val acc: 49.50% | LR: 0.005032
Epoch: 051 | Train loss: 1.0067 | Train acc: 49.73% | Val loss: 0.9828 | Val acc: 51.77% | LR: 0.004970
Epoch: 052 | Train loss: 1.4979 | Train acc: 50.70% | Val loss: 1.0119 | Val acc: 48.41% | LR: 0.004906
Epoch: 053 | Train loss: 0.9981 | Train acc: 50.54% | Val loss: 1.0180 | Val acc: 45.95% | LR: 0.004842
Epoch: 054 | Train loss: 1.0028 | Train acc: 49.69% | Val loss: 0.9966 | Val acc: 51.19% | LR: 0.004778
Epoch: 055 | Train loss: 0.9992 | Train acc: 51.09% | Val loss: 1.0583 | Val acc: 45.95% | LR: 0.004712
Epoch: 056 | Train loss: 0.9962 | Train acc: 50.18% | Val loss: 0.9766 | Val acc: 51.27% | LR: 0.004647
Epoch: 057 | Train loss: 1.0076 | Train acc: 49.71% | Val loss: 0.9773 | Val acc: 53.00% | LR: 0.004580
Epoch: 058 | Train loss: 0.9950 | Train acc: 50.23% | Val loss: 0.9688 | Val acc: 52.78% | LR: 0.004513
Epoch: 059 | Train loss: 0.9951 | Train acc: 50.22% | Val loss: 1.0116 | Val acc: 49.10% | LR: 0.004446
Epoch: 060 | Train loss: 0.9994 | Train acc: 50.58% | Val loss: 1.0006 | Val acc: 50.17% | LR: 0.004378
Epoch: 061 | Train loss: 0.9966 | Train acc: 50.38% | Val loss: 1.0084 | Val acc: 45.95% | LR: 0.004310
Epoch: 062 | Train loss: 1.0029 | Train acc: 49.68% | Val loss: 0.9914 | Val acc: 54.54% | LR: 0.004241
Epoch: 063 | Train loss: 1.0004 | Train acc: 50.05% | Val loss: 0.9987 | Val acc: 49.59% | LR: 0.004172
Epoch: 064 | Train loss: 1.0040 | Train acc: 49.99% | Val loss: 0.9976 | Val acc: 50.68% | LR: 0.004103
Epoch: 065 | Train loss: 0.9975 | Train acc: 50.35% | Val loss: 0.9758 | Val acc: 54.05% | LR: 0.004033
Epoch: 066 | Train loss: 0.9984 | Train acc: 50.72% | Val loss: 1.0160 | Val acc: 45.95% | LR: 0.003963
Epoch: 067 | Train loss: 1.0006 | Train acc: 50.10% | Val loss: 1.0117 | Val acc: 45.95% | LR: 0.003893
Epoch: 068 | Train loss: 1.0002 | Train acc: 50.40% | Val loss: 0.9992 | Val acc: 49.36% | LR: 0.003822
Epoch: 069 | Train loss: 1.0015 | Train acc: 50.00% | Val loss: 0.9582 | Val acc: 54.05% | LR: 0.003751
Epoch: 070 | Train loss: 1.0003 | Train acc: 50.41% | Val loss: 1.0035 | Val acc: 48.33% | LR: 0.003681
Epoch: 071 | Train loss: 1.0032 | Train acc: 49.71% | Val loss: 0.9739 | Val acc: 54.55% | LR: 0.003610
Epoch: 072 | Train loss: 0.9940 | Train acc: 50.40% | Val loss: 0.9648 | Val acc: 54.70% | LR: 0.003539
Epoch: 073 | Train loss: 0.9923 | Train acc: 50.79% | Val loss: 1.0549 | Val acc: 45.95% | LR: 0.003468
Epoch: 074 | Train loss: 1.0034 | Train acc: 49.93% | Val loss: 0.9844 | Val acc: 54.78% | LR: 0.003397
Epoch: 075 | Train loss: 0.9920 | Train acc: 50.74% | Val loss: 1.0068 | Val acc: 48.59% | LR: 0.003325
Epoch: 076 | Train loss: 0.9966 | Train acc: 50.64% | Val loss: 1.0122 | Val acc: 48.87% | LR: 0.003254
Epoch: 077 | Train loss: 0.9911 | Train acc: 51.28% | Val loss: 1.0245 | Val acc: 48.42% | LR: 0.003183
Epoch: 078 | Train loss: 0.9873 | Train acc: 51.38% | Val loss: 0.9943 | Val acc: 49.62% | LR: 0.003112
Epoch: 079 | Train loss: 0.9932 | Train acc: 50.56% | Val loss: 1.0512 | Val acc: 46.31% | LR: 0.003042
Epoch: 080 | Train loss: 0.9908 | Train acc: 51.09% | Val loss: 0.9938 | Val acc: 54.05% | LR: 0.002971
Epoch: 081 | Train loss: 0.9945 | Train acc: 50.69% | Val loss: 0.9966 | Val acc: 54.13% | LR: 0.002901
Epoch: 082 | Train loss: 1.0060 | Train acc: 49.70% | Val loss: 0.9954 | Val acc: 53.88% | LR: 0.002830
Epoch: 083 | Train loss: 0.9928 | Train acc: 50.66% | Val loss: 0.9876 | Val acc: 53.95% | LR: 0.002760
Epoch: 084 | Train loss: 0.9944 | Train acc: 50.14% | Val loss: 0.9882 | Val acc: 53.95% | LR: 0.002691
Epoch: 085 | Train loss: 0.9979 | Train acc: 50.10% | Val loss: 0.9874 | Val acc: 53.81% | LR: 0.002621
Epoch: 086 | Train loss: 0.9912 | Train acc: 50.83% | Val loss: 0.9909 | Val acc: 53.78% | LR: 0.002552
Epoch: 087 | Train loss: 0.9939 | Train acc: 50.86% | Val loss: 0.9997 | Val acc: 50.32% | LR: 0.002483
Epoch: 088 | Train loss: 1.0022 | Train acc: 49.53% | Val loss: 0.9945 | Val acc: 53.00% | LR: 0.002415
Epoch: 089 | Train loss: 0.9966 | Train acc: 50.55% | Val loss: 1.0016 | Val acc: 48.46% | LR: 0.002347
Epoch: 090 | Train loss: 0.9970 | Train acc: 50.53% | Val loss: 0.9920 | Val acc: 53.08% | LR: 0.002280
Epoch: 091 | Train loss: 0.9977 | Train acc: 50.44% | Val loss: 0.9900 | Val acc: 53.11% | LR: 0.002213
Epoch: 092 | Train loss: 0.9893 | Train acc: 51.05% | Val loss: 0.9892 | Val acc: 50.87% | LR: 0.002147
Epoch: 093 | Train loss: 0.9936 | Train acc: 50.64% | Val loss: 0.9713 | Val acc: 52.44% | LR: 0.002081
Epoch: 094 | Train loss: 0.9964 | Train acc: 50.24% | Val loss: 0.9606 | Val acc: 54.39% | LR: 0.002015
Epoch: 095 | Train loss: 0.9952 | Train acc: 50.39% | Val loss: 1.0138 | Val acc: 47.16% | LR: 0.001951
Epoch: 096 | Train loss: 0.9941 | Train acc: 50.87% | Val loss: 0.9919 | Val acc: 52.65% | LR: 0.001887
Epoch: 097 | Train loss: 0.9934 | Train acc: 51.02% | Val loss: 0.9796 | Val acc: 53.66% | LR: 0.001823
Epoch: 098 | Train loss: 0.9887 | Train acc: 51.40% | Val loss: 1.0041 | Val acc: 48.92% | LR: 0.001761
Epoch: 099 | Train loss: 0.9894 | Train acc: 51.40% | Val loss: 0.9587 | Val acc: 53.56% | LR: 0.001699
Epoch: 100 | Train loss: 0.9865 | Train acc: 51.57% | Val loss: 1.0136 | Val acc: 48.59% | LR: 0.001638
Epoch: 101 | Train loss: 0.9919 | Train acc: 50.71% | Val loss: 0.9925 | Val acc: 50.60% | LR: 0.001577
Epoch: 102 | Train loss: 0.9898 | Train acc: 50.94% | Val loss: 0.9946 | Val acc: 50.20% | LR: 0.001517
Epoch: 103 | Train loss: 0.9846 | Train acc: 51.51% | Val loss: 0.9973 | Val acc: 49.83% | LR: 0.001459
Epoch: 104 | Train loss: 0.9871 | Train acc: 50.57% | Val loss: 1.0019 | Val acc: 49.89% | LR: 0.001401
Epoch: 105 | Train loss: 0.9878 | Train acc: 51.05% | Val loss: 0.9972 | Val acc: 49.76% | LR: 0.001344
Epoch: 106 | Train loss: 0.9876 | Train acc: 50.86% | Val loss: 1.0025 | Val acc: 49.65% | LR: 0.001287
Epoch: 107 | Train loss: 0.9882 | Train acc: 50.90% | Val loss: 1.0118 | Val acc: 49.19% | LR: 0.001232
Epoch: 108 | Train loss: 0.9860 | Train acc: 51.27% | Val loss: 1.0150 | Val acc: 48.75% | LR: 0.001178
Epoch: 109 | Train loss: 0.9828 | Train acc: 51.23% | Val loss: 1.0107 | Val acc: 48.93% | LR: 0.001124
Epoch: 110 | Train loss: 0.9893 | Train acc: 51.03% | Val loss: 1.0170 | Val acc: 48.73% | LR: 0.001072
Epoch: 111 | Train loss: 0.9874 | Train acc: 50.82% | Val loss: 1.0191 | Val acc: 48.73% | LR: 0.001021
Epoch: 112 | Train loss: 0.9871 | Train acc: 50.99% | Val loss: 1.0164 | Val acc: 48.69% | LR: 0.000971
Epoch: 113 | Train loss: 0.9851 | Train acc: 51.46% | Val loss: 1.0164 | Val acc: 48.70% | LR: 0.000921
Epoch: 114 | Train loss: 0.9868 | Train acc: 51.08% | Val loss: 1.0160 | Val acc: 48.83% | LR: 0.000873
Epoch: 115 | Train loss: 0.9879 | Train acc: 50.87% | Val loss: 1.0155 | Val acc: 48.83% | LR: 0.000826
Epoch: 116 | Train loss: 0.9898 | Train acc: 50.65% | Val loss: 1.0187 | Val acc: 48.75% | LR: 0.000780
Epoch: 117 | Train loss: 0.9870 | Train acc: 51.06% | Val loss: 1.0166 | Val acc: 48.73% | LR: 0.000735
Epoch: 118 | Train loss: 0.9828 | Train acc: 51.10% | Val loss: 1.0153 | Val acc: 48.73% | LR: 0.000692
Epoch: 119 | Train loss: 0.9816 | Train acc: 51.42% | Val loss: 1.0175 | Val acc: 48.88% | LR: 0.000649
Epoch: 120 | Train loss: 0.9835 | Train acc: 51.36% | Val loss: 1.0150 | Val acc: 48.75% | LR: 0.000608
Epoch: 121 | Train loss: 0.9875 | Train acc: 50.83% | Val loss: 1.0161 | Val acc: 48.81% | LR: 0.000568
Epoch: 122 | Train loss: 0.9867 | Train acc: 51.06% | Val loss: 1.0173 | Val acc: 48.79% | LR: 0.000530
Epoch: 123 | Train loss: 0.9864 | Train acc: 51.02% | Val loss: 1.0206 | Val acc: 48.79% | LR: 0.000492
Epoch: 124 | Train loss: 0.9848 | Train acc: 50.91% | Val loss: 1.0195 | Val acc: 48.85% | LR: 0.000456
Epoch: 125 | Train loss: 0.9912 | Train acc: 50.42% | Val loss: 1.0179 | Val acc: 48.77% | LR: 0.000421
Epoch: 126 | Train loss: 0.9788 | Train acc: 51.53% | Val loss: 1.0211 | Val acc: 48.69% | LR: 0.000387
Epoch: 127 | Train loss: 0.9804 | Train acc: 51.35% | Val loss: 1.0189 | Val acc: 48.85% | LR: 0.000355
Epoch: 128 | Train loss: 0.9807 | Train acc: 51.18% | Val loss: 1.0171 | Val acc: 48.87% | LR: 0.000324
Epoch: 129 | Train loss: 0.9854 | Train acc: 51.04% | Val loss: 1.0205 | Val acc: 48.79% | LR: 0.000295
Epoch: 130 | Train loss: 0.9789 | Train acc: 51.36% | Val loss: 1.0152 | Val acc: 48.97% | LR: 0.000266
Epoch: 131 | Train loss: 0.9873 | Train acc: 50.66% | Val loss: 1.0185 | Val acc: 48.95% | LR: 0.000239
Epoch: 132 | Train loss: 0.9760 | Train acc: 51.47% | Val loss: 1.0216 | Val acc: 48.73% | LR: 0.000214
Epoch: 133 | Train loss: 0.9797 | Train acc: 51.21% | Val loss: 1.0186 | Val acc: 48.81% | LR: 0.000190
Epoch: 134 | Train loss: 0.9863 | Train acc: 50.70% | Val loss: 1.0189 | Val acc: 48.77% | LR: 0.000167
Epoch: 135 | Train loss: 0.9738 | Train acc: 51.82% | Val loss: 1.0182 | Val acc: 48.83% | LR: 0.000146
Epoch: 136 | Train loss: 0.9794 | Train acc: 51.56% | Val loss: 1.0190 | Val acc: 48.97% | LR: 0.000126
Epoch: 137 | Train loss: 0.9863 | Train acc: 50.85% | Val loss: 1.0186 | Val acc: 48.99% | LR: 0.000108
Epoch: 138 | Train loss: 0.9794 | Train acc: 51.38% | Val loss: 1.0181 | Val acc: 48.93% | LR: 0.000091
Epoch: 139 | Train loss: 0.9824 | Train acc: 51.30% | Val loss: 1.0182 | Val acc: 48.91% | LR: 0.000075
Epoch: 140 | Train loss: 0.9875 | Train acc: 50.78% | Val loss: 1.0188 | Val acc: 48.85% | LR: 0.000061
Epoch: 141 | Train loss: 0.9828 | Train acc: 51.23% | Val loss: 1.0183 | Val acc: 48.87% | LR: 0.000049
Epoch: 142 | Train loss: 0.9852 | Train acc: 51.09% | Val loss: 1.0180 | Val acc: 48.97% | LR: 0.000037
Epoch: 143 | Train loss: 0.9852 | Train acc: 51.03% | Val loss: 1.0191 | Val acc: 48.83% | LR: 0.000028
Epoch: 144 | Train loss: 0.9847 | Train acc: 50.96% | Val loss: 1.0187 | Val acc: 48.85% | LR: 0.000020
Epoch: 145 | Train loss: 0.9819 | Train acc: 51.13% | Val loss: 1.0187 | Val acc: 48.85% | LR: 0.000013
Epoch: 146 | Train loss: 0.9833 | Train acc: 51.04% | Val loss: 1.0186 | Val acc: 48.85% | LR: 0.000008
Epoch: 147 | Train loss: 0.9882 | Train acc: 50.69% | Val loss: 1.0187 | Val acc: 48.85% | LR: 0.000004
Epoch: 148 | Train loss: 0.9827 | Train acc: 51.05% | Val loss: 1.0187 | Val acc: 48.85% | LR: 0.000002
Epoch: 149 | Train loss: 0.9872 | Train acc: 50.87% | Val loss: 1.0187 | Val acc: 48.85% | LR: 0.000001

[I 2025-09-23 02:57:18,020] Trial 31 finished with value: 0.5477599024772644 and parameters: {'lr': 0.00679208395166722, 'hidden_size': 156, 'dropout': 0.41470856166660314, 'weight_decay': 0.647799304014497}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.0024 | Train acc: 50.27% | Val loss: 1.0066 | Val acc: 51.81% | LR: 0.007087
Epoch: 001 | Train loss: 1.0079 | Train acc: 49.93% | Val loss: 0.9824 | Val acc: 51.56% | LR: 0.007085
Epoch: 002 | Train loss: 1.0145 | Train acc: 49.42% | Val loss: 1.0139 | Val acc: 49.18% | LR: 0.007081
Epoch: 003 | Train loss: 1.0592 | Train acc: 50.19% | Val loss: 1.0069 | Val acc: 50.79% | LR: 0.007076
Epoch: 004 | Train loss: 0.9964 | Train acc: 50.87% | Val loss: 0.9598 | Val acc: 54.82% | LR: 0.007069
Epoch: 005 | Train loss: 1.0228 | Train acc: 49.95% | Val loss: 0.9702 | Val acc: 54.32% | LR: 0.007060
Epoch: 006 | Train loss: 1.6919 | Train acc: 50.34% | Val loss: 1.0175 | Val acc: 48.48% | LR: 0.007050
Epoch: 007 | Train loss: 1.0026 | Train acc: 50.07% | Val loss: 0.9889 | Val acc: 52.06% | LR: 0.007038
Epoch: 008 | Train loss: 0.9993 | Train acc: 50.23% | Val loss: 0.9793 | Val acc: 50.44% | LR: 0.007025
Epoch: 009 | Train loss: 1.0224 | Train acc: 50.40% | Val loss: 0.9553 | Val acc: 54.09% | LR: 0.007011
Epoch: 010 | Train loss: 1.0291 | Train acc: 50.05% | Val loss: 0.9720 | Val acc: 54.05% | LR: 0.006994
Epoch: 011 | Train loss: 1.0024 | Train acc: 50.45% | Val loss: 0.9909 | Val acc: 53.78% | LR: 0.006977
Epoch: 012 | Train loss: 1.0038 | Train acc: 49.95% | Val loss: 1.0034 | Val acc: 46.17% | LR: 0.006957
Epoch: 013 | Train loss: 0.9997 | Train acc: 50.36% | Val loss: 1.0140 | Val acc: 45.91% | LR: 0.006937
Epoch: 014 | Train loss: 0.9913 | Train acc: 50.90% | Val loss: 0.9679 | Val acc: 53.93% | LR: 0.006915
Epoch: 015 | Train loss: 0.9975 | Train acc: 50.25% | Val loss: 1.0023 | Val acc: 49.02% | LR: 0.006891
Epoch: 016 | Train loss: 0.9911 | Train acc: 50.90% | Val loss: 0.9452 | Val acc: 53.99% | LR: 0.006866
Epoch: 017 | Train loss: 1.0067 | Train acc: 49.89% | Val loss: 0.9817 | Val acc: 53.94% | LR: 0.006839
Epoch: 018 | Train loss: 1.0070 | Train acc: 49.82% | Val loss: 0.9253 | Val acc: 54.05% | LR: 0.006811
Epoch: 019 | Train loss: 1.0084 | Train acc: 49.84% | Val loss: 1.0047 | Val acc: 46.86% | LR: 0.006782
Epoch: 020 | Train loss: 0.9958 | Train acc: 50.65% | Val loss: 1.0359 | Val acc: 46.93% | LR: 0.006751
Epoch: 021 | Train loss: 0.9989 | Train acc: 50.13% | Val loss: 0.9948 | Val acc: 49.26% | LR: 0.006718
Epoch: 022 | Train loss: 0.9971 | Train acc: 50.95% | Val loss: 0.9990 | Val acc: 50.28% | LR: 0.006685
Epoch: 023 | Train loss: 0.9978 | Train acc: 50.32% | Val loss: 1.0054 | Val acc: 49.72% | LR: 0.006650
Epoch: 024 | Train loss: 0.9999 | Train acc: 50.53% | Val loss: 1.0092 | Val acc: 49.09% | LR: 0.006613
Epoch: 025 | Train loss: 0.9983 | Train acc: 50.51% | Val loss: 1.0277 | Val acc: 49.34% | LR: 0.006576
Epoch: 026 | Train loss: 1.0016 | Train acc: 50.84% | Val loss: 1.0216 | Val acc: 48.57% | LR: 0.006536
Epoch: 027 | Train loss: 0.9980 | Train acc: 49.77% | Val loss: 1.0106 | Val acc: 48.61% | LR: 0.006496
Epoch: 028 | Train loss: 0.9944 | Train acc: 50.37% | Val loss: 1.0107 | Val acc: 48.65% | LR: 0.006454
Epoch: 029 | Train loss: 0.9954 | Train acc: 50.85% | Val loss: 1.0326 | Val acc: 47.99% | LR: 0.006411
Epoch: 030 | Train loss: 0.9947 | Train acc: 50.88% | Val loss: 1.0125 | Val acc: 48.93% | LR: 0.006367
Epoch: 031 | Train loss: 0.9918 | Train acc: 50.85% | Val loss: 1.0113 | Val acc: 48.64% | LR: 0.006322
Epoch: 032 | Train loss: 1.0043 | Train acc: 50.24% | Val loss: 1.0000 | Val acc: 48.95% | LR: 0.006275
Epoch: 033 | Train loss: 0.9960 | Train acc: 50.95% | Val loss: 0.9734 | Val acc: 54.05% | LR: 0.006227
Epoch: 034 | Train loss: 0.9994 | Train acc: 50.63% | Val loss: 1.0329 | Val acc: 47.73% | LR: 0.006178
Epoch: 035 | Train loss: 0.9966 | Train acc: 50.73% | Val loss: 1.0090 | Val acc: 47.95% | LR: 0.006128
Epoch: 036 | Train loss: 0.9978 | Train acc: 49.76% | Val loss: 0.9817 | Val acc: 48.41% | LR: 0.006076
Epoch: 037 | Train loss: 1.0058 | Train acc: 50.42% | Val loss: 0.9841 | Val acc: 49.82% | LR: 0.006024
Epoch: 038 | Train loss: 1.0006 | Train acc: 50.23% | Val loss: 0.9827 | Val acc: 49.35% | LR: 0.005970
Epoch: 039 | Train loss: 0.9902 | Train acc: 51.18% | Val loss: 1.0159 | Val acc: 48.96% | LR: 0.005916
Epoch: 040 | Train loss: 0.9948 | Train acc: 50.59% | Val loss: 0.9764 | Val acc: 54.02% | LR: 0.005860
Epoch: 041 | Train loss: 1.0254 | Train acc: 49.63% | Val loss: 0.9701 | Val acc: 50.38% | LR: 0.005803
Epoch: 042 | Train loss: 0.9994 | Train acc: 50.40% | Val loss: 0.9962 | Val acc: 50.82% | LR: 0.005746
Epoch: 043 | Train loss: 0.9987 | Train acc: 50.05% | Val loss: 0.9975 | Val acc: 50.38% | LR: 0.005687
Epoch: 044 | Train loss: 1.0033 | Train acc: 49.78% | Val loss: 1.0018 | Val acc: 48.59% | LR: 0.005627
Epoch: 045 | Train loss: 0.9916 | Train acc: 51.08% | Val loss: 1.0241 | Val acc: 48.20% | LR: 0.005567
Epoch: 046 | Train loss: 0.9898 | Train acc: 51.28% | Val loss: 1.0080 | Val acc: 49.01% | LR: 0.005505
Epoch: 047 | Train loss: 0.9921 | Train acc: 51.28% | Val loss: 1.0231 | Val acc: 48.79% | LR: 0.005443
Epoch: 048 | Train loss: 1.0010 | Train acc: 50.81% | Val loss: 1.0118 | Val acc: 48.80% | LR: 0.005380
Epoch: 049 | Train loss: 0.9981 | Train acc: 50.29% | Val loss: 1.0152 | Val acc: 48.79% | LR: 0.005316
Epoch: 050 | Train loss: 0.9954 | Train acc: 49.99% | Val loss: 1.0124 | Val acc: 49.07% | LR: 0.005252
Epoch: 051 | Train loss: 0.9910 | Train acc: 51.27% | Val loss: 1.0069 | Val acc: 49.39% | LR: 0.005186
Epoch: 052 | Train loss: 0.9931 | Train acc: 50.54% | Val loss: 1.0174 | Val acc: 49.98% | LR: 0.005120
Epoch: 053 | Train loss: 0.9902 | Train acc: 50.83% | Val loss: 1.0891 | Val acc: 53.13% | LR: 0.005053
Epoch: 054 | Train loss: 0.9994 | Train acc: 50.71% | Val loss: 1.0570 | Val acc: 48.41% | LR: 0.004986
Epoch: 055 | Train loss: 1.0127 | Train acc: 49.63% | Val loss: 1.0766 | Val acc: 49.54% | LR: 0.004918
Epoch: 056 | Train loss: 1.0079 | Train acc: 50.11% | Val loss: 0.9757 | Val acc: 52.26% | LR: 0.004849
Epoch: 057 | Train loss: 1.0004 | Train acc: 50.55% | Val loss: 0.9758 | Val acc: 51.80% | LR: 0.004780
Epoch: 058 | Train loss: 1.0016 | Train acc: 50.38% | Val loss: 0.9908 | Val acc: 51.24% | LR: 0.004710
Epoch: 059 | Train loss: 1.0003 | Train acc: 50.26% | Val loss: 0.9754 | Val acc: 53.42% | LR: 0.004640
Epoch: 060 | Train loss: 1.0084 | Train acc: 49.87% | Val loss: 0.9921 | Val acc: 50.23% | LR: 0.004569
Epoch: 061 | Train loss: 0.9977 | Train acc: 51.29% | Val loss: 1.0223 | Val acc: 51.99% | LR: 0.004497
Epoch: 062 | Train loss: 1.0072 | Train acc: 49.81% | Val loss: 0.9618 | Val acc: 54.00% | LR: 0.004426
Epoch: 063 | Train loss: 0.9963 | Train acc: 50.61% | Val loss: 0.9965 | Val acc: 52.84% | LR: 0.004354
Epoch: 064 | Train loss: 0.9937 | Train acc: 50.62% | Val loss: 0.9676 | Val acc: 52.02% | LR: 0.004281
Epoch: 065 | Train loss: 0.9946 | Train acc: 50.52% | Val loss: 1.0017 | Val acc: 49.34% | LR: 0.004209
Epoch: 066 | Train loss: 0.9985 | Train acc: 50.59% | Val loss: 0.9897 | Val acc: 53.71% | LR: 0.004135
Epoch: 067 | Train loss: 0.9972 | Train acc: 50.66% | Val loss: 1.0004 | Val acc: 48.82% | LR: 0.004062
Epoch: 068 | Train loss: 0.9976 | Train acc: 50.60% | Val loss: 1.0054 | Val acc: 47.27% | LR: 0.003989
Epoch: 069 | Train loss: 0.9934 | Train acc: 51.06% | Val loss: 0.9883 | Val acc: 52.91% | LR: 0.003915
Epoch: 070 | Train loss: 0.9977 | Train acc: 50.37% | Val loss: 0.9841 | Val acc: 52.99% | LR: 0.003841
Epoch: 071 | Train loss: 1.0011 | Train acc: 50.41% | Val loss: 1.0210 | Val acc: 47.20% | LR: 0.003767
Epoch: 072 | Train loss: 1.0008 | Train acc: 49.99% | Val loss: 1.0195 | Val acc: 47.39% | LR: 0.003693
Epoch: 073 | Train loss: 0.9972 | Train acc: 50.44% | Val loss: 1.0068 | Val acc: 47.65% | LR: 0.003619
Epoch: 074 | Train loss: 1.0001 | Train acc: 50.15% | Val loss: 0.9938 | Val acc: 52.80% | LR: 0.003545
Epoch: 075 | Train loss: 0.9908 | Train acc: 51.04% | Val loss: 1.0075 | Val acc: 47.32% | LR: 0.003470
Epoch: 076 | Train loss: 0.9933 | Train acc: 51.13% | Val loss: 1.0112 | Val acc: 46.80% | LR: 0.003396
Epoch: 077 | Train loss: 1.0022 | Train acc: 49.99% | Val loss: 1.0223 | Val acc: 45.91% | LR: 0.003322
Epoch: 078 | Train loss: 0.9987 | Train acc: 50.32% | Val loss: 0.9680 | Val acc: 53.90% | LR: 0.003248
Epoch: 079 | Train loss: 1.0003 | Train acc: 50.06% | Val loss: 1.0348 | Val acc: 45.97% | LR: 0.003174
Epoch: 080 | Train loss: 1.0007 | Train acc: 50.05% | Val loss: 0.9897 | Val acc: 52.63% | LR: 0.003100
Epoch: 081 | Train loss: 0.9932 | Train acc: 50.97% | Val loss: 0.9634 | Val acc: 53.70% | LR: 0.003027
Epoch: 082 | Train loss: 0.9921 | Train acc: 50.55% | Val loss: 0.9925 | Val acc: 52.63% | LR: 0.002954
Epoch: 083 | Train loss: 0.9936 | Train acc: 50.98% | Val loss: 1.0053 | Val acc: 49.08% | LR: 0.002881
Epoch: 084 | Train loss: 0.9934 | Train acc: 50.96% | Val loss: 1.0179 | Val acc: 47.05% | LR: 0.002808
Epoch: 085 | Train loss: 0.9972 | Train acc: 50.82% | Val loss: 0.9773 | Val acc: 53.23% | LR: 0.002735
Epoch: 086 | Train loss: 0.9926 | Train acc: 50.82% | Val loss: 0.9779 | Val acc: 52.52% | LR: 0.002663
Epoch: 087 | Train loss: 0.9954 | Train acc: 50.47% | Val loss: 0.9715 | Val acc: 52.64% | LR: 0.002592
Epoch: 088 | Train loss: 0.9917 | Train acc: 50.90% | Val loss: 1.0033 | Val acc: 51.79% | LR: 0.002520
Epoch: 089 | Train loss: 0.9941 | Train acc: 50.64% | Val loss: 0.9962 | Val acc: 51.92% | LR: 0.002450
Epoch: 090 | Train loss: 0.9919 | Train acc: 50.94% | Val loss: 0.9648 | Val acc: 52.94% | LR: 0.002379
Epoch: 091 | Train loss: 0.9950 | Train acc: 50.61% | Val loss: 0.9630 | Val acc: 53.32% | LR: 0.002309
Epoch: 092 | Train loss: 0.9913 | Train acc: 50.69% | Val loss: 0.9513 | Val acc: 53.27% | LR: 0.002240
Epoch: 093 | Train loss: 0.9938 | Train acc: 50.61% | Val loss: 1.0657 | Val acc: 53.73% | LR: 0.002171
Epoch: 094 | Train loss: 1.0010 | Train acc: 50.90% | Val loss: 0.9875 | Val acc: 53.44% | LR: 0.002103
Epoch: 095 | Train loss: 0.9998 | Train acc: 50.11% | Val loss: 0.9697 | Val acc: 53.93% | LR: 0.002036
Epoch: 096 | Train loss: 0.9930 | Train acc: 50.49% | Val loss: 0.9871 | Val acc: 54.12% | LR: 0.001969
Epoch: 097 | Train loss: 0.9963 | Train acc: 50.38% | Val loss: 0.9785 | Val acc: 53.93% | LR: 0.001903
Epoch: 098 | Train loss: 0.9958 | Train acc: 50.24% | Val loss: 1.0077 | Val acc: 48.36% | LR: 0.001837
Epoch: 099 | Train loss: 0.9976 | Train acc: 50.22% | Val loss: 0.9888 | Val acc: 53.27% | LR: 0.001773
Epoch: 100 | Train loss: 1.0033 | Train acc: 49.66% | Val loss: 0.9782 | Val acc: 53.07% | LR: 0.001709
Epoch: 101 | Train loss: 1.0059 | Train acc: 50.67% | Val loss: 1.4171 | Val acc: 48.13% | LR: 0.001646
Epoch: 102 | Train loss: 0.9987 | Train acc: 50.68% | Val loss: 0.9811 | Val acc: 52.49% | LR: 0.001584
Epoch: 103 | Train loss: 0.9907 | Train acc: 50.91% | Val loss: 0.9547 | Val acc: 54.05% | LR: 0.001522
Epoch: 104 | Train loss: 0.9947 | Train acc: 50.48% | Val loss: 0.9554 | Val acc: 53.31% | LR: 0.001462
Epoch: 105 | Train loss: 0.9871 | Train acc: 50.98% | Val loss: 0.9602 | Val acc: 53.09% | LR: 0.001402
Epoch: 106 | Train loss: 0.9960 | Train acc: 50.11% | Val loss: 0.9638 | Val acc: 52.85% | LR: 0.001343
Epoch: 107 | Train loss: 0.9901 | Train acc: 51.15% | Val loss: 0.9739 | Val acc: 52.86% | LR: 0.001286
Epoch: 108 | Train loss: 0.9918 | Train acc: 50.71% | Val loss: 0.9710 | Val acc: 52.75% | LR: 0.001229
Epoch: 109 | Train loss: 0.9885 | Train acc: 51.08% | Val loss: 0.9719 | Val acc: 52.26% | LR: 0.001173
Epoch: 110 | Train loss: 0.9889 | Train acc: 50.72% | Val loss: 0.9746 | Val acc: 52.38% | LR: 0.001119
Epoch: 111 | Train loss: 0.9890 | Train acc: 50.78% | Val loss: 0.9811 | Val acc: 51.66% | LR: 0.001065
Epoch: 112 | Train loss: 0.9922 | Train acc: 50.64% | Val loss: 0.9715 | Val acc: 52.24% | LR: 0.001013
Epoch: 113 | Train loss: 0.9929 | Train acc: 50.49% | Val loss: 0.9837 | Val acc: 51.38% | LR: 0.000961
Epoch: 114 | Train loss: 0.9898 | Train acc: 51.01% | Val loss: 0.9807 | Val acc: 51.36% | LR: 0.000911
Epoch: 115 | Train loss: 0.9887 | Train acc: 50.97% | Val loss: 0.9803 | Val acc: 51.22% | LR: 0.000862
Epoch: 116 | Train loss: 0.9879 | Train acc: 50.89% | Val loss: 0.9796 | Val acc: 51.26% | LR: 0.000814
Epoch: 117 | Train loss: 0.9925 | Train acc: 50.79% | Val loss: 0.9806 | Val acc: 51.47% | LR: 0.000767
Epoch: 118 | Train loss: 0.9834 | Train acc: 51.72% | Val loss: 0.9816 | Val acc: 51.15% | LR: 0.000722
Epoch: 119 | Train loss: 0.9906 | Train acc: 50.79% | Val loss: 0.9816 | Val acc: 51.23% | LR: 0.000678
Epoch: 120 | Train loss: 0.9898 | Train acc: 50.76% | Val loss: 0.9761 | Val acc: 51.36% | LR: 0.000635
Epoch: 121 | Train loss: 0.9875 | Train acc: 50.89% | Val loss: 0.9765 | Val acc: 51.80% | LR: 0.000593
Epoch: 122 | Train loss: 0.9888 | Train acc: 50.84% | Val loss: 0.9833 | Val acc: 51.09% | LR: 0.000553
Epoch: 123 | Train loss: 0.9897 | Train acc: 50.77% | Val loss: 0.9838 | Val acc: 51.04% | LR: 0.000514
Epoch: 124 | Train loss: 0.9818 | Train acc: 51.34% | Val loss: 0.9792 | Val acc: 51.23% | LR: 0.000476
Epoch: 125 | Train loss: 0.9803 | Train acc: 51.40% | Val loss: 0.9792 | Val acc: 51.39% | LR: 0.000439
Epoch: 126 | Train loss: 0.9821 | Train acc: 51.51% | Val loss: 0.9817 | Val acc: 51.33% | LR: 0.000404
Epoch: 127 | Train loss: 0.9857 | Train acc: 51.02% | Val loss: 0.9827 | Val acc: 51.21% | LR: 0.000371
Epoch: 128 | Train loss: 0.9933 | Train acc: 50.54% | Val loss: 0.9813 | Val acc: 51.42% | LR: 0.000338
Epoch: 129 | Train loss: 0.9839 | Train acc: 51.06% | Val loss: 0.9871 | Val acc: 50.44% | LR: 0.000307
Epoch: 130 | Train loss: 0.9839 | Train acc: 51.01% | Val loss: 0.9834 | Val acc: 51.06% | LR: 0.000278
Epoch: 131 | Train loss: 0.9839 | Train acc: 51.20% | Val loss: 0.9818 | Val acc: 50.98% | LR: 0.000250
Epoch: 132 | Train loss: 0.9806 | Train acc: 51.26% | Val loss: 0.9807 | Val acc: 50.86% | LR: 0.000223
Epoch: 133 | Train loss: 0.9838 | Train acc: 51.23% | Val loss: 0.9833 | Val acc: 50.75% | LR: 0.000198
Epoch: 134 | Train loss: 0.9910 | Train acc: 50.44% | Val loss: 0.9805 | Val acc: 50.90% | LR: 0.000174
Epoch: 135 | Train loss: 0.9814 | Train acc: 51.40% | Val loss: 0.9809 | Val acc: 51.02% | LR: 0.000152
Epoch: 136 | Train loss: 0.9873 | Train acc: 50.81% | Val loss: 0.9828 | Val acc: 50.82% | LR: 0.000132
Epoch: 137 | Train loss: 0.9823 | Train acc: 51.30% | Val loss: 0.9817 | Val acc: 50.76% | LR: 0.000112
Epoch: 138 | Train loss: 0.9808 | Train acc: 51.24% | Val loss: 0.9821 | Val acc: 50.94% | LR: 0.000095
Epoch: 139 | Train loss: 0.9787 | Train acc: 51.42% | Val loss: 0.9830 | Val acc: 50.78% | LR: 0.000078
Epoch: 140 | Train loss: 0.9787 | Train acc: 51.39% | Val loss: 0.9837 | Val acc: 50.60% | LR: 0.000064
Epoch: 141 | Train loss: 0.9869 | Train acc: 50.96% | Val loss: 0.9829 | Val acc: 50.75% | LR: 0.000051
Epoch: 142 | Train loss: 0.9805 | Train acc: 51.32% | Val loss: 0.9811 | Val acc: 50.80% | LR: 0.000039
Epoch: 143 | Train loss: 0.9889 | Train acc: 50.71% | Val loss: 0.9805 | Val acc: 50.86% | LR: 0.000029
Epoch: 144 | Train loss: 0.9822 | Train acc: 51.26% | Val loss: 0.9806 | Val acc: 50.84% | LR: 0.000020
Epoch: 145 | Train loss: 0.9840 | Train acc: 51.16% | Val loss: 0.9804 | Val acc: 51.10% | LR: 0.000013
Epoch: 146 | Train loss: 0.9821 | Train acc: 51.28% | Val loss: 0.9804 | Val acc: 50.96% | LR: 0.000008
Epoch: 147 | Train loss: 0.9820 | Train acc: 51.34% | Val loss: 0.9803 | Val acc: 51.06% | LR: 0.000004
Epoch: 148 | Train loss: 0.9821 | Train acc: 51.27% | Val loss: 0.9803 | Val acc: 51.02% | LR: 0.000002
Epoch: 149 | Train loss: 0.9816 | Train acc: 51.23% | Val loss: 0.9803 | Val acc: 51.01% | LR: 0.000001

[I 2025-09-23 03:00:27,999] Trial 32 finished with value: 0.5482145547866821 and parameters: {'lr': 0.007088030631314136, 'hidden_size': 158, 'dropout': 0.3899319335975106, 'weight_decay': 0.5571504003613974}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.0073 | Train acc: 50.32% | Val loss: 0.9913 | Val acc: 50.80% | LR: 0.005690
Epoch: 001 | Train loss: 1.0600 | Train acc: 50.32% | Val loss: 1.0136 | Val acc: 46.62% | LR: 0.005688
Epoch: 002 | Train loss: 1.1788 | Train acc: 49.76% | Val loss: 1.0840 | Val acc: 45.87% | LR: 0.005685
Epoch: 003 | Train loss: 1.5510 | Train acc: 49.37% | Val loss: 1.0106 | Val acc: 45.97% | LR: 0.005681
Epoch: 004 | Train loss: 1.1146 | Train acc: 50.23% | Val loss: 1.0180 | Val acc: 45.95% | LR: 0.005675
Epoch: 005 | Train loss: 1.0008 | Train acc: 50.29% | Val loss: 0.9911 | Val acc: 50.60% | LR: 0.005668
Epoch: 006 | Train loss: 1.0064 | Train acc: 50.29% | Val loss: 1.0175 | Val acc: 48.57% | LR: 0.005660
Epoch: 007 | Train loss: 1.1054 | Train acc: 50.56% | Val loss: 1.0404 | Val acc: 47.07% | LR: 0.005651
Epoch: 008 | Train loss: 1.0121 | Train acc: 49.74% | Val loss: 1.0449 | Val acc: 45.95% | LR: 0.005640
Epoch: 009 | Train loss: 1.0019 | Train acc: 50.16% | Val loss: 1.0048 | Val acc: 47.28% | LR: 0.005629
Epoch: 010 | Train loss: 0.9980 | Train acc: 51.17% | Val loss: 1.0080 | Val acc: 46.82% | LR: 0.005616
Epoch: 011 | Train loss: 1.0022 | Train acc: 50.19% | Val loss: 1.0001 | Val acc: 49.48% | LR: 0.005601
Epoch: 012 | Train loss: 0.9899 | Train acc: 51.26% | Val loss: 0.9865 | Val acc: 52.54% | LR: 0.005586
Epoch: 013 | Train loss: 0.9976 | Train acc: 50.31% | Val loss: 1.0050 | Val acc: 49.20% | LR: 0.005569
Epoch: 014 | Train loss: 0.9967 | Train acc: 50.84% | Val loss: 0.9887 | Val acc: 49.55% | LR: 0.005551
Epoch: 015 | Train loss: 1.0058 | Train acc: 50.41% | Val loss: 0.9951 | Val acc: 49.55% | LR: 0.005532
Epoch: 016 | Train loss: 0.9915 | Train acc: 50.77% | Val loss: 0.9897 | Val acc: 51.08% | LR: 0.005512
Epoch: 017 | Train loss: 0.9982 | Train acc: 51.00% | Val loss: 1.0044 | Val acc: 49.38% | LR: 0.005491
Epoch: 018 | Train loss: 0.9995 | Train acc: 50.32% | Val loss: 1.0128 | Val acc: 49.10% | LR: 0.005468
Epoch: 019 | Train loss: 0.9945 | Train acc: 51.11% | Val loss: 1.0064 | Val acc: 49.20% | LR: 0.005445
Epoch: 020 | Train loss: 0.9978 | Train acc: 50.70% | Val loss: 1.0071 | Val acc: 49.74% | LR: 0.005420
Epoch: 021 | Train loss: 1.0000 | Train acc: 50.10% | Val loss: 1.0222 | Val acc: 47.64% | LR: 0.005394
Epoch: 022 | Train loss: 1.0020 | Train acc: 49.93% | Val loss: 1.0263 | Val acc: 47.17% | LR: 0.005367
Epoch: 023 | Train loss: 0.9940 | Train acc: 50.69% | Val loss: 1.0130 | Val acc: 49.09% | LR: 0.005339
Epoch: 024 | Train loss: 0.9839 | Train acc: 51.34% | Val loss: 1.0111 | Val acc: 48.72% | LR: 0.005310
Epoch: 025 | Train loss: 0.9899 | Train acc: 51.02% | Val loss: 1.0224 | Val acc: 48.58% | LR: 0.005279
Epoch: 026 | Train loss: 0.9957 | Train acc: 50.38% | Val loss: 1.0090 | Val acc: 49.47% | LR: 0.005248
Epoch: 027 | Train loss: 0.9925 | Train acc: 50.86% | Val loss: 0.9947 | Val acc: 49.67% | LR: 0.005215
Epoch: 028 | Train loss: 1.0000 | Train acc: 49.63% | Val loss: 1.0131 | Val acc: 49.11% | LR: 0.005182
Epoch: 029 | Train loss: 0.9890 | Train acc: 50.85% | Val loss: 1.0148 | Val acc: 49.23% | LR: 0.005147
Epoch: 030 | Train loss: 0.9913 | Train acc: 51.03% | Val loss: 1.0120 | Val acc: 49.00% | LR: 0.005112
Epoch: 031 | Train loss: 0.9936 | Train acc: 50.61% | Val loss: 1.0036 | Val acc: 49.54% | LR: 0.005075
Epoch: 032 | Train loss: 0.9978 | Train acc: 50.57% | Val loss: 1.0152 | Val acc: 49.19% | LR: 0.005038
Epoch: 033 | Train loss: 1.1352 | Train acc: 51.22% | Val loss: 1.0323 | Val acc: 50.41% | LR: 0.004999
Epoch: 034 | Train loss: 1.0099 | Train acc: 50.03% | Val loss: 1.0133 | Val acc: 49.63% | LR: 0.004960
Epoch: 035 | Train loss: 1.0026 | Train acc: 50.02% | Val loss: 1.0020 | Val acc: 50.18% | LR: 0.004920
Epoch: 036 | Train loss: 1.0101 | Train acc: 49.98% | Val loss: 0.9890 | Val acc: 54.73% | LR: 0.004878
Epoch: 037 | Train loss: 0.9982 | Train acc: 50.98% | Val loss: 1.0113 | Val acc: 51.55% | LR: 0.004836
Epoch: 038 | Train loss: 1.0000 | Train acc: 50.34% | Val loss: 0.9839 | Val acc: 53.45% | LR: 0.004793
Epoch: 039 | Train loss: 1.0007 | Train acc: 51.06% | Val loss: 0.9856 | Val acc: 53.29% | LR: 0.004749
Epoch: 040 | Train loss: 1.0464 | Train acc: 50.06% | Val loss: 1.0009 | Val acc: 52.67% | LR: 0.004705
Epoch: 041 | Train loss: 0.9948 | Train acc: 50.86% | Val loss: 0.9706 | Val acc: 52.61% | LR: 0.004659
Epoch: 042 | Train loss: 0.9988 | Train acc: 50.56% | Val loss: 0.9633 | Val acc: 52.82% | LR: 0.004613
Epoch: 043 | Train loss: 1.0000 | Train acc: 50.41% | Val loss: 0.9869 | Val acc: 52.72% | LR: 0.004566
Epoch: 044 | Train loss: 0.9948 | Train acc: 50.63% | Val loss: 0.9415 | Val acc: 52.72% | LR: 0.004518
Epoch: 045 | Train loss: 0.9994 | Train acc: 50.22% | Val loss: 0.9950 | Val acc: 53.19% | LR: 0.004469
Epoch: 046 | Train loss: 0.9941 | Train acc: 50.95% | Val loss: 0.9757 | Val acc: 53.62% | LR: 0.004420
Epoch: 047 | Train loss: 1.0025 | Train acc: 50.30% | Val loss: 0.9670 | Val acc: 53.49% | LR: 0.004370
Epoch: 048 | Train loss: 0.9990 | Train acc: 50.09% | Val loss: 0.9649 | Val acc: 53.88% | LR: 0.004320
Epoch: 049 | Train loss: 0.9965 | Train acc: 50.39% | Val loss: 0.9985 | Val acc: 46.03% | LR: 0.004268
Epoch: 050 | Train loss: 0.9956 | Train acc: 50.75% | Val loss: 0.9946 | Val acc: 54.12% | LR: 0.004216
Epoch: 051 | Train loss: 0.9983 | Train acc: 50.55% | Val loss: 0.9937 | Val acc: 53.05% | LR: 0.004164
Epoch: 052 | Train loss: 0.9983 | Train acc: 50.73% | Val loss: 1.0016 | Val acc: 51.43% | LR: 0.004111
Epoch: 053 | Train loss: 0.9952 | Train acc: 50.56% | Val loss: 0.9890 | Val acc: 51.68% | LR: 0.004057
Epoch: 054 | Train loss: 0.9990 | Train acc: 50.30% | Val loss: 0.9889 | Val acc: 51.73% | LR: 0.004003
Epoch: 055 | Train loss: 0.9957 | Train acc: 50.35% | Val loss: 0.9785 | Val acc: 51.80% | LR: 0.003948
Epoch: 056 | Train loss: 1.0009 | Train acc: 50.02% | Val loss: 0.9857 | Val acc: 51.50% | LR: 0.003893
Epoch: 057 | Train loss: 1.0003 | Train acc: 50.31% | Val loss: 0.9905 | Val acc: 51.28% | LR: 0.003837
Epoch: 058 | Train loss: 0.9878 | Train acc: 50.85% | Val loss: 0.9814 | Val acc: 51.48% | LR: 0.003781
Epoch: 059 | Train loss: 0.9950 | Train acc: 50.60% | Val loss: 0.9971 | Val acc: 50.43% | LR: 0.003725
Epoch: 060 | Train loss: 0.9976 | Train acc: 50.41% | Val loss: 0.9906 | Val acc: 51.09% | LR: 0.003668
Epoch: 061 | Train loss: 1.0012 | Train acc: 50.36% | Val loss: 0.9899 | Val acc: 50.71% | LR: 0.003611
Epoch: 062 | Train loss: 0.9963 | Train acc: 50.64% | Val loss: 0.9969 | Val acc: 50.42% | LR: 0.003553
Epoch: 063 | Train loss: 0.9958 | Train acc: 50.65% | Val loss: 0.9859 | Val acc: 51.28% | LR: 0.003495
Epoch: 064 | Train loss: 0.9931 | Train acc: 50.61% | Val loss: 0.9816 | Val acc: 51.40% | LR: 0.003437
Epoch: 065 | Train loss: 0.9985 | Train acc: 50.29% | Val loss: 0.9936 | Val acc: 50.61% | LR: 0.003379
Epoch: 066 | Train loss: 0.9902 | Train acc: 51.34% | Val loss: 0.9964 | Val acc: 50.90% | LR: 0.003320
Epoch: 067 | Train loss: 0.9936 | Train acc: 50.71% | Val loss: 0.9877 | Val acc: 50.90% | LR: 0.003261
Epoch: 068 | Train loss: 0.9907 | Train acc: 50.80% | Val loss: 0.9966 | Val acc: 49.95% | LR: 0.003202
Epoch: 069 | Train loss: 0.9963 | Train acc: 50.42% | Val loss: 0.9864 | Val acc: 50.98% | LR: 0.003143
Epoch: 070 | Train loss: 0.9954 | Train acc: 50.52% | Val loss: 0.9873 | Val acc: 50.57% | LR: 0.003084
Epoch: 071 | Train loss: 0.9868 | Train acc: 51.22% | Val loss: 0.9928 | Val acc: 50.54% | LR: 0.003024
Epoch: 072 | Train loss: 0.9942 | Train acc: 50.50% | Val loss: 0.9954 | Val acc: 50.59% | LR: 0.002965
Epoch: 073 | Train loss: 0.9901 | Train acc: 51.07% | Val loss: 0.9963 | Val acc: 49.88% | LR: 0.002905
Epoch: 074 | Train loss: 0.9939 | Train acc: 50.73% | Val loss: 0.9860 | Val acc: 50.81% | LR: 0.002846
Epoch: 075 | Train loss: 0.9901 | Train acc: 50.76% | Val loss: 0.9998 | Val acc: 49.68% | LR: 0.002786
Epoch: 076 | Train loss: 0.9842 | Train acc: 51.28% | Val loss: 0.9876 | Val acc: 51.02% | LR: 0.002727
Epoch: 077 | Train loss: 0.9940 | Train acc: 51.05% | Val loss: 0.9976 | Val acc: 50.38% | LR: 0.002667
Epoch: 078 | Train loss: 0.9831 | Train acc: 51.55% | Val loss: 0.9902 | Val acc: 50.29% | LR: 0.002608
Epoch: 079 | Train loss: 0.9912 | Train acc: 51.09% | Val loss: 1.0029 | Val acc: 49.97% | LR: 0.002548
Epoch: 080 | Train loss: 0.9977 | Train acc: 50.87% | Val loss: 1.0359 | Val acc: 47.72% | LR: 0.002489
Epoch: 081 | Train loss: 0.9970 | Train acc: 50.32% | Val loss: 0.9986 | Val acc: 49.37% | LR: 0.002430
Epoch: 082 | Train loss: 0.9934 | Train acc: 50.63% | Val loss: 0.9916 | Val acc: 50.88% | LR: 0.002371
Epoch: 083 | Train loss: 0.9908 | Train acc: 50.92% | Val loss: 0.9946 | Val acc: 50.20% | LR: 0.002313
Epoch: 084 | Train loss: 0.9980 | Train acc: 50.08% | Val loss: 0.9776 | Val acc: 52.59% | LR: 0.002254
Epoch: 085 | Train loss: 1.0005 | Train acc: 50.00% | Val loss: 0.9599 | Val acc: 54.71% | LR: 0.002196
Epoch: 086 | Train loss: 0.9951 | Train acc: 50.39% | Val loss: 0.9717 | Val acc: 51.76% | LR: 0.002138
Epoch: 087 | Train loss: 0.9973 | Train acc: 50.03% | Val loss: 0.9873 | Val acc: 50.68% | LR: 0.002081
Epoch: 088 | Train loss: 0.9931 | Train acc: 50.82% | Val loss: 0.9646 | Val acc: 53.05% | LR: 0.002024
Epoch: 089 | Train loss: 0.9921 | Train acc: 50.83% | Val loss: 0.9767 | Val acc: 52.64% | LR: 0.001967
Epoch: 090 | Train loss: 0.9928 | Train acc: 50.97% | Val loss: 0.9689 | Val acc: 52.43% | LR: 0.001910
Epoch: 091 | Train loss: 0.9910 | Train acc: 50.91% | Val loss: 0.9809 | Val acc: 51.67% | LR: 0.001854
Epoch: 092 | Train loss: 0.9922 | Train acc: 51.04% | Val loss: 0.9801 | Val acc: 50.76% | LR: 0.001799
Epoch: 093 | Train loss: 0.9945 | Train acc: 50.70% | Val loss: 0.9841 | Val acc: 50.96% | LR: 0.001743
Epoch: 094 | Train loss: 0.9873 | Train acc: 50.96% | Val loss: 0.9787 | Val acc: 50.22% | LR: 0.001689
Epoch: 095 | Train loss: 0.9936 | Train acc: 51.30% | Val loss: 0.9974 | Val acc: 49.76% | LR: 0.001635
Epoch: 096 | Train loss: 0.9860 | Train acc: 51.14% | Val loss: 0.9863 | Val acc: 50.10% | LR: 0.001581
Epoch: 097 | Train loss: 0.9906 | Train acc: 50.80% | Val loss: 0.9997 | Val acc: 48.89% | LR: 0.001528
Epoch: 098 | Train loss: 0.9930 | Train acc: 50.65% | Val loss: 0.9913 | Val acc: 49.44% | LR: 0.001475
Epoch: 099 | Train loss: 0.9891 | Train acc: 50.70% | Val loss: 1.0008 | Val acc: 49.24% | LR: 0.001423
Epoch: 100 | Train loss: 0.9906 | Train acc: 50.98% | Val loss: 0.9973 | Val acc: 48.83% | LR: 0.001372
Epoch: 101 | Train loss: 0.9847 | Train acc: 51.52% | Val loss: 0.9944 | Val acc: 49.29% | LR: 0.001321
Epoch: 102 | Train loss: 0.9856 | Train acc: 51.11% | Val loss: 0.9994 | Val acc: 49.15% | LR: 0.001272
Epoch: 103 | Train loss: 0.9878 | Train acc: 50.94% | Val loss: 1.0052 | Val acc: 48.68% | LR: 0.001222
Epoch: 104 | Train loss: 0.9833 | Train acc: 51.30% | Val loss: 0.9992 | Val acc: 48.93% | LR: 0.001174
Epoch: 105 | Train loss: 0.9866 | Train acc: 51.17% | Val loss: 1.0062 | Val acc: 48.90% | LR: 0.001126
Epoch: 106 | Train loss: 0.9998 | Train acc: 51.05% | Val loss: 1.0129 | Val acc: 48.77% | LR: 0.001079
Epoch: 107 | Train loss: 0.9833 | Train acc: 51.58% | Val loss: 1.0118 | Val acc: 49.29% | LR: 0.001032
Epoch: 108 | Train loss: 0.9903 | Train acc: 50.97% | Val loss: 0.9982 | Val acc: 49.42% | LR: 0.000987
Epoch: 109 | Train loss: 0.9939 | Train acc: 50.88% | Val loss: 1.0033 | Val acc: 49.34% | LR: 0.000942
Epoch: 110 | Train loss: 0.9932 | Train acc: 50.64% | Val loss: 1.0020 | Val acc: 49.30% | LR: 0.000898
Epoch: 111 | Train loss: 0.9913 | Train acc: 50.86% | Val loss: 1.0013 | Val acc: 49.33% | LR: 0.000855
Epoch: 112 | Train loss: 0.9869 | Train acc: 50.90% | Val loss: 1.0016 | Val acc: 49.33% | LR: 0.000813
Epoch: 113 | Train loss: 0.9884 | Train acc: 51.01% | Val loss: 1.0009 | Val acc: 49.33% | LR: 0.000772
Epoch: 114 | Train loss: 0.9852 | Train acc: 51.19% | Val loss: 1.0027 | Val acc: 49.27% | LR: 0.000732
Epoch: 115 | Train loss: 0.9857 | Train acc: 51.04% | Val loss: 1.0035 | Val acc: 49.17% | LR: 0.000692
Epoch: 116 | Train loss: 0.9811 | Train acc: 51.56% | Val loss: 1.0053 | Val acc: 49.07% | LR: 0.000654
Epoch: 117 | Train loss: 0.9837 | Train acc: 51.33% | Val loss: 1.0051 | Val acc: 49.16% | LR: 0.000616
Epoch: 118 | Train loss: 0.9823 | Train acc: 51.54% | Val loss: 1.0152 | Val acc: 48.65% | LR: 0.000580
Epoch: 119 | Train loss: 0.9896 | Train acc: 50.67% | Val loss: 1.0090 | Val acc: 48.97% | LR: 0.000544
Epoch: 120 | Train loss: 0.9875 | Train acc: 51.12% | Val loss: 1.0078 | Val acc: 48.99% | LR: 0.000510
Epoch: 121 | Train loss: 0.9920 | Train acc: 50.63% | Val loss: 1.0072 | Val acc: 48.87% | LR: 0.000476
Epoch: 122 | Train loss: 0.9898 | Train acc: 51.02% | Val loss: 1.0058 | Val acc: 49.11% | LR: 0.000444
Epoch: 123 | Train loss: 0.9866 | Train acc: 51.06% | Val loss: 1.0063 | Val acc: 49.13% | LR: 0.000412
Epoch: 124 | Train loss: 0.9797 | Train acc: 51.52% | Val loss: 1.0065 | Val acc: 48.87% | LR: 0.000382
Epoch: 125 | Train loss: 0.9826 | Train acc: 51.27% | Val loss: 1.0100 | Val acc: 48.94% | LR: 0.000353
Epoch: 126 | Train loss: 0.9902 | Train acc: 50.86% | Val loss: 1.0083 | Val acc: 48.93% | LR: 0.000325
Epoch: 127 | Train loss: 0.9881 | Train acc: 51.09% | Val loss: 1.0081 | Val acc: 49.13% | LR: 0.000298
Epoch: 128 | Train loss: 0.9836 | Train acc: 51.37% | Val loss: 1.0072 | Val acc: 49.15% | LR: 0.000272
Epoch: 129 | Train loss: 0.9817 | Train acc: 51.25% | Val loss: 1.0081 | Val acc: 49.01% | LR: 0.000247
Epoch: 130 | Train loss: 0.9831 | Train acc: 51.31% | Val loss: 1.0092 | Val acc: 48.91% | LR: 0.000223
Epoch: 131 | Train loss: 0.9751 | Train acc: 51.82% | Val loss: 1.0099 | Val acc: 49.03% | LR: 0.000201
Epoch: 132 | Train loss: 0.9866 | Train acc: 50.97% | Val loss: 1.0090 | Val acc: 48.93% | LR: 0.000179
Epoch: 133 | Train loss: 0.9776 | Train acc: 51.68% | Val loss: 1.0090 | Val acc: 49.05% | LR: 0.000159
Epoch: 134 | Train loss: 0.9836 | Train acc: 51.29% | Val loss: 1.0092 | Val acc: 48.95% | LR: 0.000140
Epoch: 135 | Train loss: 0.9876 | Train acc: 51.04% | Val loss: 1.0083 | Val acc: 49.01% | LR: 0.000122
Epoch: 136 | Train loss: 0.9855 | Train acc: 51.21% | Val loss: 1.0087 | Val acc: 48.97% | LR: 0.000106
Epoch: 137 | Train loss: 0.9830 | Train acc: 51.13% | Val loss: 1.0087 | Val acc: 49.03% | LR: 0.000090
Epoch: 138 | Train loss: 0.9876 | Train acc: 51.07% | Val loss: 1.0084 | Val acc: 48.99% | LR: 0.000076
Epoch: 139 | Train loss: 0.9840 | Train acc: 51.21% | Val loss: 1.0086 | Val acc: 49.01% | LR: 0.000063
Epoch: 140 | Train loss: 0.9784 | Train acc: 51.53% | Val loss: 1.0086 | Val acc: 49.01% | LR: 0.000051
Epoch: 141 | Train loss: 0.9837 | Train acc: 51.16% | Val loss: 1.0086 | Val acc: 49.05% | LR: 0.000041
Epoch: 142 | Train loss: 0.9896 | Train acc: 50.71% | Val loss: 1.0086 | Val acc: 49.03% | LR: 0.000032
Epoch: 143 | Train loss: 0.9840 | Train acc: 51.15% | Val loss: 1.0086 | Val acc: 49.03% | LR: 0.000023
Epoch: 144 | Train loss: 0.9874 | Train acc: 50.98% | Val loss: 1.0087 | Val acc: 49.01% | LR: 0.000017
Epoch: 145 | Train loss: 0.9779 | Train acc: 51.52% | Val loss: 1.0088 | Val acc: 49.03% | LR: 0.000011
Epoch: 146 | Train loss: 0.9839 | Train acc: 51.04% | Val loss: 1.0088 | Val acc: 49.03% | LR: 0.000007
Epoch: 147 | Train loss: 0.9830 | Train acc: 51.17% | Val loss: 1.0088 | Val acc: 49.03% | LR: 0.000003
Epoch: 148 | Train loss: 0.9877 | Train acc: 50.82% | Val loss: 1.0088 | Val acc: 49.03% | LR: 0.000002
Epoch: 149 | Train loss: 0.9849 | Train acc: 51.05% | Val loss: 1.0088 | Val acc: 49.03% | LR: 0.000001

[I 2025-09-23 03:02:46,229] Trial 33 finished with value: 0.5473020076751709 and parameters: {'lr': 0.005690672353959115, 'hidden_size': 124, 'dropout': 0.3269429304994287, 'weight_decay': 0.727999471270248}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 0.9978 | Train acc: 50.27% | Val loss: 1.1214 | Val acc: 46.37% | LR: 0.003387
Epoch: 001 | Train loss: 0.9993 | Train acc: 50.51% | Val loss: 1.0683 | Val acc: 52.05% | LR: 0.003386
Epoch: 002 | Train loss: 1.0228 | Train acc: 50.34% | Val loss: 0.9508 | Val acc: 53.36% | LR: 0.003384
Epoch: 003 | Train loss: 0.9942 | Train acc: 50.57% | Val loss: 0.9755 | Val acc: 51.97% | LR: 0.003381
Epoch: 004 | Train loss: 1.0147 | Train acc: 50.42% | Val loss: 0.9836 | Val acc: 53.89% | LR: 0.003378
Epoch: 005 | Train loss: 0.9988 | Train acc: 50.37% | Val loss: 1.0312 | Val acc: 48.26% | LR: 0.003374
Epoch: 006 | Train loss: 1.0245 | Train acc: 50.59% | Val loss: 1.0484 | Val acc: 46.10% | LR: 0.003369
Epoch: 007 | Train loss: 0.9950 | Train acc: 50.90% | Val loss: 1.0700 | Val acc: 44.76% | LR: 0.003363
Epoch: 008 | Train loss: 1.0028 | Train acc: 50.34% | Val loss: 1.0452 | Val acc: 52.17% | LR: 0.003357
Epoch: 009 | Train loss: 0.9972 | Train acc: 50.82% | Val loss: 0.9645 | Val acc: 52.27% | LR: 0.003350
Epoch: 010 | Train loss: 0.9973 | Train acc: 50.55% | Val loss: 0.9564 | Val acc: 54.32% | LR: 0.003342
Epoch: 011 | Train loss: 0.9916 | Train acc: 51.08% | Val loss: 0.9536 | Val acc: 53.50% | LR: 0.003334
Epoch: 012 | Train loss: 0.9954 | Train acc: 50.43% | Val loss: 0.9558 | Val acc: 53.84% | LR: 0.003325
Epoch: 013 | Train loss: 0.9952 | Train acc: 51.05% | Val loss: 0.9529 | Val acc: 54.06% | LR: 0.003315
Epoch: 014 | Train loss: 0.9998 | Train acc: 50.27% | Val loss: 0.9908 | Val acc: 53.77% | LR: 0.003304
Epoch: 015 | Train loss: 0.9976 | Train acc: 50.11% | Val loss: 0.9345 | Val acc: 53.87% | LR: 0.003293
Epoch: 016 | Train loss: 0.9990 | Train acc: 50.67% | Val loss: 0.9757 | Val acc: 53.77% | LR: 0.003281
Epoch: 017 | Train loss: 0.9928 | Train acc: 50.99% | Val loss: 1.0015 | Val acc: 49.40% | LR: 0.003268
Epoch: 018 | Train loss: 0.9999 | Train acc: 50.12% | Val loss: 0.9794 | Val acc: 54.05% | LR: 0.003255
Epoch: 019 | Train loss: 1.0001 | Train acc: 50.45% | Val loss: 1.0405 | Val acc: 45.95% | LR: 0.003241
Epoch: 020 | Train loss: 0.9972 | Train acc: 50.81% | Val loss: 1.0182 | Val acc: 45.95% | LR: 0.003226
Epoch: 021 | Train loss: 0.9940 | Train acc: 50.63% | Val loss: 1.0653 | Val acc: 45.95% | LR: 0.003210
Epoch: 022 | Train loss: 0.9962 | Train acc: 50.65% | Val loss: 1.0120 | Val acc: 45.95% | LR: 0.003194
Epoch: 023 | Train loss: 0.9954 | Train acc: 50.53% | Val loss: 0.9746 | Val acc: 54.05% | LR: 0.003178
Epoch: 024 | Train loss: 1.0021 | Train acc: 49.87% | Val loss: 0.9677 | Val acc: 54.05% | LR: 0.003160
Epoch: 025 | Train loss: 0.9981 | Train acc: 50.20% | Val loss: 0.9951 | Val acc: 53.84% | LR: 0.003142
Epoch: 026 | Train loss: 1.0198 | Train acc: 49.90% | Val loss: 1.0169 | Val acc: 45.95% | LR: 0.003124
Epoch: 027 | Train loss: 0.9982 | Train acc: 50.14% | Val loss: 1.0091 | Val acc: 45.95% | LR: 0.003104
Epoch: 028 | Train loss: 1.0002 | Train acc: 50.53% | Val loss: 0.9880 | Val acc: 54.07% | LR: 0.003084
Epoch: 029 | Train loss: 0.9986 | Train acc: 50.39% | Val loss: 0.9763 | Val acc: 54.05% | LR: 0.003064
Epoch: 030 | Train loss: 1.0002 | Train acc: 50.12% | Val loss: 0.9948 | Val acc: 52.31% | LR: 0.003043
Epoch: 031 | Train loss: 1.0013 | Train acc: 50.22% | Val loss: 0.9620 | Val acc: 54.22% | LR: 0.003021
Epoch: 032 | Train loss: 1.0039 | Train acc: 49.91% | Val loss: 1.0104 | Val acc: 49.13% | LR: 0.002999
Epoch: 033 | Train loss: 0.9946 | Train acc: 50.42% | Val loss: 1.0193 | Val acc: 48.92% | LR: 0.002976
Epoch: 034 | Train loss: 0.9847 | Train acc: 51.48% | Val loss: 0.9659 | Val acc: 54.26% | LR: 0.002952
Epoch: 035 | Train loss: 0.9978 | Train acc: 50.93% | Val loss: 0.9459 | Val acc: 53.23% | LR: 0.002928
Epoch: 036 | Train loss: 0.9925 | Train acc: 51.11% | Val loss: 0.9599 | Val acc: 51.23% | LR: 0.002904
Epoch: 037 | Train loss: 0.9937 | Train acc: 50.34% | Val loss: 0.9833 | Val acc: 53.82% | LR: 0.002879
Epoch: 038 | Train loss: 0.9993 | Train acc: 50.03% | Val loss: 0.9684 | Val acc: 54.67% | LR: 0.002853
Epoch: 039 | Train loss: 0.9984 | Train acc: 50.60% | Val loss: 0.9492 | Val acc: 53.29% | LR: 0.002827
Epoch: 040 | Train loss: 0.9988 | Train acc: 50.53% | Val loss: 0.9518 | Val acc: 54.82% | LR: 0.002800
Epoch: 041 | Train loss: 0.9938 | Train acc: 50.51% | Val loss: 1.0653 | Val acc: 49.65% | LR: 0.002773
Epoch: 042 | Train loss: 0.9944 | Train acc: 50.56% | Val loss: 1.0140 | Val acc: 48.75% | LR: 0.002746
Epoch: 043 | Train loss: 1.0024 | Train acc: 50.02% | Val loss: 0.9607 | Val acc: 54.05% | LR: 0.002718
Epoch: 044 | Train loss: 0.9967 | Train acc: 50.75% | Val loss: 0.9507 | Val acc: 54.05% | LR: 0.002689
Epoch: 045 | Train loss: 0.9963 | Train acc: 50.48% | Val loss: 1.0233 | Val acc: 45.95% | LR: 0.002660
Epoch: 046 | Train loss: 1.0029 | Train acc: 49.93% | Val loss: 1.0268 | Val acc: 45.95% | LR: 0.002631
Epoch: 047 | Train loss: 0.9964 | Train acc: 50.48% | Val loss: 0.9757 | Val acc: 54.05% | LR: 0.002601
Epoch: 048 | Train loss: 0.9961 | Train acc: 50.60% | Val loss: 1.0240 | Val acc: 45.95% | LR: 0.002571
Epoch: 049 | Train loss: 0.9951 | Train acc: 50.21% | Val loss: 1.0171 | Val acc: 46.50% | LR: 0.002541
Epoch: 050 | Train loss: 1.0093 | Train acc: 50.71% | Val loss: 1.0330 | Val acc: 45.95% | LR: 0.002510
Epoch: 051 | Train loss: 0.9984 | Train acc: 50.06% | Val loss: 0.9923 | Val acc: 50.64% | LR: 0.002478
Epoch: 052 | Train loss: 0.9955 | Train acc: 50.89% | Val loss: 0.9793 | Val acc: 50.38% | LR: 0.002447
Epoch: 053 | Train loss: 1.0005 | Train acc: 50.40% | Val loss: 1.0134 | Val acc: 47.15% | LR: 0.002415
Epoch: 054 | Train loss: 1.0025 | Train acc: 49.62% | Val loss: 1.0076 | Val acc: 49.14% | LR: 0.002383
Epoch: 055 | Train loss: 0.9962 | Train acc: 50.07% | Val loss: 0.9795 | Val acc: 49.97% | LR: 0.002350
Epoch: 056 | Train loss: 0.9968 | Train acc: 50.59% | Val loss: 1.0041 | Val acc: 49.87% | LR: 0.002317
Epoch: 057 | Train loss: 0.9937 | Train acc: 50.71% | Val loss: 0.9926 | Val acc: 49.69% | LR: 0.002284
Epoch: 058 | Train loss: 0.9974 | Train acc: 50.38% | Val loss: 0.9799 | Val acc: 49.71% | LR: 0.002251
Epoch: 059 | Train loss: 0.9946 | Train acc: 50.52% | Val loss: 1.0085 | Val acc: 48.10% | LR: 0.002217
Epoch: 060 | Train loss: 0.9922 | Train acc: 50.08% | Val loss: 1.0022 | Val acc: 49.69% | LR: 0.002183
Epoch: 061 | Train loss: 0.9914 | Train acc: 50.26% | Val loss: 1.0043 | Val acc: 49.16% | LR: 0.002149
Epoch: 062 | Train loss: 0.9878 | Train acc: 50.90% | Val loss: 1.0107 | Val acc: 49.71% | LR: 0.002115
Epoch: 063 | Train loss: 0.9985 | Train acc: 50.91% | Val loss: 1.0229 | Val acc: 49.99% | LR: 0.002081
Epoch: 064 | Train loss: 0.9950 | Train acc: 50.87% | Val loss: 1.0873 | Val acc: 47.30% | LR: 0.002046
Epoch: 065 | Train loss: 0.9983 | Train acc: 50.31% | Val loss: 0.9998 | Val acc: 51.77% | LR: 0.002011
Epoch: 066 | Train loss: 1.0324 | Train acc: 50.11% | Val loss: 0.9971 | Val acc: 52.37% | LR: 0.001976
Epoch: 067 | Train loss: 0.9935 | Train acc: 50.67% | Val loss: 1.0096 | Val acc: 47.62% | LR: 0.001941
Epoch: 068 | Train loss: 0.9947 | Train acc: 50.81% | Val loss: 0.9953 | Val acc: 48.91% | LR: 0.001906
Epoch: 069 | Train loss: 0.9948 | Train acc: 50.43% | Val loss: 0.9657 | Val acc: 52.55% | LR: 0.001871
Epoch: 070 | Train loss: 0.9964 | Train acc: 50.47% | Val loss: 1.0354 | Val acc: 48.26% | LR: 0.001836
Epoch: 071 | Train loss: 0.9899 | Train acc: 51.12% | Val loss: 1.0039 | Val acc: 50.37% | LR: 0.001800
Epoch: 072 | Train loss: 0.9916 | Train acc: 50.80% | Val loss: 0.9778 | Val acc: 51.67% | LR: 0.001765
Epoch: 073 | Train loss: 0.9863 | Train acc: 51.11% | Val loss: 1.0158 | Val acc: 50.34% | LR: 0.001729
Epoch: 074 | Train loss: 0.9921 | Train acc: 50.57% | Val loss: 0.9770 | Val acc: 50.49% | LR: 0.001694
Epoch: 075 | Train loss: 0.9865 | Train acc: 51.34% | Val loss: 1.0230 | Val acc: 49.88% | LR: 0.001659
Epoch: 076 | Train loss: 0.9840 | Train acc: 51.29% | Val loss: 1.0113 | Val acc: 49.66% | LR: 0.001623
Epoch: 077 | Train loss: 0.9903 | Train acc: 50.69% | Val loss: 0.9776 | Val acc: 50.39% | LR: 0.001588
Epoch: 078 | Train loss: 0.9903 | Train acc: 50.80% | Val loss: 1.0019 | Val acc: 50.18% | LR: 0.001552
Epoch: 079 | Train loss: 0.9823 | Train acc: 51.41% | Val loss: 1.0036 | Val acc: 50.46% | LR: 0.001517
Epoch: 080 | Train loss: 0.9855 | Train acc: 50.99% | Val loss: 0.9962 | Val acc: 50.86% | LR: 0.001482
Epoch: 081 | Train loss: 0.9898 | Train acc: 50.75% | Val loss: 1.0084 | Val acc: 50.23% | LR: 0.001447
Epoch: 082 | Train loss: 0.9874 | Train acc: 51.12% | Val loss: 1.0026 | Val acc: 50.31% | LR: 0.001412
Epoch: 083 | Train loss: 0.9793 | Train acc: 51.37% | Val loss: 1.0009 | Val acc: 49.96% | LR: 0.001377
Epoch: 084 | Train loss: 0.9850 | Train acc: 51.18% | Val loss: 1.0232 | Val acc: 49.93% | LR: 0.001342
Epoch: 085 | Train loss: 0.9842 | Train acc: 51.02% | Val loss: 1.0057 | Val acc: 50.04% | LR: 0.001307
Epoch: 086 | Train loss: 0.9949 | Train acc: 50.50% | Val loss: 1.0250 | Val acc: 49.01% | LR: 0.001273
Epoch: 087 | Train loss: 0.9863 | Train acc: 51.04% | Val loss: 1.0247 | Val acc: 49.06% | LR: 0.001239
Epoch: 088 | Train loss: 0.9792 | Train acc: 51.46% | Val loss: 1.0045 | Val acc: 49.73% | LR: 0.001205
Epoch: 089 | Train loss: 0.9785 | Train acc: 51.47% | Val loss: 0.9987 | Val acc: 49.92% | LR: 0.001171
Epoch: 090 | Train loss: 0.9778 | Train acc: 51.43% | Val loss: 1.0018 | Val acc: 50.11% | LR: 0.001137
Epoch: 091 | Train loss: 0.9877 | Train acc: 50.85% | Val loss: 0.9942 | Val acc: 50.24% | LR: 0.001104
Epoch: 092 | Train loss: 0.9947 | Train acc: 50.69% | Val loss: 1.0032 | Val acc: 49.96% | LR: 0.001071
Epoch: 093 | Train loss: 0.9859 | Train acc: 50.94% | Val loss: 1.0067 | Val acc: 50.49% | LR: 0.001038
Epoch: 094 | Train loss: 0.9884 | Train acc: 50.89% | Val loss: 0.9958 | Val acc: 50.26% | LR: 0.001005
Epoch: 095 | Train loss: 0.9918 | Train acc: 50.61% | Val loss: 0.9920 | Val acc: 50.32% | LR: 0.000973
Epoch: 096 | Train loss: 0.9799 | Train acc: 51.44% | Val loss: 1.0012 | Val acc: 50.11% | LR: 0.000941
Epoch: 097 | Train loss: 0.9732 | Train acc: 51.71% | Val loss: 0.9974 | Val acc: 49.80% | LR: 0.000910
Epoch: 098 | Train loss: 0.9889 | Train acc: 50.70% | Val loss: 1.0022 | Val acc: 50.04% | LR: 0.000878
Epoch: 099 | Train loss: 0.9792 | Train acc: 51.49% | Val loss: 0.9916 | Val acc: 50.13% | LR: 0.000848
Epoch: 100 | Train loss: 0.9822 | Train acc: 51.23% | Val loss: 0.9923 | Val acc: 50.50% | LR: 0.000817
Epoch: 101 | Train loss: 0.9896 | Train acc: 50.70% | Val loss: 0.9939 | Val acc: 51.20% | LR: 0.000787
Epoch: 102 | Train loss: 0.9811 | Train acc: 51.15% | Val loss: 0.9963 | Val acc: 50.39% | LR: 0.000757
Epoch: 103 | Train loss: 0.9805 | Train acc: 51.26% | Val loss: 0.9981 | Val acc: 50.65% | LR: 0.000728
Epoch: 104 | Train loss: 0.9800 | Train acc: 51.33% | Val loss: 0.9835 | Val acc: 51.15% | LR: 0.000699
Epoch: 105 | Train loss: 0.9911 | Train acc: 50.59% | Val loss: 1.0014 | Val acc: 49.99% | LR: 0.000670
Epoch: 106 | Train loss: 0.9756 | Train acc: 51.60% | Val loss: 1.0195 | Val acc: 50.10% | LR: 0.000642
Epoch: 107 | Train loss: 0.9820 | Train acc: 51.35% | Val loss: 0.9977 | Val acc: 49.71% | LR: 0.000615
Epoch: 108 | Train loss: 0.9899 | Train acc: 50.71% | Val loss: 1.0004 | Val acc: 49.79% | LR: 0.000588
Epoch: 109 | Train loss: 0.9828 | Train acc: 51.15% | Val loss: 0.9994 | Val acc: 50.24% | LR: 0.000561
Epoch: 110 | Train loss: 0.9867 | Train acc: 50.86% | Val loss: 0.9931 | Val acc: 50.89% | LR: 0.000535
Epoch: 111 | Train loss: 0.9773 | Train acc: 51.42% | Val loss: 0.9963 | Val acc: 50.52% | LR: 0.000509
Epoch: 112 | Train loss: 0.9781 | Train acc: 51.33% | Val loss: 0.9924 | Val acc: 50.70% | LR: 0.000484
Epoch: 113 | Train loss: 0.9848 | Train acc: 50.94% | Val loss: 1.0140 | Val acc: 49.35% | LR: 0.000460
Epoch: 114 | Train loss: 0.9799 | Train acc: 51.20% | Val loss: 1.0074 | Val acc: 49.76% | LR: 0.000436
Epoch: 115 | Train loss: 0.9826 | Train acc: 51.17% | Val loss: 1.0018 | Val acc: 49.96% | LR: 0.000412
Epoch: 116 | Train loss: 0.9759 | Train acc: 51.54% | Val loss: 1.0186 | Val acc: 49.49% | LR: 0.000390
Epoch: 117 | Train loss: 0.9792 | Train acc: 51.27% | Val loss: 1.0055 | Val acc: 49.61% | LR: 0.000367
Epoch: 118 | Train loss: 0.9865 | Train acc: 50.85% | Val loss: 1.0016 | Val acc: 49.80% | LR: 0.000345
Epoch: 119 | Train loss: 0.9830 | Train acc: 51.14% | Val loss: 1.0015 | Val acc: 50.01% | LR: 0.000324
Epoch: 120 | Train loss: 0.9839 | Train acc: 50.97% | Val loss: 1.0006 | Val acc: 49.75% | LR: 0.000304
Epoch: 121 | Train loss: 0.9807 | Train acc: 51.17% | Val loss: 1.0049 | Val acc: 49.90% | LR: 0.000284
Epoch: 122 | Train loss: 0.9681 | Train acc: 51.87% | Val loss: 1.0036 | Val acc: 50.03% | LR: 0.000265
Epoch: 123 | Train loss: 0.9727 | Train acc: 51.62% | Val loss: 1.0052 | Val acc: 49.77% | LR: 0.000246
Epoch: 124 | Train loss: 0.9752 | Train acc: 51.48% | Val loss: 1.0073 | Val acc: 49.66% | LR: 0.000228
Epoch: 125 | Train loss: 0.9745 | Train acc: 51.48% | Val loss: 1.0054 | Val acc: 49.68% | LR: 0.000210
Epoch: 126 | Train loss: 0.9857 | Train acc: 50.78% | Val loss: 1.0048 | Val acc: 49.80% | LR: 0.000194
Epoch: 127 | Train loss: 0.9780 | Train acc: 51.26% | Val loss: 1.0066 | Val acc: 49.64% | LR: 0.000178
Epoch: 128 | Train loss: 0.9741 | Train acc: 51.46% | Val loss: 1.0056 | Val acc: 49.76% | LR: 0.000162
Epoch: 129 | Train loss: 0.9859 | Train acc: 50.78% | Val loss: 1.0049 | Val acc: 49.68% | LR: 0.000147
Epoch: 130 | Train loss: 0.9778 | Train acc: 51.28% | Val loss: 1.0056 | Val acc: 49.80% | LR: 0.000133
Epoch: 131 | Train loss: 0.9770 | Train acc: 51.29% | Val loss: 1.0044 | Val acc: 49.72% | LR: 0.000120
Epoch: 132 | Train loss: 0.9697 | Train acc: 51.72% | Val loss: 1.0035 | Val acc: 49.94% | LR: 0.000107
Epoch: 133 | Train loss: 0.9690 | Train acc: 51.83% | Val loss: 1.0049 | Val acc: 49.80% | LR: 0.000095
Epoch: 134 | Train loss: 0.9844 | Train acc: 50.94% | Val loss: 1.0068 | Val acc: 49.64% | LR: 0.000084
Epoch: 135 | Train loss: 0.9791 | Train acc: 51.19% | Val loss: 1.0052 | Val acc: 49.74% | LR: 0.000073
Epoch: 136 | Train loss: 0.9851 | Train acc: 50.85% | Val loss: 1.0056 | Val acc: 49.82% | LR: 0.000063
Epoch: 137 | Train loss: 0.9649 | Train acc: 52.11% | Val loss: 1.0064 | Val acc: 49.72% | LR: 0.000054
Epoch: 138 | Train loss: 0.9786 | Train acc: 51.22% | Val loss: 1.0060 | Val acc: 49.90% | LR: 0.000046
Epoch: 139 | Train loss: 0.9732 | Train acc: 51.48% | Val loss: 1.0056 | Val acc: 49.94% | LR: 0.000038
Epoch: 140 | Train loss: 0.9757 | Train acc: 51.40% | Val loss: 1.0069 | Val acc: 49.84% | LR: 0.000031
Epoch: 141 | Train loss: 0.9819 | Train acc: 51.04% | Val loss: 1.0067 | Val acc: 49.74% | LR: 0.000025
Epoch: 142 | Train loss: 0.9686 | Train acc: 51.84% | Val loss: 1.0061 | Val acc: 49.84% | LR: 0.000019
Epoch: 143 | Train loss: 0.9743 | Train acc: 51.50% | Val loss: 1.0066 | Val acc: 49.74% | LR: 0.000014
Epoch: 144 | Train loss: 0.9754 | Train acc: 51.42% | Val loss: 1.0063 | Val acc: 49.84% | LR: 0.000010
Epoch: 145 | Train loss: 0.9722 | Train acc: 51.58% | Val loss: 1.0063 | Val acc: 49.82% | LR: 0.000007
Epoch: 146 | Train loss: 0.9716 | Train acc: 51.67% | Val loss: 1.0062 | Val acc: 49.82% | LR: 0.000004
Epoch: 147 | Train loss: 0.9763 | Train acc: 51.42% | Val loss: 1.0062 | Val acc: 49.84% | LR: 0.000002
Epoch: 148 | Train loss: 0.9684 | Train acc: 51.85% | Val loss: 1.0063 | Val acc: 49.82% | LR: 0.000001
Epoch: 149 | Train loss: 0.9699 | Train acc: 51.83% | Val loss: 1.0063 | Val acc: 49.80% | LR: 0.000001

[I 2025-09-23 03:04:54,875] Trial 34 finished with value: 0.5482401609420776 and parameters: {'lr': 0.003387060731314686, 'hidden_size': 231, 'dropout': 0.45564908876550736, 'weight_decay': 0.4332027099386499}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.0148 | Train acc: 49.74% | Val loss: 0.9931 | Val acc: 53.73% | LR: 0.002009
Epoch: 001 | Train loss: 0.9986 | Train acc: 50.46% | Val loss: 0.9751 | Val acc: 54.30% | LR: 0.002009
Epoch: 002 | Train loss: 0.9921 | Train acc: 50.73% | Val loss: 0.9850 | Val acc: 54.08% | LR: 0.002007
Epoch: 003 | Train loss: 0.9953 | Train acc: 50.59% | Val loss: 0.9937 | Val acc: 51.06% | LR: 0.002006
Epoch: 004 | Train loss: 0.9889 | Train acc: 51.24% | Val loss: 0.9847 | Val acc: 51.07% | LR: 0.002004
Epoch: 005 | Train loss: 0.9967 | Train acc: 50.39% | Val loss: 0.9968 | Val acc: 49.92% | LR: 0.002002
Epoch: 006 | Train loss: 0.9902 | Train acc: 50.79% | Val loss: 0.9937 | Val acc: 49.84% | LR: 0.001999
Epoch: 007 | Train loss: 0.9850 | Train acc: 51.14% | Val loss: 0.9905 | Val acc: 50.38% | LR: 0.001995
Epoch: 008 | Train loss: 0.9927 | Train acc: 50.82% | Val loss: 0.9525 | Val acc: 53.82% | LR: 0.001992
Epoch: 009 | Train loss: 0.9887 | Train acc: 51.05% | Val loss: 0.9641 | Val acc: 52.63% | LR: 0.001988
Epoch: 010 | Train loss: 0.9896 | Train acc: 50.81% | Val loss: 0.9752 | Val acc: 52.51% | LR: 0.001983
Epoch: 011 | Train loss: 0.9899 | Train acc: 50.74% | Val loss: 0.9610 | Val acc: 53.43% | LR: 0.001978
Epoch: 012 | Train loss: 0.9874 | Train acc: 51.01% | Val loss: 0.9736 | Val acc: 52.17% | LR: 0.001972
Epoch: 013 | Train loss: 0.9858 | Train acc: 50.92% | Val loss: 0.9787 | Val acc: 52.17% | LR: 0.001967
Epoch: 014 | Train loss: 1.0016 | Train acc: 50.87% | Val loss: 0.9998 | Val acc: 49.89% | LR: 0.001960
Epoch: 015 | Train loss: 0.9896 | Train acc: 50.77% | Val loss: 1.0197 | Val acc: 49.06% | LR: 0.001954
Epoch: 016 | Train loss: 0.9821 | Train acc: 51.37% | Val loss: 1.0178 | Val acc: 49.00% | LR: 0.001946
Epoch: 017 | Train loss: 0.9795 | Train acc: 51.49% | Val loss: 1.0098 | Val acc: 49.55% | LR: 0.001939
Epoch: 018 | Train loss: 0.9855 | Train acc: 51.53% | Val loss: 1.0087 | Val acc: 49.38% | LR: 0.001931
Epoch: 019 | Train loss: 0.9960 | Train acc: 50.27% | Val loss: 0.9906 | Val acc: 50.79% | LR: 0.001923
Epoch: 020 | Train loss: 0.9890 | Train acc: 50.70% | Val loss: 0.9974 | Val acc: 50.21% | LR: 0.001914
Epoch: 021 | Train loss: 0.9840 | Train acc: 51.02% | Val loss: 1.0253 | Val acc: 48.92% | LR: 0.001905
Epoch: 022 | Train loss: 0.9834 | Train acc: 51.42% | Val loss: 1.0247 | Val acc: 49.05% | LR: 0.001895
Epoch: 023 | Train loss: 0.9822 | Train acc: 51.38% | Val loss: 0.9785 | Val acc: 50.50% | LR: 0.001885
Epoch: 024 | Train loss: 0.9904 | Train acc: 50.93% | Val loss: 0.9955 | Val acc: 50.16% | LR: 0.001875
Epoch: 025 | Train loss: 0.9865 | Train acc: 51.07% | Val loss: 0.9928 | Val acc: 50.22% | LR: 0.001864
Epoch: 026 | Train loss: 0.9858 | Train acc: 50.83% | Val loss: 1.0003 | Val acc: 50.27% | LR: 0.001853
Epoch: 027 | Train loss: 0.9855 | Train acc: 51.03% | Val loss: 1.0078 | Val acc: 49.52% | LR: 0.001842
Epoch: 028 | Train loss: 0.9887 | Train acc: 50.73% | Val loss: 0.9967 | Val acc: 50.08% | LR: 0.001830
Epoch: 029 | Train loss: 0.9794 | Train acc: 51.43% | Val loss: 1.0075 | Val acc: 49.73% | LR: 0.001818
Epoch: 030 | Train loss: 0.9820 | Train acc: 51.26% | Val loss: 1.0009 | Val acc: 49.75% | LR: 0.001805
Epoch: 031 | Train loss: 0.9866 | Train acc: 50.94% | Val loss: 0.9916 | Val acc: 50.63% | LR: 0.001792
Epoch: 032 | Train loss: 0.9796 | Train acc: 51.60% | Val loss: 0.9945 | Val acc: 51.34% | LR: 0.001779
Epoch: 033 | Train loss: 0.9962 | Train acc: 50.48% | Val loss: 0.9699 | Val acc: 52.05% | LR: 0.001765
Epoch: 034 | Train loss: 0.9866 | Train acc: 51.07% | Val loss: 0.9587 | Val acc: 52.79% | LR: 0.001752
Epoch: 035 | Train loss: 0.9900 | Train acc: 50.61% | Val loss: 0.9181 | Val acc: 54.41% | LR: 0.001737
Epoch: 036 | Train loss: 0.9929 | Train acc: 50.64% | Val loss: 0.9689 | Val acc: 53.42% | LR: 0.001723
Epoch: 037 | Train loss: 0.9827 | Train acc: 51.24% | Val loss: 0.9462 | Val acc: 53.52% | LR: 0.001708
Epoch: 038 | Train loss: 0.9809 | Train acc: 51.16% | Val loss: 0.9533 | Val acc: 53.48% | LR: 0.001693
Epoch: 039 | Train loss: 0.9926 | Train acc: 50.60% | Val loss: 0.9442 | Val acc: 53.95% | LR: 0.001677
Epoch: 040 | Train loss: 0.9787 | Train acc: 51.53% | Val loss: 0.9556 | Val acc: 52.90% | LR: 0.001661
Epoch: 041 | Train loss: 0.9864 | Train acc: 51.21% | Val loss: 0.9738 | Val acc: 51.78% | LR: 0.001645
Epoch: 042 | Train loss: 0.9790 | Train acc: 51.54% | Val loss: 0.9920 | Val acc: 50.54% | LR: 0.001629
Epoch: 043 | Train loss: 0.9857 | Train acc: 50.85% | Val loss: 0.9700 | Val acc: 51.66% | LR: 0.001612
Epoch: 044 | Train loss: 0.9809 | Train acc: 51.37% | Val loss: 0.9702 | Val acc: 51.76% | LR: 0.001596
Epoch: 045 | Train loss: 0.9854 | Train acc: 50.98% | Val loss: 0.9830 | Val acc: 51.20% | LR: 0.001578
Epoch: 046 | Train loss: 0.9875 | Train acc: 50.81% | Val loss: 0.9896 | Val acc: 50.78% | LR: 0.001561
Epoch: 047 | Train loss: 0.9877 | Train acc: 50.79% | Val loss: 0.9991 | Val acc: 50.14% | LR: 0.001543
Epoch: 048 | Train loss: 0.9895 | Train acc: 51.27% | Val loss: 1.0025 | Val acc: 49.77% | LR: 0.001525
Epoch: 049 | Train loss: 0.9900 | Train acc: 50.74% | Val loss: 0.9839 | Val acc: 50.94% | LR: 0.001507
Epoch: 050 | Train loss: 0.9883 | Train acc: 50.71% | Val loss: 0.9836 | Val acc: 51.21% | LR: 0.001489
Epoch: 051 | Train loss: 0.9864 | Train acc: 51.22% | Val loss: 0.9676 | Val acc: 51.87% | LR: 0.001470
Epoch: 052 | Train loss: 0.9839 | Train acc: 51.09% | Val loss: 0.9753 | Val acc: 51.58% | LR: 0.001452
Epoch: 053 | Train loss: 0.9891 | Train acc: 50.94% | Val loss: 0.9763 | Val acc: 51.91% | LR: 0.001433
Epoch: 054 | Train loss: 0.9860 | Train acc: 50.83% | Val loss: 0.9758 | Val acc: 51.76% | LR: 0.001414
Epoch: 055 | Train loss: 0.9858 | Train acc: 51.07% | Val loss: 0.9843 | Val acc: 51.20% | LR: 0.001394
Epoch: 056 | Train loss: 0.9852 | Train acc: 50.93% | Val loss: 0.9853 | Val acc: 51.07% | LR: 0.001375
Epoch: 057 | Train loss: 0.9858 | Train acc: 51.22% | Val loss: 0.9882 | Val acc: 54.13% | LR: 0.001355
Epoch: 058 | Train loss: 0.9935 | Train acc: 50.28% | Val loss: 0.9527 | Val acc: 54.05% | LR: 0.001335
Epoch: 059 | Train loss: 0.9917 | Train acc: 50.46% | Val loss: 0.9564 | Val acc: 54.07% | LR: 0.001316
Epoch: 060 | Train loss: 0.9897 | Train acc: 50.55% | Val loss: 0.9642 | Val acc: 54.42% | LR: 0.001295
Epoch: 061 | Train loss: 0.9929 | Train acc: 50.53% | Val loss: 0.9565 | Val acc: 54.52% | LR: 0.001275
Epoch: 062 | Train loss: 0.9901 | Train acc: 50.72% | Val loss: 0.9551 | Val acc: 54.16% | LR: 0.001255
Epoch: 063 | Train loss: 0.9857 | Train acc: 51.18% | Val loss: 0.9548 | Val acc: 54.07% | LR: 0.001235
Epoch: 064 | Train loss: 0.9887 | Train acc: 50.90% | Val loss: 0.9510 | Val acc: 54.14% | LR: 0.001214
Epoch: 065 | Train loss: 0.9882 | Train acc: 50.91% | Val loss: 0.9496 | Val acc: 53.68% | LR: 0.001193
Epoch: 066 | Train loss: 0.9934 | Train acc: 50.57% | Val loss: 0.9602 | Val acc: 52.21% | LR: 0.001173
Epoch: 067 | Train loss: 0.9960 | Train acc: 50.29% | Val loss: 0.9722 | Val acc: 51.39% | LR: 0.001152
Epoch: 068 | Train loss: 0.9908 | Train acc: 50.80% | Val loss: 0.9774 | Val acc: 51.20% | LR: 0.001131
Epoch: 069 | Train loss: 0.9917 | Train acc: 50.65% | Val loss: 0.9776 | Val acc: 51.20% | LR: 0.001110
Epoch: 070 | Train loss: 0.9848 | Train acc: 50.82% | Val loss: 0.9881 | Val acc: 50.56% | LR: 0.001089
Epoch: 071 | Train loss: 1.0109 | Train acc: 51.24% | Val loss: 0.9993 | Val acc: 49.84% | LR: 0.001068
Epoch: 072 | Train loss: 0.9870 | Train acc: 50.78% | Val loss: 0.9946 | Val acc: 50.08% | LR: 0.001047
Epoch: 073 | Train loss: 0.9857 | Train acc: 51.16% | Val loss: 0.9961 | Val acc: 50.57% | LR: 0.001026
Epoch: 074 | Train loss: 0.9850 | Train acc: 50.90% | Val loss: 0.9928 | Val acc: 50.30% | LR: 0.001005
Epoch: 075 | Train loss: 0.9816 | Train acc: 51.24% | Val loss: 0.9909 | Val acc: 50.45% | LR: 0.000984
Epoch: 076 | Train loss: 0.9815 | Train acc: 51.21% | Val loss: 0.9832 | Val acc: 50.80% | LR: 0.000963
Epoch: 077 | Train loss: 0.9806 | Train acc: 51.37% | Val loss: 0.9716 | Val acc: 51.99% | LR: 0.000942
Epoch: 078 | Train loss: 0.9769 | Train acc: 51.36% | Val loss: 0.9762 | Val acc: 51.58% | LR: 0.000921
Epoch: 079 | Train loss: 0.9804 | Train acc: 51.21% | Val loss: 0.9645 | Val acc: 52.03% | LR: 0.000900
Epoch: 080 | Train loss: 0.9840 | Train acc: 51.05% | Val loss: 0.9648 | Val acc: 52.03% | LR: 0.000879
Epoch: 081 | Train loss: 0.9858 | Train acc: 50.82% | Val loss: 0.9804 | Val acc: 51.30% | LR: 0.000859
Epoch: 082 | Train loss: 0.9764 | Train acc: 51.58% | Val loss: 0.9764 | Val acc: 51.39% | LR: 0.000838
Epoch: 083 | Train loss: 0.9816 | Train acc: 51.12% | Val loss: 0.9739 | Val acc: 51.69% | LR: 0.000817
Epoch: 084 | Train loss: 0.9769 | Train acc: 51.50% | Val loss: 0.9710 | Val acc: 51.81% | LR: 0.000796
Epoch: 085 | Train loss: 0.9775 | Train acc: 51.31% | Val loss: 0.9743 | Val acc: 51.63% | LR: 0.000776
Epoch: 086 | Train loss: 0.9851 | Train acc: 50.88% | Val loss: 0.9742 | Val acc: 51.53% | LR: 0.000755
Epoch: 087 | Train loss: 0.9814 | Train acc: 51.27% | Val loss: 0.9730 | Val acc: 51.90% | LR: 0.000735
Epoch: 088 | Train loss: 0.9841 | Train acc: 50.98% | Val loss: 0.9770 | Val acc: 51.40% | LR: 0.000715
Epoch: 089 | Train loss: 0.9842 | Train acc: 50.98% | Val loss: 0.9738 | Val acc: 51.81% | LR: 0.000695
Epoch: 090 | Train loss: 0.9874 | Train acc: 50.69% | Val loss: 0.9743 | Val acc: 51.51% | LR: 0.000675
Epoch: 091 | Train loss: 0.9844 | Train acc: 50.97% | Val loss: 0.9809 | Val acc: 51.28% | LR: 0.000655
Epoch: 092 | Train loss: 0.9785 | Train acc: 51.17% | Val loss: 0.9671 | Val acc: 51.93% | LR: 0.000636
Epoch: 093 | Train loss: 0.9868 | Train acc: 50.70% | Val loss: 0.9666 | Val acc: 52.09% | LR: 0.000616
Epoch: 094 | Train loss: 0.9814 | Train acc: 50.99% | Val loss: 0.9702 | Val acc: 51.75% | LR: 0.000597
Epoch: 095 | Train loss: 0.9840 | Train acc: 50.86% | Val loss: 0.9724 | Val acc: 51.70% | LR: 0.000578
Epoch: 096 | Train loss: 0.9863 | Train acc: 50.96% | Val loss: 0.9749 | Val acc: 51.57% | LR: 0.000559
Epoch: 097 | Train loss: 0.9787 | Train acc: 51.32% | Val loss: 0.9703 | Val acc: 51.85% | LR: 0.000540
Epoch: 098 | Train loss: 0.9808 | Train acc: 51.05% | Val loss: 0.9771 | Val acc: 51.67% | LR: 0.000521
Epoch: 099 | Train loss: 0.9876 | Train acc: 50.71% | Val loss: 0.9809 | Val acc: 51.15% | LR: 0.000503
Epoch: 100 | Train loss: 0.9813 | Train acc: 51.15% | Val loss: 0.9799 | Val acc: 51.42% | LR: 0.000485
Epoch: 101 | Train loss: 0.9853 | Train acc: 50.90% | Val loss: 0.9715 | Val acc: 51.67% | LR: 0.000467
Epoch: 102 | Train loss: 0.9818 | Train acc: 51.07% | Val loss: 0.9996 | Val acc: 50.11% | LR: 0.000449
Epoch: 103 | Train loss: 0.9844 | Train acc: 50.96% | Val loss: 1.0059 | Val acc: 49.72% | LR: 0.000432
Epoch: 104 | Train loss: 0.9796 | Train acc: 51.27% | Val loss: 1.0009 | Val acc: 49.95% | LR: 0.000415
Epoch: 105 | Train loss: 0.9828 | Train acc: 51.01% | Val loss: 1.0008 | Val acc: 50.07% | LR: 0.000398
Epoch: 106 | Train loss: 0.9773 | Train acc: 51.37% | Val loss: 1.0009 | Val acc: 50.07% | LR: 0.000381
Epoch: 107 | Train loss: 0.9849 | Train acc: 50.87% | Val loss: 1.0139 | Val acc: 49.26% | LR: 0.000365
Epoch: 108 | Train loss: 0.9962 | Train acc: 50.18% | Val loss: 1.0134 | Val acc: 49.46% | LR: 0.000349
Epoch: 109 | Train loss: 0.9900 | Train acc: 50.43% | Val loss: 0.9950 | Val acc: 50.26% | LR: 0.000333
Epoch: 110 | Train loss: 0.9821 | Train acc: 51.06% | Val loss: 0.9913 | Val acc: 50.54% | LR: 0.000318
Epoch: 111 | Train loss: 0.9850 | Train acc: 50.84% | Val loss: 0.9863 | Val acc: 50.83% | LR: 0.000303
Epoch: 112 | Train loss: 0.9784 | Train acc: 51.23% | Val loss: 0.9888 | Val acc: 50.62% | LR: 0.000288
Epoch: 113 | Train loss: 0.9728 | Train acc: 51.61% | Val loss: 0.9896 | Val acc: 50.66% | LR: 0.000273
Epoch: 114 | Train loss: 0.9801 | Train acc: 51.19% | Val loss: 0.9934 | Val acc: 50.36% | LR: 0.000259
Epoch: 115 | Train loss: 0.9801 | Train acc: 51.17% | Val loss: 0.9913 | Val acc: 50.48% | LR: 0.000245
Epoch: 116 | Train loss: 0.9804 | Train acc: 51.19% | Val loss: 0.9908 | Val acc: 50.48% | LR: 0.000231
Epoch: 117 | Train loss: 0.9817 | Train acc: 51.11% | Val loss: 0.9909 | Val acc: 50.56% | LR: 0.000218
Epoch: 118 | Train loss: 0.9762 | Train acc: 51.46% | Val loss: 0.9912 | Val acc: 50.44% | LR: 0.000205
Epoch: 119 | Train loss: 0.9847 | Train acc: 50.84% | Val loss: 0.9930 | Val acc: 50.44% | LR: 0.000193
Epoch: 120 | Train loss: 0.9783 | Train acc: 51.17% | Val loss: 0.9914 | Val acc: 50.50% | LR: 0.000181
Epoch: 121 | Train loss: 0.9797 | Train acc: 51.19% | Val loss: 0.9922 | Val acc: 50.46% | LR: 0.000169
Epoch: 122 | Train loss: 0.9736 | Train acc: 51.55% | Val loss: 0.9935 | Val acc: 50.44% | LR: 0.000157
Epoch: 123 | Train loss: 0.9793 | Train acc: 51.19% | Val loss: 0.9918 | Val acc: 50.34% | LR: 0.000146
Epoch: 124 | Train loss: 0.9762 | Train acc: 51.37% | Val loss: 0.9909 | Val acc: 50.48% | LR: 0.000136
Epoch: 125 | Train loss: 0.9739 | Train acc: 51.64% | Val loss: 0.9922 | Val acc: 50.38% | LR: 0.000125
Epoch: 126 | Train loss: 0.9873 | Train acc: 50.75% | Val loss: 0.9915 | Val acc: 50.46% | LR: 0.000115
Epoch: 127 | Train loss: 0.9774 | Train acc: 51.37% | Val loss: 0.9914 | Val acc: 50.42% | LR: 0.000106
Epoch: 128 | Train loss: 0.9782 | Train acc: 51.37% | Val loss: 0.9914 | Val acc: 50.50% | LR: 0.000097
Epoch: 129 | Train loss: 0.9736 | Train acc: 51.55% | Val loss: 0.9915 | Val acc: 50.44% | LR: 0.000088
Epoch: 130 | Train loss: 0.9776 | Train acc: 51.29% | Val loss: 0.9921 | Val acc: 50.40% | LR: 0.000079
Epoch: 131 | Train loss: 0.9676 | Train acc: 51.91% | Val loss: 0.9916 | Val acc: 50.44% | LR: 0.000072
Epoch: 132 | Train loss: 0.9832 | Train acc: 51.02% | Val loss: 0.9918 | Val acc: 50.44% | LR: 0.000064
Epoch: 133 | Train loss: 0.9805 | Train acc: 51.11% | Val loss: 0.9917 | Val acc: 50.44% | LR: 0.000057
Epoch: 134 | Train loss: 0.9823 | Train acc: 50.93% | Val loss: 0.9918 | Val acc: 50.44% | LR: 0.000050
Epoch: 135 | Train loss: 0.9726 | Train acc: 51.63% | Val loss: 0.9924 | Val acc: 50.48% | LR: 0.000044
Epoch: 136 | Train loss: 0.9836 | Train acc: 50.93% | Val loss: 0.9915 | Val acc: 50.44% | LR: 0.000038
Epoch: 137 | Train loss: 0.9797 | Train acc: 51.20% | Val loss: 0.9919 | Val acc: 50.44% | LR: 0.000033
Epoch: 138 | Train loss: 0.9677 | Train acc: 51.91% | Val loss: 0.9919 | Val acc: 50.44% | LR: 0.000028
Epoch: 139 | Train loss: 0.9759 | Train acc: 51.37% | Val loss: 0.9917 | Val acc: 50.46% | LR: 0.000023
Epoch: 140 | Train loss: 0.9777 | Train acc: 51.29% | Val loss: 0.9921 | Val acc: 50.42% | LR: 0.000019
Epoch: 141 | Train loss: 0.9866 | Train acc: 50.76% | Val loss: 0.9923 | Val acc: 50.46% | LR: 0.000015
Epoch: 142 | Train loss: 0.9807 | Train acc: 51.21% | Val loss: 0.9923 | Val acc: 50.46% | LR: 0.000012
Epoch: 143 | Train loss: 0.9862 | Train acc: 50.67% | Val loss: 0.9921 | Val acc: 50.46% | LR: 0.000009
Epoch: 144 | Train loss: 0.9745 | Train acc: 51.47% | Val loss: 0.9921 | Val acc: 50.46% | LR: 0.000007
Epoch: 145 | Train loss: 0.9750 | Train acc: 51.48% | Val loss: 0.9922 | Val acc: 50.46% | LR: 0.000005
Epoch: 146 | Train loss: 0.9827 | Train acc: 50.94% | Val loss: 0.9922 | Val acc: 50.46% | LR: 0.000003
Epoch: 147 | Train loss: 0.9758 | Train acc: 51.48% | Val loss: 0.9922 | Val acc: 50.46% | LR: 0.000002
Epoch: 148 | Train loss: 0.9768 | Train acc: 51.29% | Val loss: 0.9922 | Val acc: 50.46% | LR: 0.000001
Epoch: 149 | Train loss: 0.9883 | Train acc: 50.68% | Val loss: 0.9922 | Val acc: 50.46% | LR: 0.000001

[I 2025-09-23 03:07:10,724] Trial 35 finished with value: 0.5452080368995667 and parameters: {'lr': 0.002009459331189142, 'hidden_size': 103, 'dropout': 0.49758433257342705, 'weight_decay': 0.35208455567328023}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.0315 | Train acc: 49.05% | Val loss: 1.0227 | Val acc: 45.85% | LR: 0.008512
Epoch: 001 | Train loss: 1.0116 | Train acc: 50.28% | Val loss: 1.0009 | Val acc: 48.66% | LR: 0.008510
Epoch: 002 | Train loss: 1.0004 | Train acc: 50.48% | Val loss: 1.1573 | Val acc: 48.22% | LR: 0.008505
Epoch: 003 | Train loss: 2.2318 | Train acc: 50.73% | Val loss: 1.0490 | Val acc: 45.95% | LR: 0.008498
Epoch: 004 | Train loss: 1.0128 | Train acc: 49.74% | Val loss: 0.9309 | Val acc: 54.05% | LR: 0.008490
Epoch: 005 | Train loss: 1.0049 | Train acc: 50.00% | Val loss: 1.0147 | Val acc: 46.59% | LR: 0.008480
Epoch: 006 | Train loss: 1.0039 | Train acc: 50.47% | Val loss: 1.0024 | Val acc: 48.91% | LR: 0.008468
Epoch: 007 | Train loss: 0.9976 | Train acc: 50.45% | Val loss: 1.0167 | Val acc: 48.09% | LR: 0.008454
Epoch: 008 | Train loss: 1.0080 | Train acc: 49.88% | Val loss: 1.0068 | Val acc: 50.18% | LR: 0.008438
Epoch: 009 | Train loss: 1.0076 | Train acc: 50.08% | Val loss: 0.9691 | Val acc: 53.02% | LR: 0.008420
Epoch: 010 | Train loss: 0.9948 | Train acc: 51.07% | Val loss: 0.9742 | Val acc: 52.28% | LR: 0.008401
Epoch: 011 | Train loss: 0.9982 | Train acc: 51.15% | Val loss: 0.9867 | Val acc: 51.60% | LR: 0.008380
Epoch: 012 | Train loss: 0.9961 | Train acc: 51.42% | Val loss: 0.9942 | Val acc: 52.13% | LR: 0.008357
Epoch: 013 | Train loss: 1.0684 | Train acc: 50.20% | Val loss: 0.9603 | Val acc: 54.14% | LR: 0.008332
Epoch: 014 | Train loss: 1.0118 | Train acc: 50.69% | Val loss: 0.9951 | Val acc: 50.98% | LR: 0.008305
Epoch: 015 | Train loss: 1.0277 | Train acc: 50.63% | Val loss: 1.0330 | Val acc: 45.93% | LR: 0.008277
Epoch: 016 | Train loss: 1.0058 | Train acc: 50.72% | Val loss: 0.9760 | Val acc: 50.35% | LR: 0.008246
Epoch: 017 | Train loss: 1.0381 | Train acc: 50.55% | Val loss: 0.9762 | Val acc: 50.34% | LR: 0.008214
Epoch: 018 | Train loss: 1.0028 | Train acc: 50.91% | Val loss: 0.9917 | Val acc: 49.53% | LR: 0.008181
Epoch: 019 | Train loss: 1.0087 | Train acc: 50.11% | Val loss: 0.9630 | Val acc: 53.87% | LR: 0.008145
Epoch: 020 | Train loss: 1.0087 | Train acc: 49.90% | Val loss: 1.0032 | Val acc: 50.07% | LR: 0.008108
Epoch: 021 | Train loss: 1.0074 | Train acc: 50.46% | Val loss: 0.9573 | Val acc: 53.48% | LR: 0.008069
Epoch: 022 | Train loss: 0.9985 | Train acc: 50.57% | Val loss: 0.9714 | Val acc: 52.66% | LR: 0.008029
Epoch: 023 | Train loss: 1.0107 | Train acc: 49.90% | Val loss: 0.9807 | Val acc: 53.09% | LR: 0.007987
Epoch: 024 | Train loss: 0.9948 | Train acc: 50.93% | Val loss: 0.9660 | Val acc: 52.91% | LR: 0.007943
Epoch: 025 | Train loss: 1.0031 | Train acc: 50.43% | Val loss: 0.9822 | Val acc: 52.93% | LR: 0.007898
Epoch: 026 | Train loss: 1.0088 | Train acc: 50.01% | Val loss: 0.9994 | Val acc: 49.86% | LR: 0.007851
Epoch: 027 | Train loss: 1.0044 | Train acc: 50.82% | Val loss: 1.0231 | Val acc: 45.95% | LR: 0.007802
Epoch: 028 | Train loss: 0.9968 | Train acc: 50.52% | Val loss: 0.9790 | Val acc: 51.35% | LR: 0.007752
Epoch: 029 | Train loss: 0.9999 | Train acc: 50.70% | Val loss: 0.9754 | Val acc: 53.49% | LR: 0.007701
Epoch: 030 | Train loss: 1.0047 | Train acc: 50.39% | Val loss: 0.9974 | Val acc: 50.22% | LR: 0.007647
Epoch: 031 | Train loss: 0.9977 | Train acc: 50.84% | Val loss: 1.0013 | Val acc: 49.64% | LR: 0.007593
Epoch: 032 | Train loss: 1.0016 | Train acc: 51.08% | Val loss: 0.9951 | Val acc: 50.71% | LR: 0.007537
Epoch: 033 | Train loss: 0.9922 | Train acc: 50.85% | Val loss: 1.0323 | Val acc: 45.95% | LR: 0.007479
Epoch: 034 | Train loss: 1.0048 | Train acc: 51.22% | Val loss: 1.0017 | Val acc: 49.85% | LR: 0.007420
Epoch: 035 | Train loss: 1.0019 | Train acc: 50.27% | Val loss: 1.0233 | Val acc: 49.45% | LR: 0.007360
Epoch: 036 | Train loss: 0.9990 | Train acc: 50.62% | Val loss: 1.0116 | Val acc: 49.06% | LR: 0.007298
Epoch: 037 | Train loss: 1.0008 | Train acc: 50.86% | Val loss: 0.9717 | Val acc: 51.15% | LR: 0.007235
Epoch: 038 | Train loss: 0.9998 | Train acc: 50.67% | Val loss: 0.9877 | Val acc: 51.64% | LR: 0.007171
Epoch: 039 | Train loss: 1.0101 | Train acc: 49.82% | Val loss: 1.0449 | Val acc: 46.14% | LR: 0.007105
Epoch: 040 | Train loss: 1.0129 | Train acc: 49.79% | Val loss: 1.0323 | Val acc: 46.03% | LR: 0.007038
Epoch: 041 | Train loss: 1.0090 | Train acc: 49.77% | Val loss: 1.0060 | Val acc: 46.43% | LR: 0.006970
Epoch: 042 | Train loss: 1.0048 | Train acc: 50.11% | Val loss: 1.0098 | Val acc: 47.87% | LR: 0.006901
Epoch: 043 | Train loss: 0.9993 | Train acc: 50.99% | Val loss: 0.9926 | Val acc: 50.99% | LR: 0.006830
Epoch: 044 | Train loss: 1.0028 | Train acc: 50.32% | Val loss: 1.0004 | Val acc: 49.46% | LR: 0.006759
Epoch: 045 | Train loss: 1.0054 | Train acc: 50.49% | Val loss: 0.9939 | Val acc: 50.37% | LR: 0.006686
Epoch: 046 | Train loss: 0.9948 | Train acc: 50.92% | Val loss: 0.9932 | Val acc: 51.38% | LR: 0.006613
Epoch: 047 | Train loss: 1.0144 | Train acc: 51.24% | Val loss: 1.0022 | Val acc: 48.96% | LR: 0.006538
Epoch: 048 | Train loss: 0.9950 | Train acc: 50.89% | Val loss: 0.9661 | Val acc: 54.49% | LR: 0.006462
Epoch: 049 | Train loss: 1.0037 | Train acc: 50.79% | Val loss: 0.9866 | Val acc: 50.85% | LR: 0.006385
Epoch: 050 | Train loss: 1.0003 | Train acc: 50.73% | Val loss: 1.0127 | Val acc: 47.93% | LR: 0.006308
Epoch: 051 | Train loss: 0.9992 | Train acc: 50.46% | Val loss: 0.9996 | Val acc: 48.96% | LR: 0.006229
Epoch: 052 | Train loss: 1.0119 | Train acc: 50.38% | Val loss: 1.0266 | Val acc: 46.97% | LR: 0.006150
Epoch: 053 | Train loss: 1.0026 | Train acc: 49.94% | Val loss: 0.9977 | Val acc: 48.92% | LR: 0.006069
Epoch: 054 | Train loss: 0.9942 | Train acc: 50.82% | Val loss: 0.9728 | Val acc: 51.01% | LR: 0.005988
Epoch: 055 | Train loss: 0.9955 | Train acc: 50.60% | Val loss: 0.9907 | Val acc: 50.25% | LR: 0.005907
Epoch: 056 | Train loss: 0.9994 | Train acc: 50.20% | Val loss: 1.0139 | Val acc: 49.05% | LR: 0.005824
Epoch: 057 | Train loss: 0.9981 | Train acc: 50.31% | Val loss: 1.0042 | Val acc: 49.31% | LR: 0.005741
Epoch: 058 | Train loss: 0.9984 | Train acc: 50.59% | Val loss: 0.9958 | Val acc: 49.86% | LR: 0.005657
Epoch: 059 | Train loss: 0.9882 | Train acc: 51.56% | Val loss: 1.0124 | Val acc: 48.78% | LR: 0.005572
Epoch: 060 | Train loss: 1.0006 | Train acc: 50.25% | Val loss: 0.9930 | Val acc: 50.86% | LR: 0.005487
Epoch: 061 | Train loss: 1.0052 | Train acc: 50.21% | Val loss: 0.9833 | Val acc: 50.49% | LR: 0.005402
Epoch: 062 | Train loss: 0.9963 | Train acc: 50.35% | Val loss: 1.0383 | Val acc: 45.58% | LR: 0.005316
Epoch: 063 | Train loss: 1.0008 | Train acc: 50.32% | Val loss: 1.0213 | Val acc: 48.37% | LR: 0.005229
Epoch: 064 | Train loss: 1.0096 | Train acc: 50.06% | Val loss: 0.9970 | Val acc: 49.25% | LR: 0.005142
Epoch: 065 | Train loss: 0.9964 | Train acc: 50.73% | Val loss: 0.9748 | Val acc: 51.32% | LR: 0.005055
Epoch: 066 | Train loss: 0.9957 | Train acc: 50.28% | Val loss: 0.9824 | Val acc: 51.29% | LR: 0.004967
Epoch: 067 | Train loss: 0.9901 | Train acc: 51.04% | Val loss: 1.0171 | Val acc: 49.24% | LR: 0.004879
Epoch: 068 | Train loss: 1.0007 | Train acc: 50.53% | Val loss: 0.9796 | Val acc: 51.26% | LR: 0.004791
Epoch: 069 | Train loss: 0.9895 | Train acc: 51.15% | Val loss: 1.0069 | Val acc: 49.80% | LR: 0.004702
Epoch: 070 | Train loss: 0.9968 | Train acc: 50.33% | Val loss: 0.9633 | Val acc: 53.09% | LR: 0.004613
Epoch: 071 | Train loss: 0.9980 | Train acc: 50.42% | Val loss: 0.9739 | Val acc: 52.21% | LR: 0.004524
Epoch: 072 | Train loss: 0.9909 | Train acc: 51.19% | Val loss: 1.0138 | Val acc: 49.86% | LR: 0.004435
Epoch: 073 | Train loss: 0.9988 | Train acc: 51.03% | Val loss: 0.9594 | Val acc: 53.93% | LR: 0.004346
Epoch: 074 | Train loss: 0.9939 | Train acc: 50.76% | Val loss: 0.9905 | Val acc: 50.90% | LR: 0.004257
Epoch: 075 | Train loss: 0.9856 | Train acc: 51.07% | Val loss: 0.9993 | Val acc: 50.22% | LR: 0.004168
Epoch: 076 | Train loss: 0.9908 | Train acc: 50.97% | Val loss: 1.0086 | Val acc: 49.56% | LR: 0.004079
Epoch: 077 | Train loss: 0.9934 | Train acc: 50.94% | Val loss: 0.9998 | Val acc: 49.87% | LR: 0.003990
Epoch: 078 | Train loss: 0.9926 | Train acc: 50.88% | Val loss: 0.9937 | Val acc: 50.39% | LR: 0.003901
Epoch: 079 | Train loss: 0.9934 | Train acc: 50.61% | Val loss: 0.9995 | Val acc: 50.63% | LR: 0.003812
Epoch: 080 | Train loss: 0.9920 | Train acc: 50.86% | Val loss: 0.9904 | Val acc: 50.79% | LR: 0.003724
Epoch: 081 | Train loss: 0.9919 | Train acc: 50.71% | Val loss: 0.9723 | Val acc: 52.46% | LR: 0.003635
Epoch: 082 | Train loss: 0.9889 | Train acc: 50.88% | Val loss: 0.9700 | Val acc: 52.42% | LR: 0.003547
Epoch: 083 | Train loss: 0.9910 | Train acc: 50.86% | Val loss: 1.0072 | Val acc: 49.77% | LR: 0.003460
Epoch: 084 | Train loss: 0.9931 | Train acc: 51.11% | Val loss: 1.0151 | Val acc: 49.13% | LR: 0.003372
Epoch: 085 | Train loss: 1.0122 | Train acc: 51.30% | Val loss: 1.0118 | Val acc: 45.99% | LR: 0.003285
Epoch: 086 | Train loss: 1.0075 | Train acc: 50.19% | Val loss: 0.9689 | Val acc: 54.61% | LR: 0.003199
Epoch: 087 | Train loss: 1.0029 | Train acc: 49.72% | Val loss: 1.0110 | Val acc: 47.09% | LR: 0.003113
Epoch: 088 | Train loss: 0.9958 | Train acc: 50.62% | Val loss: 0.9945 | Val acc: 50.64% | LR: 0.003027
Epoch: 089 | Train loss: 0.9977 | Train acc: 50.17% | Val loss: 0.9986 | Val acc: 50.90% | LR: 0.002942
Epoch: 090 | Train loss: 1.0012 | Train acc: 50.07% | Val loss: 0.9517 | Val acc: 54.52% | LR: 0.002857
Epoch: 091 | Train loss: 0.9943 | Train acc: 50.89% | Val loss: 0.9841 | Val acc: 52.05% | LR: 0.002774
Epoch: 092 | Train loss: 0.9880 | Train acc: 51.32% | Val loss: 0.9752 | Val acc: 53.23% | LR: 0.002690
Epoch: 093 | Train loss: 0.9877 | Train acc: 51.42% | Val loss: 0.9571 | Val acc: 53.10% | LR: 0.002608
Epoch: 094 | Train loss: 0.9877 | Train acc: 51.56% | Val loss: 1.0106 | Val acc: 48.18% | LR: 0.002526
Epoch: 095 | Train loss: 0.9942 | Train acc: 50.83% | Val loss: 0.9882 | Val acc: 51.37% | LR: 0.002445
Epoch: 096 | Train loss: 0.9921 | Train acc: 50.65% | Val loss: 0.9586 | Val acc: 53.82% | LR: 0.002365
Epoch: 097 | Train loss: 0.9939 | Train acc: 50.90% | Val loss: 0.9819 | Val acc: 51.26% | LR: 0.002285
Epoch: 098 | Train loss: 0.9937 | Train acc: 50.87% | Val loss: 0.9816 | Val acc: 51.23% | LR: 0.002207
Epoch: 099 | Train loss: 0.9858 | Train acc: 51.31% | Val loss: 0.9843 | Val acc: 52.15% | LR: 0.002129
Epoch: 100 | Train loss: 0.9907 | Train acc: 50.74% | Val loss: 0.9677 | Val acc: 52.04% | LR: 0.002052
Epoch: 101 | Train loss: 0.9908 | Train acc: 50.83% | Val loss: 0.9911 | Val acc: 50.45% | LR: 0.001977
Epoch: 102 | Train loss: 0.9870 | Train acc: 51.48% | Val loss: 1.0139 | Val acc: 49.25% | LR: 0.001902
Epoch: 103 | Train loss: 0.9969 | Train acc: 50.22% | Val loss: 0.9978 | Val acc: 50.55% | LR: 0.001828
Epoch: 104 | Train loss: 0.9883 | Train acc: 50.86% | Val loss: 1.0145 | Val acc: 48.97% | LR: 0.001755
Epoch: 105 | Train loss: 0.9897 | Train acc: 50.66% | Val loss: 0.9941 | Val acc: 50.12% | LR: 0.001684
Epoch: 106 | Train loss: 0.9923 | Train acc: 50.87% | Val loss: 0.9931 | Val acc: 50.65% | LR: 0.001613
Epoch: 107 | Train loss: 0.9891 | Train acc: 50.53% | Val loss: 1.0091 | Val acc: 50.06% | LR: 0.001544
Epoch: 108 | Train loss: 1.1911 | Train acc: 50.78% | Val loss: 0.9938 | Val acc: 50.55% | LR: 0.001476
Epoch: 109 | Train loss: 1.0038 | Train acc: 50.62% | Val loss: 0.9933 | Val acc: 50.50% | LR: 0.001409
Epoch: 110 | Train loss: 0.9871 | Train acc: 50.79% | Val loss: 0.9895 | Val acc: 50.65% | LR: 0.001344
Epoch: 111 | Train loss: 0.9842 | Train acc: 51.07% | Val loss: 0.9903 | Val acc: 50.52% | LR: 0.001279
Epoch: 112 | Train loss: 0.9860 | Train acc: 51.13% | Val loss: 0.9955 | Val acc: 50.90% | LR: 0.001216
Epoch: 113 | Train loss: 0.9902 | Train acc: 50.68% | Val loss: 0.9753 | Val acc: 51.36% | LR: 0.001155
Epoch: 114 | Train loss: 0.9850 | Train acc: 51.78% | Val loss: 0.9662 | Val acc: 52.33% | LR: 0.001094
Epoch: 115 | Train loss: 0.9798 | Train acc: 51.86% | Val loss: 0.9871 | Val acc: 50.88% | LR: 0.001035
Epoch: 116 | Train loss: 0.9836 | Train acc: 51.15% | Val loss: 0.9937 | Val acc: 50.34% | LR: 0.000978
Epoch: 117 | Train loss: 0.9933 | Train acc: 50.45% | Val loss: 0.9923 | Val acc: 50.83% | LR: 0.000922
Epoch: 118 | Train loss: 0.9836 | Train acc: 51.23% | Val loss: 0.9858 | Val acc: 50.85% | LR: 0.000867
Epoch: 119 | Train loss: 0.9831 | Train acc: 51.58% | Val loss: 0.9882 | Val acc: 50.49% | LR: 0.000814
Epoch: 120 | Train loss: 0.9796 | Train acc: 51.77% | Val loss: 0.9890 | Val acc: 50.73% | LR: 0.000762
Epoch: 121 | Train loss: 0.9827 | Train acc: 51.39% | Val loss: 0.9873 | Val acc: 50.70% | LR: 0.000712
Epoch: 122 | Train loss: 0.9809 | Train acc: 51.50% | Val loss: 0.9921 | Val acc: 50.65% | LR: 0.000664
Epoch: 123 | Train loss: 0.9782 | Train acc: 51.64% | Val loss: 0.9896 | Val acc: 50.79% | LR: 0.000617
Epoch: 124 | Train loss: 0.9899 | Train acc: 50.71% | Val loss: 0.9848 | Val acc: 50.67% | LR: 0.000571
Epoch: 125 | Train loss: 0.9836 | Train acc: 50.98% | Val loss: 0.9941 | Val acc: 50.37% | LR: 0.000527
Epoch: 126 | Train loss: 0.9786 | Train acc: 51.52% | Val loss: 0.9920 | Val acc: 50.63% | LR: 0.000485
Epoch: 127 | Train loss: 0.9894 | Train acc: 50.43% | Val loss: 0.9856 | Val acc: 51.04% | LR: 0.000445
Epoch: 128 | Train loss: 0.9843 | Train acc: 51.19% | Val loss: 0.9907 | Val acc: 50.66% | LR: 0.000406
Epoch: 129 | Train loss: 0.9847 | Train acc: 51.18% | Val loss: 0.9795 | Val acc: 51.30% | LR: 0.000369
Epoch: 130 | Train loss: 0.9831 | Train acc: 51.28% | Val loss: 0.9954 | Val acc: 50.46% | LR: 0.000334
Epoch: 131 | Train loss: 0.9864 | Train acc: 50.92% | Val loss: 0.9826 | Val acc: 51.12% | LR: 0.000300
Epoch: 132 | Train loss: 0.9853 | Train acc: 50.49% | Val loss: 0.9894 | Val acc: 50.76% | LR: 0.000268
Epoch: 133 | Train loss: 0.9790 | Train acc: 51.48% | Val loss: 0.9877 | Val acc: 50.80% | LR: 0.000238
Epoch: 134 | Train loss: 0.9817 | Train acc: 51.34% | Val loss: 0.9894 | Val acc: 50.74% | LR: 0.000209
Epoch: 135 | Train loss: 0.9827 | Train acc: 51.13% | Val loss: 0.9876 | Val acc: 50.82% | LR: 0.000183
Epoch: 136 | Train loss: 0.9827 | Train acc: 51.29% | Val loss: 0.9880 | Val acc: 50.72% | LR: 0.000158
Epoch: 137 | Train loss: 0.9805 | Train acc: 51.35% | Val loss: 0.9861 | Val acc: 50.84% | LR: 0.000135
Epoch: 138 | Train loss: 0.9761 | Train acc: 51.67% | Val loss: 0.9853 | Val acc: 51.00% | LR: 0.000113
Epoch: 139 | Train loss: 0.9843 | Train acc: 51.09% | Val loss: 0.9894 | Val acc: 50.68% | LR: 0.000094
Epoch: 140 | Train loss: 0.9746 | Train acc: 52.09% | Val loss: 0.9888 | Val acc: 50.72% | LR: 0.000076
Epoch: 141 | Train loss: 0.9762 | Train acc: 51.93% | Val loss: 0.9865 | Val acc: 50.88% | LR: 0.000061
Epoch: 142 | Train loss: 0.9774 | Train acc: 51.63% | Val loss: 0.9882 | Val acc: 50.76% | LR: 0.000047
Epoch: 143 | Train loss: 0.9754 | Train acc: 52.06% | Val loss: 0.9873 | Val acc: 50.74% | LR: 0.000035
Epoch: 144 | Train loss: 0.9755 | Train acc: 51.85% | Val loss: 0.9887 | Val acc: 50.80% | LR: 0.000024
Epoch: 145 | Train loss: 0.9754 | Train acc: 51.92% | Val loss: 0.9887 | Val acc: 50.80% | LR: 0.000016
Epoch: 146 | Train loss: 0.9730 | Train acc: 51.69% | Val loss: 0.9887 | Val acc: 50.80% | LR: 0.000009
Epoch: 147 | Train loss: 0.9737 | Train acc: 51.66% | Val loss: 0.9887 | Val acc: 50.80% | LR: 0.000005
Epoch: 148 | Train loss: 0.9778 | Train acc: 51.50% | Val loss: 0.9887 | Val acc: 50.80% | LR: 0.000002
Epoch: 149 | Train loss: 0.9789 | Train acc: 51.43% | Val loss: 0.9888 | Val acc: 50.80% | LR: 0.000001

[I 2025-09-23 03:11:00,649] Trial 36 finished with value: 0.5460917234420777 and parameters: {'lr': 0.008513365572619147, 'hidden_size': 161, 'dropout': 0.2637289077910383, 'weight_decay': 0.6983879389219411}. Best is trial 5 with value: 0.5506223201751709.

Epoch: 000 | Train loss: 1.0065 | Train acc: 50.21% | Val loss: 1.0082 | Val acc: 49.72% | LR: 0.005534
Epoch: 001 | Train loss: 1.1098 | Train acc: 50.24% | Val loss: 1.2715 | Val acc: 52.58% | LR: 0.005532
Epoch: 002 | Train loss: 1.1238 | Train acc: 49.78% | Val loss: 0.9988 | Val acc: 51.44% | LR: 0.005529
Epoch: 003 | Train loss: 1.0146 | Train acc: 50.32% | Val loss: 1.1165 | Val acc: 47.07% | LR: 0.005525
Epoch: 004 | Train loss: 1.0094 | Train acc: 50.17% | Val loss: 0.9842 | Val acc: 53.98% | LR: 0.005519
Epoch: 005 | Train loss: 0.9905 | Train acc: 51.31% | Val loss: 0.9335 | Val acc: 54.95% | LR: 0.005513
Epoch: 006 | Train loss: 0.9965 | Train acc: 50.73% | Val loss: 1.0179 | Val acc: 45.95% | LR: 0.005505
Epoch: 007 | Train loss: 0.9911 | Train acc: 51.02% | Val loss: 1.0092 | Val acc: 49.05% | LR: 0.005496
Epoch: 008 | Train loss: 0.9951 | Train acc: 50.91% | Val loss: 0.9980 | Val acc: 49.26% | LR: 0.005486
Epoch: 009 | Train loss: 1.0007 | Train acc: 50.21% | Val loss: 0.9811 | Val acc: 52.19% | LR: 0.005474
Epoch: 010 | Train loss: 0.9933 | Train acc: 50.62% | Val loss: 0.9776 | Val acc: 51.55% | LR: 0.005462
Epoch: 011 | Train loss: 0.9958 | Train acc: 50.76% | Val loss: 0.9914 | Val acc: 50.51% | LR: 0.005448
Epoch: 012 | Train loss: 0.9911 | Train acc: 50.74% | Val loss: 0.9833 | Val acc: 50.04% | LR: 0.005433
Epoch: 013 | Train loss: 0.9960 | Train acc: 50.17% | Val loss: 1.0057 | Val acc: 48.95% | LR: 0.005417
Epoch: 014 | Train loss: 0.9895 | Train acc: 51.24% | Val loss: 0.9726 | Val acc: 52.41% | LR: 0.005399
Epoch: 015 | Train loss: 0.9985 | Train acc: 50.47% | Val loss: 0.9826 | Val acc: 51.17% | LR: 0.005381
Epoch: 016 | Train loss: 0.9905 | Train acc: 50.87% | Val loss: 0.9661 | Val acc: 52.38% | LR: 0.005361
Epoch: 017 | Train loss: 0.9943 | Train acc: 50.72% | Val loss: 0.9611 | Val acc: 52.66% | LR: 0.005340
Epoch: 018 | Train loss: 0.9896 | Train acc: 51.54% | Val loss: 0.9827 | Val acc: 51.06% | LR: 0.005318
Epoch: 019 | Train loss: 0.9913 | Train acc: 50.90% | Val loss: 0.9849 | Val acc: 50.76% | LR: 0.005295
Epoch: 020 | Train loss: 0.9933 | Train acc: 50.26% | Val loss: 1.0093 | Val acc: 49.39% | LR: 0.005271
Epoch: 021 | Train loss: 0.9963 | Train acc: 50.83% | Val loss: 1.0221 | Val acc: 47.21% | LR: 0.005246
Epoch: 022 | Train loss: 0.9943 | Train acc: 50.64% | Val loss: 0.9983 | Val acc: 50.50% | LR: 0.005220
Epoch: 023 | Train loss: 0.9922 | Train acc: 50.58% | Val loss: 0.9730 | Val acc: 51.46% | LR: 0.005192
Epoch: 024 | Train loss: 0.9925 | Train acc: 50.29% | Val loss: 0.9585 | Val acc: 52.87% | LR: 0.005164
Epoch: 025 | Train loss: 0.9882 | Train acc: 50.74% | Val loss: 0.9566 | Val acc: 52.53% | LR: 0.005134
Epoch: 026 | Train loss: 0.9969 | Train acc: 50.90% | Val loss: 1.1286 | Val acc: 47.01% | LR: 0.005104
Epoch: 027 | Train loss: 1.0173 | Train acc: 50.68% | Val loss: 1.0512 | Val acc: 46.06% | LR: 0.005072
Epoch: 028 | Train loss: 1.0815 | Train acc: 50.14% | Val loss: 1.0061 | Val acc: 49.62% | LR: 0.005040
Epoch: 029 | Train loss: 1.0007 | Train acc: 50.27% | Val loss: 0.9640 | Val acc: 54.18% | LR: 0.005006
Epoch: 030 | Train loss: 0.9982 | Train acc: 50.61% | Val loss: 1.1178 | Val acc: 47.10% | LR: 0.004972
Epoch: 031 | Train loss: 1.0043 | Train acc: 50.25% | Val loss: 0.9732 | Val acc: 53.67% | LR: 0.004936
Epoch: 032 | Train loss: 1.0234 | Train acc: 50.21% | Val loss: 0.9976 | Val acc: 51.18% | LR: 0.004900
Epoch: 033 | Train loss: 0.9939 | Train acc: 50.71% | Val loss: 0.9733 | Val acc: 53.95% | LR: 0.004862
Epoch: 034 | Train loss: 1.0070 | Train acc: 50.59% | Val loss: 1.0790 | Val acc: 45.85% | LR: 0.004824
Epoch: 035 | Train loss: 1.0119 | Train acc: 49.66% | Val loss: 1.1207 | Val acc: 49.33% | LR: 0.004785
Epoch: 036 | Train loss: 1.0005 | Train acc: 50.99% | Val loss: 1.0489 | Val acc: 46.19% | LR: 0.004745
Epoch: 037 | Train loss: 0.9976 | Train acc: 50.40% | Val loss: 0.9668 | Val acc: 52.93% | LR: 0.004704
Epoch: 038 | Train loss: 0.9978 | Train acc: 50.43% | Val loss: 0.9848 | Val acc: 52.23% | LR: 0.004662
Epoch: 039 | Train loss: 0.9999 | Train acc: 50.06% | Val loss: 1.0359 | Val acc: 45.81% | LR: 0.004619
Epoch: 040 | Train loss: 1.0029 | Train acc: 50.70% | Val loss: 1.0241 | Val acc: 47.66% | LR: 0.004576
Epoch: 041 | Train loss: 0.9990 | Train acc: 50.77% | Val loss: 0.9824 | Val acc: 51.95% | LR: 0.004531
Epoch: 042 | Train loss: 0.9952 | Train acc: 50.67% | Val loss: 1.0024 | Val acc: 48.90% | LR: 0.004486
Epoch: 043 | Train loss: 0.9990 | Train acc: 50.39% | Val loss: 1.0231 | Val acc: 46.34% | LR: 0.004441
Epoch: 044 | Train loss: 1.0017 | Train acc: 50.10% | Val loss: 0.9942 | Val acc: 51.21% | LR: 0.004394
Epoch: 045 | Train loss: 1.0006 | Train acc: 49.99% | Val loss: 1.0160 | Val acc: 46.66% | LR: 0.004347
Epoch: 046 | Train loss: 0.9993 | Train acc: 49.91% | Val loss: 1.0006 | Val acc: 48.97% | LR: 0.004299
Epoch: 047 | Train loss: 1.0013 | Train acc: 49.57% | Val loss: 1.0156 | Val acc: 47.95% | LR: 0.004250
Epoch: 048 | Train loss: 0.9900 | Train acc: 51.18% | Val loss: 0.9869 | Val acc: 51.65% | LR: 0.004201
Epoch: 049 | Train loss: 0.9913 | Train acc: 50.43% | Val loss: 0.9908 | Val acc: 51.58% | LR: 0.004151
Epoch: 050 | Train loss: 0.9946 | Train acc: 50.29% | Val loss: 0.9869 | Val acc: 51.45% | LR: 0.004101
Epoch: 051 | Train loss: 0.9882 | Train acc: 50.98% | Val loss: 0.9915 | Val acc: 51.48% | LR: 0.004050
Epoch: 052 | Train loss: 1.0031 | Train acc: 49.44% | Val loss: 1.0053 | Val acc: 48.34% | LR: 0.003998
Epoch: 053 | Train loss: 0.9935 | Train acc: 50.57% | Val loss: 1.0092 | Val acc: 49.06% | LR: 0.003946
Epoch: 054 | Train loss: 0.9861 | Train acc: 51.45% | Val loss: 0.9863 | Val acc: 51.56% | LR: 0.003893
Epoch: 055 | Train loss: 0.9908 | Train acc: 50.96% | Val loss: 1.0124 | Val acc: 48.84% | LR: 0.003840
Epoch: 056 | Train loss: 0.9898 | Train acc: 51.00% | Val loss: 0.9981 | Val acc: 49.91% | LR: 0.003786
Epoch: 057 | Train loss: 0.9990 | Train acc: 49.90% | Val loss: 0.9951 | Val acc: 49.92% | LR: 0.003732
Epoch: 058 | Train loss: 0.9882 | Train acc: 51.26% | Val loss: 1.0128 | Val acc: 48.70% | LR: 0.003678
Epoch: 059 | Train loss: 0.9952 | Train acc: 50.64% | Val loss: 1.0133 | Val acc: 48.68% | LR: 0.003623
Epoch: 060 | Train loss: 0.9957 | Train acc: 50.49% | Val loss: 0.9903 | Val acc: 53.35% | LR: 0.003568
Epoch: 061 | Train loss: 1.0421 | Train acc: 49.87% | Val loss: 0.9976 | Val acc: 48.72% | LR: 0.003512
Epoch: 062 | Train loss: 0.9934 | Train acc: 50.85% | Val loss: 1.0172 | Val acc: 47.60% | LR: 0.003456
Epoch: 063 | Train loss: 1.0018 | Train acc: 50.52% | Val loss: 1.0066 | Val acc: 48.82% | LR: 0.003400
Epoch: 064 | Train loss: 1.0000 | Train acc: 50.01% | Val loss: 1.0189 | Val acc: 48.31% | LR: 0.003343
Epoch: 065 | Train loss: 0.9956 | Train acc: 50.38% | Val loss: 0.9789 | Val acc: 50.74% | LR: 0.003286
Epoch: 066 | Train loss: 0.9853 | Train acc: 51.24% | Val loss: 1.0268 | Val acc: 48.37% | LR: 0.003229
Epoch: 067 | Train loss: 0.9918 | Train acc: 51.22% | Val loss: 1.0404 | Val acc: 48.27% | LR: 0.003172
Epoch: 068 | Train loss: 0.9942 | Train acc: 51.40% | Val loss: 1.0034 | Val acc: 50.67% | LR: 0.003115
Epoch: 069 | Train loss: 0.9924 | Train acc: 51.11% | Val loss: 0.9753 | Val acc: 52.18% | LR: 0.003057
Epoch: 070 | Train loss: 0.9878 | Train acc: 50.35% | Val loss: 0.9882 | Val acc: 51.39% | LR: 0.002999
Epoch: 071 | Train loss: 0.9928 | Train acc: 50.46% | Val loss: 0.9935 | Val acc: 50.71% | LR: 0.002942
Epoch: 072 | Train loss: 0.9951 | Train acc: 50.84% | Val loss: 0.9948 | Val acc: 50.56% | LR: 0.002884
Epoch: 073 | Train loss: 0.9951 | Train acc: 50.87% | Val loss: 1.0109 | Val acc: 49.19% | LR: 0.002826
Epoch: 074 | Train loss: 0.9851 | Train acc: 51.22% | Val loss: 1.0068 | Val acc: 49.89% | LR: 0.002768
Epoch: 075 | Train loss: 0.9887 | Train acc: 51.09% | Val loss: 0.9969 | Val acc: 50.06% | LR: 0.002710
Epoch: 076 | Train loss: 0.9920 | Train acc: 51.34% | Val loss: 0.9885 | Val acc: 49.83% | LR: 0.002652
Epoch: 077 | Train loss: 0.9866 | Train acc: 50.82% | Val loss: 1.0103 | Val acc: 48.74% | LR: 0.002594
Epoch: 078 | Train loss: 0.9936 | Train acc: 51.11% | Val loss: 1.0050 | Val acc: 48.78% | LR: 0.002536
Epoch: 079 | Train loss: 0.9926 | Train acc: 50.74% | Val loss: 1.0029 | Val acc: 49.38% | LR: 0.002479
Epoch: 080 | Train loss: 0.9930 | Train acc: 50.60% | Val loss: 1.0050 | Val acc: 49.18% | LR: 0.002421
Epoch: 081 | Train loss: 0.9854 | Train acc: 51.38% | Val loss: 1.0110 | Val acc: 48.82% | LR: 0.002364
Epoch: 082 | Train loss: 0.9919 | Train acc: 50.58% | Val loss: 1.0018 | Val acc: 49.66% | LR: 0.002306
Epoch: 083 | Train loss: 0.9986 | Train acc: 50.06% | Val loss: 1.0345 | Val acc: 48.78% | LR: 0.002249
Epoch: 084 | Train loss: 0.9848 | Train acc: 51.21% | Val loss: 1.0109 | Val acc: 49.16% | LR: 0.002193
Epoch: 085 | Train loss: 0.9871 | Train acc: 51.08% | Val loss: 1.0094 | Val acc: 49.10% | LR: 0.002136
Epoch: 086 | Train loss: 0.9923 | Train acc: 50.58% | Val loss: 1.0249 | Val acc: 48.63% | LR: 0.002080
Epoch: 087 | Train loss: 0.9819 | Train acc: 51.43% | Val loss: 1.0100 | Val acc: 49.33% | LR: 0.002024
Epoch: 088 | Train loss: 0.9880 | Train acc: 50.80% | Val loss: 0.9931 | Val acc: 51.23% | LR: 0.001968
Epoch: 089 | Train loss: 0.9896 | Train acc: 50.80% | Val loss: 0.9885 | Val acc: 51.11% | LR: 0.001913
Epoch: 090 | Train loss: 0.9917 | Train acc: 50.64% | Val loss: 1.0001 | Val acc: 51.05% | LR: 0.001858
Epoch: 091 | Train loss: 0.9868 | Train acc: 50.99% | Val loss: 0.9883 | Val acc: 51.03% | LR: 0.001803
Epoch: 092 | Train loss: 0.9892 | Train acc: 50.79% | Val loss: 0.9944 | Val acc: 50.61% | LR: 0.001749
Epoch: 093 | Train loss: 0.9846 | Train acc: 50.97% | Val loss: 0.9974 | Val acc: 50.33% | LR: 0.001696
Epoch: 094 | Train loss: 0.9970 | Train acc: 50.34% | Val loss: 1.0032 | Val acc: 50.37% | LR: 0.001642
Epoch: 095 | Train loss: 0.9873 | Train acc: 50.59% | Val loss: 0.9874 | Val acc: 51.00% | LR: 0.001590
Epoch: 096 | Train loss: 0.9823 | Train acc: 51.16% | Val loss: 0.9946 | Val acc: 50.74% | LR: 0.001538
Epoch: 097 | Train loss: 0.9877 | Train acc: 51.04% | Val loss: 0.9902 | Val acc: 50.79% | LR: 0.001486
Epoch: 098 | Train loss: 0.9820 | Train acc: 51.19% | Val loss: 0.9940 | Val acc: 50.92% | LR: 0.001435
Epoch: 099 | Train loss: 0.9916 | Train acc: 50.58% | Val loss: 0.9950 | Val acc: 50.78% | LR: 0.001384
Epoch: 100 | Train loss: 0.9874 | Train acc: 50.64% | Val loss: 0.9929 | Val acc: 50.59% | LR: 0.001335
Epoch: 101 | Train loss: 0.9808 | Train acc: 51.32% | Val loss: 0.9872 | Val acc: 51.05% | LR: 0.001285
Epoch: 102 | Train loss: 0.9854 | Train acc: 51.08% | Val loss: 1.0055 | Val acc: 50.47% | LR: 0.001237
Epoch: 103 | Train loss: 0.9849 | Train acc: 51.31% | Val loss: 0.9914 | Val acc: 51.25% | LR: 0.001189
Epoch: 104 | Train loss: 0.9827 | Train acc: 51.04% | Val loss: 1.0129 | Val acc: 50.00% | LR: 0.001142
Epoch: 105 | Train loss: 0.9864 | Train acc: 50.75% | Val loss: 1.0102 | Val acc: 49.92% | LR: 0.001095
Epoch: 106 | Train loss: 0.9847 | Train acc: 51.08% | Val loss: 1.0131 | Val acc: 49.45% | LR: 0.001049
Epoch: 107 | Train loss: 0.9837 | Train acc: 51.18% | Val loss: 1.0112 | Val acc: 49.51% | LR: 0.001004
Epoch: 108 | Train loss: 0.9805 | Train acc: 51.35% | Val loss: 1.0026 | Val acc: 50.12% | LR: 0.000960
Epoch: 109 | Train loss: 0.9806 | Train acc: 51.28% | Val loss: 1.0048 | Val acc: 49.89% | LR: 0.000916
Epoch: 110 | Train loss: 0.9862 | Train acc: 50.74% | Val loss: 1.0037 | Val acc: 50.23% | LR: 0.000874
Epoch: 111 | Train loss: 0.9846 | Train acc: 51.13% | Val loss: 1.0059 | Val acc: 50.20% | LR: 0.000832
Epoch: 112 | Train loss: 0.9866 | Train acc: 50.94% | Val loss: 0.9933 | Val acc: 50.36% | LR: 0.000791
Epoch: 113 | Train loss: 0.9894 | Train acc: 50.68% | Val loss: 1.0027 | Val acc: 50.23% | LR: 0.000751
Epoch: 114 | Train loss: 0.9873 | Train acc: 50.75% | Val loss: 0.9920 | Val acc: 50.35% | LR: 0.000712
Epoch: 115 | Train loss: 0.9873 | Train acc: 50.98% | Val loss: 0.9806 | Val acc: 51.62% | LR: 0.000673
Epoch: 116 | Train loss: 0.9843 | Train acc: 51.04% | Val loss: 0.9932 | Val acc: 50.50% | LR: 0.000636
Epoch: 117 | Train loss: 0.9823 | Train acc: 51.29% | Val loss: 0.9886 | Val acc: 50.58% | LR: 0.000599
Epoch: 118 | Train loss: 0.9788 | Train acc: 51.45% | Val loss: 0.9860 | Val acc: 50.84% | LR: 0.000564
Epoch: 119 | Train loss: 0.9777 | Train acc: 51.50% | Val loss: 0.9909 | Val acc: 50.74% | LR: 0.000529
Epoch: 120 | Train loss: 0.9828 | Train acc: 51.02% | Val loss: 0.9878 | Val acc: 50.62% | LR: 0.000496
Epoch: 121 | Train loss: 0.9794 | Train acc: 51.29% | Val loss: 0.9872 | Val acc: 50.79% | LR: 0.000463
Epoch: 122 | Train loss: 0.9809 | Train acc: 51.32% | Val loss: 0.9944 | Val acc: 50.67% | LR: 0.000432
Epoch: 123 | Train loss: 0.9877 | Train acc: 50.94% | Val loss: 0.9859 | Val acc: 50.70% | LR: 0.000401
Epoch: 124 | Train loss: 0.9847 | Train acc: 50.92% | Val loss: 0.9917 | Val acc: 50.85% | LR: 0.000372
Epoch: 125 | Train loss: 0.9868 | Train acc: 50.95% | Val loss: 0.9862 | Val acc: 50.73% | LR: 0.000343
Epoch: 126 | Train loss: 0.9807 | Train acc: 51.29% | Val loss: 0.9845 | Val acc: 51.06% | LR: 0.000316
Epoch: 127 | Train loss: 0.9816 | Train acc: 51.22% | Val loss: 0.9899 | Val acc: 50.76% | LR: 0.000290
Epoch: 128 | Train loss: 0.9784 | Train acc: 51.42% | Val loss: 0.9875 | Val acc: 50.90% | LR: 0.000264

[W 2025-09-23 03:13:38,105] Trial 37 failed with parameters: {'lr': 0.00553461991605263, 'hidden_size': 136, 'dropout': 0.21939454858664129, 'weight_decay': 0.5185598923151987} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipython-input-2249639888.py", line 19, in objective
    return training_loop(trial, lr, hidden_size, dropout, weight_decay)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipython-input-3088323191.py", line 33, in training_loop
    logits = model(X, o, c) # (batch, output_size)
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipython-input-966400356.py", line 16, in forward
    h_out = self.alstm(final_input) # (batch, 2*hidden_size)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipython-input-3515388034.py", line 20, in forward
    output, (h_n, c_n) = self.lstm(x)
                         ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/rnn.py", line 1124, in forward
    result = _VF.lstm(
             ^^^^^^^^^
KeyboardInterrupt
[W 2025-09-23 03:13:38,107] Trial 37 failed with value None.

Epoch: 129 | Train loss: 0.9789 | Train acc: 51.36% | Val loss: 0.9890 | Val acc: 50.86% | LR: 0.000240

KeyboardInterrupt:

In [ ]:
torch.manual_seed(42)
torch.cuda.manual_seed(42)

model = SLOT(
      input_size=len(price_features),
      hidden_size=hidden_size,
).to(device)

model.load_state_dict(torch.load(dataset_dir / "best_SLOT_model.pth", map_location=device))

test_loss = 0.0
test_acc = 0.0

model.eval()

with torch.inference_mode():
    for X_test, o_test, c_test, y_test in test_dataloader:

        X_test, o_test, c_test, y_test = X_test.to(device), o_test.to(device), c_test.to(device), y_test.to(device)

        logits = model(X_test, o_test, c_test)
        loss, acc = evaluate(logits, y_test)

        test_loss += loss.item()
        test_acc += acc


    test_loss /= len(test_dataloader)
    test_acc /= len(test_dataloader)

print(f"Test loss: {test_loss:.4f} | Test acc: {100*test_acc:.2f}%")

NameError: name 'torch' is not defined