<a href="https://colab.research.google.com/github/brien60/Stock-LSTM/blob/SLOT/SLOT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Setup

### Imports

In [1]:
import torch
from torch import nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, random_split
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence

from pathlib import Path
import json
import re

import sentencepiece as sp
from collections import Counter

import pandas as pd

from tqdm import tqdm

import os

import wandb

try:
  import optuna
  from optuna.integration.wandb import WeightsAndBiasesCallback

except:
  !pip install -q optuna
  !pip install -q optuna-integration[wandb]
  import optuna
  from optuna.integration.wandb import WeightsAndBiasesCallback


import time

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.9/400.9 kB 28.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 8.4 MB/s eta 0:00:00

### Colab Setup Code

In [2]:
!git clone -q --branch SLOT https://github.com/brien60/Stock-LSTM.git
%cd Stock-LSTM/
!unzip -q data.zip -d /content/Stock-LSTM/data

/content/Stock-LSTM

### Constants

In [3]:
torch.manual_seed(42)
torch.cuda.manual_seed(42)
device = "cuda" if torch.cuda.is_available() else "cpu"

if device == "cuda":
    os.environ["CUDA_LAUNCH_BLOCKING"] = "1"


dataset = "acl18"
dataset_dir = Path(dataset.upper())

data_dir = Path(f"data/{dataset}")

tweet_dir = data_dir / "tweet"
price_dir = data_dir / "price"

tweet_files_list = list(tweet_dir.rglob("*/*"))
list.sort(tweet_files_list)

stock_names = [stock.name for stock in list(tweet_dir.rglob("*")) if stock.is_dir()]
list.sort(stock_names)

num_stocks = len(stock_names)

json_file = dataset_dir / "all_tweets.jsonl"
spm_file = dataset_dir / "spm/slot_tweet_spm.model"
tokens_file = dataset_dir / "all_tweets_tokenized.jsonl"


vocab_size = 10_000

window_size = 15

num_epochs = 150
batch_size = 1024

## SLOT Overview

SLOT (Self-supervised Learning of Tweets for Capturing Multi-level Price Trends) aims to address
1. the sparsity of tweets, with the number of tweets being heavily biased towards the most popular stocks.
2. the fact that tweets have noisy information that are often irrelevant to the actual stock movement.

The first problem was addressed by having SLOT learn the stock and tweet embeddings in the same vector space through self-supervised learning. This allows the use of any tweet for even unpopular stocks.

To tackle the second problem, SLOT uses tweets to learn multi-level relationships between stocks, rather than using them as direct evidence for stock prediction (e.g. positive sentiment = up).

## Attention LSTM

In [4]:

class ALSTM(nn.Module):
    def __init__(self, input_size, hidden_size, dropout):
        super().__init__()
        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            batch_first=True,
        )
        self.dropout = nn.Dropout(dropout)
        self.ln = nn.Linear(hidden_size, hidden_size)
        self.tanh = nn.Tanh()
        self.u = nn.Parameter(data=torch.randn(hidden_size))


    def forward(self, x):
        # x: (batch, seq_len, input_size)

        # output: (batch, seq_len, hidden_size)
        # h_n, c_n : (num_layers, batch, hidden_size)
        output, (h_n, c_n) = self.lstm(x)
        output = self.dropout(output)
        output = self.tanh(self.ln(output))

        # query: u, key: output, values: output
        attn_scores = torch.matmul(output, self.u) # (batch, seq_len, hidden_size) @ (hidden_size) -> (batch, seq_len)
        weights = attn_scores / attn_scores.sum(dim=1, keepdim=True)
        weights = weights.unsqueeze(dim=-1) # (batch, seq_len, 1)

        # (batch, seq_len, 1) * (batch, seq_len, hidden_size) -> (batch, seq_len, hidden_size)
        # (batch, seq_len, hidden_size) -> (batch, hidden_size)
        h_attn = (weights * output).sum(dim=1)

        # (batch, hidden_size) || (batch, hidden_size) -> (batch, 2*hidden_size)
        h_out = torch.cat((h_n[0], h_attn), dim=1) # both the general summary and the attention

        return h_out

## Price Features

The price features that compose a feature vector $x_{st}$ are
- Price movements in a day: *c_open, c_high, c_low*
- Price movements between days: *n_close, n_adj_close*
- Long-term movements: *5_day, 10_day, ... , 30_day*

So the daily prices of days $t-29$ to $t$ are used to generate each $x_{st}$

These features have already been calculated and normalized in the csv files.

### Extracting features data

In [24]:
data_files_list = list(price_dir.rglob("*.csv"))

data_list = []

price_features = []
labels = []

for i, stock_file in enumerate(data_files_list):
    stock = stock_file.stem
    df = pd.read_csv(stock_file)
    # columns = [
    #     f'{stock}_c_open', f'{stock}_c_high', f'{stock}_c_low',
    #     f'{stock}_n_close', f'{stock}_n_adj_close',
    #     f'{stock}_adj_sum_5', f'{stock}_adj_sum_10', f'{stock}_adj_sum_15',
    #     f'{stock}_adj_sum_20', f'{stock}_adj_sum_25', f'{stock}_adj_sum_30',
    #     f'{stock}_label', f'{stock}_closing_price_for_label'
    # ]

    # price_features.extend(columns[:-2])
    # labels.append(columns[-2])

    # if i != 0:
    # df.drop(columns=['date'], inplace=True)
    # else:
        # columns = ['date'] + columns

    # df.columns = columns

    df['label'] = df['label'].shift(-1)
    df = df.dropna()

    data_list.append(df)

# combined_df = pd.concat(data_list, axis=1)
# combined_df = combined_df.dropna()

# combined_df
data_list[0]

,date,c_open,c_high,c_low,n_close,n_adj_close,adj_sum_5,adj_sum_10,adj_sum_15,adj_sum_20,adj_sum_25,adj_sum_30,label,closing_price_for_label
0,2013-06-03,-1.214238,0.266138,-1.746504,0.940224,0.940235,0.705257,2.985694,4.059658,4.426977,4.753823,4.341868,0.0,52.789917
1,2013-06-04,-0.364961,0.481082,-0.431322,0.266138,0.266140,-0.378239,2.058720,3.405215,3.863629,4.272719,4.057722,-1.0,52.930412
2,2013-06-05,1.264045,1.264045,-0.210675,-5.507631,-2.249839,1.420411,3.612428,5.159974,5.862468,6.343023,6.305304,1.0,51.739563
3,2013-06-06,-1.399203,0.069100,-1.623768,1.632722,1.632725,-0.220305,1.444585,2.984755,3.850856,4.354486,4.506555,1.0,52.584328
4,2013-06-07,-0.532373,0.051517,-0.824317,0.587324,0.587319,-0.577936,0.466718,2.000242,2.996097,3.518573,3.820407,-1.0,52.893166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,2015-12-23,-0.915336,0.171624,-0.915336,2.132634,2.132654,-1.507447,-1.610425,-1.708631,-1.345122,-0.980543,-1.164651,0.0,71.066559
647,2015-12-24,-0.427660,0.242341,-0.427660,0.328946,0.328937,-1.550962,-1.736281,-1.852223,-1.694942,-1.272907,-1.393520,0.0,71.300323
648,2015-12-28,-0.442790,0.114266,-0.542781,-0.199574,-0.199571,-0.848450,-1.339811,-1.517880,-1.507645,-1.105674,-1.121229,1.0,71.158028
649,2015-12-29,-0.536043,0.141062,-0.578364,1.256966,1.256954,-1.416272,-2.199176,-2.527854,-2.628715,-2.342892,-2.205345,0.0,72.052452
650,2015-12-30,0.396100,0.509276,-0.056578,-0.282134,-0.282125,-0.506431,-1.584379,-2.055922,-2.283913,-2.024612,-1.846342,-1.0,71.849174

### Remove Dates

In [25]:
for df in data_list:
    df.drop(columns=['date'], inplace=True)

data_list[0]

,c_open,c_high,c_low,n_close,n_adj_close,adj_sum_5,adj_sum_10,adj_sum_15,adj_sum_20,adj_sum_25,adj_sum_30,label,closing_price_for_label
0,-1.214238,0.266138,-1.746504,0.940224,0.940235,0.705257,2.985694,4.059658,4.426977,4.753823,4.341868,0.0,52.789917
1,-0.364961,0.481082,-0.431322,0.266138,0.266140,-0.378239,2.058720,3.405215,3.863629,4.272719,4.057722,-1.0,52.930412
2,1.264045,1.264045,-0.210675,-5.507631,-2.249839,1.420411,3.612428,5.159974,5.862468,6.343023,6.305304,1.0,51.739563
3,-1.399203,0.069100,-1.623768,1.632722,1.632725,-0.220305,1.444585,2.984755,3.850856,4.354486,4.506555,1.0,52.584328
4,-0.532373,0.051517,-0.824317,0.587324,0.587319,-0.577936,0.466718,2.000242,2.996097,3.518573,3.820407,-1.0,52.893166
...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,-0.915336,0.171624,-0.915336,2.132634,2.132654,-1.507447,-1.610425,-1.708631,-1.345122,-0.980543,-1.164651,0.0,71.066559
647,-0.427660,0.242341,-0.427660,0.328946,0.328937,-1.550962,-1.736281,-1.852223,-1.694942,-1.272907,-1.393520,0.0,71.300323
648,-0.442790,0.114266,-0.542781,-0.199574,-0.199571,-0.848450,-1.339811,-1.517880,-1.507645,-1.105674,-1.121229,1.0,71.158028
649,-0.536043,0.141062,-0.578364,1.256966,1.256954,-1.416272,-2.199176,-2.527854,-2.628715,-2.342892,-2.205345,0.0,72.052452
650,0.396100,0.509276,-0.056578,-0.282134,-0.282125,-0.506431,-1.584379,-2.055922,-2.283913,-2.024612,-1.846342,-1.0,71.849174

### Make X and y tensors

In [26]:
columns = data_list[0].columns.to_list()
price_features = columns[: -2]
labels = columns[-2]

In [27]:
X_st = [
    torch.tensor(df[price_features].to_numpy(), dtype=torch.float)
    for df in data_list
]
y = [
    torch.tensor(df[labels].to_numpy(), dtype=torch.float)
    for df in data_list
]

X_st = torch.stack(X_st).transpose(0, 1).to(device)
y = torch.stack(y).transpose(0, 1).to(device)

y = torch.sign(y)

X_st[0, :5], X_st.shape, y, y.shape

(tensor([[-1.2142,  0.2661, -1.7465,  0.9402,  0.9402,  0.7053,  2.9857,  4.0597,
           4.4270,  4.7538,  4.3419],
         [ 1.0034,  1.0034, -1.7828, -0.3393, -0.3393,  0.7310,  0.9604,  1.0948,
           0.2320, -1.4926, -2.5590],
         [-0.6284,  0.0898, -1.1131,  1.5312,  1.5312, -0.2118,  0.9975,  1.2685,
           1.1894,  0.5511, -0.4571],
         [-1.3699,  0.1588, -1.4294,  1.7370,  1.7370, -0.8338, -1.2656, -2.1878,
          -3.2687, -4.4262, -5.5260],
         [ 2.8821,  3.4217, -1.1023, -2.1461, -2.1461,  1.2148,  1.6910,  2.3330,
           3.2499,  3.5939,  3.6049]], device='cuda:0'),
 torch.Size([651, 87, 11]),
 tensor([[ 0.,  1.,  0.,  ..., -1.,  0.,  1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [ 1., -1.,  0.,  ...,  1.,  1.,  1.],
         ...,
         [ 1.,  1.,  1.,  ...,  1.,  1.,  0.],
         [ 0., -1., -1.,  ..., -1.,  0., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.]], device='cuda:0'),
 torch.Size([651, 87]))

## Self-supervised Learning of Embeddings

The goal is to learn tweet (h_e) and stock (h_s) embeddings in the same semantic space, that is, learning the embeddings together such that one embedding can be used to query for the other.
- a stock embedding and the embedding of tweet relevant to it are close together (higher dot product)
- stocks that are frequently co-mentioned will have similar embeddings; this naturally groups together stocks in the same industry/sector.
- solves problem of tweet sparsity; the model can associate stocks with tweets that don't directly mention it as long as they are close in vector space.

This was done by training for stock identification: predict the mentioned stock in a tweet when the stock symbol is masked.

Every tweet is tokenized with Sentence Piece and then the tokens that correspond to the stock the tweet mentions are masked with the special token MASK.
- "Thank you Apple for the new iPhone." -> "Thank you [MASK] for the new iPhone."

### Stock Identification Model

Use a BiLSTM (need to understand the context on both sides of the mask token).
- Using a transformer risks overfitting.

The stock embedding is a learnable parameter.

The hidden state vector generated at the masked token is used as the tweet embedding because it
- captures the immediate left (via the forward LSTM) and right context (via the backward LSTM) of the tweet, making it exactly what we need for stock identification,
- and it is the part of the tweet that most connects to mentioned stock.

### Write raw data to json

In [ ]:

buffer = []
buffer_size = 100_000
lines = 0

with open(json_file, "w", encoding="utf-8") as out:
    for tweet_file in tweet_files_list:

        with open(tweet_file, "r", encoding="utf-8") as f:


            for line in f:
                tweet = json.loads(line)

                json_tweet = {
                    "date": tweet_file.stem,
                    "stock": tweet_file.parent.name,
                    "tweet": tweet["text"].replace("\n", " ")
                }

                buffer.append(json.dumps(json_tweet))

                if len(buffer) >= buffer_size:
                    out.write("\n".join(buffer) + "\n")
                    lines += len(buffer)

                    buffer.clear()

                    print(f"{lines} lines written")

    if buffer:
        lines += len(buffer)
        out.write("\n".join(buffer) + "\n")
        print(f"{lines} lines written")

print("All tweets written")

100000 lines written
119844 lines written
All tweets written

### Txt file for sp training

In [ ]:
input_file = json_file
output_file = dataset_dir / "tweets_for_sp.txt"

with open(input_file, "r", encoding="utf-8") as f, open(output_file, "w", encoding="utf-8") as out:
    for line in f:
        tweet = json.loads(line)
        out.write(tweet["tweet"] + "\n")

### SPM Training

In [ ]:
spm_file = dataset_dir / "spm/slot_tweet_spm"
vocab_size = 10_000

sp.SentencePieceTrainer.train(
    input=output_file,
    model_prefix=spm_file,
    vocab_size=vocab_size,
    model_type="unigram",
    character_coverage=1.0,
    input_sentence_size=lines,
    shuffle_input_sentence=True,
    user_defined_symbols=["<MASK>", "<PAD>", "<UNK>"]
)

spm_file = str(spm_file.with_suffix(".model"))

In [5]:
slot_spm = sp.SentencePieceProcessor()
slot_spm.load(str(spm_file))

mask_id = slot_spm.piece_to_id("<MASK>")
pad_id = slot_spm.piece_to_id("<PAD>")
unk_id = slot_spm.piece_to_id("<UNK>")

mask_id, pad_id, unk_id

(3, 4, 5)

### Create tokenized jsonl

In [6]:
all_dates = []

for tweet_file in tweet_files_list:
        date = tweet_file.stem
        all_dates.append(date)


all_dates = sorted(dict.fromkeys(all_dates))

start_date, end_date = "2014-02-19", "2015-12-31"
start_date_idx, end_date_idx = all_dates.index(start_date), all_dates.index(end_date)

all_dates = all_dates[start_date_idx : end_date_idx + 1]

num_dates = len(all_dates)
num_dates, all_dates

(651,
 ['2014-02-19',
  '2014-02-20',
  '2014-02-21',
  '2014-02-22',
  '2014-02-23',
  '2014-02-24',
  '2014-02-25',
  '2014-02-26',
  '2014-02-27',
  '2014-02-28',
  '2014-03-01',
  '2014-03-02',
  '2014-03-03',
  '2014-03-04',
  '2014-03-05',
  '2014-03-06',
  '2014-03-07',
  '2014-03-08',
  '2014-03-09',
  '2014-03-10',
  '2014-03-11',
  '2014-03-12',
  '2014-03-13',
  '2014-03-14',
  '2014-03-15',
  '2014-03-16',
  '2014-03-17',
  '2014-03-18',
  '2014-03-19',
  '2014-03-20',
  '2014-03-21',
  '2014-03-22',
  '2014-03-23',
  '2014-03-24',
  '2014-03-25',
  '2014-03-26',
  '2014-03-27',
  '2014-03-28',
  '2014-03-29',
  '2014-03-30',
  '2014-03-31',
  '2014-04-01',
  '2014-04-02',
  '2014-04-03',
  '2014-04-04',
  '2014-04-05',
  '2014-04-06',
  '2014-04-07',
  '2014-04-08',
  '2014-04-09',
  '2014-04-10',
  '2014-04-11',
  '2014-04-12',
  '2014-04-13',
  '2014-04-14',
  '2014-04-15',
  '2014-04-16',
  '2014-04-17',
  '2014-04-18',
  '2014-04-19',
  '2014-04-20',
  '2014-04-21',
  '2014-04-22',
  '2014-04-23',
  '2014-04-24',
  '2014-04-25',
  '2014-04-26',
  '2014-04-27',
  '2014-04-28',
  '2014-04-29',
  '2014-04-30',
  '2014-05-01',
  '2014-05-02',
  '2014-05-03',
  '2014-05-04',
  '2014-05-05',
  '2014-05-06',
  '2014-05-07',
  '2014-05-08',
  '2014-05-09',
  '2014-05-10',
  '2014-05-11',
  '2014-05-12',
  '2014-05-13',
  '2014-05-14',
  '2014-05-15',
  '2014-05-16',
  '2014-05-17',
  '2014-05-18',
  '2014-05-19',
  '2014-05-20',
  '2014-05-21',
  '2014-05-22',
  '2014-05-23',
  '2014-05-24',
  '2014-05-25',
  '2014-05-26',
  '2014-05-27',
  '2014-05-28',
  '2014-05-29',
  '2014-05-30',
  '2014-05-31',
  '2014-06-01',
  '2014-06-02',
  '2014-06-03',
  '2014-06-04',
  '2014-06-05',
  '2014-06-06',
  '2014-06-07',
  '2014-06-08',
  '2014-06-09',
  '2014-06-10',
  '2014-06-11',
  '2014-06-12',
  '2014-06-13',
  '2014-06-14',
  '2014-06-15',
  '2014-06-16',
  '2014-06-18',
  '2014-06-19',
  '2014-06-20',
  '2014-06-21',
  '2014-06-22',
  '2014-06-23',
  '2014-06-24',
  '2014-06-25',
  '2014-06-26',
  '2014-06-27',
  '2014-06-28',
  '2014-06-29',
  '2014-06-30',
  '2014-07-01',
  '2014-07-02',
  '2014-07-03',
  '2014-07-04',
  '2014-07-05',
  '2014-07-06',
  '2014-07-07',
  '2014-07-08',
  '2014-07-09',
  '2014-07-10',
  '2014-07-11',
  '2014-07-12',
  '2014-07-13',
  '2014-07-14',
  '2014-07-15',
  '2014-07-16',
  '2014-07-17',
  '2014-07-18',
  '2014-07-19',
  '2014-07-20',
  '2014-07-21',
  '2014-07-22',
  '2014-07-23',
  '2014-07-24',
  '2014-07-25',
  '2014-07-26',
  '2014-07-27',
  '2014-07-28',
  '2014-07-29',
  '2014-07-30',
  '2014-07-31',
  '2014-08-01',
  '2014-08-02',
  '2014-08-03',
  '2014-08-04',
  '2014-08-05',
  '2014-08-07',
  '2014-08-08',
  '2014-08-09',
  '2014-08-10',
  '2014-08-11',
  '2014-08-12',
  '2014-08-13',
  '2014-08-14',
  '2014-08-15',
  '2014-08-16',
  '2014-08-17',
  '2014-08-18',
  '2014-08-19',
  '2014-08-20',
  '2014-08-21',
  '2014-08-22',
  '2014-08-23',
  '2014-08-24',
  '2014-08-25',
  '2014-08-26',
  '2014-08-27',
  '2014-08-28',
  '2014-08-29',
  '2014-08-30',
  '2014-08-31',
  '2014-09-01',
  '2014-09-02',
  '2014-09-03',
  '2014-09-04',
  '2014-09-05',
  '2014-09-06',
  '2014-09-07',
  '2014-09-08',
  '2014-09-09',
  '2014-09-10',
  '2014-09-11',
  '2014-09-12',
  '2014-09-13',
  '2014-09-14',
  '2014-09-15',
  '2014-09-16',
  '2014-09-17',
  '2014-09-18',
  '2014-09-19',
  '2014-09-20',
  '2014-09-21',
  '2014-09-22',
  '2014-09-23',
  '2014-09-29',
  '2014-09-30',
  '2014-10-01',
  '2014-10-02',
  '2014-10-03',
  '2014-10-04',
  '2014-10-05',
  '2014-10-06',
  '2014-10-07',
  '2014-10-08',
  '2014-10-09',
  '2014-10-10',
  '2014-10-11',
  '2014-10-12',
  '2014-10-13',
  '2014-10-14',
  '2014-10-15',
  '2014-10-16',
  '2014-10-17',
  '2014-10-18',
  '2014-10-19',
  '2014-10-20',
  '2014-10-21',
  '2014-10-22',
  '2014-10-23',
  '2014-10-24',
  '2014-10-25',
  '2014-10-26',
  '2014-10-27',
  '2014-10-28',
  '2014-10-29',
  '2014-10-30',
  '2014-10-31',
  '2014-11-01',
  '2014-11-02',
  '2014-11-03',
  '2014-11-04',
  '2014-11-05',
  '2014-11-06',
  '2014-11-07',
  '2014-11-08',
  '2014-11-09',
  '2014-11-14',
  '2014-11-23',
  '2014-11-24',
  '2014-11-25',
  '2014-11-26',
  '2014-11-27',
  '2014-11-28',
  '2014-11-29',
  '2014-11-30',
  '2014-12-01',
  '2014-12-02',
  '2014-12-03',
  '2014-12-04',
  '2014-12-05',
  '2014-12-06',
  '2014-12-07',
  '2014-12-08',
  '2014-12-09',
  '2014-12-10',
  '2014-12-11',
  '2014-12-12',
  '2014-12-13',
  '2014-12-14',
  '2014-12-15',
  '2014-12-16',
  '2014-12-17',
  '2014-12-18',
  '2014-12-19',
  '2014-12-21',
  '2014-12-22',
  '2014-12-23',
  '2014-12-24',
  '2014-12-25',
  '2014-12-26',
  '2014-12-27',
  '2014-12-28',
  '2014-12-29',
  '2014-12-30',
  '2014-12-31',
  '2015-01-01',
  '2015-01-02',
  '2015-01-03',
  '2015-01-04',
  '2015-01-05',
  '2015-01-06',
  '2015-01-07',
  '2015-01-08',
  '2015-01-09',
  '2015-01-10',
  '2015-01-11',
  '2015-01-12',
  '2015-01-13',
  '2015-01-14',
  '2015-01-15',
  '2015-01-16',
  '2015-01-17',
  '2015-01-18',
  '2015-01-19',
  '2015-01-20',
  '2015-01-21',
  '2015-01-22',
  '2015-01-23',
  '2015-01-24',
  '2015-01-25',
  '2015-01-26',
  '2015-01-27',
  '2015-01-28',
  '2015-01-29',
  '2015-01-30',
  '2015-01-31',
  '2015-02-01',
  '2015-02-02',
  '2015-02-03',
  '2015-02-04',
  '2015-02-05',
  '2015-02-06',
  '2015-02-07',
  '2015-02-08',
  '2015-02-09',
  '2015-02-10',
  '2015-02-11',
  '2015-02-12',
  '2015-02-13',
  '2015-02-14',
  '2015-02-15',
  '2015-02-16',
  '2015-02-17',
  '2015-02-18',
  '2015-02-19',
  '2015-02-20',
  '2015-02-21',
  '2015-02-22',
  '2015-02-23',
  '2015-02-24',
  '2015-02-25',
  '2015-02-26',
  '2015-02-27',
  '2015-02-28',
  '2015-03-01',
  '2015-03-02',
  '2015-03-03',
  '2015-03-04',
  '2015-03-05',
  '2015-03-06',
  '2015-03-07',
  '2015-03-09',
  '2015-03-10',
  '2015-03-11',
  '2015-03-12',
  '2015-03-13',
  '2015-03-14',
  '2015-03-15',
  '2015-03-16',
  '2015-03-17',
  '2015-03-18',
  '2015-03-19',
  '2015-03-20',
  '2015-03-21',
  '2015-03-22',
  '2015-03-23',
  '2015-03-24',
  '2015-03-25',
  '2015-03-26',
  '2015-03-27',
  '2015-03-28',
  '2015-03-29',
  '2015-03-30',
  '2015-03-31',
  '2015-04-01',
  '2015-04-02',
  '2015-04-03',
  '2015-04-04',
  '2015-04-05',
  '2015-04-06',
  '2015-04-07',
  '2015-04-08',
  '2015-04-09',
  '2015-04-10',
  '2015-04-11',
  '2015-04-12',
  '2015-04-13',
  '2015-04-14',
  '2015-04-15',
  '2015-04-16',
  '2015-04-17',
  '2015-04-18',
  '2015-04-19',
  '2015-04-20',
  '2015-04-21',
  '2015-04-22',
  '2015-04-23',
  '2015-04-24',
  '2015-04-25',
  '2015-04-26',
  '2015-04-27',
  '2015-04-28',
  '2015-04-29',
  '2015-04-30',
  '2015-05-01',
  '2015-05-02',
  '2015-05-03',
  '2015-05-04',
  '2015-05-05',
  '2015-05-06',
  '2015-05-07',
  '2015-05-08',
  '2015-05-09',
  '2015-05-10',
  '2015-05-11',
  '2015-05-12',
  '2015-05-13',
  '2015-05-14',
  '2015-05-15',
  '2015-05-16',
  '2015-05-17',
  '2015-05-18',
  '2015-05-19',
  '2015-05-20',
  '2015-05-21',
  '2015-05-22',
  '2015-05-23',
  '2015-05-24',
  '2015-05-25',
  '2015-05-26',
  '2015-05-27',
  '2015-05-28',
  '2015-05-29',
  '2015-05-30',
  '2015-05-31',
  '2015-06-01',
  '2015-06-02',
  '2015-06-03',
  '2015-06-04',
  '2015-06-06',
  '2015-06-07',
  '2015-06-08',
  '2015-06-09',
  '2015-06-10',
  '2015-06-11',
  '2015-06-12',
  '2015-06-13',
  '2015-06-14',
  '2015-06-15',
  '2015-06-16',
  '2015-06-17',
  '2015-06-18',
  '2015-06-19',
  '2015-06-20',
  '2015-06-21',
  '2015-06-22',
  '2015-06-24',
  '2015-06-25',
  '2015-06-26',
  '2015-06-27',
  '2015-06-28',
  '2015-06-29',
  '2015-06-30',
  '2015-07-01',
  '2015-07-02',
  '2015-07-03',
  '2015-07-04',
  '2015-07-05',
  '2015-07-06',
  '2015-07-07',
  '2015-07-09',
  '2015-07-10',
  '2015-07-11',
  '2015-07-12',
  '2015-07-13',
  '2015-07-14',
  '2015-07-15',
  '2015-07-16',
  '2015-07-17',
  '2015-07-18',
  '2015-07-19',
  '2015-07-20',
  '2015-07-21',
  '2015-07-22',
  '2015-07-23',
  '2015-07-24',
  '2015-07-25',
  '2015-07-26',
  '2015-07-27',
  '2015-07-28',
  '2015-07-29',
  '2015-07-30',
  '2015-07-31',
  '2015-08-01',
  '2015-08-02',
  '2015-08-03',
  '2015-08-04',
  '2015-08-05',
  '2015-08-06',
  '2015-08-07',
  '2015-08-08',
  '2015-08-09',
  '2015-08-10',
  '2015-08-11',
  '2015-08-12',
  '2015-08-13',
  '2015-08-14',
  '2015-08-16',
  '2015-08-17',
  '2015-08-18',
  '2015-08-19',
  '2015-08-20',
  '2015-08-21',
  '2015-08-22',
  '2015-08-23',
  '2015-08-24',
  '2015-08-25',
  '2015-08-26',
  '2015-08-27',
  '2015-08-28',
  '2015-08-29',
  '2015-08-30',
  '2015-08-31',
  '2015-09-01',
  '2015-09-02',
  '2015-09-03',
  '2015-09-04',
  '2015-09-05',
  '2015-09-06',
  '2015-09-07',
  '2015-09-08',
  '2015-09-09',
  '2015-09-10',
  '2015-09-11',
  '2015-09-12',
  '2015-09-13',
  '2015-09-14',
  '2015-09-15',
  '2015-09-16',
  '2015-09-19',
  '2015-09-20',
  '2015-09-21',
  '2015-09-22',
  '2015-09-23',
  '2015-09-24',
  '2015-09-25',
  '2015-09-26',
  '2015-09-27',
  '2015-09-28',
  '2015-09-29',
  '2015-09-30',
  '2015-10-01',
  '2015-10-02',
  '2015-10-03',
  '2015-10-04',
  '2015-10-05',
  '2015-10-06',
  '2015-10-07',
  '2015-10-08',
  '2015-10-09',
  '2015-10-10',
  '2015-10-11',
  '2015-10-12',
  '2015-10-13',
  '2015-10-14',
  '2015-10-15',
  '2015-10-16',
  '2015-10-17',
  '2015-10-18',
  '2015-10-19',
  '2015-10-20',
  '2015-10-21',
  '2015-10-22',
  '2015-10-23',
  '2015-10-24',
  '2015-10-25',
  '2015-10-26',
  '2015-10-27',
  '2015-10-28',
  '2015-10-29',
  '2015-10-30',
  '2015-10-31',
  '2015-11-01',
  '2015-11-02',
  '2015-11-03',
  '2015-11-04',
  '2015-11-05',
  '2015-11-06',
  '2015-11-07',
  '2015-11-08',
  '2015-11-09',
  '2015-11-10',
  '2015-11-11',
  '2015-11-12',
  '2015-11-13',
  '2015-11-14',
  '2015-11-15',
  '2015-11-16',
  '2015-11-17',
  '2015-11-18',
  '2015-11-19',
  '2015-11-20',
  '2015-11-21',
  '2015-11-22',
  '2015-11-23',
  '2015-11-24',
  '2015-11-25',
  '2015-11-26',
  '2015-11-28',
  '2015-11-29',
  '2015-11-30',
  '2015-12-01',
  '2015-12-02',
  '2015-12-03',
  '2015-12-04',
  '2015-12-05',
  '2015-12-06',
  '2015-12-07',
  '2015-12-08',
  '2015-12-09',
  '2015-12-10',
  '2015-12-11',
  '2015-12-12',
  '2015-12-13',
  '2015-12-14',
  '2015-12-15',
  '2015-12-17',
  '2015-12-19',
  '2015-12-20',
  '2015-12-21',
  '2015-12-22',
  '2015-12-23',
  '2015-12-24',
  '2015-12-25',
  '2015-12-26',
  '2015-12-27',
  '2015-12-28',
  '2015-12-29',
  '2015-12-30',
  '2015-12-31'])

In [7]:
stock_ids = [i for i in range(len(stock_names))]
stock_name_to_ids = dict(zip(stock_names, stock_ids))
stock_name_to_ids

{'AAPL': 0,
 'ABB': 1,
 'ABBV': 2,
 'AEP': 3,
 'AGFS': 4,
 'AMGN': 5,
 'AMZN': 6,
 'BA': 7,
 'BABA': 8,
 'BAC': 9,
 'BBL': 10,
 'BCH': 11,
 'BHP': 12,
 'BP': 13,
 'BRK-A': 14,
 'BSAC': 15,
 'BUD': 16,
 'C': 17,
 'CAT': 18,
 'CELG': 19,
 'CHL': 20,
 'CHTR': 21,
 'CMCSA': 22,
 'CODI': 23,
 'CSCO': 24,
 'CVX': 25,
 'D': 26,
 'DHR': 27,
 'DIS': 28,
 'DUK': 29,
 'EXC': 30,
 'FB': 31,
 'GD': 32,
 'GE': 33,
 'GOOG': 34,
 'HD': 35,
 'HON': 36,
 'HRG': 37,
 'HSBC': 38,
 'IEP': 39,
 'INTC': 40,
 'JNJ': 41,
 'JPM': 42,
 'KO': 43,
 'LMT': 44,
 'MA': 45,
 'MCD': 46,
 'MDT': 47,
 'MMM': 48,
 'MO': 49,
 'MRK': 50,
 'MSFT': 51,
 'NEE': 52,
 'NGG': 53,
 'NVS': 54,
 'ORCL': 55,
 'PCG': 56,
 'PCLN': 57,
 'PEP': 58,
 'PFE': 59,
 'PG': 60,
 'PICO': 61,
 'PM': 62,
 'PPL': 63,
 'PTR': 64,
 'RDS-B': 65,
 'REX': 66,
 'SLB': 67,
 'SNP': 68,
 'SNY': 69,
 'SO': 70,
 'SPLP': 71,
 'SRE': 72,
 'T': 73,
 'TM': 74,
 'TOT': 75,
 'TSM': 76,
 'UL': 77,
 'UN': 78,
 'UNH': 79,
 'UPS': 80,
 'UTX': 81,
 'V': 82,
 'VZ': 83,
 'WFC': 84,
 'WMT': 85,
 'XOM': 86}

In [ ]:
tokens_file = dataset_dir / "all_tweets_tokenized.jsonl"
bad_data_file = dataset_dir / "bad_data.jsonl"

buffer = []
buffer_size = 100_000
lines = 0


with open(json_file, "r", encoding="utf-8") as f, open(tokens_file, "w", encoding="utf-8") as o, open(bad_data_file, "w", encoding="utf-8") as b:
    for line in f:

        entry = json.loads(line)

        stock_name = entry["stock"]
        tweet = entry["tweet"]
        date = entry["date"]


        patterns = [
            rf"\${stock_name}(?=\s|$|\W)", # strict match
            rf"\${stock_name}" # loose match
        ]

        success = False
        for pattern in patterns:
            masked_tweet = re.sub(pattern, "<MASK>", tweet, flags=re.IGNORECASE)
            masked_tweet_tokenized = slot_spm.encode(masked_tweet)

            if mask_id in masked_tweet_tokenized:
                mask_idx = masked_tweet_tokenized.index(mask_id)
                success = True
                break

        if not success:
            bad_entry = {
                "stock": stock_name,
                "tweet": slot_spm.decode(masked_tweet_tokenized)
            }
            b.write(json.dumps(bad_entry) + "\n")
            continue

        # masked_tweet_tokenized = [
        #     tok if tok not in rare_tokens else unk_id
        #     for tok in masked_tweet_tokenized
        # ]


        tokenized_tweet = {
            "date": date,
            "tweet": masked_tweet_tokenized,
            "stock_id": stock_name_to_ids[stock_name],
            "mask_idx": mask_idx
        }


        buffer.append(json.dumps(tokenized_tweet))

        if len(buffer) >= buffer_size:
            o.write("\n".join(buffer) + "\n")
            lines += len(buffer)
            buffer.clear()

            print(f"{lines} lines written")

    if buffer:
        o.write("\n".join(buffer) + "\n")
        lines += len(buffer)
        print(f"{lines} lines written")

100000 lines written
119768 lines written

### Put all the data into lists

In [8]:

tweet_tokens_by_date = [[] for i in range(num_dates)]
mask_indices_by_date = [[] for i in range(num_dates)]


tweet_tokens = []
mask_indices = []
y = []

with open(tokens_file, "r") as f:
    for line in f:
        entry = json.loads(line)

        tokens = [int(tok) for tok in entry["tweet"]]
        idx = entry["mask_idx"]

        tweet_tokens.append(tokens)
        mask_indices.append(idx)
        y.append(entry["stock_id"])

        if entry["date"] in all_dates:
            date = all_dates.index(entry["date"])
            tweet_tokens_by_date[date].append(tokens)
            mask_indices_by_date[date].append(idx)

In [9]:
for i in range(5):
    print(all_dates[i] + ":", tweet_tokens_by_date[i])
    print(all_dates[i] + ":", mask_indices_by_date[i])
    print()

2014-02-19: [[18, 7, 14, 12, 10, 13, 9, 183, 49, 300, 35, 7, 3, 16, 6, 2101, 1470, 1464, 17, 257, 35, 397, 11, 1745, 48, 1800, 11, 5043, 53, 26, 2242, 2118, 1184, 368, 57, 7789, 414, 16, 1384, 820, 8], [7, 3, 35, 233, 939, 426, 381, 95, 137, 3241, 58, 22, 60, 47, 11, 180, 15, 650, 3447, 238, 33, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [749, 37, 835, 79, 2801, 82, 7, 1887, 358, 200, 876, 6, 6241, 6, 4321, 6, 29, 7, 3, 9, 431, 8], [7, 3, 276, 88, 250, 22, 401, 1920, 93, 3295, 20, 5283], [18, 7, 14, 12, 10, 13, 1072, 196, 8150, 3233, 40, 82, 157, 1725, 27, 6, 1362, 17, 6, 254, 7, 3, 9, 4634, 9, 120, 7187, 9, 5414, 9, 1525, 1228, 122, 8], [18, 7, 14, 12, 10, 13, 1072, 196, 8150, 3233, 40, 82, 157, 1725, 27, 6, 1362, 17, 6, 254, 7, 3, 9, 4634, 9, 120, 7187, 9, 5414, 9, 1525, 1228, 122, 8], [8, 367, 228, 3128, 2779, 28, 27, 60, 37, 4345, 1739, 16, 277, 256, 16, 363, 28, 23, 1242, 244, 33, 8, 6, 7476, 6, 131, 7, 3, 6, 55], [7, 3, 35, 825, 4663, 1356, 2323, 66, 798, 89, 447, 11], [18, 7, 14, 12, 10, 13, 1072, 196, 8150, 3233, 40, 82, 157, 1725, 27, 6, 1362, 17, 6, 254, 7, 3, 9, 4634, 9, 120, 7187, 9, 5414, 9, 1525, 1228, 122, 8], [9, 63, 597, 11, 335, 105, 184, 6, 755, 6, 4568, 6, 433, 7, 3, 9, 1028, 8], [7, 3, 221, 100, 7, 14, 12, 10, 13, 8, 7, 19, 11], [7, 3, 221, 100, 7, 14, 12, 10, 13, 8, 7, 19, 11], [18, 7, 14, 12, 10, 13, 4851, 967, 46, 1066, 6864, 7099, 57, 7, 15, 94, 15, 229, 8, 7, 3], [7, 3, 68, 334, 25, 82, 1753, 4140, 35, 8, 8], [7, 14, 12, 10, 13, 5278, 2573, 11, 354, 167, 22, 1719, 3088, 41, 7300, 7, 3, 1613, 455, 52, 1017, 34, 6456, 46, 252, 1647, 11, 394, 28, 222, 445, 330, 70, 238, 811, 15], [18, 7, 14, 12, 10, 13, 1072, 196, 8150, 3233, 40, 82, 157, 1725, 27, 6, 1362, 17, 6, 254, 7, 3, 9, 4634, 9, 120, 7187, 9, 5414, 9, 1525, 1228, 122, 8], [7, 3, 297, 35, 797, 150, 25, 906, 6242, 1892, 272, 901, 11, 506, 20, 151, 202, 5527, 797, 150, 1023, 8], [288, 28, 15, 82, 9, 1076, 2172, 460, 41, 1622, 765, 143, 15, 44, 945, 76, 40, 162, 236, 1313, 697, 1519, 44, 8, 6, 51, 6, 29, 7, 3], [7, 3, 1391, 20, 2721, 57, 4104, 3311, 304, 2015, 1248, 1859, 1749, 8], [1242, 242, 2974, 70, 5768, 1822, 20, 1162, 1263, 8, 6, 74, 6, 38, 1046, 15, 6, 1381, 7, 3], [193, 113, 45, 36, 111, 114, 264, 257, 154, 733, 26, 1729, 228, 6, 74, 413, 317, 356, 26, 7, 3, 4161, 69, 4478, 15, 114, 8], [709, 475, 16, 3114, 222, 125, 25, 11, 330, 842, 81, 91, 7298, 15, 3224, 2270, 179, 194, 34, 8, 49, 7, 3, 8], [7, 3, 221, 100, 2695, 2048, 1315, 16, 8, 1030, 666, 101, 697, 2126, 1471, 142, 81, 138, 16, 72, 265, 797, 150, 69, 28, 15, 359, 3330, 11], [8, 367, 228, 3128, 2779, 28, 27, 60, 37, 4345, 1739, 16, 277, 256, 16, 363, 28, 23, 1242, 244, 33, 8, 6, 7476, 7, 3, 6, 19, 6, 55], [7, 3, 11, 35, 5655, 674, 792, 4407, 34, 2585, 703, 8], [851, 1554, 711, 1164, 319, 1816, 705, 38, 2866, 57, 285, 34, 421, 17, 195, 1835, 176, 1613, 2000, 1475, 812, 7, 3, 8], [7, 3, 285, 34, 421, 173, 48, 67, 53, 90, 16, 202, 28, 15, 201, 27, 285, 34, 421, 39, 8], [7, 3, 287, 723, 737, 884, 43, 37, 994, 5206, 321, 737, 1230, 11, 1781, 200, 737, 1230, 11, 1296, 287, 737, 2164, 11, 316, 392, 737, 1230, 11, 1280, 360, 737, 1556, 1745, 1544, 8], [563, 1485, 517, 62, 408, 1799, 2486, 408, 26, 24, 3488, 161, 3, 2407, 17, 7, 5571, 498, 156, 43, 1380, 229, 743, 75, 17, 40, 1799, 238, 863, 619, 2029, 493, 354, 457, 1200, 129, 354, 871, 15, 17, 2116, 81, 1463, 145, 568, 146, 229, 17, 568, 2113, 39], [375, 2754, 3398, 3245, 193, 5965, 6062, 70, 83, 170, 2548, 2341, 15, 170, 1337, 15, 711, 255, 7, 3, 2105, 30, 2757, 8, 48, 1532, 165, 605, 170, 7, 14, 12, 10, 13], [7, 3, 730, 47, 11, 3924, 15, 61, 425, 27, 621, 2293, 408, 173, 11, 48, 4685, 53, 8], [639, 76, 71, 242, 160, 17, 1670, 222, 145, 2244, 1020, 999, 2215, 240, 239, 100, 278, 46, 105, 96, 426, 1540, 11, 7, 3, 8], [335, 24, 201, 7, 3, 6, 4562, 6, 142, 75, 6, 2332, 810, 8], [7, 3, 439, 11, 38, 11, 38, 11, 20, 379, 669, 26, 1093, 2141, 6107, 180, 8], [546, 28, 15, 123, 3109, 5283, 267, 137, 267, 17, 243, 41, 69, 25, 214, 39, 8, 7, 3, 9, 2702], [7, 3, 35, 41, 4394, 24, 320, 15, 516, 1069, 565, 39, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [196, 2010, 27, 7, 3, 8], [7, 3, 35, 546, 2100, 15, 3165, 3322, 2704, 15, 27, 685, 2673, 1012, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [6, 1750, 6, 83, 7, 3, 8], [5650, 16, 466, 8236, 57, 6, 1754, 8, 6, 102, 7, 3, 6, 526], [1000, 41, 185, 342, 15, 7, 2826, 492, 7, 39, 15, 73, 3682, 919, 39, 3], [1313, 3338, 73, 556, 44, 9, 289, 3338, 1417, 418, 2834, 9, 54, 11, 54, 11, 54, 9, 3, 9, 258, 1105, 9, 153, 4195, 52, 9, 3915, 304, 2809, 8], [162, 89, 391, 26, 7, 3, 6, 4025, 6, 1100, 6, 895, 251, 8], [639, 46, 156, 1191, 26, 6, 1484, 23, 6, 1690, 6, 259, 7, 3, 68, 1036, 8], [9, 42, 20, 214, 6, 5499, 6, 4464, 6, 1653, 7, 3, 9, 1003, 8], [60, 1657, 7, 15, 94, 15, 229, 4851, 6864, 7099, 7, 3, 9, 661, 8], [7, 3, 3407, 24, 3275, 26, 72, 265, 106, 59, 11], [327, 447, 1057, 26, 7, 3, 143, 88, 3959, 69, 257, 11, 4708, 337, 11], [7, 14, 12, 10, 13, 7, 14, 12, 10, 13, 1808, 17, 7, 3, 447, 1353, 27, 2965, 2420, 11, 1000, 41, 6, 51, 2826, 143, 50, 991, 394, 107, 92, 447, 146, 15, 330, 70, 400, 568], [104, 14, 12, 10, 13, 104, 14, 12, 10, 13, 110, 7, 3, 22, 1739, 5738, 71, 1353, 130, 65, 326, 1245, 3677, 160, 1691, 39, 3682, 65, 326, 1245, 601, 363, 28, 23, 3928, 213, 27, 7, 1564, 69, 6324], [18, 7, 14, 12, 10, 13, 7, 3, 20, 1235, 1353, 27, 240, 2965, 291], [18, 7, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [18, 7, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [7, 3, 257, 132, 40, 373, 3453, 11], [18, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [18, 7, 14, 12, 10, 13, 2524, 25, 38, 5644, 170, 7, 3, 9, 661, 6977, 85, 35, 258, 859, 5353, 3399, 212, 3215, 2111, 566, 290, 4249, 1079, 25, 354, 1151, 170, 1353, 966, 2965, 43, 48, 3538, 384, 25, 38, 5644, 53, 33], [18, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [110, 447, 1353, 27, 2965, 4463, 7, 3, 8], [3877, 145, 406, 406, 7, 14, 12, 10, 13, 746, 16, 110, 20, 61, 1353, 27, 240, 2965, 291, 568, 40, 49, 7, 3, 476], [18, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3, 1685, 229, 2299, 17, 1471, 4013, 2783, 1076, 605, 15, 651, 307, 3203, 4533, 15, 170, 1353, 11], [1031, 18, 16, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [18, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [68, 363, 28, 23, 151, 209, 7, 3, 210, 6597, 91, 1353, 3008, 11, 11, 480, 2932, 3450, 1733, 17, 243, 202, 487, 39, 68, 4662, 69, 210, 92, 393, 2078, 58, 11, 11, 480, 5192, 7, 1570, 4618, 11], [18, 7, 14, 12, 10, 13, 3877, 5324, 2299, 44, 389, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [18, 7, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 7, 3, 521, 15, 2965, 43, 27, 367, 1230, 15, 1679, 23, 1568, 202, 28, 15, 5640, 11, 1710, 36, 202, 39, 2492, 11, 110, 521, 15, 2965, 43, 27, 367, 733, 215, 1353, 11], [8024, 93, 7, 3, 3044, 748, 291, 39, 11, 33, 2436, 50, 105, 34, 186, 5296, 3422], [18, 7, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 5422, 7, 3, 49, 3093, 245, 1633, 11, 1394, 41, 1174, 1797, 11, 224, 1837, 328, 1059, 694, 4276, 2080, 165, 301, 3166], [18, 7, 14, 12, 10, 13, 110, 1535, 1739, 5738, 71, 1353, 17, 66, 61, 27, 6, 174, 43, 22, 568, 1414, 1964, 43, 22, 110, 194, 7, 3, 6, 31], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 7, 3, 6295, 15, 3125, 26, 90, 141, 110, 66, 61, 1353, 4060, 1152, 46, 685, 8, 8], [1198, 17, 350, 4577, 17, 938, 28, 15, 193, 1833, 11, 141, 1959, 1392, 28, 23, 538, 447, 76, 7, 3, 49], [18, 7, 14, 12, 10, 13, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 739, 16, 8, 7, 3], [18, 7, 14, 12, 10, 13, 389, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3, 476, 492, 7, 3934, 44], [18, 7, 14, 12, 10, 13, 90, 240, 1353, 6, 908, 291, 1632, 2055, 110, 194, 257, 3125, 22, 245, 37, 4133, 196, 11, 8, 7, 3], [746, 16, 7, 14, 12, 10, 13, 20, 1235, 7, 14, 12, 10, 13, 27, 240, 2965, 291, 11, 541, 7, 3], [18, 7, 14, 12, 10, 13, 194, 34, 110, 1218, 233, 3590, 20, 6, 2624, 11, 1204, 22, 245, 37, 4133, 196, 245, 90, 34, 1353, 383, 11, 8, 7, 3], [1377, 2660, 41, 209, 24, 1353, 1929, 264, 4295, 57, 7, 3, 7, 11], [18, 7, 14, 12, 10, 13, 18, 7, 14, 12, 10, 13, 71, 2154, 34, 1353, 17, 7, 3, 8031, 58, 97, 1304, 34, 24, 771, 4060, 1152, 46, 88, 48, 4249, 590, 30, 46, 20, 72, 221, 53, 8], [2682, 20, 159, 693, 44, 7, 3, 6, 64, 6, 226, 6, 203, 6, 42], [110, 47, 7, 16, 7, 3253, 3230, 1865, 41, 3551, 142, 1330, 2660, 58, 27, 7, 2402, 1633, 22, 627, 423, 5407, 590, 28, 15, 1701, 8, 7, 3], [18, 7, 14, 12, 10, 13, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 739, 16, 8, 7, 3], [18, 7, 14, 12, 10, 13, 746, 16, 110, 28, 15, 5905, 2965, 291, 1353, 2154, 16, 1964, 43, 22, 7, 3, 194, 17, 6, 174, 43, 22, 568, 11, 8], [18, 7, 14, 12, 10, 13, 110, 49, 4494, 26, 90, 34, 1353, 383, 33, 7, 3, 8, 8], [18, 7, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [18, 7, 14, 12, 10, 13, 110, 49, 4494, 26, 90, 34, 1353, 383, 33, 7, 3, 8, 8], [18, 7, 14, 12, 10, 13, 110, 447, 1353, 27, 2965, 43, 8, 7, 3], [1838, 3935, 2491, 9917, 2583, 608, 572, 3073, 2970, 1838, 1495, 2490, 9917, 2556, 2971, 8567, 7, 1462, 458, 2491, 470, 3073, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [18, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [9, 661, 7, 3, 1837, 9, 6059, 27, 6, 908, 43], [18, 7, 14, 12, 10, 13, 110, 49, 4494, 26, 90, 34, 1353, 383, 33, 7, 3, 8, 8], [3541, 57, 7, 14, 12, 10, 13, 2110, 39, 2327, 339, 2116, 323, 1353, 132, 698, 962, 7, 3, 9, 6059, 9, 4356, 5497], [7, 2592, 18, 7, 14, 12, 10, 13, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 739, 16, 8, 7, 3], [18, 7, 14, 12, 10, 13, 18, 7, 14, 12, 10, 13, 110, 48, 3, 53, 5037, 1353, 27, 89, 301, 486, 28, 15, 814, 64, 53, 88, 361, 57, 241, 729, 169, 11], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [7, 14, 12, 10, 13, 1235, 15, 7, 14, 12, 10, 13, 27, 2965, 291, 8, 7, 3], [820, 3697, 170, 423, 2782, 7, 774, 3215, 25, 2061, 7, 3, 796, 3667, 1792, 255, 355, 1030, 3216, 1402], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 90, 240, 1353, 6, 908, 291, 1632, 2055, 110, 194, 257, 3125, 22, 245, 37, 4133, 196, 11, 8, 7, 3], [18, 7, 14, 12, 10, 13, 90, 240, 1353, 6, 908, 291, 1632, 2055, 110, 194, 257, 3125, 22, 245, 37, 4133, 196, 11, 8, 7, 3], [236, 260, 26, 6, 3521, 7, 3, 6, 30, 62, 6, 897, 388, 95, 8], [645, 689, 215, 7, 16, 821, 683, 176, 68, 1012, 20, 4849, 6, 316, 2305, 462, 22, 3513, 17, 1019, 8, 7, 3], [749, 37, 835, 79, 2801, 82, 7, 1887, 358, 200, 876, 6, 6241, 6, 4321, 7, 3, 6, 19, 9, 431, 8], [40, 631, 1816, 7, 3, 705, 127, 2709, 33], [7, 3, 121, 714, 3663, 15, 6, 2539, 462, 40, 4367, 15, 323, 2640, 7, 3324, 16, 121, 714, 3663, 15, 6, 2539, 462, 40, 108, 33, 8], [286, 27, 24, 201, 1081, 165, 150, 6, 80, 6, 6751, 6, 1690, 7, 3, 313, 117, 8], [22, 24, 7, 3, 648, 717, 435, 396, 27, 132, 11, 1204], [18, 7, 14, 12, 10, 13, 121, 396, 7, 5350, 3124, 37, 4215, 518, 367, 28, 5661, 4083, 15, 11, 28, 28, 789, 17, 1463, 145, 44, 369, 9, 1883, 229, 27, 7, 14, 12, 10, 13, 7, 3, 7730, 8], [1096, 125, 3076, 7347, 141, 78, 4958, 30, 20, 2742, 5882, 812, 34, 121, 5629, 16, 7, 15, 11, 280, 11, 17, 5633, 6439, 17, 5015, 313, 17, 683, 6143, 1761, 40, 8159, 7, 432, 3661, 11, 7, 3], [288, 28, 15, 82, 9, 1076, 2172, 460, 41, 1622, 765, 143, 15, 44, 945, 76, 40, 162, 236, 1313, 697, 1519, 44, 8, 6, 51, 7, 3, 6, 19], [286, 20, 1682, 2983, 150, 6, 3051, 7, 3, 6, 142, 30, 1099, 6, 543, 9, 936, 8], [7, 3, 35, 230, 16, 2125, 248, 2899, 15, 116, 2343, 1024, 141, 619, 46, 1243, 4492, 7, 3544, 697, 2047, 54, 2505, 1697, 33, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [196, 2010, 27, 7, 3, 8], [7, 3, 35, 464, 16, 1000, 180, 15, 1096, 125, 8207, 39, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 35, 303, 7, 1973, 1590, 16, 530, 65, 45, 36, 530, 378, 11, 355, 138, 6944, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 202, 7313, 15, 26, 604, 573, 1763, 27, 426, 8], [162, 89, 391, 26, 7, 3, 6, 4967, 6, 38, 52, 438, 6, 2384, 313, 117, 8], [7, 3, 1246, 2408, 93, 621, 11, 52, 11, 767, 2401, 22, 7, 2570, 7, 2572, 8], [7, 3, 836, 37, 942, 5077, 6136, 5264, 7512, 2529, 7, 3136, 1256, 2622, 174, 1384, 194, 48, 5540, 53, 8], [7, 3, 35, 1867, 1908, 474, 1595, 22, 25, 2577, 1561, 71, 4006, 4540, 238, 33, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 1867, 1908, 4799, 68, 43, 38, 37, 791, 662, 6234, 46, 1598, 3164, 46, 2373, 27, 59, 8], [7, 14, 12, 10, 13, 217, 1013, 17, 243, 69, 264, 7, 3, 367, 15, 727, 616, 23, 33], [7, 3, 2333, 1361, 27, 640, 62, 408, 3435, 732, 28, 15, 968, 8], [7, 3, 1538, 111, 1243, 697, 3600, 2174, 319, 20, 2100, 1052, 1611, 3942, 7810, 1424, 160, 59, 8], [7, 3, 3405, 3924, 15, 104, 929, 130, 425, 27, 1171, 65, 45, 36, 146, 48, 204, 53, 8], [7, 3, 202, 60, 210, 1357, 93, 288, 40, 121, 8], [7, 14, 12, 10, 13, 7, 14, 12, 10, 13, 1808, 17, 6, 21, 447, 1353, 27, 2965, 2420, 11, 1000, 41, 7, 3, 2826, 143, 50, 991, 394, 107, 92, 447, 146, 15, 330, 70, 400, 568], [288, 28, 15, 82, 9, 1076, 2172, 460, 41, 1622, 765, 143, 15, 44, 945, 76, 40, 162, 236, 1313, 697, 1519, 44, 8, 7, 3, 6, 29, 6, 19], [2240, 17, 7, 2745, 1090, 394, 28, 222, 4024, 5823, 1996, 46, 218, 1519, 15, 34, 244, 851, 182, 7, 5019, 1042, 7, 3, 6, 2745], [7, 3, 35, 5810, 7582, 6629, 15, 1569, 462, 20, 724, 953, 1577, 5717, 22, 2988, 698, 40, 33, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [286, 27, 24, 201, 1081, 165, 150, 7, 3, 6, 6751, 6, 1690, 6, 29, 313, 117, 8], [7, 3, 239, 3428, 1613, 7652, 176, 169, 37, 6980, 46, 6042, 1255, 5547, 15, 17, 2421, 15, 8], [898, 79, 20, 159, 6, 2961, 6, 4579, 6, 175, 83, 7, 3, 9, 1011, 148, 8], [18, 7, 14, 12, 10, 13, 247, 91, 6521, 20, 392, 26, 6047, 6883, 15, 27, 7, 1554, 86, 493, 7, 7148, 3088, 8, 9, 4292, 9, 7148, 7, 3], [7, 3, 161, 23, 65, 45, 36, 24, 6016, 3328, 37, 2016, 8], [185, 79, 20, 159, 7, 3, 6, 4614, 6, 5620, 6, 4328, 9, 99, 8], [7, 3, 82, 57, 113, 45, 36, 23, 20, 617, 493, 3914, 5521, 468, 2332, 4307, 27, 2431, 71, 972, 3807, 26, 265, 3060, 8], [807, 2485, 2106, 7, 1238, 272, 3704, 2833, 138, 4796, 7914, 247, 821, 20, 145, 653, 23, 2339, 91, 557, 406, 2485, 757, 25, 125, 7, 30, 6690, 3, 807, 2485, 3006, 7, 1252, 3258, 497, 1195, 5546, 621, 238, 7, 101, 1135, 525, 1041, 4653, 673, 4834, 2754, 7914, 83, 4231, 83, 2485, 757], [18, 7, 14, 12, 10, 13, 7, 14, 12, 10, 13, 7, 14, 12, 10, 13, 1679, 846, 307, 4861, 438, 839, 468, 3720, 3720, 3, 919, 120], [7, 3, 49, 723, 737, 884, 43, 37, 994, 5206, 321, 737, 163, 8210, 200, 737, 163, 8210, 287, 737, 1966, 5311, 392, 737, 1966, 5480, 360, 6329, 1190, 1105, 2709, 8], [7, 3, 463, 28, 15, 299, 35, 296, 2897, 173, 48, 4971, 634, 5020, 8159, 830, 165, 2842, 3010, 743, 59, 8], [7, 3, 35, 202, 180, 15, 201, 27, 5655, 674, 792, 39, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 76, 15, 4953, 15, 497, 1551, 390, 41, 2026, 5306, 15, 27, 1241, 698, 34, 2669, 3440, 8], [2264, 3542, 65, 45, 36, 6429, 23, 3568, 17, 8267, 125, 5993, 40, 992, 1430, 5977, 1307, 23, 1436, 23, 15, 59, 7, 3, 8], [7, 3, 1293, 79, 16, 945, 1062, 3258, 4996, 518, 513, 11, 17, 2833, 1427, 617, 215, 17, 2930, 513, 17, 40, 59, 8], [7, 3, 9, 4904, 1468, 1024, 2841, 34, 3615, 194, 1137, 20, 92, 3919, 20, 9, 1985, 83, 73, 1076, 1824, 8], [7, 3, 807, 3965, 37, 540, 336, 7, 2989, 3241, 46, 28, 57, 696, 34, 6031, 5044, 1902], [7, 3, 7, 7842, 857, 2022, 3891, 493, 39, 3830, 1107, 20, 337, 17, 602, 37, 540, 8], [5650, 16, 466, 8236, 57, 6, 1754, 8, 7, 3, 6, 139, 6, 526]]
2014-02-19: [12, 1, 18, 1, 21, 21, 27, 1, 21, 14, 1, 1, 20, 1, 16, 21, 1, 29, 1, 19, 20, 22, 1, 25, 1, 22, 1, 1, 12, 19, 1, 24, 4, 1, 18, 1, 4, 1, 5, 11, 15, 18, 5, 13, 11, 11, 1, 5, 13, 12, 7, 17, 17, 1, 19, 12, 19, 7, 23, 19, 21, 19, 7, 26, 17, 35, 7, 3, 17, 35, 35, 8, 28, 35, 35, 7, 20, 19, 24, 26, 21, 30, 11, 18, 6, 28, 19, 21, 16, 17, 16, 14, 35, 19, 3, 16, 18, 21, 14, 35, 17, 11, 35, 26, 26, 6, 22, 16, 4, 1, 14, 3, 38, 38, 27, 8, 1, 4, 1, 1, 1, 5, 1, 1, 1, 1, 12, 1, 1, 1, 1, 23, 25, 23, 1, 8, 1, 12, 29, 1, 5, 1, 28, 25, 1, 1, 1, 1, 23, 1, 1, 1, 1, 9]


### Pad the token data and shuffle

In [10]:
max_len = max(len(tweet) for tweet in tweet_tokens)


X = [tweet + [pad_id] * (max_len - len(tweet))
    for tweet in tweet_tokens]


X = torch.tensor(X, dtype=torch.long)
y = torch.tensor(y, dtype=torch.long)
mask_indices = torch.tensor(mask_indices, dtype=torch.long)

perm = torch.randperm(X.size(0))
X, y, mask_indices = X[perm], y[perm], mask_indices[perm]

X, X.shape, y, y.shape, mask_indices, mask_indices.shape

(tensor([[  25, 1091, 1369,  ...,    4,    4,    4],
         [  18,    7,   14,  ...,    4,    4,    4],
         [  18,    7,   14,  ...,    4,    4,    4],
         ...,
         [  78,   50,    7,  ...,    4,    4,    4],
         [ 184,  121,   41,  ...,    4,    4,    4],
         [   6, 1330,   49,  ...,    4,    4,    4]]),
 torch.Size([119768, 147]),
 tensor([ 8, 59, 73,  ..., 26,  0, 18]),
 torch.Size([119768]),
 tensor([24, 20, 10,  ...,  7, 14, 20]),
 torch.Size([119768]))

In [11]:
# (num_dates, num_tweets_for_that_date, seq_len)
X_by_date = [
    torch.tensor(
        [tweet + [pad_id] * (max_len - len(tweet)) for tweet in tweet_tokens_by_date[d]],
        dtype=torch.long
    )
    for d in range(num_dates)
]

mask_indices_by_date = [
    torch.tensor(mask_indices_by_date[d], dtype=torch.long)
    for d in range(num_dates)
]

X_by_date[0], X_by_date[0].shape, mask_indices_by_date[0], mask_indices_by_date[0].shape

(tensor([[  18,    7,   14,  ...,    4,    4,    4],
         [   7,    3,   35,  ...,    4,    4,    4],
         [ 749,   37,  835,  ...,    4,    4,    4],
         ...,
         [   7,    3,  807,  ...,    4,    4,    4],
         [   7,    3,    7,  ...,    4,    4,    4],
         [5650,   16,  466,  ...,    4,    4,    4]]),
 torch.Size([154, 147]),
 tensor([12,  1, 18,  1, 21, 21, 27,  1, 21, 14,  1,  1, 20,  1, 16, 21,  1, 29,
          1, 19, 20, 22,  1, 25,  1, 22,  1,  1, 12, 19,  1, 24,  4,  1, 18,  1,
          4,  1,  5, 11, 15, 18,  5, 13, 11, 11,  1,  5, 13, 12,  7, 17, 17,  1,
         19, 12, 19,  7, 23, 19, 21, 19,  7, 26, 17, 35,  7,  3, 17, 35, 35,  8,
         28, 35, 35,  7, 20, 19, 24, 26, 21, 30, 11, 18,  6, 28, 19, 21, 16, 17,
         16, 14, 35, 19,  3, 16, 18, 21, 14, 35, 17, 11, 35, 26, 26,  6, 22, 16,
          4,  1, 14,  3, 38, 38, 27,  8,  1,  4,  1,  1,  1,  5,  1,  1,  1,  1,
         12,  1,  1,  1,  1, 23, 25, 23,  1,  8,  1, 12, 29,  1,  5,  1, 28, 25,
          1,  1,  1,  1, 23,  1,  1,  1,  1,  9]),
 torch.Size([154]))

### Train/val/test split

In [ ]:
data_len = len(y)

train_end = int(data_len * 0.90)
val_end = int(data_len * 1.00)

X_train, y_train, mask_train = X[ : train_end], y[ : train_end], mask_indices[ : train_end]
X_val, y_val, mask_val = X[train_end : val_end], y[train_end : val_end], mask_indices[train_end : val_end]
# X_test, y_test, mask_test = X[val_end : ], y[val_end : ], mask_indices[val_end : ]

print(f"X_train shape: {X_train.shape}. y_train shape: {y_train.shape}")
print(f"X_val shape: {X_val.shape}. y_val shape: {y_val.shape}")
# print(f"X_test shape: {X_test.shape}. y_test shape: {y_test.shape}")

mask_train.shape, mask_val.shape #, mask_test.shape

X_train shape: torch.Size([107791, 147]). y_train shape: torch.Size([107791])
X_val shape: torch.Size([11977, 147]). y_val shape: torch.Size([11977])

(torch.Size([107791]), torch.Size([11977]))

### Datasets

In [ ]:
class SLOTTokensDataset(Dataset):
    def __init__(self, x, y, mask_idx):
        self.x = x
        self.y = y
        self.mask_idx = mask_idx

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx], self.mask_idx[idx]

In [ ]:
train_dataset = SLOTTokensDataset(X_train, y_train, mask_train)
val_dataset = SLOTTokensDataset(X_val, y_val, mask_val)
# test_dataset = SLOTTokensDataset(X_test, y_test, mask_test)

train_dataset[0]

(tensor([  25, 1091, 1369,   68,   28,   54,  883, 4367,   15,   26,   37,    6,
           64,   17,    6, 1164,   17,    6, 4474,   17,    6, 4895,   17,    7,
            3,   17,    6, 2241,   11,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4]),
 tensor(8),
 tensor(24))

In [ ]:
train_size = int(0.5 * len(train_dataset))
val_size = int(0.5 * len(val_dataset))


train_subset, _ = random_split(train_dataset, [train_size, len(train_dataset) - train_size])
val_subset, _ = random_split(val_dataset, [val_size, len(val_dataset) - val_size])

len(train_subset), len(val_subset)

(53895, 5988)

### Model Definition

In [12]:

class StockIdentification(nn.Module):
    def __init__(self, num_stocks, embd_size, hidden_size, vocab_size, dropout, temp):
        super().__init__()
        self.H = hidden_size
        self.temp = temp


        self.stock_embd = nn.Embedding(num_embeddings=num_stocks, embedding_dim=2*hidden_size)


        self.token_embd = nn.Embedding(num_embeddings=vocab_size,
                                       embedding_dim=embd_size,
                                       padding_idx=pad_id)


        self.bi_lstm = nn.LSTM(
            input_size=embd_size,
            hidden_size=hidden_size,
            bidirectional=True,
            batch_first=True,
        )

        self.dropout = nn.Dropout(dropout)

        self.init_weights()

    def init_weights(self):
        nn.init.normal_(self.token_embd.weight, mean=0.0, std=0.01)
        nn.init.normal_(self.stock_embd.weight, mean=0.0, std=0.01)

        for name, param in self.bi_lstm.named_parameters():
            if "bias" in name:
                nn.init.zeros_(param)
                # set forget gate bias to 1
                # [i, f, g, o]
                param.data[self.H : 2*self.H].fill_(1.0)
            elif "weight_ih" in name:
                nn.init.kaiming_normal_(param)
            elif "weight_hh" in name:
                nn.init.orthogonal_(param)


    def forward(self, x, mask_indices):
        # x: (B, T)
        # mask_indices: (B,). The index of the <MASK> token for each tweet
        batch_size = x.size(0)
        token_embs = self.token_embd(x) # (B, T, embd_size)
        token_embs = self.dropout(token_embs)

        seq_lengths = (x != pad_id).sum(dim=-1).to("cpu")
        packed_token_embs = pack_padded_sequence(token_embs, seq_lengths, batch_first=True, enforce_sorted=False)

        # output: (B, T, 2*hidden_size)
        # h_n, c_n : (2*num_layers, B, hidden_size)
        output, (h_n, c_n) = self.bi_lstm(packed_token_embs)

        output, _ = pad_packed_sequence(output, batch_first=True)

        output = self.dropout(output)

        h_e = output[torch.arange(batch_size), mask_indices] # (B, 2*hidden_size)

        h_s = self.stock_embd.weight # (num_stocks, 2*hidden_size)
        h_e = F.normalize(h_e, dim=-1)
        h_s = F.normalize(h_s, dim=-1)
        logits = torch.matmul(h_e, h_s.T) #  (B, 2*hidden_size) @ (2*hidden_size, num_stocks) -> (B, num_stocks)


        return logits / self.temp, h_e, h_s

### Evaluation Functions

In [13]:
stock_id_to_name = {v: k for k, v in stock_name_to_ids.items()}

stock_queries = ["AAPL", "FB", "BA", "BAC"]
stock_query_ids = [stock_name_to_ids[name] for name in stock_queries]

In [14]:
tweet_files_stocks = [tweet.parent.name for tweet in tweet_files_list]
stock_counts = Counter(tweet_files_stocks)

stock_counts = torch.tensor([value for value in stock_counts.values()], dtype=torch.long)
stock_counts = stock_counts.to(device)

N = stock_counts.sum()
inv_freq = N / stock_counts
weights = torch.log1p(inv_freq)
weights = weights / weights.mean()
weights

tensor([0.7389, 1.1751, 0.8591, 1.0505, 1.6898, 0.8491, 0.7453, 0.8261, 0.8199,
        0.7714, 1.1916, 1.5983, 0.9514, 0.8787, 1.5644, 1.4985, 1.0618, 0.7638,
        0.8325, 0.8124, 1.0836, 1.0068, 0.8787, 1.3758, 0.7979, 0.8165, 0.7540,
        1.0836, 0.7962, 1.0179, 1.0078, 0.7399, 0.9836, 0.7882, 0.7432, 0.8452,
        1.0039, 1.3697, 1.1417, 1.1992, 0.7800, 0.8052, 0.7840, 0.8095, 0.9309,
        0.8662, 0.8055, 0.9605, 0.8977, 0.8954, 0.8371, 0.7546, 1.0296, 1.3420,
        0.9793, 0.8752, 1.0618, 0.7815, 0.9069, 0.8172, 0.8577, 1.4402, 0.9898,
        1.0697, 1.2761, 1.8615, 1.1966, 0.9198, 1.3884, 1.0158, 0.9810, 1.6389,
        1.1436, 0.7422, 1.0554, 1.0822, 1.1065, 1.2124, 1.1684, 0.8866, 0.9567,
        0.9256, 0.8063, 0.8199, 0.8289, 0.8055, 0.7918], device='cuda:0')

In [15]:
def evaluate(logits, stock_labels):
    # stock_labels: (B,)
    loss = F.cross_entropy(logits, stock_labels, weight=weights)

    stock_pred = torch.argmax(logits, dim=-1) # (B,)
    acc = (stock_pred == stock_labels).float().mean()

    return loss, acc

In [16]:
def stock_cosine_similarities(model):

    h_s = model.stock_embd.weight # (num_stocks, embd_size)

    h_s_normalized = h_s / h_s.norm(dim=1, keepdim=True)
    h_s_sim = h_s_normalized @ h_s_normalized.T # (num_stocks, embd_size) @ (embd_size, num_stocks) -> (num_stocks, num_stocks)

    # n = h_s_sim.size(0)
    h_s_sim.fill_diagonal_(float("-inf")) # h_s_sim[i][i] = -inf

    h_s_sim = h_s_sim[stock_query_ids] # (4, num_stocks)
    _, top3_indices = torch.topk(h_s_sim, k=3, dim=-1) # (4, 3)


    for query_idx, query in enumerate(stock_queries):
        print(f"\n{query}: ", end="")
        for neigh_idx in top3_indices[query_idx]:
            print(stock_id_to_name[int(neigh_idx.item())], end=", ")


def tweet_embedding_quality(model):

    tweet1 = "<MASK> iphone 6s spec leaks look good. excited. might even buy one." # $AAPL
    tweet2 = "rt AT_USER <MASK> $pep $dps $mnst traditional soft drinks in decline." # $KO

    eval_X = [slot_spm.encode(tweet1), slot_spm.encode(tweet2)]

    max_len = max(len(tweet) for tweet in eval_X)

    eval_X = [tweet + [pad_id] * (max_len - len(tweet)) for tweet in eval_X]

    eval_mask_indices = torch.tensor([eval_X[0].index(mask_id), eval_X[1].index(mask_id)])
    eval_X = torch.tensor(eval_X, dtype=torch.long)

    eval_X, eval_mask_indices = eval_X.to(device), eval_mask_indices.to(device)
    eval_logits, _, _ = model(eval_X, eval_mask_indices)

    eval_preds = F.softmax(eval_logits, dim=-1)
    _, eval_top3_indices = torch.topk(eval_preds, k=3, dim=-1)

    for i, stock in enumerate(eval_top3_indices):
        print()
        for pred in stock:
            print(f"{stock_id_to_name[pred.item()]}: {eval_preds[i][pred.item()].item():.2%}", end = " | ")

### Training Loop

In [ ]:

num_epochs = 50

def objective(trial):

    torch.manual_seed(42)
    torch.cuda.manual_seed(42)

    lr = 0.00248
    batch_size = 256
    embd_size = 128
    hidden_size = 254

    # lr = trial.suggest_float("lr", 1e-5, 1e-2, log=True)
    # batch_size = trial.suggest_categorical("batch_size", [64, 128, 256, 512])
    # embd_size = trial.suggest_categorical("embd_size", [64, 128, 256])
    # hidden_size =  trial.suggest_int("hidden_size", 32, 256)
    # dropout = trial.suggest_float("dropout", 0.0, 0.5)
    # temp = trial.suggest_float("temp", 0.1, 1.0)

    dropout = 0.439
    temp = 0.13356

    # dropout = 0.1
    # temp = 0.25

    wandb.init(
        project="stock_identification_final_test",
        name=f"trial_{trial.number}",
        config={
            "lr": lr,
            "batch_size": batch_size,
            "embd_size": embd_size,
            "hidden_size": hidden_size,
            "dropout": dropout,
            "temp": temp,
            "dataset": "ACL18"
        },
    )

    model = StockIdentification(
        num_stocks=num_stocks,
        embd_size=embd_size,
        hidden_size=hidden_size,
        vocab_size=vocab_size,
        dropout=dropout,
        temp=temp,
    )

    model = model.to(device)



    optimizer = torch.optim.AdamW(params = model.parameters(), lr=lr, weight_decay=1e-3)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(optimizer, T_0=10, T_mult=2, eta_min=1e-6)
    # scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer=optimizer, T_max=num_epochs, eta_min=1e-6)

    train_dataloader = DataLoader(train_subset, batch_size, shuffle=True)
    val_dataloader = DataLoader(val_subset, batch_size, shuffle=False)


    best_val_acc = 0.0

    for epoch in range(num_epochs):
        train_loss = 0.0
        train_acc = 0.0


        model.train()
        for i, (X, y, mask_indices) in enumerate(train_dataloader):
            X, y, mask_indices = X.to(device), y.to(device).to(torch.long), mask_indices.to(device)


            logits, _, _ = model(X, mask_indices) # (B, num_stocks)

            loss, acc = evaluate(logits, y)

            train_loss += loss.detach().item()
            train_acc += acc.item()


            optimizer.zero_grad()

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

            optimizer.step()

            # if i % 300 == 0:
                # print(f"Step: {i:04d} | Train loss: {loss:.4f} | Train acc: {100*acc:.2f}%")



        train_loss /= len(train_dataloader)
        train_acc /= len(train_dataloader)

        val_loss = 0.0
        val_acc = 0.0



        model.eval()
        with torch.inference_mode():
            for j, (X_val, y_val, mask_indices_val) in enumerate(val_dataloader):


                X_val, y_val, mask_indices_val = X_val.to(device), y_val.to(device), mask_indices_val.to(device)

                logits_val, _, _ = model(X_val, mask_indices_val)
                loss, acc = evaluate(logits_val, y_val)

                val_loss += loss.detach().item()
                val_acc += acc.item()

            val_loss /= len(val_dataloader)
            val_acc /= len(val_dataloader)

            best_val_acc = max(best_val_acc, val_acc)


        stock_cosine_similarities(model)
        tweet_embedding_quality(model)


        scheduler.step()

        print(f"\nEpoch: {epoch} | Train loss: {train_loss:.4f} | Train acc: {100*train_acc:.2f}% | Val loss: {val_loss:.4f} | Val acc: {100*val_acc:.2f}%")
        print(f"Learning rate: {optimizer.param_groups[0]['lr']:6f}")

        wandb.log({
            "train_loss": train_loss,
            "train_acc": train_acc,
            "val_loss": val_loss,
            "val_acc": val_acc,
            "best_val_acc": best_val_acc
        })

        trial.report(best_val_acc, step=epoch)
        if trial.should_prune():
            wandb.finish()
            raise optuna.TrialPruned()


        if epoch == 38:
            torch.save(model.state_dict(), dataset_dir / "best_model.pth")


    wandb.finish()
    return best_val_acc


study = optuna.create_study(direction="maximize", pruner=optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=5))
study.optimize(objective, n_trials = 1)

NameError: name 'optuna' is not defined

### Analyze Embedding Quality

In [19]:
# torch.save(model.state_dict(), dataset_dir / "best_model.pth")


# embd_size = 128
# hidden_size = 254
# dropout = 0.439
# temp = 0.13356

embd_size = 128
hidden_size = 64
dropout = 0.1
temp = 0.25


model = StockIdentification(
    num_stocks=num_stocks,
    embd_size=embd_size,
    hidden_size=hidden_size,
    vocab_size=vocab_size,
    dropout=dropout,
    temp=temp
).to(device)

model.load_state_dict(torch.load(dataset_dir / "best_model (1).pth", map_location=device))

In [20]:
torch.manual_seed(42)
torch.cuda.manual_seed(42)

stock_cosine_similarities(model)
print()
tweet_embedding_quality(model)

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, HON,
BAC: WFC, JPM, C,

AAPL: 31.37% | FB: 9.29% | GOOG: 6.47% |
KO: 7.64% | PEP: 4.92% | MCD: 3.15% |

## Stock Movement Prediction

### Global Trend with Attention

The global trend vector is generated by weighting the price features of stocks based on their popularity in tweets.

The average of all tweet embeddings at day $t$ ($g_t$) is used as the query vector.

The key vector is $h_s$, and the value vector is $x_{st}$.

$$
o_t = \sum_{s' \in S} \alpha_{st} x_{st}\;\; \text {where} \;\; \alpha_{st} = \frac{\exp(g_t^\top h_s)}{\sum_{s' \in S} \exp(g_t^\top h_{s'})}
$$

In [21]:
# g_t = torch.load(dataset_dir / "g_t.pt", map_location=device)
# all_tweet_embs = torch.load(dataset_dir / "all_tweet_embs", map_location=device)



all_tweet_embs = []

model.eval()
with torch.inference_mode():
    for d in tqdm(range(num_dates)):
        tweets = X_by_date[d].to(device)
        indices = mask_indices_by_date[d].to(device)

        _, h_e, _ = model(tweets, indices)
        all_tweet_embs.append(h_e)

g_t = torch.stack([torch.mean(h_e, dim=0) for h_e in all_tweet_embs])

torch.save(g_t, dataset_dir / "g_t.pt")
torch.save(all_tweet_embs, dataset_dir / "all_tweet_embs")
g_t.shape # (num_days, 2*hidden_size)

100%|██████████| 651/651 [00:06<00:00, 107.57it/s]

torch.Size([651, 128])

In [ ]:
# a_st (num_days, num_stocks) @ x_st (num_days, num_stocks, num_features) -> o_t (num_days, num_features)
# g_t (num_days, 2*hidden_size)  @ h_s.T (2*hidden_size, num_stocks) -> a_st (num_days, num_stocks)

In [22]:
h_s = model.stock_embd.weight.detach()

attn_scores = torch.matmul(g_t, h_s.T)

a_st = F.softmax(attn_scores, dim=-1)

a_st = a_st.unsqueeze(1)
a_st.shape

torch.Size([651, 1, 87])

In [28]:
o_t = torch.matmul(a_st, X_st).squeeze(1)
o_t = o_t.unsqueeze(1).expand(-1, X_st.size(1), -1)
o_t.shape

torch.Size([651, 87, 11])

### Local Similarities between Stocks

Two steps of attention

1. Attention to find tweets (on the target day) relevant to each target stock. Produces l_st, a weighted sum of the tweets for that day based on their relevance to the target stock.
    - Q: h_s
    - K: h_e
    - V: h_e

2. Attention to find stocks most relevant to l_st, and aggregate the price features based on relevance.
    - Q: l_st
    - K: h_s
    - V: x_st

This is preferable to doing h_s @ h_s.T because it will yield different results based on the day.
- Say $AAPL is doing a collaboration with $MSFT on some day, the attention score for AAPL/MSFT should be higher than usual.

h_s (num_stocks, hidden_size) @ h_e.T (hidden_size, num_tweets_that_day) -> a_e (num_stocks num_tweets_that_day)

a_e (num_stocks num_tweets_that_day) @ h_e (num_tweets_that_day, hidden_size) -> l_st (num_stocks, hidden_size)

In [29]:
l_st = []

for d in range(len(all_tweet_embs)):
    h_e = all_tweet_embs[d]
    a_e = torch.matmul(h_s, h_e.T).softmax(dim=-1)
    l_st.append(torch.matmul(a_e, h_e))

l_st = torch.stack(l_st)
l_st.shape

torch.Size([651, 87, 128])

l_st (num_days, num_stocks, hidden_size) @ h_s.T (hidden_size, num_stocks) -> a_st (num_days, num_stocks, num_stocks)

a_st (num_days, num_stocks, num_stocks) @ X_st (num_days, num_stocks, num_features) -> c_st (num_days, num_stocks, num_features)

In [30]:
a_st = torch.matmul(l_st, h_s.T).softmax(dim=-1)
c_st = torch.matmul(a_st, X_st)

c_st.shape

torch.Size([651, 87, 11])

### Windows

In [31]:
def create_windows(input, labels=False):
    if (labels):
        windows_list = [input[t+1] for t in range(window_size - 1, num_dates-1)]
    else:
        windows_list = [input[t-window_size+1 : t+1] for t in range(window_size - 1, num_dates-1)]

    # input: (num_windows, seq_len, num_stocks, features)
    # labels: (num_windows, num_stocks)
    windows = torch.stack(windows_list)

    if labels:
        windows = windows.reshape(-1)

    else:
        windows=windows.reshape(-1, windows.size(1), windows.size(-1))

    return windows

In [32]:
X_windowed, o_windowed, c_windowed = create_windows(X_st), create_windows(o_t), create_windows(c_st)
y_windowed = create_windows(y, labels=True)

X_windowed.shape, o_windowed.shape, c_windowed.shape, y_windowed.shape

(torch.Size([55332, 15, 11]),
 torch.Size([55332, 15, 11]),
 torch.Size([55332, 15, 11]),
 torch.Size([55332]))

In [33]:
mask = y_windowed != 0

X_windowed = X_windowed[mask]
o_windowed = o_windowed[mask]
c_windowed = c_windowed[mask]
y_windowed = y_windowed[mask]


X_windowed.shape, o_windowed.shape, c_windowed.shape, y_windowed.shape

(torch.Size([33711, 15, 11]),
 torch.Size([33711, 15, 11]),
 torch.Size([33711, 15, 11]),
 torch.Size([33711]))

### Train/Val/Test Split

In [34]:
data_len = len(y_windowed)

train_end = int(data_len * 0.70)
val_end = int(data_len * 0.85)

X_train, o_train, c_train, y_train = X_windowed[: train_end], o_windowed[: train_end], c_windowed[: train_end], y_windowed[: train_end]
X_val, o_val, c_val, y_val = X_windowed[train_end : val_end], o_windowed[train_end : val_end], c_windowed[train_end :val_end], y_windowed[train_end : val_end]
X_test, o_test, c_test, y_test = X_windowed[val_end :], o_windowed[val_end :], c_windowed[val_end :], y_windowed[val_end :]

print(f"X_train shape: {X_train.shape}. y_train shape: {y_train.shape}")
print(f"X_val shape: {X_val.shape}. y_val shape: {y_val.shape}")
print(f"X_test shape: {X_test.shape}. y_test shape: {y_test.shape}")

X_train shape: torch.Size([23597, 15, 11]). y_train shape: torch.Size([23597])
X_val shape: torch.Size([5057, 15, 11]). y_val shape: torch.Size([5057])
X_test shape: torch.Size([5057, 15, 11]). y_test shape: torch.Size([5057])

### Multi-Feature Dataset

In [35]:
class MultiFeatureDataset(Dataset):
    def __init__(self, x, o, c, y):
        super().__init__()
        self.x = x; self.o = o; self.c = c
        self.y = y

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.o[idx], self.c[idx], self.y[idx]

In [36]:
train_dataset = MultiFeatureDataset(X_train, o_train, c_train, y_train)
val_dataset = MultiFeatureDataset(X_val, o_val, c_val, y_val)
test_dataset = MultiFeatureDataset(X_test, o_test, c_test, y_test)

### DataLoaders

In [37]:
train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_dataloader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
test_dataloader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)
len(train_dataloader)

24

In [38]:
X, o, c, y = next(iter(train_dataloader))
X.shape

torch.Size([1024, 15, 11])

### SLOT Model Code

In [39]:
class SLOT(nn.Module):
    def __init__(self, input_size, hidden_size, dropout, output_size = 1):
        super().__init__()
        self.ln = nn.Linear(3*input_size, input_size)
        self.alstm = ALSTM(input_size=input_size, hidden_size=hidden_size, dropout=dropout)
        self.dropout = nn.Dropout(dropout)
        self.ln_f = nn.Linear(hidden_size*2, output_size)



    def forward(self, X_st, o_t, c_st):
        # X_st, o_t, c_st: (batch, seq_len, input_size)
        final_input = torch.cat((X_st, o_t, c_st), dim=-1) # (batch, seq_len, 3*input_size)
        final_input = self.ln(final_input) # (batch, seq_len, input_size)

        h_out = self.alstm(final_input) # (batch, 2*hidden_size)
        h_out = self.dropout(h_out)
        y_pred = self.ln_f(h_out) # (batch, output_size)

        return y_pred.squeeze(-1)

### Training Helper Functions

In [40]:
def evaluate(logits, y):
  # logits: (batch,)
  # y: (batch, )
  B = logits.size(0)

  loss = torch.clamp(1 - y * logits, min=0).mean()

  preds = torch.sign(logits) # (batch,)
  acc = (preds == y).float().mean().detach()

  return loss, acc.item()

In [58]:
def training_loop(trial, lr, hidden_size, weight_decay, dropout, use_existing=False):
  torch.manual_seed(42)
  torch.cuda.manual_seed(42)

  model = SLOT(
      input_size=len(price_features),
      hidden_size=hidden_size,
      dropout=dropout
  ).to(device)


  if use_existing:
    model.load_state_dict(torch.load(dataset_dir / "best_SLOT_model.pth", map_location=device))

  optimizer = torch.optim.AdamW(params = model.parameters(), lr=lr, weight_decay=weight_decay)
  scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer=optimizer, T_max=num_epochs, eta_min=1e-6)


  best_val_acc = 0.0
  epochs_no_improve = 0
  patience = 50

  for epoch in range(num_epochs):
    train_loss = 0.0
    train_acc = 0.0



    model.train()
    for i, (X, o, c, y) in enumerate(train_dataloader):


        X, o, c, y = X.to(device), o.to(device), c.to(device), y.to(device)

        logits = model(X, o, c) # (batch, output_size)

        loss, acc = evaluate(logits, y)

        train_loss += loss.detach().item()
        train_acc += acc

        optimizer.zero_grad()
        loss.backward()

        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

        optimizer.step()


    train_loss /= len(train_dataloader)
    train_acc /= len(train_dataloader)



    val_loss = 0.0
    val_acc = 0.0


    model.eval()

    with torch.inference_mode():
        for i, (X_val, o_val, c_val, y_val) in enumerate(val_dataloader):

            X_val, o_val, c_val, y_val = X_val.to(device), o_val.to(device), c_val.to(device), y_val.to(device)

            logits = model(X_val, o_val, c_val)

            loss, acc = evaluate(logits, y_val)

            val_loss += loss.item()
            val_acc += acc


        val_loss /= len(val_dataloader)
        val_acc /= len(val_dataloader)

    if val_acc > best_val_acc:
          best_val_acc = val_acc
          epochs_no_improve = 0
    else:
        epochs_no_improve += 1


    if epochs_no_improve >= patience:
        break

    wandb.log({
        "train_loss": train_loss,
        "train_acc": train_acc,
        "val_loss": val_loss,
        "val_acc": val_acc,
    })

    scheduler.step()

    print(f"Epoch: {epoch:03d} | Train loss: {train_loss:.4f} | Train acc: {100*train_acc:.2f}% | Val loss: {val_loss:.4f} | Val acc: {100*val_acc:.2f}% | LR: {optimizer.param_groups[0]['lr']:6f}")


  wandb.log({
      "last_val_acc": val_acc
  })

  wandb.finish()
  return val_acc

### Training Loop

In [ ]:
def objective(trial):

    lr = trial.suggest_float("lr", 1e-4, 1e-2, log=True)
    hidden_size =  trial.suggest_int("hidden_size", 64, 256)
    dropout = trial.suggest_float("dropout", 0.1, 0.5)
    weight_decay = trial.suggest_float("weight_decay", 1e-4, 1e-2, log=True)

    wandb.init(
    project="SLOT_Train",
    name=f"trial_{trial.number}",
    config={
            "lr": lr,
            "hidden_size": hidden_size,
            "dropout": dropout,
            "weight_decay": weight_decay,
        },
    )

    return training_loop(trial, lr, hidden_size, dropout, weight_decay)


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials = 200)

[I 2025-09-23 16:05:17,028] A new study created in memory with name: no-name-cbbbd594-ca63-40fa-98cf-0e52903d248b

Epoch: 000 | Train loss: 1.0094 | Train acc: 50.32% | Val loss: 1.0073 | Val acc: 45.95% | LR: 0.000042
Epoch: 001 | Train loss: 0.9992 | Train acc: 50.25% | Val loss: 1.0060 | Val acc: 46.16% | LR: 0.000042
Epoch: 002 | Train loss: 1.0004 | Train acc: 49.45% | Val loss: 1.0079 | Val acc: 46.25% | LR: 0.000042
Epoch: 003 | Train loss: 0.9986 | Train acc: 50.67% | Val loss: 1.0063 | Val acc: 46.34% | LR: 0.000042
Epoch: 004 | Train loss: 0.9979 | Train acc: 50.96% | Val loss: 1.0061 | Val acc: 46.13% | LR: 0.000042
Epoch: 005 | Train loss: 0.9980 | Train acc: 50.60% | Val loss: 1.0062 | Val acc: 46.14% | LR: 0.000042
Epoch: 006 | Train loss: 0.9985 | Train acc: 50.14% | Val loss: 1.0070 | Val acc: 46.16% | LR: 0.000042
Epoch: 007 | Train loss: 0.9979 | Train acc: 50.55% | Val loss: 1.0062 | Val acc: 46.18% | LR: 0.000042
Epoch: 008 | Train loss: 0.9985 | Train acc: 50.24% | Val loss: 1.0077 | Val acc: 46.07% | LR: 0.000042
Epoch: 009 | Train loss: 0.9976 | Train acc: 50.97% | Val loss: 1.0067 | Val acc: 46.06% | LR: 0.000042
Epoch: 010 | Train loss: 1.0000 | Train acc: 49.89% | Val loss: 1.0071 | Val acc: 46.24% | LR: 0.000042
Epoch: 011 | Train loss: 0.9991 | Train acc: 50.14% | Val loss: 1.0072 | Val acc: 46.09% | LR: 0.000042
Epoch: 012 | Train loss: 0.9976 | Train acc: 50.59% | Val loss: 1.0055 | Val acc: 46.38% | LR: 0.000042
Epoch: 013 | Train loss: 0.9986 | Train acc: 50.41% | Val loss: 1.0066 | Val acc: 46.02% | LR: 0.000042
Epoch: 014 | Train loss: 0.9964 | Train acc: 50.82% | Val loss: 1.0069 | Val acc: 46.01% | LR: 0.000041
Epoch: 015 | Train loss: 0.9984 | Train acc: 50.25% | Val loss: 1.0076 | Val acc: 45.99% | LR: 0.000041
Epoch: 016 | Train loss: 0.9963 | Train acc: 50.88% | Val loss: 1.0074 | Val acc: 46.05% | LR: 0.000041
Epoch: 017 | Train loss: 0.9954 | Train acc: 50.89% | Val loss: 1.0086 | Val acc: 46.09% | LR: 0.000041
Epoch: 018 | Train loss: 0.9985 | Train acc: 50.18% | Val loss: 1.0067 | Val acc: 46.12% | LR: 0.000041
Epoch: 019 | Train loss: 0.9968 | Train acc: 50.76% | Val loss: 1.0072 | Val acc: 46.07% | LR: 0.000041
Epoch: 020 | Train loss: 0.9958 | Train acc: 50.74% | Val loss: 1.0187 | Val acc: 45.85% | LR: 0.000040
Epoch: 021 | Train loss: 0.9977 | Train acc: 50.43% | Val loss: 1.0107 | Val acc: 45.99% | LR: 0.000040
Epoch: 022 | Train loss: 0.9988 | Train acc: 50.29% | Val loss: 1.0364 | Val acc: 46.11% | LR: 0.000040
Epoch: 023 | Train loss: 0.9994 | Train acc: 50.32% | Val loss: 1.0060 | Val acc: 46.25% | LR: 0.000040
Epoch: 024 | Train loss: 0.9955 | Train acc: 50.78% | Val loss: 1.0080 | Val acc: 46.03% | LR: 0.000040
Epoch: 025 | Train loss: 0.9940 | Train acc: 50.88% | Val loss: 1.0279 | Val acc: 45.76% | LR: 0.000039
Epoch: 026 | Train loss: 0.9946 | Train acc: 50.66% | Val loss: 1.0088 | Val acc: 45.66% | LR: 0.000039
Epoch: 027 | Train loss: 0.9958 | Train acc: 50.55% | Val loss: 1.0335 | Val acc: 45.88% | LR: 0.000039
Epoch: 028 | Train loss: 0.9979 | Train acc: 50.18% | Val loss: 1.0068 | Val acc: 46.03% | LR: 0.000039
Epoch: 029 | Train loss: 0.9946 | Train acc: 50.70% | Val loss: 1.0067 | Val acc: 45.93% | LR: 0.000038
Epoch: 030 | Train loss: 0.9914 | Train acc: 50.95% | Val loss: 1.0068 | Val acc: 45.97% | LR: 0.000038
Epoch: 031 | Train loss: 0.9968 | Train acc: 50.45% | Val loss: 1.0068 | Val acc: 46.03% | LR: 0.000038
Epoch: 032 | Train loss: 0.9939 | Train acc: 50.51% | Val loss: 1.0068 | Val acc: 46.01% | LR: 0.000038
Epoch: 033 | Train loss: 0.9994 | Train acc: 49.77% | Val loss: 1.0069 | Val acc: 45.95% | LR: 0.000037
Epoch: 034 | Train loss: 0.9985 | Train acc: 50.18% | Val loss: 1.0068 | Val acc: 45.95% | LR: 0.000037
Epoch: 035 | Train loss: 0.9971 | Train acc: 50.24% | Val loss: 1.0068 | Val acc: 45.97% | LR: 0.000037
Epoch: 036 | Train loss: 0.9952 | Train acc: 50.52% | Val loss: 1.0069 | Val acc: 45.97% | LR: 0.000037
Epoch: 037 | Train loss: 0.9929 | Train acc: 50.77% | Val loss: 1.0069 | Val acc: 46.01% | LR: 0.000036
Epoch: 038 | Train loss: 0.9970 | Train acc: 49.97% | Val loss: 1.0070 | Val acc: 45.95% | LR: 0.000036
Epoch: 039 | Train loss: 0.9963 | Train acc: 50.21% | Val loss: 1.0069 | Val acc: 45.81% | LR: 0.000036
Epoch: 040 | Train loss: 0.9925 | Train acc: 50.78% | Val loss: 1.0069 | Val acc: 45.85% | LR: 0.000035
Epoch: 041 | Train loss: 0.9938 | Train acc: 50.43% | Val loss: 1.0070 | Val acc: 45.86% | LR: 0.000035
Epoch: 042 | Train loss: 0.9926 | Train acc: 50.48% | Val loss: 1.0070 | Val acc: 45.85% | LR: 0.000035
Epoch: 043 | Train loss: 0.9914 | Train acc: 50.60% | Val loss: 1.0069 | Val acc: 45.83% | LR: 0.000034
Epoch: 044 | Train loss: 0.9949 | Train acc: 50.36% | Val loss: 1.0069 | Val acc: 45.77% | LR: 0.000034
Epoch: 045 | Train loss: 0.9925 | Train acc: 50.65% | Val loss: 1.0069 | Val acc: 45.76% | LR: 0.000034
Epoch: 046 | Train loss: 0.9867 | Train acc: 51.06% | Val loss: 1.0069 | Val acc: 45.72% | LR: 0.000033
Epoch: 047 | Train loss: 0.9962 | Train acc: 50.21% | Val loss: 1.0070 | Val acc: 45.74% | LR: 0.000033
Epoch: 048 | Train loss: 0.9910 | Train acc: 50.73% | Val loss: 1.0070 | Val acc: 45.80% | LR: 0.000032
Epoch: 049 | Train loss: 0.9902 | Train acc: 50.42% | Val loss: 1.0070 | Val acc: 45.77% | LR: 0.000032
Epoch: 050 | Train loss: 0.9964 | Train acc: 50.15% | Val loss: 1.0070 | Val acc: 45.76% | LR: 0.000032
Epoch: 051 | Train loss: 0.9883 | Train acc: 50.80% | Val loss: 1.0070 | Val acc: 45.72% | LR: 0.000031
Epoch: 052 | Train loss: 0.9990 | Train acc: 50.07% | Val loss: 1.0070 | Val acc: 45.74% | LR: 0.000031
Epoch: 053 | Train loss: 0.9956 | Train acc: 50.13% | Val loss: 1.0070 | Val acc: 45.68% | LR: 0.000031
Epoch: 054 | Train loss: 0.9903 | Train acc: 50.84% | Val loss: 1.0070 | Val acc: 45.77% | LR: 0.000030
Epoch: 055 | Train loss: 0.9999 | Train acc: 49.94% | Val loss: 1.0071 | Val acc: 45.80% | LR: 0.000030
Epoch: 056 | Train loss: 0.9980 | Train acc: 50.05% | Val loss: 1.0070 | Val acc: 45.76% | LR: 0.000029
Epoch: 057 | Train loss: 0.9959 | Train acc: 50.21% | Val loss: 1.0069 | Val acc: 45.83% | LR: 0.000029
Epoch: 058 | Train loss: 0.9942 | Train acc: 50.15% | Val loss: 1.0069 | Val acc: 45.83% | LR: 0.000029
Epoch: 059 | Train loss: 0.9911 | Train acc: 50.68% | Val loss: 1.0068 | Val acc: 45.78% | LR: 0.000028
Epoch: 060 | Train loss: 0.9910 | Train acc: 50.60% | Val loss: 1.0068 | Val acc: 45.74% | LR: 0.000028
Epoch: 061 | Train loss: 0.9908 | Train acc: 50.36% | Val loss: 1.0068 | Val acc: 45.70% | LR: 0.000027

[I 2025-09-23 16:06:06,148] Trial 0 finished with value: 0.4585541248321533 and parameters: {'lr': 4.242552556008561e-05, 'hidden_size': 67, 'dropout': 0.11112776585729019, 'weight_decay': 0.009032557171212758}. Best is trial 0 with value: 0.4585541248321533.

Epoch: 000 | Train loss: 0.9961 | Train acc: 50.62% | Val loss: 1.0062 | Val acc: 46.01% | LR: 0.000065
Epoch: 001 | Train loss: 0.9927 | Train acc: 50.87% | Val loss: 1.0060 | Val acc: 45.97% | LR: 0.000065
Epoch: 002 | Train loss: 0.9897 | Train acc: 50.78% | Val loss: 1.0069 | Val acc: 45.93% | LR: 0.000065
Epoch: 003 | Train loss: 0.9922 | Train acc: 50.48% | Val loss: 1.0065 | Val acc: 46.21% | LR: 0.000065
Epoch: 004 | Train loss: 0.9987 | Train acc: 50.24% | Val loss: 1.0051 | Val acc: 46.62% | LR: 0.000065
Epoch: 005 | Train loss: 0.9883 | Train acc: 51.11% | Val loss: 1.0039 | Val acc: 47.37% | LR: 0.000065
Epoch: 006 | Train loss: 0.9951 | Train acc: 50.53% | Val loss: 1.0027 | Val acc: 48.20% | LR: 0.000065
Epoch: 007 | Train loss: 0.9909 | Train acc: 50.99% | Val loss: 1.0015 | Val acc: 48.66% | LR: 0.000065
Epoch: 008 | Train loss: 0.9867 | Train acc: 51.20% | Val loss: 1.0019 | Val acc: 48.66% | LR: 0.000064
Epoch: 009 | Train loss: 0.9854 | Train acc: 51.29% | Val loss: 1.0012 | Val acc: 49.55% | LR: 0.000064
Epoch: 010 | Train loss: 0.9891 | Train acc: 51.01% | Val loss: 1.0013 | Val acc: 49.77% | LR: 0.000064
Epoch: 011 | Train loss: 0.9969 | Train acc: 50.30% | Val loss: 0.9996 | Val acc: 50.25% | LR: 0.000064
Epoch: 012 | Train loss: 0.9903 | Train acc: 50.81% | Val loss: 0.9962 | Val acc: 50.48% | LR: 0.000064
Epoch: 013 | Train loss: 0.9891 | Train acc: 50.88% | Val loss: 0.9911 | Val acc: 50.61% | LR: 0.000064
Epoch: 014 | Train loss: 0.9996 | Train acc: 51.04% | Val loss: 0.9918 | Val acc: 50.69% | LR: 0.000063
Epoch: 015 | Train loss: 0.9847 | Train acc: 51.10% | Val loss: 1.1438 | Val acc: 50.21% | LR: 0.000063
Epoch: 016 | Train loss: 0.9994 | Train acc: 50.25% | Val loss: 0.9958 | Val acc: 50.44% | LR: 0.000063
Epoch: 017 | Train loss: 0.9943 | Train acc: 50.72% | Val loss: 0.9981 | Val acc: 51.08% | LR: 0.000063
Epoch: 018 | Train loss: 0.9835 | Train acc: 51.39% | Val loss: 1.0065 | Val acc: 50.61% | LR: 0.000062
Epoch: 019 | Train loss: 0.9888 | Train acc: 51.10% | Val loss: 1.0023 | Val acc: 50.81% | LR: 0.000062
Epoch: 020 | Train loss: 0.9975 | Train acc: 50.31% | Val loss: 1.0157 | Val acc: 50.66% | LR: 0.000062
Epoch: 021 | Train loss: 0.9800 | Train acc: 51.58% | Val loss: 1.0041 | Val acc: 50.50% | LR: 0.000062
Epoch: 022 | Train loss: 0.9861 | Train acc: 51.32% | Val loss: 1.0087 | Val acc: 50.41% | LR: 0.000061
Epoch: 023 | Train loss: 0.9864 | Train acc: 50.84% | Val loss: 1.0362 | Val acc: 50.09% | LR: 0.000061
Epoch: 024 | Train loss: 0.9862 | Train acc: 50.85% | Val loss: 1.0095 | Val acc: 50.30% | LR: 0.000061
Epoch: 025 | Train loss: 0.9829 | Train acc: 51.34% | Val loss: 1.0162 | Val acc: 50.14% | LR: 0.000060
Epoch: 026 | Train loss: 0.9821 | Train acc: 51.07% | Val loss: 1.0056 | Val acc: 49.98% | LR: 0.000060
Epoch: 027 | Train loss: 0.9877 | Train acc: 50.87% | Val loss: 1.0007 | Val acc: 50.23% | LR: 0.000060
Epoch: 028 | Train loss: 0.9823 | Train acc: 51.05% | Val loss: 1.0166 | Val acc: 49.71% | LR: 0.000059
Epoch: 029 | Train loss: 0.9941 | Train acc: 50.95% | Val loss: 1.0001 | Val acc: 49.83% | LR: 0.000059
Epoch: 030 | Train loss: 0.9876 | Train acc: 50.67% | Val loss: 1.0029 | Val acc: 49.70% | LR: 0.000058
Epoch: 031 | Train loss: 1.0534 | Train acc: 50.88% | Val loss: 1.0024 | Val acc: 49.62% | LR: 0.000058
Epoch: 032 | Train loss: 0.9958 | Train acc: 50.70% | Val loss: 1.1119 | Val acc: 50.04% | LR: 0.000058
Epoch: 033 | Train loss: 0.9854 | Train acc: 50.77% | Val loss: 1.0086 | Val acc: 49.76% | LR: 0.000057
Epoch: 034 | Train loss: 0.9869 | Train acc: 50.76% | Val loss: 1.0125 | Val acc: 49.59% | LR: 0.000057
Epoch: 035 | Train loss: 0.9789 | Train acc: 51.32% | Val loss: 1.0094 | Val acc: 50.02% | LR: 0.000056
Epoch: 036 | Train loss: 0.9836 | Train acc: 51.09% | Val loss: 1.0001 | Val acc: 49.68% | LR: 0.000056
Epoch: 037 | Train loss: 0.9859 | Train acc: 50.84% | Val loss: 1.0090 | Val acc: 49.35% | LR: 0.000055
Epoch: 038 | Train loss: 0.9854 | Train acc: 51.21% | Val loss: 1.0109 | Val acc: 49.70% | LR: 0.000055
Epoch: 039 | Train loss: 0.9795 | Train acc: 51.18% | Val loss: 1.0050 | Val acc: 50.30% | LR: 0.000054
Epoch: 040 | Train loss: 0.9898 | Train acc: 50.48% | Val loss: 1.0028 | Val acc: 49.66% | LR: 0.000054
Epoch: 041 | Train loss: 0.9896 | Train acc: 50.82% | Val loss: 1.0026 | Val acc: 50.15% | LR: 0.000053
Epoch: 042 | Train loss: 0.9789 | Train acc: 51.35% | Val loss: 0.9993 | Val acc: 50.50% | LR: 0.000053
Epoch: 043 | Train loss: 0.9833 | Train acc: 51.22% | Val loss: 1.0068 | Val acc: 49.74% | LR: 0.000052
Epoch: 044 | Train loss: 0.9894 | Train acc: 50.66% | Val loss: 1.0006 | Val acc: 49.90% | LR: 0.000052
Epoch: 045 | Train loss: 0.9809 | Train acc: 51.03% | Val loss: 1.0029 | Val acc: 49.82% | LR: 0.000051
Epoch: 046 | Train loss: 0.9874 | Train acc: 50.83% | Val loss: 1.0057 | Val acc: 50.05% | LR: 0.000051
Epoch: 047 | Train loss: 0.9865 | Train acc: 50.73% | Val loss: 1.0576 | Val acc: 50.02% | LR: 0.000050
Epoch: 048 | Train loss: 0.9836 | Train acc: 50.84% | Val loss: 1.0033 | Val acc: 49.70% | LR: 0.000050
Epoch: 049 | Train loss: 0.9836 | Train acc: 50.97% | Val loss: 1.0034 | Val acc: 49.88% | LR: 0.000049
Epoch: 050 | Train loss: 0.9843 | Train acc: 50.87% | Val loss: 1.0029 | Val acc: 49.85% | LR: 0.000048
Epoch: 051 | Train loss: 0.9875 | Train acc: 50.50% | Val loss: 1.0003 | Val acc: 49.94% | LR: 0.000048
Epoch: 052 | Train loss: 0.9769 | Train acc: 51.30% | Val loss: 1.0242 | Val acc: 49.94% | LR: 0.000047
Epoch: 053 | Train loss: 0.9865 | Train acc: 50.78% | Val loss: 1.0033 | Val acc: 49.88% | LR: 0.000047
Epoch: 054 | Train loss: 0.9891 | Train acc: 51.09% | Val loss: 1.0055 | Val acc: 49.75% | LR: 0.000046
Epoch: 055 | Train loss: 0.9840 | Train acc: 50.96% | Val loss: 1.0023 | Val acc: 49.93% | LR: 0.000045
Epoch: 056 | Train loss: 0.9830 | Train acc: 50.82% | Val loss: 1.0088 | Val acc: 49.87% | LR: 0.000045
Epoch: 057 | Train loss: 0.9770 | Train acc: 51.48% | Val loss: 1.0038 | Val acc: 49.69% | LR: 0.000044
Epoch: 058 | Train loss: 0.9864 | Train acc: 51.02% | Val loss: 1.0051 | Val acc: 49.85% | LR: 0.000043
Epoch: 059 | Train loss: 0.9934 | Train acc: 50.40% | Val loss: 1.0188 | Val acc: 49.82% | LR: 0.000043
Epoch: 060 | Train loss: 0.9825 | Train acc: 51.03% | Val loss: 1.0101 | Val acc: 49.80% | LR: 0.000042
Epoch: 061 | Train loss: 0.9817 | Train acc: 50.94% | Val loss: 1.0031 | Val acc: 49.78% | LR: 0.000042
Epoch: 062 | Train loss: 0.9955 | Train acc: 50.32% | Val loss: 1.0017 | Val acc: 49.79% | LR: 0.000041
Epoch: 063 | Train loss: 0.9827 | Train acc: 50.95% | Val loss: 1.0030 | Val acc: 49.80% | LR: 0.000040
Epoch: 064 | Train loss: 0.9848 | Train acc: 50.76% | Val loss: 1.0026 | Val acc: 49.96% | LR: 0.000040
Epoch: 065 | Train loss: 0.9844 | Train acc: 50.86% | Val loss: 1.0032 | Val acc: 49.89% | LR: 0.000039
Epoch: 066 | Train loss: 0.9814 | Train acc: 51.03% | Val loss: 1.0034 | Val acc: 49.97% | LR: 0.000038

[I 2025-09-23 16:08:10,416] Trial 1 finished with value: 0.4993742346763611 and parameters: {'lr': 6.49566168056826e-05, 'hidden_size': 191, 'dropout': 0.47635514030719595, 'weight_decay': 4.5181089524218225e-05}. Best is trial 1 with value: 0.4993742346763611.

Epoch: 000 | Train loss: 1.0022 | Train acc: 50.04% | Val loss: 1.0059 | Val acc: 45.83% | LR: 0.000026
Epoch: 001 | Train loss: 0.9993 | Train acc: 50.61% | Val loss: 1.0074 | Val acc: 46.13% | LR: 0.000026
Epoch: 002 | Train loss: 1.0023 | Train acc: 50.57% | Val loss: 1.0105 | Val acc: 45.64% | LR: 0.000026
Epoch: 003 | Train loss: 1.0005 | Train acc: 50.96% | Val loss: 1.0055 | Val acc: 46.36% | LR: 0.000025
Epoch: 004 | Train loss: 1.0060 | Train acc: 50.04% | Val loss: 1.0103 | Val acc: 45.81% | LR: 0.000025
Epoch: 005 | Train loss: 1.0060 | Train acc: 50.67% | Val loss: 1.0151 | Val acc: 46.28% | LR: 0.000025
Epoch: 006 | Train loss: 1.0089 | Train acc: 50.06% | Val loss: 1.0073 | Val acc: 46.12% | LR: 0.000025
Epoch: 007 | Train loss: 1.0001 | Train acc: 50.59% | Val loss: 1.0097 | Val acc: 45.96% | LR: 0.000025
Epoch: 008 | Train loss: 0.9990 | Train acc: 50.36% | Val loss: 1.0084 | Val acc: 46.17% | LR: 0.000025
Epoch: 009 | Train loss: 1.0631 | Train acc: 50.58% | Val loss: 1.0059 | Val acc: 46.01% | LR: 0.000025
Epoch: 010 | Train loss: 0.9987 | Train acc: 50.56% | Val loss: 1.0057 | Val acc: 46.09% | LR: 0.000025
Epoch: 011 | Train loss: 0.9995 | Train acc: 50.35% | Val loss: 1.0065 | Val acc: 45.97% | LR: 0.000025
Epoch: 012 | Train loss: 1.0285 | Train acc: 50.70% | Val loss: 1.0048 | Val acc: 46.41% | LR: 0.000025
Epoch: 013 | Train loss: 0.9983 | Train acc: 50.58% | Val loss: 1.0233 | Val acc: 45.95% | LR: 0.000025
Epoch: 014 | Train loss: 1.0010 | Train acc: 50.24% | Val loss: 1.0061 | Val acc: 46.07% | LR: 0.000025
Epoch: 015 | Train loss: 0.9991 | Train acc: 50.58% | Val loss: 1.0086 | Val acc: 45.99% | LR: 0.000025
Epoch: 016 | Train loss: 0.9979 | Train acc: 50.36% | Val loss: 1.0068 | Val acc: 45.79% | LR: 0.000025
Epoch: 017 | Train loss: 1.0044 | Train acc: 50.41% | Val loss: 1.0061 | Val acc: 45.86% | LR: 0.000025
Epoch: 018 | Train loss: 0.9978 | Train acc: 50.78% | Val loss: 1.0064 | Val acc: 45.85% | LR: 0.000025
Epoch: 019 | Train loss: 1.0016 | Train acc: 50.04% | Val loss: 1.0058 | Val acc: 46.01% | LR: 0.000024
Epoch: 020 | Train loss: 0.9982 | Train acc: 50.43% | Val loss: 1.0084 | Val acc: 46.06% | LR: 0.000024
Epoch: 021 | Train loss: 0.9992 | Train acc: 49.87% | Val loss: 1.0062 | Val acc: 46.17% | LR: 0.000024
Epoch: 022 | Train loss: 0.9952 | Train acc: 50.92% | Val loss: 1.0079 | Val acc: 46.22% | LR: 0.000024
Epoch: 023 | Train loss: 0.9969 | Train acc: 50.38% | Val loss: 1.0060 | Val acc: 45.97% | LR: 0.000024
Epoch: 024 | Train loss: 0.9956 | Train acc: 50.76% | Val loss: 1.0295 | Val acc: 45.99% | LR: 0.000024
Epoch: 025 | Train loss: 0.9953 | Train acc: 50.60% | Val loss: 1.0060 | Val acc: 45.97% | LR: 0.000024
Epoch: 026 | Train loss: 1.0032 | Train acc: 50.41% | Val loss: 1.0065 | Val acc: 45.92% | LR: 0.000024
Epoch: 027 | Train loss: 0.9949 | Train acc: 50.49% | Val loss: 1.0056 | Val acc: 46.08% | LR: 0.000023
Epoch: 028 | Train loss: 0.9936 | Train acc: 50.85% | Val loss: 1.0061 | Val acc: 45.99% | LR: 0.000023
Epoch: 029 | Train loss: 0.9919 | Train acc: 50.96% | Val loss: 1.0087 | Val acc: 45.94% | LR: 0.000023
Epoch: 030 | Train loss: 0.9921 | Train acc: 51.13% | Val loss: 1.0067 | Val acc: 45.86% | LR: 0.000023
Epoch: 031 | Train loss: 0.9960 | Train acc: 50.27% | Val loss: 1.0067 | Val acc: 45.87% | LR: 0.000023
Epoch: 032 | Train loss: 0.9922 | Train acc: 51.07% | Val loss: 1.0096 | Val acc: 46.02% | LR: 0.000023
Epoch: 033 | Train loss: 0.9938 | Train acc: 50.59% | Val loss: 1.0069 | Val acc: 45.89% | LR: 0.000023
Epoch: 034 | Train loss: 0.9926 | Train acc: 50.76% | Val loss: 1.0063 | Val acc: 46.01% | LR: 0.000022
Epoch: 035 | Train loss: 0.9975 | Train acc: 50.03% | Val loss: 1.0066 | Val acc: 46.13% | LR: 0.000022
Epoch: 036 | Train loss: 0.9935 | Train acc: 50.54% | Val loss: 1.0053 | Val acc: 46.13% | LR: 0.000022
Epoch: 037 | Train loss: 0.9925 | Train acc: 50.67% | Val loss: 1.0077 | Val acc: 45.99% | LR: 0.000022
Epoch: 038 | Train loss: 0.9901 | Train acc: 50.80% | Val loss: 1.0112 | Val acc: 45.97% | LR: 0.000022
Epoch: 039 | Train loss: 0.9955 | Train acc: 50.42% | Val loss: 1.0074 | Val acc: 46.07% | LR: 0.000021
Epoch: 040 | Train loss: 0.9951 | Train acc: 50.55% | Val loss: 1.0093 | Val acc: 45.91% | LR: 0.000021
Epoch: 041 | Train loss: 1.0471 | Train acc: 50.36% | Val loss: 1.0073 | Val acc: 45.89% | LR: 0.000021
Epoch: 042 | Train loss: 0.9925 | Train acc: 50.64% | Val loss: 1.0063 | Val acc: 45.95% | LR: 0.000021
Epoch: 043 | Train loss: 0.9956 | Train acc: 50.16% | Val loss: 1.0063 | Val acc: 45.95% | LR: 0.000021
Epoch: 044 | Train loss: 0.9947 | Train acc: 50.52% | Val loss: 1.0063 | Val acc: 45.95% | LR: 0.000020
Epoch: 045 | Train loss: 0.9896 | Train acc: 50.96% | Val loss: 1.0063 | Val acc: 45.95% | LR: 0.000020
Epoch: 046 | Train loss: 0.9965 | Train acc: 49.99% | Val loss: 1.0063 | Val acc: 45.95% | LR: 0.000020
Epoch: 047 | Train loss: 0.9884 | Train acc: 50.52% | Val loss: 1.0062 | Val acc: 45.95% | LR: 0.000020
Epoch: 048 | Train loss: 0.9945 | Train acc: 50.34% | Val loss: 1.0062 | Val acc: 45.95% | LR: 0.000020
Epoch: 049 | Train loss: 0.9969 | Train acc: 50.08% | Val loss: 1.0061 | Val acc: 45.95% | LR: 0.000019
Epoch: 050 | Train loss: 0.9933 | Train acc: 50.34% | Val loss: 1.0061 | Val acc: 45.95% | LR: 0.000019
Epoch: 051 | Train loss: 0.9911 | Train acc: 50.70% | Val loss: 1.0060 | Val acc: 45.95% | LR: 0.000019
Epoch: 052 | Train loss: 0.9969 | Train acc: 49.99% | Val loss: 1.0060 | Val acc: 45.95% | LR: 0.000019
Epoch: 053 | Train loss: 0.9904 | Train acc: 50.78% | Val loss: 1.0060 | Val acc: 45.95% | LR: 0.000018
Epoch: 054 | Train loss: 0.9899 | Train acc: 50.96% | Val loss: 1.0060 | Val acc: 45.95% | LR: 0.000018
Epoch: 055 | Train loss: 0.9935 | Train acc: 50.43% | Val loss: 1.0061 | Val acc: 45.95% | LR: 0.000018
Epoch: 056 | Train loss: 0.9896 | Train acc: 50.70% | Val loss: 1.0061 | Val acc: 45.95% | LR: 0.000018
Epoch: 057 | Train loss: 0.9901 | Train acc: 50.87% | Val loss: 1.0060 | Val acc: 45.95% | LR: 0.000018
Epoch: 058 | Train loss: 0.9889 | Train acc: 50.87% | Val loss: 1.0061 | Val acc: 45.95% | LR: 0.000017
Epoch: 059 | Train loss: 0.9910 | Train acc: 50.52% | Val loss: 1.0061 | Val acc: 45.95% | LR: 0.000017
Epoch: 060 | Train loss: 0.9956 | Train acc: 50.25% | Val loss: 1.0061 | Val acc: 45.95% | LR: 0.000017
Epoch: 061 | Train loss: 0.9927 | Train acc: 50.34% | Val loss: 1.0060 | Val acc: 45.95% | LR: 0.000017

[I 2025-09-23 16:09:26,213] Trial 2 finished with value: 0.45950507521629336 and parameters: {'lr': 2.5536888731721937e-05, 'hidden_size': 131, 'dropout': 0.4935475583216006, 'weight_decay': 0.001876405861063348}. Best is trial 1 with value: 0.4993742346763611.

Epoch: 000 | Train loss: 1.0012 | Train acc: 49.41% | Val loss: 0.9944 | Val acc: 54.15% | LR: 0.000030
Epoch: 001 | Train loss: 1.0010 | Train acc: 49.12% | Val loss: 0.9946 | Val acc: 54.09% | LR: 0.000030
Epoch: 002 | Train loss: 1.0002 | Train acc: 50.36% | Val loss: 0.9943 | Val acc: 54.15% | LR: 0.000030
Epoch: 003 | Train loss: 1.0006 | Train acc: 49.78% | Val loss: 0.9943 | Val acc: 54.17% | LR: 0.000030
Epoch: 004 | Train loss: 1.0008 | Train acc: 49.52% | Val loss: 0.9943 | Val acc: 54.26% | LR: 0.000030
Epoch: 005 | Train loss: 1.0002 | Train acc: 50.07% | Val loss: 0.9945 | Val acc: 54.31% | LR: 0.000030
Epoch: 006 | Train loss: 1.0006 | Train acc: 49.66% | Val loss: 0.9944 | Val acc: 54.37% | LR: 0.000030
Epoch: 007 | Train loss: 1.0004 | Train acc: 50.21% | Val loss: 0.9946 | Val acc: 54.43% | LR: 0.000030
Epoch: 008 | Train loss: 1.0003 | Train acc: 49.72% | Val loss: 0.9940 | Val acc: 54.39% | LR: 0.000030
Epoch: 009 | Train loss: 1.0008 | Train acc: 49.35% | Val loss: 0.9941 | Val acc: 54.45% | LR: 0.000030
Epoch: 010 | Train loss: 1.0005 | Train acc: 49.39% | Val loss: 0.9938 | Val acc: 54.55% | LR: 0.000030
Epoch: 011 | Train loss: 0.9999 | Train acc: 49.71% | Val loss: 0.9942 | Val acc: 54.57% | LR: 0.000030
Epoch: 012 | Train loss: 0.9991 | Train acc: 50.43% | Val loss: 0.9942 | Val acc: 54.60% | LR: 0.000030
Epoch: 013 | Train loss: 0.9996 | Train acc: 49.87% | Val loss: 0.9943 | Val acc: 54.43% | LR: 0.000030
Epoch: 014 | Train loss: 0.9998 | Train acc: 49.93% | Val loss: 0.9942 | Val acc: 54.45% | LR: 0.000030
Epoch: 015 | Train loss: 0.9992 | Train acc: 50.04% | Val loss: 0.9941 | Val acc: 54.50% | LR: 0.000030
Epoch: 016 | Train loss: 0.9992 | Train acc: 50.29% | Val loss: 0.9940 | Val acc: 54.26% | LR: 0.000030
Epoch: 017 | Train loss: 0.9984 | Train acc: 50.45% | Val loss: 0.9939 | Val acc: 54.18% | LR: 0.000029
Epoch: 018 | Train loss: 1.0001 | Train acc: 50.22% | Val loss: 0.9941 | Val acc: 54.26% | LR: 0.000029
Epoch: 019 | Train loss: 0.9995 | Train acc: 50.46% | Val loss: 0.9937 | Val acc: 54.12% | LR: 0.000029
Epoch: 020 | Train loss: 0.9989 | Train acc: 50.62% | Val loss: 0.9938 | Val acc: 54.10% | LR: 0.000029
Epoch: 021 | Train loss: 0.9989 | Train acc: 50.39% | Val loss: 0.9935 | Val acc: 54.14% | LR: 0.000029
Epoch: 022 | Train loss: 0.9987 | Train acc: 50.69% | Val loss: 0.9938 | Val acc: 54.00% | LR: 0.000029
Epoch: 023 | Train loss: 0.9982 | Train acc: 50.69% | Val loss: 0.9938 | Val acc: 54.12% | LR: 0.000029
Epoch: 024 | Train loss: 0.9982 | Train acc: 50.63% | Val loss: 0.9936 | Val acc: 54.12% | LR: 0.000028
Epoch: 025 | Train loss: 0.9956 | Train acc: 51.18% | Val loss: 0.9937 | Val acc: 54.14% | LR: 0.000028
Epoch: 026 | Train loss: 0.9955 | Train acc: 51.07% | Val loss: 0.9938 | Val acc: 54.14% | LR: 0.000028
Epoch: 027 | Train loss: 0.9959 | Train acc: 51.16% | Val loss: 0.9937 | Val acc: 54.22% | LR: 0.000028
Epoch: 028 | Train loss: 0.9969 | Train acc: 50.82% | Val loss: 0.9937 | Val acc: 54.20% | LR: 0.000028
Epoch: 029 | Train loss: 0.9978 | Train acc: 50.55% | Val loss: 0.9937 | Val acc: 54.12% | LR: 0.000028
Epoch: 030 | Train loss: 0.9969 | Train acc: 50.70% | Val loss: 0.9938 | Val acc: 54.10% | LR: 0.000027
Epoch: 031 | Train loss: 0.9940 | Train acc: 51.09% | Val loss: 0.9937 | Val acc: 54.16% | LR: 0.000027
Epoch: 032 | Train loss: 0.9965 | Train acc: 50.57% | Val loss: 0.9937 | Val acc: 54.16% | LR: 0.000027
Epoch: 033 | Train loss: 0.9983 | Train acc: 50.60% | Val loss: 0.9938 | Val acc: 54.18% | LR: 0.000027
Epoch: 034 | Train loss: 0.9957 | Train acc: 50.88% | Val loss: 0.9936 | Val acc: 54.28% | LR: 0.000027
Epoch: 035 | Train loss: 0.9953 | Train acc: 50.99% | Val loss: 0.9937 | Val acc: 54.53% | LR: 0.000026
Epoch: 036 | Train loss: 1.0000 | Train acc: 50.10% | Val loss: 0.9936 | Val acc: 54.49% | LR: 0.000026
Epoch: 037 | Train loss: 0.9993 | Train acc: 50.09% | Val loss: 0.9936 | Val acc: 54.48% | LR: 0.000026
Epoch: 038 | Train loss: 0.9955 | Train acc: 50.71% | Val loss: 0.9936 | Val acc: 54.40% | LR: 0.000026
Epoch: 039 | Train loss: 0.9942 | Train acc: 50.97% | Val loss: 0.9936 | Val acc: 54.50% | LR: 0.000026
Epoch: 040 | Train loss: 0.9958 | Train acc: 50.69% | Val loss: 0.9936 | Val acc: 54.49% | LR: 0.000025
Epoch: 041 | Train loss: 0.9986 | Train acc: 50.32% | Val loss: 0.9936 | Val acc: 54.57% | LR: 0.000025
Epoch: 042 | Train loss: 0.9960 | Train acc: 50.56% | Val loss: 0.9937 | Val acc: 54.65% | LR: 0.000025
Epoch: 043 | Train loss: 0.9995 | Train acc: 50.28% | Val loss: 0.9936 | Val acc: 54.83% | LR: 0.000025
Epoch: 044 | Train loss: 0.9979 | Train acc: 50.36% | Val loss: 0.9936 | Val acc: 54.88% | LR: 0.000024
Epoch: 045 | Train loss: 0.9983 | Train acc: 50.25% | Val loss: 0.9936 | Val acc: 54.86% | LR: 0.000024
Epoch: 046 | Train loss: 0.9961 | Train acc: 50.63% | Val loss: 0.9935 | Val acc: 54.81% | LR: 0.000024
Epoch: 047 | Train loss: 0.9967 | Train acc: 50.36% | Val loss: 0.9935 | Val acc: 54.83% | LR: 0.000024
Epoch: 048 | Train loss: 1.0007 | Train acc: 50.01% | Val loss: 0.9936 | Val acc: 54.77% | LR: 0.000023
Epoch: 049 | Train loss: 0.9965 | Train acc: 50.64% | Val loss: 0.9936 | Val acc: 54.77% | LR: 0.000023
Epoch: 050 | Train loss: 0.9939 | Train acc: 50.91% | Val loss: 0.9935 | Val acc: 54.71% | LR: 0.000023
Epoch: 051 | Train loss: 0.9923 | Train acc: 51.21% | Val loss: 0.9935 | Val acc: 54.61% | LR: 0.000023
Epoch: 052 | Train loss: 0.9952 | Train acc: 50.67% | Val loss: 0.9934 | Val acc: 54.63% | LR: 0.000022
Epoch: 053 | Train loss: 0.9943 | Train acc: 50.85% | Val loss: 0.9933 | Val acc: 54.57% | LR: 0.000022
Epoch: 054 | Train loss: 0.9945 | Train acc: 50.67% | Val loss: 0.9933 | Val acc: 54.57% | LR: 0.000022
Epoch: 055 | Train loss: 0.9976 | Train acc: 50.49% | Val loss: 0.9931 | Val acc: 54.61% | LR: 0.000021
Epoch: 056 | Train loss: 0.9958 | Train acc: 50.67% | Val loss: 0.9930 | Val acc: 54.61% | LR: 0.000021
Epoch: 057 | Train loss: 0.9968 | Train acc: 50.51% | Val loss: 0.9933 | Val acc: 54.57% | LR: 0.000021
Epoch: 058 | Train loss: 0.9945 | Train acc: 50.67% | Val loss: 0.9930 | Val acc: 54.55% | LR: 0.000021
Epoch: 059 | Train loss: 0.9900 | Train acc: 51.21% | Val loss: 0.9930 | Val acc: 54.63% | LR: 0.000020
Epoch: 060 | Train loss: 0.9923 | Train acc: 50.83% | Val loss: 0.9931 | Val acc: 54.61% | LR: 0.000020
Epoch: 061 | Train loss: 0.9956 | Train acc: 50.66% | Val loss: 0.9931 | Val acc: 54.69% | LR: 0.000020
Epoch: 062 | Train loss: 0.9953 | Train acc: 50.59% | Val loss: 0.9930 | Val acc: 54.61% | LR: 0.000019
Epoch: 063 | Train loss: 0.9939 | Train acc: 50.70% | Val loss: 0.9930 | Val acc: 54.37% | LR: 0.000019
Epoch: 064 | Train loss: 0.9905 | Train acc: 51.06% | Val loss: 0.9928 | Val acc: 54.38% | LR: 0.000019
Epoch: 065 | Train loss: 0.9920 | Train acc: 50.87% | Val loss: 0.9928 | Val acc: 54.38% | LR: 0.000018
Epoch: 066 | Train loss: 0.9930 | Train acc: 50.90% | Val loss: 0.9928 | Val acc: 54.26% | LR: 0.000018
Epoch: 067 | Train loss: 0.9952 | Train acc: 50.72% | Val loss: 0.9928 | Val acc: 54.15% | LR: 0.000018
Epoch: 068 | Train loss: 0.9925 | Train acc: 50.83% | Val loss: 0.9927 | Val acc: 54.18% | LR: 0.000018
Epoch: 069 | Train loss: 0.9903 | Train acc: 51.19% | Val loss: 0.9927 | Val acc: 54.18% | LR: 0.000017
Epoch: 070 | Train loss: 0.9891 | Train acc: 51.19% | Val loss: 1.0215 | Val acc: 54.06% | LR: 0.000017
Epoch: 071 | Train loss: 0.9911 | Train acc: 50.91% | Val loss: 0.9927 | Val acc: 54.08% | LR: 0.000017
Epoch: 072 | Train loss: 0.9924 | Train acc: 50.93% | Val loss: 0.9925 | Val acc: 54.03% | LR: 0.000016
Epoch: 073 | Train loss: 0.9850 | Train acc: 51.64% | Val loss: 0.9923 | Val acc: 53.87% | LR: 0.000016
Epoch: 074 | Train loss: 0.9914 | Train acc: 50.95% | Val loss: 0.9920 | Val acc: 53.85% | LR: 0.000016
Epoch: 075 | Train loss: 0.9933 | Train acc: 50.77% | Val loss: 0.9919 | Val acc: 53.85% | LR: 0.000015
Epoch: 076 | Train loss: 0.9900 | Train acc: 51.05% | Val loss: 0.9916 | Val acc: 53.82% | LR: 0.000015
Epoch: 077 | Train loss: 0.9888 | Train acc: 51.22% | Val loss: 0.9923 | Val acc: 53.70% | LR: 0.000015
Epoch: 078 | Train loss: 0.9883 | Train acc: 50.94% | Val loss: 0.9920 | Val acc: 53.74% | LR: 0.000014
Epoch: 079 | Train loss: 0.9925 | Train acc: 50.78% | Val loss: 0.9922 | Val acc: 53.64% | LR: 0.000014
Epoch: 080 | Train loss: 0.9896 | Train acc: 51.04% | Val loss: 0.9922 | Val acc: 53.66% | LR: 0.000014
Epoch: 081 | Train loss: 0.9912 | Train acc: 50.87% | Val loss: 0.9922 | Val acc: 53.66% | LR: 0.000014
Epoch: 082 | Train loss: 0.9944 | Train acc: 50.71% | Val loss: 0.9922 | Val acc: 53.62% | LR: 0.000013
Epoch: 083 | Train loss: 0.9932 | Train acc: 50.80% | Val loss: 0.9927 | Val acc: 53.60% | LR: 0.000013
Epoch: 084 | Train loss: 0.9902 | Train acc: 50.88% | Val loss: 0.9921 | Val acc: 53.64% | LR: 0.000013
Epoch: 085 | Train loss: 0.9910 | Train acc: 51.07% | Val loss: 0.9916 | Val acc: 53.64% | LR: 0.000012
Epoch: 086 | Train loss: 0.9880 | Train acc: 51.16% | Val loss: 0.9920 | Val acc: 53.68% | LR: 0.000012
Epoch: 087 | Train loss: 0.9905 | Train acc: 50.88% | Val loss: 0.9920 | Val acc: 53.70% | LR: 0.000012
Epoch: 088 | Train loss: 0.9896 | Train acc: 51.08% | Val loss: 0.9919 | Val acc: 53.58% | LR: 0.000011
Epoch: 089 | Train loss: 0.9960 | Train acc: 50.65% | Val loss: 0.9922 | Val acc: 53.50% | LR: 0.000011
Epoch: 090 | Train loss: 0.9937 | Train acc: 50.65% | Val loss: 0.9920 | Val acc: 53.60% | LR: 0.000011
Epoch: 091 | Train loss: 0.9895 | Train acc: 51.10% | Val loss: 0.9920 | Val acc: 53.48% | LR: 0.000011
Epoch: 092 | Train loss: 0.9922 | Train acc: 51.00% | Val loss: 0.9931 | Val acc: 53.50% | LR: 0.000010
Epoch: 093 | Train loss: 0.9913 | Train acc: 51.09% | Val loss: 0.9926 | Val acc: 53.54% | LR: 0.000010

[I 2025-09-23 16:10:42,719] Trial 3 finished with value: 0.5359836459159851 and parameters: {'lr': 3.0438745694947877e-05, 'hidden_size': 74, 'dropout': 0.3753476307527941, 'weight_decay': 1.6974221990669463e-06}. Best is trial 3 with value: 0.5359836459159851.

Epoch: 000 | Train loss: 1.0013 | Train acc: 50.64% | Val loss: 1.0026 | Val acc: 47.05% | LR: 0.000324
Epoch: 001 | Train loss: 0.9925 | Train acc: 50.93% | Val loss: 1.0017 | Val acc: 48.43% | LR: 0.000324
Epoch: 002 | Train loss: 0.9920 | Train acc: 50.71% | Val loss: 1.0102 | Val acc: 47.52% | LR: 0.000324
Epoch: 003 | Train loss: 0.9845 | Train acc: 51.18% | Val loss: 1.0034 | Val acc: 49.24% | LR: 0.000324
Epoch: 004 | Train loss: 0.9865 | Train acc: 50.74% | Val loss: 1.0005 | Val acc: 49.65% | LR: 0.000324
Epoch: 005 | Train loss: 0.9844 | Train acc: 51.04% | Val loss: 1.0174 | Val acc: 49.06% | LR: 0.000323
Epoch: 006 | Train loss: 0.9826 | Train acc: 51.35% | Val loss: 1.0221 | Val acc: 47.82% | LR: 0.000323
Epoch: 007 | Train loss: 0.9867 | Train acc: 50.89% | Val loss: 1.0108 | Val acc: 48.68% | LR: 0.000322
Epoch: 008 | Train loss: 0.9815 | Train acc: 51.03% | Val loss: 1.0171 | Val acc: 48.86% | LR: 0.000322
Epoch: 009 | Train loss: 0.9787 | Train acc: 51.24% | Val loss: 1.0241 | Val acc: 48.60% | LR: 0.000321
Epoch: 010 | Train loss: 0.9835 | Train acc: 50.89% | Val loss: 1.0227 | Val acc: 47.74% | LR: 0.000320
Epoch: 011 | Train loss: 0.9827 | Train acc: 50.86% | Val loss: 1.0156 | Val acc: 48.87% | LR: 0.000319
Epoch: 012 | Train loss: 0.9855 | Train acc: 50.88% | Val loss: 0.9881 | Val acc: 50.12% | LR: 0.000319
Epoch: 013 | Train loss: 0.9801 | Train acc: 51.36% | Val loss: 0.9964 | Val acc: 49.96% | LR: 0.000318
Epoch: 014 | Train loss: 0.9790 | Train acc: 51.30% | Val loss: 1.0027 | Val acc: 49.69% | LR: 0.000317
Epoch: 015 | Train loss: 0.9799 | Train acc: 51.16% | Val loss: 0.9971 | Val acc: 49.80% | LR: 0.000316
Epoch: 016 | Train loss: 0.9708 | Train acc: 51.59% | Val loss: 1.0144 | Val acc: 49.52% | LR: 0.000314
Epoch: 017 | Train loss: 0.9756 | Train acc: 51.41% | Val loss: 1.0158 | Val acc: 48.69% | LR: 0.000313
Epoch: 018 | Train loss: 0.9764 | Train acc: 51.21% | Val loss: 0.9986 | Val acc: 49.70% | LR: 0.000312
Epoch: 019 | Train loss: 0.9826 | Train acc: 51.00% | Val loss: 1.0153 | Val acc: 48.89% | LR: 0.000311
Epoch: 020 | Train loss: 0.9757 | Train acc: 51.32% | Val loss: 1.0125 | Val acc: 49.06% | LR: 0.000309
Epoch: 021 | Train loss: 0.9831 | Train acc: 51.02% | Val loss: 0.9999 | Val acc: 49.87% | LR: 0.000308
Epoch: 022 | Train loss: 0.9787 | Train acc: 51.38% | Val loss: 1.0035 | Val acc: 49.92% | LR: 0.000306
Epoch: 023 | Train loss: 0.9863 | Train acc: 50.81% | Val loss: 1.0168 | Val acc: 49.18% | LR: 0.000305
Epoch: 024 | Train loss: 0.9804 | Train acc: 51.05% | Val loss: 1.0405 | Val acc: 47.98% | LR: 0.000303
Epoch: 025 | Train loss: 0.9721 | Train acc: 51.56% | Val loss: 1.0389 | Val acc: 48.06% | LR: 0.000301
Epoch: 026 | Train loss: 0.9847 | Train acc: 50.81% | Val loss: 1.0249 | Val acc: 48.47% | LR: 0.000299
Epoch: 027 | Train loss: 0.9800 | Train acc: 51.13% | Val loss: 1.0164 | Val acc: 48.99% | LR: 0.000297
Epoch: 028 | Train loss: 0.9723 | Train acc: 51.48% | Val loss: 1.0472 | Val acc: 47.37% | LR: 0.000296
Epoch: 029 | Train loss: 0.9848 | Train acc: 50.86% | Val loss: 1.0501 | Val acc: 46.96% | LR: 0.000294
Epoch: 030 | Train loss: 0.9729 | Train acc: 51.47% | Val loss: 1.0264 | Val acc: 48.87% | LR: 0.000292
Epoch: 031 | Train loss: 0.9756 | Train acc: 51.27% | Val loss: 0.9897 | Val acc: 50.52% | LR: 0.000290
Epoch: 032 | Train loss: 0.9765 | Train acc: 51.29% | Val loss: 0.9830 | Val acc: 50.72% | LR: 0.000287
Epoch: 033 | Train loss: 0.9888 | Train acc: 50.60% | Val loss: 1.0378 | Val acc: 48.04% | LR: 0.000285
Epoch: 034 | Train loss: 0.9748 | Train acc: 51.37% | Val loss: 1.0218 | Val acc: 49.22% | LR: 0.000283
Epoch: 035 | Train loss: 0.9848 | Train acc: 50.77% | Val loss: 1.0536 | Val acc: 47.09% | LR: 0.000281
Epoch: 036 | Train loss: 0.9791 | Train acc: 51.11% | Val loss: 1.0258 | Val acc: 48.75% | LR: 0.000278
Epoch: 037 | Train loss: 0.9670 | Train acc: 51.83% | Val loss: 1.0190 | Val acc: 49.17% | LR: 0.000276
Epoch: 038 | Train loss: 0.9699 | Train acc: 51.65% | Val loss: 1.0393 | Val acc: 48.14% | LR: 0.000273
Epoch: 039 | Train loss: 0.9815 | Train acc: 50.96% | Val loss: 1.0679 | Val acc: 46.40% | LR: 0.000271
Epoch: 040 | Train loss: 0.9776 | Train acc: 51.20% | Val loss: 1.0333 | Val acc: 48.24% | LR: 0.000268
Epoch: 041 | Train loss: 0.9772 | Train acc: 51.16% | Val loss: 1.0372 | Val acc: 48.23% | LR: 0.000266
Epoch: 042 | Train loss: 0.9825 | Train acc: 50.95% | Val loss: 1.0440 | Val acc: 47.69% | LR: 0.000263
Epoch: 043 | Train loss: 0.9716 | Train acc: 51.55% | Val loss: 1.0354 | Val acc: 48.10% | LR: 0.000261
Epoch: 044 | Train loss: 0.9853 | Train acc: 50.69% | Val loss: 1.0077 | Val acc: 49.83% | LR: 0.000258
Epoch: 045 | Train loss: 0.9760 | Train acc: 51.50% | Val loss: 1.0345 | Val acc: 48.33% | LR: 0.000255
Epoch: 046 | Train loss: 0.9814 | Train acc: 50.93% | Val loss: 1.0371 | Val acc: 48.10% | LR: 0.000252
Epoch: 047 | Train loss: 0.9830 | Train acc: 50.83% | Val loss: 1.0515 | Val acc: 47.39% | LR: 0.000249
Epoch: 048 | Train loss: 0.9866 | Train acc: 50.55% | Val loss: 1.0340 | Val acc: 48.17% | LR: 0.000247
Epoch: 049 | Train loss: 0.9789 | Train acc: 51.17% | Val loss: 1.0391 | Val acc: 48.19% | LR: 0.000244
Epoch: 050 | Train loss: 0.9808 | Train acc: 51.05% | Val loss: 1.0416 | Val acc: 47.65% | LR: 0.000241
Epoch: 051 | Train loss: 0.9825 | Train acc: 50.83% | Val loss: 1.0375 | Val acc: 48.17% | LR: 0.000238
Epoch: 052 | Train loss: 0.9674 | Train acc: 51.81% | Val loss: 1.0469 | Val acc: 47.56% | LR: 0.000235
Epoch: 053 | Train loss: 0.9847 | Train acc: 50.76% | Val loss: 1.0552 | Val acc: 47.00% | LR: 0.000232
Epoch: 054 | Train loss: 0.9855 | Train acc: 50.81% | Val loss: 1.0372 | Val acc: 48.03% | LR: 0.000229
Epoch: 055 | Train loss: 0.9831 | Train acc: 50.94% | Val loss: 1.0494 | Val acc: 47.12% | LR: 0.000225
Epoch: 056 | Train loss: 0.9838 | Train acc: 50.79% | Val loss: 1.0365 | Val acc: 48.16% | LR: 0.000222
Epoch: 057 | Train loss: 0.9721 | Train acc: 51.50% | Val loss: 1.0221 | Val acc: 48.89% | LR: 0.000219
Epoch: 058 | Train loss: 0.9793 | Train acc: 50.97% | Val loss: 1.0090 | Val acc: 49.62% | LR: 0.000216
Epoch: 059 | Train loss: 0.9775 | Train acc: 51.25% | Val loss: 1.0112 | Val acc: 49.64% | LR: 0.000213
Epoch: 060 | Train loss: 0.9726 | Train acc: 51.49% | Val loss: 1.0026 | Val acc: 49.85% | LR: 0.000210
Epoch: 061 | Train loss: 0.9859 | Train acc: 50.62% | Val loss: 1.0257 | Val acc: 48.60% | LR: 0.000206
Epoch: 062 | Train loss: 0.9820 | Train acc: 50.81% | Val loss: 1.0337 | Val acc: 48.37% | LR: 0.000203
Epoch: 063 | Train loss: 0.9884 | Train acc: 50.45% | Val loss: 1.0391 | Val acc: 47.95% | LR: 0.000200
Epoch: 064 | Train loss: 0.9746 | Train acc: 51.37% | Val loss: 1.0407 | Val acc: 47.96% | LR: 0.000196
Epoch: 065 | Train loss: 0.9651 | Train acc: 51.91% | Val loss: 1.0561 | Val acc: 47.18% | LR: 0.000193
Epoch: 066 | Train loss: 0.9829 | Train acc: 50.81% | Val loss: 1.0504 | Val acc: 47.80% | LR: 0.000190
Epoch: 067 | Train loss: 0.9762 | Train acc: 51.28% | Val loss: 1.0399 | Val acc: 48.02% | LR: 0.000186
Epoch: 068 | Train loss: 0.9811 | Train acc: 50.96% | Val loss: 1.0429 | Val acc: 47.78% | LR: 0.000183
Epoch: 069 | Train loss: 0.9750 | Train acc: 51.27% | Val loss: 1.0496 | Val acc: 47.40% | LR: 0.000180
Epoch: 070 | Train loss: 0.9786 | Train acc: 51.09% | Val loss: 1.0607 | Val acc: 46.69% | LR: 0.000176
Epoch: 071 | Train loss: 0.9814 | Train acc: 50.87% | Val loss: 1.0549 | Val acc: 47.04% | LR: 0.000173
Epoch: 072 | Train loss: 0.9805 | Train acc: 50.86% | Val loss: 1.0451 | Val acc: 47.82% | LR: 0.000170
Epoch: 073 | Train loss: 0.9719 | Train acc: 51.56% | Val loss: 1.0517 | Val acc: 47.46% | LR: 0.000166
Epoch: 074 | Train loss: 0.9749 | Train acc: 51.34% | Val loss: 1.0653 | Val acc: 46.50% | LR: 0.000163
Epoch: 075 | Train loss: 0.9779 | Train acc: 51.19% | Val loss: 1.0281 | Val acc: 48.65% | LR: 0.000159
Epoch: 076 | Train loss: 0.9717 | Train acc: 51.57% | Val loss: 1.0484 | Val acc: 47.56% | LR: 0.000156
Epoch: 077 | Train loss: 0.9799 | Train acc: 51.03% | Val loss: 1.0362 | Val acc: 48.06% | LR: 0.000153
Epoch: 078 | Train loss: 0.9812 | Train acc: 51.02% | Val loss: 1.0049 | Val acc: 49.58% | LR: 0.000149
Epoch: 079 | Train loss: 0.9631 | Train acc: 51.95% | Val loss: 1.0369 | Val acc: 48.08% | LR: 0.000146
Epoch: 080 | Train loss: 0.9674 | Train acc: 51.79% | Val loss: 1.0545 | Val acc: 47.30% | LR: 0.000142
Epoch: 081 | Train loss: 0.9692 | Train acc: 51.60% | Val loss: 1.0630 | Val acc: 46.88% | LR: 0.000139

[I 2025-09-23 16:11:57,260] Trial 4 finished with value: 0.4810886323451996 and parameters: {'lr': 0.0003245227356926155, 'hidden_size': 214, 'dropout': 0.12459351972542164, 'weight_decay': 0.000525771976242492}. Best is trial 3 with value: 0.5359836459159851.

Epoch: 000 | Train loss: 1.0002 | Train acc: 50.07% | Val loss: 0.9916 | Val acc: 54.13% | LR: 0.000044
Epoch: 001 | Train loss: 1.0006 | Train acc: 49.72% | Val loss: 0.9913 | Val acc: 54.17% | LR: 0.000044
Epoch: 002 | Train loss: 1.0001 | Train acc: 49.54% | Val loss: 0.9914 | Val acc: 54.20% | LR: 0.000044
Epoch: 003 | Train loss: 1.0000 | Train acc: 49.84% | Val loss: 0.9916 | Val acc: 54.30% | LR: 0.000044
Epoch: 004 | Train loss: 1.0002 | Train acc: 49.94% | Val loss: 0.9917 | Val acc: 54.28% | LR: 0.000044
Epoch: 005 | Train loss: 0.9975 | Train acc: 50.84% | Val loss: 0.9917 | Val acc: 54.44% | LR: 0.000044
Epoch: 006 | Train loss: 0.9985 | Train acc: 50.51% | Val loss: 0.9918 | Val acc: 54.33% | LR: 0.000044
Epoch: 007 | Train loss: 0.9991 | Train acc: 49.96% | Val loss: 0.9919 | Val acc: 54.49% | LR: 0.000044
Epoch: 008 | Train loss: 0.9990 | Train acc: 50.06% | Val loss: 0.9923 | Val acc: 54.46% | LR: 0.000044
Epoch: 009 | Train loss: 0.9975 | Train acc: 50.76% | Val loss: 0.9924 | Val acc: 54.39% | LR: 0.000043
Epoch: 010 | Train loss: 0.9969 | Train acc: 50.94% | Val loss: 0.9925 | Val acc: 54.44% | LR: 0.000043
Epoch: 011 | Train loss: 0.9964 | Train acc: 51.08% | Val loss: 0.9921 | Val acc: 54.46% | LR: 0.000043
Epoch: 012 | Train loss: 0.9977 | Train acc: 51.18% | Val loss: 0.9921 | Val acc: 54.30% | LR: 0.000043
Epoch: 013 | Train loss: 0.9957 | Train acc: 50.74% | Val loss: 0.9918 | Val acc: 54.54% | LR: 0.000043
Epoch: 014 | Train loss: 0.9977 | Train acc: 50.40% | Val loss: 0.9922 | Val acc: 54.44% | LR: 0.000043
Epoch: 015 | Train loss: 0.9972 | Train acc: 50.94% | Val loss: 0.9917 | Val acc: 54.40% | LR: 0.000043
Epoch: 016 | Train loss: 0.9974 | Train acc: 50.55% | Val loss: 1.0152 | Val acc: 54.50% | LR: 0.000043
Epoch: 017 | Train loss: 0.9955 | Train acc: 51.19% | Val loss: 0.9947 | Val acc: 54.10% | LR: 0.000042
Epoch: 018 | Train loss: 0.9947 | Train acc: 51.18% | Val loss: 0.9921 | Val acc: 54.29% | LR: 0.000042
Epoch: 019 | Train loss: 0.9975 | Train acc: 50.61% | Val loss: 0.9924 | Val acc: 54.02% | LR: 0.000042
Epoch: 020 | Train loss: 0.9976 | Train acc: 50.55% | Val loss: 0.9961 | Val acc: 54.06% | LR: 0.000042
Epoch: 021 | Train loss: 0.9949 | Train acc: 50.86% | Val loss: 0.9919 | Val acc: 54.06% | LR: 0.000042
Epoch: 022 | Train loss: 0.9986 | Train acc: 50.33% | Val loss: 1.1154 | Val acc: 53.93% | LR: 0.000042
Epoch: 023 | Train loss: 0.9956 | Train acc: 50.87% | Val loss: 0.9918 | Val acc: 53.83% | LR: 0.000041
Epoch: 024 | Train loss: 0.9949 | Train acc: 51.08% | Val loss: 0.9917 | Val acc: 53.44% | LR: 0.000041
Epoch: 025 | Train loss: 0.9943 | Train acc: 51.25% | Val loss: 0.9916 | Val acc: 53.44% | LR: 0.000041
Epoch: 026 | Train loss: 0.9940 | Train acc: 51.05% | Val loss: 0.9913 | Val acc: 53.24% | LR: 0.000041
Epoch: 027 | Train loss: 0.9955 | Train acc: 50.62% | Val loss: 0.9949 | Val acc: 53.13% | LR: 0.000040
Epoch: 028 | Train loss: 0.9957 | Train acc: 50.64% | Val loss: 0.9917 | Val acc: 53.18% | LR: 0.000040
Epoch: 029 | Train loss: 0.9927 | Train acc: 51.28% | Val loss: 0.9913 | Val acc: 53.08% | LR: 0.000040
Epoch: 030 | Train loss: 0.9969 | Train acc: 50.68% | Val loss: 0.9926 | Val acc: 53.01% | LR: 0.000040
Epoch: 031 | Train loss: 0.9984 | Train acc: 50.47% | Val loss: 0.9912 | Val acc: 53.06% | LR: 0.000039
Epoch: 032 | Train loss: 0.9917 | Train acc: 50.88% | Val loss: 0.9912 | Val acc: 53.02% | LR: 0.000039
Epoch: 033 | Train loss: 0.9960 | Train acc: 51.04% | Val loss: 0.9905 | Val acc: 53.10% | LR: 0.000039
Epoch: 034 | Train loss: 0.9951 | Train acc: 51.08% | Val loss: 0.9907 | Val acc: 52.80% | LR: 0.000038
Epoch: 035 | Train loss: 0.9955 | Train acc: 50.68% | Val loss: 0.9907 | Val acc: 52.84% | LR: 0.000038
Epoch: 036 | Train loss: 0.9931 | Train acc: 51.00% | Val loss: 0.9914 | Val acc: 52.90% | LR: 0.000038
Epoch: 037 | Train loss: 1.0642 | Train acc: 51.00% | Val loss: 0.9907 | Val acc: 52.95% | LR: 0.000038
Epoch: 038 | Train loss: 1.0100 | Train acc: 50.76% | Val loss: 0.9917 | Val acc: 52.92% | LR: 0.000037
Epoch: 039 | Train loss: 0.9912 | Train acc: 51.12% | Val loss: 0.9916 | Val acc: 52.92% | LR: 0.000037
Epoch: 040 | Train loss: 0.9935 | Train acc: 50.81% | Val loss: 0.9922 | Val acc: 52.95% | LR: 0.000037
Epoch: 041 | Train loss: 0.9943 | Train acc: 50.72% | Val loss: 0.9911 | Val acc: 52.97% | LR: 0.000036
Epoch: 042 | Train loss: 0.9936 | Train acc: 50.80% | Val loss: 0.9901 | Val acc: 52.96% | LR: 0.000036
Epoch: 043 | Train loss: 0.9948 | Train acc: 50.59% | Val loss: 0.9910 | Val acc: 52.87% | LR: 0.000035
Epoch: 044 | Train loss: 0.9944 | Train acc: 50.86% | Val loss: 0.9904 | Val acc: 52.87% | LR: 0.000035
Epoch: 045 | Train loss: 0.9917 | Train acc: 51.02% | Val loss: 0.9913 | Val acc: 52.77% | LR: 0.000035
Epoch: 046 | Train loss: 0.9917 | Train acc: 50.83% | Val loss: 0.9903 | Val acc: 52.71% | LR: 0.000034
Epoch: 047 | Train loss: 1.0010 | Train acc: 51.20% | Val loss: 0.9903 | Val acc: 52.80% | LR: 0.000034
Epoch: 048 | Train loss: 0.9942 | Train acc: 50.76% | Val loss: 0.9903 | Val acc: 52.80% | LR: 0.000034
Epoch: 049 | Train loss: 0.9948 | Train acc: 50.55% | Val loss: 0.9902 | Val acc: 52.84% | LR: 0.000033
Epoch: 050 | Train loss: 0.9962 | Train acc: 50.41% | Val loss: 0.9903 | Val acc: 52.76% | LR: 0.000033
Epoch: 051 | Train loss: 0.9902 | Train acc: 51.12% | Val loss: 0.9901 | Val acc: 52.68% | LR: 0.000032
Epoch: 052 | Train loss: 0.9983 | Train acc: 50.14% | Val loss: 0.9980 | Val acc: 52.58% | LR: 0.000032
Epoch: 053 | Train loss: 1.0015 | Train acc: 51.03% | Val loss: 0.9904 | Val acc: 52.56% | LR: 0.000032
Epoch: 054 | Train loss: 0.9904 | Train acc: 51.06% | Val loss: 0.9905 | Val acc: 52.42% | LR: 0.000031
Epoch: 055 | Train loss: 0.9913 | Train acc: 50.81% | Val loss: 0.9907 | Val acc: 52.42% | LR: 0.000031
Epoch: 056 | Train loss: 0.9919 | Train acc: 50.72% | Val loss: 0.9895 | Val acc: 52.50% | LR: 0.000030
Epoch: 057 | Train loss: 0.9904 | Train acc: 51.16% | Val loss: 0.9895 | Val acc: 52.51% | LR: 0.000030
Epoch: 058 | Train loss: 0.9934 | Train acc: 50.55% | Val loss: 0.9896 | Val acc: 52.51% | LR: 0.000030
Epoch: 059 | Train loss: 0.9922 | Train acc: 50.74% | Val loss: 0.9892 | Val acc: 52.51% | LR: 0.000029
Epoch: 060 | Train loss: 0.9902 | Train acc: 51.09% | Val loss: 0.9892 | Val acc: 52.35% | LR: 0.000029
Epoch: 061 | Train loss: 0.9855 | Train acc: 51.61% | Val loss: 0.9893 | Val acc: 52.35% | LR: 0.000028
Epoch: 062 | Train loss: 0.9862 | Train acc: 51.32% | Val loss: 0.9885 | Val acc: 52.40% | LR: 0.000028

[I 2025-09-23 16:12:48,766] Trial 5 finished with value: 0.5222479462623596 and parameters: {'lr': 4.396027076941514e-05, 'hidden_size': 64, 'dropout': 0.11299774075574964, 'weight_decay': 0.00014568764082441404}. Best is trial 3 with value: 0.5359836459159851.

Epoch: 000 | Train loss: 0.9972 | Train acc: 50.32% | Val loss: 0.9983 | Val acc: 53.02% | LR: 0.000012
Epoch: 001 | Train loss: 0.9979 | Train acc: 50.14% | Val loss: 0.9980 | Val acc: 52.90% | LR: 0.000012
Epoch: 002 | Train loss: 0.9970 | Train acc: 50.16% | Val loss: 0.9983 | Val acc: 53.08% | LR: 0.000012
Epoch: 003 | Train loss: 0.9981 | Train acc: 50.20% | Val loss: 0.9981 | Val acc: 53.02% | LR: 0.000012
Epoch: 004 | Train loss: 0.9947 | Train acc: 50.89% | Val loss: 0.9980 | Val acc: 53.15% | LR: 0.000012
Epoch: 005 | Train loss: 0.9978 | Train acc: 50.13% | Val loss: 0.9982 | Val acc: 53.26% | LR: 0.000012
Epoch: 006 | Train loss: 0.9950 | Train acc: 50.66% | Val loss: 0.9981 | Val acc: 53.14% | LR: 0.000012
Epoch: 007 | Train loss: 0.9940 | Train acc: 50.78% | Val loss: 0.9980 | Val acc: 53.23% | LR: 0.000012
Epoch: 008 | Train loss: 0.9963 | Train acc: 50.67% | Val loss: 0.9979 | Val acc: 53.36% | LR: 0.000012
Epoch: 009 | Train loss: 0.9950 | Train acc: 50.58% | Val loss: 0.9978 | Val acc: 53.32% | LR: 0.000012
Epoch: 010 | Train loss: 0.9950 | Train acc: 50.84% | Val loss: 0.9976 | Val acc: 53.38% | LR: 0.000012
Epoch: 011 | Train loss: 0.9950 | Train acc: 50.83% | Val loss: 0.9975 | Val acc: 53.44% | LR: 0.000012
Epoch: 012 | Train loss: 0.9974 | Train acc: 50.51% | Val loss: 0.9971 | Val acc: 53.29% | LR: 0.000012
Epoch: 013 | Train loss: 0.9960 | Train acc: 50.51% | Val loss: 0.9968 | Val acc: 53.36% | LR: 0.000012
Epoch: 014 | Train loss: 0.9951 | Train acc: 50.75% | Val loss: 0.9965 | Val acc: 53.59% | LR: 0.000012
Epoch: 015 | Train loss: 0.9969 | Train acc: 50.43% | Val loss: 0.9966 | Val acc: 53.14% | LR: 0.000012
Epoch: 016 | Train loss: 0.9893 | Train acc: 51.25% | Val loss: 0.9964 | Val acc: 53.42% | LR: 0.000012
Epoch: 017 | Train loss: 0.9970 | Train acc: 50.34% | Val loss: 0.9963 | Val acc: 53.21% | LR: 0.000012
Epoch: 018 | Train loss: 0.9884 | Train acc: 51.37% | Val loss: 0.9962 | Val acc: 53.20% | LR: 0.000012
Epoch: 019 | Train loss: 0.9953 | Train acc: 50.76% | Val loss: 0.9959 | Val acc: 53.30% | LR: 0.000012
Epoch: 020 | Train loss: 0.9931 | Train acc: 50.91% | Val loss: 0.9955 | Val acc: 53.61% | LR: 0.000012
Epoch: 021 | Train loss: 0.9932 | Train acc: 50.89% | Val loss: 0.9951 | Val acc: 53.74% | LR: 0.000012
Epoch: 022 | Train loss: 0.9935 | Train acc: 50.82% | Val loss: 0.9953 | Val acc: 53.50% | LR: 0.000012
Epoch: 023 | Train loss: 0.9948 | Train acc: 50.82% | Val loss: 0.9951 | Val acc: 53.58% | LR: 0.000012
Epoch: 024 | Train loss: 0.9913 | Train acc: 51.05% | Val loss: 0.9948 | Val acc: 53.58% | LR: 0.000012
Epoch: 025 | Train loss: 0.9892 | Train acc: 51.24% | Val loss: 0.9948 | Val acc: 53.33% | LR: 0.000012
Epoch: 026 | Train loss: 0.9935 | Train acc: 50.90% | Val loss: 0.9946 | Val acc: 53.30% | LR: 0.000011
Epoch: 027 | Train loss: 0.9944 | Train acc: 50.79% | Val loss: 0.9945 | Val acc: 53.24% | LR: 0.000011
Epoch: 028 | Train loss: 0.9935 | Train acc: 50.64% | Val loss: 0.9945 | Val acc: 53.13% | LR: 0.000011
Epoch: 029 | Train loss: 0.9886 | Train acc: 51.18% | Val loss: 0.9946 | Val acc: 53.08% | LR: 0.000011
Epoch: 030 | Train loss: 0.9976 | Train acc: 50.55% | Val loss: 0.9944 | Val acc: 53.03% | LR: 0.000011
Epoch: 031 | Train loss: 0.9934 | Train acc: 50.70% | Val loss: 0.9943 | Val acc: 52.99% | LR: 0.000011
Epoch: 032 | Train loss: 0.9913 | Train acc: 50.82% | Val loss: 0.9964 | Val acc: 52.83% | LR: 0.000011
Epoch: 033 | Train loss: 0.9918 | Train acc: 51.03% | Val loss: 0.9963 | Val acc: 53.32% | LR: 0.000011
Epoch: 034 | Train loss: 0.9917 | Train acc: 51.07% | Val loss: 0.9942 | Val acc: 52.76% | LR: 0.000011
Epoch: 035 | Train loss: 0.9886 | Train acc: 51.08% | Val loss: 0.9942 | Val acc: 52.71% | LR: 0.000011
Epoch: 036 | Train loss: 0.9903 | Train acc: 51.10% | Val loss: 0.9941 | Val acc: 52.73% | LR: 0.000011
Epoch: 037 | Train loss: 0.9893 | Train acc: 51.26% | Val loss: 0.9941 | Val acc: 52.69% | LR: 0.000011
Epoch: 038 | Train loss: 0.9922 | Train acc: 50.91% | Val loss: 0.9940 | Val acc: 52.73% | LR: 0.000011
Epoch: 039 | Train loss: 0.9907 | Train acc: 51.02% | Val loss: 0.9939 | Val acc: 52.77% | LR: 0.000010
Epoch: 040 | Train loss: 0.9916 | Train acc: 50.91% | Val loss: 0.9938 | Val acc: 52.79% | LR: 0.000010
Epoch: 041 | Train loss: 0.9885 | Train acc: 50.93% | Val loss: 0.9937 | Val acc: 52.73% | LR: 0.000010
Epoch: 042 | Train loss: 0.9894 | Train acc: 51.17% | Val loss: 0.9936 | Val acc: 52.81% | LR: 0.000010
Epoch: 043 | Train loss: 0.9892 | Train acc: 51.17% | Val loss: 0.9936 | Val acc: 52.79% | LR: 0.000010
Epoch: 044 | Train loss: 0.9889 | Train acc: 51.10% | Val loss: 0.9930 | Val acc: 52.79% | LR: 0.000010
Epoch: 045 | Train loss: 0.9903 | Train acc: 50.83% | Val loss: 0.9927 | Val acc: 52.83% | LR: 0.000010
Epoch: 046 | Train loss: 0.9909 | Train acc: 50.75% | Val loss: 0.9930 | Val acc: 52.91% | LR: 0.000010
Epoch: 047 | Train loss: 0.9975 | Train acc: 50.38% | Val loss: 0.9928 | Val acc: 52.87% | LR: 0.000010
Epoch: 048 | Train loss: 0.9869 | Train acc: 50.99% | Val loss: 0.9928 | Val acc: 52.83% | LR: 0.000010
Epoch: 049 | Train loss: 0.9848 | Train acc: 51.27% | Val loss: 0.9961 | Val acc: 52.78% | LR: 0.000010
Epoch: 050 | Train loss: 0.9898 | Train acc: 50.82% | Val loss: 1.0071 | Val acc: 52.69% | LR: 0.000009
Epoch: 051 | Train loss: 1.0066 | Train acc: 50.22% | Val loss: 1.0172 | Val acc: 53.30% | LR: 0.000009
Epoch: 052 | Train loss: 0.9954 | Train acc: 50.96% | Val loss: 1.0353 | Val acc: 52.45% | LR: 0.000009
Epoch: 053 | Train loss: 0.9980 | Train acc: 50.55% | Val loss: 1.0030 | Val acc: 52.90% | LR: 0.000009
Epoch: 054 | Train loss: 0.9930 | Train acc: 50.60% | Val loss: 1.0338 | Val acc: 52.53% | LR: 0.000009
Epoch: 055 | Train loss: 1.0075 | Train acc: 50.43% | Val loss: 1.0029 | Val acc: 52.70% | LR: 0.000009
Epoch: 056 | Train loss: 0.9925 | Train acc: 50.82% | Val loss: 0.9930 | Val acc: 52.08% | LR: 0.000009
Epoch: 057 | Train loss: 0.9945 | Train acc: 50.73% | Val loss: 1.0002 | Val acc: 51.95% | LR: 0.000009
Epoch: 058 | Train loss: 0.9970 | Train acc: 50.66% | Val loss: 0.9970 | Val acc: 51.80% | LR: 0.000009
Epoch: 059 | Train loss: 0.9874 | Train acc: 51.22% | Val loss: 1.0178 | Val acc: 51.90% | LR: 0.000008
Epoch: 060 | Train loss: 0.9910 | Train acc: 50.77% | Val loss: 0.9964 | Val acc: 52.28% | LR: 0.000008
Epoch: 061 | Train loss: 0.9943 | Train acc: 50.67% | Val loss: 1.0239 | Val acc: 52.08% | LR: 0.000008
Epoch: 062 | Train loss: 0.9947 | Train acc: 50.59% | Val loss: 1.0253 | Val acc: 51.78% | LR: 0.000008
Epoch: 063 | Train loss: 0.9836 | Train acc: 51.50% | Val loss: 1.0020 | Val acc: 51.76% | LR: 0.000008
Epoch: 064 | Train loss: 0.9861 | Train acc: 51.18% | Val loss: 1.0052 | Val acc: 51.60% | LR: 0.000008
Epoch: 065 | Train loss: 0.9873 | Train acc: 51.19% | Val loss: 1.0023 | Val acc: 51.62% | LR: 0.000008
Epoch: 066 | Train loss: 0.9884 | Train acc: 51.37% | Val loss: 1.0039 | Val acc: 51.51% | LR: 0.000008
Epoch: 067 | Train loss: 1.0004 | Train acc: 50.70% | Val loss: 1.0091 | Val acc: 51.83% | LR: 0.000008
Epoch: 068 | Train loss: 0.9915 | Train acc: 50.84% | Val loss: 1.0067 | Val acc: 51.74% | LR: 0.000007
Epoch: 069 | Train loss: 0.9877 | Train acc: 50.93% | Val loss: 1.0027 | Val acc: 51.89% | LR: 0.000007
Epoch: 070 | Train loss: 0.9882 | Train acc: 51.29% | Val loss: 0.9993 | Val acc: 51.56% | LR: 0.000007

[I 2025-09-23 16:13:53,040] Trial 6 finished with value: 0.5189916610717773 and parameters: {'lr': 1.2357670791371932e-05, 'hidden_size': 122, 'dropout': 0.11708311491324747, 'weight_decay': 0.0023582735341837794}. Best is trial 3 with value: 0.5359836459159851.

Epoch: 000 | Train loss: 0.9953 | Train acc: 50.31% | Val loss: 1.0037 | Val acc: 46.31% | LR: 0.000010
Epoch: 001 | Train loss: 1.0050 | Train acc: 49.17% | Val loss: 1.0036 | Val acc: 46.36% | LR: 0.000010
Epoch: 002 | Train loss: 0.9918 | Train acc: 50.43% | Val loss: 1.0036 | Val acc: 46.27% | LR: 0.000010
Epoch: 003 | Train loss: 0.9957 | Train acc: 50.02% | Val loss: 1.0035 | Val acc: 46.21% | LR: 0.000010
Epoch: 004 | Train loss: 1.0293 | Train acc: 49.95% | Val loss: 1.0034 | Val acc: 46.29% | LR: 0.000010
Epoch: 005 | Train loss: 1.0154 | Train acc: 50.36% | Val loss: 1.0034 | Val acc: 46.33% | LR: 0.000010
Epoch: 006 | Train loss: 1.0234 | Train acc: 50.05% | Val loss: 1.0034 | Val acc: 46.31% | LR: 0.000010
Epoch: 007 | Train loss: 0.9956 | Train acc: 50.53% | Val loss: 1.0034 | Val acc: 46.38% | LR: 0.000010
Epoch: 008 | Train loss: 1.1413 | Train acc: 50.45% | Val loss: 1.0034 | Val acc: 46.24% | LR: 0.000010
Epoch: 009 | Train loss: 0.9929 | Train acc: 50.65% | Val loss: 1.0033 | Val acc: 45.78% | LR: 0.000010
Epoch: 010 | Train loss: 0.9965 | Train acc: 50.43% | Val loss: 1.0032 | Val acc: 45.72% | LR: 0.000010
Epoch: 011 | Train loss: 0.9988 | Train acc: 49.73% | Val loss: 1.0030 | Val acc: 45.86% | LR: 0.000010
Epoch: 012 | Train loss: 0.9957 | Train acc: 50.41% | Val loss: 1.0029 | Val acc: 45.65% | LR: 0.000010
Epoch: 013 | Train loss: 1.0336 | Train acc: 50.46% | Val loss: 1.0029 | Val acc: 45.65% | LR: 0.000010
Epoch: 014 | Train loss: 1.0082 | Train acc: 50.70% | Val loss: 1.0029 | Val acc: 45.73% | LR: 0.000010
Epoch: 015 | Train loss: 1.1469 | Train acc: 50.93% | Val loss: 1.0029 | Val acc: 45.75% | LR: 0.000010
Epoch: 016 | Train loss: 1.0084 | Train acc: 50.24% | Val loss: 1.0028 | Val acc: 45.79% | LR: 0.000010
Epoch: 017 | Train loss: 0.9925 | Train acc: 50.56% | Val loss: 1.0027 | Val acc: 45.90% | LR: 0.000010
Epoch: 018 | Train loss: 0.9944 | Train acc: 50.77% | Val loss: 1.0023 | Val acc: 45.93% | LR: 0.000010
Epoch: 019 | Train loss: 0.9962 | Train acc: 50.34% | Val loss: 1.0022 | Val acc: 46.14% | LR: 0.000010
Epoch: 020 | Train loss: 0.9925 | Train acc: 50.87% | Val loss: 1.0021 | Val acc: 46.31% | LR: 0.000010
Epoch: 021 | Train loss: 0.9956 | Train acc: 50.36% | Val loss: 1.0020 | Val acc: 46.72% | LR: 0.000010
Epoch: 022 | Train loss: 1.0001 | Train acc: 50.07% | Val loss: 1.0016 | Val acc: 47.57% | LR: 0.000010
Epoch: 023 | Train loss: 0.9925 | Train acc: 50.83% | Val loss: 1.0014 | Val acc: 47.44% | LR: 0.000010
Epoch: 024 | Train loss: 0.9919 | Train acc: 50.88% | Val loss: 1.0014 | Val acc: 47.32% | LR: 0.000009
Epoch: 025 | Train loss: 0.9930 | Train acc: 50.77% | Val loss: 1.0011 | Val acc: 47.94% | LR: 0.000009
Epoch: 026 | Train loss: 0.9945 | Train acc: 50.43% | Val loss: 1.0011 | Val acc: 47.86% | LR: 0.000009
Epoch: 027 | Train loss: 0.9930 | Train acc: 50.92% | Val loss: 1.0006 | Val acc: 48.82% | LR: 0.000009
Epoch: 028 | Train loss: 0.9942 | Train acc: 50.69% | Val loss: 1.0004 | Val acc: 49.03% | LR: 0.000009
Epoch: 029 | Train loss: 0.9889 | Train acc: 51.29% | Val loss: 1.0004 | Val acc: 49.43% | LR: 0.000009
Epoch: 030 | Train loss: 1.0210 | Train acc: 50.77% | Val loss: 1.0001 | Val acc: 49.49% | LR: 0.000009
Epoch: 031 | Train loss: 1.0256 | Train acc: 50.64% | Val loss: 1.0001 | Val acc: 49.61% | LR: 0.000009
Epoch: 032 | Train loss: 1.0107 | Train acc: 50.50% | Val loss: 1.0000 | Val acc: 49.67% | LR: 0.000009
Epoch: 033 | Train loss: 0.9885 | Train acc: 51.36% | Val loss: 0.9998 | Val acc: 49.66% | LR: 0.000009
Epoch: 034 | Train loss: 0.9918 | Train acc: 50.96% | Val loss: 0.9999 | Val acc: 50.00% | LR: 0.000009
Epoch: 035 | Train loss: 0.9943 | Train acc: 51.15% | Val loss: 1.0034 | Val acc: 50.70% | LR: 0.000009
Epoch: 036 | Train loss: 0.9946 | Train acc: 51.11% | Val loss: 0.9990 | Val acc: 50.53% | LR: 0.000009
Epoch: 037 | Train loss: 0.9938 | Train acc: 50.91% | Val loss: 0.9995 | Val acc: 50.32% | LR: 0.000009
Epoch: 038 | Train loss: 1.3283 | Train acc: 50.66% | Val loss: 0.9994 | Val acc: 50.36% | LR: 0.000009
Epoch: 039 | Train loss: 1.1610 | Train acc: 50.61% | Val loss: 0.9994 | Val acc: 50.36% | LR: 0.000009
Epoch: 040 | Train loss: 0.9941 | Train acc: 51.04% | Val loss: 0.9994 | Val acc: 50.32% | LR: 0.000009
Epoch: 041 | Train loss: 1.0011 | Train acc: 50.78% | Val loss: 0.9995 | Val acc: 50.40% | LR: 0.000008
Epoch: 042 | Train loss: 0.9954 | Train acc: 50.94% | Val loss: 0.9996 | Val acc: 50.46% | LR: 0.000008
Epoch: 043 | Train loss: 0.9954 | Train acc: 50.94% | Val loss: 0.9999 | Val acc: 50.15% | LR: 0.000008
Epoch: 044 | Train loss: 0.9972 | Train acc: 50.60% | Val loss: 0.9997 | Val acc: 50.24% | LR: 0.000008
Epoch: 045 | Train loss: 0.9944 | Train acc: 51.07% | Val loss: 0.9995 | Val acc: 50.28% | LR: 0.000008
Epoch: 046 | Train loss: 0.9926 | Train acc: 50.94% | Val loss: 0.9995 | Val acc: 50.22% | LR: 0.000008
Epoch: 047 | Train loss: 0.9948 | Train acc: 50.84% | Val loss: 0.9995 | Val acc: 50.18% | LR: 0.000008
Epoch: 048 | Train loss: 0.9933 | Train acc: 50.79% | Val loss: 1.0057 | Val acc: 50.28% | LR: 0.000008
Epoch: 049 | Train loss: 0.9930 | Train acc: 51.30% | Val loss: 0.9995 | Val acc: 50.34% | LR: 0.000008
Epoch: 050 | Train loss: 0.9971 | Train acc: 50.62% | Val loss: 1.0004 | Val acc: 50.64% | LR: 0.000008
Epoch: 051 | Train loss: 0.9982 | Train acc: 50.52% | Val loss: 0.9993 | Val acc: 50.54% | LR: 0.000008
Epoch: 052 | Train loss: 0.9986 | Train acc: 50.58% | Val loss: 0.9991 | Val acc: 50.84% | LR: 0.000008
Epoch: 053 | Train loss: 0.9924 | Train acc: 51.34% | Val loss: 0.9990 | Val acc: 50.84% | LR: 0.000007
Epoch: 054 | Train loss: 0.9938 | Train acc: 51.11% | Val loss: 0.9989 | Val acc: 50.70% | LR: 0.000007
Epoch: 055 | Train loss: 1.0066 | Train acc: 51.47% | Val loss: 0.9994 | Val acc: 50.76% | LR: 0.000007
Epoch: 056 | Train loss: 0.9920 | Train acc: 51.19% | Val loss: 0.9991 | Val acc: 50.70% | LR: 0.000007
Epoch: 057 | Train loss: 0.9937 | Train acc: 50.81% | Val loss: 0.9992 | Val acc: 50.64% | LR: 0.000007
Epoch: 058 | Train loss: 0.9938 | Train acc: 50.91% | Val loss: 0.9991 | Val acc: 50.68% | LR: 0.000007
Epoch: 059 | Train loss: 0.9933 | Train acc: 51.00% | Val loss: 0.9990 | Val acc: 50.68% | LR: 0.000007
Epoch: 060 | Train loss: 0.9887 | Train acc: 51.43% | Val loss: 0.9990 | Val acc: 50.76% | LR: 0.000007
Epoch: 061 | Train loss: 0.9924 | Train acc: 51.08% | Val loss: 0.9989 | Val acc: 50.78% | LR: 0.000007
Epoch: 062 | Train loss: 0.9954 | Train acc: 50.81% | Val loss: 0.9989 | Val acc: 50.74% | LR: 0.000007
Epoch: 063 | Train loss: 0.9990 | Train acc: 50.48% | Val loss: 0.9989 | Val acc: 50.85% | LR: 0.000007
Epoch: 064 | Train loss: 0.9922 | Train acc: 51.08% | Val loss: 0.9985 | Val acc: 50.85% | LR: 0.000006
Epoch: 065 | Train loss: 0.9852 | Train acc: 51.81% | Val loss: 0.9985 | Val acc: 50.79% | LR: 0.000006
Epoch: 066 | Train loss: 0.9977 | Train acc: 50.54% | Val loss: 0.9985 | Val acc: 50.79% | LR: 0.000006
Epoch: 067 | Train loss: 0.9922 | Train acc: 50.91% | Val loss: 0.9988 | Val acc: 50.83% | LR: 0.000006
Epoch: 068 | Train loss: 0.9853 | Train acc: 51.71% | Val loss: 0.9986 | Val acc: 50.89% | LR: 0.000006
Epoch: 069 | Train loss: 0.9872 | Train acc: 51.71% | Val loss: 1.0006 | Val acc: 50.98% | LR: 0.000006
Epoch: 070 | Train loss: 0.9944 | Train acc: 50.55% | Val loss: 0.9986 | Val acc: 51.01% | LR: 0.000006
Epoch: 071 | Train loss: 0.9946 | Train acc: 50.83% | Val loss: 0.9986 | Val acc: 50.87% | LR: 0.000006
Epoch: 072 | Train loss: 0.9946 | Train acc: 50.98% | Val loss: 0.9986 | Val acc: 50.91% | LR: 0.000006
Epoch: 073 | Train loss: 0.9912 | Train acc: 50.99% | Val loss: 0.9985 | Val acc: 50.92% | LR: 0.000006
Epoch: 074 | Train loss: 0.9960 | Train acc: 50.61% | Val loss: 0.9984 | Val acc: 51.04% | LR: 0.000006
Epoch: 075 | Train loss: 0.9946 | Train acc: 50.70% | Val loss: 0.9983 | Val acc: 50.98% | LR: 0.000005
Epoch: 076 | Train loss: 0.9991 | Train acc: 50.36% | Val loss: 0.9991 | Val acc: 51.13% | LR: 0.000005
Epoch: 077 | Train loss: 0.9975 | Train acc: 50.37% | Val loss: 0.9982 | Val acc: 51.15% | LR: 0.000005
Epoch: 078 | Train loss: 0.9990 | Train acc: 50.32% | Val loss: 0.9979 | Val acc: 51.17% | LR: 0.000005
Epoch: 079 | Train loss: 0.9956 | Train acc: 50.47% | Val loss: 0.9980 | Val acc: 51.17% | LR: 0.000005
Epoch: 080 | Train loss: 0.9976 | Train acc: 50.55% | Val loss: 0.9980 | Val acc: 51.15% | LR: 0.000005
Epoch: 081 | Train loss: 0.9944 | Train acc: 50.87% | Val loss: 0.9980 | Val acc: 51.10% | LR: 0.000005
Epoch: 082 | Train loss: 0.9935 | Train acc: 50.78% | Val loss: 0.9981 | Val acc: 51.14% | LR: 0.000005
Epoch: 083 | Train loss: 0.9855 | Train acc: 51.49% | Val loss: 0.9999 | Val acc: 51.10% | LR: 0.000005
Epoch: 084 | Train loss: 0.9878 | Train acc: 51.23% | Val loss: 0.9979 | Val acc: 51.19% | LR: 0.000005
Epoch: 085 | Train loss: 0.9936 | Train acc: 50.87% | Val loss: 0.9980 | Val acc: 51.12% | LR: 0.000005
Epoch: 086 | Train loss: 0.9870 | Train acc: 51.57% | Val loss: 0.9978 | Val acc: 51.13% | LR: 0.000004
Epoch: 087 | Train loss: 0.9916 | Train acc: 50.83% | Val loss: 0.9978 | Val acc: 51.25% | LR: 0.000004
Epoch: 088 | Train loss: 0.9855 | Train acc: 51.45% | Val loss: 0.9999 | Val acc: 51.19% | LR: 0.000004
Epoch: 089 | Train loss: 0.9963 | Train acc: 50.61% | Val loss: 0.9981 | Val acc: 51.62% | LR: 0.000004
Epoch: 090 | Train loss: 0.9980 | Train acc: 50.59% | Val loss: 0.9976 | Val acc: 51.33% | LR: 0.000004
Epoch: 091 | Train loss: 0.9929 | Train acc: 50.87% | Val loss: 0.9982 | Val acc: 51.52% | LR: 0.000004
Epoch: 092 | Train loss: 0.9875 | Train acc: 51.31% | Val loss: 0.9989 | Val acc: 51.34% | LR: 0.000004
Epoch: 093 | Train loss: 0.9919 | Train acc: 50.83% | Val loss: 0.9974 | Val acc: 51.27% | LR: 0.000004
Epoch: 094 | Train loss: 0.9927 | Train acc: 50.64% | Val loss: 0.9977 | Val acc: 51.22% | LR: 0.000004
Epoch: 095 | Train loss: 0.9924 | Train acc: 50.81% | Val loss: 0.9980 | Val acc: 51.21% | LR: 0.000004
Epoch: 096 | Train loss: 0.9886 | Train acc: 51.11% | Val loss: 0.9984 | Val acc: 51.23% | LR: 0.000004
Epoch: 097 | Train loss: 0.9926 | Train acc: 50.85% | Val loss: 1.0083 | Val acc: 51.42% | LR: 0.000003
Epoch: 098 | Train loss: 0.9910 | Train acc: 50.91% | Val loss: 0.9985 | Val acc: 51.40% | LR: 0.000003
Epoch: 099 | Train loss: 0.9956 | Train acc: 50.47% | Val loss: 0.9984 | Val acc: 51.52% | LR: 0.000003
Epoch: 100 | Train loss: 0.9925 | Train acc: 51.02% | Val loss: 0.9988 | Val acc: 51.52% | LR: 0.000003
Epoch: 101 | Train loss: 0.9879 | Train acc: 51.20% | Val loss: 1.0055 | Val acc: 51.58% | LR: 0.000003
Epoch: 102 | Train loss: 0.9872 | Train acc: 51.41% | Val loss: 0.9973 | Val acc: 51.41% | LR: 0.000003
Epoch: 103 | Train loss: 0.9923 | Train acc: 50.87% | Val loss: 0.9988 | Val acc: 51.48% | LR: 0.000003
Epoch: 104 | Train loss: 1.0052 | Train acc: 50.61% | Val loss: 1.0031 | Val acc: 51.35% | LR: 0.000003
Epoch: 105 | Train loss: 0.9867 | Train acc: 51.40% | Val loss: 0.9978 | Val acc: 51.41% | LR: 0.000003
Epoch: 106 | Train loss: 0.9957 | Train acc: 50.61% | Val loss: 1.0060 | Val acc: 51.37% | LR: 0.000003
Epoch: 107 | Train loss: 0.9933 | Train acc: 50.76% | Val loss: 0.9982 | Val acc: 51.43% | LR: 0.000003
Epoch: 108 | Train loss: 0.9994 | Train acc: 51.03% | Val loss: 1.0075 | Val acc: 51.39% | LR: 0.000003
Epoch: 109 | Train loss: 0.9890 | Train acc: 51.22% | Val loss: 0.9978 | Val acc: 51.41% | LR: 0.000003
Epoch: 110 | Train loss: 0.9972 | Train acc: 50.70% | Val loss: 1.0000 | Val acc: 51.35% | LR: 0.000002
Epoch: 111 | Train loss: 0.9874 | Train acc: 51.12% | Val loss: 0.9969 | Val acc: 51.37% | LR: 0.000002
Epoch: 112 | Train loss: 0.9912 | Train acc: 51.13% | Val loss: 0.9987 | Val acc: 51.31% | LR: 0.000002
Epoch: 113 | Train loss: 0.9874 | Train acc: 51.40% | Val loss: 1.0076 | Val acc: 51.23% | LR: 0.000002
Epoch: 114 | Train loss: 0.9966 | Train acc: 50.77% | Val loss: 1.0162 | Val acc: 51.46% | LR: 0.000002
Epoch: 115 | Train loss: 0.9937 | Train acc: 50.76% | Val loss: 0.9998 | Val acc: 51.48% | LR: 0.000002
Epoch: 116 | Train loss: 0.9914 | Train acc: 50.92% | Val loss: 0.9990 | Val acc: 51.44% | LR: 0.000002
Epoch: 117 | Train loss: 0.9892 | Train acc: 51.03% | Val loss: 0.9974 | Val acc: 51.40% | LR: 0.000002
Epoch: 118 | Train loss: 0.9899 | Train acc: 51.02% | Val loss: 0.9982 | Val acc: 51.44% | LR: 0.000002
Epoch: 119 | Train loss: 0.9969 | Train acc: 50.48% | Val loss: 1.0096 | Val acc: 51.48% | LR: 0.000002
Epoch: 120 | Train loss: 0.9929 | Train acc: 50.84% | Val loss: 0.9981 | Val acc: 51.48% | LR: 0.000002
Epoch: 121 | Train loss: 0.9972 | Train acc: 50.47% | Val loss: 0.9971 | Val acc: 51.44% | LR: 0.000002
Epoch: 122 | Train loss: 0.9933 | Train acc: 50.64% | Val loss: 0.9977 | Val acc: 51.44% | LR: 0.000002
Epoch: 123 | Train loss: 0.9818 | Train acc: 51.64% | Val loss: 0.9997 | Val acc: 51.42% | LR: 0.000002
Epoch: 124 | Train loss: 0.9851 | Train acc: 51.35% | Val loss: 0.9984 | Val acc: 51.40% | LR: 0.000002
Epoch: 125 | Train loss: 0.9982 | Train acc: 50.55% | Val loss: 0.9985 | Val acc: 51.38% | LR: 0.000002
Epoch: 126 | Train loss: 0.9944 | Train acc: 50.81% | Val loss: 0.9978 | Val acc: 51.42% | LR: 0.000002
Epoch: 127 | Train loss: 0.9895 | Train acc: 51.19% | Val loss: 0.9984 | Val acc: 51.42% | LR: 0.000001
Epoch: 128 | Train loss: 0.9885 | Train acc: 51.18% | Val loss: 1.0093 | Val acc: 51.40% | LR: 0.000001
Epoch: 129 | Train loss: 0.9873 | Train acc: 51.27% | Val loss: 1.0403 | Val acc: 51.42% | LR: 0.000001
Epoch: 130 | Train loss: 0.9942 | Train acc: 50.39% | Val loss: 0.9992 | Val acc: 51.38% | LR: 0.000001
Epoch: 131 | Train loss: 0.9879 | Train acc: 51.19% | Val loss: 0.9976 | Val acc: 51.42% | LR: 0.000001
Epoch: 132 | Train loss: 0.9883 | Train acc: 51.28% | Val loss: 0.9977 | Val acc: 51.42% | LR: 0.000001
Epoch: 133 | Train loss: 0.9909 | Train acc: 51.09% | Val loss: 0.9978 | Val acc: 51.42% | LR: 0.000001
Epoch: 134 | Train loss: 0.9920 | Train acc: 50.84% | Val loss: 0.9984 | Val acc: 51.38% | LR: 0.000001
Epoch: 135 | Train loss: 0.9926 | Train acc: 50.64% | Val loss: 1.0019 | Val acc: 51.29% | LR: 0.000001
Epoch: 136 | Train loss: 0.9927 | Train acc: 50.82% | Val loss: 0.9984 | Val acc: 51.29% | LR: 0.000001
Epoch: 137 | Train loss: 0.9918 | Train acc: 50.90% | Val loss: 0.9985 | Val acc: 51.29% | LR: 0.000001
Epoch: 138 | Train loss: 0.9894 | Train acc: 51.08% | Val loss: 0.9975 | Val acc: 51.39% | LR: 0.000001

[I 2025-09-23 16:17:52,066] Trial 7 finished with value: 0.5137631356716156 and parameters: {'lr': 1.0105802839241863e-05, 'hidden_size': 182, 'dropout': 0.1345238441588517, 'weight_decay': 2.3141925008819096e-06}. Best is trial 3 with value: 0.5359836459159851.

Epoch: 000 | Train loss: 1.0000 | Train acc: 50.27% | Val loss: 0.9953 | Val acc: 54.35% | LR: 0.000353
Epoch: 001 | Train loss: 0.9955 | Train acc: 50.00% | Val loss: 0.9926 | Val acc: 53.92% | LR: 0.000353
Epoch: 002 | Train loss: 0.9897 | Train acc: 50.58% | Val loss: 0.9853 | Val acc: 53.93% | LR: 0.000353
Epoch: 003 | Train loss: 0.9878 | Train acc: 51.00% | Val loss: 0.9787 | Val acc: 53.38% | LR: 0.000352
Epoch: 004 | Train loss: 0.9921 | Train acc: 50.58% | Val loss: 0.9865 | Val acc: 50.99% | LR: 0.000352
Epoch: 005 | Train loss: 0.9792 | Train acc: 51.52% | Val loss: 0.9839 | Val acc: 51.63% | LR: 0.000351
Epoch: 006 | Train loss: 0.9864 | Train acc: 50.93% | Val loss: 0.9892 | Val acc: 50.59% | LR: 0.000351
Epoch: 007 | Train loss: 0.9871 | Train acc: 51.05% | Val loss: 0.9997 | Val acc: 49.70% | LR: 0.000350
Epoch: 008 | Train loss: 0.9808 | Train acc: 51.28% | Val loss: 0.9988 | Val acc: 50.26% | LR: 0.000350
Epoch: 009 | Train loss: 0.9749 | Train acc: 51.57% | Val loss: 1.0142 | Val acc: 49.30% | LR: 0.000349
Epoch: 010 | Train loss: 0.9834 | Train acc: 51.15% | Val loss: 1.0264 | Val acc: 48.46% | LR: 0.000348
Epoch: 011 | Train loss: 0.9849 | Train acc: 50.89% | Val loss: 1.0117 | Val acc: 48.98% | LR: 0.000347
Epoch: 012 | Train loss: 0.9775 | Train acc: 51.33% | Val loss: 1.0096 | Val acc: 49.36% | LR: 0.000346
Epoch: 013 | Train loss: 0.9855 | Train acc: 50.81% | Val loss: 1.0225 | Val acc: 48.84% | LR: 0.000345
Epoch: 014 | Train loss: 0.9845 | Train acc: 50.81% | Val loss: 1.0177 | Val acc: 48.99% | LR: 0.000344
Epoch: 015 | Train loss: 0.9868 | Train acc: 50.79% | Val loss: 1.0229 | Val acc: 48.16% | LR: 0.000343
Epoch: 016 | Train loss: 0.9801 | Train acc: 51.17% | Val loss: 1.0284 | Val acc: 48.40% | LR: 0.000342
Epoch: 017 | Train loss: 0.9780 | Train acc: 51.33% | Val loss: 0.9786 | Val acc: 51.12% | LR: 0.000341
Epoch: 018 | Train loss: 0.9784 | Train acc: 51.15% | Val loss: 1.0118 | Val acc: 49.87% | LR: 0.000339
Epoch: 019 | Train loss: 0.9873 | Train acc: 50.82% | Val loss: 1.0102 | Val acc: 49.21% | LR: 0.000338
Epoch: 020 | Train loss: 0.9798 | Train acc: 51.11% | Val loss: 1.0168 | Val acc: 49.24% | LR: 0.000336
Epoch: 021 | Train loss: 0.9804 | Train acc: 51.14% | Val loss: 1.0137 | Val acc: 49.30% | LR: 0.000335
Epoch: 022 | Train loss: 0.9703 | Train acc: 51.72% | Val loss: 1.0139 | Val acc: 49.20% | LR: 0.000333
Epoch: 023 | Train loss: 0.9746 | Train acc: 51.39% | Val loss: 1.0136 | Val acc: 49.24% | LR: 0.000331
Epoch: 024 | Train loss: 0.9877 | Train acc: 50.68% | Val loss: 1.0059 | Val acc: 49.58% | LR: 0.000329
Epoch: 025 | Train loss: 0.9791 | Train acc: 51.15% | Val loss: 1.0230 | Val acc: 48.98% | LR: 0.000327
Epoch: 026 | Train loss: 0.9799 | Train acc: 51.14% | Val loss: 1.0342 | Val acc: 48.25% | LR: 0.000325
Epoch: 027 | Train loss: 0.9772 | Train acc: 51.23% | Val loss: 1.0146 | Val acc: 49.44% | LR: 0.000323
Epoch: 028 | Train loss: 0.9722 | Train acc: 51.46% | Val loss: 1.0065 | Val acc: 49.63% | LR: 0.000321
Epoch: 029 | Train loss: 0.9838 | Train acc: 50.85% | Val loss: 1.0105 | Val acc: 49.35% | LR: 0.000319
Epoch: 030 | Train loss: 0.9790 | Train acc: 51.14% | Val loss: 1.0111 | Val acc: 49.17% | LR: 0.000317
Epoch: 031 | Train loss: 0.9851 | Train acc: 50.79% | Val loss: 1.0236 | Val acc: 48.88% | LR: 0.000315
Epoch: 032 | Train loss: 0.9733 | Train acc: 51.59% | Val loss: 1.0159 | Val acc: 49.21% | LR: 0.000313
Epoch: 033 | Train loss: 0.9815 | Train acc: 50.99% | Val loss: 1.0113 | Val acc: 49.33% | LR: 0.000310
Epoch: 034 | Train loss: 0.9721 | Train acc: 51.51% | Val loss: 1.0107 | Val acc: 49.56% | LR: 0.000308
Epoch: 035 | Train loss: 0.9908 | Train acc: 50.48% | Val loss: 1.0050 | Val acc: 49.68% | LR: 0.000305
Epoch: 036 | Train loss: 0.9820 | Train acc: 50.99% | Val loss: 1.0080 | Val acc: 49.49% | LR: 0.000303
Epoch: 037 | Train loss: 0.9797 | Train acc: 51.08% | Val loss: 1.0085 | Val acc: 49.73% | LR: 0.000300
Epoch: 038 | Train loss: 0.9801 | Train acc: 51.14% | Val loss: 1.0162 | Val acc: 49.00% | LR: 0.000297
Epoch: 039 | Train loss: 0.9772 | Train acc: 51.24% | Val loss: 1.0230 | Val acc: 48.92% | LR: 0.000295
Epoch: 040 | Train loss: 0.9790 | Train acc: 51.11% | Val loss: 1.0103 | Val acc: 49.70% | LR: 0.000292
Epoch: 041 | Train loss: 0.9781 | Train acc: 51.11% | Val loss: 1.0101 | Val acc: 49.59% | LR: 0.000289
Epoch: 042 | Train loss: 0.9790 | Train acc: 51.12% | Val loss: 1.0065 | Val acc: 49.98% | LR: 0.000286
Epoch: 043 | Train loss: 0.9733 | Train acc: 51.52% | Val loss: 0.9952 | Val acc: 50.04% | LR: 0.000283
Epoch: 044 | Train loss: 0.9755 | Train acc: 51.30% | Val loss: 1.0019 | Val acc: 50.16% | LR: 0.000280
Epoch: 045 | Train loss: 0.9736 | Train acc: 51.41% | Val loss: 1.0014 | Val acc: 50.03% | LR: 0.000277
Epoch: 046 | Train loss: 0.9845 | Train acc: 50.82% | Val loss: 1.0107 | Val acc: 49.29% | LR: 0.000274
Epoch: 047 | Train loss: 0.9749 | Train acc: 51.35% | Val loss: 1.0001 | Val acc: 49.83% | LR: 0.000271
Epoch: 048 | Train loss: 0.9871 | Train acc: 50.63% | Val loss: 0.9993 | Val acc: 50.05% | LR: 0.000268
Epoch: 049 | Train loss: 0.9735 | Train acc: 51.40% | Val loss: 0.9998 | Val acc: 50.28% | LR: 0.000265

[I 2025-09-23 16:18:38,303] Trial 8 finished with value: 0.5066776216030121 and parameters: {'lr': 0.00035287823126996796, 'hidden_size': 231, 'dropout': 0.22728603536521153, 'weight_decay': 0.00014019310291377425}. Best is trial 3 with value: 0.5359836459159851.

Epoch: 000 | Train loss: 0.9994 | Train acc: 50.26% | Val loss: 0.9980 | Val acc: 54.51% | LR: 0.000283
Epoch: 001 | Train loss: 0.9960 | Train acc: 51.02% | Val loss: 1.0010 | Val acc: 52.21% | LR: 0.000283
Epoch: 002 | Train loss: 1.0048 | Train acc: 50.81% | Val loss: 0.9991 | Val acc: 50.83% | LR: 0.000283
Epoch: 003 | Train loss: 0.9863 | Train acc: 51.28% | Val loss: 0.9994 | Val acc: 51.23% | LR: 0.000283
Epoch: 004 | Train loss: 0.9923 | Train acc: 50.77% | Val loss: 1.0033 | Val acc: 49.95% | LR: 0.000282
Epoch: 005 | Train loss: 0.9829 | Train acc: 51.46% | Val loss: 1.0277 | Val acc: 49.71% | LR: 0.000282
Epoch: 006 | Train loss: 0.9954 | Train acc: 50.62% | Val loss: 1.0299 | Val acc: 50.95% | LR: 0.000282
Epoch: 007 | Train loss: 0.9941 | Train acc: 51.19% | Val loss: 1.0017 | Val acc: 50.80% | LR: 0.000281
Epoch: 008 | Train loss: 0.9906 | Train acc: 51.05% | Val loss: 1.0135 | Val acc: 51.66% | LR: 0.000281
Epoch: 009 | Train loss: 0.9897 | Train acc: 51.13% | Val loss: 1.0459 | Val acc: 51.65% | LR: 0.000280
Epoch: 010 | Train loss: 0.9884 | Train acc: 50.91% | Val loss: 0.9924 | Val acc: 51.91% | LR: 0.000279
Epoch: 011 | Train loss: 0.9869 | Train acc: 51.02% | Val loss: 1.0476 | Val acc: 51.74% | LR: 0.000279
Epoch: 012 | Train loss: 0.9880 | Train acc: 50.95% | Val loss: 1.0159 | Val acc: 51.73% | LR: 0.000278
Epoch: 013 | Train loss: 0.9908 | Train acc: 50.86% | Val loss: 0.9938 | Val acc: 51.79% | LR: 0.000277
Epoch: 014 | Train loss: 0.9857 | Train acc: 51.06% | Val loss: 0.9950 | Val acc: 51.28% | LR: 0.000276
Epoch: 015 | Train loss: 1.1301 | Train acc: 51.11% | Val loss: 0.9891 | Val acc: 51.66% | LR: 0.000275
Epoch: 016 | Train loss: 0.9840 | Train acc: 51.07% | Val loss: 0.9820 | Val acc: 52.13% | LR: 0.000274
Epoch: 017 | Train loss: 0.9923 | Train acc: 50.76% | Val loss: 0.9784 | Val acc: 52.60% | LR: 0.000273
Epoch: 018 | Train loss: 0.9839 | Train acc: 51.43% | Val loss: 0.9875 | Val acc: 52.43% | LR: 0.000272
Epoch: 019 | Train loss: 0.9836 | Train acc: 51.19% | Val loss: 0.9878 | Val acc: 51.23% | LR: 0.000271
Epoch: 020 | Train loss: 0.9814 | Train acc: 51.08% | Val loss: 0.9761 | Val acc: 51.87% | LR: 0.000270
Epoch: 021 | Train loss: 0.9788 | Train acc: 51.24% | Val loss: 0.9732 | Val acc: 52.21% | LR: 0.000269
Epoch: 022 | Train loss: 0.9900 | Train acc: 50.64% | Val loss: 0.9710 | Val acc: 52.20% | LR: 0.000267
Epoch: 023 | Train loss: 0.9831 | Train acc: 51.15% | Val loss: 0.9739 | Val acc: 52.30% | LR: 0.000266
Epoch: 024 | Train loss: 0.9852 | Train acc: 50.91% | Val loss: 0.9702 | Val acc: 52.17% | LR: 0.000264
Epoch: 025 | Train loss: 0.9898 | Train acc: 50.66% | Val loss: 0.9711 | Val acc: 52.36% | LR: 0.000263
Epoch: 026 | Train loss: 0.9797 | Train acc: 51.23% | Val loss: 0.9708 | Val acc: 52.28% | LR: 0.000261
Epoch: 027 | Train loss: 0.9863 | Train acc: 50.88% | Val loss: 0.9639 | Val acc: 52.42% | LR: 0.000260
Epoch: 028 | Train loss: 0.9792 | Train acc: 51.45% | Val loss: 0.9654 | Val acc: 52.41% | LR: 0.000258
Epoch: 029 | Train loss: 0.9834 | Train acc: 51.12% | Val loss: 0.9938 | Val acc: 52.15% | LR: 0.000256
Epoch: 030 | Train loss: 0.9954 | Train acc: 50.62% | Val loss: 0.9914 | Val acc: 52.20% | LR: 0.000255
Epoch: 031 | Train loss: 0.9852 | Train acc: 50.94% | Val loss: 0.9692 | Val acc: 52.46% | LR: 0.000253
Epoch: 032 | Train loss: 0.9836 | Train acc: 50.96% | Val loss: 0.9795 | Val acc: 52.30% | LR: 0.000251
Epoch: 033 | Train loss: 0.9849 | Train acc: 51.21% | Val loss: 0.9597 | Val acc: 52.91% | LR: 0.000249
Epoch: 034 | Train loss: 0.9958 | Train acc: 50.30% | Val loss: 0.9666 | Val acc: 52.86% | LR: 0.000247
Epoch: 035 | Train loss: 0.9827 | Train acc: 51.24% | Val loss: 0.9687 | Val acc: 52.63% | LR: 0.000245
Epoch: 036 | Train loss: 0.9837 | Train acc: 51.14% | Val loss: 0.9653 | Val acc: 52.44% | LR: 0.000243
Epoch: 037 | Train loss: 0.9947 | Train acc: 50.43% | Val loss: 0.9814 | Val acc: 52.60% | LR: 0.000241
Epoch: 038 | Train loss: 0.9827 | Train acc: 51.05% | Val loss: 0.9613 | Val acc: 52.60% | LR: 0.000239
Epoch: 039 | Train loss: 0.9867 | Train acc: 50.82% | Val loss: 0.9726 | Val acc: 52.16% | LR: 0.000237
Epoch: 040 | Train loss: 0.9865 | Train acc: 50.79% | Val loss: 0.9828 | Val acc: 51.96% | LR: 0.000234
Epoch: 041 | Train loss: 0.9885 | Train acc: 50.66% | Val loss: 0.9690 | Val acc: 51.93% | LR: 0.000232
Epoch: 042 | Train loss: 0.9775 | Train acc: 51.43% | Val loss: 0.9793 | Val acc: 51.48% | LR: 0.000230
Epoch: 043 | Train loss: 0.9866 | Train acc: 50.90% | Val loss: 0.9749 | Val acc: 51.16% | LR: 0.000227
Epoch: 044 | Train loss: 0.9847 | Train acc: 50.80% | Val loss: 0.9761 | Val acc: 51.21% | LR: 0.000225
Epoch: 045 | Train loss: 0.9788 | Train acc: 51.18% | Val loss: 0.9761 | Val acc: 51.10% | LR: 0.000223
Epoch: 046 | Train loss: 0.9900 | Train acc: 50.55% | Val loss: 0.9744 | Val acc: 51.34% | LR: 0.000220
Epoch: 047 | Train loss: 0.9852 | Train acc: 50.73% | Val loss: 0.9758 | Val acc: 51.24% | LR: 0.000218
Epoch: 048 | Train loss: 0.9803 | Train acc: 50.96% | Val loss: 0.9763 | Val acc: 51.30% | LR: 0.000215
Epoch: 049 | Train loss: 0.9905 | Train acc: 50.46% | Val loss: 0.9773 | Val acc: 51.31% | LR: 0.000213

[I 2025-09-23 16:19:27,124] Trial 9 finished with value: 0.5136318445205689 and parameters: {'lr': 0.0002832167316310237, 'hidden_size': 127, 'dropout': 0.26761884454234797, 'weight_decay': 0.0015974108086333964}. Best is trial 3 with value: 0.5359836459159851.

Epoch: 000 | Train loss: 0.9968 | Train acc: 50.48% | Val loss: 0.9853 | Val acc: 54.27% | LR: 0.002168
Epoch: 001 | Train loss: 0.9923 | Train acc: 50.69% | Val loss: 0.9636 | Val acc: 54.38% | LR: 0.002168
Epoch: 002 | Train loss: 0.9987 | Train acc: 50.26% | Val loss: 0.9791 | Val acc: 54.44% | LR: 0.002166
Epoch: 003 | Train loss: 0.9893 | Train acc: 51.13% | Val loss: 0.9672 | Val acc: 53.46% | LR: 0.002165
Epoch: 004 | Train loss: 0.9929 | Train acc: 50.68% | Val loss: 0.9689 | Val acc: 52.14% | LR: 0.002163
Epoch: 005 | Train loss: 0.9914 | Train acc: 50.58% | Val loss: 0.9851 | Val acc: 50.36% | LR: 0.002160
Epoch: 006 | Train loss: 0.9879 | Train acc: 51.05% | Val loss: 1.0064 | Val acc: 49.35% | LR: 0.002157
Epoch: 007 | Train loss: 0.9775 | Train acc: 51.52% | Val loss: 1.0299 | Val acc: 47.37% | LR: 0.002153
Epoch: 008 | Train loss: 0.9931 | Train acc: 50.54% | Val loss: 0.9735 | Val acc: 51.33% | LR: 0.002149
Epoch: 009 | Train loss: 0.9895 | Train acc: 50.85% | Val loss: 1.0171 | Val acc: 49.27% | LR: 0.002145
Epoch: 010 | Train loss: 0.9887 | Train acc: 50.83% | Val loss: 0.9689 | Val acc: 51.94% | LR: 0.002140
Epoch: 011 | Train loss: 0.9829 | Train acc: 50.96% | Val loss: 0.9809 | Val acc: 51.92% | LR: 0.002135
Epoch: 012 | Train loss: 0.9805 | Train acc: 51.21% | Val loss: 0.9763 | Val acc: 51.62% | LR: 0.002129
Epoch: 013 | Train loss: 0.9822 | Train acc: 51.33% | Val loss: 0.9512 | Val acc: 52.57% | LR: 0.002122
Epoch: 014 | Train loss: 0.9826 | Train acc: 51.23% | Val loss: 0.9511 | Val acc: 52.84% | LR: 0.002116
Epoch: 015 | Train loss: 0.9831 | Train acc: 50.94% | Val loss: 0.9680 | Val acc: 51.60% | LR: 0.002108
Epoch: 016 | Train loss: 0.9905 | Train acc: 50.50% | Val loss: 0.9529 | Val acc: 52.61% | LR: 0.002101
Epoch: 017 | Train loss: 0.9828 | Train acc: 51.00% | Val loss: 0.9487 | Val acc: 52.83% | LR: 0.002092
Epoch: 018 | Train loss: 0.9819 | Train acc: 51.01% | Val loss: 0.9802 | Val acc: 51.64% | LR: 0.002084
Epoch: 019 | Train loss: 0.9788 | Train acc: 51.23% | Val loss: 0.9910 | Val acc: 51.40% | LR: 0.002075
Epoch: 020 | Train loss: 0.9927 | Train acc: 50.33% | Val loss: 0.9760 | Val acc: 51.62% | LR: 0.002065
Epoch: 021 | Train loss: 0.9775 | Train acc: 51.37% | Val loss: 1.0069 | Val acc: 49.62% | LR: 0.002056
Epoch: 022 | Train loss: 0.9852 | Train acc: 50.82% | Val loss: 1.0152 | Val acc: 48.86% | LR: 0.002045
Epoch: 023 | Train loss: 0.9840 | Train acc: 50.93% | Val loss: 1.0135 | Val acc: 48.75% | LR: 0.002035
Epoch: 024 | Train loss: 0.9775 | Train acc: 51.30% | Val loss: 1.0114 | Val acc: 49.10% | LR: 0.002023
Epoch: 025 | Train loss: 0.9794 | Train acc: 51.22% | Val loss: 1.0172 | Val acc: 48.19% | LR: 0.002012
Epoch: 026 | Train loss: 0.9859 | Train acc: 50.92% | Val loss: 1.0073 | Val acc: 49.37% | LR: 0.002000
Epoch: 027 | Train loss: 0.9832 | Train acc: 51.15% | Val loss: 1.0066 | Val acc: 49.92% | LR: 0.001988
Epoch: 028 | Train loss: 0.9863 | Train acc: 50.73% | Val loss: 1.0117 | Val acc: 49.48% | LR: 0.001975
Epoch: 029 | Train loss: 0.9837 | Train acc: 51.01% | Val loss: 0.9928 | Val acc: 50.32% | LR: 0.001962
Epoch: 030 | Train loss: 0.9832 | Train acc: 50.87% | Val loss: 1.0801 | Val acc: 45.97% | LR: 0.001948
Epoch: 031 | Train loss: 0.9970 | Train acc: 50.70% | Val loss: 1.0483 | Val acc: 45.95% | LR: 0.001934
Epoch: 032 | Train loss: 0.9936 | Train acc: 50.61% | Val loss: 1.0352 | Val acc: 45.95% | LR: 0.001920
Epoch: 033 | Train loss: 0.9934 | Train acc: 50.24% | Val loss: 0.9451 | Val acc: 54.15% | LR: 0.001905
Epoch: 034 | Train loss: 0.9999 | Train acc: 49.83% | Val loss: 0.9878 | Val acc: 52.37% | LR: 0.001890
Epoch: 035 | Train loss: 0.9924 | Train acc: 50.46% | Val loss: 1.0502 | Val acc: 45.95% | LR: 0.001875
Epoch: 036 | Train loss: 0.9900 | Train acc: 50.43% | Val loss: 1.0399 | Val acc: 45.95% | LR: 0.001859
Epoch: 037 | Train loss: 0.9903 | Train acc: 50.54% | Val loss: 0.9778 | Val acc: 52.00% | LR: 0.001843
Epoch: 038 | Train loss: 0.9811 | Train acc: 51.12% | Val loss: 1.0013 | Val acc: 50.13% | LR: 0.001827
Epoch: 039 | Train loss: 0.9833 | Train acc: 51.08% | Val loss: 0.9888 | Val acc: 51.03% | LR: 0.001810
Epoch: 040 | Train loss: 0.9761 | Train acc: 51.51% | Val loss: 1.0239 | Val acc: 48.55% | LR: 0.001793
Epoch: 041 | Train loss: 1.0104 | Train acc: 49.59% | Val loss: 1.0274 | Val acc: 51.47% | LR: 0.001776
Epoch: 042 | Train loss: 1.0008 | Train acc: 50.35% | Val loss: 1.0093 | Val acc: 51.90% | LR: 0.001758
Epoch: 043 | Train loss: 1.0029 | Train acc: 50.87% | Val loss: 0.9606 | Val acc: 51.51% | LR: 0.001740
Epoch: 044 | Train loss: 1.0039 | Train acc: 49.78% | Val loss: 1.0269 | Val acc: 46.97% | LR: 0.001722
Epoch: 045 | Train loss: 0.9903 | Train acc: 50.88% | Val loss: 0.9889 | Val acc: 52.48% | LR: 0.001703
Epoch: 046 | Train loss: 0.9957 | Train acc: 50.82% | Val loss: 0.9712 | Val acc: 52.17% | LR: 0.001685
Epoch: 047 | Train loss: 0.9890 | Train acc: 50.96% | Val loss: 0.9682 | Val acc: 51.86% | LR: 0.001666
Epoch: 048 | Train loss: 0.9781 | Train acc: 51.48% | Val loss: 1.0326 | Val acc: 51.39% | LR: 0.001646
Epoch: 049 | Train loss: 0.9885 | Train acc: 50.86% | Val loss: 0.9612 | Val acc: 52.44% | LR: 0.001627
Epoch: 050 | Train loss: 0.9958 | Train acc: 50.91% | Val loss: 0.9442 | Val acc: 52.99% | LR: 0.001607
Epoch: 051 | Train loss: 0.9881 | Train acc: 50.86% | Val loss: 0.9635 | Val acc: 53.81% | LR: 0.001587

[I 2025-09-23 16:20:12,359] Trial 10 finished with value: 0.5360925793647766 and parameters: {'lr': 0.0021686067544715087, 'hidden_size': 101, 'dropout': 0.3909774850148, 'weight_decay': 1.1178748899790706e-06}. Best is trial 10 with value: 0.5360925793647766.

Epoch: 000 | Train loss: 0.9924 | Train acc: 51.13% | Val loss: 1.0067 | Val acc: 51.62% | LR: 0.002248
Epoch: 001 | Train loss: 1.0084 | Train acc: 51.26% | Val loss: 0.9961 | Val acc: 51.92% | LR: 0.002247
Epoch: 002 | Train loss: 0.9943 | Train acc: 50.88% | Val loss: 0.9584 | Val acc: 53.80% | LR: 0.002246
Epoch: 003 | Train loss: 0.9876 | Train acc: 51.05% | Val loss: 0.9985 | Val acc: 53.77% | LR: 0.002244
Epoch: 004 | Train loss: 2.1143 | Train acc: 50.94% | Val loss: 1.0144 | Val acc: 52.90% | LR: 0.002242
Epoch: 005 | Train loss: 0.9884 | Train acc: 50.86% | Val loss: 0.9718 | Val acc: 52.90% | LR: 0.002239
Epoch: 006 | Train loss: 0.9981 | Train acc: 50.67% | Val loss: 0.9848 | Val acc: 52.63% | LR: 0.002236
Epoch: 007 | Train loss: 0.9918 | Train acc: 50.76% | Val loss: 1.0077 | Val acc: 51.00% | LR: 0.002232
Epoch: 008 | Train loss: 0.9959 | Train acc: 50.71% | Val loss: 1.0136 | Val acc: 47.38% | LR: 0.002228
Epoch: 009 | Train loss: 0.9961 | Train acc: 50.54% | Val loss: 1.0055 | Val acc: 48.96% | LR: 0.002223
Epoch: 010 | Train loss: 0.9971 | Train acc: 50.33% | Val loss: 1.0067 | Val acc: 48.60% | LR: 0.002218
Epoch: 011 | Train loss: 0.9879 | Train acc: 51.15% | Val loss: 0.9885 | Val acc: 51.47% | LR: 0.002213
Epoch: 012 | Train loss: 0.9935 | Train acc: 50.46% | Val loss: 0.9998 | Val acc: 50.25% | LR: 0.002206
Epoch: 013 | Train loss: 0.9919 | Train acc: 50.47% | Val loss: 1.0066 | Val acc: 50.09% | LR: 0.002200
Epoch: 014 | Train loss: 0.9823 | Train acc: 51.00% | Val loss: 1.0100 | Val acc: 49.49% | LR: 0.002193
Epoch: 015 | Train loss: 0.9972 | Train acc: 50.59% | Val loss: 4.3238 | Val acc: 53.22% | LR: 0.002185
Epoch: 016 | Train loss: 1.0000 | Train acc: 50.51% | Val loss: 1.0260 | Val acc: 45.38% | LR: 0.002177
Epoch: 017 | Train loss: 1.0054 | Train acc: 50.62% | Val loss: 1.0443 | Val acc: 46.01% | LR: 0.002169
Epoch: 018 | Train loss: 0.9897 | Train acc: 50.90% | Val loss: 1.0661 | Val acc: 46.33% | LR: 0.002160
Epoch: 019 | Train loss: 0.9947 | Train acc: 50.66% | Val loss: 1.0280 | Val acc: 53.58% | LR: 0.002151
Epoch: 020 | Train loss: 0.9899 | Train acc: 51.04% | Val loss: 0.9484 | Val acc: 54.36% | LR: 0.002141
Epoch: 021 | Train loss: 1.0052 | Train acc: 50.22% | Val loss: 0.9579 | Val acc: 54.07% | LR: 0.002131
Epoch: 022 | Train loss: 0.9984 | Train acc: 50.54% | Val loss: 1.0070 | Val acc: 51.31% | LR: 0.002120
Epoch: 023 | Train loss: 0.9962 | Train acc: 50.52% | Val loss: 1.0258 | Val acc: 45.93% | LR: 0.002109
Epoch: 024 | Train loss: 0.9846 | Train acc: 51.43% | Val loss: 0.9939 | Val acc: 51.12% | LR: 0.002097
Epoch: 025 | Train loss: 0.9869 | Train acc: 51.15% | Val loss: 0.9770 | Val acc: 51.77% | LR: 0.002085
Epoch: 026 | Train loss: 0.9813 | Train acc: 51.37% | Val loss: 0.9824 | Val acc: 51.44% | LR: 0.002073
Epoch: 027 | Train loss: 0.9830 | Train acc: 51.25% | Val loss: 0.9799 | Val acc: 51.27% | LR: 0.002060
Epoch: 028 | Train loss: 0.9882 | Train acc: 50.80% | Val loss: 0.9826 | Val acc: 51.23% | LR: 0.002047
Epoch: 029 | Train loss: 0.9846 | Train acc: 50.97% | Val loss: 0.9788 | Val acc: 51.02% | LR: 0.002033
Epoch: 030 | Train loss: 0.9790 | Train acc: 51.25% | Val loss: 0.9877 | Val acc: 51.36% | LR: 0.002019
Epoch: 031 | Train loss: 0.9895 | Train acc: 50.62% | Val loss: 0.9812 | Val acc: 51.22% | LR: 0.002005
Epoch: 032 | Train loss: 0.9834 | Train acc: 51.05% | Val loss: 0.9786 | Val acc: 51.71% | LR: 0.001990
Epoch: 033 | Train loss: 0.9884 | Train acc: 50.70% | Val loss: 0.9782 | Val acc: 51.41% | LR: 0.001975
Epoch: 034 | Train loss: 0.9875 | Train acc: 50.68% | Val loss: 0.9676 | Val acc: 51.91% | LR: 0.001959
Epoch: 035 | Train loss: 0.9789 | Train acc: 51.40% | Val loss: 0.9711 | Val acc: 51.72% | LR: 0.001943
Epoch: 036 | Train loss: 0.9773 | Train acc: 51.36% | Val loss: 0.9669 | Val acc: 51.89% | LR: 0.001927
Epoch: 037 | Train loss: 0.9833 | Train acc: 51.29% | Val loss: 0.9837 | Val acc: 51.24% | LR: 0.001910
Epoch: 038 | Train loss: 0.9831 | Train acc: 50.98% | Val loss: 0.9809 | Val acc: 51.39% | LR: 0.001893
Epoch: 039 | Train loss: 0.9790 | Train acc: 51.21% | Val loss: 0.9591 | Val acc: 52.13% | LR: 0.001876
Epoch: 040 | Train loss: 0.9813 | Train acc: 51.22% | Val loss: 0.9768 | Val acc: 51.93% | LR: 0.001858
Epoch: 041 | Train loss: 0.9943 | Train acc: 50.28% | Val loss: 0.9809 | Val acc: 51.48% | LR: 0.001840
Epoch: 042 | Train loss: 0.9883 | Train acc: 50.76% | Val loss: 0.9873 | Val acc: 51.37% | LR: 0.001822
Epoch: 043 | Train loss: 0.9842 | Train acc: 51.17% | Val loss: 1.0025 | Val acc: 50.22% | LR: 0.001804
Epoch: 044 | Train loss: 0.9845 | Train acc: 50.89% | Val loss: 0.9910 | Val acc: 51.06% | LR: 0.001785
Epoch: 045 | Train loss: 0.9850 | Train acc: 50.94% | Val loss: 0.9789 | Val acc: 51.37% | LR: 0.001766
Epoch: 046 | Train loss: 0.9746 | Train acc: 51.50% | Val loss: 0.9814 | Val acc: 51.29% | LR: 0.001746
Epoch: 047 | Train loss: 0.9796 | Train acc: 51.04% | Val loss: 0.9856 | Val acc: 51.40% | LR: 0.001726
Epoch: 048 | Train loss: 0.9741 | Train acc: 51.48% | Val loss: 0.9776 | Val acc: 51.48% | LR: 0.001706
Epoch: 049 | Train loss: 0.9811 | Train acc: 51.13% | Val loss: 0.9930 | Val acc: 50.72% | LR: 0.001686
Epoch: 050 | Train loss: 0.9790 | Train acc: 51.23% | Val loss: 0.9876 | Val acc: 51.17% | LR: 0.001666
Epoch: 051 | Train loss: 0.9811 | Train acc: 51.10% | Val loss: 0.9698 | Val acc: 51.90% | LR: 0.001645
Epoch: 052 | Train loss: 0.9803 | Train acc: 51.12% | Val loss: 0.9707 | Val acc: 51.82% | LR: 0.001624
Epoch: 053 | Train loss: 0.9795 | Train acc: 51.10% | Val loss: 0.9777 | Val acc: 51.60% | LR: 0.001603
Epoch: 054 | Train loss: 0.9793 | Train acc: 51.16% | Val loss: 0.9820 | Val acc: 51.37% | LR: 0.001581
Epoch: 055 | Train loss: 0.9873 | Train acc: 50.66% | Val loss: 0.9734 | Val acc: 51.58% | LR: 0.001560
Epoch: 056 | Train loss: 0.9849 | Train acc: 50.86% | Val loss: 0.9728 | Val acc: 51.50% | LR: 0.001538
Epoch: 057 | Train loss: 0.9940 | Train acc: 50.34% | Val loss: 0.9912 | Val acc: 50.89% | LR: 0.001516
Epoch: 058 | Train loss: 0.9833 | Train acc: 51.13% | Val loss: 0.9828 | Val acc: 51.20% | LR: 0.001494
Epoch: 059 | Train loss: 0.9847 | Train acc: 50.81% | Val loss: 0.9791 | Val acc: 51.24% | LR: 0.001472
Epoch: 060 | Train loss: 0.9893 | Train acc: 50.58% | Val loss: 0.9820 | Val acc: 51.14% | LR: 0.001449
Epoch: 061 | Train loss: 0.9747 | Train acc: 51.37% | Val loss: 0.9931 | Val acc: 51.33% | LR: 0.001427
Epoch: 062 | Train loss: 0.9771 | Train acc: 51.40% | Val loss: 0.9941 | Val acc: 50.90% | LR: 0.001404
Epoch: 063 | Train loss: 0.9798 | Train acc: 51.04% | Val loss: 0.9912 | Val acc: 51.00% | LR: 0.001381
Epoch: 064 | Train loss: 0.9725 | Train acc: 51.63% | Val loss: 0.9920 | Val acc: 51.00% | LR: 0.001358
Epoch: 065 | Train loss: 0.9856 | Train acc: 50.76% | Val loss: 0.9961 | Val acc: 50.67% | LR: 0.001335
Epoch: 066 | Train loss: 0.9763 | Train acc: 51.33% | Val loss: 0.9994 | Val acc: 50.61% | LR: 0.001312
Epoch: 067 | Train loss: 0.9713 | Train acc: 51.53% | Val loss: 1.0024 | Val acc: 50.16% | LR: 0.001289
Epoch: 068 | Train loss: 0.9773 | Train acc: 51.21% | Val loss: 0.9996 | Val acc: 50.15% | LR: 0.001265
Epoch: 069 | Train loss: 0.9727 | Train acc: 51.43% | Val loss: 1.0061 | Val acc: 49.95% | LR: 0.001242

[I 2025-09-23 16:21:15,456] Trial 11 finished with value: 0.4989675521850586 and parameters: {'lr': 0.0022477960388129657, 'hidden_size': 96, 'dropout': 0.3884437001183014, 'weight_decay': 1.295026804126673e-06}. Best is trial 10 with value: 0.5360925793647766.

Epoch: 000 | Train loss: 1.0012 | Train acc: 49.45% | Val loss: 1.0181 | Val acc: 53.74% | LR: 0.002615
Epoch: 001 | Train loss: 0.9966 | Train acc: 50.00% | Val loss: 0.9821 | Val acc: 53.74% | LR: 0.002614
Epoch: 002 | Train loss: 1.0239 | Train acc: 50.80% | Val loss: 0.9791 | Val acc: 51.87% | LR: 0.002613
Epoch: 003 | Train loss: 1.0015 | Train acc: 50.92% | Val loss: 1.2463 | Val acc: 51.59% | LR: 0.002611
Epoch: 004 | Train loss: 0.9945 | Train acc: 50.96% | Val loss: 1.0623 | Val acc: 51.20% | LR: 0.002608
Epoch: 005 | Train loss: 0.9940 | Train acc: 50.81% | Val loss: 0.9652 | Val acc: 51.45% | LR: 0.002605
Epoch: 006 | Train loss: 0.9914 | Train acc: 50.77% | Val loss: 1.0168 | Val acc: 48.68% | LR: 0.002601
Epoch: 007 | Train loss: 0.9885 | Train acc: 51.00% | Val loss: 1.0292 | Val acc: 47.25% | LR: 0.002597
Epoch: 008 | Train loss: 0.9968 | Train acc: 50.19% | Val loss: 1.0542 | Val acc: 46.98% | LR: 0.002592
Epoch: 009 | Train loss: 1.0034 | Train acc: 49.75% | Val loss: 1.0511 | Val acc: 45.95% | LR: 0.002587
Epoch: 010 | Train loss: 0.9871 | Train acc: 50.92% | Val loss: 1.0127 | Val acc: 47.41% | LR: 0.002581
Epoch: 011 | Train loss: 0.9838 | Train acc: 51.35% | Val loss: 0.9885 | Val acc: 49.94% | LR: 0.002574
Epoch: 012 | Train loss: 0.9952 | Train acc: 51.00% | Val loss: 0.9606 | Val acc: 54.60% | LR: 0.002567
Epoch: 013 | Train loss: 0.9935 | Train acc: 50.90% | Val loss: 1.0391 | Val acc: 45.99% | LR: 0.002560
Epoch: 014 | Train loss: 0.9894 | Train acc: 50.67% | Val loss: 0.9734 | Val acc: 52.91% | LR: 0.002552
Epoch: 015 | Train loss: 0.9896 | Train acc: 50.95% | Val loss: 1.0018 | Val acc: 50.25% | LR: 0.002543
Epoch: 016 | Train loss: 0.9841 | Train acc: 51.04% | Val loss: 0.9596 | Val acc: 52.96% | LR: 0.002534
Epoch: 017 | Train loss: 0.9817 | Train acc: 50.99% | Val loss: 0.9824 | Val acc: 50.97% | LR: 0.002524
Epoch: 018 | Train loss: 0.9811 | Train acc: 51.15% | Val loss: 0.9698 | Val acc: 51.89% | LR: 0.002513
Epoch: 019 | Train loss: 0.9816 | Train acc: 51.01% | Val loss: 0.9902 | Val acc: 50.72% | LR: 0.002502
Epoch: 020 | Train loss: 0.9924 | Train acc: 50.52% | Val loss: 0.9899 | Val acc: 50.79% | LR: 0.002491
Epoch: 021 | Train loss: 0.9858 | Train acc: 50.96% | Val loss: 0.9849 | Val acc: 51.91% | LR: 0.002479
Epoch: 022 | Train loss: 0.9807 | Train acc: 51.34% | Val loss: 0.9701 | Val acc: 51.60% | LR: 0.002467
Epoch: 023 | Train loss: 0.9819 | Train acc: 51.53% | Val loss: 0.9686 | Val acc: 51.82% | LR: 0.002454
Epoch: 024 | Train loss: 0.9806 | Train acc: 51.23% | Val loss: 0.9726 | Val acc: 51.32% | LR: 0.002440
Epoch: 025 | Train loss: 0.9764 | Train acc: 51.36% | Val loss: 0.9903 | Val acc: 50.60% | LR: 0.002426
Epoch: 026 | Train loss: 0.9787 | Train acc: 51.27% | Val loss: 0.9693 | Val acc: 51.97% | LR: 0.002412
Epoch: 027 | Train loss: 0.9838 | Train acc: 50.95% | Val loss: 0.9733 | Val acc: 51.54% | LR: 0.002397
Epoch: 028 | Train loss: 0.9814 | Train acc: 51.01% | Val loss: 0.9639 | Val acc: 52.24% | LR: 0.002382
Epoch: 029 | Train loss: 0.9792 | Train acc: 51.10% | Val loss: 0.9821 | Val acc: 51.18% | LR: 0.002366
Epoch: 030 | Train loss: 0.9858 | Train acc: 50.80% | Val loss: 0.9765 | Val acc: 51.33% | LR: 0.002350
Epoch: 031 | Train loss: 0.9796 | Train acc: 51.29% | Val loss: 0.9798 | Val acc: 51.00% | LR: 0.002333
Epoch: 032 | Train loss: 0.9739 | Train acc: 51.54% | Val loss: 0.9771 | Val acc: 51.00% | LR: 0.002316
Epoch: 033 | Train loss: 0.9854 | Train acc: 50.85% | Val loss: 0.9747 | Val acc: 51.29% | LR: 0.002298
Epoch: 034 | Train loss: 0.9873 | Train acc: 50.77% | Val loss: 0.9764 | Val acc: 51.25% | LR: 0.002280
Epoch: 035 | Train loss: 0.9918 | Train acc: 50.47% | Val loss: 0.9766 | Val acc: 51.06% | LR: 0.002261
Epoch: 036 | Train loss: 0.9820 | Train acc: 50.99% | Val loss: 0.9750 | Val acc: 51.33% | LR: 0.002242
Epoch: 037 | Train loss: 0.9801 | Train acc: 51.03% | Val loss: 0.9647 | Val acc: 51.66% | LR: 0.002223
Epoch: 038 | Train loss: 0.9818 | Train acc: 51.01% | Val loss: 0.9687 | Val acc: 51.52% | LR: 0.002203
Epoch: 039 | Train loss: 0.9779 | Train acc: 51.37% | Val loss: 0.9768 | Val acc: 51.00% | LR: 0.002183
Epoch: 040 | Train loss: 0.9784 | Train acc: 51.17% | Val loss: 0.9712 | Val acc: 51.41% | LR: 0.002162
Epoch: 041 | Train loss: 0.9797 | Train acc: 51.16% | Val loss: 0.9743 | Val acc: 51.48% | LR: 0.002142
Epoch: 042 | Train loss: 0.9865 | Train acc: 50.79% | Val loss: 0.9631 | Val acc: 51.85% | LR: 0.002120
Epoch: 043 | Train loss: 0.9880 | Train acc: 50.59% | Val loss: 0.9759 | Val acc: 50.67% | LR: 0.002099
Epoch: 044 | Train loss: 0.9849 | Train acc: 50.91% | Val loss: 0.9712 | Val acc: 51.50% | LR: 0.002077
Epoch: 045 | Train loss: 0.9741 | Train acc: 51.52% | Val loss: 0.9607 | Val acc: 51.74% | LR: 0.002054
Epoch: 046 | Train loss: 0.9755 | Train acc: 51.46% | Val loss: 0.9713 | Val acc: 51.36% | LR: 0.002032
Epoch: 047 | Train loss: 0.9724 | Train acc: 51.56% | Val loss: 0.9776 | Val acc: 51.22% | LR: 0.002009
Epoch: 048 | Train loss: 0.9844 | Train acc: 50.94% | Val loss: 0.9851 | Val acc: 51.38% | LR: 0.001985
Epoch: 049 | Train loss: 0.9885 | Train acc: 50.56% | Val loss: 1.0393 | Val acc: 47.77% | LR: 0.001962
Epoch: 050 | Train loss: 0.9956 | Train acc: 50.40% | Val loss: 0.9837 | Val acc: 50.94% | LR: 0.001938
Epoch: 051 | Train loss: 0.9848 | Train acc: 50.97% | Val loss: 0.9719 | Val acc: 51.43% | LR: 0.001914
Epoch: 052 | Train loss: 0.9827 | Train acc: 51.00% | Val loss: 0.9572 | Val acc: 51.65% | LR: 0.001890
Epoch: 053 | Train loss: 0.9916 | Train acc: 50.47% | Val loss: 0.9643 | Val acc: 52.09% | LR: 0.001865
Epoch: 054 | Train loss: 0.9754 | Train acc: 51.55% | Val loss: 0.9596 | Val acc: 52.11% | LR: 0.001840
Epoch: 055 | Train loss: 0.9835 | Train acc: 51.02% | Val loss: 0.9700 | Val acc: 51.83% | LR: 0.001815
Epoch: 056 | Train loss: 0.9927 | Train acc: 50.41% | Val loss: 0.9760 | Val acc: 50.88% | LR: 0.001789
Epoch: 057 | Train loss: 0.9836 | Train acc: 51.10% | Val loss: 0.9925 | Val acc: 50.38% | LR: 0.001764
Epoch: 058 | Train loss: 0.9811 | Train acc: 51.00% | Val loss: 0.9660 | Val acc: 51.84% | LR: 0.001738
Epoch: 059 | Train loss: 0.9828 | Train acc: 51.01% | Val loss: 0.9570 | Val acc: 51.72% | LR: 0.001712
Epoch: 060 | Train loss: 0.9773 | Train acc: 51.29% | Val loss: 0.9592 | Val acc: 52.04% | LR: 0.001686
Epoch: 061 | Train loss: 0.9886 | Train acc: 50.70% | Val loss: 0.9529 | Val acc: 52.69% | LR: 0.001660

[I 2025-09-23 16:22:11,271] Trial 12 finished with value: 0.5184634327888489 and parameters: {'lr': 0.002615513452218841, 'hidden_size': 98, 'dropout': 0.37409343385241434, 'weight_decay': 8.123272471873856e-06}. Best is trial 10 with value: 0.5360925793647766.

Epoch: 000 | Train loss: 0.9990 | Train acc: 49.85% | Val loss: 0.9785 | Val acc: 54.51% | LR: 0.000921
Epoch: 001 | Train loss: 0.9857 | Train acc: 51.14% | Val loss: 0.9717 | Val acc: 52.72% | LR: 0.000920
Epoch: 002 | Train loss: 0.9920 | Train acc: 50.66% | Val loss: 0.9807 | Val acc: 51.06% | LR: 0.000920
Epoch: 003 | Train loss: 1.0075 | Train acc: 50.89% | Val loss: 0.9901 | Val acc: 52.59% | LR: 0.000919
Epoch: 004 | Train loss: 0.9985 | Train acc: 50.88% | Val loss: 0.9818 | Val acc: 53.22% | LR: 0.000918
Epoch: 005 | Train loss: 0.9869 | Train acc: 50.96% | Val loss: 0.9492 | Val acc: 53.37% | LR: 0.000917
Epoch: 006 | Train loss: 0.9868 | Train acc: 50.76% | Val loss: 0.9488 | Val acc: 53.50% | LR: 0.000916
Epoch: 007 | Train loss: 0.9904 | Train acc: 50.51% | Val loss: 0.9496 | Val acc: 53.35% | LR: 0.000914
Epoch: 008 | Train loss: 0.9901 | Train acc: 50.58% | Val loss: 0.9606 | Val acc: 53.03% | LR: 0.000913
Epoch: 009 | Train loss: 0.9958 | Train acc: 50.44% | Val loss: 0.9755 | Val acc: 52.60% | LR: 0.000911
Epoch: 010 | Train loss: 0.9842 | Train acc: 51.01% | Val loss: 0.9700 | Val acc: 52.60% | LR: 0.000909
Epoch: 011 | Train loss: 0.9769 | Train acc: 51.70% | Val loss: 0.9758 | Val acc: 51.96% | LR: 0.000906
Epoch: 012 | Train loss: 0.9905 | Train acc: 50.38% | Val loss: 0.9772 | Val acc: 51.76% | LR: 0.000904
Epoch: 013 | Train loss: 0.9721 | Train acc: 52.11% | Val loss: 0.9782 | Val acc: 51.50% | LR: 0.000901
Epoch: 014 | Train loss: 0.9770 | Train acc: 51.42% | Val loss: 0.9765 | Val acc: 51.44% | LR: 0.000898
Epoch: 015 | Train loss: 0.9818 | Train acc: 51.03% | Val loss: 0.9800 | Val acc: 51.15% | LR: 0.000895
Epoch: 016 | Train loss: 0.9774 | Train acc: 51.30% | Val loss: 0.9673 | Val acc: 52.13% | LR: 0.000892
Epoch: 017 | Train loss: 0.9817 | Train acc: 50.88% | Val loss: 0.9785 | Val acc: 51.11% | LR: 0.000888
Epoch: 018 | Train loss: 0.9801 | Train acc: 50.94% | Val loss: 0.9939 | Val acc: 50.69% | LR: 0.000885
Epoch: 019 | Train loss: 0.9784 | Train acc: 51.44% | Val loss: 1.0006 | Val acc: 50.12% | LR: 0.000881
Epoch: 020 | Train loss: 0.9764 | Train acc: 51.46% | Val loss: 1.0003 | Val acc: 50.05% | LR: 0.000877
Epoch: 021 | Train loss: 0.9827 | Train acc: 50.93% | Val loss: 1.0068 | Val acc: 49.87% | LR: 0.000873
Epoch: 022 | Train loss: 0.9713 | Train acc: 51.68% | Val loss: 1.0011 | Val acc: 50.23% | LR: 0.000868
Epoch: 023 | Train loss: 0.9889 | Train acc: 50.56% | Val loss: 1.0081 | Val acc: 49.88% | LR: 0.000864
Epoch: 024 | Train loss: 0.9793 | Train acc: 51.30% | Val loss: 1.0075 | Val acc: 49.53% | LR: 0.000859
Epoch: 025 | Train loss: 0.9712 | Train acc: 51.65% | Val loss: 1.0213 | Val acc: 48.97% | LR: 0.000854
Epoch: 026 | Train loss: 0.9786 | Train acc: 51.21% | Val loss: 1.0207 | Val acc: 49.40% | LR: 0.000849
Epoch: 027 | Train loss: 0.9850 | Train acc: 50.81% | Val loss: 1.0283 | Val acc: 48.67% | LR: 0.000844
Epoch: 028 | Train loss: 0.9865 | Train acc: 50.73% | Val loss: 1.0134 | Val acc: 49.69% | LR: 0.000838
Epoch: 029 | Train loss: 0.9807 | Train acc: 51.12% | Val loss: 1.0082 | Val acc: 49.67% | LR: 0.000833
Epoch: 030 | Train loss: 0.9680 | Train acc: 51.91% | Val loss: 1.0095 | Val acc: 49.66% | LR: 0.000827
Epoch: 031 | Train loss: 0.9910 | Train acc: 50.40% | Val loss: 1.0085 | Val acc: 49.72% | LR: 0.000821
Epoch: 032 | Train loss: 0.9765 | Train acc: 51.28% | Val loss: 1.0113 | Val acc: 49.64% | LR: 0.000815
Epoch: 033 | Train loss: 0.9774 | Train acc: 51.21% | Val loss: 1.0095 | Val acc: 49.87% | LR: 0.000809
Epoch: 034 | Train loss: 0.9885 | Train acc: 50.66% | Val loss: 1.0189 | Val acc: 49.36% | LR: 0.000803
Epoch: 035 | Train loss: 0.9747 | Train acc: 51.49% | Val loss: 1.0025 | Val acc: 49.99% | LR: 0.000796
Epoch: 036 | Train loss: 0.9810 | Train acc: 51.02% | Val loss: 1.0129 | Val acc: 49.42% | LR: 0.000789
Epoch: 037 | Train loss: 0.9867 | Train acc: 50.61% | Val loss: 0.9930 | Val acc: 50.47% | LR: 0.000783
Epoch: 038 | Train loss: 0.9821 | Train acc: 51.05% | Val loss: 1.0052 | Val acc: 49.80% | LR: 0.000776
Epoch: 039 | Train loss: 0.9846 | Train acc: 50.79% | Val loss: 0.9988 | Val acc: 50.02% | LR: 0.000769
Epoch: 040 | Train loss: 0.9829 | Train acc: 50.98% | Val loss: 1.0072 | Val acc: 49.89% | LR: 0.000761
Epoch: 041 | Train loss: 0.9866 | Train acc: 50.67% | Val loss: 1.0126 | Val acc: 49.54% | LR: 0.000754
Epoch: 042 | Train loss: 0.9780 | Train acc: 51.33% | Val loss: 1.0099 | Val acc: 49.83% | LR: 0.000747
Epoch: 043 | Train loss: 0.9707 | Train acc: 51.58% | Val loss: 1.0088 | Val acc: 49.97% | LR: 0.000739
Epoch: 044 | Train loss: 0.9839 | Train acc: 50.91% | Val loss: 1.0086 | Val acc: 49.95% | LR: 0.000731
Epoch: 045 | Train loss: 0.9629 | Train acc: 52.09% | Val loss: 1.0017 | Val acc: 50.23% | LR: 0.000723
Epoch: 046 | Train loss: 0.9715 | Train acc: 51.52% | Val loss: 1.0066 | Val acc: 50.03% | LR: 0.000715
Epoch: 047 | Train loss: 0.9710 | Train acc: 51.53% | Val loss: 1.0031 | Val acc: 50.16% | LR: 0.000707
Epoch: 048 | Train loss: 0.9691 | Train acc: 51.64% | Val loss: 1.0092 | Val acc: 50.04% | LR: 0.000699
Epoch: 049 | Train loss: 0.9672 | Train acc: 51.72% | Val loss: 1.0013 | Val acc: 50.24% | LR: 0.000691

[I 2025-09-23 16:22:59,815] Trial 13 finished with value: 0.5007765829563141 and parameters: {'lr': 0.0009207292273752499, 'hidden_size': 99, 'dropout': 0.3743516638045155, 'weight_decay': 8.337724905429164e-06}. Best is trial 10 with value: 0.5360925793647766.

Epoch: 000 | Train loss: 1.0009 | Train acc: 49.84% | Val loss: 1.0051 | Val acc: 45.93% | LR: 0.000108
Epoch: 001 | Train loss: 1.0030 | Train acc: 50.01% | Val loss: 1.0072 | Val acc: 45.95% | LR: 0.000108
Epoch: 002 | Train loss: 1.0070 | Train acc: 49.99% | Val loss: 1.0100 | Val acc: 45.85% | LR: 0.000108
Epoch: 003 | Train loss: 1.0016 | Train acc: 49.25% | Val loss: 1.0047 | Val acc: 46.09% | LR: 0.000108
Epoch: 004 | Train loss: 1.0009 | Train acc: 49.75% | Val loss: 1.0050 | Val acc: 45.91% | LR: 0.000108
Epoch: 005 | Train loss: 1.0002 | Train acc: 50.18% | Val loss: 1.0067 | Val acc: 45.99% | LR: 0.000107
Epoch: 006 | Train loss: 0.9999 | Train acc: 49.69% | Val loss: 1.0085 | Val acc: 46.09% | LR: 0.000107
Epoch: 007 | Train loss: 0.9992 | Train acc: 49.99% | Val loss: 1.0065 | Val acc: 46.73% | LR: 0.000107
Epoch: 008 | Train loss: 1.0025 | Train acc: 50.20% | Val loss: 1.0116 | Val acc: 46.89% | LR: 0.000107
Epoch: 009 | Train loss: 1.0046 | Train acc: 50.03% | Val loss: 1.0167 | Val acc: 46.28% | LR: 0.000107
Epoch: 010 | Train loss: 1.0159 | Train acc: 50.98% | Val loss: 1.0241 | Val acc: 47.02% | LR: 0.000106
Epoch: 011 | Train loss: 0.9941 | Train acc: 51.10% | Val loss: 1.0064 | Val acc: 47.10% | LR: 0.000106
Epoch: 012 | Train loss: 1.0036 | Train acc: 49.91% | Val loss: 1.0086 | Val acc: 45.83% | LR: 0.000106
Epoch: 013 | Train loss: 0.9957 | Train acc: 50.48% | Val loss: 1.0052 | Val acc: 46.07% | LR: 0.000106
Epoch: 014 | Train loss: 0.9897 | Train acc: 51.05% | Val loss: 1.0086 | Val acc: 45.76% | LR: 0.000105
Epoch: 015 | Train loss: 0.9985 | Train acc: 49.97% | Val loss: 1.0061 | Val acc: 46.09% | LR: 0.000105
Epoch: 016 | Train loss: 0.9933 | Train acc: 50.50% | Val loss: 1.0154 | Val acc: 46.41% | LR: 0.000105
Epoch: 017 | Train loss: 0.9892 | Train acc: 50.74% | Val loss: 1.0420 | Val acc: 46.60% | LR: 0.000104
Epoch: 018 | Train loss: 0.9840 | Train acc: 51.21% | Val loss: 1.0024 | Val acc: 46.87% | LR: 0.000104
Epoch: 019 | Train loss: 0.9982 | Train acc: 50.35% | Val loss: 1.0031 | Val acc: 47.00% | LR: 0.000103
Epoch: 020 | Train loss: 0.9892 | Train acc: 50.80% | Val loss: 9.0091 | Val acc: 47.59% | LR: 0.000103
Epoch: 021 | Train loss: 0.9888 | Train acc: 50.78% | Val loss: 1.0031 | Val acc: 48.12% | LR: 0.000102
Epoch: 022 | Train loss: 0.9901 | Train acc: 51.04% | Val loss: 1.0165 | Val acc: 48.32% | LR: 0.000102
Epoch: 023 | Train loss: 0.9940 | Train acc: 50.82% | Val loss: 1.0062 | Val acc: 49.19% | LR: 0.000101
Epoch: 024 | Train loss: 0.9935 | Train acc: 50.82% | Val loss: 1.0018 | Val acc: 50.38% | LR: 0.000101
Epoch: 025 | Train loss: 1.0080 | Train acc: 50.59% | Val loss: 1.0252 | Val acc: 50.14% | LR: 0.000100
Epoch: 026 | Train loss: 0.9872 | Train acc: 51.09% | Val loss: 1.0559 | Val acc: 50.36% | LR: 0.000100
Epoch: 027 | Train loss: 0.9847 | Train acc: 51.16% | Val loss: 1.0148 | Val acc: 50.58% | LR: 0.000099
Epoch: 028 | Train loss: 0.9896 | Train acc: 50.77% | Val loss: 1.0443 | Val acc: 50.51% | LR: 0.000098
Epoch: 029 | Train loss: 0.9866 | Train acc: 51.03% | Val loss: 1.0008 | Val acc: 51.26% | LR: 0.000098
Epoch: 030 | Train loss: 0.9939 | Train acc: 50.70% | Val loss: 0.9975 | Val acc: 51.00% | LR: 0.000097
Epoch: 031 | Train loss: 0.9777 | Train acc: 51.69% | Val loss: 1.0017 | Val acc: 50.84% | LR: 0.000096
Epoch: 032 | Train loss: 0.9877 | Train acc: 51.13% | Val loss: 1.0131 | Val acc: 51.04% | LR: 0.000096
Epoch: 033 | Train loss: 0.9874 | Train acc: 50.98% | Val loss: 1.0047 | Val acc: 50.70% | LR: 0.000095
Epoch: 034 | Train loss: 0.9892 | Train acc: 50.81% | Val loss: 1.0302 | Val acc: 50.86% | LR: 0.000094
Epoch: 035 | Train loss: 0.9924 | Train acc: 50.72% | Val loss: 1.0024 | Val acc: 51.17% | LR: 0.000093
Epoch: 036 | Train loss: 1.0046 | Train acc: 50.72% | Val loss: 0.9978 | Val acc: 51.57% | LR: 0.000093
Epoch: 037 | Train loss: 0.9840 | Train acc: 51.07% | Val loss: 0.9986 | Val acc: 51.70% | LR: 0.000092
Epoch: 038 | Train loss: 0.9896 | Train acc: 50.72% | Val loss: 1.0016 | Val acc: 51.51% | LR: 0.000091
Epoch: 039 | Train loss: 0.9877 | Train acc: 50.94% | Val loss: 1.0282 | Val acc: 52.02% | LR: 0.000090
Epoch: 040 | Train loss: 0.9878 | Train acc: 50.97% | Val loss: 0.9897 | Val acc: 51.78% | LR: 0.000089
Epoch: 041 | Train loss: 0.9897 | Train acc: 50.71% | Val loss: 0.9923 | Val acc: 51.89% | LR: 0.000089
Epoch: 042 | Train loss: 0.9866 | Train acc: 51.01% | Val loss: 0.9914 | Val acc: 51.62% | LR: 0.000088
Epoch: 043 | Train loss: 0.9924 | Train acc: 50.70% | Val loss: 0.9892 | Val acc: 51.78% | LR: 0.000087
Epoch: 044 | Train loss: 0.9887 | Train acc: 50.70% | Val loss: 0.9824 | Val acc: 51.82% | LR: 0.000086
Epoch: 045 | Train loss: 0.9808 | Train acc: 51.26% | Val loss: 0.9853 | Val acc: 51.84% | LR: 0.000085
Epoch: 046 | Train loss: 0.9842 | Train acc: 51.01% | Val loss: 0.9853 | Val acc: 51.67% | LR: 0.000084
Epoch: 047 | Train loss: 0.9814 | Train acc: 51.07% | Val loss: 0.9960 | Val acc: 51.62% | LR: 0.000083
Epoch: 048 | Train loss: 0.9861 | Train acc: 50.90% | Val loss: 0.9887 | Val acc: 51.58% | LR: 0.000082
Epoch: 049 | Train loss: 0.9855 | Train acc: 50.92% | Val loss: 0.9863 | Val acc: 51.83% | LR: 0.000081
Epoch: 050 | Train loss: 0.9937 | Train acc: 50.39% | Val loss: 1.0044 | Val acc: 51.49% | LR: 0.000080
Epoch: 051 | Train loss: 0.9908 | Train acc: 50.56% | Val loss: 1.0069 | Val acc: 51.59% | LR: 0.000079
Epoch: 052 | Train loss: 0.9882 | Train acc: 50.66% | Val loss: 0.9838 | Val acc: 51.55% | LR: 0.000078
Epoch: 053 | Train loss: 0.9855 | Train acc: 50.91% | Val loss: 0.9911 | Val acc: 51.47% | LR: 0.000077
Epoch: 054 | Train loss: 0.9925 | Train acc: 50.38% | Val loss: 0.9848 | Val acc: 51.24% | LR: 0.000076
Epoch: 055 | Train loss: 0.9795 | Train acc: 51.14% | Val loss: 0.9803 | Val acc: 51.63% | LR: 0.000075
Epoch: 056 | Train loss: 0.9866 | Train acc: 50.73% | Val loss: 0.9852 | Val acc: 51.16% | LR: 0.000074
Epoch: 057 | Train loss: 0.9840 | Train acc: 51.03% | Val loss: 0.9849 | Val acc: 51.59% | LR: 0.000073
Epoch: 058 | Train loss: 0.9928 | Train acc: 50.40% | Val loss: 0.9834 | Val acc: 51.38% | LR: 0.000072
Epoch: 059 | Train loss: 0.9818 | Train acc: 51.10% | Val loss: 0.9843 | Val acc: 51.26% | LR: 0.000071
Epoch: 060 | Train loss: 0.9850 | Train acc: 50.83% | Val loss: 0.9843 | Val acc: 51.42% | LR: 0.000070
Epoch: 061 | Train loss: 0.9830 | Train acc: 51.10% | Val loss: 0.9858 | Val acc: 51.17% | LR: 0.000069
Epoch: 062 | Train loss: 0.9852 | Train acc: 50.88% | Val loss: 0.9852 | Val acc: 51.38% | LR: 0.000068
Epoch: 063 | Train loss: 0.9955 | Train acc: 50.24% | Val loss: 0.9854 | Val acc: 51.22% | LR: 0.000067
Epoch: 064 | Train loss: 0.9902 | Train acc: 50.48% | Val loss: 0.9850 | Val acc: 51.15% | LR: 0.000066
Epoch: 065 | Train loss: 0.9841 | Train acc: 50.96% | Val loss: 0.9838 | Val acc: 51.64% | LR: 0.000064
Epoch: 066 | Train loss: 0.9890 | Train acc: 50.60% | Val loss: 0.9897 | Val acc: 51.26% | LR: 0.000063
Epoch: 067 | Train loss: 0.9850 | Train acc: 50.75% | Val loss: 0.9834 | Val acc: 51.30% | LR: 0.000062
Epoch: 068 | Train loss: 0.9860 | Train acc: 50.81% | Val loss: 0.9832 | Val acc: 51.54% | LR: 0.000061
Epoch: 069 | Train loss: 0.9781 | Train acc: 51.38% | Val loss: 1.0152 | Val acc: 51.46% | LR: 0.000060
Epoch: 070 | Train loss: 0.9825 | Train acc: 50.99% | Val loss: 0.9800 | Val acc: 51.41% | LR: 0.000059
Epoch: 071 | Train loss: 0.9867 | Train acc: 50.76% | Val loss: 0.9821 | Val acc: 51.51% | LR: 0.000058
Epoch: 072 | Train loss: 0.9906 | Train acc: 50.49% | Val loss: 0.9805 | Val acc: 51.45% | LR: 0.000057
Epoch: 073 | Train loss: 0.9911 | Train acc: 50.50% | Val loss: 0.9807 | Val acc: 51.51% | LR: 0.000056
Epoch: 074 | Train loss: 0.9823 | Train acc: 51.03% | Val loss: 0.9781 | Val acc: 51.43% | LR: 0.000054
Epoch: 075 | Train loss: 0.9847 | Train acc: 50.94% | Val loss: 0.9779 | Val acc: 51.70% | LR: 0.000053
Epoch: 076 | Train loss: 0.9846 | Train acc: 50.83% | Val loss: 0.9778 | Val acc: 51.70% | LR: 0.000052
Epoch: 077 | Train loss: 0.9737 | Train acc: 51.55% | Val loss: 0.9786 | Val acc: 51.52% | LR: 0.000051
Epoch: 078 | Train loss: 0.9859 | Train acc: 50.82% | Val loss: 0.9765 | Val acc: 51.54% | LR: 0.000050
Epoch: 079 | Train loss: 0.9951 | Train acc: 50.14% | Val loss: 0.9763 | Val acc: 51.56% | LR: 0.000049
Epoch: 080 | Train loss: 0.9892 | Train acc: 50.49% | Val loss: 0.9767 | Val acc: 51.48% | LR: 0.000048
Epoch: 081 | Train loss: 0.9819 | Train acc: 50.92% | Val loss: 0.9823 | Val acc: 51.60% | LR: 0.000047
Epoch: 082 | Train loss: 0.9854 | Train acc: 50.74% | Val loss: 0.9772 | Val acc: 51.62% | LR: 0.000046
Epoch: 083 | Train loss: 0.9874 | Train acc: 50.75% | Val loss: 0.9842 | Val acc: 51.60% | LR: 0.000044
Epoch: 084 | Train loss: 0.9798 | Train acc: 51.11% | Val loss: 0.9762 | Val acc: 51.76% | LR: 0.000043
Epoch: 085 | Train loss: 0.9796 | Train acc: 51.08% | Val loss: 0.9778 | Val acc: 51.52% | LR: 0.000042
Epoch: 086 | Train loss: 0.9854 | Train acc: 50.77% | Val loss: 0.9768 | Val acc: 51.42% | LR: 0.000041
Epoch: 087 | Train loss: 0.9788 | Train acc: 51.22% | Val loss: 0.9765 | Val acc: 51.44% | LR: 0.000040
Epoch: 088 | Train loss: 0.9881 | Train acc: 50.68% | Val loss: 0.9786 | Val acc: 51.42% | LR: 0.000039

[I 2025-09-23 16:24:54,255] Trial 14 finished with value: 0.5149478077888489 and parameters: {'lr': 0.00010789919606477493, 'hidden_size': 151, 'dropout': 0.42048644922119827, 'weight_decay': 7.066884063273501e-06}. Best is trial 10 with value: 0.5360925793647766.

Epoch: 000 | Train loss: 1.0009 | Train acc: 50.27% | Val loss: 0.9962 | Val acc: 53.96% | LR: 0.000115
Epoch: 001 | Train loss: 1.0019 | Train acc: 50.10% | Val loss: 0.9957 | Val acc: 54.05% | LR: 0.000115
Epoch: 002 | Train loss: 1.0042 | Train acc: 49.81% | Val loss: 0.9963 | Val acc: 53.77% | LR: 0.000115
Epoch: 003 | Train loss: 0.9990 | Train acc: 50.40% | Val loss: 0.9920 | Val acc: 54.05% | LR: 0.000115
Epoch: 004 | Train loss: 1.0004 | Train acc: 49.76% | Val loss: 0.9923 | Val acc: 54.05% | LR: 0.000115
Epoch: 005 | Train loss: 1.0041 | Train acc: 50.28% | Val loss: 0.9925 | Val acc: 54.05% | LR: 0.000115
Epoch: 006 | Train loss: 1.0848 | Train acc: 50.34% | Val loss: 0.9926 | Val acc: 54.05% | LR: 0.000115
Epoch: 007 | Train loss: 0.9987 | Train acc: 50.35% | Val loss: 0.9926 | Val acc: 54.05% | LR: 0.000114
Epoch: 008 | Train loss: 0.9981 | Train acc: 50.27% | Val loss: 0.9927 | Val acc: 54.05% | LR: 0.000114
Epoch: 009 | Train loss: 0.9957 | Train acc: 50.98% | Val loss: 0.9929 | Val acc: 54.07% | LR: 0.000114
Epoch: 010 | Train loss: 0.9976 | Train acc: 50.53% | Val loss: 0.9930 | Val acc: 54.28% | LR: 0.000114
Epoch: 011 | Train loss: 0.9982 | Train acc: 50.18% | Val loss: 0.9928 | Val acc: 54.38% | LR: 0.000113
Epoch: 012 | Train loss: 0.9986 | Train acc: 49.92% | Val loss: 0.9929 | Val acc: 54.46% | LR: 0.000113
Epoch: 013 | Train loss: 0.9987 | Train acc: 50.04% | Val loss: 0.9931 | Val acc: 54.54% | LR: 0.000113
Epoch: 014 | Train loss: 1.0033 | Train acc: 49.46% | Val loss: 0.9932 | Val acc: 54.19% | LR: 0.000112
Epoch: 015 | Train loss: 0.9934 | Train acc: 50.80% | Val loss: 0.9931 | Val acc: 54.39% | LR: 0.000112
Epoch: 016 | Train loss: 0.9950 | Train acc: 50.59% | Val loss: 0.9934 | Val acc: 54.54% | LR: 0.000112
Epoch: 017 | Train loss: 0.9917 | Train acc: 51.06% | Val loss: 0.9933 | Val acc: 54.42% | LR: 0.000111
Epoch: 018 | Train loss: 0.9922 | Train acc: 50.87% | Val loss: 0.9934 | Val acc: 54.60% | LR: 0.000111
Epoch: 019 | Train loss: 0.9973 | Train acc: 50.45% | Val loss: 0.9934 | Val acc: 54.38% | LR: 0.000110
Epoch: 020 | Train loss: 0.9898 | Train acc: 51.13% | Val loss: 0.9934 | Val acc: 54.40% | LR: 0.000110
Epoch: 021 | Train loss: 0.9900 | Train acc: 50.90% | Val loss: 0.9934 | Val acc: 54.01% | LR: 0.000109
Epoch: 022 | Train loss: 0.9898 | Train acc: 51.13% | Val loss: 0.9934 | Val acc: 53.65% | LR: 0.000109
Epoch: 023 | Train loss: 0.9860 | Train acc: 51.17% | Val loss: 0.9934 | Val acc: 53.08% | LR: 0.000108
Epoch: 024 | Train loss: 0.9985 | Train acc: 50.18% | Val loss: 0.9935 | Val acc: 52.80% | LR: 0.000108
Epoch: 025 | Train loss: 0.9899 | Train acc: 50.75% | Val loss: 0.9935 | Val acc: 53.15% | LR: 0.000107
Epoch: 026 | Train loss: 0.9853 | Train acc: 51.12% | Val loss: 0.9931 | Val acc: 53.03% | LR: 0.000106
Epoch: 027 | Train loss: 0.9921 | Train acc: 50.69% | Val loss: 0.9930 | Val acc: 52.61% | LR: 0.000106
Epoch: 028 | Train loss: 0.9794 | Train acc: 51.38% | Val loss: 0.9927 | Val acc: 52.50% | LR: 0.000105
Epoch: 029 | Train loss: 0.9910 | Train acc: 50.83% | Val loss: 0.9922 | Val acc: 52.42% | LR: 0.000104
Epoch: 030 | Train loss: 0.9998 | Train acc: 50.23% | Val loss: 0.9913 | Val acc: 52.49% | LR: 0.000104
Epoch: 031 | Train loss: 0.9932 | Train acc: 50.67% | Val loss: 0.9906 | Val acc: 52.27% | LR: 0.000103
Epoch: 032 | Train loss: 0.9962 | Train acc: 50.31% | Val loss: 0.9900 | Val acc: 52.25% | LR: 0.000102
Epoch: 033 | Train loss: 0.9940 | Train acc: 50.39% | Val loss: 0.9892 | Val acc: 52.31% | LR: 0.000101
Epoch: 034 | Train loss: 0.9926 | Train acc: 50.86% | Val loss: 0.9892 | Val acc: 52.38% | LR: 0.000101
Epoch: 035 | Train loss: 0.9923 | Train acc: 50.88% | Val loss: 0.9883 | Val acc: 52.22% | LR: 0.000100
Epoch: 036 | Train loss: 0.9853 | Train acc: 51.05% | Val loss: 0.9879 | Val acc: 52.02% | LR: 0.000099
Epoch: 037 | Train loss: 0.9837 | Train acc: 51.13% | Val loss: 0.9869 | Val acc: 51.92% | LR: 0.000098
Epoch: 038 | Train loss: 0.9825 | Train acc: 51.24% | Val loss: 0.9853 | Val acc: 51.96% | LR: 0.000097
Epoch: 039 | Train loss: 0.9882 | Train acc: 50.79% | Val loss: 0.9833 | Val acc: 51.88% | LR: 0.000096
Epoch: 040 | Train loss: 0.9894 | Train acc: 50.69% | Val loss: 0.9813 | Val acc: 51.82% | LR: 0.000095
Epoch: 041 | Train loss: 0.9910 | Train acc: 50.69% | Val loss: 0.9779 | Val acc: 51.64% | LR: 0.000094
Epoch: 042 | Train loss: 0.9779 | Train acc: 51.39% | Val loss: 0.9759 | Val acc: 51.73% | LR: 0.000094
Epoch: 043 | Train loss: 0.9785 | Train acc: 51.38% | Val loss: 0.9769 | Val acc: 51.55% | LR: 0.000093
Epoch: 044 | Train loss: 0.9913 | Train acc: 50.52% | Val loss: 0.9796 | Val acc: 51.43% | LR: 0.000092
Epoch: 045 | Train loss: 0.9907 | Train acc: 50.59% | Val loss: 0.9797 | Val acc: 51.27% | LR: 0.000091
Epoch: 046 | Train loss: 0.9841 | Train acc: 50.86% | Val loss: 0.9799 | Val acc: 51.25% | LR: 0.000090
Epoch: 047 | Train loss: 0.9786 | Train acc: 51.31% | Val loss: 0.9805 | Val acc: 51.17% | LR: 0.000089
Epoch: 048 | Train loss: 0.9891 | Train acc: 50.58% | Val loss: 0.9827 | Val acc: 50.93% | LR: 0.000088
Epoch: 049 | Train loss: 0.9889 | Train acc: 50.60% | Val loss: 0.9841 | Val acc: 50.90% | LR: 0.000087
Epoch: 050 | Train loss: 0.9813 | Train acc: 51.05% | Val loss: 0.9849 | Val acc: 51.11% | LR: 0.000086
Epoch: 051 | Train loss: 0.9845 | Train acc: 50.88% | Val loss: 0.9852 | Val acc: 51.21% | LR: 0.000085
Epoch: 052 | Train loss: 0.9865 | Train acc: 50.70% | Val loss: 0.9859 | Val acc: 51.11% | LR: 0.000083
Epoch: 053 | Train loss: 0.9849 | Train acc: 50.81% | Val loss: 0.9864 | Val acc: 50.93% | LR: 0.000082
Epoch: 054 | Train loss: 0.9834 | Train acc: 50.95% | Val loss: 0.9883 | Val acc: 50.69% | LR: 0.000081
Epoch: 055 | Train loss: 0.9845 | Train acc: 50.95% | Val loss: 0.9892 | Val acc: 50.71% | LR: 0.000080
Epoch: 056 | Train loss: 0.9853 | Train acc: 50.79% | Val loss: 0.9893 | Val acc: 50.67% | LR: 0.000079
Epoch: 057 | Train loss: 0.9868 | Train acc: 50.72% | Val loss: 0.9917 | Val acc: 50.52% | LR: 0.000078
Epoch: 058 | Train loss: 0.9808 | Train acc: 51.16% | Val loss: 0.9918 | Val acc: 50.54% | LR: 0.000077
Epoch: 059 | Train loss: 0.9863 | Train acc: 50.81% | Val loss: 0.9913 | Val acc: 50.59% | LR: 0.000076
Epoch: 060 | Train loss: 0.9781 | Train acc: 51.25% | Val loss: 0.9921 | Val acc: 50.55% | LR: 0.000075
Epoch: 061 | Train loss: 0.9751 | Train acc: 51.34% | Val loss: 0.9916 | Val acc: 50.61% | LR: 0.000073
Epoch: 062 | Train loss: 0.9868 | Train acc: 50.81% | Val loss: 0.9920 | Val acc: 50.57% | LR: 0.000072
Epoch: 063 | Train loss: 0.9861 | Train acc: 50.72% | Val loss: 0.9923 | Val acc: 50.61% | LR: 0.000071
Epoch: 064 | Train loss: 0.9753 | Train acc: 51.27% | Val loss: 0.9966 | Val acc: 50.30% | LR: 0.000070
Epoch: 065 | Train loss: 0.9836 | Train acc: 50.90% | Val loss: 0.9984 | Val acc: 50.18% | LR: 0.000069
Epoch: 066 | Train loss: 0.9864 | Train acc: 50.73% | Val loss: 0.9988 | Val acc: 50.16% | LR: 0.000068
Epoch: 067 | Train loss: 0.9910 | Train acc: 50.40% | Val loss: 1.0020 | Val acc: 49.58% | LR: 0.000066

[I 2025-09-23 16:25:51,379] Trial 15 finished with value: 0.4961083889007568 and parameters: {'lr': 0.00011516706748617036, 'hidden_size': 84, 'dropout': 0.3145400072137249, 'weight_decay': 2.1833786122843687e-05}. Best is trial 10 with value: 0.5360925793647766.

Epoch: 000 | Train loss: 0.9973 | Train acc: 50.76% | Val loss: 0.9968 | Val acc: 51.13% | LR: 0.001039
Epoch: 001 | Train loss: 0.9938 | Train acc: 51.51% | Val loss: 0.9909 | Val acc: 51.93% | LR: 0.001038
Epoch: 002 | Train loss: 0.9906 | Train acc: 50.72% | Val loss: 1.0076 | Val acc: 51.24% | LR: 0.001038
Epoch: 003 | Train loss: 0.9853 | Train acc: 51.13% | Val loss: 0.9746 | Val acc: 51.86% | LR: 0.001037
Epoch: 004 | Train loss: 0.9907 | Train acc: 50.86% | Val loss: 0.9490 | Val acc: 52.86% | LR: 0.001036
Epoch: 005 | Train loss: 1.0001 | Train acc: 50.82% | Val loss: 0.9870 | Val acc: 52.26% | LR: 0.001035
Epoch: 006 | Train loss: 0.9882 | Train acc: 50.77% | Val loss: 0.9721 | Val acc: 52.19% | LR: 0.001033
Epoch: 007 | Train loss: 0.9816 | Train acc: 51.28% | Val loss: 0.9893 | Val acc: 51.25% | LR: 0.001031
Epoch: 008 | Train loss: 0.9860 | Train acc: 51.35% | Val loss: 0.9842 | Val acc: 51.17% | LR: 0.001030
Epoch: 009 | Train loss: 0.9793 | Train acc: 51.22% | Val loss: 0.9933 | Val acc: 50.57% | LR: 0.001027
Epoch: 010 | Train loss: 0.9944 | Train acc: 50.83% | Val loss: 1.3478 | Val acc: 50.48% | LR: 0.001025
Epoch: 011 | Train loss: 0.9922 | Train acc: 51.07% | Val loss: 1.0506 | Val acc: 50.04% | LR: 0.001022
Epoch: 012 | Train loss: 0.9910 | Train acc: 50.68% | Val loss: 1.0216 | Val acc: 49.31% | LR: 0.001020
Epoch: 013 | Train loss: 0.9917 | Train acc: 50.65% | Val loss: 0.9705 | Val acc: 51.70% | LR: 0.001017
Epoch: 014 | Train loss: 0.9902 | Train acc: 50.61% | Val loss: 1.0045 | Val acc: 50.24% | LR: 0.001013
Epoch: 015 | Train loss: 0.9877 | Train acc: 50.75% | Val loss: 1.0292 | Val acc: 49.60% | LR: 0.001010
Epoch: 016 | Train loss: 1.0049 | Train acc: 50.84% | Val loss: 1.0461 | Val acc: 47.44% | LR: 0.001006
Epoch: 017 | Train loss: 0.9923 | Train acc: 50.69% | Val loss: 1.0300 | Val acc: 49.42% | LR: 0.001002
Epoch: 018 | Train loss: 0.9854 | Train acc: 51.03% | Val loss: 1.0342 | Val acc: 48.72% | LR: 0.000998
Epoch: 019 | Train loss: 0.9906 | Train acc: 50.89% | Val loss: 1.0256 | Val acc: 48.17% | LR: 0.000994
Epoch: 020 | Train loss: 0.9873 | Train acc: 50.77% | Val loss: 1.0440 | Val acc: 47.42% | LR: 0.000989
Epoch: 021 | Train loss: 0.9879 | Train acc: 50.72% | Val loss: 1.0308 | Val acc: 48.19% | LR: 0.000985
Epoch: 022 | Train loss: 0.9878 | Train acc: 50.97% | Val loss: 1.0236 | Val acc: 48.68% | LR: 0.000980
Epoch: 023 | Train loss: 0.9880 | Train acc: 50.71% | Val loss: 1.0366 | Val acc: 48.89% | LR: 0.000975
Epoch: 024 | Train loss: 0.9867 | Train acc: 50.86% | Val loss: 1.0138 | Val acc: 49.31% | LR: 0.000969
Epoch: 025 | Train loss: 0.9776 | Train acc: 51.40% | Val loss: 1.0171 | Val acc: 49.31% | LR: 0.000964
Epoch: 026 | Train loss: 0.9943 | Train acc: 50.37% | Val loss: 1.0043 | Val acc: 49.38% | LR: 0.000958
Epoch: 027 | Train loss: 0.9788 | Train acc: 51.41% | Val loss: 0.9786 | Val acc: 51.65% | LR: 0.000952
Epoch: 028 | Train loss: 0.9860 | Train acc: 50.96% | Val loss: 1.0013 | Val acc: 49.90% | LR: 0.000946
Epoch: 029 | Train loss: 0.9853 | Train acc: 50.76% | Val loss: 0.9964 | Val acc: 50.67% | LR: 0.000940
Epoch: 030 | Train loss: 0.9803 | Train acc: 51.16% | Val loss: 1.0026 | Val acc: 50.12% | LR: 0.000933
Epoch: 031 | Train loss: 0.9796 | Train acc: 51.12% | Val loss: 0.9927 | Val acc: 50.73% | LR: 0.000927
Epoch: 032 | Train loss: 0.9896 | Train acc: 50.61% | Val loss: 1.0006 | Val acc: 50.25% | LR: 0.000920
Epoch: 033 | Train loss: 0.9801 | Train acc: 51.49% | Val loss: 0.9927 | Val acc: 50.61% | LR: 0.000913
Epoch: 034 | Train loss: 0.9816 | Train acc: 51.00% | Val loss: 1.0060 | Val acc: 50.49% | LR: 0.000905
Epoch: 035 | Train loss: 0.9820 | Train acc: 51.10% | Val loss: 0.9957 | Val acc: 50.59% | LR: 0.000898
Epoch: 036 | Train loss: 0.9821 | Train acc: 51.06% | Val loss: 1.0070 | Val acc: 50.10% | LR: 0.000891
Epoch: 037 | Train loss: 0.9863 | Train acc: 50.85% | Val loss: 0.9985 | Val acc: 50.09% | LR: 0.000883
Epoch: 038 | Train loss: 0.9790 | Train acc: 51.19% | Val loss: 0.9913 | Val acc: 50.59% | LR: 0.000875
Epoch: 039 | Train loss: 0.9729 | Train acc: 51.54% | Val loss: 0.9950 | Val acc: 50.35% | LR: 0.000867
Epoch: 040 | Train loss: 0.9867 | Train acc: 50.74% | Val loss: 0.9907 | Val acc: 50.61% | LR: 0.000859
Epoch: 041 | Train loss: 0.9768 | Train acc: 51.29% | Val loss: 1.0086 | Val acc: 50.65% | LR: 0.000851
Epoch: 042 | Train loss: 0.9823 | Train acc: 50.93% | Val loss: 1.0049 | Val acc: 50.31% | LR: 0.000842
Epoch: 043 | Train loss: 0.9842 | Train acc: 50.94% | Val loss: 0.9938 | Val acc: 50.35% | LR: 0.000834
Epoch: 044 | Train loss: 0.9866 | Train acc: 50.62% | Val loss: 0.9977 | Val acc: 50.48% | LR: 0.000825
Epoch: 045 | Train loss: 0.9817 | Train acc: 51.10% | Val loss: 1.0002 | Val acc: 50.32% | LR: 0.000816
Epoch: 046 | Train loss: 0.9836 | Train acc: 50.93% | Val loss: 1.0128 | Val acc: 49.33% | LR: 0.000807
Epoch: 047 | Train loss: 0.9845 | Train acc: 50.91% | Val loss: 1.0166 | Val acc: 49.20% | LR: 0.000798
Epoch: 048 | Train loss: 0.9704 | Train acc: 51.76% | Val loss: 1.0078 | Val acc: 49.87% | LR: 0.000789
Epoch: 049 | Train loss: 0.9840 | Train acc: 50.86% | Val loss: 0.9991 | Val acc: 50.38% | LR: 0.000779
Epoch: 050 | Train loss: 0.9782 | Train acc: 51.20% | Val loss: 1.0030 | Val acc: 50.30% | LR: 0.000770
Epoch: 051 | Train loss: 0.9820 | Train acc: 50.94% | Val loss: 0.9992 | Val acc: 50.40% | LR: 0.000760
Epoch: 052 | Train loss: 0.9810 | Train acc: 51.01% | Val loss: 1.0034 | Val acc: 50.25% | LR: 0.000751
Epoch: 053 | Train loss: 0.9786 | Train acc: 51.14% | Val loss: 1.0047 | Val acc: 50.38% | LR: 0.000741

[I 2025-09-23 16:27:08,942] Trial 16 finished with value: 0.5014009296894073 and parameters: {'lr': 0.0010387617999334316, 'hidden_size': 158, 'dropout': 0.3238471073720943, 'weight_decay': 2.779620820277425e-06}. Best is trial 10 with value: 0.5360925793647766.

Epoch: 000 | Train loss: 0.9980 | Train acc: 50.20% | Val loss: 0.9973 | Val acc: 51.32% | LR: 0.000680
Epoch: 001 | Train loss: 0.9927 | Train acc: 50.91% | Val loss: 0.9913 | Val acc: 52.33% | LR: 0.000680
Epoch: 002 | Train loss: 0.9899 | Train acc: 50.89% | Val loss: 0.9785 | Val acc: 52.24% | LR: 0.000679
Epoch: 003 | Train loss: 0.9821 | Train acc: 51.06% | Val loss: 1.0000 | Val acc: 50.07% | LR: 0.000679
Epoch: 004 | Train loss: 0.9860 | Train acc: 50.82% | Val loss: 0.9967 | Val acc: 50.01% | LR: 0.000678
Epoch: 005 | Train loss: 0.9863 | Train acc: 50.89% | Val loss: 0.9964 | Val acc: 50.14% | LR: 0.000677
Epoch: 006 | Train loss: 0.9803 | Train acc: 51.26% | Val loss: 1.0014 | Val acc: 49.78% | LR: 0.000676
Epoch: 007 | Train loss: 0.9839 | Train acc: 50.98% | Val loss: 1.0091 | Val acc: 49.64% | LR: 0.000675
Epoch: 008 | Train loss: 0.9885 | Train acc: 50.85% | Val loss: 1.0258 | Val acc: 50.45% | LR: 0.000674
Epoch: 009 | Train loss: 0.9820 | Train acc: 51.18% | Val loss: 0.9863 | Val acc: 51.12% | LR: 0.000672
Epoch: 010 | Train loss: 0.9911 | Train acc: 50.55% | Val loss: 1.0190 | Val acc: 49.16% | LR: 0.000671
Epoch: 011 | Train loss: 0.9941 | Train acc: 50.45% | Val loss: 1.0435 | Val acc: 48.66% | LR: 0.000669
Epoch: 012 | Train loss: 0.9836 | Train acc: 51.00% | Val loss: 1.0153 | Val acc: 49.58% | LR: 0.000667
Epoch: 013 | Train loss: 0.9914 | Train acc: 50.54% | Val loss: 1.0120 | Val acc: 49.79% | LR: 0.000665
Epoch: 014 | Train loss: 0.9876 | Train acc: 50.90% | Val loss: 1.0127 | Val acc: 49.30% | LR: 0.000663
Epoch: 015 | Train loss: 1.0019 | Train acc: 50.72% | Val loss: 0.9831 | Val acc: 50.95% | LR: 0.000661
Epoch: 016 | Train loss: 0.9838 | Train acc: 51.09% | Val loss: 0.9661 | Val acc: 51.68% | LR: 0.000659
Epoch: 017 | Train loss: 0.9803 | Train acc: 51.23% | Val loss: 1.0190 | Val acc: 51.27% | LR: 0.000656
Epoch: 018 | Train loss: 0.9875 | Train acc: 50.80% | Val loss: 0.9798 | Val acc: 51.20% | LR: 0.000653
Epoch: 019 | Train loss: 0.9987 | Train acc: 50.50% | Val loss: 0.9805 | Val acc: 50.94% | LR: 0.000650
Epoch: 020 | Train loss: 0.9834 | Train acc: 50.98% | Val loss: 0.9875 | Val acc: 50.81% | LR: 0.000647
Epoch: 021 | Train loss: 0.9858 | Train acc: 50.80% | Val loss: 0.9843 | Val acc: 51.35% | LR: 0.000644
Epoch: 022 | Train loss: 0.9832 | Train acc: 51.22% | Val loss: 0.9933 | Val acc: 50.53% | LR: 0.000641
Epoch: 023 | Train loss: 1.1454 | Train acc: 51.07% | Val loss: 0.9797 | Val acc: 51.33% | LR: 0.000638
Epoch: 024 | Train loss: 1.0034 | Train acc: 50.10% | Val loss: 0.9686 | Val acc: 51.57% | LR: 0.000634
Epoch: 025 | Train loss: 0.9767 | Train acc: 51.33% | Val loss: 0.9775 | Val acc: 51.22% | LR: 0.000631
Epoch: 026 | Train loss: 0.9817 | Train acc: 51.08% | Val loss: 0.9626 | Val acc: 51.59% | LR: 0.000627
Epoch: 027 | Train loss: 0.9853 | Train acc: 50.82% | Val loss: 0.9459 | Val acc: 52.89% | LR: 0.000623
Epoch: 028 | Train loss: 0.9870 | Train acc: 50.76% | Val loss: 0.9754 | Val acc: 51.73% | LR: 0.000619
Epoch: 029 | Train loss: 0.9863 | Train acc: 50.86% | Val loss: 0.9925 | Val acc: 50.79% | LR: 0.000615
Epoch: 030 | Train loss: 0.9913 | Train acc: 51.00% | Val loss: 1.0186 | Val acc: 49.31% | LR: 0.000611
Epoch: 031 | Train loss: 0.9854 | Train acc: 50.84% | Val loss: 0.9869 | Val acc: 50.77% | LR: 0.000606
Epoch: 032 | Train loss: 1.0508 | Train acc: 50.88% | Val loss: 1.0217 | Val acc: 49.35% | LR: 0.000602
Epoch: 033 | Train loss: 0.9854 | Train acc: 51.05% | Val loss: 1.0164 | Val acc: 48.69% | LR: 0.000597
Epoch: 034 | Train loss: 0.9864 | Train acc: 51.01% | Val loss: 1.0261 | Val acc: 48.75% | LR: 0.000593
Epoch: 035 | Train loss: 0.9875 | Train acc: 50.91% | Val loss: 1.0347 | Val acc: 48.39% | LR: 0.000588
Epoch: 036 | Train loss: 0.9903 | Train acc: 50.67% | Val loss: 1.0347 | Val acc: 47.47% | LR: 0.000583
Epoch: 037 | Train loss: 0.9882 | Train acc: 50.74% | Val loss: 1.0370 | Val acc: 46.25% | LR: 0.000578
Epoch: 038 | Train loss: 0.9906 | Train acc: 50.43% | Val loss: 1.0393 | Val acc: 45.99% | LR: 0.000573
Epoch: 039 | Train loss: 0.9852 | Train acc: 50.82% | Val loss: 1.0425 | Val acc: 45.95% | LR: 0.000568
Epoch: 040 | Train loss: 0.9959 | Train acc: 50.02% | Val loss: 1.0377 | Val acc: 46.05% | LR: 0.000562
Epoch: 041 | Train loss: 0.9980 | Train acc: 50.02% | Val loss: 1.0354 | Val acc: 46.27% | LR: 0.000557
Epoch: 042 | Train loss: 0.9857 | Train acc: 50.98% | Val loss: 1.0331 | Val acc: 46.54% | LR: 0.000551
Epoch: 043 | Train loss: 0.9914 | Train acc: 50.56% | Val loss: 1.0345 | Val acc: 46.94% | LR: 0.000546
Epoch: 044 | Train loss: 0.9898 | Train acc: 50.56% | Val loss: 1.0327 | Val acc: 47.32% | LR: 0.000540
Epoch: 045 | Train loss: 0.9900 | Train acc: 50.49% | Val loss: 1.0342 | Val acc: 47.36% | LR: 0.000534
Epoch: 046 | Train loss: 0.9830 | Train acc: 50.88% | Val loss: 1.0295 | Val acc: 47.93% | LR: 0.000528
Epoch: 047 | Train loss: 0.9826 | Train acc: 50.99% | Val loss: 1.0236 | Val acc: 48.11% | LR: 0.000522
Epoch: 048 | Train loss: 0.9819 | Train acc: 51.00% | Val loss: 1.0211 | Val acc: 48.16% | LR: 0.000516
Epoch: 049 | Train loss: 0.9784 | Train acc: 51.44% | Val loss: 1.0184 | Val acc: 48.27% | LR: 0.000510
Epoch: 050 | Train loss: 0.9792 | Train acc: 51.25% | Val loss: 1.0200 | Val acc: 48.22% | LR: 0.000504
Epoch: 051 | Train loss: 0.9876 | Train acc: 50.62% | Val loss: 1.0165 | Val acc: 48.18% | LR: 0.000498
Epoch: 052 | Train loss: 0.9813 | Train acc: 51.09% | Val loss: 1.0175 | Val acc: 48.35% | LR: 0.000491
Epoch: 053 | Train loss: 0.9893 | Train acc: 50.50% | Val loss: 1.0156 | Val acc: 48.88% | LR: 0.000485
Epoch: 054 | Train loss: 0.9824 | Train acc: 51.08% | Val loss: 1.0179 | Val acc: 48.90% | LR: 0.000478
Epoch: 055 | Train loss: 0.9819 | Train acc: 50.99% | Val loss: 1.0132 | Val acc: 49.17% | LR: 0.000472
Epoch: 056 | Train loss: 0.9832 | Train acc: 50.91% | Val loss: 1.0040 | Val acc: 49.78% | LR: 0.000465
Epoch: 057 | Train loss: 0.9743 | Train acc: 51.48% | Val loss: 1.0059 | Val acc: 49.60% | LR: 0.000459
Epoch: 058 | Train loss: 0.9791 | Train acc: 51.09% | Val loss: 1.0107 | Val acc: 49.36% | LR: 0.000452
Epoch: 059 | Train loss: 0.9807 | Train acc: 51.25% | Val loss: 1.0080 | Val acc: 49.54% | LR: 0.000445
Epoch: 060 | Train loss: 0.9741 | Train acc: 51.55% | Val loss: 1.0033 | Val acc: 49.91% | LR: 0.000438
Epoch: 061 | Train loss: 0.9856 | Train acc: 50.76% | Val loss: 1.0072 | Val acc: 49.54% | LR: 0.000432
Epoch: 062 | Train loss: 0.9650 | Train acc: 52.07% | Val loss: 1.0100 | Val acc: 49.55% | LR: 0.000425
Epoch: 063 | Train loss: 0.9822 | Train acc: 50.93% | Val loss: 1.0040 | Val acc: 49.74% | LR: 0.000418
Epoch: 064 | Train loss: 0.9744 | Train acc: 51.51% | Val loss: 1.0038 | Val acc: 49.68% | LR: 0.000411
Epoch: 065 | Train loss: 0.9768 | Train acc: 51.20% | Val loss: 1.0013 | Val acc: 49.74% | LR: 0.000404
Epoch: 066 | Train loss: 0.9738 | Train acc: 51.39% | Val loss: 1.0003 | Val acc: 49.90% | LR: 0.000397
Epoch: 067 | Train loss: 0.9822 | Train acc: 50.96% | Val loss: 1.0027 | Val acc: 49.80% | LR: 0.000390
Epoch: 068 | Train loss: 0.9804 | Train acc: 51.06% | Val loss: 1.0099 | Val acc: 49.28% | LR: 0.000383
Epoch: 069 | Train loss: 0.9778 | Train acc: 51.22% | Val loss: 1.0041 | Val acc: 49.62% | LR: 0.000376
Epoch: 070 | Train loss: 0.9816 | Train acc: 51.00% | Val loss: 1.0062 | Val acc: 49.58% | LR: 0.000369
Epoch: 071 | Train loss: 0.9731 | Train acc: 51.54% | Val loss: 1.0021 | Val acc: 49.86% | LR: 0.000362
Epoch: 072 | Train loss: 0.9704 | Train acc: 51.68% | Val loss: 1.0035 | Val acc: 49.84% | LR: 0.000355
Epoch: 073 | Train loss: 0.9766 | Train acc: 51.33% | Val loss: 1.0027 | Val acc: 49.90% | LR: 0.000348
Epoch: 074 | Train loss: 0.9836 | Train acc: 50.89% | Val loss: 0.9997 | Val acc: 49.79% | LR: 0.000340
Epoch: 075 | Train loss: 0.9778 | Train acc: 51.16% | Val loss: 1.0035 | Val acc: 49.88% | LR: 0.000333
Epoch: 076 | Train loss: 0.9743 | Train acc: 51.42% | Val loss: 1.0025 | Val acc: 49.80% | LR: 0.000326

[I 2025-09-23 16:28:18,408] Trial 17 finished with value: 0.4988490641117096 and parameters: {'lr': 0.0006798016912045978, 'hidden_size': 109, 'dropout': 0.4365792745650823, 'weight_decay': 1.08449294755255e-06}. Best is trial 10 with value: 0.5360925793647766.

Epoch: 000 | Train loss: 0.9990 | Train acc: 50.58% | Val loss: 1.0008 | Val acc: 47.23% | LR: 0.000026
Epoch: 001 | Train loss: 0.9948 | Train acc: 51.01% | Val loss: 1.0109 | Val acc: 47.82% | LR: 0.000026
Epoch: 002 | Train loss: 0.9943 | Train acc: 50.84% | Val loss: 1.0109 | Val acc: 48.08% | LR: 0.000026
Epoch: 003 | Train loss: 0.9948 | Train acc: 51.01% | Val loss: 1.0071 | Val acc: 47.51% | LR: 0.000026
Epoch: 004 | Train loss: 0.9995 | Train acc: 49.80% | Val loss: 1.0055 | Val acc: 46.85% | LR: 0.000026
Epoch: 005 | Train loss: 0.9961 | Train acc: 50.49% | Val loss: 1.0060 | Val acc: 46.92% | LR: 0.000026
Epoch: 006 | Train loss: 0.9984 | Train acc: 50.21% | Val loss: 1.0012 | Val acc: 47.12% | LR: 0.000026
Epoch: 007 | Train loss: 0.9962 | Train acc: 50.52% | Val loss: 1.0025 | Val acc: 46.94% | LR: 0.000025
Epoch: 008 | Train loss: 0.9978 | Train acc: 50.14% | Val loss: 1.0047 | Val acc: 46.80% | LR: 0.000025
Epoch: 009 | Train loss: 0.9971 | Train acc: 50.16% | Val loss: 1.0021 | Val acc: 46.98% | LR: 0.000025
Epoch: 010 | Train loss: 0.9964 | Train acc: 50.41% | Val loss: 1.0013 | Val acc: 46.79% | LR: 0.000025
Epoch: 011 | Train loss: 0.9916 | Train acc: 51.36% | Val loss: 1.0013 | Val acc: 46.60% | LR: 0.000025
Epoch: 012 | Train loss: 0.9948 | Train acc: 50.53% | Val loss: 1.0015 | Val acc: 46.51% | LR: 0.000025
Epoch: 013 | Train loss: 0.9959 | Train acc: 50.40% | Val loss: 1.0017 | Val acc: 46.57% | LR: 0.000025
Epoch: 014 | Train loss: 0.9963 | Train acc: 50.38% | Val loss: 1.0012 | Val acc: 46.68% | LR: 0.000025
Epoch: 015 | Train loss: 0.9943 | Train acc: 50.68% | Val loss: 1.0025 | Val acc: 46.61% | LR: 0.000025
Epoch: 016 | Train loss: 0.9927 | Train acc: 50.86% | Val loss: 1.0018 | Val acc: 46.65% | LR: 0.000025
Epoch: 017 | Train loss: 0.9936 | Train acc: 50.63% | Val loss: 1.0016 | Val acc: 46.53% | LR: 0.000025
Epoch: 018 | Train loss: 0.9975 | Train acc: 50.26% | Val loss: 1.0015 | Val acc: 46.51% | LR: 0.000025
Epoch: 019 | Train loss: 0.9975 | Train acc: 50.10% | Val loss: 1.0021 | Val acc: 46.34% | LR: 0.000025
Epoch: 020 | Train loss: 1.0015 | Train acc: 49.96% | Val loss: 1.0012 | Val acc: 46.60% | LR: 0.000024
Epoch: 021 | Train loss: 0.9978 | Train acc: 50.29% | Val loss: 1.0022 | Val acc: 46.41% | LR: 0.000024
Epoch: 022 | Train loss: 0.9936 | Train acc: 50.65% | Val loss: 1.0017 | Val acc: 46.41% | LR: 0.000024
Epoch: 023 | Train loss: 1.0017 | Train acc: 49.92% | Val loss: 1.0013 | Val acc: 46.48% | LR: 0.000024
Epoch: 024 | Train loss: 1.0021 | Train acc: 49.95% | Val loss: 1.0025 | Val acc: 46.49% | LR: 0.000024
Epoch: 025 | Train loss: 0.9953 | Train acc: 50.24% | Val loss: 1.0015 | Val acc: 46.49% | LR: 0.000024
Epoch: 026 | Train loss: 0.9953 | Train acc: 50.37% | Val loss: 1.0031 | Val acc: 46.41% | LR: 0.000024
Epoch: 027 | Train loss: 0.9936 | Train acc: 50.53% | Val loss: 1.0015 | Val acc: 46.56% | LR: 0.000024
Epoch: 028 | Train loss: 0.9905 | Train acc: 50.80% | Val loss: 1.0017 | Val acc: 46.53% | LR: 0.000023
Epoch: 029 | Train loss: 0.9949 | Train acc: 50.28% | Val loss: 1.0017 | Val acc: 46.76% | LR: 0.000023
Epoch: 030 | Train loss: 0.9967 | Train acc: 50.40% | Val loss: 1.0014 | Val acc: 46.74% | LR: 0.000023
Epoch: 031 | Train loss: 0.9932 | Train acc: 50.52% | Val loss: 1.0014 | Val acc: 46.66% | LR: 0.000023
Epoch: 032 | Train loss: 0.9976 | Train acc: 50.12% | Val loss: 1.0017 | Val acc: 46.68% | LR: 0.000023
Epoch: 033 | Train loss: 1.0005 | Train acc: 49.93% | Val loss: 1.0014 | Val acc: 46.65% | LR: 0.000023
Epoch: 034 | Train loss: 0.9929 | Train acc: 50.54% | Val loss: 1.0021 | Val acc: 46.90% | LR: 0.000022
Epoch: 035 | Train loss: 0.9961 | Train acc: 50.47% | Val loss: 1.0010 | Val acc: 47.04% | LR: 0.000022
Epoch: 036 | Train loss: 0.9938 | Train acc: 50.59% | Val loss: 1.0108 | Val acc: 46.86% | LR: 0.000022
Epoch: 037 | Train loss: 0.9930 | Train acc: 50.88% | Val loss: 1.0013 | Val acc: 46.90% | LR: 0.000022
Epoch: 038 | Train loss: 0.9928 | Train acc: 50.71% | Val loss: 1.0016 | Val acc: 46.96% | LR: 0.000022
Epoch: 039 | Train loss: 0.9940 | Train acc: 50.62% | Val loss: 1.0013 | Val acc: 46.92% | LR: 0.000022
Epoch: 040 | Train loss: 0.9960 | Train acc: 50.51% | Val loss: 1.0012 | Val acc: 47.03% | LR: 0.000021
Epoch: 041 | Train loss: 0.9966 | Train acc: 50.36% | Val loss: 1.0010 | Val acc: 47.11% | LR: 0.000021
Epoch: 042 | Train loss: 0.9916 | Train acc: 50.81% | Val loss: 1.0014 | Val acc: 47.24% | LR: 0.000021
Epoch: 043 | Train loss: 0.9948 | Train acc: 50.56% | Val loss: 1.0010 | Val acc: 47.35% | LR: 0.000021
Epoch: 044 | Train loss: 0.9922 | Train acc: 50.81% | Val loss: 1.0027 | Val acc: 47.33% | LR: 0.000021
Epoch: 045 | Train loss: 1.0013 | Train acc: 50.18% | Val loss: 1.0010 | Val acc: 47.34% | LR: 0.000020
Epoch: 046 | Train loss: 0.9944 | Train acc: 50.59% | Val loss: 1.0011 | Val acc: 47.59% | LR: 0.000020
Epoch: 047 | Train loss: 0.9886 | Train acc: 51.09% | Val loss: 1.0011 | Val acc: 47.59% | LR: 0.000020
Epoch: 048 | Train loss: 0.9929 | Train acc: 50.73% | Val loss: 1.0012 | Val acc: 47.63% | LR: 0.000020
Epoch: 049 | Train loss: 0.9883 | Train acc: 50.83% | Val loss: 1.0010 | Val acc: 47.53% | LR: 0.000019
Epoch: 050 | Train loss: 0.9891 | Train acc: 50.92% | Val loss: 1.0011 | Val acc: 47.53% | LR: 0.000019
Epoch: 051 | Train loss: 0.9928 | Train acc: 50.57% | Val loss: 1.0010 | Val acc: 47.53% | LR: 0.000019

[I 2025-09-23 16:29:05,207] Trial 18 finished with value: 0.47705109119415284 and parameters: {'lr': 2.5654762175795898e-05, 'hidden_size': 82, 'dropout': 0.25525719865005003, 'weight_decay': 4.061362677416945e-06}. Best is trial 10 with value: 0.5360925793647766.

Epoch: 000 | Train loss: 0.9986 | Train acc: 50.75% | Val loss: 0.9979 | Val acc: 53.10% | LR: 0.000199
Epoch: 001 | Train loss: 0.9978 | Train acc: 50.58% | Val loss: 0.9971 | Val acc: 53.10% | LR: 0.000199
Epoch: 002 | Train loss: 0.9932 | Train acc: 50.99% | Val loss: 0.9961 | Val acc: 52.17% | LR: 0.000199
Epoch: 003 | Train loss: 0.9923 | Train acc: 51.01% | Val loss: 0.9958 | Val acc: 51.93% | LR: 0.000198
Epoch: 004 | Train loss: 0.9857 | Train acc: 51.27% | Val loss: 0.9935 | Val acc: 52.29% | LR: 0.000198
Epoch: 005 | Train loss: 0.9848 | Train acc: 51.24% | Val loss: 0.9913 | Val acc: 52.30% | LR: 0.000198
Epoch: 006 | Train loss: 0.9926 | Train acc: 50.74% | Val loss: 0.9880 | Val acc: 52.06% | LR: 0.000198
Epoch: 007 | Train loss: 0.9917 | Train acc: 50.67% | Val loss: 0.9819 | Val acc: 52.14% | LR: 0.000197
Epoch: 008 | Train loss: 0.9858 | Train acc: 51.01% | Val loss: 0.9790 | Val acc: 51.57% | LR: 0.000197
Epoch: 009 | Train loss: 0.9897 | Train acc: 50.78% | Val loss: 0.9896 | Val acc: 50.75% | LR: 0.000197
Epoch: 010 | Train loss: 0.9827 | Train acc: 50.95% | Val loss: 0.9875 | Val acc: 50.77% | LR: 0.000196
Epoch: 011 | Train loss: 0.9778 | Train acc: 51.25% | Val loss: 0.9874 | Val acc: 50.81% | LR: 0.000196
Epoch: 012 | Train loss: 0.9811 | Train acc: 51.11% | Val loss: 0.9876 | Val acc: 50.53% | LR: 0.000195
Epoch: 013 | Train loss: 0.9845 | Train acc: 50.82% | Val loss: 0.9889 | Val acc: 50.47% | LR: 0.000195
Epoch: 014 | Train loss: 0.9877 | Train acc: 50.62% | Val loss: 0.9956 | Val acc: 50.37% | LR: 0.000194
Epoch: 015 | Train loss: 0.9811 | Train acc: 51.16% | Val loss: 0.9950 | Val acc: 50.60% | LR: 0.000193
Epoch: 016 | Train loss: 0.9899 | Train acc: 50.61% | Val loss: 1.0253 | Val acc: 50.17% | LR: 0.000193
Epoch: 017 | Train loss: 0.9805 | Train acc: 51.05% | Val loss: 0.9820 | Val acc: 51.12% | LR: 0.000192
Epoch: 018 | Train loss: 0.9855 | Train acc: 50.81% | Val loss: 0.9804 | Val acc: 51.02% | LR: 0.000191
Epoch: 019 | Train loss: 0.9849 | Train acc: 50.79% | Val loss: 0.9777 | Val acc: 51.11% | LR: 0.000190
Epoch: 020 | Train loss: 0.9839 | Train acc: 50.99% | Val loss: 0.9737 | Val acc: 51.53% | LR: 0.000189
Epoch: 021 | Train loss: 0.9890 | Train acc: 50.59% | Val loss: 0.9673 | Val acc: 51.92% | LR: 0.000188
Epoch: 022 | Train loss: 0.9866 | Train acc: 50.96% | Val loss: 0.9637 | Val acc: 52.54% | LR: 0.000188
Epoch: 023 | Train loss: 0.9811 | Train acc: 51.15% | Val loss: 0.9624 | Val acc: 52.84% | LR: 0.000187
Epoch: 024 | Train loss: 0.9859 | Train acc: 50.69% | Val loss: 0.9639 | Val acc: 52.44% | LR: 0.000186
Epoch: 025 | Train loss: 0.9826 | Train acc: 51.15% | Val loss: 0.9688 | Val acc: 51.88% | LR: 0.000184
Epoch: 026 | Train loss: 0.9829 | Train acc: 50.95% | Val loss: 0.9682 | Val acc: 51.88% | LR: 0.000183
Epoch: 027 | Train loss: 0.9835 | Train acc: 50.96% | Val loss: 0.9703 | Val acc: 51.78% | LR: 0.000182
Epoch: 028 | Train loss: 0.9867 | Train acc: 50.66% | Val loss: 0.9722 | Val acc: 51.37% | LR: 0.000181
Epoch: 029 | Train loss: 0.9812 | Train acc: 51.01% | Val loss: 0.9740 | Val acc: 51.25% | LR: 0.000180
Epoch: 030 | Train loss: 0.9737 | Train acc: 51.43% | Val loss: 0.9742 | Val acc: 51.27% | LR: 0.000179
Epoch: 031 | Train loss: 0.9832 | Train acc: 50.91% | Val loss: 0.9750 | Val acc: 51.23% | LR: 0.000177
Epoch: 032 | Train loss: 0.9762 | Train acc: 51.26% | Val loss: 0.9760 | Val acc: 51.08% | LR: 0.000176
Epoch: 033 | Train loss: 0.9856 | Train acc: 50.70% | Val loss: 0.9757 | Val acc: 50.96% | LR: 0.000175
Epoch: 034 | Train loss: 0.9808 | Train acc: 50.99% | Val loss: 0.9745 | Val acc: 51.44% | LR: 0.000173
Epoch: 035 | Train loss: 0.9820 | Train acc: 51.06% | Val loss: 0.9748 | Val acc: 51.38% | LR: 0.000172
Epoch: 036 | Train loss: 0.9886 | Train acc: 50.55% | Val loss: 0.9761 | Val acc: 51.06% | LR: 0.000171
Epoch: 037 | Train loss: 0.9864 | Train acc: 50.74% | Val loss: 0.9743 | Val acc: 51.46% | LR: 0.000169
Epoch: 038 | Train loss: 0.9801 | Train acc: 51.02% | Val loss: 0.9744 | Val acc: 51.45% | LR: 0.000168
Epoch: 039 | Train loss: 0.9755 | Train acc: 51.37% | Val loss: 0.9763 | Val acc: 51.40% | LR: 0.000166
Epoch: 040 | Train loss: 0.9797 | Train acc: 51.00% | Val loss: 0.9747 | Val acc: 51.34% | LR: 0.000165
Epoch: 041 | Train loss: 0.9724 | Train acc: 51.46% | Val loss: 0.9752 | Val acc: 51.34% | LR: 0.000163
Epoch: 042 | Train loss: 0.9967 | Train acc: 50.13% | Val loss: 0.9756 | Val acc: 51.32% | LR: 0.000161
Epoch: 043 | Train loss: 0.9806 | Train acc: 51.01% | Val loss: 0.9763 | Val acc: 51.27% | LR: 0.000160
Epoch: 044 | Train loss: 0.9846 | Train acc: 50.84% | Val loss: 0.9786 | Val acc: 51.18% | LR: 0.000158
Epoch: 045 | Train loss: 0.9729 | Train acc: 51.46% | Val loss: 0.9779 | Val acc: 51.23% | LR: 0.000156
Epoch: 046 | Train loss: 0.9917 | Train acc: 50.39% | Val loss: 0.9781 | Val acc: 51.34% | LR: 0.000155
Epoch: 047 | Train loss: 0.9772 | Train acc: 51.11% | Val loss: 0.9785 | Val acc: 51.36% | LR: 0.000153
Epoch: 048 | Train loss: 0.9867 | Train acc: 50.68% | Val loss: 0.9801 | Val acc: 51.14% | LR: 0.000151
Epoch: 049 | Train loss: 0.9824 | Train acc: 50.83% | Val loss: 0.9826 | Val acc: 51.03% | LR: 0.000149
Epoch: 050 | Train loss: 0.9826 | Train acc: 50.86% | Val loss: 0.9802 | Val acc: 51.25% | LR: 0.000148

[I 2025-09-23 16:30:10,333] Trial 19 finished with value: 0.5117331862449646 and parameters: {'lr': 0.00019878348519896186, 'hidden_size': 144, 'dropout': 0.3376971010847967, 'weight_decay': 2.3653633297980208e-05}. Best is trial 10 with value: 0.5360925793647766.

Epoch: 000 | Train loss: 1.0032 | Train acc: 50.27% | Val loss: 1.0069 | Val acc: 46.29% | LR: 0.000020
Epoch: 001 | Train loss: 1.0002 | Train acc: 50.03% | Val loss: 1.0057 | Val acc: 46.08% | LR: 0.000020
Epoch: 002 | Train loss: 1.0026 | Train acc: 49.55% | Val loss: 1.0066 | Val acc: 45.99% | LR: 0.000020
Epoch: 003 | Train loss: 1.0016 | Train acc: 49.48% | Val loss: 1.0050 | Val acc: 45.88% | LR: 0.000020
Epoch: 004 | Train loss: 1.0007 | Train acc: 49.58% | Val loss: 1.0043 | Val acc: 46.03% | LR: 0.000020
Epoch: 005 | Train loss: 0.9998 | Train acc: 50.18% | Val loss: 1.0071 | Val acc: 46.06% | LR: 0.000020
Epoch: 006 | Train loss: 1.0016 | Train acc: 49.41% | Val loss: 1.0083 | Val acc: 46.14% | LR: 0.000020
Epoch: 007 | Train loss: 0.9985 | Train acc: 50.09% | Val loss: 1.0053 | Val acc: 46.13% | LR: 0.000020
Epoch: 008 | Train loss: 0.9999 | Train acc: 49.79% | Val loss: 1.0050 | Val acc: 46.17% | LR: 0.000020
Epoch: 009 | Train loss: 0.9998 | Train acc: 50.07% | Val loss: 1.0048 | Val acc: 46.36% | LR: 0.000019
Epoch: 010 | Train loss: 0.9992 | Train acc: 49.87% | Val loss: 1.0163 | Val acc: 46.34% | LR: 0.000019
Epoch: 011 | Train loss: 1.0003 | Train acc: 49.99% | Val loss: 1.0078 | Val acc: 46.02% | LR: 0.000019
Epoch: 012 | Train loss: 0.9996 | Train acc: 49.64% | Val loss: 1.0031 | Val acc: 46.56% | LR: 0.000019
Epoch: 013 | Train loss: 1.0003 | Train acc: 49.60% | Val loss: 1.0086 | Val acc: 45.90% | LR: 0.000019
Epoch: 014 | Train loss: 1.0261 | Train acc: 49.64% | Val loss: 1.0043 | Val acc: 46.27% | LR: 0.000019
Epoch: 015 | Train loss: 0.9996 | Train acc: 49.71% | Val loss: 1.0072 | Val acc: 45.93% | LR: 0.000019
Epoch: 016 | Train loss: 0.9977 | Train acc: 50.08% | Val loss: 1.0057 | Val acc: 45.85% | LR: 0.000019
Epoch: 017 | Train loss: 0.9988 | Train acc: 49.88% | Val loss: 1.0045 | Val acc: 45.93% | LR: 0.000019
Epoch: 018 | Train loss: 0.9972 | Train acc: 50.08% | Val loss: 1.0042 | Val acc: 45.97% | LR: 0.000019
Epoch: 019 | Train loss: 0.9988 | Train acc: 50.60% | Val loss: 1.0050 | Val acc: 45.89% | LR: 0.000019
Epoch: 020 | Train loss: 0.9987 | Train acc: 50.79% | Val loss: 1.0037 | Val acc: 46.02% | LR: 0.000019
Epoch: 021 | Train loss: 0.9980 | Train acc: 50.95% | Val loss: 1.0090 | Val acc: 45.91% | LR: 0.000019
Epoch: 022 | Train loss: 0.9979 | Train acc: 50.75% | Val loss: 1.0084 | Val acc: 45.83% | LR: 0.000019
Epoch: 023 | Train loss: 0.9987 | Train acc: 50.03% | Val loss: 1.0127 | Val acc: 46.11% | LR: 0.000019
Epoch: 024 | Train loss: 0.9968 | Train acc: 50.75% | Val loss: 1.0039 | Val acc: 46.05% | LR: 0.000018
Epoch: 025 | Train loss: 0.9986 | Train acc: 49.69% | Val loss: 1.0034 | Val acc: 46.15% | LR: 0.000018
Epoch: 026 | Train loss: 0.9970 | Train acc: 50.23% | Val loss: 1.0055 | Val acc: 46.04% | LR: 0.000018
Epoch: 027 | Train loss: 0.9958 | Train acc: 50.78% | Val loss: 1.0042 | Val acc: 46.18% | LR: 0.000018
Epoch: 028 | Train loss: 0.9980 | Train acc: 50.23% | Val loss: 1.0096 | Val acc: 46.14% | LR: 0.000018
Epoch: 029 | Train loss: 0.9970 | Train acc: 50.24% | Val loss: 1.0035 | Val acc: 46.46% | LR: 0.000018
Epoch: 030 | Train loss: 0.9963 | Train acc: 50.65% | Val loss: 1.0272 | Val acc: 46.00% | LR: 0.000018
Epoch: 031 | Train loss: 0.9978 | Train acc: 50.86% | Val loss: 1.0063 | Val acc: 46.08% | LR: 0.000018
Epoch: 032 | Train loss: 0.9960 | Train acc: 50.40% | Val loss: 1.0052 | Val acc: 46.10% | LR: 0.000018
Epoch: 033 | Train loss: 0.9949 | Train acc: 50.60% | Val loss: 1.0128 | Val acc: 46.44% | LR: 0.000017
Epoch: 034 | Train loss: 0.9978 | Train acc: 50.32% | Val loss: 1.0065 | Val acc: 46.12% | LR: 0.000017
Epoch: 035 | Train loss: 0.9978 | Train acc: 50.28% | Val loss: 1.0040 | Val acc: 46.35% | LR: 0.000017
Epoch: 036 | Train loss: 0.9949 | Train acc: 50.47% | Val loss: 1.0062 | Val acc: 46.04% | LR: 0.000017
Epoch: 037 | Train loss: 0.9987 | Train acc: 49.88% | Val loss: 1.0050 | Val acc: 45.96% | LR: 0.000017
Epoch: 038 | Train loss: 0.9995 | Train acc: 49.87% | Val loss: 1.0023 | Val acc: 46.31% | LR: 0.000017
Epoch: 039 | Train loss: 0.9944 | Train acc: 50.73% | Val loss: 1.0034 | Val acc: 46.18% | LR: 0.000017
Epoch: 040 | Train loss: 0.9950 | Train acc: 50.60% | Val loss: 1.0041 | Val acc: 46.34% | LR: 0.000016
Epoch: 041 | Train loss: 0.9951 | Train acc: 50.52% | Val loss: 1.0104 | Val acc: 46.11% | LR: 0.000016
Epoch: 042 | Train loss: 0.9944 | Train acc: 50.67% | Val loss: 1.0032 | Val acc: 46.44% | LR: 0.000016
Epoch: 043 | Train loss: 0.9968 | Train acc: 49.99% | Val loss: 1.0063 | Val acc: 46.13% | LR: 0.000016
Epoch: 044 | Train loss: 1.0011 | Train acc: 50.32% | Val loss: 1.0587 | Val acc: 46.16% | LR: 0.000016
Epoch: 045 | Train loss: 0.9909 | Train acc: 50.47% | Val loss: 1.0051 | Val acc: 46.36% | LR: 0.000016
Epoch: 046 | Train loss: 0.9916 | Train acc: 50.69% | Val loss: 1.0135 | Val acc: 46.28% | LR: 0.000016
Epoch: 047 | Train loss: 0.9923 | Train acc: 50.57% | Val loss: 1.0079 | Val acc: 46.46% | LR: 0.000015
Epoch: 048 | Train loss: 0.9886 | Train acc: 51.10% | Val loss: 1.0069 | Val acc: 46.38% | LR: 0.000015
Epoch: 049 | Train loss: 0.9944 | Train acc: 50.36% | Val loss: 1.0096 | Val acc: 46.34% | LR: 0.000015
Epoch: 050 | Train loss: 0.9962 | Train acc: 50.48% | Val loss: 1.0056 | Val acc: 46.20% | LR: 0.000015
Epoch: 051 | Train loss: 0.9940 | Train acc: 50.01% | Val loss: 1.0068 | Val acc: 46.61% | LR: 0.000015
Epoch: 052 | Train loss: 0.9868 | Train acc: 51.12% | Val loss: 1.0029 | Val acc: 46.28% | LR: 0.000014
Epoch: 053 | Train loss: 1.0031 | Train acc: 50.81% | Val loss: 1.0244 | Val acc: 46.46% | LR: 0.000014
Epoch: 054 | Train loss: 0.9938 | Train acc: 50.14% | Val loss: 1.0060 | Val acc: 46.45% | LR: 0.000014
Epoch: 055 | Train loss: 1.0402 | Train acc: 50.49% | Val loss: 1.0783 | Val acc: 46.56% | LR: 0.000014
Epoch: 056 | Train loss: 0.9907 | Train acc: 50.68% | Val loss: 1.0054 | Val acc: 46.37% | LR: 0.000014
Epoch: 057 | Train loss: 0.9949 | Train acc: 50.24% | Val loss: 1.0029 | Val acc: 46.52% | LR: 0.000014
Epoch: 058 | Train loss: 0.9927 | Train acc: 50.15% | Val loss: 1.0076 | Val acc: 46.22% | LR: 0.000013
Epoch: 059 | Train loss: 0.9896 | Train acc: 51.12% | Val loss: 1.0056 | Val acc: 46.52% | LR: 0.000013
Epoch: 060 | Train loss: 0.9927 | Train acc: 50.66% | Val loss: 1.0046 | Val acc: 46.42% | LR: 0.000013
Epoch: 061 | Train loss: 0.9893 | Train acc: 50.76% | Val loss: 1.0080 | Val acc: 46.36% | LR: 0.000013
Epoch: 062 | Train loss: 0.9943 | Train acc: 50.33% | Val loss: 1.0042 | Val acc: 46.24% | LR: 0.000013
Epoch: 063 | Train loss: 0.9964 | Train acc: 49.95% | Val loss: 1.0065 | Val acc: 46.28% | LR: 0.000012
Epoch: 064 | Train loss: 1.1673 | Train acc: 50.23% | Val loss: 1.0057 | Val acc: 46.18% | LR: 0.000012
Epoch: 065 | Train loss: 0.9919 | Train acc: 50.24% | Val loss: 1.0318 | Val acc: 46.40% | LR: 0.000012
Epoch: 066 | Train loss: 0.9862 | Train acc: 51.36% | Val loss: 1.0050 | Val acc: 46.38% | LR: 0.000012
Epoch: 067 | Train loss: 0.9880 | Train acc: 51.11% | Val loss: 1.0036 | Val acc: 46.44% | LR: 0.000012
Epoch: 068 | Train loss: 0.9952 | Train acc: 50.33% | Val loss: 1.0052 | Val acc: 46.48% | LR: 0.000012
Epoch: 069 | Train loss: 0.9930 | Train acc: 50.24% | Val loss: 1.0042 | Val acc: 45.96% | LR: 0.000011
Epoch: 070 | Train loss: 0.9903 | Train acc: 50.79% | Val loss: 1.0061 | Val acc: 46.03% | LR: 0.000011
Epoch: 071 | Train loss: 0.9945 | Train acc: 50.11% | Val loss: 1.0070 | Val acc: 46.04% | LR: 0.000011
Epoch: 072 | Train loss: 0.9890 | Train acc: 50.56% | Val loss: 1.0041 | Val acc: 46.07% | LR: 0.000011
Epoch: 073 | Train loss: 0.9916 | Train acc: 50.33% | Val loss: 1.0079 | Val acc: 46.03% | LR: 0.000011
Epoch: 074 | Train loss: 0.9908 | Train acc: 50.52% | Val loss: 1.0044 | Val acc: 45.91% | LR: 0.000010
Epoch: 075 | Train loss: 0.9883 | Train acc: 50.89% | Val loss: 1.0048 | Val acc: 45.98% | LR: 0.000010
Epoch: 076 | Train loss: 0.9925 | Train acc: 50.53% | Val loss: 1.0033 | Val acc: 46.03% | LR: 0.000010
Epoch: 077 | Train loss: 0.9887 | Train acc: 50.86% | Val loss: 1.0037 | Val acc: 45.94% | LR: 0.000010
Epoch: 078 | Train loss: 0.9909 | Train acc: 50.84% | Val loss: 1.0047 | Val acc: 46.41% | LR: 0.000010
Epoch: 079 | Train loss: 0.9917 | Train acc: 50.47% | Val loss: 1.0033 | Val acc: 46.55% | LR: 0.000009
Epoch: 080 | Train loss: 0.9885 | Train acc: 50.83% | Val loss: 1.0087 | Val acc: 46.19% | LR: 0.000009
Epoch: 081 | Train loss: 0.9930 | Train acc: 50.57% | Val loss: 1.0030 | Val acc: 46.03% | LR: 0.000009
Epoch: 082 | Train loss: 0.9900 | Train acc: 50.79% | Val loss: 1.0466 | Val acc: 46.35% | LR: 0.000009
Epoch: 083 | Train loss: 0.9863 | Train acc: 51.02% | Val loss: 1.0027 | Val acc: 46.80% | LR: 0.000009
Epoch: 084 | Train loss: 0.9935 | Train acc: 50.37% | Val loss: 1.0061 | Val acc: 46.96% | LR: 0.000008
Epoch: 085 | Train loss: 0.9938 | Train acc: 50.54% | Val loss: 1.0079 | Val acc: 46.84% | LR: 0.000008
Epoch: 086 | Train loss: 0.9932 | Train acc: 50.46% | Val loss: 1.0042 | Val acc: 47.14% | LR: 0.000008
Epoch: 087 | Train loss: 0.9887 | Train acc: 51.28% | Val loss: 1.0024 | Val acc: 46.94% | LR: 0.000008
Epoch: 088 | Train loss: 0.9897 | Train acc: 50.91% | Val loss: 1.0034 | Val acc: 47.02% | LR: 0.000008
Epoch: 089 | Train loss: 0.9930 | Train acc: 50.27% | Val loss: 1.0042 | Val acc: 46.96% | LR: 0.000007
Epoch: 090 | Train loss: 0.9935 | Train acc: 50.46% | Val loss: 1.0076 | Val acc: 46.79% | LR: 0.000007
Epoch: 091 | Train loss: 0.9905 | Train acc: 50.75% | Val loss: 1.0451 | Val acc: 46.80% | LR: 0.000007
Epoch: 092 | Train loss: 0.9890 | Train acc: 50.83% | Val loss: 1.0021 | Val acc: 47.34% | LR: 0.000007
Epoch: 093 | Train loss: 0.9911 | Train acc: 50.66% | Val loss: 1.0045 | Val acc: 46.86% | LR: 0.000007
Epoch: 094 | Train loss: 0.9912 | Train acc: 50.50% | Val loss: 1.0219 | Val acc: 46.65% | LR: 0.000007
Epoch: 095 | Train loss: 0.9875 | Train acc: 50.75% | Val loss: 1.0033 | Val acc: 46.53% | LR: 0.000006
Epoch: 096 | Train loss: 0.9927 | Train acc: 50.40% | Val loss: 1.0035 | Val acc: 46.58% | LR: 0.000006
Epoch: 097 | Train loss: 0.9897 | Train acc: 50.32% | Val loss: 1.0038 | Val acc: 46.53% | LR: 0.000006
Epoch: 098 | Train loss: 0.9904 | Train acc: 50.91% | Val loss: 1.0046 | Val acc: 46.21% | LR: 0.000006
Epoch: 099 | Train loss: 0.9904 | Train acc: 50.87% | Val loss: 1.0030 | Val acc: 46.30% | LR: 0.000006
Epoch: 100 | Train loss: 0.9873 | Train acc: 51.20% | Val loss: 1.0127 | Val acc: 46.16% | LR: 0.000005
Epoch: 101 | Train loss: 0.9889 | Train acc: 50.86% | Val loss: 1.0061 | Val acc: 46.09% | LR: 0.000005
Epoch: 102 | Train loss: 0.9910 | Train acc: 51.08% | Val loss: 1.0126 | Val acc: 46.20% | LR: 0.000005
Epoch: 103 | Train loss: 0.9902 | Train acc: 50.83% | Val loss: 1.0033 | Val acc: 46.26% | LR: 0.000005
Epoch: 104 | Train loss: 0.9907 | Train acc: 50.91% | Val loss: 1.0043 | Val acc: 46.19% | LR: 0.000005
Epoch: 105 | Train loss: 0.9907 | Train acc: 50.72% | Val loss: 1.0038 | Val acc: 46.25% | LR: 0.000005
Epoch: 106 | Train loss: 0.9918 | Train acc: 50.42% | Val loss: 1.0039 | Val acc: 46.47% | LR: 0.000005
Epoch: 107 | Train loss: 0.9917 | Train acc: 50.54% | Val loss: 1.0043 | Val acc: 46.57% | LR: 0.000004
Epoch: 108 | Train loss: 0.9921 | Train acc: 50.58% | Val loss: 1.0029 | Val acc: 46.69% | LR: 0.000004
Epoch: 109 | Train loss: 0.9942 | Train acc: 50.41% | Val loss: 1.0093 | Val acc: 46.64% | LR: 0.000004
Epoch: 110 | Train loss: 0.9909 | Train acc: 50.66% | Val loss: 1.0030 | Val acc: 46.70% | LR: 0.000004
Epoch: 111 | Train loss: 0.9902 | Train acc: 50.65% | Val loss: 1.0026 | Val acc: 46.90% | LR: 0.000004
Epoch: 112 | Train loss: 0.9932 | Train acc: 50.40% | Val loss: 1.0038 | Val acc: 46.72% | LR: 0.000004
Epoch: 113 | Train loss: 0.9956 | Train acc: 50.29% | Val loss: 1.0026 | Val acc: 46.86% | LR: 0.000004
Epoch: 114 | Train loss: 0.9944 | Train acc: 50.36% | Val loss: 1.0035 | Val acc: 46.78% | LR: 0.000003
Epoch: 115 | Train loss: 0.9894 | Train acc: 50.73% | Val loss: 1.0064 | Val acc: 46.83% | LR: 0.000003
Epoch: 116 | Train loss: 0.9884 | Train acc: 50.81% | Val loss: 1.0035 | Val acc: 46.82% | LR: 0.000003
Epoch: 117 | Train loss: 0.9883 | Train acc: 51.08% | Val loss: 1.0031 | Val acc: 46.79% | LR: 0.000003
Epoch: 118 | Train loss: 0.9912 | Train acc: 50.46% | Val loss: 1.0038 | Val acc: 46.78% | LR: 0.000003
Epoch: 119 | Train loss: 0.9907 | Train acc: 50.72% | Val loss: 1.0028 | Val acc: 46.86% | LR: 0.000003
Epoch: 120 | Train loss: 0.9904 | Train acc: 50.52% | Val loss: 1.0075 | Val acc: 46.82% | LR: 0.000003
Epoch: 121 | Train loss: 0.9880 | Train acc: 50.71% | Val loss: 1.0058 | Val acc: 46.84% | LR: 0.000003
Epoch: 122 | Train loss: 0.9937 | Train acc: 50.36% | Val loss: 1.0050 | Val acc: 46.70% | LR: 0.000002
Epoch: 123 | Train loss: 0.9950 | Train acc: 50.08% | Val loss: 1.0037 | Val acc: 46.80% | LR: 0.000002
Epoch: 124 | Train loss: 0.9962 | Train acc: 50.00% | Val loss: 1.0036 | Val acc: 46.80% | LR: 0.000002
Epoch: 125 | Train loss: 0.9871 | Train acc: 50.70% | Val loss: 1.0326 | Val acc: 46.89% | LR: 0.000002
Epoch: 126 | Train loss: 0.9857 | Train acc: 51.15% | Val loss: 1.0043 | Val acc: 46.82% | LR: 0.000002
Epoch: 127 | Train loss: 0.9877 | Train acc: 50.88% | Val loss: 1.0044 | Val acc: 46.82% | LR: 0.000002
Epoch: 128 | Train loss: 0.9911 | Train acc: 50.69% | Val loss: 1.0044 | Val acc: 46.90% | LR: 0.000002
Epoch: 129 | Train loss: 0.9834 | Train acc: 51.42% | Val loss: 1.0034 | Val acc: 46.84% | LR: 0.000002
Epoch: 130 | Train loss: 0.9909 | Train acc: 50.90% | Val loss: 1.0034 | Val acc: 46.82% | LR: 0.000002
Epoch: 131 | Train loss: 0.9870 | Train acc: 50.71% | Val loss: 1.0030 | Val acc: 46.87% | LR: 0.000002
Epoch: 132 | Train loss: 0.9931 | Train acc: 50.55% | Val loss: 1.0044 | Val acc: 46.86% | LR: 0.000002
Epoch: 133 | Train loss: 0.9894 | Train acc: 50.81% | Val loss: 1.0052 | Val acc: 46.89% | LR: 0.000002
Epoch: 134 | Train loss: 0.9883 | Train acc: 50.82% | Val loss: 1.0062 | Val acc: 46.87% | LR: 0.000001
Epoch: 135 | Train loss: 1.0037 | Train acc: 50.55% | Val loss: 1.0047 | Val acc: 46.92% | LR: 0.000001
Epoch: 136 | Train loss: 0.9904 | Train acc: 50.71% | Val loss: 1.0025 | Val acc: 46.97% | LR: 0.000001
Epoch: 137 | Train loss: 0.9935 | Train acc: 50.18% | Val loss: 1.0025 | Val acc: 46.91% | LR: 0.000001
Epoch: 138 | Train loss: 0.9916 | Train acc: 50.25% | Val loss: 1.0080 | Val acc: 46.87% | LR: 0.000001
Epoch: 139 | Train loss: 0.9869 | Train acc: 51.32% | Val loss: 1.0053 | Val acc: 46.87% | LR: 0.000001
Epoch: 140 | Train loss: 0.9938 | Train acc: 50.00% | Val loss: 1.0116 | Val acc: 46.91% | LR: 0.000001
Epoch: 141 | Train loss: 0.9908 | Train acc: 50.45% | Val loss: 1.0057 | Val acc: 46.89% | LR: 0.000001

[I 2025-09-23 16:34:21,544] Trial 20 finished with value: 0.46891849040985106 and parameters: {'lr': 1.966901166454849e-05, 'hidden_size': 180, 'dropout': 0.19395958556942383, 'weight_decay': 1.837005959041966e-05}. Best is trial 10 with value: 0.5360925793647766.

Epoch: 000 | Train loss: 1.0002 | Train acc: 50.07% | Val loss: 0.9916 | Val acc: 54.11% | LR: 0.000053
Epoch: 001 | Train loss: 1.0006 | Train acc: 49.73% | Val loss: 0.9912 | Val acc: 54.17% | LR: 0.000053
Epoch: 002 | Train loss: 1.0001 | Train acc: 49.54% | Val loss: 0.9912 | Val acc: 54.28% | LR: 0.000053
Epoch: 003 | Train loss: 0.9999 | Train acc: 49.97% | Val loss: 0.9915 | Val acc: 54.28% | LR: 0.000053
Epoch: 004 | Train loss: 0.9999 | Train acc: 50.12% | Val loss: 0.9916 | Val acc: 54.40% | LR: 0.000053
Epoch: 005 | Train loss: 0.9972 | Train acc: 50.88% | Val loss: 0.9916 | Val acc: 54.29% | LR: 0.000053
Epoch: 006 | Train loss: 0.9979 | Train acc: 50.64% | Val loss: 0.9916 | Val acc: 54.37% | LR: 0.000053
Epoch: 007 | Train loss: 0.9984 | Train acc: 50.05% | Val loss: 0.9917 | Val acc: 54.52% | LR: 0.000053
Epoch: 008 | Train loss: 0.9985 | Train acc: 50.13% | Val loss: 0.9922 | Val acc: 54.42% | LR: 0.000053
Epoch: 009 | Train loss: 0.9967 | Train acc: 50.84% | Val loss: 0.9923 | Val acc: 54.38% | LR: 0.000052
Epoch: 010 | Train loss: 0.9961 | Train acc: 50.56% | Val loss: 0.9924 | Val acc: 54.61% | LR: 0.000052
Epoch: 011 | Train loss: 0.9955 | Train acc: 50.96% | Val loss: 0.9921 | Val acc: 54.55% | LR: 0.000052
Epoch: 012 | Train loss: 0.9960 | Train acc: 50.80% | Val loss: 0.9921 | Val acc: 54.42% | LR: 0.000052
Epoch: 013 | Train loss: 0.9940 | Train acc: 51.33% | Val loss: 0.9915 | Val acc: 54.31% | LR: 0.000052
Epoch: 014 | Train loss: 0.9972 | Train acc: 50.38% | Val loss: 0.9917 | Val acc: 53.96% | LR: 0.000052
Epoch: 015 | Train loss: 0.9948 | Train acc: 51.04% | Val loss: 0.9916 | Val acc: 53.42% | LR: 0.000052
Epoch: 016 | Train loss: 0.9968 | Train acc: 50.60% | Val loss: 0.9918 | Val acc: 53.08% | LR: 0.000051
Epoch: 017 | Train loss: 0.9941 | Train acc: 51.29% | Val loss: 0.9914 | Val acc: 52.84% | LR: 0.000051
Epoch: 018 | Train loss: 0.9937 | Train acc: 51.24% | Val loss: 0.9910 | Val acc: 52.76% | LR: 0.000051
Epoch: 019 | Train loss: 0.9960 | Train acc: 50.49% | Val loss: 0.9908 | Val acc: 52.64% | LR: 0.000051
Epoch: 020 | Train loss: 0.9945 | Train acc: 50.39% | Val loss: 0.9906 | Val acc: 52.74% | LR: 0.000051
Epoch: 021 | Train loss: 0.9933 | Train acc: 50.77% | Val loss: 0.9901 | Val acc: 52.55% | LR: 0.000050
Epoch: 022 | Train loss: 0.9953 | Train acc: 50.34% | Val loss: 0.9896 | Val acc: 52.54% | LR: 0.000050
Epoch: 023 | Train loss: 0.9933 | Train acc: 50.78% | Val loss: 0.9892 | Val acc: 52.50% | LR: 0.000050
Epoch: 024 | Train loss: 0.9926 | Train acc: 51.14% | Val loss: 0.9891 | Val acc: 52.23% | LR: 0.000050
Epoch: 025 | Train loss: 0.9923 | Train acc: 51.17% | Val loss: 0.9886 | Val acc: 52.34% | LR: 0.000049
Epoch: 026 | Train loss: 0.9909 | Train acc: 51.10% | Val loss: 0.9877 | Val acc: 52.30% | LR: 0.000049
Epoch: 027 | Train loss: 0.9927 | Train acc: 50.66% | Val loss: 0.9874 | Val acc: 52.04% | LR: 0.000049
Epoch: 028 | Train loss: 0.9922 | Train acc: 50.61% | Val loss: 0.9865 | Val acc: 52.16% | LR: 0.000048
Epoch: 029 | Train loss: 0.9894 | Train acc: 51.15% | Val loss: 0.9854 | Val acc: 52.06% | LR: 0.000048
Epoch: 030 | Train loss: 0.9936 | Train acc: 50.71% | Val loss: 0.9841 | Val acc: 52.08% | LR: 0.000048
Epoch: 031 | Train loss: 0.9952 | Train acc: 50.43% | Val loss: 0.9823 | Val acc: 52.16% | LR: 0.000047
Epoch: 032 | Train loss: 0.9888 | Train acc: 50.94% | Val loss: 0.9806 | Val acc: 52.28% | LR: 0.000047
Epoch: 033 | Train loss: 0.9905 | Train acc: 51.02% | Val loss: 0.9796 | Val acc: 52.45% | LR: 0.000047
Epoch: 034 | Train loss: 0.9869 | Train acc: 51.04% | Val loss: 0.9791 | Val acc: 52.10% | LR: 0.000046
Epoch: 035 | Train loss: 0.9894 | Train acc: 50.87% | Val loss: 0.9776 | Val acc: 52.18% | LR: 0.000046
Epoch: 036 | Train loss: 0.9870 | Train acc: 51.03% | Val loss: 0.9769 | Val acc: 52.02% | LR: 0.000046
Epoch: 037 | Train loss: 0.9858 | Train acc: 51.11% | Val loss: 0.9769 | Val acc: 51.92% | LR: 0.000045
Epoch: 038 | Train loss: 0.9894 | Train acc: 50.74% | Val loss: 0.9774 | Val acc: 51.90% | LR: 0.000045
Epoch: 039 | Train loss: 0.9818 | Train acc: 51.22% | Val loss: 0.9771 | Val acc: 51.92% | LR: 0.000044
Epoch: 040 | Train loss: 0.9862 | Train acc: 50.86% | Val loss: 0.9776 | Val acc: 51.92% | LR: 0.000044
Epoch: 041 | Train loss: 0.9879 | Train acc: 50.77% | Val loss: 0.9786 | Val acc: 51.57% | LR: 0.000044
Epoch: 042 | Train loss: 0.9882 | Train acc: 50.85% | Val loss: 0.9792 | Val acc: 51.52% | LR: 0.000043
Epoch: 043 | Train loss: 0.9897 | Train acc: 50.68% | Val loss: 0.9802 | Val acc: 51.38% | LR: 0.000043
Epoch: 044 | Train loss: 0.9866 | Train acc: 50.95% | Val loss: 0.9803 | Val acc: 51.44% | LR: 0.000042
Epoch: 045 | Train loss: 0.9827 | Train acc: 51.13% | Val loss: 0.9810 | Val acc: 51.39% | LR: 0.000042
Epoch: 046 | Train loss: 0.9821 | Train acc: 50.95% | Val loss: 0.9813 | Val acc: 51.43% | LR: 0.000041
Epoch: 047 | Train loss: 0.9819 | Train acc: 51.31% | Val loss: 0.9823 | Val acc: 51.25% | LR: 0.000041
Epoch: 048 | Train loss: 0.9849 | Train acc: 50.86% | Val loss: 0.9823 | Val acc: 51.15% | LR: 0.000040
Epoch: 049 | Train loss: 0.9880 | Train acc: 50.68% | Val loss: 0.9828 | Val acc: 51.19% | LR: 0.000040
Epoch: 050 | Train loss: 0.9920 | Train acc: 50.49% | Val loss: 0.9829 | Val acc: 51.12% | LR: 0.000040
Epoch: 051 | Train loss: 0.9805 | Train acc: 51.20% | Val loss: 0.9840 | Val acc: 51.16% | LR: 0.000039
Epoch: 052 | Train loss: 0.9941 | Train acc: 50.33% | Val loss: 0.9842 | Val acc: 51.10% | LR: 0.000039
Epoch: 053 | Train loss: 0.9825 | Train acc: 51.21% | Val loss: 0.9842 | Val acc: 51.02% | LR: 0.000038
Epoch: 054 | Train loss: 0.9817 | Train acc: 51.03% | Val loss: 0.9845 | Val acc: 51.00% | LR: 0.000038
Epoch: 055 | Train loss: 0.9836 | Train acc: 50.86% | Val loss: 0.9842 | Val acc: 51.00% | LR: 0.000037
Epoch: 056 | Train loss: 0.9833 | Train acc: 50.86% | Val loss: 0.9848 | Val acc: 50.88% | LR: 0.000037
Epoch: 057 | Train loss: 0.9805 | Train acc: 51.23% | Val loss: 0.9849 | Val acc: 50.81% | LR: 0.000036
Epoch: 058 | Train loss: 0.9888 | Train acc: 50.61% | Val loss: 0.9855 | Val acc: 50.87% | LR: 0.000036
Epoch: 059 | Train loss: 0.9846 | Train acc: 50.80% | Val loss: 0.9855 | Val acc: 50.93% | LR: 0.000035

[I 2025-09-23 16:35:08,137] Trial 21 finished with value: 0.5093158602714538 and parameters: {'lr': 5.300462098641494e-05, 'hidden_size': 64, 'dropout': 0.43329267633203017, 'weight_decay': 0.0002523170111460684}. Best is trial 10 with value: 0.5360925793647766.

Epoch: 000 | Train loss: 0.9989 | Train acc: 50.37% | Val loss: 1.0043 | Val acc: 46.34% | LR: 0.000109
Epoch: 001 | Train loss: 0.9977 | Train acc: 50.85% | Val loss: 1.0041 | Val acc: 46.68% | LR: 0.000109
Epoch: 002 | Train loss: 0.9974 | Train acc: 50.91% | Val loss: 1.0040 | Val acc: 47.02% | LR: 0.000108
Epoch: 003 | Train loss: 0.9974 | Train acc: 50.78% | Val loss: 1.0038 | Val acc: 47.04% | LR: 0.000108
Epoch: 004 | Train loss: 0.9967 | Train acc: 50.80% | Val loss: 1.0042 | Val acc: 47.04% | LR: 0.000108
Epoch: 005 | Train loss: 0.9944 | Train acc: 51.10% | Val loss: 1.0037 | Val acc: 47.79% | LR: 0.000108
Epoch: 006 | Train loss: 0.9953 | Train acc: 50.83% | Val loss: 1.0021 | Val acc: 48.28% | LR: 0.000108
Epoch: 007 | Train loss: 0.9896 | Train acc: 51.48% | Val loss: 1.0035 | Val acc: 48.36% | LR: 0.000108
Epoch: 008 | Train loss: 0.9918 | Train acc: 51.01% | Val loss: 1.0027 | Val acc: 48.86% | LR: 0.000108
Epoch: 009 | Train loss: 0.9916 | Train acc: 51.03% | Val loss: 1.0032 | Val acc: 49.18% | LR: 0.000107
Epoch: 010 | Train loss: 0.9934 | Train acc: 50.77% | Val loss: 1.0012 | Val acc: 49.64% | LR: 0.000107
Epoch: 011 | Train loss: 0.9903 | Train acc: 51.09% | Val loss: 0.9982 | Val acc: 50.06% | LR: 0.000107
Epoch: 012 | Train loss: 0.9904 | Train acc: 50.83% | Val loss: 0.9949 | Val acc: 50.40% | LR: 0.000107
Epoch: 013 | Train loss: 0.9908 | Train acc: 50.40% | Val loss: 0.9948 | Val acc: 50.54% | LR: 0.000106
Epoch: 014 | Train loss: 0.9891 | Train acc: 51.04% | Val loss: 0.9950 | Val acc: 50.26% | LR: 0.000106
Epoch: 015 | Train loss: 0.9943 | Train acc: 49.87% | Val loss: 0.9965 | Val acc: 50.16% | LR: 0.000106
Epoch: 016 | Train loss: 0.9935 | Train acc: 50.30% | Val loss: 0.9987 | Val acc: 49.80% | LR: 0.000105
Epoch: 017 | Train loss: 0.9925 | Train acc: 50.18% | Val loss: 0.9964 | Val acc: 50.12% | LR: 0.000105
Epoch: 018 | Train loss: 0.9917 | Train acc: 50.95% | Val loss: 0.9991 | Val acc: 49.90% | LR: 0.000104
Epoch: 019 | Train loss: 0.9929 | Train acc: 50.54% | Val loss: 0.9993 | Val acc: 49.64% | LR: 0.000104
Epoch: 020 | Train loss: 0.9917 | Train acc: 50.80% | Val loss: 1.0010 | Val acc: 49.58% | LR: 0.000103
Epoch: 021 | Train loss: 0.9893 | Train acc: 51.15% | Val loss: 1.0036 | Val acc: 49.39% | LR: 0.000103
Epoch: 022 | Train loss: 0.9872 | Train acc: 50.98% | Val loss: 1.0041 | Val acc: 49.32% | LR: 0.000102
Epoch: 023 | Train loss: 0.9840 | Train acc: 51.17% | Val loss: 1.0046 | Val acc: 49.22% | LR: 0.000102
Epoch: 024 | Train loss: 0.9865 | Train acc: 50.93% | Val loss: 1.0057 | Val acc: 49.26% | LR: 0.000101
Epoch: 025 | Train loss: 0.9858 | Train acc: 50.85% | Val loss: 1.0087 | Val acc: 49.12% | LR: 0.000101
Epoch: 026 | Train loss: 0.9861 | Train acc: 50.77% | Val loss: 1.0102 | Val acc: 49.06% | LR: 0.000100
Epoch: 027 | Train loss: 0.9777 | Train acc: 51.41% | Val loss: 1.0100 | Val acc: 49.10% | LR: 0.000100
Epoch: 028 | Train loss: 0.9823 | Train acc: 51.05% | Val loss: 1.0078 | Val acc: 49.42% | LR: 0.000099
Epoch: 029 | Train loss: 0.9840 | Train acc: 50.89% | Val loss: 1.0132 | Val acc: 48.92% | LR: 0.000098
Epoch: 030 | Train loss: 0.9835 | Train acc: 50.98% | Val loss: 1.0141 | Val acc: 48.92% | LR: 0.000098
Epoch: 031 | Train loss: 0.9748 | Train acc: 51.52% | Val loss: 1.0145 | Val acc: 48.88% | LR: 0.000097
Epoch: 032 | Train loss: 0.9840 | Train acc: 50.97% | Val loss: 1.0166 | Val acc: 48.76% | LR: 0.000096
Epoch: 033 | Train loss: 0.9911 | Train acc: 50.90% | Val loss: 1.0148 | Val acc: 49.16% | LR: 0.000096
Epoch: 034 | Train loss: 0.9828 | Train acc: 51.12% | Val loss: 1.0239 | Val acc: 48.85% | LR: 0.000095
Epoch: 035 | Train loss: 0.9857 | Train acc: 50.90% | Val loss: 1.0803 | Val acc: 48.54% | LR: 0.000094
Epoch: 036 | Train loss: 1.0036 | Train acc: 50.63% | Val loss: 1.0270 | Val acc: 48.99% | LR: 0.000093
Epoch: 037 | Train loss: 1.0022 | Train acc: 50.87% | Val loss: 1.0191 | Val acc: 49.08% | LR: 0.000092
Epoch: 038 | Train loss: 0.9800 | Train acc: 51.21% | Val loss: 1.0371 | Val acc: 48.46% | LR: 0.000092
Epoch: 039 | Train loss: 0.9738 | Train acc: 51.60% | Val loss: 1.1876 | Val acc: 47.87% | LR: 0.000091
Epoch: 040 | Train loss: 0.9826 | Train acc: 51.10% | Val loss: 1.0225 | Val acc: 48.62% | LR: 0.000090
Epoch: 041 | Train loss: 0.9845 | Train acc: 50.96% | Val loss: 1.0256 | Val acc: 48.62% | LR: 0.000089
Epoch: 042 | Train loss: 0.9806 | Train acc: 51.04% | Val loss: 1.0353 | Val acc: 48.26% | LR: 0.000088
Epoch: 043 | Train loss: 0.9817 | Train acc: 51.01% | Val loss: 1.0364 | Val acc: 48.25% | LR: 0.000087
Epoch: 044 | Train loss: 0.9804 | Train acc: 51.36% | Val loss: 1.0317 | Val acc: 48.44% | LR: 0.000086
Epoch: 045 | Train loss: 0.9759 | Train acc: 51.28% | Val loss: 1.0341 | Val acc: 48.54% | LR: 0.000086
Epoch: 046 | Train loss: 0.9844 | Train acc: 51.07% | Val loss: 1.0358 | Val acc: 48.24% | LR: 0.000085
Epoch: 047 | Train loss: 0.9882 | Train acc: 50.72% | Val loss: 1.0449 | Val acc: 48.42% | LR: 0.000084
Epoch: 048 | Train loss: 0.9852 | Train acc: 50.82% | Val loss: 1.0284 | Val acc: 48.67% | LR: 0.000083
Epoch: 049 | Train loss: 0.9809 | Train acc: 51.24% | Val loss: 1.0302 | Val acc: 48.47% | LR: 0.000082
Epoch: 050 | Train loss: 0.9797 | Train acc: 51.17% | Val loss: 1.0390 | Val acc: 48.50% | LR: 0.000081
Epoch: 051 | Train loss: 0.9897 | Train acc: 50.63% | Val loss: 1.0334 | Val acc: 48.68% | LR: 0.000080
Epoch: 052 | Train loss: 0.9844 | Train acc: 50.99% | Val loss: 1.0448 | Val acc: 48.66% | LR: 0.000079
Epoch: 053 | Train loss: 0.9837 | Train acc: 50.80% | Val loss: 1.0250 | Val acc: 48.65% | LR: 0.000078
Epoch: 054 | Train loss: 0.9835 | Train acc: 51.13% | Val loss: 1.0237 | Val acc: 48.63% | LR: 0.000077
Epoch: 055 | Train loss: 0.9829 | Train acc: 51.16% | Val loss: 1.0250 | Val acc: 48.65% | LR: 0.000076
Epoch: 056 | Train loss: 0.9871 | Train acc: 50.62% | Val loss: 1.0262 | Val acc: 48.65% | LR: 0.000075
Epoch: 057 | Train loss: 0.9883 | Train acc: 50.52% | Val loss: 1.0294 | Val acc: 48.79% | LR: 0.000074
Epoch: 058 | Train loss: 0.9904 | Train acc: 50.43% | Val loss: 1.0354 | Val acc: 48.80% | LR: 0.000072
Epoch: 059 | Train loss: 0.9774 | Train acc: 51.32% | Val loss: 1.0261 | Val acc: 48.75% | LR: 0.000071
Epoch: 060 | Train loss: 0.9933 | Train acc: 50.23% | Val loss: 1.0469 | Val acc: 48.73% | LR: 0.000070
Epoch: 061 | Train loss: 0.9760 | Train acc: 51.34% | Val loss: 1.0268 | Val acc: 48.58% | LR: 0.000069
Epoch: 062 | Train loss: 0.9760 | Train acc: 51.34% | Val loss: 1.0266 | Val acc: 48.67% | LR: 0.000068

[I 2025-09-23 16:36:05,868] Trial 22 finished with value: 0.48730652332305907 and parameters: {'lr': 0.00010859733713784369, 'hidden_size': 80, 'dropout': 0.3476761750959119, 'weight_decay': 5.707240119549038e-05}. Best is trial 10 with value: 0.5360925793647766.

Epoch: 000 | Train loss: 1.0014 | Train acc: 49.54% | Val loss: 0.9940 | Val acc: 54.09% | LR: 0.000046
Epoch: 001 | Train loss: 0.9999 | Train acc: 50.29% | Val loss: 0.9939 | Val acc: 54.26% | LR: 0.000046
Epoch: 002 | Train loss: 0.9992 | Train acc: 50.75% | Val loss: 0.9938 | Val acc: 54.34% | LR: 0.000046
Epoch: 003 | Train loss: 0.9993 | Train acc: 50.46% | Val loss: 0.9936 | Val acc: 54.41% | LR: 0.000046
Epoch: 004 | Train loss: 0.9986 | Train acc: 50.54% | Val loss: 0.9933 | Val acc: 54.49% | LR: 0.000046
Epoch: 005 | Train loss: 0.9976 | Train acc: 50.81% | Val loss: 0.9932 | Val acc: 54.59% | LR: 0.000046
Epoch: 006 | Train loss: 0.9979 | Train acc: 50.68% | Val loss: 0.9930 | Val acc: 54.43% | LR: 0.000046
Epoch: 007 | Train loss: 0.9995 | Train acc: 50.00% | Val loss: 0.9930 | Val acc: 54.48% | LR: 0.000046
Epoch: 008 | Train loss: 0.9993 | Train acc: 50.30% | Val loss: 0.9932 | Val acc: 54.20% | LR: 0.000045
Epoch: 009 | Train loss: 0.9988 | Train acc: 50.30% | Val loss: 0.9930 | Val acc: 54.09% | LR: 0.000045
Epoch: 010 | Train loss: 0.9988 | Train acc: 50.32% | Val loss: 0.9929 | Val acc: 54.03% | LR: 0.000045
Epoch: 011 | Train loss: 1.0009 | Train acc: 49.74% | Val loss: 0.9926 | Val acc: 54.02% | LR: 0.000045
Epoch: 012 | Train loss: 0.9985 | Train acc: 50.29% | Val loss: 0.9924 | Val acc: 54.41% | LR: 0.000045
Epoch: 013 | Train loss: 0.9964 | Train acc: 50.86% | Val loss: 0.9928 | Val acc: 54.26% | LR: 0.000045
Epoch: 014 | Train loss: 0.9957 | Train acc: 50.91% | Val loss: 0.9928 | Val acc: 54.00% | LR: 0.000045
Epoch: 015 | Train loss: 0.9982 | Train acc: 50.38% | Val loss: 0.9927 | Val acc: 53.60% | LR: 0.000045
Epoch: 016 | Train loss: 1.0090 | Train acc: 51.13% | Val loss: 0.9925 | Val acc: 53.59% | LR: 0.000044
Epoch: 017 | Train loss: 0.9945 | Train acc: 51.38% | Val loss: 0.9924 | Val acc: 53.80% | LR: 0.000044
Epoch: 018 | Train loss: 0.9970 | Train acc: 50.86% | Val loss: 0.9921 | Val acc: 53.57% | LR: 0.000044
Epoch: 019 | Train loss: 0.9961 | Train acc: 50.83% | Val loss: 0.9918 | Val acc: 53.49% | LR: 0.000044
Epoch: 020 | Train loss: 0.9969 | Train acc: 50.75% | Val loss: 0.9914 | Val acc: 53.36% | LR: 0.000044
Epoch: 021 | Train loss: 0.9946 | Train acc: 51.03% | Val loss: 0.9908 | Val acc: 53.40% | LR: 0.000044
Epoch: 022 | Train loss: 0.9943 | Train acc: 50.96% | Val loss: 0.9901 | Val acc: 53.28% | LR: 0.000043
Epoch: 023 | Train loss: 0.9983 | Train acc: 50.06% | Val loss: 0.9902 | Val acc: 53.26% | LR: 0.000043
Epoch: 024 | Train loss: 0.9874 | Train acc: 51.45% | Val loss: 0.9897 | Val acc: 53.14% | LR: 0.000043
Epoch: 025 | Train loss: 0.9954 | Train acc: 50.40% | Val loss: 0.9893 | Val acc: 53.16% | LR: 0.000043
Epoch: 026 | Train loss: 0.9876 | Train acc: 51.23% | Val loss: 0.9890 | Val acc: 53.14% | LR: 0.000042
Epoch: 027 | Train loss: 0.9930 | Train acc: 50.80% | Val loss: 0.9883 | Val acc: 52.97% | LR: 0.000042
Epoch: 028 | Train loss: 0.9939 | Train acc: 50.97% | Val loss: 0.9880 | Val acc: 52.85% | LR: 0.000042
Epoch: 029 | Train loss: 0.9912 | Train acc: 50.72% | Val loss: 0.9875 | Val acc: 52.87% | LR: 0.000042
Epoch: 030 | Train loss: 0.9886 | Train acc: 51.24% | Val loss: 0.9866 | Val acc: 52.87% | LR: 0.000041
Epoch: 031 | Train loss: 0.9899 | Train acc: 50.98% | Val loss: 0.9860 | Val acc: 52.85% | LR: 0.000041
Epoch: 032 | Train loss: 0.9834 | Train acc: 51.60% | Val loss: 0.9850 | Val acc: 52.85% | LR: 0.000041
Epoch: 033 | Train loss: 0.9894 | Train acc: 51.16% | Val loss: 0.9843 | Val acc: 52.75% | LR: 0.000040
Epoch: 034 | Train loss: 0.9911 | Train acc: 50.80% | Val loss: 0.9832 | Val acc: 52.75% | LR: 0.000040
Epoch: 035 | Train loss: 0.9835 | Train acc: 51.94% | Val loss: 0.9817 | Val acc: 52.77% | LR: 0.000040
Epoch: 036 | Train loss: 0.9855 | Train acc: 51.58% | Val loss: 0.9806 | Val acc: 52.75% | LR: 0.000039
Epoch: 037 | Train loss: 0.9886 | Train acc: 50.96% | Val loss: 0.9792 | Val acc: 52.77% | LR: 0.000039
Epoch: 038 | Train loss: 0.9879 | Train acc: 51.04% | Val loss: 0.9775 | Val acc: 52.73% | LR: 0.000039
Epoch: 039 | Train loss: 0.9903 | Train acc: 50.70% | Val loss: 0.9759 | Val acc: 52.64% | LR: 0.000038
Epoch: 040 | Train loss: 0.9895 | Train acc: 50.78% | Val loss: 0.9751 | Val acc: 52.63% | LR: 0.000038
Epoch: 041 | Train loss: 0.9833 | Train acc: 51.50% | Val loss: 0.9747 | Val acc: 52.54% | LR: 0.000038
Epoch: 042 | Train loss: 0.9886 | Train acc: 50.88% | Val loss: 0.9746 | Val acc: 52.38% | LR: 0.000037
Epoch: 043 | Train loss: 0.9854 | Train acc: 51.14% | Val loss: 0.9754 | Val acc: 52.34% | LR: 0.000037
Epoch: 044 | Train loss: 0.9857 | Train acc: 50.78% | Val loss: 0.9754 | Val acc: 52.26% | LR: 0.000037
Epoch: 045 | Train loss: 0.9853 | Train acc: 51.22% | Val loss: 0.9760 | Val acc: 52.00% | LR: 0.000036
Epoch: 046 | Train loss: 0.9877 | Train acc: 50.78% | Val loss: 0.9758 | Val acc: 51.94% | LR: 0.000036
Epoch: 047 | Train loss: 0.9864 | Train acc: 50.78% | Val loss: 0.9762 | Val acc: 51.71% | LR: 0.000035
Epoch: 048 | Train loss: 0.9860 | Train acc: 50.95% | Val loss: 0.9765 | Val acc: 51.73% | LR: 0.000035
Epoch: 049 | Train loss: 0.9911 | Train acc: 51.41% | Val loss: 0.9772 | Val acc: 51.47% | LR: 0.000035
Epoch: 050 | Train loss: 0.9837 | Train acc: 51.06% | Val loss: 0.9781 | Val acc: 51.49% | LR: 0.000034
Epoch: 051 | Train loss: 0.9873 | Train acc: 51.08% | Val loss: 1.0151 | Val acc: 51.11% | LR: 0.000034
Epoch: 052 | Train loss: 1.0010 | Train acc: 51.15% | Val loss: 1.0032 | Val acc: 51.34% | LR: 0.000033
Epoch: 053 | Train loss: 0.9844 | Train acc: 51.47% | Val loss: 0.9844 | Val acc: 51.35% | LR: 0.000033
Epoch: 054 | Train loss: 0.9951 | Train acc: 50.78% | Val loss: 0.9867 | Val acc: 51.30% | LR: 0.000033

[I 2025-09-23 16:36:50,972] Trial 23 finished with value: 0.5151943445205689 and parameters: {'lr': 4.5893714626423916e-05, 'hidden_size': 66, 'dropout': 0.18913388112157392, 'weight_decay': 0.00043172332150398794}. Best is trial 10 with value: 0.5360925793647766.

Epoch: 000 | Train loss: 1.0001 | Train acc: 50.19% | Val loss: 0.9968 | Val acc: 53.99% | LR: 0.000017
Epoch: 001 | Train loss: 0.9993 | Train acc: 50.46% | Val loss: 0.9968 | Val acc: 53.97% | LR: 0.000017
Epoch: 002 | Train loss: 0.9997 | Train acc: 50.10% | Val loss: 0.9969 | Val acc: 53.97% | LR: 0.000017
Epoch: 003 | Train loss: 0.9993 | Train acc: 50.27% | Val loss: 0.9968 | Val acc: 53.99% | LR: 0.000017
Epoch: 004 | Train loss: 0.9988 | Train acc: 50.46% | Val loss: 0.9965 | Val acc: 54.01% | LR: 0.000017
Epoch: 005 | Train loss: 1.0003 | Train acc: 49.63% | Val loss: 0.9962 | Val acc: 53.95% | LR: 0.000017
Epoch: 006 | Train loss: 0.9999 | Train acc: 49.96% | Val loss: 0.9998 | Val acc: 53.59% | LR: 0.000017
Epoch: 007 | Train loss: 0.9995 | Train acc: 50.64% | Val loss: 0.9963 | Val acc: 53.86% | LR: 0.000017
Epoch: 008 | Train loss: 0.9984 | Train acc: 50.17% | Val loss: 1.0009 | Val acc: 53.72% | LR: 0.000017
Epoch: 009 | Train loss: 0.9976 | Train acc: 50.64% | Val loss: 0.9970 | Val acc: 53.68% | LR: 0.000017
Epoch: 010 | Train loss: 0.9974 | Train acc: 50.97% | Val loss: 0.9988 | Val acc: 53.86% | LR: 0.000017
Epoch: 011 | Train loss: 0.9985 | Train acc: 50.48% | Val loss: 0.9962 | Val acc: 53.90% | LR: 0.000017
Epoch: 012 | Train loss: 1.0001 | Train acc: 50.29% | Val loss: 0.9976 | Val acc: 53.25% | LR: 0.000017
Epoch: 013 | Train loss: 0.9981 | Train acc: 50.72% | Val loss: 0.9977 | Val acc: 53.73% | LR: 0.000017
Epoch: 014 | Train loss: 0.9992 | Train acc: 50.23% | Val loss: 0.9975 | Val acc: 53.94% | LR: 0.000017
Epoch: 015 | Train loss: 0.9975 | Train acc: 50.86% | Val loss: 0.9977 | Val acc: 53.72% | LR: 0.000017
Epoch: 016 | Train loss: 1.1656 | Train acc: 51.46% | Val loss: 0.9967 | Val acc: 53.74% | LR: 0.000017
Epoch: 017 | Train loss: 0.9998 | Train acc: 49.89% | Val loss: 1.0032 | Val acc: 53.74% | LR: 0.000017
Epoch: 018 | Train loss: 1.0030 | Train acc: 50.43% | Val loss: 0.9956 | Val acc: 54.04% | LR: 0.000016
Epoch: 019 | Train loss: 0.9976 | Train acc: 50.73% | Val loss: 0.9977 | Val acc: 54.00% | LR: 0.000016
Epoch: 020 | Train loss: 0.9994 | Train acc: 50.49% | Val loss: 1.0060 | Val acc: 53.92% | LR: 0.000016
Epoch: 021 | Train loss: 1.0001 | Train acc: 50.02% | Val loss: 0.9980 | Val acc: 53.60% | LR: 0.000016
Epoch: 022 | Train loss: 0.9991 | Train acc: 50.19% | Val loss: 0.9961 | Val acc: 53.84% | LR: 0.000016
Epoch: 023 | Train loss: 0.9983 | Train acc: 50.36% | Val loss: 0.9978 | Val acc: 53.70% | LR: 0.000016
Epoch: 024 | Train loss: 1.0010 | Train acc: 49.93% | Val loss: 0.9964 | Val acc: 53.76% | LR: 0.000016
Epoch: 025 | Train loss: 0.9964 | Train acc: 50.87% | Val loss: 0.9948 | Val acc: 54.03% | LR: 0.000016
Epoch: 026 | Train loss: 0.9985 | Train acc: 50.29% | Val loss: 0.9982 | Val acc: 53.58% | LR: 0.000016
Epoch: 027 | Train loss: 0.9964 | Train acc: 50.58% | Val loss: 0.9992 | Val acc: 53.74% | LR: 0.000016
Epoch: 028 | Train loss: 0.9989 | Train acc: 50.23% | Val loss: 0.9986 | Val acc: 53.55% | LR: 0.000016
Epoch: 029 | Train loss: 0.9961 | Train acc: 50.84% | Val loss: 0.9964 | Val acc: 53.86% | LR: 0.000016
Epoch: 030 | Train loss: 0.9997 | Train acc: 49.96% | Val loss: 1.0043 | Val acc: 53.90% | LR: 0.000015
Epoch: 031 | Train loss: 0.9965 | Train acc: 50.45% | Val loss: 0.9969 | Val acc: 53.97% | LR: 0.000015
Epoch: 032 | Train loss: 0.9963 | Train acc: 50.92% | Val loss: 0.9996 | Val acc: 54.03% | LR: 0.000015
Epoch: 033 | Train loss: 0.9953 | Train acc: 50.86% | Val loss: 1.0097 | Val acc: 54.20% | LR: 0.000015
Epoch: 034 | Train loss: 0.9988 | Train acc: 50.01% | Val loss: 0.9985 | Val acc: 53.80% | LR: 0.000015
Epoch: 035 | Train loss: 0.9956 | Train acc: 50.49% | Val loss: 0.9982 | Val acc: 54.22% | LR: 0.000015
Epoch: 036 | Train loss: 0.9996 | Train acc: 50.12% | Val loss: 0.9967 | Val acc: 53.96% | LR: 0.000015
Epoch: 037 | Train loss: 0.9983 | Train acc: 50.48% | Val loss: 0.9988 | Val acc: 53.87% | LR: 0.000015
Epoch: 038 | Train loss: 0.9984 | Train acc: 50.20% | Val loss: 0.9967 | Val acc: 53.95% | LR: 0.000015
Epoch: 039 | Train loss: 0.9947 | Train acc: 50.63% | Val loss: 0.9976 | Val acc: 54.08% | LR: 0.000014
Epoch: 040 | Train loss: 0.9950 | Train acc: 50.55% | Val loss: 0.9970 | Val acc: 53.85% | LR: 0.000014
Epoch: 041 | Train loss: 0.9966 | Train acc: 50.39% | Val loss: 0.9978 | Val acc: 53.81% | LR: 0.000014
Epoch: 042 | Train loss: 1.0030 | Train acc: 49.99% | Val loss: 0.9956 | Val acc: 54.32% | LR: 0.000014
Epoch: 043 | Train loss: 0.9927 | Train acc: 51.07% | Val loss: 0.9969 | Val acc: 53.73% | LR: 0.000014
Epoch: 044 | Train loss: 0.9948 | Train acc: 50.64% | Val loss: 1.3807 | Val acc: 53.99% | LR: 0.000014
Epoch: 045 | Train loss: 0.9975 | Train acc: 50.20% | Val loss: 1.0006 | Val acc: 53.75% | LR: 0.000014
Epoch: 046 | Train loss: 0.9903 | Train acc: 51.34% | Val loss: 0.9980 | Val acc: 53.69% | LR: 0.000014
Epoch: 047 | Train loss: 0.9996 | Train acc: 50.04% | Val loss: 0.9986 | Val acc: 53.97% | LR: 0.000013
Epoch: 048 | Train loss: 0.9970 | Train acc: 50.53% | Val loss: 0.9990 | Val acc: 53.83% | LR: 0.000013
Epoch: 049 | Train loss: 0.9951 | Train acc: 50.74% | Val loss: 0.9958 | Val acc: 54.30% | LR: 0.000013
Epoch: 050 | Train loss: 0.9983 | Train acc: 50.19% | Val loss: 1.0044 | Val acc: 54.09% | LR: 0.000013
Epoch: 051 | Train loss: 0.9938 | Train acc: 50.71% | Val loss: 0.9984 | Val acc: 54.10% | LR: 0.000013
Epoch: 052 | Train loss: 0.9967 | Train acc: 50.33% | Val loss: 0.9980 | Val acc: 54.23% | LR: 0.000013
Epoch: 053 | Train loss: 0.9927 | Train acc: 50.81% | Val loss: 0.9964 | Val acc: 54.03% | LR: 0.000012
Epoch: 054 | Train loss: 0.9963 | Train acc: 50.45% | Val loss: 0.9984 | Val acc: 54.15% | LR: 0.000012
Epoch: 055 | Train loss: 0.9946 | Train acc: 50.74% | Val loss: 0.9967 | Val acc: 54.26% | LR: 0.000012
Epoch: 056 | Train loss: 0.9966 | Train acc: 50.49% | Val loss: 1.0002 | Val acc: 54.13% | LR: 0.000012
Epoch: 057 | Train loss: 0.9965 | Train acc: 50.56% | Val loss: 1.0002 | Val acc: 54.29% | LR: 0.000012
Epoch: 058 | Train loss: 0.9964 | Train acc: 50.46% | Val loss: 0.9974 | Val acc: 54.02% | LR: 0.000012
Epoch: 059 | Train loss: 0.9998 | Train acc: 50.21% | Val loss: 0.9970 | Val acc: 53.93% | LR: 0.000012
Epoch: 060 | Train loss: 0.9938 | Train acc: 50.92% | Val loss: 0.9956 | Val acc: 54.21% | LR: 0.000011
Epoch: 061 | Train loss: 0.9952 | Train acc: 50.55% | Val loss: 0.9987 | Val acc: 54.09% | LR: 0.000011
Epoch: 062 | Train loss: 0.9958 | Train acc: 50.41% | Val loss: 0.9982 | Val acc: 54.15% | LR: 0.000011
Epoch: 063 | Train loss: 0.9962 | Train acc: 50.53% | Val loss: 0.9981 | Val acc: 54.07% | LR: 0.000011
Epoch: 064 | Train loss: 0.9991 | Train acc: 49.93% | Val loss: 0.9965 | Val acc: 54.23% | LR: 0.000011
Epoch: 065 | Train loss: 0.9940 | Train acc: 50.57% | Val loss: 0.9973 | Val acc: 54.33% | LR: 0.000011
Epoch: 066 | Train loss: 0.9960 | Train acc: 50.38% | Val loss: 0.9966 | Val acc: 54.39% | LR: 0.000010
Epoch: 067 | Train loss: 0.9977 | Train acc: 50.24% | Val loss: 0.9974 | Val acc: 54.35% | LR: 0.000010
Epoch: 068 | Train loss: 0.9933 | Train acc: 50.67% | Val loss: 0.9966 | Val acc: 54.43% | LR: 0.000010
Epoch: 069 | Train loss: 0.9947 | Train acc: 50.49% | Val loss: 0.9984 | Val acc: 54.57% | LR: 0.000010
Epoch: 070 | Train loss: 0.9948 | Train acc: 50.33% | Val loss: 0.9974 | Val acc: 54.63% | LR: 0.000010
Epoch: 071 | Train loss: 0.9925 | Train acc: 50.70% | Val loss: 0.9982 | Val acc: 54.90% | LR: 0.000010
Epoch: 072 | Train loss: 0.9911 | Train acc: 50.66% | Val loss: 0.9979 | Val acc: 55.10% | LR: 0.000009
Epoch: 073 | Train loss: 0.9935 | Train acc: 50.76% | Val loss: 0.9976 | Val acc: 54.88% | LR: 0.000009
Epoch: 074 | Train loss: 0.9948 | Train acc: 50.55% | Val loss: 0.9971 | Val acc: 54.27% | LR: 0.000009
Epoch: 075 | Train loss: 0.9940 | Train acc: 50.76% | Val loss: 0.9986 | Val acc: 54.66% | LR: 0.000009
Epoch: 076 | Train loss: 0.9958 | Train acc: 50.52% | Val loss: 0.9969 | Val acc: 54.38% | LR: 0.000009
Epoch: 077 | Train loss: 1.0296 | Train acc: 50.84% | Val loss: 0.9974 | Val acc: 54.46% | LR: 0.000009
Epoch: 078 | Train loss: 0.9933 | Train acc: 50.65% | Val loss: 0.9993 | Val acc: 54.56% | LR: 0.000008
Epoch: 079 | Train loss: 0.9931 | Train acc: 50.37% | Val loss: 1.0006 | Val acc: 54.54% | LR: 0.000008
Epoch: 080 | Train loss: 0.9939 | Train acc: 50.80% | Val loss: 0.9984 | Val acc: 54.49% | LR: 0.000008
Epoch: 081 | Train loss: 0.9909 | Train acc: 50.83% | Val loss: 0.9968 | Val acc: 54.43% | LR: 0.000008
Epoch: 082 | Train loss: 0.9933 | Train acc: 50.85% | Val loss: 0.9967 | Val acc: 54.34% | LR: 0.000008
Epoch: 083 | Train loss: 0.9981 | Train acc: 50.20% | Val loss: 0.9977 | Val acc: 54.28% | LR: 0.000008
Epoch: 084 | Train loss: 0.9983 | Train acc: 50.20% | Val loss: 0.9959 | Val acc: 54.30% | LR: 0.000007
Epoch: 085 | Train loss: 0.9914 | Train acc: 50.97% | Val loss: 0.9997 | Val acc: 54.23% | LR: 0.000007
Epoch: 086 | Train loss: 0.9934 | Train acc: 50.44% | Val loss: 0.9969 | Val acc: 54.29% | LR: 0.000007
Epoch: 087 | Train loss: 0.9935 | Train acc: 50.60% | Val loss: 0.9985 | Val acc: 54.26% | LR: 0.000007
Epoch: 088 | Train loss: 0.9932 | Train acc: 50.46% | Val loss: 0.9980 | Val acc: 54.23% | LR: 0.000007
Epoch: 089 | Train loss: 0.9931 | Train acc: 50.64% | Val loss: 0.9975 | Val acc: 54.24% | LR: 0.000007
Epoch: 090 | Train loss: 0.9909 | Train acc: 50.59% | Val loss: 1.0028 | Val acc: 54.52% | LR: 0.000006
Epoch: 091 | Train loss: 0.9940 | Train acc: 50.46% | Val loss: 0.9978 | Val acc: 54.14% | LR: 0.000006
Epoch: 092 | Train loss: 0.9880 | Train acc: 51.05% | Val loss: 0.9981 | Val acc: 54.30% | LR: 0.000006
Epoch: 093 | Train loss: 0.9913 | Train acc: 50.97% | Val loss: 0.9984 | Val acc: 54.27% | LR: 0.000006
Epoch: 094 | Train loss: 0.9957 | Train acc: 50.43% | Val loss: 0.9998 | Val acc: 54.32% | LR: 0.000006
Epoch: 095 | Train loss: 0.9960 | Train acc: 50.52% | Val loss: 0.9992 | Val acc: 54.19% | LR: 0.000006
Epoch: 096 | Train loss: 0.9931 | Train acc: 50.43% | Val loss: 0.9981 | Val acc: 53.95% | LR: 0.000005
Epoch: 097 | Train loss: 0.9858 | Train acc: 51.12% | Val loss: 1.0006 | Val acc: 53.91% | LR: 0.000005
Epoch: 098 | Train loss: 0.9980 | Train acc: 50.22% | Val loss: 0.9983 | Val acc: 54.05% | LR: 0.000005
Epoch: 099 | Train loss: 0.9948 | Train acc: 50.11% | Val loss: 1.0037 | Val acc: 54.19% | LR: 0.000005
Epoch: 100 | Train loss: 0.9967 | Train acc: 50.36% | Val loss: 1.0026 | Val acc: 54.16% | LR: 0.000005
Epoch: 101 | Train loss: 0.9968 | Train acc: 50.35% | Val loss: 0.9996 | Val acc: 54.08% | LR: 0.000005
Epoch: 102 | Train loss: 0.9896 | Train acc: 50.78% | Val loss: 1.0339 | Val acc: 54.21% | LR: 0.000005
Epoch: 103 | Train loss: 0.9918 | Train acc: 50.51% | Val loss: 0.9987 | Val acc: 54.06% | LR: 0.000004
Epoch: 104 | Train loss: 0.9910 | Train acc: 50.79% | Val loss: 1.0038 | Val acc: 54.14% | LR: 0.000004
Epoch: 105 | Train loss: 0.9952 | Train acc: 50.78% | Val loss: 1.0114 | Val acc: 54.05% | LR: 0.000004
Epoch: 106 | Train loss: 0.9903 | Train acc: 50.61% | Val loss: 0.9972 | Val acc: 54.10% | LR: 0.000004
Epoch: 107 | Train loss: 0.9915 | Train acc: 50.81% | Val loss: 0.9982 | Val acc: 54.17% | LR: 0.000004
Epoch: 108 | Train loss: 0.9948 | Train acc: 50.34% | Val loss: 1.0283 | Val acc: 54.04% | LR: 0.000004
Epoch: 109 | Train loss: 0.9941 | Train acc: 50.50% | Val loss: 1.0009 | Val acc: 54.21% | LR: 0.000004
Epoch: 110 | Train loss: 0.9958 | Train acc: 50.42% | Val loss: 1.0230 | Val acc: 54.17% | LR: 0.000004
Epoch: 111 | Train loss: 0.9939 | Train acc: 50.42% | Val loss: 0.9976 | Val acc: 54.24% | LR: 0.000003
Epoch: 112 | Train loss: 0.9968 | Train acc: 49.94% | Val loss: 0.9991 | Val acc: 54.12% | LR: 0.000003
Epoch: 113 | Train loss: 0.9871 | Train acc: 51.01% | Val loss: 14.8196 | Val acc: 54.13% | LR: 0.000003
Epoch: 114 | Train loss: 0.9950 | Train acc: 50.18% | Val loss: 1.0016 | Val acc: 54.10% | LR: 0.000003
Epoch: 115 | Train loss: 0.9943 | Train acc: 50.21% | Val loss: 0.9992 | Val acc: 54.26% | LR: 0.000003
Epoch: 116 | Train loss: 0.9917 | Train acc: 50.74% | Val loss: 0.9990 | Val acc: 54.22% | LR: 0.000003
Epoch: 117 | Train loss: 0.9949 | Train acc: 50.12% | Val loss: 1.0010 | Val acc: 54.16% | LR: 0.000003
Epoch: 118 | Train loss: 0.9924 | Train acc: 50.54% | Val loss: 1.0008 | Val acc: 54.26% | LR: 0.000003
Epoch: 119 | Train loss: 0.9959 | Train acc: 50.11% | Val loss: 0.9998 | Val acc: 54.22% | LR: 0.000003
Epoch: 120 | Train loss: 0.9944 | Train acc: 50.11% | Val loss: 0.9991 | Val acc: 54.38% | LR: 0.000002
Epoch: 121 | Train loss: 0.9841 | Train acc: 51.38% | Val loss: 1.0022 | Val acc: 54.44% | LR: 0.000002

[I 2025-09-23 16:38:51,222] Trial 24 finished with value: 0.5445964932441711 and parameters: {'lr': 1.7121866385803483e-05, 'hidden_size': 113, 'dropout': 0.2885791978208061, 'weight_decay': 6.840793496315994e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9972 | Train acc: 50.69% | Val loss: 1.0144 | Val acc: 46.45% | LR: 0.000017
Epoch: 001 | Train loss: 0.9999 | Train acc: 51.14% | Val loss: 1.0090 | Val acc: 46.23% | LR: 0.000017
Epoch: 002 | Train loss: 1.0006 | Train acc: 49.87% | Val loss: 1.0070 | Val acc: 46.15% | LR: 0.000017
Epoch: 003 | Train loss: 0.9976 | Train acc: 50.81% | Val loss: 1.0316 | Val acc: 45.64% | LR: 0.000017
Epoch: 004 | Train loss: 0.9978 | Train acc: 50.55% | Val loss: 1.0082 | Val acc: 45.77% | LR: 0.000017
Epoch: 005 | Train loss: 0.9998 | Train acc: 50.22% | Val loss: 1.0102 | Val acc: 46.13% | LR: 0.000017
Epoch: 006 | Train loss: 0.9995 | Train acc: 50.29% | Val loss: 1.0154 | Val acc: 46.49% | LR: 0.000017
Epoch: 007 | Train loss: 1.0003 | Train acc: 50.03% | Val loss: 1.0084 | Val acc: 45.63% | LR: 0.000017
Epoch: 008 | Train loss: 0.9994 | Train acc: 50.05% | Val loss: 1.0214 | Val acc: 46.16% | LR: 0.000017
Epoch: 009 | Train loss: 0.9971 | Train acc: 50.39% | Val loss: 1.0197 | Val acc: 46.05% | LR: 0.000017
Epoch: 010 | Train loss: 0.9955 | Train acc: 50.65% | Val loss: 1.0099 | Val acc: 45.90% | LR: 0.000017
Epoch: 011 | Train loss: 0.9999 | Train acc: 49.75% | Val loss: 1.0118 | Val acc: 46.05% | LR: 0.000017
Epoch: 012 | Train loss: 0.9991 | Train acc: 50.11% | Val loss: 1.0277 | Val acc: 46.10% | LR: 0.000017
Epoch: 013 | Train loss: 0.9941 | Train acc: 50.80% | Val loss: 1.0121 | Val acc: 45.93% | LR: 0.000016
Epoch: 014 | Train loss: 0.9964 | Train acc: 50.45% | Val loss: 1.0031 | Val acc: 46.46% | LR: 0.000016
Epoch: 015 | Train loss: 0.9998 | Train acc: 49.95% | Val loss: 1.0080 | Val acc: 46.43% | LR: 0.000016
Epoch: 016 | Train loss: 0.9978 | Train acc: 50.16% | Val loss: 1.0085 | Val acc: 46.25% | LR: 0.000016
Epoch: 017 | Train loss: 0.9927 | Train acc: 50.77% | Val loss: 1.0305 | Val acc: 45.91% | LR: 0.000016
Epoch: 018 | Train loss: 0.9988 | Train acc: 49.89% | Val loss: 1.0147 | Val acc: 46.01% | LR: 0.000016
Epoch: 019 | Train loss: 1.0011 | Train acc: 50.00% | Val loss: 1.0077 | Val acc: 45.96% | LR: 0.000016
Epoch: 020 | Train loss: 0.9941 | Train acc: 50.75% | Val loss: 1.0063 | Val acc: 45.91% | LR: 0.000016
Epoch: 021 | Train loss: 0.9985 | Train acc: 50.18% | Val loss: 1.0060 | Val acc: 45.91% | LR: 0.000016
Epoch: 022 | Train loss: 0.9919 | Train acc: 51.06% | Val loss: 1.0551 | Val acc: 45.83% | LR: 0.000016
Epoch: 023 | Train loss: 0.9971 | Train acc: 50.37% | Val loss: 1.0051 | Val acc: 45.95% | LR: 0.000016
Epoch: 024 | Train loss: 1.0028 | Train acc: 50.87% | Val loss: 1.0055 | Val acc: 45.71% | LR: 0.000016
Epoch: 025 | Train loss: 0.9912 | Train acc: 51.11% | Val loss: 1.0075 | Val acc: 46.36% | LR: 0.000016
Epoch: 026 | Train loss: 1.0022 | Train acc: 49.79% | Val loss: 1.0066 | Val acc: 46.29% | LR: 0.000016
Epoch: 027 | Train loss: 0.9881 | Train acc: 51.04% | Val loss: 1.0047 | Val acc: 45.90% | LR: 0.000016
Epoch: 028 | Train loss: 0.9929 | Train acc: 50.69% | Val loss: 1.0045 | Val acc: 46.24% | LR: 0.000015
Epoch: 029 | Train loss: 0.9977 | Train acc: 50.15% | Val loss: 1.0044 | Val acc: 46.14% | LR: 0.000015
Epoch: 030 | Train loss: 0.9928 | Train acc: 50.61% | Val loss: 1.0041 | Val acc: 46.16% | LR: 0.000015
Epoch: 031 | Train loss: 0.9959 | Train acc: 50.22% | Val loss: 1.0131 | Val acc: 46.28% | LR: 0.000015
Epoch: 032 | Train loss: 0.9963 | Train acc: 50.57% | Val loss: 1.0064 | Val acc: 46.18% | LR: 0.000015
Epoch: 033 | Train loss: 0.9915 | Train acc: 50.80% | Val loss: 1.0185 | Val acc: 45.96% | LR: 0.000015
Epoch: 034 | Train loss: 0.9951 | Train acc: 50.33% | Val loss: 1.0073 | Val acc: 46.18% | LR: 0.000015
Epoch: 035 | Train loss: 0.9922 | Train acc: 50.85% | Val loss: 1.0045 | Val acc: 46.20% | LR: 0.000015
Epoch: 036 | Train loss: 0.9953 | Train acc: 50.39% | Val loss: 1.0053 | Val acc: 46.10% | LR: 0.000015
Epoch: 037 | Train loss: 0.9937 | Train acc: 50.58% | Val loss: 1.0101 | Val acc: 45.72% | LR: 0.000014
Epoch: 038 | Train loss: 0.9896 | Train acc: 50.95% | Val loss: 1.0029 | Val acc: 45.66% | LR: 0.000014
Epoch: 039 | Train loss: 0.9891 | Train acc: 50.93% | Val loss: 1.0049 | Val acc: 46.17% | LR: 0.000014
Epoch: 040 | Train loss: 0.9877 | Train acc: 50.84% | Val loss: 1.0102 | Val acc: 46.41% | LR: 0.000014
Epoch: 041 | Train loss: 0.9913 | Train acc: 50.68% | Val loss: 1.0045 | Val acc: 45.90% | LR: 0.000014
Epoch: 042 | Train loss: 0.9937 | Train acc: 50.66% | Val loss: 1.0214 | Val acc: 45.76% | LR: 0.000014
Epoch: 043 | Train loss: 0.9951 | Train acc: 50.41% | Val loss: 1.0034 | Val acc: 45.92% | LR: 0.000014
Epoch: 044 | Train loss: 0.9923 | Train acc: 50.69% | Val loss: 1.0052 | Val acc: 45.88% | LR: 0.000014
Epoch: 045 | Train loss: 0.9996 | Train acc: 50.06% | Val loss: 1.0035 | Val acc: 45.68% | LR: 0.000013
Epoch: 046 | Train loss: 1.0010 | Train acc: 50.06% | Val loss: 1.0033 | Val acc: 46.26% | LR: 0.000013
Epoch: 047 | Train loss: 0.9907 | Train acc: 50.55% | Val loss: 1.0079 | Val acc: 45.72% | LR: 0.000013
Epoch: 048 | Train loss: 0.9960 | Train acc: 50.31% | Val loss: 1.0044 | Val acc: 46.00% | LR: 0.000013
Epoch: 049 | Train loss: 0.9887 | Train acc: 50.82% | Val loss: 1.0033 | Val acc: 46.20% | LR: 0.000013
Epoch: 050 | Train loss: 0.9953 | Train acc: 50.38% | Val loss: 1.0083 | Val acc: 45.72% | LR: 0.000013
Epoch: 051 | Train loss: 0.9856 | Train acc: 50.95% | Val loss: 1.0049 | Val acc: 45.82% | LR: 0.000013
Epoch: 052 | Train loss: 1.0008 | Train acc: 49.83% | Val loss: 1.0065 | Val acc: 45.88% | LR: 0.000012
Epoch: 053 | Train loss: 1.0011 | Train acc: 50.05% | Val loss: 1.0031 | Val acc: 45.92% | LR: 0.000012
Epoch: 054 | Train loss: 0.9872 | Train acc: 50.90% | Val loss: 1.0032 | Val acc: 45.86% | LR: 0.000012
Epoch: 055 | Train loss: 1.0005 | Train acc: 49.97% | Val loss: 1.0058 | Val acc: 46.28% | LR: 0.000012

[I 2025-09-23 16:39:42,165] Trial 25 finished with value: 0.46217218041419983 and parameters: {'lr': 1.6829277250763144e-05, 'hidden_size': 118, 'dropout': 0.2822836901810229, 'weight_decay': 1.5423140452100903e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9944 | Train acc: 50.70% | Val loss: 0.9941 | Val acc: 51.00% | LR: 0.001578
Epoch: 001 | Train loss: 0.9909 | Train acc: 50.80% | Val loss: 0.9961 | Val acc: 50.87% | LR: 0.001577
Epoch: 002 | Train loss: 0.9842 | Train acc: 51.18% | Val loss: 1.0058 | Val acc: 49.81% | LR: 0.001577
Epoch: 003 | Train loss: 0.9873 | Train acc: 51.49% | Val loss: 1.0375 | Val acc: 47.85% | LR: 0.001575
Epoch: 004 | Train loss: 0.9835 | Train acc: 51.03% | Val loss: 1.0070 | Val acc: 49.39% | LR: 0.001574
Epoch: 005 | Train loss: 0.9833 | Train acc: 51.14% | Val loss: 1.0103 | Val acc: 49.17% | LR: 0.001572
Epoch: 006 | Train loss: 0.9822 | Train acc: 50.99% | Val loss: 1.0190 | Val acc: 48.85% | LR: 0.001570
Epoch: 007 | Train loss: 0.9885 | Train acc: 50.70% | Val loss: 1.0528 | Val acc: 48.27% | LR: 0.001567
Epoch: 008 | Train loss: 0.9887 | Train acc: 50.92% | Val loss: 1.0340 | Val acc: 49.20% | LR: 0.001564
Epoch: 009 | Train loss: 0.9931 | Train acc: 51.32% | Val loss: 0.9617 | Val acc: 52.70% | LR: 0.001561
Epoch: 010 | Train loss: 0.9924 | Train acc: 50.68% | Val loss: 0.9827 | Val acc: 51.96% | LR: 0.001557
Epoch: 011 | Train loss: 0.9923 | Train acc: 50.65% | Val loss: 0.9790 | Val acc: 51.47% | LR: 0.001553
Epoch: 012 | Train loss: 0.9849 | Train acc: 51.03% | Val loss: 1.0143 | Val acc: 49.81% | LR: 0.001549
Epoch: 013 | Train loss: 0.9825 | Train acc: 51.28% | Val loss: 1.0239 | Val acc: 48.85% | LR: 0.001544
Epoch: 014 | Train loss: 0.9887 | Train acc: 50.72% | Val loss: 1.0415 | Val acc: 48.44% | LR: 0.001540
Epoch: 015 | Train loss: 0.9855 | Train acc: 51.08% | Val loss: 1.0069 | Val acc: 49.34% | LR: 0.001534
Epoch: 016 | Train loss: 1.0170 | Train acc: 50.87% | Val loss: 1.0351 | Val acc: 48.35% | LR: 0.001529
Epoch: 017 | Train loss: 0.9841 | Train acc: 51.12% | Val loss: 1.0328 | Val acc: 49.11% | LR: 0.001523
Epoch: 018 | Train loss: 0.9908 | Train acc: 50.94% | Val loss: 1.0417 | Val acc: 48.40% | LR: 0.001517
Epoch: 019 | Train loss: 0.9930 | Train acc: 50.66% | Val loss: 1.0318 | Val acc: 48.69% | LR: 0.001510
Epoch: 020 | Train loss: 0.9847 | Train acc: 51.36% | Val loss: 1.0157 | Val acc: 49.98% | LR: 0.001503
Epoch: 021 | Train loss: 0.9884 | Train acc: 51.03% | Val loss: 1.0023 | Val acc: 50.19% | LR: 0.001496
Epoch: 022 | Train loss: 0.9954 | Train acc: 50.59% | Val loss: 1.0498 | Val acc: 52.21% | LR: 0.001488
Epoch: 023 | Train loss: 0.9928 | Train acc: 51.07% | Val loss: 0.9942 | Val acc: 51.48% | LR: 0.001481
Epoch: 024 | Train loss: 0.9916 | Train acc: 50.89% | Val loss: 1.0326 | Val acc: 51.99% | LR: 0.001472
Epoch: 025 | Train loss: 0.9970 | Train acc: 50.40% | Val loss: 0.9988 | Val acc: 51.97% | LR: 0.001464
Epoch: 026 | Train loss: 0.9899 | Train acc: 50.88% | Val loss: 1.0313 | Val acc: 50.40% | LR: 0.001455
Epoch: 027 | Train loss: 0.9889 | Train acc: 50.87% | Val loss: 1.0143 | Val acc: 50.63% | LR: 0.001446
Epoch: 028 | Train loss: 0.9893 | Train acc: 50.77% | Val loss: 1.0263 | Val acc: 48.59% | LR: 0.001437
Epoch: 029 | Train loss: 1.0047 | Train acc: 50.30% | Val loss: 1.0518 | Val acc: 45.76% | LR: 0.001428
Epoch: 030 | Train loss: 0.9919 | Train acc: 50.65% | Val loss: 1.0569 | Val acc: 45.70% | LR: 0.001418
Epoch: 031 | Train loss: 0.9820 | Train acc: 51.03% | Val loss: 1.0347 | Val acc: 45.89% | LR: 0.001408
Epoch: 032 | Train loss: 0.9824 | Train acc: 51.01% | Val loss: 1.0197 | Val acc: 46.64% | LR: 0.001397
Epoch: 033 | Train loss: 0.9809 | Train acc: 51.43% | Val loss: 1.0140 | Val acc: 49.76% | LR: 0.001387
Epoch: 034 | Train loss: 0.9926 | Train acc: 50.45% | Val loss: 0.9923 | Val acc: 50.27% | LR: 0.001376
Epoch: 035 | Train loss: 0.9778 | Train acc: 51.40% | Val loss: 1.0191 | Val acc: 48.35% | LR: 0.001364
Epoch: 036 | Train loss: 0.9877 | Train acc: 50.84% | Val loss: 0.9878 | Val acc: 50.25% | LR: 0.001353
Epoch: 037 | Train loss: 0.9775 | Train acc: 51.54% | Val loss: 1.0038 | Val acc: 49.51% | LR: 0.001341
Epoch: 038 | Train loss: 0.9867 | Train acc: 50.75% | Val loss: 1.0073 | Val acc: 48.93% | LR: 0.001329
Epoch: 039 | Train loss: 0.9778 | Train acc: 51.28% | Val loss: 1.0429 | Val acc: 47.33% | LR: 0.001317
Epoch: 040 | Train loss: 0.9869 | Train acc: 50.78% | Val loss: 1.0533 | Val acc: 48.09% | LR: 0.001305
Epoch: 041 | Train loss: 0.9859 | Train acc: 50.78% | Val loss: 0.9896 | Val acc: 50.76% | LR: 0.001292
Epoch: 042 | Train loss: 0.9817 | Train acc: 51.00% | Val loss: 0.9620 | Val acc: 53.17% | LR: 0.001279
Epoch: 043 | Train loss: 0.9804 | Train acc: 51.01% | Val loss: 0.9786 | Val acc: 51.46% | LR: 0.001266
Epoch: 044 | Train loss: 0.9774 | Train acc: 51.20% | Val loss: 0.9639 | Val acc: 52.63% | LR: 0.001253
Epoch: 045 | Train loss: 0.9857 | Train acc: 50.81% | Val loss: 0.9923 | Val acc: 50.29% | LR: 0.001240
Epoch: 046 | Train loss: 0.9842 | Train acc: 50.90% | Val loss: 1.0038 | Val acc: 49.84% | LR: 0.001226
Epoch: 047 | Train loss: 0.9834 | Train acc: 50.98% | Val loss: 0.9932 | Val acc: 50.57% | LR: 0.001212
Epoch: 048 | Train loss: 0.9845 | Train acc: 50.80% | Val loss: 1.0008 | Val acc: 50.15% | LR: 0.001198
Epoch: 049 | Train loss: 0.9863 | Train acc: 50.74% | Val loss: 1.0060 | Val acc: 49.51% | LR: 0.001184
Epoch: 050 | Train loss: 0.9824 | Train acc: 51.01% | Val loss: 0.9911 | Val acc: 50.38% | LR: 0.001169
Epoch: 051 | Train loss: 0.9841 | Train acc: 50.88% | Val loss: 1.0089 | Val acc: 49.75% | LR: 0.001155
Epoch: 052 | Train loss: 0.9886 | Train acc: 50.67% | Val loss: 1.0194 | Val acc: 50.02% | LR: 0.001140
Epoch: 053 | Train loss: 0.9838 | Train acc: 51.31% | Val loss: 0.9752 | Val acc: 51.78% | LR: 0.001125
Epoch: 054 | Train loss: 0.9893 | Train acc: 50.63% | Val loss: 1.0118 | Val acc: 49.82% | LR: 0.001110
Epoch: 055 | Train loss: 0.9869 | Train acc: 50.83% | Val loss: 1.0210 | Val acc: 48.72% | LR: 0.001095
Epoch: 056 | Train loss: 0.9754 | Train acc: 51.42% | Val loss: 1.0131 | Val acc: 49.15% | LR: 0.001080
Epoch: 057 | Train loss: 0.9913 | Train acc: 50.43% | Val loss: 1.0288 | Val acc: 49.24% | LR: 0.001064
Epoch: 058 | Train loss: 0.9900 | Train acc: 50.70% | Val loss: 1.0121 | Val acc: 49.20% | LR: 0.001049
Epoch: 059 | Train loss: 0.9858 | Train acc: 50.88% | Val loss: 1.0035 | Val acc: 49.52% | LR: 0.001033
Epoch: 060 | Train loss: 0.9755 | Train acc: 51.35% | Val loss: 1.0141 | Val acc: 49.22% | LR: 0.001017
Epoch: 061 | Train loss: 0.9859 | Train acc: 50.70% | Val loss: 0.9911 | Val acc: 50.48% | LR: 0.001002
Epoch: 062 | Train loss: 0.9853 | Train acc: 50.85% | Val loss: 1.0199 | Val acc: 49.13% | LR: 0.000986
Epoch: 063 | Train loss: 0.9813 | Train acc: 51.03% | Val loss: 1.0443 | Val acc: 48.12% | LR: 0.000970
Epoch: 064 | Train loss: 0.9827 | Train acc: 50.98% | Val loss: 1.0089 | Val acc: 49.35% | LR: 0.000954
Epoch: 065 | Train loss: 0.9837 | Train acc: 50.91% | Val loss: 1.0048 | Val acc: 49.61% | LR: 0.000937
Epoch: 066 | Train loss: 0.9704 | Train acc: 51.64% | Val loss: 1.0022 | Val acc: 49.59% | LR: 0.000921
Epoch: 067 | Train loss: 0.9804 | Train acc: 51.16% | Val loss: 1.0025 | Val acc: 49.61% | LR: 0.000905
Epoch: 068 | Train loss: 0.9822 | Train acc: 51.09% | Val loss: 0.9945 | Val acc: 49.60% | LR: 0.000888
Epoch: 069 | Train loss: 0.9878 | Train acc: 50.74% | Val loss: 0.9837 | Val acc: 50.88% | LR: 0.000872
Epoch: 070 | Train loss: 0.9796 | Train acc: 51.10% | Val loss: 0.9833 | Val acc: 50.89% | LR: 0.000856
Epoch: 071 | Train loss: 0.9817 | Train acc: 50.97% | Val loss: 0.9814 | Val acc: 51.04% | LR: 0.000839
Epoch: 072 | Train loss: 0.9817 | Train acc: 50.95% | Val loss: 0.9883 | Val acc: 50.76% | LR: 0.000823
Epoch: 073 | Train loss: 0.9715 | Train acc: 51.57% | Val loss: 0.9940 | Val acc: 50.61% | LR: 0.000806
Epoch: 074 | Train loss: 0.9859 | Train acc: 50.73% | Val loss: 0.9986 | Val acc: 50.27% | LR: 0.000790
Epoch: 075 | Train loss: 0.9828 | Train acc: 50.96% | Val loss: 1.0119 | Val acc: 49.67% | LR: 0.000773
Epoch: 076 | Train loss: 0.9742 | Train acc: 51.39% | Val loss: 1.0145 | Val acc: 49.97% | LR: 0.000757
Epoch: 077 | Train loss: 0.9767 | Train acc: 51.21% | Val loss: 0.9950 | Val acc: 50.66% | LR: 0.000740
Epoch: 078 | Train loss: 0.9832 | Train acc: 50.91% | Val loss: 0.9980 | Val acc: 50.29% | LR: 0.000724
Epoch: 079 | Train loss: 0.9757 | Train acc: 51.32% | Val loss: 1.0037 | Val acc: 49.95% | LR: 0.000707
Epoch: 080 | Train loss: 0.9823 | Train acc: 50.97% | Val loss: 1.0022 | Val acc: 49.86% | LR: 0.000691
Epoch: 081 | Train loss: 0.9691 | Train acc: 51.68% | Val loss: 1.0011 | Val acc: 50.08% | LR: 0.000674
Epoch: 082 | Train loss: 0.9769 | Train acc: 51.22% | Val loss: 1.0026 | Val acc: 50.09% | LR: 0.000658
Epoch: 083 | Train loss: 0.9760 | Train acc: 51.23% | Val loss: 1.0128 | Val acc: 49.67% | LR: 0.000642
Epoch: 084 | Train loss: 0.9872 | Train acc: 50.68% | Val loss: 1.0118 | Val acc: 49.57% | LR: 0.000626
Epoch: 085 | Train loss: 0.9720 | Train acc: 51.46% | Val loss: 1.0123 | Val acc: 49.44% | LR: 0.000609
Epoch: 086 | Train loss: 0.9766 | Train acc: 51.22% | Val loss: 1.0026 | Val acc: 49.93% | LR: 0.000593
Epoch: 087 | Train loss: 0.9762 | Train acc: 51.30% | Val loss: 0.9980 | Val acc: 50.17% | LR: 0.000578
Epoch: 088 | Train loss: 0.9762 | Train acc: 51.24% | Val loss: 0.9944 | Val acc: 50.36% | LR: 0.000562
Epoch: 089 | Train loss: 0.9848 | Train acc: 50.80% | Val loss: 1.0021 | Val acc: 50.12% | LR: 0.000546
Epoch: 090 | Train loss: 0.9817 | Train acc: 50.97% | Val loss: 1.0005 | Val acc: 50.22% | LR: 0.000530
Epoch: 091 | Train loss: 0.9901 | Train acc: 50.56% | Val loss: 0.9948 | Val acc: 50.36% | LR: 0.000515

[I 2025-09-23 16:41:37,394] Trial 26 finished with value: 0.5020541369915008 and parameters: {'lr': 0.0015781289457353026, 'hidden_size': 135, 'dropout': 0.40186784390591823, 'weight_decay': 4.868592277385331e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9989 | Train acc: 50.29% | Val loss: 0.9976 | Val acc: 51.32% | LR: 0.000496
Epoch: 001 | Train loss: 0.9938 | Train acc: 50.94% | Val loss: 0.9933 | Val acc: 52.23% | LR: 0.000496
Epoch: 002 | Train loss: 0.9902 | Train acc: 50.99% | Val loss: 0.9780 | Val acc: 52.94% | LR: 0.000495
Epoch: 003 | Train loss: 0.9818 | Train acc: 51.30% | Val loss: 0.9865 | Val acc: 51.14% | LR: 0.000495
Epoch: 004 | Train loss: 0.9863 | Train acc: 50.87% | Val loss: 0.9929 | Val acc: 50.39% | LR: 0.000495
Epoch: 005 | Train loss: 0.9868 | Train acc: 50.89% | Val loss: 0.9911 | Val acc: 50.50% | LR: 0.000494
Epoch: 006 | Train loss: 0.9809 | Train acc: 51.25% | Val loss: 0.9944 | Val acc: 50.20% | LR: 0.000493
Epoch: 007 | Train loss: 0.9836 | Train acc: 51.06% | Val loss: 1.0027 | Val acc: 49.81% | LR: 0.000493
Epoch: 008 | Train loss: 0.9864 | Train acc: 50.89% | Val loss: 1.0071 | Val acc: 49.30% | LR: 0.000492
Epoch: 009 | Train loss: 0.9783 | Train acc: 51.53% | Val loss: 1.0116 | Val acc: 49.24% | LR: 0.000491
Epoch: 010 | Train loss: 0.9872 | Train acc: 50.75% | Val loss: 1.0240 | Val acc: 48.49% | LR: 0.000489
Epoch: 011 | Train loss: 0.9900 | Train acc: 50.60% | Val loss: 1.0172 | Val acc: 49.74% | LR: 0.000488
Epoch: 012 | Train loss: 0.9892 | Train acc: 50.89% | Val loss: 0.9580 | Val acc: 52.77% | LR: 0.000487
Epoch: 013 | Train loss: 0.9926 | Train acc: 50.60% | Val loss: 0.9596 | Val acc: 53.33% | LR: 0.000485
Epoch: 014 | Train loss: 0.9868 | Train acc: 50.87% | Val loss: 1.0328 | Val acc: 51.62% | LR: 0.000484
Epoch: 015 | Train loss: 0.9879 | Train acc: 50.78% | Val loss: 0.9867 | Val acc: 50.83% | LR: 0.000482
Epoch: 016 | Train loss: 0.9793 | Train acc: 51.24% | Val loss: 1.0027 | Val acc: 50.17% | LR: 0.000480
Epoch: 017 | Train loss: 0.9791 | Train acc: 51.45% | Val loss: 1.0216 | Val acc: 48.89% | LR: 0.000479
Epoch: 018 | Train loss: 0.9812 | Train acc: 51.08% | Val loss: 1.0096 | Val acc: 49.71% | LR: 0.000477
Epoch: 019 | Train loss: 0.9862 | Train acc: 50.73% | Val loss: 1.0218 | Val acc: 49.18% | LR: 0.000475
Epoch: 020 | Train loss: 0.9792 | Train acc: 51.13% | Val loss: 1.0093 | Val acc: 49.69% | LR: 0.000472
Epoch: 021 | Train loss: 0.9843 | Train acc: 51.03% | Val loss: 1.0140 | Val acc: 49.50% | LR: 0.000470
Epoch: 022 | Train loss: 0.9786 | Train acc: 51.34% | Val loss: 1.0312 | Val acc: 48.92% | LR: 0.000468
Epoch: 023 | Train loss: 0.9793 | Train acc: 51.25% | Val loss: 1.0045 | Val acc: 50.22% | LR: 0.000465
Epoch: 024 | Train loss: 0.9947 | Train acc: 50.34% | Val loss: 1.0013 | Val acc: 50.24% | LR: 0.000463
Epoch: 025 | Train loss: 0.9751 | Train acc: 51.44% | Val loss: 1.0025 | Val acc: 50.42% | LR: 0.000460
Epoch: 026 | Train loss: 0.9775 | Train acc: 51.28% | Val loss: 1.0113 | Val acc: 49.61% | LR: 0.000457
Epoch: 027 | Train loss: 0.9821 | Train acc: 51.04% | Val loss: 1.0371 | Val acc: 48.60% | LR: 0.000455
Epoch: 028 | Train loss: 0.9815 | Train acc: 51.04% | Val loss: 1.0344 | Val acc: 48.57% | LR: 0.000452
Epoch: 029 | Train loss: 0.9925 | Train acc: 51.02% | Val loss: 1.0256 | Val acc: 48.76% | LR: 0.000449
Epoch: 030 | Train loss: 0.9785 | Train acc: 51.31% | Val loss: 1.0218 | Val acc: 48.90% | LR: 0.000446
Epoch: 031 | Train loss: 0.9785 | Train acc: 51.20% | Val loss: 1.0306 | Val acc: 48.65% | LR: 0.000442
Epoch: 032 | Train loss: 0.9806 | Train acc: 51.07% | Val loss: 1.0254 | Val acc: 48.76% | LR: 0.000439
Epoch: 033 | Train loss: 0.9783 | Train acc: 51.28% | Val loss: 1.0259 | Val acc: 48.81% | LR: 0.000436
Epoch: 034 | Train loss: 0.9781 | Train acc: 51.17% | Val loss: 1.0137 | Val acc: 49.44% | LR: 0.000432
Epoch: 035 | Train loss: 0.9799 | Train acc: 51.10% | Val loss: 1.0211 | Val acc: 49.28% | LR: 0.000429
Epoch: 036 | Train loss: 0.9831 | Train acc: 51.03% | Val loss: 1.0136 | Val acc: 49.58% | LR: 0.000425
Epoch: 037 | Train loss: 0.9803 | Train acc: 51.12% | Val loss: 1.0167 | Val acc: 49.13% | LR: 0.000422
Epoch: 038 | Train loss: 0.9829 | Train acc: 50.97% | Val loss: 1.0253 | Val acc: 48.90% | LR: 0.000418
Epoch: 039 | Train loss: 0.9760 | Train acc: 51.45% | Val loss: 1.0147 | Val acc: 49.46% | LR: 0.000414
Epoch: 040 | Train loss: 0.9877 | Train acc: 50.67% | Val loss: 1.0143 | Val acc: 49.19% | LR: 0.000410
Epoch: 041 | Train loss: 0.9911 | Train acc: 50.54% | Val loss: 1.0124 | Val acc: 49.39% | LR: 0.000406
Epoch: 042 | Train loss: 0.9801 | Train acc: 51.10% | Val loss: 1.0112 | Val acc: 49.48% | LR: 0.000402
Epoch: 043 | Train loss: 0.9852 | Train acc: 50.86% | Val loss: 1.0190 | Val acc: 49.35% | LR: 0.000398
Epoch: 044 | Train loss: 0.9845 | Train acc: 50.84% | Val loss: 1.0290 | Val acc: 48.38% | LR: 0.000394
Epoch: 045 | Train loss: 0.9865 | Train acc: 50.73% | Val loss: 1.0396 | Val acc: 48.26% | LR: 0.000390
Epoch: 046 | Train loss: 0.9791 | Train acc: 51.05% | Val loss: 1.0200 | Val acc: 48.78% | LR: 0.000385
Epoch: 047 | Train loss: 0.9766 | Train acc: 51.35% | Val loss: 1.0027 | Val acc: 50.09% | LR: 0.000381
Epoch: 048 | Train loss: 0.9798 | Train acc: 51.08% | Val loss: 1.0144 | Val acc: 50.25% | LR: 0.000377
Epoch: 049 | Train loss: 0.9787 | Train acc: 51.21% | Val loss: 0.9912 | Val acc: 50.45% | LR: 0.000372
Epoch: 050 | Train loss: 0.9774 | Train acc: 51.25% | Val loss: 1.0008 | Val acc: 50.02% | LR: 0.000368
Epoch: 051 | Train loss: 0.9878 | Train acc: 50.65% | Val loss: 0.9995 | Val acc: 50.20% | LR: 0.000363
Epoch: 052 | Train loss: 0.9790 | Train acc: 51.15% | Val loss: 0.9920 | Val acc: 50.38% | LR: 0.000359
Epoch: 053 | Train loss: 0.9929 | Train acc: 50.41% | Val loss: 0.9872 | Val acc: 50.70% | LR: 0.000354
Epoch: 054 | Train loss: 0.9833 | Train acc: 50.88% | Val loss: 0.9956 | Val acc: 50.39% | LR: 0.000349
Epoch: 055 | Train loss: 0.9795 | Train acc: 51.28% | Val loss: 1.0029 | Val acc: 50.11% | LR: 0.000344
Epoch: 056 | Train loss: 0.9836 | Train acc: 50.85% | Val loss: 1.0026 | Val acc: 49.99% | LR: 0.000340
Epoch: 057 | Train loss: 0.9744 | Train acc: 51.40% | Val loss: 1.0019 | Val acc: 50.03% | LR: 0.000335
Epoch: 058 | Train loss: 0.9784 | Train acc: 51.13% | Val loss: 1.0059 | Val acc: 49.94% | LR: 0.000330
Epoch: 059 | Train loss: 0.9784 | Train acc: 51.14% | Val loss: 1.0063 | Val acc: 49.71% | LR: 0.000325
Epoch: 060 | Train loss: 0.9718 | Train acc: 51.52% | Val loss: 1.0075 | Val acc: 49.87% | LR: 0.000320
Epoch: 061 | Train loss: 0.9880 | Train acc: 50.61% | Val loss: 1.0099 | Val acc: 49.80% | LR: 0.000315
Epoch: 062 | Train loss: 0.9634 | Train acc: 52.05% | Val loss: 1.0082 | Val acc: 49.99% | LR: 0.000310

[I 2025-09-23 16:42:32,316] Trial 27 finished with value: 0.49983842968940734 and parameters: {'lr': 0.0004959841284147069, 'hidden_size': 109, 'dropout': 0.4604947069885895, 'weight_decay': 2.495802969520505e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0016 | Train acc: 49.89% | Val loss: 1.0304 | Val acc: 52.73% | LR: 0.000032
Epoch: 001 | Train loss: 1.0011 | Train acc: 49.47% | Val loss: 0.9964 | Val acc: 52.90% | LR: 0.000032
Epoch: 002 | Train loss: 0.9994 | Train acc: 49.75% | Val loss: 1.0495 | Val acc: 53.30% | LR: 0.000032
Epoch: 003 | Train loss: 0.9997 | Train acc: 50.00% | Val loss: 1.0050 | Val acc: 53.50% | LR: 0.000032
Epoch: 004 | Train loss: 1.0004 | Train acc: 49.98% | Val loss: 0.9988 | Val acc: 53.47% | LR: 0.000032
Epoch: 005 | Train loss: 1.0164 | Train acc: 50.58% | Val loss: 1.0055 | Val acc: 53.69% | LR: 0.000032
Epoch: 006 | Train loss: 1.1689 | Train acc: 49.70% | Val loss: 0.9990 | Val acc: 53.78% | LR: 0.000032
Epoch: 007 | Train loss: 1.0007 | Train acc: 50.06% | Val loss: 0.9993 | Val acc: 53.92% | LR: 0.000032
Epoch: 008 | Train loss: 0.9990 | Train acc: 50.32% | Val loss: 0.9991 | Val acc: 53.44% | LR: 0.000032
Epoch: 009 | Train loss: 0.9979 | Train acc: 50.71% | Val loss: 0.9996 | Val acc: 53.70% | LR: 0.000032
Epoch: 010 | Train loss: 0.9994 | Train acc: 50.33% | Val loss: 1.0232 | Val acc: 53.16% | LR: 0.000032
Epoch: 011 | Train loss: 1.0220 | Train acc: 50.63% | Val loss: 1.0054 | Val acc: 54.04% | LR: 0.000032
Epoch: 012 | Train loss: 0.9973 | Train acc: 50.50% | Val loss: 1.0001 | Val acc: 54.00% | LR: 0.000032
Epoch: 013 | Train loss: 1.0006 | Train acc: 50.42% | Val loss: 1.0114 | Val acc: 53.66% | LR: 0.000032
Epoch: 014 | Train loss: 1.0010 | Train acc: 49.95% | Val loss: 1.0006 | Val acc: 53.30% | LR: 0.000031
Epoch: 015 | Train loss: 0.9959 | Train acc: 50.71% | Val loss: 1.0012 | Val acc: 53.26% | LR: 0.000031
Epoch: 016 | Train loss: 0.9951 | Train acc: 50.88% | Val loss: 0.9991 | Val acc: 53.21% | LR: 0.000031
Epoch: 017 | Train loss: 0.9990 | Train acc: 50.21% | Val loss: 0.9989 | Val acc: 52.36% | LR: 0.000031
Epoch: 018 | Train loss: 0.9948 | Train acc: 50.97% | Val loss: 0.9999 | Val acc: 51.87% | LR: 0.000031
Epoch: 019 | Train loss: 0.9957 | Train acc: 50.61% | Val loss: 0.9998 | Val acc: 51.05% | LR: 0.000031
Epoch: 020 | Train loss: 0.9973 | Train acc: 50.43% | Val loss: 0.9974 | Val acc: 52.25% | LR: 0.000031
Epoch: 021 | Train loss: 0.9944 | Train acc: 50.76% | Val loss: 1.0047 | Val acc: 52.23% | LR: 0.000031
Epoch: 022 | Train loss: 0.9962 | Train acc: 50.59% | Val loss: 0.9982 | Val acc: 52.95% | LR: 0.000030
Epoch: 023 | Train loss: 0.9922 | Train acc: 50.81% | Val loss: 0.9975 | Val acc: 53.75% | LR: 0.000030
Epoch: 024 | Train loss: 0.9928 | Train acc: 50.63% | Val loss: 0.9990 | Val acc: 52.88% | LR: 0.000030
Epoch: 025 | Train loss: 0.9920 | Train acc: 50.70% | Val loss: 0.9983 | Val acc: 53.49% | LR: 0.000030
Epoch: 026 | Train loss: 0.9839 | Train acc: 50.96% | Val loss: 0.9984 | Val acc: 53.66% | LR: 0.000030
Epoch: 027 | Train loss: 0.9914 | Train acc: 50.73% | Val loss: 0.9979 | Val acc: 53.28% | LR: 0.000030
Epoch: 028 | Train loss: 0.9955 | Train acc: 50.80% | Val loss: 0.9972 | Val acc: 53.11% | LR: 0.000029
Epoch: 029 | Train loss: 0.9839 | Train acc: 51.42% | Val loss: 1.0757 | Val acc: 52.42% | LR: 0.000029
Epoch: 030 | Train loss: 0.9849 | Train acc: 51.17% | Val loss: 0.9967 | Val acc: 52.70% | LR: 0.000029
Epoch: 031 | Train loss: 0.9987 | Train acc: 50.41% | Val loss: 1.0081 | Val acc: 53.22% | LR: 0.000029
Epoch: 032 | Train loss: 0.9927 | Train acc: 50.94% | Val loss: 0.9977 | Val acc: 53.18% | LR: 0.000029
Epoch: 033 | Train loss: 0.9902 | Train acc: 50.56% | Val loss: 1.0070 | Val acc: 53.32% | LR: 0.000028
Epoch: 034 | Train loss: 0.9948 | Train acc: 50.48% | Val loss: 0.9970 | Val acc: 53.34% | LR: 0.000028
Epoch: 035 | Train loss: 0.9856 | Train acc: 51.41% | Val loss: 1.0026 | Val acc: 53.31% | LR: 0.000028
Epoch: 036 | Train loss: 0.9818 | Train acc: 51.16% | Val loss: 0.9973 | Val acc: 53.37% | LR: 0.000028
Epoch: 037 | Train loss: 0.9933 | Train acc: 50.67% | Val loss: 1.0200 | Val acc: 53.67% | LR: 0.000028
Epoch: 038 | Train loss: 1.0005 | Train acc: 50.55% | Val loss: 1.0201 | Val acc: 53.83% | LR: 0.000027
Epoch: 039 | Train loss: 0.9973 | Train acc: 50.59% | Val loss: 0.9982 | Val acc: 54.15% | LR: 0.000027
Epoch: 040 | Train loss: 0.9871 | Train acc: 51.00% | Val loss: 0.9967 | Val acc: 54.44% | LR: 0.000027
Epoch: 041 | Train loss: 0.9921 | Train acc: 50.52% | Val loss: 0.9995 | Val acc: 54.09% | LR: 0.000027
Epoch: 042 | Train loss: 0.9963 | Train acc: 50.41% | Val loss: 0.9958 | Val acc: 54.31% | LR: 0.000026
Epoch: 043 | Train loss: 0.9899 | Train acc: 50.78% | Val loss: 0.9957 | Val acc: 54.31% | LR: 0.000026
Epoch: 044 | Train loss: 0.9927 | Train acc: 50.67% | Val loss: 0.9969 | Val acc: 54.31% | LR: 0.000026
Epoch: 045 | Train loss: 0.9909 | Train acc: 50.91% | Val loss: 0.9958 | Val acc: 54.35% | LR: 0.000026
Epoch: 046 | Train loss: 0.9873 | Train acc: 50.85% | Val loss: 0.9958 | Val acc: 54.13% | LR: 0.000025
Epoch: 047 | Train loss: 0.9885 | Train acc: 51.04% | Val loss: 0.9958 | Val acc: 54.02% | LR: 0.000025
Epoch: 048 | Train loss: 0.9908 | Train acc: 50.77% | Val loss: 0.9957 | Val acc: 53.93% | LR: 0.000025
Epoch: 049 | Train loss: 0.9865 | Train acc: 51.06% | Val loss: 0.9955 | Val acc: 53.87% | LR: 0.000024
Epoch: 050 | Train loss: 0.9916 | Train acc: 50.82% | Val loss: 0.9954 | Val acc: 53.95% | LR: 0.000024
Epoch: 051 | Train loss: 0.9906 | Train acc: 51.07% | Val loss: 0.9954 | Val acc: 53.89% | LR: 0.000024
Epoch: 052 | Train loss: 1.0000 | Train acc: 50.37% | Val loss: 0.9952 | Val acc: 53.91% | LR: 0.000024
Epoch: 053 | Train loss: 0.9885 | Train acc: 51.00% | Val loss: 0.9951 | Val acc: 53.83% | LR: 0.000023
Epoch: 054 | Train loss: 0.9810 | Train acc: 51.44% | Val loss: 0.9950 | Val acc: 53.87% | LR: 0.000023
Epoch: 055 | Train loss: 0.9874 | Train acc: 50.99% | Val loss: 0.9948 | Val acc: 53.89% | LR: 0.000023
Epoch: 056 | Train loss: 0.9870 | Train acc: 51.00% | Val loss: 0.9947 | Val acc: 53.83% | LR: 0.000022
Epoch: 057 | Train loss: 0.9928 | Train acc: 50.65% | Val loss: 0.9945 | Val acc: 53.81% | LR: 0.000022
Epoch: 058 | Train loss: 0.9935 | Train acc: 50.64% | Val loss: 0.9944 | Val acc: 53.73% | LR: 0.000022
Epoch: 059 | Train loss: 0.9910 | Train acc: 50.81% | Val loss: 0.9944 | Val acc: 53.65% | LR: 0.000021
Epoch: 060 | Train loss: 0.9889 | Train acc: 50.71% | Val loss: 0.9943 | Val acc: 53.69% | LR: 0.000021
Epoch: 061 | Train loss: 0.9873 | Train acc: 50.83% | Val loss: 0.9943 | Val acc: 53.65% | LR: 0.000021
Epoch: 062 | Train loss: 0.9910 | Train acc: 50.86% | Val loss: 0.9941 | Val acc: 53.67% | LR: 0.000020
Epoch: 063 | Train loss: 0.9843 | Train acc: 51.30% | Val loss: 0.9941 | Val acc: 53.69% | LR: 0.000020
Epoch: 064 | Train loss: 0.9865 | Train acc: 51.03% | Val loss: 0.9939 | Val acc: 53.67% | LR: 0.000020
Epoch: 065 | Train loss: 0.9897 | Train acc: 50.84% | Val loss: 0.9938 | Val acc: 53.69% | LR: 0.000020
Epoch: 066 | Train loss: 0.9814 | Train acc: 51.28% | Val loss: 0.9937 | Val acc: 53.49% | LR: 0.000019
Epoch: 067 | Train loss: 0.9849 | Train acc: 51.11% | Val loss: 0.9935 | Val acc: 53.59% | LR: 0.000019
Epoch: 068 | Train loss: 0.9825 | Train acc: 51.38% | Val loss: 0.9934 | Val acc: 53.59% | LR: 0.000019
Epoch: 069 | Train loss: 0.9868 | Train acc: 50.93% | Val loss: 0.9933 | Val acc: 53.54% | LR: 0.000018
Epoch: 070 | Train loss: 1.0003 | Train acc: 50.30% | Val loss: 0.9932 | Val acc: 53.59% | LR: 0.000018
Epoch: 071 | Train loss: 0.9891 | Train acc: 50.74% | Val loss: 0.9930 | Val acc: 53.59% | LR: 0.000018
Epoch: 072 | Train loss: 0.9819 | Train acc: 51.54% | Val loss: 0.9929 | Val acc: 53.57% | LR: 0.000017
Epoch: 073 | Train loss: 0.9899 | Train acc: 50.75% | Val loss: 0.9928 | Val acc: 53.54% | LR: 0.000017
Epoch: 074 | Train loss: 0.9897 | Train acc: 50.93% | Val loss: 0.9927 | Val acc: 53.50% | LR: 0.000017
Epoch: 075 | Train loss: 0.9870 | Train acc: 51.28% | Val loss: 0.9926 | Val acc: 53.50% | LR: 0.000016
Epoch: 076 | Train loss: 0.9913 | Train acc: 50.94% | Val loss: 0.9924 | Val acc: 53.42% | LR: 0.000016
Epoch: 077 | Train loss: 0.9836 | Train acc: 51.38% | Val loss: 0.9923 | Val acc: 53.36% | LR: 0.000016
Epoch: 078 | Train loss: 0.9865 | Train acc: 51.11% | Val loss: 0.9921 | Val acc: 53.36% | LR: 0.000015
Epoch: 079 | Train loss: 0.9866 | Train acc: 51.19% | Val loss: 0.9920 | Val acc: 53.36% | LR: 0.000015
Epoch: 080 | Train loss: 0.9855 | Train acc: 51.10% | Val loss: 0.9918 | Val acc: 53.44% | LR: 0.000015
Epoch: 081 | Train loss: 0.9960 | Train acc: 50.30% | Val loss: 0.9917 | Val acc: 53.39% | LR: 0.000014
Epoch: 082 | Train loss: 0.9950 | Train acc: 50.57% | Val loss: 0.9916 | Val acc: 53.44% | LR: 0.000014
Epoch: 083 | Train loss: 0.9886 | Train acc: 51.01% | Val loss: 0.9916 | Val acc: 53.36% | LR: 0.000014
Epoch: 084 | Train loss: 0.9915 | Train acc: 50.75% | Val loss: 0.9915 | Val acc: 53.48% | LR: 0.000013
Epoch: 085 | Train loss: 0.9898 | Train acc: 50.76% | Val loss: 0.9914 | Val acc: 53.52% | LR: 0.000013
Epoch: 086 | Train loss: 0.9903 | Train acc: 50.76% | Val loss: 0.9913 | Val acc: 53.56% | LR: 0.000013
Epoch: 087 | Train loss: 0.9909 | Train acc: 50.75% | Val loss: 0.9912 | Val acc: 53.56% | LR: 0.000012
Epoch: 088 | Train loss: 0.9817 | Train acc: 51.54% | Val loss: 0.9912 | Val acc: 53.54% | LR: 0.000012
Epoch: 089 | Train loss: 0.9894 | Train acc: 51.01% | Val loss: 0.9910 | Val acc: 53.58% | LR: 0.000012

[I 2025-09-23 16:44:02,276] Trial 28 finished with value: 0.5356474876403808 and parameters: {'lr': 3.2216451047867666e-05, 'hidden_size': 256, 'dropout': 0.3548390264248149, 'weight_decay': 1.4846024510552035e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0008 | Train acc: 50.00% | Val loss: 1.0059 | Val acc: 46.81% | LR: 0.000017
Epoch: 001 | Train loss: 1.0058 | Train acc: 49.98% | Val loss: 1.0095 | Val acc: 47.02% | LR: 0.000017
Epoch: 002 | Train loss: 0.9983 | Train acc: 50.43% | Val loss: 1.0050 | Val acc: 47.00% | LR: 0.000017
Epoch: 003 | Train loss: 0.9984 | Train acc: 50.61% | Val loss: 1.0030 | Val acc: 46.94% | LR: 0.000017
Epoch: 004 | Train loss: 0.9993 | Train acc: 50.19% | Val loss: 1.0117 | Val acc: 46.88% | LR: 0.000017
Epoch: 005 | Train loss: 1.0003 | Train acc: 50.18% | Val loss: 1.0150 | Val acc: 46.43% | LR: 0.000017
Epoch: 006 | Train loss: 1.0001 | Train acc: 50.44% | Val loss: 1.0435 | Val acc: 46.70% | LR: 0.000017
Epoch: 007 | Train loss: 1.0060 | Train acc: 50.04% | Val loss: 1.0038 | Val acc: 46.47% | LR: 0.000017
Epoch: 008 | Train loss: 0.9979 | Train acc: 50.30% | Val loss: 1.0042 | Val acc: 46.26% | LR: 0.000017
Epoch: 009 | Train loss: 0.9995 | Train acc: 50.09% | Val loss: 1.0031 | Val acc: 46.23% | LR: 0.000017
Epoch: 010 | Train loss: 0.9983 | Train acc: 50.11% | Val loss: 1.0069 | Val acc: 45.82% | LR: 0.000017
Epoch: 011 | Train loss: 0.9991 | Train acc: 50.19% | Val loss: 1.0033 | Val acc: 46.03% | LR: 0.000017
Epoch: 012 | Train loss: 0.9993 | Train acc: 50.09% | Val loss: 1.0072 | Val acc: 45.50% | LR: 0.000017
Epoch: 013 | Train loss: 0.9991 | Train acc: 50.20% | Val loss: 1.0033 | Val acc: 45.73% | LR: 0.000017
Epoch: 014 | Train loss: 0.9986 | Train acc: 50.14% | Val loss: 1.0044 | Val acc: 45.64% | LR: 0.000017
Epoch: 015 | Train loss: 0.9991 | Train acc: 50.17% | Val loss: 1.0039 | Val acc: 45.81% | LR: 0.000017
Epoch: 016 | Train loss: 0.9988 | Train acc: 50.37% | Val loss: 1.0035 | Val acc: 45.88% | LR: 0.000017
Epoch: 017 | Train loss: 0.9978 | Train acc: 50.39% | Val loss: 1.0052 | Val acc: 45.87% | LR: 0.000017
Epoch: 018 | Train loss: 0.9982 | Train acc: 50.12% | Val loss: 1.0040 | Val acc: 45.85% | LR: 0.000017
Epoch: 019 | Train loss: 0.9967 | Train acc: 50.48% | Val loss: 1.0142 | Val acc: 45.82% | LR: 0.000017
Epoch: 020 | Train loss: 0.9982 | Train acc: 50.30% | Val loss: 1.0038 | Val acc: 45.90% | LR: 0.000017
Epoch: 021 | Train loss: 0.9966 | Train acc: 50.73% | Val loss: 1.0059 | Val acc: 45.78% | LR: 0.000017
Epoch: 022 | Train loss: 0.9996 | Train acc: 50.62% | Val loss: 1.0038 | Val acc: 45.87% | LR: 0.000017
Epoch: 023 | Train loss: 0.9951 | Train acc: 51.05% | Val loss: 1.0024 | Val acc: 45.95% | LR: 0.000016
Epoch: 024 | Train loss: 0.9974 | Train acc: 50.51% | Val loss: 1.0040 | Val acc: 45.90% | LR: 0.000016
Epoch: 025 | Train loss: 0.9957 | Train acc: 50.94% | Val loss: 1.0047 | Val acc: 45.83% | LR: 0.000016
Epoch: 026 | Train loss: 0.9965 | Train acc: 51.05% | Val loss: 1.0052 | Val acc: 45.83% | LR: 0.000016
Epoch: 027 | Train loss: 0.9951 | Train acc: 51.13% | Val loss: 1.0049 | Val acc: 45.86% | LR: 0.000016
Epoch: 028 | Train loss: 0.9986 | Train acc: 50.42% | Val loss: 1.0296 | Val acc: 45.86% | LR: 0.000016
Epoch: 029 | Train loss: 0.9971 | Train acc: 50.69% | Val loss: 1.0115 | Val acc: 46.11% | LR: 0.000016
Epoch: 030 | Train loss: 1.0003 | Train acc: 49.84% | Val loss: 1.0068 | Val acc: 45.90% | LR: 0.000016
Epoch: 031 | Train loss: 0.9948 | Train acc: 51.24% | Val loss: 1.0046 | Val acc: 46.02% | LR: 0.000016
Epoch: 032 | Train loss: 0.9984 | Train acc: 50.54% | Val loss: 1.2977 | Val acc: 45.85% | LR: 0.000016
Epoch: 033 | Train loss: 0.9968 | Train acc: 50.43% | Val loss: 1.0049 | Val acc: 45.96% | LR: 0.000015
Epoch: 034 | Train loss: 1.0018 | Train acc: 49.81% | Val loss: 1.0058 | Val acc: 45.89% | LR: 0.000015
Epoch: 035 | Train loss: 0.9940 | Train acc: 51.04% | Val loss: 1.0055 | Val acc: 45.91% | LR: 0.000015
Epoch: 036 | Train loss: 0.9959 | Train acc: 50.76% | Val loss: 1.0177 | Val acc: 45.91% | LR: 0.000015
Epoch: 037 | Train loss: 0.9968 | Train acc: 50.49% | Val loss: 1.0048 | Val acc: 45.95% | LR: 0.000015
Epoch: 038 | Train loss: 0.9943 | Train acc: 50.81% | Val loss: 1.0046 | Val acc: 45.99% | LR: 0.000015
Epoch: 039 | Train loss: 0.9947 | Train acc: 50.90% | Val loss: 1.0050 | Val acc: 45.84% | LR: 0.000015
Epoch: 040 | Train loss: 0.9956 | Train acc: 50.57% | Val loss: 1.0082 | Val acc: 45.75% | LR: 0.000015
Epoch: 041 | Train loss: 0.9943 | Train acc: 50.99% | Val loss: 1.0117 | Val acc: 46.12% | LR: 0.000014
Epoch: 042 | Train loss: 0.9999 | Train acc: 50.09% | Val loss: 1.0060 | Val acc: 45.97% | LR: 0.000014
Epoch: 043 | Train loss: 0.9969 | Train acc: 50.66% | Val loss: 1.0105 | Val acc: 45.84% | LR: 0.000014
Epoch: 044 | Train loss: 0.9983 | Train acc: 50.59% | Val loss: 1.0659 | Val acc: 46.10% | LR: 0.000014
Epoch: 045 | Train loss: 1.0039 | Train acc: 50.08% | Val loss: 1.0084 | Val acc: 45.87% | LR: 0.000014
Epoch: 046 | Train loss: 0.9965 | Train acc: 50.41% | Val loss: 1.0059 | Val acc: 45.93% | LR: 0.000014
Epoch: 047 | Train loss: 0.9929 | Train acc: 50.85% | Val loss: 1.0054 | Val acc: 45.91% | LR: 0.000014
Epoch: 048 | Train loss: 0.9966 | Train acc: 50.57% | Val loss: 1.0050 | Val acc: 45.93% | LR: 0.000013
Epoch: 049 | Train loss: 0.9998 | Train acc: 50.32% | Val loss: 1.0061 | Val acc: 45.89% | LR: 0.000013
Epoch: 050 | Train loss: 0.9966 | Train acc: 50.07% | Val loss: 1.0067 | Val acc: 45.85% | LR: 0.000013

[I 2025-09-23 16:44:46,203] Trial 29 finished with value: 0.4582307696342468 and parameters: {'lr': 1.7454310246174362e-05, 'hidden_size': 89, 'dropout': 0.30312615217742245, 'weight_decay': 0.008550595109386711}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9995 | Train acc: 49.68% | Val loss: 0.9994 | Val acc: 52.90% | LR: 0.000062
Epoch: 001 | Train loss: 0.9984 | Train acc: 50.80% | Val loss: 0.9987 | Val acc: 53.59% | LR: 0.000062
Epoch: 002 | Train loss: 0.9968 | Train acc: 50.78% | Val loss: 0.9987 | Val acc: 54.04% | LR: 0.000062
Epoch: 003 | Train loss: 0.9957 | Train acc: 50.96% | Val loss: 0.9990 | Val acc: 51.83% | LR: 0.000062
Epoch: 004 | Train loss: 1.0011 | Train acc: 50.35% | Val loss: 0.9991 | Val acc: 50.58% | LR: 0.000062
Epoch: 005 | Train loss: 0.9912 | Train acc: 51.24% | Val loss: 0.9984 | Val acc: 51.18% | LR: 0.000062
Epoch: 006 | Train loss: 1.0005 | Train acc: 50.32% | Val loss: 0.9976 | Val acc: 51.30% | LR: 0.000062
Epoch: 007 | Train loss: 0.9955 | Train acc: 50.73% | Val loss: 0.9974 | Val acc: 50.98% | LR: 0.000062
Epoch: 008 | Train loss: 0.9890 | Train acc: 51.36% | Val loss: 0.9959 | Val acc: 51.62% | LR: 0.000062
Epoch: 009 | Train loss: 0.9926 | Train acc: 50.77% | Val loss: 0.9940 | Val acc: 51.60% | LR: 0.000062
Epoch: 010 | Train loss: 0.9929 | Train acc: 50.76% | Val loss: 0.9924 | Val acc: 51.67% | LR: 0.000061
Epoch: 011 | Train loss: 0.9910 | Train acc: 50.94% | Val loss: 0.9911 | Val acc: 51.65% | LR: 0.000061
Epoch: 012 | Train loss: 0.9856 | Train acc: 51.28% | Val loss: 0.9890 | Val acc: 51.64% | LR: 0.000061
Epoch: 013 | Train loss: 0.9874 | Train acc: 51.19% | Val loss: 0.9874 | Val acc: 51.61% | LR: 0.000061
Epoch: 014 | Train loss: 0.9869 | Train acc: 50.88% | Val loss: 0.9801 | Val acc: 52.12% | LR: 0.000061
Epoch: 015 | Train loss: 0.9846 | Train acc: 51.07% | Val loss: 0.9762 | Val acc: 52.18% | LR: 0.000061
Epoch: 016 | Train loss: 0.9801 | Train acc: 51.34% | Val loss: 0.9784 | Val acc: 51.73% | LR: 0.000060
Epoch: 017 | Train loss: 0.9791 | Train acc: 51.30% | Val loss: 0.9805 | Val acc: 51.39% | LR: 0.000060
Epoch: 018 | Train loss: 0.9846 | Train acc: 51.05% | Val loss: 0.9824 | Val acc: 51.12% | LR: 0.000060
Epoch: 019 | Train loss: 0.9751 | Train acc: 51.56% | Val loss: 0.9828 | Val acc: 51.18% | LR: 0.000060
Epoch: 020 | Train loss: 0.9932 | Train acc: 50.46% | Val loss: 0.9837 | Val acc: 51.10% | LR: 0.000059
Epoch: 021 | Train loss: 0.9852 | Train acc: 50.82% | Val loss: 0.9834 | Val acc: 51.09% | LR: 0.000059
Epoch: 022 | Train loss: 0.9813 | Train acc: 50.99% | Val loss: 0.9840 | Val acc: 51.13% | LR: 0.000059
Epoch: 023 | Train loss: 0.9841 | Train acc: 50.84% | Val loss: 0.9861 | Val acc: 51.05% | LR: 0.000058
Epoch: 024 | Train loss: 0.9888 | Train acc: 50.67% | Val loss: 0.9885 | Val acc: 50.87% | LR: 0.000058
Epoch: 025 | Train loss: 0.9757 | Train acc: 51.34% | Val loss: 0.9892 | Val acc: 50.71% | LR: 0.000058
Epoch: 026 | Train loss: 0.9820 | Train acc: 51.01% | Val loss: 0.9897 | Val acc: 50.75% | LR: 0.000058
Epoch: 027 | Train loss: 0.9815 | Train acc: 50.99% | Val loss: 0.9922 | Val acc: 50.53% | LR: 0.000057
Epoch: 028 | Train loss: 0.9839 | Train acc: 50.78% | Val loss: 0.9896 | Val acc: 50.79% | LR: 0.000057
Epoch: 029 | Train loss: 0.9773 | Train acc: 51.30% | Val loss: 0.9904 | Val acc: 50.57% | LR: 0.000056
Epoch: 030 | Train loss: 0.9706 | Train acc: 51.59% | Val loss: 0.9913 | Val acc: 50.61% | LR: 0.000056
Epoch: 031 | Train loss: 0.9871 | Train acc: 50.80% | Val loss: 0.9914 | Val acc: 50.55% | LR: 0.000056
Epoch: 032 | Train loss: 0.9785 | Train acc: 51.26% | Val loss: 0.9914 | Val acc: 50.59% | LR: 0.000055
Epoch: 033 | Train loss: 0.9777 | Train acc: 51.27% | Val loss: 0.9925 | Val acc: 50.46% | LR: 0.000055
Epoch: 034 | Train loss: 0.9836 | Train acc: 50.83% | Val loss: 0.9933 | Val acc: 50.59% | LR: 0.000054
Epoch: 035 | Train loss: 0.9827 | Train acc: 50.93% | Val loss: 0.9949 | Val acc: 50.43% | LR: 0.000054
Epoch: 036 | Train loss: 0.9843 | Train acc: 50.93% | Val loss: 0.9949 | Val acc: 50.41% | LR: 0.000054
Epoch: 037 | Train loss: 0.9763 | Train acc: 51.39% | Val loss: 0.9982 | Val acc: 49.97% | LR: 0.000053
Epoch: 038 | Train loss: 0.9836 | Train acc: 50.99% | Val loss: 0.9995 | Val acc: 49.93% | LR: 0.000053
Epoch: 039 | Train loss: 0.9695 | Train acc: 51.78% | Val loss: 0.9986 | Val acc: 49.95% | LR: 0.000052
Epoch: 040 | Train loss: 0.9822 | Train acc: 51.06% | Val loss: 1.0003 | Val acc: 49.81% | LR: 0.000052
Epoch: 041 | Train loss: 0.9856 | Train acc: 50.78% | Val loss: 1.0005 | Val acc: 49.81% | LR: 0.000051
Epoch: 042 | Train loss: 0.9888 | Train acc: 50.60% | Val loss: 1.0007 | Val acc: 49.85% | LR: 0.000051
Epoch: 043 | Train loss: 0.9872 | Train acc: 50.68% | Val loss: 1.0026 | Val acc: 49.81% | LR: 0.000050
Epoch: 044 | Train loss: 0.9765 | Train acc: 51.29% | Val loss: 1.0035 | Val acc: 49.75% | LR: 0.000050
Epoch: 045 | Train loss: 0.9781 | Train acc: 51.20% | Val loss: 1.0045 | Val acc: 49.67% | LR: 0.000049
Epoch: 046 | Train loss: 0.9900 | Train acc: 50.62% | Val loss: 1.0058 | Val acc: 49.73% | LR: 0.000049
Epoch: 047 | Train loss: 0.9663 | Train acc: 51.90% | Val loss: 1.0079 | Val acc: 49.52% | LR: 0.000048
Epoch: 048 | Train loss: 0.9854 | Train acc: 50.81% | Val loss: 1.0095 | Val acc: 49.21% | LR: 0.000048
Epoch: 049 | Train loss: 0.9783 | Train acc: 51.17% | Val loss: 1.0101 | Val acc: 49.14% | LR: 0.000047
Epoch: 050 | Train loss: 0.9856 | Train acc: 50.83% | Val loss: 1.0127 | Val acc: 48.90% | LR: 0.000046
Epoch: 051 | Train loss: 0.9872 | Train acc: 50.76% | Val loss: 1.0151 | Val acc: 48.90% | LR: 0.000046

[I 2025-09-23 16:45:39,802] Trial 30 finished with value: 0.4888434112071991 and parameters: {'lr': 6.22709010930188e-05, 'hidden_size': 112, 'dropout': 0.23464736149522847, 'weight_decay': 5.053998343264271e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0030 | Train acc: 49.16% | Val loss: 1.0085 | Val acc: 46.24% | LR: 0.000029
Epoch: 001 | Train loss: 1.0018 | Train acc: 49.54% | Val loss: 1.0546 | Val acc: 46.44% | LR: 0.000029
Epoch: 002 | Train loss: 1.0000 | Train acc: 49.78% | Val loss: 1.0153 | Val acc: 46.24% | LR: 0.000029
Epoch: 003 | Train loss: 0.9988 | Train acc: 50.07% | Val loss: 1.0027 | Val acc: 46.46% | LR: 0.000029
Epoch: 004 | Train loss: 0.9986 | Train acc: 50.57% | Val loss: 1.0071 | Val acc: 45.90% | LR: 0.000029
Epoch: 005 | Train loss: 0.9984 | Train acc: 50.18% | Val loss: 1.0038 | Val acc: 46.07% | LR: 0.000029
Epoch: 006 | Train loss: 0.9985 | Train acc: 49.99% | Val loss: 1.0055 | Val acc: 46.03% | LR: 0.000029
Epoch: 007 | Train loss: 0.9966 | Train acc: 50.94% | Val loss: 1.0041 | Val acc: 46.05% | LR: 0.000029
Epoch: 008 | Train loss: 0.9959 | Train acc: 50.69% | Val loss: 1.0037 | Val acc: 46.01% | LR: 0.000029
Epoch: 009 | Train loss: 0.9962 | Train acc: 50.43% | Val loss: 1.0040 | Val acc: 46.05% | LR: 0.000029
Epoch: 010 | Train loss: 0.9980 | Train acc: 50.07% | Val loss: 1.0042 | Val acc: 46.05% | LR: 0.000029
Epoch: 011 | Train loss: 0.9950 | Train acc: 50.49% | Val loss: 1.0042 | Val acc: 45.98% | LR: 0.000029
Epoch: 012 | Train loss: 0.9975 | Train acc: 50.08% | Val loss: 1.0051 | Val acc: 46.01% | LR: 0.000029
Epoch: 013 | Train loss: 0.9930 | Train acc: 50.59% | Val loss: 1.0096 | Val acc: 45.93% | LR: 0.000028
Epoch: 014 | Train loss: 0.9947 | Train acc: 50.19% | Val loss: 1.0039 | Val acc: 46.05% | LR: 0.000028
Epoch: 015 | Train loss: 0.9957 | Train acc: 50.08% | Val loss: 1.0039 | Val acc: 45.99% | LR: 0.000028
Epoch: 016 | Train loss: 0.9929 | Train acc: 50.70% | Val loss: 1.0039 | Val acc: 46.07% | LR: 0.000028
Epoch: 017 | Train loss: 0.9942 | Train acc: 50.44% | Val loss: 1.0038 | Val acc: 45.97% | LR: 0.000028
Epoch: 018 | Train loss: 0.9938 | Train acc: 50.26% | Val loss: 1.0040 | Val acc: 46.09% | LR: 0.000028
Epoch: 019 | Train loss: 0.9892 | Train acc: 50.70% | Val loss: 1.0052 | Val acc: 46.13% | LR: 0.000028
Epoch: 020 | Train loss: 0.9843 | Train acc: 51.13% | Val loss: 1.0047 | Val acc: 46.07% | LR: 0.000028
Epoch: 021 | Train loss: 0.9926 | Train acc: 50.43% | Val loss: 1.0038 | Val acc: 46.09% | LR: 0.000028
Epoch: 022 | Train loss: 0.9905 | Train acc: 50.55% | Val loss: 1.0038 | Val acc: 46.09% | LR: 0.000027
Epoch: 023 | Train loss: 0.9938 | Train acc: 50.29% | Val loss: 1.0038 | Val acc: 46.05% | LR: 0.000027
Epoch: 024 | Train loss: 0.9878 | Train acc: 50.84% | Val loss: 1.0036 | Val acc: 46.15% | LR: 0.000027
Epoch: 025 | Train loss: 0.9915 | Train acc: 50.48% | Val loss: 1.0039 | Val acc: 46.26% | LR: 0.000027
Epoch: 026 | Train loss: 0.9923 | Train acc: 50.41% | Val loss: 1.0036 | Val acc: 46.21% | LR: 0.000027
Epoch: 027 | Train loss: 0.9894 | Train acc: 50.66% | Val loss: 1.0032 | Val acc: 46.46% | LR: 0.000027
Epoch: 028 | Train loss: 0.9843 | Train acc: 51.08% | Val loss: 1.0032 | Val acc: 46.48% | LR: 0.000027
Epoch: 029 | Train loss: 0.9868 | Train acc: 50.57% | Val loss: 1.0028 | Val acc: 46.62% | LR: 0.000026
Epoch: 030 | Train loss: 0.9829 | Train acc: 50.96% | Val loss: 1.0034 | Val acc: 46.50% | LR: 0.000026
Epoch: 031 | Train loss: 0.9960 | Train acc: 50.23% | Val loss: 1.0035 | Val acc: 46.54% | LR: 0.000026
Epoch: 032 | Train loss: 0.9915 | Train acc: 50.34% | Val loss: 1.0043 | Val acc: 46.36% | LR: 0.000026
Epoch: 033 | Train loss: 0.9938 | Train acc: 50.33% | Val loss: 1.0035 | Val acc: 46.33% | LR: 0.000026
Epoch: 034 | Train loss: 0.9890 | Train acc: 50.74% | Val loss: 1.0100 | Val acc: 46.66% | LR: 0.000025
Epoch: 035 | Train loss: 0.9908 | Train acc: 50.87% | Val loss: 1.0030 | Val acc: 46.41% | LR: 0.000025
Epoch: 036 | Train loss: 0.9853 | Train acc: 50.93% | Val loss: 1.0028 | Val acc: 46.35% | LR: 0.000025
Epoch: 037 | Train loss: 0.9869 | Train acc: 51.04% | Val loss: 1.0030 | Val acc: 46.31% | LR: 0.000025
Epoch: 038 | Train loss: 0.9979 | Train acc: 50.12% | Val loss: 1.0027 | Val acc: 46.51% | LR: 0.000025
Epoch: 039 | Train loss: 0.9857 | Train acc: 50.80% | Val loss: 1.0024 | Val acc: 46.61% | LR: 0.000024
Epoch: 040 | Train loss: 0.9944 | Train acc: 50.66% | Val loss: 1.0021 | Val acc: 46.49% | LR: 0.000024
Epoch: 041 | Train loss: 0.9927 | Train acc: 50.47% | Val loss: 1.0026 | Val acc: 46.53% | LR: 0.000024
Epoch: 042 | Train loss: 0.9820 | Train acc: 51.12% | Val loss: 1.0020 | Val acc: 46.55% | LR: 0.000024
Epoch: 043 | Train loss: 1.0071 | Train acc: 50.26% | Val loss: 1.0030 | Val acc: 46.39% | LR: 0.000024
Epoch: 044 | Train loss: 0.9893 | Train acc: 50.94% | Val loss: 1.0023 | Val acc: 46.74% | LR: 0.000023
Epoch: 045 | Train loss: 0.9933 | Train acc: 50.59% | Val loss: 1.0021 | Val acc: 46.73% | LR: 0.000023
Epoch: 046 | Train loss: 0.9918 | Train acc: 50.72% | Val loss: 1.0020 | Val acc: 46.74% | LR: 0.000023
Epoch: 047 | Train loss: 0.9944 | Train acc: 50.52% | Val loss: 1.0019 | Val acc: 46.68% | LR: 0.000023
Epoch: 048 | Train loss: 0.9914 | Train acc: 50.95% | Val loss: 1.0020 | Val acc: 46.69% | LR: 0.000022
Epoch: 049 | Train loss: 0.9972 | Train acc: 50.47% | Val loss: 1.0019 | Val acc: 47.13% | LR: 0.000022
Epoch: 050 | Train loss: 0.9892 | Train acc: 51.00% | Val loss: 1.0017 | Val acc: 47.47% | LR: 0.000022
Epoch: 051 | Train loss: 0.9839 | Train acc: 51.65% | Val loss: 1.0031 | Val acc: 47.49% | LR: 0.000022
Epoch: 052 | Train loss: 0.9910 | Train acc: 50.85% | Val loss: 1.0006 | Val acc: 47.73% | LR: 0.000021
Epoch: 053 | Train loss: 0.9927 | Train acc: 50.62% | Val loss: 1.0032 | Val acc: 47.71% | LR: 0.000021
Epoch: 054 | Train loss: 0.9861 | Train acc: 51.11% | Val loss: 1.0017 | Val acc: 47.90% | LR: 0.000021
Epoch: 055 | Train loss: 0.9905 | Train acc: 50.85% | Val loss: 1.0017 | Val acc: 47.94% | LR: 0.000020
Epoch: 056 | Train loss: 0.9970 | Train acc: 50.50% | Val loss: 1.0014 | Val acc: 47.98% | LR: 0.000020
Epoch: 057 | Train loss: 0.9885 | Train acc: 51.12% | Val loss: 1.0009 | Val acc: 48.25% | LR: 0.000020
Epoch: 058 | Train loss: 0.9927 | Train acc: 50.81% | Val loss: 1.0010 | Val acc: 48.38% | LR: 0.000020
Epoch: 059 | Train loss: 0.9899 | Train acc: 51.15% | Val loss: 1.0007 | Val acc: 48.58% | LR: 0.000019
Epoch: 060 | Train loss: 0.9904 | Train acc: 50.92% | Val loss: 1.0008 | Val acc: 48.62% | LR: 0.000019
Epoch: 061 | Train loss: 0.9943 | Train acc: 50.56% | Val loss: 1.0010 | Val acc: 48.46% | LR: 0.000019
Epoch: 062 | Train loss: 0.9842 | Train acc: 51.24% | Val loss: 1.0021 | Val acc: 48.48% | LR: 0.000019
Epoch: 063 | Train loss: 0.9882 | Train acc: 50.88% | Val loss: 1.0005 | Val acc: 48.50% | LR: 0.000018
Epoch: 064 | Train loss: 0.9913 | Train acc: 50.61% | Val loss: 1.0004 | Val acc: 48.58% | LR: 0.000018
Epoch: 065 | Train loss: 0.9877 | Train acc: 51.05% | Val loss: 1.0019 | Val acc: 48.39% | LR: 0.000018
Epoch: 066 | Train loss: 0.9972 | Train acc: 50.27% | Val loss: 1.0006 | Val acc: 48.52% | LR: 0.000017
Epoch: 067 | Train loss: 0.9881 | Train acc: 50.91% | Val loss: 1.0081 | Val acc: 48.68% | LR: 0.000017
Epoch: 068 | Train loss: 0.9889 | Train acc: 51.04% | Val loss: 1.0000 | Val acc: 48.87% | LR: 0.000017
Epoch: 069 | Train loss: 0.9826 | Train acc: 51.29% | Val loss: 1.0013 | Val acc: 48.74% | LR: 0.000016
Epoch: 070 | Train loss: 0.9896 | Train acc: 50.82% | Val loss: 1.0007 | Val acc: 48.87% | LR: 0.000016
Epoch: 071 | Train loss: 0.9893 | Train acc: 50.66% | Val loss: 1.0005 | Val acc: 48.69% | LR: 0.000016
Epoch: 072 | Train loss: 0.9950 | Train acc: 50.64% | Val loss: 1.0001 | Val acc: 48.99% | LR: 0.000016
Epoch: 073 | Train loss: 0.9888 | Train acc: 51.03% | Val loss: 1.0000 | Val acc: 48.83% | LR: 0.000015
Epoch: 074 | Train loss: 0.9933 | Train acc: 50.67% | Val loss: 1.0016 | Val acc: 49.02% | LR: 0.000015
Epoch: 075 | Train loss: 0.9898 | Train acc: 50.78% | Val loss: 0.9995 | Val acc: 49.16% | LR: 0.000015
Epoch: 076 | Train loss: 0.9928 | Train acc: 50.68% | Val loss: 1.0064 | Val acc: 49.17% | LR: 0.000014
Epoch: 077 | Train loss: 0.9883 | Train acc: 50.93% | Val loss: 0.9991 | Val acc: 49.18% | LR: 0.000014
Epoch: 078 | Train loss: 0.9907 | Train acc: 50.57% | Val loss: 0.9993 | Val acc: 49.23% | LR: 0.000014
Epoch: 079 | Train loss: 0.9833 | Train acc: 51.13% | Val loss: 1.0011 | Val acc: 49.27% | LR: 0.000014
Epoch: 080 | Train loss: 0.9919 | Train acc: 50.58% | Val loss: 0.9988 | Val acc: 49.39% | LR: 0.000013
Epoch: 081 | Train loss: 0.9836 | Train acc: 51.06% | Val loss: 0.9988 | Val acc: 49.51% | LR: 0.000013
Epoch: 082 | Train loss: 0.9821 | Train acc: 51.40% | Val loss: 1.0349 | Val acc: 49.40% | LR: 0.000013
Epoch: 083 | Train loss: 0.9886 | Train acc: 50.77% | Val loss: 0.9986 | Val acc: 49.45% | LR: 0.000012
Epoch: 084 | Train loss: 0.9899 | Train acc: 50.90% | Val loss: 0.9985 | Val acc: 49.27% | LR: 0.000012
Epoch: 085 | Train loss: 0.9769 | Train acc: 51.79% | Val loss: 0.9989 | Val acc: 49.25% | LR: 0.000012
Epoch: 086 | Train loss: 0.9939 | Train acc: 50.71% | Val loss: 0.9981 | Val acc: 49.39% | LR: 0.000012
Epoch: 087 | Train loss: 0.9927 | Train acc: 50.70% | Val loss: 0.9990 | Val acc: 49.37% | LR: 0.000011
Epoch: 088 | Train loss: 0.9866 | Train acc: 51.08% | Val loss: 0.9980 | Val acc: 49.39% | LR: 0.000011
Epoch: 089 | Train loss: 0.9913 | Train acc: 50.82% | Val loss: 0.9986 | Val acc: 49.37% | LR: 0.000011
Epoch: 090 | Train loss: 0.9952 | Train acc: 51.03% | Val loss: 0.9996 | Val acc: 49.47% | LR: 0.000010
Epoch: 091 | Train loss: 0.9883 | Train acc: 50.99% | Val loss: 1.0016 | Val acc: 49.37% | LR: 0.000010
Epoch: 092 | Train loss: 0.9867 | Train acc: 51.11% | Val loss: 1.0168 | Val acc: 49.39% | LR: 0.000010
Epoch: 093 | Train loss: 0.9850 | Train acc: 51.27% | Val loss: 0.9984 | Val acc: 49.39% | LR: 0.000010
Epoch: 094 | Train loss: 0.9882 | Train acc: 50.84% | Val loss: 0.9984 | Val acc: 49.39% | LR: 0.000009
Epoch: 095 | Train loss: 0.9852 | Train acc: 51.17% | Val loss: 1.0022 | Val acc: 49.39% | LR: 0.000009
Epoch: 096 | Train loss: 0.9944 | Train acc: 50.66% | Val loss: 0.9989 | Val acc: 49.41% | LR: 0.000009
Epoch: 097 | Train loss: 0.9836 | Train acc: 51.18% | Val loss: 1.0097 | Val acc: 49.37% | LR: 0.000009
Epoch: 098 | Train loss: 0.9975 | Train acc: 50.22% | Val loss: 0.9979 | Val acc: 49.47% | LR: 0.000008
Epoch: 099 | Train loss: 0.9853 | Train acc: 51.18% | Val loss: 0.9978 | Val acc: 49.47% | LR: 0.000008
Epoch: 100 | Train loss: 0.9912 | Train acc: 51.29% | Val loss: 0.9987 | Val acc: 49.54% | LR: 0.000008
Epoch: 101 | Train loss: 0.9865 | Train acc: 50.90% | Val loss: 0.9979 | Val acc: 49.58% | LR: 0.000008
Epoch: 102 | Train loss: 0.9846 | Train acc: 51.03% | Val loss: 0.9981 | Val acc: 49.58% | LR: 0.000007
Epoch: 103 | Train loss: 0.9869 | Train acc: 51.03% | Val loss: 0.9982 | Val acc: 49.52% | LR: 0.000007
Epoch: 104 | Train loss: 0.9838 | Train acc: 51.28% | Val loss: 0.9980 | Val acc: 49.62% | LR: 0.000007
Epoch: 105 | Train loss: 0.9846 | Train acc: 50.93% | Val loss: 0.9978 | Val acc: 49.56% | LR: 0.000007
Epoch: 106 | Train loss: 0.9905 | Train acc: 50.82% | Val loss: 0.9986 | Val acc: 49.60% | LR: 0.000006
Epoch: 107 | Train loss: 0.9899 | Train acc: 50.91% | Val loss: 0.9995 | Val acc: 49.56% | LR: 0.000006
Epoch: 108 | Train loss: 0.9871 | Train acc: 50.83% | Val loss: 1.0003 | Val acc: 49.60% | LR: 0.000006
Epoch: 109 | Train loss: 0.9881 | Train acc: 51.03% | Val loss: 0.9980 | Val acc: 49.56% | LR: 0.000006
Epoch: 110 | Train loss: 0.9912 | Train acc: 50.58% | Val loss: 0.9978 | Val acc: 49.50% | LR: 0.000005
Epoch: 111 | Train loss: 0.9834 | Train acc: 51.19% | Val loss: 0.9981 | Val acc: 49.56% | LR: 0.000005
Epoch: 112 | Train loss: 0.9807 | Train acc: 51.36% | Val loss: 0.9979 | Val acc: 49.60% | LR: 0.000005
Epoch: 113 | Train loss: 0.9827 | Train acc: 51.34% | Val loss: 0.9975 | Val acc: 49.68% | LR: 0.000005
Epoch: 114 | Train loss: 0.9831 | Train acc: 51.25% | Val loss: 0.9975 | Val acc: 49.68% | LR: 0.000005
Epoch: 115 | Train loss: 0.9829 | Train acc: 51.34% | Val loss: 0.9977 | Val acc: 49.62% | LR: 0.000004
Epoch: 116 | Train loss: 0.9860 | Train acc: 50.90% | Val loss: 0.9978 | Val acc: 49.56% | LR: 0.000004
Epoch: 117 | Train loss: 0.9839 | Train acc: 51.09% | Val loss: 0.9977 | Val acc: 49.52% | LR: 0.000004
Epoch: 118 | Train loss: 0.9889 | Train acc: 50.74% | Val loss: 0.9978 | Val acc: 49.51% | LR: 0.000004
Epoch: 119 | Train loss: 0.9868 | Train acc: 51.10% | Val loss: 1.0030 | Val acc: 49.53% | LR: 0.000004
Epoch: 120 | Train loss: 0.9803 | Train acc: 51.44% | Val loss: 0.9973 | Val acc: 49.55% | LR: 0.000004
Epoch: 121 | Train loss: 0.9866 | Train acc: 51.10% | Val loss: 0.9974 | Val acc: 49.51% | LR: 0.000003
Epoch: 122 | Train loss: 0.9886 | Train acc: 50.92% | Val loss: 0.9978 | Val acc: 49.57% | LR: 0.000003
Epoch: 123 | Train loss: 0.9999 | Train acc: 49.94% | Val loss: 0.9979 | Val acc: 49.61% | LR: 0.000003
Epoch: 124 | Train loss: 0.9869 | Train acc: 50.91% | Val loss: 0.9972 | Val acc: 49.61% | LR: 0.000003
Epoch: 125 | Train loss: 0.9846 | Train acc: 51.19% | Val loss: 0.9996 | Val acc: 49.61% | LR: 0.000003
Epoch: 126 | Train loss: 0.9937 | Train acc: 50.56% | Val loss: 0.9976 | Val acc: 49.61% | LR: 0.000003
Epoch: 127 | Train loss: 0.9874 | Train acc: 51.00% | Val loss: 0.9985 | Val acc: 49.55% | LR: 0.000002
Epoch: 128 | Train loss: 0.9894 | Train acc: 50.83% | Val loss: 0.9972 | Val acc: 49.57% | LR: 0.000002
Epoch: 129 | Train loss: 0.9862 | Train acc: 51.17% | Val loss: 0.9974 | Val acc: 49.57% | LR: 0.000002
Epoch: 130 | Train loss: 0.9847 | Train acc: 51.00% | Val loss: 0.9974 | Val acc: 49.55% | LR: 0.000002
Epoch: 131 | Train loss: 0.9898 | Train acc: 50.92% | Val loss: 0.9971 | Val acc: 49.65% | LR: 0.000002
Epoch: 132 | Train loss: 0.9861 | Train acc: 51.00% | Val loss: 0.9973 | Val acc: 49.65% | LR: 0.000002
Epoch: 133 | Train loss: 0.9812 | Train acc: 51.28% | Val loss: 0.9969 | Val acc: 49.75% | LR: 0.000002
Epoch: 134 | Train loss: 0.9894 | Train acc: 50.90% | Val loss: 0.9973 | Val acc: 49.75% | LR: 0.000002
Epoch: 135 | Train loss: 0.9871 | Train acc: 51.00% | Val loss: 0.9973 | Val acc: 49.77% | LR: 0.000002
Epoch: 136 | Train loss: 0.9844 | Train acc: 51.18% | Val loss: 0.9973 | Val acc: 49.77% | LR: 0.000002
Epoch: 137 | Train loss: 0.9856 | Train acc: 51.00% | Val loss: 0.9973 | Val acc: 49.81% | LR: 0.000001
Epoch: 138 | Train loss: 0.9957 | Train acc: 50.48% | Val loss: 0.9970 | Val acc: 49.85% | LR: 0.000001
Epoch: 139 | Train loss: 0.9876 | Train acc: 51.00% | Val loss: 0.9972 | Val acc: 49.81% | LR: 0.000001
Epoch: 140 | Train loss: 0.9873 | Train acc: 51.10% | Val loss: 0.9972 | Val acc: 49.81% | LR: 0.000001
Epoch: 141 | Train loss: 0.9885 | Train acc: 50.84% | Val loss: 0.9972 | Val acc: 49.81% | LR: 0.000001
Epoch: 142 | Train loss: 0.9795 | Train acc: 51.44% | Val loss: 0.9972 | Val acc: 49.83% | LR: 0.000001
Epoch: 143 | Train loss: 0.9885 | Train acc: 51.00% | Val loss: 0.9972 | Val acc: 49.83% | LR: 0.000001
Epoch: 144 | Train loss: 0.9905 | Train acc: 50.83% | Val loss: 0.9972 | Val acc: 49.79% | LR: 0.000001
Epoch: 145 | Train loss: 0.9877 | Train acc: 51.00% | Val loss: 0.9972 | Val acc: 49.79% | LR: 0.000001
Epoch: 146 | Train loss: 0.9869 | Train acc: 50.84% | Val loss: 0.9973 | Val acc: 49.81% | LR: 0.000001
Epoch: 147 | Train loss: 0.9885 | Train acc: 50.84% | Val loss: 0.9972 | Val acc: 49.81% | LR: 0.000001
Epoch: 148 | Train loss: 0.9996 | Train acc: 50.04% | Val loss: 0.9972 | Val acc: 49.81% | LR: 0.000001
Epoch: 149 | Train loss: 0.9940 | Train acc: 50.66% | Val loss: 0.9980 | Val acc: 49.81% | LR: 0.000001

[I 2025-09-23 16:47:56,106] Trial 31 finished with value: 0.4980999231338501 and parameters: {'lr': 2.905741095861995e-05, 'hidden_size': 245, 'dropout': 0.35084304940912875, 'weight_decay': 1.2341792034452715e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0005 | Train acc: 49.63% | Val loss: 0.9953 | Val acc: 54.63% | LR: 0.000029
Epoch: 001 | Train loss: 0.9987 | Train acc: 50.63% | Val loss: 0.9944 | Val acc: 54.72% | LR: 0.000029
Epoch: 002 | Train loss: 0.9990 | Train acc: 50.25% | Val loss: 0.9938 | Val acc: 54.17% | LR: 0.000029
Epoch: 003 | Train loss: 0.9970 | Train acc: 51.17% | Val loss: 0.9933 | Val acc: 53.64% | LR: 0.000029
Epoch: 004 | Train loss: 0.9969 | Train acc: 51.67% | Val loss: 0.9925 | Val acc: 53.19% | LR: 0.000029
Epoch: 005 | Train loss: 0.9953 | Train acc: 50.50% | Val loss: 1.0000 | Val acc: 52.91% | LR: 0.000029
Epoch: 006 | Train loss: 0.9966 | Train acc: 50.84% | Val loss: 0.9960 | Val acc: 52.81% | LR: 0.000029
Epoch: 007 | Train loss: 1.0171 | Train acc: 50.56% | Val loss: 0.9921 | Val acc: 53.09% | LR: 0.000029
Epoch: 008 | Train loss: 1.1435 | Train acc: 50.36% | Val loss: 0.9941 | Val acc: 52.95% | LR: 0.000029
Epoch: 009 | Train loss: 1.0056 | Train acc: 50.70% | Val loss: 0.9957 | Val acc: 52.89% | LR: 0.000029
Epoch: 010 | Train loss: 0.9958 | Train acc: 50.76% | Val loss: 0.9969 | Val acc: 53.21% | LR: 0.000029
Epoch: 011 | Train loss: 0.9955 | Train acc: 50.82% | Val loss: 0.9954 | Val acc: 52.96% | LR: 0.000029
Epoch: 012 | Train loss: 0.9963 | Train acc: 50.55% | Val loss: 0.9982 | Val acc: 53.01% | LR: 0.000029
Epoch: 013 | Train loss: 0.9932 | Train acc: 51.05% | Val loss: 0.9920 | Val acc: 52.78% | LR: 0.000029
Epoch: 014 | Train loss: 0.9902 | Train acc: 51.38% | Val loss: 0.9929 | Val acc: 52.76% | LR: 0.000029
Epoch: 015 | Train loss: 0.9923 | Train acc: 51.03% | Val loss: 0.9931 | Val acc: 52.63% | LR: 0.000029
Epoch: 016 | Train loss: 0.9968 | Train acc: 50.30% | Val loss: 0.9930 | Val acc: 52.46% | LR: 0.000029
Epoch: 017 | Train loss: 0.9923 | Train acc: 51.10% | Val loss: 0.9929 | Val acc: 52.38% | LR: 0.000028
Epoch: 018 | Train loss: 0.9913 | Train acc: 50.92% | Val loss: 0.9929 | Val acc: 52.42% | LR: 0.000028
Epoch: 019 | Train loss: 0.9966 | Train acc: 50.38% | Val loss: 0.9927 | Val acc: 52.32% | LR: 0.000028
Epoch: 020 | Train loss: 0.9898 | Train acc: 50.99% | Val loss: 0.9926 | Val acc: 52.42% | LR: 0.000028
Epoch: 021 | Train loss: 0.9893 | Train acc: 50.81% | Val loss: 0.9925 | Val acc: 52.46% | LR: 0.000028
Epoch: 022 | Train loss: 0.9947 | Train acc: 50.55% | Val loss: 0.9926 | Val acc: 52.34% | LR: 0.000028
Epoch: 023 | Train loss: 0.9934 | Train acc: 50.55% | Val loss: 0.9925 | Val acc: 52.36% | LR: 0.000028
Epoch: 024 | Train loss: 0.9899 | Train acc: 50.90% | Val loss: 0.9923 | Val acc: 52.36% | LR: 0.000027
Epoch: 025 | Train loss: 0.9887 | Train acc: 50.73% | Val loss: 0.9922 | Val acc: 52.36% | LR: 0.000027
Epoch: 026 | Train loss: 0.9816 | Train acc: 51.54% | Val loss: 0.9922 | Val acc: 52.36% | LR: 0.000027
Epoch: 027 | Train loss: 0.9858 | Train acc: 51.10% | Val loss: 0.9920 | Val acc: 52.40% | LR: 0.000027
Epoch: 028 | Train loss: 0.9895 | Train acc: 50.83% | Val loss: 0.9920 | Val acc: 52.36% | LR: 0.000027
Epoch: 029 | Train loss: 0.9822 | Train acc: 51.37% | Val loss: 0.9920 | Val acc: 52.30% | LR: 0.000027
Epoch: 030 | Train loss: 0.9912 | Train acc: 50.75% | Val loss: 0.9918 | Val acc: 52.32% | LR: 0.000027
Epoch: 031 | Train loss: 0.9849 | Train acc: 51.19% | Val loss: 0.9916 | Val acc: 52.32% | LR: 0.000026
Epoch: 032 | Train loss: 0.9893 | Train acc: 50.84% | Val loss: 0.9915 | Val acc: 52.32% | LR: 0.000026
Epoch: 033 | Train loss: 0.9902 | Train acc: 50.75% | Val loss: 0.9913 | Val acc: 52.28% | LR: 0.000026
Epoch: 034 | Train loss: 0.9856 | Train acc: 51.28% | Val loss: 0.9911 | Val acc: 52.32% | LR: 0.000026
Epoch: 035 | Train loss: 0.9932 | Train acc: 50.67% | Val loss: 0.9909 | Val acc: 52.21% | LR: 0.000026
Epoch: 036 | Train loss: 0.9985 | Train acc: 50.41% | Val loss: 0.9908 | Val acc: 52.21% | LR: 0.000025
Epoch: 037 | Train loss: 0.9877 | Train acc: 51.04% | Val loss: 0.9905 | Val acc: 52.20% | LR: 0.000025
Epoch: 038 | Train loss: 0.9857 | Train acc: 51.30% | Val loss: 0.9902 | Val acc: 52.19% | LR: 0.000025
Epoch: 039 | Train loss: 0.9916 | Train acc: 50.70% | Val loss: 0.9900 | Val acc: 52.13% | LR: 0.000025
Epoch: 040 | Train loss: 0.9907 | Train acc: 50.79% | Val loss: 0.9897 | Val acc: 52.13% | LR: 0.000024
Epoch: 041 | Train loss: 0.9877 | Train acc: 51.12% | Val loss: 0.9896 | Val acc: 52.07% | LR: 0.000024
Epoch: 042 | Train loss: 0.9900 | Train acc: 50.87% | Val loss: 0.9894 | Val acc: 52.07% | LR: 0.000024
Epoch: 043 | Train loss: 0.9878 | Train acc: 50.87% | Val loss: 0.9893 | Val acc: 51.84% | LR: 0.000024
Epoch: 044 | Train loss: 0.9858 | Train acc: 51.23% | Val loss: 0.9890 | Val acc: 51.88% | LR: 0.000024
Epoch: 045 | Train loss: 0.9873 | Train acc: 50.96% | Val loss: 0.9888 | Val acc: 51.88% | LR: 0.000023
Epoch: 046 | Train loss: 0.9934 | Train acc: 50.61% | Val loss: 0.9887 | Val acc: 51.92% | LR: 0.000023
Epoch: 047 | Train loss: 0.9888 | Train acc: 50.96% | Val loss: 0.9884 | Val acc: 51.92% | LR: 0.000023
Epoch: 048 | Train loss: 0.9873 | Train acc: 50.95% | Val loss: 0.9882 | Val acc: 51.98% | LR: 0.000023
Epoch: 049 | Train loss: 0.9865 | Train acc: 50.95% | Val loss: 0.9878 | Val acc: 51.98% | LR: 0.000022
Epoch: 050 | Train loss: 0.9855 | Train acc: 51.03% | Val loss: 0.9875 | Val acc: 52.04% | LR: 0.000022

[I 2025-09-23 16:48:49,214] Trial 32 finished with value: 0.5199970841407776 and parameters: {'lr': 2.939931344884346e-05, 'hidden_size': 209, 'dropout': 0.35948642551839427, 'weight_decay': 7.244472068139074e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0002 | Train acc: 50.24% | Val loss: 1.0018 | Val acc: 45.97% | LR: 0.000083
Epoch: 001 | Train loss: 0.9987 | Train acc: 50.24% | Val loss: 1.0014 | Val acc: 45.98% | LR: 0.000083
Epoch: 002 | Train loss: 0.9933 | Train acc: 50.90% | Val loss: 1.0017 | Val acc: 46.11% | LR: 0.000083
Epoch: 003 | Train loss: 0.9966 | Train acc: 50.70% | Val loss: 1.0015 | Val acc: 46.32% | LR: 0.000083
Epoch: 004 | Train loss: 0.9876 | Train acc: 51.11% | Val loss: 1.0016 | Val acc: 46.41% | LR: 0.000082
Epoch: 005 | Train loss: 0.9880 | Train acc: 51.02% | Val loss: 1.0015 | Val acc: 46.98% | LR: 0.000082
Epoch: 006 | Train loss: 0.9847 | Train acc: 51.30% | Val loss: 1.0010 | Val acc: 47.88% | LR: 0.000082
Epoch: 007 | Train loss: 0.9939 | Train acc: 50.92% | Val loss: 1.0004 | Val acc: 48.46% | LR: 0.000082
Epoch: 008 | Train loss: 0.9882 | Train acc: 50.97% | Val loss: 1.0002 | Val acc: 48.84% | LR: 0.000082
Epoch: 009 | Train loss: 0.9893 | Train acc: 50.85% | Val loss: 0.9995 | Val acc: 49.39% | LR: 0.000082
Epoch: 010 | Train loss: 0.9812 | Train acc: 51.35% | Val loss: 0.9990 | Val acc: 50.01% | LR: 0.000082
Epoch: 011 | Train loss: 0.9948 | Train acc: 50.66% | Val loss: 0.9981 | Val acc: 50.36% | LR: 0.000081
Epoch: 012 | Train loss: 0.9944 | Train acc: 50.62% | Val loss: 0.9967 | Val acc: 50.62% | LR: 0.000081
Epoch: 013 | Train loss: 0.9981 | Train acc: 50.37% | Val loss: 0.9951 | Val acc: 50.73% | LR: 0.000081
Epoch: 014 | Train loss: 0.9904 | Train acc: 50.99% | Val loss: 0.9920 | Val acc: 51.15% | LR: 0.000081
Epoch: 015 | Train loss: 0.9925 | Train acc: 50.67% | Val loss: 0.9853 | Val acc: 51.72% | LR: 0.000080
Epoch: 016 | Train loss: 0.9816 | Train acc: 51.26% | Val loss: 0.9826 | Val acc: 51.72% | LR: 0.000080
Epoch: 017 | Train loss: 0.9857 | Train acc: 50.86% | Val loss: 0.9862 | Val acc: 51.07% | LR: 0.000080
Epoch: 018 | Train loss: 0.9889 | Train acc: 50.60% | Val loss: 0.9904 | Val acc: 50.62% | LR: 0.000080
Epoch: 019 | Train loss: 0.9824 | Train acc: 51.23% | Val loss: 0.9902 | Val acc: 50.82% | LR: 0.000079
Epoch: 020 | Train loss: 0.9863 | Train acc: 50.87% | Val loss: 0.9889 | Val acc: 51.00% | LR: 0.000079
Epoch: 021 | Train loss: 0.9787 | Train acc: 51.30% | Val loss: 0.9873 | Val acc: 50.76% | LR: 0.000078
Epoch: 022 | Train loss: 0.9890 | Train acc: 50.67% | Val loss: 0.9917 | Val acc: 50.73% | LR: 0.000078
Epoch: 023 | Train loss: 0.9857 | Train acc: 50.88% | Val loss: 0.9942 | Val acc: 50.57% | LR: 0.000078
Epoch: 024 | Train loss: 0.9825 | Train acc: 51.04% | Val loss: 0.9964 | Val acc: 50.34% | LR: 0.000077
Epoch: 025 | Train loss: 0.9891 | Train acc: 50.60% | Val loss: 1.0025 | Val acc: 49.38% | LR: 0.000077
Epoch: 026 | Train loss: 0.9834 | Train acc: 51.22% | Val loss: 0.9979 | Val acc: 49.84% | LR: 0.000076
Epoch: 027 | Train loss: 0.9872 | Train acc: 50.88% | Val loss: 0.9972 | Val acc: 50.10% | LR: 0.000076
Epoch: 028 | Train loss: 0.9923 | Train acc: 50.35% | Val loss: 0.9960 | Val acc: 50.02% | LR: 0.000075
Epoch: 029 | Train loss: 0.9847 | Train acc: 50.93% | Val loss: 0.9994 | Val acc: 49.78% | LR: 0.000075
Epoch: 030 | Train loss: 0.9816 | Train acc: 51.11% | Val loss: 1.0009 | Val acc: 49.72% | LR: 0.000074
Epoch: 031 | Train loss: 0.9819 | Train acc: 51.19% | Val loss: 1.0521 | Val acc: 49.73% | LR: 0.000074
Epoch: 032 | Train loss: 0.9851 | Train acc: 51.30% | Val loss: 1.0081 | Val acc: 49.32% | LR: 0.000073
Epoch: 033 | Train loss: 0.9786 | Train acc: 51.30% | Val loss: 1.0077 | Val acc: 49.47% | LR: 0.000073
Epoch: 034 | Train loss: 0.9762 | Train acc: 51.33% | Val loss: 1.0137 | Val acc: 49.32% | LR: 0.000072
Epoch: 035 | Train loss: 0.9838 | Train acc: 50.81% | Val loss: 1.0010 | Val acc: 50.19% | LR: 0.000072
Epoch: 036 | Train loss: 0.9817 | Train acc: 50.97% | Val loss: 0.9983 | Val acc: 50.15% | LR: 0.000071
Epoch: 037 | Train loss: 0.9855 | Train acc: 50.70% | Val loss: 1.0025 | Val acc: 50.06% | LR: 0.000070
Epoch: 038 | Train loss: 0.9779 | Train acc: 51.15% | Val loss: 0.9990 | Val acc: 50.31% | LR: 0.000070
Epoch: 039 | Train loss: 0.9867 | Train acc: 50.72% | Val loss: 0.9973 | Val acc: 50.31% | LR: 0.000069
Epoch: 040 | Train loss: 0.9793 | Train acc: 51.07% | Val loss: 1.0113 | Val acc: 50.21% | LR: 0.000069
Epoch: 041 | Train loss: 0.9770 | Train acc: 51.34% | Val loss: 1.0177 | Val acc: 50.37% | LR: 0.000068
Epoch: 042 | Train loss: 0.9883 | Train acc: 50.45% | Val loss: 0.9893 | Val acc: 50.48% | LR: 0.000067
Epoch: 043 | Train loss: 0.9768 | Train acc: 51.28% | Val loss: 0.9922 | Val acc: 50.44% | LR: 0.000067
Epoch: 044 | Train loss: 0.9794 | Train acc: 51.11% | Val loss: 0.9958 | Val acc: 50.30% | LR: 0.000066
Epoch: 045 | Train loss: 0.9796 | Train acc: 51.12% | Val loss: 0.9883 | Val acc: 50.35% | LR: 0.000065
Epoch: 046 | Train loss: 0.9817 | Train acc: 50.93% | Val loss: 0.9921 | Val acc: 50.22% | LR: 0.000064
Epoch: 047 | Train loss: 0.9785 | Train acc: 51.05% | Val loss: 0.9969 | Val acc: 50.08% | LR: 0.000064
Epoch: 048 | Train loss: 0.9837 | Train acc: 50.97% | Val loss: 0.9974 | Val acc: 50.15% | LR: 0.000063
Epoch: 049 | Train loss: 0.9914 | Train acc: 50.36% | Val loss: 0.9970 | Val acc: 50.16% | LR: 0.000062
Epoch: 050 | Train loss: 0.9788 | Train acc: 51.12% | Val loss: 0.9923 | Val acc: 50.42% | LR: 0.000062
Epoch: 051 | Train loss: 0.9925 | Train acc: 50.28% | Val loss: 1.0015 | Val acc: 50.17% | LR: 0.000061
Epoch: 052 | Train loss: 0.9819 | Train acc: 51.06% | Val loss: 0.9973 | Val acc: 50.21% | LR: 0.000060
Epoch: 053 | Train loss: 0.9861 | Train acc: 51.04% | Val loss: 0.9929 | Val acc: 50.22% | LR: 0.000059
Epoch: 054 | Train loss: 0.9729 | Train acc: 51.63% | Val loss: 0.9920 | Val acc: 50.24% | LR: 0.000058
Epoch: 055 | Train loss: 0.9884 | Train acc: 50.61% | Val loss: 0.9960 | Val acc: 50.10% | LR: 0.000058
Epoch: 056 | Train loss: 0.9748 | Train acc: 51.34% | Val loss: 0.9958 | Val acc: 50.12% | LR: 0.000057
Epoch: 057 | Train loss: 0.9858 | Train acc: 50.80% | Val loss: 0.9958 | Val acc: 50.12% | LR: 0.000056
Epoch: 058 | Train loss: 0.9833 | Train acc: 50.87% | Val loss: 0.9932 | Val acc: 50.10% | LR: 0.000055
Epoch: 059 | Train loss: 0.9751 | Train acc: 51.40% | Val loss: 0.9942 | Val acc: 50.02% | LR: 0.000054
Epoch: 060 | Train loss: 0.9795 | Train acc: 51.05% | Val loss: 0.9950 | Val acc: 50.12% | LR: 0.000054
Epoch: 061 | Train loss: 0.9804 | Train acc: 51.07% | Val loss: 0.9929 | Val acc: 50.06% | LR: 0.000053
Epoch: 062 | Train loss: 0.9784 | Train acc: 51.23% | Val loss: 0.9931 | Val acc: 50.16% | LR: 0.000052
Epoch: 063 | Train loss: 0.9828 | Train acc: 50.89% | Val loss: 0.9960 | Val acc: 50.08% | LR: 0.000051
Epoch: 064 | Train loss: 0.9799 | Train acc: 51.05% | Val loss: 0.9915 | Val acc: 50.18% | LR: 0.000050

[I 2025-09-23 16:49:51,701] Trial 33 finished with value: 0.5032772302627564 and parameters: {'lr': 8.271514961845743e-05, 'hidden_size': 252, 'dropout': 0.39514429831739223, 'weight_decay': 4.05753130112096e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9994 | Train acc: 50.10% | Val loss: 1.0043 | Val acc: 45.97% | LR: 0.000038
Epoch: 001 | Train loss: 0.9988 | Train acc: 50.42% | Val loss: 1.0043 | Val acc: 46.15% | LR: 0.000038
Epoch: 002 | Train loss: 0.9990 | Train acc: 50.71% | Val loss: 1.0043 | Val acc: 46.36% | LR: 0.000038
Epoch: 003 | Train loss: 0.9990 | Train acc: 50.63% | Val loss: 1.0043 | Val acc: 46.44% | LR: 0.000038
Epoch: 004 | Train loss: 0.9987 | Train acc: 50.47% | Val loss: 1.0047 | Val acc: 46.44% | LR: 0.000038
Epoch: 005 | Train loss: 0.9980 | Train acc: 50.82% | Val loss: 1.0044 | Val acc: 46.78% | LR: 0.000038
Epoch: 006 | Train loss: 0.9981 | Train acc: 50.67% | Val loss: 1.0039 | Val acc: 46.72% | LR: 0.000038
Epoch: 007 | Train loss: 0.9958 | Train acc: 51.23% | Val loss: 1.0043 | Val acc: 46.66% | LR: 0.000038
Epoch: 008 | Train loss: 0.9971 | Train acc: 50.89% | Val loss: 1.0044 | Val acc: 46.85% | LR: 0.000038
Epoch: 009 | Train loss: 0.9970 | Train acc: 50.88% | Val loss: 1.0041 | Val acc: 47.06% | LR: 0.000038
Epoch: 010 | Train loss: 0.9967 | Train acc: 50.96% | Val loss: 1.0042 | Val acc: 46.90% | LR: 0.000038
Epoch: 011 | Train loss: 0.9960 | Train acc: 51.11% | Val loss: 1.0038 | Val acc: 46.96% | LR: 0.000038
Epoch: 012 | Train loss: 0.9951 | Train acc: 51.25% | Val loss: 1.0037 | Val acc: 47.29% | LR: 0.000038
Epoch: 013 | Train loss: 0.9941 | Train acc: 51.26% | Val loss: 1.0033 | Val acc: 47.69% | LR: 0.000038
Epoch: 014 | Train loss: 0.9995 | Train acc: 50.26% | Val loss: 1.0030 | Val acc: 47.85% | LR: 0.000037
Epoch: 015 | Train loss: 0.9932 | Train acc: 51.25% | Val loss: 1.0029 | Val acc: 47.83% | LR: 0.000037
Epoch: 016 | Train loss: 0.9940 | Train acc: 51.14% | Val loss: 1.0031 | Val acc: 47.80% | LR: 0.000037
Epoch: 017 | Train loss: 0.9967 | Train acc: 50.60% | Val loss: 1.0820 | Val acc: 48.22% | LR: 0.000037
Epoch: 018 | Train loss: 0.9944 | Train acc: 51.05% | Val loss: 1.0116 | Val acc: 48.49% | LR: 0.000037
Epoch: 019 | Train loss: 0.9970 | Train acc: 50.47% | Val loss: 1.0021 | Val acc: 48.77% | LR: 0.000037
Epoch: 020 | Train loss: 0.9949 | Train acc: 50.74% | Val loss: 1.0039 | Val acc: 49.10% | LR: 0.000037
Epoch: 021 | Train loss: 0.9921 | Train acc: 51.07% | Val loss: 1.0014 | Val acc: 49.23% | LR: 0.000036
Epoch: 022 | Train loss: 0.9927 | Train acc: 50.88% | Val loss: 1.0013 | Val acc: 49.23% | LR: 0.000036
Epoch: 023 | Train loss: 0.9918 | Train acc: 51.06% | Val loss: 1.0018 | Val acc: 49.35% | LR: 0.000036
Epoch: 024 | Train loss: 0.9935 | Train acc: 50.82% | Val loss: 1.0011 | Val acc: 49.36% | LR: 0.000036
Epoch: 025 | Train loss: 0.9942 | Train acc: 50.83% | Val loss: 1.0014 | Val acc: 49.29% | LR: 0.000036
Epoch: 026 | Train loss: 0.9949 | Train acc: 50.65% | Val loss: 1.0013 | Val acc: 49.29% | LR: 0.000035
Epoch: 027 | Train loss: 0.9879 | Train acc: 51.29% | Val loss: 1.0013 | Val acc: 49.29% | LR: 0.000035
Epoch: 028 | Train loss: 0.9924 | Train acc: 50.89% | Val loss: 1.0007 | Val acc: 49.43% | LR: 0.000035
Epoch: 029 | Train loss: 0.9923 | Train acc: 50.72% | Val loss: 1.0015 | Val acc: 49.39% | LR: 0.000035
Epoch: 030 | Train loss: 0.9923 | Train acc: 50.73% | Val loss: 1.0017 | Val acc: 49.49% | LR: 0.000035
Epoch: 031 | Train loss: 0.9852 | Train acc: 51.43% | Val loss: 1.0023 | Val acc: 49.47% | LR: 0.000034
Epoch: 032 | Train loss: 0.9907 | Train acc: 50.90% | Val loss: 1.0017 | Val acc: 49.54% | LR: 0.000034
Epoch: 033 | Train loss: 0.9904 | Train acc: 50.80% | Val loss: 1.0006 | Val acc: 49.62% | LR: 0.000034
Epoch: 034 | Train loss: 0.9893 | Train acc: 50.92% | Val loss: 0.9995 | Val acc: 49.80% | LR: 0.000034
Epoch: 035 | Train loss: 0.9896 | Train acc: 50.74% | Val loss: 0.9987 | Val acc: 49.98% | LR: 0.000033
Epoch: 036 | Train loss: 0.9917 | Train acc: 50.55% | Val loss: 0.9972 | Val acc: 50.12% | LR: 0.000033
Epoch: 037 | Train loss: 0.9900 | Train acc: 50.76% | Val loss: 0.9953 | Val acc: 50.27% | LR: 0.000033
Epoch: 038 | Train loss: 0.9857 | Train acc: 51.19% | Val loss: 0.9946 | Val acc: 50.42% | LR: 0.000032
Epoch: 039 | Train loss: 0.9797 | Train acc: 51.57% | Val loss: 0.9937 | Val acc: 50.62% | LR: 0.000032
Epoch: 040 | Train loss: 0.9863 | Train acc: 50.86% | Val loss: 0.9927 | Val acc: 50.60% | LR: 0.000032
Epoch: 041 | Train loss: 0.9880 | Train acc: 50.76% | Val loss: 0.9929 | Val acc: 50.56% | LR: 0.000032
Epoch: 042 | Train loss: 0.9843 | Train acc: 51.05% | Val loss: 0.9931 | Val acc: 50.60% | LR: 0.000031
Epoch: 043 | Train loss: 0.9853 | Train acc: 50.95% | Val loss: 0.9931 | Val acc: 50.52% | LR: 0.000031
Epoch: 044 | Train loss: 0.9798 | Train acc: 51.41% | Val loss: 0.9930 | Val acc: 50.56% | LR: 0.000031
Epoch: 045 | Train loss: 0.9793 | Train acc: 51.32% | Val loss: 0.9930 | Val acc: 50.46% | LR: 0.000030
Epoch: 046 | Train loss: 0.9830 | Train acc: 51.05% | Val loss: 0.9933 | Val acc: 50.52% | LR: 0.000030
Epoch: 047 | Train loss: 0.9884 | Train acc: 50.79% | Val loss: 0.9932 | Val acc: 50.48% | LR: 0.000030
Epoch: 048 | Train loss: 0.9866 | Train acc: 50.78% | Val loss: 0.9929 | Val acc: 50.48% | LR: 0.000029
Epoch: 049 | Train loss: 0.9815 | Train acc: 51.13% | Val loss: 0.9923 | Val acc: 50.52% | LR: 0.000029
Epoch: 050 | Train loss: 0.9831 | Train acc: 51.05% | Val loss: 0.9928 | Val acc: 50.50% | LR: 0.000029
Epoch: 051 | Train loss: 1.1940 | Train acc: 50.61% | Val loss: 1.0075 | Val acc: 50.43% | LR: 0.000028
Epoch: 052 | Train loss: 0.9864 | Train acc: 51.07% | Val loss: 1.0023 | Val acc: 50.47% | LR: 0.000028
Epoch: 053 | Train loss: 0.9894 | Train acc: 50.80% | Val loss: 0.9990 | Val acc: 50.38% | LR: 0.000028
Epoch: 054 | Train loss: 0.9853 | Train acc: 51.24% | Val loss: 1.0263 | Val acc: 50.44% | LR: 0.000027
Epoch: 055 | Train loss: 0.9838 | Train acc: 51.15% | Val loss: 1.0405 | Val acc: 50.30% | LR: 0.000027
Epoch: 056 | Train loss: 0.9917 | Train acc: 50.58% | Val loss: 0.9976 | Val acc: 50.51% | LR: 0.000027
Epoch: 057 | Train loss: 0.9900 | Train acc: 50.57% | Val loss: 1.0061 | Val acc: 50.51% | LR: 0.000026
Epoch: 058 | Train loss: 0.9916 | Train acc: 50.52% | Val loss: 1.0440 | Val acc: 50.42% | LR: 0.000026
Epoch: 059 | Train loss: 0.9827 | Train acc: 51.31% | Val loss: 0.9979 | Val acc: 50.58% | LR: 0.000025
Epoch: 060 | Train loss: 0.9968 | Train acc: 50.12% | Val loss: 1.0052 | Val acc: 50.67% | LR: 0.000025
Epoch: 061 | Train loss: 0.9803 | Train acc: 51.39% | Val loss: 1.0116 | Val acc: 51.12% | LR: 0.000025
Epoch: 062 | Train loss: 0.9821 | Train acc: 51.19% | Val loss: 1.0076 | Val acc: 50.69% | LR: 0.000024
Epoch: 063 | Train loss: 0.9832 | Train acc: 51.09% | Val loss: 1.4265 | Val acc: 51.04% | LR: 0.000024
Epoch: 064 | Train loss: 0.9873 | Train acc: 50.86% | Val loss: 1.0270 | Val acc: 50.67% | LR: 0.000024
Epoch: 065 | Train loss: 0.9832 | Train acc: 51.11% | Val loss: 1.0169 | Val acc: 50.69% | LR: 0.000023
Epoch: 066 | Train loss: 0.9944 | Train acc: 50.83% | Val loss: 1.0277 | Val acc: 50.57% | LR: 0.000023
Epoch: 067 | Train loss: 0.9838 | Train acc: 51.11% | Val loss: 1.0206 | Val acc: 50.62% | LR: 0.000022
Epoch: 068 | Train loss: 0.9839 | Train acc: 51.03% | Val loss: 1.0929 | Val acc: 50.57% | LR: 0.000022
Epoch: 069 | Train loss: 0.9884 | Train acc: 50.85% | Val loss: 1.0351 | Val acc: 50.43% | LR: 0.000022
Epoch: 070 | Train loss: 1.0389 | Train acc: 50.58% | Val loss: 1.0266 | Val acc: 50.49% | LR: 0.000021
Epoch: 071 | Train loss: 0.9876 | Train acc: 50.95% | Val loss: 1.0530 | Val acc: 50.57% | LR: 0.000021
Epoch: 072 | Train loss: 0.9857 | Train acc: 50.76% | Val loss: 1.0117 | Val acc: 50.89% | LR: 0.000020
Epoch: 073 | Train loss: 0.9913 | Train acc: 51.37% | Val loss: 1.0364 | Val acc: 50.59% | LR: 0.000020
Epoch: 074 | Train loss: 0.9778 | Train acc: 51.45% | Val loss: 1.0237 | Val acc: 50.41% | LR: 0.000020
Epoch: 075 | Train loss: 0.9841 | Train acc: 50.90% | Val loss: 1.0246 | Val acc: 50.41% | LR: 0.000019
Epoch: 076 | Train loss: 0.9827 | Train acc: 51.10% | Val loss: 1.2941 | Val acc: 50.37% | LR: 0.000019
Epoch: 077 | Train loss: 0.9904 | Train acc: 50.58% | Val loss: 1.0143 | Val acc: 50.35% | LR: 0.000019
Epoch: 078 | Train loss: 0.9902 | Train acc: 50.63% | Val loss: 1.0563 | Val acc: 50.49% | LR: 0.000018
Epoch: 079 | Train loss: 0.9845 | Train acc: 51.10% | Val loss: 1.0442 | Val acc: 50.45% | LR: 0.000018
Epoch: 080 | Train loss: 0.9900 | Train acc: 50.66% | Val loss: 1.0139 | Val acc: 50.37% | LR: 0.000017
Epoch: 081 | Train loss: 0.9836 | Train acc: 51.07% | Val loss: 1.0678 | Val acc: 50.31% | LR: 0.000017
Epoch: 082 | Train loss: 0.9811 | Train acc: 51.25% | Val loss: 1.0158 | Val acc: 50.33% | LR: 0.000017
Epoch: 083 | Train loss: 0.9815 | Train acc: 51.25% | Val loss: 1.0819 | Val acc: 50.47% | LR: 0.000016
Epoch: 084 | Train loss: 0.9838 | Train acc: 50.82% | Val loss: 1.0256 | Val acc: 50.31% | LR: 0.000016
Epoch: 085 | Train loss: 0.9808 | Train acc: 51.17% | Val loss: 1.1241 | Val acc: 50.37% | LR: 0.000015
Epoch: 086 | Train loss: 0.9896 | Train acc: 50.47% | Val loss: 1.0560 | Val acc: 50.33% | LR: 0.000015
Epoch: 087 | Train loss: 0.9813 | Train acc: 51.16% | Val loss: 1.0080 | Val acc: 50.35% | LR: 0.000015
Epoch: 088 | Train loss: 0.9877 | Train acc: 50.91% | Val loss: 1.0625 | Val acc: 50.39% | LR: 0.000014
Epoch: 089 | Train loss: 0.9906 | Train acc: 50.56% | Val loss: 1.0304 | Val acc: 50.37% | LR: 0.000014
Epoch: 090 | Train loss: 0.9803 | Train acc: 51.35% | Val loss: 1.0226 | Val acc: 50.33% | LR: 0.000014
Epoch: 091 | Train loss: 0.9854 | Train acc: 51.17% | Val loss: 1.0241 | Val acc: 50.33% | LR: 0.000013
Epoch: 092 | Train loss: 0.9865 | Train acc: 50.64% | Val loss: 1.0067 | Val acc: 50.34% | LR: 0.000013
Epoch: 093 | Train loss: 0.9850 | Train acc: 50.91% | Val loss: 1.0082 | Val acc: 50.33% | LR: 0.000012
Epoch: 094 | Train loss: 0.9940 | Train acc: 50.30% | Val loss: 1.0229 | Val acc: 50.35% | LR: 0.000012
Epoch: 095 | Train loss: 0.9846 | Train acc: 50.83% | Val loss: 1.0082 | Val acc: 50.25% | LR: 0.000012
Epoch: 096 | Train loss: 0.9818 | Train acc: 51.05% | Val loss: 1.0342 | Val acc: 50.32% | LR: 0.000011
Epoch: 097 | Train loss: 0.9834 | Train acc: 51.08% | Val loss: 1.0109 | Val acc: 50.17% | LR: 0.000011
Epoch: 098 | Train loss: 0.9885 | Train acc: 50.47% | Val loss: 1.0059 | Val acc: 50.29% | LR: 0.000011
Epoch: 099 | Train loss: 0.9931 | Train acc: 50.29% | Val loss: 1.0136 | Val acc: 50.33% | LR: 0.000010
Epoch: 100 | Train loss: 0.9880 | Train acc: 50.72% | Val loss: 1.0160 | Val acc: 50.15% | LR: 0.000010
Epoch: 101 | Train loss: 0.9844 | Train acc: 50.90% | Val loss: 1.0309 | Val acc: 50.09% | LR: 0.000010
Epoch: 102 | Train loss: 0.9956 | Train acc: 50.28% | Val loss: 1.0116 | Val acc: 50.15% | LR: 0.000009
Epoch: 103 | Train loss: 0.9809 | Train acc: 51.08% | Val loss: 1.0093 | Val acc: 50.09% | LR: 0.000009
Epoch: 104 | Train loss: 0.9877 | Train acc: 50.64% | Val loss: 1.0835 | Val acc: 50.17% | LR: 0.000009
Epoch: 105 | Train loss: 0.9839 | Train acc: 50.98% | Val loss: 1.0083 | Val acc: 50.13% | LR: 0.000008
Epoch: 106 | Train loss: 0.9820 | Train acc: 51.08% | Val loss: 1.0561 | Val acc: 50.09% | LR: 0.000008
Epoch: 107 | Train loss: 0.9772 | Train acc: 51.42% | Val loss: 1.0432 | Val acc: 50.09% | LR: 0.000008
Epoch: 108 | Train loss: 0.9825 | Train acc: 50.99% | Val loss: 1.0254 | Val acc: 50.17% | LR: 0.000007
Epoch: 109 | Train loss: 0.9850 | Train acc: 50.90% | Val loss: 1.0579 | Val acc: 50.09% | LR: 0.000007
Epoch: 110 | Train loss: 0.9807 | Train acc: 51.16% | Val loss: 1.0084 | Val acc: 50.21% | LR: 0.000007

[I 2025-09-23 16:51:27,382] Trial 34 finished with value: 0.5008822619915009 and parameters: {'lr': 3.8382449560068804e-05, 'hidden_size': 80, 'dropout': 0.2919491011907306, 'weight_decay': 3.3326130858824264e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0025 | Train acc: 49.26% | Val loss: 0.9999 | Val acc: 49.97% | LR: 0.000014
Epoch: 001 | Train loss: 1.0044 | Train acc: 48.81% | Val loss: 1.0118 | Val acc: 50.34% | LR: 0.000014
Epoch: 002 | Train loss: 1.0035 | Train acc: 49.28% | Val loss: 1.0017 | Val acc: 50.62% | LR: 0.000014
Epoch: 003 | Train loss: 1.0013 | Train acc: 49.22% | Val loss: 1.0073 | Val acc: 50.16% | LR: 0.000014
Epoch: 004 | Train loss: 1.0032 | Train acc: 49.62% | Val loss: 1.0020 | Val acc: 50.04% | LR: 0.000014
Epoch: 005 | Train loss: 1.0023 | Train acc: 49.40% | Val loss: 1.0018 | Val acc: 50.50% | LR: 0.000014
Epoch: 006 | Train loss: 1.0043 | Train acc: 49.53% | Val loss: 0.9979 | Val acc: 50.42% | LR: 0.000014
Epoch: 007 | Train loss: 1.0038 | Train acc: 49.50% | Val loss: 1.0016 | Val acc: 50.32% | LR: 0.000014
Epoch: 008 | Train loss: 1.0016 | Train acc: 49.46% | Val loss: 1.0078 | Val acc: 50.24% | LR: 0.000014
Epoch: 009 | Train loss: 1.0015 | Train acc: 49.69% | Val loss: 1.0010 | Val acc: 50.34% | LR: 0.000014
Epoch: 010 | Train loss: 1.0027 | Train acc: 49.28% | Val loss: 1.0079 | Val acc: 50.36% | LR: 0.000014
Epoch: 011 | Train loss: 1.0064 | Train acc: 48.59% | Val loss: 1.0056 | Val acc: 50.42% | LR: 0.000014
Epoch: 012 | Train loss: 1.0023 | Train acc: 49.30% | Val loss: 1.0042 | Val acc: 50.63% | LR: 0.000014
Epoch: 013 | Train loss: 1.0036 | Train acc: 48.93% | Val loss: 1.0080 | Val acc: 50.16% | LR: 0.000014
Epoch: 014 | Train loss: 1.0017 | Train acc: 49.68% | Val loss: 0.9996 | Val acc: 50.58% | LR: 0.000014
Epoch: 015 | Train loss: 1.0012 | Train acc: 49.28% | Val loss: 1.0045 | Val acc: 50.14% | LR: 0.000014
Epoch: 016 | Train loss: 1.0017 | Train acc: 49.36% | Val loss: 1.0015 | Val acc: 50.63% | LR: 0.000014
Epoch: 017 | Train loss: 1.0008 | Train acc: 49.49% | Val loss: 1.0014 | Val acc: 50.49% | LR: 0.000014
Epoch: 018 | Train loss: 1.0076 | Train acc: 49.29% | Val loss: 1.0186 | Val acc: 49.54% | LR: 0.000013
Epoch: 019 | Train loss: 1.0005 | Train acc: 49.47% | Val loss: 1.0009 | Val acc: 49.56% | LR: 0.000013
Epoch: 020 | Train loss: 1.0006 | Train acc: 49.55% | Val loss: 1.0022 | Val acc: 49.90% | LR: 0.000013
Epoch: 021 | Train loss: 1.0008 | Train acc: 49.36% | Val loss: 1.0253 | Val acc: 50.01% | LR: 0.000013
Epoch: 022 | Train loss: 1.0009 | Train acc: 49.61% | Val loss: 1.0019 | Val acc: 49.64% | LR: 0.000013
Epoch: 023 | Train loss: 1.0012 | Train acc: 49.84% | Val loss: 1.0213 | Val acc: 49.33% | LR: 0.000013
Epoch: 024 | Train loss: 1.0001 | Train acc: 50.68% | Val loss: 1.0021 | Val acc: 48.92% | LR: 0.000013
Epoch: 025 | Train loss: 1.0079 | Train acc: 50.22% | Val loss: 1.0033 | Val acc: 49.04% | LR: 0.000013
Epoch: 026 | Train loss: 1.0229 | Train acc: 49.37% | Val loss: 0.9997 | Val acc: 49.20% | LR: 0.000013
Epoch: 027 | Train loss: 1.0099 | Train acc: 48.92% | Val loss: 1.0050 | Val acc: 49.06% | LR: 0.000013
Epoch: 028 | Train loss: 1.0064 | Train acc: 50.50% | Val loss: 1.0053 | Val acc: 48.80% | LR: 0.000013
Epoch: 029 | Train loss: 1.0066 | Train acc: 49.85% | Val loss: 1.0013 | Val acc: 48.54% | LR: 0.000013
Epoch: 030 | Train loss: 1.0114 | Train acc: 49.70% | Val loss: 1.0009 | Val acc: 48.66% | LR: 0.000013
Epoch: 031 | Train loss: 1.0139 | Train acc: 50.16% | Val loss: 1.0003 | Val acc: 48.58% | LR: 0.000013
Epoch: 032 | Train loss: 1.0060 | Train acc: 49.35% | Val loss: 1.0013 | Val acc: 48.63% | LR: 0.000013
Epoch: 033 | Train loss: 1.0183 | Train acc: 49.92% | Val loss: 1.0904 | Val acc: 48.24% | LR: 0.000012
Epoch: 034 | Train loss: 1.0062 | Train acc: 49.94% | Val loss: 1.0011 | Val acc: 48.33% | LR: 0.000012
Epoch: 035 | Train loss: 1.0056 | Train acc: 49.60% | Val loss: 1.0167 | Val acc: 48.24% | LR: 0.000012
Epoch: 036 | Train loss: 0.9996 | Train acc: 49.90% | Val loss: 1.0011 | Val acc: 48.28% | LR: 0.000012
Epoch: 037 | Train loss: 1.0038 | Train acc: 49.83% | Val loss: 1.0005 | Val acc: 48.31% | LR: 0.000012
Epoch: 038 | Train loss: 1.0026 | Train acc: 50.20% | Val loss: 1.0003 | Val acc: 47.94% | LR: 0.000012
Epoch: 039 | Train loss: 1.0264 | Train acc: 49.67% | Val loss: 1.0007 | Val acc: 48.01% | LR: 0.000012
Epoch: 040 | Train loss: 1.3640 | Train acc: 50.23% | Val loss: 1.0011 | Val acc: 47.96% | LR: 0.000012
Epoch: 041 | Train loss: 0.9982 | Train acc: 50.53% | Val loss: 1.0135 | Val acc: 47.89% | LR: 0.000012
Epoch: 042 | Train loss: 1.0696 | Train acc: 50.14% | Val loss: 1.0015 | Val acc: 48.04% | LR: 0.000012
Epoch: 043 | Train loss: 1.0050 | Train acc: 49.66% | Val loss: 1.0011 | Val acc: 47.55% | LR: 0.000011
Epoch: 044 | Train loss: 1.0204 | Train acc: 49.91% | Val loss: 1.2347 | Val acc: 47.63% | LR: 0.000011
Epoch: 045 | Train loss: 1.0999 | Train acc: 49.38% | Val loss: 1.0009 | Val acc: 47.51% | LR: 0.000011
Epoch: 046 | Train loss: 1.0044 | Train acc: 49.55% | Val loss: 1.0006 | Val acc: 47.51% | LR: 0.000011
Epoch: 047 | Train loss: 1.0007 | Train acc: 50.58% | Val loss: 1.0006 | Val acc: 47.79% | LR: 0.000011
Epoch: 048 | Train loss: 0.9987 | Train acc: 50.36% | Val loss: 1.0000 | Val acc: 47.91% | LR: 0.000011
Epoch: 049 | Train loss: 0.9993 | Train acc: 50.32% | Val loss: 1.0015 | Val acc: 47.82% | LR: 0.000011
Epoch: 050 | Train loss: 0.9988 | Train acc: 50.42% | Val loss: 1.0009 | Val acc: 47.78% | LR: 0.000011
Epoch: 051 | Train loss: 1.0113 | Train acc: 50.14% | Val loss: 1.0007 | Val acc: 47.55% | LR: 0.000011
Epoch: 052 | Train loss: 1.0165 | Train acc: 49.74% | Val loss: 1.0006 | Val acc: 47.50% | LR: 0.000010
Epoch: 053 | Train loss: 1.0494 | Train acc: 50.06% | Val loss: 1.0011 | Val acc: 47.63% | LR: 0.000010
Epoch: 054 | Train loss: 1.0006 | Train acc: 50.03% | Val loss: 1.0003 | Val acc: 47.68% | LR: 0.000010
Epoch: 055 | Train loss: 0.9990 | Train acc: 50.18% | Val loss: 1.0014 | Val acc: 47.76% | LR: 0.000010
Epoch: 056 | Train loss: 0.9984 | Train acc: 50.46% | Val loss: 0.9998 | Val acc: 47.41% | LR: 0.000010
Epoch: 057 | Train loss: 0.9984 | Train acc: 50.35% | Val loss: 1.0006 | Val acc: 47.52% | LR: 0.000010
Epoch: 058 | Train loss: 0.9982 | Train acc: 50.30% | Val loss: 1.0003 | Val acc: 47.94% | LR: 0.000010
Epoch: 059 | Train loss: 0.9990 | Train acc: 50.12% | Val loss: 1.0013 | Val acc: 47.68% | LR: 0.000010
Epoch: 060 | Train loss: 0.9978 | Train acc: 50.40% | Val loss: 1.0070 | Val acc: 47.81% | LR: 0.000009
Epoch: 061 | Train loss: 0.9979 | Train acc: 50.49% | Val loss: 1.0009 | Val acc: 47.85% | LR: 0.000009

[I 2025-09-23 16:53:11,487] Trial 35 finished with value: 0.4730903744697571 and parameters: {'lr': 1.399073173434255e-05, 'hidden_size': 171, 'dropout': 0.4579615437177043, 'weight_decay': 1.1514691571110703e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9940 | Train acc: 50.67% | Val loss: 1.0007 | Val acc: 47.47% | LR: 0.000170
Epoch: 001 | Train loss: 0.9899 | Train acc: 50.93% | Val loss: 1.0005 | Val acc: 48.27% | LR: 0.000170
Epoch: 002 | Train loss: 0.9976 | Train acc: 50.49% | Val loss: 0.9971 | Val acc: 50.47% | LR: 0.000170
Epoch: 003 | Train loss: 0.9839 | Train acc: 51.34% | Val loss: 0.9934 | Val acc: 51.18% | LR: 0.000170
Epoch: 004 | Train loss: 0.9892 | Train acc: 50.78% | Val loss: 0.9812 | Val acc: 51.73% | LR: 0.000170
Epoch: 005 | Train loss: 0.9829 | Train acc: 51.40% | Val loss: 0.9846 | Val acc: 51.11% | LR: 0.000169
Epoch: 006 | Train loss: 0.9841 | Train acc: 51.17% | Val loss: 0.9862 | Val acc: 51.23% | LR: 0.000169
Epoch: 007 | Train loss: 0.9832 | Train acc: 51.05% | Val loss: 0.9823 | Val acc: 51.23% | LR: 0.000169
Epoch: 008 | Train loss: 0.9839 | Train acc: 50.95% | Val loss: 0.9867 | Val acc: 51.30% | LR: 0.000169
Epoch: 009 | Train loss: 0.9873 | Train acc: 50.67% | Val loss: 0.9834 | Val acc: 51.16% | LR: 0.000168
Epoch: 010 | Train loss: 0.9812 | Train acc: 51.20% | Val loss: 0.9875 | Val acc: 51.16% | LR: 0.000168
Epoch: 011 | Train loss: 0.9799 | Train acc: 51.24% | Val loss: 0.9888 | Val acc: 50.94% | LR: 0.000167
Epoch: 012 | Train loss: 0.9896 | Train acc: 50.45% | Val loss: 0.9966 | Val acc: 50.36% | LR: 0.000167
Epoch: 013 | Train loss: 0.9816 | Train acc: 51.12% | Val loss: 1.0003 | Val acc: 49.88% | LR: 0.000166
Epoch: 014 | Train loss: 0.9779 | Train acc: 51.27% | Val loss: 1.0032 | Val acc: 49.48% | LR: 0.000166
Epoch: 015 | Train loss: 0.9849 | Train acc: 50.94% | Val loss: 1.0128 | Val acc: 49.06% | LR: 0.000165
Epoch: 016 | Train loss: 0.9836 | Train acc: 50.91% | Val loss: 1.0118 | Val acc: 49.14% | LR: 0.000165
Epoch: 017 | Train loss: 0.9794 | Train acc: 51.27% | Val loss: 1.0139 | Val acc: 49.00% | LR: 0.000164
Epoch: 018 | Train loss: 0.9782 | Train acc: 51.27% | Val loss: 1.0051 | Val acc: 49.96% | LR: 0.000163
Epoch: 019 | Train loss: 0.9860 | Train acc: 50.78% | Val loss: 1.0057 | Val acc: 49.84% | LR: 0.000163
Epoch: 020 | Train loss: 0.9764 | Train acc: 51.25% | Val loss: 1.0184 | Val acc: 48.85% | LR: 0.000162
Epoch: 021 | Train loss: 0.9850 | Train acc: 50.78% | Val loss: 1.0153 | Val acc: 49.24% | LR: 0.000161
Epoch: 022 | Train loss: 0.9795 | Train acc: 51.20% | Val loss: 1.0054 | Val acc: 49.84% | LR: 0.000160
Epoch: 023 | Train loss: 0.9746 | Train acc: 51.47% | Val loss: 1.0062 | Val acc: 49.52% | LR: 0.000160
Epoch: 024 | Train loss: 0.9793 | Train acc: 51.10% | Val loss: 1.0062 | Val acc: 49.60% | LR: 0.000159
Epoch: 025 | Train loss: 0.9777 | Train acc: 51.19% | Val loss: 1.0086 | Val acc: 49.64% | LR: 0.000158
Epoch: 026 | Train loss: 0.9759 | Train acc: 51.40% | Val loss: 1.0011 | Val acc: 50.18% | LR: 0.000157
Epoch: 027 | Train loss: 0.9791 | Train acc: 51.14% | Val loss: 0.9946 | Val acc: 50.31% | LR: 0.000156
Epoch: 028 | Train loss: 0.9829 | Train acc: 50.93% | Val loss: 0.9976 | Val acc: 50.02% | LR: 0.000155
Epoch: 029 | Train loss: 0.9731 | Train acc: 51.56% | Val loss: 0.9991 | Val acc: 50.18% | LR: 0.000154
Epoch: 030 | Train loss: 0.9815 | Train acc: 50.94% | Val loss: 0.9989 | Val acc: 50.09% | LR: 0.000153
Epoch: 031 | Train loss: 0.9840 | Train acc: 50.74% | Val loss: 0.9963 | Val acc: 50.18% | LR: 0.000152
Epoch: 032 | Train loss: 0.9869 | Train acc: 50.66% | Val loss: 1.0039 | Val acc: 49.88% | LR: 0.000151
Epoch: 033 | Train loss: 0.9755 | Train acc: 51.37% | Val loss: 1.0006 | Val acc: 50.04% | LR: 0.000149
Epoch: 034 | Train loss: 0.9820 | Train acc: 51.00% | Val loss: 1.0074 | Val acc: 49.74% | LR: 0.000148
Epoch: 035 | Train loss: 0.9815 | Train acc: 50.92% | Val loss: 1.0103 | Val acc: 49.56% | LR: 0.000147
Epoch: 036 | Train loss: 0.9735 | Train acc: 51.38% | Val loss: 1.0070 | Val acc: 49.90% | LR: 0.000146
Epoch: 037 | Train loss: 0.9736 | Train acc: 51.48% | Val loss: 0.9992 | Val acc: 49.94% | LR: 0.000145
Epoch: 038 | Train loss: 0.9678 | Train acc: 51.87% | Val loss: 1.0016 | Val acc: 50.14% | LR: 0.000143
Epoch: 039 | Train loss: 0.9819 | Train acc: 50.99% | Val loss: 0.9993 | Val acc: 49.98% | LR: 0.000142
Epoch: 040 | Train loss: 0.9821 | Train acc: 50.90% | Val loss: 1.0002 | Val acc: 49.87% | LR: 0.000141
Epoch: 041 | Train loss: 0.9797 | Train acc: 51.06% | Val loss: 1.0009 | Val acc: 50.00% | LR: 0.000139
Epoch: 042 | Train loss: 0.9828 | Train acc: 50.96% | Val loss: 1.0019 | Val acc: 49.96% | LR: 0.000138
Epoch: 043 | Train loss: 0.9734 | Train acc: 51.39% | Val loss: 1.0085 | Val acc: 49.72% | LR: 0.000137
Epoch: 044 | Train loss: 0.9860 | Train acc: 50.71% | Val loss: 1.0008 | Val acc: 50.12% | LR: 0.000135
Epoch: 045 | Train loss: 0.9870 | Train acc: 50.63% | Val loss: 1.0014 | Val acc: 50.10% | LR: 0.000134
Epoch: 046 | Train loss: 0.9751 | Train acc: 51.33% | Val loss: 1.0013 | Val acc: 50.20% | LR: 0.000132
Epoch: 047 | Train loss: 0.9806 | Train acc: 51.04% | Val loss: 0.9964 | Val acc: 50.28% | LR: 0.000131
Epoch: 048 | Train loss: 0.9711 | Train acc: 51.59% | Val loss: 0.9982 | Val acc: 50.28% | LR: 0.000129
Epoch: 049 | Train loss: 0.9764 | Train acc: 51.24% | Val loss: 0.9993 | Val acc: 50.04% | LR: 0.000128
Epoch: 050 | Train loss: 0.9775 | Train acc: 51.17% | Val loss: 1.0053 | Val acc: 49.90% | LR: 0.000126
Epoch: 051 | Train loss: 0.9741 | Train acc: 51.42% | Val loss: 1.0032 | Val acc: 49.78% | LR: 0.000125
Epoch: 052 | Train loss: 0.9716 | Train acc: 51.49% | Val loss: 1.0031 | Val acc: 49.76% | LR: 0.000123
Epoch: 053 | Train loss: 0.9782 | Train acc: 51.17% | Val loss: 0.9967 | Val acc: 50.18% | LR: 0.000121

[I 2025-09-23 16:54:23,067] Trial 36 finished with value: 0.49961751103401186 and parameters: {'lr': 0.00017000871173758597, 'hidden_size': 142, 'dropout': 0.3288215638424197, 'weight_decay': 1.0215395410908522e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0035 | Train acc: 49.81% | Val loss: 1.0018 | Val acc: 48.03% | LR: 0.000037
Epoch: 001 | Train loss: 1.0006 | Train acc: 50.25% | Val loss: 1.0181 | Val acc: 46.78% | LR: 0.000037
Epoch: 002 | Train loss: 0.9998 | Train acc: 50.37% | Val loss: 1.0029 | Val acc: 45.81% | LR: 0.000037
Epoch: 003 | Train loss: 0.9994 | Train acc: 50.43% | Val loss: 1.0034 | Val acc: 45.28% | LR: 0.000037
Epoch: 004 | Train loss: 0.9990 | Train acc: 50.03% | Val loss: 1.0005 | Val acc: 46.01% | LR: 0.000037
Epoch: 005 | Train loss: 0.9985 | Train acc: 50.45% | Val loss: 1.0007 | Val acc: 45.52% | LR: 0.000037
Epoch: 006 | Train loss: 0.9995 | Train acc: 50.06% | Val loss: 1.0141 | Val acc: 46.71% | LR: 0.000037
Epoch: 007 | Train loss: 0.9993 | Train acc: 50.00% | Val loss: 1.0038 | Val acc: 45.50% | LR: 0.000037
Epoch: 008 | Train loss: 0.9983 | Train acc: 50.36% | Val loss: 1.0006 | Val acc: 46.19% | LR: 0.000036
Epoch: 009 | Train loss: 0.9972 | Train acc: 50.49% | Val loss: 1.0062 | Val acc: 46.64% | LR: 0.000036
Epoch: 010 | Train loss: 0.9986 | Train acc: 50.28% | Val loss: 1.0031 | Val acc: 46.18% | LR: 0.000036
Epoch: 011 | Train loss: 0.9991 | Train acc: 50.02% | Val loss: 1.0012 | Val acc: 45.78% | LR: 0.000036
Epoch: 012 | Train loss: 0.9995 | Train acc: 50.14% | Val loss: 1.0017 | Val acc: 46.41% | LR: 0.000036
Epoch: 013 | Train loss: 0.9976 | Train acc: 50.36% | Val loss: 1.0095 | Val acc: 46.76% | LR: 0.000036
Epoch: 014 | Train loss: 0.9967 | Train acc: 50.44% | Val loss: 1.0087 | Val acc: 45.94% | LR: 0.000036
Epoch: 015 | Train loss: 0.9964 | Train acc: 50.39% | Val loss: 1.0148 | Val acc: 46.37% | LR: 0.000036
Epoch: 016 | Train loss: 0.9967 | Train acc: 50.40% | Val loss: 1.0047 | Val acc: 46.01% | LR: 0.000036
Epoch: 017 | Train loss: 0.9974 | Train acc: 50.48% | Val loss: 1.0066 | Val acc: 46.21% | LR: 0.000036
Epoch: 018 | Train loss: 0.9932 | Train acc: 50.70% | Val loss: 1.0022 | Val acc: 46.17% | LR: 0.000035
Epoch: 019 | Train loss: 0.9992 | Train acc: 50.15% | Val loss: 1.0031 | Val acc: 46.15% | LR: 0.000035
Epoch: 020 | Train loss: 0.9940 | Train acc: 50.84% | Val loss: 1.0029 | Val acc: 46.78% | LR: 0.000035
Epoch: 021 | Train loss: 0.9928 | Train acc: 50.73% | Val loss: 1.0026 | Val acc: 46.17% | LR: 0.000035
Epoch: 022 | Train loss: 0.9947 | Train acc: 50.43% | Val loss: 1.0020 | Val acc: 46.01% | LR: 0.000035
Epoch: 023 | Train loss: 0.9906 | Train acc: 50.88% | Val loss: 1.0024 | Val acc: 46.01% | LR: 0.000035
Epoch: 024 | Train loss: 0.9935 | Train acc: 50.51% | Val loss: 1.0020 | Val acc: 46.07% | LR: 0.000034
Epoch: 025 | Train loss: 0.9913 | Train acc: 50.51% | Val loss: 1.0027 | Val acc: 45.95% | LR: 0.000034
Epoch: 026 | Train loss: 0.9926 | Train acc: 50.51% | Val loss: 1.0027 | Val acc: 45.95% | LR: 0.000034
Epoch: 027 | Train loss: 0.9934 | Train acc: 50.42% | Val loss: 1.0028 | Val acc: 45.95% | LR: 0.000034
Epoch: 028 | Train loss: 0.9998 | Train acc: 49.80% | Val loss: 1.0028 | Val acc: 45.95% | LR: 0.000034
Epoch: 029 | Train loss: 0.9907 | Train acc: 50.53% | Val loss: 1.0027 | Val acc: 45.95% | LR: 0.000033
Epoch: 030 | Train loss: 0.9870 | Train acc: 50.98% | Val loss: 1.0027 | Val acc: 45.97% | LR: 0.000033
Epoch: 031 | Train loss: 0.9903 | Train acc: 50.56% | Val loss: 1.0027 | Val acc: 45.99% | LR: 0.000033
Epoch: 032 | Train loss: 0.9891 | Train acc: 50.74% | Val loss: 1.0027 | Val acc: 46.17% | LR: 0.000033
Epoch: 033 | Train loss: 0.9982 | Train acc: 49.86% | Val loss: 1.0027 | Val acc: 46.26% | LR: 0.000032
Epoch: 034 | Train loss: 0.9848 | Train acc: 50.93% | Val loss: 1.0026 | Val acc: 46.21% | LR: 0.000032
Epoch: 035 | Train loss: 0.9932 | Train acc: 50.23% | Val loss: 1.0025 | Val acc: 46.69% | LR: 0.000032
Epoch: 036 | Train loss: 1.0120 | Train acc: 50.27% | Val loss: 1.0023 | Val acc: 46.48% | LR: 0.000032
Epoch: 037 | Train loss: 0.9931 | Train acc: 50.68% | Val loss: 1.0023 | Val acc: 46.50% | LR: 0.000031
Epoch: 038 | Train loss: 0.9908 | Train acc: 50.68% | Val loss: 1.0023 | Val acc: 46.64% | LR: 0.000031
Epoch: 039 | Train loss: 0.9858 | Train acc: 51.00% | Val loss: 1.0022 | Val acc: 46.70% | LR: 0.000031
Epoch: 040 | Train loss: 0.9842 | Train acc: 51.02% | Val loss: 1.0022 | Val acc: 46.89% | LR: 0.000031
Epoch: 041 | Train loss: 0.9929 | Train acc: 50.52% | Val loss: 1.0019 | Val acc: 47.40% | LR: 0.000030
Epoch: 042 | Train loss: 0.9901 | Train acc: 50.80% | Val loss: 1.0019 | Val acc: 47.42% | LR: 0.000030
Epoch: 043 | Train loss: 0.9894 | Train acc: 50.74% | Val loss: 1.0020 | Val acc: 47.38% | LR: 0.000030
Epoch: 044 | Train loss: 0.9861 | Train acc: 51.19% | Val loss: 1.0018 | Val acc: 47.18% | LR: 0.000029
Epoch: 045 | Train loss: 0.9827 | Train acc: 51.22% | Val loss: 1.0017 | Val acc: 47.17% | LR: 0.000029
Epoch: 046 | Train loss: 0.9942 | Train acc: 50.56% | Val loss: 1.0016 | Val acc: 47.23% | LR: 0.000029
Epoch: 047 | Train loss: 0.9943 | Train acc: 50.60% | Val loss: 1.0016 | Val acc: 47.31% | LR: 0.000028
Epoch: 048 | Train loss: 0.9879 | Train acc: 51.13% | Val loss: 1.0015 | Val acc: 47.27% | LR: 0.000028
Epoch: 049 | Train loss: 0.9875 | Train acc: 51.07% | Val loss: 1.0013 | Val acc: 47.49% | LR: 0.000028

[I 2025-09-23 16:55:09,585] Trial 37 finished with value: 0.47433277368545534 and parameters: {'lr': 3.679067174739818e-05, 'hidden_size': 204, 'dropout': 0.3671842930750679, 'weight_decay': 0.0001168448311379124}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0008 | Train acc: 50.51% | Val loss: 1.0044 | Val acc: 48.49% | LR: 0.000010
Epoch: 001 | Train loss: 1.0001 | Train acc: 50.03% | Val loss: 1.0041 | Val acc: 48.41% | LR: 0.000010
Epoch: 002 | Train loss: 0.9993 | Train acc: 50.33% | Val loss: 1.0017 | Val acc: 48.47% | LR: 0.000010
Epoch: 003 | Train loss: 1.0092 | Train acc: 50.09% | Val loss: 1.0017 | Val acc: 48.35% | LR: 0.000010
Epoch: 004 | Train loss: 0.9991 | Train acc: 50.45% | Val loss: 1.0020 | Val acc: 48.33% | LR: 0.000010
Epoch: 005 | Train loss: 0.9986 | Train acc: 50.54% | Val loss: 1.0032 | Val acc: 48.33% | LR: 0.000010
Epoch: 006 | Train loss: 1.0029 | Train acc: 50.78% | Val loss: 1.0204 | Val acc: 48.35% | LR: 0.000010
Epoch: 007 | Train loss: 1.0080 | Train acc: 50.35% | Val loss: 1.0021 | Val acc: 48.41% | LR: 0.000010
Epoch: 008 | Train loss: 1.0009 | Train acc: 50.31% | Val loss: 1.0020 | Val acc: 48.37% | LR: 0.000010
Epoch: 009 | Train loss: 1.0004 | Train acc: 50.54% | Val loss: 1.0015 | Val acc: 48.33% | LR: 0.000010
Epoch: 010 | Train loss: 1.0004 | Train acc: 51.07% | Val loss: 1.0034 | Val acc: 48.29% | LR: 0.000010
Epoch: 011 | Train loss: 1.0014 | Train acc: 50.30% | Val loss: 1.0018 | Val acc: 48.33% | LR: 0.000010
Epoch: 012 | Train loss: 1.0210 | Train acc: 50.62% | Val loss: 1.0022 | Val acc: 48.25% | LR: 0.000010
Epoch: 013 | Train loss: 0.9992 | Train acc: 50.80% | Val loss: 1.0024 | Val acc: 48.35% | LR: 0.000010
Epoch: 014 | Train loss: 0.9993 | Train acc: 50.27% | Val loss: 1.0018 | Val acc: 48.37% | LR: 0.000010
Epoch: 015 | Train loss: 0.9989 | Train acc: 50.63% | Val loss: 1.0023 | Val acc: 48.41% | LR: 0.000010
Epoch: 016 | Train loss: 1.0011 | Train acc: 50.61% | Val loss: 1.0018 | Val acc: 48.39% | LR: 0.000010
Epoch: 017 | Train loss: 0.9976 | Train acc: 50.89% | Val loss: 1.0015 | Val acc: 48.39% | LR: 0.000010
Epoch: 018 | Train loss: 1.0001 | Train acc: 50.23% | Val loss: 1.0019 | Val acc: 48.46% | LR: 0.000010
Epoch: 019 | Train loss: 0.9995 | Train acc: 50.16% | Val loss: 1.0021 | Val acc: 48.44% | LR: 0.000010
Epoch: 020 | Train loss: 0.9979 | Train acc: 50.67% | Val loss: 1.0020 | Val acc: 48.43% | LR: 0.000010
Epoch: 021 | Train loss: 0.9973 | Train acc: 50.59% | Val loss: 1.0016 | Val acc: 48.37% | LR: 0.000010
Epoch: 022 | Train loss: 1.0110 | Train acc: 50.22% | Val loss: 1.0038 | Val acc: 48.33% | LR: 0.000010
Epoch: 023 | Train loss: 1.0014 | Train acc: 50.05% | Val loss: 1.0030 | Val acc: 48.31% | LR: 0.000010
Epoch: 024 | Train loss: 0.9986 | Train acc: 49.84% | Val loss: 1.0023 | Val acc: 48.33% | LR: 0.000010
Epoch: 025 | Train loss: 1.0005 | Train acc: 50.06% | Val loss: 1.0021 | Val acc: 48.37% | LR: 0.000010
Epoch: 026 | Train loss: 1.0034 | Train acc: 50.55% | Val loss: 1.0023 | Val acc: 48.35% | LR: 0.000010
Epoch: 027 | Train loss: 0.9979 | Train acc: 50.58% | Val loss: 1.0021 | Val acc: 48.29% | LR: 0.000010
Epoch: 028 | Train loss: 0.9989 | Train acc: 50.84% | Val loss: 1.0019 | Val acc: 48.35% | LR: 0.000010
Epoch: 029 | Train loss: 1.0196 | Train acc: 50.34% | Val loss: 1.0035 | Val acc: 48.33% | LR: 0.000010
Epoch: 030 | Train loss: 0.9959 | Train acc: 50.56% | Val loss: 1.0020 | Val acc: 48.37% | LR: 0.000010
Epoch: 031 | Train loss: 0.9977 | Train acc: 50.40% | Val loss: 1.0045 | Val acc: 48.23% | LR: 0.000009
Epoch: 032 | Train loss: 1.0144 | Train acc: 50.72% | Val loss: 1.0017 | Val acc: 48.33% | LR: 0.000009
Epoch: 033 | Train loss: 1.0003 | Train acc: 50.61% | Val loss: 1.0024 | Val acc: 48.21% | LR: 0.000009
Epoch: 034 | Train loss: 0.9982 | Train acc: 50.18% | Val loss: 1.0018 | Val acc: 48.29% | LR: 0.000009
Epoch: 035 | Train loss: 0.9984 | Train acc: 50.01% | Val loss: 1.0021 | Val acc: 48.38% | LR: 0.000009
Epoch: 036 | Train loss: 0.9964 | Train acc: 50.64% | Val loss: 1.0021 | Val acc: 48.34% | LR: 0.000009
Epoch: 037 | Train loss: 0.9959 | Train acc: 50.72% | Val loss: 1.0024 | Val acc: 48.30% | LR: 0.000009
Epoch: 038 | Train loss: 1.0024 | Train acc: 50.12% | Val loss: 1.0022 | Val acc: 48.36% | LR: 0.000009
Epoch: 039 | Train loss: 0.9996 | Train acc: 49.94% | Val loss: 1.0016 | Val acc: 48.28% | LR: 0.000009
Epoch: 040 | Train loss: 1.0136 | Train acc: 50.17% | Val loss: 1.0025 | Val acc: 48.31% | LR: 0.000009
Epoch: 041 | Train loss: 0.9963 | Train acc: 50.37% | Val loss: 1.0020 | Val acc: 48.29% | LR: 0.000009
Epoch: 042 | Train loss: 0.9998 | Train acc: 50.48% | Val loss: 1.0026 | Val acc: 48.25% | LR: 0.000009
Epoch: 043 | Train loss: 1.0019 | Train acc: 49.67% | Val loss: 1.0023 | Val acc: 48.21% | LR: 0.000009
Epoch: 044 | Train loss: 0.9999 | Train acc: 50.29% | Val loss: 1.0021 | Val acc: 48.24% | LR: 0.000009
Epoch: 045 | Train loss: 0.9963 | Train acc: 50.48% | Val loss: 1.0031 | Val acc: 48.21% | LR: 0.000008
Epoch: 046 | Train loss: 1.0111 | Train acc: 49.68% | Val loss: 1.0025 | Val acc: 48.23% | LR: 0.000008
Epoch: 047 | Train loss: 1.0171 | Train acc: 49.87% | Val loss: 1.0025 | Val acc: 48.25% | LR: 0.000008
Epoch: 048 | Train loss: 0.9986 | Train acc: 50.31% | Val loss: 1.0026 | Val acc: 48.31% | LR: 0.000008
Epoch: 049 | Train loss: 0.9986 | Train acc: 50.39% | Val loss: 1.0023 | Val acc: 48.35% | LR: 0.000008

[I 2025-09-23 16:55:52,627] Trial 38 finished with value: 0.48384841084480285 and parameters: {'lr': 1.0466705977759247e-05, 'hidden_size': 73, 'dropout': 0.4868249660970927, 'weight_decay': 2.1313368708608285e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9995 | Train acc: 50.59% | Val loss: 0.9975 | Val acc: 53.74% | LR: 0.000074
Epoch: 001 | Train loss: 0.9993 | Train acc: 50.85% | Val loss: 0.9981 | Val acc: 53.29% | LR: 0.000074
Epoch: 002 | Train loss: 0.9988 | Train acc: 50.92% | Val loss: 1.0035 | Val acc: 53.81% | LR: 0.000074
Epoch: 003 | Train loss: 1.0247 | Train acc: 50.31% | Val loss: 1.0035 | Val acc: 54.00% | LR: 0.000074
Epoch: 004 | Train loss: 1.0125 | Train acc: 49.85% | Val loss: 0.9971 | Val acc: 54.15% | LR: 0.000074
Epoch: 005 | Train loss: 0.9966 | Train acc: 51.35% | Val loss: 0.9999 | Val acc: 54.11% | LR: 0.000074
Epoch: 006 | Train loss: 0.9972 | Train acc: 50.30% | Val loss: 0.9979 | Val acc: 54.07% | LR: 0.000073
Epoch: 007 | Train loss: 0.9932 | Train acc: 50.91% | Val loss: 0.9978 | Val acc: 54.05% | LR: 0.000073
Epoch: 008 | Train loss: 0.9930 | Train acc: 50.81% | Val loss: 0.9960 | Val acc: 54.23% | LR: 0.000073
Epoch: 009 | Train loss: 0.9900 | Train acc: 50.53% | Val loss: 0.9973 | Val acc: 54.27% | LR: 0.000073
Epoch: 010 | Train loss: 0.9897 | Train acc: 50.74% | Val loss: 0.9976 | Val acc: 54.23% | LR: 0.000073
Epoch: 011 | Train loss: 0.9915 | Train acc: 50.53% | Val loss: 0.9975 | Val acc: 53.99% | LR: 0.000073
Epoch: 012 | Train loss: 0.9897 | Train acc: 50.66% | Val loss: 0.9965 | Val acc: 54.14% | LR: 0.000073
Epoch: 013 | Train loss: 0.9940 | Train acc: 50.54% | Val loss: 0.9964 | Val acc: 54.22% | LR: 0.000072
Epoch: 014 | Train loss: 0.9937 | Train acc: 50.31% | Val loss: 0.9969 | Val acc: 54.49% | LR: 0.000072
Epoch: 015 | Train loss: 0.9925 | Train acc: 50.58% | Val loss: 0.9960 | Val acc: 54.36% | LR: 0.000072
Epoch: 016 | Train loss: 0.9900 | Train acc: 50.83% | Val loss: 0.9956 | Val acc: 54.42% | LR: 0.000072
Epoch: 017 | Train loss: 0.9844 | Train acc: 51.18% | Val loss: 0.9950 | Val acc: 54.00% | LR: 0.000071
Epoch: 018 | Train loss: 0.9917 | Train acc: 50.57% | Val loss: 0.9946 | Val acc: 54.04% | LR: 0.000071
Epoch: 019 | Train loss: 0.9928 | Train acc: 50.65% | Val loss: 0.9947 | Val acc: 53.69% | LR: 0.000071
Epoch: 020 | Train loss: 0.9884 | Train acc: 51.10% | Val loss: 0.9947 | Val acc: 53.31% | LR: 0.000070
Epoch: 021 | Train loss: 0.9885 | Train acc: 51.00% | Val loss: 0.9940 | Val acc: 53.39% | LR: 0.000070
Epoch: 022 | Train loss: 0.9825 | Train acc: 51.50% | Val loss: 0.9937 | Val acc: 53.23% | LR: 0.000070
Epoch: 023 | Train loss: 0.9870 | Train acc: 51.28% | Val loss: 0.9934 | Val acc: 53.22% | LR: 0.000069
Epoch: 024 | Train loss: 0.9947 | Train acc: 50.50% | Val loss: 0.9927 | Val acc: 52.95% | LR: 0.000069
Epoch: 025 | Train loss: 0.9881 | Train acc: 50.75% | Val loss: 0.9920 | Val acc: 53.01% | LR: 0.000069
Epoch: 026 | Train loss: 0.9891 | Train acc: 51.01% | Val loss: 0.9922 | Val acc: 52.32% | LR: 0.000068
Epoch: 027 | Train loss: 0.9876 | Train acc: 51.03% | Val loss: 0.9918 | Val acc: 52.19% | LR: 0.000068
Epoch: 028 | Train loss: 0.9828 | Train acc: 51.38% | Val loss: 0.9906 | Val acc: 52.21% | LR: 0.000067
Epoch: 029 | Train loss: 0.9921 | Train acc: 50.68% | Val loss: 0.9891 | Val acc: 52.37% | LR: 0.000067
Epoch: 030 | Train loss: 0.9890 | Train acc: 50.87% | Val loss: 0.9876 | Val acc: 52.54% | LR: 0.000066
Epoch: 031 | Train loss: 0.9935 | Train acc: 50.58% | Val loss: 0.9856 | Val acc: 52.70% | LR: 0.000066
Epoch: 032 | Train loss: 0.9820 | Train acc: 51.36% | Val loss: 0.9843 | Val acc: 52.48% | LR: 0.000065
Epoch: 033 | Train loss: 0.9894 | Train acc: 50.83% | Val loss: 0.9800 | Val acc: 52.56% | LR: 0.000065
Epoch: 034 | Train loss: 0.9817 | Train acc: 51.26% | Val loss: 0.9769 | Val acc: 52.70% | LR: 0.000065
Epoch: 035 | Train loss: 0.9954 | Train acc: 50.30% | Val loss: 0.9778 | Val acc: 52.51% | LR: 0.000064
Epoch: 036 | Train loss: 0.9872 | Train acc: 50.89% | Val loss: 0.9785 | Val acc: 52.45% | LR: 0.000063
Epoch: 037 | Train loss: 0.9841 | Train acc: 50.94% | Val loss: 0.9780 | Val acc: 52.43% | LR: 0.000063
Epoch: 038 | Train loss: 0.9876 | Train acc: 50.87% | Val loss: 0.9801 | Val acc: 51.87% | LR: 0.000062
Epoch: 039 | Train loss: 0.9863 | Train acc: 50.78% | Val loss: 0.9817 | Val acc: 51.57% | LR: 0.000062
Epoch: 040 | Train loss: 0.9871 | Train acc: 50.81% | Val loss: 0.9848 | Val acc: 51.19% | LR: 0.000061
Epoch: 041 | Train loss: 0.9865 | Train acc: 50.89% | Val loss: 0.9857 | Val acc: 51.05% | LR: 0.000061
Epoch: 042 | Train loss: 0.9867 | Train acc: 50.73% | Val loss: 0.9886 | Val acc: 50.76% | LR: 0.000060
Epoch: 043 | Train loss: 0.9813 | Train acc: 51.24% | Val loss: 0.9903 | Val acc: 50.69% | LR: 0.000059
Epoch: 044 | Train loss: 0.9832 | Train acc: 50.93% | Val loss: 0.9920 | Val acc: 50.63% | LR: 0.000059
Epoch: 045 | Train loss: 0.9805 | Train acc: 51.12% | Val loss: 0.9927 | Val acc: 50.51% | LR: 0.000058
Epoch: 046 | Train loss: 0.9884 | Train acc: 50.60% | Val loss: 0.9942 | Val acc: 50.68% | LR: 0.000058
Epoch: 047 | Train loss: 0.9816 | Train acc: 51.04% | Val loss: 0.9963 | Val acc: 50.45% | LR: 0.000057
Epoch: 048 | Train loss: 0.9896 | Train acc: 50.42% | Val loss: 0.9957 | Val acc: 50.41% | LR: 0.000056
Epoch: 049 | Train loss: 0.9800 | Train acc: 51.31% | Val loss: 0.9967 | Val acc: 50.39% | LR: 0.000056
Epoch: 050 | Train loss: 0.9833 | Train acc: 50.95% | Val loss: 0.9967 | Val acc: 50.33% | LR: 0.000055
Epoch: 051 | Train loss: 0.9805 | Train acc: 51.04% | Val loss: 1.0006 | Val acc: 49.89% | LR: 0.000054
Epoch: 052 | Train loss: 0.9852 | Train acc: 50.78% | Val loss: 0.9981 | Val acc: 50.12% | LR: 0.000054
Epoch: 053 | Train loss: 0.9860 | Train acc: 50.78% | Val loss: 0.9959 | Val acc: 50.26% | LR: 0.000053
Epoch: 054 | Train loss: 0.9905 | Train acc: 50.54% | Val loss: 0.9969 | Val acc: 50.12% | LR: 0.000052
Epoch: 055 | Train loss: 0.9781 | Train acc: 51.31% | Val loss: 1.0001 | Val acc: 49.92% | LR: 0.000052
Epoch: 056 | Train loss: 0.9836 | Train acc: 50.98% | Val loss: 1.0020 | Val acc: 49.84% | LR: 0.000051
Epoch: 057 | Train loss: 0.9805 | Train acc: 51.05% | Val loss: 1.0020 | Val acc: 50.00% | LR: 0.000050
Epoch: 058 | Train loss: 0.9802 | Train acc: 51.10% | Val loss: 1.0045 | Val acc: 49.44% | LR: 0.000049
Epoch: 059 | Train loss: 0.9820 | Train acc: 51.04% | Val loss: 1.0037 | Val acc: 49.58% | LR: 0.000049
Epoch: 060 | Train loss: 0.9837 | Train acc: 50.93% | Val loss: 1.0044 | Val acc: 49.46% | LR: 0.000048
Epoch: 061 | Train loss: 0.9785 | Train acc: 51.24% | Val loss: 1.0072 | Val acc: 49.28% | LR: 0.000047
Epoch: 062 | Train loss: 0.9825 | Train acc: 50.98% | Val loss: 1.0081 | Val acc: 49.19% | LR: 0.000046
Epoch: 063 | Train loss: 0.9878 | Train acc: 50.73% | Val loss: 1.0105 | Val acc: 49.21% | LR: 0.000046

[I 2025-09-23 16:56:51,082] Trial 39 finished with value: 0.49097904562950134 and parameters: {'lr': 7.385921152563537e-05, 'hidden_size': 231, 'dropout': 0.40749878568109876, 'weight_decay': 0.00020354219032903977}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0248 | Train acc: 49.87% | Val loss: 1.0214 | Val acc: 46.48% | LR: 0.000020
Epoch: 001 | Train loss: 1.0012 | Train acc: 49.76% | Val loss: 1.0107 | Val acc: 47.03% | LR: 0.000020
Epoch: 002 | Train loss: 1.0008 | Train acc: 49.65% | Val loss: 1.1157 | Val acc: 46.37% | LR: 0.000020
Epoch: 003 | Train loss: 1.0005 | Train acc: 50.19% | Val loss: 1.0245 | Val acc: 46.92% | LR: 0.000020
Epoch: 004 | Train loss: 0.9997 | Train acc: 49.80% | Val loss: 1.0062 | Val acc: 46.54% | LR: 0.000020
Epoch: 005 | Train loss: 1.0010 | Train acc: 49.70% | Val loss: 1.0077 | Val acc: 46.34% | LR: 0.000020
Epoch: 006 | Train loss: 0.9998 | Train acc: 50.23% | Val loss: 1.0058 | Val acc: 46.38% | LR: 0.000020
Epoch: 007 | Train loss: 0.9987 | Train acc: 50.67% | Val loss: 1.0023 | Val acc: 46.46% | LR: 0.000020
Epoch: 008 | Train loss: 0.9994 | Train acc: 50.47% | Val loss: 1.0141 | Val acc: 45.64% | LR: 0.000020
Epoch: 009 | Train loss: 0.9988 | Train acc: 50.28% | Val loss: 1.0041 | Val acc: 46.14% | LR: 0.000020
Epoch: 010 | Train loss: 0.9982 | Train acc: 51.09% | Val loss: 1.0090 | Val acc: 46.36% | LR: 0.000020
Epoch: 011 | Train loss: 0.9986 | Train acc: 51.20% | Val loss: 1.0030 | Val acc: 46.34% | LR: 0.000020
Epoch: 012 | Train loss: 1.0024 | Train acc: 50.84% | Val loss: 1.0167 | Val acc: 46.18% | LR: 0.000019
Epoch: 013 | Train loss: 0.9979 | Train acc: 50.51% | Val loss: 1.0078 | Val acc: 46.32% | LR: 0.000019
Epoch: 014 | Train loss: 1.0001 | Train acc: 50.76% | Val loss: 1.0213 | Val acc: 46.02% | LR: 0.000019
Epoch: 015 | Train loss: 0.9991 | Train acc: 50.84% | Val loss: 1.0069 | Val acc: 46.08% | LR: 0.000019
Epoch: 016 | Train loss: 0.9977 | Train acc: 50.22% | Val loss: 1.0056 | Val acc: 46.24% | LR: 0.000019
Epoch: 017 | Train loss: 0.9967 | Train acc: 50.60% | Val loss: 1.0102 | Val acc: 45.84% | LR: 0.000019
Epoch: 018 | Train loss: 0.9974 | Train acc: 50.80% | Val loss: 1.0260 | Val acc: 45.82% | LR: 0.000019
Epoch: 019 | Train loss: 0.9976 | Train acc: 50.23% | Val loss: 1.0048 | Val acc: 45.87% | LR: 0.000019
Epoch: 020 | Train loss: 0.9956 | Train acc: 50.52% | Val loss: 1.0053 | Val acc: 45.87% | LR: 0.000019
Epoch: 021 | Train loss: 0.9950 | Train acc: 50.70% | Val loss: 1.0053 | Val acc: 45.76% | LR: 0.000019
Epoch: 022 | Train loss: 0.9980 | Train acc: 49.90% | Val loss: 1.0052 | Val acc: 45.87% | LR: 0.000019
Epoch: 023 | Train loss: 0.9931 | Train acc: 50.96% | Val loss: 1.0053 | Val acc: 45.91% | LR: 0.000019
Epoch: 024 | Train loss: 0.9938 | Train acc: 50.61% | Val loss: 1.0053 | Val acc: 45.93% | LR: 0.000019
Epoch: 025 | Train loss: 0.9952 | Train acc: 50.25% | Val loss: 1.0054 | Val acc: 45.97% | LR: 0.000018
Epoch: 026 | Train loss: 0.9953 | Train acc: 50.34% | Val loss: 1.0053 | Val acc: 45.97% | LR: 0.000018
Epoch: 027 | Train loss: 0.9920 | Train acc: 50.69% | Val loss: 1.0053 | Val acc: 45.97% | LR: 0.000018
Epoch: 028 | Train loss: 0.9916 | Train acc: 50.69% | Val loss: 1.0053 | Val acc: 45.97% | LR: 0.000018
Epoch: 029 | Train loss: 0.9900 | Train acc: 50.69% | Val loss: 1.0053 | Val acc: 45.97% | LR: 0.000018
Epoch: 030 | Train loss: 0.9984 | Train acc: 49.81% | Val loss: 1.0053 | Val acc: 45.97% | LR: 0.000018
Epoch: 031 | Train loss: 0.9960 | Train acc: 50.34% | Val loss: 1.0053 | Val acc: 45.97% | LR: 0.000018
Epoch: 032 | Train loss: 0.9949 | Train acc: 50.34% | Val loss: 1.0053 | Val acc: 45.97% | LR: 0.000018
Epoch: 033 | Train loss: 0.9909 | Train acc: 50.69% | Val loss: 1.0053 | Val acc: 45.97% | LR: 0.000018
Epoch: 034 | Train loss: 0.9914 | Train acc: 50.34% | Val loss: 1.0053 | Val acc: 45.97% | LR: 0.000017
Epoch: 035 | Train loss: 0.9951 | Train acc: 50.07% | Val loss: 1.0052 | Val acc: 45.97% | LR: 0.000017
Epoch: 036 | Train loss: 0.9923 | Train acc: 50.34% | Val loss: 1.0052 | Val acc: 45.97% | LR: 0.000017
Epoch: 037 | Train loss: 0.9891 | Train acc: 50.41% | Val loss: 1.0051 | Val acc: 45.97% | LR: 0.000017
Epoch: 038 | Train loss: 0.9895 | Train acc: 50.68% | Val loss: 1.0049 | Val acc: 45.97% | LR: 0.000017
Epoch: 039 | Train loss: 0.9930 | Train acc: 50.24% | Val loss: 1.0051 | Val acc: 45.97% | LR: 0.000017
Epoch: 040 | Train loss: 0.9866 | Train acc: 50.59% | Val loss: 1.0050 | Val acc: 45.99% | LR: 0.000017
Epoch: 041 | Train loss: 1.0169 | Train acc: 50.67% | Val loss: 1.0049 | Val acc: 45.97% | LR: 0.000016
Epoch: 042 | Train loss: 0.9885 | Train acc: 50.50% | Val loss: 1.0049 | Val acc: 45.97% | LR: 0.000016
Epoch: 043 | Train loss: 0.9916 | Train acc: 50.23% | Val loss: 1.0049 | Val acc: 45.97% | LR: 0.000016
Epoch: 044 | Train loss: 0.9946 | Train acc: 50.15% | Val loss: 1.0048 | Val acc: 45.97% | LR: 0.000016
Epoch: 045 | Train loss: 0.9954 | Train acc: 50.23% | Val loss: 1.0047 | Val acc: 45.97% | LR: 0.000016
Epoch: 046 | Train loss: 0.9902 | Train acc: 50.59% | Val loss: 1.0046 | Val acc: 45.99% | LR: 0.000016
Epoch: 047 | Train loss: 0.9917 | Train acc: 50.33% | Val loss: 1.0047 | Val acc: 45.97% | LR: 0.000015
Epoch: 048 | Train loss: 0.9878 | Train acc: 50.78% | Val loss: 1.0047 | Val acc: 45.99% | LR: 0.000015
Epoch: 049 | Train loss: 0.9877 | Train acc: 50.88% | Val loss: 1.0046 | Val acc: 45.97% | LR: 0.000015
Epoch: 050 | Train loss: 0.9867 | Train acc: 50.52% | Val loss: 1.0045 | Val acc: 45.99% | LR: 0.000015

[I 2025-09-23 16:57:43,458] Trial 40 finished with value: 0.45970038771629335 and parameters: {'lr': 1.9795501289314037e-05, 'hidden_size': 195, 'dropout': 0.3070083150563862, 'weight_decay': 0.0009001990813215304}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9986 | Train acc: 50.68% | Val loss: 1.0042 | Val acc: 45.93% | LR: 0.000023
Epoch: 001 | Train loss: 0.9992 | Train acc: 50.43% | Val loss: 1.0043 | Val acc: 45.95% | LR: 0.000023
Epoch: 002 | Train loss: 0.9965 | Train acc: 50.70% | Val loss: 1.0043 | Val acc: 45.95% | LR: 0.000023
Epoch: 003 | Train loss: 0.9988 | Train acc: 50.25% | Val loss: 1.0043 | Val acc: 45.99% | LR: 0.000023
Epoch: 004 | Train loss: 0.9963 | Train acc: 50.69% | Val loss: 1.0041 | Val acc: 46.01% | LR: 0.000023
Epoch: 005 | Train loss: 0.9974 | Train acc: 50.50% | Val loss: 1.0040 | Val acc: 46.03% | LR: 0.000023
Epoch: 006 | Train loss: 0.9944 | Train acc: 50.69% | Val loss: 1.0040 | Val acc: 46.01% | LR: 0.000023
Epoch: 007 | Train loss: 0.9943 | Train acc: 50.79% | Val loss: 1.0038 | Val acc: 45.93% | LR: 0.000023
Epoch: 008 | Train loss: 0.9971 | Train acc: 50.59% | Val loss: 1.0037 | Val acc: 45.93% | LR: 0.000023
Epoch: 009 | Train loss: 0.9947 | Train acc: 50.70% | Val loss: 1.0037 | Val acc: 45.95% | LR: 0.000023
Epoch: 010 | Train loss: 0.9993 | Train acc: 50.02% | Val loss: 1.0036 | Val acc: 46.25% | LR: 0.000023
Epoch: 011 | Train loss: 0.9941 | Train acc: 50.84% | Val loss: 1.0034 | Val acc: 46.29% | LR: 0.000023
Epoch: 012 | Train loss: 0.9946 | Train acc: 50.74% | Val loss: 1.0033 | Val acc: 46.34% | LR: 0.000023
Epoch: 013 | Train loss: 0.9978 | Train acc: 50.46% | Val loss: 1.0032 | Val acc: 46.66% | LR: 0.000023
Epoch: 014 | Train loss: 0.9947 | Train acc: 50.76% | Val loss: 1.0030 | Val acc: 46.72% | LR: 0.000023
Epoch: 015 | Train loss: 0.9960 | Train acc: 50.56% | Val loss: 1.0030 | Val acc: 46.63% | LR: 0.000023
Epoch: 016 | Train loss: 0.9919 | Train acc: 51.05% | Val loss: 1.0029 | Val acc: 46.84% | LR: 0.000022
Epoch: 017 | Train loss: 0.9946 | Train acc: 50.73% | Val loss: 1.0028 | Val acc: 47.10% | LR: 0.000022
Epoch: 018 | Train loss: 0.9982 | Train acc: 50.36% | Val loss: 1.0026 | Val acc: 47.40% | LR: 0.000022
Epoch: 019 | Train loss: 0.9915 | Train acc: 50.90% | Val loss: 1.0026 | Val acc: 47.44% | LR: 0.000022
Epoch: 020 | Train loss: 0.9970 | Train acc: 50.29% | Val loss: 1.0025 | Val acc: 47.56% | LR: 0.000022
Epoch: 021 | Train loss: 0.9979 | Train acc: 50.47% | Val loss: 1.0022 | Val acc: 48.00% | LR: 0.000022
Epoch: 022 | Train loss: 0.9872 | Train acc: 51.13% | Val loss: 1.0020 | Val acc: 48.23% | LR: 0.000022
Epoch: 023 | Train loss: 0.9910 | Train acc: 50.97% | Val loss: 1.0017 | Val acc: 48.35% | LR: 0.000022
Epoch: 024 | Train loss: 0.9904 | Train acc: 50.97% | Val loss: 1.0014 | Val acc: 48.27% | LR: 0.000022
Epoch: 025 | Train loss: 0.9937 | Train acc: 50.90% | Val loss: 1.0068 | Val acc: 48.21% | LR: 0.000022
Epoch: 026 | Train loss: 0.9893 | Train acc: 50.95% | Val loss: 1.0140 | Val acc: 48.58% | LR: 0.000021
Epoch: 027 | Train loss: 0.9956 | Train acc: 50.58% | Val loss: 1.0019 | Val acc: 48.54% | LR: 0.000021
Epoch: 028 | Train loss: 0.9872 | Train acc: 51.03% | Val loss: 1.0013 | Val acc: 48.39% | LR: 0.000021
Epoch: 029 | Train loss: 0.9903 | Train acc: 51.04% | Val loss: 1.0008 | Val acc: 48.45% | LR: 0.000021
Epoch: 030 | Train loss: 0.9933 | Train acc: 50.71% | Val loss: 1.0014 | Val acc: 48.47% | LR: 0.000021
Epoch: 031 | Train loss: 0.9906 | Train acc: 50.87% | Val loss: 1.0014 | Val acc: 48.45% | LR: 0.000021
Epoch: 032 | Train loss: 0.9900 | Train acc: 50.80% | Val loss: 1.0011 | Val acc: 48.50% | LR: 0.000021
Epoch: 033 | Train loss: 0.9922 | Train acc: 50.60% | Val loss: 1.0009 | Val acc: 48.55% | LR: 0.000020
Epoch: 034 | Train loss: 0.9904 | Train acc: 50.85% | Val loss: 1.0018 | Val acc: 48.45% | LR: 0.000020
Epoch: 035 | Train loss: 0.9902 | Train acc: 50.97% | Val loss: 1.0007 | Val acc: 48.46% | LR: 0.000020
Epoch: 036 | Train loss: 0.9907 | Train acc: 50.88% | Val loss: 1.0014 | Val acc: 48.44% | LR: 0.000020
Epoch: 037 | Train loss: 1.0362 | Train acc: 50.60% | Val loss: 1.0007 | Val acc: 48.44% | LR: 0.000020
Epoch: 038 | Train loss: 1.6294 | Train acc: 50.74% | Val loss: 1.0009 | Val acc: 48.64% | LR: 0.000020
Epoch: 039 | Train loss: 0.9981 | Train acc: 50.27% | Val loss: 1.0040 | Val acc: 49.04% | LR: 0.000019
Epoch: 040 | Train loss: 0.9933 | Train acc: 50.71% | Val loss: 1.0157 | Val acc: 49.00% | LR: 0.000019
Epoch: 041 | Train loss: 0.9885 | Train acc: 51.17% | Val loss: 1.0025 | Val acc: 48.92% | LR: 0.000019
Epoch: 042 | Train loss: 0.9913 | Train acc: 50.95% | Val loss: 1.0050 | Val acc: 48.90% | LR: 0.000019
Epoch: 043 | Train loss: 0.9895 | Train acc: 51.19% | Val loss: 1.0054 | Val acc: 49.30% | LR: 0.000019
Epoch: 044 | Train loss: 0.9911 | Train acc: 50.92% | Val loss: 0.9999 | Val acc: 48.82% | LR: 0.000019
Epoch: 045 | Train loss: 0.9853 | Train acc: 51.36% | Val loss: 1.0011 | Val acc: 49.04% | LR: 0.000018
Epoch: 046 | Train loss: 0.9869 | Train acc: 51.00% | Val loss: 1.0027 | Val acc: 49.10% | LR: 0.000018
Epoch: 047 | Train loss: 0.9953 | Train acc: 50.66% | Val loss: 1.0037 | Val acc: 49.00% | LR: 0.000018
Epoch: 048 | Train loss: 0.9891 | Train acc: 50.96% | Val loss: 1.0017 | Val acc: 49.22% | LR: 0.000018
Epoch: 049 | Train loss: 0.9912 | Train acc: 50.86% | Val loss: 1.0211 | Val acc: 49.17% | LR: 0.000018
Epoch: 050 | Train loss: 0.9875 | Train acc: 51.05% | Val loss: 1.0071 | Val acc: 49.33% | LR: 0.000017
Epoch: 051 | Train loss: 0.9866 | Train acc: 51.15% | Val loss: 0.9997 | Val acc: 49.12% | LR: 0.000017
Epoch: 052 | Train loss: 0.9816 | Train acc: 51.77% | Val loss: 1.0127 | Val acc: 49.01% | LR: 0.000017
Epoch: 053 | Train loss: 0.9937 | Train acc: 50.68% | Val loss: 0.9993 | Val acc: 49.17% | LR: 0.000017
Epoch: 054 | Train loss: 0.9871 | Train acc: 51.25% | Val loss: 0.9997 | Val acc: 49.15% | LR: 0.000017
Epoch: 055 | Train loss: 0.9873 | Train acc: 51.14% | Val loss: 1.0147 | Val acc: 49.09% | LR: 0.000016
Epoch: 056 | Train loss: 0.9958 | Train acc: 50.27% | Val loss: 1.0009 | Val acc: 49.19% | LR: 0.000016
Epoch: 057 | Train loss: 0.9837 | Train acc: 51.43% | Val loss: 1.0003 | Val acc: 49.41% | LR: 0.000016
Epoch: 058 | Train loss: 0.9904 | Train acc: 50.98% | Val loss: 1.0168 | Val acc: 49.33% | LR: 0.000016
Epoch: 059 | Train loss: 0.9926 | Train acc: 50.79% | Val loss: 0.9996 | Val acc: 49.62% | LR: 0.000016
Epoch: 060 | Train loss: 0.9902 | Train acc: 50.89% | Val loss: 1.0065 | Val acc: 49.44% | LR: 0.000015
Epoch: 061 | Train loss: 0.9967 | Train acc: 50.25% | Val loss: 1.0018 | Val acc: 49.62% | LR: 0.000015
Epoch: 062 | Train loss: 0.9937 | Train acc: 51.04% | Val loss: 1.0000 | Val acc: 49.54% | LR: 0.000015
Epoch: 063 | Train loss: 0.9902 | Train acc: 50.90% | Val loss: 1.0014 | Val acc: 49.50% | LR: 0.000015
Epoch: 064 | Train loss: 0.9890 | Train acc: 51.04% | Val loss: 1.0052 | Val acc: 49.50% | LR: 0.000014
Epoch: 065 | Train loss: 0.9983 | Train acc: 50.49% | Val loss: 0.9986 | Val acc: 49.69% | LR: 0.000014
Epoch: 066 | Train loss: 1.0362 | Train acc: 51.08% | Val loss: 1.0060 | Val acc: 49.68% | LR: 0.000014
Epoch: 067 | Train loss: 0.9842 | Train acc: 51.32% | Val loss: 1.0021 | Val acc: 49.57% | LR: 0.000014
Epoch: 068 | Train loss: 0.9898 | Train acc: 51.01% | Val loss: 0.9991 | Val acc: 49.78% | LR: 0.000013
Epoch: 069 | Train loss: 0.9952 | Train acc: 50.79% | Val loss: 0.9994 | Val acc: 49.80% | LR: 0.000013
Epoch: 070 | Train loss: 0.9904 | Train acc: 50.88% | Val loss: 1.0007 | Val acc: 49.80% | LR: 0.000013
Epoch: 071 | Train loss: 0.9905 | Train acc: 50.71% | Val loss: 1.0051 | Val acc: 49.78% | LR: 0.000013
Epoch: 072 | Train loss: 0.9890 | Train acc: 50.80% | Val loss: 0.9972 | Val acc: 49.95% | LR: 0.000013
Epoch: 073 | Train loss: 0.9923 | Train acc: 50.75% | Val loss: 1.0016 | Val acc: 49.72% | LR: 0.000012
Epoch: 074 | Train loss: 0.9834 | Train acc: 51.38% | Val loss: 0.9997 | Val acc: 49.67% | LR: 0.000012
Epoch: 075 | Train loss: 0.9932 | Train acc: 50.69% | Val loss: 1.0017 | Val acc: 49.63% | LR: 0.000012
Epoch: 076 | Train loss: 0.9810 | Train acc: 51.68% | Val loss: 1.0077 | Val acc: 49.54% | LR: 0.000012
Epoch: 077 | Train loss: 0.9937 | Train acc: 50.60% | Val loss: 1.0082 | Val acc: 49.86% | LR: 0.000011
Epoch: 078 | Train loss: 0.9889 | Train acc: 50.67% | Val loss: 1.0303 | Val acc: 49.82% | LR: 0.000011
Epoch: 079 | Train loss: 0.9911 | Train acc: 50.76% | Val loss: 1.0103 | Val acc: 49.78% | LR: 0.000011
Epoch: 080 | Train loss: 0.9867 | Train acc: 51.23% | Val loss: 0.9988 | Val acc: 49.80% | LR: 0.000011
Epoch: 081 | Train loss: 0.9837 | Train acc: 51.34% | Val loss: 1.0125 | Val acc: 49.98% | LR: 0.000010
Epoch: 082 | Train loss: 0.9964 | Train acc: 50.65% | Val loss: 1.0017 | Val acc: 49.76% | LR: 0.000010
Epoch: 083 | Train loss: 0.9979 | Train acc: 50.14% | Val loss: 1.0109 | Val acc: 49.88% | LR: 0.000010
Epoch: 084 | Train loss: 1.0157 | Train acc: 50.85% | Val loss: 1.0219 | Val acc: 49.92% | LR: 0.000010
Epoch: 085 | Train loss: 0.9870 | Train acc: 51.00% | Val loss: 1.0036 | Val acc: 49.78% | LR: 0.000010
Epoch: 086 | Train loss: 0.9825 | Train acc: 51.17% | Val loss: 1.0011 | Val acc: 49.80% | LR: 0.000009
Epoch: 087 | Train loss: 0.9929 | Train acc: 50.53% | Val loss: 1.0008 | Val acc: 49.86% | LR: 0.000009
Epoch: 088 | Train loss: 0.9812 | Train acc: 51.52% | Val loss: 1.0011 | Val acc: 49.92% | LR: 0.000009
Epoch: 089 | Train loss: 0.9905 | Train acc: 50.74% | Val loss: 1.0142 | Val acc: 49.94% | LR: 0.000009
Epoch: 090 | Train loss: 0.9881 | Train acc: 50.84% | Val loss: 1.0060 | Val acc: 50.04% | LR: 0.000008
Epoch: 091 | Train loss: 0.9919 | Train acc: 50.74% | Val loss: 1.0029 | Val acc: 49.98% | LR: 0.000008
Epoch: 092 | Train loss: 0.9904 | Train acc: 50.75% | Val loss: 1.0113 | Val acc: 49.94% | LR: 0.000008
Epoch: 093 | Train loss: 0.9958 | Train acc: 50.22% | Val loss: 1.0097 | Val acc: 49.90% | LR: 0.000008
Epoch: 094 | Train loss: 0.9898 | Train acc: 50.80% | Val loss: 1.0231 | Val acc: 49.92% | LR: 0.000008
Epoch: 095 | Train loss: 0.9927 | Train acc: 50.64% | Val loss: 0.9996 | Val acc: 50.02% | LR: 0.000007
Epoch: 096 | Train loss: 0.9942 | Train acc: 50.53% | Val loss: 1.0036 | Val acc: 49.86% | LR: 0.000007
Epoch: 097 | Train loss: 0.9947 | Train acc: 50.57% | Val loss: 1.0012 | Val acc: 49.90% | LR: 0.000007
Epoch: 098 | Train loss: 1.0009 | Train acc: 50.32% | Val loss: 1.0020 | Val acc: 49.94% | LR: 0.000007
Epoch: 099 | Train loss: 0.9904 | Train acc: 50.68% | Val loss: 1.0003 | Val acc: 49.94% | LR: 0.000007
Epoch: 100 | Train loss: 0.9907 | Train acc: 50.84% | Val loss: 1.0037 | Val acc: 50.00% | LR: 0.000006
Epoch: 101 | Train loss: 0.9914 | Train acc: 50.84% | Val loss: 1.0064 | Val acc: 49.86% | LR: 0.000006
Epoch: 102 | Train loss: 0.9876 | Train acc: 51.05% | Val loss: 1.0249 | Val acc: 50.02% | LR: 0.000006
Epoch: 103 | Train loss: 0.9926 | Train acc: 50.93% | Val loss: 1.0898 | Val acc: 49.98% | LR: 0.000006
Epoch: 104 | Train loss: 0.9915 | Train acc: 50.57% | Val loss: 1.0009 | Val acc: 49.86% | LR: 0.000006
Epoch: 105 | Train loss: 0.9839 | Train acc: 51.37% | Val loss: 1.0145 | Val acc: 49.96% | LR: 0.000005
Epoch: 106 | Train loss: 0.9869 | Train acc: 51.08% | Val loss: 1.0019 | Val acc: 49.94% | LR: 0.000005
Epoch: 107 | Train loss: 0.9888 | Train acc: 51.01% | Val loss: 1.0027 | Val acc: 50.06% | LR: 0.000005
Epoch: 108 | Train loss: 0.9916 | Train acc: 50.67% | Val loss: 1.0014 | Val acc: 49.92% | LR: 0.000005
Epoch: 109 | Train loss: 0.9901 | Train acc: 50.84% | Val loss: 1.0016 | Val acc: 50.02% | LR: 0.000005
Epoch: 110 | Train loss: 0.9902 | Train acc: 51.05% | Val loss: 1.0035 | Val acc: 50.02% | LR: 0.000004
Epoch: 111 | Train loss: 0.9901 | Train acc: 51.03% | Val loss: 1.0049 | Val acc: 49.98% | LR: 0.000004
Epoch: 112 | Train loss: 0.9919 | Train acc: 50.80% | Val loss: 0.9998 | Val acc: 49.96% | LR: 0.000004
Epoch: 113 | Train loss: 0.9910 | Train acc: 50.68% | Val loss: 0.9998 | Val acc: 49.96% | LR: 0.000004
Epoch: 114 | Train loss: 0.9886 | Train acc: 50.84% | Val loss: 1.0040 | Val acc: 49.98% | LR: 0.000004
Epoch: 115 | Train loss: 0.9883 | Train acc: 50.85% | Val loss: 1.0019 | Val acc: 49.86% | LR: 0.000004
Epoch: 116 | Train loss: 0.9874 | Train acc: 51.19% | Val loss: 1.0145 | Val acc: 49.96% | LR: 0.000004
Epoch: 117 | Train loss: 0.9927 | Train acc: 50.67% | Val loss: 1.0007 | Val acc: 49.88% | LR: 0.000003
Epoch: 118 | Train loss: 0.9842 | Train acc: 51.13% | Val loss: 1.0021 | Val acc: 49.94% | LR: 0.000003
Epoch: 119 | Train loss: 0.9864 | Train acc: 51.37% | Val loss: 1.0023 | Val acc: 49.88% | LR: 0.000003
Epoch: 120 | Train loss: 0.9908 | Train acc: 50.67% | Val loss: 1.0085 | Val acc: 49.80% | LR: 0.000003
Epoch: 121 | Train loss: 0.9911 | Train acc: 50.84% | Val loss: 1.2208 | Val acc: 49.78% | LR: 0.000003
Epoch: 122 | Train loss: 0.9940 | Train acc: 50.67% | Val loss: 1.0026 | Val acc: 49.86% | LR: 0.000003
Epoch: 123 | Train loss: 0.9918 | Train acc: 50.67% | Val loss: 1.0018 | Val acc: 49.92% | LR: 0.000003
Epoch: 124 | Train loss: 0.9955 | Train acc: 50.59% | Val loss: 1.0014 | Val acc: 49.96% | LR: 0.000002
Epoch: 125 | Train loss: 0.9982 | Train acc: 50.25% | Val loss: 1.0010 | Val acc: 49.92% | LR: 0.000002
Epoch: 126 | Train loss: 0.9918 | Train acc: 50.97% | Val loss: 0.9998 | Val acc: 49.96% | LR: 0.000002
Epoch: 127 | Train loss: 0.9864 | Train acc: 51.02% | Val loss: 0.9993 | Val acc: 49.96% | LR: 0.000002
Epoch: 128 | Train loss: 0.9884 | Train acc: 51.10% | Val loss: 1.0040 | Val acc: 49.92% | LR: 0.000002
Epoch: 129 | Train loss: 0.9813 | Train acc: 51.47% | Val loss: 1.0079 | Val acc: 49.84% | LR: 0.000002
Epoch: 130 | Train loss: 1.0001 | Train acc: 50.06% | Val loss: 1.0023 | Val acc: 49.92% | LR: 0.000002
Epoch: 131 | Train loss: 0.9847 | Train acc: 51.22% | Val loss: 1.0021 | Val acc: 49.88% | LR: 0.000002
Epoch: 132 | Train loss: 0.9931 | Train acc: 50.67% | Val loss: 1.0017 | Val acc: 49.90% | LR: 0.000002
Epoch: 133 | Train loss: 0.9855 | Train acc: 51.28% | Val loss: 0.9996 | Val acc: 49.90% | LR: 0.000002
Epoch: 134 | Train loss: 0.9895 | Train acc: 50.85% | Val loss: 1.0512 | Val acc: 49.94% | LR: 0.000002
Epoch: 135 | Train loss: 0.9880 | Train acc: 51.02% | Val loss: 0.9999 | Val acc: 49.88% | LR: 0.000001
Epoch: 136 | Train loss: 0.9886 | Train acc: 50.93% | Val loss: 1.0316 | Val acc: 49.94% | LR: 0.000001
Epoch: 137 | Train loss: 0.9863 | Train acc: 51.11% | Val loss: 1.0069 | Val acc: 49.90% | LR: 0.000001
Epoch: 138 | Train loss: 0.9883 | Train acc: 50.85% | Val loss: 1.0027 | Val acc: 49.90% | LR: 0.000001
Epoch: 139 | Train loss: 0.9857 | Train acc: 51.12% | Val loss: 1.0011 | Val acc: 49.88% | LR: 0.000001
Epoch: 140 | Train loss: 0.9922 | Train acc: 50.76% | Val loss: 1.0073 | Val acc: 50.02% | LR: 0.000001
Epoch: 141 | Train loss: 0.9950 | Train acc: 50.31% | Val loss: 1.0124 | Val acc: 49.94% | LR: 0.000001
Epoch: 142 | Train loss: 0.9858 | Train acc: 51.11% | Val loss: 1.0497 | Val acc: 49.86% | LR: 0.000001
Epoch: 143 | Train loss: 0.9890 | Train acc: 50.94% | Val loss: 1.0033 | Val acc: 49.88% | LR: 0.000001
Epoch: 144 | Train loss: 0.9920 | Train acc: 50.67% | Val loss: 1.0116 | Val acc: 49.96% | LR: 0.000001
Epoch: 145 | Train loss: 0.9880 | Train acc: 51.19% | Val loss: 1.0019 | Val acc: 49.86% | LR: 0.000001
Epoch: 146 | Train loss: 0.9954 | Train acc: 50.49% | Val loss: 1.0086 | Val acc: 49.88% | LR: 0.000001
Epoch: 147 | Train loss: 0.9879 | Train acc: 50.84% | Val loss: 1.0027 | Val acc: 49.90% | LR: 0.000001
Epoch: 148 | Train loss: 0.9887 | Train acc: 50.94% | Val loss: 1.0025 | Val acc: 49.90% | LR: 0.000001
Epoch: 149 | Train loss: 0.9913 | Train acc: 50.67% | Val loss: 1.0012 | Val acc: 49.88% | LR: 0.000001

[I 2025-09-23 16:59:48,468] Trial 41 finished with value: 0.49882670640945437 and parameters: {'lr': 2.315504928833584e-05, 'hidden_size': 95, 'dropout': 0.14663996208505944, 'weight_decay': 9.255322398780462e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9997 | Train acc: 50.45% | Val loss: 0.9986 | Val acc: 52.37% | LR: 0.000035
Epoch: 001 | Train loss: 0.9992 | Train acc: 51.19% | Val loss: 0.9984 | Val acc: 52.41% | LR: 0.000035
Epoch: 002 | Train loss: 1.0002 | Train acc: 51.02% | Val loss: 1.0033 | Val acc: 52.15% | LR: 0.000035
Epoch: 003 | Train loss: 0.9995 | Train acc: 51.14% | Val loss: 1.0032 | Val acc: 52.32% | LR: 0.000035
Epoch: 004 | Train loss: 0.9999 | Train acc: 50.22% | Val loss: 0.9995 | Val acc: 53.09% | LR: 0.000035
Epoch: 005 | Train loss: 1.0009 | Train acc: 50.72% | Val loss: 1.0062 | Val acc: 52.34% | LR: 0.000035
Epoch: 006 | Train loss: 0.9980 | Train acc: 51.21% | Val loss: 0.9981 | Val acc: 53.00% | LR: 0.000035
Epoch: 007 | Train loss: 0.9983 | Train acc: 50.65% | Val loss: 1.0083 | Val acc: 52.92% | LR: 0.000034
Epoch: 008 | Train loss: 0.9972 | Train acc: 50.78% | Val loss: 1.0019 | Val acc: 52.72% | LR: 0.000034
Epoch: 009 | Train loss: 0.9979 | Train acc: 50.51% | Val loss: 1.0082 | Val acc: 52.90% | LR: 0.000034
Epoch: 010 | Train loss: 1.0053 | Train acc: 49.76% | Val loss: 0.9995 | Val acc: 52.63% | LR: 0.000034
Epoch: 011 | Train loss: 1.0013 | Train acc: 50.83% | Val loss: 1.0489 | Val acc: 52.32% | LR: 0.000034
Epoch: 012 | Train loss: 0.9986 | Train acc: 50.45% | Val loss: 0.9991 | Val acc: 52.78% | LR: 0.000034
Epoch: 013 | Train loss: 0.9978 | Train acc: 50.69% | Val loss: 0.9978 | Val acc: 52.77% | LR: 0.000034
Epoch: 014 | Train loss: 0.9987 | Train acc: 50.86% | Val loss: 0.9979 | Val acc: 53.00% | LR: 0.000034
Epoch: 015 | Train loss: 0.9989 | Train acc: 50.15% | Val loss: 1.0017 | Val acc: 53.18% | LR: 0.000034
Epoch: 016 | Train loss: 0.9972 | Train acc: 50.90% | Val loss: 0.9972 | Val acc: 53.12% | LR: 0.000034
Epoch: 017 | Train loss: 0.9977 | Train acc: 50.60% | Val loss: 0.9999 | Val acc: 53.11% | LR: 0.000034
Epoch: 018 | Train loss: 0.9954 | Train acc: 51.22% | Val loss: 0.9969 | Val acc: 53.23% | LR: 0.000033
Epoch: 019 | Train loss: 0.9967 | Train acc: 50.78% | Val loss: 0.9970 | Val acc: 53.27% | LR: 0.000033
Epoch: 020 | Train loss: 0.9993 | Train acc: 50.06% | Val loss: 0.9973 | Val acc: 53.14% | LR: 0.000033
Epoch: 021 | Train loss: 0.9972 | Train acc: 50.54% | Val loss: 0.9969 | Val acc: 53.20% | LR: 0.000033
Epoch: 022 | Train loss: 0.9944 | Train acc: 51.17% | Val loss: 0.9971 | Val acc: 53.16% | LR: 0.000033
Epoch: 023 | Train loss: 0.9963 | Train acc: 50.76% | Val loss: 0.9971 | Val acc: 53.20% | LR: 0.000033
Epoch: 024 | Train loss: 0.9951 | Train acc: 50.77% | Val loss: 0.9970 | Val acc: 53.31% | LR: 0.000032
Epoch: 025 | Train loss: 0.9973 | Train acc: 50.48% | Val loss: 0.9973 | Val acc: 53.09% | LR: 0.000032
Epoch: 026 | Train loss: 0.9943 | Train acc: 50.77% | Val loss: 0.9972 | Val acc: 53.11% | LR: 0.000032
Epoch: 027 | Train loss: 0.9949 | Train acc: 50.86% | Val loss: 0.9979 | Val acc: 52.91% | LR: 0.000032
Epoch: 028 | Train loss: 0.9945 | Train acc: 50.94% | Val loss: 0.9973 | Val acc: 52.90% | LR: 0.000032
Epoch: 029 | Train loss: 0.9937 | Train acc: 50.94% | Val loss: 0.9970 | Val acc: 52.82% | LR: 0.000031
Epoch: 030 | Train loss: 0.9957 | Train acc: 50.40% | Val loss: 0.9973 | Val acc: 52.76% | LR: 0.000031
Epoch: 031 | Train loss: 0.9952 | Train acc: 50.67% | Val loss: 0.9975 | Val acc: 52.61% | LR: 0.000031
Epoch: 032 | Train loss: 0.9923 | Train acc: 51.22% | Val loss: 0.9973 | Val acc: 52.66% | LR: 0.000031
Epoch: 033 | Train loss: 0.9932 | Train acc: 51.04% | Val loss: 0.9972 | Val acc: 52.68% | LR: 0.000031
Epoch: 034 | Train loss: 0.9942 | Train acc: 50.97% | Val loss: 0.9972 | Val acc: 52.36% | LR: 0.000030
Epoch: 035 | Train loss: 0.9950 | Train acc: 50.58% | Val loss: 0.9972 | Val acc: 52.38% | LR: 0.000030
Epoch: 036 | Train loss: 0.9957 | Train acc: 50.41% | Val loss: 0.9972 | Val acc: 52.38% | LR: 0.000030
Epoch: 037 | Train loss: 0.9920 | Train acc: 50.96% | Val loss: 0.9972 | Val acc: 52.26% | LR: 0.000030
Epoch: 038 | Train loss: 0.9950 | Train acc: 50.57% | Val loss: 0.9973 | Val acc: 52.34% | LR: 0.000029
Epoch: 039 | Train loss: 0.9913 | Train acc: 51.01% | Val loss: 0.9975 | Val acc: 52.22% | LR: 0.000029
Epoch: 040 | Train loss: 0.9941 | Train acc: 50.72% | Val loss: 0.9972 | Val acc: 52.14% | LR: 0.000029
Epoch: 041 | Train loss: 0.9959 | Train acc: 50.53% | Val loss: 0.9972 | Val acc: 52.18% | LR: 0.000029
Epoch: 042 | Train loss: 0.9957 | Train acc: 50.37% | Val loss: 0.9972 | Val acc: 52.12% | LR: 0.000028
Epoch: 043 | Train loss: 0.9982 | Train acc: 50.09% | Val loss: 0.9972 | Val acc: 52.14% | LR: 0.000028
Epoch: 044 | Train loss: 0.9965 | Train acc: 50.27% | Val loss: 0.9972 | Val acc: 52.38% | LR: 0.000028
Epoch: 045 | Train loss: 0.9951 | Train acc: 50.66% | Val loss: 0.9972 | Val acc: 52.45% | LR: 0.000027
Epoch: 046 | Train loss: 0.9981 | Train acc: 49.87% | Val loss: 0.9972 | Val acc: 52.53% | LR: 0.000027
Epoch: 047 | Train loss: 1.0004 | Train acc: 50.02% | Val loss: 0.9973 | Val acc: 52.42% | LR: 0.000027
Epoch: 048 | Train loss: 0.9954 | Train acc: 50.40% | Val loss: 0.9972 | Val acc: 52.37% | LR: 0.000027
Epoch: 049 | Train loss: 0.9912 | Train acc: 50.86% | Val loss: 0.9972 | Val acc: 52.59% | LR: 0.000026
Epoch: 050 | Train loss: 0.9939 | Train acc: 50.77% | Val loss: 0.9972 | Val acc: 52.53% | LR: 0.000026
Epoch: 051 | Train loss: 0.9912 | Train acc: 50.67% | Val loss: 0.9971 | Val acc: 52.45% | LR: 0.000026
Epoch: 052 | Train loss: 0.9951 | Train acc: 50.40% | Val loss: 0.9970 | Val acc: 52.51% | LR: 0.000025
Epoch: 053 | Train loss: 0.9893 | Train acc: 50.86% | Val loss: 0.9970 | Val acc: 52.59% | LR: 0.000025
Epoch: 054 | Train loss: 0.9988 | Train acc: 50.07% | Val loss: 0.9970 | Val acc: 52.55% | LR: 0.000025
Epoch: 055 | Train loss: 0.9930 | Train acc: 50.53% | Val loss: 0.9970 | Val acc: 52.55% | LR: 0.000024
Epoch: 056 | Train loss: 0.9885 | Train acc: 51.06% | Val loss: 0.9970 | Val acc: 52.51% | LR: 0.000024
Epoch: 057 | Train loss: 0.9918 | Train acc: 50.69% | Val loss: 0.9970 | Val acc: 52.49% | LR: 0.000024
Epoch: 058 | Train loss: 0.9861 | Train acc: 51.24% | Val loss: 0.9970 | Val acc: 52.51% | LR: 0.000023
Epoch: 059 | Train loss: 0.9888 | Train acc: 50.82% | Val loss: 0.9969 | Val acc: 52.55% | LR: 0.000023
Epoch: 060 | Train loss: 0.9955 | Train acc: 50.27% | Val loss: 0.9969 | Val acc: 52.63% | LR: 0.000023
Epoch: 061 | Train loss: 0.9936 | Train acc: 50.54% | Val loss: 0.9969 | Val acc: 52.61% | LR: 0.000022
Epoch: 062 | Train loss: 0.9907 | Train acc: 50.90% | Val loss: 0.9969 | Val acc: 52.67% | LR: 0.000022
Epoch: 063 | Train loss: 0.9894 | Train acc: 50.68% | Val loss: 0.9969 | Val acc: 52.73% | LR: 0.000022
Epoch: 064 | Train loss: 0.9967 | Train acc: 50.26% | Val loss: 0.9969 | Val acc: 52.79% | LR: 0.000021
Epoch: 065 | Train loss: 0.9902 | Train acc: 50.89% | Val loss: 0.9969 | Val acc: 52.83% | LR: 0.000021
Epoch: 066 | Train loss: 0.9872 | Train acc: 51.16% | Val loss: 0.9968 | Val acc: 52.75% | LR: 0.000021
Epoch: 067 | Train loss: 0.9892 | Train acc: 50.89% | Val loss: 0.9968 | Val acc: 52.69% | LR: 0.000020
Epoch: 068 | Train loss: 0.9917 | Train acc: 50.77% | Val loss: 0.9968 | Val acc: 52.74% | LR: 0.000020
Epoch: 069 | Train loss: 1.0000 | Train acc: 50.15% | Val loss: 0.9968 | Val acc: 52.62% | LR: 0.000020
Epoch: 070 | Train loss: 0.9918 | Train acc: 50.58% | Val loss: 0.9967 | Val acc: 52.74% | LR: 0.000019
Epoch: 071 | Train loss: 0.9957 | Train acc: 50.39% | Val loss: 0.9967 | Val acc: 52.76% | LR: 0.000019
Epoch: 072 | Train loss: 0.9898 | Train acc: 50.67% | Val loss: 0.9967 | Val acc: 52.86% | LR: 0.000019
Epoch: 073 | Train loss: 0.9808 | Train acc: 51.38% | Val loss: 0.9966 | Val acc: 52.82% | LR: 0.000018

[I 2025-09-23 17:00:45,880] Trial 42 finished with value: 0.5288308501243592 and parameters: {'lr': 3.4686445515385406e-05, 'hidden_size': 69, 'dropout': 0.1744969423445089, 'weight_decay': 0.00029407862282008226}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0017 | Train acc: 49.62% | Val loss: 1.0007 | Val acc: 48.88% | LR: 0.000013
Epoch: 001 | Train loss: 1.0023 | Train acc: 49.20% | Val loss: 1.0008 | Val acc: 48.86% | LR: 0.000013
Epoch: 002 | Train loss: 1.0007 | Train acc: 50.25% | Val loss: 1.0006 | Val acc: 48.94% | LR: 0.000013
Epoch: 003 | Train loss: 1.0018 | Train acc: 49.27% | Val loss: 1.0009 | Val acc: 48.86% | LR: 0.000013
Epoch: 004 | Train loss: 1.0021 | Train acc: 49.63% | Val loss: 1.0006 | Val acc: 48.98% | LR: 0.000013
Epoch: 005 | Train loss: 1.0011 | Train acc: 49.81% | Val loss: 1.0007 | Val acc: 48.95% | LR: 0.000013
Epoch: 006 | Train loss: 1.0010 | Train acc: 50.10% | Val loss: 1.0005 | Val acc: 48.87% | LR: 0.000013
Epoch: 007 | Train loss: 1.0012 | Train acc: 49.56% | Val loss: 1.0002 | Val acc: 48.88% | LR: 0.000013
Epoch: 008 | Train loss: 1.0018 | Train acc: 49.54% | Val loss: 1.0007 | Val acc: 48.85% | LR: 0.000013
Epoch: 009 | Train loss: 1.0016 | Train acc: 49.66% | Val loss: 1.0007 | Val acc: 48.77% | LR: 0.000013
Epoch: 010 | Train loss: 1.0010 | Train acc: 49.66% | Val loss: 1.0005 | Val acc: 48.82% | LR: 0.000013
Epoch: 011 | Train loss: 1.0011 | Train acc: 49.75% | Val loss: 1.0008 | Val acc: 48.78% | LR: 0.000013
Epoch: 012 | Train loss: 1.0010 | Train acc: 49.56% | Val loss: 1.0007 | Val acc: 48.78% | LR: 0.000013
Epoch: 013 | Train loss: 1.0016 | Train acc: 49.66% | Val loss: 1.0007 | Val acc: 48.72% | LR: 0.000013
Epoch: 014 | Train loss: 1.0011 | Train acc: 49.72% | Val loss: 1.0002 | Val acc: 48.68% | LR: 0.000013
Epoch: 015 | Train loss: 1.0005 | Train acc: 50.06% | Val loss: 1.0010 | Val acc: 48.52% | LR: 0.000013
Epoch: 016 | Train loss: 1.0007 | Train acc: 49.65% | Val loss: 1.0005 | Val acc: 48.58% | LR: 0.000013
Epoch: 017 | Train loss: 1.0013 | Train acc: 49.56% | Val loss: 1.0010 | Val acc: 48.60% | LR: 0.000012
Epoch: 018 | Train loss: 1.0007 | Train acc: 49.73% | Val loss: 1.0011 | Val acc: 48.53% | LR: 0.000012
Epoch: 019 | Train loss: 1.0008 | Train acc: 49.70% | Val loss: 1.0002 | Val acc: 48.63% | LR: 0.000012
Epoch: 020 | Train loss: 1.0009 | Train acc: 49.66% | Val loss: 1.0009 | Val acc: 48.61% | LR: 0.000012
Epoch: 021 | Train loss: 1.0007 | Train acc: 49.90% | Val loss: 1.0007 | Val acc: 48.47% | LR: 0.000012
Epoch: 022 | Train loss: 1.0004 | Train acc: 50.57% | Val loss: 1.0008 | Val acc: 48.49% | LR: 0.000012
Epoch: 023 | Train loss: 1.0007 | Train acc: 49.80% | Val loss: 1.0008 | Val acc: 48.41% | LR: 0.000012
Epoch: 024 | Train loss: 1.0003 | Train acc: 50.10% | Val loss: 1.0007 | Val acc: 48.57% | LR: 0.000012
Epoch: 025 | Train loss: 1.0009 | Train acc: 49.58% | Val loss: 1.0008 | Val acc: 48.45% | LR: 0.000012
Epoch: 026 | Train loss: 1.0005 | Train acc: 49.94% | Val loss: 1.0007 | Val acc: 48.49% | LR: 0.000012
Epoch: 027 | Train loss: 1.0009 | Train acc: 49.71% | Val loss: 1.0008 | Val acc: 48.54% | LR: 0.000012
Epoch: 028 | Train loss: 1.0166 | Train acc: 49.94% | Val loss: 1.0008 | Val acc: 48.59% | LR: 0.000012
Epoch: 029 | Train loss: 1.0005 | Train acc: 50.15% | Val loss: 1.0007 | Val acc: 48.57% | LR: 0.000012
Epoch: 030 | Train loss: 1.0010 | Train acc: 50.45% | Val loss: 1.0022 | Val acc: 48.39% | LR: 0.000012
Epoch: 031 | Train loss: 1.0005 | Train acc: 50.48% | Val loss: 1.0007 | Val acc: 48.47% | LR: 0.000012
Epoch: 032 | Train loss: 0.9997 | Train acc: 50.81% | Val loss: 1.0007 | Val acc: 48.53% | LR: 0.000012
Epoch: 033 | Train loss: 0.9998 | Train acc: 50.63% | Val loss: 1.0007 | Val acc: 48.49% | LR: 0.000011
Epoch: 034 | Train loss: 1.0000 | Train acc: 50.58% | Val loss: 1.0006 | Val acc: 48.47% | LR: 0.000011
Epoch: 035 | Train loss: 1.0009 | Train acc: 50.08% | Val loss: 1.0007 | Val acc: 48.45% | LR: 0.000011
Epoch: 036 | Train loss: 1.0001 | Train acc: 50.61% | Val loss: 1.0007 | Val acc: 48.43% | LR: 0.000011
Epoch: 037 | Train loss: 1.0004 | Train acc: 50.09% | Val loss: 1.0007 | Val acc: 48.53% | LR: 0.000011
Epoch: 038 | Train loss: 0.9992 | Train acc: 51.00% | Val loss: 1.0007 | Val acc: 48.57% | LR: 0.000011
Epoch: 039 | Train loss: 1.0009 | Train acc: 50.26% | Val loss: 1.0007 | Val acc: 48.59% | LR: 0.000011
Epoch: 040 | Train loss: 1.0110 | Train acc: 49.94% | Val loss: 1.0007 | Val acc: 48.75% | LR: 0.000011
Epoch: 041 | Train loss: 1.0486 | Train acc: 49.80% | Val loss: 1.0006 | Val acc: 48.75% | LR: 0.000011
Epoch: 042 | Train loss: 1.0060 | Train acc: 50.06% | Val loss: 1.0006 | Val acc: 48.76% | LR: 0.000011
Epoch: 043 | Train loss: 1.0006 | Train acc: 49.93% | Val loss: 1.0008 | Val acc: 48.63% | LR: 0.000011
Epoch: 044 | Train loss: 1.0126 | Train acc: 50.54% | Val loss: 1.0007 | Val acc: 48.61% | LR: 0.000010
Epoch: 045 | Train loss: 1.0002 | Train acc: 50.35% | Val loss: 1.0007 | Val acc: 48.55% | LR: 0.000010
Epoch: 046 | Train loss: 1.0006 | Train acc: 50.22% | Val loss: 1.0008 | Val acc: 48.46% | LR: 0.000010
Epoch: 047 | Train loss: 1.0005 | Train acc: 50.26% | Val loss: 1.0008 | Val acc: 48.44% | LR: 0.000010
Epoch: 048 | Train loss: 1.0004 | Train acc: 50.36% | Val loss: 1.0008 | Val acc: 48.47% | LR: 0.000010
Epoch: 049 | Train loss: 1.0002 | Train acc: 50.26% | Val loss: 1.0006 | Val acc: 48.42% | LR: 0.000010
Epoch: 050 | Train loss: 1.0005 | Train acc: 50.16% | Val loss: 1.0008 | Val acc: 48.48% | LR: 0.000010
Epoch: 051 | Train loss: 1.0005 | Train acc: 50.44% | Val loss: 1.0006 | Val acc: 48.48% | LR: 0.000010
Epoch: 052 | Train loss: 1.0007 | Train acc: 50.62% | Val loss: 1.0008 | Val acc: 48.50% | LR: 0.000010
Epoch: 053 | Train loss: 1.0000 | Train acc: 50.24% | Val loss: 1.0005 | Val acc: 48.52% | LR: 0.000009

[I 2025-09-23 17:01:31,753] Trial 43 finished with value: 0.4850300431251526 and parameters: {'lr': 1.2896929034065425e-05, 'hidden_size': 71, 'dropout': 0.20661435054162075, 'weight_decay': 0.0002936192689696658}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9996 | Train acc: 49.96% | Val loss: 0.9977 | Val acc: 53.91% | LR: 0.000031
Epoch: 001 | Train loss: 1.0002 | Train acc: 49.89% | Val loss: 1.0050 | Val acc: 53.85% | LR: 0.000031
Epoch: 002 | Train loss: 1.0004 | Train acc: 49.80% | Val loss: 0.9958 | Val acc: 53.73% | LR: 0.000031
Epoch: 003 | Train loss: 1.0110 | Train acc: 49.84% | Val loss: 0.9990 | Val acc: 53.62% | LR: 0.000031
Epoch: 004 | Train loss: 1.0010 | Train acc: 49.86% | Val loss: 0.9957 | Val acc: 53.79% | LR: 0.000030
Epoch: 005 | Train loss: 0.9998 | Train acc: 50.01% | Val loss: 0.9997 | Val acc: 53.62% | LR: 0.000030
Epoch: 006 | Train loss: 1.0009 | Train acc: 50.57% | Val loss: 0.9960 | Val acc: 53.55% | LR: 0.000030
Epoch: 007 | Train loss: 1.0006 | Train acc: 50.33% | Val loss: 0.9964 | Val acc: 53.60% | LR: 0.000030
Epoch: 008 | Train loss: 0.9991 | Train acc: 51.12% | Val loss: 0.9981 | Val acc: 53.47% | LR: 0.000030
Epoch: 009 | Train loss: 0.9992 | Train acc: 50.52% | Val loss: 0.9972 | Val acc: 53.37% | LR: 0.000030
Epoch: 010 | Train loss: 1.0058 | Train acc: 50.36% | Val loss: 0.9959 | Val acc: 53.53% | LR: 0.000030
Epoch: 011 | Train loss: 0.9992 | Train acc: 50.21% | Val loss: 0.9973 | Val acc: 53.37% | LR: 0.000030
Epoch: 012 | Train loss: 0.9989 | Train acc: 50.53% | Val loss: 0.9971 | Val acc: 52.95% | LR: 0.000030
Epoch: 013 | Train loss: 0.9986 | Train acc: 50.37% | Val loss: 0.9955 | Val acc: 53.40% | LR: 0.000030
Epoch: 014 | Train loss: 0.9985 | Train acc: 50.01% | Val loss: 0.9995 | Val acc: 53.54% | LR: 0.000030
Epoch: 015 | Train loss: 0.9989 | Train acc: 50.58% | Val loss: 1.0002 | Val acc: 53.20% | LR: 0.000030
Epoch: 016 | Train loss: 0.9998 | Train acc: 50.52% | Val loss: 0.9970 | Val acc: 53.50% | LR: 0.000030
Epoch: 017 | Train loss: 1.0000 | Train acc: 50.36% | Val loss: 0.9994 | Val acc: 53.70% | LR: 0.000030
Epoch: 018 | Train loss: 0.9976 | Train acc: 50.53% | Val loss: 0.9989 | Val acc: 53.66% | LR: 0.000029
Epoch: 019 | Train loss: 0.9984 | Train acc: 50.43% | Val loss: 0.9988 | Val acc: 53.78% | LR: 0.000029
Epoch: 020 | Train loss: 0.9994 | Train acc: 50.10% | Val loss: 0.9971 | Val acc: 53.77% | LR: 0.000029
Epoch: 021 | Train loss: 0.9983 | Train acc: 50.45% | Val loss: 0.9957 | Val acc: 53.64% | LR: 0.000029
Epoch: 022 | Train loss: 0.9990 | Train acc: 50.69% | Val loss: 0.9954 | Val acc: 53.75% | LR: 0.000029
Epoch: 023 | Train loss: 0.9977 | Train acc: 50.74% | Val loss: 1.0118 | Val acc: 54.01% | LR: 0.000029
Epoch: 024 | Train loss: 0.9970 | Train acc: 50.81% | Val loss: 0.9948 | Val acc: 54.24% | LR: 0.000029
Epoch: 025 | Train loss: 0.9977 | Train acc: 50.78% | Val loss: 0.9975 | Val acc: 53.88% | LR: 0.000028
Epoch: 026 | Train loss: 0.9980 | Train acc: 50.90% | Val loss: 0.9971 | Val acc: 53.96% | LR: 0.000028
Epoch: 027 | Train loss: 0.9983 | Train acc: 50.50% | Val loss: 1.0008 | Val acc: 53.92% | LR: 0.000028
Epoch: 028 | Train loss: 0.9975 | Train acc: 50.66% | Val loss: 0.9978 | Val acc: 53.91% | LR: 0.000028
Epoch: 029 | Train loss: 1.0061 | Train acc: 50.72% | Val loss: 1.0105 | Val acc: 53.64% | LR: 0.000028
Epoch: 030 | Train loss: 0.9976 | Train acc: 50.37% | Val loss: 0.9966 | Val acc: 54.06% | LR: 0.000028
Epoch: 031 | Train loss: 0.9980 | Train acc: 50.74% | Val loss: 0.9964 | Val acc: 54.04% | LR: 0.000027
Epoch: 032 | Train loss: 0.9950 | Train acc: 51.05% | Val loss: 0.9953 | Val acc: 53.99% | LR: 0.000027
Epoch: 033 | Train loss: 0.9979 | Train acc: 50.28% | Val loss: 0.9978 | Val acc: 53.66% | LR: 0.000027
Epoch: 034 | Train loss: 1.0059 | Train acc: 50.37% | Val loss: 0.9961 | Val acc: 53.74% | LR: 0.000027
Epoch: 035 | Train loss: 0.9986 | Train acc: 49.93% | Val loss: 0.9980 | Val acc: 53.80% | LR: 0.000027
Epoch: 036 | Train loss: 0.9973 | Train acc: 50.79% | Val loss: 1.0028 | Val acc: 53.69% | LR: 0.000026
Epoch: 037 | Train loss: 0.9981 | Train acc: 50.55% | Val loss: 0.9967 | Val acc: 53.95% | LR: 0.000026
Epoch: 038 | Train loss: 0.9970 | Train acc: 50.59% | Val loss: 1.0096 | Val acc: 54.09% | LR: 0.000026
Epoch: 039 | Train loss: 0.9975 | Train acc: 50.65% | Val loss: 0.9966 | Val acc: 54.33% | LR: 0.000026
Epoch: 040 | Train loss: 0.9957 | Train acc: 50.63% | Val loss: 1.0099 | Val acc: 54.21% | LR: 0.000025
Epoch: 041 | Train loss: 0.9976 | Train acc: 50.60% | Val loss: 1.0002 | Val acc: 54.39% | LR: 0.000025
Epoch: 042 | Train loss: 0.9982 | Train acc: 50.35% | Val loss: 0.9960 | Val acc: 54.01% | LR: 0.000025
Epoch: 043 | Train loss: 0.9974 | Train acc: 50.30% | Val loss: 0.9955 | Val acc: 54.08% | LR: 0.000025
Epoch: 044 | Train loss: 0.9978 | Train acc: 50.32% | Val loss: 1.0045 | Val acc: 53.82% | LR: 0.000024
Epoch: 045 | Train loss: 0.9956 | Train acc: 50.84% | Val loss: 1.0000 | Val acc: 53.75% | LR: 0.000024
Epoch: 046 | Train loss: 0.9962 | Train acc: 50.94% | Val loss: 0.9959 | Val acc: 54.00% | LR: 0.000024
Epoch: 047 | Train loss: 0.9945 | Train acc: 50.83% | Val loss: 0.9980 | Val acc: 54.29% | LR: 0.000024
Epoch: 048 | Train loss: 0.9963 | Train acc: 50.49% | Val loss: 0.9980 | Val acc: 53.85% | LR: 0.000023
Epoch: 049 | Train loss: 0.9968 | Train acc: 50.36% | Val loss: 0.9980 | Val acc: 53.96% | LR: 0.000023
Epoch: 050 | Train loss: 0.9985 | Train acc: 50.02% | Val loss: 0.9959 | Val acc: 54.03% | LR: 0.000023
Epoch: 051 | Train loss: 0.9955 | Train acc: 50.62% | Val loss: 0.9968 | Val acc: 53.94% | LR: 0.000023
Epoch: 052 | Train loss: 0.9948 | Train acc: 50.67% | Val loss: 0.9955 | Val acc: 53.78% | LR: 0.000022
Epoch: 053 | Train loss: 0.9977 | Train acc: 50.05% | Val loss: 1.0022 | Val acc: 53.89% | LR: 0.000022
Epoch: 054 | Train loss: 0.9932 | Train acc: 50.87% | Val loss: 1.0011 | Val acc: 53.97% | LR: 0.000022
Epoch: 055 | Train loss: 0.9949 | Train acc: 50.80% | Val loss: 0.9973 | Val acc: 53.89% | LR: 0.000022
Epoch: 056 | Train loss: 1.0000 | Train acc: 50.07% | Val loss: 0.9972 | Val acc: 53.97% | LR: 0.000021
Epoch: 057 | Train loss: 0.9944 | Train acc: 50.90% | Val loss: 0.9951 | Val acc: 54.13% | LR: 0.000021
Epoch: 058 | Train loss: 0.9955 | Train acc: 50.71% | Val loss: 1.0023 | Val acc: 53.91% | LR: 0.000021
Epoch: 059 | Train loss: 0.9948 | Train acc: 50.79% | Val loss: 0.9960 | Val acc: 53.79% | LR: 0.000020
Epoch: 060 | Train loss: 0.9938 | Train acc: 51.01% | Val loss: 0.9992 | Val acc: 53.77% | LR: 0.000020
Epoch: 061 | Train loss: 0.9957 | Train acc: 50.47% | Val loss: 1.0128 | Val acc: 54.03% | LR: 0.000020
Epoch: 062 | Train loss: 0.9970 | Train acc: 50.36% | Val loss: 1.0025 | Val acc: 53.93% | LR: 0.000019
Epoch: 063 | Train loss: 0.9954 | Train acc: 50.60% | Val loss: 0.9961 | Val acc: 53.80% | LR: 0.000019
Epoch: 064 | Train loss: 0.9948 | Train acc: 50.78% | Val loss: 0.9958 | Val acc: 53.80% | LR: 0.000019
Epoch: 065 | Train loss: 0.9941 | Train acc: 50.66% | Val loss: 0.9986 | Val acc: 53.75% | LR: 0.000019
Epoch: 066 | Train loss: 0.9896 | Train acc: 51.55% | Val loss: 0.9971 | Val acc: 53.74% | LR: 0.000018
Epoch: 067 | Train loss: 0.9935 | Train acc: 50.76% | Val loss: 0.9970 | Val acc: 53.86% | LR: 0.000018
Epoch: 068 | Train loss: 0.9949 | Train acc: 50.58% | Val loss: 1.0268 | Val acc: 53.71% | LR: 0.000018
Epoch: 069 | Train loss: 0.9947 | Train acc: 50.58% | Val loss: 0.9983 | Val acc: 53.74% | LR: 0.000017
Epoch: 070 | Train loss: 0.9965 | Train acc: 50.56% | Val loss: 0.9962 | Val acc: 53.84% | LR: 0.000017
Epoch: 071 | Train loss: 0.9940 | Train acc: 50.79% | Val loss: 1.0035 | Val acc: 53.58% | LR: 0.000017
Epoch: 072 | Train loss: 0.9917 | Train acc: 50.99% | Val loss: 0.9956 | Val acc: 53.88% | LR: 0.000016
Epoch: 073 | Train loss: 0.9915 | Train acc: 50.99% | Val loss: 0.9972 | Val acc: 53.79% | LR: 0.000016
Epoch: 074 | Train loss: 0.9929 | Train acc: 50.89% | Val loss: 0.9961 | Val acc: 53.83% | LR: 0.000016
Epoch: 075 | Train loss: 0.9931 | Train acc: 51.05% | Val loss: 0.9946 | Val acc: 53.94% | LR: 0.000015
Epoch: 076 | Train loss: 0.9957 | Train acc: 50.63% | Val loss: 0.9952 | Val acc: 53.87% | LR: 0.000015
Epoch: 077 | Train loss: 0.9929 | Train acc: 50.73% | Val loss: 0.9952 | Val acc: 53.83% | LR: 0.000015
Epoch: 078 | Train loss: 0.9948 | Train acc: 50.52% | Val loss: 1.0316 | Val acc: 53.75% | LR: 0.000015
Epoch: 079 | Train loss: 0.9918 | Train acc: 51.03% | Val loss: 0.9965 | Val acc: 53.78% | LR: 0.000014
Epoch: 080 | Train loss: 0.9936 | Train acc: 50.79% | Val loss: 0.9953 | Val acc: 53.88% | LR: 0.000014
Epoch: 081 | Train loss: 0.9915 | Train acc: 50.85% | Val loss: 0.9965 | Val acc: 53.95% | LR: 0.000014
Epoch: 082 | Train loss: 0.9915 | Train acc: 50.93% | Val loss: 0.9965 | Val acc: 53.62% | LR: 0.000013
Epoch: 083 | Train loss: 0.9982 | Train acc: 50.16% | Val loss: 0.9943 | Val acc: 53.96% | LR: 0.000013
Epoch: 084 | Train loss: 0.9906 | Train acc: 51.11% | Val loss: 0.9977 | Val acc: 53.70% | LR: 0.000013
Epoch: 085 | Train loss: 0.9900 | Train acc: 50.96% | Val loss: 0.9978 | Val acc: 53.64% | LR: 0.000012
Epoch: 086 | Train loss: 0.9884 | Train acc: 51.10% | Val loss: 0.9969 | Val acc: 53.76% | LR: 0.000012
Epoch: 087 | Train loss: 1.0005 | Train acc: 49.87% | Val loss: 0.9961 | Val acc: 53.87% | LR: 0.000012
Epoch: 088 | Train loss: 0.9933 | Train acc: 50.68% | Val loss: 1.0017 | Val acc: 53.75% | LR: 0.000012
Epoch: 089 | Train loss: 0.9935 | Train acc: 50.57% | Val loss: 0.9955 | Val acc: 53.87% | LR: 0.000011
Epoch: 090 | Train loss: 0.9938 | Train acc: 50.43% | Val loss: 0.9955 | Val acc: 53.89% | LR: 0.000011

[I 2025-09-23 17:02:54,117] Trial 44 finished with value: 0.5371394634246827 and parameters: {'lr': 3.055517979389346e-05, 'hidden_size': 98, 'dropout': 0.3819323511402064, 'weight_decay': 3.5398043401780876e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0007 | Train acc: 49.90% | Val loss: 1.0039 | Val acc: 46.07% | LR: 0.000051
Epoch: 001 | Train loss: 1.0009 | Train acc: 49.80% | Val loss: 1.0038 | Val acc: 46.03% | LR: 0.000051
Epoch: 002 | Train loss: 1.0013 | Train acc: 49.52% | Val loss: 1.0039 | Val acc: 46.15% | LR: 0.000050
Epoch: 003 | Train loss: 1.0013 | Train acc: 49.58% | Val loss: 1.0029 | Val acc: 46.25% | LR: 0.000050
Epoch: 004 | Train loss: 1.0015 | Train acc: 49.35% | Val loss: 1.0030 | Val acc: 46.43% | LR: 0.000050
Epoch: 005 | Train loss: 1.0011 | Train acc: 49.08% | Val loss: 1.0029 | Val acc: 46.56% | LR: 0.000050
Epoch: 006 | Train loss: 0.9995 | Train acc: 49.92% | Val loss: 1.0027 | Val acc: 46.57% | LR: 0.000050
Epoch: 007 | Train loss: 0.9989 | Train acc: 50.31% | Val loss: 1.0025 | Val acc: 46.57% | LR: 0.000050
Epoch: 008 | Train loss: 1.0262 | Train acc: 51.00% | Val loss: 1.0026 | Val acc: 46.55% | LR: 0.000050
Epoch: 009 | Train loss: 1.0157 | Train acc: 50.60% | Val loss: 1.0026 | Val acc: 46.53% | LR: 0.000050
Epoch: 010 | Train loss: 0.9989 | Train acc: 50.62% | Val loss: 1.0027 | Val acc: 46.67% | LR: 0.000050
Epoch: 011 | Train loss: 0.9986 | Train acc: 50.83% | Val loss: 1.0022 | Val acc: 46.69% | LR: 0.000050
Epoch: 012 | Train loss: 0.9975 | Train acc: 50.98% | Val loss: 1.0020 | Val acc: 46.76% | LR: 0.000050
Epoch: 013 | Train loss: 1.0007 | Train acc: 50.16% | Val loss: 1.0020 | Val acc: 47.02% | LR: 0.000049
Epoch: 014 | Train loss: 0.9970 | Train acc: 51.08% | Val loss: 1.0021 | Val acc: 47.13% | LR: 0.000049
Epoch: 015 | Train loss: 0.9967 | Train acc: 51.12% | Val loss: 1.0016 | Val acc: 47.57% | LR: 0.000049
Epoch: 016 | Train loss: 0.9990 | Train acc: 50.53% | Val loss: 1.0017 | Val acc: 47.69% | LR: 0.000049
Epoch: 017 | Train loss: 0.9950 | Train acc: 51.36% | Val loss: 1.0015 | Val acc: 47.84% | LR: 0.000049
Epoch: 018 | Train loss: 0.9982 | Train acc: 50.63% | Val loss: 1.0013 | Val acc: 48.14% | LR: 0.000049
Epoch: 019 | Train loss: 0.9971 | Train acc: 50.82% | Val loss: 1.0009 | Val acc: 48.38% | LR: 0.000048
Epoch: 020 | Train loss: 0.9946 | Train acc: 51.20% | Val loss: 1.0010 | Val acc: 48.34% | LR: 0.000048
Epoch: 021 | Train loss: 0.9995 | Train acc: 50.31% | Val loss: 1.0003 | Val acc: 48.54% | LR: 0.000048
Epoch: 022 | Train loss: 0.9955 | Train acc: 50.90% | Val loss: 0.9998 | Val acc: 48.96% | LR: 0.000048
Epoch: 023 | Train loss: 0.9973 | Train acc: 50.68% | Val loss: 0.9997 | Val acc: 49.12% | LR: 0.000047
Epoch: 024 | Train loss: 0.9976 | Train acc: 50.75% | Val loss: 0.9995 | Val acc: 49.25% | LR: 0.000047
Epoch: 025 | Train loss: 0.9969 | Train acc: 50.77% | Val loss: 0.9997 | Val acc: 49.48% | LR: 0.000047
Epoch: 026 | Train loss: 0.9960 | Train acc: 51.11% | Val loss: 0.9990 | Val acc: 49.41% | LR: 0.000047
Epoch: 027 | Train loss: 0.9969 | Train acc: 50.66% | Val loss: 0.9985 | Val acc: 49.51% | LR: 0.000046
Epoch: 028 | Train loss: 0.9956 | Train acc: 50.82% | Val loss: 0.9979 | Val acc: 50.17% | LR: 0.000046
Epoch: 029 | Train loss: 0.9946 | Train acc: 51.12% | Val loss: 0.9975 | Val acc: 50.41% | LR: 0.000046
Epoch: 030 | Train loss: 0.9919 | Train acc: 51.49% | Val loss: 0.9966 | Val acc: 50.64% | LR: 0.000046
Epoch: 031 | Train loss: 0.9926 | Train acc: 51.22% | Val loss: 0.9961 | Val acc: 50.79% | LR: 0.000045
Epoch: 032 | Train loss: 0.9950 | Train acc: 50.70% | Val loss: 0.9951 | Val acc: 51.19% | LR: 0.000045
Epoch: 033 | Train loss: 0.9946 | Train acc: 50.87% | Val loss: 0.9948 | Val acc: 51.23% | LR: 0.000045
Epoch: 034 | Train loss: 0.9929 | Train acc: 50.96% | Val loss: 0.9943 | Val acc: 51.27% | LR: 0.000044
Epoch: 035 | Train loss: 0.9922 | Train acc: 51.04% | Val loss: 0.9934 | Val acc: 51.49% | LR: 0.000044
Epoch: 036 | Train loss: 0.9891 | Train acc: 51.29% | Val loss: 0.9926 | Val acc: 51.50% | LR: 0.000043
Epoch: 037 | Train loss: 0.9901 | Train acc: 50.94% | Val loss: 0.9915 | Val acc: 51.71% | LR: 0.000043
Epoch: 038 | Train loss: 0.9939 | Train acc: 50.68% | Val loss: 0.9906 | Val acc: 51.72% | LR: 0.000043
Epoch: 039 | Train loss: 0.9986 | Train acc: 50.07% | Val loss: 0.9894 | Val acc: 51.76% | LR: 0.000042
Epoch: 040 | Train loss: 0.9865 | Train acc: 51.30% | Val loss: 0.9880 | Val acc: 51.82% | LR: 0.000042
Epoch: 041 | Train loss: 0.9869 | Train acc: 51.15% | Val loss: 0.9869 | Val acc: 52.13% | LR: 0.000042
Epoch: 042 | Train loss: 0.9885 | Train acc: 50.89% | Val loss: 0.9849 | Val acc: 52.31% | LR: 0.000041
Epoch: 043 | Train loss: 0.9864 | Train acc: 51.10% | Val loss: 0.9829 | Val acc: 52.35% | LR: 0.000041
Epoch: 044 | Train loss: 0.9882 | Train acc: 50.75% | Val loss: 0.9800 | Val acc: 52.67% | LR: 0.000040
Epoch: 045 | Train loss: 0.9883 | Train acc: 50.92% | Val loss: 0.9781 | Val acc: 52.67% | LR: 0.000040
Epoch: 046 | Train loss: 0.9834 | Train acc: 51.38% | Val loss: 0.9757 | Val acc: 52.87% | LR: 0.000039
Epoch: 047 | Train loss: 0.9864 | Train acc: 51.25% | Val loss: 0.9753 | Val acc: 52.85% | LR: 0.000039
Epoch: 048 | Train loss: 0.9859 | Train acc: 51.26% | Val loss: 0.9756 | Val acc: 52.45% | LR: 0.000039
Epoch: 049 | Train loss: 0.9834 | Train acc: 51.35% | Val loss: 0.9754 | Val acc: 52.37% | LR: 0.000038
Epoch: 050 | Train loss: 0.9909 | Train acc: 50.66% | Val loss: 0.9756 | Val acc: 52.31% | LR: 0.000038
Epoch: 051 | Train loss: 0.9883 | Train acc: 50.66% | Val loss: 0.9759 | Val acc: 52.27% | LR: 0.000037
Epoch: 052 | Train loss: 0.9826 | Train acc: 51.38% | Val loss: 0.9757 | Val acc: 52.31% | LR: 0.000037
Epoch: 053 | Train loss: 0.9858 | Train acc: 51.18% | Val loss: 0.9757 | Val acc: 52.26% | LR: 0.000036
Epoch: 054 | Train loss: 0.9802 | Train acc: 51.52% | Val loss: 0.9763 | Val acc: 52.10% | LR: 0.000036
Epoch: 055 | Train loss: 0.9837 | Train acc: 51.25% | Val loss: 0.9773 | Val acc: 51.78% | LR: 0.000035
Epoch: 056 | Train loss: 0.9831 | Train acc: 50.93% | Val loss: 0.9780 | Val acc: 51.61% | LR: 0.000035
Epoch: 057 | Train loss: 0.9827 | Train acc: 51.21% | Val loss: 0.9777 | Val acc: 51.57% | LR: 0.000034
Epoch: 058 | Train loss: 0.9793 | Train acc: 51.46% | Val loss: 0.9779 | Val acc: 51.47% | LR: 0.000034
Epoch: 059 | Train loss: 0.9833 | Train acc: 51.01% | Val loss: 0.9784 | Val acc: 51.37% | LR: 0.000033
Epoch: 060 | Train loss: 0.9784 | Train acc: 51.38% | Val loss: 0.9790 | Val acc: 51.33% | LR: 0.000033
Epoch: 061 | Train loss: 0.9879 | Train acc: 50.52% | Val loss: 0.9795 | Val acc: 51.37% | LR: 0.000032
Epoch: 062 | Train loss: 0.9805 | Train acc: 51.31% | Val loss: 0.9795 | Val acc: 51.37% | LR: 0.000032
Epoch: 063 | Train loss: 0.9829 | Train acc: 51.24% | Val loss: 0.9803 | Val acc: 51.18% | LR: 0.000031
Epoch: 064 | Train loss: 0.9931 | Train acc: 50.16% | Val loss: 0.9812 | Val acc: 51.28% | LR: 0.000031
Epoch: 065 | Train loss: 0.9843 | Train acc: 50.87% | Val loss: 0.9812 | Val acc: 51.28% | LR: 0.000030
Epoch: 066 | Train loss: 0.9805 | Train acc: 51.23% | Val loss: 0.9810 | Val acc: 51.30% | LR: 0.000030
Epoch: 067 | Train loss: 0.9833 | Train acc: 51.05% | Val loss: 0.9817 | Val acc: 51.35% | LR: 0.000029
Epoch: 068 | Train loss: 0.9803 | Train acc: 51.24% | Val loss: 0.9820 | Val acc: 51.35% | LR: 0.000029
Epoch: 069 | Train loss: 0.9813 | Train acc: 51.15% | Val loss: 0.9823 | Val acc: 51.31% | LR: 0.000028
Epoch: 070 | Train loss: 0.9818 | Train acc: 51.15% | Val loss: 0.9827 | Val acc: 51.31% | LR: 0.000028
Epoch: 071 | Train loss: 0.9856 | Train acc: 51.16% | Val loss: 0.9831 | Val acc: 51.27% | LR: 0.000027
Epoch: 072 | Train loss: 0.9819 | Train acc: 51.07% | Val loss: 0.9838 | Val acc: 51.16% | LR: 0.000027
Epoch: 073 | Train loss: 0.9772 | Train acc: 51.34% | Val loss: 0.9837 | Val acc: 51.18% | LR: 0.000026
Epoch: 074 | Train loss: 0.9869 | Train acc: 50.70% | Val loss: 0.9840 | Val acc: 50.92% | LR: 0.000026
Epoch: 075 | Train loss: 0.9852 | Train acc: 50.96% | Val loss: 0.9835 | Val acc: 51.20% | LR: 0.000025
Epoch: 076 | Train loss: 0.9890 | Train acc: 50.61% | Val loss: 0.9839 | Val acc: 50.98% | LR: 0.000025
Epoch: 077 | Train loss: 0.9912 | Train acc: 50.54% | Val loss: 0.9842 | Val acc: 50.90% | LR: 0.000024
Epoch: 078 | Train loss: 0.9855 | Train acc: 50.81% | Val loss: 0.9841 | Val acc: 50.94% | LR: 0.000024
Epoch: 079 | Train loss: 0.9790 | Train acc: 51.42% | Val loss: 0.9836 | Val acc: 50.98% | LR: 0.000023
Epoch: 080 | Train loss: 0.9845 | Train acc: 50.89% | Val loss: 0.9836 | Val acc: 50.98% | LR: 0.000023
Epoch: 081 | Train loss: 0.9884 | Train acc: 50.62% | Val loss: 0.9839 | Val acc: 50.98% | LR: 0.000022
Epoch: 082 | Train loss: 0.9816 | Train acc: 51.25% | Val loss: 0.9838 | Val acc: 51.04% | LR: 0.000022
Epoch: 083 | Train loss: 0.9871 | Train acc: 50.78% | Val loss: 0.9837 | Val acc: 51.00% | LR: 0.000021
Epoch: 084 | Train loss: 0.9857 | Train acc: 50.80% | Val loss: 0.9837 | Val acc: 51.00% | LR: 0.000021
Epoch: 085 | Train loss: 0.9894 | Train acc: 50.61% | Val loss: 0.9839 | Val acc: 50.98% | LR: 0.000020
Epoch: 086 | Train loss: 0.9827 | Train acc: 51.05% | Val loss: 0.9839 | Val acc: 51.02% | LR: 0.000020
Epoch: 087 | Train loss: 0.9784 | Train acc: 51.49% | Val loss: 0.9843 | Val acc: 50.98% | LR: 0.000019
Epoch: 088 | Train loss: 0.9866 | Train acc: 50.70% | Val loss: 0.9845 | Val acc: 50.96% | LR: 0.000019
Epoch: 089 | Train loss: 0.9844 | Train acc: 50.86% | Val loss: 0.9848 | Val acc: 51.00% | LR: 0.000018
Epoch: 090 | Train loss: 0.9763 | Train acc: 51.41% | Val loss: 0.9850 | Val acc: 51.06% | LR: 0.000018
Epoch: 091 | Train loss: 0.9825 | Train acc: 50.87% | Val loss: 0.9850 | Val acc: 51.00% | LR: 0.000017
Epoch: 092 | Train loss: 0.9861 | Train acc: 50.70% | Val loss: 0.9851 | Val acc: 51.00% | LR: 0.000017
Epoch: 093 | Train loss: 0.9832 | Train acc: 50.79% | Val loss: 0.9851 | Val acc: 51.00% | LR: 0.000016
Epoch: 094 | Train loss: 0.9853 | Train acc: 50.70% | Val loss: 0.9852 | Val acc: 51.04% | LR: 0.000016
Epoch: 095 | Train loss: 0.9803 | Train acc: 51.15% | Val loss: 0.9851 | Val acc: 51.00% | LR: 0.000015

[I 2025-09-23 17:04:24,692] Trial 45 finished with value: 0.5095879971981049 and parameters: {'lr': 5.0541939429187655e-05, 'hidden_size': 105, 'dropout': 0.41575644281244983, 'weight_decay': 3.127059898439838e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9972 | Train acc: 50.30% | Val loss: 0.9983 | Val acc: 52.96% | LR: 0.000015
Epoch: 001 | Train loss: 0.9980 | Train acc: 50.13% | Val loss: 1.0023 | Val acc: 52.92% | LR: 0.000015
Epoch: 002 | Train loss: 0.9970 | Train acc: 50.28% | Val loss: 0.9982 | Val acc: 53.00% | LR: 0.000015
Epoch: 003 | Train loss: 0.9979 | Train acc: 50.26% | Val loss: 0.9980 | Val acc: 53.11% | LR: 0.000015
Epoch: 004 | Train loss: 0.9945 | Train acc: 50.81% | Val loss: 0.9980 | Val acc: 53.20% | LR: 0.000015
Epoch: 005 | Train loss: 0.9977 | Train acc: 50.23% | Val loss: 0.9981 | Val acc: 53.02% | LR: 0.000015
Epoch: 006 | Train loss: 0.9948 | Train acc: 50.71% | Val loss: 0.9979 | Val acc: 53.21% | LR: 0.000015
Epoch: 007 | Train loss: 0.9935 | Train acc: 50.83% | Val loss: 0.9979 | Val acc: 53.14% | LR: 0.000015
Epoch: 008 | Train loss: 0.9960 | Train acc: 50.74% | Val loss: 0.9993 | Val acc: 53.41% | LR: 0.000015
Epoch: 009 | Train loss: 0.9948 | Train acc: 50.74% | Val loss: 0.9976 | Val acc: 53.35% | LR: 0.000015
Epoch: 010 | Train loss: 0.9943 | Train acc: 50.83% | Val loss: 0.9974 | Val acc: 53.07% | LR: 0.000015
Epoch: 011 | Train loss: 0.9959 | Train acc: 50.79% | Val loss: 0.9973 | Val acc: 53.12% | LR: 0.000015
Epoch: 012 | Train loss: 0.9984 | Train acc: 50.67% | Val loss: 0.9970 | Val acc: 52.91% | LR: 0.000015
Epoch: 013 | Train loss: 0.9972 | Train acc: 50.61% | Val loss: 0.9965 | Val acc: 53.15% | LR: 0.000015
Epoch: 014 | Train loss: 0.9952 | Train acc: 50.82% | Val loss: 0.9964 | Val acc: 53.12% | LR: 0.000015
Epoch: 015 | Train loss: 0.9975 | Train acc: 50.53% | Val loss: 0.9964 | Val acc: 52.84% | LR: 0.000015
Epoch: 016 | Train loss: 0.9909 | Train acc: 51.35% | Val loss: 0.9960 | Val acc: 53.06% | LR: 0.000015
Epoch: 017 | Train loss: 0.9979 | Train acc: 50.42% | Val loss: 0.9960 | Val acc: 53.10% | LR: 0.000015
Epoch: 018 | Train loss: 0.9891 | Train acc: 51.49% | Val loss: 0.9957 | Val acc: 52.99% | LR: 0.000014
Epoch: 019 | Train loss: 0.9961 | Train acc: 50.75% | Val loss: 0.9955 | Val acc: 52.86% | LR: 0.000014
Epoch: 020 | Train loss: 0.9936 | Train acc: 50.88% | Val loss: 0.9949 | Val acc: 53.24% | LR: 0.000014
Epoch: 021 | Train loss: 0.9934 | Train acc: 50.88% | Val loss: 0.9945 | Val acc: 53.44% | LR: 0.000014
Epoch: 022 | Train loss: 0.9940 | Train acc: 50.81% | Val loss: 0.9946 | Val acc: 53.09% | LR: 0.000014
Epoch: 023 | Train loss: 0.9948 | Train acc: 50.80% | Val loss: 0.9949 | Val acc: 52.79% | LR: 0.000014
Epoch: 024 | Train loss: 0.9932 | Train acc: 50.89% | Val loss: 0.9947 | Val acc: 52.85% | LR: 0.000014
Epoch: 025 | Train loss: 0.9912 | Train acc: 51.25% | Val loss: 0.9946 | Val acc: 52.97% | LR: 0.000014
Epoch: 026 | Train loss: 0.9952 | Train acc: 50.90% | Val loss: 0.9944 | Val acc: 52.93% | LR: 0.000014
Epoch: 027 | Train loss: 0.9959 | Train acc: 50.80% | Val loss: 0.9943 | Val acc: 52.89% | LR: 0.000014
Epoch: 028 | Train loss: 0.9958 | Train acc: 50.63% | Val loss: 0.9942 | Val acc: 52.93% | LR: 0.000014
Epoch: 029 | Train loss: 0.9906 | Train acc: 51.18% | Val loss: 0.9942 | Val acc: 52.83% | LR: 0.000014
Epoch: 030 | Train loss: 0.9983 | Train acc: 50.56% | Val loss: 0.9940 | Val acc: 52.93% | LR: 0.000014
Epoch: 031 | Train loss: 0.9944 | Train acc: 50.73% | Val loss: 0.9938 | Val acc: 52.93% | LR: 0.000014
Epoch: 032 | Train loss: 0.9930 | Train acc: 50.89% | Val loss: 0.9936 | Val acc: 52.89% | LR: 0.000013
Epoch: 033 | Train loss: 0.9926 | Train acc: 50.92% | Val loss: 0.9933 | Val acc: 52.87% | LR: 0.000013
Epoch: 034 | Train loss: 0.9905 | Train acc: 51.10% | Val loss: 0.9936 | Val acc: 52.86% | LR: 0.000013
Epoch: 035 | Train loss: 0.9897 | Train acc: 51.11% | Val loss: 0.9936 | Val acc: 52.72% | LR: 0.000013
Epoch: 036 | Train loss: 0.9913 | Train acc: 51.13% | Val loss: 1.0281 | Val acc: 52.78% | LR: 0.000013
Epoch: 037 | Train loss: 0.9896 | Train acc: 51.29% | Val loss: 0.9932 | Val acc: 52.86% | LR: 0.000013
Epoch: 038 | Train loss: 0.9935 | Train acc: 50.91% | Val loss: 0.9930 | Val acc: 52.88% | LR: 0.000013
Epoch: 039 | Train loss: 0.9910 | Train acc: 50.92% | Val loss: 0.9929 | Val acc: 52.92% | LR: 0.000013
Epoch: 040 | Train loss: 0.9928 | Train acc: 50.90% | Val loss: 0.9924 | Val acc: 52.98% | LR: 0.000013
Epoch: 041 | Train loss: 0.9894 | Train acc: 50.99% | Val loss: 1.0341 | Val acc: 53.41% | LR: 0.000012
Epoch: 042 | Train loss: 1.0013 | Train acc: 50.92% | Val loss: 1.0356 | Val acc: 52.79% | LR: 0.000012
Epoch: 043 | Train loss: 0.9937 | Train acc: 51.00% | Val loss: 1.3609 | Val acc: 52.53% | LR: 0.000012
Epoch: 044 | Train loss: 0.9926 | Train acc: 50.95% | Val loss: 1.0145 | Val acc: 52.13% | LR: 0.000012
Epoch: 045 | Train loss: 0.9928 | Train acc: 50.80% | Val loss: 0.9990 | Val acc: 52.54% | LR: 0.000012
Epoch: 046 | Train loss: 0.9962 | Train acc: 50.83% | Val loss: 0.9920 | Val acc: 52.66% | LR: 0.000012
Epoch: 047 | Train loss: 0.9980 | Train acc: 50.51% | Val loss: 0.9983 | Val acc: 52.66% | LR: 0.000012
Epoch: 048 | Train loss: 0.9889 | Train acc: 50.96% | Val loss: 1.0698 | Val acc: 52.53% | LR: 0.000012
Epoch: 049 | Train loss: 0.9917 | Train acc: 51.36% | Val loss: 1.0099 | Val acc: 52.23% | LR: 0.000012
Epoch: 050 | Train loss: 0.9941 | Train acc: 50.88% | Val loss: 0.9959 | Val acc: 51.94% | LR: 0.000011
Epoch: 051 | Train loss: 0.9971 | Train acc: 50.51% | Val loss: 1.0366 | Val acc: 51.96% | LR: 0.000011
Epoch: 052 | Train loss: 0.9869 | Train acc: 51.28% | Val loss: 1.0113 | Val acc: 52.03% | LR: 0.000011
Epoch: 053 | Train loss: 0.9963 | Train acc: 50.77% | Val loss: 1.1136 | Val acc: 51.37% | LR: 0.000011
Epoch: 054 | Train loss: 0.9961 | Train acc: 50.51% | Val loss: 1.0235 | Val acc: 50.97% | LR: 0.000011
Epoch: 055 | Train loss: 0.9977 | Train acc: 50.42% | Val loss: 1.0081 | Val acc: 51.36% | LR: 0.000011
Epoch: 056 | Train loss: 0.9944 | Train acc: 50.92% | Val loss: 1.0128 | Val acc: 51.96% | LR: 0.000011
Epoch: 057 | Train loss: 0.9969 | Train acc: 50.76% | Val loss: 1.0133 | Val acc: 51.93% | LR: 0.000010
Epoch: 058 | Train loss: 0.9966 | Train acc: 50.64% | Val loss: 1.0062 | Val acc: 52.25% | LR: 0.000010
Epoch: 059 | Train loss: 0.9904 | Train acc: 51.11% | Val loss: 0.9983 | Val acc: 52.27% | LR: 0.000010
Epoch: 060 | Train loss: 0.9934 | Train acc: 50.87% | Val loss: 0.9972 | Val acc: 52.15% | LR: 0.000010
Epoch: 061 | Train loss: 0.9949 | Train acc: 50.76% | Val loss: 0.9970 | Val acc: 52.14% | LR: 0.000010
Epoch: 062 | Train loss: 0.9929 | Train acc: 50.81% | Val loss: 0.9944 | Val acc: 52.34% | LR: 0.000010
Epoch: 063 | Train loss: 0.9843 | Train acc: 51.53% | Val loss: 0.9944 | Val acc: 52.34% | LR: 0.000010
Epoch: 064 | Train loss: 0.9853 | Train acc: 51.26% | Val loss: 0.9944 | Val acc: 52.32% | LR: 0.000009
Epoch: 065 | Train loss: 0.9866 | Train acc: 51.26% | Val loss: 0.9944 | Val acc: 52.38% | LR: 0.000009
Epoch: 066 | Train loss: 0.9853 | Train acc: 51.35% | Val loss: 0.9944 | Val acc: 52.32% | LR: 0.000009
Epoch: 067 | Train loss: 0.9933 | Train acc: 50.91% | Val loss: 0.9944 | Val acc: 52.30% | LR: 0.000009
Epoch: 068 | Train loss: 0.9912 | Train acc: 50.91% | Val loss: 0.9943 | Val acc: 52.30% | LR: 0.000009
Epoch: 069 | Train loss: 0.9874 | Train acc: 51.09% | Val loss: 0.9944 | Val acc: 52.22% | LR: 0.000009
Epoch: 070 | Train loss: 0.9834 | Train acc: 51.44% | Val loss: 0.9943 | Val acc: 52.20% | LR: 0.000009

[I 2025-09-23 17:05:27,372] Trial 46 finished with value: 0.5221934795379639 and parameters: {'lr': 1.5019390070329984e-05, 'hidden_size': 122, 'dropout': 0.38208523236989855, 'weight_decay': 3.8676573743414134e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0049 | Train acc: 49.81% | Val loss: 1.0047 | Val acc: 46.07% | LR: 0.000023
Epoch: 001 | Train loss: 1.0036 | Train acc: 49.92% | Val loss: 1.0137 | Val acc: 45.99% | LR: 0.000023
Epoch: 002 | Train loss: 0.9990 | Train acc: 50.36% | Val loss: 1.0094 | Val acc: 45.86% | LR: 0.000023
Epoch: 003 | Train loss: 0.9963 | Train acc: 50.86% | Val loss: 1.0179 | Val acc: 45.69% | LR: 0.000023
Epoch: 004 | Train loss: 0.9981 | Train acc: 50.31% | Val loss: 1.0052 | Val acc: 45.45% | LR: 0.000023
Epoch: 005 | Train loss: 1.0152 | Train acc: 50.01% | Val loss: 1.0046 | Val acc: 45.49% | LR: 0.000023
Epoch: 006 | Train loss: 0.9972 | Train acc: 50.39% | Val loss: 1.0118 | Val acc: 45.20% | LR: 0.000023
Epoch: 007 | Train loss: 0.9979 | Train acc: 50.14% | Val loss: 1.0036 | Val acc: 45.32% | LR: 0.000023
Epoch: 008 | Train loss: 0.9995 | Train acc: 49.79% | Val loss: 1.0092 | Val acc: 45.43% | LR: 0.000023
Epoch: 009 | Train loss: 1.0030 | Train acc: 50.27% | Val loss: 1.0331 | Val acc: 45.91% | LR: 0.000023
Epoch: 010 | Train loss: 0.9974 | Train acc: 50.44% | Val loss: 1.0061 | Val acc: 46.14% | LR: 0.000023
Epoch: 011 | Train loss: 0.9983 | Train acc: 50.45% | Val loss: 1.0085 | Val acc: 45.91% | LR: 0.000023
Epoch: 012 | Train loss: 0.9954 | Train acc: 51.06% | Val loss: 1.0039 | Val acc: 46.08% | LR: 0.000022
Epoch: 013 | Train loss: 0.9986 | Train acc: 50.15% | Val loss: 1.0045 | Val acc: 45.96% | LR: 0.000022
Epoch: 014 | Train loss: 0.9961 | Train acc: 50.59% | Val loss: 1.0013 | Val acc: 46.60% | LR: 0.000022
Epoch: 015 | Train loss: 1.0000 | Train acc: 50.45% | Val loss: 1.0049 | Val acc: 46.00% | LR: 0.000022
Epoch: 016 | Train loss: 0.9971 | Train acc: 50.21% | Val loss: 1.0146 | Val acc: 46.09% | LR: 0.000022
Epoch: 017 | Train loss: 0.9947 | Train acc: 50.71% | Val loss: 1.0040 | Val acc: 45.90% | LR: 0.000022
Epoch: 018 | Train loss: 1.0005 | Train acc: 50.23% | Val loss: 1.0046 | Val acc: 45.72% | LR: 0.000022
Epoch: 019 | Train loss: 0.9966 | Train acc: 50.55% | Val loss: 1.0033 | Val acc: 45.74% | LR: 0.000022
Epoch: 020 | Train loss: 0.9983 | Train acc: 50.39% | Val loss: 1.0062 | Val acc: 45.70% | LR: 0.000022
Epoch: 021 | Train loss: 1.0008 | Train acc: 49.95% | Val loss: 1.0053 | Val acc: 45.72% | LR: 0.000022
Epoch: 022 | Train loss: 0.9996 | Train acc: 50.05% | Val loss: 1.0047 | Val acc: 45.74% | LR: 0.000022
Epoch: 023 | Train loss: 0.9979 | Train acc: 50.56% | Val loss: 1.0032 | Val acc: 46.12% | LR: 0.000022
Epoch: 024 | Train loss: 0.9991 | Train acc: 50.26% | Val loss: 1.0042 | Val acc: 46.12% | LR: 0.000021
Epoch: 025 | Train loss: 0.9993 | Train acc: 50.55% | Val loss: 1.0053 | Val acc: 46.20% | LR: 0.000021
Epoch: 026 | Train loss: 0.9954 | Train acc: 50.53% | Val loss: 1.0032 | Val acc: 46.01% | LR: 0.000021
Epoch: 027 | Train loss: 0.9925 | Train acc: 50.95% | Val loss: 1.0037 | Val acc: 46.60% | LR: 0.000021
Epoch: 028 | Train loss: 0.9991 | Train acc: 50.11% | Val loss: 1.0019 | Val acc: 46.48% | LR: 0.000021
Epoch: 029 | Train loss: 0.9955 | Train acc: 50.36% | Val loss: 1.0070 | Val acc: 46.21% | LR: 0.000021
Epoch: 030 | Train loss: 0.9949 | Train acc: 50.80% | Val loss: 1.0049 | Val acc: 46.41% | LR: 0.000021
Epoch: 031 | Train loss: 0.9979 | Train acc: 50.36% | Val loss: 1.0103 | Val acc: 46.15% | LR: 0.000021
Epoch: 032 | Train loss: 0.9984 | Train acc: 50.15% | Val loss: 1.0026 | Val acc: 46.68% | LR: 0.000020
Epoch: 033 | Train loss: 0.9943 | Train acc: 50.70% | Val loss: 1.0065 | Val acc: 46.10% | LR: 0.000020
Epoch: 034 | Train loss: 0.9963 | Train acc: 50.53% | Val loss: 1.0044 | Val acc: 46.12% | LR: 0.000020
Epoch: 035 | Train loss: 0.9938 | Train acc: 50.67% | Val loss: 1.0037 | Val acc: 46.04% | LR: 0.000020
Epoch: 036 | Train loss: 0.9988 | Train acc: 50.60% | Val loss: 1.0047 | Val acc: 46.04% | LR: 0.000020
Epoch: 037 | Train loss: 0.9965 | Train acc: 50.41% | Val loss: 1.0028 | Val acc: 46.19% | LR: 0.000020
Epoch: 038 | Train loss: 0.9923 | Train acc: 50.66% | Val loss: 1.0050 | Val acc: 45.91% | LR: 0.000019
Epoch: 039 | Train loss: 0.9984 | Train acc: 49.98% | Val loss: 1.0036 | Val acc: 45.91% | LR: 0.000019
Epoch: 040 | Train loss: 0.9934 | Train acc: 50.48% | Val loss: 1.0199 | Val acc: 45.96% | LR: 0.000019
Epoch: 041 | Train loss: 0.9917 | Train acc: 50.92% | Val loss: 1.0032 | Val acc: 46.15% | LR: 0.000019
Epoch: 042 | Train loss: 0.9936 | Train acc: 50.55% | Val loss: 1.0028 | Val acc: 46.01% | LR: 0.000019
Epoch: 043 | Train loss: 0.9916 | Train acc: 50.54% | Val loss: 1.0036 | Val acc: 46.17% | LR: 0.000019
Epoch: 044 | Train loss: 0.9910 | Train acc: 50.91% | Val loss: 1.0039 | Val acc: 46.08% | LR: 0.000018
Epoch: 045 | Train loss: 0.9924 | Train acc: 50.56% | Val loss: 1.0049 | Val acc: 46.02% | LR: 0.000018
Epoch: 046 | Train loss: 0.9933 | Train acc: 50.57% | Val loss: 1.0042 | Val acc: 46.15% | LR: 0.000018
Epoch: 047 | Train loss: 0.9911 | Train acc: 50.64% | Val loss: 1.0039 | Val acc: 45.90% | LR: 0.000018
Epoch: 048 | Train loss: 0.9943 | Train acc: 50.73% | Val loss: 1.0040 | Val acc: 45.74% | LR: 0.000018
Epoch: 049 | Train loss: 0.9911 | Train acc: 50.55% | Val loss: 1.0037 | Val acc: 45.92% | LR: 0.000017
Epoch: 050 | Train loss: 0.9972 | Train acc: 50.15% | Val loss: 1.0041 | Val acc: 46.11% | LR: 0.000017
Epoch: 051 | Train loss: 0.9959 | Train acc: 50.24% | Val loss: 1.0030 | Val acc: 46.14% | LR: 0.000017
Epoch: 052 | Train loss: 0.9954 | Train acc: 50.45% | Val loss: 1.0100 | Val acc: 46.23% | LR: 0.000017
Epoch: 053 | Train loss: 1.0004 | Train acc: 49.96% | Val loss: 1.0044 | Val acc: 46.07% | LR: 0.000017
Epoch: 054 | Train loss: 0.9867 | Train acc: 51.13% | Val loss: 1.0214 | Val acc: 45.90% | LR: 0.000016
Epoch: 055 | Train loss: 0.9931 | Train acc: 50.67% | Val loss: 1.0031 | Val acc: 46.23% | LR: 0.000016
Epoch: 056 | Train loss: 0.9932 | Train acc: 50.41% | Val loss: 1.0030 | Val acc: 45.99% | LR: 0.000016
Epoch: 057 | Train loss: 0.9910 | Train acc: 50.66% | Val loss: 1.0044 | Val acc: 46.23% | LR: 0.000016
Epoch: 058 | Train loss: 0.9897 | Train acc: 50.66% | Val loss: 1.0044 | Val acc: 46.05% | LR: 0.000016
Epoch: 059 | Train loss: 0.9984 | Train acc: 50.22% | Val loss: 1.0033 | Val acc: 46.11% | LR: 0.000015
Epoch: 060 | Train loss: 0.9899 | Train acc: 50.65% | Val loss: 1.0044 | Val acc: 45.88% | LR: 0.000015
Epoch: 061 | Train loss: 0.9927 | Train acc: 50.40% | Val loss: 1.0035 | Val acc: 46.09% | LR: 0.000015
Epoch: 062 | Train loss: 0.9912 | Train acc: 50.64% | Val loss: 1.0037 | Val acc: 45.84% | LR: 0.000015
Epoch: 063 | Train loss: 0.9890 | Train acc: 50.82% | Val loss: 1.0039 | Val acc: 45.97% | LR: 0.000014
Epoch: 064 | Train loss: 0.9928 | Train acc: 50.47% | Val loss: 1.0050 | Val acc: 46.22% | LR: 0.000014
Epoch: 065 | Train loss: 0.9926 | Train acc: 50.70% | Val loss: 1.0061 | Val acc: 46.19% | LR: 0.000014
Epoch: 066 | Train loss: 0.9928 | Train acc: 50.30% | Val loss: 1.0030 | Val acc: 46.19% | LR: 0.000014
Epoch: 067 | Train loss: 0.9962 | Train acc: 50.20% | Val loss: 1.0030 | Val acc: 46.11% | LR: 0.000014
Epoch: 068 | Train loss: 0.9925 | Train acc: 50.49% | Val loss: 1.0032 | Val acc: 46.23% | LR: 0.000013
Epoch: 069 | Train loss: 0.9933 | Train acc: 50.64% | Val loss: 1.0054 | Val acc: 46.15% | LR: 0.000013
Epoch: 070 | Train loss: 0.9920 | Train acc: 50.59% | Val loss: 1.0033 | Val acc: 46.22% | LR: 0.000013
Epoch: 071 | Train loss: 0.9966 | Train acc: 50.20% | Val loss: 1.0059 | Val acc: 46.19% | LR: 0.000013
Epoch: 072 | Train loss: 0.9947 | Train acc: 50.60% | Val loss: 1.0077 | Val acc: 46.31% | LR: 0.000012
Epoch: 073 | Train loss: 1.0019 | Train acc: 49.78% | Val loss: 1.0525 | Val acc: 46.00% | LR: 0.000012
Epoch: 074 | Train loss: 0.9998 | Train acc: 50.09% | Val loss: 1.0213 | Val acc: 46.22% | LR: 0.000012
Epoch: 075 | Train loss: 0.9953 | Train acc: 50.50% | Val loss: 1.0762 | Val acc: 46.05% | LR: 0.000012
Epoch: 076 | Train loss: 0.9912 | Train acc: 50.59% | Val loss: 1.0037 | Val acc: 46.12% | LR: 0.000011
Epoch: 077 | Train loss: 0.9903 | Train acc: 50.76% | Val loss: 1.0040 | Val acc: 46.34% | LR: 0.000011
Epoch: 078 | Train loss: 0.9950 | Train acc: 50.38% | Val loss: 1.0021 | Val acc: 46.18% | LR: 0.000011
Epoch: 079 | Train loss: 0.9964 | Train acc: 50.13% | Val loss: 1.0191 | Val acc: 45.86% | LR: 0.000011
Epoch: 080 | Train loss: 0.9893 | Train acc: 50.84% | Val loss: 1.0028 | Val acc: 45.96% | LR: 0.000011
Epoch: 081 | Train loss: 0.9937 | Train acc: 50.58% | Val loss: 1.0033 | Val acc: 46.18% | LR: 0.000010

[I 2025-09-23 17:06:39,400] Trial 47 finished with value: 0.4629278242588043 and parameters: {'lr': 2.289407455807825e-05, 'hidden_size': 92, 'dropout': 0.2721229651406953, 'weight_decay': 1.461692984721071e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0017 | Train acc: 49.95% | Val loss: 0.9935 | Val acc: 54.05% | LR: 0.000182
Epoch: 001 | Train loss: 0.9987 | Train acc: 50.60% | Val loss: 0.9941 | Val acc: 54.05% | LR: 0.000182
Epoch: 002 | Train loss: 0.9975 | Train acc: 50.52% | Val loss: 0.9951 | Val acc: 54.05% | LR: 0.000182
Epoch: 003 | Train loss: 0.9964 | Train acc: 50.80% | Val loss: 0.9954 | Val acc: 54.05% | LR: 0.000181
Epoch: 004 | Train loss: 0.9986 | Train acc: 50.01% | Val loss: 0.9949 | Val acc: 54.05% | LR: 0.000181
Epoch: 005 | Train loss: 0.9941 | Train acc: 50.45% | Val loss: 0.9950 | Val acc: 54.05% | LR: 0.000181
Epoch: 006 | Train loss: 0.9929 | Train acc: 50.72% | Val loss: 0.9951 | Val acc: 54.03% | LR: 0.000181
Epoch: 007 | Train loss: 0.9903 | Train acc: 50.80% | Val loss: 0.9947 | Val acc: 54.20% | LR: 0.000180
Epoch: 008 | Train loss: 0.9943 | Train acc: 50.45% | Val loss: 0.9937 | Val acc: 54.46% | LR: 0.000180
Epoch: 009 | Train loss: 0.9872 | Train acc: 50.69% | Val loss: 0.9923 | Val acc: 54.31% | LR: 0.000180
Epoch: 010 | Train loss: 0.9923 | Train acc: 50.84% | Val loss: 0.9909 | Val acc: 54.48% | LR: 0.000179
Epoch: 011 | Train loss: 0.9968 | Train acc: 50.61% | Val loss: 0.9904 | Val acc: 54.44% | LR: 0.000179
Epoch: 012 | Train loss: 0.9913 | Train acc: 50.89% | Val loss: 0.9880 | Val acc: 54.10% | LR: 0.000178
Epoch: 013 | Train loss: 0.9905 | Train acc: 50.68% | Val loss: 0.9834 | Val acc: 53.91% | LR: 0.000178
Epoch: 014 | Train loss: 0.9899 | Train acc: 50.84% | Val loss: 0.9791 | Val acc: 53.39% | LR: 0.000177
Epoch: 015 | Train loss: 0.9885 | Train acc: 50.75% | Val loss: 0.9697 | Val acc: 53.42% | LR: 0.000177
Epoch: 016 | Train loss: 0.9768 | Train acc: 51.26% | Val loss: 0.9689 | Val acc: 53.38% | LR: 0.000176
Epoch: 017 | Train loss: 0.9790 | Train acc: 51.42% | Val loss: 0.9700 | Val acc: 53.32% | LR: 0.000175
Epoch: 018 | Train loss: 0.9779 | Train acc: 51.46% | Val loss: 0.9702 | Val acc: 52.66% | LR: 0.000175
Epoch: 019 | Train loss: 0.9957 | Train acc: 50.27% | Val loss: 0.9717 | Val acc: 52.12% | LR: 0.000174
Epoch: 020 | Train loss: 0.9876 | Train acc: 50.79% | Val loss: 0.9743 | Val acc: 51.71% | LR: 0.000173
Epoch: 021 | Train loss: 0.9838 | Train acc: 50.86% | Val loss: 0.9771 | Val acc: 51.18% | LR: 0.000172
Epoch: 022 | Train loss: 0.9779 | Train acc: 51.37% | Val loss: 0.9809 | Val acc: 51.02% | LR: 0.000171
Epoch: 023 | Train loss: 0.9784 | Train acc: 51.11% | Val loss: 0.9858 | Val acc: 50.57% | LR: 0.000171
Epoch: 024 | Train loss: 0.9850 | Train acc: 50.86% | Val loss: 0.9850 | Val acc: 50.57% | LR: 0.000170
Epoch: 025 | Train loss: 0.9825 | Train acc: 50.94% | Val loss: 0.9877 | Val acc: 50.62% | LR: 0.000169
Epoch: 026 | Train loss: 0.9888 | Train acc: 50.62% | Val loss: 0.9913 | Val acc: 50.38% | LR: 0.000168
Epoch: 027 | Train loss: 0.9811 | Train acc: 51.14% | Val loss: 0.9939 | Val acc: 50.12% | LR: 0.000167
Epoch: 028 | Train loss: 0.9874 | Train acc: 50.71% | Val loss: 0.9949 | Val acc: 50.10% | LR: 0.000166
Epoch: 029 | Train loss: 0.9751 | Train acc: 51.44% | Val loss: 1.0034 | Val acc: 49.59% | LR: 0.000164
Epoch: 030 | Train loss: 0.9799 | Train acc: 51.28% | Val loss: 1.0012 | Val acc: 49.62% | LR: 0.000163
Epoch: 031 | Train loss: 0.9842 | Train acc: 50.95% | Val loss: 0.9991 | Val acc: 49.74% | LR: 0.000162
Epoch: 032 | Train loss: 0.9726 | Train acc: 51.49% | Val loss: 0.9972 | Val acc: 50.06% | LR: 0.000161
Epoch: 033 | Train loss: 0.9884 | Train acc: 50.62% | Val loss: 1.0013 | Val acc: 49.58% | LR: 0.000160
Epoch: 034 | Train loss: 0.9793 | Train acc: 51.19% | Val loss: 1.0069 | Val acc: 49.30% | LR: 0.000159
Epoch: 035 | Train loss: 0.9986 | Train acc: 50.56% | Val loss: 1.0090 | Val acc: 49.26% | LR: 0.000157
Epoch: 036 | Train loss: 0.9849 | Train acc: 50.82% | Val loss: 1.0099 | Val acc: 49.24% | LR: 0.000156
Epoch: 037 | Train loss: 0.9775 | Train acc: 51.28% | Val loss: 1.0127 | Val acc: 49.36% | LR: 0.000155
Epoch: 038 | Train loss: 0.9777 | Train acc: 51.19% | Val loss: 1.0116 | Val acc: 49.40% | LR: 0.000153
Epoch: 039 | Train loss: 0.9883 | Train acc: 50.76% | Val loss: 1.0131 | Val acc: 49.02% | LR: 0.000152
Epoch: 040 | Train loss: 0.9710 | Train acc: 51.61% | Val loss: 1.0129 | Val acc: 48.96% | LR: 0.000150
Epoch: 041 | Train loss: 0.9765 | Train acc: 51.28% | Val loss: 1.0126 | Val acc: 49.14% | LR: 0.000149
Epoch: 042 | Train loss: 0.9691 | Train acc: 51.70% | Val loss: 1.0156 | Val acc: 48.74% | LR: 0.000147
Epoch: 043 | Train loss: 0.9810 | Train acc: 51.03% | Val loss: 1.0166 | Val acc: 48.80% | LR: 0.000146
Epoch: 044 | Train loss: 0.9746 | Train acc: 51.34% | Val loss: 1.0183 | Val acc: 48.84% | LR: 0.000144
Epoch: 045 | Train loss: 0.9837 | Train acc: 50.85% | Val loss: 1.0129 | Val acc: 48.94% | LR: 0.000143
Epoch: 046 | Train loss: 0.9826 | Train acc: 50.93% | Val loss: 1.0117 | Val acc: 49.00% | LR: 0.000141
Epoch: 047 | Train loss: 0.9859 | Train acc: 50.75% | Val loss: 1.0178 | Val acc: 48.94% | LR: 0.000140
Epoch: 048 | Train loss: 0.9750 | Train acc: 51.37% | Val loss: 1.0134 | Val acc: 48.90% | LR: 0.000138
Epoch: 049 | Train loss: 0.9877 | Train acc: 50.66% | Val loss: 1.0130 | Val acc: 49.08% | LR: 0.000137
Epoch: 050 | Train loss: 0.9851 | Train acc: 50.73% | Val loss: 1.0104 | Val acc: 49.24% | LR: 0.000135
Epoch: 051 | Train loss: 0.9752 | Train acc: 51.35% | Val loss: 1.0186 | Val acc: 49.06% | LR: 0.000133
Epoch: 052 | Train loss: 0.9894 | Train acc: 51.30% | Val loss: 1.0223 | Val acc: 48.62% | LR: 0.000132
Epoch: 053 | Train loss: 0.9813 | Train acc: 51.10% | Val loss: 1.0220 | Val acc: 48.64% | LR: 0.000130
Epoch: 054 | Train loss: 0.9832 | Train acc: 50.93% | Val loss: 1.0273 | Val acc: 48.56% | LR: 0.000128
Epoch: 055 | Train loss: 0.9800 | Train acc: 51.11% | Val loss: 1.0231 | Val acc: 48.54% | LR: 0.000126
Epoch: 056 | Train loss: 0.9816 | Train acc: 50.95% | Val loss: 1.0182 | Val acc: 48.92% | LR: 0.000125
Epoch: 057 | Train loss: 0.9743 | Train acc: 51.37% | Val loss: 1.0187 | Val acc: 48.88% | LR: 0.000123
Epoch: 058 | Train loss: 0.9845 | Train acc: 50.79% | Val loss: 1.0225 | Val acc: 48.80% | LR: 0.000121
Epoch: 059 | Train loss: 0.9782 | Train acc: 51.08% | Val loss: 1.0157 | Val acc: 48.92% | LR: 0.000119

[I 2025-09-23 17:07:34,009] Trial 48 finished with value: 0.48717848062515257 and parameters: {'lr': 0.00018171828914246074, 'hidden_size': 103, 'dropout': 0.384375159128637, 'weight_decay': 1.6028398623965077e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0031 | Train acc: 49.92% | Val loss: 0.9926 | Val acc: 51.49% | LR: 0.001941
Epoch: 001 | Train loss: 1.0254 | Train acc: 50.52% | Val loss: 1.0107 | Val acc: 49.04% | LR: 0.001941
Epoch: 002 | Train loss: 0.9911 | Train acc: 51.20% | Val loss: 1.0451 | Val acc: 50.95% | LR: 0.001939
Epoch: 003 | Train loss: 0.9919 | Train acc: 50.62% | Val loss: 1.0402 | Val acc: 46.07% | LR: 0.001938
Epoch: 004 | Train loss: 0.9968 | Train acc: 50.40% | Val loss: 1.0358 | Val acc: 46.03% | LR: 0.001936
Epoch: 005 | Train loss: 0.9978 | Train acc: 50.10% | Val loss: 1.0323 | Val acc: 46.21% | LR: 0.001934
Epoch: 006 | Train loss: 0.9812 | Train acc: 50.88% | Val loss: 1.0225 | Val acc: 47.15% | LR: 0.001931
Epoch: 007 | Train loss: 0.9942 | Train acc: 50.43% | Val loss: 1.0184 | Val acc: 48.52% | LR: 0.001928
Epoch: 008 | Train loss: 0.9855 | Train acc: 51.10% | Val loss: 0.9955 | Val acc: 51.05% | LR: 0.001924
Epoch: 009 | Train loss: 0.9846 | Train acc: 50.95% | Val loss: 0.9930 | Val acc: 50.26% | LR: 0.001920
Epoch: 010 | Train loss: 0.9860 | Train acc: 50.74% | Val loss: 0.9851 | Val acc: 50.08% | LR: 0.001916
Epoch: 011 | Train loss: 0.9890 | Train acc: 50.74% | Val loss: 0.9974 | Val acc: 49.57% | LR: 0.001911
Epoch: 012 | Train loss: 0.9791 | Train acc: 51.45% | Val loss: 0.9941 | Val acc: 49.47% | LR: 0.001906
Epoch: 013 | Train loss: 0.9883 | Train acc: 51.10% | Val loss: 0.9885 | Val acc: 50.68% | LR: 0.001900
Epoch: 014 | Train loss: 0.9799 | Train acc: 51.45% | Val loss: 1.0059 | Val acc: 49.34% | LR: 0.001894
Epoch: 015 | Train loss: 0.9846 | Train acc: 50.98% | Val loss: 1.0259 | Val acc: 48.86% | LR: 0.001887
Epoch: 016 | Train loss: 0.9816 | Train acc: 51.05% | Val loss: 1.0076 | Val acc: 49.52% | LR: 0.001881
Epoch: 017 | Train loss: 0.9827 | Train acc: 51.00% | Val loss: 0.9953 | Val acc: 50.28% | LR: 0.001873
Epoch: 018 | Train loss: 0.9789 | Train acc: 51.18% | Val loss: 1.0189 | Val acc: 49.32% | LR: 0.001866
Epoch: 019 | Train loss: 0.9754 | Train acc: 51.40% | Val loss: 1.0187 | Val acc: 49.06% | LR: 0.001858
Epoch: 020 | Train loss: 0.9799 | Train acc: 51.13% | Val loss: 0.9848 | Val acc: 51.14% | LR: 0.001849
Epoch: 021 | Train loss: 0.9819 | Train acc: 51.02% | Val loss: 1.0014 | Val acc: 50.67% | LR: 0.001840
Epoch: 022 | Train loss: 0.9768 | Train acc: 51.35% | Val loss: 1.0171 | Val acc: 49.61% | LR: 0.001831
Epoch: 023 | Train loss: 0.9872 | Train acc: 50.72% | Val loss: 1.0098 | Val acc: 49.62% | LR: 0.001821
Epoch: 024 | Train loss: 0.9788 | Train acc: 51.41% | Val loss: 1.0079 | Val acc: 49.65% | LR: 0.001811
Epoch: 025 | Train loss: 0.9822 | Train acc: 51.05% | Val loss: 1.0028 | Val acc: 49.83% | LR: 0.001801
Epoch: 026 | Train loss: 0.9780 | Train acc: 51.22% | Val loss: 0.9980 | Val acc: 50.12% | LR: 0.001790
Epoch: 027 | Train loss: 0.9811 | Train acc: 51.15% | Val loss: 1.0088 | Val acc: 49.99% | LR: 0.001779
Epoch: 028 | Train loss: 0.9710 | Train acc: 51.68% | Val loss: 1.0131 | Val acc: 49.53% | LR: 0.001768
Epoch: 029 | Train loss: 0.9852 | Train acc: 50.77% | Val loss: 1.0087 | Val acc: 49.60% | LR: 0.001756
Epoch: 030 | Train loss: 0.9766 | Train acc: 51.40% | Val loss: 1.0028 | Val acc: 49.86% | LR: 0.001744
Epoch: 031 | Train loss: 0.9824 | Train acc: 50.98% | Val loss: 1.0067 | Val acc: 49.86% | LR: 0.001732
Epoch: 032 | Train loss: 0.9778 | Train acc: 51.35% | Val loss: 1.0266 | Val acc: 48.77% | LR: 0.001719
Epoch: 033 | Train loss: 0.9648 | Train acc: 51.96% | Val loss: 1.0241 | Val acc: 48.59% | LR: 0.001706
Epoch: 034 | Train loss: 0.9831 | Train acc: 51.00% | Val loss: 1.0300 | Val acc: 48.23% | LR: 0.001692
Epoch: 035 | Train loss: 0.9802 | Train acc: 51.06% | Val loss: 1.0063 | Val acc: 49.76% | LR: 0.001678
Epoch: 036 | Train loss: 0.9795 | Train acc: 51.18% | Val loss: 0.9919 | Val acc: 50.97% | LR: 0.001664
Epoch: 037 | Train loss: 0.9809 | Train acc: 51.36% | Val loss: 1.0013 | Val acc: 50.08% | LR: 0.001650
Epoch: 038 | Train loss: 0.9945 | Train acc: 50.26% | Val loss: 1.0579 | Val acc: 47.39% | LR: 0.001635
Epoch: 039 | Train loss: 0.9962 | Train acc: 50.33% | Val loss: 1.0280 | Val acc: 47.37% | LR: 0.001620
Epoch: 040 | Train loss: 0.9880 | Train acc: 50.83% | Val loss: 1.0291 | Val acc: 47.97% | LR: 0.001605
Epoch: 041 | Train loss: 0.9832 | Train acc: 51.14% | Val loss: 1.0038 | Val acc: 49.21% | LR: 0.001590
Epoch: 042 | Train loss: 0.9888 | Train acc: 50.76% | Val loss: 1.0254 | Val acc: 48.59% | LR: 0.001574
Epoch: 043 | Train loss: 0.9823 | Train acc: 51.67% | Val loss: 1.0594 | Val acc: 46.93% | LR: 0.001558
Epoch: 044 | Train loss: 0.9975 | Train acc: 50.46% | Val loss: 1.0412 | Val acc: 47.98% | LR: 0.001541
Epoch: 045 | Train loss: 0.9950 | Train acc: 50.48% | Val loss: 1.0426 | Val acc: 47.36% | LR: 0.001525
Epoch: 046 | Train loss: 0.9935 | Train acc: 50.94% | Val loss: 1.0285 | Val acc: 50.85% | LR: 0.001508
Epoch: 047 | Train loss: 1.0046 | Train acc: 50.06% | Val loss: 0.9978 | Val acc: 53.08% | LR: 0.001491
Epoch: 048 | Train loss: 0.9903 | Train acc: 51.26% | Val loss: 1.0546 | Val acc: 50.37% | LR: 0.001474
Epoch: 049 | Train loss: 0.9871 | Train acc: 50.62% | Val loss: 1.0333 | Val acc: 50.82% | LR: 0.001456
Epoch: 050 | Train loss: 0.9892 | Train acc: 50.64% | Val loss: 1.0175 | Val acc: 50.68% | LR: 0.001439
Epoch: 051 | Train loss: 0.9767 | Train acc: 51.38% | Val loss: 1.0175 | Val acc: 50.17% | LR: 0.001421
Epoch: 052 | Train loss: 0.9850 | Train acc: 51.12% | Val loss: 1.0199 | Val acc: 49.68% | LR: 0.001403
Epoch: 053 | Train loss: 0.9866 | Train acc: 50.87% | Val loss: 1.4864 | Val acc: 49.79% | LR: 0.001384
Epoch: 054 | Train loss: 0.9856 | Train acc: 50.73% | Val loss: 1.0196 | Val acc: 49.37% | LR: 0.001366
Epoch: 055 | Train loss: 0.9881 | Train acc: 50.81% | Val loss: 1.0265 | Val acc: 48.75% | LR: 0.001347
Epoch: 056 | Train loss: 0.9851 | Train acc: 51.01% | Val loss: 1.0353 | Val acc: 48.68% | LR: 0.001328
Epoch: 057 | Train loss: 0.9840 | Train acc: 51.05% | Val loss: 1.0239 | Val acc: 49.05% | LR: 0.001309
Epoch: 058 | Train loss: 0.9758 | Train acc: 51.42% | Val loss: 1.0773 | Val acc: 47.80% | LR: 0.001290
Epoch: 059 | Train loss: 0.9845 | Train acc: 50.94% | Val loss: 1.0428 | Val acc: 47.76% | LR: 0.001271
Epoch: 060 | Train loss: 0.9810 | Train acc: 51.12% | Val loss: 1.0300 | Val acc: 47.97% | LR: 0.001252
Epoch: 061 | Train loss: 0.9727 | Train acc: 51.59% | Val loss: 1.0412 | Val acc: 47.93% | LR: 0.001232
Epoch: 062 | Train loss: 0.9764 | Train acc: 51.30% | Val loss: 1.0556 | Val acc: 47.79% | LR: 0.001212
Epoch: 063 | Train loss: 0.9786 | Train acc: 51.19% | Val loss: 1.0281 | Val acc: 48.57% | LR: 0.001193
Epoch: 064 | Train loss: 0.9787 | Train acc: 51.21% | Val loss: 1.0165 | Val acc: 48.57% | LR: 0.001173
Epoch: 065 | Train loss: 0.9857 | Train acc: 50.85% | Val loss: 1.0251 | Val acc: 48.91% | LR: 0.001153
Epoch: 066 | Train loss: 0.9744 | Train acc: 51.41% | Val loss: 1.0228 | Val acc: 48.78% | LR: 0.001133
Epoch: 067 | Train loss: 0.9782 | Train acc: 51.22% | Val loss: 1.0282 | Val acc: 48.65% | LR: 0.001113
Epoch: 068 | Train loss: 0.9697 | Train acc: 51.68% | Val loss: 1.0201 | Val acc: 49.27% | LR: 0.001093
Epoch: 069 | Train loss: 0.9902 | Train acc: 50.51% | Val loss: 1.0173 | Val acc: 49.29% | LR: 0.001073
Epoch: 070 | Train loss: 0.9736 | Train acc: 51.49% | Val loss: 1.0191 | Val acc: 49.17% | LR: 0.001052
Epoch: 071 | Train loss: 0.9786 | Train acc: 51.16% | Val loss: 1.0227 | Val acc: 49.41% | LR: 0.001032
Epoch: 072 | Train loss: 0.9842 | Train acc: 50.87% | Val loss: 1.0182 | Val acc: 49.27% | LR: 0.001012
Epoch: 073 | Train loss: 0.9803 | Train acc: 51.04% | Val loss: 1.0198 | Val acc: 49.42% | LR: 0.000992
Epoch: 074 | Train loss: 0.9941 | Train acc: 50.35% | Val loss: 1.0124 | Val acc: 49.49% | LR: 0.000971
Epoch: 075 | Train loss: 0.9810 | Train acc: 51.15% | Val loss: 1.0089 | Val acc: 49.70% | LR: 0.000951
Epoch: 076 | Train loss: 0.9726 | Train acc: 51.56% | Val loss: 1.0018 | Val acc: 50.18% | LR: 0.000931
Epoch: 077 | Train loss: 0.9770 | Train acc: 51.27% | Val loss: 0.9982 | Val acc: 50.15% | LR: 0.000910
Epoch: 078 | Train loss: 0.9900 | Train acc: 50.58% | Val loss: 0.9912 | Val acc: 50.54% | LR: 0.000890
Epoch: 079 | Train loss: 0.9840 | Train acc: 50.94% | Val loss: 0.9927 | Val acc: 50.69% | LR: 0.000870
Epoch: 080 | Train loss: 0.9819 | Train acc: 50.96% | Val loss: 1.0416 | Val acc: 50.51% | LR: 0.000850
Epoch: 081 | Train loss: 0.9805 | Train acc: 51.05% | Val loss: 0.9927 | Val acc: 50.42% | LR: 0.000829
Epoch: 082 | Train loss: 0.9816 | Train acc: 50.99% | Val loss: 0.9923 | Val acc: 50.41% | LR: 0.000809
Epoch: 083 | Train loss: 0.9793 | Train acc: 51.07% | Val loss: 0.9968 | Val acc: 50.29% | LR: 0.000789
Epoch: 084 | Train loss: 0.9704 | Train acc: 51.54% | Val loss: 1.0029 | Val acc: 50.29% | LR: 0.000769
Epoch: 085 | Train loss: 0.9829 | Train acc: 50.91% | Val loss: 0.9960 | Val acc: 50.31% | LR: 0.000750
Epoch: 086 | Train loss: 0.9842 | Train acc: 50.87% | Val loss: 1.0111 | Val acc: 50.21% | LR: 0.000730
Epoch: 087 | Train loss: 0.9708 | Train acc: 51.48% | Val loss: 0.9946 | Val acc: 50.39% | LR: 0.000710
Epoch: 088 | Train loss: 0.9767 | Train acc: 51.29% | Val loss: 0.9927 | Val acc: 50.47% | LR: 0.000691
Epoch: 089 | Train loss: 0.9789 | Train acc: 51.10% | Val loss: 0.9910 | Val acc: 50.67% | LR: 0.000671
Epoch: 090 | Train loss: 0.9773 | Train acc: 51.23% | Val loss: 0.9851 | Val acc: 50.79% | LR: 0.000652
Epoch: 091 | Train loss: 0.9806 | Train acc: 50.97% | Val loss: 0.9842 | Val acc: 50.74% | LR: 0.000633
Epoch: 092 | Train loss: 0.9910 | Train acc: 50.41% | Val loss: 0.9871 | Val acc: 50.59% | LR: 0.000614
Epoch: 093 | Train loss: 0.9777 | Train acc: 51.13% | Val loss: 0.9808 | Val acc: 51.03% | LR: 0.000595
Epoch: 094 | Train loss: 0.9876 | Train acc: 50.62% | Val loss: 0.9829 | Val acc: 51.07% | LR: 0.000577
Epoch: 095 | Train loss: 0.9792 | Train acc: 51.16% | Val loss: 0.9886 | Val acc: 50.65% | LR: 0.000558
Epoch: 096 | Train loss: 0.9860 | Train acc: 50.82% | Val loss: 0.9898 | Val acc: 50.61% | LR: 0.000540

[I 2025-09-23 17:09:06,616] Trial 49 finished with value: 0.5066487610340118 and parameters: {'lr': 0.001941377746107175, 'hidden_size': 117, 'dropout': 0.33914614948548066, 'weight_decay': 5.368560710318297e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9992 | Train acc: 50.02% | Val loss: 1.0064 | Val acc: 45.83% | LR: 0.000427
Epoch: 001 | Train loss: 0.9955 | Train acc: 50.26% | Val loss: 1.0044 | Val acc: 46.03% | LR: 0.000427
Epoch: 002 | Train loss: 0.9933 | Train acc: 50.59% | Val loss: 1.0045 | Val acc: 46.22% | LR: 0.000427
Epoch: 003 | Train loss: 0.9869 | Train acc: 51.11% | Val loss: 1.0032 | Val acc: 47.70% | LR: 0.000426
Epoch: 004 | Train loss: 0.9885 | Train acc: 51.06% | Val loss: 1.0002 | Val acc: 49.00% | LR: 0.000426
Epoch: 005 | Train loss: 0.9796 | Train acc: 51.36% | Val loss: 0.9926 | Val acc: 51.02% | LR: 0.000425
Epoch: 006 | Train loss: 0.9901 | Train acc: 50.74% | Val loss: 0.9938 | Val acc: 50.07% | LR: 0.000425
Epoch: 007 | Train loss: 0.9864 | Train acc: 50.87% | Val loss: 0.9923 | Val acc: 50.22% | LR: 0.000424
Epoch: 008 | Train loss: 0.9818 | Train acc: 51.07% | Val loss: 1.0031 | Val acc: 49.89% | LR: 0.000423
Epoch: 009 | Train loss: 0.9849 | Train acc: 50.86% | Val loss: 1.0171 | Val acc: 48.86% | LR: 0.000422
Epoch: 010 | Train loss: 0.9809 | Train acc: 51.16% | Val loss: 1.0292 | Val acc: 47.95% | LR: 0.000421
Epoch: 011 | Train loss: 0.9782 | Train acc: 51.41% | Val loss: 1.0040 | Val acc: 49.44% | LR: 0.000420
Epoch: 012 | Train loss: 0.9803 | Train acc: 51.10% | Val loss: 1.0164 | Val acc: 48.78% | LR: 0.000419
Epoch: 013 | Train loss: 0.9817 | Train acc: 51.12% | Val loss: 1.0026 | Val acc: 49.86% | LR: 0.000418
Epoch: 014 | Train loss: 0.9813 | Train acc: 51.08% | Val loss: 1.0137 | Val acc: 49.20% | LR: 0.000417
Epoch: 015 | Train loss: 0.9861 | Train acc: 50.60% | Val loss: 1.0243 | Val acc: 48.52% | LR: 0.000415
Epoch: 016 | Train loss: 0.9794 | Train acc: 51.38% | Val loss: 1.0330 | Val acc: 48.46% | LR: 0.000414
Epoch: 017 | Train loss: 0.9848 | Train acc: 50.65% | Val loss: 1.0273 | Val acc: 48.56% | LR: 0.000412
Epoch: 018 | Train loss: 0.9826 | Train acc: 51.07% | Val loss: 1.0186 | Val acc: 48.86% | LR: 0.000410
Epoch: 019 | Train loss: 0.9794 | Train acc: 51.20% | Val loss: 1.0287 | Val acc: 48.54% | LR: 0.000409
Epoch: 020 | Train loss: 0.9827 | Train acc: 50.86% | Val loss: 1.0244 | Val acc: 48.76% | LR: 0.000407
Epoch: 021 | Train loss: 0.9817 | Train acc: 50.93% | Val loss: 1.0207 | Val acc: 49.24% | LR: 0.000405
Epoch: 022 | Train loss: 0.9773 | Train acc: 51.40% | Val loss: 1.0115 | Val acc: 49.37% | LR: 0.000403
Epoch: 023 | Train loss: 0.9774 | Train acc: 51.30% | Val loss: 1.0373 | Val acc: 47.98% | LR: 0.000401
Epoch: 024 | Train loss: 0.9880 | Train acc: 50.56% | Val loss: 1.0251 | Val acc: 48.08% | LR: 0.000399
Epoch: 025 | Train loss: 0.9819 | Train acc: 50.98% | Val loss: 1.0323 | Val acc: 47.99% | LR: 0.000396
Epoch: 026 | Train loss: 0.9805 | Train acc: 50.99% | Val loss: 1.0357 | Val acc: 47.90% | LR: 0.000394
Epoch: 027 | Train loss: 0.9778 | Train acc: 51.27% | Val loss: 1.0184 | Val acc: 48.85% | LR: 0.000391
Epoch: 028 | Train loss: 0.9859 | Train acc: 50.73% | Val loss: 1.0261 | Val acc: 48.84% | LR: 0.000389
Epoch: 029 | Train loss: 0.9871 | Train acc: 50.74% | Val loss: 1.0151 | Val acc: 49.01% | LR: 0.000386
Epoch: 030 | Train loss: 0.9788 | Train acc: 51.14% | Val loss: 1.0208 | Val acc: 49.00% | LR: 0.000384
Epoch: 031 | Train loss: 0.9898 | Train acc: 50.32% | Val loss: 1.0348 | Val acc: 48.21% | LR: 0.000381
Epoch: 032 | Train loss: 0.9841 | Train acc: 51.16% | Val loss: 1.0230 | Val acc: 49.00% | LR: 0.000378
Epoch: 033 | Train loss: 0.9732 | Train acc: 51.58% | Val loss: 1.0198 | Val acc: 49.06% | LR: 0.000375
Epoch: 034 | Train loss: 0.9809 | Train acc: 51.07% | Val loss: 1.0166 | Val acc: 49.36% | LR: 0.000372
Epoch: 035 | Train loss: 0.9774 | Train acc: 51.18% | Val loss: 1.0170 | Val acc: 49.22% | LR: 0.000369
Epoch: 036 | Train loss: 0.9795 | Train acc: 51.11% | Val loss: 1.0199 | Val acc: 49.18% | LR: 0.000366
Epoch: 037 | Train loss: 0.9740 | Train acc: 51.48% | Val loss: 1.0177 | Val acc: 49.16% | LR: 0.000363
Epoch: 038 | Train loss: 0.9749 | Train acc: 51.38% | Val loss: 1.0119 | Val acc: 49.40% | LR: 0.000360
Epoch: 039 | Train loss: 0.9762 | Train acc: 51.33% | Val loss: 1.0124 | Val acc: 49.54% | LR: 0.000357
Epoch: 040 | Train loss: 0.9735 | Train acc: 51.43% | Val loss: 1.0209 | Val acc: 49.04% | LR: 0.000353
Epoch: 041 | Train loss: 0.9853 | Train acc: 50.73% | Val loss: 1.0165 | Val acc: 49.27% | LR: 0.000350
Epoch: 042 | Train loss: 0.9872 | Train acc: 50.63% | Val loss: 1.0175 | Val acc: 49.26% | LR: 0.000346
Epoch: 043 | Train loss: 0.9803 | Train acc: 51.12% | Val loss: 1.0162 | Val acc: 49.18% | LR: 0.000343
Epoch: 044 | Train loss: 0.9794 | Train acc: 51.07% | Val loss: 1.0156 | Val acc: 49.04% | LR: 0.000339
Epoch: 045 | Train loss: 0.9757 | Train acc: 51.29% | Val loss: 1.0140 | Val acc: 49.51% | LR: 0.000336
Epoch: 046 | Train loss: 0.9775 | Train acc: 51.21% | Val loss: 1.0191 | Val acc: 48.88% | LR: 0.000332
Epoch: 047 | Train loss: 0.9822 | Train acc: 50.88% | Val loss: 1.0241 | Val acc: 48.90% | LR: 0.000328
Epoch: 048 | Train loss: 0.9778 | Train acc: 51.25% | Val loss: 1.0291 | Val acc: 48.75% | LR: 0.000324
Epoch: 049 | Train loss: 0.9747 | Train acc: 51.40% | Val loss: 1.0122 | Val acc: 49.16% | LR: 0.000321
Epoch: 050 | Train loss: 0.9807 | Train acc: 50.97% | Val loss: 1.0060 | Val acc: 49.61% | LR: 0.000317
Epoch: 051 | Train loss: 0.9797 | Train acc: 51.08% | Val loss: 1.0121 | Val acc: 49.33% | LR: 0.000313
Epoch: 052 | Train loss: 0.9757 | Train acc: 51.31% | Val loss: 1.0162 | Val acc: 49.48% | LR: 0.000309
Epoch: 053 | Train loss: 0.9847 | Train acc: 50.74% | Val loss: 1.0117 | Val acc: 49.47% | LR: 0.000305
Epoch: 054 | Train loss: 0.9781 | Train acc: 51.21% | Val loss: 1.0153 | Val acc: 49.19% | LR: 0.000301

[I 2025-09-23 17:10:12,005] Trial 50 finished with value: 0.4926728367805481 and parameters: {'lr': 0.00042706178593363996, 'hidden_size': 132, 'dropout': 0.43977573045295326, 'weight_decay': 6.959234207106234e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9996 | Train acc: 50.06% | Val loss: 0.9986 | Val acc: 51.47% | LR: 0.000035
Epoch: 001 | Train loss: 0.9988 | Train acc: 51.06% | Val loss: 0.9981 | Val acc: 51.84% | LR: 0.000035
Epoch: 002 | Train loss: 0.9988 | Train acc: 51.02% | Val loss: 0.9978 | Val acc: 51.96% | LR: 0.000035
Epoch: 003 | Train loss: 0.9973 | Train acc: 51.08% | Val loss: 0.9975 | Val acc: 51.70% | LR: 0.000035
Epoch: 004 | Train loss: 1.0023 | Train acc: 50.70% | Val loss: 0.9974 | Val acc: 51.72% | LR: 0.000035
Epoch: 005 | Train loss: 0.9950 | Train acc: 51.13% | Val loss: 0.9973 | Val acc: 51.64% | LR: 0.000035
Epoch: 006 | Train loss: 0.9958 | Train acc: 51.85% | Val loss: 0.9971 | Val acc: 51.60% | LR: 0.000035
Epoch: 007 | Train loss: 0.9969 | Train acc: 50.91% | Val loss: 0.9967 | Val acc: 52.11% | LR: 0.000035
Epoch: 008 | Train loss: 0.9939 | Train acc: 51.12% | Val loss: 0.9967 | Val acc: 52.01% | LR: 0.000035
Epoch: 009 | Train loss: 0.9940 | Train acc: 51.22% | Val loss: 0.9964 | Val acc: 51.95% | LR: 0.000034
Epoch: 010 | Train loss: 1.0083 | Train acc: 51.22% | Val loss: 0.9963 | Val acc: 51.90% | LR: 0.000034
Epoch: 011 | Train loss: 0.9946 | Train acc: 51.30% | Val loss: 0.9961 | Val acc: 51.86% | LR: 0.000034
Epoch: 012 | Train loss: 0.9936 | Train acc: 51.65% | Val loss: 0.9959 | Val acc: 51.90% | LR: 0.000034
Epoch: 013 | Train loss: 0.9951 | Train acc: 51.12% | Val loss: 0.9958 | Val acc: 51.82% | LR: 0.000034
Epoch: 014 | Train loss: 1.1520 | Train acc: 50.27% | Val loss: 0.9958 | Val acc: 51.84% | LR: 0.000034
Epoch: 015 | Train loss: 1.0381 | Train acc: 50.38% | Val loss: 0.9958 | Val acc: 51.62% | LR: 0.000034
Epoch: 016 | Train loss: 0.9986 | Train acc: 50.74% | Val loss: 0.9955 | Val acc: 51.60% | LR: 0.000034
Epoch: 017 | Train loss: 0.9983 | Train acc: 50.98% | Val loss: 0.9955 | Val acc: 51.37% | LR: 0.000034
Epoch: 018 | Train loss: 0.9985 | Train acc: 50.63% | Val loss: 0.9949 | Val acc: 51.55% | LR: 0.000034
Epoch: 019 | Train loss: 0.9977 | Train acc: 50.86% | Val loss: 0.9944 | Val acc: 51.73% | LR: 0.000033
Epoch: 020 | Train loss: 0.9982 | Train acc: 50.81% | Val loss: 0.9941 | Val acc: 51.77% | LR: 0.000033
Epoch: 021 | Train loss: 0.9977 | Train acc: 50.81% | Val loss: 0.9941 | Val acc: 51.29% | LR: 0.000033
Epoch: 022 | Train loss: 0.9972 | Train acc: 51.04% | Val loss: 0.9935 | Val acc: 51.55% | LR: 0.000033
Epoch: 023 | Train loss: 0.9978 | Train acc: 50.99% | Val loss: 0.9928 | Val acc: 51.57% | LR: 0.000033
Epoch: 024 | Train loss: 0.9965 | Train acc: 51.28% | Val loss: 0.9925 | Val acc: 51.77% | LR: 0.000033
Epoch: 025 | Train loss: 0.9974 | Train acc: 50.92% | Val loss: 0.9920 | Val acc: 51.81% | LR: 0.000032
Epoch: 026 | Train loss: 0.9968 | Train acc: 51.00% | Val loss: 0.9918 | Val acc: 51.76% | LR: 0.000032
Epoch: 027 | Train loss: 0.9967 | Train acc: 50.90% | Val loss: 0.9912 | Val acc: 51.78% | LR: 0.000032
Epoch: 028 | Train loss: 0.9954 | Train acc: 51.16% | Val loss: 0.9904 | Val acc: 51.83% | LR: 0.000032
Epoch: 029 | Train loss: 0.9953 | Train acc: 50.88% | Val loss: 0.9900 | Val acc: 51.70% | LR: 0.000032
Epoch: 030 | Train loss: 0.9959 | Train acc: 50.80% | Val loss: 0.9890 | Val acc: 51.56% | LR: 0.000031
Epoch: 031 | Train loss: 0.9973 | Train acc: 50.79% | Val loss: 0.9885 | Val acc: 51.52% | LR: 0.000031
Epoch: 032 | Train loss: 0.9967 | Train acc: 50.67% | Val loss: 0.9878 | Val acc: 51.52% | LR: 0.000031
Epoch: 033 | Train loss: 0.9955 | Train acc: 50.80% | Val loss: 0.9863 | Val acc: 51.76% | LR: 0.000031
Epoch: 034 | Train loss: 0.9966 | Train acc: 50.71% | Val loss: 0.9846 | Val acc: 51.87% | LR: 0.000031
Epoch: 035 | Train loss: 0.9955 | Train acc: 50.25% | Val loss: 0.9837 | Val acc: 51.82% | LR: 0.000030
Epoch: 036 | Train loss: 0.9959 | Train acc: 50.28% | Val loss: 0.9820 | Val acc: 51.84% | LR: 0.000030
Epoch: 037 | Train loss: 0.9940 | Train acc: 50.39% | Val loss: 0.9813 | Val acc: 51.86% | LR: 0.000030
Epoch: 038 | Train loss: 0.9942 | Train acc: 50.08% | Val loss: 0.9789 | Val acc: 51.88% | LR: 0.000030
Epoch: 039 | Train loss: 0.9946 | Train acc: 50.43% | Val loss: 0.9774 | Val acc: 51.92% | LR: 0.000029
Epoch: 040 | Train loss: 0.9931 | Train acc: 50.86% | Val loss: 0.9768 | Val acc: 51.80% | LR: 0.000029
Epoch: 041 | Train loss: 0.9914 | Train acc: 51.04% | Val loss: 0.9763 | Val acc: 51.72% | LR: 0.000029
Epoch: 042 | Train loss: 0.9934 | Train acc: 51.05% | Val loss: 0.9767 | Val acc: 51.50% | LR: 0.000028
Epoch: 043 | Train loss: 0.9952 | Train acc: 50.52% | Val loss: 0.9771 | Val acc: 51.43% | LR: 0.000028
Epoch: 044 | Train loss: 0.9930 | Train acc: 50.70% | Val loss: 0.9775 | Val acc: 51.26% | LR: 0.000028
Epoch: 045 | Train loss: 0.9939 | Train acc: 50.40% | Val loss: 0.9785 | Val acc: 51.02% | LR: 0.000028
Epoch: 046 | Train loss: 0.9922 | Train acc: 50.99% | Val loss: 0.9784 | Val acc: 51.02% | LR: 0.000027
Epoch: 047 | Train loss: 0.9917 | Train acc: 51.16% | Val loss: 0.9858 | Val acc: 50.81% | LR: 0.000027
Epoch: 048 | Train loss: 0.9927 | Train acc: 51.05% | Val loss: 1.0195 | Val acc: 50.93% | LR: 0.000027
Epoch: 049 | Train loss: 0.9939 | Train acc: 51.10% | Val loss: 0.9862 | Val acc: 50.70% | LR: 0.000026
Epoch: 050 | Train loss: 0.9920 | Train acc: 51.02% | Val loss: 0.9941 | Val acc: 51.16% | LR: 0.000026
Epoch: 051 | Train loss: 0.9944 | Train acc: 51.44% | Val loss: 0.9972 | Val acc: 51.01% | LR: 0.000026
Epoch: 052 | Train loss: 0.9944 | Train acc: 50.79% | Val loss: 1.0372 | Val acc: 51.15% | LR: 0.000025
Epoch: 053 | Train loss: 0.9953 | Train acc: 50.79% | Val loss: 0.9846 | Val acc: 51.11% | LR: 0.000025
Epoch: 054 | Train loss: 0.9965 | Train acc: 50.68% | Val loss: 0.9883 | Val acc: 51.05% | LR: 0.000025
Epoch: 055 | Train loss: 0.9915 | Train acc: 51.31% | Val loss: 0.9864 | Val acc: 51.05% | LR: 0.000024
Epoch: 056 | Train loss: 0.9918 | Train acc: 51.00% | Val loss: 0.9824 | Val acc: 51.21% | LR: 0.000024

[I 2025-09-23 17:10:58,838] Trial 51 finished with value: 0.5081791460514069 and parameters: {'lr': 3.485418452413821e-05, 'hidden_size': 76, 'dropout': 0.37312096727290633, 'weight_decay': 0.00015932463799620184}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9951 | Train acc: 50.69% | Val loss: 0.9914 | Val acc: 54.33% | LR: 0.000031
Epoch: 001 | Train loss: 0.9983 | Train acc: 50.26% | Val loss: 0.9919 | Val acc: 54.30% | LR: 0.000031
Epoch: 002 | Train loss: 0.9948 | Train acc: 50.41% | Val loss: 0.9907 | Val acc: 54.46% | LR: 0.000031
Epoch: 003 | Train loss: 0.9962 | Train acc: 50.51% | Val loss: 0.9911 | Val acc: 54.42% | LR: 0.000031
Epoch: 004 | Train loss: 0.9968 | Train acc: 50.22% | Val loss: 0.9905 | Val acc: 54.15% | LR: 0.000031
Epoch: 005 | Train loss: 0.9899 | Train acc: 50.86% | Val loss: 0.9902 | Val acc: 54.49% | LR: 0.000031
Epoch: 006 | Train loss: 0.9983 | Train acc: 50.00% | Val loss: 0.9898 | Val acc: 54.43% | LR: 0.000031
Epoch: 007 | Train loss: 0.9921 | Train acc: 50.78% | Val loss: 0.9895 | Val acc: 54.56% | LR: 0.000031
Epoch: 008 | Train loss: 0.9962 | Train acc: 50.37% | Val loss: 0.9891 | Val acc: 54.56% | LR: 0.000031
Epoch: 009 | Train loss: 0.9956 | Train acc: 50.31% | Val loss: 0.9886 | Val acc: 54.68% | LR: 0.000031
Epoch: 010 | Train loss: 1.2045 | Train acc: 51.04% | Val loss: 0.9884 | Val acc: 54.54% | LR: 0.000031
Epoch: 011 | Train loss: 0.9896 | Train acc: 50.75% | Val loss: 0.9879 | Val acc: 54.56% | LR: 0.000031
Epoch: 012 | Train loss: 0.9886 | Train acc: 50.92% | Val loss: 0.9874 | Val acc: 54.68% | LR: 0.000030
Epoch: 013 | Train loss: 0.9933 | Train acc: 50.53% | Val loss: 0.9873 | Val acc: 54.45% | LR: 0.000030
Epoch: 014 | Train loss: 0.9883 | Train acc: 50.92% | Val loss: 0.9865 | Val acc: 54.45% | LR: 0.000030
Epoch: 015 | Train loss: 0.9865 | Train acc: 50.93% | Val loss: 0.9859 | Val acc: 54.39% | LR: 0.000030
Epoch: 016 | Train loss: 0.9873 | Train acc: 51.04% | Val loss: 0.9856 | Val acc: 54.24% | LR: 0.000030
Epoch: 017 | Train loss: 0.9905 | Train acc: 50.72% | Val loss: 0.9851 | Val acc: 54.32% | LR: 0.000030
Epoch: 018 | Train loss: 0.9837 | Train acc: 51.07% | Val loss: 0.9847 | Val acc: 54.12% | LR: 0.000030
Epoch: 019 | Train loss: 0.9885 | Train acc: 51.11% | Val loss: 0.9843 | Val acc: 54.30% | LR: 0.000030
Epoch: 020 | Train loss: 0.9902 | Train acc: 50.86% | Val loss: 0.9831 | Val acc: 54.25% | LR: 0.000030
Epoch: 021 | Train loss: 0.9863 | Train acc: 51.13% | Val loss: 0.9820 | Val acc: 53.80% | LR: 0.000029
Epoch: 022 | Train loss: 0.9905 | Train acc: 50.76% | Val loss: 0.9808 | Val acc: 53.76% | LR: 0.000029
Epoch: 023 | Train loss: 0.9920 | Train acc: 50.67% | Val loss: 0.9798 | Val acc: 53.72% | LR: 0.000029
Epoch: 024 | Train loss: 0.9884 | Train acc: 50.77% | Val loss: 0.9787 | Val acc: 53.76% | LR: 0.000029
Epoch: 025 | Train loss: 0.9935 | Train acc: 51.05% | Val loss: 0.9778 | Val acc: 53.78% | LR: 0.000029
Epoch: 026 | Train loss: 1.0167 | Train acc: 50.61% | Val loss: 0.9769 | Val acc: 53.77% | LR: 0.000029
Epoch: 027 | Train loss: 1.0323 | Train acc: 50.32% | Val loss: 0.9765 | Val acc: 53.69% | LR: 0.000029
Epoch: 028 | Train loss: 1.0480 | Train acc: 50.23% | Val loss: 0.9764 | Val acc: 53.65% | LR: 0.000028
Epoch: 029 | Train loss: 1.0066 | Train acc: 50.42% | Val loss: 0.9760 | Val acc: 53.69% | LR: 0.000028
Epoch: 030 | Train loss: 0.9943 | Train acc: 50.97% | Val loss: 0.9757 | Val acc: 53.75% | LR: 0.000028
Epoch: 031 | Train loss: 0.9959 | Train acc: 51.14% | Val loss: 0.9751 | Val acc: 53.69% | LR: 0.000028
Epoch: 032 | Train loss: 1.0201 | Train acc: 50.78% | Val loss: 0.9748 | Val acc: 53.75% | LR: 0.000028
Epoch: 033 | Train loss: 1.0021 | Train acc: 50.97% | Val loss: 0.9743 | Val acc: 53.79% | LR: 0.000027
Epoch: 034 | Train loss: 0.9964 | Train acc: 50.90% | Val loss: 0.9738 | Val acc: 53.81% | LR: 0.000027
Epoch: 035 | Train loss: 1.0134 | Train acc: 50.75% | Val loss: 0.9728 | Val acc: 53.79% | LR: 0.000027
Epoch: 036 | Train loss: 1.0171 | Train acc: 51.00% | Val loss: 0.9722 | Val acc: 53.79% | LR: 0.000027
Epoch: 037 | Train loss: 1.0088 | Train acc: 50.52% | Val loss: 0.9713 | Val acc: 53.73% | LR: 0.000027
Epoch: 038 | Train loss: 1.0249 | Train acc: 50.32% | Val loss: 0.9712 | Val acc: 53.73% | LR: 0.000026
Epoch: 039 | Train loss: 1.0440 | Train acc: 51.21% | Val loss: 0.9712 | Val acc: 53.65% | LR: 0.000026
Epoch: 040 | Train loss: 1.0657 | Train acc: 51.27% | Val loss: 0.9710 | Val acc: 53.59% | LR: 0.000026
Epoch: 041 | Train loss: 1.0166 | Train acc: 50.36% | Val loss: 0.9709 | Val acc: 53.59% | LR: 0.000026
Epoch: 042 | Train loss: 0.9900 | Train acc: 51.08% | Val loss: 0.9699 | Val acc: 53.59% | LR: 0.000025
Epoch: 043 | Train loss: 0.9932 | Train acc: 50.77% | Val loss: 0.9693 | Val acc: 53.33% | LR: 0.000025
Epoch: 044 | Train loss: 0.9894 | Train acc: 51.21% | Val loss: 0.9693 | Val acc: 53.33% | LR: 0.000025
Epoch: 045 | Train loss: 0.9896 | Train acc: 51.02% | Val loss: 0.9697 | Val acc: 53.37% | LR: 0.000025
Epoch: 046 | Train loss: 0.9985 | Train acc: 50.24% | Val loss: 0.9697 | Val acc: 53.35% | LR: 0.000024
Epoch: 047 | Train loss: 0.9946 | Train acc: 50.52% | Val loss: 0.9703 | Val acc: 53.30% | LR: 0.000024
Epoch: 048 | Train loss: 0.9914 | Train acc: 50.83% | Val loss: 0.9708 | Val acc: 53.25% | LR: 0.000024
Epoch: 049 | Train loss: 0.9928 | Train acc: 50.71% | Val loss: 0.9712 | Val acc: 53.29% | LR: 0.000024
Epoch: 050 | Train loss: 0.9924 | Train acc: 50.62% | Val loss: 0.9713 | Val acc: 53.29% | LR: 0.000023
Epoch: 051 | Train loss: 0.9898 | Train acc: 50.97% | Val loss: 0.9711 | Val acc: 53.15% | LR: 0.000023
Epoch: 052 | Train loss: 0.9887 | Train acc: 50.98% | Val loss: 0.9715 | Val acc: 53.04% | LR: 0.000023
Epoch: 053 | Train loss: 0.9918 | Train acc: 50.91% | Val loss: 0.9713 | Val acc: 52.96% | LR: 0.000022
Epoch: 054 | Train loss: 0.9913 | Train acc: 50.85% | Val loss: 0.9718 | Val acc: 52.93% | LR: 0.000022
Epoch: 055 | Train loss: 0.9968 | Train acc: 50.30% | Val loss: 0.9720 | Val acc: 52.99% | LR: 0.000022
Epoch: 056 | Train loss: 0.9955 | Train acc: 50.39% | Val loss: 0.9723 | Val acc: 52.79% | LR: 0.000022
Epoch: 057 | Train loss: 0.9905 | Train acc: 51.02% | Val loss: 0.9728 | Val acc: 52.77% | LR: 0.000021
Epoch: 058 | Train loss: 0.9885 | Train acc: 51.39% | Val loss: 0.9731 | Val acc: 52.82% | LR: 0.000021
Epoch: 059 | Train loss: 0.9928 | Train acc: 50.84% | Val loss: 0.9738 | Val acc: 52.66% | LR: 0.000021
Epoch: 060 | Train loss: 0.9894 | Train acc: 51.11% | Val loss: 0.9741 | Val acc: 52.58% | LR: 0.000020
Epoch: 061 | Train loss: 0.9916 | Train acc: 50.93% | Val loss: 0.9743 | Val acc: 52.42% | LR: 0.000020

[I 2025-09-23 17:11:47,450] Trial 52 finished with value: 0.5215691328048706 and parameters: {'lr': 3.103285990336117e-05, 'hidden_size': 86, 'dropout': 0.14818682555474932, 'weight_decay': 0.0007304810928859148}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0005 | Train acc: 49.88% | Val loss: 0.9954 | Val acc: 54.20% | LR: 0.000059
Epoch: 001 | Train loss: 1.0008 | Train acc: 49.32% | Val loss: 0.9958 | Val acc: 54.14% | LR: 0.000059
Epoch: 002 | Train loss: 1.0003 | Train acc: 49.66% | Val loss: 0.9948 | Val acc: 54.55% | LR: 0.000059
Epoch: 003 | Train loss: 1.0213 | Train acc: 50.62% | Val loss: 0.9984 | Val acc: 54.25% | LR: 0.000059
Epoch: 004 | Train loss: 1.0001 | Train acc: 49.97% | Val loss: 0.9961 | Val acc: 54.17% | LR: 0.000059
Epoch: 005 | Train loss: 0.9994 | Train acc: 50.46% | Val loss: 0.9966 | Val acc: 54.14% | LR: 0.000059
Epoch: 006 | Train loss: 0.9992 | Train acc: 50.28% | Val loss: 0.9957 | Val acc: 54.13% | LR: 0.000059
Epoch: 007 | Train loss: 0.9988 | Train acc: 50.32% | Val loss: 0.9952 | Val acc: 54.14% | LR: 0.000059
Epoch: 008 | Train loss: 0.9988 | Train acc: 50.13% | Val loss: 0.9977 | Val acc: 53.98% | LR: 0.000059
Epoch: 009 | Train loss: 1.0017 | Train acc: 50.24% | Val loss: 0.9954 | Val acc: 54.25% | LR: 0.000058
Epoch: 010 | Train loss: 0.9967 | Train acc: 50.31% | Val loss: 0.9963 | Val acc: 54.43% | LR: 0.000058
Epoch: 011 | Train loss: 0.9939 | Train acc: 50.74% | Val loss: 0.9968 | Val acc: 54.39% | LR: 0.000058
Epoch: 012 | Train loss: 1.0025 | Train acc: 50.46% | Val loss: 0.9955 | Val acc: 54.08% | LR: 0.000058
Epoch: 013 | Train loss: 0.9949 | Train acc: 50.94% | Val loss: 0.9955 | Val acc: 53.89% | LR: 0.000058
Epoch: 014 | Train loss: 0.9977 | Train acc: 50.29% | Val loss: 0.9979 | Val acc: 53.84% | LR: 0.000058
Epoch: 015 | Train loss: 0.9967 | Train acc: 50.21% | Val loss: 0.9955 | Val acc: 53.83% | LR: 0.000057
Epoch: 016 | Train loss: 0.9941 | Train acc: 50.73% | Val loss: 0.9958 | Val acc: 54.06% | LR: 0.000057
Epoch: 017 | Train loss: 0.9920 | Train acc: 51.08% | Val loss: 0.9981 | Val acc: 54.10% | LR: 0.000057
Epoch: 018 | Train loss: 0.9987 | Train acc: 50.17% | Val loss: 0.9997 | Val acc: 53.98% | LR: 0.000057
Epoch: 019 | Train loss: 0.9967 | Train acc: 50.21% | Val loss: 0.9956 | Val acc: 54.08% | LR: 0.000057
Epoch: 020 | Train loss: 0.9983 | Train acc: 50.08% | Val loss: 1.0845 | Val acc: 53.55% | LR: 0.000056
Epoch: 021 | Train loss: 0.9921 | Train acc: 50.50% | Val loss: 0.9950 | Val acc: 54.07% | LR: 0.000056
Epoch: 022 | Train loss: 0.9923 | Train acc: 50.70% | Val loss: 0.9968 | Val acc: 53.83% | LR: 0.000056
Epoch: 023 | Train loss: 0.9952 | Train acc: 50.63% | Val loss: 1.0026 | Val acc: 53.54% | LR: 0.000055
Epoch: 024 | Train loss: 0.9952 | Train acc: 50.64% | Val loss: 1.0251 | Val acc: 53.37% | LR: 0.000055
Epoch: 025 | Train loss: 0.9933 | Train acc: 50.97% | Val loss: 0.9970 | Val acc: 53.29% | LR: 0.000055
Epoch: 026 | Train loss: 0.9886 | Train acc: 50.82% | Val loss: 1.0019 | Val acc: 53.31% | LR: 0.000055
Epoch: 027 | Train loss: 0.9894 | Train acc: 50.79% | Val loss: 0.9947 | Val acc: 53.53% | LR: 0.000054
Epoch: 028 | Train loss: 0.9961 | Train acc: 50.37% | Val loss: 0.9960 | Val acc: 54.01% | LR: 0.000054
Epoch: 029 | Train loss: 0.9898 | Train acc: 51.20% | Val loss: 1.0030 | Val acc: 53.77% | LR: 0.000054
Epoch: 030 | Train loss: 0.9958 | Train acc: 51.03% | Val loss: 0.9976 | Val acc: 53.96% | LR: 0.000053
Epoch: 031 | Train loss: 0.9933 | Train acc: 50.83% | Val loss: 0.9961 | Val acc: 54.01% | LR: 0.000053
Epoch: 032 | Train loss: 0.9948 | Train acc: 50.65% | Val loss: 0.9952 | Val acc: 53.95% | LR: 0.000052
Epoch: 033 | Train loss: 0.9919 | Train acc: 50.78% | Val loss: 0.9974 | Val acc: 53.73% | LR: 0.000052
Epoch: 034 | Train loss: 0.9990 | Train acc: 50.07% | Val loss: 1.0030 | Val acc: 53.43% | LR: 0.000052
Epoch: 035 | Train loss: 0.9948 | Train acc: 50.69% | Val loss: 0.9954 | Val acc: 54.05% | LR: 0.000051
Epoch: 036 | Train loss: 0.9958 | Train acc: 50.57% | Val loss: 0.9949 | Val acc: 54.36% | LR: 0.000051
Epoch: 037 | Train loss: 0.9962 | Train acc: 50.38% | Val loss: 0.9939 | Val acc: 54.48% | LR: 0.000050
Epoch: 038 | Train loss: 0.9933 | Train acc: 50.91% | Val loss: 0.9976 | Val acc: 54.36% | LR: 0.000050
Epoch: 039 | Train loss: 0.9926 | Train acc: 50.91% | Val loss: 1.0101 | Val acc: 54.32% | LR: 0.000049
Epoch: 040 | Train loss: 0.9882 | Train acc: 51.19% | Val loss: 0.9968 | Val acc: 54.18% | LR: 0.000049
Epoch: 041 | Train loss: 0.9904 | Train acc: 51.12% | Val loss: 0.9970 | Val acc: 54.30% | LR: 0.000049
Epoch: 042 | Train loss: 0.9958 | Train acc: 50.19% | Val loss: 0.9959 | Val acc: 54.13% | LR: 0.000048
Epoch: 043 | Train loss: 0.9931 | Train acc: 50.82% | Val loss: 0.9997 | Val acc: 54.36% | LR: 0.000048
Epoch: 044 | Train loss: 0.9890 | Train acc: 51.02% | Val loss: 0.9949 | Val acc: 54.26% | LR: 0.000047
Epoch: 045 | Train loss: 0.9944 | Train acc: 50.60% | Val loss: 0.9947 | Val acc: 54.50% | LR: 0.000047
Epoch: 046 | Train loss: 0.9948 | Train acc: 50.57% | Val loss: 0.9947 | Val acc: 54.43% | LR: 0.000046
Epoch: 047 | Train loss: 0.9923 | Train acc: 51.01% | Val loss: 0.9951 | Val acc: 54.28% | LR: 0.000046
Epoch: 048 | Train loss: 0.9979 | Train acc: 50.21% | Val loss: 0.9945 | Val acc: 54.13% | LR: 0.000045
Epoch: 049 | Train loss: 0.9995 | Train acc: 50.41% | Val loss: 0.9970 | Val acc: 53.97% | LR: 0.000045
Epoch: 050 | Train loss: 0.9951 | Train acc: 50.49% | Val loss: 0.9948 | Val acc: 53.91% | LR: 0.000044
Epoch: 051 | Train loss: 0.9918 | Train acc: 50.65% | Val loss: 0.9955 | Val acc: 53.84% | LR: 0.000043

[I 2025-09-23 17:12:33,068] Trial 53 finished with value: 0.5385611176490783 and parameters: {'lr': 5.906062106446906e-05, 'hidden_size': 90, 'dropout': 0.3200181420368652, 'weight_decay': 7.032292473417736e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9981 | Train acc: 50.70% | Val loss: 1.0041 | Val acc: 45.99% | LR: 0.000066
Epoch: 001 | Train loss: 0.9992 | Train acc: 50.43% | Val loss: 1.0042 | Val acc: 46.03% | LR: 0.000066
Epoch: 002 | Train loss: 0.9952 | Train acc: 50.69% | Val loss: 1.0042 | Val acc: 46.01% | LR: 0.000066
Epoch: 003 | Train loss: 0.9982 | Train acc: 50.29% | Val loss: 1.0039 | Val acc: 46.33% | LR: 0.000066
Epoch: 004 | Train loss: 0.9942 | Train acc: 50.85% | Val loss: 1.0034 | Val acc: 46.68% | LR: 0.000066
Epoch: 005 | Train loss: 0.9956 | Train acc: 50.60% | Val loss: 1.0034 | Val acc: 46.72% | LR: 0.000066
Epoch: 006 | Train loss: 0.9908 | Train acc: 51.11% | Val loss: 1.0037 | Val acc: 46.64% | LR: 0.000065
Epoch: 007 | Train loss: 0.9902 | Train acc: 51.05% | Val loss: 1.0029 | Val acc: 47.44% | LR: 0.000065
Epoch: 008 | Train loss: 0.9917 | Train acc: 50.81% | Val loss: 1.0027 | Val acc: 47.87% | LR: 0.000065
Epoch: 009 | Train loss: 0.9879 | Train acc: 51.18% | Val loss: 1.0028 | Val acc: 47.91% | LR: 0.000065
Epoch: 010 | Train loss: 0.9965 | Train acc: 50.47% | Val loss: 1.0021 | Val acc: 48.24% | LR: 0.000065
Epoch: 011 | Train loss: 0.9876 | Train acc: 51.03% | Val loss: 1.0015 | Val acc: 48.97% | LR: 0.000065
Epoch: 012 | Train loss: 0.9876 | Train acc: 51.29% | Val loss: 1.0015 | Val acc: 49.05% | LR: 0.000065
Epoch: 013 | Train loss: 0.9934 | Train acc: 50.76% | Val loss: 1.0011 | Val acc: 49.27% | LR: 0.000064
Epoch: 014 | Train loss: 0.9894 | Train acc: 50.85% | Val loss: 1.0003 | Val acc: 49.71% | LR: 0.000064
Epoch: 015 | Train loss: 0.9901 | Train acc: 50.83% | Val loss: 1.0006 | Val acc: 49.77% | LR: 0.000064
Epoch: 016 | Train loss: 0.9857 | Train acc: 51.03% | Val loss: 0.9996 | Val acc: 49.71% | LR: 0.000064
Epoch: 017 | Train loss: 0.9863 | Train acc: 50.93% | Val loss: 0.9970 | Val acc: 50.12% | LR: 0.000064
Epoch: 018 | Train loss: 0.9924 | Train acc: 50.54% | Val loss: 0.9936 | Val acc: 50.74% | LR: 0.000063
Epoch: 019 | Train loss: 0.9852 | Train acc: 50.98% | Val loss: 0.9909 | Val acc: 50.79% | LR: 0.000063
Epoch: 020 | Train loss: 0.9935 | Train acc: 50.45% | Val loss: 0.9910 | Val acc: 50.81% | LR: 0.000063
Epoch: 021 | Train loss: 0.9912 | Train acc: 50.53% | Val loss: 0.9905 | Val acc: 50.79% | LR: 0.000062
Epoch: 022 | Train loss: 0.9819 | Train acc: 51.16% | Val loss: 0.9909 | Val acc: 50.69% | LR: 0.000062
Epoch: 023 | Train loss: 0.9834 | Train acc: 51.07% | Val loss: 0.9905 | Val acc: 50.75% | LR: 0.000062
Epoch: 024 | Train loss: 0.9827 | Train acc: 50.98% | Val loss: 0.9906 | Val acc: 50.81% | LR: 0.000061
Epoch: 025 | Train loss: 0.9863 | Train acc: 50.89% | Val loss: 0.9921 | Val acc: 50.69% | LR: 0.000061
Epoch: 026 | Train loss: 0.9835 | Train acc: 51.01% | Val loss: 0.9936 | Val acc: 50.57% | LR: 0.000061
Epoch: 027 | Train loss: 0.9887 | Train acc: 50.72% | Val loss: 0.9927 | Val acc: 50.55% | LR: 0.000060
Epoch: 028 | Train loss: 0.9818 | Train acc: 51.03% | Val loss: 0.9958 | Val acc: 50.39% | LR: 0.000060
Epoch: 029 | Train loss: 0.9813 | Train acc: 51.16% | Val loss: 0.9962 | Val acc: 50.23% | LR: 0.000060
Epoch: 030 | Train loss: 0.9884 | Train acc: 50.68% | Val loss: 0.9970 | Val acc: 50.23% | LR: 0.000059
Epoch: 031 | Train loss: 0.9812 | Train acc: 51.02% | Val loss: 0.9987 | Val acc: 49.83% | LR: 0.000059
Epoch: 032 | Train loss: 0.9839 | Train acc: 50.83% | Val loss: 0.9970 | Val acc: 50.28% | LR: 0.000058
Epoch: 033 | Train loss: 0.9848 | Train acc: 50.76% | Val loss: 0.9972 | Val acc: 50.19% | LR: 0.000058
Epoch: 034 | Train loss: 0.9821 | Train acc: 50.94% | Val loss: 0.9956 | Val acc: 50.25% | LR: 0.000057
Epoch: 035 | Train loss: 0.9814 | Train acc: 51.06% | Val loss: 1.0029 | Val acc: 50.40% | LR: 0.000057
Epoch: 036 | Train loss: 0.9842 | Train acc: 50.98% | Val loss: 0.9924 | Val acc: 50.57% | LR: 0.000057
Epoch: 037 | Train loss: 0.9866 | Train acc: 50.72% | Val loss: 0.9937 | Val acc: 50.45% | LR: 0.000056
Epoch: 038 | Train loss: 0.9851 | Train acc: 50.81% | Val loss: 0.9940 | Val acc: 50.47% | LR: 0.000056
Epoch: 039 | Train loss: 0.9937 | Train acc: 50.27% | Val loss: 0.9940 | Val acc: 50.47% | LR: 0.000055
Epoch: 040 | Train loss: 0.9857 | Train acc: 50.89% | Val loss: 0.9941 | Val acc: 50.47% | LR: 0.000055
Epoch: 041 | Train loss: 0.9796 | Train acc: 50.97% | Val loss: 0.9948 | Val acc: 50.47% | LR: 0.000054
Epoch: 042 | Train loss: 0.9830 | Train acc: 51.04% | Val loss: 0.9974 | Val acc: 50.34% | LR: 0.000054
Epoch: 043 | Train loss: 0.9780 | Train acc: 51.28% | Val loss: 0.9977 | Val acc: 50.36% | LR: 0.000053
Epoch: 044 | Train loss: 0.9811 | Train acc: 51.10% | Val loss: 0.9976 | Val acc: 50.32% | LR: 0.000052
Epoch: 045 | Train loss: 0.9787 | Train acc: 51.28% | Val loss: 0.9990 | Val acc: 50.22% | LR: 0.000052
Epoch: 046 | Train loss: 0.9789 | Train acc: 51.19% | Val loss: 1.0000 | Val acc: 50.01% | LR: 0.000051
Epoch: 047 | Train loss: 0.9848 | Train acc: 50.84% | Val loss: 1.0005 | Val acc: 50.01% | LR: 0.000051
Epoch: 048 | Train loss: 0.9794 | Train acc: 51.19% | Val loss: 1.0018 | Val acc: 49.79% | LR: 0.000050
Epoch: 049 | Train loss: 0.9815 | Train acc: 51.09% | Val loss: 1.0013 | Val acc: 49.95% | LR: 0.000050
Epoch: 050 | Train loss: 0.9788 | Train acc: 51.22% | Val loss: 1.0023 | Val acc: 49.86% | LR: 0.000049
Epoch: 051 | Train loss: 0.9770 | Train acc: 51.27% | Val loss: 1.0038 | Val acc: 49.98% | LR: 0.000048
Epoch: 052 | Train loss: 0.9673 | Train acc: 51.87% | Val loss: 1.0048 | Val acc: 49.91% | LR: 0.000048
Epoch: 053 | Train loss: 0.9835 | Train acc: 50.78% | Val loss: 1.0058 | Val acc: 49.74% | LR: 0.000047
Epoch: 054 | Train loss: 0.9783 | Train acc: 51.19% | Val loss: 1.0074 | Val acc: 49.80% | LR: 0.000047
Epoch: 055 | Train loss: 0.9762 | Train acc: 51.39% | Val loss: 1.0265 | Val acc: 49.23% | LR: 0.000046
Epoch: 056 | Train loss: 0.9916 | Train acc: 50.64% | Val loss: 1.0117 | Val acc: 48.97% | LR: 0.000045
Epoch: 057 | Train loss: 0.9743 | Train acc: 51.43% | Val loss: 1.0122 | Val acc: 49.01% | LR: 0.000045
Epoch: 058 | Train loss: 0.9805 | Train acc: 51.16% | Val loss: 1.0128 | Val acc: 48.99% | LR: 0.000044
Epoch: 059 | Train loss: 0.9824 | Train acc: 51.00% | Val loss: 1.0140 | Val acc: 49.01% | LR: 0.000043
Epoch: 060 | Train loss: 0.9820 | Train acc: 51.08% | Val loss: 1.0143 | Val acc: 48.95% | LR: 0.000043
Epoch: 061 | Train loss: 0.9897 | Train acc: 50.62% | Val loss: 1.0133 | Val acc: 49.03% | LR: 0.000042
Epoch: 062 | Train loss: 0.9784 | Train acc: 51.16% | Val loss: 1.0135 | Val acc: 49.05% | LR: 0.000041
Epoch: 063 | Train loss: 0.9804 | Train acc: 51.06% | Val loss: 1.0132 | Val acc: 49.11% | LR: 0.000041
Epoch: 064 | Train loss: 0.9794 | Train acc: 51.16% | Val loss: 1.0137 | Val acc: 49.03% | LR: 0.000040
Epoch: 065 | Train loss: 0.9871 | Train acc: 50.65% | Val loss: 1.0135 | Val acc: 49.01% | LR: 0.000039
Epoch: 066 | Train loss: 0.9782 | Train acc: 51.28% | Val loss: 1.0132 | Val acc: 49.05% | LR: 0.000039
Epoch: 067 | Train loss: 0.9741 | Train acc: 51.45% | Val loss: 1.0144 | Val acc: 48.99% | LR: 0.000038
Epoch: 068 | Train loss: 0.9784 | Train acc: 51.27% | Val loss: 1.0148 | Val acc: 48.91% | LR: 0.000037
Epoch: 069 | Train loss: 0.9826 | Train acc: 50.92% | Val loss: 1.0158 | Val acc: 48.93% | LR: 0.000037
Epoch: 070 | Train loss: 0.9799 | Train acc: 51.11% | Val loss: 1.0175 | Val acc: 48.73% | LR: 0.000036
Epoch: 071 | Train loss: 0.9838 | Train acc: 50.84% | Val loss: 1.0171 | Val acc: 48.59% | LR: 0.000035
Epoch: 072 | Train loss: 0.9814 | Train acc: 51.01% | Val loss: 1.0187 | Val acc: 48.63% | LR: 0.000035
Epoch: 073 | Train loss: 0.9828 | Train acc: 51.01% | Val loss: 1.0186 | Val acc: 48.59% | LR: 0.000034

[I 2025-09-23 17:13:33,802] Trial 54 finished with value: 0.4856671988964081 and parameters: {'lr': 6.580659219813765e-05, 'hidden_size': 95, 'dropout': 0.35383592170709327, 'weight_decay': 6.91060856909784e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0035 | Train acc: 49.27% | Val loss: 1.0034 | Val acc: 47.15% | LR: 0.000087
Epoch: 001 | Train loss: 1.0004 | Train acc: 49.45% | Val loss: 1.0016 | Val acc: 45.72% | LR: 0.000087
Epoch: 002 | Train loss: 0.9995 | Train acc: 50.05% | Val loss: 1.0026 | Val acc: 45.67% | LR: 0.000087
Epoch: 003 | Train loss: 0.9983 | Train acc: 50.36% | Val loss: 1.0039 | Val acc: 46.00% | LR: 0.000087
Epoch: 004 | Train loss: 1.0095 | Train acc: 50.19% | Val loss: 1.0028 | Val acc: 45.96% | LR: 0.000087
Epoch: 005 | Train loss: 1.0020 | Train acc: 50.28% | Val loss: 1.0189 | Val acc: 45.78% | LR: 0.000087
Epoch: 006 | Train loss: 0.9982 | Train acc: 50.10% | Val loss: 1.0017 | Val acc: 46.32% | LR: 0.000087
Epoch: 007 | Train loss: 0.9973 | Train acc: 50.54% | Val loss: 1.0015 | Val acc: 46.56% | LR: 0.000087
Epoch: 008 | Train loss: 0.9952 | Train acc: 50.90% | Val loss: 1.0051 | Val acc: 48.72% | LR: 0.000087
Epoch: 009 | Train loss: 0.9957 | Train acc: 50.60% | Val loss: 0.9999 | Val acc: 50.65% | LR: 0.000086
Epoch: 010 | Train loss: 0.9945 | Train acc: 50.94% | Val loss: 1.0324 | Val acc: 50.60% | LR: 0.000086
Epoch: 011 | Train loss: 0.9890 | Train acc: 51.00% | Val loss: 1.0231 | Val acc: 50.23% | LR: 0.000086
Epoch: 012 | Train loss: 0.9886 | Train acc: 51.15% | Val loss: 1.0005 | Val acc: 49.48% | LR: 0.000086
Epoch: 013 | Train loss: 0.9866 | Train acc: 51.35% | Val loss: 1.0007 | Val acc: 48.79% | LR: 0.000085
Epoch: 014 | Train loss: 0.9910 | Train acc: 50.88% | Val loss: 1.0003 | Val acc: 49.02% | LR: 0.000085
Epoch: 015 | Train loss: 0.9915 | Train acc: 50.88% | Val loss: 0.9999 | Val acc: 49.70% | LR: 0.000085
Epoch: 016 | Train loss: 0.9902 | Train acc: 50.98% | Val loss: 0.9999 | Val acc: 49.65% | LR: 0.000085
Epoch: 017 | Train loss: 0.9896 | Train acc: 51.07% | Val loss: 0.9996 | Val acc: 49.79% | LR: 0.000084
Epoch: 018 | Train loss: 0.9912 | Train acc: 51.07% | Val loss: 0.9993 | Val acc: 49.99% | LR: 0.000084
Epoch: 019 | Train loss: 0.9911 | Train acc: 50.76% | Val loss: 0.9989 | Val acc: 50.59% | LR: 0.000084
Epoch: 020 | Train loss: 0.9901 | Train acc: 50.94% | Val loss: 0.9986 | Val acc: 50.57% | LR: 0.000083
Epoch: 021 | Train loss: 0.9956 | Train acc: 50.53% | Val loss: 0.9980 | Val acc: 50.54% | LR: 0.000083
Epoch: 022 | Train loss: 0.9942 | Train acc: 50.63% | Val loss: 0.9976 | Val acc: 50.69% | LR: 0.000082
Epoch: 023 | Train loss: 0.9869 | Train acc: 51.44% | Val loss: 0.9972 | Val acc: 50.89% | LR: 0.000082
Epoch: 024 | Train loss: 0.9922 | Train acc: 50.66% | Val loss: 0.9967 | Val acc: 50.89% | LR: 0.000082
Epoch: 025 | Train loss: 0.9934 | Train acc: 50.62% | Val loss: 0.9959 | Val acc: 51.04% | LR: 0.000081
Epoch: 026 | Train loss: 0.9896 | Train acc: 51.11% | Val loss: 0.9951 | Val acc: 51.12% | LR: 0.000081
Epoch: 027 | Train loss: 0.9929 | Train acc: 50.83% | Val loss: 0.9947 | Val acc: 51.22% | LR: 0.000080
Epoch: 028 | Train loss: 0.9903 | Train acc: 50.91% | Val loss: 0.9933 | Val acc: 51.26% | LR: 0.000080
Epoch: 029 | Train loss: 0.9915 | Train acc: 50.64% | Val loss: 0.9914 | Val acc: 51.54% | LR: 0.000079
Epoch: 030 | Train loss: 0.9934 | Train acc: 50.85% | Val loss: 0.9910 | Val acc: 51.31% | LR: 0.000079
Epoch: 031 | Train loss: 0.9875 | Train acc: 50.92% | Val loss: 0.9887 | Val acc: 51.56% | LR: 0.000078
Epoch: 032 | Train loss: 0.9891 | Train acc: 50.92% | Val loss: 0.9875 | Val acc: 51.58% | LR: 0.000077
Epoch: 033 | Train loss: 0.9845 | Train acc: 51.03% | Val loss: 0.9834 | Val acc: 52.05% | LR: 0.000077
Epoch: 034 | Train loss: 0.9874 | Train acc: 50.89% | Val loss: 0.9805 | Val acc: 52.32% | LR: 0.000076
Epoch: 035 | Train loss: 0.9871 | Train acc: 51.08% | Val loss: 0.9803 | Val acc: 52.24% | LR: 0.000076
Epoch: 036 | Train loss: 0.9807 | Train acc: 51.34% | Val loss: 0.9810 | Val acc: 52.08% | LR: 0.000075
Epoch: 037 | Train loss: 0.9886 | Train acc: 50.72% | Val loss: 0.9815 | Val acc: 51.76% | LR: 0.000074
Epoch: 038 | Train loss: 0.9869 | Train acc: 50.88% | Val loss: 0.9813 | Val acc: 51.74% | LR: 0.000074
Epoch: 039 | Train loss: 0.9938 | Train acc: 50.21% | Val loss: 0.9831 | Val acc: 51.53% | LR: 0.000073
Epoch: 040 | Train loss: 0.9850 | Train acc: 50.84% | Val loss: 0.9843 | Val acc: 51.37% | LR: 0.000072
Epoch: 041 | Train loss: 0.9855 | Train acc: 51.07% | Val loss: 0.9846 | Val acc: 51.45% | LR: 0.000072
Epoch: 042 | Train loss: 0.9915 | Train acc: 50.56% | Val loss: 0.9863 | Val acc: 51.20% | LR: 0.000071
Epoch: 043 | Train loss: 0.9836 | Train acc: 51.13% | Val loss: 0.9873 | Val acc: 50.96% | LR: 0.000070
Epoch: 044 | Train loss: 0.9785 | Train acc: 51.45% | Val loss: 0.9869 | Val acc: 51.04% | LR: 0.000070
Epoch: 045 | Train loss: 0.9767 | Train acc: 51.54% | Val loss: 0.9878 | Val acc: 50.92% | LR: 0.000069
Epoch: 046 | Train loss: 0.9893 | Train acc: 50.73% | Val loss: 0.9881 | Val acc: 50.67% | LR: 0.000068
Epoch: 047 | Train loss: 0.9761 | Train acc: 51.51% | Val loss: 0.9890 | Val acc: 50.93% | LR: 0.000067
Epoch: 048 | Train loss: 0.9836 | Train acc: 51.06% | Val loss: 0.9891 | Val acc: 50.81% | LR: 0.000066
Epoch: 049 | Train loss: 0.9826 | Train acc: 50.98% | Val loss: 0.9897 | Val acc: 50.89% | LR: 0.000066
Epoch: 050 | Train loss: 0.9789 | Train acc: 51.24% | Val loss: 0.9907 | Val acc: 50.77% | LR: 0.000065
Epoch: 051 | Train loss: 0.9844 | Train acc: 50.96% | Val loss: 0.9907 | Val acc: 50.78% | LR: 0.000064
Epoch: 052 | Train loss: 0.9831 | Train acc: 50.97% | Val loss: 0.9906 | Val acc: 50.82% | LR: 0.000063
Epoch: 053 | Train loss: 0.9862 | Train acc: 50.98% | Val loss: 0.9911 | Val acc: 50.93% | LR: 0.000063
Epoch: 054 | Train loss: 0.9852 | Train acc: 50.96% | Val loss: 0.9908 | Val acc: 50.70% | LR: 0.000062
Epoch: 055 | Train loss: 0.9806 | Train acc: 51.13% | Val loss: 0.9924 | Val acc: 50.43% | LR: 0.000061
Epoch: 056 | Train loss: 0.9860 | Train acc: 50.83% | Val loss: 0.9929 | Val acc: 50.30% | LR: 0.000060
Epoch: 057 | Train loss: 0.9844 | Train acc: 50.91% | Val loss: 0.9932 | Val acc: 49.92% | LR: 0.000059
Epoch: 058 | Train loss: 0.9804 | Train acc: 51.10% | Val loss: 0.9952 | Val acc: 49.97% | LR: 0.000058
Epoch: 059 | Train loss: 0.9783 | Train acc: 51.38% | Val loss: 0.9962 | Val acc: 49.95% | LR: 0.000057
Epoch: 060 | Train loss: 0.9759 | Train acc: 51.44% | Val loss: 0.9978 | Val acc: 49.86% | LR: 0.000057
Epoch: 061 | Train loss: 0.9848 | Train acc: 50.84% | Val loss: 0.9986 | Val acc: 49.74% | LR: 0.000056
Epoch: 062 | Train loss: 0.9827 | Train acc: 50.93% | Val loss: 0.9985 | Val acc: 49.65% | LR: 0.000055
Epoch: 063 | Train loss: 0.9927 | Train acc: 50.30% | Val loss: 0.9978 | Val acc: 49.74% | LR: 0.000054
Epoch: 064 | Train loss: 0.9866 | Train acc: 50.70% | Val loss: 0.9991 | Val acc: 49.53% | LR: 0.000053
Epoch: 065 | Train loss: 0.9784 | Train acc: 51.22% | Val loss: 1.0006 | Val acc: 49.49% | LR: 0.000052
Epoch: 066 | Train loss: 0.9772 | Train acc: 51.51% | Val loss: 1.0012 | Val acc: 49.41% | LR: 0.000051
Epoch: 067 | Train loss: 0.9848 | Train acc: 50.81% | Val loss: 1.0025 | Val acc: 49.39% | LR: 0.000050
Epoch: 068 | Train loss: 0.9763 | Train acc: 51.49% | Val loss: 1.0029 | Val acc: 49.35% | LR: 0.000050
Epoch: 069 | Train loss: 0.9884 | Train acc: 50.61% | Val loss: 1.0041 | Val acc: 49.31% | LR: 0.000049
Epoch: 070 | Train loss: 0.9806 | Train acc: 51.10% | Val loss: 1.0071 | Val acc: 49.39% | LR: 0.000048
Epoch: 071 | Train loss: 0.9816 | Train acc: 51.10% | Val loss: 1.0080 | Val acc: 49.29% | LR: 0.000047
Epoch: 072 | Train loss: 0.9811 | Train acc: 51.11% | Val loss: 1.0080 | Val acc: 49.21% | LR: 0.000046
Epoch: 073 | Train loss: 0.9868 | Train acc: 50.74% | Val loss: 1.0082 | Val acc: 49.31% | LR: 0.000045
Epoch: 074 | Train loss: 0.9808 | Train acc: 51.20% | Val loss: 1.0098 | Val acc: 49.25% | LR: 0.000044
Epoch: 075 | Train loss: 0.9812 | Train acc: 51.12% | Val loss: 1.0113 | Val acc: 49.25% | LR: 0.000043
Epoch: 076 | Train loss: 0.9841 | Train acc: 50.94% | Val loss: 1.0099 | Val acc: 49.02% | LR: 0.000042
Epoch: 077 | Train loss: 0.9788 | Train acc: 51.31% | Val loss: 1.0104 | Val acc: 49.25% | LR: 0.000041
Epoch: 078 | Train loss: 0.9727 | Train acc: 51.66% | Val loss: 1.0127 | Val acc: 49.25% | LR: 0.000041
Epoch: 079 | Train loss: 0.9806 | Train acc: 51.14% | Val loss: 1.0126 | Val acc: 49.29% | LR: 0.000040
Epoch: 080 | Train loss: 0.9834 | Train acc: 50.94% | Val loss: 1.0128 | Val acc: 49.23% | LR: 0.000039
Epoch: 081 | Train loss: 0.9865 | Train acc: 50.77% | Val loss: 1.0142 | Val acc: 48.95% | LR: 0.000038
Epoch: 082 | Train loss: 0.9754 | Train acc: 51.53% | Val loss: 1.0153 | Val acc: 48.95% | LR: 0.000037
Epoch: 083 | Train loss: 0.9804 | Train acc: 51.06% | Val loss: 1.0171 | Val acc: 48.89% | LR: 0.000036

[I 2025-09-23 17:14:56,862] Trial 55 finished with value: 0.4869063436985016 and parameters: {'lr': 8.728794534111601e-05, 'hidden_size': 223, 'dropout': 0.321658334332196, 'weight_decay': 2.5139149397769517e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0001 | Train acc: 49.81% | Val loss: 1.0019 | Val acc: 45.93% | LR: 0.000047
Epoch: 001 | Train loss: 0.9966 | Train acc: 50.59% | Val loss: 1.0013 | Val acc: 47.00% | LR: 0.000047
Epoch: 002 | Train loss: 0.9973 | Train acc: 50.80% | Val loss: 1.0017 | Val acc: 46.93% | LR: 0.000047
Epoch: 003 | Train loss: 0.9930 | Train acc: 51.09% | Val loss: 1.0014 | Val acc: 47.56% | LR: 0.000047
Epoch: 004 | Train loss: 0.9958 | Train acc: 50.73% | Val loss: 1.0005 | Val acc: 48.80% | LR: 0.000047
Epoch: 005 | Train loss: 0.9951 | Train acc: 50.69% | Val loss: 0.9998 | Val acc: 49.63% | LR: 0.000047
Epoch: 006 | Train loss: 0.9933 | Train acc: 50.78% | Val loss: 0.9995 | Val acc: 49.65% | LR: 0.000047
Epoch: 007 | Train loss: 0.9871 | Train acc: 51.42% | Val loss: 0.9989 | Val acc: 49.88% | LR: 0.000046
Epoch: 008 | Train loss: 0.9907 | Train acc: 51.11% | Val loss: 0.9982 | Val acc: 50.04% | LR: 0.000046
Epoch: 009 | Train loss: 0.9885 | Train acc: 51.25% | Val loss: 0.9966 | Val acc: 50.41% | LR: 0.000046
Epoch: 010 | Train loss: 0.9953 | Train acc: 50.55% | Val loss: 0.9941 | Val acc: 50.71% | LR: 0.000046
Epoch: 011 | Train loss: 0.9907 | Train acc: 50.97% | Val loss: 0.9915 | Val acc: 51.05% | LR: 0.000046
Epoch: 012 | Train loss: 0.9839 | Train acc: 51.32% | Val loss: 0.9891 | Val acc: 51.33% | LR: 0.000046
Epoch: 013 | Train loss: 0.9875 | Train acc: 50.87% | Val loss: 0.9843 | Val acc: 51.80% | LR: 0.000046
Epoch: 014 | Train loss: 0.9891 | Train acc: 50.62% | Val loss: 0.9832 | Val acc: 51.80% | LR: 0.000046
Epoch: 015 | Train loss: 0.9793 | Train acc: 51.42% | Val loss: 0.9838 | Val acc: 51.69% | LR: 0.000046
Epoch: 016 | Train loss: 0.9806 | Train acc: 51.30% | Val loss: 0.9866 | Val acc: 51.07% | LR: 0.000045
Epoch: 017 | Train loss: 0.9836 | Train acc: 50.96% | Val loss: 0.9868 | Val acc: 51.05% | LR: 0.000045
Epoch: 018 | Train loss: 0.9843 | Train acc: 50.96% | Val loss: 0.9883 | Val acc: 50.81% | LR: 0.000045
Epoch: 019 | Train loss: 0.9888 | Train acc: 50.62% | Val loss: 0.9888 | Val acc: 50.75% | LR: 0.000045
Epoch: 020 | Train loss: 0.9863 | Train acc: 50.79% | Val loss: 0.9888 | Val acc: 50.85% | LR: 0.000045
Epoch: 021 | Train loss: 0.9832 | Train acc: 51.08% | Val loss: 0.9904 | Val acc: 50.66% | LR: 0.000044
Epoch: 022 | Train loss: 0.9830 | Train acc: 50.91% | Val loss: 0.9894 | Val acc: 50.75% | LR: 0.000044
Epoch: 023 | Train loss: 0.9846 | Train acc: 51.19% | Val loss: 0.9909 | Val acc: 50.68% | LR: 0.000044
Epoch: 024 | Train loss: 0.9877 | Train acc: 50.58% | Val loss: 0.9914 | Val acc: 50.76% | LR: 0.000044
Epoch: 025 | Train loss: 0.9953 | Train acc: 50.21% | Val loss: 0.9916 | Val acc: 50.66% | LR: 0.000043
Epoch: 026 | Train loss: 0.9858 | Train acc: 50.73% | Val loss: 0.9924 | Val acc: 50.65% | LR: 0.000043
Epoch: 027 | Train loss: 0.9905 | Train acc: 50.54% | Val loss: 0.9947 | Val acc: 50.49% | LR: 0.000043
Epoch: 028 | Train loss: 0.9746 | Train acc: 51.69% | Val loss: 0.9942 | Val acc: 50.50% | LR: 0.000043
Epoch: 029 | Train loss: 0.9767 | Train acc: 51.57% | Val loss: 0.9950 | Val acc: 50.45% | LR: 0.000042
Epoch: 030 | Train loss: 0.9839 | Train acc: 50.95% | Val loss: 1.0093 | Val acc: 50.45% | LR: 0.000042
Epoch: 031 | Train loss: 0.9887 | Train acc: 50.60% | Val loss: 0.9963 | Val acc: 50.36% | LR: 0.000042
Epoch: 032 | Train loss: 0.9925 | Train acc: 50.25% | Val loss: 0.9975 | Val acc: 50.00% | LR: 0.000042
Epoch: 033 | Train loss: 0.9781 | Train acc: 51.15% | Val loss: 0.9990 | Val acc: 49.80% | LR: 0.000041
Epoch: 034 | Train loss: 0.9862 | Train acc: 50.81% | Val loss: 0.9994 | Val acc: 49.78% | LR: 0.000041
Epoch: 035 | Train loss: 0.9822 | Train acc: 51.26% | Val loss: 1.0008 | Val acc: 49.68% | LR: 0.000041
Epoch: 036 | Train loss: 0.9796 | Train acc: 51.18% | Val loss: 0.9999 | Val acc: 49.74% | LR: 0.000040
Epoch: 037 | Train loss: 0.9819 | Train acc: 50.64% | Val loss: 1.0010 | Val acc: 49.70% | LR: 0.000040
Epoch: 038 | Train loss: 0.9873 | Train acc: 50.66% | Val loss: 1.0023 | Val acc: 49.54% | LR: 0.000040
Epoch: 039 | Train loss: 0.9864 | Train acc: 50.87% | Val loss: 1.0031 | Val acc: 49.39% | LR: 0.000039
Epoch: 040 | Train loss: 0.9780 | Train acc: 51.57% | Val loss: 1.0060 | Val acc: 49.40% | LR: 0.000039
Epoch: 041 | Train loss: 0.9832 | Train acc: 51.32% | Val loss: 1.0039 | Val acc: 49.27% | LR: 0.000038
Epoch: 042 | Train loss: 0.9859 | Train acc: 50.72% | Val loss: 1.0068 | Val acc: 49.48% | LR: 0.000038
Epoch: 043 | Train loss: 0.9853 | Train acc: 50.46% | Val loss: 1.0073 | Val acc: 49.28% | LR: 0.000038
Epoch: 044 | Train loss: 0.9711 | Train acc: 51.86% | Val loss: 1.0101 | Val acc: 48.82% | LR: 0.000037
Epoch: 045 | Train loss: 0.9842 | Train acc: 50.52% | Val loss: 1.0111 | Val acc: 48.72% | LR: 0.000037
Epoch: 046 | Train loss: 0.9790 | Train acc: 51.06% | Val loss: 1.0117 | Val acc: 48.72% | LR: 0.000037
Epoch: 047 | Train loss: 0.9815 | Train acc: 51.33% | Val loss: 1.0116 | Val acc: 48.76% | LR: 0.000036
Epoch: 048 | Train loss: 0.9820 | Train acc: 50.98% | Val loss: 1.0106 | Val acc: 49.00% | LR: 0.000036
Epoch: 049 | Train loss: 0.9794 | Train acc: 51.43% | Val loss: 1.0090 | Val acc: 49.04% | LR: 0.000035
Epoch: 050 | Train loss: 0.9828 | Train acc: 51.08% | Val loss: 1.0141 | Val acc: 48.90% | LR: 0.000035
Epoch: 051 | Train loss: 0.9822 | Train acc: 51.06% | Val loss: 1.0134 | Val acc: 48.68% | LR: 0.000035
Epoch: 052 | Train loss: 0.9769 | Train acc: 50.99% | Val loss: 1.0141 | Val acc: 48.66% | LR: 0.000034
Epoch: 053 | Train loss: 0.9795 | Train acc: 51.13% | Val loss: 1.0129 | Val acc: 48.80% | LR: 0.000034
Epoch: 054 | Train loss: 0.9848 | Train acc: 50.65% | Val loss: 1.0142 | Val acc: 48.89% | LR: 0.000033
Epoch: 055 | Train loss: 0.9807 | Train acc: 51.71% | Val loss: 1.0147 | Val acc: 48.62% | LR: 0.000033
Epoch: 056 | Train loss: 0.9835 | Train acc: 51.52% | Val loss: 1.0123 | Val acc: 48.95% | LR: 0.000032
Epoch: 057 | Train loss: 0.9800 | Train acc: 51.66% | Val loss: 1.0093 | Val acc: 48.88% | LR: 0.000032
Epoch: 058 | Train loss: 0.9770 | Train acc: 51.08% | Val loss: 1.0085 | Val acc: 48.98% | LR: 0.000031
Epoch: 059 | Train loss: 0.9821 | Train acc: 51.15% | Val loss: 1.0087 | Val acc: 48.96% | LR: 0.000031
Epoch: 060 | Train loss: 0.9790 | Train acc: 51.13% | Val loss: 1.0128 | Val acc: 48.90% | LR: 0.000031
Epoch: 061 | Train loss: 0.9819 | Train acc: 50.79% | Val loss: 1.0087 | Val acc: 48.84% | LR: 0.000030
Epoch: 062 | Train loss: 0.9784 | Train acc: 51.05% | Val loss: 1.0078 | Val acc: 49.12% | LR: 0.000030

[I 2025-09-23 17:16:38,000] Trial 56 finished with value: 0.4910174608230591 and parameters: {'lr': 4.680316378841505e-05, 'hidden_size': 165, 'dropout': 0.2529782390352693, 'weight_decay': 3.3982164869661484e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0014 | Train acc: 49.83% | Val loss: 0.9933 | Val acc: 54.01% | LR: 0.000138
Epoch: 001 | Train loss: 0.9989 | Train acc: 50.50% | Val loss: 0.9940 | Val acc: 54.05% | LR: 0.000138
Epoch: 002 | Train loss: 0.9977 | Train acc: 50.52% | Val loss: 0.9949 | Val acc: 54.05% | LR: 0.000138
Epoch: 003 | Train loss: 0.9967 | Train acc: 50.80% | Val loss: 0.9951 | Val acc: 54.05% | LR: 0.000138
Epoch: 004 | Train loss: 0.9991 | Train acc: 50.01% | Val loss: 0.9943 | Val acc: 54.05% | LR: 0.000138
Epoch: 005 | Train loss: 0.9952 | Train acc: 50.45% | Val loss: 0.9943 | Val acc: 54.05% | LR: 0.000138
Epoch: 006 | Train loss: 0.9930 | Train acc: 50.72% | Val loss: 0.9942 | Val acc: 54.05% | LR: 0.000137
Epoch: 007 | Train loss: 0.9914 | Train acc: 50.80% | Val loss: 0.9936 | Val acc: 54.22% | LR: 0.000137
Epoch: 008 | Train loss: 0.9949 | Train acc: 50.41% | Val loss: 0.9923 | Val acc: 54.36% | LR: 0.000137
Epoch: 009 | Train loss: 0.9898 | Train acc: 50.61% | Val loss: 0.9908 | Val acc: 54.34% | LR: 0.000137
Epoch: 010 | Train loss: 0.9894 | Train acc: 50.83% | Val loss: 0.9893 | Val acc: 54.51% | LR: 0.000136
Epoch: 011 | Train loss: 0.9938 | Train acc: 50.57% | Val loss: 0.9877 | Val acc: 54.06% | LR: 0.000136
Epoch: 012 | Train loss: 0.9908 | Train acc: 50.86% | Val loss: 0.9846 | Val acc: 54.35% | LR: 0.000136
Epoch: 013 | Train loss: 0.9898 | Train acc: 50.64% | Val loss: 0.9781 | Val acc: 54.27% | LR: 0.000135
Epoch: 014 | Train loss: 0.9897 | Train acc: 50.79% | Val loss: 0.9710 | Val acc: 53.92% | LR: 0.000135
Epoch: 015 | Train loss: 0.9883 | Train acc: 50.75% | Val loss: 0.9702 | Val acc: 53.83% | LR: 0.000134
Epoch: 016 | Train loss: 0.9795 | Train acc: 51.27% | Val loss: 0.9694 | Val acc: 53.77% | LR: 0.000134
Epoch: 017 | Train loss: 0.9806 | Train acc: 51.50% | Val loss: 0.9704 | Val acc: 53.54% | LR: 0.000133
Epoch: 018 | Train loss: 0.9773 | Train acc: 51.46% | Val loss: 0.9701 | Val acc: 53.26% | LR: 0.000133
Epoch: 019 | Train loss: 0.9946 | Train acc: 50.24% | Val loss: 0.9787 | Val acc: 53.17% | LR: 0.000132
Epoch: 020 | Train loss: 0.9890 | Train acc: 50.66% | Val loss: 0.9695 | Val acc: 53.59% | LR: 0.000132
Epoch: 021 | Train loss: 0.9850 | Train acc: 50.84% | Val loss: 0.9754 | Val acc: 53.14% | LR: 0.000131
Epoch: 022 | Train loss: 0.9809 | Train acc: 51.27% | Val loss: 0.9797 | Val acc: 52.76% | LR: 0.000130
Epoch: 023 | Train loss: 0.9813 | Train acc: 51.22% | Val loss: 0.9822 | Val acc: 52.68% | LR: 0.000130
Epoch: 024 | Train loss: 0.9885 | Train acc: 50.81% | Val loss: 0.9788 | Val acc: 51.83% | LR: 0.000129
Epoch: 025 | Train loss: 0.9878 | Train acc: 50.92% | Val loss: 0.9966 | Val acc: 51.49% | LR: 0.000128
Epoch: 026 | Train loss: 0.9912 | Train acc: 50.47% | Val loss: 0.9941 | Val acc: 51.75% | LR: 0.000128
Epoch: 027 | Train loss: 0.9893 | Train acc: 50.93% | Val loss: 0.9815 | Val acc: 51.56% | LR: 0.000127
Epoch: 028 | Train loss: 0.9894 | Train acc: 50.47% | Val loss: 0.9769 | Val acc: 51.31% | LR: 0.000126
Epoch: 029 | Train loss: 0.9780 | Train acc: 51.29% | Val loss: 1.0028 | Val acc: 51.55% | LR: 0.000125
Epoch: 030 | Train loss: 0.9826 | Train acc: 51.07% | Val loss: 1.0539 | Val acc: 51.57% | LR: 0.000124
Epoch: 031 | Train loss: 0.9884 | Train acc: 50.90% | Val loss: 0.9784 | Val acc: 51.22% | LR: 0.000123
Epoch: 032 | Train loss: 0.9766 | Train acc: 51.40% | Val loss: 0.9760 | Val acc: 51.30% | LR: 0.000122
Epoch: 033 | Train loss: 0.9901 | Train acc: 50.44% | Val loss: 1.0849 | Val acc: 51.59% | LR: 0.000122
Epoch: 034 | Train loss: 0.9824 | Train acc: 50.94% | Val loss: 0.9742 | Val acc: 51.54% | LR: 0.000121
Epoch: 035 | Train loss: 0.9894 | Train acc: 50.44% | Val loss: 0.9704 | Val acc: 51.63% | LR: 0.000120
Epoch: 036 | Train loss: 1.0145 | Train acc: 50.60% | Val loss: 0.9696 | Val acc: 51.79% | LR: 0.000119
Epoch: 037 | Train loss: 0.9830 | Train acc: 51.02% | Val loss: 0.9712 | Val acc: 51.40% | LR: 0.000118
Epoch: 038 | Train loss: 0.9812 | Train acc: 50.94% | Val loss: 0.9788 | Val acc: 51.69% | LR: 0.000117
Epoch: 039 | Train loss: 0.9905 | Train acc: 50.54% | Val loss: 0.9729 | Val acc: 51.40% | LR: 0.000116
Epoch: 040 | Train loss: 0.9763 | Train acc: 51.41% | Val loss: 0.9716 | Val acc: 51.34% | LR: 0.000114
Epoch: 041 | Train loss: 0.9811 | Train acc: 51.06% | Val loss: 0.9793 | Val acc: 51.26% | LR: 0.000113
Epoch: 042 | Train loss: 0.9763 | Train acc: 51.30% | Val loss: 0.9720 | Val acc: 51.51% | LR: 0.000112
Epoch: 043 | Train loss: 0.9853 | Train acc: 50.69% | Val loss: 0.9709 | Val acc: 51.53% | LR: 0.000111
Epoch: 044 | Train loss: 0.9779 | Train acc: 51.21% | Val loss: 0.9785 | Val acc: 51.06% | LR: 0.000110
Epoch: 045 | Train loss: 0.9848 | Train acc: 50.70% | Val loss: 0.9838 | Val acc: 51.20% | LR: 0.000109
Epoch: 046 | Train loss: 0.9848 | Train acc: 50.59% | Val loss: 0.9707 | Val acc: 51.46% | LR: 0.000108
Epoch: 047 | Train loss: 0.9872 | Train acc: 50.60% | Val loss: 0.9744 | Val acc: 51.22% | LR: 0.000106
Epoch: 048 | Train loss: 0.9794 | Train acc: 51.12% | Val loss: 0.9753 | Val acc: 51.18% | LR: 0.000105
Epoch: 049 | Train loss: 0.9898 | Train acc: 50.59% | Val loss: 0.9789 | Val acc: 51.30% | LR: 0.000104
Epoch: 050 | Train loss: 1.0215 | Train acc: 50.57% | Val loss: 0.9704 | Val acc: 51.49% | LR: 0.000103
Epoch: 051 | Train loss: 0.9831 | Train acc: 51.10% | Val loss: 0.9716 | Val acc: 51.36% | LR: 0.000101
Epoch: 052 | Train loss: 0.9827 | Train acc: 51.06% | Val loss: 0.9714 | Val acc: 51.36% | LR: 0.000100
Epoch: 053 | Train loss: 0.9842 | Train acc: 50.81% | Val loss: 0.9717 | Val acc: 51.42% | LR: 0.000099
Epoch: 054 | Train loss: 0.9850 | Train acc: 50.61% | Val loss: 0.9750 | Val acc: 51.35% | LR: 0.000098
Epoch: 055 | Train loss: 0.9834 | Train acc: 50.90% | Val loss: 0.9683 | Val acc: 51.61% | LR: 0.000096
Epoch: 056 | Train loss: 0.9848 | Train acc: 50.76% | Val loss: 0.9669 | Val acc: 51.91% | LR: 0.000095
Epoch: 057 | Train loss: 0.9816 | Train acc: 50.99% | Val loss: 0.9719 | Val acc: 51.25% | LR: 0.000094
Epoch: 058 | Train loss: 0.9870 | Train acc: 50.47% | Val loss: 0.9725 | Val acc: 51.26% | LR: 0.000092
Epoch: 059 | Train loss: 0.9854 | Train acc: 50.74% | Val loss: 0.9723 | Val acc: 51.20% | LR: 0.000091

[I 2025-09-23 17:17:33,490] Trial 57 finished with value: 0.5140864849090576 and parameters: {'lr': 0.00013820764754834773, 'hidden_size': 103, 'dropout': 0.2947635358249325, 'weight_decay': 9.799725613464171e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0078 | Train acc: 49.59% | Val loss: 0.9985 | Val acc: 53.91% | LR: 0.000025
Epoch: 001 | Train loss: 1.0334 | Train acc: 49.27% | Val loss: 0.9990 | Val acc: 53.75% | LR: 0.000025
Epoch: 002 | Train loss: 1.0080 | Train acc: 49.59% | Val loss: 0.9965 | Val acc: 53.99% | LR: 0.000024
Epoch: 003 | Train loss: 1.0103 | Train acc: 50.14% | Val loss: 1.0050 | Val acc: 54.15% | LR: 0.000024
Epoch: 004 | Train loss: 1.0004 | Train acc: 50.36% | Val loss: 0.9975 | Val acc: 54.01% | LR: 0.000024
Epoch: 005 | Train loss: 1.1508 | Train acc: 49.59% | Val loss: 1.0092 | Val acc: 53.79% | LR: 0.000024
Epoch: 006 | Train loss: 1.0007 | Train acc: 49.44% | Val loss: 1.0188 | Val acc: 53.56% | LR: 0.000024
Epoch: 007 | Train loss: 1.0006 | Train acc: 49.91% | Val loss: 1.0248 | Val acc: 53.36% | LR: 0.000024
Epoch: 008 | Train loss: 1.0007 | Train acc: 49.62% | Val loss: 0.9984 | Val acc: 53.79% | LR: 0.000024
Epoch: 009 | Train loss: 1.0017 | Train acc: 49.01% | Val loss: 0.9976 | Val acc: 54.03% | LR: 0.000024
Epoch: 010 | Train loss: 1.0026 | Train acc: 49.94% | Val loss: 1.0064 | Val acc: 53.96% | LR: 0.000024
Epoch: 011 | Train loss: 1.0018 | Train acc: 49.76% | Val loss: 0.9974 | Val acc: 53.95% | LR: 0.000024
Epoch: 012 | Train loss: 0.9996 | Train acc: 50.10% | Val loss: 1.0005 | Val acc: 53.51% | LR: 0.000024
Epoch: 013 | Train loss: 0.9998 | Train acc: 49.90% | Val loss: 0.9989 | Val acc: 52.98% | LR: 0.000024
Epoch: 014 | Train loss: 1.0047 | Train acc: 50.33% | Val loss: 1.0005 | Val acc: 53.33% | LR: 0.000024
Epoch: 015 | Train loss: 1.0103 | Train acc: 50.76% | Val loss: 1.0023 | Val acc: 53.39% | LR: 0.000024
Epoch: 016 | Train loss: 1.0001 | Train acc: 49.71% | Val loss: 1.0008 | Val acc: 53.28% | LR: 0.000024
Epoch: 017 | Train loss: 0.9989 | Train acc: 50.68% | Val loss: 1.0032 | Val acc: 53.30% | LR: 0.000024
Epoch: 018 | Train loss: 1.0009 | Train acc: 50.03% | Val loss: 1.0076 | Val acc: 53.47% | LR: 0.000024
Epoch: 019 | Train loss: 1.0066 | Train acc: 49.99% | Val loss: 0.9974 | Val acc: 53.64% | LR: 0.000024
Epoch: 020 | Train loss: 0.9993 | Train acc: 50.55% | Val loss: 0.9986 | Val acc: 53.52% | LR: 0.000023
Epoch: 021 | Train loss: 0.9990 | Train acc: 50.83% | Val loss: 1.0035 | Val acc: 53.54% | LR: 0.000023
Epoch: 022 | Train loss: 1.0036 | Train acc: 50.67% | Val loss: 0.9983 | Val acc: 53.38% | LR: 0.000023
Epoch: 023 | Train loss: 0.9984 | Train acc: 50.41% | Val loss: 1.0006 | Val acc: 53.65% | LR: 0.000023
Epoch: 024 | Train loss: 0.9988 | Train acc: 50.52% | Val loss: 0.9994 | Val acc: 53.22% | LR: 0.000023
Epoch: 025 | Train loss: 0.9991 | Train acc: 50.32% | Val loss: 0.9988 | Val acc: 53.43% | LR: 0.000023
Epoch: 026 | Train loss: 0.9985 | Train acc: 50.25% | Val loss: 0.9993 | Val acc: 53.30% | LR: 0.000023
Epoch: 027 | Train loss: 0.9987 | Train acc: 50.61% | Val loss: 0.9974 | Val acc: 53.69% | LR: 0.000023
Epoch: 028 | Train loss: 0.9978 | Train acc: 50.87% | Val loss: 0.9995 | Val acc: 53.28% | LR: 0.000022
Epoch: 029 | Train loss: 0.9968 | Train acc: 51.00% | Val loss: 0.9978 | Val acc: 52.85% | LR: 0.000022
Epoch: 030 | Train loss: 0.9966 | Train acc: 50.72% | Val loss: 0.9985 | Val acc: 52.94% | LR: 0.000022
Epoch: 031 | Train loss: 0.9968 | Train acc: 50.40% | Val loss: 1.0864 | Val acc: 52.85% | LR: 0.000022
Epoch: 032 | Train loss: 0.9971 | Train acc: 50.58% | Val loss: 0.9982 | Val acc: 52.53% | LR: 0.000022
Epoch: 033 | Train loss: 0.9966 | Train acc: 50.77% | Val loss: 0.9983 | Val acc: 52.62% | LR: 0.000022
Epoch: 034 | Train loss: 0.9948 | Train acc: 51.12% | Val loss: 0.9981 | Val acc: 52.94% | LR: 0.000021
Epoch: 035 | Train loss: 0.9958 | Train acc: 50.66% | Val loss: 1.0043 | Val acc: 52.54% | LR: 0.000021
Epoch: 036 | Train loss: 0.9949 | Train acc: 50.85% | Val loss: 0.9990 | Val acc: 52.66% | LR: 0.000021
Epoch: 037 | Train loss: 0.9949 | Train acc: 50.77% | Val loss: 0.9995 | Val acc: 52.13% | LR: 0.000021
Epoch: 038 | Train loss: 0.9943 | Train acc: 50.81% | Val loss: 0.9989 | Val acc: 52.05% | LR: 0.000021
Epoch: 039 | Train loss: 0.9977 | Train acc: 50.41% | Val loss: 0.9993 | Val acc: 52.12% | LR: 0.000021
Epoch: 040 | Train loss: 0.9953 | Train acc: 50.69% | Val loss: 1.0003 | Val acc: 52.03% | LR: 0.000020
Epoch: 041 | Train loss: 0.9960 | Train acc: 50.60% | Val loss: 0.9988 | Val acc: 52.09% | LR: 0.000020
Epoch: 042 | Train loss: 0.9951 | Train acc: 50.57% | Val loss: 0.9995 | Val acc: 51.98% | LR: 0.000020
Epoch: 043 | Train loss: 0.9939 | Train acc: 51.05% | Val loss: 1.0005 | Val acc: 51.89% | LR: 0.000020
Epoch: 044 | Train loss: 0.9933 | Train acc: 51.12% | Val loss: 1.0009 | Val acc: 51.98% | LR: 0.000020
Epoch: 045 | Train loss: 0.9985 | Train acc: 50.18% | Val loss: 0.9983 | Val acc: 51.92% | LR: 0.000019
Epoch: 046 | Train loss: 0.9927 | Train acc: 50.96% | Val loss: 0.9988 | Val acc: 52.15% | LR: 0.000019
Epoch: 047 | Train loss: 0.9944 | Train acc: 51.00% | Val loss: 0.9988 | Val acc: 52.20% | LR: 0.000019
Epoch: 048 | Train loss: 0.9936 | Train acc: 51.07% | Val loss: 0.9987 | Val acc: 51.79% | LR: 0.000019
Epoch: 049 | Train loss: 0.9955 | Train acc: 50.65% | Val loss: 1.0010 | Val acc: 52.01% | LR: 0.000019
Epoch: 050 | Train loss: 0.9926 | Train acc: 51.09% | Val loss: 0.9993 | Val acc: 51.81% | LR: 0.000018
Epoch: 051 | Train loss: 0.9985 | Train acc: 50.23% | Val loss: 0.9991 | Val acc: 51.69% | LR: 0.000018
Epoch: 052 | Train loss: 0.9915 | Train acc: 50.84% | Val loss: 1.0031 | Val acc: 52.09% | LR: 0.000018

[I 2025-09-23 17:18:20,285] Trial 58 finished with value: 0.5219085454940796 and parameters: {'lr': 2.4517094527265e-05, 'hidden_size': 126, 'dropout': 0.3369836161404284, 'weight_decay': 1.7695150392188197e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0031 | Train acc: 49.76% | Val loss: 0.9988 | Val acc: 54.01% | LR: 0.000057
Epoch: 001 | Train loss: 0.9998 | Train acc: 50.57% | Val loss: 0.9985 | Val acc: 53.21% | LR: 0.000057
Epoch: 002 | Train loss: 1.0006 | Train acc: 49.99% | Val loss: 0.9978 | Val acc: 53.38% | LR: 0.000057
Epoch: 003 | Train loss: 1.0062 | Train acc: 50.43% | Val loss: 0.9974 | Val acc: 53.25% | LR: 0.000057
Epoch: 004 | Train loss: 1.0026 | Train acc: 49.54% | Val loss: 0.9969 | Val acc: 53.39% | LR: 0.000057
Epoch: 005 | Train loss: 1.0014 | Train acc: 49.79% | Val loss: 0.9964 | Val acc: 53.38% | LR: 0.000056
Epoch: 006 | Train loss: 0.9993 | Train acc: 50.57% | Val loss: 0.9960 | Val acc: 53.12% | LR: 0.000056
Epoch: 007 | Train loss: 0.9992 | Train acc: 50.31% | Val loss: 0.9953 | Val acc: 53.01% | LR: 0.000056
Epoch: 008 | Train loss: 1.0509 | Train acc: 50.58% | Val loss: 0.9950 | Val acc: 53.01% | LR: 0.000056
Epoch: 009 | Train loss: 1.0239 | Train acc: 50.60% | Val loss: 0.9947 | Val acc: 52.95% | LR: 0.000056
Epoch: 010 | Train loss: 1.0183 | Train acc: 50.37% | Val loss: 0.9945 | Val acc: 52.93% | LR: 0.000056
Epoch: 011 | Train loss: 1.0115 | Train acc: 50.75% | Val loss: 0.9944 | Val acc: 52.99% | LR: 0.000056
Epoch: 012 | Train loss: 1.0025 | Train acc: 49.66% | Val loss: 0.9939 | Val acc: 52.64% | LR: 0.000056
Epoch: 013 | Train loss: 0.9990 | Train acc: 49.97% | Val loss: 0.9939 | Val acc: 52.57% | LR: 0.000056
Epoch: 014 | Train loss: 0.9987 | Train acc: 50.21% | Val loss: 0.9930 | Val acc: 52.58% | LR: 0.000055
Epoch: 015 | Train loss: 0.9981 | Train acc: 49.75% | Val loss: 0.9922 | Val acc: 52.48% | LR: 0.000055
Epoch: 016 | Train loss: 0.9962 | Train acc: 50.66% | Val loss: 0.9910 | Val acc: 52.54% | LR: 0.000055
Epoch: 017 | Train loss: 0.9967 | Train acc: 50.66% | Val loss: 0.9904 | Val acc: 52.19% | LR: 0.000055
Epoch: 018 | Train loss: 0.9969 | Train acc: 51.49% | Val loss: 0.9899 | Val acc: 51.94% | LR: 0.000055
Epoch: 019 | Train loss: 0.9953 | Train acc: 51.34% | Val loss: 0.9878 | Val acc: 52.19% | LR: 0.000054
Epoch: 020 | Train loss: 0.9945 | Train acc: 51.34% | Val loss: 0.9869 | Val acc: 51.97% | LR: 0.000054
Epoch: 021 | Train loss: 0.9944 | Train acc: 50.92% | Val loss: 0.9843 | Val acc: 51.93% | LR: 0.000054
Epoch: 022 | Train loss: 0.9918 | Train acc: 51.07% | Val loss: 0.9809 | Val acc: 52.15% | LR: 0.000054
Epoch: 023 | Train loss: 0.9907 | Train acc: 51.23% | Val loss: 0.9759 | Val acc: 52.24% | LR: 0.000053
Epoch: 024 | Train loss: 0.9900 | Train acc: 51.10% | Val loss: 0.9757 | Val acc: 52.18% | LR: 0.000053
Epoch: 025 | Train loss: 0.9913 | Train acc: 51.24% | Val loss: 0.9754 | Val acc: 52.03% | LR: 0.000053
Epoch: 026 | Train loss: 0.9905 | Train acc: 51.10% | Val loss: 0.9759 | Val acc: 51.93% | LR: 0.000052
Epoch: 027 | Train loss: 0.9884 | Train acc: 51.10% | Val loss: 0.9762 | Val acc: 51.73% | LR: 0.000052
Epoch: 028 | Train loss: 0.9926 | Train acc: 50.66% | Val loss: 0.9775 | Val acc: 51.64% | LR: 0.000052
Epoch: 029 | Train loss: 0.9858 | Train acc: 51.31% | Val loss: 0.9785 | Val acc: 51.50% | LR: 0.000051
Epoch: 030 | Train loss: 0.9931 | Train acc: 50.49% | Val loss: 0.9802 | Val acc: 51.16% | LR: 0.000051
Epoch: 031 | Train loss: 0.9839 | Train acc: 51.59% | Val loss: 0.9813 | Val acc: 51.26% | LR: 0.000051
Epoch: 032 | Train loss: 0.9829 | Train acc: 51.61% | Val loss: 0.9816 | Val acc: 51.16% | LR: 0.000050
Epoch: 033 | Train loss: 0.9894 | Train acc: 50.72% | Val loss: 0.9815 | Val acc: 51.20% | LR: 0.000050
Epoch: 034 | Train loss: 0.9836 | Train acc: 51.33% | Val loss: 0.9825 | Val acc: 51.20% | LR: 0.000050
Epoch: 035 | Train loss: 0.9834 | Train acc: 51.33% | Val loss: 0.9837 | Val acc: 51.05% | LR: 0.000049
Epoch: 036 | Train loss: 0.9897 | Train acc: 50.71% | Val loss: 0.9838 | Val acc: 51.03% | LR: 0.000049
Epoch: 037 | Train loss: 0.9826 | Train acc: 51.49% | Val loss: 0.9843 | Val acc: 51.05% | LR: 0.000048
Epoch: 038 | Train loss: 0.9852 | Train acc: 51.03% | Val loss: 1.0085 | Val acc: 50.82% | LR: 0.000048
Epoch: 039 | Train loss: 0.9907 | Train acc: 50.89% | Val loss: 1.0000 | Val acc: 50.65% | LR: 0.000047
Epoch: 040 | Train loss: 0.9820 | Train acc: 51.34% | Val loss: 1.1907 | Val acc: 50.56% | LR: 0.000047
Epoch: 041 | Train loss: 0.9917 | Train acc: 50.63% | Val loss: 1.0908 | Val acc: 50.60% | LR: 0.000047
Epoch: 042 | Train loss: 0.9916 | Train acc: 50.55% | Val loss: 1.0027 | Val acc: 50.43% | LR: 0.000046
Epoch: 043 | Train loss: 0.9868 | Train acc: 50.89% | Val loss: 1.0261 | Val acc: 50.65% | LR: 0.000046
Epoch: 044 | Train loss: 0.9922 | Train acc: 50.76% | Val loss: 1.0346 | Val acc: 50.89% | LR: 0.000045
Epoch: 045 | Train loss: 0.9996 | Train acc: 50.17% | Val loss: 1.0282 | Val acc: 50.85% | LR: 0.000045
Epoch: 046 | Train loss: 0.9863 | Train acc: 51.04% | Val loss: 1.0256 | Val acc: 50.83% | LR: 0.000044
Epoch: 047 | Train loss: 0.9852 | Train acc: 51.24% | Val loss: 1.0062 | Val acc: 50.77% | LR: 0.000044
Epoch: 048 | Train loss: 0.9852 | Train acc: 51.13% | Val loss: 1.0085 | Val acc: 50.54% | LR: 0.000043
Epoch: 049 | Train loss: 1.0000 | Train acc: 50.66% | Val loss: 1.0070 | Val acc: 50.29% | LR: 0.000043

[I 2025-09-23 17:19:04,942] Trial 59 finished with value: 0.5051246702671051 and parameters: {'lr': 5.6701310939183125e-05, 'hidden_size': 87, 'dropout': 0.4270873947844199, 'weight_decay': 4.89055170705554e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9995 | Train acc: 50.01% | Val loss: 0.9959 | Val acc: 50.53% | LR: 0.001121
Epoch: 001 | Train loss: 0.9894 | Train acc: 51.04% | Val loss: 0.9728 | Val acc: 52.85% | LR: 0.001121
Epoch: 002 | Train loss: 0.9861 | Train acc: 51.11% | Val loss: 0.9772 | Val acc: 51.52% | LR: 0.001120
Epoch: 003 | Train loss: 0.9875 | Train acc: 50.69% | Val loss: 0.9949 | Val acc: 50.76% | LR: 0.001119
Epoch: 004 | Train loss: 0.9860 | Train acc: 51.25% | Val loss: 1.0040 | Val acc: 50.29% | LR: 0.001118
Epoch: 005 | Train loss: 0.9832 | Train acc: 51.04% | Val loss: 1.0029 | Val acc: 50.26% | LR: 0.001117
Epoch: 006 | Train loss: 0.9855 | Train acc: 51.02% | Val loss: 1.0143 | Val acc: 49.21% | LR: 0.001115
Epoch: 007 | Train loss: 0.9825 | Train acc: 51.04% | Val loss: 1.0043 | Val acc: 49.69% | LR: 0.001113
Epoch: 008 | Train loss: 0.9846 | Train acc: 50.99% | Val loss: 0.9919 | Val acc: 50.88% | LR: 0.001111
Epoch: 009 | Train loss: 0.9862 | Train acc: 50.83% | Val loss: 1.0012 | Val acc: 49.41% | LR: 0.001109
Epoch: 010 | Train loss: 0.9843 | Train acc: 51.02% | Val loss: 0.9918 | Val acc: 50.35% | LR: 0.001106
Epoch: 011 | Train loss: 0.9850 | Train acc: 50.76% | Val loss: 0.9757 | Val acc: 51.21% | LR: 0.001103
Epoch: 012 | Train loss: 0.9827 | Train acc: 51.10% | Val loss: 0.9905 | Val acc: 50.58% | LR: 0.001100
Epoch: 013 | Train loss: 0.9781 | Train acc: 51.41% | Val loss: 1.0010 | Val acc: 49.86% | LR: 0.001097
Epoch: 014 | Train loss: 0.9875 | Train acc: 50.73% | Val loss: 1.0203 | Val acc: 49.06% | LR: 0.001094
Epoch: 015 | Train loss: 0.9803 | Train acc: 51.21% | Val loss: 1.0284 | Val acc: 48.42% | LR: 0.001090
Epoch: 016 | Train loss: 0.9893 | Train acc: 50.75% | Val loss: 1.0103 | Val acc: 49.30% | LR: 0.001086
Epoch: 017 | Train loss: 0.9778 | Train acc: 51.36% | Val loss: 1.0398 | Val acc: 48.03% | LR: 0.001082
Epoch: 018 | Train loss: 0.9755 | Train acc: 51.52% | Val loss: 0.9692 | Val acc: 51.91% | LR: 0.001077
Epoch: 019 | Train loss: 0.9848 | Train acc: 51.04% | Val loss: 0.9890 | Val acc: 52.46% | LR: 0.001073
Epoch: 020 | Train loss: 0.9821 | Train acc: 51.14% | Val loss: 1.0033 | Val acc: 51.25% | LR: 0.001068
Epoch: 021 | Train loss: 0.9880 | Train acc: 50.94% | Val loss: 1.0869 | Val acc: 48.79% | LR: 0.001063
Epoch: 022 | Train loss: 0.9891 | Train acc: 50.70% | Val loss: 1.0547 | Val acc: 45.95% | LR: 0.001057
Epoch: 023 | Train loss: 0.9949 | Train acc: 50.34% | Val loss: 1.0265 | Val acc: 46.11% | LR: 0.001052
Epoch: 024 | Train loss: 0.9931 | Train acc: 50.56% | Val loss: 1.0295 | Val acc: 46.23% | LR: 0.001046
Epoch: 025 | Train loss: 0.9996 | Train acc: 50.05% | Val loss: 1.0175 | Val acc: 47.41% | LR: 0.001040
Epoch: 026 | Train loss: 0.9869 | Train acc: 51.19% | Val loss: 1.0174 | Val acc: 47.75% | LR: 0.001034
Epoch: 027 | Train loss: 0.9846 | Train acc: 51.05% | Val loss: 1.0172 | Val acc: 48.33% | LR: 0.001028
Epoch: 028 | Train loss: 0.9779 | Train acc: 51.54% | Val loss: 1.0025 | Val acc: 49.93% | LR: 0.001021
Epoch: 029 | Train loss: 0.9826 | Train acc: 50.96% | Val loss: 0.9891 | Val acc: 51.23% | LR: 0.001014
Epoch: 030 | Train loss: 0.9786 | Train acc: 51.30% | Val loss: 0.9737 | Val acc: 52.43% | LR: 0.001007
Epoch: 031 | Train loss: 0.9794 | Train acc: 51.20% | Val loss: 0.9998 | Val acc: 50.73% | LR: 0.001000
Epoch: 032 | Train loss: 0.9788 | Train acc: 51.31% | Val loss: 0.9954 | Val acc: 51.18% | LR: 0.000993
Epoch: 033 | Train loss: 0.9773 | Train acc: 51.33% | Val loss: 1.0242 | Val acc: 48.95% | LR: 0.000985
Epoch: 034 | Train loss: 0.9801 | Train acc: 51.21% | Val loss: 1.0168 | Val acc: 49.40% | LR: 0.000977
Epoch: 035 | Train loss: 0.9795 | Train acc: 51.29% | Val loss: 1.0045 | Val acc: 50.08% | LR: 0.000969
Epoch: 036 | Train loss: 0.9849 | Train acc: 50.83% | Val loss: 1.0071 | Val acc: 49.87% | LR: 0.000961
Epoch: 037 | Train loss: 0.9845 | Train acc: 50.81% | Val loss: 1.0172 | Val acc: 49.56% | LR: 0.000953
Epoch: 038 | Train loss: 0.9792 | Train acc: 51.19% | Val loss: 1.0086 | Val acc: 50.06% | LR: 0.000944
Epoch: 039 | Train loss: 0.9827 | Train acc: 50.95% | Val loss: 1.0055 | Val acc: 50.00% | LR: 0.000936
Epoch: 040 | Train loss: 0.9762 | Train acc: 51.32% | Val loss: 1.0038 | Val acc: 50.14% | LR: 0.000927
Epoch: 041 | Train loss: 0.9800 | Train acc: 51.05% | Val loss: 1.0217 | Val acc: 49.65% | LR: 0.000918
Epoch: 042 | Train loss: 0.9817 | Train acc: 51.08% | Val loss: 1.0305 | Val acc: 48.44% | LR: 0.000909
Epoch: 043 | Train loss: 0.9782 | Train acc: 51.17% | Val loss: 1.0205 | Val acc: 49.10% | LR: 0.000900
Epoch: 044 | Train loss: 0.9868 | Train acc: 50.61% | Val loss: 1.0000 | Val acc: 50.02% | LR: 0.000890
Epoch: 045 | Train loss: 0.9766 | Train acc: 51.28% | Val loss: 1.0043 | Val acc: 49.62% | LR: 0.000881
Epoch: 046 | Train loss: 0.9868 | Train acc: 50.72% | Val loss: 1.0046 | Val acc: 49.84% | LR: 0.000871
Epoch: 047 | Train loss: 0.9858 | Train acc: 50.90% | Val loss: 0.9961 | Val acc: 49.98% | LR: 0.000861
Epoch: 048 | Train loss: 0.9783 | Train acc: 51.36% | Val loss: 0.9917 | Val acc: 50.86% | LR: 0.000851
Epoch: 049 | Train loss: 0.9779 | Train acc: 51.27% | Val loss: 0.9956 | Val acc: 50.54% | LR: 0.000841
Epoch: 050 | Train loss: 0.9721 | Train acc: 51.55% | Val loss: 1.0112 | Val acc: 49.65% | LR: 0.000831

[I 2025-09-23 17:19:50,136] Trial 60 finished with value: 0.49089897274971006 and parameters: {'lr': 0.0011210823113875425, 'hidden_size': 114, 'dropout': 0.31174989291582367, 'weight_decay': 1.9621297297145955e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0007 | Train acc: 49.26% | Val loss: 1.0063 | Val acc: 45.95% | LR: 0.000259
Epoch: 001 | Train loss: 0.9996 | Train acc: 50.20% | Val loss: 1.0058 | Val acc: 45.95% | LR: 0.000259
Epoch: 002 | Train loss: 0.9987 | Train acc: 50.43% | Val loss: 1.0059 | Val acc: 45.99% | LR: 0.000259
Epoch: 003 | Train loss: 0.9991 | Train acc: 50.16% | Val loss: 1.0062 | Val acc: 45.99% | LR: 0.000259
Epoch: 004 | Train loss: 0.9961 | Train acc: 50.61% | Val loss: 1.0063 | Val acc: 46.03% | LR: 0.000259
Epoch: 005 | Train loss: 0.9908 | Train acc: 51.05% | Val loss: 1.0072 | Val acc: 46.01% | LR: 0.000258
Epoch: 006 | Train loss: 0.9895 | Train acc: 50.87% | Val loss: 1.0087 | Val acc: 46.03% | LR: 0.000258
Epoch: 007 | Train loss: 0.9943 | Train acc: 50.35% | Val loss: 1.0097 | Val acc: 46.18% | LR: 0.000258
Epoch: 008 | Train loss: 0.9918 | Train acc: 50.42% | Val loss: 1.0097 | Val acc: 46.24% | LR: 0.000257
Epoch: 009 | Train loss: 0.9884 | Train acc: 50.94% | Val loss: 1.0079 | Val acc: 47.13% | LR: 0.000257
Epoch: 010 | Train loss: 0.9910 | Train acc: 50.78% | Val loss: 1.0073 | Val acc: 47.86% | LR: 0.000256
Epoch: 011 | Train loss: 0.9809 | Train acc: 51.18% | Val loss: 1.0083 | Val acc: 48.22% | LR: 0.000255
Epoch: 012 | Train loss: 0.9826 | Train acc: 51.18% | Val loss: 1.0021 | Val acc: 49.28% | LR: 0.000255
Epoch: 013 | Train loss: 0.9969 | Train acc: 50.28% | Val loss: 0.9958 | Val acc: 50.19% | LR: 0.000254
Epoch: 014 | Train loss: 0.9887 | Train acc: 50.73% | Val loss: 0.9891 | Val acc: 50.80% | LR: 0.000253
Epoch: 015 | Train loss: 0.9772 | Train acc: 51.41% | Val loss: 0.9927 | Val acc: 50.01% | LR: 0.000252
Epoch: 016 | Train loss: 0.9786 | Train acc: 51.43% | Val loss: 0.9959 | Val acc: 50.10% | LR: 0.000251
Epoch: 017 | Train loss: 0.9847 | Train acc: 50.91% | Val loss: 0.9992 | Val acc: 49.89% | LR: 0.000250
Epoch: 018 | Train loss: 0.9886 | Train acc: 50.62% | Val loss: 1.0036 | Val acc: 49.39% | LR: 0.000249
Epoch: 019 | Train loss: 0.9810 | Train acc: 51.10% | Val loss: 1.0079 | Val acc: 49.27% | LR: 0.000248
Epoch: 020 | Train loss: 0.9766 | Train acc: 51.34% | Val loss: 1.0158 | Val acc: 48.69% | LR: 0.000247
Epoch: 021 | Train loss: 0.9766 | Train acc: 51.24% | Val loss: 1.0148 | Val acc: 48.93% | LR: 0.000246
Epoch: 022 | Train loss: 0.9808 | Train acc: 51.10% | Val loss: 1.0112 | Val acc: 49.11% | LR: 0.000245
Epoch: 023 | Train loss: 0.9796 | Train acc: 51.12% | Val loss: 1.0108 | Val acc: 49.25% | LR: 0.000243
Epoch: 024 | Train loss: 0.9750 | Train acc: 51.37% | Val loss: 1.0117 | Val acc: 49.20% | LR: 0.000242
Epoch: 025 | Train loss: 0.9820 | Train acc: 51.04% | Val loss: 1.0136 | Val acc: 48.99% | LR: 0.000241
Epoch: 026 | Train loss: 0.9780 | Train acc: 51.25% | Val loss: 1.0216 | Val acc: 48.86% | LR: 0.000239
Epoch: 027 | Train loss: 0.9866 | Train acc: 50.65% | Val loss: 1.0241 | Val acc: 48.69% | LR: 0.000238
Epoch: 028 | Train loss: 0.9745 | Train acc: 51.52% | Val loss: 1.0146 | Val acc: 49.02% | LR: 0.000236
Epoch: 029 | Train loss: 0.9840 | Train acc: 50.88% | Val loss: 1.0186 | Val acc: 49.05% | LR: 0.000235
Epoch: 030 | Train loss: 0.9791 | Train acc: 51.12% | Val loss: 1.0172 | Val acc: 49.04% | LR: 0.000233
Epoch: 031 | Train loss: 0.9709 | Train acc: 51.62% | Val loss: 1.0210 | Val acc: 48.93% | LR: 0.000232
Epoch: 032 | Train loss: 0.9758 | Train acc: 51.29% | Val loss: 1.0171 | Val acc: 49.04% | LR: 0.000230
Epoch: 033 | Train loss: 0.9708 | Train acc: 51.55% | Val loss: 1.0189 | Val acc: 48.97% | LR: 0.000228
Epoch: 034 | Train loss: 0.9832 | Train acc: 50.87% | Val loss: 1.0219 | Val acc: 48.94% | LR: 0.000226
Epoch: 035 | Train loss: 0.9766 | Train acc: 51.21% | Val loss: 1.0175 | Val acc: 48.98% | LR: 0.000224
Epoch: 036 | Train loss: 0.9726 | Train acc: 51.41% | Val loss: 1.0227 | Val acc: 48.77% | LR: 0.000223
Epoch: 037 | Train loss: 0.9764 | Train acc: 51.22% | Val loss: 1.0167 | Val acc: 49.06% | LR: 0.000221
Epoch: 038 | Train loss: 0.9746 | Train acc: 51.35% | Val loss: 1.0222 | Val acc: 48.79% | LR: 0.000219
Epoch: 039 | Train loss: 0.9853 | Train acc: 50.74% | Val loss: 1.0170 | Val acc: 49.02% | LR: 0.000217
Epoch: 040 | Train loss: 0.9737 | Train acc: 51.43% | Val loss: 1.0171 | Val acc: 49.00% | LR: 0.000215
Epoch: 041 | Train loss: 0.9783 | Train acc: 51.23% | Val loss: 1.0155 | Val acc: 49.15% | LR: 0.000213
Epoch: 042 | Train loss: 0.9814 | Train acc: 51.00% | Val loss: 1.0209 | Val acc: 49.00% | LR: 0.000211
Epoch: 043 | Train loss: 0.9761 | Train acc: 51.27% | Val loss: 1.0193 | Val acc: 49.00% | LR: 0.000208
Epoch: 044 | Train loss: 0.9709 | Train acc: 51.52% | Val loss: 1.0173 | Val acc: 49.06% | LR: 0.000206
Epoch: 045 | Train loss: 0.9723 | Train acc: 51.44% | Val loss: 1.0169 | Val acc: 49.06% | LR: 0.000204
Epoch: 046 | Train loss: 0.9824 | Train acc: 50.92% | Val loss: 1.0194 | Val acc: 48.98% | LR: 0.000202
Epoch: 047 | Train loss: 0.9736 | Train acc: 51.35% | Val loss: 1.0193 | Val acc: 49.00% | LR: 0.000199
Epoch: 048 | Train loss: 0.9818 | Train acc: 50.92% | Val loss: 1.0191 | Val acc: 49.06% | LR: 0.000197
Epoch: 049 | Train loss: 0.9833 | Train acc: 50.85% | Val loss: 1.0186 | Val acc: 49.02% | LR: 0.000195
Epoch: 050 | Train loss: 0.9645 | Train acc: 51.90% | Val loss: 1.0183 | Val acc: 49.02% | LR: 0.000193
Epoch: 051 | Train loss: 0.9705 | Train acc: 51.55% | Val loss: 1.0165 | Val acc: 49.10% | LR: 0.000190
Epoch: 052 | Train loss: 0.9799 | Train acc: 51.05% | Val loss: 1.0190 | Val acc: 48.93% | LR: 0.000188
Epoch: 053 | Train loss: 0.9854 | Train acc: 50.73% | Val loss: 1.0190 | Val acc: 49.06% | LR: 0.000185
Epoch: 054 | Train loss: 0.9796 | Train acc: 51.05% | Val loss: 1.0251 | Val acc: 48.63% | LR: 0.000183
Epoch: 055 | Train loss: 0.9695 | Train acc: 51.59% | Val loss: 1.0178 | Val acc: 49.01% | LR: 0.000180
Epoch: 056 | Train loss: 0.9732 | Train acc: 51.40% | Val loss: 1.0174 | Val acc: 49.09% | LR: 0.000178
Epoch: 057 | Train loss: 0.9789 | Train acc: 51.10% | Val loss: 1.0164 | Val acc: 49.14% | LR: 0.000175
Epoch: 058 | Train loss: 0.9836 | Train acc: 50.85% | Val loss: 1.0172 | Val acc: 49.00% | LR: 0.000173
Epoch: 059 | Train loss: 0.9799 | Train acc: 51.05% | Val loss: 1.0177 | Val acc: 49.06% | LR: 0.000170
Epoch: 060 | Train loss: 0.9830 | Train acc: 50.86% | Val loss: 1.0167 | Val acc: 49.02% | LR: 0.000168
Epoch: 061 | Train loss: 0.9689 | Train acc: 51.66% | Val loss: 1.0167 | Val acc: 49.14% | LR: 0.000165
Epoch: 062 | Train loss: 0.9699 | Train acc: 51.58% | Val loss: 1.0194 | Val acc: 48.95% | LR: 0.000162
Epoch: 063 | Train loss: 0.9753 | Train acc: 51.27% | Val loss: 1.0144 | Val acc: 49.02% | LR: 0.000160

[I 2025-09-23 17:20:48,354] Trial 61 finished with value: 0.4905628144741058 and parameters: {'lr': 0.0002594835215952651, 'hidden_size': 72, 'dropout': 0.10709925884734534, 'weight_decay': 0.00015720243515737073}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9984 | Train acc: 50.35% | Val loss: 0.9994 | Val acc: 50.13% | LR: 0.000042
Epoch: 001 | Train loss: 0.9953 | Train acc: 50.61% | Val loss: 0.9994 | Val acc: 50.08% | LR: 0.000042
Epoch: 002 | Train loss: 0.9935 | Train acc: 50.86% | Val loss: 0.9989 | Val acc: 50.49% | LR: 0.000042
Epoch: 003 | Train loss: 0.9967 | Train acc: 50.75% | Val loss: 0.9987 | Val acc: 50.41% | LR: 0.000042
Epoch: 004 | Train loss: 0.9939 | Train acc: 50.87% | Val loss: 0.9984 | Val acc: 50.57% | LR: 0.000042
Epoch: 005 | Train loss: 0.9964 | Train acc: 50.97% | Val loss: 0.9985 | Val acc: 50.53% | LR: 0.000042
Epoch: 006 | Train loss: 0.9934 | Train acc: 51.10% | Val loss: 0.9982 | Val acc: 50.49% | LR: 0.000042
Epoch: 007 | Train loss: 0.9956 | Train acc: 51.01% | Val loss: 0.9977 | Val acc: 50.89% | LR: 0.000042
Epoch: 008 | Train loss: 0.9962 | Train acc: 51.19% | Val loss: 0.9971 | Val acc: 51.19% | LR: 0.000042
Epoch: 009 | Train loss: 0.9924 | Train acc: 50.27% | Val loss: 0.9969 | Val acc: 51.14% | LR: 0.000042
Epoch: 010 | Train loss: 0.9947 | Train acc: 50.41% | Val loss: 0.9966 | Val acc: 51.32% | LR: 0.000042
Epoch: 011 | Train loss: 0.9962 | Train acc: 50.70% | Val loss: 0.9959 | Val acc: 51.38% | LR: 0.000041
Epoch: 012 | Train loss: 0.9973 | Train acc: 51.22% | Val loss: 0.9953 | Val acc: 51.80% | LR: 0.000041
Epoch: 013 | Train loss: 0.9949 | Train acc: 51.01% | Val loss: 0.9944 | Val acc: 51.97% | LR: 0.000041
Epoch: 014 | Train loss: 0.9933 | Train acc: 50.33% | Val loss: 0.9941 | Val acc: 51.95% | LR: 0.000041
Epoch: 015 | Train loss: 0.9939 | Train acc: 50.65% | Val loss: 0.9942 | Val acc: 51.78% | LR: 0.000041
Epoch: 016 | Train loss: 0.9917 | Train acc: 50.86% | Val loss: 0.9938 | Val acc: 51.82% | LR: 0.000041
Epoch: 017 | Train loss: 0.9938 | Train acc: 50.66% | Val loss: 0.9933 | Val acc: 51.72% | LR: 0.000041
Epoch: 018 | Train loss: 0.9899 | Train acc: 51.47% | Val loss: 0.9929 | Val acc: 51.72% | LR: 0.000040
Epoch: 019 | Train loss: 0.9923 | Train acc: 50.51% | Val loss: 0.9924 | Val acc: 51.62% | LR: 0.000040
Epoch: 020 | Train loss: 0.9913 | Train acc: 51.03% | Val loss: 0.9918 | Val acc: 51.61% | LR: 0.000040
Epoch: 021 | Train loss: 0.9896 | Train acc: 50.96% | Val loss: 0.9911 | Val acc: 51.74% | LR: 0.000040
Epoch: 022 | Train loss: 0.9875 | Train acc: 51.74% | Val loss: 0.9906 | Val acc: 51.74% | LR: 0.000040
Epoch: 023 | Train loss: 0.9909 | Train acc: 50.51% | Val loss: 0.9897 | Val acc: 51.76% | LR: 0.000040
Epoch: 024 | Train loss: 0.9888 | Train acc: 51.06% | Val loss: 0.9885 | Val acc: 51.88% | LR: 0.000039
Epoch: 025 | Train loss: 0.9891 | Train acc: 50.98% | Val loss: 0.9871 | Val acc: 51.92% | LR: 0.000039
Epoch: 026 | Train loss: 0.9878 | Train acc: 50.96% | Val loss: 0.9857 | Val acc: 51.93% | LR: 0.000039
Epoch: 027 | Train loss: 0.9908 | Train acc: 51.07% | Val loss: 0.9846 | Val acc: 51.93% | LR: 0.000039
Epoch: 028 | Train loss: 0.9889 | Train acc: 51.32% | Val loss: 0.9838 | Val acc: 51.99% | LR: 0.000038
Epoch: 029 | Train loss: 0.9884 | Train acc: 51.08% | Val loss: 0.9823 | Val acc: 52.09% | LR: 0.000038
Epoch: 030 | Train loss: 0.9885 | Train acc: 51.01% | Val loss: 0.9819 | Val acc: 52.03% | LR: 0.000038
Epoch: 031 | Train loss: 0.9890 | Train acc: 50.81% | Val loss: 0.9820 | Val acc: 51.85% | LR: 0.000038
Epoch: 032 | Train loss: 0.9880 | Train acc: 50.97% | Val loss: 0.9806 | Val acc: 51.95% | LR: 0.000037
Epoch: 033 | Train loss: 0.9898 | Train acc: 50.72% | Val loss: 0.9803 | Val acc: 51.91% | LR: 0.000037
Epoch: 034 | Train loss: 0.9843 | Train acc: 51.18% | Val loss: 0.9786 | Val acc: 51.95% | LR: 0.000037
Epoch: 035 | Train loss: 0.9833 | Train acc: 51.27% | Val loss: 0.9780 | Val acc: 51.91% | LR: 0.000037
Epoch: 036 | Train loss: 0.9859 | Train acc: 50.72% | Val loss: 0.9774 | Val acc: 51.85% | LR: 0.000036
Epoch: 037 | Train loss: 0.9828 | Train acc: 51.17% | Val loss: 0.9771 | Val acc: 51.77% | LR: 0.000036
Epoch: 038 | Train loss: 0.9880 | Train acc: 50.72% | Val loss: 0.9775 | Val acc: 51.77% | LR: 0.000036
Epoch: 039 | Train loss: 0.9883 | Train acc: 50.63% | Val loss: 0.9776 | Val acc: 51.69% | LR: 0.000035
Epoch: 040 | Train loss: 0.9852 | Train acc: 51.51% | Val loss: 0.9779 | Val acc: 51.79% | LR: 0.000035
Epoch: 041 | Train loss: 0.9941 | Train acc: 50.78% | Val loss: 0.9780 | Val acc: 51.71% | LR: 0.000035
Epoch: 042 | Train loss: 0.9851 | Train acc: 51.24% | Val loss: 0.9782 | Val acc: 51.60% | LR: 0.000034
Epoch: 043 | Train loss: 0.9861 | Train acc: 50.88% | Val loss: 0.9785 | Val acc: 51.56% | LR: 0.000034
Epoch: 044 | Train loss: 0.9866 | Train acc: 50.88% | Val loss: 0.9790 | Val acc: 51.48% | LR: 0.000034
Epoch: 045 | Train loss: 0.9895 | Train acc: 50.77% | Val loss: 0.9795 | Val acc: 51.44% | LR: 0.000033
Epoch: 046 | Train loss: 0.9871 | Train acc: 50.94% | Val loss: 0.9795 | Val acc: 51.38% | LR: 0.000033
Epoch: 047 | Train loss: 0.9888 | Train acc: 50.84% | Val loss: 0.9799 | Val acc: 51.30% | LR: 0.000033
Epoch: 048 | Train loss: 0.9851 | Train acc: 51.37% | Val loss: 0.9800 | Val acc: 51.20% | LR: 0.000032
Epoch: 049 | Train loss: 0.9863 | Train acc: 50.66% | Val loss: 0.9802 | Val acc: 51.22% | LR: 0.000032
Epoch: 050 | Train loss: 0.9809 | Train acc: 51.21% | Val loss: 0.9809 | Val acc: 51.11% | LR: 0.000031
Epoch: 051 | Train loss: 0.9838 | Train acc: 50.94% | Val loss: 0.9811 | Val acc: 51.17% | LR: 0.000031
Epoch: 052 | Train loss: 0.9830 | Train acc: 51.30% | Val loss: 0.9813 | Val acc: 51.17% | LR: 0.000031
Epoch: 053 | Train loss: 0.9908 | Train acc: 50.15% | Val loss: 0.9815 | Val acc: 51.13% | LR: 0.000030
Epoch: 054 | Train loss: 0.9859 | Train acc: 51.03% | Val loss: 0.9817 | Val acc: 51.05% | LR: 0.000030
Epoch: 055 | Train loss: 1.2348 | Train acc: 51.15% | Val loss: 0.9817 | Val acc: 51.03% | LR: 0.000029
Epoch: 056 | Train loss: 0.9976 | Train acc: 51.17% | Val loss: 0.9818 | Val acc: 51.03% | LR: 0.000029
Epoch: 057 | Train loss: 0.9860 | Train acc: 51.82% | Val loss: 0.9824 | Val acc: 50.93% | LR: 0.000029
Epoch: 058 | Train loss: 0.9855 | Train acc: 51.19% | Val loss: 0.9824 | Val acc: 50.95% | LR: 0.000028
Epoch: 059 | Train loss: 0.9914 | Train acc: 50.86% | Val loss: 0.9831 | Val acc: 50.92% | LR: 0.000028
Epoch: 060 | Train loss: 0.9886 | Train acc: 50.93% | Val loss: 0.9834 | Val acc: 51.06% | LR: 0.000027
Epoch: 061 | Train loss: 0.9872 | Train acc: 51.12% | Val loss: 0.9834 | Val acc: 51.00% | LR: 0.000027
Epoch: 062 | Train loss: 0.9890 | Train acc: 50.76% | Val loss: 0.9838 | Val acc: 51.18% | LR: 0.000027
Epoch: 063 | Train loss: 0.9847 | Train acc: 50.85% | Val loss: 0.9838 | Val acc: 51.16% | LR: 0.000026
Epoch: 064 | Train loss: 0.9895 | Train acc: 50.85% | Val loss: 0.9840 | Val acc: 51.20% | LR: 0.000026
Epoch: 065 | Train loss: 0.9833 | Train acc: 51.30% | Val loss: 0.9842 | Val acc: 51.20% | LR: 0.000025
Epoch: 066 | Train loss: 0.9881 | Train acc: 50.86% | Val loss: 0.9847 | Val acc: 51.20% | LR: 0.000025
Epoch: 067 | Train loss: 0.9841 | Train acc: 51.04% | Val loss: 0.9847 | Val acc: 51.12% | LR: 0.000025
Epoch: 068 | Train loss: 0.9856 | Train acc: 51.24% | Val loss: 0.9850 | Val acc: 51.04% | LR: 0.000024
Epoch: 069 | Train loss: 0.9828 | Train acc: 51.50% | Val loss: 0.9850 | Val acc: 51.12% | LR: 0.000024
Epoch: 070 | Train loss: 0.9842 | Train acc: 50.97% | Val loss: 0.9849 | Val acc: 51.12% | LR: 0.000023
Epoch: 071 | Train loss: 0.9856 | Train acc: 51.06% | Val loss: 0.9851 | Val acc: 51.06% | LR: 0.000023
Epoch: 072 | Train loss: 0.9851 | Train acc: 50.88% | Val loss: 0.9848 | Val acc: 51.10% | LR: 0.000022
Epoch: 073 | Train loss: 0.9850 | Train acc: 50.97% | Val loss: 0.9850 | Val acc: 51.04% | LR: 0.000022
Epoch: 074 | Train loss: 0.9861 | Train acc: 51.15% | Val loss: 0.9851 | Val acc: 51.01% | LR: 0.000022
Epoch: 075 | Train loss: 0.9837 | Train acc: 51.24% | Val loss: 0.9854 | Val acc: 51.03% | LR: 0.000021
Epoch: 076 | Train loss: 0.9820 | Train acc: 51.16% | Val loss: 0.9855 | Val acc: 50.97% | LR: 0.000021
Epoch: 077 | Train loss: 0.9870 | Train acc: 50.70% | Val loss: 0.9856 | Val acc: 50.97% | LR: 0.000020
Epoch: 078 | Train loss: 0.9784 | Train acc: 51.50% | Val loss: 0.9855 | Val acc: 50.99% | LR: 0.000020

[I 2025-09-23 17:21:52,947] Trial 62 finished with value: 0.5097320973873138 and parameters: {'lr': 4.207431096274087e-05, 'hidden_size': 77, 'dropout': 0.40150643384513535, 'weight_decay': 7.526857747010594e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0003 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000020
Epoch: 001 | Train loss: 1.0007 | Train acc: 49.72% | Val loss: 0.9916 | Val acc: 54.13% | LR: 0.000020
Epoch: 002 | Train loss: 1.0004 | Train acc: 49.55% | Val loss: 0.9916 | Val acc: 54.13% | LR: 0.000020
Epoch: 003 | Train loss: 1.0007 | Train acc: 49.54% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000020
Epoch: 004 | Train loss: 1.0012 | Train acc: 49.36% | Val loss: 0.9918 | Val acc: 54.17% | LR: 0.000020
Epoch: 005 | Train loss: 0.9984 | Train acc: 50.04% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000020
Epoch: 006 | Train loss: 1.0004 | Train acc: 49.86% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000020
Epoch: 007 | Train loss: 1.0011 | Train acc: 49.72% | Val loss: 0.9919 | Val acc: 54.30% | LR: 0.000020
Epoch: 008 | Train loss: 1.0006 | Train acc: 49.75% | Val loss: 0.9920 | Val acc: 54.28% | LR: 0.000020
Epoch: 009 | Train loss: 0.9988 | Train acc: 50.55% | Val loss: 0.9921 | Val acc: 54.28% | LR: 0.000020
Epoch: 010 | Train loss: 0.9982 | Train acc: 50.71% | Val loss: 0.9922 | Val acc: 54.32% | LR: 0.000020
Epoch: 011 | Train loss: 0.9981 | Train acc: 50.75% | Val loss: 0.9920 | Val acc: 54.32% | LR: 0.000020
Epoch: 012 | Train loss: 0.9978 | Train acc: 50.62% | Val loss: 0.9920 | Val acc: 54.32% | LR: 0.000020
Epoch: 013 | Train loss: 0.9987 | Train acc: 50.44% | Val loss: 0.9918 | Val acc: 54.36% | LR: 0.000020
Epoch: 014 | Train loss: 0.9981 | Train acc: 50.53% | Val loss: 0.9919 | Val acc: 54.38% | LR: 0.000020
Epoch: 015 | Train loss: 0.9990 | Train acc: 50.17% | Val loss: 0.9919 | Val acc: 54.28% | LR: 0.000020
Epoch: 016 | Train loss: 0.9979 | Train acc: 50.60% | Val loss: 0.9920 | Val acc: 54.31% | LR: 0.000020
Epoch: 017 | Train loss: 0.9982 | Train acc: 50.58% | Val loss: 0.9919 | Val acc: 54.39% | LR: 0.000019
Epoch: 018 | Train loss: 0.9984 | Train acc: 50.46% | Val loss: 0.9918 | Val acc: 54.37% | LR: 0.000019
Epoch: 019 | Train loss: 0.9986 | Train acc: 50.30% | Val loss: 0.9917 | Val acc: 54.40% | LR: 0.000019
Epoch: 020 | Train loss: 0.9967 | Train acc: 51.17% | Val loss: 0.9927 | Val acc: 54.31% | LR: 0.000019
Epoch: 021 | Train loss: 0.9975 | Train acc: 50.85% | Val loss: 0.9917 | Val acc: 54.40% | LR: 0.000019
Epoch: 022 | Train loss: 0.9973 | Train acc: 50.87% | Val loss: 0.9917 | Val acc: 54.46% | LR: 0.000019
Epoch: 023 | Train loss: 0.9980 | Train acc: 50.56% | Val loss: 0.9916 | Val acc: 54.56% | LR: 0.000019
Epoch: 024 | Train loss: 0.9978 | Train acc: 50.55% | Val loss: 0.9916 | Val acc: 54.52% | LR: 0.000019
Epoch: 025 | Train loss: 0.9987 | Train acc: 50.18% | Val loss: 0.9916 | Val acc: 54.60% | LR: 0.000019
Epoch: 026 | Train loss: 0.9978 | Train acc: 50.60% | Val loss: 0.9916 | Val acc: 54.40% | LR: 0.000019
Epoch: 027 | Train loss: 0.9970 | Train acc: 50.95% | Val loss: 0.9916 | Val acc: 54.58% | LR: 0.000019
Epoch: 028 | Train loss: 0.9966 | Train acc: 51.15% | Val loss: 0.9916 | Val acc: 54.70% | LR: 0.000018
Epoch: 029 | Train loss: 0.9967 | Train acc: 51.07% | Val loss: 0.9915 | Val acc: 54.66% | LR: 0.000018
Epoch: 030 | Train loss: 0.9979 | Train acc: 50.73% | Val loss: 0.9915 | Val acc: 54.71% | LR: 0.000018
Epoch: 031 | Train loss: 0.9983 | Train acc: 50.62% | Val loss: 0.9914 | Val acc: 54.62% | LR: 0.000018
Epoch: 032 | Train loss: 0.9959 | Train acc: 51.25% | Val loss: 0.9921 | Val acc: 54.56% | LR: 0.000018
Epoch: 033 | Train loss: 0.9981 | Train acc: 50.21% | Val loss: 0.9914 | Val acc: 54.57% | LR: 0.000018
Epoch: 034 | Train loss: 0.9957 | Train acc: 51.20% | Val loss: 0.9914 | Val acc: 54.73% | LR: 0.000018
Epoch: 035 | Train loss: 0.9977 | Train acc: 50.63% | Val loss: 0.9914 | Val acc: 54.53% | LR: 0.000018
Epoch: 036 | Train loss: 0.9968 | Train acc: 50.82% | Val loss: 0.9914 | Val acc: 54.51% | LR: 0.000017
Epoch: 037 | Train loss: 0.9966 | Train acc: 50.77% | Val loss: 0.9914 | Val acc: 54.45% | LR: 0.000017
Epoch: 038 | Train loss: 0.9978 | Train acc: 50.52% | Val loss: 0.9915 | Val acc: 54.56% | LR: 0.000017
Epoch: 039 | Train loss: 0.9952 | Train acc: 50.80% | Val loss: 0.9913 | Val acc: 54.52% | LR: 0.000017
Epoch: 040 | Train loss: 0.9963 | Train acc: 51.00% | Val loss: 0.9913 | Val acc: 54.51% | LR: 0.000017
Epoch: 041 | Train loss: 0.9967 | Train acc: 50.80% | Val loss: 0.9913 | Val acc: 54.52% | LR: 0.000017
Epoch: 042 | Train loss: 0.9972 | Train acc: 50.81% | Val loss: 0.9912 | Val acc: 54.54% | LR: 0.000017
Epoch: 043 | Train loss: 0.9972 | Train acc: 50.39% | Val loss: 0.9912 | Val acc: 54.56% | LR: 0.000016
Epoch: 044 | Train loss: 0.9971 | Train acc: 50.68% | Val loss: 0.9912 | Val acc: 54.52% | LR: 0.000016
Epoch: 045 | Train loss: 0.9956 | Train acc: 51.07% | Val loss: 0.9911 | Val acc: 54.66% | LR: 0.000016
Epoch: 046 | Train loss: 0.9951 | Train acc: 50.77% | Val loss: 0.9911 | Val acc: 54.61% | LR: 0.000016
Epoch: 047 | Train loss: 0.9960 | Train acc: 51.12% | Val loss: 0.9911 | Val acc: 54.45% | LR: 0.000016
Epoch: 048 | Train loss: 0.9964 | Train acc: 50.74% | Val loss: 0.9911 | Val acc: 54.44% | LR: 0.000016
Epoch: 049 | Train loss: 0.9966 | Train acc: 50.59% | Val loss: 0.9911 | Val acc: 54.40% | LR: 0.000015
Epoch: 050 | Train loss: 0.9977 | Train acc: 50.40% | Val loss: 0.9910 | Val acc: 54.36% | LR: 0.000015
Epoch: 051 | Train loss: 0.9948 | Train acc: 51.11% | Val loss: 0.9911 | Val acc: 54.38% | LR: 0.000015
Epoch: 052 | Train loss: 0.9987 | Train acc: 50.15% | Val loss: 0.9911 | Val acc: 54.47% | LR: 0.000015
Epoch: 053 | Train loss: 0.9960 | Train acc: 51.03% | Val loss: 0.9910 | Val acc: 54.53% | LR: 0.000015
Epoch: 054 | Train loss: 0.9947 | Train acc: 51.05% | Val loss: 0.9910 | Val acc: 54.45% | LR: 0.000014
Epoch: 055 | Train loss: 0.9949 | Train acc: 50.79% | Val loss: 0.9909 | Val acc: 54.35% | LR: 0.000014
Epoch: 056 | Train loss: 0.9950 | Train acc: 50.80% | Val loss: 0.9909 | Val acc: 54.24% | LR: 0.000014
Epoch: 057 | Train loss: 1.0788 | Train acc: 51.00% | Val loss: 0.9909 | Val acc: 54.26% | LR: 0.000014
Epoch: 058 | Train loss: 1.0913 | Train acc: 50.53% | Val loss: 0.9909 | Val acc: 54.20% | LR: 0.000014
Epoch: 059 | Train loss: 0.9959 | Train acc: 50.73% | Val loss: 0.9909 | Val acc: 54.26% | LR: 0.000014
Epoch: 060 | Train loss: 0.9950 | Train acc: 51.01% | Val loss: 0.9908 | Val acc: 54.16% | LR: 0.000013
Epoch: 061 | Train loss: 0.9938 | Train acc: 51.63% | Val loss: 0.9907 | Val acc: 54.16% | LR: 0.000013
Epoch: 062 | Train loss: 0.9945 | Train acc: 51.29% | Val loss: 0.9908 | Val acc: 54.26% | LR: 0.000013
Epoch: 063 | Train loss: 0.9970 | Train acc: 50.54% | Val loss: 0.9910 | Val acc: 54.24% | LR: 0.000013
Epoch: 064 | Train loss: 0.9961 | Train acc: 50.53% | Val loss: 0.9909 | Val acc: 54.00% | LR: 0.000013
Epoch: 065 | Train loss: 0.9964 | Train acc: 51.02% | Val loss: 0.9904 | Val acc: 54.06% | LR: 0.000012
Epoch: 066 | Train loss: 0.9957 | Train acc: 51.00% | Val loss: 0.9917 | Val acc: 54.01% | LR: 0.000012
Epoch: 067 | Train loss: 0.9961 | Train acc: 50.45% | Val loss: 0.9908 | Val acc: 53.90% | LR: 0.000012
Epoch: 068 | Train loss: 0.9965 | Train acc: 50.46% | Val loss: 0.9906 | Val acc: 53.90% | LR: 0.000012
Epoch: 069 | Train loss: 0.9955 | Train acc: 50.93% | Val loss: 0.9904 | Val acc: 53.76% | LR: 0.000012
Epoch: 070 | Train loss: 0.9942 | Train acc: 51.00% | Val loss: 0.9904 | Val acc: 53.68% | LR: 0.000011
Epoch: 071 | Train loss: 0.9966 | Train acc: 50.62% | Val loss: 0.9905 | Val acc: 53.68% | LR: 0.000011
Epoch: 072 | Train loss: 0.9935 | Train acc: 51.19% | Val loss: 0.9917 | Val acc: 53.68% | LR: 0.000011
Epoch: 073 | Train loss: 0.9948 | Train acc: 51.42% | Val loss: 0.9904 | Val acc: 53.64% | LR: 0.000011
Epoch: 074 | Train loss: 0.9936 | Train acc: 50.81% | Val loss: 0.9906 | Val acc: 53.49% | LR: 0.000011
Epoch: 075 | Train loss: 0.9947 | Train acc: 50.70% | Val loss: 0.9905 | Val acc: 53.47% | LR: 0.000010
Epoch: 076 | Train loss: 0.9960 | Train acc: 50.86% | Val loss: 0.9902 | Val acc: 53.47% | LR: 0.000010
Epoch: 077 | Train loss: 0.9949 | Train acc: 51.13% | Val loss: 0.9911 | Val acc: 53.37% | LR: 0.000010
Epoch: 078 | Train loss: 0.9939 | Train acc: 51.15% | Val loss: 0.9904 | Val acc: 53.37% | LR: 0.000010
Epoch: 079 | Train loss: 0.9949 | Train acc: 51.06% | Val loss: 0.9908 | Val acc: 53.26% | LR: 0.000010
Epoch: 080 | Train loss: 0.9950 | Train acc: 50.78% | Val loss: 0.9901 | Val acc: 53.38% | LR: 0.000009
Epoch: 081 | Train loss: 0.9944 | Train acc: 50.97% | Val loss: 0.9903 | Val acc: 53.32% | LR: 0.000009
Epoch: 082 | Train loss: 0.9957 | Train acc: 50.34% | Val loss: 0.9908 | Val acc: 53.30% | LR: 0.000009
Epoch: 083 | Train loss: 0.9947 | Train acc: 51.14% | Val loss: 0.9906 | Val acc: 53.24% | LR: 0.000009

[I 2025-09-23 17:22:53,014] Trial 63 finished with value: 0.5316388010978699 and parameters: {'lr': 2.013732745908471e-05, 'hidden_size': 64, 'dropout': 0.16658133981814777, 'weight_decay': 0.0002801777099861928}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0041 | Train acc: 50.75% | Val loss: 1.0166 | Val acc: 45.91% | LR: 0.000018
Epoch: 001 | Train loss: 1.0017 | Train acc: 51.04% | Val loss: 1.0179 | Val acc: 46.03% | LR: 0.000018
Epoch: 002 | Train loss: 1.0004 | Train acc: 51.08% | Val loss: 1.0109 | Val acc: 46.29% | LR: 0.000018
Epoch: 003 | Train loss: 1.0003 | Train acc: 50.06% | Val loss: 1.0127 | Val acc: 46.21% | LR: 0.000018
Epoch: 004 | Train loss: 1.0032 | Train acc: 50.39% | Val loss: 1.0123 | Val acc: 45.86% | LR: 0.000018
Epoch: 005 | Train loss: 1.0020 | Train acc: 49.75% | Val loss: 1.0109 | Val acc: 45.98% | LR: 0.000018
Epoch: 006 | Train loss: 0.9996 | Train acc: 50.47% | Val loss: 1.0146 | Val acc: 46.07% | LR: 0.000018
Epoch: 007 | Train loss: 1.0035 | Train acc: 50.70% | Val loss: 1.0114 | Val acc: 45.78% | LR: 0.000018
Epoch: 008 | Train loss: 1.0010 | Train acc: 50.34% | Val loss: 1.0137 | Val acc: 46.01% | LR: 0.000018
Epoch: 009 | Train loss: 0.9995 | Train acc: 50.84% | Val loss: 1.0110 | Val acc: 45.86% | LR: 0.000018
Epoch: 010 | Train loss: 1.0000 | Train acc: 50.24% | Val loss: 1.0175 | Val acc: 45.72% | LR: 0.000018
Epoch: 011 | Train loss: 0.9989 | Train acc: 50.64% | Val loss: 1.0267 | Val acc: 46.14% | LR: 0.000018
Epoch: 012 | Train loss: 0.9987 | Train acc: 50.82% | Val loss: 1.0121 | Val acc: 46.15% | LR: 0.000018
Epoch: 013 | Train loss: 0.9988 | Train acc: 50.71% | Val loss: 1.0103 | Val acc: 46.57% | LR: 0.000018
Epoch: 014 | Train loss: 0.9990 | Train acc: 50.60% | Val loss: 1.0313 | Val acc: 46.28% | LR: 0.000018
Epoch: 015 | Train loss: 1.0000 | Train acc: 50.87% | Val loss: 1.0126 | Val acc: 46.10% | LR: 0.000018
Epoch: 016 | Train loss: 0.9972 | Train acc: 51.33% | Val loss: 1.0131 | Val acc: 46.23% | LR: 0.000018
Epoch: 017 | Train loss: 0.9992 | Train acc: 50.99% | Val loss: 1.0099 | Val acc: 46.17% | LR: 0.000018
Epoch: 018 | Train loss: 0.9978 | Train acc: 50.70% | Val loss: 1.0108 | Val acc: 46.18% | LR: 0.000018
Epoch: 019 | Train loss: 1.0002 | Train acc: 50.16% | Val loss: 1.0135 | Val acc: 46.09% | LR: 0.000018
Epoch: 020 | Train loss: 0.9998 | Train acc: 50.03% | Val loss: 1.1142 | Val acc: 45.93% | LR: 0.000018
Epoch: 021 | Train loss: 0.9980 | Train acc: 50.61% | Val loss: 1.0115 | Val acc: 46.13% | LR: 0.000017
Epoch: 022 | Train loss: 0.9995 | Train acc: 50.24% | Val loss: 1.0097 | Val acc: 46.23% | LR: 0.000017
Epoch: 023 | Train loss: 0.9979 | Train acc: 50.68% | Val loss: 1.0120 | Val acc: 46.20% | LR: 0.000017
Epoch: 024 | Train loss: 0.9964 | Train acc: 51.04% | Val loss: 1.0112 | Val acc: 46.28% | LR: 0.000017
Epoch: 025 | Train loss: 0.9978 | Train acc: 50.51% | Val loss: 1.0105 | Val acc: 46.25% | LR: 0.000017
Epoch: 026 | Train loss: 1.0123 | Train acc: 50.31% | Val loss: 1.0115 | Val acc: 46.25% | LR: 0.000017
Epoch: 027 | Train loss: 0.9984 | Train acc: 50.40% | Val loss: 1.0097 | Val acc: 46.01% | LR: 0.000017
Epoch: 028 | Train loss: 0.9986 | Train acc: 50.24% | Val loss: 1.0137 | Val acc: 46.19% | LR: 0.000017
Epoch: 029 | Train loss: 0.9971 | Train acc: 50.69% | Val loss: 1.0114 | Val acc: 46.09% | LR: 0.000017
Epoch: 030 | Train loss: 0.9997 | Train acc: 50.41% | Val loss: 1.0109 | Val acc: 46.13% | LR: 0.000017
Epoch: 031 | Train loss: 0.9976 | Train acc: 50.40% | Val loss: 1.0095 | Val acc: 46.25% | LR: 0.000016
Epoch: 032 | Train loss: 0.9972 | Train acc: 50.53% | Val loss: 1.0581 | Val acc: 46.15% | LR: 0.000016
Epoch: 033 | Train loss: 0.9961 | Train acc: 50.76% | Val loss: 1.0101 | Val acc: 46.17% | LR: 0.000016
Epoch: 034 | Train loss: 1.0003 | Train acc: 50.06% | Val loss: 1.0092 | Val acc: 46.17% | LR: 0.000016
Epoch: 035 | Train loss: 0.9977 | Train acc: 50.58% | Val loss: 1.0118 | Val acc: 46.17% | LR: 0.000016
Epoch: 036 | Train loss: 0.9991 | Train acc: 49.98% | Val loss: 1.0099 | Val acc: 46.13% | LR: 0.000016
Epoch: 037 | Train loss: 0.9973 | Train acc: 50.51% | Val loss: 1.0096 | Val acc: 46.15% | LR: 0.000016
Epoch: 038 | Train loss: 0.9970 | Train acc: 50.61% | Val loss: 1.0121 | Val acc: 46.13% | LR: 0.000016
Epoch: 039 | Train loss: 0.9970 | Train acc: 50.43% | Val loss: 1.0164 | Val acc: 46.11% | LR: 0.000015
Epoch: 040 | Train loss: 0.9970 | Train acc: 50.51% | Val loss: 1.0110 | Val acc: 45.99% | LR: 0.000015
Epoch: 041 | Train loss: 0.9964 | Train acc: 50.49% | Val loss: 1.0104 | Val acc: 46.11% | LR: 0.000015
Epoch: 042 | Train loss: 0.9957 | Train acc: 50.78% | Val loss: 1.0100 | Val acc: 46.11% | LR: 0.000015
Epoch: 043 | Train loss: 0.9968 | Train acc: 50.28% | Val loss: 1.0103 | Val acc: 46.07% | LR: 0.000015
Epoch: 044 | Train loss: 0.9940 | Train acc: 50.90% | Val loss: 1.0113 | Val acc: 45.91% | LR: 0.000015
Epoch: 045 | Train loss: 0.9951 | Train acc: 50.70% | Val loss: 1.0102 | Val acc: 45.99% | LR: 0.000015
Epoch: 046 | Train loss: 0.9968 | Train acc: 50.32% | Val loss: 1.0104 | Val acc: 46.01% | LR: 0.000014
Epoch: 047 | Train loss: 0.9959 | Train acc: 50.59% | Val loss: 1.0105 | Val acc: 45.95% | LR: 0.000014
Epoch: 048 | Train loss: 0.9976 | Train acc: 50.24% | Val loss: 1.0289 | Val acc: 45.99% | LR: 0.000014
Epoch: 049 | Train loss: 0.9972 | Train acc: 50.24% | Val loss: 1.0100 | Val acc: 46.01% | LR: 0.000014
Epoch: 050 | Train loss: 0.9982 | Train acc: 50.06% | Val loss: 1.0103 | Val acc: 46.03% | LR: 0.000014
Epoch: 051 | Train loss: 0.9995 | Train acc: 49.96% | Val loss: 1.0113 | Val acc: 45.99% | LR: 0.000014
Epoch: 052 | Train loss: 0.9995 | Train acc: 50.08% | Val loss: 1.0134 | Val acc: 46.01% | LR: 0.000014
Epoch: 053 | Train loss: 0.9966 | Train acc: 50.49% | Val loss: 1.0112 | Val acc: 46.01% | LR: 0.000013
Epoch: 054 | Train loss: 0.9981 | Train acc: 50.16% | Val loss: 1.0105 | Val acc: 45.95% | LR: 0.000013
Epoch: 055 | Train loss: 0.9933 | Train acc: 51.13% | Val loss: 1.0104 | Val acc: 45.93% | LR: 0.000013
Epoch: 056 | Train loss: 0.9954 | Train acc: 50.68% | Val loss: 1.0094 | Val acc: 46.07% | LR: 0.000013
Epoch: 057 | Train loss: 0.9959 | Train acc: 50.51% | Val loss: 1.0114 | Val acc: 45.99% | LR: 0.000013
Epoch: 058 | Train loss: 0.9960 | Train acc: 50.60% | Val loss: 1.0105 | Val acc: 45.91% | LR: 0.000013
Epoch: 059 | Train loss: 0.9980 | Train acc: 50.96% | Val loss: 1.0097 | Val acc: 46.01% | LR: 0.000012
Epoch: 060 | Train loss: 0.9992 | Train acc: 49.89% | Val loss: 1.0099 | Val acc: 46.01% | LR: 0.000012
Epoch: 061 | Train loss: 0.9963 | Train acc: 50.33% | Val loss: 1.0096 | Val acc: 46.07% | LR: 0.000012
Epoch: 062 | Train loss: 0.9968 | Train acc: 50.33% | Val loss: 1.0088 | Val acc: 46.15% | LR: 0.000012

[I 2025-09-23 17:23:46,454] Trial 64 finished with value: 0.4593097627162933 and parameters: {'lr': 1.8334741058871288e-05, 'hidden_size': 83, 'dropout': 0.35808231387329154, 'weight_decay': 0.00040729276935999934}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0005 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.05% | LR: 0.000010
Epoch: 001 | Train loss: 1.0006 | Train acc: 49.54% | Val loss: 0.9916 | Val acc: 54.05% | LR: 0.000010
Epoch: 002 | Train loss: 0.9996 | Train acc: 50.36% | Val loss: 0.9916 | Val acc: 54.07% | LR: 0.000010
Epoch: 003 | Train loss: 0.9994 | Train acc: 50.56% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000010
Epoch: 004 | Train loss: 1.0000 | Train acc: 50.17% | Val loss: 0.9917 | Val acc: 54.11% | LR: 0.000010
Epoch: 005 | Train loss: 0.9980 | Train acc: 50.87% | Val loss: 0.9917 | Val acc: 54.11% | LR: 0.000010
Epoch: 006 | Train loss: 0.9989 | Train acc: 50.52% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000010
Epoch: 007 | Train loss: 0.9999 | Train acc: 49.98% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000010
Epoch: 008 | Train loss: 1.0002 | Train acc: 49.72% | Val loss: 0.9918 | Val acc: 54.15% | LR: 0.000010
Epoch: 009 | Train loss: 0.9983 | Train acc: 50.60% | Val loss: 0.9919 | Val acc: 54.17% | LR: 0.000010
Epoch: 010 | Train loss: 0.9979 | Train acc: 50.78% | Val loss: 0.9919 | Val acc: 54.20% | LR: 0.000010
Epoch: 011 | Train loss: 0.9977 | Train acc: 50.87% | Val loss: 0.9918 | Val acc: 54.24% | LR: 0.000010
Epoch: 012 | Train loss: 0.9980 | Train acc: 50.69% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000010
Epoch: 013 | Train loss: 0.9984 | Train acc: 50.43% | Val loss: 0.9917 | Val acc: 54.32% | LR: 0.000010
Epoch: 014 | Train loss: 0.9987 | Train acc: 50.43% | Val loss: 0.9918 | Val acc: 54.34% | LR: 0.000010
Epoch: 015 | Train loss: 0.9990 | Train acc: 50.16% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000010
Epoch: 016 | Train loss: 0.9985 | Train acc: 50.60% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000010
Epoch: 017 | Train loss: 0.9981 | Train acc: 50.51% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000010
Epoch: 018 | Train loss: 0.9984 | Train acc: 50.25% | Val loss: 0.9917 | Val acc: 54.30% | LR: 0.000010
Epoch: 019 | Train loss: 0.9986 | Train acc: 50.34% | Val loss: 0.9917 | Val acc: 54.28% | LR: 0.000010
Epoch: 020 | Train loss: 0.9971 | Train acc: 51.15% | Val loss: 0.9917 | Val acc: 54.28% | LR: 0.000010
Epoch: 021 | Train loss: 0.9976 | Train acc: 50.61% | Val loss: 0.9917 | Val acc: 54.28% | LR: 0.000010
Epoch: 022 | Train loss: 0.9977 | Train acc: 50.78% | Val loss: 0.9916 | Val acc: 54.28% | LR: 0.000009
Epoch: 023 | Train loss: 0.9982 | Train acc: 50.25% | Val loss: 0.9916 | Val acc: 54.28% | LR: 0.000009
Epoch: 024 | Train loss: 0.9979 | Train acc: 50.43% | Val loss: 0.9916 | Val acc: 54.30% | LR: 0.000009
Epoch: 025 | Train loss: 0.9984 | Train acc: 50.06% | Val loss: 0.9916 | Val acc: 54.32% | LR: 0.000009
Epoch: 026 | Train loss: 0.9979 | Train acc: 50.13% | Val loss: 0.9915 | Val acc: 54.36% | LR: 0.000009
Epoch: 027 | Train loss: 0.9974 | Train acc: 50.76% | Val loss: 0.9916 | Val acc: 54.36% | LR: 0.000009
Epoch: 028 | Train loss: 0.9970 | Train acc: 50.89% | Val loss: 0.9915 | Val acc: 54.38% | LR: 0.000009
Epoch: 029 | Train loss: 0.9968 | Train acc: 50.78% | Val loss: 0.9915 | Val acc: 54.34% | LR: 0.000009
Epoch: 030 | Train loss: 0.9982 | Train acc: 50.43% | Val loss: 0.9921 | Val acc: 54.38% | LR: 0.000009
Epoch: 031 | Train loss: 0.9986 | Train acc: 50.34% | Val loss: 0.9914 | Val acc: 54.44% | LR: 0.000009
Epoch: 032 | Train loss: 0.9956 | Train acc: 51.05% | Val loss: 0.9913 | Val acc: 54.38% | LR: 0.000009
Epoch: 033 | Train loss: 1.0031 | Train acc: 50.03% | Val loss: 0.9913 | Val acc: 54.40% | LR: 0.000009
Epoch: 034 | Train loss: 1.0247 | Train acc: 50.93% | Val loss: 0.9913 | Val acc: 54.40% | LR: 0.000009
Epoch: 035 | Train loss: 0.9979 | Train acc: 50.15% | Val loss: 0.9913 | Val acc: 54.38% | LR: 0.000009
Epoch: 036 | Train loss: 1.0859 | Train acc: 50.55% | Val loss: 0.9914 | Val acc: 54.44% | LR: 0.000009
Epoch: 037 | Train loss: 0.9993 | Train acc: 50.40% | Val loss: 0.9913 | Val acc: 54.42% | LR: 0.000009
Epoch: 038 | Train loss: 0.9986 | Train acc: 50.29% | Val loss: 0.9913 | Val acc: 54.34% | LR: 0.000009
Epoch: 039 | Train loss: 1.0018 | Train acc: 50.79% | Val loss: 1.0057 | Val acc: 54.32% | LR: 0.000009
Epoch: 040 | Train loss: 0.9953 | Train acc: 50.57% | Val loss: 0.9913 | Val acc: 54.36% | LR: 0.000008
Epoch: 041 | Train loss: 0.9983 | Train acc: 50.30% | Val loss: 0.9913 | Val acc: 54.30% | LR: 0.000008
Epoch: 042 | Train loss: 0.9968 | Train acc: 50.48% | Val loss: 0.9913 | Val acc: 54.28% | LR: 0.000008
Epoch: 043 | Train loss: 0.9962 | Train acc: 50.41% | Val loss: 0.9913 | Val acc: 54.30% | LR: 0.000008
Epoch: 044 | Train loss: 1.1050 | Train acc: 50.03% | Val loss: 0.9913 | Val acc: 54.30% | LR: 0.000008
Epoch: 045 | Train loss: 0.9958 | Train acc: 50.47% | Val loss: 0.9913 | Val acc: 54.30% | LR: 0.000008
Epoch: 046 | Train loss: 0.9973 | Train acc: 50.82% | Val loss: 0.9913 | Val acc: 54.30% | LR: 0.000008
Epoch: 047 | Train loss: 0.9953 | Train acc: 50.01% | Val loss: 0.9913 | Val acc: 54.26% | LR: 0.000008
Epoch: 048 | Train loss: 0.9974 | Train acc: 50.36% | Val loss: 0.9913 | Val acc: 54.33% | LR: 0.000008
Epoch: 049 | Train loss: 0.9969 | Train acc: 50.36% | Val loss: 0.9913 | Val acc: 54.28% | LR: 0.000008
Epoch: 050 | Train loss: 0.9976 | Train acc: 50.00% | Val loss: 0.9926 | Val acc: 54.26% | LR: 0.000008
Epoch: 051 | Train loss: 0.9957 | Train acc: 50.25% | Val loss: 0.9913 | Val acc: 54.24% | LR: 0.000008
Epoch: 052 | Train loss: 1.0008 | Train acc: 50.24% | Val loss: 0.9913 | Val acc: 54.22% | LR: 0.000008
Epoch: 053 | Train loss: 0.9973 | Train acc: 50.10% | Val loss: 0.9913 | Val acc: 54.22% | LR: 0.000007
Epoch: 054 | Train loss: 0.9946 | Train acc: 50.43% | Val loss: 0.9913 | Val acc: 54.22% | LR: 0.000007
Epoch: 055 | Train loss: 1.0015 | Train acc: 50.49% | Val loss: 0.9913 | Val acc: 54.22% | LR: 0.000007
Epoch: 056 | Train loss: 0.9967 | Train acc: 50.68% | Val loss: 0.9913 | Val acc: 54.24% | LR: 0.000007
Epoch: 057 | Train loss: 1.0037 | Train acc: 50.07% | Val loss: 0.9914 | Val acc: 54.32% | LR: 0.000007
Epoch: 058 | Train loss: 0.9977 | Train acc: 50.21% | Val loss: 0.9913 | Val acc: 54.30% | LR: 0.000007
Epoch: 059 | Train loss: 0.9948 | Train acc: 50.73% | Val loss: 0.9913 | Val acc: 54.30% | LR: 0.000007
Epoch: 060 | Train loss: 0.9931 | Train acc: 50.45% | Val loss: 0.9913 | Val acc: 54.30% | LR: 0.000007
Epoch: 061 | Train loss: 0.9941 | Train acc: 50.19% | Val loss: 0.9913 | Val acc: 54.32% | LR: 0.000007
Epoch: 062 | Train loss: 0.9918 | Train acc: 50.33% | Val loss: 0.9912 | Val acc: 54.30% | LR: 0.000007
Epoch: 063 | Train loss: 0.9972 | Train acc: 50.12% | Val loss: 0.9913 | Val acc: 54.24% | LR: 0.000007
Epoch: 064 | Train loss: 0.9938 | Train acc: 50.57% | Val loss: 0.9914 | Val acc: 54.20% | LR: 0.000006
Epoch: 065 | Train loss: 0.9965 | Train acc: 50.49% | Val loss: 0.9914 | Val acc: 54.20% | LR: 0.000006
Epoch: 066 | Train loss: 0.9995 | Train acc: 50.02% | Val loss: 0.9914 | Val acc: 54.20% | LR: 0.000006
Epoch: 067 | Train loss: 0.9955 | Train acc: 50.86% | Val loss: 0.9914 | Val acc: 54.20% | LR: 0.000006
Epoch: 068 | Train loss: 0.9966 | Train acc: 50.56% | Val loss: 0.9914 | Val acc: 54.20% | LR: 0.000006
Epoch: 069 | Train loss: 0.9956 | Train acc: 50.43% | Val loss: 0.9914 | Val acc: 54.20% | LR: 0.000006
Epoch: 070 | Train loss: 0.9936 | Train acc: 50.82% | Val loss: 0.9914 | Val acc: 54.22% | LR: 0.000006
Epoch: 071 | Train loss: 0.9962 | Train acc: 50.59% | Val loss: 0.9914 | Val acc: 54.14% | LR: 0.000006
Epoch: 072 | Train loss: 0.9916 | Train acc: 50.42% | Val loss: 0.9914 | Val acc: 54.18% | LR: 0.000006
Epoch: 073 | Train loss: 0.9980 | Train acc: 49.58% | Val loss: 0.9914 | Val acc: 54.20% | LR: 0.000006
Epoch: 074 | Train loss: 0.9959 | Train acc: 50.93% | Val loss: 0.9914 | Val acc: 54.18% | LR: 0.000006
Epoch: 075 | Train loss: 0.9919 | Train acc: 50.83% | Val loss: 0.9914 | Val acc: 54.20% | LR: 0.000005
Epoch: 076 | Train loss: 0.9953 | Train acc: 50.37% | Val loss: 0.9914 | Val acc: 54.20% | LR: 0.000005
Epoch: 077 | Train loss: 0.9954 | Train acc: 50.16% | Val loss: 0.9912 | Val acc: 54.24% | LR: 0.000005
Epoch: 078 | Train loss: 0.9936 | Train acc: 50.47% | Val loss: 0.9914 | Val acc: 54.24% | LR: 0.000005
Epoch: 079 | Train loss: 0.9942 | Train acc: 50.53% | Val loss: 0.9914 | Val acc: 54.24% | LR: 0.000005
Epoch: 080 | Train loss: 0.9936 | Train acc: 50.88% | Val loss: 0.9914 | Val acc: 54.28% | LR: 0.000005

[I 2025-09-23 17:24:51,782] Trial 65 finished with value: 0.5431876420974732 and parameters: {'lr': 1.0008088630600493e-05, 'hidden_size': 64, 'dropout': 0.38942510207353215, 'weight_decay': 9.86609816667667e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9972 | Train acc: 50.51% | Val loss: 1.0170 | Val acc: 46.97% | LR: 0.002902
Epoch: 001 | Train loss: 1.0009 | Train acc: 49.88% | Val loss: 1.0096 | Val acc: 48.80% | LR: 0.002902
Epoch: 002 | Train loss: 0.9809 | Train acc: 51.34% | Val loss: 1.0022 | Val acc: 49.72% | LR: 0.002900
Epoch: 003 | Train loss: 0.9832 | Train acc: 51.12% | Val loss: 1.0078 | Val acc: 49.46% | LR: 0.002898
Epoch: 004 | Train loss: 0.9901 | Train acc: 50.55% | Val loss: 1.0314 | Val acc: 47.77% | LR: 0.002895
Epoch: 005 | Train loss: 0.9949 | Train acc: 50.56% | Val loss: 0.9815 | Val acc: 51.18% | LR: 0.002891
Epoch: 006 | Train loss: 0.9832 | Train acc: 51.18% | Val loss: 1.0053 | Val acc: 49.84% | LR: 0.002887
Epoch: 007 | Train loss: 0.9895 | Train acc: 50.83% | Val loss: 1.0097 | Val acc: 49.21% | LR: 0.002882
Epoch: 008 | Train loss: 0.9891 | Train acc: 50.85% | Val loss: 1.0156 | Val acc: 49.60% | LR: 0.002877
Epoch: 009 | Train loss: 0.9914 | Train acc: 50.90% | Val loss: 0.9983 | Val acc: 50.27% | LR: 0.002871
Epoch: 010 | Train loss: 0.9877 | Train acc: 50.91% | Val loss: 0.9649 | Val acc: 52.62% | LR: 0.002864
Epoch: 011 | Train loss: 0.9921 | Train acc: 50.63% | Val loss: 0.9800 | Val acc: 51.13% | LR: 0.002857
Epoch: 012 | Train loss: 0.9780 | Train acc: 51.28% | Val loss: 0.9904 | Val acc: 50.72% | LR: 0.002849
Epoch: 013 | Train loss: 0.9896 | Train acc: 50.58% | Val loss: 1.0104 | Val acc: 50.52% | LR: 0.002841
Epoch: 014 | Train loss: 1.0003 | Train acc: 49.81% | Val loss: 1.0164 | Val acc: 51.45% | LR: 0.002832
Epoch: 015 | Train loss: 0.9945 | Train acc: 50.27% | Val loss: 1.0299 | Val acc: 46.13% | LR: 0.002822
Epoch: 016 | Train loss: 1.0145 | Train acc: 50.53% | Val loss: 1.3021 | Val acc: 50.16% | LR: 0.002812
Epoch: 017 | Train loss: 0.9874 | Train acc: 51.13% | Val loss: 0.9993 | Val acc: 49.91% | LR: 0.002801
Epoch: 018 | Train loss: 0.9850 | Train acc: 50.79% | Val loss: 1.0327 | Val acc: 49.23% | LR: 0.002789
Epoch: 019 | Train loss: 0.9919 | Train acc: 51.15% | Val loss: 1.0077 | Val acc: 49.80% | LR: 0.002777
Epoch: 020 | Train loss: 0.9986 | Train acc: 50.41% | Val loss: 1.0148 | Val acc: 49.74% | LR: 0.002765
Epoch: 021 | Train loss: 0.9939 | Train acc: 50.60% | Val loss: 1.0183 | Val acc: 47.39% | LR: 0.002752
Epoch: 022 | Train loss: 0.9936 | Train acc: 50.42% | Val loss: 1.0093 | Val acc: 48.77% | LR: 0.002738
Epoch: 023 | Train loss: 0.9925 | Train acc: 50.72% | Val loss: 1.0424 | Val acc: 49.80% | LR: 0.002723
Epoch: 024 | Train loss: 0.9911 | Train acc: 50.72% | Val loss: 1.0021 | Val acc: 50.05% | LR: 0.002708
Epoch: 025 | Train loss: 0.9913 | Train acc: 51.09% | Val loss: 0.9954 | Val acc: 50.03% | LR: 0.002693
Epoch: 026 | Train loss: 0.9926 | Train acc: 50.57% | Val loss: 0.9817 | Val acc: 50.96% | LR: 0.002677
Epoch: 027 | Train loss: 0.9914 | Train acc: 50.43% | Val loss: 0.9702 | Val acc: 54.77% | LR: 0.002660
Epoch: 028 | Train loss: 0.9894 | Train acc: 50.65% | Val loss: 0.9682 | Val acc: 54.67% | LR: 0.002643
Epoch: 029 | Train loss: 0.9826 | Train acc: 51.27% | Val loss: 0.9788 | Val acc: 50.32% | LR: 0.002626
Epoch: 030 | Train loss: 0.9822 | Train acc: 51.31% | Val loss: 0.9858 | Val acc: 49.93% | LR: 0.002608
Epoch: 031 | Train loss: 0.9795 | Train acc: 51.29% | Val loss: 1.0087 | Val acc: 48.92% | LR: 0.002589
Epoch: 032 | Train loss: 0.9893 | Train acc: 51.29% | Val loss: 1.0055 | Val acc: 48.60% | LR: 0.002570
Epoch: 033 | Train loss: 0.9863 | Train acc: 50.81% | Val loss: 1.0105 | Val acc: 48.91% | LR: 0.002550
Epoch: 034 | Train loss: 0.9851 | Train acc: 51.08% | Val loss: 0.9952 | Val acc: 50.16% | LR: 0.002530
Epoch: 035 | Train loss: 0.9914 | Train acc: 50.80% | Val loss: 0.9658 | Val acc: 51.78% | LR: 0.002510
Epoch: 036 | Train loss: 0.9858 | Train acc: 51.09% | Val loss: 1.1335 | Val acc: 52.20% | LR: 0.002489
Epoch: 037 | Train loss: 0.9796 | Train acc: 51.22% | Val loss: 0.9908 | Val acc: 50.53% | LR: 0.002467
Epoch: 038 | Train loss: 0.9872 | Train acc: 51.08% | Val loss: 1.0333 | Val acc: 48.81% | LR: 0.002445
Epoch: 039 | Train loss: 0.9934 | Train acc: 50.97% | Val loss: 1.0147 | Val acc: 49.52% | LR: 0.002423
Epoch: 040 | Train loss: 0.9805 | Train acc: 51.38% | Val loss: 1.0258 | Val acc: 49.73% | LR: 0.002400
Epoch: 041 | Train loss: 0.9966 | Train acc: 50.93% | Val loss: 0.9933 | Val acc: 49.60% | LR: 0.002377
Epoch: 042 | Train loss: 0.9814 | Train acc: 51.38% | Val loss: 0.9991 | Val acc: 50.78% | LR: 0.002353
Epoch: 043 | Train loss: 0.9855 | Train acc: 51.14% | Val loss: 1.0366 | Val acc: 50.33% | LR: 0.002329
Epoch: 044 | Train loss: 0.9922 | Train acc: 50.57% | Val loss: 0.9973 | Val acc: 49.85% | LR: 0.002305
Epoch: 045 | Train loss: 0.9854 | Train acc: 50.97% | Val loss: 1.2683 | Val acc: 50.18% | LR: 0.002280
Epoch: 046 | Train loss: 0.9865 | Train acc: 51.15% | Val loss: 0.9954 | Val acc: 49.59% | LR: 0.002255
Epoch: 047 | Train loss: 0.9868 | Train acc: 50.77% | Val loss: 0.9963 | Val acc: 49.92% | LR: 0.002229
Epoch: 048 | Train loss: 0.9735 | Train acc: 51.79% | Val loss: 0.9892 | Val acc: 50.06% | LR: 0.002204
Epoch: 049 | Train loss: 0.9853 | Train acc: 50.87% | Val loss: 0.9890 | Val acc: 50.95% | LR: 0.002177
Epoch: 050 | Train loss: 0.9805 | Train acc: 51.05% | Val loss: 0.9911 | Val acc: 50.02% | LR: 0.002151
Epoch: 051 | Train loss: 0.9872 | Train acc: 50.86% | Val loss: 1.0142 | Val acc: 49.34% | LR: 0.002124
Epoch: 052 | Train loss: 0.9868 | Train acc: 51.08% | Val loss: 1.0139 | Val acc: 49.12% | LR: 0.002097
Epoch: 053 | Train loss: 0.9834 | Train acc: 51.25% | Val loss: 1.0095 | Val acc: 49.10% | LR: 0.002070
Epoch: 054 | Train loss: 0.9862 | Train acc: 51.12% | Val loss: 0.9874 | Val acc: 50.38% | LR: 0.002042
Epoch: 055 | Train loss: 0.9756 | Train acc: 51.56% | Val loss: 0.9903 | Val acc: 50.91% | LR: 0.002014
Epoch: 056 | Train loss: 0.9783 | Train acc: 51.26% | Val loss: 0.9638 | Val acc: 51.81% | LR: 0.001986
Epoch: 057 | Train loss: 0.9814 | Train acc: 51.05% | Val loss: 0.9787 | Val acc: 51.59% | LR: 0.001958
Epoch: 058 | Train loss: 0.9873 | Train acc: 50.70% | Val loss: 0.9853 | Val acc: 51.20% | LR: 0.001929
Epoch: 059 | Train loss: 1.0693 | Train acc: 50.80% | Val loss: 0.9909 | Val acc: 50.72% | LR: 0.001900
Epoch: 060 | Train loss: 0.9809 | Train acc: 51.05% | Val loss: 0.9849 | Val acc: 51.04% | LR: 0.001871
Epoch: 061 | Train loss: 0.9846 | Train acc: 50.90% | Val loss: 0.9809 | Val acc: 51.38% | LR: 0.001842
Epoch: 062 | Train loss: 0.9756 | Train acc: 51.38% | Val loss: 0.9875 | Val acc: 51.27% | LR: 0.001813
Epoch: 063 | Train loss: 0.9895 | Train acc: 50.60% | Val loss: 0.9858 | Val acc: 51.10% | LR: 0.001783
Epoch: 064 | Train loss: 0.9836 | Train acc: 51.18% | Val loss: 0.9732 | Val acc: 51.49% | LR: 0.001754
Epoch: 065 | Train loss: 0.9876 | Train acc: 50.67% | Val loss: 0.9835 | Val acc: 51.29% | LR: 0.001724
Epoch: 066 | Train loss: 0.9826 | Train acc: 51.07% | Val loss: 1.0194 | Val acc: 50.85% | LR: 0.001694
Epoch: 067 | Train loss: 0.9900 | Train acc: 50.70% | Val loss: 1.0074 | Val acc: 51.09% | LR: 0.001664
Epoch: 068 | Train loss: 0.9828 | Train acc: 51.18% | Val loss: 1.0558 | Val acc: 52.10% | LR: 0.001634
Epoch: 069 | Train loss: 0.9834 | Train acc: 51.04% | Val loss: 0.9946 | Val acc: 51.39% | LR: 0.001604
Epoch: 070 | Train loss: 0.9828 | Train acc: 51.26% | Val loss: 0.9978 | Val acc: 51.27% | LR: 0.001573
Epoch: 071 | Train loss: 0.9895 | Train acc: 50.60% | Val loss: 0.9815 | Val acc: 51.35% | LR: 0.001543
Epoch: 072 | Train loss: 0.9830 | Train acc: 50.92% | Val loss: 0.9805 | Val acc: 51.53% | LR: 0.001513
Epoch: 073 | Train loss: 0.9836 | Train acc: 50.94% | Val loss: 1.0171 | Val acc: 51.75% | LR: 0.001482
Epoch: 074 | Train loss: 0.9855 | Train acc: 50.81% | Val loss: 0.9879 | Val acc: 51.81% | LR: 0.001452
Epoch: 075 | Train loss: 0.9839 | Train acc: 50.99% | Val loss: 0.9798 | Val acc: 51.73% | LR: 0.001422
Epoch: 076 | Train loss: 0.9867 | Train acc: 50.66% | Val loss: 0.9736 | Val acc: 51.97% | LR: 0.001391

[I 2025-09-23 17:25:58,440] Trial 66 finished with value: 0.5221166610717773 and parameters: {'lr': 0.002902815331373641, 'hidden_size': 91, 'dropout': 0.38573570716908756, 'weight_decay': 8.85695994976388e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0001 | Train acc: 50.25% | Val loss: 0.9995 | Val acc: 51.13% | LR: 0.000010
Epoch: 001 | Train loss: 1.0001 | Train acc: 50.15% | Val loss: 0.9995 | Val acc: 51.42% | LR: 0.000010
Epoch: 002 | Train loss: 1.0000 | Train acc: 50.00% | Val loss: 0.9993 | Val acc: 52.03% | LR: 0.000010
Epoch: 003 | Train loss: 0.9997 | Train acc: 50.80% | Val loss: 0.9992 | Val acc: 52.23% | LR: 0.000010
Epoch: 004 | Train loss: 1.0004 | Train acc: 49.88% | Val loss: 0.9991 | Val acc: 52.65% | LR: 0.000010
Epoch: 005 | Train loss: 0.9999 | Train acc: 50.32% | Val loss: 0.9989 | Val acc: 52.64% | LR: 0.000010
Epoch: 006 | Train loss: 0.9996 | Train acc: 50.60% | Val loss: 0.9990 | Val acc: 52.83% | LR: 0.000010
Epoch: 007 | Train loss: 0.9989 | Train acc: 51.06% | Val loss: 0.9990 | Val acc: 52.52% | LR: 0.000010
Epoch: 008 | Train loss: 1.0004 | Train acc: 49.77% | Val loss: 0.9989 | Val acc: 52.45% | LR: 0.000010
Epoch: 009 | Train loss: 0.9992 | Train acc: 50.78% | Val loss: 0.9988 | Val acc: 52.69% | LR: 0.000010
Epoch: 010 | Train loss: 0.9996 | Train acc: 50.36% | Val loss: 0.9987 | Val acc: 52.47% | LR: 0.000010
Epoch: 011 | Train loss: 0.9990 | Train acc: 50.64% | Val loss: 0.9985 | Val acc: 52.52% | LR: 0.000010
Epoch: 012 | Train loss: 0.9988 | Train acc: 50.77% | Val loss: 0.9984 | Val acc: 52.44% | LR: 0.000010
Epoch: 013 | Train loss: 0.9985 | Train acc: 51.11% | Val loss: 0.9984 | Val acc: 52.21% | LR: 0.000010
Epoch: 014 | Train loss: 0.9987 | Train acc: 50.68% | Val loss: 0.9982 | Val acc: 52.32% | LR: 0.000010
Epoch: 015 | Train loss: 0.9989 | Train acc: 50.43% | Val loss: 0.9981 | Val acc: 52.24% | LR: 0.000010
Epoch: 016 | Train loss: 0.9995 | Train acc: 50.43% | Val loss: 0.9980 | Val acc: 52.28% | LR: 0.000010
Epoch: 017 | Train loss: 0.9985 | Train acc: 50.88% | Val loss: 0.9980 | Val acc: 52.42% | LR: 0.000010
Epoch: 018 | Train loss: 0.9987 | Train acc: 50.63% | Val loss: 0.9979 | Val acc: 52.33% | LR: 0.000010
Epoch: 019 | Train loss: 0.9980 | Train acc: 50.89% | Val loss: 0.9977 | Val acc: 52.32% | LR: 0.000010
Epoch: 020 | Train loss: 0.9993 | Train acc: 50.28% | Val loss: 0.9976 | Val acc: 52.17% | LR: 0.000010
Epoch: 021 | Train loss: 0.9971 | Train acc: 51.08% | Val loss: 0.9975 | Val acc: 52.32% | LR: 0.000010
Epoch: 022 | Train loss: 0.9981 | Train acc: 50.74% | Val loss: 0.9974 | Val acc: 52.36% | LR: 0.000010
Epoch: 023 | Train loss: 0.9980 | Train acc: 50.81% | Val loss: 0.9972 | Val acc: 52.50% | LR: 0.000010
Epoch: 024 | Train loss: 0.9972 | Train acc: 50.92% | Val loss: 0.9971 | Val acc: 52.36% | LR: 0.000009
Epoch: 025 | Train loss: 0.9972 | Train acc: 51.07% | Val loss: 0.9972 | Val acc: 52.31% | LR: 0.000009
Epoch: 026 | Train loss: 0.9980 | Train acc: 50.74% | Val loss: 0.9970 | Val acc: 52.27% | LR: 0.000009
Epoch: 027 | Train loss: 0.9971 | Train acc: 51.09% | Val loss: 0.9968 | Val acc: 52.32% | LR: 0.000009
Epoch: 028 | Train loss: 0.9986 | Train acc: 50.91% | Val loss: 0.9967 | Val acc: 52.27% | LR: 0.000009
Epoch: 029 | Train loss: 0.9982 | Train acc: 50.83% | Val loss: 0.9966 | Val acc: 52.27% | LR: 0.000009
Epoch: 030 | Train loss: 0.9983 | Train acc: 50.74% | Val loss: 0.9965 | Val acc: 52.25% | LR: 0.000009
Epoch: 031 | Train loss: 0.9962 | Train acc: 51.42% | Val loss: 0.9964 | Val acc: 52.11% | LR: 0.000009
Epoch: 032 | Train loss: 0.9966 | Train acc: 51.18% | Val loss: 0.9964 | Val acc: 52.05% | LR: 0.000009
Epoch: 033 | Train loss: 0.9967 | Train acc: 51.20% | Val loss: 0.9962 | Val acc: 52.16% | LR: 0.000009
Epoch: 034 | Train loss: 0.9980 | Train acc: 50.62% | Val loss: 0.9960 | Val acc: 52.20% | LR: 0.000009
Epoch: 035 | Train loss: 0.9965 | Train acc: 50.99% | Val loss: 0.9960 | Val acc: 52.16% | LR: 0.000009
Epoch: 036 | Train loss: 0.9961 | Train acc: 51.18% | Val loss: 0.9960 | Val acc: 52.17% | LR: 0.000009
Epoch: 037 | Train loss: 0.9974 | Train acc: 50.72% | Val loss: 0.9958 | Val acc: 52.25% | LR: 0.000009
Epoch: 038 | Train loss: 0.9948 | Train acc: 51.52% | Val loss: 0.9958 | Val acc: 52.19% | LR: 0.000009
Epoch: 039 | Train loss: 0.9970 | Train acc: 50.97% | Val loss: 0.9957 | Val acc: 52.07% | LR: 0.000009
Epoch: 040 | Train loss: 0.9940 | Train acc: 51.59% | Val loss: 0.9956 | Val acc: 51.89% | LR: 0.000009
Epoch: 041 | Train loss: 0.9997 | Train acc: 50.27% | Val loss: 0.9955 | Val acc: 51.83% | LR: 0.000008
Epoch: 042 | Train loss: 0.9960 | Train acc: 51.06% | Val loss: 0.9954 | Val acc: 51.81% | LR: 0.000008
Epoch: 043 | Train loss: 0.9973 | Train acc: 50.79% | Val loss: 0.9952 | Val acc: 51.95% | LR: 0.000008
Epoch: 044 | Train loss: 0.9952 | Train acc: 51.13% | Val loss: 0.9952 | Val acc: 51.87% | LR: 0.000008
Epoch: 045 | Train loss: 0.9948 | Train acc: 51.32% | Val loss: 0.9950 | Val acc: 51.95% | LR: 0.000008
Epoch: 046 | Train loss: 0.9964 | Train acc: 50.89% | Val loss: 0.9948 | Val acc: 51.97% | LR: 0.000008
Epoch: 047 | Train loss: 0.9955 | Train acc: 50.99% | Val loss: 0.9947 | Val acc: 52.05% | LR: 0.000008
Epoch: 048 | Train loss: 0.9924 | Train acc: 51.40% | Val loss: 0.9947 | Val acc: 51.89% | LR: 0.000008
Epoch: 049 | Train loss: 0.9962 | Train acc: 50.87% | Val loss: 0.9946 | Val acc: 51.99% | LR: 0.000008
Epoch: 050 | Train loss: 0.9960 | Train acc: 50.87% | Val loss: 0.9944 | Val acc: 51.99% | LR: 0.000008
Epoch: 051 | Train loss: 0.9957 | Train acc: 50.79% | Val loss: 0.9942 | Val acc: 52.07% | LR: 0.000008
Epoch: 052 | Train loss: 0.9943 | Train acc: 51.15% | Val loss: 0.9941 | Val acc: 52.11% | LR: 0.000008
Epoch: 053 | Train loss: 0.9949 | Train acc: 51.08% | Val loss: 0.9939 | Val acc: 52.03% | LR: 0.000007
Epoch: 054 | Train loss: 0.9938 | Train acc: 51.16% | Val loss: 0.9938 | Val acc: 52.03% | LR: 0.000007
Epoch: 055 | Train loss: 0.9966 | Train acc: 50.81% | Val loss: 0.9936 | Val acc: 52.09% | LR: 0.000007

[I 2025-09-23 17:26:48,763] Trial 67 finished with value: 0.5212937474250794 and parameters: {'lr': 1.0109941816697553e-05, 'hidden_size': 101, 'dropout': 0.3728352049344443, 'weight_decay': 2.7447426500630172e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9973 | Train acc: 50.19% | Val loss: 1.0052 | Val acc: 46.03% | LR: 0.000011
Epoch: 001 | Train loss: 0.9966 | Train acc: 50.10% | Val loss: 1.0051 | Val acc: 46.01% | LR: 0.000011
Epoch: 002 | Train loss: 1.0004 | Train acc: 49.57% | Val loss: 1.0050 | Val acc: 46.03% | LR: 0.000011
Epoch: 003 | Train loss: 0.9984 | Train acc: 49.67% | Val loss: 1.0049 | Val acc: 46.07% | LR: 0.000011
Epoch: 004 | Train loss: 0.9947 | Train acc: 50.39% | Val loss: 1.0048 | Val acc: 46.11% | LR: 0.000011
Epoch: 005 | Train loss: 0.9989 | Train acc: 50.19% | Val loss: 1.0048 | Val acc: 46.09% | LR: 0.000011
Epoch: 006 | Train loss: 0.9956 | Train acc: 50.20% | Val loss: 1.0048 | Val acc: 46.09% | LR: 0.000011
Epoch: 007 | Train loss: 0.9947 | Train acc: 50.12% | Val loss: 1.0046 | Val acc: 46.11% | LR: 0.000011
Epoch: 008 | Train loss: 0.9966 | Train acc: 49.95% | Val loss: 1.0046 | Val acc: 46.11% | LR: 0.000011
Epoch: 009 | Train loss: 1.0011 | Train acc: 49.42% | Val loss: 1.0045 | Val acc: 46.05% | LR: 0.000011
Epoch: 010 | Train loss: 0.9967 | Train acc: 50.13% | Val loss: 1.0045 | Val acc: 46.07% | LR: 0.000011
Epoch: 011 | Train loss: 0.9951 | Train acc: 50.48% | Val loss: 1.0044 | Val acc: 46.19% | LR: 0.000011
Epoch: 012 | Train loss: 0.9960 | Train acc: 50.15% | Val loss: 1.0044 | Val acc: 46.27% | LR: 0.000011
Epoch: 013 | Train loss: 0.9966 | Train acc: 50.19% | Val loss: 1.0043 | Val acc: 46.25% | LR: 0.000011
Epoch: 014 | Train loss: 0.9940 | Train acc: 50.53% | Val loss: 1.0042 | Val acc: 46.37% | LR: 0.000011
Epoch: 015 | Train loss: 0.9953 | Train acc: 50.43% | Val loss: 1.0040 | Val acc: 46.19% | LR: 0.000011
Epoch: 016 | Train loss: 0.9949 | Train acc: 50.10% | Val loss: 1.0039 | Val acc: 46.21% | LR: 0.000011
Epoch: 017 | Train loss: 0.9951 | Train acc: 50.43% | Val loss: 1.0039 | Val acc: 46.25% | LR: 0.000011
Epoch: 018 | Train loss: 0.9892 | Train acc: 51.32% | Val loss: 1.0039 | Val acc: 46.41% | LR: 0.000011
Epoch: 019 | Train loss: 0.9918 | Train acc: 50.96% | Val loss: 1.0039 | Val acc: 46.41% | LR: 0.000011
Epoch: 020 | Train loss: 0.9978 | Train acc: 50.32% | Val loss: 1.0037 | Val acc: 46.62% | LR: 0.000011
Epoch: 021 | Train loss: 0.9948 | Train acc: 50.27% | Val loss: 1.0037 | Val acc: 46.64% | LR: 0.000011
Epoch: 022 | Train loss: 0.9925 | Train acc: 50.97% | Val loss: 1.0035 | Val acc: 46.53% | LR: 0.000011
Epoch: 023 | Train loss: 0.9962 | Train acc: 50.56% | Val loss: 1.0035 | Val acc: 46.74% | LR: 0.000011
Epoch: 024 | Train loss: 0.9906 | Train acc: 51.20% | Val loss: 1.0034 | Val acc: 46.86% | LR: 0.000011
Epoch: 025 | Train loss: 0.9937 | Train acc: 50.68% | Val loss: 1.0034 | Val acc: 46.88% | LR: 0.000011
Epoch: 026 | Train loss: 0.9958 | Train acc: 50.29% | Val loss: 1.0033 | Val acc: 46.77% | LR: 0.000011
Epoch: 027 | Train loss: 0.9912 | Train acc: 51.01% | Val loss: 1.0032 | Val acc: 46.75% | LR: 0.000011
Epoch: 028 | Train loss: 0.9904 | Train acc: 50.68% | Val loss: 1.0030 | Val acc: 46.67% | LR: 0.000011
Epoch: 029 | Train loss: 0.9898 | Train acc: 51.02% | Val loss: 1.0029 | Val acc: 46.94% | LR: 0.000010
Epoch: 030 | Train loss: 0.9929 | Train acc: 50.68% | Val loss: 1.0029 | Val acc: 47.10% | LR: 0.000010
Epoch: 031 | Train loss: 0.9929 | Train acc: 51.07% | Val loss: 1.0027 | Val acc: 47.05% | LR: 0.000010
Epoch: 032 | Train loss: 0.9938 | Train acc: 50.79% | Val loss: 1.0026 | Val acc: 47.05% | LR: 0.000010
Epoch: 033 | Train loss: 0.9927 | Train acc: 50.82% | Val loss: 1.0025 | Val acc: 47.16% | LR: 0.000010
Epoch: 034 | Train loss: 0.9966 | Train acc: 50.60% | Val loss: 1.0023 | Val acc: 47.28% | LR: 0.000010
Epoch: 035 | Train loss: 0.9920 | Train acc: 51.24% | Val loss: 1.0022 | Val acc: 47.38% | LR: 0.000010
Epoch: 036 | Train loss: 0.9942 | Train acc: 50.89% | Val loss: 1.0021 | Val acc: 47.42% | LR: 0.000010
Epoch: 037 | Train loss: 0.9919 | Train acc: 51.01% | Val loss: 1.0020 | Val acc: 47.47% | LR: 0.000010
Epoch: 038 | Train loss: 0.9945 | Train acc: 50.84% | Val loss: 1.0019 | Val acc: 47.49% | LR: 0.000010
Epoch: 039 | Train loss: 0.9886 | Train acc: 51.57% | Val loss: 1.0018 | Val acc: 47.69% | LR: 0.000010
Epoch: 040 | Train loss: 0.9872 | Train acc: 51.28% | Val loss: 1.0017 | Val acc: 47.87% | LR: 0.000010
Epoch: 041 | Train loss: 0.9917 | Train acc: 51.19% | Val loss: 1.0016 | Val acc: 48.04% | LR: 0.000010
Epoch: 042 | Train loss: 0.9942 | Train acc: 50.93% | Val loss: 1.0015 | Val acc: 48.13% | LR: 0.000009
Epoch: 043 | Train loss: 0.9922 | Train acc: 50.83% | Val loss: 1.0013 | Val acc: 48.35% | LR: 0.000009
Epoch: 044 | Train loss: 0.9989 | Train acc: 50.10% | Val loss: 1.0011 | Val acc: 48.60% | LR: 0.000009
Epoch: 045 | Train loss: 0.9934 | Train acc: 51.00% | Val loss: 1.0009 | Val acc: 48.60% | LR: 0.000009
Epoch: 046 | Train loss: 0.9852 | Train acc: 51.63% | Val loss: 1.0009 | Val acc: 48.74% | LR: 0.000009
Epoch: 047 | Train loss: 0.9924 | Train acc: 50.82% | Val loss: 1.0007 | Val acc: 48.88% | LR: 0.000009
Epoch: 048 | Train loss: 0.9946 | Train acc: 50.75% | Val loss: 1.0005 | Val acc: 48.92% | LR: 0.000009
Epoch: 049 | Train loss: 0.9947 | Train acc: 50.75% | Val loss: 1.0004 | Val acc: 49.06% | LR: 0.000009
Epoch: 050 | Train loss: 0.9896 | Train acc: 51.00% | Val loss: 1.0002 | Val acc: 49.33% | LR: 0.000009
Epoch: 051 | Train loss: 0.9943 | Train acc: 50.83% | Val loss: 1.0000 | Val acc: 49.31% | LR: 0.000009
Epoch: 052 | Train loss: 0.9890 | Train acc: 51.28% | Val loss: 0.9998 | Val acc: 49.33% | LR: 0.000009
Epoch: 053 | Train loss: 0.9899 | Train acc: 50.87% | Val loss: 0.9997 | Val acc: 49.29% | LR: 0.000008
Epoch: 054 | Train loss: 0.9869 | Train acc: 51.12% | Val loss: 0.9996 | Val acc: 49.33% | LR: 0.000008
Epoch: 055 | Train loss: 0.9955 | Train acc: 50.59% | Val loss: 0.9994 | Val acc: 49.43% | LR: 0.000008
Epoch: 056 | Train loss: 0.9888 | Train acc: 51.29% | Val loss: 0.9993 | Val acc: 49.53% | LR: 0.000008
Epoch: 057 | Train loss: 0.9962 | Train acc: 50.58% | Val loss: 0.9990 | Val acc: 49.59% | LR: 0.000008
Epoch: 058 | Train loss: 0.9897 | Train acc: 51.06% | Val loss: 0.9989 | Val acc: 49.55% | LR: 0.000008
Epoch: 059 | Train loss: 0.9977 | Train acc: 50.18% | Val loss: 0.9988 | Val acc: 49.61% | LR: 0.000008
Epoch: 060 | Train loss: 0.9921 | Train acc: 50.98% | Val loss: 0.9987 | Val acc: 49.63% | LR: 0.000008
Epoch: 061 | Train loss: 0.9936 | Train acc: 50.80% | Val loss: 0.9985 | Val acc: 49.60% | LR: 0.000008
Epoch: 062 | Train loss: 0.9909 | Train acc: 51.00% | Val loss: 0.9984 | Val acc: 49.67% | LR: 0.000008
Epoch: 063 | Train loss: 0.9929 | Train acc: 50.91% | Val loss: 0.9983 | Val acc: 49.69% | LR: 0.000007
Epoch: 064 | Train loss: 0.9870 | Train acc: 51.09% | Val loss: 0.9981 | Val acc: 49.78% | LR: 0.000007
Epoch: 065 | Train loss: 0.9842 | Train acc: 51.72% | Val loss: 0.9979 | Val acc: 49.83% | LR: 0.000007
Epoch: 066 | Train loss: 0.9907 | Train acc: 51.20% | Val loss: 0.9978 | Val acc: 49.90% | LR: 0.000007
Epoch: 067 | Train loss: 0.9902 | Train acc: 51.12% | Val loss: 0.9976 | Val acc: 50.04% | LR: 0.000007
Epoch: 068 | Train loss: 0.9932 | Train acc: 50.87% | Val loss: 0.9975 | Val acc: 50.20% | LR: 0.000007
Epoch: 069 | Train loss: 0.9890 | Train acc: 51.21% | Val loss: 0.9973 | Val acc: 50.34% | LR: 0.000007
Epoch: 070 | Train loss: 0.9951 | Train acc: 51.02% | Val loss: 0.9971 | Val acc: 50.34% | LR: 0.000007
Epoch: 071 | Train loss: 0.9904 | Train acc: 51.29% | Val loss: 0.9971 | Val acc: 50.37% | LR: 0.000007
Epoch: 072 | Train loss: 0.9885 | Train acc: 51.55% | Val loss: 0.9970 | Val acc: 50.39% | LR: 0.000006
Epoch: 073 | Train loss: 0.9923 | Train acc: 50.93% | Val loss: 0.9969 | Val acc: 50.44% | LR: 0.000006
Epoch: 074 | Train loss: 0.9908 | Train acc: 51.19% | Val loss: 0.9968 | Val acc: 50.52% | LR: 0.000006
Epoch: 075 | Train loss: 0.9953 | Train acc: 50.47% | Val loss: 0.9967 | Val acc: 50.56% | LR: 0.000006
Epoch: 076 | Train loss: 0.9860 | Train acc: 51.34% | Val loss: 0.9966 | Val acc: 50.56% | LR: 0.000006
Epoch: 077 | Train loss: 0.9929 | Train acc: 50.72% | Val loss: 0.9966 | Val acc: 50.59% | LR: 0.000006
Epoch: 078 | Train loss: 0.9847 | Train acc: 51.51% | Val loss: 0.9964 | Val acc: 50.59% | LR: 0.000006
Epoch: 079 | Train loss: 0.9892 | Train acc: 51.13% | Val loss: 0.9964 | Val acc: 50.61% | LR: 0.000006
Epoch: 080 | Train loss: 0.9905 | Train acc: 50.96% | Val loss: 0.9963 | Val acc: 50.66% | LR: 0.000006
Epoch: 081 | Train loss: 0.9945 | Train acc: 50.43% | Val loss: 0.9963 | Val acc: 50.68% | LR: 0.000005
Epoch: 082 | Train loss: 0.9923 | Train acc: 50.25% | Val loss: 0.9962 | Val acc: 50.68% | LR: 0.000005
Epoch: 083 | Train loss: 0.9940 | Train acc: 50.58% | Val loss: 0.9961 | Val acc: 50.70% | LR: 0.000005
Epoch: 084 | Train loss: 0.9928 | Train acc: 50.85% | Val loss: 0.9961 | Val acc: 50.70% | LR: 0.000005
Epoch: 085 | Train loss: 0.9918 | Train acc: 50.75% | Val loss: 0.9960 | Val acc: 50.72% | LR: 0.000005
Epoch: 086 | Train loss: 0.9913 | Train acc: 51.65% | Val loss: 0.9960 | Val acc: 50.77% | LR: 0.000005
Epoch: 087 | Train loss: 0.9945 | Train acc: 50.58% | Val loss: 0.9959 | Val acc: 50.82% | LR: 0.000005
Epoch: 088 | Train loss: 0.9892 | Train acc: 51.11% | Val loss: 0.9958 | Val acc: 50.88% | LR: 0.000005
Epoch: 089 | Train loss: 0.9887 | Train acc: 51.29% | Val loss: 0.9958 | Val acc: 50.88% | LR: 0.000005
Epoch: 090 | Train loss: 0.9933 | Train acc: 50.66% | Val loss: 0.9957 | Val acc: 50.90% | LR: 0.000005
Epoch: 091 | Train loss: 0.9920 | Train acc: 50.75% | Val loss: 0.9956 | Val acc: 50.90% | LR: 0.000004
Epoch: 092 | Train loss: 0.9897 | Train acc: 51.10% | Val loss: 0.9956 | Val acc: 50.96% | LR: 0.000004
Epoch: 093 | Train loss: 0.9889 | Train acc: 51.00% | Val loss: 0.9955 | Val acc: 50.94% | LR: 0.000004
Epoch: 094 | Train loss: 0.9876 | Train acc: 50.75% | Val loss: 0.9954 | Val acc: 50.86% | LR: 0.000004
Epoch: 095 | Train loss: 0.9842 | Train acc: 51.36% | Val loss: 0.9953 | Val acc: 50.88% | LR: 0.000004
Epoch: 096 | Train loss: 0.9950 | Train acc: 50.57% | Val loss: 0.9953 | Val acc: 50.88% | LR: 0.000004
Epoch: 097 | Train loss: 0.9901 | Train acc: 50.93% | Val loss: 0.9952 | Val acc: 50.85% | LR: 0.000004
Epoch: 098 | Train loss: 0.9922 | Train acc: 50.85% | Val loss: 0.9951 | Val acc: 50.91% | LR: 0.000004
Epoch: 099 | Train loss: 0.9832 | Train acc: 51.37% | Val loss: 0.9950 | Val acc: 50.93% | LR: 0.000004
Epoch: 100 | Train loss: 0.9927 | Train acc: 50.75% | Val loss: 0.9949 | Val acc: 50.95% | LR: 0.000004
Epoch: 101 | Train loss: 0.9884 | Train acc: 51.20% | Val loss: 0.9948 | Val acc: 50.89% | LR: 0.000003
Epoch: 102 | Train loss: 0.9918 | Train acc: 50.84% | Val loss: 0.9947 | Val acc: 50.93% | LR: 0.000003
Epoch: 103 | Train loss: 0.9914 | Train acc: 50.85% | Val loss: 0.9946 | Val acc: 50.91% | LR: 0.000003
Epoch: 104 | Train loss: 0.9988 | Train acc: 50.93% | Val loss: 0.9947 | Val acc: 50.93% | LR: 0.000003
Epoch: 105 | Train loss: 0.9921 | Train acc: 50.84% | Val loss: 0.9947 | Val acc: 50.93% | LR: 0.000003
Epoch: 106 | Train loss: 0.9894 | Train acc: 50.93% | Val loss: 0.9946 | Val acc: 50.93% | LR: 0.000003
Epoch: 107 | Train loss: 0.9922 | Train acc: 50.84% | Val loss: 0.9946 | Val acc: 50.93% | LR: 0.000003
Epoch: 108 | Train loss: 0.9886 | Train acc: 51.28% | Val loss: 0.9946 | Val acc: 50.93% | LR: 0.000003
Epoch: 109 | Train loss: 0.9929 | Train acc: 50.40% | Val loss: 0.9945 | Val acc: 50.89% | LR: 0.000003
Epoch: 110 | Train loss: 0.9908 | Train acc: 50.93% | Val loss: 0.9945 | Val acc: 50.85% | LR: 0.000003
Epoch: 111 | Train loss: 0.9882 | Train acc: 51.11% | Val loss: 0.9945 | Val acc: 50.86% | LR: 0.000003
Epoch: 112 | Train loss: 0.9886 | Train acc: 51.12% | Val loss: 0.9944 | Val acc: 50.86% | LR: 0.000002
Epoch: 113 | Train loss: 0.9878 | Train acc: 51.03% | Val loss: 0.9944 | Val acc: 50.88% | LR: 0.000002
Epoch: 114 | Train loss: 0.9918 | Train acc: 50.76% | Val loss: 0.9943 | Val acc: 50.84% | LR: 0.000002
Epoch: 115 | Train loss: 0.9938 | Train acc: 50.41% | Val loss: 0.9943 | Val acc: 50.82% | LR: 0.000002
Epoch: 116 | Train loss: 0.9888 | Train acc: 50.94% | Val loss: 0.9943 | Val acc: 50.86% | LR: 0.000002
Epoch: 117 | Train loss: 0.9968 | Train acc: 50.14% | Val loss: 0.9942 | Val acc: 50.86% | LR: 0.000002
Epoch: 118 | Train loss: 0.9888 | Train acc: 51.12% | Val loss: 0.9942 | Val acc: 50.86% | LR: 0.000002
Epoch: 119 | Train loss: 0.9932 | Train acc: 50.59% | Val loss: 0.9942 | Val acc: 50.86% | LR: 0.000002
Epoch: 120 | Train loss: 0.9931 | Train acc: 50.68% | Val loss: 0.9942 | Val acc: 50.88% | LR: 0.000002
Epoch: 121 | Train loss: 0.9820 | Train acc: 51.83% | Val loss: 0.9942 | Val acc: 50.88% | LR: 0.000002
Epoch: 122 | Train loss: 0.9925 | Train acc: 50.76% | Val loss: 0.9941 | Val acc: 50.90% | LR: 0.000002
Epoch: 123 | Train loss: 0.9922 | Train acc: 50.50% | Val loss: 0.9941 | Val acc: 50.86% | LR: 0.000002
Epoch: 124 | Train loss: 0.9944 | Train acc: 50.59% | Val loss: 0.9941 | Val acc: 50.86% | LR: 0.000002
Epoch: 125 | Train loss: 0.9904 | Train acc: 50.67% | Val loss: 0.9940 | Val acc: 50.86% | LR: 0.000002
Epoch: 126 | Train loss: 0.9908 | Train acc: 50.76% | Val loss: 0.9940 | Val acc: 50.86% | LR: 0.000002
Epoch: 127 | Train loss: 0.9902 | Train acc: 51.02% | Val loss: 0.9940 | Val acc: 50.86% | LR: 0.000002
Epoch: 128 | Train loss: 0.9885 | Train acc: 51.11% | Val loss: 0.9940 | Val acc: 50.86% | LR: 0.000001
Epoch: 129 | Train loss: 0.9892 | Train acc: 50.84% | Val loss: 0.9940 | Val acc: 50.88% | LR: 0.000001
Epoch: 130 | Train loss: 0.9860 | Train acc: 51.19% | Val loss: 0.9939 | Val acc: 50.88% | LR: 0.000001
Epoch: 131 | Train loss: 0.9891 | Train acc: 51.01% | Val loss: 0.9939 | Val acc: 50.90% | LR: 0.000001
Epoch: 132 | Train loss: 0.9825 | Train acc: 51.72% | Val loss: 0.9939 | Val acc: 50.90% | LR: 0.000001
Epoch: 133 | Train loss: 0.9885 | Train acc: 50.93% | Val loss: 0.9939 | Val acc: 50.88% | LR: 0.000001
Epoch: 134 | Train loss: 0.9904 | Train acc: 50.92% | Val loss: 0.9939 | Val acc: 50.88% | LR: 0.000001
Epoch: 135 | Train loss: 0.9859 | Train acc: 51.28% | Val loss: 0.9938 | Val acc: 50.84% | LR: 0.000001
Epoch: 136 | Train loss: 0.9913 | Train acc: 50.74% | Val loss: 0.9938 | Val acc: 50.84% | LR: 0.000001
Epoch: 137 | Train loss: 0.9928 | Train acc: 50.75% | Val loss: 0.9938 | Val acc: 50.80% | LR: 0.000001
Epoch: 138 | Train loss: 0.9963 | Train acc: 50.04% | Val loss: 0.9938 | Val acc: 50.80% | LR: 0.000001
Epoch: 139 | Train loss: 0.9928 | Train acc: 50.66% | Val loss: 0.9938 | Val acc: 50.80% | LR: 0.000001
Epoch: 140 | Train loss: 0.9890 | Train acc: 51.19% | Val loss: 0.9937 | Val acc: 50.78% | LR: 0.000001
Epoch: 141 | Train loss: 0.9925 | Train acc: 50.48% | Val loss: 0.9937 | Val acc: 50.78% | LR: 0.000001

[I 2025-09-23 17:29:01,625] Trial 68 finished with value: 0.5077661633491516 and parameters: {'lr': 1.1482385676901078e-05, 'hidden_size': 108, 'dropout': 0.412026284981476, 'weight_decay': 4.073361514279229e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0001 | Train acc: 49.87% | Val loss: 1.0007 | Val acc: 46.91% | LR: 0.000015
Epoch: 001 | Train loss: 0.9996 | Train acc: 50.02% | Val loss: 1.0006 | Val acc: 47.29% | LR: 0.000015
Epoch: 002 | Train loss: 0.9994 | Train acc: 50.18% | Val loss: 1.0007 | Val acc: 46.95% | LR: 0.000015
Epoch: 003 | Train loss: 0.9995 | Train acc: 50.23% | Val loss: 1.0006 | Val acc: 47.28% | LR: 0.000015
Epoch: 004 | Train loss: 0.9995 | Train acc: 50.01% | Val loss: 1.0005 | Val acc: 47.53% | LR: 0.000015
Epoch: 005 | Train loss: 0.9992 | Train acc: 50.34% | Val loss: 1.0003 | Val acc: 47.92% | LR: 0.000015
Epoch: 006 | Train loss: 0.9988 | Train acc: 50.39% | Val loss: 1.0003 | Val acc: 48.09% | LR: 0.000015
Epoch: 007 | Train loss: 0.9989 | Train acc: 51.01% | Val loss: 1.0002 | Val acc: 48.24% | LR: 0.000015
Epoch: 008 | Train loss: 1.0004 | Train acc: 50.86% | Val loss: 1.0001 | Val acc: 48.07% | LR: 0.000015
Epoch: 009 | Train loss: 1.0139 | Train acc: 50.93% | Val loss: 1.0001 | Val acc: 48.04% | LR: 0.000015
Epoch: 010 | Train loss: 1.0182 | Train acc: 50.51% | Val loss: 1.0001 | Val acc: 48.06% | LR: 0.000015
Epoch: 011 | Train loss: 1.0031 | Train acc: 50.63% | Val loss: 1.0001 | Val acc: 48.44% | LR: 0.000015
Epoch: 012 | Train loss: 1.0004 | Train acc: 50.65% | Val loss: 1.0000 | Val acc: 48.79% | LR: 0.000015
Epoch: 013 | Train loss: 0.9992 | Train acc: 51.06% | Val loss: 1.0000 | Val acc: 48.31% | LR: 0.000015
Epoch: 014 | Train loss: 0.9998 | Train acc: 50.17% | Val loss: 1.0000 | Val acc: 48.47% | LR: 0.000015
Epoch: 015 | Train loss: 1.0005 | Train acc: 50.13% | Val loss: 0.9999 | Val acc: 48.76% | LR: 0.000015
Epoch: 016 | Train loss: 0.9994 | Train acc: 50.62% | Val loss: 0.9998 | Val acc: 49.03% | LR: 0.000015
Epoch: 017 | Train loss: 1.0277 | Train acc: 50.56% | Val loss: 0.9998 | Val acc: 49.33% | LR: 0.000015
Epoch: 018 | Train loss: 0.9998 | Train acc: 50.71% | Val loss: 0.9997 | Val acc: 49.29% | LR: 0.000015
Epoch: 019 | Train loss: 0.9985 | Train acc: 50.81% | Val loss: 0.9996 | Val acc: 49.41% | LR: 0.000015
Epoch: 020 | Train loss: 1.0017 | Train acc: 51.23% | Val loss: 0.9994 | Val acc: 49.66% | LR: 0.000015
Epoch: 021 | Train loss: 0.9975 | Train acc: 51.09% | Val loss: 0.9994 | Val acc: 49.70% | LR: 0.000015
Epoch: 022 | Train loss: 0.9983 | Train acc: 50.31% | Val loss: 0.9990 | Val acc: 50.11% | LR: 0.000014
Epoch: 023 | Train loss: 1.0940 | Train acc: 50.78% | Val loss: 0.9989 | Val acc: 50.09% | LR: 0.000014
Epoch: 024 | Train loss: 0.9969 | Train acc: 50.80% | Val loss: 0.9992 | Val acc: 50.05% | LR: 0.000014
Epoch: 025 | Train loss: 0.9980 | Train acc: 50.93% | Val loss: 0.9992 | Val acc: 50.01% | LR: 0.000014
Epoch: 026 | Train loss: 0.9970 | Train acc: 51.20% | Val loss: 0.9990 | Val acc: 50.19% | LR: 0.000014
Epoch: 027 | Train loss: 1.0139 | Train acc: 50.97% | Val loss: 0.9990 | Val acc: 50.29% | LR: 0.000014
Epoch: 028 | Train loss: 1.0005 | Train acc: 50.58% | Val loss: 0.9987 | Val acc: 50.63% | LR: 0.000014
Epoch: 029 | Train loss: 0.9975 | Train acc: 51.26% | Val loss: 0.9986 | Val acc: 50.59% | LR: 0.000014
Epoch: 030 | Train loss: 0.9964 | Train acc: 51.40% | Val loss: 0.9984 | Val acc: 50.68% | LR: 0.000014
Epoch: 031 | Train loss: 0.9991 | Train acc: 50.99% | Val loss: 0.9983 | Val acc: 50.66% | LR: 0.000014
Epoch: 032 | Train loss: 0.9971 | Train acc: 50.88% | Val loss: 0.9983 | Val acc: 50.65% | LR: 0.000014
Epoch: 033 | Train loss: 1.0383 | Train acc: 51.13% | Val loss: 0.9984 | Val acc: 50.81% | LR: 0.000014
Epoch: 034 | Train loss: 0.9960 | Train acc: 50.95% | Val loss: 0.9986 | Val acc: 50.53% | LR: 0.000013
Epoch: 035 | Train loss: 0.9986 | Train acc: 51.04% | Val loss: 0.9985 | Val acc: 50.59% | LR: 0.000013
Epoch: 036 | Train loss: 0.9971 | Train acc: 51.02% | Val loss: 0.9982 | Val acc: 50.63% | LR: 0.000013
Epoch: 037 | Train loss: 0.9981 | Train acc: 50.70% | Val loss: 0.9980 | Val acc: 50.68% | LR: 0.000013
Epoch: 038 | Train loss: 0.9955 | Train acc: 51.36% | Val loss: 0.9979 | Val acc: 50.78% | LR: 0.000013
Epoch: 039 | Train loss: 0.9968 | Train acc: 50.59% | Val loss: 0.9977 | Val acc: 50.83% | LR: 0.000013
Epoch: 040 | Train loss: 0.9961 | Train acc: 51.07% | Val loss: 0.9975 | Val acc: 50.89% | LR: 0.000013
Epoch: 041 | Train loss: 0.9970 | Train acc: 51.15% | Val loss: 0.9974 | Val acc: 50.97% | LR: 0.000013
Epoch: 042 | Train loss: 0.9961 | Train acc: 50.99% | Val loss: 0.9972 | Val acc: 50.93% | LR: 0.000013
Epoch: 043 | Train loss: 0.9965 | Train acc: 50.72% | Val loss: 0.9972 | Val acc: 51.03% | LR: 0.000012
Epoch: 044 | Train loss: 0.9944 | Train acc: 51.26% | Val loss: 0.9972 | Val acc: 50.99% | LR: 0.000012
Epoch: 045 | Train loss: 0.9953 | Train acc: 50.82% | Val loss: 0.9971 | Val acc: 50.99% | LR: 0.000012
Epoch: 046 | Train loss: 0.9961 | Train acc: 50.72% | Val loss: 0.9970 | Val acc: 51.01% | LR: 0.000012
Epoch: 047 | Train loss: 0.9947 | Train acc: 51.35% | Val loss: 0.9968 | Val acc: 50.94% | LR: 0.000012
Epoch: 048 | Train loss: 0.9960 | Train acc: 50.52% | Val loss: 0.9967 | Val acc: 50.98% | LR: 0.000012
Epoch: 049 | Train loss: 0.9940 | Train acc: 51.18% | Val loss: 0.9965 | Val acc: 51.04% | LR: 0.000012
Epoch: 050 | Train loss: 0.9925 | Train acc: 51.20% | Val loss: 0.9963 | Val acc: 51.18% | LR: 0.000012
Epoch: 051 | Train loss: 0.9948 | Train acc: 50.74% | Val loss: 0.9962 | Val acc: 51.18% | LR: 0.000011
Epoch: 052 | Train loss: 0.9931 | Train acc: 51.10% | Val loss: 0.9961 | Val acc: 51.10% | LR: 0.000011
Epoch: 053 | Train loss: 0.9951 | Train acc: 50.65% | Val loss: 0.9960 | Val acc: 51.08% | LR: 0.000011
Epoch: 054 | Train loss: 0.9930 | Train acc: 51.10% | Val loss: 0.9959 | Val acc: 51.12% | LR: 0.000011
Epoch: 055 | Train loss: 0.9957 | Train acc: 50.67% | Val loss: 0.9958 | Val acc: 51.15% | LR: 0.000011
Epoch: 056 | Train loss: 0.9926 | Train acc: 51.45% | Val loss: 0.9957 | Val acc: 51.12% | LR: 0.000011
Epoch: 057 | Train loss: 0.9944 | Train acc: 51.75% | Val loss: 0.9956 | Val acc: 51.13% | LR: 0.000011
Epoch: 058 | Train loss: 0.9944 | Train acc: 51.10% | Val loss: 0.9955 | Val acc: 51.08% | LR: 0.000011
Epoch: 059 | Train loss: 0.9936 | Train acc: 50.83% | Val loss: 0.9954 | Val acc: 51.12% | LR: 0.000010
Epoch: 060 | Train loss: 0.9932 | Train acc: 51.10% | Val loss: 0.9953 | Val acc: 51.12% | LR: 0.000010
Epoch: 061 | Train loss: 0.9927 | Train acc: 51.10% | Val loss: 0.9951 | Val acc: 51.17% | LR: 0.000010
Epoch: 062 | Train loss: 0.9934 | Train acc: 50.91% | Val loss: 0.9950 | Val acc: 51.19% | LR: 0.000010
Epoch: 063 | Train loss: 0.9928 | Train acc: 50.91% | Val loss: 0.9948 | Val acc: 51.13% | LR: 0.000010
Epoch: 064 | Train loss: 0.9954 | Train acc: 50.81% | Val loss: 0.9947 | Val acc: 51.13% | LR: 0.000010
Epoch: 065 | Train loss: 0.9936 | Train acc: 51.02% | Val loss: 0.9947 | Val acc: 51.19% | LR: 0.000009
Epoch: 066 | Train loss: 0.9934 | Train acc: 50.91% | Val loss: 0.9945 | Val acc: 51.13% | LR: 0.000009
Epoch: 067 | Train loss: 0.9969 | Train acc: 50.56% | Val loss: 0.9946 | Val acc: 51.21% | LR: 0.000009
Epoch: 068 | Train loss: 0.9936 | Train acc: 51.09% | Val loss: 0.9945 | Val acc: 51.15% | LR: 0.000009
Epoch: 069 | Train loss: 0.9968 | Train acc: 50.47% | Val loss: 0.9944 | Val acc: 51.15% | LR: 0.000009
Epoch: 070 | Train loss: 0.9920 | Train acc: 51.17% | Val loss: 0.9942 | Val acc: 51.11% | LR: 0.000009
Epoch: 071 | Train loss: 0.9937 | Train acc: 50.81% | Val loss: 0.9941 | Val acc: 51.13% | LR: 0.000009
Epoch: 072 | Train loss: 0.9931 | Train acc: 50.89% | Val loss: 0.9940 | Val acc: 51.13% | LR: 0.000008
Epoch: 073 | Train loss: 0.9904 | Train acc: 51.16% | Val loss: 0.9940 | Val acc: 51.15% | LR: 0.000008
Epoch: 074 | Train loss: 0.9941 | Train acc: 50.91% | Val loss: 0.9940 | Val acc: 51.15% | LR: 0.000008
Epoch: 075 | Train loss: 0.9935 | Train acc: 50.91% | Val loss: 0.9939 | Val acc: 51.13% | LR: 0.000008
Epoch: 076 | Train loss: 0.9942 | Train acc: 50.91% | Val loss: 0.9938 | Val acc: 51.15% | LR: 0.000008
Epoch: 077 | Train loss: 0.9907 | Train acc: 51.61% | Val loss: 0.9937 | Val acc: 51.17% | LR: 0.000008
Epoch: 078 | Train loss: 0.9962 | Train acc: 50.73% | Val loss: 0.9936 | Val acc: 51.15% | LR: 0.000008
Epoch: 079 | Train loss: 0.9940 | Train acc: 50.55% | Val loss: 0.9935 | Val acc: 51.17% | LR: 0.000007
Epoch: 080 | Train loss: 0.9894 | Train acc: 51.78% | Val loss: 0.9934 | Val acc: 51.23% | LR: 0.000007
Epoch: 081 | Train loss: 0.9945 | Train acc: 50.79% | Val loss: 0.9932 | Val acc: 51.29% | LR: 0.000007
Epoch: 082 | Train loss: 0.9945 | Train acc: 50.78% | Val loss: 0.9931 | Val acc: 51.28% | LR: 0.000007
Epoch: 083 | Train loss: 0.9964 | Train acc: 50.60% | Val loss: 0.9929 | Val acc: 51.31% | LR: 0.000007
Epoch: 084 | Train loss: 0.9955 | Train acc: 50.87% | Val loss: 0.9929 | Val acc: 51.27% | LR: 0.000007
Epoch: 085 | Train loss: 0.9932 | Train acc: 50.70% | Val loss: 0.9928 | Val acc: 51.27% | LR: 0.000007
Epoch: 086 | Train loss: 0.9945 | Train acc: 50.86% | Val loss: 0.9926 | Val acc: 51.29% | LR: 0.000006
Epoch: 087 | Train loss: 0.9953 | Train acc: 50.32% | Val loss: 0.9926 | Val acc: 51.29% | LR: 0.000006
Epoch: 088 | Train loss: 0.9914 | Train acc: 51.20% | Val loss: 0.9924 | Val acc: 51.30% | LR: 0.000006
Epoch: 089 | Train loss: 0.9941 | Train acc: 50.58% | Val loss: 0.9923 | Val acc: 51.36% | LR: 0.000006
Epoch: 090 | Train loss: 0.9928 | Train acc: 50.75% | Val loss: 0.9922 | Val acc: 51.36% | LR: 0.000006
Epoch: 091 | Train loss: 0.9934 | Train acc: 50.84% | Val loss: 0.9921 | Val acc: 51.36% | LR: 0.000006
Epoch: 092 | Train loss: 0.9943 | Train acc: 50.49% | Val loss: 0.9919 | Val acc: 51.44% | LR: 0.000006
Epoch: 093 | Train loss: 0.9903 | Train acc: 51.21% | Val loss: 0.9919 | Val acc: 51.36% | LR: 0.000005
Epoch: 094 | Train loss: 0.9944 | Train acc: 50.31% | Val loss: 0.9919 | Val acc: 51.36% | LR: 0.000005
Epoch: 095 | Train loss: 0.9934 | Train acc: 50.66% | Val loss: 0.9919 | Val acc: 51.33% | LR: 0.000005
Epoch: 096 | Train loss: 0.9924 | Train acc: 50.93% | Val loss: 0.9918 | Val acc: 51.32% | LR: 0.000005
Epoch: 097 | Train loss: 0.9928 | Train acc: 50.75% | Val loss: 0.9916 | Val acc: 51.38% | LR: 0.000005
Epoch: 098 | Train loss: 0.9910 | Train acc: 51.11% | Val loss: 0.9915 | Val acc: 51.40% | LR: 0.000005
Epoch: 099 | Train loss: 0.9923 | Train acc: 51.02% | Val loss: 0.9915 | Val acc: 51.36% | LR: 0.000005
Epoch: 100 | Train loss: 0.9898 | Train acc: 51.29% | Val loss: 0.9914 | Val acc: 51.42% | LR: 0.000004
Epoch: 101 | Train loss: 0.9911 | Train acc: 51.01% | Val loss: 0.9914 | Val acc: 51.38% | LR: 0.000004
Epoch: 102 | Train loss: 0.9946 | Train acc: 50.40% | Val loss: 0.9914 | Val acc: 51.38% | LR: 0.000004
Epoch: 103 | Train loss: 0.9919 | Train acc: 51.11% | Val loss: 0.9914 | Val acc: 51.32% | LR: 0.000004
Epoch: 104 | Train loss: 0.9928 | Train acc: 50.75% | Val loss: 0.9913 | Val acc: 51.32% | LR: 0.000004
Epoch: 105 | Train loss: 0.9897 | Train acc: 51.46% | Val loss: 0.9913 | Val acc: 51.38% | LR: 0.000004
Epoch: 106 | Train loss: 0.9930 | Train acc: 50.58% | Val loss: 0.9912 | Val acc: 51.38% | LR: 0.000004
Epoch: 107 | Train loss: 0.9942 | Train acc: 50.66% | Val loss: 0.9912 | Val acc: 51.38% | LR: 0.000004
Epoch: 108 | Train loss: 0.9912 | Train acc: 51.02% | Val loss: 0.9911 | Val acc: 51.38% | LR: 0.000003
Epoch: 109 | Train loss: 0.9900 | Train acc: 51.29% | Val loss: 0.9910 | Val acc: 51.42% | LR: 0.000003
Epoch: 110 | Train loss: 0.9931 | Train acc: 50.84% | Val loss: 0.9909 | Val acc: 51.44% | LR: 0.000003
Epoch: 111 | Train loss: 0.9933 | Train acc: 50.76% | Val loss: 0.9909 | Val acc: 51.44% | LR: 0.000003
Epoch: 112 | Train loss: 0.9884 | Train acc: 51.46% | Val loss: 0.9908 | Val acc: 51.50% | LR: 0.000003
Epoch: 113 | Train loss: 0.9908 | Train acc: 51.11% | Val loss: 0.9908 | Val acc: 51.50% | LR: 0.000003
Epoch: 114 | Train loss: 0.9927 | Train acc: 50.66% | Val loss: 0.9907 | Val acc: 51.58% | LR: 0.000003
Epoch: 115 | Train loss: 0.9929 | Train acc: 50.66% | Val loss: 0.9907 | Val acc: 51.54% | LR: 0.000003
Epoch: 116 | Train loss: 0.9919 | Train acc: 50.75% | Val loss: 0.9906 | Val acc: 51.54% | LR: 0.000003
Epoch: 117 | Train loss: 0.9907 | Train acc: 51.02% | Val loss: 0.9906 | Val acc: 51.50% | LR: 0.000003
Epoch: 118 | Train loss: 0.9929 | Train acc: 50.75% | Val loss: 0.9906 | Val acc: 51.46% | LR: 0.000002
Epoch: 119 | Train loss: 0.9933 | Train acc: 50.66% | Val loss: 0.9906 | Val acc: 51.48% | LR: 0.000002
Epoch: 120 | Train loss: 0.9884 | Train acc: 51.19% | Val loss: 0.9906 | Val acc: 51.48% | LR: 0.000002
Epoch: 121 | Train loss: 0.9894 | Train acc: 51.10% | Val loss: 0.9905 | Val acc: 51.46% | LR: 0.000002
Epoch: 122 | Train loss: 0.9897 | Train acc: 50.93% | Val loss: 0.9905 | Val acc: 51.44% | LR: 0.000002
Epoch: 123 | Train loss: 0.9895 | Train acc: 51.28% | Val loss: 0.9904 | Val acc: 51.44% | LR: 0.000002
Epoch: 124 | Train loss: 0.9889 | Train acc: 51.28% | Val loss: 0.9904 | Val acc: 51.44% | LR: 0.000002
Epoch: 125 | Train loss: 0.9925 | Train acc: 50.84% | Val loss: 0.9904 | Val acc: 51.44% | LR: 0.000002
Epoch: 126 | Train loss: 0.9942 | Train acc: 50.39% | Val loss: 0.9904 | Val acc: 51.44% | LR: 0.000002
Epoch: 127 | Train loss: 0.9907 | Train acc: 50.93% | Val loss: 0.9903 | Val acc: 51.44% | LR: 0.000002
Epoch: 128 | Train loss: 0.9930 | Train acc: 50.66% | Val loss: 0.9903 | Val acc: 51.46% | LR: 0.000002
Epoch: 129 | Train loss: 0.9891 | Train acc: 51.37% | Val loss: 0.9903 | Val acc: 51.46% | LR: 0.000002
Epoch: 130 | Train loss: 0.9926 | Train acc: 50.66% | Val loss: 0.9903 | Val acc: 51.46% | LR: 0.000002
Epoch: 131 | Train loss: 0.9914 | Train acc: 50.66% | Val loss: 0.9903 | Val acc: 51.46% | LR: 0.000002
Epoch: 132 | Train loss: 0.9909 | Train acc: 51.03% | Val loss: 0.9902 | Val acc: 51.48% | LR: 0.000001
Epoch: 133 | Train loss: 0.9886 | Train acc: 51.47% | Val loss: 0.9902 | Val acc: 51.48% | LR: 0.000001
Epoch: 134 | Train loss: 0.9931 | Train acc: 50.58% | Val loss: 0.9902 | Val acc: 51.48% | LR: 0.000001
Epoch: 135 | Train loss: 0.9901 | Train acc: 51.02% | Val loss: 0.9902 | Val acc: 51.48% | LR: 0.000001
Epoch: 136 | Train loss: 0.9952 | Train acc: 50.49% | Val loss: 0.9901 | Val acc: 51.50% | LR: 0.000001
Epoch: 137 | Train loss: 0.9913 | Train acc: 50.85% | Val loss: 0.9901 | Val acc: 51.54% | LR: 0.000001
Epoch: 138 | Train loss: 0.9927 | Train acc: 50.76% | Val loss: 0.9901 | Val acc: 51.54% | LR: 0.000001
Epoch: 139 | Train loss: 0.9914 | Train acc: 50.94% | Val loss: 0.9901 | Val acc: 51.52% | LR: 0.000001
Epoch: 140 | Train loss: 0.9918 | Train acc: 50.58% | Val loss: 0.9901 | Val acc: 51.48% | LR: 0.000001
Epoch: 141 | Train loss: 0.9931 | Train acc: 50.67% | Val loss: 0.9901 | Val acc: 51.48% | LR: 0.000001
Epoch: 142 | Train loss: 0.9922 | Train acc: 50.93% | Val loss: 0.9900 | Val acc: 51.48% | LR: 0.000001
Epoch: 143 | Train loss: 0.9878 | Train acc: 51.20% | Val loss: 0.9900 | Val acc: 51.48% | LR: 0.000001
Epoch: 144 | Train loss: 0.9939 | Train acc: 50.67% | Val loss: 0.9900 | Val acc: 51.48% | LR: 0.000001
Epoch: 145 | Train loss: 0.9919 | Train acc: 50.84% | Val loss: 0.9900 | Val acc: 51.48% | LR: 0.000001
Epoch: 146 | Train loss: 0.9957 | Train acc: 50.41% | Val loss: 0.9900 | Val acc: 51.48% | LR: 0.000001
Epoch: 147 | Train loss: 0.9918 | Train acc: 50.85% | Val loss: 0.9900 | Val acc: 51.52% | LR: 0.000001
Epoch: 148 | Train loss: 0.9897 | Train acc: 51.47% | Val loss: 0.9900 | Val acc: 51.52% | LR: 0.000001
Epoch: 149 | Train loss: 0.9926 | Train acc: 50.68% | Val loss: 0.9900 | Val acc: 51.48% | LR: 0.000001

[I 2025-09-23 17:32:21,438] Trial 69 finished with value: 0.5148037195205688 and parameters: {'lr': 1.5302216175914392e-05, 'hidden_size': 152, 'dropout': 0.34220696959899716, 'weight_decay': 2.9939352033499353e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9995 | Train acc: 49.94% | Val loss: 0.9975 | Val acc: 53.67% | LR: 0.000030
Epoch: 001 | Train loss: 1.0002 | Train acc: 49.93% | Val loss: 1.0074 | Val acc: 53.89% | LR: 0.000030
Epoch: 002 | Train loss: 1.0011 | Train acc: 49.75% | Val loss: 1.0028 | Val acc: 53.61% | LR: 0.000030
Epoch: 003 | Train loss: 0.9994 | Train acc: 49.88% | Val loss: 1.0321 | Val acc: 53.81% | LR: 0.000030
Epoch: 004 | Train loss: 0.9997 | Train acc: 50.32% | Val loss: 0.9969 | Val acc: 53.70% | LR: 0.000030
Epoch: 005 | Train loss: 0.9993 | Train acc: 50.45% | Val loss: 0.9978 | Val acc: 53.80% | LR: 0.000030
Epoch: 006 | Train loss: 0.9995 | Train acc: 50.55% | Val loss: 0.9987 | Val acc: 53.82% | LR: 0.000030
Epoch: 007 | Train loss: 1.0002 | Train acc: 50.37% | Val loss: 0.9984 | Val acc: 53.47% | LR: 0.000029
Epoch: 008 | Train loss: 0.9987 | Train acc: 51.14% | Val loss: 0.9969 | Val acc: 53.76% | LR: 0.000029
Epoch: 009 | Train loss: 1.0154 | Train acc: 50.57% | Val loss: 1.0171 | Val acc: 53.67% | LR: 0.000029
Epoch: 010 | Train loss: 0.9991 | Train acc: 50.43% | Val loss: 0.9968 | Val acc: 53.67% | LR: 0.000029
Epoch: 011 | Train loss: 1.0004 | Train acc: 50.24% | Val loss: 1.0055 | Val acc: 53.78% | LR: 0.000029
Epoch: 012 | Train loss: 0.9986 | Train acc: 50.49% | Val loss: 0.9953 | Val acc: 53.93% | LR: 0.000029
Epoch: 013 | Train loss: 0.9989 | Train acc: 51.03% | Val loss: 1.0070 | Val acc: 53.43% | LR: 0.000029
Epoch: 014 | Train loss: 0.9991 | Train acc: 50.62% | Val loss: 1.0015 | Val acc: 53.80% | LR: 0.000029
Epoch: 015 | Train loss: 1.0011 | Train acc: 50.58% | Val loss: 1.0011 | Val acc: 54.07% | LR: 0.000029
Epoch: 016 | Train loss: 0.9996 | Train acc: 50.60% | Val loss: 1.0058 | Val acc: 54.05% | LR: 0.000029
Epoch: 017 | Train loss: 0.9980 | Train acc: 50.53% | Val loss: 0.9965 | Val acc: 54.25% | LR: 0.000029
Epoch: 018 | Train loss: 1.0141 | Train acc: 50.58% | Val loss: 0.9959 | Val acc: 54.21% | LR: 0.000029
Epoch: 019 | Train loss: 0.9978 | Train acc: 50.51% | Val loss: 0.9959 | Val acc: 54.25% | LR: 0.000028
Epoch: 020 | Train loss: 0.9991 | Train acc: 50.17% | Val loss: 0.9959 | Val acc: 54.40% | LR: 0.000028
Epoch: 021 | Train loss: 0.9978 | Train acc: 50.54% | Val loss: 0.9958 | Val acc: 54.29% | LR: 0.000028
Epoch: 022 | Train loss: 0.9980 | Train acc: 50.82% | Val loss: 0.9959 | Val acc: 54.37% | LR: 0.000028
Epoch: 023 | Train loss: 0.9969 | Train acc: 50.91% | Val loss: 0.9958 | Val acc: 54.13% | LR: 0.000028
Epoch: 024 | Train loss: 0.9959 | Train acc: 50.93% | Val loss: 0.9959 | Val acc: 54.21% | LR: 0.000028
Epoch: 025 | Train loss: 0.9958 | Train acc: 50.93% | Val loss: 0.9959 | Val acc: 54.25% | LR: 0.000028
Epoch: 026 | Train loss: 0.9965 | Train acc: 51.01% | Val loss: 0.9959 | Val acc: 54.27% | LR: 0.000027
Epoch: 027 | Train loss: 0.9970 | Train acc: 50.55% | Val loss: 0.9959 | Val acc: 54.13% | LR: 0.000027
Epoch: 028 | Train loss: 0.9962 | Train acc: 50.71% | Val loss: 0.9959 | Val acc: 54.19% | LR: 0.000027
Epoch: 029 | Train loss: 0.9958 | Train acc: 50.71% | Val loss: 0.9958 | Val acc: 54.17% | LR: 0.000027
Epoch: 030 | Train loss: 0.9964 | Train acc: 50.44% | Val loss: 0.9958 | Val acc: 54.25% | LR: 0.000027
Epoch: 031 | Train loss: 0.9960 | Train acc: 50.81% | Val loss: 0.9959 | Val acc: 54.34% | LR: 0.000027
Epoch: 032 | Train loss: 0.9939 | Train acc: 50.97% | Val loss: 0.9959 | Val acc: 54.28% | LR: 0.000026
Epoch: 033 | Train loss: 0.9974 | Train acc: 50.26% | Val loss: 0.9959 | Val acc: 54.34% | LR: 0.000026
Epoch: 034 | Train loss: 0.9974 | Train acc: 50.35% | Val loss: 0.9959 | Val acc: 54.46% | LR: 0.000026
Epoch: 035 | Train loss: 0.9991 | Train acc: 49.92% | Val loss: 0.9958 | Val acc: 54.42% | LR: 0.000026
Epoch: 036 | Train loss: 0.9961 | Train acc: 50.45% | Val loss: 0.9957 | Val acc: 54.42% | LR: 0.000026
Epoch: 037 | Train loss: 0.9947 | Train acc: 50.46% | Val loss: 0.9956 | Val acc: 54.40% | LR: 0.000025
Epoch: 038 | Train loss: 0.9959 | Train acc: 50.61% | Val loss: 0.9956 | Val acc: 54.20% | LR: 0.000025
Epoch: 039 | Train loss: 0.9958 | Train acc: 50.68% | Val loss: 0.9955 | Val acc: 54.22% | LR: 0.000025
Epoch: 040 | Train loss: 0.9941 | Train acc: 50.60% | Val loss: 0.9954 | Val acc: 54.16% | LR: 0.000025
Epoch: 041 | Train loss: 0.9955 | Train acc: 50.62% | Val loss: 0.9954 | Val acc: 54.23% | LR: 0.000024
Epoch: 042 | Train loss: 0.9963 | Train acc: 50.36% | Val loss: 0.9954 | Val acc: 54.12% | LR: 0.000024
Epoch: 043 | Train loss: 0.9968 | Train acc: 50.27% | Val loss: 0.9953 | Val acc: 54.26% | LR: 0.000024
Epoch: 044 | Train loss: 0.9963 | Train acc: 50.36% | Val loss: 0.9952 | Val acc: 54.20% | LR: 0.000024
Epoch: 045 | Train loss: 0.9927 | Train acc: 50.90% | Val loss: 0.9952 | Val acc: 54.14% | LR: 0.000024
Epoch: 046 | Train loss: 0.9940 | Train acc: 50.89% | Val loss: 0.9952 | Val acc: 54.26% | LR: 0.000023
Epoch: 047 | Train loss: 0.9926 | Train acc: 51.00% | Val loss: 0.9951 | Val acc: 54.12% | LR: 0.000023
Epoch: 048 | Train loss: 0.9952 | Train acc: 50.58% | Val loss: 0.9951 | Val acc: 54.10% | LR: 0.000023
Epoch: 049 | Train loss: 0.9956 | Train acc: 50.41% | Val loss: 0.9950 | Val acc: 54.22% | LR: 0.000023
Epoch: 050 | Train loss: 0.9978 | Train acc: 50.33% | Val loss: 0.9949 | Val acc: 54.12% | LR: 0.000022
Epoch: 051 | Train loss: 0.9941 | Train acc: 50.69% | Val loss: 0.9948 | Val acc: 54.08% | LR: 0.000022
Epoch: 052 | Train loss: 0.9934 | Train acc: 50.82% | Val loss: 0.9948 | Val acc: 53.92% | LR: 0.000022
Epoch: 053 | Train loss: 0.9970 | Train acc: 50.22% | Val loss: 0.9947 | Val acc: 53.94% | LR: 0.000021
Epoch: 054 | Train loss: 0.9903 | Train acc: 51.10% | Val loss: 0.9946 | Val acc: 53.92% | LR: 0.000021
Epoch: 055 | Train loss: 0.9926 | Train acc: 51.03% | Val loss: 0.9946 | Val acc: 53.90% | LR: 0.000021
Epoch: 056 | Train loss: 0.9977 | Train acc: 50.14% | Val loss: 0.9946 | Val acc: 53.86% | LR: 0.000021
Epoch: 057 | Train loss: 0.9927 | Train acc: 50.94% | Val loss: 0.9945 | Val acc: 53.90% | LR: 0.000020
Epoch: 058 | Train loss: 0.9923 | Train acc: 50.75% | Val loss: 0.9943 | Val acc: 53.94% | LR: 0.000020
Epoch: 059 | Train loss: 0.9926 | Train acc: 50.85% | Val loss: 0.9981 | Val acc: 53.86% | LR: 0.000020
Epoch: 060 | Train loss: 0.9931 | Train acc: 50.85% | Val loss: 0.9922 | Val acc: 53.80% | LR: 0.000019
Epoch: 061 | Train loss: 0.9952 | Train acc: 50.50% | Val loss: 1.0163 | Val acc: 53.53% | LR: 0.000019
Epoch: 062 | Train loss: 0.9966 | Train acc: 50.39% | Val loss: 0.9956 | Val acc: 53.27% | LR: 0.000019
Epoch: 063 | Train loss: 0.9928 | Train acc: 50.60% | Val loss: 0.9992 | Val acc: 53.13% | LR: 0.000019
Epoch: 064 | Train loss: 0.9927 | Train acc: 50.81% | Val loss: 1.0004 | Val acc: 53.13% | LR: 0.000018
Epoch: 065 | Train loss: 0.9929 | Train acc: 50.80% | Val loss: 0.9985 | Val acc: 53.33% | LR: 0.000018
Epoch: 066 | Train loss: 0.9870 | Train acc: 51.52% | Val loss: 0.9949 | Val acc: 53.37% | LR: 0.000018
Epoch: 067 | Train loss: 0.9932 | Train acc: 50.73% | Val loss: 0.9969 | Val acc: 53.18% | LR: 0.000017
Epoch: 068 | Train loss: 0.9942 | Train acc: 50.64% | Val loss: 0.9952 | Val acc: 53.25% | LR: 0.000017
Epoch: 069 | Train loss: 0.9934 | Train acc: 50.64% | Val loss: 0.9978 | Val acc: 53.26% | LR: 0.000017
Epoch: 070 | Train loss: 0.9960 | Train acc: 50.59% | Val loss: 0.9961 | Val acc: 53.06% | LR: 0.000017
Epoch: 071 | Train loss: 0.9928 | Train acc: 50.83% | Val loss: 0.9953 | Val acc: 53.08% | LR: 0.000016
Epoch: 072 | Train loss: 0.9898 | Train acc: 50.94% | Val loss: 0.9948 | Val acc: 53.16% | LR: 0.000016
Epoch: 073 | Train loss: 0.9905 | Train acc: 51.00% | Val loss: 0.9959 | Val acc: 53.30% | LR: 0.000016
Epoch: 074 | Train loss: 0.9940 | Train acc: 50.96% | Val loss: 1.0125 | Val acc: 53.13% | LR: 0.000015
Epoch: 075 | Train loss: 0.9909 | Train acc: 51.14% | Val loss: 0.9937 | Val acc: 53.26% | LR: 0.000015
Epoch: 076 | Train loss: 0.9959 | Train acc: 50.72% | Val loss: 0.9935 | Val acc: 53.24% | LR: 0.000015
Epoch: 077 | Train loss: 0.9914 | Train acc: 50.80% | Val loss: 0.9990 | Val acc: 53.25% | LR: 0.000014
Epoch: 078 | Train loss: 0.9935 | Train acc: 50.64% | Val loss: 0.9965 | Val acc: 53.10% | LR: 0.000014
Epoch: 079 | Train loss: 0.9951 | Train acc: 51.19% | Val loss: 0.9951 | Val acc: 53.05% | LR: 0.000014
Epoch: 080 | Train loss: 0.9927 | Train acc: 50.86% | Val loss: 0.9996 | Val acc: 52.88% | LR: 0.000014
Epoch: 081 | Train loss: 0.9896 | Train acc: 50.94% | Val loss: 0.9952 | Val acc: 52.68% | LR: 0.000013
Epoch: 082 | Train loss: 0.9897 | Train acc: 51.19% | Val loss: 1.0035 | Val acc: 53.10% | LR: 0.000013
Epoch: 083 | Train loss: 0.9977 | Train acc: 50.32% | Val loss: 1.0733 | Val acc: 52.97% | LR: 0.000013

[I 2025-09-23 17:33:37,488] Trial 70 finished with value: 0.5295671939849853 and parameters: {'lr': 2.9679575865720284e-05, 'hidden_size': 98, 'dropout': 0.44561304563964205, 'weight_decay': 1.3517143807068657e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0003 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000021
Epoch: 001 | Train loss: 1.0007 | Train acc: 49.72% | Val loss: 0.9916 | Val acc: 54.13% | LR: 0.000021
Epoch: 002 | Train loss: 1.0005 | Train acc: 49.54% | Val loss: 0.9916 | Val acc: 54.11% | LR: 0.000021
Epoch: 003 | Train loss: 1.0011 | Train acc: 49.54% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000021
Epoch: 004 | Train loss: 1.0014 | Train acc: 49.37% | Val loss: 0.9917 | Val acc: 54.17% | LR: 0.000021
Epoch: 005 | Train loss: 0.9988 | Train acc: 49.89% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000021
Epoch: 006 | Train loss: 1.0007 | Train acc: 49.82% | Val loss: 0.9917 | Val acc: 54.24% | LR: 0.000021
Epoch: 007 | Train loss: 1.0012 | Train acc: 49.71% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000021
Epoch: 008 | Train loss: 1.0008 | Train acc: 49.56% | Val loss: 0.9920 | Val acc: 54.28% | LR: 0.000021
Epoch: 009 | Train loss: 0.9990 | Train acc: 50.44% | Val loss: 0.9921 | Val acc: 54.32% | LR: 0.000021
Epoch: 010 | Train loss: 0.9985 | Train acc: 50.71% | Val loss: 0.9922 | Val acc: 54.30% | LR: 0.000021
Epoch: 011 | Train loss: 0.9983 | Train acc: 50.71% | Val loss: 0.9920 | Val acc: 54.32% | LR: 0.000021
Epoch: 012 | Train loss: 0.9981 | Train acc: 50.72% | Val loss: 0.9920 | Val acc: 54.34% | LR: 0.000021
Epoch: 013 | Train loss: 0.9990 | Train acc: 50.45% | Val loss: 0.9918 | Val acc: 54.42% | LR: 0.000021
Epoch: 014 | Train loss: 0.9983 | Train acc: 50.53% | Val loss: 0.9917 | Val acc: 54.40% | LR: 0.000021
Epoch: 015 | Train loss: 0.9993 | Train acc: 50.20% | Val loss: 0.9918 | Val acc: 54.44% | LR: 0.000021
Epoch: 016 | Train loss: 0.9984 | Train acc: 50.61% | Val loss: 0.9918 | Val acc: 54.35% | LR: 0.000021
Epoch: 017 | Train loss: 0.9987 | Train acc: 50.48% | Val loss: 0.9918 | Val acc: 54.34% | LR: 0.000021
Epoch: 018 | Train loss: 0.9986 | Train acc: 50.34% | Val loss: 0.9919 | Val acc: 54.34% | LR: 0.000021
Epoch: 019 | Train loss: 0.9986 | Train acc: 50.18% | Val loss: 0.9918 | Val acc: 54.33% | LR: 0.000021
Epoch: 020 | Train loss: 0.9966 | Train acc: 51.17% | Val loss: 0.9918 | Val acc: 54.33% | LR: 0.000020
Epoch: 021 | Train loss: 0.9976 | Train acc: 50.65% | Val loss: 0.9918 | Val acc: 54.33% | LR: 0.000020
Epoch: 022 | Train loss: 0.9974 | Train acc: 50.81% | Val loss: 0.9918 | Val acc: 54.31% | LR: 0.000020
Epoch: 023 | Train loss: 0.9991 | Train acc: 50.41% | Val loss: 0.9932 | Val acc: 54.30% | LR: 0.000020
Epoch: 024 | Train loss: 0.9978 | Train acc: 50.42% | Val loss: 0.9918 | Val acc: 54.45% | LR: 0.000020
Epoch: 025 | Train loss: 0.9986 | Train acc: 50.10% | Val loss: 0.9917 | Val acc: 54.35% | LR: 0.000020
Epoch: 026 | Train loss: 0.9990 | Train acc: 50.37% | Val loss: 0.9918 | Val acc: 54.35% | LR: 0.000020
Epoch: 027 | Train loss: 0.9971 | Train acc: 50.93% | Val loss: 0.9919 | Val acc: 54.40% | LR: 0.000020
Epoch: 028 | Train loss: 0.9967 | Train acc: 51.04% | Val loss: 0.9918 | Val acc: 54.29% | LR: 0.000020
Epoch: 029 | Train loss: 0.9992 | Train acc: 50.95% | Val loss: 0.9918 | Val acc: 54.39% | LR: 0.000019
Epoch: 030 | Train loss: 0.9982 | Train acc: 50.57% | Val loss: 0.9917 | Val acc: 54.42% | LR: 0.000019
Epoch: 031 | Train loss: 0.9983 | Train acc: 50.50% | Val loss: 0.9916 | Val acc: 54.38% | LR: 0.000019
Epoch: 032 | Train loss: 0.9961 | Train acc: 51.24% | Val loss: 0.9912 | Val acc: 54.46% | LR: 0.000019
Epoch: 033 | Train loss: 0.9982 | Train acc: 50.07% | Val loss: 0.9914 | Val acc: 54.44% | LR: 0.000019
Epoch: 034 | Train loss: 0.9958 | Train acc: 51.04% | Val loss: 0.9917 | Val acc: 54.51% | LR: 0.000019
Epoch: 035 | Train loss: 0.9979 | Train acc: 50.60% | Val loss: 0.9917 | Val acc: 54.54% | LR: 0.000019
Epoch: 036 | Train loss: 0.9970 | Train acc: 50.65% | Val loss: 0.9917 | Val acc: 54.46% | LR: 0.000019
Epoch: 037 | Train loss: 0.9968 | Train acc: 50.58% | Val loss: 0.9918 | Val acc: 54.62% | LR: 0.000018
Epoch: 038 | Train loss: 0.9980 | Train acc: 50.51% | Val loss: 0.9919 | Val acc: 54.62% | LR: 0.000018
Epoch: 039 | Train loss: 0.9955 | Train acc: 51.02% | Val loss: 0.9918 | Val acc: 54.64% | LR: 0.000018
Epoch: 040 | Train loss: 0.9967 | Train acc: 51.04% | Val loss: 0.9916 | Val acc: 54.48% | LR: 0.000018
Epoch: 041 | Train loss: 0.9970 | Train acc: 50.35% | Val loss: 0.9917 | Val acc: 54.60% | LR: 0.000018
Epoch: 042 | Train loss: 0.9974 | Train acc: 50.68% | Val loss: 0.9918 | Val acc: 54.64% | LR: 0.000018
Epoch: 043 | Train loss: 0.9974 | Train acc: 50.42% | Val loss: 0.9917 | Val acc: 54.65% | LR: 0.000017
Epoch: 044 | Train loss: 0.9973 | Train acc: 50.70% | Val loss: 0.9916 | Val acc: 54.67% | LR: 0.000017
Epoch: 045 | Train loss: 0.9958 | Train acc: 51.06% | Val loss: 0.9916 | Val acc: 54.63% | LR: 0.000017
Epoch: 046 | Train loss: 0.9955 | Train acc: 50.70% | Val loss: 0.9916 | Val acc: 54.57% | LR: 0.000017
Epoch: 047 | Train loss: 0.9962 | Train acc: 51.06% | Val loss: 0.9919 | Val acc: 54.51% | LR: 0.000017
Epoch: 048 | Train loss: 0.9968 | Train acc: 50.70% | Val loss: 0.9916 | Val acc: 54.57% | LR: 0.000017
Epoch: 049 | Train loss: 0.9970 | Train acc: 50.55% | Val loss: 0.9922 | Val acc: 54.53% | LR: 0.000016
Epoch: 050 | Train loss: 0.9978 | Train acc: 50.35% | Val loss: 0.9922 | Val acc: 54.57% | LR: 0.000016
Epoch: 051 | Train loss: 0.9951 | Train acc: 51.08% | Val loss: 0.9919 | Val acc: 54.57% | LR: 0.000016
Epoch: 052 | Train loss: 0.9988 | Train acc: 50.09% | Val loss: 0.9921 | Val acc: 54.63% | LR: 0.000016
Epoch: 053 | Train loss: 0.9963 | Train acc: 50.97% | Val loss: 0.9920 | Val acc: 54.63% | LR: 0.000016
Epoch: 054 | Train loss: 0.9954 | Train acc: 50.97% | Val loss: 0.9919 | Val acc: 54.59% | LR: 0.000015
Epoch: 055 | Train loss: 0.9955 | Train acc: 50.70% | Val loss: 0.9918 | Val acc: 54.58% | LR: 0.000015
Epoch: 056 | Train loss: 0.9952 | Train acc: 50.79% | Val loss: 0.9919 | Val acc: 54.63% | LR: 0.000015
Epoch: 057 | Train loss: 0.9954 | Train acc: 51.01% | Val loss: 0.9918 | Val acc: 54.68% | LR: 0.000015
Epoch: 058 | Train loss: 0.9968 | Train acc: 50.56% | Val loss: 0.9918 | Val acc: 54.64% | LR: 0.000015
Epoch: 059 | Train loss: 0.9957 | Train acc: 50.63% | Val loss: 0.9918 | Val acc: 54.70% | LR: 0.000014
Epoch: 060 | Train loss: 0.9948 | Train acc: 50.89% | Val loss: 0.9918 | Val acc: 54.74% | LR: 0.000014
Epoch: 061 | Train loss: 0.9935 | Train acc: 51.52% | Val loss: 0.9918 | Val acc: 54.58% | LR: 0.000014
Epoch: 062 | Train loss: 0.9935 | Train acc: 51.26% | Val loss: 0.9916 | Val acc: 54.58% | LR: 0.000014
Epoch: 063 | Train loss: 0.9971 | Train acc: 50.45% | Val loss: 0.9916 | Val acc: 54.47% | LR: 0.000014
Epoch: 064 | Train loss: 0.9959 | Train acc: 50.56% | Val loss: 0.9919 | Val acc: 54.47% | LR: 0.000013
Epoch: 065 | Train loss: 0.9947 | Train acc: 50.94% | Val loss: 0.9916 | Val acc: 54.51% | LR: 0.000013
Epoch: 066 | Train loss: 0.9967 | Train acc: 50.93% | Val loss: 0.9918 | Val acc: 54.33% | LR: 0.000013
Epoch: 067 | Train loss: 0.9958 | Train acc: 50.41% | Val loss: 0.9919 | Val acc: 54.26% | LR: 0.000013
Epoch: 068 | Train loss: 0.9962 | Train acc: 50.41% | Val loss: 0.9918 | Val acc: 54.24% | LR: 0.000013
Epoch: 069 | Train loss: 0.9954 | Train acc: 50.94% | Val loss: 0.9918 | Val acc: 54.35% | LR: 0.000012
Epoch: 070 | Train loss: 1.0057 | Train acc: 50.94% | Val loss: 0.9917 | Val acc: 54.39% | LR: 0.000012
Epoch: 071 | Train loss: 0.9963 | Train acc: 50.51% | Val loss: 0.9917 | Val acc: 54.33% | LR: 0.000012
Epoch: 072 | Train loss: 0.9927 | Train acc: 51.17% | Val loss: 0.9919 | Val acc: 54.29% | LR: 0.000012
Epoch: 073 | Train loss: 0.9935 | Train acc: 51.41% | Val loss: 0.9929 | Val acc: 54.29% | LR: 0.000011
Epoch: 074 | Train loss: 0.9928 | Train acc: 50.79% | Val loss: 0.9936 | Val acc: 54.16% | LR: 0.000011
Epoch: 075 | Train loss: 0.9941 | Train acc: 50.70% | Val loss: 0.9917 | Val acc: 54.29% | LR: 0.000011
Epoch: 076 | Train loss: 0.9950 | Train acc: 50.86% | Val loss: 1.0017 | Val acc: 54.26% | LR: 0.000011
Epoch: 077 | Train loss: 0.9942 | Train acc: 51.02% | Val loss: 0.9917 | Val acc: 54.18% | LR: 0.000011
Epoch: 078 | Train loss: 0.9948 | Train acc: 51.17% | Val loss: 0.9918 | Val acc: 54.10% | LR: 0.000010
Epoch: 079 | Train loss: 0.9940 | Train acc: 51.09% | Val loss: 0.9918 | Val acc: 54.24% | LR: 0.000010
Epoch: 080 | Train loss: 0.9938 | Train acc: 50.82% | Val loss: 0.9916 | Val acc: 54.20% | LR: 0.000010
Epoch: 081 | Train loss: 0.9935 | Train acc: 51.08% | Val loss: 0.9917 | Val acc: 54.16% | LR: 0.000010
Epoch: 082 | Train loss: 0.9955 | Train acc: 50.37% | Val loss: 0.9913 | Val acc: 54.20% | LR: 0.000010
Epoch: 083 | Train loss: 0.9940 | Train acc: 50.99% | Val loss: 0.9925 | Val acc: 54.20% | LR: 0.000009
Epoch: 084 | Train loss: 0.9933 | Train acc: 51.00% | Val loss: 0.9915 | Val acc: 54.12% | LR: 0.000009
Epoch: 085 | Train loss: 0.9962 | Train acc: 50.57% | Val loss: 0.9914 | Val acc: 54.06% | LR: 0.000009
Epoch: 086 | Train loss: 0.9936 | Train acc: 51.01% | Val loss: 0.9917 | Val acc: 54.04% | LR: 0.000009
Epoch: 087 | Train loss: 0.9916 | Train acc: 51.37% | Val loss: 0.9917 | Val acc: 54.01% | LR: 0.000008
Epoch: 088 | Train loss: 0.9934 | Train acc: 50.84% | Val loss: 0.9918 | Val acc: 53.99% | LR: 0.000008
Epoch: 089 | Train loss: 0.9958 | Train acc: 51.03% | Val loss: 0.9915 | Val acc: 54.03% | LR: 0.000008
Epoch: 090 | Train loss: 0.9943 | Train acc: 51.12% | Val loss: 0.9917 | Val acc: 53.85% | LR: 0.000008
Epoch: 091 | Train loss: 0.9944 | Train acc: 50.83% | Val loss: 0.9916 | Val acc: 53.83% | LR: 0.000008
Epoch: 092 | Train loss: 0.9905 | Train acc: 51.62% | Val loss: 0.9915 | Val acc: 53.89% | LR: 0.000007
Epoch: 093 | Train loss: 0.9929 | Train acc: 51.01% | Val loss: 0.9917 | Val acc: 53.89% | LR: 0.000007
Epoch: 094 | Train loss: 0.9936 | Train acc: 50.72% | Val loss: 0.9915 | Val acc: 53.93% | LR: 0.000007
Epoch: 095 | Train loss: 0.9960 | Train acc: 50.64% | Val loss: 0.9915 | Val acc: 53.84% | LR: 0.000007
Epoch: 096 | Train loss: 0.9916 | Train acc: 51.32% | Val loss: 0.9915 | Val acc: 53.86% | LR: 0.000007
Epoch: 097 | Train loss: 0.9932 | Train acc: 51.14% | Val loss: 0.9915 | Val acc: 53.72% | LR: 0.000006
Epoch: 098 | Train loss: 0.9971 | Train acc: 50.42% | Val loss: 0.9915 | Val acc: 53.64% | LR: 0.000006
Epoch: 099 | Train loss: 0.9950 | Train acc: 50.58% | Val loss: 0.9917 | Val acc: 53.56% | LR: 0.000006
Epoch: 100 | Train loss: 0.9886 | Train acc: 51.76% | Val loss: 0.9915 | Val acc: 53.58% | LR: 0.000006
Epoch: 101 | Train loss: 0.9959 | Train acc: 50.85% | Val loss: 0.9914 | Val acc: 53.60% | LR: 0.000006
Epoch: 102 | Train loss: 0.9925 | Train acc: 50.99% | Val loss: 0.9914 | Val acc: 53.56% | LR: 0.000006
Epoch: 103 | Train loss: 0.9938 | Train acc: 50.86% | Val loss: 0.9915 | Val acc: 53.56% | LR: 0.000005
Epoch: 104 | Train loss: 0.9936 | Train acc: 51.04% | Val loss: 0.9914 | Val acc: 53.56% | LR: 0.000005
Epoch: 105 | Train loss: 0.9948 | Train acc: 50.33% | Val loss: 0.9915 | Val acc: 53.54% | LR: 0.000005
Epoch: 106 | Train loss: 0.9945 | Train acc: 50.80% | Val loss: 0.9914 | Val acc: 53.50% | LR: 0.000005
Epoch: 107 | Train loss: 0.9940 | Train acc: 50.88% | Val loss: 0.9918 | Val acc: 53.48% | LR: 0.000005
Epoch: 108 | Train loss: 0.9945 | Train acc: 50.96% | Val loss: 0.9915 | Val acc: 53.48% | LR: 0.000005
Epoch: 109 | Train loss: 0.9955 | Train acc: 50.53% | Val loss: 0.9913 | Val acc: 53.50% | LR: 0.000004

[I 2025-09-23 17:35:07,527] Trial 71 finished with value: 0.5344243884086609 and parameters: {'lr': 2.144942494494285e-05, 'hidden_size': 64, 'dropout': 0.36344186422953667, 'weight_decay': 1.115060005281124e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0000 | Train acc: 49.82% | Val loss: 1.0042 | Val acc: 45.95% | LR: 0.000013
Epoch: 001 | Train loss: 0.9994 | Train acc: 50.39% | Val loss: 1.0042 | Val acc: 45.91% | LR: 0.000013
Epoch: 002 | Train loss: 0.9996 | Train acc: 49.93% | Val loss: 1.0046 | Val acc: 45.93% | LR: 0.000013
Epoch: 003 | Train loss: 0.9996 | Train acc: 49.94% | Val loss: 1.0043 | Val acc: 45.93% | LR: 0.000013
Epoch: 004 | Train loss: 0.9994 | Train acc: 50.33% | Val loss: 1.0044 | Val acc: 45.93% | LR: 0.000013
Epoch: 005 | Train loss: 0.9993 | Train acc: 50.42% | Val loss: 1.0044 | Val acc: 45.97% | LR: 0.000013
Epoch: 006 | Train loss: 0.9991 | Train acc: 50.42% | Val loss: 1.0044 | Val acc: 45.97% | LR: 0.000013
Epoch: 007 | Train loss: 0.9983 | Train acc: 50.87% | Val loss: 1.0044 | Val acc: 45.97% | LR: 0.000013
Epoch: 008 | Train loss: 0.9990 | Train acc: 50.66% | Val loss: 1.0045 | Val acc: 45.97% | LR: 0.000013
Epoch: 009 | Train loss: 0.9991 | Train acc: 50.58% | Val loss: 1.0045 | Val acc: 46.11% | LR: 0.000013
Epoch: 010 | Train loss: 0.9989 | Train acc: 50.59% | Val loss: 1.0045 | Val acc: 46.15% | LR: 0.000013
Epoch: 011 | Train loss: 0.9987 | Train acc: 50.68% | Val loss: 1.0045 | Val acc: 46.19% | LR: 0.000013
Epoch: 012 | Train loss: 0.9984 | Train acc: 50.68% | Val loss: 1.0045 | Val acc: 46.21% | LR: 0.000013
Epoch: 013 | Train loss: 0.9980 | Train acc: 50.77% | Val loss: 1.0045 | Val acc: 46.15% | LR: 0.000013
Epoch: 014 | Train loss: 1.0002 | Train acc: 49.89% | Val loss: 1.0046 | Val acc: 46.15% | LR: 0.000013
Epoch: 015 | Train loss: 0.9976 | Train acc: 51.03% | Val loss: 1.0045 | Val acc: 46.24% | LR: 0.000012
Epoch: 016 | Train loss: 0.9983 | Train acc: 50.59% | Val loss: 1.0046 | Val acc: 46.24% | LR: 0.000012
Epoch: 017 | Train loss: 0.9992 | Train acc: 50.33% | Val loss: 1.0046 | Val acc: 46.25% | LR: 0.000012
Epoch: 018 | Train loss: 0.9984 | Train acc: 50.60% | Val loss: 1.0046 | Val acc: 46.44% | LR: 0.000012
Epoch: 019 | Train loss: 0.9996 | Train acc: 50.17% | Val loss: 1.0046 | Val acc: 46.38% | LR: 0.000012
Epoch: 020 | Train loss: 0.9984 | Train acc: 50.62% | Val loss: 1.0046 | Val acc: 46.48% | LR: 0.000012
Epoch: 021 | Train loss: 0.9975 | Train acc: 50.89% | Val loss: 1.0046 | Val acc: 46.44% | LR: 0.000012
Epoch: 022 | Train loss: 0.9979 | Train acc: 50.73% | Val loss: 1.0046 | Val acc: 46.46% | LR: 0.000012
Epoch: 023 | Train loss: 0.9978 | Train acc: 50.64% | Val loss: 1.0046 | Val acc: 46.33% | LR: 0.000012
Epoch: 024 | Train loss: 0.9982 | Train acc: 50.53% | Val loss: 1.0046 | Val acc: 46.34% | LR: 0.000012
Epoch: 025 | Train loss: 0.9986 | Train acc: 50.52% | Val loss: 1.0047 | Val acc: 46.38% | LR: 0.000012
Epoch: 026 | Train loss: 0.9988 | Train acc: 50.34% | Val loss: 1.0047 | Val acc: 46.36% | LR: 0.000012
Epoch: 027 | Train loss: 0.9965 | Train acc: 50.89% | Val loss: 1.0047 | Val acc: 46.42% | LR: 0.000012
Epoch: 028 | Train loss: 0.9977 | Train acc: 50.72% | Val loss: 1.0046 | Val acc: 46.42% | LR: 0.000012
Epoch: 029 | Train loss: 0.9981 | Train acc: 50.46% | Val loss: 1.0048 | Val acc: 46.52% | LR: 0.000012
Epoch: 030 | Train loss: 0.9982 | Train acc: 50.45% | Val loss: 1.0048 | Val acc: 46.42% | LR: 0.000012
Epoch: 031 | Train loss: 0.9957 | Train acc: 51.12% | Val loss: 1.0048 | Val acc: 46.44% | LR: 0.000012
Epoch: 032 | Train loss: 0.9974 | Train acc: 50.71% | Val loss: 1.0048 | Val acc: 46.46% | LR: 0.000011
Epoch: 033 | Train loss: 0.9980 | Train acc: 50.44% | Val loss: 1.0048 | Val acc: 46.64% | LR: 0.000011
Epoch: 034 | Train loss: 0.9977 | Train acc: 50.88% | Val loss: 1.0047 | Val acc: 46.60% | LR: 0.000011
Epoch: 035 | Train loss: 0.9975 | Train acc: 50.61% | Val loss: 1.0047 | Val acc: 46.66% | LR: 0.000011
Epoch: 036 | Train loss: 0.9986 | Train acc: 50.38% | Val loss: 1.0047 | Val acc: 46.58% | LR: 0.000011
Epoch: 037 | Train loss: 0.9982 | Train acc: 50.46% | Val loss: 1.0046 | Val acc: 46.56% | LR: 0.000011
Epoch: 038 | Train loss: 0.9966 | Train acc: 50.82% | Val loss: 1.0046 | Val acc: 46.66% | LR: 0.000011
Epoch: 039 | Train loss: 0.9947 | Train acc: 51.06% | Val loss: 1.0046 | Val acc: 46.68% | LR: 0.000011
Epoch: 040 | Train loss: 0.9966 | Train acc: 50.90% | Val loss: 1.0046 | Val acc: 46.66% | LR: 0.000011
Epoch: 041 | Train loss: 0.9964 | Train acc: 51.00% | Val loss: 1.0047 | Val acc: 46.66% | LR: 0.000011
Epoch: 042 | Train loss: 0.9963 | Train acc: 50.73% | Val loss: 1.0048 | Val acc: 46.62% | LR: 0.000011
Epoch: 043 | Train loss: 0.9968 | Train acc: 50.63% | Val loss: 1.0048 | Val acc: 46.68% | LR: 0.000010
Epoch: 044 | Train loss: 0.9951 | Train acc: 51.10% | Val loss: 1.0048 | Val acc: 46.82% | LR: 0.000010
Epoch: 045 | Train loss: 0.9953 | Train acc: 50.83% | Val loss: 1.0048 | Val acc: 46.87% | LR: 0.000010
Epoch: 046 | Train loss: 0.9954 | Train acc: 50.95% | Val loss: 1.0048 | Val acc: 46.78% | LR: 0.000010
Epoch: 047 | Train loss: 0.9978 | Train acc: 50.33% | Val loss: 1.0048 | Val acc: 46.72% | LR: 0.000010
Epoch: 048 | Train loss: 0.9976 | Train acc: 50.35% | Val loss: 1.0048 | Val acc: 46.70% | LR: 0.000010
Epoch: 049 | Train loss: 0.9960 | Train acc: 50.86% | Val loss: 1.0047 | Val acc: 46.64% | LR: 0.000010
Epoch: 050 | Train loss: 0.9950 | Train acc: 50.99% | Val loss: 1.0047 | Val acc: 46.72% | LR: 0.000010
Epoch: 051 | Train loss: 0.9978 | Train acc: 50.46% | Val loss: 1.0047 | Val acc: 46.70% | LR: 0.000010
Epoch: 052 | Train loss: 0.9952 | Train acc: 50.92% | Val loss: 1.0047 | Val acc: 46.62% | LR: 0.000010
Epoch: 053 | Train loss: 1.0065 | Train acc: 50.62% | Val loss: 1.0047 | Val acc: 46.74% | LR: 0.000009
Epoch: 054 | Train loss: 0.9954 | Train acc: 51.00% | Val loss: 1.0048 | Val acc: 46.82% | LR: 0.000009
Epoch: 055 | Train loss: 0.9946 | Train acc: 51.01% | Val loss: 1.0060 | Val acc: 46.80% | LR: 0.000009
Epoch: 056 | Train loss: 0.9970 | Train acc: 50.58% | Val loss: 1.0045 | Val acc: 46.88% | LR: 0.000009
Epoch: 057 | Train loss: 0.9977 | Train acc: 50.42% | Val loss: 1.0045 | Val acc: 46.86% | LR: 0.000009
Epoch: 058 | Train loss: 0.9972 | Train acc: 50.61% | Val loss: 1.0044 | Val acc: 46.92% | LR: 0.000009
Epoch: 059 | Train loss: 0.9927 | Train acc: 51.43% | Val loss: 1.0044 | Val acc: 46.98% | LR: 0.000009
Epoch: 060 | Train loss: 1.0002 | Train acc: 50.08% | Val loss: 1.0315 | Val acc: 47.09% | LR: 0.000009
Epoch: 061 | Train loss: 0.9934 | Train acc: 51.17% | Val loss: 1.0045 | Val acc: 47.04% | LR: 0.000008
Epoch: 062 | Train loss: 0.9920 | Train acc: 51.38% | Val loss: 1.0089 | Val acc: 46.99% | LR: 0.000008
Epoch: 063 | Train loss: 0.9974 | Train acc: 51.16% | Val loss: 1.0040 | Val acc: 47.06% | LR: 0.000008
Epoch: 064 | Train loss: 0.9946 | Train acc: 50.87% | Val loss: 1.0042 | Val acc: 46.94% | LR: 0.000008
Epoch: 065 | Train loss: 0.9934 | Train acc: 50.97% | Val loss: 1.0041 | Val acc: 46.90% | LR: 0.000008
Epoch: 066 | Train loss: 0.9997 | Train acc: 50.72% | Val loss: 1.0041 | Val acc: 46.98% | LR: 0.000008
Epoch: 067 | Train loss: 0.9938 | Train acc: 51.13% | Val loss: 1.0041 | Val acc: 46.96% | LR: 0.000008
Epoch: 068 | Train loss: 0.9935 | Train acc: 51.03% | Val loss: 1.0041 | Val acc: 47.00% | LR: 0.000008
Epoch: 069 | Train loss: 0.9951 | Train acc: 50.83% | Val loss: 1.0042 | Val acc: 47.02% | LR: 0.000008
Epoch: 070 | Train loss: 0.9971 | Train acc: 50.49% | Val loss: 1.0037 | Val acc: 47.04% | LR: 0.000007
Epoch: 071 | Train loss: 0.9959 | Train acc: 50.76% | Val loss: 1.0044 | Val acc: 46.94% | LR: 0.000007
Epoch: 072 | Train loss: 0.9950 | Train acc: 50.84% | Val loss: 1.0043 | Val acc: 46.92% | LR: 0.000007
Epoch: 073 | Train loss: 1.0042 | Train acc: 51.58% | Val loss: 1.0042 | Val acc: 46.92% | LR: 0.000007
Epoch: 074 | Train loss: 0.9892 | Train acc: 51.51% | Val loss: 1.0042 | Val acc: 46.92% | LR: 0.000007
Epoch: 075 | Train loss: 0.9926 | Train acc: 51.03% | Val loss: 1.0043 | Val acc: 46.92% | LR: 0.000007
Epoch: 076 | Train loss: 0.9926 | Train acc: 51.13% | Val loss: 1.0047 | Val acc: 46.88% | LR: 0.000007
Epoch: 077 | Train loss: 0.9952 | Train acc: 50.49% | Val loss: 1.0111 | Val acc: 46.92% | LR: 0.000007
Epoch: 078 | Train loss: 0.9962 | Train acc: 50.70% | Val loss: 1.0039 | Val acc: 46.96% | LR: 0.000006
Epoch: 079 | Train loss: 0.9934 | Train acc: 51.00% | Val loss: 1.0040 | Val acc: 47.06% | LR: 0.000006
Epoch: 080 | Train loss: 0.9961 | Train acc: 50.71% | Val loss: 1.0040 | Val acc: 47.02% | LR: 0.000006
Epoch: 081 | Train loss: 0.9928 | Train acc: 51.31% | Val loss: 1.0039 | Val acc: 47.02% | LR: 0.000006
Epoch: 082 | Train loss: 0.9925 | Train acc: 51.40% | Val loss: 1.0039 | Val acc: 47.00% | LR: 0.000006
Epoch: 083 | Train loss: 0.9900 | Train acc: 51.23% | Val loss: 1.0039 | Val acc: 47.00% | LR: 0.000006
Epoch: 084 | Train loss: 0.9941 | Train acc: 51.13% | Val loss: 1.0039 | Val acc: 47.08% | LR: 0.000006
Epoch: 085 | Train loss: 0.9939 | Train acc: 51.22% | Val loss: 1.0039 | Val acc: 47.08% | LR: 0.000006
Epoch: 086 | Train loss: 0.9946 | Train acc: 50.52% | Val loss: 1.0039 | Val acc: 47.06% | LR: 0.000005
Epoch: 087 | Train loss: 0.9896 | Train acc: 51.31% | Val loss: 1.0039 | Val acc: 47.02% | LR: 0.000005
Epoch: 088 | Train loss: 0.9946 | Train acc: 51.05% | Val loss: 1.0039 | Val acc: 47.06% | LR: 0.000005
Epoch: 089 | Train loss: 0.9969 | Train acc: 50.60% | Val loss: 1.0038 | Val acc: 47.08% | LR: 0.000005
Epoch: 090 | Train loss: 1.0710 | Train acc: 51.33% | Val loss: 1.0038 | Val acc: 47.14% | LR: 0.000005
Epoch: 091 | Train loss: 0.9930 | Train acc: 51.01% | Val loss: 1.0038 | Val acc: 47.20% | LR: 0.000005
Epoch: 092 | Train loss: 0.9944 | Train acc: 50.83% | Val loss: 1.0037 | Val acc: 47.34% | LR: 0.000005
Epoch: 093 | Train loss: 0.9940 | Train acc: 50.94% | Val loss: 1.0037 | Val acc: 47.32% | LR: 0.000005
Epoch: 094 | Train loss: 0.9977 | Train acc: 50.25% | Val loss: 1.0035 | Val acc: 47.34% | LR: 0.000004
Epoch: 095 | Train loss: 0.9941 | Train acc: 50.77% | Val loss: 1.0035 | Val acc: 47.30% | LR: 0.000004
Epoch: 096 | Train loss: 0.9925 | Train acc: 51.13% | Val loss: 1.0043 | Val acc: 47.31% | LR: 0.000004
Epoch: 097 | Train loss: 0.9941 | Train acc: 51.12% | Val loss: 1.0039 | Val acc: 47.35% | LR: 0.000004
Epoch: 098 | Train loss: 0.9961 | Train acc: 50.50% | Val loss: 1.0039 | Val acc: 47.39% | LR: 0.000004
Epoch: 099 | Train loss: 0.9980 | Train acc: 50.24% | Val loss: 1.0038 | Val acc: 47.37% | LR: 0.000004
Epoch: 100 | Train loss: 0.9941 | Train acc: 50.79% | Val loss: 1.0038 | Val acc: 47.41% | LR: 0.000004
Epoch: 101 | Train loss: 0.9945 | Train acc: 50.95% | Val loss: 1.0038 | Val acc: 47.39% | LR: 0.000004
Epoch: 102 | Train loss: 0.9987 | Train acc: 50.44% | Val loss: 1.0038 | Val acc: 47.33% | LR: 0.000004
Epoch: 103 | Train loss: 0.9916 | Train acc: 51.07% | Val loss: 1.0038 | Val acc: 47.29% | LR: 0.000004
Epoch: 104 | Train loss: 0.9930 | Train acc: 50.63% | Val loss: 1.0037 | Val acc: 47.39% | LR: 0.000003
Epoch: 105 | Train loss: 0.9935 | Train acc: 50.99% | Val loss: 1.0037 | Val acc: 47.39% | LR: 0.000003
Epoch: 106 | Train loss: 0.9943 | Train acc: 51.16% | Val loss: 1.0037 | Val acc: 47.39% | LR: 0.000003
Epoch: 107 | Train loss: 1.0401 | Train acc: 51.50% | Val loss: 1.0037 | Val acc: 47.43% | LR: 0.000003
Epoch: 108 | Train loss: 0.9929 | Train acc: 50.98% | Val loss: 1.0037 | Val acc: 47.43% | LR: 0.000003
Epoch: 109 | Train loss: 0.9924 | Train acc: 51.01% | Val loss: 1.0037 | Val acc: 47.45% | LR: 0.000003
Epoch: 110 | Train loss: 0.9986 | Train acc: 51.16% | Val loss: 1.0037 | Val acc: 47.45% | LR: 0.000003
Epoch: 111 | Train loss: 0.9972 | Train acc: 50.64% | Val loss: 1.0037 | Val acc: 47.47% | LR: 0.000003
Epoch: 112 | Train loss: 0.9959 | Train acc: 50.90% | Val loss: 1.0037 | Val acc: 47.57% | LR: 0.000003
Epoch: 113 | Train loss: 0.9920 | Train acc: 51.17% | Val loss: 1.0036 | Val acc: 47.56% | LR: 0.000003
Epoch: 114 | Train loss: 0.9969 | Train acc: 50.72% | Val loss: 1.0033 | Val acc: 47.63% | LR: 0.000003
Epoch: 115 | Train loss: 0.9926 | Train acc: 50.97% | Val loss: 1.0037 | Val acc: 47.61% | LR: 0.000002
Epoch: 116 | Train loss: 0.9960 | Train acc: 50.44% | Val loss: 1.0034 | Val acc: 47.64% | LR: 0.000002
Epoch: 117 | Train loss: 0.9983 | Train acc: 50.54% | Val loss: 1.0035 | Val acc: 47.61% | LR: 0.000002
Epoch: 118 | Train loss: 0.9907 | Train acc: 51.67% | Val loss: 1.0034 | Val acc: 47.61% | LR: 0.000002
Epoch: 119 | Train loss: 0.9925 | Train acc: 50.98% | Val loss: 1.0034 | Val acc: 47.64% | LR: 0.000002
Epoch: 120 | Train loss: 0.9915 | Train acc: 50.81% | Val loss: 1.0043 | Val acc: 47.64% | LR: 0.000002
Epoch: 121 | Train loss: 0.9963 | Train acc: 50.46% | Val loss: 1.0040 | Val acc: 47.64% | LR: 0.000002
Epoch: 122 | Train loss: 0.9880 | Train acc: 51.34% | Val loss: 1.0040 | Val acc: 47.70% | LR: 0.000002
Epoch: 123 | Train loss: 0.9937 | Train acc: 50.88% | Val loss: 1.0040 | Val acc: 47.74% | LR: 0.000002
Epoch: 124 | Train loss: 0.9952 | Train acc: 50.61% | Val loss: 1.0040 | Val acc: 47.74% | LR: 0.000002
Epoch: 125 | Train loss: 0.9935 | Train acc: 51.06% | Val loss: 1.0040 | Val acc: 47.74% | LR: 0.000002
Epoch: 126 | Train loss: 0.9919 | Train acc: 50.87% | Val loss: 1.0039 | Val acc: 47.74% | LR: 0.000002
Epoch: 127 | Train loss: 0.9910 | Train acc: 51.05% | Val loss: 1.0039 | Val acc: 47.74% | LR: 0.000002
Epoch: 128 | Train loss: 0.9895 | Train acc: 51.24% | Val loss: 1.0039 | Val acc: 47.76% | LR: 0.000002
Epoch: 129 | Train loss: 0.9905 | Train acc: 51.23% | Val loss: 1.0039 | Val acc: 47.76% | LR: 0.000002
Epoch: 130 | Train loss: 0.9921 | Train acc: 50.97% | Val loss: 1.0040 | Val acc: 47.77% | LR: 0.000001
Epoch: 131 | Train loss: 0.9890 | Train acc: 51.32% | Val loss: 1.0040 | Val acc: 47.77% | LR: 0.000001
Epoch: 132 | Train loss: 0.9903 | Train acc: 51.15% | Val loss: 1.0040 | Val acc: 47.77% | LR: 0.000001
Epoch: 133 | Train loss: 0.9908 | Train acc: 50.71% | Val loss: 1.0040 | Val acc: 47.77% | LR: 0.000001
Epoch: 134 | Train loss: 0.9905 | Train acc: 51.15% | Val loss: 1.0041 | Val acc: 47.77% | LR: 0.000001
Epoch: 135 | Train loss: 0.9922 | Train acc: 50.97% | Val loss: 1.0041 | Val acc: 47.77% | LR: 0.000001
Epoch: 136 | Train loss: 0.9906 | Train acc: 51.24% | Val loss: 1.0041 | Val acc: 47.77% | LR: 0.000001
Epoch: 137 | Train loss: 0.9889 | Train acc: 51.24% | Val loss: 1.0042 | Val acc: 47.77% | LR: 0.000001
Epoch: 138 | Train loss: 0.9935 | Train acc: 50.88% | Val loss: 1.0042 | Val acc: 47.78% | LR: 0.000001
Epoch: 139 | Train loss: 0.9916 | Train acc: 51.15% | Val loss: 1.0043 | Val acc: 47.78% | LR: 0.000001
Epoch: 140 | Train loss: 0.9942 | Train acc: 50.97% | Val loss: 1.0045 | Val acc: 47.78% | LR: 0.000001
Epoch: 141 | Train loss: 0.9955 | Train acc: 50.80% | Val loss: 1.0046 | Val acc: 47.78% | LR: 0.000001
Epoch: 142 | Train loss: 0.9964 | Train acc: 50.79% | Val loss: 1.0048 | Val acc: 47.78% | LR: 0.000001
Epoch: 143 | Train loss: 0.9875 | Train acc: 51.32% | Val loss: 1.0048 | Val acc: 47.77% | LR: 0.000001
Epoch: 144 | Train loss: 0.9932 | Train acc: 50.97% | Val loss: 1.0052 | Val acc: 47.78% | LR: 0.000001
Epoch: 145 | Train loss: 0.9932 | Train acc: 50.69% | Val loss: 1.0054 | Val acc: 47.78% | LR: 0.000001
Epoch: 146 | Train loss: 0.9920 | Train acc: 51.05% | Val loss: 1.0056 | Val acc: 47.78% | LR: 0.000001
Epoch: 147 | Train loss: 0.9926 | Train acc: 51.05% | Val loss: 1.0056 | Val acc: 47.78% | LR: 0.000001
Epoch: 148 | Train loss: 0.9912 | Train acc: 51.05% | Val loss: 1.0062 | Val acc: 47.77% | LR: 0.000001
Epoch: 149 | Train loss: 0.9916 | Train acc: 50.88% | Val loss: 1.0071 | Val acc: 47.77% | LR: 0.000001

[I 2025-09-23 17:37:07,209] Trial 72 finished with value: 0.4776530861854553 and parameters: {'lr': 1.278949643467557e-05, 'hidden_size': 80, 'dropout': 0.36202431771228055, 'weight_decay': 1.8562017740121807e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9995 | Train acc: 50.44% | Val loss: 1.0068 | Val acc: 46.14% | LR: 0.000025
Epoch: 001 | Train loss: 0.9994 | Train acc: 50.65% | Val loss: 1.0069 | Val acc: 46.14% | LR: 0.000025
Epoch: 002 | Train loss: 1.0029 | Train acc: 49.78% | Val loss: 1.0095 | Val acc: 46.20% | LR: 0.000025
Epoch: 003 | Train loss: 0.9997 | Train acc: 50.65% | Val loss: 1.0063 | Val acc: 46.25% | LR: 0.000025
Epoch: 004 | Train loss: 1.0000 | Train acc: 50.90% | Val loss: 1.0221 | Val acc: 46.49% | LR: 0.000025
Epoch: 005 | Train loss: 0.9985 | Train acc: 50.61% | Val loss: 1.0123 | Val acc: 46.24% | LR: 0.000025
Epoch: 006 | Train loss: 0.9987 | Train acc: 50.13% | Val loss: 1.0069 | Val acc: 46.11% | LR: 0.000025
Epoch: 007 | Train loss: 0.9984 | Train acc: 50.55% | Val loss: 1.0075 | Val acc: 46.24% | LR: 0.000025
Epoch: 008 | Train loss: 0.9991 | Train acc: 50.22% | Val loss: 1.0082 | Val acc: 46.32% | LR: 0.000025
Epoch: 009 | Train loss: 0.9979 | Train acc: 50.89% | Val loss: 1.0168 | Val acc: 46.26% | LR: 0.000025
Epoch: 010 | Train loss: 1.0001 | Train acc: 49.87% | Val loss: 1.8970 | Val acc: 46.20% | LR: 0.000025
Epoch: 011 | Train loss: 0.9995 | Train acc: 50.12% | Val loss: 1.0068 | Val acc: 46.36% | LR: 0.000024
Epoch: 012 | Train loss: 0.9986 | Train acc: 50.60% | Val loss: 1.0217 | Val acc: 46.20% | LR: 0.000024
Epoch: 013 | Train loss: 0.9989 | Train acc: 50.39% | Val loss: 1.0074 | Val acc: 46.22% | LR: 0.000024
Epoch: 014 | Train loss: 0.9977 | Train acc: 50.81% | Val loss: 1.0076 | Val acc: 46.20% | LR: 0.000024
Epoch: 015 | Train loss: 0.9991 | Train acc: 50.10% | Val loss: 1.0065 | Val acc: 46.18% | LR: 0.000024
Epoch: 016 | Train loss: 0.9976 | Train acc: 50.84% | Val loss: 1.0063 | Val acc: 46.24% | LR: 0.000024
Epoch: 017 | Train loss: 0.9971 | Train acc: 50.88% | Val loss: 1.0066 | Val acc: 45.96% | LR: 0.000024
Epoch: 018 | Train loss: 0.9985 | Train acc: 50.17% | Val loss: 1.0084 | Val acc: 46.14% | LR: 0.000024
Epoch: 019 | Train loss: 0.9971 | Train acc: 50.80% | Val loss: 1.0078 | Val acc: 45.98% | LR: 0.000024
Epoch: 020 | Train loss: 0.9967 | Train acc: 50.77% | Val loss: 1.0064 | Val acc: 46.10% | LR: 0.000024
Epoch: 021 | Train loss: 0.9979 | Train acc: 50.40% | Val loss: 1.0066 | Val acc: 46.16% | LR: 0.000024
Epoch: 022 | Train loss: 0.9985 | Train acc: 50.22% | Val loss: 1.0066 | Val acc: 46.06% | LR: 0.000023
Epoch: 023 | Train loss: 0.9975 | Train acc: 50.32% | Val loss: 1.0064 | Val acc: 46.18% | LR: 0.000023
Epoch: 024 | Train loss: 0.9966 | Train acc: 50.77% | Val loss: 1.0061 | Val acc: 46.12% | LR: 0.000023
Epoch: 025 | Train loss: 0.9956 | Train acc: 50.86% | Val loss: 1.0068 | Val acc: 45.98% | LR: 0.000023
Epoch: 026 | Train loss: 0.9981 | Train acc: 50.70% | Val loss: 1.0077 | Val acc: 46.01% | LR: 0.000023
Epoch: 027 | Train loss: 0.9973 | Train acc: 50.48% | Val loss: 1.0076 | Val acc: 45.83% | LR: 0.000023
Epoch: 028 | Train loss: 0.9978 | Train acc: 50.33% | Val loss: 1.0077 | Val acc: 46.20% | LR: 0.000023
Epoch: 029 | Train loss: 0.9962 | Train acc: 50.60% | Val loss: 1.0065 | Val acc: 46.10% | LR: 0.000023
Epoch: 030 | Train loss: 0.9950 | Train acc: 50.94% | Val loss: 1.0070 | Val acc: 46.07% | LR: 0.000022
Epoch: 031 | Train loss: 1.0024 | Train acc: 50.39% | Val loss: 1.0063 | Val acc: 45.90% | LR: 0.000022
Epoch: 032 | Train loss: 0.9961 | Train acc: 50.48% | Val loss: 1.0078 | Val acc: 46.10% | LR: 0.000022
Epoch: 033 | Train loss: 1.0000 | Train acc: 49.77% | Val loss: 1.0057 | Val acc: 46.05% | LR: 0.000022
Epoch: 034 | Train loss: 1.0033 | Train acc: 50.14% | Val loss: 1.0099 | Val acc: 46.11% | LR: 0.000022
Epoch: 035 | Train loss: 0.9983 | Train acc: 50.22% | Val loss: 1.0067 | Val acc: 46.11% | LR: 0.000022
Epoch: 036 | Train loss: 0.9968 | Train acc: 50.48% | Val loss: 1.0071 | Val acc: 45.99% | LR: 0.000021
Epoch: 037 | Train loss: 0.9955 | Train acc: 50.73% | Val loss: 1.0116 | Val acc: 45.96% | LR: 0.000021
Epoch: 038 | Train loss: 1.0012 | Train acc: 49.99% | Val loss: 1.0084 | Val acc: 45.96% | LR: 0.000021
Epoch: 039 | Train loss: 0.9976 | Train acc: 50.25% | Val loss: 1.0071 | Val acc: 45.89% | LR: 0.000021
Epoch: 040 | Train loss: 0.9958 | Train acc: 50.75% | Val loss: 1.0072 | Val acc: 46.05% | LR: 0.000021
Epoch: 041 | Train loss: 0.9973 | Train acc: 50.41% | Val loss: 1.0073 | Val acc: 45.99% | LR: 0.000021
Epoch: 042 | Train loss: 0.9956 | Train acc: 50.49% | Val loss: 1.0071 | Val acc: 46.05% | LR: 0.000020
Epoch: 043 | Train loss: 0.9980 | Train acc: 50.57% | Val loss: 1.0066 | Val acc: 46.02% | LR: 0.000020
Epoch: 044 | Train loss: 0.9968 | Train acc: 50.35% | Val loss: 1.0115 | Val acc: 46.03% | LR: 0.000020
Epoch: 045 | Train loss: 0.9955 | Train acc: 50.59% | Val loss: 1.0073 | Val acc: 46.11% | LR: 0.000020
Epoch: 046 | Train loss: 0.9924 | Train acc: 51.05% | Val loss: 1.0058 | Val acc: 46.03% | LR: 0.000020
Epoch: 047 | Train loss: 0.9979 | Train acc: 50.18% | Val loss: 1.0232 | Val acc: 46.03% | LR: 0.000019
Epoch: 048 | Train loss: 0.9952 | Train acc: 50.69% | Val loss: 1.0076 | Val acc: 45.90% | LR: 0.000019
Epoch: 049 | Train loss: 0.9944 | Train acc: 50.55% | Val loss: 1.0070 | Val acc: 46.05% | LR: 0.000019
Epoch: 050 | Train loss: 0.9979 | Train acc: 50.20% | Val loss: 1.0078 | Val acc: 46.11% | LR: 0.000019
Epoch: 051 | Train loss: 0.9933 | Train acc: 50.80% | Val loss: 1.0081 | Val acc: 45.99% | LR: 0.000018
Epoch: 052 | Train loss: 0.9997 | Train acc: 49.89% | Val loss: 1.0078 | Val acc: 46.09% | LR: 0.000018
Epoch: 053 | Train loss: 0.9972 | Train acc: 50.18% | Val loss: 1.0074 | Val acc: 46.05% | LR: 0.000018

[I 2025-09-23 17:37:54,533] Trial 73 finished with value: 0.4603503465652466 and parameters: {'lr': 2.4837869662448574e-05, 'hidden_size': 67, 'dropout': 0.3968950733656286, 'weight_decay': 1.0519565323756813e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0028 | Train acc: 49.99% | Val loss: 0.9930 | Val acc: 54.02% | LR: 0.000016
Epoch: 001 | Train loss: 1.0002 | Train acc: 50.13% | Val loss: 0.9923 | Val acc: 54.09% | LR: 0.000016
Epoch: 002 | Train loss: 0.9995 | Train acc: 50.05% | Val loss: 0.9935 | Val acc: 53.88% | LR: 0.000016
Epoch: 003 | Train loss: 0.9982 | Train acc: 50.39% | Val loss: 0.9924 | Val acc: 53.92% | LR: 0.000016
Epoch: 004 | Train loss: 1.0005 | Train acc: 50.02% | Val loss: 0.9946 | Val acc: 53.80% | LR: 0.000016
Epoch: 005 | Train loss: 0.9991 | Train acc: 50.11% | Val loss: 0.9927 | Val acc: 54.00% | LR: 0.000016
Epoch: 006 | Train loss: 1.0004 | Train acc: 49.85% | Val loss: 0.9926 | Val acc: 53.91% | LR: 0.000016
Epoch: 007 | Train loss: 0.9970 | Train acc: 50.91% | Val loss: 0.9947 | Val acc: 54.12% | LR: 0.000016
Epoch: 008 | Train loss: 1.0033 | Train acc: 49.94% | Val loss: 0.9949 | Val acc: 53.96% | LR: 0.000016
Epoch: 009 | Train loss: 0.9988 | Train acc: 50.30% | Val loss: 0.9935 | Val acc: 53.78% | LR: 0.000016
Epoch: 010 | Train loss: 1.0009 | Train acc: 49.77% | Val loss: 1.0013 | Val acc: 53.97% | LR: 0.000016
Epoch: 011 | Train loss: 0.9988 | Train acc: 50.30% | Val loss: 0.9945 | Val acc: 53.83% | LR: 0.000016
Epoch: 012 | Train loss: 1.0004 | Train acc: 49.95% | Val loss: 0.9931 | Val acc: 53.97% | LR: 0.000016
Epoch: 013 | Train loss: 0.9986 | Train acc: 50.23% | Val loss: 0.9933 | Val acc: 53.85% | LR: 0.000016
Epoch: 014 | Train loss: 0.9987 | Train acc: 50.29% | Val loss: 0.9930 | Val acc: 53.76% | LR: 0.000015
Epoch: 015 | Train loss: 0.9993 | Train acc: 50.14% | Val loss: 0.9931 | Val acc: 53.99% | LR: 0.000015
Epoch: 016 | Train loss: 0.9997 | Train acc: 50.13% | Val loss: 0.9931 | Val acc: 53.81% | LR: 0.000015
Epoch: 017 | Train loss: 0.9994 | Train acc: 50.12% | Val loss: 0.9926 | Val acc: 53.87% | LR: 0.000015
Epoch: 018 | Train loss: 0.9990 | Train acc: 50.13% | Val loss: 0.9937 | Val acc: 53.93% | LR: 0.000015
Epoch: 019 | Train loss: 1.0002 | Train acc: 49.95% | Val loss: 0.9933 | Val acc: 53.93% | LR: 0.000015
Epoch: 020 | Train loss: 0.9980 | Train acc: 50.40% | Val loss: 0.9942 | Val acc: 53.95% | LR: 0.000015
Epoch: 021 | Train loss: 0.9973 | Train acc: 50.49% | Val loss: 0.9927 | Val acc: 53.99% | LR: 0.000015
Epoch: 022 | Train loss: 1.0000 | Train acc: 49.78% | Val loss: 0.9932 | Val acc: 53.97% | LR: 0.000015
Epoch: 023 | Train loss: 0.9983 | Train acc: 50.04% | Val loss: 0.9932 | Val acc: 53.89% | LR: 0.000015
Epoch: 024 | Train loss: 0.9987 | Train acc: 50.21% | Val loss: 0.9940 | Val acc: 53.76% | LR: 0.000015
Epoch: 025 | Train loss: 0.9989 | Train acc: 50.22% | Val loss: 0.9949 | Val acc: 53.92% | LR: 0.000015
Epoch: 026 | Train loss: 0.9981 | Train acc: 50.40% | Val loss: 0.9932 | Val acc: 54.00% | LR: 0.000015
Epoch: 027 | Train loss: 0.9974 | Train acc: 50.41% | Val loss: 0.9929 | Val acc: 53.99% | LR: 0.000015
Epoch: 028 | Train loss: 1.0018 | Train acc: 49.60% | Val loss: 0.9923 | Val acc: 53.99% | LR: 0.000015
Epoch: 029 | Train loss: 0.9991 | Train acc: 50.13% | Val loss: 0.9927 | Val acc: 53.93% | LR: 0.000014
Epoch: 030 | Train loss: 0.9990 | Train acc: 49.95% | Val loss: 0.9931 | Val acc: 53.95% | LR: 0.000014
Epoch: 031 | Train loss: 0.9976 | Train acc: 50.05% | Val loss: 0.9933 | Val acc: 53.88% | LR: 0.000014
Epoch: 032 | Train loss: 0.9965 | Train acc: 50.60% | Val loss: 0.9928 | Val acc: 53.93% | LR: 0.000014
Epoch: 033 | Train loss: 0.9977 | Train acc: 50.38% | Val loss: 0.9926 | Val acc: 54.01% | LR: 0.000014
Epoch: 034 | Train loss: 0.9959 | Train acc: 50.91% | Val loss: 0.9931 | Val acc: 53.93% | LR: 0.000014
Epoch: 035 | Train loss: 0.9902 | Train acc: 51.44% | Val loss: 0.9929 | Val acc: 54.03% | LR: 0.000014
Epoch: 036 | Train loss: 0.9945 | Train acc: 50.82% | Val loss: 0.9932 | Val acc: 53.95% | LR: 0.000014
Epoch: 037 | Train loss: 0.9953 | Train acc: 50.90% | Val loss: 0.9926 | Val acc: 54.01% | LR: 0.000014
Epoch: 038 | Train loss: 0.9986 | Train acc: 50.38% | Val loss: 0.9936 | Val acc: 53.97% | LR: 0.000013
Epoch: 039 | Train loss: 0.9937 | Train acc: 51.08% | Val loss: 0.9927 | Val acc: 54.01% | LR: 0.000013
Epoch: 040 | Train loss: 0.9994 | Train acc: 50.11% | Val loss: 0.9925 | Val acc: 54.01% | LR: 0.000013
Epoch: 041 | Train loss: 0.9990 | Train acc: 50.36% | Val loss: 0.9926 | Val acc: 54.09% | LR: 0.000013
Epoch: 042 | Train loss: 1.0004 | Train acc: 50.20% | Val loss: 0.9989 | Val acc: 54.07% | LR: 0.000013
Epoch: 043 | Train loss: 0.9975 | Train acc: 50.47% | Val loss: 0.9925 | Val acc: 54.05% | LR: 0.000013
Epoch: 044 | Train loss: 0.9983 | Train acc: 50.45% | Val loss: 0.9920 | Val acc: 54.11% | LR: 0.000013
Epoch: 045 | Train loss: 0.9957 | Train acc: 50.64% | Val loss: 0.9920 | Val acc: 54.05% | LR: 0.000013
Epoch: 046 | Train loss: 0.9957 | Train acc: 50.64% | Val loss: 0.9926 | Val acc: 53.97% | LR: 0.000013
Epoch: 047 | Train loss: 0.9940 | Train acc: 50.91% | Val loss: 0.9926 | Val acc: 53.99% | LR: 0.000012
Epoch: 048 | Train loss: 0.9980 | Train acc: 50.37% | Val loss: 0.9923 | Val acc: 53.99% | LR: 0.000012
Epoch: 049 | Train loss: 0.9975 | Train acc: 50.20% | Val loss: 0.9915 | Val acc: 54.11% | LR: 0.000012
Epoch: 050 | Train loss: 0.9990 | Train acc: 50.37% | Val loss: 0.9940 | Val acc: 54.06% | LR: 0.000012
Epoch: 051 | Train loss: 0.9928 | Train acc: 50.88% | Val loss: 0.9924 | Val acc: 53.99% | LR: 0.000012
Epoch: 052 | Train loss: 0.9966 | Train acc: 50.55% | Val loss: 0.9919 | Val acc: 54.06% | LR: 0.000012
Epoch: 053 | Train loss: 0.9989 | Train acc: 50.20% | Val loss: 0.9925 | Val acc: 53.91% | LR: 0.000012
Epoch: 054 | Train loss: 0.9976 | Train acc: 50.38% | Val loss: 0.9922 | Val acc: 54.07% | LR: 0.000011
Epoch: 055 | Train loss: 0.9977 | Train acc: 50.45% | Val loss: 0.9926 | Val acc: 53.93% | LR: 0.000011
Epoch: 056 | Train loss: 0.9949 | Train acc: 50.55% | Val loss: 0.9921 | Val acc: 54.01% | LR: 0.000011

[I 2025-09-23 17:38:40,966] Trial 74 finished with value: 0.5403124213218689 and parameters: {'lr': 1.583297453738307e-05, 'hidden_size': 75, 'dropout': 0.32391212848900736, 'weight_decay': 5.851967916202717e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9978 | Train acc: 50.41% | Val loss: 0.9997 | Val acc: 49.55% | LR: 0.000017
Epoch: 001 | Train loss: 0.9959 | Train acc: 50.36% | Val loss: 0.9998 | Val acc: 49.78% | LR: 0.000017
Epoch: 002 | Train loss: 0.9938 | Train acc: 50.76% | Val loss: 0.9997 | Val acc: 49.64% | LR: 0.000017
Epoch: 003 | Train loss: 0.9963 | Train acc: 50.58% | Val loss: 0.9997 | Val acc: 49.40% | LR: 0.000017
Epoch: 004 | Train loss: 0.9940 | Train acc: 50.70% | Val loss: 0.9997 | Val acc: 49.48% | LR: 0.000017
Epoch: 005 | Train loss: 0.9957 | Train acc: 51.00% | Val loss: 0.9996 | Val acc: 49.55% | LR: 0.000017
Epoch: 006 | Train loss: 0.9938 | Train acc: 50.75% | Val loss: 0.9995 | Val acc: 49.94% | LR: 0.000017
Epoch: 007 | Train loss: 0.9960 | Train acc: 50.84% | Val loss: 0.9994 | Val acc: 49.74% | LR: 0.000017
Epoch: 008 | Train loss: 0.9956 | Train acc: 50.89% | Val loss: 0.9992 | Val acc: 49.84% | LR: 0.000017
Epoch: 009 | Train loss: 0.9936 | Train acc: 50.14% | Val loss: 0.9991 | Val acc: 50.08% | LR: 0.000017
Epoch: 010 | Train loss: 0.9956 | Train acc: 50.96% | Val loss: 0.9990 | Val acc: 50.08% | LR: 0.000017
Epoch: 011 | Train loss: 0.9963 | Train acc: 50.51% | Val loss: 0.9988 | Val acc: 50.42% | LR: 0.000017
Epoch: 012 | Train loss: 0.9943 | Train acc: 50.99% | Val loss: 0.9987 | Val acc: 50.49% | LR: 0.000017
Epoch: 013 | Train loss: 0.9962 | Train acc: 50.65% | Val loss: 0.9984 | Val acc: 50.57% | LR: 0.000017
Epoch: 014 | Train loss: 0.9937 | Train acc: 50.88% | Val loss: 0.9983 | Val acc: 50.66% | LR: 0.000017
Epoch: 015 | Train loss: 0.9946 | Train acc: 50.72% | Val loss: 0.9983 | Val acc: 50.62% | LR: 0.000017
Epoch: 016 | Train loss: 0.9933 | Train acc: 50.76% | Val loss: 0.9982 | Val acc: 50.86% | LR: 0.000017
Epoch: 017 | Train loss: 0.9954 | Train acc: 50.86% | Val loss: 0.9981 | Val acc: 50.93% | LR: 0.000017
Epoch: 018 | Train loss: 0.9928 | Train acc: 50.76% | Val loss: 0.9981 | Val acc: 50.95% | LR: 0.000016
Epoch: 019 | Train loss: 0.9916 | Train acc: 51.36% | Val loss: 0.9980 | Val acc: 50.82% | LR: 0.000016
Epoch: 020 | Train loss: 0.9927 | Train acc: 50.65% | Val loss: 0.9979 | Val acc: 50.82% | LR: 0.000016
Epoch: 021 | Train loss: 0.9921 | Train acc: 51.16% | Val loss: 0.9978 | Val acc: 50.86% | LR: 0.000016
Epoch: 022 | Train loss: 0.9924 | Train acc: 50.80% | Val loss: 0.9977 | Val acc: 50.90% | LR: 0.000016
Epoch: 023 | Train loss: 0.9925 | Train acc: 51.06% | Val loss: 0.9976 | Val acc: 50.87% | LR: 0.000016
Epoch: 024 | Train loss: 0.9928 | Train acc: 51.07% | Val loss: 0.9975 | Val acc: 50.89% | LR: 0.000016
Epoch: 025 | Train loss: 0.9933 | Train acc: 50.80% | Val loss: 0.9973 | Val acc: 51.02% | LR: 0.000016
Epoch: 026 | Train loss: 0.9902 | Train acc: 50.99% | Val loss: 0.9970 | Val acc: 51.14% | LR: 0.000016
Epoch: 027 | Train loss: 0.9944 | Train acc: 50.92% | Val loss: 0.9968 | Val acc: 51.31% | LR: 0.000016
Epoch: 028 | Train loss: 0.9928 | Train acc: 50.39% | Val loss: 0.9967 | Val acc: 51.29% | LR: 0.000016
Epoch: 029 | Train loss: 0.9924 | Train acc: 50.82% | Val loss: 0.9965 | Val acc: 51.27% | LR: 0.000016
Epoch: 030 | Train loss: 0.9932 | Train acc: 50.53% | Val loss: 0.9965 | Val acc: 51.27% | LR: 0.000015
Epoch: 031 | Train loss: 0.9935 | Train acc: 50.91% | Val loss: 0.9964 | Val acc: 51.29% | LR: 0.000015
Epoch: 032 | Train loss: 0.9933 | Train acc: 50.82% | Val loss: 0.9963 | Val acc: 51.32% | LR: 0.000015
Epoch: 033 | Train loss: 0.9953 | Train acc: 51.11% | Val loss: 0.9962 | Val acc: 51.34% | LR: 0.000015
Epoch: 034 | Train loss: 0.9912 | Train acc: 50.93% | Val loss: 0.9960 | Val acc: 51.36% | LR: 0.000015
Epoch: 035 | Train loss: 0.9908 | Train acc: 50.99% | Val loss: 0.9958 | Val acc: 51.47% | LR: 0.000015
Epoch: 036 | Train loss: 0.9902 | Train acc: 50.84% | Val loss: 0.9956 | Val acc: 51.45% | LR: 0.000015
Epoch: 037 | Train loss: 0.9894 | Train acc: 51.10% | Val loss: 0.9954 | Val acc: 51.45% | LR: 0.000015
Epoch: 038 | Train loss: 0.9944 | Train acc: 50.65% | Val loss: 0.9952 | Val acc: 51.45% | LR: 0.000015
Epoch: 039 | Train loss: 0.9928 | Train acc: 50.56% | Val loss: 0.9951 | Val acc: 51.47% | LR: 0.000014
Epoch: 040 | Train loss: 0.9912 | Train acc: 51.28% | Val loss: 0.9950 | Val acc: 51.43% | LR: 0.000014
Epoch: 041 | Train loss: 0.9952 | Train acc: 50.76% | Val loss: 0.9945 | Val acc: 51.73% | LR: 0.000014
Epoch: 042 | Train loss: 0.9896 | Train acc: 51.22% | Val loss: 0.9943 | Val acc: 51.71% | LR: 0.000014
Epoch: 043 | Train loss: 0.9898 | Train acc: 50.90% | Val loss: 0.9942 | Val acc: 51.73% | LR: 0.000014
Epoch: 044 | Train loss: 0.9944 | Train acc: 50.86% | Val loss: 0.9940 | Val acc: 51.63% | LR: 0.000014
Epoch: 045 | Train loss: 0.9963 | Train acc: 50.67% | Val loss: 0.9938 | Val acc: 51.63% | LR: 0.000014
Epoch: 046 | Train loss: 0.9943 | Train acc: 50.93% | Val loss: 0.9935 | Val acc: 51.65% | LR: 0.000014
Epoch: 047 | Train loss: 0.9949 | Train acc: 50.85% | Val loss: 0.9934 | Val acc: 51.65% | LR: 0.000013
Epoch: 048 | Train loss: 0.9921 | Train acc: 51.39% | Val loss: 0.9931 | Val acc: 51.76% | LR: 0.000013
Epoch: 049 | Train loss: 0.9915 | Train acc: 50.67% | Val loss: 0.9930 | Val acc: 51.76% | LR: 0.000013
Epoch: 050 | Train loss: 0.9891 | Train acc: 51.21% | Val loss: 0.9928 | Val acc: 51.70% | LR: 0.000013
Epoch: 051 | Train loss: 0.9894 | Train acc: 50.94% | Val loss: 0.9926 | Val acc: 51.72% | LR: 0.000013
Epoch: 052 | Train loss: 0.9912 | Train acc: 51.30% | Val loss: 0.9925 | Val acc: 51.63% | LR: 0.000013
Epoch: 053 | Train loss: 0.9951 | Train acc: 50.15% | Val loss: 0.9924 | Val acc: 51.63% | LR: 0.000012
Epoch: 054 | Train loss: 0.9931 | Train acc: 51.04% | Val loss: 0.9922 | Val acc: 51.61% | LR: 0.000012
Epoch: 055 | Train loss: 0.9888 | Train acc: 51.57% | Val loss: 0.9919 | Val acc: 51.72% | LR: 0.000012
Epoch: 056 | Train loss: 0.9890 | Train acc: 51.14% | Val loss: 0.9916 | Val acc: 51.74% | LR: 0.000012
Epoch: 057 | Train loss: 0.9909 | Train acc: 51.76% | Val loss: 0.9915 | Val acc: 51.74% | LR: 0.000012
Epoch: 058 | Train loss: 0.9890 | Train acc: 51.24% | Val loss: 0.9911 | Val acc: 51.82% | LR: 0.000012
Epoch: 059 | Train loss: 0.9928 | Train acc: 50.88% | Val loss: 0.9910 | Val acc: 51.82% | LR: 0.000012
Epoch: 060 | Train loss: 0.9921 | Train acc: 51.05% | Val loss: 0.9909 | Val acc: 51.78% | LR: 0.000011
Epoch: 061 | Train loss: 0.9916 | Train acc: 51.15% | Val loss: 0.9907 | Val acc: 51.80% | LR: 0.000011
Epoch: 062 | Train loss: 0.9918 | Train acc: 50.79% | Val loss: 0.9905 | Val acc: 51.80% | LR: 0.000011
Epoch: 063 | Train loss: 0.9902 | Train acc: 50.88% | Val loss: 0.9903 | Val acc: 51.76% | LR: 0.000011
Epoch: 064 | Train loss: 0.9936 | Train acc: 50.80% | Val loss: 0.9901 | Val acc: 51.76% | LR: 0.000011
Epoch: 065 | Train loss: 0.9895 | Train acc: 51.32% | Val loss: 0.9898 | Val acc: 51.78% | LR: 0.000011
Epoch: 066 | Train loss: 0.9923 | Train acc: 50.87% | Val loss: 0.9897 | Val acc: 51.76% | LR: 0.000010
Epoch: 067 | Train loss: 0.9881 | Train acc: 51.06% | Val loss: 0.9895 | Val acc: 51.70% | LR: 0.000010
Epoch: 068 | Train loss: 0.9912 | Train acc: 51.16% | Val loss: 0.9894 | Val acc: 51.71% | LR: 0.000010
Epoch: 069 | Train loss: 0.9901 | Train acc: 51.64% | Val loss: 0.9892 | Val acc: 51.72% | LR: 0.000010
Epoch: 070 | Train loss: 0.9894 | Train acc: 51.05% | Val loss: 0.9890 | Val acc: 51.76% | LR: 0.000010
Epoch: 071 | Train loss: 0.9905 | Train acc: 51.14% | Val loss: 0.9888 | Val acc: 51.68% | LR: 0.000010
Epoch: 072 | Train loss: 0.9910 | Train acc: 51.14% | Val loss: 0.9887 | Val acc: 51.68% | LR: 0.000009
Epoch: 073 | Train loss: 0.9893 | Train acc: 51.63% | Val loss: 0.9885 | Val acc: 51.68% | LR: 0.000009
Epoch: 074 | Train loss: 0.9908 | Train acc: 51.11% | Val loss: 0.9885 | Val acc: 51.68% | LR: 0.000009
Epoch: 075 | Train loss: 0.9903 | Train acc: 51.17% | Val loss: 0.9883 | Val acc: 51.66% | LR: 0.000009
Epoch: 076 | Train loss: 0.9886 | Train acc: 51.13% | Val loss: 0.9881 | Val acc: 51.64% | LR: 0.000009
Epoch: 077 | Train loss: 0.9905 | Train acc: 50.64% | Val loss: 0.9880 | Val acc: 51.64% | LR: 0.000009
Epoch: 078 | Train loss: 0.9871 | Train acc: 51.48% | Val loss: 0.9878 | Val acc: 51.60% | LR: 0.000008
Epoch: 079 | Train loss: 0.9872 | Train acc: 51.48% | Val loss: 0.9876 | Val acc: 51.66% | LR: 0.000008
Epoch: 080 | Train loss: 0.9906 | Train acc: 50.64% | Val loss: 0.9875 | Val acc: 51.62% | LR: 0.000008
Epoch: 081 | Train loss: 0.9898 | Train acc: 50.84% | Val loss: 0.9873 | Val acc: 51.58% | LR: 0.000008
Epoch: 082 | Train loss: 0.9910 | Train acc: 50.59% | Val loss: 0.9872 | Val acc: 51.58% | LR: 0.000008
Epoch: 083 | Train loss: 0.9877 | Train acc: 50.93% | Val loss: 0.9871 | Val acc: 51.62% | LR: 0.000008
Epoch: 084 | Train loss: 0.9875 | Train acc: 50.82% | Val loss: 0.9870 | Val acc: 51.64% | LR: 0.000007
Epoch: 085 | Train loss: 0.9900 | Train acc: 51.19% | Val loss: 0.9870 | Val acc: 51.60% | LR: 0.000007
Epoch: 086 | Train loss: 0.9881 | Train acc: 50.93% | Val loss: 0.9870 | Val acc: 51.58% | LR: 0.000007
Epoch: 087 | Train loss: 0.9881 | Train acc: 51.03% | Val loss: 0.9868 | Val acc: 51.52% | LR: 0.000007
Epoch: 088 | Train loss: 0.9893 | Train acc: 50.91% | Val loss: 0.9867 | Val acc: 51.48% | LR: 0.000007
Epoch: 089 | Train loss: 0.9896 | Train acc: 50.99% | Val loss: 0.9865 | Val acc: 51.50% | LR: 0.000007
Epoch: 090 | Train loss: 0.9876 | Train acc: 50.67% | Val loss: 0.9876 | Val acc: 51.46% | LR: 0.000006
Epoch: 091 | Train loss: 0.9848 | Train acc: 51.74% | Val loss: 0.9863 | Val acc: 51.54% | LR: 0.000006
Epoch: 092 | Train loss: 0.9883 | Train acc: 51.03% | Val loss: 0.9861 | Val acc: 51.54% | LR: 0.000006
Epoch: 093 | Train loss: 0.9913 | Train acc: 50.76% | Val loss: 0.9860 | Val acc: 51.54% | LR: 0.000006
Epoch: 094 | Train loss: 0.9918 | Train acc: 50.76% | Val loss: 0.9861 | Val acc: 51.48% | LR: 0.000006
Epoch: 095 | Train loss: 0.9884 | Train acc: 50.94% | Val loss: 0.9860 | Val acc: 51.54% | LR: 0.000006
Epoch: 096 | Train loss: 0.9896 | Train acc: 51.02% | Val loss: 0.9865 | Val acc: 51.54% | LR: 0.000005
Epoch: 097 | Train loss: 0.9918 | Train acc: 50.50% | Val loss: 0.9860 | Val acc: 51.42% | LR: 0.000005
Epoch: 098 | Train loss: 0.9878 | Train acc: 51.29% | Val loss: 0.9858 | Val acc: 51.48% | LR: 0.000005
Epoch: 099 | Train loss: 0.9860 | Train acc: 51.38% | Val loss: 0.9858 | Val acc: 51.48% | LR: 0.000005
Epoch: 100 | Train loss: 0.9910 | Train acc: 50.78% | Val loss: 0.9858 | Val acc: 51.48% | LR: 0.000005
Epoch: 101 | Train loss: 0.9840 | Train acc: 51.49% | Val loss: 0.9855 | Val acc: 51.48% | LR: 0.000005
Epoch: 102 | Train loss: 0.9842 | Train acc: 51.21% | Val loss: 0.9856 | Val acc: 51.48% | LR: 0.000005
Epoch: 103 | Train loss: 0.9882 | Train acc: 51.00% | Val loss: 0.9855 | Val acc: 51.46% | LR: 0.000004
Epoch: 104 | Train loss: 0.9847 | Train acc: 51.75% | Val loss: 0.9853 | Val acc: 51.48% | LR: 0.000004
Epoch: 105 | Train loss: 0.9872 | Train acc: 51.30% | Val loss: 0.9853 | Val acc: 51.48% | LR: 0.000004
Epoch: 106 | Train loss: 0.9873 | Train acc: 51.65% | Val loss: 0.9852 | Val acc: 51.48% | LR: 0.000004
Epoch: 107 | Train loss: 0.9895 | Train acc: 51.03% | Val loss: 0.9851 | Val acc: 51.48% | LR: 0.000004

[I 2025-09-23 17:40:14,226] Trial 75 finished with value: 0.5147909164428711 and parameters: {'lr': 1.7124396505243834e-05, 'hidden_size': 77, 'dropout': 0.32462072632184635, 'weight_decay': 5.582127554433846e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9956 | Train acc: 50.68% | Val loss: 0.9921 | Val acc: 54.31% | LR: 0.000015
Epoch: 001 | Train loss: 0.9984 | Train acc: 50.25% | Val loss: 1.0060 | Val acc: 54.40% | LR: 0.000015
Epoch: 002 | Train loss: 0.9956 | Train acc: 50.43% | Val loss: 0.9922 | Val acc: 54.28% | LR: 0.000015
Epoch: 003 | Train loss: 0.9969 | Train acc: 50.51% | Val loss: 0.9983 | Val acc: 54.44% | LR: 0.000015
Epoch: 004 | Train loss: 0.9971 | Train acc: 50.16% | Val loss: 0.9919 | Val acc: 54.32% | LR: 0.000015
Epoch: 005 | Train loss: 0.9919 | Train acc: 50.94% | Val loss: 0.9907 | Val acc: 54.32% | LR: 0.000015
Epoch: 006 | Train loss: 0.9988 | Train acc: 49.96% | Val loss: 0.9906 | Val acc: 54.21% | LR: 0.000015
Epoch: 007 | Train loss: 0.9936 | Train acc: 50.65% | Val loss: 0.9900 | Val acc: 54.21% | LR: 0.000015
Epoch: 008 | Train loss: 0.9971 | Train acc: 50.22% | Val loss: 0.9900 | Val acc: 54.29% | LR: 0.000015
Epoch: 009 | Train loss: 0.9976 | Train acc: 50.08% | Val loss: 0.9896 | Val acc: 54.45% | LR: 0.000015
Epoch: 010 | Train loss: 0.9916 | Train acc: 50.91% | Val loss: 0.9901 | Val acc: 54.57% | LR: 0.000015
Epoch: 011 | Train loss: 0.9931 | Train acc: 50.66% | Val loss: 0.9902 | Val acc: 54.39% | LR: 0.000015
Epoch: 012 | Train loss: 0.9919 | Train acc: 50.85% | Val loss: 0.9903 | Val acc: 54.62% | LR: 0.000015
Epoch: 013 | Train loss: 0.9950 | Train acc: 50.35% | Val loss: 0.9900 | Val acc: 54.48% | LR: 0.000015
Epoch: 014 | Train loss: 0.9915 | Train acc: 50.83% | Val loss: 0.9887 | Val acc: 54.51% | LR: 0.000015
Epoch: 015 | Train loss: 0.9895 | Train acc: 50.83% | Val loss: 0.9902 | Val acc: 54.55% | LR: 0.000014
Epoch: 016 | Train loss: 0.9892 | Train acc: 50.91% | Val loss: 0.9890 | Val acc: 54.70% | LR: 0.000014
Epoch: 017 | Train loss: 0.9925 | Train acc: 50.56% | Val loss: 0.9888 | Val acc: 54.60% | LR: 0.000014
Epoch: 018 | Train loss: 0.9849 | Train acc: 50.90% | Val loss: 0.9887 | Val acc: 54.68% | LR: 0.000014
Epoch: 019 | Train loss: 0.9912 | Train acc: 50.93% | Val loss: 0.9887 | Val acc: 54.70% | LR: 0.000014
Epoch: 020 | Train loss: 0.9921 | Train acc: 50.66% | Val loss: 0.9883 | Val acc: 54.56% | LR: 0.000014
Epoch: 021 | Train loss: 0.9884 | Train acc: 50.94% | Val loss: 0.9889 | Val acc: 54.64% | LR: 0.000014
Epoch: 022 | Train loss: 0.9923 | Train acc: 50.66% | Val loss: 0.9901 | Val acc: 54.62% | LR: 0.000014
Epoch: 023 | Train loss: 0.9941 | Train acc: 50.59% | Val loss: 0.9863 | Val acc: 54.50% | LR: 0.000014
Epoch: 024 | Train loss: 0.9895 | Train acc: 50.57% | Val loss: 0.9862 | Val acc: 54.62% | LR: 0.000014
Epoch: 025 | Train loss: 0.9887 | Train acc: 50.76% | Val loss: 0.9861 | Val acc: 54.65% | LR: 0.000014
Epoch: 026 | Train loss: 0.9914 | Train acc: 50.50% | Val loss: 0.9859 | Val acc: 54.63% | LR: 0.000014
Epoch: 027 | Train loss: 0.9919 | Train acc: 50.40% | Val loss: 0.9861 | Val acc: 54.62% | LR: 0.000014
Epoch: 028 | Train loss: 0.9925 | Train acc: 50.26% | Val loss: 0.9860 | Val acc: 54.60% | LR: 0.000014
Epoch: 029 | Train loss: 0.9948 | Train acc: 50.25% | Val loss: 0.9863 | Val acc: 54.58% | LR: 0.000014
Epoch: 030 | Train loss: 0.9884 | Train acc: 50.97% | Val loss: 0.9897 | Val acc: 54.49% | LR: 0.000013
Epoch: 031 | Train loss: 0.9860 | Train acc: 51.24% | Val loss: 0.9862 | Val acc: 54.39% | LR: 0.000013
Epoch: 032 | Train loss: 0.9933 | Train acc: 50.63% | Val loss: 0.9856 | Val acc: 54.47% | LR: 0.000013
Epoch: 033 | Train loss: 0.9886 | Train acc: 50.75% | Val loss: 0.9856 | Val acc: 54.46% | LR: 0.000013
Epoch: 034 | Train loss: 0.9983 | Train acc: 50.95% | Val loss: 0.9855 | Val acc: 54.41% | LR: 0.000013
Epoch: 035 | Train loss: 0.9932 | Train acc: 50.59% | Val loss: 0.9851 | Val acc: 54.33% | LR: 0.000013
Epoch: 036 | Train loss: 0.9877 | Train acc: 51.14% | Val loss: 0.9848 | Val acc: 54.31% | LR: 0.000013
Epoch: 037 | Train loss: 0.9934 | Train acc: 50.42% | Val loss: 0.9846 | Val acc: 54.26% | LR: 0.000013
Epoch: 038 | Train loss: 0.9930 | Train acc: 50.45% | Val loss: 0.9844 | Val acc: 54.28% | LR: 0.000013
Epoch: 039 | Train loss: 0.9894 | Train acc: 51.06% | Val loss: 0.9843 | Val acc: 54.26% | LR: 0.000013
Epoch: 040 | Train loss: 0.9868 | Train acc: 51.24% | Val loss: 0.9841 | Val acc: 54.32% | LR: 0.000012
Epoch: 041 | Train loss: 0.9973 | Train acc: 50.27% | Val loss: 0.9840 | Val acc: 54.34% | LR: 0.000012
Epoch: 042 | Train loss: 0.9913 | Train acc: 50.88% | Val loss: 0.9839 | Val acc: 54.30% | LR: 0.000012
Epoch: 043 | Train loss: 0.9935 | Train acc: 50.53% | Val loss: 0.9838 | Val acc: 54.36% | LR: 0.000012
Epoch: 044 | Train loss: 0.9873 | Train acc: 51.09% | Val loss: 0.9836 | Val acc: 54.24% | LR: 0.000012
Epoch: 045 | Train loss: 0.9872 | Train acc: 51.10% | Val loss: 0.9833 | Val acc: 54.28% | LR: 0.000012
Epoch: 046 | Train loss: 0.9984 | Train acc: 50.14% | Val loss: 0.9831 | Val acc: 54.26% | LR: 0.000012
Epoch: 047 | Train loss: 0.9962 | Train acc: 50.32% | Val loss: 0.9830 | Val acc: 54.24% | LR: 0.000012
Epoch: 048 | Train loss: 0.9900 | Train acc: 50.77% | Val loss: 0.9829 | Val acc: 54.24% | LR: 0.000012
Epoch: 049 | Train loss: 0.9918 | Train acc: 50.68% | Val loss: 0.9827 | Val acc: 54.24% | LR: 0.000011
Epoch: 050 | Train loss: 0.9935 | Train acc: 50.59% | Val loss: 0.9825 | Val acc: 54.26% | LR: 0.000011
Epoch: 051 | Train loss: 0.9904 | Train acc: 50.96% | Val loss: 0.9821 | Val acc: 54.30% | LR: 0.000011
Epoch: 052 | Train loss: 0.9894 | Train acc: 50.96% | Val loss: 0.9821 | Val acc: 54.26% | LR: 0.000011
Epoch: 053 | Train loss: 0.9923 | Train acc: 50.69% | Val loss: 0.9819 | Val acc: 54.26% | LR: 0.000011
Epoch: 054 | Train loss: 0.9912 | Train acc: 50.77% | Val loss: 0.9818 | Val acc: 54.30% | LR: 0.000011
Epoch: 055 | Train loss: 0.9957 | Train acc: 50.24% | Val loss: 0.9817 | Val acc: 54.25% | LR: 0.000011
Epoch: 056 | Train loss: 0.9938 | Train acc: 50.33% | Val loss: 0.9816 | Val acc: 54.12% | LR: 0.000010
Epoch: 057 | Train loss: 0.9886 | Train acc: 50.95% | Val loss: 0.9815 | Val acc: 54.12% | LR: 0.000010
Epoch: 058 | Train loss: 0.9847 | Train acc: 51.21% | Val loss: 0.9814 | Val acc: 53.99% | LR: 0.000010
Epoch: 059 | Train loss: 0.9901 | Train acc: 50.77% | Val loss: 0.9814 | Val acc: 53.93% | LR: 0.000010
Epoch: 060 | Train loss: 0.9881 | Train acc: 51.05% | Val loss: 0.9813 | Val acc: 53.95% | LR: 0.000010
Epoch: 061 | Train loss: 0.9892 | Train acc: 50.86% | Val loss: 0.9812 | Val acc: 53.91% | LR: 0.000010
Epoch: 062 | Train loss: 0.9884 | Train acc: 50.96% | Val loss: 0.9811 | Val acc: 53.91% | LR: 0.000010
Epoch: 063 | Train loss: 0.9893 | Train acc: 50.87% | Val loss: 0.9811 | Val acc: 53.95% | LR: 0.000010
Epoch: 064 | Train loss: 0.9856 | Train acc: 51.31% | Val loss: 0.9811 | Val acc: 53.87% | LR: 0.000009
Epoch: 065 | Train loss: 0.9862 | Train acc: 51.13% | Val loss: 0.9810 | Val acc: 53.87% | LR: 0.000009

[I 2025-09-23 17:41:10,697] Trial 76 finished with value: 0.5377542614936829 and parameters: {'lr': 1.4849349610010558e-05, 'hidden_size': 86, 'dropout': 0.2835750312119191, 'weight_decay': 1.5062021957911088e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0004 | Train acc: 50.01% | Val loss: 1.0053 | Val acc: 46.84% | LR: 0.000012
Epoch: 001 | Train loss: 1.0022 | Train acc: 50.02% | Val loss: 1.0039 | Val acc: 46.22% | LR: 0.000012
Epoch: 002 | Train loss: 0.9999 | Train acc: 50.41% | Val loss: 1.0042 | Val acc: 46.30% | LR: 0.000012
Epoch: 003 | Train loss: 0.9982 | Train acc: 50.62% | Val loss: 1.0051 | Val acc: 46.34% | LR: 0.000012
Epoch: 004 | Train loss: 0.9995 | Train acc: 50.17% | Val loss: 1.0054 | Val acc: 46.31% | LR: 0.000012
Epoch: 005 | Train loss: 0.9998 | Train acc: 50.09% | Val loss: 1.0137 | Val acc: 46.39% | LR: 0.000012
Epoch: 006 | Train loss: 0.9987 | Train acc: 50.44% | Val loss: 1.0037 | Val acc: 46.19% | LR: 0.000012
Epoch: 007 | Train loss: 0.9994 | Train acc: 50.09% | Val loss: 1.0120 | Val acc: 46.23% | LR: 0.000012
Epoch: 008 | Train loss: 0.9987 | Train acc: 50.36% | Val loss: 1.0075 | Val acc: 46.39% | LR: 0.000012
Epoch: 009 | Train loss: 0.9993 | Train acc: 50.17% | Val loss: 1.0098 | Val acc: 46.26% | LR: 0.000012
Epoch: 010 | Train loss: 0.9990 | Train acc: 50.14% | Val loss: 1.0074 | Val acc: 46.39% | LR: 0.000012
Epoch: 011 | Train loss: 1.0000 | Train acc: 50.21% | Val loss: 1.0124 | Val acc: 46.22% | LR: 0.000012
Epoch: 012 | Train loss: 0.9992 | Train acc: 50.08% | Val loss: 1.0286 | Val acc: 46.49% | LR: 0.000012
Epoch: 013 | Train loss: 1.0011 | Train acc: 50.14% | Val loss: 1.0075 | Val acc: 46.16% | LR: 0.000012
Epoch: 014 | Train loss: 0.9994 | Train acc: 50.13% | Val loss: 1.0045 | Val acc: 46.15% | LR: 0.000012
Epoch: 015 | Train loss: 0.9988 | Train acc: 50.13% | Val loss: 1.0056 | Val acc: 46.33% | LR: 0.000011
Epoch: 016 | Train loss: 0.9985 | Train acc: 50.24% | Val loss: 1.0066 | Val acc: 46.38% | LR: 0.000011
Epoch: 017 | Train loss: 0.9992 | Train acc: 50.29% | Val loss: 1.0048 | Val acc: 46.30% | LR: 0.000011
Epoch: 018 | Train loss: 0.9986 | Train acc: 50.21% | Val loss: 1.0061 | Val acc: 46.32% | LR: 0.000011
Epoch: 019 | Train loss: 0.9977 | Train acc: 50.34% | Val loss: 1.0045 | Val acc: 46.12% | LR: 0.000011
Epoch: 020 | Train loss: 0.9985 | Train acc: 50.15% | Val loss: 1.0028 | Val acc: 46.25% | LR: 0.000011
Epoch: 021 | Train loss: 0.9982 | Train acc: 50.53% | Val loss: 1.0062 | Val acc: 46.00% | LR: 0.000011
Epoch: 022 | Train loss: 0.9982 | Train acc: 50.35% | Val loss: 1.0045 | Val acc: 46.13% | LR: 0.000011
Epoch: 023 | Train loss: 0.9970 | Train acc: 50.78% | Val loss: 1.0035 | Val acc: 46.10% | LR: 0.000011
Epoch: 024 | Train loss: 1.0008 | Train acc: 50.21% | Val loss: 1.0040 | Val acc: 46.05% | LR: 0.000011
Epoch: 025 | Train loss: 0.9971 | Train acc: 50.70% | Val loss: 1.0028 | Val acc: 46.13% | LR: 0.000011
Epoch: 026 | Train loss: 0.9969 | Train acc: 50.65% | Val loss: 1.0044 | Val acc: 46.13% | LR: 0.000011
Epoch: 027 | Train loss: 0.9961 | Train acc: 50.87% | Val loss: 1.0054 | Val acc: 46.17% | LR: 0.000011
Epoch: 028 | Train loss: 0.9985 | Train acc: 50.09% | Val loss: 1.0046 | Val acc: 45.89% | LR: 0.000011
Epoch: 029 | Train loss: 0.9969 | Train acc: 50.52% | Val loss: 1.0040 | Val acc: 46.02% | LR: 0.000011
Epoch: 030 | Train loss: 1.0008 | Train acc: 49.81% | Val loss: 1.0155 | Val acc: 46.13% | LR: 0.000011
Epoch: 031 | Train loss: 0.9958 | Train acc: 51.19% | Val loss: 1.0041 | Val acc: 45.81% | LR: 0.000011
Epoch: 032 | Train loss: 0.9988 | Train acc: 50.48% | Val loss: 1.0144 | Val acc: 45.93% | LR: 0.000011
Epoch: 033 | Train loss: 0.9976 | Train acc: 50.40% | Val loss: 1.0040 | Val acc: 45.87% | LR: 0.000010
Epoch: 034 | Train loss: 1.0010 | Train acc: 49.83% | Val loss: 1.0039 | Val acc: 45.93% | LR: 0.000010
Epoch: 035 | Train loss: 0.9956 | Train acc: 51.07% | Val loss: 1.0050 | Val acc: 45.50% | LR: 0.000010
Epoch: 036 | Train loss: 0.9966 | Train acc: 50.81% | Val loss: 1.0046 | Val acc: 45.54% | LR: 0.000010
Epoch: 037 | Train loss: 0.9976 | Train acc: 50.53% | Val loss: 1.0048 | Val acc: 45.64% | LR: 0.000010
Epoch: 038 | Train loss: 0.9962 | Train acc: 50.79% | Val loss: 1.0041 | Val acc: 45.66% | LR: 0.000010
Epoch: 039 | Train loss: 0.9963 | Train acc: 50.88% | Val loss: 1.0040 | Val acc: 45.76% | LR: 0.000010
Epoch: 040 | Train loss: 0.9972 | Train acc: 50.54% | Val loss: 1.0039 | Val acc: 45.79% | LR: 0.000010
Epoch: 041 | Train loss: 0.9956 | Train acc: 50.98% | Val loss: 1.0043 | Val acc: 45.62% | LR: 0.000010
Epoch: 042 | Train loss: 0.9992 | Train acc: 50.10% | Val loss: 1.0042 | Val acc: 45.71% | LR: 0.000010
Epoch: 043 | Train loss: 0.9973 | Train acc: 50.61% | Val loss: 1.0047 | Val acc: 45.73% | LR: 0.000010
Epoch: 044 | Train loss: 0.9971 | Train acc: 50.61% | Val loss: 1.0041 | Val acc: 45.68% | LR: 0.000010
Epoch: 045 | Train loss: 0.9994 | Train acc: 50.08% | Val loss: 1.0042 | Val acc: 45.71% | LR: 0.000009
Epoch: 046 | Train loss: 0.9971 | Train acc: 50.43% | Val loss: 1.0041 | Val acc: 45.85% | LR: 0.000009
Epoch: 047 | Train loss: 0.9945 | Train acc: 50.86% | Val loss: 1.0041 | Val acc: 45.81% | LR: 0.000009
Epoch: 048 | Train loss: 0.9971 | Train acc: 50.61% | Val loss: 1.0040 | Val acc: 45.81% | LR: 0.000009
Epoch: 049 | Train loss: 0.9975 | Train acc: 50.43% | Val loss: 1.0060 | Val acc: 45.65% | LR: 0.000009

[I 2025-09-23 17:41:56,973] Trial 77 finished with value: 0.45852851271629336 and parameters: {'lr': 1.1763958763286879e-05, 'hidden_size': 89, 'dropout': 0.25660044618103856, 'weight_decay': 6.932562635030951e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0001 | Train acc: 50.27% | Val loss: 0.9945 | Val acc: 53.85% | LR: 0.000015
Epoch: 001 | Train loss: 1.0006 | Train acc: 50.09% | Val loss: 0.9973 | Val acc: 53.73% | LR: 0.000015
Epoch: 002 | Train loss: 1.0625 | Train acc: 49.83% | Val loss: 0.9940 | Val acc: 53.87% | LR: 0.000015
Epoch: 003 | Train loss: 1.0004 | Train acc: 50.36% | Val loss: 0.9941 | Val acc: 54.09% | LR: 0.000015
Epoch: 004 | Train loss: 1.0010 | Train acc: 49.76% | Val loss: 0.9996 | Val acc: 53.89% | LR: 0.000015
Epoch: 005 | Train loss: 1.0004 | Train acc: 50.04% | Val loss: 1.0177 | Val acc: 53.85% | LR: 0.000014
Epoch: 006 | Train loss: 1.0004 | Train acc: 50.01% | Val loss: 0.9928 | Val acc: 54.10% | LR: 0.000014
Epoch: 007 | Train loss: 1.0017 | Train acc: 50.04% | Val loss: 0.9935 | Val acc: 53.95% | LR: 0.000014
Epoch: 008 | Train loss: 0.9991 | Train acc: 50.14% | Val loss: 1.0001 | Val acc: 53.85% | LR: 0.000014
Epoch: 009 | Train loss: 0.9994 | Train acc: 50.54% | Val loss: 1.0407 | Val acc: 53.99% | LR: 0.000014
Epoch: 010 | Train loss: 1.0003 | Train acc: 50.13% | Val loss: 0.9963 | Val acc: 53.97% | LR: 0.000014
Epoch: 011 | Train loss: 1.0019 | Train acc: 49.98% | Val loss: 0.9925 | Val acc: 53.97% | LR: 0.000014
Epoch: 012 | Train loss: 1.0031 | Train acc: 49.70% | Val loss: 0.9970 | Val acc: 54.05% | LR: 0.000014
Epoch: 013 | Train loss: 1.0019 | Train acc: 49.82% | Val loss: 0.9981 | Val acc: 53.83% | LR: 0.000014
Epoch: 014 | Train loss: 1.0019 | Train acc: 49.11% | Val loss: 0.9988 | Val acc: 53.96% | LR: 0.000014
Epoch: 015 | Train loss: 1.0016 | Train acc: 50.33% | Val loss: 1.1883 | Val acc: 53.97% | LR: 0.000014
Epoch: 016 | Train loss: 0.9995 | Train acc: 50.21% | Val loss: 0.9932 | Val acc: 54.03% | LR: 0.000014
Epoch: 017 | Train loss: 0.9987 | Train acc: 50.54% | Val loss: 0.9955 | Val acc: 53.89% | LR: 0.000014
Epoch: 018 | Train loss: 0.9997 | Train acc: 50.54% | Val loss: 0.9974 | Val acc: 53.81% | LR: 0.000014
Epoch: 019 | Train loss: 1.0011 | Train acc: 49.70% | Val loss: 0.9922 | Val acc: 54.01% | LR: 0.000014
Epoch: 020 | Train loss: 1.0000 | Train acc: 50.39% | Val loss: 0.9965 | Val acc: 53.77% | LR: 0.000014
Epoch: 021 | Train loss: 0.9996 | Train acc: 50.39% | Val loss: 0.9937 | Val acc: 53.91% | LR: 0.000014
Epoch: 022 | Train loss: 1.0006 | Train acc: 50.32% | Val loss: 0.9919 | Val acc: 53.93% | LR: 0.000014
Epoch: 023 | Train loss: 0.9994 | Train acc: 50.35% | Val loss: 0.9933 | Val acc: 53.79% | LR: 0.000014
Epoch: 024 | Train loss: 1.0013 | Train acc: 49.61% | Val loss: 0.9951 | Val acc: 53.87% | LR: 0.000014
Epoch: 025 | Train loss: 1.0001 | Train acc: 50.17% | Val loss: 0.9980 | Val acc: 53.96% | LR: 0.000014
Epoch: 026 | Train loss: 0.9997 | Train acc: 50.22% | Val loss: 0.9955 | Val acc: 53.89% | LR: 0.000013
Epoch: 027 | Train loss: 1.0001 | Train acc: 49.94% | Val loss: 1.0005 | Val acc: 53.85% | LR: 0.000013
Epoch: 028 | Train loss: 0.9969 | Train acc: 50.93% | Val loss: 0.9953 | Val acc: 53.96% | LR: 0.000013
Epoch: 029 | Train loss: 1.0062 | Train acc: 50.33% | Val loss: 1.0045 | Val acc: 54.01% | LR: 0.000013
Epoch: 030 | Train loss: 1.0023 | Train acc: 49.60% | Val loss: 0.9946 | Val acc: 53.99% | LR: 0.000013
Epoch: 031 | Train loss: 0.9998 | Train acc: 50.05% | Val loss: 0.9929 | Val acc: 53.93% | LR: 0.000013
Epoch: 032 | Train loss: 1.0015 | Train acc: 49.74% | Val loss: 0.9926 | Val acc: 54.05% | LR: 0.000013
Epoch: 033 | Train loss: 0.9988 | Train acc: 50.20% | Val loss: 0.9930 | Val acc: 53.89% | LR: 0.000013
Epoch: 034 | Train loss: 0.9995 | Train acc: 50.05% | Val loss: 1.0688 | Val acc: 53.67% | LR: 0.000013
Epoch: 035 | Train loss: 0.9993 | Train acc: 49.93% | Val loss: 0.9943 | Val acc: 54.05% | LR: 0.000013
Epoch: 036 | Train loss: 0.9981 | Train acc: 50.52% | Val loss: 0.9958 | Val acc: 53.66% | LR: 0.000013
Epoch: 037 | Train loss: 0.9979 | Train acc: 50.33% | Val loss: 0.9924 | Val acc: 53.83% | LR: 0.000013
Epoch: 038 | Train loss: 0.9979 | Train acc: 50.64% | Val loss: 0.9941 | Val acc: 53.99% | LR: 0.000012
Epoch: 039 | Train loss: 0.9987 | Train acc: 50.34% | Val loss: 0.9959 | Val acc: 53.79% | LR: 0.000012
Epoch: 040 | Train loss: 0.9986 | Train acc: 50.35% | Val loss: 0.9983 | Val acc: 53.99% | LR: 0.000012
Epoch: 041 | Train loss: 0.9997 | Train acc: 50.03% | Val loss: 0.9950 | Val acc: 53.69% | LR: 0.000012
Epoch: 042 | Train loss: 0.9968 | Train acc: 51.00% | Val loss: 0.9939 | Val acc: 53.95% | LR: 0.000012
Epoch: 043 | Train loss: 0.9976 | Train acc: 50.44% | Val loss: 0.9944 | Val acc: 53.95% | LR: 0.000012
Epoch: 044 | Train loss: 0.9995 | Train acc: 50.28% | Val loss: 0.9967 | Val acc: 53.80% | LR: 0.000012
Epoch: 045 | Train loss: 1.0014 | Train acc: 50.13% | Val loss: 0.9965 | Val acc: 53.87% | LR: 0.000012
Epoch: 046 | Train loss: 0.9978 | Train acc: 50.59% | Val loss: 0.9938 | Val acc: 53.79% | LR: 0.000012
Epoch: 047 | Train loss: 0.9969 | Train acc: 50.59% | Val loss: 1.0011 | Val acc: 53.87% | LR: 0.000011
Epoch: 048 | Train loss: 0.9991 | Train acc: 50.13% | Val loss: 0.9957 | Val acc: 53.95% | LR: 0.000011
Epoch: 049 | Train loss: 0.9993 | Train acc: 50.07% | Val loss: 0.9936 | Val acc: 53.81% | LR: 0.000011
Epoch: 050 | Train loss: 0.9980 | Train acc: 50.49% | Val loss: 0.9939 | Val acc: 53.93% | LR: 0.000011
Epoch: 051 | Train loss: 0.9984 | Train acc: 50.27% | Val loss: 0.9935 | Val acc: 53.95% | LR: 0.000011
Epoch: 052 | Train loss: 0.9978 | Train acc: 50.44% | Val loss: 0.9939 | Val acc: 53.77% | LR: 0.000011
Epoch: 053 | Train loss: 1.0009 | Train acc: 50.24% | Val loss: 0.9937 | Val acc: 54.03% | LR: 0.000011
Epoch: 054 | Train loss: 0.9978 | Train acc: 50.37% | Val loss: 0.9932 | Val acc: 54.05% | LR: 0.000011
Epoch: 055 | Train loss: 0.9980 | Train acc: 50.54% | Val loss: 0.9937 | Val acc: 54.03% | LR: 0.000010

[I 2025-09-23 17:42:45,830] Trial 78 finished with value: 0.5395183682441711 and parameters: {'lr': 1.4538736587101868e-05, 'hidden_size': 84, 'dropout': 0.28205576771405105, 'weight_decay': 3.7927885352623726e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0003 | Train acc: 50.27% | Val loss: 0.9945 | Val acc: 53.71% | LR: 0.000015
Epoch: 001 | Train loss: 1.0003 | Train acc: 50.12% | Val loss: 0.9941 | Val acc: 53.97% | LR: 0.000015
Epoch: 002 | Train loss: 1.0021 | Train acc: 49.88% | Val loss: 0.9940 | Val acc: 54.09% | LR: 0.000015
Epoch: 003 | Train loss: 0.9999 | Train acc: 50.32% | Val loss: 0.9948 | Val acc: 53.91% | LR: 0.000015
Epoch: 004 | Train loss: 1.0005 | Train acc: 49.76% | Val loss: 0.9938 | Val acc: 53.74% | LR: 0.000015
Epoch: 005 | Train loss: 1.0001 | Train acc: 50.02% | Val loss: 0.9995 | Val acc: 53.84% | LR: 0.000015
Epoch: 006 | Train loss: 1.0007 | Train acc: 49.96% | Val loss: 0.9928 | Val acc: 53.89% | LR: 0.000015
Epoch: 007 | Train loss: 1.0017 | Train acc: 50.08% | Val loss: 0.9928 | Val acc: 54.19% | LR: 0.000015
Epoch: 008 | Train loss: 0.9993 | Train acc: 50.03% | Val loss: 0.9976 | Val acc: 53.97% | LR: 0.000015
Epoch: 009 | Train loss: 1.0010 | Train acc: 50.48% | Val loss: 0.9958 | Val acc: 53.93% | LR: 0.000015
Epoch: 010 | Train loss: 0.9999 | Train acc: 50.25% | Val loss: 0.9951 | Val acc: 53.74% | LR: 0.000015
Epoch: 011 | Train loss: 1.0001 | Train acc: 49.96% | Val loss: 0.9940 | Val acc: 54.03% | LR: 0.000015
Epoch: 012 | Train loss: 1.0010 | Train acc: 49.61% | Val loss: 0.9934 | Val acc: 53.95% | LR: 0.000015
Epoch: 013 | Train loss: 1.0012 | Train acc: 49.80% | Val loss: 1.0032 | Val acc: 54.03% | LR: 0.000015
Epoch: 014 | Train loss: 1.0024 | Train acc: 49.20% | Val loss: 0.9951 | Val acc: 53.83% | LR: 0.000014
Epoch: 015 | Train loss: 0.9995 | Train acc: 50.30% | Val loss: 1.0075 | Val acc: 53.78% | LR: 0.000014
Epoch: 016 | Train loss: 0.9999 | Train acc: 50.16% | Val loss: 0.9977 | Val acc: 53.95% | LR: 0.000014
Epoch: 017 | Train loss: 0.9994 | Train acc: 50.48% | Val loss: 1.0101 | Val acc: 53.82% | LR: 0.000014
Epoch: 018 | Train loss: 1.0000 | Train acc: 50.62% | Val loss: 0.9936 | Val acc: 54.03% | LR: 0.000014
Epoch: 019 | Train loss: 1.0001 | Train acc: 49.73% | Val loss: 0.9959 | Val acc: 54.03% | LR: 0.000014
Epoch: 020 | Train loss: 1.0004 | Train acc: 50.50% | Val loss: 1.2941 | Val acc: 53.97% | LR: 0.000014
Epoch: 021 | Train loss: 0.9990 | Train acc: 50.44% | Val loss: 0.9922 | Val acc: 53.93% | LR: 0.000014
Epoch: 022 | Train loss: 1.0001 | Train acc: 50.39% | Val loss: 0.9949 | Val acc: 54.03% | LR: 0.000014
Epoch: 023 | Train loss: 0.9996 | Train acc: 50.41% | Val loss: 0.9939 | Val acc: 54.13% | LR: 0.000014
Epoch: 024 | Train loss: 1.0003 | Train acc: 49.69% | Val loss: 0.9934 | Val acc: 53.93% | LR: 0.000014
Epoch: 025 | Train loss: 1.0001 | Train acc: 50.19% | Val loss: 0.9931 | Val acc: 54.21% | LR: 0.000014
Epoch: 026 | Train loss: 0.9992 | Train acc: 50.29% | Val loss: 0.9948 | Val acc: 53.99% | LR: 0.000014
Epoch: 027 | Train loss: 0.9997 | Train acc: 50.00% | Val loss: 0.9929 | Val acc: 53.76% | LR: 0.000014
Epoch: 028 | Train loss: 0.9968 | Train acc: 50.99% | Val loss: 0.9950 | Val acc: 53.80% | LR: 0.000014
Epoch: 029 | Train loss: 0.9987 | Train acc: 50.37% | Val loss: 0.9942 | Val acc: 53.78% | LR: 0.000014
Epoch: 030 | Train loss: 1.0008 | Train acc: 49.64% | Val loss: 0.9934 | Val acc: 53.97% | LR: 0.000013
Epoch: 031 | Train loss: 0.9991 | Train acc: 50.13% | Val loss: 0.9934 | Val acc: 54.01% | LR: 0.000013
Epoch: 032 | Train loss: 0.9998 | Train acc: 49.76% | Val loss: 0.9948 | Val acc: 53.72% | LR: 0.000013
Epoch: 033 | Train loss: 1.0007 | Train acc: 50.19% | Val loss: 0.9958 | Val acc: 53.85% | LR: 0.000013
Epoch: 034 | Train loss: 0.9987 | Train acc: 50.08% | Val loss: 0.9938 | Val acc: 53.93% | LR: 0.000013
Epoch: 035 | Train loss: 0.9992 | Train acc: 49.95% | Val loss: 0.9936 | Val acc: 53.97% | LR: 0.000013
Epoch: 036 | Train loss: 0.9976 | Train acc: 50.52% | Val loss: 0.9929 | Val acc: 54.09% | LR: 0.000013
Epoch: 037 | Train loss: 0.9974 | Train acc: 50.46% | Val loss: 0.9935 | Val acc: 54.03% | LR: 0.000013
Epoch: 038 | Train loss: 0.9975 | Train acc: 50.87% | Val loss: 0.9941 | Val acc: 53.78% | LR: 0.000013
Epoch: 039 | Train loss: 0.9986 | Train acc: 50.33% | Val loss: 0.9960 | Val acc: 53.83% | LR: 0.000013
Epoch: 040 | Train loss: 0.9989 | Train acc: 50.33% | Val loss: 0.9934 | Val acc: 54.01% | LR: 0.000012
Epoch: 041 | Train loss: 0.9998 | Train acc: 50.09% | Val loss: 0.9931 | Val acc: 54.07% | LR: 0.000012
Epoch: 042 | Train loss: 0.9969 | Train acc: 51.06% | Val loss: 0.9936 | Val acc: 54.13% | LR: 0.000012
Epoch: 043 | Train loss: 0.9980 | Train acc: 50.40% | Val loss: 0.9991 | Val acc: 54.01% | LR: 0.000012
Epoch: 044 | Train loss: 1.0052 | Train acc: 50.20% | Val loss: 0.9936 | Val acc: 53.73% | LR: 0.000012
Epoch: 045 | Train loss: 1.0008 | Train acc: 50.02% | Val loss: 0.9994 | Val acc: 53.83% | LR: 0.000012
Epoch: 046 | Train loss: 0.9980 | Train acc: 50.58% | Val loss: 0.9954 | Val acc: 53.95% | LR: 0.000012
Epoch: 047 | Train loss: 0.9975 | Train acc: 50.65% | Val loss: 0.9923 | Val acc: 54.03% | LR: 0.000012
Epoch: 048 | Train loss: 0.9992 | Train acc: 50.14% | Val loss: 0.9945 | Val acc: 53.95% | LR: 0.000011
Epoch: 049 | Train loss: 1.0020 | Train acc: 50.06% | Val loss: 0.9975 | Val acc: 53.89% | LR: 0.000011
Epoch: 050 | Train loss: 0.9985 | Train acc: 50.50% | Val loss: 0.9935 | Val acc: 53.69% | LR: 0.000011
Epoch: 051 | Train loss: 0.9979 | Train acc: 50.27% | Val loss: 0.9977 | Val acc: 54.07% | LR: 0.000011
Epoch: 052 | Train loss: 0.9982 | Train acc: 50.46% | Val loss: 1.0542 | Val acc: 53.99% | LR: 0.000011
Epoch: 053 | Train loss: 0.9981 | Train acc: 50.30% | Val loss: 0.9939 | Val acc: 53.87% | LR: 0.000011
Epoch: 054 | Train loss: 0.9983 | Train acc: 50.35% | Val loss: 0.9920 | Val acc: 54.13% | LR: 0.000011
Epoch: 055 | Train loss: 0.9981 | Train acc: 50.52% | Val loss: 0.9932 | Val acc: 53.97% | LR: 0.000011
Epoch: 056 | Train loss: 0.9978 | Train acc: 50.35% | Val loss: 0.9973 | Val acc: 53.85% | LR: 0.000010
Epoch: 057 | Train loss: 0.9996 | Train acc: 50.06% | Val loss: 0.9955 | Val acc: 54.14% | LR: 0.000010
Epoch: 058 | Train loss: 0.9974 | Train acc: 50.49% | Val loss: 0.9931 | Val acc: 53.88% | LR: 0.000010
Epoch: 059 | Train loss: 0.9980 | Train acc: 50.34% | Val loss: 0.9943 | Val acc: 54.05% | LR: 0.000010
Epoch: 060 | Train loss: 0.9966 | Train acc: 50.70% | Val loss: 0.9944 | Val acc: 53.87% | LR: 0.000010
Epoch: 061 | Train loss: 0.9951 | Train acc: 50.94% | Val loss: 0.9947 | Val acc: 54.01% | LR: 0.000010
Epoch: 062 | Train loss: 0.9990 | Train acc: 50.18% | Val loss: 0.9921 | Val acc: 54.05% | LR: 0.000010
Epoch: 063 | Train loss: 0.9983 | Train acc: 50.16% | Val loss: 0.9933 | Val acc: 53.93% | LR: 0.000009
Epoch: 064 | Train loss: 0.9955 | Train acc: 50.61% | Val loss: 0.9938 | Val acc: 54.01% | LR: 0.000009
Epoch: 065 | Train loss: 0.9975 | Train acc: 50.40% | Val loss: 1.0006 | Val acc: 54.01% | LR: 0.000009
Epoch: 066 | Train loss: 0.9983 | Train acc: 50.16% | Val loss: 0.9940 | Val acc: 54.01% | LR: 0.000009
Epoch: 067 | Train loss: 1.0005 | Train acc: 49.85% | Val loss: 0.9963 | Val acc: 54.01% | LR: 0.000009
Epoch: 068 | Train loss: 0.9940 | Train acc: 50.76% | Val loss: 0.9936 | Val acc: 53.93% | LR: 0.000009
Epoch: 069 | Train loss: 0.9935 | Train acc: 50.86% | Val loss: 0.9925 | Val acc: 54.07% | LR: 0.000009
Epoch: 070 | Train loss: 0.9922 | Train acc: 51.24% | Val loss: 0.9934 | Val acc: 53.99% | LR: 0.000008
Epoch: 071 | Train loss: 1.0039 | Train acc: 49.89% | Val loss: 0.9928 | Val acc: 54.05% | LR: 0.000008
Epoch: 072 | Train loss: 0.9969 | Train acc: 50.17% | Val loss: 0.9922 | Val acc: 54.17% | LR: 0.000008
Epoch: 073 | Train loss: 0.9961 | Train acc: 50.51% | Val loss: 0.9937 | Val acc: 53.95% | LR: 0.000008
Epoch: 074 | Train loss: 0.9975 | Train acc: 50.44% | Val loss: 0.9937 | Val acc: 53.93% | LR: 0.000008

[I 2025-09-23 17:43:52,505] Trial 79 finished with value: 0.5395183682441711 and parameters: {'lr': 1.4822694860193288e-05, 'hidden_size': 84, 'dropout': 0.282654593047947, 'weight_decay': 3.4848325089142923e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9956 | Train acc: 50.68% | Val loss: 0.9921 | Val acc: 54.31% | LR: 0.000015
Epoch: 001 | Train loss: 0.9984 | Train acc: 50.26% | Val loss: 0.9912 | Val acc: 54.42% | LR: 0.000015
Epoch: 002 | Train loss: 0.9955 | Train acc: 50.43% | Val loss: 0.9922 | Val acc: 54.28% | LR: 0.000015
Epoch: 003 | Train loss: 0.9968 | Train acc: 50.51% | Val loss: 0.9910 | Val acc: 54.46% | LR: 0.000015
Epoch: 004 | Train loss: 0.9971 | Train acc: 50.16% | Val loss: 0.9907 | Val acc: 54.34% | LR: 0.000015
Epoch: 005 | Train loss: 0.9919 | Train acc: 50.94% | Val loss: 0.9902 | Val acc: 54.34% | LR: 0.000015
Epoch: 006 | Train loss: 0.9988 | Train acc: 49.96% | Val loss: 0.9902 | Val acc: 54.24% | LR: 0.000015
Epoch: 007 | Train loss: 0.9936 | Train acc: 50.64% | Val loss: 0.9901 | Val acc: 54.21% | LR: 0.000015
Epoch: 008 | Train loss: 0.9971 | Train acc: 50.22% | Val loss: 0.9902 | Val acc: 54.29% | LR: 0.000015
Epoch: 009 | Train loss: 0.9976 | Train acc: 50.08% | Val loss: 0.9898 | Val acc: 54.45% | LR: 0.000015
Epoch: 010 | Train loss: 0.9916 | Train acc: 50.91% | Val loss: 0.9895 | Val acc: 54.61% | LR: 0.000015
Epoch: 011 | Train loss: 0.9931 | Train acc: 50.65% | Val loss: 0.9903 | Val acc: 54.43% | LR: 0.000015
Epoch: 012 | Train loss: 0.9918 | Train acc: 50.85% | Val loss: 0.9894 | Val acc: 54.64% | LR: 0.000015
Epoch: 013 | Train loss: 0.9949 | Train acc: 50.37% | Val loss: 0.9908 | Val acc: 54.35% | LR: 0.000015
Epoch: 014 | Train loss: 0.9911 | Train acc: 50.84% | Val loss: 0.9893 | Val acc: 54.51% | LR: 0.000015
Epoch: 015 | Train loss: 1.0465 | Train acc: 50.74% | Val loss: 0.9890 | Val acc: 54.63% | LR: 0.000015
Epoch: 016 | Train loss: 0.9946 | Train acc: 50.95% | Val loss: 0.9892 | Val acc: 54.74% | LR: 0.000015
Epoch: 017 | Train loss: 1.0024 | Train acc: 50.45% | Val loss: 0.9892 | Val acc: 54.64% | LR: 0.000015
Epoch: 018 | Train loss: 0.9881 | Train acc: 50.89% | Val loss: 0.9891 | Val acc: 54.70% | LR: 0.000015
Epoch: 019 | Train loss: 0.9923 | Train acc: 50.91% | Val loss: 0.9893 | Val acc: 54.74% | LR: 0.000015
Epoch: 020 | Train loss: 0.9991 | Train acc: 50.66% | Val loss: 0.9885 | Val acc: 54.82% | LR: 0.000015
Epoch: 021 | Train loss: 0.9897 | Train acc: 50.92% | Val loss: 0.9885 | Val acc: 54.70% | LR: 0.000015
Epoch: 022 | Train loss: 1.0032 | Train acc: 50.53% | Val loss: 0.9882 | Val acc: 54.64% | LR: 0.000014
Epoch: 023 | Train loss: 1.0037 | Train acc: 50.58% | Val loss: 0.9883 | Val acc: 54.58% | LR: 0.000014
Epoch: 024 | Train loss: 0.9939 | Train acc: 50.57% | Val loss: 0.9883 | Val acc: 54.68% | LR: 0.000014
Epoch: 025 | Train loss: 0.9904 | Train acc: 50.74% | Val loss: 0.9880 | Val acc: 54.53% | LR: 0.000014
Epoch: 026 | Train loss: 0.9930 | Train acc: 50.50% | Val loss: 0.9878 | Val acc: 54.65% | LR: 0.000014
Epoch: 027 | Train loss: 1.4082 | Train acc: 50.33% | Val loss: 0.9876 | Val acc: 54.65% | LR: 0.000014
Epoch: 028 | Train loss: 0.9971 | Train acc: 50.26% | Val loss: 0.9875 | Val acc: 54.55% | LR: 0.000014
Epoch: 029 | Train loss: 1.1292 | Train acc: 50.24% | Val loss: 0.9874 | Val acc: 54.58% | LR: 0.000014
Epoch: 030 | Train loss: 0.9915 | Train acc: 50.95% | Val loss: 0.9873 | Val acc: 54.57% | LR: 0.000014
Epoch: 031 | Train loss: 0.9886 | Train acc: 51.26% | Val loss: 0.9872 | Val acc: 54.52% | LR: 0.000014
Epoch: 032 | Train loss: 0.9964 | Train acc: 50.63% | Val loss: 0.9903 | Val acc: 54.43% | LR: 0.000014
Epoch: 033 | Train loss: 1.0585 | Train acc: 50.69% | Val loss: 0.9870 | Val acc: 54.53% | LR: 0.000014
Epoch: 034 | Train loss: 0.9917 | Train acc: 50.91% | Val loss: 0.9865 | Val acc: 54.55% | LR: 0.000013
Epoch: 035 | Train loss: 0.9935 | Train acc: 50.54% | Val loss: 0.9867 | Val acc: 54.41% | LR: 0.000013
Epoch: 036 | Train loss: 0.9970 | Train acc: 51.13% | Val loss: 0.9863 | Val acc: 54.43% | LR: 0.000013
Epoch: 037 | Train loss: 1.0039 | Train acc: 50.43% | Val loss: 0.9863 | Val acc: 54.41% | LR: 0.000013
Epoch: 038 | Train loss: 1.0010 | Train acc: 50.34% | Val loss: 0.9862 | Val acc: 54.33% | LR: 0.000013
Epoch: 039 | Train loss: 1.0032 | Train acc: 51.07% | Val loss: 0.9861 | Val acc: 54.34% | LR: 0.000013
Epoch: 040 | Train loss: 0.9931 | Train acc: 51.22% | Val loss: 0.9860 | Val acc: 54.34% | LR: 0.000013
Epoch: 041 | Train loss: 1.0440 | Train acc: 50.15% | Val loss: 0.9862 | Val acc: 54.34% | LR: 0.000013
Epoch: 042 | Train loss: 0.9934 | Train acc: 50.88% | Val loss: 0.9850 | Val acc: 54.22% | LR: 0.000013
Epoch: 043 | Train loss: 0.9960 | Train acc: 50.53% | Val loss: 0.9887 | Val acc: 54.12% | LR: 0.000012
Epoch: 044 | Train loss: 0.9893 | Train acc: 51.07% | Val loss: 0.9853 | Val acc: 54.22% | LR: 0.000012
Epoch: 045 | Train loss: 0.9961 | Train acc: 51.00% | Val loss: 0.9873 | Val acc: 54.22% | LR: 0.000012
Epoch: 046 | Train loss: 1.0061 | Train acc: 50.18% | Val loss: 0.9851 | Val acc: 54.28% | LR: 0.000012
Epoch: 047 | Train loss: 0.9973 | Train acc: 50.22% | Val loss: 0.9850 | Val acc: 54.28% | LR: 0.000012
Epoch: 048 | Train loss: 0.9988 | Train acc: 50.69% | Val loss: 0.9870 | Val acc: 54.28% | LR: 0.000012
Epoch: 049 | Train loss: 1.0495 | Train acc: 50.81% | Val loss: 0.9850 | Val acc: 54.28% | LR: 0.000012
Epoch: 050 | Train loss: 1.0022 | Train acc: 50.51% | Val loss: 0.9850 | Val acc: 54.26% | LR: 0.000012
Epoch: 051 | Train loss: 0.9987 | Train acc: 50.89% | Val loss: 0.9848 | Val acc: 54.34% | LR: 0.000011
Epoch: 052 | Train loss: 0.9929 | Train acc: 50.87% | Val loss: 0.9847 | Val acc: 54.32% | LR: 0.000011
Epoch: 053 | Train loss: 1.0622 | Train acc: 50.58% | Val loss: 0.9846 | Val acc: 54.38% | LR: 0.000011
Epoch: 054 | Train loss: 1.1986 | Train acc: 50.73% | Val loss: 0.9846 | Val acc: 54.40% | LR: 0.000011
Epoch: 055 | Train loss: 1.0045 | Train acc: 50.06% | Val loss: 0.9846 | Val acc: 54.36% | LR: 0.000011
Epoch: 056 | Train loss: 1.0018 | Train acc: 50.30% | Val loss: 0.9846 | Val acc: 54.34% | LR: 0.000011
Epoch: 057 | Train loss: 1.0041 | Train acc: 50.95% | Val loss: 0.9897 | Val acc: 54.32% | LR: 0.000011
Epoch: 058 | Train loss: 0.9933 | Train acc: 51.12% | Val loss: 0.9906 | Val acc: 54.32% | LR: 0.000010
Epoch: 059 | Train loss: 0.9948 | Train acc: 50.75% | Val loss: 0.9860 | Val acc: 54.34% | LR: 0.000010
Epoch: 060 | Train loss: 1.0754 | Train acc: 50.93% | Val loss: 0.9843 | Val acc: 54.40% | LR: 0.000010
Epoch: 061 | Train loss: 1.0202 | Train acc: 50.74% | Val loss: 0.9842 | Val acc: 54.24% | LR: 0.000010
Epoch: 062 | Train loss: 0.9948 | Train acc: 50.94% | Val loss: 0.9842 | Val acc: 54.28% | LR: 0.000010
Epoch: 063 | Train loss: 1.0809 | Train acc: 50.68% | Val loss: 0.9841 | Val acc: 54.28% | LR: 0.000010
Epoch: 064 | Train loss: 0.9895 | Train acc: 51.32% | Val loss: 0.9839 | Val acc: 54.30% | LR: 0.000010
Epoch: 065 | Train loss: 1.0045 | Train acc: 51.11% | Val loss: 0.9839 | Val acc: 54.30% | LR: 0.000009
Epoch: 066 | Train loss: 1.0062 | Train acc: 50.77% | Val loss: 0.9839 | Val acc: 54.30% | LR: 0.000009
Epoch: 067 | Train loss: 1.0149 | Train acc: 51.03% | Val loss: 0.9838 | Val acc: 54.32% | LR: 0.000009
Epoch: 068 | Train loss: 1.0371 | Train acc: 50.36% | Val loss: 0.9838 | Val acc: 54.34% | LR: 0.000009
Epoch: 069 | Train loss: 1.0033 | Train acc: 50.66% | Val loss: 0.9838 | Val acc: 54.36% | LR: 0.000009

[I 2025-09-23 17:44:51,536] Trial 80 finished with value: 0.5435591697692871 and parameters: {'lr': 1.52583576612105e-05, 'hidden_size': 86, 'dropout': 0.27333997897490636, 'weight_decay': 3.9166632191993075e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9988 | Train acc: 50.60% | Val loss: 1.0133 | Val acc: 45.99% | LR: 0.000015
Epoch: 001 | Train loss: 1.0029 | Train acc: 49.99% | Val loss: 1.0086 | Val acc: 45.99% | LR: 0.000015
Epoch: 002 | Train loss: 1.0014 | Train acc: 50.43% | Val loss: 1.0092 | Val acc: 45.87% | LR: 0.000015
Epoch: 003 | Train loss: 0.9999 | Train acc: 50.24% | Val loss: 1.0086 | Val acc: 46.01% | LR: 0.000015
Epoch: 004 | Train loss: 0.9996 | Train acc: 50.51% | Val loss: 1.0090 | Val acc: 45.99% | LR: 0.000015
Epoch: 005 | Train loss: 1.0017 | Train acc: 50.59% | Val loss: 1.0105 | Val acc: 45.89% | LR: 0.000015
Epoch: 006 | Train loss: 0.9994 | Train acc: 50.56% | Val loss: 1.0084 | Val acc: 45.87% | LR: 0.000015
Epoch: 007 | Train loss: 1.0118 | Train acc: 50.40% | Val loss: 1.0215 | Val acc: 46.07% | LR: 0.000015
Epoch: 008 | Train loss: 0.9998 | Train acc: 49.97% | Val loss: 1.0142 | Val acc: 46.05% | LR: 0.000015
Epoch: 009 | Train loss: 0.9992 | Train acc: 50.32% | Val loss: 1.0191 | Val acc: 45.74% | LR: 0.000015
Epoch: 010 | Train loss: 1.0014 | Train acc: 49.97% | Val loss: 1.0161 | Val acc: 45.91% | LR: 0.000015
Epoch: 011 | Train loss: 1.0033 | Train acc: 50.15% | Val loss: 1.0505 | Val acc: 46.21% | LR: 0.000015
Epoch: 012 | Train loss: 1.0007 | Train acc: 50.74% | Val loss: 1.0135 | Val acc: 46.03% | LR: 0.000014
Epoch: 013 | Train loss: 1.0008 | Train acc: 51.00% | Val loss: 1.0201 | Val acc: 45.82% | LR: 0.000014
Epoch: 014 | Train loss: 0.9988 | Train acc: 50.92% | Val loss: 1.0198 | Val acc: 46.07% | LR: 0.000014
Epoch: 015 | Train loss: 0.9990 | Train acc: 50.89% | Val loss: 1.0111 | Val acc: 45.83% | LR: 0.000014
Epoch: 016 | Train loss: 0.9990 | Train acc: 51.33% | Val loss: 1.0082 | Val acc: 46.11% | LR: 0.000014
Epoch: 017 | Train loss: 0.9993 | Train acc: 50.98% | Val loss: 1.0149 | Val acc: 46.15% | LR: 0.000014
Epoch: 018 | Train loss: 0.9987 | Train acc: 50.72% | Val loss: 1.0147 | Val acc: 46.22% | LR: 0.000014
Epoch: 019 | Train loss: 1.0016 | Train acc: 50.15% | Val loss: 1.0121 | Val acc: 46.06% | LR: 0.000014
Epoch: 020 | Train loss: 0.9994 | Train acc: 50.10% | Val loss: 1.0100 | Val acc: 45.86% | LR: 0.000014
Epoch: 021 | Train loss: 0.9985 | Train acc: 50.60% | Val loss: 1.0252 | Val acc: 45.87% | LR: 0.000014
Epoch: 022 | Train loss: 0.9994 | Train acc: 50.20% | Val loss: 1.0149 | Val acc: 45.98% | LR: 0.000014
Epoch: 023 | Train loss: 0.9987 | Train acc: 50.70% | Val loss: 1.0069 | Val acc: 46.19% | LR: 0.000014
Epoch: 024 | Train loss: 1.0223 | Train acc: 50.99% | Val loss: 1.0197 | Val acc: 46.11% | LR: 0.000014
Epoch: 025 | Train loss: 0.9990 | Train acc: 50.53% | Val loss: 1.0131 | Val acc: 45.98% | LR: 0.000014
Epoch: 026 | Train loss: 0.9987 | Train acc: 50.36% | Val loss: 1.0118 | Val acc: 46.02% | LR: 0.000014
Epoch: 027 | Train loss: 0.9996 | Train acc: 50.36% | Val loss: 1.0108 | Val acc: 46.00% | LR: 0.000014
Epoch: 028 | Train loss: 0.9994 | Train acc: 50.25% | Val loss: 1.0122 | Val acc: 45.96% | LR: 0.000014
Epoch: 029 | Train loss: 0.9981 | Train acc: 50.66% | Val loss: 1.0109 | Val acc: 46.09% | LR: 0.000013
Epoch: 030 | Train loss: 1.0002 | Train acc: 50.40% | Val loss: 1.0272 | Val acc: 45.86% | LR: 0.000013
Epoch: 031 | Train loss: 0.9999 | Train acc: 50.38% | Val loss: 1.0224 | Val acc: 45.93% | LR: 0.000013
Epoch: 032 | Train loss: 0.9985 | Train acc: 50.52% | Val loss: 1.0090 | Val acc: 46.09% | LR: 0.000013
Epoch: 033 | Train loss: 0.9980 | Train acc: 50.76% | Val loss: 1.0479 | Val acc: 45.89% | LR: 0.000013
Epoch: 034 | Train loss: 0.9991 | Train acc: 50.08% | Val loss: 1.0111 | Val acc: 45.93% | LR: 0.000013
Epoch: 035 | Train loss: 0.9981 | Train acc: 50.61% | Val loss: 1.0155 | Val acc: 46.04% | LR: 0.000013
Epoch: 036 | Train loss: 0.9993 | Train acc: 50.00% | Val loss: 1.0092 | Val acc: 46.03% | LR: 0.000013
Epoch: 037 | Train loss: 0.9981 | Train acc: 50.52% | Val loss: 1.0114 | Val acc: 45.93% | LR: 0.000013
Epoch: 038 | Train loss: 0.9979 | Train acc: 50.60% | Val loss: 1.0106 | Val acc: 45.79% | LR: 0.000013
Epoch: 039 | Train loss: 1.0030 | Train acc: 50.43% | Val loss: 1.0092 | Val acc: 45.93% | LR: 0.000012
Epoch: 040 | Train loss: 0.9980 | Train acc: 50.54% | Val loss: 1.0103 | Val acc: 45.87% | LR: 0.000012
Epoch: 041 | Train loss: 0.9979 | Train acc: 50.53% | Val loss: 1.0198 | Val acc: 45.88% | LR: 0.000012
Epoch: 042 | Train loss: 0.9973 | Train acc: 50.79% | Val loss: 1.0103 | Val acc: 45.91% | LR: 0.000012
Epoch: 043 | Train loss: 0.9981 | Train acc: 50.26% | Val loss: 1.0101 | Val acc: 45.99% | LR: 0.000012
Epoch: 044 | Train loss: 0.9964 | Train acc: 50.86% | Val loss: 1.0107 | Val acc: 45.99% | LR: 0.000012
Epoch: 045 | Train loss: 0.9967 | Train acc: 50.72% | Val loss: 1.0101 | Val acc: 45.92% | LR: 0.000012
Epoch: 046 | Train loss: 0.9991 | Train acc: 50.34% | Val loss: 1.0096 | Val acc: 45.97% | LR: 0.000012
Epoch: 047 | Train loss: 0.9973 | Train acc: 50.61% | Val loss: 1.0091 | Val acc: 45.95% | LR: 0.000012
Epoch: 048 | Train loss: 0.9977 | Train acc: 50.26% | Val loss: 1.0534 | Val acc: 45.99% | LR: 0.000011
Epoch: 049 | Train loss: 0.9980 | Train acc: 50.25% | Val loss: 1.0095 | Val acc: 45.97% | LR: 0.000011
Epoch: 050 | Train loss: 0.9980 | Train acc: 50.08% | Val loss: 1.0101 | Val acc: 46.08% | LR: 0.000011
Epoch: 051 | Train loss: 0.9994 | Train acc: 50.00% | Val loss: 1.0099 | Val acc: 45.99% | LR: 0.000011
Epoch: 052 | Train loss: 0.9991 | Train acc: 49.97% | Val loss: 1.0126 | Val acc: 45.93% | LR: 0.000011
Epoch: 053 | Train loss: 0.9972 | Train acc: 50.52% | Val loss: 1.0100 | Val acc: 45.93% | LR: 0.000011
Epoch: 054 | Train loss: 0.9987 | Train acc: 50.15% | Val loss: 1.0124 | Val acc: 45.95% | LR: 0.000011
Epoch: 055 | Train loss: 0.9950 | Train acc: 51.13% | Val loss: 1.0092 | Val acc: 46.11% | LR: 0.000011
Epoch: 056 | Train loss: 0.9977 | Train acc: 50.70% | Val loss: 1.0095 | Val acc: 45.97% | LR: 0.000010
Epoch: 057 | Train loss: 0.9976 | Train acc: 50.53% | Val loss: 1.0127 | Val acc: 45.83% | LR: 0.000010
Epoch: 058 | Train loss: 0.9973 | Train acc: 50.60% | Val loss: 1.0110 | Val acc: 45.89% | LR: 0.000010
Epoch: 059 | Train loss: 0.9955 | Train acc: 51.02% | Val loss: 1.0116 | Val acc: 45.95% | LR: 0.000010
Epoch: 060 | Train loss: 0.9994 | Train acc: 49.91% | Val loss: 1.0094 | Val acc: 45.91% | LR: 0.000010
Epoch: 061 | Train loss: 0.9972 | Train acc: 50.32% | Val loss: 1.0104 | Val acc: 46.01% | LR: 0.000010
Epoch: 062 | Train loss: 0.9973 | Train acc: 50.36% | Val loss: 1.0102 | Val acc: 46.05% | LR: 0.000010
Epoch: 063 | Train loss: 0.9966 | Train acc: 50.96% | Val loss: 1.0109 | Val acc: 45.91% | LR: 0.000009
Epoch: 064 | Train loss: 0.9988 | Train acc: 49.89% | Val loss: 1.0105 | Val acc: 45.93% | LR: 0.000009
Epoch: 065 | Train loss: 0.9961 | Train acc: 50.64% | Val loss: 1.0113 | Val acc: 45.89% | LR: 0.000009
Epoch: 066 | Train loss: 0.9967 | Train acc: 50.67% | Val loss: 1.0095 | Val acc: 45.91% | LR: 0.000009
Epoch: 067 | Train loss: 0.9966 | Train acc: 50.53% | Val loss: 1.0100 | Val acc: 45.93% | LR: 0.000009

[I 2025-09-23 17:45:52,820] Trial 81 finished with value: 0.4600910127162933 and parameters: {'lr': 1.473904480021771e-05, 'hidden_size': 83, 'dropout': 0.27747203952851707, 'weight_decay': 3.9906367540244315e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0011 | Train acc: 49.72% | Val loss: 0.9944 | Val acc: 53.98% | LR: 0.000016
Epoch: 001 | Train loss: 1.0037 | Train acc: 49.24% | Val loss: 0.9942 | Val acc: 54.09% | LR: 0.000016
Epoch: 002 | Train loss: 1.0004 | Train acc: 49.79% | Val loss: 0.9942 | Val acc: 54.08% | LR: 0.000016
Epoch: 003 | Train loss: 1.0025 | Train acc: 49.55% | Val loss: 0.9941 | Val acc: 54.27% | LR: 0.000016
Epoch: 004 | Train loss: 1.0010 | Train acc: 49.62% | Val loss: 0.9941 | Val acc: 54.30% | LR: 0.000016
Epoch: 005 | Train loss: 1.0064 | Train acc: 48.75% | Val loss: 0.9940 | Val acc: 54.34% | LR: 0.000016
Epoch: 006 | Train loss: 1.0024 | Train acc: 49.51% | Val loss: 0.9941 | Val acc: 54.22% | LR: 0.000016
Epoch: 007 | Train loss: 1.0021 | Train acc: 49.58% | Val loss: 0.9940 | Val acc: 54.39% | LR: 0.000016
Epoch: 008 | Train loss: 1.0013 | Train acc: 49.66% | Val loss: 0.9939 | Val acc: 54.19% | LR: 0.000016
Epoch: 009 | Train loss: 1.0019 | Train acc: 49.40% | Val loss: 0.9938 | Val acc: 54.24% | LR: 0.000016
Epoch: 010 | Train loss: 1.0025 | Train acc: 49.31% | Val loss: 0.9937 | Val acc: 54.07% | LR: 0.000016
Epoch: 011 | Train loss: 1.0006 | Train acc: 49.72% | Val loss: 0.9939 | Val acc: 54.12% | LR: 0.000016
Epoch: 012 | Train loss: 1.0007 | Train acc: 49.80% | Val loss: 0.9939 | Val acc: 54.14% | LR: 0.000016
Epoch: 013 | Train loss: 1.0010 | Train acc: 49.67% | Val loss: 0.9938 | Val acc: 54.19% | LR: 0.000016
Epoch: 014 | Train loss: 1.0016 | Train acc: 49.54% | Val loss: 0.9938 | Val acc: 54.31% | LR: 0.000016
Epoch: 015 | Train loss: 1.0023 | Train acc: 49.31% | Val loss: 0.9938 | Val acc: 54.38% | LR: 0.000016
Epoch: 016 | Train loss: 1.0001 | Train acc: 49.96% | Val loss: 0.9938 | Val acc: 54.16% | LR: 0.000016
Epoch: 017 | Train loss: 0.9979 | Train acc: 50.45% | Val loss: 0.9937 | Val acc: 54.00% | LR: 0.000016
Epoch: 018 | Train loss: 1.0031 | Train acc: 49.32% | Val loss: 0.9936 | Val acc: 53.86% | LR: 0.000016
Epoch: 019 | Train loss: 1.0009 | Train acc: 49.84% | Val loss: 0.9937 | Val acc: 53.64% | LR: 0.000016
Epoch: 020 | Train loss: 1.0018 | Train acc: 49.68% | Val loss: 0.9934 | Val acc: 53.80% | LR: 0.000016
Epoch: 021 | Train loss: 1.0001 | Train acc: 49.87% | Val loss: 0.9933 | Val acc: 53.72% | LR: 0.000016
Epoch: 022 | Train loss: 1.0022 | Train acc: 49.34% | Val loss: 0.9934 | Val acc: 53.57% | LR: 0.000016
Epoch: 023 | Train loss: 0.9994 | Train acc: 50.48% | Val loss: 0.9934 | Val acc: 53.31% | LR: 0.000015
Epoch: 024 | Train loss: 0.9995 | Train acc: 50.24% | Val loss: 0.9933 | Val acc: 53.07% | LR: 0.000015
Epoch: 025 | Train loss: 0.9992 | Train acc: 50.41% | Val loss: 0.9932 | Val acc: 53.01% | LR: 0.000015
Epoch: 026 | Train loss: 0.9989 | Train acc: 50.34% | Val loss: 0.9929 | Val acc: 53.17% | LR: 0.000015
Epoch: 027 | Train loss: 0.9996 | Train acc: 50.03% | Val loss: 1.0260 | Val acc: 53.17% | LR: 0.000015
Epoch: 028 | Train loss: 0.9997 | Train acc: 49.82% | Val loss: 0.9928 | Val acc: 52.94% | LR: 0.000015
Epoch: 029 | Train loss: 0.9997 | Train acc: 49.94% | Val loss: 0.9928 | Val acc: 52.80% | LR: 0.000015
Epoch: 030 | Train loss: 1.0005 | Train acc: 49.30% | Val loss: 0.9928 | Val acc: 52.69% | LR: 0.000015
Epoch: 031 | Train loss: 0.9995 | Train acc: 49.74% | Val loss: 0.9927 | Val acc: 52.71% | LR: 0.000015
Epoch: 032 | Train loss: 0.9994 | Train acc: 49.70% | Val loss: 0.9925 | Val acc: 52.59% | LR: 0.000015
Epoch: 033 | Train loss: 0.9993 | Train acc: 50.58% | Val loss: 0.9934 | Val acc: 52.64% | LR: 0.000015
Epoch: 034 | Train loss: 0.9986 | Train acc: 50.45% | Val loss: 0.9927 | Val acc: 52.39% | LR: 0.000014
Epoch: 035 | Train loss: 0.9991 | Train acc: 50.01% | Val loss: 0.9926 | Val acc: 52.31% | LR: 0.000014
Epoch: 036 | Train loss: 0.9990 | Train acc: 50.71% | Val loss: 0.9927 | Val acc: 52.13% | LR: 0.000014
Epoch: 037 | Train loss: 0.9985 | Train acc: 50.94% | Val loss: 0.9926 | Val acc: 52.15% | LR: 0.000014
Epoch: 038 | Train loss: 0.9985 | Train acc: 50.66% | Val loss: 0.9926 | Val acc: 52.04% | LR: 0.000014
Epoch: 039 | Train loss: 0.9982 | Train acc: 50.92% | Val loss: 0.9926 | Val acc: 52.12% | LR: 0.000014
Epoch: 040 | Train loss: 0.9984 | Train acc: 50.83% | Val loss: 0.9924 | Val acc: 52.14% | LR: 0.000014
Epoch: 041 | Train loss: 0.9984 | Train acc: 51.24% | Val loss: 1.0016 | Val acc: 52.28% | LR: 0.000014
Epoch: 042 | Train loss: 0.9982 | Train acc: 50.64% | Val loss: 0.9922 | Val acc: 52.28% | LR: 0.000014
Epoch: 043 | Train loss: 0.9979 | Train acc: 50.99% | Val loss: 0.9937 | Val acc: 52.32% | LR: 0.000013
Epoch: 044 | Train loss: 0.9980 | Train acc: 51.07% | Val loss: 0.9932 | Val acc: 52.37% | LR: 0.000013
Epoch: 045 | Train loss: 0.9968 | Train acc: 51.51% | Val loss: 1.0062 | Val acc: 52.27% | LR: 0.000013
Epoch: 046 | Train loss: 0.9969 | Train acc: 50.72% | Val loss: 1.0279 | Val acc: 52.22% | LR: 0.000013
Epoch: 047 | Train loss: 1.0013 | Train acc: 50.66% | Val loss: 1.0019 | Val acc: 52.14% | LR: 0.000013
Epoch: 048 | Train loss: 0.9973 | Train acc: 51.00% | Val loss: 1.0478 | Val acc: 52.16% | LR: 0.000013
Epoch: 049 | Train loss: 0.9996 | Train acc: 50.82% | Val loss: 1.0125 | Val acc: 52.06% | LR: 0.000013
Epoch: 050 | Train loss: 1.0084 | Train acc: 50.92% | Val loss: 0.9976 | Val acc: 50.99% | LR: 0.000012
Epoch: 051 | Train loss: 1.0045 | Train acc: 50.15% | Val loss: 0.9928 | Val acc: 51.94% | LR: 0.000012
Epoch: 052 | Train loss: 1.0027 | Train acc: 50.22% | Val loss: 0.9943 | Val acc: 52.32% | LR: 0.000012
Epoch: 053 | Train loss: 1.0014 | Train acc: 50.49% | Val loss: 0.9932 | Val acc: 51.98% | LR: 0.000012
Epoch: 054 | Train loss: 0.9995 | Train acc: 50.65% | Val loss: 1.0309 | Val acc: 51.29% | LR: 0.000012
Epoch: 055 | Train loss: 0.9995 | Train acc: 50.38% | Val loss: 0.9950 | Val acc: 51.86% | LR: 0.000012
Epoch: 056 | Train loss: 0.9990 | Train acc: 50.80% | Val loss: 0.9957 | Val acc: 51.99% | LR: 0.000012

[I 2025-09-23 17:46:40,994] Trial 82 finished with value: 0.5175092339515686 and parameters: {'lr': 1.6426122219400726e-05, 'hidden_size': 94, 'dropout': 0.28271576881498117, 'weight_decay': 4.811830530684072e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0015 | Train acc: 49.81% | Val loss: 1.0270 | Val acc: 45.91% | LR: 0.000014
Epoch: 001 | Train loss: 1.0008 | Train acc: 49.45% | Val loss: 1.0058 | Val acc: 45.85% | LR: 0.000014
Epoch: 002 | Train loss: 1.0018 | Train acc: 49.46% | Val loss: 1.0062 | Val acc: 45.99% | LR: 0.000014
Epoch: 003 | Train loss: 1.0010 | Train acc: 49.59% | Val loss: 1.0082 | Val acc: 45.99% | LR: 0.000014
Epoch: 004 | Train loss: 1.0099 | Train acc: 49.81% | Val loss: 1.0069 | Val acc: 45.89% | LR: 0.000014
Epoch: 005 | Train loss: 1.0004 | Train acc: 49.26% | Val loss: 1.0063 | Val acc: 45.93% | LR: 0.000014
Epoch: 006 | Train loss: 1.0000 | Train acc: 49.47% | Val loss: 1.0053 | Val acc: 46.06% | LR: 0.000014
Epoch: 007 | Train loss: 1.0018 | Train acc: 49.70% | Val loss: 1.0053 | Val acc: 46.22% | LR: 0.000013
Epoch: 008 | Train loss: 1.0001 | Train acc: 49.94% | Val loss: 1.0050 | Val acc: 46.09% | LR: 0.000013
Epoch: 009 | Train loss: 0.9998 | Train acc: 50.25% | Val loss: 1.0064 | Val acc: 46.11% | LR: 0.000013
Epoch: 010 | Train loss: 0.9998 | Train acc: 49.88% | Val loss: 1.0089 | Val acc: 45.97% | LR: 0.000013
Epoch: 011 | Train loss: 1.0006 | Train acc: 48.92% | Val loss: 1.0095 | Val acc: 46.03% | LR: 0.000013
Epoch: 012 | Train loss: 1.0000 | Train acc: 50.36% | Val loss: 1.0241 | Val acc: 46.04% | LR: 0.000013
Epoch: 013 | Train loss: 1.0004 | Train acc: 49.03% | Val loss: 1.0065 | Val acc: 46.01% | LR: 0.000013
Epoch: 014 | Train loss: 1.0000 | Train acc: 49.17% | Val loss: 1.0054 | Val acc: 46.06% | LR: 0.000013
Epoch: 015 | Train loss: 0.9997 | Train acc: 49.75% | Val loss: 1.0072 | Val acc: 46.05% | LR: 0.000013
Epoch: 016 | Train loss: 0.9999 | Train acc: 50.06% | Val loss: 1.0051 | Val acc: 46.20% | LR: 0.000013
Epoch: 017 | Train loss: 0.9994 | Train acc: 50.21% | Val loss: 1.0064 | Val acc: 46.06% | LR: 0.000013
Epoch: 018 | Train loss: 1.0001 | Train acc: 49.74% | Val loss: 1.0084 | Val acc: 46.04% | LR: 0.000013
Epoch: 019 | Train loss: 0.9996 | Train acc: 49.98% | Val loss: 1.0065 | Val acc: 45.99% | LR: 0.000013
Epoch: 020 | Train loss: 1.0102 | Train acc: 50.32% | Val loss: 1.0063 | Val acc: 45.93% | LR: 0.000013
Epoch: 021 | Train loss: 0.9996 | Train acc: 50.28% | Val loss: 1.0064 | Val acc: 45.93% | LR: 0.000013
Epoch: 022 | Train loss: 0.9997 | Train acc: 50.12% | Val loss: 1.0078 | Val acc: 45.95% | LR: 0.000013
Epoch: 023 | Train loss: 0.9999 | Train acc: 49.95% | Val loss: 1.0056 | Val acc: 45.99% | LR: 0.000013
Epoch: 024 | Train loss: 0.9993 | Train acc: 50.44% | Val loss: 1.0083 | Val acc: 45.91% | LR: 0.000013
Epoch: 025 | Train loss: 1.0000 | Train acc: 50.15% | Val loss: 1.0052 | Val acc: 45.97% | LR: 0.000013
Epoch: 026 | Train loss: 0.9990 | Train acc: 50.70% | Val loss: 1.0059 | Val acc: 45.95% | LR: 0.000013
Epoch: 027 | Train loss: 1.0000 | Train acc: 50.06% | Val loss: 1.0068 | Val acc: 45.91% | LR: 0.000013
Epoch: 028 | Train loss: 0.9993 | Train acc: 50.86% | Val loss: 1.0060 | Val acc: 45.91% | LR: 0.000012
Epoch: 029 | Train loss: 1.0000 | Train acc: 50.07% | Val loss: 1.0058 | Val acc: 46.01% | LR: 0.000012
Epoch: 030 | Train loss: 0.9995 | Train acc: 50.52% | Val loss: 1.0064 | Val acc: 45.81% | LR: 0.000012
Epoch: 031 | Train loss: 0.9988 | Train acc: 50.87% | Val loss: 1.0057 | Val acc: 46.01% | LR: 0.000012
Epoch: 032 | Train loss: 0.9988 | Train acc: 50.87% | Val loss: 1.0058 | Val acc: 45.99% | LR: 0.000012
Epoch: 033 | Train loss: 0.9995 | Train acc: 50.67% | Val loss: 1.0288 | Val acc: 46.05% | LR: 0.000012
Epoch: 034 | Train loss: 1.0003 | Train acc: 50.20% | Val loss: 1.0045 | Val acc: 46.20% | LR: 0.000012
Epoch: 035 | Train loss: 0.9995 | Train acc: 50.39% | Val loss: 1.0061 | Val acc: 45.95% | LR: 0.000012
Epoch: 036 | Train loss: 0.9983 | Train acc: 50.87% | Val loss: 1.0061 | Val acc: 45.89% | LR: 0.000012
Epoch: 037 | Train loss: 0.9995 | Train acc: 50.32% | Val loss: 1.0055 | Val acc: 46.09% | LR: 0.000012
Epoch: 038 | Train loss: 0.9985 | Train acc: 50.78% | Val loss: 1.0047 | Val acc: 46.05% | LR: 0.000012
Epoch: 039 | Train loss: 0.9999 | Train acc: 50.23% | Val loss: 1.0063 | Val acc: 45.97% | LR: 0.000011
Epoch: 040 | Train loss: 0.9986 | Train acc: 50.67% | Val loss: 1.0058 | Val acc: 46.01% | LR: 0.000011
Epoch: 041 | Train loss: 0.9989 | Train acc: 50.49% | Val loss: 1.0057 | Val acc: 46.05% | LR: 0.000011
Epoch: 042 | Train loss: 0.9994 | Train acc: 50.34% | Val loss: 1.0066 | Val acc: 46.09% | LR: 0.000011
Epoch: 043 | Train loss: 0.9983 | Train acc: 50.77% | Val loss: 1.0056 | Val acc: 46.09% | LR: 0.000011
Epoch: 044 | Train loss: 0.9977 | Train acc: 50.94% | Val loss: 1.0081 | Val acc: 46.03% | LR: 0.000011
Epoch: 045 | Train loss: 0.9984 | Train acc: 50.59% | Val loss: 1.0069 | Val acc: 45.93% | LR: 0.000011
Epoch: 046 | Train loss: 0.9991 | Train acc: 50.32% | Val loss: 1.0054 | Val acc: 46.03% | LR: 0.000011
Epoch: 047 | Train loss: 0.9985 | Train acc: 50.60% | Val loss: 1.0163 | Val acc: 45.99% | LR: 0.000011
Epoch: 048 | Train loss: 0.9994 | Train acc: 50.15% | Val loss: 1.0055 | Val acc: 46.07% | LR: 0.000011
Epoch: 049 | Train loss: 0.9991 | Train acc: 50.32% | Val loss: 1.0054 | Val acc: 46.07% | LR: 0.000010
Epoch: 050 | Train loss: 0.9973 | Train acc: 51.03% | Val loss: 1.0072 | Val acc: 45.93% | LR: 0.000010
Epoch: 051 | Train loss: 0.9976 | Train acc: 50.95% | Val loss: 1.0091 | Val acc: 46.03% | LR: 0.000010
Epoch: 052 | Train loss: 0.9993 | Train acc: 50.24% | Val loss: 1.0061 | Val acc: 45.93% | LR: 0.000010
Epoch: 053 | Train loss: 0.9993 | Train acc: 50.31% | Val loss: 1.0065 | Val acc: 46.01% | LR: 0.000010
Epoch: 054 | Train loss: 0.9984 | Train acc: 50.43% | Val loss: 1.0080 | Val acc: 46.01% | LR: 0.000010
Epoch: 055 | Train loss: 0.9976 | Train acc: 50.78% | Val loss: 1.0059 | Val acc: 45.95% | LR: 0.000010
Epoch: 056 | Train loss: 0.9979 | Train acc: 50.60% | Val loss: 1.0059 | Val acc: 45.95% | LR: 0.000010

[I 2025-09-23 17:47:30,968] Trial 83 finished with value: 0.45950507521629336 and parameters: {'lr': 1.3580013484113088e-05, 'hidden_size': 72, 'dropout': 0.2605650528300837, 'weight_decay': 8.177634537390813e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0025 | Train acc: 49.49% | Val loss: 1.0025 | Val acc: 45.66% | LR: 0.000011
Epoch: 001 | Train loss: 1.0034 | Train acc: 49.67% | Val loss: 1.0091 | Val acc: 45.70% | LR: 0.000011
Epoch: 002 | Train loss: 1.0031 | Train acc: 49.21% | Val loss: 1.0023 | Val acc: 45.78% | LR: 0.000011
Epoch: 003 | Train loss: 1.0035 | Train acc: 49.36% | Val loss: 1.0023 | Val acc: 45.76% | LR: 0.000011
Epoch: 004 | Train loss: 1.0022 | Train acc: 49.62% | Val loss: 1.0022 | Val acc: 45.90% | LR: 0.000011
Epoch: 005 | Train loss: 1.0029 | Train acc: 49.62% | Val loss: 1.0023 | Val acc: 45.90% | LR: 0.000011
Epoch: 006 | Train loss: 1.0059 | Train acc: 48.83% | Val loss: 1.0023 | Val acc: 45.92% | LR: 0.000011
Epoch: 007 | Train loss: 1.0000 | Train acc: 49.94% | Val loss: 1.0023 | Val acc: 45.92% | LR: 0.000011
Epoch: 008 | Train loss: 1.0057 | Train acc: 48.88% | Val loss: 1.0023 | Val acc: 45.94% | LR: 0.000011
Epoch: 009 | Train loss: 1.0021 | Train acc: 49.66% | Val loss: 1.0023 | Val acc: 45.96% | LR: 0.000011
Epoch: 010 | Train loss: 1.0038 | Train acc: 49.05% | Val loss: 1.0023 | Val acc: 46.00% | LR: 0.000011
Epoch: 011 | Train loss: 1.0040 | Train acc: 49.06% | Val loss: 1.0023 | Val acc: 46.02% | LR: 0.000011
Epoch: 012 | Train loss: 1.0016 | Train acc: 49.77% | Val loss: 1.0023 | Val acc: 46.10% | LR: 0.000011
Epoch: 013 | Train loss: 1.0018 | Train acc: 49.69% | Val loss: 1.0023 | Val acc: 46.10% | LR: 0.000011
Epoch: 014 | Train loss: 1.0043 | Train acc: 48.81% | Val loss: 1.0023 | Val acc: 46.08% | LR: 0.000011
Epoch: 015 | Train loss: 1.0009 | Train acc: 49.70% | Val loss: 1.0023 | Val acc: 46.06% | LR: 0.000011
Epoch: 016 | Train loss: 1.0011 | Train acc: 49.81% | Val loss: 1.0023 | Val acc: 46.08% | LR: 0.000011
Epoch: 017 | Train loss: 1.0027 | Train acc: 49.16% | Val loss: 1.0023 | Val acc: 46.18% | LR: 0.000011
Epoch: 018 | Train loss: 1.0028 | Train acc: 49.07% | Val loss: 1.0023 | Val acc: 46.12% | LR: 0.000011
Epoch: 019 | Train loss: 1.0023 | Train acc: 49.36% | Val loss: 1.0022 | Val acc: 46.10% | LR: 0.000011
Epoch: 020 | Train loss: 1.0016 | Train acc: 49.47% | Val loss: 1.0023 | Val acc: 46.04% | LR: 0.000011
Epoch: 021 | Train loss: 1.0023 | Train acc: 49.22% | Val loss: 1.0022 | Val acc: 46.06% | LR: 0.000011
Epoch: 022 | Train loss: 1.0007 | Train acc: 49.74% | Val loss: 1.0022 | Val acc: 46.00% | LR: 0.000011
Epoch: 023 | Train loss: 1.0012 | Train acc: 49.50% | Val loss: 1.0022 | Val acc: 46.09% | LR: 0.000011
Epoch: 024 | Train loss: 1.0020 | Train acc: 49.43% | Val loss: 1.0022 | Val acc: 46.13% | LR: 0.000011
Epoch: 025 | Train loss: 1.0009 | Train acc: 49.57% | Val loss: 1.0022 | Val acc: 46.09% | LR: 0.000011
Epoch: 026 | Train loss: 1.0021 | Train acc: 49.65% | Val loss: 1.0021 | Val acc: 46.27% | LR: 0.000010
Epoch: 027 | Train loss: 1.0025 | Train acc: 50.05% | Val loss: 1.0021 | Val acc: 46.27% | LR: 0.000010
Epoch: 028 | Train loss: 1.0013 | Train acc: 49.95% | Val loss: 1.0021 | Val acc: 46.27% | LR: 0.000010
Epoch: 029 | Train loss: 1.0647 | Train acc: 50.31% | Val loss: 1.0021 | Val acc: 46.23% | LR: 0.000010
Epoch: 030 | Train loss: 0.9976 | Train acc: 50.60% | Val loss: 1.0021 | Val acc: 46.19% | LR: 0.000010
Epoch: 031 | Train loss: 0.9995 | Train acc: 50.26% | Val loss: 1.0021 | Val acc: 46.23% | LR: 0.000010
Epoch: 032 | Train loss: 0.9988 | Train acc: 50.09% | Val loss: 1.0021 | Val acc: 46.25% | LR: 0.000010
Epoch: 033 | Train loss: 0.9986 | Train acc: 49.66% | Val loss: 1.0020 | Val acc: 46.23% | LR: 0.000010
Epoch: 034 | Train loss: 1.0590 | Train acc: 49.96% | Val loss: 1.0020 | Val acc: 46.27% | LR: 0.000010
Epoch: 035 | Train loss: 1.0045 | Train acc: 49.95% | Val loss: 1.0021 | Val acc: 46.21% | LR: 0.000010
Epoch: 036 | Train loss: 1.0037 | Train acc: 50.02% | Val loss: 1.0021 | Val acc: 46.23% | LR: 0.000010
Epoch: 037 | Train loss: 1.0017 | Train acc: 49.90% | Val loss: 1.0021 | Val acc: 46.39% | LR: 0.000010
Epoch: 038 | Train loss: 0.9986 | Train acc: 50.20% | Val loss: 1.0021 | Val acc: 46.33% | LR: 0.000010
Epoch: 039 | Train loss: 1.0007 | Train acc: 49.96% | Val loss: 1.0020 | Val acc: 46.51% | LR: 0.000010
Epoch: 040 | Train loss: 1.0001 | Train acc: 50.08% | Val loss: 1.0021 | Val acc: 46.56% | LR: 0.000010
Epoch: 041 | Train loss: 1.0031 | Train acc: 49.37% | Val loss: 1.0020 | Val acc: 46.45% | LR: 0.000009
Epoch: 042 | Train loss: 1.0451 | Train acc: 50.25% | Val loss: 1.0020 | Val acc: 46.45% | LR: 0.000009
Epoch: 043 | Train loss: 1.0096 | Train acc: 49.96% | Val loss: 1.0020 | Val acc: 46.41% | LR: 0.000009
Epoch: 044 | Train loss: 1.0008 | Train acc: 49.94% | Val loss: 1.0020 | Val acc: 46.43% | LR: 0.000009
Epoch: 045 | Train loss: 1.0087 | Train acc: 50.04% | Val loss: 1.0020 | Val acc: 46.45% | LR: 0.000009
Epoch: 046 | Train loss: 1.0832 | Train acc: 50.05% | Val loss: 1.0020 | Val acc: 46.45% | LR: 0.000009
Epoch: 047 | Train loss: 1.0160 | Train acc: 50.58% | Val loss: 1.0020 | Val acc: 46.43% | LR: 0.000009
Epoch: 048 | Train loss: 1.0119 | Train acc: 49.68% | Val loss: 1.0020 | Val acc: 46.47% | LR: 0.000009
Epoch: 049 | Train loss: 1.0036 | Train acc: 49.78% | Val loss: 1.0020 | Val acc: 46.47% | LR: 0.000009
Epoch: 050 | Train loss: 1.0380 | Train acc: 49.90% | Val loss: 1.0020 | Val acc: 46.51% | LR: 0.000009
Epoch: 051 | Train loss: 1.0198 | Train acc: 49.82% | Val loss: 1.0020 | Val acc: 46.47% | LR: 0.000009
Epoch: 052 | Train loss: 1.0026 | Train acc: 49.60% | Val loss: 1.0020 | Val acc: 46.43% | LR: 0.000008
Epoch: 053 | Train loss: 1.0899 | Train acc: 49.66% | Val loss: 1.0020 | Val acc: 46.51% | LR: 0.000008
Epoch: 054 | Train loss: 1.0128 | Train acc: 49.80% | Val loss: 1.0020 | Val acc: 46.51% | LR: 0.000008
Epoch: 055 | Train loss: 1.0154 | Train acc: 50.02% | Val loss: 1.0020 | Val acc: 46.51% | LR: 0.000008
Epoch: 056 | Train loss: 0.9992 | Train acc: 49.76% | Val loss: 1.0020 | Val acc: 46.53% | LR: 0.000008
Epoch: 057 | Train loss: 1.0277 | Train acc: 49.50% | Val loss: 1.0020 | Val acc: 46.59% | LR: 0.000008
Epoch: 058 | Train loss: 1.0020 | Train acc: 49.59% | Val loss: 1.0020 | Val acc: 46.58% | LR: 0.000008
Epoch: 059 | Train loss: 1.0052 | Train acc: 50.00% | Val loss: 1.0020 | Val acc: 46.60% | LR: 0.000008
Epoch: 060 | Train loss: 1.0132 | Train acc: 49.70% | Val loss: 1.0020 | Val acc: 46.62% | LR: 0.000008
Epoch: 061 | Train loss: 0.9988 | Train acc: 49.64% | Val loss: 1.0020 | Val acc: 46.62% | LR: 0.000008
Epoch: 062 | Train loss: 1.0006 | Train acc: 50.26% | Val loss: 1.0019 | Val acc: 46.60% | LR: 0.000007
Epoch: 063 | Train loss: 1.0185 | Train acc: 50.01% | Val loss: 1.0019 | Val acc: 46.60% | LR: 0.000007
Epoch: 064 | Train loss: 1.0025 | Train acc: 50.63% | Val loss: 1.0020 | Val acc: 46.53% | LR: 0.000007
Epoch: 065 | Train loss: 1.0110 | Train acc: 50.93% | Val loss: 1.0020 | Val acc: 46.53% | LR: 0.000007
Epoch: 066 | Train loss: 1.0136 | Train acc: 49.52% | Val loss: 1.0019 | Val acc: 46.55% | LR: 0.000007
Epoch: 067 | Train loss: 0.9994 | Train acc: 49.31% | Val loss: 1.0019 | Val acc: 46.55% | LR: 0.000007
Epoch: 068 | Train loss: 1.0032 | Train acc: 50.00% | Val loss: 1.0019 | Val acc: 46.56% | LR: 0.000007
Epoch: 069 | Train loss: 1.0033 | Train acc: 49.93% | Val loss: 1.0019 | Val acc: 46.56% | LR: 0.000007
Epoch: 070 | Train loss: 1.0071 | Train acc: 49.62% | Val loss: 1.0019 | Val acc: 46.55% | LR: 0.000007
Epoch: 071 | Train loss: 1.0023 | Train acc: 49.51% | Val loss: 1.0019 | Val acc: 46.53% | LR: 0.000006
Epoch: 072 | Train loss: 0.9979 | Train acc: 49.83% | Val loss: 1.0019 | Val acc: 46.56% | LR: 0.000006
Epoch: 073 | Train loss: 1.0145 | Train acc: 49.58% | Val loss: 1.0019 | Val acc: 46.58% | LR: 0.000006
Epoch: 074 | Train loss: 1.0946 | Train acc: 49.83% | Val loss: 1.0019 | Val acc: 46.58% | LR: 0.000006
Epoch: 075 | Train loss: 1.0084 | Train acc: 49.54% | Val loss: 1.0019 | Val acc: 46.58% | LR: 0.000006
Epoch: 076 | Train loss: 1.0279 | Train acc: 49.97% | Val loss: 1.0019 | Val acc: 46.58% | LR: 0.000006
Epoch: 077 | Train loss: 1.0278 | Train acc: 50.05% | Val loss: 1.0019 | Val acc: 46.58% | LR: 0.000006
Epoch: 078 | Train loss: 1.0160 | Train acc: 49.83% | Val loss: 1.0019 | Val acc: 46.58% | LR: 0.000006
Epoch: 079 | Train loss: 1.0189 | Train acc: 49.40% | Val loss: 1.0019 | Val acc: 46.58% | LR: 0.000006
Epoch: 080 | Train loss: 0.9998 | Train acc: 50.52% | Val loss: 1.0019 | Val acc: 46.60% | LR: 0.000005
Epoch: 081 | Train loss: 1.0028 | Train acc: 50.46% | Val loss: 1.0019 | Val acc: 46.62% | LR: 0.000005
Epoch: 082 | Train loss: 1.0068 | Train acc: 50.13% | Val loss: 1.0019 | Val acc: 46.62% | LR: 0.000005
Epoch: 083 | Train loss: 1.0024 | Train acc: 50.26% | Val loss: 1.0019 | Val acc: 46.64% | LR: 0.000005
Epoch: 084 | Train loss: 1.0118 | Train acc: 50.08% | Val loss: 1.0019 | Val acc: 46.62% | LR: 0.000005
Epoch: 085 | Train loss: 0.9986 | Train acc: 50.06% | Val loss: 1.0019 | Val acc: 46.60% | LR: 0.000005
Epoch: 086 | Train loss: 0.9988 | Train acc: 49.67% | Val loss: 1.0019 | Val acc: 46.66% | LR: 0.000005
Epoch: 087 | Train loss: 1.0937 | Train acc: 50.18% | Val loss: 1.0019 | Val acc: 46.64% | LR: 0.000005
Epoch: 088 | Train loss: 0.9990 | Train acc: 50.34% | Val loss: 1.0019 | Val acc: 46.66% | LR: 0.000005
Epoch: 089 | Train loss: 1.0126 | Train acc: 49.73% | Val loss: 1.0019 | Val acc: 46.66% | LR: 0.000005
Epoch: 090 | Train loss: 1.0157 | Train acc: 49.41% | Val loss: 1.0019 | Val acc: 46.68% | LR: 0.000004
Epoch: 091 | Train loss: 1.0016 | Train acc: 50.09% | Val loss: 1.0019 | Val acc: 46.70% | LR: 0.000004
Epoch: 092 | Train loss: 1.0548 | Train acc: 50.41% | Val loss: 1.0019 | Val acc: 46.70% | LR: 0.000004
Epoch: 093 | Train loss: 1.1329 | Train acc: 49.53% | Val loss: 1.0019 | Val acc: 46.74% | LR: 0.000004
Epoch: 094 | Train loss: 0.9997 | Train acc: 49.98% | Val loss: 1.0019 | Val acc: 46.78% | LR: 0.000004
Epoch: 095 | Train loss: 1.0284 | Train acc: 50.34% | Val loss: 1.0019 | Val acc: 46.78% | LR: 0.000004
Epoch: 096 | Train loss: 1.0106 | Train acc: 50.10% | Val loss: 1.0019 | Val acc: 46.82% | LR: 0.000004
Epoch: 097 | Train loss: 1.0319 | Train acc: 50.01% | Val loss: 1.0019 | Val acc: 46.82% | LR: 0.000004
Epoch: 098 | Train loss: 1.0598 | Train acc: 50.22% | Val loss: 1.0019 | Val acc: 46.82% | LR: 0.000004
Epoch: 099 | Train loss: 1.0061 | Train acc: 50.24% | Val loss: 1.0019 | Val acc: 46.84% | LR: 0.000004
Epoch: 100 | Train loss: 1.0119 | Train acc: 49.97% | Val loss: 1.0019 | Val acc: 46.84% | LR: 0.000003
Epoch: 101 | Train loss: 1.0399 | Train acc: 49.53% | Val loss: 1.0019 | Val acc: 46.84% | LR: 0.000003
Epoch: 102 | Train loss: 1.0128 | Train acc: 50.55% | Val loss: 1.0019 | Val acc: 46.80% | LR: 0.000003
Epoch: 103 | Train loss: 1.0265 | Train acc: 50.06% | Val loss: 1.0019 | Val acc: 46.74% | LR: 0.000003
Epoch: 104 | Train loss: 1.0065 | Train acc: 50.02% | Val loss: 1.0019 | Val acc: 46.84% | LR: 0.000003
Epoch: 105 | Train loss: 0.9988 | Train acc: 50.12% | Val loss: 1.0019 | Val acc: 46.74% | LR: 0.000003
Epoch: 106 | Train loss: 1.0140 | Train acc: 49.42% | Val loss: 1.0019 | Val acc: 46.74% | LR: 0.000003
Epoch: 107 | Train loss: 1.0330 | Train acc: 50.25% | Val loss: 1.0019 | Val acc: 46.74% | LR: 0.000003
Epoch: 108 | Train loss: 1.0738 | Train acc: 50.63% | Val loss: 1.0019 | Val acc: 46.74% | LR: 0.000003
Epoch: 109 | Train loss: 1.0225 | Train acc: 50.24% | Val loss: 1.0019 | Val acc: 46.67% | LR: 0.000003
Epoch: 110 | Train loss: 1.0196 | Train acc: 50.15% | Val loss: 1.0018 | Val acc: 46.67% | LR: 0.000003
Epoch: 111 | Train loss: 1.0272 | Train acc: 49.55% | Val loss: 1.0018 | Val acc: 46.67% | LR: 0.000003
Epoch: 112 | Train loss: 1.0491 | Train acc: 50.27% | Val loss: 1.0018 | Val acc: 46.67% | LR: 0.000002
Epoch: 113 | Train loss: 1.0536 | Train acc: 50.12% | Val loss: 1.0018 | Val acc: 46.67% | LR: 0.000002
Epoch: 114 | Train loss: 1.0158 | Train acc: 50.21% | Val loss: 1.0018 | Val acc: 46.67% | LR: 0.000002
Epoch: 115 | Train loss: 1.0039 | Train acc: 50.48% | Val loss: 1.0018 | Val acc: 46.67% | LR: 0.000002
Epoch: 116 | Train loss: 1.0010 | Train acc: 49.62% | Val loss: 1.0018 | Val acc: 46.67% | LR: 0.000002
Epoch: 117 | Train loss: 1.0161 | Train acc: 50.26% | Val loss: 1.0018 | Val acc: 46.67% | LR: 0.000002
Epoch: 118 | Train loss: 1.0068 | Train acc: 50.11% | Val loss: 1.0018 | Val acc: 46.67% | LR: 0.000002
Epoch: 119 | Train loss: 1.0315 | Train acc: 49.60% | Val loss: 1.0018 | Val acc: 46.67% | LR: 0.000002
Epoch: 120 | Train loss: 1.0466 | Train acc: 50.34% | Val loss: 1.0018 | Val acc: 46.67% | LR: 0.000002
Epoch: 121 | Train loss: 1.0241 | Train acc: 50.37% | Val loss: 1.0018 | Val acc: 46.67% | LR: 0.000002
Epoch: 122 | Train loss: 1.0019 | Train acc: 49.53% | Val loss: 1.0018 | Val acc: 46.67% | LR: 0.000002
Epoch: 123 | Train loss: 0.9989 | Train acc: 50.05% | Val loss: 1.0018 | Val acc: 46.67% | LR: 0.000002
Epoch: 124 | Train loss: 1.0141 | Train acc: 49.80% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000002
Epoch: 125 | Train loss: 1.0165 | Train acc: 50.44% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000002
Epoch: 126 | Train loss: 1.0198 | Train acc: 50.16% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000002
Epoch: 127 | Train loss: 1.0131 | Train acc: 49.71% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000002
Epoch: 128 | Train loss: 1.0164 | Train acc: 49.91% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001
Epoch: 129 | Train loss: 1.0251 | Train acc: 50.38% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001
Epoch: 130 | Train loss: 1.0176 | Train acc: 49.30% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001
Epoch: 131 | Train loss: 1.0144 | Train acc: 49.88% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001
Epoch: 132 | Train loss: 1.0251 | Train acc: 49.24% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001
Epoch: 133 | Train loss: 1.0342 | Train acc: 49.34% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001
Epoch: 134 | Train loss: 1.0304 | Train acc: 50.10% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001
Epoch: 135 | Train loss: 1.0283 | Train acc: 49.31% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001
Epoch: 136 | Train loss: 0.9957 | Train acc: 50.57% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001
Epoch: 137 | Train loss: 1.0043 | Train acc: 49.36% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001
Epoch: 138 | Train loss: 1.0074 | Train acc: 49.82% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001
Epoch: 139 | Train loss: 1.0061 | Train acc: 49.59% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001
Epoch: 140 | Train loss: 1.0167 | Train acc: 50.56% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001
Epoch: 141 | Train loss: 1.0442 | Train acc: 50.00% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001
Epoch: 142 | Train loss: 1.0066 | Train acc: 49.88% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001
Epoch: 143 | Train loss: 1.0158 | Train acc: 49.78% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001
Epoch: 144 | Train loss: 1.0033 | Train acc: 50.10% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001
Epoch: 145 | Train loss: 1.0065 | Train acc: 50.39% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001
Epoch: 146 | Train loss: 1.0111 | Train acc: 49.81% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001
Epoch: 147 | Train loss: 1.0249 | Train acc: 49.17% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001
Epoch: 148 | Train loss: 1.0667 | Train acc: 49.62% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001
Epoch: 149 | Train loss: 1.0184 | Train acc: 50.12% | Val loss: 1.0018 | Val acc: 46.70% | LR: 0.000001

[I 2025-09-23 17:49:28,521] Trial 84 finished with value: 0.4670421898365021 and parameters: {'lr': 1.1289494850039936e-05, 'hidden_size': 88, 'dropout': 0.2407378889342084, 'weight_decay': 2.757569685399904e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0063 | Train acc: 50.32% | Val loss: 1.0109 | Val acc: 47.49% | LR: 0.000019
Epoch: 001 | Train loss: 1.0029 | Train acc: 49.75% | Val loss: 1.0141 | Val acc: 47.04% | LR: 0.000019
Epoch: 002 | Train loss: 0.9995 | Train acc: 50.08% | Val loss: 1.0091 | Val acc: 47.20% | LR: 0.000019
Epoch: 003 | Train loss: 0.9994 | Train acc: 50.44% | Val loss: 1.0055 | Val acc: 47.40% | LR: 0.000019
Epoch: 004 | Train loss: 1.0007 | Train acc: 50.28% | Val loss: 1.0049 | Val acc: 47.34% | LR: 0.000019
Epoch: 005 | Train loss: 1.0020 | Train acc: 50.11% | Val loss: 1.0048 | Val acc: 47.44% | LR: 0.000019
Epoch: 006 | Train loss: 0.9992 | Train acc: 50.50% | Val loss: 1.0048 | Val acc: 47.70% | LR: 0.000019
Epoch: 007 | Train loss: 1.0018 | Train acc: 50.15% | Val loss: 1.0044 | Val acc: 47.62% | LR: 0.000019
Epoch: 008 | Train loss: 1.0004 | Train acc: 50.60% | Val loss: 1.0051 | Val acc: 47.86% | LR: 0.000019
Epoch: 009 | Train loss: 0.9979 | Train acc: 51.00% | Val loss: 1.0047 | Val acc: 47.71% | LR: 0.000019
Epoch: 010 | Train loss: 0.9993 | Train acc: 50.55% | Val loss: 1.0080 | Val acc: 47.72% | LR: 0.000019
Epoch: 011 | Train loss: 1.0002 | Train acc: 50.40% | Val loss: 1.0064 | Val acc: 47.98% | LR: 0.000019
Epoch: 012 | Train loss: 0.9988 | Train acc: 50.60% | Val loss: 1.0243 | Val acc: 47.87% | LR: 0.000019
Epoch: 013 | Train loss: 0.9997 | Train acc: 50.21% | Val loss: 1.0060 | Val acc: 47.68% | LR: 0.000018
Epoch: 014 | Train loss: 0.9981 | Train acc: 50.48% | Val loss: 1.0272 | Val acc: 47.82% | LR: 0.000018
Epoch: 015 | Train loss: 1.0022 | Train acc: 50.26% | Val loss: 1.0044 | Val acc: 47.67% | LR: 0.000018
Epoch: 016 | Train loss: 0.9979 | Train acc: 50.53% | Val loss: 1.0098 | Val acc: 47.52% | LR: 0.000018
Epoch: 017 | Train loss: 1.0002 | Train acc: 50.32% | Val loss: 1.0227 | Val acc: 47.65% | LR: 0.000018
Epoch: 018 | Train loss: 0.9974 | Train acc: 50.99% | Val loss: 1.0088 | Val acc: 47.74% | LR: 0.000018
Epoch: 019 | Train loss: 1.0018 | Train acc: 50.11% | Val loss: 1.0079 | Val acc: 47.62% | LR: 0.000018
Epoch: 020 | Train loss: 1.0008 | Train acc: 50.21% | Val loss: 1.0106 | Val acc: 47.69% | LR: 0.000018
Epoch: 021 | Train loss: 1.0011 | Train acc: 49.66% | Val loss: 1.0045 | Val acc: 47.55% | LR: 0.000018
Epoch: 022 | Train loss: 0.9998 | Train acc: 50.21% | Val loss: 1.0046 | Val acc: 47.75% | LR: 0.000018
Epoch: 023 | Train loss: 1.0007 | Train acc: 50.18% | Val loss: 1.0075 | Val acc: 47.51% | LR: 0.000018
Epoch: 024 | Train loss: 1.0003 | Train acc: 50.21% | Val loss: 1.0052 | Val acc: 47.61% | LR: 0.000018
Epoch: 025 | Train loss: 0.9980 | Train acc: 50.50% | Val loss: 1.0092 | Val acc: 47.80% | LR: 0.000018
Epoch: 026 | Train loss: 1.0044 | Train acc: 50.17% | Val loss: 1.0086 | Val acc: 47.69% | LR: 0.000017
Epoch: 027 | Train loss: 1.0006 | Train acc: 50.11% | Val loss: 1.0070 | Val acc: 47.68% | LR: 0.000017
Epoch: 028 | Train loss: 0.9989 | Train acc: 50.19% | Val loss: 1.0083 | Val acc: 47.54% | LR: 0.000017
Epoch: 029 | Train loss: 1.0021 | Train acc: 49.84% | Val loss: 1.0046 | Val acc: 47.65% | LR: 0.000017
Epoch: 030 | Train loss: 0.9980 | Train acc: 50.56% | Val loss: 1.0054 | Val acc: 47.56% | LR: 0.000017
Epoch: 031 | Train loss: 0.9982 | Train acc: 50.51% | Val loss: 1.0297 | Val acc: 47.61% | LR: 0.000017
Epoch: 032 | Train loss: 1.0005 | Train acc: 50.05% | Val loss: 1.0094 | Val acc: 47.70% | LR: 0.000017
Epoch: 033 | Train loss: 1.0036 | Train acc: 50.37% | Val loss: 1.0105 | Val acc: 47.66% | LR: 0.000017
Epoch: 034 | Train loss: 0.9979 | Train acc: 50.63% | Val loss: 1.0072 | Val acc: 47.56% | LR: 0.000017
Epoch: 035 | Train loss: 0.9989 | Train acc: 50.40% | Val loss: 1.0042 | Val acc: 47.82% | LR: 0.000016
Epoch: 036 | Train loss: 0.9954 | Train acc: 51.12% | Val loss: 1.0071 | Val acc: 47.71% | LR: 0.000016
Epoch: 037 | Train loss: 1.0080 | Train acc: 50.17% | Val loss: 1.0040 | Val acc: 47.85% | LR: 0.000016
Epoch: 038 | Train loss: 0.9987 | Train acc: 50.73% | Val loss: 1.0122 | Val acc: 47.80% | LR: 0.000016
Epoch: 039 | Train loss: 1.0095 | Train acc: 50.13% | Val loss: 1.0055 | Val acc: 47.52% | LR: 0.000016
Epoch: 040 | Train loss: 0.9984 | Train acc: 50.86% | Val loss: 1.0060 | Val acc: 47.59% | LR: 0.000016
Epoch: 041 | Train loss: 0.9990 | Train acc: 50.31% | Val loss: 1.0037 | Val acc: 47.62% | LR: 0.000016
Epoch: 042 | Train loss: 1.0011 | Train acc: 49.72% | Val loss: 1.0076 | Val acc: 47.61% | LR: 0.000015
Epoch: 043 | Train loss: 1.0014 | Train acc: 50.16% | Val loss: 1.0056 | Val acc: 47.94% | LR: 0.000015
Epoch: 044 | Train loss: 0.9986 | Train acc: 50.28% | Val loss: 1.0051 | Val acc: 47.58% | LR: 0.000015
Epoch: 045 | Train loss: 0.9959 | Train acc: 50.77% | Val loss: 1.0043 | Val acc: 47.76% | LR: 0.000015
Epoch: 046 | Train loss: 0.9968 | Train acc: 50.86% | Val loss: 1.0046 | Val acc: 47.65% | LR: 0.000015
Epoch: 047 | Train loss: 0.9984 | Train acc: 50.09% | Val loss: 1.0054 | Val acc: 47.69% | LR: 0.000015
Epoch: 048 | Train loss: 0.9972 | Train acc: 50.49% | Val loss: 1.0041 | Val acc: 47.74% | LR: 0.000015
Epoch: 049 | Train loss: 0.9977 | Train acc: 50.38% | Val loss: 1.0046 | Val acc: 47.64% | LR: 0.000014
Epoch: 050 | Train loss: 0.9976 | Train acc: 50.35% | Val loss: 1.0042 | Val acc: 47.56% | LR: 0.000014
Epoch: 051 | Train loss: 0.9995 | Train acc: 49.93% | Val loss: 1.0041 | Val acc: 47.72% | LR: 0.000014
Epoch: 052 | Train loss: 0.9979 | Train acc: 50.30% | Val loss: 1.0042 | Val acc: 47.76% | LR: 0.000014
Epoch: 053 | Train loss: 0.9988 | Train acc: 50.24% | Val loss: 1.0049 | Val acc: 47.57% | LR: 0.000014
Epoch: 054 | Train loss: 0.9969 | Train acc: 50.40% | Val loss: 1.0042 | Val acc: 47.71% | LR: 0.000014
Epoch: 055 | Train loss: 0.9963 | Train acc: 50.75% | Val loss: 1.0034 | Val acc: 47.62% | LR: 0.000013
Epoch: 056 | Train loss: 0.9982 | Train acc: 50.24% | Val loss: 1.0046 | Val acc: 47.56% | LR: 0.000013
Epoch: 057 | Train loss: 0.9994 | Train acc: 49.87% | Val loss: 1.0053 | Val acc: 47.45% | LR: 0.000013
Epoch: 058 | Train loss: 0.9977 | Train acc: 50.32% | Val loss: 1.0044 | Val acc: 47.50% | LR: 0.000013
Epoch: 059 | Train loss: 0.9981 | Train acc: 50.22% | Val loss: 1.0052 | Val acc: 47.58% | LR: 0.000013
Epoch: 060 | Train loss: 1.0002 | Train acc: 50.15% | Val loss: 1.0045 | Val acc: 47.58% | LR: 0.000013

[I 2025-09-23 17:50:22,940] Trial 85 finished with value: 0.4745567381381989 and parameters: {'lr': 1.8845661673006333e-05, 'hidden_size': 79, 'dropout': 0.2898521531707152, 'weight_decay': 3.375760060780711e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9991 | Train acc: 50.46% | Val loss: 0.9986 | Val acc: 51.41% | LR: 0.000027
Epoch: 001 | Train loss: 0.9984 | Train acc: 50.56% | Val loss: 1.0005 | Val acc: 51.17% | LR: 0.000027
Epoch: 002 | Train loss: 0.9993 | Train acc: 50.60% | Val loss: 0.9996 | Val acc: 50.94% | LR: 0.000027
Epoch: 003 | Train loss: 0.9997 | Train acc: 50.14% | Val loss: 0.9993 | Val acc: 51.10% | LR: 0.000027
Epoch: 004 | Train loss: 0.9992 | Train acc: 50.18% | Val loss: 0.9990 | Val acc: 51.28% | LR: 0.000027
Epoch: 005 | Train loss: 0.9980 | Train acc: 50.46% | Val loss: 0.9999 | Val acc: 51.65% | LR: 0.000027
Epoch: 006 | Train loss: 1.0002 | Train acc: 50.17% | Val loss: 1.0001 | Val acc: 51.77% | LR: 0.000027
Epoch: 007 | Train loss: 0.9975 | Train acc: 50.50% | Val loss: 0.9991 | Val acc: 51.83% | LR: 0.000027
Epoch: 008 | Train loss: 0.9973 | Train acc: 50.52% | Val loss: 1.0007 | Val acc: 51.76% | LR: 0.000027
Epoch: 009 | Train loss: 0.9998 | Train acc: 49.95% | Val loss: 0.9989 | Val acc: 51.70% | LR: 0.000027
Epoch: 010 | Train loss: 0.9987 | Train acc: 50.39% | Val loss: 0.9991 | Val acc: 51.50% | LR: 0.000026
Epoch: 011 | Train loss: 0.9981 | Train acc: 50.43% | Val loss: 0.9991 | Val acc: 51.29% | LR: 0.000026
Epoch: 012 | Train loss: 0.9983 | Train acc: 50.18% | Val loss: 1.0026 | Val acc: 51.30% | LR: 0.000026
Epoch: 013 | Train loss: 0.9982 | Train acc: 50.37% | Val loss: 0.9994 | Val acc: 51.24% | LR: 0.000026
Epoch: 014 | Train loss: 0.9974 | Train acc: 50.71% | Val loss: 0.9993 | Val acc: 51.21% | LR: 0.000026
Epoch: 015 | Train loss: 0.9969 | Train acc: 50.55% | Val loss: 1.0013 | Val acc: 50.89% | LR: 0.000026
Epoch: 016 | Train loss: 0.9948 | Train acc: 51.01% | Val loss: 1.0013 | Val acc: 50.42% | LR: 0.000026
Epoch: 017 | Train loss: 0.9976 | Train acc: 50.52% | Val loss: 0.9990 | Val acc: 49.91% | LR: 0.000026
Epoch: 018 | Train loss: 0.9948 | Train acc: 50.95% | Val loss: 0.9995 | Val acc: 49.93% | LR: 0.000026
Epoch: 019 | Train loss: 0.9965 | Train acc: 50.53% | Val loss: 1.0005 | Val acc: 49.79% | LR: 0.000026
Epoch: 020 | Train loss: 0.9982 | Train acc: 50.25% | Val loss: 1.0031 | Val acc: 49.79% | LR: 0.000026
Epoch: 021 | Train loss: 0.9987 | Train acc: 50.20% | Val loss: 1.0003 | Val acc: 49.95% | LR: 0.000025
Epoch: 022 | Train loss: 0.9964 | Train acc: 50.86% | Val loss: 0.9995 | Val acc: 50.32% | LR: 0.000025
Epoch: 023 | Train loss: 0.9975 | Train acc: 50.39% | Val loss: 1.0003 | Val acc: 49.89% | LR: 0.000025
Epoch: 024 | Train loss: 0.9947 | Train acc: 50.82% | Val loss: 0.9994 | Val acc: 50.24% | LR: 0.000025
Epoch: 025 | Train loss: 0.9980 | Train acc: 50.27% | Val loss: 0.9984 | Val acc: 49.89% | LR: 0.000025
Epoch: 026 | Train loss: 0.9976 | Train acc: 50.37% | Val loss: 0.9994 | Val acc: 50.69% | LR: 0.000025
Epoch: 027 | Train loss: 0.9967 | Train acc: 50.60% | Val loss: 1.0000 | Val acc: 50.40% | LR: 0.000025
Epoch: 028 | Train loss: 0.9964 | Train acc: 50.75% | Val loss: 0.9996 | Val acc: 49.79% | LR: 0.000024
Epoch: 029 | Train loss: 0.9944 | Train acc: 50.89% | Val loss: 0.9993 | Val acc: 50.02% | LR: 0.000024
Epoch: 030 | Train loss: 0.9935 | Train acc: 51.04% | Val loss: 1.0015 | Val acc: 50.26% | LR: 0.000024
Epoch: 031 | Train loss: 0.9961 | Train acc: 50.69% | Val loss: 0.9995 | Val acc: 50.16% | LR: 0.000024
Epoch: 032 | Train loss: 0.9958 | Train acc: 50.83% | Val loss: 0.9996 | Val acc: 49.92% | LR: 0.000024
Epoch: 033 | Train loss: 0.9944 | Train acc: 50.94% | Val loss: 1.0006 | Val acc: 50.06% | LR: 0.000024
Epoch: 034 | Train loss: 0.9940 | Train acc: 50.94% | Val loss: 0.9995 | Val acc: 50.17% | LR: 0.000023
Epoch: 035 | Train loss: 0.9976 | Train acc: 50.43% | Val loss: 0.9995 | Val acc: 50.16% | LR: 0.000023
Epoch: 036 | Train loss: 0.9933 | Train acc: 50.81% | Val loss: 0.9993 | Val acc: 50.14% | LR: 0.000023
Epoch: 037 | Train loss: 0.9891 | Train acc: 51.43% | Val loss: 0.9996 | Val acc: 49.76% | LR: 0.000023
Epoch: 038 | Train loss: 0.9913 | Train acc: 51.24% | Val loss: 0.9995 | Val acc: 49.48% | LR: 0.000023
Epoch: 039 | Train loss: 0.9930 | Train acc: 50.81% | Val loss: 0.9995 | Val acc: 49.32% | LR: 0.000023
Epoch: 040 | Train loss: 0.9941 | Train acc: 50.69% | Val loss: 0.9996 | Val acc: 49.06% | LR: 0.000022
Epoch: 041 | Train loss: 0.9910 | Train acc: 51.04% | Val loss: 0.9996 | Val acc: 48.72% | LR: 0.000022
Epoch: 042 | Train loss: 0.9956 | Train acc: 50.53% | Val loss: 0.9996 | Val acc: 48.54% | LR: 0.000022
Epoch: 043 | Train loss: 0.9911 | Train acc: 50.89% | Val loss: 0.9997 | Val acc: 48.94% | LR: 0.000022
Epoch: 044 | Train loss: 0.9968 | Train acc: 50.45% | Val loss: 0.9996 | Val acc: 48.68% | LR: 0.000021
Epoch: 045 | Train loss: 0.9935 | Train acc: 50.58% | Val loss: 0.9998 | Val acc: 48.16% | LR: 0.000021
Epoch: 046 | Train loss: 0.9952 | Train acc: 50.78% | Val loss: 0.9998 | Val acc: 48.43% | LR: 0.000021
Epoch: 047 | Train loss: 0.9889 | Train acc: 51.04% | Val loss: 1.0003 | Val acc: 48.82% | LR: 0.000021
Epoch: 048 | Train loss: 0.9950 | Train acc: 50.65% | Val loss: 0.9997 | Val acc: 48.54% | LR: 0.000021
Epoch: 049 | Train loss: 0.9874 | Train acc: 51.22% | Val loss: 0.9999 | Val acc: 48.38% | LR: 0.000020
Epoch: 050 | Train loss: 0.9931 | Train acc: 50.80% | Val loss: 0.9999 | Val acc: 48.37% | LR: 0.000020
Epoch: 051 | Train loss: 0.9870 | Train acc: 51.22% | Val loss: 0.9999 | Val acc: 48.13% | LR: 0.000020
Epoch: 052 | Train loss: 0.9943 | Train acc: 50.61% | Val loss: 1.0000 | Val acc: 48.03% | LR: 0.000020
Epoch: 053 | Train loss: 0.9966 | Train acc: 50.20% | Val loss: 1.0004 | Val acc: 47.87% | LR: 0.000019
Epoch: 054 | Train loss: 0.9897 | Train acc: 51.10% | Val loss: 0.9999 | Val acc: 48.09% | LR: 0.000019
Epoch: 055 | Train loss: 0.9921 | Train acc: 50.72% | Val loss: 1.0000 | Val acc: 47.86% | LR: 0.000019
Epoch: 056 | Train loss: 0.9980 | Train acc: 50.39% | Val loss: 1.0000 | Val acc: 48.21% | LR: 0.000019

[I 2025-09-23 17:51:11,526] Trial 86 finished with value: 0.4830897212028503 and parameters: {'lr': 2.678898429363231e-05, 'hidden_size': 85, 'dropout': 0.21864672933815954, 'weight_decay': 5.965635850036176e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0015 | Train acc: 50.31% | Val loss: 1.0381 | Val acc: 52.63% | LR: 0.000010
Epoch: 001 | Train loss: 0.9991 | Train acc: 50.52% | Val loss: 1.0034 | Val acc: 52.78% | LR: 0.000010
Epoch: 002 | Train loss: 1.0018 | Train acc: 50.48% | Val loss: 1.0104 | Val acc: 52.80% | LR: 0.000010
Epoch: 003 | Train loss: 0.9986 | Train acc: 50.82% | Val loss: 1.0014 | Val acc: 52.84% | LR: 0.000010
Epoch: 004 | Train loss: 1.0002 | Train acc: 50.10% | Val loss: 0.9968 | Val acc: 53.04% | LR: 0.000010
Epoch: 005 | Train loss: 0.9995 | Train acc: 50.21% | Val loss: 1.0814 | Val acc: 52.76% | LR: 0.000010
Epoch: 006 | Train loss: 0.9994 | Train acc: 51.87% | Val loss: 0.9991 | Val acc: 52.97% | LR: 0.000010
Epoch: 007 | Train loss: 1.0005 | Train acc: 50.55% | Val loss: 0.9966 | Val acc: 52.91% | LR: 0.000010
Epoch: 008 | Train loss: 0.9977 | Train acc: 51.23% | Val loss: 0.9993 | Val acc: 52.80% | LR: 0.000010
Epoch: 009 | Train loss: 0.9988 | Train acc: 50.82% | Val loss: 1.0057 | Val acc: 52.73% | LR: 0.000010
Epoch: 010 | Train loss: 0.9999 | Train acc: 51.62% | Val loss: 1.0027 | Val acc: 52.93% | LR: 0.000010
Epoch: 011 | Train loss: 0.9987 | Train acc: 50.86% | Val loss: 1.0084 | Val acc: 52.79% | LR: 0.000010
Epoch: 012 | Train loss: 0.9991 | Train acc: 50.84% | Val loss: 1.0351 | Val acc: 52.78% | LR: 0.000010
Epoch: 013 | Train loss: 0.9986 | Train acc: 50.86% | Val loss: 1.0003 | Val acc: 52.87% | LR: 0.000010
Epoch: 014 | Train loss: 0.9984 | Train acc: 50.96% | Val loss: 0.9959 | Val acc: 52.90% | LR: 0.000010
Epoch: 015 | Train loss: 0.9984 | Train acc: 51.28% | Val loss: 1.0000 | Val acc: 52.92% | LR: 0.000010
Epoch: 016 | Train loss: 0.9994 | Train acc: 51.78% | Val loss: 1.0071 | Val acc: 52.80% | LR: 0.000010
Epoch: 017 | Train loss: 1.0028 | Train acc: 51.26% | Val loss: 1.0024 | Val acc: 52.92% | LR: 0.000010
Epoch: 018 | Train loss: 0.9985 | Train acc: 51.69% | Val loss: 1.0134 | Val acc: 52.92% | LR: 0.000010
Epoch: 019 | Train loss: 0.9986 | Train acc: 51.31% | Val loss: 1.0094 | Val acc: 53.04% | LR: 0.000010
Epoch: 020 | Train loss: 1.0026 | Train acc: 50.28% | Val loss: 1.0090 | Val acc: 52.88% | LR: 0.000010
Epoch: 021 | Train loss: 0.9989 | Train acc: 51.44% | Val loss: 1.0181 | Val acc: 52.86% | LR: 0.000010
Epoch: 022 | Train loss: 0.9970 | Train acc: 51.47% | Val loss: 1.0065 | Val acc: 52.52% | LR: 0.000010
Epoch: 023 | Train loss: 0.9983 | Train acc: 51.81% | Val loss: 1.0045 | Val acc: 53.06% | LR: 0.000010
Epoch: 024 | Train loss: 0.9988 | Train acc: 50.93% | Val loss: 1.0012 | Val acc: 52.86% | LR: 0.000010
Epoch: 025 | Train loss: 1.0000 | Train acc: 50.48% | Val loss: 0.9992 | Val acc: 53.09% | LR: 0.000009
Epoch: 026 | Train loss: 0.9987 | Train acc: 50.77% | Val loss: 0.9979 | Val acc: 52.68% | LR: 0.000009
Epoch: 027 | Train loss: 0.9980 | Train acc: 51.14% | Val loss: 1.0060 | Val acc: 52.92% | LR: 0.000009
Epoch: 028 | Train loss: 0.9981 | Train acc: 50.82% | Val loss: 1.0380 | Val acc: 52.80% | LR: 0.000009
Epoch: 029 | Train loss: 0.9980 | Train acc: 50.76% | Val loss: 1.0227 | Val acc: 52.84% | LR: 0.000009
Epoch: 030 | Train loss: 0.9978 | Train acc: 50.80% | Val loss: 1.0083 | Val acc: 52.92% | LR: 0.000009
Epoch: 031 | Train loss: 0.9982 | Train acc: 50.91% | Val loss: 0.9967 | Val acc: 52.76% | LR: 0.000009
Epoch: 032 | Train loss: 0.9975 | Train acc: 51.12% | Val loss: 0.9993 | Val acc: 52.80% | LR: 0.000009
Epoch: 033 | Train loss: 0.9977 | Train acc: 51.08% | Val loss: 1.0278 | Val acc: 52.53% | LR: 0.000009
Epoch: 034 | Train loss: 0.9982 | Train acc: 51.02% | Val loss: 0.9985 | Val acc: 52.51% | LR: 0.000009
Epoch: 035 | Train loss: 0.9979 | Train acc: 50.37% | Val loss: 1.0345 | Val acc: 52.40% | LR: 0.000009
Epoch: 036 | Train loss: 0.9982 | Train acc: 50.19% | Val loss: 1.0127 | Val acc: 52.54% | LR: 0.000009
Epoch: 037 | Train loss: 0.9971 | Train acc: 51.00% | Val loss: 1.0012 | Val acc: 52.56% | LR: 0.000009
Epoch: 038 | Train loss: 0.9985 | Train acc: 50.44% | Val loss: 0.9973 | Val acc: 52.66% | LR: 0.000009
Epoch: 039 | Train loss: 0.9972 | Train acc: 50.79% | Val loss: 1.0023 | Val acc: 52.68% | LR: 0.000009
Epoch: 040 | Train loss: 0.9977 | Train acc: 50.61% | Val loss: 1.0037 | Val acc: 52.54% | LR: 0.000009
Epoch: 041 | Train loss: 0.9990 | Train acc: 50.27% | Val loss: 0.9988 | Val acc: 52.58% | LR: 0.000008
Epoch: 042 | Train loss: 0.9990 | Train acc: 50.22% | Val loss: 1.0076 | Val acc: 52.58% | LR: 0.000008
Epoch: 043 | Train loss: 0.9986 | Train acc: 50.03% | Val loss: 0.9979 | Val acc: 52.58% | LR: 0.000008
Epoch: 044 | Train loss: 1.0032 | Train acc: 50.19% | Val loss: 1.0064 | Val acc: 52.48% | LR: 0.000008
Epoch: 045 | Train loss: 0.9989 | Train acc: 50.53% | Val loss: 1.0055 | Val acc: 52.60% | LR: 0.000008
Epoch: 046 | Train loss: 0.9984 | Train acc: 49.85% | Val loss: 0.9970 | Val acc: 52.85% | LR: 0.000008
Epoch: 047 | Train loss: 0.9990 | Train acc: 49.94% | Val loss: 1.0012 | Val acc: 52.71% | LR: 0.000008
Epoch: 048 | Train loss: 0.9979 | Train acc: 50.26% | Val loss: 0.9979 | Val acc: 52.75% | LR: 0.000008
Epoch: 049 | Train loss: 0.9968 | Train acc: 50.74% | Val loss: 1.0004 | Val acc: 52.81% | LR: 0.000008
Epoch: 050 | Train loss: 0.9982 | Train acc: 50.31% | Val loss: 0.9976 | Val acc: 52.69% | LR: 0.000008
Epoch: 051 | Train loss: 0.9973 | Train acc: 50.74% | Val loss: 0.9998 | Val acc: 52.76% | LR: 0.000008
Epoch: 052 | Train loss: 0.9982 | Train acc: 50.38% | Val loss: 1.0099 | Val acc: 52.87% | LR: 0.000008
Epoch: 053 | Train loss: 0.9970 | Train acc: 50.90% | Val loss: 1.0024 | Val acc: 52.89% | LR: 0.000007
Epoch: 054 | Train loss: 0.9985 | Train acc: 49.94% | Val loss: 1.0008 | Val acc: 52.34% | LR: 0.000007
Epoch: 055 | Train loss: 0.9974 | Train acc: 50.31% | Val loss: 0.9987 | Val acc: 52.54% | LR: 0.000007
Epoch: 056 | Train loss: 0.9971 | Train acc: 50.84% | Val loss: 0.9988 | Val acc: 52.52% | LR: 0.000007
Epoch: 057 | Train loss: 0.9977 | Train acc: 50.66% | Val loss: 0.9994 | Val acc: 52.59% | LR: 0.000007
Epoch: 058 | Train loss: 0.9953 | Train acc: 51.12% | Val loss: 0.9995 | Val acc: 52.87% | LR: 0.000007
Epoch: 059 | Train loss: 0.9967 | Train acc: 50.76% | Val loss: 0.9996 | Val acc: 52.75% | LR: 0.000007
Epoch: 060 | Train loss: 0.9981 | Train acc: 50.23% | Val loss: 1.0016 | Val acc: 52.87% | LR: 0.000007
Epoch: 061 | Train loss: 0.9981 | Train acc: 50.38% | Val loss: 1.0054 | Val acc: 52.59% | LR: 0.000007
Epoch: 062 | Train loss: 0.9972 | Train acc: 50.74% | Val loss: 0.9962 | Val acc: 52.91% | LR: 0.000007
Epoch: 063 | Train loss: 0.9974 | Train acc: 50.46% | Val loss: 0.9984 | Val acc: 52.61% | LR: 0.000007
Epoch: 064 | Train loss: 0.9985 | Train acc: 50.12% | Val loss: 1.0286 | Val acc: 52.55% | LR: 0.000007
Epoch: 065 | Train loss: 0.9960 | Train acc: 50.72% | Val loss: 1.0003 | Val acc: 52.75% | LR: 0.000006
Epoch: 066 | Train loss: 0.9962 | Train acc: 50.96% | Val loss: 1.0006 | Val acc: 52.62% | LR: 0.000006
Epoch: 067 | Train loss: 0.9971 | Train acc: 50.71% | Val loss: 1.0000 | Val acc: 52.76% | LR: 0.000006
Epoch: 068 | Train loss: 0.9974 | Train acc: 50.36% | Val loss: 1.0058 | Val acc: 52.66% | LR: 0.000006
Epoch: 069 | Train loss: 0.9993 | Train acc: 49.98% | Val loss: 1.0022 | Val acc: 52.72% | LR: 0.000006
Epoch: 070 | Train loss: 0.9975 | Train acc: 50.35% | Val loss: 0.9964 | Val acc: 52.61% | LR: 0.000006
Epoch: 071 | Train loss: 0.9989 | Train acc: 50.23% | Val loss: 0.9976 | Val acc: 52.73% | LR: 0.000006
Epoch: 072 | Train loss: 0.9969 | Train acc: 50.66% | Val loss: 1.0009 | Val acc: 52.79% | LR: 0.000006
Epoch: 073 | Train loss: 0.9943 | Train acc: 51.18% | Val loss: 0.9972 | Val acc: 52.58% | LR: 0.000006
Epoch: 074 | Train loss: 0.9982 | Train acc: 50.22% | Val loss: 1.0317 | Val acc: 52.67% | LR: 0.000006

[I 2025-09-23 17:52:16,615] Trial 87 finished with value: 0.5261444449424744 and parameters: {'lr': 1.0114534519118456e-05, 'hidden_size': 69, 'dropout': 0.301645016237257, 'weight_decay': 5.602674269453935e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9978 | Train acc: 51.05% | Val loss: 1.0065 | Val acc: 53.20% | LR: 0.000013
Epoch: 001 | Train loss: 0.9981 | Train acc: 50.88% | Val loss: 0.9980 | Val acc: 53.36% | LR: 0.000013
Epoch: 002 | Train loss: 0.9983 | Train acc: 50.94% | Val loss: 0.9982 | Val acc: 53.52% | LR: 0.000013
Epoch: 003 | Train loss: 0.9976 | Train acc: 50.83% | Val loss: 0.9975 | Val acc: 53.54% | LR: 0.000013
Epoch: 004 | Train loss: 0.9974 | Train acc: 50.71% | Val loss: 0.9972 | Val acc: 53.66% | LR: 0.000013
Epoch: 005 | Train loss: 0.9980 | Train acc: 50.67% | Val loss: 1.0129 | Val acc: 53.71% | LR: 0.000013
Epoch: 006 | Train loss: 0.9983 | Train acc: 50.57% | Val loss: 0.9977 | Val acc: 53.73% | LR: 0.000013
Epoch: 007 | Train loss: 1.0039 | Train acc: 51.09% | Val loss: 0.9995 | Val acc: 53.43% | LR: 0.000013
Epoch: 008 | Train loss: 0.9983 | Train acc: 50.52% | Val loss: 1.0132 | Val acc: 53.61% | LR: 0.000013
Epoch: 009 | Train loss: 0.9995 | Train acc: 50.23% | Val loss: 1.0010 | Val acc: 53.69% | LR: 0.000013
Epoch: 010 | Train loss: 0.9974 | Train acc: 50.85% | Val loss: 0.9981 | Val acc: 53.54% | LR: 0.000013
Epoch: 011 | Train loss: 0.9971 | Train acc: 50.78% | Val loss: 0.9952 | Val acc: 53.78% | LR: 0.000013
Epoch: 012 | Train loss: 1.0111 | Train acc: 50.18% | Val loss: 1.0114 | Val acc: 53.64% | LR: 0.000013
Epoch: 013 | Train loss: 0.9994 | Train acc: 50.23% | Val loss: 0.9965 | Val acc: 53.70% | LR: 0.000013
Epoch: 014 | Train loss: 0.9974 | Train acc: 50.60% | Val loss: 0.9964 | Val acc: 53.84% | LR: 0.000013
Epoch: 015 | Train loss: 0.9981 | Train acc: 50.63% | Val loss: 0.9982 | Val acc: 53.76% | LR: 0.000013
Epoch: 016 | Train loss: 0.9981 | Train acc: 50.42% | Val loss: 0.9985 | Val acc: 54.04% | LR: 0.000013
Epoch: 017 | Train loss: 0.9995 | Train acc: 50.70% | Val loss: 0.9958 | Val acc: 54.03% | LR: 0.000013
Epoch: 018 | Train loss: 0.9962 | Train acc: 50.90% | Val loss: 0.9958 | Val acc: 54.03% | LR: 0.000013
Epoch: 019 | Train loss: 0.9962 | Train acc: 50.88% | Val loss: 0.9978 | Val acc: 54.09% | LR: 0.000013
Epoch: 020 | Train loss: 0.9962 | Train acc: 51.14% | Val loss: 0.9959 | Val acc: 54.09% | LR: 0.000013
Epoch: 021 | Train loss: 0.9984 | Train acc: 50.42% | Val loss: 0.9959 | Val acc: 54.04% | LR: 0.000012
Epoch: 022 | Train loss: 0.9996 | Train acc: 50.46% | Val loss: 0.9963 | Val acc: 54.04% | LR: 0.000012
Epoch: 023 | Train loss: 0.9969 | Train acc: 50.78% | Val loss: 0.9955 | Val acc: 53.94% | LR: 0.000012
Epoch: 024 | Train loss: 0.9937 | Train acc: 51.10% | Val loss: 0.9965 | Val acc: 53.92% | LR: 0.000012
Epoch: 025 | Train loss: 0.9952 | Train acc: 51.15% | Val loss: 0.9964 | Val acc: 53.66% | LR: 0.000012
Epoch: 026 | Train loss: 0.9953 | Train acc: 50.86% | Val loss: 0.9964 | Val acc: 53.68% | LR: 0.000012
Epoch: 027 | Train loss: 0.9947 | Train acc: 50.98% | Val loss: 0.9964 | Val acc: 53.58% | LR: 0.000012
Epoch: 028 | Train loss: 0.9968 | Train acc: 50.59% | Val loss: 0.9961 | Val acc: 53.50% | LR: 0.000012
Epoch: 029 | Train loss: 0.9956 | Train acc: 50.86% | Val loss: 0.9964 | Val acc: 53.36% | LR: 0.000012
Epoch: 030 | Train loss: 0.9938 | Train acc: 51.02% | Val loss: 0.9964 | Val acc: 53.32% | LR: 0.000012
Epoch: 031 | Train loss: 0.9981 | Train acc: 50.28% | Val loss: 0.9963 | Val acc: 53.46% | LR: 0.000012
Epoch: 032 | Train loss: 0.9948 | Train acc: 50.77% | Val loss: 0.9965 | Val acc: 53.40% | LR: 0.000012
Epoch: 033 | Train loss: 0.9968 | Train acc: 50.63% | Val loss: 0.9964 | Val acc: 53.44% | LR: 0.000012
Epoch: 034 | Train loss: 0.9958 | Train acc: 50.57% | Val loss: 1.0014 | Val acc: 53.40% | LR: 0.000012
Epoch: 035 | Train loss: 0.9919 | Train acc: 51.47% | Val loss: 0.9965 | Val acc: 53.40% | LR: 0.000011
Epoch: 036 | Train loss: 0.9933 | Train acc: 51.20% | Val loss: 0.9964 | Val acc: 53.47% | LR: 0.000011
Epoch: 037 | Train loss: 0.9961 | Train acc: 50.93% | Val loss: 0.9963 | Val acc: 53.39% | LR: 0.000011
Epoch: 038 | Train loss: 0.9952 | Train acc: 50.79% | Val loss: 0.9971 | Val acc: 53.36% | LR: 0.000011
Epoch: 039 | Train loss: 0.9936 | Train acc: 50.95% | Val loss: 0.9964 | Val acc: 53.30% | LR: 0.000011
Epoch: 040 | Train loss: 0.9934 | Train acc: 51.20% | Val loss: 0.9965 | Val acc: 53.28% | LR: 0.000011
Epoch: 041 | Train loss: 0.9992 | Train acc: 50.16% | Val loss: 0.9964 | Val acc: 53.38% | LR: 0.000011
Epoch: 042 | Train loss: 0.9963 | Train acc: 50.69% | Val loss: 0.9965 | Val acc: 53.53% | LR: 0.000011
Epoch: 043 | Train loss: 0.9933 | Train acc: 51.08% | Val loss: 0.9963 | Val acc: 53.65% | LR: 0.000011
Epoch: 044 | Train loss: 1.0006 | Train acc: 50.88% | Val loss: 0.9963 | Val acc: 53.69% | LR: 0.000011
Epoch: 045 | Train loss: 0.9958 | Train acc: 50.91% | Val loss: 0.9963 | Val acc: 53.55% | LR: 0.000011
Epoch: 046 | Train loss: 0.9914 | Train acc: 51.26% | Val loss: 0.9963 | Val acc: 53.53% | LR: 0.000010
Epoch: 047 | Train loss: 0.9975 | Train acc: 50.53% | Val loss: 0.9963 | Val acc: 53.65% | LR: 0.000010
Epoch: 048 | Train loss: 0.9907 | Train acc: 51.37% | Val loss: 0.9962 | Val acc: 53.75% | LR: 0.000010
Epoch: 049 | Train loss: 0.9948 | Train acc: 50.66% | Val loss: 0.9963 | Val acc: 53.79% | LR: 0.000010
Epoch: 050 | Train loss: 0.9919 | Train acc: 51.17% | Val loss: 0.9963 | Val acc: 53.71% | LR: 0.000010
Epoch: 051 | Train loss: 0.9935 | Train acc: 50.99% | Val loss: 0.9963 | Val acc: 53.63% | LR: 0.000010
Epoch: 052 | Train loss: 0.9918 | Train acc: 50.91% | Val loss: 0.9963 | Val acc: 53.67% | LR: 0.000010
Epoch: 053 | Train loss: 0.9930 | Train acc: 50.90% | Val loss: 0.9963 | Val acc: 53.71% | LR: 0.000010
Epoch: 054 | Train loss: 0.9880 | Train acc: 51.07% | Val loss: 0.9962 | Val acc: 53.73% | LR: 0.000010
Epoch: 055 | Train loss: 0.9967 | Train acc: 50.52% | Val loss: 0.9962 | Val acc: 53.73% | LR: 0.000009
Epoch: 056 | Train loss: 0.9949 | Train acc: 50.71% | Val loss: 0.9963 | Val acc: 53.63% | LR: 0.000009
Epoch: 057 | Train loss: 0.9971 | Train acc: 50.26% | Val loss: 0.9962 | Val acc: 53.53% | LR: 0.000009
Epoch: 058 | Train loss: 0.9928 | Train acc: 51.06% | Val loss: 0.9962 | Val acc: 53.51% | LR: 0.000009
Epoch: 059 | Train loss: 0.9922 | Train acc: 50.61% | Val loss: 0.9962 | Val acc: 53.53% | LR: 0.000009
Epoch: 060 | Train loss: 0.9988 | Train acc: 50.35% | Val loss: 0.9962 | Val acc: 53.49% | LR: 0.000009
Epoch: 061 | Train loss: 0.9869 | Train acc: 51.23% | Val loss: 0.9962 | Val acc: 53.49% | LR: 0.000009
Epoch: 062 | Train loss: 0.9898 | Train acc: 51.14% | Val loss: 0.9962 | Val acc: 53.39% | LR: 0.000009
Epoch: 063 | Train loss: 0.9897 | Train acc: 50.96% | Val loss: 0.9962 | Val acc: 53.39% | LR: 0.000008
Epoch: 064 | Train loss: 0.9867 | Train acc: 51.50% | Val loss: 0.9962 | Val acc: 53.35% | LR: 0.000008
Epoch: 065 | Train loss: 0.9959 | Train acc: 50.70% | Val loss: 0.9961 | Val acc: 53.37% | LR: 0.000008
Epoch: 066 | Train loss: 0.9893 | Train acc: 51.08% | Val loss: 0.9961 | Val acc: 53.37% | LR: 0.000008
Epoch: 067 | Train loss: 0.9855 | Train acc: 51.31% | Val loss: 0.9961 | Val acc: 53.35% | LR: 0.000008
Epoch: 068 | Train loss: 0.9912 | Train acc: 51.11% | Val loss: 0.9961 | Val acc: 53.35% | LR: 0.000008

[I 2025-09-23 17:53:16,928] Trial 88 finished with value: 0.5334478259086609 and parameters: {'lr': 1.3110954878703886e-05, 'hidden_size': 96, 'dropout': 0.27074680593453954, 'weight_decay': 9.67131504151315e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0010 | Train acc: 49.42% | Val loss: 0.9960 | Val acc: 54.74% | LR: 0.000016
Epoch: 001 | Train loss: 1.0002 | Train acc: 49.70% | Val loss: 0.9960 | Val acc: 54.62% | LR: 0.000016
Epoch: 002 | Train loss: 1.0006 | Train acc: 49.68% | Val loss: 0.9959 | Val acc: 54.76% | LR: 0.000016
Epoch: 003 | Train loss: 0.9993 | Train acc: 50.34% | Val loss: 0.9960 | Val acc: 54.57% | LR: 0.000016
Epoch: 004 | Train loss: 0.9999 | Train acc: 50.18% | Val loss: 0.9960 | Val acc: 54.53% | LR: 0.000016
Epoch: 005 | Train loss: 0.9986 | Train acc: 50.42% | Val loss: 0.9959 | Val acc: 54.44% | LR: 0.000016
Epoch: 006 | Train loss: 0.9997 | Train acc: 51.19% | Val loss: 0.9959 | Val acc: 53.96% | LR: 0.000016
Epoch: 007 | Train loss: 0.9975 | Train acc: 50.29% | Val loss: 0.9958 | Val acc: 53.75% | LR: 0.000016
Epoch: 008 | Train loss: 0.9962 | Train acc: 50.75% | Val loss: 0.9954 | Val acc: 53.85% | LR: 0.000016
Epoch: 009 | Train loss: 0.9969 | Train acc: 50.56% | Val loss: 0.9957 | Val acc: 54.06% | LR: 0.000016
Epoch: 010 | Train loss: 1.0033 | Train acc: 50.57% | Val loss: 0.9956 | Val acc: 54.05% | LR: 0.000016
Epoch: 011 | Train loss: 0.9947 | Train acc: 51.19% | Val loss: 0.9955 | Val acc: 53.86% | LR: 0.000016
Epoch: 012 | Train loss: 0.9977 | Train acc: 50.71% | Val loss: 0.9953 | Val acc: 53.89% | LR: 0.000016
Epoch: 013 | Train loss: 0.9967 | Train acc: 50.21% | Val loss: 0.9952 | Val acc: 53.77% | LR: 0.000016
Epoch: 014 | Train loss: 0.9973 | Train acc: 50.42% | Val loss: 0.9953 | Val acc: 53.47% | LR: 0.000016
Epoch: 015 | Train loss: 0.9948 | Train acc: 50.93% | Val loss: 0.9953 | Val acc: 53.61% | LR: 0.000016
Epoch: 016 | Train loss: 0.9963 | Train acc: 51.09% | Val loss: 0.9954 | Val acc: 53.31% | LR: 0.000016
Epoch: 017 | Train loss: 0.9955 | Train acc: 50.75% | Val loss: 0.9948 | Val acc: 53.34% | LR: 0.000016
Epoch: 018 | Train loss: 0.9918 | Train acc: 51.31% | Val loss: 0.9948 | Val acc: 53.24% | LR: 0.000016
Epoch: 019 | Train loss: 0.9927 | Train acc: 51.13% | Val loss: 0.9948 | Val acc: 53.27% | LR: 0.000016
Epoch: 020 | Train loss: 0.9993 | Train acc: 50.49% | Val loss: 0.9946 | Val acc: 53.39% | LR: 0.000015
Epoch: 021 | Train loss: 0.9929 | Train acc: 50.69% | Val loss: 0.9945 | Val acc: 53.33% | LR: 0.000015
Epoch: 022 | Train loss: 0.9967 | Train acc: 50.51% | Val loss: 0.9945 | Val acc: 53.34% | LR: 0.000015
Epoch: 023 | Train loss: 0.9950 | Train acc: 51.15% | Val loss: 0.9943 | Val acc: 53.24% | LR: 0.000015
Epoch: 024 | Train loss: 0.9955 | Train acc: 50.79% | Val loss: 0.9942 | Val acc: 53.28% | LR: 0.000015
Epoch: 025 | Train loss: 0.9953 | Train acc: 51.23% | Val loss: 0.9941 | Val acc: 53.22% | LR: 0.000015
Epoch: 026 | Train loss: 0.9937 | Train acc: 50.89% | Val loss: 0.9940 | Val acc: 53.26% | LR: 0.000015
Epoch: 027 | Train loss: 0.9935 | Train acc: 50.79% | Val loss: 0.9938 | Val acc: 53.25% | LR: 0.000015
Epoch: 028 | Train loss: 0.9962 | Train acc: 50.36% | Val loss: 0.9943 | Val acc: 53.13% | LR: 0.000015
Epoch: 029 | Train loss: 0.9980 | Train acc: 50.16% | Val loss: 0.9932 | Val acc: 53.09% | LR: 0.000015
Epoch: 030 | Train loss: 0.9940 | Train acc: 50.80% | Val loss: 0.9932 | Val acc: 53.21% | LR: 0.000015
Epoch: 031 | Train loss: 0.9951 | Train acc: 50.82% | Val loss: 0.9926 | Val acc: 53.28% | LR: 0.000015
Epoch: 032 | Train loss: 0.9926 | Train acc: 50.80% | Val loss: 0.9924 | Val acc: 52.99% | LR: 0.000014
Epoch: 033 | Train loss: 0.9936 | Train acc: 50.88% | Val loss: 0.9925 | Val acc: 52.87% | LR: 0.000014
Epoch: 034 | Train loss: 0.9955 | Train acc: 50.98% | Val loss: 0.9920 | Val acc: 52.93% | LR: 0.000014
Epoch: 035 | Train loss: 0.9913 | Train acc: 51.15% | Val loss: 0.9931 | Val acc: 52.89% | LR: 0.000014
Epoch: 036 | Train loss: 0.9927 | Train acc: 50.91% | Val loss: 0.9918 | Val acc: 52.85% | LR: 0.000014
Epoch: 037 | Train loss: 0.9918 | Train acc: 51.19% | Val loss: 0.9915 | Val acc: 52.73% | LR: 0.000014
Epoch: 038 | Train loss: 0.9902 | Train acc: 51.20% | Val loss: 0.9916 | Val acc: 52.67% | LR: 0.000014
Epoch: 039 | Train loss: 0.9940 | Train acc: 50.75% | Val loss: 0.9910 | Val acc: 52.71% | LR: 0.000014
Epoch: 040 | Train loss: 0.9968 | Train acc: 50.76% | Val loss: 0.9908 | Val acc: 52.65% | LR: 0.000014
Epoch: 041 | Train loss: 0.9942 | Train acc: 50.75% | Val loss: 0.9906 | Val acc: 52.51% | LR: 0.000013
Epoch: 042 | Train loss: 0.9949 | Train acc: 50.57% | Val loss: 0.9909 | Val acc: 52.40% | LR: 0.000013
Epoch: 043 | Train loss: 0.9942 | Train acc: 50.65% | Val loss: 0.9907 | Val acc: 52.34% | LR: 0.000013
Epoch: 044 | Train loss: 0.9903 | Train acc: 51.35% | Val loss: 0.9903 | Val acc: 52.36% | LR: 0.000013
Epoch: 045 | Train loss: 0.9960 | Train acc: 50.46% | Val loss: 0.9901 | Val acc: 52.42% | LR: 0.000013
Epoch: 046 | Train loss: 0.9945 | Train acc: 51.09% | Val loss: 0.9900 | Val acc: 52.48% | LR: 0.000013
Epoch: 047 | Train loss: 0.9924 | Train acc: 50.90% | Val loss: 0.9900 | Val acc: 52.33% | LR: 0.000013
Epoch: 048 | Train loss: 0.9929 | Train acc: 50.74% | Val loss: 0.9899 | Val acc: 52.29% | LR: 0.000013
Epoch: 049 | Train loss: 0.9940 | Train acc: 50.65% | Val loss: 0.9896 | Val acc: 52.29% | LR: 0.000012
Epoch: 050 | Train loss: 0.9933 | Train acc: 51.19% | Val loss: 0.9894 | Val acc: 52.28% | LR: 0.000012
Epoch: 051 | Train loss: 0.9880 | Train acc: 51.37% | Val loss: 0.9894 | Val acc: 52.25% | LR: 0.000012

[I 2025-09-23 17:54:11,086] Trial 89 finished with value: 0.5228722929954529 and parameters: {'lr': 1.616765229661061e-05, 'hidden_size': 107, 'dropout': 0.31444920736181037, 'weight_decay': 1.3668979589129607e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0020 | Train acc: 49.91% | Val loss: 1.0089 | Val acc: 46.51% | LR: 0.000021
Epoch: 001 | Train loss: 1.0009 | Train acc: 49.96% | Val loss: 1.0064 | Val acc: 46.38% | LR: 0.000021
Epoch: 002 | Train loss: 1.0027 | Train acc: 49.16% | Val loss: 1.0059 | Val acc: 46.80% | LR: 0.000021
Epoch: 003 | Train loss: 1.0012 | Train acc: 49.63% | Val loss: 1.0048 | Val acc: 46.86% | LR: 0.000021
Epoch: 004 | Train loss: 0.9994 | Train acc: 49.99% | Val loss: 1.0129 | Val acc: 46.78% | LR: 0.000021
Epoch: 005 | Train loss: 1.0007 | Train acc: 49.85% | Val loss: 1.0089 | Val acc: 46.88% | LR: 0.000021
Epoch: 006 | Train loss: 1.0023 | Train acc: 49.43% | Val loss: 1.0082 | Val acc: 46.35% | LR: 0.000021
Epoch: 007 | Train loss: 1.0023 | Train acc: 49.81% | Val loss: 1.0104 | Val acc: 46.43% | LR: 0.000021
Epoch: 008 | Train loss: 1.0008 | Train acc: 50.06% | Val loss: 1.0086 | Val acc: 46.71% | LR: 0.000021
Epoch: 009 | Train loss: 1.0012 | Train acc: 49.94% | Val loss: 1.0125 | Val acc: 46.07% | LR: 0.000021
Epoch: 010 | Train loss: 1.0008 | Train acc: 49.91% | Val loss: 1.0074 | Val acc: 45.98% | LR: 0.000021
Epoch: 011 | Train loss: 1.0016 | Train acc: 49.71% | Val loss: 1.0150 | Val acc: 46.40% | LR: 0.000021
Epoch: 012 | Train loss: 1.0028 | Train acc: 49.18% | Val loss: 1.0289 | Val acc: 46.15% | LR: 0.000021
Epoch: 013 | Train loss: 1.0003 | Train acc: 49.91% | Val loss: 1.0058 | Val acc: 46.23% | LR: 0.000021
Epoch: 014 | Train loss: 1.0002 | Train acc: 49.87% | Val loss: 1.0042 | Val acc: 46.36% | LR: 0.000021
Epoch: 015 | Train loss: 1.0012 | Train acc: 49.58% | Val loss: 1.0045 | Val acc: 46.40% | LR: 0.000021
Epoch: 016 | Train loss: 0.9997 | Train acc: 49.94% | Val loss: 1.0043 | Val acc: 46.25% | LR: 0.000021
Epoch: 017 | Train loss: 1.0008 | Train acc: 49.79% | Val loss: 1.0047 | Val acc: 46.41% | LR: 0.000021
Epoch: 018 | Train loss: 0.9995 | Train acc: 49.89% | Val loss: 1.0049 | Val acc: 46.27% | LR: 0.000021
Epoch: 019 | Train loss: 1.0013 | Train acc: 49.33% | Val loss: 1.0039 | Val acc: 46.37% | LR: 0.000021
Epoch: 020 | Train loss: 0.9997 | Train acc: 50.04% | Val loss: 1.0045 | Val acc: 46.39% | LR: 0.000020
Epoch: 021 | Train loss: 1.0003 | Train acc: 49.79% | Val loss: 1.0082 | Val acc: 46.32% | LR: 0.000020
Epoch: 022 | Train loss: 1.0001 | Train acc: 49.80% | Val loss: 1.0042 | Val acc: 46.40% | LR: 0.000020
Epoch: 023 | Train loss: 1.0123 | Train acc: 49.87% | Val loss: 1.0045 | Val acc: 46.40% | LR: 0.000020
Epoch: 024 | Train loss: 1.0000 | Train acc: 49.77% | Val loss: 1.0041 | Val acc: 46.35% | LR: 0.000020
Epoch: 025 | Train loss: 1.0009 | Train acc: 49.34% | Val loss: 1.0049 | Val acc: 46.27% | LR: 0.000020
Epoch: 026 | Train loss: 0.9999 | Train acc: 49.69% | Val loss: 1.0053 | Val acc: 46.35% | LR: 0.000020
Epoch: 027 | Train loss: 1.0002 | Train acc: 49.82% | Val loss: 1.0113 | Val acc: 46.23% | LR: 0.000020
Epoch: 028 | Train loss: 1.0001 | Train acc: 49.66% | Val loss: 1.0143 | Val acc: 46.35% | LR: 0.000020
Epoch: 029 | Train loss: 1.0014 | Train acc: 49.34% | Val loss: 1.0054 | Val acc: 46.36% | LR: 0.000019
Epoch: 030 | Train loss: 0.9998 | Train acc: 49.42% | Val loss: 1.0078 | Val acc: 46.28% | LR: 0.000019
Epoch: 031 | Train loss: 0.9999 | Train acc: 49.28% | Val loss: 1.0030 | Val acc: 46.42% | LR: 0.000019
Epoch: 032 | Train loss: 0.9991 | Train acc: 49.81% | Val loss: 1.0060 | Val acc: 46.40% | LR: 0.000019
Epoch: 033 | Train loss: 0.9994 | Train acc: 50.00% | Val loss: 1.0040 | Val acc: 46.34% | LR: 0.000019
Epoch: 034 | Train loss: 0.9995 | Train acc: 49.64% | Val loss: 1.0069 | Val acc: 46.38% | LR: 0.000019
Epoch: 035 | Train loss: 0.9994 | Train acc: 49.65% | Val loss: 1.0046 | Val acc: 46.42% | LR: 0.000019
Epoch: 036 | Train loss: 0.9988 | Train acc: 49.91% | Val loss: 1.0060 | Val acc: 46.42% | LR: 0.000019
Epoch: 037 | Train loss: 0.9991 | Train acc: 49.54% | Val loss: 1.0042 | Val acc: 46.54% | LR: 0.000018
Epoch: 038 | Train loss: 0.9991 | Train acc: 50.26% | Val loss: 1.0046 | Val acc: 46.21% | LR: 0.000018
Epoch: 039 | Train loss: 0.9991 | Train acc: 50.85% | Val loss: 1.0037 | Val acc: 46.33% | LR: 0.000018
Epoch: 040 | Train loss: 0.9985 | Train acc: 50.55% | Val loss: 1.0127 | Val acc: 46.32% | LR: 0.000018
Epoch: 041 | Train loss: 0.9987 | Train acc: 50.61% | Val loss: 1.0046 | Val acc: 46.50% | LR: 0.000018
Epoch: 042 | Train loss: 0.9988 | Train acc: 50.10% | Val loss: 1.0045 | Val acc: 46.50% | LR: 0.000018
Epoch: 043 | Train loss: 0.9985 | Train acc: 51.03% | Val loss: 1.0050 | Val acc: 46.35% | LR: 0.000017
Epoch: 044 | Train loss: 0.9982 | Train acc: 50.01% | Val loss: 1.0045 | Val acc: 46.21% | LR: 0.000017
Epoch: 045 | Train loss: 0.9986 | Train acc: 50.68% | Val loss: 1.0089 | Val acc: 46.21% | LR: 0.000017
Epoch: 046 | Train loss: 0.9988 | Train acc: 50.71% | Val loss: 1.0046 | Val acc: 46.36% | LR: 0.000017
Epoch: 047 | Train loss: 0.9992 | Train acc: 50.26% | Val loss: 1.0045 | Val acc: 46.44% | LR: 0.000017
Epoch: 048 | Train loss: 0.9975 | Train acc: 51.19% | Val loss: 1.0075 | Val acc: 46.22% | LR: 0.000017
Epoch: 049 | Train loss: 0.9984 | Train acc: 50.65% | Val loss: 1.0064 | Val acc: 46.45% | LR: 0.000016
Epoch: 050 | Train loss: 0.9983 | Train acc: 50.87% | Val loss: 1.0097 | Val acc: 46.47% | LR: 0.000016
Epoch: 051 | Train loss: 0.9997 | Train acc: 50.21% | Val loss: 1.0059 | Val acc: 46.19% | LR: 0.000016
Epoch: 052 | Train loss: 0.9980 | Train acc: 50.62% | Val loss: 1.0045 | Val acc: 46.49% | LR: 0.000016
Epoch: 053 | Train loss: 0.9972 | Train acc: 50.63% | Val loss: 1.0089 | Val acc: 46.21% | LR: 0.000016
Epoch: 054 | Train loss: 0.9978 | Train acc: 50.47% | Val loss: 1.0082 | Val acc: 46.29% | LR: 0.000015

[I 2025-09-23 17:55:00,283] Trial 90 finished with value: 0.46167912483215334 and parameters: {'lr': 2.1422910995198266e-05, 'hidden_size': 91, 'dropout': 0.2428516825162605, 'weight_decay': 2.1912527939969364e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0013 | Train acc: 50.02% | Val loss: 1.0017 | Val acc: 46.34% | LR: 0.000014
Epoch: 001 | Train loss: 3.7055 | Train acc: 50.84% | Val loss: 1.0016 | Val acc: 46.50% | LR: 0.000014
Epoch: 002 | Train loss: 0.9995 | Train acc: 50.35% | Val loss: 1.0016 | Val acc: 46.74% | LR: 0.000014
Epoch: 003 | Train loss: 0.9992 | Train acc: 50.26% | Val loss: 1.0015 | Val acc: 47.03% | LR: 0.000014
Epoch: 004 | Train loss: 1.0006 | Train acc: 50.76% | Val loss: 1.0014 | Val acc: 47.33% | LR: 0.000014
Epoch: 005 | Train loss: 0.9993 | Train acc: 50.58% | Val loss: 1.0014 | Val acc: 47.31% | LR: 0.000014
Epoch: 006 | Train loss: 0.9990 | Train acc: 50.59% | Val loss: 1.0013 | Val acc: 47.51% | LR: 0.000014
Epoch: 007 | Train loss: 0.9989 | Train acc: 50.79% | Val loss: 1.0012 | Val acc: 47.74% | LR: 0.000014
Epoch: 008 | Train loss: 0.9998 | Train acc: 50.62% | Val loss: 1.0012 | Val acc: 47.63% | LR: 0.000014
Epoch: 009 | Train loss: 1.0010 | Train acc: 50.48% | Val loss: 1.0012 | Val acc: 47.79% | LR: 0.000014
Epoch: 010 | Train loss: 0.9992 | Train acc: 50.98% | Val loss: 1.0010 | Val acc: 47.94% | LR: 0.000014
Epoch: 011 | Train loss: 0.9993 | Train acc: 50.61% | Val loss: 1.0008 | Val acc: 48.25% | LR: 0.000014
Epoch: 012 | Train loss: 0.9990 | Train acc: 50.67% | Val loss: 1.0008 | Val acc: 48.48% | LR: 0.000014
Epoch: 013 | Train loss: 1.0072 | Train acc: 50.86% | Val loss: 1.0008 | Val acc: 48.62% | LR: 0.000014
Epoch: 014 | Train loss: 0.9982 | Train acc: 50.79% | Val loss: 1.0007 | Val acc: 48.82% | LR: 0.000014
Epoch: 015 | Train loss: 1.0106 | Train acc: 51.05% | Val loss: 1.0007 | Val acc: 48.68% | LR: 0.000014
Epoch: 016 | Train loss: 1.0000 | Train acc: 50.84% | Val loss: 1.0007 | Val acc: 48.72% | LR: 0.000014
Epoch: 017 | Train loss: 1.0026 | Train acc: 50.52% | Val loss: 1.0008 | Val acc: 48.66% | LR: 0.000013
Epoch: 018 | Train loss: 1.0005 | Train acc: 51.07% | Val loss: 1.0008 | Val acc: 48.73% | LR: 0.000013
Epoch: 019 | Train loss: 0.9994 | Train acc: 50.54% | Val loss: 1.0007 | Val acc: 48.72% | LR: 0.000013
Epoch: 020 | Train loss: 0.9978 | Train acc: 50.58% | Val loss: 1.0007 | Val acc: 48.78% | LR: 0.000013
Epoch: 021 | Train loss: 0.9981 | Train acc: 50.94% | Val loss: 1.0006 | Val acc: 48.82% | LR: 0.000013
Epoch: 022 | Train loss: 0.9979 | Train acc: 51.13% | Val loss: 1.0006 | Val acc: 48.95% | LR: 0.000013
Epoch: 023 | Train loss: 0.9967 | Train acc: 51.15% | Val loss: 1.0005 | Val acc: 48.88% | LR: 0.000013
Epoch: 024 | Train loss: 0.9977 | Train acc: 50.95% | Val loss: 1.0004 | Val acc: 49.13% | LR: 0.000013
Epoch: 025 | Train loss: 0.9982 | Train acc: 50.68% | Val loss: 1.0003 | Val acc: 49.33% | LR: 0.000013
Epoch: 026 | Train loss: 1.0451 | Train acc: 50.85% | Val loss: 1.0003 | Val acc: 49.31% | LR: 0.000013
Epoch: 027 | Train loss: 1.1715 | Train acc: 50.91% | Val loss: 1.0003 | Val acc: 49.29% | LR: 0.000013
Epoch: 028 | Train loss: 1.0001 | Train acc: 50.97% | Val loss: 1.0002 | Val acc: 49.36% | LR: 0.000013
Epoch: 029 | Train loss: 1.0125 | Train acc: 50.15% | Val loss: 1.0002 | Val acc: 49.35% | LR: 0.000013
Epoch: 030 | Train loss: 1.0004 | Train acc: 50.52% | Val loss: 1.0002 | Val acc: 49.22% | LR: 0.000013
Epoch: 031 | Train loss: 0.9999 | Train acc: 50.08% | Val loss: 1.0000 | Val acc: 49.24% | LR: 0.000013
Epoch: 032 | Train loss: 1.0014 | Train acc: 51.04% | Val loss: 0.9998 | Val acc: 49.59% | LR: 0.000012
Epoch: 033 | Train loss: 0.9969 | Train acc: 51.29% | Val loss: 0.9998 | Val acc: 49.52% | LR: 0.000012
Epoch: 034 | Train loss: 1.0471 | Train acc: 50.96% | Val loss: 0.9996 | Val acc: 49.68% | LR: 0.000012
Epoch: 035 | Train loss: 0.9980 | Train acc: 50.79% | Val loss: 0.9995 | Val acc: 49.90% | LR: 0.000012
Epoch: 036 | Train loss: 0.9977 | Train acc: 50.70% | Val loss: 0.9993 | Val acc: 49.96% | LR: 0.000012
Epoch: 037 | Train loss: 0.9982 | Train acc: 50.85% | Val loss: 0.9992 | Val acc: 49.82% | LR: 0.000012
Epoch: 038 | Train loss: 0.9998 | Train acc: 50.75% | Val loss: 0.9991 | Val acc: 49.84% | LR: 0.000012
Epoch: 039 | Train loss: 0.9988 | Train acc: 50.18% | Val loss: 0.9990 | Val acc: 49.94% | LR: 0.000012
Epoch: 040 | Train loss: 0.9972 | Train acc: 50.51% | Val loss: 0.9990 | Val acc: 49.98% | LR: 0.000012
Epoch: 041 | Train loss: 0.9984 | Train acc: 50.74% | Val loss: 0.9989 | Val acc: 50.02% | LR: 0.000012
Epoch: 042 | Train loss: 1.0128 | Train acc: 50.80% | Val loss: 0.9988 | Val acc: 50.15% | LR: 0.000011
Epoch: 043 | Train loss: 0.9971 | Train acc: 50.86% | Val loss: 0.9988 | Val acc: 50.17% | LR: 0.000011
Epoch: 044 | Train loss: 0.9978 | Train acc: 50.86% | Val loss: 0.9988 | Val acc: 50.17% | LR: 0.000011
Epoch: 045 | Train loss: 0.9980 | Train acc: 50.61% | Val loss: 0.9988 | Val acc: 50.09% | LR: 0.000011
Epoch: 046 | Train loss: 0.9975 | Train acc: 50.51% | Val loss: 0.9987 | Val acc: 50.05% | LR: 0.000011
Epoch: 047 | Train loss: 0.9991 | Train acc: 51.20% | Val loss: 0.9985 | Val acc: 50.23% | LR: 0.000011
Epoch: 048 | Train loss: 0.9964 | Train acc: 51.16% | Val loss: 0.9983 | Val acc: 50.51% | LR: 0.000011
Epoch: 049 | Train loss: 1.0000 | Train acc: 50.38% | Val loss: 0.9982 | Val acc: 50.47% | LR: 0.000011
Epoch: 050 | Train loss: 0.9958 | Train acc: 50.99% | Val loss: 0.9982 | Val acc: 50.51% | LR: 0.000011
Epoch: 051 | Train loss: 0.9961 | Train acc: 51.07% | Val loss: 0.9981 | Val acc: 50.51% | LR: 0.000010
Epoch: 052 | Train loss: 0.9983 | Train acc: 50.63% | Val loss: 0.9980 | Val acc: 50.45% | LR: 0.000010
Epoch: 053 | Train loss: 0.9963 | Train acc: 50.80% | Val loss: 0.9979 | Val acc: 50.59% | LR: 0.000010
Epoch: 054 | Train loss: 0.9968 | Train acc: 50.79% | Val loss: 0.9977 | Val acc: 50.61% | LR: 0.000010
Epoch: 055 | Train loss: 0.9965 | Train acc: 51.35% | Val loss: 0.9977 | Val acc: 50.55% | LR: 0.000010
Epoch: 056 | Train loss: 0.9964 | Train acc: 50.57% | Val loss: 0.9975 | Val acc: 50.64% | LR: 0.000010
Epoch: 057 | Train loss: 0.9990 | Train acc: 50.18% | Val loss: 0.9974 | Val acc: 50.64% | LR: 0.000010
Epoch: 058 | Train loss: 1.0010 | Train acc: 50.79% | Val loss: 0.9974 | Val acc: 50.66% | LR: 0.000010
Epoch: 059 | Train loss: 1.0111 | Train acc: 51.11% | Val loss: 0.9973 | Val acc: 50.56% | LR: 0.000009
Epoch: 060 | Train loss: 0.9968 | Train acc: 50.59% | Val loss: 0.9972 | Val acc: 50.58% | LR: 0.000009
Epoch: 061 | Train loss: 0.9967 | Train acc: 50.97% | Val loss: 0.9968 | Val acc: 50.78% | LR: 0.000009
Epoch: 062 | Train loss: 0.9984 | Train acc: 50.24% | Val loss: 0.9967 | Val acc: 50.84% | LR: 0.000009
Epoch: 063 | Train loss: 0.9962 | Train acc: 50.86% | Val loss: 0.9966 | Val acc: 50.94% | LR: 0.000009
Epoch: 064 | Train loss: 0.9949 | Train acc: 50.75% | Val loss: 0.9965 | Val acc: 50.96% | LR: 0.000009
Epoch: 065 | Train loss: 1.0327 | Train acc: 51.01% | Val loss: 0.9964 | Val acc: 50.96% | LR: 0.000009
Epoch: 066 | Train loss: 0.9956 | Train acc: 50.98% | Val loss: 0.9964 | Val acc: 50.96% | LR: 0.000009
Epoch: 067 | Train loss: 0.9944 | Train acc: 51.03% | Val loss: 0.9965 | Val acc: 50.92% | LR: 0.000008
Epoch: 068 | Train loss: 1.0031 | Train acc: 50.84% | Val loss: 0.9964 | Val acc: 50.90% | LR: 0.000008
Epoch: 069 | Train loss: 0.9937 | Train acc: 51.15% | Val loss: 0.9964 | Val acc: 50.90% | LR: 0.000008
Epoch: 070 | Train loss: 0.9977 | Train acc: 50.66% | Val loss: 0.9963 | Val acc: 50.98% | LR: 0.000008
Epoch: 071 | Train loss: 0.9972 | Train acc: 50.55% | Val loss: 0.9962 | Val acc: 50.90% | LR: 0.000008
Epoch: 072 | Train loss: 0.9953 | Train acc: 50.75% | Val loss: 0.9962 | Val acc: 50.90% | LR: 0.000008
Epoch: 073 | Train loss: 0.9947 | Train acc: 50.86% | Val loss: 0.9962 | Val acc: 51.00% | LR: 0.000008
Epoch: 074 | Train loss: 0.9944 | Train acc: 51.04% | Val loss: 0.9963 | Val acc: 50.84% | LR: 0.000007
Epoch: 075 | Train loss: 1.0032 | Train acc: 50.35% | Val loss: 0.9962 | Val acc: 50.80% | LR: 0.000007
Epoch: 076 | Train loss: 0.9947 | Train acc: 51.12% | Val loss: 0.9961 | Val acc: 51.02% | LR: 0.000007
Epoch: 077 | Train loss: 0.9968 | Train acc: 50.49% | Val loss: 0.9960 | Val acc: 51.04% | LR: 0.000007
Epoch: 078 | Train loss: 0.9965 | Train acc: 50.53% | Val loss: 0.9959 | Val acc: 51.04% | LR: 0.000007
Epoch: 079 | Train loss: 0.9957 | Train acc: 50.87% | Val loss: 0.9959 | Val acc: 51.04% | LR: 0.000007
Epoch: 080 | Train loss: 0.9978 | Train acc: 50.07% | Val loss: 0.9958 | Val acc: 51.04% | LR: 0.000007
Epoch: 081 | Train loss: 0.9999 | Train acc: 50.50% | Val loss: 0.9957 | Val acc: 51.15% | LR: 0.000007
Epoch: 082 | Train loss: 0.9955 | Train acc: 50.86% | Val loss: 0.9956 | Val acc: 51.17% | LR: 0.000006
Epoch: 083 | Train loss: 0.9958 | Train acc: 50.80% | Val loss: 0.9954 | Val acc: 51.14% | LR: 0.000006
Epoch: 084 | Train loss: 0.9965 | Train acc: 50.70% | Val loss: 0.9952 | Val acc: 51.20% | LR: 0.000006
Epoch: 085 | Train loss: 0.9991 | Train acc: 50.96% | Val loss: 0.9951 | Val acc: 51.20% | LR: 0.000006
Epoch: 086 | Train loss: 0.9957 | Train acc: 50.81% | Val loss: 0.9950 | Val acc: 51.14% | LR: 0.000006
Epoch: 087 | Train loss: 0.9958 | Train acc: 50.92% | Val loss: 0.9949 | Val acc: 51.14% | LR: 0.000006
Epoch: 088 | Train loss: 0.9969 | Train acc: 50.72% | Val loss: 0.9949 | Val acc: 51.14% | LR: 0.000006
Epoch: 089 | Train loss: 0.9963 | Train acc: 50.53% | Val loss: 0.9948 | Val acc: 51.16% | LR: 0.000005
Epoch: 090 | Train loss: 0.9932 | Train acc: 51.25% | Val loss: 0.9947 | Val acc: 51.22% | LR: 0.000005
Epoch: 091 | Train loss: 0.9953 | Train acc: 50.53% | Val loss: 0.9945 | Val acc: 51.26% | LR: 0.000005
Epoch: 092 | Train loss: 1.0011 | Train acc: 51.13% | Val loss: 0.9945 | Val acc: 51.29% | LR: 0.000005
Epoch: 093 | Train loss: 0.9958 | Train acc: 50.70% | Val loss: 0.9944 | Val acc: 51.28% | LR: 0.000005
Epoch: 094 | Train loss: 0.9970 | Train acc: 50.54% | Val loss: 0.9943 | Val acc: 51.28% | LR: 0.000005
Epoch: 095 | Train loss: 0.9929 | Train acc: 51.12% | Val loss: 0.9942 | Val acc: 51.24% | LR: 0.000005
Epoch: 096 | Train loss: 0.9950 | Train acc: 50.89% | Val loss: 0.9941 | Val acc: 51.26% | LR: 0.000005
Epoch: 097 | Train loss: 0.9959 | Train acc: 50.53% | Val loss: 0.9940 | Val acc: 51.26% | LR: 0.000004
Epoch: 098 | Train loss: 0.9942 | Train acc: 50.90% | Val loss: 0.9939 | Val acc: 51.30% | LR: 0.000004
Epoch: 099 | Train loss: 0.9972 | Train acc: 50.27% | Val loss: 0.9938 | Val acc: 51.32% | LR: 0.000004
Epoch: 100 | Train loss: 0.9958 | Train acc: 50.96% | Val loss: 0.9938 | Val acc: 51.30% | LR: 0.000004
Epoch: 101 | Train loss: 0.9965 | Train acc: 50.71% | Val loss: 0.9937 | Val acc: 51.32% | LR: 0.000004
Epoch: 102 | Train loss: 0.9950 | Train acc: 50.72% | Val loss: 0.9936 | Val acc: 51.34% | LR: 0.000004
Epoch: 103 | Train loss: 1.0005 | Train acc: 50.63% | Val loss: 0.9936 | Val acc: 51.37% | LR: 0.000004
Epoch: 104 | Train loss: 0.9956 | Train acc: 51.01% | Val loss: 0.9935 | Val acc: 51.42% | LR: 0.000004
Epoch: 105 | Train loss: 1.0154 | Train acc: 50.62% | Val loss: 0.9934 | Val acc: 51.40% | LR: 0.000004
Epoch: 106 | Train loss: 0.9962 | Train acc: 50.63% | Val loss: 0.9934 | Val acc: 51.40% | LR: 0.000003
Epoch: 107 | Train loss: 0.9991 | Train acc: 50.90% | Val loss: 0.9933 | Val acc: 51.40% | LR: 0.000003
Epoch: 108 | Train loss: 0.9930 | Train acc: 50.98% | Val loss: 0.9933 | Val acc: 51.40% | LR: 0.000003
Epoch: 109 | Train loss: 0.9947 | Train acc: 50.82% | Val loss: 0.9932 | Val acc: 51.40% | LR: 0.000003
Epoch: 110 | Train loss: 0.9936 | Train acc: 50.72% | Val loss: 0.9931 | Val acc: 51.40% | LR: 0.000003
Epoch: 111 | Train loss: 0.9939 | Train acc: 50.88% | Val loss: 0.9931 | Val acc: 51.40% | LR: 0.000003
Epoch: 112 | Train loss: 0.9941 | Train acc: 50.63% | Val loss: 0.9931 | Val acc: 51.42% | LR: 0.000003
Epoch: 113 | Train loss: 0.9936 | Train acc: 50.63% | Val loss: 0.9930 | Val acc: 51.42% | LR: 0.000003
Epoch: 114 | Train loss: 0.9946 | Train acc: 50.55% | Val loss: 0.9930 | Val acc: 51.42% | LR: 0.000003
Epoch: 115 | Train loss: 0.9942 | Train acc: 50.72% | Val loss: 0.9929 | Val acc: 51.36% | LR: 0.000003
Epoch: 116 | Train loss: 0.9951 | Train acc: 50.89% | Val loss: 0.9929 | Val acc: 51.36% | LR: 0.000002
Epoch: 117 | Train loss: 0.9957 | Train acc: 50.55% | Val loss: 0.9929 | Val acc: 51.36% | LR: 0.000002
Epoch: 118 | Train loss: 0.9934 | Train acc: 50.90% | Val loss: 0.9928 | Val acc: 51.36% | LR: 0.000002
Epoch: 119 | Train loss: 0.9962 | Train acc: 50.45% | Val loss: 0.9928 | Val acc: 51.36% | LR: 0.000002
Epoch: 120 | Train loss: 0.9965 | Train acc: 50.72% | Val loss: 0.9928 | Val acc: 51.32% | LR: 0.000002
Epoch: 121 | Train loss: 0.9942 | Train acc: 50.90% | Val loss: 0.9928 | Val acc: 51.36% | LR: 0.000002
Epoch: 122 | Train loss: 0.9924 | Train acc: 51.06% | Val loss: 0.9928 | Val acc: 51.36% | LR: 0.000002
Epoch: 123 | Train loss: 0.9962 | Train acc: 50.37% | Val loss: 0.9928 | Val acc: 51.32% | LR: 0.000002
Epoch: 124 | Train loss: 0.9948 | Train acc: 50.55% | Val loss: 0.9928 | Val acc: 51.32% | LR: 0.000002
Epoch: 125 | Train loss: 0.9930 | Train acc: 50.90% | Val loss: 0.9928 | Val acc: 51.32% | LR: 0.000002
Epoch: 126 | Train loss: 0.9955 | Train acc: 50.62% | Val loss: 0.9927 | Val acc: 51.32% | LR: 0.000002
Epoch: 127 | Train loss: 0.9933 | Train acc: 50.72% | Val loss: 0.9927 | Val acc: 51.32% | LR: 0.000002
Epoch: 128 | Train loss: 0.9939 | Train acc: 50.98% | Val loss: 0.9927 | Val acc: 51.32% | LR: 0.000002
Epoch: 129 | Train loss: 0.9952 | Train acc: 50.37% | Val loss: 0.9927 | Val acc: 51.32% | LR: 0.000002
Epoch: 130 | Train loss: 0.9965 | Train acc: 50.46% | Val loss: 0.9927 | Val acc: 51.32% | LR: 0.000002
Epoch: 131 | Train loss: 0.9958 | Train acc: 50.71% | Val loss: 0.9927 | Val acc: 51.32% | LR: 0.000001
Epoch: 132 | Train loss: 0.9949 | Train acc: 50.90% | Val loss: 0.9927 | Val acc: 51.38% | LR: 0.000001
Epoch: 133 | Train loss: 0.9940 | Train acc: 50.98% | Val loss: 0.9927 | Val acc: 51.38% | LR: 0.000001
Epoch: 134 | Train loss: 0.9961 | Train acc: 50.60% | Val loss: 0.9927 | Val acc: 51.38% | LR: 0.000001
Epoch: 135 | Train loss: 0.9930 | Train acc: 50.90% | Val loss: 0.9927 | Val acc: 51.38% | LR: 0.000001
Epoch: 136 | Train loss: 0.9931 | Train acc: 50.98% | Val loss: 0.9927 | Val acc: 51.38% | LR: 0.000001
Epoch: 137 | Train loss: 0.9939 | Train acc: 50.73% | Val loss: 0.9926 | Val acc: 51.36% | LR: 0.000001
Epoch: 138 | Train loss: 0.9943 | Train acc: 50.78% | Val loss: 0.9926 | Val acc: 51.36% | LR: 0.000001
Epoch: 139 | Train loss: 0.9949 | Train acc: 51.07% | Val loss: 0.9926 | Val acc: 51.36% | LR: 0.000001
Epoch: 140 | Train loss: 0.9948 | Train acc: 50.90% | Val loss: 0.9926 | Val acc: 51.36% | LR: 0.000001
Epoch: 141 | Train loss: 0.9950 | Train acc: 50.63% | Val loss: 0.9926 | Val acc: 51.36% | LR: 0.000001
Epoch: 142 | Train loss: 0.9966 | Train acc: 50.39% | Val loss: 0.9926 | Val acc: 51.36% | LR: 0.000001
Epoch: 143 | Train loss: 0.9965 | Train acc: 50.71% | Val loss: 0.9926 | Val acc: 51.36% | LR: 0.000001
Epoch: 144 | Train loss: 0.9926 | Train acc: 50.69% | Val loss: 0.9926 | Val acc: 51.36% | LR: 0.000001
Epoch: 145 | Train loss: 0.9908 | Train acc: 51.45% | Val loss: 0.9926 | Val acc: 51.36% | LR: 0.000001
Epoch: 146 | Train loss: 0.9944 | Train acc: 50.98% | Val loss: 0.9926 | Val acc: 51.36% | LR: 0.000001
Epoch: 147 | Train loss: 0.9950 | Train acc: 50.43% | Val loss: 0.9926 | Val acc: 51.36% | LR: 0.000001
Epoch: 148 | Train loss: 0.9918 | Train acc: 51.23% | Val loss: 0.9926 | Val acc: 51.36% | LR: 0.000001
Epoch: 149 | Train loss: 0.9948 | Train acc: 50.80% | Val loss: 0.9926 | Val acc: 51.38% | LR: 0.000001

[I 2025-09-23 17:57:24,106] Trial 91 finished with value: 0.5138176023960114 and parameters: {'lr': 1.3938334671333379e-05, 'hidden_size': 100, 'dropout': 0.28544558022733046, 'weight_decay': 4.208307981036744e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 0.9994 | Train acc: 50.02% | Val loss: 0.9996 | Val acc: 52.33% | LR: 0.000012
Epoch: 001 | Train loss: 0.9992 | Train acc: 50.12% | Val loss: 0.9994 | Val acc: 52.76% | LR: 0.000012
Epoch: 002 | Train loss: 0.9987 | Train acc: 50.18% | Val loss: 0.9994 | Val acc: 52.86% | LR: 0.000012
Epoch: 003 | Train loss: 0.9986 | Train acc: 50.19% | Val loss: 0.9995 | Val acc: 52.58% | LR: 0.000012
Epoch: 004 | Train loss: 1.0011 | Train acc: 49.45% | Val loss: 0.9995 | Val acc: 52.62% | LR: 0.000012
Epoch: 005 | Train loss: 0.9971 | Train acc: 50.63% | Val loss: 0.9994 | Val acc: 52.67% | LR: 0.000012
Epoch: 006 | Train loss: 1.0008 | Train acc: 49.77% | Val loss: 0.9993 | Val acc: 52.70% | LR: 0.000012
Epoch: 007 | Train loss: 0.9994 | Train acc: 50.04% | Val loss: 0.9993 | Val acc: 52.69% | LR: 0.000012
Epoch: 008 | Train loss: 0.9976 | Train acc: 50.37% | Val loss: 0.9992 | Val acc: 52.97% | LR: 0.000012
Epoch: 009 | Train loss: 0.9986 | Train acc: 50.54% | Val loss: 0.9990 | Val acc: 53.76% | LR: 0.000012
Epoch: 010 | Train loss: 0.9989 | Train acc: 50.67% | Val loss: 0.9990 | Val acc: 53.80% | LR: 0.000012
Epoch: 011 | Train loss: 0.9980 | Train acc: 50.75% | Val loss: 0.9989 | Val acc: 53.72% | LR: 0.000012
Epoch: 012 | Train loss: 0.9959 | Train acc: 50.95% | Val loss: 0.9988 | Val acc: 53.88% | LR: 0.000012
Epoch: 013 | Train loss: 0.9974 | Train acc: 50.73% | Val loss: 0.9990 | Val acc: 53.75% | LR: 0.000012
Epoch: 014 | Train loss: 0.9976 | Train acc: 50.79% | Val loss: 0.9988 | Val acc: 53.71% | LR: 0.000012
Epoch: 015 | Train loss: 0.9976 | Train acc: 50.88% | Val loss: 0.9987 | Val acc: 53.62% | LR: 0.000011
Epoch: 016 | Train loss: 0.9951 | Train acc: 51.45% | Val loss: 0.9985 | Val acc: 53.54% | LR: 0.000011
Epoch: 017 | Train loss: 0.9960 | Train acc: 51.25% | Val loss: 0.9985 | Val acc: 53.25% | LR: 0.000011
Epoch: 018 | Train loss: 0.9966 | Train acc: 50.92% | Val loss: 0.9984 | Val acc: 53.14% | LR: 0.000011
Epoch: 019 | Train loss: 0.9929 | Train acc: 51.39% | Val loss: 0.9983 | Val acc: 53.20% | LR: 0.000011
Epoch: 020 | Train loss: 1.0012 | Train acc: 50.33% | Val loss: 0.9983 | Val acc: 52.67% | LR: 0.000011
Epoch: 021 | Train loss: 0.9962 | Train acc: 50.84% | Val loss: 0.9981 | Val acc: 52.82% | LR: 0.000011
Epoch: 022 | Train loss: 1.0487 | Train acc: 50.90% | Val loss: 0.9981 | Val acc: 52.92% | LR: 0.000011
Epoch: 023 | Train loss: 1.0199 | Train acc: 50.77% | Val loss: 0.9980 | Val acc: 52.74% | LR: 0.000011
Epoch: 024 | Train loss: 0.9984 | Train acc: 50.69% | Val loss: 0.9980 | Val acc: 52.57% | LR: 0.000011
Epoch: 025 | Train loss: 0.9941 | Train acc: 51.47% | Val loss: 0.9980 | Val acc: 52.60% | LR: 0.000011
Epoch: 026 | Train loss: 0.9970 | Train acc: 50.85% | Val loss: 0.9979 | Val acc: 52.46% | LR: 0.000011
Epoch: 027 | Train loss: 0.9961 | Train acc: 51.02% | Val loss: 0.9980 | Val acc: 52.26% | LR: 0.000011
Epoch: 028 | Train loss: 0.9972 | Train acc: 50.78% | Val loss: 0.9978 | Val acc: 52.45% | LR: 0.000011
Epoch: 029 | Train loss: 0.9932 | Train acc: 51.31% | Val loss: 0.9977 | Val acc: 52.55% | LR: 0.000011
Epoch: 030 | Train loss: 0.9900 | Train acc: 51.69% | Val loss: 0.9976 | Val acc: 52.59% | LR: 0.000011
Epoch: 031 | Train loss: 0.9978 | Train acc: 50.71% | Val loss: 0.9975 | Val acc: 52.49% | LR: 0.000011
Epoch: 032 | Train loss: 0.9938 | Train acc: 51.24% | Val loss: 0.9974 | Val acc: 52.53% | LR: 0.000011
Epoch: 033 | Train loss: 0.9936 | Train acc: 51.24% | Val loss: 0.9973 | Val acc: 52.37% | LR: 0.000010
Epoch: 034 | Train loss: 0.9955 | Train acc: 50.85% | Val loss: 0.9971 | Val acc: 52.43% | LR: 0.000010
Epoch: 035 | Train loss: 0.9947 | Train acc: 50.87% | Val loss: 0.9970 | Val acc: 52.16% | LR: 0.000010
Epoch: 036 | Train loss: 0.9965 | Train acc: 50.72% | Val loss: 0.9968 | Val acc: 52.30% | LR: 0.000010
Epoch: 037 | Train loss: 0.9926 | Train acc: 51.34% | Val loss: 0.9968 | Val acc: 52.30% | LR: 0.000010
Epoch: 038 | Train loss: 0.9951 | Train acc: 50.85% | Val loss: 0.9967 | Val acc: 51.98% | LR: 0.000010
Epoch: 039 | Train loss: 0.9884 | Train acc: 51.64% | Val loss: 0.9966 | Val acc: 52.00% | LR: 0.000010
Epoch: 040 | Train loss: 0.9957 | Train acc: 50.93% | Val loss: 0.9965 | Val acc: 51.86% | LR: 0.000010
Epoch: 041 | Train loss: 0.9962 | Train acc: 50.66% | Val loss: 0.9963 | Val acc: 51.86% | LR: 0.000010
Epoch: 042 | Train loss: 0.9991 | Train acc: 50.44% | Val loss: 0.9961 | Val acc: 51.94% | LR: 0.000010
Epoch: 043 | Train loss: 0.9970 | Train acc: 50.52% | Val loss: 0.9960 | Val acc: 52.02% | LR: 0.000010
Epoch: 044 | Train loss: 0.9912 | Train acc: 51.15% | Val loss: 0.9959 | Val acc: 51.88% | LR: 0.000010
Epoch: 045 | Train loss: 0.9919 | Train acc: 51.05% | Val loss: 0.9958 | Val acc: 51.80% | LR: 0.000009
Epoch: 046 | Train loss: 0.9988 | Train acc: 50.36% | Val loss: 0.9957 | Val acc: 51.85% | LR: 0.000009
Epoch: 047 | Train loss: 0.9848 | Train acc: 51.69% | Val loss: 0.9956 | Val acc: 51.80% | LR: 0.000009
Epoch: 048 | Train loss: 0.9948 | Train acc: 50.72% | Val loss: 0.9955 | Val acc: 51.76% | LR: 0.000009
Epoch: 049 | Train loss: 0.9892 | Train acc: 50.99% | Val loss: 0.9954 | Val acc: 51.76% | LR: 0.000009
Epoch: 050 | Train loss: 0.9921 | Train acc: 50.54% | Val loss: 0.9954 | Val acc: 51.62% | LR: 0.000009
Epoch: 051 | Train loss: 0.9936 | Train acc: 50.81% | Val loss: 0.9954 | Val acc: 51.72% | LR: 0.000009
Epoch: 052 | Train loss: 0.9843 | Train acc: 51.33% | Val loss: 0.9953 | Val acc: 51.64% | LR: 0.000009
Epoch: 053 | Train loss: 0.9903 | Train acc: 50.79% | Val loss: 0.9952 | Val acc: 51.70% | LR: 0.000009
Epoch: 054 | Train loss: 0.9936 | Train acc: 50.53% | Val loss: 0.9951 | Val acc: 51.66% | LR: 0.000009
Epoch: 055 | Train loss: 0.9865 | Train acc: 51.07% | Val loss: 0.9950 | Val acc: 51.70% | LR: 0.000008
Epoch: 056 | Train loss: 0.9871 | Train acc: 51.18% | Val loss: 0.9950 | Val acc: 51.54% | LR: 0.000008
Epoch: 057 | Train loss: 0.9893 | Train acc: 50.92% | Val loss: 0.9949 | Val acc: 51.64% | LR: 0.000008
Epoch: 058 | Train loss: 0.9925 | Train acc: 50.73% | Val loss: 0.9948 | Val acc: 51.58% | LR: 0.000008
Epoch: 059 | Train loss: 0.9919 | Train acc: 50.64% | Val loss: 0.9947 | Val acc: 51.54% | LR: 0.000008
Epoch: 060 | Train loss: 0.9876 | Train acc: 51.24% | Val loss: 0.9946 | Val acc: 51.54% | LR: 0.000008
Epoch: 061 | Train loss: 0.9878 | Train acc: 50.99% | Val loss: 0.9946 | Val acc: 51.54% | LR: 0.000008

[I 2025-09-23 17:58:22,037] Trial 92 finished with value: 0.5151910901069641 and parameters: {'lr': 1.1794691468038253e-05, 'hidden_size': 112, 'dropout': 0.2967324733193415, 'weight_decay': 1.2773702865842971e-06}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0275 | Train acc: 49.96% | Val loss: 0.9953 | Val acc: 53.86% | LR: 0.000018
Epoch: 001 | Train loss: 1.0013 | Train acc: 50.13% | Val loss: 0.9942 | Val acc: 53.93% | LR: 0.000018
Epoch: 002 | Train loss: 0.9998 | Train acc: 50.03% | Val loss: 0.9931 | Val acc: 53.90% | LR: 0.000018
Epoch: 003 | Train loss: 0.9988 | Train acc: 50.37% | Val loss: 0.9942 | Val acc: 53.86% | LR: 0.000018
Epoch: 004 | Train loss: 1.0001 | Train acc: 50.05% | Val loss: 0.9962 | Val acc: 53.76% | LR: 0.000018
Epoch: 005 | Train loss: 0.9991 | Train acc: 50.13% | Val loss: 0.9937 | Val acc: 53.82% | LR: 0.000018
Epoch: 006 | Train loss: 1.0003 | Train acc: 49.87% | Val loss: 0.9939 | Val acc: 53.86% | LR: 0.000018
Epoch: 007 | Train loss: 0.9970 | Train acc: 50.89% | Val loss: 0.9926 | Val acc: 53.84% | LR: 0.000018
Epoch: 008 | Train loss: 1.0002 | Train acc: 49.94% | Val loss: 0.9931 | Val acc: 53.80% | LR: 0.000018
Epoch: 009 | Train loss: 0.9983 | Train acc: 50.28% | Val loss: 0.9924 | Val acc: 53.96% | LR: 0.000018
Epoch: 010 | Train loss: 1.0012 | Train acc: 49.96% | Val loss: 0.9921 | Val acc: 53.94% | LR: 0.000018
Epoch: 011 | Train loss: 0.9987 | Train acc: 50.45% | Val loss: 0.9918 | Val acc: 53.98% | LR: 0.000018
Epoch: 012 | Train loss: 0.9999 | Train acc: 50.21% | Val loss: 0.9937 | Val acc: 53.91% | LR: 0.000018
Epoch: 013 | Train loss: 0.9982 | Train acc: 50.63% | Val loss: 0.9933 | Val acc: 53.86% | LR: 0.000018
Epoch: 014 | Train loss: 0.9980 | Train acc: 50.62% | Val loss: 0.9963 | Val acc: 53.70% | LR: 0.000018
Epoch: 015 | Train loss: 0.9993 | Train acc: 50.35% | Val loss: 0.9936 | Val acc: 53.94% | LR: 0.000018
Epoch: 016 | Train loss: 0.9996 | Train acc: 50.18% | Val loss: 1.0039 | Val acc: 53.90% | LR: 0.000018
Epoch: 017 | Train loss: 0.9991 | Train acc: 50.37% | Val loss: 0.9932 | Val acc: 53.98% | LR: 0.000018
Epoch: 018 | Train loss: 0.9994 | Train acc: 50.45% | Val loss: 0.9935 | Val acc: 53.91% | LR: 0.000017
Epoch: 019 | Train loss: 0.9999 | Train acc: 50.20% | Val loss: 0.9932 | Val acc: 54.07% | LR: 0.000017
Epoch: 020 | Train loss: 0.9978 | Train acc: 50.55% | Val loss: 0.9939 | Val acc: 53.83% | LR: 0.000017
Epoch: 021 | Train loss: 0.9973 | Train acc: 50.48% | Val loss: 0.9944 | Val acc: 53.91% | LR: 0.000017
Epoch: 022 | Train loss: 1.0000 | Train acc: 49.76% | Val loss: 0.9966 | Val acc: 53.93% | LR: 0.000017
Epoch: 023 | Train loss: 0.9983 | Train acc: 50.03% | Val loss: 1.1239 | Val acc: 53.92% | LR: 0.000017
Epoch: 024 | Train loss: 0.9990 | Train acc: 50.22% | Val loss: 0.9960 | Val acc: 53.78% | LR: 0.000017
Epoch: 025 | Train loss: 0.9988 | Train acc: 50.22% | Val loss: 0.9932 | Val acc: 53.87% | LR: 0.000017
Epoch: 026 | Train loss: 0.9981 | Train acc: 50.41% | Val loss: 0.9927 | Val acc: 53.92% | LR: 0.000017
Epoch: 027 | Train loss: 0.9973 | Train acc: 50.40% | Val loss: 0.9930 | Val acc: 53.99% | LR: 0.000017
Epoch: 028 | Train loss: 1.0017 | Train acc: 49.61% | Val loss: 0.9926 | Val acc: 53.88% | LR: 0.000017
Epoch: 029 | Train loss: 0.9990 | Train acc: 50.12% | Val loss: 0.9982 | Val acc: 53.97% | LR: 0.000017
Epoch: 030 | Train loss: 0.9989 | Train acc: 49.97% | Val loss: 0.9923 | Val acc: 54.01% | LR: 0.000016
Epoch: 031 | Train loss: 0.9976 | Train acc: 50.36% | Val loss: 0.9923 | Val acc: 54.03% | LR: 0.000016
Epoch: 032 | Train loss: 0.9965 | Train acc: 50.72% | Val loss: 0.9942 | Val acc: 53.97% | LR: 0.000016
Epoch: 033 | Train loss: 0.9976 | Train acc: 50.38% | Val loss: 0.9929 | Val acc: 54.01% | LR: 0.000016
Epoch: 034 | Train loss: 0.9958 | Train acc: 50.90% | Val loss: 0.9949 | Val acc: 53.97% | LR: 0.000016
Epoch: 035 | Train loss: 0.9903 | Train acc: 51.43% | Val loss: 0.9918 | Val acc: 54.01% | LR: 0.000016
Epoch: 036 | Train loss: 0.9942 | Train acc: 50.82% | Val loss: 0.9927 | Val acc: 53.95% | LR: 0.000016
Epoch: 037 | Train loss: 0.9951 | Train acc: 50.90% | Val loss: 0.9930 | Val acc: 54.03% | LR: 0.000016
Epoch: 038 | Train loss: 0.9985 | Train acc: 50.37% | Val loss: 0.9925 | Val acc: 54.05% | LR: 0.000015
Epoch: 039 | Train loss: 0.9934 | Train acc: 51.08% | Val loss: 0.9921 | Val acc: 54.03% | LR: 0.000015
Epoch: 040 | Train loss: 0.9993 | Train acc: 50.12% | Val loss: 0.9922 | Val acc: 54.03% | LR: 0.000015
Epoch: 041 | Train loss: 0.9989 | Train acc: 50.37% | Val loss: 0.9923 | Val acc: 54.03% | LR: 0.000015
Epoch: 042 | Train loss: 1.0003 | Train acc: 50.19% | Val loss: 0.9915 | Val acc: 54.07% | LR: 0.000015
Epoch: 043 | Train loss: 0.9975 | Train acc: 50.46% | Val loss: 0.9918 | Val acc: 54.05% | LR: 0.000015
Epoch: 044 | Train loss: 0.9982 | Train acc: 50.44% | Val loss: 0.9925 | Val acc: 53.93% | LR: 0.000015
Epoch: 045 | Train loss: 0.9956 | Train acc: 50.64% | Val loss: 0.9921 | Val acc: 54.07% | LR: 0.000014
Epoch: 046 | Train loss: 0.9957 | Train acc: 50.63% | Val loss: 1.0186 | Val acc: 54.07% | LR: 0.000014
Epoch: 047 | Train loss: 0.9940 | Train acc: 50.89% | Val loss: 0.9928 | Val acc: 54.03% | LR: 0.000014
Epoch: 048 | Train loss: 0.9979 | Train acc: 50.37% | Val loss: 0.9921 | Val acc: 54.05% | LR: 0.000014
Epoch: 049 | Train loss: 0.9973 | Train acc: 50.19% | Val loss: 0.9922 | Val acc: 54.11% | LR: 0.000014
Epoch: 050 | Train loss: 0.9994 | Train acc: 50.37% | Val loss: 0.9946 | Val acc: 53.99% | LR: 0.000014
Epoch: 051 | Train loss: 0.9926 | Train acc: 50.89% | Val loss: 0.9926 | Val acc: 54.13% | LR: 0.000014
Epoch: 052 | Train loss: 0.9966 | Train acc: 50.55% | Val loss: 0.9927 | Val acc: 54.05% | LR: 0.000013
Epoch: 053 | Train loss: 0.9991 | Train acc: 50.19% | Val loss: 0.9920 | Val acc: 53.99% | LR: 0.000013
Epoch: 054 | Train loss: 0.9976 | Train acc: 50.36% | Val loss: 0.9918 | Val acc: 54.05% | LR: 0.000013
Epoch: 055 | Train loss: 0.9980 | Train acc: 50.45% | Val loss: 0.9919 | Val acc: 54.01% | LR: 0.000013
Epoch: 056 | Train loss: 0.9948 | Train acc: 50.54% | Val loss: 0.9943 | Val acc: 53.95% | LR: 0.000013
Epoch: 057 | Train loss: 0.9985 | Train acc: 50.19% | Val loss: 0.9919 | Val acc: 54.05% | LR: 0.000013
Epoch: 058 | Train loss: 0.9964 | Train acc: 50.54% | Val loss: 0.9922 | Val acc: 54.09% | LR: 0.000012
Epoch: 059 | Train loss: 0.9909 | Train acc: 51.07% | Val loss: 0.9936 | Val acc: 54.03% | LR: 0.000012
Epoch: 060 | Train loss: 0.9956 | Train acc: 50.55% | Val loss: 0.9922 | Val acc: 54.09% | LR: 0.000012
Epoch: 061 | Train loss: 0.9971 | Train acc: 50.54% | Val loss: 0.9919 | Val acc: 54.07% | LR: 0.000012
Epoch: 062 | Train loss: 0.9918 | Train acc: 50.99% | Val loss: 0.9916 | Val acc: 54.13% | LR: 0.000012
Epoch: 063 | Train loss: 0.9964 | Train acc: 50.37% | Val loss: 0.9925 | Val acc: 54.07% | LR: 0.000012
Epoch: 064 | Train loss: 0.9998 | Train acc: 50.10% | Val loss: 1.0201 | Val acc: 54.15% | LR: 0.000011
Epoch: 065 | Train loss: 1.0003 | Train acc: 49.93% | Val loss: 0.9919 | Val acc: 54.11% | LR: 0.000011
Epoch: 066 | Train loss: 1.0003 | Train acc: 50.10% | Val loss: 0.9928 | Val acc: 54.05% | LR: 0.000011
Epoch: 067 | Train loss: 0.9983 | Train acc: 50.28% | Val loss: 0.9919 | Val acc: 54.11% | LR: 0.000011
Epoch: 068 | Train loss: 0.9970 | Train acc: 50.38% | Val loss: 0.9915 | Val acc: 54.12% | LR: 0.000011
Epoch: 069 | Train loss: 0.9932 | Train acc: 50.74% | Val loss: 0.9915 | Val acc: 54.11% | LR: 0.000010
Epoch: 070 | Train loss: 0.9955 | Train acc: 50.29% | Val loss: 0.9923 | Val acc: 54.15% | LR: 0.000010
Epoch: 071 | Train loss: 0.9921 | Train acc: 50.74% | Val loss: 0.9916 | Val acc: 54.17% | LR: 0.000010
Epoch: 072 | Train loss: 0.9956 | Train acc: 50.49% | Val loss: 0.9918 | Val acc: 54.11% | LR: 0.000010
Epoch: 073 | Train loss: 0.9970 | Train acc: 50.22% | Val loss: 0.9919 | Val acc: 54.27% | LR: 0.000010
Epoch: 074 | Train loss: 0.9961 | Train acc: 50.48% | Val loss: 0.9929 | Val acc: 54.05% | LR: 0.000010
Epoch: 075 | Train loss: 0.9991 | Train acc: 50.21% | Val loss: 0.9924 | Val acc: 54.08% | LR: 0.000009
Epoch: 076 | Train loss: 0.9960 | Train acc: 50.47% | Val loss: 0.9919 | Val acc: 54.21% | LR: 0.000009
Epoch: 077 | Train loss: 0.9965 | Train acc: 50.39% | Val loss: 0.9922 | Val acc: 54.18% | LR: 0.000009
Epoch: 078 | Train loss: 0.9920 | Train acc: 50.74% | Val loss: 0.9920 | Val acc: 54.18% | LR: 0.000009
Epoch: 079 | Train loss: 0.9918 | Train acc: 50.83% | Val loss: 0.9915 | Val acc: 54.17% | LR: 0.000009
Epoch: 080 | Train loss: 0.9976 | Train acc: 50.39% | Val loss: 0.9913 | Val acc: 54.28% | LR: 0.000008
Epoch: 081 | Train loss: 1.0050 | Train acc: 50.84% | Val loss: 0.9936 | Val acc: 54.06% | LR: 0.000008
Epoch: 082 | Train loss: 0.9966 | Train acc: 50.12% | Val loss: 0.9919 | Val acc: 54.20% | LR: 0.000008
Epoch: 083 | Train loss: 0.9924 | Train acc: 50.83% | Val loss: 0.9913 | Val acc: 54.22% | LR: 0.000008
Epoch: 084 | Train loss: 0.9960 | Train acc: 50.56% | Val loss: 0.9932 | Val acc: 54.24% | LR: 0.000008
Epoch: 085 | Train loss: 1.0046 | Train acc: 49.77% | Val loss: 0.9920 | Val acc: 54.20% | LR: 0.000008
Epoch: 086 | Train loss: 0.9921 | Train acc: 50.74% | Val loss: 0.9916 | Val acc: 54.18% | LR: 0.000007
Epoch: 087 | Train loss: 0.9945 | Train acc: 50.46% | Val loss: 0.9919 | Val acc: 54.22% | LR: 0.000007
Epoch: 088 | Train loss: 0.9958 | Train acc: 50.56% | Val loss: 0.9920 | Val acc: 54.16% | LR: 0.000007
Epoch: 089 | Train loss: 0.9888 | Train acc: 51.01% | Val loss: 0.9922 | Val acc: 54.08% | LR: 0.000007
Epoch: 090 | Train loss: 0.9895 | Train acc: 51.01% | Val loss: 0.9922 | Val acc: 54.15% | LR: 0.000007
Epoch: 091 | Train loss: 0.9949 | Train acc: 50.47% | Val loss: 0.9922 | Val acc: 54.06% | LR: 0.000007
Epoch: 092 | Train loss: 0.9935 | Train acc: 50.55% | Val loss: 0.9924 | Val acc: 54.08% | LR: 0.000006
Epoch: 093 | Train loss: 0.9966 | Train acc: 50.39% | Val loss: 0.9924 | Val acc: 54.14% | LR: 0.000006
Epoch: 094 | Train loss: 0.9970 | Train acc: 50.46% | Val loss: 0.9915 | Val acc: 54.30% | LR: 0.000006
Epoch: 095 | Train loss: 0.9945 | Train acc: 50.55% | Val loss: 0.9924 | Val acc: 54.12% | LR: 0.000006
Epoch: 096 | Train loss: 0.9942 | Train acc: 50.37% | Val loss: 0.9922 | Val acc: 54.14% | LR: 0.000006
Epoch: 097 | Train loss: 0.9962 | Train acc: 50.46% | Val loss: 0.9914 | Val acc: 54.28% | LR: 0.000006
Epoch: 098 | Train loss: 0.9902 | Train acc: 50.80% | Val loss: 0.9913 | Val acc: 54.34% | LR: 0.000005
Epoch: 099 | Train loss: 1.0005 | Train acc: 49.94% | Val loss: 0.9925 | Val acc: 54.07% | LR: 0.000005
Epoch: 100 | Train loss: 0.9897 | Train acc: 50.81% | Val loss: 0.9928 | Val acc: 54.01% | LR: 0.000005
Epoch: 101 | Train loss: 0.9942 | Train acc: 50.54% | Val loss: 1.6845 | Val acc: 54.03% | LR: 0.000005
Epoch: 102 | Train loss: 1.0005 | Train acc: 49.92% | Val loss: 0.9917 | Val acc: 54.15% | LR: 0.000005
Epoch: 103 | Train loss: 0.9955 | Train acc: 50.37% | Val loss: 0.9922 | Val acc: 54.01% | LR: 0.000005
Epoch: 104 | Train loss: 0.9939 | Train acc: 50.37% | Val loss: 0.9918 | Val acc: 54.09% | LR: 0.000005
Epoch: 105 | Train loss: 0.9902 | Train acc: 50.64% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000004
Epoch: 106 | Train loss: 0.9974 | Train acc: 50.11% | Val loss: 0.9919 | Val acc: 54.17% | LR: 0.000004
Epoch: 107 | Train loss: 0.9877 | Train acc: 50.99% | Val loss: 0.9925 | Val acc: 54.09% | LR: 0.000004
Epoch: 108 | Train loss: 0.9916 | Train acc: 50.98% | Val loss: 0.9916 | Val acc: 54.09% | LR: 0.000004
Epoch: 109 | Train loss: 0.9997 | Train acc: 50.09% | Val loss: 0.9923 | Val acc: 54.09% | LR: 0.000004
Epoch: 110 | Train loss: 0.9937 | Train acc: 50.54% | Val loss: 0.9914 | Val acc: 54.09% | LR: 0.000004
Epoch: 111 | Train loss: 0.9944 | Train acc: 50.63% | Val loss: 0.9917 | Val acc: 54.18% | LR: 0.000004
Epoch: 112 | Train loss: 0.9952 | Train acc: 50.63% | Val loss: 0.9913 | Val acc: 54.20% | LR: 0.000003
Epoch: 113 | Train loss: 0.9935 | Train acc: 50.53% | Val loss: 0.9918 | Val acc: 54.16% | LR: 0.000003
Epoch: 114 | Train loss: 0.9936 | Train acc: 50.71% | Val loss: 0.9920 | Val acc: 54.13% | LR: 0.000003
Epoch: 115 | Train loss: 1.0003 | Train acc: 50.01% | Val loss: 0.9914 | Val acc: 54.20% | LR: 0.000003
Epoch: 116 | Train loss: 0.9902 | Train acc: 50.81% | Val loss: 0.9919 | Val acc: 54.05% | LR: 0.000003
Epoch: 117 | Train loss: 1.0001 | Train acc: 50.01% | Val loss: 0.9919 | Val acc: 54.13% | LR: 0.000003
Epoch: 118 | Train loss: 0.9982 | Train acc: 50.28% | Val loss: 0.9919 | Val acc: 54.15% | LR: 0.000003
Epoch: 119 | Train loss: 0.9900 | Train acc: 50.89% | Val loss: 0.9919 | Val acc: 54.07% | LR: 0.000003
Epoch: 120 | Train loss: 0.9920 | Train acc: 50.64% | Val loss: 0.9913 | Val acc: 54.20% | LR: 0.000003
Epoch: 121 | Train loss: 0.9874 | Train acc: 51.07% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000002
Epoch: 122 | Train loss: 0.9921 | Train acc: 50.72% | Val loss: 0.9917 | Val acc: 54.22% | LR: 0.000002
Epoch: 123 | Train loss: 0.9904 | Train acc: 50.72% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000002
Epoch: 124 | Train loss: 0.9870 | Train acc: 51.17% | Val loss: 0.9917 | Val acc: 54.26% | LR: 0.000002
Epoch: 125 | Train loss: 0.9941 | Train acc: 50.37% | Val loss: 0.9919 | Val acc: 54.24% | LR: 0.000002
Epoch: 126 | Train loss: 1.0021 | Train acc: 50.01% | Val loss: 0.9915 | Val acc: 54.24% | LR: 0.000002
Epoch: 127 | Train loss: 0.9983 | Train acc: 50.55% | Val loss: 0.9918 | Val acc: 54.22% | LR: 0.000002
Epoch: 128 | Train loss: 0.9890 | Train acc: 50.99% | Val loss: 0.9919 | Val acc: 54.17% | LR: 0.000002
Epoch: 129 | Train loss: 0.9820 | Train acc: 51.34% | Val loss: 0.9918 | Val acc: 54.22% | LR: 0.000002
Epoch: 130 | Train loss: 1.0006 | Train acc: 50.28% | Val loss: 0.9918 | Val acc: 54.22% | LR: 0.000002
Epoch: 131 | Train loss: 0.9909 | Train acc: 50.64% | Val loss: 0.9918 | Val acc: 54.20% | LR: 0.000002
Epoch: 132 | Train loss: 0.9966 | Train acc: 50.28% | Val loss: 0.9918 | Val acc: 54.20% | LR: 0.000002
Epoch: 133 | Train loss: 0.9972 | Train acc: 50.46% | Val loss: 0.9920 | Val acc: 54.18% | LR: 0.000001
Epoch: 134 | Train loss: 0.9938 | Train acc: 50.46% | Val loss: 0.9947 | Val acc: 54.20% | LR: 0.000001
Epoch: 135 | Train loss: 0.9939 | Train acc: 50.55% | Val loss: 0.9916 | Val acc: 54.20% | LR: 0.000001
Epoch: 136 | Train loss: 0.9938 | Train acc: 50.45% | Val loss: 0.9919 | Val acc: 54.16% | LR: 0.000001
Epoch: 137 | Train loss: 0.9938 | Train acc: 50.55% | Val loss: 0.9917 | Val acc: 54.20% | LR: 0.000001
Epoch: 138 | Train loss: 0.9999 | Train acc: 50.01% | Val loss: 0.9918 | Val acc: 54.20% | LR: 0.000001
Epoch: 139 | Train loss: 0.9958 | Train acc: 50.35% | Val loss: 0.9918 | Val acc: 54.22% | LR: 0.000001
Epoch: 140 | Train loss: 0.9934 | Train acc: 50.61% | Val loss: 0.9923 | Val acc: 54.20% | LR: 0.000001
Epoch: 141 | Train loss: 1.0001 | Train acc: 50.08% | Val loss: 0.9923 | Val acc: 54.18% | LR: 0.000001
Epoch: 142 | Train loss: 0.9870 | Train acc: 50.88% | Val loss: 0.9917 | Val acc: 54.20% | LR: 0.000001
Epoch: 143 | Train loss: 0.9932 | Train acc: 50.43% | Val loss: 0.9919 | Val acc: 54.18% | LR: 0.000001
Epoch: 144 | Train loss: 0.9934 | Train acc: 50.61% | Val loss: 0.9939 | Val acc: 54.18% | LR: 0.000001
Epoch: 145 | Train loss: 0.9843 | Train acc: 50.97% | Val loss: 0.9917 | Val acc: 54.20% | LR: 0.000001
Epoch: 146 | Train loss: 0.9909 | Train acc: 50.61% | Val loss: 0.9920 | Val acc: 54.18% | LR: 0.000001
Epoch: 147 | Train loss: 0.9930 | Train acc: 50.52% | Val loss: 0.9919 | Val acc: 54.18% | LR: 0.000001

[I 2025-09-23 18:00:19,296] Trial 93 finished with value: 0.5419773578643798 and parameters: {'lr': 1.814429379172703e-05, 'hidden_size': 75, 'dropout': 0.26457092905701357, 'weight_decay': 2.0764435202064442e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0019 | Train acc: 49.97% | Val loss: 0.9932 | Val acc: 53.91% | LR: 0.000017
Epoch: 001 | Train loss: 1.0000 | Train acc: 50.11% | Val loss: 0.9955 | Val acc: 53.88% | LR: 0.000017
Epoch: 002 | Train loss: 0.9996 | Train acc: 50.03% | Val loss: 0.9926 | Val acc: 53.94% | LR: 0.000017
Epoch: 003 | Train loss: 0.9985 | Train acc: 50.39% | Val loss: 0.9918 | Val acc: 54.02% | LR: 0.000017
Epoch: 004 | Train loss: 1.0001 | Train acc: 50.04% | Val loss: 0.9928 | Val acc: 53.91% | LR: 0.000017
Epoch: 005 | Train loss: 0.9990 | Train acc: 50.11% | Val loss: 0.9930 | Val acc: 53.96% | LR: 0.000017
Epoch: 006 | Train loss: 1.0004 | Train acc: 49.86% | Val loss: 0.9919 | Val acc: 53.99% | LR: 0.000017
Epoch: 007 | Train loss: 0.9967 | Train acc: 50.89% | Val loss: 0.9953 | Val acc: 53.95% | LR: 0.000017
Epoch: 008 | Train loss: 0.9995 | Train acc: 49.96% | Val loss: 0.9921 | Val acc: 53.94% | LR: 0.000017
Epoch: 009 | Train loss: 0.9982 | Train acc: 50.31% | Val loss: 0.9930 | Val acc: 53.85% | LR: 0.000017
Epoch: 010 | Train loss: 1.0005 | Train acc: 49.86% | Val loss: 0.9979 | Val acc: 53.72% | LR: 0.000017
Epoch: 011 | Train loss: 0.9987 | Train acc: 50.44% | Val loss: 0.9958 | Val acc: 53.91% | LR: 0.000017
Epoch: 012 | Train loss: 0.9999 | Train acc: 50.19% | Val loss: 0.9936 | Val acc: 53.93% | LR: 0.000017
Epoch: 013 | Train loss: 0.9980 | Train acc: 50.65% | Val loss: 0.9932 | Val acc: 53.82% | LR: 0.000017
Epoch: 014 | Train loss: 0.9979 | Train acc: 50.65% | Val loss: 0.9915 | Val acc: 53.96% | LR: 0.000017
Epoch: 015 | Train loss: 0.9990 | Train acc: 50.35% | Val loss: 0.9966 | Val acc: 53.82% | LR: 0.000016
Epoch: 016 | Train loss: 0.9998 | Train acc: 50.16% | Val loss: 0.9919 | Val acc: 53.95% | LR: 0.000016
Epoch: 017 | Train loss: 0.9990 | Train acc: 50.32% | Val loss: 0.9927 | Val acc: 53.90% | LR: 0.000016
Epoch: 018 | Train loss: 0.9985 | Train acc: 50.43% | Val loss: 0.9926 | Val acc: 53.94% | LR: 0.000016
Epoch: 019 | Train loss: 0.9998 | Train acc: 50.18% | Val loss: 1.0009 | Val acc: 53.76% | LR: 0.000016
Epoch: 020 | Train loss: 0.9977 | Train acc: 50.55% | Val loss: 0.9915 | Val acc: 53.91% | LR: 0.000016
Epoch: 021 | Train loss: 0.9970 | Train acc: 50.70% | Val loss: 0.9923 | Val acc: 53.84% | LR: 0.000016
Epoch: 022 | Train loss: 0.9994 | Train acc: 50.28% | Val loss: 0.9919 | Val acc: 54.01% | LR: 0.000016
Epoch: 023 | Train loss: 0.9980 | Train acc: 50.30% | Val loss: 0.9974 | Val acc: 54.01% | LR: 0.000016
Epoch: 024 | Train loss: 0.9987 | Train acc: 50.38% | Val loss: 0.9922 | Val acc: 53.82% | LR: 0.000016
Epoch: 025 | Train loss: 0.9987 | Train acc: 50.37% | Val loss: 0.9940 | Val acc: 53.98% | LR: 0.000016
Epoch: 026 | Train loss: 0.9981 | Train acc: 50.48% | Val loss: 0.9918 | Val acc: 53.96% | LR: 0.000016
Epoch: 027 | Train loss: 0.9973 | Train acc: 50.55% | Val loss: 0.9933 | Val acc: 53.84% | LR: 0.000016
Epoch: 028 | Train loss: 1.0015 | Train acc: 49.84% | Val loss: 0.9950 | Val acc: 53.82% | LR: 0.000016
Epoch: 029 | Train loss: 0.9990 | Train acc: 50.10% | Val loss: 0.9965 | Val acc: 53.70% | LR: 0.000015
Epoch: 030 | Train loss: 0.9986 | Train acc: 50.37% | Val loss: 0.9937 | Val acc: 53.72% | LR: 0.000015
Epoch: 031 | Train loss: 0.9976 | Train acc: 50.45% | Val loss: 1.0082 | Val acc: 53.80% | LR: 0.000015
Epoch: 032 | Train loss: 0.9963 | Train acc: 50.70% | Val loss: 0.9935 | Val acc: 53.92% | LR: 0.000015
Epoch: 033 | Train loss: 0.9977 | Train acc: 50.36% | Val loss: 0.9922 | Val acc: 53.98% | LR: 0.000015
Epoch: 034 | Train loss: 0.9959 | Train acc: 50.82% | Val loss: 0.9951 | Val acc: 53.91% | LR: 0.000015
Epoch: 035 | Train loss: 0.9904 | Train acc: 51.40% | Val loss: 0.9937 | Val acc: 53.93% | LR: 0.000015
Epoch: 036 | Train loss: 0.9944 | Train acc: 50.80% | Val loss: 0.9945 | Val acc: 53.91% | LR: 0.000015
Epoch: 037 | Train loss: 0.9951 | Train acc: 50.91% | Val loss: 0.9930 | Val acc: 53.92% | LR: 0.000015
Epoch: 038 | Train loss: 0.9983 | Train acc: 50.35% | Val loss: 0.9921 | Val acc: 53.92% | LR: 0.000014
Epoch: 039 | Train loss: 0.9939 | Train acc: 51.03% | Val loss: 0.9925 | Val acc: 53.95% | LR: 0.000014
Epoch: 040 | Train loss: 0.9995 | Train acc: 50.10% | Val loss: 0.9928 | Val acc: 53.94% | LR: 0.000014
Epoch: 041 | Train loss: 0.9991 | Train acc: 50.36% | Val loss: 0.9928 | Val acc: 53.97% | LR: 0.000014
Epoch: 042 | Train loss: 1.0006 | Train acc: 50.18% | Val loss: 0.9951 | Val acc: 53.99% | LR: 0.000014
Epoch: 043 | Train loss: 0.9975 | Train acc: 50.45% | Val loss: 0.9930 | Val acc: 53.93% | LR: 0.000014
Epoch: 044 | Train loss: 0.9979 | Train acc: 50.47% | Val loss: 0.9924 | Val acc: 54.05% | LR: 0.000014
Epoch: 045 | Train loss: 0.9957 | Train acc: 50.62% | Val loss: 0.9925 | Val acc: 53.95% | LR: 0.000014
Epoch: 046 | Train loss: 0.9957 | Train acc: 50.63% | Val loss: 0.9930 | Val acc: 53.90% | LR: 0.000013
Epoch: 047 | Train loss: 0.9943 | Train acc: 50.88% | Val loss: 0.9908 | Val acc: 53.98% | LR: 0.000013
Epoch: 048 | Train loss: 0.9979 | Train acc: 50.36% | Val loss: 0.9928 | Val acc: 53.92% | LR: 0.000013
Epoch: 049 | Train loss: 0.9975 | Train acc: 50.18% | Val loss: 0.9931 | Val acc: 54.04% | LR: 0.000013
Epoch: 050 | Train loss: 0.9988 | Train acc: 50.38% | Val loss: 0.9926 | Val acc: 53.99% | LR: 0.000013
Epoch: 051 | Train loss: 0.9931 | Train acc: 50.89% | Val loss: 0.9928 | Val acc: 53.89% | LR: 0.000013
Epoch: 052 | Train loss: 0.9965 | Train acc: 50.54% | Val loss: 0.9921 | Val acc: 54.03% | LR: 0.000013
Epoch: 053 | Train loss: 0.9988 | Train acc: 50.19% | Val loss: 0.9921 | Val acc: 53.99% | LR: 0.000012
Epoch: 054 | Train loss: 0.9974 | Train acc: 50.39% | Val loss: 0.9923 | Val acc: 53.96% | LR: 0.000012
Epoch: 055 | Train loss: 0.9973 | Train acc: 50.46% | Val loss: 0.9930 | Val acc: 54.07% | LR: 0.000012
Epoch: 056 | Train loss: 0.9950 | Train acc: 50.55% | Val loss: 0.9966 | Val acc: 53.97% | LR: 0.000012
Epoch: 057 | Train loss: 0.9981 | Train acc: 50.18% | Val loss: 0.9922 | Val acc: 54.03% | LR: 0.000012
Epoch: 058 | Train loss: 0.9965 | Train acc: 50.54% | Val loss: 0.9927 | Val acc: 54.01% | LR: 0.000012
Epoch: 059 | Train loss: 0.9912 | Train acc: 51.09% | Val loss: 0.9922 | Val acc: 54.01% | LR: 0.000011
Epoch: 060 | Train loss: 0.9956 | Train acc: 50.54% | Val loss: 0.9927 | Val acc: 53.99% | LR: 0.000011
Epoch: 061 | Train loss: 0.9969 | Train acc: 50.54% | Val loss: 0.9922 | Val acc: 53.94% | LR: 0.000011
Epoch: 062 | Train loss: 0.9918 | Train acc: 50.99% | Val loss: 0.9919 | Val acc: 53.98% | LR: 0.000011
Epoch: 063 | Train loss: 0.9963 | Train acc: 50.36% | Val loss: 0.9921 | Val acc: 53.97% | LR: 0.000011
Epoch: 064 | Train loss: 0.9994 | Train acc: 50.10% | Val loss: 0.9919 | Val acc: 53.97% | LR: 0.000011
Epoch: 065 | Train loss: 0.9999 | Train acc: 49.92% | Val loss: 0.9923 | Val acc: 53.99% | LR: 0.000010
Epoch: 066 | Train loss: 0.9997 | Train acc: 50.10% | Val loss: 0.9920 | Val acc: 53.99% | LR: 0.000010
Epoch: 067 | Train loss: 0.9980 | Train acc: 50.27% | Val loss: 0.9924 | Val acc: 54.07% | LR: 0.000010
Epoch: 068 | Train loss: 0.9970 | Train acc: 50.36% | Val loss: 0.9918 | Val acc: 54.09% | LR: 0.000010
Epoch: 069 | Train loss: 0.9934 | Train acc: 50.72% | Val loss: 0.9921 | Val acc: 53.97% | LR: 0.000010
Epoch: 070 | Train loss: 0.9955 | Train acc: 50.28% | Val loss: 0.9923 | Val acc: 53.99% | LR: 0.000010
Epoch: 071 | Train loss: 0.9923 | Train acc: 50.72% | Val loss: 0.9927 | Val acc: 53.99% | LR: 0.000009
Epoch: 072 | Train loss: 0.9958 | Train acc: 50.45% | Val loss: 0.9920 | Val acc: 54.01% | LR: 0.000009
Epoch: 073 | Train loss: 0.9970 | Train acc: 50.18% | Val loss: 0.9923 | Val acc: 54.03% | LR: 0.000009
Epoch: 074 | Train loss: 0.9960 | Train acc: 50.46% | Val loss: 0.9919 | Val acc: 54.11% | LR: 0.000009
Epoch: 075 | Train loss: 0.9990 | Train acc: 50.19% | Val loss: 0.9922 | Val acc: 54.03% | LR: 0.000009
Epoch: 076 | Train loss: 0.9959 | Train acc: 50.55% | Val loss: 0.9930 | Val acc: 54.03% | LR: 0.000009
Epoch: 077 | Train loss: 0.9967 | Train acc: 50.38% | Val loss: 0.9925 | Val acc: 54.05% | LR: 0.000008
Epoch: 078 | Train loss: 0.9922 | Train acc: 50.73% | Val loss: 0.9922 | Val acc: 54.05% | LR: 0.000008
Epoch: 079 | Train loss: 0.9921 | Train acc: 50.82% | Val loss: 0.9922 | Val acc: 54.07% | LR: 0.000008
Epoch: 080 | Train loss: 0.9975 | Train acc: 50.38% | Val loss: 0.9924 | Val acc: 54.07% | LR: 0.000008
Epoch: 081 | Train loss: 0.9929 | Train acc: 50.82% | Val loss: 0.9922 | Val acc: 54.07% | LR: 0.000008
Epoch: 082 | Train loss: 0.9998 | Train acc: 50.12% | Val loss: 0.9916 | Val acc: 54.16% | LR: 0.000008
Epoch: 083 | Train loss: 0.9927 | Train acc: 50.84% | Val loss: 0.9923 | Val acc: 54.09% | LR: 0.000007
Epoch: 084 | Train loss: 0.9958 | Train acc: 50.57% | Val loss: 0.9919 | Val acc: 54.21% | LR: 0.000007
Epoch: 085 | Train loss: 1.0040 | Train acc: 49.76% | Val loss: 0.9952 | Val acc: 54.22% | LR: 0.000007
Epoch: 086 | Train loss: 0.9925 | Train acc: 50.65% | Val loss: 0.9918 | Val acc: 54.23% | LR: 0.000007
Epoch: 087 | Train loss: 0.9947 | Train acc: 50.47% | Val loss: 0.9920 | Val acc: 54.11% | LR: 0.000007
Epoch: 088 | Train loss: 0.9956 | Train acc: 50.56% | Val loss: 0.9920 | Val acc: 54.15% | LR: 0.000007
Epoch: 089 | Train loss: 0.9893 | Train acc: 51.01% | Val loss: 0.9918 | Val acc: 54.19% | LR: 0.000007
Epoch: 090 | Train loss: 0.9903 | Train acc: 51.01% | Val loss: 0.9918 | Val acc: 54.23% | LR: 0.000006
Epoch: 091 | Train loss: 0.9950 | Train acc: 50.47% | Val loss: 0.9918 | Val acc: 54.19% | LR: 0.000006
Epoch: 092 | Train loss: 0.9941 | Train acc: 50.56% | Val loss: 1.0436 | Val acc: 54.18% | LR: 0.000006
Epoch: 093 | Train loss: 0.9964 | Train acc: 50.39% | Val loss: 0.9919 | Val acc: 54.18% | LR: 0.000006
Epoch: 094 | Train loss: 0.9969 | Train acc: 50.47% | Val loss: 0.9921 | Val acc: 54.18% | LR: 0.000006
Epoch: 095 | Train loss: 0.9948 | Train acc: 50.56% | Val loss: 0.9920 | Val acc: 54.18% | LR: 0.000006
Epoch: 096 | Train loss: 0.9947 | Train acc: 50.38% | Val loss: 0.9918 | Val acc: 54.24% | LR: 0.000005
Epoch: 097 | Train loss: 0.9963 | Train acc: 50.47% | Val loss: 0.9920 | Val acc: 54.24% | LR: 0.000005
Epoch: 098 | Train loss: 0.9907 | Train acc: 50.83% | Val loss: 0.9921 | Val acc: 54.20% | LR: 0.000005
Epoch: 099 | Train loss: 1.0002 | Train acc: 49.94% | Val loss: 0.9920 | Val acc: 54.20% | LR: 0.000005
Epoch: 100 | Train loss: 0.9902 | Train acc: 50.83% | Val loss: 0.9920 | Val acc: 54.20% | LR: 0.000005
Epoch: 101 | Train loss: 0.9943 | Train acc: 50.56% | Val loss: 0.9921 | Val acc: 54.20% | LR: 0.000005
Epoch: 102 | Train loss: 1.0002 | Train acc: 49.94% | Val loss: 0.9914 | Val acc: 54.22% | LR: 0.000005
Epoch: 103 | Train loss: 0.9955 | Train acc: 50.39% | Val loss: 0.9924 | Val acc: 54.22% | LR: 0.000004
Epoch: 104 | Train loss: 0.9942 | Train acc: 50.38% | Val loss: 0.9915 | Val acc: 54.26% | LR: 0.000004
Epoch: 105 | Train loss: 0.9908 | Train acc: 50.64% | Val loss: 0.9915 | Val acc: 54.22% | LR: 0.000004
Epoch: 106 | Train loss: 0.9977 | Train acc: 50.11% | Val loss: 0.9922 | Val acc: 54.16% | LR: 0.000004
Epoch: 107 | Train loss: 0.9885 | Train acc: 50.99% | Val loss: 0.9916 | Val acc: 54.20% | LR: 0.000004
Epoch: 108 | Train loss: 0.9903 | Train acc: 51.00% | Val loss: 0.9922 | Val acc: 54.14% | LR: 0.000004
Epoch: 109 | Train loss: 0.9994 | Train acc: 50.11% | Val loss: 0.9926 | Val acc: 54.14% | LR: 0.000004
Epoch: 110 | Train loss: 0.9938 | Train acc: 50.56% | Val loss: 0.9991 | Val acc: 54.16% | LR: 0.000004
Epoch: 111 | Train loss: 0.9945 | Train acc: 50.65% | Val loss: 0.9940 | Val acc: 54.18% | LR: 0.000003
Epoch: 112 | Train loss: 0.9951 | Train acc: 50.65% | Val loss: 0.9922 | Val acc: 54.14% | LR: 0.000003
Epoch: 113 | Train loss: 0.9935 | Train acc: 50.56% | Val loss: 0.9921 | Val acc: 54.12% | LR: 0.000003
Epoch: 114 | Train loss: 0.9938 | Train acc: 50.74% | Val loss: 0.9921 | Val acc: 54.12% | LR: 0.000003
Epoch: 115 | Train loss: 1.0000 | Train acc: 50.03% | Val loss: 0.9920 | Val acc: 54.12% | LR: 0.000003
Epoch: 116 | Train loss: 0.9906 | Train acc: 50.82% | Val loss: 0.9921 | Val acc: 54.12% | LR: 0.000003
Epoch: 117 | Train loss: 0.9999 | Train acc: 50.03% | Val loss: 0.9921 | Val acc: 54.12% | LR: 0.000003
Epoch: 118 | Train loss: 0.9982 | Train acc: 50.29% | Val loss: 0.9947 | Val acc: 54.17% | LR: 0.000003
Epoch: 119 | Train loss: 0.9904 | Train acc: 50.91% | Val loss: 0.9924 | Val acc: 54.17% | LR: 0.000003
Epoch: 120 | Train loss: 0.9923 | Train acc: 50.65% | Val loss: 0.9923 | Val acc: 54.12% | LR: 0.000002
Epoch: 121 | Train loss: 0.9878 | Train acc: 51.09% | Val loss: 0.9923 | Val acc: 54.12% | LR: 0.000002
Epoch: 122 | Train loss: 0.9920 | Train acc: 50.74% | Val loss: 0.9919 | Val acc: 54.16% | LR: 0.000002
Epoch: 123 | Train loss: 0.9911 | Train acc: 50.74% | Val loss: 0.9926 | Val acc: 54.09% | LR: 0.000002
Epoch: 124 | Train loss: 0.9875 | Train acc: 51.17% | Val loss: 0.9919 | Val acc: 54.11% | LR: 0.000002
Epoch: 125 | Train loss: 0.9942 | Train acc: 50.38% | Val loss: 0.9920 | Val acc: 54.14% | LR: 0.000002
Epoch: 126 | Train loss: 1.0017 | Train acc: 50.12% | Val loss: 0.9921 | Val acc: 54.11% | LR: 0.000002
Epoch: 127 | Train loss: 0.9948 | Train acc: 50.56% | Val loss: 0.9946 | Val acc: 54.11% | LR: 0.000002
Epoch: 128 | Train loss: 0.9893 | Train acc: 51.00% | Val loss: 0.9941 | Val acc: 54.11% | LR: 0.000002
Epoch: 129 | Train loss: 0.9830 | Train acc: 51.36% | Val loss: 0.9916 | Val acc: 54.09% | LR: 0.000002
Epoch: 130 | Train loss: 0.9990 | Train acc: 50.29% | Val loss: 0.9916 | Val acc: 54.09% | LR: 0.000002
Epoch: 131 | Train loss: 0.9912 | Train acc: 50.65% | Val loss: 0.9916 | Val acc: 54.09% | LR: 0.000002
Epoch: 132 | Train loss: 0.9966 | Train acc: 50.29% | Val loss: 0.9935 | Val acc: 54.07% | LR: 0.000001
Epoch: 133 | Train loss: 0.9971 | Train acc: 50.47% | Val loss: 0.9916 | Val acc: 54.09% | LR: 0.000001
Epoch: 134 | Train loss: 0.9939 | Train acc: 50.47% | Val loss: 0.9920 | Val acc: 54.09% | LR: 0.000001
Epoch: 135 | Train loss: 0.9939 | Train acc: 50.56% | Val loss: 0.9918 | Val acc: 54.11% | LR: 0.000001
Epoch: 136 | Train loss: 0.9938 | Train acc: 50.47% | Val loss: 0.9921 | Val acc: 54.11% | LR: 0.000001
Epoch: 137 | Train loss: 0.9941 | Train acc: 50.56% | Val loss: 0.9916 | Val acc: 54.11% | LR: 0.000001
Epoch: 138 | Train loss: 0.9994 | Train acc: 50.03% | Val loss: 0.9916 | Val acc: 54.14% | LR: 0.000001
Epoch: 139 | Train loss: 0.9959 | Train acc: 50.38% | Val loss: 0.9916 | Val acc: 54.14% | LR: 0.000001
Epoch: 140 | Train loss: 0.9936 | Train acc: 50.64% | Val loss: 0.9916 | Val acc: 54.14% | LR: 0.000001
Epoch: 141 | Train loss: 0.9998 | Train acc: 50.11% | Val loss: 0.9916 | Val acc: 54.14% | LR: 0.000001
Epoch: 142 | Train loss: 0.9878 | Train acc: 50.91% | Val loss: 0.9915 | Val acc: 54.14% | LR: 0.000001
Epoch: 143 | Train loss: 0.9934 | Train acc: 50.47% | Val loss: 0.9916 | Val acc: 54.14% | LR: 0.000001
Epoch: 144 | Train loss: 0.9935 | Train acc: 50.65% | Val loss: 0.9916 | Val acc: 54.14% | LR: 0.000001
Epoch: 145 | Train loss: 0.9849 | Train acc: 51.00% | Val loss: 0.9916 | Val acc: 54.14% | LR: 0.000001
Epoch: 146 | Train loss: 0.9914 | Train acc: 50.65% | Val loss: 0.9916 | Val acc: 54.14% | LR: 0.000001
Epoch: 147 | Train loss: 0.9933 | Train acc: 50.56% | Val loss: 0.9916 | Val acc: 54.14% | LR: 0.000001
Epoch: 148 | Train loss: 0.9991 | Train acc: 50.12% | Val loss: 0.9916 | Val acc: 54.14% | LR: 0.000001
Epoch: 149 | Train loss: 0.9980 | Train acc: 50.12% | Val loss: 0.9915 | Val acc: 54.14% | LR: 0.000001

[I 2025-09-23 18:02:24,257] Trial 94 finished with value: 0.5413530111312866 and parameters: {'lr': 1.6933428345144963e-05, 'hidden_size': 75, 'dropout': 0.26504015273081427, 'weight_decay': 1.9127723824648004e-05}. Best is trial 24 with value: 0.5445964932441711.

Epoch: 000 | Train loss: 1.0008 | Train acc: 49.42% | Val loss: 0.9944 | Val acc: 54.11% | LR: 0.000018
Epoch: 001 | Train loss: 1.0012 | Train acc: 49.57% | Val loss: 0.9943 | Val acc: 54.11% | LR: 0.000018
Epoch: 002 | Train loss: 1.0003 | Train acc: 50.53% | Val loss: 0.9943 | Val acc: 54.26% | LR: 0.000018
Epoch: 003 | Train loss: 1.0007 | Train acc: 49.68% | Val loss: 0.9941 | Val acc: 54.30% | LR: 0.000018
Epoch: 004 | Train loss: 1.0009 | Train acc: 49.52% | Val loss: 0.9941 | Val acc: 54.42% | LR: 0.000018
Epoch: 005 | Train loss: 1.0005 | Train acc: 49.68% | Val loss: 0.9942 | Val acc: 54.40% | LR: 0.000018
Epoch: 006 | Train loss: 1.0008 | Train acc: 49.41% | Val loss: 0.9943 | Val acc: 54.36% | LR: 0.000018
Epoch: 007 | Train loss: 1.0002 | Train acc: 50.20% | Val loss: 0.9941 | Val acc: 54.42% | LR: 0.000018
Epoch: 008 | Train loss: 1.0005 | Train acc: 49.66% | Val loss: 0.9944 | Val acc: 54.46% | LR: 0.000018
Epoch: 009 | Train loss: 1.0011 | Train acc: 49.32% | Val loss: 0.9945 | Val acc: 54.46% | LR: 0.000018
Epoch: 010 | Train loss: 1.0008 | Train acc: 49.32% | Val loss: 0.9940 | Val acc: 54.52% | LR: 0.000018
Epoch: 011 | Train loss: 1.0003 | Train acc: 49.76% | Val loss: 0.9941 | Val acc: 54.54% | LR: 0.000018
Epoch: 012 | Train loss: 0.9995 | Train acc: 50.37% | Val loss: 0.9945 | Val acc: 54.52% | LR: 0.000018
Epoch: 013 | Train loss: 1.0001 | Train acc: 49.85% | Val loss: 0.9945 | Val acc: 54.58% | LR: 0.000018
Epoch: 014 | Train loss: 1.0000 | Train acc: 49.92% | Val loss: 0.9941 | Val acc: 54.60% | LR: 0.000018
Epoch: 015 | Train loss: 0.9996 | Train acc: 49.85% | Val loss: 0.9940 | Val acc: 54.68% | LR: 0.000018
Epoch: 016 | Train loss: 0.9997 | Train acc: 49.83% | Val loss: 0.9945 | Val acc: 54.53% | LR: 0.000018
Epoch: 017 | Train loss: 0.9991 | Train acc: 50.23% | Val loss: 0.9941 | Val acc: 54.55% | LR: 0.000018
Epoch: 018 | Train loss: 1.0006 | Train acc: 49.47% | Val loss: 0.9941 | Val acc: 54.43% | LR: 0.000018
Epoch: 019 | Train loss: 1.0002 | Train acc: 49.59% | Val loss: 0.9942 | Val acc: 54.49% | LR: 0.000018
Epoch: 020 | Train loss: 1.0000 | Train acc: 49.68% | Val loss: 0.9940 | Val acc: 54.55% | LR: 0.000018
Epoch: 021 | Train loss: 0.9998 | Train acc: 49.80% | Val loss: 0.9940 | Val acc: 54.57% | LR: 0.000018
Epoch: 022 | Train loss: 0.9998 | Train acc: 50.00% | Val loss: 0.9940 | Val acc: 54.40% | LR: 0.000017
Epoch: 023 | Train loss: 0.9994 | Train acc: 50.09% | Val loss: 0.9940 | Val acc: 54.34% | LR: 0.000017
Epoch: 024 | Train loss: 0.9991 | Train acc: 50.19% | Val loss: 0.9940 | Val acc: 54.40% | LR: 0.000017
Epoch: 025 | Train loss: 0.9981 | Train acc: 50.40% | Val loss: 0.9942 | Val acc: 54.43% | LR: 0.000017
Epoch: 026 | Train loss: 0.9981 | Train acc: 50.59% | Val loss: 0.9939 | Val acc: 54.32% | LR: 0.000017
Epoch: 027 | Train loss: 0.9982 | Train acc: 50.96% | Val loss: 0.9937 | Val acc: 54.30% | LR: 0.000017
Epoch: 028 | Train loss: 0.9987 | Train acc: 50.78% | Val loss: 0.9939 | Val acc: 54.22% | LR: 0.000017
Epoch: 029 | Train loss: 0.9991 | Train acc: 50.54% | Val loss: 0.9940 | Val acc: 54.18% | LR: 0.000017
Epoch: 030 | Train loss: 0.9987 | Train acc: 50.71% | Val loss: 0.9939 | Val acc: 54.22% | LR: 0.000017
Epoch: 031 | Train loss: 0.9971 | Train acc: 51.07% | Val loss: 0.9940 | Val acc: 54.14% | LR: 0.000017
Epoch: 032 | Train loss: 0.9986 | Train acc: 50.60% | Val loss: 0.9937 | Val acc: 54.16% | LR: 0.000016
Epoch: 033 | Train loss: 0.9993 | Train acc: 50.52% | Val loss: 0.9937 | Val acc: 54.28% | LR: 0.000016
Epoch: 034 | Train loss: 0.9980 | Train acc: 50.72% | Val loss: 0.9936 | Val acc: 54.18% | LR: 0.000016
Epoch: 035 | Train loss: 0.9977 | Train acc: 50.91% | Val loss: 0.9941 | Val acc: 54.20% | LR: 0.000016
Epoch: 036 | Train loss: 1.0004 | Train acc: 50.03% | Val loss: 0.9945 | Val acc: 54.10% | LR: 0.000016
Epoch: 037 | Train loss: 1.0007 | Train acc: 49.98% | Val loss: 0.9941 | Val acc: 54.16% | LR: 0.000016
Epoch: 038 | Train loss: 0.9981 | Train acc: 50.62% | Val loss: 0.9939 | Val acc: 54.12% | LR: 0.000016
Epoch: 039 | Train loss: 0.9970 | Train acc: 50.80% | Val loss: 0.9940 | Val acc: 54.18% | LR: 0.000016
Epoch: 040 | Train loss: 0.9983 | Train acc: 50.53% | Val loss: 0.9940 | Val acc: 54.06% | LR: 0.000015
Epoch: 041 | Train loss: 0.9996 | Train acc: 50.19% | Val loss: 0.9940 | Val acc: 54.00% | LR: 0.000015
Epoch: 042 | Train loss: 0.9983 | Train acc: 50.46% | Val loss: 0.9940 | Val acc: 54.16% | LR: 0.000015
Epoch: 043 | Train loss: 1.0002 | Train acc: 50.17% | Val loss: 0.9941 | Val acc: 54.08% | LR: 0.000015
Epoch: 044 | Train loss: 0.9991 | Train acc: 50.18% | Val loss: 0.9941 | Val acc: 54.04% | LR: 0.000015
Epoch: 045 | Train loss: 0.9994 | Train acc: 50.20% | Val loss: 0.9941 | Val acc: 54.08% | LR: 0.000015
Epoch: 046 | Train loss: 0.9983 | Train acc: 50.47% | Val loss: 0.9941 | Val acc: 54.04% | LR: 0.000015
Epoch: 047 | Train loss: 0.9990 | Train acc: 50.29% | Val loss: 0.9941 | Val acc: 53.94% | LR: 0.000014
Epoch: 048 | Train loss: 1.0010 | Train acc: 50.00% | Val loss: 0.9940 | Val acc: 53.94% | LR: 0.000014
Epoch: 049 | Train loss: 0.9984 | Train acc: 50.40% | Val loss: 1.0048 | Val acc: 53.92% | LR: 0.000014
Epoch: 050 | Train loss: 0.9974 | Train acc: 50.72% | Val loss: 0.9942 | Val acc: 54.02% | LR: 0.000014
Epoch: 051 | Train loss: 0.9958 | Train acc: 51.13% | Val loss: 0.9941 | Val acc: 54.08% | LR: 0.000014
Epoch: 052 | Train loss: 0.9978 | Train acc: 50.66% | Val loss: 0.9934 | Val acc: 54.45% | LR: 0.000014
Epoch: 053 | Train loss: 0.9971 | Train acc: 50.75% | Val loss: 0.9939 | Val acc: 54.38% | LR: 0.000013
Epoch: 054 | Train loss: 0.9974 | Train acc: 50.75% | Val loss: 0.9941 | Val acc: 54.39% | LR: 0.000013
Epoch: 055 | Train loss: 0.9990 | Train acc: 50.43% | Val loss: 0.9940 | Val acc: 54.57% | LR: 0.000013
Epoch: 056 | Train loss: 0.9983 | Train acc: 50.61% | Val loss: 0.9940 | Val acc: 54.53% | LR: 0.000013
Epoch: 057 | Train loss: 0.9988 | Train acc: 50.42% | Val loss: 0.9939 | Val acc: 54.46% | LR: 0.000013
Epoch: 058 | Train loss: 0.9975 | Train acc: 50.53% | Val loss: 0.9939 | Val acc: 54.50% | LR: 0.000013
Epoch: 059 | Train loss: 0.9947 | Train acc: 51.16% | Val loss: 0.9940 | Val acc: 54.48% | LR: 0.000012
Epoch: 060 | Train loss: 0.9963 | Train acc: 50.82% | Val loss: 0.9940 | Val acc: 54.40% | LR: 0.000012
Epoch: 061 | Train loss: 0.9978 | Train acc: 50.61% | Val loss: 0.9940 | Val acc: 54.42% | LR: 0.000012
Epoch: 062 | Train loss: 0.9972 | Train acc: 50.44% | Val loss: 0.9940 | Val acc: 54.40% | LR: 0.000012
Epoch: 063 | Train loss: 0.9968 | Train acc: 50.63% | Val loss: 0.9940 | Val acc: 54.44% | LR: 0.000012
Epoch: 064 | Train loss: 0.9948 | Train acc: 50.99% | Val loss: 0.9939 | Val acc: 54.44% | LR: 0.000012

[I 2025-09-23 18:03:15,760] Trial 95 finished with value: 0.5447885513305664 and parameters: {'lr': 1.8462467431358333e-05, 'hidden_size': 74, 'dropout': 0.2632404256329749, 'weight_decay': 1.9308418800697618e-05}. Best is trial 95 with value: 0.5447885513305664.

Epoch: 000 | Train loss: 1.0017 | Train acc: 49.94% | Val loss: 0.9942 | Val acc: 53.98% | LR: 0.000019
Epoch: 001 | Train loss: 0.9992 | Train acc: 50.22% | Val loss: 1.0497 | Val acc: 53.90% | LR: 0.000019
Epoch: 002 | Train loss: 0.9994 | Train acc: 50.04% | Val loss: 0.9942 | Val acc: 53.82% | LR: 0.000019
Epoch: 003 | Train loss: 0.9985 | Train acc: 50.36% | Val loss: 0.9954 | Val acc: 53.90% | LR: 0.000018
Epoch: 004 | Train loss: 1.0002 | Train acc: 50.02% | Val loss: 0.9927 | Val acc: 54.04% | LR: 0.000018
Epoch: 005 | Train loss: 0.9992 | Train acc: 50.12% | Val loss: 0.9920 | Val acc: 54.03% | LR: 0.000018
Epoch: 006 | Train loss: 1.0003 | Train acc: 49.84% | Val loss: 0.9930 | Val acc: 53.86% | LR: 0.000018
Epoch: 007 | Train loss: 0.9967 | Train acc: 50.90% | Val loss: 0.9949 | Val acc: 53.95% | LR: 0.000018
Epoch: 008 | Train loss: 0.9992 | Train acc: 49.95% | Val loss: 0.9937 | Val acc: 53.98% | LR: 0.000018
Epoch: 009 | Train loss: 0.9981 | Train acc: 50.61% | Val loss: 0.9935 | Val acc: 53.93% | LR: 0.000018
Epoch: 010 | Train loss: 1.0005 | Train acc: 50.02% | Val loss: 0.9956 | Val acc: 53.89% | LR: 0.000018
Epoch: 011 | Train loss: 0.9989 | Train acc: 50.44% | Val loss: 0.9928 | Val acc: 54.06% | LR: 0.000018
Epoch: 012 | Train loss: 1.0000 | Train acc: 50.20% | Val loss: 0.9932 | Val acc: 53.92% | LR: 0.000018
Epoch: 013 | Train loss: 0.9979 | Train acc: 50.64% | Val loss: 0.9950 | Val acc: 53.79% | LR: 0.000018
Epoch: 014 | Train loss: 0.9983 | Train acc: 50.61% | Val loss: 0.9933 | Val acc: 53.98% | LR: 0.000018
Epoch: 015 | Train loss: 0.9991 | Train acc: 50.36% | Val loss: 0.9931 | Val acc: 53.93% | LR: 0.000018
Epoch: 016 | Train loss: 0.9995 | Train acc: 50.20% | Val loss: 0.9932 | Val acc: 53.91% | LR: 0.000018
Epoch: 017 | Train loss: 0.9990 | Train acc: 50.36% | Val loss: 0.9926 | Val acc: 53.96% | LR: 0.000018
Epoch: 018 | Train loss: 0.9985 | Train acc: 50.45% | Val loss: 0.9930 | Val acc: 53.93% | LR: 0.000018
Epoch: 019 | Train loss: 0.9997 | Train acc: 50.28% | Val loss: 0.9931 | Val acc: 54.00% | LR: 0.000018
Epoch: 020 | Train loss: 0.9975 | Train acc: 50.54% | Val loss: 0.9924 | Val acc: 54.02% | LR: 0.000018
Epoch: 021 | Train loss: 0.9968 | Train acc: 50.74% | Val loss: 0.9930 | Val acc: 54.02% | LR: 0.000018
Epoch: 022 | Train loss: 0.9993 | Train acc: 50.28% | Val loss: 0.9929 | Val acc: 53.96% | LR: 0.000018
Epoch: 023 | Train loss: 0.9979 | Train acc: 50.29% | Val loss: 0.9929 | Val acc: 53.92% | LR: 0.000017
Epoch: 024 | Train loss: 0.9988 | Train acc: 50.36% | Val loss: 0.9931 | Val acc: 53.96% | LR: 0.000017
Epoch: 025 | Train loss: 0.9986 | Train acc: 50.38% | Val loss: 0.9935 | Val acc: 54.00% | LR: 0.000017
Epoch: 026 | Train loss: 0.9977 | Train acc: 50.56% | Val loss: 0.9927 | Val acc: 53.98% | LR: 0.000017
Epoch: 027 | Train loss: 0.9971 | Train acc: 50.34% | Val loss: 0.9930 | Val acc: 54.01% | LR: 0.000017
Epoch: 028 | Train loss: 1.0019 | Train acc: 49.61% | Val loss: 0.9928 | Val acc: 53.96% | LR: 0.000017
Epoch: 029 | Train loss: 0.9992 | Train acc: 50.10% | Val loss: 0.9921 | Val acc: 54.07% | LR: 0.000017
Epoch: 030 | Train loss: 0.9994 | Train acc: 50.38% | Val loss: 0.9929 | Val acc: 53.95% | LR: 0.000017
Epoch: 031 | Train loss: 0.9973 | Train acc: 50.47% | Val loss: 0.9927 | Val acc: 54.01% | LR: 0.000017
Epoch: 032 | Train loss: 0.9961 | Train acc: 50.73% | Val loss: 0.9929 | Val acc: 54.01% | LR: 0.000017
Epoch: 033 | Train loss: 0.9974 | Train acc: 50.37% | Val loss: 0.9928 | Val acc: 54.01% | LR: 0.000016
Epoch: 034 | Train loss: 0.9955 | Train acc: 50.90% | Val loss: 0.9923 | Val acc: 53.97% | LR: 0.000016
Epoch: 035 | Train loss: 0.9894 | Train acc: 51.44% | Val loss: 0.9929 | Val acc: 53.95% | LR: 0.000016
Epoch: 036 | Train loss: 0.9939 | Train acc: 50.81% | Val loss: 0.9928 | Val acc: 53.99% | LR: 0.000016
Epoch: 037 | Train loss: 0.9950 | Train acc: 50.90% | Val loss: 0.9927 | Val acc: 54.05% | LR: 0.000016
Epoch: 038 | Train loss: 0.9985 | Train acc: 50.39% | Val loss: 0.9928 | Val acc: 54.05% | LR: 0.000016
Epoch: 039 | Train loss: 0.9933 | Train acc: 51.08% | Val loss: 0.9930 | Val acc: 53.99% | LR: 0.000016
Epoch: 040 | Train loss: 0.9994 | Train acc: 50.10% | Val loss: 0.9925 | Val acc: 54.07% | LR: 0.000015
Epoch: 041 | Train loss: 0.9990 | Train acc: 50.37% | Val loss: 0.9929 | Val acc: 53.97% | LR: 0.000015
Epoch: 042 | Train loss: 1.0004 | Train acc: 50.20% | Val loss: 0.9927 | Val acc: 54.03% | LR: 0.000015
Epoch: 043 | Train loss: 0.9975 | Train acc: 50.46% | Val loss: 0.9933 | Val acc: 53.89% | LR: 0.000015
Epoch: 044 | Train loss: 0.9982 | Train acc: 50.46% | Val loss: 0.9974 | Val acc: 53.95% | LR: 0.000015
Epoch: 045 | Train loss: 0.9954 | Train acc: 50.64% | Val loss: 0.9930 | Val acc: 53.91% | LR: 0.000015
Epoch: 046 | Train loss: 0.9954 | Train acc: 50.64% | Val loss: 0.9927 | Val acc: 53.97% | LR: 0.000015
Epoch: 047 | Train loss: 0.9939 | Train acc: 50.90% | Val loss: 0.9927 | Val acc: 53.96% | LR: 0.000014
Epoch: 048 | Train loss: 0.9979 | Train acc: 50.37% | Val loss: 0.9945 | Val acc: 53.87% | LR: 0.000014
Epoch: 049 | Train loss: 0.9973 | Train acc: 50.19% | Val loss: 0.9919 | Val acc: 54.04% | LR: 0.000014
Epoch: 050 | Train loss: 0.9989 | Train acc: 50.36% | Val loss: 0.9924 | Val acc: 53.99% | LR: 0.000014
Epoch: 051 | Train loss: 0.9922 | Train acc: 50.90% | Val loss: 0.9919 | Val acc: 54.07% | LR: 0.000014
Epoch: 052 | Train loss: 0.9963 | Train acc: 50.55% | Val loss: 0.9924 | Val acc: 54.03% | LR: 0.000014
Epoch: 053 | Train loss: 0.9987 | Train acc: 50.20% | Val loss: 0.9923 | Val acc: 54.07% | LR: 0.000013
Epoch: 054 | Train loss: 0.9973 | Train acc: 50.37% | Val loss: 0.9922 | Val acc: 54.01% | LR: 0.000013
Epoch: 055 | Train loss: 0.9973 | Train acc: 50.45% | Val loss: 0.9924 | Val acc: 54.01% | LR: 0.000013
Epoch: 056 | Train loss: 0.9946 | Train acc: 50.54% | Val loss: 0.9921 | Val acc: 53.99% | LR: 0.000013
Epoch: 057 | Train loss: 0.9983 | Train acc: 50.18% | Val loss: 0.9912 | Val acc: 54.29% | LR: 0.000013
Epoch: 058 | Train loss: 0.9964 | Train acc: 50.55% | Val loss: 0.9928 | Val acc: 54.13% | LR: 0.000013
Epoch: 059 | Train loss: 0.9904 | Train acc: 51.07% | Val loss: 0.9922 | Val acc: 54.15% | LR: 0.000012
Epoch: 060 | Train loss: 0.9952 | Train acc: 50.55% | Val loss: 0.9921 | Val acc: 54.13% | LR: 0.000012
Epoch: 061 | Train loss: 0.9967 | Train acc: 50.55% | Val loss: 0.9919 | Val acc: 54.11% | LR: 0.000012
Epoch: 062 | Train loss: 0.9910 | Train acc: 50.97% | Val loss: 0.9919 | Val acc: 54.13% | LR: 0.000012
Epoch: 063 | Train loss: 0.9960 | Train acc: 50.35% | Val loss: 0.9918 | Val acc: 54.17% | LR: 0.000012
Epoch: 064 | Train loss: 0.9996 | Train acc: 50.10% | Val loss: 0.9940 | Val acc: 54.15% | LR: 0.000012
Epoch: 065 | Train loss: 1.0001 | Train acc: 49.92% | Val loss: 0.9917 | Val acc: 54.21% | LR: 0.000011
Epoch: 066 | Train loss: 0.9999 | Train acc: 50.10% | Val loss: 0.9916 | Val acc: 54.36% | LR: 0.000011
Epoch: 067 | Train loss: 0.9981 | Train acc: 50.28% | Val loss: 0.9931 | Val acc: 54.19% | LR: 0.000011
Epoch: 068 | Train loss: 0.9967 | Train acc: 50.37% | Val loss: 0.9922 | Val acc: 54.23% | LR: 0.000011
Epoch: 069 | Train loss: 0.9927 | Train acc: 50.74% | Val loss: 0.9912 | Val acc: 54.21% | LR: 0.000011
Epoch: 070 | Train loss: 0.9949 | Train acc: 50.29% | Val loss: 0.9916 | Val acc: 54.23% | LR: 0.000010
Epoch: 071 | Train loss: 0.9914 | Train acc: 50.72% | Val loss: 0.9919 | Val acc: 54.20% | LR: 0.000010
Epoch: 072 | Train loss: 0.9953 | Train acc: 50.47% | Val loss: 0.9919 | Val acc: 54.24% | LR: 0.000010
Epoch: 073 | Train loss: 0.9968 | Train acc: 50.20% | Val loss: 0.9928 | Val acc: 54.11% | LR: 0.000010
Epoch: 074 | Train loss: 0.9957 | Train acc: 50.48% | Val loss: 0.9925 | Val acc: 54.16% | LR: 0.000010
Epoch: 075 | Train loss: 0.9989 | Train acc: 50.19% | Val loss: 0.9936 | Val acc: 54.26% | LR: 0.000010
Epoch: 076 | Train loss: 0.9955 | Train acc: 50.55% | Val loss: 0.9924 | Val acc: 54.28% | LR: 0.000009
Epoch: 077 | Train loss: 0.9962 | Train acc: 50.37% | Val loss: 0.9920 | Val acc: 54.18% | LR: 0.000009
Epoch: 078 | Train loss: 0.9913 | Train acc: 50.73% | Val loss: 0.9919 | Val acc: 54.28% | LR: 0.000009
Epoch: 079 | Train loss: 0.9912 | Train acc: 50.83% | Val loss: 0.9922 | Val acc: 54.24% | LR: 0.000009
Epoch: 080 | Train loss: 0.9974 | Train acc: 50.39% | Val loss: 0.9924 | Val acc: 54.31% | LR: 0.000009
Epoch: 081 | Train loss: 0.9921 | Train acc: 50.83% | Val loss: 0.9920 | Val acc: 54.24% | LR: 0.000008
Epoch: 082 | Train loss: 0.9962 | Train acc: 50.12% | Val loss: 0.9921 | Val acc: 54.24% | LR: 0.000008
Epoch: 083 | Train loss: 0.9918 | Train acc: 50.83% | Val loss: 0.9931 | Val acc: 54.20% | LR: 0.000008
Epoch: 084 | Train loss: 0.9955 | Train acc: 50.56% | Val loss: 0.9926 | Val acc: 54.20% | LR: 0.000008
Epoch: 085 | Train loss: 1.0047 | Train acc: 49.77% | Val loss: 0.9918 | Val acc: 54.20% | LR: 0.000008
Epoch: 086 | Train loss: 0.9915 | Train acc: 50.75% | Val loss: 0.9920 | Val acc: 54.18% | LR: 0.000008
Epoch: 087 | Train loss: 0.9941 | Train acc: 50.46% | Val loss: 0.9922 | Val acc: 54.18% | LR: 0.000007
Epoch: 088 | Train loss: 0.9952 | Train acc: 50.56% | Val loss: 0.9931 | Val acc: 54.08% | LR: 0.000007
Epoch: 089 | Train loss: 0.9880 | Train acc: 51.00% | Val loss: 0.9921 | Val acc: 54.22% | LR: 0.000007
Epoch: 090 | Train loss: 0.9890 | Train acc: 50.99% | Val loss: 0.9924 | Val acc: 54.15% | LR: 0.000007
Epoch: 091 | Train loss: 0.9944 | Train acc: 50.47% | Val loss: 0.9922 | Val acc: 54.18% | LR: 0.000007
Epoch: 092 | Train loss: 0.9932 | Train acc: 50.56% | Val loss: 0.9917 | Val acc: 54.28% | LR: 0.000007
Epoch: 093 | Train loss: 0.9961 | Train acc: 50.39% | Val loss: 0.9925 | Val acc: 54.16% | LR: 0.000006
Epoch: 094 | Train loss: 0.9966 | Train acc: 50.47% | Val loss: 0.9911 | Val acc: 54.22% | LR: 0.000006
Epoch: 095 | Train loss: 0.9941 | Train acc: 50.57% | Val loss: 0.9976 | Val acc: 54.26% | LR: 0.000006
Epoch: 096 | Train loss: 0.9939 | Train acc: 50.39% | Val loss: 0.9919 | Val acc: 54.18% | LR: 0.000006
Epoch: 097 | Train loss: 0.9960 | Train acc: 50.47% | Val loss: 0.9922 | Val acc: 54.18% | LR: 0.000006
Epoch: 098 | Train loss: 0.9895 | Train acc: 50.83% | Val loss: 0.9919 | Val acc: 54.22% | LR: 0.000006
Epoch: 099 | Train loss: 1.0004 | Train acc: 49.94% | Val loss: 0.9922 | Val acc: 54.15% | LR: 0.000005
Epoch: 100 | Train loss: 0.9890 | Train acc: 50.81% | Val loss: 0.9938 | Val acc: 54.17% | LR: 0.000005
Epoch: 101 | Train loss: 0.9938 | Train acc: 50.55% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000005
Epoch: 102 | Train loss: 1.0004 | Train acc: 49.94% | Val loss: 0.9930 | Val acc: 54.14% | LR: 0.000005
Epoch: 103 | Train loss: 0.9950 | Train acc: 50.38% | Val loss: 0.9922 | Val acc: 54.14% | LR: 0.000005
Epoch: 104 | Train loss: 0.9935 | Train acc: 50.38% | Val loss: 0.9915 | Val acc: 54.26% | LR: 0.000005
Epoch: 105 | Train loss: 0.9896 | Train acc: 50.64% | Val loss: 0.9952 | Val acc: 54.20% | LR: 0.000004
Epoch: 106 | Train loss: 0.9973 | Train acc: 50.11% | Val loss: 0.9917 | Val acc: 54.30% | LR: 0.000004
Epoch: 107 | Train loss: 0.9870 | Train acc: 51.00% | Val loss: 0.9941 | Val acc: 54.14% | LR: 0.000004
Epoch: 108 | Train loss: 0.9892 | Train acc: 51.00% | Val loss: 0.9917 | Val acc: 54.26% | LR: 0.000004
Epoch: 109 | Train loss: 0.9994 | Train acc: 50.12% | Val loss: 0.9916 | Val acc: 54.21% | LR: 0.000004
Epoch: 110 | Train loss: 0.9932 | Train acc: 50.55% | Val loss: 0.9925 | Val acc: 54.13% | LR: 0.000004
Epoch: 111 | Train loss: 0.9939 | Train acc: 50.65% | Val loss: 0.9923 | Val acc: 54.10% | LR: 0.000004
Epoch: 112 | Train loss: 0.9946 | Train acc: 50.66% | Val loss: 0.9997 | Val acc: 54.17% | LR: 0.000004
Epoch: 113 | Train loss: 0.9928 | Train acc: 50.56% | Val loss: 0.9921 | Val acc: 54.18% | LR: 0.000003
Epoch: 114 | Train loss: 0.9932 | Train acc: 50.74% | Val loss: 0.9920 | Val acc: 54.26% | LR: 0.000003
Epoch: 115 | Train loss: 1.0001 | Train acc: 50.04% | Val loss: 0.9913 | Val acc: 54.28% | LR: 0.000003

[I 2025-09-23 18:04:52,768] Trial 96 finished with value: 0.5419901609420776 and parameters: {'lr': 1.8518261147787563e-05, 'hidden_size': 75, 'dropout': 0.26493824592907245, 'weight_decay': 3.1053975986243926e-05}. Best is trial 95 with value: 0.5447885513305664.

Epoch: 000 | Train loss: 1.0010 | Train acc: 49.41% | Val loss: 0.9945 | Val acc: 54.11% | LR: 0.000018
Epoch: 001 | Train loss: 1.0010 | Train acc: 49.58% | Val loss: 0.9944 | Val acc: 54.11% | LR: 0.000018
Epoch: 002 | Train loss: 1.0009 | Train acc: 50.07% | Val loss: 0.9944 | Val acc: 54.13% | LR: 0.000018
Epoch: 003 | Train loss: 1.0007 | Train acc: 49.70% | Val loss: 0.9944 | Val acc: 54.09% | LR: 0.000018
Epoch: 004 | Train loss: 1.0011 | Train acc: 49.55% | Val loss: 0.9947 | Val acc: 54.15% | LR: 0.000018
Epoch: 005 | Train loss: 1.0007 | Train acc: 49.71% | Val loss: 0.9944 | Val acc: 54.40% | LR: 0.000018
Epoch: 006 | Train loss: 1.0010 | Train acc: 49.33% | Val loss: 0.9957 | Val acc: 54.40% | LR: 0.000018
Epoch: 007 | Train loss: 1.0003 | Train acc: 49.94% | Val loss: 0.9945 | Val acc: 54.42% | LR: 0.000018
Epoch: 008 | Train loss: 1.0006 | Train acc: 49.65% | Val loss: 0.9941 | Val acc: 54.46% | LR: 0.000018
Epoch: 009 | Train loss: 1.0011 | Train acc: 49.31% | Val loss: 0.9941 | Val acc: 54.48% | LR: 0.000018
Epoch: 010 | Train loss: 1.0009 | Train acc: 49.32% | Val loss: 0.9941 | Val acc: 54.48% | LR: 0.000018
Epoch: 011 | Train loss: 1.0003 | Train acc: 49.76% | Val loss: 0.9941 | Val acc: 54.50% | LR: 0.000018
Epoch: 012 | Train loss: 0.9997 | Train acc: 50.38% | Val loss: 0.9941 | Val acc: 54.54% | LR: 0.000018
Epoch: 013 | Train loss: 1.0002 | Train acc: 49.85% | Val loss: 0.9948 | Val acc: 54.50% | LR: 0.000018
Epoch: 014 | Train loss: 0.9999 | Train acc: 49.94% | Val loss: 0.9944 | Val acc: 54.60% | LR: 0.000018
Epoch: 015 | Train loss: 0.9998 | Train acc: 49.85% | Val loss: 0.9943 | Val acc: 54.60% | LR: 0.000018
Epoch: 016 | Train loss: 0.9998 | Train acc: 49.85% | Val loss: 0.9940 | Val acc: 54.62% | LR: 0.000018
Epoch: 017 | Train loss: 0.9992 | Train acc: 50.22% | Val loss: 0.9939 | Val acc: 54.60% | LR: 0.000018
Epoch: 018 | Train loss: 1.0005 | Train acc: 49.42% | Val loss: 0.9941 | Val acc: 54.51% | LR: 0.000018
Epoch: 019 | Train loss: 1.0001 | Train acc: 49.62% | Val loss: 0.9941 | Val acc: 54.41% | LR: 0.000018
Epoch: 020 | Train loss: 0.9998 | Train acc: 49.80% | Val loss: 0.9942 | Val acc: 54.49% | LR: 0.000017
Epoch: 021 | Train loss: 0.9997 | Train acc: 49.82% | Val loss: 0.9937 | Val acc: 54.47% | LR: 0.000017
Epoch: 022 | Train loss: 0.9997 | Train acc: 50.01% | Val loss: 0.9938 | Val acc: 54.61% | LR: 0.000017
Epoch: 023 | Train loss: 0.9992 | Train acc: 50.12% | Val loss: 0.9937 | Val acc: 54.65% | LR: 0.000017
Epoch: 024 | Train loss: 0.9992 | Train acc: 50.19% | Val loss: 0.9937 | Val acc: 54.59% | LR: 0.000017
Epoch: 025 | Train loss: 0.9979 | Train acc: 50.39% | Val loss: 0.9936 | Val acc: 54.59% | LR: 0.000017
Epoch: 026 | Train loss: 0.9977 | Train acc: 50.83% | Val loss: 1.0020 | Val acc: 54.49% | LR: 0.000017
Epoch: 027 | Train loss: 0.9980 | Train acc: 51.07% | Val loss: 0.9941 | Val acc: 54.47% | LR: 0.000017
Epoch: 028 | Train loss: 0.9985 | Train acc: 50.81% | Val loss: 0.9940 | Val acc: 54.41% | LR: 0.000017
Epoch: 029 | Train loss: 0.9990 | Train acc: 50.52% | Val loss: 0.9939 | Val acc: 54.31% | LR: 0.000017
Epoch: 030 | Train loss: 0.9985 | Train acc: 50.69% | Val loss: 0.9939 | Val acc: 54.30% | LR: 0.000017
Epoch: 031 | Train loss: 0.9966 | Train acc: 51.07% | Val loss: 0.9939 | Val acc: 54.26% | LR: 0.000016
Epoch: 032 | Train loss: 0.9983 | Train acc: 50.60% | Val loss: 0.9939 | Val acc: 54.10% | LR: 0.000016
Epoch: 033 | Train loss: 0.9990 | Train acc: 50.41% | Val loss: 0.9940 | Val acc: 54.06% | LR: 0.000016
Epoch: 034 | Train loss: 0.9978 | Train acc: 50.70% | Val loss: 0.9936 | Val acc: 54.12% | LR: 0.000016
Epoch: 035 | Train loss: 0.9973 | Train acc: 50.88% | Val loss: 0.9937 | Val acc: 54.26% | LR: 0.000016
Epoch: 036 | Train loss: 1.0003 | Train acc: 50.02% | Val loss: 0.9940 | Val acc: 54.18% | LR: 0.000016
Epoch: 037 | Train loss: 0.9998 | Train acc: 50.04% | Val loss: 0.9937 | Val acc: 54.10% | LR: 0.000016
Epoch: 038 | Train loss: 0.9977 | Train acc: 50.60% | Val loss: 0.9945 | Val acc: 54.18% | LR: 0.000016
Epoch: 039 | Train loss: 0.9965 | Train acc: 50.81% | Val loss: 0.9939 | Val acc: 54.16% | LR: 0.000015
Epoch: 040 | Train loss: 0.9978 | Train acc: 50.53% | Val loss: 0.9940 | Val acc: 54.08% | LR: 0.000015
Epoch: 041 | Train loss: 0.9993 | Train acc: 50.19% | Val loss: 0.9953 | Val acc: 54.02% | LR: 0.000015
Epoch: 042 | Train loss: 0.9980 | Train acc: 50.47% | Val loss: 0.9934 | Val acc: 54.12% | LR: 0.000015
Epoch: 043 | Train loss: 1.0000 | Train acc: 50.27% | Val loss: 0.9933 | Val acc: 54.34% | LR: 0.000015
Epoch: 044 | Train loss: 0.9988 | Train acc: 50.34% | Val loss: 0.9942 | Val acc: 54.42% | LR: 0.000015
Epoch: 045 | Train loss: 0.9992 | Train acc: 50.25% | Val loss: 0.9935 | Val acc: 54.44% | LR: 0.000015
Epoch: 046 | Train loss: 0.9978 | Train acc: 50.51% | Val loss: 0.9958 | Val acc: 54.33% | LR: 0.000014
Epoch: 047 | Train loss: 0.9985 | Train acc: 50.35% | Val loss: 0.9935 | Val acc: 54.50% | LR: 0.000014
Epoch: 048 | Train loss: 1.0007 | Train acc: 50.04% | Val loss: 0.9936 | Val acc: 54.54% | LR: 0.000014
Epoch: 049 | Train loss: 0.9980 | Train acc: 50.57% | Val loss: 0.9935 | Val acc: 54.54% | LR: 0.000014
Epoch: 050 | Train loss: 0.9963 | Train acc: 50.83% | Val loss: 0.9939 | Val acc: 54.40% | LR: 0.000014
Epoch: 051 | Train loss: 0.9951 | Train acc: 51.19% | Val loss: 0.9937 | Val acc: 54.44% | LR: 0.000014
Epoch: 052 | Train loss: 0.9968 | Train acc: 50.66% | Val loss: 0.9937 | Val acc: 54.44% | LR: 0.000014
Epoch: 053 | Train loss: 0.9958 | Train acc: 50.81% | Val loss: 0.9938 | Val acc: 54.37% | LR: 0.000013
Epoch: 054 | Train loss: 0.9970 | Train acc: 50.81% | Val loss: 0.9942 | Val acc: 54.36% | LR: 0.000013
Epoch: 055 | Train loss: 0.9967 | Train acc: 50.48% | Val loss: 0.9933 | Val acc: 54.39% | LR: 0.000013
Epoch: 056 | Train loss: 0.9966 | Train acc: 50.66% | Val loss: 0.9934 | Val acc: 54.45% | LR: 0.000013
Epoch: 057 | Train loss: 0.9971 | Train acc: 50.48% | Val loss: 0.9934 | Val acc: 54.45% | LR: 0.000013
Epoch: 058 | Train loss: 0.9959 | Train acc: 50.56% | Val loss: 0.9935 | Val acc: 54.57% | LR: 0.000013
Epoch: 059 | Train loss: 0.9927 | Train acc: 51.18% | Val loss: 0.9941 | Val acc: 54.55% | LR: 0.000012
Epoch: 060 | Train loss: 0.9944 | Train acc: 50.85% | Val loss: 0.9933 | Val acc: 54.61% | LR: 0.000012
Epoch: 061 | Train loss: 0.9947 | Train acc: 50.69% | Val loss: 0.9934 | Val acc: 54.65% | LR: 0.000012
Epoch: 062 | Train loss: 0.9965 | Train acc: 50.51% | Val loss: 0.9934 | Val acc: 54.65% | LR: 0.000012
Epoch: 063 | Train loss: 0.9954 | Train acc: 50.67% | Val loss: 0.9934 | Val acc: 54.76% | LR: 0.000012
Epoch: 064 | Train loss: 0.9939 | Train acc: 51.02% | Val loss: 0.9933 | Val acc: 54.73% | LR: 0.000011
Epoch: 065 | Train loss: 0.9933 | Train acc: 50.85% | Val loss: 0.9934 | Val acc: 54.73% | LR: 0.000011
Epoch: 066 | Train loss: 0.9947 | Train acc: 50.77% | Val loss: 0.9935 | Val acc: 54.76% | LR: 0.000011
Epoch: 067 | Train loss: 0.9959 | Train acc: 50.58% | Val loss: 0.9931 | Val acc: 54.78% | LR: 0.000011
Epoch: 068 | Train loss: 0.9950 | Train acc: 50.66% | Val loss: 0.9930 | Val acc: 54.86% | LR: 0.000011
Epoch: 069 | Train loss: 0.9939 | Train acc: 51.10% | Val loss: 0.9930 | Val acc: 54.71% | LR: 0.000011
Epoch: 070 | Train loss: 0.9936 | Train acc: 51.12% | Val loss: 0.9930 | Val acc: 54.80% | LR: 0.000010
Epoch: 071 | Train loss: 0.9934 | Train acc: 50.86% | Val loss: 0.9930 | Val acc: 54.76% | LR: 0.000010
Epoch: 072 | Train loss: 0.9952 | Train acc: 50.68% | Val loss: 0.9930 | Val acc: 54.80% | LR: 0.000010
Epoch: 073 | Train loss: 0.9915 | Train acc: 51.56% | Val loss: 0.9930 | Val acc: 54.81% | LR: 0.000010
Epoch: 074 | Train loss: 0.9941 | Train acc: 50.86% | Val loss: 0.9930 | Val acc: 54.77% | LR: 0.000010
Epoch: 075 | Train loss: 0.9950 | Train acc: 50.60% | Val loss: 0.9930 | Val acc: 54.73% | LR: 0.000009
Epoch: 076 | Train loss: 0.9920 | Train acc: 50.95% | Val loss: 0.9930 | Val acc: 54.75% | LR: 0.000009
Epoch: 077 | Train loss: 0.9943 | Train acc: 51.11% | Val loss: 0.9930 | Val acc: 54.75% | LR: 0.000009
Epoch: 078 | Train loss: 0.9938 | Train acc: 50.85% | Val loss: 0.9929 | Val acc: 54.73% | LR: 0.000009
Epoch: 079 | Train loss: 0.9951 | Train acc: 50.67% | Val loss: 0.9929 | Val acc: 54.75% | LR: 0.000009
Epoch: 080 | Train loss: 0.9931 | Train acc: 50.94% | Val loss: 0.9929 | Val acc: 54.81% | LR: 0.000009
Epoch: 081 | Train loss: 0.9941 | Train acc: 50.85% | Val loss: 0.9929 | Val acc: 54.81% | LR: 0.000008
Epoch: 082 | Train loss: 0.9958 | Train acc: 50.50% | Val loss: 0.9929 | Val acc: 54.81% | LR: 0.000008
Epoch: 083 | Train loss: 0.9948 | Train acc: 50.67% | Val loss: 0.9929 | Val acc: 54.83% | LR: 0.000008
Epoch: 084 | Train loss: 0.9964 | Train acc: 50.76% | Val loss: 0.9929 | Val acc: 54.79% | LR: 0.000008
Epoch: 085 | Train loss: 0.9929 | Train acc: 50.94% | Val loss: 0.9929 | Val acc: 54.79% | LR: 0.000008
Epoch: 086 | Train loss: 0.9923 | Train acc: 51.02% | Val loss: 0.9929 | Val acc: 54.79% | LR: 0.000008
Epoch: 087 | Train loss: 0.9935 | Train acc: 50.75% | Val loss: 0.9929 | Val acc: 54.77% | LR: 0.000007
Epoch: 088 | Train loss: 0.9930 | Train acc: 50.93% | Val loss: 0.9929 | Val acc: 54.77% | LR: 0.000007
Epoch: 089 | Train loss: 0.9959 | Train acc: 50.48% | Val loss: 0.9928 | Val acc: 54.77% | LR: 0.000007
Epoch: 090 | Train loss: 0.9951 | Train acc: 50.58% | Val loss: 0.9928 | Val acc: 54.77% | LR: 0.000007
Epoch: 091 | Train loss: 0.9936 | Train acc: 50.95% | Val loss: 0.9928 | Val acc: 54.77% | LR: 0.000007
Epoch: 092 | Train loss: 0.9940 | Train acc: 50.86% | Val loss: 0.9928 | Val acc: 54.77% | LR: 0.000006
Epoch: 093 | Train loss: 0.9943 | Train acc: 50.95% | Val loss: 0.9928 | Val acc: 54.77% | LR: 0.000006
Epoch: 094 | Train loss: 0.9979 | Train acc: 50.42% | Val loss: 0.9928 | Val acc: 54.77% | LR: 0.000006
Epoch: 095 | Train loss: 0.9937 | Train acc: 50.96% | Val loss: 0.9927 | Val acc: 54.77% | LR: 0.000006
Epoch: 096 | Train loss: 0.9951 | Train acc: 50.78% | Val loss: 0.9927 | Val acc: 54.77% | LR: 0.000006
Epoch: 097 | Train loss: 0.9943 | Train acc: 50.77% | Val loss: 0.9927 | Val acc: 54.73% | LR: 0.000006
Epoch: 098 | Train loss: 0.9918 | Train acc: 51.03% | Val loss: 0.9927 | Val acc: 54.73% | LR: 0.000005
Epoch: 099 | Train loss: 0.9949 | Train acc: 50.50% | Val loss: 0.9927 | Val acc: 54.71% | LR: 0.000005
Epoch: 100 | Train loss: 0.9916 | Train acc: 51.04% | Val loss: 0.9927 | Val acc: 54.71% | LR: 0.000005
Epoch: 101 | Train loss: 0.9931 | Train acc: 50.95% | Val loss: 0.9927 | Val acc: 54.67% | LR: 0.000005
Epoch: 102 | Train loss: 0.9965 | Train acc: 50.68% | Val loss: 0.9927 | Val acc: 54.65% | LR: 0.000005
Epoch: 103 | Train loss: 0.9926 | Train acc: 50.77% | Val loss: 0.9927 | Val acc: 54.65% | LR: 0.000005
Epoch: 104 | Train loss: 0.9902 | Train acc: 51.20% | Val loss: 0.9927 | Val acc: 54.63% | LR: 0.000005
Epoch: 105 | Train loss: 0.9953 | Train acc: 50.57% | Val loss: 0.9926 | Val acc: 54.65% | LR: 0.000004
Epoch: 106 | Train loss: 0.9922 | Train acc: 51.10% | Val loss: 0.9926 | Val acc: 54.63% | LR: 0.000004
Epoch: 107 | Train loss: 0.9947 | Train acc: 50.67% | Val loss: 0.9926 | Val acc: 54.59% | LR: 0.000004
Epoch: 108 | Train loss: 0.9964 | Train acc: 50.40% | Val loss: 0.9926 | Val acc: 54.63% | LR: 0.000004
Epoch: 109 | Train loss: 0.9920 | Train acc: 50.83% | Val loss: 0.9926 | Val acc: 54.61% | LR: 0.000004
Epoch: 110 | Train loss: 0.9961 | Train acc: 50.48% | Val loss: 0.9926 | Val acc: 54.57% | LR: 0.000004
Epoch: 111 | Train loss: 0.9880 | Train acc: 51.54% | Val loss: 0.9926 | Val acc: 54.53% | LR: 0.000004
Epoch: 112 | Train loss: 0.9928 | Train acc: 50.74% | Val loss: 0.9926 | Val acc: 54.53% | LR: 0.000003
Epoch: 113 | Train loss: 0.9939 | Train acc: 50.92% | Val loss: 0.9926 | Val acc: 54.55% | LR: 0.000003
Epoch: 114 | Train loss: 0.9969 | Train acc: 50.12% | Val loss: 0.9926 | Val acc: 54.53% | LR: 0.000003
Epoch: 115 | Train loss: 0.9930 | Train acc: 50.65% | Val loss: 0.9926 | Val acc: 54.55% | LR: 0.000003
Epoch: 116 | Train loss: 0.9951 | Train acc: 50.65% | Val loss: 0.9926 | Val acc: 54.55% | LR: 0.000003
Epoch: 117 | Train loss: 0.9940 | Train acc: 50.57% | Val loss: 0.9926 | Val acc: 54.51% | LR: 0.000003

[I 2025-09-23 18:06:22,707] Trial 97 finished with value: 0.5451023578643799 and parameters: {'lr': 1.8318960643061677e-05, 'hidden_size': 74, 'dropout': 0.2649007895643807, 'weight_decay': 2.2103883295834924e-05}. Best is trial 97 with value: 0.5451023578643799.

Epoch: 000 | Train loss: 1.0018 | Train acc: 49.96% | Val loss: 0.9943 | Val acc: 53.92% | LR: 0.000018
Epoch: 001 | Train loss: 1.0000 | Train acc: 50.22% | Val loss: 0.9925 | Val acc: 54.03% | LR: 0.000018
Epoch: 002 | Train loss: 1.0005 | Train acc: 50.02% | Val loss: 0.9924 | Val acc: 53.90% | LR: 0.000018
Epoch: 003 | Train loss: 0.9981 | Train acc: 50.38% | Val loss: 0.9930 | Val acc: 54.02% | LR: 0.000018
Epoch: 004 | Train loss: 1.0002 | Train acc: 50.03% | Val loss: 0.9953 | Val acc: 53.64% | LR: 0.000018
Epoch: 005 | Train loss: 0.9997 | Train acc: 50.10% | Val loss: 0.9930 | Val acc: 53.84% | LR: 0.000018
Epoch: 006 | Train loss: 1.0005 | Train acc: 49.83% | Val loss: 0.9929 | Val acc: 53.92% | LR: 0.000018
Epoch: 007 | Train loss: 0.9968 | Train acc: 50.89% | Val loss: 0.9933 | Val acc: 53.88% | LR: 0.000018
Epoch: 008 | Train loss: 0.9996 | Train acc: 49.94% | Val loss: 1.0008 | Val acc: 53.68% | LR: 0.000018
Epoch: 009 | Train loss: 0.9987 | Train acc: 50.30% | Val loss: 0.9947 | Val acc: 53.88% | LR: 0.000018
Epoch: 010 | Train loss: 1.0005 | Train acc: 49.92% | Val loss: 0.9950 | Val acc: 53.88% | LR: 0.000018
Epoch: 011 | Train loss: 0.9989 | Train acc: 50.44% | Val loss: 0.9932 | Val acc: 53.82% | LR: 0.000018
Epoch: 012 | Train loss: 1.0002 | Train acc: 49.94% | Val loss: 0.9965 | Val acc: 54.05% | LR: 0.000018
Epoch: 013 | Train loss: 1.0003 | Train acc: 50.21% | Val loss: 0.9944 | Val acc: 53.89% | LR: 0.000018
Epoch: 014 | Train loss: 0.9983 | Train acc: 50.32% | Val loss: 0.9931 | Val acc: 53.93% | LR: 0.000018
Epoch: 015 | Train loss: 0.9993 | Train acc: 50.12% | Val loss: 0.9936 | Val acc: 53.96% | LR: 0.000018
Epoch: 016 | Train loss: 0.9997 | Train acc: 50.14% | Val loss: 0.9918 | Val acc: 53.98% | LR: 0.000018
Epoch: 017 | Train loss: 0.9993 | Train acc: 50.13% | Val loss: 0.9923 | Val acc: 54.09% | LR: 0.000018
Epoch: 018 | Train loss: 0.9987 | Train acc: 50.15% | Val loss: 0.9926 | Val acc: 53.89% | LR: 0.000018
Epoch: 019 | Train loss: 1.0003 | Train acc: 49.95% | Val loss: 0.9945 | Val acc: 53.83% | LR: 0.000018
Epoch: 020 | Train loss: 0.9978 | Train acc: 50.39% | Val loss: 0.9923 | Val acc: 54.02% | LR: 0.000017
Epoch: 021 | Train loss: 0.9971 | Train acc: 50.49% | Val loss: 0.9946 | Val acc: 53.94% | LR: 0.000017
Epoch: 022 | Train loss: 1.0000 | Train acc: 49.77% | Val loss: 1.0065 | Val acc: 53.85% | LR: 0.000017
Epoch: 023 | Train loss: 0.9982 | Train acc: 50.04% | Val loss: 0.9939 | Val acc: 53.95% | LR: 0.000017
Epoch: 024 | Train loss: 0.9986 | Train acc: 50.22% | Val loss: 0.9934 | Val acc: 53.86% | LR: 0.000017
Epoch: 025 | Train loss: 0.9985 | Train acc: 50.21% | Val loss: 0.9936 | Val acc: 53.80% | LR: 0.000017
Epoch: 026 | Train loss: 0.9987 | Train acc: 50.40% | Val loss: 0.9957 | Val acc: 53.90% | LR: 0.000017
Epoch: 027 | Train loss: 0.9980 | Train acc: 50.40% | Val loss: 0.9932 | Val acc: 53.95% | LR: 0.000017
Epoch: 028 | Train loss: 1.0026 | Train acc: 49.79% | Val loss: 0.9930 | Val acc: 53.85% | LR: 0.000017
Epoch: 029 | Train loss: 0.9995 | Train acc: 50.12% | Val loss: 0.9950 | Val acc: 53.88% | LR: 0.000017
Epoch: 030 | Train loss: 0.9993 | Train acc: 50.37% | Val loss: 0.9920 | Val acc: 54.05% | LR: 0.000016
Epoch: 031 | Train loss: 0.9978 | Train acc: 50.47% | Val loss: 0.9946 | Val acc: 53.93% | LR: 0.000016
Epoch: 032 | Train loss: 0.9978 | Train acc: 50.72% | Val loss: 0.9928 | Val acc: 53.91% | LR: 0.000016
Epoch: 033 | Train loss: 0.9976 | Train acc: 50.38% | Val loss: 0.9975 | Val acc: 53.97% | LR: 0.000016
Epoch: 034 | Train loss: 0.9963 | Train acc: 50.90% | Val loss: 0.9929 | Val acc: 53.89% | LR: 0.000016
Epoch: 035 | Train loss: 0.9900 | Train acc: 51.44% | Val loss: 0.9926 | Val acc: 53.89% | LR: 0.000016
Epoch: 036 | Train loss: 0.9946 | Train acc: 50.82% | Val loss: 0.9930 | Val acc: 53.93% | LR: 0.000016
Epoch: 037 | Train loss: 0.9956 | Train acc: 50.91% | Val loss: 0.9930 | Val acc: 53.93% | LR: 0.000016
Epoch: 038 | Train loss: 0.9987 | Train acc: 50.38% | Val loss: 0.9936 | Val acc: 53.87% | LR: 0.000016
Epoch: 039 | Train loss: 0.9940 | Train acc: 51.08% | Val loss: 0.9929 | Val acc: 54.01% | LR: 0.000015
Epoch: 040 | Train loss: 0.9999 | Train acc: 50.11% | Val loss: 0.9930 | Val acc: 53.93% | LR: 0.000015
Epoch: 041 | Train loss: 0.9994 | Train acc: 50.36% | Val loss: 0.9925 | Val acc: 54.05% | LR: 0.000015
Epoch: 042 | Train loss: 1.0007 | Train acc: 50.19% | Val loss: 0.9926 | Val acc: 54.01% | LR: 0.000015
Epoch: 043 | Train loss: 0.9978 | Train acc: 50.46% | Val loss: 0.9923 | Val acc: 53.99% | LR: 0.000015
Epoch: 044 | Train loss: 0.9983 | Train acc: 50.45% | Val loss: 0.9940 | Val acc: 53.97% | LR: 0.000015
Epoch: 045 | Train loss: 0.9958 | Train acc: 50.64% | Val loss: 0.9924 | Val acc: 53.99% | LR: 0.000015
Epoch: 046 | Train loss: 0.9959 | Train acc: 50.64% | Val loss: 0.9923 | Val acc: 54.03% | LR: 0.000014
Epoch: 047 | Train loss: 0.9943 | Train acc: 50.90% | Val loss: 1.0691 | Val acc: 53.98% | LR: 0.000014
Epoch: 048 | Train loss: 0.9984 | Train acc: 50.37% | Val loss: 0.9923 | Val acc: 53.97% | LR: 0.000014
Epoch: 049 | Train loss: 0.9977 | Train acc: 50.20% | Val loss: 0.9922 | Val acc: 53.93% | LR: 0.000014
Epoch: 050 | Train loss: 0.9996 | Train acc: 50.37% | Val loss: 0.9919 | Val acc: 54.05% | LR: 0.000014
Epoch: 051 | Train loss: 0.9931 | Train acc: 50.90% | Val loss: 1.0010 | Val acc: 53.85% | LR: 0.000014
Epoch: 052 | Train loss: 0.9969 | Train acc: 50.55% | Val loss: 0.9938 | Val acc: 53.95% | LR: 0.000013
Epoch: 053 | Train loss: 0.9991 | Train acc: 50.19% | Val loss: 0.9922 | Val acc: 54.05% | LR: 0.000013
Epoch: 054 | Train loss: 0.9975 | Train acc: 50.37% | Val loss: 0.9927 | Val acc: 53.83% | LR: 0.000013
Epoch: 055 | Train loss: 0.9977 | Train acc: 50.46% | Val loss: 0.9926 | Val acc: 54.03% | LR: 0.000013
Epoch: 056 | Train loss: 0.9950 | Train acc: 50.54% | Val loss: 0.9921 | Val acc: 53.99% | LR: 0.000013
Epoch: 057 | Train loss: 0.9985 | Train acc: 50.18% | Val loss: 0.9921 | Val acc: 54.03% | LR: 0.000013
Epoch: 058 | Train loss: 0.9966 | Train acc: 50.55% | Val loss: 0.9936 | Val acc: 53.99% | LR: 0.000012
Epoch: 059 | Train loss: 0.9908 | Train acc: 51.08% | Val loss: 0.9915 | Val acc: 54.17% | LR: 0.000012
Epoch: 060 | Train loss: 0.9956 | Train acc: 50.55% | Val loss: 0.9919 | Val acc: 54.15% | LR: 0.000012
Epoch: 061 | Train loss: 0.9971 | Train acc: 50.54% | Val loss: 0.9923 | Val acc: 54.09% | LR: 0.000012
Epoch: 062 | Train loss: 0.9915 | Train acc: 50.99% | Val loss: 0.9924 | Val acc: 54.11% | LR: 0.000012
Epoch: 063 | Train loss: 0.9963 | Train acc: 50.36% | Val loss: 0.9925 | Val acc: 54.13% | LR: 0.000012
Epoch: 064 | Train loss: 0.9999 | Train acc: 50.10% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000011
Epoch: 065 | Train loss: 1.0002 | Train acc: 49.93% | Val loss: 0.9921 | Val acc: 54.05% | LR: 0.000011
Epoch: 066 | Train loss: 1.0004 | Train acc: 50.10% | Val loss: 0.9925 | Val acc: 54.18% | LR: 0.000011
Epoch: 067 | Train loss: 0.9984 | Train acc: 50.29% | Val loss: 0.9921 | Val acc: 54.12% | LR: 0.000011
Epoch: 068 | Train loss: 0.9970 | Train acc: 50.38% | Val loss: 0.9918 | Val acc: 54.20% | LR: 0.000011
Epoch: 069 | Train loss: 0.9930 | Train acc: 50.73% | Val loss: 0.9926 | Val acc: 54.16% | LR: 0.000011
Epoch: 070 | Train loss: 0.9952 | Train acc: 50.29% | Val loss: 0.9924 | Val acc: 54.09% | LR: 0.000010
Epoch: 071 | Train loss: 0.9917 | Train acc: 50.74% | Val loss: 0.9923 | Val acc: 54.20% | LR: 0.000010
Epoch: 072 | Train loss: 0.9956 | Train acc: 50.47% | Val loss: 0.9925 | Val acc: 54.04% | LR: 0.000010
Epoch: 073 | Train loss: 0.9970 | Train acc: 50.21% | Val loss: 0.9923 | Val acc: 54.14% | LR: 0.000010
Epoch: 074 | Train loss: 0.9961 | Train acc: 50.48% | Val loss: 1.0059 | Val acc: 54.34% | LR: 0.000010
Epoch: 075 | Train loss: 0.9994 | Train acc: 50.20% | Val loss: 0.9936 | Val acc: 54.32% | LR: 0.000009
Epoch: 076 | Train loss: 0.9957 | Train acc: 50.56% | Val loss: 0.9968 | Val acc: 54.26% | LR: 0.000009
Epoch: 077 | Train loss: 0.9966 | Train acc: 50.40% | Val loss: 0.9920 | Val acc: 54.24% | LR: 0.000009
Epoch: 078 | Train loss: 0.9915 | Train acc: 50.73% | Val loss: 0.9915 | Val acc: 54.20% | LR: 0.000009
Epoch: 079 | Train loss: 0.9913 | Train acc: 50.82% | Val loss: 0.9924 | Val acc: 54.28% | LR: 0.000009
Epoch: 080 | Train loss: 0.9975 | Train acc: 50.40% | Val loss: 0.9932 | Val acc: 54.16% | LR: 0.000009
Epoch: 081 | Train loss: 0.9922 | Train acc: 50.84% | Val loss: 0.9942 | Val acc: 54.28% | LR: 0.000008
Epoch: 082 | Train loss: 0.9965 | Train acc: 50.14% | Val loss: 0.9942 | Val acc: 54.08% | LR: 0.000008
Epoch: 083 | Train loss: 0.9920 | Train acc: 50.84% | Val loss: 0.9926 | Val acc: 54.24% | LR: 0.000008
Epoch: 084 | Train loss: 0.9959 | Train acc: 50.57% | Val loss: 0.9925 | Val acc: 54.26% | LR: 0.000008
Epoch: 085 | Train loss: 1.0051 | Train acc: 49.77% | Val loss: 0.9932 | Val acc: 54.30% | LR: 0.000008
Epoch: 086 | Train loss: 0.9916 | Train acc: 50.75% | Val loss: 0.9915 | Val acc: 54.24% | LR: 0.000007
Epoch: 087 | Train loss: 0.9943 | Train acc: 50.49% | Val loss: 0.9926 | Val acc: 54.20% | LR: 0.000007
Epoch: 088 | Train loss: 0.9954 | Train acc: 50.58% | Val loss: 0.9931 | Val acc: 54.20% | LR: 0.000007
Epoch: 089 | Train loss: 0.9886 | Train acc: 51.02% | Val loss: 0.9922 | Val acc: 54.32% | LR: 0.000007
Epoch: 090 | Train loss: 0.9890 | Train acc: 51.01% | Val loss: 0.9949 | Val acc: 54.26% | LR: 0.000007
Epoch: 091 | Train loss: 0.9944 | Train acc: 50.48% | Val loss: 0.9921 | Val acc: 54.28% | LR: 0.000007
Epoch: 092 | Train loss: 0.9933 | Train acc: 50.57% | Val loss: 0.9925 | Val acc: 54.24% | LR: 0.000006
Epoch: 093 | Train loss: 0.9964 | Train acc: 50.39% | Val loss: 0.9922 | Val acc: 54.16% | LR: 0.000006
Epoch: 094 | Train loss: 0.9969 | Train acc: 50.48% | Val loss: 0.9930 | Val acc: 54.14% | LR: 0.000006
Epoch: 095 | Train loss: 0.9943 | Train acc: 50.56% | Val loss: 0.9931 | Val acc: 54.34% | LR: 0.000006
Epoch: 096 | Train loss: 0.9939 | Train acc: 50.39% | Val loss: 0.9939 | Val acc: 54.18% | LR: 0.000006
Epoch: 097 | Train loss: 0.9962 | Train acc: 50.49% | Val loss: 0.9916 | Val acc: 54.25% | LR: 0.000006
Epoch: 098 | Train loss: 0.9903 | Train acc: 50.84% | Val loss: 0.9923 | Val acc: 54.14% | LR: 0.000005
Epoch: 099 | Train loss: 1.0008 | Train acc: 49.96% | Val loss: 0.9937 | Val acc: 54.21% | LR: 0.000005
Epoch: 100 | Train loss: 0.9891 | Train acc: 50.82% | Val loss: 0.9912 | Val acc: 54.25% | LR: 0.000005
Epoch: 101 | Train loss: 0.9938 | Train acc: 50.56% | Val loss: 0.9928 | Val acc: 54.14% | LR: 0.000005
Epoch: 102 | Train loss: 1.0006 | Train acc: 49.95% | Val loss: 0.9917 | Val acc: 54.26% | LR: 0.000005
Epoch: 103 | Train loss: 0.9951 | Train acc: 50.40% | Val loss: 0.9925 | Val acc: 54.22% | LR: 0.000005
Epoch: 104 | Train loss: 0.9936 | Train acc: 50.39% | Val loss: 0.9914 | Val acc: 54.37% | LR: 0.000005
Epoch: 105 | Train loss: 0.9896 | Train acc: 50.65% | Val loss: 0.9924 | Val acc: 54.18% | LR: 0.000004
Epoch: 106 | Train loss: 0.9976 | Train acc: 50.13% | Val loss: 0.9920 | Val acc: 54.20% | LR: 0.000004
Epoch: 107 | Train loss: 0.9870 | Train acc: 51.01% | Val loss: 0.9919 | Val acc: 54.26% | LR: 0.000004
Epoch: 108 | Train loss: 0.9895 | Train acc: 51.01% | Val loss: 0.9928 | Val acc: 54.30% | LR: 0.000004
Epoch: 109 | Train loss: 0.9998 | Train acc: 50.13% | Val loss: 0.9950 | Val acc: 54.24% | LR: 0.000004
Epoch: 110 | Train loss: 0.9934 | Train acc: 50.57% | Val loss: 0.9924 | Val acc: 54.24% | LR: 0.000004
Epoch: 111 | Train loss: 0.9942 | Train acc: 50.66% | Val loss: 0.9924 | Val acc: 54.24% | LR: 0.000004
Epoch: 112 | Train loss: 0.9949 | Train acc: 50.66% | Val loss: 0.9923 | Val acc: 54.24% | LR: 0.000003
Epoch: 113 | Train loss: 0.9928 | Train acc: 50.56% | Val loss: 0.9923 | Val acc: 54.24% | LR: 0.000003
Epoch: 114 | Train loss: 0.9934 | Train acc: 50.74% | Val loss: 0.9922 | Val acc: 54.24% | LR: 0.000003
Epoch: 115 | Train loss: 1.0003 | Train acc: 50.03% | Val loss: 0.9922 | Val acc: 54.24% | LR: 0.000003
Epoch: 116 | Train loss: 0.9895 | Train acc: 50.82% | Val loss: 0.9928 | Val acc: 54.20% | LR: 0.000003
Epoch: 117 | Train loss: 1.0003 | Train acc: 50.03% | Val loss: 0.9923 | Val acc: 54.20% | LR: 0.000003
Epoch: 118 | Train loss: 0.9984 | Train acc: 50.30% | Val loss: 0.9927 | Val acc: 54.20% | LR: 0.000003
Epoch: 119 | Train loss: 0.9894 | Train acc: 50.91% | Val loss: 0.9924 | Val acc: 54.20% | LR: 0.000003
Epoch: 120 | Train loss: 0.9916 | Train acc: 50.65% | Val loss: 0.9924 | Val acc: 54.18% | LR: 0.000003
Epoch: 121 | Train loss: 0.9865 | Train acc: 51.09% | Val loss: 0.9924 | Val acc: 54.20% | LR: 0.000002
Epoch: 122 | Train loss: 0.9913 | Train acc: 50.74% | Val loss: 0.9927 | Val acc: 54.18% | LR: 0.000002
Epoch: 123 | Train loss: 0.9899 | Train acc: 50.74% | Val loss: 0.9922 | Val acc: 54.16% | LR: 0.000002
Epoch: 124 | Train loss: 0.9863 | Train acc: 51.19% | Val loss: 0.9923 | Val acc: 54.20% | LR: 0.000002
Epoch: 125 | Train loss: 0.9935 | Train acc: 50.41% | Val loss: 0.9924 | Val acc: 54.22% | LR: 0.000002
Epoch: 126 | Train loss: 1.0024 | Train acc: 50.05% | Val loss: 0.9922 | Val acc: 54.20% | LR: 0.000002
Epoch: 127 | Train loss: 0.9945 | Train acc: 50.59% | Val loss: 0.9953 | Val acc: 54.24% | LR: 0.000002
Epoch: 128 | Train loss: 0.9882 | Train acc: 51.03% | Val loss: 0.9924 | Val acc: 54.20% | LR: 0.000002
Epoch: 129 | Train loss: 0.9809 | Train acc: 51.38% | Val loss: 0.9923 | Val acc: 54.24% | LR: 0.000002
Epoch: 130 | Train loss: 0.9994 | Train acc: 50.31% | Val loss: 0.9925 | Val acc: 54.16% | LR: 0.000002
Epoch: 131 | Train loss: 0.9902 | Train acc: 50.67% | Val loss: 0.9922 | Val acc: 54.24% | LR: 0.000002
Epoch: 132 | Train loss: 0.9965 | Train acc: 50.31% | Val loss: 0.9925 | Val acc: 54.22% | LR: 0.000002
Epoch: 133 | Train loss: 0.9972 | Train acc: 50.49% | Val loss: 0.9972 | Val acc: 54.14% | LR: 0.000001
Epoch: 134 | Train loss: 0.9933 | Train acc: 50.49% | Val loss: 0.9926 | Val acc: 54.22% | LR: 0.000001
Epoch: 135 | Train loss: 0.9937 | Train acc: 50.58% | Val loss: 0.9977 | Val acc: 54.20% | LR: 0.000001
Epoch: 136 | Train loss: 0.9933 | Train acc: 50.49% | Val loss: 1.0000 | Val acc: 54.18% | LR: 0.000001
Epoch: 137 | Train loss: 0.9936 | Train acc: 50.59% | Val loss: 0.9926 | Val acc: 54.18% | LR: 0.000001
Epoch: 138 | Train loss: 0.9998 | Train acc: 50.05% | Val loss: 0.9952 | Val acc: 54.16% | LR: 0.000001
Epoch: 139 | Train loss: 0.9957 | Train acc: 50.40% | Val loss: 0.9925 | Val acc: 54.18% | LR: 0.000001
Epoch: 140 | Train loss: 0.9929 | Train acc: 50.66% | Val loss: 0.9925 | Val acc: 54.18% | LR: 0.000001
Epoch: 141 | Train loss: 1.0001 | Train acc: 50.13% | Val loss: 1.0030 | Val acc: 54.18% | LR: 0.000001
Epoch: 142 | Train loss: 0.9862 | Train acc: 51.11% | Val loss: 0.9937 | Val acc: 54.22% | LR: 0.000001
Epoch: 143 | Train loss: 0.9927 | Train acc: 50.49% | Val loss: 0.9931 | Val acc: 54.18% | LR: 0.000001
Epoch: 144 | Train loss: 0.9929 | Train acc: 50.66% | Val loss: 0.9927 | Val acc: 54.18% | LR: 0.000001
Epoch: 145 | Train loss: 0.9830 | Train acc: 51.02% | Val loss: 0.9926 | Val acc: 54.22% | LR: 0.000001
Epoch: 146 | Train loss: 0.9904 | Train acc: 50.66% | Val loss: 0.9925 | Val acc: 54.22% | LR: 0.000001
Epoch: 147 | Train loss: 0.9928 | Train acc: 50.58% | Val loss: 0.9930 | Val acc: 54.18% | LR: 0.000001
Epoch: 148 | Train loss: 0.9992 | Train acc: 50.13% | Val loss: 0.9927 | Val acc: 54.18% | LR: 0.000001
Epoch: 149 | Train loss: 0.9979 | Train acc: 50.13% | Val loss: 0.9950 | Val acc: 54.18% | LR: 0.000001

[I 2025-09-23 18:08:26,604] Trial 98 finished with value: 0.5418076515197754 and parameters: {'lr': 1.8251905448589537e-05, 'hidden_size': 75, 'dropout': 0.26601326621951615, 'weight_decay': 1.9947752609244068e-05}. Best is trial 97 with value: 0.5451023578643799.

Epoch: 000 | Train loss: 1.0010 | Train acc: 49.41% | Val loss: 0.9945 | Val acc: 54.11% | LR: 0.000018
Epoch: 001 | Train loss: 1.0009 | Train acc: 49.59% | Val loss: 0.9942 | Val acc: 54.09% | LR: 0.000018
Epoch: 002 | Train loss: 1.0005 | Train acc: 49.23% | Val loss: 0.9944 | Val acc: 54.26% | LR: 0.000018
Epoch: 003 | Train loss: 1.0007 | Train acc: 49.94% | Val loss: 0.9943 | Val acc: 54.34% | LR: 0.000018
Epoch: 004 | Train loss: 1.0010 | Train acc: 49.50% | Val loss: 0.9943 | Val acc: 54.36% | LR: 0.000018
Epoch: 005 | Train loss: 1.0006 | Train acc: 49.68% | Val loss: 0.9943 | Val acc: 54.46% | LR: 0.000018
Epoch: 006 | Train loss: 1.0010 | Train acc: 49.32% | Val loss: 0.9943 | Val acc: 54.46% | LR: 0.000018
Epoch: 007 | Train loss: 1.0002 | Train acc: 50.10% | Val loss: 0.9943 | Val acc: 54.46% | LR: 0.000018
Epoch: 008 | Train loss: 1.0005 | Train acc: 49.64% | Val loss: 0.9955 | Val acc: 54.46% | LR: 0.000018
Epoch: 009 | Train loss: 1.0012 | Train acc: 49.30% | Val loss: 0.9943 | Val acc: 54.48% | LR: 0.000018
Epoch: 010 | Train loss: 1.0009 | Train acc: 49.31% | Val loss: 0.9940 | Val acc: 54.50% | LR: 0.000018
Epoch: 011 | Train loss: 1.0004 | Train acc: 49.75% | Val loss: 0.9940 | Val acc: 54.54% | LR: 0.000018
Epoch: 012 | Train loss: 0.9996 | Train acc: 50.38% | Val loss: 0.9940 | Val acc: 54.58% | LR: 0.000018
Epoch: 013 | Train loss: 1.0002 | Train acc: 49.84% | Val loss: 0.9942 | Val acc: 54.52% | LR: 0.000018
Epoch: 014 | Train loss: 0.9999 | Train acc: 49.94% | Val loss: 0.9940 | Val acc: 54.58% | LR: 0.000018
Epoch: 015 | Train loss: 0.9997 | Train acc: 49.85% | Val loss: 0.9939 | Val acc: 54.59% | LR: 0.000018
Epoch: 016 | Train loss: 0.9998 | Train acc: 49.85% | Val loss: 0.9939 | Val acc: 54.61% | LR: 0.000018
Epoch: 017 | Train loss: 0.9991 | Train acc: 50.21% | Val loss: 0.9945 | Val acc: 54.49% | LR: 0.000018
Epoch: 018 | Train loss: 1.0005 | Train acc: 49.42% | Val loss: 0.9937 | Val acc: 54.47% | LR: 0.000018
Epoch: 019 | Train loss: 1.0001 | Train acc: 49.62% | Val loss: 0.9945 | Val acc: 54.55% | LR: 0.000018
Epoch: 020 | Train loss: 0.9997 | Train acc: 49.82% | Val loss: 0.9934 | Val acc: 54.59% | LR: 0.000017
Epoch: 021 | Train loss: 0.9997 | Train acc: 49.84% | Val loss: 0.9942 | Val acc: 54.57% | LR: 0.000017
Epoch: 022 | Train loss: 0.9997 | Train acc: 50.14% | Val loss: 0.9942 | Val acc: 54.57% | LR: 0.000017
Epoch: 023 | Train loss: 0.9991 | Train acc: 50.48% | Val loss: 0.9939 | Val acc: 54.59% | LR: 0.000017
Epoch: 024 | Train loss: 0.9992 | Train acc: 50.04% | Val loss: 0.9940 | Val acc: 54.49% | LR: 0.000017
Epoch: 025 | Train loss: 0.9977 | Train acc: 50.85% | Val loss: 0.9992 | Val acc: 54.53% | LR: 0.000017
Epoch: 026 | Train loss: 0.9976 | Train acc: 51.17% | Val loss: 0.9937 | Val acc: 54.59% | LR: 0.000017
Epoch: 027 | Train loss: 0.9980 | Train acc: 51.13% | Val loss: 0.9937 | Val acc: 54.44% | LR: 0.000017
Epoch: 028 | Train loss: 0.9986 | Train acc: 50.76% | Val loss: 0.9938 | Val acc: 54.30% | LR: 0.000017
Epoch: 029 | Train loss: 0.9990 | Train acc: 50.48% | Val loss: 0.9938 | Val acc: 54.24% | LR: 0.000017
Epoch: 030 | Train loss: 0.9987 | Train acc: 50.68% | Val loss: 0.9938 | Val acc: 54.22% | LR: 0.000017
Epoch: 031 | Train loss: 0.9967 | Train acc: 51.05% | Val loss: 0.9938 | Val acc: 54.14% | LR: 0.000016
Epoch: 032 | Train loss: 0.9983 | Train acc: 50.61% | Val loss: 0.9938 | Val acc: 54.08% | LR: 0.000016
Epoch: 033 | Train loss: 0.9992 | Train acc: 50.43% | Val loss: 0.9937 | Val acc: 54.10% | LR: 0.000016
Epoch: 034 | Train loss: 0.9978 | Train acc: 50.72% | Val loss: 0.9942 | Val acc: 54.08% | LR: 0.000016
Epoch: 035 | Train loss: 0.9974 | Train acc: 50.88% | Val loss: 0.9942 | Val acc: 54.18% | LR: 0.000016
Epoch: 036 | Train loss: 1.0003 | Train acc: 50.02% | Val loss: 0.9943 | Val acc: 54.18% | LR: 0.000016
Epoch: 037 | Train loss: 1.0000 | Train acc: 50.03% | Val loss: 0.9935 | Val acc: 54.12% | LR: 0.000016
Epoch: 038 | Train loss: 0.9978 | Train acc: 50.62% | Val loss: 0.9937 | Val acc: 54.10% | LR: 0.000016
Epoch: 039 | Train loss: 0.9966 | Train acc: 50.79% | Val loss: 0.9937 | Val acc: 54.24% | LR: 0.000015
Epoch: 040 | Train loss: 0.9980 | Train acc: 50.55% | Val loss: 0.9945 | Val acc: 54.14% | LR: 0.000015
Epoch: 041 | Train loss: 0.9994 | Train acc: 50.20% | Val loss: 0.9935 | Val acc: 54.06% | LR: 0.000015
Epoch: 042 | Train loss: 0.9980 | Train acc: 50.49% | Val loss: 0.9948 | Val acc: 54.30% | LR: 0.000015
Epoch: 043 | Train loss: 1.0001 | Train acc: 50.26% | Val loss: 0.9936 | Val acc: 54.49% | LR: 0.000015
Epoch: 044 | Train loss: 0.9990 | Train acc: 50.25% | Val loss: 0.9935 | Val acc: 54.55% | LR: 0.000015
Epoch: 045 | Train loss: 0.9992 | Train acc: 50.25% | Val loss: 0.9935 | Val acc: 54.39% | LR: 0.000015
Epoch: 046 | Train loss: 0.9980 | Train acc: 50.52% | Val loss: 0.9935 | Val acc: 54.36% | LR: 0.000014
Epoch: 047 | Train loss: 0.9986 | Train acc: 50.35% | Val loss: 0.9935 | Val acc: 54.46% | LR: 0.000014
Epoch: 048 | Train loss: 1.0009 | Train acc: 50.03% | Val loss: 0.9936 | Val acc: 54.42% | LR: 0.000014
Epoch: 049 | Train loss: 0.9982 | Train acc: 50.57% | Val loss: 0.9935 | Val acc: 54.42% | LR: 0.000014
Epoch: 050 | Train loss: 0.9967 | Train acc: 50.84% | Val loss: 0.9935 | Val acc: 54.36% | LR: 0.000014
Epoch: 051 | Train loss: 0.9952 | Train acc: 51.18% | Val loss: 0.9935 | Val acc: 54.34% | LR: 0.000014
Epoch: 052 | Train loss: 0.9973 | Train acc: 50.75% | Val loss: 0.9934 | Val acc: 54.36% | LR: 0.000014
Epoch: 053 | Train loss: 0.9966 | Train acc: 50.83% | Val loss: 0.9933 | Val acc: 54.40% | LR: 0.000013
Epoch: 054 | Train loss: 0.9970 | Train acc: 50.83% | Val loss: 0.9932 | Val acc: 54.44% | LR: 0.000013
Epoch: 055 | Train loss: 0.9986 | Train acc: 50.44% | Val loss: 0.9932 | Val acc: 54.54% | LR: 0.000013
Epoch: 056 | Train loss: 0.9978 | Train acc: 50.67% | Val loss: 0.9931 | Val acc: 54.55% | LR: 0.000013
Epoch: 057 | Train loss: 0.9985 | Train acc: 50.50% | Val loss: 0.9931 | Val acc: 54.53% | LR: 0.000013
Epoch: 058 | Train loss: 0.9970 | Train acc: 50.59% | Val loss: 0.9931 | Val acc: 54.57% | LR: 0.000013
Epoch: 059 | Train loss: 0.9939 | Train acc: 51.21% | Val loss: 0.9931 | Val acc: 54.59% | LR: 0.000012
Epoch: 060 | Train loss: 0.9958 | Train acc: 50.84% | Val loss: 0.9931 | Val acc: 54.51% | LR: 0.000012
Epoch: 061 | Train loss: 0.9978 | Train acc: 50.63% | Val loss: 1.0075 | Val acc: 54.61% | LR: 0.000012
Epoch: 062 | Train loss: 0.9970 | Train acc: 50.44% | Val loss: 0.9930 | Val acc: 54.68% | LR: 0.000012
Epoch: 063 | Train loss: 0.9964 | Train acc: 50.63% | Val loss: 0.9931 | Val acc: 54.62% | LR: 0.000012
Epoch: 064 | Train loss: 0.9946 | Train acc: 50.98% | Val loss: 0.9934 | Val acc: 54.56% | LR: 0.000011
Epoch: 065 | Train loss: 0.9956 | Train acc: 50.81% | Val loss: 0.9933 | Val acc: 54.58% | LR: 0.000011
Epoch: 066 | Train loss: 0.9958 | Train acc: 50.73% | Val loss: 0.9933 | Val acc: 54.70% | LR: 0.000011
Epoch: 067 | Train loss: 0.9980 | Train acc: 50.57% | Val loss: 0.9933 | Val acc: 54.72% | LR: 0.000011
Epoch: 068 | Train loss: 0.9964 | Train acc: 50.66% | Val loss: 0.9932 | Val acc: 54.72% | LR: 0.000011
Epoch: 069 | Train loss: 0.9945 | Train acc: 51.12% | Val loss: 0.9932 | Val acc: 54.82% | LR: 0.000011
Epoch: 070 | Train loss: 0.9938 | Train acc: 51.12% | Val loss: 0.9932 | Val acc: 54.74% | LR: 0.000010
Epoch: 071 | Train loss: 0.9959 | Train acc: 50.86% | Val loss: 0.9931 | Val acc: 54.76% | LR: 0.000010
Epoch: 072 | Train loss: 0.9955 | Train acc: 50.68% | Val loss: 0.9931 | Val acc: 54.73% | LR: 0.000010
Epoch: 073 | Train loss: 0.9914 | Train acc: 51.58% | Val loss: 0.9931 | Val acc: 54.67% | LR: 0.000010
Epoch: 074 | Train loss: 0.9953 | Train acc: 50.86% | Val loss: 0.9931 | Val acc: 54.73% | LR: 0.000010
Epoch: 075 | Train loss: 0.9964 | Train acc: 50.59% | Val loss: 0.9930 | Val acc: 54.73% | LR: 0.000009
Epoch: 076 | Train loss: 0.9955 | Train acc: 50.95% | Val loss: 0.9930 | Val acc: 54.73% | LR: 0.000009
Epoch: 077 | Train loss: 0.9930 | Train acc: 51.12% | Val loss: 0.9935 | Val acc: 54.73% | LR: 0.000009
Epoch: 078 | Train loss: 0.9937 | Train acc: 50.86% | Val loss: 0.9932 | Val acc: 54.71% | LR: 0.000009
Epoch: 079 | Train loss: 0.9957 | Train acc: 50.69% | Val loss: 0.9932 | Val acc: 54.68% | LR: 0.000009
Epoch: 080 | Train loss: 0.9944 | Train acc: 50.95% | Val loss: 0.9932 | Val acc: 54.56% | LR: 0.000009
Epoch: 081 | Train loss: 0.9953 | Train acc: 50.86% | Val loss: 0.9927 | Val acc: 54.56% | LR: 0.000008
Epoch: 082 | Train loss: 0.9970 | Train acc: 50.50% | Val loss: 0.9927 | Val acc: 54.66% | LR: 0.000008
Epoch: 083 | Train loss: 0.9969 | Train acc: 50.69% | Val loss: 0.9928 | Val acc: 54.68% | LR: 0.000008
Epoch: 084 | Train loss: 0.9949 | Train acc: 50.77% | Val loss: 0.9928 | Val acc: 54.62% | LR: 0.000008
Epoch: 085 | Train loss: 0.9931 | Train acc: 50.94% | Val loss: 0.9928 | Val acc: 54.64% | LR: 0.000008
Epoch: 086 | Train loss: 0.9925 | Train acc: 51.01% | Val loss: 0.9926 | Val acc: 54.62% | LR: 0.000008
Epoch: 087 | Train loss: 0.9951 | Train acc: 50.74% | Val loss: 0.9927 | Val acc: 54.52% | LR: 0.000007
Epoch: 088 | Train loss: 0.9937 | Train acc: 50.92% | Val loss: 0.9929 | Val acc: 54.54% | LR: 0.000007
Epoch: 089 | Train loss: 0.9970 | Train acc: 50.48% | Val loss: 0.9928 | Val acc: 54.53% | LR: 0.000007
Epoch: 090 | Train loss: 0.9955 | Train acc: 50.50% | Val loss: 0.9928 | Val acc: 54.49% | LR: 0.000007
Epoch: 091 | Train loss: 0.9938 | Train acc: 50.95% | Val loss: 0.9928 | Val acc: 54.49% | LR: 0.000007
Epoch: 092 | Train loss: 0.9942 | Train acc: 50.86% | Val loss: 0.9929 | Val acc: 54.47% | LR: 0.000006
Epoch: 093 | Train loss: 0.9936 | Train acc: 50.95% | Val loss: 0.9928 | Val acc: 54.49% | LR: 0.000006
Epoch: 094 | Train loss: 0.9977 | Train acc: 50.42% | Val loss: 0.9928 | Val acc: 54.49% | LR: 0.000006
Epoch: 095 | Train loss: 0.9939 | Train acc: 50.95% | Val loss: 0.9928 | Val acc: 54.49% | LR: 0.000006
Epoch: 096 | Train loss: 0.9955 | Train acc: 50.77% | Val loss: 0.9928 | Val acc: 54.51% | LR: 0.000006
Epoch: 097 | Train loss: 0.9951 | Train acc: 50.78% | Val loss: 0.9927 | Val acc: 54.51% | LR: 0.000006
Epoch: 098 | Train loss: 0.9916 | Train acc: 51.05% | Val loss: 0.9928 | Val acc: 54.51% | LR: 0.000005
Epoch: 099 | Train loss: 0.9960 | Train acc: 50.52% | Val loss: 0.9928 | Val acc: 54.56% | LR: 0.000005
Epoch: 100 | Train loss: 0.9914 | Train acc: 51.07% | Val loss: 0.9927 | Val acc: 54.60% | LR: 0.000005
Epoch: 101 | Train loss: 0.9923 | Train acc: 50.99% | Val loss: 0.9927 | Val acc: 54.68% | LR: 0.000005
Epoch: 102 | Train loss: 0.9969 | Train acc: 50.71% | Val loss: 0.9927 | Val acc: 54.68% | LR: 0.000005
Epoch: 103 | Train loss: 0.9927 | Train acc: 50.81% | Val loss: 0.9927 | Val acc: 54.62% | LR: 0.000005
Epoch: 104 | Train loss: 0.9893 | Train acc: 51.35% | Val loss: 0.9927 | Val acc: 54.60% | LR: 0.000005
Epoch: 105 | Train loss: 0.9953 | Train acc: 50.63% | Val loss: 0.9927 | Val acc: 54.50% | LR: 0.000004
Epoch: 106 | Train loss: 0.9908 | Train acc: 51.17% | Val loss: 0.9927 | Val acc: 54.50% | LR: 0.000004
Epoch: 107 | Train loss: 0.9943 | Train acc: 50.72% | Val loss: 0.9926 | Val acc: 54.50% | LR: 0.000004
Epoch: 108 | Train loss: 0.9968 | Train acc: 50.46% | Val loss: 0.9926 | Val acc: 54.46% | LR: 0.000004
Epoch: 109 | Train loss: 0.9919 | Train acc: 50.89% | Val loss: 0.9926 | Val acc: 54.38% | LR: 0.000004
Epoch: 110 | Train loss: 0.9970 | Train acc: 50.53% | Val loss: 0.9926 | Val acc: 54.36% | LR: 0.000004
Epoch: 111 | Train loss: 0.9864 | Train acc: 51.60% | Val loss: 0.9931 | Val acc: 54.32% | LR: 0.000004
Epoch: 112 | Train loss: 0.9922 | Train acc: 50.89% | Val loss: 0.9926 | Val acc: 54.34% | LR: 0.000003
Epoch: 113 | Train loss: 0.9927 | Train acc: 50.98% | Val loss: 0.9925 | Val acc: 54.36% | LR: 0.000003
Epoch: 114 | Train loss: 0.9982 | Train acc: 50.18% | Val loss: 0.9925 | Val acc: 54.34% | LR: 0.000003
Epoch: 115 | Train loss: 0.9928 | Train acc: 50.71% | Val loss: 0.9925 | Val acc: 54.40% | LR: 0.000003
Epoch: 116 | Train loss: 0.9947 | Train acc: 50.71% | Val loss: 0.9925 | Val acc: 54.40% | LR: 0.000003
Epoch: 117 | Train loss: 0.9942 | Train acc: 50.63% | Val loss: 0.9925 | Val acc: 54.34% | LR: 0.000003
Epoch: 118 | Train loss: 0.9928 | Train acc: 50.81% | Val loss: 0.9925 | Val acc: 54.36% | LR: 0.000003

[I 2025-09-23 18:09:57,886] Trial 99 finished with value: 0.5431780934333801 and parameters: {'lr': 1.8315124987703963e-05, 'hidden_size': 74, 'dropout': 0.24554996350144814, 'weight_decay': 2.2553321296360976e-05}. Best is trial 97 with value: 0.5451023578643799.

Epoch: 000 | Train loss: 0.9996 | Train acc: 50.44% | Val loss: 1.0020 | Val acc: 52.58% | LR: 0.000027
Epoch: 001 | Train loss: 1.0007 | Train acc: 50.47% | Val loss: 0.9994 | Val acc: 52.68% | LR: 0.000027
Epoch: 002 | Train loss: 0.9982 | Train acc: 51.14% | Val loss: 1.0043 | Val acc: 52.49% | LR: 0.000027
Epoch: 003 | Train loss: 1.0015 | Train acc: 51.09% | Val loss: 0.9981 | Val acc: 52.41% | LR: 0.000027
Epoch: 004 | Train loss: 1.0047 | Train acc: 50.47% | Val loss: 0.9985 | Val acc: 52.52% | LR: 0.000027
Epoch: 005 | Train loss: 0.9995 | Train acc: 50.24% | Val loss: 1.0024 | Val acc: 52.40% | LR: 0.000027
Epoch: 006 | Train loss: 0.9982 | Train acc: 51.91% | Val loss: 1.0092 | Val acc: 52.38% | LR: 0.000027
Epoch: 007 | Train loss: 1.0023 | Train acc: 51.26% | Val loss: 0.9973 | Val acc: 52.36% | LR: 0.000027
Epoch: 008 | Train loss: 0.9979 | Train acc: 50.57% | Val loss: 0.9988 | Val acc: 52.31% | LR: 0.000027
Epoch: 009 | Train loss: 0.9981 | Train acc: 51.22% | Val loss: 1.2692 | Val acc: 52.30% | LR: 0.000027
Epoch: 010 | Train loss: 0.9984 | Train acc: 51.23% | Val loss: 0.9993 | Val acc: 52.59% | LR: 0.000027
Epoch: 011 | Train loss: 1.0050 | Train acc: 50.81% | Val loss: 1.0220 | Val acc: 52.47% | LR: 0.000027
Epoch: 012 | Train loss: 0.9989 | Train acc: 50.46% | Val loss: 1.0066 | Val acc: 52.18% | LR: 0.000027
Epoch: 013 | Train loss: 0.9982 | Train acc: 50.59% | Val loss: 0.9991 | Val acc: 52.54% | LR: 0.000027
Epoch: 014 | Train loss: 0.9973 | Train acc: 50.93% | Val loss: 0.9981 | Val acc: 52.28% | LR: 0.000027
Epoch: 015 | Train loss: 0.9988 | Train acc: 50.22% | Val loss: 1.0338 | Val acc: 52.30% | LR: 0.000027
Epoch: 016 | Train loss: 0.9970 | Train acc: 50.82% | Val loss: 1.0064 | Val acc: 52.23% | LR: 0.000027
Epoch: 017 | Train loss: 0.9977 | Train acc: 50.64% | Val loss: 0.9986 | Val acc: 52.19% | LR: 0.000027
Epoch: 018 | Train loss: 0.9971 | Train acc: 51.18% | Val loss: 1.0018 | Val acc: 52.08% | LR: 0.000026
Epoch: 019 | Train loss: 0.9973 | Train acc: 50.78% | Val loss: 0.9999 | Val acc: 52.20% | LR: 0.000026
Epoch: 020 | Train loss: 1.0000 | Train acc: 50.03% | Val loss: 1.0103 | Val acc: 52.84% | LR: 0.000026
Epoch: 021 | Train loss: 0.9982 | Train acc: 50.75% | Val loss: 0.9991 | Val acc: 52.54% | LR: 0.000026
Epoch: 022 | Train loss: 0.9941 | Train acc: 51.30% | Val loss: 0.9973 | Val acc: 52.61% | LR: 0.000026
Epoch: 023 | Train loss: 0.9964 | Train acc: 50.68% | Val loss: 1.0040 | Val acc: 52.17% | LR: 0.000026
Epoch: 024 | Train loss: 0.9957 | Train acc: 50.68% | Val loss: 1.0008 | Val acc: 52.51% | LR: 0.000026
Epoch: 025 | Train loss: 1.0001 | Train acc: 50.56% | Val loss: 1.0026 | Val acc: 52.53% | LR: 0.000026
Epoch: 026 | Train loss: 0.9973 | Train acc: 50.75% | Val loss: 1.0003 | Val acc: 52.60% | LR: 0.000025
Epoch: 027 | Train loss: 1.0789 | Train acc: 50.67% | Val loss: 0.9990 | Val acc: 52.23% | LR: 0.000025
Epoch: 028 | Train loss: 0.9954 | Train acc: 50.87% | Val loss: 0.9975 | Val acc: 52.62% | LR: 0.000025
Epoch: 029 | Train loss: 0.9954 | Train acc: 50.84% | Val loss: 1.0081 | Val acc: 52.16% | LR: 0.000025
Epoch: 030 | Train loss: 0.9968 | Train acc: 50.44% | Val loss: 0.9995 | Val acc: 52.40% | LR: 0.000025
Epoch: 031 | Train loss: 0.9964 | Train acc: 50.55% | Val loss: 1.0011 | Val acc: 52.13% | LR: 0.000025
Epoch: 032 | Train loss: 0.9953 | Train acc: 51.19% | Val loss: 0.9976 | Val acc: 52.17% | LR: 0.000024
Epoch: 033 | Train loss: 0.9952 | Train acc: 51.07% | Val loss: 0.9974 | Val acc: 52.07% | LR: 0.000024
Epoch: 034 | Train loss: 0.9954 | Train acc: 50.87% | Val loss: 1.0098 | Val acc: 51.84% | LR: 0.000024
Epoch: 035 | Train loss: 1.0001 | Train acc: 50.52% | Val loss: 0.9990 | Val acc: 52.20% | LR: 0.000024
Epoch: 036 | Train loss: 0.9968 | Train acc: 50.37% | Val loss: 0.9983 | Val acc: 52.08% | LR: 0.000024
Epoch: 037 | Train loss: 0.9942 | Train acc: 50.85% | Val loss: 1.0001 | Val acc: 52.03% | LR: 0.000023
Epoch: 038 | Train loss: 0.9964 | Train acc: 50.54% | Val loss: 0.9982 | Val acc: 51.93% | LR: 0.000023
Epoch: 039 | Train loss: 0.9967 | Train acc: 50.99% | Val loss: 1.0178 | Val acc: 52.18% | LR: 0.000023
Epoch: 040 | Train loss: 0.9954 | Train acc: 50.80% | Val loss: 0.9980 | Val acc: 51.93% | LR: 0.000023
Epoch: 041 | Train loss: 0.9965 | Train acc: 50.46% | Val loss: 0.9997 | Val acc: 52.22% | LR: 0.000023
Epoch: 042 | Train loss: 0.9988 | Train acc: 50.21% | Val loss: 0.9980 | Val acc: 52.13% | LR: 0.000022
Epoch: 043 | Train loss: 0.9986 | Train acc: 50.04% | Val loss: 0.9969 | Val acc: 52.03% | LR: 0.000022
Epoch: 044 | Train loss: 0.9979 | Train acc: 50.24% | Val loss: 0.9989 | Val acc: 52.19% | LR: 0.000022
Epoch: 045 | Train loss: 0.9968 | Train acc: 50.60% | Val loss: 0.9975 | Val acc: 52.23% | LR: 0.000022
Epoch: 046 | Train loss: 0.9982 | Train acc: 49.79% | Val loss: 0.9976 | Val acc: 52.05% | LR: 0.000022
Epoch: 047 | Train loss: 1.0000 | Train acc: 49.94% | Val loss: 0.9970 | Val acc: 52.33% | LR: 0.000021
Epoch: 048 | Train loss: 0.9964 | Train acc: 50.33% | Val loss: 0.9974 | Val acc: 52.21% | LR: 0.000021
Epoch: 049 | Train loss: 0.9939 | Train acc: 50.75% | Val loss: 0.9975 | Val acc: 52.19% | LR: 0.000021
Epoch: 050 | Train loss: 0.9961 | Train acc: 50.62% | Val loss: 0.9973 | Val acc: 52.05% | LR: 0.000021
Epoch: 051 | Train loss: 0.9940 | Train acc: 50.65% | Val loss: 0.9975 | Val acc: 52.15% | LR: 0.000020
Epoch: 052 | Train loss: 0.9972 | Train acc: 50.14% | Val loss: 0.9974 | Val acc: 52.24% | LR: 0.000020
Epoch: 053 | Train loss: 0.9925 | Train acc: 50.86% | Val loss: 0.9977 | Val acc: 52.17% | LR: 0.000020
Epoch: 054 | Train loss: 0.9989 | Train acc: 49.96% | Val loss: 0.9975 | Val acc: 52.24% | LR: 0.000020
Epoch: 055 | Train loss: 0.9951 | Train acc: 50.31% | Val loss: 0.9974 | Val acc: 52.24% | LR: 0.000019
Epoch: 056 | Train loss: 0.9921 | Train acc: 50.81% | Val loss: 0.9972 | Val acc: 52.07% | LR: 0.000019
Epoch: 057 | Train loss: 0.9945 | Train acc: 50.54% | Val loss: 0.9978 | Val acc: 52.12% | LR: 0.000019
Epoch: 058 | Train loss: 0.9903 | Train acc: 51.11% | Val loss: 0.9973 | Val acc: 52.12% | LR: 0.000019
Epoch: 059 | Train loss: 0.9941 | Train acc: 50.76% | Val loss: 0.9974 | Val acc: 52.20% | LR: 0.000018
Epoch: 060 | Train loss: 0.9965 | Train acc: 50.20% | Val loss: 0.9974 | Val acc: 52.14% | LR: 0.000018
Epoch: 061 | Train loss: 0.9957 | Train acc: 50.46% | Val loss: 0.9970 | Val acc: 52.06% | LR: 0.000018
Epoch: 062 | Train loss: 0.9936 | Train acc: 50.81% | Val loss: 0.9975 | Val acc: 51.94% | LR: 0.000018
Epoch: 063 | Train loss: 0.9933 | Train acc: 50.52% | Val loss: 0.9975 | Val acc: 52.08% | LR: 0.000017
Epoch: 064 | Train loss: 0.9974 | Train acc: 50.10% | Val loss: 0.9977 | Val acc: 52.06% | LR: 0.000017
Epoch: 065 | Train loss: 0.9932 | Train acc: 50.70% | Val loss: 0.9969 | Val acc: 52.22% | LR: 0.000017
Epoch: 066 | Train loss: 0.9912 | Train acc: 50.96% | Val loss: 0.9989 | Val acc: 52.10% | LR: 0.000016
Epoch: 067 | Train loss: 0.9927 | Train acc: 50.69% | Val loss: 0.9966 | Val acc: 52.14% | LR: 0.000016
Epoch: 068 | Train loss: 0.9943 | Train acc: 50.51% | Val loss: 0.9969 | Val acc: 52.08% | LR: 0.000016
Epoch: 069 | Train loss: 1.0001 | Train acc: 49.93% | Val loss: 0.9971 | Val acc: 52.08% | LR: 0.000016

[I 2025-09-23 18:10:57,742] Trial 100 finished with value: 0.5222030282020569 and parameters: {'lr': 2.7448703646515307e-05, 'hidden_size': 69, 'dropout': 0.2252996814786884, 'weight_decay': 1.985768934786404e-05}. Best is trial 97 with value: 0.5451023578643799.

Epoch: 000 | Train loss: 1.0007 | Train acc: 50.57% | Val loss: 1.0016 | Val acc: 48.63% | LR: 0.000018
Epoch: 001 | Train loss: 1.0001 | Train acc: 50.09% | Val loss: 1.0015 | Val acc: 48.57% | LR: 0.000018
Epoch: 002 | Train loss: 1.0057 | Train acc: 50.35% | Val loss: 1.0024 | Val acc: 48.48% | LR: 0.000018
Epoch: 003 | Train loss: 1.0004 | Train acc: 49.99% | Val loss: 1.0014 | Val acc: 48.41% | LR: 0.000018
Epoch: 004 | Train loss: 0.9989 | Train acc: 50.46% | Val loss: 1.0025 | Val acc: 48.45% | LR: 0.000018
Epoch: 005 | Train loss: 0.9993 | Train acc: 50.55% | Val loss: 1.0017 | Val acc: 48.57% | LR: 0.000018
Epoch: 006 | Train loss: 1.0009 | Train acc: 50.78% | Val loss: 1.0030 | Val acc: 48.37% | LR: 0.000018
Epoch: 007 | Train loss: 0.9994 | Train acc: 50.53% | Val loss: 1.0020 | Val acc: 48.47% | LR: 0.000018
Epoch: 008 | Train loss: 1.0026 | Train acc: 50.51% | Val loss: 1.0016 | Val acc: 48.37% | LR: 0.000018
Epoch: 009 | Train loss: 0.9986 | Train acc: 50.59% | Val loss: 1.0015 | Val acc: 48.49% | LR: 0.000018
Epoch: 010 | Train loss: 0.9962 | Train acc: 51.17% | Val loss: 1.0037 | Val acc: 48.24% | LR: 0.000018
Epoch: 011 | Train loss: 1.0000 | Train acc: 50.34% | Val loss: 1.0025 | Val acc: 48.31% | LR: 0.000018
Epoch: 012 | Train loss: 0.9978 | Train acc: 50.72% | Val loss: 1.0020 | Val acc: 48.16% | LR: 0.000018
Epoch: 013 | Train loss: 0.9972 | Train acc: 50.82% | Val loss: 1.0020 | Val acc: 48.34% | LR: 0.000018
Epoch: 014 | Train loss: 0.9982 | Train acc: 50.31% | Val loss: 1.0052 | Val acc: 48.23% | LR: 0.000018
Epoch: 015 | Train loss: 1.0133 | Train acc: 50.58% | Val loss: 1.0026 | Val acc: 48.29% | LR: 0.000018
Epoch: 016 | Train loss: 1.0022 | Train acc: 50.57% | Val loss: 1.0081 | Val acc: 48.29% | LR: 0.000018
Epoch: 017 | Train loss: 1.0068 | Train acc: 50.83% | Val loss: 1.0019 | Val acc: 48.27% | LR: 0.000018
Epoch: 018 | Train loss: 1.0288 | Train acc: 50.25% | Val loss: 1.0029 | Val acc: 48.34% | LR: 0.000018
Epoch: 019 | Train loss: 1.0007 | Train acc: 50.18% | Val loss: 1.0016 | Val acc: 48.47% | LR: 0.000017
Epoch: 020 | Train loss: 0.9976 | Train acc: 50.72% | Val loss: 1.0050 | Val acc: 48.39% | LR: 0.000017
Epoch: 021 | Train loss: 0.9977 | Train acc: 50.81% | Val loss: 1.0021 | Val acc: 48.45% | LR: 0.000017
Epoch: 022 | Train loss: 0.9990 | Train acc: 50.29% | Val loss: 1.0030 | Val acc: 48.47% | LR: 0.000017
Epoch: 023 | Train loss: 1.0013 | Train acc: 50.04% | Val loss: 1.0044 | Val acc: 48.19% | LR: 0.000017
Epoch: 024 | Train loss: 0.9993 | Train acc: 50.20% | Val loss: 1.0012 | Val acc: 48.38% | LR: 0.000017
Epoch: 025 | Train loss: 0.9993 | Train acc: 50.16% | Val loss: 1.0024 | Val acc: 48.39% | LR: 0.000017
Epoch: 026 | Train loss: 0.9980 | Train acc: 50.61% | Val loss: 1.0013 | Val acc: 48.39% | LR: 0.000017
Epoch: 027 | Train loss: 0.9970 | Train acc: 50.54% | Val loss: 1.0013 | Val acc: 48.25% | LR: 0.000017
Epoch: 028 | Train loss: 0.9968 | Train acc: 50.81% | Val loss: 1.0028 | Val acc: 47.92% | LR: 0.000017
Epoch: 029 | Train loss: 0.9989 | Train acc: 50.47% | Val loss: 1.0024 | Val acc: 47.68% | LR: 0.000017
Epoch: 030 | Train loss: 0.9971 | Train acc: 50.82% | Val loss: 1.0038 | Val acc: 47.78% | LR: 0.000016
Epoch: 031 | Train loss: 0.9984 | Train acc: 50.46% | Val loss: 1.0017 | Val acc: 47.82% | LR: 0.000016
Epoch: 032 | Train loss: 0.9966 | Train acc: 50.73% | Val loss: 1.0022 | Val acc: 47.78% | LR: 0.000016
Epoch: 033 | Train loss: 1.0012 | Train acc: 50.56% | Val loss: 1.0027 | Val acc: 47.86% | LR: 0.000016
Epoch: 034 | Train loss: 0.9989 | Train acc: 50.02% | Val loss: 1.0023 | Val acc: 47.68% | LR: 0.000016
Epoch: 035 | Train loss: 1.0011 | Train acc: 50.01% | Val loss: 1.0146 | Val acc: 47.70% | LR: 0.000016
Epoch: 036 | Train loss: 0.9973 | Train acc: 50.60% | Val loss: 1.0028 | Val acc: 47.69% | LR: 0.000016
Epoch: 037 | Train loss: 0.9960 | Train acc: 50.72% | Val loss: 1.0019 | Val acc: 47.76% | LR: 0.000016
Epoch: 038 | Train loss: 1.0005 | Train acc: 50.18% | Val loss: 1.0020 | Val acc: 47.70% | LR: 0.000015
Epoch: 039 | Train loss: 1.0001 | Train acc: 50.09% | Val loss: 1.0019 | Val acc: 47.86% | LR: 0.000015
Epoch: 040 | Train loss: 0.9970 | Train acc: 50.61% | Val loss: 1.0021 | Val acc: 47.98% | LR: 0.000015
Epoch: 041 | Train loss: 0.9971 | Train acc: 50.53% | Val loss: 1.0020 | Val acc: 47.92% | LR: 0.000015
Epoch: 042 | Train loss: 0.9989 | Train acc: 50.64% | Val loss: 1.0047 | Val acc: 47.76% | LR: 0.000015
Epoch: 043 | Train loss: 1.0009 | Train acc: 50.18% | Val loss: 1.0025 | Val acc: 47.81% | LR: 0.000015
Epoch: 044 | Train loss: 0.9979 | Train acc: 50.45% | Val loss: 1.0028 | Val acc: 47.90% | LR: 0.000015
Epoch: 045 | Train loss: 0.9954 | Train acc: 50.84% | Val loss: 1.0023 | Val acc: 47.81% | LR: 0.000014
Epoch: 046 | Train loss: 1.0007 | Train acc: 50.22% | Val loss: 1.0017 | Val acc: 47.89% | LR: 0.000014
Epoch: 047 | Train loss: 0.9995 | Train acc: 50.23% | Val loss: 1.0031 | Val acc: 47.85% | LR: 0.000014
Epoch: 048 | Train loss: 0.9977 | Train acc: 50.60% | Val loss: 1.0029 | Val acc: 47.90% | LR: 0.000014
Epoch: 049 | Train loss: 0.9956 | Train acc: 50.96% | Val loss: 1.0013 | Val acc: 48.01% | LR: 0.000014

[I 2025-09-23 18:11:40,834] Trial 101 finished with value: 0.47957714796066286 and parameters: {'lr': 1.8172570493315188e-05, 'hidden_size': 73, 'dropout': 0.2625657498792074, 'weight_decay': 2.6351780029548662e-05}. Best is trial 97 with value: 0.5451023578643799.

Epoch: 000 | Train loss: 0.9977 | Train acc: 50.41% | Val loss: 0.9997 | Val acc: 49.91% | LR: 0.000022
Epoch: 001 | Train loss: 0.9955 | Train acc: 50.39% | Val loss: 0.9998 | Val acc: 49.76% | LR: 0.000022
Epoch: 002 | Train loss: 0.9945 | Train acc: 50.80% | Val loss: 0.9997 | Val acc: 49.44% | LR: 0.000022
Epoch: 003 | Train loss: 0.9967 | Train acc: 50.61% | Val loss: 0.9996 | Val acc: 49.61% | LR: 0.000022
Epoch: 004 | Train loss: 0.9940 | Train acc: 50.76% | Val loss: 0.9994 | Val acc: 49.92% | LR: 0.000022
Epoch: 005 | Train loss: 0.9970 | Train acc: 50.86% | Val loss: 0.9994 | Val acc: 49.67% | LR: 0.000022
Epoch: 006 | Train loss: 0.9940 | Train acc: 50.83% | Val loss: 0.9993 | Val acc: 49.78% | LR: 0.000022
Epoch: 007 | Train loss: 0.9960 | Train acc: 50.83% | Val loss: 0.9992 | Val acc: 49.64% | LR: 0.000022
Epoch: 008 | Train loss: 0.9961 | Train acc: 51.06% | Val loss: 0.9989 | Val acc: 50.11% | LR: 0.000022
Epoch: 009 | Train loss: 0.9934 | Train acc: 50.21% | Val loss: 0.9987 | Val acc: 50.35% | LR: 0.000022
Epoch: 010 | Train loss: 0.9949 | Train acc: 51.07% | Val loss: 0.9986 | Val acc: 50.45% | LR: 0.000022
Epoch: 011 | Train loss: 0.9961 | Train acc: 50.53% | Val loss: 0.9984 | Val acc: 50.49% | LR: 0.000022
Epoch: 012 | Train loss: 0.9946 | Train acc: 51.01% | Val loss: 0.9982 | Val acc: 50.78% | LR: 0.000021
Epoch: 013 | Train loss: 0.9956 | Train acc: 50.65% | Val loss: 0.9977 | Val acc: 50.76% | LR: 0.000021
Epoch: 014 | Train loss: 0.9936 | Train acc: 50.92% | Val loss: 0.9976 | Val acc: 50.80% | LR: 0.000021
Epoch: 015 | Train loss: 0.9944 | Train acc: 50.71% | Val loss: 0.9977 | Val acc: 50.86% | LR: 0.000021
Epoch: 016 | Train loss: 0.9930 | Train acc: 50.70% | Val loss: 0.9974 | Val acc: 50.75% | LR: 0.000021
Epoch: 017 | Train loss: 0.9946 | Train acc: 50.80% | Val loss: 0.9972 | Val acc: 50.79% | LR: 0.000021
Epoch: 018 | Train loss: 0.9915 | Train acc: 50.70% | Val loss: 0.9971 | Val acc: 50.89% | LR: 0.000021
Epoch: 019 | Train loss: 0.9911 | Train acc: 51.33% | Val loss: 0.9970 | Val acc: 50.97% | LR: 0.000021
Epoch: 020 | Train loss: 0.9925 | Train acc: 50.71% | Val loss: 0.9969 | Val acc: 51.13% | LR: 0.000021
Epoch: 021 | Train loss: 0.9917 | Train acc: 51.26% | Val loss: 0.9967 | Val acc: 51.25% | LR: 0.000021
Epoch: 022 | Train loss: 0.9909 | Train acc: 50.84% | Val loss: 0.9965 | Val acc: 51.21% | LR: 0.000021
Epoch: 023 | Train loss: 0.9925 | Train acc: 51.08% | Val loss: 0.9963 | Val acc: 51.25% | LR: 0.000021
Epoch: 024 | Train loss: 0.9918 | Train acc: 51.10% | Val loss: 0.9962 | Val acc: 51.26% | LR: 0.000020
Epoch: 025 | Train loss: 0.9919 | Train acc: 50.84% | Val loss: 0.9959 | Val acc: 51.35% | LR: 0.000020
Epoch: 026 | Train loss: 0.9894 | Train acc: 50.99% | Val loss: 0.9954 | Val acc: 51.43% | LR: 0.000020
Epoch: 027 | Train loss: 0.9941 | Train acc: 50.58% | Val loss: 0.9951 | Val acc: 51.49% | LR: 0.000020
Epoch: 028 | Train loss: 0.9923 | Train acc: 51.19% | Val loss: 0.9948 | Val acc: 51.53% | LR: 0.000020
Epoch: 029 | Train loss: 0.9916 | Train acc: 50.87% | Val loss: 0.9945 | Val acc: 51.77% | LR: 0.000020
Epoch: 030 | Train loss: 0.9921 | Train acc: 50.96% | Val loss: 0.9944 | Val acc: 51.75% | LR: 0.000020
Epoch: 031 | Train loss: 0.9952 | Train acc: 50.76% | Val loss: 0.9941 | Val acc: 51.70% | LR: 0.000020
Epoch: 032 | Train loss: 0.9947 | Train acc: 50.95% | Val loss: 0.9936 | Val acc: 51.60% | LR: 0.000019
Epoch: 033 | Train loss: 1.0973 | Train acc: 50.82% | Val loss: 0.9935 | Val acc: 51.59% | LR: 0.000019
Epoch: 034 | Train loss: 0.9927 | Train acc: 51.30% | Val loss: 0.9932 | Val acc: 51.58% | LR: 0.000019
Epoch: 035 | Train loss: 0.9936 | Train acc: 51.40% | Val loss: 0.9931 | Val acc: 51.58% | LR: 0.000019
Epoch: 036 | Train loss: 0.9940 | Train acc: 50.79% | Val loss: 0.9930 | Val acc: 51.58% | LR: 0.000019
Epoch: 037 | Train loss: 0.9921 | Train acc: 51.12% | Val loss: 0.9927 | Val acc: 51.58% | LR: 0.000019
Epoch: 038 | Train loss: 0.9948 | Train acc: 50.68% | Val loss: 0.9924 | Val acc: 51.59% | LR: 0.000019
Epoch: 039 | Train loss: 0.9944 | Train acc: 50.59% | Val loss: 0.9921 | Val acc: 51.64% | LR: 0.000018
Epoch: 040 | Train loss: 0.9911 | Train acc: 51.30% | Val loss: 0.9917 | Val acc: 51.78% | LR: 0.000018
Epoch: 041 | Train loss: 0.9940 | Train acc: 50.76% | Val loss: 0.9909 | Val acc: 51.77% | LR: 0.000018
Epoch: 042 | Train loss: 0.9901 | Train acc: 51.22% | Val loss: 0.9909 | Val acc: 51.76% | LR: 0.000018
Epoch: 043 | Train loss: 0.9917 | Train acc: 50.87% | Val loss: 0.9906 | Val acc: 51.72% | LR: 0.000018
Epoch: 044 | Train loss: 0.9914 | Train acc: 50.88% | Val loss: 0.9905 | Val acc: 51.76% | LR: 0.000018
Epoch: 045 | Train loss: 0.9932 | Train acc: 50.80% | Val loss: 0.9903 | Val acc: 51.74% | LR: 0.000017
Epoch: 046 | Train loss: 0.9922 | Train acc: 50.97% | Val loss: 0.9900 | Val acc: 51.72% | LR: 0.000017
Epoch: 047 | Train loss: 0.9934 | Train acc: 50.87% | Val loss: 0.9899 | Val acc: 51.66% | LR: 0.000017
Epoch: 048 | Train loss: 0.9906 | Train acc: 51.41% | Val loss: 0.9896 | Val acc: 51.74% | LR: 0.000017
Epoch: 049 | Train loss: 0.9907 | Train acc: 50.70% | Val loss: 0.9894 | Val acc: 51.62% | LR: 0.000017
Epoch: 050 | Train loss: 0.9873 | Train acc: 51.22% | Val loss: 0.9893 | Val acc: 51.58% | LR: 0.000016
Epoch: 051 | Train loss: 0.9884 | Train acc: 50.95% | Val loss: 0.9890 | Val acc: 51.58% | LR: 0.000016
Epoch: 052 | Train loss: 0.9893 | Train acc: 51.30% | Val loss: 0.9888 | Val acc: 51.58% | LR: 0.000016
Epoch: 053 | Train loss: 0.9939 | Train acc: 50.23% | Val loss: 0.9885 | Val acc: 51.56% | LR: 0.000016
Epoch: 054 | Train loss: 0.9911 | Train acc: 51.03% | Val loss: 0.9883 | Val acc: 51.54% | LR: 0.000016
Epoch: 055 | Train loss: 0.9871 | Train acc: 51.57% | Val loss: 0.9879 | Val acc: 51.54% | LR: 0.000015
Epoch: 056 | Train loss: 0.9870 | Train acc: 51.25% | Val loss: 0.9876 | Val acc: 51.54% | LR: 0.000015
Epoch: 057 | Train loss: 0.9897 | Train acc: 51.95% | Val loss: 0.9876 | Val acc: 51.54% | LR: 0.000015
Epoch: 058 | Train loss: 0.9868 | Train acc: 51.21% | Val loss: 0.9874 | Val acc: 51.54% | LR: 0.000015
Epoch: 059 | Train loss: 0.9921 | Train acc: 50.95% | Val loss: 0.9872 | Val acc: 51.54% | LR: 0.000015
Epoch: 060 | Train loss: 0.9901 | Train acc: 51.10% | Val loss: 0.9871 | Val acc: 51.56% | LR: 0.000014
Epoch: 061 | Train loss: 0.9901 | Train acc: 51.19% | Val loss: 0.9869 | Val acc: 51.60% | LR: 0.000014
Epoch: 062 | Train loss: 0.9899 | Train acc: 51.28% | Val loss: 0.9868 | Val acc: 51.54% | LR: 0.000014
Epoch: 063 | Train loss: 0.9892 | Train acc: 51.11% | Val loss: 0.9866 | Val acc: 51.58% | LR: 0.000014
Epoch: 064 | Train loss: 0.9919 | Train acc: 51.03% | Val loss: 0.9864 | Val acc: 51.58% | LR: 0.000014
Epoch: 065 | Train loss: 0.9876 | Train acc: 51.56% | Val loss: 0.9863 | Val acc: 51.58% | LR: 0.000013
Epoch: 066 | Train loss: 0.9913 | Train acc: 50.84% | Val loss: 0.9862 | Val acc: 51.58% | LR: 0.000013
Epoch: 067 | Train loss: 0.9862 | Train acc: 51.64% | Val loss: 0.9860 | Val acc: 51.58% | LR: 0.000013
Epoch: 068 | Train loss: 0.9903 | Train acc: 51.28% | Val loss: 0.9859 | Val acc: 51.58% | LR: 0.000013
Epoch: 069 | Train loss: 0.9890 | Train acc: 51.86% | Val loss: 0.9858 | Val acc: 51.58% | LR: 0.000013
Epoch: 070 | Train loss: 0.9874 | Train acc: 51.65% | Val loss: 0.9857 | Val acc: 51.56% | LR: 0.000012
Epoch: 071 | Train loss: 0.9900 | Train acc: 51.47% | Val loss: 0.9856 | Val acc: 51.58% | LR: 0.000012
Epoch: 072 | Train loss: 0.9891 | Train acc: 51.12% | Val loss: 0.9855 | Val acc: 51.54% | LR: 0.000012
Epoch: 073 | Train loss: 0.9879 | Train acc: 51.63% | Val loss: 0.9854 | Val acc: 51.58% | LR: 0.000012
Epoch: 074 | Train loss: 0.9894 | Train acc: 51.47% | Val loss: 0.9854 | Val acc: 51.58% | LR: 0.000011
Epoch: 075 | Train loss: 0.9893 | Train acc: 51.56% | Val loss: 0.9853 | Val acc: 51.52% | LR: 0.000011
Epoch: 076 | Train loss: 0.9867 | Train acc: 51.65% | Val loss: 0.9852 | Val acc: 51.52% | LR: 0.000011
Epoch: 077 | Train loss: 0.9891 | Train acc: 50.94% | Val loss: 0.9851 | Val acc: 51.52% | LR: 0.000011
Epoch: 078 | Train loss: 0.9855 | Train acc: 51.92% | Val loss: 0.9850 | Val acc: 51.52% | LR: 0.000011
Epoch: 079 | Train loss: 0.9867 | Train acc: 51.47% | Val loss: 0.9850 | Val acc: 51.56% | LR: 0.000010
Epoch: 080 | Train loss: 0.9887 | Train acc: 51.11% | Val loss: 0.9850 | Val acc: 51.56% | LR: 0.000010
Epoch: 081 | Train loss: 0.9883 | Train acc: 51.20% | Val loss: 0.9848 | Val acc: 51.54% | LR: 0.000010
Epoch: 082 | Train loss: 0.9901 | Train acc: 50.85% | Val loss: 0.9847 | Val acc: 51.54% | LR: 0.000010
Epoch: 083 | Train loss: 0.9865 | Train acc: 51.73% | Val loss: 0.9845 | Val acc: 51.52% | LR: 0.000009
Epoch: 084 | Train loss: 0.9860 | Train acc: 51.20% | Val loss: 0.9844 | Val acc: 51.52% | LR: 0.000009
Epoch: 085 | Train loss: 0.9889 | Train acc: 51.30% | Val loss: 0.9842 | Val acc: 51.52% | LR: 0.000009
Epoch: 086 | Train loss: 0.9867 | Train acc: 51.20% | Val loss: 0.9842 | Val acc: 51.52% | LR: 0.000009
Epoch: 087 | Train loss: 0.9870 | Train acc: 51.38% | Val loss: 0.9840 | Val acc: 51.52% | LR: 0.000009
Epoch: 088 | Train loss: 0.9882 | Train acc: 51.47% | Val loss: 0.9839 | Val acc: 51.52% | LR: 0.000008
Epoch: 089 | Train loss: 0.9884 | Train acc: 51.20% | Val loss: 0.9838 | Val acc: 51.52% | LR: 0.000008

[I 2025-09-23 18:12:49,828] Trial 102 finished with value: 0.5153896570205688 and parameters: {'lr': 2.182908916964238e-05, 'hidden_size': 77, 'dropout': 0.24578050531317744, 'weight_decay': 3.275295904643856e-05}. Best is trial 97 with value: 0.5451023578643799.

Epoch: 000 | Train loss: 1.0009 | Train acc: 49.42% | Val loss: 0.9944 | Val acc: 54.11% | LR: 0.000019
Epoch: 001 | Train loss: 1.0010 | Train acc: 49.58% | Val loss: 0.9954 | Val acc: 54.07% | LR: 0.000019
Epoch: 002 | Train loss: 1.0005 | Train acc: 50.32% | Val loss: 0.9944 | Val acc: 54.05% | LR: 0.000019
Epoch: 003 | Train loss: 1.0005 | Train acc: 49.76% | Val loss: 0.9946 | Val acc: 54.11% | LR: 0.000019
Epoch: 004 | Train loss: 1.0009 | Train acc: 49.51% | Val loss: 0.9944 | Val acc: 54.17% | LR: 0.000019
Epoch: 005 | Train loss: 1.0007 | Train acc: 49.68% | Val loss: 0.9936 | Val acc: 54.38% | LR: 0.000019
Epoch: 006 | Train loss: 1.0010 | Train acc: 49.32% | Val loss: 0.9944 | Val acc: 54.42% | LR: 0.000019
Epoch: 007 | Train loss: 1.0002 | Train acc: 50.06% | Val loss: 0.9940 | Val acc: 54.44% | LR: 0.000019
Epoch: 008 | Train loss: 1.0005 | Train acc: 49.65% | Val loss: 0.9941 | Val acc: 54.50% | LR: 0.000019
Epoch: 009 | Train loss: 1.0012 | Train acc: 49.32% | Val loss: 0.9948 | Val acc: 54.31% | LR: 0.000019
Epoch: 010 | Train loss: 1.0008 | Train acc: 49.31% | Val loss: 0.9944 | Val acc: 54.31% | LR: 0.000019
Epoch: 011 | Train loss: 0.9995 | Train acc: 49.75% | Val loss: 0.9944 | Val acc: 54.37% | LR: 0.000019
Epoch: 012 | Train loss: 0.9996 | Train acc: 50.40% | Val loss: 0.9944 | Val acc: 54.41% | LR: 0.000019
Epoch: 013 | Train loss: 1.0002 | Train acc: 49.87% | Val loss: 0.9943 | Val acc: 54.47% | LR: 0.000019
Epoch: 014 | Train loss: 0.9999 | Train acc: 49.96% | Val loss: 0.9941 | Val acc: 54.59% | LR: 0.000019
Epoch: 015 | Train loss: 0.9998 | Train acc: 49.88% | Val loss: 0.9941 | Val acc: 54.55% | LR: 0.000019
Epoch: 016 | Train loss: 0.9999 | Train acc: 49.87% | Val loss: 0.9943 | Val acc: 54.53% | LR: 0.000019
Epoch: 017 | Train loss: 0.9992 | Train acc: 50.25% | Val loss: 0.9941 | Val acc: 54.39% | LR: 0.000019
Epoch: 018 | Train loss: 1.0005 | Train acc: 49.47% | Val loss: 0.9941 | Val acc: 54.43% | LR: 0.000018
Epoch: 019 | Train loss: 1.0002 | Train acc: 49.60% | Val loss: 0.9944 | Val acc: 54.51% | LR: 0.000018
Epoch: 020 | Train loss: 0.9998 | Train acc: 49.79% | Val loss: 0.9940 | Val acc: 54.51% | LR: 0.000018
Epoch: 021 | Train loss: 0.9999 | Train acc: 49.77% | Val loss: 0.9939 | Val acc: 54.47% | LR: 0.000018
Epoch: 022 | Train loss: 0.9998 | Train acc: 49.73% | Val loss: 0.9939 | Val acc: 54.57% | LR: 0.000018
Epoch: 023 | Train loss: 0.9993 | Train acc: 50.07% | Val loss: 0.9941 | Val acc: 54.69% | LR: 0.000018
Epoch: 024 | Train loss: 0.9993 | Train acc: 50.21% | Val loss: 0.9941 | Val acc: 54.57% | LR: 0.000018
Epoch: 025 | Train loss: 0.9981 | Train acc: 50.40% | Val loss: 0.9940 | Val acc: 54.51% | LR: 0.000018
Epoch: 026 | Train loss: 0.9980 | Train acc: 50.63% | Val loss: 0.9940 | Val acc: 54.36% | LR: 0.000018
Epoch: 027 | Train loss: 0.9982 | Train acc: 50.98% | Val loss: 0.9941 | Val acc: 54.41% | LR: 0.000018
Epoch: 028 | Train loss: 0.9987 | Train acc: 50.76% | Val loss: 0.9943 | Val acc: 54.39% | LR: 0.000018
Epoch: 029 | Train loss: 0.9991 | Train acc: 50.54% | Val loss: 0.9939 | Val acc: 54.56% | LR: 0.000017
Epoch: 030 | Train loss: 0.9988 | Train acc: 50.71% | Val loss: 0.9940 | Val acc: 54.52% | LR: 0.000017
Epoch: 031 | Train loss: 0.9969 | Train acc: 51.07% | Val loss: 0.9939 | Val acc: 54.54% | LR: 0.000017
Epoch: 032 | Train loss: 0.9985 | Train acc: 50.62% | Val loss: 0.9939 | Val acc: 54.44% | LR: 0.000017
Epoch: 033 | Train loss: 0.9992 | Train acc: 50.41% | Val loss: 0.9941 | Val acc: 54.26% | LR: 0.000017
Epoch: 034 | Train loss: 0.9981 | Train acc: 50.69% | Val loss: 0.9940 | Val acc: 54.18% | LR: 0.000017
Epoch: 035 | Train loss: 0.9976 | Train acc: 50.85% | Val loss: 0.9940 | Val acc: 54.28% | LR: 0.000017
Epoch: 036 | Train loss: 1.0004 | Train acc: 49.98% | Val loss: 0.9940 | Val acc: 54.20% | LR: 0.000017
Epoch: 037 | Train loss: 1.0000 | Train acc: 49.98% | Val loss: 0.9940 | Val acc: 54.13% | LR: 0.000016
Epoch: 038 | Train loss: 0.9980 | Train acc: 50.64% | Val loss: 0.9940 | Val acc: 54.11% | LR: 0.000016
Epoch: 039 | Train loss: 0.9968 | Train acc: 50.81% | Val loss: 0.9941 | Val acc: 54.13% | LR: 0.000016
Epoch: 040 | Train loss: 0.9982 | Train acc: 50.54% | Val loss: 0.9940 | Val acc: 54.22% | LR: 0.000016
Epoch: 041 | Train loss: 0.9995 | Train acc: 50.19% | Val loss: 0.9941 | Val acc: 54.26% | LR: 0.000016
Epoch: 042 | Train loss: 0.9983 | Train acc: 50.48% | Val loss: 0.9943 | Val acc: 54.18% | LR: 0.000016
Epoch: 043 | Train loss: 1.0002 | Train acc: 50.19% | Val loss: 0.9940 | Val acc: 54.26% | LR: 0.000016
Epoch: 044 | Train loss: 0.9991 | Train acc: 50.18% | Val loss: 0.9938 | Val acc: 54.24% | LR: 0.000015
Epoch: 045 | Train loss: 0.9993 | Train acc: 50.17% | Val loss: 0.9938 | Val acc: 54.24% | LR: 0.000015
Epoch: 046 | Train loss: 0.9982 | Train acc: 50.46% | Val loss: 0.9940 | Val acc: 54.18% | LR: 0.000015
Epoch: 047 | Train loss: 0.9987 | Train acc: 50.28% | Val loss: 0.9939 | Val acc: 54.16% | LR: 0.000015
Epoch: 048 | Train loss: 1.0009 | Train acc: 50.02% | Val loss: 0.9940 | Val acc: 53.96% | LR: 0.000015
Epoch: 049 | Train loss: 0.9983 | Train acc: 50.37% | Val loss: 0.9938 | Val acc: 54.00% | LR: 0.000015
Epoch: 050 | Train loss: 0.9968 | Train acc: 50.72% | Val loss: 0.9938 | Val acc: 54.06% | LR: 0.000014
Epoch: 051 | Train loss: 0.9956 | Train acc: 51.10% | Val loss: 0.9938 | Val acc: 54.06% | LR: 0.000014
Epoch: 052 | Train loss: 0.9974 | Train acc: 50.67% | Val loss: 0.9940 | Val acc: 54.06% | LR: 0.000014
Epoch: 053 | Train loss: 0.9968 | Train acc: 50.78% | Val loss: 0.9937 | Val acc: 53.98% | LR: 0.000014
Epoch: 054 | Train loss: 0.9971 | Train acc: 50.77% | Val loss: 0.9937 | Val acc: 54.12% | LR: 0.000014
Epoch: 055 | Train loss: 0.9988 | Train acc: 50.42% | Val loss: 0.9937 | Val acc: 54.12% | LR: 0.000014
Epoch: 056 | Train loss: 0.9980 | Train acc: 50.50% | Val loss: 0.9938 | Val acc: 54.22% | LR: 0.000013
Epoch: 057 | Train loss: 0.9985 | Train acc: 50.42% | Val loss: 0.9936 | Val acc: 54.48% | LR: 0.000013
Epoch: 058 | Train loss: 0.9972 | Train acc: 50.53% | Val loss: 0.9938 | Val acc: 54.62% | LR: 0.000013
Epoch: 059 | Train loss: 0.9942 | Train acc: 51.17% | Val loss: 0.9938 | Val acc: 54.60% | LR: 0.000013
Epoch: 060 | Train loss: 0.9959 | Train acc: 50.83% | Val loss: 0.9938 | Val acc: 54.60% | LR: 0.000013
Epoch: 061 | Train loss: 0.9974 | Train acc: 50.65% | Val loss: 0.9936 | Val acc: 54.54% | LR: 0.000013
Epoch: 062 | Train loss: 0.9970 | Train acc: 50.45% | Val loss: 0.9937 | Val acc: 54.58% | LR: 0.000012
Epoch: 063 | Train loss: 0.9964 | Train acc: 50.65% | Val loss: 0.9945 | Val acc: 54.40% | LR: 0.000012
Epoch: 064 | Train loss: 0.9941 | Train acc: 50.99% | Val loss: 0.9936 | Val acc: 54.44% | LR: 0.000012
Epoch: 065 | Train loss: 0.9952 | Train acc: 50.83% | Val loss: 0.9937 | Val acc: 54.42% | LR: 0.000012
Epoch: 066 | Train loss: 0.9957 | Train acc: 50.83% | Val loss: 0.9937 | Val acc: 54.42% | LR: 0.000012
Epoch: 067 | Train loss: 0.9975 | Train acc: 50.55% | Val loss: 0.9937 | Val acc: 54.52% | LR: 0.000011
Epoch: 068 | Train loss: 0.9958 | Train acc: 50.67% | Val loss: 0.9937 | Val acc: 54.51% | LR: 0.000011
Epoch: 069 | Train loss: 0.9940 | Train acc: 51.10% | Val loss: 0.9937 | Val acc: 54.65% | LR: 0.000011
Epoch: 070 | Train loss: 0.9926 | Train acc: 51.01% | Val loss: 0.9938 | Val acc: 54.63% | LR: 0.000011
Epoch: 071 | Train loss: 0.9940 | Train acc: 50.84% | Val loss: 0.9936 | Val acc: 54.67% | LR: 0.000011
Epoch: 072 | Train loss: 0.9953 | Train acc: 50.67% | Val loss: 0.9935 | Val acc: 54.73% | LR: 0.000010
Epoch: 073 | Train loss: 0.9910 | Train acc: 51.65% | Val loss: 0.9933 | Val acc: 54.71% | LR: 0.000010
Epoch: 074 | Train loss: 0.9946 | Train acc: 50.86% | Val loss: 0.9933 | Val acc: 54.67% | LR: 0.000010
Epoch: 075 | Train loss: 0.9960 | Train acc: 50.58% | Val loss: 0.9932 | Val acc: 54.71% | LR: 0.000010
Epoch: 076 | Train loss: 0.9928 | Train acc: 50.94% | Val loss: 0.9948 | Val acc: 54.67% | LR: 0.000010
Epoch: 077 | Train loss: 0.9937 | Train acc: 51.11% | Val loss: 0.9935 | Val acc: 54.71% | LR: 0.000010
Epoch: 078 | Train loss: 0.9920 | Train acc: 50.86% | Val loss: 0.9934 | Val acc: 54.67% | LR: 0.000009
Epoch: 079 | Train loss: 0.9951 | Train acc: 50.59% | Val loss: 0.9938 | Val acc: 54.79% | LR: 0.000009
Epoch: 080 | Train loss: 0.9928 | Train acc: 50.93% | Val loss: 0.9937 | Val acc: 54.79% | LR: 0.000009
Epoch: 081 | Train loss: 0.9944 | Train acc: 50.83% | Val loss: 0.9936 | Val acc: 54.87% | LR: 0.000009
Epoch: 082 | Train loss: 0.9962 | Train acc: 50.47% | Val loss: 0.9936 | Val acc: 54.92% | LR: 0.000009
Epoch: 083 | Train loss: 0.9953 | Train acc: 50.64% | Val loss: 0.9936 | Val acc: 54.98% | LR: 0.000008
Epoch: 084 | Train loss: 0.9932 | Train acc: 50.73% | Val loss: 0.9936 | Val acc: 54.89% | LR: 0.000008
Epoch: 085 | Train loss: 0.9931 | Train acc: 50.91% | Val loss: 0.9936 | Val acc: 54.87% | LR: 0.000008
Epoch: 086 | Train loss: 0.9923 | Train acc: 51.00% | Val loss: 0.9936 | Val acc: 54.87% | LR: 0.000008
Epoch: 087 | Train loss: 0.9934 | Train acc: 50.73% | Val loss: 0.9935 | Val acc: 54.87% | LR: 0.000008
Epoch: 088 | Train loss: 0.9927 | Train acc: 50.91% | Val loss: 0.9935 | Val acc: 54.92% | LR: 0.000007
Epoch: 089 | Train loss: 0.9961 | Train acc: 50.46% | Val loss: 0.9935 | Val acc: 54.92% | LR: 0.000007
Epoch: 090 | Train loss: 0.9950 | Train acc: 50.55% | Val loss: 0.9935 | Val acc: 54.89% | LR: 0.000007
Epoch: 091 | Train loss: 0.9933 | Train acc: 51.00% | Val loss: 0.9935 | Val acc: 54.83% | LR: 0.000007
Epoch: 092 | Train loss: 0.9939 | Train acc: 50.82% | Val loss: 0.9935 | Val acc: 54.79% | LR: 0.000007
Epoch: 093 | Train loss: 0.9932 | Train acc: 50.91% | Val loss: 0.9935 | Val acc: 54.75% | LR: 0.000007
Epoch: 094 | Train loss: 0.9973 | Train acc: 50.38% | Val loss: 0.9935 | Val acc: 54.75% | LR: 0.000006
Epoch: 095 | Train loss: 0.9935 | Train acc: 50.92% | Val loss: 0.9934 | Val acc: 54.73% | LR: 0.000006
Epoch: 096 | Train loss: 0.9950 | Train acc: 50.75% | Val loss: 0.9934 | Val acc: 54.73% | LR: 0.000006
Epoch: 097 | Train loss: 0.9942 | Train acc: 50.75% | Val loss: 0.9934 | Val acc: 54.71% | LR: 0.000006
Epoch: 098 | Train loss: 0.9914 | Train acc: 51.01% | Val loss: 0.9934 | Val acc: 54.65% | LR: 0.000006
Epoch: 099 | Train loss: 0.9951 | Train acc: 50.48% | Val loss: 0.9934 | Val acc: 54.65% | LR: 0.000006
Epoch: 100 | Train loss: 0.9912 | Train acc: 51.00% | Val loss: 0.9934 | Val acc: 54.71% | LR: 0.000005
Epoch: 101 | Train loss: 0.9927 | Train acc: 50.91% | Val loss: 0.9934 | Val acc: 54.75% | LR: 0.000005
Epoch: 102 | Train loss: 0.9966 | Train acc: 50.65% | Val loss: 0.9934 | Val acc: 54.71% | LR: 0.000005
Epoch: 103 | Train loss: 0.9924 | Train acc: 50.74% | Val loss: 0.9934 | Val acc: 54.71% | LR: 0.000005
Epoch: 104 | Train loss: 0.9897 | Train acc: 51.18% | Val loss: 0.9934 | Val acc: 54.73% | LR: 0.000005
Epoch: 105 | Train loss: 0.9952 | Train acc: 50.56% | Val loss: 0.9934 | Val acc: 54.75% | LR: 0.000005
Epoch: 106 | Train loss: 0.9914 | Train acc: 51.09% | Val loss: 0.9934 | Val acc: 54.75% | LR: 0.000004
Epoch: 107 | Train loss: 0.9945 | Train acc: 50.65% | Val loss: 0.9934 | Val acc: 54.75% | LR: 0.000004
Epoch: 108 | Train loss: 0.9964 | Train acc: 50.38% | Val loss: 0.9934 | Val acc: 54.73% | LR: 0.000004
Epoch: 109 | Train loss: 0.9918 | Train acc: 50.83% | Val loss: 0.9935 | Val acc: 54.73% | LR: 0.000004
Epoch: 110 | Train loss: 0.9963 | Train acc: 50.47% | Val loss: 0.9935 | Val acc: 54.73% | LR: 0.000004
Epoch: 111 | Train loss: 0.9873 | Train acc: 51.53% | Val loss: 0.9935 | Val acc: 54.75% | LR: 0.000004
Epoch: 112 | Train loss: 0.9924 | Train acc: 50.74% | Val loss: 0.9935 | Val acc: 54.73% | LR: 0.000004
Epoch: 113 | Train loss: 0.9932 | Train acc: 50.92% | Val loss: 0.9939 | Val acc: 54.69% | LR: 0.000003
Epoch: 114 | Train loss: 0.9972 | Train acc: 50.12% | Val loss: 1.0516 | Val acc: 54.69% | LR: 0.000003
Epoch: 115 | Train loss: 0.9927 | Train acc: 50.65% | Val loss: 0.9948 | Val acc: 54.69% | LR: 0.000003
Epoch: 116 | Train loss: 0.9948 | Train acc: 50.65% | Val loss: 0.9931 | Val acc: 54.71% | LR: 0.000003
Epoch: 117 | Train loss: 0.9938 | Train acc: 50.66% | Val loss: 0.9931 | Val acc: 54.67% | LR: 0.000003
Epoch: 118 | Train loss: 0.9931 | Train acc: 50.74% | Val loss: 0.9931 | Val acc: 54.67% | LR: 0.000003
Epoch: 119 | Train loss: 0.9911 | Train acc: 50.83% | Val loss: 0.9931 | Val acc: 54.67% | LR: 0.000003
Epoch: 120 | Train loss: 0.9931 | Train acc: 50.83% | Val loss: 0.9931 | Val acc: 54.65% | LR: 0.000003
Epoch: 121 | Train loss: 0.9922 | Train acc: 50.92% | Val loss: 0.9932 | Val acc: 54.65% | LR: 0.000003
Epoch: 122 | Train loss: 0.9961 | Train acc: 50.75% | Val loss: 0.9931 | Val acc: 54.65% | LR: 0.000002
Epoch: 123 | Train loss: 0.9931 | Train acc: 50.83% | Val loss: 0.9931 | Val acc: 54.59% | LR: 0.000002
Epoch: 124 | Train loss: 0.9909 | Train acc: 51.10% | Val loss: 0.9931 | Val acc: 54.65% | LR: 0.000002
Epoch: 125 | Train loss: 0.9925 | Train acc: 51.01% | Val loss: 0.9931 | Val acc: 54.65% | LR: 0.000002
Epoch: 126 | Train loss: 0.9962 | Train acc: 50.39% | Val loss: 0.9931 | Val acc: 54.59% | LR: 0.000002
Epoch: 127 | Train loss: 0.9946 | Train acc: 50.75% | Val loss: 0.9931 | Val acc: 54.61% | LR: 0.000002
Epoch: 128 | Train loss: 0.9909 | Train acc: 51.10% | Val loss: 0.9931 | Val acc: 54.61% | LR: 0.000002
Epoch: 129 | Train loss: 0.9919 | Train acc: 51.01% | Val loss: 0.9931 | Val acc: 54.63% | LR: 0.000002
Epoch: 130 | Train loss: 0.9954 | Train acc: 50.39% | Val loss: 0.9930 | Val acc: 54.63% | LR: 0.000002
Epoch: 131 | Train loss: 0.9943 | Train acc: 50.83% | Val loss: 0.9930 | Val acc: 54.63% | LR: 0.000002
Epoch: 132 | Train loss: 0.9915 | Train acc: 50.83% | Val loss: 0.9930 | Val acc: 54.63% | LR: 0.000002

[I 2025-09-23 18:14:39,161] Trial 103 finished with value: 0.5463126420974731 and parameters: {'lr': 1.9203929440987328e-05, 'hidden_size': 74, 'dropout': 0.23183749861270414, 'weight_decay': 2.0257538722739168e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 0.9990 | Train acc: 50.43% | Val loss: 1.0578 | Val acc: 52.27% | LR: 0.000020
Epoch: 001 | Train loss: 1.0001 | Train acc: 50.62% | Val loss: 1.0725 | Val acc: 52.94% | LR: 0.000020
Epoch: 002 | Train loss: 0.9991 | Train acc: 51.01% | Val loss: 1.0287 | Val acc: 52.52% | LR: 0.000020
Epoch: 003 | Train loss: 0.9977 | Train acc: 51.22% | Val loss: 1.0361 | Val acc: 52.21% | LR: 0.000020
Epoch: 004 | Train loss: 1.0115 | Train acc: 50.71% | Val loss: 1.0071 | Val acc: 52.21% | LR: 0.000020
Epoch: 005 | Train loss: 0.9994 | Train acc: 50.02% | Val loss: 0.9993 | Val acc: 52.48% | LR: 0.000020
Epoch: 006 | Train loss: 0.9988 | Train acc: 51.85% | Val loss: 1.0039 | Val acc: 52.26% | LR: 0.000020
Epoch: 007 | Train loss: 0.9987 | Train acc: 50.90% | Val loss: 1.0023 | Val acc: 52.47% | LR: 0.000019
Epoch: 008 | Train loss: 0.9994 | Train acc: 51.32% | Val loss: 1.0062 | Val acc: 52.90% | LR: 0.000019
Epoch: 009 | Train loss: 0.9991 | Train acc: 50.79% | Val loss: 1.0027 | Val acc: 52.70% | LR: 0.000019
Epoch: 010 | Train loss: 1.0006 | Train acc: 50.25% | Val loss: 0.9999 | Val acc: 52.86% | LR: 0.000019
Epoch: 011 | Train loss: 0.9975 | Train acc: 51.38% | Val loss: 1.0113 | Val acc: 53.33% | LR: 0.000019
Epoch: 012 | Train loss: 0.9983 | Train acc: 50.46% | Val loss: 0.9965 | Val acc: 53.21% | LR: 0.000019
Epoch: 013 | Train loss: 1.1447 | Train acc: 51.69% | Val loss: 1.0063 | Val acc: 52.93% | LR: 0.000019
Epoch: 014 | Train loss: 0.9977 | Train acc: 51.54% | Val loss: 1.0034 | Val acc: 52.99% | LR: 0.000019
Epoch: 015 | Train loss: 0.9989 | Train acc: 50.21% | Val loss: 0.9948 | Val acc: 53.29% | LR: 0.000019
Epoch: 016 | Train loss: 1.0040 | Train acc: 50.85% | Val loss: 1.0044 | Val acc: 53.17% | LR: 0.000019
Epoch: 017 | Train loss: 0.9978 | Train acc: 50.67% | Val loss: 1.0056 | Val acc: 53.19% | LR: 0.000019
Epoch: 018 | Train loss: 0.9991 | Train acc: 51.30% | Val loss: 1.0052 | Val acc: 53.10% | LR: 0.000019
Epoch: 019 | Train loss: 1.0026 | Train acc: 50.87% | Val loss: 1.0065 | Val acc: 52.78% | LR: 0.000019
Epoch: 020 | Train loss: 1.0344 | Train acc: 50.12% | Val loss: 1.0195 | Val acc: 52.79% | LR: 0.000019
Epoch: 021 | Train loss: 0.9974 | Train acc: 50.63% | Val loss: 1.0214 | Val acc: 53.24% | LR: 0.000019
Epoch: 022 | Train loss: 0.9982 | Train acc: 51.19% | Val loss: 1.0415 | Val acc: 52.95% | LR: 0.000019
Epoch: 023 | Train loss: 0.9982 | Train acc: 50.78% | Val loss: 1.0274 | Val acc: 52.45% | LR: 0.000018
Epoch: 024 | Train loss: 1.0002 | Train acc: 50.76% | Val loss: 1.0041 | Val acc: 52.47% | LR: 0.000018
Epoch: 025 | Train loss: 0.9987 | Train acc: 50.52% | Val loss: 1.0007 | Val acc: 52.47% | LR: 0.000018
Epoch: 026 | Train loss: 0.9975 | Train acc: 50.79% | Val loss: 1.0026 | Val acc: 52.88% | LR: 0.000018
Epoch: 027 | Train loss: 0.9965 | Train acc: 50.77% | Val loss: 1.0056 | Val acc: 53.22% | LR: 0.000018
Epoch: 028 | Train loss: 0.9972 | Train acc: 50.95% | Val loss: 1.0017 | Val acc: 53.00% | LR: 0.000018
Epoch: 029 | Train loss: 0.9982 | Train acc: 50.85% | Val loss: 0.9999 | Val acc: 53.02% | LR: 0.000018
Epoch: 030 | Train loss: 0.9995 | Train acc: 50.42% | Val loss: 1.0205 | Val acc: 53.03% | LR: 0.000018
Epoch: 031 | Train loss: 0.9978 | Train acc: 50.67% | Val loss: 1.0071 | Val acc: 52.81% | LR: 0.000018
Epoch: 032 | Train loss: 0.9966 | Train acc: 51.20% | Val loss: 1.0103 | Val acc: 52.88% | LR: 0.000017
Epoch: 033 | Train loss: 0.9967 | Train acc: 51.03% | Val loss: 0.9970 | Val acc: 52.90% | LR: 0.000017
Epoch: 034 | Train loss: 0.9983 | Train acc: 50.92% | Val loss: 1.0053 | Val acc: 52.88% | LR: 0.000017
Epoch: 035 | Train loss: 0.9975 | Train acc: 50.62% | Val loss: 1.0312 | Val acc: 52.86% | LR: 0.000017
Epoch: 036 | Train loss: 0.9975 | Train acc: 50.36% | Val loss: 1.0238 | Val acc: 52.67% | LR: 0.000017
Epoch: 037 | Train loss: 0.9960 | Train acc: 51.01% | Val loss: 1.0175 | Val acc: 52.31% | LR: 0.000017
Epoch: 038 | Train loss: 1.0038 | Train acc: 50.54% | Val loss: 0.9964 | Val acc: 52.76% | LR: 0.000017
Epoch: 039 | Train loss: 0.9957 | Train acc: 50.93% | Val loss: 0.9999 | Val acc: 52.80% | LR: 0.000017
Epoch: 040 | Train loss: 0.9968 | Train acc: 50.76% | Val loss: 0.9998 | Val acc: 52.72% | LR: 0.000016
Epoch: 041 | Train loss: 0.9980 | Train acc: 50.39% | Val loss: 1.0043 | Val acc: 52.71% | LR: 0.000016
Epoch: 042 | Train loss: 0.9988 | Train acc: 50.32% | Val loss: 0.9967 | Val acc: 52.70% | LR: 0.000016
Epoch: 043 | Train loss: 1.0034 | Train acc: 49.99% | Val loss: 0.9980 | Val acc: 52.55% | LR: 0.000016
Epoch: 044 | Train loss: 0.9981 | Train acc: 50.30% | Val loss: 1.0102 | Val acc: 52.48% | LR: 0.000016
Epoch: 045 | Train loss: 0.9980 | Train acc: 50.63% | Val loss: 1.0104 | Val acc: 52.58% | LR: 0.000016
Epoch: 046 | Train loss: 0.9985 | Train acc: 49.93% | Val loss: 1.0085 | Val acc: 52.38% | LR: 0.000015
Epoch: 047 | Train loss: 0.9994 | Train acc: 49.98% | Val loss: 0.9976 | Val acc: 52.56% | LR: 0.000015
Epoch: 048 | Train loss: 0.9997 | Train acc: 50.34% | Val loss: 1.0394 | Val acc: 52.18% | LR: 0.000015
Epoch: 049 | Train loss: 0.9956 | Train acc: 50.80% | Val loss: 0.9988 | Val acc: 52.36% | LR: 0.000015
Epoch: 050 | Train loss: 0.9971 | Train acc: 50.68% | Val loss: 1.0016 | Val acc: 52.48% | LR: 0.000015
Epoch: 051 | Train loss: 0.9963 | Train acc: 50.59% | Val loss: 0.9970 | Val acc: 52.30% | LR: 0.000015
Epoch: 052 | Train loss: 0.9975 | Train acc: 50.40% | Val loss: 0.9980 | Val acc: 52.22% | LR: 0.000014
Epoch: 053 | Train loss: 0.9948 | Train acc: 50.94% | Val loss: 0.9995 | Val acc: 52.10% | LR: 0.000014
Epoch: 054 | Train loss: 0.9990 | Train acc: 50.00% | Val loss: 1.0004 | Val acc: 51.92% | LR: 0.000014
Epoch: 055 | Train loss: 0.9978 | Train acc: 50.40% | Val loss: 0.9969 | Val acc: 52.02% | LR: 0.000014
Epoch: 056 | Train loss: 0.9943 | Train acc: 50.89% | Val loss: 1.0016 | Val acc: 51.96% | LR: 0.000014
Epoch: 057 | Train loss: 0.9997 | Train acc: 50.43% | Val loss: 1.0042 | Val acc: 51.87% | LR: 0.000014
Epoch: 058 | Train loss: 1.0123 | Train acc: 51.10% | Val loss: 0.9997 | Val acc: 52.08% | LR: 0.000013
Epoch: 059 | Train loss: 0.9945 | Train acc: 50.78% | Val loss: 1.0025 | Val acc: 52.10% | LR: 0.000013
Epoch: 060 | Train loss: 0.9975 | Train acc: 50.12% | Val loss: 0.9972 | Val acc: 52.11% | LR: 0.000013

[I 2025-09-23 18:15:26,947] Trial 104 finished with value: 0.5192605376243591 and parameters: {'lr': 1.9625993650120615e-05, 'hidden_size': 69, 'dropout': 0.23204949446989184, 'weight_decay': 2.3182308272474546e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0023 | Train acc: 49.96% | Val loss: 0.9939 | Val acc: 53.92% | LR: 0.000025
Epoch: 001 | Train loss: 0.9998 | Train acc: 50.15% | Val loss: 0.9935 | Val acc: 53.89% | LR: 0.000025
Epoch: 002 | Train loss: 0.9997 | Train acc: 50.06% | Val loss: 0.9979 | Val acc: 54.05% | LR: 0.000025
Epoch: 003 | Train loss: 0.9984 | Train acc: 50.37% | Val loss: 0.9967 | Val acc: 53.83% | LR: 0.000025
Epoch: 004 | Train loss: 1.0007 | Train acc: 50.01% | Val loss: 0.9951 | Val acc: 53.80% | LR: 0.000025
Epoch: 005 | Train loss: 0.9993 | Train acc: 50.05% | Val loss: 0.9925 | Val acc: 53.84% | LR: 0.000025
Epoch: 006 | Train loss: 1.0004 | Train acc: 49.84% | Val loss: 0.9970 | Val acc: 53.92% | LR: 0.000025
Epoch: 007 | Train loss: 0.9966 | Train acc: 50.93% | Val loss: 0.9944 | Val acc: 53.88% | LR: 0.000025
Epoch: 008 | Train loss: 0.9996 | Train acc: 50.05% | Val loss: 0.9914 | Val acc: 53.95% | LR: 0.000025
Epoch: 009 | Train loss: 0.9984 | Train acc: 50.66% | Val loss: 0.9918 | Val acc: 53.99% | LR: 0.000025
Epoch: 010 | Train loss: 1.0008 | Train acc: 50.03% | Val loss: 0.9959 | Val acc: 53.93% | LR: 0.000025
Epoch: 011 | Train loss: 0.9987 | Train acc: 50.47% | Val loss: 0.9941 | Val acc: 53.76% | LR: 0.000025
Epoch: 012 | Train loss: 0.9999 | Train acc: 50.18% | Val loss: 0.9923 | Val acc: 53.89% | LR: 0.000025
Epoch: 013 | Train loss: 0.9974 | Train acc: 50.68% | Val loss: 0.9930 | Val acc: 53.88% | LR: 0.000025
Epoch: 014 | Train loss: 0.9979 | Train acc: 50.65% | Val loss: 0.9929 | Val acc: 53.91% | LR: 0.000024
Epoch: 015 | Train loss: 0.9988 | Train acc: 50.37% | Val loss: 0.9977 | Val acc: 53.80% | LR: 0.000024
Epoch: 016 | Train loss: 0.9994 | Train acc: 50.22% | Val loss: 0.9932 | Val acc: 53.89% | LR: 0.000024
Epoch: 017 | Train loss: 0.9987 | Train acc: 50.39% | Val loss: 0.9925 | Val acc: 53.96% | LR: 0.000024
Epoch: 018 | Train loss: 0.9979 | Train acc: 50.51% | Val loss: 1.0032 | Val acc: 53.72% | LR: 0.000024
Epoch: 019 | Train loss: 0.9997 | Train acc: 50.18% | Val loss: 1.0041 | Val acc: 53.76% | LR: 0.000024
Epoch: 020 | Train loss: 0.9981 | Train acc: 50.53% | Val loss: 0.9920 | Val acc: 53.96% | LR: 0.000024
Epoch: 021 | Train loss: 0.9967 | Train acc: 50.69% | Val loss: 0.9926 | Val acc: 53.99% | LR: 0.000024
Epoch: 022 | Train loss: 0.9990 | Train acc: 50.25% | Val loss: 0.9931 | Val acc: 53.74% | LR: 0.000024
Epoch: 023 | Train loss: 0.9976 | Train acc: 50.24% | Val loss: 0.9953 | Val acc: 53.90% | LR: 0.000024
Epoch: 024 | Train loss: 0.9982 | Train acc: 50.37% | Val loss: 0.9944 | Val acc: 53.92% | LR: 0.000023
Epoch: 025 | Train loss: 0.9989 | Train acc: 50.35% | Val loss: 0.9954 | Val acc: 53.80% | LR: 0.000023
Epoch: 026 | Train loss: 0.9979 | Train acc: 50.44% | Val loss: 0.9936 | Val acc: 53.90% | LR: 0.000023
Epoch: 027 | Train loss: 0.9968 | Train acc: 50.52% | Val loss: 0.9923 | Val acc: 53.96% | LR: 0.000023
Epoch: 028 | Train loss: 1.0026 | Train acc: 49.80% | Val loss: 0.9927 | Val acc: 53.93% | LR: 0.000023
Epoch: 029 | Train loss: 0.9989 | Train acc: 50.09% | Val loss: 0.9934 | Val acc: 53.99% | LR: 0.000023
Epoch: 030 | Train loss: 0.9983 | Train acc: 50.36% | Val loss: 0.9933 | Val acc: 53.80% | LR: 0.000023
Epoch: 031 | Train loss: 0.9964 | Train acc: 50.42% | Val loss: 0.9926 | Val acc: 54.07% | LR: 0.000022
Epoch: 032 | Train loss: 0.9953 | Train acc: 50.70% | Val loss: 0.9927 | Val acc: 53.97% | LR: 0.000022
Epoch: 033 | Train loss: 0.9968 | Train acc: 50.33% | Val loss: 0.9922 | Val acc: 54.05% | LR: 0.000022
Epoch: 034 | Train loss: 0.9950 | Train acc: 50.91% | Val loss: 0.9922 | Val acc: 54.05% | LR: 0.000022
Epoch: 035 | Train loss: 0.9878 | Train acc: 51.44% | Val loss: 0.9971 | Val acc: 54.03% | LR: 0.000022
Epoch: 036 | Train loss: 0.9928 | Train acc: 50.80% | Val loss: 0.9929 | Val acc: 53.91% | LR: 0.000022
Epoch: 037 | Train loss: 0.9939 | Train acc: 50.87% | Val loss: 0.9930 | Val acc: 53.93% | LR: 0.000021
Epoch: 038 | Train loss: 0.9975 | Train acc: 50.34% | Val loss: 0.9924 | Val acc: 54.00% | LR: 0.000021
Epoch: 039 | Train loss: 0.9914 | Train acc: 51.07% | Val loss: 0.9922 | Val acc: 54.05% | LR: 0.000021
Epoch: 040 | Train loss: 0.9989 | Train acc: 50.09% | Val loss: 0.9924 | Val acc: 53.95% | LR: 0.000021
Epoch: 041 | Train loss: 0.9983 | Train acc: 50.37% | Val loss: 0.9929 | Val acc: 53.82% | LR: 0.000021
Epoch: 042 | Train loss: 0.9999 | Train acc: 50.18% | Val loss: 0.9928 | Val acc: 53.97% | LR: 0.000020
Epoch: 043 | Train loss: 0.9963 | Train acc: 50.45% | Val loss: 0.9918 | Val acc: 54.19% | LR: 0.000020
Epoch: 044 | Train loss: 0.9973 | Train acc: 50.45% | Val loss: 0.9925 | Val acc: 54.03% | LR: 0.000020
Epoch: 045 | Train loss: 0.9941 | Train acc: 50.63% | Val loss: 0.9926 | Val acc: 54.15% | LR: 0.000020
Epoch: 046 | Train loss: 0.9938 | Train acc: 50.64% | Val loss: 0.9925 | Val acc: 54.11% | LR: 0.000020
Epoch: 047 | Train loss: 0.9924 | Train acc: 50.90% | Val loss: 0.9922 | Val acc: 54.15% | LR: 0.000019
Epoch: 048 | Train loss: 0.9972 | Train acc: 50.37% | Val loss: 0.9922 | Val acc: 54.09% | LR: 0.000019
Epoch: 049 | Train loss: 0.9964 | Train acc: 50.19% | Val loss: 0.9921 | Val acc: 54.17% | LR: 0.000019
Epoch: 050 | Train loss: 0.9982 | Train acc: 50.36% | Val loss: 0.9923 | Val acc: 54.15% | LR: 0.000019
Epoch: 051 | Train loss: 0.9901 | Train acc: 50.91% | Val loss: 0.9921 | Val acc: 54.16% | LR: 0.000019
Epoch: 052 | Train loss: 0.9952 | Train acc: 50.57% | Val loss: 0.9923 | Val acc: 54.24% | LR: 0.000018
Epoch: 053 | Train loss: 0.9976 | Train acc: 50.21% | Val loss: 0.9922 | Val acc: 54.26% | LR: 0.000018
Epoch: 054 | Train loss: 0.9962 | Train acc: 50.39% | Val loss: 0.9919 | Val acc: 54.32% | LR: 0.000018
Epoch: 055 | Train loss: 0.9958 | Train acc: 50.47% | Val loss: 0.9917 | Val acc: 54.26% | LR: 0.000018
Epoch: 056 | Train loss: 0.9930 | Train acc: 50.56% | Val loss: 0.9921 | Val acc: 54.30% | LR: 0.000017
Epoch: 057 | Train loss: 0.9966 | Train acc: 50.21% | Val loss: 0.9920 | Val acc: 54.22% | LR: 0.000017
Epoch: 058 | Train loss: 0.9950 | Train acc: 50.58% | Val loss: 0.9913 | Val acc: 54.17% | LR: 0.000017
Epoch: 059 | Train loss: 0.9878 | Train acc: 51.12% | Val loss: 0.9922 | Val acc: 54.16% | LR: 0.000017
Epoch: 060 | Train loss: 0.9936 | Train acc: 50.58% | Val loss: 0.9919 | Val acc: 54.09% | LR: 0.000016
Epoch: 061 | Train loss: 0.9955 | Train acc: 50.56% | Val loss: 0.9928 | Val acc: 54.20% | LR: 0.000016
Epoch: 062 | Train loss: 0.9882 | Train acc: 51.00% | Val loss: 0.9924 | Val acc: 54.10% | LR: 0.000016
Epoch: 063 | Train loss: 0.9945 | Train acc: 50.38% | Val loss: 0.9921 | Val acc: 54.13% | LR: 0.000016
Epoch: 064 | Train loss: 0.9986 | Train acc: 50.09% | Val loss: 0.9922 | Val acc: 54.16% | LR: 0.000016
Epoch: 065 | Train loss: 0.9991 | Train acc: 49.92% | Val loss: 0.9913 | Val acc: 54.28% | LR: 0.000015
Epoch: 066 | Train loss: 0.9988 | Train acc: 50.10% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000015
Epoch: 067 | Train loss: 0.9966 | Train acc: 50.38% | Val loss: 0.9907 | Val acc: 54.38% | LR: 0.000015
Epoch: 068 | Train loss: 0.9954 | Train acc: 50.37% | Val loss: 0.9914 | Val acc: 54.30% | LR: 0.000015
Epoch: 069 | Train loss: 0.9909 | Train acc: 50.71% | Val loss: 0.9910 | Val acc: 54.40% | LR: 0.000014
Epoch: 070 | Train loss: 0.9932 | Train acc: 50.36% | Val loss: 0.9915 | Val acc: 54.32% | LR: 0.000014
Epoch: 071 | Train loss: 0.9887 | Train acc: 50.72% | Val loss: 0.9940 | Val acc: 54.20% | LR: 0.000014
Epoch: 072 | Train loss: 0.9939 | Train acc: 50.46% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000014
Epoch: 073 | Train loss: 0.9954 | Train acc: 50.19% | Val loss: 0.9917 | Val acc: 54.24% | LR: 0.000013
Epoch: 074 | Train loss: 0.9964 | Train acc: 50.47% | Val loss: 0.9924 | Val acc: 54.28% | LR: 0.000013
Epoch: 075 | Train loss: 0.9981 | Train acc: 50.20% | Val loss: 0.9914 | Val acc: 54.38% | LR: 0.000013
Epoch: 076 | Train loss: 0.9938 | Train acc: 50.66% | Val loss: 0.9917 | Val acc: 54.38% | LR: 0.000013
Epoch: 077 | Train loss: 0.9951 | Train acc: 50.41% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000012
Epoch: 078 | Train loss: 0.9887 | Train acc: 50.78% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000012
Epoch: 079 | Train loss: 0.9888 | Train acc: 50.87% | Val loss: 0.9933 | Val acc: 54.44% | LR: 0.000012
Epoch: 080 | Train loss: 0.9961 | Train acc: 50.43% | Val loss: 0.9914 | Val acc: 54.36% | LR: 0.000012
Epoch: 081 | Train loss: 0.9898 | Train acc: 50.89% | Val loss: 1.0040 | Val acc: 54.27% | LR: 0.000011
Epoch: 082 | Train loss: 0.9947 | Train acc: 50.17% | Val loss: 0.9919 | Val acc: 54.20% | LR: 0.000011
Epoch: 083 | Train loss: 0.9896 | Train acc: 50.87% | Val loss: 0.9928 | Val acc: 54.22% | LR: 0.000011
Epoch: 084 | Train loss: 0.9936 | Train acc: 50.60% | Val loss: 0.9916 | Val acc: 54.30% | LR: 0.000011
Epoch: 085 | Train loss: 1.0050 | Train acc: 49.79% | Val loss: 0.9918 | Val acc: 54.18% | LR: 0.000010
Epoch: 086 | Train loss: 0.9891 | Train acc: 50.78% | Val loss: 0.9918 | Val acc: 54.16% | LR: 0.000010
Epoch: 087 | Train loss: 0.9923 | Train acc: 50.53% | Val loss: 0.9916 | Val acc: 54.24% | LR: 0.000010
Epoch: 088 | Train loss: 0.9932 | Train acc: 50.62% | Val loss: 0.9931 | Val acc: 54.20% | LR: 0.000010
Epoch: 089 | Train loss: 0.9849 | Train acc: 51.07% | Val loss: 0.9911 | Val acc: 54.28% | LR: 0.000009
Epoch: 090 | Train loss: 0.9864 | Train acc: 50.94% | Val loss: 0.9916 | Val acc: 54.32% | LR: 0.000009
Epoch: 091 | Train loss: 0.9925 | Train acc: 50.50% | Val loss: 0.9919 | Val acc: 54.24% | LR: 0.000009
Epoch: 092 | Train loss: 0.9924 | Train acc: 50.69% | Val loss: 0.9919 | Val acc: 54.14% | LR: 0.000009
Epoch: 093 | Train loss: 0.9944 | Train acc: 50.41% | Val loss: 0.9915 | Val acc: 54.24% | LR: 0.000008
Epoch: 094 | Train loss: 0.9954 | Train acc: 50.59% | Val loss: 0.9919 | Val acc: 54.21% | LR: 0.000008
Epoch: 095 | Train loss: 0.9925 | Train acc: 50.51% | Val loss: 0.9915 | Val acc: 54.32% | LR: 0.000008
Epoch: 096 | Train loss: 0.9924 | Train acc: 50.41% | Val loss: 0.9914 | Val acc: 54.36% | LR: 0.000008
Epoch: 097 | Train loss: 0.9950 | Train acc: 50.47% | Val loss: 0.9915 | Val acc: 54.49% | LR: 0.000007
Epoch: 098 | Train loss: 0.9872 | Train acc: 50.93% | Val loss: 0.9913 | Val acc: 54.45% | LR: 0.000007
Epoch: 099 | Train loss: 1.0000 | Train acc: 50.06% | Val loss: 0.9913 | Val acc: 54.45% | LR: 0.000007
Epoch: 100 | Train loss: 0.9864 | Train acc: 50.96% | Val loss: 0.9914 | Val acc: 54.47% | LR: 0.000007
Epoch: 101 | Train loss: 0.9922 | Train acc: 50.59% | Val loss: 0.9911 | Val acc: 54.37% | LR: 0.000007
Epoch: 102 | Train loss: 0.9999 | Train acc: 49.97% | Val loss: 0.9917 | Val acc: 54.37% | LR: 0.000006
Epoch: 103 | Train loss: 0.9938 | Train acc: 50.50% | Val loss: 0.9916 | Val acc: 54.30% | LR: 0.000006
Epoch: 104 | Train loss: 0.9918 | Train acc: 50.42% | Val loss: 0.9922 | Val acc: 54.25% | LR: 0.000006
Epoch: 105 | Train loss: 0.9872 | Train acc: 50.78% | Val loss: 0.9918 | Val acc: 54.31% | LR: 0.000006
Epoch: 106 | Train loss: 0.9966 | Train acc: 50.16% | Val loss: 0.9914 | Val acc: 54.29% | LR: 0.000006
Epoch: 107 | Train loss: 0.9844 | Train acc: 51.04% | Val loss: 0.9912 | Val acc: 54.39% | LR: 0.000005
Epoch: 108 | Train loss: 0.9910 | Train acc: 50.79% | Val loss: 0.9917 | Val acc: 54.39% | LR: 0.000005
Epoch: 109 | Train loss: 0.9991 | Train acc: 50.13% | Val loss: 0.9952 | Val acc: 54.41% | LR: 0.000005
Epoch: 110 | Train loss: 0.9914 | Train acc: 50.60% | Val loss: 0.9924 | Val acc: 54.25% | LR: 0.000005
Epoch: 111 | Train loss: 0.9926 | Train acc: 50.61% | Val loss: 0.9915 | Val acc: 54.45% | LR: 0.000005
Epoch: 112 | Train loss: 0.9935 | Train acc: 50.59% | Val loss: 0.9982 | Val acc: 54.23% | LR: 0.000004
Epoch: 113 | Train loss: 0.9909 | Train acc: 50.60% | Val loss: 0.9919 | Val acc: 54.31% | LR: 0.000004
Epoch: 114 | Train loss: 0.9917 | Train acc: 50.76% | Val loss: 0.9916 | Val acc: 54.39% | LR: 0.000004
Epoch: 115 | Train loss: 0.9997 | Train acc: 50.08% | Val loss: 0.9941 | Val acc: 54.25% | LR: 0.000004
Epoch: 116 | Train loss: 0.9878 | Train acc: 50.76% | Val loss: 0.9911 | Val acc: 54.45% | LR: 0.000004
Epoch: 117 | Train loss: 0.9995 | Train acc: 50.06% | Val loss: 0.9919 | Val acc: 54.31% | LR: 0.000004
Epoch: 118 | Train loss: 0.9979 | Train acc: 50.31% | Val loss: 0.9937 | Val acc: 54.45% | LR: 0.000003
Epoch: 119 | Train loss: 0.9874 | Train acc: 50.84% | Val loss: 0.9919 | Val acc: 54.31% | LR: 0.000003
Epoch: 120 | Train loss: 0.9896 | Train acc: 50.67% | Val loss: 0.9912 | Val acc: 54.39% | LR: 0.000003
Epoch: 121 | Train loss: 0.9837 | Train acc: 50.94% | Val loss: 0.9915 | Val acc: 54.47% | LR: 0.000003
Epoch: 122 | Train loss: 0.9891 | Train acc: 50.77% | Val loss: 0.9919 | Val acc: 54.29% | LR: 0.000003
Epoch: 123 | Train loss: 0.9881 | Train acc: 50.84% | Val loss: 0.9932 | Val acc: 54.35% | LR: 0.000003
Epoch: 124 | Train loss: 0.9832 | Train acc: 51.19% | Val loss: 0.9915 | Val acc: 54.41% | LR: 0.000003
Epoch: 125 | Train loss: 0.9920 | Train acc: 50.41% | Val loss: 0.9918 | Val acc: 54.41% | LR: 0.000002
Epoch: 126 | Train loss: 1.0022 | Train acc: 49.97% | Val loss: 0.9913 | Val acc: 54.41% | LR: 0.000002
Epoch: 127 | Train loss: 0.9930 | Train acc: 50.59% | Val loss: 0.9933 | Val acc: 54.39% | LR: 0.000002
Epoch: 128 | Train loss: 0.9856 | Train acc: 51.12% | Val loss: 0.9949 | Val acc: 54.42% | LR: 0.000002
Epoch: 129 | Train loss: 0.9774 | Train acc: 51.38% | Val loss: 0.9917 | Val acc: 54.49% | LR: 0.000002
Epoch: 130 | Train loss: 0.9985 | Train acc: 50.32% | Val loss: 0.9915 | Val acc: 54.46% | LR: 0.000002
Epoch: 131 | Train loss: 0.9881 | Train acc: 50.68% | Val loss: 0.9942 | Val acc: 54.51% | LR: 0.000002
Epoch: 132 | Train loss: 0.9954 | Train acc: 50.41% | Val loss: 0.9926 | Val acc: 54.44% | LR: 0.000002
Epoch: 133 | Train loss: 0.9961 | Train acc: 50.40% | Val loss: 0.9920 | Val acc: 54.42% | LR: 0.000002
Epoch: 134 | Train loss: 0.9917 | Train acc: 50.50% | Val loss: 0.9963 | Val acc: 54.45% | LR: 0.000002
Epoch: 135 | Train loss: 0.9918 | Train acc: 50.60% | Val loss: 0.9939 | Val acc: 54.45% | LR: 0.000002
Epoch: 136 | Train loss: 0.9915 | Train acc: 50.51% | Val loss: 1.0025 | Val acc: 54.51% | LR: 0.000001
Epoch: 137 | Train loss: 0.9919 | Train acc: 50.69% | Val loss: 0.9915 | Val acc: 54.55% | LR: 0.000001
Epoch: 138 | Train loss: 0.9989 | Train acc: 50.25% | Val loss: 0.9914 | Val acc: 54.53% | LR: 0.000001
Epoch: 139 | Train loss: 0.9944 | Train acc: 50.42% | Val loss: 0.9915 | Val acc: 54.53% | LR: 0.000001
Epoch: 140 | Train loss: 0.9913 | Train acc: 50.61% | Val loss: 0.9913 | Val acc: 54.53% | LR: 0.000001
Epoch: 141 | Train loss: 0.9995 | Train acc: 50.08% | Val loss: 0.9914 | Val acc: 54.53% | LR: 0.000001
Epoch: 142 | Train loss: 0.9836 | Train acc: 50.97% | Val loss: 0.9917 | Val acc: 54.53% | LR: 0.000001
Epoch: 143 | Train loss: 0.9910 | Train acc: 50.52% | Val loss: 0.9918 | Val acc: 54.51% | LR: 0.000001
Epoch: 144 | Train loss: 0.9913 | Train acc: 50.70% | Val loss: 0.9915 | Val acc: 54.51% | LR: 0.000001
Epoch: 145 | Train loss: 0.9796 | Train acc: 51.23% | Val loss: 0.9916 | Val acc: 54.51% | LR: 0.000001
Epoch: 146 | Train loss: 0.9885 | Train acc: 50.78% | Val loss: 0.9912 | Val acc: 54.59% | LR: 0.000001
Epoch: 147 | Train loss: 0.9910 | Train acc: 50.51% | Val loss: 0.9915 | Val acc: 54.55% | LR: 0.000001
Epoch: 148 | Train loss: 0.9985 | Train acc: 50.08% | Val loss: 1.0428 | Val acc: 54.55% | LR: 0.000001
Epoch: 149 | Train loss: 0.9971 | Train acc: 50.15% | Val loss: 0.9912 | Val acc: 54.57% | LR: 0.000001

[I 2025-09-23 18:17:30,737] Trial 105 finished with value: 0.5456626892089844 and parameters: {'lr': 2.5023508106769445e-05, 'hidden_size': 75, 'dropout': 0.2509872199855663, 'weight_decay': 1.6170693372357332e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0014 | Train acc: 49.57% | Val loss: 0.9940 | Val acc: 54.07% | LR: 0.000024
Epoch: 001 | Train loss: 1.0003 | Train acc: 50.11% | Val loss: 0.9940 | Val acc: 54.07% | LR: 0.000024
Epoch: 002 | Train loss: 0.9999 | Train acc: 50.40% | Val loss: 0.9939 | Val acc: 54.17% | LR: 0.000024
Epoch: 003 | Train loss: 0.9997 | Train acc: 50.30% | Val loss: 0.9938 | Val acc: 54.24% | LR: 0.000024
Epoch: 004 | Train loss: 0.9995 | Train acc: 50.51% | Val loss: 0.9936 | Val acc: 54.36% | LR: 0.000024
Epoch: 005 | Train loss: 0.9988 | Train acc: 50.83% | Val loss: 0.9936 | Val acc: 54.32% | LR: 0.000024
Epoch: 006 | Train loss: 0.9992 | Train acc: 50.63% | Val loss: 0.9935 | Val acc: 54.40% | LR: 0.000024
Epoch: 007 | Train loss: 1.0002 | Train acc: 49.86% | Val loss: 0.9935 | Val acc: 54.42% | LR: 0.000024
Epoch: 008 | Train loss: 0.9999 | Train acc: 50.03% | Val loss: 0.9936 | Val acc: 54.30% | LR: 0.000024
Epoch: 009 | Train loss: 0.9995 | Train acc: 50.29% | Val loss: 0.9935 | Val acc: 54.48% | LR: 0.000024
Epoch: 010 | Train loss: 1.0000 | Train acc: 50.18% | Val loss: 0.9935 | Val acc: 54.55% | LR: 0.000024
Epoch: 011 | Train loss: 1.0010 | Train acc: 49.55% | Val loss: 0.9933 | Val acc: 54.34% | LR: 0.000024
Epoch: 012 | Train loss: 0.9994 | Train acc: 50.07% | Val loss: 0.9933 | Val acc: 54.42% | LR: 0.000024
Epoch: 013 | Train loss: 0.9982 | Train acc: 50.65% | Val loss: 0.9935 | Val acc: 54.18% | LR: 0.000023
Epoch: 014 | Train loss: 0.9980 | Train acc: 50.58% | Val loss: 0.9935 | Val acc: 54.36% | LR: 0.000023
Epoch: 015 | Train loss: 0.9993 | Train acc: 50.13% | Val loss: 0.9936 | Val acc: 54.11% | LR: 0.000023
Epoch: 016 | Train loss: 0.9975 | Train acc: 50.77% | Val loss: 0.9935 | Val acc: 54.03% | LR: 0.000023
Epoch: 017 | Train loss: 0.9967 | Train acc: 50.89% | Val loss: 0.9936 | Val acc: 53.98% | LR: 0.000023
Epoch: 018 | Train loss: 0.9989 | Train acc: 50.07% | Val loss: 0.9934 | Val acc: 53.83% | LR: 0.000023
Epoch: 019 | Train loss: 0.9984 | Train acc: 50.35% | Val loss: 0.9934 | Val acc: 54.14% | LR: 0.000023
Epoch: 020 | Train loss: 0.9987 | Train acc: 50.43% | Val loss: 0.9933 | Val acc: 54.45% | LR: 0.000023
Epoch: 021 | Train loss: 0.9980 | Train acc: 50.55% | Val loss: 0.9931 | Val acc: 54.39% | LR: 0.000023
Epoch: 022 | Train loss: 0.9977 | Train acc: 50.67% | Val loss: 0.9929 | Val acc: 54.43% | LR: 0.000023
Epoch: 023 | Train loss: 1.0018 | Train acc: 49.74% | Val loss: 0.9928 | Val acc: 54.42% | LR: 0.000023
Epoch: 024 | Train loss: 0.9957 | Train acc: 51.34% | Val loss: 0.9927 | Val acc: 54.36% | LR: 0.000022
Epoch: 025 | Train loss: 0.9989 | Train acc: 50.19% | Val loss: 0.9927 | Val acc: 53.98% | LR: 0.000022
Epoch: 026 | Train loss: 0.9967 | Train acc: 50.80% | Val loss: 0.9926 | Val acc: 53.86% | LR: 0.000022
Epoch: 027 | Train loss: 0.9982 | Train acc: 50.46% | Val loss: 0.9924 | Val acc: 53.78% | LR: 0.000022
Epoch: 028 | Train loss: 0.9975 | Train acc: 50.69% | Val loss: 0.9924 | Val acc: 53.60% | LR: 0.000022
Epoch: 029 | Train loss: 0.9974 | Train acc: 50.49% | Val loss: 0.9923 | Val acc: 53.72% | LR: 0.000022
Epoch: 030 | Train loss: 0.9957 | Train acc: 51.01% | Val loss: 0.9921 | Val acc: 53.72% | LR: 0.000022
Epoch: 031 | Train loss: 0.9967 | Train acc: 50.67% | Val loss: 0.9921 | Val acc: 53.68% | LR: 0.000021
Epoch: 032 | Train loss: 0.9933 | Train acc: 51.37% | Val loss: 0.9919 | Val acc: 53.76% | LR: 0.000021
Epoch: 033 | Train loss: 0.9952 | Train acc: 51.07% | Val loss: 0.9918 | Val acc: 53.63% | LR: 0.000021
Epoch: 034 | Train loss: 0.9965 | Train acc: 50.76% | Val loss: 0.9916 | Val acc: 53.75% | LR: 0.000021
Epoch: 035 | Train loss: 0.9900 | Train acc: 51.93% | Val loss: 0.9913 | Val acc: 53.75% | LR: 0.000021
Epoch: 036 | Train loss: 0.9929 | Train acc: 51.37% | Val loss: 0.9912 | Val acc: 53.72% | LR: 0.000021
Epoch: 037 | Train loss: 0.9963 | Train acc: 50.93% | Val loss: 0.9912 | Val acc: 53.57% | LR: 0.000021
Epoch: 038 | Train loss: 0.9952 | Train acc: 51.11% | Val loss: 0.9910 | Val acc: 53.57% | LR: 0.000020
Epoch: 039 | Train loss: 0.9969 | Train acc: 50.64% | Val loss: 0.9910 | Val acc: 53.31% | LR: 0.000020
Epoch: 040 | Train loss: 0.9970 | Train acc: 50.75% | Val loss: 0.9909 | Val acc: 53.39% | LR: 0.000020
Epoch: 041 | Train loss: 0.9922 | Train acc: 51.46% | Val loss: 0.9905 | Val acc: 53.39% | LR: 0.000020
Epoch: 042 | Train loss: 0.9951 | Train acc: 50.86% | Val loss: 0.9903 | Val acc: 53.47% | LR: 0.000020
Epoch: 043 | Train loss: 0.9941 | Train acc: 51.11% | Val loss: 0.9902 | Val acc: 53.52% | LR: 0.000019
Epoch: 044 | Train loss: 0.9955 | Train acc: 50.76% | Val loss: 0.9900 | Val acc: 53.40% | LR: 0.000019
Epoch: 045 | Train loss: 0.9940 | Train acc: 51.20% | Val loss: 0.9898 | Val acc: 53.28% | LR: 0.000019
Epoch: 046 | Train loss: 0.9951 | Train acc: 50.75% | Val loss: 0.9895 | Val acc: 53.20% | LR: 0.000019
Epoch: 047 | Train loss: 0.9957 | Train acc: 50.83% | Val loss: 0.9893 | Val acc: 53.18% | LR: 0.000019
Epoch: 048 | Train loss: 0.9940 | Train acc: 50.92% | Val loss: 0.9890 | Val acc: 53.18% | LR: 0.000018
Epoch: 049 | Train loss: 0.9904 | Train acc: 51.45% | Val loss: 0.9889 | Val acc: 53.08% | LR: 0.000018
Epoch: 050 | Train loss: 0.9923 | Train acc: 51.02% | Val loss: 0.9885 | Val acc: 53.08% | LR: 0.000018
Epoch: 051 | Train loss: 0.9940 | Train acc: 51.02% | Val loss: 0.9883 | Val acc: 53.00% | LR: 0.000018
Epoch: 052 | Train loss: 0.9928 | Train acc: 51.02% | Val loss: 0.9879 | Val acc: 53.02% | LR: 0.000018
Epoch: 053 | Train loss: 0.9885 | Train acc: 51.46% | Val loss: 0.9876 | Val acc: 52.94% | LR: 0.000017
Epoch: 054 | Train loss: 0.9940 | Train acc: 50.76% | Val loss: 0.9872 | Val acc: 52.94% | LR: 0.000017
Epoch: 055 | Train loss: 0.9931 | Train acc: 50.87% | Val loss: 0.9869 | Val acc: 52.90% | LR: 0.000017
Epoch: 056 | Train loss: 0.9952 | Train acc: 50.51% | Val loss: 0.9868 | Val acc: 52.88% | LR: 0.000017
Epoch: 057 | Train loss: 0.9897 | Train acc: 51.04% | Val loss: 0.9865 | Val acc: 52.90% | LR: 0.000016
Epoch: 058 | Train loss: 0.9897 | Train acc: 51.05% | Val loss: 0.9862 | Val acc: 52.86% | LR: 0.000016
Epoch: 059 | Train loss: 0.9917 | Train acc: 51.05% | Val loss: 0.9860 | Val acc: 52.80% | LR: 0.000016

[I 2025-09-23 18:18:18,296] Trial 106 finished with value: 0.5277870178222657 and parameters: {'lr': 2.3958693887906765e-05, 'hidden_size': 66, 'dropout': 0.25261030329222006, 'weight_decay': 4.1880066522772485e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 0.9998 | Train acc: 50.11% | Val loss: 1.0043 | Val acc: 45.95% | LR: 0.000020
Epoch: 001 | Train loss: 0.9991 | Train acc: 50.37% | Val loss: 1.0043 | Val acc: 45.91% | LR: 0.000020
Epoch: 002 | Train loss: 0.9995 | Train acc: 50.23% | Val loss: 1.0043 | Val acc: 45.95% | LR: 0.000020
Epoch: 003 | Train loss: 0.9995 | Train acc: 50.23% | Val loss: 1.0044 | Val acc: 45.97% | LR: 0.000020
Epoch: 004 | Train loss: 0.9992 | Train acc: 50.35% | Val loss: 1.0045 | Val acc: 45.97% | LR: 0.000020
Epoch: 005 | Train loss: 0.9990 | Train acc: 50.76% | Val loss: 1.0045 | Val acc: 46.05% | LR: 0.000020
Epoch: 006 | Train loss: 0.9989 | Train acc: 50.50% | Val loss: 1.0045 | Val acc: 46.15% | LR: 0.000020
Epoch: 007 | Train loss: 0.9977 | Train acc: 51.12% | Val loss: 1.0045 | Val acc: 46.19% | LR: 0.000020
Epoch: 008 | Train loss: 0.9986 | Train acc: 50.68% | Val loss: 1.0046 | Val acc: 46.11% | LR: 0.000020
Epoch: 009 | Train loss: 0.9987 | Train acc: 50.60% | Val loss: 1.0046 | Val acc: 46.21% | LR: 0.000020
Epoch: 010 | Train loss: 0.9984 | Train acc: 50.63% | Val loss: 1.0046 | Val acc: 46.34% | LR: 0.000020
Epoch: 011 | Train loss: 0.9982 | Train acc: 50.70% | Val loss: 1.0046 | Val acc: 46.42% | LR: 0.000020
Epoch: 012 | Train loss: 0.9978 | Train acc: 50.82% | Val loss: 1.0047 | Val acc: 46.40% | LR: 0.000020
Epoch: 013 | Train loss: 0.9972 | Train acc: 50.79% | Val loss: 1.0047 | Val acc: 46.34% | LR: 0.000020
Epoch: 014 | Train loss: 1.0003 | Train acc: 49.92% | Val loss: 1.0047 | Val acc: 46.44% | LR: 0.000019
Epoch: 015 | Train loss: 0.9966 | Train acc: 51.08% | Val loss: 1.0047 | Val acc: 46.46% | LR: 0.000019
Epoch: 016 | Train loss: 0.9973 | Train acc: 50.66% | Val loss: 1.0048 | Val acc: 46.44% | LR: 0.000019
Epoch: 017 | Train loss: 0.9988 | Train acc: 50.44% | Val loss: 1.0047 | Val acc: 46.70% | LR: 0.000019
Epoch: 018 | Train loss: 0.9975 | Train acc: 50.71% | Val loss: 1.0048 | Val acc: 46.60% | LR: 0.000019
Epoch: 019 | Train loss: 0.9992 | Train acc: 50.26% | Val loss: 1.0048 | Val acc: 46.72% | LR: 0.000019
Epoch: 020 | Train loss: 0.9977 | Train acc: 50.65% | Val loss: 1.0048 | Val acc: 46.52% | LR: 0.000019
Epoch: 021 | Train loss: 0.9962 | Train acc: 50.90% | Val loss: 1.0058 | Val acc: 46.52% | LR: 0.000019
Epoch: 022 | Train loss: 0.9968 | Train acc: 50.72% | Val loss: 1.0047 | Val acc: 46.62% | LR: 0.000019
Epoch: 023 | Train loss: 0.9966 | Train acc: 50.81% | Val loss: 1.0048 | Val acc: 46.62% | LR: 0.000019
Epoch: 024 | Train loss: 0.9974 | Train acc: 50.65% | Val loss: 1.0047 | Val acc: 46.80% | LR: 0.000019
Epoch: 025 | Train loss: 0.9977 | Train acc: 50.60% | Val loss: 1.0056 | Val acc: 46.79% | LR: 0.000019
Epoch: 026 | Train loss: 0.9982 | Train acc: 50.41% | Val loss: 1.0044 | Val acc: 46.64% | LR: 0.000018
Epoch: 027 | Train loss: 0.9944 | Train acc: 51.14% | Val loss: 1.0046 | Val acc: 46.60% | LR: 0.000018
Epoch: 028 | Train loss: 0.9965 | Train acc: 50.92% | Val loss: 1.0046 | Val acc: 46.78% | LR: 0.000018
Epoch: 029 | Train loss: 0.9971 | Train acc: 50.65% | Val loss: 1.0048 | Val acc: 46.68% | LR: 0.000018
Epoch: 030 | Train loss: 0.9972 | Train acc: 50.74% | Val loss: 1.0048 | Val acc: 46.85% | LR: 0.000018
Epoch: 031 | Train loss: 0.9934 | Train acc: 51.40% | Val loss: 1.0048 | Val acc: 46.86% | LR: 0.000018
Epoch: 032 | Train loss: 0.9957 | Train acc: 50.83% | Val loss: 1.0050 | Val acc: 46.84% | LR: 0.000018
Epoch: 033 | Train loss: 0.9965 | Train acc: 50.58% | Val loss: 1.0047 | Val acc: 46.94% | LR: 0.000018
Epoch: 034 | Train loss: 0.9962 | Train acc: 50.98% | Val loss: 1.0045 | Val acc: 46.88% | LR: 0.000018
Epoch: 035 | Train loss: 0.9960 | Train acc: 50.78% | Val loss: 1.0049 | Val acc: 47.01% | LR: 0.000017
Epoch: 036 | Train loss: 0.9975 | Train acc: 50.53% | Val loss: 1.0044 | Val acc: 47.02% | LR: 0.000017
Epoch: 037 | Train loss: 0.9968 | Train acc: 50.77% | Val loss: 1.0042 | Val acc: 46.96% | LR: 0.000017
Epoch: 038 | Train loss: 0.9945 | Train acc: 51.06% | Val loss: 1.0059 | Val acc: 46.93% | LR: 0.000017
Epoch: 039 | Train loss: 0.9914 | Train acc: 51.51% | Val loss: 1.0042 | Val acc: 46.96% | LR: 0.000017
Epoch: 040 | Train loss: 0.9944 | Train acc: 51.17% | Val loss: 1.0042 | Val acc: 47.06% | LR: 0.000017
Epoch: 041 | Train loss: 0.9942 | Train acc: 50.89% | Val loss: 1.0043 | Val acc: 47.10% | LR: 0.000017
Epoch: 042 | Train loss: 0.9939 | Train acc: 51.08% | Val loss: 1.0045 | Val acc: 47.06% | LR: 0.000016
Epoch: 043 | Train loss: 0.9949 | Train acc: 50.91% | Val loss: 1.0047 | Val acc: 47.02% | LR: 0.000016
Epoch: 044 | Train loss: 0.9918 | Train acc: 51.33% | Val loss: 1.0043 | Val acc: 47.20% | LR: 0.000016
Epoch: 045 | Train loss: 0.9924 | Train acc: 51.24% | Val loss: 1.0043 | Val acc: 47.35% | LR: 0.000016
Epoch: 046 | Train loss: 0.9926 | Train acc: 51.06% | Val loss: 1.0042 | Val acc: 47.55% | LR: 0.000016
Epoch: 047 | Train loss: 0.9962 | Train acc: 50.62% | Val loss: 1.0043 | Val acc: 47.65% | LR: 0.000016
Epoch: 048 | Train loss: 0.9959 | Train acc: 50.62% | Val loss: 1.0041 | Val acc: 47.77% | LR: 0.000015
Epoch: 049 | Train loss: 0.9927 | Train acc: 51.19% | Val loss: 1.0064 | Val acc: 47.89% | LR: 0.000015
Epoch: 050 | Train loss: 0.9920 | Train acc: 51.30% | Val loss: 1.0028 | Val acc: 48.05% | LR: 0.000015
Epoch: 051 | Train loss: 0.9965 | Train acc: 50.65% | Val loss: 1.0035 | Val acc: 48.08% | LR: 0.000015
Epoch: 052 | Train loss: 0.9925 | Train acc: 51.01% | Val loss: 1.0037 | Val acc: 48.10% | LR: 0.000015
Epoch: 053 | Train loss: 0.9951 | Train acc: 50.83% | Val loss: 1.0038 | Val acc: 48.04% | LR: 0.000015
Epoch: 054 | Train loss: 0.9918 | Train acc: 51.21% | Val loss: 1.0041 | Val acc: 48.06% | LR: 0.000014
Epoch: 055 | Train loss: 0.9907 | Train acc: 51.22% | Val loss: 1.0032 | Val acc: 48.08% | LR: 0.000014
Epoch: 056 | Train loss: 0.9951 | Train acc: 50.70% | Val loss: 1.0036 | Val acc: 48.12% | LR: 0.000014
Epoch: 057 | Train loss: 0.9961 | Train acc: 50.59% | Val loss: 1.0033 | Val acc: 48.12% | LR: 0.000014
Epoch: 058 | Train loss: 0.9951 | Train acc: 50.70% | Val loss: 1.0030 | Val acc: 48.12% | LR: 0.000014
Epoch: 059 | Train loss: 0.9876 | Train acc: 51.35% | Val loss: 1.0028 | Val acc: 48.24% | LR: 0.000013
Epoch: 060 | Train loss: 1.0001 | Train acc: 50.35% | Val loss: 1.0031 | Val acc: 48.25% | LR: 0.000013
Epoch: 061 | Train loss: 0.9887 | Train acc: 51.32% | Val loss: 1.0033 | Val acc: 48.33% | LR: 0.000013
Epoch: 062 | Train loss: 0.9874 | Train acc: 51.41% | Val loss: 1.0027 | Val acc: 48.39% | LR: 0.000013
Epoch: 063 | Train loss: 0.9906 | Train acc: 51.19% | Val loss: 1.0027 | Val acc: 48.47% | LR: 0.000013
Epoch: 064 | Train loss: 0.9914 | Train acc: 50.85% | Val loss: 1.0026 | Val acc: 48.45% | LR: 0.000012
Epoch: 065 | Train loss: 0.9899 | Train acc: 51.02% | Val loss: 1.0026 | Val acc: 48.53% | LR: 0.000012
Epoch: 066 | Train loss: 0.9913 | Train acc: 50.75% | Val loss: 1.0024 | Val acc: 48.76% | LR: 0.000012
Epoch: 067 | Train loss: 0.9897 | Train acc: 51.08% | Val loss: 1.0020 | Val acc: 48.82% | LR: 0.000012
Epoch: 068 | Train loss: 0.9891 | Train acc: 51.09% | Val loss: 1.0020 | Val acc: 48.92% | LR: 0.000012
Epoch: 069 | Train loss: 0.9918 | Train acc: 50.74% | Val loss: 1.0020 | Val acc: 48.98% | LR: 0.000011
Epoch: 070 | Train loss: 0.9942 | Train acc: 50.47% | Val loss: 1.0021 | Val acc: 49.06% | LR: 0.000011
Epoch: 071 | Train loss: 0.9921 | Train acc: 50.73% | Val loss: 1.0018 | Val acc: 49.12% | LR: 0.000011
Epoch: 072 | Train loss: 0.9908 | Train acc: 50.82% | Val loss: 1.0018 | Val acc: 49.13% | LR: 0.000011
Epoch: 073 | Train loss: 0.9854 | Train acc: 51.43% | Val loss: 1.0017 | Val acc: 49.17% | LR: 0.000011
Epoch: 074 | Train loss: 0.9828 | Train acc: 51.51% | Val loss: 1.0019 | Val acc: 49.15% | LR: 0.000010
Epoch: 075 | Train loss: 0.9882 | Train acc: 50.90% | Val loss: 1.0025 | Val acc: 49.15% | LR: 0.000010
Epoch: 076 | Train loss: 0.9875 | Train acc: 50.99% | Val loss: 1.0027 | Val acc: 49.29% | LR: 0.000010
Epoch: 077 | Train loss: 0.9930 | Train acc: 50.47% | Val loss: 1.0033 | Val acc: 49.41% | LR: 0.000010
Epoch: 078 | Train loss: 0.9935 | Train acc: 50.73% | Val loss: 1.0104 | Val acc: 49.32% | LR: 0.000010
Epoch: 079 | Train loss: 0.9908 | Train acc: 51.07% | Val loss: 1.0769 | Val acc: 49.14% | LR: 0.000009
Epoch: 080 | Train loss: 1.0449 | Train acc: 50.58% | Val loss: 1.0069 | Val acc: 49.33% | LR: 0.000009
Epoch: 081 | Train loss: 0.9904 | Train acc: 51.05% | Val loss: 1.0030 | Val acc: 49.21% | LR: 0.000009
Epoch: 082 | Train loss: 0.9850 | Train acc: 51.25% | Val loss: 1.0047 | Val acc: 49.35% | LR: 0.000009
Epoch: 083 | Train loss: 0.9895 | Train acc: 51.14% | Val loss: 1.0492 | Val acc: 49.15% | LR: 0.000009
Epoch: 084 | Train loss: 0.9876 | Train acc: 50.86% | Val loss: 1.0077 | Val acc: 49.39% | LR: 0.000009
Epoch: 085 | Train loss: 0.9858 | Train acc: 51.13% | Val loss: 1.0071 | Val acc: 49.39% | LR: 0.000008
Epoch: 086 | Train loss: 0.9942 | Train acc: 50.42% | Val loss: 1.0161 | Val acc: 49.10% | LR: 0.000008
Epoch: 087 | Train loss: 0.9853 | Train acc: 51.29% | Val loss: 1.0651 | Val acc: 49.04% | LR: 0.000008
Epoch: 088 | Train loss: 0.9874 | Train acc: 50.96% | Val loss: 1.0672 | Val acc: 49.31% | LR: 0.000008
Epoch: 089 | Train loss: 0.9935 | Train acc: 50.56% | Val loss: 1.0189 | Val acc: 49.40% | LR: 0.000008
Epoch: 090 | Train loss: 0.9860 | Train acc: 51.32% | Val loss: 1.0023 | Val acc: 49.48% | LR: 0.000007
Epoch: 091 | Train loss: 0.9963 | Train acc: 51.14% | Val loss: 1.0109 | Val acc: 49.48% | LR: 0.000007
Epoch: 092 | Train loss: 0.9924 | Train acc: 50.62% | Val loss: 1.0019 | Val acc: 49.49% | LR: 0.000007
Epoch: 093 | Train loss: 0.9900 | Train acc: 50.87% | Val loss: 1.0162 | Val acc: 49.44% | LR: 0.000007
Epoch: 094 | Train loss: 0.9960 | Train acc: 50.19% | Val loss: 1.0010 | Val acc: 49.49% | LR: 0.000007
Epoch: 095 | Train loss: 0.9910 | Train acc: 50.79% | Val loss: 1.0024 | Val acc: 49.49% | LR: 0.000006
Epoch: 096 | Train loss: 0.9883 | Train acc: 51.14% | Val loss: 1.0172 | Val acc: 49.38% | LR: 0.000006
Epoch: 097 | Train loss: 0.9922 | Train acc: 51.08% | Val loss: 1.0158 | Val acc: 49.36% | LR: 0.000006
Epoch: 098 | Train loss: 0.9952 | Train acc: 50.45% | Val loss: 1.0054 | Val acc: 49.44% | LR: 0.000006
Epoch: 099 | Train loss: 0.9969 | Train acc: 50.15% | Val loss: 1.0061 | Val acc: 49.55% | LR: 0.000006
Epoch: 100 | Train loss: 0.9911 | Train acc: 50.79% | Val loss: 1.0035 | Val acc: 49.47% | LR: 0.000006
Epoch: 101 | Train loss: 0.9904 | Train acc: 50.90% | Val loss: 1.0236 | Val acc: 49.47% | LR: 0.000005
Epoch: 102 | Train loss: 1.0003 | Train acc: 50.35% | Val loss: 1.0099 | Val acc: 49.51% | LR: 0.000005
Epoch: 103 | Train loss: 0.9895 | Train acc: 51.07% | Val loss: 1.0269 | Val acc: 49.18% | LR: 0.000005
Epoch: 104 | Train loss: 0.9918 | Train acc: 50.56% | Val loss: 1.0160 | Val acc: 49.32% | LR: 0.000005
Epoch: 105 | Train loss: 0.9871 | Train acc: 51.02% | Val loss: 1.0650 | Val acc: 49.30% | LR: 0.000005
Epoch: 106 | Train loss: 0.9877 | Train acc: 51.09% | Val loss: 1.0200 | Val acc: 49.20% | LR: 0.000005
Epoch: 107 | Train loss: 0.9846 | Train acc: 51.44% | Val loss: 1.0252 | Val acc: 49.55% | LR: 0.000004
Epoch: 108 | Train loss: 1.0065 | Train acc: 50.96% | Val loss: 1.0020 | Val acc: 49.51% | LR: 0.000004
Epoch: 109 | Train loss: 0.9898 | Train acc: 50.86% | Val loss: 1.0020 | Val acc: 49.43% | LR: 0.000004
Epoch: 110 | Train loss: 0.9908 | Train acc: 51.16% | Val loss: 1.0166 | Val acc: 49.20% | LR: 0.000004
Epoch: 111 | Train loss: 0.9944 | Train acc: 50.48% | Val loss: 1.0208 | Val acc: 49.11% | LR: 0.000004
Epoch: 112 | Train loss: 0.9920 | Train acc: 50.90% | Val loss: 1.0010 | Val acc: 49.39% | LR: 0.000004
Epoch: 113 | Train loss: 0.9900 | Train acc: 51.05% | Val loss: 1.0069 | Val acc: 49.49% | LR: 0.000004
Epoch: 114 | Train loss: 0.9946 | Train acc: 50.52% | Val loss: 1.0001 | Val acc: 49.43% | LR: 0.000003
Epoch: 115 | Train loss: 0.9890 | Train acc: 50.88% | Val loss: 1.0194 | Val acc: 49.45% | LR: 0.000003
Epoch: 116 | Train loss: 1.0006 | Train acc: 50.24% | Val loss: 1.0165 | Val acc: 49.43% | LR: 0.000003
Epoch: 117 | Train loss: 0.9964 | Train acc: 50.51% | Val loss: 1.0114 | Val acc: 49.43% | LR: 0.000003
Epoch: 118 | Train loss: 0.9864 | Train acc: 51.58% | Val loss: 1.0061 | Val acc: 49.51% | LR: 0.000003
Epoch: 119 | Train loss: 0.9923 | Train acc: 50.78% | Val loss: 1.0039 | Val acc: 49.35% | LR: 0.000003
Epoch: 120 | Train loss: 0.9914 | Train acc: 50.88% | Val loss: 1.0194 | Val acc: 49.31% | LR: 0.000003
Epoch: 121 | Train loss: 0.9953 | Train acc: 50.36% | Val loss: 1.0103 | Val acc: 49.53% | LR: 0.000003
Epoch: 122 | Train loss: 0.9840 | Train acc: 51.31% | Val loss: 1.1062 | Val acc: 49.47% | LR: 0.000002
Epoch: 123 | Train loss: 0.9907 | Train acc: 50.86% | Val loss: 1.0086 | Val acc: 49.47% | LR: 0.000002
Epoch: 124 | Train loss: 0.9943 | Train acc: 50.51% | Val loss: 1.0075 | Val acc: 49.47% | LR: 0.000002
Epoch: 125 | Train loss: 0.9913 | Train acc: 50.95% | Val loss: 1.0354 | Val acc: 49.43% | LR: 0.000002
Epoch: 126 | Train loss: 0.9906 | Train acc: 50.67% | Val loss: 1.0048 | Val acc: 49.43% | LR: 0.000002
Epoch: 127 | Train loss: 0.9879 | Train acc: 50.94% | Val loss: 1.0168 | Val acc: 49.37% | LR: 0.000002
Epoch: 128 | Train loss: 0.9854 | Train acc: 51.12% | Val loss: 1.0047 | Val acc: 49.47% | LR: 0.000002
Epoch: 129 | Train loss: 0.9870 | Train acc: 51.20% | Val loss: 1.0017 | Val acc: 49.47% | LR: 0.000002
Epoch: 130 | Train loss: 0.9897 | Train acc: 50.77% | Val loss: 1.0023 | Val acc: 49.47% | LR: 0.000002
Epoch: 131 | Train loss: 0.9842 | Train acc: 51.22% | Val loss: 1.0244 | Val acc: 49.39% | LR: 0.000002
Epoch: 132 | Train loss: 0.9872 | Train acc: 50.96% | Val loss: 1.0255 | Val acc: 49.47% | LR: 0.000002
Epoch: 133 | Train loss: 0.9903 | Train acc: 50.77% | Val loss: 1.0042 | Val acc: 49.47% | LR: 0.000002
Epoch: 134 | Train loss: 0.9884 | Train acc: 51.05% | Val loss: 1.0055 | Val acc: 49.43% | LR: 0.000001
Epoch: 135 | Train loss: 0.9905 | Train acc: 50.86% | Val loss: 1.0102 | Val acc: 49.45% | LR: 0.000001
Epoch: 136 | Train loss: 0.9875 | Train acc: 51.04% | Val loss: 1.0088 | Val acc: 49.43% | LR: 0.000001
Epoch: 137 | Train loss: 0.9853 | Train acc: 51.22% | Val loss: 1.0215 | Val acc: 49.39% | LR: 0.000001
Epoch: 138 | Train loss: 0.9905 | Train acc: 50.77% | Val loss: 1.0089 | Val acc: 49.39% | LR: 0.000001
Epoch: 139 | Train loss: 0.9890 | Train acc: 50.95% | Val loss: 1.0129 | Val acc: 49.37% | LR: 0.000001
Epoch: 140 | Train loss: 0.9913 | Train acc: 50.95% | Val loss: 1.0007 | Val acc: 49.45% | LR: 0.000001
Epoch: 141 | Train loss: 0.9942 | Train acc: 50.70% | Val loss: 1.0087 | Val acc: 49.41% | LR: 0.000001
Epoch: 142 | Train loss: 0.9954 | Train acc: 50.69% | Val loss: 1.0783 | Val acc: 49.37% | LR: 0.000001
Epoch: 143 | Train loss: 0.9839 | Train acc: 51.31% | Val loss: 1.0180 | Val acc: 49.39% | LR: 0.000001
Epoch: 144 | Train loss: 0.9894 | Train acc: 50.86% | Val loss: 1.0102 | Val acc: 49.41% | LR: 0.000001
Epoch: 145 | Train loss: 0.9914 | Train acc: 50.59% | Val loss: 1.0115 | Val acc: 49.41% | LR: 0.000001
Epoch: 146 | Train loss: 0.9884 | Train acc: 50.95% | Val loss: 1.0132 | Val acc: 49.37% | LR: 0.000001
Epoch: 147 | Train loss: 0.9886 | Train acc: 50.86% | Val loss: 1.0243 | Val acc: 49.39% | LR: 0.000001
Epoch: 148 | Train loss: 0.9881 | Train acc: 51.04% | Val loss: 1.0244 | Val acc: 49.39% | LR: 0.000001

[I 2025-09-23 18:20:21,708] Trial 107 finished with value: 0.4940912425518036 and parameters: {'lr': 1.9950579398646168e-05, 'hidden_size': 80, 'dropout': 0.2147572581490792, 'weight_decay': 2.946213772260108e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0006 | Train acc: 49.83% | Val loss: 1.0083 | Val acc: 45.93% | LR: 0.000027
Epoch: 001 | Train loss: 1.0005 | Train acc: 49.47% | Val loss: 1.0060 | Val acc: 45.91% | LR: 0.000027
Epoch: 002 | Train loss: 1.0006 | Train acc: 49.46% | Val loss: 1.0059 | Val acc: 45.82% | LR: 0.000027
Epoch: 003 | Train loss: 1.0007 | Train acc: 48.62% | Val loss: 1.0052 | Val acc: 46.07% | LR: 0.000027
Epoch: 004 | Train loss: 0.9998 | Train acc: 50.21% | Val loss: 1.0089 | Val acc: 46.09% | LR: 0.000027
Epoch: 005 | Train loss: 0.9998 | Train acc: 50.18% | Val loss: 1.0057 | Val acc: 45.87% | LR: 0.000027
Epoch: 006 | Train loss: 0.9996 | Train acc: 50.23% | Val loss: 1.0062 | Val acc: 45.93% | LR: 0.000027
Epoch: 007 | Train loss: 1.0002 | Train acc: 49.59% | Val loss: 1.0060 | Val acc: 46.03% | LR: 0.000027
Epoch: 008 | Train loss: 1.0000 | Train acc: 49.98% | Val loss: 1.0116 | Val acc: 45.87% | LR: 0.000027
Epoch: 009 | Train loss: 0.9993 | Train acc: 50.44% | Val loss: 1.0080 | Val acc: 45.81% | LR: 0.000027
Epoch: 010 | Train loss: 0.9997 | Train acc: 50.40% | Val loss: 1.0060 | Val acc: 45.96% | LR: 0.000027
Epoch: 011 | Train loss: 0.9998 | Train acc: 50.39% | Val loss: 1.0069 | Val acc: 46.15% | LR: 0.000026
Epoch: 012 | Train loss: 0.9990 | Train acc: 50.70% | Val loss: 1.0095 | Val acc: 45.95% | LR: 0.000026
Epoch: 013 | Train loss: 1.0007 | Train acc: 49.72% | Val loss: 1.0077 | Val acc: 45.97% | LR: 0.000026
Epoch: 014 | Train loss: 1.0002 | Train acc: 50.14% | Val loss: 1.0344 | Val acc: 45.91% | LR: 0.000026
Epoch: 015 | Train loss: 0.9989 | Train acc: 50.78% | Val loss: 1.0068 | Val acc: 46.14% | LR: 0.000026
Epoch: 016 | Train loss: 0.9987 | Train acc: 50.77% | Val loss: 1.0052 | Val acc: 45.99% | LR: 0.000026
Epoch: 017 | Train loss: 0.9990 | Train acc: 50.50% | Val loss: 1.0062 | Val acc: 45.95% | LR: 0.000026
Epoch: 018 | Train loss: 1.0001 | Train acc: 50.03% | Val loss: 1.0092 | Val acc: 45.93% | LR: 0.000026
Epoch: 019 | Train loss: 0.9994 | Train acc: 50.40% | Val loss: 1.0077 | Val acc: 45.97% | LR: 0.000026
Epoch: 020 | Train loss: 0.9984 | Train acc: 50.68% | Val loss: 1.0076 | Val acc: 45.95% | LR: 0.000026
Epoch: 021 | Train loss: 0.9987 | Train acc: 50.50% | Val loss: 1.0063 | Val acc: 45.93% | LR: 0.000026
Epoch: 022 | Train loss: 0.9986 | Train acc: 50.45% | Val loss: 1.0141 | Val acc: 45.93% | LR: 0.000025
Epoch: 023 | Train loss: 0.9991 | Train acc: 50.25% | Val loss: 1.0090 | Val acc: 45.98% | LR: 0.000025
Epoch: 024 | Train loss: 0.9984 | Train acc: 50.61% | Val loss: 1.0099 | Val acc: 46.01% | LR: 0.000025
Epoch: 025 | Train loss: 0.9998 | Train acc: 50.14% | Val loss: 1.0062 | Val acc: 45.91% | LR: 0.000025
Epoch: 026 | Train loss: 1.0028 | Train acc: 50.69% | Val loss: 1.0066 | Val acc: 45.89% | LR: 0.000025
Epoch: 027 | Train loss: 0.9997 | Train acc: 50.06% | Val loss: 1.0089 | Val acc: 45.92% | LR: 0.000025
Epoch: 028 | Train loss: 0.9973 | Train acc: 50.88% | Val loss: 1.0061 | Val acc: 45.99% | LR: 0.000025
Epoch: 029 | Train loss: 0.9997 | Train acc: 50.07% | Val loss: 1.0064 | Val acc: 46.01% | LR: 0.000024
Epoch: 030 | Train loss: 0.9985 | Train acc: 50.51% | Val loss: 1.0195 | Val acc: 46.05% | LR: 0.000024
Epoch: 031 | Train loss: 0.9968 | Train acc: 50.87% | Val loss: 1.0549 | Val acc: 45.93% | LR: 0.000024
Epoch: 032 | Train loss: 0.9973 | Train acc: 50.88% | Val loss: 1.0093 | Val acc: 46.05% | LR: 0.000024
Epoch: 033 | Train loss: 0.9965 | Train acc: 50.70% | Val loss: 1.0063 | Val acc: 46.04% | LR: 0.000024
Epoch: 034 | Train loss: 0.9990 | Train acc: 50.24% | Val loss: 1.0060 | Val acc: 46.03% | LR: 0.000024
Epoch: 035 | Train loss: 1.0095 | Train acc: 50.41% | Val loss: 1.0062 | Val acc: 45.99% | LR: 0.000023
Epoch: 036 | Train loss: 0.9960 | Train acc: 50.86% | Val loss: 1.0071 | Val acc: 46.05% | LR: 0.000023
Epoch: 037 | Train loss: 0.9980 | Train acc: 50.32% | Val loss: 1.0144 | Val acc: 46.01% | LR: 0.000023
Epoch: 038 | Train loss: 0.9987 | Train acc: 50.77% | Val loss: 1.0063 | Val acc: 46.03% | LR: 0.000023
Epoch: 039 | Train loss: 0.9991 | Train acc: 50.23% | Val loss: 1.0061 | Val acc: 46.09% | LR: 0.000023
Epoch: 040 | Train loss: 0.9963 | Train acc: 50.76% | Val loss: 1.0068 | Val acc: 45.97% | LR: 0.000022
Epoch: 041 | Train loss: 0.9971 | Train acc: 50.49% | Val loss: 1.0072 | Val acc: 46.01% | LR: 0.000022
Epoch: 042 | Train loss: 0.9982 | Train acc: 50.33% | Val loss: 1.0068 | Val acc: 46.07% | LR: 0.000022
Epoch: 043 | Train loss: 0.9963 | Train acc: 50.78% | Val loss: 1.0071 | Val acc: 46.03% | LR: 0.000022
Epoch: 044 | Train loss: 0.9952 | Train acc: 50.94% | Val loss: 1.0085 | Val acc: 45.99% | LR: 0.000022
Epoch: 045 | Train loss: 0.9962 | Train acc: 50.57% | Val loss: 1.0071 | Val acc: 45.99% | LR: 0.000021
Epoch: 046 | Train loss: 0.9982 | Train acc: 50.32% | Val loss: 1.0080 | Val acc: 46.05% | LR: 0.000021
Epoch: 047 | Train loss: 0.9971 | Train acc: 50.57% | Val loss: 1.0083 | Val acc: 46.03% | LR: 0.000021
Epoch: 048 | Train loss: 0.9989 | Train acc: 50.14% | Val loss: 1.0216 | Val acc: 46.05% | LR: 0.000021
Epoch: 049 | Train loss: 0.9985 | Train acc: 50.32% | Val loss: 1.0071 | Val acc: 46.03% | LR: 0.000020
Epoch: 050 | Train loss: 0.9932 | Train acc: 51.13% | Val loss: 1.0071 | Val acc: 46.09% | LR: 0.000020
Epoch: 051 | Train loss: 0.9944 | Train acc: 50.94% | Val loss: 1.0071 | Val acc: 45.95% | LR: 0.000020
Epoch: 052 | Train loss: 0.9981 | Train acc: 50.22% | Val loss: 1.0237 | Val acc: 46.07% | LR: 0.000020
Epoch: 053 | Train loss: 0.9982 | Train acc: 50.32% | Val loss: 1.0063 | Val acc: 46.13% | LR: 0.000019
Epoch: 054 | Train loss: 0.9960 | Train acc: 50.42% | Val loss: 1.0068 | Val acc: 46.01% | LR: 0.000019
Epoch: 055 | Train loss: 0.9942 | Train acc: 50.78% | Val loss: 1.0101 | Val acc: 46.03% | LR: 0.000019
Epoch: 056 | Train loss: 0.9953 | Train acc: 50.58% | Val loss: 1.0200 | Val acc: 46.05% | LR: 0.000019
Epoch: 057 | Train loss: 0.9962 | Train acc: 50.50% | Val loss: 1.0067 | Val acc: 46.11% | LR: 0.000018
Epoch: 058 | Train loss: 0.9982 | Train acc: 50.16% | Val loss: 1.0068 | Val acc: 46.15% | LR: 0.000018
Epoch: 059 | Train loss: 0.9967 | Train acc: 50.34% | Val loss: 1.0072 | Val acc: 46.01% | LR: 0.000018
Epoch: 060 | Train loss: 0.9996 | Train acc: 50.08% | Val loss: 1.0080 | Val acc: 46.01% | LR: 0.000018

[I 2025-09-23 18:21:10,785] Trial 108 finished with value: 0.4609106779098511 and parameters: {'lr': 2.6882511802649324e-05, 'hidden_size': 72, 'dropout': 0.27050280309804703, 'weight_decay': 1.357335117775358e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0032 | Train acc: 48.83% | Val loss: 0.9970 | Val acc: 53.91% | LR: 0.000041
Epoch: 001 | Train loss: 1.0016 | Train acc: 49.32% | Val loss: 0.9971 | Val acc: 54.07% | LR: 0.000041
Epoch: 002 | Train loss: 1.0006 | Train acc: 49.88% | Val loss: 0.9969 | Val acc: 54.01% | LR: 0.000041
Epoch: 003 | Train loss: 1.0013 | Train acc: 49.33% | Val loss: 0.9967 | Val acc: 54.03% | LR: 0.000041
Epoch: 004 | Train loss: 1.0007 | Train acc: 49.49% | Val loss: 0.9968 | Val acc: 54.15% | LR: 0.000041
Epoch: 005 | Train loss: 1.0002 | Train acc: 49.72% | Val loss: 0.9970 | Val acc: 54.29% | LR: 0.000041
Epoch: 006 | Train loss: 0.9996 | Train acc: 50.15% | Val loss: 0.9969 | Val acc: 54.13% | LR: 0.000041
Epoch: 007 | Train loss: 0.9991 | Train acc: 50.61% | Val loss: 0.9969 | Val acc: 53.80% | LR: 0.000041
Epoch: 008 | Train loss: 0.9990 | Train acc: 50.64% | Val loss: 0.9969 | Val acc: 53.56% | LR: 0.000041
Epoch: 009 | Train loss: 0.9989 | Train acc: 50.62% | Val loss: 0.9969 | Val acc: 53.03% | LR: 0.000040
Epoch: 010 | Train loss: 0.9977 | Train acc: 51.23% | Val loss: 0.9966 | Val acc: 53.09% | LR: 0.000040
Epoch: 011 | Train loss: 0.9990 | Train acc: 50.59% | Val loss: 0.9967 | Val acc: 52.92% | LR: 0.000040
Epoch: 012 | Train loss: 0.9983 | Train acc: 50.79% | Val loss: 0.9966 | Val acc: 53.11% | LR: 0.000040
Epoch: 013 | Train loss: 0.9973 | Train acc: 51.21% | Val loss: 0.9965 | Val acc: 52.80% | LR: 0.000040
Epoch: 014 | Train loss: 0.9965 | Train acc: 51.41% | Val loss: 0.9964 | Val acc: 52.47% | LR: 0.000040
Epoch: 015 | Train loss: 0.9974 | Train acc: 50.87% | Val loss: 0.9963 | Val acc: 52.40% | LR: 0.000040
Epoch: 016 | Train loss: 0.9966 | Train acc: 50.98% | Val loss: 0.9961 | Val acc: 52.25% | LR: 0.000040
Epoch: 017 | Train loss: 0.9961 | Train acc: 51.07% | Val loss: 0.9953 | Val acc: 52.45% | LR: 0.000040
Epoch: 018 | Train loss: 0.9968 | Train acc: 50.98% | Val loss: 0.9951 | Val acc: 52.27% | LR: 0.000039
Epoch: 019 | Train loss: 0.9966 | Train acc: 50.81% | Val loss: 0.9949 | Val acc: 52.21% | LR: 0.000039
Epoch: 020 | Train loss: 0.9946 | Train acc: 51.43% | Val loss: 0.9948 | Val acc: 52.27% | LR: 0.000039
Epoch: 021 | Train loss: 0.9956 | Train acc: 51.07% | Val loss: 0.9946 | Val acc: 51.97% | LR: 0.000039
Epoch: 022 | Train loss: 0.9945 | Train acc: 51.26% | Val loss: 0.9943 | Val acc: 51.75% | LR: 0.000039
Epoch: 023 | Train loss: 0.9945 | Train acc: 51.16% | Val loss: 0.9939 | Val acc: 51.81% | LR: 0.000038
Epoch: 024 | Train loss: 0.9938 | Train acc: 51.16% | Val loss: 0.9937 | Val acc: 51.59% | LR: 0.000038
Epoch: 025 | Train loss: 0.9939 | Train acc: 50.79% | Val loss: 0.9933 | Val acc: 51.61% | LR: 0.000038
Epoch: 026 | Train loss: 0.9900 | Train acc: 51.54% | Val loss: 0.9933 | Val acc: 51.54% | LR: 0.000038
Epoch: 027 | Train loss: 0.9922 | Train acc: 51.03% | Val loss: 0.9933 | Val acc: 51.27% | LR: 0.000038
Epoch: 028 | Train loss: 0.9894 | Train acc: 51.17% | Val loss: 0.9937 | Val acc: 51.05% | LR: 0.000037
Epoch: 029 | Train loss: 0.9873 | Train acc: 51.63% | Val loss: 0.9931 | Val acc: 51.03% | LR: 0.000037
Epoch: 030 | Train loss: 0.9873 | Train acc: 51.19% | Val loss: 0.9927 | Val acc: 51.03% | LR: 0.000037
Epoch: 031 | Train loss: 0.9862 | Train acc: 51.20% | Val loss: 0.9921 | Val acc: 51.01% | LR: 0.000037
Epoch: 032 | Train loss: 0.9936 | Train acc: 50.57% | Val loss: 0.9912 | Val acc: 51.09% | LR: 0.000036
Epoch: 033 | Train loss: 0.9890 | Train acc: 50.90% | Val loss: 0.9905 | Val acc: 51.03% | LR: 0.000036
Epoch: 034 | Train loss: 0.9883 | Train acc: 50.90% | Val loss: 0.9904 | Val acc: 50.97% | LR: 0.000036
Epoch: 035 | Train loss: 0.9869 | Train acc: 51.16% | Val loss: 0.9902 | Val acc: 50.97% | LR: 0.000036
Epoch: 036 | Train loss: 0.9879 | Train acc: 51.09% | Val loss: 0.9896 | Val acc: 51.01% | LR: 0.000035
Epoch: 037 | Train loss: 0.9884 | Train acc: 50.92% | Val loss: 0.9884 | Val acc: 51.11% | LR: 0.000035
Epoch: 038 | Train loss: 0.9892 | Train acc: 50.56% | Val loss: 0.9875 | Val acc: 51.07% | LR: 0.000035
Epoch: 039 | Train loss: 0.9859 | Train acc: 51.20% | Val loss: 0.9860 | Val acc: 51.03% | LR: 0.000034
Epoch: 040 | Train loss: 0.9802 | Train acc: 51.74% | Val loss: 0.9860 | Val acc: 50.99% | LR: 0.000034
Epoch: 041 | Train loss: 0.9840 | Train acc: 51.37% | Val loss: 0.9852 | Val acc: 50.99% | LR: 0.000034
Epoch: 042 | Train loss: 0.9867 | Train acc: 50.49% | Val loss: 0.9849 | Val acc: 51.09% | LR: 0.000033
Epoch: 043 | Train loss: 0.9883 | Train acc: 50.73% | Val loss: 0.9853 | Val acc: 51.17% | LR: 0.000033
Epoch: 044 | Train loss: 0.9869 | Train acc: 50.84% | Val loss: 0.9855 | Val acc: 51.13% | LR: 0.000033
Epoch: 045 | Train loss: 0.9832 | Train acc: 51.30% | Val loss: 0.9859 | Val acc: 51.09% | LR: 0.000032
Epoch: 046 | Train loss: 0.9826 | Train acc: 51.21% | Val loss: 0.9865 | Val acc: 51.09% | LR: 0.000032
Epoch: 047 | Train loss: 0.9838 | Train acc: 51.21% | Val loss: 0.9865 | Val acc: 51.11% | LR: 0.000032
Epoch: 048 | Train loss: 0.9841 | Train acc: 51.18% | Val loss: 0.9867 | Val acc: 51.11% | LR: 0.000031
Epoch: 049 | Train loss: 0.9867 | Train acc: 50.72% | Val loss: 0.9873 | Val acc: 50.98% | LR: 0.000031
Epoch: 050 | Train loss: 0.9863 | Train acc: 50.73% | Val loss: 0.9869 | Val acc: 51.03% | LR: 0.000031
Epoch: 051 | Train loss: 0.9880 | Train acc: 50.82% | Val loss: 0.9871 | Val acc: 51.03% | LR: 0.000030
Epoch: 052 | Train loss: 0.9831 | Train acc: 51.08% | Val loss: 0.9871 | Val acc: 51.05% | LR: 0.000030
Epoch: 053 | Train loss: 0.9842 | Train acc: 50.84% | Val loss: 0.9875 | Val acc: 50.95% | LR: 0.000029
Epoch: 054 | Train loss: 0.9822 | Train acc: 51.27% | Val loss: 0.9880 | Val acc: 50.93% | LR: 0.000029

[I 2025-09-23 18:21:56,465] Trial 109 finished with value: 0.5084545373916626 and parameters: {'lr': 4.093340092237613e-05, 'hidden_size': 68, 'dropout': 0.24816953237714803, 'weight_decay': 1.7030351803701603e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0005 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.05% | LR: 0.000012
Epoch: 001 | Train loss: 1.0010 | Train acc: 49.72% | Val loss: 0.9917 | Val acc: 54.11% | LR: 0.000012
Epoch: 002 | Train loss: 0.9999 | Train acc: 50.23% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000012
Epoch: 003 | Train loss: 0.9992 | Train acc: 50.53% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000012
Epoch: 004 | Train loss: 0.9997 | Train acc: 50.18% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000012
Epoch: 005 | Train loss: 0.9977 | Train acc: 50.87% | Val loss: 0.9918 | Val acc: 54.17% | LR: 0.000012
Epoch: 006 | Train loss: 0.9984 | Train acc: 50.52% | Val loss: 0.9918 | Val acc: 54.20% | LR: 0.000012
Epoch: 007 | Train loss: 0.9994 | Train acc: 49.98% | Val loss: 0.9919 | Val acc: 54.24% | LR: 0.000012
Epoch: 008 | Train loss: 0.9999 | Train acc: 49.72% | Val loss: 0.9920 | Val acc: 54.34% | LR: 0.000012
Epoch: 009 | Train loss: 0.9980 | Train acc: 50.60% | Val loss: 0.9920 | Val acc: 54.26% | LR: 0.000012
Epoch: 010 | Train loss: 0.9976 | Train acc: 50.78% | Val loss: 0.9921 | Val acc: 54.26% | LR: 0.000012
Epoch: 011 | Train loss: 0.9973 | Train acc: 50.87% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000012
Epoch: 012 | Train loss: 0.9976 | Train acc: 50.68% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000012
Epoch: 013 | Train loss: 0.9972 | Train acc: 50.43% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000012
Epoch: 014 | Train loss: 0.9994 | Train acc: 50.43% | Val loss: 0.9919 | Val acc: 54.24% | LR: 0.000012
Epoch: 015 | Train loss: 1.0004 | Train acc: 50.14% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000012
Epoch: 016 | Train loss: 1.0113 | Train acc: 50.66% | Val loss: 0.9919 | Val acc: 54.28% | LR: 0.000012
Epoch: 017 | Train loss: 0.9962 | Train acc: 50.52% | Val loss: 0.9919 | Val acc: 54.32% | LR: 0.000012
Epoch: 018 | Train loss: 0.9956 | Train acc: 50.25% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000012
Epoch: 019 | Train loss: 0.9975 | Train acc: 50.33% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000012
Epoch: 020 | Train loss: 1.0124 | Train acc: 51.11% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000012
Epoch: 021 | Train loss: 0.9955 | Train acc: 50.57% | Val loss: 0.9918 | Val acc: 54.34% | LR: 0.000012
Epoch: 022 | Train loss: 1.0024 | Train acc: 50.66% | Val loss: 0.9918 | Val acc: 54.34% | LR: 0.000012
Epoch: 023 | Train loss: 0.9989 | Train acc: 50.26% | Val loss: 0.9918 | Val acc: 54.36% | LR: 0.000012
Epoch: 024 | Train loss: 0.9988 | Train acc: 50.39% | Val loss: 0.9919 | Val acc: 54.38% | LR: 0.000012
Epoch: 025 | Train loss: 1.0001 | Train acc: 49.97% | Val loss: 0.9918 | Val acc: 54.44% | LR: 0.000012
Epoch: 026 | Train loss: 0.9990 | Train acc: 50.33% | Val loss: 0.9917 | Val acc: 54.38% | LR: 0.000012
Epoch: 027 | Train loss: 0.9974 | Train acc: 50.79% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000012
Epoch: 028 | Train loss: 0.9967 | Train acc: 50.77% | Val loss: 0.9917 | Val acc: 54.30% | LR: 0.000011
Epoch: 029 | Train loss: 0.9980 | Train acc: 50.75% | Val loss: 0.9941 | Val acc: 54.26% | LR: 0.000011
Epoch: 030 | Train loss: 0.9983 | Train acc: 50.40% | Val loss: 0.9918 | Val acc: 54.24% | LR: 0.000011
Epoch: 031 | Train loss: 0.9982 | Train acc: 50.35% | Val loss: 0.9917 | Val acc: 54.16% | LR: 0.000011
Epoch: 032 | Train loss: 0.9971 | Train acc: 51.08% | Val loss: 0.9916 | Val acc: 54.38% | LR: 0.000011
Epoch: 033 | Train loss: 0.9997 | Train acc: 49.93% | Val loss: 0.9916 | Val acc: 54.42% | LR: 0.000011
Epoch: 034 | Train loss: 0.9967 | Train acc: 50.91% | Val loss: 0.9917 | Val acc: 54.42% | LR: 0.000011
Epoch: 035 | Train loss: 0.9983 | Train acc: 50.36% | Val loss: 0.9919 | Val acc: 54.27% | LR: 0.000011
Epoch: 036 | Train loss: 0.9979 | Train acc: 50.49% | Val loss: 0.9917 | Val acc: 54.33% | LR: 0.000011
Epoch: 037 | Train loss: 0.9985 | Train acc: 50.39% | Val loss: 0.9916 | Val acc: 54.27% | LR: 0.000011
Epoch: 038 | Train loss: 0.9986 | Train acc: 50.31% | Val loss: 0.9916 | Val acc: 54.25% | LR: 0.000011
Epoch: 039 | Train loss: 0.9972 | Train acc: 50.85% | Val loss: 0.9927 | Val acc: 54.39% | LR: 0.000011
Epoch: 040 | Train loss: 0.9974 | Train acc: 50.77% | Val loss: 0.9918 | Val acc: 54.43% | LR: 0.000010
Epoch: 041 | Train loss: 0.9979 | Train acc: 50.69% | Val loss: 0.9916 | Val acc: 54.39% | LR: 0.000010
Epoch: 042 | Train loss: 0.9986 | Train acc: 50.36% | Val loss: 0.9915 | Val acc: 54.39% | LR: 0.000010
Epoch: 043 | Train loss: 0.9981 | Train acc: 50.46% | Val loss: 0.9915 | Val acc: 54.41% | LR: 0.000010
Epoch: 044 | Train loss: 0.9987 | Train acc: 50.29% | Val loss: 0.9920 | Val acc: 54.46% | LR: 0.000010
Epoch: 045 | Train loss: 0.9978 | Train acc: 50.64% | Val loss: 0.9932 | Val acc: 54.42% | LR: 0.000010
Epoch: 046 | Train loss: 0.9964 | Train acc: 50.99% | Val loss: 0.9916 | Val acc: 54.48% | LR: 0.000010
Epoch: 047 | Train loss: 0.9985 | Train acc: 50.19% | Val loss: 0.9916 | Val acc: 54.48% | LR: 0.000010
Epoch: 048 | Train loss: 0.9977 | Train acc: 50.63% | Val loss: 0.9916 | Val acc: 54.52% | LR: 0.000010
Epoch: 049 | Train loss: 1.0082 | Train acc: 50.54% | Val loss: 0.9916 | Val acc: 54.42% | LR: 0.000010
Epoch: 050 | Train loss: 0.9985 | Train acc: 50.38% | Val loss: 0.9916 | Val acc: 54.39% | LR: 0.000010
Epoch: 051 | Train loss: 0.9972 | Train acc: 50.56% | Val loss: 0.9916 | Val acc: 54.37% | LR: 0.000009
Epoch: 052 | Train loss: 0.9983 | Train acc: 50.51% | Val loss: 0.9916 | Val acc: 54.35% | LR: 0.000009
Epoch: 053 | Train loss: 0.9980 | Train acc: 50.36% | Val loss: 0.9917 | Val acc: 54.37% | LR: 0.000009
Epoch: 054 | Train loss: 0.9970 | Train acc: 50.78% | Val loss: 0.9916 | Val acc: 54.41% | LR: 0.000009
Epoch: 055 | Train loss: 0.9966 | Train acc: 50.79% | Val loss: 0.9917 | Val acc: 54.45% | LR: 0.000009
Epoch: 056 | Train loss: 1.0246 | Train acc: 50.97% | Val loss: 0.9917 | Val acc: 54.47% | LR: 0.000009
Epoch: 057 | Train loss: 0.9974 | Train acc: 50.44% | Val loss: 0.9917 | Val acc: 54.48% | LR: 0.000009
Epoch: 058 | Train loss: 0.9983 | Train acc: 50.53% | Val loss: 0.9917 | Val acc: 54.54% | LR: 0.000009
Epoch: 059 | Train loss: 0.9977 | Train acc: 50.98% | Val loss: 0.9917 | Val acc: 54.46% | LR: 0.000009
Epoch: 060 | Train loss: 0.9973 | Train acc: 50.71% | Val loss: 0.9917 | Val acc: 54.56% | LR: 0.000008
Epoch: 061 | Train loss: 0.9978 | Train acc: 50.43% | Val loss: 0.9918 | Val acc: 54.54% | LR: 0.000008
Epoch: 062 | Train loss: 0.9983 | Train acc: 50.55% | Val loss: 0.9917 | Val acc: 54.64% | LR: 0.000008
Epoch: 063 | Train loss: 1.0219 | Train acc: 50.35% | Val loss: 0.9917 | Val acc: 54.54% | LR: 0.000008
Epoch: 064 | Train loss: 1.0013 | Train acc: 50.46% | Val loss: 0.9917 | Val acc: 54.52% | LR: 0.000008
Epoch: 065 | Train loss: 0.9962 | Train acc: 50.85% | Val loss: 0.9917 | Val acc: 54.54% | LR: 0.000008
Epoch: 066 | Train loss: 1.0169 | Train acc: 50.18% | Val loss: 0.9917 | Val acc: 54.58% | LR: 0.000008
Epoch: 067 | Train loss: 1.0119 | Train acc: 50.78% | Val loss: 0.9917 | Val acc: 54.56% | LR: 0.000008
Epoch: 068 | Train loss: 1.0660 | Train acc: 50.50% | Val loss: 0.9917 | Val acc: 54.58% | LR: 0.000007
Epoch: 069 | Train loss: 1.0664 | Train acc: 50.55% | Val loss: 0.9917 | Val acc: 54.56% | LR: 0.000007
Epoch: 070 | Train loss: 0.9983 | Train acc: 50.93% | Val loss: 0.9917 | Val acc: 54.58% | LR: 0.000007
Epoch: 071 | Train loss: 1.0024 | Train acc: 50.74% | Val loss: 0.9917 | Val acc: 54.58% | LR: 0.000007
Epoch: 072 | Train loss: 0.9937 | Train acc: 50.69% | Val loss: 0.9917 | Val acc: 54.56% | LR: 0.000007
Epoch: 073 | Train loss: 0.9990 | Train acc: 49.99% | Val loss: 0.9917 | Val acc: 54.58% | LR: 0.000007
Epoch: 074 | Train loss: 0.9945 | Train acc: 51.30% | Val loss: 0.9917 | Val acc: 54.58% | LR: 0.000007
Epoch: 075 | Train loss: 0.9928 | Train acc: 51.04% | Val loss: 0.9916 | Val acc: 54.52% | LR: 0.000007
Epoch: 076 | Train loss: 0.9978 | Train acc: 50.30% | Val loss: 0.9918 | Val acc: 54.50% | LR: 0.000007
Epoch: 077 | Train loss: 1.0981 | Train acc: 50.25% | Val loss: 0.9917 | Val acc: 54.52% | LR: 0.000006
Epoch: 078 | Train loss: 0.9994 | Train acc: 50.63% | Val loss: 0.9917 | Val acc: 54.50% | LR: 0.000006
Epoch: 079 | Train loss: 0.9990 | Train acc: 50.63% | Val loss: 0.9917 | Val acc: 54.50% | LR: 0.000006
Epoch: 080 | Train loss: 0.9971 | Train acc: 50.99% | Val loss: 0.9917 | Val acc: 54.50% | LR: 0.000006
Epoch: 081 | Train loss: 0.9955 | Train acc: 50.63% | Val loss: 0.9917 | Val acc: 54.50% | LR: 0.000006
Epoch: 082 | Train loss: 0.9932 | Train acc: 51.41% | Val loss: 0.9917 | Val acc: 54.44% | LR: 0.000006
Epoch: 083 | Train loss: 0.9983 | Train acc: 50.24% | Val loss: 0.9917 | Val acc: 54.50% | LR: 0.000006
Epoch: 084 | Train loss: 0.9959 | Train acc: 50.71% | Val loss: 0.9917 | Val acc: 54.58% | LR: 0.000006
Epoch: 085 | Train loss: 0.9986 | Train acc: 50.30% | Val loss: 0.9917 | Val acc: 54.56% | LR: 0.000005
Epoch: 086 | Train loss: 0.9951 | Train acc: 50.65% | Val loss: 0.9917 | Val acc: 54.56% | LR: 0.000005
Epoch: 087 | Train loss: 0.9952 | Train acc: 50.65% | Val loss: 0.9917 | Val acc: 54.56% | LR: 0.000005
Epoch: 088 | Train loss: 0.9972 | Train acc: 50.63% | Val loss: 0.9917 | Val acc: 54.56% | LR: 0.000005
Epoch: 089 | Train loss: 0.9961 | Train acc: 50.54% | Val loss: 0.9917 | Val acc: 54.56% | LR: 0.000005
Epoch: 090 | Train loss: 0.9977 | Train acc: 50.69% | Val loss: 0.9917 | Val acc: 54.42% | LR: 0.000005
Epoch: 091 | Train loss: 1.0001 | Train acc: 50.87% | Val loss: 0.9917 | Val acc: 54.40% | LR: 0.000005
Epoch: 092 | Train loss: 1.0104 | Train acc: 50.51% | Val loss: 0.9917 | Val acc: 54.42% | LR: 0.000005
Epoch: 093 | Train loss: 0.9940 | Train acc: 50.88% | Val loss: 0.9917 | Val acc: 54.42% | LR: 0.000005
Epoch: 094 | Train loss: 0.9930 | Train acc: 51.06% | Val loss: 0.9917 | Val acc: 54.42% | LR: 0.000004
Epoch: 095 | Train loss: 0.9958 | Train acc: 50.71% | Val loss: 0.9917 | Val acc: 54.42% | LR: 0.000004
Epoch: 096 | Train loss: 0.9926 | Train acc: 50.90% | Val loss: 0.9917 | Val acc: 54.42% | LR: 0.000004
Epoch: 097 | Train loss: 0.9948 | Train acc: 50.63% | Val loss: 0.9917 | Val acc: 54.42% | LR: 0.000004
Epoch: 098 | Train loss: 0.9950 | Train acc: 50.93% | Val loss: 0.9917 | Val acc: 54.38% | LR: 0.000004
Epoch: 099 | Train loss: 0.9946 | Train acc: 51.00% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000004
Epoch: 100 | Train loss: 0.9942 | Train acc: 50.46% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000004
Epoch: 101 | Train loss: 0.9954 | Train acc: 50.84% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000004
Epoch: 102 | Train loss: 0.9943 | Train acc: 51.03% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000004
Epoch: 103 | Train loss: 0.9941 | Train acc: 50.81% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000003
Epoch: 104 | Train loss: 0.9960 | Train acc: 50.55% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000003
Epoch: 105 | Train loss: 0.9933 | Train acc: 51.10% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000003
Epoch: 106 | Train loss: 0.9953 | Train acc: 50.83% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000003
Epoch: 107 | Train loss: 0.9943 | Train acc: 50.92% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000003
Epoch: 108 | Train loss: 0.9971 | Train acc: 50.21% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000003
Epoch: 109 | Train loss: 0.9988 | Train acc: 50.83% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000003
Epoch: 110 | Train loss: 0.9957 | Train acc: 50.57% | Val loss: 0.9917 | Val acc: 54.32% | LR: 0.000003
Epoch: 111 | Train loss: 0.9949 | Train acc: 50.87% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000003

[I 2025-09-23 18:23:18,005] Trial 110 finished with value: 0.5434374213218689 and parameters: {'lr': 1.2485318802764778e-05, 'hidden_size': 64, 'dropout': 0.20260309108792682, 'weight_decay': 2.2162546268424974e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0000 | Train acc: 49.79% | Val loss: 1.0042 | Val acc: 45.95% | LR: 0.000013
Epoch: 001 | Train loss: 0.9995 | Train acc: 50.35% | Val loss: 1.0042 | Val acc: 45.91% | LR: 0.000013
Epoch: 002 | Train loss: 0.9996 | Train acc: 49.93% | Val loss: 1.0042 | Val acc: 45.95% | LR: 0.000013
Epoch: 003 | Train loss: 0.9996 | Train acc: 49.92% | Val loss: 1.0042 | Val acc: 45.95% | LR: 0.000013
Epoch: 004 | Train loss: 0.9994 | Train acc: 50.33% | Val loss: 1.0042 | Val acc: 45.95% | LR: 0.000013
Epoch: 005 | Train loss: 0.9993 | Train acc: 50.42% | Val loss: 1.0053 | Val acc: 45.95% | LR: 0.000013
Epoch: 006 | Train loss: 0.9991 | Train acc: 50.42% | Val loss: 1.0045 | Val acc: 45.95% | LR: 0.000013
Epoch: 007 | Train loss: 0.9983 | Train acc: 50.87% | Val loss: 1.0045 | Val acc: 45.95% | LR: 0.000012
Epoch: 008 | Train loss: 0.9990 | Train acc: 50.65% | Val loss: 1.0045 | Val acc: 46.03% | LR: 0.000012
Epoch: 009 | Train loss: 0.9991 | Train acc: 50.59% | Val loss: 1.0045 | Val acc: 46.11% | LR: 0.000012
Epoch: 010 | Train loss: 0.9988 | Train acc: 50.59% | Val loss: 1.0045 | Val acc: 46.19% | LR: 0.000012
Epoch: 011 | Train loss: 0.9987 | Train acc: 50.68% | Val loss: 1.0045 | Val acc: 46.19% | LR: 0.000012
Epoch: 012 | Train loss: 0.9984 | Train acc: 50.68% | Val loss: 1.0045 | Val acc: 46.13% | LR: 0.000012
Epoch: 013 | Train loss: 0.9980 | Train acc: 50.77% | Val loss: 1.0045 | Val acc: 46.15% | LR: 0.000012
Epoch: 014 | Train loss: 1.0002 | Train acc: 49.89% | Val loss: 1.0046 | Val acc: 46.17% | LR: 0.000012
Epoch: 015 | Train loss: 0.9976 | Train acc: 51.03% | Val loss: 1.0045 | Val acc: 46.27% | LR: 0.000012
Epoch: 016 | Train loss: 0.9983 | Train acc: 50.59% | Val loss: 1.0046 | Val acc: 46.25% | LR: 0.000012
Epoch: 017 | Train loss: 0.9992 | Train acc: 50.32% | Val loss: 1.0046 | Val acc: 46.40% | LR: 0.000012
Epoch: 018 | Train loss: 0.9984 | Train acc: 50.61% | Val loss: 1.0046 | Val acc: 46.42% | LR: 0.000012
Epoch: 019 | Train loss: 0.9996 | Train acc: 50.17% | Val loss: 1.0046 | Val acc: 46.38% | LR: 0.000012
Epoch: 020 | Train loss: 0.9985 | Train acc: 50.63% | Val loss: 1.0046 | Val acc: 46.42% | LR: 0.000012
Epoch: 021 | Train loss: 0.9975 | Train acc: 50.91% | Val loss: 1.0046 | Val acc: 46.42% | LR: 0.000012
Epoch: 022 | Train loss: 0.9979 | Train acc: 50.72% | Val loss: 1.0046 | Val acc: 46.33% | LR: 0.000012
Epoch: 023 | Train loss: 0.9978 | Train acc: 50.63% | Val loss: 1.0046 | Val acc: 46.40% | LR: 0.000012
Epoch: 024 | Train loss: 0.9983 | Train acc: 50.52% | Val loss: 1.0046 | Val acc: 46.34% | LR: 0.000012
Epoch: 025 | Train loss: 0.9986 | Train acc: 50.50% | Val loss: 1.0047 | Val acc: 46.36% | LR: 0.000012
Epoch: 026 | Train loss: 0.9989 | Train acc: 50.36% | Val loss: 1.0047 | Val acc: 46.42% | LR: 0.000012
Epoch: 027 | Train loss: 0.9965 | Train acc: 50.91% | Val loss: 1.0047 | Val acc: 46.48% | LR: 0.000012
Epoch: 028 | Train loss: 0.9977 | Train acc: 50.73% | Val loss: 1.0046 | Val acc: 46.42% | LR: 0.000012
Epoch: 029 | Train loss: 0.9982 | Train acc: 50.50% | Val loss: 1.0047 | Val acc: 46.42% | LR: 0.000011
Epoch: 030 | Train loss: 0.9983 | Train acc: 50.50% | Val loss: 1.0048 | Val acc: 46.44% | LR: 0.000011
Epoch: 031 | Train loss: 0.9958 | Train acc: 51.15% | Val loss: 1.0048 | Val acc: 46.66% | LR: 0.000011
Epoch: 032 | Train loss: 0.9974 | Train acc: 50.70% | Val loss: 1.0048 | Val acc: 46.56% | LR: 0.000011
Epoch: 033 | Train loss: 0.9980 | Train acc: 50.42% | Val loss: 1.0048 | Val acc: 46.58% | LR: 0.000011
Epoch: 034 | Train loss: 0.9977 | Train acc: 50.89% | Val loss: 1.0047 | Val acc: 46.66% | LR: 0.000011
Epoch: 035 | Train loss: 0.9975 | Train acc: 50.64% | Val loss: 1.0047 | Val acc: 46.62% | LR: 0.000011
Epoch: 036 | Train loss: 0.9987 | Train acc: 50.38% | Val loss: 1.0047 | Val acc: 46.66% | LR: 0.000011
Epoch: 037 | Train loss: 0.9983 | Train acc: 50.45% | Val loss: 1.0046 | Val acc: 46.72% | LR: 0.000011
Epoch: 038 | Train loss: 0.9966 | Train acc: 50.81% | Val loss: 1.0046 | Val acc: 46.60% | LR: 0.000011
Epoch: 039 | Train loss: 0.9947 | Train acc: 51.09% | Val loss: 1.0046 | Val acc: 46.83% | LR: 0.000011
Epoch: 040 | Train loss: 0.9966 | Train acc: 50.93% | Val loss: 1.0046 | Val acc: 46.89% | LR: 0.000011
Epoch: 041 | Train loss: 0.9964 | Train acc: 51.04% | Val loss: 1.0047 | Val acc: 46.87% | LR: 0.000010
Epoch: 042 | Train loss: 0.9964 | Train acc: 50.86% | Val loss: 1.0047 | Val acc: 46.87% | LR: 0.000010
Epoch: 043 | Train loss: 0.9970 | Train acc: 50.68% | Val loss: 1.0048 | Val acc: 46.76% | LR: 0.000010
Epoch: 044 | Train loss: 0.9951 | Train acc: 51.14% | Val loss: 1.0048 | Val acc: 46.70% | LR: 0.000010
Epoch: 045 | Train loss: 0.9955 | Train acc: 50.97% | Val loss: 1.0049 | Val acc: 46.70% | LR: 0.000010
Epoch: 046 | Train loss: 0.9955 | Train acc: 50.98% | Val loss: 1.0050 | Val acc: 46.72% | LR: 0.000010
Epoch: 047 | Train loss: 0.9979 | Train acc: 50.36% | Val loss: 1.0068 | Val acc: 46.66% | LR: 0.000010
Epoch: 048 | Train loss: 0.9978 | Train acc: 50.36% | Val loss: 1.0045 | Val acc: 46.70% | LR: 0.000010
Epoch: 049 | Train loss: 0.9957 | Train acc: 51.00% | Val loss: 1.0045 | Val acc: 46.80% | LR: 0.000010
Epoch: 050 | Train loss: 0.9953 | Train acc: 50.98% | Val loss: 1.0048 | Val acc: 46.74% | LR: 0.000010
Epoch: 051 | Train loss: 0.9981 | Train acc: 50.47% | Val loss: 1.0050 | Val acc: 46.86% | LR: 0.000009
Epoch: 052 | Train loss: 0.9955 | Train acc: 50.93% | Val loss: 1.0063 | Val acc: 46.91% | LR: 0.000009
Epoch: 053 | Train loss: 0.9973 | Train acc: 50.67% | Val loss: 1.0041 | Val acc: 46.92% | LR: 0.000009
Epoch: 054 | Train loss: 0.9952 | Train acc: 51.04% | Val loss: 1.0044 | Val acc: 46.94% | LR: 0.000009
Epoch: 055 | Train loss: 0.9945 | Train acc: 51.05% | Val loss: 1.0043 | Val acc: 47.00% | LR: 0.000009
Epoch: 056 | Train loss: 0.9973 | Train acc: 50.62% | Val loss: 1.0049 | Val acc: 46.98% | LR: 0.000009
Epoch: 057 | Train loss: 0.9981 | Train acc: 50.45% | Val loss: 1.0044 | Val acc: 47.09% | LR: 0.000009
Epoch: 058 | Train loss: 0.9973 | Train acc: 50.68% | Val loss: 1.0044 | Val acc: 47.11% | LR: 0.000009
Epoch: 059 | Train loss: 0.9927 | Train acc: 51.48% | Val loss: 1.0043 | Val acc: 47.02% | LR: 0.000009
Epoch: 060 | Train loss: 1.0007 | Train acc: 50.13% | Val loss: 1.0044 | Val acc: 47.08% | LR: 0.000008
Epoch: 061 | Train loss: 0.9936 | Train acc: 51.20% | Val loss: 1.0056 | Val acc: 47.02% | LR: 0.000008
Epoch: 062 | Train loss: 0.9929 | Train acc: 51.41% | Val loss: 1.0042 | Val acc: 47.08% | LR: 0.000008
Epoch: 063 | Train loss: 0.9943 | Train acc: 51.21% | Val loss: 1.0042 | Val acc: 47.04% | LR: 0.000008
Epoch: 064 | Train loss: 0.9953 | Train acc: 50.84% | Val loss: 1.0042 | Val acc: 46.92% | LR: 0.000008
Epoch: 065 | Train loss: 0.9948 | Train acc: 50.94% | Val loss: 1.0042 | Val acc: 46.88% | LR: 0.000008
Epoch: 066 | Train loss: 0.9954 | Train acc: 50.76% | Val loss: 1.0039 | Val acc: 47.04% | LR: 0.000008
Epoch: 067 | Train loss: 0.9943 | Train acc: 51.23% | Val loss: 1.0044 | Val acc: 47.04% | LR: 0.000008
Epoch: 068 | Train loss: 0.9941 | Train acc: 51.13% | Val loss: 1.0043 | Val acc: 46.88% | LR: 0.000008
Epoch: 069 | Train loss: 0.9962 | Train acc: 50.78% | Val loss: 1.0043 | Val acc: 46.86% | LR: 0.000007
Epoch: 070 | Train loss: 0.9974 | Train acc: 50.51% | Val loss: 1.0050 | Val acc: 47.02% | LR: 0.000007
Epoch: 071 | Train loss: 0.9959 | Train acc: 50.79% | Val loss: 1.0041 | Val acc: 47.06% | LR: 0.000007
Epoch: 072 | Train loss: 0.9958 | Train acc: 50.88% | Val loss: 1.0040 | Val acc: 47.14% | LR: 0.000007
Epoch: 073 | Train loss: 0.9920 | Train acc: 51.50% | Val loss: 1.0040 | Val acc: 47.16% | LR: 0.000007
Epoch: 074 | Train loss: 0.9908 | Train acc: 51.59% | Val loss: 1.0039 | Val acc: 47.10% | LR: 0.000007
Epoch: 075 | Train loss: 0.9942 | Train acc: 51.05% | Val loss: 1.0040 | Val acc: 47.10% | LR: 0.000007
Epoch: 076 | Train loss: 0.9934 | Train acc: 51.14% | Val loss: 1.0038 | Val acc: 47.14% | LR: 0.000007
Epoch: 077 | Train loss: 0.9971 | Train acc: 50.52% | Val loss: 1.0040 | Val acc: 47.10% | LR: 0.000006
Epoch: 078 | Train loss: 0.9968 | Train acc: 50.79% | Val loss: 1.0039 | Val acc: 47.28% | LR: 0.000006
Epoch: 079 | Train loss: 0.9933 | Train acc: 50.97% | Val loss: 1.0039 | Val acc: 47.30% | LR: 0.000006
Epoch: 080 | Train loss: 0.9962 | Train acc: 50.61% | Val loss: 1.0039 | Val acc: 47.33% | LR: 0.000006
Epoch: 081 | Train loss: 0.9925 | Train acc: 51.30% | Val loss: 1.0039 | Val acc: 47.43% | LR: 0.000006
Epoch: 082 | Train loss: 0.9912 | Train acc: 51.39% | Val loss: 1.0039 | Val acc: 47.41% | LR: 0.000006
Epoch: 083 | Train loss: 0.9920 | Train acc: 51.22% | Val loss: 1.0039 | Val acc: 47.43% | LR: 0.000006
Epoch: 084 | Train loss: 0.9932 | Train acc: 51.05% | Val loss: 1.0039 | Val acc: 47.39% | LR: 0.000006
Epoch: 085 | Train loss: 0.9919 | Train acc: 51.22% | Val loss: 1.0039 | Val acc: 47.35% | LR: 0.000005
Epoch: 086 | Train loss: 0.9974 | Train acc: 50.52% | Val loss: 1.0040 | Val acc: 47.35% | LR: 0.000005
Epoch: 087 | Train loss: 0.9910 | Train acc: 51.34% | Val loss: 1.0039 | Val acc: 47.33% | LR: 0.000005
Epoch: 088 | Train loss: 0.9932 | Train acc: 51.07% | Val loss: 1.0040 | Val acc: 47.47% | LR: 0.000005
Epoch: 089 | Train loss: 0.9964 | Train acc: 50.63% | Val loss: 1.0043 | Val acc: 47.59% | LR: 0.000005
Epoch: 090 | Train loss: 0.9907 | Train acc: 51.41% | Val loss: 1.0037 | Val acc: 47.71% | LR: 0.000005
Epoch: 091 | Train loss: 0.9928 | Train acc: 51.06% | Val loss: 1.0037 | Val acc: 47.73% | LR: 0.000005
Epoch: 092 | Train loss: 0.9944 | Train acc: 50.88% | Val loss: 1.0036 | Val acc: 47.67% | LR: 0.000005
Epoch: 093 | Train loss: 0.9939 | Train acc: 50.97% | Val loss: 1.0036 | Val acc: 47.71% | LR: 0.000005
Epoch: 094 | Train loss: 0.9979 | Train acc: 50.27% | Val loss: 1.0036 | Val acc: 47.69% | LR: 0.000004
Epoch: 095 | Train loss: 0.9949 | Train acc: 50.79% | Val loss: 1.0036 | Val acc: 47.77% | LR: 0.000004
Epoch: 096 | Train loss: 0.9924 | Train acc: 51.14% | Val loss: 1.0035 | Val acc: 47.81% | LR: 0.000004
Epoch: 097 | Train loss: 0.9934 | Train acc: 51.17% | Val loss: 1.0035 | Val acc: 47.83% | LR: 0.000004
Epoch: 098 | Train loss: 0.9971 | Train acc: 50.54% | Val loss: 1.0035 | Val acc: 47.83% | LR: 0.000004
Epoch: 099 | Train loss: 0.9991 | Train acc: 50.28% | Val loss: 1.0033 | Val acc: 47.89% | LR: 0.000004
Epoch: 100 | Train loss: 0.9946 | Train acc: 50.82% | Val loss: 1.0033 | Val acc: 47.87% | LR: 0.000004
Epoch: 101 | Train loss: 0.9936 | Train acc: 51.00% | Val loss: 1.0034 | Val acc: 47.87% | LR: 0.000004
Epoch: 102 | Train loss: 0.9982 | Train acc: 50.47% | Val loss: 1.0033 | Val acc: 47.89% | LR: 0.000004
Epoch: 103 | Train loss: 0.9921 | Train acc: 51.17% | Val loss: 1.0032 | Val acc: 47.93% | LR: 0.000003
Epoch: 104 | Train loss: 0.9952 | Train acc: 50.64% | Val loss: 1.0032 | Val acc: 47.83% | LR: 0.000003
Epoch: 105 | Train loss: 0.9933 | Train acc: 50.99% | Val loss: 1.0037 | Val acc: 47.82% | LR: 0.000003
Epoch: 106 | Train loss: 0.9926 | Train acc: 51.15% | Val loss: 1.0028 | Val acc: 48.00% | LR: 0.000003
Epoch: 107 | Train loss: 0.9895 | Train acc: 51.51% | Val loss: 1.0028 | Val acc: 48.02% | LR: 0.000003
Epoch: 108 | Train loss: 0.9939 | Train acc: 51.06% | Val loss: 1.0027 | Val acc: 47.98% | LR: 0.000003
Epoch: 109 | Train loss: 0.9927 | Train acc: 51.06% | Val loss: 1.0025 | Val acc: 48.10% | LR: 0.000003
Epoch: 110 | Train loss: 0.9925 | Train acc: 51.15% | Val loss: 1.0023 | Val acc: 48.14% | LR: 0.000003
Epoch: 111 | Train loss: 0.9970 | Train acc: 50.61% | Val loss: 1.0099 | Val acc: 48.08% | LR: 0.000003
Epoch: 112 | Train loss: 0.9934 | Train acc: 50.88% | Val loss: 1.0026 | Val acc: 47.96% | LR: 0.000003
Epoch: 113 | Train loss: 0.9924 | Train acc: 51.23% | Val loss: 1.0061 | Val acc: 47.92% | LR: 0.000003
Epoch: 114 | Train loss: 0.9959 | Train acc: 50.69% | Val loss: 1.0036 | Val acc: 47.98% | LR: 0.000002
Epoch: 115 | Train loss: 0.9928 | Train acc: 50.95% | Val loss: 1.0034 | Val acc: 47.94% | LR: 0.000002
Epoch: 116 | Train loss: 0.9969 | Train acc: 50.41% | Val loss: 1.0033 | Val acc: 47.94% | LR: 0.000002
Epoch: 117 | Train loss: 0.9978 | Train acc: 50.59% | Val loss: 1.0033 | Val acc: 47.94% | LR: 0.000002
Epoch: 118 | Train loss: 0.9877 | Train acc: 51.65% | Val loss: 1.0036 | Val acc: 47.88% | LR: 0.000002
Epoch: 119 | Train loss: 0.9932 | Train acc: 50.94% | Val loss: 1.0030 | Val acc: 47.92% | LR: 0.000002
Epoch: 120 | Train loss: 0.9928 | Train acc: 50.87% | Val loss: 1.0030 | Val acc: 47.92% | LR: 0.000002
Epoch: 121 | Train loss: 0.9971 | Train acc: 50.41% | Val loss: 1.0034 | Val acc: 47.96% | LR: 0.000002
Epoch: 122 | Train loss: 0.9889 | Train acc: 51.39% | Val loss: 1.0026 | Val acc: 48.02% | LR: 0.000002
Epoch: 123 | Train loss: 0.9932 | Train acc: 50.86% | Val loss: 1.0037 | Val acc: 47.94% | LR: 0.000002
Epoch: 124 | Train loss: 0.9959 | Train acc: 50.60% | Val loss: 1.0032 | Val acc: 47.90% | LR: 0.000002
Epoch: 125 | Train loss: 0.9936 | Train acc: 51.04% | Val loss: 1.0032 | Val acc: 47.88% | LR: 0.000002
Epoch: 126 | Train loss: 0.9935 | Train acc: 50.78% | Val loss: 1.0033 | Val acc: 47.88% | LR: 0.000002
Epoch: 127 | Train loss: 0.9913 | Train acc: 51.04% | Val loss: 1.0036 | Val acc: 47.92% | LR: 0.000002
Epoch: 128 | Train loss: 0.9893 | Train acc: 51.22% | Val loss: 1.0079 | Val acc: 47.92% | LR: 0.000002
Epoch: 129 | Train loss: 0.9906 | Train acc: 51.21% | Val loss: 1.0027 | Val acc: 47.94% | LR: 0.000001
Epoch: 130 | Train loss: 0.9926 | Train acc: 50.95% | Val loss: 1.0026 | Val acc: 47.96% | LR: 0.000001
Epoch: 131 | Train loss: 0.9884 | Train acc: 51.29% | Val loss: 1.0025 | Val acc: 48.02% | LR: 0.000001
Epoch: 132 | Train loss: 0.9910 | Train acc: 51.11% | Val loss: 1.0023 | Val acc: 48.02% | LR: 0.000001
Epoch: 133 | Train loss: 0.9938 | Train acc: 50.67% | Val loss: 1.0030 | Val acc: 48.00% | LR: 0.000001
Epoch: 134 | Train loss: 0.9913 | Train acc: 51.11% | Val loss: 1.0027 | Val acc: 48.06% | LR: 0.000001
Epoch: 135 | Train loss: 0.9935 | Train acc: 50.94% | Val loss: 1.0027 | Val acc: 48.06% | LR: 0.000001
Epoch: 136 | Train loss: 0.9907 | Train acc: 51.19% | Val loss: 1.0026 | Val acc: 48.14% | LR: 0.000001
Epoch: 137 | Train loss: 0.9890 | Train acc: 51.20% | Val loss: 1.0026 | Val acc: 48.16% | LR: 0.000001
Epoch: 138 | Train loss: 0.9929 | Train acc: 50.85% | Val loss: 1.0026 | Val acc: 48.18% | LR: 0.000001
Epoch: 139 | Train loss: 0.9920 | Train acc: 51.11% | Val loss: 1.0026 | Val acc: 48.18% | LR: 0.000001
Epoch: 140 | Train loss: 0.9939 | Train acc: 51.02% | Val loss: 1.0025 | Val acc: 48.18% | LR: 0.000001
Epoch: 141 | Train loss: 0.9962 | Train acc: 50.76% | Val loss: 1.0024 | Val acc: 48.20% | LR: 0.000001
Epoch: 142 | Train loss: 0.9963 | Train acc: 50.74% | Val loss: 1.0023 | Val acc: 48.18% | LR: 0.000001
Epoch: 143 | Train loss: 0.9889 | Train acc: 51.27% | Val loss: 1.0106 | Val acc: 48.16% | LR: 0.000001
Epoch: 144 | Train loss: 0.9924 | Train acc: 50.92% | Val loss: 1.0032 | Val acc: 48.16% | LR: 0.000001
Epoch: 145 | Train loss: 0.9938 | Train acc: 50.76% | Val loss: 1.0029 | Val acc: 48.14% | LR: 0.000001
Epoch: 146 | Train loss: 0.9914 | Train acc: 51.01% | Val loss: 1.0029 | Val acc: 48.14% | LR: 0.000001
Epoch: 147 | Train loss: 0.9918 | Train acc: 50.93% | Val loss: 1.0029 | Val acc: 48.14% | LR: 0.000001
Epoch: 148 | Train loss: 0.9917 | Train acc: 51.02% | Val loss: 1.0028 | Val acc: 48.18% | LR: 0.000001
Epoch: 149 | Train loss: 0.9925 | Train acc: 50.75% | Val loss: 1.0030 | Val acc: 48.12% | LR: 0.000001

[I 2025-09-23 18:25:19,596] Trial 111 finished with value: 0.4811559021472931 and parameters: {'lr': 1.2563931845085656e-05, 'hidden_size': 80, 'dropout': 0.2066921692125542, 'weight_decay': 2.3707322919039217e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0003 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.11% | LR: 0.000017
Epoch: 001 | Train loss: 1.0007 | Train acc: 49.72% | Val loss: 0.9916 | Val acc: 54.13% | LR: 0.000017
Epoch: 002 | Train loss: 1.0004 | Train acc: 49.54% | Val loss: 0.9916 | Val acc: 54.13% | LR: 0.000017
Epoch: 003 | Train loss: 1.0008 | Train acc: 49.54% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000017
Epoch: 004 | Train loss: 1.0014 | Train acc: 49.37% | Val loss: 0.9918 | Val acc: 54.15% | LR: 0.000017
Epoch: 005 | Train loss: 0.9986 | Train acc: 49.92% | Val loss: 0.9918 | Val acc: 54.24% | LR: 0.000017
Epoch: 006 | Train loss: 1.0006 | Train acc: 49.60% | Val loss: 0.9918 | Val acc: 54.34% | LR: 0.000017
Epoch: 007 | Train loss: 1.0013 | Train acc: 49.65% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000017
Epoch: 008 | Train loss: 1.0008 | Train acc: 49.53% | Val loss: 0.9920 | Val acc: 54.26% | LR: 0.000017
Epoch: 009 | Train loss: 0.9990 | Train acc: 50.52% | Val loss: 0.9921 | Val acc: 54.28% | LR: 0.000017
Epoch: 010 | Train loss: 0.9984 | Train acc: 50.82% | Val loss: 0.9921 | Val acc: 54.28% | LR: 0.000017
Epoch: 011 | Train loss: 0.9983 | Train acc: 50.80% | Val loss: 0.9920 | Val acc: 54.26% | LR: 0.000017
Epoch: 012 | Train loss: 0.9980 | Train acc: 50.64% | Val loss: 0.9920 | Val acc: 54.28% | LR: 0.000017
Epoch: 013 | Train loss: 0.9991 | Train acc: 50.43% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000017
Epoch: 014 | Train loss: 0.9982 | Train acc: 50.41% | Val loss: 0.9919 | Val acc: 54.34% | LR: 0.000017
Epoch: 015 | Train loss: 0.9994 | Train acc: 50.15% | Val loss: 0.9919 | Val acc: 54.34% | LR: 0.000017
Epoch: 016 | Train loss: 0.9981 | Train acc: 50.61% | Val loss: 0.9920 | Val acc: 54.44% | LR: 0.000017
Epoch: 017 | Train loss: 0.9986 | Train acc: 50.51% | Val loss: 0.9919 | Val acc: 54.34% | LR: 0.000017
Epoch: 018 | Train loss: 0.9987 | Train acc: 50.23% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000017
Epoch: 019 | Train loss: 0.9986 | Train acc: 50.20% | Val loss: 0.9919 | Val acc: 54.37% | LR: 0.000017
Epoch: 020 | Train loss: 0.9961 | Train acc: 51.19% | Val loss: 0.9918 | Val acc: 54.33% | LR: 0.000017
Epoch: 021 | Train loss: 0.9973 | Train acc: 50.65% | Val loss: 0.9919 | Val acc: 54.23% | LR: 0.000017
Epoch: 022 | Train loss: 0.9968 | Train acc: 50.86% | Val loss: 0.9916 | Val acc: 54.35% | LR: 0.000017
Epoch: 023 | Train loss: 0.9977 | Train acc: 50.42% | Val loss: 0.9916 | Val acc: 54.27% | LR: 0.000016
Epoch: 024 | Train loss: 0.9977 | Train acc: 50.43% | Val loss: 0.9917 | Val acc: 54.37% | LR: 0.000016
Epoch: 025 | Train loss: 0.9987 | Train acc: 50.15% | Val loss: 1.0051 | Val acc: 54.31% | LR: 0.000016
Epoch: 026 | Train loss: 0.9974 | Train acc: 50.41% | Val loss: 0.9922 | Val acc: 54.40% | LR: 0.000016
Epoch: 027 | Train loss: 0.9968 | Train acc: 50.93% | Val loss: 0.9943 | Val acc: 54.39% | LR: 0.000016
Epoch: 028 | Train loss: 0.9962 | Train acc: 51.01% | Val loss: 0.9917 | Val acc: 54.32% | LR: 0.000016
Epoch: 029 | Train loss: 1.1716 | Train acc: 50.20% | Val loss: 1.0015 | Val acc: 54.35% | LR: 0.000016
Epoch: 030 | Train loss: 1.0019 | Train acc: 50.26% | Val loss: 0.9916 | Val acc: 54.29% | LR: 0.000016
Epoch: 031 | Train loss: 0.9989 | Train acc: 50.34% | Val loss: 0.9916 | Val acc: 54.29% | LR: 0.000016
Epoch: 032 | Train loss: 0.9980 | Train acc: 50.63% | Val loss: 0.9915 | Val acc: 54.31% | LR: 0.000016
Epoch: 033 | Train loss: 1.0038 | Train acc: 49.59% | Val loss: 0.9916 | Val acc: 54.31% | LR: 0.000015
Epoch: 034 | Train loss: 0.9983 | Train acc: 50.75% | Val loss: 0.9917 | Val acc: 54.32% | LR: 0.000015
Epoch: 035 | Train loss: 0.9996 | Train acc: 50.27% | Val loss: 0.9917 | Val acc: 54.37% | LR: 0.000015
Epoch: 036 | Train loss: 0.9985 | Train acc: 50.50% | Val loss: 0.9923 | Val acc: 54.42% | LR: 0.000015
Epoch: 037 | Train loss: 0.9987 | Train acc: 50.55% | Val loss: 0.9916 | Val acc: 54.55% | LR: 0.000015
Epoch: 038 | Train loss: 1.0025 | Train acc: 50.45% | Val loss: 0.9916 | Val acc: 54.45% | LR: 0.000015
Epoch: 039 | Train loss: 0.9978 | Train acc: 51.00% | Val loss: 0.9915 | Val acc: 54.50% | LR: 0.000015
Epoch: 040 | Train loss: 0.9979 | Train acc: 51.02% | Val loss: 0.9914 | Val acc: 54.43% | LR: 0.000015
Epoch: 041 | Train loss: 0.9978 | Train acc: 50.82% | Val loss: 0.9916 | Val acc: 54.56% | LR: 0.000014
Epoch: 042 | Train loss: 0.9986 | Train acc: 50.54% | Val loss: 0.9916 | Val acc: 54.62% | LR: 0.000014
Epoch: 043 | Train loss: 1.0005 | Train acc: 50.52% | Val loss: 0.9916 | Val acc: 54.68% | LR: 0.000014
Epoch: 044 | Train loss: 0.9986 | Train acc: 50.36% | Val loss: 0.9949 | Val acc: 54.68% | LR: 0.000014
Epoch: 045 | Train loss: 0.9978 | Train acc: 50.72% | Val loss: 0.9930 | Val acc: 54.54% | LR: 0.000014
Epoch: 046 | Train loss: 0.9967 | Train acc: 51.21% | Val loss: 0.9928 | Val acc: 54.62% | LR: 0.000014
Epoch: 047 | Train loss: 0.9986 | Train acc: 50.33% | Val loss: 0.9916 | Val acc: 54.58% | LR: 0.000014
Epoch: 048 | Train loss: 0.9983 | Train acc: 50.68% | Val loss: 0.9911 | Val acc: 54.60% | LR: 0.000014
Epoch: 049 | Train loss: 0.9981 | Train acc: 50.61% | Val loss: 0.9915 | Val acc: 54.67% | LR: 0.000013
Epoch: 050 | Train loss: 0.9990 | Train acc: 50.44% | Val loss: 0.9915 | Val acc: 54.64% | LR: 0.000013
Epoch: 051 | Train loss: 0.9975 | Train acc: 50.69% | Val loss: 0.9916 | Val acc: 54.50% | LR: 0.000013
Epoch: 052 | Train loss: 0.9989 | Train acc: 50.55% | Val loss: 0.9916 | Val acc: 54.48% | LR: 0.000013
Epoch: 053 | Train loss: 0.9981 | Train acc: 50.52% | Val loss: 0.9916 | Val acc: 54.58% | LR: 0.000013
Epoch: 054 | Train loss: 0.9971 | Train acc: 50.86% | Val loss: 0.9916 | Val acc: 54.50% | LR: 0.000013
Epoch: 055 | Train loss: 0.9971 | Train acc: 50.88% | Val loss: 0.9916 | Val acc: 54.56% | LR: 0.000012
Epoch: 056 | Train loss: 0.9968 | Train acc: 51.04% | Val loss: 0.9916 | Val acc: 54.56% | LR: 0.000012
Epoch: 057 | Train loss: 0.9975 | Train acc: 50.48% | Val loss: 0.9923 | Val acc: 54.57% | LR: 0.000012
Epoch: 058 | Train loss: 0.9980 | Train acc: 50.62% | Val loss: 0.9916 | Val acc: 54.53% | LR: 0.000012
Epoch: 059 | Train loss: 0.9970 | Train acc: 51.04% | Val loss: 0.9915 | Val acc: 54.53% | LR: 0.000012
Epoch: 060 | Train loss: 0.9969 | Train acc: 50.78% | Val loss: 0.9916 | Val acc: 54.49% | LR: 0.000012
Epoch: 061 | Train loss: 0.9965 | Train acc: 50.61% | Val loss: 0.9914 | Val acc: 54.55% | LR: 0.000011
Epoch: 062 | Train loss: 0.9966 | Train acc: 50.63% | Val loss: 0.9915 | Val acc: 54.59% | LR: 0.000011
Epoch: 063 | Train loss: 0.9980 | Train acc: 50.53% | Val loss: 0.9914 | Val acc: 54.67% | LR: 0.000011
Epoch: 064 | Train loss: 0.9971 | Train acc: 50.89% | Val loss: 0.9917 | Val acc: 54.73% | LR: 0.000011
Epoch: 065 | Train loss: 0.9974 | Train acc: 50.87% | Val loss: 0.9914 | Val acc: 54.74% | LR: 0.000011
Epoch: 066 | Train loss: 0.9981 | Train acc: 50.44% | Val loss: 0.9918 | Val acc: 54.71% | LR: 0.000011
Epoch: 067 | Train loss: 0.9961 | Train acc: 51.50% | Val loss: 0.9916 | Val acc: 54.65% | LR: 0.000010
Epoch: 068 | Train loss: 0.9969 | Train acc: 50.98% | Val loss: 0.9991 | Val acc: 54.63% | LR: 0.000010
Epoch: 069 | Train loss: 0.9978 | Train acc: 50.60% | Val loss: 0.9914 | Val acc: 54.67% | LR: 0.000010
Epoch: 070 | Train loss: 0.9938 | Train acc: 51.08% | Val loss: 0.9918 | Val acc: 54.70% | LR: 0.000010
Epoch: 071 | Train loss: 0.9983 | Train acc: 50.71% | Val loss: 0.9915 | Val acc: 54.71% | LR: 0.000010
Epoch: 072 | Train loss: 0.9985 | Train acc: 50.58% | Val loss: 0.9915 | Val acc: 54.71% | LR: 0.000010
Epoch: 073 | Train loss: 1.0005 | Train acc: 50.00% | Val loss: 0.9915 | Val acc: 54.71% | LR: 0.000009
Epoch: 074 | Train loss: 1.0406 | Train acc: 50.91% | Val loss: 0.9914 | Val acc: 54.69% | LR: 0.000009
Epoch: 075 | Train loss: 0.9974 | Train acc: 50.94% | Val loss: 0.9915 | Val acc: 54.74% | LR: 0.000009
Epoch: 076 | Train loss: 0.9993 | Train acc: 50.50% | Val loss: 0.9913 | Val acc: 54.76% | LR: 0.000009
Epoch: 077 | Train loss: 0.9982 | Train acc: 50.35% | Val loss: 0.9913 | Val acc: 54.76% | LR: 0.000009
Epoch: 078 | Train loss: 0.9979 | Train acc: 50.77% | Val loss: 0.9913 | Val acc: 54.80% | LR: 0.000009
Epoch: 079 | Train loss: 0.9990 | Train acc: 50.75% | Val loss: 0.9915 | Val acc: 54.68% | LR: 0.000008
Epoch: 080 | Train loss: 0.9982 | Train acc: 51.10% | Val loss: 0.9915 | Val acc: 54.72% | LR: 0.000008
Epoch: 081 | Train loss: 0.9983 | Train acc: 50.66% | Val loss: 0.9915 | Val acc: 54.62% | LR: 0.000008
Epoch: 082 | Train loss: 0.9974 | Train acc: 51.27% | Val loss: 0.9915 | Val acc: 54.68% | LR: 0.000008
Epoch: 083 | Train loss: 0.9980 | Train acc: 50.41% | Val loss: 0.9915 | Val acc: 54.72% | LR: 0.000008
Epoch: 084 | Train loss: 0.9988 | Train acc: 50.76% | Val loss: 0.9915 | Val acc: 54.68% | LR: 0.000008
Epoch: 085 | Train loss: 0.9989 | Train acc: 50.33% | Val loss: 0.9915 | Val acc: 54.62% | LR: 0.000007
Epoch: 086 | Train loss: 0.9978 | Train acc: 50.68% | Val loss: 0.9915 | Val acc: 54.62% | LR: 0.000007
Epoch: 087 | Train loss: 0.9976 | Train acc: 50.69% | Val loss: 0.9915 | Val acc: 54.60% | LR: 0.000007
Epoch: 088 | Train loss: 1.0013 | Train acc: 50.64% | Val loss: 0.9915 | Val acc: 54.58% | LR: 0.000007
Epoch: 089 | Train loss: 0.9977 | Train acc: 50.59% | Val loss: 0.9916 | Val acc: 54.50% | LR: 0.000007
Epoch: 090 | Train loss: 0.9975 | Train acc: 50.77% | Val loss: 0.9915 | Val acc: 54.58% | LR: 0.000007
Epoch: 091 | Train loss: 0.9972 | Train acc: 50.96% | Val loss: 0.9914 | Val acc: 54.64% | LR: 0.000006
Epoch: 092 | Train loss: 0.9966 | Train acc: 50.54% | Val loss: 0.9915 | Val acc: 54.58% | LR: 0.000006
Epoch: 093 | Train loss: 0.9971 | Train acc: 50.78% | Val loss: 0.9915 | Val acc: 54.62% | LR: 0.000006
Epoch: 094 | Train loss: 0.9964 | Train acc: 51.32% | Val loss: 0.9915 | Val acc: 54.64% | LR: 0.000006
Epoch: 095 | Train loss: 0.9976 | Train acc: 50.90% | Val loss: 0.9915 | Val acc: 54.48% | LR: 0.000006
Epoch: 096 | Train loss: 0.9972 | Train acc: 50.98% | Val loss: 0.9916 | Val acc: 54.52% | LR: 0.000006
Epoch: 097 | Train loss: 0.9972 | Train acc: 50.82% | Val loss: 0.9916 | Val acc: 54.41% | LR: 0.000005
Epoch: 098 | Train loss: 0.9979 | Train acc: 50.98% | Val loss: 0.9915 | Val acc: 54.45% | LR: 0.000005
Epoch: 099 | Train loss: 0.9972 | Train acc: 51.08% | Val loss: 0.9915 | Val acc: 54.46% | LR: 0.000005
Epoch: 100 | Train loss: 0.9966 | Train acc: 50.45% | Val loss: 0.9916 | Val acc: 54.37% | LR: 0.000005
Epoch: 101 | Train loss: 0.9970 | Train acc: 50.96% | Val loss: 0.9916 | Val acc: 54.36% | LR: 0.000005
Epoch: 102 | Train loss: 0.9965 | Train acc: 50.97% | Val loss: 0.9916 | Val acc: 54.38% | LR: 0.000005
Epoch: 103 | Train loss: 0.9971 | Train acc: 50.90% | Val loss: 0.9916 | Val acc: 54.36% | LR: 0.000005
Epoch: 104 | Train loss: 0.9976 | Train acc: 50.63% | Val loss: 0.9916 | Val acc: 54.32% | LR: 0.000004
Epoch: 105 | Train loss: 0.9967 | Train acc: 51.33% | Val loss: 0.9916 | Val acc: 54.32% | LR: 0.000004
Epoch: 106 | Train loss: 0.9966 | Train acc: 50.99% | Val loss: 0.9915 | Val acc: 54.34% | LR: 0.000004
Epoch: 107 | Train loss: 0.9966 | Train acc: 51.06% | Val loss: 0.9916 | Val acc: 54.26% | LR: 0.000004
Epoch: 108 | Train loss: 0.9981 | Train acc: 50.27% | Val loss: 0.9915 | Val acc: 54.31% | LR: 0.000004
Epoch: 109 | Train loss: 0.9973 | Train acc: 50.96% | Val loss: 0.9915 | Val acc: 54.39% | LR: 0.000004
Epoch: 110 | Train loss: 0.9966 | Train acc: 50.61% | Val loss: 0.9916 | Val acc: 54.39% | LR: 0.000004
Epoch: 111 | Train loss: 0.9962 | Train acc: 50.79% | Val loss: 0.9915 | Val acc: 54.41% | LR: 0.000003
Epoch: 112 | Train loss: 0.9973 | Train acc: 50.34% | Val loss: 0.9915 | Val acc: 54.41% | LR: 0.000003
Epoch: 113 | Train loss: 0.9969 | Train acc: 50.44% | Val loss: 0.9915 | Val acc: 54.41% | LR: 0.000003
Epoch: 114 | Train loss: 0.9969 | Train acc: 50.37% | Val loss: 0.9916 | Val acc: 54.39% | LR: 0.000003
Epoch: 115 | Train loss: 0.9968 | Train acc: 51.25% | Val loss: 0.9916 | Val acc: 54.41% | LR: 0.000003
Epoch: 116 | Train loss: 0.9960 | Train acc: 51.16% | Val loss: 0.9916 | Val acc: 54.41% | LR: 0.000003
Epoch: 117 | Train loss: 0.9976 | Train acc: 50.47% | Val loss: 0.9915 | Val acc: 54.43% | LR: 0.000003
Epoch: 118 | Train loss: 0.9971 | Train acc: 50.53% | Val loss: 0.9915 | Val acc: 54.43% | LR: 0.000003
Epoch: 119 | Train loss: 0.9974 | Train acc: 50.90% | Val loss: 0.9915 | Val acc: 54.43% | LR: 0.000003
Epoch: 120 | Train loss: 0.9974 | Train acc: 50.55% | Val loss: 0.9915 | Val acc: 54.41% | LR: 0.000002
Epoch: 121 | Train loss: 0.9965 | Train acc: 50.99% | Val loss: 0.9915 | Val acc: 54.39% | LR: 0.000002
Epoch: 122 | Train loss: 0.9966 | Train acc: 51.00% | Val loss: 0.9915 | Val acc: 54.39% | LR: 0.000002
Epoch: 123 | Train loss: 0.9962 | Train acc: 50.99% | Val loss: 0.9915 | Val acc: 54.39% | LR: 0.000002
Epoch: 124 | Train loss: 0.9966 | Train acc: 51.17% | Val loss: 0.9915 | Val acc: 54.34% | LR: 0.000002
Epoch: 125 | Train loss: 0.9965 | Train acc: 50.99% | Val loss: 0.9915 | Val acc: 54.34% | LR: 0.000002
Epoch: 126 | Train loss: 0.9982 | Train acc: 50.32% | Val loss: 0.9915 | Val acc: 54.34% | LR: 0.000002
Epoch: 127 | Train loss: 1.0140 | Train acc: 50.69% | Val loss: 0.9915 | Val acc: 54.34% | LR: 0.000002

[I 2025-09-23 18:27:05,665] Trial 112 finished with value: 0.5433510422706604 and parameters: {'lr': 1.7488699988446936e-05, 'hidden_size': 64, 'dropout': 0.23693802148059073, 'weight_decay': 2.22809930353863e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0005 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.05% | LR: 0.000011
Epoch: 001 | Train loss: 1.0007 | Train acc: 49.52% | Val loss: 0.9916 | Val acc: 54.09% | LR: 0.000011
Epoch: 002 | Train loss: 0.9995 | Train acc: 50.36% | Val loss: 0.9916 | Val acc: 54.11% | LR: 0.000011
Epoch: 003 | Train loss: 0.9992 | Train acc: 50.49% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000011
Epoch: 004 | Train loss: 0.9998 | Train acc: 50.16% | Val loss: 0.9918 | Val acc: 54.11% | LR: 0.000011
Epoch: 005 | Train loss: 0.9979 | Train acc: 50.87% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000011
Epoch: 006 | Train loss: 0.9986 | Train acc: 50.52% | Val loss: 0.9918 | Val acc: 54.17% | LR: 0.000011
Epoch: 007 | Train loss: 0.9996 | Train acc: 49.98% | Val loss: 0.9918 | Val acc: 54.17% | LR: 0.000011
Epoch: 008 | Train loss: 1.0000 | Train acc: 49.72% | Val loss: 0.9919 | Val acc: 54.24% | LR: 0.000011
Epoch: 009 | Train loss: 0.9981 | Train acc: 50.60% | Val loss: 0.9919 | Val acc: 54.30% | LR: 0.000011
Epoch: 010 | Train loss: 0.9977 | Train acc: 50.78% | Val loss: 0.9920 | Val acc: 54.34% | LR: 0.000011
Epoch: 011 | Train loss: 0.9975 | Train acc: 50.87% | Val loss: 0.9919 | Val acc: 54.34% | LR: 0.000011
Epoch: 012 | Train loss: 0.9978 | Train acc: 50.69% | Val loss: 0.9919 | Val acc: 54.30% | LR: 0.000011
Epoch: 013 | Train loss: 0.9977 | Train acc: 50.43% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000011
Epoch: 014 | Train loss: 0.9984 | Train acc: 50.43% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000011
Epoch: 015 | Train loss: 0.9983 | Train acc: 50.15% | Val loss: 0.9918 | Val acc: 54.34% | LR: 0.000011
Epoch: 016 | Train loss: 0.9982 | Train acc: 50.59% | Val loss: 0.9919 | Val acc: 54.28% | LR: 0.000011
Epoch: 017 | Train loss: 0.9973 | Train acc: 50.51% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000011
Epoch: 018 | Train loss: 0.9971 | Train acc: 50.24% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000011
Epoch: 019 | Train loss: 0.9987 | Train acc: 50.24% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000011
Epoch: 020 | Train loss: 0.9983 | Train acc: 51.13% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000011
Epoch: 021 | Train loss: 0.9958 | Train acc: 50.59% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000011
Epoch: 022 | Train loss: 0.9996 | Train acc: 50.78% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000011
Epoch: 023 | Train loss: 1.0026 | Train acc: 50.22% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000011
Epoch: 024 | Train loss: 1.0087 | Train acc: 50.40% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000011
Epoch: 025 | Train loss: 1.0002 | Train acc: 50.06% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000011
Epoch: 026 | Train loss: 0.9977 | Train acc: 50.15% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000011
Epoch: 027 | Train loss: 1.0041 | Train acc: 50.75% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000010
Epoch: 028 | Train loss: 0.9953 | Train acc: 50.88% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000010
Epoch: 029 | Train loss: 0.9965 | Train acc: 50.65% | Val loss: 0.9917 | Val acc: 54.36% | LR: 0.000010
Epoch: 030 | Train loss: 0.9991 | Train acc: 50.44% | Val loss: 0.9917 | Val acc: 54.38% | LR: 0.000010
Epoch: 031 | Train loss: 0.9979 | Train acc: 50.32% | Val loss: 0.9917 | Val acc: 54.38% | LR: 0.000010
Epoch: 032 | Train loss: 0.9949 | Train acc: 51.03% | Val loss: 0.9917 | Val acc: 54.38% | LR: 0.000010
Epoch: 033 | Train loss: 0.9972 | Train acc: 49.93% | Val loss: 0.9917 | Val acc: 54.36% | LR: 0.000010
Epoch: 034 | Train loss: 0.9945 | Train acc: 50.92% | Val loss: 0.9917 | Val acc: 54.42% | LR: 0.000010
Epoch: 035 | Train loss: 0.9972 | Train acc: 50.12% | Val loss: 0.9917 | Val acc: 54.44% | LR: 0.000010
Epoch: 036 | Train loss: 1.0027 | Train acc: 50.33% | Val loss: 0.9917 | Val acc: 54.44% | LR: 0.000010
Epoch: 037 | Train loss: 0.9961 | Train acc: 50.31% | Val loss: 0.9917 | Val acc: 54.38% | LR: 0.000010
Epoch: 038 | Train loss: 0.9978 | Train acc: 50.27% | Val loss: 0.9917 | Val acc: 54.38% | LR: 0.000010
Epoch: 039 | Train loss: 0.9972 | Train acc: 50.78% | Val loss: 0.9917 | Val acc: 54.38% | LR: 0.000010
Epoch: 040 | Train loss: 0.9968 | Train acc: 50.58% | Val loss: 0.9917 | Val acc: 54.44% | LR: 0.000010
Epoch: 041 | Train loss: 0.9971 | Train acc: 50.51% | Val loss: 0.9916 | Val acc: 54.39% | LR: 0.000009
Epoch: 042 | Train loss: 0.9964 | Train acc: 50.27% | Val loss: 0.9916 | Val acc: 54.47% | LR: 0.000009
Epoch: 043 | Train loss: 0.9986 | Train acc: 50.49% | Val loss: 0.9916 | Val acc: 54.40% | LR: 0.000009
Epoch: 044 | Train loss: 0.9987 | Train acc: 50.15% | Val loss: 0.9916 | Val acc: 54.40% | LR: 0.000009
Epoch: 045 | Train loss: 0.9965 | Train acc: 50.51% | Val loss: 0.9915 | Val acc: 54.34% | LR: 0.000009
Epoch: 046 | Train loss: 0.9944 | Train acc: 50.88% | Val loss: 0.9915 | Val acc: 54.34% | LR: 0.000009
Epoch: 047 | Train loss: 0.9973 | Train acc: 50.06% | Val loss: 0.9915 | Val acc: 54.28% | LR: 0.000009
Epoch: 048 | Train loss: 0.9970 | Train acc: 50.36% | Val loss: 0.9915 | Val acc: 54.26% | LR: 0.000009
Epoch: 049 | Train loss: 0.9972 | Train acc: 50.39% | Val loss: 0.9919 | Val acc: 54.24% | LR: 0.000009
Epoch: 050 | Train loss: 0.9971 | Train acc: 50.14% | Val loss: 0.9916 | Val acc: 54.30% | LR: 0.000009
Epoch: 051 | Train loss: 0.9994 | Train acc: 50.33% | Val loss: 0.9915 | Val acc: 54.32% | LR: 0.000009
Epoch: 052 | Train loss: 0.9999 | Train acc: 50.32% | Val loss: 0.9915 | Val acc: 54.26% | LR: 0.000008
Epoch: 053 | Train loss: 0.9972 | Train acc: 50.19% | Val loss: 0.9915 | Val acc: 54.37% | LR: 0.000008
Epoch: 054 | Train loss: 0.9969 | Train acc: 50.64% | Val loss: 0.9915 | Val acc: 54.43% | LR: 0.000008
Epoch: 055 | Train loss: 0.9953 | Train acc: 50.65% | Val loss: 0.9915 | Val acc: 54.34% | LR: 0.000008
Epoch: 056 | Train loss: 0.9944 | Train acc: 50.84% | Val loss: 0.9915 | Val acc: 54.41% | LR: 0.000008
Epoch: 057 | Train loss: 0.9971 | Train acc: 50.29% | Val loss: 0.9915 | Val acc: 54.36% | LR: 0.000008
Epoch: 058 | Train loss: 0.9978 | Train acc: 50.41% | Val loss: 0.9915 | Val acc: 54.41% | LR: 0.000008
Epoch: 059 | Train loss: 0.9954 | Train acc: 50.89% | Val loss: 0.9915 | Val acc: 54.37% | LR: 0.000008
Epoch: 060 | Train loss: 0.9951 | Train acc: 50.59% | Val loss: 0.9915 | Val acc: 54.31% | LR: 0.000008
Epoch: 061 | Train loss: 0.9939 | Train acc: 50.31% | Val loss: 0.9915 | Val acc: 54.35% | LR: 0.000008
Epoch: 062 | Train loss: 0.9953 | Train acc: 50.39% | Val loss: 0.9915 | Val acc: 54.41% | LR: 0.000007
Epoch: 063 | Train loss: 0.9985 | Train acc: 50.33% | Val loss: 0.9915 | Val acc: 54.41% | LR: 0.000007
Epoch: 064 | Train loss: 0.9956 | Train acc: 50.72% | Val loss: 0.9915 | Val acc: 54.45% | LR: 0.000007
Epoch: 065 | Train loss: 1.0002 | Train acc: 50.60% | Val loss: 0.9915 | Val acc: 54.43% | LR: 0.000007
Epoch: 066 | Train loss: 0.9980 | Train acc: 50.19% | Val loss: 0.9915 | Val acc: 54.39% | LR: 0.000007
Epoch: 067 | Train loss: 0.9946 | Train acc: 51.15% | Val loss: 0.9915 | Val acc: 54.45% | LR: 0.000007
Epoch: 068 | Train loss: 0.9985 | Train acc: 50.57% | Val loss: 0.9915 | Val acc: 54.51% | LR: 0.000007
Epoch: 069 | Train loss: 0.9966 | Train acc: 50.47% | Val loss: 0.9915 | Val acc: 54.53% | LR: 0.000007
Epoch: 070 | Train loss: 0.9943 | Train acc: 50.97% | Val loss: 0.9915 | Val acc: 54.46% | LR: 0.000007
Epoch: 071 | Train loss: 0.9963 | Train acc: 50.75% | Val loss: 0.9915 | Val acc: 54.52% | LR: 0.000006
Epoch: 072 | Train loss: 0.9939 | Train acc: 50.64% | Val loss: 0.9915 | Val acc: 54.52% | LR: 0.000006
Epoch: 073 | Train loss: 0.9962 | Train acc: 49.73% | Val loss: 0.9915 | Val acc: 54.50% | LR: 0.000006
Epoch: 074 | Train loss: 0.9929 | Train acc: 51.22% | Val loss: 0.9915 | Val acc: 54.48% | LR: 0.000006
Epoch: 075 | Train loss: 0.9933 | Train acc: 51.12% | Val loss: 0.9914 | Val acc: 54.48% | LR: 0.000006
Epoch: 076 | Train loss: 0.9952 | Train acc: 50.14% | Val loss: 0.9914 | Val acc: 54.50% | LR: 0.000006
Epoch: 077 | Train loss: 0.9961 | Train acc: 50.22% | Val loss: 0.9914 | Val acc: 54.48% | LR: 0.000006
Epoch: 078 | Train loss: 1.0332 | Train acc: 50.27% | Val loss: 0.9914 | Val acc: 54.44% | LR: 0.000006
Epoch: 079 | Train loss: 0.9941 | Train acc: 50.85% | Val loss: 0.9915 | Val acc: 54.50% | LR: 0.000006
Epoch: 080 | Train loss: 0.9955 | Train acc: 51.29% | Val loss: 0.9915 | Val acc: 54.46% | LR: 0.000006
Epoch: 081 | Train loss: 0.9957 | Train acc: 51.07% | Val loss: 0.9915 | Val acc: 54.48% | LR: 0.000005
Epoch: 082 | Train loss: 0.9948 | Train acc: 51.39% | Val loss: 0.9915 | Val acc: 54.48% | LR: 0.000005
Epoch: 083 | Train loss: 0.9950 | Train acc: 50.21% | Val loss: 0.9915 | Val acc: 54.48% | LR: 0.000005
Epoch: 084 | Train loss: 0.9950 | Train acc: 50.64% | Val loss: 0.9915 | Val acc: 54.39% | LR: 0.000005
Epoch: 085 | Train loss: 0.9971 | Train acc: 50.21% | Val loss: 0.9915 | Val acc: 54.40% | LR: 0.000005
Epoch: 086 | Train loss: 0.9935 | Train acc: 50.58% | Val loss: 0.9915 | Val acc: 54.38% | LR: 0.000005
Epoch: 087 | Train loss: 0.9950 | Train acc: 50.65% | Val loss: 0.9915 | Val acc: 54.36% | LR: 0.000005
Epoch: 088 | Train loss: 0.9950 | Train acc: 50.57% | Val loss: 0.9915 | Val acc: 54.34% | LR: 0.000005
Epoch: 089 | Train loss: 0.9958 | Train acc: 50.49% | Val loss: 0.9915 | Val acc: 54.34% | LR: 0.000005
Epoch: 090 | Train loss: 0.9979 | Train acc: 50.56% | Val loss: 0.9915 | Val acc: 54.38% | LR: 0.000004
Epoch: 091 | Train loss: 0.9939 | Train acc: 50.80% | Val loss: 0.9915 | Val acc: 54.40% | LR: 0.000004
Epoch: 092 | Train loss: 0.9931 | Train acc: 50.38% | Val loss: 0.9915 | Val acc: 54.36% | LR: 0.000004
Epoch: 093 | Train loss: 0.9940 | Train acc: 50.85% | Val loss: 0.9915 | Val acc: 54.34% | LR: 0.000004
Epoch: 094 | Train loss: 0.9940 | Train acc: 50.97% | Val loss: 0.9914 | Val acc: 54.34% | LR: 0.000004
Epoch: 095 | Train loss: 0.9968 | Train acc: 50.60% | Val loss: 0.9914 | Val acc: 54.34% | LR: 0.000004
Epoch: 096 | Train loss: 0.9922 | Train acc: 50.98% | Val loss: 0.9914 | Val acc: 54.34% | LR: 0.000004
Epoch: 097 | Train loss: 1.0003 | Train acc: 50.31% | Val loss: 0.9914 | Val acc: 54.34% | LR: 0.000004
Epoch: 098 | Train loss: 1.0054 | Train acc: 50.94% | Val loss: 0.9914 | Val acc: 54.34% | LR: 0.000004
Epoch: 099 | Train loss: 0.9966 | Train acc: 51.02% | Val loss: 0.9914 | Val acc: 54.34% | LR: 0.000004
Epoch: 100 | Train loss: 0.9918 | Train acc: 50.54% | Val loss: 0.9914 | Val acc: 54.34% | LR: 0.000003
Epoch: 101 | Train loss: 0.9935 | Train acc: 50.87% | Val loss: 0.9914 | Val acc: 54.34% | LR: 0.000003
Epoch: 102 | Train loss: 0.9976 | Train acc: 51.05% | Val loss: 0.9914 | Val acc: 54.38% | LR: 0.000003
Epoch: 103 | Train loss: 0.9941 | Train acc: 50.81% | Val loss: 0.9914 | Val acc: 54.40% | LR: 0.000003
Epoch: 104 | Train loss: 0.9948 | Train acc: 50.46% | Val loss: 0.9914 | Val acc: 54.44% | LR: 0.000003
Epoch: 105 | Train loss: 0.9923 | Train acc: 51.19% | Val loss: 0.9913 | Val acc: 54.44% | LR: 0.000003
Epoch: 106 | Train loss: 0.9945 | Train acc: 50.83% | Val loss: 0.9914 | Val acc: 54.48% | LR: 0.000003
Epoch: 107 | Train loss: 0.9948 | Train acc: 50.92% | Val loss: 0.9914 | Val acc: 54.48% | LR: 0.000003
Epoch: 108 | Train loss: 0.9979 | Train acc: 50.19% | Val loss: 0.9913 | Val acc: 54.46% | LR: 0.000003
Epoch: 109 | Train loss: 0.9955 | Train acc: 50.82% | Val loss: 0.9913 | Val acc: 54.48% | LR: 0.000003
Epoch: 110 | Train loss: 0.9989 | Train acc: 50.58% | Val loss: 0.9913 | Val acc: 54.48% | LR: 0.000003
Epoch: 111 | Train loss: 0.9925 | Train acc: 50.81% | Val loss: 0.9913 | Val acc: 54.46% | LR: 0.000003
Epoch: 112 | Train loss: 0.9945 | Train acc: 50.38% | Val loss: 0.9913 | Val acc: 54.46% | LR: 0.000002
Epoch: 113 | Train loss: 0.9940 | Train acc: 50.23% | Val loss: 0.9913 | Val acc: 54.46% | LR: 0.000002
Epoch: 114 | Train loss: 0.9967 | Train acc: 50.19% | Val loss: 0.9913 | Val acc: 54.50% | LR: 0.000002
Epoch: 115 | Train loss: 0.9949 | Train acc: 50.91% | Val loss: 0.9913 | Val acc: 54.52% | LR: 0.000002
Epoch: 116 | Train loss: 0.9944 | Train acc: 51.16% | Val loss: 0.9913 | Val acc: 54.52% | LR: 0.000002
Epoch: 117 | Train loss: 0.9949 | Train acc: 50.52% | Val loss: 0.9913 | Val acc: 54.52% | LR: 0.000002
Epoch: 118 | Train loss: 0.9973 | Train acc: 50.37% | Val loss: 0.9913 | Val acc: 54.52% | LR: 0.000002

[I 2025-09-23 18:28:35,411] Trial 113 finished with value: 0.5452464580535888 and parameters: {'lr': 1.1341729211011958e-05, 'hidden_size': 64, 'dropout': 0.18726804885772794, 'weight_decay': 3.3915782020012484e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0005 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.05% | LR: 0.000011
Epoch: 001 | Train loss: 1.0006 | Train acc: 49.57% | Val loss: 0.9916 | Val acc: 54.05% | LR: 0.000011
Epoch: 002 | Train loss: 0.9996 | Train acc: 50.35% | Val loss: 0.9916 | Val acc: 54.11% | LR: 0.000011
Epoch: 003 | Train loss: 0.9993 | Train acc: 50.51% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000011
Epoch: 004 | Train loss: 0.9999 | Train acc: 50.16% | Val loss: 0.9917 | Val acc: 54.11% | LR: 0.000011
Epoch: 005 | Train loss: 0.9980 | Train acc: 50.86% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000011
Epoch: 006 | Train loss: 0.9987 | Train acc: 50.52% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000011
Epoch: 007 | Train loss: 0.9998 | Train acc: 49.98% | Val loss: 0.9918 | Val acc: 54.15% | LR: 0.000011
Epoch: 008 | Train loss: 1.0001 | Train acc: 49.72% | Val loss: 0.9919 | Val acc: 54.17% | LR: 0.000011
Epoch: 009 | Train loss: 0.9983 | Train acc: 50.61% | Val loss: 0.9919 | Val acc: 54.24% | LR: 0.000011
Epoch: 010 | Train loss: 0.9978 | Train acc: 50.78% | Val loss: 0.9920 | Val acc: 54.22% | LR: 0.000011
Epoch: 011 | Train loss: 0.9976 | Train acc: 50.87% | Val loss: 0.9919 | Val acc: 54.26% | LR: 0.000011
Epoch: 012 | Train loss: 0.9979 | Train acc: 50.69% | Val loss: 0.9919 | Val acc: 54.30% | LR: 0.000010
Epoch: 013 | Train loss: 0.9979 | Train acc: 50.43% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000010
Epoch: 014 | Train loss: 0.9984 | Train acc: 50.43% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000010
Epoch: 015 | Train loss: 0.9985 | Train acc: 50.16% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000010
Epoch: 016 | Train loss: 0.9983 | Train acc: 50.60% | Val loss: 0.9919 | Val acc: 54.28% | LR: 0.000010
Epoch: 017 | Train loss: 0.9977 | Train acc: 50.51% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000010
Epoch: 018 | Train loss: 0.9978 | Train acc: 50.24% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000010
Epoch: 019 | Train loss: 0.9980 | Train acc: 50.35% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000010
Epoch: 020 | Train loss: 1.0074 | Train acc: 51.13% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000010
Epoch: 021 | Train loss: 1.0550 | Train acc: 50.33% | Val loss: 0.9917 | Val acc: 54.28% | LR: 0.000010
Epoch: 022 | Train loss: 0.9982 | Train acc: 50.78% | Val loss: 0.9917 | Val acc: 54.30% | LR: 0.000010
Epoch: 023 | Train loss: 0.9984 | Train acc: 50.25% | Val loss: 0.9916 | Val acc: 54.32% | LR: 0.000010
Epoch: 024 | Train loss: 0.9980 | Train acc: 50.40% | Val loss: 0.9916 | Val acc: 54.34% | LR: 0.000010
Epoch: 025 | Train loss: 0.9986 | Train acc: 50.08% | Val loss: 0.9916 | Val acc: 54.36% | LR: 0.000010
Epoch: 026 | Train loss: 0.9981 | Train acc: 50.25% | Val loss: 0.9915 | Val acc: 54.36% | LR: 0.000010
Epoch: 027 | Train loss: 0.9976 | Train acc: 50.78% | Val loss: 0.9916 | Val acc: 54.36% | LR: 0.000010
Epoch: 028 | Train loss: 0.9972 | Train acc: 50.79% | Val loss: 0.9915 | Val acc: 54.40% | LR: 0.000010
Epoch: 029 | Train loss: 0.9973 | Train acc: 50.80% | Val loss: 0.9914 | Val acc: 54.42% | LR: 0.000010
Epoch: 030 | Train loss: 0.9983 | Train acc: 50.43% | Val loss: 0.9914 | Val acc: 54.40% | LR: 0.000010
Epoch: 031 | Train loss: 0.9987 | Train acc: 50.35% | Val loss: 0.9914 | Val acc: 54.48% | LR: 0.000010
Epoch: 032 | Train loss: 0.9963 | Train acc: 51.05% | Val loss: 0.9913 | Val acc: 54.38% | LR: 0.000010
Epoch: 033 | Train loss: 0.9984 | Train acc: 50.01% | Val loss: 0.9913 | Val acc: 54.36% | LR: 0.000009
Epoch: 034 | Train loss: 0.9964 | Train acc: 50.87% | Val loss: 0.9913 | Val acc: 54.31% | LR: 0.000009
Epoch: 035 | Train loss: 0.9983 | Train acc: 50.31% | Val loss: 0.9913 | Val acc: 54.34% | LR: 0.000009
Epoch: 036 | Train loss: 0.9974 | Train acc: 50.39% | Val loss: 0.9913 | Val acc: 54.28% | LR: 0.000009
Epoch: 037 | Train loss: 0.9973 | Train acc: 50.32% | Val loss: 0.9913 | Val acc: 54.22% | LR: 0.000009
Epoch: 038 | Train loss: 0.9982 | Train acc: 50.26% | Val loss: 0.9912 | Val acc: 54.30% | LR: 0.000009
Epoch: 039 | Train loss: 0.9961 | Train acc: 50.80% | Val loss: 0.9912 | Val acc: 54.34% | LR: 0.000009
Epoch: 040 | Train loss: 0.9971 | Train acc: 50.72% | Val loss: 0.9916 | Val acc: 54.34% | LR: 0.000009
Epoch: 041 | Train loss: 0.9977 | Train acc: 50.55% | Val loss: 0.9911 | Val acc: 54.29% | LR: 0.000009
Epoch: 042 | Train loss: 0.9988 | Train acc: 50.25% | Val loss: 0.9911 | Val acc: 54.37% | LR: 0.000009
Epoch: 043 | Train loss: 0.9977 | Train acc: 50.47% | Val loss: 0.9911 | Val acc: 54.28% | LR: 0.000009
Epoch: 044 | Train loss: 0.9987 | Train acc: 50.18% | Val loss: 0.9911 | Val acc: 54.38% | LR: 0.000009
Epoch: 045 | Train loss: 0.9968 | Train acc: 50.54% | Val loss: 0.9911 | Val acc: 54.25% | LR: 0.000009
Epoch: 046 | Train loss: 0.9973 | Train acc: 50.52% | Val loss: 0.9909 | Val acc: 54.25% | LR: 0.000008
Epoch: 047 | Train loss: 1.0007 | Train acc: 49.81% | Val loss: 0.9910 | Val acc: 54.25% | LR: 0.000008
Epoch: 048 | Train loss: 0.9988 | Train acc: 50.47% | Val loss: 0.9911 | Val acc: 54.25% | LR: 0.000008
Epoch: 049 | Train loss: 0.9987 | Train acc: 50.42% | Val loss: 0.9909 | Val acc: 54.35% | LR: 0.000008
Epoch: 050 | Train loss: 0.9993 | Train acc: 50.08% | Val loss: 0.9912 | Val acc: 54.29% | LR: 0.000008
Epoch: 051 | Train loss: 1.0005 | Train acc: 50.35% | Val loss: 0.9911 | Val acc: 54.33% | LR: 0.000008
Epoch: 052 | Train loss: 0.9986 | Train acc: 50.37% | Val loss: 0.9909 | Val acc: 54.33% | LR: 0.000008
Epoch: 053 | Train loss: 0.9996 | Train acc: 50.18% | Val loss: 0.9916 | Val acc: 54.35% | LR: 0.000008
Epoch: 054 | Train loss: 1.0008 | Train acc: 50.55% | Val loss: 0.9916 | Val acc: 54.29% | LR: 0.000008
Epoch: 055 | Train loss: 0.9982 | Train acc: 50.75% | Val loss: 0.9911 | Val acc: 54.35% | LR: 0.000008
Epoch: 056 | Train loss: 0.9979 | Train acc: 50.86% | Val loss: 0.9916 | Val acc: 54.43% | LR: 0.000008
Epoch: 057 | Train loss: 0.9992 | Train acc: 50.35% | Val loss: 0.9925 | Val acc: 54.40% | LR: 0.000008
Epoch: 058 | Train loss: 0.9992 | Train acc: 50.42% | Val loss: 0.9911 | Val acc: 54.40% | LR: 0.000007
Epoch: 059 | Train loss: 0.9977 | Train acc: 50.87% | Val loss: 0.9911 | Val acc: 54.44% | LR: 0.000007
Epoch: 060 | Train loss: 0.9981 | Train acc: 50.60% | Val loss: 0.9913 | Val acc: 54.35% | LR: 0.000007
Epoch: 061 | Train loss: 0.9990 | Train acc: 50.45% | Val loss: 0.9910 | Val acc: 54.40% | LR: 0.000007
Epoch: 062 | Train loss: 0.9989 | Train acc: 50.48% | Val loss: 0.9911 | Val acc: 54.39% | LR: 0.000007
Epoch: 063 | Train loss: 0.9986 | Train acc: 50.38% | Val loss: 0.9911 | Val acc: 54.40% | LR: 0.000007
Epoch: 064 | Train loss: 0.9983 | Train acc: 50.76% | Val loss: 0.9910 | Val acc: 54.38% | LR: 0.000007
Epoch: 065 | Train loss: 0.9976 | Train acc: 50.69% | Val loss: 0.9911 | Val acc: 54.38% | LR: 0.000007
Epoch: 066 | Train loss: 0.9989 | Train acc: 50.26% | Val loss: 0.9912 | Val acc: 54.46% | LR: 0.000007
Epoch: 067 | Train loss: 0.9964 | Train acc: 51.22% | Val loss: 0.9910 | Val acc: 54.52% | LR: 0.000007
Epoch: 068 | Train loss: 0.9976 | Train acc: 50.77% | Val loss: 0.9915 | Val acc: 54.52% | LR: 0.000006
Epoch: 069 | Train loss: 0.9988 | Train acc: 50.52% | Val loss: 0.9912 | Val acc: 54.49% | LR: 0.000006
Epoch: 070 | Train loss: 0.9973 | Train acc: 50.96% | Val loss: 0.9912 | Val acc: 54.55% | LR: 0.000006
Epoch: 071 | Train loss: 0.9979 | Train acc: 50.71% | Val loss: 0.9914 | Val acc: 54.55% | LR: 0.000006
Epoch: 072 | Train loss: 0.9980 | Train acc: 50.69% | Val loss: 0.9911 | Val acc: 54.60% | LR: 0.000006
Epoch: 073 | Train loss: 0.9997 | Train acc: 50.00% | Val loss: 0.9912 | Val acc: 54.49% | LR: 0.000006
Epoch: 074 | Train loss: 0.9963 | Train acc: 51.34% | Val loss: 0.9912 | Val acc: 54.46% | LR: 0.000006
Epoch: 075 | Train loss: 0.9967 | Train acc: 51.06% | Val loss: 0.9912 | Val acc: 54.47% | LR: 0.000006
Epoch: 076 | Train loss: 0.9987 | Train acc: 50.46% | Val loss: 0.9914 | Val acc: 54.50% | LR: 0.000006
Epoch: 077 | Train loss: 0.9986 | Train acc: 50.31% | Val loss: 0.9911 | Val acc: 54.54% | LR: 0.000006
Epoch: 078 | Train loss: 0.9978 | Train acc: 50.67% | Val loss: 0.9918 | Val acc: 54.48% | LR: 0.000005
Epoch: 079 | Train loss: 0.9980 | Train acc: 50.75% | Val loss: 0.9912 | Val acc: 54.51% | LR: 0.000005
Epoch: 080 | Train loss: 0.9971 | Train acc: 51.11% | Val loss: 0.9911 | Val acc: 54.51% | LR: 0.000005
Epoch: 081 | Train loss: 0.9980 | Train acc: 50.65% | Val loss: 1.0387 | Val acc: 54.46% | LR: 0.000005
Epoch: 082 | Train loss: 0.9965 | Train acc: 51.44% | Val loss: 0.9912 | Val acc: 54.44% | LR: 0.000005
Epoch: 083 | Train loss: 0.9986 | Train acc: 50.30% | Val loss: 0.9910 | Val acc: 54.52% | LR: 0.000005
Epoch: 084 | Train loss: 0.9975 | Train acc: 50.73% | Val loss: 0.9917 | Val acc: 54.52% | LR: 0.000005
Epoch: 085 | Train loss: 0.9990 | Train acc: 50.30% | Val loss: 0.9913 | Val acc: 54.58% | LR: 0.000005
Epoch: 086 | Train loss: 0.9980 | Train acc: 50.67% | Val loss: 0.9924 | Val acc: 54.64% | LR: 0.000005
Epoch: 087 | Train loss: 0.9978 | Train acc: 50.67% | Val loss: 0.9912 | Val acc: 54.58% | LR: 0.000005
Epoch: 088 | Train loss: 0.9976 | Train acc: 50.67% | Val loss: 0.9913 | Val acc: 54.58% | LR: 0.000004
Epoch: 089 | Train loss: 0.9979 | Train acc: 50.58% | Val loss: 0.9913 | Val acc: 54.60% | LR: 0.000004
Epoch: 090 | Train loss: 0.9977 | Train acc: 50.78% | Val loss: 0.9914 | Val acc: 54.70% | LR: 0.000004
Epoch: 091 | Train loss: 0.9975 | Train acc: 50.96% | Val loss: 0.9916 | Val acc: 54.66% | LR: 0.000004
Epoch: 092 | Train loss: 0.9973 | Train acc: 50.59% | Val loss: 0.9914 | Val acc: 54.66% | LR: 0.000004
Epoch: 093 | Train loss: 0.9968 | Train acc: 51.03% | Val loss: 0.9915 | Val acc: 54.70% | LR: 0.000004
Epoch: 094 | Train loss: 0.9964 | Train acc: 51.21% | Val loss: 0.9914 | Val acc: 54.66% | LR: 0.000004
Epoch: 095 | Train loss: 0.9978 | Train acc: 50.77% | Val loss: 0.9915 | Val acc: 54.58% | LR: 0.000004
Epoch: 096 | Train loss: 0.9971 | Train acc: 50.96% | Val loss: 0.9913 | Val acc: 54.60% | LR: 0.000004
Epoch: 097 | Train loss: 0.9976 | Train acc: 50.68% | Val loss: 0.9913 | Val acc: 54.58% | LR: 0.000004
Epoch: 098 | Train loss: 0.9983 | Train acc: 50.94% | Val loss: 0.9915 | Val acc: 54.50% | LR: 0.000004
Epoch: 099 | Train loss: 0.9975 | Train acc: 51.04% | Val loss: 0.9914 | Val acc: 54.52% | LR: 0.000003
Epoch: 100 | Train loss: 0.9977 | Train acc: 50.49% | Val loss: 0.9913 | Val acc: 54.54% | LR: 0.000003
Epoch: 101 | Train loss: 0.9973 | Train acc: 50.95% | Val loss: 0.9913 | Val acc: 54.52% | LR: 0.000003
Epoch: 102 | Train loss: 0.9969 | Train acc: 51.03% | Val loss: 0.9913 | Val acc: 54.57% | LR: 0.000003
Epoch: 103 | Train loss: 0.9973 | Train acc: 50.86% | Val loss: 0.9913 | Val acc: 54.57% | LR: 0.000003
Epoch: 104 | Train loss: 0.9980 | Train acc: 50.59% | Val loss: 0.9913 | Val acc: 54.57% | LR: 0.000003
Epoch: 105 | Train loss: 0.9969 | Train acc: 51.13% | Val loss: 0.9913 | Val acc: 54.55% | LR: 0.000003
Epoch: 106 | Train loss: 0.9972 | Train acc: 50.86% | Val loss: 0.9914 | Val acc: 54.56% | LR: 0.000003
Epoch: 107 | Train loss: 0.9971 | Train acc: 51.03% | Val loss: 0.9913 | Val acc: 54.56% | LR: 0.000003
Epoch: 108 | Train loss: 0.9989 | Train acc: 50.23% | Val loss: 0.9913 | Val acc: 54.54% | LR: 0.000003
Epoch: 109 | Train loss: 0.9973 | Train acc: 50.86% | Val loss: 0.9913 | Val acc: 54.52% | LR: 0.000003
Epoch: 110 | Train loss: 0.9972 | Train acc: 50.58% | Val loss: 0.9913 | Val acc: 54.52% | LR: 0.000003
Epoch: 111 | Train loss: 0.9968 | Train acc: 50.85% | Val loss: 0.9913 | Val acc: 54.56% | LR: 0.000002
Epoch: 112 | Train loss: 0.9977 | Train acc: 50.31% | Val loss: 0.9913 | Val acc: 54.54% | LR: 0.000002
Epoch: 113 | Train loss: 0.9976 | Train acc: 50.40% | Val loss: 0.9913 | Val acc: 54.49% | LR: 0.000002
Epoch: 114 | Train loss: 0.9977 | Train acc: 50.32% | Val loss: 0.9913 | Val acc: 54.49% | LR: 0.000002
Epoch: 115 | Train loss: 0.9970 | Train acc: 51.02% | Val loss: 0.9913 | Val acc: 54.49% | LR: 0.000002
Epoch: 116 | Train loss: 0.9964 | Train acc: 51.21% | Val loss: 0.9913 | Val acc: 54.49% | LR: 0.000002
Epoch: 117 | Train loss: 0.9980 | Train acc: 50.42% | Val loss: 0.9913 | Val acc: 54.54% | LR: 0.000002
Epoch: 118 | Train loss: 0.9977 | Train acc: 50.61% | Val loss: 0.9913 | Val acc: 54.54% | LR: 0.000002
Epoch: 119 | Train loss: 0.9978 | Train acc: 50.77% | Val loss: 0.9913 | Val acc: 54.52% | LR: 0.000002
Epoch: 120 | Train loss: 0.9978 | Train acc: 50.60% | Val loss: 0.9913 | Val acc: 54.50% | LR: 0.000002
Epoch: 121 | Train loss: 0.9968 | Train acc: 51.04% | Val loss: 0.9913 | Val acc: 54.52% | LR: 0.000002
Epoch: 122 | Train loss: 0.9972 | Train acc: 50.86% | Val loss: 0.9913 | Val acc: 54.52% | LR: 0.000002
Epoch: 123 | Train loss: 0.9967 | Train acc: 50.94% | Val loss: 0.9913 | Val acc: 54.48% | LR: 0.000002
Epoch: 124 | Train loss: 0.9970 | Train acc: 51.12% | Val loss: 0.9913 | Val acc: 54.48% | LR: 0.000002
Epoch: 125 | Train loss: 0.9969 | Train acc: 51.02% | Val loss: 0.9913 | Val acc: 54.48% | LR: 0.000002
Epoch: 126 | Train loss: 0.9981 | Train acc: 50.23% | Val loss: 0.9913 | Val acc: 54.49% | LR: 0.000002
Epoch: 127 | Train loss: 0.9971 | Train acc: 50.67% | Val loss: 0.9913 | Val acc: 54.49% | LR: 0.000002
Epoch: 128 | Train loss: 0.9980 | Train acc: 50.30% | Val loss: 0.9913 | Val acc: 54.49% | LR: 0.000001
Epoch: 129 | Train loss: 0.9973 | Train acc: 50.66% | Val loss: 0.9913 | Val acc: 54.49% | LR: 0.000001
Epoch: 130 | Train loss: 0.9980 | Train acc: 50.66% | Val loss: 0.9913 | Val acc: 54.47% | LR: 0.000001
Epoch: 131 | Train loss: 0.9970 | Train acc: 50.84% | Val loss: 0.9913 | Val acc: 54.47% | LR: 0.000001
Epoch: 132 | Train loss: 0.9975 | Train acc: 50.40% | Val loss: 0.9913 | Val acc: 54.49% | LR: 0.000001
Epoch: 133 | Train loss: 0.9980 | Train acc: 50.48% | Val loss: 0.9913 | Val acc: 54.53% | LR: 0.000001
Epoch: 134 | Train loss: 0.9972 | Train acc: 50.85% | Val loss: 0.9913 | Val acc: 54.53% | LR: 0.000001
Epoch: 135 | Train loss: 0.9963 | Train acc: 50.77% | Val loss: 0.9913 | Val acc: 54.61% | LR: 0.000001
Epoch: 136 | Train loss: 0.9964 | Train acc: 51.02% | Val loss: 0.9913 | Val acc: 54.57% | LR: 0.000001
Epoch: 137 | Train loss: 0.9981 | Train acc: 50.32% | Val loss: 0.9913 | Val acc: 54.57% | LR: 0.000001
Epoch: 138 | Train loss: 0.9982 | Train acc: 50.41% | Val loss: 0.9913 | Val acc: 54.57% | LR: 0.000001
Epoch: 139 | Train loss: 0.9977 | Train acc: 50.59% | Val loss: 0.9913 | Val acc: 54.57% | LR: 0.000001
Epoch: 140 | Train loss: 0.9964 | Train acc: 51.03% | Val loss: 0.9913 | Val acc: 54.53% | LR: 0.000001
Epoch: 141 | Train loss: 0.9969 | Train acc: 50.87% | Val loss: 0.9913 | Val acc: 54.49% | LR: 0.000001
Epoch: 142 | Train loss: 0.9969 | Train acc: 50.93% | Val loss: 0.9913 | Val acc: 54.49% | LR: 0.000001

[I 2025-09-23 18:30:32,687] Trial 114 finished with value: 0.5447021842002868 and parameters: {'lr': 1.0655359241278108e-05, 'hidden_size': 64, 'dropout': 0.19508825829342566, 'weight_decay': 4.937584063912242e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0005 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.05% | LR: 0.000011
Epoch: 001 | Train loss: 1.0007 | Train acc: 49.60% | Val loss: 0.9916 | Val acc: 54.07% | LR: 0.000011
Epoch: 002 | Train loss: 0.9995 | Train acc: 50.36% | Val loss: 0.9916 | Val acc: 54.11% | LR: 0.000011
Epoch: 003 | Train loss: 0.9993 | Train acc: 50.46% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000011
Epoch: 004 | Train loss: 0.9999 | Train acc: 50.14% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000011
Epoch: 005 | Train loss: 0.9979 | Train acc: 50.87% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000011
Epoch: 006 | Train loss: 0.9987 | Train acc: 50.52% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000011
Epoch: 007 | Train loss: 0.9997 | Train acc: 49.98% | Val loss: 0.9918 | Val acc: 54.17% | LR: 0.000011
Epoch: 008 | Train loss: 1.0001 | Train acc: 49.72% | Val loss: 0.9919 | Val acc: 54.20% | LR: 0.000011
Epoch: 009 | Train loss: 0.9982 | Train acc: 50.60% | Val loss: 0.9919 | Val acc: 54.26% | LR: 0.000011
Epoch: 010 | Train loss: 0.9978 | Train acc: 50.78% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000011
Epoch: 011 | Train loss: 0.9975 | Train acc: 50.87% | Val loss: 0.9919 | Val acc: 54.34% | LR: 0.000011
Epoch: 012 | Train loss: 0.9979 | Train acc: 50.69% | Val loss: 0.9919 | Val acc: 54.34% | LR: 0.000011
Epoch: 013 | Train loss: 0.9978 | Train acc: 50.43% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000011
Epoch: 014 | Train loss: 0.9984 | Train acc: 50.43% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000011
Epoch: 015 | Train loss: 0.9984 | Train acc: 50.16% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000011
Epoch: 016 | Train loss: 0.9982 | Train acc: 50.60% | Val loss: 0.9919 | Val acc: 54.28% | LR: 0.000011
Epoch: 017 | Train loss: 0.9975 | Train acc: 50.51% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000011
Epoch: 018 | Train loss: 0.9975 | Train acc: 50.24% | Val loss: 0.9917 | Val acc: 54.28% | LR: 0.000011
Epoch: 019 | Train loss: 1.0436 | Train acc: 50.19% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000011
Epoch: 020 | Train loss: 0.9965 | Train acc: 51.11% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000011
Epoch: 021 | Train loss: 0.9983 | Train acc: 50.52% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000011
Epoch: 022 | Train loss: 0.9971 | Train acc: 50.90% | Val loss: 0.9916 | Val acc: 54.36% | LR: 0.000011
Epoch: 023 | Train loss: 0.9989 | Train acc: 50.30% | Val loss: 0.9916 | Val acc: 54.38% | LR: 0.000011
Epoch: 024 | Train loss: 0.9988 | Train acc: 50.40% | Val loss: 0.9916 | Val acc: 54.40% | LR: 0.000011
Epoch: 025 | Train loss: 1.0001 | Train acc: 49.99% | Val loss: 0.9916 | Val acc: 54.42% | LR: 0.000010
Epoch: 026 | Train loss: 0.9990 | Train acc: 50.28% | Val loss: 0.9915 | Val acc: 54.40% | LR: 0.000010
Epoch: 027 | Train loss: 0.9973 | Train acc: 50.80% | Val loss: 0.9916 | Val acc: 54.45% | LR: 0.000010
Epoch: 028 | Train loss: 0.9965 | Train acc: 50.78% | Val loss: 0.9915 | Val acc: 54.32% | LR: 0.000010
Epoch: 029 | Train loss: 0.9977 | Train acc: 50.78% | Val loss: 0.9917 | Val acc: 54.30% | LR: 0.000010
Epoch: 030 | Train loss: 1.0027 | Train acc: 50.39% | Val loss: 0.9912 | Val acc: 54.33% | LR: 0.000010
Epoch: 031 | Train loss: 1.0146 | Train acc: 50.13% | Val loss: 0.9916 | Val acc: 54.20% | LR: 0.000010
Epoch: 032 | Train loss: 1.0316 | Train acc: 50.56% | Val loss: 0.9915 | Val acc: 54.24% | LR: 0.000010
Epoch: 033 | Train loss: 1.0474 | Train acc: 49.55% | Val loss: 0.9914 | Val acc: 54.26% | LR: 0.000010
Epoch: 034 | Train loss: nan | Train acc: 1.99% | Val loss: nan | Val acc: 0.00% | LR: 0.000010
Epoch: 035 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000010
Epoch: 036 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000010
Epoch: 037 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000010
Epoch: 038 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000010
Epoch: 039 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000010
Epoch: 040 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000009
Epoch: 041 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000009
Epoch: 042 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000009
Epoch: 043 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000009
Epoch: 044 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000009
Epoch: 045 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000009
Epoch: 046 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000009
Epoch: 047 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000009
Epoch: 048 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000009
Epoch: 049 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000009
Epoch: 050 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000009
Epoch: 051 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000008
Epoch: 052 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000008
Epoch: 053 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000008
Epoch: 054 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000008
Epoch: 055 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000008
Epoch: 056 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000008
Epoch: 057 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000008
Epoch: 058 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000008
Epoch: 059 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000008
Epoch: 060 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000008
Epoch: 061 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000007
Epoch: 062 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000007
Epoch: 063 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000007
Epoch: 064 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000007
Epoch: 065 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000007
Epoch: 066 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000007
Epoch: 067 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000007
Epoch: 068 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000007
Epoch: 069 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000007
Epoch: 070 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000007
Epoch: 071 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000006
Epoch: 072 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000006
Epoch: 073 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000006
Epoch: 074 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000006
Epoch: 075 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000006
Epoch: 076 | Train loss: nan | Train acc: 0.00% | Val loss: nan | Val acc: 0.00% | LR: 0.000006

[I 2025-09-23 18:31:35,135] Trial 115 finished with value: 0.0 and parameters: {'lr': 1.1208195508304202e-05, 'hidden_size': 64, 'dropout': 0.1843849987581015, 'weight_decay': 5.649594132903254e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 0.9994 | Train acc: 50.40% | Val loss: 1.0086 | Val acc: 46.09% | LR: 0.000010
Epoch: 001 | Train loss: 0.9994 | Train acc: 50.77% | Val loss: 1.0152 | Val acc: 46.28% | LR: 0.000010
Epoch: 002 | Train loss: 1.0000 | Train acc: 49.44% | Val loss: 1.0060 | Val acc: 46.42% | LR: 0.000010
Epoch: 003 | Train loss: 0.9988 | Train acc: 50.17% | Val loss: 1.0058 | Val acc: 46.26% | LR: 0.000010
Epoch: 004 | Train loss: 0.9987 | Train acc: 50.68% | Val loss: 1.0067 | Val acc: 46.16% | LR: 0.000010
Epoch: 005 | Train loss: 0.9987 | Train acc: 50.64% | Val loss: 1.0109 | Val acc: 46.02% | LR: 0.000010
Epoch: 006 | Train loss: 0.9989 | Train acc: 50.14% | Val loss: 1.0069 | Val acc: 46.34% | LR: 0.000010
Epoch: 007 | Train loss: 0.9994 | Train acc: 50.58% | Val loss: 1.0063 | Val acc: 46.08% | LR: 0.000010
Epoch: 008 | Train loss: 0.9993 | Train acc: 50.22% | Val loss: 1.0061 | Val acc: 46.08% | LR: 0.000010
Epoch: 009 | Train loss: 1.0007 | Train acc: 50.93% | Val loss: 1.0079 | Val acc: 46.12% | LR: 0.000010
Epoch: 010 | Train loss: 0.9997 | Train acc: 49.81% | Val loss: 1.0063 | Val acc: 46.10% | LR: 0.000010
Epoch: 011 | Train loss: 0.9996 | Train acc: 50.11% | Val loss: 1.0089 | Val acc: 46.09% | LR: 0.000010
Epoch: 012 | Train loss: 0.9993 | Train acc: 50.58% | Val loss: 1.0067 | Val acc: 46.17% | LR: 0.000010
Epoch: 013 | Train loss: 0.9991 | Train acc: 50.40% | Val loss: 1.0060 | Val acc: 46.24% | LR: 0.000010
Epoch: 014 | Train loss: 0.9983 | Train acc: 50.84% | Val loss: 1.0059 | Val acc: 46.30% | LR: 0.000010
Epoch: 015 | Train loss: 0.9989 | Train acc: 50.22% | Val loss: 1.0081 | Val acc: 46.22% | LR: 0.000010
Epoch: 016 | Train loss: 0.9986 | Train acc: 50.82% | Val loss: 1.0065 | Val acc: 46.08% | LR: 0.000010
Epoch: 017 | Train loss: 0.9982 | Train acc: 50.87% | Val loss: 1.0059 | Val acc: 45.96% | LR: 0.000010
Epoch: 018 | Train loss: 0.9990 | Train acc: 50.15% | Val loss: 1.0070 | Val acc: 45.96% | LR: 0.000010
Epoch: 019 | Train loss: 0.9994 | Train acc: 50.78% | Val loss: 1.0087 | Val acc: 46.16% | LR: 0.000010
Epoch: 020 | Train loss: 0.9984 | Train acc: 50.73% | Val loss: 1.0067 | Val acc: 46.16% | LR: 0.000010
Epoch: 021 | Train loss: 0.9987 | Train acc: 50.41% | Val loss: 1.0069 | Val acc: 46.02% | LR: 0.000010
Epoch: 022 | Train loss: 0.9991 | Train acc: 50.25% | Val loss: 1.0076 | Val acc: 46.10% | LR: 0.000010
Epoch: 023 | Train loss: 0.9985 | Train acc: 50.32% | Val loss: 1.0061 | Val acc: 46.16% | LR: 0.000009
Epoch: 024 | Train loss: 0.9984 | Train acc: 50.78% | Val loss: 1.0411 | Val acc: 46.08% | LR: 0.000009
Epoch: 025 | Train loss: 0.9978 | Train acc: 50.86% | Val loss: 1.0059 | Val acc: 46.20% | LR: 0.000009
Epoch: 026 | Train loss: 0.9983 | Train acc: 50.58% | Val loss: 1.0063 | Val acc: 46.16% | LR: 0.000009
Epoch: 027 | Train loss: 0.9983 | Train acc: 50.50% | Val loss: 1.0070 | Val acc: 46.10% | LR: 0.000009
Epoch: 028 | Train loss: 0.9999 | Train acc: 50.13% | Val loss: 1.0066 | Val acc: 46.14% | LR: 0.000009
Epoch: 029 | Train loss: 0.9979 | Train acc: 50.68% | Val loss: 1.0065 | Val acc: 46.17% | LR: 0.000009
Epoch: 030 | Train loss: 0.9974 | Train acc: 50.92% | Val loss: 1.0056 | Val acc: 46.24% | LR: 0.000009
Epoch: 031 | Train loss: 0.9985 | Train acc: 50.40% | Val loss: 1.0076 | Val acc: 46.18% | LR: 0.000009
Epoch: 032 | Train loss: 0.9980 | Train acc: 50.51% | Val loss: 1.0062 | Val acc: 46.14% | LR: 0.000009
Epoch: 033 | Train loss: 1.0000 | Train acc: 49.81% | Val loss: 1.0065 | Val acc: 46.16% | LR: 0.000009
Epoch: 034 | Train loss: 0.9987 | Train acc: 50.15% | Val loss: 1.0064 | Val acc: 46.09% | LR: 0.000009
Epoch: 035 | Train loss: 0.9987 | Train acc: 50.22% | Val loss: 1.0071 | Val acc: 46.15% | LR: 0.000009
Epoch: 036 | Train loss: 0.9981 | Train acc: 50.50% | Val loss: 1.0066 | Val acc: 46.08% | LR: 0.000009
Epoch: 037 | Train loss: 0.9973 | Train acc: 50.78% | Val loss: 1.0075 | Val acc: 45.98% | LR: 0.000009
Epoch: 038 | Train loss: 0.9995 | Train acc: 49.97% | Val loss: 1.0089 | Val acc: 46.14% | LR: 0.000009
Epoch: 039 | Train loss: 0.9992 | Train acc: 50.20% | Val loss: 1.0068 | Val acc: 46.14% | LR: 0.000009
Epoch: 040 | Train loss: 0.9975 | Train acc: 50.78% | Val loss: 1.0215 | Val acc: 46.08% | LR: 0.000008
Epoch: 041 | Train loss: 0.9983 | Train acc: 50.39% | Val loss: 1.0066 | Val acc: 46.10% | LR: 0.000008
Epoch: 042 | Train loss: 0.9976 | Train acc: 50.49% | Val loss: 1.0071 | Val acc: 46.15% | LR: 0.000008
Epoch: 043 | Train loss: 0.9975 | Train acc: 50.61% | Val loss: 1.0064 | Val acc: 46.07% | LR: 0.000008
Epoch: 044 | Train loss: 0.9984 | Train acc: 50.34% | Val loss: 1.0073 | Val acc: 46.05% | LR: 0.000008
Epoch: 045 | Train loss: 0.9979 | Train acc: 50.59% | Val loss: 1.0066 | Val acc: 45.99% | LR: 0.000008
Epoch: 046 | Train loss: 0.9966 | Train acc: 51.03% | Val loss: 1.0061 | Val acc: 46.09% | LR: 0.000008
Epoch: 047 | Train loss: 0.9992 | Train acc: 50.03% | Val loss: 1.0062 | Val acc: 46.07% | LR: 0.000008
Epoch: 048 | Train loss: 0.9969 | Train acc: 50.69% | Val loss: 1.0062 | Val acc: 46.03% | LR: 0.000008
Epoch: 049 | Train loss: 0.9977 | Train acc: 50.49% | Val loss: 1.0059 | Val acc: 46.04% | LR: 0.000008
Epoch: 050 | Train loss: 0.9989 | Train acc: 50.14% | Val loss: 1.0061 | Val acc: 45.96% | LR: 0.000008
Epoch: 051 | Train loss: 0.9966 | Train acc: 50.77% | Val loss: 1.0074 | Val acc: 45.98% | LR: 0.000008

[I 2025-09-23 18:32:23,616] Trial 116 finished with value: 0.4589575529098511 and parameters: {'lr': 1.004813473606717e-05, 'hidden_size': 67, 'dropout': 0.19538669368393696, 'weight_decay': 4.252407461182044e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0018 | Train acc: 49.62% | Val loss: 1.0009 | Val acc: 48.80% | LR: 0.000012
Epoch: 001 | Train loss: 1.0028 | Train acc: 49.17% | Val loss: 1.0006 | Val acc: 48.88% | LR: 0.000012
Epoch: 002 | Train loss: 1.0008 | Train acc: 50.24% | Val loss: 1.0006 | Val acc: 48.92% | LR: 0.000012
Epoch: 003 | Train loss: 1.0018 | Train acc: 49.28% | Val loss: 1.0014 | Val acc: 48.98% | LR: 0.000012
Epoch: 004 | Train loss: 1.0020 | Train acc: 49.66% | Val loss: 1.0006 | Val acc: 48.88% | LR: 0.000012
Epoch: 005 | Train loss: 1.0012 | Train acc: 49.79% | Val loss: 1.0006 | Val acc: 48.98% | LR: 0.000012
Epoch: 006 | Train loss: 1.0009 | Train acc: 50.07% | Val loss: 1.0006 | Val acc: 48.98% | LR: 0.000012
Epoch: 007 | Train loss: 1.0012 | Train acc: 49.53% | Val loss: 1.0007 | Val acc: 48.94% | LR: 0.000012
Epoch: 008 | Train loss: 1.0018 | Train acc: 49.56% | Val loss: 1.0006 | Val acc: 48.78% | LR: 0.000012
Epoch: 009 | Train loss: 1.0016 | Train acc: 49.65% | Val loss: 1.0007 | Val acc: 48.86% | LR: 0.000012
Epoch: 010 | Train loss: 1.0012 | Train acc: 49.65% | Val loss: 1.0007 | Val acc: 48.72% | LR: 0.000012
Epoch: 011 | Train loss: 1.0011 | Train acc: 49.73% | Val loss: 1.0007 | Val acc: 48.70% | LR: 0.000012
Epoch: 012 | Train loss: 1.0011 | Train acc: 49.55% | Val loss: 1.0007 | Val acc: 48.76% | LR: 0.000012
Epoch: 013 | Train loss: 1.0014 | Train acc: 49.63% | Val loss: 1.0019 | Val acc: 48.74% | LR: 0.000012
Epoch: 014 | Train loss: 1.0011 | Train acc: 49.77% | Val loss: 1.0003 | Val acc: 48.70% | LR: 0.000012
Epoch: 015 | Train loss: 1.0005 | Train acc: 50.10% | Val loss: 1.0006 | Val acc: 48.57% | LR: 0.000012
Epoch: 016 | Train loss: 1.0009 | Train acc: 49.64% | Val loss: 1.0007 | Val acc: 48.70% | LR: 0.000012
Epoch: 017 | Train loss: 1.0016 | Train acc: 49.57% | Val loss: 1.0012 | Val acc: 48.69% | LR: 0.000012
Epoch: 018 | Train loss: 1.0009 | Train acc: 49.75% | Val loss: 1.0007 | Val acc: 48.71% | LR: 0.000012
Epoch: 019 | Train loss: 1.0010 | Train acc: 49.66% | Val loss: 1.0003 | Val acc: 48.73% | LR: 0.000012
Epoch: 020 | Train loss: 1.0017 | Train acc: 49.65% | Val loss: 1.0006 | Val acc: 48.73% | LR: 0.000012
Epoch: 021 | Train loss: 1.0010 | Train acc: 49.79% | Val loss: 1.0004 | Val acc: 48.73% | LR: 0.000012
Epoch: 022 | Train loss: 1.0006 | Train acc: 49.02% | Val loss: 1.0007 | Val acc: 48.69% | LR: 0.000012
Epoch: 023 | Train loss: 1.0007 | Train acc: 49.55% | Val loss: 1.0006 | Val acc: 48.69% | LR: 0.000012
Epoch: 024 | Train loss: 1.0006 | Train acc: 50.06% | Val loss: 1.0006 | Val acc: 48.73% | LR: 0.000012
Epoch: 025 | Train loss: 1.0007 | Train acc: 49.52% | Val loss: 1.0008 | Val acc: 48.67% | LR: 0.000012
Epoch: 026 | Train loss: 1.0004 | Train acc: 49.86% | Val loss: 1.0025 | Val acc: 48.61% | LR: 0.000012
Epoch: 027 | Train loss: 1.0011 | Train acc: 49.57% | Val loss: 1.0005 | Val acc: 48.71% | LR: 0.000012
Epoch: 028 | Train loss: 1.0009 | Train acc: 49.60% | Val loss: 1.0005 | Val acc: 48.63% | LR: 0.000011
Epoch: 029 | Train loss: 1.0004 | Train acc: 49.92% | Val loss: 1.0004 | Val acc: 48.67% | LR: 0.000011
Epoch: 030 | Train loss: 1.0005 | Train acc: 50.31% | Val loss: 1.0005 | Val acc: 48.67% | LR: 0.000011
Epoch: 031 | Train loss: 1.0007 | Train acc: 50.31% | Val loss: 1.0003 | Val acc: 48.71% | LR: 0.000011
Epoch: 032 | Train loss: 0.9998 | Train acc: 50.77% | Val loss: 1.0004 | Val acc: 48.67% | LR: 0.000011
Epoch: 033 | Train loss: 1.0001 | Train acc: 50.70% | Val loss: 1.0007 | Val acc: 48.49% | LR: 0.000011
Epoch: 034 | Train loss: 1.0004 | Train acc: 50.57% | Val loss: 1.0011 | Val acc: 48.53% | LR: 0.000011
Epoch: 035 | Train loss: 1.0010 | Train acc: 50.12% | Val loss: 1.0005 | Val acc: 48.65% | LR: 0.000011
Epoch: 036 | Train loss: 1.0004 | Train acc: 50.70% | Val loss: 1.0008 | Val acc: 48.70% | LR: 0.000011
Epoch: 037 | Train loss: 1.0006 | Train acc: 50.15% | Val loss: 1.0003 | Val acc: 48.65% | LR: 0.000011
Epoch: 038 | Train loss: 1.0005 | Train acc: 48.99% | Val loss: 1.0005 | Val acc: 48.73% | LR: 0.000011
Epoch: 039 | Train loss: 1.0004 | Train acc: 49.36% | Val loss: 1.0005 | Val acc: 48.73% | LR: 0.000011
Epoch: 040 | Train loss: 1.0006 | Train acc: 49.72% | Val loss: 1.0004 | Val acc: 48.84% | LR: 0.000010
Epoch: 041 | Train loss: 1.0000 | Train acc: 49.96% | Val loss: 1.0002 | Val acc: 48.86% | LR: 0.000010
Epoch: 042 | Train loss: 1.0001 | Train acc: 50.25% | Val loss: 1.0002 | Val acc: 48.94% | LR: 0.000010
Epoch: 043 | Train loss: 1.0003 | Train acc: 50.28% | Val loss: 1.0004 | Val acc: 48.90% | LR: 0.000010
Epoch: 044 | Train loss: 1.0007 | Train acc: 50.52% | Val loss: 1.0002 | Val acc: 48.92% | LR: 0.000010
Epoch: 045 | Train loss: 0.9999 | Train acc: 50.40% | Val loss: 1.0007 | Val acc: 48.82% | LR: 0.000010
Epoch: 046 | Train loss: 1.0001 | Train acc: 50.48% | Val loss: 1.0004 | Val acc: 48.86% | LR: 0.000010
Epoch: 047 | Train loss: 1.0004 | Train acc: 50.30% | Val loss: 1.0009 | Val acc: 48.78% | LR: 0.000010
Epoch: 048 | Train loss: 1.0002 | Train acc: 50.38% | Val loss: 1.0009 | Val acc: 48.75% | LR: 0.000010
Epoch: 049 | Train loss: 1.0002 | Train acc: 50.21% | Val loss: 1.0005 | Val acc: 48.83% | LR: 0.000010
Epoch: 050 | Train loss: 1.0010 | Train acc: 50.25% | Val loss: 1.0005 | Val acc: 48.86% | LR: 0.000010
Epoch: 051 | Train loss: 1.0001 | Train acc: 50.47% | Val loss: 1.0004 | Val acc: 48.78% | LR: 0.000009
Epoch: 052 | Train loss: 0.9996 | Train acc: 50.64% | Val loss: 1.0012 | Val acc: 48.72% | LR: 0.000009

[I 2025-09-23 18:33:07,719] Trial 117 finished with value: 0.4878284394741058 and parameters: {'lr': 1.248190329022992e-05, 'hidden_size': 71, 'dropout': 0.17050306948268426, 'weight_decay': 3.528995142183118e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 0.9995 | Train acc: 50.40% | Val loss: 1.0063 | Val acc: 46.04% | LR: 0.000014
Epoch: 001 | Train loss: 0.9993 | Train acc: 50.27% | Val loss: 1.0076 | Val acc: 45.97% | LR: 0.000014
Epoch: 002 | Train loss: 1.0001 | Train acc: 49.77% | Val loss: 1.0135 | Val acc: 45.96% | LR: 0.000014
Epoch: 003 | Train loss: 0.9987 | Train acc: 50.67% | Val loss: 1.0062 | Val acc: 46.09% | LR: 0.000014
Epoch: 004 | Train loss: 0.9987 | Train acc: 50.95% | Val loss: 1.0069 | Val acc: 46.10% | LR: 0.000014
Epoch: 005 | Train loss: 0.9988 | Train acc: 50.65% | Val loss: 1.0070 | Val acc: 46.12% | LR: 0.000014
Epoch: 006 | Train loss: 0.9989 | Train acc: 50.15% | Val loss: 1.0063 | Val acc: 46.15% | LR: 0.000014
Epoch: 007 | Train loss: 0.9987 | Train acc: 50.59% | Val loss: 1.0064 | Val acc: 46.15% | LR: 0.000014
Epoch: 008 | Train loss: 0.9993 | Train acc: 50.22% | Val loss: 1.0066 | Val acc: 46.12% | LR: 0.000014
Epoch: 009 | Train loss: 0.9982 | Train acc: 50.94% | Val loss: 1.0070 | Val acc: 46.12% | LR: 0.000014
Epoch: 010 | Train loss: 0.9996 | Train acc: 49.89% | Val loss: 1.0065 | Val acc: 46.09% | LR: 0.000014
Epoch: 011 | Train loss: 0.9994 | Train acc: 50.15% | Val loss: 1.0077 | Val acc: 46.08% | LR: 0.000014
Epoch: 012 | Train loss: 0.9991 | Train acc: 50.59% | Val loss: 1.0065 | Val acc: 46.05% | LR: 0.000014
Epoch: 013 | Train loss: 0.9993 | Train acc: 50.42% | Val loss: 1.0062 | Val acc: 46.09% | LR: 0.000014
Epoch: 014 | Train loss: 0.9978 | Train acc: 50.86% | Val loss: 1.0065 | Val acc: 46.07% | LR: 0.000014
Epoch: 015 | Train loss: 0.9988 | Train acc: 50.25% | Val loss: 1.0065 | Val acc: 46.07% | LR: 0.000014
Epoch: 016 | Train loss: 0.9981 | Train acc: 50.86% | Val loss: 1.0065 | Val acc: 46.07% | LR: 0.000013
Epoch: 017 | Train loss: 0.9979 | Train acc: 50.85% | Val loss: 1.0066 | Val acc: 46.05% | LR: 0.000013
Epoch: 018 | Train loss: 0.9990 | Train acc: 50.14% | Val loss: 1.0066 | Val acc: 46.05% | LR: 0.000013
Epoch: 019 | Train loss: 0.9981 | Train acc: 50.75% | Val loss: 1.0065 | Val acc: 46.05% | LR: 0.000013
Epoch: 020 | Train loss: 0.9978 | Train acc: 50.76% | Val loss: 1.0066 | Val acc: 46.03% | LR: 0.000013
Epoch: 021 | Train loss: 0.9984 | Train acc: 50.41% | Val loss: 1.0065 | Val acc: 46.03% | LR: 0.000013
Epoch: 022 | Train loss: 0.9989 | Train acc: 50.22% | Val loss: 1.0065 | Val acc: 46.01% | LR: 0.000013
Epoch: 023 | Train loss: 0.9982 | Train acc: 50.32% | Val loss: 1.0064 | Val acc: 46.03% | LR: 0.000013
Epoch: 024 | Train loss: 0.9977 | Train acc: 50.76% | Val loss: 1.0066 | Val acc: 46.09% | LR: 0.000013
Epoch: 025 | Train loss: 0.9969 | Train acc: 50.85% | Val loss: 1.0070 | Val acc: 46.05% | LR: 0.000013
Epoch: 026 | Train loss: 0.9977 | Train acc: 50.58% | Val loss: 1.0083 | Val acc: 46.01% | LR: 0.000013
Epoch: 027 | Train loss: 0.9978 | Train acc: 50.50% | Val loss: 1.0070 | Val acc: 45.99% | LR: 0.000013
Epoch: 028 | Train loss: 0.9989 | Train acc: 50.12% | Val loss: 1.0066 | Val acc: 45.99% | LR: 0.000013
Epoch: 029 | Train loss: 0.9973 | Train acc: 50.66% | Val loss: 1.0064 | Val acc: 46.01% | LR: 0.000013
Epoch: 030 | Train loss: 0.9962 | Train acc: 50.92% | Val loss: 1.0063 | Val acc: 45.99% | LR: 0.000013
Epoch: 031 | Train loss: 0.9981 | Train acc: 50.41% | Val loss: 1.0067 | Val acc: 46.01% | LR: 0.000012
Epoch: 032 | Train loss: 0.9970 | Train acc: 50.48% | Val loss: 1.0100 | Val acc: 46.03% | LR: 0.000012
Epoch: 033 | Train loss: 0.9999 | Train acc: 49.78% | Val loss: 1.0076 | Val acc: 45.97% | LR: 0.000012
Epoch: 034 | Train loss: 0.9986 | Train acc: 50.13% | Val loss: 1.0069 | Val acc: 46.03% | LR: 0.000012
Epoch: 035 | Train loss: 0.9984 | Train acc: 50.22% | Val loss: 1.0067 | Val acc: 46.03% | LR: 0.000012
Epoch: 036 | Train loss: 0.9976 | Train acc: 50.49% | Val loss: 1.0066 | Val acc: 46.05% | LR: 0.000012
Epoch: 037 | Train loss: 0.9967 | Train acc: 50.75% | Val loss: 1.0065 | Val acc: 46.09% | LR: 0.000012
Epoch: 038 | Train loss: 0.9986 | Train acc: 49.96% | Val loss: 1.0066 | Val acc: 46.03% | LR: 0.000012
Epoch: 039 | Train loss: 0.9983 | Train acc: 50.22% | Val loss: 1.0066 | Val acc: 45.97% | LR: 0.000012
Epoch: 040 | Train loss: 0.9967 | Train acc: 50.76% | Val loss: 1.0066 | Val acc: 45.97% | LR: 0.000012
Epoch: 041 | Train loss: 0.9973 | Train acc: 50.41% | Val loss: 1.0073 | Val acc: 45.97% | LR: 0.000012
Epoch: 042 | Train loss: 0.9967 | Train acc: 50.49% | Val loss: 1.0067 | Val acc: 45.99% | LR: 0.000011
Epoch: 043 | Train loss: 0.9966 | Train acc: 50.57% | Val loss: 1.0065 | Val acc: 45.99% | LR: 0.000011
Epoch: 044 | Train loss: 0.9978 | Train acc: 50.32% | Val loss: 1.0065 | Val acc: 45.99% | LR: 0.000011
Epoch: 045 | Train loss: 0.9969 | Train acc: 50.58% | Val loss: 1.0065 | Val acc: 45.99% | LR: 0.000011
Epoch: 046 | Train loss: 0.9948 | Train acc: 51.05% | Val loss: 1.0066 | Val acc: 45.99% | LR: 0.000011
Epoch: 047 | Train loss: 0.9981 | Train acc: 50.14% | Val loss: 1.0067 | Val acc: 45.99% | LR: 0.000011
Epoch: 048 | Train loss: 0.9959 | Train acc: 50.68% | Val loss: 1.0066 | Val acc: 46.01% | LR: 0.000011
Epoch: 049 | Train loss: 1.0006 | Train acc: 50.50% | Val loss: 1.0067 | Val acc: 46.01% | LR: 0.000011
Epoch: 050 | Train loss: 0.9985 | Train acc: 50.16% | Val loss: 1.0067 | Val acc: 46.01% | LR: 0.000011
Epoch: 051 | Train loss: 0.9951 | Train acc: 50.78% | Val loss: 1.0067 | Val acc: 46.01% | LR: 0.000010
Epoch: 052 | Train loss: 0.9995 | Train acc: 49.90% | Val loss: 1.0067 | Val acc: 46.01% | LR: 0.000010
Epoch: 053 | Train loss: 0.9979 | Train acc: 50.17% | Val loss: 1.0067 | Val acc: 46.01% | LR: 0.000010
Epoch: 054 | Train loss: 0.9959 | Train acc: 50.78% | Val loss: 1.0067 | Val acc: 46.01% | LR: 0.000010
Epoch: 055 | Train loss: 0.9998 | Train acc: 49.90% | Val loss: 1.0067 | Val acc: 46.01% | LR: 0.000010

[I 2025-09-23 18:33:58,201] Trial 118 finished with value: 0.4601422309875488 and parameters: {'lr': 1.388538833297901e-05, 'hidden_size': 67, 'dropout': 0.23454803749336162, 'weight_decay': 1.249777317320162e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0011 | Train acc: 49.57% | Val loss: 0.9966 | Val acc: 52.63% | LR: 0.000011
Epoch: 001 | Train loss: 1.0013 | Train acc: 49.03% | Val loss: 0.9972 | Val acc: 52.48% | LR: 0.000011
Epoch: 002 | Train loss: 1.0005 | Train acc: 49.83% | Val loss: 0.9967 | Val acc: 52.48% | LR: 0.000011
Epoch: 003 | Train loss: 1.0005 | Train acc: 49.96% | Val loss: 0.9967 | Val acc: 52.40% | LR: 0.000011
Epoch: 004 | Train loss: 1.0010 | Train acc: 49.34% | Val loss: 0.9976 | Val acc: 52.46% | LR: 0.000011
Epoch: 005 | Train loss: 1.0009 | Train acc: 49.38% | Val loss: 0.9971 | Val acc: 52.36% | LR: 0.000011
Epoch: 006 | Train loss: 1.0011 | Train acc: 49.81% | Val loss: 0.9967 | Val acc: 52.32% | LR: 0.000011
Epoch: 007 | Train loss: 1.0007 | Train acc: 49.92% | Val loss: 1.0072 | Val acc: 52.40% | LR: 0.000011
Epoch: 008 | Train loss: 1.0023 | Train acc: 49.92% | Val loss: 0.9993 | Val acc: 52.16% | LR: 0.000011
Epoch: 009 | Train loss: 1.0000 | Train acc: 49.75% | Val loss: 0.9989 | Val acc: 52.08% | LR: 0.000011
Epoch: 010 | Train loss: 1.0024 | Train acc: 49.85% | Val loss: 1.0034 | Val acc: 52.24% | LR: 0.000011
Epoch: 011 | Train loss: 1.0005 | Train acc: 50.14% | Val loss: 0.9971 | Val acc: 52.58% | LR: 0.000011
Epoch: 012 | Train loss: 1.0019 | Train acc: 50.09% | Val loss: 1.0142 | Val acc: 52.32% | LR: 0.000011
Epoch: 013 | Train loss: 1.0004 | Train acc: 50.00% | Val loss: 1.0097 | Val acc: 52.40% | LR: 0.000011
Epoch: 014 | Train loss: 1.0004 | Train acc: 50.19% | Val loss: 0.9973 | Val acc: 52.26% | LR: 0.000011
Epoch: 015 | Train loss: 1.0012 | Train acc: 49.86% | Val loss: 1.1990 | Val acc: 52.26% | LR: 0.000011
Epoch: 016 | Train loss: 1.0003 | Train acc: 49.94% | Val loss: 0.9986 | Val acc: 52.14% | LR: 0.000011
Epoch: 017 | Train loss: 1.0023 | Train acc: 49.78% | Val loss: 1.0006 | Val acc: 52.16% | LR: 0.000011
Epoch: 018 | Train loss: 1.0004 | Train acc: 49.77% | Val loss: 0.9980 | Val acc: 52.13% | LR: 0.000011
Epoch: 019 | Train loss: 1.0012 | Train acc: 49.25% | Val loss: 1.0002 | Val acc: 51.84% | LR: 0.000011
Epoch: 020 | Train loss: 0.9999 | Train acc: 50.12% | Val loss: 0.9973 | Val acc: 51.76% | LR: 0.000011
Epoch: 021 | Train loss: 1.0011 | Train acc: 50.08% | Val loss: 1.0002 | Val acc: 51.67% | LR: 0.000011
Epoch: 022 | Train loss: 1.0001 | Train acc: 49.67% | Val loss: 0.9983 | Val acc: 51.63% | LR: 0.000011
Epoch: 023 | Train loss: 1.0005 | Train acc: 49.99% | Val loss: 0.9974 | Val acc: 51.73% | LR: 0.000010
Epoch: 024 | Train loss: 0.9999 | Train acc: 49.86% | Val loss: 0.9968 | Val acc: 51.84% | LR: 0.000010
Epoch: 025 | Train loss: 1.0886 | Train acc: 49.50% | Val loss: 0.9972 | Val acc: 51.72% | LR: 0.000010
Epoch: 026 | Train loss: 1.0003 | Train acc: 49.85% | Val loss: 0.9974 | Val acc: 51.70% | LR: 0.000010
Epoch: 027 | Train loss: 0.9999 | Train acc: 50.05% | Val loss: 0.9997 | Val acc: 51.54% | LR: 0.000010
Epoch: 028 | Train loss: 1.0002 | Train acc: 49.96% | Val loss: 0.9974 | Val acc: 51.52% | LR: 0.000010
Epoch: 029 | Train loss: 0.9997 | Train acc: 49.92% | Val loss: 0.9991 | Val acc: 51.42% | LR: 0.000010
Epoch: 030 | Train loss: 1.0002 | Train acc: 50.16% | Val loss: 0.9975 | Val acc: 51.46% | LR: 0.000010
Epoch: 031 | Train loss: 1.0002 | Train acc: 49.99% | Val loss: 0.9977 | Val acc: 51.44% | LR: 0.000010
Epoch: 032 | Train loss: 1.0004 | Train acc: 50.33% | Val loss: 0.9996 | Val acc: 51.48% | LR: 0.000010
Epoch: 033 | Train loss: 1.0010 | Train acc: 49.42% | Val loss: 0.9977 | Val acc: 51.52% | LR: 0.000010
Epoch: 034 | Train loss: 0.9996 | Train acc: 50.35% | Val loss: 0.9987 | Val acc: 51.66% | LR: 0.000010
Epoch: 035 | Train loss: 1.0001 | Train acc: 49.40% | Val loss: 1.0063 | Val acc: 51.47% | LR: 0.000010
Epoch: 036 | Train loss: 1.0003 | Train acc: 49.96% | Val loss: 0.9976 | Val acc: 51.45% | LR: 0.000010
Epoch: 037 | Train loss: 0.9999 | Train acc: 50.48% | Val loss: 1.0021 | Val acc: 51.37% | LR: 0.000010
Epoch: 038 | Train loss: 1.0000 | Train acc: 50.11% | Val loss: 0.9979 | Val acc: 51.39% | LR: 0.000010
Epoch: 039 | Train loss: 0.9999 | Train acc: 50.14% | Val loss: 1.0507 | Val acc: 51.02% | LR: 0.000009
Epoch: 040 | Train loss: 0.9997 | Train acc: 50.34% | Val loss: 0.9975 | Val acc: 51.14% | LR: 0.000009
Epoch: 041 | Train loss: 0.9996 | Train acc: 50.84% | Val loss: 0.9977 | Val acc: 51.64% | LR: 0.000009
Epoch: 042 | Train loss: 0.9998 | Train acc: 50.07% | Val loss: 1.0017 | Val acc: 51.41% | LR: 0.000009
Epoch: 043 | Train loss: 1.0002 | Train acc: 50.24% | Val loss: 1.0012 | Val acc: 51.52% | LR: 0.000009
Epoch: 044 | Train loss: 1.0010 | Train acc: 50.20% | Val loss: 1.0089 | Val acc: 51.43% | LR: 0.000009
Epoch: 045 | Train loss: 0.9993 | Train acc: 51.09% | Val loss: 1.0093 | Val acc: 51.44% | LR: 0.000009
Epoch: 046 | Train loss: 1.0030 | Train acc: 50.75% | Val loss: 0.9997 | Val acc: 51.29% | LR: 0.000009
Epoch: 047 | Train loss: 1.0000 | Train acc: 50.66% | Val loss: 0.9972 | Val acc: 51.35% | LR: 0.000009
Epoch: 048 | Train loss: 1.0002 | Train acc: 50.49% | Val loss: 1.1661 | Val acc: 51.52% | LR: 0.000009
Epoch: 049 | Train loss: 0.9994 | Train acc: 50.69% | Val loss: 0.9992 | Val acc: 51.34% | LR: 0.000009

[I 2025-09-23 18:34:42,313] Trial 119 finished with value: 0.5131932497024536 and parameters: {'lr': 1.109619653942369e-05, 'hidden_size': 65, 'dropout': 0.20492299975825892, 'weight_decay': 8.839591314826583e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0005 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.05% | LR: 0.000013
Epoch: 001 | Train loss: 1.0010 | Train acc: 49.72% | Val loss: 0.9917 | Val acc: 54.11% | LR: 0.000013
Epoch: 002 | Train loss: 1.0000 | Train acc: 50.17% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000013
Epoch: 003 | Train loss: 0.9991 | Train acc: 50.52% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000013
Epoch: 004 | Train loss: 0.9997 | Train acc: 50.18% | Val loss: 0.9919 | Val acc: 54.13% | LR: 0.000013
Epoch: 005 | Train loss: 0.9977 | Train acc: 50.87% | Val loss: 0.9919 | Val acc: 54.17% | LR: 0.000013
Epoch: 006 | Train loss: 0.9983 | Train acc: 50.52% | Val loss: 0.9919 | Val acc: 54.22% | LR: 0.000013
Epoch: 007 | Train loss: 0.9994 | Train acc: 49.98% | Val loss: 0.9919 | Val acc: 54.26% | LR: 0.000013
Epoch: 008 | Train loss: 0.9998 | Train acc: 49.72% | Val loss: 0.9920 | Val acc: 54.34% | LR: 0.000013
Epoch: 009 | Train loss: 0.9979 | Train acc: 50.60% | Val loss: 0.9921 | Val acc: 54.26% | LR: 0.000013
Epoch: 010 | Train loss: 0.9975 | Train acc: 50.78% | Val loss: 0.9921 | Val acc: 54.26% | LR: 0.000013
Epoch: 011 | Train loss: 0.9972 | Train acc: 50.87% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000013
Epoch: 012 | Train loss: 0.9975 | Train acc: 50.69% | Val loss: 0.9920 | Val acc: 54.28% | LR: 0.000013
Epoch: 013 | Train loss: 0.9968 | Train acc: 50.43% | Val loss: 0.9919 | Val acc: 54.28% | LR: 0.000013
Epoch: 014 | Train loss: 1.0165 | Train acc: 50.34% | Val loss: 0.9919 | Val acc: 54.26% | LR: 0.000012
Epoch: 015 | Train loss: 0.9988 | Train acc: 50.16% | Val loss: 0.9919 | Val acc: 54.32% | LR: 0.000012
Epoch: 016 | Train loss: 0.9984 | Train acc: 50.61% | Val loss: 0.9919 | Val acc: 54.32% | LR: 0.000012
Epoch: 017 | Train loss: 0.9978 | Train acc: 50.49% | Val loss: 0.9919 | Val acc: 54.36% | LR: 0.000012
Epoch: 018 | Train loss: 0.9981 | Train acc: 50.25% | Val loss: 0.9918 | Val acc: 54.38% | LR: 0.000012
Epoch: 019 | Train loss: 0.9985 | Train acc: 50.35% | Val loss: 0.9918 | Val acc: 54.36% | LR: 0.000012
Epoch: 020 | Train loss: 0.9970 | Train acc: 51.16% | Val loss: 0.9918 | Val acc: 54.38% | LR: 0.000012
Epoch: 021 | Train loss: 0.9974 | Train acc: 50.59% | Val loss: 0.9917 | Val acc: 54.40% | LR: 0.000012
Epoch: 022 | Train loss: 0.9976 | Train acc: 50.79% | Val loss: 0.9922 | Val acc: 54.39% | LR: 0.000012
Epoch: 023 | Train loss: 0.9979 | Train acc: 50.34% | Val loss: 0.9916 | Val acc: 54.40% | LR: 0.000012
Epoch: 024 | Train loss: 0.9978 | Train acc: 50.34% | Val loss: 0.9916 | Val acc: 54.31% | LR: 0.000012
Epoch: 025 | Train loss: 0.9980 | Train acc: 50.06% | Val loss: 0.9916 | Val acc: 54.27% | LR: 0.000012
Epoch: 026 | Train loss: 0.9975 | Train acc: 50.24% | Val loss: 0.9915 | Val acc: 54.27% | LR: 0.000012
Epoch: 027 | Train loss: 0.9972 | Train acc: 50.79% | Val loss: 0.9916 | Val acc: 54.36% | LR: 0.000012
Epoch: 028 | Train loss: 0.9969 | Train acc: 50.81% | Val loss: 0.9915 | Val acc: 54.33% | LR: 0.000012
Epoch: 029 | Train loss: 0.9967 | Train acc: 50.82% | Val loss: 0.9915 | Val acc: 54.31% | LR: 0.000012
Epoch: 030 | Train loss: 0.9981 | Train acc: 50.47% | Val loss: 0.9914 | Val acc: 54.39% | LR: 0.000012
Epoch: 031 | Train loss: 0.9985 | Train acc: 50.40% | Val loss: 0.9914 | Val acc: 54.33% | LR: 0.000012
Epoch: 032 | Train loss: 0.9959 | Train acc: 51.09% | Val loss: 0.9913 | Val acc: 54.43% | LR: 0.000011
Epoch: 033 | Train loss: 0.9980 | Train acc: 50.00% | Val loss: 0.9913 | Val acc: 54.45% | LR: 0.000011
Epoch: 034 | Train loss: 0.9963 | Train acc: 51.02% | Val loss: 0.9914 | Val acc: 54.49% | LR: 0.000011
Epoch: 035 | Train loss: 0.9980 | Train acc: 50.47% | Val loss: 0.9913 | Val acc: 54.50% | LR: 0.000011
Epoch: 036 | Train loss: 0.9971 | Train acc: 50.56% | Val loss: 0.9914 | Val acc: 54.40% | LR: 0.000011
Epoch: 037 | Train loss: 0.9969 | Train acc: 50.67% | Val loss: 0.9913 | Val acc: 54.34% | LR: 0.000011
Epoch: 038 | Train loss: 0.9980 | Train acc: 50.76% | Val loss: 0.9915 | Val acc: 54.40% | LR: 0.000011
Epoch: 039 | Train loss: 1.0261 | Train acc: 50.92% | Val loss: 0.9913 | Val acc: 54.46% | LR: 0.000011
Epoch: 040 | Train loss: 1.0026 | Train acc: 50.42% | Val loss: 0.9915 | Val acc: 54.51% | LR: 0.000011
Epoch: 041 | Train loss: 0.9983 | Train acc: 50.66% | Val loss: 0.9912 | Val acc: 54.52% | LR: 0.000011
Epoch: 042 | Train loss: 0.9995 | Train acc: 50.22% | Val loss: 0.9909 | Val acc: 54.62% | LR: 0.000011
Epoch: 043 | Train loss: 0.9987 | Train acc: 50.56% | Val loss: 0.9916 | Val acc: 54.54% | LR: 0.000010
Epoch: 044 | Train loss: 0.9996 | Train acc: 50.52% | Val loss: 0.9913 | Val acc: 54.52% | LR: 0.000010
Epoch: 045 | Train loss: 0.9986 | Train acc: 50.67% | Val loss: 0.9911 | Val acc: 54.45% | LR: 0.000010
Epoch: 046 | Train loss: 0.9970 | Train acc: 51.21% | Val loss: 0.9935 | Val acc: 54.50% | LR: 0.000010
Epoch: 047 | Train loss: 0.9996 | Train acc: 50.31% | Val loss: 0.9911 | Val acc: 54.52% | LR: 0.000010
Epoch: 048 | Train loss: 0.9983 | Train acc: 50.75% | Val loss: 0.9971 | Val acc: 54.46% | LR: 0.000010
Epoch: 049 | Train loss: 0.9983 | Train acc: 50.61% | Val loss: 0.9911 | Val acc: 54.52% | LR: 0.000010
Epoch: 050 | Train loss: 0.9990 | Train acc: 50.40% | Val loss: 0.9919 | Val acc: 54.50% | LR: 0.000010
Epoch: 051 | Train loss: 0.9981 | Train acc: 50.67% | Val loss: 0.9911 | Val acc: 54.60% | LR: 0.000010
Epoch: 052 | Train loss: 0.9987 | Train acc: 50.42% | Val loss: 0.9911 | Val acc: 54.54% | LR: 0.000010
Epoch: 053 | Train loss: 0.9988 | Train acc: 50.50% | Val loss: 0.9911 | Val acc: 54.62% | LR: 0.000009
Epoch: 054 | Train loss: 0.9977 | Train acc: 50.86% | Val loss: 0.9909 | Val acc: 54.62% | LR: 0.000009
Epoch: 055 | Train loss: 0.9977 | Train acc: 50.87% | Val loss: 0.9911 | Val acc: 54.58% | LR: 0.000009
Epoch: 056 | Train loss: 0.9973 | Train acc: 51.05% | Val loss: 0.9917 | Val acc: 54.50% | LR: 0.000009
Epoch: 057 | Train loss: 0.9982 | Train acc: 50.53% | Val loss: 0.9912 | Val acc: 54.54% | LR: 0.000009
Epoch: 058 | Train loss: 1.0003 | Train acc: 50.61% | Val loss: 0.9911 | Val acc: 54.52% | LR: 0.000009
Epoch: 059 | Train loss: 0.9991 | Train acc: 51.06% | Val loss: 0.9911 | Val acc: 54.55% | LR: 0.000009
Epoch: 060 | Train loss: 0.9973 | Train acc: 50.81% | Val loss: 0.9920 | Val acc: 54.59% | LR: 0.000009
Epoch: 061 | Train loss: 0.9978 | Train acc: 50.64% | Val loss: 0.9913 | Val acc: 54.57% | LR: 0.000008
Epoch: 062 | Train loss: 0.9979 | Train acc: 50.64% | Val loss: 0.9914 | Val acc: 54.65% | LR: 0.000008
Epoch: 063 | Train loss: 0.9985 | Train acc: 50.54% | Val loss: 0.9912 | Val acc: 54.67% | LR: 0.000008
Epoch: 064 | Train loss: 0.9983 | Train acc: 50.89% | Val loss: 0.9912 | Val acc: 54.59% | LR: 0.000008
Epoch: 065 | Train loss: 0.9968 | Train acc: 50.88% | Val loss: 0.9912 | Val acc: 54.51% | LR: 0.000008
Epoch: 066 | Train loss: 0.9985 | Train acc: 50.44% | Val loss: 0.9911 | Val acc: 54.57% | LR: 0.000008
Epoch: 067 | Train loss: 0.9961 | Train acc: 51.52% | Val loss: 0.9923 | Val acc: 54.51% | LR: 0.000008
Epoch: 068 | Train loss: 0.9975 | Train acc: 50.98% | Val loss: 0.9911 | Val acc: 54.48% | LR: 0.000008
Epoch: 069 | Train loss: 0.9979 | Train acc: 50.63% | Val loss: 0.9912 | Val acc: 54.48% | LR: 0.000008
Epoch: 070 | Train loss: 0.9965 | Train acc: 51.07% | Val loss: 0.9912 | Val acc: 54.47% | LR: 0.000007
Epoch: 071 | Train loss: 0.9977 | Train acc: 50.80% | Val loss: 0.9912 | Val acc: 54.45% | LR: 0.000007
Epoch: 072 | Train loss: 0.9968 | Train acc: 50.79% | Val loss: 0.9912 | Val acc: 54.45% | LR: 0.000007
Epoch: 073 | Train loss: 0.9988 | Train acc: 50.08% | Val loss: 0.9912 | Val acc: 54.50% | LR: 0.000007
Epoch: 074 | Train loss: 0.9955 | Train acc: 51.33% | Val loss: 0.9913 | Val acc: 54.49% | LR: 0.000007
Epoch: 075 | Train loss: 0.9962 | Train acc: 51.14% | Val loss: 0.9913 | Val acc: 54.54% | LR: 0.000007
Epoch: 076 | Train loss: 0.9986 | Train acc: 50.41% | Val loss: 0.9913 | Val acc: 54.50% | LR: 0.000007
Epoch: 077 | Train loss: 0.9983 | Train acc: 50.32% | Val loss: 0.9913 | Val acc: 54.48% | LR: 0.000007
Epoch: 078 | Train loss: 0.9971 | Train acc: 50.67% | Val loss: 0.9913 | Val acc: 54.48% | LR: 0.000006
Epoch: 079 | Train loss: 0.9973 | Train acc: 50.75% | Val loss: 0.9913 | Val acc: 54.50% | LR: 0.000006
Epoch: 080 | Train loss: 0.9965 | Train acc: 51.11% | Val loss: 0.9913 | Val acc: 54.52% | LR: 0.000006
Epoch: 081 | Train loss: 0.9972 | Train acc: 50.66% | Val loss: 0.9913 | Val acc: 54.46% | LR: 0.000006
Epoch: 082 | Train loss: 0.9963 | Train acc: 51.37% | Val loss: 0.9913 | Val acc: 54.50% | LR: 0.000006
Epoch: 083 | Train loss: 0.9975 | Train acc: 50.32% | Val loss: 0.9913 | Val acc: 54.48% | LR: 0.000006
Epoch: 084 | Train loss: 0.9966 | Train acc: 50.84% | Val loss: 0.9913 | Val acc: 54.54% | LR: 0.000006
Epoch: 085 | Train loss: 0.9985 | Train acc: 50.30% | Val loss: 0.9913 | Val acc: 54.52% | LR: 0.000006
Epoch: 086 | Train loss: 0.9971 | Train acc: 50.65% | Val loss: 0.9913 | Val acc: 54.52% | LR: 0.000005
Epoch: 087 | Train loss: 0.9965 | Train acc: 50.64% | Val loss: 0.9913 | Val acc: 54.54% | LR: 0.000005
Epoch: 088 | Train loss: 0.9967 | Train acc: 50.66% | Val loss: 0.9914 | Val acc: 54.62% | LR: 0.000005
Epoch: 089 | Train loss: 0.9971 | Train acc: 50.60% | Val loss: 0.9913 | Val acc: 54.64% | LR: 0.000005
Epoch: 090 | Train loss: 0.9970 | Train acc: 50.76% | Val loss: 0.9913 | Val acc: 54.62% | LR: 0.000005
Epoch: 091 | Train loss: 0.9966 | Train acc: 50.94% | Val loss: 0.9913 | Val acc: 54.62% | LR: 0.000005
Epoch: 092 | Train loss: 0.9959 | Train acc: 50.59% | Val loss: 0.9913 | Val acc: 54.64% | LR: 0.000005
Epoch: 093 | Train loss: 0.9966 | Train acc: 50.76% | Val loss: 0.9914 | Val acc: 54.64% | LR: 0.000005
Epoch: 094 | Train loss: 0.9958 | Train acc: 51.29% | Val loss: 0.9913 | Val acc: 54.68% | LR: 0.000004
Epoch: 095 | Train loss: 0.9974 | Train acc: 50.86% | Val loss: 0.9913 | Val acc: 54.68% | LR: 0.000004
Epoch: 096 | Train loss: 0.9959 | Train acc: 50.94% | Val loss: 0.9913 | Val acc: 54.68% | LR: 0.000004
Epoch: 097 | Train loss: 0.9966 | Train acc: 50.77% | Val loss: 0.9913 | Val acc: 54.70% | LR: 0.000004
Epoch: 098 | Train loss: 0.9975 | Train acc: 50.93% | Val loss: 0.9913 | Val acc: 54.66% | LR: 0.000004
Epoch: 099 | Train loss: 0.9968 | Train acc: 51.06% | Val loss: 0.9914 | Val acc: 54.66% | LR: 0.000004
Epoch: 100 | Train loss: 0.9957 | Train acc: 50.53% | Val loss: 0.9914 | Val acc: 54.56% | LR: 0.000004
Epoch: 101 | Train loss: 0.9964 | Train acc: 50.96% | Val loss: 0.9913 | Val acc: 54.54% | LR: 0.000004
Epoch: 102 | Train loss: 0.9960 | Train acc: 50.97% | Val loss: 0.9913 | Val acc: 54.48% | LR: 0.000004
Epoch: 103 | Train loss: 0.9965 | Train acc: 50.88% | Val loss: 0.9913 | Val acc: 54.48% | LR: 0.000004
Epoch: 104 | Train loss: 0.9971 | Train acc: 50.62% | Val loss: 0.9913 | Val acc: 54.46% | LR: 0.000003
Epoch: 105 | Train loss: 0.9964 | Train acc: 51.15% | Val loss: 0.9913 | Val acc: 54.40% | LR: 0.000003
Epoch: 106 | Train loss: 0.9966 | Train acc: 50.88% | Val loss: 0.9914 | Val acc: 54.42% | LR: 0.000003
Epoch: 107 | Train loss: 0.9964 | Train acc: 51.05% | Val loss: 0.9913 | Val acc: 54.46% | LR: 0.000003
Epoch: 108 | Train loss: 0.9979 | Train acc: 50.18% | Val loss: 0.9913 | Val acc: 54.46% | LR: 0.000003
Epoch: 109 | Train loss: 0.9968 | Train acc: 50.96% | Val loss: 0.9913 | Val acc: 54.42% | LR: 0.000003
Epoch: 110 | Train loss: 0.9961 | Train acc: 50.61% | Val loss: 0.9913 | Val acc: 54.42% | LR: 0.000003
Epoch: 111 | Train loss: 0.9957 | Train acc: 50.88% | Val loss: 0.9913 | Val acc: 54.42% | LR: 0.000003
Epoch: 112 | Train loss: 0.9965 | Train acc: 50.34% | Val loss: 0.9913 | Val acc: 54.40% | LR: 0.000003
Epoch: 113 | Train loss: 0.9962 | Train acc: 50.43% | Val loss: 0.9913 | Val acc: 54.40% | LR: 0.000003
Epoch: 114 | Train loss: 0.9962 | Train acc: 50.35% | Val loss: 0.9913 | Val acc: 54.34% | LR: 0.000003
Epoch: 115 | Train loss: 0.9962 | Train acc: 51.21% | Val loss: 0.9913 | Val acc: 54.32% | LR: 0.000002
Epoch: 116 | Train loss: 0.9955 | Train acc: 51.14% | Val loss: 0.9913 | Val acc: 54.32% | LR: 0.000002
Epoch: 117 | Train loss: 0.9972 | Train acc: 50.44% | Val loss: 0.9913 | Val acc: 54.32% | LR: 0.000002
Epoch: 118 | Train loss: 0.9968 | Train acc: 50.52% | Val loss: 0.9913 | Val acc: 54.32% | LR: 0.000002
Epoch: 119 | Train loss: 0.9972 | Train acc: 50.88% | Val loss: 0.9913 | Val acc: 54.32% | LR: 0.000002
Epoch: 120 | Train loss: 0.9974 | Train acc: 50.64% | Val loss: 0.9913 | Val acc: 54.28% | LR: 0.000002
Epoch: 121 | Train loss: 0.9961 | Train acc: 50.96% | Val loss: 0.9913 | Val acc: 54.33% | LR: 0.000002
Epoch: 122 | Train loss: 0.9962 | Train acc: 50.89% | Val loss: 0.9913 | Val acc: 54.33% | LR: 0.000002
Epoch: 123 | Train loss: 0.9958 | Train acc: 50.98% | Val loss: 0.9913 | Val acc: 54.35% | LR: 0.000002
Epoch: 124 | Train loss: 0.9963 | Train acc: 51.14% | Val loss: 0.9913 | Val acc: 54.37% | LR: 0.000002
Epoch: 125 | Train loss: 0.9962 | Train acc: 50.97% | Val loss: 0.9913 | Val acc: 54.35% | LR: 0.000002
Epoch: 126 | Train loss: 0.9970 | Train acc: 50.25% | Val loss: 0.9913 | Val acc: 54.35% | LR: 0.000002
Epoch: 127 | Train loss: 0.9961 | Train acc: 50.79% | Val loss: 0.9913 | Val acc: 54.35% | LR: 0.000002
Epoch: 128 | Train loss: 0.9975 | Train acc: 50.34% | Val loss: 0.9913 | Val acc: 54.37% | LR: 0.000002
Epoch: 129 | Train loss: 0.9962 | Train acc: 50.70% | Val loss: 0.9913 | Val acc: 54.37% | LR: 0.000002
Epoch: 130 | Train loss: 0.9980 | Train acc: 50.69% | Val loss: 0.9913 | Val acc: 54.37% | LR: 0.000001
Epoch: 131 | Train loss: 0.9960 | Train acc: 50.86% | Val loss: 0.9913 | Val acc: 54.37% | LR: 0.000001
Epoch: 132 | Train loss: 0.9965 | Train acc: 50.52% | Val loss: 0.9913 | Val acc: 54.35% | LR: 0.000001
Epoch: 133 | Train loss: 0.9971 | Train acc: 50.35% | Val loss: 0.9913 | Val acc: 54.35% | LR: 0.000001
Epoch: 134 | Train loss: 0.9962 | Train acc: 50.97% | Val loss: 0.9913 | Val acc: 54.37% | LR: 0.000001
Epoch: 135 | Train loss: 0.9945 | Train acc: 50.79% | Val loss: 0.9913 | Val acc: 54.37% | LR: 0.000001
Epoch: 136 | Train loss: 0.9957 | Train acc: 51.06% | Val loss: 0.9913 | Val acc: 54.35% | LR: 0.000001
Epoch: 137 | Train loss: 0.9967 | Train acc: 50.34% | Val loss: 0.9913 | Val acc: 54.37% | LR: 0.000001
Epoch: 138 | Train loss: 0.9973 | Train acc: 50.44% | Val loss: 0.9913 | Val acc: 54.35% | LR: 0.000001
Epoch: 139 | Train loss: 0.9970 | Train acc: 50.63% | Val loss: 0.9913 | Val acc: 54.35% | LR: 0.000001
Epoch: 140 | Train loss: 0.9957 | Train acc: 50.48% | Val loss: 0.9913 | Val acc: 54.35% | LR: 0.000001
Epoch: 141 | Train loss: 0.9957 | Train acc: 51.27% | Val loss: 0.9913 | Val acc: 54.35% | LR: 0.000001
Epoch: 142 | Train loss: 0.9960 | Train acc: 51.37% | Val loss: 0.9913 | Val acc: 54.35% | LR: 0.000001
Epoch: 143 | Train loss: 0.9957 | Train acc: 51.31% | Val loss: 0.9913 | Val acc: 54.34% | LR: 0.000001
Epoch: 144 | Train loss: 0.9959 | Train acc: 51.12% | Val loss: 0.9913 | Val acc: 54.34% | LR: 0.000001
Epoch: 145 | Train loss: 0.9963 | Train acc: 51.29% | Val loss: 0.9913 | Val acc: 54.36% | LR: 0.000001
Epoch: 146 | Train loss: 0.9970 | Train acc: 51.16% | Val loss: 0.9913 | Val acc: 54.36% | LR: 0.000001

[I 2025-09-23 18:36:40,766] Trial 120 finished with value: 0.5435591697692871 and parameters: {'lr': 1.278334360822462e-05, 'hidden_size': 64, 'dropout': 0.22140959795376589, 'weight_decay': 1.6187902856838157e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0005 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.05% | LR: 0.000013
Epoch: 001 | Train loss: 1.0010 | Train acc: 49.73% | Val loss: 0.9916 | Val acc: 54.11% | LR: 0.000013
Epoch: 002 | Train loss: 0.9998 | Train acc: 50.23% | Val loss: 0.9916 | Val acc: 54.13% | LR: 0.000013
Epoch: 003 | Train loss: 0.9992 | Train acc: 50.51% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000013
Epoch: 004 | Train loss: 0.9997 | Train acc: 50.17% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000012
Epoch: 005 | Train loss: 0.9978 | Train acc: 50.87% | Val loss: 0.9917 | Val acc: 54.15% | LR: 0.000012
Epoch: 006 | Train loss: 0.9984 | Train acc: 50.52% | Val loss: 0.9917 | Val acc: 54.17% | LR: 0.000012
Epoch: 007 | Train loss: 0.9995 | Train acc: 49.98% | Val loss: 0.9918 | Val acc: 54.24% | LR: 0.000012
Epoch: 008 | Train loss: 0.9999 | Train acc: 49.72% | Val loss: 0.9919 | Val acc: 54.34% | LR: 0.000012
Epoch: 009 | Train loss: 0.9980 | Train acc: 50.60% | Val loss: 0.9920 | Val acc: 54.28% | LR: 0.000012
Epoch: 010 | Train loss: 0.9975 | Train acc: 50.78% | Val loss: 0.9920 | Val acc: 54.26% | LR: 0.000012
Epoch: 011 | Train loss: 0.9973 | Train acc: 50.87% | Val loss: 0.9919 | Val acc: 54.26% | LR: 0.000012
Epoch: 012 | Train loss: 0.9975 | Train acc: 50.68% | Val loss: 0.9919 | Val acc: 54.30% | LR: 0.000012
Epoch: 013 | Train loss: 0.9971 | Train acc: 50.43% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000012
Epoch: 014 | Train loss: 1.0087 | Train acc: 50.39% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000012
Epoch: 015 | Train loss: 0.9987 | Train acc: 50.18% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000012
Epoch: 016 | Train loss: 1.1972 | Train acc: 50.58% | Val loss: 0.9919 | Val acc: 54.26% | LR: 0.000012
Epoch: 017 | Train loss: 0.9983 | Train acc: 50.52% | Val loss: 0.9919 | Val acc: 54.28% | LR: 0.000012
Epoch: 018 | Train loss: 0.9970 | Train acc: 50.24% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000012
Epoch: 019 | Train loss: 0.9977 | Train acc: 50.28% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000012
Epoch: 020 | Train loss: 1.0219 | Train acc: 51.09% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000012
Epoch: 021 | Train loss: 1.0738 | Train acc: 50.62% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000012
Epoch: 022 | Train loss: 1.0738 | Train acc: 50.56% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000012
Epoch: 023 | Train loss: 0.9966 | Train acc: 50.21% | Val loss: 0.9918 | Val acc: 54.34% | LR: 0.000012
Epoch: 024 | Train loss: 0.9973 | Train acc: 50.43% | Val loss: 0.9918 | Val acc: 54.34% | LR: 0.000012
Epoch: 025 | Train loss: 1.0117 | Train acc: 49.95% | Val loss: 0.9917 | Val acc: 54.36% | LR: 0.000012
Epoch: 026 | Train loss: 1.0095 | Train acc: 50.30% | Val loss: 0.9917 | Val acc: 54.36% | LR: 0.000012
Epoch: 027 | Train loss: 0.9959 | Train acc: 50.77% | Val loss: 0.9917 | Val acc: 54.36% | LR: 0.000012
Epoch: 028 | Train loss: 1.0929 | Train acc: 50.50% | Val loss: 0.9917 | Val acc: 54.36% | LR: 0.000011
Epoch: 029 | Train loss: 1.0002 | Train acc: 50.72% | Val loss: 0.9917 | Val acc: 54.38% | LR: 0.000011
Epoch: 030 | Train loss: 0.9984 | Train acc: 50.43% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000011
Epoch: 031 | Train loss: 0.9989 | Train acc: 50.44% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000011
Epoch: 032 | Train loss: 0.9941 | Train acc: 51.05% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000011
Epoch: 033 | Train loss: 1.0096 | Train acc: 50.00% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000011
Epoch: 034 | Train loss: 1.0279 | Train acc: 50.76% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000011
Epoch: 035 | Train loss: 1.0020 | Train acc: 50.13% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000011
Epoch: 036 | Train loss: 1.0067 | Train acc: 50.30% | Val loss: 0.9917 | Val acc: 54.36% | LR: 0.000011
Epoch: 037 | Train loss: 1.0011 | Train acc: 50.14% | Val loss: 0.9917 | Val acc: 54.38% | LR: 0.000011
Epoch: 038 | Train loss: 1.2290 | Train acc: 50.14% | Val loss: 0.9917 | Val acc: 54.38% | LR: 0.000011
Epoch: 039 | Train loss: 0.9972 | Train acc: 50.76% | Val loss: 0.9917 | Val acc: 54.38% | LR: 0.000011
Epoch: 040 | Train loss: 0.9968 | Train acc: 50.56% | Val loss: 0.9916 | Val acc: 54.38% | LR: 0.000011
Epoch: 041 | Train loss: 1.0023 | Train acc: 50.47% | Val loss: 0.9917 | Val acc: 54.38% | LR: 0.000010
Epoch: 042 | Train loss: 0.9994 | Train acc: 50.20% | Val loss: 0.9916 | Val acc: 54.38% | LR: 0.000010
Epoch: 043 | Train loss: 0.9995 | Train acc: 50.71% | Val loss: 0.9917 | Val acc: 54.46% | LR: 0.000010
Epoch: 044 | Train loss: 0.9993 | Train acc: 50.09% | Val loss: 0.9917 | Val acc: 54.44% | LR: 0.000010
Epoch: 045 | Train loss: 0.9959 | Train acc: 50.56% | Val loss: 0.9917 | Val acc: 54.40% | LR: 0.000010
Epoch: 046 | Train loss: 1.0031 | Train acc: 50.27% | Val loss: 0.9917 | Val acc: 54.40% | LR: 0.000010
Epoch: 047 | Train loss: 1.0005 | Train acc: 50.46% | Val loss: 0.9916 | Val acc: 54.46% | LR: 0.000010
Epoch: 048 | Train loss: 1.0005 | Train acc: 50.45% | Val loss: 0.9916 | Val acc: 54.46% | LR: 0.000010
Epoch: 049 | Train loss: 1.0338 | Train acc: 50.33% | Val loss: 0.9916 | Val acc: 54.40% | LR: 0.000010
Epoch: 050 | Train loss: 0.9976 | Train acc: 50.06% | Val loss: 0.9916 | Val acc: 54.34% | LR: 0.000010
Epoch: 051 | Train loss: 0.9954 | Train acc: 50.32% | Val loss: 0.9916 | Val acc: 54.34% | LR: 0.000009
Epoch: 052 | Train loss: 1.0140 | Train acc: 50.30% | Val loss: 0.9915 | Val acc: 54.24% | LR: 0.000009
Epoch: 053 | Train loss: 1.0010 | Train acc: 50.13% | Val loss: 0.9915 | Val acc: 54.31% | LR: 0.000009
Epoch: 054 | Train loss: 0.9962 | Train acc: 50.60% | Val loss: 0.9916 | Val acc: 54.30% | LR: 0.000009
Epoch: 055 | Train loss: 0.9960 | Train acc: 50.63% | Val loss: 0.9915 | Val acc: 54.45% | LR: 0.000009
Epoch: 056 | Train loss: 0.9944 | Train acc: 50.83% | Val loss: 0.9914 | Val acc: 54.42% | LR: 0.000009
Epoch: 057 | Train loss: 0.9953 | Train acc: 50.31% | Val loss: 0.9916 | Val acc: 54.41% | LR: 0.000009
Epoch: 058 | Train loss: 0.9987 | Train acc: 50.39% | Val loss: 0.9915 | Val acc: 54.33% | LR: 0.000009
Epoch: 059 | Train loss: 0.9953 | Train acc: 50.92% | Val loss: 0.9915 | Val acc: 54.37% | LR: 0.000009
Epoch: 060 | Train loss: 1.0260 | Train acc: 50.59% | Val loss: 0.9915 | Val acc: 54.35% | LR: 0.000008
Epoch: 061 | Train loss: 0.9952 | Train acc: 50.54% | Val loss: 0.9919 | Val acc: 54.25% | LR: 0.000008
Epoch: 062 | Train loss: 1.0504 | Train acc: 50.57% | Val loss: 0.9914 | Val acc: 54.41% | LR: 0.000008
Epoch: 063 | Train loss: 1.0014 | Train acc: 50.53% | Val loss: 0.9914 | Val acc: 54.39% | LR: 0.000008
Epoch: 064 | Train loss: 0.9934 | Train acc: 50.82% | Val loss: 0.9914 | Val acc: 54.43% | LR: 0.000008
Epoch: 065 | Train loss: 1.0042 | Train acc: 50.86% | Val loss: 0.9914 | Val acc: 54.45% | LR: 0.000008
Epoch: 066 | Train loss: 0.9996 | Train acc: 50.39% | Val loss: 0.9914 | Val acc: 54.47% | LR: 0.000008
Epoch: 067 | Train loss: 0.9947 | Train acc: 51.16% | Val loss: 0.9914 | Val acc: 54.43% | LR: 0.000008
Epoch: 068 | Train loss: 0.9983 | Train acc: 50.70% | Val loss: 0.9914 | Val acc: 54.41% | LR: 0.000007
Epoch: 069 | Train loss: 1.0052 | Train acc: 50.34% | Val loss: 0.9912 | Val acc: 54.49% | LR: 0.000007
Epoch: 070 | Train loss: 0.9972 | Train acc: 50.83% | Val loss: 0.9914 | Val acc: 54.51% | LR: 0.000007
Epoch: 071 | Train loss: 1.0066 | Train acc: 50.66% | Val loss: 0.9911 | Val acc: 54.51% | LR: 0.000007
Epoch: 072 | Train loss: 0.9952 | Train acc: 50.25% | Val loss: 0.9913 | Val acc: 54.53% | LR: 0.000007
Epoch: 073 | Train loss: 0.9967 | Train acc: 49.69% | Val loss: 0.9914 | Val acc: 54.45% | LR: 0.000007
Epoch: 074 | Train loss: 0.9925 | Train acc: 51.18% | Val loss: 0.9913 | Val acc: 54.43% | LR: 0.000007
Epoch: 075 | Train loss: 0.9926 | Train acc: 50.98% | Val loss: 0.9914 | Val acc: 54.43% | LR: 0.000007
Epoch: 076 | Train loss: 0.9951 | Train acc: 50.25% | Val loss: 0.9913 | Val acc: 54.47% | LR: 0.000007
Epoch: 077 | Train loss: 0.9959 | Train acc: 50.35% | Val loss: 0.9913 | Val acc: 54.49% | LR: 0.000006
Epoch: 078 | Train loss: 0.9959 | Train acc: 50.54% | Val loss: 0.9911 | Val acc: 54.47% | LR: 0.000006
Epoch: 079 | Train loss: 0.9954 | Train acc: 50.64% | Val loss: 0.9910 | Val acc: 54.47% | LR: 0.000006
Epoch: 080 | Train loss: 0.9950 | Train acc: 51.04% | Val loss: 0.9913 | Val acc: 54.43% | LR: 0.000006
Epoch: 081 | Train loss: 0.9941 | Train acc: 50.42% | Val loss: 0.9913 | Val acc: 54.43% | LR: 0.000006
Epoch: 082 | Train loss: 0.9948 | Train acc: 51.30% | Val loss: 0.9913 | Val acc: 54.37% | LR: 0.000006
Epoch: 083 | Train loss: 0.9983 | Train acc: 50.06% | Val loss: 0.9913 | Val acc: 54.37% | LR: 0.000006
Epoch: 084 | Train loss: 1.0461 | Train acc: 50.61% | Val loss: 0.9913 | Val acc: 54.37% | LR: 0.000006
Epoch: 085 | Train loss: 0.9965 | Train acc: 50.12% | Val loss: 0.9913 | Val acc: 54.37% | LR: 0.000005
Epoch: 086 | Train loss: 0.9935 | Train acc: 50.52% | Val loss: 0.9926 | Val acc: 54.39% | LR: 0.000005
Epoch: 087 | Train loss: 0.9981 | Train acc: 50.68% | Val loss: 0.9927 | Val acc: 54.42% | LR: 0.000005
Epoch: 088 | Train loss: 0.9984 | Train acc: 50.42% | Val loss: 0.9911 | Val acc: 54.44% | LR: 0.000005
Epoch: 089 | Train loss: 0.9955 | Train acc: 49.93% | Val loss: 0.9910 | Val acc: 54.44% | LR: 0.000005
Epoch: 090 | Train loss: 0.9983 | Train acc: 50.35% | Val loss: 0.9911 | Val acc: 54.50% | LR: 0.000005
Epoch: 091 | Train loss: 0.9958 | Train acc: 50.75% | Val loss: 0.9911 | Val acc: 54.46% | LR: 0.000005
Epoch: 092 | Train loss: 0.9946 | Train acc: 50.26% | Val loss: 0.9917 | Val acc: 54.48% | LR: 0.000005
Epoch: 093 | Train loss: 0.9948 | Train acc: 50.91% | Val loss: 0.9913 | Val acc: 54.43% | LR: 0.000005
Epoch: 094 | Train loss: 0.9922 | Train acc: 50.94% | Val loss: 0.9913 | Val acc: 54.43% | LR: 0.000004
Epoch: 095 | Train loss: 0.9994 | Train acc: 50.31% | Val loss: 0.9913 | Val acc: 54.43% | LR: 0.000004
Epoch: 096 | Train loss: 0.9960 | Train acc: 50.73% | Val loss: 0.9913 | Val acc: 54.43% | LR: 0.000004
Epoch: 097 | Train loss: 0.9973 | Train acc: 50.22% | Val loss: 0.9910 | Val acc: 54.46% | LR: 0.000004
Epoch: 098 | Train loss: 0.9962 | Train acc: 50.69% | Val loss: 0.9913 | Val acc: 54.42% | LR: 0.000004
Epoch: 099 | Train loss: 0.9943 | Train acc: 50.88% | Val loss: 0.9912 | Val acc: 54.38% | LR: 0.000004
Epoch: 100 | Train loss: 0.9925 | Train acc: 50.43% | Val loss: 0.9912 | Val acc: 54.35% | LR: 0.000004
Epoch: 101 | Train loss: 0.9973 | Train acc: 50.54% | Val loss: 0.9912 | Val acc: 54.35% | LR: 0.000004
Epoch: 102 | Train loss: 0.9922 | Train acc: 51.00% | Val loss: 0.9912 | Val acc: 54.31% | LR: 0.000004
Epoch: 103 | Train loss: 0.9929 | Train acc: 50.55% | Val loss: 0.9912 | Val acc: 54.31% | LR: 0.000003
Epoch: 104 | Train loss: 0.9952 | Train acc: 50.17% | Val loss: 0.9912 | Val acc: 54.31% | LR: 0.000003
Epoch: 105 | Train loss: 0.9930 | Train acc: 50.90% | Val loss: 0.9912 | Val acc: 54.31% | LR: 0.000003
Epoch: 106 | Train loss: 0.9944 | Train acc: 50.70% | Val loss: 0.9913 | Val acc: 54.35% | LR: 0.000003
Epoch: 107 | Train loss: 0.9985 | Train acc: 50.61% | Val loss: 0.9912 | Val acc: 54.35% | LR: 0.000003
Epoch: 108 | Train loss: 1.0127 | Train acc: 50.04% | Val loss: 0.9913 | Val acc: 54.35% | LR: 0.000003
Epoch: 109 | Train loss: 1.0027 | Train acc: 50.69% | Val loss: 0.9913 | Val acc: 54.35% | LR: 0.000003
Epoch: 110 | Train loss: 1.0037 | Train acc: 50.19% | Val loss: 0.9912 | Val acc: 54.29% | LR: 0.000003
Epoch: 111 | Train loss: 0.9952 | Train acc: 50.66% | Val loss: 0.9912 | Val acc: 54.29% | LR: 0.000003
Epoch: 112 | Train loss: 1.0139 | Train acc: 50.14% | Val loss: 0.9912 | Val acc: 54.29% | LR: 0.000003
Epoch: 113 | Train loss: 0.9941 | Train acc: 50.22% | Val loss: 0.9913 | Val acc: 54.31% | LR: 0.000003
Epoch: 114 | Train loss: 1.0045 | Train acc: 50.04% | Val loss: 0.9913 | Val acc: 54.31% | LR: 0.000002
Epoch: 115 | Train loss: 0.9980 | Train acc: 50.74% | Val loss: 0.9913 | Val acc: 54.31% | LR: 0.000002
Epoch: 116 | Train loss: 0.9961 | Train acc: 50.92% | Val loss: 0.9914 | Val acc: 54.31% | LR: 0.000002
Epoch: 117 | Train loss: 0.9966 | Train acc: 50.18% | Val loss: 0.9913 | Val acc: 54.29% | LR: 0.000002
Epoch: 118 | Train loss: 1.0078 | Train acc: 50.06% | Val loss: 0.9913 | Val acc: 54.29% | LR: 0.000002
Epoch: 119 | Train loss: 1.0069 | Train acc: 50.48% | Val loss: 0.9913 | Val acc: 54.29% | LR: 0.000002
Epoch: 120 | Train loss: 0.9967 | Train acc: 50.26% | Val loss: 0.9913 | Val acc: 54.27% | LR: 0.000002
Epoch: 121 | Train loss: 0.9933 | Train acc: 50.81% | Val loss: 0.9913 | Val acc: 54.31% | LR: 0.000002

[I 2025-09-23 18:38:11,169] Trial 121 finished with value: 0.5430724024772644 and parameters: {'lr': 1.2524499701650849e-05, 'hidden_size': 64, 'dropout': 0.22337026134509277, 'weight_decay': 4.8007786608048266e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0018 | Train acc: 49.62% | Val loss: 1.0005 | Val acc: 48.88% | LR: 0.000022
Epoch: 001 | Train loss: 1.0023 | Train acc: 49.17% | Val loss: 1.0008 | Val acc: 49.00% | LR: 0.000022
Epoch: 002 | Train loss: 1.0007 | Train acc: 50.25% | Val loss: 1.0005 | Val acc: 49.05% | LR: 0.000022
Epoch: 003 | Train loss: 1.0018 | Train acc: 49.31% | Val loss: 1.0007 | Val acc: 48.97% | LR: 0.000022
Epoch: 004 | Train loss: 1.0019 | Train acc: 49.66% | Val loss: 1.0008 | Val acc: 48.91% | LR: 0.000022
Epoch: 005 | Train loss: 1.0009 | Train acc: 49.85% | Val loss: 1.0004 | Val acc: 48.89% | LR: 0.000022
Epoch: 006 | Train loss: 1.0010 | Train acc: 50.01% | Val loss: 1.0005 | Val acc: 48.81% | LR: 0.000022
Epoch: 007 | Train loss: 1.0010 | Train acc: 49.58% | Val loss: 1.0009 | Val acc: 48.71% | LR: 0.000022
Epoch: 008 | Train loss: 1.0016 | Train acc: 49.61% | Val loss: 1.0002 | Val acc: 48.79% | LR: 0.000022
Epoch: 009 | Train loss: 1.0015 | Train acc: 49.70% | Val loss: 1.0026 | Val acc: 48.61% | LR: 0.000022
Epoch: 010 | Train loss: 1.0007 | Train acc: 49.67% | Val loss: 1.0009 | Val acc: 48.53% | LR: 0.000022
Epoch: 011 | Train loss: 1.0008 | Train acc: 49.73% | Val loss: 1.0006 | Val acc: 48.57% | LR: 0.000022
Epoch: 012 | Train loss: 1.0004 | Train acc: 49.59% | Val loss: 1.0005 | Val acc: 48.71% | LR: 0.000022
Epoch: 013 | Train loss: 1.0007 | Train acc: 49.93% | Val loss: 1.0005 | Val acc: 48.65% | LR: 0.000022
Epoch: 014 | Train loss: 1.0004 | Train acc: 50.12% | Val loss: 1.0005 | Val acc: 48.45% | LR: 0.000022
Epoch: 015 | Train loss: 1.0002 | Train acc: 49.83% | Val loss: 1.0012 | Val acc: 48.39% | LR: 0.000022
Epoch: 016 | Train loss: 1.0002 | Train acc: 50.08% | Val loss: 1.0006 | Val acc: 48.57% | LR: 0.000022
Epoch: 017 | Train loss: 1.0007 | Train acc: 50.06% | Val loss: 1.0007 | Val acc: 48.55% | LR: 0.000022
Epoch: 018 | Train loss: 1.0003 | Train acc: 50.06% | Val loss: 1.0002 | Val acc: 48.82% | LR: 0.000022
Epoch: 019 | Train loss: 1.0001 | Train acc: 50.66% | Val loss: 1.0004 | Val acc: 48.96% | LR: 0.000021
Epoch: 020 | Train loss: 1.0002 | Train acc: 50.57% | Val loss: 1.0005 | Val acc: 49.01% | LR: 0.000021
Epoch: 021 | Train loss: 1.0003 | Train acc: 50.22% | Val loss: 1.0008 | Val acc: 48.86% | LR: 0.000021
Epoch: 022 | Train loss: 0.9986 | Train acc: 51.29% | Val loss: 1.0007 | Val acc: 48.86% | LR: 0.000021
Epoch: 023 | Train loss: 1.0005 | Train acc: 50.01% | Val loss: 1.0006 | Val acc: 48.78% | LR: 0.000021
Epoch: 024 | Train loss: 0.9996 | Train acc: 50.67% | Val loss: 1.0002 | Val acc: 48.80% | LR: 0.000021
Epoch: 025 | Train loss: 1.0002 | Train acc: 50.15% | Val loss: 1.0009 | Val acc: 48.84% | LR: 0.000021
Epoch: 026 | Train loss: 0.9998 | Train acc: 50.21% | Val loss: 1.0014 | Val acc: 48.74% | LR: 0.000021
Epoch: 027 | Train loss: 1.0000 | Train acc: 50.21% | Val loss: 1.0009 | Val acc: 48.68% | LR: 0.000021
Epoch: 028 | Train loss: 1.0051 | Train acc: 50.34% | Val loss: 1.0009 | Val acc: 48.70% | LR: 0.000020
Epoch: 029 | Train loss: 1.0622 | Train acc: 49.82% | Val loss: 1.0007 | Val acc: 48.75% | LR: 0.000020
Epoch: 030 | Train loss: 1.0002 | Train acc: 50.25% | Val loss: 1.0005 | Val acc: 48.79% | LR: 0.000020
Epoch: 031 | Train loss: 1.0028 | Train acc: 50.17% | Val loss: 1.0007 | Val acc: 48.76% | LR: 0.000020
Epoch: 032 | Train loss: 1.0180 | Train acc: 50.39% | Val loss: 1.0007 | Val acc: 48.76% | LR: 0.000020
Epoch: 033 | Train loss: 1.0026 | Train acc: 50.14% | Val loss: 1.0006 | Val acc: 48.72% | LR: 0.000020
Epoch: 034 | Train loss: 1.0042 | Train acc: 50.33% | Val loss: 1.0009 | Val acc: 48.64% | LR: 0.000020
Epoch: 035 | Train loss: 1.0166 | Train acc: 50.28% | Val loss: 1.0008 | Val acc: 48.66% | LR: 0.000019
Epoch: 036 | Train loss: 1.0279 | Train acc: 50.78% | Val loss: 1.0006 | Val acc: 48.72% | LR: 0.000019
Epoch: 037 | Train loss: 1.0009 | Train acc: 50.07% | Val loss: 1.0009 | Val acc: 48.64% | LR: 0.000019
Epoch: 038 | Train loss: 1.0014 | Train acc: 50.98% | Val loss: 1.0008 | Val acc: 48.68% | LR: 0.000019
Epoch: 039 | Train loss: 1.0173 | Train acc: 50.30% | Val loss: 1.0005 | Val acc: 48.76% | LR: 0.000019
Epoch: 040 | Train loss: 1.0010 | Train acc: 50.28% | Val loss: 1.0005 | Val acc: 48.72% | LR: 0.000019
Epoch: 041 | Train loss: 0.9995 | Train acc: 50.45% | Val loss: 1.0009 | Val acc: 48.70% | LR: 0.000019
Epoch: 042 | Train loss: 0.9986 | Train acc: 50.83% | Val loss: 1.0007 | Val acc: 48.80% | LR: 0.000018
Epoch: 043 | Train loss: 0.9990 | Train acc: 50.76% | Val loss: 1.0009 | Val acc: 48.60% | LR: 0.000018
Epoch: 044 | Train loss: 1.0045 | Train acc: 50.72% | Val loss: 1.0012 | Val acc: 48.52% | LR: 0.000018
Epoch: 045 | Train loss: 0.9991 | Train acc: 50.42% | Val loss: 1.0016 | Val acc: 48.54% | LR: 0.000018
Epoch: 046 | Train loss: 0.9990 | Train acc: 50.42% | Val loss: 1.0012 | Val acc: 48.44% | LR: 0.000018
Epoch: 047 | Train loss: 0.9994 | Train acc: 50.26% | Val loss: 1.0005 | Val acc: 48.46% | LR: 0.000017
Epoch: 048 | Train loss: 0.9989 | Train acc: 50.42% | Val loss: 1.0009 | Val acc: 48.40% | LR: 0.000017
Epoch: 049 | Train loss: 0.9999 | Train acc: 50.18% | Val loss: 1.0010 | Val acc: 48.38% | LR: 0.000017
Epoch: 050 | Train loss: 0.9992 | Train acc: 50.28% | Val loss: 1.0010 | Val acc: 48.42% | LR: 0.000017
Epoch: 051 | Train loss: 0.9995 | Train acc: 50.30% | Val loss: 1.0005 | Val acc: 48.46% | LR: 0.000017

[I 2025-09-23 18:38:58,158] Trial 122 finished with value: 0.4851741373538971 and parameters: {'lr': 2.2391961281643895e-05, 'hidden_size': 71, 'dropout': 0.18153132375148331, 'weight_decay': 2.6549708474677358e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0025 | Train acc: 49.60% | Val loss: 1.0006 | Val acc: 48.96% | LR: 0.000016
Epoch: 001 | Train loss: 1.0024 | Train acc: 49.19% | Val loss: 1.0012 | Val acc: 48.90% | LR: 0.000016
Epoch: 002 | Train loss: 1.0006 | Train acc: 50.26% | Val loss: 1.0003 | Val acc: 48.92% | LR: 0.000016
Epoch: 003 | Train loss: 1.0017 | Train acc: 49.29% | Val loss: 1.0005 | Val acc: 49.10% | LR: 0.000016
Epoch: 004 | Train loss: 1.0021 | Train acc: 49.64% | Val loss: 1.0001 | Val acc: 49.06% | LR: 0.000016
Epoch: 005 | Train loss: 1.0009 | Train acc: 49.84% | Val loss: 1.0023 | Val acc: 49.00% | LR: 0.000016
Epoch: 006 | Train loss: 1.0009 | Train acc: 50.12% | Val loss: 1.0008 | Val acc: 48.91% | LR: 0.000016
Epoch: 007 | Train loss: 1.0012 | Train acc: 49.55% | Val loss: 1.0021 | Val acc: 48.86% | LR: 0.000016
Epoch: 008 | Train loss: 1.0017 | Train acc: 49.56% | Val loss: 1.0009 | Val acc: 48.90% | LR: 0.000016
Epoch: 009 | Train loss: 1.0015 | Train acc: 49.65% | Val loss: 1.0006 | Val acc: 48.84% | LR: 0.000016
Epoch: 010 | Train loss: 1.0010 | Train acc: 49.64% | Val loss: 1.0008 | Val acc: 48.60% | LR: 0.000016
Epoch: 011 | Train loss: 1.0010 | Train acc: 49.73% | Val loss: 1.0009 | Val acc: 48.56% | LR: 0.000016
Epoch: 012 | Train loss: 1.0009 | Train acc: 49.55% | Val loss: 1.0013 | Val acc: 48.53% | LR: 0.000016
Epoch: 013 | Train loss: 1.0010 | Train acc: 49.62% | Val loss: 1.0020 | Val acc: 48.60% | LR: 0.000016
Epoch: 014 | Train loss: 1.0013 | Train acc: 49.62% | Val loss: 1.0008 | Val acc: 48.48% | LR: 0.000016
Epoch: 015 | Train loss: 1.0005 | Train acc: 50.05% | Val loss: 1.0004 | Val acc: 48.48% | LR: 0.000016
Epoch: 016 | Train loss: 1.0006 | Train acc: 49.61% | Val loss: 1.0023 | Val acc: 48.58% | LR: 0.000016
Epoch: 017 | Train loss: 1.0012 | Train acc: 49.51% | Val loss: 1.0007 | Val acc: 48.50% | LR: 0.000016
Epoch: 018 | Train loss: 1.0006 | Train acc: 49.60% | Val loss: 1.0009 | Val acc: 48.42% | LR: 0.000016
Epoch: 019 | Train loss: 1.0005 | Train acc: 50.04% | Val loss: 1.0010 | Val acc: 48.56% | LR: 0.000016
Epoch: 020 | Train loss: 1.0006 | Train acc: 49.96% | Val loss: 1.0018 | Val acc: 48.60% | LR: 0.000016
Epoch: 021 | Train loss: 1.0006 | Train acc: 49.81% | Val loss: 1.0008 | Val acc: 48.51% | LR: 0.000016
Epoch: 022 | Train loss: 0.9997 | Train acc: 50.91% | Val loss: 1.0012 | Val acc: 48.31% | LR: 0.000016
Epoch: 023 | Train loss: 1.0006 | Train acc: 50.01% | Val loss: 1.0007 | Val acc: 48.47% | LR: 0.000015
Epoch: 024 | Train loss: 0.9999 | Train acc: 50.65% | Val loss: 1.0003 | Val acc: 48.49% | LR: 0.000015
Epoch: 025 | Train loss: 1.0007 | Train acc: 50.07% | Val loss: 1.0017 | Val acc: 48.43% | LR: 0.000015
Epoch: 026 | Train loss: 1.0002 | Train acc: 50.16% | Val loss: 1.0005 | Val acc: 48.47% | LR: 0.000015
Epoch: 027 | Train loss: 1.0005 | Train acc: 50.19% | Val loss: 1.0007 | Val acc: 48.49% | LR: 0.000015
Epoch: 028 | Train loss: 1.0004 | Train acc: 50.37% | Val loss: 1.0007 | Val acc: 48.53% | LR: 0.000015
Epoch: 029 | Train loss: 1.0001 | Train acc: 50.28% | Val loss: 1.0011 | Val acc: 48.49% | LR: 0.000015
Epoch: 030 | Train loss: 0.9999 | Train acc: 50.38% | Val loss: 1.0010 | Val acc: 48.43% | LR: 0.000015
Epoch: 031 | Train loss: 1.0002 | Train acc: 50.47% | Val loss: 1.0003 | Val acc: 48.51% | LR: 0.000015
Epoch: 032 | Train loss: 0.9990 | Train acc: 50.83% | Val loss: 1.0011 | Val acc: 48.35% | LR: 0.000015
Epoch: 033 | Train loss: 0.9993 | Train acc: 50.65% | Val loss: 1.0011 | Val acc: 48.48% | LR: 0.000015
Epoch: 034 | Train loss: 0.9994 | Train acc: 50.54% | Val loss: 1.0010 | Val acc: 48.38% | LR: 0.000014
Epoch: 035 | Train loss: 1.0008 | Train acc: 50.07% | Val loss: 1.0007 | Val acc: 48.44% | LR: 0.000014
Epoch: 036 | Train loss: 0.9990 | Train acc: 50.59% | Val loss: 1.0011 | Val acc: 48.38% | LR: 0.000014
Epoch: 037 | Train loss: 1.0007 | Train acc: 50.07% | Val loss: 1.0011 | Val acc: 48.48% | LR: 0.000014
Epoch: 038 | Train loss: 1.0125 | Train acc: 50.89% | Val loss: 1.0013 | Val acc: 48.56% | LR: 0.000014
Epoch: 039 | Train loss: 1.0203 | Train acc: 50.27% | Val loss: 1.0013 | Val acc: 48.60% | LR: 0.000014
Epoch: 040 | Train loss: 0.9988 | Train acc: 50.26% | Val loss: 1.0011 | Val acc: 48.64% | LR: 0.000014
Epoch: 041 | Train loss: 0.9986 | Train acc: 50.41% | Val loss: 1.0010 | Val acc: 48.64% | LR: 0.000014
Epoch: 042 | Train loss: 0.9960 | Train acc: 50.76% | Val loss: 1.0009 | Val acc: 48.70% | LR: 0.000014
Epoch: 043 | Train loss: 0.9974 | Train acc: 50.64% | Val loss: 1.0007 | Val acc: 48.70% | LR: 0.000013
Epoch: 044 | Train loss: 0.9977 | Train acc: 50.71% | Val loss: 1.0011 | Val acc: 48.67% | LR: 0.000013
Epoch: 045 | Train loss: 0.9986 | Train acc: 50.47% | Val loss: 1.0009 | Val acc: 48.67% | LR: 0.000013
Epoch: 046 | Train loss: 0.9986 | Train acc: 50.46% | Val loss: 1.0008 | Val acc: 48.70% | LR: 0.000013
Epoch: 047 | Train loss: 0.9992 | Train acc: 50.30% | Val loss: 1.0006 | Val acc: 48.70% | LR: 0.000013
Epoch: 048 | Train loss: 0.9988 | Train acc: 50.39% | Val loss: 1.0006 | Val acc: 48.73% | LR: 0.000013
Epoch: 049 | Train loss: 0.9994 | Train acc: 50.22% | Val loss: 1.0008 | Val acc: 48.75% | LR: 0.000013
Epoch: 050 | Train loss: 0.9987 | Train acc: 50.32% | Val loss: 1.0009 | Val acc: 48.72% | LR: 0.000012
Epoch: 051 | Train loss: 0.9980 | Train acc: 50.51% | Val loss: 1.0007 | Val acc: 48.75% | LR: 0.000012
Epoch: 052 | Train loss: 0.9990 | Train acc: 50.67% | Val loss: 1.0007 | Val acc: 48.72% | LR: 0.000012

[I 2025-09-23 18:39:43,562] Trial 123 finished with value: 0.4868518769741058 and parameters: {'lr': 1.6434092776232276e-05, 'hidden_size': 71, 'dropout': 0.19470204338094807, 'weight_decay': 1.7213746265548996e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0030 | Train acc: 50.28% | Val loss: 1.0058 | Val acc: 47.30% | LR: 0.000011
Epoch: 001 | Train loss: 1.0011 | Train acc: 49.78% | Val loss: 1.0091 | Val acc: 47.62% | LR: 0.000011
Epoch: 002 | Train loss: 1.0017 | Train acc: 50.04% | Val loss: 1.0530 | Val acc: 47.15% | LR: 0.000011
Epoch: 003 | Train loss: 0.9993 | Train acc: 50.31% | Val loss: 1.0589 | Val acc: 47.36% | LR: 0.000011
Epoch: 004 | Train loss: 0.9995 | Train acc: 50.07% | Val loss: 1.0049 | Val acc: 47.38% | LR: 0.000011
Epoch: 005 | Train loss: 1.0013 | Train acc: 49.95% | Val loss: 1.0062 | Val acc: 47.32% | LR: 0.000011
Epoch: 006 | Train loss: 0.9993 | Train acc: 50.55% | Val loss: 1.0049 | Val acc: 47.44% | LR: 0.000011
Epoch: 007 | Train loss: 0.9994 | Train acc: 50.21% | Val loss: 1.0047 | Val acc: 47.74% | LR: 0.000011
Epoch: 008 | Train loss: 0.9984 | Train acc: 50.64% | Val loss: 1.0056 | Val acc: 47.54% | LR: 0.000011
Epoch: 009 | Train loss: 0.9989 | Train acc: 50.99% | Val loss: 1.0047 | Val acc: 47.56% | LR: 0.000011
Epoch: 010 | Train loss: 1.0020 | Train acc: 50.44% | Val loss: 1.0069 | Val acc: 47.56% | LR: 0.000011
Epoch: 011 | Train loss: 1.0087 | Train acc: 50.37% | Val loss: 1.0037 | Val acc: 47.67% | LR: 0.000011
Epoch: 012 | Train loss: 1.0032 | Train acc: 50.51% | Val loss: 1.0091 | Val acc: 47.69% | LR: 0.000011
Epoch: 013 | Train loss: 1.0006 | Train acc: 50.19% | Val loss: 1.0054 | Val acc: 47.82% | LR: 0.000011
Epoch: 014 | Train loss: 1.0107 | Train acc: 50.46% | Val loss: 1.0069 | Val acc: 47.76% | LR: 0.000011
Epoch: 015 | Train loss: 1.0009 | Train acc: 50.34% | Val loss: 1.0118 | Val acc: 47.96% | LR: 0.000011
Epoch: 016 | Train loss: 0.9981 | Train acc: 50.53% | Val loss: 1.0042 | Val acc: 47.98% | LR: 0.000011
Epoch: 017 | Train loss: 1.0002 | Train acc: 50.30% | Val loss: 1.0064 | Val acc: 47.84% | LR: 0.000011
Epoch: 018 | Train loss: 0.9974 | Train acc: 50.95% | Val loss: 1.0176 | Val acc: 47.96% | LR: 0.000010
Epoch: 019 | Train loss: 1.0008 | Train acc: 50.25% | Val loss: 1.0085 | Val acc: 47.74% | LR: 0.000010
Epoch: 020 | Train loss: 1.0005 | Train acc: 50.29% | Val loss: 1.0350 | Val acc: 47.76% | LR: 0.000010
Epoch: 021 | Train loss: 1.0018 | Train acc: 49.69% | Val loss: 1.0049 | Val acc: 47.78% | LR: 0.000010
Epoch: 022 | Train loss: 0.9995 | Train acc: 50.34% | Val loss: 1.0102 | Val acc: 47.74% | LR: 0.000010
Epoch: 023 | Train loss: 1.0005 | Train acc: 50.25% | Val loss: 1.0098 | Val acc: 47.77% | LR: 0.000010
Epoch: 024 | Train loss: 0.9999 | Train acc: 50.32% | Val loss: 1.0187 | Val acc: 47.68% | LR: 0.000010
Epoch: 025 | Train loss: 1.0041 | Train acc: 50.55% | Val loss: 1.0091 | Val acc: 47.84% | LR: 0.000010
Epoch: 026 | Train loss: 1.0016 | Train acc: 50.10% | Val loss: 1.0044 | Val acc: 47.78% | LR: 0.000010
Epoch: 027 | Train loss: 1.0009 | Train acc: 50.09% | Val loss: 1.0059 | Val acc: 47.76% | LR: 0.000010
Epoch: 028 | Train loss: 1.0018 | Train acc: 50.36% | Val loss: 1.0061 | Val acc: 47.74% | LR: 0.000010
Epoch: 029 | Train loss: 1.0017 | Train acc: 49.92% | Val loss: 1.0059 | Val acc: 47.76% | LR: 0.000010
Epoch: 030 | Train loss: 1.0010 | Train acc: 50.51% | Val loss: 1.0117 | Val acc: 47.78% | LR: 0.000010
Epoch: 031 | Train loss: 1.0041 | Train acc: 50.37% | Val loss: 1.0060 | Val acc: 47.86% | LR: 0.000010
Epoch: 032 | Train loss: 1.0006 | Train acc: 50.04% | Val loss: 1.0041 | Val acc: 48.02% | LR: 0.000010
Epoch: 033 | Train loss: 1.0003 | Train acc: 50.22% | Val loss: 1.0210 | Val acc: 47.88% | LR: 0.000010
Epoch: 034 | Train loss: 1.0001 | Train acc: 50.65% | Val loss: 1.0055 | Val acc: 47.84% | LR: 0.000010
Epoch: 035 | Train loss: 1.0078 | Train acc: 50.30% | Val loss: 1.0037 | Val acc: 47.78% | LR: 0.000010
Epoch: 036 | Train loss: 0.9964 | Train acc: 51.09% | Val loss: 1.0048 | Val acc: 47.70% | LR: 0.000009
Epoch: 037 | Train loss: 0.9987 | Train acc: 50.16% | Val loss: 1.0100 | Val acc: 47.68% | LR: 0.000009
Epoch: 038 | Train loss: 1.0039 | Train acc: 50.73% | Val loss: 1.0055 | Val acc: 47.77% | LR: 0.000009
Epoch: 039 | Train loss: 1.0011 | Train acc: 50.01% | Val loss: 1.0064 | Val acc: 47.72% | LR: 0.000009
Epoch: 040 | Train loss: 0.9989 | Train acc: 50.81% | Val loss: 1.0048 | Val acc: 47.67% | LR: 0.000009
Epoch: 041 | Train loss: 1.0010 | Train acc: 50.28% | Val loss: 1.0035 | Val acc: 47.82% | LR: 0.000009
Epoch: 042 | Train loss: 1.0057 | Train acc: 49.76% | Val loss: 1.0068 | Val acc: 47.86% | LR: 0.000009
Epoch: 043 | Train loss: 1.0020 | Train acc: 50.22% | Val loss: 1.0077 | Val acc: 47.88% | LR: 0.000009
Epoch: 044 | Train loss: 0.9986 | Train acc: 50.35% | Val loss: 1.0055 | Val acc: 47.82% | LR: 0.000009
Epoch: 045 | Train loss: 0.9971 | Train acc: 50.75% | Val loss: 1.0058 | Val acc: 47.56% | LR: 0.000009
Epoch: 046 | Train loss: 0.9974 | Train acc: 50.74% | Val loss: 1.0145 | Val acc: 47.50% | LR: 0.000009
Epoch: 047 | Train loss: 0.9989 | Train acc: 50.26% | Val loss: 1.0074 | Val acc: 47.88% | LR: 0.000009
Epoch: 048 | Train loss: 0.9987 | Train acc: 50.48% | Val loss: 1.0066 | Val acc: 47.76% | LR: 0.000009
Epoch: 049 | Train loss: 0.9990 | Train acc: 50.47% | Val loss: 1.0045 | Val acc: 47.60% | LR: 0.000008
Epoch: 050 | Train loss: 0.9985 | Train acc: 50.45% | Val loss: 1.0048 | Val acc: 47.60% | LR: 0.000008
Epoch: 051 | Train loss: 1.0004 | Train acc: 49.98% | Val loss: 1.0044 | Val acc: 47.68% | LR: 0.000008
Epoch: 052 | Train loss: 0.9997 | Train acc: 50.32% | Val loss: 1.0039 | Val acc: 47.86% | LR: 0.000008
Epoch: 053 | Train loss: 0.9991 | Train acc: 50.26% | Val loss: 1.0062 | Val acc: 47.62% | LR: 0.000008
Epoch: 054 | Train loss: 0.9980 | Train acc: 50.39% | Val loss: 1.0047 | Val acc: 47.64% | LR: 0.000008
Epoch: 055 | Train loss: 0.9994 | Train acc: 50.76% | Val loss: 1.0104 | Val acc: 47.68% | LR: 0.000008
Epoch: 056 | Train loss: 0.9994 | Train acc: 50.22% | Val loss: 1.0068 | Val acc: 47.70% | LR: 0.000008
Epoch: 057 | Train loss: 1.0014 | Train acc: 49.86% | Val loss: 1.0055 | Val acc: 47.72% | LR: 0.000008
Epoch: 058 | Train loss: 0.9985 | Train acc: 50.36% | Val loss: 1.0040 | Val acc: 47.80% | LR: 0.000008
Epoch: 059 | Train loss: 0.9987 | Train acc: 50.24% | Val loss: 1.0041 | Val acc: 47.60% | LR: 0.000007
Epoch: 060 | Train loss: 1.0034 | Train acc: 50.08% | Val loss: 1.0093 | Val acc: 47.80% | LR: 0.000007
Epoch: 061 | Train loss: 1.0005 | Train acc: 50.56% | Val loss: 1.0044 | Val acc: 47.68% | LR: 0.000007
Epoch: 062 | Train loss: 0.9959 | Train acc: 50.68% | Val loss: 1.0056 | Val acc: 47.76% | LR: 0.000007
Epoch: 063 | Train loss: 1.0006 | Train acc: 50.13% | Val loss: 1.0101 | Val acc: 47.62% | LR: 0.000007
Epoch: 064 | Train loss: 0.9978 | Train acc: 50.47% | Val loss: 1.0043 | Val acc: 47.76% | LR: 0.000007
Epoch: 065 | Train loss: 0.9962 | Train acc: 50.84% | Val loss: 1.0066 | Val acc: 47.78% | LR: 0.000007
Epoch: 066 | Train loss: 0.9998 | Train acc: 50.29% | Val loss: 1.0050 | Val acc: 47.74% | LR: 0.000007
Epoch: 067 | Train loss: 1.0007 | Train acc: 50.12% | Val loss: 1.0053 | Val acc: 47.62% | LR: 0.000007
Epoch: 068 | Train loss: 1.0007 | Train acc: 50.40% | Val loss: 1.0044 | Val acc: 47.68% | LR: 0.000007
Epoch: 069 | Train loss: 0.9996 | Train acc: 50.21% | Val loss: 1.0050 | Val acc: 47.58% | LR: 0.000006
Epoch: 070 | Train loss: 0.9984 | Train acc: 50.48% | Val loss: 1.0062 | Val acc: 47.60% | LR: 0.000006
Epoch: 071 | Train loss: 1.0013 | Train acc: 50.12% | Val loss: 1.0045 | Val acc: 47.68% | LR: 0.000006
Epoch: 072 | Train loss: 0.9993 | Train acc: 50.30% | Val loss: 1.0043 | Val acc: 47.68% | LR: 0.000006
Epoch: 073 | Train loss: 0.9958 | Train acc: 50.67% | Val loss: 1.0044 | Val acc: 47.72% | LR: 0.000006
Epoch: 074 | Train loss: 1.0000 | Train acc: 50.30% | Val loss: 1.0039 | Val acc: 47.78% | LR: 0.000006
Epoch: 075 | Train loss: 0.9954 | Train acc: 50.92% | Val loss: 1.0269 | Val acc: 47.60% | LR: 0.000006
Epoch: 076 | Train loss: 0.9977 | Train acc: 50.49% | Val loss: 1.0070 | Val acc: 47.62% | LR: 0.000006
Epoch: 077 | Train loss: 0.9978 | Train acc: 50.50% | Val loss: 1.0045 | Val acc: 47.70% | LR: 0.000006
Epoch: 078 | Train loss: 0.9966 | Train acc: 50.77% | Val loss: 1.0044 | Val acc: 47.72% | LR: 0.000006
Epoch: 079 | Train loss: 0.9981 | Train acc: 50.23% | Val loss: 1.0047 | Val acc: 47.58% | LR: 0.000005
Epoch: 080 | Train loss: 0.9990 | Train acc: 50.30% | Val loss: 1.0105 | Val acc: 47.69% | LR: 0.000005
Epoch: 081 | Train loss: 0.9979 | Train acc: 50.47% | Val loss: 1.0053 | Val acc: 47.61% | LR: 0.000005

[I 2025-09-23 18:40:56,180] Trial 124 finished with value: 0.4745951533317566 and parameters: {'lr': 1.0884001036890974e-05, 'hidden_size': 79, 'dropout': 0.21509059696315205, 'weight_decay': 9.93014843996033e-06}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0005 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.07% | LR: 0.000013
Epoch: 001 | Train loss: 1.0008 | Train acc: 49.72% | Val loss: 0.9917 | Val acc: 54.09% | LR: 0.000013
Epoch: 002 | Train loss: 1.0005 | Train acc: 49.54% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000013
Epoch: 003 | Train loss: 1.0008 | Train acc: 49.54% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000013
Epoch: 004 | Train loss: 1.0014 | Train acc: 49.37% | Val loss: 0.9918 | Val acc: 54.11% | LR: 0.000013
Epoch: 005 | Train loss: 0.9989 | Train acc: 49.81% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000013
Epoch: 006 | Train loss: 1.0009 | Train acc: 49.57% | Val loss: 0.9919 | Val acc: 54.17% | LR: 0.000013
Epoch: 007 | Train loss: 1.0016 | Train acc: 49.44% | Val loss: 0.9919 | Val acc: 54.17% | LR: 0.000013
Epoch: 008 | Train loss: 1.0011 | Train acc: 49.58% | Val loss: 0.9920 | Val acc: 54.28% | LR: 0.000013
Epoch: 009 | Train loss: 0.9993 | Train acc: 50.38% | Val loss: 0.9921 | Val acc: 54.34% | LR: 0.000013
Epoch: 010 | Train loss: 0.9988 | Train acc: 50.62% | Val loss: 0.9921 | Val acc: 54.32% | LR: 0.000013
Epoch: 011 | Train loss: 0.9987 | Train acc: 50.71% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000013
Epoch: 012 | Train loss: 0.9984 | Train acc: 50.65% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000013
Epoch: 013 | Train loss: 0.9998 | Train acc: 50.46% | Val loss: 0.9919 | Val acc: 54.30% | LR: 0.000013
Epoch: 014 | Train loss: 0.9985 | Train acc: 50.46% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000013
Epoch: 015 | Train loss: 1.0000 | Train acc: 50.03% | Val loss: 0.9920 | Val acc: 54.28% | LR: 0.000013
Epoch: 016 | Train loss: 0.9984 | Train acc: 50.46% | Val loss: 0.9921 | Val acc: 54.26% | LR: 0.000013
Epoch: 017 | Train loss: 0.9992 | Train acc: 50.37% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000013
Epoch: 018 | Train loss: 0.9995 | Train acc: 50.12% | Val loss: 0.9919 | Val acc: 54.32% | LR: 0.000013
Epoch: 019 | Train loss: 0.9991 | Train acc: 50.32% | Val loss: 0.9920 | Val acc: 54.36% | LR: 0.000013
Epoch: 020 | Train loss: 0.9967 | Train acc: 51.15% | Val loss: 0.9919 | Val acc: 54.36% | LR: 0.000013
Epoch: 021 | Train loss: 0.9981 | Train acc: 50.64% | Val loss: 0.9919 | Val acc: 54.36% | LR: 0.000013
Epoch: 022 | Train loss: 0.9973 | Train acc: 50.76% | Val loss: 0.9918 | Val acc: 54.38% | LR: 0.000013
Epoch: 023 | Train loss: 0.9987 | Train acc: 50.34% | Val loss: 0.9920 | Val acc: 54.34% | LR: 0.000012
Epoch: 024 | Train loss: 0.9986 | Train acc: 50.33% | Val loss: 0.9918 | Val acc: 54.44% | LR: 0.000012
Epoch: 025 | Train loss: 0.9996 | Train acc: 50.06% | Val loss: 0.9918 | Val acc: 54.46% | LR: 0.000012
Epoch: 026 | Train loss: 0.9988 | Train acc: 50.24% | Val loss: 0.9918 | Val acc: 54.44% | LR: 0.000012
Epoch: 027 | Train loss: 0.9975 | Train acc: 50.79% | Val loss: 0.9918 | Val acc: 54.40% | LR: 0.000012
Epoch: 028 | Train loss: 0.9970 | Train acc: 50.79% | Val loss: 0.9917 | Val acc: 54.42% | LR: 0.000012
Epoch: 029 | Train loss: 0.9981 | Train acc: 50.76% | Val loss: 0.9918 | Val acc: 54.31% | LR: 0.000012
Epoch: 030 | Train loss: 0.9989 | Train acc: 50.41% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000012
Epoch: 031 | Train loss: 0.9986 | Train acc: 50.31% | Val loss: 0.9917 | Val acc: 54.30% | LR: 0.000012
Epoch: 032 | Train loss: 0.9972 | Train acc: 51.01% | Val loss: 0.9917 | Val acc: 54.26% | LR: 0.000012
Epoch: 033 | Train loss: 0.9993 | Train acc: 49.86% | Val loss: 0.9918 | Val acc: 54.18% | LR: 0.000012
Epoch: 034 | Train loss: 0.9966 | Train acc: 50.87% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000012
Epoch: 035 | Train loss: 0.9987 | Train acc: 50.33% | Val loss: 0.9916 | Val acc: 54.24% | LR: 0.000012
Epoch: 036 | Train loss: 0.9980 | Train acc: 50.44% | Val loss: 0.9920 | Val acc: 54.26% | LR: 0.000012
Epoch: 037 | Train loss: 0.9982 | Train acc: 50.38% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000011
Epoch: 038 | Train loss: 0.9986 | Train acc: 50.28% | Val loss: 0.9918 | Val acc: 54.43% | LR: 0.000011
Epoch: 039 | Train loss: 0.9970 | Train acc: 50.83% | Val loss: 0.9917 | Val acc: 54.39% | LR: 0.000011
Epoch: 040 | Train loss: 0.9975 | Train acc: 50.74% | Val loss: 0.9915 | Val acc: 54.33% | LR: 0.000011
Epoch: 041 | Train loss: 0.9975 | Train acc: 50.60% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000011
Epoch: 042 | Train loss: 0.9984 | Train acc: 50.33% | Val loss: 0.9918 | Val acc: 54.27% | LR: 0.000011
Epoch: 043 | Train loss: 0.9980 | Train acc: 50.50% | Val loss: 0.9919 | Val acc: 54.33% | LR: 0.000011
Epoch: 044 | Train loss: 0.9983 | Train acc: 50.24% | Val loss: 0.9920 | Val acc: 54.31% | LR: 0.000011
Epoch: 045 | Train loss: 0.9973 | Train acc: 50.57% | Val loss: 0.9918 | Val acc: 54.33% | LR: 0.000011
Epoch: 046 | Train loss: 0.9966 | Train acc: 50.91% | Val loss: 0.9928 | Val acc: 54.33% | LR: 0.000011
Epoch: 047 | Train loss: 0.9992 | Train acc: 50.12% | Val loss: 0.9918 | Val acc: 54.36% | LR: 0.000010
Epoch: 048 | Train loss: 0.9980 | Train acc: 50.56% | Val loss: 0.9920 | Val acc: 54.42% | LR: 0.000010
Epoch: 049 | Train loss: 0.9978 | Train acc: 50.51% | Val loss: 0.9919 | Val acc: 54.44% | LR: 0.000010
Epoch: 050 | Train loss: 0.9989 | Train acc: 50.34% | Val loss: 0.9921 | Val acc: 54.46% | LR: 0.000010
Epoch: 051 | Train loss: 0.9971 | Train acc: 50.44% | Val loss: 0.9917 | Val acc: 54.49% | LR: 0.000010
Epoch: 052 | Train loss: 0.9986 | Train acc: 50.45% | Val loss: 0.9919 | Val acc: 54.33% | LR: 0.000010
Epoch: 053 | Train loss: 0.9979 | Train acc: 50.29% | Val loss: 0.9919 | Val acc: 54.27% | LR: 0.000010
Epoch: 054 | Train loss: 0.9968 | Train acc: 50.71% | Val loss: 0.9923 | Val acc: 54.31% | LR: 0.000010
Epoch: 055 | Train loss: 0.9966 | Train acc: 50.72% | Val loss: 0.9918 | Val acc: 54.36% | LR: 0.000009
Epoch: 056 | Train loss: 0.9964 | Train acc: 50.92% | Val loss: 0.9929 | Val acc: 54.33% | LR: 0.000009
Epoch: 057 | Train loss: 0.9977 | Train acc: 50.35% | Val loss: 0.9921 | Val acc: 54.42% | LR: 0.000009
Epoch: 058 | Train loss: 0.9980 | Train acc: 50.46% | Val loss: 0.9925 | Val acc: 54.33% | LR: 0.000009
Epoch: 059 | Train loss: 0.9967 | Train acc: 51.00% | Val loss: 0.9919 | Val acc: 54.35% | LR: 0.000009
Epoch: 060 | Train loss: 0.9966 | Train acc: 50.68% | Val loss: 0.9920 | Val acc: 54.37% | LR: 0.000009
Epoch: 061 | Train loss: 0.9964 | Train acc: 50.45% | Val loss: 0.9919 | Val acc: 54.33% | LR: 0.000009
Epoch: 062 | Train loss: 0.9964 | Train acc: 50.52% | Val loss: 0.9917 | Val acc: 54.43% | LR: 0.000009
Epoch: 063 | Train loss: 0.9980 | Train acc: 50.44% | Val loss: 0.9919 | Val acc: 54.52% | LR: 0.000009
Epoch: 064 | Train loss: 0.9971 | Train acc: 50.79% | Val loss: 0.9921 | Val acc: 54.50% | LR: 0.000008
Epoch: 065 | Train loss: 0.9964 | Train acc: 50.79% | Val loss: 0.9920 | Val acc: 54.42% | LR: 0.000008
Epoch: 066 | Train loss: 0.9979 | Train acc: 50.28% | Val loss: 0.9920 | Val acc: 54.39% | LR: 0.000008
Epoch: 067 | Train loss: 0.9963 | Train acc: 51.23% | Val loss: 0.9920 | Val acc: 54.50% | LR: 0.000008
Epoch: 068 | Train loss: 0.9971 | Train acc: 50.80% | Val loss: 0.9938 | Val acc: 54.54% | LR: 0.000008
Epoch: 069 | Train loss: 0.9971 | Train acc: 50.51% | Val loss: 0.9921 | Val acc: 54.62% | LR: 0.000008
Epoch: 070 | Train loss: 0.9953 | Train acc: 50.95% | Val loss: 0.9920 | Val acc: 54.54% | LR: 0.000008
Epoch: 071 | Train loss: 0.9973 | Train acc: 50.72% | Val loss: 0.9920 | Val acc: 54.62% | LR: 0.000008
Epoch: 072 | Train loss: 0.9953 | Train acc: 50.72% | Val loss: 0.9921 | Val acc: 54.54% | LR: 0.000007
Epoch: 073 | Train loss: 0.9971 | Train acc: 50.09% | Val loss: 0.9920 | Val acc: 54.56% | LR: 0.000007
Epoch: 074 | Train loss: 0.9947 | Train acc: 51.36% | Val loss: 0.9920 | Val acc: 54.60% | LR: 0.000007
Epoch: 075 | Train loss: 0.9955 | Train acc: 51.09% | Val loss: 0.9921 | Val acc: 54.55% | LR: 0.000007
Epoch: 076 | Train loss: 0.9971 | Train acc: 50.57% | Val loss: 0.9920 | Val acc: 54.55% | LR: 0.000007
Epoch: 077 | Train loss: 0.9969 | Train acc: 50.97% | Val loss: 0.9922 | Val acc: 54.52% | LR: 0.000007
Epoch: 078 | Train loss: 0.9955 | Train acc: 51.00% | Val loss: 0.9929 | Val acc: 54.52% | LR: 0.000007
Epoch: 079 | Train loss: 0.9962 | Train acc: 50.92% | Val loss: 0.9921 | Val acc: 54.50% | LR: 0.000006
Epoch: 080 | Train loss: 0.9957 | Train acc: 50.67% | Val loss: 0.9922 | Val acc: 54.52% | LR: 0.000006
Epoch: 081 | Train loss: 0.9958 | Train acc: 50.92% | Val loss: 0.9925 | Val acc: 54.60% | LR: 0.000006
Epoch: 082 | Train loss: 0.9961 | Train acc: 50.40% | Val loss: 0.9921 | Val acc: 54.60% | LR: 0.000006
Epoch: 083 | Train loss: 0.9965 | Train acc: 50.67% | Val loss: 0.9930 | Val acc: 54.60% | LR: 0.000006
Epoch: 084 | Train loss: 0.9957 | Train acc: 50.83% | Val loss: 0.9922 | Val acc: 54.60% | LR: 0.000006
Epoch: 085 | Train loss: 0.9977 | Train acc: 50.41% | Val loss: 0.9923 | Val acc: 54.56% | LR: 0.000006
Epoch: 086 | Train loss: 0.9960 | Train acc: 50.86% | Val loss: 0.9939 | Val acc: 54.56% | LR: 0.000006
Epoch: 087 | Train loss: 0.9949 | Train acc: 51.20% | Val loss: 0.9921 | Val acc: 54.54% | LR: 0.000005
Epoch: 088 | Train loss: 0.9959 | Train acc: 50.69% | Val loss: 0.9921 | Val acc: 54.54% | LR: 0.000005
Epoch: 089 | Train loss: 0.9962 | Train acc: 50.68% | Val loss: 0.9936 | Val acc: 54.50% | LR: 0.000005
Epoch: 090 | Train loss: 0.9963 | Train acc: 50.84% | Val loss: 0.9921 | Val acc: 54.42% | LR: 0.000005
Epoch: 091 | Train loss: 0.9960 | Train acc: 50.58% | Val loss: 0.9921 | Val acc: 54.38% | LR: 0.000005
Epoch: 092 | Train loss: 0.9942 | Train acc: 51.47% | Val loss: 0.9921 | Val acc: 54.50% | LR: 0.000005
Epoch: 093 | Train loss: 0.9954 | Train acc: 50.74% | Val loss: 0.9963 | Val acc: 54.46% | LR: 0.000005
Epoch: 094 | Train loss: 0.9952 | Train acc: 50.51% | Val loss: 0.9933 | Val acc: 54.48% | LR: 0.000005
Epoch: 095 | Train loss: 0.9971 | Train acc: 50.44% | Val loss: 0.9925 | Val acc: 54.48% | LR: 0.000005
Epoch: 096 | Train loss: 0.9945 | Train acc: 51.23% | Val loss: 0.9919 | Val acc: 54.54% | LR: 0.000004
Epoch: 097 | Train loss: 0.9957 | Train acc: 50.96% | Val loss: 0.9930 | Val acc: 54.52% | LR: 0.000004
Epoch: 098 | Train loss: 0.9974 | Train acc: 50.26% | Val loss: 0.9921 | Val acc: 54.48% | LR: 0.000004
Epoch: 099 | Train loss: 0.9964 | Train acc: 50.51% | Val loss: 0.9922 | Val acc: 54.45% | LR: 0.000004
Epoch: 100 | Train loss: 0.9936 | Train acc: 51.76% | Val loss: 0.9922 | Val acc: 54.53% | LR: 0.000004
Epoch: 101 | Train loss: 0.9954 | Train acc: 50.77% | Val loss: 0.9922 | Val acc: 54.51% | LR: 0.000004
Epoch: 102 | Train loss: 0.9950 | Train acc: 50.94% | Val loss: 0.9921 | Val acc: 54.53% | LR: 0.000004
Epoch: 103 | Train loss: 0.9957 | Train acc: 50.77% | Val loss: 0.9921 | Val acc: 54.51% | LR: 0.000004
Epoch: 104 | Train loss: 0.9960 | Train acc: 50.96% | Val loss: 0.9922 | Val acc: 54.47% | LR: 0.000004
Epoch: 105 | Train loss: 0.9958 | Train acc: 50.33% | Val loss: 0.9925 | Val acc: 54.45% | LR: 0.000003
Epoch: 106 | Train loss: 0.9959 | Train acc: 50.51% | Val loss: 0.9922 | Val acc: 54.43% | LR: 0.000003
Epoch: 107 | Train loss: 0.9958 | Train acc: 50.79% | Val loss: 0.9921 | Val acc: 54.47% | LR: 0.000003
Epoch: 108 | Train loss: 0.9968 | Train acc: 50.78% | Val loss: 0.9922 | Val acc: 54.49% | LR: 0.000003
Epoch: 109 | Train loss: 0.9965 | Train acc: 50.33% | Val loss: 0.9921 | Val acc: 54.55% | LR: 0.000003
Epoch: 110 | Train loss: 0.9949 | Train acc: 51.13% | Val loss: 0.9921 | Val acc: 54.53% | LR: 0.000003
Epoch: 111 | Train loss: 0.9945 | Train acc: 51.05% | Val loss: 0.9921 | Val acc: 54.53% | LR: 0.000003
Epoch: 112 | Train loss: 0.9953 | Train acc: 50.96% | Val loss: 0.9921 | Val acc: 54.53% | LR: 0.000003
Epoch: 113 | Train loss: 0.9947 | Train acc: 51.04% | Val loss: 0.9936 | Val acc: 54.57% | LR: 0.000003
Epoch: 114 | Train loss: 0.9948 | Train acc: 51.22% | Val loss: 0.9921 | Val acc: 54.53% | LR: 0.000003
Epoch: 115 | Train loss: 0.9956 | Train acc: 50.69% | Val loss: 0.9922 | Val acc: 54.59% | LR: 0.000002
Epoch: 116 | Train loss: 0.9946 | Train acc: 50.88% | Val loss: 0.9921 | Val acc: 54.61% | LR: 0.000002
Epoch: 117 | Train loss: 0.9965 | Train acc: 50.70% | Val loss: 0.9922 | Val acc: 54.61% | LR: 0.000002
Epoch: 118 | Train loss: 0.9959 | Train acc: 50.79% | Val loss: 0.9921 | Val acc: 54.61% | LR: 0.000002
Epoch: 119 | Train loss: 0.9968 | Train acc: 50.53% | Val loss: 0.9922 | Val acc: 54.63% | LR: 0.000002
Epoch: 120 | Train loss: 0.9972 | Train acc: 50.61% | Val loss: 0.9921 | Val acc: 54.63% | LR: 0.000002
Epoch: 121 | Train loss: 0.9955 | Train acc: 50.70% | Val loss: 0.9944 | Val acc: 54.63% | LR: 0.000002
Epoch: 122 | Train loss: 0.9952 | Train acc: 50.96% | Val loss: 0.9950 | Val acc: 54.61% | LR: 0.000002
Epoch: 123 | Train loss: 0.9949 | Train acc: 50.68% | Val loss: 0.9923 | Val acc: 54.61% | LR: 0.000002
Epoch: 124 | Train loss: 0.9958 | Train acc: 50.68% | Val loss: 0.9949 | Val acc: 54.65% | LR: 0.000002
Epoch: 125 | Train loss: 0.9959 | Train acc: 50.59% | Val loss: 0.9922 | Val acc: 54.61% | LR: 0.000002
Epoch: 126 | Train loss: 0.9962 | Train acc: 50.95% | Val loss: 0.9921 | Val acc: 54.61% | LR: 0.000002
Epoch: 127 | Train loss: 0.9951 | Train acc: 50.78% | Val loss: 0.9930 | Val acc: 54.65% | LR: 0.000002
Epoch: 128 | Train loss: 0.9969 | Train acc: 50.34% | Val loss: 0.9952 | Val acc: 54.59% | LR: 0.000002
Epoch: 129 | Train loss: 0.9954 | Train acc: 50.87% | Val loss: 0.9921 | Val acc: 54.59% | LR: 0.000002
Epoch: 130 | Train loss: 0.9985 | Train acc: 50.07% | Val loss: 0.9924 | Val acc: 54.59% | LR: 0.000001
Epoch: 131 | Train loss: 0.9952 | Train acc: 50.97% | Val loss: 0.9921 | Val acc: 54.59% | LR: 0.000001
Epoch: 132 | Train loss: 0.9955 | Train acc: 50.88% | Val loss: 0.9922 | Val acc: 54.59% | LR: 0.000001
Epoch: 133 | Train loss: 0.9966 | Train acc: 50.88% | Val loss: 0.9921 | Val acc: 54.59% | LR: 0.000001
Epoch: 134 | Train loss: 0.9953 | Train acc: 51.06% | Val loss: 0.9921 | Val acc: 54.65% | LR: 0.000001
Epoch: 135 | Train loss: 0.9928 | Train acc: 51.68% | Val loss: 0.9922 | Val acc: 54.65% | LR: 0.000001
Epoch: 136 | Train loss: 0.9951 | Train acc: 50.53% | Val loss: 0.9921 | Val acc: 54.67% | LR: 0.000001
Epoch: 137 | Train loss: 0.9954 | Train acc: 51.24% | Val loss: 0.9928 | Val acc: 54.69% | LR: 0.000001
Epoch: 138 | Train loss: 0.9965 | Train acc: 50.62% | Val loss: 0.9927 | Val acc: 54.69% | LR: 0.000001
Epoch: 139 | Train loss: 0.9963 | Train acc: 50.53% | Val loss: 0.9924 | Val acc: 54.69% | LR: 0.000001
Epoch: 140 | Train loss: 0.9951 | Train acc: 50.54% | Val loss: 0.9921 | Val acc: 54.65% | LR: 0.000001
Epoch: 141 | Train loss: 0.9946 | Train acc: 50.90% | Val loss: 0.9921 | Val acc: 54.65% | LR: 0.000001
Epoch: 142 | Train loss: 0.9951 | Train acc: 50.71% | Val loss: 0.9921 | Val acc: 54.61% | LR: 0.000001
Epoch: 143 | Train loss: 0.9945 | Train acc: 51.06% | Val loss: 0.9921 | Val acc: 54.61% | LR: 0.000001
Epoch: 144 | Train loss: 0.9951 | Train acc: 50.53% | Val loss: 0.9921 | Val acc: 54.63% | LR: 0.000001
Epoch: 145 | Train loss: 0.9953 | Train acc: 51.15% | Val loss: 0.9922 | Val acc: 54.63% | LR: 0.000001
Epoch: 146 | Train loss: 0.9966 | Train acc: 50.53% | Val loss: 0.9921 | Val acc: 54.59% | LR: 0.000001
Epoch: 147 | Train loss: 0.9943 | Train acc: 51.14% | Val loss: 0.9926 | Val acc: 54.59% | LR: 0.000001
Epoch: 148 | Train loss: 0.9952 | Train acc: 50.79% | Val loss: 0.9921 | Val acc: 54.61% | LR: 0.000001
Epoch: 149 | Train loss: 0.9936 | Train acc: 51.15% | Val loss: 0.9921 | Val acc: 54.61% | LR: 0.000001

[I 2025-09-23 18:42:45,449] Trial 125 finished with value: 0.5460565686225891 and parameters: {'lr': 1.3248685259440813e-05, 'hidden_size': 64, 'dropout': 0.20269765179526428, 'weight_decay': 2.2880435776711507e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0005 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.09% | LR: 0.000013
Epoch: 001 | Train loss: 1.0008 | Train acc: 49.72% | Val loss: 0.9917 | Val acc: 54.11% | LR: 0.000013
Epoch: 002 | Train loss: 1.0005 | Train acc: 49.54% | Val loss: 0.9916 | Val acc: 54.13% | LR: 0.000013
Epoch: 003 | Train loss: 1.0008 | Train acc: 49.54% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000013
Epoch: 004 | Train loss: 1.0014 | Train acc: 49.36% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000013
Epoch: 005 | Train loss: 0.9987 | Train acc: 49.81% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000013
Epoch: 006 | Train loss: 1.0007 | Train acc: 49.50% | Val loss: 0.9919 | Val acc: 54.17% | LR: 0.000013
Epoch: 007 | Train loss: 1.0014 | Train acc: 49.50% | Val loss: 0.9919 | Val acc: 54.22% | LR: 0.000013
Epoch: 008 | Train loss: 1.0009 | Train acc: 49.44% | Val loss: 0.9920 | Val acc: 54.24% | LR: 0.000013
Epoch: 009 | Train loss: 0.9991 | Train acc: 50.47% | Val loss: 0.9921 | Val acc: 54.34% | LR: 0.000013
Epoch: 010 | Train loss: 0.9986 | Train acc: 50.62% | Val loss: 0.9921 | Val acc: 54.30% | LR: 0.000013
Epoch: 011 | Train loss: 0.9985 | Train acc: 50.81% | Val loss: 0.9921 | Val acc: 54.30% | LR: 0.000013
Epoch: 012 | Train loss: 0.9982 | Train acc: 50.71% | Val loss: 0.9920 | Val acc: 54.28% | LR: 0.000013
Epoch: 013 | Train loss: 0.9995 | Train acc: 50.36% | Val loss: 0.9919 | Val acc: 54.28% | LR: 0.000013
Epoch: 014 | Train loss: 0.9983 | Train acc: 50.46% | Val loss: 0.9920 | Val acc: 54.28% | LR: 0.000013
Epoch: 015 | Train loss: 0.9998 | Train acc: 50.03% | Val loss: 0.9920 | Val acc: 54.26% | LR: 0.000013
Epoch: 016 | Train loss: 0.9984 | Train acc: 50.48% | Val loss: 0.9921 | Val acc: 54.28% | LR: 0.000013
Epoch: 017 | Train loss: 0.9991 | Train acc: 50.39% | Val loss: 0.9920 | Val acc: 54.32% | LR: 0.000013
Epoch: 018 | Train loss: 0.9992 | Train acc: 50.24% | Val loss: 0.9919 | Val acc: 54.34% | LR: 0.000013
Epoch: 019 | Train loss: 0.9989 | Train acc: 50.35% | Val loss: 0.9920 | Val acc: 54.36% | LR: 0.000013
Epoch: 020 | Train loss: 0.9965 | Train acc: 51.15% | Val loss: 0.9920 | Val acc: 54.36% | LR: 0.000013
Epoch: 021 | Train loss: 0.9979 | Train acc: 50.60% | Val loss: 0.9919 | Val acc: 54.38% | LR: 0.000013
Epoch: 022 | Train loss: 0.9971 | Train acc: 50.79% | Val loss: 0.9918 | Val acc: 54.42% | LR: 0.000013
Epoch: 023 | Train loss: 0.9985 | Train acc: 50.36% | Val loss: 0.9918 | Val acc: 54.38% | LR: 0.000013
Epoch: 024 | Train loss: 0.9987 | Train acc: 50.35% | Val loss: 0.9918 | Val acc: 54.34% | LR: 0.000013
Epoch: 025 | Train loss: 0.9994 | Train acc: 50.04% | Val loss: 0.9915 | Val acc: 54.33% | LR: 0.000013
Epoch: 026 | Train loss: 0.9982 | Train acc: 50.23% | Val loss: 0.9918 | Val acc: 54.33% | LR: 0.000012
Epoch: 027 | Train loss: 1.0008 | Train acc: 50.75% | Val loss: 0.9918 | Val acc: 54.24% | LR: 0.000012
Epoch: 028 | Train loss: 0.9967 | Train acc: 50.77% | Val loss: 0.9918 | Val acc: 54.22% | LR: 0.000012
Epoch: 029 | Train loss: 0.9974 | Train acc: 50.78% | Val loss: 0.9917 | Val acc: 54.22% | LR: 0.000012
Epoch: 030 | Train loss: 0.9982 | Train acc: 50.45% | Val loss: 0.9916 | Val acc: 54.34% | LR: 0.000012
Epoch: 031 | Train loss: 0.9981 | Train acc: 50.35% | Val loss: 0.9918 | Val acc: 54.36% | LR: 0.000012
Epoch: 032 | Train loss: 0.9965 | Train acc: 51.08% | Val loss: 0.9916 | Val acc: 54.32% | LR: 0.000012
Epoch: 033 | Train loss: 0.9993 | Train acc: 49.93% | Val loss: 0.9916 | Val acc: 54.34% | LR: 0.000012
Epoch: 034 | Train loss: 0.9961 | Train acc: 50.90% | Val loss: 0.9916 | Val acc: 54.40% | LR: 0.000012
Epoch: 035 | Train loss: 0.9986 | Train acc: 50.38% | Val loss: 0.9916 | Val acc: 54.29% | LR: 0.000012
Epoch: 036 | Train loss: 0.9974 | Train acc: 50.49% | Val loss: 0.9917 | Val acc: 54.33% | LR: 0.000012
Epoch: 037 | Train loss: 0.9976 | Train acc: 50.40% | Val loss: 0.9918 | Val acc: 54.27% | LR: 0.000012
Epoch: 038 | Train loss: 0.9982 | Train acc: 50.33% | Val loss: 0.9915 | Val acc: 54.39% | LR: 0.000011
Epoch: 039 | Train loss: 0.9963 | Train acc: 50.87% | Val loss: 0.9918 | Val acc: 54.45% | LR: 0.000011
Epoch: 040 | Train loss: 0.9968 | Train acc: 50.78% | Val loss: 0.9920 | Val acc: 54.45% | LR: 0.000011
Epoch: 041 | Train loss: 0.9972 | Train acc: 50.72% | Val loss: 0.9915 | Val acc: 54.45% | LR: 0.000011
Epoch: 042 | Train loss: 0.9979 | Train acc: 50.38% | Val loss: 0.9916 | Val acc: 54.41% | LR: 0.000011
Epoch: 043 | Train loss: 0.9975 | Train acc: 50.47% | Val loss: 0.9916 | Val acc: 54.36% | LR: 0.000011
Epoch: 044 | Train loss: 0.9982 | Train acc: 50.29% | Val loss: 0.9916 | Val acc: 54.38% | LR: 0.000011
Epoch: 045 | Train loss: 0.9965 | Train acc: 50.64% | Val loss: 0.9918 | Val acc: 54.40% | LR: 0.000011
Epoch: 046 | Train loss: 0.9952 | Train acc: 50.73% | Val loss: 0.9912 | Val acc: 54.48% | LR: 0.000011
Epoch: 047 | Train loss: 1.0152 | Train acc: 49.99% | Val loss: 0.9916 | Val acc: 54.46% | LR: 0.000011
Epoch: 048 | Train loss: 0.9991 | Train acc: 50.46% | Val loss: 0.9918 | Val acc: 54.52% | LR: 0.000010
Epoch: 049 | Train loss: 0.9991 | Train acc: 50.55% | Val loss: 0.9923 | Val acc: 54.40% | LR: 0.000010
Epoch: 050 | Train loss: 1.0039 | Train acc: 50.17% | Val loss: 0.9917 | Val acc: 54.40% | LR: 0.000010
Epoch: 051 | Train loss: 0.9991 | Train acc: 50.33% | Val loss: 0.9917 | Val acc: 54.36% | LR: 0.000010
Epoch: 052 | Train loss: 1.0028 | Train acc: 50.50% | Val loss: 0.9918 | Val acc: 54.31% | LR: 0.000010
Epoch: 053 | Train loss: 1.0020 | Train acc: 50.04% | Val loss: 0.9918 | Val acc: 54.29% | LR: 0.000010
Epoch: 054 | Train loss: 0.9959 | Train acc: 50.64% | Val loss: 0.9917 | Val acc: 54.32% | LR: 0.000010
Epoch: 055 | Train loss: 1.0156 | Train acc: 50.63% | Val loss: 0.9915 | Val acc: 54.38% | LR: 0.000010
Epoch: 056 | Train loss: 1.0054 | Train acc: 50.92% | Val loss: 0.9915 | Val acc: 54.44% | LR: 0.000010
Epoch: 057 | Train loss: 0.9980 | Train acc: 50.41% | Val loss: 0.9920 | Val acc: 54.29% | LR: 0.000009
Epoch: 058 | Train loss: 0.9982 | Train acc: 50.52% | Val loss: 0.9935 | Val acc: 54.39% | LR: 0.000009
Epoch: 059 | Train loss: 0.9968 | Train acc: 50.95% | Val loss: 0.9918 | Val acc: 54.36% | LR: 0.000009
Epoch: 060 | Train loss: 0.9973 | Train acc: 50.70% | Val loss: 0.9917 | Val acc: 54.47% | LR: 0.000009
Epoch: 061 | Train loss: 0.9981 | Train acc: 50.42% | Val loss: 0.9935 | Val acc: 54.48% | LR: 0.000009
Epoch: 062 | Train loss: 0.9980 | Train acc: 50.50% | Val loss: 0.9914 | Val acc: 54.54% | LR: 0.000009
Epoch: 063 | Train loss: 0.9984 | Train acc: 50.45% | Val loss: 0.9917 | Val acc: 54.46% | LR: 0.000009
Epoch: 064 | Train loss: 0.9977 | Train acc: 50.78% | Val loss: 0.9918 | Val acc: 54.44% | LR: 0.000009
Epoch: 065 | Train loss: 0.9970 | Train acc: 50.82% | Val loss: 0.9915 | Val acc: 54.38% | LR: 0.000008
Epoch: 066 | Train loss: 0.9985 | Train acc: 50.30% | Val loss: 0.9925 | Val acc: 54.38% | LR: 0.000008
Epoch: 067 | Train loss: 0.9962 | Train acc: 51.24% | Val loss: 0.9918 | Val acc: 54.44% | LR: 0.000008
Epoch: 068 | Train loss: 0.9971 | Train acc: 50.85% | Val loss: 0.9919 | Val acc: 54.58% | LR: 0.000008
Epoch: 069 | Train loss: 0.9984 | Train acc: 50.56% | Val loss: 1.0295 | Val acc: 54.58% | LR: 0.000008
Epoch: 070 | Train loss: 0.9965 | Train acc: 51.03% | Val loss: 0.9918 | Val acc: 54.64% | LR: 0.000008
Epoch: 071 | Train loss: 0.9976 | Train acc: 50.77% | Val loss: 0.9920 | Val acc: 54.62% | LR: 0.000008
Epoch: 072 | Train loss: 0.9968 | Train acc: 50.75% | Val loss: 0.9916 | Val acc: 54.62% | LR: 0.000007
Epoch: 073 | Train loss: 0.9991 | Train acc: 50.03% | Val loss: 0.9919 | Val acc: 54.52% | LR: 0.000007
Epoch: 074 | Train loss: 0.9955 | Train acc: 51.39% | Val loss: 0.9919 | Val acc: 54.58% | LR: 0.000007
Epoch: 075 | Train loss: 0.9962 | Train acc: 51.10% | Val loss: 0.9918 | Val acc: 54.58% | LR: 0.000007
Epoch: 076 | Train loss: 0.9986 | Train acc: 50.43% | Val loss: 0.9916 | Val acc: 54.62% | LR: 0.000007
Epoch: 077 | Train loss: 0.9981 | Train acc: 50.32% | Val loss: 0.9914 | Val acc: 54.61% | LR: 0.000007
Epoch: 078 | Train loss: 0.9966 | Train acc: 50.78% | Val loss: 0.9919 | Val acc: 54.58% | LR: 0.000007
Epoch: 079 | Train loss: 0.9973 | Train acc: 50.88% | Val loss: 0.9919 | Val acc: 54.61% | LR: 0.000007
Epoch: 080 | Train loss: 0.9965 | Train acc: 51.14% | Val loss: 0.9956 | Val acc: 54.57% | LR: 0.000006
Epoch: 081 | Train loss: 0.9986 | Train acc: 50.67% | Val loss: 0.9922 | Val acc: 54.63% | LR: 0.000006
Epoch: 082 | Train loss: 0.9960 | Train acc: 51.39% | Val loss: 0.9917 | Val acc: 54.59% | LR: 0.000006
Epoch: 083 | Train loss: 0.9978 | Train acc: 50.32% | Val loss: 0.9920 | Val acc: 54.52% | LR: 0.000006
Epoch: 084 | Train loss: 0.9968 | Train acc: 50.77% | Val loss: 0.9918 | Val acc: 54.59% | LR: 0.000006
Epoch: 085 | Train loss: 0.9988 | Train acc: 50.34% | Val loss: 0.9917 | Val acc: 54.65% | LR: 0.000006
Epoch: 086 | Train loss: 0.9977 | Train acc: 50.68% | Val loss: 0.9958 | Val acc: 54.61% | LR: 0.000006
Epoch: 087 | Train loss: 0.9968 | Train acc: 50.69% | Val loss: 0.9918 | Val acc: 54.65% | LR: 0.000006
Epoch: 088 | Train loss: 0.9970 | Train acc: 50.68% | Val loss: 0.9922 | Val acc: 54.48% | LR: 0.000005
Epoch: 089 | Train loss: 0.9971 | Train acc: 50.69% | Val loss: 0.9914 | Val acc: 54.59% | LR: 0.000005
Epoch: 090 | Train loss: 0.9971 | Train acc: 50.80% | Val loss: 0.9919 | Val acc: 54.51% | LR: 0.000005
Epoch: 091 | Train loss: 0.9970 | Train acc: 50.97% | Val loss: 0.9915 | Val acc: 54.57% | LR: 0.000005
Epoch: 092 | Train loss: 0.9965 | Train acc: 50.60% | Val loss: 0.9931 | Val acc: 54.57% | LR: 0.000005
Epoch: 093 | Train loss: 0.9963 | Train acc: 50.87% | Val loss: 0.9915 | Val acc: 54.65% | LR: 0.000005
Epoch: 094 | Train loss: 0.9960 | Train acc: 51.22% | Val loss: 0.9920 | Val acc: 54.65% | LR: 0.000005
Epoch: 095 | Train loss: 0.9973 | Train acc: 50.86% | Val loss: 0.9926 | Val acc: 54.61% | LR: 0.000005
Epoch: 096 | Train loss: 0.9961 | Train acc: 50.97% | Val loss: 0.9918 | Val acc: 54.61% | LR: 0.000004
Epoch: 097 | Train loss: 0.9969 | Train acc: 50.71% | Val loss: 0.9934 | Val acc: 54.59% | LR: 0.000004
Epoch: 098 | Train loss: 0.9973 | Train acc: 50.96% | Val loss: 0.9918 | Val acc: 54.61% | LR: 0.000004
Epoch: 099 | Train loss: 0.9967 | Train acc: 51.06% | Val loss: 0.9917 | Val acc: 54.55% | LR: 0.000004
Epoch: 100 | Train loss: 0.9964 | Train acc: 50.52% | Val loss: 0.9989 | Val acc: 54.53% | LR: 0.000004
Epoch: 101 | Train loss: 0.9964 | Train acc: 50.95% | Val loss: 0.9918 | Val acc: 54.61% | LR: 0.000004
Epoch: 102 | Train loss: 0.9960 | Train acc: 50.96% | Val loss: 0.9918 | Val acc: 54.57% | LR: 0.000004
Epoch: 103 | Train loss: 0.9965 | Train acc: 50.85% | Val loss: 0.9915 | Val acc: 54.59% | LR: 0.000004
Epoch: 104 | Train loss: 0.9974 | Train acc: 50.61% | Val loss: 0.9918 | Val acc: 54.64% | LR: 0.000004
Epoch: 105 | Train loss: 0.9960 | Train acc: 51.13% | Val loss: 0.9917 | Val acc: 54.56% | LR: 0.000003
Epoch: 106 | Train loss: 0.9963 | Train acc: 50.87% | Val loss: 0.9917 | Val acc: 54.52% | LR: 0.000003
Epoch: 107 | Train loss: 0.9963 | Train acc: 51.04% | Val loss: 0.9918 | Val acc: 54.60% | LR: 0.000003
Epoch: 108 | Train loss: 0.9979 | Train acc: 50.24% | Val loss: 0.9916 | Val acc: 54.62% | LR: 0.000003
Epoch: 109 | Train loss: 0.9967 | Train acc: 50.95% | Val loss: 0.9915 | Val acc: 54.62% | LR: 0.000003
Epoch: 110 | Train loss: 0.9964 | Train acc: 50.59% | Val loss: 0.9914 | Val acc: 54.62% | LR: 0.000003
Epoch: 111 | Train loss: 0.9959 | Train acc: 50.85% | Val loss: 0.9917 | Val acc: 54.64% | LR: 0.000003
Epoch: 112 | Train loss: 0.9969 | Train acc: 50.33% | Val loss: 0.9932 | Val acc: 54.64% | LR: 0.000003
Epoch: 113 | Train loss: 1.0071 | Train acc: 50.41% | Val loss: 0.9914 | Val acc: 54.60% | LR: 0.000003
Epoch: 114 | Train loss: 0.9966 | Train acc: 50.34% | Val loss: 0.9918 | Val acc: 54.50% | LR: 0.000003
Epoch: 115 | Train loss: 0.9963 | Train acc: 51.12% | Val loss: 0.9939 | Val acc: 54.60% | LR: 0.000003
Epoch: 116 | Train loss: 0.9971 | Train acc: 51.23% | Val loss: 0.9916 | Val acc: 54.57% | LR: 0.000002
Epoch: 117 | Train loss: 0.9987 | Train acc: 50.41% | Val loss: 0.9916 | Val acc: 54.57% | LR: 0.000002
Epoch: 118 | Train loss: 1.0005 | Train acc: 50.58% | Val loss: 0.9916 | Val acc: 54.57% | LR: 0.000002
Epoch: 119 | Train loss: 1.0036 | Train acc: 50.77% | Val loss: 0.9916 | Val acc: 54.57% | LR: 0.000002
Epoch: 120 | Train loss: 1.0088 | Train acc: 50.62% | Val loss: 0.9916 | Val acc: 54.57% | LR: 0.000002
Epoch: 121 | Train loss: 0.9961 | Train acc: 51.08% | Val loss: 0.9917 | Val acc: 54.57% | LR: 0.000002
Epoch: 122 | Train loss: 0.9956 | Train acc: 50.89% | Val loss: 0.9917 | Val acc: 54.57% | LR: 0.000002
Epoch: 123 | Train loss: 0.9947 | Train acc: 50.98% | Val loss: 0.9916 | Val acc: 54.58% | LR: 0.000002
Epoch: 124 | Train loss: 0.9953 | Train acc: 51.26% | Val loss: 0.9916 | Val acc: 54.58% | LR: 0.000002
Epoch: 125 | Train loss: 0.9943 | Train acc: 51.11% | Val loss: 0.9919 | Val acc: 54.53% | LR: 0.000002
Epoch: 126 | Train loss: 0.9997 | Train acc: 50.30% | Val loss: 0.9924 | Val acc: 54.51% | LR: 0.000002
Epoch: 127 | Train loss: 0.9968 | Train acc: 50.63% | Val loss: 0.9917 | Val acc: 54.57% | LR: 0.000002
Epoch: 128 | Train loss: 1.0001 | Train acc: 50.23% | Val loss: 0.9918 | Val acc: 54.57% | LR: 0.000002
Epoch: 129 | Train loss: 0.9972 | Train acc: 50.59% | Val loss: 0.9916 | Val acc: 54.57% | LR: 0.000002
Epoch: 130 | Train loss: 0.9989 | Train acc: 50.64% | Val loss: 0.9916 | Val acc: 54.57% | LR: 0.000001
Epoch: 131 | Train loss: 0.9967 | Train acc: 50.80% | Val loss: 0.9917 | Val acc: 54.57% | LR: 0.000001
Epoch: 132 | Train loss: 0.9984 | Train acc: 50.43% | Val loss: 0.9917 | Val acc: 54.57% | LR: 0.000001
Epoch: 133 | Train loss: 0.9988 | Train acc: 50.35% | Val loss: 0.9987 | Val acc: 54.53% | LR: 0.000001
Epoch: 134 | Train loss: 0.9979 | Train acc: 50.91% | Val loss: 0.9916 | Val acc: 54.57% | LR: 0.000001
Epoch: 135 | Train loss: 0.9964 | Train acc: 50.65% | Val loss: 0.9916 | Val acc: 54.57% | LR: 0.000001
Epoch: 136 | Train loss: 0.9976 | Train acc: 50.90% | Val loss: 0.9918 | Val acc: 54.57% | LR: 0.000001

[I 2025-09-23 18:44:36,463] Trial 126 finished with value: 0.5456531286239624 and parameters: {'lr': 1.3454855031741436e-05, 'hidden_size': 64, 'dropout': 0.162570533027078, 'weight_decay': 0.00012067111838984355}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 0.9998 | Train acc: 50.33% | Val loss: 1.0048 | Val acc: 52.50% | LR: 0.000014
Epoch: 001 | Train loss: 1.0024 | Train acc: 50.47% | Val loss: 1.0052 | Val acc: 52.52% | LR: 0.000014
Epoch: 002 | Train loss: 1.0004 | Train acc: 50.41% | Val loss: 1.0413 | Val acc: 52.45% | LR: 0.000014
Epoch: 003 | Train loss: 0.9991 | Train acc: 51.18% | Val loss: 0.9989 | Val acc: 52.77% | LR: 0.000014
Epoch: 004 | Train loss: 1.0231 | Train acc: 50.93% | Val loss: 1.0059 | Val acc: 52.72% | LR: 0.000014
Epoch: 005 | Train loss: 0.9993 | Train acc: 51.05% | Val loss: 0.9988 | Val acc: 52.78% | LR: 0.000014
Epoch: 006 | Train loss: 0.9981 | Train acc: 51.51% | Val loss: 1.0001 | Val acc: 52.72% | LR: 0.000014
Epoch: 007 | Train loss: 0.9991 | Train acc: 51.53% | Val loss: 1.0032 | Val acc: 52.56% | LR: 0.000014
Epoch: 008 | Train loss: 0.9996 | Train acc: 50.96% | Val loss: 1.0045 | Val acc: 52.47% | LR: 0.000014
Epoch: 009 | Train loss: 0.9989 | Train acc: 50.79% | Val loss: 1.0008 | Val acc: 52.58% | LR: 0.000014
Epoch: 010 | Train loss: 0.9983 | Train acc: 50.61% | Val loss: 1.0042 | Val acc: 52.56% | LR: 0.000014
Epoch: 011 | Train loss: 0.9989 | Train acc: 51.02% | Val loss: 1.0001 | Val acc: 52.60% | LR: 0.000014
Epoch: 012 | Train loss: 0.9986 | Train acc: 50.66% | Val loss: 1.0219 | Val acc: 52.70% | LR: 0.000014
Epoch: 013 | Train loss: 0.9980 | Train acc: 51.01% | Val loss: 1.0050 | Val acc: 52.39% | LR: 0.000014
Epoch: 014 | Train loss: 0.9976 | Train acc: 51.62% | Val loss: 0.9989 | Val acc: 52.75% | LR: 0.000014
Epoch: 015 | Train loss: 1.0083 | Train acc: 50.20% | Val loss: 1.0191 | Val acc: 52.84% | LR: 0.000014
Epoch: 016 | Train loss: 1.0009 | Train acc: 51.70% | Val loss: 1.0106 | Val acc: 52.72% | LR: 0.000014
Epoch: 017 | Train loss: 0.9990 | Train acc: 50.94% | Val loss: 0.9979 | Val acc: 52.74% | LR: 0.000014
Epoch: 018 | Train loss: 0.9989 | Train acc: 50.09% | Val loss: 1.0006 | Val acc: 52.61% | LR: 0.000014
Epoch: 019 | Train loss: 0.9979 | Train acc: 51.10% | Val loss: 1.0024 | Val acc: 52.54% | LR: 0.000014
Epoch: 020 | Train loss: 0.9993 | Train acc: 50.03% | Val loss: 1.0053 | Val acc: 52.46% | LR: 0.000013
Epoch: 021 | Train loss: 0.9984 | Train acc: 50.92% | Val loss: 0.9982 | Val acc: 52.72% | LR: 0.000013
Epoch: 022 | Train loss: 1.0175 | Train acc: 51.13% | Val loss: 1.0013 | Val acc: 52.42% | LR: 0.000013
Epoch: 023 | Train loss: 0.9980 | Train acc: 50.63% | Val loss: 1.0146 | Val acc: 52.50% | LR: 0.000013
Epoch: 024 | Train loss: 0.9977 | Train acc: 50.63% | Val loss: 1.0131 | Val acc: 52.79% | LR: 0.000013
Epoch: 025 | Train loss: 0.9987 | Train acc: 50.39% | Val loss: 1.0008 | Val acc: 52.60% | LR: 0.000013
Epoch: 026 | Train loss: 0.9976 | Train acc: 50.65% | Val loss: 0.9998 | Val acc: 52.79% | LR: 0.000013
Epoch: 027 | Train loss: 0.9988 | Train acc: 50.66% | Val loss: 1.0243 | Val acc: 52.72% | LR: 0.000013
Epoch: 028 | Train loss: 0.9977 | Train acc: 50.83% | Val loss: 1.0084 | Val acc: 52.45% | LR: 0.000013
Epoch: 029 | Train loss: 0.9974 | Train acc: 50.74% | Val loss: 1.0246 | Val acc: 52.79% | LR: 0.000013
Epoch: 030 | Train loss: 0.9980 | Train acc: 50.33% | Val loss: 1.0291 | Val acc: 52.77% | LR: 0.000013
Epoch: 031 | Train loss: 0.9979 | Train acc: 50.50% | Val loss: 0.9999 | Val acc: 52.88% | LR: 0.000013
Epoch: 032 | Train loss: 0.9971 | Train acc: 51.10% | Val loss: 0.9963 | Val acc: 53.00% | LR: 0.000013
Epoch: 033 | Train loss: 0.9969 | Train acc: 51.10% | Val loss: 1.0030 | Val acc: 52.61% | LR: 0.000012
Epoch: 034 | Train loss: 0.9972 | Train acc: 50.82% | Val loss: 1.0191 | Val acc: 52.58% | LR: 0.000012
Epoch: 035 | Train loss: 0.9985 | Train acc: 50.55% | Val loss: 0.9995 | Val acc: 52.73% | LR: 0.000012
Epoch: 036 | Train loss: 0.9974 | Train acc: 50.26% | Val loss: 1.0000 | Val acc: 52.76% | LR: 0.000012
Epoch: 037 | Train loss: 0.9965 | Train acc: 51.03% | Val loss: 0.9977 | Val acc: 52.73% | LR: 0.000012
Epoch: 038 | Train loss: 0.9969 | Train acc: 50.51% | Val loss: 1.0004 | Val acc: 52.96% | LR: 0.000012
Epoch: 039 | Train loss: 0.9971 | Train acc: 50.87% | Val loss: 0.9978 | Val acc: 52.86% | LR: 0.000012
Epoch: 040 | Train loss: 0.9996 | Train acc: 50.69% | Val loss: 1.0004 | Val acc: 52.88% | LR: 0.000012
Epoch: 041 | Train loss: 0.9991 | Train acc: 50.34% | Val loss: 0.9986 | Val acc: 52.85% | LR: 0.000012
Epoch: 042 | Train loss: 0.9985 | Train acc: 50.23% | Val loss: 1.0289 | Val acc: 52.68% | LR: 0.000012
Epoch: 043 | Train loss: 1.0382 | Train acc: 50.06% | Val loss: 1.0169 | Val acc: 52.94% | LR: 0.000011
Epoch: 044 | Train loss: 0.9979 | Train acc: 50.32% | Val loss: 1.0008 | Val acc: 52.86% | LR: 0.000011
Epoch: 045 | Train loss: 1.3533 | Train acc: 50.57% | Val loss: 1.0041 | Val acc: 52.86% | LR: 0.000011
Epoch: 046 | Train loss: 1.0079 | Train acc: 49.86% | Val loss: 1.0065 | Val acc: 52.83% | LR: 0.000011
Epoch: 047 | Train loss: 0.9994 | Train acc: 49.90% | Val loss: 1.0073 | Val acc: 52.80% | LR: 0.000011
Epoch: 048 | Train loss: 0.9999 | Train acc: 50.31% | Val loss: 0.9972 | Val acc: 52.81% | LR: 0.000011
Epoch: 049 | Train loss: 0.9970 | Train acc: 50.76% | Val loss: 1.0046 | Val acc: 52.80% | LR: 0.000011
Epoch: 050 | Train loss: 0.9983 | Train acc: 50.48% | Val loss: 0.9982 | Val acc: 52.60% | LR: 0.000011
Epoch: 051 | Train loss: 0.9974 | Train acc: 50.66% | Val loss: 0.9994 | Val acc: 52.79% | LR: 0.000011
Epoch: 052 | Train loss: 0.9975 | Train acc: 50.48% | Val loss: 1.0316 | Val acc: 52.71% | LR: 0.000010
Epoch: 053 | Train loss: 1.0032 | Train acc: 50.95% | Val loss: 1.1143 | Val acc: 52.71% | LR: 0.000010
Epoch: 054 | Train loss: 0.9992 | Train acc: 49.94% | Val loss: 1.0031 | Val acc: 52.71% | LR: 0.000010
Epoch: 055 | Train loss: 0.9976 | Train acc: 50.32% | Val loss: 1.0119 | Val acc: 52.49% | LR: 0.000010
Epoch: 056 | Train loss: 0.9959 | Train acc: 50.93% | Val loss: 0.9974 | Val acc: 52.97% | LR: 0.000010
Epoch: 057 | Train loss: 0.9966 | Train acc: 50.67% | Val loss: 1.0062 | Val acc: 52.81% | LR: 0.000010
Epoch: 058 | Train loss: 0.9947 | Train acc: 51.08% | Val loss: 0.9989 | Val acc: 52.76% | LR: 0.000010
Epoch: 059 | Train loss: 1.0002 | Train acc: 50.64% | Val loss: 1.0006 | Val acc: 52.64% | LR: 0.000010
Epoch: 060 | Train loss: 0.9977 | Train acc: 50.21% | Val loss: 0.9987 | Val acc: 53.09% | LR: 0.000009
Epoch: 061 | Train loss: 0.9977 | Train acc: 50.30% | Val loss: 0.9975 | Val acc: 53.13% | LR: 0.000009
Epoch: 062 | Train loss: 0.9984 | Train acc: 50.74% | Val loss: 1.0077 | Val acc: 53.21% | LR: 0.000009
Epoch: 063 | Train loss: 0.9966 | Train acc: 50.48% | Val loss: 0.9984 | Val acc: 53.15% | LR: 0.000009
Epoch: 064 | Train loss: 0.9980 | Train acc: 50.10% | Val loss: 0.9985 | Val acc: 53.24% | LR: 0.000009
Epoch: 065 | Train loss: 0.9961 | Train acc: 50.66% | Val loss: 1.0289 | Val acc: 53.24% | LR: 0.000009
Epoch: 066 | Train loss: 0.9962 | Train acc: 50.97% | Val loss: 1.0027 | Val acc: 53.12% | LR: 0.000009
Epoch: 067 | Train loss: 0.9966 | Train acc: 50.64% | Val loss: 1.0000 | Val acc: 53.08% | LR: 0.000008
Epoch: 068 | Train loss: 0.9966 | Train acc: 50.57% | Val loss: 0.9991 | Val acc: 52.84% | LR: 0.000008
Epoch: 069 | Train loss: 0.9988 | Train acc: 50.19% | Val loss: 1.0096 | Val acc: 52.89% | LR: 0.000008
Epoch: 070 | Train loss: 1.0015 | Train acc: 50.54% | Val loss: 1.0003 | Val acc: 52.77% | LR: 0.000008
Epoch: 071 | Train loss: 1.0001 | Train acc: 50.33% | Val loss: 1.0057 | Val acc: 52.75% | LR: 0.000008
Epoch: 072 | Train loss: 0.9956 | Train acc: 50.72% | Val loss: 1.0037 | Val acc: 52.79% | LR: 0.000008
Epoch: 073 | Train loss: 0.9926 | Train acc: 51.26% | Val loss: 0.9994 | Val acc: 52.85% | LR: 0.000008
Epoch: 074 | Train loss: 0.9981 | Train acc: 50.39% | Val loss: 1.0014 | Val acc: 52.89% | LR: 0.000008
Epoch: 075 | Train loss: 0.9967 | Train acc: 50.67% | Val loss: 1.0040 | Val acc: 52.97% | LR: 0.000007
Epoch: 076 | Train loss: 0.9958 | Train acc: 50.83% | Val loss: 0.9971 | Val acc: 53.05% | LR: 0.000007
Epoch: 077 | Train loss: 0.9941 | Train acc: 50.78% | Val loss: 1.0048 | Val acc: 52.73% | LR: 0.000007
Epoch: 078 | Train loss: 0.9957 | Train acc: 50.63% | Val loss: 0.9967 | Val acc: 52.82% | LR: 0.000007
Epoch: 079 | Train loss: 0.9938 | Train acc: 50.95% | Val loss: 0.9995 | Val acc: 52.83% | LR: 0.000007
Epoch: 080 | Train loss: 0.9950 | Train acc: 51.01% | Val loss: 0.9992 | Val acc: 52.77% | LR: 0.000007
Epoch: 081 | Train loss: 0.9959 | Train acc: 50.66% | Val loss: 1.1571 | Val acc: 52.85% | LR: 0.000007
Epoch: 082 | Train loss: 0.9976 | Train acc: 50.41% | Val loss: 1.0005 | Val acc: 52.83% | LR: 0.000006
Epoch: 083 | Train loss: 0.9975 | Train acc: 50.46% | Val loss: 1.0028 | Val acc: 52.79% | LR: 0.000006
Epoch: 084 | Train loss: 0.9960 | Train acc: 50.54% | Val loss: 0.9995 | Val acc: 52.89% | LR: 0.000006
Epoch: 085 | Train loss: 0.9984 | Train acc: 49.81% | Val loss: 0.9981 | Val acc: 52.81% | LR: 0.000006
Epoch: 086 | Train loss: 0.9964 | Train acc: 50.55% | Val loss: 0.9997 | Val acc: 52.75% | LR: 0.000006
Epoch: 087 | Train loss: 0.9961 | Train acc: 50.55% | Val loss: 0.9990 | Val acc: 52.69% | LR: 0.000006
Epoch: 088 | Train loss: 0.9962 | Train acc: 50.53% | Val loss: 0.9982 | Val acc: 52.71% | LR: 0.000006
Epoch: 089 | Train loss: 0.9955 | Train acc: 50.62% | Val loss: 1.0067 | Val acc: 52.63% | LR: 0.000006
Epoch: 090 | Train loss: 0.9971 | Train acc: 50.01% | Val loss: 0.9983 | Val acc: 52.65% | LR: 0.000005
Epoch: 091 | Train loss: 1.0000 | Train acc: 49.58% | Val loss: 0.9979 | Val acc: 52.65% | LR: 0.000005
Epoch: 092 | Train loss: 0.9942 | Train acc: 50.72% | Val loss: 0.9997 | Val acc: 52.55% | LR: 0.000005
Epoch: 093 | Train loss: 0.9937 | Train acc: 50.87% | Val loss: 0.9995 | Val acc: 52.47% | LR: 0.000005
Epoch: 094 | Train loss: 0.9963 | Train acc: 50.81% | Val loss: 0.9979 | Val acc: 52.53% | LR: 0.000005
Epoch: 095 | Train loss: 0.9970 | Train acc: 50.45% | Val loss: 0.9981 | Val acc: 52.45% | LR: 0.000005
Epoch: 096 | Train loss: 0.9962 | Train acc: 50.36% | Val loss: 0.9982 | Val acc: 52.47% | LR: 0.000005
Epoch: 097 | Train loss: 0.9953 | Train acc: 50.54% | Val loss: 0.9979 | Val acc: 52.51% | LR: 0.000005
Epoch: 098 | Train loss: 0.9938 | Train acc: 50.89% | Val loss: 0.9989 | Val acc: 52.53% | LR: 0.000004
Epoch: 099 | Train loss: 0.9945 | Train acc: 50.54% | Val loss: 1.0009 | Val acc: 52.53% | LR: 0.000004
Epoch: 100 | Train loss: 0.9991 | Train acc: 50.18% | Val loss: 1.0001 | Val acc: 52.51% | LR: 0.000004
Epoch: 101 | Train loss: 0.9972 | Train acc: 50.73% | Val loss: 0.9983 | Val acc: 52.47% | LR: 0.000004
Epoch: 102 | Train loss: 0.9950 | Train acc: 50.55% | Val loss: 1.0037 | Val acc: 52.48% | LR: 0.000004
Epoch: 103 | Train loss: 0.9952 | Train acc: 50.71% | Val loss: 0.9986 | Val acc: 52.41% | LR: 0.000004
Epoch: 104 | Train loss: 0.9982 | Train acc: 50.46% | Val loss: 0.9971 | Val acc: 52.45% | LR: 0.000004
Epoch: 105 | Train loss: 0.9955 | Train acc: 50.37% | Val loss: 0.9977 | Val acc: 52.39% | LR: 0.000004
Epoch: 106 | Train loss: 0.9941 | Train acc: 50.68% | Val loss: 0.9978 | Val acc: 52.37% | LR: 0.000003
Epoch: 107 | Train loss: 0.9950 | Train acc: 50.59% | Val loss: 0.9995 | Val acc: 52.35% | LR: 0.000003
Epoch: 108 | Train loss: 0.9967 | Train acc: 50.65% | Val loss: 0.9973 | Val acc: 52.47% | LR: 0.000003
Epoch: 109 | Train loss: 0.9933 | Train acc: 50.48% | Val loss: 0.9973 | Val acc: 52.47% | LR: 0.000003
Epoch: 110 | Train loss: 0.9972 | Train acc: 50.44% | Val loss: 1.0030 | Val acc: 52.33% | LR: 0.000003
Epoch: 111 | Train loss: 0.9966 | Train acc: 50.34% | Val loss: 1.0022 | Val acc: 52.35% | LR: 0.000003
Epoch: 112 | Train loss: 0.9983 | Train acc: 50.00% | Val loss: 1.0000 | Val acc: 52.29% | LR: 0.000003
Epoch: 113 | Train loss: 0.9962 | Train acc: 50.27% | Val loss: 0.9978 | Val acc: 52.35% | LR: 0.000003

[I 2025-09-23 18:46:04,456] Trial 127 finished with value: 0.5237110614776611 and parameters: {'lr': 1.4074473452524923e-05, 'hidden_size': 69, 'dropout': 0.16441394502800002, 'weight_decay': 6.354001740153035e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0009 | Train acc: 50.34% | Val loss: 1.0162 | Val acc: 49.56% | LR: 0.000016
Epoch: 001 | Train loss: 1.0003 | Train acc: 50.38% | Val loss: 1.0109 | Val acc: 49.47% | LR: 0.000016
Epoch: 002 | Train loss: 1.0017 | Train acc: 50.78% | Val loss: 1.0003 | Val acc: 49.71% | LR: 0.000016
Epoch: 003 | Train loss: 1.0000 | Train acc: 49.89% | Val loss: 1.0017 | Val acc: 50.07% | LR: 0.000016
Epoch: 004 | Train loss: 0.9975 | Train acc: 51.00% | Val loss: 1.0034 | Val acc: 50.07% | LR: 0.000016
Epoch: 005 | Train loss: 0.9997 | Train acc: 50.76% | Val loss: 1.0013 | Val acc: 49.97% | LR: 0.000016
Epoch: 006 | Train loss: 0.9977 | Train acc: 50.57% | Val loss: 1.0154 | Val acc: 49.66% | LR: 0.000016
Epoch: 007 | Train loss: 0.9999 | Train acc: 50.45% | Val loss: 1.0007 | Val acc: 49.53% | LR: 0.000016
Epoch: 008 | Train loss: 0.9978 | Train acc: 50.92% | Val loss: 1.0047 | Val acc: 49.81% | LR: 0.000016
Epoch: 009 | Train loss: 0.9995 | Train acc: 50.67% | Val loss: 1.0061 | Val acc: 49.46% | LR: 0.000016
Epoch: 010 | Train loss: 0.9982 | Train acc: 50.67% | Val loss: 1.0247 | Val acc: 49.72% | LR: 0.000015
Epoch: 011 | Train loss: 0.9973 | Train acc: 50.94% | Val loss: 1.0106 | Val acc: 49.68% | LR: 0.000015
Epoch: 012 | Train loss: 0.9977 | Train acc: 50.59% | Val loss: 1.0178 | Val acc: 49.67% | LR: 0.000015
Epoch: 013 | Train loss: 0.9988 | Train acc: 50.41% | Val loss: 1.0007 | Val acc: 50.12% | LR: 0.000015
Epoch: 014 | Train loss: 0.9976 | Train acc: 50.65% | Val loss: 1.0001 | Val acc: 50.05% | LR: 0.000015
Epoch: 015 | Train loss: 0.9953 | Train acc: 51.11% | Val loss: 1.0016 | Val acc: 49.94% | LR: 0.000015
Epoch: 016 | Train loss: 0.9972 | Train acc: 50.59% | Val loss: 1.0010 | Val acc: 49.67% | LR: 0.000015
Epoch: 017 | Train loss: 0.9968 | Train acc: 50.65% | Val loss: 0.9998 | Val acc: 49.99% | LR: 0.000015
Epoch: 018 | Train loss: 1.0051 | Train acc: 51.43% | Val loss: 1.0011 | Val acc: 49.88% | LR: 0.000015
Epoch: 019 | Train loss: 1.0036 | Train acc: 50.59% | Val loss: 1.0185 | Val acc: 50.03% | LR: 0.000015
Epoch: 020 | Train loss: 1.0010 | Train acc: 50.46% | Val loss: 0.9993 | Val acc: 50.42% | LR: 0.000015
Epoch: 021 | Train loss: 0.9952 | Train acc: 50.94% | Val loss: 1.0000 | Val acc: 50.36% | LR: 0.000015
Epoch: 022 | Train loss: 0.9989 | Train acc: 50.65% | Val loss: 1.0003 | Val acc: 50.38% | LR: 0.000015
Epoch: 023 | Train loss: 0.9953 | Train acc: 51.20% | Val loss: 1.0047 | Val acc: 50.42% | LR: 0.000015
Epoch: 024 | Train loss: 0.9976 | Train acc: 50.63% | Val loss: 1.0043 | Val acc: 50.30% | LR: 0.000015
Epoch: 025 | Train loss: 0.9958 | Train acc: 50.80% | Val loss: 1.0010 | Val acc: 50.28% | LR: 0.000015
Epoch: 026 | Train loss: 0.9955 | Train acc: 51.04% | Val loss: 1.0142 | Val acc: 50.35% | LR: 0.000015
Epoch: 027 | Train loss: 0.9939 | Train acc: 51.06% | Val loss: 1.0003 | Val acc: 50.32% | LR: 0.000014
Epoch: 028 | Train loss: 0.9945 | Train acc: 51.05% | Val loss: 1.0005 | Val acc: 50.20% | LR: 0.000014
Epoch: 029 | Train loss: 0.9983 | Train acc: 50.37% | Val loss: 1.0005 | Val acc: 50.32% | LR: 0.000014
Epoch: 030 | Train loss: 0.9966 | Train acc: 50.47% | Val loss: 1.0000 | Val acc: 50.14% | LR: 0.000014
Epoch: 031 | Train loss: 0.9933 | Train acc: 51.01% | Val loss: 1.0000 | Val acc: 50.22% | LR: 0.000014
Epoch: 032 | Train loss: 0.9948 | Train acc: 50.75% | Val loss: 1.0003 | Val acc: 50.18% | LR: 0.000014
Epoch: 033 | Train loss: 0.9954 | Train acc: 50.62% | Val loss: 1.0002 | Val acc: 50.44% | LR: 0.000014
Epoch: 034 | Train loss: 0.9946 | Train acc: 50.57% | Val loss: 1.0002 | Val acc: 50.38% | LR: 0.000014
Epoch: 035 | Train loss: 0.9966 | Train acc: 50.38% | Val loss: 1.0002 | Val acc: 50.44% | LR: 0.000014
Epoch: 036 | Train loss: 0.9972 | Train acc: 50.36% | Val loss: 1.0000 | Val acc: 50.38% | LR: 0.000014
Epoch: 037 | Train loss: 0.9933 | Train acc: 50.94% | Val loss: 0.9999 | Val acc: 50.40% | LR: 0.000013
Epoch: 038 | Train loss: 0.9957 | Train acc: 50.86% | Val loss: 1.0003 | Val acc: 49.98% | LR: 0.000013
Epoch: 039 | Train loss: 0.9915 | Train acc: 50.83% | Val loss: 1.0005 | Val acc: 50.18% | LR: 0.000013
Epoch: 040 | Train loss: 0.9934 | Train acc: 50.96% | Val loss: 0.9993 | Val acc: 50.29% | LR: 0.000013
Epoch: 041 | Train loss: 0.9941 | Train acc: 50.85% | Val loss: 1.0001 | Val acc: 50.18% | LR: 0.000013
Epoch: 042 | Train loss: 0.9961 | Train acc: 50.76% | Val loss: 1.0002 | Val acc: 50.24% | LR: 0.000013
Epoch: 043 | Train loss: 0.9959 | Train acc: 50.63% | Val loss: 1.0002 | Val acc: 50.00% | LR: 0.000013
Epoch: 044 | Train loss: 0.9934 | Train acc: 51.06% | Val loss: 0.9996 | Val acc: 49.84% | LR: 0.000013
Epoch: 045 | Train loss: 0.9945 | Train acc: 50.70% | Val loss: 1.0004 | Val acc: 49.90% | LR: 0.000013
Epoch: 046 | Train loss: 0.9912 | Train acc: 51.16% | Val loss: 1.0003 | Val acc: 49.76% | LR: 0.000012
Epoch: 047 | Train loss: 1.0050 | Train acc: 50.50% | Val loss: 1.0003 | Val acc: 49.86% | LR: 0.000012
Epoch: 048 | Train loss: 1.0101 | Train acc: 50.36% | Val loss: 1.0002 | Val acc: 49.86% | LR: 0.000012
Epoch: 049 | Train loss: 0.9925 | Train acc: 50.94% | Val loss: 1.0002 | Val acc: 49.94% | LR: 0.000012
Epoch: 050 | Train loss: 1.0015 | Train acc: 50.88% | Val loss: 1.0001 | Val acc: 49.92% | LR: 0.000012
Epoch: 051 | Train loss: 0.9936 | Train acc: 51.00% | Val loss: 1.0002 | Val acc: 49.76% | LR: 0.000012
Epoch: 052 | Train loss: 0.9955 | Train acc: 50.52% | Val loss: 1.0000 | Val acc: 49.96% | LR: 0.000012
Epoch: 053 | Train loss: 0.9887 | Train acc: 51.30% | Val loss: 1.0001 | Val acc: 49.88% | LR: 0.000011
Epoch: 054 | Train loss: 0.9934 | Train acc: 50.72% | Val loss: 1.0001 | Val acc: 49.93% | LR: 0.000011
Epoch: 055 | Train loss: 0.9954 | Train acc: 50.60% | Val loss: 1.0003 | Val acc: 49.89% | LR: 0.000011
Epoch: 056 | Train loss: 0.9956 | Train acc: 50.50% | Val loss: 1.0001 | Val acc: 49.87% | LR: 0.000011
Epoch: 057 | Train loss: 0.9950 | Train acc: 50.89% | Val loss: 1.0001 | Val acc: 49.83% | LR: 0.000011
Epoch: 058 | Train loss: 0.9967 | Train acc: 50.32% | Val loss: 1.0003 | Val acc: 49.61% | LR: 0.000011
Epoch: 059 | Train loss: 0.9922 | Train acc: 50.90% | Val loss: 1.0000 | Val acc: 49.82% | LR: 0.000011
Epoch: 060 | Train loss: 0.9918 | Train acc: 50.98% | Val loss: 1.0002 | Val acc: 49.72% | LR: 0.000010
Epoch: 061 | Train loss: 0.9935 | Train acc: 50.80% | Val loss: 1.0000 | Val acc: 49.73% | LR: 0.000010
Epoch: 062 | Train loss: 0.9937 | Train acc: 50.95% | Val loss: 1.0161 | Val acc: 49.63% | LR: 0.000010
Epoch: 063 | Train loss: 0.9981 | Train acc: 50.17% | Val loss: 1.0000 | Val acc: 49.66% | LR: 0.000010
Epoch: 064 | Train loss: 0.9920 | Train acc: 50.86% | Val loss: 1.0005 | Val acc: 49.79% | LR: 0.000010
Epoch: 065 | Train loss: 0.9960 | Train acc: 50.40% | Val loss: 1.0001 | Val acc: 49.75% | LR: 0.000010
Epoch: 066 | Train loss: 0.9949 | Train acc: 50.77% | Val loss: 1.0003 | Val acc: 49.76% | LR: 0.000010
Epoch: 067 | Train loss: 0.9905 | Train acc: 51.02% | Val loss: 1.0002 | Val acc: 49.79% | LR: 0.000009
Epoch: 068 | Train loss: 0.9897 | Train acc: 51.02% | Val loss: 1.0001 | Val acc: 49.97% | LR: 0.000009
Epoch: 069 | Train loss: 0.9935 | Train acc: 50.77% | Val loss: 1.0002 | Val acc: 49.91% | LR: 0.000009
Epoch: 070 | Train loss: 0.9942 | Train acc: 50.69% | Val loss: 1.0001 | Val acc: 49.97% | LR: 0.000009
Epoch: 071 | Train loss: 0.9945 | Train acc: 50.23% | Val loss: 1.0002 | Val acc: 49.81% | LR: 0.000009
Epoch: 072 | Train loss: 0.9966 | Train acc: 50.18% | Val loss: 0.9998 | Val acc: 49.85% | LR: 0.000009
Epoch: 073 | Train loss: 0.9939 | Train acc: 50.64% | Val loss: 0.9994 | Val acc: 50.02% | LR: 0.000008
Epoch: 074 | Train loss: 0.9906 | Train acc: 50.89% | Val loss: 1.0000 | Val acc: 49.96% | LR: 0.000008
Epoch: 075 | Train loss: 0.9974 | Train acc: 50.52% | Val loss: 1.0000 | Val acc: 49.84% | LR: 0.000008
Epoch: 076 | Train loss: 0.9976 | Train acc: 50.17% | Val loss: 0.9998 | Val acc: 49.90% | LR: 0.000008
Epoch: 077 | Train loss: 0.9934 | Train acc: 50.59% | Val loss: 0.9998 | Val acc: 49.84% | LR: 0.000008
Epoch: 078 | Train loss: 0.9973 | Train acc: 50.46% | Val loss: 1.0002 | Val acc: 49.84% | LR: 0.000008
Epoch: 079 | Train loss: 0.9913 | Train acc: 50.91% | Val loss: 1.0004 | Val acc: 49.84% | LR: 0.000008
Epoch: 080 | Train loss: 0.9923 | Train acc: 50.63% | Val loss: 1.0003 | Val acc: 49.88% | LR: 0.000007
Epoch: 081 | Train loss: 0.9927 | Train acc: 50.90% | Val loss: 1.0005 | Val acc: 50.06% | LR: 0.000007
Epoch: 082 | Train loss: 0.9898 | Train acc: 51.07% | Val loss: 1.0016 | Val acc: 50.09% | LR: 0.000007

[I 2025-09-23 18:47:55,420] Trial 128 finished with value: 0.5023102223873138 and parameters: {'lr': 1.5684901580388936e-05, 'hidden_size': 139, 'dropout': 0.19960201981303416, 'weight_decay': 1.545677278164265e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 0.9978 | Train acc: 50.53% | Val loss: 1.0023 | Val acc: 47.19% | LR: 0.000013
Epoch: 001 | Train loss: 0.9947 | Train acc: 50.96% | Val loss: 1.0016 | Val acc: 47.13% | LR: 0.000013
Epoch: 002 | Train loss: 0.9941 | Train acc: 50.80% | Val loss: 1.6766 | Val acc: 47.09% | LR: 0.000013
Epoch: 003 | Train loss: 0.9957 | Train acc: 50.81% | Val loss: 1.0027 | Val acc: 47.27% | LR: 0.000013
Epoch: 004 | Train loss: 0.9998 | Train acc: 49.69% | Val loss: 1.0040 | Val acc: 46.98% | LR: 0.000013
Epoch: 005 | Train loss: 0.9974 | Train acc: 50.44% | Val loss: 1.0019 | Val acc: 47.11% | LR: 0.000013
Epoch: 006 | Train loss: 0.9990 | Train acc: 50.11% | Val loss: 1.0008 | Val acc: 46.97% | LR: 0.000013
Epoch: 007 | Train loss: 0.9965 | Train acc: 50.54% | Val loss: 1.0012 | Val acc: 46.95% | LR: 0.000013
Epoch: 008 | Train loss: 0.9978 | Train acc: 50.10% | Val loss: 1.0027 | Val acc: 46.81% | LR: 0.000013
Epoch: 009 | Train loss: 0.9982 | Train acc: 50.12% | Val loss: 1.0020 | Val acc: 46.71% | LR: 0.000013
Epoch: 010 | Train loss: 0.9968 | Train acc: 50.21% | Val loss: 1.0032 | Val acc: 46.91% | LR: 0.000013
Epoch: 011 | Train loss: 0.9921 | Train acc: 51.35% | Val loss: 1.0344 | Val acc: 46.83% | LR: 0.000013
Epoch: 012 | Train loss: 0.9955 | Train acc: 50.49% | Val loss: 1.0011 | Val acc: 47.39% | LR: 0.000012
Epoch: 013 | Train loss: 0.9979 | Train acc: 50.33% | Val loss: 1.0019 | Val acc: 47.48% | LR: 0.000012
Epoch: 014 | Train loss: 0.9970 | Train acc: 50.52% | Val loss: 1.0111 | Val acc: 47.01% | LR: 0.000012
Epoch: 015 | Train loss: 0.9961 | Train acc: 50.75% | Val loss: 1.0021 | Val acc: 47.47% | LR: 0.000012
Epoch: 016 | Train loss: 0.9946 | Train acc: 50.64% | Val loss: 1.0062 | Val acc: 47.08% | LR: 0.000012
Epoch: 017 | Train loss: 0.9955 | Train acc: 50.48% | Val loss: 1.0034 | Val acc: 47.14% | LR: 0.000012
Epoch: 018 | Train loss: 0.9986 | Train acc: 50.16% | Val loss: 1.0058 | Val acc: 47.08% | LR: 0.000012
Epoch: 019 | Train loss: 0.9983 | Train acc: 50.04% | Val loss: 1.0032 | Val acc: 47.34% | LR: 0.000012
Epoch: 020 | Train loss: 1.0013 | Train acc: 49.96% | Val loss: 1.0068 | Val acc: 47.18% | LR: 0.000012
Epoch: 021 | Train loss: 0.9986 | Train acc: 50.26% | Val loss: 1.0036 | Val acc: 47.08% | LR: 0.000012
Epoch: 022 | Train loss: 0.9955 | Train acc: 50.59% | Val loss: 1.0138 | Val acc: 46.96% | LR: 0.000012
Epoch: 023 | Train loss: 1.0015 | Train acc: 49.90% | Val loss: 1.0068 | Val acc: 47.08% | LR: 0.000012
Epoch: 024 | Train loss: 1.0017 | Train acc: 49.88% | Val loss: 1.0008 | Val acc: 47.27% | LR: 0.000012
Epoch: 025 | Train loss: 0.9970 | Train acc: 50.30% | Val loss: 1.0012 | Val acc: 47.22% | LR: 0.000012
Epoch: 026 | Train loss: 0.9964 | Train acc: 50.36% | Val loss: 1.0007 | Val acc: 47.15% | LR: 0.000012
Epoch: 027 | Train loss: 0.9950 | Train acc: 50.46% | Val loss: 1.0024 | Val acc: 47.05% | LR: 0.000012
Epoch: 028 | Train loss: 0.9930 | Train acc: 50.80% | Val loss: 1.0288 | Val acc: 47.01% | LR: 0.000012
Epoch: 029 | Train loss: 0.9964 | Train acc: 50.28% | Val loss: 1.0055 | Val acc: 47.03% | LR: 0.000012
Epoch: 030 | Train loss: 0.9977 | Train acc: 50.50% | Val loss: 1.0058 | Val acc: 47.17% | LR: 0.000012
Epoch: 031 | Train loss: 0.9957 | Train acc: 50.45% | Val loss: 1.0028 | Val acc: 47.00% | LR: 0.000011
Epoch: 032 | Train loss: 0.9989 | Train acc: 50.05% | Val loss: 1.0029 | Val acc: 46.73% | LR: 0.000011
Epoch: 033 | Train loss: 1.0029 | Train acc: 49.87% | Val loss: 1.0017 | Val acc: 46.82% | LR: 0.000011
Epoch: 034 | Train loss: 0.9950 | Train acc: 50.29% | Val loss: 1.0057 | Val acc: 46.90% | LR: 0.000011
Epoch: 035 | Train loss: 0.9973 | Train acc: 50.28% | Val loss: 1.0017 | Val acc: 47.18% | LR: 0.000011
Epoch: 036 | Train loss: 0.9957 | Train acc: 50.28% | Val loss: 1.0015 | Val acc: 47.15% | LR: 0.000011
Epoch: 037 | Train loss: 0.9950 | Train acc: 50.74% | Val loss: 1.0000 | Val acc: 47.32% | LR: 0.000011
Epoch: 038 | Train loss: 0.9951 | Train acc: 50.53% | Val loss: 1.0093 | Val acc: 47.06% | LR: 0.000011
Epoch: 039 | Train loss: 0.9962 | Train acc: 50.34% | Val loss: 1.0024 | Val acc: 46.80% | LR: 0.000011
Epoch: 040 | Train loss: 0.9973 | Train acc: 50.20% | Val loss: 1.0015 | Val acc: 46.84% | LR: 0.000011
Epoch: 041 | Train loss: 0.9977 | Train acc: 50.14% | Val loss: 1.0010 | Val acc: 46.64% | LR: 0.000011
Epoch: 042 | Train loss: 0.9942 | Train acc: 50.58% | Val loss: 1.0030 | Val acc: 46.81% | LR: 0.000010
Epoch: 043 | Train loss: 0.9966 | Train acc: 50.33% | Val loss: 1.0018 | Val acc: 46.66% | LR: 0.000010
Epoch: 044 | Train loss: 0.9949 | Train acc: 50.58% | Val loss: 1.0025 | Val acc: 46.76% | LR: 0.000010
Epoch: 045 | Train loss: 1.0012 | Train acc: 49.87% | Val loss: 1.0053 | Val acc: 46.72% | LR: 0.000010
Epoch: 046 | Train loss: 0.9964 | Train acc: 50.29% | Val loss: 1.0025 | Val acc: 46.75% | LR: 0.000010
Epoch: 047 | Train loss: 0.9924 | Train acc: 51.05% | Val loss: 1.0010 | Val acc: 46.89% | LR: 0.000010
Epoch: 048 | Train loss: 0.9955 | Train acc: 50.51% | Val loss: 1.0090 | Val acc: 46.85% | LR: 0.000010
Epoch: 049 | Train loss: 0.9924 | Train acc: 50.60% | Val loss: 1.0011 | Val acc: 47.17% | LR: 0.000010
Epoch: 050 | Train loss: 0.9925 | Train acc: 50.84% | Val loss: 1.0021 | Val acc: 46.97% | LR: 0.000010
Epoch: 051 | Train loss: 0.9954 | Train acc: 50.23% | Val loss: 1.0006 | Val acc: 46.85% | LR: 0.000010
Epoch: 052 | Train loss: 0.9914 | Train acc: 51.01% | Val loss: 1.0033 | Val acc: 46.76% | LR: 0.000009
Epoch: 053 | Train loss: 0.9957 | Train acc: 50.51% | Val loss: 1.0034 | Val acc: 47.17% | LR: 0.000009
Epoch: 054 | Train loss: 0.9918 | Train acc: 50.70% | Val loss: 1.0155 | Val acc: 46.80% | LR: 0.000009
Epoch: 055 | Train loss: 0.9952 | Train acc: 50.39% | Val loss: 1.0017 | Val acc: 46.93% | LR: 0.000009
Epoch: 056 | Train loss: 0.9956 | Train acc: 50.46% | Val loss: 1.0007 | Val acc: 46.95% | LR: 0.000009
Epoch: 057 | Train loss: 0.9925 | Train acc: 50.82% | Val loss: 1.0022 | Val acc: 46.80% | LR: 0.000009
Epoch: 058 | Train loss: 0.9898 | Train acc: 50.97% | Val loss: 1.0017 | Val acc: 46.80% | LR: 0.000009
Epoch: 059 | Train loss: 0.9929 | Train acc: 50.43% | Val loss: 1.0011 | Val acc: 46.76% | LR: 0.000009
Epoch: 060 | Train loss: 0.9911 | Train acc: 50.90% | Val loss: 1.0007 | Val acc: 46.82% | LR: 0.000009
Epoch: 061 | Train loss: 0.9911 | Train acc: 50.71% | Val loss: 1.0054 | Val acc: 46.83% | LR: 0.000008
Epoch: 062 | Train loss: 0.9962 | Train acc: 50.26% | Val loss: 1.0015 | Val acc: 46.95% | LR: 0.000008

[I 2025-09-23 18:48:47,282] Trial 129 finished with value: 0.4691585123538971 and parameters: {'lr': 1.2699134892292928e-05, 'hidden_size': 82, 'dropout': 0.14239265386617755, 'weight_decay': 0.0001111824320863278}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0003 | Train acc: 50.07% | Val loss: 0.9918 | Val acc: 54.09% | LR: 0.000016
Epoch: 001 | Train loss: 1.0007 | Train acc: 49.72% | Val loss: 0.9916 | Val acc: 54.13% | LR: 0.000016
Epoch: 002 | Train loss: 1.0005 | Train acc: 49.54% | Val loss: 0.9916 | Val acc: 54.13% | LR: 0.000016
Epoch: 003 | Train loss: 1.0008 | Train acc: 49.54% | Val loss: 0.9917 | Val acc: 54.11% | LR: 0.000016
Epoch: 004 | Train loss: 1.0014 | Train acc: 49.36% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000016
Epoch: 005 | Train loss: 0.9987 | Train acc: 49.81% | Val loss: 0.9918 | Val acc: 54.17% | LR: 0.000016
Epoch: 006 | Train loss: 1.0008 | Train acc: 49.49% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000016
Epoch: 007 | Train loss: 1.0014 | Train acc: 49.52% | Val loss: 0.9918 | Val acc: 54.34% | LR: 0.000016
Epoch: 008 | Train loss: 1.0010 | Train acc: 49.55% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000016
Epoch: 009 | Train loss: 0.9993 | Train acc: 50.47% | Val loss: 0.9920 | Val acc: 54.28% | LR: 0.000016
Epoch: 010 | Train loss: 0.9987 | Train acc: 50.62% | Val loss: 0.9921 | Val acc: 54.28% | LR: 0.000015
Epoch: 011 | Train loss: 0.9987 | Train acc: 50.66% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000015
Epoch: 012 | Train loss: 0.9983 | Train acc: 50.71% | Val loss: 0.9920 | Val acc: 54.28% | LR: 0.000015
Epoch: 013 | Train loss: 0.9997 | Train acc: 50.36% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000015
Epoch: 014 | Train loss: 0.9984 | Train acc: 50.46% | Val loss: 0.9919 | Val acc: 54.32% | LR: 0.000015
Epoch: 015 | Train loss: 0.9999 | Train acc: 50.01% | Val loss: 0.9919 | Val acc: 54.34% | LR: 0.000015
Epoch: 016 | Train loss: 0.9983 | Train acc: 50.44% | Val loss: 0.9920 | Val acc: 54.38% | LR: 0.000015
Epoch: 017 | Train loss: 0.9990 | Train acc: 50.53% | Val loss: 0.9919 | Val acc: 54.38% | LR: 0.000015
Epoch: 018 | Train loss: 0.9992 | Train acc: 50.26% | Val loss: 0.9918 | Val acc: 54.42% | LR: 0.000015
Epoch: 019 | Train loss: 0.9990 | Train acc: 50.17% | Val loss: 0.9918 | Val acc: 54.36% | LR: 0.000015
Epoch: 020 | Train loss: 0.9966 | Train acc: 51.13% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000015
Epoch: 021 | Train loss: 0.9979 | Train acc: 50.57% | Val loss: 0.9917 | Val acc: 54.20% | LR: 0.000015
Epoch: 022 | Train loss: 0.9971 | Train acc: 50.79% | Val loss: 0.9917 | Val acc: 54.24% | LR: 0.000015
Epoch: 023 | Train loss: 0.9984 | Train acc: 50.35% | Val loss: 0.9916 | Val acc: 54.41% | LR: 0.000015
Epoch: 024 | Train loss: 0.9982 | Train acc: 50.39% | Val loss: 0.9917 | Val acc: 54.29% | LR: 0.000015
Epoch: 025 | Train loss: 0.9993 | Train acc: 50.05% | Val loss: 0.9916 | Val acc: 54.25% | LR: 0.000015
Epoch: 026 | Train loss: 0.9982 | Train acc: 50.33% | Val loss: 0.9915 | Val acc: 54.37% | LR: 0.000015
Epoch: 027 | Train loss: 0.9971 | Train acc: 50.91% | Val loss: 0.9920 | Val acc: 54.39% | LR: 0.000014
Epoch: 028 | Train loss: 0.9966 | Train acc: 51.03% | Val loss: 0.9915 | Val acc: 54.42% | LR: 0.000014
Epoch: 029 | Train loss: 0.9973 | Train acc: 50.95% | Val loss: 0.9915 | Val acc: 54.38% | LR: 0.000014
Epoch: 030 | Train loss: 0.9979 | Train acc: 50.60% | Val loss: 0.9914 | Val acc: 54.31% | LR: 0.000014
Epoch: 031 | Train loss: 0.9982 | Train acc: 50.49% | Val loss: 0.9914 | Val acc: 54.25% | LR: 0.000014
Epoch: 032 | Train loss: 0.9965 | Train acc: 51.19% | Val loss: 0.9911 | Val acc: 54.36% | LR: 0.000014
Epoch: 033 | Train loss: 0.9985 | Train acc: 50.05% | Val loss: 0.9914 | Val acc: 54.27% | LR: 0.000014
Epoch: 034 | Train loss: 0.9961 | Train acc: 51.01% | Val loss: 0.9914 | Val acc: 54.45% | LR: 0.000014
Epoch: 035 | Train loss: 0.9981 | Train acc: 50.59% | Val loss: 0.9914 | Val acc: 54.57% | LR: 0.000014
Epoch: 036 | Train loss: 0.9973 | Train acc: 50.72% | Val loss: 0.9917 | Val acc: 54.47% | LR: 0.000014
Epoch: 037 | Train loss: 0.9975 | Train acc: 50.55% | Val loss: 0.9915 | Val acc: 54.48% | LR: 0.000013
Epoch: 038 | Train loss: 0.9981 | Train acc: 50.51% | Val loss: 0.9916 | Val acc: 54.53% | LR: 0.000013
Epoch: 039 | Train loss: 0.9961 | Train acc: 51.02% | Val loss: 0.9917 | Val acc: 54.54% | LR: 0.000013
Epoch: 040 | Train loss: 0.9967 | Train acc: 51.04% | Val loss: 0.9922 | Val acc: 54.58% | LR: 0.000013
Epoch: 041 | Train loss: 0.9971 | Train acc: 50.84% | Val loss: 0.9914 | Val acc: 54.76% | LR: 0.000013
Epoch: 042 | Train loss: 0.9984 | Train acc: 50.51% | Val loss: 0.9917 | Val acc: 54.74% | LR: 0.000013
Epoch: 043 | Train loss: 0.9977 | Train acc: 50.60% | Val loss: 0.9914 | Val acc: 54.58% | LR: 0.000013
Epoch: 044 | Train loss: 0.9979 | Train acc: 50.41% | Val loss: 0.9911 | Val acc: 54.56% | LR: 0.000013
Epoch: 045 | Train loss: 0.9970 | Train acc: 50.77% | Val loss: 0.9911 | Val acc: 54.68% | LR: 0.000013
Epoch: 046 | Train loss: 0.9958 | Train acc: 51.26% | Val loss: 0.9912 | Val acc: 54.64% | LR: 0.000012
Epoch: 047 | Train loss: 0.9973 | Train acc: 50.36% | Val loss: 0.9912 | Val acc: 54.60% | LR: 0.000012
Epoch: 048 | Train loss: 0.9973 | Train acc: 50.71% | Val loss: 0.9914 | Val acc: 54.57% | LR: 0.000012
Epoch: 049 | Train loss: 0.9972 | Train acc: 50.61% | Val loss: 0.9912 | Val acc: 54.64% | LR: 0.000012
Epoch: 050 | Train loss: 0.9981 | Train acc: 50.45% | Val loss: 0.9912 | Val acc: 54.62% | LR: 0.000012
Epoch: 051 | Train loss: 0.9966 | Train acc: 50.73% | Val loss: 0.9918 | Val acc: 54.69% | LR: 0.000012
Epoch: 052 | Train loss: 0.9984 | Train acc: 50.45% | Val loss: 0.9914 | Val acc: 54.69% | LR: 0.000012
Epoch: 053 | Train loss: 0.9971 | Train acc: 50.53% | Val loss: 0.9913 | Val acc: 54.73% | LR: 0.000011
Epoch: 054 | Train loss: 0.9961 | Train acc: 50.87% | Val loss: 0.9940 | Val acc: 54.62% | LR: 0.000011
Epoch: 055 | Train loss: 0.9960 | Train acc: 50.86% | Val loss: 0.9913 | Val acc: 54.64% | LR: 0.000011
Epoch: 056 | Train loss: 0.9957 | Train acc: 51.00% | Val loss: 0.9913 | Val acc: 54.61% | LR: 0.000011
Epoch: 057 | Train loss: 0.9971 | Train acc: 50.45% | Val loss: 0.9913 | Val acc: 54.61% | LR: 0.000011
Epoch: 058 | Train loss: 0.9988 | Train acc: 50.60% | Val loss: 0.9913 | Val acc: 54.55% | LR: 0.000011
Epoch: 059 | Train loss: 0.9958 | Train acc: 51.05% | Val loss: 0.9924 | Val acc: 54.53% | LR: 0.000011
Epoch: 060 | Train loss: 0.9955 | Train acc: 50.82% | Val loss: 0.9916 | Val acc: 54.57% | LR: 0.000010
Epoch: 061 | Train loss: 0.9955 | Train acc: 50.56% | Val loss: 0.9913 | Val acc: 54.67% | LR: 0.000010
Epoch: 062 | Train loss: 0.9957 | Train acc: 50.64% | Val loss: 0.9913 | Val acc: 54.65% | LR: 0.000010
Epoch: 063 | Train loss: 0.9978 | Train acc: 50.74% | Val loss: 0.9913 | Val acc: 54.69% | LR: 0.000010
Epoch: 064 | Train loss: 0.9965 | Train acc: 50.48% | Val loss: 0.9914 | Val acc: 54.61% | LR: 0.000010
Epoch: 065 | Train loss: 0.9956 | Train acc: 50.63% | Val loss: 0.9914 | Val acc: 54.63% | LR: 0.000010
Epoch: 066 | Train loss: 0.9966 | Train acc: 50.94% | Val loss: 0.9914 | Val acc: 54.61% | LR: 0.000010
Epoch: 067 | Train loss: 0.9959 | Train acc: 50.32% | Val loss: 0.9914 | Val acc: 54.55% | LR: 0.000009
Epoch: 068 | Train loss: 0.9964 | Train acc: 50.36% | Val loss: 0.9914 | Val acc: 54.47% | LR: 0.000009
Epoch: 069 | Train loss: 0.9961 | Train acc: 51.03% | Val loss: 0.9916 | Val acc: 54.60% | LR: 0.000009
Epoch: 070 | Train loss: 0.9944 | Train acc: 50.76% | Val loss: 0.9913 | Val acc: 54.60% | LR: 0.000009
Epoch: 071 | Train loss: 0.9976 | Train acc: 50.57% | Val loss: 0.9918 | Val acc: 54.68% | LR: 0.000009
Epoch: 072 | Train loss: 0.9941 | Train acc: 51.06% | Val loss: 0.9914 | Val acc: 54.62% | LR: 0.000009
Epoch: 073 | Train loss: 0.9986 | Train acc: 51.39% | Val loss: 0.9921 | Val acc: 54.68% | LR: 0.000008
Epoch: 074 | Train loss: 0.9944 | Train acc: 50.81% | Val loss: 0.9915 | Val acc: 54.64% | LR: 0.000008
Epoch: 075 | Train loss: 0.9947 | Train acc: 50.61% | Val loss: 0.9920 | Val acc: 54.56% | LR: 0.000008
Epoch: 076 | Train loss: 0.9967 | Train acc: 50.72% | Val loss: 0.9915 | Val acc: 54.64% | LR: 0.000008
Epoch: 077 | Train loss: 0.9962 | Train acc: 50.86% | Val loss: 0.9937 | Val acc: 54.64% | LR: 0.000008
Epoch: 078 | Train loss: 0.9943 | Train acc: 51.04% | Val loss: 0.9914 | Val acc: 54.68% | LR: 0.000008
Epoch: 079 | Train loss: 0.9951 | Train acc: 50.97% | Val loss: 0.9914 | Val acc: 54.68% | LR: 0.000008
Epoch: 080 | Train loss: 0.9946 | Train acc: 50.71% | Val loss: 0.9913 | Val acc: 54.68% | LR: 0.000007
Epoch: 081 | Train loss: 0.9945 | Train acc: 50.98% | Val loss: 0.9913 | Val acc: 54.72% | LR: 0.000007
Epoch: 082 | Train loss: 0.9951 | Train acc: 50.34% | Val loss: 0.9915 | Val acc: 54.64% | LR: 0.000007
Epoch: 083 | Train loss: 0.9951 | Train acc: 50.77% | Val loss: 0.9914 | Val acc: 54.64% | LR: 0.000007
Epoch: 084 | Train loss: 0.9938 | Train acc: 50.82% | Val loss: 0.9914 | Val acc: 54.72% | LR: 0.000007
Epoch: 085 | Train loss: 0.9966 | Train acc: 50.44% | Val loss: 0.9914 | Val acc: 54.68% | LR: 0.000007
Epoch: 086 | Train loss: 0.9945 | Train acc: 50.88% | Val loss: 0.9913 | Val acc: 54.66% | LR: 0.000007
Epoch: 087 | Train loss: 0.9923 | Train acc: 51.19% | Val loss: 0.9913 | Val acc: 54.64% | LR: 0.000006
Epoch: 088 | Train loss: 0.9965 | Train acc: 50.73% | Val loss: 0.9914 | Val acc: 54.66% | LR: 0.000006
Epoch: 089 | Train loss: 0.9950 | Train acc: 50.73% | Val loss: 0.9915 | Val acc: 54.60% | LR: 0.000006
Epoch: 090 | Train loss: 0.9952 | Train acc: 50.89% | Val loss: 0.9915 | Val acc: 54.50% | LR: 0.000006

[I 2025-09-23 18:50:04,930] Trial 130 finished with value: 0.5454322099685669 and parameters: {'lr': 1.5690836043671214e-05, 'hidden_size': 64, 'dropout': 0.23304204891248428, 'weight_decay': 8.346340899676947e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0003 | Train acc: 50.07% | Val loss: 0.9918 | Val acc: 54.09% | LR: 0.000016
Epoch: 001 | Train loss: 1.0007 | Train acc: 49.72% | Val loss: 0.9916 | Val acc: 54.13% | LR: 0.000016
Epoch: 002 | Train loss: 1.0005 | Train acc: 49.54% | Val loss: 0.9916 | Val acc: 54.13% | LR: 0.000016
Epoch: 003 | Train loss: 1.0008 | Train acc: 49.54% | Val loss: 0.9917 | Val acc: 54.11% | LR: 0.000016
Epoch: 004 | Train loss: 1.0015 | Train acc: 49.36% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000016
Epoch: 005 | Train loss: 0.9989 | Train acc: 49.82% | Val loss: 0.9918 | Val acc: 54.17% | LR: 0.000016
Epoch: 006 | Train loss: 1.0010 | Train acc: 49.46% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000016
Epoch: 007 | Train loss: 1.0016 | Train acc: 49.48% | Val loss: 0.9919 | Val acc: 54.32% | LR: 0.000016
Epoch: 008 | Train loss: 1.0010 | Train acc: 49.54% | Val loss: 0.9920 | Val acc: 54.32% | LR: 0.000015
Epoch: 009 | Train loss: 0.9993 | Train acc: 50.47% | Val loss: 0.9920 | Val acc: 54.26% | LR: 0.000015
Epoch: 010 | Train loss: 0.9988 | Train acc: 50.61% | Val loss: 0.9921 | Val acc: 54.30% | LR: 0.000015
Epoch: 011 | Train loss: 0.9987 | Train acc: 50.61% | Val loss: 0.9920 | Val acc: 54.28% | LR: 0.000015
Epoch: 012 | Train loss: 0.9983 | Train acc: 50.71% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000015
Epoch: 013 | Train loss: 0.9997 | Train acc: 50.36% | Val loss: 0.9919 | Val acc: 54.26% | LR: 0.000015
Epoch: 014 | Train loss: 0.9984 | Train acc: 50.47% | Val loss: 0.9919 | Val acc: 54.28% | LR: 0.000015
Epoch: 015 | Train loss: 0.9999 | Train acc: 50.03% | Val loss: 0.9919 | Val acc: 54.32% | LR: 0.000015
Epoch: 016 | Train loss: 0.9983 | Train acc: 50.44% | Val loss: 0.9918 | Val acc: 54.36% | LR: 0.000015
Epoch: 017 | Train loss: 0.9990 | Train acc: 50.51% | Val loss: 0.9919 | Val acc: 54.32% | LR: 0.000015
Epoch: 018 | Train loss: 0.9992 | Train acc: 50.28% | Val loss: 0.9919 | Val acc: 54.38% | LR: 0.000015
Epoch: 019 | Train loss: 0.9990 | Train acc: 50.26% | Val loss: 0.9919 | Val acc: 54.46% | LR: 0.000015
Epoch: 020 | Train loss: 0.9966 | Train acc: 51.13% | Val loss: 0.9918 | Val acc: 54.50% | LR: 0.000015
Epoch: 021 | Train loss: 0.9980 | Train acc: 50.61% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000015
Epoch: 022 | Train loss: 0.9972 | Train acc: 50.78% | Val loss: 0.9918 | Val acc: 54.34% | LR: 0.000015
Epoch: 023 | Train loss: 0.9985 | Train acc: 50.31% | Val loss: 0.9918 | Val acc: 54.34% | LR: 0.000015
Epoch: 024 | Train loss: 0.9983 | Train acc: 50.33% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000015
Epoch: 025 | Train loss: 0.9993 | Train acc: 50.01% | Val loss: 0.9918 | Val acc: 54.39% | LR: 0.000015
Epoch: 026 | Train loss: 0.9984 | Train acc: 50.30% | Val loss: 0.9918 | Val acc: 54.33% | LR: 0.000014
Epoch: 027 | Train loss: 0.9973 | Train acc: 50.85% | Val loss: 0.9916 | Val acc: 54.41% | LR: 0.000014
Epoch: 028 | Train loss: 0.9968 | Train acc: 50.93% | Val loss: 0.9917 | Val acc: 54.36% | LR: 0.000014
Epoch: 029 | Train loss: 0.9974 | Train acc: 50.85% | Val loss: 0.9917 | Val acc: 54.23% | LR: 0.000014
Epoch: 030 | Train loss: 0.9981 | Train acc: 50.52% | Val loss: 0.9917 | Val acc: 54.23% | LR: 0.000014
Epoch: 031 | Train loss: 0.9982 | Train acc: 50.48% | Val loss: 0.9916 | Val acc: 54.49% | LR: 0.000014
Epoch: 032 | Train loss: 0.9965 | Train acc: 51.20% | Val loss: 0.9915 | Val acc: 54.45% | LR: 0.000014
Epoch: 033 | Train loss: 0.9988 | Train acc: 50.05% | Val loss: 0.9915 | Val acc: 54.39% | LR: 0.000014
Epoch: 034 | Train loss: 0.9961 | Train acc: 51.04% | Val loss: 0.9916 | Val acc: 54.35% | LR: 0.000014
Epoch: 035 | Train loss: 0.9980 | Train acc: 50.62% | Val loss: 0.9916 | Val acc: 54.43% | LR: 0.000014
Epoch: 036 | Train loss: 0.9973 | Train acc: 50.63% | Val loss: 0.9916 | Val acc: 54.56% | LR: 0.000014
Epoch: 037 | Train loss: 0.9975 | Train acc: 50.54% | Val loss: 0.9916 | Val acc: 54.52% | LR: 0.000013
Epoch: 038 | Train loss: 0.9981 | Train acc: 50.48% | Val loss: 0.9916 | Val acc: 54.39% | LR: 0.000013
Epoch: 039 | Train loss: 0.9960 | Train acc: 50.95% | Val loss: 0.9915 | Val acc: 54.56% | LR: 0.000013
Epoch: 040 | Train loss: 0.9967 | Train acc: 51.07% | Val loss: 0.9914 | Val acc: 54.66% | LR: 0.000013
Epoch: 041 | Train loss: 0.9969 | Train acc: 50.89% | Val loss: 0.9914 | Val acc: 54.62% | LR: 0.000013
Epoch: 042 | Train loss: 0.9976 | Train acc: 50.65% | Val loss: 0.9914 | Val acc: 54.72% | LR: 0.000013
Epoch: 043 | Train loss: 0.9974 | Train acc: 50.57% | Val loss: 0.9914 | Val acc: 54.70% | LR: 0.000013
Epoch: 044 | Train loss: 0.9979 | Train acc: 50.57% | Val loss: 0.9914 | Val acc: 54.67% | LR: 0.000013
Epoch: 045 | Train loss: 0.9963 | Train acc: 50.84% | Val loss: 0.9913 | Val acc: 54.68% | LR: 0.000012
Epoch: 046 | Train loss: 0.9954 | Train acc: 51.30% | Val loss: 0.9913 | Val acc: 54.78% | LR: 0.000012
Epoch: 047 | Train loss: 0.9964 | Train acc: 50.41% | Val loss: 0.9913 | Val acc: 54.68% | LR: 0.000012
Epoch: 048 | Train loss: 0.9966 | Train acc: 50.73% | Val loss: 0.9913 | Val acc: 54.57% | LR: 0.000012
Epoch: 049 | Train loss: 0.9970 | Train acc: 50.57% | Val loss: 0.9913 | Val acc: 54.47% | LR: 0.000012
Epoch: 050 | Train loss: 0.9977 | Train acc: 50.46% | Val loss: 0.9912 | Val acc: 54.53% | LR: 0.000012
Epoch: 051 | Train loss: 0.9951 | Train acc: 50.73% | Val loss: 0.9912 | Val acc: 54.55% | LR: 0.000012
Epoch: 052 | Train loss: 0.9983 | Train acc: 50.69% | Val loss: 0.9913 | Val acc: 54.39% | LR: 0.000012
Epoch: 053 | Train loss: 0.9963 | Train acc: 50.55% | Val loss: 0.9912 | Val acc: 54.35% | LR: 0.000011
Epoch: 054 | Train loss: 0.9971 | Train acc: 50.72% | Val loss: 0.9912 | Val acc: 54.42% | LR: 0.000011
Epoch: 055 | Train loss: 0.9945 | Train acc: 50.88% | Val loss: 0.9913 | Val acc: 54.44% | LR: 0.000011
Epoch: 056 | Train loss: 0.9976 | Train acc: 51.14% | Val loss: 0.9912 | Val acc: 54.48% | LR: 0.000011
Epoch: 057 | Train loss: 0.9945 | Train acc: 50.72% | Val loss: 0.9912 | Val acc: 54.44% | LR: 0.000011
Epoch: 058 | Train loss: 0.9996 | Train acc: 50.37% | Val loss: 0.9912 | Val acc: 54.44% | LR: 0.000011
Epoch: 059 | Train loss: 0.9946 | Train acc: 51.25% | Val loss: 0.9912 | Val acc: 54.47% | LR: 0.000011
Epoch: 060 | Train loss: 0.9943 | Train acc: 50.83% | Val loss: 0.9912 | Val acc: 54.55% | LR: 0.000010
Epoch: 061 | Train loss: 0.9958 | Train acc: 50.69% | Val loss: 0.9911 | Val acc: 54.55% | LR: 0.000010
Epoch: 062 | Train loss: 0.9937 | Train acc: 50.73% | Val loss: 0.9911 | Val acc: 54.49% | LR: 0.000010
Epoch: 063 | Train loss: 0.9963 | Train acc: 50.60% | Val loss: 0.9910 | Val acc: 54.49% | LR: 0.000010
Epoch: 064 | Train loss: 0.9948 | Train acc: 50.82% | Val loss: 0.9910 | Val acc: 54.51% | LR: 0.000010
Epoch: 065 | Train loss: 0.9937 | Train acc: 51.06% | Val loss: 0.9910 | Val acc: 54.47% | LR: 0.000010
Epoch: 066 | Train loss: 0.9964 | Train acc: 50.48% | Val loss: 0.9910 | Val acc: 54.47% | LR: 0.000010
Epoch: 067 | Train loss: 0.9942 | Train acc: 51.58% | Val loss: 0.9910 | Val acc: 54.47% | LR: 0.000009
Epoch: 068 | Train loss: 0.9948 | Train acc: 51.11% | Val loss: 0.9909 | Val acc: 54.33% | LR: 0.000009
Epoch: 069 | Train loss: 0.9941 | Train acc: 50.66% | Val loss: 0.9909 | Val acc: 54.43% | LR: 0.000009
Epoch: 070 | Train loss: 0.9922 | Train acc: 51.13% | Val loss: 0.9909 | Val acc: 54.35% | LR: 0.000009
Epoch: 071 | Train loss: 0.9956 | Train acc: 50.89% | Val loss: 0.9909 | Val acc: 54.45% | LR: 0.000009
Epoch: 072 | Train loss: 0.9932 | Train acc: 50.84% | Val loss: 0.9909 | Val acc: 54.45% | LR: 0.000009
Epoch: 073 | Train loss: 0.9962 | Train acc: 50.03% | Val loss: 0.9909 | Val acc: 54.47% | LR: 0.000008
Epoch: 074 | Train loss: 0.9976 | Train acc: 51.40% | Val loss: 0.9908 | Val acc: 54.47% | LR: 0.000008
Epoch: 075 | Train loss: 0.9910 | Train acc: 51.19% | Val loss: 0.9908 | Val acc: 54.43% | LR: 0.000008
Epoch: 076 | Train loss: 0.9953 | Train acc: 50.73% | Val loss: 0.9908 | Val acc: 54.39% | LR: 0.000008
Epoch: 077 | Train loss: 0.9943 | Train acc: 50.56% | Val loss: 0.9908 | Val acc: 54.43% | LR: 0.000008
Epoch: 078 | Train loss: 1.0039 | Train acc: 50.69% | Val loss: 0.9908 | Val acc: 54.47% | LR: 0.000008
Epoch: 079 | Train loss: 0.9951 | Train acc: 50.86% | Val loss: 0.9908 | Val acc: 54.45% | LR: 0.000008
Epoch: 080 | Train loss: 1.0201 | Train acc: 51.19% | Val loss: 0.9908 | Val acc: 54.49% | LR: 0.000007
Epoch: 081 | Train loss: 0.9924 | Train acc: 50.67% | Val loss: 0.9908 | Val acc: 54.53% | LR: 0.000007
Epoch: 082 | Train loss: 0.9920 | Train acc: 51.43% | Val loss: 0.9908 | Val acc: 54.49% | LR: 0.000007
Epoch: 083 | Train loss: 0.9935 | Train acc: 50.66% | Val loss: 0.9908 | Val acc: 54.49% | LR: 0.000007
Epoch: 084 | Train loss: 0.9937 | Train acc: 50.93% | Val loss: 0.9908 | Val acc: 54.29% | LR: 0.000007
Epoch: 085 | Train loss: 0.9962 | Train acc: 50.40% | Val loss: 0.9908 | Val acc: 54.31% | LR: 0.000007
Epoch: 086 | Train loss: 0.9927 | Train acc: 50.78% | Val loss: 0.9908 | Val acc: 54.27% | LR: 0.000006
Epoch: 087 | Train loss: 0.9919 | Train acc: 50.76% | Val loss: 0.9908 | Val acc: 54.29% | LR: 0.000006
Epoch: 088 | Train loss: 0.9916 | Train acc: 50.80% | Val loss: 0.9908 | Val acc: 54.29% | LR: 0.000006
Epoch: 089 | Train loss: 0.9950 | Train acc: 50.79% | Val loss: 0.9908 | Val acc: 54.29% | LR: 0.000006
Epoch: 090 | Train loss: 0.9960 | Train acc: 51.01% | Val loss: 0.9908 | Val acc: 54.29% | LR: 0.000006
Epoch: 091 | Train loss: 0.9929 | Train acc: 51.17% | Val loss: 0.9908 | Val acc: 54.29% | LR: 0.000006
Epoch: 092 | Train loss: 0.9918 | Train acc: 50.80% | Val loss: 0.9908 | Val acc: 54.29% | LR: 0.000006
Epoch: 093 | Train loss: 0.9922 | Train acc: 51.01% | Val loss: 0.9908 | Val acc: 54.29% | LR: 0.000005
Epoch: 094 | Train loss: 0.9914 | Train acc: 51.28% | Val loss: 0.9908 | Val acc: 54.29% | LR: 0.000005
Epoch: 095 | Train loss: 0.9956 | Train acc: 50.91% | Val loss: 0.9908 | Val acc: 54.27% | LR: 0.000005

[I 2025-09-23 18:51:18,243] Trial 131 finished with value: 0.5423232674598694 and parameters: {'lr': 1.5603403628090494e-05, 'hidden_size': 64, 'dropout': 0.2307680768849288, 'weight_decay': 0.00013120196882056493}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0034 | Train acc: 48.82% | Val loss: 0.9973 | Val acc: 53.40% | LR: 0.000013
Epoch: 001 | Train loss: 1.0021 | Train acc: 49.19% | Val loss: 0.9973 | Val acc: 53.48% | LR: 0.000013
Epoch: 002 | Train loss: 1.0011 | Train acc: 49.47% | Val loss: 0.9972 | Val acc: 53.62% | LR: 0.000013
Epoch: 003 | Train loss: 1.0024 | Train acc: 48.94% | Val loss: 0.9972 | Val acc: 53.77% | LR: 0.000013
Epoch: 004 | Train loss: 1.0021 | Train acc: 49.09% | Val loss: 0.9972 | Val acc: 53.87% | LR: 0.000013
Epoch: 005 | Train loss: 1.0021 | Train acc: 49.35% | Val loss: 0.9972 | Val acc: 53.95% | LR: 0.000013
Epoch: 006 | Train loss: 1.0018 | Train acc: 49.36% | Val loss: 0.9972 | Val acc: 53.95% | LR: 0.000013
Epoch: 007 | Train loss: 1.0012 | Train acc: 49.51% | Val loss: 0.9972 | Val acc: 54.07% | LR: 0.000013
Epoch: 008 | Train loss: 1.0008 | Train acc: 49.71% | Val loss: 0.9972 | Val acc: 54.11% | LR: 0.000013
Epoch: 009 | Train loss: 1.0004 | Train acc: 49.91% | Val loss: 0.9972 | Val acc: 54.13% | LR: 0.000013
Epoch: 010 | Train loss: 1.0011 | Train acc: 49.57% | Val loss: 0.9971 | Val acc: 54.09% | LR: 0.000013
Epoch: 011 | Train loss: 1.0006 | Train acc: 49.74% | Val loss: 0.9971 | Val acc: 54.05% | LR: 0.000013
Epoch: 012 | Train loss: 0.9999 | Train acc: 50.12% | Val loss: 0.9971 | Val acc: 54.07% | LR: 0.000013
Epoch: 013 | Train loss: 1.0012 | Train acc: 49.32% | Val loss: 0.9970 | Val acc: 54.19% | LR: 0.000013
Epoch: 014 | Train loss: 1.0007 | Train acc: 49.58% | Val loss: 0.9970 | Val acc: 54.23% | LR: 0.000013
Epoch: 015 | Train loss: 1.0000 | Train acc: 49.86% | Val loss: 0.9970 | Val acc: 54.25% | LR: 0.000013
Epoch: 016 | Train loss: 0.9996 | Train acc: 50.22% | Val loss: 0.9969 | Val acc: 54.11% | LR: 0.000013
Epoch: 017 | Train loss: 1.0000 | Train acc: 49.74% | Val loss: 0.9967 | Val acc: 54.11% | LR: 0.000013
Epoch: 018 | Train loss: 1.0001 | Train acc: 49.61% | Val loss: 0.9966 | Val acc: 54.04% | LR: 0.000013
Epoch: 019 | Train loss: 0.9997 | Train acc: 49.97% | Val loss: 0.9965 | Val acc: 54.05% | LR: 0.000013
Epoch: 020 | Train loss: 1.0001 | Train acc: 49.64% | Val loss: 0.9966 | Val acc: 54.07% | LR: 0.000013
Epoch: 021 | Train loss: 0.9999 | Train acc: 49.93% | Val loss: 0.9965 | Val acc: 54.09% | LR: 0.000013
Epoch: 022 | Train loss: 0.9999 | Train acc: 50.07% | Val loss: 0.9965 | Val acc: 54.10% | LR: 0.000013
Epoch: 023 | Train loss: 0.9993 | Train acc: 50.17% | Val loss: 0.9964 | Val acc: 53.79% | LR: 0.000013
Epoch: 024 | Train loss: 0.9993 | Train acc: 50.42% | Val loss: 0.9964 | Val acc: 54.12% | LR: 0.000013
Epoch: 025 | Train loss: 0.9992 | Train acc: 50.72% | Val loss: 0.9963 | Val acc: 54.06% | LR: 0.000013
Epoch: 026 | Train loss: 0.9992 | Train acc: 50.38% | Val loss: 0.9963 | Val acc: 54.02% | LR: 0.000013
Epoch: 027 | Train loss: 0.9993 | Train acc: 50.09% | Val loss: 0.9963 | Val acc: 53.80% | LR: 0.000012
Epoch: 028 | Train loss: 0.9986 | Train acc: 50.45% | Val loss: 0.9964 | Val acc: 53.61% | LR: 0.000012
Epoch: 029 | Train loss: 0.9987 | Train acc: 50.92% | Val loss: 0.9964 | Val acc: 53.54% | LR: 0.000012
Epoch: 030 | Train loss: 0.9985 | Train acc: 50.96% | Val loss: 0.9964 | Val acc: 53.55% | LR: 0.000012
Epoch: 031 | Train loss: 0.9982 | Train acc: 51.06% | Val loss: 0.9963 | Val acc: 53.66% | LR: 0.000012
Epoch: 032 | Train loss: 0.9993 | Train acc: 50.34% | Val loss: 0.9962 | Val acc: 53.89% | LR: 0.000012
Epoch: 033 | Train loss: 0.9986 | Train acc: 50.66% | Val loss: 0.9961 | Val acc: 53.77% | LR: 0.000012
Epoch: 034 | Train loss: 0.9984 | Train acc: 50.76% | Val loss: 0.9961 | Val acc: 53.67% | LR: 0.000012
Epoch: 035 | Train loss: 0.9983 | Train acc: 51.10% | Val loss: 0.9961 | Val acc: 53.47% | LR: 0.000012
Epoch: 036 | Train loss: 0.9983 | Train acc: 50.83% | Val loss: 0.9961 | Val acc: 53.21% | LR: 0.000012
Epoch: 037 | Train loss: 0.9985 | Train acc: 50.72% | Val loss: 0.9959 | Val acc: 53.19% | LR: 0.000012
Epoch: 038 | Train loss: 0.9984 | Train acc: 50.74% | Val loss: 0.9959 | Val acc: 53.03% | LR: 0.000012
Epoch: 039 | Train loss: 0.9981 | Train acc: 50.90% | Val loss: 0.9958 | Val acc: 52.97% | LR: 0.000011
Epoch: 040 | Train loss: 0.9968 | Train acc: 51.52% | Val loss: 0.9959 | Val acc: 53.22% | LR: 0.000011
Epoch: 041 | Train loss: 0.9974 | Train acc: 51.09% | Val loss: 0.9959 | Val acc: 53.22% | LR: 0.000011
Epoch: 042 | Train loss: 0.9982 | Train acc: 50.47% | Val loss: 0.9959 | Val acc: 52.94% | LR: 0.000011
Epoch: 043 | Train loss: 0.9985 | Train acc: 50.58% | Val loss: 0.9959 | Val acc: 53.20% | LR: 0.000011
Epoch: 044 | Train loss: 0.9977 | Train acc: 50.75% | Val loss: 0.9959 | Val acc: 53.30% | LR: 0.000011
Epoch: 045 | Train loss: 0.9971 | Train acc: 51.10% | Val loss: 0.9959 | Val acc: 53.31% | LR: 0.000011
Epoch: 046 | Train loss: 0.9968 | Train acc: 50.99% | Val loss: 0.9960 | Val acc: 53.33% | LR: 0.000011
Epoch: 047 | Train loss: 0.9971 | Train acc: 51.17% | Val loss: 0.9959 | Val acc: 53.31% | LR: 0.000011
Epoch: 048 | Train loss: 0.9968 | Train acc: 51.09% | Val loss: 0.9959 | Val acc: 53.35% | LR: 0.000010
Epoch: 049 | Train loss: 0.9976 | Train acc: 50.76% | Val loss: 0.9959 | Val acc: 53.27% | LR: 0.000010
Epoch: 050 | Train loss: 0.9975 | Train acc: 50.67% | Val loss: 0.9958 | Val acc: 53.19% | LR: 0.000010
Epoch: 051 | Train loss: 0.9977 | Train acc: 50.67% | Val loss: 0.9958 | Val acc: 53.25% | LR: 0.000010
Epoch: 052 | Train loss: 0.9967 | Train acc: 50.93% | Val loss: 0.9957 | Val acc: 53.31% | LR: 0.000010
Epoch: 053 | Train loss: 0.9965 | Train acc: 50.86% | Val loss: 0.9957 | Val acc: 53.07% | LR: 0.000010
Epoch: 054 | Train loss: 0.9962 | Train acc: 51.12% | Val loss: 0.9957 | Val acc: 52.97% | LR: 0.000010
Epoch: 055 | Train loss: 0.9965 | Train acc: 50.94% | Val loss: 0.9956 | Val acc: 52.97% | LR: 0.000010
Epoch: 056 | Train loss: 0.9975 | Train acc: 50.67% | Val loss: 0.9956 | Val acc: 53.01% | LR: 0.000010
Epoch: 057 | Train loss: 0.9974 | Train acc: 50.58% | Val loss: 0.9957 | Val acc: 52.65% | LR: 0.000009
Epoch: 058 | Train loss: 0.9962 | Train acc: 50.87% | Val loss: 0.9956 | Val acc: 52.55% | LR: 0.000009
Epoch: 059 | Train loss: 0.9984 | Train acc: 50.09% | Val loss: 0.9956 | Val acc: 52.57% | LR: 0.000009
Epoch: 060 | Train loss: 0.9972 | Train acc: 50.78% | Val loss: 0.9956 | Val acc: 52.49% | LR: 0.000009
Epoch: 061 | Train loss: 0.9969 | Train acc: 50.47% | Val loss: 0.9956 | Val acc: 52.43% | LR: 0.000009
Epoch: 062 | Train loss: 0.9951 | Train acc: 51.16% | Val loss: 0.9956 | Val acc: 52.47% | LR: 0.000009
Epoch: 063 | Train loss: 0.9971 | Train acc: 50.53% | Val loss: 0.9956 | Val acc: 52.41% | LR: 0.000009
Epoch: 064 | Train loss: 0.9967 | Train acc: 50.83% | Val loss: 0.9956 | Val acc: 52.40% | LR: 0.000009

[I 2025-09-23 18:52:16,621] Trial 132 finished with value: 0.5240248680114746 and parameters: {'lr': 1.3489143715487667e-05, 'hidden_size': 68, 'dropout': 0.15403558323042676, 'weight_decay': 0.0001735744873307974}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0006 | Train acc: 49.79% | Val loss: 1.0129 | Val acc: 45.75% | LR: 0.000012
Epoch: 001 | Train loss: 1.0005 | Train acc: 49.49% | Val loss: 1.0085 | Val acc: 45.83% | LR: 0.000012
Epoch: 002 | Train loss: 1.0017 | Train acc: 49.35% | Val loss: 1.0079 | Val acc: 45.96% | LR: 0.000012
Epoch: 003 | Train loss: 1.0009 | Train acc: 49.63% | Val loss: 1.0061 | Val acc: 45.97% | LR: 0.000012
Epoch: 004 | Train loss: 0.9997 | Train acc: 49.83% | Val loss: 1.0052 | Val acc: 46.04% | LR: 0.000012
Epoch: 005 | Train loss: 1.0004 | Train acc: 49.33% | Val loss: 1.0064 | Val acc: 45.94% | LR: 0.000012
Epoch: 006 | Train loss: 1.0001 | Train acc: 49.47% | Val loss: 1.0067 | Val acc: 45.93% | LR: 0.000012
Epoch: 007 | Train loss: 1.0003 | Train acc: 49.74% | Val loss: 1.0072 | Val acc: 46.01% | LR: 0.000012
Epoch: 008 | Train loss: 1.0002 | Train acc: 49.55% | Val loss: 1.0072 | Val acc: 45.87% | LR: 0.000012
Epoch: 009 | Train loss: 0.9999 | Train acc: 49.71% | Val loss: 1.0053 | Val acc: 46.35% | LR: 0.000012
Epoch: 010 | Train loss: 0.9997 | Train acc: 49.62% | Val loss: 1.0056 | Val acc: 46.15% | LR: 0.000012
Epoch: 011 | Train loss: 1.0006 | Train acc: 49.37% | Val loss: 1.0059 | Val acc: 46.15% | LR: 0.000011
Epoch: 012 | Train loss: 1.0003 | Train acc: 50.00% | Val loss: 1.0064 | Val acc: 45.87% | LR: 0.000011
Epoch: 013 | Train loss: 1.0004 | Train acc: 48.96% | Val loss: 1.0060 | Val acc: 45.99% | LR: 0.000011
Epoch: 014 | Train loss: 1.0000 | Train acc: 49.54% | Val loss: 1.0059 | Val acc: 46.02% | LR: 0.000011
Epoch: 015 | Train loss: 0.9997 | Train acc: 49.87% | Val loss: 1.0053 | Val acc: 46.21% | LR: 0.000011
Epoch: 016 | Train loss: 0.9999 | Train acc: 49.66% | Val loss: 1.0051 | Val acc: 46.34% | LR: 0.000011
Epoch: 017 | Train loss: 1.0000 | Train acc: 50.13% | Val loss: 1.0067 | Val acc: 46.12% | LR: 0.000011
Epoch: 018 | Train loss: 1.0000 | Train acc: 49.76% | Val loss: 1.0088 | Val acc: 45.98% | LR: 0.000011
Epoch: 019 | Train loss: 0.9995 | Train acc: 49.69% | Val loss: 1.0058 | Val acc: 46.02% | LR: 0.000011
Epoch: 020 | Train loss: 0.9996 | Train acc: 50.39% | Val loss: 1.0075 | Val acc: 45.98% | LR: 0.000011
Epoch: 021 | Train loss: 0.9998 | Train acc: 49.87% | Val loss: 1.0049 | Val acc: 46.29% | LR: 0.000011
Epoch: 022 | Train loss: 0.9999 | Train acc: 50.04% | Val loss: 1.0055 | Val acc: 46.28% | LR: 0.000011
Epoch: 023 | Train loss: 1.0015 | Train acc: 49.63% | Val loss: 1.0053 | Val acc: 46.18% | LR: 0.000011
Epoch: 024 | Train loss: 0.9998 | Train acc: 50.18% | Val loss: 1.0071 | Val acc: 45.99% | LR: 0.000011
Epoch: 025 | Train loss: 1.0001 | Train acc: 49.92% | Val loss: 1.0060 | Val acc: 46.18% | LR: 0.000011
Epoch: 026 | Train loss: 0.9992 | Train acc: 50.43% | Val loss: 1.0049 | Val acc: 46.08% | LR: 0.000011
Epoch: 027 | Train loss: 0.9999 | Train acc: 49.85% | Val loss: 1.0093 | Val acc: 46.20% | LR: 0.000011
Epoch: 028 | Train loss: 0.9996 | Train acc: 50.54% | Val loss: 1.0054 | Val acc: 46.15% | LR: 0.000011
Epoch: 029 | Train loss: 1.0000 | Train acc: 49.86% | Val loss: 1.0097 | Val acc: 46.10% | LR: 0.000011
Epoch: 030 | Train loss: 1.0001 | Train acc: 50.51% | Val loss: 1.0055 | Val acc: 45.95% | LR: 0.000011
Epoch: 031 | Train loss: 0.9992 | Train acc: 50.86% | Val loss: 1.0054 | Val acc: 46.16% | LR: 0.000010
Epoch: 032 | Train loss: 0.9993 | Train acc: 50.85% | Val loss: 1.0067 | Val acc: 46.12% | LR: 0.000010
Epoch: 033 | Train loss: 0.9993 | Train acc: 50.65% | Val loss: 1.0075 | Val acc: 46.16% | LR: 0.000010
Epoch: 034 | Train loss: 1.0014 | Train acc: 50.25% | Val loss: 1.0048 | Val acc: 46.24% | LR: 0.000010
Epoch: 035 | Train loss: 0.9994 | Train acc: 50.45% | Val loss: 1.0062 | Val acc: 46.05% | LR: 0.000010
Epoch: 036 | Train loss: 0.9987 | Train acc: 50.78% | Val loss: 1.0054 | Val acc: 46.14% | LR: 0.000010
Epoch: 037 | Train loss: 0.9994 | Train acc: 50.36% | Val loss: 1.0042 | Val acc: 46.11% | LR: 0.000010
Epoch: 038 | Train loss: 0.9990 | Train acc: 50.79% | Val loss: 1.0071 | Val acc: 46.16% | LR: 0.000010
Epoch: 039 | Train loss: 0.9996 | Train acc: 50.23% | Val loss: 1.0060 | Val acc: 46.14% | LR: 0.000010
Epoch: 040 | Train loss: 1.0001 | Train acc: 50.76% | Val loss: 1.0063 | Val acc: 46.22% | LR: 0.000010
Epoch: 041 | Train loss: 0.9992 | Train acc: 50.49% | Val loss: 1.0041 | Val acc: 46.28% | LR: 0.000010
Epoch: 042 | Train loss: 1.0000 | Train acc: 50.30% | Val loss: 1.0069 | Val acc: 46.18% | LR: 0.000010
Epoch: 043 | Train loss: 0.9986 | Train acc: 50.76% | Val loss: 1.0067 | Val acc: 46.23% | LR: 0.000010
Epoch: 044 | Train loss: 0.9986 | Train acc: 50.86% | Val loss: 1.0109 | Val acc: 46.14% | LR: 0.000009
Epoch: 045 | Train loss: 0.9996 | Train acc: 50.59% | Val loss: 1.0053 | Val acc: 46.28% | LR: 0.000009
Epoch: 046 | Train loss: 1.0017 | Train acc: 50.34% | Val loss: 1.0069 | Val acc: 46.02% | LR: 0.000009
Epoch: 047 | Train loss: 0.9989 | Train acc: 50.58% | Val loss: 1.0077 | Val acc: 46.27% | LR: 0.000009
Epoch: 048 | Train loss: 0.9998 | Train acc: 50.16% | Val loss: 1.0116 | Val acc: 46.22% | LR: 0.000009
Epoch: 049 | Train loss: 0.9993 | Train acc: 50.33% | Val loss: 1.0120 | Val acc: 46.14% | LR: 0.000009
Epoch: 050 | Train loss: 0.9979 | Train acc: 51.13% | Val loss: 1.0288 | Val acc: 46.14% | LR: 0.000009
Epoch: 051 | Train loss: 0.9985 | Train acc: 50.94% | Val loss: 1.0078 | Val acc: 46.16% | LR: 0.000009
Epoch: 052 | Train loss: 0.9992 | Train acc: 50.33% | Val loss: 1.0060 | Val acc: 46.11% | LR: 0.000009
Epoch: 053 | Train loss: 0.9995 | Train acc: 50.36% | Val loss: 1.0058 | Val acc: 46.21% | LR: 0.000009
Epoch: 054 | Train loss: 0.9978 | Train acc: 50.53% | Val loss: 1.0058 | Val acc: 46.18% | LR: 0.000008
Epoch: 055 | Train loss: 0.9981 | Train acc: 50.76% | Val loss: 1.0066 | Val acc: 46.15% | LR: 0.000008
Epoch: 056 | Train loss: 0.9988 | Train acc: 50.61% | Val loss: 1.0102 | Val acc: 46.23% | LR: 0.000008
Epoch: 057 | Train loss: 0.9987 | Train acc: 50.51% | Val loss: 1.0081 | Val acc: 46.12% | LR: 0.000008
Epoch: 058 | Train loss: 0.9996 | Train acc: 50.14% | Val loss: 1.0055 | Val acc: 46.18% | LR: 0.000008

[I 2025-09-23 18:53:07,440] Trial 133 finished with value: 0.46136532425880433 and parameters: {'lr': 1.1646880300357918e-05, 'hidden_size': 72, 'dropout': 0.17661598223959965, 'weight_decay': 8.418129856590873e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 0.9938 | Train acc: 50.91% | Val loss: 0.9987 | Val acc: 54.17% | LR: 0.000023
Epoch: 001 | Train loss: 0.9935 | Train acc: 50.74% | Val loss: 0.9988 | Val acc: 54.38% | LR: 0.000023
Epoch: 002 | Train loss: 0.9919 | Train acc: 50.62% | Val loss: 0.9988 | Val acc: 54.12% | LR: 0.000023
Epoch: 003 | Train loss: 0.9948 | Train acc: 50.55% | Val loss: 0.9988 | Val acc: 54.03% | LR: 0.000023
Epoch: 004 | Train loss: 0.9942 | Train acc: 50.62% | Val loss: 0.9989 | Val acc: 53.62% | LR: 0.000023
Epoch: 005 | Train loss: 0.9967 | Train acc: 50.35% | Val loss: 0.9990 | Val acc: 53.31% | LR: 0.000023
Epoch: 006 | Train loss: 0.9921 | Train acc: 50.81% | Val loss: 0.9987 | Val acc: 53.37% | LR: 0.000023
Epoch: 007 | Train loss: 0.9972 | Train acc: 50.41% | Val loss: 0.9990 | Val acc: 53.47% | LR: 0.000023
Epoch: 008 | Train loss: 0.9962 | Train acc: 50.63% | Val loss: 0.9990 | Val acc: 53.21% | LR: 0.000022
Epoch: 009 | Train loss: 0.9977 | Train acc: 50.31% | Val loss: 0.9991 | Val acc: 53.13% | LR: 0.000022
Epoch: 010 | Train loss: 0.9972 | Train acc: 50.63% | Val loss: 0.9990 | Val acc: 53.19% | LR: 0.000022
Epoch: 011 | Train loss: 0.9967 | Train acc: 50.67% | Val loss: 1.0006 | Val acc: 52.82% | LR: 0.000022
Epoch: 012 | Train loss: 0.9973 | Train acc: 50.46% | Val loss: 0.9989 | Val acc: 52.92% | LR: 0.000022
Epoch: 013 | Train loss: 0.9956 | Train acc: 50.63% | Val loss: 0.9989 | Val acc: 52.81% | LR: 0.000022
Epoch: 014 | Train loss: 0.9959 | Train acc: 50.57% | Val loss: 0.9990 | Val acc: 52.49% | LR: 0.000022
Epoch: 015 | Train loss: 0.9912 | Train acc: 50.94% | Val loss: 0.9989 | Val acc: 52.67% | LR: 0.000022
Epoch: 016 | Train loss: 0.9911 | Train acc: 51.02% | Val loss: 0.9989 | Val acc: 52.49% | LR: 0.000022
Epoch: 017 | Train loss: 0.9894 | Train acc: 51.26% | Val loss: 0.9987 | Val acc: 52.27% | LR: 0.000022
Epoch: 018 | Train loss: 0.9951 | Train acc: 50.52% | Val loss: 0.9990 | Val acc: 51.86% | LR: 0.000022
Epoch: 019 | Train loss: 0.9911 | Train acc: 50.96% | Val loss: 0.9991 | Val acc: 51.66% | LR: 0.000022
Epoch: 020 | Train loss: 0.9908 | Train acc: 50.99% | Val loss: 0.9991 | Val acc: 51.70% | LR: 0.000022
Epoch: 021 | Train loss: 0.9891 | Train acc: 51.21% | Val loss: 0.9992 | Val acc: 51.34% | LR: 0.000022
Epoch: 022 | Train loss: 0.9940 | Train acc: 50.74% | Val loss: 0.9992 | Val acc: 51.16% | LR: 0.000021
Epoch: 023 | Train loss: 0.9892 | Train acc: 51.31% | Val loss: 0.9991 | Val acc: 51.26% | LR: 0.000021
Epoch: 024 | Train loss: 0.9927 | Train acc: 50.85% | Val loss: 0.9992 | Val acc: 51.24% | LR: 0.000021
Epoch: 025 | Train loss: 0.9897 | Train acc: 51.39% | Val loss: 0.9991 | Val acc: 51.19% | LR: 0.000021
Epoch: 026 | Train loss: 0.9986 | Train acc: 50.24% | Val loss: 0.9991 | Val acc: 51.20% | LR: 0.000021
Epoch: 027 | Train loss: 0.9868 | Train acc: 51.38% | Val loss: 0.9990 | Val acc: 51.40% | LR: 0.000021
Epoch: 028 | Train loss: 0.9925 | Train acc: 50.73% | Val loss: 0.9991 | Val acc: 51.18% | LR: 0.000021
Epoch: 029 | Train loss: 0.9874 | Train acc: 51.17% | Val loss: 0.9990 | Val acc: 51.20% | LR: 0.000021
Epoch: 030 | Train loss: 0.9943 | Train acc: 50.67% | Val loss: 0.9990 | Val acc: 51.20% | LR: 0.000020
Epoch: 031 | Train loss: 1.0010 | Train acc: 50.57% | Val loss: 0.9990 | Val acc: 51.20% | LR: 0.000020
Epoch: 032 | Train loss: 0.9949 | Train acc: 50.68% | Val loss: 0.9989 | Val acc: 51.08% | LR: 0.000020
Epoch: 033 | Train loss: 0.9953 | Train acc: 50.77% | Val loss: 0.9989 | Val acc: 51.26% | LR: 0.000020
Epoch: 034 | Train loss: 0.9889 | Train acc: 51.31% | Val loss: 0.9989 | Val acc: 51.30% | LR: 0.000020
Epoch: 035 | Train loss: 0.9865 | Train acc: 51.29% | Val loss: 0.9988 | Val acc: 51.32% | LR: 0.000020
Epoch: 036 | Train loss: 0.9994 | Train acc: 50.30% | Val loss: 0.9988 | Val acc: 51.32% | LR: 0.000020
Epoch: 037 | Train loss: 0.9935 | Train acc: 50.78% | Val loss: 0.9988 | Val acc: 51.34% | LR: 0.000019
Epoch: 038 | Train loss: 0.9979 | Train acc: 50.32% | Val loss: 0.9988 | Val acc: 51.32% | LR: 0.000019
Epoch: 039 | Train loss: 0.9947 | Train acc: 50.40% | Val loss: 0.9987 | Val acc: 51.34% | LR: 0.000019
Epoch: 040 | Train loss: 0.9923 | Train acc: 50.51% | Val loss: 0.9987 | Val acc: 51.26% | LR: 0.000019
Epoch: 041 | Train loss: 0.9946 | Train acc: 50.66% | Val loss: 0.9988 | Val acc: 51.15% | LR: 0.000019
Epoch: 042 | Train loss: 0.9926 | Train acc: 50.85% | Val loss: 0.9987 | Val acc: 51.10% | LR: 0.000019
Epoch: 043 | Train loss: 0.9945 | Train acc: 50.68% | Val loss: 0.9987 | Val acc: 51.13% | LR: 0.000018
Epoch: 044 | Train loss: 0.9912 | Train acc: 51.06% | Val loss: 0.9987 | Val acc: 51.08% | LR: 0.000018
Epoch: 045 | Train loss: 0.9827 | Train acc: 51.49% | Val loss: 0.9987 | Val acc: 51.15% | LR: 0.000018
Epoch: 046 | Train loss: 0.9941 | Train acc: 50.80% | Val loss: 0.9987 | Val acc: 51.15% | LR: 0.000018
Epoch: 047 | Train loss: 1.0010 | Train acc: 50.39% | Val loss: 0.9986 | Val acc: 51.23% | LR: 0.000018
Epoch: 048 | Train loss: 0.9908 | Train acc: 51.07% | Val loss: 0.9986 | Val acc: 51.23% | LR: 0.000017
Epoch: 049 | Train loss: 0.9933 | Train acc: 50.79% | Val loss: 0.9986 | Val acc: 51.18% | LR: 0.000017
Epoch: 050 | Train loss: 1.0010 | Train acc: 50.21% | Val loss: 0.9985 | Val acc: 51.11% | LR: 0.000017

[I 2025-09-23 18:53:51,718] Trial 134 finished with value: 0.5121398627758026 and parameters: {'lr': 2.2661169468532637e-05, 'hidden_size': 78, 'dropout': 0.21322972201260337, 'weight_decay': 4.842455155379778e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 0.9990 | Train acc: 50.36% | Val loss: 1.0023 | Val acc: 52.51% | LR: 0.000016
Epoch: 001 | Train loss: 0.9986 | Train acc: 50.49% | Val loss: 0.9995 | Val acc: 53.00% | LR: 0.000016
Epoch: 002 | Train loss: 0.9985 | Train acc: 50.51% | Val loss: 1.0031 | Val acc: 53.17% | LR: 0.000016
Epoch: 003 | Train loss: 0.9981 | Train acc: 51.09% | Val loss: 1.0007 | Val acc: 52.97% | LR: 0.000016
Epoch: 004 | Train loss: 0.9992 | Train acc: 50.57% | Val loss: 1.0103 | Val acc: 52.92% | LR: 0.000016
Epoch: 005 | Train loss: 1.0002 | Train acc: 50.83% | Val loss: 1.0023 | Val acc: 52.92% | LR: 0.000016
Epoch: 006 | Train loss: 0.9985 | Train acc: 51.29% | Val loss: 0.9995 | Val acc: 52.76% | LR: 0.000016
Epoch: 007 | Train loss: 0.9980 | Train acc: 51.20% | Val loss: 1.0539 | Val acc: 52.66% | LR: 0.000016
Epoch: 008 | Train loss: 1.0028 | Train acc: 50.76% | Val loss: 0.9990 | Val acc: 52.60% | LR: 0.000016
Epoch: 009 | Train loss: 0.9982 | Train acc: 50.86% | Val loss: 1.0189 | Val acc: 52.47% | LR: 0.000016
Epoch: 010 | Train loss: 0.9981 | Train acc: 51.20% | Val loss: 1.0039 | Val acc: 52.78% | LR: 0.000016
Epoch: 011 | Train loss: 0.9991 | Train acc: 50.73% | Val loss: 1.0008 | Val acc: 53.00% | LR: 0.000016
Epoch: 012 | Train loss: 0.9995 | Train acc: 50.88% | Val loss: 1.0073 | Val acc: 53.23% | LR: 0.000015
Epoch: 013 | Train loss: 1.0001 | Train acc: 51.79% | Val loss: 0.9982 | Val acc: 53.21% | LR: 0.000015
Epoch: 014 | Train loss: 0.9996 | Train acc: 50.94% | Val loss: 0.9972 | Val acc: 53.09% | LR: 0.000015
Epoch: 015 | Train loss: 0.9995 | Train acc: 50.16% | Val loss: 1.0458 | Val acc: 53.15% | LR: 0.000015
Epoch: 016 | Train loss: 0.9992 | Train acc: 50.79% | Val loss: 1.0120 | Val acc: 53.02% | LR: 0.000015
Epoch: 017 | Train loss: 0.9987 | Train acc: 51.16% | Val loss: 0.9989 | Val acc: 53.11% | LR: 0.000015
Epoch: 018 | Train loss: 0.9980 | Train acc: 51.51% | Val loss: 1.0090 | Val acc: 53.06% | LR: 0.000015
Epoch: 019 | Train loss: 0.9991 | Train acc: 51.09% | Val loss: 0.9983 | Val acc: 53.25% | LR: 0.000015
Epoch: 020 | Train loss: 1.0015 | Train acc: 49.94% | Val loss: 0.9977 | Val acc: 53.34% | LR: 0.000015
Epoch: 021 | Train loss: 0.9978 | Train acc: 50.76% | Val loss: 1.0009 | Val acc: 53.28% | LR: 0.000015
Epoch: 022 | Train loss: 0.9977 | Train acc: 51.23% | Val loss: 1.0001 | Val acc: 53.36% | LR: 0.000015
Epoch: 023 | Train loss: 0.9981 | Train acc: 50.66% | Val loss: 0.9974 | Val acc: 53.42% | LR: 0.000015
Epoch: 024 | Train loss: 0.9969 | Train acc: 50.64% | Val loss: 0.9977 | Val acc: 53.51% | LR: 0.000015
Epoch: 025 | Train loss: 0.9985 | Train acc: 50.39% | Val loss: 0.9985 | Val acc: 53.43% | LR: 0.000015
Epoch: 026 | Train loss: 0.9971 | Train acc: 50.74% | Val loss: 0.9983 | Val acc: 53.37% | LR: 0.000015
Epoch: 027 | Train loss: 0.9983 | Train acc: 50.66% | Val loss: 1.0046 | Val acc: 53.39% | LR: 0.000015
Epoch: 028 | Train loss: 0.9969 | Train acc: 50.88% | Val loss: 1.0149 | Val acc: 53.34% | LR: 0.000014
Epoch: 029 | Train loss: 0.9980 | Train acc: 50.86% | Val loss: 0.9973 | Val acc: 53.21% | LR: 0.000014
Epoch: 030 | Train loss: 0.9974 | Train acc: 50.25% | Val loss: 0.9978 | Val acc: 53.33% | LR: 0.000014
Epoch: 031 | Train loss: 1.0015 | Train acc: 50.51% | Val loss: 0.9965 | Val acc: 53.31% | LR: 0.000014
Epoch: 032 | Train loss: 0.9970 | Train acc: 51.07% | Val loss: 0.9979 | Val acc: 53.35% | LR: 0.000014
Epoch: 033 | Train loss: 0.9965 | Train acc: 50.97% | Val loss: 1.0129 | Val acc: 53.27% | LR: 0.000014
Epoch: 034 | Train loss: 0.9972 | Train acc: 50.92% | Val loss: 0.9978 | Val acc: 53.33% | LR: 0.000014
Epoch: 035 | Train loss: 0.9972 | Train acc: 50.48% | Val loss: 0.9966 | Val acc: 53.33% | LR: 0.000014
Epoch: 036 | Train loss: 0.9979 | Train acc: 50.41% | Val loss: 0.9980 | Val acc: 53.43% | LR: 0.000014
Epoch: 037 | Train loss: 0.9961 | Train acc: 50.91% | Val loss: 1.0033 | Val acc: 53.45% | LR: 0.000014
Epoch: 038 | Train loss: 0.9975 | Train acc: 50.47% | Val loss: 1.0006 | Val acc: 53.25% | LR: 0.000013
Epoch: 039 | Train loss: 0.9965 | Train acc: 50.84% | Val loss: 0.9970 | Val acc: 53.19% | LR: 0.000013
Epoch: 040 | Train loss: 0.9993 | Train acc: 50.69% | Val loss: 1.0024 | Val acc: 53.35% | LR: 0.000013
Epoch: 041 | Train loss: 0.9976 | Train acc: 50.35% | Val loss: 0.9984 | Val acc: 53.46% | LR: 0.000013
Epoch: 042 | Train loss: 0.9981 | Train acc: 50.25% | Val loss: 0.9968 | Val acc: 53.35% | LR: 0.000013
Epoch: 043 | Train loss: 0.9983 | Train acc: 50.05% | Val loss: 0.9969 | Val acc: 53.40% | LR: 0.000013
Epoch: 044 | Train loss: 0.9979 | Train acc: 50.31% | Val loss: 0.9978 | Val acc: 53.36% | LR: 0.000013
Epoch: 045 | Train loss: 0.9979 | Train acc: 50.56% | Val loss: 1.0020 | Val acc: 53.40% | LR: 0.000013
Epoch: 046 | Train loss: 0.9982 | Train acc: 49.77% | Val loss: 0.9982 | Val acc: 53.40% | LR: 0.000012
Epoch: 047 | Train loss: 0.9992 | Train acc: 50.00% | Val loss: 0.9975 | Val acc: 53.44% | LR: 0.000012
Epoch: 048 | Train loss: 0.9974 | Train acc: 50.33% | Val loss: 0.9996 | Val acc: 53.45% | LR: 0.000012
Epoch: 049 | Train loss: 0.9958 | Train acc: 50.78% | Val loss: 0.9974 | Val acc: 53.34% | LR: 0.000012
Epoch: 050 | Train loss: 0.9973 | Train acc: 50.68% | Val loss: 0.9969 | Val acc: 53.40% | LR: 0.000012
Epoch: 051 | Train loss: 0.9964 | Train acc: 50.66% | Val loss: 0.9969 | Val acc: 53.30% | LR: 0.000012
Epoch: 052 | Train loss: 0.9976 | Train acc: 50.33% | Val loss: 0.9981 | Val acc: 53.22% | LR: 0.000012
Epoch: 053 | Train loss: 0.9953 | Train acc: 50.84% | Val loss: 0.9969 | Val acc: 53.32% | LR: 0.000012
Epoch: 054 | Train loss: 0.9989 | Train acc: 49.95% | Val loss: 0.9983 | Val acc: 53.33% | LR: 0.000011
Epoch: 055 | Train loss: 0.9966 | Train acc: 50.32% | Val loss: 0.9988 | Val acc: 53.20% | LR: 0.000011
Epoch: 056 | Train loss: 0.9952 | Train acc: 50.90% | Val loss: 0.9977 | Val acc: 53.10% | LR: 0.000011
Epoch: 057 | Train loss: 0.9967 | Train acc: 50.58% | Val loss: 0.9975 | Val acc: 53.08% | LR: 0.000011
Epoch: 058 | Train loss: 0.9936 | Train acc: 51.12% | Val loss: 0.9971 | Val acc: 53.12% | LR: 0.000011
Epoch: 059 | Train loss: 0.9953 | Train acc: 50.68% | Val loss: 0.9975 | Val acc: 53.14% | LR: 0.000011
Epoch: 060 | Train loss: 0.9986 | Train acc: 50.19% | Val loss: 0.9971 | Val acc: 53.16% | LR: 0.000010
Epoch: 061 | Train loss: 0.9972 | Train acc: 50.34% | Val loss: 0.9972 | Val acc: 53.19% | LR: 0.000010
Epoch: 062 | Train loss: 0.9961 | Train acc: 50.75% | Val loss: 0.9977 | Val acc: 53.00% | LR: 0.000010
Epoch: 063 | Train loss: 0.9956 | Train acc: 50.49% | Val loss: 0.9968 | Val acc: 53.04% | LR: 0.000010
Epoch: 064 | Train loss: 0.9984 | Train acc: 50.03% | Val loss: 0.9996 | Val acc: 52.80% | LR: 0.000010
Epoch: 065 | Train loss: 0.9957 | Train acc: 50.68% | Val loss: 0.9973 | Val acc: 52.82% | LR: 0.000010
Epoch: 066 | Train loss: 0.9947 | Train acc: 50.98% | Val loss: 0.9974 | Val acc: 52.78% | LR: 0.000010
Epoch: 067 | Train loss: 0.9957 | Train acc: 50.66% | Val loss: 1.0090 | Val acc: 52.68% | LR: 0.000009
Epoch: 068 | Train loss: 0.9972 | Train acc: 50.50% | Val loss: 0.9988 | Val acc: 53.08% | LR: 0.000009
Epoch: 069 | Train loss: 0.9991 | Train acc: 50.06% | Val loss: 0.9973 | Val acc: 52.84% | LR: 0.000009
Epoch: 070 | Train loss: 0.9966 | Train acc: 50.39% | Val loss: 0.9992 | Val acc: 52.76% | LR: 0.000009
Epoch: 071 | Train loss: 0.9975 | Train acc: 50.29% | Val loss: 0.9963 | Val acc: 52.92% | LR: 0.000009
Epoch: 072 | Train loss: 0.9955 | Train acc: 50.66% | Val loss: 0.9967 | Val acc: 52.78% | LR: 0.000009
Epoch: 073 | Train loss: 0.9919 | Train acc: 51.20% | Val loss: 0.9978 | Val acc: 52.74% | LR: 0.000009

[I 2025-09-23 18:54:55,292] Trial 135 finished with value: 0.5258466958999634 and parameters: {'lr': 1.5738372704144244e-05, 'hidden_size': 69, 'dropout': 0.19025750793124357, 'weight_decay': 3.6800376012913595e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0003 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000021
Epoch: 001 | Train loss: 1.0007 | Train acc: 49.72% | Val loss: 0.9916 | Val acc: 54.13% | LR: 0.000021
Epoch: 002 | Train loss: 1.0004 | Train acc: 49.54% | Val loss: 0.9916 | Val acc: 54.11% | LR: 0.000021
Epoch: 003 | Train loss: 1.0007 | Train acc: 49.54% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000021
Epoch: 004 | Train loss: 1.0012 | Train acc: 49.30% | Val loss: 0.9917 | Val acc: 54.17% | LR: 0.000021
Epoch: 005 | Train loss: 0.9986 | Train acc: 49.93% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000021
Epoch: 006 | Train loss: 1.0008 | Train acc: 49.69% | Val loss: 0.9918 | Val acc: 54.24% | LR: 0.000021
Epoch: 007 | Train loss: 1.0012 | Train acc: 49.74% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000021
Epoch: 008 | Train loss: 1.0007 | Train acc: 49.57% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000021
Epoch: 009 | Train loss: 0.9989 | Train acc: 50.49% | Val loss: 0.9921 | Val acc: 54.32% | LR: 0.000021
Epoch: 010 | Train loss: 0.9984 | Train acc: 50.71% | Val loss: 0.9921 | Val acc: 54.32% | LR: 0.000021
Epoch: 011 | Train loss: 0.9982 | Train acc: 50.74% | Val loss: 0.9920 | Val acc: 54.34% | LR: 0.000021
Epoch: 012 | Train loss: 0.9979 | Train acc: 50.74% | Val loss: 0.9920 | Val acc: 54.36% | LR: 0.000020
Epoch: 013 | Train loss: 0.9989 | Train acc: 50.45% | Val loss: 0.9918 | Val acc: 54.38% | LR: 0.000020
Epoch: 014 | Train loss: 0.9982 | Train acc: 50.53% | Val loss: 0.9919 | Val acc: 54.42% | LR: 0.000020
Epoch: 015 | Train loss: 0.9991 | Train acc: 50.16% | Val loss: 0.9919 | Val acc: 54.30% | LR: 0.000020
Epoch: 016 | Train loss: 0.9980 | Train acc: 50.60% | Val loss: 0.9920 | Val acc: 54.36% | LR: 0.000020
Epoch: 017 | Train loss: 0.9983 | Train acc: 50.58% | Val loss: 0.9918 | Val acc: 54.17% | LR: 0.000020
Epoch: 018 | Train loss: 0.9989 | Train acc: 50.45% | Val loss: 0.9969 | Val acc: 54.43% | LR: 0.000020
Epoch: 019 | Train loss: 0.9996 | Train acc: 50.27% | Val loss: 0.9918 | Val acc: 54.33% | LR: 0.000020
Epoch: 020 | Train loss: 0.9964 | Train acc: 51.28% | Val loss: 0.9918 | Val acc: 54.39% | LR: 0.000020
Epoch: 021 | Train loss: 0.9972 | Train acc: 50.86% | Val loss: 0.9917 | Val acc: 54.48% | LR: 0.000020
Epoch: 022 | Train loss: 0.9970 | Train acc: 50.92% | Val loss: 0.9917 | Val acc: 54.30% | LR: 0.000020
Epoch: 023 | Train loss: 0.9981 | Train acc: 50.48% | Val loss: 0.9916 | Val acc: 54.34% | LR: 0.000020
Epoch: 024 | Train loss: 0.9979 | Train acc: 50.52% | Val loss: 0.9917 | Val acc: 54.48% | LR: 0.000020
Epoch: 025 | Train loss: 0.9987 | Train acc: 50.18% | Val loss: 0.9917 | Val acc: 54.50% | LR: 0.000019
Epoch: 026 | Train loss: 0.9978 | Train acc: 50.54% | Val loss: 0.9916 | Val acc: 54.54% | LR: 0.000019
Epoch: 027 | Train loss: 0.9971 | Train acc: 50.91% | Val loss: 0.9917 | Val acc: 54.52% | LR: 0.000019
Epoch: 028 | Train loss: 0.9968 | Train acc: 51.11% | Val loss: 0.9917 | Val acc: 54.48% | LR: 0.000019
Epoch: 029 | Train loss: 0.9969 | Train acc: 51.05% | Val loss: 0.9916 | Val acc: 54.56% | LR: 0.000019
Epoch: 030 | Train loss: 0.9980 | Train acc: 50.69% | Val loss: 0.9916 | Val acc: 54.68% | LR: 0.000019
Epoch: 031 | Train loss: 0.9984 | Train acc: 50.61% | Val loss: 0.9915 | Val acc: 54.64% | LR: 0.000019
Epoch: 032 | Train loss: 0.9960 | Train acc: 51.22% | Val loss: 0.9914 | Val acc: 54.65% | LR: 0.000019
Epoch: 033 | Train loss: 0.9981 | Train acc: 50.17% | Val loss: 0.9914 | Val acc: 54.64% | LR: 0.000018
Epoch: 034 | Train loss: 0.9958 | Train acc: 51.15% | Val loss: 0.9915 | Val acc: 54.53% | LR: 0.000018
Epoch: 035 | Train loss: 0.9978 | Train acc: 50.63% | Val loss: 0.9915 | Val acc: 54.73% | LR: 0.000018
Epoch: 036 | Train loss: 0.9968 | Train acc: 50.82% | Val loss: 0.9914 | Val acc: 54.53% | LR: 0.000018
Epoch: 037 | Train loss: 0.9967 | Train acc: 50.76% | Val loss: 0.9915 | Val acc: 54.47% | LR: 0.000018
Epoch: 038 | Train loss: 0.9978 | Train acc: 50.58% | Val loss: 0.9915 | Val acc: 54.47% | LR: 0.000018
Epoch: 039 | Train loss: 0.9952 | Train acc: 50.80% | Val loss: 0.9914 | Val acc: 54.56% | LR: 0.000018
Epoch: 040 | Train loss: 0.9964 | Train acc: 51.00% | Val loss: 0.9913 | Val acc: 54.49% | LR: 0.000017
Epoch: 041 | Train loss: 0.9967 | Train acc: 50.95% | Val loss: 0.9913 | Val acc: 54.43% | LR: 0.000017
Epoch: 042 | Train loss: 0.9972 | Train acc: 50.84% | Val loss: 0.9913 | Val acc: 54.50% | LR: 0.000017
Epoch: 043 | Train loss: 0.9972 | Train acc: 50.41% | Val loss: 0.9913 | Val acc: 54.54% | LR: 0.000017
Epoch: 044 | Train loss: 0.9971 | Train acc: 50.66% | Val loss: 0.9912 | Val acc: 54.42% | LR: 0.000017
Epoch: 045 | Train loss: 0.9956 | Train acc: 51.08% | Val loss: 0.9912 | Val acc: 54.54% | LR: 0.000017
Epoch: 046 | Train loss: 0.9952 | Train acc: 50.76% | Val loss: 0.9912 | Val acc: 54.61% | LR: 0.000016
Epoch: 047 | Train loss: 0.9959 | Train acc: 51.10% | Val loss: 0.9911 | Val acc: 54.45% | LR: 0.000016
Epoch: 048 | Train loss: 0.9964 | Train acc: 50.75% | Val loss: 0.9911 | Val acc: 54.38% | LR: 0.000016
Epoch: 049 | Train loss: 0.9967 | Train acc: 50.57% | Val loss: 0.9911 | Val acc: 54.40% | LR: 0.000016
Epoch: 050 | Train loss: 0.9977 | Train acc: 50.41% | Val loss: 0.9910 | Val acc: 54.40% | LR: 0.000016
Epoch: 051 | Train loss: 0.9948 | Train acc: 51.13% | Val loss: 0.9911 | Val acc: 54.38% | LR: 0.000016
Epoch: 052 | Train loss: 0.9986 | Train acc: 50.17% | Val loss: 0.9911 | Val acc: 54.41% | LR: 0.000015
Epoch: 053 | Train loss: 0.9960 | Train acc: 51.06% | Val loss: 0.9911 | Val acc: 54.49% | LR: 0.000015
Epoch: 054 | Train loss: 0.9948 | Train acc: 51.05% | Val loss: 0.9911 | Val acc: 54.49% | LR: 0.000015
Epoch: 055 | Train loss: 0.9951 | Train acc: 50.80% | Val loss: 0.9910 | Val acc: 54.29% | LR: 0.000015
Epoch: 056 | Train loss: 0.9949 | Train acc: 50.82% | Val loss: 0.9910 | Val acc: 54.34% | LR: 0.000015
Epoch: 057 | Train loss: 0.9950 | Train acc: 51.08% | Val loss: 0.9909 | Val acc: 54.23% | LR: 0.000014
Epoch: 058 | Train loss: 0.9965 | Train acc: 50.67% | Val loss: 0.9909 | Val acc: 54.15% | LR: 0.000014
Epoch: 059 | Train loss: 0.9953 | Train acc: 50.74% | Val loss: 0.9909 | Val acc: 54.09% | LR: 0.000014
Epoch: 060 | Train loss: 0.9944 | Train acc: 51.03% | Val loss: 0.9909 | Val acc: 54.01% | LR: 0.000014
Epoch: 061 | Train loss: 0.9929 | Train acc: 51.66% | Val loss: 0.9908 | Val acc: 53.91% | LR: 0.000014
Epoch: 062 | Train loss: 0.9929 | Train acc: 51.42% | Val loss: 0.9908 | Val acc: 53.79% | LR: 0.000013
Epoch: 063 | Train loss: 0.9968 | Train acc: 50.61% | Val loss: 0.9908 | Val acc: 53.73% | LR: 0.000013
Epoch: 064 | Train loss: 0.9955 | Train acc: 50.69% | Val loss: 0.9907 | Val acc: 53.65% | LR: 0.000013
Epoch: 065 | Train loss: 0.9943 | Train acc: 51.01% | Val loss: 0.9908 | Val acc: 53.47% | LR: 0.000013
Epoch: 066 | Train loss: 0.9957 | Train acc: 51.10% | Val loss: 0.9908 | Val acc: 53.35% | LR: 0.000013
Epoch: 067 | Train loss: 0.9952 | Train acc: 50.48% | Val loss: 0.9908 | Val acc: 53.28% | LR: 0.000012
Epoch: 068 | Train loss: 0.9960 | Train acc: 50.48% | Val loss: 0.9907 | Val acc: 53.30% | LR: 0.000012
Epoch: 069 | Train loss: 0.9953 | Train acc: 50.93% | Val loss: 0.9910 | Val acc: 53.30% | LR: 0.000012
Epoch: 070 | Train loss: 0.9932 | Train acc: 51.04% | Val loss: 0.9909 | Val acc: 53.24% | LR: 0.000012
Epoch: 071 | Train loss: 0.9961 | Train acc: 50.65% | Val loss: 0.9906 | Val acc: 53.20% | LR: 0.000012
Epoch: 072 | Train loss: 0.9933 | Train acc: 51.18% | Val loss: 0.9903 | Val acc: 53.17% | LR: 0.000011
Epoch: 073 | Train loss: 0.9946 | Train acc: 51.44% | Val loss: 0.9905 | Val acc: 52.99% | LR: 0.000011
Epoch: 074 | Train loss: 0.9926 | Train acc: 50.85% | Val loss: 0.9905 | Val acc: 53.02% | LR: 0.000011
Epoch: 075 | Train loss: 0.9941 | Train acc: 50.75% | Val loss: 0.9908 | Val acc: 53.06% | LR: 0.000011
Epoch: 076 | Train loss: 0.9952 | Train acc: 50.97% | Val loss: 0.9903 | Val acc: 53.04% | LR: 0.000011
Epoch: 077 | Train loss: 0.9946 | Train acc: 51.22% | Val loss: 0.9903 | Val acc: 53.06% | LR: 0.000010
Epoch: 078 | Train loss: 0.9932 | Train acc: 51.24% | Val loss: 0.9904 | Val acc: 53.02% | LR: 0.000010
Epoch: 079 | Train loss: 0.9941 | Train acc: 51.14% | Val loss: 0.9904 | Val acc: 53.02% | LR: 0.000010
Epoch: 080 | Train loss: 0.9942 | Train acc: 50.87% | Val loss: 0.9905 | Val acc: 53.02% | LR: 0.000010
Epoch: 081 | Train loss: 0.9936 | Train acc: 50.96% | Val loss: 0.9912 | Val acc: 52.96% | LR: 0.000009
Epoch: 082 | Train loss: 0.9950 | Train acc: 50.44% | Val loss: 0.9905 | Val acc: 52.96% | LR: 0.000009
Epoch: 083 | Train loss: 0.9941 | Train acc: 51.24% | Val loss: 0.9903 | Val acc: 52.98% | LR: 0.000009
Epoch: 084 | Train loss: 0.9937 | Train acc: 51.06% | Val loss: 0.9913 | Val acc: 52.96% | LR: 0.000009

[I 2025-09-23 18:55:58,490] Trial 136 finished with value: 0.5290101051330567 and parameters: {'lr': 2.0846665121590776e-05, 'hidden_size': 64, 'dropout': 0.12237248319425822, 'weight_decay': 0.00011719876280283588}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 0.9978 | Train acc: 50.40% | Val loss: 0.9997 | Val acc: 49.51% | LR: 0.000017
Epoch: 001 | Train loss: 0.9958 | Train acc: 50.38% | Val loss: 0.9998 | Val acc: 49.76% | LR: 0.000017
Epoch: 002 | Train loss: 0.9940 | Train acc: 50.76% | Val loss: 0.9997 | Val acc: 49.64% | LR: 0.000017
Epoch: 003 | Train loss: 0.9965 | Train acc: 50.55% | Val loss: 0.9996 | Val acc: 49.64% | LR: 0.000017
Epoch: 004 | Train loss: 0.9936 | Train acc: 50.71% | Val loss: 0.9995 | Val acc: 49.79% | LR: 0.000017
Epoch: 005 | Train loss: 0.9957 | Train acc: 50.83% | Val loss: 0.9995 | Val acc: 49.87% | LR: 0.000017
Epoch: 006 | Train loss: 0.9939 | Train acc: 50.83% | Val loss: 0.9993 | Val acc: 49.97% | LR: 0.000017
Epoch: 007 | Train loss: 0.9967 | Train acc: 50.84% | Val loss: 0.9991 | Val acc: 50.07% | LR: 0.000017
Epoch: 008 | Train loss: 0.9961 | Train acc: 51.02% | Val loss: 0.9990 | Val acc: 50.11% | LR: 0.000017
Epoch: 009 | Train loss: 0.9937 | Train acc: 50.16% | Val loss: 0.9989 | Val acc: 50.39% | LR: 0.000017
Epoch: 010 | Train loss: 0.9950 | Train acc: 51.01% | Val loss: 0.9988 | Val acc: 50.53% | LR: 0.000017
Epoch: 011 | Train loss: 0.9966 | Train acc: 50.54% | Val loss: 0.9987 | Val acc: 50.57% | LR: 0.000017
Epoch: 012 | Train loss: 0.9944 | Train acc: 50.96% | Val loss: 0.9985 | Val acc: 50.59% | LR: 0.000017
Epoch: 013 | Train loss: 0.9961 | Train acc: 50.61% | Val loss: 0.9983 | Val acc: 50.70% | LR: 0.000017
Epoch: 014 | Train loss: 0.9938 | Train acc: 50.92% | Val loss: 0.9981 | Val acc: 50.82% | LR: 0.000017
Epoch: 015 | Train loss: 0.9947 | Train acc: 50.75% | Val loss: 0.9981 | Val acc: 50.82% | LR: 0.000017
Epoch: 016 | Train loss: 0.9933 | Train acc: 50.72% | Val loss: 0.9980 | Val acc: 50.72% | LR: 0.000016
Epoch: 017 | Train loss: 0.9953 | Train acc: 50.80% | Val loss: 0.9980 | Val acc: 50.78% | LR: 0.000016
Epoch: 018 | Train loss: 0.9923 | Train acc: 50.74% | Val loss: 0.9979 | Val acc: 50.72% | LR: 0.000016
Epoch: 019 | Train loss: 0.9917 | Train acc: 51.34% | Val loss: 0.9978 | Val acc: 50.68% | LR: 0.000016
Epoch: 020 | Train loss: 0.9927 | Train acc: 50.64% | Val loss: 0.9978 | Val acc: 50.74% | LR: 0.000016
Epoch: 021 | Train loss: 0.9920 | Train acc: 51.26% | Val loss: 0.9977 | Val acc: 50.84% | LR: 0.000016
Epoch: 022 | Train loss: 0.9917 | Train acc: 50.81% | Val loss: 0.9976 | Val acc: 50.78% | LR: 0.000016
Epoch: 023 | Train loss: 0.9927 | Train acc: 51.07% | Val loss: 0.9974 | Val acc: 50.89% | LR: 0.000016
Epoch: 024 | Train loss: 0.9927 | Train acc: 51.11% | Val loss: 0.9973 | Val acc: 50.92% | LR: 0.000016
Epoch: 025 | Train loss: 0.9934 | Train acc: 50.84% | Val loss: 0.9970 | Val acc: 51.08% | LR: 0.000016
Epoch: 026 | Train loss: 0.9898 | Train acc: 50.99% | Val loss: 0.9967 | Val acc: 51.19% | LR: 0.000016
Epoch: 027 | Train loss: 0.9950 | Train acc: 50.94% | Val loss: 0.9965 | Val acc: 51.43% | LR: 0.000016
Epoch: 028 | Train loss: 0.9931 | Train acc: 50.37% | Val loss: 0.9964 | Val acc: 51.33% | LR: 0.000016
Epoch: 029 | Train loss: 0.9974 | Train acc: 50.83% | Val loss: 0.9963 | Val acc: 51.47% | LR: 0.000015
Epoch: 030 | Train loss: 0.9931 | Train acc: 50.47% | Val loss: 0.9962 | Val acc: 51.51% | LR: 0.000015
Epoch: 031 | Train loss: 0.9929 | Train acc: 50.91% | Val loss: 0.9960 | Val acc: 51.70% | LR: 0.000015
Epoch: 032 | Train loss: 0.9928 | Train acc: 50.96% | Val loss: 0.9957 | Val acc: 51.86% | LR: 0.000015
Epoch: 033 | Train loss: 0.9955 | Train acc: 50.60% | Val loss: 0.9957 | Val acc: 51.71% | LR: 0.000015
Epoch: 034 | Train loss: 0.9934 | Train acc: 51.23% | Val loss: 0.9956 | Val acc: 51.69% | LR: 0.000015
Epoch: 035 | Train loss: 0.9901 | Train acc: 51.13% | Val loss: 0.9955 | Val acc: 51.75% | LR: 0.000015
Epoch: 036 | Train loss: 0.9902 | Train acc: 50.65% | Val loss: 0.9954 | Val acc: 51.71% | LR: 0.000015
Epoch: 037 | Train loss: 0.9893 | Train acc: 51.07% | Val loss: 0.9953 | Val acc: 51.69% | LR: 0.000015
Epoch: 038 | Train loss: 0.9947 | Train acc: 50.62% | Val loss: 0.9952 | Val acc: 51.65% | LR: 0.000014
Epoch: 039 | Train loss: 0.9931 | Train acc: 50.52% | Val loss: 0.9952 | Val acc: 51.67% | LR: 0.000014
Epoch: 040 | Train loss: 0.9914 | Train acc: 51.24% | Val loss: 0.9951 | Val acc: 51.67% | LR: 0.000014
Epoch: 041 | Train loss: 0.9954 | Train acc: 50.72% | Val loss: 0.9947 | Val acc: 51.81% | LR: 0.000014
Epoch: 042 | Train loss: 0.9897 | Train acc: 51.17% | Val loss: 0.9945 | Val acc: 51.81% | LR: 0.000014
Epoch: 043 | Train loss: 0.9899 | Train acc: 50.81% | Val loss: 0.9944 | Val acc: 51.79% | LR: 0.000014
Epoch: 044 | Train loss: 0.9919 | Train acc: 50.82% | Val loss: 0.9942 | Val acc: 51.81% | LR: 0.000014
Epoch: 045 | Train loss: 0.9932 | Train acc: 50.65% | Val loss: 0.9941 | Val acc: 51.81% | LR: 0.000014
Epoch: 046 | Train loss: 0.9920 | Train acc: 50.90% | Val loss: 0.9939 | Val acc: 51.79% | LR: 0.000013
Epoch: 047 | Train loss: 0.9947 | Train acc: 50.82% | Val loss: 0.9939 | Val acc: 51.83% | LR: 0.000013
Epoch: 048 | Train loss: 0.9911 | Train acc: 51.25% | Val loss: 0.9937 | Val acc: 51.81% | LR: 0.000013
Epoch: 049 | Train loss: 0.9945 | Train acc: 50.65% | Val loss: 0.9936 | Val acc: 51.81% | LR: 0.000013
Epoch: 050 | Train loss: 0.9913 | Train acc: 51.17% | Val loss: 0.9935 | Val acc: 51.79% | LR: 0.000013
Epoch: 051 | Train loss: 0.9902 | Train acc: 50.92% | Val loss: 0.9933 | Val acc: 51.78% | LR: 0.000013
Epoch: 052 | Train loss: 0.9914 | Train acc: 51.28% | Val loss: 0.9932 | Val acc: 51.80% | LR: 0.000013
Epoch: 053 | Train loss: 0.9953 | Train acc: 50.14% | Val loss: 0.9931 | Val acc: 51.81% | LR: 0.000012
Epoch: 054 | Train loss: 0.9931 | Train acc: 51.13% | Val loss: 0.9929 | Val acc: 51.78% | LR: 0.000012
Epoch: 055 | Train loss: 0.9890 | Train acc: 51.57% | Val loss: 0.9927 | Val acc: 51.76% | LR: 0.000012
Epoch: 056 | Train loss: 0.9894 | Train acc: 51.13% | Val loss: 0.9925 | Val acc: 51.74% | LR: 0.000012
Epoch: 057 | Train loss: 0.9911 | Train acc: 51.75% | Val loss: 0.9924 | Val acc: 51.70% | LR: 0.000012
Epoch: 058 | Train loss: 0.9893 | Train acc: 51.22% | Val loss: 0.9921 | Val acc: 51.70% | LR: 0.000012
Epoch: 059 | Train loss: 0.9930 | Train acc: 50.87% | Val loss: 0.9920 | Val acc: 51.70% | LR: 0.000011
Epoch: 060 | Train loss: 0.9923 | Train acc: 51.05% | Val loss: 0.9919 | Val acc: 51.70% | LR: 0.000011
Epoch: 061 | Train loss: 0.9920 | Train acc: 51.14% | Val loss: 0.9917 | Val acc: 51.66% | LR: 0.000011
Epoch: 062 | Train loss: 0.9922 | Train acc: 50.78% | Val loss: 0.9916 | Val acc: 51.68% | LR: 0.000011
Epoch: 063 | Train loss: 0.9908 | Train acc: 50.87% | Val loss: 0.9914 | Val acc: 51.68% | LR: 0.000011
Epoch: 064 | Train loss: 0.9938 | Train acc: 50.78% | Val loss: 0.9911 | Val acc: 51.72% | LR: 0.000011
Epoch: 065 | Train loss: 0.9899 | Train acc: 51.32% | Val loss: 0.9909 | Val acc: 51.72% | LR: 0.000010
Epoch: 066 | Train loss: 0.9926 | Train acc: 50.97% | Val loss: 0.9908 | Val acc: 51.74% | LR: 0.000010
Epoch: 067 | Train loss: 0.9893 | Train acc: 51.07% | Val loss: 0.9906 | Val acc: 51.72% | LR: 0.000010
Epoch: 068 | Train loss: 0.9914 | Train acc: 51.16% | Val loss: 0.9905 | Val acc: 51.70% | LR: 0.000010
Epoch: 069 | Train loss: 0.9904 | Train acc: 51.51% | Val loss: 0.9902 | Val acc: 51.64% | LR: 0.000010
Epoch: 070 | Train loss: 0.9897 | Train acc: 51.06% | Val loss: 0.9900 | Val acc: 51.64% | LR: 0.000010
Epoch: 071 | Train loss: 0.9910 | Train acc: 51.14% | Val loss: 0.9898 | Val acc: 51.62% | LR: 0.000009
Epoch: 072 | Train loss: 0.9912 | Train acc: 50.78% | Val loss: 0.9896 | Val acc: 51.66% | LR: 0.000009
Epoch: 073 | Train loss: 0.9899 | Train acc: 50.96% | Val loss: 0.9894 | Val acc: 51.64% | LR: 0.000009
Epoch: 074 | Train loss: 0.9910 | Train acc: 51.13% | Val loss: 0.9892 | Val acc: 51.60% | LR: 0.000009
Epoch: 075 | Train loss: 0.9906 | Train acc: 51.22% | Val loss: 0.9891 | Val acc: 51.60% | LR: 0.000009
Epoch: 076 | Train loss: 0.9893 | Train acc: 51.13% | Val loss: 0.9889 | Val acc: 51.60% | LR: 0.000009
Epoch: 077 | Train loss: 0.9907 | Train acc: 50.70% | Val loss: 0.9886 | Val acc: 51.56% | LR: 0.000008
Epoch: 078 | Train loss: 0.9876 | Train acc: 51.50% | Val loss: 0.9884 | Val acc: 51.64% | LR: 0.000008
Epoch: 079 | Train loss: 0.9873 | Train acc: 51.50% | Val loss: 0.9883 | Val acc: 51.58% | LR: 0.000008
Epoch: 080 | Train loss: 0.9912 | Train acc: 50.61% | Val loss: 0.9882 | Val acc: 51.64% | LR: 0.000008
Epoch: 081 | Train loss: 0.9903 | Train acc: 50.87% | Val loss: 0.9880 | Val acc: 51.62% | LR: 0.000008

[I 2025-09-23 18:57:10,539] Trial 137 finished with value: 0.5161837100982666 and parameters: {'lr': 1.6991164481055668e-05, 'hidden_size': 77, 'dropout': 0.15936606007219425, 'weight_decay': 6.285632246398712e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0052 | Train acc: 50.63% | Val loss: 1.0022 | Val acc: 48.57% | LR: 0.000014
Epoch: 001 | Train loss: 1.0005 | Train acc: 50.01% | Val loss: 1.0018 | Val acc: 48.46% | LR: 0.000014
Epoch: 002 | Train loss: 0.9990 | Train acc: 50.40% | Val loss: 1.0020 | Val acc: 48.31% | LR: 0.000014
Epoch: 003 | Train loss: 1.0014 | Train acc: 50.07% | Val loss: 1.0024 | Val acc: 48.31% | LR: 0.000014
Epoch: 004 | Train loss: 1.0081 | Train acc: 50.43% | Val loss: 1.0027 | Val acc: 48.33% | LR: 0.000014
Epoch: 005 | Train loss: 1.0007 | Train acc: 50.46% | Val loss: 1.0024 | Val acc: 48.41% | LR: 0.000014
Epoch: 006 | Train loss: 0.9982 | Train acc: 50.71% | Val loss: 1.0018 | Val acc: 48.41% | LR: 0.000014
Epoch: 007 | Train loss: 0.9992 | Train acc: 50.34% | Val loss: 1.0018 | Val acc: 48.29% | LR: 0.000014
Epoch: 008 | Train loss: 1.0036 | Train acc: 50.47% | Val loss: 1.0026 | Val acc: 48.29% | LR: 0.000014
Epoch: 009 | Train loss: 0.9982 | Train acc: 50.49% | Val loss: 1.0019 | Val acc: 48.39% | LR: 0.000014
Epoch: 010 | Train loss: 0.9965 | Train acc: 51.11% | Val loss: 1.0027 | Val acc: 48.25% | LR: 0.000014
Epoch: 011 | Train loss: 1.0055 | Train acc: 50.29% | Val loss: 1.0018 | Val acc: 48.28% | LR: 0.000014
Epoch: 012 | Train loss: 1.0017 | Train acc: 50.58% | Val loss: 1.0027 | Val acc: 48.27% | LR: 0.000014
Epoch: 013 | Train loss: 0.9990 | Train acc: 50.81% | Val loss: 1.0018 | Val acc: 48.37% | LR: 0.000014
Epoch: 014 | Train loss: 0.9990 | Train acc: 50.25% | Val loss: 1.0022 | Val acc: 48.41% | LR: 0.000013
Epoch: 015 | Train loss: 0.9999 | Train acc: 50.61% | Val loss: 1.0006 | Val acc: 48.31% | LR: 0.000013
Epoch: 016 | Train loss: 1.0049 | Train acc: 50.60% | Val loss: 1.0020 | Val acc: 48.37% | LR: 0.000013
Epoch: 017 | Train loss: 0.9979 | Train acc: 50.88% | Val loss: 1.0023 | Val acc: 48.40% | LR: 0.000013
Epoch: 018 | Train loss: 1.0003 | Train acc: 50.24% | Val loss: 1.0022 | Val acc: 48.30% | LR: 0.000013
Epoch: 019 | Train loss: 1.0003 | Train acc: 50.14% | Val loss: 1.0016 | Val acc: 48.28% | LR: 0.000013
Epoch: 020 | Train loss: 0.9975 | Train acc: 50.69% | Val loss: 1.0016 | Val acc: 48.44% | LR: 0.000013
Epoch: 021 | Train loss: 0.9973 | Train acc: 50.68% | Val loss: 1.0022 | Val acc: 48.41% | LR: 0.000013
Epoch: 022 | Train loss: 0.9996 | Train acc: 50.25% | Val loss: 1.0020 | Val acc: 48.40% | LR: 0.000013
Epoch: 023 | Train loss: 1.0007 | Train acc: 49.98% | Val loss: 1.0098 | Val acc: 48.44% | LR: 0.000013
Epoch: 024 | Train loss: 1.0000 | Train acc: 50.02% | Val loss: 1.0125 | Val acc: 48.53% | LR: 0.000013
Epoch: 025 | Train loss: 1.0090 | Train acc: 50.05% | Val loss: 1.0014 | Val acc: 48.54% | LR: 0.000013
Epoch: 026 | Train loss: 1.0051 | Train acc: 50.46% | Val loss: 1.0022 | Val acc: 48.38% | LR: 0.000013
Epoch: 027 | Train loss: 0.9986 | Train acc: 50.65% | Val loss: 1.0021 | Val acc: 48.49% | LR: 0.000013
Epoch: 028 | Train loss: 0.9975 | Train acc: 50.53% | Val loss: 1.0016 | Val acc: 48.38% | LR: 0.000013
Epoch: 029 | Train loss: 0.9988 | Train acc: 50.56% | Val loss: 1.0014 | Val acc: 48.34% | LR: 0.000013
Epoch: 030 | Train loss: 1.0009 | Train acc: 50.71% | Val loss: 1.0020 | Val acc: 48.36% | LR: 0.000013
Epoch: 031 | Train loss: 0.9988 | Train acc: 50.61% | Val loss: 1.0016 | Val acc: 48.42% | LR: 0.000012
Epoch: 032 | Train loss: 0.9994 | Train acc: 50.72% | Val loss: 1.0020 | Val acc: 48.43% | LR: 0.000012
Epoch: 033 | Train loss: 0.9989 | Train acc: 50.65% | Val loss: 1.0017 | Val acc: 48.43% | LR: 0.000012
Epoch: 034 | Train loss: 1.0006 | Train acc: 50.09% | Val loss: 1.0017 | Val acc: 48.40% | LR: 0.000012
Epoch: 035 | Train loss: 1.0016 | Train acc: 49.95% | Val loss: 1.0022 | Val acc: 48.34% | LR: 0.000012
Epoch: 036 | Train loss: 0.9999 | Train acc: 50.64% | Val loss: 1.0024 | Val acc: 48.40% | LR: 0.000012
Epoch: 037 | Train loss: 0.9973 | Train acc: 50.65% | Val loss: 1.0018 | Val acc: 48.34% | LR: 0.000012
Epoch: 038 | Train loss: 0.9985 | Train acc: 50.15% | Val loss: 1.0017 | Val acc: 48.43% | LR: 0.000012
Epoch: 039 | Train loss: 1.0028 | Train acc: 49.95% | Val loss: 1.0016 | Val acc: 48.38% | LR: 0.000012
Epoch: 040 | Train loss: 0.9984 | Train acc: 50.58% | Val loss: 1.0016 | Val acc: 48.42% | LR: 0.000012
Epoch: 041 | Train loss: 1.0032 | Train acc: 50.52% | Val loss: 1.0016 | Val acc: 48.44% | LR: 0.000011
Epoch: 042 | Train loss: 0.9972 | Train acc: 50.66% | Val loss: 1.0015 | Val acc: 48.46% | LR: 0.000011
Epoch: 043 | Train loss: 1.0023 | Train acc: 50.29% | Val loss: 1.0371 | Val acc: 48.35% | LR: 0.000011
Epoch: 044 | Train loss: 1.0017 | Train acc: 50.58% | Val loss: 1.0018 | Val acc: 48.12% | LR: 0.000011
Epoch: 045 | Train loss: 0.9966 | Train acc: 50.87% | Val loss: 1.0035 | Val acc: 48.14% | LR: 0.000011
Epoch: 046 | Train loss: 1.0010 | Train acc: 50.16% | Val loss: 1.0018 | Val acc: 48.12% | LR: 0.000011
Epoch: 047 | Train loss: 0.9997 | Train acc: 50.11% | Val loss: 1.0022 | Val acc: 48.18% | LR: 0.000011
Epoch: 048 | Train loss: 1.0279 | Train acc: 50.55% | Val loss: 1.0016 | Val acc: 48.34% | LR: 0.000011
Epoch: 049 | Train loss: 0.9993 | Train acc: 50.85% | Val loss: 1.0019 | Val acc: 48.42% | LR: 0.000011

[I 2025-09-23 18:57:52,241] Trial 138 finished with value: 0.48160709738731383 and parameters: {'lr': 1.3804778768831454e-05, 'hidden_size': 73, 'dropout': 0.23701725657693853, 'weight_decay': 7.64691189996163e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 0.9945 | Train acc: 50.73% | Val loss: 1.0069 | Val acc: 45.95% | LR: 0.000611
Epoch: 001 | Train loss: 0.9838 | Train acc: 50.95% | Val loss: 1.0072 | Val acc: 46.01% | LR: 0.000611
Epoch: 002 | Train loss: 0.9808 | Train acc: 50.97% | Val loss: 1.0074 | Val acc: 46.52% | LR: 0.000611
Epoch: 003 | Train loss: 0.9891 | Train acc: 50.99% | Val loss: 1.0043 | Val acc: 47.55% | LR: 0.000610
Epoch: 004 | Train loss: 0.9993 | Train acc: 50.60% | Val loss: 1.0039 | Val acc: 48.37% | LR: 0.000609
Epoch: 005 | Train loss: 0.9914 | Train acc: 50.93% | Val loss: 0.9898 | Val acc: 50.51% | LR: 0.000609
Epoch: 006 | Train loss: 0.9906 | Train acc: 50.70% | Val loss: 0.9916 | Val acc: 50.37% | LR: 0.000608
Epoch: 007 | Train loss: 0.9842 | Train acc: 51.06% | Val loss: 1.0039 | Val acc: 49.58% | LR: 0.000607
Epoch: 008 | Train loss: 0.9850 | Train acc: 50.95% | Val loss: 1.0046 | Val acc: 49.73% | LR: 0.000606
Epoch: 009 | Train loss: 0.9902 | Train acc: 50.58% | Val loss: 1.0174 | Val acc: 49.09% | LR: 0.000604
Epoch: 010 | Train loss: 0.9819 | Train acc: 51.04% | Val loss: 1.0026 | Val acc: 50.02% | LR: 0.000603
Epoch: 011 | Train loss: 0.9702 | Train acc: 51.72% | Val loss: 1.0082 | Val acc: 49.66% | LR: 0.000602
Epoch: 012 | Train loss: 0.9765 | Train acc: 51.28% | Val loss: 1.0080 | Val acc: 49.62% | LR: 0.000600
Epoch: 013 | Train loss: 0.9819 | Train acc: 51.03% | Val loss: 1.0087 | Val acc: 49.76% | LR: 0.000598
Epoch: 014 | Train loss: 0.9795 | Train acc: 51.16% | Val loss: 1.0078 | Val acc: 49.87% | LR: 0.000596
Epoch: 015 | Train loss: 0.9776 | Train acc: 51.30% | Val loss: 0.9996 | Val acc: 50.06% | LR: 0.000594
Epoch: 016 | Train loss: 0.9746 | Train acc: 51.37% | Val loss: 1.0201 | Val acc: 49.02% | LR: 0.000592
Epoch: 017 | Train loss: 0.9794 | Train acc: 51.14% | Val loss: 1.0051 | Val acc: 49.72% | LR: 0.000590
Epoch: 018 | Train loss: 0.9851 | Train acc: 50.76% | Val loss: 1.0162 | Val acc: 49.01% | LR: 0.000587
Epoch: 019 | Train loss: 0.9889 | Train acc: 50.64% | Val loss: 1.0109 | Val acc: 49.18% | LR: 0.000585
Epoch: 020 | Train loss: 0.9900 | Train acc: 50.61% | Val loss: 0.9912 | Val acc: 50.38% | LR: 0.000582
Epoch: 021 | Train loss: 0.9838 | Train acc: 50.90% | Val loss: 0.9906 | Val acc: 50.52% | LR: 0.000579
Epoch: 022 | Train loss: 0.9808 | Train acc: 51.13% | Val loss: 1.0036 | Val acc: 49.82% | LR: 0.000576
Epoch: 023 | Train loss: 0.9910 | Train acc: 50.50% | Val loss: 1.0010 | Val acc: 50.38% | LR: 0.000573
Epoch: 024 | Train loss: 0.9902 | Train acc: 50.55% | Val loss: 0.9971 | Val acc: 50.24% | LR: 0.000570
Epoch: 025 | Train loss: 0.9830 | Train acc: 51.00% | Val loss: 1.0047 | Val acc: 49.68% | LR: 0.000567
Epoch: 026 | Train loss: 0.9781 | Train acc: 51.17% | Val loss: 0.9955 | Val acc: 50.32% | LR: 0.000564
Epoch: 027 | Train loss: 0.9808 | Train acc: 51.02% | Val loss: 1.0045 | Val acc: 49.73% | LR: 0.000560
Epoch: 028 | Train loss: 0.9698 | Train acc: 51.62% | Val loss: 0.9958 | Val acc: 50.16% | LR: 0.000557
Epoch: 029 | Train loss: 0.9817 | Train acc: 51.00% | Val loss: 1.0010 | Val acc: 50.06% | LR: 0.000553
Epoch: 030 | Train loss: 0.9811 | Train acc: 51.01% | Val loss: 1.0088 | Val acc: 49.63% | LR: 0.000549
Epoch: 031 | Train loss: 0.9762 | Train acc: 51.27% | Val loss: 0.9965 | Val acc: 50.12% | LR: 0.000545
Epoch: 032 | Train loss: 0.9833 | Train acc: 50.93% | Val loss: 1.0092 | Val acc: 49.74% | LR: 0.000541
Epoch: 033 | Train loss: 0.9882 | Train acc: 50.67% | Val loss: 1.0010 | Val acc: 49.91% | LR: 0.000537
Epoch: 034 | Train loss: 0.9786 | Train acc: 51.28% | Val loss: 1.0054 | Val acc: 49.84% | LR: 0.000533
Epoch: 035 | Train loss: 0.9814 | Train acc: 51.01% | Val loss: 1.0108 | Val acc: 49.72% | LR: 0.000528
Epoch: 036 | Train loss: 0.9801 | Train acc: 51.06% | Val loss: 0.9931 | Val acc: 50.48% | LR: 0.000524
Epoch: 037 | Train loss: 0.9753 | Train acc: 51.32% | Val loss: 1.0002 | Val acc: 50.04% | LR: 0.000520
Epoch: 038 | Train loss: 0.9767 | Train acc: 51.27% | Val loss: 0.9998 | Val acc: 50.13% | LR: 0.000515
Epoch: 039 | Train loss: 0.9781 | Train acc: 51.19% | Val loss: 1.0015 | Val acc: 50.02% | LR: 0.000510
Epoch: 040 | Train loss: 0.9782 | Train acc: 51.17% | Val loss: 0.9976 | Val acc: 50.16% | LR: 0.000505
Epoch: 041 | Train loss: 0.9816 | Train acc: 51.00% | Val loss: 1.0012 | Val acc: 50.04% | LR: 0.000501
Epoch: 042 | Train loss: 0.9763 | Train acc: 51.40% | Val loss: 1.0012 | Val acc: 50.25% | LR: 0.000496
Epoch: 043 | Train loss: 0.9803 | Train acc: 51.08% | Val loss: 1.0019 | Val acc: 49.74% | LR: 0.000491
Epoch: 044 | Train loss: 0.9768 | Train acc: 51.23% | Val loss: 1.0029 | Val acc: 49.90% | LR: 0.000485
Epoch: 045 | Train loss: 0.9885 | Train acc: 50.61% | Val loss: 1.0009 | Val acc: 50.08% | LR: 0.000480
Epoch: 046 | Train loss: 0.9811 | Train acc: 51.01% | Val loss: 0.9983 | Val acc: 50.15% | LR: 0.000475
Epoch: 047 | Train loss: 0.9762 | Train acc: 51.32% | Val loss: 1.0023 | Val acc: 49.98% | LR: 0.000470
Epoch: 048 | Train loss: 0.9788 | Train acc: 51.16% | Val loss: 1.0081 | Val acc: 49.58% | LR: 0.000464
Epoch: 049 | Train loss: 0.9760 | Train acc: 51.29% | Val loss: 0.9942 | Val acc: 50.27% | LR: 0.000459
Epoch: 050 | Train loss: 0.9765 | Train acc: 51.36% | Val loss: 1.0026 | Val acc: 49.80% | LR: 0.000453
Epoch: 051 | Train loss: 0.9778 | Train acc: 51.27% | Val loss: 1.0103 | Val acc: 49.82% | LR: 0.000447
Epoch: 052 | Train loss: 0.9795 | Train acc: 51.52% | Val loss: 0.9856 | Val acc: 50.87% | LR: 0.000442
Epoch: 053 | Train loss: 0.9788 | Train acc: 51.25% | Val loss: 0.9865 | Val acc: 50.88% | LR: 0.000436
Epoch: 054 | Train loss: 0.9797 | Train acc: 51.04% | Val loss: 0.9670 | Val acc: 51.84% | LR: 0.000430
Epoch: 055 | Train loss: 0.9813 | Train acc: 51.04% | Val loss: 0.9565 | Val acc: 52.38% | LR: 0.000424
Epoch: 056 | Train loss: 0.9790 | Train acc: 51.19% | Val loss: 0.9574 | Val acc: 52.84% | LR: 0.000418
Epoch: 057 | Train loss: 0.9780 | Train acc: 51.12% | Val loss: 0.9514 | Val acc: 52.98% | LR: 0.000412
Epoch: 058 | Train loss: 0.9743 | Train acc: 51.42% | Val loss: 0.9572 | Val acc: 52.47% | LR: 0.000406
Epoch: 059 | Train loss: 0.9807 | Train acc: 51.14% | Val loss: 0.9658 | Val acc: 52.32% | LR: 0.000400
Epoch: 060 | Train loss: 0.9755 | Train acc: 51.33% | Val loss: 0.9847 | Val acc: 51.02% | LR: 0.000394
Epoch: 061 | Train loss: 0.9763 | Train acc: 51.24% | Val loss: 0.9623 | Val acc: 52.22% | LR: 0.000388
Epoch: 062 | Train loss: 0.9847 | Train acc: 50.79% | Val loss: 0.9568 | Val acc: 52.64% | LR: 0.000382
Epoch: 063 | Train loss: 0.9771 | Train acc: 51.22% | Val loss: 0.9618 | Val acc: 52.23% | LR: 0.000376
Epoch: 064 | Train loss: 0.9849 | Train acc: 50.77% | Val loss: 0.9576 | Val acc: 52.11% | LR: 0.000369
Epoch: 065 | Train loss: 0.9826 | Train acc: 50.89% | Val loss: 0.9518 | Val acc: 52.56% | LR: 0.000363
Epoch: 066 | Train loss: 0.9799 | Train acc: 51.02% | Val loss: 0.9504 | Val acc: 52.82% | LR: 0.000357
Epoch: 067 | Train loss: 0.9829 | Train acc: 50.87% | Val loss: 0.9586 | Val acc: 52.42% | LR: 0.000351
Epoch: 068 | Train loss: 0.9741 | Train acc: 51.65% | Val loss: 0.9874 | Val acc: 50.78% | LR: 0.000344
Epoch: 069 | Train loss: 0.9808 | Train acc: 51.01% | Val loss: 1.0112 | Val acc: 49.70% | LR: 0.000338
Epoch: 070 | Train loss: 0.9849 | Train acc: 50.81% | Val loss: 1.0406 | Val acc: 47.99% | LR: 0.000332
Epoch: 071 | Train loss: 0.9679 | Train acc: 51.77% | Val loss: 1.0497 | Val acc: 47.83% | LR: 0.000325
Epoch: 072 | Train loss: 0.9862 | Train acc: 50.73% | Val loss: 1.0350 | Val acc: 48.15% | LR: 0.000319
Epoch: 073 | Train loss: 0.9793 | Train acc: 51.20% | Val loss: 1.0507 | Val acc: 47.40% | LR: 0.000312
Epoch: 074 | Train loss: 0.9793 | Train acc: 51.11% | Val loss: 1.0506 | Val acc: 47.38% | LR: 0.000306
Epoch: 075 | Train loss: 0.9747 | Train acc: 51.30% | Val loss: 1.0595 | Val acc: 46.87% | LR: 0.000300
Epoch: 076 | Train loss: 0.9772 | Train acc: 51.21% | Val loss: 1.0606 | Val acc: 46.85% | LR: 0.000293
Epoch: 077 | Train loss: 0.9879 | Train acc: 50.80% | Val loss: 1.0751 | Val acc: 46.04% | LR: 0.000287
Epoch: 078 | Train loss: 0.9823 | Train acc: 51.09% | Val loss: 1.0777 | Val acc: 45.66% | LR: 0.000281
Epoch: 079 | Train loss: 0.9913 | Train acc: 50.48% | Val loss: 1.0726 | Val acc: 45.89% | LR: 0.000274
Epoch: 080 | Train loss: 0.9878 | Train acc: 50.65% | Val loss: 1.0768 | Val acc: 45.77% | LR: 0.000268
Epoch: 081 | Train loss: 0.9816 | Train acc: 50.99% | Val loss: 1.0718 | Val acc: 46.11% | LR: 0.000261
Epoch: 082 | Train loss: 0.9812 | Train acc: 50.98% | Val loss: 1.0738 | Val acc: 45.83% | LR: 0.000255
Epoch: 083 | Train loss: 0.9807 | Train acc: 51.01% | Val loss: 1.0782 | Val acc: 45.60% | LR: 0.000249
Epoch: 084 | Train loss: 0.9852 | Train acc: 50.75% | Val loss: 1.0744 | Val acc: 45.77% | LR: 0.000243
Epoch: 085 | Train loss: 0.9858 | Train acc: 50.72% | Val loss: 1.0798 | Val acc: 45.70% | LR: 0.000236
Epoch: 086 | Train loss: 0.9866 | Train acc: 50.65% | Val loss: 1.0720 | Val acc: 45.93% | LR: 0.000230
Epoch: 087 | Train loss: 0.9869 | Train acc: 50.63% | Val loss: 1.0631 | Val acc: 46.53% | LR: 0.000224
Epoch: 088 | Train loss: 0.9816 | Train acc: 50.96% | Val loss: 1.0616 | Val acc: 46.71% | LR: 0.000218
Epoch: 089 | Train loss: 0.9798 | Train acc: 51.06% | Val loss: 1.0738 | Val acc: 45.98% | LR: 0.000212
Epoch: 090 | Train loss: 0.9770 | Train acc: 51.21% | Val loss: 1.0658 | Val acc: 46.45% | LR: 0.000206
Epoch: 091 | Train loss: 0.9765 | Train acc: 51.24% | Val loss: 1.0636 | Val acc: 46.47% | LR: 0.000200
Epoch: 092 | Train loss: 0.9822 | Train acc: 50.89% | Val loss: 1.0656 | Val acc: 46.45% | LR: 0.000194
Epoch: 093 | Train loss: 0.9748 | Train acc: 51.32% | Val loss: 1.0677 | Val acc: 46.33% | LR: 0.000188
Epoch: 094 | Train loss: 0.9844 | Train acc: 50.78% | Val loss: 1.0695 | Val acc: 46.25% | LR: 0.000182
Epoch: 095 | Train loss: 0.9832 | Train acc: 50.82% | Val loss: 1.0702 | Val acc: 46.35% | LR: 0.000176
Epoch: 096 | Train loss: 0.9729 | Train acc: 51.43% | Val loss: 1.0818 | Val acc: 45.74% | LR: 0.000170
Epoch: 097 | Train loss: 0.9859 | Train acc: 50.70% | Val loss: 1.0777 | Val acc: 45.74% | LR: 0.000165
Epoch: 098 | Train loss: 0.9840 | Train acc: 50.80% | Val loss: 1.0769 | Val acc: 45.77% | LR: 0.000159
Epoch: 099 | Train loss: 0.9758 | Train acc: 51.24% | Val loss: 1.0779 | Val acc: 45.87% | LR: 0.000154
Epoch: 100 | Train loss: 0.9711 | Train acc: 51.52% | Val loss: 1.0766 | Val acc: 45.93% | LR: 0.000148
Epoch: 101 | Train loss: 0.9823 | Train acc: 50.89% | Val loss: 1.0747 | Val acc: 45.95% | LR: 0.000143
Epoch: 102 | Train loss: 0.9731 | Train acc: 51.41% | Val loss: 1.0749 | Val acc: 45.93% | LR: 0.000137
Epoch: 103 | Train loss: 0.9824 | Train acc: 50.89% | Val loss: 1.0778 | Val acc: 45.81% | LR: 0.000132
Epoch: 104 | Train loss: 0.9892 | Train acc: 50.53% | Val loss: 1.0804 | Val acc: 45.76% | LR: 0.000127
Epoch: 105 | Train loss: 0.9756 | Train acc: 51.24% | Val loss: 1.0764 | Val acc: 45.95% | LR: 0.000122
Epoch: 106 | Train loss: 0.9822 | Train acc: 50.89% | Val loss: 1.0746 | Val acc: 46.09% | LR: 0.000117

[I 2025-09-23 18:59:25,009] Trial 139 finished with value: 0.45989570021629333 and parameters: {'lr': 0.0006111279538486456, 'hidden_size': 82, 'dropout': 0.22419985303792966, 'weight_decay': 3.043475544251783e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0035 | Train acc: 48.82% | Val loss: 0.9973 | Val acc: 53.42% | LR: 0.000012
Epoch: 001 | Train loss: 1.0021 | Train acc: 49.20% | Val loss: 0.9973 | Val acc: 53.48% | LR: 0.000012
Epoch: 002 | Train loss: 1.0011 | Train acc: 49.44% | Val loss: 0.9972 | Val acc: 53.58% | LR: 0.000012
Epoch: 003 | Train loss: 1.0025 | Train acc: 48.92% | Val loss: 0.9972 | Val acc: 53.72% | LR: 0.000012
Epoch: 004 | Train loss: 1.0022 | Train acc: 49.07% | Val loss: 0.9972 | Val acc: 53.77% | LR: 0.000012
Epoch: 005 | Train loss: 1.0022 | Train acc: 49.19% | Val loss: 0.9973 | Val acc: 53.79% | LR: 0.000012
Epoch: 006 | Train loss: 1.0020 | Train acc: 49.34% | Val loss: 0.9972 | Val acc: 53.95% | LR: 0.000012
Epoch: 007 | Train loss: 1.0014 | Train acc: 49.52% | Val loss: 0.9972 | Val acc: 53.99% | LR: 0.000012
Epoch: 008 | Train loss: 1.0009 | Train acc: 49.69% | Val loss: 0.9972 | Val acc: 54.05% | LR: 0.000012
Epoch: 009 | Train loss: 1.0005 | Train acc: 49.87% | Val loss: 0.9972 | Val acc: 54.05% | LR: 0.000012
Epoch: 010 | Train loss: 1.0013 | Train acc: 49.55% | Val loss: 0.9971 | Val acc: 54.09% | LR: 0.000012
Epoch: 011 | Train loss: 1.0006 | Train acc: 49.73% | Val loss: 0.9971 | Val acc: 54.11% | LR: 0.000012
Epoch: 012 | Train loss: 1.0000 | Train acc: 50.10% | Val loss: 0.9971 | Val acc: 54.09% | LR: 0.000011
Epoch: 013 | Train loss: 1.0015 | Train acc: 49.30% | Val loss: 0.9971 | Val acc: 54.02% | LR: 0.000011
Epoch: 014 | Train loss: 1.0009 | Train acc: 49.59% | Val loss: 0.9970 | Val acc: 54.07% | LR: 0.000011
Epoch: 015 | Train loss: 1.0002 | Train acc: 49.86% | Val loss: 0.9970 | Val acc: 54.15% | LR: 0.000011
Epoch: 016 | Train loss: 0.9998 | Train acc: 50.22% | Val loss: 0.9969 | Val acc: 54.27% | LR: 0.000011
Epoch: 017 | Train loss: 1.0003 | Train acc: 49.79% | Val loss: 0.9967 | Val acc: 54.11% | LR: 0.000011
Epoch: 018 | Train loss: 1.0003 | Train acc: 49.62% | Val loss: 0.9967 | Val acc: 54.13% | LR: 0.000011
Epoch: 019 | Train loss: 0.9999 | Train acc: 49.96% | Val loss: 0.9966 | Val acc: 54.13% | LR: 0.000011
Epoch: 020 | Train loss: 1.0004 | Train acc: 49.50% | Val loss: 0.9966 | Val acc: 54.06% | LR: 0.000011
Epoch: 021 | Train loss: 1.0001 | Train acc: 49.67% | Val loss: 0.9966 | Val acc: 54.12% | LR: 0.000011
Epoch: 022 | Train loss: 1.0002 | Train acc: 49.68% | Val loss: 0.9965 | Val acc: 54.04% | LR: 0.000011
Epoch: 023 | Train loss: 0.9997 | Train acc: 49.94% | Val loss: 0.9964 | Val acc: 54.11% | LR: 0.000011
Epoch: 024 | Train loss: 0.9997 | Train acc: 50.11% | Val loss: 0.9964 | Val acc: 53.97% | LR: 0.000011
Epoch: 025 | Train loss: 0.9995 | Train acc: 50.16% | Val loss: 0.9964 | Val acc: 54.05% | LR: 0.000011
Epoch: 026 | Train loss: 0.9997 | Train acc: 49.89% | Val loss: 0.9964 | Val acc: 54.08% | LR: 0.000011
Epoch: 027 | Train loss: 0.9997 | Train acc: 50.11% | Val loss: 0.9964 | Val acc: 53.90% | LR: 0.000011
Epoch: 028 | Train loss: 0.9991 | Train acc: 50.31% | Val loss: 0.9965 | Val acc: 54.16% | LR: 0.000011
Epoch: 029 | Train loss: 0.9995 | Train acc: 50.11% | Val loss: 0.9964 | Val acc: 54.16% | LR: 0.000011
Epoch: 030 | Train loss: 0.9990 | Train acc: 50.75% | Val loss: 0.9964 | Val acc: 53.96% | LR: 0.000011
Epoch: 031 | Train loss: 0.9988 | Train acc: 50.59% | Val loss: 0.9964 | Val acc: 53.70% | LR: 0.000011
Epoch: 032 | Train loss: 0.9995 | Train acc: 50.13% | Val loss: 0.9963 | Val acc: 53.70% | LR: 0.000010
Epoch: 033 | Train loss: 0.9990 | Train acc: 50.54% | Val loss: 0.9962 | Val acc: 53.54% | LR: 0.000010
Epoch: 034 | Train loss: 0.9989 | Train acc: 50.64% | Val loss: 0.9962 | Val acc: 53.51% | LR: 0.000010
Epoch: 035 | Train loss: 0.9990 | Train acc: 50.92% | Val loss: 0.9962 | Val acc: 53.47% | LR: 0.000010
Epoch: 036 | Train loss: 0.9989 | Train acc: 50.83% | Val loss: 0.9962 | Val acc: 53.57% | LR: 0.000010
Epoch: 037 | Train loss: 0.9990 | Train acc: 50.67% | Val loss: 0.9960 | Val acc: 53.46% | LR: 0.000010
Epoch: 038 | Train loss: 0.9988 | Train acc: 50.58% | Val loss: 0.9960 | Val acc: 53.78% | LR: 0.000010
Epoch: 039 | Train loss: 0.9987 | Train acc: 50.77% | Val loss: 0.9959 | Val acc: 53.86% | LR: 0.000010
Epoch: 040 | Train loss: 0.9979 | Train acc: 51.30% | Val loss: 0.9960 | Val acc: 53.78% | LR: 0.000010
Epoch: 041 | Train loss: 0.9983 | Train acc: 51.09% | Val loss: 0.9960 | Val acc: 53.63% | LR: 0.000010
Epoch: 042 | Train loss: 0.9986 | Train acc: 50.36% | Val loss: 0.9960 | Val acc: 53.59% | LR: 0.000010
Epoch: 043 | Train loss: 0.9989 | Train acc: 50.47% | Val loss: 0.9960 | Val acc: 53.49% | LR: 0.000010
Epoch: 044 | Train loss: 0.9985 | Train acc: 50.80% | Val loss: 0.9960 | Val acc: 53.35% | LR: 0.000009
Epoch: 045 | Train loss: 0.9980 | Train acc: 51.06% | Val loss: 0.9960 | Val acc: 53.15% | LR: 0.000009
Epoch: 046 | Train loss: 0.9977 | Train acc: 51.16% | Val loss: 0.9961 | Val acc: 53.07% | LR: 0.000009
Epoch: 047 | Train loss: 0.9980 | Train acc: 51.15% | Val loss: 0.9960 | Val acc: 53.15% | LR: 0.000009
Epoch: 048 | Train loss: 0.9978 | Train acc: 51.09% | Val loss: 0.9960 | Val acc: 53.17% | LR: 0.000009
Epoch: 049 | Train loss: 0.9982 | Train acc: 50.73% | Val loss: 0.9960 | Val acc: 53.14% | LR: 0.000009
Epoch: 050 | Train loss: 0.9981 | Train acc: 50.65% | Val loss: 0.9960 | Val acc: 53.18% | LR: 0.000009
Epoch: 051 | Train loss: 0.9983 | Train acc: 50.57% | Val loss: 0.9959 | Val acc: 53.04% | LR: 0.000009
Epoch: 052 | Train loss: 0.9977 | Train acc: 50.91% | Val loss: 0.9959 | Val acc: 53.02% | LR: 0.000009
Epoch: 053 | Train loss: 0.9974 | Train acc: 50.82% | Val loss: 0.9959 | Val acc: 53.00% | LR: 0.000009
Epoch: 054 | Train loss: 0.9972 | Train acc: 51.09% | Val loss: 0.9959 | Val acc: 53.22% | LR: 0.000009
Epoch: 055 | Train loss: 0.9975 | Train acc: 50.84% | Val loss: 0.9958 | Val acc: 53.22% | LR: 0.000008
Epoch: 056 | Train loss: 0.9981 | Train acc: 50.67% | Val loss: 0.9958 | Val acc: 53.36% | LR: 0.000008
Epoch: 057 | Train loss: 0.9982 | Train acc: 50.66% | Val loss: 0.9958 | Val acc: 53.36% | LR: 0.000008
Epoch: 058 | Train loss: 0.9972 | Train acc: 51.00% | Val loss: 0.9958 | Val acc: 53.39% | LR: 0.000008
Epoch: 059 | Train loss: 0.9990 | Train acc: 50.39% | Val loss: 0.9958 | Val acc: 53.43% | LR: 0.000008
Epoch: 060 | Train loss: 0.9972 | Train acc: 50.74% | Val loss: 0.9957 | Val acc: 53.37% | LR: 0.000008
Epoch: 061 | Train loss: 0.9978 | Train acc: 50.55% | Val loss: 0.9957 | Val acc: 53.31% | LR: 0.000008
Epoch: 062 | Train loss: 0.9964 | Train acc: 51.19% | Val loss: 0.9957 | Val acc: 53.29% | LR: 0.000008
Epoch: 063 | Train loss: 0.9980 | Train acc: 50.58% | Val loss: 0.9957 | Val acc: 53.35% | LR: 0.000008
Epoch: 064 | Train loss: 0.9975 | Train acc: 50.86% | Val loss: 0.9958 | Val acc: 53.24% | LR: 0.000007
Epoch: 065 | Train loss: 0.9960 | Train acc: 51.24% | Val loss: 0.9957 | Val acc: 53.28% | LR: 0.000007

[I 2025-09-23 19:00:19,297] Trial 140 finished with value: 0.5316772103309632 and parameters: {'lr': 1.167810334831914e-05, 'hidden_size': 68, 'dropout': 0.20512433474745403, 'weight_decay': 2.439525558345315e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0005 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.05% | LR: 0.000010
Epoch: 001 | Train loss: 1.0006 | Train acc: 49.57% | Val loss: 0.9916 | Val acc: 54.05% | LR: 0.000010
Epoch: 002 | Train loss: 0.9996 | Train acc: 50.36% | Val loss: 0.9916 | Val acc: 54.11% | LR: 0.000010
Epoch: 003 | Train loss: 0.9994 | Train acc: 50.46% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000010
Epoch: 004 | Train loss: 1.0000 | Train acc: 50.16% | Val loss: 0.9917 | Val acc: 54.11% | LR: 0.000010
Epoch: 005 | Train loss: 0.9982 | Train acc: 50.88% | Val loss: 0.9917 | Val acc: 54.11% | LR: 0.000010
Epoch: 006 | Train loss: 0.9991 | Train acc: 50.52% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000010
Epoch: 007 | Train loss: 1.0000 | Train acc: 49.98% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000010
Epoch: 008 | Train loss: 1.0003 | Train acc: 49.72% | Val loss: 0.9919 | Val acc: 54.17% | LR: 0.000010
Epoch: 009 | Train loss: 0.9985 | Train acc: 50.61% | Val loss: 0.9919 | Val acc: 54.20% | LR: 0.000010
Epoch: 010 | Train loss: 0.9981 | Train acc: 50.78% | Val loss: 0.9919 | Val acc: 54.24% | LR: 0.000010
Epoch: 011 | Train loss: 0.9979 | Train acc: 50.87% | Val loss: 0.9919 | Val acc: 54.26% | LR: 0.000010
Epoch: 012 | Train loss: 0.9982 | Train acc: 50.69% | Val loss: 0.9918 | Val acc: 54.24% | LR: 0.000010
Epoch: 013 | Train loss: 0.9983 | Train acc: 50.43% | Val loss: 0.9917 | Val acc: 54.32% | LR: 0.000010
Epoch: 014 | Train loss: 0.9986 | Train acc: 50.43% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000010
Epoch: 015 | Train loss: 0.9989 | Train acc: 50.16% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000010
Epoch: 016 | Train loss: 0.9984 | Train acc: 50.60% | Val loss: 0.9919 | Val acc: 54.28% | LR: 0.000010
Epoch: 017 | Train loss: 0.9980 | Train acc: 50.51% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000010
Epoch: 018 | Train loss: 0.9983 | Train acc: 50.25% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000010
Epoch: 019 | Train loss: 0.9985 | Train acc: 50.34% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000010
Epoch: 020 | Train loss: 0.9970 | Train acc: 51.13% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000010
Epoch: 021 | Train loss: 0.9975 | Train acc: 50.60% | Val loss: 0.9917 | Val acc: 54.26% | LR: 0.000010
Epoch: 022 | Train loss: 0.9976 | Train acc: 50.78% | Val loss: 0.9917 | Val acc: 54.28% | LR: 0.000010
Epoch: 023 | Train loss: 0.9980 | Train acc: 50.25% | Val loss: 0.9916 | Val acc: 54.30% | LR: 0.000010
Epoch: 024 | Train loss: 0.9977 | Train acc: 50.42% | Val loss: 0.9917 | Val acc: 54.32% | LR: 0.000010
Epoch: 025 | Train loss: 0.9982 | Train acc: 50.03% | Val loss: 0.9916 | Val acc: 54.34% | LR: 0.000010
Epoch: 026 | Train loss: 1.0019 | Train acc: 50.33% | Val loss: 0.9916 | Val acc: 54.34% | LR: 0.000010
Epoch: 027 | Train loss: 1.0576 | Train acc: 50.50% | Val loss: 0.9916 | Val acc: 54.34% | LR: 0.000010
Epoch: 028 | Train loss: 0.9999 | Train acc: 50.78% | Val loss: 0.9915 | Val acc: 54.34% | LR: 0.000010
Epoch: 029 | Train loss: 1.0158 | Train acc: 50.93% | Val loss: 0.9916 | Val acc: 54.34% | LR: 0.000009
Epoch: 030 | Train loss: 0.9975 | Train acc: 50.27% | Val loss: 0.9916 | Val acc: 54.34% | LR: 0.000009
Epoch: 031 | Train loss: 1.0328 | Train acc: 50.35% | Val loss: 0.9916 | Val acc: 54.36% | LR: 0.000009
Epoch: 032 | Train loss: 0.9947 | Train acc: 50.88% | Val loss: 0.9915 | Val acc: 54.36% | LR: 0.000009
Epoch: 033 | Train loss: 1.0072 | Train acc: 50.02% | Val loss: 0.9915 | Val acc: 54.32% | LR: 0.000009
Epoch: 034 | Train loss: 1.0041 | Train acc: 50.68% | Val loss: 0.9915 | Val acc: 54.34% | LR: 0.000009
Epoch: 035 | Train loss: 1.1484 | Train acc: 50.04% | Val loss: 0.9915 | Val acc: 54.34% | LR: 0.000009
Epoch: 036 | Train loss: 1.0010 | Train acc: 50.54% | Val loss: 0.9915 | Val acc: 54.34% | LR: 0.000009
Epoch: 037 | Train loss: 0.9959 | Train acc: 50.61% | Val loss: 0.9915 | Val acc: 54.38% | LR: 0.000009
Epoch: 038 | Train loss: 1.0062 | Train acc: 50.36% | Val loss: 0.9915 | Val acc: 54.38% | LR: 0.000009
Epoch: 039 | Train loss: 1.0060 | Train acc: 50.68% | Val loss: 0.9915 | Val acc: 54.38% | LR: 0.000009
Epoch: 040 | Train loss: 1.0068 | Train acc: 50.52% | Val loss: 0.9913 | Val acc: 54.42% | LR: 0.000009
Epoch: 041 | Train loss: 1.0044 | Train acc: 50.82% | Val loss: 0.9914 | Val acc: 54.42% | LR: 0.000009
Epoch: 042 | Train loss: 1.0078 | Train acc: 50.26% | Val loss: 0.9915 | Val acc: 54.42% | LR: 0.000009
Epoch: 043 | Train loss: 1.0080 | Train acc: 50.57% | Val loss: 0.9915 | Val acc: 54.44% | LR: 0.000008
Epoch: 044 | Train loss: 1.0290 | Train acc: 50.12% | Val loss: 0.9915 | Val acc: 54.44% | LR: 0.000008
Epoch: 045 | Train loss: 1.0182 | Train acc: 50.49% | Val loss: 0.9915 | Val acc: 54.44% | LR: 0.000008
Epoch: 046 | Train loss: 0.9953 | Train acc: 50.80% | Val loss: 0.9915 | Val acc: 54.44% | LR: 0.000008
Epoch: 047 | Train loss: 0.9958 | Train acc: 50.02% | Val loss: 0.9915 | Val acc: 54.44% | LR: 0.000008
Epoch: 048 | Train loss: 1.0090 | Train acc: 50.31% | Val loss: 0.9915 | Val acc: 54.44% | LR: 0.000008
Epoch: 049 | Train loss: 0.9985 | Train acc: 50.40% | Val loss: 0.9915 | Val acc: 54.42% | LR: 0.000008
Epoch: 050 | Train loss: 0.9970 | Train acc: 50.08% | Val loss: 0.9915 | Val acc: 54.40% | LR: 0.000008
Epoch: 051 | Train loss: 0.9948 | Train acc: 50.30% | Val loss: 0.9915 | Val acc: 54.38% | LR: 0.000008
Epoch: 052 | Train loss: 0.9992 | Train acc: 50.33% | Val loss: 0.9916 | Val acc: 54.36% | LR: 0.000008
Epoch: 053 | Train loss: 0.9954 | Train acc: 50.12% | Val loss: 0.9913 | Val acc: 54.38% | LR: 0.000008
Epoch: 054 | Train loss: 1.0019 | Train acc: 50.60% | Val loss: 0.9915 | Val acc: 54.38% | LR: 0.000008
Epoch: 055 | Train loss: 1.0049 | Train acc: 50.53% | Val loss: 0.9917 | Val acc: 54.38% | LR: 0.000007
Epoch: 056 | Train loss: 0.9945 | Train acc: 50.56% | Val loss: 0.9916 | Val acc: 54.32% | LR: 0.000007
Epoch: 057 | Train loss: 1.0035 | Train acc: 50.13% | Val loss: 0.9915 | Val acc: 54.36% | LR: 0.000007
Epoch: 058 | Train loss: 0.9993 | Train acc: 50.27% | Val loss: 0.9916 | Val acc: 54.32% | LR: 0.000007
Epoch: 059 | Train loss: 0.9949 | Train acc: 50.87% | Val loss: 0.9928 | Val acc: 54.34% | LR: 0.000007
Epoch: 060 | Train loss: 0.9928 | Train acc: 50.54% | Val loss: 0.9915 | Val acc: 54.32% | LR: 0.000007
Epoch: 061 | Train loss: 0.9936 | Train acc: 50.18% | Val loss: 0.9915 | Val acc: 54.36% | LR: 0.000007
Epoch: 062 | Train loss: 0.9945 | Train acc: 50.33% | Val loss: 0.9915 | Val acc: 54.40% | LR: 0.000007
Epoch: 063 | Train loss: 1.0004 | Train acc: 50.10% | Val loss: 0.9915 | Val acc: 54.40% | LR: 0.000007
Epoch: 064 | Train loss: 0.9942 | Train acc: 50.62% | Val loss: 0.9915 | Val acc: 54.42% | LR: 0.000007
Epoch: 065 | Train loss: 0.9949 | Train acc: 50.47% | Val loss: 0.9916 | Val acc: 54.42% | LR: 0.000007
Epoch: 066 | Train loss: 0.9990 | Train acc: 49.95% | Val loss: 0.9914 | Val acc: 54.42% | LR: 0.000006
Epoch: 067 | Train loss: 0.9968 | Train acc: 51.10% | Val loss: 0.9915 | Val acc: 54.38% | LR: 0.000006
Epoch: 068 | Train loss: 0.9961 | Train acc: 50.61% | Val loss: 0.9916 | Val acc: 54.38% | LR: 0.000006
Epoch: 069 | Train loss: 0.9956 | Train acc: 50.23% | Val loss: 0.9915 | Val acc: 54.40% | LR: 0.000006
Epoch: 070 | Train loss: 0.9957 | Train acc: 50.83% | Val loss: 0.9915 | Val acc: 54.38% | LR: 0.000006
Epoch: 071 | Train loss: 1.0137 | Train acc: 50.51% | Val loss: 0.9913 | Val acc: 54.44% | LR: 0.000006
Epoch: 072 | Train loss: 0.9918 | Train acc: 50.38% | Val loss: 0.9912 | Val acc: 54.42% | LR: 0.000006
Epoch: 073 | Train loss: 0.9971 | Train acc: 49.63% | Val loss: 0.9914 | Val acc: 54.40% | LR: 0.000006
Epoch: 074 | Train loss: 0.9924 | Train acc: 51.05% | Val loss: 0.9914 | Val acc: 54.46% | LR: 0.000006
Epoch: 075 | Train loss: 0.9918 | Train acc: 50.87% | Val loss: 0.9916 | Val acc: 54.38% | LR: 0.000006
Epoch: 076 | Train loss: 0.9990 | Train acc: 50.32% | Val loss: 0.9916 | Val acc: 54.34% | LR: 0.000005
Epoch: 077 | Train loss: 1.0045 | Train acc: 50.03% | Val loss: 0.9916 | Val acc: 54.40% | LR: 0.000005
Epoch: 078 | Train loss: 0.9990 | Train acc: 50.36% | Val loss: 0.9918 | Val acc: 54.40% | LR: 0.000005
Epoch: 079 | Train loss: 0.9983 | Train acc: 50.47% | Val loss: 0.9914 | Val acc: 54.36% | LR: 0.000005
Epoch: 080 | Train loss: 0.9952 | Train acc: 50.74% | Val loss: 0.9912 | Val acc: 54.40% | LR: 0.000005
Epoch: 081 | Train loss: 0.9941 | Train acc: 50.50% | Val loss: 0.9914 | Val acc: 54.38% | LR: 0.000005
Epoch: 082 | Train loss: 0.9931 | Train acc: 51.22% | Val loss: 0.9913 | Val acc: 54.40% | LR: 0.000005
Epoch: 083 | Train loss: 0.9968 | Train acc: 49.87% | Val loss: 0.9913 | Val acc: 54.40% | LR: 0.000005
Epoch: 084 | Train loss: 0.9951 | Train acc: 50.42% | Val loss: 0.9913 | Val acc: 54.40% | LR: 0.000005
Epoch: 085 | Train loss: 0.9955 | Train acc: 50.05% | Val loss: 0.9914 | Val acc: 54.40% | LR: 0.000005
Epoch: 086 | Train loss: 0.9950 | Train acc: 50.54% | Val loss: 0.9918 | Val acc: 54.38% | LR: 0.000005
Epoch: 087 | Train loss: 0.9943 | Train acc: 50.48% | Val loss: 0.9914 | Val acc: 54.40% | LR: 0.000004
Epoch: 088 | Train loss: 0.9977 | Train acc: 50.49% | Val loss: 0.9914 | Val acc: 54.38% | LR: 0.000004
Epoch: 089 | Train loss: 0.9950 | Train acc: 50.28% | Val loss: 0.9915 | Val acc: 54.38% | LR: 0.000004
Epoch: 090 | Train loss: 0.9965 | Train acc: 50.37% | Val loss: 0.9915 | Val acc: 54.36% | LR: 0.000004
Epoch: 091 | Train loss: 0.9926 | Train acc: 50.65% | Val loss: 0.9913 | Val acc: 54.42% | LR: 0.000004
Epoch: 092 | Train loss: 0.9940 | Train acc: 50.02% | Val loss: 0.9915 | Val acc: 54.42% | LR: 0.000004
Epoch: 093 | Train loss: 0.9945 | Train acc: 50.54% | Val loss: 0.9997 | Val acc: 54.42% | LR: 0.000004
Epoch: 094 | Train loss: 0.9941 | Train acc: 50.91% | Val loss: 0.9914 | Val acc: 54.46% | LR: 0.000004
Epoch: 095 | Train loss: 0.9960 | Train acc: 50.40% | Val loss: 0.9913 | Val acc: 54.44% | LR: 0.000004
Epoch: 096 | Train loss: 0.9925 | Train acc: 50.63% | Val loss: 0.9915 | Val acc: 54.40% | LR: 0.000004
Epoch: 097 | Train loss: 0.9957 | Train acc: 50.04% | Val loss: 0.9915 | Val acc: 54.42% | LR: 0.000004
Epoch: 098 | Train loss: 0.9965 | Train acc: 50.69% | Val loss: 0.9914 | Val acc: 54.36% | LR: 0.000003
Epoch: 099 | Train loss: 0.9972 | Train acc: 50.45% | Val loss: 0.9915 | Val acc: 54.36% | LR: 0.000003
Epoch: 100 | Train loss: 0.9949 | Train acc: 50.16% | Val loss: 0.9915 | Val acc: 54.36% | LR: 0.000003
Epoch: 101 | Train loss: 0.9934 | Train acc: 50.37% | Val loss: 0.9915 | Val acc: 54.36% | LR: 0.000003
Epoch: 102 | Train loss: 0.9926 | Train acc: 50.71% | Val loss: 0.9915 | Val acc: 54.36% | LR: 0.000003
Epoch: 103 | Train loss: 0.9936 | Train acc: 50.63% | Val loss: 0.9914 | Val acc: 54.30% | LR: 0.000003
Epoch: 104 | Train loss: 0.9976 | Train acc: 50.18% | Val loss: 0.9915 | Val acc: 54.26% | LR: 0.000003
Epoch: 105 | Train loss: 0.9918 | Train acc: 50.77% | Val loss: 0.9935 | Val acc: 54.26% | LR: 0.000003
Epoch: 106 | Train loss: 0.9940 | Train acc: 50.58% | Val loss: 0.9915 | Val acc: 54.26% | LR: 0.000003
Epoch: 107 | Train loss: 0.9949 | Train acc: 50.68% | Val loss: 0.9915 | Val acc: 54.26% | LR: 0.000003
Epoch: 108 | Train loss: 0.9976 | Train acc: 49.88% | Val loss: 0.9915 | Val acc: 54.30% | LR: 0.000003
Epoch: 109 | Train loss: 0.9955 | Train acc: 50.64% | Val loss: 0.9915 | Val acc: 54.30% | LR: 0.000003
Epoch: 110 | Train loss: 0.9959 | Train acc: 50.32% | Val loss: 0.9914 | Val acc: 54.24% | LR: 0.000002
Epoch: 111 | Train loss: 0.9926 | Train acc: 50.55% | Val loss: 0.9915 | Val acc: 54.30% | LR: 0.000002
Epoch: 112 | Train loss: 1.0008 | Train acc: 50.12% | Val loss: 0.9915 | Val acc: 54.26% | LR: 0.000002
Epoch: 113 | Train loss: 0.9932 | Train acc: 50.11% | Val loss: 0.9914 | Val acc: 54.27% | LR: 0.000002
Epoch: 114 | Train loss: 0.9994 | Train acc: 49.83% | Val loss: 0.9915 | Val acc: 54.26% | LR: 0.000002
Epoch: 115 | Train loss: 0.9955 | Train acc: 50.73% | Val loss: 0.9914 | Val acc: 54.28% | LR: 0.000002
Epoch: 116 | Train loss: 0.9925 | Train acc: 50.87% | Val loss: 0.9915 | Val acc: 54.24% | LR: 0.000002
Epoch: 117 | Train loss: 0.9949 | Train acc: 50.35% | Val loss: 0.9915 | Val acc: 54.26% | LR: 0.000002
Epoch: 118 | Train loss: 0.9946 | Train acc: 50.28% | Val loss: 0.9915 | Val acc: 54.26% | LR: 0.000002
Epoch: 119 | Train loss: 0.9974 | Train acc: 50.09% | Val loss: 0.9915 | Val acc: 54.24% | LR: 0.000002
Epoch: 120 | Train loss: 0.9963 | Train acc: 50.18% | Val loss: 0.9915 | Val acc: 54.24% | LR: 0.000002
Epoch: 121 | Train loss: 0.9928 | Train acc: 50.67% | Val loss: 0.9915 | Val acc: 54.24% | LR: 0.000002
Epoch: 122 | Train loss: 0.9943 | Train acc: 50.54% | Val loss: 0.9915 | Val acc: 54.26% | LR: 0.000002
Epoch: 123 | Train loss: 0.9948 | Train acc: 50.58% | Val loss: 0.9915 | Val acc: 54.24% | LR: 0.000002

[I 2025-09-23 19:01:59,507] Trial 141 finished with value: 0.5423551797866821 and parameters: {'lr': 1.0336559003325748e-05, 'hidden_size': 64, 'dropout': 0.2114986028797556, 'weight_decay': 1.534692726874199e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0006 | Train acc: 49.80% | Val loss: 1.0060 | Val acc: 45.93% | LR: 0.000012
Epoch: 001 | Train loss: 1.0008 | Train acc: 49.50% | Val loss: 1.0065 | Val acc: 45.98% | LR: 0.000012
Epoch: 002 | Train loss: 1.0014 | Train acc: 49.47% | Val loss: 1.0069 | Val acc: 45.93% | LR: 0.000012
Epoch: 003 | Train loss: 1.0008 | Train acc: 49.65% | Val loss: 1.0059 | Val acc: 45.97% | LR: 0.000012
Epoch: 004 | Train loss: 1.0109 | Train acc: 49.77% | Val loss: 1.0070 | Val acc: 46.08% | LR: 0.000012
Epoch: 005 | Train loss: 1.0004 | Train acc: 49.31% | Val loss: 1.0053 | Val acc: 45.96% | LR: 0.000012
Epoch: 006 | Train loss: 1.0003 | Train acc: 49.50% | Val loss: 1.0053 | Val acc: 46.19% | LR: 0.000012
Epoch: 007 | Train loss: 1.0003 | Train acc: 49.77% | Val loss: 1.0142 | Val acc: 46.13% | LR: 0.000012
Epoch: 008 | Train loss: 1.0003 | Train acc: 49.58% | Val loss: 1.0130 | Val acc: 45.93% | LR: 0.000012
Epoch: 009 | Train loss: 1.0000 | Train acc: 49.75% | Val loss: 1.0052 | Val acc: 46.07% | LR: 0.000012
Epoch: 010 | Train loss: 0.9999 | Train acc: 49.84% | Val loss: 1.0064 | Val acc: 45.99% | LR: 0.000012
Epoch: 011 | Train loss: 1.0008 | Train acc: 48.79% | Val loss: 1.0056 | Val acc: 46.03% | LR: 0.000012
Epoch: 012 | Train loss: 1.0017 | Train acc: 50.33% | Val loss: 1.0053 | Val acc: 46.19% | LR: 0.000012
Epoch: 013 | Train loss: 1.0008 | Train acc: 48.84% | Val loss: 1.0103 | Val acc: 46.01% | LR: 0.000012
Epoch: 014 | Train loss: 1.0001 | Train acc: 49.40% | Val loss: 1.0069 | Val acc: 45.91% | LR: 0.000012
Epoch: 015 | Train loss: 1.0008 | Train acc: 49.88% | Val loss: 1.0059 | Val acc: 46.12% | LR: 0.000012
Epoch: 016 | Train loss: 0.9998 | Train acc: 49.72% | Val loss: 1.0058 | Val acc: 46.16% | LR: 0.000012
Epoch: 017 | Train loss: 0.9995 | Train acc: 50.07% | Val loss: 1.0055 | Val acc: 46.02% | LR: 0.000012
Epoch: 018 | Train loss: 0.9999 | Train acc: 49.79% | Val loss: 1.0051 | Val acc: 45.91% | LR: 0.000012
Epoch: 019 | Train loss: 0.9999 | Train acc: 50.15% | Val loss: 1.0056 | Val acc: 45.85% | LR: 0.000012
Epoch: 020 | Train loss: 0.9997 | Train acc: 50.31% | Val loss: 1.0071 | Val acc: 45.91% | LR: 0.000012
Epoch: 021 | Train loss: 1.0010 | Train acc: 50.25% | Val loss: 1.0054 | Val acc: 45.99% | LR: 0.000012
Epoch: 022 | Train loss: 0.9999 | Train acc: 49.93% | Val loss: 1.0064 | Val acc: 46.05% | LR: 0.000012
Epoch: 023 | Train loss: 1.0000 | Train acc: 49.92% | Val loss: 1.0081 | Val acc: 45.93% | LR: 0.000012
Epoch: 024 | Train loss: 0.9994 | Train acc: 50.36% | Val loss: 1.0071 | Val acc: 46.05% | LR: 0.000012
Epoch: 025 | Train loss: 1.0000 | Train acc: 50.09% | Val loss: 1.0136 | Val acc: 45.87% | LR: 0.000012
Epoch: 026 | Train loss: 0.9991 | Train acc: 50.70% | Val loss: 1.0095 | Val acc: 45.87% | LR: 0.000012
Epoch: 027 | Train loss: 1.0000 | Train acc: 50.06% | Val loss: 1.0058 | Val acc: 45.93% | LR: 0.000012
Epoch: 028 | Train loss: 0.9992 | Train acc: 50.86% | Val loss: 1.0059 | Val acc: 45.87% | LR: 0.000011
Epoch: 029 | Train loss: 1.0001 | Train acc: 50.07% | Val loss: 1.0053 | Val acc: 45.93% | LR: 0.000011
Epoch: 030 | Train loss: 0.9995 | Train acc: 50.53% | Val loss: 1.0050 | Val acc: 45.95% | LR: 0.000011
Epoch: 031 | Train loss: 0.9989 | Train acc: 50.87% | Val loss: 1.0058 | Val acc: 45.95% | LR: 0.000011
Epoch: 032 | Train loss: 0.9987 | Train acc: 50.89% | Val loss: 1.0067 | Val acc: 45.95% | LR: 0.000011
Epoch: 033 | Train loss: 0.9992 | Train acc: 50.66% | Val loss: 1.0060 | Val acc: 45.85% | LR: 0.000011
Epoch: 034 | Train loss: 0.9998 | Train acc: 50.22% | Val loss: 1.0058 | Val acc: 45.97% | LR: 0.000011
Epoch: 035 | Train loss: 0.9999 | Train acc: 50.42% | Val loss: 1.0053 | Val acc: 45.97% | LR: 0.000011
Epoch: 036 | Train loss: 0.9985 | Train acc: 50.88% | Val loss: 1.0145 | Val acc: 45.95% | LR: 0.000011
Epoch: 037 | Train loss: 0.9992 | Train acc: 50.35% | Val loss: 1.0055 | Val acc: 46.03% | LR: 0.000011
Epoch: 038 | Train loss: 0.9987 | Train acc: 50.82% | Val loss: 1.0059 | Val acc: 45.99% | LR: 0.000011
Epoch: 039 | Train loss: 1.0005 | Train acc: 50.22% | Val loss: 1.0060 | Val acc: 45.87% | LR: 0.000011
Epoch: 040 | Train loss: 1.0020 | Train acc: 50.78% | Val loss: 1.0074 | Val acc: 45.97% | LR: 0.000010
Epoch: 041 | Train loss: 0.9990 | Train acc: 50.52% | Val loss: 1.0064 | Val acc: 45.87% | LR: 0.000010
Epoch: 042 | Train loss: 0.9996 | Train acc: 50.30% | Val loss: 1.0066 | Val acc: 45.91% | LR: 0.000010
Epoch: 043 | Train loss: 0.9984 | Train acc: 50.74% | Val loss: 1.0068 | Val acc: 45.87% | LR: 0.000010
Epoch: 044 | Train loss: 0.9985 | Train acc: 50.95% | Val loss: 1.0064 | Val acc: 45.81% | LR: 0.000010
Epoch: 045 | Train loss: 0.9985 | Train acc: 50.59% | Val loss: 1.0060 | Val acc: 45.97% | LR: 0.000010
Epoch: 046 | Train loss: 0.9995 | Train acc: 50.32% | Val loss: 1.0063 | Val acc: 45.99% | LR: 0.000010
Epoch: 047 | Train loss: 0.9986 | Train acc: 50.61% | Val loss: 1.0057 | Val acc: 46.03% | LR: 0.000010
Epoch: 048 | Train loss: 0.9997 | Train acc: 50.14% | Val loss: 1.0060 | Val acc: 46.03% | LR: 0.000010
Epoch: 049 | Train loss: 0.9992 | Train acc: 50.34% | Val loss: 1.0062 | Val acc: 45.93% | LR: 0.000010
Epoch: 050 | Train loss: 0.9974 | Train acc: 51.12% | Val loss: 1.0057 | Val acc: 46.03% | LR: 0.000009
Epoch: 051 | Train loss: 0.9979 | Train acc: 50.85% | Val loss: 1.0060 | Val acc: 45.99% | LR: 0.000009
Epoch: 052 | Train loss: 0.9993 | Train acc: 50.27% | Val loss: 1.0063 | Val acc: 45.87% | LR: 0.000009
Epoch: 053 | Train loss: 0.9993 | Train acc: 50.30% | Val loss: 1.0067 | Val acc: 45.99% | LR: 0.000009
Epoch: 054 | Train loss: 0.9987 | Train acc: 50.39% | Val loss: 1.0058 | Val acc: 45.95% | LR: 0.000009
Epoch: 055 | Train loss: 0.9985 | Train acc: 50.78% | Val loss: 1.0058 | Val acc: 45.97% | LR: 0.000009
Epoch: 056 | Train loss: 0.9980 | Train acc: 50.60% | Val loss: 1.0172 | Val acc: 46.03% | LR: 0.000009
Epoch: 057 | Train loss: 0.9984 | Train acc: 50.52% | Val loss: 1.0118 | Val acc: 45.93% | LR: 0.000009
Epoch: 058 | Train loss: 0.9995 | Train acc: 50.12% | Val loss: 1.0081 | Val acc: 45.83% | LR: 0.000009
Epoch: 059 | Train loss: 1.0019 | Train acc: 50.33% | Val loss: 1.0088 | Val acc: 45.87% | LR: 0.000009
Epoch: 060 | Train loss: 0.9993 | Train acc: 50.06% | Val loss: 1.0060 | Val acc: 45.95% | LR: 0.000008
Epoch: 061 | Train loss: 0.9967 | Train acc: 50.94% | Val loss: 1.0088 | Val acc: 45.91% | LR: 0.000008

[I 2025-09-23 19:02:49,081] Trial 142 finished with value: 0.4599085032939911 and parameters: {'lr': 1.2464545257020505e-05, 'hidden_size': 72, 'dropout': 0.25128430286188674, 'weight_decay': 0.00020992434997699802}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0037 | Train acc: 48.85% | Val loss: 0.9973 | Val acc: 53.40% | LR: 0.000014
Epoch: 001 | Train loss: 1.0023 | Train acc: 49.16% | Val loss: 0.9973 | Val acc: 53.56% | LR: 0.000014
Epoch: 002 | Train loss: 1.0011 | Train acc: 49.49% | Val loss: 0.9972 | Val acc: 53.70% | LR: 0.000014
Epoch: 003 | Train loss: 1.0021 | Train acc: 49.01% | Val loss: 0.9972 | Val acc: 53.77% | LR: 0.000014
Epoch: 004 | Train loss: 1.0020 | Train acc: 49.22% | Val loss: 0.9972 | Val acc: 53.95% | LR: 0.000014
Epoch: 005 | Train loss: 1.0022 | Train acc: 49.36% | Val loss: 0.9972 | Val acc: 53.99% | LR: 0.000014
Epoch: 006 | Train loss: 1.0018 | Train acc: 49.32% | Val loss: 0.9972 | Val acc: 53.91% | LR: 0.000014
Epoch: 007 | Train loss: 1.0013 | Train acc: 49.53% | Val loss: 0.9972 | Val acc: 54.07% | LR: 0.000014
Epoch: 008 | Train loss: 1.0010 | Train acc: 49.74% | Val loss: 0.9972 | Val acc: 54.11% | LR: 0.000014
Epoch: 009 | Train loss: 1.0003 | Train acc: 49.79% | Val loss: 0.9972 | Val acc: 54.09% | LR: 0.000014
Epoch: 010 | Train loss: 1.0009 | Train acc: 49.65% | Val loss: 0.9971 | Val acc: 54.07% | LR: 0.000014
Epoch: 011 | Train loss: 1.0006 | Train acc: 49.79% | Val loss: 0.9971 | Val acc: 54.07% | LR: 0.000014
Epoch: 012 | Train loss: 1.0000 | Train acc: 50.11% | Val loss: 0.9971 | Val acc: 54.11% | LR: 0.000014
Epoch: 013 | Train loss: 1.0010 | Train acc: 49.34% | Val loss: 0.9970 | Val acc: 54.21% | LR: 0.000014
Epoch: 014 | Train loss: 1.0003 | Train acc: 49.62% | Val loss: 0.9970 | Val acc: 54.27% | LR: 0.000014
Epoch: 015 | Train loss: 1.0002 | Train acc: 49.94% | Val loss: 0.9970 | Val acc: 54.27% | LR: 0.000014
Epoch: 016 | Train loss: 0.9996 | Train acc: 50.23% | Val loss: 0.9969 | Val acc: 54.19% | LR: 0.000014
Epoch: 017 | Train loss: 0.9998 | Train acc: 49.58% | Val loss: 0.9966 | Val acc: 54.11% | LR: 0.000014
Epoch: 018 | Train loss: 1.0003 | Train acc: 49.61% | Val loss: 0.9966 | Val acc: 53.99% | LR: 0.000014
Epoch: 019 | Train loss: 0.9999 | Train acc: 49.82% | Val loss: 0.9965 | Val acc: 54.07% | LR: 0.000014
Epoch: 020 | Train loss: 0.9999 | Train acc: 49.90% | Val loss: 0.9965 | Val acc: 54.09% | LR: 0.000014
Epoch: 021 | Train loss: 0.9997 | Train acc: 49.95% | Val loss: 0.9965 | Val acc: 54.00% | LR: 0.000013
Epoch: 022 | Train loss: 0.9996 | Train acc: 50.15% | Val loss: 0.9964 | Val acc: 53.77% | LR: 0.000013
Epoch: 023 | Train loss: 0.9993 | Train acc: 49.96% | Val loss: 0.9963 | Val acc: 53.96% | LR: 0.000013
Epoch: 024 | Train loss: 0.9992 | Train acc: 50.54% | Val loss: 0.9963 | Val acc: 53.94% | LR: 0.000013
Epoch: 025 | Train loss: 0.9991 | Train acc: 50.71% | Val loss: 0.9962 | Val acc: 53.98% | LR: 0.000013
Epoch: 026 | Train loss: 0.9989 | Train acc: 50.36% | Val loss: 0.9962 | Val acc: 53.78% | LR: 0.000013
Epoch: 027 | Train loss: 0.9987 | Train acc: 50.99% | Val loss: 0.9962 | Val acc: 53.54% | LR: 0.000013
Epoch: 028 | Train loss: 0.9985 | Train acc: 51.11% | Val loss: 0.9963 | Val acc: 53.62% | LR: 0.000013
Epoch: 029 | Train loss: 0.9984 | Train acc: 51.32% | Val loss: 0.9963 | Val acc: 53.60% | LR: 0.000013
Epoch: 030 | Train loss: 0.9988 | Train acc: 50.60% | Val loss: 0.9963 | Val acc: 53.85% | LR: 0.000013
Epoch: 031 | Train loss: 0.9985 | Train acc: 51.06% | Val loss: 0.9962 | Val acc: 53.81% | LR: 0.000013
Epoch: 032 | Train loss: 0.9994 | Train acc: 50.24% | Val loss: 0.9961 | Val acc: 53.59% | LR: 0.000013
Epoch: 033 | Train loss: 0.9988 | Train acc: 50.71% | Val loss: 0.9960 | Val acc: 53.61% | LR: 0.000013
Epoch: 034 | Train loss: 0.9988 | Train acc: 50.70% | Val loss: 0.9960 | Val acc: 53.35% | LR: 0.000012
Epoch: 035 | Train loss: 0.9985 | Train acc: 50.86% | Val loss: 0.9960 | Val acc: 53.05% | LR: 0.000012
Epoch: 036 | Train loss: 0.9983 | Train acc: 50.78% | Val loss: 0.9960 | Val acc: 53.17% | LR: 0.000012
Epoch: 037 | Train loss: 0.9988 | Train acc: 50.66% | Val loss: 0.9958 | Val acc: 53.29% | LR: 0.000012
Epoch: 038 | Train loss: 0.9987 | Train acc: 50.78% | Val loss: 0.9958 | Val acc: 53.24% | LR: 0.000012
Epoch: 039 | Train loss: 0.9982 | Train acc: 50.84% | Val loss: 0.9957 | Val acc: 53.22% | LR: 0.000012
Epoch: 040 | Train loss: 0.9969 | Train acc: 51.52% | Val loss: 0.9958 | Val acc: 53.10% | LR: 0.000012
Epoch: 041 | Train loss: 0.9976 | Train acc: 51.07% | Val loss: 0.9958 | Val acc: 53.28% | LR: 0.000012
Epoch: 042 | Train loss: 0.9991 | Train acc: 50.49% | Val loss: 0.9958 | Val acc: 53.30% | LR: 0.000012
Epoch: 043 | Train loss: 0.9988 | Train acc: 50.64% | Val loss: 0.9958 | Val acc: 53.40% | LR: 0.000012
Epoch: 044 | Train loss: 0.9984 | Train acc: 50.64% | Val loss: 0.9958 | Val acc: 53.35% | LR: 0.000011
Epoch: 045 | Train loss: 0.9970 | Train acc: 51.12% | Val loss: 0.9958 | Val acc: 53.37% | LR: 0.000011
Epoch: 046 | Train loss: 0.9970 | Train acc: 51.02% | Val loss: 0.9959 | Val acc: 53.27% | LR: 0.000011
Epoch: 047 | Train loss: 0.9973 | Train acc: 51.19% | Val loss: 0.9958 | Val acc: 53.23% | LR: 0.000011
Epoch: 048 | Train loss: 0.9969 | Train acc: 51.15% | Val loss: 0.9957 | Val acc: 53.17% | LR: 0.000011
Epoch: 049 | Train loss: 0.9977 | Train acc: 50.78% | Val loss: 0.9958 | Val acc: 53.09% | LR: 0.000011
Epoch: 050 | Train loss: 0.9975 | Train acc: 50.67% | Val loss: 0.9957 | Val acc: 53.09% | LR: 0.000011
Epoch: 051 | Train loss: 0.9983 | Train acc: 50.69% | Val loss: 0.9956 | Val acc: 53.09% | LR: 0.000011
Epoch: 052 | Train loss: 0.9971 | Train acc: 50.99% | Val loss: 0.9956 | Val acc: 52.99% | LR: 0.000010
Epoch: 053 | Train loss: 0.9970 | Train acc: 50.83% | Val loss: 0.9956 | Val acc: 52.81% | LR: 0.000010
Epoch: 054 | Train loss: 0.9967 | Train acc: 51.09% | Val loss: 0.9956 | Val acc: 52.61% | LR: 0.000010
Epoch: 055 | Train loss: 0.9967 | Train acc: 50.91% | Val loss: 0.9956 | Val acc: 52.59% | LR: 0.000010
Epoch: 056 | Train loss: 0.9980 | Train acc: 50.67% | Val loss: 0.9955 | Val acc: 52.41% | LR: 0.000010
Epoch: 057 | Train loss: 0.9979 | Train acc: 50.68% | Val loss: 0.9956 | Val acc: 52.39% | LR: 0.000010
Epoch: 058 | Train loss: 0.9964 | Train acc: 50.89% | Val loss: 0.9956 | Val acc: 52.37% | LR: 0.000010
Epoch: 059 | Train loss: 0.9988 | Train acc: 50.20% | Val loss: 0.9955 | Val acc: 52.39% | LR: 0.000010
Epoch: 060 | Train loss: 0.9965 | Train acc: 50.84% | Val loss: 0.9955 | Val acc: 52.39% | LR: 0.000009
Epoch: 061 | Train loss: 0.9977 | Train acc: 50.48% | Val loss: 0.9955 | Val acc: 52.43% | LR: 0.000009
Epoch: 062 | Train loss: 0.9960 | Train acc: 51.17% | Val loss: 0.9955 | Val acc: 52.46% | LR: 0.000009
Epoch: 063 | Train loss: 0.9977 | Train acc: 50.64% | Val loss: 0.9955 | Val acc: 52.46% | LR: 0.000009
Epoch: 064 | Train loss: 0.9974 | Train acc: 50.87% | Val loss: 0.9955 | Val acc: 52.45% | LR: 0.000009

[I 2025-09-23 19:03:45,511] Trial 143 finished with value: 0.5243130564689636 and parameters: {'lr': 1.4129444498462534e-05, 'hidden_size': 68, 'dropout': 0.1843046740491496, 'weight_decay': 0.006072448793781861}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 0.9995 | Train acc: 50.42% | Val loss: 0.9986 | Val acc: 51.64% | LR: 0.000010
Epoch: 001 | Train loss: 0.9992 | Train acc: 51.13% | Val loss: 0.9984 | Val acc: 52.01% | LR: 0.000010
Epoch: 002 | Train loss: 0.9990 | Train acc: 51.12% | Val loss: 0.9984 | Val acc: 51.75% | LR: 0.000010
Epoch: 003 | Train loss: 0.9990 | Train acc: 50.86% | Val loss: 0.9984 | Val acc: 51.72% | LR: 0.000010
Epoch: 004 | Train loss: 0.9989 | Train acc: 50.72% | Val loss: 0.9983 | Val acc: 51.63% | LR: 0.000010
Epoch: 005 | Train loss: 0.9985 | Train acc: 51.00% | Val loss: 0.9982 | Val acc: 51.51% | LR: 0.000010
Epoch: 006 | Train loss: 0.9976 | Train acc: 51.83% | Val loss: 0.9982 | Val acc: 51.29% | LR: 0.000010
Epoch: 007 | Train loss: 0.9977 | Train acc: 50.99% | Val loss: 0.9981 | Val acc: 51.35% | LR: 0.000010
Epoch: 008 | Train loss: 0.9999 | Train acc: 50.99% | Val loss: 0.9981 | Val acc: 51.39% | LR: 0.000010
Epoch: 009 | Train loss: 0.9962 | Train acc: 51.17% | Val loss: 0.9980 | Val acc: 51.59% | LR: 0.000010
Epoch: 010 | Train loss: 0.9968 | Train acc: 51.23% | Val loss: 0.9979 | Val acc: 51.69% | LR: 0.000010
Epoch: 011 | Train loss: 0.9954 | Train acc: 51.36% | Val loss: 0.9979 | Val acc: 51.81% | LR: 0.000010
Epoch: 012 | Train loss: 0.9971 | Train acc: 51.65% | Val loss: 0.9979 | Val acc: 51.72% | LR: 0.000010
Epoch: 013 | Train loss: 0.9966 | Train acc: 51.12% | Val loss: 0.9979 | Val acc: 51.68% | LR: 0.000010
Epoch: 014 | Train loss: 1.0002 | Train acc: 50.71% | Val loss: 0.9978 | Val acc: 51.70% | LR: 0.000010
Epoch: 015 | Train loss: 0.9976 | Train acc: 50.62% | Val loss: 0.9978 | Val acc: 51.72% | LR: 0.000010
Epoch: 016 | Train loss: 0.9967 | Train acc: 50.94% | Val loss: 0.9977 | Val acc: 51.72% | LR: 0.000010
Epoch: 017 | Train loss: 0.9962 | Train acc: 50.87% | Val loss: 0.9976 | Val acc: 51.72% | LR: 0.000010
Epoch: 018 | Train loss: 0.9967 | Train acc: 50.61% | Val loss: 0.9976 | Val acc: 51.70% | LR: 0.000010
Epoch: 019 | Train loss: 0.9962 | Train acc: 50.94% | Val loss: 0.9975 | Val acc: 51.66% | LR: 0.000010
Epoch: 020 | Train loss: 0.9960 | Train acc: 50.77% | Val loss: 0.9974 | Val acc: 51.68% | LR: 0.000010
Epoch: 021 | Train loss: 0.9956 | Train acc: 50.78% | Val loss: 0.9973 | Val acc: 51.72% | LR: 0.000010
Epoch: 022 | Train loss: 0.9955 | Train acc: 51.05% | Val loss: 0.9973 | Val acc: 51.72% | LR: 0.000010
Epoch: 023 | Train loss: 0.9937 | Train acc: 51.07% | Val loss: 0.9972 | Val acc: 51.73% | LR: 0.000009
Epoch: 024 | Train loss: 0.9919 | Train acc: 51.25% | Val loss: 0.9971 | Val acc: 51.65% | LR: 0.000009
Epoch: 025 | Train loss: 0.9942 | Train acc: 50.91% | Val loss: 0.9971 | Val acc: 51.65% | LR: 0.000009
Epoch: 026 | Train loss: 0.9946 | Train acc: 50.99% | Val loss: 0.9971 | Val acc: 51.67% | LR: 0.000009
Epoch: 027 | Train loss: 0.9964 | Train acc: 50.91% | Val loss: 0.9970 | Val acc: 51.79% | LR: 0.000009
Epoch: 028 | Train loss: 0.9931 | Train acc: 51.16% | Val loss: 0.9970 | Val acc: 51.85% | LR: 0.000009
Epoch: 029 | Train loss: 0.9971 | Train acc: 50.90% | Val loss: 0.9970 | Val acc: 51.83% | LR: 0.000009
Epoch: 030 | Train loss: 0.9939 | Train acc: 50.82% | Val loss: 0.9969 | Val acc: 51.88% | LR: 0.000009
Epoch: 031 | Train loss: 0.9941 | Train acc: 51.01% | Val loss: 0.9969 | Val acc: 51.90% | LR: 0.000009
Epoch: 032 | Train loss: 0.9917 | Train acc: 50.99% | Val loss: 0.9969 | Val acc: 52.00% | LR: 0.000009
Epoch: 033 | Train loss: 0.9961 | Train acc: 50.66% | Val loss: 0.9967 | Val acc: 51.95% | LR: 0.000009
Epoch: 034 | Train loss: 0.9965 | Train acc: 50.73% | Val loss: 0.9966 | Val acc: 51.93% | LR: 0.000009
Epoch: 035 | Train loss: 0.9959 | Train acc: 51.10% | Val loss: 0.9966 | Val acc: 51.91% | LR: 0.000009
Epoch: 036 | Train loss: 0.9940 | Train acc: 50.90% | Val loss: 0.9966 | Val acc: 51.93% | LR: 0.000009
Epoch: 037 | Train loss: 0.9969 | Train acc: 50.98% | Val loss: 0.9966 | Val acc: 51.93% | LR: 0.000009
Epoch: 038 | Train loss: 0.9959 | Train acc: 50.81% | Val loss: 0.9965 | Val acc: 52.03% | LR: 0.000009
Epoch: 039 | Train loss: 0.9939 | Train acc: 50.78% | Val loss: 0.9964 | Val acc: 52.02% | LR: 0.000009
Epoch: 040 | Train loss: 0.9933 | Train acc: 51.24% | Val loss: 0.9963 | Val acc: 52.06% | LR: 0.000008
Epoch: 041 | Train loss: 0.9955 | Train acc: 51.17% | Val loss: 0.9963 | Val acc: 52.10% | LR: 0.000008
Epoch: 042 | Train loss: 0.9913 | Train acc: 51.07% | Val loss: 0.9962 | Val acc: 52.10% | LR: 0.000008
Epoch: 043 | Train loss: 0.9961 | Train acc: 50.53% | Val loss: 0.9962 | Val acc: 52.02% | LR: 0.000008
Epoch: 044 | Train loss: 0.9952 | Train acc: 50.71% | Val loss: 0.9962 | Val acc: 52.04% | LR: 0.000008
Epoch: 045 | Train loss: 0.9914 | Train acc: 50.72% | Val loss: 0.9962 | Val acc: 52.06% | LR: 0.000008
Epoch: 046 | Train loss: 0.9933 | Train acc: 50.99% | Val loss: 0.9961 | Val acc: 52.12% | LR: 0.000008
Epoch: 047 | Train loss: 0.9935 | Train acc: 51.15% | Val loss: 0.9961 | Val acc: 52.06% | LR: 0.000008
Epoch: 048 | Train loss: 0.9951 | Train acc: 51.06% | Val loss: 0.9960 | Val acc: 52.18% | LR: 0.000008
Epoch: 049 | Train loss: 0.9997 | Train acc: 50.51% | Val loss: 0.9959 | Val acc: 52.12% | LR: 0.000008
Epoch: 050 | Train loss: 1.0027 | Train acc: 50.09% | Val loss: 0.9959 | Val acc: 52.14% | LR: 0.000008
Epoch: 051 | Train loss: 0.9976 | Train acc: 50.98% | Val loss: 0.9959 | Val acc: 52.24% | LR: 0.000008
Epoch: 052 | Train loss: 0.9999 | Train acc: 50.34% | Val loss: 0.9959 | Val acc: 52.20% | LR: 0.000008
Epoch: 053 | Train loss: 1.0001 | Train acc: 50.32% | Val loss: 0.9958 | Val acc: 52.18% | LR: 0.000007
Epoch: 054 | Train loss: 1.0001 | Train acc: 50.23% | Val loss: 0.9958 | Val acc: 52.18% | LR: 0.000007
Epoch: 055 | Train loss: 0.9988 | Train acc: 50.42% | Val loss: 0.9957 | Val acc: 52.18% | LR: 0.000007
Epoch: 056 | Train loss: 0.9996 | Train acc: 50.42% | Val loss: 0.9957 | Val acc: 52.16% | LR: 0.000007
Epoch: 057 | Train loss: 0.9970 | Train acc: 50.68% | Val loss: 0.9956 | Val acc: 52.24% | LR: 0.000007
Epoch: 058 | Train loss: 0.9987 | Train acc: 50.04% | Val loss: 0.9956 | Val acc: 52.24% | LR: 0.000007
Epoch: 059 | Train loss: 0.9975 | Train acc: 50.83% | Val loss: 0.9956 | Val acc: 52.12% | LR: 0.000007
Epoch: 060 | Train loss: 0.9980 | Train acc: 50.48% | Val loss: 0.9956 | Val acc: 52.18% | LR: 0.000007
Epoch: 061 | Train loss: 0.9989 | Train acc: 50.31% | Val loss: 0.9955 | Val acc: 52.23% | LR: 0.000007
Epoch: 062 | Train loss: 0.9975 | Train acc: 50.23% | Val loss: 0.9955 | Val acc: 52.21% | LR: 0.000007
Epoch: 063 | Train loss: 0.9991 | Train acc: 50.49% | Val loss: 0.9955 | Val acc: 52.23% | LR: 0.000007
Epoch: 064 | Train loss: 0.9973 | Train acc: 50.15% | Val loss: 0.9955 | Val acc: 52.23% | LR: 0.000006
Epoch: 065 | Train loss: 1.0017 | Train acc: 49.87% | Val loss: 0.9955 | Val acc: 52.23% | LR: 0.000006
Epoch: 066 | Train loss: 0.9992 | Train acc: 49.94% | Val loss: 0.9954 | Val acc: 52.23% | LR: 0.000006
Epoch: 067 | Train loss: 0.9987 | Train acc: 50.48% | Val loss: 0.9954 | Val acc: 52.25% | LR: 0.000006
Epoch: 068 | Train loss: 0.9982 | Train acc: 50.21% | Val loss: 0.9954 | Val acc: 52.25% | LR: 0.000006
Epoch: 069 | Train loss: 1.0024 | Train acc: 49.49% | Val loss: 0.9954 | Val acc: 52.25% | LR: 0.000006
Epoch: 070 | Train loss: 0.9960 | Train acc: 50.46% | Val loss: 0.9954 | Val acc: 52.25% | LR: 0.000006
Epoch: 071 | Train loss: 0.9969 | Train acc: 50.28% | Val loss: 0.9954 | Val acc: 52.29% | LR: 0.000006
Epoch: 072 | Train loss: 0.9990 | Train acc: 50.20% | Val loss: 0.9953 | Val acc: 52.29% | LR: 0.000006
Epoch: 073 | Train loss: 0.9989 | Train acc: 50.20% | Val loss: 0.9953 | Val acc: 52.29% | LR: 0.000006
Epoch: 074 | Train loss: 0.9998 | Train acc: 49.85% | Val loss: 0.9953 | Val acc: 52.29% | LR: 0.000006
Epoch: 075 | Train loss: 0.9991 | Train acc: 50.29% | Val loss: 0.9952 | Val acc: 52.25% | LR: 0.000005
Epoch: 076 | Train loss: 0.9975 | Train acc: 50.29% | Val loss: 0.9952 | Val acc: 52.21% | LR: 0.000005
Epoch: 077 | Train loss: 0.9967 | Train acc: 50.56% | Val loss: 0.9952 | Val acc: 52.21% | LR: 0.000005
Epoch: 078 | Train loss: 0.9974 | Train acc: 50.58% | Val loss: 0.9952 | Val acc: 52.15% | LR: 0.000005
Epoch: 079 | Train loss: 0.9991 | Train acc: 50.05% | Val loss: 0.9952 | Val acc: 52.17% | LR: 0.000005
Epoch: 080 | Train loss: 0.9988 | Train acc: 50.23% | Val loss: 0.9951 | Val acc: 52.11% | LR: 0.000005
Epoch: 081 | Train loss: 0.9968 | Train acc: 50.59% | Val loss: 0.9951 | Val acc: 52.11% | LR: 0.000005
Epoch: 082 | Train loss: 0.9989 | Train acc: 50.50% | Val loss: 0.9951 | Val acc: 52.11% | LR: 0.000005
Epoch: 083 | Train loss: 0.9987 | Train acc: 50.32% | Val loss: 0.9951 | Val acc: 52.09% | LR: 0.000005
Epoch: 084 | Train loss: 0.9984 | Train acc: 50.24% | Val loss: 0.9950 | Val acc: 52.07% | LR: 0.000005
Epoch: 085 | Train loss: 0.9998 | Train acc: 49.96% | Val loss: 0.9950 | Val acc: 52.05% | LR: 0.000004
Epoch: 086 | Train loss: 0.9989 | Train acc: 50.59% | Val loss: 0.9949 | Val acc: 52.03% | LR: 0.000004
Epoch: 087 | Train loss: 0.9985 | Train acc: 50.33% | Val loss: 0.9949 | Val acc: 52.03% | LR: 0.000004
Epoch: 088 | Train loss: 0.9966 | Train acc: 50.59% | Val loss: 0.9949 | Val acc: 52.03% | LR: 0.000004
Epoch: 089 | Train loss: 0.9994 | Train acc: 49.97% | Val loss: 0.9949 | Val acc: 52.01% | LR: 0.000004
Epoch: 090 | Train loss: 0.9974 | Train acc: 50.59% | Val loss: 0.9949 | Val acc: 52.03% | LR: 0.000004
Epoch: 091 | Train loss: 1.0000 | Train acc: 49.88% | Val loss: 0.9949 | Val acc: 52.03% | LR: 0.000004
Epoch: 092 | Train loss: 0.9994 | Train acc: 50.06% | Val loss: 0.9949 | Val acc: 52.03% | LR: 0.000004
Epoch: 093 | Train loss: 1.0002 | Train acc: 49.80% | Val loss: 0.9949 | Val acc: 52.09% | LR: 0.000004
Epoch: 094 | Train loss: 0.9988 | Train acc: 50.24% | Val loss: 0.9948 | Val acc: 52.11% | LR: 0.000004
Epoch: 095 | Train loss: 0.9984 | Train acc: 50.15% | Val loss: 0.9948 | Val acc: 52.11% | LR: 0.000004
Epoch: 096 | Train loss: 0.9983 | Train acc: 50.24% | Val loss: 0.9948 | Val acc: 52.11% | LR: 0.000004
Epoch: 097 | Train loss: 0.9982 | Train acc: 49.80% | Val loss: 0.9948 | Val acc: 52.11% | LR: 0.000003
Epoch: 098 | Train loss: 0.9973 | Train acc: 50.78% | Val loss: 0.9947 | Val acc: 52.11% | LR: 0.000003
Epoch: 099 | Train loss: 0.9975 | Train acc: 50.33% | Val loss: 0.9947 | Val acc: 52.13% | LR: 0.000003
Epoch: 100 | Train loss: 0.9998 | Train acc: 50.16% | Val loss: 0.9947 | Val acc: 52.14% | LR: 0.000003
Epoch: 101 | Train loss: 0.9998 | Train acc: 49.89% | Val loss: 0.9947 | Val acc: 52.14% | LR: 0.000003
Epoch: 102 | Train loss: 0.9956 | Train acc: 50.87% | Val loss: 0.9947 | Val acc: 52.14% | LR: 0.000003
Epoch: 103 | Train loss: 0.9964 | Train acc: 50.25% | Val loss: 0.9947 | Val acc: 52.15% | LR: 0.000003
Epoch: 104 | Train loss: 0.9958 | Train acc: 50.87% | Val loss: 0.9947 | Val acc: 52.17% | LR: 0.000003
Epoch: 105 | Train loss: 0.9974 | Train acc: 50.32% | Val loss: 0.9947 | Val acc: 52.21% | LR: 0.000003
Epoch: 106 | Train loss: 0.9998 | Train acc: 50.15% | Val loss: 0.9946 | Val acc: 52.25% | LR: 0.000003
Epoch: 107 | Train loss: 0.9978 | Train acc: 50.06% | Val loss: 0.9946 | Val acc: 52.25% | LR: 0.000003
Epoch: 108 | Train loss: 0.9970 | Train acc: 50.15% | Val loss: 0.9946 | Val acc: 52.25% | LR: 0.000003
Epoch: 109 | Train loss: 1.0000 | Train acc: 49.61% | Val loss: 0.9946 | Val acc: 52.25% | LR: 0.000002
Epoch: 110 | Train loss: 0.9967 | Train acc: 50.68% | Val loss: 0.9946 | Val acc: 52.21% | LR: 0.000002
Epoch: 111 | Train loss: 0.9983 | Train acc: 50.50% | Val loss: 0.9946 | Val acc: 52.21% | LR: 0.000002
Epoch: 112 | Train loss: 0.9966 | Train acc: 50.33% | Val loss: 0.9946 | Val acc: 52.23% | LR: 0.000002
Epoch: 113 | Train loss: 0.9995 | Train acc: 50.32% | Val loss: 0.9945 | Val acc: 52.23% | LR: 0.000002
Epoch: 114 | Train loss: 0.9975 | Train acc: 50.42% | Val loss: 0.9945 | Val acc: 52.25% | LR: 0.000002
Epoch: 115 | Train loss: 0.9989 | Train acc: 50.15% | Val loss: 0.9945 | Val acc: 52.25% | LR: 0.000002
Epoch: 116 | Train loss: 0.9973 | Train acc: 50.33% | Val loss: 0.9945 | Val acc: 52.25% | LR: 0.000002
Epoch: 117 | Train loss: 1.0004 | Train acc: 49.61% | Val loss: 0.9945 | Val acc: 52.25% | LR: 0.000002
Epoch: 118 | Train loss: 0.9985 | Train acc: 50.77% | Val loss: 0.9945 | Val acc: 52.21% | LR: 0.000002
Epoch: 119 | Train loss: 0.9973 | Train acc: 50.50% | Val loss: 0.9945 | Val acc: 52.25% | LR: 0.000002
Epoch: 120 | Train loss: 0.9977 | Train acc: 50.07% | Val loss: 0.9945 | Val acc: 52.25% | LR: 0.000002
Epoch: 121 | Train loss: 0.9976 | Train acc: 50.24% | Val loss: 0.9945 | Val acc: 52.27% | LR: 0.000002

[I 2025-09-23 19:05:20,071] Trial 144 finished with value: 0.5226704835891723 and parameters: {'lr': 1.0036813684998354e-05, 'hidden_size': 76, 'dropout': 0.22228159382562693, 'weight_decay': 1.1461079850026293e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0003 | Train acc: 50.07% | Val loss: 0.9918 | Val acc: 54.11% | LR: 0.000020
Epoch: 001 | Train loss: 1.0007 | Train acc: 49.72% | Val loss: 0.9916 | Val acc: 54.13% | LR: 0.000020
Epoch: 002 | Train loss: 1.0004 | Train acc: 49.54% | Val loss: 0.9916 | Val acc: 54.13% | LR: 0.000020
Epoch: 003 | Train loss: 1.0007 | Train acc: 49.54% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000020
Epoch: 004 | Train loss: 1.0012 | Train acc: 49.37% | Val loss: 0.9918 | Val acc: 54.17% | LR: 0.000020
Epoch: 005 | Train loss: 0.9984 | Train acc: 50.05% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000020
Epoch: 006 | Train loss: 1.0004 | Train acc: 49.89% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000020
Epoch: 007 | Train loss: 1.0011 | Train acc: 49.72% | Val loss: 0.9919 | Val acc: 54.30% | LR: 0.000020
Epoch: 008 | Train loss: 1.0008 | Train acc: 49.57% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000020
Epoch: 009 | Train loss: 0.9990 | Train acc: 50.37% | Val loss: 0.9921 | Val acc: 54.28% | LR: 0.000020
Epoch: 010 | Train loss: 0.9984 | Train acc: 50.73% | Val loss: 0.9921 | Val acc: 54.32% | LR: 0.000020
Epoch: 011 | Train loss: 0.9983 | Train acc: 50.76% | Val loss: 0.9920 | Val acc: 54.32% | LR: 0.000020
Epoch: 012 | Train loss: 0.9980 | Train acc: 50.63% | Val loss: 0.9920 | Val acc: 54.34% | LR: 0.000020
Epoch: 013 | Train loss: 0.9990 | Train acc: 50.42% | Val loss: 0.9918 | Val acc: 54.34% | LR: 0.000020
Epoch: 014 | Train loss: 0.9982 | Train acc: 50.55% | Val loss: 0.9919 | Val acc: 54.40% | LR: 0.000020
Epoch: 015 | Train loss: 0.9992 | Train acc: 50.18% | Val loss: 0.9919 | Val acc: 54.34% | LR: 0.000020
Epoch: 016 | Train loss: 0.9981 | Train acc: 50.60% | Val loss: 0.9920 | Val acc: 54.39% | LR: 0.000019
Epoch: 017 | Train loss: 0.9983 | Train acc: 50.56% | Val loss: 0.9918 | Val acc: 54.33% | LR: 0.000019
Epoch: 018 | Train loss: 0.9984 | Train acc: 50.44% | Val loss: 0.9918 | Val acc: 54.39% | LR: 0.000019
Epoch: 019 | Train loss: 0.9986 | Train acc: 50.29% | Val loss: 0.9918 | Val acc: 54.42% | LR: 0.000019
Epoch: 020 | Train loss: 0.9965 | Train acc: 51.31% | Val loss: 0.9918 | Val acc: 54.42% | LR: 0.000019
Epoch: 021 | Train loss: 0.9976 | Train acc: 50.88% | Val loss: 0.9917 | Val acc: 54.38% | LR: 0.000019
Epoch: 022 | Train loss: 0.9973 | Train acc: 50.89% | Val loss: 0.9916 | Val acc: 54.44% | LR: 0.000019
Epoch: 023 | Train loss: 0.9980 | Train acc: 50.55% | Val loss: 0.9916 | Val acc: 54.49% | LR: 0.000019
Epoch: 024 | Train loss: 0.9978 | Train acc: 50.57% | Val loss: 0.9916 | Val acc: 54.43% | LR: 0.000019
Epoch: 025 | Train loss: 0.9985 | Train acc: 50.26% | Val loss: 0.9915 | Val acc: 54.66% | LR: 0.000019
Epoch: 026 | Train loss: 0.9976 | Train acc: 50.62% | Val loss: 0.9916 | Val acc: 54.66% | LR: 0.000019
Epoch: 027 | Train loss: 0.9969 | Train acc: 51.01% | Val loss: 0.9915 | Val acc: 54.64% | LR: 0.000018
Epoch: 028 | Train loss: 0.9965 | Train acc: 51.21% | Val loss: 0.9914 | Val acc: 54.77% | LR: 0.000018
Epoch: 029 | Train loss: 0.9974 | Train acc: 51.12% | Val loss: 0.9920 | Val acc: 54.42% | LR: 0.000018
Epoch: 030 | Train loss: 0.9982 | Train acc: 50.71% | Val loss: 0.9921 | Val acc: 54.63% | LR: 0.000018
Epoch: 031 | Train loss: 0.9985 | Train acc: 50.65% | Val loss: 0.9931 | Val acc: 54.59% | LR: 0.000018
Epoch: 032 | Train loss: 1.0794 | Train acc: 51.29% | Val loss: 0.9943 | Val acc: 54.55% | LR: 0.000018
Epoch: 033 | Train loss: 0.9988 | Train acc: 50.22% | Val loss: 0.9923 | Val acc: 54.39% | LR: 0.000018
Epoch: 034 | Train loss: 0.9980 | Train acc: 51.12% | Val loss: 0.9967 | Val acc: 54.45% | LR: 0.000018
Epoch: 035 | Train loss: 0.9992 | Train acc: 50.68% | Val loss: 1.0020 | Val acc: 54.49% | LR: 0.000017
Epoch: 036 | Train loss: 0.9980 | Train acc: 50.78% | Val loss: 0.9925 | Val acc: 54.34% | LR: 0.000017
Epoch: 037 | Train loss: 0.9971 | Train acc: 50.68% | Val loss: 0.9921 | Val acc: 54.21% | LR: 0.000017
Epoch: 038 | Train loss: 0.9982 | Train acc: 50.53% | Val loss: 0.9915 | Val acc: 54.35% | LR: 0.000017
Epoch: 039 | Train loss: 0.9977 | Train acc: 50.90% | Val loss: 0.9934 | Val acc: 54.58% | LR: 0.000017
Epoch: 040 | Train loss: 0.9970 | Train acc: 50.99% | Val loss: 0.9916 | Val acc: 54.48% | LR: 0.000017
Epoch: 041 | Train loss: 0.9971 | Train acc: 50.89% | Val loss: 0.9921 | Val acc: 54.37% | LR: 0.000017
Epoch: 042 | Train loss: 0.9980 | Train acc: 50.61% | Val loss: 0.9917 | Val acc: 54.66% | LR: 0.000016
Epoch: 043 | Train loss: 0.9979 | Train acc: 50.51% | Val loss: 0.9908 | Val acc: 54.76% | LR: 0.000016
Epoch: 044 | Train loss: 0.9981 | Train acc: 50.53% | Val loss: 0.9935 | Val acc: 54.78% | LR: 0.000016
Epoch: 045 | Train loss: 0.9966 | Train acc: 50.81% | Val loss: 0.9919 | Val acc: 54.72% | LR: 0.000016
Epoch: 046 | Train loss: 0.9963 | Train acc: 51.24% | Val loss: 0.9916 | Val acc: 54.62% | LR: 0.000016
Epoch: 047 | Train loss: 0.9970 | Train acc: 50.39% | Val loss: 1.0074 | Val acc: 54.54% | LR: 0.000016
Epoch: 048 | Train loss: 0.9973 | Train acc: 50.69% | Val loss: 0.9921 | Val acc: 54.90% | LR: 0.000015
Epoch: 049 | Train loss: 0.9973 | Train acc: 50.59% | Val loss: 0.9909 | Val acc: 55.08% | LR: 0.000015
Epoch: 050 | Train loss: 0.9983 | Train acc: 50.44% | Val loss: 0.9918 | Val acc: 55.00% | LR: 0.000015
Epoch: 051 | Train loss: 0.9962 | Train acc: 50.69% | Val loss: 0.9902 | Val acc: 54.88% | LR: 0.000015
Epoch: 052 | Train loss: 0.9989 | Train acc: 50.10% | Val loss: 0.9908 | Val acc: 55.02% | LR: 0.000015
Epoch: 053 | Train loss: 0.9971 | Train acc: 51.02% | Val loss: 0.9944 | Val acc: 54.56% | LR: 0.000015
Epoch: 054 | Train loss: 0.9966 | Train acc: 51.01% | Val loss: 0.9994 | Val acc: 54.62% | LR: 0.000014
Epoch: 055 | Train loss: 0.9961 | Train acc: 50.73% | Val loss: 0.9920 | Val acc: 54.82% | LR: 0.000014
Epoch: 056 | Train loss: 0.9959 | Train acc: 50.83% | Val loss: 0.9911 | Val acc: 55.00% | LR: 0.000014
Epoch: 057 | Train loss: 0.9961 | Train acc: 51.02% | Val loss: 0.9907 | Val acc: 54.96% | LR: 0.000014
Epoch: 058 | Train loss: 0.9971 | Train acc: 50.55% | Val loss: 0.9911 | Val acc: 54.92% | LR: 0.000014
Epoch: 059 | Train loss: 0.9960 | Train acc: 50.65% | Val loss: 0.9978 | Val acc: 54.90% | LR: 0.000013
Epoch: 060 | Train loss: 0.9958 | Train acc: 50.89% | Val loss: 1.0000 | Val acc: 54.92% | LR: 0.000013
Epoch: 061 | Train loss: 0.9956 | Train acc: 51.50% | Val loss: 0.9909 | Val acc: 54.96% | LR: 0.000013
Epoch: 062 | Train loss: 0.9948 | Train acc: 51.25% | Val loss: 0.9911 | Val acc: 55.00% | LR: 0.000013
Epoch: 063 | Train loss: 0.9986 | Train acc: 50.39% | Val loss: 0.9924 | Val acc: 54.70% | LR: 0.000013
Epoch: 064 | Train loss: 1.0003 | Train acc: 50.61% | Val loss: 0.9922 | Val acc: 54.94% | LR: 0.000013
Epoch: 065 | Train loss: 0.9970 | Train acc: 50.65% | Val loss: 0.9904 | Val acc: 54.85% | LR: 0.000012
Epoch: 066 | Train loss: 0.9966 | Train acc: 50.90% | Val loss: 0.9916 | Val acc: 54.71% | LR: 0.000012
Epoch: 067 | Train loss: 0.9959 | Train acc: 50.38% | Val loss: 0.9919 | Val acc: 54.57% | LR: 0.000012
Epoch: 068 | Train loss: 0.9971 | Train acc: 50.29% | Val loss: 0.9905 | Val acc: 54.63% | LR: 0.000012
Epoch: 069 | Train loss: 0.9960 | Train acc: 50.95% | Val loss: 0.9935 | Val acc: 54.57% | LR: 0.000012
Epoch: 070 | Train loss: 0.9943 | Train acc: 50.95% | Val loss: 0.9908 | Val acc: 54.69% | LR: 0.000011
Epoch: 071 | Train loss: 0.9968 | Train acc: 50.50% | Val loss: 0.9905 | Val acc: 54.53% | LR: 0.000011
Epoch: 072 | Train loss: 0.9951 | Train acc: 51.13% | Val loss: 0.9911 | Val acc: 54.59% | LR: 0.000011
Epoch: 073 | Train loss: 0.9955 | Train acc: 51.39% | Val loss: 0.9917 | Val acc: 54.65% | LR: 0.000011
Epoch: 074 | Train loss: 0.9938 | Train acc: 50.84% | Val loss: 0.9912 | Val acc: 54.53% | LR: 0.000011
Epoch: 075 | Train loss: 0.9951 | Train acc: 50.67% | Val loss: 0.9914 | Val acc: 54.47% | LR: 0.000010
Epoch: 076 | Train loss: 0.9958 | Train acc: 50.84% | Val loss: 0.9926 | Val acc: 54.41% | LR: 0.000010
Epoch: 077 | Train loss: 0.9952 | Train acc: 51.04% | Val loss: 0.9942 | Val acc: 54.31% | LR: 0.000010
Epoch: 078 | Train loss: 0.9941 | Train acc: 51.19% | Val loss: 0.9916 | Val acc: 54.44% | LR: 0.000010
Epoch: 079 | Train loss: 0.9958 | Train acc: 51.04% | Val loss: 0.9914 | Val acc: 54.42% | LR: 0.000010
Epoch: 080 | Train loss: 0.9948 | Train acc: 50.76% | Val loss: 0.9919 | Val acc: 54.41% | LR: 0.000009
Epoch: 081 | Train loss: 0.9945 | Train acc: 51.03% | Val loss: 0.9909 | Val acc: 54.42% | LR: 0.000009
Epoch: 082 | Train loss: 0.9959 | Train acc: 50.34% | Val loss: 0.9945 | Val acc: 54.32% | LR: 0.000009
Epoch: 083 | Train loss: 0.9952 | Train acc: 50.96% | Val loss: 0.9915 | Val acc: 54.38% | LR: 0.000009
Epoch: 084 | Train loss: 0.9945 | Train acc: 50.96% | Val loss: 0.9920 | Val acc: 54.47% | LR: 0.000009
Epoch: 085 | Train loss: 0.9975 | Train acc: 50.50% | Val loss: 0.9913 | Val acc: 54.39% | LR: 0.000008
Epoch: 086 | Train loss: 0.9946 | Train acc: 50.97% | Val loss: 0.9927 | Val acc: 54.44% | LR: 0.000008
Epoch: 087 | Train loss: 0.9931 | Train acc: 51.30% | Val loss: 0.9928 | Val acc: 54.45% | LR: 0.000008
Epoch: 088 | Train loss: 0.9943 | Train acc: 50.80% | Val loss: 0.9938 | Val acc: 54.53% | LR: 0.000008
Epoch: 089 | Train loss: 0.9953 | Train acc: 50.88% | Val loss: 0.9911 | Val acc: 54.51% | LR: 0.000008
Epoch: 090 | Train loss: 0.9956 | Train acc: 50.96% | Val loss: 0.9914 | Val acc: 54.45% | LR: 0.000007
Epoch: 091 | Train loss: 0.9953 | Train acc: 50.80% | Val loss: 0.9919 | Val acc: 54.39% | LR: 0.000007
Epoch: 092 | Train loss: 0.9922 | Train acc: 51.60% | Val loss: 0.9913 | Val acc: 54.53% | LR: 0.000007
Epoch: 093 | Train loss: 0.9944 | Train acc: 50.90% | Val loss: 1.0661 | Val acc: 54.53% | LR: 0.000007
Epoch: 094 | Train loss: 0.9944 | Train acc: 50.62% | Val loss: 0.9917 | Val acc: 54.45% | LR: 0.000007
Epoch: 095 | Train loss: 0.9966 | Train acc: 50.62% | Val loss: 0.9917 | Val acc: 54.43% | LR: 0.000006
Epoch: 096 | Train loss: 0.9927 | Train acc: 51.33% | Val loss: 0.9918 | Val acc: 54.36% | LR: 0.000006
Epoch: 097 | Train loss: 0.9943 | Train acc: 51.15% | Val loss: 0.9916 | Val acc: 54.40% | LR: 0.000006
Epoch: 098 | Train loss: 0.9970 | Train acc: 50.47% | Val loss: 0.9944 | Val acc: 54.32% | LR: 0.000006

[I 2025-09-23 19:06:40,809] Trial 145 finished with value: 0.5415676236152649 and parameters: {'lr': 2.006197215800715e-05, 'hidden_size': 64, 'dropout': 0.2756073013579623, 'weight_decay': 1.989748480047951e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0019 | Train acc: 49.60% | Val loss: 1.0006 | Val acc: 48.86% | LR: 0.000017
Epoch: 001 | Train loss: 1.0024 | Train acc: 49.18% | Val loss: 1.0006 | Val acc: 48.92% | LR: 0.000017
Epoch: 002 | Train loss: 1.0006 | Train acc: 50.24% | Val loss: 1.0006 | Val acc: 49.02% | LR: 0.000017
Epoch: 003 | Train loss: 1.0024 | Train acc: 49.29% | Val loss: 1.0006 | Val acc: 49.02% | LR: 0.000017
Epoch: 004 | Train loss: 1.0020 | Train acc: 49.61% | Val loss: 1.0009 | Val acc: 48.95% | LR: 0.000017
Epoch: 005 | Train loss: 1.0010 | Train acc: 49.83% | Val loss: 1.0009 | Val acc: 48.97% | LR: 0.000017
Epoch: 006 | Train loss: 1.0009 | Train acc: 50.01% | Val loss: 1.0003 | Val acc: 48.99% | LR: 0.000017
Epoch: 007 | Train loss: 1.0010 | Train acc: 49.61% | Val loss: 1.0005 | Val acc: 48.95% | LR: 0.000017
Epoch: 008 | Train loss: 1.0017 | Train acc: 49.57% | Val loss: 1.0009 | Val acc: 48.86% | LR: 0.000017
Epoch: 009 | Train loss: 1.0014 | Train acc: 49.67% | Val loss: 1.0011 | Val acc: 48.90% | LR: 0.000017
Epoch: 010 | Train loss: 1.0011 | Train acc: 49.64% | Val loss: 1.0013 | Val acc: 48.70% | LR: 0.000017
Epoch: 011 | Train loss: 1.0009 | Train acc: 49.73% | Val loss: 1.0015 | Val acc: 48.74% | LR: 0.000017
Epoch: 012 | Train loss: 1.0007 | Train acc: 49.56% | Val loss: 1.0011 | Val acc: 48.72% | LR: 0.000017
Epoch: 013 | Train loss: 1.0012 | Train acc: 49.62% | Val loss: 1.0006 | Val acc: 48.73% | LR: 0.000017
Epoch: 014 | Train loss: 1.0006 | Train acc: 49.73% | Val loss: 1.0007 | Val acc: 48.57% | LR: 0.000017
Epoch: 015 | Train loss: 1.0002 | Train acc: 49.79% | Val loss: 1.0010 | Val acc: 48.54% | LR: 0.000017
Epoch: 016 | Train loss: 1.0007 | Train acc: 49.81% | Val loss: 1.0006 | Val acc: 48.59% | LR: 0.000017
Epoch: 017 | Train loss: 1.0012 | Train acc: 49.63% | Val loss: 1.0004 | Val acc: 48.61% | LR: 0.000017
Epoch: 018 | Train loss: 1.0014 | Train acc: 49.72% | Val loss: 1.0006 | Val acc: 48.59% | LR: 0.000017
Epoch: 019 | Train loss: 1.0005 | Train acc: 49.96% | Val loss: 1.0004 | Val acc: 48.71% | LR: 0.000017
Epoch: 020 | Train loss: 1.0006 | Train acc: 50.05% | Val loss: 1.0015 | Val acc: 48.80% | LR: 0.000016
Epoch: 021 | Train loss: 1.0005 | Train acc: 50.00% | Val loss: 1.0004 | Val acc: 48.69% | LR: 0.000016
Epoch: 022 | Train loss: 0.9997 | Train acc: 51.14% | Val loss: 1.0012 | Val acc: 48.70% | LR: 0.000016
Epoch: 023 | Train loss: 1.0005 | Train acc: 50.08% | Val loss: 1.0006 | Val acc: 48.70% | LR: 0.000016
Epoch: 024 | Train loss: 0.9998 | Train acc: 50.70% | Val loss: 1.0009 | Val acc: 48.90% | LR: 0.000016
Epoch: 025 | Train loss: 1.0006 | Train acc: 50.16% | Val loss: 1.0005 | Val acc: 48.84% | LR: 0.000016
Epoch: 026 | Train loss: 1.0003 | Train acc: 50.22% | Val loss: 1.0005 | Val acc: 48.82% | LR: 0.000016
Epoch: 027 | Train loss: 1.0006 | Train acc: 50.25% | Val loss: 1.0006 | Val acc: 48.80% | LR: 0.000016
Epoch: 028 | Train loss: 1.0003 | Train acc: 50.41% | Val loss: 1.0004 | Val acc: 48.82% | LR: 0.000016
Epoch: 029 | Train loss: 1.0001 | Train acc: 50.31% | Val loss: 1.0009 | Val acc: 48.84% | LR: 0.000016
Epoch: 030 | Train loss: 0.9998 | Train acc: 50.42% | Val loss: 1.0012 | Val acc: 48.90% | LR: 0.000016
Epoch: 031 | Train loss: 0.9997 | Train acc: 50.58% | Val loss: 1.0007 | Val acc: 48.90% | LR: 0.000015
Epoch: 032 | Train loss: 0.9990 | Train acc: 50.85% | Val loss: 1.0024 | Val acc: 48.90% | LR: 0.000015
Epoch: 033 | Train loss: 0.9994 | Train acc: 50.65% | Val loss: 1.0008 | Val acc: 48.92% | LR: 0.000015
Epoch: 034 | Train loss: 0.9995 | Train acc: 50.55% | Val loss: 1.0006 | Val acc: 48.90% | LR: 0.000015
Epoch: 035 | Train loss: 1.0004 | Train acc: 50.13% | Val loss: 1.0012 | Val acc: 48.84% | LR: 0.000015
Epoch: 036 | Train loss: 0.9994 | Train acc: 50.65% | Val loss: 1.0014 | Val acc: 48.76% | LR: 0.000015
Epoch: 037 | Train loss: 1.0003 | Train acc: 50.11% | Val loss: 1.0017 | Val acc: 48.70% | LR: 0.000015
Epoch: 038 | Train loss: 0.9985 | Train acc: 51.00% | Val loss: 1.0007 | Val acc: 48.80% | LR: 0.000015
Epoch: 039 | Train loss: 0.9996 | Train acc: 50.28% | Val loss: 1.0011 | Val acc: 48.69% | LR: 0.000015
Epoch: 040 | Train loss: 0.9994 | Train acc: 50.26% | Val loss: 1.0013 | Val acc: 48.83% | LR: 0.000014
Epoch: 041 | Train loss: 0.9990 | Train acc: 50.45% | Val loss: 1.0005 | Val acc: 48.62% | LR: 0.000014
Epoch: 042 | Train loss: 0.9982 | Train acc: 50.82% | Val loss: 1.0023 | Val acc: 48.77% | LR: 0.000014
Epoch: 043 | Train loss: 0.9998 | Train acc: 50.74% | Val loss: 1.0026 | Val acc: 48.93% | LR: 0.000014
Epoch: 044 | Train loss: 0.9983 | Train acc: 50.70% | Val loss: 0.9998 | Val acc: 48.93% | LR: 0.000014
Epoch: 045 | Train loss: 0.9986 | Train acc: 50.49% | Val loss: 1.0034 | Val acc: 48.75% | LR: 0.000014
Epoch: 046 | Train loss: 0.9988 | Train acc: 50.47% | Val loss: 1.0005 | Val acc: 48.91% | LR: 0.000014
Epoch: 047 | Train loss: 0.9998 | Train acc: 50.32% | Val loss: 1.0005 | Val acc: 48.75% | LR: 0.000013
Epoch: 048 | Train loss: 0.9988 | Train acc: 50.40% | Val loss: 1.0012 | Val acc: 48.91% | LR: 0.000013
Epoch: 049 | Train loss: 1.0000 | Train acc: 50.21% | Val loss: 1.0009 | Val acc: 48.77% | LR: 0.000013
Epoch: 050 | Train loss: 0.9991 | Train acc: 50.31% | Val loss: 1.0014 | Val acc: 48.79% | LR: 0.000013
Epoch: 051 | Train loss: 0.9993 | Train acc: 50.47% | Val loss: 1.0000 | Val acc: 48.77% | LR: 0.000013
Epoch: 052 | Train loss: 0.9978 | Train acc: 50.67% | Val loss: 1.0091 | Val acc: 48.73% | LR: 0.000013

[I 2025-09-23 19:07:24,619] Trial 146 finished with value: 0.4872809112071991 and parameters: {'lr': 1.7236172872783755e-05, 'hidden_size': 71, 'dropout': 0.2568550244298454, 'weight_decay': 3.7620419252875095e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0020 | Train acc: 49.97% | Val loss: 0.9942 | Val acc: 53.95% | LR: 0.000015
Epoch: 001 | Train loss: 1.0009 | Train acc: 50.16% | Val loss: 0.9931 | Val acc: 53.93% | LR: 0.000015
Epoch: 002 | Train loss: 0.9993 | Train acc: 50.07% | Val loss: 0.9924 | Val acc: 53.92% | LR: 0.000015
Epoch: 003 | Train loss: 0.9983 | Train acc: 50.37% | Val loss: 0.9951 | Val acc: 53.86% | LR: 0.000015
Epoch: 004 | Train loss: 1.0003 | Train acc: 50.03% | Val loss: 0.9936 | Val acc: 53.68% | LR: 0.000015
Epoch: 005 | Train loss: 0.9989 | Train acc: 50.12% | Val loss: 0.9942 | Val acc: 53.82% | LR: 0.000015
Epoch: 006 | Train loss: 1.0002 | Train acc: 49.84% | Val loss: 0.9941 | Val acc: 53.86% | LR: 0.000015
Epoch: 007 | Train loss: 0.9967 | Train acc: 50.91% | Val loss: 1.0049 | Val acc: 53.82% | LR: 0.000015
Epoch: 008 | Train loss: 1.0003 | Train acc: 49.92% | Val loss: 1.0015 | Val acc: 53.86% | LR: 0.000015
Epoch: 009 | Train loss: 0.9983 | Train acc: 50.44% | Val loss: 0.9951 | Val acc: 53.74% | LR: 0.000015
Epoch: 010 | Train loss: 1.0007 | Train acc: 50.02% | Val loss: 0.9946 | Val acc: 53.92% | LR: 0.000015
Epoch: 011 | Train loss: 0.9986 | Train acc: 50.47% | Val loss: 1.0029 | Val acc: 53.76% | LR: 0.000015
Epoch: 012 | Train loss: 1.0010 | Train acc: 50.20% | Val loss: 0.9937 | Val acc: 53.78% | LR: 0.000015
Epoch: 013 | Train loss: 0.9978 | Train acc: 50.65% | Val loss: 0.9932 | Val acc: 53.76% | LR: 0.000015
Epoch: 014 | Train loss: 0.9980 | Train acc: 50.64% | Val loss: 0.9964 | Val acc: 53.76% | LR: 0.000015
Epoch: 015 | Train loss: 0.9991 | Train acc: 50.29% | Val loss: 0.9928 | Val acc: 53.78% | LR: 0.000015
Epoch: 016 | Train loss: 0.9999 | Train acc: 50.21% | Val loss: 0.9941 | Val acc: 54.00% | LR: 0.000015
Epoch: 017 | Train loss: 0.9991 | Train acc: 50.37% | Val loss: 0.9929 | Val acc: 53.84% | LR: 0.000014
Epoch: 018 | Train loss: 0.9985 | Train acc: 50.46% | Val loss: 0.9927 | Val acc: 53.86% | LR: 0.000014
Epoch: 019 | Train loss: 1.0001 | Train acc: 50.20% | Val loss: 0.9929 | Val acc: 53.94% | LR: 0.000014
Epoch: 020 | Train loss: 0.9989 | Train acc: 50.57% | Val loss: 0.9944 | Val acc: 53.90% | LR: 0.000014
Epoch: 021 | Train loss: 0.9973 | Train acc: 50.74% | Val loss: 0.9925 | Val acc: 53.92% | LR: 0.000014
Epoch: 022 | Train loss: 1.0004 | Train acc: 50.29% | Val loss: 0.9993 | Val acc: 53.90% | LR: 0.000014
Epoch: 023 | Train loss: 0.9981 | Train acc: 50.29% | Val loss: 0.9958 | Val acc: 53.82% | LR: 0.000014
Epoch: 024 | Train loss: 0.9986 | Train acc: 50.37% | Val loss: 0.9949 | Val acc: 53.97% | LR: 0.000014
Epoch: 025 | Train loss: 0.9987 | Train acc: 50.37% | Val loss: 0.9944 | Val acc: 53.88% | LR: 0.000014
Epoch: 026 | Train loss: 0.9982 | Train acc: 50.48% | Val loss: 0.9934 | Val acc: 53.93% | LR: 0.000014
Epoch: 027 | Train loss: 0.9975 | Train acc: 50.55% | Val loss: 0.9933 | Val acc: 53.95% | LR: 0.000014
Epoch: 028 | Train loss: 1.0015 | Train acc: 49.85% | Val loss: 0.9928 | Val acc: 53.99% | LR: 0.000014
Epoch: 029 | Train loss: 0.9992 | Train acc: 50.12% | Val loss: 0.9927 | Val acc: 53.90% | LR: 0.000014
Epoch: 030 | Train loss: 0.9986 | Train acc: 50.37% | Val loss: 0.9931 | Val acc: 53.92% | LR: 0.000014
Epoch: 031 | Train loss: 0.9979 | Train acc: 50.46% | Val loss: 0.9956 | Val acc: 53.90% | LR: 0.000013
Epoch: 032 | Train loss: 0.9962 | Train acc: 50.72% | Val loss: 0.9933 | Val acc: 54.00% | LR: 0.000013
Epoch: 033 | Train loss: 0.9977 | Train acc: 50.37% | Val loss: 0.9928 | Val acc: 53.88% | LR: 0.000013
Epoch: 034 | Train loss: 0.9958 | Train acc: 50.88% | Val loss: 0.9967 | Val acc: 53.96% | LR: 0.000013
Epoch: 035 | Train loss: 0.9906 | Train acc: 51.41% | Val loss: 0.9925 | Val acc: 53.98% | LR: 0.000013
Epoch: 036 | Train loss: 0.9946 | Train acc: 50.80% | Val loss: 0.9929 | Val acc: 53.89% | LR: 0.000013
Epoch: 037 | Train loss: 0.9953 | Train acc: 50.89% | Val loss: 0.9929 | Val acc: 53.88% | LR: 0.000013
Epoch: 038 | Train loss: 0.9985 | Train acc: 50.33% | Val loss: 0.9930 | Val acc: 53.94% | LR: 0.000013
Epoch: 039 | Train loss: 0.9937 | Train acc: 51.07% | Val loss: 0.9942 | Val acc: 54.00% | LR: 0.000013
Epoch: 040 | Train loss: 0.9993 | Train acc: 50.08% | Val loss: 0.9928 | Val acc: 54.00% | LR: 0.000013
Epoch: 041 | Train loss: 0.9989 | Train acc: 50.37% | Val loss: 0.9920 | Val acc: 53.93% | LR: 0.000012
Epoch: 042 | Train loss: 1.0006 | Train acc: 50.20% | Val loss: 1.0175 | Val acc: 53.84% | LR: 0.000012
Epoch: 043 | Train loss: 0.9976 | Train acc: 50.46% | Val loss: 0.9943 | Val acc: 53.90% | LR: 0.000012
Epoch: 044 | Train loss: 0.9982 | Train acc: 50.46% | Val loss: 0.9937 | Val acc: 53.92% | LR: 0.000012
Epoch: 045 | Train loss: 0.9959 | Train acc: 50.63% | Val loss: 0.9933 | Val acc: 53.96% | LR: 0.000012
Epoch: 046 | Train loss: 0.9958 | Train acc: 50.61% | Val loss: 0.9925 | Val acc: 53.91% | LR: 0.000012
Epoch: 047 | Train loss: 0.9946 | Train acc: 50.86% | Val loss: 0.9929 | Val acc: 53.96% | LR: 0.000012
Epoch: 048 | Train loss: 0.9981 | Train acc: 50.35% | Val loss: 0.9936 | Val acc: 53.94% | LR: 0.000012
Epoch: 049 | Train loss: 0.9977 | Train acc: 50.17% | Val loss: 0.9924 | Val acc: 53.96% | LR: 0.000011
Epoch: 050 | Train loss: 0.9989 | Train acc: 50.34% | Val loss: 0.9928 | Val acc: 53.98% | LR: 0.000011
Epoch: 051 | Train loss: 0.9931 | Train acc: 50.88% | Val loss: 0.9936 | Val acc: 53.90% | LR: 0.000011
Epoch: 052 | Train loss: 0.9967 | Train acc: 50.53% | Val loss: 0.9927 | Val acc: 53.96% | LR: 0.000011
Epoch: 053 | Train loss: 0.9989 | Train acc: 50.17% | Val loss: 0.9993 | Val acc: 53.92% | LR: 0.000011
Epoch: 054 | Train loss: 0.9976 | Train acc: 50.35% | Val loss: 0.9933 | Val acc: 53.96% | LR: 0.000011
Epoch: 055 | Train loss: 0.9976 | Train acc: 50.44% | Val loss: 0.9935 | Val acc: 53.95% | LR: 0.000011
Epoch: 056 | Train loss: 0.9953 | Train acc: 50.53% | Val loss: 0.9931 | Val acc: 53.92% | LR: 0.000011
Epoch: 057 | Train loss: 0.9982 | Train acc: 50.18% | Val loss: 0.9923 | Val acc: 53.92% | LR: 0.000010
Epoch: 058 | Train loss: 0.9966 | Train acc: 50.55% | Val loss: 0.9924 | Val acc: 53.97% | LR: 0.000010
Epoch: 059 | Train loss: 0.9917 | Train acc: 51.06% | Val loss: 0.9925 | Val acc: 54.00% | LR: 0.000010
Epoch: 060 | Train loss: 0.9961 | Train acc: 50.52% | Val loss: 0.9936 | Val acc: 53.99% | LR: 0.000010
Epoch: 061 | Train loss: 0.9971 | Train acc: 50.54% | Val loss: 0.9930 | Val acc: 53.95% | LR: 0.000010
Epoch: 062 | Train loss: 0.9923 | Train acc: 50.98% | Val loss: 0.9925 | Val acc: 53.86% | LR: 0.000010
Epoch: 063 | Train loss: 0.9964 | Train acc: 50.45% | Val loss: 0.9927 | Val acc: 53.95% | LR: 0.000010
Epoch: 064 | Train loss: 0.9996 | Train acc: 50.08% | Val loss: 0.9926 | Val acc: 53.91% | LR: 0.000009
Epoch: 065 | Train loss: 1.0005 | Train acc: 49.91% | Val loss: 0.9927 | Val acc: 53.91% | LR: 0.000009

[I 2025-09-23 19:08:22,784] Trial 147 finished with value: 0.5398577809333801 and parameters: {'lr': 1.4954187528919027e-05, 'hidden_size': 75, 'dropout': 0.2420948714158056, 'weight_decay': 1.2697860422966283e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0035 | Train acc: 48.82% | Val loss: 0.9973 | Val acc: 53.42% | LR: 0.000012
Epoch: 001 | Train loss: 1.0021 | Train acc: 49.20% | Val loss: 0.9973 | Val acc: 53.48% | LR: 0.000012
Epoch: 002 | Train loss: 1.0011 | Train acc: 49.44% | Val loss: 0.9972 | Val acc: 53.58% | LR: 0.000012
Epoch: 003 | Train loss: 1.0025 | Train acc: 48.92% | Val loss: 0.9972 | Val acc: 53.72% | LR: 0.000012
Epoch: 004 | Train loss: 1.0022 | Train acc: 49.07% | Val loss: 0.9972 | Val acc: 53.77% | LR: 0.000012
Epoch: 005 | Train loss: 1.0022 | Train acc: 49.18% | Val loss: 0.9973 | Val acc: 53.79% | LR: 0.000012
Epoch: 006 | Train loss: 1.0020 | Train acc: 49.34% | Val loss: 0.9972 | Val acc: 54.01% | LR: 0.000012
Epoch: 007 | Train loss: 1.0014 | Train acc: 49.52% | Val loss: 0.9972 | Val acc: 53.99% | LR: 0.000012
Epoch: 008 | Train loss: 1.0009 | Train acc: 49.69% | Val loss: 0.9972 | Val acc: 54.07% | LR: 0.000012
Epoch: 009 | Train loss: 1.0005 | Train acc: 49.88% | Val loss: 0.9972 | Val acc: 54.05% | LR: 0.000012
Epoch: 010 | Train loss: 1.0013 | Train acc: 49.55% | Val loss: 0.9971 | Val acc: 54.09% | LR: 0.000011
Epoch: 011 | Train loss: 1.0006 | Train acc: 49.73% | Val loss: 0.9971 | Val acc: 54.13% | LR: 0.000011
Epoch: 012 | Train loss: 1.0000 | Train acc: 50.10% | Val loss: 0.9971 | Val acc: 54.09% | LR: 0.000011
Epoch: 013 | Train loss: 1.0015 | Train acc: 49.30% | Val loss: 0.9970 | Val acc: 54.02% | LR: 0.000011
Epoch: 014 | Train loss: 1.0009 | Train acc: 49.60% | Val loss: 0.9970 | Val acc: 54.11% | LR: 0.000011
Epoch: 015 | Train loss: 1.0002 | Train acc: 49.86% | Val loss: 0.9970 | Val acc: 54.15% | LR: 0.000011
Epoch: 016 | Train loss: 0.9998 | Train acc: 50.22% | Val loss: 0.9969 | Val acc: 54.25% | LR: 0.000011
Epoch: 017 | Train loss: 1.0002 | Train acc: 49.80% | Val loss: 0.9967 | Val acc: 54.11% | LR: 0.000011
Epoch: 018 | Train loss: 1.0003 | Train acc: 49.62% | Val loss: 0.9967 | Val acc: 54.13% | LR: 0.000011
Epoch: 019 | Train loss: 0.9999 | Train acc: 49.96% | Val loss: 0.9966 | Val acc: 54.12% | LR: 0.000011
Epoch: 020 | Train loss: 1.0004 | Train acc: 49.50% | Val loss: 0.9966 | Val acc: 54.08% | LR: 0.000011
Epoch: 021 | Train loss: 1.0001 | Train acc: 49.67% | Val loss: 0.9966 | Val acc: 54.12% | LR: 0.000011
Epoch: 022 | Train loss: 1.0002 | Train acc: 49.70% | Val loss: 0.9965 | Val acc: 54.00% | LR: 0.000011
Epoch: 023 | Train loss: 0.9997 | Train acc: 49.84% | Val loss: 0.9964 | Val acc: 54.07% | LR: 0.000011
Epoch: 024 | Train loss: 0.9997 | Train acc: 50.13% | Val loss: 0.9964 | Val acc: 53.99% | LR: 0.000011
Epoch: 025 | Train loss: 0.9995 | Train acc: 50.14% | Val loss: 0.9964 | Val acc: 54.05% | LR: 0.000011
Epoch: 026 | Train loss: 0.9997 | Train acc: 50.02% | Val loss: 0.9964 | Val acc: 53.99% | LR: 0.000011
Epoch: 027 | Train loss: 0.9997 | Train acc: 50.14% | Val loss: 0.9964 | Val acc: 53.98% | LR: 0.000011
Epoch: 028 | Train loss: 0.9991 | Train acc: 50.49% | Val loss: 0.9965 | Val acc: 54.12% | LR: 0.000011
Epoch: 029 | Train loss: 0.9994 | Train acc: 50.14% | Val loss: 0.9964 | Val acc: 54.18% | LR: 0.000011
Epoch: 030 | Train loss: 0.9990 | Train acc: 50.75% | Val loss: 0.9964 | Val acc: 53.98% | LR: 0.000011
Epoch: 031 | Train loss: 0.9988 | Train acc: 50.59% | Val loss: 0.9964 | Val acc: 53.78% | LR: 0.000010
Epoch: 032 | Train loss: 0.9994 | Train acc: 50.31% | Val loss: 0.9963 | Val acc: 53.76% | LR: 0.000010
Epoch: 033 | Train loss: 0.9990 | Train acc: 50.54% | Val loss: 0.9962 | Val acc: 53.56% | LR: 0.000010
Epoch: 034 | Train loss: 0.9989 | Train acc: 50.64% | Val loss: 0.9962 | Val acc: 53.51% | LR: 0.000010
Epoch: 035 | Train loss: 0.9989 | Train acc: 50.93% | Val loss: 0.9962 | Val acc: 53.53% | LR: 0.000010
Epoch: 036 | Train loss: 0.9988 | Train acc: 50.83% | Val loss: 0.9962 | Val acc: 53.57% | LR: 0.000010
Epoch: 037 | Train loss: 0.9989 | Train acc: 50.67% | Val loss: 0.9960 | Val acc: 53.48% | LR: 0.000010
Epoch: 038 | Train loss: 0.9987 | Train acc: 50.57% | Val loss: 0.9960 | Val acc: 53.82% | LR: 0.000010
Epoch: 039 | Train loss: 0.9987 | Train acc: 50.75% | Val loss: 0.9959 | Val acc: 53.88% | LR: 0.000010
Epoch: 040 | Train loss: 0.9978 | Train acc: 51.30% | Val loss: 0.9960 | Val acc: 53.80% | LR: 0.000010
Epoch: 041 | Train loss: 0.9982 | Train acc: 51.08% | Val loss: 0.9960 | Val acc: 53.65% | LR: 0.000010
Epoch: 042 | Train loss: 0.9985 | Train acc: 50.36% | Val loss: 0.9960 | Val acc: 53.54% | LR: 0.000010
Epoch: 043 | Train loss: 0.9989 | Train acc: 50.48% | Val loss: 0.9960 | Val acc: 53.47% | LR: 0.000010
Epoch: 044 | Train loss: 0.9984 | Train acc: 50.80% | Val loss: 0.9960 | Val acc: 53.25% | LR: 0.000009
Epoch: 045 | Train loss: 0.9980 | Train acc: 51.06% | Val loss: 0.9960 | Val acc: 53.13% | LR: 0.000009
Epoch: 046 | Train loss: 0.9976 | Train acc: 51.16% | Val loss: 0.9961 | Val acc: 53.11% | LR: 0.000009
Epoch: 047 | Train loss: 0.9979 | Train acc: 51.16% | Val loss: 0.9960 | Val acc: 53.25% | LR: 0.000009
Epoch: 048 | Train loss: 0.9977 | Train acc: 51.09% | Val loss: 0.9960 | Val acc: 53.12% | LR: 0.000009
Epoch: 049 | Train loss: 0.9982 | Train acc: 50.70% | Val loss: 0.9960 | Val acc: 53.18% | LR: 0.000009
Epoch: 050 | Train loss: 0.9981 | Train acc: 50.64% | Val loss: 0.9960 | Val acc: 53.14% | LR: 0.000009
Epoch: 051 | Train loss: 0.9983 | Train acc: 50.57% | Val loss: 0.9959 | Val acc: 53.06% | LR: 0.000009
Epoch: 052 | Train loss: 0.9976 | Train acc: 50.93% | Val loss: 0.9958 | Val acc: 53.02% | LR: 0.000009
Epoch: 053 | Train loss: 0.9974 | Train acc: 50.83% | Val loss: 0.9959 | Val acc: 53.04% | LR: 0.000009
Epoch: 054 | Train loss: 0.9972 | Train acc: 51.08% | Val loss: 0.9958 | Val acc: 53.20% | LR: 0.000008
Epoch: 055 | Train loss: 0.9974 | Train acc: 50.84% | Val loss: 0.9958 | Val acc: 53.26% | LR: 0.000008
Epoch: 056 | Train loss: 0.9981 | Train acc: 50.67% | Val loss: 0.9958 | Val acc: 53.43% | LR: 0.000008
Epoch: 057 | Train loss: 0.9981 | Train acc: 50.67% | Val loss: 0.9958 | Val acc: 53.37% | LR: 0.000008
Epoch: 058 | Train loss: 0.9971 | Train acc: 51.01% | Val loss: 0.9958 | Val acc: 53.36% | LR: 0.000008
Epoch: 059 | Train loss: 0.9989 | Train acc: 50.39% | Val loss: 0.9958 | Val acc: 53.43% | LR: 0.000008
Epoch: 060 | Train loss: 0.9971 | Train acc: 50.73% | Val loss: 0.9957 | Val acc: 53.35% | LR: 0.000008
Epoch: 061 | Train loss: 0.9978 | Train acc: 50.56% | Val loss: 0.9957 | Val acc: 53.37% | LR: 0.000008
Epoch: 062 | Train loss: 0.9964 | Train acc: 51.19% | Val loss: 0.9957 | Val acc: 53.29% | LR: 0.000008
Epoch: 063 | Train loss: 0.9979 | Train acc: 50.58% | Val loss: 0.9957 | Val acc: 53.37% | LR: 0.000008
Epoch: 064 | Train loss: 0.9975 | Train acc: 50.87% | Val loss: 0.9958 | Val acc: 53.26% | LR: 0.000007
Epoch: 065 | Train loss: 0.9959 | Train acc: 51.24% | Val loss: 0.9957 | Val acc: 53.28% | LR: 0.000007

[I 2025-09-23 19:09:15,820] Trial 148 finished with value: 0.5318725228309631 and parameters: {'lr': 1.1639478083655162e-05, 'hidden_size': 68, 'dropout': 0.23493091396570714, 'weight_decay': 7.818467111383766e-06}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0000 | Train acc: 49.81% | Val loss: 0.9931 | Val acc: 54.22% | LR: 0.000013
Epoch: 001 | Train loss: 1.0004 | Train acc: 49.36% | Val loss: 0.9930 | Val acc: 54.20% | LR: 0.000013
Epoch: 002 | Train loss: 1.0002 | Train acc: 49.54% | Val loss: 0.9929 | Val acc: 54.24% | LR: 0.000013
Epoch: 003 | Train loss: 0.9994 | Train acc: 49.81% | Val loss: 0.9929 | Val acc: 54.22% | LR: 0.000013
Epoch: 004 | Train loss: 0.9999 | Train acc: 49.73% | Val loss: 0.9928 | Val acc: 54.17% | LR: 0.000013
Epoch: 005 | Train loss: 0.9991 | Train acc: 50.16% | Val loss: 0.9927 | Val acc: 54.22% | LR: 0.000013
Epoch: 006 | Train loss: 0.9992 | Train acc: 49.89% | Val loss: 0.9925 | Val acc: 54.28% | LR: 0.000013
Epoch: 007 | Train loss: 0.9991 | Train acc: 50.17% | Val loss: 0.9925 | Val acc: 54.26% | LR: 0.000013
Epoch: 008 | Train loss: 0.9990 | Train acc: 50.17% | Val loss: 0.9924 | Val acc: 54.34% | LR: 0.000013
Epoch: 009 | Train loss: 0.9988 | Train acc: 50.09% | Val loss: 0.9922 | Val acc: 54.34% | LR: 0.000013
Epoch: 010 | Train loss: 0.9996 | Train acc: 49.59% | Val loss: 0.9922 | Val acc: 54.36% | LR: 0.000013
Epoch: 011 | Train loss: 0.9992 | Train acc: 49.93% | Val loss: 0.9921 | Val acc: 54.34% | LR: 0.000013
Epoch: 012 | Train loss: 0.9993 | Train acc: 49.66% | Val loss: 0.9920 | Val acc: 54.32% | LR: 0.000013
Epoch: 013 | Train loss: 0.9989 | Train acc: 51.06% | Val loss: 0.9919 | Val acc: 54.30% | LR: 0.000013
Epoch: 014 | Train loss: 0.9985 | Train acc: 51.05% | Val loss: 0.9917 | Val acc: 54.24% | LR: 0.000013
Epoch: 015 | Train loss: 0.9984 | Train acc: 50.75% | Val loss: 0.9917 | Val acc: 54.24% | LR: 0.000013
Epoch: 016 | Train loss: 0.9987 | Train acc: 50.57% | Val loss: 0.9916 | Val acc: 54.32% | LR: 0.000013
Epoch: 017 | Train loss: 0.9990 | Train acc: 50.30% | Val loss: 0.9915 | Val acc: 54.42% | LR: 0.000012
Epoch: 018 | Train loss: 0.9981 | Train acc: 50.72% | Val loss: 0.9914 | Val acc: 54.53% | LR: 0.000012
Epoch: 019 | Train loss: 0.9991 | Train acc: 50.26% | Val loss: 0.9913 | Val acc: 54.56% | LR: 0.000012
Epoch: 020 | Train loss: 0.9988 | Train acc: 50.20% | Val loss: 0.9914 | Val acc: 54.38% | LR: 0.000012
Epoch: 021 | Train loss: 0.9981 | Train acc: 50.37% | Val loss: 0.9913 | Val acc: 54.30% | LR: 0.000012
Epoch: 022 | Train loss: 0.9984 | Train acc: 50.24% | Val loss: 0.9912 | Val acc: 54.30% | LR: 0.000012
Epoch: 023 | Train loss: 0.9985 | Train acc: 50.34% | Val loss: 0.9911 | Val acc: 54.44% | LR: 0.000012
Epoch: 024 | Train loss: 0.9978 | Train acc: 50.53% | Val loss: 0.9910 | Val acc: 54.65% | LR: 0.000012
Epoch: 025 | Train loss: 0.9990 | Train acc: 49.86% | Val loss: 0.9909 | Val acc: 54.65% | LR: 0.000012
Epoch: 026 | Train loss: 0.9973 | Train acc: 50.93% | Val loss: 0.9908 | Val acc: 54.71% | LR: 0.000012
Epoch: 027 | Train loss: 0.9973 | Train acc: 50.51% | Val loss: 0.9908 | Val acc: 54.54% | LR: 0.000012
Epoch: 028 | Train loss: 0.9976 | Train acc: 51.05% | Val loss: 0.9907 | Val acc: 54.48% | LR: 0.000012
Epoch: 029 | Train loss: 0.9977 | Train acc: 50.79% | Val loss: 0.9906 | Val acc: 54.48% | LR: 0.000012
Epoch: 030 | Train loss: 0.9968 | Train acc: 50.95% | Val loss: 0.9907 | Val acc: 54.56% | LR: 0.000012
Epoch: 031 | Train loss: 0.9972 | Train acc: 51.05% | Val loss: 0.9906 | Val acc: 54.66% | LR: 0.000012
Epoch: 032 | Train loss: 0.9968 | Train acc: 51.15% | Val loss: 0.9905 | Val acc: 54.73% | LR: 0.000012
Epoch: 033 | Train loss: 0.9977 | Train acc: 50.59% | Val loss: 0.9904 | Val acc: 54.69% | LR: 0.000011
Epoch: 034 | Train loss: 0.9978 | Train acc: 50.63% | Val loss: 0.9903 | Val acc: 54.71% | LR: 0.000011
Epoch: 035 | Train loss: 0.9970 | Train acc: 50.83% | Val loss: 0.9902 | Val acc: 54.61% | LR: 0.000011
Epoch: 036 | Train loss: 0.9984 | Train acc: 50.40% | Val loss: 0.9901 | Val acc: 54.53% | LR: 0.000011
Epoch: 037 | Train loss: 0.9973 | Train acc: 51.02% | Val loss: 0.9901 | Val acc: 54.49% | LR: 0.000011
Epoch: 038 | Train loss: 0.9983 | Train acc: 50.69% | Val loss: 0.9900 | Val acc: 54.57% | LR: 0.000011
Epoch: 039 | Train loss: 0.9965 | Train acc: 50.75% | Val loss: 0.9900 | Val acc: 54.68% | LR: 0.000011
Epoch: 040 | Train loss: 0.9984 | Train acc: 50.30% | Val loss: 0.9899 | Val acc: 54.60% | LR: 0.000011
Epoch: 041 | Train loss: 0.9975 | Train acc: 50.55% | Val loss: 0.9898 | Val acc: 54.46% | LR: 0.000011
Epoch: 042 | Train loss: 0.9960 | Train acc: 50.93% | Val loss: 0.9898 | Val acc: 54.48% | LR: 0.000011
Epoch: 043 | Train loss: 0.9968 | Train acc: 50.68% | Val loss: 0.9897 | Val acc: 54.46% | LR: 0.000011
Epoch: 044 | Train loss: 0.9958 | Train acc: 51.11% | Val loss: 0.9897 | Val acc: 54.44% | LR: 0.000010
Epoch: 045 | Train loss: 0.9970 | Train acc: 50.77% | Val loss: 0.9897 | Val acc: 54.51% | LR: 0.000010
Epoch: 046 | Train loss: 0.9966 | Train acc: 50.67% | Val loss: 0.9898 | Val acc: 54.54% | LR: 0.000010
Epoch: 047 | Train loss: 0.9950 | Train acc: 51.29% | Val loss: 0.9897 | Val acc: 54.54% | LR: 0.000010
Epoch: 048 | Train loss: 0.9978 | Train acc: 50.41% | Val loss: 0.9897 | Val acc: 54.50% | LR: 0.000010
Epoch: 049 | Train loss: 0.9956 | Train acc: 51.02% | Val loss: 0.9896 | Val acc: 54.52% | LR: 0.000010
Epoch: 050 | Train loss: 0.9985 | Train acc: 50.35% | Val loss: 0.9895 | Val acc: 54.37% | LR: 0.000010
Epoch: 051 | Train loss: 0.9955 | Train acc: 50.99% | Val loss: 0.9894 | Val acc: 54.37% | LR: 0.000010
Epoch: 052 | Train loss: 0.9982 | Train acc: 50.63% | Val loss: 0.9894 | Val acc: 54.45% | LR: 0.000010
Epoch: 053 | Train loss: 0.9962 | Train acc: 50.90% | Val loss: 0.9893 | Val acc: 54.49% | LR: 0.000009
Epoch: 054 | Train loss: 0.9971 | Train acc: 50.55% | Val loss: 0.9893 | Val acc: 54.57% | LR: 0.000009
Epoch: 055 | Train loss: 0.9956 | Train acc: 50.90% | Val loss: 0.9892 | Val acc: 54.53% | LR: 0.000009
Epoch: 056 | Train loss: 0.9960 | Train acc: 50.84% | Val loss: 0.9892 | Val acc: 54.47% | LR: 0.000009
Epoch: 057 | Train loss: 0.9996 | Train acc: 49.96% | Val loss: 0.9892 | Val acc: 54.43% | LR: 0.000009
Epoch: 058 | Train loss: 0.9966 | Train acc: 50.58% | Val loss: 0.9891 | Val acc: 54.57% | LR: 0.000009
Epoch: 059 | Train loss: 0.9960 | Train acc: 50.85% | Val loss: 0.9892 | Val acc: 54.48% | LR: 0.000009
Epoch: 060 | Train loss: 0.9975 | Train acc: 50.51% | Val loss: 0.9892 | Val acc: 54.42% | LR: 0.000009
Epoch: 061 | Train loss: 0.9956 | Train acc: 50.94% | Val loss: 0.9891 | Val acc: 54.40% | LR: 0.000009
Epoch: 062 | Train loss: 0.9937 | Train acc: 51.29% | Val loss: 0.9891 | Val acc: 54.23% | LR: 0.000008
Epoch: 063 | Train loss: 0.9942 | Train acc: 51.28% | Val loss: 0.9890 | Val acc: 54.25% | LR: 0.000008
Epoch: 064 | Train loss: 0.9956 | Train acc: 50.66% | Val loss: 0.9889 | Val acc: 54.23% | LR: 0.000008
Epoch: 065 | Train loss: 0.9940 | Train acc: 51.10% | Val loss: 0.9889 | Val acc: 54.25% | LR: 0.000008
Epoch: 066 | Train loss: 0.9954 | Train acc: 50.93% | Val loss: 0.9889 | Val acc: 54.21% | LR: 0.000008
Epoch: 067 | Train loss: 0.9967 | Train acc: 50.48% | Val loss: 0.9888 | Val acc: 54.20% | LR: 0.000008
Epoch: 068 | Train loss: 0.9965 | Train acc: 50.65% | Val loss: 0.9887 | Val acc: 54.16% | LR: 0.000008
Epoch: 069 | Train loss: 0.9957 | Train acc: 50.82% | Val loss: 0.9887 | Val acc: 54.09% | LR: 0.000008
Epoch: 070 | Train loss: 0.9941 | Train acc: 51.06% | Val loss: 0.9888 | Val acc: 54.07% | LR: 0.000007
Epoch: 071 | Train loss: 0.9948 | Train acc: 50.88% | Val loss: 0.9887 | Val acc: 54.03% | LR: 0.000007
Epoch: 072 | Train loss: 0.9952 | Train acc: 50.70% | Val loss: 0.9886 | Val acc: 54.00% | LR: 0.000007
Epoch: 073 | Train loss: 0.9937 | Train acc: 51.06% | Val loss: 0.9885 | Val acc: 54.00% | LR: 0.000007
Epoch: 074 | Train loss: 0.9929 | Train acc: 51.23% | Val loss: 0.9885 | Val acc: 54.02% | LR: 0.000007
Epoch: 075 | Train loss: 0.9943 | Train acc: 50.97% | Val loss: 0.9885 | Val acc: 53.90% | LR: 0.000007
Epoch: 076 | Train loss: 0.9950 | Train acc: 50.63% | Val loss: 0.9884 | Val acc: 53.93% | LR: 0.000007
Epoch: 077 | Train loss: 0.9956 | Train acc: 50.80% | Val loss: 0.9884 | Val acc: 53.90% | LR: 0.000007
Epoch: 078 | Train loss: 0.9957 | Train acc: 50.64% | Val loss: 0.9884 | Val acc: 53.86% | LR: 0.000006
Epoch: 079 | Train loss: 0.9939 | Train acc: 50.90% | Val loss: 0.9884 | Val acc: 53.92% | LR: 0.000006
Epoch: 080 | Train loss: 0.9957 | Train acc: 50.73% | Val loss: 0.9884 | Val acc: 53.71% | LR: 0.000006
Epoch: 081 | Train loss: 0.9938 | Train acc: 51.08% | Val loss: 0.9883 | Val acc: 53.70% | LR: 0.000006

[I 2025-09-23 19:10:28,116] Trial 149 finished with value: 0.5372355937957763 and parameters: {'lr': 1.2914132158040125e-05, 'hidden_size': 81, 'dropout': 0.20122542959929907, 'weight_decay': 2.7875347345509536e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0003 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000025
Epoch: 001 | Train loss: 1.0007 | Train acc: 49.72% | Val loss: 0.9915 | Val acc: 54.13% | LR: 0.000025
Epoch: 002 | Train loss: 1.0003 | Train acc: 49.54% | Val loss: 0.9915 | Val acc: 54.13% | LR: 0.000025
Epoch: 003 | Train loss: 1.0006 | Train acc: 49.54% | Val loss: 0.9917 | Val acc: 54.17% | LR: 0.000025
Epoch: 004 | Train loss: 1.0010 | Train acc: 49.35% | Val loss: 0.9917 | Val acc: 54.28% | LR: 0.000025
Epoch: 005 | Train loss: 0.9984 | Train acc: 50.33% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000025
Epoch: 006 | Train loss: 1.0002 | Train acc: 50.15% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000025
Epoch: 007 | Train loss: 1.0008 | Train acc: 49.72% | Val loss: 0.9919 | Val acc: 54.28% | LR: 0.000025
Epoch: 008 | Train loss: 1.0004 | Train acc: 49.66% | Val loss: 0.9921 | Val acc: 54.32% | LR: 0.000025
Epoch: 009 | Train loss: 0.9986 | Train acc: 50.59% | Val loss: 0.9922 | Val acc: 54.36% | LR: 0.000025
Epoch: 010 | Train loss: 0.9981 | Train acc: 50.81% | Val loss: 0.9923 | Val acc: 54.40% | LR: 0.000025
Epoch: 011 | Train loss: 0.9978 | Train acc: 50.88% | Val loss: 0.9921 | Val acc: 54.40% | LR: 0.000025
Epoch: 012 | Train loss: 0.9976 | Train acc: 50.73% | Val loss: 0.9921 | Val acc: 54.34% | LR: 0.000025
Epoch: 013 | Train loss: 0.9982 | Train acc: 50.41% | Val loss: 0.9918 | Val acc: 54.39% | LR: 0.000025
Epoch: 014 | Train loss: 0.9980 | Train acc: 50.60% | Val loss: 0.9918 | Val acc: 54.29% | LR: 0.000025
Epoch: 015 | Train loss: 0.9986 | Train acc: 50.24% | Val loss: 0.9917 | Val acc: 54.33% | LR: 0.000025
Epoch: 016 | Train loss: 0.9978 | Train acc: 50.76% | Val loss: 0.9920 | Val acc: 54.38% | LR: 0.000025
Epoch: 017 | Train loss: 0.9975 | Train acc: 50.70% | Val loss: 0.9918 | Val acc: 54.40% | LR: 0.000025
Epoch: 018 | Train loss: 0.9976 | Train acc: 50.52% | Val loss: 0.9919 | Val acc: 54.45% | LR: 0.000024
Epoch: 019 | Train loss: 0.9982 | Train acc: 50.37% | Val loss: 0.9920 | Val acc: 54.56% | LR: 0.000024
Epoch: 020 | Train loss: 0.9960 | Train acc: 51.36% | Val loss: 0.9919 | Val acc: 54.46% | LR: 0.000024
Epoch: 021 | Train loss: 0.9965 | Train acc: 50.92% | Val loss: 0.9917 | Val acc: 54.45% | LR: 0.000024
Epoch: 022 | Train loss: 0.9968 | Train acc: 50.94% | Val loss: 0.9921 | Val acc: 54.58% | LR: 0.000024
Epoch: 023 | Train loss: 0.9971 | Train acc: 50.57% | Val loss: 0.9914 | Val acc: 54.60% | LR: 0.000024
Epoch: 024 | Train loss: 0.9970 | Train acc: 50.57% | Val loss: 0.9916 | Val acc: 54.46% | LR: 0.000024
Epoch: 025 | Train loss: 0.9979 | Train acc: 50.20% | Val loss: 0.9923 | Val acc: 54.68% | LR: 0.000024
Epoch: 026 | Train loss: 0.9974 | Train acc: 50.63% | Val loss: 0.9917 | Val acc: 54.61% | LR: 0.000023
Epoch: 027 | Train loss: 0.9967 | Train acc: 50.99% | Val loss: 0.9944 | Val acc: 54.63% | LR: 0.000023
Epoch: 028 | Train loss: 0.9965 | Train acc: 51.12% | Val loss: 0.9916 | Val acc: 54.73% | LR: 0.000023
Epoch: 029 | Train loss: 0.9961 | Train acc: 51.06% | Val loss: 0.9918 | Val acc: 54.43% | LR: 0.000023
Epoch: 030 | Train loss: 0.9978 | Train acc: 50.67% | Val loss: 0.9931 | Val acc: 54.51% | LR: 0.000023
Epoch: 031 | Train loss: 0.9983 | Train acc: 50.63% | Val loss: 0.9920 | Val acc: 54.51% | LR: 0.000023
Epoch: 032 | Train loss: 0.9954 | Train acc: 51.22% | Val loss: 0.9921 | Val acc: 54.53% | LR: 0.000023
Epoch: 033 | Train loss: 0.9975 | Train acc: 50.27% | Val loss: 0.9915 | Val acc: 54.51% | LR: 0.000022
Epoch: 034 | Train loss: 0.9952 | Train acc: 51.17% | Val loss: 0.9934 | Val acc: 54.57% | LR: 0.000022
Epoch: 035 | Train loss: 0.9972 | Train acc: 50.57% | Val loss: 0.9917 | Val acc: 54.49% | LR: 0.000022
Epoch: 036 | Train loss: 1.0071 | Train acc: 50.86% | Val loss: 0.9915 | Val acc: 54.56% | LR: 0.000022
Epoch: 037 | Train loss: 1.0049 | Train acc: 50.98% | Val loss: 0.9917 | Val acc: 54.62% | LR: 0.000022
Epoch: 038 | Train loss: 0.9981 | Train acc: 50.72% | Val loss: 0.9917 | Val acc: 54.70% | LR: 0.000022
Epoch: 039 | Train loss: 0.9953 | Train acc: 50.82% | Val loss: 0.9917 | Val acc: 54.52% | LR: 0.000021
Epoch: 040 | Train loss: 0.9965 | Train acc: 50.79% | Val loss: 0.9917 | Val acc: 54.60% | LR: 0.000021
Epoch: 041 | Train loss: 0.9968 | Train acc: 50.70% | Val loss: 0.9917 | Val acc: 54.57% | LR: 0.000021
Epoch: 042 | Train loss: 0.9990 | Train acc: 50.15% | Val loss: 0.9925 | Val acc: 54.51% | LR: 0.000021
Epoch: 043 | Train loss: 0.9973 | Train acc: 50.39% | Val loss: 0.9916 | Val acc: 54.44% | LR: 0.000021
Epoch: 044 | Train loss: 0.9971 | Train acc: 50.64% | Val loss: 0.9917 | Val acc: 54.46% | LR: 0.000020
Epoch: 045 | Train loss: 0.9960 | Train acc: 50.63% | Val loss: 0.9916 | Val acc: 54.51% | LR: 0.000020
Epoch: 046 | Train loss: 0.9956 | Train acc: 51.18% | Val loss: 0.9916 | Val acc: 54.44% | LR: 0.000020
Epoch: 047 | Train loss: 0.9967 | Train acc: 50.39% | Val loss: 0.9915 | Val acc: 54.25% | LR: 0.000020
Epoch: 048 | Train loss: 0.9975 | Train acc: 50.73% | Val loss: 0.9915 | Val acc: 54.27% | LR: 0.000019
Epoch: 049 | Train loss: 0.9969 | Train acc: 50.67% | Val loss: 0.9913 | Val acc: 54.49% | LR: 0.000019
Epoch: 050 | Train loss: 1.0570 | Train acc: 50.49% | Val loss: 0.9919 | Val acc: 54.47% | LR: 0.000019
Epoch: 051 | Train loss: 1.0087 | Train acc: 50.64% | Val loss: 0.9912 | Val acc: 54.39% | LR: 0.000019
Epoch: 052 | Train loss: 1.0226 | Train acc: 50.49% | Val loss: 0.9917 | Val acc: 54.35% | LR: 0.000019
Epoch: 053 | Train loss: 0.9961 | Train acc: 50.33% | Val loss: 0.9915 | Val acc: 54.23% | LR: 0.000018
Epoch: 054 | Train loss: 0.9991 | Train acc: 51.24% | Val loss: 0.9915 | Val acc: 54.13% | LR: 0.000018
Epoch: 055 | Train loss: 1.0026 | Train acc: 51.10% | Val loss: 0.9916 | Val acc: 54.13% | LR: 0.000018
Epoch: 056 | Train loss: 0.9953 | Train acc: 51.11% | Val loss: 0.9916 | Val acc: 54.13% | LR: 0.000018
Epoch: 057 | Train loss: 0.9957 | Train acc: 51.08% | Val loss: 0.9915 | Val acc: 54.23% | LR: 0.000017
Epoch: 058 | Train loss: 0.9969 | Train acc: 50.45% | Val loss: 0.9915 | Val acc: 54.03% | LR: 0.000017
Epoch: 059 | Train loss: 0.9948 | Train acc: 50.72% | Val loss: 0.9915 | Val acc: 54.03% | LR: 0.000017
Epoch: 060 | Train loss: 0.9959 | Train acc: 51.01% | Val loss: 0.9915 | Val acc: 53.97% | LR: 0.000017
Epoch: 061 | Train loss: 0.9951 | Train acc: 51.64% | Val loss: 0.9914 | Val acc: 53.95% | LR: 0.000016
Epoch: 062 | Train loss: 0.9929 | Train acc: 51.38% | Val loss: 0.9914 | Val acc: 53.91% | LR: 0.000016
Epoch: 063 | Train loss: 0.9971 | Train acc: 50.56% | Val loss: 0.9914 | Val acc: 53.97% | LR: 0.000016
Epoch: 064 | Train loss: 0.9957 | Train acc: 50.58% | Val loss: 0.9915 | Val acc: 53.93% | LR: 0.000016
Epoch: 065 | Train loss: 0.9944 | Train acc: 51.03% | Val loss: 0.9917 | Val acc: 53.83% | LR: 0.000015
Epoch: 066 | Train loss: 0.9970 | Train acc: 51.00% | Val loss: 0.9941 | Val acc: 53.69% | LR: 0.000015
Epoch: 067 | Train loss: 0.9940 | Train acc: 50.45% | Val loss: 0.9914 | Val acc: 53.66% | LR: 0.000015
Epoch: 068 | Train loss: 0.9952 | Train acc: 50.44% | Val loss: 0.9914 | Val acc: 53.64% | LR: 0.000015
Epoch: 069 | Train loss: 0.9940 | Train acc: 50.92% | Val loss: 1.0023 | Val acc: 53.54% | LR: 0.000014
Epoch: 070 | Train loss: 0.9918 | Train acc: 50.96% | Val loss: 0.9913 | Val acc: 53.44% | LR: 0.000014
Epoch: 071 | Train loss: 0.9957 | Train acc: 50.62% | Val loss: 0.9914 | Val acc: 53.39% | LR: 0.000014
Epoch: 072 | Train loss: 0.9910 | Train acc: 51.17% | Val loss: 0.9913 | Val acc: 53.41% | LR: 0.000014
Epoch: 073 | Train loss: 0.9973 | Train acc: 50.21% | Val loss: 0.9917 | Val acc: 53.39% | LR: 0.000013
Epoch: 074 | Train loss: 0.9929 | Train acc: 51.32% | Val loss: 0.9914 | Val acc: 53.30% | LR: 0.000013
Epoch: 075 | Train loss: 0.9926 | Train acc: 51.07% | Val loss: 0.9913 | Val acc: 53.30% | LR: 0.000013
Epoch: 076 | Train loss: 0.9974 | Train acc: 50.98% | Val loss: 0.9913 | Val acc: 53.30% | LR: 0.000013
Epoch: 077 | Train loss: 0.9960 | Train acc: 51.35% | Val loss: 0.9915 | Val acc: 53.32% | LR: 0.000012

[I 2025-09-23 19:11:28,240] Trial 150 finished with value: 0.5326281666755677 and parameters: {'lr': 2.537122967933743e-05, 'hidden_size': 64, 'dropout': 0.1319865061315453, 'weight_decay': 2.1725413568595863e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 0.9994 | Train acc: 50.68% | Val loss: 1.0008 | Val acc: 48.51% | LR: 0.000018
Epoch: 001 | Train loss: 1.0371 | Train acc: 50.00% | Val loss: 1.0026 | Val acc: 48.55% | LR: 0.000018
Epoch: 002 | Train loss: 0.9992 | Train acc: 50.36% | Val loss: 1.0022 | Val acc: 48.33% | LR: 0.000018
Epoch: 003 | Train loss: 1.0002 | Train acc: 50.21% | Val loss: 1.0024 | Val acc: 48.27% | LR: 0.000018
Epoch: 004 | Train loss: 0.9989 | Train acc: 50.50% | Val loss: 1.0015 | Val acc: 48.35% | LR: 0.000018
Epoch: 005 | Train loss: 0.9988 | Train acc: 50.57% | Val loss: 1.0020 | Val acc: 48.18% | LR: 0.000018
Epoch: 006 | Train loss: 0.9972 | Train acc: 50.80% | Val loss: 1.0024 | Val acc: 48.36% | LR: 0.000018
Epoch: 007 | Train loss: 0.9997 | Train acc: 50.48% | Val loss: 1.0023 | Val acc: 48.22% | LR: 0.000018
Epoch: 008 | Train loss: 0.9984 | Train acc: 50.51% | Val loss: 1.0266 | Val acc: 48.15% | LR: 0.000018
Epoch: 009 | Train loss: 0.9981 | Train acc: 50.49% | Val loss: 1.0021 | Val acc: 48.04% | LR: 0.000018
Epoch: 010 | Train loss: 0.9966 | Train acc: 51.09% | Val loss: 1.0043 | Val acc: 48.27% | LR: 0.000018
Epoch: 011 | Train loss: 1.0004 | Train acc: 50.24% | Val loss: 1.0031 | Val acc: 48.35% | LR: 0.000018
Epoch: 012 | Train loss: 0.9983 | Train acc: 50.55% | Val loss: 1.0048 | Val acc: 48.34% | LR: 0.000018
Epoch: 013 | Train loss: 0.9976 | Train acc: 50.67% | Val loss: 1.0017 | Val acc: 48.37% | LR: 0.000018
Epoch: 014 | Train loss: 0.9990 | Train acc: 50.18% | Val loss: 1.0022 | Val acc: 48.31% | LR: 0.000018
Epoch: 015 | Train loss: 0.9970 | Train acc: 50.59% | Val loss: 1.0018 | Val acc: 48.31% | LR: 0.000018
Epoch: 016 | Train loss: 0.9980 | Train acc: 50.48% | Val loss: 1.0023 | Val acc: 48.39% | LR: 0.000018
Epoch: 017 | Train loss: 0.9968 | Train acc: 50.72% | Val loss: 1.0022 | Val acc: 48.26% | LR: 0.000017
Epoch: 018 | Train loss: 0.9997 | Train acc: 50.28% | Val loss: 1.0025 | Val acc: 48.13% | LR: 0.000017
Epoch: 019 | Train loss: 0.9998 | Train acc: 50.02% | Val loss: 1.0025 | Val acc: 48.13% | LR: 0.000017
Epoch: 020 | Train loss: 0.9969 | Train acc: 50.67% | Val loss: 1.0038 | Val acc: 48.25% | LR: 0.000017
Epoch: 021 | Train loss: 0.9970 | Train acc: 50.53% | Val loss: 1.0021 | Val acc: 48.29% | LR: 0.000017
Epoch: 022 | Train loss: 0.9981 | Train acc: 50.22% | Val loss: 1.0021 | Val acc: 48.31% | LR: 0.000017
Epoch: 023 | Train loss: 1.0009 | Train acc: 49.95% | Val loss: 1.0038 | Val acc: 48.23% | LR: 0.000017
Epoch: 024 | Train loss: 0.9984 | Train acc: 50.08% | Val loss: 1.0020 | Val acc: 48.09% | LR: 0.000017
Epoch: 025 | Train loss: 1.0261 | Train acc: 50.12% | Val loss: 1.0025 | Val acc: 48.05% | LR: 0.000017
Epoch: 026 | Train loss: 0.9974 | Train acc: 50.56% | Val loss: 1.0024 | Val acc: 48.09% | LR: 0.000017
Epoch: 027 | Train loss: 0.9980 | Train acc: 50.57% | Val loss: 1.0023 | Val acc: 48.19% | LR: 0.000017
Epoch: 028 | Train loss: 0.9961 | Train acc: 50.76% | Val loss: 1.0024 | Val acc: 48.01% | LR: 0.000017
Epoch: 029 | Train loss: 0.9981 | Train acc: 50.48% | Val loss: 1.0023 | Val acc: 47.91% | LR: 0.000016
Epoch: 030 | Train loss: 0.9964 | Train acc: 50.73% | Val loss: 1.0026 | Val acc: 47.79% | LR: 0.000016
Epoch: 031 | Train loss: 0.9979 | Train acc: 50.60% | Val loss: 1.0023 | Val acc: 47.81% | LR: 0.000016
Epoch: 032 | Train loss: 0.9962 | Train acc: 50.76% | Val loss: 1.0025 | Val acc: 47.79% | LR: 0.000016
Epoch: 033 | Train loss: 0.9978 | Train acc: 50.56% | Val loss: 1.0027 | Val acc: 48.15% | LR: 0.000016
Epoch: 034 | Train loss: 0.9983 | Train acc: 50.02% | Val loss: 1.0029 | Val acc: 47.97% | LR: 0.000016
Epoch: 035 | Train loss: 1.0004 | Train acc: 49.93% | Val loss: 1.0025 | Val acc: 47.92% | LR: 0.000016
Epoch: 036 | Train loss: 0.9967 | Train acc: 50.48% | Val loss: 1.0060 | Val acc: 48.07% | LR: 0.000016
Epoch: 037 | Train loss: 0.9959 | Train acc: 50.65% | Val loss: 1.0022 | Val acc: 48.03% | LR: 0.000015
Epoch: 038 | Train loss: 0.9999 | Train acc: 50.15% | Val loss: 1.0036 | Val acc: 47.91% | LR: 0.000015
Epoch: 039 | Train loss: 0.9997 | Train acc: 50.01% | Val loss: 1.0025 | Val acc: 47.94% | LR: 0.000015
Epoch: 040 | Train loss: 0.9964 | Train acc: 50.61% | Val loss: 1.0031 | Val acc: 47.92% | LR: 0.000015
Epoch: 041 | Train loss: 0.9967 | Train acc: 50.49% | Val loss: 1.0033 | Val acc: 47.95% | LR: 0.000015
Epoch: 042 | Train loss: 0.9961 | Train acc: 50.57% | Val loss: 1.0022 | Val acc: 47.95% | LR: 0.000015
Epoch: 043 | Train loss: 1.0000 | Train acc: 50.24% | Val loss: 1.0025 | Val acc: 47.87% | LR: 0.000015
Epoch: 044 | Train loss: 0.9977 | Train acc: 50.43% | Val loss: 1.0032 | Val acc: 47.87% | LR: 0.000015
Epoch: 045 | Train loss: 0.9952 | Train acc: 50.88% | Val loss: 1.0023 | Val acc: 47.71% | LR: 0.000014
Epoch: 046 | Train loss: 1.0003 | Train acc: 50.08% | Val loss: 1.0025 | Val acc: 47.69% | LR: 0.000014
Epoch: 047 | Train loss: 0.9992 | Train acc: 50.18% | Val loss: 1.0026 | Val acc: 47.69% | LR: 0.000014
Epoch: 048 | Train loss: 0.9975 | Train acc: 50.56% | Val loss: 1.0034 | Val acc: 47.71% | LR: 0.000014
Epoch: 049 | Train loss: 0.9952 | Train acc: 50.90% | Val loss: 1.0043 | Val acc: 47.67% | LR: 0.000014
Epoch: 050 | Train loss: 0.9963 | Train acc: 50.82% | Val loss: 1.0023 | Val acc: 47.69% | LR: 0.000014

[I 2025-09-23 19:12:14,603] Trial 151 finished with value: 0.47749598026275636 and parameters: {'lr': 1.8053383730316143e-05, 'hidden_size': 73, 'dropout': 0.2474286645394827, 'weight_decay': 2.350904162535472e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0014 | Train acc: 49.99% | Val loss: 0.9929 | Val acc: 53.81% | LR: 0.000020
Epoch: 001 | Train loss: 0.9997 | Train acc: 50.12% | Val loss: 0.9925 | Val acc: 53.90% | LR: 0.000020
Epoch: 002 | Train loss: 1.0000 | Train acc: 50.01% | Val loss: 0.9926 | Val acc: 53.66% | LR: 0.000020
Epoch: 003 | Train loss: 0.9982 | Train acc: 50.37% | Val loss: 0.9929 | Val acc: 53.98% | LR: 0.000020
Epoch: 004 | Train loss: 1.0001 | Train acc: 50.01% | Val loss: 0.9946 | Val acc: 53.75% | LR: 0.000020
Epoch: 005 | Train loss: 0.9990 | Train acc: 50.10% | Val loss: 0.9962 | Val acc: 53.70% | LR: 0.000020
Epoch: 006 | Train loss: 1.0003 | Train acc: 49.86% | Val loss: 0.9936 | Val acc: 53.70% | LR: 0.000020
Epoch: 007 | Train loss: 1.0004 | Train acc: 50.92% | Val loss: 0.9962 | Val acc: 53.76% | LR: 0.000020
Epoch: 008 | Train loss: 0.9994 | Train acc: 50.26% | Val loss: 0.9927 | Val acc: 53.76% | LR: 0.000020
Epoch: 009 | Train loss: 1.0069 | Train acc: 50.65% | Val loss: 0.9926 | Val acc: 53.83% | LR: 0.000020
Epoch: 010 | Train loss: 1.0013 | Train acc: 50.01% | Val loss: 0.9986 | Val acc: 53.80% | LR: 0.000020
Epoch: 011 | Train loss: 0.9974 | Train acc: 50.58% | Val loss: 0.9943 | Val acc: 53.92% | LR: 0.000020
Epoch: 012 | Train loss: 1.0005 | Train acc: 50.17% | Val loss: 0.9924 | Val acc: 54.01% | LR: 0.000020
Epoch: 013 | Train loss: 0.9977 | Train acc: 50.64% | Val loss: 0.9940 | Val acc: 53.76% | LR: 0.000020
Epoch: 014 | Train loss: 0.9977 | Train acc: 50.66% | Val loss: 0.9920 | Val acc: 54.01% | LR: 0.000020
Epoch: 015 | Train loss: 0.9990 | Train acc: 50.37% | Val loss: 0.9974 | Val acc: 53.82% | LR: 0.000020
Epoch: 016 | Train loss: 1.0002 | Train acc: 50.20% | Val loss: 0.9933 | Val acc: 53.80% | LR: 0.000019
Epoch: 017 | Train loss: 0.9990 | Train acc: 50.37% | Val loss: 0.9927 | Val acc: 53.86% | LR: 0.000019
Epoch: 018 | Train loss: 0.9984 | Train acc: 50.44% | Val loss: 0.9957 | Val acc: 53.84% | LR: 0.000019
Epoch: 019 | Train loss: 1.0002 | Train acc: 50.17% | Val loss: 0.9939 | Val acc: 53.84% | LR: 0.000019
Epoch: 020 | Train loss: 0.9974 | Train acc: 50.53% | Val loss: 0.9940 | Val acc: 53.78% | LR: 0.000019
Epoch: 021 | Train loss: 0.9966 | Train acc: 50.72% | Val loss: 0.9932 | Val acc: 53.84% | LR: 0.000019
Epoch: 022 | Train loss: 0.9991 | Train acc: 50.26% | Val loss: 0.9927 | Val acc: 54.00% | LR: 0.000019
Epoch: 023 | Train loss: 0.9978 | Train acc: 50.28% | Val loss: 0.9948 | Val acc: 53.88% | LR: 0.000019
Epoch: 024 | Train loss: 0.9983 | Train acc: 50.45% | Val loss: 0.9951 | Val acc: 53.82% | LR: 0.000019
Epoch: 025 | Train loss: 0.9989 | Train acc: 50.32% | Val loss: 0.9933 | Val acc: 53.72% | LR: 0.000019
Epoch: 026 | Train loss: 0.9982 | Train acc: 50.44% | Val loss: 0.9916 | Val acc: 54.12% | LR: 0.000019
Epoch: 027 | Train loss: 0.9972 | Train acc: 50.54% | Val loss: 0.9933 | Val acc: 53.94% | LR: 0.000018
Epoch: 028 | Train loss: 1.0019 | Train acc: 49.82% | Val loss: 0.9926 | Val acc: 53.88% | LR: 0.000018
Epoch: 029 | Train loss: 1.0000 | Train acc: 50.07% | Val loss: 0.9932 | Val acc: 53.76% | LR: 0.000018
Epoch: 030 | Train loss: 0.9988 | Train acc: 50.36% | Val loss: 0.9921 | Val acc: 53.87% | LR: 0.000018
Epoch: 031 | Train loss: 0.9973 | Train acc: 50.44% | Val loss: 0.9925 | Val acc: 53.92% | LR: 0.000018
Epoch: 032 | Train loss: 0.9960 | Train acc: 50.72% | Val loss: 0.9925 | Val acc: 53.99% | LR: 0.000018
Epoch: 033 | Train loss: 0.9989 | Train acc: 50.36% | Val loss: 0.9930 | Val acc: 53.85% | LR: 0.000018
Epoch: 034 | Train loss: 0.9956 | Train acc: 50.80% | Val loss: 0.9931 | Val acc: 53.82% | LR: 0.000018
Epoch: 035 | Train loss: 0.9893 | Train acc: 51.44% | Val loss: 0.9997 | Val acc: 53.85% | LR: 0.000017
Epoch: 036 | Train loss: 0.9941 | Train acc: 50.78% | Val loss: 0.9930 | Val acc: 53.89% | LR: 0.000017
Epoch: 037 | Train loss: 0.9948 | Train acc: 50.88% | Val loss: 0.9927 | Val acc: 54.06% | LR: 0.000017
Epoch: 038 | Train loss: 0.9985 | Train acc: 50.35% | Val loss: 0.9968 | Val acc: 53.85% | LR: 0.000017
Epoch: 039 | Train loss: 0.9931 | Train acc: 51.06% | Val loss: 0.9934 | Val acc: 54.02% | LR: 0.000017
Epoch: 040 | Train loss: 0.9993 | Train acc: 50.09% | Val loss: 1.0609 | Val acc: 53.96% | LR: 0.000017
Epoch: 041 | Train loss: 0.9990 | Train acc: 50.34% | Val loss: 0.9977 | Val acc: 53.95% | LR: 0.000017
Epoch: 042 | Train loss: 1.0004 | Train acc: 50.17% | Val loss: 0.9931 | Val acc: 53.91% | LR: 0.000016
Epoch: 043 | Train loss: 0.9973 | Train acc: 50.44% | Val loss: 0.9922 | Val acc: 54.00% | LR: 0.000016
Epoch: 044 | Train loss: 0.9981 | Train acc: 50.44% | Val loss: 0.9927 | Val acc: 53.91% | LR: 0.000016
Epoch: 045 | Train loss: 0.9952 | Train acc: 50.62% | Val loss: 1.2203 | Val acc: 53.93% | LR: 0.000016
Epoch: 046 | Train loss: 0.9952 | Train acc: 50.63% | Val loss: 0.9929 | Val acc: 53.93% | LR: 0.000016
Epoch: 047 | Train loss: 0.9935 | Train acc: 50.90% | Val loss: 0.9924 | Val acc: 53.99% | LR: 0.000016
Epoch: 048 | Train loss: 0.9979 | Train acc: 50.36% | Val loss: 0.9961 | Val acc: 53.96% | LR: 0.000015
Epoch: 049 | Train loss: 0.9972 | Train acc: 50.18% | Val loss: 0.9927 | Val acc: 54.07% | LR: 0.000015
Epoch: 050 | Train loss: 0.9992 | Train acc: 50.36% | Val loss: 0.9921 | Val acc: 53.94% | LR: 0.000015
Epoch: 051 | Train loss: 0.9922 | Train acc: 50.91% | Val loss: 0.9925 | Val acc: 53.92% | LR: 0.000015
Epoch: 052 | Train loss: 0.9962 | Train acc: 50.55% | Val loss: 0.9914 | Val acc: 53.95% | LR: 0.000015
Epoch: 053 | Train loss: 0.9988 | Train acc: 50.20% | Val loss: 0.9939 | Val acc: 53.97% | LR: 0.000015
Epoch: 054 | Train loss: 0.9972 | Train acc: 50.39% | Val loss: 0.9937 | Val acc: 53.95% | LR: 0.000014
Epoch: 055 | Train loss: 0.9973 | Train acc: 50.47% | Val loss: 0.9924 | Val acc: 53.97% | LR: 0.000014
Epoch: 056 | Train loss: 0.9944 | Train acc: 50.55% | Val loss: 0.9936 | Val acc: 53.95% | LR: 0.000014
Epoch: 057 | Train loss: 0.9980 | Train acc: 50.20% | Val loss: 0.9932 | Val acc: 53.97% | LR: 0.000014
Epoch: 058 | Train loss: 0.9961 | Train acc: 50.57% | Val loss: 0.9931 | Val acc: 53.83% | LR: 0.000014
Epoch: 059 | Train loss: 0.9902 | Train acc: 51.08% | Val loss: 0.9928 | Val acc: 53.99% | LR: 0.000013
Epoch: 060 | Train loss: 0.9954 | Train acc: 50.55% | Val loss: 0.9939 | Val acc: 53.89% | LR: 0.000013
Epoch: 061 | Train loss: 0.9968 | Train acc: 50.55% | Val loss: 0.9933 | Val acc: 53.91% | LR: 0.000013
Epoch: 062 | Train loss: 0.9910 | Train acc: 50.99% | Val loss: 0.9924 | Val acc: 53.89% | LR: 0.000013
Epoch: 063 | Train loss: 0.9959 | Train acc: 50.37% | Val loss: 0.9926 | Val acc: 53.87% | LR: 0.000013
Epoch: 064 | Train loss: 0.9996 | Train acc: 50.12% | Val loss: 0.9919 | Val acc: 53.97% | LR: 0.000013
Epoch: 065 | Train loss: 1.0001 | Train acc: 49.94% | Val loss: 0.9925 | Val acc: 53.95% | LR: 0.000012
Epoch: 066 | Train loss: 1.0000 | Train acc: 50.14% | Val loss: 0.9945 | Val acc: 53.97% | LR: 0.000012
Epoch: 067 | Train loss: 0.9979 | Train acc: 50.31% | Val loss: 0.9921 | Val acc: 54.01% | LR: 0.000012
Epoch: 068 | Train loss: 0.9967 | Train acc: 50.39% | Val loss: 0.9916 | Val acc: 54.05% | LR: 0.000012
Epoch: 069 | Train loss: 0.9925 | Train acc: 50.75% | Val loss: 0.9925 | Val acc: 53.99% | LR: 0.000012
Epoch: 070 | Train loss: 0.9949 | Train acc: 50.40% | Val loss: 0.9923 | Val acc: 53.99% | LR: 0.000011
Epoch: 071 | Train loss: 0.9911 | Train acc: 50.76% | Val loss: 0.9922 | Val acc: 54.04% | LR: 0.000011
Epoch: 072 | Train loss: 0.9952 | Train acc: 50.49% | Val loss: 0.9927 | Val acc: 54.09% | LR: 0.000011
Epoch: 073 | Train loss: 0.9966 | Train acc: 50.22% | Val loss: 0.9914 | Val acc: 54.09% | LR: 0.000011
Epoch: 074 | Train loss: 0.9958 | Train acc: 50.49% | Val loss: 0.9919 | Val acc: 54.09% | LR: 0.000011
Epoch: 075 | Train loss: 0.9990 | Train acc: 50.22% | Val loss: 0.9922 | Val acc: 54.14% | LR: 0.000010
Epoch: 076 | Train loss: 0.9956 | Train acc: 50.57% | Val loss: 0.9927 | Val acc: 54.22% | LR: 0.000010
Epoch: 077 | Train loss: 0.9962 | Train acc: 50.39% | Val loss: 0.9924 | Val acc: 54.22% | LR: 0.000010
Epoch: 078 | Train loss: 0.9913 | Train acc: 50.76% | Val loss: 0.9924 | Val acc: 54.19% | LR: 0.000010
Epoch: 079 | Train loss: 0.9911 | Train acc: 50.83% | Val loss: 0.9922 | Val acc: 54.19% | LR: 0.000010
Epoch: 080 | Train loss: 0.9974 | Train acc: 50.39% | Val loss: 0.9979 | Val acc: 54.10% | LR: 0.000009
Epoch: 081 | Train loss: 0.9920 | Train acc: 50.82% | Val loss: 0.9984 | Val acc: 54.14% | LR: 0.000009
Epoch: 082 | Train loss: 0.9963 | Train acc: 50.12% | Val loss: 0.9920 | Val acc: 54.18% | LR: 0.000009
Epoch: 083 | Train loss: 0.9918 | Train acc: 50.83% | Val loss: 0.9920 | Val acc: 54.18% | LR: 0.000009
Epoch: 084 | Train loss: 0.9956 | Train acc: 50.57% | Val loss: 0.9924 | Val acc: 54.15% | LR: 0.000009
Epoch: 085 | Train loss: 1.0050 | Train acc: 49.77% | Val loss: 0.9918 | Val acc: 54.15% | LR: 0.000008
Epoch: 086 | Train loss: 0.9913 | Train acc: 50.74% | Val loss: 0.9920 | Val acc: 54.11% | LR: 0.000008
Epoch: 087 | Train loss: 0.9940 | Train acc: 50.48% | Val loss: 0.9987 | Val acc: 54.09% | LR: 0.000008
Epoch: 088 | Train loss: 0.9953 | Train acc: 50.57% | Val loss: 0.9929 | Val acc: 54.11% | LR: 0.000008
Epoch: 089 | Train loss: 0.9878 | Train acc: 51.01% | Val loss: 0.9920 | Val acc: 54.15% | LR: 0.000008
Epoch: 090 | Train loss: 0.9887 | Train acc: 51.01% | Val loss: 0.9922 | Val acc: 54.07% | LR: 0.000007
Epoch: 091 | Train loss: 0.9945 | Train acc: 50.48% | Val loss: 0.9965 | Val acc: 54.13% | LR: 0.000007
Epoch: 092 | Train loss: 0.9929 | Train acc: 50.57% | Val loss: 0.9917 | Val acc: 54.20% | LR: 0.000007
Epoch: 093 | Train loss: 0.9961 | Train acc: 50.38% | Val loss: 0.9914 | Val acc: 54.21% | LR: 0.000007
Epoch: 094 | Train loss: 0.9967 | Train acc: 50.48% | Val loss: 0.9920 | Val acc: 54.14% | LR: 0.000007
Epoch: 095 | Train loss: 0.9941 | Train acc: 50.56% | Val loss: 0.9930 | Val acc: 54.12% | LR: 0.000006
Epoch: 096 | Train loss: 0.9936 | Train acc: 50.39% | Val loss: 0.9922 | Val acc: 54.14% | LR: 0.000006
Epoch: 097 | Train loss: 0.9959 | Train acc: 50.48% | Val loss: 0.9919 | Val acc: 54.20% | LR: 0.000006
Epoch: 098 | Train loss: 0.9893 | Train acc: 50.82% | Val loss: 0.9918 | Val acc: 54.20% | LR: 0.000006
Epoch: 099 | Train loss: 1.0005 | Train acc: 49.94% | Val loss: 0.9921 | Val acc: 54.18% | LR: 0.000006
Epoch: 100 | Train loss: 0.9887 | Train acc: 50.81% | Val loss: 0.9928 | Val acc: 54.18% | LR: 0.000006
Epoch: 101 | Train loss: 0.9936 | Train acc: 50.55% | Val loss: 0.9912 | Val acc: 54.18% | LR: 0.000005
Epoch: 102 | Train loss: 1.0004 | Train acc: 49.93% | Val loss: 0.9915 | Val acc: 54.22% | LR: 0.000005
Epoch: 103 | Train loss: 0.9950 | Train acc: 50.37% | Val loss: 0.9921 | Val acc: 54.24% | LR: 0.000005
Epoch: 104 | Train loss: 0.9933 | Train acc: 50.37% | Val loss: 0.9919 | Val acc: 54.26% | LR: 0.000005
Epoch: 105 | Train loss: 0.9893 | Train acc: 50.64% | Val loss: 0.9915 | Val acc: 54.32% | LR: 0.000005
Epoch: 106 | Train loss: 0.9972 | Train acc: 50.10% | Val loss: 0.9915 | Val acc: 54.32% | LR: 0.000005
Epoch: 107 | Train loss: 0.9866 | Train acc: 50.99% | Val loss: 0.9915 | Val acc: 54.28% | LR: 0.000004
Epoch: 108 | Train loss: 0.9891 | Train acc: 50.99% | Val loss: 0.9929 | Val acc: 54.30% | LR: 0.000004
Epoch: 109 | Train loss: 0.9995 | Train acc: 50.11% | Val loss: 0.9921 | Val acc: 54.26% | LR: 0.000004
Epoch: 110 | Train loss: 0.9931 | Train acc: 50.55% | Val loss: 0.9919 | Val acc: 54.30% | LR: 0.000004
Epoch: 111 | Train loss: 0.9939 | Train acc: 50.64% | Val loss: 0.9915 | Val acc: 54.34% | LR: 0.000004
Epoch: 112 | Train loss: 0.9947 | Train acc: 50.64% | Val loss: 0.9915 | Val acc: 54.34% | LR: 0.000004
Epoch: 113 | Train loss: 0.9928 | Train acc: 50.55% | Val loss: 0.9920 | Val acc: 54.32% | LR: 0.000004
Epoch: 114 | Train loss: 0.9930 | Train acc: 50.73% | Val loss: 0.9920 | Val acc: 54.32% | LR: 0.000003
Epoch: 115 | Train loss: 1.0002 | Train acc: 50.03% | Val loss: 0.9915 | Val acc: 54.34% | LR: 0.000003
Epoch: 116 | Train loss: 0.9893 | Train acc: 50.83% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000003
Epoch: 117 | Train loss: 0.9999 | Train acc: 50.03% | Val loss: 0.9920 | Val acc: 54.32% | LR: 0.000003
Epoch: 118 | Train loss: 0.9980 | Train acc: 50.30% | Val loss: 0.9919 | Val acc: 54.32% | LR: 0.000003
Epoch: 119 | Train loss: 0.9891 | Train acc: 50.91% | Val loss: 0.9919 | Val acc: 54.32% | LR: 0.000003
Epoch: 120 | Train loss: 0.9912 | Train acc: 50.65% | Val loss: 0.9920 | Val acc: 54.32% | LR: 0.000003
Epoch: 121 | Train loss: 0.9861 | Train acc: 51.09% | Val loss: 0.9923 | Val acc: 54.30% | LR: 0.000003
Epoch: 122 | Train loss: 0.9911 | Train acc: 50.73% | Val loss: 0.9917 | Val acc: 54.32% | LR: 0.000002
Epoch: 123 | Train loss: 0.9896 | Train acc: 50.72% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000002
Epoch: 124 | Train loss: 0.9857 | Train acc: 51.16% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000002
Epoch: 125 | Train loss: 0.9934 | Train acc: 50.37% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000002
Epoch: 126 | Train loss: 1.0022 | Train acc: 50.01% | Val loss: 0.9917 | Val acc: 54.32% | LR: 0.000002
Epoch: 127 | Train loss: 0.9942 | Train acc: 50.55% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000002
Epoch: 128 | Train loss: 0.9878 | Train acc: 50.99% | Val loss: 0.9917 | Val acc: 54.30% | LR: 0.000002
Epoch: 129 | Train loss: 0.9803 | Train acc: 51.35% | Val loss: 0.9917 | Val acc: 54.32% | LR: 0.000002
Epoch: 130 | Train loss: 0.9995 | Train acc: 50.29% | Val loss: 0.9919 | Val acc: 54.34% | LR: 0.000002
Epoch: 131 | Train loss: 0.9899 | Train acc: 50.64% | Val loss: 0.9916 | Val acc: 54.28% | LR: 0.000002
Epoch: 132 | Train loss: 0.9962 | Train acc: 50.28% | Val loss: 0.9913 | Val acc: 54.32% | LR: 0.000002
Epoch: 133 | Train loss: 0.9969 | Train acc: 50.46% | Val loss: 0.9916 | Val acc: 54.34% | LR: 0.000002
Epoch: 134 | Train loss: 0.9931 | Train acc: 50.46% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000001
Epoch: 135 | Train loss: 0.9933 | Train acc: 50.55% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000001
Epoch: 136 | Train loss: 0.9930 | Train acc: 50.46% | Val loss: 0.9917 | Val acc: 54.32% | LR: 0.000001
Epoch: 137 | Train loss: 0.9931 | Train acc: 50.55% | Val loss: 0.9925 | Val acc: 54.28% | LR: 0.000001
Epoch: 138 | Train loss: 0.9996 | Train acc: 50.02% | Val loss: 0.9915 | Val acc: 54.40% | LR: 0.000001
Epoch: 139 | Train loss: 0.9953 | Train acc: 50.38% | Val loss: 0.9915 | Val acc: 54.34% | LR: 0.000001
Epoch: 140 | Train loss: 0.9927 | Train acc: 50.64% | Val loss: 0.9920 | Val acc: 54.28% | LR: 0.000001
Epoch: 141 | Train loss: 1.0001 | Train acc: 50.02% | Val loss: 0.9908 | Val acc: 54.32% | LR: 0.000001
Epoch: 142 | Train loss: 0.9858 | Train acc: 50.90% | Val loss: 0.9908 | Val acc: 54.32% | LR: 0.000001
Epoch: 143 | Train loss: 0.9924 | Train acc: 50.46% | Val loss: 0.9916 | Val acc: 54.24% | LR: 0.000001
Epoch: 144 | Train loss: 0.9927 | Train acc: 50.65% | Val loss: 0.9912 | Val acc: 54.26% | LR: 0.000001
Epoch: 145 | Train loss: 0.9825 | Train acc: 51.00% | Val loss: 0.9910 | Val acc: 54.28% | LR: 0.000001
Epoch: 146 | Train loss: 0.9900 | Train acc: 50.74% | Val loss: 0.9916 | Val acc: 54.22% | LR: 0.000001
Epoch: 147 | Train loss: 0.9922 | Train acc: 50.56% | Val loss: 0.9912 | Val acc: 54.24% | LR: 0.000001
Epoch: 148 | Train loss: 1.0002 | Train acc: 50.12% | Val loss: 0.9914 | Val acc: 54.24% | LR: 0.000001
Epoch: 149 | Train loss: 1.0173 | Train acc: 50.12% | Val loss: 0.9914 | Val acc: 54.24% | LR: 0.000001

[I 2025-09-23 19:14:08,264] Trial 152 finished with value: 0.5424191951751709 and parameters: {'lr': 2.0073846613838258e-05, 'hidden_size': 75, 'dropout': 0.218257349531178, 'weight_decay': 1.627437530886402e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0038 | Train acc: 48.82% | Val loss: 0.9973 | Val acc: 53.44% | LR: 0.000016
Epoch: 001 | Train loss: 1.0022 | Train acc: 49.17% | Val loss: 0.9973 | Val acc: 53.60% | LR: 0.000016
Epoch: 002 | Train loss: 1.0014 | Train acc: 49.46% | Val loss: 0.9972 | Val acc: 53.77% | LR: 0.000016
Epoch: 003 | Train loss: 1.0026 | Train acc: 49.00% | Val loss: 0.9972 | Val acc: 53.91% | LR: 0.000016
Epoch: 004 | Train loss: 1.0023 | Train acc: 49.11% | Val loss: 0.9972 | Val acc: 53.97% | LR: 0.000016
Epoch: 005 | Train loss: 1.0023 | Train acc: 49.10% | Val loss: 0.9973 | Val acc: 53.89% | LR: 0.000016
Epoch: 006 | Train loss: 1.0019 | Train acc: 49.08% | Val loss: 0.9972 | Val acc: 54.01% | LR: 0.000016
Epoch: 007 | Train loss: 1.0014 | Train acc: 49.21% | Val loss: 0.9972 | Val acc: 54.07% | LR: 0.000016
Epoch: 008 | Train loss: 1.0008 | Train acc: 49.50% | Val loss: 0.9972 | Val acc: 54.11% | LR: 0.000016
Epoch: 009 | Train loss: 1.0005 | Train acc: 49.58% | Val loss: 0.9972 | Val acc: 54.07% | LR: 0.000016
Epoch: 010 | Train loss: 1.0013 | Train acc: 49.06% | Val loss: 0.9971 | Val acc: 54.11% | LR: 0.000016
Epoch: 011 | Train loss: 1.0005 | Train acc: 49.70% | Val loss: 0.9971 | Val acc: 54.21% | LR: 0.000016
Epoch: 012 | Train loss: 1.0001 | Train acc: 49.81% | Val loss: 0.9971 | Val acc: 54.31% | LR: 0.000016
Epoch: 013 | Train loss: 1.0011 | Train acc: 49.17% | Val loss: 0.9970 | Val acc: 54.33% | LR: 0.000016
Epoch: 014 | Train loss: 1.0006 | Train acc: 49.34% | Val loss: 0.9970 | Val acc: 54.29% | LR: 0.000016
Epoch: 015 | Train loss: 1.0001 | Train acc: 49.72% | Val loss: 0.9970 | Val acc: 54.23% | LR: 0.000016
Epoch: 016 | Train loss: 0.9996 | Train acc: 50.28% | Val loss: 0.9969 | Val acc: 54.17% | LR: 0.000016
Epoch: 017 | Train loss: 0.9999 | Train acc: 49.94% | Val loss: 0.9966 | Val acc: 54.19% | LR: 0.000015
Epoch: 018 | Train loss: 0.9999 | Train acc: 50.14% | Val loss: 0.9966 | Val acc: 54.06% | LR: 0.000015
Epoch: 019 | Train loss: 0.9998 | Train acc: 50.33% | Val loss: 0.9965 | Val acc: 53.87% | LR: 0.000015
Epoch: 020 | Train loss: 0.9998 | Train acc: 50.17% | Val loss: 0.9965 | Val acc: 54.20% | LR: 0.000015
Epoch: 021 | Train loss: 0.9996 | Train acc: 50.10% | Val loss: 0.9964 | Val acc: 53.84% | LR: 0.000015
Epoch: 022 | Train loss: 0.9994 | Train acc: 50.30% | Val loss: 0.9963 | Val acc: 53.68% | LR: 0.000015
Epoch: 023 | Train loss: 0.9994 | Train acc: 50.40% | Val loss: 0.9962 | Val acc: 53.59% | LR: 0.000015
Epoch: 024 | Train loss: 0.9992 | Train acc: 50.75% | Val loss: 0.9962 | Val acc: 53.41% | LR: 0.000015
Epoch: 025 | Train loss: 0.9991 | Train acc: 50.55% | Val loss: 0.9962 | Val acc: 53.59% | LR: 0.000015
Epoch: 026 | Train loss: 0.9987 | Train acc: 50.95% | Val loss: 0.9961 | Val acc: 53.94% | LR: 0.000015
Epoch: 027 | Train loss: 0.9990 | Train acc: 50.83% | Val loss: 0.9962 | Val acc: 53.69% | LR: 0.000015
Epoch: 028 | Train loss: 0.9986 | Train acc: 50.82% | Val loss: 0.9963 | Val acc: 53.45% | LR: 0.000015
Epoch: 029 | Train loss: 0.9980 | Train acc: 51.31% | Val loss: 0.9963 | Val acc: 53.09% | LR: 0.000015
Epoch: 030 | Train loss: 0.9981 | Train acc: 51.08% | Val loss: 0.9963 | Val acc: 53.08% | LR: 0.000014
Epoch: 031 | Train loss: 0.9979 | Train acc: 51.15% | Val loss: 0.9962 | Val acc: 53.16% | LR: 0.000014
Epoch: 032 | Train loss: 0.9991 | Train acc: 50.43% | Val loss: 0.9961 | Val acc: 53.18% | LR: 0.000014
Epoch: 033 | Train loss: 0.9984 | Train acc: 50.82% | Val loss: 0.9960 | Val acc: 53.02% | LR: 0.000014
Epoch: 034 | Train loss: 0.9987 | Train acc: 50.80% | Val loss: 0.9959 | Val acc: 53.28% | LR: 0.000014
Epoch: 035 | Train loss: 0.9976 | Train acc: 51.22% | Val loss: 0.9959 | Val acc: 53.31% | LR: 0.000014
Epoch: 036 | Train loss: 0.9976 | Train acc: 50.92% | Val loss: 0.9959 | Val acc: 53.30% | LR: 0.000014
Epoch: 037 | Train loss: 0.9981 | Train acc: 50.72% | Val loss: 0.9957 | Val acc: 53.30% | LR: 0.000014
Epoch: 038 | Train loss: 0.9982 | Train acc: 50.63% | Val loss: 0.9956 | Val acc: 53.33% | LR: 0.000014
Epoch: 039 | Train loss: 0.9975 | Train acc: 50.88% | Val loss: 0.9955 | Val acc: 53.33% | LR: 0.000014
Epoch: 040 | Train loss: 0.9958 | Train acc: 51.55% | Val loss: 0.9956 | Val acc: 53.39% | LR: 0.000013
Epoch: 041 | Train loss: 0.9967 | Train acc: 51.24% | Val loss: 0.9957 | Val acc: 53.15% | LR: 0.000013
Epoch: 042 | Train loss: 0.9982 | Train acc: 50.40% | Val loss: 0.9957 | Val acc: 52.97% | LR: 0.000013
Epoch: 043 | Train loss: 0.9982 | Train acc: 50.67% | Val loss: 0.9957 | Val acc: 52.65% | LR: 0.000013
Epoch: 044 | Train loss: 0.9975 | Train acc: 50.72% | Val loss: 0.9957 | Val acc: 52.65% | LR: 0.000013
Epoch: 045 | Train loss: 0.9963 | Train acc: 51.10% | Val loss: 0.9958 | Val acc: 52.47% | LR: 0.000013
Epoch: 046 | Train loss: 0.9963 | Train acc: 50.90% | Val loss: 0.9959 | Val acc: 52.33% | LR: 0.000013
Epoch: 047 | Train loss: 0.9962 | Train acc: 51.17% | Val loss: 0.9958 | Val acc: 52.36% | LR: 0.000013
Epoch: 048 | Train loss: 0.9959 | Train acc: 51.09% | Val loss: 0.9958 | Val acc: 52.38% | LR: 0.000012
Epoch: 049 | Train loss: 0.9971 | Train acc: 50.74% | Val loss: 0.9958 | Val acc: 52.46% | LR: 0.000012
Epoch: 050 | Train loss: 0.9972 | Train acc: 50.66% | Val loss: 0.9957 | Val acc: 52.44% | LR: 0.000012
Epoch: 051 | Train loss: 0.9973 | Train acc: 50.75% | Val loss: 0.9956 | Val acc: 52.46% | LR: 0.000012
Epoch: 052 | Train loss: 0.9960 | Train acc: 50.93% | Val loss: 0.9956 | Val acc: 52.54% | LR: 0.000012
Epoch: 053 | Train loss: 0.9958 | Train acc: 50.85% | Val loss: 0.9956 | Val acc: 52.45% | LR: 0.000012
Epoch: 054 | Train loss: 0.9951 | Train acc: 51.21% | Val loss: 0.9956 | Val acc: 52.39% | LR: 0.000012
Epoch: 055 | Train loss: 0.9955 | Train acc: 50.96% | Val loss: 0.9955 | Val acc: 52.29% | LR: 0.000011
Epoch: 056 | Train loss: 0.9970 | Train acc: 50.71% | Val loss: 0.9955 | Val acc: 52.25% | LR: 0.000011
Epoch: 057 | Train loss: 0.9964 | Train acc: 50.72% | Val loss: 0.9956 | Val acc: 52.19% | LR: 0.000011
Epoch: 058 | Train loss: 0.9949 | Train acc: 50.98% | Val loss: 0.9955 | Val acc: 52.05% | LR: 0.000011
Epoch: 059 | Train loss: 0.9985 | Train acc: 50.27% | Val loss: 0.9955 | Val acc: 52.09% | LR: 0.000011
Epoch: 060 | Train loss: 0.9947 | Train acc: 50.90% | Val loss: 0.9954 | Val acc: 51.97% | LR: 0.000011
Epoch: 061 | Train loss: 0.9958 | Train acc: 50.55% | Val loss: 0.9954 | Val acc: 51.97% | LR: 0.000011
Epoch: 062 | Train loss: 0.9935 | Train acc: 51.24% | Val loss: 0.9954 | Val acc: 51.95% | LR: 0.000010

[I 2025-09-23 19:15:04,102] Trial 153 finished with value: 0.5202531576156616 and parameters: {'lr': 1.5990438991545583e-05, 'hidden_size': 68, 'dropout': 0.22737400538335942, 'weight_decay': 4.422015777714017e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 0.9957 | Train acc: 50.68% | Val loss: 0.9921 | Val acc: 54.31% | LR: 0.000014
Epoch: 001 | Train loss: 0.9984 | Train acc: 50.25% | Val loss: 0.9912 | Val acc: 54.40% | LR: 0.000014
Epoch: 002 | Train loss: 0.9958 | Train acc: 50.43% | Val loss: 0.9919 | Val acc: 54.32% | LR: 0.000014
Epoch: 003 | Train loss: 0.9970 | Train acc: 50.50% | Val loss: 0.9915 | Val acc: 54.42% | LR: 0.000014
Epoch: 004 | Train loss: 0.9969 | Train acc: 50.18% | Val loss: 0.9911 | Val acc: 54.36% | LR: 0.000014
Epoch: 005 | Train loss: 0.9916 | Train acc: 50.94% | Val loss: 0.9910 | Val acc: 54.24% | LR: 0.000014
Epoch: 006 | Train loss: 0.9985 | Train acc: 49.96% | Val loss: 0.9906 | Val acc: 54.30% | LR: 0.000014
Epoch: 007 | Train loss: 0.9935 | Train acc: 50.67% | Val loss: 0.9915 | Val acc: 54.24% | LR: 0.000014
Epoch: 008 | Train loss: 0.9969 | Train acc: 50.22% | Val loss: 0.9910 | Val acc: 54.21% | LR: 0.000014
Epoch: 009 | Train loss: 0.9974 | Train acc: 50.06% | Val loss: 0.9906 | Val acc: 54.25% | LR: 0.000014
Epoch: 010 | Train loss: 0.9915 | Train acc: 50.88% | Val loss: 0.9903 | Val acc: 54.53% | LR: 0.000014
Epoch: 011 | Train loss: 0.9929 | Train acc: 50.56% | Val loss: 0.9902 | Val acc: 54.53% | LR: 0.000014
Epoch: 012 | Train loss: 0.9921 | Train acc: 50.74% | Val loss: 0.9899 | Val acc: 54.64% | LR: 0.000014
Epoch: 013 | Train loss: 0.9951 | Train acc: 50.35% | Val loss: 0.9899 | Val acc: 54.58% | LR: 0.000014
Epoch: 014 | Train loss: 0.9919 | Train acc: 50.81% | Val loss: 0.9898 | Val acc: 54.51% | LR: 0.000014
Epoch: 015 | Train loss: 0.9905 | Train acc: 50.82% | Val loss: 0.9894 | Val acc: 54.49% | LR: 0.000014
Epoch: 016 | Train loss: 0.9910 | Train acc: 50.89% | Val loss: 0.9892 | Val acc: 54.55% | LR: 0.000014
Epoch: 017 | Train loss: 1.0215 | Train acc: 50.47% | Val loss: 0.9898 | Val acc: 54.66% | LR: 0.000014
Epoch: 018 | Train loss: 0.9913 | Train acc: 50.91% | Val loss: 0.9894 | Val acc: 54.70% | LR: 0.000014
Epoch: 019 | Train loss: 0.9925 | Train acc: 50.93% | Val loss: 0.9885 | Val acc: 54.68% | LR: 0.000014
Epoch: 020 | Train loss: 0.9945 | Train acc: 50.68% | Val loss: 0.9888 | Val acc: 54.60% | LR: 0.000014
Epoch: 021 | Train loss: 0.9904 | Train acc: 50.92% | Val loss: 1.0277 | Val acc: 54.63% | LR: 0.000013
Epoch: 022 | Train loss: 0.9945 | Train acc: 50.67% | Val loss: 0.9883 | Val acc: 54.53% | LR: 0.000013
Epoch: 023 | Train loss: 0.9962 | Train acc: 50.60% | Val loss: 0.9881 | Val acc: 54.57% | LR: 0.000013
Epoch: 024 | Train loss: 0.9938 | Train acc: 50.59% | Val loss: 0.9880 | Val acc: 54.56% | LR: 0.000013
Epoch: 025 | Train loss: 0.9905 | Train acc: 50.77% | Val loss: 0.9876 | Val acc: 54.54% | LR: 0.000013
Epoch: 026 | Train loss: 0.9935 | Train acc: 50.55% | Val loss: 0.9877 | Val acc: 54.37% | LR: 0.000013
Epoch: 027 | Train loss: 0.9942 | Train acc: 50.48% | Val loss: 0.9874 | Val acc: 54.49% | LR: 0.000013
Epoch: 028 | Train loss: 0.9952 | Train acc: 50.30% | Val loss: 0.9873 | Val acc: 54.57% | LR: 0.000013
Epoch: 029 | Train loss: 0.9959 | Train acc: 50.30% | Val loss: 0.9875 | Val acc: 54.39% | LR: 0.000013
Epoch: 030 | Train loss: 0.9911 | Train acc: 51.02% | Val loss: 0.9863 | Val acc: 54.39% | LR: 0.000013
Epoch: 031 | Train loss: 0.9877 | Train acc: 51.41% | Val loss: 0.9866 | Val acc: 54.32% | LR: 0.000013
Epoch: 032 | Train loss: 0.9941 | Train acc: 50.69% | Val loss: 0.9867 | Val acc: 54.26% | LR: 0.000013
Epoch: 033 | Train loss: 0.9905 | Train acc: 50.77% | Val loss: 0.9863 | Val acc: 54.22% | LR: 0.000013
Epoch: 034 | Train loss: 0.9909 | Train acc: 50.98% | Val loss: 0.9860 | Val acc: 54.18% | LR: 0.000012
Epoch: 035 | Train loss: 0.9936 | Train acc: 50.62% | Val loss: 0.9856 | Val acc: 54.22% | LR: 0.000012
Epoch: 036 | Train loss: 1.0014 | Train acc: 51.08% | Val loss: 0.9855 | Val acc: 54.32% | LR: 0.000012
Epoch: 037 | Train loss: 0.9944 | Train acc: 50.44% | Val loss: 0.9854 | Val acc: 54.36% | LR: 0.000012
Epoch: 038 | Train loss: 0.9947 | Train acc: 50.50% | Val loss: 0.9852 | Val acc: 54.36% | LR: 0.000012
Epoch: 039 | Train loss: 0.9899 | Train acc: 51.12% | Val loss: 0.9850 | Val acc: 54.30% | LR: 0.000012
Epoch: 040 | Train loss: 0.9870 | Train acc: 51.30% | Val loss: 0.9847 | Val acc: 54.33% | LR: 0.000012
Epoch: 041 | Train loss: 0.9988 | Train acc: 50.35% | Val loss: 0.9844 | Val acc: 54.23% | LR: 0.000012
Epoch: 042 | Train loss: 0.9916 | Train acc: 50.95% | Val loss: 0.9841 | Val acc: 54.11% | LR: 0.000012
Epoch: 043 | Train loss: 0.9942 | Train acc: 50.70% | Val loss: 0.9838 | Val acc: 53.99% | LR: 0.000012
Epoch: 044 | Train loss: 0.9872 | Train acc: 51.14% | Val loss: 0.9835 | Val acc: 53.95% | LR: 0.000011
Epoch: 045 | Train loss: 0.9922 | Train acc: 51.13% | Val loss: 0.9834 | Val acc: 53.95% | LR: 0.000011
Epoch: 046 | Train loss: 1.0105 | Train acc: 50.07% | Val loss: 0.9833 | Val acc: 53.93% | LR: 0.000011
Epoch: 047 | Train loss: 0.9965 | Train acc: 50.34% | Val loss: 0.9831 | Val acc: 53.81% | LR: 0.000011
Epoch: 048 | Train loss: 0.9925 | Train acc: 50.78% | Val loss: 0.9830 | Val acc: 53.72% | LR: 0.000011
Epoch: 049 | Train loss: 0.9938 | Train acc: 50.71% | Val loss: 0.9830 | Val acc: 53.75% | LR: 0.000011
Epoch: 050 | Train loss: 0.9965 | Train acc: 50.57% | Val loss: 0.9829 | Val acc: 53.77% | LR: 0.000011
Epoch: 051 | Train loss: 1.0270 | Train acc: 50.91% | Val loss: 0.9828 | Val acc: 53.77% | LR: 0.000011
Epoch: 052 | Train loss: 0.9916 | Train acc: 50.96% | Val loss: 0.9828 | Val acc: 53.71% | LR: 0.000011
Epoch: 053 | Train loss: 1.0051 | Train acc: 50.65% | Val loss: 0.9826 | Val acc: 53.73% | LR: 0.000010
Epoch: 054 | Train loss: 0.9990 | Train acc: 50.73% | Val loss: 0.9824 | Val acc: 53.75% | LR: 0.000010
Epoch: 055 | Train loss: 0.9967 | Train acc: 50.24% | Val loss: 0.9822 | Val acc: 53.73% | LR: 0.000010
Epoch: 056 | Train loss: 1.0033 | Train acc: 50.13% | Val loss: 0.9820 | Val acc: 53.69% | LR: 0.000010
Epoch: 057 | Train loss: 1.0335 | Train acc: 50.89% | Val loss: 0.9820 | Val acc: 53.69% | LR: 0.000010
Epoch: 058 | Train loss: 0.9912 | Train acc: 51.21% | Val loss: 0.9820 | Val acc: 53.71% | LR: 0.000010
Epoch: 059 | Train loss: 1.0086 | Train acc: 50.82% | Val loss: 0.9820 | Val acc: 53.67% | LR: 0.000010
Epoch: 060 | Train loss: 0.9913 | Train acc: 51.03% | Val loss: 0.9820 | Val acc: 53.71% | LR: 0.000009
Epoch: 061 | Train loss: 0.9934 | Train acc: 50.85% | Val loss: 0.9819 | Val acc: 53.71% | LR: 0.000009
Epoch: 062 | Train loss: 1.0312 | Train acc: 50.80% | Val loss: 0.9819 | Val acc: 53.71% | LR: 0.000009
Epoch: 063 | Train loss: 0.9937 | Train acc: 50.73% | Val loss: 0.9819 | Val acc: 53.67% | LR: 0.000009
Epoch: 064 | Train loss: 0.9886 | Train acc: 51.25% | Val loss: 0.9818 | Val acc: 53.71% | LR: 0.000009
Epoch: 065 | Train loss: 0.9908 | Train acc: 51.14% | Val loss: 0.9816 | Val acc: 53.73% | LR: 0.000009
Epoch: 066 | Train loss: 0.9954 | Train acc: 50.88% | Val loss: 0.9814 | Val acc: 53.73% | LR: 0.000009
Epoch: 067 | Train loss: 1.0370 | Train acc: 50.82% | Val loss: 0.9814 | Val acc: 53.69% | LR: 0.000009

[I 2025-09-23 19:16:01,917] Trial 154 finished with value: 0.5369217872619629 and parameters: {'lr': 1.4174504704138596e-05, 'hidden_size': 86, 'dropout': 0.23891933758898376, 'weight_decay': 2.939493248213659e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0025 | Train acc: 50.28% | Val loss: 1.0293 | Val acc: 47.38% | LR: 0.000019
Epoch: 001 | Train loss: 1.0085 | Train acc: 49.76% | Val loss: 1.0065 | Val acc: 47.10% | LR: 0.000019
Epoch: 002 | Train loss: 1.0003 | Train acc: 50.19% | Val loss: 1.0094 | Val acc: 47.33% | LR: 0.000019
Epoch: 003 | Train loss: 0.9995 | Train acc: 50.67% | Val loss: 1.0148 | Val acc: 47.41% | LR: 0.000019
Epoch: 004 | Train loss: 0.9996 | Train acc: 50.28% | Val loss: 1.0092 | Val acc: 47.52% | LR: 0.000018
Epoch: 005 | Train loss: 1.0004 | Train acc: 50.28% | Val loss: 1.0140 | Val acc: 47.34% | LR: 0.000018
Epoch: 006 | Train loss: 0.9990 | Train acc: 50.56% | Val loss: 1.0151 | Val acc: 47.45% | LR: 0.000018
Epoch: 007 | Train loss: 1.0045 | Train acc: 50.26% | Val loss: 1.0238 | Val acc: 47.24% | LR: 0.000018
Epoch: 008 | Train loss: 1.0071 | Train acc: 50.74% | Val loss: 1.0136 | Val acc: 47.29% | LR: 0.000018
Epoch: 009 | Train loss: 0.9993 | Train acc: 51.10% | Val loss: 1.0201 | Val acc: 47.29% | LR: 0.000018
Epoch: 010 | Train loss: 0.9979 | Train acc: 50.58% | Val loss: 1.0040 | Val acc: 47.67% | LR: 0.000018
Epoch: 011 | Train loss: 0.9984 | Train acc: 50.48% | Val loss: 1.2498 | Val acc: 47.17% | LR: 0.000018
Epoch: 012 | Train loss: 1.0022 | Train acc: 50.66% | Val loss: 1.0102 | Val acc: 47.25% | LR: 0.000018
Epoch: 013 | Train loss: 0.9988 | Train acc: 50.28% | Val loss: 1.0106 | Val acc: 47.24% | LR: 0.000018
Epoch: 014 | Train loss: 1.0254 | Train acc: 50.54% | Val loss: 1.0082 | Val acc: 47.36% | LR: 0.000018
Epoch: 015 | Train loss: 0.9995 | Train acc: 50.29% | Val loss: 1.0059 | Val acc: 47.32% | LR: 0.000018
Epoch: 016 | Train loss: 0.9982 | Train acc: 50.42% | Val loss: 1.0057 | Val acc: 47.34% | LR: 0.000018
Epoch: 017 | Train loss: 1.0006 | Train acc: 50.29% | Val loss: 1.0047 | Val acc: 47.68% | LR: 0.000018
Epoch: 018 | Train loss: 0.9952 | Train acc: 50.89% | Val loss: 1.0068 | Val acc: 47.61% | LR: 0.000018
Epoch: 019 | Train loss: 0.9992 | Train acc: 50.20% | Val loss: 1.0049 | Val acc: 47.70% | LR: 0.000018
Epoch: 020 | Train loss: 0.9993 | Train acc: 50.07% | Val loss: 1.0133 | Val acc: 47.74% | LR: 0.000018
Epoch: 021 | Train loss: 1.0009 | Train acc: 49.78% | Val loss: 1.0038 | Val acc: 47.60% | LR: 0.000018
Epoch: 022 | Train loss: 0.9997 | Train acc: 50.31% | Val loss: 1.0065 | Val acc: 47.56% | LR: 0.000018
Epoch: 023 | Train loss: 0.9996 | Train acc: 50.16% | Val loss: 1.0041 | Val acc: 47.62% | LR: 0.000017
Epoch: 024 | Train loss: 1.0000 | Train acc: 50.20% | Val loss: 1.0064 | Val acc: 47.62% | LR: 0.000017
Epoch: 025 | Train loss: 0.9976 | Train acc: 50.56% | Val loss: 1.0044 | Val acc: 47.64% | LR: 0.000017
Epoch: 026 | Train loss: 0.9989 | Train acc: 50.12% | Val loss: 1.0264 | Val acc: 47.66% | LR: 0.000017
Epoch: 027 | Train loss: 1.0008 | Train acc: 50.11% | Val loss: 1.0057 | Val acc: 47.56% | LR: 0.000017
Epoch: 028 | Train loss: 0.9983 | Train acc: 50.29% | Val loss: 1.0039 | Val acc: 47.86% | LR: 0.000017
Epoch: 029 | Train loss: 1.0006 | Train acc: 49.85% | Val loss: 1.0172 | Val acc: 47.70% | LR: 0.000017
Epoch: 030 | Train loss: 0.9978 | Train acc: 50.56% | Val loss: 1.0041 | Val acc: 47.68% | LR: 0.000017
Epoch: 031 | Train loss: 0.9988 | Train acc: 50.41% | Val loss: 1.0032 | Val acc: 47.60% | LR: 0.000017
Epoch: 032 | Train loss: 1.0001 | Train acc: 50.11% | Val loss: 1.0049 | Val acc: 47.60% | LR: 0.000017
Epoch: 033 | Train loss: 0.9989 | Train acc: 50.24% | Val loss: 1.0063 | Val acc: 47.40% | LR: 0.000016
Epoch: 034 | Train loss: 0.9969 | Train acc: 50.67% | Val loss: 1.0057 | Val acc: 47.41% | LR: 0.000016
Epoch: 035 | Train loss: 0.9977 | Train acc: 50.44% | Val loss: 1.0108 | Val acc: 47.47% | LR: 0.000016
Epoch: 036 | Train loss: 0.9941 | Train acc: 51.15% | Val loss: 1.0061 | Val acc: 47.21% | LR: 0.000016
Epoch: 037 | Train loss: 0.9977 | Train acc: 50.26% | Val loss: 1.0043 | Val acc: 47.30% | LR: 0.000016
Epoch: 038 | Train loss: 0.9966 | Train acc: 50.75% | Val loss: 1.0058 | Val acc: 47.40% | LR: 0.000016
Epoch: 039 | Train loss: 0.9993 | Train acc: 50.19% | Val loss: 1.0054 | Val acc: 47.29% | LR: 0.000016
Epoch: 040 | Train loss: 0.9952 | Train acc: 50.86% | Val loss: 1.0174 | Val acc: 47.38% | LR: 0.000016
Epoch: 041 | Train loss: 0.9993 | Train acc: 50.30% | Val loss: 1.0097 | Val acc: 47.46% | LR: 0.000015
Epoch: 042 | Train loss: 1.0020 | Train acc: 49.79% | Val loss: 1.0072 | Val acc: 47.43% | LR: 0.000015
Epoch: 043 | Train loss: 0.9999 | Train acc: 50.20% | Val loss: 1.0114 | Val acc: 47.16% | LR: 0.000015
Epoch: 044 | Train loss: 0.9978 | Train acc: 50.29% | Val loss: 1.0070 | Val acc: 47.50% | LR: 0.000015
Epoch: 045 | Train loss: 1.0070 | Train acc: 50.76% | Val loss: 1.0035 | Val acc: 47.27% | LR: 0.000015
Epoch: 046 | Train loss: 0.9954 | Train acc: 50.87% | Val loss: 1.0067 | Val acc: 47.26% | LR: 0.000015
Epoch: 047 | Train loss: 1.0109 | Train acc: 50.09% | Val loss: 1.0043 | Val acc: 47.44% | LR: 0.000014
Epoch: 048 | Train loss: 0.9966 | Train acc: 50.50% | Val loss: 1.0061 | Val acc: 47.34% | LR: 0.000014
Epoch: 049 | Train loss: 0.9969 | Train acc: 50.41% | Val loss: 1.0071 | Val acc: 47.25% | LR: 0.000014
Epoch: 050 | Train loss: 0.9971 | Train acc: 50.37% | Val loss: 1.0142 | Val acc: 46.99% | LR: 0.000014
Epoch: 051 | Train loss: 0.9996 | Train acc: 49.92% | Val loss: 1.0045 | Val acc: 47.34% | LR: 0.000014
Epoch: 052 | Train loss: 0.9974 | Train acc: 50.23% | Val loss: 1.0042 | Val acc: 47.60% | LR: 0.000014
Epoch: 053 | Train loss: 0.9991 | Train acc: 50.20% | Val loss: 1.0325 | Val acc: 47.28% | LR: 0.000014
Epoch: 054 | Train loss: 0.9965 | Train acc: 50.34% | Val loss: 1.0049 | Val acc: 47.34% | LR: 0.000013
Epoch: 055 | Train loss: 0.9953 | Train acc: 50.69% | Val loss: 1.0044 | Val acc: 47.29% | LR: 0.000013
Epoch: 056 | Train loss: 0.9978 | Train acc: 50.16% | Val loss: 1.0042 | Val acc: 47.34% | LR: 0.000013
Epoch: 057 | Train loss: 0.9993 | Train acc: 49.80% | Val loss: 1.0056 | Val acc: 47.36% | LR: 0.000013
Epoch: 058 | Train loss: 0.9973 | Train acc: 50.24% | Val loss: 1.0047 | Val acc: 47.21% | LR: 0.000013
Epoch: 059 | Train loss: 0.9977 | Train acc: 50.15% | Val loss: 1.0051 | Val acc: 47.24% | LR: 0.000012
Epoch: 060 | Train loss: 0.9997 | Train acc: 50.07% | Val loss: 1.0052 | Val acc: 47.29% | LR: 0.000012
Epoch: 061 | Train loss: 0.9980 | Train acc: 50.34% | Val loss: 1.0050 | Val acc: 47.39% | LR: 0.000012
Epoch: 062 | Train loss: 0.9936 | Train acc: 50.72% | Val loss: 1.0053 | Val acc: 47.39% | LR: 0.000012
Epoch: 063 | Train loss: 0.9988 | Train acc: 50.09% | Val loss: 1.0050 | Val acc: 47.45% | LR: 0.000012
Epoch: 064 | Train loss: 0.9962 | Train acc: 50.44% | Val loss: 1.0042 | Val acc: 47.42% | LR: 0.000012
Epoch: 065 | Train loss: 0.9928 | Train acc: 50.80% | Val loss: 1.0043 | Val acc: 47.54% | LR: 0.000011
Epoch: 066 | Train loss: 1.0057 | Train acc: 50.29% | Val loss: 1.0045 | Val acc: 47.47% | LR: 0.000011
Epoch: 067 | Train loss: 0.9992 | Train acc: 50.09% | Val loss: 1.0041 | Val acc: 47.55% | LR: 0.000011
Epoch: 068 | Train loss: 0.9963 | Train acc: 50.45% | Val loss: 1.0043 | Val acc: 47.48% | LR: 0.000011
Epoch: 069 | Train loss: 0.9980 | Train acc: 50.02% | Val loss: 1.0048 | Val acc: 47.60% | LR: 0.000011
Epoch: 070 | Train loss: 0.9957 | Train acc: 50.47% | Val loss: 1.0063 | Val acc: 47.58% | LR: 0.000011
Epoch: 071 | Train loss: 0.9991 | Train acc: 50.05% | Val loss: 1.0037 | Val acc: 47.68% | LR: 0.000010
Epoch: 072 | Train loss: 0.9981 | Train acc: 50.34% | Val loss: 1.0043 | Val acc: 47.62% | LR: 0.000010
Epoch: 073 | Train loss: 0.9940 | Train acc: 50.63% | Val loss: 1.0045 | Val acc: 47.50% | LR: 0.000010
Epoch: 074 | Train loss: 0.9973 | Train acc: 50.26% | Val loss: 1.0052 | Val acc: 47.60% | LR: 0.000010
Epoch: 075 | Train loss: 0.9921 | Train acc: 50.90% | Val loss: 1.0040 | Val acc: 47.68% | LR: 0.000010
Epoch: 076 | Train loss: 0.9955 | Train acc: 50.45% | Val loss: 1.0045 | Val acc: 47.54% | LR: 0.000009
Epoch: 077 | Train loss: 0.9957 | Train acc: 50.47% | Val loss: 1.0044 | Val acc: 47.64% | LR: 0.000009

[I 2025-09-23 19:17:06,262] Trial 155 finished with value: 0.4758182466030121 and parameters: {'lr': 1.8544093792677862e-05, 'hidden_size': 79, 'dropout': 0.2546276379927468, 'weight_decay': 5.415901482270155e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0006 | Train acc: 49.77% | Val loss: 1.0091 | Val acc: 45.81% | LR: 0.000011
Epoch: 001 | Train loss: 1.0008 | Train acc: 49.46% | Val loss: 1.0059 | Val acc: 45.92% | LR: 0.000011
Epoch: 002 | Train loss: 1.0003 | Train acc: 49.47% | Val loss: 1.0059 | Val acc: 45.93% | LR: 0.000011
Epoch: 003 | Train loss: 1.0008 | Train acc: 49.65% | Val loss: 1.0106 | Val acc: 46.02% | LR: 0.000011
Epoch: 004 | Train loss: 0.9999 | Train acc: 49.82% | Val loss: 1.0064 | Val acc: 46.03% | LR: 0.000011
Epoch: 005 | Train loss: 1.0005 | Train acc: 49.30% | Val loss: 1.0055 | Val acc: 46.13% | LR: 0.000011
Epoch: 006 | Train loss: 1.0003 | Train acc: 49.44% | Val loss: 1.0048 | Val acc: 46.23% | LR: 0.000011
Epoch: 007 | Train loss: 1.0003 | Train acc: 49.71% | Val loss: 1.0054 | Val acc: 46.29% | LR: 0.000011
Epoch: 008 | Train loss: 1.0005 | Train acc: 49.84% | Val loss: 1.0074 | Val acc: 46.15% | LR: 0.000011
Epoch: 009 | Train loss: 0.9997 | Train acc: 50.24% | Val loss: 1.0095 | Val acc: 45.99% | LR: 0.000011
Epoch: 010 | Train loss: 0.9999 | Train acc: 49.91% | Val loss: 1.0074 | Val acc: 46.20% | LR: 0.000011
Epoch: 011 | Train loss: 1.0012 | Train acc: 49.03% | Val loss: 1.0062 | Val acc: 46.11% | LR: 0.000011
Epoch: 012 | Train loss: 1.0000 | Train acc: 50.45% | Val loss: 1.0044 | Val acc: 46.07% | LR: 0.000011
Epoch: 013 | Train loss: 1.0005 | Train acc: 49.02% | Val loss: 1.0082 | Val acc: 46.17% | LR: 0.000011
Epoch: 014 | Train loss: 1.0024 | Train acc: 49.34% | Val loss: 1.0050 | Val acc: 46.11% | LR: 0.000011
Epoch: 015 | Train loss: 1.0000 | Train acc: 49.94% | Val loss: 1.0059 | Val acc: 46.04% | LR: 0.000011
Epoch: 016 | Train loss: 1.0001 | Train acc: 49.84% | Val loss: 1.0056 | Val acc: 46.03% | LR: 0.000011
Epoch: 017 | Train loss: 0.9996 | Train acc: 50.13% | Val loss: 1.0057 | Val acc: 46.09% | LR: 0.000011
Epoch: 018 | Train loss: 1.0003 | Train acc: 49.62% | Val loss: 1.0095 | Val acc: 46.03% | LR: 0.000011
Epoch: 019 | Train loss: 1.0001 | Train acc: 49.41% | Val loss: 1.0066 | Val acc: 46.13% | LR: 0.000011
Epoch: 020 | Train loss: 0.9997 | Train acc: 49.95% | Val loss: 1.0062 | Val acc: 46.07% | LR: 0.000011
Epoch: 021 | Train loss: 0.9999 | Train acc: 49.55% | Val loss: 1.0060 | Val acc: 46.20% | LR: 0.000011
Epoch: 022 | Train loss: 1.0000 | Train acc: 49.82% | Val loss: 1.0060 | Val acc: 45.99% | LR: 0.000011
Epoch: 023 | Train loss: 0.9999 | Train acc: 49.35% | Val loss: 1.0103 | Val acc: 46.05% | LR: 0.000010
Epoch: 024 | Train loss: 0.9997 | Train acc: 50.05% | Val loss: 1.0075 | Val acc: 46.05% | LR: 0.000010
Epoch: 025 | Train loss: 1.0000 | Train acc: 49.73% | Val loss: 1.0057 | Val acc: 46.19% | LR: 0.000010
Epoch: 026 | Train loss: 0.9997 | Train acc: 50.24% | Val loss: 1.0052 | Val acc: 46.09% | LR: 0.000010
Epoch: 027 | Train loss: 1.0000 | Train acc: 49.80% | Val loss: 1.0046 | Val acc: 46.03% | LR: 0.000010
Epoch: 028 | Train loss: 0.9998 | Train acc: 50.02% | Val loss: 1.0063 | Val acc: 45.99% | LR: 0.000010
Epoch: 029 | Train loss: 1.0001 | Train acc: 49.81% | Val loss: 1.0051 | Val acc: 46.05% | LR: 0.000010
Epoch: 030 | Train loss: 0.9997 | Train acc: 50.15% | Val loss: 1.0048 | Val acc: 46.17% | LR: 0.000010
Epoch: 031 | Train loss: 0.9994 | Train acc: 50.49% | Val loss: 1.0086 | Val acc: 46.13% | LR: 0.000010
Epoch: 032 | Train loss: 0.9993 | Train acc: 50.76% | Val loss: 1.0055 | Val acc: 46.05% | LR: 0.000010
Epoch: 033 | Train loss: 0.9992 | Train acc: 50.67% | Val loss: 1.0051 | Val acc: 46.15% | LR: 0.000010
Epoch: 034 | Train loss: 0.9996 | Train acc: 50.26% | Val loss: 1.0053 | Val acc: 46.03% | LR: 0.000010
Epoch: 035 | Train loss: 0.9997 | Train acc: 50.44% | Val loss: 1.0050 | Val acc: 46.13% | LR: 0.000010
Epoch: 036 | Train loss: 0.9992 | Train acc: 50.85% | Val loss: 1.0055 | Val acc: 46.13% | LR: 0.000010
Epoch: 037 | Train loss: 0.9996 | Train acc: 50.31% | Val loss: 1.0051 | Val acc: 46.15% | LR: 0.000010
Epoch: 038 | Train loss: 0.9989 | Train acc: 50.77% | Val loss: 1.0049 | Val acc: 46.07% | LR: 0.000010
Epoch: 039 | Train loss: 0.9997 | Train acc: 50.22% | Val loss: 1.0057 | Val acc: 46.15% | LR: 0.000009
Epoch: 040 | Train loss: 0.9988 | Train acc: 50.76% | Val loss: 1.0053 | Val acc: 46.05% | LR: 0.000009
Epoch: 041 | Train loss: 0.9993 | Train acc: 50.50% | Val loss: 1.0054 | Val acc: 46.09% | LR: 0.000009
Epoch: 042 | Train loss: 0.9996 | Train acc: 50.30% | Val loss: 1.0063 | Val acc: 46.05% | LR: 0.000009
Epoch: 043 | Train loss: 0.9986 | Train acc: 50.76% | Val loss: 1.0116 | Val acc: 46.05% | LR: 0.000009
Epoch: 044 | Train loss: 0.9986 | Train acc: 50.95% | Val loss: 1.0058 | Val acc: 46.03% | LR: 0.000009
Epoch: 045 | Train loss: 0.9989 | Train acc: 50.57% | Val loss: 1.0049 | Val acc: 46.15% | LR: 0.000009
Epoch: 046 | Train loss: 0.9993 | Train acc: 50.32% | Val loss: 1.0061 | Val acc: 46.09% | LR: 0.000009
Epoch: 047 | Train loss: 0.9989 | Train acc: 50.58% | Val loss: 1.0059 | Val acc: 45.99% | LR: 0.000009
Epoch: 048 | Train loss: 0.9996 | Train acc: 50.16% | Val loss: 1.0083 | Val acc: 45.95% | LR: 0.000009
Epoch: 049 | Train loss: 0.9993 | Train acc: 50.32% | Val loss: 1.0057 | Val acc: 46.03% | LR: 0.000009
Epoch: 050 | Train loss: 0.9979 | Train acc: 51.13% | Val loss: 1.0052 | Val acc: 46.09% | LR: 0.000008
Epoch: 051 | Train loss: 0.9983 | Train acc: 50.94% | Val loss: 1.0108 | Val acc: 45.92% | LR: 0.000008
Epoch: 052 | Train loss: 0.9997 | Train acc: 50.22% | Val loss: 1.0058 | Val acc: 46.06% | LR: 0.000008
Epoch: 053 | Train loss: 0.9991 | Train acc: 50.34% | Val loss: 1.0055 | Val acc: 46.13% | LR: 0.000008
Epoch: 054 | Train loss: 0.9990 | Train acc: 50.42% | Val loss: 1.0093 | Val acc: 46.01% | LR: 0.000008
Epoch: 055 | Train loss: 0.9983 | Train acc: 50.75% | Val loss: 1.0074 | Val acc: 46.03% | LR: 0.000008
Epoch: 056 | Train loss: 0.9986 | Train acc: 50.58% | Val loss: 1.0062 | Val acc: 46.07% | LR: 0.000008

[I 2025-09-23 19:17:57,090] Trial 156 finished with value: 0.4607153654098511 and parameters: {'lr': 1.1113856843327957e-05, 'hidden_size': 72, 'dropout': 0.18950928851194598, 'weight_decay': 1.8316629133760373e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 0.9998 | Train acc: 50.37% | Val loss: 1.0065 | Val acc: 46.06% | LR: 0.000023
Epoch: 001 | Train loss: 0.9992 | Train acc: 50.37% | Val loss: 1.0076 | Val acc: 46.12% | LR: 0.000023
Epoch: 002 | Train loss: 0.9999 | Train acc: 49.78% | Val loss: 1.0077 | Val acc: 46.13% | LR: 0.000023
Epoch: 003 | Train loss: 0.9985 | Train acc: 50.62% | Val loss: 1.0065 | Val acc: 46.20% | LR: 0.000023
Epoch: 004 | Train loss: 1.0012 | Train acc: 50.86% | Val loss: 1.0057 | Val acc: 46.16% | LR: 0.000023
Epoch: 005 | Train loss: 0.9982 | Train acc: 50.64% | Val loss: 1.0081 | Val acc: 45.94% | LR: 0.000023
Epoch: 006 | Train loss: 0.9986 | Train acc: 50.16% | Val loss: 1.0117 | Val acc: 46.56% | LR: 0.000023
Epoch: 007 | Train loss: 1.0009 | Train acc: 50.54% | Val loss: 1.0060 | Val acc: 46.56% | LR: 0.000023
Epoch: 008 | Train loss: 0.9995 | Train acc: 50.19% | Val loss: 1.0087 | Val acc: 46.46% | LR: 0.000023
Epoch: 009 | Train loss: 0.9983 | Train acc: 50.91% | Val loss: 1.0059 | Val acc: 46.28% | LR: 0.000023
Epoch: 010 | Train loss: 1.0004 | Train acc: 49.91% | Val loss: 1.0090 | Val acc: 46.34% | LR: 0.000023
Epoch: 011 | Train loss: 0.9999 | Train acc: 50.13% | Val loss: 1.0073 | Val acc: 46.38% | LR: 0.000023
Epoch: 012 | Train loss: 0.9988 | Train acc: 50.56% | Val loss: 1.0099 | Val acc: 46.39% | LR: 0.000023
Epoch: 013 | Train loss: 0.9989 | Train acc: 50.38% | Val loss: 1.0190 | Val acc: 46.35% | LR: 0.000023
Epoch: 014 | Train loss: 0.9974 | Train acc: 50.88% | Val loss: 1.0081 | Val acc: 46.45% | LR: 0.000023
Epoch: 015 | Train loss: 0.9988 | Train acc: 50.22% | Val loss: 1.0065 | Val acc: 46.40% | LR: 0.000023
Epoch: 016 | Train loss: 0.9974 | Train acc: 50.84% | Val loss: 1.0057 | Val acc: 46.40% | LR: 0.000023
Epoch: 017 | Train loss: 0.9970 | Train acc: 50.84% | Val loss: 1.0075 | Val acc: 46.07% | LR: 0.000023
Epoch: 018 | Train loss: 1.0059 | Train acc: 50.13% | Val loss: 1.0072 | Val acc: 46.24% | LR: 0.000023
Epoch: 019 | Train loss: 0.9972 | Train acc: 50.75% | Val loss: 1.0074 | Val acc: 46.14% | LR: 0.000022
Epoch: 020 | Train loss: 0.9969 | Train acc: 50.76% | Val loss: 1.0070 | Val acc: 46.10% | LR: 0.000022
Epoch: 021 | Train loss: 0.9980 | Train acc: 50.40% | Val loss: 1.0071 | Val acc: 46.16% | LR: 0.000022
Epoch: 022 | Train loss: 0.9984 | Train acc: 50.22% | Val loss: 1.0453 | Val acc: 46.12% | LR: 0.000022
Epoch: 023 | Train loss: 0.9978 | Train acc: 50.31% | Val loss: 1.0069 | Val acc: 46.12% | LR: 0.000022
Epoch: 024 | Train loss: 0.9968 | Train acc: 50.74% | Val loss: 1.0072 | Val acc: 46.07% | LR: 0.000022
Epoch: 025 | Train loss: 0.9959 | Train acc: 50.86% | Val loss: 1.0073 | Val acc: 46.11% | LR: 0.000022
Epoch: 026 | Train loss: 0.9965 | Train acc: 50.61% | Val loss: 1.0068 | Val acc: 45.87% | LR: 0.000022
Epoch: 027 | Train loss: 0.9970 | Train acc: 50.50% | Val loss: 1.0093 | Val acc: 45.99% | LR: 0.000022
Epoch: 028 | Train loss: 0.9984 | Train acc: 50.12% | Val loss: 1.0064 | Val acc: 46.04% | LR: 0.000021
Epoch: 029 | Train loss: 0.9972 | Train acc: 50.65% | Val loss: 1.0074 | Val acc: 46.08% | LR: 0.000021
Epoch: 030 | Train loss: 0.9947 | Train acc: 50.91% | Val loss: 1.0064 | Val acc: 45.91% | LR: 0.000021
Epoch: 031 | Train loss: 0.9985 | Train acc: 50.38% | Val loss: 1.0069 | Val acc: 45.99% | LR: 0.000021
Epoch: 032 | Train loss: 0.9963 | Train acc: 50.49% | Val loss: 1.0063 | Val acc: 46.03% | LR: 0.000021
Epoch: 033 | Train loss: 0.9999 | Train acc: 49.75% | Val loss: 1.0172 | Val acc: 46.04% | LR: 0.000021
Epoch: 034 | Train loss: 0.9987 | Train acc: 50.11% | Val loss: 1.0096 | Val acc: 45.92% | LR: 0.000021
Epoch: 035 | Train loss: 0.9979 | Train acc: 50.23% | Val loss: 1.0191 | Val acc: 46.13% | LR: 0.000020
Epoch: 036 | Train loss: 0.9975 | Train acc: 50.50% | Val loss: 1.0066 | Val acc: 46.09% | LR: 0.000020
Epoch: 037 | Train loss: 0.9961 | Train acc: 50.81% | Val loss: 1.0283 | Val acc: 45.91% | LR: 0.000020
Epoch: 038 | Train loss: 0.9985 | Train acc: 49.96% | Val loss: 1.0067 | Val acc: 45.98% | LR: 0.000020
Epoch: 039 | Train loss: 0.9983 | Train acc: 50.01% | Val loss: 1.0059 | Val acc: 46.13% | LR: 0.000020
Epoch: 040 | Train loss: 0.9974 | Train acc: 50.76% | Val loss: 1.0066 | Val acc: 46.04% | LR: 0.000020
Epoch: 041 | Train loss: 0.9986 | Train acc: 50.39% | Val loss: 1.0254 | Val acc: 45.97% | LR: 0.000019
Epoch: 042 | Train loss: 0.9959 | Train acc: 50.49% | Val loss: 1.0114 | Val acc: 46.09% | LR: 0.000019
Epoch: 043 | Train loss: 0.9952 | Train acc: 50.57% | Val loss: 1.0077 | Val acc: 45.99% | LR: 0.000019
Epoch: 044 | Train loss: 0.9970 | Train acc: 50.30% | Val loss: 1.0101 | Val acc: 46.03% | LR: 0.000019
Epoch: 045 | Train loss: 0.9957 | Train acc: 50.57% | Val loss: 1.0065 | Val acc: 46.09% | LR: 0.000019
Epoch: 046 | Train loss: 0.9929 | Train acc: 51.01% | Val loss: 1.0117 | Val acc: 45.95% | LR: 0.000018
Epoch: 047 | Train loss: 0.9976 | Train acc: 50.12% | Val loss: 1.0085 | Val acc: 46.05% | LR: 0.000018
Epoch: 048 | Train loss: 0.9947 | Train acc: 50.64% | Val loss: 1.0078 | Val acc: 46.03% | LR: 0.000018
Epoch: 049 | Train loss: 0.9949 | Train acc: 50.47% | Val loss: 1.0097 | Val acc: 46.05% | LR: 0.000018
Epoch: 050 | Train loss: 0.9981 | Train acc: 50.12% | Val loss: 1.0072 | Val acc: 46.01% | LR: 0.000018
Epoch: 051 | Train loss: 0.9935 | Train acc: 50.74% | Val loss: 1.0093 | Val acc: 45.99% | LR: 0.000017
Epoch: 052 | Train loss: 0.9994 | Train acc: 49.73% | Val loss: 1.0079 | Val acc: 45.99% | LR: 0.000017
Epoch: 053 | Train loss: 0.9990 | Train acc: 50.07% | Val loss: 1.0074 | Val acc: 45.93% | LR: 0.000017
Epoch: 054 | Train loss: 0.9944 | Train acc: 50.74% | Val loss: 1.0076 | Val acc: 46.05% | LR: 0.000017
Epoch: 055 | Train loss: 1.0001 | Train acc: 49.84% | Val loss: 1.0070 | Val acc: 46.11% | LR: 0.000017
Epoch: 056 | Train loss: 0.9990 | Train acc: 49.85% | Val loss: 1.0079 | Val acc: 46.01% | LR: 0.000016

[I 2025-09-23 19:18:43,967] Trial 157 finished with value: 0.46033754348754885 and parameters: {'lr': 2.3387699895960976e-05, 'hidden_size': 67, 'dropout': 0.49589085910849134, 'weight_decay': 1.3915002795689896e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0069 | Train acc: 50.33% | Val loss: 1.0011 | Val acc: 50.46% | LR: 0.000017
Epoch: 001 | Train loss: 1.0124 | Train acc: 49.79% | Val loss: 1.0031 | Val acc: 50.41% | LR: 0.000017
Epoch: 002 | Train loss: 1.3380 | Train acc: 49.59% | Val loss: 1.0046 | Val acc: 50.44% | LR: 0.000017
Epoch: 003 | Train loss: 1.0351 | Train acc: 50.32% | Val loss: 1.0017 | Val acc: 50.26% | LR: 0.000017
Epoch: 004 | Train loss: 1.0029 | Train acc: 49.75% | Val loss: 1.0039 | Val acc: 50.36% | LR: 0.000017
Epoch: 005 | Train loss: 1.0031 | Train acc: 49.62% | Val loss: 0.9992 | Val acc: 50.73% | LR: 0.000017
Epoch: 006 | Train loss: 1.0009 | Train acc: 49.80% | Val loss: 1.0031 | Val acc: 50.22% | LR: 0.000017
Epoch: 007 | Train loss: 1.0001 | Train acc: 49.84% | Val loss: 1.0022 | Val acc: 50.38% | LR: 0.000017
Epoch: 008 | Train loss: 1.0008 | Train acc: 49.40% | Val loss: 0.9996 | Val acc: 50.33% | LR: 0.000017
Epoch: 009 | Train loss: 1.0011 | Train acc: 49.02% | Val loss: 0.9995 | Val acc: 50.42% | LR: 0.000016
Epoch: 010 | Train loss: 0.9999 | Train acc: 50.10% | Val loss: 1.0211 | Val acc: 50.57% | LR: 0.000016
Epoch: 011 | Train loss: 1.0002 | Train acc: 50.08% | Val loss: 0.9980 | Val acc: 50.51% | LR: 0.000016
Epoch: 012 | Train loss: 1.0013 | Train acc: 50.29% | Val loss: 0.9993 | Val acc: 50.54% | LR: 0.000016
Epoch: 013 | Train loss: 1.0098 | Train acc: 49.63% | Val loss: 1.0014 | Val acc: 50.62% | LR: 0.000016
Epoch: 014 | Train loss: 0.9991 | Train acc: 50.30% | Val loss: 1.0002 | Val acc: 50.87% | LR: 0.000016
Epoch: 015 | Train loss: 0.9995 | Train acc: 49.75% | Val loss: 0.9991 | Val acc: 50.88% | LR: 0.000016
Epoch: 016 | Train loss: 0.9997 | Train acc: 50.19% | Val loss: 1.0001 | Val acc: 50.35% | LR: 0.000016
Epoch: 017 | Train loss: 1.0002 | Train acc: 50.04% | Val loss: 0.9997 | Val acc: 51.28% | LR: 0.000016
Epoch: 018 | Train loss: 0.9989 | Train acc: 50.61% | Val loss: 1.0009 | Val acc: 51.09% | LR: 0.000016
Epoch: 019 | Train loss: 0.9989 | Train acc: 50.64% | Val loss: 1.0056 | Val acc: 50.74% | LR: 0.000016
Epoch: 020 | Train loss: 0.9988 | Train acc: 50.93% | Val loss: 1.0007 | Val acc: 50.79% | LR: 0.000016
Epoch: 021 | Train loss: 0.9983 | Train acc: 50.72% | Val loss: 1.0009 | Val acc: 50.37% | LR: 0.000016
Epoch: 022 | Train loss: 0.9998 | Train acc: 50.20% | Val loss: 1.0006 | Val acc: 50.36% | LR: 0.000016
Epoch: 023 | Train loss: 0.9981 | Train acc: 51.04% | Val loss: 1.0004 | Val acc: 50.18% | LR: 0.000016
Epoch: 024 | Train loss: 0.9988 | Train acc: 50.74% | Val loss: 1.0005 | Val acc: 50.03% | LR: 0.000016
Epoch: 025 | Train loss: 0.9975 | Train acc: 51.11% | Val loss: 1.0006 | Val acc: 50.07% | LR: 0.000016
Epoch: 026 | Train loss: 0.9976 | Train acc: 50.98% | Val loss: 0.9989 | Val acc: 50.05% | LR: 0.000015
Epoch: 027 | Train loss: 0.9988 | Train acc: 50.50% | Val loss: 1.0005 | Val acc: 49.53% | LR: 0.000015
Epoch: 028 | Train loss: 1.0009 | Train acc: 50.29% | Val loss: 0.9999 | Val acc: 49.91% | LR: 0.000015
Epoch: 029 | Train loss: 0.9984 | Train acc: 50.34% | Val loss: 1.0079 | Val acc: 49.64% | LR: 0.000015
Epoch: 030 | Train loss: 0.9974 | Train acc: 50.85% | Val loss: 1.0004 | Val acc: 49.77% | LR: 0.000015
Epoch: 031 | Train loss: 0.9976 | Train acc: 50.78% | Val loss: 1.0006 | Val acc: 49.73% | LR: 0.000015
Epoch: 032 | Train loss: 0.9971 | Train acc: 51.18% | Val loss: 1.0000 | Val acc: 50.03% | LR: 0.000015
Epoch: 033 | Train loss: 0.9967 | Train acc: 51.06% | Val loss: 1.0048 | Val acc: 50.06% | LR: 0.000015
Epoch: 034 | Train loss: 0.9967 | Train acc: 50.96% | Val loss: 0.9998 | Val acc: 50.24% | LR: 0.000015
Epoch: 035 | Train loss: 0.9995 | Train acc: 50.09% | Val loss: 0.9996 | Val acc: 50.29% | LR: 0.000015
Epoch: 036 | Train loss: 0.9973 | Train acc: 50.63% | Val loss: 1.0031 | Val acc: 50.17% | LR: 0.000014
Epoch: 037 | Train loss: 0.9995 | Train acc: 49.99% | Val loss: 1.0006 | Val acc: 49.74% | LR: 0.000014
Epoch: 038 | Train loss: 0.9953 | Train acc: 51.00% | Val loss: 0.9996 | Val acc: 50.37% | LR: 0.000014
Epoch: 039 | Train loss: 0.9979 | Train acc: 50.35% | Val loss: 1.0001 | Val acc: 49.86% | LR: 0.000014
Epoch: 040 | Train loss: 0.9980 | Train acc: 50.36% | Val loss: 0.9996 | Val acc: 49.96% | LR: 0.000014
Epoch: 041 | Train loss: 0.9995 | Train acc: 50.21% | Val loss: 1.0004 | Val acc: 49.87% | LR: 0.000014
Epoch: 042 | Train loss: 1.0007 | Train acc: 50.19% | Val loss: 0.9987 | Val acc: 50.11% | LR: 0.000014
Epoch: 043 | Train loss: 0.9986 | Train acc: 50.55% | Val loss: 1.0002 | Val acc: 50.25% | LR: 0.000014
Epoch: 044 | Train loss: 0.9974 | Train acc: 50.65% | Val loss: 0.9995 | Val acc: 50.41% | LR: 0.000013
Epoch: 045 | Train loss: 0.9961 | Train acc: 50.98% | Val loss: 0.9998 | Val acc: 50.21% | LR: 0.000013
Epoch: 046 | Train loss: 0.9999 | Train acc: 50.93% | Val loss: 0.9997 | Val acc: 50.33% | LR: 0.000013
Epoch: 047 | Train loss: 0.9973 | Train acc: 50.53% | Val loss: 1.0000 | Val acc: 50.27% | LR: 0.000013
Epoch: 048 | Train loss: 1.0468 | Train acc: 51.23% | Val loss: 0.9996 | Val acc: 50.43% | LR: 0.000013
Epoch: 049 | Train loss: 1.0122 | Train acc: 50.98% | Val loss: 0.9996 | Val acc: 50.25% | LR: 0.000013
Epoch: 050 | Train loss: 0.9992 | Train acc: 50.91% | Val loss: 1.0001 | Val acc: 50.12% | LR: 0.000013
Epoch: 051 | Train loss: 0.9953 | Train acc: 51.16% | Val loss: 1.0007 | Val acc: 50.20% | LR: 0.000012
Epoch: 052 | Train loss: 0.9981 | Train acc: 50.72% | Val loss: 1.0020 | Val acc: 50.12% | LR: 0.000012
Epoch: 053 | Train loss: 0.9981 | Train acc: 50.49% | Val loss: 1.0027 | Val acc: 50.01% | LR: 0.000012
Epoch: 054 | Train loss: 1.0120 | Train acc: 50.47% | Val loss: 1.0034 | Val acc: 50.13% | LR: 0.000012
Epoch: 055 | Train loss: 0.9962 | Train acc: 50.87% | Val loss: 1.0088 | Val acc: 49.71% | LR: 0.000012
Epoch: 056 | Train loss: 0.9981 | Train acc: 50.63% | Val loss: 1.0053 | Val acc: 50.24% | LR: 0.000012
Epoch: 057 | Train loss: 0.9953 | Train acc: 51.06% | Val loss: 1.0008 | Val acc: 50.54% | LR: 0.000012
Epoch: 058 | Train loss: 0.9993 | Train acc: 50.61% | Val loss: 1.0051 | Val acc: 50.08% | LR: 0.000011
Epoch: 059 | Train loss: 0.9954 | Train acc: 50.90% | Val loss: 1.0038 | Val acc: 49.78% | LR: 0.000011
Epoch: 060 | Train loss: 0.9969 | Train acc: 50.69% | Val loss: 1.0004 | Val acc: 50.21% | LR: 0.000011
Epoch: 061 | Train loss: 0.9976 | Train acc: 50.63% | Val loss: 1.0021 | Val acc: 50.21% | LR: 0.000011
Epoch: 062 | Train loss: 0.9980 | Train acc: 50.57% | Val loss: 1.0015 | Val acc: 50.26% | LR: 0.000011
Epoch: 063 | Train loss: 0.9977 | Train acc: 50.36% | Val loss: 1.0082 | Val acc: 50.14% | LR: 0.000011
Epoch: 064 | Train loss: 0.9963 | Train acc: 50.53% | Val loss: 1.0016 | Val acc: 50.41% | LR: 0.000010
Epoch: 065 | Train loss: 0.9961 | Train acc: 50.60% | Val loss: 1.0020 | Val acc: 50.23% | LR: 0.000010
Epoch: 066 | Train loss: 0.9977 | Train acc: 50.42% | Val loss: 1.0080 | Val acc: 49.69% | LR: 0.000010

[I 2025-09-23 19:20:40,240] Trial 158 finished with value: 0.5000304877758026 and parameters: {'lr': 1.665609187081006e-05, 'hidden_size': 172, 'dropout': 0.2754828079271543, 'weight_decay': 2.210521026932248e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0005 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.05% | LR: 0.000012
Epoch: 001 | Train loss: 1.0010 | Train acc: 49.73% | Val loss: 0.9917 | Val acc: 54.11% | LR: 0.000012
Epoch: 002 | Train loss: 0.9999 | Train acc: 50.24% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000012
Epoch: 003 | Train loss: 0.9992 | Train acc: 50.53% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000012
Epoch: 004 | Train loss: 0.9997 | Train acc: 50.18% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000012
Epoch: 005 | Train loss: 0.9977 | Train acc: 50.87% | Val loss: 0.9918 | Val acc: 54.15% | LR: 0.000012
Epoch: 006 | Train loss: 0.9984 | Train acc: 50.52% | Val loss: 0.9918 | Val acc: 54.17% | LR: 0.000012
Epoch: 007 | Train loss: 0.9994 | Train acc: 49.98% | Val loss: 0.9919 | Val acc: 54.22% | LR: 0.000012
Epoch: 008 | Train loss: 0.9999 | Train acc: 49.72% | Val loss: 0.9920 | Val acc: 54.34% | LR: 0.000012
Epoch: 009 | Train loss: 0.9980 | Train acc: 50.60% | Val loss: 0.9920 | Val acc: 54.28% | LR: 0.000012
Epoch: 010 | Train loss: 0.9976 | Train acc: 50.78% | Val loss: 0.9921 | Val acc: 54.26% | LR: 0.000012
Epoch: 011 | Train loss: 0.9973 | Train acc: 50.87% | Val loss: 0.9920 | Val acc: 54.28% | LR: 0.000012
Epoch: 012 | Train loss: 0.9976 | Train acc: 50.69% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000012
Epoch: 013 | Train loss: 0.9972 | Train acc: 50.43% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000012
Epoch: 014 | Train loss: 0.9980 | Train acc: 50.44% | Val loss: 0.9919 | Val acc: 54.26% | LR: 0.000012
Epoch: 015 | Train loss: 0.9977 | Train acc: 50.15% | Val loss: 0.9919 | Val acc: 54.28% | LR: 0.000012
Epoch: 016 | Train loss: 1.0122 | Train acc: 50.81% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000012
Epoch: 017 | Train loss: 0.9967 | Train acc: 50.47% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000012
Epoch: 018 | Train loss: 1.0148 | Train acc: 50.12% | Val loss: 0.9919 | Val acc: 54.32% | LR: 0.000012
Epoch: 019 | Train loss: 1.0073 | Train acc: 50.60% | Val loss: 0.9920 | Val acc: 54.32% | LR: 0.000012
Epoch: 020 | Train loss: 1.1420 | Train acc: 51.09% | Val loss: 0.9920 | Val acc: 54.32% | LR: 0.000012
Epoch: 021 | Train loss: 1.0099 | Train acc: 50.70% | Val loss: 0.9919 | Val acc: 54.32% | LR: 0.000012
Epoch: 022 | Train loss: 1.0029 | Train acc: 50.73% | Val loss: 0.9919 | Val acc: 54.34% | LR: 0.000012
Epoch: 023 | Train loss: 1.0312 | Train acc: 50.20% | Val loss: 0.9919 | Val acc: 54.34% | LR: 0.000012
Epoch: 024 | Train loss: 0.9978 | Train acc: 50.55% | Val loss: 0.9919 | Val acc: 54.34% | LR: 0.000012
Epoch: 025 | Train loss: 1.0002 | Train acc: 50.01% | Val loss: 0.9919 | Val acc: 54.36% | LR: 0.000012
Epoch: 026 | Train loss: 0.9991 | Train acc: 50.47% | Val loss: 0.9918 | Val acc: 54.34% | LR: 0.000012
Epoch: 027 | Train loss: 0.9975 | Train acc: 50.80% | Val loss: 0.9918 | Val acc: 54.44% | LR: 0.000012
Epoch: 028 | Train loss: 0.9968 | Train acc: 50.78% | Val loss: 0.9918 | Val acc: 54.40% | LR: 0.000011
Epoch: 029 | Train loss: 0.9982 | Train acc: 50.80% | Val loss: 0.9917 | Val acc: 54.40% | LR: 0.000011
Epoch: 030 | Train loss: 0.9983 | Train acc: 50.42% | Val loss: 0.9916 | Val acc: 54.34% | LR: 0.000011
Epoch: 031 | Train loss: 0.9980 | Train acc: 50.31% | Val loss: 0.9915 | Val acc: 54.30% | LR: 0.000011
Epoch: 032 | Train loss: 0.9972 | Train acc: 51.06% | Val loss: 0.9914 | Val acc: 54.24% | LR: 0.000011
Epoch: 033 | Train loss: 0.9997 | Train acc: 49.91% | Val loss: 0.9914 | Val acc: 54.20% | LR: 0.000011
Epoch: 034 | Train loss: 0.9965 | Train acc: 51.00% | Val loss: 0.9914 | Val acc: 54.42% | LR: 0.000011
Epoch: 035 | Train loss: 0.9986 | Train acc: 50.38% | Val loss: 0.9913 | Val acc: 54.44% | LR: 0.000011
Epoch: 036 | Train loss: 0.9983 | Train acc: 50.47% | Val loss: 0.9914 | Val acc: 54.26% | LR: 0.000011
Epoch: 037 | Train loss: 0.9987 | Train acc: 50.38% | Val loss: 0.9937 | Val acc: 54.30% | LR: 0.000011
Epoch: 038 | Train loss: 1.0025 | Train acc: 50.27% | Val loss: 0.9913 | Val acc: 54.43% | LR: 0.000011
Epoch: 039 | Train loss: 0.9973 | Train acc: 50.84% | Val loss: 0.9913 | Val acc: 54.41% | LR: 0.000011
Epoch: 040 | Train loss: 0.9973 | Train acc: 50.78% | Val loss: 0.9912 | Val acc: 54.33% | LR: 0.000010
Epoch: 041 | Train loss: 0.9986 | Train acc: 50.71% | Val loss: 0.9913 | Val acc: 54.37% | LR: 0.000010
Epoch: 042 | Train loss: 0.9986 | Train acc: 50.35% | Val loss: 0.9913 | Val acc: 54.50% | LR: 0.000010
Epoch: 043 | Train loss: 0.9980 | Train acc: 50.45% | Val loss: 0.9913 | Val acc: 54.52% | LR: 0.000010
Epoch: 044 | Train loss: 0.9987 | Train acc: 50.30% | Val loss: 0.9913 | Val acc: 54.52% | LR: 0.000010
Epoch: 045 | Train loss: 0.9977 | Train acc: 50.64% | Val loss: 0.9913 | Val acc: 54.46% | LR: 0.000010
Epoch: 046 | Train loss: 0.9965 | Train acc: 50.99% | Val loss: 1.0695 | Val acc: 54.40% | LR: 0.000010
Epoch: 047 | Train loss: 0.9985 | Train acc: 50.19% | Val loss: 0.9931 | Val acc: 54.37% | LR: 0.000010
Epoch: 048 | Train loss: 0.9978 | Train acc: 50.65% | Val loss: 0.9913 | Val acc: 54.37% | LR: 0.000010
Epoch: 049 | Train loss: 0.9979 | Train acc: 50.58% | Val loss: 0.9913 | Val acc: 54.40% | LR: 0.000010
Epoch: 050 | Train loss: 0.9985 | Train acc: 50.44% | Val loss: 0.9912 | Val acc: 54.38% | LR: 0.000010
Epoch: 051 | Train loss: 0.9974 | Train acc: 50.61% | Val loss: 0.9912 | Val acc: 54.40% | LR: 0.000009
Epoch: 052 | Train loss: 0.9985 | Train acc: 50.52% | Val loss: 0.9915 | Val acc: 54.46% | LR: 0.000009
Epoch: 053 | Train loss: 0.9984 | Train acc: 50.34% | Val loss: 0.9914 | Val acc: 54.46% | LR: 0.000009
Epoch: 054 | Train loss: 0.9996 | Train acc: 50.77% | Val loss: 0.9917 | Val acc: 54.52% | LR: 0.000009
Epoch: 055 | Train loss: 0.9967 | Train acc: 50.80% | Val loss: 0.9952 | Val acc: 54.54% | LR: 0.000009
Epoch: 056 | Train loss: 0.9963 | Train acc: 50.97% | Val loss: 0.9927 | Val acc: 54.52% | LR: 0.000009
Epoch: 057 | Train loss: 0.9976 | Train acc: 50.47% | Val loss: 0.9918 | Val acc: 54.50% | LR: 0.000009
Epoch: 058 | Train loss: 0.9983 | Train acc: 50.53% | Val loss: 0.9912 | Val acc: 54.35% | LR: 0.000009
Epoch: 059 | Train loss: 0.9969 | Train acc: 50.98% | Val loss: 0.9911 | Val acc: 54.31% | LR: 0.000009
Epoch: 060 | Train loss: 0.9970 | Train acc: 50.73% | Val loss: 0.9912 | Val acc: 54.31% | LR: 0.000008
Epoch: 061 | Train loss: 0.9978 | Train acc: 50.48% | Val loss: 0.9910 | Val acc: 54.45% | LR: 0.000008
Epoch: 062 | Train loss: 0.9978 | Train acc: 50.58% | Val loss: 0.9912 | Val acc: 54.66% | LR: 0.000008
Epoch: 063 | Train loss: 0.9983 | Train acc: 50.48% | Val loss: 0.9911 | Val acc: 54.52% | LR: 0.000008
Epoch: 064 | Train loss: 0.9980 | Train acc: 50.85% | Val loss: 0.9913 | Val acc: 54.62% | LR: 0.000008
Epoch: 065 | Train loss: 0.9969 | Train acc: 50.83% | Val loss: 0.9913 | Val acc: 54.70% | LR: 0.000008
Epoch: 066 | Train loss: 0.9983 | Train acc: 50.30% | Val loss: 0.9912 | Val acc: 54.66% | LR: 0.000008
Epoch: 067 | Train loss: 0.9959 | Train acc: 51.38% | Val loss: 0.9913 | Val acc: 54.68% | LR: 0.000008
Epoch: 068 | Train loss: 0.9971 | Train acc: 50.84% | Val loss: 0.9911 | Val acc: 54.62% | LR: 0.000007
Epoch: 069 | Train loss: 0.9978 | Train acc: 50.59% | Val loss: 0.9913 | Val acc: 54.70% | LR: 0.000007
Epoch: 070 | Train loss: 0.9961 | Train acc: 51.04% | Val loss: 0.9911 | Val acc: 54.68% | LR: 0.000007
Epoch: 071 | Train loss: 0.9973 | Train acc: 50.79% | Val loss: 0.9912 | Val acc: 54.64% | LR: 0.000007
Epoch: 072 | Train loss: 0.9965 | Train acc: 50.77% | Val loss: 0.9911 | Val acc: 54.65% | LR: 0.000007
Epoch: 073 | Train loss: 0.9986 | Train acc: 50.07% | Val loss: 0.9916 | Val acc: 54.54% | LR: 0.000007
Epoch: 074 | Train loss: 0.9953 | Train acc: 51.32% | Val loss: 1.0015 | Val acc: 54.59% | LR: 0.000007
Epoch: 075 | Train loss: 0.9954 | Train acc: 51.15% | Val loss: 0.9911 | Val acc: 54.63% | LR: 0.000007
Epoch: 076 | Train loss: 0.9981 | Train acc: 50.43% | Val loss: 0.9910 | Val acc: 54.69% | LR: 0.000006
Epoch: 077 | Train loss: 0.9977 | Train acc: 50.36% | Val loss: 0.9913 | Val acc: 54.69% | LR: 0.000006
Epoch: 078 | Train loss: 0.9965 | Train acc: 50.69% | Val loss: 0.9914 | Val acc: 54.59% | LR: 0.000006
Epoch: 079 | Train loss: 0.9982 | Train acc: 50.79% | Val loss: 0.9914 | Val acc: 54.67% | LR: 0.000006
Epoch: 080 | Train loss: 0.9960 | Train acc: 51.12% | Val loss: 0.9915 | Val acc: 54.49% | LR: 0.000006
Epoch: 081 | Train loss: 0.9965 | Train acc: 50.67% | Val loss: 0.9915 | Val acc: 54.57% | LR: 0.000006
Epoch: 082 | Train loss: 0.9953 | Train acc: 51.38% | Val loss: 0.9916 | Val acc: 54.57% | LR: 0.000006
Epoch: 083 | Train loss: 0.9969 | Train acc: 50.38% | Val loss: 0.9909 | Val acc: 54.57% | LR: 0.000006
Epoch: 084 | Train loss: 0.9956 | Train acc: 50.87% | Val loss: 0.9914 | Val acc: 54.49% | LR: 0.000006
Epoch: 085 | Train loss: 0.9977 | Train acc: 50.32% | Val loss: 0.9912 | Val acc: 54.57% | LR: 0.000005
Epoch: 086 | Train loss: 0.9977 | Train acc: 50.66% | Val loss: 0.9920 | Val acc: 54.61% | LR: 0.000005
Epoch: 087 | Train loss: 0.9948 | Train acc: 50.70% | Val loss: 0.9911 | Val acc: 54.61% | LR: 0.000005
Epoch: 088 | Train loss: 1.0009 | Train acc: 50.71% | Val loss: 0.9915 | Val acc: 54.59% | LR: 0.000005
Epoch: 089 | Train loss: 0.9963 | Train acc: 50.54% | Val loss: 0.9971 | Val acc: 54.55% | LR: 0.000005
Epoch: 090 | Train loss: 0.9983 | Train acc: 50.83% | Val loss: 0.9915 | Val acc: 54.53% | LR: 0.000005
Epoch: 091 | Train loss: 0.9933 | Train acc: 50.94% | Val loss: 0.9915 | Val acc: 54.53% | LR: 0.000005
Epoch: 092 | Train loss: 0.9957 | Train acc: 50.58% | Val loss: 0.9932 | Val acc: 54.53% | LR: 0.000005
Epoch: 093 | Train loss: 0.9943 | Train acc: 50.84% | Val loss: 0.9963 | Val acc: 54.51% | LR: 0.000005
Epoch: 094 | Train loss: 0.9919 | Train acc: 51.21% | Val loss: 0.9919 | Val acc: 54.43% | LR: 0.000004
Epoch: 095 | Train loss: 0.9995 | Train acc: 50.88% | Val loss: 0.9918 | Val acc: 54.39% | LR: 0.000004
Epoch: 096 | Train loss: 0.9923 | Train acc: 50.94% | Val loss: 0.9934 | Val acc: 54.51% | LR: 0.000004
Epoch: 097 | Train loss: 1.0068 | Train acc: 50.67% | Val loss: 0.9919 | Val acc: 54.47% | LR: 0.000004
Epoch: 098 | Train loss: 1.0024 | Train acc: 50.94% | Val loss: 0.9911 | Val acc: 54.53% | LR: 0.000004
Epoch: 099 | Train loss: 0.9949 | Train acc: 51.04% | Val loss: 0.9923 | Val acc: 54.51% | LR: 0.000004
Epoch: 100 | Train loss: 0.9928 | Train acc: 50.50% | Val loss: 0.9931 | Val acc: 54.47% | LR: 0.000004
Epoch: 101 | Train loss: 0.9929 | Train acc: 50.96% | Val loss: 0.9949 | Val acc: 54.49% | LR: 0.000004
Epoch: 102 | Train loss: 0.9976 | Train acc: 50.85% | Val loss: 0.9917 | Val acc: 54.47% | LR: 0.000004
Epoch: 103 | Train loss: 0.9962 | Train acc: 50.87% | Val loss: 0.9938 | Val acc: 54.47% | LR: 0.000003
Epoch: 104 | Train loss: 0.9953 | Train acc: 50.52% | Val loss: 0.9921 | Val acc: 54.49% | LR: 0.000003
Epoch: 105 | Train loss: 0.9916 | Train acc: 51.10% | Val loss: 0.9919 | Val acc: 54.49% | LR: 0.000003
Epoch: 106 | Train loss: 0.9939 | Train acc: 50.87% | Val loss: 0.9920 | Val acc: 54.49% | LR: 0.000003
Epoch: 107 | Train loss: 0.9945 | Train acc: 51.05% | Val loss: 0.9944 | Val acc: 54.47% | LR: 0.000003
Epoch: 108 | Train loss: 0.9963 | Train acc: 50.13% | Val loss: 0.9949 | Val acc: 54.47% | LR: 0.000003
Epoch: 109 | Train loss: 0.9954 | Train acc: 50.83% | Val loss: 0.9922 | Val acc: 54.49% | LR: 0.000003
Epoch: 110 | Train loss: 0.9959 | Train acc: 50.57% | Val loss: 0.9921 | Val acc: 54.49% | LR: 0.000003
Epoch: 111 | Train loss: 0.9957 | Train acc: 50.81% | Val loss: 0.9914 | Val acc: 54.45% | LR: 0.000003
Epoch: 112 | Train loss: 0.9965 | Train acc: 50.30% | Val loss: 0.9921 | Val acc: 54.45% | LR: 0.000003
Epoch: 113 | Train loss: 0.9941 | Train acc: 50.34% | Val loss: 0.9933 | Val acc: 54.43% | LR: 0.000003
Epoch: 114 | Train loss: 1.2961 | Train acc: 50.39% | Val loss: 0.9966 | Val acc: 54.47% | LR: 0.000002

[I 2025-09-23 19:22:09,414] Trial 159 finished with value: 0.5447021842002868 and parameters: {'lr': 1.2474922422861322e-05, 'hidden_size': 64, 'dropout': 0.20869329480221382, 'weight_decay': 9.829706357156114e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0005 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.05% | LR: 0.000013
Epoch: 001 | Train loss: 1.0010 | Train acc: 49.73% | Val loss: 0.9917 | Val acc: 54.11% | LR: 0.000013
Epoch: 002 | Train loss: 1.0000 | Train acc: 50.23% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000013
Epoch: 003 | Train loss: 0.9991 | Train acc: 50.51% | Val loss: 0.9919 | Val acc: 54.13% | LR: 0.000013
Epoch: 004 | Train loss: 0.9997 | Train acc: 50.16% | Val loss: 0.9919 | Val acc: 54.13% | LR: 0.000013
Epoch: 005 | Train loss: 0.9979 | Train acc: 50.87% | Val loss: 0.9919 | Val acc: 54.17% | LR: 0.000013
Epoch: 006 | Train loss: 0.9986 | Train acc: 50.52% | Val loss: 0.9919 | Val acc: 54.24% | LR: 0.000013
Epoch: 007 | Train loss: 0.9996 | Train acc: 49.98% | Val loss: 0.9919 | Val acc: 54.26% | LR: 0.000013
Epoch: 008 | Train loss: 1.0000 | Train acc: 49.72% | Val loss: 0.9921 | Val acc: 54.34% | LR: 0.000013
Epoch: 009 | Train loss: 0.9982 | Train acc: 50.60% | Val loss: 0.9921 | Val acc: 54.26% | LR: 0.000013
Epoch: 010 | Train loss: 0.9978 | Train acc: 50.78% | Val loss: 0.9921 | Val acc: 54.26% | LR: 0.000013
Epoch: 011 | Train loss: 0.9975 | Train acc: 50.86% | Val loss: 0.9921 | Val acc: 54.30% | LR: 0.000013
Epoch: 012 | Train loss: 0.9978 | Train acc: 50.69% | Val loss: 0.9920 | Val acc: 54.28% | LR: 0.000013
Epoch: 013 | Train loss: 0.9976 | Train acc: 50.43% | Val loss: 0.9919 | Val acc: 54.28% | LR: 0.000013
Epoch: 014 | Train loss: 0.9984 | Train acc: 50.44% | Val loss: 0.9920 | Val acc: 54.28% | LR: 0.000013
Epoch: 015 | Train loss: 0.9982 | Train acc: 50.16% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000013
Epoch: 016 | Train loss: 0.9981 | Train acc: 50.61% | Val loss: 0.9920 | Val acc: 54.32% | LR: 0.000013
Epoch: 017 | Train loss: 0.9973 | Train acc: 50.49% | Val loss: 0.9920 | Val acc: 54.36% | LR: 0.000012
Epoch: 018 | Train loss: 0.9982 | Train acc: 50.10% | Val loss: 0.9919 | Val acc: 54.40% | LR: 0.000012
Epoch: 019 | Train loss: 1.0544 | Train acc: 50.12% | Val loss: 0.9917 | Val acc: 54.38% | LR: 0.000012
Epoch: 020 | Train loss: 0.9974 | Train acc: 51.14% | Val loss: 0.9918 | Val acc: 54.38% | LR: 0.000012
Epoch: 021 | Train loss: 0.9977 | Train acc: 50.59% | Val loss: 0.9917 | Val acc: 54.40% | LR: 0.000012
Epoch: 022 | Train loss: 0.9980 | Train acc: 50.79% | Val loss: 0.9916 | Val acc: 54.40% | LR: 0.000012
Epoch: 023 | Train loss: 0.9983 | Train acc: 50.36% | Val loss: 0.9916 | Val acc: 54.36% | LR: 0.000012
Epoch: 024 | Train loss: 0.9978 | Train acc: 50.33% | Val loss: 0.9919 | Val acc: 54.46% | LR: 0.000012
Epoch: 025 | Train loss: 0.9985 | Train acc: 50.04% | Val loss: 0.9913 | Val acc: 54.38% | LR: 0.000012
Epoch: 026 | Train loss: 0.9994 | Train acc: 50.25% | Val loss: 0.9916 | Val acc: 54.28% | LR: 0.000012
Epoch: 027 | Train loss: 1.0025 | Train acc: 50.77% | Val loss: 0.9915 | Val acc: 54.31% | LR: 0.000012
Epoch: 028 | Train loss: 0.9971 | Train acc: 50.74% | Val loss: 0.9915 | Val acc: 54.22% | LR: 0.000012
Epoch: 029 | Train loss: 0.9971 | Train acc: 50.74% | Val loss: 0.9915 | Val acc: 54.22% | LR: 0.000012
Epoch: 030 | Train loss: 0.9983 | Train acc: 50.37% | Val loss: 0.9908 | Val acc: 54.28% | LR: 0.000012
Epoch: 031 | Train loss: 0.9988 | Train acc: 50.32% | Val loss: 0.9928 | Val acc: 54.20% | LR: 0.000012
Epoch: 032 | Train loss: 0.9966 | Train acc: 51.08% | Val loss: 0.9915 | Val acc: 54.12% | LR: 0.000012
Epoch: 033 | Train loss: 0.9983 | Train acc: 49.92% | Val loss: 0.9914 | Val acc: 54.14% | LR: 0.000011
Epoch: 034 | Train loss: 0.9965 | Train acc: 50.90% | Val loss: 0.9919 | Val acc: 54.22% | LR: 0.000011
Epoch: 035 | Train loss: 0.9984 | Train acc: 50.34% | Val loss: 0.9920 | Val acc: 54.43% | LR: 0.000011
Epoch: 036 | Train loss: 0.9973 | Train acc: 50.52% | Val loss: 0.9915 | Val acc: 54.36% | LR: 0.000011
Epoch: 037 | Train loss: 0.9974 | Train acc: 50.41% | Val loss: 0.9915 | Val acc: 54.38% | LR: 0.000011
Epoch: 038 | Train loss: 0.9985 | Train acc: 50.29% | Val loss: 0.9939 | Val acc: 54.35% | LR: 0.000011
Epoch: 039 | Train loss: 0.9966 | Train acc: 50.80% | Val loss: 0.9920 | Val acc: 54.21% | LR: 0.000011
Epoch: 040 | Train loss: 0.9976 | Train acc: 50.72% | Val loss: 0.9917 | Val acc: 54.35% | LR: 0.000011
Epoch: 041 | Train loss: 0.9974 | Train acc: 50.20% | Val loss: 0.9912 | Val acc: 54.25% | LR: 0.000011
Epoch: 042 | Train loss: 0.9977 | Train acc: 50.35% | Val loss: 0.9915 | Val acc: 54.15% | LR: 0.000011
Epoch: 043 | Train loss: 0.9978 | Train acc: 50.87% | Val loss: 0.9911 | Val acc: 54.25% | LR: 0.000011
Epoch: 044 | Train loss: 0.9980 | Train acc: 50.62% | Val loss: 0.9915 | Val acc: 54.16% | LR: 0.000010
Epoch: 045 | Train loss: 0.9966 | Train acc: 51.09% | Val loss: 0.9924 | Val acc: 54.20% | LR: 0.000010
Epoch: 046 | Train loss: 0.9964 | Train acc: 50.32% | Val loss: 0.9916 | Val acc: 54.23% | LR: 0.000010
Epoch: 047 | Train loss: 0.9971 | Train acc: 50.57% | Val loss: 0.9915 | Val acc: 54.31% | LR: 0.000010
Epoch: 048 | Train loss: 0.9973 | Train acc: 50.65% | Val loss: 0.9916 | Val acc: 54.35% | LR: 0.000010
Epoch: 049 | Train loss: 0.9980 | Train acc: 50.39% | Val loss: 0.9926 | Val acc: 54.37% | LR: 0.000010
Epoch: 050 | Train loss: 1.0003 | Train acc: 50.09% | Val loss: 0.9911 | Val acc: 54.41% | LR: 0.000010
Epoch: 051 | Train loss: 0.9990 | Train acc: 50.39% | Val loss: 0.9914 | Val acc: 54.43% | LR: 0.000010
Epoch: 052 | Train loss: 0.9987 | Train acc: 50.46% | Val loss: 0.9914 | Val acc: 54.41% | LR: 0.000010
Epoch: 053 | Train loss: 0.9996 | Train acc: 50.29% | Val loss: 0.9916 | Val acc: 54.37% | LR: 0.000009
Epoch: 054 | Train loss: 0.9979 | Train acc: 50.73% | Val loss: 0.9908 | Val acc: 54.35% | LR: 0.000009
Epoch: 055 | Train loss: 0.9978 | Train acc: 50.74% | Val loss: 0.9911 | Val acc: 54.35% | LR: 0.000009
Epoch: 056 | Train loss: 0.9972 | Train acc: 50.89% | Val loss: 0.9915 | Val acc: 54.40% | LR: 0.000009
Epoch: 057 | Train loss: 0.9994 | Train acc: 50.36% | Val loss: 0.9909 | Val acc: 54.50% | LR: 0.000009
Epoch: 058 | Train loss: 0.9986 | Train acc: 50.47% | Val loss: 0.9911 | Val acc: 54.40% | LR: 0.000009
Epoch: 059 | Train loss: 0.9971 | Train acc: 51.01% | Val loss: 0.9915 | Val acc: 54.29% | LR: 0.000009
Epoch: 060 | Train loss: 0.9974 | Train acc: 50.63% | Val loss: 0.9915 | Val acc: 54.37% | LR: 0.000009
Epoch: 061 | Train loss: 0.9982 | Train acc: 50.38% | Val loss: 0.9918 | Val acc: 54.31% | LR: 0.000009
Epoch: 062 | Train loss: 0.9982 | Train acc: 50.47% | Val loss: 0.9918 | Val acc: 54.35% | LR: 0.000008
Epoch: 063 | Train loss: 0.9984 | Train acc: 50.38% | Val loss: 0.9917 | Val acc: 54.33% | LR: 0.000008
Epoch: 064 | Train loss: 0.9978 | Train acc: 50.74% | Val loss: 0.9919 | Val acc: 54.36% | LR: 0.000008
Epoch: 065 | Train loss: 0.9971 | Train acc: 50.67% | Val loss: 0.9913 | Val acc: 54.40% | LR: 0.000008
Epoch: 066 | Train loss: 0.9985 | Train acc: 50.25% | Val loss: 0.9916 | Val acc: 54.38% | LR: 0.000008
Epoch: 067 | Train loss: 0.9973 | Train acc: 51.22% | Val loss: 0.9916 | Val acc: 54.39% | LR: 0.000008
Epoch: 068 | Train loss: 0.9977 | Train acc: 50.78% | Val loss: 0.9916 | Val acc: 54.31% | LR: 0.000008
Epoch: 069 | Train loss: 1.0480 | Train acc: 50.70% | Val loss: 0.9915 | Val acc: 54.40% | LR: 0.000008
Epoch: 070 | Train loss: 0.9984 | Train acc: 50.95% | Val loss: 0.9964 | Val acc: 54.31% | LR: 0.000007
Epoch: 071 | Train loss: 1.0076 | Train acc: 50.74% | Val loss: 0.9926 | Val acc: 54.33% | LR: 0.000007
Epoch: 072 | Train loss: 1.0041 | Train acc: 50.44% | Val loss: 0.9912 | Val acc: 54.38% | LR: 0.000007
Epoch: 073 | Train loss: 1.0006 | Train acc: 50.14% | Val loss: 0.9915 | Val acc: 54.44% | LR: 0.000007
Epoch: 074 | Train loss: 0.9965 | Train acc: 51.33% | Val loss: 0.9917 | Val acc: 54.40% | LR: 0.000007
Epoch: 075 | Train loss: 0.9979 | Train acc: 51.12% | Val loss: 0.9915 | Val acc: 54.44% | LR: 0.000007
Epoch: 076 | Train loss: 1.1036 | Train acc: 50.20% | Val loss: 0.9915 | Val acc: 54.44% | LR: 0.000007
Epoch: 077 | Train loss: 1.0001 | Train acc: 50.31% | Val loss: 0.9916 | Val acc: 54.44% | LR: 0.000007
Epoch: 078 | Train loss: 1.0150 | Train acc: 50.68% | Val loss: 0.9911 | Val acc: 54.38% | LR: 0.000006
Epoch: 079 | Train loss: 1.0488 | Train acc: 50.69% | Val loss: 0.9915 | Val acc: 54.52% | LR: 0.000006
Epoch: 080 | Train loss: 0.9987 | Train acc: 51.11% | Val loss: 0.9913 | Val acc: 54.36% | LR: 0.000006
Epoch: 081 | Train loss: 1.0382 | Train acc: 50.47% | Val loss: 0.9914 | Val acc: 54.40% | LR: 0.000006
Epoch: 082 | Train loss: 1.0151 | Train acc: 51.17% | Val loss: 0.9915 | Val acc: 54.44% | LR: 0.000006
Epoch: 083 | Train loss: 1.0085 | Train acc: 50.28% | Val loss: 0.9920 | Val acc: 54.29% | LR: 0.000006
Epoch: 084 | Train loss: 1.0047 | Train acc: 50.66% | Val loss: 0.9912 | Val acc: 54.46% | LR: 0.000006
Epoch: 085 | Train loss: 1.0005 | Train acc: 50.22% | Val loss: 0.9913 | Val acc: 54.46% | LR: 0.000006
Epoch: 086 | Train loss: 0.9994 | Train acc: 50.56% | Val loss: 0.9912 | Val acc: 54.46% | LR: 0.000005
Epoch: 087 | Train loss: 0.9974 | Train acc: 50.67% | Val loss: 0.9914 | Val acc: 54.40% | LR: 0.000005
Epoch: 088 | Train loss: 0.9986 | Train acc: 50.56% | Val loss: 0.9919 | Val acc: 54.40% | LR: 0.000005
Epoch: 089 | Train loss: 1.0039 | Train acc: 50.60% | Val loss: 0.9920 | Val acc: 54.40% | LR: 0.000005
Epoch: 090 | Train loss: 0.9969 | Train acc: 50.75% | Val loss: 0.9915 | Val acc: 54.42% | LR: 0.000005
Epoch: 091 | Train loss: 1.0007 | Train acc: 50.68% | Val loss: 0.9915 | Val acc: 54.42% | LR: 0.000005
Epoch: 092 | Train loss: 0.9984 | Train acc: 50.46% | Val loss: 0.9917 | Val acc: 54.37% | LR: 0.000005
Epoch: 093 | Train loss: 0.9972 | Train acc: 50.89% | Val loss: 0.9916 | Val acc: 54.42% | LR: 0.000005
Epoch: 094 | Train loss: 0.9971 | Train acc: 50.99% | Val loss: 0.9918 | Val acc: 54.39% | LR: 0.000005
Epoch: 095 | Train loss: 0.9987 | Train acc: 50.62% | Val loss: 0.9915 | Val acc: 54.42% | LR: 0.000004
Epoch: 096 | Train loss: 0.9972 | Train acc: 50.78% | Val loss: 0.9917 | Val acc: 54.39% | LR: 0.000004
Epoch: 097 | Train loss: 1.0068 | Train acc: 50.45% | Val loss: 0.9916 | Val acc: 54.42% | LR: 0.000004
Epoch: 098 | Train loss: 0.9982 | Train acc: 50.79% | Val loss: 0.9917 | Val acc: 54.50% | LR: 0.000004
Epoch: 099 | Train loss: 0.9971 | Train acc: 50.88% | Val loss: 0.9918 | Val acc: 54.50% | LR: 0.000004
Epoch: 100 | Train loss: 0.9990 | Train acc: 50.42% | Val loss: 0.9917 | Val acc: 54.50% | LR: 0.000004
Epoch: 101 | Train loss: 1.0008 | Train acc: 50.70% | Val loss: 0.9916 | Val acc: 54.54% | LR: 0.000004
Epoch: 102 | Train loss: 0.9966 | Train acc: 50.87% | Val loss: 0.9917 | Val acc: 54.60% | LR: 0.000004
Epoch: 103 | Train loss: 1.0010 | Train acc: 50.72% | Val loss: 0.9911 | Val acc: 54.60% | LR: 0.000004
Epoch: 104 | Train loss: 0.9991 | Train acc: 50.24% | Val loss: 0.9918 | Val acc: 54.48% | LR: 0.000003
Epoch: 105 | Train loss: 0.9997 | Train acc: 50.95% | Val loss: 0.9917 | Val acc: 54.58% | LR: 0.000003
Epoch: 106 | Train loss: 0.9963 | Train acc: 50.73% | Val loss: 0.9917 | Val acc: 54.48% | LR: 0.000003
Epoch: 107 | Train loss: 0.9968 | Train acc: 50.89% | Val loss: 0.9917 | Val acc: 54.48% | LR: 0.000003
Epoch: 108 | Train loss: 0.9975 | Train acc: 50.27% | Val loss: 0.9916 | Val acc: 54.50% | LR: 0.000003
Epoch: 109 | Train loss: 0.9968 | Train acc: 50.81% | Val loss: 0.9916 | Val acc: 54.54% | LR: 0.000003
Epoch: 110 | Train loss: 0.9957 | Train acc: 50.79% | Val loss: 0.9916 | Val acc: 54.50% | LR: 0.000003
Epoch: 111 | Train loss: 0.9972 | Train acc: 50.68% | Val loss: 0.9916 | Val acc: 54.50% | LR: 0.000003
Epoch: 112 | Train loss: 0.9978 | Train acc: 50.37% | Val loss: 0.9916 | Val acc: 54.50% | LR: 0.000003
Epoch: 113 | Train loss: 0.9980 | Train acc: 50.17% | Val loss: 0.9916 | Val acc: 54.44% | LR: 0.000003
Epoch: 114 | Train loss: 0.9973 | Train acc: 50.23% | Val loss: 0.9916 | Val acc: 54.44% | LR: 0.000003
Epoch: 115 | Train loss: 0.9960 | Train acc: 50.99% | Val loss: 0.9917 | Val acc: 54.48% | LR: 0.000002
Epoch: 116 | Train loss: 0.9965 | Train acc: 51.06% | Val loss: 0.9916 | Val acc: 54.46% | LR: 0.000002
Epoch: 117 | Train loss: 0.9970 | Train acc: 50.54% | Val loss: 0.9916 | Val acc: 54.41% | LR: 0.000002
Epoch: 118 | Train loss: 0.9972 | Train acc: 50.61% | Val loss: 0.9916 | Val acc: 54.33% | LR: 0.000002
Epoch: 119 | Train loss: 0.9972 | Train acc: 50.68% | Val loss: 0.9916 | Val acc: 54.36% | LR: 0.000002
Epoch: 120 | Train loss: 0.9973 | Train acc: 50.70% | Val loss: 0.9916 | Val acc: 54.38% | LR: 0.000002
Epoch: 121 | Train loss: 0.9996 | Train acc: 50.79% | Val loss: 0.9916 | Val acc: 54.35% | LR: 0.000002
Epoch: 122 | Train loss: 0.9973 | Train acc: 50.71% | Val loss: 0.9916 | Val acc: 54.35% | LR: 0.000002
Epoch: 123 | Train loss: 0.9956 | Train acc: 50.89% | Val loss: 0.9916 | Val acc: 54.38% | LR: 0.000002
Epoch: 124 | Train loss: 0.9970 | Train acc: 50.97% | Val loss: 0.9916 | Val acc: 54.38% | LR: 0.000002
Epoch: 125 | Train loss: 0.9977 | Train acc: 50.81% | Val loss: 0.9916 | Val acc: 54.38% | LR: 0.000002
Epoch: 126 | Train loss: 0.9975 | Train acc: 50.16% | Val loss: 0.9916 | Val acc: 54.38% | LR: 0.000002
Epoch: 127 | Train loss: 0.9981 | Train acc: 50.51% | Val loss: 0.9916 | Val acc: 54.38% | LR: 0.000002
Epoch: 128 | Train loss: 1.0201 | Train acc: 50.60% | Val loss: 0.9915 | Val acc: 54.42% | LR: 0.000002
Epoch: 129 | Train loss: 0.9989 | Train acc: 50.49% | Val loss: 0.9916 | Val acc: 54.38% | LR: 0.000002
Epoch: 130 | Train loss: 0.9986 | Train acc: 50.72% | Val loss: 0.9916 | Val acc: 54.42% | LR: 0.000001
Epoch: 131 | Train loss: 0.9970 | Train acc: 50.88% | Val loss: 0.9916 | Val acc: 54.44% | LR: 0.000001
Epoch: 132 | Train loss: 0.9981 | Train acc: 50.34% | Val loss: 0.9916 | Val acc: 54.44% | LR: 0.000001
Epoch: 133 | Train loss: 1.0024 | Train acc: 50.47% | Val loss: 0.9916 | Val acc: 54.44% | LR: 0.000001
Epoch: 134 | Train loss: 1.0003 | Train acc: 50.69% | Val loss: 0.9916 | Val acc: 54.42% | LR: 0.000001
Epoch: 135 | Train loss: 0.9960 | Train acc: 50.51% | Val loss: 0.9916 | Val acc: 54.42% | LR: 0.000001
Epoch: 136 | Train loss: 1.0036 | Train acc: 50.99% | Val loss: 0.9917 | Val acc: 54.44% | LR: 0.000001
Epoch: 137 | Train loss: 0.9990 | Train acc: 50.05% | Val loss: 0.9916 | Val acc: 54.42% | LR: 0.000001
Epoch: 138 | Train loss: 0.9994 | Train acc: 50.21% | Val loss: 0.9916 | Val acc: 54.42% | LR: 0.000001
Epoch: 139 | Train loss: 0.9981 | Train acc: 50.23% | Val loss: 0.9916 | Val acc: 54.44% | LR: 0.000001
Epoch: 140 | Train loss: 0.9999 | Train acc: 50.96% | Val loss: 0.9916 | Val acc: 54.44% | LR: 0.000001
Epoch: 141 | Train loss: 0.9974 | Train acc: 50.44% | Val loss: 0.9917 | Val acc: 54.46% | LR: 0.000001
Epoch: 142 | Train loss: 0.9977 | Train acc: 50.68% | Val loss: 0.9916 | Val acc: 54.44% | LR: 0.000001
Epoch: 143 | Train loss: 0.9955 | Train acc: 50.70% | Val loss: 0.9916 | Val acc: 54.40% | LR: 0.000001
Epoch: 144 | Train loss: 0.9959 | Train acc: 50.98% | Val loss: 0.9917 | Val acc: 54.40% | LR: 0.000001
Epoch: 145 | Train loss: 0.9968 | Train acc: 50.26% | Val loss: 0.9916 | Val acc: 54.40% | LR: 0.000001
Epoch: 146 | Train loss: 0.9978 | Train acc: 50.59% | Val loss: 0.9916 | Val acc: 54.40% | LR: 0.000001
Epoch: 147 | Train loss: 0.9963 | Train acc: 50.35% | Val loss: 0.9917 | Val acc: 54.40% | LR: 0.000001
Epoch: 148 | Train loss: 0.9968 | Train acc: 50.67% | Val loss: 0.9917 | Val acc: 54.40% | LR: 0.000001
Epoch: 149 | Train loss: 1.0029 | Train acc: 50.27% | Val loss: 0.9917 | Val acc: 54.40% | LR: 0.000001

[I 2025-09-23 19:23:57,996] Trial 160 finished with value: 0.5440361618995666 and parameters: {'lr': 1.2917933161578656e-05, 'hidden_size': 64, 'dropout': 0.1946869483183823, 'weight_decay': 9.210958562963769e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0005 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.05% | LR: 0.000013
Epoch: 001 | Train loss: 1.0010 | Train acc: 49.73% | Val loss: 0.9917 | Val acc: 54.11% | LR: 0.000013
Epoch: 002 | Train loss: 0.9999 | Train acc: 50.23% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000013
Epoch: 003 | Train loss: 0.9991 | Train acc: 50.53% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000013
Epoch: 004 | Train loss: 0.9997 | Train acc: 50.18% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000012
Epoch: 005 | Train loss: 0.9977 | Train acc: 50.87% | Val loss: 0.9918 | Val acc: 54.17% | LR: 0.000012
Epoch: 006 | Train loss: 0.9984 | Train acc: 50.52% | Val loss: 0.9918 | Val acc: 54.20% | LR: 0.000012
Epoch: 007 | Train loss: 0.9994 | Train acc: 49.98% | Val loss: 0.9919 | Val acc: 54.24% | LR: 0.000012
Epoch: 008 | Train loss: 0.9999 | Train acc: 49.72% | Val loss: 0.9920 | Val acc: 54.34% | LR: 0.000012
Epoch: 009 | Train loss: 0.9980 | Train acc: 50.60% | Val loss: 0.9921 | Val acc: 54.28% | LR: 0.000012
Epoch: 010 | Train loss: 0.9976 | Train acc: 50.78% | Val loss: 0.9921 | Val acc: 54.26% | LR: 0.000012
Epoch: 011 | Train loss: 0.9973 | Train acc: 50.87% | Val loss: 0.9920 | Val acc: 54.28% | LR: 0.000012
Epoch: 012 | Train loss: 0.9976 | Train acc: 50.69% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000012
Epoch: 013 | Train loss: 0.9971 | Train acc: 50.43% | Val loss: 0.9919 | Val acc: 54.28% | LR: 0.000012
Epoch: 014 | Train loss: 1.0002 | Train acc: 50.38% | Val loss: 0.9919 | Val acc: 54.26% | LR: 0.000012
Epoch: 015 | Train loss: 1.0180 | Train acc: 49.88% | Val loss: 0.9918 | Val acc: 54.24% | LR: 0.000012
Epoch: 016 | Train loss: 1.0836 | Train acc: 50.54% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000012
Epoch: 017 | Train loss: 1.0897 | Train acc: 50.64% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000012
Epoch: 018 | Train loss: 0.9981 | Train acc: 50.19% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000012
Epoch: 019 | Train loss: 1.0035 | Train acc: 50.40% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000012
Epoch: 020 | Train loss: 0.9959 | Train acc: 51.13% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000012
Epoch: 021 | Train loss: 0.9982 | Train acc: 50.51% | Val loss: 0.9917 | Val acc: 54.32% | LR: 0.000012
Epoch: 022 | Train loss: 1.0019 | Train acc: 50.74% | Val loss: 0.9917 | Val acc: 54.32% | LR: 0.000012
Epoch: 023 | Train loss: 0.9975 | Train acc: 50.22% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000012
Epoch: 024 | Train loss: 0.9974 | Train acc: 50.43% | Val loss: 0.9917 | Val acc: 54.36% | LR: 0.000012
Epoch: 025 | Train loss: 0.9978 | Train acc: 50.09% | Val loss: 0.9918 | Val acc: 54.36% | LR: 0.000012
Epoch: 026 | Train loss: 0.9971 | Train acc: 50.25% | Val loss: 0.9917 | Val acc: 54.38% | LR: 0.000012
Epoch: 027 | Train loss: 1.0171 | Train acc: 50.78% | Val loss: 0.9917 | Val acc: 54.38% | LR: 0.000012
Epoch: 028 | Train loss: 1.0027 | Train acc: 50.74% | Val loss: 0.9917 | Val acc: 54.42% | LR: 0.000011
Epoch: 029 | Train loss: 0.9993 | Train acc: 50.66% | Val loss: 0.9917 | Val acc: 54.44% | LR: 0.000011
Epoch: 030 | Train loss: 0.9976 | Train acc: 50.45% | Val loss: 0.9917 | Val acc: 54.44% | LR: 0.000011
Epoch: 031 | Train loss: 0.9977 | Train acc: 50.42% | Val loss: 0.9917 | Val acc: 54.40% | LR: 0.000011
Epoch: 032 | Train loss: 0.9941 | Train acc: 51.07% | Val loss: 0.9917 | Val acc: 54.40% | LR: 0.000011
Epoch: 033 | Train loss: 1.0015 | Train acc: 49.99% | Val loss: 0.9917 | Val acc: 54.44% | LR: 0.000011
Epoch: 034 | Train loss: 1.0055 | Train acc: 50.91% | Val loss: 0.9918 | Val acc: 54.46% | LR: 0.000011
Epoch: 035 | Train loss: 0.9971 | Train acc: 50.39% | Val loss: 0.9918 | Val acc: 54.42% | LR: 0.000011
Epoch: 036 | Train loss: 1.0004 | Train acc: 50.42% | Val loss: 0.9918 | Val acc: 54.34% | LR: 0.000011
Epoch: 037 | Train loss: 0.9961 | Train acc: 50.32% | Val loss: 0.9917 | Val acc: 54.32% | LR: 0.000011
Epoch: 038 | Train loss: 0.9990 | Train acc: 50.22% | Val loss: 0.9917 | Val acc: 54.33% | LR: 0.000011
Epoch: 039 | Train loss: 0.9945 | Train acc: 50.68% | Val loss: 0.9918 | Val acc: 54.36% | LR: 0.000011
Epoch: 040 | Train loss: 0.9964 | Train acc: 50.65% | Val loss: 0.9969 | Val acc: 54.28% | LR: 0.000011
Epoch: 041 | Train loss: 0.9958 | Train acc: 50.49% | Val loss: 0.9922 | Val acc: 54.22% | LR: 0.000010
Epoch: 042 | Train loss: 0.9983 | Train acc: 50.37% | Val loss: 0.9920 | Val acc: 54.24% | LR: 0.000010
Epoch: 043 | Train loss: 0.9972 | Train acc: 50.39% | Val loss: 0.9915 | Val acc: 54.32% | LR: 0.000010
Epoch: 044 | Train loss: 0.9962 | Train acc: 50.00% | Val loss: 0.9922 | Val acc: 54.30% | LR: 0.000010
Epoch: 045 | Train loss: 1.0164 | Train acc: 50.49% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000010
Epoch: 046 | Train loss: 0.9944 | Train acc: 50.84% | Val loss: 1.0223 | Val acc: 54.26% | LR: 0.000010
Epoch: 047 | Train loss: 0.9966 | Train acc: 49.99% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000010
Epoch: 048 | Train loss: 0.9962 | Train acc: 50.34% | Val loss: 0.9918 | Val acc: 54.27% | LR: 0.000010
Epoch: 049 | Train loss: 0.9959 | Train acc: 50.33% | Val loss: 0.9918 | Val acc: 54.34% | LR: 0.000010
Epoch: 050 | Train loss: 1.0007 | Train acc: 50.07% | Val loss: 0.9931 | Val acc: 54.38% | LR: 0.000010
Epoch: 051 | Train loss: 0.9939 | Train acc: 50.30% | Val loss: 0.9917 | Val acc: 54.40% | LR: 0.000009
Epoch: 052 | Train loss: 0.9986 | Train acc: 50.22% | Val loss: 1.0071 | Val acc: 54.38% | LR: 0.000009
Epoch: 053 | Train loss: 0.9981 | Train acc: 50.06% | Val loss: 0.9928 | Val acc: 54.34% | LR: 0.000009
Epoch: 054 | Train loss: 0.9949 | Train acc: 50.49% | Val loss: 0.9920 | Val acc: 54.32% | LR: 0.000009
Epoch: 055 | Train loss: 0.9940 | Train acc: 50.66% | Val loss: 0.9913 | Val acc: 54.28% | LR: 0.000009
Epoch: 056 | Train loss: 1.0575 | Train acc: 50.65% | Val loss: 0.9917 | Val acc: 54.28% | LR: 0.000009
Epoch: 057 | Train loss: 1.0025 | Train acc: 50.19% | Val loss: 0.9919 | Val acc: 54.32% | LR: 0.000009
Epoch: 058 | Train loss: 0.9969 | Train acc: 50.30% | Val loss: 0.9921 | Val acc: 54.32% | LR: 0.000009
Epoch: 059 | Train loss: 0.9978 | Train acc: 50.83% | Val loss: 0.9917 | Val acc: 54.32% | LR: 0.000009
Epoch: 060 | Train loss: 0.9967 | Train acc: 50.54% | Val loss: 0.9919 | Val acc: 54.39% | LR: 0.000008
Epoch: 061 | Train loss: 0.9945 | Train acc: 50.25% | Val loss: 0.9917 | Val acc: 54.32% | LR: 0.000008
Epoch: 062 | Train loss: 0.9929 | Train acc: 50.34% | Val loss: 0.9921 | Val acc: 54.28% | LR: 0.000008
Epoch: 063 | Train loss: 1.0182 | Train acc: 50.23% | Val loss: 0.9922 | Val acc: 54.32% | LR: 0.000008
Epoch: 064 | Train loss: 1.0021 | Train acc: 50.84% | Val loss: 0.9917 | Val acc: 54.24% | LR: 0.000008
Epoch: 065 | Train loss: 0.9948 | Train acc: 50.50% | Val loss: 0.9913 | Val acc: 54.32% | LR: 0.000008
Epoch: 066 | Train loss: 1.0016 | Train acc: 49.91% | Val loss: 0.9916 | Val acc: 54.26% | LR: 0.000008
Epoch: 067 | Train loss: 1.0020 | Train acc: 51.05% | Val loss: 0.9920 | Val acc: 54.26% | LR: 0.000008
Epoch: 068 | Train loss: 1.0061 | Train acc: 50.61% | Val loss: 0.9916 | Val acc: 54.36% | LR: 0.000007
Epoch: 069 | Train loss: 0.9977 | Train acc: 50.31% | Val loss: 0.9916 | Val acc: 54.40% | LR: 0.000007
Epoch: 070 | Train loss: 0.9932 | Train acc: 50.97% | Val loss: 0.9918 | Val acc: 54.33% | LR: 0.000007
Epoch: 071 | Train loss: 0.9984 | Train acc: 50.48% | Val loss: 0.9920 | Val acc: 54.31% | LR: 0.000007
Epoch: 072 | Train loss: 0.9993 | Train acc: 50.71% | Val loss: 0.9918 | Val acc: 54.33% | LR: 0.000007
Epoch: 073 | Train loss: 1.0308 | Train acc: 49.94% | Val loss: 0.9918 | Val acc: 54.31% | LR: 0.000007
Epoch: 074 | Train loss: 0.9925 | Train acc: 51.17% | Val loss: 0.9923 | Val acc: 54.33% | LR: 0.000007
Epoch: 075 | Train loss: 1.0009 | Train acc: 50.91% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000007
Epoch: 076 | Train loss: 0.9942 | Train acc: 50.29% | Val loss: 0.9918 | Val acc: 54.21% | LR: 0.000007
Epoch: 077 | Train loss: 0.9966 | Train acc: 50.18% | Val loss: 0.9918 | Val acc: 54.21% | LR: 0.000006
Epoch: 078 | Train loss: 1.0066 | Train acc: 50.63% | Val loss: 0.9924 | Val acc: 54.25% | LR: 0.000006
Epoch: 079 | Train loss: 0.9943 | Train acc: 50.52% | Val loss: 0.9920 | Val acc: 54.33% | LR: 0.000006
Epoch: 080 | Train loss: 0.9929 | Train acc: 50.90% | Val loss: 0.9917 | Val acc: 54.25% | LR: 0.000006
Epoch: 081 | Train loss: 0.9934 | Train acc: 50.39% | Val loss: 0.9917 | Val acc: 54.25% | LR: 0.000006
Epoch: 082 | Train loss: 0.9919 | Train acc: 51.28% | Val loss: 0.9919 | Val acc: 54.19% | LR: 0.000006
Epoch: 083 | Train loss: 0.9948 | Train acc: 50.12% | Val loss: 0.9920 | Val acc: 54.19% | LR: 0.000006

[I 2025-09-23 19:25:04,233] Trial 161 finished with value: 0.5431236267089844 and parameters: {'lr': 1.252523274305989e-05, 'hidden_size': 64, 'dropout': 0.1794218947631203, 'weight_decay': 0.0001324123369500269}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0035 | Train acc: 50.33% | Val loss: 1.0046 | Val acc: 52.61% | LR: 0.000011
Epoch: 001 | Train loss: 1.0131 | Train acc: 50.53% | Val loss: 1.0004 | Val acc: 52.52% | LR: 0.000011
Epoch: 002 | Train loss: 0.9991 | Train acc: 50.51% | Val loss: 1.0154 | Val acc: 52.74% | LR: 0.000011
Epoch: 003 | Train loss: 1.0001 | Train acc: 50.96% | Val loss: 1.0018 | Val acc: 52.41% | LR: 0.000011
Epoch: 004 | Train loss: 1.0002 | Train acc: 50.13% | Val loss: 1.0112 | Val acc: 52.64% | LR: 0.000011
Epoch: 005 | Train loss: 0.9996 | Train acc: 50.38% | Val loss: 1.0070 | Val acc: 52.53% | LR: 0.000011
Epoch: 006 | Train loss: 0.9986 | Train acc: 52.03% | Val loss: 1.0005 | Val acc: 52.68% | LR: 0.000011
Epoch: 007 | Train loss: 1.0020 | Train acc: 50.96% | Val loss: 0.9987 | Val acc: 52.72% | LR: 0.000011
Epoch: 008 | Train loss: 0.9988 | Train acc: 51.71% | Val loss: 0.9984 | Val acc: 52.83% | LR: 0.000011
Epoch: 009 | Train loss: 0.9988 | Train acc: 50.87% | Val loss: 1.0036 | Val acc: 52.76% | LR: 0.000011
Epoch: 010 | Train loss: 1.0014 | Train acc: 51.54% | Val loss: 1.0011 | Val acc: 52.72% | LR: 0.000011
Epoch: 011 | Train loss: 1.0106 | Train acc: 50.63% | Val loss: 1.0002 | Val acc: 52.76% | LR: 0.000011
Epoch: 012 | Train loss: 0.9996 | Train acc: 50.76% | Val loss: 1.0129 | Val acc: 52.77% | LR: 0.000011
Epoch: 013 | Train loss: 0.9979 | Train acc: 50.74% | Val loss: 1.0074 | Val acc: 52.72% | LR: 0.000011
Epoch: 014 | Train loss: 0.9983 | Train acc: 51.05% | Val loss: 1.0026 | Val acc: 52.62% | LR: 0.000011
Epoch: 015 | Train loss: 1.0132 | Train acc: 51.64% | Val loss: 1.0081 | Val acc: 52.72% | LR: 0.000011
Epoch: 016 | Train loss: 0.9991 | Train acc: 52.18% | Val loss: 1.0131 | Val acc: 52.74% | LR: 0.000011
Epoch: 017 | Train loss: 0.9982 | Train acc: 51.19% | Val loss: 1.0524 | Val acc: 52.68% | LR: 0.000010
Epoch: 018 | Train loss: 1.0031 | Train acc: 51.14% | Val loss: 0.9999 | Val acc: 52.45% | LR: 0.000010
Epoch: 019 | Train loss: 0.9981 | Train acc: 51.36% | Val loss: 1.0079 | Val acc: 52.74% | LR: 0.000010
Epoch: 020 | Train loss: 0.9992 | Train acc: 50.88% | Val loss: 0.9981 | Val acc: 53.02% | LR: 0.000010
Epoch: 021 | Train loss: 0.9981 | Train acc: 51.12% | Val loss: 0.9982 | Val acc: 53.13% | LR: 0.000010
Epoch: 022 | Train loss: 0.9977 | Train acc: 51.94% | Val loss: 1.0043 | Val acc: 53.28% | LR: 0.000010
Epoch: 023 | Train loss: 0.9983 | Train acc: 51.32% | Val loss: 1.0056 | Val acc: 53.19% | LR: 0.000010
Epoch: 024 | Train loss: 0.9975 | Train acc: 51.18% | Val loss: 0.9988 | Val acc: 52.97% | LR: 0.000010
Epoch: 025 | Train loss: 1.0034 | Train acc: 50.60% | Val loss: 1.0028 | Val acc: 53.16% | LR: 0.000010
Epoch: 026 | Train loss: 0.9974 | Train acc: 50.84% | Val loss: 0.9974 | Val acc: 53.12% | LR: 0.000010
Epoch: 027 | Train loss: 0.9974 | Train acc: 51.99% | Val loss: 1.0195 | Val acc: 53.00% | LR: 0.000010
Epoch: 028 | Train loss: 0.9985 | Train acc: 50.74% | Val loss: 1.0114 | Val acc: 53.03% | LR: 0.000010
Epoch: 029 | Train loss: 0.9979 | Train acc: 50.98% | Val loss: 0.9989 | Val acc: 53.05% | LR: 0.000010
Epoch: 030 | Train loss: 0.9983 | Train acc: 50.64% | Val loss: 0.9998 | Val acc: 53.03% | LR: 0.000010
Epoch: 031 | Train loss: 0.9983 | Train acc: 50.46% | Val loss: 0.9980 | Val acc: 53.08% | LR: 0.000010
Epoch: 032 | Train loss: 0.9973 | Train acc: 51.20% | Val loss: 0.9963 | Val acc: 53.16% | LR: 0.000010
Epoch: 033 | Train loss: 0.9978 | Train acc: 51.03% | Val loss: 1.0262 | Val acc: 52.77% | LR: 0.000010
Epoch: 034 | Train loss: 0.9978 | Train acc: 50.84% | Val loss: 1.0055 | Val acc: 52.99% | LR: 0.000010
Epoch: 035 | Train loss: 0.9981 | Train acc: 50.47% | Val loss: 1.2121 | Val acc: 52.64% | LR: 0.000010
Epoch: 036 | Train loss: 0.9982 | Train acc: 50.22% | Val loss: 1.0139 | Val acc: 52.77% | LR: 0.000009
Epoch: 037 | Train loss: 0.9968 | Train acc: 51.01% | Val loss: 0.9983 | Val acc: 53.04% | LR: 0.000009
Epoch: 038 | Train loss: 0.9974 | Train acc: 50.48% | Val loss: 1.0004 | Val acc: 53.16% | LR: 0.000009
Epoch: 039 | Train loss: 0.9973 | Train acc: 50.80% | Val loss: 0.9983 | Val acc: 53.14% | LR: 0.000009
Epoch: 040 | Train loss: 0.9979 | Train acc: 50.65% | Val loss: 1.0027 | Val acc: 53.14% | LR: 0.000009
Epoch: 041 | Train loss: 0.9988 | Train acc: 50.29% | Val loss: 0.9967 | Val acc: 52.91% | LR: 0.000009
Epoch: 042 | Train loss: 0.9985 | Train acc: 50.21% | Val loss: 1.0011 | Val acc: 52.93% | LR: 0.000009
Epoch: 043 | Train loss: 0.9983 | Train acc: 50.01% | Val loss: 1.0006 | Val acc: 52.69% | LR: 0.000009
Epoch: 044 | Train loss: 0.9980 | Train acc: 50.29% | Val loss: 1.0000 | Val acc: 52.90% | LR: 0.000009
Epoch: 045 | Train loss: 0.9985 | Train acc: 50.56% | Val loss: 0.9985 | Val acc: 52.69% | LR: 0.000009
Epoch: 046 | Train loss: 0.9984 | Train acc: 49.79% | Val loss: 0.9966 | Val acc: 52.98% | LR: 0.000009
Epoch: 047 | Train loss: 0.9995 | Train acc: 49.84% | Val loss: 1.3050 | Val acc: 52.79% | LR: 0.000009
Epoch: 048 | Train loss: 1.0037 | Train acc: 50.22% | Val loss: 1.0038 | Val acc: 52.77% | LR: 0.000008
Epoch: 049 | Train loss: 0.9970 | Train acc: 50.73% | Val loss: 1.0698 | Val acc: 52.93% | LR: 0.000008
Epoch: 050 | Train loss: 1.0015 | Train acc: 50.33% | Val loss: 1.0030 | Val acc: 52.83% | LR: 0.000008
Epoch: 051 | Train loss: 0.9974 | Train acc: 50.77% | Val loss: 0.9974 | Val acc: 52.81% | LR: 0.000008
Epoch: 052 | Train loss: 0.9982 | Train acc: 50.42% | Val loss: 0.9967 | Val acc: 53.04% | LR: 0.000008
Epoch: 053 | Train loss: 0.9962 | Train acc: 50.97% | Val loss: 1.0023 | Val acc: 53.05% | LR: 0.000008
Epoch: 054 | Train loss: 0.9989 | Train acc: 49.98% | Val loss: 0.9999 | Val acc: 52.83% | LR: 0.000008
Epoch: 055 | Train loss: 0.9976 | Train acc: 50.33% | Val loss: 0.9991 | Val acc: 52.79% | LR: 0.000008
Epoch: 056 | Train loss: 0.9966 | Train acc: 50.97% | Val loss: 1.0035 | Val acc: 52.89% | LR: 0.000008
Epoch: 057 | Train loss: 0.9978 | Train acc: 50.56% | Val loss: 1.0040 | Val acc: 52.71% | LR: 0.000008
Epoch: 058 | Train loss: 0.9949 | Train acc: 51.11% | Val loss: 1.0002 | Val acc: 52.79% | LR: 0.000008
Epoch: 059 | Train loss: 0.9965 | Train acc: 50.66% | Val loss: 1.0004 | Val acc: 52.75% | LR: 0.000007
Epoch: 060 | Train loss: 0.9982 | Train acc: 50.22% | Val loss: 1.0004 | Val acc: 52.59% | LR: 0.000007
Epoch: 061 | Train loss: 0.9975 | Train acc: 50.40% | Val loss: 1.0069 | Val acc: 52.61% | LR: 0.000007
Epoch: 062 | Train loss: 0.9969 | Train acc: 50.75% | Val loss: 0.9973 | Val acc: 52.93% | LR: 0.000007
Epoch: 063 | Train loss: 0.9972 | Train acc: 50.48% | Val loss: 1.0085 | Val acc: 52.72% | LR: 0.000007
Epoch: 064 | Train loss: 0.9980 | Train acc: 50.17% | Val loss: 1.0055 | Val acc: 52.97% | LR: 0.000007
Epoch: 065 | Train loss: 0.9966 | Train acc: 50.75% | Val loss: 0.9987 | Val acc: 52.66% | LR: 0.000007
Epoch: 066 | Train loss: 1.0066 | Train acc: 51.03% | Val loss: 0.9985 | Val acc: 52.95% | LR: 0.000007
Epoch: 067 | Train loss: 0.9966 | Train acc: 50.68% | Val loss: 0.9976 | Val acc: 52.93% | LR: 0.000007
Epoch: 068 | Train loss: 0.9974 | Train acc: 50.47% | Val loss: 1.0000 | Val acc: 52.71% | LR: 0.000007
Epoch: 069 | Train loss: 1.0026 | Train acc: 50.05% | Val loss: 1.0035 | Val acc: 52.75% | LR: 0.000006
Epoch: 070 | Train loss: 0.9970 | Train acc: 50.43% | Val loss: 1.0019 | Val acc: 52.83% | LR: 0.000006
Epoch: 071 | Train loss: 0.9982 | Train acc: 50.24% | Val loss: 1.0023 | Val acc: 52.77% | LR: 0.000006

[I 2025-09-23 19:26:00,178] Trial 162 finished with value: 0.5301403164863586 and parameters: {'lr': 1.0844131100555047e-05, 'hidden_size': 69, 'dropout': 0.1969697842884164, 'weight_decay': 9.464556611363745e-05}. Best is trial 103 with value: 0.5463126420974731.

Epoch: 000 | Train loss: 1.0005 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.07% | LR: 0.000013
Epoch: 001 | Train loss: 1.0008 | Train acc: 49.72% | Val loss: 0.9917 | Val acc: 54.11% | LR: 0.000013
Epoch: 002 | Train loss: 1.0005 | Train acc: 49.54% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000013
Epoch: 003 | Train loss: 1.0008 | Train acc: 49.54% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000013
Epoch: 004 | Train loss: 1.0014 | Train acc: 49.36% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000013
Epoch: 005 | Train loss: 0.9987 | Train acc: 49.81% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000013
Epoch: 006 | Train loss: 1.0007 | Train acc: 49.50% | Val loss: 0.9919 | Val acc: 54.17% | LR: 0.000013
Epoch: 007 | Train loss: 1.0015 | Train acc: 49.41% | Val loss: 0.9919 | Val acc: 54.20% | LR: 0.000013
Epoch: 008 | Train loss: 1.0010 | Train acc: 49.65% | Val loss: 0.9920 | Val acc: 54.26% | LR: 0.000013
Epoch: 009 | Train loss: 0.9993 | Train acc: 50.02% | Val loss: 0.9921 | Val acc: 54.36% | LR: 0.000013
Epoch: 010 | Train loss: 0.9988 | Train acc: 50.66% | Val loss: 0.9921 | Val acc: 54.32% | LR: 0.000013
Epoch: 011 | Train loss: 0.9987 | Train acc: 50.70% | Val loss: 0.9921 | Val acc: 54.30% | LR: 0.000013
Epoch: 012 | Train loss: 0.9984 | Train acc: 50.43% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000013
Epoch: 013 | Train loss: 0.9998 | Train acc: 50.22% | Val loss: 0.9919 | Val acc: 54.30% | LR: 0.000013
Epoch: 014 | Train loss: 0.9985 | Train acc: 50.45% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000013
Epoch: 015 | Train loss: 1.0000 | Train acc: 50.03% | Val loss: 0.9920 | Val acc: 54.28% | LR: 0.000013
Epoch: 016 | Train loss: 0.9985 | Train acc: 50.46% | Val loss: 0.9921 | Val acc: 54.28% | LR: 0.000013
Epoch: 017 | Train loss: 0.9992 | Train acc: 50.39% | Val loss: 0.9919 | Val acc: 54.32% | LR: 0.000013
Epoch: 018 | Train loss: 0.9994 | Train acc: 50.12% | Val loss: 0.9920 | Val acc: 54.32% | LR: 0.000013
Epoch: 019 | Train loss: 0.9991 | Train acc: 50.35% | Val loss: 0.9920 | Val acc: 54.34% | LR: 0.000013
Epoch: 020 | Train loss: 0.9967 | Train acc: 51.15% | Val loss: 0.9920 | Val acc: 54.36% | LR: 0.000013
Epoch: 021 | Train loss: 0.9981 | Train acc: 50.61% | Val loss: 0.9919 | Val acc: 54.36% | LR: 0.000013
Epoch: 022 | Train loss: 0.9973 | Train acc: 50.80% | Val loss: 0.9918 | Val acc: 54.42% | LR: 0.000013
Epoch: 023 | Train loss: 0.9987 | Train acc: 50.38% | Val loss: 0.9916 | Val acc: 54.44% | LR: 0.000013
Epoch: 024 | Train loss: 0.9984 | Train acc: 50.34% | Val loss: 0.9918 | Val acc: 54.38% | LR: 0.000013
Epoch: 025 | Train loss: 0.9996 | Train acc: 50.07% | Val loss: 0.9918 | Val acc: 54.50% | LR: 0.000013
Epoch: 026 | Train loss: 0.9991 | Train acc: 50.26% | Val loss: 0.9918 | Val acc: 54.36% | LR: 0.000012
Epoch: 027 | Train loss: 0.9974 | Train acc: 50.80% | Val loss: 0.9918 | Val acc: 54.29% | LR: 0.000012
Epoch: 028 | Train loss: 0.9969 | Train acc: 50.76% | Val loss: 0.9937 | Val acc: 54.32% | LR: 0.000012
Epoch: 029 | Train loss: 0.9977 | Train acc: 50.76% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000012
Epoch: 030 | Train loss: 0.9982 | Train acc: 50.38% | Val loss: 0.9917 | Val acc: 54.24% | LR: 0.000012
Epoch: 031 | Train loss: 0.9984 | Train acc: 50.30% | Val loss: 0.9916 | Val acc: 54.22% | LR: 0.000012
Epoch: 032 | Train loss: 0.9969 | Train acc: 51.03% | Val loss: 0.9918 | Val acc: 54.22% | LR: 0.000012
Epoch: 033 | Train loss: 0.9991 | Train acc: 49.90% | Val loss: 0.9917 | Val acc: 54.22% | LR: 0.000012
Epoch: 034 | Train loss: 0.9964 | Train acc: 50.90% | Val loss: 0.9915 | Val acc: 54.30% | LR: 0.000012
Epoch: 035 | Train loss: 0.9983 | Train acc: 50.36% | Val loss: 0.9915 | Val acc: 54.37% | LR: 0.000012
Epoch: 036 | Train loss: 0.9978 | Train acc: 50.46% | Val loss: 0.9917 | Val acc: 54.31% | LR: 0.000012
Epoch: 037 | Train loss: 0.9979 | Train acc: 50.38% | Val loss: 0.9917 | Val acc: 54.33% | LR: 0.000012
Epoch: 038 | Train loss: 0.9984 | Train acc: 50.32% | Val loss: 0.9918 | Val acc: 54.35% | LR: 0.000011
Epoch: 039 | Train loss: 0.9967 | Train acc: 50.84% | Val loss: 0.9917 | Val acc: 54.32% | LR: 0.000011
Epoch: 040 | Train loss: 0.9973 | Train acc: 50.73% | Val loss: 0.9916 | Val acc: 54.30% | LR: 0.000011
Epoch: 041 | Train loss: 0.9985 | Train acc: 50.57% | Val loss: 0.9917 | Val acc: 54.33% | LR: 0.000011
Epoch: 042 | Train loss: 0.9983 | Train acc: 50.31% | Val loss: 0.9917 | Val acc: 54.37% | LR: 0.000011
Epoch: 043 | Train loss: 0.9982 | Train acc: 50.41% | Val loss: 0.9919 | Val acc: 54.41% | LR: 0.000011
Epoch: 044 | Train loss: 0.9983 | Train acc: 50.25% | Val loss: 0.9917 | Val acc: 54.39% | LR: 0.000011
Epoch: 045 | Train loss: 0.9970 | Train acc: 50.64% | Val loss: 0.9916 | Val acc: 54.33% | LR: 0.000011
Epoch: 046 | Train loss: 0.9966 | Train acc: 50.98% | Val loss: 0.9915 | Val acc: 54.41% | LR: 0.000011
Epoch: 047 | Train loss: 0.9978 | Train acc: 50.20% | Val loss: 0.9918 | Val acc: 54.43% | LR: 0.000011
Epoch: 048 | Train loss: 0.9975 | Train acc: 50.65% | Val loss: 0.9918 | Val acc: 54.35% | LR: 0.000010
Epoch: 049 | Train loss: 0.9977 | Train acc: 50.56% | Val loss: 0.9920 | Val acc: 54.46% | LR: 0.000010
Epoch: 050 | Train loss: 0.9984 | Train acc: 50.40% | Val loss: 0.9918 | Val acc: 54.44% | LR: 0.000010
Epoch: 051 | Train loss: 0.9970 | Train acc: 50.58% | Val loss: 0.9918 | Val acc: 54.38% | LR: 0.000010
Epoch: 052 | Train loss: 0.9987 | Train acc: 50.39% | Val loss: 0.9917 | Val acc: 54.36% | LR: 0.000010
Epoch: 053 | Train loss: 0.9977 | Train acc: 50.27% | Val loss: 0.9917 | Val acc: 54.31% | LR: 0.000010
Epoch: 054 | Train loss: 0.9989 | Train acc: 50.73% | Val loss: 0.9917 | Val acc: 54.39% | LR: 0.000010
Epoch: 055 | Train loss: 0.9968 | Train acc: 50.77% | Val loss: 0.9915 | Val acc: 54.40% | LR: 0.000010
Epoch: 056 | Train loss: 0.9962 | Train acc: 50.93% | Val loss: 0.9923 | Val acc: 54.34% | LR: 0.000009
Epoch: 057 | Train loss: 0.9971 | Train acc: 50.41% | Val loss: 0.9917 | Val acc: 54.42% | LR: 0.000009
Epoch: 058 | Train loss: 0.9977 | Train acc: 50.53% | Val loss: 0.9917 | Val acc: 54.44% | LR: 0.000009
Epoch: 059 | Train loss: 0.9965 | Train acc: 50.96% | Val loss: 0.9918 | Val acc: 54.52% | LR: 0.000009
Epoch: 060 | Train loss: 0.9962 | Train acc: 50.71% | Val loss: 0.9915 | Val acc: 54.46% | LR: 0.000009
Epoch: 061 | Train loss: 0.9970 | Train acc: 50.40% | Val loss: 0.9920 | Val acc: 54.52% | LR: 0.000009
Epoch: 062 | Train loss: 0.9977 | Train acc: 50.53% | Val loss: 0.9917 | Val acc: 54.56% | LR: 0.000009
Epoch: 063 | Train loss: 0.9978 | Train acc: 50.45% | Val loss: 0.9918 | Val acc: 54.50% | LR: 0.000009
Epoch: 064 | Train loss: 0.9970 | Train acc: 50.78% | Val loss: 0.9918 | Val acc: 54.58% | LR: 0.000008
Epoch: 065 | Train loss: 0.9961 | Train acc: 50.82% | Val loss: 0.9917 | Val acc: 54.56% | LR: 0.000008
Epoch: 066 | Train loss: 0.9973 | Train acc: 50.27% | Val loss: 0.9920 | Val acc: 54.48% | LR: 0.000008
Epoch: 067 | Train loss: 0.9961 | Train acc: 51.18% | Val loss: 0.9918 | Val acc: 54.50% | LR: 0.000008
Epoch: 068 | Train loss: 0.9969 | Train acc: 50.85% | Val loss: 0.9918 | Val acc: 54.50% | LR: 0.000008
Epoch: 069 | Train loss: 0.9968 | Train acc: 50.62% | Val loss: 0.9918 | Val acc: 54.60% | LR: 0.000008
Epoch: 070 | Train loss: 0.9951 | Train acc: 50.99% | Val loss: 0.9918 | Val acc: 54.60% | LR: 0.000008
Epoch: 071 | Train loss: 0.9971 | Train acc: 50.81% | Val loss: 0.9917 | Val acc: 54.62% | LR: 0.000008
Epoch: 072 | Train loss: 0.9968 | Train acc: 50.95% | Val loss: 0.9918 | Val acc: 54.56% | LR: 0.000007
Epoch: 073 | Train loss: 0.9966 | Train acc: 51.42% | Val loss: 0.9919 | Val acc: 54.52% | LR: 0.000007
Epoch: 074 | Train loss: 0.9996 | Train acc: 50.92% | Val loss: 0.9922 | Val acc: 54.52% | LR: 0.000007
Epoch: 075 | Train loss: 0.9952 | Train acc: 50.60% | Val loss: 0.9923 | Val acc: 54.46% | LR: 0.000007
Epoch: 076 | Train loss: 0.9970 | Train acc: 50.63% | Val loss: 0.9924 | Val acc: 54.50% | LR: 0.000007
Epoch: 077 | Train loss: 0.9966 | Train acc: 50.85% | Val loss: 0.9920 | Val acc: 54.50% | LR: 0.000007
Epoch: 078 | Train loss: 1.0021 | Train acc: 51.03% | Val loss: 0.9921 | Val acc: 54.50% | LR: 0.000007
Epoch: 079 | Train loss: 0.9961 | Train acc: 50.94% | Val loss: 0.9941 | Val acc: 54.58% | LR: 0.000007
Epoch: 080 | Train loss: 0.9955 | Train acc: 50.69% | Val loss: 0.9917 | Val acc: 54.58% | LR: 0.000006
Epoch: 081 | Train loss: 0.9956 | Train acc: 50.94% | Val loss: 0.9919 | Val acc: 54.54% | LR: 0.000006
Epoch: 082 | Train loss: 0.9960 | Train acc: 50.33% | Val loss: 0.9919 | Val acc: 54.50% | LR: 0.000006
Epoch: 083 | Train loss: 0.9962 | Train acc: 50.67% | Val loss: 0.9919 | Val acc: 54.52% | LR: 0.000006
Epoch: 084 | Train loss: 0.9953 | Train acc: 50.85% | Val loss: 0.9919 | Val acc: 54.59% | LR: 0.000006
Epoch: 085 | Train loss: 0.9976 | Train acc: 50.42% | Val loss: 0.9921 | Val acc: 54.57% | LR: 0.000006
Epoch: 086 | Train loss: 0.9959 | Train acc: 50.88% | Val loss: 0.9919 | Val acc: 54.55% | LR: 0.000006
Epoch: 087 | Train loss: 0.9947 | Train acc: 51.25% | Val loss: 0.9920 | Val acc: 54.45% | LR: 0.000006
Epoch: 088 | Train loss: 0.9958 | Train acc: 50.69% | Val loss: 0.9920 | Val acc: 54.45% | LR: 0.000005
Epoch: 089 | Train loss: 0.9961 | Train acc: 50.71% | Val loss: 0.9920 | Val acc: 54.41% | LR: 0.000005
Epoch: 090 | Train loss: 0.9962 | Train acc: 50.88% | Val loss: 0.9920 | Val acc: 54.49% | LR: 0.000005
Epoch: 091 | Train loss: 0.9959 | Train acc: 50.62% | Val loss: 0.9920 | Val acc: 54.49% | LR: 0.000005
Epoch: 092 | Train loss: 0.9942 | Train acc: 51.51% | Val loss: 0.9920 | Val acc: 54.54% | LR: 0.000005
Epoch: 093 | Train loss: 0.9954 | Train acc: 50.79% | Val loss: 0.9920 | Val acc: 54.55% | LR: 0.000005
Epoch: 094 | Train loss: 0.9950 | Train acc: 50.53% | Val loss: 0.9920 | Val acc: 54.57% | LR: 0.000005
Epoch: 095 | Train loss: 0.9970 | Train acc: 50.43% | Val loss: 0.9920 | Val acc: 54.61% | LR: 0.000005
Epoch: 096 | Train loss: 0.9945 | Train acc: 51.23% | Val loss: 0.9920 | Val acc: 54.63% | LR: 0.000004
Epoch: 097 | Train loss: 0.9955 | Train acc: 50.96% | Val loss: 0.9920 | Val acc: 54.57% | LR: 0.000004
Epoch: 098 | Train loss: 0.9975 | Train acc: 50.28% | Val loss: 0.9920 | Val acc: 54.57% | LR: 0.000004
Epoch: 099 | Train loss: 0.9964 | Train acc: 50.53% | Val loss: 0.9921 | Val acc: 54.61% | LR: 0.000004
Epoch: 100 | Train loss: 0.9937 | Train acc: 51.76% | Val loss: 0.9936 | Val acc: 54.49% | LR: 0.000004
Epoch: 101 | Train loss: 0.9954 | Train acc: 50.79% | Val loss: 0.9946 | Val acc: 54.49% | LR: 0.000004
Epoch: 102 | Train loss: 0.9949 | Train acc: 50.96% | Val loss: 0.9921 | Val acc: 54.43% | LR: 0.000004
Epoch: 103 | Train loss: 0.9955 | Train acc: 50.79% | Val loss: 0.9920 | Val acc: 54.43% | LR: 0.000004
Epoch: 104 | Train loss: 0.9959 | Train acc: 50.97% | Val loss: 0.9920 | Val acc: 54.43% | LR: 0.000004
Epoch: 105 | Train loss: 0.9959 | Train acc: 50.35% | Val loss: 0.9920 | Val acc: 54.51% | LR: 0.000003
Epoch: 106 | Train loss: 0.9959 | Train acc: 50.53% | Val loss: 0.9920 | Val acc: 54.51% | LR: 0.000003
Epoch: 107 | Train loss: 0.9956 | Train acc: 50.79% | Val loss: 0.9920 | Val acc: 54.55% | LR: 0.000003
Epoch: 108 | Train loss: 0.9966 | Train acc: 50.79% | Val loss: 0.9920 | Val acc: 54.59% | LR: 0.000003
Epoch: 109 | Train loss: 0.9967 | Train acc: 50.35% | Val loss: 0.9920 | Val acc: 54.65% | LR: 0.000003
Epoch: 110 | Train loss: 0.9946 | Train acc: 51.15% | Val loss: 0.9920 | Val acc: 54.65% | LR: 0.000003
Epoch: 111 | Train loss: 0.9946 | Train acc: 51.04% | Val loss: 0.9920 | Val acc: 54.67% | LR: 0.000003
Epoch: 112 | Train loss: 0.9952 | Train acc: 50.96% | Val loss: 0.9920 | Val acc: 54.73% | LR: 0.000003
Epoch: 113 | Train loss: 0.9945 | Train acc: 51.04% | Val loss: 0.9920 | Val acc: 54.73% | LR: 0.000003
Epoch: 114 | Train loss: 0.9945 | Train acc: 51.21% | Val loss: 0.9920 | Val acc: 54.75% | LR: 0.000003
Epoch: 115 | Train loss: 0.9955 | Train acc: 50.68% | Val loss: 0.9920 | Val acc: 54.73% | LR: 0.000003
Epoch: 116 | Train loss: 0.9952 | Train acc: 50.86% | Val loss: 0.9920 | Val acc: 54.74% | LR: 0.000002
Epoch: 117 | Train loss: 0.9988 | Train acc: 50.68% | Val loss: 0.9920 | Val acc: 54.74% | LR: 0.000002
Epoch: 118 | Train loss: 0.9958 | Train acc: 50.77% | Val loss: 0.9920 | Val acc: 54.74% | LR: 0.000002
Epoch: 119 | Train loss: 0.9969 | Train acc: 50.50% | Val loss: 0.9920 | Val acc: 54.76% | LR: 0.000002
Epoch: 120 | Train loss: 0.9971 | Train acc: 50.59% | Val loss: 0.9920 | Val acc: 54.74% | LR: 0.000002
Epoch: 121 | Train loss: 0.9955 | Train acc: 50.68% | Val loss: 0.9920 | Val acc: 54.70% | LR: 0.000002
Epoch: 122 | Train loss: 0.9953 | Train acc: 50.94% | Val loss: 0.9920 | Val acc: 54.70% | LR: 0.000002
Epoch: 123 | Train loss: 0.9949 | Train acc: 50.68% | Val loss: 0.9920 | Val acc: 54.74% | LR: 0.000002
Epoch: 124 | Train loss: 0.9959 | Train acc: 50.75% | Val loss: 0.9920 | Val acc: 54.73% | LR: 0.000002
Epoch: 125 | Train loss: 0.9958 | Train acc: 50.60% | Val loss: 0.9920 | Val acc: 54.73% | LR: 0.000002
Epoch: 126 | Train loss: 0.9966 | Train acc: 50.95% | Val loss: 0.9920 | Val acc: 54.73% | LR: 0.000002
Epoch: 127 | Train loss: 0.9951 | Train acc: 50.78% | Val loss: 0.9920 | Val acc: 54.73% | LR: 0.000002
Epoch: 128 | Train loss: 0.9969 | Train acc: 50.34% | Val loss: 0.9920 | Val acc: 54.73% | LR: 0.000002
Epoch: 129 | Train loss: 0.9954 | Train acc: 50.87% | Val loss: 0.9920 | Val acc: 54.73% | LR: 0.000002
Epoch: 130 | Train loss: 0.9984 | Train acc: 50.07% | Val loss: 0.9920 | Val acc: 54.69% | LR: 0.000001
Epoch: 131 | Train loss: 0.9950 | Train acc: 50.96% | Val loss: 0.9920 | Val acc: 54.71% | LR: 0.000001
Epoch: 132 | Train loss: 0.9953 | Train acc: 50.86% | Val loss: 0.9920 | Val acc: 54.71% | LR: 0.000001
Epoch: 133 | Train loss: 0.9964 | Train acc: 50.87% | Val loss: 0.9920 | Val acc: 54.71% | LR: 0.000001
Epoch: 134 | Train loss: 0.9952 | Train acc: 51.05% | Val loss: 0.9920 | Val acc: 54.71% | LR: 0.000001
Epoch: 135 | Train loss: 0.9926 | Train acc: 51.67% | Val loss: 0.9920 | Val acc: 54.71% | LR: 0.000001
Epoch: 136 | Train loss: 0.9951 | Train acc: 50.51% | Val loss: 0.9920 | Val acc: 54.71% | LR: 0.000001
Epoch: 137 | Train loss: 0.9953 | Train acc: 51.22% | Val loss: 0.9920 | Val acc: 54.67% | LR: 0.000001
Epoch: 138 | Train loss: 0.9965 | Train acc: 50.61% | Val loss: 0.9920 | Val acc: 54.67% | LR: 0.000001
Epoch: 139 | Train loss: 0.9962 | Train acc: 50.51% | Val loss: 0.9920 | Val acc: 54.67% | LR: 0.000001
Epoch: 140 | Train loss: 0.9951 | Train acc: 50.61% | Val loss: 0.9920 | Val acc: 54.67% | LR: 0.000001
Epoch: 141 | Train loss: 0.9945 | Train acc: 50.88% | Val loss: 0.9920 | Val acc: 54.67% | LR: 0.000001
Epoch: 142 | Train loss: 0.9951 | Train acc: 50.69% | Val loss: 0.9920 | Val acc: 54.67% | LR: 0.000001
Epoch: 143 | Train loss: 0.9945 | Train acc: 51.04% | Val loss: 0.9920 | Val acc: 54.67% | LR: 0.000001
Epoch: 144 | Train loss: 0.9951 | Train acc: 50.52% | Val loss: 0.9920 | Val acc: 54.67% | LR: 0.000001
Epoch: 145 | Train loss: 0.9951 | Train acc: 51.14% | Val loss: 0.9920 | Val acc: 54.67% | LR: 0.000001
Epoch: 146 | Train loss: 0.9966 | Train acc: 50.51% | Val loss: 0.9920 | Val acc: 54.67% | LR: 0.000001
Epoch: 147 | Train loss: 0.9941 | Train acc: 51.13% | Val loss: 0.9920 | Val acc: 54.67% | LR: 0.000001
Epoch: 148 | Train loss: 0.9951 | Train acc: 50.77% | Val loss: 0.9920 | Val acc: 54.67% | LR: 0.000001
Epoch: 149 | Train loss: 0.9934 | Train acc: 51.12% | Val loss: 0.9920 | Val acc: 54.67% | LR: 0.000001

[I 2025-09-23 19:27:53,732] Trial 163 finished with value: 0.5466681122779846 and parameters: {'lr': 1.3408894256201908e-05, 'hidden_size': 64, 'dropout': 0.2098390334489329, 'weight_decay': 6.758813888285353e-05}. Best is trial 163 with value: 0.5466681122779846.

Epoch: 000 | Train loss: 1.0034 | Train acc: 48.82% | Val loss: 0.9973 | Val acc: 53.46% | LR: 0.000015
Epoch: 001 | Train loss: 1.0021 | Train acc: 49.19% | Val loss: 0.9973 | Val acc: 53.58% | LR: 0.000015
Epoch: 002 | Train loss: 1.0011 | Train acc: 49.46% | Val loss: 0.9972 | Val acc: 53.71% | LR: 0.000015
Epoch: 003 | Train loss: 1.0024 | Train acc: 48.97% | Val loss: 0.9971 | Val acc: 53.79% | LR: 0.000015
Epoch: 004 | Train loss: 1.0020 | Train acc: 49.26% | Val loss: 0.9972 | Val acc: 53.95% | LR: 0.000015
Epoch: 005 | Train loss: 1.0020 | Train acc: 49.43% | Val loss: 0.9972 | Val acc: 54.03% | LR: 0.000015
Epoch: 006 | Train loss: 1.0017 | Train acc: 49.33% | Val loss: 0.9972 | Val acc: 53.97% | LR: 0.000014
Epoch: 007 | Train loss: 1.0011 | Train acc: 49.52% | Val loss: 0.9972 | Val acc: 54.07% | LR: 0.000014
Epoch: 008 | Train loss: 1.0007 | Train acc: 49.73% | Val loss: 0.9972 | Val acc: 54.16% | LR: 0.000014
Epoch: 009 | Train loss: 1.0003 | Train acc: 49.92% | Val loss: 0.9972 | Val acc: 54.11% | LR: 0.000014
Epoch: 010 | Train loss: 1.0010 | Train acc: 49.56% | Val loss: 0.9971 | Val acc: 54.07% | LR: 0.000014
Epoch: 011 | Train loss: 1.0005 | Train acc: 49.74% | Val loss: 0.9971 | Val acc: 54.09% | LR: 0.000014
Epoch: 012 | Train loss: 0.9999 | Train acc: 50.12% | Val loss: 0.9970 | Val acc: 54.15% | LR: 0.000014
Epoch: 013 | Train loss: 1.0011 | Train acc: 49.34% | Val loss: 0.9970 | Val acc: 54.23% | LR: 0.000014
Epoch: 014 | Train loss: 1.0005 | Train acc: 49.59% | Val loss: 0.9970 | Val acc: 54.25% | LR: 0.000014
Epoch: 015 | Train loss: 1.0000 | Train acc: 49.83% | Val loss: 0.9970 | Val acc: 54.23% | LR: 0.000014
Epoch: 016 | Train loss: 0.9995 | Train acc: 50.22% | Val loss: 0.9969 | Val acc: 54.21% | LR: 0.000014
Epoch: 017 | Train loss: 0.9998 | Train acc: 49.77% | Val loss: 0.9966 | Val acc: 54.09% | LR: 0.000014
Epoch: 018 | Train loss: 1.0000 | Train acc: 49.91% | Val loss: 0.9966 | Val acc: 54.05% | LR: 0.000014
Epoch: 019 | Train loss: 0.9996 | Train acc: 50.24% | Val loss: 0.9965 | Val acc: 54.21% | LR: 0.000014
Epoch: 020 | Train loss: 0.9999 | Train acc: 49.70% | Val loss: 0.9965 | Val acc: 54.02% | LR: 0.000014
Epoch: 021 | Train loss: 0.9997 | Train acc: 50.12% | Val loss: 0.9965 | Val acc: 53.86% | LR: 0.000014
Epoch: 022 | Train loss: 0.9996 | Train acc: 50.40% | Val loss: 0.9964 | Val acc: 54.02% | LR: 0.000014
Epoch: 023 | Train loss: 0.9992 | Train acc: 50.20% | Val loss: 0.9963 | Val acc: 53.94% | LR: 0.000014
Epoch: 024 | Train loss: 0.9991 | Train acc: 50.36% | Val loss: 0.9963 | Val acc: 53.84% | LR: 0.000014
Epoch: 025 | Train loss: 0.9990 | Train acc: 50.74% | Val loss: 0.9962 | Val acc: 53.84% | LR: 0.000014
Epoch: 026 | Train loss: 0.9989 | Train acc: 51.34% | Val loss: 0.9962 | Val acc: 53.66% | LR: 0.000014
Epoch: 027 | Train loss: 0.9991 | Train acc: 50.66% | Val loss: 0.9962 | Val acc: 53.57% | LR: 0.000013
Epoch: 028 | Train loss: 0.9984 | Train acc: 50.83% | Val loss: 0.9963 | Val acc: 53.64% | LR: 0.000013
Epoch: 029 | Train loss: 0.9983 | Train acc: 51.19% | Val loss: 0.9963 | Val acc: 53.83% | LR: 0.000013
Epoch: 030 | Train loss: 0.9982 | Train acc: 50.98% | Val loss: 0.9963 | Val acc: 53.43% | LR: 0.000013
Epoch: 031 | Train loss: 0.9979 | Train acc: 51.05% | Val loss: 0.9962 | Val acc: 53.50% | LR: 0.000013
Epoch: 032 | Train loss: 0.9992 | Train acc: 50.26% | Val loss: 0.9961 | Val acc: 53.49% | LR: 0.000013
Epoch: 033 | Train loss: 0.9984 | Train acc: 50.77% | Val loss: 0.9960 | Val acc: 53.61% | LR: 0.000013
Epoch: 034 | Train loss: 0.9982 | Train acc: 50.82% | Val loss: 0.9960 | Val acc: 53.05% | LR: 0.000013
Epoch: 035 | Train loss: 0.9980 | Train acc: 51.15% | Val loss: 0.9960 | Val acc: 53.27% | LR: 0.000013
Epoch: 036 | Train loss: 0.9980 | Train acc: 50.90% | Val loss: 0.9959 | Val acc: 53.26% | LR: 0.000013
Epoch: 037 | Train loss: 0.9983 | Train acc: 50.73% | Val loss: 0.9958 | Val acc: 53.12% | LR: 0.000013
Epoch: 038 | Train loss: 0.9982 | Train acc: 50.75% | Val loss: 0.9957 | Val acc: 53.24% | LR: 0.000012
Epoch: 039 | Train loss: 0.9977 | Train acc: 50.95% | Val loss: 0.9956 | Val acc: 53.18% | LR: 0.000012
Epoch: 040 | Train loss: 0.9962 | Train acc: 51.55% | Val loss: 0.9957 | Val acc: 53.22% | LR: 0.000012
Epoch: 041 | Train loss: 0.9970 | Train acc: 51.12% | Val loss: 0.9957 | Val acc: 53.31% | LR: 0.000012
Epoch: 042 | Train loss: 0.9980 | Train acc: 50.46% | Val loss: 0.9957 | Val acc: 53.36% | LR: 0.000012
Epoch: 043 | Train loss: 0.9984 | Train acc: 50.64% | Val loss: 0.9957 | Val acc: 53.33% | LR: 0.000012
Epoch: 044 | Train loss: 0.9974 | Train acc: 50.74% | Val loss: 0.9957 | Val acc: 53.37% | LR: 0.000012
Epoch: 045 | Train loss: 0.9967 | Train acc: 51.10% | Val loss: 0.9957 | Val acc: 53.33% | LR: 0.000012
Epoch: 046 | Train loss: 0.9964 | Train acc: 51.02% | Val loss: 0.9958 | Val acc: 53.11% | LR: 0.000012
Epoch: 047 | Train loss: 0.9966 | Train acc: 51.21% | Val loss: 0.9957 | Val acc: 53.07% | LR: 0.000011
Epoch: 048 | Train loss: 0.9963 | Train acc: 51.11% | Val loss: 0.9957 | Val acc: 53.03% | LR: 0.000011
Epoch: 049 | Train loss: 0.9973 | Train acc: 50.76% | Val loss: 0.9957 | Val acc: 52.77% | LR: 0.000011
Epoch: 050 | Train loss: 0.9973 | Train acc: 50.66% | Val loss: 0.9957 | Val acc: 52.65% | LR: 0.000011
Epoch: 051 | Train loss: 0.9974 | Train acc: 50.66% | Val loss: 0.9956 | Val acc: 52.57% | LR: 0.000011
Epoch: 052 | Train loss: 0.9963 | Train acc: 50.91% | Val loss: 0.9955 | Val acc: 52.59% | LR: 0.000011
Epoch: 053 | Train loss: 0.9962 | Train acc: 50.82% | Val loss: 0.9955 | Val acc: 52.37% | LR: 0.000011
Epoch: 054 | Train loss: 0.9956 | Train acc: 51.08% | Val loss: 0.9955 | Val acc: 52.41% | LR: 0.000011
Epoch: 055 | Train loss: 0.9961 | Train acc: 50.88% | Val loss: 0.9955 | Val acc: 52.43% | LR: 0.000010
Epoch: 056 | Train loss: 0.9973 | Train acc: 50.64% | Val loss: 0.9954 | Val acc: 52.45% | LR: 0.000010
Epoch: 057 | Train loss: 0.9970 | Train acc: 50.66% | Val loss: 0.9955 | Val acc: 52.44% | LR: 0.000010
Epoch: 058 | Train loss: 0.9956 | Train acc: 50.92% | Val loss: 0.9955 | Val acc: 52.46% | LR: 0.000010
Epoch: 059 | Train loss: 0.9986 | Train acc: 50.21% | Val loss: 0.9954 | Val acc: 52.44% | LR: 0.000010
Epoch: 060 | Train loss: 0.9956 | Train acc: 50.84% | Val loss: 0.9953 | Val acc: 52.48% | LR: 0.000010
Epoch: 061 | Train loss: 0.9966 | Train acc: 50.49% | Val loss: 0.9953 | Val acc: 52.44% | LR: 0.000010
Epoch: 062 | Train loss: 0.9946 | Train acc: 51.21% | Val loss: 0.9953 | Val acc: 52.52% | LR: 0.000009
Epoch: 063 | Train loss: 0.9968 | Train acc: 50.59% | Val loss: 0.9953 | Val acc: 52.45% | LR: 0.000009

[I 2025-09-23 19:28:43,224] Trial 164 finished with value: 0.5231283783912659 and parameters: {'lr': 1.4563684218588592e-05, 'hidden_size': 68, 'dropout': 0.20986808278801478, 'weight_decay': 0.00010720635828301437}. Best is trial 163 with value: 0.5466681122779846.

Epoch: 000 | Train loss: 1.0018 | Train acc: 49.63% | Val loss: 1.0013 | Val acc: 48.82% | LR: 0.000013
Epoch: 001 | Train loss: 1.0026 | Train acc: 49.17% | Val loss: 1.0006 | Val acc: 48.92% | LR: 0.000013
Epoch: 002 | Train loss: 1.0007 | Train acc: 50.24% | Val loss: 1.0008 | Val acc: 48.88% | LR: 0.000013
Epoch: 003 | Train loss: 1.0018 | Train acc: 49.27% | Val loss: 1.0006 | Val acc: 48.98% | LR: 0.000013
Epoch: 004 | Train loss: 1.0021 | Train acc: 49.62% | Val loss: 1.0006 | Val acc: 48.96% | LR: 0.000013
Epoch: 005 | Train loss: 1.0011 | Train acc: 49.81% | Val loss: 1.0006 | Val acc: 49.00% | LR: 0.000013
Epoch: 006 | Train loss: 1.0012 | Train acc: 50.07% | Val loss: 1.0006 | Val acc: 48.98% | LR: 0.000013
Epoch: 007 | Train loss: 1.0012 | Train acc: 49.56% | Val loss: 1.0006 | Val acc: 48.90% | LR: 0.000013
Epoch: 008 | Train loss: 1.0020 | Train acc: 49.53% | Val loss: 1.0004 | Val acc: 48.88% | LR: 0.000013
Epoch: 009 | Train loss: 1.0017 | Train acc: 49.66% | Val loss: 1.0006 | Val acc: 48.90% | LR: 0.000013
Epoch: 010 | Train loss: 1.0011 | Train acc: 49.66% | Val loss: 1.0006 | Val acc: 48.72% | LR: 0.000013
Epoch: 011 | Train loss: 1.0011 | Train acc: 49.74% | Val loss: 1.0007 | Val acc: 48.76% | LR: 0.000013
Epoch: 012 | Train loss: 1.0011 | Train acc: 49.57% | Val loss: 1.0008 | Val acc: 48.80% | LR: 0.000013
Epoch: 013 | Train loss: 1.0014 | Train acc: 49.66% | Val loss: 1.0004 | Val acc: 48.78% | LR: 0.000013
Epoch: 014 | Train loss: 1.0011 | Train acc: 49.76% | Val loss: 1.0008 | Val acc: 48.60% | LR: 0.000013
Epoch: 015 | Train loss: 1.0005 | Train acc: 50.10% | Val loss: 1.0008 | Val acc: 48.68% | LR: 0.000013
Epoch: 016 | Train loss: 1.0008 | Train acc: 49.67% | Val loss: 1.0007 | Val acc: 48.66% | LR: 0.000013
Epoch: 017 | Train loss: 1.0015 | Train acc: 49.59% | Val loss: 1.0003 | Val acc: 48.77% | LR: 0.000013
Epoch: 018 | Train loss: 1.0008 | Train acc: 49.73% | Val loss: 1.0007 | Val acc: 48.73% | LR: 0.000013
Epoch: 019 | Train loss: 1.0009 | Train acc: 49.66% | Val loss: 1.0006 | Val acc: 48.69% | LR: 0.000013
Epoch: 020 | Train loss: 1.0013 | Train acc: 49.65% | Val loss: 1.0007 | Val acc: 48.65% | LR: 0.000013
Epoch: 021 | Train loss: 1.0008 | Train acc: 49.81% | Val loss: 1.0008 | Val acc: 48.57% | LR: 0.000013
Epoch: 022 | Train loss: 1.0005 | Train acc: 49.02% | Val loss: 1.0007 | Val acc: 48.61% | LR: 0.000012
Epoch: 023 | Train loss: 1.0007 | Train acc: 49.62% | Val loss: 1.0007 | Val acc: 48.53% | LR: 0.000012
Epoch: 024 | Train loss: 1.0006 | Train acc: 50.16% | Val loss: 1.0006 | Val acc: 48.59% | LR: 0.000012
Epoch: 025 | Train loss: 1.0007 | Train acc: 49.54% | Val loss: 1.0011 | Val acc: 48.47% | LR: 0.000012
Epoch: 026 | Train loss: 1.0004 | Train acc: 49.69% | Val loss: 1.0007 | Val acc: 48.53% | LR: 0.000012
Epoch: 027 | Train loss: 1.0010 | Train acc: 49.61% | Val loss: 1.0005 | Val acc: 48.55% | LR: 0.000012
Epoch: 028 | Train loss: 1.0009 | Train acc: 49.77% | Val loss: 1.0002 | Val acc: 48.59% | LR: 0.000012
Epoch: 029 | Train loss: 1.0005 | Train acc: 50.06% | Val loss: 1.0006 | Val acc: 48.69% | LR: 0.000012
Epoch: 030 | Train loss: 1.0003 | Train acc: 50.30% | Val loss: 1.0006 | Val acc: 48.65% | LR: 0.000012
Epoch: 031 | Train loss: 1.0005 | Train acc: 50.47% | Val loss: 1.0003 | Val acc: 48.71% | LR: 0.000012
Epoch: 032 | Train loss: 0.9997 | Train acc: 50.85% | Val loss: 1.0002 | Val acc: 48.67% | LR: 0.000012
Epoch: 033 | Train loss: 0.9999 | Train acc: 50.70% | Val loss: 1.0006 | Val acc: 48.63% | LR: 0.000012
Epoch: 034 | Train loss: 1.0002 | Train acc: 50.57% | Val loss: 1.0008 | Val acc: 48.63% | LR: 0.000012
Epoch: 035 | Train loss: 1.0009 | Train acc: 50.14% | Val loss: 1.0003 | Val acc: 48.60% | LR: 0.000012
Epoch: 036 | Train loss: 1.0003 | Train acc: 50.68% | Val loss: 1.0013 | Val acc: 48.72% | LR: 0.000011
Epoch: 037 | Train loss: 1.0007 | Train acc: 50.12% | Val loss: 1.0004 | Val acc: 48.72% | LR: 0.000011
Epoch: 038 | Train loss: 0.9996 | Train acc: 50.77% | Val loss: 1.0010 | Val acc: 48.76% | LR: 0.000011
Epoch: 039 | Train loss: 1.0001 | Train acc: 50.30% | Val loss: 1.0003 | Val acc: 48.80% | LR: 0.000011
Epoch: 040 | Train loss: 0.9999 | Train acc: 50.30% | Val loss: 1.0014 | Val acc: 48.74% | LR: 0.000011
Epoch: 041 | Train loss: 0.9994 | Train acc: 50.39% | Val loss: 1.0008 | Val acc: 48.78% | LR: 0.000011
Epoch: 042 | Train loss: 0.9998 | Train acc: 50.83% | Val loss: 1.0009 | Val acc: 48.70% | LR: 0.000011
Epoch: 043 | Train loss: 0.9984 | Train acc: 50.63% | Val loss: 1.0010 | Val acc: 48.63% | LR: 0.000011
Epoch: 044 | Train loss: 1.0578 | Train acc: 50.70% | Val loss: 1.0009 | Val acc: 48.66% | LR: 0.000011
Epoch: 045 | Train loss: 1.0048 | Train acc: 50.42% | Val loss: 1.0002 | Val acc: 48.77% | LR: 0.000011
Epoch: 046 | Train loss: 1.0054 | Train acc: 50.21% | Val loss: 1.0002 | Val acc: 48.77% | LR: 0.000010
Epoch: 047 | Train loss: 1.1561 | Train acc: 50.14% | Val loss: 1.0003 | Val acc: 48.77% | LR: 0.000010
Epoch: 048 | Train loss: 1.0022 | Train acc: 50.07% | Val loss: 1.0003 | Val acc: 48.77% | LR: 0.000010
Epoch: 049 | Train loss: 1.0007 | Train acc: 50.20% | Val loss: 1.0015 | Val acc: 48.73% | LR: 0.000010
Epoch: 050 | Train loss: 1.0004 | Train acc: 50.16% | Val loss: 1.0004 | Val acc: 48.76% | LR: 0.000010
Epoch: 051 | Train loss: 1.0003 | Train acc: 50.48% | Val loss: 1.0000 | Val acc: 48.72% | LR: 0.000010
Epoch: 052 | Train loss: 0.9994 | Train acc: 50.62% | Val loss: 1.0010 | Val acc: 48.62% | LR: 0.000010
Epoch: 053 | Train loss: 0.9999 | Train acc: 50.28% | Val loss: 1.0009 | Val acc: 48.58% | LR: 0.000010
Epoch: 054 | Train loss: 0.9986 | Train acc: 50.71% | Val loss: 1.0005 | Val acc: 48.77% | LR: 0.000010

[I 2025-09-23 19:29:30,153] Trial 165 finished with value: 0.4874762237071991 and parameters: {'lr': 1.3187463411975215e-05, 'hidden_size': 71, 'dropout': 0.1892195107736699, 'weight_decay': 6.761965262520727e-05}. Best is trial 163 with value: 0.5466681122779846.

Epoch: 000 | Train loss: 1.0005 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.05% | LR: 0.000012
Epoch: 001 | Train loss: 1.0010 | Train acc: 49.72% | Val loss: 0.9917 | Val acc: 54.11% | LR: 0.000012
Epoch: 002 | Train loss: 0.9997 | Train acc: 50.25% | Val loss: 0.9915 | Val acc: 54.13% | LR: 0.000012
Epoch: 003 | Train loss: 0.9992 | Train acc: 50.49% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000012
Epoch: 004 | Train loss: 0.9998 | Train acc: 50.16% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000012
Epoch: 005 | Train loss: 0.9978 | Train acc: 50.87% | Val loss: 0.9917 | Val acc: 54.15% | LR: 0.000012
Epoch: 006 | Train loss: 0.9985 | Train acc: 50.52% | Val loss: 0.9917 | Val acc: 54.17% | LR: 0.000012
Epoch: 007 | Train loss: 0.9996 | Train acc: 49.98% | Val loss: 0.9917 | Val acc: 54.24% | LR: 0.000012
Epoch: 008 | Train loss: 1.0000 | Train acc: 49.72% | Val loss: 0.9919 | Val acc: 54.26% | LR: 0.000012
Epoch: 009 | Train loss: 0.9981 | Train acc: 50.60% | Val loss: 0.9919 | Val acc: 54.30% | LR: 0.000012
Epoch: 010 | Train loss: 0.9977 | Train acc: 50.78% | Val loss: 0.9919 | Val acc: 54.28% | LR: 0.000012
Epoch: 011 | Train loss: 0.9974 | Train acc: 50.87% | Val loss: 0.9919 | Val acc: 54.26% | LR: 0.000012
Epoch: 012 | Train loss: 0.9977 | Train acc: 50.69% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000012
Epoch: 013 | Train loss: 0.9975 | Train acc: 50.43% | Val loss: 0.9917 | Val acc: 54.30% | LR: 0.000012
Epoch: 014 | Train loss: 0.9983 | Train acc: 50.43% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000012
Epoch: 015 | Train loss: 0.9979 | Train acc: 50.16% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000012
Epoch: 016 | Train loss: 1.0451 | Train acc: 50.73% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000012
Epoch: 017 | Train loss: 0.9988 | Train acc: 50.30% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000012
Epoch: 018 | Train loss: 0.9985 | Train acc: 50.26% | Val loss: 0.9917 | Val acc: 54.32% | LR: 0.000012
Epoch: 019 | Train loss: 0.9987 | Train acc: 50.31% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000012
Epoch: 020 | Train loss: 0.9972 | Train acc: 51.09% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000012
Epoch: 021 | Train loss: 0.9977 | Train acc: 50.60% | Val loss: 0.9916 | Val acc: 54.36% | LR: 0.000012
Epoch: 022 | Train loss: 0.9977 | Train acc: 50.81% | Val loss: 0.9916 | Val acc: 54.38% | LR: 0.000011
Epoch: 023 | Train loss: 0.9981 | Train acc: 50.27% | Val loss: 0.9915 | Val acc: 54.36% | LR: 0.000011
Epoch: 024 | Train loss: 0.9977 | Train acc: 50.33% | Val loss: 0.9915 | Val acc: 54.42% | LR: 0.000011
Epoch: 025 | Train loss: 0.9983 | Train acc: 50.08% | Val loss: 0.9915 | Val acc: 54.46% | LR: 0.000011
Epoch: 026 | Train loss: 0.9977 | Train acc: 50.29% | Val loss: 0.9914 | Val acc: 54.43% | LR: 0.000011
Epoch: 027 | Train loss: 0.9973 | Train acc: 50.80% | Val loss: 0.9915 | Val acc: 54.36% | LR: 0.000011
Epoch: 028 | Train loss: 0.9970 | Train acc: 50.77% | Val loss: 0.9914 | Val acc: 54.32% | LR: 0.000011
Epoch: 029 | Train loss: 0.9968 | Train acc: 50.74% | Val loss: 0.9914 | Val acc: 54.28% | LR: 0.000011
Epoch: 030 | Train loss: 0.9981 | Train acc: 50.40% | Val loss: 0.9913 | Val acc: 54.30% | LR: 0.000011
Epoch: 031 | Train loss: 0.9991 | Train acc: 50.34% | Val loss: 0.9913 | Val acc: 54.32% | LR: 0.000011
Epoch: 032 | Train loss: 0.9960 | Train acc: 51.06% | Val loss: 0.9914 | Val acc: 54.38% | LR: 0.000011
Epoch: 033 | Train loss: 0.9981 | Train acc: 49.94% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000011
Epoch: 034 | Train loss: 0.9960 | Train acc: 50.91% | Val loss: 0.9904 | Val acc: 54.32% | LR: 0.000011
Epoch: 035 | Train loss: 0.9990 | Train acc: 50.39% | Val loss: 0.9914 | Val acc: 54.35% | LR: 0.000011
Epoch: 036 | Train loss: 0.9973 | Train acc: 50.47% | Val loss: 0.9912 | Val acc: 54.37% | LR: 0.000011
Epoch: 037 | Train loss: 0.9971 | Train acc: 50.38% | Val loss: 0.9914 | Val acc: 54.29% | LR: 0.000010
Epoch: 038 | Train loss: 0.9981 | Train acc: 50.27% | Val loss: 0.9912 | Val acc: 54.23% | LR: 0.000010
Epoch: 039 | Train loss: 0.9964 | Train acc: 50.81% | Val loss: 0.9912 | Val acc: 54.33% | LR: 0.000010
Epoch: 040 | Train loss: 0.9985 | Train acc: 50.87% | Val loss: 0.9916 | Val acc: 54.33% | LR: 0.000010
Epoch: 041 | Train loss: 0.9988 | Train acc: 50.50% | Val loss: 0.9910 | Val acc: 54.33% | LR: 0.000010
Epoch: 042 | Train loss: 0.9996 | Train acc: 50.09% | Val loss: 0.9910 | Val acc: 54.41% | LR: 0.000010
Epoch: 043 | Train loss: 0.9986 | Train acc: 50.44% | Val loss: 0.9911 | Val acc: 54.31% | LR: 0.000010
Epoch: 044 | Train loss: 0.9991 | Train acc: 50.29% | Val loss: 0.9907 | Val acc: 54.37% | LR: 0.000010
Epoch: 045 | Train loss: 0.9989 | Train acc: 50.53% | Val loss: 0.9911 | Val acc: 54.39% | LR: 0.000010
Epoch: 046 | Train loss: 0.9973 | Train acc: 50.76% | Val loss: 0.9915 | Val acc: 54.35% | LR: 0.000010
Epoch: 047 | Train loss: 0.9997 | Train acc: 50.17% | Val loss: 0.9917 | Val acc: 54.43% | LR: 0.000010
Epoch: 048 | Train loss: 0.9986 | Train acc: 50.74% | Val loss: 0.9915 | Val acc: 54.40% | LR: 0.000009
Epoch: 049 | Train loss: 0.9984 | Train acc: 50.56% | Val loss: 0.9912 | Val acc: 54.42% | LR: 0.000009
Epoch: 050 | Train loss: 0.9993 | Train acc: 50.38% | Val loss: 0.9913 | Val acc: 54.35% | LR: 0.000009
Epoch: 051 | Train loss: 0.9986 | Train acc: 50.58% | Val loss: 0.9912 | Val acc: 54.29% | LR: 0.000009
Epoch: 052 | Train loss: 0.9985 | Train acc: 50.48% | Val loss: 0.9913 | Val acc: 54.35% | LR: 0.000009
Epoch: 053 | Train loss: 0.9992 | Train acc: 50.29% | Val loss: 0.9913 | Val acc: 54.33% | LR: 0.000009
Epoch: 054 | Train loss: 0.9980 | Train acc: 50.74% | Val loss: 0.9912 | Val acc: 54.31% | LR: 0.000009
Epoch: 055 | Train loss: 0.9978 | Train acc: 50.75% | Val loss: 0.9914 | Val acc: 54.43% | LR: 0.000009
Epoch: 056 | Train loss: 0.9971 | Train acc: 50.96% | Val loss: 0.9910 | Val acc: 54.44% | LR: 0.000009
Epoch: 057 | Train loss: 0.9987 | Train acc: 50.42% | Val loss: 0.9913 | Val acc: 54.44% | LR: 0.000009
Epoch: 058 | Train loss: 0.9988 | Train acc: 50.50% | Val loss: 0.9917 | Val acc: 54.45% | LR: 0.000008
Epoch: 059 | Train loss: 0.9970 | Train acc: 50.95% | Val loss: 0.9912 | Val acc: 54.52% | LR: 0.000008
Epoch: 060 | Train loss: 0.9976 | Train acc: 50.68% | Val loss: 0.9913 | Val acc: 54.51% | LR: 0.000008
Epoch: 061 | Train loss: 0.9982 | Train acc: 50.42% | Val loss: 0.9918 | Val acc: 54.56% | LR: 0.000008
Epoch: 062 | Train loss: 0.9982 | Train acc: 50.50% | Val loss: 0.9911 | Val acc: 54.56% | LR: 0.000008
Epoch: 063 | Train loss: 0.9983 | Train acc: 50.43% | Val loss: 0.9915 | Val acc: 54.47% | LR: 0.000008
Epoch: 064 | Train loss: 0.9979 | Train acc: 50.80% | Val loss: 0.9905 | Val acc: 54.58% | LR: 0.000008
Epoch: 065 | Train loss: 0.9975 | Train acc: 50.82% | Val loss: 0.9912 | Val acc: 54.60% | LR: 0.000008
Epoch: 066 | Train loss: 0.9986 | Train acc: 50.29% | Val loss: 0.9911 | Val acc: 54.48% | LR: 0.000007
Epoch: 067 | Train loss: 0.9961 | Train acc: 51.35% | Val loss: 0.9912 | Val acc: 54.54% | LR: 0.000007
Epoch: 068 | Train loss: 0.9972 | Train acc: 50.83% | Val loss: 0.9924 | Val acc: 54.58% | LR: 0.000007
Epoch: 069 | Train loss: 0.9981 | Train acc: 50.59% | Val loss: 0.9918 | Val acc: 54.58% | LR: 0.000007
Epoch: 070 | Train loss: 0.9965 | Train acc: 51.05% | Val loss: 0.9906 | Val acc: 54.78% | LR: 0.000007
Epoch: 071 | Train loss: 0.9973 | Train acc: 50.79% | Val loss: 0.9913 | Val acc: 54.60% | LR: 0.000007
Epoch: 072 | Train loss: 0.9991 | Train acc: 50.76% | Val loss: 0.9911 | Val acc: 54.62% | LR: 0.000007
Epoch: 073 | Train loss: 0.9989 | Train acc: 50.05% | Val loss: 0.9914 | Val acc: 54.58% | LR: 0.000007
Epoch: 074 | Train loss: 0.9955 | Train acc: 51.39% | Val loss: 0.9915 | Val acc: 54.54% | LR: 0.000007
Epoch: 075 | Train loss: 0.9959 | Train acc: 51.12% | Val loss: 0.9913 | Val acc: 54.56% | LR: 0.000006
Epoch: 076 | Train loss: 0.9986 | Train acc: 50.33% | Val loss: 0.9912 | Val acc: 54.60% | LR: 0.000006
Epoch: 077 | Train loss: 0.9980 | Train acc: 50.34% | Val loss: 0.9913 | Val acc: 54.64% | LR: 0.000006
Epoch: 078 | Train loss: 0.9971 | Train acc: 50.70% | Val loss: 0.9913 | Val acc: 54.61% | LR: 0.000006
Epoch: 079 | Train loss: 0.9974 | Train acc: 50.79% | Val loss: 0.9912 | Val acc: 54.61% | LR: 0.000006
Epoch: 080 | Train loss: 0.9965 | Train acc: 51.15% | Val loss: 0.9911 | Val acc: 54.65% | LR: 0.000006
Epoch: 081 | Train loss: 0.9973 | Train acc: 50.71% | Val loss: 0.9911 | Val acc: 54.55% | LR: 0.000006
Epoch: 082 | Train loss: 0.9961 | Train acc: 51.40% | Val loss: 0.9915 | Val acc: 54.59% | LR: 0.000006
Epoch: 083 | Train loss: 0.9976 | Train acc: 50.36% | Val loss: 0.9912 | Val acc: 54.54% | LR: 0.000006
Epoch: 084 | Train loss: 0.9967 | Train acc: 50.78% | Val loss: 0.9911 | Val acc: 54.55% | LR: 0.000005
Epoch: 085 | Train loss: 0.9986 | Train acc: 50.34% | Val loss: 0.9911 | Val acc: 54.53% | LR: 0.000005
Epoch: 086 | Train loss: 0.9973 | Train acc: 50.69% | Val loss: 0.9911 | Val acc: 54.57% | LR: 0.000005
Epoch: 087 | Train loss: 0.9967 | Train acc: 50.71% | Val loss: 0.9911 | Val acc: 54.58% | LR: 0.000005
Epoch: 088 | Train loss: 0.9970 | Train acc: 50.71% | Val loss: 0.9911 | Val acc: 54.53% | LR: 0.000005
Epoch: 089 | Train loss: 0.9974 | Train acc: 50.62% | Val loss: 0.9912 | Val acc: 54.55% | LR: 0.000005
Epoch: 090 | Train loss: 0.9971 | Train acc: 50.80% | Val loss: 0.9919 | Val acc: 54.51% | LR: 0.000005
Epoch: 091 | Train loss: 0.9966 | Train acc: 50.99% | Val loss: 0.9912 | Val acc: 54.57% | LR: 0.000005
Epoch: 092 | Train loss: 0.9962 | Train acc: 50.63% | Val loss: 0.9912 | Val acc: 54.57% | LR: 0.000005
Epoch: 093 | Train loss: 0.9963 | Train acc: 50.87% | Val loss: 0.9915 | Val acc: 54.53% | LR: 0.000004
Epoch: 094 | Train loss: 0.9957 | Train acc: 51.23% | Val loss: 0.9915 | Val acc: 54.53% | LR: 0.000004
Epoch: 095 | Train loss: 0.9973 | Train acc: 50.88% | Val loss: 0.9921 | Val acc: 54.51% | LR: 0.000004
Epoch: 096 | Train loss: 0.9961 | Train acc: 50.96% | Val loss: 0.9919 | Val acc: 54.51% | LR: 0.000004
Epoch: 097 | Train loss: 0.9967 | Train acc: 50.71% | Val loss: 0.9914 | Val acc: 54.57% | LR: 0.000004
Epoch: 098 | Train loss: 0.9975 | Train acc: 50.98% | Val loss: 0.9912 | Val acc: 54.59% | LR: 0.000004
Epoch: 099 | Train loss: 0.9970 | Train acc: 51.08% | Val loss: 0.9912 | Val acc: 54.55% | LR: 0.000004
Epoch: 100 | Train loss: 0.9961 | Train acc: 50.56% | Val loss: 0.9911 | Val acc: 54.63% | LR: 0.000004
Epoch: 101 | Train loss: 0.9965 | Train acc: 50.98% | Val loss: 0.9911 | Val acc: 54.63% | LR: 0.000004
Epoch: 102 | Train loss: 0.9960 | Train acc: 51.06% | Val loss: 0.9916 | Val acc: 54.57% | LR: 0.000003
Epoch: 103 | Train loss: 0.9966 | Train acc: 50.91% | Val loss: 0.9911 | Val acc: 54.59% | LR: 0.000003
Epoch: 104 | Train loss: 0.9972 | Train acc: 50.65% | Val loss: 0.9912 | Val acc: 54.59% | LR: 0.000003
Epoch: 105 | Train loss: 0.9962 | Train acc: 51.16% | Val loss: 0.9912 | Val acc: 54.57% | LR: 0.000003
Epoch: 106 | Train loss: 0.9973 | Train acc: 50.91% | Val loss: 0.9911 | Val acc: 54.57% | LR: 0.000003
Epoch: 107 | Train loss: 0.9964 | Train acc: 51.06% | Val loss: 0.9922 | Val acc: 54.53% | LR: 0.000003
Epoch: 108 | Train loss: 0.9980 | Train acc: 50.18% | Val loss: 0.9914 | Val acc: 54.48% | LR: 0.000003
Epoch: 109 | Train loss: 0.9968 | Train acc: 50.97% | Val loss: 0.9915 | Val acc: 54.45% | LR: 0.000003
Epoch: 110 | Train loss: 0.9962 | Train acc: 50.63% | Val loss: 0.9918 | Val acc: 54.45% | LR: 0.000003
Epoch: 111 | Train loss: 0.9956 | Train acc: 50.88% | Val loss: 0.9915 | Val acc: 54.45% | LR: 0.000003
Epoch: 112 | Train loss: 0.9968 | Train acc: 50.33% | Val loss: 0.9915 | Val acc: 54.45% | LR: 0.000003
Epoch: 113 | Train loss: 0.9964 | Train acc: 50.43% | Val loss: 0.9914 | Val acc: 54.51% | LR: 0.000003
Epoch: 114 | Train loss: 0.9966 | Train acc: 50.36% | Val loss: 0.9914 | Val acc: 54.51% | LR: 0.000002
Epoch: 115 | Train loss: 0.9964 | Train acc: 51.14% | Val loss: 0.9915 | Val acc: 54.52% | LR: 0.000002
Epoch: 116 | Train loss: 0.9953 | Train acc: 51.21% | Val loss: 0.9916 | Val acc: 54.49% | LR: 0.000002
Epoch: 117 | Train loss: 0.9973 | Train acc: 50.44% | Val loss: 0.9916 | Val acc: 54.58% | LR: 0.000002
Epoch: 118 | Train loss: 0.9966 | Train acc: 50.51% | Val loss: 0.9924 | Val acc: 54.60% | LR: 0.000002
Epoch: 119 | Train loss: 0.9972 | Train acc: 50.87% | Val loss: 0.9944 | Val acc: 54.56% | LR: 0.000002

[I 2025-09-23 19:30:56,243] Trial 166 finished with value: 0.5450543880462646 and parameters: {'lr': 1.2130178541398631e-05, 'hidden_size': 64, 'dropout': 0.1987267606659758, 'weight_decay': 8.203262514995546e-05}. Best is trial 163 with value: 0.5466681122779846.

Epoch: 000 | Train loss: 0.9994 | Train acc: 50.36% | Val loss: 0.9986 | Val acc: 51.61% | LR: 0.000012
Epoch: 001 | Train loss: 0.9992 | Train acc: 51.14% | Val loss: 0.9984 | Val acc: 51.83% | LR: 0.000012
Epoch: 002 | Train loss: 0.9990 | Train acc: 51.05% | Val loss: 0.9983 | Val acc: 51.81% | LR: 0.000012
Epoch: 003 | Train loss: 0.9989 | Train acc: 50.89% | Val loss: 0.9983 | Val acc: 51.85% | LR: 0.000012
Epoch: 004 | Train loss: 0.9989 | Train acc: 50.71% | Val loss: 0.9982 | Val acc: 51.49% | LR: 0.000012
Epoch: 005 | Train loss: 0.9984 | Train acc: 50.97% | Val loss: 0.9981 | Val acc: 51.55% | LR: 0.000012
Epoch: 006 | Train loss: 0.9976 | Train acc: 51.78% | Val loss: 0.9980 | Val acc: 51.65% | LR: 0.000012
Epoch: 007 | Train loss: 0.9974 | Train acc: 50.96% | Val loss: 0.9979 | Val acc: 51.81% | LR: 0.000012
Epoch: 008 | Train loss: 0.9967 | Train acc: 51.04% | Val loss: 0.9978 | Val acc: 51.76% | LR: 0.000012
Epoch: 009 | Train loss: 0.9961 | Train acc: 51.20% | Val loss: 0.9978 | Val acc: 51.74% | LR: 0.000012
Epoch: 010 | Train loss: 0.9986 | Train acc: 51.23% | Val loss: 0.9978 | Val acc: 51.66% | LR: 0.000012
Epoch: 011 | Train loss: 1.0004 | Train acc: 51.42% | Val loss: 0.9977 | Val acc: 51.72% | LR: 0.000012
Epoch: 012 | Train loss: 0.9973 | Train acc: 51.63% | Val loss: 0.9976 | Val acc: 51.72% | LR: 0.000012
Epoch: 013 | Train loss: 0.9977 | Train acc: 51.11% | Val loss: 0.9975 | Val acc: 51.74% | LR: 0.000012
Epoch: 014 | Train loss: 0.9988 | Train acc: 50.68% | Val loss: 0.9975 | Val acc: 51.80% | LR: 0.000012
Epoch: 015 | Train loss: 0.9987 | Train acc: 50.60% | Val loss: 0.9974 | Val acc: 51.82% | LR: 0.000012
Epoch: 016 | Train loss: 0.9974 | Train acc: 50.93% | Val loss: 0.9974 | Val acc: 51.62% | LR: 0.000012
Epoch: 017 | Train loss: 0.9997 | Train acc: 50.84% | Val loss: 0.9973 | Val acc: 51.60% | LR: 0.000012
Epoch: 018 | Train loss: 0.9986 | Train acc: 50.57% | Val loss: 0.9973 | Val acc: 51.60% | LR: 0.000012
Epoch: 019 | Train loss: 0.9975 | Train acc: 50.95% | Val loss: 0.9972 | Val acc: 51.68% | LR: 0.000012
Epoch: 020 | Train loss: 0.9977 | Train acc: 50.82% | Val loss: 0.9972 | Val acc: 51.68% | LR: 0.000012
Epoch: 021 | Train loss: 1.0062 | Train acc: 50.86% | Val loss: 0.9972 | Val acc: 51.64% | LR: 0.000011
Epoch: 022 | Train loss: 0.9980 | Train acc: 51.05% | Val loss: 0.9971 | Val acc: 51.70% | LR: 0.000011
Epoch: 023 | Train loss: 0.9946 | Train acc: 51.08% | Val loss: 0.9970 | Val acc: 51.59% | LR: 0.000011
Epoch: 024 | Train loss: 0.9956 | Train acc: 51.25% | Val loss: 0.9969 | Val acc: 51.53% | LR: 0.000011
Epoch: 025 | Train loss: 1.0025 | Train acc: 50.90% | Val loss: 0.9968 | Val acc: 51.61% | LR: 0.000011
Epoch: 026 | Train loss: 0.9997 | Train acc: 50.99% | Val loss: 0.9968 | Val acc: 51.67% | LR: 0.000011
Epoch: 027 | Train loss: 0.9965 | Train acc: 50.92% | Val loss: 0.9967 | Val acc: 51.94% | LR: 0.000011
Epoch: 028 | Train loss: 0.9940 | Train acc: 51.16% | Val loss: 0.9966 | Val acc: 51.94% | LR: 0.000011
Epoch: 029 | Train loss: 0.9974 | Train acc: 50.90% | Val loss: 0.9966 | Val acc: 51.96% | LR: 0.000011
Epoch: 030 | Train loss: 0.9959 | Train acc: 50.83% | Val loss: 0.9965 | Val acc: 51.96% | LR: 0.000011
Epoch: 031 | Train loss: 0.9951 | Train acc: 50.97% | Val loss: 0.9965 | Val acc: 52.02% | LR: 0.000011
Epoch: 032 | Train loss: 0.9955 | Train acc: 50.99% | Val loss: 0.9964 | Val acc: 51.96% | LR: 0.000011
Epoch: 033 | Train loss: 0.9982 | Train acc: 50.63% | Val loss: 0.9963 | Val acc: 51.99% | LR: 0.000011
Epoch: 034 | Train loss: 0.9996 | Train acc: 50.74% | Val loss: 0.9962 | Val acc: 52.10% | LR: 0.000011
Epoch: 035 | Train loss: 0.9949 | Train acc: 51.17% | Val loss: 0.9961 | Val acc: 52.20% | LR: 0.000011
Epoch: 036 | Train loss: 0.9961 | Train acc: 50.90% | Val loss: 0.9961 | Val acc: 52.12% | LR: 0.000010
Epoch: 037 | Train loss: 0.9959 | Train acc: 51.00% | Val loss: 0.9960 | Val acc: 52.12% | LR: 0.000010
Epoch: 038 | Train loss: 0.9976 | Train acc: 50.82% | Val loss: 0.9960 | Val acc: 52.08% | LR: 0.000010
Epoch: 039 | Train loss: 0.9953 | Train acc: 50.80% | Val loss: 0.9960 | Val acc: 52.02% | LR: 0.000010
Epoch: 040 | Train loss: 0.9944 | Train acc: 51.26% | Val loss: 0.9959 | Val acc: 52.12% | LR: 0.000010
Epoch: 041 | Train loss: 0.9966 | Train acc: 51.18% | Val loss: 0.9957 | Val acc: 52.06% | LR: 0.000010
Epoch: 042 | Train loss: 0.9918 | Train acc: 51.11% | Val loss: 0.9956 | Val acc: 52.14% | LR: 0.000010
Epoch: 043 | Train loss: 0.9972 | Train acc: 50.56% | Val loss: 0.9955 | Val acc: 52.12% | LR: 0.000010
Epoch: 044 | Train loss: 0.9972 | Train acc: 50.75% | Val loss: 0.9955 | Val acc: 52.18% | LR: 0.000010
Epoch: 045 | Train loss: 0.9935 | Train acc: 50.73% | Val loss: 0.9954 | Val acc: 52.24% | LR: 0.000010
Epoch: 046 | Train loss: 0.9988 | Train acc: 51.02% | Val loss: 0.9954 | Val acc: 52.28% | LR: 0.000010
Epoch: 047 | Train loss: 0.9979 | Train acc: 51.17% | Val loss: 0.9954 | Val acc: 52.22% | LR: 0.000009
Epoch: 048 | Train loss: 0.9947 | Train acc: 51.11% | Val loss: 0.9952 | Val acc: 52.26% | LR: 0.000009
Epoch: 049 | Train loss: 0.9958 | Train acc: 51.09% | Val loss: 0.9950 | Val acc: 52.44% | LR: 0.000009
Epoch: 050 | Train loss: 0.9936 | Train acc: 51.03% | Val loss: 0.9949 | Val acc: 52.48% | LR: 0.000009
Epoch: 051 | Train loss: 1.0230 | Train acc: 51.55% | Val loss: 0.9948 | Val acc: 52.46% | LR: 0.000009
Epoch: 052 | Train loss: 0.9957 | Train acc: 50.94% | Val loss: 0.9948 | Val acc: 52.50% | LR: 0.000009
Epoch: 053 | Train loss: 0.9984 | Train acc: 50.84% | Val loss: 0.9947 | Val acc: 52.50% | LR: 0.000009
Epoch: 054 | Train loss: 0.9959 | Train acc: 50.66% | Val loss: 0.9946 | Val acc: 52.46% | LR: 0.000009
Epoch: 055 | Train loss: 0.9918 | Train acc: 51.47% | Val loss: 0.9946 | Val acc: 52.42% | LR: 0.000009
Epoch: 056 | Train loss: 0.9939 | Train acc: 51.21% | Val loss: 0.9945 | Val acc: 52.36% | LR: 0.000009
Epoch: 057 | Train loss: 0.9969 | Train acc: 50.85% | Val loss: 0.9945 | Val acc: 52.28% | LR: 0.000008
Epoch: 058 | Train loss: 1.0290 | Train acc: 50.76% | Val loss: 0.9945 | Val acc: 52.20% | LR: 0.000008
Epoch: 059 | Train loss: 0.9933 | Train acc: 51.46% | Val loss: 0.9945 | Val acc: 52.22% | LR: 0.000008
Epoch: 060 | Train loss: 0.9942 | Train acc: 50.91% | Val loss: 0.9944 | Val acc: 52.22% | LR: 0.000008
Epoch: 061 | Train loss: 0.9963 | Train acc: 50.83% | Val loss: 0.9943 | Val acc: 52.29% | LR: 0.000008
Epoch: 062 | Train loss: 0.9946 | Train acc: 50.99% | Val loss: 0.9941 | Val acc: 52.42% | LR: 0.000008
Epoch: 063 | Train loss: 0.9943 | Train acc: 51.35% | Val loss: 0.9940 | Val acc: 52.41% | LR: 0.000008
Epoch: 064 | Train loss: 1.0033 | Train acc: 51.06% | Val loss: 0.9939 | Val acc: 52.48% | LR: 0.000008
Epoch: 065 | Train loss: 0.9946 | Train acc: 50.80% | Val loss: 0.9939 | Val acc: 52.46% | LR: 0.000008
Epoch: 066 | Train loss: 0.9936 | Train acc: 50.71% | Val loss: 0.9938 | Val acc: 52.45% | LR: 0.000007
Epoch: 067 | Train loss: 0.9947 | Train acc: 51.15% | Val loss: 0.9938 | Val acc: 52.45% | LR: 0.000007
Epoch: 068 | Train loss: 0.9941 | Train acc: 50.88% | Val loss: 0.9937 | Val acc: 52.45% | LR: 0.000007
Epoch: 069 | Train loss: 0.9923 | Train acc: 50.64% | Val loss: 0.9936 | Val acc: 52.45% | LR: 0.000007
Epoch: 070 | Train loss: 0.9954 | Train acc: 50.98% | Val loss: 0.9936 | Val acc: 52.51% | LR: 0.000007
Epoch: 071 | Train loss: 0.9950 | Train acc: 50.80% | Val loss: 0.9935 | Val acc: 52.51% | LR: 0.000007
Epoch: 072 | Train loss: 0.9985 | Train acc: 50.35% | Val loss: 0.9934 | Val acc: 52.63% | LR: 0.000007
Epoch: 073 | Train loss: 0.9966 | Train acc: 50.52% | Val loss: 0.9933 | Val acc: 52.63% | LR: 0.000007
Epoch: 074 | Train loss: 0.9910 | Train acc: 50.96% | Val loss: 0.9933 | Val acc: 52.75% | LR: 0.000007
Epoch: 075 | Train loss: 0.9935 | Train acc: 51.04% | Val loss: 0.9933 | Val acc: 52.71% | LR: 0.000006
Epoch: 076 | Train loss: 0.9942 | Train acc: 50.88% | Val loss: 0.9932 | Val acc: 52.77% | LR: 0.000006
Epoch: 077 | Train loss: 0.9926 | Train acc: 51.22% | Val loss: 0.9932 | Val acc: 52.77% | LR: 0.000006
Epoch: 078 | Train loss: 0.9936 | Train acc: 51.29% | Val loss: 0.9931 | Val acc: 52.77% | LR: 0.000006
Epoch: 079 | Train loss: 0.9954 | Train acc: 50.59% | Val loss: 0.9931 | Val acc: 52.83% | LR: 0.000006
Epoch: 080 | Train loss: 1.0071 | Train acc: 50.95% | Val loss: 0.9930 | Val acc: 52.85% | LR: 0.000006
Epoch: 081 | Train loss: 0.9950 | Train acc: 51.39% | Val loss: 0.9930 | Val acc: 52.77% | LR: 0.000006
Epoch: 082 | Train loss: 0.9959 | Train acc: 50.85% | Val loss: 0.9929 | Val acc: 52.81% | LR: 0.000006
Epoch: 083 | Train loss: 0.9949 | Train acc: 50.86% | Val loss: 0.9928 | Val acc: 52.77% | LR: 0.000005
Epoch: 084 | Train loss: 0.9934 | Train acc: 50.95% | Val loss: 0.9928 | Val acc: 52.77% | LR: 0.000005
Epoch: 085 | Train loss: 0.9945 | Train acc: 50.67% | Val loss: 0.9927 | Val acc: 52.75% | LR: 0.000005
Epoch: 086 | Train loss: 0.9911 | Train acc: 51.46% | Val loss: 0.9926 | Val acc: 52.75% | LR: 0.000005
Epoch: 087 | Train loss: 0.9933 | Train acc: 51.01% | Val loss: 0.9926 | Val acc: 52.81% | LR: 0.000005
Epoch: 088 | Train loss: 0.9949 | Train acc: 51.01% | Val loss: 0.9925 | Val acc: 52.83% | LR: 0.000005
Epoch: 089 | Train loss: 0.9935 | Train acc: 50.75% | Val loss: 0.9925 | Val acc: 52.83% | LR: 0.000005
Epoch: 090 | Train loss: 0.9921 | Train acc: 51.19% | Val loss: 0.9924 | Val acc: 52.85% | LR: 0.000005
Epoch: 091 | Train loss: 0.9925 | Train acc: 50.92% | Val loss: 0.9924 | Val acc: 52.85% | LR: 0.000005
Epoch: 092 | Train loss: 0.9946 | Train acc: 50.76% | Val loss: 0.9923 | Val acc: 52.87% | LR: 0.000004
Epoch: 093 | Train loss: 0.9955 | Train acc: 50.41% | Val loss: 0.9923 | Val acc: 52.85% | LR: 0.000004
Epoch: 094 | Train loss: 0.9922 | Train acc: 51.12% | Val loss: 0.9923 | Val acc: 52.85% | LR: 0.000004
Epoch: 095 | Train loss: 0.9975 | Train acc: 50.49% | Val loss: 0.9923 | Val acc: 52.85% | LR: 0.000004
Epoch: 096 | Train loss: 0.9925 | Train acc: 51.12% | Val loss: 0.9922 | Val acc: 52.87% | LR: 0.000004
Epoch: 097 | Train loss: 0.9948 | Train acc: 50.60% | Val loss: 0.9922 | Val acc: 52.83% | LR: 0.000004
Epoch: 098 | Train loss: 0.9921 | Train acc: 51.40% | Val loss: 0.9921 | Val acc: 52.87% | LR: 0.000004
Epoch: 099 | Train loss: 0.9923 | Train acc: 51.03% | Val loss: 0.9921 | Val acc: 52.86% | LR: 0.000004
Epoch: 100 | Train loss: 0.9948 | Train acc: 50.68% | Val loss: 0.9920 | Val acc: 52.82% | LR: 0.000004
Epoch: 101 | Train loss: 0.9913 | Train acc: 50.94% | Val loss: 0.9920 | Val acc: 52.76% | LR: 0.000004
Epoch: 102 | Train loss: 0.9900 | Train acc: 51.57% | Val loss: 0.9919 | Val acc: 52.76% | LR: 0.000003
Epoch: 103 | Train loss: 0.9915 | Train acc: 51.03% | Val loss: 0.9919 | Val acc: 52.74% | LR: 0.000003
Epoch: 104 | Train loss: 0.9913 | Train acc: 51.48% | Val loss: 0.9919 | Val acc: 52.76% | LR: 0.000003
Epoch: 105 | Train loss: 0.9909 | Train acc: 51.22% | Val loss: 0.9918 | Val acc: 52.78% | LR: 0.000003
Epoch: 106 | Train loss: 0.9958 | Train acc: 50.60% | Val loss: 0.9918 | Val acc: 52.78% | LR: 0.000003
Epoch: 107 | Train loss: 0.9947 | Train acc: 50.67% | Val loss: 0.9918 | Val acc: 52.83% | LR: 0.000003
Epoch: 108 | Train loss: 1.0006 | Train acc: 50.41% | Val loss: 0.9917 | Val acc: 52.83% | LR: 0.000003
Epoch: 109 | Train loss: 0.9951 | Train acc: 50.31% | Val loss: 0.9917 | Val acc: 52.83% | LR: 0.000003
Epoch: 110 | Train loss: 0.9924 | Train acc: 51.13% | Val loss: 0.9917 | Val acc: 52.83% | LR: 0.000003
Epoch: 111 | Train loss: 0.9933 | Train acc: 50.95% | Val loss: 0.9916 | Val acc: 52.81% | LR: 0.000003
Epoch: 112 | Train loss: 0.9928 | Train acc: 51.03% | Val loss: 0.9916 | Val acc: 52.77% | LR: 0.000003
Epoch: 113 | Train loss: 0.9969 | Train acc: 50.59% | Val loss: 0.9916 | Val acc: 52.77% | LR: 0.000002
Epoch: 114 | Train loss: 0.9936 | Train acc: 51.22% | Val loss: 0.9916 | Val acc: 52.79% | LR: 0.000002
Epoch: 115 | Train loss: 0.9949 | Train acc: 50.69% | Val loss: 0.9916 | Val acc: 52.79% | LR: 0.000002
Epoch: 116 | Train loss: 0.9933 | Train acc: 51.13% | Val loss: 0.9915 | Val acc: 52.77% | LR: 0.000002
Epoch: 117 | Train loss: 0.9957 | Train acc: 50.33% | Val loss: 0.9915 | Val acc: 52.73% | LR: 0.000002
Epoch: 118 | Train loss: 0.9961 | Train acc: 51.47% | Val loss: 0.9915 | Val acc: 52.75% | LR: 0.000002
Epoch: 119 | Train loss: 0.9925 | Train acc: 51.20% | Val loss: 0.9915 | Val acc: 52.77% | LR: 0.000002
Epoch: 120 | Train loss: 0.9935 | Train acc: 50.93% | Val loss: 0.9914 | Val acc: 52.77% | LR: 0.000002
Epoch: 121 | Train loss: 0.9929 | Train acc: 51.03% | Val loss: 0.9914 | Val acc: 52.77% | LR: 0.000002
Epoch: 122 | Train loss: 0.9906 | Train acc: 51.31% | Val loss: 0.9914 | Val acc: 52.79% | LR: 0.000002
Epoch: 123 | Train loss: 0.9952 | Train acc: 50.77% | Val loss: 0.9914 | Val acc: 52.75% | LR: 0.000002
Epoch: 124 | Train loss: 0.9945 | Train acc: 50.40% | Val loss: 0.9914 | Val acc: 52.77% | LR: 0.000002
Epoch: 125 | Train loss: 0.9945 | Train acc: 51.01% | Val loss: 0.9913 | Val acc: 52.77% | LR: 0.000002
Epoch: 126 | Train loss: 0.9920 | Train acc: 51.53% | Val loss: 0.9913 | Val acc: 52.77% | LR: 0.000002
Epoch: 127 | Train loss: 0.9949 | Train acc: 50.47% | Val loss: 0.9913 | Val acc: 52.77% | LR: 0.000002
Epoch: 128 | Train loss: 0.9912 | Train acc: 51.19% | Val loss: 0.9913 | Val acc: 52.77% | LR: 0.000002
Epoch: 129 | Train loss: 0.9977 | Train acc: 50.05% | Val loss: 0.9913 | Val acc: 52.77% | LR: 0.000001
Epoch: 130 | Train loss: 0.9925 | Train acc: 50.75% | Val loss: 0.9912 | Val acc: 52.77% | LR: 0.000001
Epoch: 131 | Train loss: 0.9956 | Train acc: 50.31% | Val loss: 0.9912 | Val acc: 52.77% | LR: 0.000001
Epoch: 132 | Train loss: 0.9904 | Train acc: 51.01% | Val loss: 0.9912 | Val acc: 52.77% | LR: 0.000001
Epoch: 133 | Train loss: 0.9972 | Train acc: 50.31% | Val loss: 0.9912 | Val acc: 52.73% | LR: 0.000001
Epoch: 134 | Train loss: 0.9930 | Train acc: 50.93% | Val loss: 0.9911 | Val acc: 52.73% | LR: 0.000001
Epoch: 135 | Train loss: 0.9950 | Train acc: 50.30% | Val loss: 0.9912 | Val acc: 52.73% | LR: 0.000001
Epoch: 136 | Train loss: 0.9888 | Train acc: 51.63% | Val loss: 0.9911 | Val acc: 52.75% | LR: 0.000001
Epoch: 137 | Train loss: 0.9932 | Train acc: 51.10% | Val loss: 0.9911 | Val acc: 52.75% | LR: 0.000001
Epoch: 138 | Train loss: 1.0024 | Train acc: 51.09% | Val loss: 0.9911 | Val acc: 52.75% | LR: 0.000001
Epoch: 139 | Train loss: 0.9915 | Train acc: 51.10% | Val loss: 0.9911 | Val acc: 52.75% | LR: 0.000001
Epoch: 140 | Train loss: 0.9926 | Train acc: 50.75% | Val loss: 0.9911 | Val acc: 52.79% | LR: 0.000001
Epoch: 141 | Train loss: 0.9912 | Train acc: 51.11% | Val loss: 0.9911 | Val acc: 52.79% | LR: 0.000001
Epoch: 142 | Train loss: 0.9960 | Train acc: 50.31% | Val loss: 0.9911 | Val acc: 52.79% | LR: 0.000001
Epoch: 143 | Train loss: 0.9957 | Train acc: 50.57% | Val loss: 0.9911 | Val acc: 52.79% | LR: 0.000001
Epoch: 144 | Train loss: 0.9918 | Train acc: 51.01% | Val loss: 0.9911 | Val acc: 52.79% | LR: 0.000001
Epoch: 145 | Train loss: 0.9964 | Train acc: 50.58% | Val loss: 0.9910 | Val acc: 52.73% | LR: 0.000001
Epoch: 146 | Train loss: 0.9916 | Train acc: 51.19% | Val loss: 0.9910 | Val acc: 52.73% | LR: 0.000001
Epoch: 147 | Train loss: 0.9916 | Train acc: 51.01% | Val loss: 0.9910 | Val acc: 52.73% | LR: 0.000001

[I 2025-09-23 19:32:54,575] Trial 167 finished with value: 0.5272907137870788 and parameters: {'lr': 1.2055233326321923e-05, 'hidden_size': 76, 'dropout': 0.1718785181890728, 'weight_decay': 8.501972982399431e-05}. Best is trial 163 with value: 0.5466681122779846.

Epoch: 000 | Train loss: 1.0034 | Train acc: 48.82% | Val loss: 0.9973 | Val acc: 53.46% | LR: 0.000015
Epoch: 001 | Train loss: 1.0021 | Train acc: 49.19% | Val loss: 0.9973 | Val acc: 53.54% | LR: 0.000015
Epoch: 002 | Train loss: 1.0011 | Train acc: 49.46% | Val loss: 0.9972 | Val acc: 53.71% | LR: 0.000015
Epoch: 003 | Train loss: 1.0024 | Train acc: 48.98% | Val loss: 0.9971 | Val acc: 53.79% | LR: 0.000015
Epoch: 004 | Train loss: 1.0020 | Train acc: 49.26% | Val loss: 0.9972 | Val acc: 53.95% | LR: 0.000014
Epoch: 005 | Train loss: 1.0020 | Train acc: 49.44% | Val loss: 0.9972 | Val acc: 54.01% | LR: 0.000014
Epoch: 006 | Train loss: 1.0017 | Train acc: 49.32% | Val loss: 0.9972 | Val acc: 53.97% | LR: 0.000014
Epoch: 007 | Train loss: 1.0011 | Train acc: 49.52% | Val loss: 0.9972 | Val acc: 54.07% | LR: 0.000014
Epoch: 008 | Train loss: 1.0007 | Train acc: 49.73% | Val loss: 0.9972 | Val acc: 54.13% | LR: 0.000014
Epoch: 009 | Train loss: 1.0003 | Train acc: 49.92% | Val loss: 0.9972 | Val acc: 54.11% | LR: 0.000014
Epoch: 010 | Train loss: 1.0010 | Train acc: 49.55% | Val loss: 0.9971 | Val acc: 54.07% | LR: 0.000014
Epoch: 011 | Train loss: 1.0005 | Train acc: 49.73% | Val loss: 0.9971 | Val acc: 54.09% | LR: 0.000014
Epoch: 012 | Train loss: 0.9999 | Train acc: 50.11% | Val loss: 0.9971 | Val acc: 54.15% | LR: 0.000014
Epoch: 013 | Train loss: 1.0011 | Train acc: 49.33% | Val loss: 0.9970 | Val acc: 54.23% | LR: 0.000014
Epoch: 014 | Train loss: 1.0005 | Train acc: 49.59% | Val loss: 0.9970 | Val acc: 54.27% | LR: 0.000014
Epoch: 015 | Train loss: 0.9999 | Train acc: 49.84% | Val loss: 0.9970 | Val acc: 54.23% | LR: 0.000014
Epoch: 016 | Train loss: 0.9995 | Train acc: 50.23% | Val loss: 0.9969 | Val acc: 54.21% | LR: 0.000014
Epoch: 017 | Train loss: 0.9998 | Train acc: 49.77% | Val loss: 0.9966 | Val acc: 54.07% | LR: 0.000014
Epoch: 018 | Train loss: 1.0000 | Train acc: 49.91% | Val loss: 0.9966 | Val acc: 54.05% | LR: 0.000014
Epoch: 019 | Train loss: 0.9996 | Train acc: 50.23% | Val loss: 0.9965 | Val acc: 54.23% | LR: 0.000014
Epoch: 020 | Train loss: 0.9998 | Train acc: 49.76% | Val loss: 0.9965 | Val acc: 54.16% | LR: 0.000014
Epoch: 021 | Train loss: 0.9997 | Train acc: 50.13% | Val loss: 0.9964 | Val acc: 53.94% | LR: 0.000014
Epoch: 022 | Train loss: 0.9996 | Train acc: 50.41% | Val loss: 0.9964 | Val acc: 54.12% | LR: 0.000014
Epoch: 023 | Train loss: 0.9992 | Train acc: 50.20% | Val loss: 0.9963 | Val acc: 53.96% | LR: 0.000014
Epoch: 024 | Train loss: 0.9991 | Train acc: 50.34% | Val loss: 0.9963 | Val acc: 53.90% | LR: 0.000014
Epoch: 025 | Train loss: 0.9990 | Train acc: 50.76% | Val loss: 0.9962 | Val acc: 53.78% | LR: 0.000014
Epoch: 026 | Train loss: 0.9989 | Train acc: 51.25% | Val loss: 0.9962 | Val acc: 53.70% | LR: 0.000013
Epoch: 027 | Train loss: 0.9991 | Train acc: 50.66% | Val loss: 0.9962 | Val acc: 53.55% | LR: 0.000013
Epoch: 028 | Train loss: 0.9984 | Train acc: 50.81% | Val loss: 0.9963 | Val acc: 53.64% | LR: 0.000013
Epoch: 029 | Train loss: 0.9983 | Train acc: 51.19% | Val loss: 0.9963 | Val acc: 53.85% | LR: 0.000013
Epoch: 030 | Train loss: 0.9982 | Train acc: 50.96% | Val loss: 0.9963 | Val acc: 53.71% | LR: 0.000013
Epoch: 031 | Train loss: 0.9979 | Train acc: 51.06% | Val loss: 0.9962 | Val acc: 53.55% | LR: 0.000013
Epoch: 032 | Train loss: 0.9992 | Train acc: 50.26% | Val loss: 0.9961 | Val acc: 53.55% | LR: 0.000013
Epoch: 033 | Train loss: 0.9984 | Train acc: 50.76% | Val loss: 0.9960 | Val acc: 53.55% | LR: 0.000013
Epoch: 034 | Train loss: 0.9982 | Train acc: 50.81% | Val loss: 0.9960 | Val acc: 53.07% | LR: 0.000013
Epoch: 035 | Train loss: 0.9980 | Train acc: 51.15% | Val loss: 0.9960 | Val acc: 53.25% | LR: 0.000013
Epoch: 036 | Train loss: 0.9980 | Train acc: 50.89% | Val loss: 0.9959 | Val acc: 53.15% | LR: 0.000013
Epoch: 037 | Train loss: 0.9983 | Train acc: 50.71% | Val loss: 0.9958 | Val acc: 53.15% | LR: 0.000013
Epoch: 038 | Train loss: 0.9982 | Train acc: 50.75% | Val loss: 0.9957 | Val acc: 53.22% | LR: 0.000012
Epoch: 039 | Train loss: 0.9978 | Train acc: 50.92% | Val loss: 0.9956 | Val acc: 53.24% | LR: 0.000012
Epoch: 040 | Train loss: 0.9962 | Train acc: 51.54% | Val loss: 0.9957 | Val acc: 53.20% | LR: 0.000012
Epoch: 041 | Train loss: 0.9970 | Train acc: 51.12% | Val loss: 0.9957 | Val acc: 53.24% | LR: 0.000012
Epoch: 042 | Train loss: 0.9980 | Train acc: 50.48% | Val loss: 0.9958 | Val acc: 53.42% | LR: 0.000012
Epoch: 043 | Train loss: 0.9984 | Train acc: 50.62% | Val loss: 0.9958 | Val acc: 53.41% | LR: 0.000012
Epoch: 044 | Train loss: 0.9974 | Train acc: 50.74% | Val loss: 0.9957 | Val acc: 53.38% | LR: 0.000012
Epoch: 045 | Train loss: 0.9967 | Train acc: 51.08% | Val loss: 0.9958 | Val acc: 53.29% | LR: 0.000012
Epoch: 046 | Train loss: 0.9965 | Train acc: 51.02% | Val loss: 0.9958 | Val acc: 52.97% | LR: 0.000012
Epoch: 047 | Train loss: 0.9966 | Train acc: 51.19% | Val loss: 0.9958 | Val acc: 53.17% | LR: 0.000011
Epoch: 048 | Train loss: 0.9963 | Train acc: 51.12% | Val loss: 0.9957 | Val acc: 53.07% | LR: 0.000011
Epoch: 049 | Train loss: 0.9973 | Train acc: 50.77% | Val loss: 0.9958 | Val acc: 52.83% | LR: 0.000011
Epoch: 050 | Train loss: 0.9973 | Train acc: 50.67% | Val loss: 0.9957 | Val acc: 52.75% | LR: 0.000011
Epoch: 051 | Train loss: 0.9974 | Train acc: 50.68% | Val loss: 0.9956 | Val acc: 52.75% | LR: 0.000011
Epoch: 052 | Train loss: 0.9964 | Train acc: 50.95% | Val loss: 0.9955 | Val acc: 52.75% | LR: 0.000011
Epoch: 053 | Train loss: 0.9962 | Train acc: 50.84% | Val loss: 0.9956 | Val acc: 52.51% | LR: 0.000011
Epoch: 054 | Train loss: 0.9957 | Train acc: 51.07% | Val loss: 0.9955 | Val acc: 52.39% | LR: 0.000011
Epoch: 055 | Train loss: 0.9961 | Train acc: 50.88% | Val loss: 0.9955 | Val acc: 52.37% | LR: 0.000010
Epoch: 056 | Train loss: 0.9973 | Train acc: 50.61% | Val loss: 0.9954 | Val acc: 52.37% | LR: 0.000010
Epoch: 057 | Train loss: 0.9970 | Train acc: 50.65% | Val loss: 0.9955 | Val acc: 52.46% | LR: 0.000010
Epoch: 058 | Train loss: 0.9957 | Train acc: 50.92% | Val loss: 0.9955 | Val acc: 52.39% | LR: 0.000010
Epoch: 059 | Train loss: 0.9985 | Train acc: 50.20% | Val loss: 0.9955 | Val acc: 52.48% | LR: 0.000010
Epoch: 060 | Train loss: 0.9958 | Train acc: 50.84% | Val loss: 0.9954 | Val acc: 52.42% | LR: 0.000010
Epoch: 061 | Train loss: 0.9966 | Train acc: 50.49% | Val loss: 0.9954 | Val acc: 52.48% | LR: 0.000010
Epoch: 062 | Train loss: 0.9947 | Train acc: 51.19% | Val loss: 0.9953 | Val acc: 52.46% | LR: 0.000009
Epoch: 063 | Train loss: 0.9968 | Train acc: 50.57% | Val loss: 0.9953 | Val acc: 52.50% | LR: 0.000009

[I 2025-09-23 19:33:44,533] Trial 168 finished with value: 0.5238968253135681 and parameters: {'lr': 1.4534987748946878e-05, 'hidden_size': 68, 'dropout': 0.19776039516028993, 'weight_decay': 7.208194144630185e-05}. Best is trial 163 with value: 0.5466681122779846.

Epoch: 000 | Train loss: 1.0018 | Train acc: 49.64% | Val loss: 1.0015 | Val acc: 48.82% | LR: 0.000013
Epoch: 001 | Train loss: 1.0028 | Train acc: 49.17% | Val loss: 1.0006 | Val acc: 48.88% | LR: 0.000013
Epoch: 002 | Train loss: 1.0007 | Train acc: 50.24% | Val loss: 1.0006 | Val acc: 48.90% | LR: 0.000013
Epoch: 003 | Train loss: 1.0018 | Train acc: 49.28% | Val loss: 1.0006 | Val acc: 48.94% | LR: 0.000013
Epoch: 004 | Train loss: 1.0020 | Train acc: 49.64% | Val loss: 1.0006 | Val acc: 48.94% | LR: 0.000013
Epoch: 005 | Train loss: 1.0012 | Train acc: 49.82% | Val loss: 1.0001 | Val acc: 49.02% | LR: 0.000013
Epoch: 006 | Train loss: 1.0009 | Train acc: 50.08% | Val loss: 1.0007 | Val acc: 48.91% | LR: 0.000013
Epoch: 007 | Train loss: 1.0015 | Train acc: 49.54% | Val loss: 1.0006 | Val acc: 48.94% | LR: 0.000013
Epoch: 008 | Train loss: 1.0019 | Train acc: 49.54% | Val loss: 1.0006 | Val acc: 48.88% | LR: 0.000013
Epoch: 009 | Train loss: 1.0016 | Train acc: 49.66% | Val loss: 1.0007 | Val acc: 48.92% | LR: 0.000013
Epoch: 010 | Train loss: 1.0012 | Train acc: 49.65% | Val loss: 1.0007 | Val acc: 48.78% | LR: 0.000013
Epoch: 011 | Train loss: 1.0011 | Train acc: 49.75% | Val loss: 1.0002 | Val acc: 48.82% | LR: 0.000013
Epoch: 012 | Train loss: 1.0011 | Train acc: 49.55% | Val loss: 1.0007 | Val acc: 48.76% | LR: 0.000013
Epoch: 013 | Train loss: 1.0016 | Train acc: 49.69% | Val loss: 1.0005 | Val acc: 48.62% | LR: 0.000013
Epoch: 014 | Train loss: 1.0011 | Train acc: 49.76% | Val loss: 1.0009 | Val acc: 48.56% | LR: 0.000013
Epoch: 015 | Train loss: 1.0009 | Train acc: 50.10% | Val loss: 1.0004 | Val acc: 48.66% | LR: 0.000013
Epoch: 016 | Train loss: 1.0008 | Train acc: 49.66% | Val loss: 1.0010 | Val acc: 48.70% | LR: 0.000013
Epoch: 017 | Train loss: 1.0015 | Train acc: 49.60% | Val loss: 1.0005 | Val acc: 48.69% | LR: 0.000013
Epoch: 018 | Train loss: 1.0007 | Train acc: 49.74% | Val loss: 1.0007 | Val acc: 48.59% | LR: 0.000013
Epoch: 019 | Train loss: 1.0016 | Train acc: 49.67% | Val loss: 1.0006 | Val acc: 48.67% | LR: 0.000013
Epoch: 020 | Train loss: 1.0011 | Train acc: 49.57% | Val loss: 1.0007 | Val acc: 48.69% | LR: 0.000013
Epoch: 021 | Train loss: 1.0013 | Train acc: 49.78% | Val loss: 1.0004 | Val acc: 48.55% | LR: 0.000012
Epoch: 022 | Train loss: 1.0003 | Train acc: 50.34% | Val loss: 1.0007 | Val acc: 48.53% | LR: 0.000012
Epoch: 023 | Train loss: 1.0007 | Train acc: 49.94% | Val loss: 1.0006 | Val acc: 48.61% | LR: 0.000012
Epoch: 024 | Train loss: 1.0005 | Train acc: 50.09% | Val loss: 1.0007 | Val acc: 48.55% | LR: 0.000012
Epoch: 025 | Train loss: 1.0007 | Train acc: 49.77% | Val loss: 1.0002 | Val acc: 48.51% | LR: 0.000012
Epoch: 026 | Train loss: 1.0004 | Train acc: 49.68% | Val loss: 1.0013 | Val acc: 48.45% | LR: 0.000012
Epoch: 027 | Train loss: 1.0009 | Train acc: 49.55% | Val loss: 1.0008 | Val acc: 48.51% | LR: 0.000012
Epoch: 028 | Train loss: 1.0010 | Train acc: 49.85% | Val loss: 1.0008 | Val acc: 48.53% | LR: 0.000012
Epoch: 029 | Train loss: 1.0006 | Train acc: 50.14% | Val loss: 1.0006 | Val acc: 48.57% | LR: 0.000012
Epoch: 030 | Train loss: 1.0003 | Train acc: 50.27% | Val loss: 1.0007 | Val acc: 48.53% | LR: 0.000012
Epoch: 031 | Train loss: 1.0005 | Train acc: 50.44% | Val loss: 1.0016 | Val acc: 48.45% | LR: 0.000012
Epoch: 032 | Train loss: 0.9995 | Train acc: 50.82% | Val loss: 1.0004 | Val acc: 48.61% | LR: 0.000012
Epoch: 033 | Train loss: 0.9999 | Train acc: 50.63% | Val loss: 1.0007 | Val acc: 48.55% | LR: 0.000012
Epoch: 034 | Train loss: 1.0001 | Train acc: 50.58% | Val loss: 1.0007 | Val acc: 48.55% | LR: 0.000012
Epoch: 035 | Train loss: 1.0009 | Train acc: 50.08% | Val loss: 1.0009 | Val acc: 48.47% | LR: 0.000011
Epoch: 036 | Train loss: 1.0006 | Train acc: 50.63% | Val loss: 1.0006 | Val acc: 48.53% | LR: 0.000011
Epoch: 037 | Train loss: 1.0007 | Train acc: 50.10% | Val loss: 1.0029 | Val acc: 48.47% | LR: 0.000011
Epoch: 038 | Train loss: 0.9993 | Train acc: 51.01% | Val loss: 1.0032 | Val acc: 48.57% | LR: 0.000011
Epoch: 039 | Train loss: 1.0002 | Train acc: 50.30% | Val loss: 1.0006 | Val acc: 48.63% | LR: 0.000011
Epoch: 040 | Train loss: 1.0000 | Train acc: 50.30% | Val loss: 1.0007 | Val acc: 48.67% | LR: 0.000011
Epoch: 041 | Train loss: 0.9994 | Train acc: 50.47% | Val loss: 1.0006 | Val acc: 48.80% | LR: 0.000011
Epoch: 042 | Train loss: 0.9989 | Train acc: 50.86% | Val loss: 1.0006 | Val acc: 48.78% | LR: 0.000011
Epoch: 043 | Train loss: 0.9990 | Train acc: 50.65% | Val loss: 1.0006 | Val acc: 48.80% | LR: 0.000011
Epoch: 044 | Train loss: 0.9991 | Train acc: 50.73% | Val loss: 1.0005 | Val acc: 48.82% | LR: 0.000011
Epoch: 045 | Train loss: 0.9991 | Train acc: 50.46% | Val loss: 1.0005 | Val acc: 48.84% | LR: 0.000010
Epoch: 046 | Train loss: 0.9992 | Train acc: 50.45% | Val loss: 1.0005 | Val acc: 48.73% | LR: 0.000010
Epoch: 047 | Train loss: 1.0120 | Train acc: 50.27% | Val loss: 1.0005 | Val acc: 48.75% | LR: 0.000010
Epoch: 048 | Train loss: 1.0029 | Train acc: 50.18% | Val loss: 1.0003 | Val acc: 48.73% | LR: 0.000010
Epoch: 049 | Train loss: 1.0076 | Train acc: 50.08% | Val loss: 1.0009 | Val acc: 48.63% | LR: 0.000010
Epoch: 050 | Train loss: 1.0005 | Train acc: 50.13% | Val loss: 1.0005 | Val acc: 48.75% | LR: 0.000010
Epoch: 051 | Train loss: 1.0008 | Train acc: 50.21% | Val loss: 1.0005 | Val acc: 48.77% | LR: 0.000010
Epoch: 052 | Train loss: 1.0012 | Train acc: 50.55% | Val loss: 1.0005 | Val acc: 48.77% | LR: 0.000010
Epoch: 053 | Train loss: 1.0015 | Train acc: 49.94% | Val loss: 1.0005 | Val acc: 48.81% | LR: 0.000010
Epoch: 054 | Train loss: 1.0024 | Train acc: 50.65% | Val loss: 1.0018 | Val acc: 48.81% | LR: 0.000010

[I 2025-09-23 19:34:30,346] Trial 169 finished with value: 0.4880621612071991 and parameters: {'lr': 1.3088520091295146e-05, 'hidden_size': 71, 'dropout': 0.2049286588674082, 'weight_decay': 0.00015335648742629215}. Best is trial 163 with value: 0.5466681122779846.

Epoch: 000 | Train loss: 1.0003 | Train acc: 50.07% | Val loss: 0.9918 | Val acc: 54.09% | LR: 0.000016
Epoch: 001 | Train loss: 1.0007 | Train acc: 49.72% | Val loss: 0.9916 | Val acc: 54.13% | LR: 0.000016
Epoch: 002 | Train loss: 1.0005 | Train acc: 49.54% | Val loss: 0.9916 | Val acc: 54.13% | LR: 0.000016
Epoch: 003 | Train loss: 1.0008 | Train acc: 49.54% | Val loss: 0.9917 | Val acc: 54.11% | LR: 0.000016
Epoch: 004 | Train loss: 1.0015 | Train acc: 49.36% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000016
Epoch: 005 | Train loss: 0.9989 | Train acc: 49.81% | Val loss: 0.9918 | Val acc: 54.17% | LR: 0.000016
Epoch: 006 | Train loss: 1.0010 | Train acc: 49.45% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000016
Epoch: 007 | Train loss: 1.0016 | Train acc: 49.48% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000016
Epoch: 008 | Train loss: 1.0011 | Train acc: 49.56% | Val loss: 0.9920 | Val acc: 54.32% | LR: 0.000016
Epoch: 009 | Train loss: 0.9993 | Train acc: 50.46% | Val loss: 0.9920 | Val acc: 54.26% | LR: 0.000016
Epoch: 010 | Train loss: 0.9988 | Train acc: 50.61% | Val loss: 0.9921 | Val acc: 54.30% | LR: 0.000015
Epoch: 011 | Train loss: 0.9987 | Train acc: 50.70% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000015
Epoch: 012 | Train loss: 0.9983 | Train acc: 50.65% | Val loss: 0.9920 | Val acc: 54.30% | LR: 0.000015
Epoch: 013 | Train loss: 0.9997 | Train acc: 50.36% | Val loss: 0.9919 | Val acc: 54.26% | LR: 0.000015
Epoch: 014 | Train loss: 0.9984 | Train acc: 50.45% | Val loss: 0.9919 | Val acc: 54.30% | LR: 0.000015
Epoch: 015 | Train loss: 0.9999 | Train acc: 50.02% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000015
Epoch: 016 | Train loss: 0.9983 | Train acc: 50.45% | Val loss: 0.9920 | Val acc: 54.34% | LR: 0.000015
Epoch: 017 | Train loss: 0.9990 | Train acc: 50.49% | Val loss: 0.9919 | Val acc: 54.32% | LR: 0.000015
Epoch: 018 | Train loss: 0.9992 | Train acc: 50.29% | Val loss: 0.9919 | Val acc: 54.38% | LR: 0.000015
Epoch: 019 | Train loss: 0.9990 | Train acc: 50.25% | Val loss: 0.9919 | Val acc: 54.46% | LR: 0.000015
Epoch: 020 | Train loss: 0.9977 | Train acc: 51.12% | Val loss: 0.9918 | Val acc: 54.44% | LR: 0.000015
Epoch: 021 | Train loss: 0.9987 | Train acc: 50.60% | Val loss: 0.9922 | Val acc: 54.34% | LR: 0.000015
Epoch: 022 | Train loss: 0.9974 | Train acc: 50.79% | Val loss: 0.9918 | Val acc: 54.34% | LR: 0.000015
Epoch: 023 | Train loss: 0.9985 | Train acc: 50.30% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000015
Epoch: 024 | Train loss: 0.9985 | Train acc: 50.28% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000015
Epoch: 025 | Train loss: 0.9994 | Train acc: 49.95% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000015
Epoch: 026 | Train loss: 0.9985 | Train acc: 50.26% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000015
Epoch: 027 | Train loss: 0.9973 | Train acc: 50.80% | Val loss: 0.9918 | Val acc: 54.31% | LR: 0.000014
Epoch: 028 | Train loss: 0.9968 | Train acc: 50.82% | Val loss: 0.9918 | Val acc: 54.35% | LR: 0.000014
Epoch: 029 | Train loss: 0.9975 | Train acc: 50.84% | Val loss: 0.9917 | Val acc: 54.33% | LR: 0.000014
Epoch: 030 | Train loss: 0.9983 | Train acc: 50.46% | Val loss: 0.9917 | Val acc: 54.39% | LR: 0.000014
Epoch: 031 | Train loss: 0.9983 | Train acc: 50.39% | Val loss: 0.9917 | Val acc: 54.21% | LR: 0.000014
Epoch: 032 | Train loss: 0.9965 | Train acc: 51.13% | Val loss: 0.9916 | Val acc: 54.29% | LR: 0.000014
Epoch: 033 | Train loss: 0.9988 | Train acc: 49.99% | Val loss: 0.9916 | Val acc: 54.29% | LR: 0.000014
Epoch: 034 | Train loss: 0.9963 | Train acc: 50.96% | Val loss: 0.9915 | Val acc: 54.23% | LR: 0.000014
Epoch: 035 | Train loss: 0.9983 | Train acc: 50.54% | Val loss: 0.9916 | Val acc: 54.37% | LR: 0.000014
Epoch: 036 | Train loss: 0.9975 | Train acc: 50.56% | Val loss: 0.9914 | Val acc: 54.40% | LR: 0.000014
Epoch: 037 | Train loss: 0.9977 | Train acc: 50.47% | Val loss: 0.9917 | Val acc: 54.33% | LR: 0.000013
Epoch: 038 | Train loss: 0.9983 | Train acc: 50.41% | Val loss: 0.9917 | Val acc: 54.46% | LR: 0.000013
Epoch: 039 | Train loss: 0.9963 | Train acc: 50.97% | Val loss: 0.9916 | Val acc: 54.46% | LR: 0.000013
Epoch: 040 | Train loss: 0.9969 | Train acc: 50.87% | Val loss: 0.9916 | Val acc: 54.46% | LR: 0.000013
Epoch: 041 | Train loss: 0.9972 | Train acc: 50.79% | Val loss: 0.9916 | Val acc: 54.53% | LR: 0.000013
Epoch: 042 | Train loss: 0.9979 | Train acc: 50.44% | Val loss: 0.9916 | Val acc: 54.53% | LR: 0.000013
Epoch: 043 | Train loss: 0.9977 | Train acc: 50.44% | Val loss: 0.9916 | Val acc: 54.56% | LR: 0.000013
Epoch: 044 | Train loss: 0.9980 | Train acc: 50.35% | Val loss: 0.9916 | Val acc: 54.58% | LR: 0.000013
Epoch: 045 | Train loss: 0.9967 | Train acc: 50.75% | Val loss: 0.9915 | Val acc: 54.60% | LR: 0.000013
Epoch: 046 | Train loss: 0.9960 | Train acc: 51.18% | Val loss: 0.9915 | Val acc: 54.49% | LR: 0.000012
Epoch: 047 | Train loss: 0.9972 | Train acc: 50.32% | Val loss: 0.9915 | Val acc: 54.51% | LR: 0.000012
Epoch: 048 | Train loss: 0.9972 | Train acc: 50.68% | Val loss: 0.9915 | Val acc: 54.64% | LR: 0.000012
Epoch: 049 | Train loss: 0.9974 | Train acc: 50.58% | Val loss: 0.9915 | Val acc: 54.68% | LR: 0.000012
Epoch: 050 | Train loss: 0.9981 | Train acc: 50.54% | Val loss: 0.9915 | Val acc: 54.62% | LR: 0.000012
Epoch: 051 | Train loss: 0.9962 | Train acc: 50.71% | Val loss: 0.9915 | Val acc: 54.52% | LR: 0.000012
Epoch: 052 | Train loss: 0.9986 | Train acc: 50.45% | Val loss: 0.9916 | Val acc: 54.66% | LR: 0.000012
Epoch: 053 | Train loss: 0.9972 | Train acc: 50.55% | Val loss: 0.9915 | Val acc: 54.74% | LR: 0.000011
Epoch: 054 | Train loss: 0.9961 | Train acc: 50.91% | Val loss: 0.9915 | Val acc: 54.66% | LR: 0.000011
Epoch: 055 | Train loss: 0.9961 | Train acc: 50.92% | Val loss: 0.9915 | Val acc: 54.64% | LR: 0.000011
Epoch: 056 | Train loss: 0.9957 | Train acc: 51.09% | Val loss: 0.9915 | Val acc: 54.52% | LR: 0.000011
Epoch: 057 | Train loss: 0.9964 | Train acc: 50.51% | Val loss: 0.9915 | Val acc: 54.64% | LR: 0.000011
Epoch: 058 | Train loss: 0.9974 | Train acc: 50.64% | Val loss: 0.9915 | Val acc: 54.59% | LR: 0.000011
Epoch: 059 | Train loss: 0.9964 | Train acc: 50.14% | Val loss: 0.9915 | Val acc: 54.61% | LR: 0.000011
Epoch: 060 | Train loss: 0.9961 | Train acc: 51.37% | Val loss: 0.9915 | Val acc: 54.63% | LR: 0.000010
Epoch: 061 | Train loss: 0.9955 | Train acc: 51.34% | Val loss: 0.9914 | Val acc: 54.59% | LR: 0.000010
Epoch: 062 | Train loss: 0.9953 | Train acc: 51.17% | Val loss: 0.9914 | Val acc: 54.59% | LR: 0.000010
Epoch: 063 | Train loss: 0.9978 | Train acc: 50.47% | Val loss: 0.9914 | Val acc: 54.53% | LR: 0.000010
Epoch: 064 | Train loss: 0.9969 | Train acc: 50.49% | Val loss: 0.9914 | Val acc: 54.55% | LR: 0.000010
Epoch: 065 | Train loss: 0.9958 | Train acc: 50.71% | Val loss: 0.9914 | Val acc: 54.51% | LR: 0.000010
Epoch: 066 | Train loss: 0.9968 | Train acc: 50.94% | Val loss: 0.9914 | Val acc: 54.62% | LR: 0.000010
Epoch: 067 | Train loss: 0.9960 | Train acc: 50.33% | Val loss: 0.9914 | Val acc: 54.52% | LR: 0.000009
Epoch: 068 | Train loss: 0.9968 | Train acc: 50.36% | Val loss: 0.9914 | Val acc: 54.44% | LR: 0.000009
Epoch: 069 | Train loss: 0.9964 | Train acc: 50.92% | Val loss: 0.9915 | Val acc: 54.56% | LR: 0.000009
Epoch: 070 | Train loss: 0.9945 | Train acc: 50.90% | Val loss: 0.9913 | Val acc: 54.57% | LR: 0.000009
Epoch: 071 | Train loss: 0.9968 | Train acc: 50.61% | Val loss: 0.9914 | Val acc: 54.57% | LR: 0.000009
Epoch: 072 | Train loss: 0.9946 | Train acc: 51.10% | Val loss: 0.9914 | Val acc: 54.63% | LR: 0.000009
Epoch: 073 | Train loss: 0.9959 | Train acc: 51.46% | Val loss: 0.9913 | Val acc: 54.63% | LR: 0.000008
Epoch: 074 | Train loss: 0.9941 | Train acc: 50.87% | Val loss: 0.9914 | Val acc: 54.66% | LR: 0.000008
Epoch: 075 | Train loss: 0.9951 | Train acc: 50.66% | Val loss: 0.9913 | Val acc: 54.40% | LR: 0.000008
Epoch: 076 | Train loss: 0.9962 | Train acc: 50.85% | Val loss: 0.9913 | Val acc: 54.41% | LR: 0.000008
Epoch: 077 | Train loss: 0.9964 | Train acc: 51.28% | Val loss: 0.9913 | Val acc: 54.39% | LR: 0.000008
Epoch: 078 | Train loss: 0.9952 | Train acc: 51.09% | Val loss: 0.9913 | Val acc: 54.30% | LR: 0.000008
Epoch: 079 | Train loss: 0.9959 | Train acc: 51.00% | Val loss: 0.9913 | Val acc: 54.28% | LR: 0.000008
Epoch: 080 | Train loss: 0.9952 | Train acc: 50.76% | Val loss: 0.9913 | Val acc: 54.34% | LR: 0.000007
Epoch: 081 | Train loss: 0.9954 | Train acc: 51.05% | Val loss: 0.9912 | Val acc: 54.44% | LR: 0.000007
Epoch: 082 | Train loss: 0.9951 | Train acc: 50.37% | Val loss: 0.9913 | Val acc: 54.45% | LR: 0.000007
Epoch: 083 | Train loss: 0.9960 | Train acc: 51.09% | Val loss: 0.9913 | Val acc: 54.49% | LR: 0.000007
Epoch: 084 | Train loss: 0.9952 | Train acc: 50.72% | Val loss: 0.9913 | Val acc: 54.51% | LR: 0.000007
Epoch: 085 | Train loss: 0.9972 | Train acc: 50.48% | Val loss: 0.9912 | Val acc: 54.51% | LR: 0.000007
Epoch: 086 | Train loss: 0.9953 | Train acc: 51.00% | Val loss: 0.9912 | Val acc: 54.51% | LR: 0.000007
Epoch: 087 | Train loss: 0.9942 | Train acc: 51.29% | Val loss: 0.9912 | Val acc: 54.43% | LR: 0.000006
Epoch: 088 | Train loss: 0.9951 | Train acc: 50.80% | Val loss: 0.9912 | Val acc: 54.37% | LR: 0.000006
Epoch: 089 | Train loss: 0.9956 | Train acc: 50.78% | Val loss: 0.9912 | Val acc: 54.31% | LR: 0.000006
Epoch: 090 | Train loss: 0.9956 | Train acc: 50.99% | Val loss: 0.9912 | Val acc: 54.28% | LR: 0.000006
Epoch: 091 | Train loss: 0.9951 | Train acc: 50.83% | Val loss: 0.9912 | Val acc: 54.29% | LR: 0.000006
Epoch: 092 | Train loss: 0.9937 | Train acc: 51.60% | Val loss: 0.9912 | Val acc: 54.25% | LR: 0.000006
Epoch: 093 | Train loss: 0.9945 | Train acc: 50.71% | Val loss: 0.9912 | Val acc: 54.25% | LR: 0.000005
Epoch: 094 | Train loss: 0.9945 | Train acc: 50.55% | Val loss: 0.9912 | Val acc: 54.21% | LR: 0.000005
Epoch: 095 | Train loss: 0.9963 | Train acc: 50.68% | Val loss: 0.9912 | Val acc: 54.19% | LR: 0.000005
Epoch: 096 | Train loss: 0.9947 | Train acc: 51.24% | Val loss: 0.9912 | Val acc: 54.21% | LR: 0.000005
Epoch: 097 | Train loss: 0.9968 | Train acc: 51.13% | Val loss: 0.9912 | Val acc: 54.15% | LR: 0.000005
Epoch: 098 | Train loss: 0.9973 | Train acc: 50.42% | Val loss: 0.9912 | Val acc: 54.17% | LR: 0.000005
Epoch: 099 | Train loss: 0.9951 | Train acc: 50.65% | Val loss: 0.9911 | Val acc: 54.11% | LR: 0.000005
Epoch: 100 | Train loss: 0.9914 | Train acc: 51.66% | Val loss: 0.9911 | Val acc: 54.17% | LR: 0.000005
Epoch: 101 | Train loss: 0.9961 | Train acc: 50.82% | Val loss: 0.9911 | Val acc: 54.17% | LR: 0.000004
Epoch: 102 | Train loss: 0.9944 | Train acc: 50.99% | Val loss: 0.9911 | Val acc: 54.09% | LR: 0.000004

[I 2025-09-23 19:35:53,362] Trial 170 finished with value: 0.5409432768821716 and parameters: {'lr': 1.5673038121487345e-05, 'hidden_size': 64, 'dropout': 0.21443718715163243, 'weight_decay': 0.00010349344936413484}. Best is trial 163 with value: 0.5466681122779846.

Epoch: 000 | Train loss: 1.0005 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.05% | LR: 0.000011
Epoch: 001 | Train loss: 1.0007 | Train acc: 49.55% | Val loss: 0.9916 | Val acc: 54.09% | LR: 0.000011
Epoch: 002 | Train loss: 0.9995 | Train acc: 50.35% | Val loss: 0.9916 | Val acc: 54.13% | LR: 0.000011
Epoch: 003 | Train loss: 0.9992 | Train acc: 50.47% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000011
Epoch: 004 | Train loss: 0.9998 | Train acc: 50.16% | Val loss: 0.9917 | Val acc: 54.11% | LR: 0.000011
Epoch: 005 | Train loss: 0.9979 | Train acc: 50.87% | Val loss: 0.9917 | Val acc: 54.13% | LR: 0.000011
Epoch: 006 | Train loss: 0.9986 | Train acc: 50.52% | Val loss: 0.9918 | Val acc: 54.17% | LR: 0.000011
Epoch: 007 | Train loss: 0.9996 | Train acc: 49.98% | Val loss: 0.9918 | Val acc: 54.17% | LR: 0.000011
Epoch: 008 | Train loss: 1.0000 | Train acc: 49.72% | Val loss: 0.9919 | Val acc: 54.24% | LR: 0.000011
Epoch: 009 | Train loss: 0.9982 | Train acc: 50.60% | Val loss: 0.9919 | Val acc: 54.32% | LR: 0.000011
Epoch: 010 | Train loss: 0.9978 | Train acc: 50.78% | Val loss: 0.9920 | Val acc: 54.34% | LR: 0.000011
Epoch: 011 | Train loss: 0.9975 | Train acc: 50.87% | Val loss: 0.9919 | Val acc: 54.32% | LR: 0.000011
Epoch: 012 | Train loss: 0.9978 | Train acc: 50.69% | Val loss: 0.9919 | Val acc: 54.30% | LR: 0.000011
Epoch: 013 | Train loss: 0.9977 | Train acc: 50.43% | Val loss: 0.9918 | Val acc: 54.26% | LR: 0.000011
Epoch: 014 | Train loss: 0.9984 | Train acc: 50.43% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000011
Epoch: 015 | Train loss: 0.9983 | Train acc: 50.15% | Val loss: 0.9918 | Val acc: 54.32% | LR: 0.000011
Epoch: 016 | Train loss: 0.9982 | Train acc: 50.60% | Val loss: 0.9919 | Val acc: 54.28% | LR: 0.000011
Epoch: 017 | Train loss: 0.9974 | Train acc: 50.51% | Val loss: 0.9918 | Val acc: 54.28% | LR: 0.000011
Epoch: 018 | Train loss: 1.0090 | Train acc: 50.15% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000011
Epoch: 019 | Train loss: 0.9992 | Train acc: 50.18% | Val loss: 0.9917 | Val acc: 54.32% | LR: 0.000011
Epoch: 020 | Train loss: 0.9972 | Train acc: 51.13% | Val loss: 0.9917 | Val acc: 54.32% | LR: 0.000011
Epoch: 021 | Train loss: 0.9977 | Train acc: 50.57% | Val loss: 0.9916 | Val acc: 54.34% | LR: 0.000011
Epoch: 022 | Train loss: 0.9977 | Train acc: 50.78% | Val loss: 0.9916 | Val acc: 54.36% | LR: 0.000011
Epoch: 023 | Train loss: 0.9982 | Train acc: 50.24% | Val loss: 0.9915 | Val acc: 54.36% | LR: 0.000011
Epoch: 024 | Train loss: 0.9978 | Train acc: 50.35% | Val loss: 0.9915 | Val acc: 54.40% | LR: 0.000011
Epoch: 025 | Train loss: 0.9984 | Train acc: 50.09% | Val loss: 0.9915 | Val acc: 54.38% | LR: 0.000011
Epoch: 026 | Train loss: 0.9979 | Train acc: 50.27% | Val loss: 0.9914 | Val acc: 54.46% | LR: 0.000011
Epoch: 027 | Train loss: 0.9974 | Train acc: 50.78% | Val loss: 0.9915 | Val acc: 54.40% | LR: 0.000011
Epoch: 028 | Train loss: 0.9970 | Train acc: 50.78% | Val loss: 0.9914 | Val acc: 54.38% | LR: 0.000011
Epoch: 029 | Train loss: 0.9970 | Train acc: 50.78% | Val loss: 0.9910 | Val acc: 54.52% | LR: 0.000010
Epoch: 030 | Train loss: 0.9981 | Train acc: 50.43% | Val loss: 0.9910 | Val acc: 54.42% | LR: 0.000010
Epoch: 031 | Train loss: 0.9987 | Train acc: 50.30% | Val loss: 0.9912 | Val acc: 54.26% | LR: 0.000010
Epoch: 032 | Train loss: 0.9961 | Train acc: 51.00% | Val loss: 0.9910 | Val acc: 54.31% | LR: 0.000010
Epoch: 033 | Train loss: 0.9983 | Train acc: 49.86% | Val loss: 0.9920 | Val acc: 54.28% | LR: 0.000010
Epoch: 034 | Train loss: 0.9964 | Train acc: 50.86% | Val loss: 0.9913 | Val acc: 54.25% | LR: 0.000010
Epoch: 035 | Train loss: 0.9982 | Train acc: 50.28% | Val loss: 0.9911 | Val acc: 54.24% | LR: 0.000010
Epoch: 036 | Train loss: 0.9974 | Train acc: 50.38% | Val loss: 0.9913 | Val acc: 54.24% | LR: 0.000010
Epoch: 037 | Train loss: 0.9974 | Train acc: 50.30% | Val loss: 0.9917 | Val acc: 54.24% | LR: 0.000010
Epoch: 038 | Train loss: 0.9983 | Train acc: 50.26% | Val loss: 0.9909 | Val acc: 54.16% | LR: 0.000010
Epoch: 039 | Train loss: 0.9965 | Train acc: 50.80% | Val loss: 0.9913 | Val acc: 54.22% | LR: 0.000010
Epoch: 040 | Train loss: 0.9972 | Train acc: 50.72% | Val loss: 0.9921 | Val acc: 54.42% | LR: 0.000010
Epoch: 041 | Train loss: 0.9973 | Train acc: 50.55% | Val loss: 0.9917 | Val acc: 54.44% | LR: 0.000010
Epoch: 042 | Train loss: 0.9979 | Train acc: 50.26% | Val loss: 0.9917 | Val acc: 54.34% | LR: 0.000009
Epoch: 043 | Train loss: 0.9982 | Train acc: 50.45% | Val loss: 0.9910 | Val acc: 54.36% | LR: 0.000009
Epoch: 044 | Train loss: 0.9979 | Train acc: 50.19% | Val loss: 0.9911 | Val acc: 54.36% | LR: 0.000009
Epoch: 045 | Train loss: 0.9966 | Train acc: 50.51% | Val loss: 0.9914 | Val acc: 54.31% | LR: 0.000009
Epoch: 046 | Train loss: 0.9962 | Train acc: 50.98% | Val loss: 0.9910 | Val acc: 54.27% | LR: 0.000009
Epoch: 047 | Train loss: 0.9970 | Train acc: 50.15% | Val loss: 0.9911 | Val acc: 54.35% | LR: 0.000009
Epoch: 048 | Train loss: 0.9975 | Train acc: 50.96% | Val loss: 0.9915 | Val acc: 54.33% | LR: 0.000009
Epoch: 049 | Train loss: 1.0175 | Train acc: 50.92% | Val loss: 0.9913 | Val acc: 54.20% | LR: 0.000009
Epoch: 050 | Train loss: 0.9986 | Train acc: 50.18% | Val loss: 0.9913 | Val acc: 54.20% | LR: 0.000009
Epoch: 051 | Train loss: 0.9964 | Train acc: 50.83% | Val loss: 0.9908 | Val acc: 54.31% | LR: 0.000009
Epoch: 052 | Train loss: 0.9989 | Train acc: 50.08% | Val loss: 0.9910 | Val acc: 54.27% | LR: 0.000009
Epoch: 053 | Train loss: 0.9976 | Train acc: 50.64% | Val loss: 0.9910 | Val acc: 54.37% | LR: 0.000008
Epoch: 054 | Train loss: 0.9964 | Train acc: 50.73% | Val loss: 0.9910 | Val acc: 54.43% | LR: 0.000008
Epoch: 055 | Train loss: 0.9965 | Train acc: 50.60% | Val loss: 0.9913 | Val acc: 54.43% | LR: 0.000008
Epoch: 056 | Train loss: 0.9966 | Train acc: 50.86% | Val loss: 0.9910 | Val acc: 54.43% | LR: 0.000008
Epoch: 057 | Train loss: 0.9969 | Train acc: 50.76% | Val loss: 0.9913 | Val acc: 54.39% | LR: 0.000008
Epoch: 058 | Train loss: 0.9976 | Train acc: 50.48% | Val loss: 0.9912 | Val acc: 54.43% | LR: 0.000008
Epoch: 059 | Train loss: 1.0255 | Train acc: 50.87% | Val loss: 0.9912 | Val acc: 54.47% | LR: 0.000008
Epoch: 060 | Train loss: 1.1655 | Train acc: 50.25% | Val loss: 0.9912 | Val acc: 54.43% | LR: 0.000008
Epoch: 061 | Train loss: 0.9966 | Train acc: 51.03% | Val loss: 0.9912 | Val acc: 54.47% | LR: 0.000008
Epoch: 062 | Train loss: 0.9958 | Train acc: 51.02% | Val loss: 0.9912 | Val acc: 54.51% | LR: 0.000008
Epoch: 063 | Train loss: 0.9981 | Train acc: 50.30% | Val loss: 0.9912 | Val acc: 54.41% | LR: 0.000007
Epoch: 064 | Train loss: 0.9971 | Train acc: 50.37% | Val loss: 0.9915 | Val acc: 54.37% | LR: 0.000007
Epoch: 065 | Train loss: 0.9965 | Train acc: 50.37% | Val loss: 0.9912 | Val acc: 54.33% | LR: 0.000007
Epoch: 066 | Train loss: 0.9973 | Train acc: 50.62% | Val loss: 0.9912 | Val acc: 54.30% | LR: 0.000007
Epoch: 067 | Train loss: 0.9973 | Train acc: 49.99% | Val loss: 0.9916 | Val acc: 54.31% | LR: 0.000007
Epoch: 068 | Train loss: 0.9975 | Train acc: 50.02% | Val loss: 0.9911 | Val acc: 54.39% | LR: 0.000007
Epoch: 069 | Train loss: 0.9970 | Train acc: 50.79% | Val loss: 0.9913 | Val acc: 54.46% | LR: 0.000007
Epoch: 070 | Train loss: 0.9953 | Train acc: 50.80% | Val loss: 0.9913 | Val acc: 54.40% | LR: 0.000007
Epoch: 071 | Train loss: 0.9976 | Train acc: 50.42% | Val loss: 0.9912 | Val acc: 54.37% | LR: 0.000007
Epoch: 072 | Train loss: 0.9957 | Train acc: 50.97% | Val loss: 0.9913 | Val acc: 54.35% | LR: 0.000006
Epoch: 073 | Train loss: 0.9972 | Train acc: 50.79% | Val loss: 0.9912 | Val acc: 54.35% | LR: 0.000006
Epoch: 074 | Train loss: 1.0131 | Train acc: 50.33% | Val loss: 0.9911 | Val acc: 54.35% | LR: 0.000006
Epoch: 075 | Train loss: 1.0047 | Train acc: 50.43% | Val loss: 0.9914 | Val acc: 54.35% | LR: 0.000006
Epoch: 076 | Train loss: 1.0232 | Train acc: 50.70% | Val loss: 0.9914 | Val acc: 54.35% | LR: 0.000006
Epoch: 077 | Train loss: 0.9986 | Train acc: 50.76% | Val loss: 0.9911 | Val acc: 54.29% | LR: 0.000006
Epoch: 078 | Train loss: 0.9970 | Train acc: 50.63% | Val loss: 0.9914 | Val acc: 54.29% | LR: 0.000006

[I 2025-09-23 19:36:53,513] Trial 171 finished with value: 0.5434502243995667 and parameters: {'lr': 1.1453981950494848e-05, 'hidden_size': 64, 'dropout': 0.23043702917577302, 'weight_decay': 5.918242035001922e-05}. Best is trial 163 with value: 0.5466681122779846.

Epoch: 000 | Train loss: 0.9995 | Train acc: 50.41% | Val loss: 1.0175 | Val acc: 46.02% | LR: 0.000011
Epoch: 001 | Train loss: 0.9993 | Train acc: 50.28% | Val loss: 1.0069 | Val acc: 46.02% | LR: 0.000011
Epoch: 002 | Train loss: 0.9999 | Train acc: 49.73% | Val loss: 1.0084 | Val acc: 46.37% | LR: 0.000011
Epoch: 003 | Train loss: 0.9987 | Train acc: 50.46% | Val loss: 1.0060 | Val acc: 46.14% | LR: 0.000011
Epoch: 004 | Train loss: 0.9988 | Train acc: 50.90% | Val loss: 1.0075 | Val acc: 46.16% | LR: 0.000011
Epoch: 005 | Train loss: 0.9990 | Train acc: 50.63% | Val loss: 1.0071 | Val acc: 46.38% | LR: 0.000011
Epoch: 006 | Train loss: 0.9990 | Train acc: 50.12% | Val loss: 1.0286 | Val acc: 46.04% | LR: 0.000011
Epoch: 007 | Train loss: 0.9991 | Train acc: 50.58% | Val loss: 1.0078 | Val acc: 46.28% | LR: 0.000011
Epoch: 008 | Train loss: 0.9994 | Train acc: 50.20% | Val loss: 1.0070 | Val acc: 46.24% | LR: 0.000011
Epoch: 009 | Train loss: 0.9986 | Train acc: 50.91% | Val loss: 1.0057 | Val acc: 46.32% | LR: 0.000011
Epoch: 010 | Train loss: 0.9997 | Train acc: 49.78% | Val loss: 1.0094 | Val acc: 46.24% | LR: 0.000011
Epoch: 011 | Train loss: 1.0017 | Train acc: 50.12% | Val loss: 1.0061 | Val acc: 46.15% | LR: 0.000011
Epoch: 012 | Train loss: 0.9994 | Train acc: 50.58% | Val loss: 1.0055 | Val acc: 46.23% | LR: 0.000011
Epoch: 013 | Train loss: 0.9992 | Train acc: 50.41% | Val loss: 1.0058 | Val acc: 46.24% | LR: 0.000011
Epoch: 014 | Train loss: 0.9982 | Train acc: 50.84% | Val loss: 1.0067 | Val acc: 46.27% | LR: 0.000011
Epoch: 015 | Train loss: 0.9988 | Train acc: 50.18% | Val loss: 1.0059 | Val acc: 46.22% | LR: 0.000011
Epoch: 016 | Train loss: 0.9991 | Train acc: 50.82% | Val loss: 1.0079 | Val acc: 46.16% | LR: 0.000011
Epoch: 017 | Train loss: 0.9980 | Train acc: 50.84% | Val loss: 1.0069 | Val acc: 46.09% | LR: 0.000011
Epoch: 018 | Train loss: 0.9990 | Train acc: 50.13% | Val loss: 1.0070 | Val acc: 46.15% | LR: 0.000011
Epoch: 019 | Train loss: 0.9984 | Train acc: 50.76% | Val loss: 1.0068 | Val acc: 46.09% | LR: 0.000011
Epoch: 020 | Train loss: 0.9987 | Train acc: 50.76% | Val loss: 1.0076 | Val acc: 46.16% | LR: 0.000011
Epoch: 021 | Train loss: 0.9993 | Train acc: 50.33% | Val loss: 1.0064 | Val acc: 46.17% | LR: 0.000011
Epoch: 022 | Train loss: 0.9992 | Train acc: 50.22% | Val loss: 1.0095 | Val acc: 46.02% | LR: 0.000011
Epoch: 023 | Train loss: 0.9982 | Train acc: 50.44% | Val loss: 1.0068 | Val acc: 46.06% | LR: 0.000011
Epoch: 024 | Train loss: 0.9983 | Train acc: 50.76% | Val loss: 1.0069 | Val acc: 46.04% | LR: 0.000011
Epoch: 025 | Train loss: 0.9977 | Train acc: 50.85% | Val loss: 1.0070 | Val acc: 46.11% | LR: 0.000010
Epoch: 026 | Train loss: 0.9984 | Train acc: 50.59% | Val loss: 1.0074 | Val acc: 46.03% | LR: 0.000010
Epoch: 027 | Train loss: 0.9982 | Train acc: 50.53% | Val loss: 1.3311 | Val acc: 46.15% | LR: 0.000010
Epoch: 028 | Train loss: 0.9991 | Train acc: 50.15% | Val loss: 1.0063 | Val acc: 46.09% | LR: 0.000010
Epoch: 029 | Train loss: 0.9979 | Train acc: 50.67% | Val loss: 1.0063 | Val acc: 46.19% | LR: 0.000010
Epoch: 030 | Train loss: 0.9971 | Train acc: 50.94% | Val loss: 1.0077 | Val acc: 46.14% | LR: 0.000010
Epoch: 031 | Train loss: 0.9988 | Train acc: 50.39% | Val loss: 1.0060 | Val acc: 46.11% | LR: 0.000010
Epoch: 032 | Train loss: 0.9977 | Train acc: 50.49% | Val loss: 1.0067 | Val acc: 46.18% | LR: 0.000010
Epoch: 033 | Train loss: 1.0001 | Train acc: 49.80% | Val loss: 1.0080 | Val acc: 46.22% | LR: 0.000010
Epoch: 034 | Train loss: 0.9988 | Train acc: 50.12% | Val loss: 1.0078 | Val acc: 46.09% | LR: 0.000010
Epoch: 035 | Train loss: 0.9986 | Train acc: 50.22% | Val loss: 1.0065 | Val acc: 46.14% | LR: 0.000010
Epoch: 036 | Train loss: 0.9982 | Train acc: 50.52% | Val loss: 1.0062 | Val acc: 46.20% | LR: 0.000010
Epoch: 037 | Train loss: 0.9973 | Train acc: 50.77% | Val loss: 1.0063 | Val acc: 46.21% | LR: 0.000010
Epoch: 038 | Train loss: 0.9989 | Train acc: 49.96% | Val loss: 1.0066 | Val acc: 46.04% | LR: 0.000010
Epoch: 039 | Train loss: 0.9987 | Train acc: 50.23% | Val loss: 1.0070 | Val acc: 46.07% | LR: 0.000010
Epoch: 040 | Train loss: 0.9974 | Train acc: 50.76% | Val loss: 1.0072 | Val acc: 46.07% | LR: 0.000009
Epoch: 041 | Train loss: 0.9979 | Train acc: 50.42% | Val loss: 1.0062 | Val acc: 46.11% | LR: 0.000009
Epoch: 042 | Train loss: 0.9976 | Train acc: 50.49% | Val loss: 1.0081 | Val acc: 46.01% | LR: 0.000009
Epoch: 043 | Train loss: 0.9977 | Train acc: 50.55% | Val loss: 1.0078 | Val acc: 45.98% | LR: 0.000009
Epoch: 044 | Train loss: 0.9980 | Train acc: 50.43% | Val loss: 1.0073 | Val acc: 45.96% | LR: 0.000009
Epoch: 045 | Train loss: 0.9976 | Train acc: 50.70% | Val loss: 1.0059 | Val acc: 46.04% | LR: 0.000009
Epoch: 046 | Train loss: 0.9963 | Train acc: 51.03% | Val loss: 1.0071 | Val acc: 46.07% | LR: 0.000009
Epoch: 047 | Train loss: 0.9983 | Train acc: 50.14% | Val loss: 1.0059 | Val acc: 46.06% | LR: 0.000009
Epoch: 048 | Train loss: 0.9969 | Train acc: 50.67% | Val loss: 1.0069 | Val acc: 46.02% | LR: 0.000009
Epoch: 049 | Train loss: 0.9978 | Train acc: 50.52% | Val loss: 1.0071 | Val acc: 45.92% | LR: 0.000009
Epoch: 050 | Train loss: 0.9992 | Train acc: 50.17% | Val loss: 1.0061 | Val acc: 45.98% | LR: 0.000009
Epoch: 051 | Train loss: 0.9966 | Train acc: 50.77% | Val loss: 1.0062 | Val acc: 45.99% | LR: 0.000008
Epoch: 052 | Train loss: 0.9997 | Train acc: 49.80% | Val loss: 1.0068 | Val acc: 45.85% | LR: 0.000008
Epoch: 053 | Train loss: 0.9987 | Train acc: 50.16% | Val loss: 1.0063 | Val acc: 45.89% | LR: 0.000008
Epoch: 054 | Train loss: 0.9970 | Train acc: 50.78% | Val loss: 1.0060 | Val acc: 46.02% | LR: 0.000008

[I 2025-09-23 19:37:42,910] Trial 172 finished with value: 0.4593353748321533 and parameters: {'lr': 1.1200929980471488e-05, 'hidden_size': 67, 'dropout': 0.22757251591947536, 'weight_decay': 5.778569479521031e-05}. Best is trial 163 with value: 0.5466681122779846.

Epoch: 000 | Train loss: 0.9990 | Train acc: 50.81% | Val loss: 1.0018 | Val acc: 48.45% | LR: 0.000012
Epoch: 001 | Train loss: 1.0012 | Train acc: 50.16% | Val loss: 1.0022 | Val acc: 48.43% | LR: 0.000012
Epoch: 002 | Train loss: 1.0052 | Train acc: 50.24% | Val loss: 1.0018 | Val acc: 48.37% | LR: 0.000012
Epoch: 003 | Train loss: 1.0007 | Train acc: 50.01% | Val loss: 1.0022 | Val acc: 48.39% | LR: 0.000012
Epoch: 004 | Train loss: 0.9988 | Train acc: 50.46% | Val loss: 1.0018 | Val acc: 48.45% | LR: 0.000012
Epoch: 005 | Train loss: 1.0185 | Train acc: 50.53% | Val loss: 1.0026 | Val acc: 48.39% | LR: 0.000012
Epoch: 006 | Train loss: 0.9970 | Train acc: 50.78% | Val loss: 1.0018 | Val acc: 48.22% | LR: 0.000012
Epoch: 007 | Train loss: 0.9992 | Train acc: 50.46% | Val loss: 1.0027 | Val acc: 48.32% | LR: 0.000012
Epoch: 008 | Train loss: 0.9978 | Train acc: 50.55% | Val loss: 1.0038 | Val acc: 48.41% | LR: 0.000012
Epoch: 009 | Train loss: 1.0044 | Train acc: 50.61% | Val loss: 1.0017 | Val acc: 48.34% | LR: 0.000012
Epoch: 010 | Train loss: 1.0068 | Train acc: 51.09% | Val loss: 1.0011 | Val acc: 48.30% | LR: 0.000012
Epoch: 011 | Train loss: 1.0002 | Train acc: 50.36% | Val loss: 1.0019 | Val acc: 48.20% | LR: 0.000012
Epoch: 012 | Train loss: 1.0170 | Train acc: 50.36% | Val loss: 1.0021 | Val acc: 48.18% | LR: 0.000012
Epoch: 013 | Train loss: 0.9975 | Train acc: 50.81% | Val loss: 1.0031 | Val acc: 48.16% | LR: 0.000012
Epoch: 014 | Train loss: 1.1501 | Train acc: 50.10% | Val loss: 1.0029 | Val acc: 48.16% | LR: 0.000012
Epoch: 015 | Train loss: 0.9985 | Train acc: 50.17% | Val loss: 1.0024 | Val acc: 48.16% | LR: 0.000012
Epoch: 016 | Train loss: 1.0263 | Train acc: 50.55% | Val loss: 1.0040 | Val acc: 48.20% | LR: 0.000012
Epoch: 017 | Train loss: 0.9977 | Train acc: 50.79% | Val loss: 1.0020 | Val acc: 48.24% | LR: 0.000012
Epoch: 018 | Train loss: 1.0010 | Train acc: 50.18% | Val loss: 1.0023 | Val acc: 48.06% | LR: 0.000012
Epoch: 019 | Train loss: 1.0031 | Train acc: 50.16% | Val loss: 1.0020 | Val acc: 48.26% | LR: 0.000011
Epoch: 020 | Train loss: 0.9978 | Train acc: 50.51% | Val loss: 1.0022 | Val acc: 48.12% | LR: 0.000011
Epoch: 021 | Train loss: 0.9966 | Train acc: 50.74% | Val loss: 1.0025 | Val acc: 48.20% | LR: 0.000011
Epoch: 022 | Train loss: 1.0036 | Train acc: 50.18% | Val loss: 1.0017 | Val acc: 48.27% | LR: 0.000011
Epoch: 023 | Train loss: 1.0013 | Train acc: 49.81% | Val loss: 1.0021 | Val acc: 48.21% | LR: 0.000011
Epoch: 024 | Train loss: 0.9997 | Train acc: 50.07% | Val loss: 1.0021 | Val acc: 48.35% | LR: 0.000011
Epoch: 025 | Train loss: 0.9990 | Train acc: 50.20% | Val loss: 1.0015 | Val acc: 48.29% | LR: 0.000011
Epoch: 026 | Train loss: 1.0022 | Train acc: 50.47% | Val loss: 1.0025 | Val acc: 48.31% | LR: 0.000011
Epoch: 027 | Train loss: 0.9978 | Train acc: 50.53% | Val loss: 1.0024 | Val acc: 48.26% | LR: 0.000011
Epoch: 028 | Train loss: 0.9965 | Train acc: 50.86% | Val loss: 1.0013 | Val acc: 48.31% | LR: 0.000011
Epoch: 029 | Train loss: 0.9991 | Train acc: 50.40% | Val loss: 1.0021 | Val acc: 48.35% | LR: 0.000011
Epoch: 030 | Train loss: 1.0014 | Train acc: 50.67% | Val loss: 1.0011 | Val acc: 48.45% | LR: 0.000011
Epoch: 031 | Train loss: 0.9979 | Train acc: 50.46% | Val loss: 1.0026 | Val acc: 48.33% | LR: 0.000011
Epoch: 032 | Train loss: 0.9949 | Train acc: 50.78% | Val loss: 1.0023 | Val acc: 48.39% | LR: 0.000011
Epoch: 033 | Train loss: 1.0077 | Train acc: 50.61% | Val loss: 1.0020 | Val acc: 48.33% | LR: 0.000011
Epoch: 034 | Train loss: 0.9986 | Train acc: 50.10% | Val loss: 1.0025 | Val acc: 48.25% | LR: 0.000011
Epoch: 035 | Train loss: 1.0005 | Train acc: 50.02% | Val loss: 1.0021 | Val acc: 48.29% | LR: 0.000010
Epoch: 036 | Train loss: 0.9971 | Train acc: 50.64% | Val loss: 1.0021 | Val acc: 48.35% | LR: 0.000010
Epoch: 037 | Train loss: 0.9969 | Train acc: 50.65% | Val loss: 1.0021 | Val acc: 48.29% | LR: 0.000010
Epoch: 038 | Train loss: 1.0017 | Train acc: 49.97% | Val loss: 1.0025 | Val acc: 48.25% | LR: 0.000010
Epoch: 039 | Train loss: 1.0015 | Train acc: 49.97% | Val loss: 1.0022 | Val acc: 48.31% | LR: 0.000010
Epoch: 040 | Train loss: 0.9973 | Train acc: 50.48% | Val loss: 1.0021 | Val acc: 48.27% | LR: 0.000010
Epoch: 041 | Train loss: 0.9963 | Train acc: 50.47% | Val loss: 1.0021 | Val acc: 48.37% | LR: 0.000010
Epoch: 042 | Train loss: 1.0004 | Train acc: 50.66% | Val loss: 1.0025 | Val acc: 48.33% | LR: 0.000010
Epoch: 043 | Train loss: 1.0093 | Train acc: 50.01% | Val loss: 1.0020 | Val acc: 48.38% | LR: 0.000010
Epoch: 044 | Train loss: 1.0125 | Train acc: 50.18% | Val loss: 1.0019 | Val acc: 48.33% | LR: 0.000010
Epoch: 045 | Train loss: 0.9980 | Train acc: 50.65% | Val loss: 1.0022 | Val acc: 48.35% | LR: 0.000010
Epoch: 046 | Train loss: 1.0008 | Train acc: 50.03% | Val loss: 1.0021 | Val acc: 48.35% | LR: 0.000010
Epoch: 047 | Train loss: 1.0014 | Train acc: 49.61% | Val loss: 1.0016 | Val acc: 48.25% | LR: 0.000009
Epoch: 048 | Train loss: 0.9999 | Train acc: 50.14% | Val loss: 1.0024 | Val acc: 48.11% | LR: 0.000009
Epoch: 049 | Train loss: 0.9980 | Train acc: 50.82% | Val loss: 1.0030 | Val acc: 47.97% | LR: 0.000009
Epoch: 050 | Train loss: 0.9980 | Train acc: 50.68% | Val loss: 1.0023 | Val acc: 48.19% | LR: 0.000009
Epoch: 051 | Train loss: 0.9995 | Train acc: 50.14% | Val loss: 1.0020 | Val acc: 48.29% | LR: 0.000009
Epoch: 052 | Train loss: 1.0002 | Train acc: 50.04% | Val loss: 1.0015 | Val acc: 48.35% | LR: 0.000009
Epoch: 053 | Train loss: 0.9984 | Train acc: 50.22% | Val loss: 1.0020 | Val acc: 48.25% | LR: 0.000009

[I 2025-09-23 19:38:27,482] Trial 173 finished with value: 0.4819465041160583 and parameters: {'lr': 1.1953605147904667e-05, 'hidden_size': 73, 'dropout': 0.2058350486531103, 'weight_decay': 8.44160121812958e-05}. Best is trial 163 with value: 0.5466681122779846.

Epoch: 000 | Train loss: 0.9979 | Train acc: 50.48% | Val loss: 0.9998 | Val acc: 49.68% | LR: 0.000010
Epoch: 001 | Train loss: 0.9971 | Train acc: 50.44% | Val loss: 0.9999 | Val acc: 49.62% | LR: 0.000010
Epoch: 002 | Train loss: 0.9946 | Train acc: 50.72% | Val loss: 0.9998 | Val acc: 49.47% | LR: 0.000010
Epoch: 003 | Train loss: 0.9963 | Train acc: 50.48% | Val loss: 0.9997 | Val acc: 49.72% | LR: 0.000010
Epoch: 004 | Train loss: 0.9939 | Train acc: 50.60% | Val loss: 0.9997 | Val acc: 49.76% | LR: 0.000010
Epoch: 005 | Train loss: 0.9958 | Train acc: 50.89% | Val loss: 0.9997 | Val acc: 49.70% | LR: 0.000010
Epoch: 006 | Train loss: 0.9947 | Train acc: 50.87% | Val loss: 0.9996 | Val acc: 49.59% | LR: 0.000010
Epoch: 007 | Train loss: 0.9962 | Train acc: 50.84% | Val loss: 0.9995 | Val acc: 49.83% | LR: 0.000010
Epoch: 008 | Train loss: 0.9961 | Train acc: 51.00% | Val loss: 0.9994 | Val acc: 50.24% | LR: 0.000010
Epoch: 009 | Train loss: 0.9942 | Train acc: 50.19% | Val loss: 0.9994 | Val acc: 49.96% | LR: 0.000010
Epoch: 010 | Train loss: 0.9952 | Train acc: 50.92% | Val loss: 0.9993 | Val acc: 50.02% | LR: 0.000010
Epoch: 011 | Train loss: 0.9964 | Train acc: 50.31% | Val loss: 0.9993 | Val acc: 50.06% | LR: 0.000010
Epoch: 012 | Train loss: 0.9945 | Train acc: 50.73% | Val loss: 0.9992 | Val acc: 50.25% | LR: 0.000010
Epoch: 013 | Train loss: 0.9964 | Train acc: 50.67% | Val loss: 0.9991 | Val acc: 50.25% | LR: 0.000010
Epoch: 014 | Train loss: 0.9939 | Train acc: 50.76% | Val loss: 0.9990 | Val acc: 50.17% | LR: 0.000010
Epoch: 015 | Train loss: 0.9950 | Train acc: 50.58% | Val loss: 0.9990 | Val acc: 50.05% | LR: 0.000010
Epoch: 016 | Train loss: 0.9936 | Train acc: 50.62% | Val loss: 0.9989 | Val acc: 50.30% | LR: 0.000010
Epoch: 017 | Train loss: 0.9950 | Train acc: 50.75% | Val loss: 0.9988 | Val acc: 50.39% | LR: 0.000010
Epoch: 018 | Train loss: 0.9925 | Train acc: 50.78% | Val loss: 0.9988 | Val acc: 50.40% | LR: 0.000010
Epoch: 019 | Train loss: 0.9922 | Train acc: 51.31% | Val loss: 0.9987 | Val acc: 50.39% | LR: 0.000010
Epoch: 020 | Train loss: 0.9929 | Train acc: 50.55% | Val loss: 0.9987 | Val acc: 50.57% | LR: 0.000010
Epoch: 021 | Train loss: 0.9924 | Train acc: 51.17% | Val loss: 0.9986 | Val acc: 50.37% | LR: 0.000010
Epoch: 022 | Train loss: 0.9934 | Train acc: 50.78% | Val loss: 0.9986 | Val acc: 50.43% | LR: 0.000010
Epoch: 023 | Train loss: 0.9933 | Train acc: 51.09% | Val loss: 0.9985 | Val acc: 50.61% | LR: 0.000009
Epoch: 024 | Train loss: 0.9931 | Train acc: 51.21% | Val loss: 0.9984 | Val acc: 50.64% | LR: 0.000009
Epoch: 025 | Train loss: 0.9931 | Train acc: 50.83% | Val loss: 0.9983 | Val acc: 50.70% | LR: 0.000009
Epoch: 026 | Train loss: 0.9895 | Train acc: 51.00% | Val loss: 0.9982 | Val acc: 50.96% | LR: 0.000009
Epoch: 027 | Train loss: 0.9949 | Train acc: 50.91% | Val loss: 0.9980 | Val acc: 51.06% | LR: 0.000009
Epoch: 028 | Train loss: 0.9937 | Train acc: 50.26% | Val loss: 0.9980 | Val acc: 51.08% | LR: 0.000009
Epoch: 029 | Train loss: 0.9929 | Train acc: 50.82% | Val loss: 0.9979 | Val acc: 51.08% | LR: 0.000009
Epoch: 030 | Train loss: 0.9939 | Train acc: 50.64% | Val loss: 0.9978 | Val acc: 51.10% | LR: 0.000009
Epoch: 031 | Train loss: 0.9936 | Train acc: 50.92% | Val loss: 0.9978 | Val acc: 51.22% | LR: 0.000009
Epoch: 032 | Train loss: 0.9935 | Train acc: 50.90% | Val loss: 0.9977 | Val acc: 51.22% | LR: 0.000009
Epoch: 033 | Train loss: 0.9959 | Train acc: 51.08% | Val loss: 0.9976 | Val acc: 51.13% | LR: 0.000009
Epoch: 034 | Train loss: 0.9919 | Train acc: 50.93% | Val loss: 0.9976 | Val acc: 51.13% | LR: 0.000009
Epoch: 035 | Train loss: 0.9913 | Train acc: 51.01% | Val loss: 0.9975 | Val acc: 51.17% | LR: 0.000009
Epoch: 036 | Train loss: 0.9909 | Train acc: 51.30% | Val loss: 0.9975 | Val acc: 51.17% | LR: 0.000009
Epoch: 037 | Train loss: 0.9904 | Train acc: 50.92% | Val loss: 0.9974 | Val acc: 51.15% | LR: 0.000009
Epoch: 038 | Train loss: 0.9953 | Train acc: 50.65% | Val loss: 0.9974 | Val acc: 51.10% | LR: 0.000009
Epoch: 039 | Train loss: 0.9937 | Train acc: 50.84% | Val loss: 0.9974 | Val acc: 51.14% | LR: 0.000009
Epoch: 040 | Train loss: 0.9928 | Train acc: 50.90% | Val loss: 0.9973 | Val acc: 51.10% | LR: 0.000008
Epoch: 041 | Train loss: 0.9966 | Train acc: 50.90% | Val loss: 0.9972 | Val acc: 51.21% | LR: 0.000008
Epoch: 042 | Train loss: 0.9911 | Train acc: 51.11% | Val loss: 0.9971 | Val acc: 51.31% | LR: 0.000008
Epoch: 043 | Train loss: 0.9910 | Train acc: 51.02% | Val loss: 0.9970 | Val acc: 51.35% | LR: 0.000008
Epoch: 044 | Train loss: 0.9931 | Train acc: 50.91% | Val loss: 0.9969 | Val acc: 51.43% | LR: 0.000008
Epoch: 045 | Train loss: 0.9942 | Train acc: 50.66% | Val loss: 0.9968 | Val acc: 51.53% | LR: 0.000008
Epoch: 046 | Train loss: 0.9930 | Train acc: 50.74% | Val loss: 0.9967 | Val acc: 51.53% | LR: 0.000008
Epoch: 047 | Train loss: 0.9960 | Train acc: 50.64% | Val loss: 0.9967 | Val acc: 51.49% | LR: 0.000008
Epoch: 048 | Train loss: 0.9925 | Train acc: 50.74% | Val loss: 0.9966 | Val acc: 51.51% | LR: 0.000008
Epoch: 049 | Train loss: 0.9913 | Train acc: 51.25% | Val loss: 0.9966 | Val acc: 51.58% | LR: 0.000008
Epoch: 050 | Train loss: 0.9902 | Train acc: 51.23% | Val loss: 0.9965 | Val acc: 51.54% | LR: 0.000008
Epoch: 051 | Train loss: 0.9902 | Train acc: 51.17% | Val loss: 0.9964 | Val acc: 51.54% | LR: 0.000008
Epoch: 052 | Train loss: 0.9913 | Train acc: 50.65% | Val loss: 0.9964 | Val acc: 51.57% | LR: 0.000008
Epoch: 053 | Train loss: 0.9957 | Train acc: 51.31% | Val loss: 0.9964 | Val acc: 51.51% | LR: 0.000007
Epoch: 054 | Train loss: 0.9945 | Train acc: 50.61% | Val loss: 0.9963 | Val acc: 51.55% | LR: 0.000007
Epoch: 055 | Train loss: 0.9885 | Train acc: 51.00% | Val loss: 0.9962 | Val acc: 51.59% | LR: 0.000007
Epoch: 056 | Train loss: 0.9907 | Train acc: 50.96% | Val loss: 0.9961 | Val acc: 51.64% | LR: 0.000007
Epoch: 057 | Train loss: 0.9937 | Train acc: 50.09% | Val loss: 0.9960 | Val acc: 51.64% | LR: 0.000007
Epoch: 058 | Train loss: 0.9905 | Train acc: 51.13% | Val loss: 0.9959 | Val acc: 51.67% | LR: 0.000007
Epoch: 059 | Train loss: 0.9938 | Train acc: 50.35% | Val loss: 0.9958 | Val acc: 51.84% | LR: 0.000007
Epoch: 060 | Train loss: 0.9936 | Train acc: 50.45% | Val loss: 0.9958 | Val acc: 51.80% | LR: 0.000007
Epoch: 061 | Train loss: 0.9926 | Train acc: 50.85% | Val loss: 0.9957 | Val acc: 51.91% | LR: 0.000007
Epoch: 062 | Train loss: 0.9917 | Train acc: 50.65% | Val loss: 0.9956 | Val acc: 51.93% | LR: 0.000007
Epoch: 063 | Train loss: 0.9914 | Train acc: 50.80% | Val loss: 0.9955 | Val acc: 51.89% | LR: 0.000007
Epoch: 064 | Train loss: 0.9949 | Train acc: 50.64% | Val loss: 0.9955 | Val acc: 51.89% | LR: 0.000006
Epoch: 065 | Train loss: 0.9914 | Train acc: 51.50% | Val loss: 0.9954 | Val acc: 51.91% | LR: 0.000006
Epoch: 066 | Train loss: 0.9938 | Train acc: 51.01% | Val loss: 0.9953 | Val acc: 51.91% | LR: 0.000006
Epoch: 067 | Train loss: 0.9898 | Train acc: 51.03% | Val loss: 0.9952 | Val acc: 51.91% | LR: 0.000006
Epoch: 068 | Train loss: 0.9924 | Train acc: 51.11% | Val loss: 0.9952 | Val acc: 51.87% | LR: 0.000006
Epoch: 069 | Train loss: 0.9913 | Train acc: 51.55% | Val loss: 0.9950 | Val acc: 51.77% | LR: 0.000006
Epoch: 070 | Train loss: 0.9910 | Train acc: 51.02% | Val loss: 0.9949 | Val acc: 51.86% | LR: 0.000006
Epoch: 071 | Train loss: 0.9924 | Train acc: 51.13% | Val loss: 0.9948 | Val acc: 51.86% | LR: 0.000006
Epoch: 072 | Train loss: 0.9918 | Train acc: 50.81% | Val loss: 0.9947 | Val acc: 51.87% | LR: 0.000006
Epoch: 073 | Train loss: 0.9906 | Train acc: 50.98% | Val loss: 0.9947 | Val acc: 51.82% | LR: 0.000006
Epoch: 074 | Train loss: 0.9928 | Train acc: 51.13% | Val loss: 0.9946 | Val acc: 51.82% | LR: 0.000006
Epoch: 075 | Train loss: 0.9914 | Train acc: 51.24% | Val loss: 0.9946 | Val acc: 51.82% | LR: 0.000005
Epoch: 076 | Train loss: 0.9914 | Train acc: 51.13% | Val loss: 0.9945 | Val acc: 51.82% | LR: 0.000005
Epoch: 077 | Train loss: 0.9911 | Train acc: 50.68% | Val loss: 0.9944 | Val acc: 51.76% | LR: 0.000005
Epoch: 078 | Train loss: 0.9898 | Train acc: 51.47% | Val loss: 0.9943 | Val acc: 51.80% | LR: 0.000005
Epoch: 079 | Train loss: 0.9889 | Train acc: 51.50% | Val loss: 0.9943 | Val acc: 51.80% | LR: 0.000005
Epoch: 080 | Train loss: 0.9918 | Train acc: 50.62% | Val loss: 0.9943 | Val acc: 51.78% | LR: 0.000005
Epoch: 081 | Train loss: 0.9917 | Train acc: 50.86% | Val loss: 0.9942 | Val acc: 51.72% | LR: 0.000005
Epoch: 082 | Train loss: 0.9917 | Train acc: 50.60% | Val loss: 0.9942 | Val acc: 51.76% | LR: 0.000005
Epoch: 083 | Train loss: 0.9902 | Train acc: 50.98% | Val loss: 0.9941 | Val acc: 51.76% | LR: 0.000005
Epoch: 084 | Train loss: 0.9892 | Train acc: 50.91% | Val loss: 0.9941 | Val acc: 51.76% | LR: 0.000005
Epoch: 085 | Train loss: 0.9923 | Train acc: 51.22% | Val loss: 0.9940 | Val acc: 51.84% | LR: 0.000004
Epoch: 086 | Train loss: 0.9893 | Train acc: 50.95% | Val loss: 0.9940 | Val acc: 51.84% | LR: 0.000004
Epoch: 087 | Train loss: 0.9920 | Train acc: 51.05% | Val loss: 0.9939 | Val acc: 51.84% | LR: 0.000004
Epoch: 088 | Train loss: 0.9965 | Train acc: 50.94% | Val loss: 0.9939 | Val acc: 51.82% | LR: 0.000004
Epoch: 089 | Train loss: 0.9962 | Train acc: 51.03% | Val loss: 0.9937 | Val acc: 51.82% | LR: 0.000004
Epoch: 090 | Train loss: 0.9955 | Train acc: 50.66% | Val loss: 0.9936 | Val acc: 51.78% | LR: 0.000004
Epoch: 091 | Train loss: 0.9946 | Train acc: 51.75% | Val loss: 0.9936 | Val acc: 51.72% | LR: 0.000004
Epoch: 092 | Train loss: 0.9966 | Train acc: 51.05% | Val loss: 0.9935 | Val acc: 51.76% | LR: 0.000004
Epoch: 093 | Train loss: 0.9969 | Train acc: 50.80% | Val loss: 0.9935 | Val acc: 51.74% | LR: 0.000004
Epoch: 094 | Train loss: 0.9969 | Train acc: 50.82% | Val loss: 0.9935 | Val acc: 51.76% | LR: 0.000004
Epoch: 095 | Train loss: 0.9949 | Train acc: 51.44% | Val loss: 0.9935 | Val acc: 51.78% | LR: 0.000004
Epoch: 096 | Train loss: 0.9960 | Train acc: 50.53% | Val loss: 0.9934 | Val acc: 51.78% | LR: 0.000004
Epoch: 097 | Train loss: 0.9963 | Train acc: 50.98% | Val loss: 0.9934 | Val acc: 51.76% | LR: 0.000003
Epoch: 098 | Train loss: 0.9936 | Train acc: 50.57% | Val loss: 0.9933 | Val acc: 51.80% | LR: 0.000003
Epoch: 099 | Train loss: 0.9913 | Train acc: 50.93% | Val loss: 0.9933 | Val acc: 51.78% | LR: 0.000003
Epoch: 100 | Train loss: 0.9956 | Train acc: 51.11% | Val loss: 0.9933 | Val acc: 51.78% | LR: 0.000003
Epoch: 101 | Train loss: 0.9920 | Train acc: 51.28% | Val loss: 0.9933 | Val acc: 51.80% | LR: 0.000003
Epoch: 102 | Train loss: 0.9906 | Train acc: 51.56% | Val loss: 0.9933 | Val acc: 51.78% | LR: 0.000003
Epoch: 103 | Train loss: 0.9938 | Train acc: 51.17% | Val loss: 0.9933 | Val acc: 51.74% | LR: 0.000003
Epoch: 104 | Train loss: 0.9923 | Train acc: 51.63% | Val loss: 0.9932 | Val acc: 51.74% | LR: 0.000003
Epoch: 105 | Train loss: 0.9924 | Train acc: 50.83% | Val loss: 0.9932 | Val acc: 51.74% | LR: 0.000003
Epoch: 106 | Train loss: 0.9950 | Train acc: 50.82% | Val loss: 0.9932 | Val acc: 51.80% | LR: 0.000003
Epoch: 107 | Train loss: 0.9937 | Train acc: 50.82% | Val loss: 0.9932 | Val acc: 51.78% | LR: 0.000003
Epoch: 108 | Train loss: 0.9918 | Train acc: 51.00% | Val loss: 0.9932 | Val acc: 51.80% | LR: 0.000003
Epoch: 109 | Train loss: 0.9921 | Train acc: 50.81% | Val loss: 0.9932 | Val acc: 51.80% | LR: 0.000002
Epoch: 110 | Train loss: 0.9932 | Train acc: 50.39% | Val loss: 0.9932 | Val acc: 51.80% | LR: 0.000002
Epoch: 111 | Train loss: 0.9914 | Train acc: 51.01% | Val loss: 0.9932 | Val acc: 51.80% | LR: 0.000002

[I 2025-09-23 19:40:04,420] Trial 174 finished with value: 0.5179671287536621 and parameters: {'lr': 1.0017644672816624e-05, 'hidden_size': 77, 'dropout': 0.18517562999072962, 'weight_decay': 4.991535867594604e-05}. Best is trial 163 with value: 0.5466681122779846.

Epoch: 000 | Train loss: 1.0005 | Train acc: 50.07% | Val loss: 0.9917 | Val acc: 54.07% | LR: 0.000013
Epoch: 001 | Train loss: 1.0009 | Train acc: 49.72% | Val loss: 0.9917 | Val acc: 54.09% | LR: 0.000013
Epoch: 002 | Train loss: 1.0006 | Train acc: 49.54% | Val loss: 0.9918 | Val acc: 54.13% | LR: 0.000013
Epoch: 003 | Train loss: 1.0007 | Train acc: 49.53% | Val loss: 0.9920 | Val acc: 54.13% | LR: 0.000013
Epoch: 004 | Train loss: 1.0013 | Train acc: 49.36% | Val loss: 0.9920 | Val acc: 54.13% | LR: 0.000013
Epoch: 005 | Train loss: 0.9986 | Train acc: 49.99% | Val loss: 0.9920 | Val acc: 54.15% | LR: 0.000013
Epoch: 006 | Train loss: 1.0006 | Train acc: 49.52% | Val loss: 0.9920 | Val acc: 54.17% | LR: 0.000013
Epoch: 007 | Train loss: 1.0012 | Train acc: 49.67% | Val loss: 0.9921 | Val acc: 54.26% | LR: 0.000013
Epoch: 008 | Train loss: 1.0008 | Train acc: 49.57% | Val loss: 0.9922 | Val acc: 54.30% | LR: 0.000013
Epoch: 009 | Train loss: 0.9990 | Train acc: 50.44% | Val loss: 0.9922 | Val acc: 54.30% | LR: 0.000013
Epoch: 010 | Train loss: 0.9985 | Train acc: 50.80% | Val loss: 0.9923 | Val acc: 54.28% | LR: 0.000013
Epoch: 011 | Train loss: 0.9985 | Train acc: 50.72% | Val loss: 0.9922 | Val acc: 54.28% | LR: 0.000013
Epoch: 012 | Train loss: 0.9982 | Train acc: 50.63% | Val loss: 0.9922 | Val acc: 54.28% | LR: 0.000013
Epoch: 013 | Train loss: 0.9994 | Train acc: 50.36% | Val loss: 0.9920 | Val acc: 54.28% | LR: 0.000013
Epoch: 014 | Train loss: 0.9983 | Train acc: 50.50% | Val loss: 0.9921 | Val acc: 54.28% | LR: 0.000013
Epoch: 015 | Train loss: 0.9997 | Train acc: 50.06% | Val loss: 0.9921 | Val acc: 54.28% | LR: 0.000013
Epoch: 016 | Train loss: 0.9983 | Train acc: 50.65% | Val loss: 0.9922 | Val acc: 54.32% | LR: 0.000013
Epoch: 017 | Train loss: 0.9989 | Train acc: 50.49% | Val loss: 0.9921 | Val acc: 54.34% | LR: 0.000013
Epoch: 018 | Train loss: 0.9991 | Train acc: 50.25% | Val loss: 0.9920 | Val acc: 54.40% | LR: 0.000013
Epoch: 019 | Train loss: 0.9989 | Train acc: 50.33% | Val loss: 0.9921 | Val acc: 54.36% | LR: 0.000013
Epoch: 020 | Train loss: 0.9965 | Train acc: 51.16% | Val loss: 0.9921 | Val acc: 54.38% | LR: 0.000013
Epoch: 021 | Train loss: 0.9978 | Train acc: 50.63% | Val loss: 0.9920 | Val acc: 54.38% | LR: 0.000013
Epoch: 022 | Train loss: 0.9971 | Train acc: 50.77% | Val loss: 0.9919 | Val acc: 54.40% | LR: 0.000012
Epoch: 023 | Train loss: 0.9983 | Train acc: 50.35% | Val loss: 0.9919 | Val acc: 54.40% | LR: 0.000012
Epoch: 024 | Train loss: 0.9983 | Train acc: 50.32% | Val loss: 0.9917 | Val acc: 54.39% | LR: 0.000012
Epoch: 025 | Train loss: 0.9996 | Train acc: 50.03% | Val loss: 0.9916 | Val acc: 54.30% | LR: 0.000012
Epoch: 026 | Train loss: 0.9984 | Train acc: 50.24% | Val loss: 0.9916 | Val acc: 54.24% | LR: 0.000012
Epoch: 027 | Train loss: 0.9972 | Train acc: 50.76% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000012
Epoch: 028 | Train loss: 0.9975 | Train acc: 50.79% | Val loss: 0.9918 | Val acc: 54.20% | LR: 0.000012
Epoch: 029 | Train loss: 0.9975 | Train acc: 50.80% | Val loss: 0.9918 | Val acc: 54.30% | LR: 0.000012
Epoch: 030 | Train loss: 0.9981 | Train acc: 50.46% | Val loss: 0.9918 | Val acc: 54.40% | LR: 0.000012
Epoch: 031 | Train loss: 0.9981 | Train acc: 50.41% | Val loss: 0.9918 | Val acc: 54.38% | LR: 0.000012
Epoch: 032 | Train loss: 0.9965 | Train acc: 51.11% | Val loss: 0.9917 | Val acc: 54.43% | LR: 0.000012
Epoch: 033 | Train loss: 0.9989 | Train acc: 49.96% | Val loss: 0.9917 | Val acc: 54.43% | LR: 0.000012
Epoch: 034 | Train loss: 0.9967 | Train acc: 50.92% | Val loss: 0.9917 | Val acc: 54.33% | LR: 0.000012
Epoch: 035 | Train loss: 0.9984 | Train acc: 50.39% | Val loss: 0.9917 | Val acc: 54.39% | LR: 0.000011
Epoch: 036 | Train loss: 0.9979 | Train acc: 50.48% | Val loss: 0.9917 | Val acc: 54.41% | LR: 0.000011
Epoch: 037 | Train loss: 0.9981 | Train acc: 50.42% | Val loss: 0.9918 | Val acc: 54.41% | LR: 0.000011
Epoch: 038 | Train loss: 0.9984 | Train acc: 50.35% | Val loss: 0.9918 | Val acc: 54.49% | LR: 0.000011
Epoch: 039 | Train loss: 0.9968 | Train acc: 50.90% | Val loss: 0.9917 | Val acc: 54.45% | LR: 0.000011
Epoch: 040 | Train loss: 0.9973 | Train acc: 50.83% | Val loss: 0.9917 | Val acc: 54.43% | LR: 0.000011
Epoch: 041 | Train loss: 0.9975 | Train acc: 50.75% | Val loss: 0.9917 | Val acc: 54.50% | LR: 0.000011
Epoch: 042 | Train loss: 0.9983 | Train acc: 50.39% | Val loss: 0.9917 | Val acc: 54.42% | LR: 0.000011
Epoch: 043 | Train loss: 0.9980 | Train acc: 50.39% | Val loss: 0.9917 | Val acc: 54.39% | LR: 0.000011
Epoch: 044 | Train loss: 0.9983 | Train acc: 50.29% | Val loss: 0.9917 | Val acc: 54.40% | LR: 0.000011
Epoch: 045 | Train loss: 0.9972 | Train acc: 50.65% | Val loss: 0.9916 | Val acc: 54.36% | LR: 0.000011
Epoch: 046 | Train loss: 0.9964 | Train acc: 51.02% | Val loss: 0.9916 | Val acc: 54.36% | LR: 0.000010
Epoch: 047 | Train loss: 0.9978 | Train acc: 50.27% | Val loss: 0.9916 | Val acc: 54.42% | LR: 0.000010
Epoch: 048 | Train loss: 0.9976 | Train acc: 50.74% | Val loss: 0.9916 | Val acc: 54.44% | LR: 0.000010
Epoch: 049 | Train loss: 0.9977 | Train acc: 50.62% | Val loss: 0.9916 | Val acc: 54.46% | LR: 0.000010
Epoch: 050 | Train loss: 0.9984 | Train acc: 50.45% | Val loss: 0.9916 | Val acc: 54.46% | LR: 0.000010
Epoch: 051 | Train loss: 0.9968 | Train acc: 50.61% | Val loss: 0.9916 | Val acc: 54.52% | LR: 0.000010
Epoch: 052 | Train loss: 0.9987 | Train acc: 50.30% | Val loss: 0.9917 | Val acc: 54.48% | LR: 0.000010
Epoch: 053 | Train loss: 0.9977 | Train acc: 50.43% | Val loss: 0.9916 | Val acc: 54.50% | LR: 0.000010
Epoch: 054 | Train loss: 0.9966 | Train acc: 50.85% | Val loss: 0.9916 | Val acc: 54.48% | LR: 0.000010
Epoch: 055 | Train loss: 0.9966 | Train acc: 50.83% | Val loss: 0.9916 | Val acc: 54.44% | LR: 0.000009
Epoch: 056 | Train loss: 0.9965 | Train acc: 51.00% | Val loss: 0.9916 | Val acc: 54.54% | LR: 0.000009
Epoch: 057 | Train loss: 0.9972 | Train acc: 50.51% | Val loss: 0.9916 | Val acc: 54.62% | LR: 0.000009
Epoch: 058 | Train loss: 0.9978 | Train acc: 50.63% | Val loss: 0.9916 | Val acc: 54.64% | LR: 0.000009
Epoch: 059 | Train loss: 0.9966 | Train acc: 51.04% | Val loss: 0.9916 | Val acc: 54.52% | LR: 0.000009
Epoch: 060 | Train loss: 0.9964 | Train acc: 50.81% | Val loss: 0.9916 | Val acc: 54.50% | LR: 0.000009
Epoch: 061 | Train loss: 0.9961 | Train acc: 50.49% | Val loss: 0.9916 | Val acc: 54.55% | LR: 0.000009
Epoch: 062 | Train loss: 0.9960 | Train acc: 50.63% | Val loss: 0.9916 | Val acc: 54.52% | LR: 0.000009
Epoch: 063 | Train loss: 0.9979 | Train acc: 50.52% | Val loss: 0.9916 | Val acc: 54.57% | LR: 0.000008
Epoch: 064 | Train loss: 0.9970 | Train acc: 50.94% | Val loss: 0.9916 | Val acc: 54.63% | LR: 0.000008
Epoch: 065 | Train loss: 0.9962 | Train acc: 50.92% | Val loss: 0.9916 | Val acc: 54.63% | LR: 0.000008
Epoch: 066 | Train loss: 0.9972 | Train acc: 50.38% | Val loss: 0.9916 | Val acc: 54.59% | LR: 0.000008
Epoch: 067 | Train loss: 0.9962 | Train acc: 50.58% | Val loss: 0.9916 | Val acc: 54.53% | LR: 0.000008
Epoch: 068 | Train loss: 0.9970 | Train acc: 50.86% | Val loss: 0.9915 | Val acc: 54.53% | LR: 0.000008
Epoch: 069 | Train loss: 0.9968 | Train acc: 50.96% | Val loss: 0.9916 | Val acc: 54.54% | LR: 0.000008
Epoch: 070 | Train loss: 0.9950 | Train acc: 50.90% | Val loss: 0.9916 | Val acc: 54.54% | LR: 0.000008
Epoch: 071 | Train loss: 0.9971 | Train acc: 50.67% | Val loss: 0.9915 | Val acc: 54.62% | LR: 0.000007
Epoch: 072 | Train loss: 0.9952 | Train acc: 51.12% | Val loss: 0.9915 | Val acc: 54.57% | LR: 0.000007
Epoch: 073 | Train loss: 0.9965 | Train acc: 51.33% | Val loss: 0.9915 | Val acc: 54.54% | LR: 0.000007
Epoch: 074 | Train loss: 0.9945 | Train acc: 50.95% | Val loss: 0.9915 | Val acc: 54.54% | LR: 0.000007
Epoch: 075 | Train loss: 0.9954 | Train acc: 50.69% | Val loss: 0.9915 | Val acc: 54.44% | LR: 0.000007
Epoch: 076 | Train loss: 0.9967 | Train acc: 50.88% | Val loss: 0.9915 | Val acc: 54.48% | LR: 0.000007
Epoch: 077 | Train loss: 0.9963 | Train acc: 50.92% | Val loss: 0.9915 | Val acc: 54.44% | LR: 0.000007
Epoch: 078 | Train loss: 0.9951 | Train acc: 51.12% | Val loss: 0.9915 | Val acc: 54.40% | LR: 0.000007
Epoch: 079 | Train loss: 0.9959 | Train acc: 51.02% | Val loss: 0.9915 | Val acc: 54.46% | LR: 0.000006
Epoch: 080 | Train loss: 0.9954 | Train acc: 50.80% | Val loss: 0.9915 | Val acc: 54.46% | LR: 0.000006
Epoch: 081 | Train loss: 0.9954 | Train acc: 51.03% | Val loss: 0.9914 | Val acc: 54.48% | LR: 0.000006
Epoch: 082 | Train loss: 0.9960 | Train acc: 50.43% | Val loss: 0.9915 | Val acc: 54.50% | LR: 0.000006
Epoch: 083 | Train loss: 0.9960 | Train acc: 50.93% | Val loss: 0.9914 | Val acc: 54.54% | LR: 0.000006
Epoch: 084 | Train loss: 0.9953 | Train acc: 51.05% | Val loss: 0.9914 | Val acc: 54.71% | LR: 0.000006
Epoch: 085 | Train loss: 0.9976 | Train acc: 50.71% | Val loss: 0.9914 | Val acc: 54.72% | LR: 0.000006
Epoch: 086 | Train loss: 0.9956 | Train acc: 50.97% | Val loss: 0.9914 | Val acc: 54.66% | LR: 0.000006
Epoch: 087 | Train loss: 0.9945 | Train acc: 51.33% | Val loss: 0.9915 | Val acc: 54.68% | LR: 0.000005
Epoch: 088 | Train loss: 0.9953 | Train acc: 50.79% | Val loss: 0.9915 | Val acc: 54.58% | LR: 0.000005
Epoch: 089 | Train loss: 0.9959 | Train acc: 50.79% | Val loss: 0.9915 | Val acc: 54.60% | LR: 0.000005
Epoch: 090 | Train loss: 0.9959 | Train acc: 50.96% | Val loss: 0.9914 | Val acc: 54.60% | LR: 0.000005
Epoch: 091 | Train loss: 0.9957 | Train acc: 50.70% | Val loss: 0.9914 | Val acc: 54.51% | LR: 0.000005
Epoch: 092 | Train loss: 0.9937 | Train acc: 51.58% | Val loss: 0.9914 | Val acc: 54.38% | LR: 0.000005
Epoch: 093 | Train loss: 0.9951 | Train acc: 50.78% | Val loss: 0.9914 | Val acc: 54.34% | LR: 0.000005
Epoch: 094 | Train loss: 0.9949 | Train acc: 50.61% | Val loss: 0.9914 | Val acc: 54.36% | LR: 0.000005
Epoch: 095 | Train loss: 0.9969 | Train acc: 50.62% | Val loss: 0.9914 | Val acc: 54.34% | LR: 0.000004
Epoch: 096 | Train loss: 0.9939 | Train acc: 51.31% | Val loss: 0.9914 | Val acc: 54.45% | LR: 0.000004
Epoch: 097 | Train loss: 0.9951 | Train acc: 51.15% | Val loss: 0.9914 | Val acc: 54.49% | LR: 0.000004
Epoch: 098 | Train loss: 0.9971 | Train acc: 50.44% | Val loss: 0.9914 | Val acc: 54.43% | LR: 0.000004
Epoch: 099 | Train loss: 0.9959 | Train acc: 50.62% | Val loss: 0.9913 | Val acc: 54.41% | LR: 0.000004
Epoch: 100 | Train loss: 0.9924 | Train acc: 51.76% | Val loss: 0.9914 | Val acc: 54.36% | LR: 0.000004
Epoch: 101 | Train loss: 0.9949 | Train acc: 50.87% | Val loss: 0.9913 | Val acc: 54.39% | LR: 0.000004
Epoch: 102 | Train loss: 0.9943 | Train acc: 50.97% | Val loss: 0.9914 | Val acc: 54.43% | LR: 0.000004
Epoch: 103 | Train loss: 0.9951 | Train acc: 50.89% | Val loss: 0.9913 | Val acc: 54.50% | LR: 0.000004
Epoch: 104 | Train loss: 0.9954 | Train acc: 51.06% | Val loss: 0.9913 | Val acc: 54.48% | LR: 0.000004
Epoch: 105 | Train loss: 0.9953 | Train acc: 50.52% | Val loss: 0.9913 | Val acc: 54.50% | LR: 0.000003
Epoch: 106 | Train loss: 0.9954 | Train acc: 50.70% | Val loss: 0.9913 | Val acc: 54.41% | LR: 0.000003
Epoch: 107 | Train loss: 0.9951 | Train acc: 50.88% | Val loss: 0.9913 | Val acc: 54.39% | LR: 0.000003
Epoch: 108 | Train loss: 0.9961 | Train acc: 50.87% | Val loss: 0.9913 | Val acc: 54.43% | LR: 0.000003
Epoch: 109 | Train loss: 0.9998 | Train acc: 50.44% | Val loss: 0.9913 | Val acc: 54.47% | LR: 0.000003
Epoch: 110 | Train loss: 0.9987 | Train acc: 50.92% | Val loss: 0.9913 | Val acc: 54.47% | LR: 0.000003
Epoch: 111 | Train loss: 0.9940 | Train acc: 51.19% | Val loss: 0.9913 | Val acc: 54.41% | LR: 0.000003
Epoch: 112 | Train loss: 0.9957 | Train acc: 51.03% | Val loss: 0.9913 | Val acc: 54.41% | LR: 0.000003
Epoch: 113 | Train loss: 0.9943 | Train acc: 51.17% | Val loss: 0.9913 | Val acc: 54.39% | LR: 0.000003
Epoch: 114 | Train loss: 0.9959 | Train acc: 51.36% | Val loss: 0.9913 | Val acc: 54.39% | LR: 0.000003
Epoch: 115 | Train loss: 0.9980 | Train acc: 50.98% | Val loss: 0.9913 | Val acc: 54.39% | LR: 0.000002
Epoch: 116 | Train loss: 0.9941 | Train acc: 50.83% | Val loss: 0.9913 | Val acc: 54.39% | LR: 0.000002
Epoch: 117 | Train loss: 0.9974 | Train acc: 50.79% | Val loss: 0.9913 | Val acc: 54.41% | LR: 0.000002
Epoch: 118 | Train loss: 0.9965 | Train acc: 50.92% | Val loss: 0.9913 | Val acc: 54.41% | LR: 0.000002
Epoch: 119 | Train loss: 1.0083 | Train acc: 50.70% | Val loss: 0.9913 | Val acc: 54.39% | LR: 0.000002
Epoch: 120 | Train loss: 0.9985 | Train acc: 50.56% | Val loss: 0.9913 | Val acc: 54.39% | LR: 0.000002
Epoch: 121 | Train loss: 0.9955 | Train acc: 50.76% | Val loss: 0.9913 | Val acc: 54.39% | LR: 0.000002
Epoch: 122 | Train loss: 0.9959 | Train acc: 51.11% | Val loss: 0.9913 | Val acc: 54.39% | LR: 0.000002
Epoch: 123 | Train loss: 0.9946 | Train acc: 50.77% | Val loss: 0.9912 | Val acc: 54.39% | LR: 0.000002
Epoch: 124 | Train loss: 0.9954 | Train acc: 50.80% | Val loss: 0.9912 | Val acc: 54.39% | LR: 0.000002
Epoch: 125 | Train loss: 0.9963 | Train acc: 50.73% | Val loss: 0.9912 | Val acc: 54.39% | LR: 0.000002
Epoch: 126 | Train loss: 1.0320 | Train acc: 51.32% | Val loss: 0.9912 | Val acc: 54.39% | LR: 0.000002
Epoch: 127 | Train loss: 1.3895 | Train acc: 50.92% | Val loss: 0.9912 | Val acc: 54.39% | LR: 0.000002
Epoch: 128 | Train loss: 0.9996 | Train acc: 50.41% | Val loss: 0.9912 | Val acc: 54.39% | LR: 0.000002
Epoch: 129 | Train loss: 0.9957 | Train acc: 50.96% | Val loss: 0.9912 | Val acc: 54.39% | LR: 0.000002
Epoch: 130 | Train loss: 0.9991 | Train acc: 50.17% | Val loss: 0.9912 | Val acc: 54.35% | LR: 0.000001
Epoch: 131 | Train loss: 0.9956 | Train acc: 50.90% | Val loss: 0.9912 | Val acc: 54.35% | LR: 0.000001
Epoch: 132 | Train loss: 0.9956 | Train acc: 50.96% | Val loss: 0.9912 | Val acc: 54.35% | LR: 0.000001
Epoch: 133 | Train loss: 0.9972 | Train acc: 50.85% | Val loss: 0.9912 | Val acc: 54.35% | LR: 0.000001
Epoch: 134 | Train loss: 0.9965 | Train acc: 51.11% | Val loss: 0.9912 | Val acc: 54.35% | LR: 0.000001

[I 2025-09-23 19:41:46,350] Trial 175 finished with value: 0.5435079455375671 and parameters: {'lr': 1.313977755296824e-05, 'hidden_size': 64, 'dropout': 0.21902071647580137, 'weight_decay': 0.00019085162305942918}. Best is trial 163 with value: 0.5466681122779846.

Epoch: 000 | Train loss: 0.9971 | Train acc: 50.89% | Val loss: 1.0112 | Val acc: 53.29% | LR: 0.000014
Epoch: 001 | Train loss: 1.0001 | Train acc: 50.17% | Val loss: 0.9973 | Val acc: 53.39% | LR: 0.000014
Epoch: 002 | Train loss: 0.9979 | Train acc: 50.66% | Val loss: 0.9975 | Val acc: 53.39% | LR: 0.000014
Epoch: 003 | Train loss: 0.9980 | Train acc: 50.27% | Val loss: 0.9974 | Val acc: 53.39% | LR: 0.000014
Epoch: 004 | Train loss: 0.9983 | Train acc: 50.48% | Val loss: 0.9974 | Val acc: 53.40% | LR: 0.000014
Epoch: 005 | Train loss: 0.9993 | Train acc: 50.32% | Val loss: 0.9974 | Val acc: 53.42% | LR: 0.000014
Epoch: 006 | Train loss: 0.9977 | Train acc: 50.81% | Val loss: 0.9974 | Val acc: 53.34% | LR: 0.000014
Epoch: 007 | Train loss: 0.9984 | Train acc: 50.73% | Val loss: 0.9974 | Val acc: 53.38% | LR: 0.000014
Epoch: 008 | Train loss: 0.9973 | Train acc: 50.72% | Val loss: 0.9974 | Val acc: 53.32% | LR: 0.000014
Epoch: 009 | Train loss: 0.9972 | Train acc: 50.72% | Val loss: 0.9974 | Val acc: 53.39% | LR: 0.000014
Epoch: 010 | Train loss: 0.9969 | Train acc: 50.52% | Val loss: 0.9974 | Val acc: 53.31% | LR: 0.000014
Epoch: 011 | Train loss: 0.9958 | Train acc: 50.82% | Val loss: 0.9974 | Val acc: 53.14% | LR: 0.000014
Epoch: 012 | Train loss: 0.9925 | Train acc: 51.44% | Val loss: 0.9974 | Val acc: 53.16% | LR: 0.000014
Epoch: 013 | Train loss: 1.0012 | Train acc: 50.25% | Val loss: 0.9974 | Val acc: 53.10% | LR: 0.000014
Epoch: 014 | Train loss: 0.9986 | Train acc: 50.52% | Val loss: 0.9974 | Val acc: 52.86% | LR: 0.000014
Epoch: 015 | Train loss: 0.9974 | Train acc: 50.57% | Val loss: 0.9974 | Val acc: 52.84% | LR: 0.000013
Epoch: 016 | Train loss: 0.9980 | Train acc: 50.48% | Val loss: 0.9975 | Val acc: 52.66% | LR: 0.000013
Epoch: 017 | Train loss: 1.0001 | Train acc: 50.21% | Val loss: 0.9975 | Val acc: 52.65% | LR: 0.000013
Epoch: 018 | Train loss: 0.9977 | Train acc: 50.48% | Val loss: 0.9974 | Val acc: 52.69% | LR: 0.000013
Epoch: 019 | Train loss: 0.9979 | Train acc: 50.47% | Val loss: 0.9974 | Val acc: 52.63% | LR: 0.000013
Epoch: 020 | Train loss: 0.9955 | Train acc: 50.73% | Val loss: 0.9974 | Val acc: 52.48% | LR: 0.000013
Epoch: 021 | Train loss: 0.9983 | Train acc: 50.51% | Val loss: 0.9975 | Val acc: 52.66% | LR: 0.000013
Epoch: 022 | Train loss: 0.9984 | Train acc: 50.34% | Val loss: 0.9974 | Val acc: 52.70% | LR: 0.000013
Epoch: 023 | Train loss: 0.9961 | Train acc: 50.71% | Val loss: 0.9974 | Val acc: 52.64% | LR: 0.000013
Epoch: 024 | Train loss: 1.0009 | Train acc: 50.28% | Val loss: 0.9974 | Val acc: 52.72% | LR: 0.000013
Epoch: 025 | Train loss: 0.9978 | Train acc: 50.56% | Val loss: 0.9974 | Val acc: 52.68% | LR: 0.000013
Epoch: 026 | Train loss: 0.9961 | Train acc: 50.56% | Val loss: 0.9975 | Val acc: 52.26% | LR: 0.000013
Epoch: 027 | Train loss: 0.9959 | Train acc: 50.94% | Val loss: 0.9975 | Val acc: 52.34% | LR: 0.000013
Epoch: 028 | Train loss: 0.9962 | Train acc: 50.59% | Val loss: 0.9975 | Val acc: 52.24% | LR: 0.000013
Epoch: 029 | Train loss: 0.9887 | Train acc: 51.56% | Val loss: 0.9974 | Val acc: 52.33% | LR: 0.000013
Epoch: 030 | Train loss: 0.9920 | Train acc: 51.20% | Val loss: 0.9975 | Val acc: 51.99% | LR: 0.000013
Epoch: 031 | Train loss: 0.9975 | Train acc: 50.68% | Val loss: 0.9975 | Val acc: 51.91% | LR: 0.000012
Epoch: 032 | Train loss: 0.9928 | Train acc: 51.15% | Val loss: 0.9975 | Val acc: 51.85% | LR: 0.000012
Epoch: 033 | Train loss: 0.9933 | Train acc: 51.09% | Val loss: 0.9976 | Val acc: 51.79% | LR: 0.000012
Epoch: 034 | Train loss: 0.9983 | Train acc: 50.74% | Val loss: 0.9976 | Val acc: 51.94% | LR: 0.000012
Epoch: 035 | Train loss: 0.9958 | Train acc: 50.82% | Val loss: 0.9976 | Val acc: 51.89% | LR: 0.000012
Epoch: 036 | Train loss: 0.9939 | Train acc: 50.92% | Val loss: 0.9976 | Val acc: 51.95% | LR: 0.000012
Epoch: 037 | Train loss: 0.9917 | Train acc: 51.21% | Val loss: 0.9976 | Val acc: 51.93% | LR: 0.000012
Epoch: 038 | Train loss: 0.9961 | Train acc: 51.03% | Val loss: 0.9976 | Val acc: 51.68% | LR: 0.000012
Epoch: 039 | Train loss: 0.9973 | Train acc: 50.69% | Val loss: 0.9975 | Val acc: 51.58% | LR: 0.000012
Epoch: 040 | Train loss: 0.9997 | Train acc: 50.60% | Val loss: 0.9975 | Val acc: 51.54% | LR: 0.000012
Epoch: 041 | Train loss: 0.9925 | Train acc: 51.17% | Val loss: 0.9974 | Val acc: 51.58% | LR: 0.000012
Epoch: 042 | Train loss: 0.9981 | Train acc: 50.53% | Val loss: 0.9974 | Val acc: 51.62% | LR: 0.000011
Epoch: 043 | Train loss: 0.9942 | Train acc: 50.79% | Val loss: 0.9974 | Val acc: 51.70% | LR: 0.000011
Epoch: 044 | Train loss: 0.9926 | Train acc: 51.18% | Val loss: 0.9974 | Val acc: 51.60% | LR: 0.000011
Epoch: 045 | Train loss: 0.9985 | Train acc: 50.53% | Val loss: 0.9974 | Val acc: 51.70% | LR: 0.000011
Epoch: 046 | Train loss: 0.9928 | Train acc: 50.97% | Val loss: 0.9974 | Val acc: 51.76% | LR: 0.000011
Epoch: 047 | Train loss: 0.9885 | Train acc: 51.37% | Val loss: 0.9974 | Val acc: 51.62% | LR: 0.000011
Epoch: 048 | Train loss: 0.9964 | Train acc: 50.72% | Val loss: 0.9974 | Val acc: 51.59% | LR: 0.000011
Epoch: 049 | Train loss: 0.9921 | Train acc: 50.89% | Val loss: 0.9974 | Val acc: 51.46% | LR: 0.000011
Epoch: 050 | Train loss: 1.0093 | Train acc: 50.82% | Val loss: 0.9974 | Val acc: 51.52% | LR: 0.000011
Epoch: 051 | Train loss: 1.0058 | Train acc: 50.52% | Val loss: 0.9974 | Val acc: 51.54% | LR: 0.000010
Epoch: 052 | Train loss: 0.9964 | Train acc: 50.89% | Val loss: 0.9973 | Val acc: 51.56% | LR: 0.000010
Epoch: 053 | Train loss: 0.9958 | Train acc: 51.03% | Val loss: 0.9973 | Val acc: 51.58% | LR: 0.000010
Epoch: 054 | Train loss: 0.9943 | Train acc: 51.34% | Val loss: 0.9973 | Val acc: 51.64% | LR: 0.000010

[I 2025-09-23 19:42:36,962] Trial 176 finished with value: 0.5153768539428711 and parameters: {'lr': 1.3826368916292164e-05, 'hidden_size': 70, 'dropout': 0.21734948374439497, 'weight_decay': 0.00021996784828135196}. Best is trial 163 with value: 0.5466681122779846.

Epoch: 000 | Train loss: 1.0038 | Train acc: 48.82% | Val loss: 0.9973 | Val acc: 53.44% | LR: 0.000016
Epoch: 001 | Train loss: 1.0023 | Train acc: 49.17% | Val loss: 0.9973 | Val acc: 53.60% | LR: 0.000016
Epoch: 002 | Train loss: 1.0014 | Train acc: 49.46% | Val loss: 0.9972 | Val acc: 53.77% | LR: 0.000016
Epoch: 003 | Train loss: 1.0026 | Train acc: 48.98% | Val loss: 0.9972 | Val acc: 53.81% | LR: 0.000016
Epoch: 004 | Train loss: 1.0024 | Train acc: 49.12% | Val loss: 0.9972 | Val acc: 53.99% | LR: 0.000016
Epoch: 005 | Train loss: 1.0023 | Train acc: 49.11% | Val loss: 0.9973 | Val acc: 53.93% | LR: 0.000016
Epoch: 006 | Train loss: 1.0019 | Train acc: 49.09% | Val loss: 0.9972 | Val acc: 54.01% | LR: 0.000016
Epoch: 007 | Train loss: 1.0014 | Train acc: 49.20% | Val loss: 0.9972 | Val acc: 54.07% | LR: 0.000016
Epoch: 008 | Train loss: 1.0009 | Train acc: 49.50% | Val loss: 0.9972 | Val acc: 54.13% | LR: 0.000016
Epoch: 009 | Train loss: 1.0005 | Train acc: 49.68% | Val loss: 0.9972 | Val acc: 54.09% | LR: 0.000015
Epoch: 010 | Train loss: 1.0014 | Train acc: 49.04% | Val loss: 0.9971 | Val acc: 54.09% | LR: 0.000015
Epoch: 011 | Train loss: 1.0005 | Train acc: 49.70% | Val loss: 0.9971 | Val acc: 54.19% | LR: 0.000015
Epoch: 012 | Train loss: 1.0002 | Train acc: 49.81% | Val loss: 0.9971 | Val acc: 54.35% | LR: 0.000015
Epoch: 013 | Train loss: 1.0011 | Train acc: 49.18% | Val loss: 0.9970 | Val acc: 54.31% | LR: 0.000015
Epoch: 014 | Train loss: 1.0006 | Train acc: 49.30% | Val loss: 0.9970 | Val acc: 54.27% | LR: 0.000015
Epoch: 015 | Train loss: 1.0001 | Train acc: 49.74% | Val loss: 0.9970 | Val acc: 54.31% | LR: 0.000015
Epoch: 016 | Train loss: 0.9997 | Train acc: 50.14% | Val loss: 0.9969 | Val acc: 54.17% | LR: 0.000015
Epoch: 017 | Train loss: 0.9999 | Train acc: 49.97% | Val loss: 0.9966 | Val acc: 54.19% | LR: 0.000015
Epoch: 018 | Train loss: 0.9999 | Train acc: 49.97% | Val loss: 0.9966 | Val acc: 54.10% | LR: 0.000015
Epoch: 019 | Train loss: 0.9998 | Train acc: 50.30% | Val loss: 0.9965 | Val acc: 54.02% | LR: 0.000015
Epoch: 020 | Train loss: 0.9998 | Train acc: 50.24% | Val loss: 0.9965 | Val acc: 54.14% | LR: 0.000015
Epoch: 021 | Train loss: 0.9997 | Train acc: 50.09% | Val loss: 0.9964 | Val acc: 53.92% | LR: 0.000015
Epoch: 022 | Train loss: 0.9995 | Train acc: 50.25% | Val loss: 0.9963 | Val acc: 53.76% | LR: 0.000015
Epoch: 023 | Train loss: 0.9994 | Train acc: 50.20% | Val loss: 0.9962 | Val acc: 53.55% | LR: 0.000015
Epoch: 024 | Train loss: 0.9993 | Train acc: 50.41% | Val loss: 0.9962 | Val acc: 53.51% | LR: 0.000015
Epoch: 025 | Train loss: 0.9992 | Train acc: 50.59% | Val loss: 0.9962 | Val acc: 53.53% | LR: 0.000015
Epoch: 026 | Train loss: 0.9988 | Train acc: 50.89% | Val loss: 0.9962 | Val acc: 53.58% | LR: 0.000015
Epoch: 027 | Train loss: 0.9991 | Train acc: 50.77% | Val loss: 0.9962 | Val acc: 53.85% | LR: 0.000014
Epoch: 028 | Train loss: 0.9987 | Train acc: 50.82% | Val loss: 0.9963 | Val acc: 53.47% | LR: 0.000014
Epoch: 029 | Train loss: 0.9981 | Train acc: 51.29% | Val loss: 0.9963 | Val acc: 53.25% | LR: 0.000014
Epoch: 030 | Train loss: 0.9982 | Train acc: 51.10% | Val loss: 0.9963 | Val acc: 53.13% | LR: 0.000014
Epoch: 031 | Train loss: 0.9980 | Train acc: 51.18% | Val loss: 0.9962 | Val acc: 53.21% | LR: 0.000014
Epoch: 032 | Train loss: 0.9991 | Train acc: 50.46% | Val loss: 0.9961 | Val acc: 53.20% | LR: 0.000014
Epoch: 033 | Train loss: 0.9984 | Train acc: 50.84% | Val loss: 0.9960 | Val acc: 53.20% | LR: 0.000014
Epoch: 034 | Train loss: 0.9988 | Train acc: 50.75% | Val loss: 0.9959 | Val acc: 53.08% | LR: 0.000014
Epoch: 035 | Train loss: 0.9978 | Train acc: 51.19% | Val loss: 0.9959 | Val acc: 53.32% | LR: 0.000014
Epoch: 036 | Train loss: 0.9977 | Train acc: 50.92% | Val loss: 0.9959 | Val acc: 53.37% | LR: 0.000014
Epoch: 037 | Train loss: 0.9982 | Train acc: 50.74% | Val loss: 0.9957 | Val acc: 53.44% | LR: 0.000013
Epoch: 038 | Train loss: 0.9982 | Train acc: 50.74% | Val loss: 0.9956 | Val acc: 53.34% | LR: 0.000013
Epoch: 039 | Train loss: 0.9976 | Train acc: 50.92% | Val loss: 0.9956 | Val acc: 53.32% | LR: 0.000013
Epoch: 040 | Train loss: 0.9961 | Train acc: 51.53% | Val loss: 0.9956 | Val acc: 53.47% | LR: 0.000013
Epoch: 041 | Train loss: 0.9968 | Train acc: 51.19% | Val loss: 0.9957 | Val acc: 53.31% | LR: 0.000013
Epoch: 042 | Train loss: 0.9981 | Train acc: 50.53% | Val loss: 0.9957 | Val acc: 53.17% | LR: 0.000013
Epoch: 043 | Train loss: 0.9983 | Train acc: 50.67% | Val loss: 0.9957 | Val acc: 52.97% | LR: 0.000013
Epoch: 044 | Train loss: 0.9974 | Train acc: 50.75% | Val loss: 0.9957 | Val acc: 52.69% | LR: 0.000013
Epoch: 045 | Train loss: 0.9964 | Train acc: 51.09% | Val loss: 0.9957 | Val acc: 52.61% | LR: 0.000013
Epoch: 046 | Train loss: 0.9963 | Train acc: 50.99% | Val loss: 0.9958 | Val acc: 52.49% | LR: 0.000012
Epoch: 047 | Train loss: 0.9963 | Train acc: 51.17% | Val loss: 0.9958 | Val acc: 52.35% | LR: 0.000012
Epoch: 048 | Train loss: 0.9959 | Train acc: 51.09% | Val loss: 0.9957 | Val acc: 52.37% | LR: 0.000012
Epoch: 049 | Train loss: 0.9970 | Train acc: 50.74% | Val loss: 0.9957 | Val acc: 52.40% | LR: 0.000012
Epoch: 050 | Train loss: 0.9971 | Train acc: 50.66% | Val loss: 0.9956 | Val acc: 52.38% | LR: 0.000012
Epoch: 051 | Train loss: 0.9972 | Train acc: 50.66% | Val loss: 0.9956 | Val acc: 52.44% | LR: 0.000012
Epoch: 052 | Train loss: 0.9959 | Train acc: 50.93% | Val loss: 0.9955 | Val acc: 52.40% | LR: 0.000012
Epoch: 053 | Train loss: 0.9957 | Train acc: 50.86% | Val loss: 0.9956 | Val acc: 52.46% | LR: 0.000011
Epoch: 054 | Train loss: 0.9950 | Train acc: 51.19% | Val loss: 0.9955 | Val acc: 52.45% | LR: 0.000011
Epoch: 055 | Train loss: 0.9953 | Train acc: 50.96% | Val loss: 0.9955 | Val acc: 52.41% | LR: 0.000011
Epoch: 056 | Train loss: 0.9968 | Train acc: 50.68% | Val loss: 0.9954 | Val acc: 52.37% | LR: 0.000011
Epoch: 057 | Train loss: 0.9962 | Train acc: 50.71% | Val loss: 0.9955 | Val acc: 52.13% | LR: 0.000011
Epoch: 058 | Train loss: 0.9946 | Train acc: 51.01% | Val loss: 0.9955 | Val acc: 52.13% | LR: 0.000011
Epoch: 059 | Train loss: 0.9982 | Train acc: 50.29% | Val loss: 0.9955 | Val acc: 51.99% | LR: 0.000011
Epoch: 060 | Train loss: 0.9939 | Train acc: 50.91% | Val loss: 0.9954 | Val acc: 51.99% | LR: 0.000010
Epoch: 061 | Train loss: 0.9946 | Train acc: 50.55% | Val loss: 0.9954 | Val acc: 51.95% | LR: 0.000010

[I 2025-09-23 19:43:28,408] Trial 177 finished with value: 0.5192765951156616 and parameters: {'lr': 1.565594641796093e-05, 'hidden_size': 68, 'dropout': 0.2257617936356838, 'weight_decay': 0.00017548489059165514}. Best is trial 163 with value: 0.5466681122779846.

Epoch: 000 | Train loss: 1.0002 | Train acc: 49.92% | Val loss: 0.9945 | Val acc: 54.23% | LR: 0.000230
Epoch: 001 | Train loss: 0.9997 | Train acc: 49.94% | Val loss: 0.9941 | Val acc: 54.68% | LR: 0.000230
Epoch: 002 | Train loss: 0.9947 | Train acc: 51.40% | Val loss: 0.9929 | Val acc: 53.23% | LR: 0.000230
Epoch: 003 | Train loss: 0.9941 | Train acc: 51.11% | Val loss: 0.9911 | Val acc: 53.31% | LR: 0.000229
Epoch: 004 | Train loss: 0.9924 | Train acc: 51.04% | Val loss: 0.9905 | Val acc: 52.68% | LR: 0.000229
Epoch: 005 | Train loss: 0.9879 | Train acc: 51.29% | Val loss: 0.9891 | Val acc: 52.37% | LR: 0.000229
Epoch: 006 | Train loss: 0.9881 | Train acc: 50.95% | Val loss: 0.9869 | Val acc: 52.22% | LR: 0.000229
Epoch: 007 | Train loss: 0.9835 | Train acc: 51.19% | Val loss: 0.9846 | Val acc: 52.18% | LR: 0.000228
Epoch: 008 | Train loss: 0.9911 | Train acc: 50.68% | Val loss: 0.9760 | Val acc: 52.41% | LR: 0.000228
Epoch: 009 | Train loss: 0.9904 | Train acc: 50.67% | Val loss: 0.9734 | Val acc: 52.23% | LR: 0.000227
Epoch: 010 | Train loss: 0.9883 | Train acc: 50.74% | Val loss: 0.9769 | Val acc: 51.85% | LR: 0.000227
Epoch: 011 | Train loss: 0.9884 | Train acc: 50.58% | Val loss: 0.9806 | Val acc: 51.17% | LR: 0.000226
Epoch: 012 | Train loss: 0.9827 | Train acc: 50.92% | Val loss: 0.9812 | Val acc: 51.04% | LR: 0.000226
Epoch: 013 | Train loss: 0.9825 | Train acc: 51.02% | Val loss: 0.9806 | Val acc: 51.13% | LR: 0.000225
Epoch: 014 | Train loss: 0.9904 | Train acc: 50.60% | Val loss: 0.9834 | Val acc: 50.92% | LR: 0.000224
Epoch: 015 | Train loss: 0.9812 | Train acc: 51.17% | Val loss: 0.9844 | Val acc: 50.84% | LR: 0.000223
Epoch: 016 | Train loss: 0.9842 | Train acc: 50.90% | Val loss: 0.9898 | Val acc: 50.73% | LR: 0.000223
Epoch: 017 | Train loss: 0.9792 | Train acc: 51.17% | Val loss: 0.9919 | Val acc: 50.55% | LR: 0.000222

In [ ]:
torch.manual_seed(42)
torch.cuda.manual_seed(42)

model = SLOT(
      input_size=len(price_features),
      hidden_size=hidden_size,
).to(device)

model.load_state_dict(torch.load(dataset_dir / "best_SLOT_model.pth", map_location=device))

test_loss = 0.0
test_acc = 0.0

model.eval()

with torch.inference_mode():
    for X_test, o_test, c_test, y_test in test_dataloader:

        X_test, o_test, c_test, y_test = X_test.to(device), o_test.to(device), c_test.to(device), y_test.to(device)

        logits = model(X_test, o_test, c_test)
        loss, acc = evaluate(logits, y_test)

        test_loss += loss.item()
        test_acc += acc


    test_loss /= len(test_dataloader)
    test_acc /= len(test_dataloader)

print(f"Test loss: {test_loss:.4f} | Test acc: {100*test_acc:.2f}%")

NameError: name 'torch' is not defined