<a href="https://colab.research.google.com/github/brien60/Stock-LSTM/blob/SLOT/SLOT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Setup

### Imports

In [1]:
import torch
from torch import nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, random_split
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence

from pathlib import Path
import json
import re

import sentencepiece as sp
from collections import Counter

import pandas as pd

from tqdm import tqdm

import os

import wandb

try:
  import optuna
  from optuna.integration.wandb import WeightsAndBiasesCallback

except:
  !pip install -q optuna
  !pip install -q optuna-integration[wandb]
  import optuna
  from optuna.integration.wandb import WeightsAndBiasesCallback


import time

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.9/400.9 kB 14.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 4.5 MB/s eta 0:00:00

### Colab Setup Code

In [2]:
!git clone -q --branch SLOT https://github.com/brien60/Stock-LSTM.git
%cd Stock-LSTM/
!unzip -q data.zip -d /content/Stock-LSTM/data

/content/Stock-LSTM

### Constants

In [3]:
torch.manual_seed(42)
torch.cuda.manual_seed(42)
device = "cuda" if torch.cuda.is_available() else "cpu"

if device == "cuda":
    os.environ["CUDA_LAUNCH_BLOCKING"] = "1"


dataset = "acl18"
dataset_dir = Path(dataset.upper())

data_dir = Path(f"data/{dataset}")

tweet_dir = data_dir / "tweet"
price_dir = data_dir / "price"

tweet_files_list = list(tweet_dir.rglob("*/*"))
list.sort(tweet_files_list)

stock_names = [stock.name for stock in list(tweet_dir.rglob("*")) if stock.is_dir()]
list.sort(stock_names)

num_stocks = len(stock_names)

json_file = dataset_dir / "all_tweets.jsonl"
spm_file = dataset_dir / "spm/slot_tweet_spm.model"
tokens_file = dataset_dir / "all_tweets_tokenized.jsonl"


vocab_size = 10_000

window_size = 15

num_epochs = 150
batch_size = 1024

## SLOT Overview

SLOT (Self-supervised Learning of Tweets for Capturing Multi-level Price Trends) aims to address
1. the sparsity of tweets, with the number of tweets being heavily biased towards the most popular stocks.
2. the fact that tweets have noisy information that are often irrelevant to the actual stock movement.

The first problem was addressed by having SLOT learn the stock and tweet embeddings in the same vector space through self-supervised learning. This allows the use of any tweet for even unpopular stocks.

To tackle the second problem, SLOT uses tweets to learn multi-level relationships between stocks, rather than using them as direct evidence for stock prediction (e.g. positive sentiment = up).

## Attention LSTM

In [4]:

class ALSTM(nn.Module):
    def __init__(self, input_size, hidden_size, dropout):
        super().__init__()
        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            batch_first=True,
        )
        self.dropout = nn.Dropout(dropout)
        self.ln = nn.Linear(hidden_size, hidden_size)
        self.tanh = nn.Tanh()
        self.u = nn.Parameter(data=torch.randn(hidden_size))


    def forward(self, x):
        # x: (batch, seq_len, input_size)

        # output: (batch, seq_len, hidden_size)
        # h_n, c_n : (num_layers, batch, hidden_size)
        output, (h_n, c_n) = self.lstm(x)
        output = self.dropout(output)
        output = self.tanh(self.ln(output))

        # query: u, key: output, values: output
        attn_scores = torch.matmul(output, self.u) # (batch, seq_len, hidden_size) @ (hidden_size) -> (batch, seq_len)
        weights = attn_scores / attn_scores.sum(dim=1, keepdim=True)
        weights = weights.unsqueeze(dim=-1) # (batch, seq_len, 1)

        # (batch, seq_len, 1) * (batch, seq_len, hidden_size) -> (batch, seq_len, hidden_size)
        # (batch, seq_len, hidden_size) -> (batch, hidden_size)
        h_attn = (weights * output).sum(dim=1)

        # (batch, hidden_size) || (batch, hidden_size) -> (batch, 2*hidden_size)
        h_out = torch.cat((h_n[0], h_attn), dim=1) # both the general summary and the attention

        return h_out

## Price Features

The price features that compose a feature vector $x_{st}$ are
- Price movements in a day: *c_open, c_high, c_low*
- Price movements between days: *n_close, n_adj_close*
- Long-term movements: *5_day, 10_day, ... , 30_day*

So the daily prices of days $t-29$ to $t$ are used to generate each $x_{st}$

These features have already been calculated and normalized in the csv files.

### Extracting features data

In [27]:
data_files_list = list(price_dir.rglob("*.csv"))

data_list = []

price_features = []
labels = []

for i, stock_file in enumerate(data_files_list):
    stock = stock_file.stem
    df = pd.read_csv(stock_file)
    # columns = [
    #     f'{stock}_c_open', f'{stock}_c_high', f'{stock}_c_low',
    #     f'{stock}_n_close', f'{stock}_n_adj_close',
    #     f'{stock}_adj_sum_5', f'{stock}_adj_sum_10', f'{stock}_adj_sum_15',
    #     f'{stock}_adj_sum_20', f'{stock}_adj_sum_25', f'{stock}_adj_sum_30',
    #     f'{stock}_label', f'{stock}_closing_price_for_label'
    # ]

    # price_features.extend(columns[:-2])
    # labels.append(columns[-2])

    # if i != 0:
    # df.drop(columns=['date'], inplace=True)
    # else:
        # columns = ['date'] + columns

    # df.columns = columns

    df['label'] = df['label'].shift(-1)
    df = df.dropna()

    data_list.append(df)

# combined_df = pd.concat(data_list, axis=1)
# combined_df = combined_df.dropna()

# combined_df
data_list[0]

,date,c_open,c_high,c_low,n_close,n_adj_close,adj_sum_5,adj_sum_10,adj_sum_15,adj_sum_20,adj_sum_25,adj_sum_30,label,closing_price_for_label
0,2013-06-03,0.315221,0.403677,-1.789139,-0.162949,-0.162949,-0.060053,0.693978,0.254750,-1.822094,-3.904163,-5.357703,0.0,802.619995
1,2013-06-04,0.259175,1.541274,-0.580953,-0.489646,-0.489646,0.290475,0.640925,0.925432,-0.888392,-2.934205,-4.442024,0.0,798.690002
2,2013-06-05,0.307984,1.697046,-0.062854,-0.399404,-0.399404,0.773852,0.661597,1.366688,-0.048146,-2.044601,-3.668510,1.0,795.500000
3,2013-06-06,-1.371144,0.016132,-2.345207,1.307357,1.307357,-0.567319,-0.539772,0.059806,-0.899804,-2.753595,-4.476944,1.0,805.900024
4,2013-06-07,-0.767961,0.341721,-1.388943,1.309094,1.309094,-1.545472,-1.667586,-1.099477,-1.696860,-3.478622,-5.281647,1.0,816.450012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,2015-12-23,0.387002,0.461272,-0.924911,0.122119,0.122119,0.569325,1.461315,1.426054,0.687537,0.405953,0.525282,0.0,1279.050049
647,2015-12-24,0.426532,0.585205,-0.083258,-0.467543,-0.467543,0.402810,1.675324,1.865783,1.267805,0.860538,0.849525,0.0,1273.069946
648,2015-12-28,-0.468983,0.139834,-1.552288,-0.008639,-0.008639,0.211791,1.586934,1.730458,1.386417,0.832519,0.750746,1.0,1272.959961
649,2015-12-29,-1.873466,0.122848,-1.949479,2.312725,2.312725,-1.643583,-0.674679,-0.569208,-0.699787,-1.382650,-1.514770,-1.0,1302.400024
650,2015-12-30,0.763285,0.970400,-0.084558,-1.016584,-1.016584,-0.452390,0.077257,0.375384,0.345881,-0.292752,-0.445668,-1.0,1289.160034

### Remove Dates

In [28]:
for df in data_list:
    df.drop(columns=['date'], inplace=True)

data_list[0]

,c_open,c_high,c_low,n_close,n_adj_close,adj_sum_5,adj_sum_10,adj_sum_15,adj_sum_20,adj_sum_25,adj_sum_30,label,closing_price_for_label
0,0.315221,0.403677,-1.789139,-0.162949,-0.162949,-0.060053,0.693978,0.254750,-1.822094,-3.904163,-5.357703,0.0,802.619995
1,0.259175,1.541274,-0.580953,-0.489646,-0.489646,0.290475,0.640925,0.925432,-0.888392,-2.934205,-4.442024,0.0,798.690002
2,0.307984,1.697046,-0.062854,-0.399404,-0.399404,0.773852,0.661597,1.366688,-0.048146,-2.044601,-3.668510,1.0,795.500000
3,-1.371144,0.016132,-2.345207,1.307357,1.307357,-0.567319,-0.539772,0.059806,-0.899804,-2.753595,-4.476944,1.0,805.900024
4,-0.767961,0.341721,-1.388943,1.309094,1.309094,-1.545472,-1.667586,-1.099477,-1.696860,-3.478622,-5.281647,1.0,816.450012
...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,0.387002,0.461272,-0.924911,0.122119,0.122119,0.569325,1.461315,1.426054,0.687537,0.405953,0.525282,0.0,1279.050049
647,0.426532,0.585205,-0.083258,-0.467543,-0.467543,0.402810,1.675324,1.865783,1.267805,0.860538,0.849525,0.0,1273.069946
648,-0.468983,0.139834,-1.552288,-0.008639,-0.008639,0.211791,1.586934,1.730458,1.386417,0.832519,0.750746,1.0,1272.959961
649,-1.873466,0.122848,-1.949479,2.312725,2.312725,-1.643583,-0.674679,-0.569208,-0.699787,-1.382650,-1.514770,-1.0,1302.400024
650,0.763285,0.970400,-0.084558,-1.016584,-1.016584,-0.452390,0.077257,0.375384,0.345881,-0.292752,-0.445668,-1.0,1289.160034

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['c_open'].plot(kind='hist', bins=20, title='c_open')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['c_high'].plot(kind='hist', bins=20, title='c_high')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['c_low'].plot(kind='hist', bins=20, title='c_low')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='index', y='c_open', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='c_open', y='c_high', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='c_high', y='c_low', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='c_low', y='n_close', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['c_open']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_8.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('c_open')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['c_high']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_9.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('c_high')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['c_low']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('c_low')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['n_close']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_11.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('n_close')

from matplotlib import pyplot as plt
_df_12['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_13['c_open'].plot(kind='line', figsize=(8, 4), title='c_open')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_14['c_high'].plot(kind='line', figsize=(8, 4), title='c_high')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_15['c_low'].plot(kind='line', figsize=(8, 4), title='c_low')
plt.gca().spines[['top', 'right']].set_visible(False)

### Make X and y tensors

In [29]:
columns = data_list[0].columns.to_list()
price_features = columns[: -2]
labels = columns[-2]

In [30]:
X_st = [
    torch.tensor(df[price_features].to_numpy(), dtype=torch.float)
    for df in data_list
]
y = [
    torch.tensor(df[labels].to_numpy(), dtype=torch.float)
    for df in data_list
]

X_st = torch.stack(X_st).transpose(0, 1).to(device)
y = torch.stack(y).transpose(0, 1).to(device)

y = torch.sign(y)

X_st[0, :5], X_st.shape, y, y.shape

(tensor([[ 0.3152,  0.4037, -1.7891, -0.1629, -0.1629, -0.0601,  0.6940,  0.2548,
          -1.8221, -3.9042, -5.3577],
         [-0.3088,  0.6176, -1.4998,  0.3541,  0.3541, -0.9793, -2.8275, -3.6965,
          -3.8730, -4.0141, -4.0494],
         [-1.5480,  0.3031, -2.3598,  1.6170,  1.6170, -0.1256,  1.0089,  1.7204,
           1.6346,  1.9394,  1.9236],
         [-1.0971,  0.1097, -2.3039,  0.9972,  0.9972,  0.1097,  0.8256,  1.2379,
           0.9010,  0.7537,  0.2670],
         [ 1.4930,  2.1386, -1.9268, -1.3926, -1.3926,  3.9988,  4.7059,  5.6074,
           5.6017,  5.6725,  6.4114]], device='cuda:0'),
 torch.Size([651, 87, 11]),
 tensor([[ 0.,  0., -1.,  ..., -1.,  0., -1.],
         [ 0., -1., -1.,  ..., -1., -1., -1.],
         [ 1.,  1.,  1.,  ...,  1.,  0.,  0.],
         ...,
         [ 1.,  1.,  1.,  ...,  1.,  1.,  1.],
         [-1.,  0.,  0.,  ...,  0.,  0.,  0.],
         [-1.,  1., -1.,  ..., -1., -1., -1.]], device='cuda:0'),
 torch.Size([651, 87]))

## Self-supervised Learning of Embeddings

The goal is to learn tweet (h_e) and stock (h_s) embeddings in the same semantic space, that is, learning the embeddings together such that one embedding can be used to query for the other.
- a stock embedding and the embedding of tweet relevant to it are close together (higher dot product)
- stocks that are frequently co-mentioned will have similar embeddings; this naturally groups together stocks in the same industry/sector.
- solves problem of tweet sparsity; the model can associate stocks with tweets that don't directly mention it as long as they are close in vector space.

This was done by training for stock identification: predict the mentioned stock in a tweet when the stock symbol is masked.

Every tweet is tokenized with Sentence Piece and then the tokens that correspond to the stock the tweet mentions are masked with the special token MASK.
- "Thank you Apple for the new iPhone." -> "Thank you [MASK] for the new iPhone."

### Stock Identification Model

Use a BiLSTM (need to understand the context on both sides of the mask token).
- Using a transformer risks overfitting.

The stock embedding is a learnable parameter.

The hidden state vector generated at the masked token is used as the tweet embedding because it
- captures the immediate left (via the forward LSTM) and right context (via the backward LSTM) of the tweet, making it exactly what we need for stock identification,
- and it is the part of the tweet that most connects to mentioned stock.

### Write raw data to json

In [ ]:

buffer = []
buffer_size = 100_000
lines = 0

with open(json_file, "w", encoding="utf-8") as out:
    for tweet_file in tweet_files_list:

        with open(tweet_file, "r", encoding="utf-8") as f:


            for line in f:
                tweet = json.loads(line)

                json_tweet = {
                    "date": tweet_file.stem,
                    "stock": tweet_file.parent.name,
                    "tweet": tweet["text"].replace("\n", " ")
                }

                buffer.append(json.dumps(json_tweet))

                if len(buffer) >= buffer_size:
                    out.write("\n".join(buffer) + "\n")
                    lines += len(buffer)

                    buffer.clear()

                    print(f"{lines} lines written")

    if buffer:
        lines += len(buffer)
        out.write("\n".join(buffer) + "\n")
        print(f"{lines} lines written")

print("All tweets written")

100000 lines written
119844 lines written
All tweets written

### Txt file for sp training

In [ ]:
input_file = json_file
output_file = dataset_dir / "tweets_for_sp.txt"

with open(input_file, "r", encoding="utf-8") as f, open(output_file, "w", encoding="utf-8") as out:
    for line in f:
        tweet = json.loads(line)
        out.write(tweet["tweet"] + "\n")

### SPM Training

In [ ]:
spm_file = dataset_dir / "spm/slot_tweet_spm"
vocab_size = 10_000

sp.SentencePieceTrainer.train(
    input=output_file,
    model_prefix=spm_file,
    vocab_size=vocab_size,
    model_type="unigram",
    character_coverage=1.0,
    input_sentence_size=lines,
    shuffle_input_sentence=True,
    user_defined_symbols=["<MASK>", "<PAD>", "<UNK>"]
)

spm_file = str(spm_file.with_suffix(".model"))

In [5]:
slot_spm = sp.SentencePieceProcessor()
slot_spm.load(str(spm_file))

mask_id = slot_spm.piece_to_id("<MASK>")
pad_id = slot_spm.piece_to_id("<PAD>")
unk_id = slot_spm.piece_to_id("<UNK>")

mask_id, pad_id, unk_id

(3, 4, 5)

### Create tokenized jsonl

In [6]:
all_dates = []

for tweet_file in tweet_files_list:
        date = tweet_file.stem
        all_dates.append(date)


all_dates = sorted(dict.fromkeys(all_dates))

start_date, end_date = "2014-02-19", "2015-12-31"
start_date_idx, end_date_idx = all_dates.index(start_date), all_dates.index(end_date)

all_dates = all_dates[start_date_idx : end_date_idx + 1]

num_dates = len(all_dates)
num_dates, all_dates

(651,
 ['2014-02-19',
  '2014-02-20',
  '2014-02-21',
  '2014-02-22',
  '2014-02-23',
  '2014-02-24',
  '2014-02-25',
  '2014-02-26',
  '2014-02-27',
  '2014-02-28',
  '2014-03-01',
  '2014-03-02',
  '2014-03-03',
  '2014-03-04',
  '2014-03-05',
  '2014-03-06',
  '2014-03-07',
  '2014-03-08',
  '2014-03-09',
  '2014-03-10',
  '2014-03-11',
  '2014-03-12',
  '2014-03-13',
  '2014-03-14',
  '2014-03-15',
  '2014-03-16',
  '2014-03-17',
  '2014-03-18',
  '2014-03-19',
  '2014-03-20',
  '2014-03-21',
  '2014-03-22',
  '2014-03-23',
  '2014-03-24',
  '2014-03-25',
  '2014-03-26',
  '2014-03-27',
  '2014-03-28',
  '2014-03-29',
  '2014-03-30',
  '2014-03-31',
  '2014-04-01',
  '2014-04-02',
  '2014-04-03',
  '2014-04-04',
  '2014-04-05',
  '2014-04-06',
  '2014-04-07',
  '2014-04-08',
  '2014-04-09',
  '2014-04-10',
  '2014-04-11',
  '2014-04-12',
  '2014-04-13',
  '2014-04-14',
  '2014-04-15',
  '2014-04-16',
  '2014-04-17',
  '2014-04-18',
  '2014-04-19',
  '2014-04-20',
  '2014-04-21',
  '2014-04-22',
  '2014-04-23',
  '2014-04-24',
  '2014-04-25',
  '2014-04-26',
  '2014-04-27',
  '2014-04-28',
  '2014-04-29',
  '2014-04-30',
  '2014-05-01',
  '2014-05-02',
  '2014-05-03',
  '2014-05-04',
  '2014-05-05',
  '2014-05-06',
  '2014-05-07',
  '2014-05-08',
  '2014-05-09',
  '2014-05-10',
  '2014-05-11',
  '2014-05-12',
  '2014-05-13',
  '2014-05-14',
  '2014-05-15',
  '2014-05-16',
  '2014-05-17',
  '2014-05-18',
  '2014-05-19',
  '2014-05-20',
  '2014-05-21',
  '2014-05-22',
  '2014-05-23',
  '2014-05-24',
  '2014-05-25',
  '2014-05-26',
  '2014-05-27',
  '2014-05-28',
  '2014-05-29',
  '2014-05-30',
  '2014-05-31',
  '2014-06-01',
  '2014-06-02',
  '2014-06-03',
  '2014-06-04',
  '2014-06-05',
  '2014-06-06',
  '2014-06-07',
  '2014-06-08',
  '2014-06-09',
  '2014-06-10',
  '2014-06-11',
  '2014-06-12',
  '2014-06-13',
  '2014-06-14',
  '2014-06-15',
  '2014-06-16',
  '2014-06-18',
  '2014-06-19',
  '2014-06-20',
  '2014-06-21',
  '2014-06-22',
  '2014-06-23',
  '2014-06-24',
  '2014-06-25',
  '2014-06-26',
  '2014-06-27',
  '2014-06-28',
  '2014-06-29',
  '2014-06-30',
  '2014-07-01',
  '2014-07-02',
  '2014-07-03',
  '2014-07-04',
  '2014-07-05',
  '2014-07-06',
  '2014-07-07',
  '2014-07-08',
  '2014-07-09',
  '2014-07-10',
  '2014-07-11',
  '2014-07-12',
  '2014-07-13',
  '2014-07-14',
  '2014-07-15',
  '2014-07-16',
  '2014-07-17',
  '2014-07-18',
  '2014-07-19',
  '2014-07-20',
  '2014-07-21',
  '2014-07-22',
  '2014-07-23',
  '2014-07-24',
  '2014-07-25',
  '2014-07-26',
  '2014-07-27',
  '2014-07-28',
  '2014-07-29',
  '2014-07-30',
  '2014-07-31',
  '2014-08-01',
  '2014-08-02',
  '2014-08-03',
  '2014-08-04',
  '2014-08-05',
  '2014-08-07',
  '2014-08-08',
  '2014-08-09',
  '2014-08-10',
  '2014-08-11',
  '2014-08-12',
  '2014-08-13',
  '2014-08-14',
  '2014-08-15',
  '2014-08-16',
  '2014-08-17',
  '2014-08-18',
  '2014-08-19',
  '2014-08-20',
  '2014-08-21',
  '2014-08-22',
  '2014-08-23',
  '2014-08-24',
  '2014-08-25',
  '2014-08-26',
  '2014-08-27',
  '2014-08-28',
  '2014-08-29',
  '2014-08-30',
  '2014-08-31',
  '2014-09-01',
  '2014-09-02',
  '2014-09-03',
  '2014-09-04',
  '2014-09-05',
  '2014-09-06',
  '2014-09-07',
  '2014-09-08',
  '2014-09-09',
  '2014-09-10',
  '2014-09-11',
  '2014-09-12',
  '2014-09-13',
  '2014-09-14',
  '2014-09-15',
  '2014-09-16',
  '2014-09-17',
  '2014-09-18',
  '2014-09-19',
  '2014-09-20',
  '2014-09-21',
  '2014-09-22',
  '2014-09-23',
  '2014-09-29',
  '2014-09-30',
  '2014-10-01',
  '2014-10-02',
  '2014-10-03',
  '2014-10-04',
  '2014-10-05',
  '2014-10-06',
  '2014-10-07',
  '2014-10-08',
  '2014-10-09',
  '2014-10-10',
  '2014-10-11',
  '2014-10-12',
  '2014-10-13',
  '2014-10-14',
  '2014-10-15',
  '2014-10-16',
  '2014-10-17',
  '2014-10-18',
  '2014-10-19',
  '2014-10-20',
  '2014-10-21',
  '2014-10-22',
  '2014-10-23',
  '2014-10-24',
  '2014-10-25',
  '2014-10-26',
  '2014-10-27',
  '2014-10-28',
  '2014-10-29',
  '2014-10-30',
  '2014-10-31',
  '2014-11-01',
  '2014-11-02',
  '2014-11-03',
  '2014-11-04',
  '2014-11-05',
  '2014-11-06',
  '2014-11-07',
  '2014-11-08',
  '2014-11-09',
  '2014-11-14',
  '2014-11-23',
  '2014-11-24',
  '2014-11-25',
  '2014-11-26',
  '2014-11-27',
  '2014-11-28',
  '2014-11-29',
  '2014-11-30',
  '2014-12-01',
  '2014-12-02',
  '2014-12-03',
  '2014-12-04',
  '2014-12-05',
  '2014-12-06',
  '2014-12-07',
  '2014-12-08',
  '2014-12-09',
  '2014-12-10',
  '2014-12-11',
  '2014-12-12',
  '2014-12-13',
  '2014-12-14',
  '2014-12-15',
  '2014-12-16',
  '2014-12-17',
  '2014-12-18',
  '2014-12-19',
  '2014-12-21',
  '2014-12-22',
  '2014-12-23',
  '2014-12-24',
  '2014-12-25',
  '2014-12-26',
  '2014-12-27',
  '2014-12-28',
  '2014-12-29',
  '2014-12-30',
  '2014-12-31',
  '2015-01-01',
  '2015-01-02',
  '2015-01-03',
  '2015-01-04',
  '2015-01-05',
  '2015-01-06',
  '2015-01-07',
  '2015-01-08',
  '2015-01-09',
  '2015-01-10',
  '2015-01-11',
  '2015-01-12',
  '2015-01-13',
  '2015-01-14',
  '2015-01-15',
  '2015-01-16',
  '2015-01-17',
  '2015-01-18',
  '2015-01-19',
  '2015-01-20',
  '2015-01-21',
  '2015-01-22',
  '2015-01-23',
  '2015-01-24',
  '2015-01-25',
  '2015-01-26',
  '2015-01-27',
  '2015-01-28',
  '2015-01-29',
  '2015-01-30',
  '2015-01-31',
  '2015-02-01',
  '2015-02-02',
  '2015-02-03',
  '2015-02-04',
  '2015-02-05',
  '2015-02-06',
  '2015-02-07',
  '2015-02-08',
  '2015-02-09',
  '2015-02-10',
  '2015-02-11',
  '2015-02-12',
  '2015-02-13',
  '2015-02-14',
  '2015-02-15',
  '2015-02-16',
  '2015-02-17',
  '2015-02-18',
  '2015-02-19',
  '2015-02-20',
  '2015-02-21',
  '2015-02-22',
  '2015-02-23',
  '2015-02-24',
  '2015-02-25',
  '2015-02-26',
  '2015-02-27',
  '2015-02-28',
  '2015-03-01',
  '2015-03-02',
  '2015-03-03',
  '2015-03-04',
  '2015-03-05',
  '2015-03-06',
  '2015-03-07',
  '2015-03-09',
  '2015-03-10',
  '2015-03-11',
  '2015-03-12',
  '2015-03-13',
  '2015-03-14',
  '2015-03-15',
  '2015-03-16',
  '2015-03-17',
  '2015-03-18',
  '2015-03-19',
  '2015-03-20',
  '2015-03-21',
  '2015-03-22',
  '2015-03-23',
  '2015-03-24',
  '2015-03-25',
  '2015-03-26',
  '2015-03-27',
  '2015-03-28',
  '2015-03-29',
  '2015-03-30',
  '2015-03-31',
  '2015-04-01',
  '2015-04-02',
  '2015-04-03',
  '2015-04-04',
  '2015-04-05',
  '2015-04-06',
  '2015-04-07',
  '2015-04-08',
  '2015-04-09',
  '2015-04-10',
  '2015-04-11',
  '2015-04-12',
  '2015-04-13',
  '2015-04-14',
  '2015-04-15',
  '2015-04-16',
  '2015-04-17',
  '2015-04-18',
  '2015-04-19',
  '2015-04-20',
  '2015-04-21',
  '2015-04-22',
  '2015-04-23',
  '2015-04-24',
  '2015-04-25',
  '2015-04-26',
  '2015-04-27',
  '2015-04-28',
  '2015-04-29',
  '2015-04-30',
  '2015-05-01',
  '2015-05-02',
  '2015-05-03',
  '2015-05-04',
  '2015-05-05',
  '2015-05-06',
  '2015-05-07',
  '2015-05-08',
  '2015-05-09',
  '2015-05-10',
  '2015-05-11',
  '2015-05-12',
  '2015-05-13',
  '2015-05-14',
  '2015-05-15',
  '2015-05-16',
  '2015-05-17',
  '2015-05-18',
  '2015-05-19',
  '2015-05-20',
  '2015-05-21',
  '2015-05-22',
  '2015-05-23',
  '2015-05-24',
  '2015-05-25',
  '2015-05-26',
  '2015-05-27',
  '2015-05-28',
  '2015-05-29',
  '2015-05-30',
  '2015-05-31',
  '2015-06-01',
  '2015-06-02',
  '2015-06-03',
  '2015-06-04',
  '2015-06-06',
  '2015-06-07',
  '2015-06-08',
  '2015-06-09',
  '2015-06-10',
  '2015-06-11',
  '2015-06-12',
  '2015-06-13',
  '2015-06-14',
  '2015-06-15',
  '2015-06-16',
  '2015-06-17',
  '2015-06-18',
  '2015-06-19',
  '2015-06-20',
  '2015-06-21',
  '2015-06-22',
  '2015-06-24',
  '2015-06-25',
  '2015-06-26',
  '2015-06-27',
  '2015-06-28',
  '2015-06-29',
  '2015-06-30',
  '2015-07-01',
  '2015-07-02',
  '2015-07-03',
  '2015-07-04',
  '2015-07-05',
  '2015-07-06',
  '2015-07-07',
  '2015-07-09',
  '2015-07-10',
  '2015-07-11',
  '2015-07-12',
  '2015-07-13',
  '2015-07-14',
  '2015-07-15',
  '2015-07-16',
  '2015-07-17',
  '2015-07-18',
  '2015-07-19',
  '2015-07-20',
  '2015-07-21',
  '2015-07-22',
  '2015-07-23',
  '2015-07-24',
  '2015-07-25',
  '2015-07-26',
  '2015-07-27',
  '2015-07-28',
  '2015-07-29',
  '2015-07-30',
  '2015-07-31',
  '2015-08-01',
  '2015-08-02',
  '2015-08-03',
  '2015-08-04',
  '2015-08-05',
  '2015-08-06',
  '2015-08-07',
  '2015-08-08',
  '2015-08-09',
  '2015-08-10',
  '2015-08-11',
  '2015-08-12',
  '2015-08-13',
  '2015-08-14',
  '2015-08-16',
  '2015-08-17',
  '2015-08-18',
  '2015-08-19',
  '2015-08-20',
  '2015-08-21',
  '2015-08-22',
  '2015-08-23',
  '2015-08-24',
  '2015-08-25',
  '2015-08-26',
  '2015-08-27',
  '2015-08-28',
  '2015-08-29',
  '2015-08-30',
  '2015-08-31',
  '2015-09-01',
  '2015-09-02',
  '2015-09-03',
  '2015-09-04',
  '2015-09-05',
  '2015-09-06',
  '2015-09-07',
  '2015-09-08',
  '2015-09-09',
  '2015-09-10',
  '2015-09-11',
  '2015-09-12',
  '2015-09-13',
  '2015-09-14',
  '2015-09-15',
  '2015-09-16',
  '2015-09-19',
  '2015-09-20',
  '2015-09-21',
  '2015-09-22',
  '2015-09-23',
  '2015-09-24',
  '2015-09-25',
  '2015-09-26',
  '2015-09-27',
  '2015-09-28',
  '2015-09-29',
  '2015-09-30',
  '2015-10-01',
  '2015-10-02',
  '2015-10-03',
  '2015-10-04',
  '2015-10-05',
  '2015-10-06',
  '2015-10-07',
  '2015-10-08',
  '2015-10-09',
  '2015-10-10',
  '2015-10-11',
  '2015-10-12',
  '2015-10-13',
  '2015-10-14',
  '2015-10-15',
  '2015-10-16',
  '2015-10-17',
  '2015-10-18',
  '2015-10-19',
  '2015-10-20',
  '2015-10-21',
  '2015-10-22',
  '2015-10-23',
  '2015-10-24',
  '2015-10-25',
  '2015-10-26',
  '2015-10-27',
  '2015-10-28',
  '2015-10-29',
  '2015-10-30',
  '2015-10-31',
  '2015-11-01',
  '2015-11-02',
  '2015-11-03',
  '2015-11-04',
  '2015-11-05',
  '2015-11-06',
  '2015-11-07',
  '2015-11-08',
  '2015-11-09',
  '2015-11-10',
  '2015-11-11',
  '2015-11-12',
  '2015-11-13',
  '2015-11-14',
  '2015-11-15',
  '2015-11-16',
  '2015-11-17',
  '2015-11-18',
  '2015-11-19',
  '2015-11-20',
  '2015-11-21',
  '2015-11-22',
  '2015-11-23',
  '2015-11-24',
  '2015-11-25',
  '2015-11-26',
  '2015-11-28',
  '2015-11-29',
  '2015-11-30',
  '2015-12-01',
  '2015-12-02',
  '2015-12-03',
  '2015-12-04',
  '2015-12-05',
  '2015-12-06',
  '2015-12-07',
  '2015-12-08',
  '2015-12-09',
  '2015-12-10',
  '2015-12-11',
  '2015-12-12',
  '2015-12-13',
  '2015-12-14',
  '2015-12-15',
  '2015-12-17',
  '2015-12-19',
  '2015-12-20',
  '2015-12-21',
  '2015-12-22',
  '2015-12-23',
  '2015-12-24',
  '2015-12-25',
  '2015-12-26',
  '2015-12-27',
  '2015-12-28',
  '2015-12-29',
  '2015-12-30',
  '2015-12-31'])

In [7]:
stock_ids = [i for i in range(len(stock_names))]
stock_name_to_ids = dict(zip(stock_names, stock_ids))
stock_name_to_ids

{'AAPL': 0,
 'ABB': 1,
 'ABBV': 2,
 'AEP': 3,
 'AGFS': 4,
 'AMGN': 5,
 'AMZN': 6,
 'BA': 7,
 'BABA': 8,
 'BAC': 9,
 'BBL': 10,
 'BCH': 11,
 'BHP': 12,
 'BP': 13,
 'BRK-A': 14,
 'BSAC': 15,
 'BUD': 16,
 'C': 17,
 'CAT': 18,
 'CELG': 19,
 'CHL': 20,
 'CHTR': 21,
 'CMCSA': 22,
 'CODI': 23,
 'CSCO': 24,
 'CVX': 25,
 'D': 26,
 'DHR': 27,
 'DIS': 28,
 'DUK': 29,
 'EXC': 30,
 'FB': 31,
 'GD': 32,
 'GE': 33,
 'GOOG': 34,
 'HD': 35,
 'HON': 36,
 'HRG': 37,
 'HSBC': 38,
 'IEP': 39,
 'INTC': 40,
 'JNJ': 41,
 'JPM': 42,
 'KO': 43,
 'LMT': 44,
 'MA': 45,
 'MCD': 46,
 'MDT': 47,
 'MMM': 48,
 'MO': 49,
 'MRK': 50,
 'MSFT': 51,
 'NEE': 52,
 'NGG': 53,
 'NVS': 54,
 'ORCL': 55,
 'PCG': 56,
 'PCLN': 57,
 'PEP': 58,
 'PFE': 59,
 'PG': 60,
 'PICO': 61,
 'PM': 62,
 'PPL': 63,
 'PTR': 64,
 'RDS-B': 65,
 'REX': 66,
 'SLB': 67,
 'SNP': 68,
 'SNY': 69,
 'SO': 70,
 'SPLP': 71,
 'SRE': 72,
 'T': 73,
 'TM': 74,
 'TOT': 75,
 'TSM': 76,
 'UL': 77,
 'UN': 78,
 'UNH': 79,
 'UPS': 80,
 'UTX': 81,
 'V': 82,
 'VZ': 83,
 'WFC': 84,
 'WMT': 85,
 'XOM': 86}

In [ ]:
tokens_file = dataset_dir / "all_tweets_tokenized.jsonl"
bad_data_file = dataset_dir / "bad_data.jsonl"

buffer = []
buffer_size = 100_000
lines = 0


with open(json_file, "r", encoding="utf-8") as f, open(tokens_file, "w", encoding="utf-8") as o, open(bad_data_file, "w", encoding="utf-8") as b:
    for line in f:

        entry = json.loads(line)

        stock_name = entry["stock"]
        tweet = entry["tweet"]
        date = entry["date"]


        patterns = [
            rf"\${stock_name}(?=\s|$|\W)", # strict match
            rf"\${stock_name}" # loose match
        ]

        success = False
        for pattern in patterns:
            masked_tweet = re.sub(pattern, "<MASK>", tweet, flags=re.IGNORECASE)
            masked_tweet_tokenized = slot_spm.encode(masked_tweet)

            if mask_id in masked_tweet_tokenized:
                mask_idx = masked_tweet_tokenized.index(mask_id)
                success = True
                break

        if not success:
            bad_entry = {
                "stock": stock_name,
                "tweet": slot_spm.decode(masked_tweet_tokenized)
            }
            b.write(json.dumps(bad_entry) + "\n")
            continue

        # masked_tweet_tokenized = [
        #     tok if tok not in rare_tokens else unk_id
        #     for tok in masked_tweet_tokenized
        # ]


        tokenized_tweet = {
            "date": date,
            "tweet": masked_tweet_tokenized,
            "stock_id": stock_name_to_ids[stock_name],
            "mask_idx": mask_idx
        }


        buffer.append(json.dumps(tokenized_tweet))

        if len(buffer) >= buffer_size:
            o.write("\n".join(buffer) + "\n")
            lines += len(buffer)
            buffer.clear()

            print(f"{lines} lines written")

    if buffer:
        o.write("\n".join(buffer) + "\n")
        lines += len(buffer)
        print(f"{lines} lines written")

100000 lines written
119768 lines written

### Put all the data into lists

In [8]:

tweet_tokens_by_date = [[] for i in range(num_dates)]
mask_indices_by_date = [[] for i in range(num_dates)]


tweet_tokens = []
mask_indices = []
y = []

with open(tokens_file, "r") as f:
    for line in f:
        entry = json.loads(line)

        tokens = [int(tok) for tok in entry["tweet"]]
        idx = entry["mask_idx"]

        tweet_tokens.append(tokens)
        mask_indices.append(idx)
        y.append(entry["stock_id"])

        if entry["date"] in all_dates:
            date = all_dates.index(entry["date"])
            tweet_tokens_by_date[date].append(tokens)
            mask_indices_by_date[date].append(idx)

In [9]:
for i in range(5):
    print(all_dates[i] + ":", tweet_tokens_by_date[i])
    print(all_dates[i] + ":", mask_indices_by_date[i])
    print()

2014-02-19: [[18, 7, 14, 12, 10, 13, 9, 183, 49, 300, 35, 7, 3, 16, 6, 2101, 1470, 1464, 17, 257, 35, 397, 11, 1745, 48, 1800, 11, 5043, 53, 26, 2242, 2118, 1184, 368, 57, 7789, 414, 16, 1384, 820, 8], [7, 3, 35, 233, 939, 426, 381, 95, 137, 3241, 58, 22, 60, 47, 11, 180, 15, 650, 3447, 238, 33, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [749, 37, 835, 79, 2801, 82, 7, 1887, 358, 200, 876, 6, 6241, 6, 4321, 6, 29, 7, 3, 9, 431, 8], [7, 3, 276, 88, 250, 22, 401, 1920, 93, 3295, 20, 5283], [18, 7, 14, 12, 10, 13, 1072, 196, 8150, 3233, 40, 82, 157, 1725, 27, 6, 1362, 17, 6, 254, 7, 3, 9, 4634, 9, 120, 7187, 9, 5414, 9, 1525, 1228, 122, 8], [18, 7, 14, 12, 10, 13, 1072, 196, 8150, 3233, 40, 82, 157, 1725, 27, 6, 1362, 17, 6, 254, 7, 3, 9, 4634, 9, 120, 7187, 9, 5414, 9, 1525, 1228, 122, 8], [8, 367, 228, 3128, 2779, 28, 27, 60, 37, 4345, 1739, 16, 277, 256, 16, 363, 28, 23, 1242, 244, 33, 8, 6, 7476, 6, 131, 7, 3, 6, 55], [7, 3, 35, 825, 4663, 1356, 2323, 66, 798, 89, 447, 11], [18, 7, 14, 12, 10, 13, 1072, 196, 8150, 3233, 40, 82, 157, 1725, 27, 6, 1362, 17, 6, 254, 7, 3, 9, 4634, 9, 120, 7187, 9, 5414, 9, 1525, 1228, 122, 8], [9, 63, 597, 11, 335, 105, 184, 6, 755, 6, 4568, 6, 433, 7, 3, 9, 1028, 8], [7, 3, 221, 100, 7, 14, 12, 10, 13, 8, 7, 19, 11], [7, 3, 221, 100, 7, 14, 12, 10, 13, 8, 7, 19, 11], [18, 7, 14, 12, 10, 13, 4851, 967, 46, 1066, 6864, 7099, 57, 7, 15, 94, 15, 229, 8, 7, 3], [7, 3, 68, 334, 25, 82, 1753, 4140, 35, 8, 8], [7, 14, 12, 10, 13, 5278, 2573, 11, 354, 167, 22, 1719, 3088, 41, 7300, 7, 3, 1613, 455, 52, 1017, 34, 6456, 46, 252, 1647, 11, 394, 28, 222, 445, 330, 70, 238, 811, 15], [18, 7, 14, 12, 10, 13, 1072, 196, 8150, 3233, 40, 82, 157, 1725, 27, 6, 1362, 17, 6, 254, 7, 3, 9, 4634, 9, 120, 7187, 9, 5414, 9, 1525, 1228, 122, 8], [7, 3, 297, 35, 797, 150, 25, 906, 6242, 1892, 272, 901, 11, 506, 20, 151, 202, 5527, 797, 150, 1023, 8], [288, 28, 15, 82, 9, 1076, 2172, 460, 41, 1622, 765, 143, 15, 44, 945, 76, 40, 162, 236, 1313, 697, 1519, 44, 8, 6, 51, 6, 29, 7, 3], [7, 3, 1391, 20, 2721, 57, 4104, 3311, 304, 2015, 1248, 1859, 1749, 8], [1242, 242, 2974, 70, 5768, 1822, 20, 1162, 1263, 8, 6, 74, 6, 38, 1046, 15, 6, 1381, 7, 3], [193, 113, 45, 36, 111, 114, 264, 257, 154, 733, 26, 1729, 228, 6, 74, 413, 317, 356, 26, 7, 3, 4161, 69, 4478, 15, 114, 8], [709, 475, 16, 3114, 222, 125, 25, 11, 330, 842, 81, 91, 7298, 15, 3224, 2270, 179, 194, 34, 8, 49, 7, 3, 8], [7, 3, 221, 100, 2695, 2048, 1315, 16, 8, 1030, 666, 101, 697, 2126, 1471, 142, 81, 138, 16, 72, 265, 797, 150, 69, 28, 15, 359, 3330, 11], [8, 367, 228, 3128, 2779, 28, 27, 60, 37, 4345, 1739, 16, 277, 256, 16, 363, 28, 23, 1242, 244, 33, 8, 6, 7476, 7, 3, 6, 19, 6, 55], [7, 3, 11, 35, 5655, 674, 792, 4407, 34, 2585, 703, 8], [851, 1554, 711, 1164, 319, 1816, 705, 38, 2866, 57, 285, 34, 421, 17, 195, 1835, 176, 1613, 2000, 1475, 812, 7, 3, 8], [7, 3, 285, 34, 421, 173, 48, 67, 53, 90, 16, 202, 28, 15, 201, 27, 285, 34, 421, 39, 8], [7, 3, 287, 723, 737, 884, 43, 37, 994, 5206, 321, 737, 1230, 11, 1781, 200, 737, 1230, 11, 1296, 287, 737, 2164, 11, 316, 392, 737, 1230, 11, 1280, 360, 737, 1556, 1745, 1544, 8], [563, 1485, 517, 62, 408, 1799, 2486, 408, 26, 24, 3488, 161, 3, 2407, 17, 7, 5571, 498, 156, 43, 1380, 229, 743, 75, 17, 40, 1799, 238, 863, 619, 2029, 493, 354, 457, 1200, 129, 354, 871, 15, 17, 2116, 81, 1463, 145, 568, 146, 229, 17, 568, 2113, 39], [375, 2754, 3398, 3245, 193, 5965, 6062, 70, 83, 170, 2548, 2341, 15, 170, 1337, 15, 711, 255, 7, 3, 2105, 30, 2757, 8, 48, 1532, 165, 605, 170, 7, 14, 12, 10, 13], [7, 3, 730, 47, 11, 3924, 15, 61, 425, 27, 621, 2293, 408, 173, 11, 48, 4685, 53, 8], [639, 76, 71, 242, 160, 17, 1670, 222, 145, 2244, 1020, 999, 2215, 240, 239, 100, 278, 46, 105, 96, 426, 1540, 11, 7, 3, 8], [335, 24, 201, 7, 3, 6, 4562, 6, 142, 75, 6, 2332, 810, 8], [7, 3, 439, 11, 38, 11, 38, 11, 20, 379, 669, 26, 1093, 2141, 6107, 180, 8], [546, 28, 15, 123, 3109, 5283, 267, 137, 267, 17, 243, 41, 69, 25, 214, 39, 8, 7, 3, 9, 2702], [7, 3, 35, 41, 4394, 24, 320, 15, 516, 1069, 565, 39, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [196, 2010, 27, 7, 3, 8], [7, 3, 35, 546, 2100, 15, 3165, 3322, 2704, 15, 27, 685, 2673, 1012, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [6, 1750, 6, 83, 7, 3, 8], [5650, 16, 466, 8236, 57, 6, 1754, 8, 6, 102, 7, 3, 6, 526], [1000, 41, 185, 342, 15, 7, 2826, 492, 7, 39, 15, 73, 3682, 919, 39, 3], [1313, 3338, 73, 556, 44, 9, 289, 3338, 1417, 418, 2834, 9, 54, 11, 54, 11, 54, 9, 3, 9, 258, 1105, 9, 153, 4195, 52, 9, 3915, 304, 2809, 8], [162, 89, 391, 26, 7, 3, 6, 4025, 6, 1100, 6, 895, 251, 8], [639, 46, 156, 1191, 26, 6, 1484, 23, 6, 1690, 6, 259, 7, 3, 68, 1036, 8], [9, 42, 20, 214, 6, 5499, 6, 4464, 6, 1653, 7, 3, 9, 1003, 8], [60, 1657, 7, 15, 94, 15, 229, 4851, 6864, 7099, 7, 3, 9, 661, 8], [7, 3, 3407, 24, 3275, 26, 72, 265, 106, 59, 11], [327, 447, 1057, 26, 7, 3, 143, 88, 3959, 69, 257, 11, 4708, 337, 11], [7, 14, 12, 10, 13, 7, 14, 12, 10, 13, 1808, 17, 7, 3, 447, 1353, 27, 2965, 2420, 11, 1000, 41, 6, 51, 2826, 143, 50, 991, 394, 107, 92, 447, 146, 15, 330, 70, 400, 568], [104, 14, 12, 10, 13, 104, 14, 12, 10, 13, 110, 7, 3, 22, 1739, 5738, 71, 1353, 130, 65, 326, 1245, 3677, 160, 1691, 39, 3682, 65, 326, 1245, 601, 363, 28, 23, 3928, 213, 27, 7, 1564, 69, 6324], [18, 7, 14, 12, 10, 13, 7, 3, 20, 1235, 1353, 27, 240, 2965, 291], [18, 7, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [18, 7, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [7, 3, 257, 132, 40, 373, 3453, 11], [18, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [18, 7, 14, 12, 10, 13, 2524, 25, 38, 5644, 170, 7, 3, 9, 661, 6977, 85, 35, 258, 859, 5353, 3399, 212, 3215, 2111, 566, 290, 4249, 1079, 25, 354, 1151, 170, 1353, 966, 2965, 43, 48, 3538, 384, 25, 38, 5644, 53, 33], [18, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [110, 447, 1353, 27, 2965, 4463, 7, 3, 8], [3877, 145, 406, 406, 7, 14, 12, 10, 13, 746, 16, 110, 20, 61, 1353, 27, 240, 2965, 291, 568, 40, 49, 7, 3, 476], [18, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3, 1685, 229, 2299, 17, 1471, 4013, 2783, 1076, 605, 15, 651, 307, 3203, 4533, 15, 170, 1353, 11], [1031, 18, 16, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [18, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [68, 363, 28, 23, 151, 209, 7, 3, 210, 6597, 91, 1353, 3008, 11, 11, 480, 2932, 3450, 1733, 17, 243, 202, 487, 39, 68, 4662, 69, 210, 92, 393, 2078, 58, 11, 11, 480, 5192, 7, 1570, 4618, 11], [18, 7, 14, 12, 10, 13, 3877, 5324, 2299, 44, 389, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [18, 7, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 7, 3, 521, 15, 2965, 43, 27, 367, 1230, 15, 1679, 23, 1568, 202, 28, 15, 5640, 11, 1710, 36, 202, 39, 2492, 11, 110, 521, 15, 2965, 43, 27, 367, 733, 215, 1353, 11], [8024, 93, 7, 3, 3044, 748, 291, 39, 11, 33, 2436, 50, 105, 34, 186, 5296, 3422], [18, 7, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 5422, 7, 3, 49, 3093, 245, 1633, 11, 1394, 41, 1174, 1797, 11, 224, 1837, 328, 1059, 694, 4276, 2080, 165, 301, 3166], [18, 7, 14, 12, 10, 13, 110, 1535, 1739, 5738, 71, 1353, 17, 66, 61, 27, 6, 174, 43, 22, 568, 1414, 1964, 43, 22, 110, 194, 7, 3, 6, 31], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 7, 3, 6295, 15, 3125, 26, 90, 141, 110, 66, 61, 1353, 4060, 1152, 46, 685, 8, 8], [1198, 17, 350, 4577, 17, 938, 28, 15, 193, 1833, 11, 141, 1959, 1392, 28, 23, 538, 447, 76, 7, 3, 49], [18, 7, 14, 12, 10, 13, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 739, 16, 8, 7, 3], [18, 7, 14, 12, 10, 13, 389, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3, 476, 492, 7, 3934, 44], [18, 7, 14, 12, 10, 13, 90, 240, 1353, 6, 908, 291, 1632, 2055, 110, 194, 257, 3125, 22, 245, 37, 4133, 196, 11, 8, 7, 3], [746, 16, 7, 14, 12, 10, 13, 20, 1235, 7, 14, 12, 10, 13, 27, 240, 2965, 291, 11, 541, 7, 3], [18, 7, 14, 12, 10, 13, 194, 34, 110, 1218, 233, 3590, 20, 6, 2624, 11, 1204, 22, 245, 37, 4133, 196, 245, 90, 34, 1353, 383, 11, 8, 7, 3], [1377, 2660, 41, 209, 24, 1353, 1929, 264, 4295, 57, 7, 3, 7, 11], [18, 7, 14, 12, 10, 13, 18, 7, 14, 12, 10, 13, 71, 2154, 34, 1353, 17, 7, 3, 8031, 58, 97, 1304, 34, 24, 771, 4060, 1152, 46, 88, 48, 4249, 590, 30, 46, 20, 72, 221, 53, 8], [2682, 20, 159, 693, 44, 7, 3, 6, 64, 6, 226, 6, 203, 6, 42], [110, 47, 7, 16, 7, 3253, 3230, 1865, 41, 3551, 142, 1330, 2660, 58, 27, 7, 2402, 1633, 22, 627, 423, 5407, 590, 28, 15, 1701, 8, 7, 3], [18, 7, 14, 12, 10, 13, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 739, 16, 8, 7, 3], [18, 7, 14, 12, 10, 13, 746, 16, 110, 28, 15, 5905, 2965, 291, 1353, 2154, 16, 1964, 43, 22, 7, 3, 194, 17, 6, 174, 43, 22, 568, 11, 8], [18, 7, 14, 12, 10, 13, 110, 49, 4494, 26, 90, 34, 1353, 383, 33, 7, 3, 8, 8], [18, 7, 14, 12, 10, 13, 110, 41, 447, 480, 3484, 522, 1353, 27, 2965, 291, 7, 3, 8, 100, 7, 14, 12, 10, 13], [18, 7, 14, 12, 10, 13, 110, 49, 4494, 26, 90, 34, 1353, 383, 33, 7, 3, 8, 8], [18, 7, 14, 12, 10, 13, 110, 447, 1353, 27, 2965, 43, 8, 7, 3], [1838, 3935, 2491, 9917, 2583, 608, 572, 3073, 2970, 1838, 1495, 2490, 9917, 2556, 2971, 8567, 7, 1462, 458, 2491, 470, 3073, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [18, 7, 14, 12, 10, 13, 746, 16, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 541, 7, 3], [9, 661, 7, 3, 1837, 9, 6059, 27, 6, 908, 43], [18, 7, 14, 12, 10, 13, 110, 49, 4494, 26, 90, 34, 1353, 383, 33, 7, 3, 8, 8], [3541, 57, 7, 14, 12, 10, 13, 2110, 39, 2327, 339, 2116, 323, 1353, 132, 698, 962, 7, 3, 9, 6059, 9, 4356, 5497], [7, 2592, 18, 7, 14, 12, 10, 13, 110, 20, 1235, 1353, 27, 240, 2965, 291, 11, 739, 16, 8, 7, 3], [18, 7, 14, 12, 10, 13, 18, 7, 14, 12, 10, 13, 110, 48, 3, 53, 5037, 1353, 27, 89, 301, 486, 28, 15, 814, 64, 53, 88, 361, 57, 241, 729, 169, 11], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [7, 14, 12, 10, 13, 1235, 15, 7, 14, 12, 10, 13, 27, 2965, 291, 8, 7, 3], [820, 3697, 170, 423, 2782, 7, 774, 3215, 25, 2061, 7, 3, 796, 3667, 1792, 255, 355, 1030, 3216, 1402], [18, 7, 14, 12, 10, 13, 110, 28, 15, 1219, 2154, 169, 27, 3968, 37, 1453, 1178, 1353, 16, 6, 908, 291, 11, 141, 28, 15, 456, 6, 163, 1295, 462, 592, 3856, 11, 7, 3], [18, 7, 14, 12, 10, 13, 90, 240, 1353, 6, 908, 291, 1632, 2055, 110, 194, 257, 3125, 22, 245, 37, 4133, 196, 11, 8, 7, 3], [18, 7, 14, 12, 10, 13, 90, 240, 1353, 6, 908, 291, 1632, 2055, 110, 194, 257, 3125, 22, 245, 37, 4133, 196, 11, 8, 7, 3], [236, 260, 26, 6, 3521, 7, 3, 6, 30, 62, 6, 897, 388, 95, 8], [645, 689, 215, 7, 16, 821, 683, 176, 68, 1012, 20, 4849, 6, 316, 2305, 462, 22, 3513, 17, 1019, 8, 7, 3], [749, 37, 835, 79, 2801, 82, 7, 1887, 358, 200, 876, 6, 6241, 6, 4321, 7, 3, 6, 19, 9, 431, 8], [40, 631, 1816, 7, 3, 705, 127, 2709, 33], [7, 3, 121, 714, 3663, 15, 6, 2539, 462, 40, 4367, 15, 323, 2640, 7, 3324, 16, 121, 714, 3663, 15, 6, 2539, 462, 40, 108, 33, 8], [286, 27, 24, 201, 1081, 165, 150, 6, 80, 6, 6751, 6, 1690, 7, 3, 313, 117, 8], [22, 24, 7, 3, 648, 717, 435, 396, 27, 132, 11, 1204], [18, 7, 14, 12, 10, 13, 121, 396, 7, 5350, 3124, 37, 4215, 518, 367, 28, 5661, 4083, 15, 11, 28, 28, 789, 17, 1463, 145, 44, 369, 9, 1883, 229, 27, 7, 14, 12, 10, 13, 7, 3, 7730, 8], [1096, 125, 3076, 7347, 141, 78, 4958, 30, 20, 2742, 5882, 812, 34, 121, 5629, 16, 7, 15, 11, 280, 11, 17, 5633, 6439, 17, 5015, 313, 17, 683, 6143, 1761, 40, 8159, 7, 432, 3661, 11, 7, 3], [288, 28, 15, 82, 9, 1076, 2172, 460, 41, 1622, 765, 143, 15, 44, 945, 76, 40, 162, 236, 1313, 697, 1519, 44, 8, 6, 51, 7, 3, 6, 19], [286, 20, 1682, 2983, 150, 6, 3051, 7, 3, 6, 142, 30, 1099, 6, 543, 9, 936, 8], [7, 3, 35, 230, 16, 2125, 248, 2899, 15, 116, 2343, 1024, 141, 619, 46, 1243, 4492, 7, 3544, 697, 2047, 54, 2505, 1697, 33, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [196, 2010, 27, 7, 3, 8], [7, 3, 35, 464, 16, 1000, 180, 15, 1096, 125, 8207, 39, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 35, 303, 7, 1973, 1590, 16, 530, 65, 45, 36, 530, 378, 11, 355, 138, 6944, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 202, 7313, 15, 26, 604, 573, 1763, 27, 426, 8], [162, 89, 391, 26, 7, 3, 6, 4967, 6, 38, 52, 438, 6, 2384, 313, 117, 8], [7, 3, 1246, 2408, 93, 621, 11, 52, 11, 767, 2401, 22, 7, 2570, 7, 2572, 8], [7, 3, 836, 37, 942, 5077, 6136, 5264, 7512, 2529, 7, 3136, 1256, 2622, 174, 1384, 194, 48, 5540, 53, 8], [7, 3, 35, 1867, 1908, 474, 1595, 22, 25, 2577, 1561, 71, 4006, 4540, 238, 33, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 1867, 1908, 4799, 68, 43, 38, 37, 791, 662, 6234, 46, 1598, 3164, 46, 2373, 27, 59, 8], [7, 14, 12, 10, 13, 217, 1013, 17, 243, 69, 264, 7, 3, 367, 15, 727, 616, 23, 33], [7, 3, 2333, 1361, 27, 640, 62, 408, 3435, 732, 28, 15, 968, 8], [7, 3, 1538, 111, 1243, 697, 3600, 2174, 319, 20, 2100, 1052, 1611, 3942, 7810, 1424, 160, 59, 8], [7, 3, 3405, 3924, 15, 104, 929, 130, 425, 27, 1171, 65, 45, 36, 146, 48, 204, 53, 8], [7, 3, 202, 60, 210, 1357, 93, 288, 40, 121, 8], [7, 14, 12, 10, 13, 7, 14, 12, 10, 13, 1808, 17, 6, 21, 447, 1353, 27, 2965, 2420, 11, 1000, 41, 7, 3, 2826, 143, 50, 991, 394, 107, 92, 447, 146, 15, 330, 70, 400, 568], [288, 28, 15, 82, 9, 1076, 2172, 460, 41, 1622, 765, 143, 15, 44, 945, 76, 40, 162, 236, 1313, 697, 1519, 44, 8, 7, 3, 6, 29, 6, 19], [2240, 17, 7, 2745, 1090, 394, 28, 222, 4024, 5823, 1996, 46, 218, 1519, 15, 34, 244, 851, 182, 7, 5019, 1042, 7, 3, 6, 2745], [7, 3, 35, 5810, 7582, 6629, 15, 1569, 462, 20, 724, 953, 1577, 5717, 22, 2988, 698, 40, 33, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [286, 27, 24, 201, 1081, 165, 150, 7, 3, 6, 6751, 6, 1690, 6, 29, 313, 117, 8], [7, 3, 239, 3428, 1613, 7652, 176, 169, 37, 6980, 46, 6042, 1255, 5547, 15, 17, 2421, 15, 8], [898, 79, 20, 159, 6, 2961, 6, 4579, 6, 175, 83, 7, 3, 9, 1011, 148, 8], [18, 7, 14, 12, 10, 13, 247, 91, 6521, 20, 392, 26, 6047, 6883, 15, 27, 7, 1554, 86, 493, 7, 7148, 3088, 8, 9, 4292, 9, 7148, 7, 3], [7, 3, 161, 23, 65, 45, 36, 24, 6016, 3328, 37, 2016, 8], [185, 79, 20, 159, 7, 3, 6, 4614, 6, 5620, 6, 4328, 9, 99, 8], [7, 3, 82, 57, 113, 45, 36, 23, 20, 617, 493, 3914, 5521, 468, 2332, 4307, 27, 2431, 71, 972, 3807, 26, 265, 3060, 8], [807, 2485, 2106, 7, 1238, 272, 3704, 2833, 138, 4796, 7914, 247, 821, 20, 145, 653, 23, 2339, 91, 557, 406, 2485, 757, 25, 125, 7, 30, 6690, 3, 807, 2485, 3006, 7, 1252, 3258, 497, 1195, 5546, 621, 238, 7, 101, 1135, 525, 1041, 4653, 673, 4834, 2754, 7914, 83, 4231, 83, 2485, 757], [18, 7, 14, 12, 10, 13, 7, 14, 12, 10, 13, 7, 14, 12, 10, 13, 1679, 846, 307, 4861, 438, 839, 468, 3720, 3720, 3, 919, 120], [7, 3, 49, 723, 737, 884, 43, 37, 994, 5206, 321, 737, 163, 8210, 200, 737, 163, 8210, 287, 737, 1966, 5311, 392, 737, 1966, 5480, 360, 6329, 1190, 1105, 2709, 8], [7, 3, 463, 28, 15, 299, 35, 296, 2897, 173, 48, 4971, 634, 5020, 8159, 830, 165, 2842, 3010, 743, 59, 8], [7, 3, 35, 202, 180, 15, 201, 27, 5655, 674, 792, 39, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 76, 15, 4953, 15, 497, 1551, 390, 41, 2026, 5306, 15, 27, 1241, 698, 34, 2669, 3440, 8], [2264, 3542, 65, 45, 36, 6429, 23, 3568, 17, 8267, 125, 5993, 40, 992, 1430, 5977, 1307, 23, 1436, 23, 15, 59, 7, 3, 8], [7, 3, 1293, 79, 16, 945, 1062, 3258, 4996, 518, 513, 11, 17, 2833, 1427, 617, 215, 17, 2930, 513, 17, 40, 59, 8], [7, 3, 9, 4904, 1468, 1024, 2841, 34, 3615, 194, 1137, 20, 92, 3919, 20, 9, 1985, 83, 73, 1076, 1824, 8], [7, 3, 807, 3965, 37, 540, 336, 7, 2989, 3241, 46, 28, 57, 696, 34, 6031, 5044, 1902], [7, 3, 7, 7842, 857, 2022, 3891, 493, 39, 3830, 1107, 20, 337, 17, 602, 37, 540, 8], [5650, 16, 466, 8236, 57, 6, 1754, 8, 7, 3, 6, 139, 6, 526]]
2014-02-19: [12, 1, 18, 1, 21, 21, 27, 1, 21, 14, 1, 1, 20, 1, 16, 21, 1, 29, 1, 19, 20, 22, 1, 25, 1, 22, 1, 1, 12, 19, 1, 24, 4, 1, 18, 1, 4, 1, 5, 11, 15, 18, 5, 13, 11, 11, 1, 5, 13, 12, 7, 17, 17, 1, 19, 12, 19, 7, 23, 19, 21, 19, 7, 26, 17, 35, 7, 3, 17, 35, 35, 8, 28, 35, 35, 7, 20, 19, 24, 26, 21, 30, 11, 18, 6, 28, 19, 21, 16, 17, 16, 14, 35, 19, 3, 16, 18, 21, 14, 35, 17, 11, 35, 26, 26, 6, 22, 16, 4, 1, 14, 3, 38, 38, 27, 8, 1, 4, 1, 1, 1, 5, 1, 1, 1, 1, 12, 1, 1, 1, 1, 23, 25, 23, 1, 8, 1, 12, 29, 1, 5, 1, 28, 25, 1, 1, 1, 1, 23, 1, 1, 1, 1, 9]


### Pad the token data and shuffle

In [10]:
max_len = max(len(tweet) for tweet in tweet_tokens)


X = [tweet + [pad_id] * (max_len - len(tweet))
    for tweet in tweet_tokens]


X = torch.tensor(X, dtype=torch.long)
y = torch.tensor(y, dtype=torch.long)
mask_indices = torch.tensor(mask_indices, dtype=torch.long)

perm = torch.randperm(X.size(0))
X, y, mask_indices = X[perm], y[perm], mask_indices[perm]

X, X.shape, y, y.shape, mask_indices, mask_indices.shape

(tensor([[  25, 1091, 1369,  ...,    4,    4,    4],
         [  18,    7,   14,  ...,    4,    4,    4],
         [  18,    7,   14,  ...,    4,    4,    4],
         ...,
         [  78,   50,    7,  ...,    4,    4,    4],
         [ 184,  121,   41,  ...,    4,    4,    4],
         [   6, 1330,   49,  ...,    4,    4,    4]]),
 torch.Size([119768, 147]),
 tensor([ 8, 59, 73,  ..., 26,  0, 18]),
 torch.Size([119768]),
 tensor([24, 20, 10,  ...,  7, 14, 20]),
 torch.Size([119768]))

In [11]:
# (num_dates, num_tweets_for_that_date, seq_len)
X_by_date = [
    torch.tensor(
        [tweet + [pad_id] * (max_len - len(tweet)) for tweet in tweet_tokens_by_date[d]],
        dtype=torch.long
    )
    for d in range(num_dates)
]

mask_indices_by_date = [
    torch.tensor(mask_indices_by_date[d], dtype=torch.long)
    for d in range(num_dates)
]

X_by_date[0], X_by_date[0].shape, mask_indices_by_date[0], mask_indices_by_date[0].shape

(tensor([[  18,    7,   14,  ...,    4,    4,    4],
         [   7,    3,   35,  ...,    4,    4,    4],
         [ 749,   37,  835,  ...,    4,    4,    4],
         ...,
         [   7,    3,  807,  ...,    4,    4,    4],
         [   7,    3,    7,  ...,    4,    4,    4],
         [5650,   16,  466,  ...,    4,    4,    4]]),
 torch.Size([154, 147]),
 tensor([12,  1, 18,  1, 21, 21, 27,  1, 21, 14,  1,  1, 20,  1, 16, 21,  1, 29,
          1, 19, 20, 22,  1, 25,  1, 22,  1,  1, 12, 19,  1, 24,  4,  1, 18,  1,
          4,  1,  5, 11, 15, 18,  5, 13, 11, 11,  1,  5, 13, 12,  7, 17, 17,  1,
         19, 12, 19,  7, 23, 19, 21, 19,  7, 26, 17, 35,  7,  3, 17, 35, 35,  8,
         28, 35, 35,  7, 20, 19, 24, 26, 21, 30, 11, 18,  6, 28, 19, 21, 16, 17,
         16, 14, 35, 19,  3, 16, 18, 21, 14, 35, 17, 11, 35, 26, 26,  6, 22, 16,
          4,  1, 14,  3, 38, 38, 27,  8,  1,  4,  1,  1,  1,  5,  1,  1,  1,  1,
         12,  1,  1,  1,  1, 23, 25, 23,  1,  8,  1, 12, 29,  1,  5,  1, 28, 25,
          1,  1,  1,  1, 23,  1,  1,  1,  1,  9]),
 torch.Size([154]))

### Train/val/test split

In [13]:
data_len = len(y)

train_end = int(data_len * 0.90)
val_end = int(data_len * 1.00)

X_train, y_train, mask_train = X[ : train_end], y[ : train_end], mask_indices[ : train_end]
X_val, y_val, mask_val = X[train_end : val_end], y[train_end : val_end], mask_indices[train_end : val_end]
# X_test, y_test, mask_test = X[val_end : ], y[val_end : ], mask_indices[val_end : ]

print(f"X_train shape: {X_train.shape}. y_train shape: {y_train.shape}")
print(f"X_val shape: {X_val.shape}. y_val shape: {y_val.shape}")
# print(f"X_test shape: {X_test.shape}. y_test shape: {y_test.shape}")

mask_train.shape, mask_val.shape #, mask_test.shape

X_train shape: torch.Size([107791, 147]). y_train shape: torch.Size([107791])
X_val shape: torch.Size([11977, 147]). y_val shape: torch.Size([11977])

(torch.Size([107791]), torch.Size([11977]))

### Datasets

In [ ]:
class SLOTTokensDataset(Dataset):
    def __init__(self, x, y, mask_idx):
        self.x = x
        self.y = y
        self.mask_idx = mask_idx

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx], self.mask_idx[idx]

In [ ]:
train_dataset = SLOTTokensDataset(X_train, y_train, mask_train)
val_dataset = SLOTTokensDataset(X_val, y_val, mask_val)
# test_dataset = SLOTTokensDataset(X_test, y_test, mask_test)

train_dataset[0]

(tensor([  25, 1091, 1369,   68,   28,   54,  883, 4367,   15,   26,   37,    6,
           64,   17,    6, 1164,   17,    6, 4474,   17,    6, 4895,   17,    7,
            3,   17,    6, 2241,   11,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4]),
 tensor(8),
 tensor(24))

In [ ]:
train_size = int(0.5 * len(train_dataset))
val_size = int(0.5 * len(val_dataset))


train_subset, _ = random_split(train_dataset, [train_size, len(train_dataset) - train_size])
val_subset, _ = random_split(val_dataset, [val_size, len(val_dataset) - val_size])

len(train_subset), len(val_subset)

(53895, 5988)

### Model Definition

In [14]:

class StockIdentification(nn.Module):
    def __init__(self, num_stocks, embd_size, hidden_size, vocab_size, dropout, temp):
        super().__init__()
        self.H = hidden_size
        self.temp = temp


        self.stock_embd = nn.Embedding(num_embeddings=num_stocks, embedding_dim=2*hidden_size)


        self.token_embd = nn.Embedding(num_embeddings=vocab_size,
                                       embedding_dim=embd_size,
                                       padding_idx=pad_id)


        self.bi_lstm = nn.LSTM(
            input_size=embd_size,
            hidden_size=hidden_size,
            bidirectional=True,
            batch_first=True,
        )

        self.dropout = nn.Dropout(dropout)

        self.init_weights()

    def init_weights(self):
        nn.init.normal_(self.token_embd.weight, mean=0.0, std=0.01)
        nn.init.normal_(self.stock_embd.weight, mean=0.0, std=0.01)

        for name, param in self.bi_lstm.named_parameters():
            if "bias" in name:
                nn.init.zeros_(param)
                # set forget gate bias to 1
                # [i, f, g, o]
                param.data[self.H : 2*self.H].fill_(1.0)
            elif "weight_ih" in name:
                nn.init.kaiming_normal_(param)
            elif "weight_hh" in name:
                nn.init.orthogonal_(param)


    def forward(self, x, mask_indices):
        # x: (B, T)
        # mask_indices: (B,). The index of the <MASK> token for each tweet
        batch_size = x.size(0)
        token_embs = self.token_embd(x) # (B, T, embd_size)
        token_embs = self.dropout(token_embs)

        seq_lengths = (x != pad_id).sum(dim=-1).to("cpu")
        packed_token_embs = pack_padded_sequence(token_embs, seq_lengths, batch_first=True, enforce_sorted=False)

        # output: (B, T, 2*hidden_size)
        # h_n, c_n : (2*num_layers, B, hidden_size)
        output, (h_n, c_n) = self.bi_lstm(packed_token_embs)

        output, _ = pad_packed_sequence(output, batch_first=True)

        output = self.dropout(output)

        h_e = output[torch.arange(batch_size), mask_indices] # (B, 2*hidden_size)

        h_s = self.stock_embd.weight # (num_stocks, 2*hidden_size)
        h_e = F.normalize(h_e, dim=-1)
        h_s = F.normalize(h_s, dim=-1)
        logits = torch.matmul(h_e, h_s.T) #  (B, 2*hidden_size) @ (2*hidden_size, num_stocks) -> (B, num_stocks)


        return logits / self.temp, h_e, h_s

### Evaluation Functions

In [15]:
stock_id_to_name = {v: k for k, v in stock_name_to_ids.items()}

stock_queries = ["AAPL", "FB", "BA", "BAC"]
stock_query_ids = [stock_name_to_ids[name] for name in stock_queries]

In [16]:
tweet_files_stocks = [tweet.parent.name for tweet in tweet_files_list]
stock_counts = Counter(tweet_files_stocks)

stock_counts = torch.tensor([value for value in stock_counts.values()], dtype=torch.long)
stock_counts = stock_counts.to(device)

N = stock_counts.sum()
inv_freq = N / stock_counts
weights = torch.log1p(inv_freq)
weights = weights / weights.mean()
weights

tensor([0.7389, 1.1751, 0.8591, 1.0505, 1.6898, 0.8491, 0.7453, 0.8261, 0.8199,
        0.7714, 1.1916, 1.5983, 0.9514, 0.8787, 1.5644, 1.4985, 1.0618, 0.7638,
        0.8325, 0.8124, 1.0836, 1.0068, 0.8787, 1.3758, 0.7979, 0.8165, 0.7540,
        1.0836, 0.7962, 1.0179, 1.0078, 0.7399, 0.9836, 0.7882, 0.7432, 0.8452,
        1.0039, 1.3697, 1.1417, 1.1992, 0.7800, 0.8052, 0.7840, 0.8095, 0.9309,
        0.8662, 0.8055, 0.9605, 0.8977, 0.8954, 0.8371, 0.7546, 1.0296, 1.3420,
        0.9793, 0.8752, 1.0618, 0.7815, 0.9069, 0.8172, 0.8577, 1.4402, 0.9898,
        1.0697, 1.2761, 1.8615, 1.1966, 0.9198, 1.3884, 1.0158, 0.9810, 1.6389,
        1.1436, 0.7422, 1.0554, 1.0822, 1.1065, 1.2124, 1.1684, 0.8866, 0.9567,
        0.9256, 0.8063, 0.8199, 0.8289, 0.8055, 0.7918], device='cuda:0')

In [17]:
def evaluate(logits, stock_labels):
    # stock_labels: (B,)
    loss = F.cross_entropy(logits, stock_labels, weight=weights)

    stock_pred = torch.argmax(logits, dim=-1) # (B,)
    acc = (stock_pred == stock_labels).float().mean()

    return loss, acc

In [18]:
def stock_cosine_similarities(model):

    h_s = model.stock_embd.weight # (num_stocks, embd_size)

    h_s_normalized = h_s / h_s.norm(dim=1, keepdim=True)
    h_s_sim = h_s_normalized @ h_s_normalized.T # (num_stocks, embd_size) @ (embd_size, num_stocks) -> (num_stocks, num_stocks)

    # n = h_s_sim.size(0)
    h_s_sim.fill_diagonal_(float("-inf")) # h_s_sim[i][i] = -inf

    h_s_sim = h_s_sim[stock_query_ids] # (4, num_stocks)
    _, top3_indices = torch.topk(h_s_sim, k=3, dim=-1) # (4, 3)


    for query_idx, query in enumerate(stock_queries):
        print(f"\n{query}: ", end="")
        for neigh_idx in top3_indices[query_idx]:
            print(stock_id_to_name[int(neigh_idx.item())], end=", ")


def tweet_embedding_quality(model):

    tweet1 = "<MASK> iphone 6s spec leaks look good. excited. might even buy one." # $AAPL
    tweet2 = "rt AT_USER <MASK> $pep $dps $mnst traditional soft drinks in decline." # $KO

    eval_X = [slot_spm.encode(tweet1), slot_spm.encode(tweet2)]

    max_len = max(len(tweet) for tweet in eval_X)

    eval_X = [tweet + [pad_id] * (max_len - len(tweet)) for tweet in eval_X]

    eval_mask_indices = torch.tensor([eval_X[0].index(mask_id), eval_X[1].index(mask_id)])
    eval_X = torch.tensor(eval_X, dtype=torch.long)

    eval_X, eval_mask_indices = eval_X.to(device), eval_mask_indices.to(device)
    eval_logits, _, _ = model(eval_X, eval_mask_indices)

    eval_preds = F.softmax(eval_logits, dim=-1)
    _, eval_top3_indices = torch.topk(eval_preds, k=3, dim=-1)

    for i, stock in enumerate(eval_top3_indices):
        print()
        for pred in stock:
            print(f"{stock_id_to_name[pred.item()]}: {eval_preds[i][pred.item()].item():.2%}", end = " | ")

### Training Loop

In [ ]:

num_epochs = 50

def objective(trial):

    torch.manual_seed(42)
    torch.cuda.manual_seed(42)

    lr = 0.00248
    batch_size = 256
    embd_size = 128
    hidden_size = 254

    # lr = trial.suggest_float("lr", 1e-5, 1e-2, log=True)
    # batch_size = trial.suggest_categorical("batch_size", [64, 128, 256, 512])
    # embd_size = trial.suggest_categorical("embd_size", [64, 128, 256])
    # hidden_size =  trial.suggest_int("hidden_size", 32, 256)
    # dropout = trial.suggest_float("dropout", 0.0, 0.5)
    # temp = trial.suggest_float("temp", 0.1, 1.0)

    dropout = 0.439
    temp = 0.13356

    # dropout = 0.1
    # temp = 0.25

    wandb.init(
        project="stock_identification_final_test",
        name=f"trial_{trial.number}",
        config={
            "lr": lr,
            "batch_size": batch_size,
            "embd_size": embd_size,
            "hidden_size": hidden_size,
            "dropout": dropout,
            "temp": temp,
            "dataset": "ACL18"
        },
    )

    model = StockIdentification(
        num_stocks=num_stocks,
        embd_size=embd_size,
        hidden_size=hidden_size,
        vocab_size=vocab_size,
        dropout=dropout,
        temp=temp,
    )

    model = model.to(device)



    optimizer = torch.optim.AdamW(params = model.parameters(), lr=lr, weight_decay=1e-3)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(optimizer, T_0=10, T_mult=2, eta_min=1e-6)
    # scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer=optimizer, T_max=num_epochs, eta_min=1e-6)

    train_dataloader = DataLoader(train_subset, batch_size, shuffle=True)
    val_dataloader = DataLoader(val_subset, batch_size, shuffle=False)


    best_val_acc = 0.0

    for epoch in range(num_epochs):
        train_loss = 0.0
        train_acc = 0.0


        model.train()
        for i, (X, y, mask_indices) in enumerate(train_dataloader):
            X, y, mask_indices = X.to(device), y.to(device).to(torch.long), mask_indices.to(device)


            logits, _, _ = model(X, mask_indices) # (B, num_stocks)

            loss, acc = evaluate(logits, y)

            train_loss += loss.detach().item()
            train_acc += acc.item()


            optimizer.zero_grad()

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

            optimizer.step()

            # if i % 300 == 0:
                # print(f"Step: {i:04d} | Train loss: {loss:.4f} | Train acc: {100*acc:.2f}%")



        train_loss /= len(train_dataloader)
        train_acc /= len(train_dataloader)

        val_loss = 0.0
        val_acc = 0.0



        model.eval()
        with torch.inference_mode():
            for j, (X_val, y_val, mask_indices_val) in enumerate(val_dataloader):


                X_val, y_val, mask_indices_val = X_val.to(device), y_val.to(device), mask_indices_val.to(device)

                logits_val, _, _ = model(X_val, mask_indices_val)
                loss, acc = evaluate(logits_val, y_val)

                val_loss += loss.detach().item()
                val_acc += acc.item()

            val_loss /= len(val_dataloader)
            val_acc /= len(val_dataloader)

            best_val_acc = max(best_val_acc, val_acc)


        stock_cosine_similarities(model)
        tweet_embedding_quality(model)


        scheduler.step()

        print(f"\nEpoch: {epoch} | Train loss: {train_loss:.4f} | Train acc: {100*train_acc:.2f}% | Val loss: {val_loss:.4f} | Val acc: {100*val_acc:.2f}%")
        print(f"Learning rate: {optimizer.param_groups[0]['lr']:6f}")

        wandb.log({
            "train_loss": train_loss,
            "train_acc": train_acc,
            "val_loss": val_loss,
            "val_acc": val_acc,
            "best_val_acc": best_val_acc
        })

        trial.report(best_val_acc, step=epoch)
        if trial.should_prune():
            wandb.finish()
            raise optuna.TrialPruned()


        if epoch == 38:
            torch.save(model.state_dict(), dataset_dir / "best_model.pth")


    wandb.finish()
    return best_val_acc


study = optuna.create_study(direction="maximize", pruner=optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=5))
study.optimize(objective, n_trials = 1)

NameError: name 'optuna' is not defined

### Analyze Embedding Quality

In [20]:
# torch.save(model.state_dict(), dataset_dir / "best_model.pth")


# embd_size = 128
# hidden_size = 254
# dropout = 0.439
# temp = 0.13356

embd_size = 128
hidden_size = 64
dropout = 0.1
temp = 0.25


model = StockIdentification(
    num_stocks=num_stocks,
    embd_size=embd_size,
    hidden_size=hidden_size,
    vocab_size=vocab_size,
    dropout=dropout,
    temp=temp
).to(device)

model.load_state_dict(torch.load(dataset_dir / "best_model (1).pth", map_location=device))

In [21]:
torch.manual_seed(42)
torch.cuda.manual_seed(42)

stock_cosine_similarities(model)
print()
tweet_embedding_quality(model)

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, HON,
BAC: WFC, JPM, C,

AAPL: 31.37% | FB: 9.29% | GOOG: 6.47% |
KO: 7.64% | PEP: 4.92% | MCD: 3.15% |

## Stock Movement Prediction

### Global Trend with Attention

The global trend vector is generated by weighting the price features of stocks based on their popularity in tweets.

The average of all tweet embeddings at day $t$ ($g_t$) is used as the query vector.

The key vector is $h_s$, and the value vector is $x_{st}$.

$$
o_t = \sum_{s' \in S} \alpha_{st} x_{st}\;\; \text {where} \;\; \alpha_{st} = \frac{\exp(g_t^\top h_s)}{\sum_{s' \in S} \exp(g_t^\top h_{s'})}
$$

In [22]:
# g_t = torch.load(dataset_dir / "g_t.pt", map_location=device)
# all_tweet_embs = torch.load(dataset_dir / "all_tweet_embs", map_location=device)



all_tweet_embs = []

model.eval()
with torch.inference_mode():
    for d in tqdm(range(num_dates)):
        tweets = X_by_date[d].to(device)
        indices = mask_indices_by_date[d].to(device)

        _, h_e, _ = model(tweets, indices)
        all_tweet_embs.append(h_e)

g_t = torch.stack([torch.mean(h_e, dim=0) for h_e in all_tweet_embs])

torch.save(g_t, dataset_dir / "g_t.pt")
torch.save(all_tweet_embs, dataset_dir / "all_tweet_embs")
g_t.shape # (num_days, 2*hidden_size)

100%|██████████| 651/651 [00:05<00:00, 111.50it/s]

torch.Size([651, 128])

In [ ]:
# a_st (num_days, num_stocks) @ x_st (num_days, num_stocks, num_features) -> o_t (num_days, num_features)
# g_t (num_days, 2*hidden_size)  @ h_s.T (2*hidden_size, num_stocks) -> a_st (num_days, num_stocks)

In [35]:
h_s = model.stock_embd.weight.detach()

attn_scores = torch.matmul(g_t, h_s.T)

a_st = F.softmax(attn_scores, dim=-1)

a_st = a_st.unsqueeze(1)
a_st.shape

torch.Size([651, 1, 87])

In [36]:
o_t = torch.matmul(a_st, X_st).squeeze(1)
o_t = o_t.unsqueeze(1).expand(-1, X_st.size(1), -1)
o_t.shape

torch.Size([651, 87, 11])

### Local Similarities between Stocks

Two steps of attention

1. Attention to find tweets (on the target day) relevant to each target stock. Produces l_st, a weighted sum of the tweets for that day based on their relevance to the target stock.
    - Q: h_s
    - K: h_e
    - V: h_e

2. Attention to find stocks most relevant to l_st, and aggregate the price features based on relevance.
    - Q: l_st
    - K: h_s
    - V: x_st

This is preferable to doing h_s @ h_s.T because it will yield different results based on the day.
- Say $AAPL is doing a collaboration with $MSFT on some day, the attention score for AAPL/MSFT should be higher than usual.

h_s (num_stocks, hidden_size) @ h_e.T (hidden_size, num_tweets_that_day) -> a_e (num_stocks num_tweets_that_day)

a_e (num_stocks num_tweets_that_day) @ h_e (num_tweets_that_day, hidden_size) -> l_st (num_stocks, hidden_size)

In [37]:
l_st = []

for d in range(len(all_tweet_embs)):
    h_e = all_tweet_embs[d]
    a_e = torch.matmul(h_s, h_e.T).softmax(dim=-1)
    l_st.append(torch.matmul(a_e, h_e))

l_st = torch.stack(l_st)
l_st.shape

torch.Size([651, 87, 128])

l_st (num_days, num_stocks, hidden_size) @ h_s.T (hidden_size, num_stocks) -> a_st (num_days, num_stocks, num_stocks)

a_st (num_days, num_stocks, num_stocks) @ X_st (num_days, num_stocks, num_features) -> c_st (num_days, num_stocks, num_features)

In [38]:
a_st = torch.matmul(l_st, h_s.T).softmax(dim=-1)
c_st = torch.matmul(a_st, X_st)

c_st.shape

torch.Size([651, 87, 11])

### Windows

In [39]:
def create_windows(input, labels=False):
    if (labels):
        windows_list = [input[t+1] for t in range(window_size - 1, num_dates-1)]
    else:
        windows_list = [input[t-window_size+1 : t+1] for t in range(window_size - 1, num_dates-1)]

    # input: (num_windows, seq_len, num_stocks, features)
    # labels: (num_windows, num_stocks)
    windows = torch.stack(windows_list)

    if labels:
        windows = windows.reshape(-1)

    else:
        windows=windows.reshape(-1, windows.size(1), windows.size(-1))

    return windows

In [40]:
X_windowed, o_windowed, c_windowed = create_windows(X_st), create_windows(o_t), create_windows(c_st)
y_windowed = create_windows(y, labels=True)

X_windowed.shape, o_windowed.shape, c_windowed.shape, y_windowed.shape

(torch.Size([55332, 15, 11]),
 torch.Size([55332, 15, 11]),
 torch.Size([55332, 15, 11]),
 torch.Size([55332]))

In [41]:
mask = y_windowed != 0

X_windowed = X_windowed[mask]
o_windowed = o_windowed[mask]
c_windowed = c_windowed[mask]
y_windowed = y_windowed[mask]


X_windowed.shape, o_windowed.shape, c_windowed.shape, y_windowed.shape

(torch.Size([33711, 15, 11]),
 torch.Size([33711, 15, 11]),
 torch.Size([33711, 15, 11]),
 torch.Size([33711]))

### Train/Val/Test Split

In [42]:
data_len = len(y_windowed)

train_end = int(data_len * 0.80)
val_end = int(data_len * 0.90)

X_train, o_train, c_train, y_train = X_windowed[: train_end], o_windowed[: train_end], c_windowed[: train_end], y_windowed[: train_end]
X_val, o_val, c_val, y_val = X_windowed[train_end : val_end], o_windowed[train_end : val_end], c_windowed[train_end :val_end], y_windowed[train_end : val_end]
X_test, o_test, c_test, y_test = X_windowed[val_end :], o_windowed[val_end :], c_windowed[val_end :], y_windowed[val_end :]

print(f"X_train shape: {X_train.shape}. y_train shape: {y_train.shape}")
print(f"X_val shape: {X_val.shape}. y_val shape: {y_val.shape}")
print(f"X_test shape: {X_test.shape}. y_test shape: {y_test.shape}")

X_train shape: torch.Size([26968, 15, 11]). y_train shape: torch.Size([26968])
X_val shape: torch.Size([3371, 15, 11]). y_val shape: torch.Size([3371])
X_test shape: torch.Size([3372, 15, 11]). y_test shape: torch.Size([3372])

### Multi-Feature Dataset

In [43]:
class MultiFeatureDataset(Dataset):
    def __init__(self, x, o, c, y):
        super().__init__()
        self.x = x; self.o = o; self.c = c
        self.y = y

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.o[idx], self.c[idx], self.y[idx]

In [44]:
train_dataset = MultiFeatureDataset(X_train, o_train, c_train, y_train)
val_dataset = MultiFeatureDataset(X_val, o_val, c_val, y_val)
test_dataset = MultiFeatureDataset(X_test, o_test, c_test, y_test)

### DataLoaders

In [45]:
train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_dataloader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
test_dataloader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)
len(train_dataloader)

27

In [46]:
X, o, c, y = next(iter(train_dataloader))
X.shape

torch.Size([1024, 15, 11])

### SLOT Model Code

In [47]:
class SLOT(nn.Module):
    def __init__(self, input_size, hidden_size, dropout, output_size = 1):
        super().__init__()
        self.ln = nn.Linear(3*input_size, input_size)
        self.alstm = ALSTM(input_size=input_size, hidden_size=hidden_size, dropout=dropout)
        self.dropout = nn.Dropout(dropout)
        self.ln_f = nn.Linear(hidden_size*2, output_size)



    def forward(self, X_st, o_t, c_st):
        # X_st, o_t, c_st: (batch, seq_len, input_size)
        final_input = torch.cat((X_st, o_t, c_st), dim=-1) # (batch, seq_len, 3*input_size)
        final_input = self.ln(final_input) # (batch, seq_len, input_size)

        h_out = self.alstm(final_input) # (batch, 2*hidden_size)
        h_out = self.dropout(h_out)
        y_pred = self.ln_f(h_out) # (batch, output_size)

        return y_pred.squeeze(-1)

### Training Helper Functions

In [63]:
def evaluate(logits, y):
  # logits: (batch,)
  # y: (batch, )
  B = logits.size(0)

  loss = torch.clamp(1 - y * logits, min=0).mean()

  preds = torch.sign(logits) # (batch,)

  TP = ((y == 1) & (preds == 1)).sum().float()
  TN = ((y == -1) & (preds == -1)).sum().float()
  FP = ((y == -1) & (preds == 1)).sum().float()
  FN = ((y == 1) & (preds == -1)).sum().float()

  MCC = (TP * TN - FP * FN) / torch.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN) + 1e-8)

  acc = (preds == y).float().mean()

  return loss, acc.item(), MCC.item()

In [70]:
def training_loop(trial, lr, hidden_size, weight_decay, dropout, use_existing=False):
  torch.manual_seed(42)
  torch.cuda.manual_seed(42)

  model = SLOT(
      input_size=len(price_features),
      hidden_size=hidden_size,
      dropout=dropout
  ).to(device)


  if use_existing:
    model.load_state_dict(torch.load(dataset_dir / "best_SLOT_model.pth", map_location=device))

  optimizer = torch.optim.AdamW(params = model.parameters(), lr=lr, weight_decay=weight_decay)
  scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer=optimizer, T_max=num_epochs, eta_min=1e-6)


  best_val_loss = 1e9
  epochs_no_improve = 0
  patience = 75

  for epoch in range(num_epochs):
    train_loss = 0.0
    train_acc = 0.0



    model.train()
    for i, (X, o, c, y) in enumerate(train_dataloader):


        X, o, c, y = X.to(device), o.to(device), c.to(device), y.to(device)

        logits = model(X, o, c) # (batch, output_size)

        loss, acc, _ = evaluate(logits, y)

        train_loss += loss.detach().item()
        train_acc += acc

        optimizer.zero_grad()
        loss.backward()

        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

        optimizer.step()


    train_loss /= len(train_dataloader)
    train_acc /= len(train_dataloader)



    val_loss = 0.0
    val_acc = 0.0
    MCC = 0.0


    model.eval()

    with torch.inference_mode():
        for i, (X_val, o_val, c_val, y_val) in enumerate(val_dataloader):

            X_val, o_val, c_val, y_val = X_val.to(device), o_val.to(device), c_val.to(device), y_val.to(device)

            logits = model(X_val, o_val, c_val)

            loss, acc, mcc = evaluate(logits, y_val)

            val_loss += loss.item()
            val_acc += acc
            MCC += mcc


        val_loss /= len(val_dataloader)
        val_acc /= len(val_dataloader)
        MCC /= len(val_dataloader)

    if val_loss < best_val_loss:
          best_val_loss = val_loss
          epochs_no_improve = 0
    else:
        epochs_no_improve += 1


    if epochs_no_improve >= patience:
        break

    wandb.log({
        "MCC:": MCC,
        "train_loss": train_loss,
        "train_acc": train_acc,
        "val_loss": val_loss,
        "val_acc": val_acc,
    })

    scheduler.step()

    print(f"Epoch: {epoch:03d} | MCC: {MCC:4f} | Train loss: {train_loss:.4f} | Train acc: {100*train_acc:.2f}% | Val loss: {val_loss:.4f} | Val acc: {100*val_acc:.2f}% | LR: {optimizer.param_groups[0]['lr']:6f}")


  wandb.log({
      "last_val_loss": val_loss
  })

  wandb.finish()
  return MCC

### Training Loop

In [ ]:
def objective(trial):

    lr = trial.suggest_float("lr", 1e-4, 1e-2, log=True)
    hidden_size =  trial.suggest_int("hidden_size", 16, 128)
    dropout = trial.suggest_float("dropout", 0.0, 0.5)
    weight_decay = trial.suggest_float("weight_decay", 1e-4, 1e-1, log=True)

    wandb.init(
    project="SLOT_Train_MCC",
    name=f"trial_{trial.number}",
    config={
            "lr": lr,
            "hidden_size": hidden_size,
            "dropout": dropout,
            "weight_decay": weight_decay,
        },
    )

    return training_loop(trial, lr, hidden_size, dropout, weight_decay)


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials = 200)

[I 2025-10-05 08:36:59,954] A new study created in memory with name: no-name-781375c0-9e90-4128-838a-7817c94901ff

Epoch: 000 | MCC: 0.026376 | Train loss: 1.0015 | Train acc: 49.82% | Val loss: 0.9889 | Val acc: 56.20% | LR: 0.000163
Epoch: 001 | MCC: 0.004296 | Train loss: 1.0035 | Train acc: 49.91% | Val loss: 0.9938 | Val acc: 55.50% | LR: 0.000163
Epoch: 002 | MCC: -0.000228 | Train loss: 1.0001 | Train acc: 50.15% | Val loss: 0.9872 | Val acc: 55.07% | LR: 0.000163
Epoch: 003 | MCC: 0.006708 | Train loss: 1.0001 | Train acc: 50.09% | Val loss: 0.9887 | Val acc: 55.77% | LR: 0.000163
Epoch: 004 | MCC: 0.007090 | Train loss: 0.9998 | Train acc: 50.78% | Val loss: 0.9879 | Val acc: 55.75% | LR: 0.000163
Epoch: 005 | MCC: 0.001354 | Train loss: 0.9994 | Train acc: 50.80% | Val loss: 0.9864 | Val acc: 55.72% | LR: 0.000162
Epoch: 006 | MCC: 0.001178 | Train loss: 0.9981 | Train acc: 50.71% | Val loss: 0.9872 | Val acc: 55.84% | LR: 0.000162
Epoch: 007 | MCC: 0.014932 | Train loss: 0.9972 | Train acc: 50.75% | Val loss: 0.9845 | Val acc: 56.15% | LR: 0.000162
Epoch: 008 | MCC: 0.015301 | Train loss: 0.9970 | Train acc: 50.72% | Val loss: 0.9843 | Val acc: 56.55% | LR: 0.000162
Epoch: 009 | MCC: 0.021979 | Train loss: 0.9951 | Train acc: 50.91% | Val loss: 0.9835 | Val acc: 56.73% | LR: 0.000161
Epoch: 010 | MCC: 0.029763 | Train loss: 0.9943 | Train acc: 50.91% | Val loss: 0.9831 | Val acc: 56.82% | LR: 0.000161
Epoch: 011 | MCC: 0.025605 | Train loss: 0.9925 | Train acc: 50.99% | Val loss: 0.9823 | Val acc: 57.04% | LR: 0.000160
Epoch: 012 | MCC: 0.034825 | Train loss: 0.9923 | Train acc: 50.93% | Val loss: 0.9807 | Val acc: 57.18% | LR: 0.000160
Epoch: 013 | MCC: 0.032101 | Train loss: 0.9908 | Train acc: 50.89% | Val loss: 0.9780 | Val acc: 56.97% | LR: 0.000160
Epoch: 014 | MCC: 0.032188 | Train loss: 0.9910 | Train acc: 50.86% | Val loss: 0.9749 | Val acc: 56.95% | LR: 0.000159
Epoch: 015 | MCC: 0.022803 | Train loss: 0.9906 | Train acc: 50.94% | Val loss: 0.9735 | Val acc: 56.28% | LR: 0.000158
Epoch: 016 | MCC: 0.012341 | Train loss: 0.9897 | Train acc: 50.94% | Val loss: 0.9715 | Val acc: 56.22% | LR: 0.000158
Epoch: 017 | MCC: 0.016346 | Train loss: 0.9913 | Train acc: 50.87% | Val loss: 0.9691 | Val acc: 56.19% | LR: 0.000157
Epoch: 018 | MCC: 0.019193 | Train loss: 0.9963 | Train acc: 50.94% | Val loss: 0.9675 | Val acc: 56.18% | LR: 0.000157
Epoch: 019 | MCC: 0.027137 | Train loss: 0.9913 | Train acc: 50.80% | Val loss: 0.9656 | Val acc: 56.44% | LR: 0.000156
Epoch: 020 | MCC: 0.015467 | Train loss: 0.9902 | Train acc: 50.89% | Val loss: 0.9654 | Val acc: 56.34% | LR: 0.000155
Epoch: 021 | MCC: 0.017209 | Train loss: 0.9937 | Train acc: 50.74% | Val loss: 0.9640 | Val acc: 56.43% | LR: 0.000155
Epoch: 022 | MCC: 0.016767 | Train loss: 0.9909 | Train acc: 50.85% | Val loss: 0.9629 | Val acc: 56.40% | LR: 0.000154
Epoch: 023 | MCC: 0.022276 | Train loss: 0.9899 | Train acc: 50.82% | Val loss: 0.9605 | Val acc: 56.03% | LR: 0.000153
Epoch: 024 | MCC: 0.021710 | Train loss: 0.9891 | Train acc: 50.76% | Val loss: 0.9585 | Val acc: 56.04% | LR: 0.000152
Epoch: 025 | MCC: 0.022500 | Train loss: 0.9891 | Train acc: 50.95% | Val loss: 0.9569 | Val acc: 56.19% | LR: 0.000151
Epoch: 026 | MCC: 0.022738 | Train loss: 0.9906 | Train acc: 50.88% | Val loss: 0.9571 | Val acc: 56.10% | LR: 0.000150
Epoch: 027 | MCC: 0.023690 | Train loss: 0.9880 | Train acc: 50.82% | Val loss: 0.9522 | Val acc: 56.19% | LR: 0.000149
Epoch: 028 | MCC: 0.030436 | Train loss: 0.9860 | Train acc: 50.88% | Val loss: 0.9545 | Val acc: 56.43% | LR: 0.000149
Epoch: 029 | MCC: 0.026165 | Train loss: 0.9855 | Train acc: 50.97% | Val loss: 0.9454 | Val acc: 56.09% | LR: 0.000148
Epoch: 030 | MCC: 0.026018 | Train loss: 0.9876 | Train acc: 50.90% | Val loss: 0.9441 | Val acc: 56.11% | LR: 0.000147
Epoch: 031 | MCC: 0.028751 | Train loss: 0.9856 | Train acc: 50.84% | Val loss: 0.9418 | Val acc: 56.31% | LR: 0.000145
Epoch: 032 | MCC: 0.030807 | Train loss: 0.9858 | Train acc: 50.83% | Val loss: 0.9394 | Val acc: 56.25% | LR: 0.000144
Epoch: 033 | MCC: 0.030698 | Train loss: 0.9896 | Train acc: 50.88% | Val loss: 0.9379 | Val acc: 56.16% | LR: 0.000143
Epoch: 034 | MCC: 0.027922 | Train loss: 1.0070 | Train acc: 50.89% | Val loss: 0.9361 | Val acc: 56.11% | LR: 0.000142
Epoch: 035 | MCC: 0.026443 | Train loss: 0.9853 | Train acc: 50.91% | Val loss: 0.9488 | Val acc: 55.80% | LR: 0.000141
Epoch: 036 | MCC: 0.027197 | Train loss: 0.9848 | Train acc: 50.98% | Val loss: 0.9343 | Val acc: 55.85% | LR: 0.000140
Epoch: 037 | MCC: 0.018784 | Train loss: 0.9852 | Train acc: 50.85% | Val loss: 0.9351 | Val acc: 55.25% | LR: 0.000139
Epoch: 038 | MCC: 0.015256 | Train loss: 0.9863 | Train acc: 50.80% | Val loss: 0.9334 | Val acc: 54.83% | LR: 0.000137
Epoch: 039 | MCC: 0.023750 | Train loss: 0.9848 | Train acc: 50.90% | Val loss: 0.9341 | Val acc: 55.19% | LR: 0.000136
Epoch: 040 | MCC: 0.020853 | Train loss: 0.9846 | Train acc: 50.94% | Val loss: 0.9389 | Val acc: 55.20% | LR: 0.000135
Epoch: 041 | MCC: 0.021821 | Train loss: 0.9847 | Train acc: 50.87% | Val loss: 0.9333 | Val acc: 55.23% | LR: 0.000134
Epoch: 042 | MCC: 0.022407 | Train loss: 0.9839 | Train acc: 50.90% | Val loss: 1.4956 | Val acc: 55.13% | LR: 0.000132
Epoch: 043 | MCC: 0.025575 | Train loss: 0.9856 | Train acc: 50.88% | Val loss: 0.9339 | Val acc: 55.20% | LR: 0.000131
Epoch: 044 | MCC: 0.020269 | Train loss: 0.9844 | Train acc: 50.98% | Val loss: 0.9303 | Val acc: 54.88% | LR: 0.000130
Epoch: 045 | MCC: 0.026028 | Train loss: 0.9847 | Train acc: 50.99% | Val loss: 0.9318 | Val acc: 54.97% | LR: 0.000128
Epoch: 046 | MCC: 0.027007 | Train loss: 0.9867 | Train acc: 50.92% | Val loss: 0.9311 | Val acc: 54.96% | LR: 0.000127
Epoch: 047 | MCC: 0.021675 | Train loss: 0.9843 | Train acc: 50.98% | Val loss: 0.9387 | Val acc: 54.90% | LR: 0.000125
Epoch: 048 | MCC: 0.024744 | Train loss: 0.9843 | Train acc: 50.98% | Val loss: 0.9368 | Val acc: 55.32% | LR: 0.000124
Epoch: 049 | MCC: 0.026834 | Train loss: 0.9820 | Train acc: 51.03% | Val loss: 0.9312 | Val acc: 55.39% | LR: 0.000122
Epoch: 050 | MCC: 0.024872 | Train loss: 0.9820 | Train acc: 51.00% | Val loss: 0.9315 | Val acc: 54.97% | LR: 0.000121
Epoch: 051 | MCC: 0.025398 | Train loss: 0.9834 | Train acc: 50.98% | Val loss: 0.9442 | Val acc: 55.02% | LR: 0.000120
Epoch: 052 | MCC: 0.028104 | Train loss: 0.9861 | Train acc: 51.04% | Val loss: 0.9319 | Val acc: 54.93% | LR: 0.000118
Epoch: 053 | MCC: 0.029331 | Train loss: 0.9834 | Train acc: 50.92% | Val loss: 0.9297 | Val acc: 55.16% | LR: 0.000116
Epoch: 054 | MCC: 0.021697 | Train loss: 0.9816 | Train acc: 51.00% | Val loss: 0.9265 | Val acc: 54.96% | LR: 0.000115
Epoch: 055 | MCC: 0.018158 | Train loss: 0.9824 | Train acc: 50.96% | Val loss: 0.9326 | Val acc: 54.68% | LR: 0.000113
Epoch: 056 | MCC: 0.020434 | Train loss: 0.9848 | Train acc: 50.99% | Val loss: 0.9285 | Val acc: 54.90% | LR: 0.000112
Epoch: 057 | MCC: 0.021854 | Train loss: 0.9824 | Train acc: 50.92% | Val loss: 0.9294 | Val acc: 54.89% | LR: 0.000110
Epoch: 058 | MCC: 0.026347 | Train loss: 0.9839 | Train acc: 50.81% | Val loss: 0.9281 | Val acc: 55.16% | LR: 0.000109
Epoch: 059 | MCC: 0.020777 | Train loss: 0.9880 | Train acc: 50.99% | Val loss: 0.9264 | Val acc: 54.90% | LR: 0.000107
Epoch: 060 | MCC: 0.025955 | Train loss: 0.9836 | Train acc: 50.98% | Val loss: 0.9281 | Val acc: 55.13% | LR: 0.000105
Epoch: 061 | MCC: 0.031024 | Train loss: 0.9842 | Train acc: 50.92% | Val loss: 0.9280 | Val acc: 55.50% | LR: 0.000104
Epoch: 062 | MCC: 0.027883 | Train loss: 0.9824 | Train acc: 50.94% | Val loss: 0.9263 | Val acc: 55.48% | LR: 0.000102
Epoch: 063 | MCC: 0.025441 | Train loss: 0.9818 | Train acc: 50.85% | Val loss: 0.9555 | Val acc: 55.13% | LR: 0.000100
Epoch: 064 | MCC: 0.023007 | Train loss: 0.9822 | Train acc: 50.92% | Val loss: 0.9340 | Val acc: 55.02% | LR: 0.000099
Epoch: 065 | MCC: 0.024311 | Train loss: 0.9806 | Train acc: 51.02% | Val loss: 0.9228 | Val acc: 55.02% | LR: 0.000097
Epoch: 066 | MCC: 0.027434 | Train loss: 0.9839 | Train acc: 50.96% | Val loss: 0.9241 | Val acc: 55.10% | LR: 0.000096
Epoch: 067 | MCC: 0.026547 | Train loss: 0.9834 | Train acc: 50.85% | Val loss: 0.9296 | Val acc: 55.10% | LR: 0.000094
Epoch: 068 | MCC: 0.024407 | Train loss: 0.9882 | Train acc: 51.09% | Val loss: 0.9653 | Val acc: 55.12% | LR: 0.000092
Epoch: 069 | MCC: 0.024731 | Train loss: 0.9825 | Train acc: 50.86% | Val loss: 0.9248 | Val acc: 54.95% | LR: 0.000090
Epoch: 070 | MCC: 0.024650 | Train loss: 0.9810 | Train acc: 51.09% | Val loss: 0.9226 | Val acc: 54.89% | LR: 0.000089
Epoch: 071 | MCC: 0.024033 | Train loss: 0.9820 | Train acc: 50.98% | Val loss: 0.9667 | Val acc: 55.19% | LR: 0.000087
Epoch: 072 | MCC: 0.019830 | Train loss: 1.0051 | Train acc: 50.84% | Val loss: 0.9267 | Val acc: 55.34% | LR: 0.000085
Epoch: 073 | MCC: 0.022537 | Train loss: 0.9818 | Train acc: 50.89% | Val loss: 0.9251 | Val acc: 55.56% | LR: 0.000084
Epoch: 074 | MCC: 0.024991 | Train loss: 0.9804 | Train acc: 50.88% | Val loss: 0.9294 | Val acc: 55.68% | LR: 0.000082
Epoch: 075 | MCC: 0.022957 | Train loss: 0.9834 | Train acc: 50.92% | Val loss: 0.9332 | Val acc: 55.57% | LR: 0.000080
Epoch: 076 | MCC: 0.025546 | Train loss: 0.9804 | Train acc: 51.00% | Val loss: 0.9254 | Val acc: 55.73% | LR: 0.000079
Epoch: 077 | MCC: 0.027986 | Train loss: 0.9818 | Train acc: 50.91% | Val loss: 0.9177 | Val acc: 55.95% | LR: 0.000077
Epoch: 078 | MCC: 0.029467 | Train loss: 0.9830 | Train acc: 50.85% | Val loss: 0.9224 | Val acc: 55.98% | LR: 0.000075
Epoch: 079 | MCC: 0.024677 | Train loss: 0.9816 | Train acc: 50.85% | Val loss: 0.9189 | Val acc: 55.76% | LR: 0.000074
Epoch: 080 | MCC: 0.027732 | Train loss: 0.9857 | Train acc: 51.00% | Val loss: 0.9233 | Val acc: 55.91% | LR: 0.000072
Epoch: 081 | MCC: 0.029754 | Train loss: 0.9816 | Train acc: 50.86% | Val loss: 0.9131 | Val acc: 56.05% | LR: 0.000070
Epoch: 082 | MCC: 0.031729 | Train loss: 0.9809 | Train acc: 50.83% | Val loss: 0.9153 | Val acc: 56.17% | LR: 0.000068
Epoch: 083 | MCC: 0.027624 | Train loss: 0.9797 | Train acc: 51.01% | Val loss: 0.9173 | Val acc: 56.08% | LR: 0.000067
Epoch: 084 | MCC: 0.028404 | Train loss: 0.9812 | Train acc: 50.88% | Val loss: 0.9265 | Val acc: 56.05% | LR: 0.000065
Epoch: 085 | MCC: 0.030228 | Train loss: 0.9795 | Train acc: 50.97% | Val loss: 0.9127 | Val acc: 56.09% | LR: 0.000064
Epoch: 086 | MCC: 0.030239 | Train loss: 0.9787 | Train acc: 50.87% | Val loss: 0.9165 | Val acc: 56.14% | LR: 0.000062
Epoch: 087 | MCC: 0.033071 | Train loss: 0.9812 | Train acc: 50.69% | Val loss: 0.9134 | Val acc: 56.28% | LR: 0.000060
Epoch: 088 | MCC: 0.032355 | Train loss: 0.9809 | Train acc: 50.90% | Val loss: 0.9144 | Val acc: 56.26% | LR: 0.000059
Epoch: 089 | MCC: 0.030962 | Train loss: 0.9788 | Train acc: 50.86% | Val loss: 0.9108 | Val acc: 56.16% | LR: 0.000057
Epoch: 090 | MCC: 0.029262 | Train loss: 0.9831 | Train acc: 50.84% | Val loss: 0.9112 | Val acc: 56.09% | LR: 0.000055
Epoch: 091 | MCC: 0.031994 | Train loss: 0.9795 | Train acc: 50.81% | Val loss: 0.9092 | Val acc: 56.16% | LR: 0.000054
Epoch: 092 | MCC: 0.031687 | Train loss: 0.9791 | Train acc: 50.97% | Val loss: 0.9095 | Val acc: 56.16% | LR: 0.000052
Epoch: 093 | MCC: 0.030422 | Train loss: 0.9789 | Train acc: 50.83% | Val loss: 0.9107 | Val acc: 56.14% | LR: 0.000051
Epoch: 094 | MCC: 0.028927 | Train loss: 0.9784 | Train acc: 50.87% | Val loss: 0.9134 | Val acc: 56.06% | LR: 0.000049
Epoch: 095 | MCC: 0.030861 | Train loss: 0.9788 | Train acc: 50.83% | Val loss: 0.9079 | Val acc: 56.14% | LR: 0.000048
Epoch: 096 | MCC: 0.030343 | Train loss: 0.9888 | Train acc: 51.18% | Val loss: 0.9253 | Val acc: 56.14% | LR: 0.000046
Epoch: 097 | MCC: 0.028359 | Train loss: 0.9808 | Train acc: 51.56% | Val loss: 0.9088 | Val acc: 55.96% | LR: 0.000044
Epoch: 098 | MCC: 0.026782 | Train loss: 0.9794 | Train acc: 50.84% | Val loss: 0.9092 | Val acc: 55.92% | LR: 0.000043
Epoch: 099 | MCC: 0.026936 | Train loss: 0.9783 | Train acc: 50.91% | Val loss: 0.9096 | Val acc: 55.92% | LR: 0.000041
Epoch: 100 | MCC: 0.027777 | Train loss: 0.9795 | Train acc: 50.81% | Val loss: 0.9097 | Val acc: 55.96% | LR: 0.000040
Epoch: 101 | MCC: 0.025154 | Train loss: 0.9958 | Train acc: 50.84% | Val loss: 0.9157 | Val acc: 55.82% | LR: 0.000039
Epoch: 102 | MCC: 0.024943 | Train loss: 0.9777 | Train acc: 50.84% | Val loss: 0.9092 | Val acc: 55.82% | LR: 0.000037
Epoch: 103 | MCC: 0.025096 | Train loss: 0.9787 | Train acc: 50.94% | Val loss: 0.9079 | Val acc: 55.82% | LR: 0.000036
Epoch: 104 | MCC: 0.026498 | Train loss: 0.9779 | Train acc: 51.15% | Val loss: 0.9073 | Val acc: 55.92% | LR: 0.000034
Epoch: 105 | MCC: 0.026498 | Train loss: 0.9774 | Train acc: 50.84% | Val loss: 0.9085 | Val acc: 55.92% | LR: 0.000033
Epoch: 106 | MCC: 0.027012 | Train loss: 0.9778 | Train acc: 50.82% | Val loss: 0.9070 | Val acc: 55.94% | LR: 0.000032
Epoch: 107 | MCC: 0.027012 | Train loss: 0.9791 | Train acc: 50.86% | Val loss: 0.9066 | Val acc: 55.94% | LR: 0.000030
Epoch: 108 | MCC: 0.026958 | Train loss: 0.9783 | Train acc: 50.79% | Val loss: 0.9076 | Val acc: 55.94% | LR: 0.000029
Epoch: 109 | MCC: 0.025855 | Train loss: 0.9779 | Train acc: 50.77% | Val loss: 0.9239 | Val acc: 55.87% | LR: 0.000028
Epoch: 110 | MCC: 0.027913 | Train loss: 0.9781 | Train acc: 50.86% | Val loss: 0.9081 | Val acc: 55.96% | LR: 0.000027
Epoch: 111 | MCC: 0.027941 | Train loss: 0.9771 | Train acc: 50.89% | Val loss: 0.9105 | Val acc: 56.01% | LR: 0.000025
Epoch: 112 | MCC: 0.024256 | Train loss: 0.9796 | Train acc: 51.11% | Val loss: 0.9107 | Val acc: 55.79% | LR: 0.000024
Epoch: 113 | MCC: 0.025876 | Train loss: 0.9792 | Train acc: 51.53% | Val loss: 0.9075 | Val acc: 55.89% | LR: 0.000023
Epoch: 114 | MCC: 0.026726 | Train loss: 0.9774 | Train acc: 51.42% | Val loss: 0.9075 | Val acc: 55.92% | LR: 0.000022
Epoch: 115 | MCC: 0.026726 | Train loss: 0.9771 | Train acc: 50.96% | Val loss: 0.9087 | Val acc: 55.92% | LR: 0.000021
Epoch: 116 | MCC: 0.030280 | Train loss: 0.9776 | Train acc: 51.26% | Val loss: 0.9048 | Val acc: 56.06% | LR: 0.000020
Epoch: 117 | MCC: 0.028708 | Train loss: 0.9769 | Train acc: 51.50% | Val loss: 0.9065 | Val acc: 56.01% | LR: 0.000019
Epoch: 118 | MCC: 0.029511 | Train loss: 0.9781 | Train acc: 51.32% | Val loss: 0.9060 | Val acc: 56.04% | LR: 0.000017
Epoch: 119 | MCC: 0.029896 | Train loss: 0.9772 | Train acc: 51.27% | Val loss: 0.9066 | Val acc: 56.06% | LR: 0.000016
Epoch: 120 | MCC: 0.029457 | Train loss: 0.9773 | Train acc: 51.83% | Val loss: 0.9067 | Val acc: 56.04% | LR: 0.000015
Epoch: 121 | MCC: 0.029918 | Train loss: 0.9768 | Train acc: 51.64% | Val loss: 0.9049 | Val acc: 56.06% | LR: 0.000015
Epoch: 122 | MCC: 0.029172 | Train loss: 0.9777 | Train acc: 51.64% | Val loss: 0.9055 | Val acc: 56.04% | LR: 0.000014
Epoch: 123 | MCC: 0.027475 | Train loss: 0.9772 | Train acc: 51.31% | Val loss: 0.9083 | Val acc: 55.94% | LR: 0.000013
Epoch: 124 | MCC: 0.029094 | Train loss: 0.9778 | Train acc: 51.48% | Val loss: 0.9071 | Val acc: 56.04% | LR: 0.000012
Epoch: 125 | MCC: 0.029457 | Train loss: 0.9784 | Train acc: 51.57% | Val loss: 0.9069 | Val acc: 56.04% | LR: 0.000011
Epoch: 126 | MCC: 0.029457 | Train loss: 0.9772 | Train acc: 51.48% | Val loss: 0.9090 | Val acc: 56.04% | LR: 0.000010
Epoch: 127 | MCC: 0.029918 | Train loss: 0.9779 | Train acc: 51.57% | Val loss: 0.9051 | Val acc: 56.06% | LR: 0.000009
Epoch: 128 | MCC: 0.028686 | Train loss: 0.9773 | Train acc: 51.89% | Val loss: 0.9058 | Val acc: 55.99% | LR: 0.000009
Epoch: 129 | MCC: 0.029918 | Train loss: 0.9770 | Train acc: 52.12% | Val loss: 0.9051 | Val acc: 56.06% | LR: 0.000008
Epoch: 130 | MCC: 0.028993 | Train loss: 0.9782 | Train acc: 52.36% | Val loss: 0.9073 | Val acc: 56.01% | LR: 0.000007
Epoch: 131 | MCC: 0.028993 | Train loss: 0.9784 | Train acc: 51.75% | Val loss: 0.9092 | Val acc: 56.01% | LR: 0.000007
Epoch: 132 | MCC: 0.029536 | Train loss: 0.9758 | Train acc: 52.11% | Val loss: 0.9076 | Val acc: 56.04% | LR: 0.000006
Epoch: 133 | MCC: 0.029457 | Train loss: 0.9766 | Train acc: 51.68% | Val loss: 0.9067 | Val acc: 56.04% | LR: 0.000006
Epoch: 134 | MCC: 0.029457 | Train loss: 0.9760 | Train acc: 51.99% | Val loss: 0.9085 | Val acc: 56.04% | LR: 0.000005
Epoch: 135 | MCC: 0.029457 | Train loss: 0.9789 | Train acc: 51.57% | Val loss: 0.9090 | Val acc: 56.04% | LR: 0.000004
Epoch: 136 | MCC: 0.029457 | Train loss: 0.9770 | Train acc: 51.54% | Val loss: 0.9071 | Val acc: 56.04% | LR: 0.000004
Epoch: 137 | MCC: 0.029457 | Train loss: 0.9763 | Train acc: 52.36% | Val loss: 0.9074 | Val acc: 56.04% | LR: 0.000004
Epoch: 138 | MCC: 0.029457 | Train loss: 0.9772 | Train acc: 52.62% | Val loss: 0.9079 | Val acc: 56.04% | LR: 0.000003
Epoch: 139 | MCC: 0.029457 | Train loss: 0.9776 | Train acc: 51.52% | Val loss: 0.9095 | Val acc: 56.04% | LR: 0.000003
Epoch: 140 | MCC: 0.029457 | Train loss: 0.9765 | Train acc: 52.17% | Val loss: 0.9062 | Val acc: 56.04% | LR: 0.000002
Epoch: 141 | MCC: 0.029457 | Train loss: 0.9772 | Train acc: 51.93% | Val loss: 0.9065 | Val acc: 56.04% | LR: 0.000002
Epoch: 142 | MCC: 0.029457 | Train loss: 0.9776 | Train acc: 52.75% | Val loss: 0.9061 | Val acc: 56.04% | LR: 0.000002
Epoch: 143 | MCC: 0.029457 | Train loss: 0.9764 | Train acc: 52.19% | Val loss: 0.9061 | Val acc: 56.04% | LR: 0.000002
Epoch: 144 | MCC: 0.029457 | Train loss: 0.9777 | Train acc: 51.75% | Val loss: 0.9063 | Val acc: 56.04% | LR: 0.000001
Epoch: 145 | MCC: 0.029457 | Train loss: 0.9765 | Train acc: 51.46% | Val loss: 0.9061 | Val acc: 56.04% | LR: 0.000001
Epoch: 146 | MCC: 0.029457 | Train loss: 0.9767 | Train acc: 51.84% | Val loss: 0.9061 | Val acc: 56.04% | LR: 0.000001
Epoch: 147 | MCC: 0.029457 | Train loss: 0.9763 | Train acc: 51.49% | Val loss: 0.9065 | Val acc: 56.04% | LR: 0.000001
Epoch: 148 | MCC: 0.029918 | Train loss: 0.9779 | Train acc: 51.62% | Val loss: 0.9070 | Val acc: 56.06% | LR: 0.000001
Epoch: 149 | MCC: 0.029457 | Train loss: 0.9764 | Train acc: 51.87% | Val loss: 0.9065 | Val acc: 56.04% | LR: 0.000001

[I 2025-10-05 08:39:12,041] Trial 0 finished with value: 0.02945748995989561 and parameters: {'lr': 0.00016299915617778437, 'hidden_size': 65, 'dropout': 0.3446275782276479, 'weight_decay': 0.0003804670000598707}. Best is trial 0 with value: 0.02945748995989561.

Epoch: 000 | MCC: -0.010559 | Train loss: 0.9966 | Train acc: 50.30% | Val loss: 0.9782 | Val acc: 54.71% | LR: 0.000382
Epoch: 001 | MCC: 0.006778 | Train loss: 0.9953 | Train acc: 50.42% | Val loss: 0.9735 | Val acc: 54.68% | LR: 0.000382
Epoch: 002 | MCC: 0.025296 | Train loss: 0.9954 | Train acc: 50.82% | Val loss: 0.9654 | Val acc: 54.75% | LR: 0.000382
Epoch: 003 | MCC: 0.008003 | Train loss: 0.9939 | Train acc: 51.00% | Val loss: 0.9579 | Val acc: 54.38% | LR: 0.000382
Epoch: 004 | MCC: 0.011801 | Train loss: 0.9978 | Train acc: 50.87% | Val loss: 0.9605 | Val acc: 54.40% | LR: 0.000381
Epoch: 005 | MCC: 0.020482 | Train loss: 0.9950 | Train acc: 50.89% | Val loss: 0.9600 | Val acc: 55.38% | LR: 0.000381
Epoch: 006 | MCC: 0.021719 | Train loss: 0.9926 | Train acc: 50.99% | Val loss: 0.9566 | Val acc: 56.04% | LR: 0.000380
Epoch: 007 | MCC: 0.028454 | Train loss: 0.9908 | Train acc: 50.97% | Val loss: 0.9504 | Val acc: 56.31% | LR: 0.000380
Epoch: 008 | MCC: 0.029485 | Train loss: 0.9887 | Train acc: 50.94% | Val loss: 0.9466 | Val acc: 56.39% | LR: 0.000379
Epoch: 009 | MCC: 0.023073 | Train loss: 0.9860 | Train acc: 51.04% | Val loss: 0.9399 | Val acc: 56.13% | LR: 0.000378
Epoch: 010 | MCC: 0.027026 | Train loss: 0.9858 | Train acc: 50.92% | Val loss: 0.9327 | Val acc: 56.35% | LR: 0.000377
Epoch: 011 | MCC: 0.028154 | Train loss: 0.9819 | Train acc: 51.03% | Val loss: 0.9285 | Val acc: 56.24% | LR: 0.000376
Epoch: 012 | MCC: 0.034724 | Train loss: 0.9829 | Train acc: 50.95% | Val loss: 0.9232 | Val acc: 56.66% | LR: 0.000375
Epoch: 013 | MCC: 0.032418 | Train loss: 0.9800 | Train acc: 51.09% | Val loss: 0.9166 | Val acc: 56.60% | LR: 0.000374
Epoch: 014 | MCC: 0.027638 | Train loss: 0.9816 | Train acc: 51.00% | Val loss: 0.9183 | Val acc: 56.07% | LR: 0.000373
Epoch: 015 | MCC: 0.024715 | Train loss: 0.9812 | Train acc: 51.07% | Val loss: 0.9205 | Val acc: 55.92% | LR: 0.000372
Epoch: 016 | MCC: 0.026844 | Train loss: 0.9967 | Train acc: 50.94% | Val loss: 0.9091 | Val acc: 55.84% | LR: 0.000370
Epoch: 017 | MCC: 0.023661 | Train loss: 0.9834 | Train acc: 50.95% | Val loss: 0.9048 | Val acc: 55.82% | LR: 0.000369
Epoch: 018 | MCC: 0.044193 | Train loss: 0.9876 | Train acc: 50.99% | Val loss: 0.9024 | Val acc: 57.12% | LR: 0.000367
Epoch: 019 | MCC: 0.059204 | Train loss: 0.9863 | Train acc: 50.92% | Val loss: 0.8987 | Val acc: 57.88% | LR: 0.000366
Epoch: 020 | MCC: 0.033650 | Train loss: 0.9831 | Train acc: 50.95% | Val loss: 0.8970 | Val acc: 57.27% | LR: 0.000364
Epoch: 021 | MCC: 0.039441 | Train loss: 0.9800 | Train acc: 51.12% | Val loss: 0.8934 | Val acc: 57.13% | LR: 0.000362
Epoch: 022 | MCC: 0.042741 | Train loss: 0.9820 | Train acc: 51.08% | Val loss: 0.8923 | Val acc: 56.89% | LR: 0.000361
Epoch: 023 | MCC: 0.030199 | Train loss: 0.9794 | Train acc: 51.17% | Val loss: 0.8889 | Val acc: 56.82% | LR: 0.000359
Epoch: 024 | MCC: 0.027499 | Train loss: 0.9817 | Train acc: 51.06% | Val loss: 0.8850 | Val acc: 56.96% | LR: 0.000357
Epoch: 025 | MCC: 0.022561 | Train loss: 0.9802 | Train acc: 51.15% | Val loss: 0.8829 | Val acc: 56.67% | LR: 0.000355
Epoch: 026 | MCC: -0.003097 | Train loss: 0.9797 | Train acc: 51.15% | Val loss: 0.8800 | Val acc: 56.38% | LR: 0.000353
Epoch: 027 | MCC: 0.000097 | Train loss: 0.9799 | Train acc: 51.17% | Val loss: 0.8807 | Val acc: 55.92% | LR: 0.000350
Epoch: 028 | MCC: 0.002685 | Train loss: 0.9783 | Train acc: 51.22% | Val loss: 0.8777 | Val acc: 56.14% | LR: 0.000348
Epoch: 029 | MCC: 0.006782 | Train loss: 0.9788 | Train acc: 51.24% | Val loss: 0.8744 | Val acc: 56.27% | LR: 0.000346
Epoch: 030 | MCC: 0.006323 | Train loss: 0.9822 | Train acc: 51.29% | Val loss: 0.8731 | Val acc: 56.42% | LR: 0.000343
Epoch: 031 | MCC: 0.003222 | Train loss: 0.9773 | Train acc: 51.33% | Val loss: 0.8714 | Val acc: 56.37% | LR: 0.000341
Epoch: 032 | MCC: 0.004071 | Train loss: 0.9775 | Train acc: 51.26% | Val loss: 0.8719 | Val acc: 56.39% | LR: 0.000338
Epoch: 033 | MCC: -0.004091 | Train loss: 0.9771 | Train acc: 51.33% | Val loss: 0.8689 | Val acc: 56.61% | LR: 0.000336
Epoch: 034 | MCC: -0.009378 | Train loss: 0.9773 | Train acc: 51.27% | Val loss: 0.8665 | Val acc: 56.56% | LR: 0.000333
Epoch: 035 | MCC: 0.002787 | Train loss: 0.9777 | Train acc: 51.23% | Val loss: 0.8649 | Val acc: 57.15% | LR: 0.000331
Epoch: 036 | MCC: -0.004454 | Train loss: 0.9763 | Train acc: 51.29% | Val loss: 0.8671 | Val acc: 56.64% | LR: 0.000328
Epoch: 037 | MCC: 0.012403 | Train loss: 0.9756 | Train acc: 51.33% | Val loss: 0.8573 | Val acc: 57.66% | LR: 0.000325
Epoch: 038 | MCC: 0.011980 | Train loss: 0.9767 | Train acc: 51.24% | Val loss: 0.8560 | Val acc: 57.66% | LR: 0.000322
Epoch: 039 | MCC: -0.000401 | Train loss: 0.9785 | Train acc: 51.12% | Val loss: 0.8640 | Val acc: 56.83% | LR: 0.000319
Epoch: 040 | MCC: 0.017605 | Train loss: 0.9739 | Train acc: 51.42% | Val loss: 0.8474 | Val acc: 58.44% | LR: 0.000316
Epoch: 041 | MCC: 0.018982 | Train loss: 0.9754 | Train acc: 51.34% | Val loss: 0.8513 | Val acc: 58.10% | LR: 0.000313
Epoch: 042 | MCC: 0.021572 | Train loss: 0.9727 | Train acc: 51.48% | Val loss: 0.8469 | Val acc: 58.32% | LR: 0.000310
Epoch: 043 | MCC: 0.029549 | Train loss: 0.9744 | Train acc: 51.38% | Val loss: 0.8412 | Val acc: 59.01% | LR: 0.000307
Epoch: 044 | MCC: 0.021913 | Train loss: 0.9735 | Train acc: 51.45% | Val loss: 0.8483 | Val acc: 58.22% | LR: 0.000304
Epoch: 045 | MCC: 0.011343 | Train loss: 0.9767 | Train acc: 51.29% | Val loss: 0.8585 | Val acc: 57.35% | LR: 0.000300
Epoch: 046 | MCC: 0.028743 | Train loss: 0.9724 | Train acc: 51.48% | Val loss: 0.8377 | Val acc: 58.98% | LR: 0.000297
Epoch: 047 | MCC: 0.025001 | Train loss: 0.9736 | Train acc: 51.40% | Val loss: 0.8357 | Val acc: 58.98% | LR: 0.000294
Epoch: 048 | MCC: 0.026532 | Train loss: 0.9785 | Train acc: 51.18% | Val loss: 0.8351 | Val acc: 59.15% | LR: 0.000290
Epoch: 049 | MCC: 0.028141 | Train loss: 0.9730 | Train acc: 51.46% | Val loss: 0.8342 | Val acc: 59.03% | LR: 0.000287
Epoch: 050 | MCC: 0.026463 | Train loss: 0.9734 | Train acc: 51.44% | Val loss: 0.8440 | Val acc: 58.96% | LR: 0.000283
Epoch: 051 | MCC: 0.045023 | Train loss: 0.9757 | Train acc: 51.33% | Val loss: 0.8192 | Val acc: 60.30% | LR: 0.000280
Epoch: 052 | MCC: 0.042785 | Train loss: 0.9737 | Train acc: 51.43% | Val loss: 0.8265 | Val acc: 59.93% | LR: 0.000276
Epoch: 053 | MCC: 0.037953 | Train loss: 0.9722 | Train acc: 51.43% | Val loss: 0.8266 | Val acc: 59.67% | LR: 0.000273
Epoch: 054 | MCC: 0.029332 | Train loss: 0.9760 | Train acc: 51.29% | Val loss: 0.8376 | Val acc: 59.01% | LR: 0.000269
Epoch: 055 | MCC: 0.029804 | Train loss: 0.9747 | Train acc: 51.40% | Val loss: 0.8307 | Val acc: 59.32% | LR: 0.000265
Epoch: 056 | MCC: 0.036133 | Train loss: 0.9740 | Train acc: 51.36% | Val loss: 0.8317 | Val acc: 59.18% | LR: 0.000262
Epoch: 057 | MCC: 0.035933 | Train loss: 0.9719 | Train acc: 51.50% | Val loss: 0.8232 | Val acc: 59.70% | LR: 0.000258
Epoch: 058 | MCC: 0.026861 | Train loss: 0.9701 | Train acc: 51.62% | Val loss: 0.8302 | Val acc: 59.30% | LR: 0.000254
Epoch: 059 | MCC: 0.041099 | Train loss: 0.9732 | Train acc: 51.44% | Val loss: 0.8231 | Val acc: 59.59% | LR: 0.000251
Epoch: 060 | MCC: 0.034797 | Train loss: 0.9721 | Train acc: 51.47% | Val loss: 0.8243 | Val acc: 59.42% | LR: 0.000247
Epoch: 061 | MCC: 0.037275 | Train loss: 0.9702 | Train acc: 51.59% | Val loss: 0.8140 | Val acc: 60.03% | LR: 0.000243
Epoch: 062 | MCC: 0.039464 | Train loss: 0.9728 | Train acc: 51.43% | Val loss: 0.8204 | Val acc: 59.64% | LR: 0.000239
Epoch: 063 | MCC: 0.044251 | Train loss: 0.9725 | Train acc: 51.44% | Val loss: 0.8191 | Val acc: 59.81% | LR: 0.000235
Epoch: 064 | MCC: 0.035074 | Train loss: 0.9732 | Train acc: 51.43% | Val loss: 0.8154 | Val acc: 59.81% | LR: 0.000231
Epoch: 065 | MCC: 0.037679 | Train loss: 0.9719 | Train acc: 51.49% | Val loss: 0.8217 | Val acc: 59.42% | LR: 0.000227
Epoch: 066 | MCC: 0.034813 | Train loss: 0.9704 | Train acc: 51.55% | Val loss: 0.8179 | Val acc: 59.82% | LR: 0.000223
Epoch: 067 | MCC: 0.026160 | Train loss: 0.9715 | Train acc: 51.45% | Val loss: 0.8517 | Val acc: 59.39% | LR: 0.000219
Epoch: 068 | MCC: 0.023558 | Train loss: 0.9730 | Train acc: 51.43% | Val loss: 0.8331 | Val acc: 59.24% | LR: 0.000216
Epoch: 069 | MCC: 0.037407 | Train loss: 0.9719 | Train acc: 51.49% | Val loss: 0.8341 | Val acc: 59.63% | LR: 0.000212
Epoch: 070 | MCC: 0.033949 | Train loss: 0.9717 | Train acc: 51.48% | Val loss: 0.8229 | Val acc: 59.62% | LR: 0.000208
Epoch: 071 | MCC: 0.023488 | Train loss: 0.9722 | Train acc: 51.45% | Val loss: 0.8211 | Val acc: 59.40% | LR: 0.000204
Epoch: 072 | MCC: 0.034036 | Train loss: 0.9691 | Train acc: 51.60% | Val loss: 0.8278 | Val acc: 59.27% | LR: 0.000200
Epoch: 073 | MCC: 0.025351 | Train loss: 0.9710 | Train acc: 51.50% | Val loss: 0.8190 | Val acc: 59.61% | LR: 0.000196
Epoch: 074 | MCC: 0.023160 | Train loss: 0.9706 | Train acc: 51.56% | Val loss: 0.8250 | Val acc: 59.21% | LR: 0.000192
Epoch: 075 | MCC: 0.025766 | Train loss: 0.9724 | Train acc: 51.47% | Val loss: 0.8216 | Val acc: 59.46% | LR: 0.000188
Epoch: 076 | MCC: 0.027191 | Train loss: 0.9699 | Train acc: 51.56% | Val loss: 0.8244 | Val acc: 59.36% | LR: 0.000184
Epoch: 077 | MCC: 0.028197 | Train loss: 0.9726 | Train acc: 51.40% | Val loss: 0.8334 | Val acc: 59.51% | LR: 0.000180
Epoch: 078 | MCC: 0.027976 | Train loss: 0.9704 | Train acc: 51.58% | Val loss: 0.8237 | Val acc: 59.30% | LR: 0.000176
Epoch: 079 | MCC: 0.034351 | Train loss: 0.9702 | Train acc: 51.59% | Val loss: 0.8286 | Val acc: 59.18% | LR: 0.000172
Epoch: 080 | MCC: 0.035069 | Train loss: 0.9720 | Train acc: 51.44% | Val loss: 0.8316 | Val acc: 59.27% | LR: 0.000168
Epoch: 081 | MCC: 0.027710 | Train loss: 0.9717 | Train acc: 51.47% | Val loss: 0.8266 | Val acc: 59.30% | LR: 0.000164
Epoch: 082 | MCC: 0.023907 | Train loss: 0.9696 | Train acc: 51.58% | Val loss: 0.8255 | Val acc: 59.29% | LR: 0.000160
Epoch: 083 | MCC: 0.037994 | Train loss: 0.9706 | Train acc: 51.53% | Val loss: 0.8317 | Val acc: 59.16% | LR: 0.000156
Epoch: 084 | MCC: 0.014847 | Train loss: 0.9711 | Train acc: 51.52% | Val loss: 0.8313 | Val acc: 59.04% | LR: 0.000152
Epoch: 085 | MCC: 0.033983 | Train loss: 0.9682 | Train acc: 51.65% | Val loss: 0.9790 | Val acc: 59.49% | LR: 0.000148
Epoch: 086 | MCC: 0.025873 | Train loss: 0.9726 | Train acc: 51.44% | Val loss: 0.8760 | Val acc: 59.48% | LR: 0.000144
Epoch: 087 | MCC: 0.027319 | Train loss: 0.9704 | Train acc: 51.55% | Val loss: 0.8332 | Val acc: 59.25% | LR: 0.000140
Epoch: 088 | MCC: 0.031673 | Train loss: 0.9713 | Train acc: 51.52% | Val loss: 0.8342 | Val acc: 59.52% | LR: 0.000137
Epoch: 089 | MCC: 0.029291 | Train loss: 0.9714 | Train acc: 51.48% | Val loss: 0.8302 | Val acc: 59.32% | LR: 0.000133
Epoch: 090 | MCC: 0.033780 | Train loss: 0.9699 | Train acc: 51.58% | Val loss: 0.8251 | Val acc: 59.42% | LR: 0.000129
Epoch: 091 | MCC: 0.037184 | Train loss: 0.9859 | Train acc: 51.50% | Val loss: 0.8222 | Val acc: 59.76% | LR: 0.000125
Epoch: 092 | MCC: 0.032298 | Train loss: 0.9735 | Train acc: 51.51% | Val loss: 0.8296 | Val acc: 59.62% | LR: 0.000121
Epoch: 093 | MCC: 0.033580 | Train loss: 0.9723 | Train acc: 51.58% | Val loss: 0.8243 | Val acc: 59.62% | LR: 0.000118
Epoch: 094 | MCC: 0.028327 | Train loss: 0.9705 | Train acc: 51.61% | Val loss: 0.8226 | Val acc: 59.59% | LR: 0.000114
Epoch: 095 | MCC: 0.031162 | Train loss: 0.9696 | Train acc: 51.66% | Val loss: 0.8253 | Val acc: 59.57% | LR: 0.000110
Epoch: 096 | MCC: 0.031845 | Train loss: 0.9718 | Train acc: 51.51% | Val loss: 0.8289 | Val acc: 59.37% | LR: 0.000107
Epoch: 097 | MCC: 0.029182 | Train loss: 0.9707 | Train acc: 51.55% | Val loss: 0.8251 | Val acc: 59.84% | LR: 0.000103
Epoch: 098 | MCC: 0.035993 | Train loss: 0.9714 | Train acc: 51.52% | Val loss: 0.8307 | Val acc: 59.42% | LR: 0.000100
Epoch: 099 | MCC: 0.026507 | Train loss: 0.9718 | Train acc: 51.50% | Val loss: 0.8320 | Val acc: 59.35% | LR: 0.000096
Epoch: 100 | MCC: 0.030226 | Train loss: 0.9713 | Train acc: 51.56% | Val loss: 0.8294 | Val acc: 59.49% | LR: 0.000093
Epoch: 101 | MCC: 0.030006 | Train loss: 0.9701 | Train acc: 51.60% | Val loss: 0.8300 | Val acc: 59.69% | LR: 0.000089
Epoch: 102 | MCC: 0.023099 | Train loss: 0.9714 | Train acc: 51.53% | Val loss: 0.8534 | Val acc: 59.27% | LR: 0.000086
Epoch: 103 | MCC: 0.023608 | Train loss: 0.9691 | Train acc: 51.66% | Val loss: 0.8362 | Val acc: 59.56% | LR: 0.000083
Epoch: 104 | MCC: 0.029791 | Train loss: 0.9686 | Train acc: 51.68% | Val loss: 0.8260 | Val acc: 59.52% | LR: 0.000080
Epoch: 105 | MCC: 0.029447 | Train loss: 0.9695 | Train acc: 51.62% | Val loss: 0.8556 | Val acc: 59.49% | LR: 0.000076
Epoch: 106 | MCC: 0.030380 | Train loss: 0.9686 | Train acc: 51.70% | Val loss: 0.8279 | Val acc: 59.47% | LR: 0.000073
Epoch: 107 | MCC: 0.032679 | Train loss: 0.9710 | Train acc: 51.57% | Val loss: 0.8259 | Val acc: 59.59% | LR: 0.000070
Epoch: 108 | MCC: 0.032322 | Train loss: 0.9702 | Train acc: 51.61% | Val loss: 0.8282 | Val acc: 59.47% | LR: 0.000067
Epoch: 109 | MCC: 0.034806 | Train loss: 0.9716 | Train acc: 51.53% | Val loss: 0.8295 | Val acc: 59.45% | LR: 0.000064
Epoch: 110 | MCC: 0.022263 | Train loss: 0.9722 | Train acc: 51.50% | Val loss: 0.8490 | Val acc: 59.29% | LR: 0.000061
Epoch: 111 | MCC: 0.026937 | Train loss: 0.9693 | Train acc: 51.66% | Val loss: 0.8302 | Val acc: 59.30% | LR: 0.000058
Epoch: 112 | MCC: 0.025812 | Train loss: 0.9702 | Train acc: 51.58% | Val loss: 0.8333 | Val acc: 59.30% | LR: 0.000055
Epoch: 113 | MCC: 0.029245 | Train loss: 0.9700 | Train acc: 51.63% | Val loss: 0.8275 | Val acc: 59.35% | LR: 0.000053
Epoch: 114 | MCC: 0.025216 | Train loss: 0.9704 | Train acc: 51.59% | Val loss: 0.8284 | Val acc: 59.27% | LR: 0.000050
Epoch: 115 | MCC: 0.026061 | Train loss: 0.9682 | Train acc: 51.72% | Val loss: 0.8281 | Val acc: 59.32% | LR: 0.000047
Epoch: 116 | MCC: 0.028779 | Train loss: 0.9713 | Train acc: 51.54% | Val loss: 0.8272 | Val acc: 59.32% | LR: 0.000045
Epoch: 117 | MCC: 0.030816 | Train loss: 0.9699 | Train acc: 51.61% | Val loss: 0.8294 | Val acc: 59.37% | LR: 0.000042
Epoch: 118 | MCC: 0.029944 | Train loss: 0.9674 | Train acc: 51.76% | Val loss: 0.8307 | Val acc: 59.32% | LR: 0.000040
Epoch: 119 | MCC: 0.029944 | Train loss: 0.9695 | Train acc: 51.64% | Val loss: 0.8374 | Val acc: 59.32% | LR: 0.000037
Epoch: 120 | MCC: 0.032207 | Train loss: 0.9678 | Train acc: 51.74% | Val loss: 0.8292 | Val acc: 59.37% | LR: 0.000035
Epoch: 121 | MCC: 0.029127 | Train loss: 0.9715 | Train acc: 51.54% | Val loss: 0.8295 | Val acc: 59.30% | LR: 0.000033
Epoch: 122 | MCC: 0.029932 | Train loss: 0.9700 | Train acc: 51.59% | Val loss: 0.8318 | Val acc: 59.45% | LR: 0.000031
Epoch: 123 | MCC: 0.019526 | Train loss: 0.9694 | Train acc: 51.65% | Val loss: 0.8282 | Val acc: 59.25% | LR: 0.000029
Epoch: 124 | MCC: 0.025224 | Train loss: 0.9691 | Train acc: 51.67% | Val loss: 0.8395 | Val acc: 59.35% | LR: 0.000027
Epoch: 125 | MCC: 0.016262 | Train loss: 0.9709 | Train acc: 51.57% | Val loss: 0.9052 | Val acc: 59.15% | LR: 0.000025
Epoch: 126 | MCC: 0.042723 | Train loss: 0.9697 | Train acc: 51.63% | Val loss: 0.8717 | Val acc: 59.32% | LR: 0.000023
Epoch: 127 | MCC: 0.011713 | Train loss: 0.9709 | Train acc: 51.55% | Val loss: 0.8449 | Val acc: 59.04% | LR: 0.000021
Epoch: 128 | MCC: 0.004426 | Train loss: 0.9684 | Train acc: 51.70% | Val loss: 0.8492 | Val acc: 58.83% | LR: 0.000019
Epoch: 129 | MCC: 0.024392 | Train loss: 0.9653 | Train acc: 51.85% | Val loss: 0.8915 | Val acc: 59.18% | LR: 0.000017
Epoch: 130 | MCC: 0.012766 | Train loss: 0.9715 | Train acc: 51.53% | Val loss: 2.4439 | Val acc: 59.06% | LR: 0.000016
Epoch: 131 | MCC: 0.010490 | Train loss: 0.9863 | Train acc: 51.72% | Val loss: 0.8767 | Val acc: 59.05% | LR: 0.000014
Epoch: 132 | MCC: 0.039616 | Train loss: 0.9821 | Train acc: 51.63% | Val loss: 0.8843 | Val acc: 59.24% | LR: 0.000013
Epoch: 133 | MCC: 0.017484 | Train loss: 0.9922 | Train acc: 51.73% | Val loss: 0.8829 | Val acc: 59.06% | LR: 0.000012
Epoch: 134 | MCC: 0.049632 | Train loss: 1.0001 | Train acc: 51.60% | Val loss: 0.8677 | Val acc: 59.16% | LR: 0.000010
Epoch: 135 | MCC: 0.019981 | Train loss: 0.9971 | Train acc: 51.50% | Val loss: 0.8443 | Val acc: 59.21% | LR: 0.000009

[I 2025-10-05 08:41:00,249] Trial 1 finished with value: 0.02645567338913679 and parameters: {'lr': 0.00038224520975047656, 'hidden_size': 33, 'dropout': 0.009763469901000577, 'weight_decay': 0.0054774780036185005}. Best is trial 0 with value: 0.02945748995989561.

Epoch: 000 | MCC: -0.018430 | Train loss: 0.9991 | Train acc: 50.11% | Val loss: 0.9729 | Val acc: 54.53% | LR: 0.001732
Epoch: 001 | MCC: -0.015602 | Train loss: 0.9916 | Train acc: 50.33% | Val loss: 0.9589 | Val acc: 54.36% | LR: 0.001731
Epoch: 002 | MCC: 0.013120 | Train loss: 0.9861 | Train acc: 50.90% | Val loss: 0.9346 | Val acc: 55.41% | LR: 0.001730
Epoch: 003 | MCC: 0.020117 | Train loss: 0.9883 | Train acc: 50.68% | Val loss: 0.9215 | Val acc: 55.80% | LR: 0.001729
Epoch: 004 | MCC: 0.021833 | Train loss: 0.9832 | Train acc: 50.92% | Val loss: 0.9074 | Val acc: 55.62% | LR: 0.001727
Epoch: 005 | MCC: 0.001805 | Train loss: 0.9829 | Train acc: 51.06% | Val loss: 0.9054 | Val acc: 55.60% | LR: 0.001725
Epoch: 006 | MCC: -0.009944 | Train loss: 0.9802 | Train acc: 51.01% | Val loss: 0.8966 | Val acc: 55.28% | LR: 0.001723
Epoch: 007 | MCC: -0.009419 | Train loss: 0.9778 | Train acc: 51.15% | Val loss: 0.8930 | Val acc: 55.37% | LR: 0.001720
Epoch: 008 | MCC: -0.007969 | Train loss: 0.9769 | Train acc: 50.84% | Val loss: 0.8693 | Val acc: 56.76% | LR: 0.001717
Epoch: 009 | MCC: -0.003449 | Train loss: 0.9750 | Train acc: 51.11% | Val loss: 0.8927 | Val acc: 55.71% | LR: 0.001713
Epoch: 010 | MCC: 0.010339 | Train loss: 0.9760 | Train acc: 51.91% | Val loss: 0.8720 | Val acc: 57.38% | LR: 0.001709
Epoch: 011 | MCC: -0.018664 | Train loss: 0.9774 | Train acc: 51.75% | Val loss: 0.8909 | Val acc: 55.66% | LR: 0.001705
Epoch: 012 | MCC: -0.001806 | Train loss: 0.9732 | Train acc: 51.91% | Val loss: 0.8772 | Val acc: 56.83% | LR: 0.001700
Epoch: 013 | MCC: 0.026984 | Train loss: 0.9727 | Train acc: 51.93% | Val loss: 0.8365 | Val acc: 59.52% | LR: 0.001695
Epoch: 014 | MCC: 0.019280 | Train loss: 0.9757 | Train acc: 51.76% | Val loss: 0.8393 | Val acc: 58.91% | LR: 0.001690
Epoch: 015 | MCC: 0.019751 | Train loss: 0.9761 | Train acc: 51.64% | Val loss: 0.8435 | Val acc: 58.64% | LR: 0.001684
Epoch: 016 | MCC: 0.005979 | Train loss: 0.9718 | Train acc: 51.87% | Val loss: 0.8796 | Val acc: 56.34% | LR: 0.001678
Epoch: 017 | MCC: 0.002343 | Train loss: 0.9688 | Train acc: 52.04% | Val loss: 0.8745 | Val acc: 56.56% | LR: 0.001671
Epoch: 018 | MCC: 0.010943 | Train loss: 0.9712 | Train acc: 51.96% | Val loss: 0.8606 | Val acc: 57.47% | LR: 0.001664
Epoch: 019 | MCC: 0.009526 | Train loss: 0.9703 | Train acc: 51.81% | Val loss: 0.8828 | Val acc: 56.30% | LR: 0.001657
Epoch: 020 | MCC: 0.004704 | Train loss: 0.9687 | Train acc: 51.95% | Val loss: 0.8705 | Val acc: 56.66% | LR: 0.001650
Epoch: 021 | MCC: 0.000334 | Train loss: 0.9686 | Train acc: 51.99% | Val loss: 0.8639 | Val acc: 57.42% | LR: 0.001642
Epoch: 022 | MCC: 0.025682 | Train loss: 0.9678 | Train acc: 51.91% | Val loss: 0.8162 | Val acc: 59.84% | LR: 0.001634
Epoch: 023 | MCC: 0.005616 | Train loss: 0.9680 | Train acc: 51.86% | Val loss: 0.8886 | Val acc: 55.88% | LR: 0.001625
Epoch: 024 | MCC: 0.010901 | Train loss: 0.9738 | Train acc: 51.95% | Val loss: 0.8407 | Val acc: 58.51% | LR: 0.001616
Epoch: 025 | MCC: 0.014405 | Train loss: 0.9741 | Train acc: 51.73% | Val loss: 0.8468 | Val acc: 58.39% | LR: 0.001607
Epoch: 026 | MCC: 0.007171 | Train loss: 0.9726 | Train acc: 51.75% | Val loss: 0.8954 | Val acc: 55.42% | LR: 0.001597
Epoch: 027 | MCC: -0.002974 | Train loss: 0.9756 | Train acc: 51.55% | Val loss: 0.9239 | Val acc: 54.86% | LR: 0.001587
Epoch: 028 | MCC: 0.034094 | Train loss: 0.9820 | Train acc: 51.73% | Val loss: 0.8808 | Val acc: 56.37% | LR: 0.001577
Epoch: 029 | MCC: 0.005923 | Train loss: 0.9811 | Train acc: 51.65% | Val loss: 0.9059 | Val acc: 55.17% | LR: 0.001567
Epoch: 030 | MCC: 0.016446 | Train loss: 0.9718 | Train acc: 52.15% | Val loss: 0.9105 | Val acc: 57.66% | LR: 0.001556
Epoch: 031 | MCC: 0.022909 | Train loss: 0.9715 | Train acc: 51.93% | Val loss: 0.8607 | Val acc: 57.87% | LR: 0.001545
Epoch: 032 | MCC: 0.011398 | Train loss: 0.9790 | Train acc: 51.66% | Val loss: 0.8404 | Val acc: 58.64% | LR: 0.001533
Epoch: 033 | MCC: 0.036114 | Train loss: 0.9735 | Train acc: 51.76% | Val loss: 0.8271 | Val acc: 59.42% | LR: 0.001522
Epoch: 034 | MCC: 0.021257 | Train loss: 0.9765 | Train acc: 51.59% | Val loss: 0.8474 | Val acc: 58.19% | LR: 0.001510
Epoch: 035 | MCC: 0.056683 | Train loss: 0.9799 | Train acc: 50.96% | Val loss: 0.8595 | Val acc: 58.11% | LR: 0.001497
Epoch: 036 | MCC: 0.030222 | Train loss: 0.9803 | Train acc: 51.41% | Val loss: 1.0546 | Val acc: 47.38% | LR: 0.001485
Epoch: 037 | MCC: -0.012207 | Train loss: 0.9812 | Train acc: 50.96% | Val loss: 1.0721 | Val acc: 45.10% | LR: 0.001472
Epoch: 038 | MCC: 0.039862 | Train loss: 0.9808 | Train acc: 51.15% | Val loss: 0.9782 | Val acc: 47.99% | LR: 0.001459
Epoch: 039 | MCC: 0.011976 | Train loss: 0.9759 | Train acc: 51.76% | Val loss: 0.9125 | Val acc: 55.63% | LR: 0.001446
Epoch: 040 | MCC: 0.037955 | Train loss: 0.9704 | Train acc: 51.91% | Val loss: 1.2967 | Val acc: 56.51% | LR: 0.001432
Epoch: 041 | MCC: 0.034234 | Train loss: 0.9720 | Train acc: 51.76% | Val loss: 1.0207 | Val acc: 56.88% | LR: 0.001418
Epoch: 042 | MCC: 0.018505 | Train loss: 0.9755 | Train acc: 51.55% | Val loss: 0.8728 | Val acc: 58.50% | LR: 0.001404
Epoch: 043 | MCC: 0.002563 | Train loss: 0.9754 | Train acc: 51.89% | Val loss: 0.9090 | Val acc: 55.61% | LR: 0.001390
Epoch: 044 | MCC: 0.004052 | Train loss: 0.9700 | Train acc: 51.85% | Val loss: 0.8994 | Val acc: 55.85% | LR: 0.001375
Epoch: 045 | MCC: 0.001277 | Train loss: 0.9699 | Train acc: 51.88% | Val loss: 0.9061 | Val acc: 55.05% | LR: 0.001361
Epoch: 046 | MCC: 0.004013 | Train loss: 0.9718 | Train acc: 51.79% | Val loss: 0.9112 | Val acc: 55.15% | LR: 0.001346
Epoch: 047 | MCC: 0.012480 | Train loss: 0.9708 | Train acc: 51.84% | Val loss: 0.8658 | Val acc: 57.70% | LR: 0.001330
Epoch: 048 | MCC: 0.045380 | Train loss: 0.9735 | Train acc: 51.67% | Val loss: 0.8558 | Val acc: 60.59% | LR: 0.001315
Epoch: 049 | MCC: 0.018882 | Train loss: 0.9753 | Train acc: 51.63% | Val loss: 0.8510 | Val acc: 59.84% | LR: 0.001299
Epoch: 050 | MCC: 0.019735 | Train loss: 0.9736 | Train acc: 51.66% | Val loss: 0.8592 | Val acc: 59.04% | LR: 0.001284
Epoch: 051 | MCC: -0.008136 | Train loss: 0.9776 | Train acc: 51.63% | Val loss: 0.9265 | Val acc: 55.85% | LR: 0.001268
Epoch: 052 | MCC: 0.005556 | Train loss: 0.9872 | Train acc: 51.04% | Val loss: 0.9032 | Val acc: 56.46% | LR: 0.001251
Epoch: 053 | MCC: 0.005233 | Train loss: 0.9801 | Train acc: 51.00% | Val loss: 0.8943 | Val acc: 57.10% | LR: 0.001235
Epoch: 054 | MCC: 0.025160 | Train loss: 0.9778 | Train acc: 51.01% | Val loss: 0.8444 | Val acc: 59.53% | LR: 0.001219
Epoch: 055 | MCC: 0.040343 | Train loss: 0.9780 | Train acc: 50.98% | Val loss: 0.8266 | Val acc: 60.94% | LR: 0.001202
Epoch: 056 | MCC: 0.031906 | Train loss: 0.9783 | Train acc: 51.20% | Val loss: 0.8517 | Val acc: 60.48% | LR: 0.001185
Epoch: 057 | MCC: 0.029809 | Train loss: 0.9782 | Train acc: 50.95% | Val loss: 0.8359 | Val acc: 60.33% | LR: 0.001168
Epoch: 058 | MCC: 0.035253 | Train loss: 0.9760 | Train acc: 51.35% | Val loss: 0.8335 | Val acc: 60.56% | LR: 0.001151
Epoch: 059 | MCC: 0.024962 | Train loss: 0.9759 | Train acc: 51.64% | Val loss: 0.8354 | Val acc: 60.40% | LR: 0.001134
Epoch: 060 | MCC: 0.006865 | Train loss: 0.9761 | Train acc: 51.64% | Val loss: 0.8464 | Val acc: 58.18% | LR: 0.001117
Epoch: 061 | MCC: -0.001786 | Train loss: 0.9745 | Train acc: 51.79% | Val loss: 0.8694 | Val acc: 56.15% | LR: 0.001099
Epoch: 062 | MCC: 0.006587 | Train loss: 0.9732 | Train acc: 51.95% | Val loss: 0.8579 | Val acc: 57.68% | LR: 0.001082
Epoch: 063 | MCC: 0.009769 | Train loss: 0.9709 | Train acc: 51.97% | Val loss: 0.9214 | Val acc: 55.18% | LR: 0.001064
Epoch: 064 | MCC: -0.033933 | Train loss: 0.9764 | Train acc: 51.72% | Val loss: 0.9350 | Val acc: 54.40% | LR: 0.001046
Epoch: 065 | MCC: 0.014475 | Train loss: 0.9783 | Train acc: 51.09% | Val loss: 0.9082 | Val acc: 55.63% | LR: 0.001029
Epoch: 066 | MCC: -0.019441 | Train loss: 0.9760 | Train acc: 51.24% | Val loss: 0.9038 | Val acc: 55.23% | LR: 0.001011
Epoch: 067 | MCC: -0.035723 | Train loss: 0.9740 | Train acc: 51.13% | Val loss: 0.9186 | Val acc: 54.77% | LR: 0.000993
Epoch: 068 | MCC: 0.031259 | Train loss: 0.9713 | Train acc: 51.83% | Val loss: 0.8911 | Val acc: 56.73% | LR: 0.000975
Epoch: 069 | MCC: 0.019686 | Train loss: 0.9756 | Train acc: 51.38% | Val loss: 0.9048 | Val acc: 56.52% | LR: 0.000957
Epoch: 070 | MCC: 0.007800 | Train loss: 0.9769 | Train acc: 51.75% | Val loss: 0.8878 | Val acc: 56.30% | LR: 0.000939
Epoch: 071 | MCC: 0.023738 | Train loss: 0.9744 | Train acc: 51.83% | Val loss: 0.9609 | Val acc: 52.57% | LR: 0.000921
Epoch: 072 | MCC: -0.010016 | Train loss: 0.9715 | Train acc: 51.92% | Val loss: 1.1061 | Val acc: 53.04% | LR: 0.000903
Epoch: 073 | MCC: -0.016309 | Train loss: 0.9717 | Train acc: 51.79% | Val loss: 0.9517 | Val acc: 53.16% | LR: 0.000885
Epoch: 074 | MCC: -0.007610 | Train loss: 0.9712 | Train acc: 51.93% | Val loss: 0.9288 | Val acc: 55.17% | LR: 0.000867
Epoch: 075 | MCC: -0.006347 | Train loss: 0.9713 | Train acc: 51.89% | Val loss: 0.9273 | Val acc: 54.79% | LR: 0.000848
Epoch: 076 | MCC: -0.017681 | Train loss: 0.9690 | Train acc: 51.98% | Val loss: 0.9637 | Val acc: 53.74% | LR: 0.000830
Epoch: 077 | MCC: -0.013223 | Train loss: 0.9691 | Train acc: 51.94% | Val loss: 0.9611 | Val acc: 54.14% | LR: 0.000812
Epoch: 078 | MCC: -0.004783 | Train loss: 0.9694 | Train acc: 51.93% | Val loss: 0.9329 | Val acc: 54.69% | LR: 0.000794
Epoch: 079 | MCC: -0.006903 | Train loss: 0.9694 | Train acc: 51.93% | Val loss: 0.9357 | Val acc: 54.83% | LR: 0.000776
Epoch: 080 | MCC: -0.012382 | Train loss: 0.9695 | Train acc: 51.80% | Val loss: 0.9452 | Val acc: 53.79% | LR: 0.000758
Epoch: 081 | MCC: -0.007750 | Train loss: 0.9716 | Train acc: 51.89% | Val loss: 0.9421 | Val acc: 54.45% | LR: 0.000740
Epoch: 082 | MCC: 0.006045 | Train loss: 0.9691 | Train acc: 51.93% | Val loss: 0.9148 | Val acc: 56.04% | LR: 0.000722
Epoch: 083 | MCC: -0.019042 | Train loss: 0.9691 | Train acc: 51.92% | Val loss: 0.9492 | Val acc: 53.38% | LR: 0.000704
Epoch: 084 | MCC: -0.000654 | Train loss: 0.9689 | Train acc: 51.95% | Val loss: 0.9170 | Val acc: 56.27% | LR: 0.000687
Epoch: 085 | MCC: -0.012851 | Train loss: 0.9676 | Train acc: 52.00% | Val loss: 0.9780 | Val acc: 53.57% | LR: 0.000669
Epoch: 086 | MCC: 0.009814 | Train loss: 0.9700 | Train acc: 51.83% | Val loss: 0.9141 | Val acc: 56.15% | LR: 0.000651
Epoch: 087 | MCC: -0.032045 | Train loss: 0.9680 | Train acc: 51.96% | Val loss: 1.0386 | Val acc: 53.08% | LR: 0.000634
Epoch: 088 | MCC: -0.018781 | Train loss: 0.9689 | Train acc: 51.90% | Val loss: 0.9433 | Val acc: 54.25% | LR: 0.000616
Epoch: 089 | MCC: -0.002672 | Train loss: 0.9666 | Train acc: 52.04% | Val loss: 0.9301 | Val acc: 55.89% | LR: 0.000599
Epoch: 090 | MCC: 0.006810 | Train loss: 0.9669 | Train acc: 51.99% | Val loss: 0.9140 | Val acc: 56.46% | LR: 0.000582
Epoch: 091 | MCC: -0.010106 | Train loss: 0.9646 | Train acc: 52.11% | Val loss: 0.9290 | Val acc: 54.51% | LR: 0.000565
Epoch: 092 | MCC: 0.008124 | Train loss: 0.9653 | Train acc: 52.01% | Val loss: 0.8994 | Val acc: 56.47% | LR: 0.000548
Epoch: 093 | MCC: 0.008838 | Train loss: 0.9661 | Train acc: 51.97% | Val loss: 0.8942 | Val acc: 56.47% | LR: 0.000531
Epoch: 094 | MCC: -0.011664 | Train loss: 0.9657 | Train acc: 52.06% | Val loss: 0.9314 | Val acc: 54.21% | LR: 0.000514
Epoch: 095 | MCC: 0.000688 | Train loss: 0.9646 | Train acc: 52.08% | Val loss: 0.9298 | Val acc: 55.15% | LR: 0.000498
Epoch: 096 | MCC: -0.001557 | Train loss: 0.9674 | Train acc: 52.19% | Val loss: 0.9050 | Val acc: 55.44% | LR: 0.000482

[I 2025-10-05 08:42:22,309] Trial 2 finished with value: -0.0006134707946330309 and parameters: {'lr': 0.0017320812095012225, 'hidden_size': 59, 'dropout': 0.2542416744623671, 'weight_decay': 0.0006199253726910866}. Best is trial 0 with value: 0.02945748995989561.

Epoch: 000 | MCC: 0.005049 | Train loss: 1.0144 | Train acc: 50.17% | Val loss: 0.9885 | Val acc: 55.28% | LR: 0.000230
Epoch: 001 | MCC: 0.009331 | Train loss: 0.9984 | Train acc: 50.86% | Val loss: 0.9846 | Val acc: 55.48% | LR: 0.000230
Epoch: 002 | MCC: 0.019125 | Train loss: 0.9954 | Train acc: 50.87% | Val loss: 0.9738 | Val acc: 54.81% | LR: 0.000230
Epoch: 003 | MCC: 0.029300 | Train loss: 0.9911 | Train acc: 50.89% | Val loss: 0.9635 | Val acc: 55.11% | LR: 0.000229
Epoch: 004 | MCC: 0.031479 | Train loss: 0.9907 | Train acc: 50.97% | Val loss: 0.9555 | Val acc: 55.41% | LR: 0.000229
Epoch: 005 | MCC: 0.029149 | Train loss: 0.9908 | Train acc: 51.33% | Val loss: 0.9484 | Val acc: 55.23% | LR: 0.000229
Epoch: 006 | MCC: 0.023877 | Train loss: 0.9909 | Train acc: 51.58% | Val loss: 0.9463 | Val acc: 55.03% | LR: 0.000229
Epoch: 007 | MCC: 0.020049 | Train loss: 0.9833 | Train acc: 51.53% | Val loss: 0.9472 | Val acc: 55.10% | LR: 0.000228
Epoch: 008 | MCC: 0.019807 | Train loss: 0.9864 | Train acc: 51.29% | Val loss: 0.9399 | Val acc: 55.18% | LR: 0.000228
Epoch: 009 | MCC: 0.017543 | Train loss: 0.9792 | Train acc: 51.68% | Val loss: 0.9352 | Val acc: 55.30% | LR: 0.000227
Epoch: 010 | MCC: 0.017242 | Train loss: 0.9794 | Train acc: 51.47% | Val loss: 0.9332 | Val acc: 55.36% | LR: 0.000227
Epoch: 011 | MCC: 0.023057 | Train loss: 0.9835 | Train acc: 51.55% | Val loss: 0.9486 | Val acc: 55.84% | LR: 0.000226
Epoch: 012 | MCC: 0.023239 | Train loss: 0.9863 | Train acc: 51.52% | Val loss: 0.9194 | Val acc: 56.68% | LR: 0.000226
Epoch: 013 | MCC: 0.010688 | Train loss: 0.9800 | Train acc: 51.54% | Val loss: 0.9672 | Val acc: 55.71% | LR: 0.000225
Epoch: 014 | MCC: 0.007289 | Train loss: 0.9815 | Train acc: 51.38% | Val loss: 1.0234 | Val acc: 54.96% | LR: 0.000224
Epoch: 015 | MCC: 0.003794 | Train loss: 0.9860 | Train acc: 51.56% | Val loss: 1.0799 | Val acc: 54.70% | LR: 0.000223
Epoch: 016 | MCC: 0.023660 | Train loss: 0.9870 | Train acc: 51.57% | Val loss: 0.9390 | Val acc: 55.72% | LR: 0.000223
Epoch: 017 | MCC: 0.019980 | Train loss: 0.9834 | Train acc: 51.41% | Val loss: 0.9617 | Val acc: 55.30% | LR: 0.000222
Epoch: 018 | MCC: 0.022898 | Train loss: 0.9859 | Train acc: 51.45% | Val loss: 0.9412 | Val acc: 55.35% | LR: 0.000221
Epoch: 019 | MCC: 0.025907 | Train loss: 0.9798 | Train acc: 51.42% | Val loss: 0.9410 | Val acc: 55.43% | LR: 0.000220
Epoch: 020 | MCC: 0.025629 | Train loss: 0.9812 | Train acc: 51.61% | Val loss: 0.9419 | Val acc: 55.57% | LR: 0.000219
Epoch: 021 | MCC: 0.044211 | Train loss: 0.9913 | Train acc: 51.51% | Val loss: 0.9369 | Val acc: 56.32% | LR: 0.000218
Epoch: 022 | MCC: 0.037265 | Train loss: 0.9836 | Train acc: 51.43% | Val loss: 0.9349 | Val acc: 56.18% | LR: 0.000217
Epoch: 023 | MCC: 0.040352 | Train loss: 0.9768 | Train acc: 51.49% | Val loss: 0.9468 | Val acc: 56.30% | LR: 0.000216
Epoch: 024 | MCC: 0.035137 | Train loss: 0.9773 | Train acc: 51.44% | Val loss: 0.9251 | Val acc: 56.03% | LR: 0.000214
Epoch: 025 | MCC: 0.026772 | Train loss: 0.9919 | Train acc: 51.55% | Val loss: 0.9162 | Val acc: 55.89% | LR: 0.000213
Epoch: 026 | MCC: 0.035457 | Train loss: 0.9783 | Train acc: 51.51% | Val loss: 0.9123 | Val acc: 55.95% | LR: 0.000212
Epoch: 027 | MCC: 0.036214 | Train loss: 0.9830 | Train acc: 51.52% | Val loss: 0.9239 | Val acc: 56.06% | LR: 0.000211
Epoch: 028 | MCC: 0.037027 | Train loss: 0.9880 | Train acc: 51.61% | Val loss: 0.9114 | Val acc: 56.08% | LR: 0.000209
Epoch: 029 | MCC: 0.027072 | Train loss: 0.9783 | Train acc: 51.50% | Val loss: 0.9064 | Val acc: 55.89% | LR: 0.000208
Epoch: 030 | MCC: 0.036166 | Train loss: 0.9771 | Train acc: 51.54% | Val loss: 0.9250 | Val acc: 55.83% | LR: 0.000207
Epoch: 031 | MCC: 0.046459 | Train loss: 0.9860 | Train acc: 51.64% | Val loss: 0.9236 | Val acc: 56.32% | LR: 0.000205
Epoch: 032 | MCC: 0.046986 | Train loss: 0.9787 | Train acc: 51.62% | Val loss: 0.9206 | Val acc: 56.32% | LR: 0.000204
Epoch: 033 | MCC: 0.040411 | Train loss: 0.9881 | Train acc: 51.55% | Val loss: 0.9422 | Val acc: 56.15% | LR: 0.000202
Epoch: 034 | MCC: 0.036559 | Train loss: 0.9879 | Train acc: 51.55% | Val loss: 0.9088 | Val acc: 56.13% | LR: 0.000200
Epoch: 035 | MCC: 0.036376 | Train loss: 0.9835 | Train acc: 51.41% | Val loss: 0.9069 | Val acc: 56.09% | LR: 0.000199
Epoch: 036 | MCC: 0.029343 | Train loss: 0.9743 | Train acc: 51.56% | Val loss: 0.9052 | Val acc: 55.94% | LR: 0.000197
Epoch: 037 | MCC: 0.024980 | Train loss: 0.9786 | Train acc: 51.52% | Val loss: 0.9023 | Val acc: 55.92% | LR: 0.000195
Epoch: 038 | MCC: 0.026703 | Train loss: 0.9831 | Train acc: 51.49% | Val loss: 0.9075 | Val acc: 55.91% | LR: 0.000194
Epoch: 039 | MCC: 0.027446 | Train loss: 0.9807 | Train acc: 51.56% | Val loss: 0.9044 | Val acc: 55.91% | LR: 0.000192
Epoch: 040 | MCC: 0.022484 | Train loss: 0.9803 | Train acc: 51.53% | Val loss: 0.9034 | Val acc: 55.75% | LR: 0.000190
Epoch: 041 | MCC: 0.036181 | Train loss: 0.9838 | Train acc: 51.38% | Val loss: 0.9093 | Val acc: 56.08% | LR: 0.000188
Epoch: 042 | MCC: 0.039539 | Train loss: 0.9772 | Train acc: 51.59% | Val loss: 0.9067 | Val acc: 56.32% | LR: 0.000186
Epoch: 043 | MCC: 0.036284 | Train loss: 0.9817 | Train acc: 51.47% | Val loss: 0.9835 | Val acc: 56.09% | LR: 0.000185
Epoch: 044 | MCC: 0.035013 | Train loss: 1.0100 | Train acc: 51.44% | Val loss: 0.9062 | Val acc: 56.25% | LR: 0.000183
Epoch: 045 | MCC: 0.032043 | Train loss: 0.9744 | Train acc: 51.51% | Val loss: 0.9061 | Val acc: 56.00% | LR: 0.000181
Epoch: 046 | MCC: 0.032460 | Train loss: 0.9739 | Train acc: 51.48% | Val loss: 0.9006 | Val acc: 55.95% | LR: 0.000179
Epoch: 047 | MCC: 0.033330 | Train loss: 0.9756 | Train acc: 51.42% | Val loss: 0.9043 | Val acc: 56.03% | LR: 0.000177
Epoch: 048 | MCC: 0.035137 | Train loss: 0.9746 | Train acc: 51.47% | Val loss: 0.9091 | Val acc: 56.13% | LR: 0.000175
Epoch: 049 | MCC: 0.039949 | Train loss: 0.9751 | Train acc: 51.42% | Val loss: 0.9092 | Val acc: 56.13% | LR: 0.000173
Epoch: 050 | MCC: 0.037396 | Train loss: 0.9760 | Train acc: 51.49% | Val loss: 0.9147 | Val acc: 55.87% | LR: 0.000171
Epoch: 051 | MCC: 0.032386 | Train loss: 0.9728 | Train acc: 51.53% | Val loss: 0.9179 | Val acc: 55.64% | LR: 0.000168
Epoch: 052 | MCC: 0.035665 | Train loss: 0.9733 | Train acc: 51.46% | Val loss: 0.9447 | Val acc: 56.32% | LR: 0.000166
Epoch: 053 | MCC: 0.036012 | Train loss: 0.9742 | Train acc: 51.52% | Val loss: 0.9041 | Val acc: 56.58% | LR: 0.000164
Epoch: 054 | MCC: 0.029126 | Train loss: 0.9804 | Train acc: 51.45% | Val loss: 0.9061 | Val acc: 56.11% | LR: 0.000162
Epoch: 055 | MCC: 0.028320 | Train loss: 0.9741 | Train acc: 51.58% | Val loss: 0.9030 | Val acc: 55.98% | LR: 0.000160
Epoch: 056 | MCC: 0.027217 | Train loss: 0.9749 | Train acc: 51.49% | Val loss: 0.9070 | Val acc: 55.97% | LR: 0.000158
Epoch: 057 | MCC: 0.027319 | Train loss: 0.9723 | Train acc: 51.58% | Val loss: 0.9105 | Val acc: 55.91% | LR: 0.000155
Epoch: 058 | MCC: 0.029835 | Train loss: 0.9716 | Train acc: 51.64% | Val loss: 0.9029 | Val acc: 55.92% | LR: 0.000153
Epoch: 059 | MCC: 0.026379 | Train loss: 0.9720 | Train acc: 51.61% | Val loss: 0.9006 | Val acc: 55.92% | LR: 0.000151
Epoch: 060 | MCC: 0.028626 | Train loss: 0.9730 | Train acc: 51.58% | Val loss: 0.9012 | Val acc: 56.00% | LR: 0.000148
Epoch: 061 | MCC: 0.025022 | Train loss: 0.9731 | Train acc: 51.52% | Val loss: 0.9024 | Val acc: 55.82% | LR: 0.000146
Epoch: 062 | MCC: 0.027507 | Train loss: 0.9736 | Train acc: 51.55% | Val loss: 0.9116 | Val acc: 55.92% | LR: 0.000144
Epoch: 063 | MCC: 0.027514 | Train loss: 0.9723 | Train acc: 51.53% | Val loss: 0.9063 | Val acc: 55.98% | LR: 0.000142
Epoch: 064 | MCC: 0.027261 | Train loss: 0.9721 | Train acc: 51.54% | Val loss: 0.9032 | Val acc: 55.89% | LR: 0.000139
Epoch: 065 | MCC: 0.027520 | Train loss: 0.9716 | Train acc: 51.60% | Val loss: 0.9028 | Val acc: 56.02% | LR: 0.000137
Epoch: 066 | MCC: 0.027632 | Train loss: 0.9720 | Train acc: 51.55% | Val loss: 0.9078 | Val acc: 55.99% | LR: 0.000134
Epoch: 067 | MCC: 0.026486 | Train loss: 0.9714 | Train acc: 51.64% | Val loss: 0.9048 | Val acc: 55.94% | LR: 0.000132
Epoch: 068 | MCC: 0.024570 | Train loss: 1.0225 | Train acc: 51.55% | Val loss: 0.9053 | Val acc: 55.92% | LR: 0.000130
Epoch: 069 | MCC: 0.026083 | Train loss: 0.9771 | Train acc: 51.65% | Val loss: 0.9050 | Val acc: 56.03% | LR: 0.000127
Epoch: 070 | MCC: 0.024940 | Train loss: 0.9772 | Train acc: 51.52% | Val loss: 0.9049 | Val acc: 55.93% | LR: 0.000125
Epoch: 071 | MCC: 0.023581 | Train loss: 0.9710 | Train acc: 51.56% | Val loss: 0.9060 | Val acc: 55.79% | LR: 0.000123
Epoch: 072 | MCC: 0.029421 | Train loss: 0.9705 | Train acc: 51.51% | Val loss: 0.9922 | Val acc: 56.10% | LR: 0.000120
Epoch: 073 | MCC: 0.024510 | Train loss: 0.9722 | Train acc: 51.49% | Val loss: 0.9020 | Val acc: 56.06% | LR: 0.000118
Epoch: 074 | MCC: 0.029480 | Train loss: 0.9767 | Train acc: 51.46% | Val loss: 0.9053 | Val acc: 56.10% | LR: 0.000115
Epoch: 075 | MCC: 0.025320 | Train loss: 0.9756 | Train acc: 51.54% | Val loss: 0.9041 | Val acc: 55.89% | LR: 0.000113
Epoch: 076 | MCC: 0.027004 | Train loss: 0.9834 | Train acc: 51.59% | Val loss: 0.9015 | Val acc: 56.00% | LR: 0.000111
Epoch: 077 | MCC: 0.029202 | Train loss: 0.9722 | Train acc: 51.55% | Val loss: 0.9017 | Val acc: 56.11% | LR: 0.000108
Epoch: 078 | MCC: 0.029617 | Train loss: 0.9729 | Train acc: 51.48% | Val loss: 0.9010 | Val acc: 56.14% | LR: 0.000106
Epoch: 079 | MCC: 0.023686 | Train loss: 0.9702 | Train acc: 51.61% | Val loss: 0.9025 | Val acc: 55.90% | LR: 0.000103
Epoch: 080 | MCC: 0.023355 | Train loss: 0.9726 | Train acc: 51.57% | Val loss: 0.9465 | Val acc: 55.89% | LR: 0.000101
Epoch: 081 | MCC: 0.025790 | Train loss: 0.9729 | Train acc: 51.52% | Val loss: 0.9196 | Val acc: 56.04% | LR: 0.000099
Epoch: 082 | MCC: 0.032078 | Train loss: 0.9725 | Train acc: 51.57% | Val loss: 0.9066 | Val acc: 55.99% | LR: 0.000096
Epoch: 083 | MCC: 0.028035 | Train loss: 0.9731 | Train acc: 51.48% | Val loss: 0.9146 | Val acc: 56.05% | LR: 0.000094
Epoch: 084 | MCC: 0.023110 | Train loss: 0.9730 | Train acc: 51.46% | Val loss: 0.9064 | Val acc: 55.75% | LR: 0.000092
Epoch: 085 | MCC: 0.023888 | Train loss: 0.9714 | Train acc: 51.51% | Val loss: 0.9070 | Val acc: 55.73% | LR: 0.000089
Epoch: 086 | MCC: 0.025979 | Train loss: 0.9742 | Train acc: 51.43% | Val loss: 0.9052 | Val acc: 55.92% | LR: 0.000087
Epoch: 087 | MCC: 0.033769 | Train loss: 0.9705 | Train acc: 51.62% | Val loss: 0.9113 | Val acc: 56.06% | LR: 0.000085
Epoch: 088 | MCC: 0.029611 | Train loss: 0.9754 | Train acc: 51.46% | Val loss: 0.9074 | Val acc: 56.04% | LR: 0.000082
Epoch: 089 | MCC: 0.030116 | Train loss: 0.9723 | Train acc: 51.48% | Val loss: 0.9096 | Val acc: 56.01% | LR: 0.000080
Epoch: 090 | MCC: 0.033396 | Train loss: 0.9726 | Train acc: 51.43% | Val loss: 0.9083 | Val acc: 55.98% | LR: 0.000078
Epoch: 091 | MCC: 0.032588 | Train loss: 0.9707 | Train acc: 51.58% | Val loss: 0.9067 | Val acc: 56.11% | LR: 0.000076
Epoch: 092 | MCC: 0.018007 | Train loss: 1.0041 | Train acc: 51.40% | Val loss: 0.9098 | Val acc: 55.64% | LR: 0.000073
Epoch: 093 | MCC: 0.025329 | Train loss: 0.9713 | Train acc: 51.62% | Val loss: 0.9037 | Val acc: 56.06% | LR: 0.000071
Epoch: 094 | MCC: 0.026382 | Train loss: 0.9698 | Train acc: 51.59% | Val loss: 0.9011 | Val acc: 56.13% | LR: 0.000069
Epoch: 095 | MCC: 0.027438 | Train loss: 0.9896 | Train acc: 51.37% | Val loss: 0.9053 | Val acc: 56.17% | LR: 0.000067
Epoch: 096 | MCC: 0.026308 | Train loss: 0.9708 | Train acc: 51.53% | Val loss: 0.9087 | Val acc: 56.13% | LR: 0.000065
Epoch: 097 | MCC: 0.015709 | Train loss: 0.9721 | Train acc: 51.55% | Val loss: 0.9091 | Val acc: 55.82% | LR: 0.000062
Epoch: 098 | MCC: 0.017457 | Train loss: 0.9716 | Train acc: 51.47% | Val loss: 0.9033 | Val acc: 56.01% | LR: 0.000060
Epoch: 099 | MCC: 0.020040 | Train loss: 0.9717 | Train acc: 51.54% | Val loss: 0.9028 | Val acc: 56.09% | LR: 0.000058
Epoch: 100 | MCC: 0.017319 | Train loss: 0.9712 | Train acc: 51.55% | Val loss: 0.9742 | Val acc: 56.15% | LR: 0.000056
Epoch: 101 | MCC: 0.016456 | Train loss: 0.9724 | Train acc: 51.58% | Val loss: 0.9053 | Val acc: 55.92% | LR: 0.000054
Epoch: 102 | MCC: 0.030399 | Train loss: 0.9697 | Train acc: 51.55% | Val loss: 0.8998 | Val acc: 56.26% | LR: 0.000052
Epoch: 103 | MCC: 0.019543 | Train loss: 0.9713 | Train acc: 51.52% | Val loss: 0.9041 | Val acc: 56.01% | LR: 0.000050
Epoch: 104 | MCC: 0.016180 | Train loss: 0.9710 | Train acc: 51.51% | Val loss: 0.9072 | Val acc: 56.05% | LR: 0.000048
Epoch: 105 | MCC: 0.014019 | Train loss: 0.9744 | Train acc: 51.40% | Val loss: 0.9061 | Val acc: 56.02% | LR: 0.000046
Epoch: 106 | MCC: 0.015526 | Train loss: 0.9702 | Train acc: 51.56% | Val loss: 0.9094 | Val acc: 56.06% | LR: 0.000044
Epoch: 107 | MCC: 0.020176 | Train loss: 0.9710 | Train acc: 51.53% | Val loss: 0.9113 | Val acc: 56.08% | LR: 0.000042
Epoch: 108 | MCC: 0.024321 | Train loss: 0.9711 | Train acc: 51.52% | Val loss: 0.9005 | Val acc: 56.14% | LR: 0.000041
Epoch: 109 | MCC: 0.019500 | Train loss: 0.9694 | Train acc: 51.53% | Val loss: 0.9033 | Val acc: 56.07% | LR: 0.000039
Epoch: 110 | MCC: 0.019170 | Train loss: 0.9705 | Train acc: 51.55% | Val loss: 0.9025 | Val acc: 56.12% | LR: 0.000037
Epoch: 111 | MCC: 0.018484 | Train loss: 0.9704 | Train acc: 51.54% | Val loss: 0.9080 | Val acc: 56.09% | LR: 0.000035
Epoch: 112 | MCC: 0.024629 | Train loss: 0.9728 | Train acc: 51.40% | Val loss: 0.9037 | Val acc: 56.17% | LR: 0.000034
Epoch: 113 | MCC: 0.018894 | Train loss: 0.9704 | Train acc: 51.48% | Val loss: 0.9116 | Val acc: 56.12% | LR: 0.000032
Epoch: 114 | MCC: 0.010790 | Train loss: 0.9685 | Train acc: 51.58% | Val loss: 0.9046 | Val acc: 55.85% | LR: 0.000030
Epoch: 115 | MCC: 0.020698 | Train loss: 0.9702 | Train acc: 51.48% | Val loss: 0.9124 | Val acc: 56.02% | LR: 0.000029
Epoch: 116 | MCC: 0.011932 | Train loss: 0.9734 | Train acc: 51.59% | Val loss: 0.9074 | Val acc: 55.88% | LR: 0.000027
Epoch: 117 | MCC: 0.014457 | Train loss: 0.9686 | Train acc: 51.62% | Val loss: 0.9094 | Val acc: 55.91% | LR: 0.000026
Epoch: 118 | MCC: 0.015968 | Train loss: 0.9699 | Train acc: 51.57% | Val loss: 0.9343 | Val acc: 55.95% | LR: 0.000024
Epoch: 119 | MCC: 0.014975 | Train loss: 0.9696 | Train acc: 51.55% | Val loss: 0.9063 | Val acc: 55.91% | LR: 0.000023
Epoch: 120 | MCC: 0.018621 | Train loss: 0.9721 | Train acc: 51.42% | Val loss: 0.9257 | Val acc: 55.97% | LR: 0.000021
Epoch: 121 | MCC: 0.012950 | Train loss: 0.9689 | Train acc: 51.64% | Val loss: 0.9043 | Val acc: 55.83% | LR: 0.000020
Epoch: 122 | MCC: 0.011138 | Train loss: 0.9701 | Train acc: 51.57% | Val loss: 0.9065 | Val acc: 55.75% | LR: 0.000019
Epoch: 123 | MCC: 0.013022 | Train loss: 0.9699 | Train acc: 51.54% | Val loss: 0.9400 | Val acc: 55.86% | LR: 0.000018
Epoch: 124 | MCC: 0.017855 | Train loss: 0.9688 | Train acc: 51.60% | Val loss: 0.9138 | Val acc: 55.94% | LR: 0.000016
Epoch: 125 | MCC: 0.012665 | Train loss: 0.9723 | Train acc: 51.42% | Val loss: 0.9062 | Val acc: 55.83% | LR: 0.000015
Epoch: 126 | MCC: 0.018324 | Train loss: 0.9703 | Train acc: 51.52% | Val loss: 0.9088 | Val acc: 55.99% | LR: 0.000014
Epoch: 127 | MCC: 0.012586 | Train loss: 0.9719 | Train acc: 51.39% | Val loss: 0.9058 | Val acc: 55.91% | LR: 0.000013
Epoch: 128 | MCC: 0.012200 | Train loss: 0.9703 | Train acc: 51.50% | Val loss: 0.9062 | Val acc: 55.86% | LR: 0.000012
Epoch: 129 | MCC: 0.016250 | Train loss: 0.9689 | Train acc: 51.57% | Val loss: 0.9215 | Val acc: 55.90% | LR: 0.000011
Epoch: 130 | MCC: 0.016388 | Train loss: 0.9710 | Train acc: 51.50% | Val loss: 0.9060 | Val acc: 55.90% | LR: 0.000010
Epoch: 131 | MCC: 0.011030 | Train loss: 0.9721 | Train acc: 51.42% | Val loss: 1.0382 | Val acc: 55.84% | LR: 0.000009
Epoch: 132 | MCC: 0.011195 | Train loss: 0.9733 | Train acc: 51.31% | Val loss: 1.0805 | Val acc: 55.81% | LR: 0.000008
Epoch: 133 | MCC: 0.017276 | Train loss: 0.9695 | Train acc: 51.63% | Val loss: 1.3535 | Val acc: 55.94% | LR: 0.000007
Epoch: 134 | MCC: 0.021797 | Train loss: 0.9701 | Train acc: 51.58% | Val loss: 0.9051 | Val acc: 56.03% | LR: 0.000007
Epoch: 135 | MCC: 0.017276 | Train loss: 0.9705 | Train acc: 51.50% | Val loss: 0.9062 | Val acc: 55.94% | LR: 0.000006
Epoch: 136 | MCC: 0.017055 | Train loss: 0.9726 | Train acc: 51.37% | Val loss: 0.9134 | Val acc: 55.97% | LR: 0.000005
Epoch: 137 | MCC: 0.017811 | Train loss: 0.9687 | Train acc: 51.58% | Val loss: 0.9036 | Val acc: 56.02% | LR: 0.000005
Epoch: 138 | MCC: 0.011544 | Train loss: 0.9725 | Train acc: 51.45% | Val loss: 0.9132 | Val acc: 55.89% | LR: 0.000004
Epoch: 139 | MCC: 0.012246 | Train loss: 0.9719 | Train acc: 51.47% | Val loss: 0.9123 | Val acc: 55.91% | LR: 0.000004
Epoch: 140 | MCC: 0.016451 | Train loss: 0.9708 | Train acc: 51.50% | Val loss: 0.9043 | Val acc: 55.97% | LR: 0.000003
Epoch: 141 | MCC: 0.016948 | Train loss: 0.9719 | Train acc: 51.38% | Val loss: 0.9044 | Val acc: 55.99% | LR: 0.000003
Epoch: 142 | MCC: 0.022300 | Train loss: 0.9700 | Train acc: 51.52% | Val loss: 0.9107 | Val acc: 56.10% | LR: 0.000002
Epoch: 143 | MCC: 0.021397 | Train loss: 0.9703 | Train acc: 51.50% | Val loss: 0.9148 | Val acc: 56.05% | LR: 0.000002
Epoch: 144 | MCC: 0.021397 | Train loss: 0.9695 | Train acc: 51.53% | Val loss: 0.9218 | Val acc: 56.05% | LR: 0.000002
Epoch: 145 | MCC: 0.022094 | Train loss: 0.9686 | Train acc: 51.67% | Val loss: 0.9533 | Val acc: 56.08% | LR: 0.000001
Epoch: 146 | MCC: 0.022094 | Train loss: 0.9687 | Train acc: 51.63% | Val loss: 0.9897 | Val acc: 56.08% | LR: 0.000001
Epoch: 147 | MCC: 0.017441 | Train loss: 0.9716 | Train acc: 51.48% | Val loss: 0.9052 | Val acc: 56.02% | LR: 0.000001
Epoch: 148 | MCC: 0.017441 | Train loss: 0.9718 | Train acc: 51.48% | Val loss: 0.9052 | Val acc: 56.02% | LR: 0.000001
Epoch: 149 | MCC: 0.017441 | Train loss: 0.9708 | Train acc: 51.53% | Val loss: 0.9061 | Val acc: 56.02% | LR: 0.000001

[I 2025-10-05 08:44:57,609] Trial 3 finished with value: 0.017440524417907 and parameters: {'lr': 0.0002298185653414403, 'hidden_size': 100, 'dropout': 0.042152683276100444, 'weight_decay': 0.01923147535402457}. Best is trial 0 with value: 0.02945748995989561.

Epoch: 000 | MCC: 0.043043 | Train loss: 0.9982 | Train acc: 50.63% | Val loss: 0.9975 | Val acc: 54.52% | LR: 0.000167
Epoch: 001 | MCC: 0.035141 | Train loss: 0.9955 | Train acc: 51.02% | Val loss: 0.9922 | Val acc: 54.83% | LR: 0.000167
Epoch: 002 | MCC: 0.034960 | Train loss: 0.9929 | Train acc: 50.99% | Val loss: 0.9845 | Val acc: 54.73% | LR: 0.000167
Epoch: 003 | MCC: 0.034637 | Train loss: 0.9909 | Train acc: 50.81% | Val loss: 0.9750 | Val acc: 55.01% | LR: 0.000167
Epoch: 004 | MCC: 0.028289 | Train loss: 0.9859 | Train acc: 51.07% | Val loss: 0.9676 | Val acc: 54.91% | LR: 0.000167
Epoch: 005 | MCC: 0.035144 | Train loss: 0.9835 | Train acc: 51.00% | Val loss: 0.9596 | Val acc: 55.53% | LR: 0.000166
Epoch: 006 | MCC: 0.035772 | Train loss: 0.9848 | Train acc: 50.94% | Val loss: 0.9545 | Val acc: 55.52% | LR: 0.000166
Epoch: 007 | MCC: 0.035076 | Train loss: 0.9826 | Train acc: 51.01% | Val loss: 0.9479 | Val acc: 55.64% | LR: 0.000166
Epoch: 008 | MCC: 0.032455 | Train loss: 0.9810 | Train acc: 50.91% | Val loss: 0.9448 | Val acc: 55.39% | LR: 0.000165
Epoch: 009 | MCC: 0.029245 | Train loss: 0.9838 | Train acc: 50.84% | Val loss: 0.9432 | Val acc: 55.44% | LR: 0.000165
Epoch: 010 | MCC: 0.030102 | Train loss: 0.9818 | Train acc: 50.85% | Val loss: 0.9440 | Val acc: 55.49% | LR: 0.000165
Epoch: 011 | MCC: 0.024029 | Train loss: 0.9795 | Train acc: 50.99% | Val loss: 0.9365 | Val acc: 55.52% | LR: 0.000164
Epoch: 012 | MCC: 0.027986 | Train loss: 0.9785 | Train acc: 51.01% | Val loss: 0.9336 | Val acc: 55.77% | LR: 0.000164
Epoch: 013 | MCC: 0.023947 | Train loss: 0.9824 | Train acc: 50.88% | Val loss: 0.9310 | Val acc: 55.49% | LR: 0.000163
Epoch: 014 | MCC: 0.023041 | Train loss: 0.9802 | Train acc: 50.93% | Val loss: 0.9247 | Val acc: 55.76% | LR: 0.000163
Epoch: 015 | MCC: 0.018794 | Train loss: 0.9795 | Train acc: 50.97% | Val loss: 0.9237 | Val acc: 55.53% | LR: 0.000162
Epoch: 016 | MCC: 0.016715 | Train loss: 0.9789 | Train acc: 50.85% | Val loss: 0.9212 | Val acc: 55.41% | LR: 0.000162
Epoch: 017 | MCC: 0.011918 | Train loss: 0.9807 | Train acc: 50.83% | Val loss: 0.9196 | Val acc: 55.39% | LR: 0.000161
Epoch: 018 | MCC: 0.008450 | Train loss: 0.9815 | Train acc: 50.93% | Val loss: 0.9272 | Val acc: 55.08% | LR: 0.000160
Epoch: 019 | MCC: 0.011304 | Train loss: 0.9771 | Train acc: 51.01% | Val loss: 0.9156 | Val acc: 55.46% | LR: 0.000160
Epoch: 020 | MCC: 0.015670 | Train loss: 0.9770 | Train acc: 50.96% | Val loss: 0.9138 | Val acc: 55.92% | LR: 0.000159
Epoch: 021 | MCC: 0.014556 | Train loss: 0.9766 | Train acc: 50.91% | Val loss: 0.9118 | Val acc: 55.82% | LR: 0.000158
Epoch: 022 | MCC: 0.018401 | Train loss: 0.9776 | Train acc: 51.19% | Val loss: 0.9085 | Val acc: 55.98% | LR: 0.000158
Epoch: 023 | MCC: 0.017575 | Train loss: 0.9760 | Train acc: 51.58% | Val loss: 0.9070 | Val acc: 56.16% | LR: 0.000157
Epoch: 024 | MCC: 0.019648 | Train loss: 0.9783 | Train acc: 51.52% | Val loss: 0.9060 | Val acc: 56.19% | LR: 0.000156
Epoch: 025 | MCC: 0.018106 | Train loss: 0.9792 | Train acc: 51.57% | Val loss: 0.9024 | Val acc: 56.11% | LR: 0.000155
Epoch: 026 | MCC: 0.023115 | Train loss: 0.9779 | Train acc: 51.62% | Val loss: 0.8999 | Val acc: 56.48% | LR: 0.000154
Epoch: 027 | MCC: 0.021836 | Train loss: 0.9794 | Train acc: 51.65% | Val loss: 0.8998 | Val acc: 56.44% | LR: 0.000153
Epoch: 028 | MCC: 0.029285 | Train loss: 0.9767 | Train acc: 51.54% | Val loss: 0.8972 | Val acc: 56.75% | LR: 0.000152
Epoch: 029 | MCC: 0.030524 | Train loss: 0.9748 | Train acc: 51.67% | Val loss: 0.8937 | Val acc: 56.78% | LR: 0.000151
Epoch: 030 | MCC: 0.028907 | Train loss: 0.9738 | Train acc: 51.64% | Val loss: 0.8928 | Val acc: 56.79% | LR: 0.000150
Epoch: 031 | MCC: 0.034155 | Train loss: 0.9761 | Train acc: 51.46% | Val loss: 0.8901 | Val acc: 57.00% | LR: 0.000149
Epoch: 032 | MCC: 0.037011 | Train loss: 0.9734 | Train acc: 51.63% | Val loss: 0.8894 | Val acc: 57.26% | LR: 0.000148
Epoch: 033 | MCC: 0.042403 | Train loss: 0.9731 | Train acc: 51.60% | Val loss: 0.8862 | Val acc: 57.20% | LR: 0.000147
Epoch: 034 | MCC: 0.036581 | Train loss: 0.9779 | Train acc: 51.57% | Val loss: 0.8843 | Val acc: 57.13% | LR: 0.000146
Epoch: 035 | MCC: 0.038199 | Train loss: 0.9740 | Train acc: 51.67% | Val loss: 0.8829 | Val acc: 57.74% | LR: 0.000144
Epoch: 036 | MCC: 0.044310 | Train loss: 0.9725 | Train acc: 51.69% | Val loss: 0.8817 | Val acc: 57.98% | LR: 0.000143
Epoch: 037 | MCC: 0.059980 | Train loss: 0.9739 | Train acc: 51.60% | Val loss: 0.8777 | Val acc: 58.59% | LR: 0.000142
Epoch: 038 | MCC: 0.052815 | Train loss: 0.9719 | Train acc: 51.73% | Val loss: 0.8780 | Val acc: 58.11% | LR: 0.000141
Epoch: 039 | MCC: 0.046225 | Train loss: 0.9717 | Train acc: 51.72% | Val loss: 0.8728 | Val acc: 58.28% | LR: 0.000140
Epoch: 040 | MCC: 0.049278 | Train loss: 0.9747 | Train acc: 51.59% | Val loss: 0.8701 | Val acc: 58.71% | LR: 0.000138
Epoch: 041 | MCC: 0.036096 | Train loss: 0.9815 | Train acc: 51.56% | Val loss: 0.8685 | Val acc: 58.27% | LR: 0.000137
Epoch: 042 | MCC: 0.033916 | Train loss: 0.9759 | Train acc: 51.75% | Val loss: 0.8673 | Val acc: 57.91% | LR: 0.000136
Epoch: 043 | MCC: 0.038672 | Train loss: 0.9720 | Train acc: 51.74% | Val loss: 0.8635 | Val acc: 58.26% | LR: 0.000134
Epoch: 044 | MCC: 0.035111 | Train loss: 0.9731 | Train acc: 51.73% | Val loss: 0.8610 | Val acc: 57.94% | LR: 0.000133
Epoch: 045 | MCC: 0.039279 | Train loss: 1.1967 | Train acc: 51.76% | Val loss: 0.8583 | Val acc: 58.31% | LR: 0.000131
Epoch: 046 | MCC: 0.032682 | Train loss: 0.9712 | Train acc: 51.72% | Val loss: 0.8575 | Val acc: 57.99% | LR: 0.000130
Epoch: 047 | MCC: 0.043640 | Train loss: 0.9707 | Train acc: 51.70% | Val loss: 0.8553 | Val acc: 58.53% | LR: 0.000128
Epoch: 048 | MCC: 0.027035 | Train loss: 0.9696 | Train acc: 51.85% | Val loss: 0.8541 | Val acc: 58.36% | LR: 0.000127
Epoch: 049 | MCC: 0.022151 | Train loss: 0.9683 | Train acc: 51.86% | Val loss: 0.8580 | Val acc: 57.83% | LR: 0.000125
Epoch: 050 | MCC: 0.019695 | Train loss: 1.0131 | Train acc: 51.86% | Val loss: 0.8880 | Val acc: 58.12% | LR: 0.000124
Epoch: 051 | MCC: 0.027641 | Train loss: 1.0114 | Train acc: 51.85% | Val loss: 0.8664 | Val acc: 57.11% | LR: 0.000122
Epoch: 052 | MCC: 0.038183 | Train loss: 0.9897 | Train acc: 51.62% | Val loss: 0.8763 | Val acc: 56.44% | LR: 0.000121
Epoch: 053 | MCC: 0.038261 | Train loss: 0.9760 | Train acc: 51.78% | Val loss: 0.8588 | Val acc: 58.35% | LR: 0.000119
Epoch: 054 | MCC: 0.031658 | Train loss: 0.9680 | Train acc: 51.93% | Val loss: 0.8544 | Val acc: 58.27% | LR: 0.000118
Epoch: 055 | MCC: 0.032174 | Train loss: 0.9696 | Train acc: 51.81% | Val loss: 0.8561 | Val acc: 58.31% | LR: 0.000116
Epoch: 056 | MCC: 0.031629 | Train loss: 0.9683 | Train acc: 52.00% | Val loss: 0.8541 | Val acc: 58.44% | LR: 0.000115
Epoch: 057 | MCC: 0.029562 | Train loss: 0.9750 | Train acc: 52.01% | Val loss: 0.8598 | Val acc: 58.29% | LR: 0.000113
Epoch: 058 | MCC: 0.030516 | Train loss: 0.9675 | Train acc: 52.01% | Val loss: 0.8572 | Val acc: 58.49% | LR: 0.000111
Epoch: 059 | MCC: 0.026165 | Train loss: 0.9691 | Train acc: 51.83% | Val loss: 0.8560 | Val acc: 58.62% | LR: 0.000110
Epoch: 060 | MCC: 0.024335 | Train loss: 0.9655 | Train acc: 52.05% | Val loss: 0.8538 | Val acc: 58.79% | LR: 0.000108
Epoch: 061 | MCC: 0.030251 | Train loss: 0.9653 | Train acc: 52.02% | Val loss: 0.8571 | Val acc: 58.79% | LR: 0.000106
Epoch: 062 | MCC: 0.033045 | Train loss: 0.9665 | Train acc: 51.94% | Val loss: 0.8526 | Val acc: 59.10% | LR: 0.000105
Epoch: 063 | MCC: 0.025568 | Train loss: 0.9646 | Train acc: 52.04% | Val loss: 0.8505 | Val acc: 58.81% | LR: 0.000103
Epoch: 064 | MCC: 0.028060 | Train loss: 0.9664 | Train acc: 52.00% | Val loss: 0.8475 | Val acc: 58.86% | LR: 0.000101
Epoch: 065 | MCC: 0.026568 | Train loss: 0.9687 | Train acc: 52.10% | Val loss: 0.8436 | Val acc: 59.05% | LR: 0.000100
Epoch: 066 | MCC: 0.025810 | Train loss: 0.9634 | Train acc: 52.10% | Val loss: 0.8415 | Val acc: 59.01% | LR: 0.000098
Epoch: 067 | MCC: 0.031560 | Train loss: 0.9637 | Train acc: 52.06% | Val loss: 0.8403 | Val acc: 59.18% | LR: 0.000096
Epoch: 068 | MCC: 0.032130 | Train loss: 0.9678 | Train acc: 52.02% | Val loss: 0.8392 | Val acc: 59.20% | LR: 0.000094
Epoch: 069 | MCC: 0.030448 | Train loss: 0.9715 | Train acc: 52.00% | Val loss: 0.8387 | Val acc: 58.98% | LR: 0.000093
Epoch: 070 | MCC: 0.026629 | Train loss: 0.9702 | Train acc: 51.99% | Val loss: 0.8468 | Val acc: 58.30% | LR: 0.000091
Epoch: 071 | MCC: 0.026943 | Train loss: 0.9658 | Train acc: 52.05% | Val loss: 0.8402 | Val acc: 58.69% | LR: 0.000089
Epoch: 072 | MCC: 0.028341 | Train loss: 0.9661 | Train acc: 52.10% | Val loss: 0.8357 | Val acc: 58.96% | LR: 0.000087
Epoch: 073 | MCC: 0.038496 | Train loss: 0.9641 | Train acc: 51.99% | Val loss: 0.8363 | Val acc: 59.62% | LR: 0.000086
Epoch: 074 | MCC: 0.027800 | Train loss: 0.9680 | Train acc: 52.04% | Val loss: 0.8396 | Val acc: 58.69% | LR: 0.000084
Epoch: 075 | MCC: 0.028382 | Train loss: 0.9596 | Train acc: 52.17% | Val loss: 0.8414 | Val acc: 58.62% | LR: 0.000082
Epoch: 076 | MCC: 0.029568 | Train loss: 0.9606 | Train acc: 52.09% | Val loss: 0.8344 | Val acc: 59.03% | LR: 0.000081
Epoch: 077 | MCC: 0.025179 | Train loss: 0.9610 | Train acc: 52.11% | Val loss: 0.8275 | Val acc: 59.18% | LR: 0.000079
Epoch: 078 | MCC: 0.026881 | Train loss: 0.9682 | Train acc: 51.98% | Val loss: 0.8277 | Val acc: 59.23% | LR: 0.000077
Epoch: 079 | MCC: 0.037326 | Train loss: 0.9615 | Train acc: 52.02% | Val loss: 0.8218 | Val acc: 59.76% | LR: 0.000075
Epoch: 080 | MCC: 0.038126 | Train loss: 0.9595 | Train acc: 52.14% | Val loss: 0.8252 | Val acc: 59.52% | LR: 0.000074
Epoch: 081 | MCC: 0.038267 | Train loss: 0.9622 | Train acc: 52.02% | Val loss: 0.8206 | Val acc: 59.67% | LR: 0.000072
Epoch: 082 | MCC: 0.042249 | Train loss: 0.9593 | Train acc: 52.16% | Val loss: 0.8220 | Val acc: 59.59% | LR: 0.000070
Epoch: 083 | MCC: 0.041598 | Train loss: 0.9593 | Train acc: 52.22% | Val loss: 0.8168 | Val acc: 59.96% | LR: 0.000068
Epoch: 084 | MCC: 0.038326 | Train loss: 0.9612 | Train acc: 52.07% | Val loss: 0.8210 | Val acc: 59.59% | LR: 0.000067
Epoch: 085 | MCC: 0.041642 | Train loss: 0.9623 | Train acc: 52.04% | Val loss: 0.8200 | Val acc: 59.64% | LR: 0.000065
Epoch: 086 | MCC: 0.033326 | Train loss: 0.9606 | Train acc: 52.13% | Val loss: 0.8219 | Val acc: 59.20% | LR: 0.000063
Epoch: 087 | MCC: 0.038430 | Train loss: 0.9589 | Train acc: 52.19% | Val loss: 0.8189 | Val acc: 59.49% | LR: 0.000062
Epoch: 088 | MCC: 0.036857 | Train loss: 0.9563 | Train acc: 52.32% | Val loss: 0.8179 | Val acc: 59.47% | LR: 0.000060
Epoch: 089 | MCC: 0.039097 | Train loss: 0.9596 | Train acc: 52.18% | Val loss: 0.8118 | Val acc: 59.96% | LR: 0.000058
Epoch: 090 | MCC: 0.037472 | Train loss: 0.9607 | Train acc: 52.09% | Val loss: 0.8182 | Val acc: 59.47% | LR: 0.000057
Epoch: 091 | MCC: 0.039765 | Train loss: 0.9618 | Train acc: 52.08% | Val loss: 0.8159 | Val acc: 59.54% | LR: 0.000055
Epoch: 092 | MCC: 0.037404 | Train loss: 0.9593 | Train acc: 52.18% | Val loss: 0.8162 | Val acc: 59.42% | LR: 0.000053
Epoch: 093 | MCC: 0.040183 | Train loss: 0.9573 | Train acc: 52.24% | Val loss: 0.8164 | Val acc: 59.54% | LR: 0.000052
Epoch: 094 | MCC: 0.036159 | Train loss: 0.9591 | Train acc: 52.16% | Val loss: 0.8138 | Val acc: 59.45% | LR: 0.000050
Epoch: 095 | MCC: 0.036095 | Train loss: 0.9599 | Train acc: 52.14% | Val loss: 0.8150 | Val acc: 59.40% | LR: 0.000049
Epoch: 096 | MCC: 0.038080 | Train loss: 0.9586 | Train acc: 52.23% | Val loss: 0.8151 | Val acc: 59.45% | LR: 0.000047
Epoch: 097 | MCC: 0.037240 | Train loss: 0.9586 | Train acc: 52.21% | Val loss: 0.8173 | Val acc: 59.45% | LR: 0.000046
Epoch: 098 | MCC: 0.041247 | Train loss: 0.9573 | Train acc: 52.24% | Val loss: 0.8166 | Val acc: 59.52% | LR: 0.000044
Epoch: 099 | MCC: 0.036393 | Train loss: 0.9574 | Train acc: 52.26% | Val loss: 0.8171 | Val acc: 59.37% | LR: 0.000042
Epoch: 100 | MCC: 0.042705 | Train loss: 0.9595 | Train acc: 52.13% | Val loss: 0.8162 | Val acc: 59.62% | LR: 0.000041
Epoch: 101 | MCC: 0.037179 | Train loss: 0.9580 | Train acc: 52.23% | Val loss: 0.8130 | Val acc: 59.47% | LR: 0.000040
Epoch: 102 | MCC: 0.038699 | Train loss: 0.9576 | Train acc: 52.21% | Val loss: 0.8143 | Val acc: 59.49% | LR: 0.000038
Epoch: 103 | MCC: 0.040358 | Train loss: 0.9592 | Train acc: 52.16% | Val loss: 0.8165 | Val acc: 59.52% | LR: 0.000037
Epoch: 104 | MCC: 0.037917 | Train loss: 0.9590 | Train acc: 52.17% | Val loss: 0.8163 | Val acc: 59.40% | LR: 0.000035
Epoch: 105 | MCC: 0.039591 | Train loss: 0.9588 | Train acc: 52.16% | Val loss: 0.8134 | Val acc: 59.67% | LR: 0.000034
Epoch: 106 | MCC: 0.037439 | Train loss: 0.9576 | Train acc: 52.23% | Val loss: 0.8170 | Val acc: 59.37% | LR: 0.000032
Epoch: 107 | MCC: 0.042787 | Train loss: 0.9575 | Train acc: 52.26% | Val loss: 0.8132 | Val acc: 59.69% | LR: 0.000031
Epoch: 108 | MCC: 0.040004 | Train loss: 0.9569 | Train acc: 52.28% | Val loss: 0.8141 | Val acc: 59.54% | LR: 0.000030
Epoch: 109 | MCC: 0.037831 | Train loss: 0.9562 | Train acc: 52.28% | Val loss: 0.8161 | Val acc: 59.40% | LR: 0.000028
Epoch: 110 | MCC: 0.038889 | Train loss: 0.9585 | Train acc: 52.21% | Val loss: 0.8144 | Val acc: 59.52% | LR: 0.000027
Epoch: 111 | MCC: 0.039033 | Train loss: 0.9596 | Train acc: 52.12% | Val loss: 0.8153 | Val acc: 59.47% | LR: 0.000026
Epoch: 112 | MCC: 0.039169 | Train loss: 0.9577 | Train acc: 52.24% | Val loss: 0.8141 | Val acc: 59.57% | LR: 0.000025
Epoch: 113 | MCC: 0.039494 | Train loss: 0.9610 | Train acc: 52.04% | Val loss: 0.8120 | Val acc: 59.64% | LR: 0.000023
Epoch: 114 | MCC: 0.042211 | Train loss: 0.9571 | Train acc: 52.24% | Val loss: 0.8144 | Val acc: 59.69% | LR: 0.000022
Epoch: 115 | MCC: 0.041626 | Train loss: 0.9590 | Train acc: 52.15% | Val loss: 0.8159 | Val acc: 59.57% | LR: 0.000021
Epoch: 116 | MCC: 0.039587 | Train loss: 0.9598 | Train acc: 52.11% | Val loss: 0.8170 | Val acc: 59.49% | LR: 0.000020
Epoch: 117 | MCC: 0.040289 | Train loss: 0.9579 | Train acc: 52.18% | Val loss: 0.8159 | Val acc: 59.54% | LR: 0.000019
Epoch: 118 | MCC: 0.040261 | Train loss: 0.9573 | Train acc: 52.24% | Val loss: 0.8159 | Val acc: 59.49% | LR: 0.000018
Epoch: 119 | MCC: 0.045496 | Train loss: 0.9560 | Train acc: 52.30% | Val loss: 0.8149 | Val acc: 59.81% | LR: 0.000017
Epoch: 120 | MCC: 0.040822 | Train loss: 0.9581 | Train acc: 52.20% | Val loss: 0.8139 | Val acc: 59.62% | LR: 0.000016
Epoch: 121 | MCC: 0.040961 | Train loss: 0.9584 | Train acc: 52.18% | Val loss: 0.8143 | Val acc: 59.64% | LR: 0.000015
Epoch: 122 | MCC: 0.044585 | Train loss: 0.9576 | Train acc: 52.23% | Val loss: 0.8147 | Val acc: 59.76% | LR: 0.000014
Epoch: 123 | MCC: 0.043910 | Train loss: 0.9564 | Train acc: 52.29% | Val loss: 0.8151 | Val acc: 59.71% | LR: 0.000013
Epoch: 124 | MCC: 0.041402 | Train loss: 0.9581 | Train acc: 52.20% | Val loss: 0.8155 | Val acc: 59.57% | LR: 0.000012
Epoch: 125 | MCC: 0.042544 | Train loss: 0.9545 | Train acc: 52.38% | Val loss: 0.8154 | Val acc: 59.64% | LR: 0.000011
Epoch: 126 | MCC: 0.042544 | Train loss: 0.9586 | Train acc: 52.21% | Val loss: 0.8151 | Val acc: 59.64% | LR: 0.000010
Epoch: 127 | MCC: 0.042544 | Train loss: 0.9568 | Train acc: 52.25% | Val loss: 0.8151 | Val acc: 59.64% | LR: 0.000010
Epoch: 128 | MCC: 0.041291 | Train loss: 0.9582 | Train acc: 52.20% | Val loss: 0.8136 | Val acc: 59.64% | LR: 0.000009
Epoch: 129 | MCC: 0.042298 | Train loss: 0.9598 | Train acc: 52.12% | Val loss: 0.8139 | Val acc: 59.69% | LR: 0.000008
Epoch: 130 | MCC: 0.042298 | Train loss: 0.9578 | Train acc: 52.22% | Val loss: 0.8140 | Val acc: 59.69% | LR: 0.000007
Epoch: 131 | MCC: 0.042161 | Train loss: 0.9578 | Train acc: 52.22% | Val loss: 0.8141 | Val acc: 59.67% | LR: 0.000007
Epoch: 132 | MCC: 0.042787 | Train loss: 0.9585 | Train acc: 52.18% | Val loss: 0.8144 | Val acc: 59.69% | LR: 0.000006
Epoch: 133 | MCC: 0.042703 | Train loss: 0.9570 | Train acc: 52.26% | Val loss: 0.8143 | Val acc: 59.69% | LR: 0.000006
Epoch: 134 | MCC: 0.044671 | Train loss: 0.9589 | Train acc: 52.16% | Val loss: 0.8146 | Val acc: 59.76% | LR: 0.000005
Epoch: 135 | MCC: 0.043306 | Train loss: 0.9598 | Train acc: 52.12% | Val loss: 0.8148 | Val acc: 59.69% | LR: 0.000005
Epoch: 136 | MCC: 0.041920 | Train loss: 0.9574 | Train acc: 52.25% | Val loss: 0.8140 | Val acc: 59.67% | LR: 0.000004
Epoch: 137 | MCC: 0.043306 | Train loss: 0.9565 | Train acc: 52.29% | Val loss: 0.8146 | Val acc: 59.69% | LR: 0.000004
Epoch: 138 | MCC: 0.041833 | Train loss: 0.9570 | Train acc: 52.26% | Val loss: 0.8138 | Val acc: 59.67% | LR: 0.000003
Epoch: 139 | MCC: 0.041806 | Train loss: 0.9566 | Train acc: 52.28% | Val loss: 0.8142 | Val acc: 59.64% | LR: 0.000003
Epoch: 140 | MCC: 0.041291 | Train loss: 0.9566 | Train acc: 52.27% | Val loss: 0.8137 | Val acc: 59.64% | LR: 0.000002
Epoch: 141 | MCC: 0.040554 | Train loss: 0.9595 | Train acc: 52.13% | Val loss: 0.8141 | Val acc: 59.59% | LR: 0.000002
Epoch: 142 | MCC: 0.041806 | Train loss: 0.9574 | Train acc: 52.24% | Val loss: 0.8142 | Val acc: 59.64% | LR: 0.000002
Epoch: 143 | MCC: 0.042432 | Train loss: 0.9548 | Train acc: 52.36% | Val loss: 0.8143 | Val acc: 59.67% | LR: 0.000002
Epoch: 144 | MCC: 0.042432 | Train loss: 0.9581 | Train acc: 52.20% | Val loss: 0.8144 | Val acc: 59.67% | LR: 0.000001
Epoch: 145 | MCC: 0.042432 | Train loss: 0.9571 | Train acc: 52.26% | Val loss: 0.8143 | Val acc: 59.67% | LR: 0.000001
Epoch: 146 | MCC: 0.042432 | Train loss: 0.9576 | Train acc: 52.23% | Val loss: 0.8144 | Val acc: 59.67% | LR: 0.000001
Epoch: 147 | MCC: 0.042432 | Train loss: 0.9559 | Train acc: 52.32% | Val loss: 0.8144 | Val acc: 59.67% | LR: 0.000001
Epoch: 148 | MCC: 0.042432 | Train loss: 0.9571 | Train acc: 52.26% | Val loss: 0.8144 | Val acc: 59.67% | LR: 0.000001
Epoch: 149 | MCC: 0.042432 | Train loss: 0.9575 | Train acc: 52.23% | Val loss: 0.8143 | Val acc: 59.67% | LR: 0.000001

[I 2025-10-05 08:47:31,605] Trial 4 finished with value: 0.04243219271302223 and parameters: {'lr': 0.0001669578157355315, 'hidden_size': 101, 'dropout': 0.4634999711327079, 'weight_decay': 0.00012734589694986186}. Best is trial 4 with value: 0.04243219271302223.

Epoch: 000 | MCC: 0.029557 | Train loss: 0.9965 | Train acc: 50.62% | Val loss: 0.9683 | Val acc: 54.99% | LR: 0.002016
Epoch: 001 | MCC: 0.022433 | Train loss: 0.9901 | Train acc: 50.96% | Val loss: 0.9364 | Val acc: 55.15% | LR: 0.002016
Epoch: 002 | MCC: 0.024822 | Train loss: 0.9860 | Train acc: 50.61% | Val loss: 0.9265 | Val acc: 55.63% | LR: 0.002015
Epoch: 003 | MCC: 0.026897 | Train loss: 1.0575 | Train acc: 51.40% | Val loss: 0.9182 | Val acc: 55.82% | LR: 0.002013
Epoch: 004 | MCC: 0.029405 | Train loss: 0.9803 | Train acc: 50.95% | Val loss: 0.9061 | Val acc: 56.14% | LR: 0.002011
Epoch: 005 | MCC: 0.023408 | Train loss: 0.9795 | Train acc: 50.91% | Val loss: 0.8975 | Val acc: 56.28% | LR: 0.002009
Epoch: 006 | MCC: 0.027092 | Train loss: 0.9798 | Train acc: 50.86% | Val loss: 0.8906 | Val acc: 56.51% | LR: 0.002006
Epoch: 007 | MCC: 0.030496 | Train loss: 0.9791 | Train acc: 51.03% | Val loss: 0.9074 | Val acc: 56.89% | LR: 0.002003
Epoch: 008 | MCC: 0.033359 | Train loss: 0.9786 | Train acc: 51.67% | Val loss: 0.9023 | Val acc: 57.15% | LR: 0.001999
Epoch: 009 | MCC: 0.035415 | Train loss: 0.9790 | Train acc: 51.78% | Val loss: 0.8825 | Val acc: 56.77% | LR: 0.001995
Epoch: 010 | MCC: 0.054918 | Train loss: 0.9778 | Train acc: 51.63% | Val loss: 0.8772 | Val acc: 58.31% | LR: 0.001990
Epoch: 011 | MCC: 0.042226 | Train loss: 0.9768 | Train acc: 51.68% | Val loss: 0.8701 | Val acc: 58.23% | LR: 0.001985
Epoch: 012 | MCC: 0.045966 | Train loss: 0.9752 | Train acc: 51.80% | Val loss: 0.8627 | Val acc: 58.51% | LR: 0.001980
Epoch: 013 | MCC: 0.040528 | Train loss: 0.9768 | Train acc: 51.70% | Val loss: 0.8663 | Val acc: 57.32% | LR: 0.001974
Epoch: 014 | MCC: 0.053694 | Train loss: 1.0617 | Train acc: 51.42% | Val loss: 0.8744 | Val acc: 57.59% | LR: 0.001967
Epoch: 015 | MCC: 0.024146 | Train loss: 0.9807 | Train acc: 51.35% | Val loss: 0.8651 | Val acc: 57.22% | LR: 0.001961
Epoch: 016 | MCC: 0.047819 | Train loss: 0.9771 | Train acc: 51.12% | Val loss: 0.8506 | Val acc: 58.20% | LR: 0.001953
Epoch: 017 | MCC: 0.024738 | Train loss: 0.9761 | Train acc: 51.21% | Val loss: 0.8731 | Val acc: 57.44% | LR: 0.001946
Epoch: 018 | MCC: 0.035640 | Train loss: 0.9786 | Train acc: 51.18% | Val loss: 0.8848 | Val acc: 58.00% | LR: 0.001938
Epoch: 019 | MCC: 0.049165 | Train loss: 0.9766 | Train acc: 51.30% | Val loss: 0.8514 | Val acc: 58.24% | LR: 0.001930
Epoch: 020 | MCC: 0.054734 | Train loss: 0.9766 | Train acc: 50.97% | Val loss: 0.8757 | Val acc: 57.11% | LR: 0.001921
Epoch: 021 | MCC: 0.048964 | Train loss: 0.9768 | Train acc: 51.77% | Val loss: 0.8629 | Val acc: 57.33% | LR: 0.001912
Epoch: 022 | MCC: 0.058617 | Train loss: 0.9758 | Train acc: 51.62% | Val loss: 0.8487 | Val acc: 58.80% | LR: 0.001902
Epoch: 023 | MCC: 0.053415 | Train loss: 0.9731 | Train acc: 51.74% | Val loss: 0.8473 | Val acc: 59.25% | LR: 0.001892
Epoch: 024 | MCC: 0.040362 | Train loss: 0.9831 | Train acc: 51.15% | Val loss: 0.8476 | Val acc: 58.29% | LR: 0.001882
Epoch: 025 | MCC: 0.043904 | Train loss: 0.9795 | Train acc: 50.90% | Val loss: 0.9282 | Val acc: 53.72% | LR: 0.001871
Epoch: 026 | MCC: 0.057318 | Train loss: 0.9781 | Train acc: 51.31% | Val loss: 0.8577 | Val acc: 57.75% | LR: 0.001860
Epoch: 027 | MCC: 0.053887 | Train loss: 0.9740 | Train acc: 51.69% | Val loss: 0.8550 | Val acc: 57.55% | LR: 0.001848
Epoch: 028 | MCC: 0.040428 | Train loss: 0.9735 | Train acc: 51.78% | Val loss: 0.8487 | Val acc: 57.96% | LR: 0.001836
Epoch: 029 | MCC: 0.004125 | Train loss: 0.9733 | Train acc: 51.77% | Val loss: 0.8641 | Val acc: 56.88% | LR: 0.001824
Epoch: 030 | MCC: 0.015275 | Train loss: 0.9711 | Train acc: 51.89% | Val loss: 0.8781 | Val acc: 56.88% | LR: 0.001812
Epoch: 031 | MCC: 0.030311 | Train loss: 0.9705 | Train acc: 51.88% | Val loss: 0.8669 | Val acc: 58.24% | LR: 0.001799
Epoch: 032 | MCC: 0.032916 | Train loss: 0.9754 | Train acc: 51.68% | Val loss: 0.8682 | Val acc: 57.48% | LR: 0.001785
Epoch: 033 | MCC: 0.016457 | Train loss: 0.9728 | Train acc: 51.80% | Val loss: 0.8895 | Val acc: 56.45% | LR: 0.001772
Epoch: 034 | MCC: 0.057040 | Train loss: 0.9717 | Train acc: 51.83% | Val loss: 0.8744 | Val acc: 56.96% | LR: 0.001758
Epoch: 035 | MCC: 0.052916 | Train loss: 0.9877 | Train acc: 51.84% | Val loss: 0.8754 | Val acc: 56.60% | LR: 0.001744
Epoch: 036 | MCC: 0.045686 | Train loss: 0.9760 | Train acc: 51.23% | Val loss: 0.8935 | Val acc: 56.57% | LR: 0.001729
Epoch: 037 | MCC: 0.051691 | Train loss: 0.9756 | Train acc: 51.17% | Val loss: 0.8691 | Val acc: 57.04% | LR: 0.001714
Epoch: 038 | MCC: -0.005397 | Train loss: 0.9765 | Train acc: 51.14% | Val loss: 0.9054 | Val acc: 55.09% | LR: 0.001699
Epoch: 039 | MCC: -0.003746 | Train loss: 0.9769 | Train acc: 51.20% | Val loss: 0.9016 | Val acc: 55.31% | LR: 0.001683
Epoch: 040 | MCC: 0.020545 | Train loss: 0.9763 | Train acc: 51.42% | Val loss: 0.8775 | Val acc: 57.25% | LR: 0.001667
Epoch: 041 | MCC: 0.024090 | Train loss: 0.9764 | Train acc: 51.54% | Val loss: 0.9078 | Val acc: 55.66% | LR: 0.001651
Epoch: 042 | MCC: 0.009889 | Train loss: 0.9833 | Train acc: 50.70% | Val loss: 0.9052 | Val acc: 55.12% | LR: 0.001635
Epoch: 043 | MCC: 0.008278 | Train loss: 1.0209 | Train acc: 50.97% | Val loss: 0.9054 | Val acc: 55.20% | LR: 0.001618
Epoch: 044 | MCC: 0.003385 | Train loss: 0.9909 | Train acc: 50.81% | Val loss: 0.8953 | Val acc: 55.41% | LR: 0.001601
Epoch: 045 | MCC: -0.007157 | Train loss: 0.9811 | Train acc: 51.34% | Val loss: 0.9158 | Val acc: 54.87% | LR: 0.001584
Epoch: 046 | MCC: -0.011593 | Train loss: 0.9810 | Train acc: 51.10% | Val loss: 0.9244 | Val acc: 54.53% | LR: 0.001567
Epoch: 047 | MCC: -0.010719 | Train loss: 0.9795 | Train acc: 51.16% | Val loss: 0.9145 | Val acc: 54.68% | LR: 0.001549
Epoch: 048 | MCC: -0.002371 | Train loss: 0.9812 | Train acc: 51.06% | Val loss: 0.9014 | Val acc: 54.97% | LR: 0.001531
Epoch: 049 | MCC: -0.005727 | Train loss: 0.9777 | Train acc: 51.22% | Val loss: 0.9069 | Val acc: 54.92% | LR: 0.001513
Epoch: 050 | MCC: -0.005044 | Train loss: 0.9776 | Train acc: 51.23% | Val loss: 0.9140 | Val acc: 54.92% | LR: 0.001494
Epoch: 051 | MCC: -0.004990 | Train loss: 0.9775 | Train acc: 51.23% | Val loss: 0.9118 | Val acc: 54.73% | LR: 0.001476
Epoch: 052 | MCC: 0.001911 | Train loss: 0.9789 | Train acc: 51.16% | Val loss: 0.9051 | Val acc: 54.95% | LR: 0.001457
Epoch: 053 | MCC: 0.000633 | Train loss: 0.9788 | Train acc: 51.11% | Val loss: 0.9073 | Val acc: 55.43% | LR: 0.001438
Epoch: 054 | MCC: 0.005293 | Train loss: 0.9744 | Train acc: 51.39% | Val loss: 0.8878 | Val acc: 55.66% | LR: 0.001419
Epoch: 055 | MCC: 0.014837 | Train loss: 0.9791 | Train acc: 51.22% | Val loss: 0.8773 | Val acc: 56.32% | LR: 0.001399
Epoch: 056 | MCC: -0.000657 | Train loss: 0.9772 | Train acc: 51.28% | Val loss: 0.8926 | Val acc: 55.48% | LR: 0.001380
Epoch: 057 | MCC: -0.002863 | Train loss: 0.9780 | Train acc: 51.20% | Val loss: 0.8952 | Val acc: 55.45% | LR: 0.001360
Epoch: 058 | MCC: 0.005359 | Train loss: 0.9788 | Train acc: 51.13% | Val loss: 0.8939 | Val acc: 55.95% | LR: 0.001340
Epoch: 059 | MCC: 0.002686 | Train loss: 0.9775 | Train acc: 51.18% | Val loss: 0.8832 | Val acc: 56.03% | LR: 0.001320
Epoch: 060 | MCC: -0.006274 | Train loss: 0.9733 | Train acc: 51.40% | Val loss: 0.8979 | Val acc: 55.30% | LR: 0.001300
Epoch: 061 | MCC: -0.000494 | Train loss: 0.9771 | Train acc: 51.20% | Val loss: 0.9037 | Val acc: 55.43% | LR: 0.001280
Epoch: 062 | MCC: -0.005288 | Train loss: 0.9780 | Train acc: 51.17% | Val loss: 0.9042 | Val acc: 55.15% | LR: 0.001259
Epoch: 063 | MCC: -0.000932 | Train loss: 0.9757 | Train acc: 51.34% | Val loss: 0.9051 | Val acc: 55.10% | LR: 0.001239
Epoch: 064 | MCC: -0.000689 | Train loss: 0.9773 | Train acc: 51.19% | Val loss: 0.9046 | Val acc: 55.17% | LR: 0.001218
Epoch: 065 | MCC: -0.004351 | Train loss: 0.9764 | Train acc: 51.30% | Val loss: 0.8974 | Val acc: 55.18% | LR: 0.001198
Epoch: 066 | MCC: -0.006266 | Train loss: 0.9732 | Train acc: 51.38% | Val loss: 0.9041 | Val acc: 54.95% | LR: 0.001177
Epoch: 067 | MCC: 0.000239 | Train loss: 0.9750 | Train acc: 51.32% | Val loss: 0.9000 | Val acc: 55.20% | LR: 0.001156
Epoch: 068 | MCC: -0.009737 | Train loss: 0.9752 | Train acc: 51.29% | Val loss: 0.9030 | Val acc: 54.96% | LR: 0.001135
Epoch: 069 | MCC: -0.005821 | Train loss: 0.9753 | Train acc: 51.28% | Val loss: 0.8994 | Val acc: 55.17% | LR: 0.001114
Epoch: 070 | MCC: -0.008809 | Train loss: 0.9771 | Train acc: 51.23% | Val loss: 0.9118 | Val acc: 55.01% | LR: 0.001093
Epoch: 071 | MCC: -0.006814 | Train loss: 0.9770 | Train acc: 51.22% | Val loss: 0.8988 | Val acc: 55.01% | LR: 0.001072
Epoch: 072 | MCC: -0.005486 | Train loss: 0.9741 | Train acc: 51.34% | Val loss: 0.8976 | Val acc: 55.13% | LR: 0.001051
Epoch: 073 | MCC: 0.003555 | Train loss: 0.9756 | Train acc: 51.27% | Val loss: 0.9032 | Val acc: 55.32% | LR: 0.001030
Epoch: 074 | MCC: -0.003536 | Train loss: 0.9746 | Train acc: 51.36% | Val loss: 0.9003 | Val acc: 55.03% | LR: 0.001009
Epoch: 075 | MCC: -0.014442 | Train loss: 0.9766 | Train acc: 51.18% | Val loss: 0.9212 | Val acc: 54.44% | LR: 0.000988
Epoch: 076 | MCC: 0.008693 | Train loss: 0.9762 | Train acc: 51.33% | Val loss: 0.8942 | Val acc: 55.64% | LR: 0.000967
Epoch: 077 | MCC: 0.010166 | Train loss: 0.9771 | Train acc: 51.19% | Val loss: 0.8920 | Val acc: 55.66% | LR: 0.000946
Epoch: 078 | MCC: -0.005356 | Train loss: 0.9749 | Train acc: 51.31% | Val loss: 0.9031 | Val acc: 54.88% | LR: 0.000924
Epoch: 079 | MCC: 0.000465 | Train loss: 0.9754 | Train acc: 51.29% | Val loss: 0.8954 | Val acc: 55.38% | LR: 0.000903
Epoch: 080 | MCC: 0.004237 | Train loss: 0.9774 | Train acc: 51.16% | Val loss: 0.8956 | Val acc: 55.34% | LR: 0.000883
Epoch: 081 | MCC: -0.004071 | Train loss: 0.9745 | Train acc: 51.33% | Val loss: 0.9017 | Val acc: 54.93% | LR: 0.000862
Epoch: 082 | MCC: -0.007892 | Train loss: 0.9762 | Train acc: 51.22% | Val loss: 0.9017 | Val acc: 55.01% | LR: 0.000841
Epoch: 083 | MCC: 0.001556 | Train loss: 0.9754 | Train acc: 51.30% | Val loss: 0.8983 | Val acc: 55.25% | LR: 0.000820
Epoch: 084 | MCC: -0.003671 | Train loss: 0.9728 | Train acc: 51.41% | Val loss: 0.8985 | Val acc: 55.15% | LR: 0.000799
Epoch: 085 | MCC: -0.000819 | Train loss: 0.9762 | Train acc: 51.23% | Val loss: 0.8986 | Val acc: 55.32% | LR: 0.000779
Epoch: 086 | MCC: -0.002420 | Train loss: 0.9754 | Train acc: 51.27% | Val loss: 0.8986 | Val acc: 55.36% | LR: 0.000758
Epoch: 087 | MCC: -0.006317 | Train loss: 0.9757 | Train acc: 51.25% | Val loss: 0.8954 | Val acc: 55.18% | LR: 0.000738
Epoch: 088 | MCC: -0.004967 | Train loss: 0.9746 | Train acc: 51.35% | Val loss: 0.8997 | Val acc: 55.15% | LR: 0.000718
Epoch: 089 | MCC: -0.006576 | Train loss: 0.9752 | Train acc: 51.29% | Val loss: 0.9013 | Val acc: 54.83% | LR: 0.000697
Epoch: 090 | MCC: -0.001140 | Train loss: 0.9760 | Train acc: 51.23% | Val loss: 0.8960 | Val acc: 55.26% | LR: 0.000677
Epoch: 091 | MCC: -0.002263 | Train loss: 0.9746 | Train acc: 51.30% | Val loss: 0.8999 | Val acc: 55.05% | LR: 0.000658
Epoch: 092 | MCC: -0.000590 | Train loss: 0.9735 | Train acc: 51.39% | Val loss: 0.8968 | Val acc: 55.31% | LR: 0.000638
Epoch: 093 | MCC: 0.002232 | Train loss: 0.9733 | Train acc: 51.39% | Val loss: 0.8955 | Val acc: 55.27% | LR: 0.000618
Epoch: 094 | MCC: -0.001745 | Train loss: 0.9730 | Train acc: 51.42% | Val loss: 0.8958 | Val acc: 55.32% | LR: 0.000599
Epoch: 095 | MCC: -0.005125 | Train loss: 0.9737 | Train acc: 51.35% | Val loss: 0.8955 | Val acc: 55.20% | LR: 0.000580
Epoch: 096 | MCC: 0.001685 | Train loss: 0.9724 | Train acc: 51.44% | Val loss: 0.8962 | Val acc: 55.25% | LR: 0.000561
Epoch: 097 | MCC: 0.000715 | Train loss: 0.9722 | Train acc: 51.47% | Val loss: 0.8972 | Val acc: 55.20% | LR: 0.000542

[I 2025-10-05 08:48:51,842] Trial 5 finished with value: 0.003429468721151352 and parameters: {'lr': 0.002016658068493325, 'hidden_size': 41, 'dropout': 0.3945885408922329, 'weight_decay': 0.0024357955970442315}. Best is trial 4 with value: 0.04243219271302223.

Epoch: 000 | MCC: 0.025057 | Train loss: 0.9990 | Train acc: 50.48% | Val loss: 1.0036 | Val acc: 53.12% | LR: 0.002920
Epoch: 001 | MCC: 0.010102 | Train loss: 1.0170 | Train acc: 50.38% | Val loss: 1.0633 | Val acc: 47.54% | LR: 0.002919
Epoch: 002 | MCC: 0.027988 | Train loss: 0.9878 | Train acc: 50.68% | Val loss: 0.9498 | Val acc: 54.23% | LR: 0.002918
Epoch: 003 | MCC: 0.042411 | Train loss: 0.9887 | Train acc: 51.07% | Val loss: 0.9910 | Val acc: 54.76% | LR: 0.002915
Epoch: 004 | MCC: 0.028132 | Train loss: 0.9872 | Train acc: 50.83% | Val loss: 0.9480 | Val acc: 54.37% | LR: 0.002913
Epoch: 005 | MCC: 0.012313 | Train loss: 0.9933 | Train acc: 50.96% | Val loss: 0.9869 | Val acc: 53.68% | LR: 0.002909
Epoch: 006 | MCC: 0.038487 | Train loss: 0.9840 | Train acc: 50.91% | Val loss: 0.9454 | Val acc: 53.68% | LR: 0.002905
Epoch: 007 | MCC: 0.044667 | Train loss: 0.9886 | Train acc: 50.76% | Val loss: 0.9735 | Val acc: 54.01% | LR: 0.002900
Epoch: 008 | MCC: 0.042474 | Train loss: 0.9856 | Train acc: 50.94% | Val loss: 0.9517 | Val acc: 53.83% | LR: 0.002895
Epoch: 009 | MCC: 0.043911 | Train loss: 0.9841 | Train acc: 50.95% | Val loss: 0.9585 | Val acc: 54.27% | LR: 0.002889
Epoch: 010 | MCC: 0.029733 | Train loss: 0.9872 | Train acc: 50.88% | Val loss: 0.9534 | Val acc: 53.19% | LR: 0.002882
Epoch: 011 | MCC: 0.037873 | Train loss: 0.9903 | Train acc: 50.95% | Val loss: 0.9561 | Val acc: 53.51% | LR: 0.002875
Epoch: 012 | MCC: 0.047983 | Train loss: 0.9875 | Train acc: 50.89% | Val loss: 0.9625 | Val acc: 55.56% | LR: 0.002867
Epoch: 013 | MCC: 0.049393 | Train loss: 0.9987 | Train acc: 50.65% | Val loss: 0.9882 | Val acc: 55.30% | LR: 0.002858
Epoch: 014 | MCC: 0.047858 | Train loss: 0.9914 | Train acc: 50.76% | Val loss: 0.9854 | Val acc: 55.72% | LR: 0.002849
Epoch: 015 | MCC: 0.036557 | Train loss: 0.9889 | Train acc: 50.88% | Val loss: 0.9613 | Val acc: 54.51% | LR: 0.002839
Epoch: 016 | MCC: 0.045388 | Train loss: 0.9949 | Train acc: 50.55% | Val loss: 0.9576 | Val acc: 54.63% | LR: 0.002829
Epoch: 017 | MCC: 0.043971 | Train loss: 0.9859 | Train acc: 50.83% | Val loss: 0.9335 | Val acc: 54.77% | LR: 0.002818
Epoch: 018 | MCC: 0.040193 | Train loss: 0.9852 | Train acc: 50.92% | Val loss: 0.9325 | Val acc: 54.64% | LR: 0.002807
Epoch: 019 | MCC: 0.035439 | Train loss: 0.9865 | Train acc: 51.00% | Val loss: 0.9248 | Val acc: 54.43% | LR: 0.002794
Epoch: 020 | MCC: 0.029522 | Train loss: 0.9871 | Train acc: 51.07% | Val loss: 0.9156 | Val acc: 54.30% | LR: 0.002782
Epoch: 021 | MCC: 0.038593 | Train loss: 0.9862 | Train acc: 51.03% | Val loss: 0.9513 | Val acc: 54.41% | LR: 0.002768
Epoch: 022 | MCC: 0.038744 | Train loss: 0.9855 | Train acc: 51.04% | Val loss: 0.9445 | Val acc: 54.40% | LR: 0.002754
Epoch: 023 | MCC: 0.039897 | Train loss: 0.9827 | Train acc: 51.05% | Val loss: 0.9405 | Val acc: 54.60% | LR: 0.002740
Epoch: 024 | MCC: 0.030262 | Train loss: 0.9808 | Train acc: 51.13% | Val loss: 0.9451 | Val acc: 54.58% | LR: 0.002725
Epoch: 025 | MCC: 0.029685 | Train loss: 0.9863 | Train acc: 50.85% | Val loss: 0.9221 | Val acc: 53.93% | LR: 0.002709
Epoch: 026 | MCC: 0.034665 | Train loss: 0.9834 | Train acc: 50.94% | Val loss: 0.9263 | Val acc: 54.51% | LR: 0.002693
Epoch: 027 | MCC: 0.033413 | Train loss: 0.9842 | Train acc: 50.87% | Val loss: 0.9070 | Val acc: 54.99% | LR: 0.002677
Epoch: 028 | MCC: 0.036040 | Train loss: 0.9813 | Train acc: 50.99% | Val loss: 0.9251 | Val acc: 55.19% | LR: 0.002660
Epoch: 029 | MCC: 0.039965 | Train loss: 0.9812 | Train acc: 51.06% | Val loss: 0.9444 | Val acc: 55.42% | LR: 0.002642
Epoch: 030 | MCC: 0.036379 | Train loss: 0.9825 | Train acc: 50.95% | Val loss: 0.9092 | Val acc: 55.15% | LR: 0.002624
Epoch: 031 | MCC: 0.041814 | Train loss: 0.9855 | Train acc: 50.89% | Val loss: 0.8993 | Val acc: 55.06% | LR: 0.002605
Epoch: 032 | MCC: 0.052087 | Train loss: 0.9796 | Train acc: 51.02% | Val loss: 0.9064 | Val acc: 55.19% | LR: 0.002586
Epoch: 033 | MCC: 0.049601 | Train loss: 0.9769 | Train acc: 51.13% | Val loss: 0.9126 | Val acc: 54.66% | LR: 0.002566
Epoch: 034 | MCC: 0.044635 | Train loss: 0.9801 | Train acc: 50.96% | Val loss: 0.9352 | Val acc: 55.17% | LR: 0.002546
Epoch: 035 | MCC: 0.047197 | Train loss: 0.9775 | Train acc: 51.20% | Val loss: 0.9083 | Val acc: 54.53% | LR: 0.002525
Epoch: 036 | MCC: 0.050255 | Train loss: 0.9794 | Train acc: 51.09% | Val loss: 0.9002 | Val acc: 54.99% | LR: 0.002504
Epoch: 037 | MCC: 0.040876 | Train loss: 0.9736 | Train acc: 51.30% | Val loss: 0.8875 | Val acc: 56.06% | LR: 0.002482
Epoch: 038 | MCC: 0.042168 | Train loss: 0.9737 | Train acc: 51.36% | Val loss: 0.8776 | Val acc: 56.43% | LR: 0.002460
Epoch: 039 | MCC: 0.051841 | Train loss: 0.9773 | Train acc: 51.06% | Val loss: 0.8906 | Val acc: 56.23% | LR: 0.002438
Epoch: 040 | MCC: 0.045712 | Train loss: 0.9777 | Train acc: 50.99% | Val loss: 0.8535 | Val acc: 58.24% | LR: 0.002415
Epoch: 041 | MCC: 0.037935 | Train loss: 0.9793 | Train acc: 51.03% | Val loss: 0.8397 | Val acc: 59.65% | LR: 0.002391
Epoch: 042 | MCC: 0.025488 | Train loss: 0.9780 | Train acc: 51.19% | Val loss: 0.8618 | Val acc: 57.16% | LR: 0.002368
Epoch: 043 | MCC: 0.012008 | Train loss: 0.9732 | Train acc: 51.15% | Val loss: 0.8710 | Val acc: 56.08% | LR: 0.002343
Epoch: 044 | MCC: 0.045607 | Train loss: 0.9737 | Train acc: 51.35% | Val loss: 0.7966 | Val acc: 60.90% | LR: 0.002319
Epoch: 045 | MCC: 0.038559 | Train loss: 0.9744 | Train acc: 51.67% | Val loss: 0.8275 | Val acc: 58.88% | LR: 0.002294
Epoch: 046 | MCC: 0.040059 | Train loss: 0.9777 | Train acc: 51.76% | Val loss: 0.8582 | Val acc: 57.92% | LR: 0.002269
Epoch: 047 | MCC: 0.040847 | Train loss: 0.9784 | Train acc: 51.76% | Val loss: 0.8730 | Val acc: 57.05% | LR: 0.002243
Epoch: 048 | MCC: 0.051109 | Train loss: 0.9750 | Train acc: 51.76% | Val loss: 0.8442 | Val acc: 58.06% | LR: 0.002217
Epoch: 049 | MCC: 0.045885 | Train loss: 0.9756 | Train acc: 51.81% | Val loss: 0.8456 | Val acc: 57.87% | LR: 0.002191
Epoch: 050 | MCC: -0.000464 | Train loss: 0.9772 | Train acc: 51.68% | Val loss: 0.9323 | Val acc: 53.87% | LR: 0.002164
Epoch: 051 | MCC: 0.043302 | Train loss: 0.9810 | Train acc: 51.64% | Val loss: 0.8853 | Val acc: 56.52% | LR: 0.002137
Epoch: 052 | MCC: 0.051509 | Train loss: 0.9696 | Train acc: 51.88% | Val loss: 0.8644 | Val acc: 57.21% | LR: 0.002110
Epoch: 053 | MCC: 0.058993 | Train loss: 0.9697 | Train acc: 51.74% | Val loss: 0.8561 | Val acc: 57.45% | LR: 0.002082
Epoch: 054 | MCC: 0.048579 | Train loss: 0.9701 | Train acc: 51.79% | Val loss: 0.8609 | Val acc: 57.43% | LR: 0.002055
Epoch: 055 | MCC: 0.055525 | Train loss: 0.9714 | Train acc: 51.70% | Val loss: 0.8524 | Val acc: 57.87% | LR: 0.002026
Epoch: 056 | MCC: 0.024038 | Train loss: 0.9673 | Train acc: 51.91% | Val loss: 0.8680 | Val acc: 57.08% | LR: 0.001998
Epoch: 057 | MCC: 0.033065 | Train loss: 0.9675 | Train acc: 51.87% | Val loss: 0.8572 | Val acc: 57.26% | LR: 0.001970
Epoch: 058 | MCC: 0.028741 | Train loss: 0.9685 | Train acc: 51.78% | Val loss: 0.8685 | Val acc: 56.79% | LR: 0.001941
Epoch: 059 | MCC: 0.028946 | Train loss: 0.9644 | Train acc: 51.96% | Val loss: 0.8703 | Val acc: 56.84% | LR: 0.001912
Epoch: 060 | MCC: 0.027287 | Train loss: 0.9636 | Train acc: 51.99% | Val loss: 0.8679 | Val acc: 57.04% | LR: 0.001883
Epoch: 061 | MCC: 0.027761 | Train loss: 0.9658 | Train acc: 51.85% | Val loss: 0.8691 | Val acc: 56.63% | LR: 0.001853
Epoch: 062 | MCC: 0.032859 | Train loss: 0.9667 | Train acc: 51.84% | Val loss: 0.8564 | Val acc: 57.29% | LR: 0.001824
Epoch: 063 | MCC: 0.025880 | Train loss: 0.9665 | Train acc: 51.91% | Val loss: 0.8829 | Val acc: 56.53% | LR: 0.001794
Epoch: 064 | MCC: 0.037496 | Train loss: 0.9662 | Train acc: 51.91% | Val loss: 0.8447 | Val acc: 58.01% | LR: 0.001764
Epoch: 065 | MCC: 0.035203 | Train loss: 0.9683 | Train acc: 51.72% | Val loss: 0.8495 | Val acc: 57.96% | LR: 0.001734
Epoch: 066 | MCC: 0.029334 | Train loss: 0.9666 | Train acc: 51.78% | Val loss: 0.8558 | Val acc: 57.55% | LR: 0.001704
Epoch: 067 | MCC: 0.032854 | Train loss: 0.9669 | Train acc: 51.75% | Val loss: 0.8580 | Val acc: 57.23% | LR: 0.001674
Epoch: 068 | MCC: 0.022494 | Train loss: 0.9647 | Train acc: 51.87% | Val loss: 0.8642 | Val acc: 56.85% | LR: 0.001644
Epoch: 069 | MCC: 0.025901 | Train loss: 0.9620 | Train acc: 52.01% | Val loss: 0.8794 | Val acc: 56.58% | LR: 0.001613
Epoch: 070 | MCC: 0.030214 | Train loss: 0.9633 | Train acc: 51.94% | Val loss: 0.8730 | Val acc: 56.92% | LR: 0.001583
Epoch: 071 | MCC: 0.024365 | Train loss: 0.9637 | Train acc: 51.91% | Val loss: 0.8685 | Val acc: 56.70% | LR: 0.001552
Epoch: 072 | MCC: 0.024630 | Train loss: 0.9622 | Train acc: 52.06% | Val loss: 0.8676 | Val acc: 56.78% | LR: 0.001522
Epoch: 073 | MCC: 0.028347 | Train loss: 0.9634 | Train acc: 51.92% | Val loss: 0.8716 | Val acc: 56.69% | LR: 0.001491
Epoch: 074 | MCC: 0.029324 | Train loss: 0.9617 | Train acc: 52.00% | Val loss: 0.8607 | Val acc: 56.97% | LR: 0.001461
Epoch: 075 | MCC: 0.033380 | Train loss: 0.9619 | Train acc: 52.01% | Val loss: 0.8634 | Val acc: 56.97% | LR: 0.001430
Epoch: 076 | MCC: 0.031419 | Train loss: 0.9656 | Train acc: 51.83% | Val loss: 0.8654 | Val acc: 57.07% | LR: 0.001400
Epoch: 077 | MCC: 0.043020 | Train loss: 0.9652 | Train acc: 51.82% | Val loss: 0.8736 | Val acc: 56.54% | LR: 0.001369
Epoch: 078 | MCC: 0.041672 | Train loss: 0.9654 | Train acc: 51.84% | Val loss: 0.8868 | Val acc: 55.83% | LR: 0.001339
Epoch: 079 | MCC: 0.022667 | Train loss: 0.9636 | Train acc: 51.93% | Val loss: 0.8652 | Val acc: 56.78% | LR: 0.001308
Epoch: 080 | MCC: 0.025275 | Train loss: 0.9623 | Train acc: 52.00% | Val loss: 0.8570 | Val acc: 57.39% | LR: 0.001278
Epoch: 081 | MCC: 0.021782 | Train loss: 0.9660 | Train acc: 52.00% | Val loss: 0.8681 | Val acc: 56.54% | LR: 0.001248
Epoch: 082 | MCC: 0.020300 | Train loss: 0.9634 | Train acc: 51.95% | Val loss: 0.8624 | Val acc: 56.83% | LR: 0.001217
Epoch: 083 | MCC: 0.022601 | Train loss: 0.9641 | Train acc: 51.92% | Val loss: 0.8644 | Val acc: 57.05% | LR: 0.001187
Epoch: 084 | MCC: 0.030492 | Train loss: 0.9631 | Train acc: 51.94% | Val loss: 0.8541 | Val acc: 57.32% | LR: 0.001157
Epoch: 085 | MCC: 0.021738 | Train loss: 0.9625 | Train acc: 51.93% | Val loss: 0.8486 | Val acc: 57.39% | LR: 0.001127
Epoch: 086 | MCC: 0.025569 | Train loss: 0.9614 | Train acc: 51.95% | Val loss: 0.8367 | Val acc: 58.08% | LR: 0.001098
Epoch: 087 | MCC: 0.018199 | Train loss: 0.9619 | Train acc: 52.00% | Val loss: 0.8453 | Val acc: 57.76% | LR: 0.001068
Epoch: 088 | MCC: 0.031699 | Train loss: 0.9615 | Train acc: 51.99% | Val loss: 0.8310 | Val acc: 58.52% | LR: 0.001039
Epoch: 089 | MCC: 0.031491 | Train loss: 0.9612 | Train acc: 52.05% | Val loss: 0.8280 | Val acc: 58.63% | LR: 0.001010
Epoch: 090 | MCC: 0.030097 | Train loss: 0.9585 | Train acc: 52.14% | Val loss: 0.8278 | Val acc: 58.53% | LR: 0.000981
Epoch: 091 | MCC: 0.038548 | Train loss: 0.9585 | Train acc: 52.16% | Val loss: 0.8320 | Val acc: 58.64% | LR: 0.000952
Epoch: 092 | MCC: 0.063437 | Train loss: 0.9609 | Train acc: 51.99% | Val loss: 0.8296 | Val acc: 58.85% | LR: 0.000923
Epoch: 093 | MCC: 0.033825 | Train loss: 0.9602 | Train acc: 52.08% | Val loss: 0.8448 | Val acc: 57.91% | LR: 0.000895
Epoch: 094 | MCC: 0.030864 | Train loss: 0.9602 | Train acc: 52.06% | Val loss: 0.8545 | Val acc: 57.30% | LR: 0.000867
Epoch: 095 | MCC: 0.038536 | Train loss: 0.9648 | Train acc: 51.78% | Val loss: 0.8509 | Val acc: 57.59% | LR: 0.000839
Epoch: 096 | MCC: 0.032657 | Train loss: 0.9621 | Train acc: 51.97% | Val loss: 0.8579 | Val acc: 57.27% | LR: 0.000812
Epoch: 097 | MCC: 0.036117 | Train loss: 0.9615 | Train acc: 51.98% | Val loss: 0.8553 | Val acc: 57.52% | LR: 0.000784
Epoch: 098 | MCC: 0.028608 | Train loss: 0.9609 | Train acc: 52.02% | Val loss: 0.8518 | Val acc: 57.42% | LR: 0.000758
Epoch: 099 | MCC: 0.034363 | Train loss: 0.9583 | Train acc: 52.14% | Val loss: 0.8402 | Val acc: 57.83% | LR: 0.000731
Epoch: 100 | MCC: 0.032136 | Train loss: 0.9595 | Train acc: 52.10% | Val loss: 0.8177 | Val acc: 59.05% | LR: 0.000705
Epoch: 101 | MCC: 0.026236 | Train loss: 0.9601 | Train acc: 52.04% | Val loss: 0.8308 | Val acc: 58.42% | LR: 0.000679
Epoch: 102 | MCC: 0.035021 | Train loss: 0.9606 | Train acc: 52.01% | Val loss: 0.8283 | Val acc: 58.79% | LR: 0.000653
Epoch: 103 | MCC: 0.028786 | Train loss: 0.9592 | Train acc: 52.09% | Val loss: 0.8245 | Val acc: 58.84% | LR: 0.000628
Epoch: 104 | MCC: 0.034880 | Train loss: 0.9605 | Train acc: 52.03% | Val loss: 0.8253 | Val acc: 58.88% | LR: 0.000603
Epoch: 105 | MCC: 0.036882 | Train loss: 0.9596 | Train acc: 52.08% | Val loss: 0.8283 | Val acc: 58.76% | LR: 0.000578
Epoch: 106 | MCC: 0.037242 | Train loss: 0.9591 | Train acc: 52.11% | Val loss: 0.8266 | Val acc: 58.93% | LR: 0.000554
Epoch: 107 | MCC: 0.031824 | Train loss: 0.9572 | Train acc: 52.20% | Val loss: 0.8232 | Val acc: 58.98% | LR: 0.000530
Epoch: 108 | MCC: 0.065872 | Train loss: 0.9594 | Train acc: 52.10% | Val loss: 0.8023 | Val acc: 60.10% | LR: 0.000507
Epoch: 109 | MCC: 0.032032 | Train loss: 0.9585 | Train acc: 52.16% | Val loss: 0.8210 | Val acc: 59.01% | LR: 0.000484
Epoch: 110 | MCC: 0.042298 | Train loss: 0.9575 | Train acc: 52.19% | Val loss: 0.8314 | Val acc: 58.54% | LR: 0.000461
Epoch: 111 | MCC: 0.029088 | Train loss: 0.9625 | Train acc: 51.92% | Val loss: 0.8208 | Val acc: 59.02% | LR: 0.000439
Epoch: 112 | MCC: 0.033374 | Train loss: 0.9594 | Train acc: 52.10% | Val loss: 0.8208 | Val acc: 58.96% | LR: 0.000418
Epoch: 113 | MCC: 0.033318 | Train loss: 0.9600 | Train acc: 52.05% | Val loss: 0.8255 | Val acc: 58.81% | LR: 0.000397
Epoch: 114 | MCC: 0.034192 | Train loss: 0.9589 | Train acc: 52.10% | Val loss: 0.8219 | Val acc: 58.96% | LR: 0.000376
Epoch: 115 | MCC: 0.051750 | Train loss: 0.9590 | Train acc: 52.09% | Val loss: 0.8230 | Val acc: 58.86% | LR: 0.000356
Epoch: 116 | MCC: 0.047124 | Train loss: 0.9588 | Train acc: 52.10% | Val loss: 0.8297 | Val acc: 58.71% | LR: 0.000336
Epoch: 117 | MCC: 0.034591 | Train loss: 0.9613 | Train acc: 51.95% | Val loss: 0.8218 | Val acc: 59.10% | LR: 0.000317
Epoch: 118 | MCC: 0.036485 | Train loss: 0.9580 | Train acc: 52.15% | Val loss: 0.8198 | Val acc: 59.13% | LR: 0.000298

[I 2025-10-05 08:50:56,241] Trial 6 finished with value: 0.035166327841579914 and parameters: {'lr': 0.002920599140030628, 'hidden_size': 106, 'dropout': 0.1744373603402662, 'weight_decay': 0.002852484817032574}. Best is trial 4 with value: 0.04243219271302223.

Epoch: 000 | MCC: 0.009504 | Train loss: 1.0020 | Train acc: 49.58% | Val loss: 0.9834 | Val acc: 54.98% | LR: 0.001260
Epoch: 001 | MCC: -0.014037 | Train loss: 1.0009 | Train acc: 50.10% | Val loss: 0.9848 | Val acc: 54.57% | LR: 0.001259
Epoch: 002 | MCC: -0.009233 | Train loss: 1.0253 | Train acc: 50.28% | Val loss: 0.9792 | Val acc: 54.54% | LR: 0.001259
Epoch: 003 | MCC: -0.002758 | Train loss: 1.0015 | Train acc: 50.30% | Val loss: 0.9781 | Val acc: 54.40% | LR: 0.001258
Epoch: 004 | MCC: -0.003922 | Train loss: 1.0008 | Train acc: 50.31% | Val loss: 0.9824 | Val acc: 54.74% | LR: 0.001256
Epoch: 005 | MCC: 0.006832 | Train loss: 0.9949 | Train acc: 50.25% | Val loss: 0.9762 | Val acc: 54.72% | LR: 0.001255
Epoch: 006 | MCC: -0.013742 | Train loss: 0.9952 | Train acc: 50.13% | Val loss: 0.9812 | Val acc: 54.42% | LR: 0.001253
Epoch: 007 | MCC: 0.016596 | Train loss: 0.9952 | Train acc: 50.45% | Val loss: 0.9734 | Val acc: 54.82% | LR: 0.001251
Epoch: 008 | MCC: -0.029864 | Train loss: 1.0023 | Train acc: 50.71% | Val loss: 0.9762 | Val acc: 54.50% | LR: 0.001249
Epoch: 009 | MCC: -0.003995 | Train loss: 0.9967 | Train acc: 50.49% | Val loss: 0.9904 | Val acc: 54.53% | LR: 0.001246
Epoch: 010 | MCC: 0.008287 | Train loss: 0.9897 | Train acc: 50.25% | Val loss: 0.9883 | Val acc: 54.83% | LR: 0.001243
Epoch: 011 | MCC: -0.001202 | Train loss: 0.9899 | Train acc: 50.29% | Val loss: 0.9669 | Val acc: 54.68% | LR: 0.001240
Epoch: 012 | MCC: -0.003698 | Train loss: 0.9886 | Train acc: 50.47% | Val loss: 0.9708 | Val acc: 54.43% | LR: 0.001237
Epoch: 013 | MCC: 0.026645 | Train loss: 0.9876 | Train acc: 50.75% | Val loss: 0.9736 | Val acc: 54.12% | LR: 0.001233
Epoch: 014 | MCC: 0.021495 | Train loss: 0.9867 | Train acc: 50.95% | Val loss: 0.9670 | Val acc: 54.57% | LR: 0.001229
Epoch: 015 | MCC: 0.031446 | Train loss: 0.9864 | Train acc: 51.12% | Val loss: 0.9755 | Val acc: 54.66% | LR: 0.001225
Epoch: 016 | MCC: 0.030308 | Train loss: 0.9843 | Train acc: 51.04% | Val loss: 0.9665 | Val acc: 52.63% | LR: 0.001220
Epoch: 017 | MCC: 0.051097 | Train loss: 0.9821 | Train acc: 51.00% | Val loss: 0.9517 | Val acc: 54.27% | LR: 0.001216
Epoch: 018 | MCC: 0.060072 | Train loss: 0.9820 | Train acc: 51.01% | Val loss: 0.9470 | Val acc: 53.88% | LR: 0.001211
Epoch: 019 | MCC: 0.041813 | Train loss: 0.9808 | Train acc: 51.12% | Val loss: 0.9424 | Val acc: 52.75% | LR: 0.001206
Epoch: 020 | MCC: 0.047539 | Train loss: 0.9813 | Train acc: 50.99% | Val loss: 0.9401 | Val acc: 53.18% | LR: 0.001200
Epoch: 021 | MCC: 0.058717 | Train loss: 0.9804 | Train acc: 51.08% | Val loss: 0.9404 | Val acc: 53.86% | LR: 0.001194
Epoch: 022 | MCC: 0.049889 | Train loss: 0.9805 | Train acc: 51.03% | Val loss: 0.9371 | Val acc: 53.19% | LR: 0.001188
Epoch: 023 | MCC: 0.047257 | Train loss: 0.9790 | Train acc: 51.10% | Val loss: 0.9368 | Val acc: 52.93% | LR: 0.001182
Epoch: 024 | MCC: 0.058907 | Train loss: 0.9785 | Train acc: 51.05% | Val loss: 0.9376 | Val acc: 53.44% | LR: 0.001176
Epoch: 025 | MCC: 0.061899 | Train loss: 0.9821 | Train acc: 50.93% | Val loss: 0.9378 | Val acc: 54.13% | LR: 0.001169
Epoch: 026 | MCC: 0.056476 | Train loss: 0.9806 | Train acc: 50.92% | Val loss: 0.9290 | Val acc: 54.03% | LR: 0.001162
Epoch: 027 | MCC: 0.058226 | Train loss: 0.9799 | Train acc: 50.94% | Val loss: 0.9275 | Val acc: 54.15% | LR: 0.001155
Epoch: 028 | MCC: 0.056944 | Train loss: 0.9788 | Train acc: 50.98% | Val loss: 0.9322 | Val acc: 53.95% | LR: 0.001147
Epoch: 029 | MCC: 0.064108 | Train loss: 0.9781 | Train acc: 51.07% | Val loss: 0.9716 | Val acc: 54.38% | LR: 0.001140
Epoch: 030 | MCC: 0.064279 | Train loss: 0.9787 | Train acc: 50.95% | Val loss: 0.9356 | Val acc: 55.03% | LR: 0.001132
Epoch: 031 | MCC: 0.065020 | Train loss: 0.9796 | Train acc: 50.87% | Val loss: 0.9409 | Val acc: 55.18% | LR: 0.001124
Epoch: 032 | MCC: 0.063381 | Train loss: 0.9788 | Train acc: 50.95% | Val loss: 0.9411 | Val acc: 54.96% | LR: 0.001115
Epoch: 033 | MCC: 0.062632 | Train loss: 0.9793 | Train acc: 50.97% | Val loss: 0.9410 | Val acc: 55.34% | LR: 0.001107
Epoch: 034 | MCC: 0.055511 | Train loss: 0.9774 | Train acc: 51.00% | Val loss: 0.9340 | Val acc: 54.86% | LR: 0.001098
Epoch: 035 | MCC: 0.050207 | Train loss: 0.9789 | Train acc: 51.03% | Val loss: 0.9335 | Val acc: 54.43% | LR: 0.001089
Epoch: 036 | MCC: 0.050628 | Train loss: 0.9782 | Train acc: 51.03% | Val loss: 0.9283 | Val acc: 54.35% | LR: 0.001080
Epoch: 037 | MCC: 0.048430 | Train loss: 0.9765 | Train acc: 51.19% | Val loss: 0.9242 | Val acc: 54.51% | LR: 0.001071
Epoch: 038 | MCC: 0.050129 | Train loss: 0.9767 | Train acc: 51.15% | Val loss: 0.9235 | Val acc: 55.02% | LR: 0.001061
Epoch: 039 | MCC: 0.051792 | Train loss: 0.9773 | Train acc: 51.10% | Val loss: 0.9253 | Val acc: 55.07% | LR: 0.001052
Epoch: 040 | MCC: 0.049348 | Train loss: 0.9775 | Train acc: 51.09% | Val loss: 0.9199 | Val acc: 55.16% | LR: 0.001042
Epoch: 041 | MCC: 0.045583 | Train loss: 0.9754 | Train acc: 51.14% | Val loss: 0.9211 | Val acc: 54.76% | LR: 0.001032
Epoch: 042 | MCC: 0.051271 | Train loss: 0.9758 | Train acc: 51.12% | Val loss: 0.9174 | Val acc: 55.06% | LR: 0.001021
Epoch: 043 | MCC: 0.040379 | Train loss: 0.9748 | Train acc: 51.20% | Val loss: 0.9044 | Val acc: 55.16% | LR: 0.001011
Epoch: 044 | MCC: 0.045270 | Train loss: 0.9749 | Train acc: 51.03% | Val loss: 0.8977 | Val acc: 56.08% | LR: 0.001000
Epoch: 045 | MCC: 0.046690 | Train loss: 0.9745 | Train acc: 51.20% | Val loss: 0.8891 | Val acc: 56.23% | LR: 0.000990
Epoch: 046 | MCC: 0.049347 | Train loss: 0.9742 | Train acc: 51.04% | Val loss: 0.8867 | Val acc: 56.47% | LR: 0.000979
Epoch: 047 | MCC: 0.057747 | Train loss: 0.9737 | Train acc: 51.15% | Val loss: 0.8773 | Val acc: 57.27% | LR: 0.000968
Epoch: 048 | MCC: 0.058193 | Train loss: 0.9735 | Train acc: 51.24% | Val loss: 0.8741 | Val acc: 57.21% | LR: 0.000957
Epoch: 049 | MCC: 0.038178 | Train loss: 0.9721 | Train acc: 51.15% | Val loss: 0.8692 | Val acc: 57.11% | LR: 0.000945
Epoch: 050 | MCC: 0.006447 | Train loss: 0.9727 | Train acc: 51.15% | Val loss: 0.8755 | Val acc: 56.30% | LR: 0.000934
Epoch: 051 | MCC: 0.008902 | Train loss: 0.9742 | Train acc: 51.20% | Val loss: 0.8737 | Val acc: 56.62% | LR: 0.000922
Epoch: 052 | MCC: 0.023544 | Train loss: 0.9734 | Train acc: 51.05% | Val loss: 0.8745 | Val acc: 56.99% | LR: 0.000910
Epoch: 053 | MCC: 0.061054 | Train loss: 0.9720 | Train acc: 51.23% | Val loss: 0.8499 | Val acc: 58.27% | LR: 0.000898
Epoch: 054 | MCC: 0.024332 | Train loss: 0.9717 | Train acc: 51.20% | Val loss: 0.8610 | Val acc: 57.50% | LR: 0.000887
Epoch: 055 | MCC: 0.032389 | Train loss: 0.9730 | Train acc: 51.23% | Val loss: 0.8600 | Val acc: 57.96% | LR: 0.000874
Epoch: 056 | MCC: 0.016809 | Train loss: 0.9711 | Train acc: 51.28% | Val loss: 0.8721 | Val acc: 56.91% | LR: 0.000862
Epoch: 057 | MCC: 0.020499 | Train loss: 0.9709 | Train acc: 51.34% | Val loss: 0.8614 | Val acc: 57.61% | LR: 0.000850
Epoch: 058 | MCC: 0.011293 | Train loss: 0.9696 | Train acc: 51.31% | Val loss: 0.8595 | Val acc: 57.36% | LR: 0.000837
Epoch: 059 | MCC: 0.014426 | Train loss: 0.9702 | Train acc: 51.25% | Val loss: 0.8646 | Val acc: 57.08% | LR: 0.000825
Epoch: 060 | MCC: -0.003198 | Train loss: 0.9694 | Train acc: 51.29% | Val loss: 0.8545 | Val acc: 57.20% | LR: 0.000812
Epoch: 061 | MCC: 0.008901 | Train loss: 0.9701 | Train acc: 51.25% | Val loss: 0.8902 | Val acc: 55.59% | LR: 0.000800
Epoch: 062 | MCC: 0.015977 | Train loss: 0.9715 | Train acc: 51.11% | Val loss: 0.8327 | Val acc: 58.55% | LR: 0.000787
Epoch: 063 | MCC: 0.022413 | Train loss: 0.9695 | Train acc: 51.96% | Val loss: 0.8367 | Val acc: 58.47% | LR: 0.000774
Epoch: 064 | MCC: 0.041160 | Train loss: 0.9688 | Train acc: 51.96% | Val loss: 0.8230 | Val acc: 59.69% | LR: 0.000761
Epoch: 065 | MCC: 0.028340 | Train loss: 0.9703 | Train acc: 51.88% | Val loss: 0.8240 | Val acc: 59.40% | LR: 0.000748
Epoch: 066 | MCC: 0.013853 | Train loss: 0.9710 | Train acc: 51.84% | Val loss: 0.9062 | Val acc: 54.99% | LR: 0.000735
Epoch: 067 | MCC: 0.033138 | Train loss: 0.9769 | Train acc: 51.69% | Val loss: 0.8401 | Val acc: 58.32% | LR: 0.000722
Epoch: 068 | MCC: 0.026560 | Train loss: 0.9697 | Train acc: 51.36% | Val loss: 0.8554 | Val acc: 57.52% | LR: 0.000709
Epoch: 069 | MCC: 0.009810 | Train loss: 0.9682 | Train acc: 51.45% | Val loss: 0.8523 | Val acc: 57.39% | LR: 0.000696
Epoch: 070 | MCC: 0.002472 | Train loss: 0.9679 | Train acc: 51.41% | Val loss: 0.8519 | Val acc: 57.52% | LR: 0.000683
Epoch: 071 | MCC: 0.024052 | Train loss: 0.9692 | Train acc: 51.35% | Val loss: 0.8717 | Val acc: 56.59% | LR: 0.000670
Epoch: 072 | MCC: 0.013390 | Train loss: 0.9694 | Train acc: 51.36% | Val loss: 0.8507 | Val acc: 57.59% | LR: 0.000657
Epoch: 073 | MCC: 0.028021 | Train loss: 0.9678 | Train acc: 51.44% | Val loss: 0.8265 | Val acc: 59.08% | LR: 0.000644
Epoch: 074 | MCC: 0.018877 | Train loss: 0.9682 | Train acc: 51.40% | Val loss: 0.8566 | Val acc: 57.35% | LR: 0.000630
Epoch: 075 | MCC: 0.008080 | Train loss: 0.9685 | Train acc: 51.31% | Val loss: 0.8692 | Val acc: 56.39% | LR: 0.000617
Epoch: 076 | MCC: 0.010838 | Train loss: 0.9691 | Train acc: 51.34% | Val loss: 0.8460 | Val acc: 57.79% | LR: 0.000604
Epoch: 077 | MCC: 0.033440 | Train loss: 0.9672 | Train acc: 51.43% | Val loss: 0.8248 | Val acc: 59.39% | LR: 0.000591
Epoch: 078 | MCC: 0.037627 | Train loss: 0.9773 | Train acc: 50.80% | Val loss: 0.8404 | Val acc: 58.64% | LR: 0.000578
Epoch: 079 | MCC: 0.031405 | Train loss: 0.9669 | Train acc: 51.43% | Val loss: 0.8370 | Val acc: 58.37% | LR: 0.000565
Epoch: 080 | MCC: 0.027432 | Train loss: 0.9689 | Train acc: 51.20% | Val loss: 0.8321 | Val acc: 58.79% | LR: 0.000552
Epoch: 081 | MCC: 0.020960 | Train loss: 0.9674 | Train acc: 51.22% | Val loss: 0.8366 | Val acc: 58.22% | LR: 0.000539
Epoch: 082 | MCC: 0.030334 | Train loss: 0.9666 | Train acc: 51.98% | Val loss: 0.8213 | Val acc: 58.96% | LR: 0.000525
Epoch: 083 | MCC: 0.079940 | Train loss: 0.9664 | Train acc: 52.17% | Val loss: 0.8141 | Val acc: 59.80% | LR: 0.000513
Epoch: 084 | MCC: 0.031633 | Train loss: 0.9680 | Train acc: 51.99% | Val loss: 0.8527 | Val acc: 57.69% | LR: 0.000500
Epoch: 085 | MCC: 0.023352 | Train loss: 0.9679 | Train acc: 51.96% | Val loss: 0.8462 | Val acc: 57.83% | LR: 0.000487
Epoch: 086 | MCC: 0.031541 | Train loss: 0.9678 | Train acc: 51.97% | Val loss: 0.8166 | Val acc: 59.30% | LR: 0.000474
Epoch: 087 | MCC: 0.041876 | Train loss: 0.9663 | Train acc: 51.99% | Val loss: 0.8162 | Val acc: 59.57% | LR: 0.000461
Epoch: 088 | MCC: 0.019819 | Train loss: 0.9640 | Train acc: 52.23% | Val loss: 0.8414 | Val acc: 57.96% | LR: 0.000449
Epoch: 089 | MCC: 0.050424 | Train loss: 0.9652 | Train acc: 52.15% | Val loss: 0.8234 | Val acc: 58.88% | LR: 0.000436
Epoch: 090 | MCC: 0.079215 | Train loss: 0.9653 | Train acc: 52.05% | Val loss: 0.8089 | Val acc: 59.75% | LR: 0.000423
Epoch: 091 | MCC: 0.084831 | Train loss: 0.9676 | Train acc: 52.07% | Val loss: 0.8074 | Val acc: 59.92% | LR: 0.000411
Epoch: 092 | MCC: 0.023005 | Train loss: 0.9662 | Train acc: 52.05% | Val loss: 0.8383 | Val acc: 58.09% | LR: 0.000399
Epoch: 093 | MCC: 0.022599 | Train loss: 0.9691 | Train acc: 51.90% | Val loss: 0.8310 | Val acc: 58.54% | LR: 0.000387
Epoch: 094 | MCC: 0.022842 | Train loss: 0.9672 | Train acc: 52.15% | Val loss: 0.8312 | Val acc: 58.42% | LR: 0.000374
Epoch: 095 | MCC: 0.043701 | Train loss: 0.9738 | Train acc: 51.68% | Val loss: 0.8137 | Val acc: 59.67% | LR: 0.000362
Epoch: 096 | MCC: 0.040095 | Train loss: 0.9672 | Train acc: 52.05% | Val loss: 0.8303 | Val acc: 58.69% | LR: 0.000351
Epoch: 097 | MCC: 0.096646 | Train loss: 0.9654 | Train acc: 52.12% | Val loss: 0.8034 | Val acc: 60.14% | LR: 0.000339
Epoch: 098 | MCC: 0.034351 | Train loss: 0.9654 | Train acc: 52.12% | Val loss: 0.8289 | Val acc: 58.66% | LR: 0.000327
Epoch: 099 | MCC: 0.033152 | Train loss: 0.9664 | Train acc: 52.14% | Val loss: 0.8179 | Val acc: 59.22% | LR: 0.000316
Epoch: 100 | MCC: 0.034950 | Train loss: 0.9662 | Train acc: 52.12% | Val loss: 0.8205 | Val acc: 59.08% | LR: 0.000304
Epoch: 101 | MCC: 0.088706 | Train loss: 0.9655 | Train acc: 51.98% | Val loss: 0.7955 | Val acc: 60.37% | LR: 0.000293
Epoch: 102 | MCC: 0.051872 | Train loss: 0.9656 | Train acc: 52.17% | Val loss: 0.8065 | Val acc: 59.96% | LR: 0.000282
Epoch: 103 | MCC: 0.082680 | Train loss: 0.9656 | Train acc: 52.12% | Val loss: 0.8168 | Val acc: 59.31% | LR: 0.000271
Epoch: 104 | MCC: 0.034074 | Train loss: 0.9651 | Train acc: 52.15% | Val loss: 0.8220 | Val acc: 58.97% | LR: 0.000260
Epoch: 105 | MCC: 0.033660 | Train loss: 0.9648 | Train acc: 52.13% | Val loss: 0.8295 | Val acc: 58.69% | LR: 0.000250
Epoch: 106 | MCC: 0.064106 | Train loss: 0.9647 | Train acc: 52.07% | Val loss: 0.8170 | Val acc: 59.47% | LR: 0.000239
Epoch: 107 | MCC: 0.052234 | Train loss: 0.9672 | Train acc: 52.02% | Val loss: 0.8077 | Val acc: 59.73% | LR: 0.000229
Epoch: 108 | MCC: 0.052035 | Train loss: 0.9640 | Train acc: 52.18% | Val loss: 0.8129 | Val acc: 59.49% | LR: 0.000219
Epoch: 109 | MCC: 0.064663 | Train loss: 0.9638 | Train acc: 52.15% | Val loss: 0.8109 | Val acc: 59.57% | LR: 0.000209
Epoch: 110 | MCC: 0.053982 | Train loss: 0.9635 | Train acc: 52.23% | Val loss: 0.8123 | Val acc: 59.46% | LR: 0.000200
Epoch: 111 | MCC: 0.054180 | Train loss: 0.9647 | Train acc: 52.21% | Val loss: 0.8119 | Val acc: 59.45% | LR: 0.000190
Epoch: 112 | MCC: 0.059128 | Train loss: 0.9644 | Train acc: 52.21% | Val loss: 0.8054 | Val acc: 59.90% | LR: 0.000181
Epoch: 113 | MCC: 0.034112 | Train loss: 0.9648 | Train acc: 52.13% | Val loss: 0.8136 | Val acc: 59.40% | LR: 0.000172
Epoch: 114 | MCC: 0.030190 | Train loss: 0.9651 | Train acc: 52.17% | Val loss: 0.8245 | Val acc: 58.86% | LR: 0.000163
Epoch: 115 | MCC: 0.033858 | Train loss: 0.9655 | Train acc: 52.18% | Val loss: 0.8174 | Val acc: 59.18% | LR: 0.000154
Epoch: 116 | MCC: 0.035033 | Train loss: 0.9645 | Train acc: 52.08% | Val loss: 0.8118 | Val acc: 59.55% | LR: 0.000145
Epoch: 117 | MCC: 0.037953 | Train loss: 0.9639 | Train acc: 52.29% | Val loss: 0.8121 | Val acc: 59.61% | LR: 0.000137
Epoch: 118 | MCC: 0.034186 | Train loss: 0.9643 | Train acc: 52.12% | Val loss: 0.8177 | Val acc: 59.15% | LR: 0.000129
Epoch: 119 | MCC: 0.037910 | Train loss: 0.9634 | Train acc: 52.17% | Val loss: 0.8160 | Val acc: 59.32% | LR: 0.000121
Epoch: 120 | MCC: 0.034353 | Train loss: 0.9635 | Train acc: 52.16% | Val loss: 0.8170 | Val acc: 59.20% | LR: 0.000114
Epoch: 121 | MCC: 0.063560 | Train loss: 0.9633 | Train acc: 52.22% | Val loss: 0.8037 | Val acc: 60.05% | LR: 0.000106
Epoch: 122 | MCC: 0.062457 | Train loss: 0.9623 | Train acc: 52.23% | Val loss: 0.8097 | Val acc: 59.67% | LR: 0.000099
Epoch: 123 | MCC: 0.037613 | Train loss: 0.9644 | Train acc: 52.14% | Val loss: 0.8163 | Val acc: 59.35% | LR: 0.000092
Epoch: 124 | MCC: 0.034882 | Train loss: 0.9632 | Train acc: 52.22% | Val loss: 0.8154 | Val acc: 59.41% | LR: 0.000085
Epoch: 125 | MCC: 0.033729 | Train loss: 0.9631 | Train acc: 52.14% | Val loss: 0.8160 | Val acc: 59.34% | LR: 0.000079
Epoch: 126 | MCC: 0.038068 | Train loss: 0.9647 | Train acc: 52.09% | Val loss: 0.8157 | Val acc: 59.37% | LR: 0.000073
Epoch: 127 | MCC: 0.037294 | Train loss: 0.9627 | Train acc: 52.26% | Val loss: 0.8170 | Val acc: 59.27% | LR: 0.000067
Epoch: 128 | MCC: 0.041357 | Train loss: 0.9678 | Train acc: 52.16% | Val loss: 0.8135 | Val acc: 59.59% | LR: 0.000061
Epoch: 129 | MCC: 0.034864 | Train loss: 0.9633 | Train acc: 52.07% | Val loss: 0.8148 | Val acc: 59.44% | LR: 0.000055
Epoch: 130 | MCC: 0.039369 | Train loss: 0.9620 | Train acc: 52.21% | Val loss: 0.8155 | Val acc: 59.40% | LR: 0.000050
Epoch: 131 | MCC: 0.035154 | Train loss: 0.9637 | Train acc: 52.19% | Val loss: 0.8139 | Val acc: 59.46% | LR: 0.000045
Epoch: 132 | MCC: 0.036511 | Train loss: 0.9635 | Train acc: 52.19% | Val loss: 0.8149 | Val acc: 59.51% | LR: 0.000040
Epoch: 133 | MCC: 0.034864 | Train loss: 0.9645 | Train acc: 52.13% | Val loss: 0.8143 | Val acc: 59.44% | LR: 0.000036
Epoch: 134 | MCC: 0.035099 | Train loss: 0.9624 | Train acc: 52.25% | Val loss: 0.8151 | Val acc: 59.44% | LR: 0.000032
Epoch: 135 | MCC: 0.036745 | Train loss: 0.9625 | Train acc: 52.26% | Val loss: 0.8151 | Val acc: 59.51% | LR: 0.000028
Epoch: 136 | MCC: 0.032560 | Train loss: 0.9636 | Train acc: 52.20% | Val loss: 0.8150 | Val acc: 59.35% | LR: 0.000024
Epoch: 137 | MCC: 0.034936 | Train loss: 0.9623 | Train acc: 52.36% | Val loss: 0.8144 | Val acc: 59.44% | LR: 0.000021
Epoch: 138 | MCC: 0.034936 | Train loss: 0.9642 | Train acc: 52.18% | Val loss: 0.8145 | Val acc: 59.44% | LR: 0.000018
Epoch: 139 | MCC: 0.032396 | Train loss: 0.9636 | Train acc: 52.30% | Val loss: 0.8146 | Val acc: 59.35% | LR: 0.000015
Epoch: 140 | MCC: 0.033446 | Train loss: 0.9628 | Train acc: 52.21% | Val loss: 0.8147 | Val acc: 59.40% | LR: 0.000012
Epoch: 141 | MCC: 0.033446 | Train loss: 0.9637 | Train acc: 52.14% | Val loss: 0.8149 | Val acc: 59.40% | LR: 0.000010
Epoch: 142 | MCC: 0.033446 | Train loss: 0.9624 | Train acc: 52.23% | Val loss: 0.8149 | Val acc: 59.40% | LR: 0.000008
Epoch: 143 | MCC: 0.033446 | Train loss: 0.9640 | Train acc: 52.27% | Val loss: 0.8147 | Val acc: 59.40% | LR: 0.000006
Epoch: 144 | MCC: 0.033901 | Train loss: 0.9636 | Train acc: 52.23% | Val loss: 0.8148 | Val acc: 59.42% | LR: 0.000004
Epoch: 145 | MCC: 0.033446 | Train loss: 0.9628 | Train acc: 52.19% | Val loss: 0.8148 | Val acc: 59.40% | LR: 0.000003
Epoch: 146 | MCC: 0.033901 | Train loss: 0.9628 | Train acc: 52.25% | Val loss: 0.8147 | Val acc: 59.42% | LR: 0.000002
Epoch: 147 | MCC: 0.033446 | Train loss: 0.9636 | Train acc: 52.23% | Val loss: 0.8148 | Val acc: 59.40% | LR: 0.000002
Epoch: 148 | MCC: 0.033901 | Train loss: 0.9628 | Train acc: 52.23% | Val loss: 0.8147 | Val acc: 59.42% | LR: 0.000001
Epoch: 149 | MCC: 0.033901 | Train loss: 0.9624 | Train acc: 52.31% | Val loss: 0.8147 | Val acc: 59.42% | LR: 0.000001

[I 2025-10-05 08:52:47,785] Trial 7 finished with value: 0.03390073589980602 and parameters: {'lr': 0.0012599429330508861, 'hidden_size': 23, 'dropout': 0.44775918828498984, 'weight_decay': 0.0001072082184964921}. Best is trial 4 with value: 0.04243219271302223.

Epoch: 000 | MCC: 0.033239 | Train loss: 1.0061 | Train acc: 49.39% | Val loss: 1.0002 | Val acc: 52.59% | LR: 0.000884
Epoch: 001 | MCC: 0.026247 | Train loss: 0.9999 | Train acc: 50.33% | Val loss: 1.0002 | Val acc: 53.22% | LR: 0.000884
Epoch: 002 | MCC: 0.031993 | Train loss: 0.9985 | Train acc: 50.75% | Val loss: 1.0018 | Val acc: 50.95% | LR: 0.000883
Epoch: 003 | MCC: 0.042699 | Train loss: 0.9972 | Train acc: 50.90% | Val loss: 0.9992 | Val acc: 51.79% | LR: 0.000883
Epoch: 004 | MCC: 0.044394 | Train loss: 0.9962 | Train acc: 50.82% | Val loss: 0.9987 | Val acc: 52.64% | LR: 0.000882
Epoch: 005 | MCC: 0.042704 | Train loss: 0.9951 | Train acc: 50.83% | Val loss: 0.9986 | Val acc: 52.25% | LR: 0.000881
Epoch: 006 | MCC: 0.034959 | Train loss: 0.9935 | Train acc: 51.02% | Val loss: 0.9970 | Val acc: 53.25% | LR: 0.000879
Epoch: 007 | MCC: 0.040697 | Train loss: 0.9921 | Train acc: 50.83% | Val loss: 0.9968 | Val acc: 52.93% | LR: 0.000878
Epoch: 008 | MCC: 0.027982 | Train loss: 0.9910 | Train acc: 50.89% | Val loss: 0.9878 | Val acc: 54.45% | LR: 0.000876
Epoch: 009 | MCC: 0.036657 | Train loss: 0.9887 | Train acc: 50.96% | Val loss: 0.9855 | Val acc: 54.96% | LR: 0.000875
Epoch: 010 | MCC: 0.039449 | Train loss: 0.9846 | Train acc: 50.94% | Val loss: 0.9742 | Val acc: 55.01% | LR: 0.000873
Epoch: 011 | MCC: 0.026620 | Train loss: 0.9843 | Train acc: 50.98% | Val loss: 0.9532 | Val acc: 54.33% | LR: 0.000870
Epoch: 012 | MCC: 0.032207 | Train loss: 0.9904 | Train acc: 50.10% | Val loss: 0.9634 | Val acc: 54.56% | LR: 0.000868
Epoch: 013 | MCC: 0.034301 | Train loss: 0.9911 | Train acc: 50.85% | Val loss: 1.2003 | Val acc: 54.90% | LR: 0.000865
Epoch: 014 | MCC: 0.027329 | Train loss: 0.9901 | Train acc: 50.86% | Val loss: 0.9375 | Val acc: 54.67% | LR: 0.000863
Epoch: 015 | MCC: 0.028455 | Train loss: 0.9909 | Train acc: 50.85% | Val loss: 0.9390 | Val acc: 54.14% | LR: 0.000860
Epoch: 016 | MCC: 0.033713 | Train loss: 0.9869 | Train acc: 50.92% | Val loss: 0.9378 | Val acc: 54.20% | LR: 0.000857
Epoch: 017 | MCC: 0.029018 | Train loss: 0.9849 | Train acc: 50.79% | Val loss: 0.9451 | Val acc: 54.17% | LR: 0.000853
Epoch: 018 | MCC: 0.031157 | Train loss: 0.9816 | Train acc: 50.89% | Val loss: 0.9498 | Val acc: 54.33% | LR: 0.000850
Epoch: 019 | MCC: 0.031097 | Train loss: 0.9799 | Train acc: 50.93% | Val loss: 0.9400 | Val acc: 54.21% | LR: 0.000846
Epoch: 020 | MCC: 0.029739 | Train loss: 0.9804 | Train acc: 50.93% | Val loss: 0.9371 | Val acc: 54.26% | LR: 0.000842
Epoch: 021 | MCC: 0.034071 | Train loss: 0.9812 | Train acc: 50.86% | Val loss: 0.9369 | Val acc: 54.59% | LR: 0.000838
Epoch: 022 | MCC: 0.031133 | Train loss: 0.9792 | Train acc: 50.98% | Val loss: 0.9537 | Val acc: 54.36% | LR: 0.000834
Epoch: 023 | MCC: 0.032824 | Train loss: 0.9813 | Train acc: 50.90% | Val loss: 0.9387 | Val acc: 54.38% | LR: 0.000830
Epoch: 024 | MCC: 0.034229 | Train loss: 0.9794 | Train acc: 50.89% | Val loss: 0.9374 | Val acc: 54.17% | LR: 0.000825
Epoch: 025 | MCC: 0.019194 | Train loss: 0.9806 | Train acc: 50.98% | Val loss: 0.9433 | Val acc: 53.20% | LR: 0.000820
Epoch: 026 | MCC: 0.009301 | Train loss: 0.9844 | Train acc: 50.79% | Val loss: 0.9386 | Val acc: 52.64% | LR: 0.000815
Epoch: 027 | MCC: 0.015261 | Train loss: 0.9847 | Train acc: 50.84% | Val loss: 0.9396 | Val acc: 53.04% | LR: 0.000810
Epoch: 028 | MCC: 0.019992 | Train loss: 0.9805 | Train acc: 51.03% | Val loss: 0.9412 | Val acc: 53.27% | LR: 0.000805
Epoch: 029 | MCC: 0.024991 | Train loss: 0.9814 | Train acc: 50.93% | Val loss: 0.9396 | Val acc: 53.56% | LR: 0.000800
Epoch: 030 | MCC: 0.026929 | Train loss: 0.9782 | Train acc: 51.04% | Val loss: 0.9376 | Val acc: 53.73% | LR: 0.000794
Epoch: 031 | MCC: 0.030726 | Train loss: 0.9805 | Train acc: 50.82% | Val loss: 0.9351 | Val acc: 53.93% | LR: 0.000789
Epoch: 032 | MCC: 0.032546 | Train loss: 0.9794 | Train acc: 50.88% | Val loss: 0.9350 | Val acc: 54.07% | LR: 0.000783
Epoch: 033 | MCC: 0.032458 | Train loss: 0.9787 | Train acc: 50.97% | Val loss: 0.9332 | Val acc: 54.07% | LR: 0.000777
Epoch: 034 | MCC: 0.031967 | Train loss: 0.9784 | Train acc: 50.95% | Val loss: 0.9309 | Val acc: 54.20% | LR: 0.000771
Epoch: 035 | MCC: 0.032288 | Train loss: 0.9773 | Train acc: 51.03% | Val loss: 0.9308 | Val acc: 54.15% | LR: 0.000765
Epoch: 036 | MCC: 0.032098 | Train loss: 0.9787 | Train acc: 50.80% | Val loss: 0.9286 | Val acc: 54.12% | LR: 0.000758
Epoch: 037 | MCC: 0.033912 | Train loss: 0.9787 | Train acc: 50.88% | Val loss: 0.9286 | Val acc: 54.15% | LR: 0.000752
Epoch: 038 | MCC: 0.033912 | Train loss: 0.9776 | Train acc: 50.98% | Val loss: 0.9272 | Val acc: 54.15% | LR: 0.000745
Epoch: 039 | MCC: 0.032077 | Train loss: 0.9786 | Train acc: 50.93% | Val loss: 0.9251 | Val acc: 54.07% | LR: 0.000738
Epoch: 040 | MCC: 0.032475 | Train loss: 0.9777 | Train acc: 50.93% | Val loss: 0.9248 | Val acc: 54.23% | LR: 0.000731
Epoch: 041 | MCC: 0.034856 | Train loss: 0.9775 | Train acc: 50.89% | Val loss: 0.9236 | Val acc: 54.35% | LR: 0.000724
Epoch: 042 | MCC: 0.033036 | Train loss: 0.9776 | Train acc: 50.89% | Val loss: 0.9227 | Val acc: 54.26% | LR: 0.000717
Epoch: 043 | MCC: 0.032523 | Train loss: 0.9769 | Train acc: 50.97% | Val loss: 0.9184 | Val acc: 54.16% | LR: 0.000710
Epoch: 044 | MCC: 0.033161 | Train loss: 0.9776 | Train acc: 50.95% | Val loss: 0.9197 | Val acc: 54.27% | LR: 0.000702
Epoch: 045 | MCC: 0.032842 | Train loss: 0.9764 | Train acc: 51.06% | Val loss: 0.9177 | Val acc: 54.14% | LR: 0.000695
Epoch: 046 | MCC: 0.031476 | Train loss: 0.9772 | Train acc: 51.00% | Val loss: 0.9191 | Val acc: 54.07% | LR: 0.000687
Epoch: 047 | MCC: 0.030774 | Train loss: 0.9755 | Train acc: 51.02% | Val loss: 0.9134 | Val acc: 54.07% | LR: 0.000679
Epoch: 048 | MCC: 0.030793 | Train loss: 0.9766 | Train acc: 50.99% | Val loss: 0.9140 | Val acc: 54.07% | LR: 0.000671
Epoch: 049 | MCC: 0.031230 | Train loss: 0.9754 | Train acc: 51.06% | Val loss: 0.9102 | Val acc: 54.05% | LR: 0.000663
Epoch: 050 | MCC: 0.029680 | Train loss: 0.9759 | Train acc: 51.06% | Val loss: 0.9077 | Val acc: 53.98% | LR: 0.000655
Epoch: 051 | MCC: 0.032551 | Train loss: 0.9761 | Train acc: 51.04% | Val loss: 0.9071 | Val acc: 54.21% | LR: 0.000647
Epoch: 052 | MCC: 0.032418 | Train loss: 0.9746 | Train acc: 51.03% | Val loss: 0.9049 | Val acc: 55.10% | LR: 0.000639
Epoch: 053 | MCC: 0.054365 | Train loss: 0.9749 | Train acc: 51.10% | Val loss: 0.9016 | Val acc: 56.28% | LR: 0.000631
Epoch: 054 | MCC: 0.035800 | Train loss: 0.9743 | Train acc: 51.07% | Val loss: 0.9027 | Val acc: 56.23% | LR: 0.000622
Epoch: 055 | MCC: 0.037450 | Train loss: 0.9746 | Train acc: 51.15% | Val loss: 0.8951 | Val acc: 56.32% | LR: 0.000614
Epoch: 056 | MCC: 0.038749 | Train loss: 0.9751 | Train acc: 51.10% | Val loss: 0.8974 | Val acc: 56.22% | LR: 0.000605
Epoch: 057 | MCC: 0.026254 | Train loss: 0.9735 | Train acc: 50.97% | Val loss: 0.8957 | Val acc: 56.16% | LR: 0.000597
Epoch: 058 | MCC: 0.006899 | Train loss: 0.9740 | Train acc: 51.68% | Val loss: 0.8952 | Val acc: 55.86% | LR: 0.000588
Epoch: 059 | MCC: 0.011216 | Train loss: 0.9736 | Train acc: 51.65% | Val loss: 0.8905 | Val acc: 56.13% | LR: 0.000579
Epoch: 060 | MCC: 0.000968 | Train loss: 0.9731 | Train acc: 51.87% | Val loss: 0.8917 | Val acc: 55.57% | LR: 0.000570
Epoch: 061 | MCC: -0.001065 | Train loss: 0.9723 | Train acc: 51.83% | Val loss: 0.8930 | Val acc: 55.40% | LR: 0.000561
Epoch: 062 | MCC: 0.000777 | Train loss: 0.9733 | Train acc: 51.77% | Val loss: 0.8877 | Val acc: 55.32% | LR: 0.000552
Epoch: 063 | MCC: 0.004991 | Train loss: 0.9805 | Train acc: 51.32% | Val loss: 0.8915 | Val acc: 55.20% | LR: 0.000543
Epoch: 064 | MCC: 0.007096 | Train loss: 0.9740 | Train acc: 51.86% | Val loss: 0.8897 | Val acc: 55.27% | LR: 0.000534
Epoch: 065 | MCC: 0.001129 | Train loss: 0.9722 | Train acc: 51.41% | Val loss: 0.8894 | Val acc: 55.00% | LR: 0.000525
Epoch: 066 | MCC: 0.001450 | Train loss: 0.9719 | Train acc: 50.96% | Val loss: 0.8881 | Val acc: 55.12% | LR: 0.000516
Epoch: 067 | MCC: 0.000579 | Train loss: 0.9748 | Train acc: 51.40% | Val loss: 0.8912 | Val acc: 55.12% | LR: 0.000507
Epoch: 068 | MCC: 0.008694 | Train loss: 0.9721 | Train acc: 51.85% | Val loss: 0.8862 | Val acc: 55.49% | LR: 0.000498
Epoch: 069 | MCC: 0.009809 | Train loss: 0.9806 | Train acc: 51.71% | Val loss: 0.8887 | Val acc: 55.47% | LR: 0.000489
Epoch: 070 | MCC: 0.004842 | Train loss: 0.9748 | Train acc: 51.99% | Val loss: 0.8950 | Val acc: 55.22% | LR: 0.000480
Epoch: 071 | MCC: 0.011787 | Train loss: 0.9744 | Train acc: 51.96% | Val loss: 0.8918 | Val acc: 55.61% | LR: 0.000470
Epoch: 072 | MCC: 0.010835 | Train loss: 0.9720 | Train acc: 51.93% | Val loss: 0.8880 | Val acc: 55.54% | LR: 0.000461
Epoch: 073 | MCC: 0.011712 | Train loss: 0.9725 | Train acc: 51.93% | Val loss: 0.8850 | Val acc: 55.69% | LR: 0.000452
Epoch: 074 | MCC: 0.014264 | Train loss: 0.9698 | Train acc: 51.95% | Val loss: 0.8817 | Val acc: 55.71% | LR: 0.000443
Epoch: 075 | MCC: 0.008033 | Train loss: 0.9682 | Train acc: 51.88% | Val loss: 0.8872 | Val acc: 55.34% | LR: 0.000433
Epoch: 076 | MCC: 0.011881 | Train loss: 0.9706 | Train acc: 51.95% | Val loss: 0.8782 | Val acc: 56.05% | LR: 0.000424
Epoch: 077 | MCC: 0.012225 | Train loss: 0.9687 | Train acc: 52.01% | Val loss: 0.8831 | Val acc: 55.81% | LR: 0.000415
Epoch: 078 | MCC: 0.015138 | Train loss: 0.9701 | Train acc: 51.93% | Val loss: 0.8701 | Val acc: 56.74% | LR: 0.000406
Epoch: 079 | MCC: 0.017924 | Train loss: 0.9685 | Train acc: 52.06% | Val loss: 0.8686 | Val acc: 56.98% | LR: 0.000396
Epoch: 080 | MCC: 0.013422 | Train loss: 0.9697 | Train acc: 52.06% | Val loss: 0.8775 | Val acc: 56.42% | LR: 0.000387
Epoch: 081 | MCC: 0.017269 | Train loss: 0.9692 | Train acc: 51.89% | Val loss: 0.8659 | Val acc: 57.00% | LR: 0.000378
Epoch: 082 | MCC: 0.014573 | Train loss: 0.9678 | Train acc: 51.93% | Val loss: 0.8708 | Val acc: 56.83% | LR: 0.000369
Epoch: 083 | MCC: 0.012091 | Train loss: 0.9684 | Train acc: 51.95% | Val loss: 0.8628 | Val acc: 57.61% | LR: 0.000360
Epoch: 084 | MCC: -0.001696 | Train loss: 0.9758 | Train acc: 52.10% | Val loss: 0.8702 | Val acc: 56.81% | LR: 0.000351
Epoch: 085 | MCC: -0.000421 | Train loss: 0.9672 | Train acc: 52.04% | Val loss: 0.8630 | Val acc: 57.17% | LR: 0.000342
Epoch: 086 | MCC: 0.002157 | Train loss: 0.9662 | Train acc: 52.05% | Val loss: 0.8660 | Val acc: 57.22% | LR: 0.000333
Epoch: 087 | MCC: -0.003619 | Train loss: 0.9672 | Train acc: 52.08% | Val loss: 0.8676 | Val acc: 56.71% | LR: 0.000324
Epoch: 088 | MCC: 0.000549 | Train loss: 0.9672 | Train acc: 52.01% | Val loss: 0.8610 | Val acc: 57.20% | LR: 0.000315
Epoch: 089 | MCC: 0.007835 | Train loss: 0.9681 | Train acc: 51.95% | Val loss: 0.8547 | Val acc: 57.93% | LR: 0.000306
Epoch: 090 | MCC: -0.003097 | Train loss: 0.9804 | Train acc: 51.96% | Val loss: 0.8622 | Val acc: 57.00% | LR: 0.000297
Epoch: 091 | MCC: 0.009824 | Train loss: 0.9697 | Train acc: 51.89% | Val loss: 0.8537 | Val acc: 57.93% | LR: 0.000289
Epoch: 092 | MCC: 0.001521 | Train loss: 0.9671 | Train acc: 52.04% | Val loss: 0.8615 | Val acc: 57.15% | LR: 0.000280
Epoch: 093 | MCC: -0.002385 | Train loss: 0.9675 | Train acc: 52.04% | Val loss: 0.8609 | Val acc: 57.17% | LR: 0.000271
Epoch: 094 | MCC: -0.002581 | Train loss: 0.9671 | Train acc: 52.01% | Val loss: 0.8604 | Val acc: 57.13% | LR: 0.000263
Epoch: 095 | MCC: -0.017403 | Train loss: 0.9648 | Train acc: 52.19% | Val loss: 0.8667 | Val acc: 56.42% | LR: 0.000255
Epoch: 096 | MCC: -0.015694 | Train loss: 0.9685 | Train acc: 51.94% | Val loss: 0.8659 | Val acc: 56.59% | LR: 0.000246
Epoch: 097 | MCC: -0.014439 | Train loss: 0.9661 | Train acc: 52.03% | Val loss: 0.8696 | Val acc: 56.44% | LR: 0.000238
Epoch: 098 | MCC: -0.010805 | Train loss: 0.9670 | Train acc: 52.01% | Val loss: 0.8639 | Val acc: 56.64% | LR: 0.000230
Epoch: 099 | MCC: -0.011201 | Train loss: 0.9672 | Train acc: 52.00% | Val loss: 0.8694 | Val acc: 56.56% | LR: 0.000222
Epoch: 100 | MCC: -0.015271 | Train loss: 0.9659 | Train acc: 52.09% | Val loss: 0.8664 | Val acc: 56.66% | LR: 0.000214
Epoch: 101 | MCC: -0.015190 | Train loss: 0.9645 | Train acc: 52.11% | Val loss: 0.8698 | Val acc: 56.47% | LR: 0.000206
Epoch: 102 | MCC: -0.018418 | Train loss: 0.9662 | Train acc: 51.99% | Val loss: 0.8684 | Val acc: 56.37% | LR: 0.000198
Epoch: 103 | MCC: -0.010382 | Train loss: 0.9647 | Train acc: 52.06% | Val loss: 0.8706 | Val acc: 56.61% | LR: 0.000191
Epoch: 104 | MCC: -0.002632 | Train loss: 0.9670 | Train acc: 51.98% | Val loss: 0.8611 | Val acc: 57.13% | LR: 0.000183
Epoch: 105 | MCC: -0.007319 | Train loss: 0.9669 | Train acc: 51.94% | Val loss: 0.8715 | Val acc: 56.76% | LR: 0.000176
Epoch: 106 | MCC: -0.012713 | Train loss: 0.9668 | Train acc: 51.95% | Val loss: 0.8669 | Val acc: 56.52% | LR: 0.000168
Epoch: 107 | MCC: -0.005973 | Train loss: 0.9717 | Train acc: 52.10% | Val loss: 0.8621 | Val acc: 56.93% | LR: 0.000161
Epoch: 108 | MCC: -0.013808 | Train loss: 0.9658 | Train acc: 52.06% | Val loss: 0.8671 | Val acc: 56.54% | LR: 0.000154
Epoch: 109 | MCC: -0.012692 | Train loss: 0.9666 | Train acc: 51.95% | Val loss: 0.8658 | Val acc: 56.54% | LR: 0.000147
Epoch: 110 | MCC: -0.011513 | Train loss: 0.9649 | Train acc: 52.14% | Val loss: 0.8677 | Val acc: 56.56% | LR: 0.000140
Epoch: 111 | MCC: -0.013204 | Train loss: 0.9631 | Train acc: 52.18% | Val loss: 0.8702 | Val acc: 56.44% | LR: 0.000134
Epoch: 112 | MCC: -0.013533 | Train loss: 0.9649 | Train acc: 52.03% | Val loss: 0.8659 | Val acc: 56.61% | LR: 0.000127
Epoch: 113 | MCC: -0.019435 | Train loss: 0.9634 | Train acc: 52.16% | Val loss: 0.8682 | Val acc: 56.30% | LR: 0.000121
Epoch: 114 | MCC: -0.011352 | Train loss: 0.9660 | Train acc: 52.06% | Val loss: 0.8671 | Val acc: 56.71% | LR: 0.000114
Epoch: 115 | MCC: -0.010010 | Train loss: 0.9656 | Train acc: 52.05% | Val loss: 0.8697 | Val acc: 56.56% | LR: 0.000108
Epoch: 116 | MCC: -0.012668 | Train loss: 0.9666 | Train acc: 52.18% | Val loss: 0.8695 | Val acc: 56.52% | LR: 0.000102
Epoch: 117 | MCC: -0.010053 | Train loss: 1.0155 | Train acc: 51.99% | Val loss: 0.8690 | Val acc: 56.71% | LR: 0.000097
Epoch: 118 | MCC: -0.009291 | Train loss: 0.9667 | Train acc: 51.95% | Val loss: 0.8693 | Val acc: 56.74% | LR: 0.000091
Epoch: 119 | MCC: -0.012644 | Train loss: 0.9817 | Train acc: 52.02% | Val loss: 0.8707 | Val acc: 56.47% | LR: 0.000085
Epoch: 120 | MCC: -0.012987 | Train loss: 0.9779 | Train acc: 52.13% | Val loss: 0.8707 | Val acc: 56.37% | LR: 0.000080
Epoch: 121 | MCC: -0.010930 | Train loss: 0.9650 | Train acc: 52.07% | Val loss: 0.8668 | Val acc: 56.69% | LR: 0.000075
Epoch: 122 | MCC: -0.016774 | Train loss: 0.9643 | Train acc: 52.14% | Val loss: 0.8678 | Val acc: 56.44% | LR: 0.000070
Epoch: 123 | MCC: -0.012231 | Train loss: 0.9633 | Train acc: 52.17% | Val loss: 0.8689 | Val acc: 56.61% | LR: 0.000065
Epoch: 124 | MCC: -0.016192 | Train loss: 0.9789 | Train acc: 52.02% | Val loss: 0.8687 | Val acc: 56.47% | LR: 0.000060
Epoch: 125 | MCC: -0.012069 | Train loss: 0.9652 | Train acc: 52.03% | Val loss: 0.8649 | Val acc: 56.76% | LR: 0.000056
Epoch: 126 | MCC: -0.013149 | Train loss: 0.9635 | Train acc: 52.13% | Val loss: 0.8684 | Val acc: 56.49% | LR: 0.000051
Epoch: 127 | MCC: -0.017061 | Train loss: 0.9646 | Train acc: 52.05% | Val loss: 0.8681 | Val acc: 56.42% | LR: 0.000047
Epoch: 128 | MCC: -0.012809 | Train loss: 0.9639 | Train acc: 52.07% | Val loss: 0.8663 | Val acc: 56.66% | LR: 0.000043
Epoch: 129 | MCC: -0.014134 | Train loss: 0.9649 | Train acc: 52.05% | Val loss: 0.8666 | Val acc: 56.59% | LR: 0.000039
Epoch: 130 | MCC: -0.012604 | Train loss: 0.9633 | Train acc: 52.13% | Val loss: 0.8672 | Val acc: 56.64% | LR: 0.000036
Epoch: 131 | MCC: -0.012604 | Train loss: 0.9643 | Train acc: 52.08% | Val loss: 0.8674 | Val acc: 56.64% | LR: 0.000032
Epoch: 132 | MCC: -0.012971 | Train loss: 0.9637 | Train acc: 52.13% | Val loss: 0.8670 | Val acc: 56.64% | LR: 0.000029
Epoch: 133 | MCC: -0.011165 | Train loss: 0.9641 | Train acc: 52.09% | Val loss: 0.8663 | Val acc: 56.76% | LR: 0.000026
Epoch: 134 | MCC: -0.011319 | Train loss: 0.9632 | Train acc: 52.17% | Val loss: 0.8665 | Val acc: 56.74% | LR: 0.000023
Epoch: 135 | MCC: -0.011661 | Train loss: 0.9649 | Train acc: 52.04% | Val loss: 0.8672 | Val acc: 56.71% | LR: 0.000020
Epoch: 136 | MCC: -0.013557 | Train loss: 0.9630 | Train acc: 52.09% | Val loss: 0.8671 | Val acc: 56.61% | LR: 0.000017
Epoch: 137 | MCC: -0.012299 | Train loss: 0.9650 | Train acc: 52.00% | Val loss: 0.8666 | Val acc: 56.69% | LR: 0.000015
Epoch: 138 | MCC: -0.013163 | Train loss: 0.9649 | Train acc: 52.00% | Val loss: 0.8669 | Val acc: 56.64% | LR: 0.000013
Epoch: 139 | MCC: -0.013163 | Train loss: 0.9644 | Train acc: 52.03% | Val loss: 0.8670 | Val acc: 56.64% | LR: 0.000011
Epoch: 140 | MCC: -0.012119 | Train loss: 0.9645 | Train acc: 52.04% | Val loss: 0.8668 | Val acc: 56.69% | LR: 0.000009
Epoch: 141 | MCC: -0.013557 | Train loss: 0.9655 | Train acc: 51.96% | Val loss: 0.8671 | Val acc: 56.61% | LR: 0.000007
Epoch: 142 | MCC: -0.012119 | Train loss: 0.9652 | Train acc: 51.98% | Val loss: 0.8669 | Val acc: 56.69% | LR: 0.000006
Epoch: 143 | MCC: -0.011726 | Train loss: 0.9641 | Train acc: 52.10% | Val loss: 0.8667 | Val acc: 56.71% | LR: 0.000004
Epoch: 144 | MCC: -0.013163 | Train loss: 0.9638 | Train acc: 52.09% | Val loss: 0.8669 | Val acc: 56.64% | LR: 0.000003
Epoch: 145 | MCC: -0.013163 | Train loss: 0.9632 | Train acc: 52.08% | Val loss: 0.8670 | Val acc: 56.64% | LR: 0.000003
Epoch: 146 | MCC: -0.013163 | Train loss: 0.9653 | Train acc: 51.95% | Val loss: 0.8669 | Val acc: 56.64% | LR: 0.000002
Epoch: 147 | MCC: -0.013621 | Train loss: 0.9653 | Train acc: 51.98% | Val loss: 0.8669 | Val acc: 56.61% | LR: 0.000001
Epoch: 148 | MCC: -0.013163 | Train loss: 0.9632 | Train acc: 52.12% | Val loss: 0.8669 | Val acc: 56.64% | LR: 0.000001
Epoch: 149 | MCC: -0.013163 | Train loss: 0.9639 | Train acc: 52.06% | Val loss: 0.8669 | Val acc: 56.64% | LR: 0.000001

[I 2025-10-05 08:54:40,750] Trial 8 finished with value: -0.013163488358259201 and parameters: {'lr': 0.0008842155892467394, 'hidden_size': 22, 'dropout': 0.2691846162969495, 'weight_decay': 0.0044343648567938074}. Best is trial 4 with value: 0.04243219271302223.

Epoch: 000 | MCC: 0.011666 | Train loss: 1.0008 | Train acc: 50.38% | Val loss: 0.9917 | Val acc: 51.57% | LR: 0.000147
Epoch: 001 | MCC: 0.014161 | Train loss: 1.0012 | Train acc: 50.66% | Val loss: 0.9906 | Val acc: 52.21% | LR: 0.000147
Epoch: 002 | MCC: 0.016027 | Train loss: 0.9993 | Train acc: 50.76% | Val loss: 0.9883 | Val acc: 52.53% | LR: 0.000147
Epoch: 003 | MCC: 0.018112 | Train loss: 0.9993 | Train acc: 50.78% | Val loss: 0.9865 | Val acc: 53.18% | LR: 0.000147
Epoch: 004 | MCC: 0.023845 | Train loss: 0.9982 | Train acc: 50.78% | Val loss: 0.9849 | Val acc: 53.84% | LR: 0.000147
Epoch: 005 | MCC: 0.037808 | Train loss: 1.0444 | Train acc: 50.82% | Val loss: 0.9844 | Val acc: 54.62% | LR: 0.000146
Epoch: 006 | MCC: 0.039666 | Train loss: 0.9973 | Train acc: 50.96% | Val loss: 0.9836 | Val acc: 54.93% | LR: 0.000146
Epoch: 007 | MCC: 0.039860 | Train loss: 1.0011 | Train acc: 50.77% | Val loss: 0.9829 | Val acc: 55.17% | LR: 0.000146
Epoch: 008 | MCC: 0.038953 | Train loss: 0.9975 | Train acc: 50.81% | Val loss: 0.9817 | Val acc: 55.18% | LR: 0.000146
Epoch: 009 | MCC: 0.042414 | Train loss: 0.9964 | Train acc: 50.92% | Val loss: 0.9804 | Val acc: 55.54% | LR: 0.000145
Epoch: 010 | MCC: 0.046344 | Train loss: 0.9957 | Train acc: 51.00% | Val loss: 0.9784 | Val acc: 55.87% | LR: 0.000145
Epoch: 011 | MCC: 0.043261 | Train loss: 0.9994 | Train acc: 50.92% | Val loss: 0.9770 | Val acc: 55.87% | LR: 0.000145
Epoch: 012 | MCC: 0.042119 | Train loss: 0.9949 | Train acc: 50.91% | Val loss: 0.9747 | Val acc: 55.81% | LR: 0.000144
Epoch: 013 | MCC: 0.046795 | Train loss: 0.9972 | Train acc: 50.83% | Val loss: 0.9729 | Val acc: 55.88% | LR: 0.000144
Epoch: 014 | MCC: 0.049582 | Train loss: 0.9950 | Train acc: 50.77% | Val loss: 0.9704 | Val acc: 56.15% | LR: 0.000143
Epoch: 015 | MCC: 0.053775 | Train loss: 0.9943 | Train acc: 50.77% | Val loss: 0.9685 | Val acc: 56.03% | LR: 0.000143
Epoch: 016 | MCC: 0.046478 | Train loss: 0.9943 | Train acc: 50.83% | Val loss: 0.9662 | Val acc: 55.90% | LR: 0.000142
Epoch: 017 | MCC: 0.043603 | Train loss: 0.9956 | Train acc: 50.56% | Val loss: 0.9657 | Val acc: 55.58% | LR: 0.000142
Epoch: 018 | MCC: 0.041649 | Train loss: 0.9947 | Train acc: 50.39% | Val loss: 0.9644 | Val acc: 55.52% | LR: 0.000141
Epoch: 019 | MCC: 0.038957 | Train loss: 0.9920 | Train acc: 50.76% | Val loss: 0.9632 | Val acc: 55.39% | LR: 0.000141
Epoch: 020 | MCC: 0.037452 | Train loss: 1.0001 | Train acc: 49.91% | Val loss: 0.9623 | Val acc: 55.28% | LR: 0.000140
Epoch: 021 | MCC: 0.039829 | Train loss: 0.9976 | Train acc: 50.06% | Val loss: 0.9604 | Val acc: 55.51% | LR: 0.000139
Epoch: 022 | MCC: 0.041195 | Train loss: 0.9987 | Train acc: 50.00% | Val loss: 0.9582 | Val acc: 55.62% | LR: 0.000139
Epoch: 023 | MCC: 0.040269 | Train loss: 0.9987 | Train acc: 49.88% | Val loss: 0.9567 | Val acc: 55.66% | LR: 0.000138
Epoch: 024 | MCC: 0.041014 | Train loss: 0.9989 | Train acc: 49.92% | Val loss: 0.9550 | Val acc: 55.66% | LR: 0.000137
Epoch: 025 | MCC: 0.044344 | Train loss: 0.9990 | Train acc: 49.87% | Val loss: 0.9526 | Val acc: 55.79% | LR: 0.000136
Epoch: 026 | MCC: 0.046189 | Train loss: 0.9975 | Train acc: 49.97% | Val loss: 0.9502 | Val acc: 55.90% | LR: 0.000136
Epoch: 027 | MCC: 0.043638 | Train loss: 0.9959 | Train acc: 50.08% | Val loss: 0.9483 | Val acc: 55.80% | LR: 0.000135
Epoch: 028 | MCC: 0.046595 | Train loss: 0.9959 | Train acc: 50.06% | Val loss: 0.9459 | Val acc: 55.99% | LR: 0.000134
Epoch: 029 | MCC: 0.045190 | Train loss: 0.9954 | Train acc: 50.07% | Val loss: 0.9443 | Val acc: 55.95% | LR: 0.000133
Epoch: 030 | MCC: 0.050285 | Train loss: 0.9961 | Train acc: 50.00% | Val loss: 0.9414 | Val acc: 56.27% | LR: 0.000132
Epoch: 031 | MCC: 0.046728 | Train loss: 0.9962 | Train acc: 49.96% | Val loss: 0.9399 | Val acc: 56.30% | LR: 0.000131
Epoch: 032 | MCC: 0.046170 | Train loss: 0.9962 | Train acc: 49.95% | Val loss: 0.9374 | Val acc: 56.34% | LR: 0.000130
Epoch: 033 | MCC: 0.041965 | Train loss: 0.9952 | Train acc: 50.07% | Val loss: 0.9354 | Val acc: 56.30% | LR: 0.000129
Epoch: 034 | MCC: 0.042327 | Train loss: 0.9957 | Train acc: 49.91% | Val loss: 0.9328 | Val acc: 56.37% | LR: 0.000128
Epoch: 035 | MCC: 0.038056 | Train loss: 0.9940 | Train acc: 50.13% | Val loss: 0.9309 | Val acc: 56.32% | LR: 0.000127
Epoch: 036 | MCC: 0.035242 | Train loss: 0.9959 | Train acc: 49.86% | Val loss: 0.9283 | Val acc: 56.10% | LR: 0.000126
Epoch: 037 | MCC: 0.031691 | Train loss: 0.9956 | Train acc: 49.85% | Val loss: 0.9263 | Val acc: 56.23% | LR: 0.000125
Epoch: 038 | MCC: 0.036398 | Train loss: 0.9935 | Train acc: 50.01% | Val loss: 0.9240 | Val acc: 56.47% | LR: 0.000124
Epoch: 039 | MCC: 0.036892 | Train loss: 0.9945 | Train acc: 49.98% | Val loss: 0.9214 | Val acc: 56.43% | LR: 0.000123
Epoch: 040 | MCC: 0.041494 | Train loss: 0.9935 | Train acc: 50.05% | Val loss: 0.9194 | Val acc: 56.59% | LR: 0.000122
Epoch: 041 | MCC: 0.042600 | Train loss: 0.9957 | Train acc: 49.85% | Val loss: 0.9179 | Val acc: 56.73% | LR: 0.000121
Epoch: 042 | MCC: 0.036637 | Train loss: 0.9939 | Train acc: 50.01% | Val loss: 0.9150 | Val acc: 56.64% | LR: 0.000119
Epoch: 043 | MCC: 0.040675 | Train loss: 0.9936 | Train acc: 50.01% | Val loss: 0.9129 | Val acc: 56.79% | LR: 0.000118
Epoch: 044 | MCC: 0.042739 | Train loss: 0.9939 | Train acc: 50.00% | Val loss: 0.9109 | Val acc: 56.83% | LR: 0.000117
Epoch: 045 | MCC: 0.042953 | Train loss: 0.9924 | Train acc: 50.17% | Val loss: 0.9100 | Val acc: 56.85% | LR: 0.000116
Epoch: 046 | MCC: 0.036819 | Train loss: 0.9919 | Train acc: 50.11% | Val loss: 0.9087 | Val acc: 56.72% | LR: 0.000114
Epoch: 047 | MCC: 0.037010 | Train loss: 0.9942 | Train acc: 49.90% | Val loss: 0.9075 | Val acc: 56.69% | LR: 0.000113
Epoch: 048 | MCC: 0.031337 | Train loss: 0.9930 | Train acc: 50.06% | Val loss: 0.9068 | Val acc: 56.69% | LR: 0.000112
Epoch: 049 | MCC: 0.034439 | Train loss: 0.9931 | Train acc: 50.02% | Val loss: 0.9064 | Val acc: 56.84% | LR: 0.000111
Epoch: 050 | MCC: 0.031734 | Train loss: 0.9926 | Train acc: 50.10% | Val loss: 0.9052 | Val acc: 56.62% | LR: 0.000109
Epoch: 051 | MCC: 0.035328 | Train loss: 0.9920 | Train acc: 50.02% | Val loss: 0.9045 | Val acc: 56.81% | LR: 0.000108
Epoch: 052 | MCC: 0.034665 | Train loss: 0.9924 | Train acc: 50.01% | Val loss: 0.9033 | Val acc: 56.79% | LR: 0.000106
Epoch: 053 | MCC: 0.034925 | Train loss: 0.9917 | Train acc: 50.16% | Val loss: 0.9031 | Val acc: 56.79% | LR: 0.000105
Epoch: 054 | MCC: 0.034510 | Train loss: 0.9909 | Train acc: 50.21% | Val loss: 0.9024 | Val acc: 56.75% | LR: 0.000104
Epoch: 055 | MCC: 0.037346 | Train loss: 0.9908 | Train acc: 50.00% | Val loss: 0.9013 | Val acc: 56.88% | LR: 0.000102
Epoch: 056 | MCC: 0.038638 | Train loss: 0.9910 | Train acc: 49.96% | Val loss: 0.9003 | Val acc: 56.93% | LR: 0.000101
Epoch: 057 | MCC: 0.036827 | Train loss: 0.9914 | Train acc: 49.91% | Val loss: 0.8994 | Val acc: 56.81% | LR: 0.000099
Epoch: 058 | MCC: 0.035861 | Train loss: 0.9907 | Train acc: 50.04% | Val loss: 0.8990 | Val acc: 56.73% | LR: 0.000098
Epoch: 059 | MCC: 0.034421 | Train loss: 0.9905 | Train acc: 49.98% | Val loss: 0.8981 | Val acc: 56.63% | LR: 0.000097
Epoch: 060 | MCC: 0.033623 | Train loss: 0.9909 | Train acc: 50.03% | Val loss: 0.8972 | Val acc: 56.54% | LR: 0.000095
Epoch: 061 | MCC: 0.033543 | Train loss: 0.9913 | Train acc: 49.84% | Val loss: 0.8963 | Val acc: 56.55% | LR: 0.000094
Epoch: 062 | MCC: 0.028266 | Train loss: 0.9986 | Train acc: 50.56% | Val loss: 0.9176 | Val acc: 56.54% | LR: 0.000092
Epoch: 063 | MCC: 0.028770 | Train loss: 1.0268 | Train acc: 50.90% | Val loss: 0.9338 | Val acc: 56.00% | LR: 0.000091
Epoch: 064 | MCC: 0.035617 | Train loss: 1.0290 | Train acc: 51.16% | Val loss: 0.9020 | Val acc: 56.17% | LR: 0.000089
Epoch: 065 | MCC: 0.028929 | Train loss: 1.0159 | Train acc: 50.84% | Val loss: 0.9535 | Val acc: 56.00% | LR: 0.000088
Epoch: 066 | MCC: 0.033890 | Train loss: 1.0025 | Train acc: 50.92% | Val loss: 0.9316 | Val acc: 56.00% | LR: 0.000086
Epoch: 067 | MCC: 0.033408 | Train loss: 0.9969 | Train acc: 50.86% | Val loss: 0.9125 | Val acc: 56.20% | LR: 0.000085
Epoch: 068 | MCC: 0.028969 | Train loss: 1.0121 | Train acc: 51.03% | Val loss: 0.9299 | Val acc: 55.85% | LR: 0.000083
Epoch: 069 | MCC: 0.035723 | Train loss: 1.0064 | Train acc: 51.12% | Val loss: 0.9358 | Val acc: 56.12% | LR: 0.000082
Epoch: 070 | MCC: 0.033988 | Train loss: 1.0327 | Train acc: 50.88% | Val loss: 0.9071 | Val acc: 55.96% | LR: 0.000080
Epoch: 071 | MCC: 0.030884 | Train loss: 1.0003 | Train acc: 50.71% | Val loss: 0.9069 | Val acc: 55.67% | LR: 0.000079
Epoch: 072 | MCC: 0.026454 | Train loss: 0.9972 | Train acc: 51.07% | Val loss: 0.9135 | Val acc: 55.46% | LR: 0.000077
Epoch: 073 | MCC: 0.026784 | Train loss: 0.9955 | Train acc: 50.85% | Val loss: 0.9184 | Val acc: 55.29% | LR: 0.000076
Epoch: 074 | MCC: 0.030259 | Train loss: 0.9949 | Train acc: 50.92% | Val loss: 0.9180 | Val acc: 55.45% | LR: 0.000074
Epoch: 075 | MCC: 0.031495 | Train loss: 1.0060 | Train acc: 51.04% | Val loss: 0.9180 | Val acc: 55.57% | LR: 0.000072
Epoch: 076 | MCC: 0.030794 | Train loss: 1.0036 | Train acc: 50.96% | Val loss: 0.9279 | Val acc: 55.46% | LR: 0.000071
Epoch: 077 | MCC: 0.029152 | Train loss: 0.9968 | Train acc: 50.91% | Val loss: 0.9080 | Val acc: 55.36% | LR: 0.000069
Epoch: 078 | MCC: 0.031330 | Train loss: 0.9944 | Train acc: 51.04% | Val loss: 0.9118 | Val acc: 55.51% | LR: 0.000068
Epoch: 079 | MCC: 0.027632 | Train loss: 0.9951 | Train acc: 50.89% | Val loss: 0.9053 | Val acc: 55.39% | LR: 0.000066
Epoch: 080 | MCC: 0.025761 | Train loss: 0.9962 | Train acc: 51.00% | Val loss: 0.9284 | Val acc: 55.24% | LR: 0.000065
Epoch: 081 | MCC: 0.028843 | Train loss: 0.9930 | Train acc: 51.02% | Val loss: 0.9067 | Val acc: 55.39% | LR: 0.000063
Epoch: 082 | MCC: 0.032252 | Train loss: 0.9933 | Train acc: 50.90% | Val loss: 0.9074 | Val acc: 55.49% | LR: 0.000062
Epoch: 083 | MCC: 0.031427 | Train loss: 1.0408 | Train acc: 50.91% | Val loss: 1.0005 | Val acc: 55.39% | LR: 0.000060
Epoch: 084 | MCC: 0.028665 | Train loss: 0.9914 | Train acc: 51.12% | Val loss: 0.9313 | Val acc: 55.22% | LR: 0.000059
Epoch: 085 | MCC: 0.028733 | Train loss: 1.0028 | Train acc: 50.85% | Val loss: 0.9203 | Val acc: 55.17% | LR: 0.000057
Epoch: 086 | MCC: 0.025546 | Train loss: 0.9951 | Train acc: 50.84% | Val loss: 0.9322 | Val acc: 54.90% | LR: 0.000056
Epoch: 087 | MCC: 0.026286 | Train loss: 1.0034 | Train acc: 50.94% | Val loss: 0.9498 | Val acc: 55.05% | LR: 0.000054
Epoch: 088 | MCC: 0.031742 | Train loss: 1.0200 | Train acc: 50.99% | Val loss: 0.9160 | Val acc: 55.36% | LR: 0.000053
Epoch: 089 | MCC: 0.033805 | Train loss: 0.9949 | Train acc: 50.77% | Val loss: 0.9142 | Val acc: 55.44% | LR: 0.000051
Epoch: 090 | MCC: 0.030283 | Train loss: 0.9925 | Train acc: 50.84% | Val loss: 0.9126 | Val acc: 55.29% | LR: 0.000050
Epoch: 091 | MCC: 0.031063 | Train loss: 0.9936 | Train acc: 50.92% | Val loss: 0.9044 | Val acc: 55.40% | LR: 0.000049
Epoch: 092 | MCC: 0.030652 | Train loss: 0.9904 | Train acc: 50.95% | Val loss: 0.9423 | Val acc: 55.29% | LR: 0.000047
Epoch: 093 | MCC: 0.026916 | Train loss: 0.9953 | Train acc: 50.96% | Val loss: 0.9190 | Val acc: 55.23% | LR: 0.000046
Epoch: 094 | MCC: 0.028171 | Train loss: 0.9922 | Train acc: 50.98% | Val loss: 0.9124 | Val acc: 55.30% | LR: 0.000044
Epoch: 095 | MCC: 0.030876 | Train loss: 0.9907 | Train acc: 50.89% | Val loss: 0.9400 | Val acc: 55.35% | LR: 0.000043
Epoch: 096 | MCC: 0.031309 | Train loss: 1.0006 | Train acc: 51.00% | Val loss: 0.9403 | Val acc: 55.38% | LR: 0.000042
Epoch: 097 | MCC: 0.026916 | Train loss: 0.9930 | Train acc: 50.74% | Val loss: 0.9226 | Val acc: 55.23% | LR: 0.000040
Epoch: 098 | MCC: 0.026152 | Train loss: 1.0025 | Train acc: 51.00% | Val loss: 0.9237 | Val acc: 55.23% | LR: 0.000039
Epoch: 099 | MCC: 0.030612 | Train loss: 0.9892 | Train acc: 51.00% | Val loss: 0.9118 | Val acc: 55.35% | LR: 0.000038
Epoch: 100 | MCC: 0.030609 | Train loss: 0.9980 | Train acc: 50.95% | Val loss: 0.9062 | Val acc: 55.38% | LR: 0.000036
Epoch: 101 | MCC: 0.028045 | Train loss: 0.9901 | Train acc: 50.89% | Val loss: 0.9125 | Val acc: 55.25% | LR: 0.000035
Epoch: 102 | MCC: 0.030082 | Train loss: 0.9927 | Train acc: 50.84% | Val loss: 0.9051 | Val acc: 55.35% | LR: 0.000034
Epoch: 103 | MCC: 0.029821 | Train loss: 1.0242 | Train acc: 50.93% | Val loss: 0.9244 | Val acc: 55.30% | LR: 0.000032
Epoch: 104 | MCC: 0.030587 | Train loss: 0.9901 | Train acc: 50.86% | Val loss: 0.9092 | Val acc: 55.38% | LR: 0.000031
Epoch: 105 | MCC: 0.027999 | Train loss: 0.9910 | Train acc: 50.80% | Val loss: 0.9122 | Val acc: 55.23% | LR: 0.000030
Epoch: 106 | MCC: 0.027999 | Train loss: 0.9910 | Train acc: 50.97% | Val loss: 0.9419 | Val acc: 55.23% | LR: 0.000029
Epoch: 107 | MCC: 0.030108 | Train loss: 0.9980 | Train acc: 50.94% | Val loss: 0.9082 | Val acc: 55.33% | LR: 0.000027
Epoch: 108 | MCC: 0.027999 | Train loss: 1.0001 | Train acc: 50.81% | Val loss: 0.9149 | Val acc: 55.23% | LR: 0.000026
Epoch: 109 | MCC: 0.028482 | Train loss: 0.9922 | Train acc: 50.81% | Val loss: 0.9445 | Val acc: 55.23% | LR: 0.000025
Epoch: 110 | MCC: 0.029010 | Train loss: 0.9903 | Train acc: 50.85% | Val loss: 0.9100 | Val acc: 55.25% | LR: 0.000024
Epoch: 111 | MCC: 0.029010 | Train loss: 0.9934 | Train acc: 51.10% | Val loss: 0.9098 | Val acc: 55.25% | LR: 0.000023
Epoch: 112 | MCC: 0.027620 | Train loss: 0.9889 | Train acc: 50.96% | Val loss: 0.9247 | Val acc: 55.18% | LR: 0.000022
Epoch: 113 | MCC: 0.030398 | Train loss: 0.9906 | Train acc: 50.95% | Val loss: 0.9113 | Val acc: 55.33% | LR: 0.000021
Epoch: 114 | MCC: 0.029149 | Train loss: 0.9919 | Train acc: 50.81% | Val loss: 0.9116 | Val acc: 55.30% | LR: 0.000020
Epoch: 115 | MCC: 0.028937 | Train loss: 0.9909 | Train acc: 50.84% | Val loss: 0.9282 | Val acc: 55.25% | LR: 0.000019
Epoch: 116 | MCC: 0.029465 | Train loss: 0.9911 | Train acc: 50.82% | Val loss: 0.9166 | Val acc: 55.28% | LR: 0.000018
Epoch: 117 | MCC: 0.029465 | Train loss: 1.0073 | Train acc: 50.93% | Val loss: 0.9125 | Val acc: 55.28% | LR: 0.000017
Epoch: 118 | MCC: 0.029465 | Train loss: 0.9908 | Train acc: 50.85% | Val loss: 0.9134 | Val acc: 55.28% | LR: 0.000016
Epoch: 119 | MCC: 0.030157 | Train loss: 1.0008 | Train acc: 50.85% | Val loss: 1.0627 | Val acc: 55.33% | LR: 0.000015
Epoch: 120 | MCC: 0.030157 | Train loss: 0.9892 | Train acc: 50.85% | Val loss: 0.9488 | Val acc: 55.33% | LR: 0.000014
Epoch: 121 | MCC: 0.030157 | Train loss: 0.9916 | Train acc: 50.95% | Val loss: 0.9926 | Val acc: 55.33% | LR: 0.000013
Epoch: 122 | MCC: 0.030036 | Train loss: 0.9906 | Train acc: 50.80% | Val loss: 0.9163 | Val acc: 55.33% | LR: 0.000012
Epoch: 123 | MCC: 0.030036 | Train loss: 0.9954 | Train acc: 50.86% | Val loss: 0.9130 | Val acc: 55.33% | LR: 0.000012
Epoch: 124 | MCC: 0.028526 | Train loss: 0.9915 | Train acc: 50.82% | Val loss: 0.9531 | Val acc: 55.25% | LR: 0.000011
Epoch: 125 | MCC: 0.029169 | Train loss: 0.9920 | Train acc: 50.78% | Val loss: 0.9680 | Val acc: 55.28% | LR: 0.000010
Epoch: 126 | MCC: 0.029576 | Train loss: 0.9904 | Train acc: 50.85% | Val loss: 0.9071 | Val acc: 55.30% | LR: 0.000009
Epoch: 127 | MCC: 0.029294 | Train loss: 0.9889 | Train acc: 50.87% | Val loss: 0.9134 | Val acc: 55.28% | LR: 0.000009
Epoch: 128 | MCC: 0.029010 | Train loss: 0.9919 | Train acc: 50.91% | Val loss: 0.9616 | Val acc: 55.25% | LR: 0.000008
Epoch: 129 | MCC: 0.031332 | Train loss: 0.9908 | Train acc: 50.89% | Val loss: 0.9147 | Val acc: 55.33% | LR: 0.000007
Epoch: 130 | MCC: 0.028404 | Train loss: 0.9923 | Train acc: 50.75% | Val loss: 0.9399 | Val acc: 55.25% | LR: 0.000007
Epoch: 131 | MCC: 0.028526 | Train loss: 0.9907 | Train acc: 50.86% | Val loss: 0.9471 | Val acc: 55.25% | LR: 0.000006
Epoch: 132 | MCC: 0.028120 | Train loss: 0.9908 | Train acc: 50.92% | Val loss: 1.6956 | Val acc: 55.23% | LR: 0.000006
Epoch: 133 | MCC: 0.031415 | Train loss: 0.9957 | Train acc: 50.99% | Val loss: 0.9227 | Val acc: 55.35% | LR: 0.000005
Epoch: 134 | MCC: 0.030433 | Train loss: 0.9915 | Train acc: 50.84% | Val loss: 5.7629 | Val acc: 55.30% | LR: 0.000005
Epoch: 135 | MCC: 0.030433 | Train loss: 0.9923 | Train acc: 50.85% | Val loss: 0.9428 | Val acc: 55.30% | LR: 0.000004

[I 2025-10-05 08:56:25,137] Trial 9 finished with value: 0.03043293207883835 and parameters: {'lr': 0.0001470388983108696, 'hidden_size': 19, 'dropout': 0.10058350303968477, 'weight_decay': 0.016275173308217754}. Best is trial 4 with value: 0.04243219271302223.

Epoch: 000 | MCC: 0.033399 | Train loss: 0.9919 | Train acc: 51.02% | Val loss: 1.0121 | Val acc: 47.24% | LR: 0.008937
Epoch: 001 | MCC: -0.017054 | Train loss: 0.9958 | Train acc: 50.36% | Val loss: 1.0037 | Val acc: 54.21% | LR: 0.008934
Epoch: 002 | MCC: -0.011197 | Train loss: 0.9985 | Train acc: 50.65% | Val loss: 1.0432 | Val acc: 45.17% | LR: 0.008929
Epoch: 003 | MCC: 0.000380 | Train loss: 1.0073 | Train acc: 50.16% | Val loss: 1.0344 | Val acc: 45.18% | LR: 0.008922
Epoch: 004 | MCC: -0.004581 | Train loss: 0.9993 | Train acc: 50.31% | Val loss: 1.0303 | Val acc: 45.02% | LR: 0.008913
Epoch: 005 | MCC: 0.012446 | Train loss: 1.0040 | Train acc: 50.27% | Val loss: 1.0065 | Val acc: 49.41% | LR: 0.008903
Epoch: 006 | MCC: -0.002165 | Train loss: 1.0185 | Train acc: 50.18% | Val loss: 1.0351 | Val acc: 45.30% | LR: 0.008890
Epoch: 007 | MCC: -0.012106 | Train loss: 1.0943 | Train acc: 50.28% | Val loss: 1.0105 | Val acc: 53.96% | LR: 0.008875
Epoch: 008 | MCC: 0.025656 | Train loss: 1.0076 | Train acc: 50.50% | Val loss: 0.9527 | Val acc: 54.98% | LR: 0.008859
Epoch: 009 | MCC: 0.034490 | Train loss: 1.0127 | Train acc: 50.55% | Val loss: 0.9390 | Val acc: 55.41% | LR: 0.008840
Epoch: 010 | MCC: 0.038548 | Train loss: 0.9933 | Train acc: 51.09% | Val loss: 0.9550 | Val acc: 54.92% | LR: 0.008820
Epoch: 011 | MCC: 0.000000 | Train loss: 0.9928 | Train acc: 50.93% | Val loss: 1.0397 | Val acc: 45.27% | LR: 0.008798
Epoch: 012 | MCC: 0.040477 | Train loss: 0.9929 | Train acc: 51.05% | Val loss: 0.9320 | Val acc: 54.55% | LR: 0.008773
Epoch: 013 | MCC: 0.000000 | Train loss: 0.9904 | Train acc: 50.91% | Val loss: 1.0627 | Val acc: 45.27% | LR: 0.008747
Epoch: 014 | MCC: 0.050210 | Train loss: 0.9900 | Train acc: 50.66% | Val loss: 0.9556 | Val acc: 54.97% | LR: 0.008719
Epoch: 015 | MCC: 0.044644 | Train loss: 0.9917 | Train acc: 50.81% | Val loss: 0.9858 | Val acc: 54.19% | LR: 0.008689
Epoch: 016 | MCC: 0.042064 | Train loss: 0.9842 | Train acc: 51.15% | Val loss: 0.9285 | Val acc: 54.00% | LR: 0.008658
Epoch: 017 | MCC: 0.042942 | Train loss: 0.9833 | Train acc: 51.07% | Val loss: 0.9242 | Val acc: 53.97% | LR: 0.008624
Epoch: 018 | MCC: 0.038962 | Train loss: 0.9856 | Train acc: 50.61% | Val loss: 0.9371 | Val acc: 53.55% | LR: 0.008589
Epoch: 019 | MCC: 0.044336 | Train loss: 0.9811 | Train acc: 51.11% | Val loss: 0.9229 | Val acc: 53.90% | LR: 0.008552
Epoch: 020 | MCC: 0.045045 | Train loss: 0.9859 | Train acc: 51.47% | Val loss: 0.9215 | Val acc: 54.09% | LR: 0.008513
Epoch: 021 | MCC: 0.036936 | Train loss: 0.9954 | Train acc: 50.17% | Val loss: 1.0177 | Val acc: 47.87% | LR: 0.008472
Epoch: 022 | MCC: -0.046598 | Train loss: 1.0101 | Train acc: 49.68% | Val loss: 1.0594 | Val acc: 46.24% | LR: 0.008429
Epoch: 023 | MCC: 0.026633 | Train loss: 1.0083 | Train acc: 49.82% | Val loss: 1.0218 | Val acc: 45.59% | LR: 0.008385
Epoch: 024 | MCC: 0.032695 | Train loss: 1.0045 | Train acc: 50.03% | Val loss: 1.0137 | Val acc: 47.99% | LR: 0.008339
Epoch: 025 | MCC: -0.057127 | Train loss: 1.0044 | Train acc: 49.88% | Val loss: 1.0729 | Val acc: 49.25% | LR: 0.008292
Epoch: 026 | MCC: 0.000000 | Train loss: 1.0037 | Train acc: 50.12% | Val loss: 1.0761 | Val acc: 45.27% | LR: 0.008242
Epoch: 027 | MCC: 0.021903 | Train loss: 0.9894 | Train acc: 50.37% | Val loss: 1.0606 | Val acc: 45.34% | LR: 0.008191
Epoch: 028 | MCC: 0.000000 | Train loss: 0.9855 | Train acc: 50.73% | Val loss: 1.0644 | Val acc: 45.27% | LR: 0.008139
Epoch: 029 | MCC: 0.000000 | Train loss: 0.9839 | Train acc: 51.35% | Val loss: 1.0608 | Val acc: 45.27% | LR: 0.008085
Epoch: 030 | MCC: 0.029329 | Train loss: 0.9833 | Train acc: 51.27% | Val loss: 0.9894 | Val acc: 53.55% | LR: 0.008029
Epoch: 031 | MCC: 0.041749 | Train loss: 0.9874 | Train acc: 50.98% | Val loss: 0.9971 | Val acc: 50.36% | LR: 0.007971
Epoch: 032 | MCC: 0.032330 | Train loss: 0.9822 | Train acc: 51.28% | Val loss: 0.9990 | Val acc: 48.66% | LR: 0.007912
Epoch: 033 | MCC: 0.019275 | Train loss: 0.9842 | Train acc: 51.58% | Val loss: 0.9655 | Val acc: 55.71% | LR: 0.007852
Epoch: 034 | MCC: 0.041461 | Train loss: 0.9875 | Train acc: 51.36% | Val loss: 0.9838 | Val acc: 55.90% | LR: 0.007790
Epoch: 035 | MCC: 0.045684 | Train loss: 0.9834 | Train acc: 51.57% | Val loss: 0.9406 | Val acc: 56.22% | LR: 0.007727
Epoch: 036 | MCC: 0.043953 | Train loss: 0.9830 | Train acc: 51.70% | Val loss: 0.9378 | Val acc: 56.05% | LR: 0.007662
Epoch: 037 | MCC: 0.030419 | Train loss: 0.9833 | Train acc: 51.69% | Val loss: 0.9281 | Val acc: 54.33% | LR: 0.007596
Epoch: 038 | MCC: 0.033287 | Train loss: 0.9786 | Train acc: 51.78% | Val loss: 0.9277 | Val acc: 54.73% | LR: 0.007528
Epoch: 039 | MCC: 0.031530 | Train loss: 0.9823 | Train acc: 51.38% | Val loss: 0.9114 | Val acc: 54.86% | LR: 0.007459
Epoch: 040 | MCC: 0.035813 | Train loss: 0.9874 | Train acc: 51.28% | Val loss: 0.9429 | Val acc: 56.11% | LR: 0.007389
Epoch: 041 | MCC: 0.038499 | Train loss: 0.9917 | Train acc: 51.16% | Val loss: 0.9055 | Val acc: 57.24% | LR: 0.007318
Epoch: 042 | MCC: 0.045990 | Train loss: 0.9808 | Train acc: 51.67% | Val loss: 0.8751 | Val acc: 56.72% | LR: 0.007245
Epoch: 043 | MCC: 0.046768 | Train loss: 0.9755 | Train acc: 51.84% | Val loss: 0.8655 | Val acc: 57.92% | LR: 0.007171
Epoch: 044 | MCC: -0.001929 | Train loss: 0.9780 | Train acc: 51.64% | Val loss: 0.9290 | Val acc: 55.11% | LR: 0.007096
Epoch: 045 | MCC: -0.002323 | Train loss: 0.9823 | Train acc: 51.21% | Val loss: 0.9668 | Val acc: 55.18% | LR: 0.007020
Epoch: 046 | MCC: 0.021151 | Train loss: 0.9862 | Train acc: 51.18% | Val loss: 0.9288 | Val acc: 55.56% | LR: 0.006942
Epoch: 047 | MCC: -0.003435 | Train loss: 0.9853 | Train acc: 50.81% | Val loss: 0.9168 | Val acc: 55.18% | LR: 0.006864
Epoch: 048 | MCC: -0.010998 | Train loss: 0.9845 | Train acc: 50.76% | Val loss: 0.9057 | Val acc: 54.84% | LR: 0.006784
Epoch: 049 | MCC: 0.003775 | Train loss: 0.9845 | Train acc: 51.45% | Val loss: 0.9041 | Val acc: 55.82% | LR: 0.006704
Epoch: 050 | MCC: -0.022233 | Train loss: 0.9860 | Train acc: 51.14% | Val loss: 0.9694 | Val acc: 55.91% | LR: 0.006622
Epoch: 051 | MCC: 0.003258 | Train loss: 0.9914 | Train acc: 50.48% | Val loss: 0.9389 | Val acc: 55.74% | LR: 0.006540
Epoch: 052 | MCC: 0.047982 | Train loss: 0.9843 | Train acc: 51.02% | Val loss: 0.8950 | Val acc: 56.18% | LR: 0.006456
Epoch: 053 | MCC: 0.038873 | Train loss: 0.9968 | Train acc: 49.64% | Val loss: 0.9256 | Val acc: 55.16% | LR: 0.006372
Epoch: 054 | MCC: 0.042739 | Train loss: 1.0023 | Train acc: 50.67% | Val loss: 1.0191 | Val acc: 50.55% | LR: 0.006287
Epoch: 055 | MCC: -0.052044 | Train loss: 1.0178 | Train acc: 50.11% | Val loss: 1.0260 | Val acc: 44.96% | LR: 0.006201
Epoch: 056 | MCC: 0.000000 | Train loss: 0.9904 | Train acc: 50.38% | Val loss: 1.0745 | Val acc: 45.27% | LR: 0.006114
Epoch: 057 | MCC: 0.000000 | Train loss: 0.9968 | Train acc: 50.22% | Val loss: 1.0467 | Val acc: 45.27% | LR: 0.006027
Epoch: 058 | MCC: 0.000000 | Train loss: 0.9961 | Train acc: 50.53% | Val loss: 1.0525 | Val acc: 45.27% | LR: 0.005939
Epoch: 059 | MCC: 0.020715 | Train loss: 0.9990 | Train acc: 49.67% | Val loss: 0.9741 | Val acc: 53.87% | LR: 0.005850
Epoch: 060 | MCC: 0.023718 | Train loss: 0.9894 | Train acc: 50.93% | Val loss: 1.0250 | Val acc: 45.41% | LR: 0.005761
Epoch: 061 | MCC: 0.059531 | Train loss: 0.9858 | Train acc: 51.40% | Val loss: 0.9805 | Val acc: 52.75% | LR: 0.005671
Epoch: 062 | MCC: 0.032908 | Train loss: 1.0029 | Train acc: 51.05% | Val loss: 0.9207 | Val acc: 54.12% | LR: 0.005581
Epoch: 063 | MCC: 0.058732 | Train loss: 0.9865 | Train acc: 51.49% | Val loss: 0.9698 | Val acc: 54.90% | LR: 0.005490
Epoch: 064 | MCC: 0.045185 | Train loss: 0.9888 | Train acc: 51.26% | Val loss: 0.9908 | Val acc: 49.57% | LR: 0.005399
Epoch: 065 | MCC: 0.059271 | Train loss: 0.9863 | Train acc: 51.06% | Val loss: 0.9444 | Val acc: 56.46% | LR: 0.005307
Epoch: 066 | MCC: 0.050799 | Train loss: 0.9844 | Train acc: 50.98% | Val loss: 0.9273 | Val acc: 56.75% | LR: 0.005215
Epoch: 067 | MCC: 0.035554 | Train loss: 0.9844 | Train acc: 51.01% | Val loss: 0.9446 | Val acc: 55.26% | LR: 0.005122
Epoch: 068 | MCC: 0.026045 | Train loss: 1.0126 | Train acc: 50.62% | Val loss: 0.9559 | Val acc: 54.25% | LR: 0.005030
Epoch: 069 | MCC: 0.036130 | Train loss: 0.9824 | Train acc: 51.21% | Val loss: 0.9757 | Val acc: 54.60% | LR: 0.004937
Epoch: 070 | MCC: 0.038065 | Train loss: 0.9785 | Train acc: 51.74% | Val loss: 0.9541 | Val acc: 54.86% | LR: 0.004843
Epoch: 071 | MCC: 0.046927 | Train loss: 0.9873 | Train acc: 51.43% | Val loss: 0.9273 | Val acc: 54.79% | LR: 0.004750
Epoch: 072 | MCC: 0.033195 | Train loss: 0.9850 | Train acc: 50.85% | Val loss: 0.9360 | Val acc: 55.60% | LR: 0.004657
Epoch: 073 | MCC: 0.017502 | Train loss: 0.9849 | Train acc: 51.54% | Val loss: 0.9561 | Val acc: 56.08% | LR: 0.004563
Epoch: 074 | MCC: -0.011167 | Train loss: 0.9858 | Train acc: 51.38% | Val loss: 0.9081 | Val acc: 56.21% | LR: 0.004469
Epoch: 075 | MCC: 0.004575 | Train loss: 1.0026 | Train acc: 51.37% | Val loss: 0.9197 | Val acc: 55.35% | LR: 0.004376
Epoch: 076 | MCC: 0.026937 | Train loss: 0.9876 | Train acc: 51.35% | Val loss: 0.9218 | Val acc: 54.61% | LR: 0.004282
Epoch: 077 | MCC: 0.013889 | Train loss: 1.0002 | Train acc: 49.63% | Val loss: 0.9260 | Val acc: 54.43% | LR: 0.004189
Epoch: 078 | MCC: 0.013985 | Train loss: 0.9948 | Train acc: 50.39% | Val loss: 0.9492 | Val acc: 54.22% | LR: 0.004096
Epoch: 079 | MCC: 0.011494 | Train loss: 0.9901 | Train acc: 51.06% | Val loss: 0.9930 | Val acc: 54.10% | LR: 0.004002
Epoch: 080 | MCC: 0.009574 | Train loss: 0.9935 | Train acc: 50.80% | Val loss: 0.9408 | Val acc: 54.03% | LR: 0.003909
Epoch: 081 | MCC: 0.009535 | Train loss: 0.9964 | Train acc: 50.11% | Val loss: 0.9830 | Val acc: 54.04% | LR: 0.003817
Epoch: 082 | MCC: 0.011786 | Train loss: 0.9894 | Train acc: 51.14% | Val loss: 0.9263 | Val acc: 54.30% | LR: 0.003724
Epoch: 083 | MCC: 0.018096 | Train loss: 0.9834 | Train acc: 51.13% | Val loss: 0.9401 | Val acc: 54.68% | LR: 0.003632
Epoch: 084 | MCC: 0.000985 | Train loss: 0.9858 | Train acc: 51.01% | Val loss: 0.9125 | Val acc: 54.64% | LR: 0.003540
Epoch: 085 | MCC: 0.000650 | Train loss: 0.9827 | Train acc: 51.18% | Val loss: 0.9126 | Val acc: 54.91% | LR: 0.003449
Epoch: 086 | MCC: 0.016985 | Train loss: 0.9834 | Train acc: 51.10% | Val loss: 0.9154 | Val acc: 55.01% | LR: 0.003358
Epoch: 087 | MCC: 0.021238 | Train loss: 0.9841 | Train acc: 50.97% | Val loss: 0.8953 | Val acc: 55.33% | LR: 0.003268
Epoch: 088 | MCC: 0.005760 | Train loss: 0.9860 | Train acc: 51.01% | Val loss: 0.8972 | Val acc: 55.70% | LR: 0.003178
Epoch: 089 | MCC: -0.003769 | Train loss: 0.9839 | Train acc: 51.09% | Val loss: 0.9189 | Val acc: 55.12% | LR: 0.003089
Epoch: 090 | MCC: -0.013140 | Train loss: 0.9830 | Train acc: 51.11% | Val loss: 0.9121 | Val acc: 54.60% | LR: 0.003000
Epoch: 091 | MCC: -0.010019 | Train loss: 0.9836 | Train acc: 51.09% | Val loss: 0.9191 | Val acc: 54.70% | LR: 0.002912
Epoch: 092 | MCC: -0.003345 | Train loss: 0.9810 | Train acc: 51.09% | Val loss: 0.9143 | Val acc: 55.04% | LR: 0.002825
Epoch: 093 | MCC: -0.006506 | Train loss: 0.9791 | Train acc: 51.28% | Val loss: 0.9245 | Val acc: 54.70% | LR: 0.002738
Epoch: 094 | MCC: -0.006610 | Train loss: 0.9817 | Train acc: 51.06% | Val loss: 0.9405 | Val acc: 54.80% | LR: 0.002652
Epoch: 095 | MCC: -0.009141 | Train loss: 0.9782 | Train acc: 51.18% | Val loss: 0.9164 | Val acc: 54.78% | LR: 0.002567
Epoch: 096 | MCC: -0.004064 | Train loss: 0.9802 | Train acc: 51.08% | Val loss: 0.9090 | Val acc: 55.02% | LR: 0.002483
Epoch: 097 | MCC: -0.004163 | Train loss: 0.9794 | Train acc: 51.11% | Val loss: 0.9167 | Val acc: 54.97% | LR: 0.002399
Epoch: 098 | MCC: -0.007938 | Train loss: 0.9864 | Train acc: 51.08% | Val loss: 0.9085 | Val acc: 54.75% | LR: 0.002317
Epoch: 099 | MCC: -0.010513 | Train loss: 0.9800 | Train acc: 51.17% | Val loss: 0.9262 | Val acc: 54.68% | LR: 0.002235
Epoch: 100 | MCC: -0.007212 | Train loss: 0.9781 | Train acc: 51.25% | Val loss: 0.9120 | Val acc: 54.92% | LR: 0.002155
Epoch: 101 | MCC: 0.002376 | Train loss: 0.9802 | Train acc: 51.11% | Val loss: 0.9070 | Val acc: 55.76% | LR: 0.002075
Epoch: 102 | MCC: 0.000813 | Train loss: 0.9820 | Train acc: 51.04% | Val loss: 0.8908 | Val acc: 55.80% | LR: 0.001997
Epoch: 103 | MCC: 0.001596 | Train loss: 0.9821 | Train acc: 51.02% | Val loss: 0.9104 | Val acc: 55.78% | LR: 0.001919
Epoch: 104 | MCC: -0.006176 | Train loss: 0.9792 | Train acc: 51.21% | Val loss: 0.9435 | Val acc: 54.59% | LR: 0.001843
Epoch: 105 | MCC: -0.004596 | Train loss: 0.9946 | Train acc: 51.01% | Val loss: 0.9212 | Val acc: 54.46% | LR: 0.001768
Epoch: 106 | MCC: -0.008993 | Train loss: 0.9784 | Train acc: 51.23% | Val loss: 0.9155 | Val acc: 54.76% | LR: 0.001694
Epoch: 107 | MCC: -0.003890 | Train loss: 0.9788 | Train acc: 51.19% | Val loss: 0.9004 | Val acc: 55.14% | LR: 0.001621
Epoch: 108 | MCC: -0.007047 | Train loss: 0.9800 | Train acc: 51.14% | Val loss: 0.9115 | Val acc: 54.64% | LR: 0.001550
Epoch: 109 | MCC: -0.003669 | Train loss: 0.9794 | Train acc: 51.36% | Val loss: 0.8977 | Val acc: 55.39% | LR: 0.001479
Epoch: 110 | MCC: -0.004362 | Train loss: 0.9792 | Train acc: 51.15% | Val loss: 0.9011 | Val acc: 55.07% | LR: 0.001411
Epoch: 111 | MCC: -0.008903 | Train loss: 0.9801 | Train acc: 51.16% | Val loss: 0.9124 | Val acc: 54.63% | LR: 0.001343
Epoch: 112 | MCC: -0.002410 | Train loss: 0.9793 | Train acc: 51.10% | Val loss: 0.9020 | Val acc: 55.26% | LR: 0.001277
Epoch: 113 | MCC: -0.004998 | Train loss: 0.9803 | Train acc: 51.06% | Val loss: 0.9008 | Val acc: 55.09% | LR: 0.001212
Epoch: 114 | MCC: -0.003724 | Train loss: 0.9788 | Train acc: 51.16% | Val loss: 0.9091 | Val acc: 54.95% | LR: 0.001149
Epoch: 115 | MCC: -0.006947 | Train loss: 0.9779 | Train acc: 51.21% | Val loss: 0.9127 | Val acc: 54.73% | LR: 0.001087
Epoch: 116 | MCC: -0.004824 | Train loss: 0.9759 | Train acc: 51.30% | Val loss: 0.9100 | Val acc: 54.76% | LR: 0.001026
Epoch: 117 | MCC: -0.012346 | Train loss: 0.9779 | Train acc: 51.21% | Val loss: 0.9097 | Val acc: 54.73% | LR: 0.000968

[I 2025-10-05 08:58:14,191] Trial 10 finished with value: -0.0103712547570467 and parameters: {'lr': 0.008937922713169651, 'hidden_size': 86, 'dropout': 0.4879721545257818, 'weight_decay': 0.09266411576854267}. Best is trial 4 with value: 0.04243219271302223.

Epoch: 000 | MCC: -0.001594 | Train loss: 1.0325 | Train acc: 50.16% | Val loss: 1.0058 | Val acc: 47.09% | LR: 0.005357
Epoch: 001 | MCC: 0.016165 | Train loss: 1.0048 | Train acc: 50.21% | Val loss: 0.9317 | Val acc: 54.05% | LR: 0.005355
Epoch: 002 | MCC: 0.000000 | Train loss: 1.0016 | Train acc: 50.44% | Val loss: 1.0464 | Val acc: 45.27% | LR: 0.005352
Epoch: 003 | MCC: 0.023574 | Train loss: 0.9899 | Train acc: 50.68% | Val loss: 0.9617 | Val acc: 53.98% | LR: 0.005348
Epoch: 004 | MCC: 0.025692 | Train loss: 0.9949 | Train acc: 50.25% | Val loss: 0.9690 | Val acc: 54.12% | LR: 0.005343
Epoch: 005 | MCC: -0.013838 | Train loss: 0.9952 | Train acc: 50.29% | Val loss: 1.0193 | Val acc: 45.22% | LR: 0.005336
Epoch: 006 | MCC: 0.000000 | Train loss: 0.9881 | Train acc: 50.66% | Val loss: 1.0186 | Val acc: 45.27% | LR: 0.005329
Epoch: 007 | MCC: 0.013074 | Train loss: 0.9880 | Train acc: 50.54% | Val loss: 1.0084 | Val acc: 45.51% | LR: 0.005320
Epoch: 008 | MCC: 0.023219 | Train loss: 0.9904 | Train acc: 50.42% | Val loss: 0.9815 | Val acc: 54.61% | LR: 0.005310
Epoch: 009 | MCC: 0.026731 | Train loss: 0.9875 | Train acc: 50.80% | Val loss: 0.9912 | Val acc: 54.88% | LR: 0.005299
Epoch: 010 | MCC: 0.015539 | Train loss: 0.9888 | Train acc: 50.77% | Val loss: 0.9902 | Val acc: 53.97% | LR: 0.005287
Epoch: 011 | MCC: 0.025782 | Train loss: 0.9963 | Train acc: 50.62% | Val loss: 0.9618 | Val acc: 54.77% | LR: 0.005273
Epoch: 012 | MCC: 0.029234 | Train loss: 0.9909 | Train acc: 50.78% | Val loss: 1.0102 | Val acc: 46.56% | LR: 0.005259
Epoch: 013 | MCC: 0.058800 | Train loss: 0.9863 | Train acc: 50.78% | Val loss: 0.9983 | Val acc: 51.40% | LR: 0.005243
Epoch: 014 | MCC: 0.033181 | Train loss: 0.9840 | Train acc: 51.12% | Val loss: 0.9785 | Val acc: 54.14% | LR: 0.005226
Epoch: 015 | MCC: 0.024251 | Train loss: 0.9967 | Train acc: 50.03% | Val loss: 0.9755 | Val acc: 54.31% | LR: 0.005209
Epoch: 016 | MCC: 0.052380 | Train loss: 0.9940 | Train acc: 50.72% | Val loss: 0.9981 | Val acc: 50.11% | LR: 0.005190
Epoch: 017 | MCC: 0.030768 | Train loss: 0.9930 | Train acc: 50.87% | Val loss: 0.9757 | Val acc: 55.05% | LR: 0.005170
Epoch: 018 | MCC: 0.045792 | Train loss: 0.9939 | Train acc: 51.05% | Val loss: 0.9518 | Val acc: 54.40% | LR: 0.005148
Epoch: 019 | MCC: 0.036730 | Train loss: 0.9885 | Train acc: 50.85% | Val loss: 0.9395 | Val acc: 53.96% | LR: 0.005126
Epoch: 020 | MCC: 0.022874 | Train loss: 0.9876 | Train acc: 50.90% | Val loss: 0.9530 | Val acc: 54.10% | LR: 0.005103
Epoch: 021 | MCC: 0.032928 | Train loss: 0.9848 | Train acc: 50.81% | Val loss: 0.9336 | Val acc: 54.54% | LR: 0.005078
Epoch: 022 | MCC: 0.061248 | Train loss: 0.9861 | Train acc: 50.83% | Val loss: 0.9541 | Val acc: 54.52% | LR: 0.005053
Epoch: 023 | MCC: 0.055101 | Train loss: 0.9842 | Train acc: 50.91% | Val loss: 0.9368 | Val acc: 54.64% | LR: 0.005026
Epoch: 024 | MCC: 0.040650 | Train loss: 0.9932 | Train acc: 50.67% | Val loss: 0.9298 | Val acc: 54.78% | LR: 0.004999
Epoch: 025 | MCC: 0.030048 | Train loss: 0.9981 | Train acc: 50.54% | Val loss: 0.9703 | Val acc: 54.87% | LR: 0.004970
Epoch: 026 | MCC: 0.036661 | Train loss: 1.0071 | Train acc: 50.49% | Val loss: 0.9431 | Val acc: 55.42% | LR: 0.004941
Epoch: 027 | MCC: 0.047743 | Train loss: 0.9901 | Train acc: 50.77% | Val loss: 0.9525 | Val acc: 53.55% | LR: 0.004910
Epoch: 028 | MCC: -0.007030 | Train loss: 0.9958 | Train acc: 50.87% | Val loss: 1.0070 | Val acc: 46.65% | LR: 0.004879
Epoch: 029 | MCC: -0.006771 | Train loss: 1.0111 | Train acc: 49.94% | Val loss: 0.9817 | Val acc: 51.23% | LR: 0.004846
Epoch: 030 | MCC: 0.048185 | Train loss: 0.9964 | Train acc: 50.40% | Val loss: 0.9218 | Val acc: 54.58% | LR: 0.004813
Epoch: 031 | MCC: 0.038423 | Train loss: 0.9876 | Train acc: 50.87% | Val loss: 0.9475 | Val acc: 54.53% | LR: 0.004778
Epoch: 032 | MCC: 0.052414 | Train loss: 0.9895 | Train acc: 50.93% | Val loss: 0.9729 | Val acc: 54.90% | LR: 0.004743
Epoch: 033 | MCC: 0.000000 | Train loss: 0.9896 | Train acc: 50.87% | Val loss: 1.0730 | Val acc: 45.27% | LR: 0.004707
Epoch: 034 | MCC: 0.016662 | Train loss: 1.0240 | Train acc: 50.51% | Val loss: 0.9589 | Val acc: 54.01% | LR: 0.004670
Epoch: 035 | MCC: 0.046039 | Train loss: 0.9925 | Train acc: 50.58% | Val loss: 0.9386 | Val acc: 54.67% | LR: 0.004632
Epoch: 036 | MCC: 0.012141 | Train loss: 0.9870 | Train acc: 50.86% | Val loss: 0.9137 | Val acc: 54.88% | LR: 0.004593
Epoch: 037 | MCC: 0.033050 | Train loss: 0.9846 | Train acc: 51.26% | Val loss: 0.9163 | Val acc: 54.26% | LR: 0.004553
Epoch: 038 | MCC: 0.047053 | Train loss: 0.9821 | Train acc: 51.39% | Val loss: 0.9893 | Val acc: 54.58% | LR: 0.004513
Epoch: 039 | MCC: 0.034364 | Train loss: 0.9900 | Train acc: 51.11% | Val loss: 0.9428 | Val acc: 54.05% | LR: 0.004471
Epoch: 040 | MCC: 0.043665 | Train loss: 0.9917 | Train acc: 51.10% | Val loss: 0.9769 | Val acc: 54.34% | LR: 0.004429
Epoch: 041 | MCC: 0.000435 | Train loss: 0.9976 | Train acc: 50.62% | Val loss: 0.9184 | Val acc: 54.76% | LR: 0.004387
Epoch: 042 | MCC: 0.042988 | Train loss: 0.9920 | Train acc: 50.87% | Val loss: 0.9472 | Val acc: 54.02% | LR: 0.004343
Epoch: 043 | MCC: 0.023403 | Train loss: 0.9830 | Train acc: 50.95% | Val loss: 0.9276 | Val acc: 54.28% | LR: 0.004299
Epoch: 044 | MCC: 0.035824 | Train loss: 0.9831 | Train acc: 51.64% | Val loss: 0.9322 | Val acc: 54.05% | LR: 0.004254
Epoch: 045 | MCC: 0.039873 | Train loss: 0.9849 | Train acc: 50.94% | Val loss: 0.9654 | Val acc: 53.90% | LR: 0.004208
Epoch: 046 | MCC: 0.040585 | Train loss: 0.9798 | Train acc: 51.24% | Val loss: 0.9408 | Val acc: 54.12% | LR: 0.004161
Epoch: 047 | MCC: 0.031975 | Train loss: 0.9811 | Train acc: 51.26% | Val loss: 0.9311 | Val acc: 53.49% | LR: 0.004114
Epoch: 048 | MCC: 0.041716 | Train loss: 0.9777 | Train acc: 51.25% | Val loss: 0.9397 | Val acc: 54.19% | LR: 0.004067
Epoch: 049 | MCC: 0.037476 | Train loss: 0.9796 | Train acc: 51.34% | Val loss: 0.9397 | Val acc: 53.96% | LR: 0.004018
Epoch: 050 | MCC: 0.030891 | Train loss: 0.9805 | Train acc: 51.29% | Val loss: 0.9294 | Val acc: 53.65% | LR: 0.003970
Epoch: 051 | MCC: 0.027984 | Train loss: 0.9812 | Train acc: 51.33% | Val loss: 0.9486 | Val acc: 53.58% | LR: 0.003920
Epoch: 052 | MCC: 0.040357 | Train loss: 0.9844 | Train acc: 51.38% | Val loss: 0.9632 | Val acc: 54.19% | LR: 0.003870
Epoch: 053 | MCC: 0.040630 | Train loss: 0.9740 | Train acc: 51.50% | Val loss: 0.9477 | Val acc: 54.03% | LR: 0.003820
Epoch: 054 | MCC: 0.039539 | Train loss: 0.9771 | Train acc: 51.37% | Val loss: 0.9429 | Val acc: 54.12% | LR: 0.003769
Epoch: 055 | MCC: 0.037072 | Train loss: 0.9704 | Train acc: 51.70% | Val loss: 0.9446 | Val acc: 54.10% | LR: 0.003717
Epoch: 056 | MCC: 0.024399 | Train loss: 0.9736 | Train acc: 52.14% | Val loss: 0.9402 | Val acc: 53.79% | LR: 0.003665
Epoch: 057 | MCC: 0.028646 | Train loss: 0.9787 | Train acc: 51.56% | Val loss: 0.9330 | Val acc: 53.57% | LR: 0.003613
Epoch: 058 | MCC: 0.013603 | Train loss: 0.9713 | Train acc: 52.16% | Val loss: 0.9456 | Val acc: 53.23% | LR: 0.003560
Epoch: 059 | MCC: 0.031693 | Train loss: 0.9669 | Train acc: 51.69% | Val loss: 0.9509 | Val acc: 53.45% | LR: 0.003507
Epoch: 060 | MCC: 0.020026 | Train loss: 0.9659 | Train acc: 51.91% | Val loss: 0.9509 | Val acc: 53.19% | LR: 0.003453
Epoch: 061 | MCC: 0.046626 | Train loss: 0.9683 | Train acc: 52.39% | Val loss: 0.9443 | Val acc: 54.30% | LR: 0.003400
Epoch: 062 | MCC: 0.028935 | Train loss: 0.9694 | Train acc: 52.08% | Val loss: 0.9396 | Val acc: 53.77% | LR: 0.003345
Epoch: 063 | MCC: -0.004840 | Train loss: 0.9686 | Train acc: 51.95% | Val loss: 0.9736 | Val acc: 51.95% | LR: 0.003291
Epoch: 064 | MCC: 0.024190 | Train loss: 0.9667 | Train acc: 52.39% | Val loss: 0.9629 | Val acc: 53.26% | LR: 0.003236
Epoch: 065 | MCC: 0.018358 | Train loss: 0.9657 | Train acc: 52.28% | Val loss: 0.9429 | Val acc: 53.36% | LR: 0.003181
Epoch: 066 | MCC: 0.000898 | Train loss: 0.9700 | Train acc: 51.54% | Val loss: 0.9595 | Val acc: 52.88% | LR: 0.003126
Epoch: 067 | MCC: 0.017077 | Train loss: 0.9700 | Train acc: 51.91% | Val loss: 0.9374 | Val acc: 54.45% | LR: 0.003071
Epoch: 068 | MCC: 0.011831 | Train loss: 0.9642 | Train acc: 51.99% | Val loss: 0.9451 | Val acc: 53.66% | LR: 0.003015
Epoch: 069 | MCC: 0.023348 | Train loss: 0.9622 | Train acc: 51.99% | Val loss: 0.9400 | Val acc: 54.27% | LR: 0.002959
Epoch: 070 | MCC: 0.003937 | Train loss: 0.9610 | Train acc: 52.34% | Val loss: 0.9679 | Val acc: 52.64% | LR: 0.002903
Epoch: 071 | MCC: 0.009084 | Train loss: 0.9588 | Train acc: 52.45% | Val loss: 0.9385 | Val acc: 54.56% | LR: 0.002847
Epoch: 072 | MCC: 0.013250 | Train loss: 0.9585 | Train acc: 52.73% | Val loss: 0.9368 | Val acc: 54.40% | LR: 0.002791
Epoch: 073 | MCC: -0.006451 | Train loss: 0.9563 | Train acc: 52.87% | Val loss: 0.9377 | Val acc: 54.20% | LR: 0.002735
Epoch: 074 | MCC: -0.012070 | Train loss: 0.9547 | Train acc: 52.90% | Val loss: 0.9465 | Val acc: 54.06% | LR: 0.002679
Epoch: 075 | MCC: 0.013717 | Train loss: 0.9557 | Train acc: 52.94% | Val loss: 0.9418 | Val acc: 54.13% | LR: 0.002623
Epoch: 076 | MCC: 0.000186 | Train loss: 0.9596 | Train acc: 52.24% | Val loss: 0.9407 | Val acc: 55.05% | LR: 0.002567
Epoch: 077 | MCC: 0.000713 | Train loss: 0.9539 | Train acc: 52.40% | Val loss: 0.9478 | Val acc: 54.64% | LR: 0.002511
Epoch: 078 | MCC: -0.022422 | Train loss: 0.9512 | Train acc: 53.21% | Val loss: 0.9559 | Val acc: 53.68% | LR: 0.002455
Epoch: 079 | MCC: 0.012024 | Train loss: 0.9539 | Train acc: 52.68% | Val loss: 0.9359 | Val acc: 55.42% | LR: 0.002399
Epoch: 080 | MCC: -0.011700 | Train loss: 0.9551 | Train acc: 53.29% | Val loss: 0.9618 | Val acc: 53.72% | LR: 0.002344
Epoch: 081 | MCC: -0.006506 | Train loss: 0.9516 | Train acc: 53.13% | Val loss: 0.9472 | Val acc: 54.06% | LR: 0.002288
Epoch: 082 | MCC: -0.006766 | Train loss: 0.9484 | Train acc: 53.22% | Val loss: 0.9795 | Val acc: 52.96% | LR: 0.002233
Epoch: 083 | MCC: -0.027262 | Train loss: 0.9477 | Train acc: 53.51% | Val loss: 0.9563 | Val acc: 53.85% | LR: 0.002177
Epoch: 084 | MCC: -0.005246 | Train loss: 0.9434 | Train acc: 53.66% | Val loss: 0.9584 | Val acc: 53.84% | LR: 0.002122
Epoch: 085 | MCC: -0.036318 | Train loss: 0.9482 | Train acc: 53.31% | Val loss: 0.9606 | Val acc: 53.56% | LR: 0.002068
Epoch: 086 | MCC: -0.043905 | Train loss: 0.9422 | Train acc: 53.64% | Val loss: 0.9879 | Val acc: 51.88% | LR: 0.002013
Epoch: 087 | MCC: -0.036921 | Train loss: 0.9394 | Train acc: 53.73% | Val loss: 0.9889 | Val acc: 51.89% | LR: 0.001959
Epoch: 088 | MCC: -0.010687 | Train loss: 0.9374 | Train acc: 53.74% | Val loss: 0.9604 | Val acc: 54.21% | LR: 0.001905
Epoch: 089 | MCC: -0.037890 | Train loss: 0.9389 | Train acc: 53.74% | Val loss: 0.9805 | Val acc: 52.69% | LR: 0.001852
Epoch: 090 | MCC: -0.019362 | Train loss: 0.9354 | Train acc: 54.06% | Val loss: 0.9664 | Val acc: 53.91% | LR: 0.001798
Epoch: 091 | MCC: -0.020505 | Train loss: 0.9312 | Train acc: 54.15% | Val loss: 1.0214 | Val acc: 50.07% | LR: 0.001746
Epoch: 092 | MCC: -0.026308 | Train loss: 0.9277 | Train acc: 54.30% | Val loss: 0.9892 | Val acc: 52.54% | LR: 0.001693
Epoch: 093 | MCC: -0.037038 | Train loss: 0.9288 | Train acc: 54.26% | Val loss: 0.9919 | Val acc: 52.73% | LR: 0.001641
Epoch: 094 | MCC: -0.029066 | Train loss: 0.9268 | Train acc: 54.30% | Val loss: 1.0096 | Val acc: 51.93% | LR: 0.001590
Epoch: 095 | MCC: -0.030799 | Train loss: 0.9264 | Train acc: 54.40% | Val loss: 0.9962 | Val acc: 52.57% | LR: 0.001539
Epoch: 096 | MCC: -0.028568 | Train loss: 0.9218 | Train acc: 54.63% | Val loss: 0.9965 | Val acc: 52.23% | LR: 0.001488
Epoch: 097 | MCC: -0.035599 | Train loss: 0.9218 | Train acc: 54.68% | Val loss: 0.9805 | Val acc: 52.84% | LR: 0.001438
Epoch: 098 | MCC: -0.025723 | Train loss: 0.9236 | Train acc: 54.48% | Val loss: 0.9935 | Val acc: 52.11% | LR: 0.001389
Epoch: 099 | MCC: -0.024332 | Train loss: 0.9203 | Train acc: 54.60% | Val loss: 0.9937 | Val acc: 52.58% | LR: 0.001340
Epoch: 100 | MCC: -0.035107 | Train loss: 0.9160 | Train acc: 54.94% | Val loss: 0.9958 | Val acc: 52.05% | LR: 0.001292
Epoch: 101 | MCC: -0.009208 | Train loss: 0.9145 | Train acc: 54.81% | Val loss: 1.0046 | Val acc: 52.43% | LR: 0.001244
Epoch: 102 | MCC: -0.018079 | Train loss: 0.9129 | Train acc: 55.07% | Val loss: 1.0235 | Val acc: 52.00% | LR: 0.001197
Epoch: 103 | MCC: -0.006456 | Train loss: 0.9126 | Train acc: 54.98% | Val loss: 0.9902 | Val acc: 53.11% | LR: 0.001151
Epoch: 104 | MCC: -0.007707 | Train loss: 0.9104 | Train acc: 55.20% | Val loss: 0.9943 | Val acc: 52.84% | LR: 0.001105
Epoch: 105 | MCC: -0.004099 | Train loss: 0.9082 | Train acc: 55.21% | Val loss: 1.0109 | Val acc: 51.92% | LR: 0.001060
Epoch: 106 | MCC: -0.011750 | Train loss: 0.9145 | Train acc: 55.11% | Val loss: 0.9896 | Val acc: 52.77% | LR: 0.001016
Epoch: 107 | MCC: -0.011565 | Train loss: 0.9082 | Train acc: 55.35% | Val loss: 1.0042 | Val acc: 51.94% | LR: 0.000972
Epoch: 108 | MCC: -0.020240 | Train loss: 0.9107 | Train acc: 55.39% | Val loss: 1.0122 | Val acc: 52.02% | LR: 0.000929
Epoch: 109 | MCC: -0.003707 | Train loss: 0.9074 | Train acc: 55.43% | Val loss: 0.9883 | Val acc: 53.13% | LR: 0.000887
Epoch: 110 | MCC: -0.002441 | Train loss: 0.9066 | Train acc: 55.38% | Val loss: 1.0169 | Val acc: 52.23% | LR: 0.000846

[I 2025-10-05 09:00:12,473] Trial 11 finished with value: -0.023183749057352543 and parameters: {'lr': 0.0053575847954195795, 'hidden_size': 128, 'dropout': 0.16168958095878436, 'weight_decay': 0.00016245280452785544}. Best is trial 4 with value: 0.04243219271302223.

Epoch: 000 | MCC: 0.025418 | Train loss: 0.9989 | Train acc: 50.38% | Val loss: 0.9824 | Val acc: 55.61% | LR: 0.003469
Epoch: 001 | MCC: 0.000165 | Train loss: 0.9953 | Train acc: 50.75% | Val loss: 0.9884 | Val acc: 54.14% | LR: 0.003468
Epoch: 002 | MCC: 0.002478 | Train loss: 0.9978 | Train acc: 50.50% | Val loss: 0.9411 | Val acc: 54.20% | LR: 0.003466
Epoch: 003 | MCC: 0.023935 | Train loss: 0.9897 | Train acc: 50.86% | Val loss: 0.9544 | Val acc: 53.52% | LR: 0.003463
Epoch: 004 | MCC: 0.021753 | Train loss: 0.9899 | Train acc: 50.82% | Val loss: 1.0258 | Val acc: 53.09% | LR: 0.003460
Epoch: 005 | MCC: 0.029308 | Train loss: 0.9874 | Train acc: 51.17% | Val loss: 0.9260 | Val acc: 53.83% | LR: 0.003456
Epoch: 006 | MCC: 0.029852 | Train loss: 0.9890 | Train acc: 50.75% | Val loss: 0.9738 | Val acc: 53.91% | LR: 0.003451
Epoch: 007 | MCC: 0.033406 | Train loss: 0.9864 | Train acc: 50.85% | Val loss: 0.9500 | Val acc: 53.89% | LR: 0.003445
Epoch: 008 | MCC: 0.037047 | Train loss: 0.9870 | Train acc: 50.94% | Val loss: 0.9470 | Val acc: 53.76% | LR: 0.003439
Epoch: 009 | MCC: 0.049956 | Train loss: 0.9940 | Train acc: 50.53% | Val loss: 0.9846 | Val acc: 55.40% | LR: 0.003431
Epoch: 010 | MCC: 0.041737 | Train loss: 0.9895 | Train acc: 50.88% | Val loss: 0.9367 | Val acc: 54.31% | LR: 0.003424
Epoch: 011 | MCC: 0.040784 | Train loss: 0.9890 | Train acc: 51.05% | Val loss: 0.9474 | Val acc: 54.33% | LR: 0.003415
Epoch: 012 | MCC: 0.040680 | Train loss: 0.9884 | Train acc: 50.97% | Val loss: 0.9203 | Val acc: 53.62% | LR: 0.003405
Epoch: 013 | MCC: 0.048141 | Train loss: 0.9928 | Train acc: 50.86% | Val loss: 0.9075 | Val acc: 55.03% | LR: 0.003395
Epoch: 014 | MCC: 0.040316 | Train loss: 0.9889 | Train acc: 51.22% | Val loss: 0.9583 | Val acc: 55.08% | LR: 0.003384
Epoch: 015 | MCC: 0.000000 | Train loss: 0.9877 | Train acc: 50.97% | Val loss: 1.0400 | Val acc: 45.27% | LR: 0.003373
Epoch: 016 | MCC: 0.041096 | Train loss: 0.9881 | Train acc: 50.83% | Val loss: 0.9352 | Val acc: 54.72% | LR: 0.003361
Epoch: 017 | MCC: 0.032561 | Train loss: 0.9863 | Train acc: 50.86% | Val loss: 1.0058 | Val acc: 47.08% | LR: 0.003348
Epoch: 018 | MCC: 0.033197 | Train loss: 0.9888 | Train acc: 50.45% | Val loss: 0.9591 | Val acc: 54.32% | LR: 0.003334
Epoch: 019 | MCC: 0.034730 | Train loss: 0.9846 | Train acc: 50.87% | Val loss: 0.9351 | Val acc: 54.18% | LR: 0.003319
Epoch: 020 | MCC: 0.025900 | Train loss: 0.9899 | Train acc: 50.75% | Val loss: 0.9815 | Val acc: 53.06% | LR: 0.003304
Epoch: 021 | MCC: 0.030544 | Train loss: 0.9870 | Train acc: 50.83% | Val loss: 0.9891 | Val acc: 54.09% | LR: 0.003288
Epoch: 022 | MCC: 0.040823 | Train loss: 0.9887 | Train acc: 50.49% | Val loss: 0.9836 | Val acc: 54.55% | LR: 0.003272
Epoch: 023 | MCC: 0.020623 | Train loss: 0.9878 | Train acc: 50.64% | Val loss: 0.9796 | Val acc: 53.81% | LR: 0.003255
Epoch: 024 | MCC: 0.034405 | Train loss: 0.9872 | Train acc: 50.68% | Val loss: 0.9350 | Val acc: 53.99% | LR: 0.003237
Epoch: 025 | MCC: 0.036738 | Train loss: 0.9845 | Train acc: 50.98% | Val loss: 0.9531 | Val acc: 54.28% | LR: 0.003219
Epoch: 026 | MCC: 0.038014 | Train loss: 0.9835 | Train acc: 50.92% | Val loss: 0.9354 | Val acc: 54.20% | LR: 0.003199
Epoch: 027 | MCC: 0.041382 | Train loss: 0.9824 | Train acc: 50.83% | Val loss: 0.9282 | Val acc: 54.53% | LR: 0.003180
Epoch: 028 | MCC: 0.015740 | Train loss: 0.9808 | Train acc: 51.37% | Val loss: 0.9744 | Val acc: 53.68% | LR: 0.003159
Epoch: 029 | MCC: 0.019525 | Train loss: 0.9807 | Train acc: 50.93% | Val loss: 0.8994 | Val acc: 55.41% | LR: 0.003138
Epoch: 030 | MCC: 0.010792 | Train loss: 0.9833 | Train acc: 50.97% | Val loss: 0.9292 | Val acc: 55.30% | LR: 0.003116
Epoch: 031 | MCC: 0.008647 | Train loss: 0.9847 | Train acc: 51.24% | Val loss: 0.9284 | Val acc: 55.56% | LR: 0.003094
Epoch: 032 | MCC: 0.007594 | Train loss: 0.9788 | Train acc: 51.66% | Val loss: 0.9214 | Val acc: 56.25% | LR: 0.003071
Epoch: 033 | MCC: 0.008671 | Train loss: 0.9766 | Train acc: 51.66% | Val loss: 0.8889 | Val acc: 56.30% | LR: 0.003048
Epoch: 034 | MCC: -0.002281 | Train loss: 0.9744 | Train acc: 51.69% | Val loss: 0.9071 | Val acc: 55.70% | LR: 0.003024
Epoch: 035 | MCC: -0.043621 | Train loss: 0.9842 | Train acc: 51.33% | Val loss: 1.0714 | Val acc: 46.71% | LR: 0.002999
Epoch: 036 | MCC: -0.004057 | Train loss: 0.9872 | Train acc: 51.23% | Val loss: 1.0358 | Val acc: 47.29% | LR: 0.002974
Epoch: 037 | MCC: 0.002175 | Train loss: 0.9860 | Train acc: 51.29% | Val loss: 1.0016 | Val acc: 48.61% | LR: 0.002949
Epoch: 038 | MCC: 0.033745 | Train loss: 0.9798 | Train acc: 51.24% | Val loss: 0.9751 | Val acc: 54.13% | LR: 0.002922
Epoch: 039 | MCC: 0.053688 | Train loss: 0.9803 | Train acc: 51.29% | Val loss: 0.9958 | Val acc: 49.48% | LR: 0.002896
Epoch: 040 | MCC: 0.031322 | Train loss: 0.9761 | Train acc: 51.49% | Val loss: 0.9056 | Val acc: 56.70% | LR: 0.002868
Epoch: 041 | MCC: 0.018647 | Train loss: 0.9757 | Train acc: 51.55% | Val loss: 0.9124 | Val acc: 55.84% | LR: 0.002841
Epoch: 042 | MCC: 0.030833 | Train loss: 0.9753 | Train acc: 51.57% | Val loss: 0.9216 | Val acc: 57.23% | LR: 0.002812
Epoch: 043 | MCC: 0.030466 | Train loss: 0.9751 | Train acc: 51.69% | Val loss: 0.9005 | Val acc: 55.68% | LR: 0.002784
Epoch: 044 | MCC: 0.026487 | Train loss: 0.9760 | Train acc: 51.55% | Val loss: 0.9018 | Val acc: 57.39% | LR: 0.002754
Epoch: 045 | MCC: 0.035059 | Train loss: 0.9746 | Train acc: 51.58% | Val loss: 0.8751 | Val acc: 57.48% | LR: 0.002725
Epoch: 046 | MCC: 0.033465 | Train loss: 0.9789 | Train acc: 51.21% | Val loss: 0.8824 | Val acc: 57.21% | LR: 0.002695
Epoch: 047 | MCC: 0.029816 | Train loss: 0.9834 | Train acc: 51.73% | Val loss: 0.8910 | Val acc: 57.06% | LR: 0.002664
Epoch: 048 | MCC: 0.030375 | Train loss: 0.9806 | Train acc: 51.93% | Val loss: 0.9330 | Val acc: 57.22% | LR: 0.002634
Epoch: 049 | MCC: 0.033848 | Train loss: 0.9764 | Train acc: 51.81% | Val loss: 0.8852 | Val acc: 56.72% | LR: 0.002602
Epoch: 050 | MCC: 0.026422 | Train loss: 0.9761 | Train acc: 51.70% | Val loss: 0.9280 | Val acc: 54.14% | LR: 0.002571
Epoch: 051 | MCC: 0.039809 | Train loss: 0.9791 | Train acc: 51.48% | Val loss: 0.9552 | Val acc: 54.89% | LR: 0.002539
Epoch: 052 | MCC: 0.029131 | Train loss: 0.9750 | Train acc: 51.62% | Val loss: 0.9234 | Val acc: 54.73% | LR: 0.002506
Epoch: 053 | MCC: 0.003120 | Train loss: 0.9716 | Train acc: 51.71% | Val loss: 0.9233 | Val acc: 55.53% | LR: 0.002474
Epoch: 054 | MCC: 0.006211 | Train loss: 0.9755 | Train acc: 51.42% | Val loss: 0.9415 | Val acc: 55.16% | LR: 0.002441
Epoch: 055 | MCC: -0.010448 | Train loss: 0.9700 | Train acc: 51.79% | Val loss: 0.9177 | Val acc: 55.20% | LR: 0.002407
Epoch: 056 | MCC: 0.018434 | Train loss: 0.9703 | Train acc: 51.66% | Val loss: 0.9066 | Val acc: 56.34% | LR: 0.002374
Epoch: 057 | MCC: 0.033262 | Train loss: 0.9693 | Train acc: 51.65% | Val loss: 0.9111 | Val acc: 55.24% | LR: 0.002340
Epoch: 058 | MCC: 0.037598 | Train loss: 0.9684 | Train acc: 51.76% | Val loss: 0.8969 | Val acc: 56.07% | LR: 0.002305
Epoch: 059 | MCC: -0.002346 | Train loss: 0.9712 | Train acc: 51.67% | Val loss: 0.9032 | Val acc: 55.27% | LR: 0.002271
Epoch: 060 | MCC: -0.002987 | Train loss: 0.9679 | Train acc: 51.74% | Val loss: 0.9084 | Val acc: 55.06% | LR: 0.002236
Epoch: 061 | MCC: -0.015188 | Train loss: 0.9688 | Train acc: 51.75% | Val loss: 0.9113 | Val acc: 54.84% | LR: 0.002202
Epoch: 062 | MCC: -0.006847 | Train loss: 0.9666 | Train acc: 51.82% | Val loss: 0.9089 | Val acc: 55.38% | LR: 0.002166
Epoch: 063 | MCC: 0.048032 | Train loss: 0.9687 | Train acc: 51.60% | Val loss: 0.9024 | Val acc: 56.33% | LR: 0.002131
Epoch: 064 | MCC: 0.050326 | Train loss: 0.9681 | Train acc: 51.79% | Val loss: 0.9272 | Val acc: 55.46% | LR: 0.002096
Epoch: 065 | MCC: 0.045261 | Train loss: 0.9672 | Train acc: 51.73% | Val loss: 0.9060 | Val acc: 55.15% | LR: 0.002060
Epoch: 066 | MCC: 0.022467 | Train loss: 0.9654 | Train acc: 51.97% | Val loss: 0.8950 | Val acc: 56.25% | LR: 0.002024
Epoch: 067 | MCC: 0.033201 | Train loss: 0.9645 | Train acc: 52.01% | Val loss: 0.9070 | Val acc: 55.09% | LR: 0.001989
Epoch: 068 | MCC: 0.023439 | Train loss: 0.9654 | Train acc: 51.96% | Val loss: 0.9115 | Val acc: 54.78% | LR: 0.001953
Epoch: 069 | MCC: 0.016439 | Train loss: 0.9651 | Train acc: 51.99% | Val loss: 0.8977 | Val acc: 55.49% | LR: 0.001916
Epoch: 070 | MCC: 0.041368 | Train loss: 0.9693 | Train acc: 51.65% | Val loss: 0.9263 | Val acc: 53.93% | LR: 0.001880
Epoch: 071 | MCC: 0.042501 | Train loss: 0.9645 | Train acc: 51.93% | Val loss: 0.9003 | Val acc: 55.46% | LR: 0.001844
Epoch: 072 | MCC: 0.034430 | Train loss: 0.9650 | Train acc: 51.81% | Val loss: 0.8955 | Val acc: 55.61% | LR: 0.001808
Epoch: 073 | MCC: 0.035149 | Train loss: 0.9624 | Train acc: 52.05% | Val loss: 0.9246 | Val acc: 54.03% | LR: 0.001771
Epoch: 074 | MCC: 0.032185 | Train loss: 0.9628 | Train acc: 51.98% | Val loss: 0.9175 | Val acc: 54.40% | LR: 0.001735
Epoch: 075 | MCC: 0.012761 | Train loss: 0.9637 | Train acc: 51.86% | Val loss: 0.8939 | Val acc: 55.45% | LR: 0.001699
Epoch: 076 | MCC: 0.025092 | Train loss: 0.9621 | Train acc: 51.95% | Val loss: 0.9099 | Val acc: 54.65% | LR: 0.001663
Epoch: 077 | MCC: 0.018489 | Train loss: 0.9602 | Train acc: 52.10% | Val loss: 0.9178 | Val acc: 54.30% | LR: 0.001626
Epoch: 078 | MCC: 0.049344 | Train loss: 0.9568 | Train acc: 52.36% | Val loss: 0.8951 | Val acc: 55.75% | LR: 0.001590
Epoch: 079 | MCC: 0.018469 | Train loss: 0.9593 | Train acc: 52.28% | Val loss: 0.9030 | Val acc: 54.70% | LR: 0.001554
Epoch: 080 | MCC: 0.050952 | Train loss: 0.9589 | Train acc: 52.31% | Val loss: 0.8980 | Val acc: 55.46% | LR: 0.001518
Epoch: 081 | MCC: 0.025423 | Train loss: 0.9591 | Train acc: 52.18% | Val loss: 0.9109 | Val acc: 55.13% | LR: 0.001482
Epoch: 082 | MCC: 0.026515 | Train loss: 0.9568 | Train acc: 52.35% | Val loss: 0.9122 | Val acc: 54.55% | LR: 0.001446
Epoch: 083 | MCC: 0.032358 | Train loss: 0.9617 | Train acc: 52.12% | Val loss: 0.9169 | Val acc: 54.49% | LR: 0.001410
Epoch: 084 | MCC: 0.010657 | Train loss: 0.9627 | Train acc: 52.15% | Val loss: 0.9870 | Val acc: 54.34% | LR: 0.001375
Epoch: 085 | MCC: 0.000562 | Train loss: 0.9785 | Train acc: 51.99% | Val loss: 0.9184 | Val acc: 54.40% | LR: 0.001339
Epoch: 086 | MCC: 0.018118 | Train loss: 0.9687 | Train acc: 51.72% | Val loss: 0.9437 | Val acc: 55.69% | LR: 0.001304
Epoch: 087 | MCC: 0.047911 | Train loss: 0.9659 | Train acc: 52.13% | Val loss: 0.9238 | Val acc: 55.65% | LR: 0.001269
Epoch: 088 | MCC: -0.007295 | Train loss: 0.9737 | Train acc: 51.86% | Val loss: 0.9211 | Val acc: 54.93% | LR: 0.001234
Epoch: 089 | MCC: -0.008675 | Train loss: 0.9688 | Train acc: 51.77% | Val loss: 0.9056 | Val acc: 54.91% | LR: 0.001199
Epoch: 090 | MCC: 0.002589 | Train loss: 0.9675 | Train acc: 51.80% | Val loss: 0.8967 | Val acc: 55.30% | LR: 0.001165
Epoch: 091 | MCC: 0.007869 | Train loss: 0.9672 | Train acc: 51.77% | Val loss: 0.8877 | Val acc: 55.80% | LR: 0.001131
Epoch: 092 | MCC: 0.003233 | Train loss: 0.9645 | Train acc: 51.85% | Val loss: 0.8918 | Val acc: 55.50% | LR: 0.001097
Epoch: 093 | MCC: -0.005460 | Train loss: 0.9657 | Train acc: 51.78% | Val loss: 0.9057 | Val acc: 54.67% | LR: 0.001063
Epoch: 094 | MCC: 0.002827 | Train loss: 0.9653 | Train acc: 51.80% | Val loss: 0.9036 | Val acc: 54.99% | LR: 0.001030
Epoch: 095 | MCC: 0.009119 | Train loss: 0.9629 | Train acc: 51.90% | Val loss: 0.9069 | Val acc: 55.33% | LR: 0.000997
Epoch: 096 | MCC: -0.004638 | Train loss: 0.9632 | Train acc: 51.91% | Val loss: 0.9079 | Val acc: 54.72% | LR: 0.000964
Epoch: 097 | MCC: -0.017789 | Train loss: 0.9656 | Train acc: 51.76% | Val loss: 0.9037 | Val acc: 54.79% | LR: 0.000932
Epoch: 098 | MCC: -0.000809 | Train loss: 0.9632 | Train acc: 51.93% | Val loss: 0.8915 | Val acc: 55.72% | LR: 0.000900
Epoch: 099 | MCC: -0.008845 | Train loss: 0.9623 | Train acc: 51.93% | Val loss: 0.8965 | Val acc: 56.00% | LR: 0.000868
Epoch: 100 | MCC: -0.008216 | Train loss: 0.9914 | Train acc: 52.25% | Val loss: 0.9850 | Val acc: 50.85% | LR: 0.000837
Epoch: 101 | MCC: -0.016294 | Train loss: 0.9726 | Train acc: 52.20% | Val loss: 0.9287 | Val acc: 54.23% | LR: 0.000806
Epoch: 102 | MCC: -0.006764 | Train loss: 0.9683 | Train acc: 52.11% | Val loss: 0.9453 | Val acc: 53.97% | LR: 0.000775
Epoch: 103 | MCC: -0.004939 | Train loss: 0.9635 | Train acc: 52.06% | Val loss: 0.9360 | Val acc: 54.22% | LR: 0.000745
Epoch: 104 | MCC: 0.003404 | Train loss: 0.9679 | Train acc: 51.95% | Val loss: 0.9418 | Val acc: 54.05% | LR: 0.000716
Epoch: 105 | MCC: 0.011366 | Train loss: 0.9617 | Train acc: 52.12% | Val loss: 0.9080 | Val acc: 55.27% | LR: 0.000687
Epoch: 106 | MCC: -0.006024 | Train loss: 0.9633 | Train acc: 51.98% | Val loss: 0.9229 | Val acc: 54.30% | LR: 0.000658
Epoch: 107 | MCC: 0.021519 | Train loss: 0.9575 | Train acc: 52.26% | Val loss: 0.9167 | Val acc: 55.09% | LR: 0.000630
Epoch: 108 | MCC: 0.007993 | Train loss: 0.9590 | Train acc: 52.22% | Val loss: 0.9138 | Val acc: 54.98% | LR: 0.000602
Epoch: 109 | MCC: -0.003572 | Train loss: 0.9588 | Train acc: 52.19% | Val loss: 0.9238 | Val acc: 54.53% | LR: 0.000575
Epoch: 110 | MCC: -0.003111 | Train loss: 0.9586 | Train acc: 52.17% | Val loss: 0.9222 | Val acc: 54.38% | LR: 0.000548
Epoch: 111 | MCC: 0.010878 | Train loss: 0.9586 | Train acc: 52.16% | Val loss: 0.9198 | Val acc: 54.99% | LR: 0.000522
Epoch: 112 | MCC: 0.001539 | Train loss: 0.9576 | Train acc: 52.21% | Val loss: 0.9175 | Val acc: 55.05% | LR: 0.000496
Epoch: 113 | MCC: -0.005191 | Train loss: 0.9572 | Train acc: 52.26% | Val loss: 0.9124 | Val acc: 54.98% | LR: 0.000471
Epoch: 114 | MCC: 0.018000 | Train loss: 0.9549 | Train acc: 52.43% | Val loss: 0.9100 | Val acc: 55.74% | LR: 0.000446
Epoch: 115 | MCC: 0.005644 | Train loss: 0.9558 | Train acc: 52.35% | Val loss: 0.9078 | Val acc: 55.38% | LR: 0.000422
Epoch: 116 | MCC: 0.004450 | Train loss: 0.9538 | Train acc: 52.45% | Val loss: 0.9108 | Val acc: 55.25% | LR: 0.000399
Epoch: 117 | MCC: 0.002692 | Train loss: 0.9552 | Train acc: 52.34% | Val loss: 0.9143 | Val acc: 54.64% | LR: 0.000376
Epoch: 118 | MCC: 0.003429 | Train loss: 0.9558 | Train acc: 52.34% | Val loss: 0.9085 | Val acc: 55.10% | LR: 0.000354
Epoch: 119 | MCC: -0.001767 | Train loss: 0.9554 | Train acc: 52.36% | Val loss: 0.9080 | Val acc: 55.36% | LR: 0.000332

[I 2025-10-05 09:02:18,526] Trial 12 finished with value: 0.014706894289702177 and parameters: {'lr': 0.0034693386778337516, 'hidden_size': 114, 'dropout': 0.1721284351422082, 'weight_decay': 0.0012645600387685611}. Best is trial 4 with value: 0.04243219271302223.

Epoch: 000 | MCC: 0.041128 | Train loss: 0.9990 | Train acc: 50.33% | Val loss: 1.0009 | Val acc: 48.50% | LR: 0.000483
Epoch: 001 | MCC: 0.049911 | Train loss: 0.9938 | Train acc: 50.70% | Val loss: 1.0009 | Val acc: 46.31% | LR: 0.000483
Epoch: 002 | MCC: 0.061795 | Train loss: 0.9902 | Train acc: 50.65% | Val loss: 1.0004 | Val acc: 48.14% | LR: 0.000483
Epoch: 003 | MCC: 0.080737 | Train loss: 0.9903 | Train acc: 50.57% | Val loss: 0.9999 | Val acc: 49.50% | LR: 0.000482
Epoch: 004 | MCC: 0.062972 | Train loss: 0.9890 | Train acc: 50.60% | Val loss: 0.9972 | Val acc: 50.81% | LR: 0.000482
Epoch: 005 | MCC: 0.038687 | Train loss: 0.9880 | Train acc: 50.61% | Val loss: 0.9948 | Val acc: 51.59% | LR: 0.000481
Epoch: 006 | MCC: 0.031039 | Train loss: 0.9877 | Train acc: 50.79% | Val loss: 0.9891 | Val acc: 53.32% | LR: 0.000480
Epoch: 007 | MCC: 0.043236 | Train loss: 0.9859 | Train acc: 50.76% | Val loss: 0.9812 | Val acc: 54.45% | LR: 0.000480
Epoch: 008 | MCC: 0.039805 | Train loss: 0.9861 | Train acc: 50.77% | Val loss: 0.9717 | Val acc: 55.12% | LR: 0.000479
Epoch: 009 | MCC: 0.033761 | Train loss: 0.9851 | Train acc: 51.06% | Val loss: 0.9612 | Val acc: 55.37% | LR: 0.000478
Epoch: 010 | MCC: 0.033540 | Train loss: 0.9825 | Train acc: 51.04% | Val loss: 0.9508 | Val acc: 55.78% | LR: 0.000477
Epoch: 011 | MCC: 0.026420 | Train loss: 0.9816 | Train acc: 51.00% | Val loss: 0.9399 | Val acc: 55.96% | LR: 0.000475
Epoch: 012 | MCC: 0.024182 | Train loss: 0.9809 | Train acc: 50.83% | Val loss: 0.9363 | Val acc: 55.98% | LR: 0.000474
Epoch: 013 | MCC: 0.024841 | Train loss: 0.9799 | Train acc: 50.96% | Val loss: 0.9250 | Val acc: 56.36% | LR: 0.000473
Epoch: 014 | MCC: 0.022440 | Train loss: 0.9804 | Train acc: 50.86% | Val loss: 0.9198 | Val acc: 56.50% | LR: 0.000471
Epoch: 015 | MCC: 0.030712 | Train loss: 0.9795 | Train acc: 50.93% | Val loss: 0.9090 | Val acc: 56.99% | LR: 0.000470
Epoch: 016 | MCC: 0.059082 | Train loss: 0.9794 | Train acc: 50.93% | Val loss: 0.9045 | Val acc: 58.05% | LR: 0.000468
Epoch: 017 | MCC: 0.034660 | Train loss: 0.9791 | Train acc: 51.10% | Val loss: 0.8807 | Val acc: 58.01% | LR: 0.000466
Epoch: 018 | MCC: 0.028724 | Train loss: 0.9784 | Train acc: 51.08% | Val loss: 0.8756 | Val acc: 57.04% | LR: 0.000464
Epoch: 019 | MCC: -0.003469 | Train loss: 0.9766 | Train acc: 51.14% | Val loss: 0.8797 | Val acc: 56.02% | LR: 0.000462
Epoch: 020 | MCC: 0.018634 | Train loss: 0.9762 | Train acc: 51.18% | Val loss: 0.8835 | Val acc: 56.54% | LR: 0.000460
Epoch: 021 | MCC: 0.015432 | Train loss: 0.9767 | Train acc: 51.23% | Val loss: 0.8471 | Val acc: 58.44% | LR: 0.000458
Epoch: 022 | MCC: 0.029865 | Train loss: 0.9741 | Train acc: 51.25% | Val loss: 0.8352 | Val acc: 59.20% | LR: 0.000456
Epoch: 023 | MCC: 0.036997 | Train loss: 0.9733 | Train acc: 51.30% | Val loss: 0.8300 | Val acc: 59.40% | LR: 0.000453
Epoch: 024 | MCC: 0.011539 | Train loss: 0.9752 | Train acc: 51.14% | Val loss: 0.9008 | Val acc: 55.87% | LR: 0.000451
Epoch: 025 | MCC: 0.008846 | Train loss: 0.9769 | Train acc: 51.16% | Val loss: 0.8907 | Val acc: 55.96% | LR: 0.000448
Epoch: 026 | MCC: 0.008254 | Train loss: 0.9746 | Train acc: 51.21% | Val loss: 0.8787 | Val acc: 56.13% | LR: 0.000446
Epoch: 027 | MCC: 0.002421 | Train loss: 0.9734 | Train acc: 51.31% | Val loss: 0.8942 | Val acc: 55.20% | LR: 0.000443
Epoch: 028 | MCC: 0.027936 | Train loss: 0.9716 | Train acc: 51.89% | Val loss: 0.8279 | Val acc: 59.41% | LR: 0.000440
Epoch: 029 | MCC: 0.009513 | Train loss: 0.9755 | Train acc: 51.21% | Val loss: 0.8770 | Val acc: 56.20% | LR: 0.000437
Epoch: 030 | MCC: 0.047366 | Train loss: 0.9735 | Train acc: 51.90% | Val loss: 0.8238 | Val acc: 59.85% | LR: 0.000434
Epoch: 031 | MCC: 0.015510 | Train loss: 0.9756 | Train acc: 51.65% | Val loss: 0.8999 | Val acc: 54.84% | LR: 0.000431
Epoch: 032 | MCC: 0.015794 | Train loss: 0.9771 | Train acc: 51.74% | Val loss: 0.8821 | Val acc: 56.14% | LR: 0.000428
Epoch: 033 | MCC: 0.063983 | Train loss: 0.9703 | Train acc: 51.91% | Val loss: 0.8099 | Val acc: 60.36% | LR: 0.000424
Epoch: 034 | MCC: 0.030946 | Train loss: 0.9700 | Train acc: 51.93% | Val loss: 0.8188 | Val acc: 59.64% | LR: 0.000421
Epoch: 035 | MCC: 0.030314 | Train loss: 0.9740 | Train acc: 51.86% | Val loss: 0.8244 | Val acc: 59.20% | LR: 0.000418
Epoch: 036 | MCC: 0.052739 | Train loss: 0.9693 | Train acc: 52.08% | Val loss: 0.8805 | Val acc: 56.53% | LR: 0.000414
Epoch: 037 | MCC: 0.024459 | Train loss: 0.9751 | Train acc: 51.64% | Val loss: 0.8502 | Val acc: 58.13% | LR: 0.000411
Epoch: 038 | MCC: 0.051995 | Train loss: 0.9715 | Train acc: 51.88% | Val loss: 0.8161 | Val acc: 60.53% | LR: 0.000407
Epoch: 039 | MCC: 0.040400 | Train loss: 0.9742 | Train acc: 51.66% | Val loss: 0.8334 | Val acc: 59.10% | LR: 0.000403
Epoch: 040 | MCC: 0.021094 | Train loss: 0.9709 | Train acc: 51.92% | Val loss: 0.8615 | Val acc: 57.14% | LR: 0.000400
Epoch: 041 | MCC: 0.026972 | Train loss: 0.9703 | Train acc: 51.88% | Val loss: 0.8694 | Val acc: 56.89% | LR: 0.000396
Epoch: 042 | MCC: 0.034816 | Train loss: 0.9701 | Train acc: 51.86% | Val loss: 0.8653 | Val acc: 57.30% | LR: 0.000392
Epoch: 043 | MCC: 0.028120 | Train loss: 0.9657 | Train acc: 52.05% | Val loss: 0.8349 | Val acc: 58.69% | LR: 0.000388
Epoch: 044 | MCC: 0.035450 | Train loss: 0.9634 | Train acc: 52.20% | Val loss: 0.8395 | Val acc: 58.32% | LR: 0.000384
Epoch: 045 | MCC: 0.068522 | Train loss: 0.9678 | Train acc: 52.03% | Val loss: 0.8130 | Val acc: 59.95% | LR: 0.000380
Epoch: 046 | MCC: 0.060900 | Train loss: 0.9692 | Train acc: 51.88% | Val loss: 0.8228 | Val acc: 59.15% | LR: 0.000375
Epoch: 047 | MCC: 0.024752 | Train loss: 0.9667 | Train acc: 52.04% | Val loss: 0.8167 | Val acc: 59.46% | LR: 0.000371
Epoch: 048 | MCC: 0.039439 | Train loss: 0.9680 | Train acc: 51.98% | Val loss: 0.8087 | Val acc: 60.12% | LR: 0.000367
Epoch: 049 | MCC: 0.027845 | Train loss: 0.9684 | Train acc: 51.88% | Val loss: 0.8469 | Val acc: 58.06% | LR: 0.000363
Epoch: 050 | MCC: 0.037598 | Train loss: 0.9642 | Train acc: 52.06% | Val loss: 0.8172 | Val acc: 59.65% | LR: 0.000358
Epoch: 051 | MCC: 0.039540 | Train loss: 0.9644 | Train acc: 51.95% | Val loss: 0.8053 | Val acc: 60.30% | LR: 0.000354
Epoch: 052 | MCC: 0.056655 | Train loss: 0.9616 | Train acc: 52.15% | Val loss: 0.8167 | Val acc: 59.82% | LR: 0.000349
Epoch: 053 | MCC: 0.020546 | Train loss: 0.9625 | Train acc: 52.14% | Val loss: 0.8260 | Val acc: 59.12% | LR: 0.000345
Epoch: 054 | MCC: 0.023484 | Train loss: 0.9636 | Train acc: 52.00% | Val loss: 0.8328 | Val acc: 58.95% | LR: 0.000340
Epoch: 055 | MCC: 0.073577 | Train loss: 0.9649 | Train acc: 52.05% | Val loss: 0.8188 | Val acc: 59.44% | LR: 0.000335
Epoch: 056 | MCC: 0.031206 | Train loss: 0.9629 | Train acc: 52.04% | Val loss: 0.8190 | Val acc: 59.24% | LR: 0.000331
Epoch: 057 | MCC: 0.032250 | Train loss: 0.9628 | Train acc: 52.08% | Val loss: 0.8351 | Val acc: 58.56% | LR: 0.000326
Epoch: 058 | MCC: 0.024971 | Train loss: 0.9647 | Train acc: 51.96% | Val loss: 0.8501 | Val acc: 57.90% | LR: 0.000321
Epoch: 059 | MCC: 0.028821 | Train loss: 0.9624 | Train acc: 52.11% | Val loss: 0.8403 | Val acc: 58.10% | LR: 0.000317
Epoch: 060 | MCC: 0.024882 | Train loss: 0.9636 | Train acc: 52.01% | Val loss: 0.8428 | Val acc: 58.35% | LR: 0.000312
Epoch: 061 | MCC: 0.049498 | Train loss: 0.9620 | Train acc: 52.09% | Val loss: 0.8057 | Val acc: 60.05% | LR: 0.000307
Epoch: 062 | MCC: 0.060466 | Train loss: 0.9621 | Train acc: 52.09% | Val loss: 0.8011 | Val acc: 60.13% | LR: 0.000302
Epoch: 063 | MCC: 0.027418 | Train loss: 0.9625 | Train acc: 52.08% | Val loss: 0.8278 | Val acc: 58.79% | LR: 0.000297
Epoch: 064 | MCC: 0.028457 | Train loss: 0.9602 | Train acc: 52.19% | Val loss: 0.8450 | Val acc: 57.98% | LR: 0.000292
Epoch: 065 | MCC: 0.038736 | Train loss: 0.9643 | Train acc: 52.05% | Val loss: 0.8095 | Val acc: 59.72% | LR: 0.000287
Epoch: 066 | MCC: 0.049133 | Train loss: 0.9643 | Train acc: 51.98% | Val loss: 0.8032 | Val acc: 60.06% | LR: 0.000282
Epoch: 067 | MCC: 0.034961 | Train loss: 0.9620 | Train acc: 52.08% | Val loss: 0.8170 | Val acc: 59.46% | LR: 0.000277
Epoch: 068 | MCC: 0.032959 | Train loss: 0.9594 | Train acc: 52.23% | Val loss: 0.8242 | Val acc: 59.10% | LR: 0.000272
Epoch: 069 | MCC: 0.033541 | Train loss: 0.9582 | Train acc: 52.30% | Val loss: 0.8254 | Val acc: 59.10% | LR: 0.000267
Epoch: 070 | MCC: 0.025875 | Train loss: 0.9638 | Train acc: 52.00% | Val loss: 0.8159 | Val acc: 59.41% | LR: 0.000262
Epoch: 071 | MCC: 0.036451 | Train loss: 0.9619 | Train acc: 52.10% | Val loss: 0.8123 | Val acc: 59.65% | LR: 0.000257
Epoch: 072 | MCC: 0.029626 | Train loss: 0.9608 | Train acc: 52.12% | Val loss: 0.8247 | Val acc: 58.88% | LR: 0.000252
Epoch: 073 | MCC: 0.032008 | Train loss: 0.9620 | Train acc: 52.07% | Val loss: 0.8159 | Val acc: 59.42% | LR: 0.000247
Epoch: 074 | MCC: 0.029819 | Train loss: 0.9605 | Train acc: 52.16% | Val loss: 0.8171 | Val acc: 59.32% | LR: 0.000242
Epoch: 075 | MCC: 0.031657 | Train loss: 0.9600 | Train acc: 52.14% | Val loss: 0.8111 | Val acc: 59.68% | LR: 0.000237
Epoch: 076 | MCC: 0.034208 | Train loss: 0.9600 | Train acc: 52.14% | Val loss: 0.8186 | Val acc: 59.37% | LR: 0.000232
Epoch: 077 | MCC: 0.032843 | Train loss: 0.9609 | Train acc: 52.08% | Val loss: 0.8197 | Val acc: 59.32% | LR: 0.000227
Epoch: 078 | MCC: 0.028858 | Train loss: 0.9622 | Train acc: 52.00% | Val loss: 0.8320 | Val acc: 58.62% | LR: 0.000222
Epoch: 079 | MCC: 0.054247 | Train loss: 0.9590 | Train acc: 52.19% | Val loss: 0.8140 | Val acc: 59.52% | LR: 0.000217
Epoch: 080 | MCC: 0.028984 | Train loss: 0.9584 | Train acc: 52.19% | Val loss: 0.8314 | Val acc: 58.59% | LR: 0.000212
Epoch: 081 | MCC: 0.035666 | Train loss: 0.9597 | Train acc: 52.15% | Val loss: 0.8109 | Val acc: 59.78% | LR: 0.000207
Epoch: 082 | MCC: 0.033027 | Train loss: 0.9577 | Train acc: 52.27% | Val loss: 0.8199 | Val acc: 59.22% | LR: 0.000202
Epoch: 083 | MCC: 0.032896 | Train loss: 0.9603 | Train acc: 52.13% | Val loss: 0.8233 | Val acc: 59.20% | LR: 0.000197
Epoch: 084 | MCC: 0.027076 | Train loss: 0.9584 | Train acc: 52.21% | Val loss: 0.8347 | Val acc: 58.54% | LR: 0.000192
Epoch: 085 | MCC: 0.022233 | Train loss: 0.9653 | Train acc: 51.97% | Val loss: 0.8413 | Val acc: 58.18% | LR: 0.000187
Epoch: 086 | MCC: 0.024536 | Train loss: 0.9622 | Train acc: 52.10% | Val loss: 0.8336 | Val acc: 58.54% | LR: 0.000182
Epoch: 087 | MCC: 0.022988 | Train loss: 0.9668 | Train acc: 51.84% | Val loss: 0.8293 | Val acc: 58.78% | LR: 0.000177
Epoch: 088 | MCC: 0.018560 | Train loss: 0.9632 | Train acc: 51.95% | Val loss: 0.8416 | Val acc: 58.08% | LR: 0.000172
Epoch: 089 | MCC: 0.024860 | Train loss: 0.9609 | Train acc: 52.07% | Val loss: 0.8438 | Val acc: 58.05% | LR: 0.000168
Epoch: 090 | MCC: 0.025415 | Train loss: 0.9620 | Train acc: 52.02% | Val loss: 0.8429 | Val acc: 58.03% | LR: 0.000163
Epoch: 091 | MCC: 0.016300 | Train loss: 0.9604 | Train acc: 52.11% | Val loss: 0.8430 | Val acc: 57.91% | LR: 0.000158
Epoch: 092 | MCC: 0.022443 | Train loss: 0.9617 | Train acc: 52.03% | Val loss: 0.8447 | Val acc: 57.83% | LR: 0.000153
Epoch: 093 | MCC: 0.022666 | Train loss: 0.9610 | Train acc: 52.06% | Val loss: 0.8338 | Val acc: 58.59% | LR: 0.000149
Epoch: 094 | MCC: 0.026515 | Train loss: 0.9602 | Train acc: 52.13% | Val loss: 0.8282 | Val acc: 58.84% | LR: 0.000144
Epoch: 095 | MCC: 0.025956 | Train loss: 0.9592 | Train acc: 52.14% | Val loss: 0.8393 | Val acc: 58.25% | LR: 0.000139
Epoch: 096 | MCC: 0.028751 | Train loss: 0.9615 | Train acc: 52.03% | Val loss: 0.8260 | Val acc: 58.93% | LR: 0.000135
Epoch: 097 | MCC: 0.023593 | Train loss: 0.9601 | Train acc: 52.11% | Val loss: 0.8399 | Val acc: 58.18% | LR: 0.000130
Epoch: 098 | MCC: 0.020572 | Train loss: 0.9604 | Train acc: 52.09% | Val loss: 0.8358 | Val acc: 58.35% | LR: 0.000126
Epoch: 099 | MCC: 0.021550 | Train loss: 0.9605 | Train acc: 52.10% | Val loss: 0.8386 | Val acc: 58.32% | LR: 0.000122
Epoch: 100 | MCC: 0.026428 | Train loss: 0.9596 | Train acc: 52.14% | Val loss: 0.8285 | Val acc: 58.79% | LR: 0.000117
Epoch: 101 | MCC: 0.022732 | Train loss: 0.9602 | Train acc: 52.09% | Val loss: 0.8346 | Val acc: 58.47% | LR: 0.000113
Epoch: 102 | MCC: 0.025060 | Train loss: 0.9601 | Train acc: 52.11% | Val loss: 0.8286 | Val acc: 58.74% | LR: 0.000109
Epoch: 103 | MCC: 0.017725 | Train loss: 0.9608 | Train acc: 52.08% | Val loss: 0.8383 | Val acc: 58.27% | LR: 0.000104
Epoch: 104 | MCC: 0.026257 | Train loss: 0.9601 | Train acc: 52.10% | Val loss: 0.8426 | Val acc: 58.18% | LR: 0.000100
Epoch: 105 | MCC: 0.023281 | Train loss: 0.9603 | Train acc: 52.09% | Val loss: 0.8356 | Val acc: 58.52% | LR: 0.000096
Epoch: 106 | MCC: 0.023166 | Train loss: 0.9593 | Train acc: 52.14% | Val loss: 0.8484 | Val acc: 57.86% | LR: 0.000092
Epoch: 107 | MCC: 0.025207 | Train loss: 0.9607 | Train acc: 52.06% | Val loss: 0.8474 | Val acc: 57.98% | LR: 0.000088
Epoch: 108 | MCC: 0.019640 | Train loss: 0.9621 | Train acc: 52.00% | Val loss: 0.8402 | Val acc: 58.35% | LR: 0.000085
Epoch: 109 | MCC: 0.016790 | Train loss: 0.9609 | Train acc: 52.05% | Val loss: 0.8405 | Val acc: 58.08% | LR: 0.000081
Epoch: 110 | MCC: 0.016821 | Train loss: 0.9601 | Train acc: 52.09% | Val loss: 0.8401 | Val acc: 58.18% | LR: 0.000077
Epoch: 111 | MCC: 0.022603 | Train loss: 0.9607 | Train acc: 52.05% | Val loss: 0.8408 | Val acc: 58.15% | LR: 0.000073
Epoch: 112 | MCC: 0.023461 | Train loss: 0.9607 | Train acc: 52.06% | Val loss: 0.8395 | Val acc: 58.22% | LR: 0.000070
Epoch: 113 | MCC: 0.023372 | Train loss: 0.9577 | Train acc: 52.22% | Val loss: 0.8400 | Val acc: 58.22% | LR: 0.000066
Epoch: 114 | MCC: 0.025959 | Train loss: 0.9591 | Train acc: 52.15% | Val loss: 0.8401 | Val acc: 58.18% | LR: 0.000063
Epoch: 115 | MCC: 0.024925 | Train loss: 0.9590 | Train acc: 52.14% | Val loss: 0.8429 | Val acc: 58.03% | LR: 0.000060
Epoch: 116 | MCC: 0.027045 | Train loss: 0.9615 | Train acc: 52.02% | Val loss: 0.8420 | Val acc: 58.25% | LR: 0.000056
Epoch: 117 | MCC: 0.027021 | Train loss: 0.9611 | Train acc: 52.04% | Val loss: 0.8423 | Val acc: 58.10% | LR: 0.000053
Epoch: 118 | MCC: 0.027382 | Train loss: 0.9610 | Train acc: 52.06% | Val loss: 0.8418 | Val acc: 58.20% | LR: 0.000050
Epoch: 119 | MCC: 0.026295 | Train loss: 0.9612 | Train acc: 52.04% | Val loss: 0.8402 | Val acc: 58.22% | LR: 0.000047
Epoch: 120 | MCC: 0.027522 | Train loss: 0.9641 | Train acc: 51.88% | Val loss: 0.8433 | Val acc: 58.13% | LR: 0.000044
Epoch: 121 | MCC: 0.025026 | Train loss: 0.9616 | Train acc: 52.02% | Val loss: 0.8429 | Val acc: 58.15% | LR: 0.000041
Epoch: 122 | MCC: 0.027497 | Train loss: 0.9598 | Train acc: 52.11% | Val loss: 0.8423 | Val acc: 58.18% | LR: 0.000039
Epoch: 123 | MCC: 0.028020 | Train loss: 0.9582 | Train acc: 52.20% | Val loss: 0.8413 | Val acc: 58.30% | LR: 0.000036
Epoch: 124 | MCC: 0.026997 | Train loss: 0.9606 | Train acc: 52.07% | Val loss: 0.8418 | Val acc: 58.15% | LR: 0.000033
Epoch: 125 | MCC: 0.026569 | Train loss: 0.9597 | Train acc: 52.12% | Val loss: 0.8423 | Val acc: 58.15% | LR: 0.000031
Epoch: 126 | MCC: 0.026357 | Train loss: 0.9570 | Train acc: 52.25% | Val loss: 0.8415 | Val acc: 58.15% | LR: 0.000028
Epoch: 127 | MCC: 0.026206 | Train loss: 0.9580 | Train acc: 52.20% | Val loss: 0.8426 | Val acc: 58.20% | LR: 0.000026
Epoch: 128 | MCC: 0.025956 | Train loss: 0.9599 | Train acc: 52.10% | Val loss: 0.8434 | Val acc: 58.08% | LR: 0.000024
Epoch: 129 | MCC: 0.026569 | Train loss: 0.9595 | Train acc: 52.12% | Val loss: 0.8421 | Val acc: 58.15% | LR: 0.000022
Epoch: 130 | MCC: 0.026727 | Train loss: 0.9588 | Train acc: 52.17% | Val loss: 0.8428 | Val acc: 58.13% | LR: 0.000020
Epoch: 131 | MCC: 0.026727 | Train loss: 0.9601 | Train acc: 52.10% | Val loss: 0.8425 | Val acc: 58.13% | LR: 0.000018
Epoch: 132 | MCC: 0.026727 | Train loss: 0.9589 | Train acc: 52.17% | Val loss: 0.8428 | Val acc: 58.13% | LR: 0.000016
Epoch: 133 | MCC: 0.026569 | Train loss: 0.9595 | Train acc: 52.13% | Val loss: 0.8422 | Val acc: 58.15% | LR: 0.000014
Epoch: 134 | MCC: 0.026727 | Train loss: 0.9609 | Train acc: 52.06% | Val loss: 0.8426 | Val acc: 58.13% | LR: 0.000013
Epoch: 135 | MCC: 0.026569 | Train loss: 0.9585 | Train acc: 52.18% | Val loss: 0.8422 | Val acc: 58.15% | LR: 0.000011
Epoch: 136 | MCC: 0.026569 | Train loss: 0.9566 | Train acc: 52.28% | Val loss: 0.8424 | Val acc: 58.15% | LR: 0.000010

[I 2025-10-05 09:04:26,780] Trial 13 finished with value: 0.026569227688014507 and parameters: {'lr': 0.00048307204796837995, 'hidden_size': 90, 'dropout': 0.34174264038163593, 'weight_decay': 0.00031023777226364175}. Best is trial 4 with value: 0.04243219271302223.

Epoch: 000 | MCC: 0.013346 | Train loss: 1.0081 | Train acc: 50.60% | Val loss: 0.9663 | Val acc: 53.91% | LR: 0.000680
Epoch: 001 | MCC: 0.019319 | Train loss: 0.9902 | Train acc: 50.84% | Val loss: 0.9604 | Val acc: 54.36% | LR: 0.000680
Epoch: 002 | MCC: 0.022192 | Train loss: 0.9858 | Train acc: 51.03% | Val loss: 0.9542 | Val acc: 54.85% | LR: 0.000679
Epoch: 003 | MCC: 0.023260 | Train loss: 0.9838 | Train acc: 50.93% | Val loss: 0.9505 | Val acc: 54.92% | LR: 0.000679
Epoch: 004 | MCC: 0.015997 | Train loss: 0.9839 | Train acc: 50.98% | Val loss: 0.9356 | Val acc: 55.21% | LR: 0.000678
Epoch: 005 | MCC: 0.024110 | Train loss: 0.9813 | Train acc: 51.03% | Val loss: 0.9267 | Val acc: 55.89% | LR: 0.000677
Epoch: 006 | MCC: 0.024918 | Train loss: 0.9850 | Train acc: 50.83% | Val loss: 0.9126 | Val acc: 56.10% | LR: 0.000676
Epoch: 007 | MCC: 0.030317 | Train loss: 0.9807 | Train acc: 51.05% | Val loss: 0.8977 | Val acc: 56.30% | LR: 0.000675
Epoch: 008 | MCC: 0.036483 | Train loss: 0.9810 | Train acc: 50.98% | Val loss: 0.9091 | Val acc: 57.05% | LR: 0.000674
Epoch: 009 | MCC: 0.041456 | Train loss: 0.9806 | Train acc: 51.09% | Val loss: 0.8827 | Val acc: 57.09% | LR: 0.000672
Epoch: 010 | MCC: 0.032385 | Train loss: 0.9808 | Train acc: 51.11% | Val loss: 0.8927 | Val acc: 57.79% | LR: 0.000671
Epoch: 011 | MCC: -0.006167 | Train loss: 0.9769 | Train acc: 51.31% | Val loss: 0.8958 | Val acc: 55.91% | LR: 0.000669
Epoch: 012 | MCC: 0.019138 | Train loss: 0.9770 | Train acc: 51.24% | Val loss: 0.8685 | Val acc: 57.39% | LR: 0.000667
Epoch: 013 | MCC: 0.012605 | Train loss: 1.0538 | Train acc: 51.21% | Val loss: 0.8576 | Val acc: 58.71% | LR: 0.000665
Epoch: 014 | MCC: 0.034179 | Train loss: 0.9779 | Train acc: 51.07% | Val loss: 0.8329 | Val acc: 59.29% | LR: 0.000663
Epoch: 015 | MCC: -0.009577 | Train loss: 0.9772 | Train acc: 51.09% | Val loss: 0.9452 | Val acc: 56.02% | LR: 0.000661
Epoch: 016 | MCC: 0.007800 | Train loss: 0.9764 | Train acc: 51.32% | Val loss: 0.9011 | Val acc: 54.90% | LR: 0.000659
Epoch: 017 | MCC: -0.005265 | Train loss: 0.9799 | Train acc: 50.89% | Val loss: 0.9012 | Val acc: 55.32% | LR: 0.000656
Epoch: 018 | MCC: 0.012552 | Train loss: 0.9836 | Train acc: 51.02% | Val loss: 0.8884 | Val acc: 58.06% | LR: 0.000653
Epoch: 019 | MCC: 0.008063 | Train loss: 0.9910 | Train acc: 50.92% | Val loss: 0.8938 | Val acc: 57.42% | LR: 0.000651
Epoch: 020 | MCC: 0.005990 | Train loss: 0.9835 | Train acc: 50.87% | Val loss: 0.8886 | Val acc: 56.73% | LR: 0.000648
Epoch: 021 | MCC: -0.004387 | Train loss: 0.9807 | Train acc: 50.97% | Val loss: 0.8808 | Val acc: 57.04% | LR: 0.000644
Epoch: 022 | MCC: 0.006612 | Train loss: 0.9828 | Train acc: 50.91% | Val loss: 0.8783 | Val acc: 57.16% | LR: 0.000641
Epoch: 023 | MCC: 0.012404 | Train loss: 0.9814 | Train acc: 50.98% | Val loss: 0.8664 | Val acc: 57.36% | LR: 0.000638
Epoch: 024 | MCC: 0.006727 | Train loss: 0.9796 | Train acc: 51.00% | Val loss: 0.9165 | Val acc: 57.18% | LR: 0.000634
Epoch: 025 | MCC: 0.014206 | Train loss: 0.9801 | Train acc: 51.01% | Val loss: 0.8723 | Val acc: 56.97% | LR: 0.000631
Epoch: 026 | MCC: 0.002452 | Train loss: 0.9811 | Train acc: 50.95% | Val loss: 0.9047 | Val acc: 56.05% | LR: 0.000627
Epoch: 027 | MCC: -0.003187 | Train loss: 0.9793 | Train acc: 51.03% | Val loss: 0.9197 | Val acc: 55.00% | LR: 0.000623
Epoch: 028 | MCC: -0.005596 | Train loss: 0.9781 | Train acc: 51.05% | Val loss: 0.9118 | Val acc: 54.90% | LR: 0.000619
Epoch: 029 | MCC: -0.013529 | Train loss: 0.9854 | Train acc: 50.98% | Val loss: 0.9126 | Val acc: 54.51% | LR: 0.000615
Epoch: 030 | MCC: -0.015909 | Train loss: 0.9807 | Train acc: 50.87% | Val loss: 0.9091 | Val acc: 54.42% | LR: 0.000611
Epoch: 031 | MCC: -0.018136 | Train loss: 0.9787 | Train acc: 51.07% | Val loss: 0.9116 | Val acc: 54.54% | LR: 0.000606
Epoch: 032 | MCC: 0.000080 | Train loss: 0.9769 | Train acc: 51.00% | Val loss: 0.8887 | Val acc: 55.56% | LR: 0.000602
Epoch: 033 | MCC: 0.012218 | Train loss: 0.9791 | Train acc: 51.35% | Val loss: 0.8668 | Val acc: 56.87% | LR: 0.000597
Epoch: 034 | MCC: 0.005911 | Train loss: 0.9768 | Train acc: 51.04% | Val loss: 0.8716 | Val acc: 56.79% | LR: 0.000593
Epoch: 035 | MCC: 0.007634 | Train loss: 0.9776 | Train acc: 50.98% | Val loss: 0.8612 | Val acc: 57.33% | LR: 0.000588
Epoch: 036 | MCC: 0.003436 | Train loss: 0.9781 | Train acc: 50.94% | Val loss: 0.8688 | Val acc: 56.73% | LR: 0.000583
Epoch: 037 | MCC: 0.002823 | Train loss: 0.9761 | Train acc: 51.12% | Val loss: 0.8893 | Val acc: 56.23% | LR: 0.000578
Epoch: 038 | MCC: 0.000647 | Train loss: 0.9774 | Train acc: 50.99% | Val loss: 0.8788 | Val acc: 56.11% | LR: 0.000573
Epoch: 039 | MCC: 0.001628 | Train loss: 0.9768 | Train acc: 51.17% | Val loss: 0.8805 | Val acc: 56.16% | LR: 0.000568
Epoch: 040 | MCC: 0.007213 | Train loss: 0.9772 | Train acc: 51.24% | Val loss: 0.8927 | Val acc: 56.39% | LR: 0.000562
Epoch: 041 | MCC: 0.001767 | Train loss: 0.9766 | Train acc: 50.88% | Val loss: 0.8738 | Val acc: 56.24% | LR: 0.000557
Epoch: 042 | MCC: 0.015706 | Train loss: 0.9792 | Train acc: 51.15% | Val loss: 0.8682 | Val acc: 57.28% | LR: 0.000551
Epoch: 043 | MCC: 0.015414 | Train loss: 0.9784 | Train acc: 51.49% | Val loss: 0.8651 | Val acc: 57.31% | LR: 0.000546
Epoch: 044 | MCC: 0.010211 | Train loss: 0.9770 | Train acc: 51.47% | Val loss: 0.8710 | Val acc: 56.88% | LR: 0.000540
Epoch: 045 | MCC: 0.004095 | Train loss: 0.9769 | Train acc: 51.68% | Val loss: 0.8835 | Val acc: 56.17% | LR: 0.000534
Epoch: 046 | MCC: -0.007520 | Train loss: 1.0501 | Train acc: 51.74% | Val loss: 0.9008 | Val acc: 55.96% | LR: 0.000528
Epoch: 047 | MCC: 0.001294 | Train loss: 0.9761 | Train acc: 51.58% | Val loss: 0.8773 | Val acc: 56.52% | LR: 0.000522
Epoch: 048 | MCC: 0.002119 | Train loss: 0.9748 | Train acc: 51.69% | Val loss: 0.8754 | Val acc: 56.40% | LR: 0.000516
Epoch: 049 | MCC: 0.007816 | Train loss: 0.9753 | Train acc: 51.67% | Val loss: 0.8957 | Val acc: 56.66% | LR: 0.000510
Epoch: 050 | MCC: -0.000534 | Train loss: 1.0123 | Train acc: 51.57% | Val loss: 0.8771 | Val acc: 56.52% | LR: 0.000504
Epoch: 051 | MCC: 0.028620 | Train loss: 0.9766 | Train acc: 51.67% | Val loss: 0.8774 | Val acc: 57.20% | LR: 0.000498
Epoch: 052 | MCC: 0.008810 | Train loss: 0.9746 | Train acc: 51.77% | Val loss: 0.8698 | Val acc: 56.99% | LR: 0.000491
Epoch: 053 | MCC: 0.007781 | Train loss: 0.9759 | Train acc: 51.56% | Val loss: 0.8705 | Val acc: 56.90% | LR: 0.000485
Epoch: 054 | MCC: 0.044969 | Train loss: 0.9757 | Train acc: 51.61% | Val loss: 0.8638 | Val acc: 57.90% | LR: 0.000479
Epoch: 055 | MCC: 0.041597 | Train loss: 0.9749 | Train acc: 51.66% | Val loss: 0.8653 | Val acc: 57.87% | LR: 0.000472
Epoch: 056 | MCC: 0.044963 | Train loss: 0.9755 | Train acc: 51.79% | Val loss: 0.8637 | Val acc: 57.88% | LR: 0.000465
Epoch: 057 | MCC: 0.047992 | Train loss: 0.9736 | Train acc: 51.71% | Val loss: 0.8854 | Val acc: 58.17% | LR: 0.000459
Epoch: 058 | MCC: 0.044526 | Train loss: 0.9724 | Train acc: 51.79% | Val loss: 0.8688 | Val acc: 57.91% | LR: 0.000452
Epoch: 059 | MCC: 0.027798 | Train loss: 1.0679 | Train acc: 51.56% | Val loss: 0.8850 | Val acc: 56.97% | LR: 0.000445
Epoch: 060 | MCC: 0.035288 | Train loss: 0.9851 | Train acc: 51.44% | Val loss: 0.8706 | Val acc: 57.31% | LR: 0.000439
Epoch: 061 | MCC: 0.026793 | Train loss: 0.9808 | Train acc: 51.41% | Val loss: 0.8732 | Val acc: 57.32% | LR: 0.000432
Epoch: 062 | MCC: 0.040416 | Train loss: 0.9839 | Train acc: 51.58% | Val loss: 0.8661 | Val acc: 57.77% | LR: 0.000425
Epoch: 063 | MCC: 0.042870 | Train loss: 0.9765 | Train acc: 51.58% | Val loss: 0.8655 | Val acc: 57.77% | LR: 0.000418
Epoch: 064 | MCC: 0.025308 | Train loss: 0.9732 | Train acc: 51.73% | Val loss: 0.8685 | Val acc: 57.32% | LR: 0.000411
Epoch: 065 | MCC: 0.027458 | Train loss: 0.9754 | Train acc: 51.50% | Val loss: 0.8715 | Val acc: 57.48% | LR: 0.000404
Epoch: 066 | MCC: 0.048402 | Train loss: 0.9724 | Train acc: 51.71% | Val loss: 0.8757 | Val acc: 58.35% | LR: 0.000397
Epoch: 067 | MCC: 0.045026 | Train loss: 0.9720 | Train acc: 51.70% | Val loss: 0.8618 | Val acc: 58.46% | LR: 0.000390
Epoch: 068 | MCC: 0.022889 | Train loss: 0.9726 | Train acc: 51.67% | Val loss: 0.8998 | Val acc: 58.21% | LR: 0.000383
Epoch: 069 | MCC: 0.038896 | Train loss: 0.9740 | Train acc: 51.64% | Val loss: 0.8574 | Val acc: 58.18% | LR: 0.000376
Epoch: 070 | MCC: 0.019869 | Train loss: 0.9726 | Train acc: 51.71% | Val loss: 0.8611 | Val acc: 57.72% | LR: 0.000369
Epoch: 071 | MCC: 0.026011 | Train loss: 0.9754 | Train acc: 51.49% | Val loss: 0.8566 | Val acc: 58.00% | LR: 0.000362
Epoch: 072 | MCC: 0.034799 | Train loss: 0.9729 | Train acc: 51.61% | Val loss: 0.8553 | Val acc: 58.25% | LR: 0.000355
Epoch: 073 | MCC: 0.022717 | Train loss: 0.9701 | Train acc: 51.79% | Val loss: 0.8613 | Val acc: 57.75% | LR: 0.000348
Epoch: 074 | MCC: 0.045858 | Train loss: 0.9727 | Train acc: 51.68% | Val loss: 0.8666 | Val acc: 58.52% | LR: 0.000340
Epoch: 075 | MCC: 0.043389 | Train loss: 0.9711 | Train acc: 51.68% | Val loss: 0.8712 | Val acc: 58.35% | LR: 0.000333
Epoch: 076 | MCC: 0.035750 | Train loss: 0.9701 | Train acc: 51.72% | Val loss: 0.8627 | Val acc: 58.27% | LR: 0.000326
Epoch: 077 | MCC: 0.045506 | Train loss: 0.9703 | Train acc: 51.70% | Val loss: 0.8643 | Val acc: 58.24% | LR: 0.000319
Epoch: 078 | MCC: 0.053621 | Train loss: 0.9720 | Train acc: 51.69% | Val loss: 0.8653 | Val acc: 58.54% | LR: 0.000312
Epoch: 079 | MCC: 0.044835 | Train loss: 0.9712 | Train acc: 51.65% | Val loss: 0.8594 | Val acc: 58.21% | LR: 0.000305
Epoch: 080 | MCC: 0.036869 | Train loss: 0.9691 | Train acc: 51.73% | Val loss: 0.8638 | Val acc: 58.31% | LR: 0.000298
Epoch: 081 | MCC: 0.037411 | Train loss: 0.9685 | Train acc: 51.76% | Val loss: 0.8575 | Val acc: 58.28% | LR: 0.000291
Epoch: 082 | MCC: 0.039385 | Train loss: 0.9700 | Train acc: 51.70% | Val loss: 0.8572 | Val acc: 58.50% | LR: 0.000284
Epoch: 083 | MCC: 0.042192 | Train loss: 0.9688 | Train acc: 51.77% | Val loss: 0.8596 | Val acc: 58.35% | LR: 0.000277
Epoch: 084 | MCC: 0.031095 | Train loss: 0.9732 | Train acc: 51.52% | Val loss: 0.8672 | Val acc: 58.21% | LR: 0.000270
Epoch: 085 | MCC: 0.030112 | Train loss: 0.9712 | Train acc: 51.73% | Val loss: 0.8720 | Val acc: 57.87% | LR: 0.000263
Epoch: 086 | MCC: 0.046766 | Train loss: 0.9705 | Train acc: 51.63% | Val loss: 0.8724 | Val acc: 58.32% | LR: 0.000256
Epoch: 087 | MCC: 0.049060 | Train loss: 0.9692 | Train acc: 51.71% | Val loss: 0.8676 | Val acc: 58.14% | LR: 0.000249
Epoch: 088 | MCC: 0.037668 | Train loss: 0.9687 | Train acc: 51.75% | Val loss: 0.8715 | Val acc: 58.10% | LR: 0.000242

[I 2025-10-05 09:06:04,018] Trial 14 finished with value: 0.04210797697305679 and parameters: {'lr': 0.0006798919162535369, 'hidden_size': 107, 'dropout': 0.19047844798123598, 'weight_decay': 0.014122168054324938}. Best is trial 4 with value: 0.04243219271302223.

Epoch: 000 | MCC: -0.003398 | Train loss: 1.0008 | Train acc: 50.51% | Val loss: 1.0045 | Val acc: 47.76% | LR: 0.000109
Epoch: 001 | MCC: 0.002257 | Train loss: 0.9997 | Train acc: 50.33% | Val loss: 1.0029 | Val acc: 47.78% | LR: 0.000109
Epoch: 002 | MCC: 0.012987 | Train loss: 1.0008 | Train acc: 50.34% | Val loss: 1.0021 | Val acc: 48.27% | LR: 0.000109
Epoch: 003 | MCC: 0.012308 | Train loss: 1.0008 | Train acc: 50.26% | Val loss: 1.0017 | Val acc: 48.14% | LR: 0.000109
Epoch: 004 | MCC: 0.012898 | Train loss: 0.9972 | Train acc: 50.37% | Val loss: 1.0016 | Val acc: 48.35% | LR: 0.000108
Epoch: 005 | MCC: 0.023210 | Train loss: 1.0224 | Train acc: 50.11% | Val loss: 1.0012 | Val acc: 48.39% | LR: 0.000108
Epoch: 006 | MCC: 0.031653 | Train loss: 0.9971 | Train acc: 50.38% | Val loss: 1.0013 | Val acc: 48.88% | LR: 0.000108
Epoch: 007 | MCC: 0.034551 | Train loss: 0.9962 | Train acc: 50.48% | Val loss: 1.0009 | Val acc: 48.93% | LR: 0.000108
Epoch: 008 | MCC: 0.031278 | Train loss: 0.9959 | Train acc: 50.50% | Val loss: 1.0006 | Val acc: 49.05% | LR: 0.000108
Epoch: 009 | MCC: 0.035875 | Train loss: 0.9949 | Train acc: 50.49% | Val loss: 1.0002 | Val acc: 49.38% | LR: 0.000108
Epoch: 010 | MCC: 0.024194 | Train loss: 0.9954 | Train acc: 50.43% | Val loss: 0.9994 | Val acc: 49.32% | LR: 0.000107
Epoch: 011 | MCC: 0.024887 | Train loss: 0.9940 | Train acc: 50.56% | Val loss: 0.9990 | Val acc: 49.53% | LR: 0.000107
Epoch: 012 | MCC: 0.029802 | Train loss: 0.9945 | Train acc: 50.43% | Val loss: 0.9987 | Val acc: 50.11% | LR: 0.000107
Epoch: 013 | MCC: 0.040742 | Train loss: 0.9930 | Train acc: 50.60% | Val loss: 0.9981 | Val acc: 50.76% | LR: 0.000106
Epoch: 014 | MCC: 0.050024 | Train loss: 0.9927 | Train acc: 50.58% | Val loss: 0.9974 | Val acc: 51.84% | LR: 0.000106
Epoch: 015 | MCC: 0.053356 | Train loss: 0.9918 | Train acc: 50.59% | Val loss: 0.9964 | Val acc: 52.33% | LR: 0.000106
Epoch: 016 | MCC: 0.048119 | Train loss: 0.9919 | Train acc: 50.61% | Val loss: 0.9960 | Val acc: 52.16% | LR: 0.000105
Epoch: 017 | MCC: 0.054953 | Train loss: 0.9903 | Train acc: 50.70% | Val loss: 0.9961 | Val acc: 52.34% | LR: 0.000105
Epoch: 018 | MCC: 0.061234 | Train loss: 0.9925 | Train acc: 50.58% | Val loss: 0.9954 | Val acc: 53.07% | LR: 0.000104
Epoch: 019 | MCC: 0.061118 | Train loss: 0.9907 | Train acc: 50.75% | Val loss: 0.9945 | Val acc: 53.55% | LR: 0.000104
Epoch: 020 | MCC: 0.063287 | Train loss: 0.9919 | Train acc: 50.97% | Val loss: 0.9932 | Val acc: 54.53% | LR: 0.000104
Epoch: 021 | MCC: 0.060921 | Train loss: 0.9903 | Train acc: 50.96% | Val loss: 0.9929 | Val acc: 54.52% | LR: 0.000103
Epoch: 022 | MCC: 0.049697 | Train loss: 0.9895 | Train acc: 51.06% | Val loss: 0.9914 | Val acc: 54.70% | LR: 0.000103
Epoch: 023 | MCC: 0.055923 | Train loss: 0.9908 | Train acc: 50.99% | Val loss: 0.9908 | Val acc: 55.17% | LR: 0.000102
Epoch: 024 | MCC: 0.038227 | Train loss: 0.9920 | Train acc: 50.85% | Val loss: 0.9892 | Val acc: 55.14% | LR: 0.000101
Epoch: 025 | MCC: 0.031438 | Train loss: 0.9894 | Train acc: 51.17% | Val loss: 0.9879 | Val acc: 55.05% | LR: 0.000101
Epoch: 026 | MCC: 0.039248 | Train loss: 0.9891 | Train acc: 51.08% | Val loss: 0.9872 | Val acc: 55.34% | LR: 0.000100
Epoch: 027 | MCC: 0.037101 | Train loss: 0.9902 | Train acc: 50.88% | Val loss: 0.9850 | Val acc: 55.46% | LR: 0.000100
Epoch: 028 | MCC: 0.034478 | Train loss: 0.9886 | Train acc: 50.99% | Val loss: 0.9835 | Val acc: 55.46% | LR: 0.000099
Epoch: 029 | MCC: 0.032326 | Train loss: 0.9886 | Train acc: 50.86% | Val loss: 0.9815 | Val acc: 55.41% | LR: 0.000098
Epoch: 030 | MCC: 0.039688 | Train loss: 0.9886 | Train acc: 50.91% | Val loss: 0.9795 | Val acc: 55.53% | LR: 0.000098
Epoch: 031 | MCC: 0.044388 | Train loss: 0.9875 | Train acc: 50.97% | Val loss: 0.9784 | Val acc: 55.51% | LR: 0.000097
Epoch: 032 | MCC: 0.045383 | Train loss: 0.9875 | Train acc: 50.97% | Val loss: 0.9751 | Val acc: 55.39% | LR: 0.000096
Epoch: 033 | MCC: 0.041770 | Train loss: 0.9850 | Train acc: 50.98% | Val loss: 0.9730 | Val acc: 55.35% | LR: 0.000096
Epoch: 034 | MCC: 0.041687 | Train loss: 0.9870 | Train acc: 50.91% | Val loss: 0.9710 | Val acc: 55.33% | LR: 0.000095
Epoch: 035 | MCC: 0.036235 | Train loss: 0.9847 | Train acc: 51.12% | Val loss: 0.9694 | Val acc: 55.29% | LR: 0.000094
Epoch: 036 | MCC: 0.029384 | Train loss: 0.9843 | Train acc: 50.96% | Val loss: 0.9666 | Val acc: 55.33% | LR: 0.000093
Epoch: 037 | MCC: 0.025475 | Train loss: 0.9831 | Train acc: 51.06% | Val loss: 0.9645 | Val acc: 55.34% | LR: 0.000093
Epoch: 038 | MCC: 0.029922 | Train loss: 0.9826 | Train acc: 51.04% | Val loss: 0.9627 | Val acc: 55.73% | LR: 0.000092
Epoch: 039 | MCC: 0.031491 | Train loss: 0.9849 | Train acc: 50.86% | Val loss: 0.9592 | Val acc: 55.89% | LR: 0.000091
Epoch: 040 | MCC: 0.031417 | Train loss: 0.9853 | Train acc: 50.94% | Val loss: 0.9566 | Val acc: 56.05% | LR: 0.000090
Epoch: 041 | MCC: 0.030445 | Train loss: 0.9830 | Train acc: 50.92% | Val loss: 0.9543 | Val acc: 56.09% | LR: 0.000089
Epoch: 042 | MCC: 0.031586 | Train loss: 0.9822 | Train acc: 51.00% | Val loss: 0.9513 | Val acc: 56.25% | LR: 0.000088
Epoch: 043 | MCC: 0.032518 | Train loss: 0.9824 | Train acc: 50.96% | Val loss: 0.9488 | Val acc: 56.27% | LR: 0.000087
Epoch: 044 | MCC: 0.032405 | Train loss: 0.9829 | Train acc: 50.96% | Val loss: 0.9465 | Val acc: 56.27% | LR: 0.000086
Epoch: 045 | MCC: 0.023073 | Train loss: 0.9817 | Train acc: 50.99% | Val loss: 0.9439 | Val acc: 56.05% | LR: 0.000086
Epoch: 046 | MCC: 0.024241 | Train loss: 0.9825 | Train acc: 50.99% | Val loss: 0.9410 | Val acc: 56.03% | LR: 0.000085
Epoch: 047 | MCC: 0.024415 | Train loss: 0.9825 | Train acc: 51.05% | Val loss: 0.9395 | Val acc: 55.98% | LR: 0.000084
Epoch: 048 | MCC: 0.026272 | Train loss: 0.9802 | Train acc: 51.10% | Val loss: 0.9371 | Val acc: 55.95% | LR: 0.000083
Epoch: 049 | MCC: 0.023347 | Train loss: 0.9807 | Train acc: 51.05% | Val loss: 0.9346 | Val acc: 55.77% | LR: 0.000082
Epoch: 050 | MCC: 0.024508 | Train loss: 0.9811 | Train acc: 51.03% | Val loss: 0.9321 | Val acc: 55.82% | LR: 0.000081
Epoch: 051 | MCC: 0.022555 | Train loss: 0.9798 | Train acc: 51.07% | Val loss: 0.9309 | Val acc: 55.81% | LR: 0.000080
Epoch: 052 | MCC: 0.026265 | Train loss: 0.9841 | Train acc: 50.77% | Val loss: 0.9298 | Val acc: 56.00% | LR: 0.000079
Epoch: 053 | MCC: 0.029794 | Train loss: 0.9810 | Train acc: 50.96% | Val loss: 0.9290 | Val acc: 56.21% | LR: 0.000078
Epoch: 054 | MCC: 0.029250 | Train loss: 0.9824 | Train acc: 50.91% | Val loss: 0.9282 | Val acc: 56.14% | LR: 0.000077
Epoch: 055 | MCC: 0.034699 | Train loss: 0.9817 | Train acc: 50.90% | Val loss: 0.9261 | Val acc: 56.25% | LR: 0.000076
Epoch: 056 | MCC: 0.035643 | Train loss: 0.9816 | Train acc: 50.93% | Val loss: 0.9246 | Val acc: 56.27% | LR: 0.000075
Epoch: 057 | MCC: 0.028845 | Train loss: 0.9805 | Train acc: 50.99% | Val loss: 0.9309 | Val acc: 56.08% | LR: 0.000074
Epoch: 058 | MCC: 0.026430 | Train loss: 0.9803 | Train acc: 50.98% | Val loss: 0.9229 | Val acc: 56.03% | LR: 0.000073
Epoch: 059 | MCC: 0.032369 | Train loss: 0.9808 | Train acc: 50.93% | Val loss: 0.9215 | Val acc: 56.26% | LR: 0.000071
Epoch: 060 | MCC: 0.028905 | Train loss: 0.9811 | Train acc: 50.95% | Val loss: 0.9225 | Val acc: 56.19% | LR: 0.000070
Epoch: 061 | MCC: 0.031910 | Train loss: 0.9809 | Train acc: 50.95% | Val loss: 0.9192 | Val acc: 56.33% | LR: 0.000069
Epoch: 062 | MCC: 0.029936 | Train loss: 0.9828 | Train acc: 50.82% | Val loss: 0.9181 | Val acc: 56.28% | LR: 0.000068
Epoch: 063 | MCC: 0.031784 | Train loss: 0.9823 | Train acc: 50.90% | Val loss: 0.9194 | Val acc: 56.40% | LR: 0.000067
Epoch: 064 | MCC: 0.035811 | Train loss: 0.9803 | Train acc: 50.97% | Val loss: 0.9185 | Val acc: 56.44% | LR: 0.000066
Epoch: 065 | MCC: 0.032899 | Train loss: 0.9805 | Train acc: 50.96% | Val loss: 0.9234 | Val acc: 56.52% | LR: 0.000065
Epoch: 066 | MCC: 0.036307 | Train loss: 0.9810 | Train acc: 50.96% | Val loss: 0.9159 | Val acc: 56.47% | LR: 0.000064
Epoch: 067 | MCC: 0.035629 | Train loss: 0.9809 | Train acc: 50.90% | Val loss: 0.9141 | Val acc: 56.54% | LR: 0.000063
Epoch: 068 | MCC: 0.039371 | Train loss: 0.9809 | Train acc: 50.93% | Val loss: 0.9201 | Val acc: 56.70% | LR: 0.000062
Epoch: 069 | MCC: 0.040733 | Train loss: 0.9786 | Train acc: 51.05% | Val loss: 0.9117 | Val acc: 56.77% | LR: 0.000060
Epoch: 070 | MCC: 0.036203 | Train loss: 0.9813 | Train acc: 50.86% | Val loss: 0.9125 | Val acc: 56.60% | LR: 0.000059
Epoch: 071 | MCC: 0.044552 | Train loss: 0.9812 | Train acc: 50.86% | Val loss: 0.9096 | Val acc: 56.78% | LR: 0.000058
Epoch: 072 | MCC: 0.037572 | Train loss: 0.9813 | Train acc: 50.88% | Val loss: 0.9236 | Val acc: 56.73% | LR: 0.000057
Epoch: 073 | MCC: 0.033416 | Train loss: 0.9802 | Train acc: 51.02% | Val loss: 0.9309 | Val acc: 56.40% | LR: 0.000056
Epoch: 074 | MCC: 0.032050 | Train loss: 0.9814 | Train acc: 50.94% | Val loss: 0.9068 | Val acc: 56.41% | LR: 0.000055
Epoch: 075 | MCC: 0.023429 | Train loss: 0.9818 | Train acc: 50.87% | Val loss: 0.9050 | Val acc: 56.29% | LR: 0.000054
Epoch: 076 | MCC: 0.028123 | Train loss: 0.9808 | Train acc: 50.88% | Val loss: 0.9034 | Val acc: 56.44% | LR: 0.000053
Epoch: 077 | MCC: 0.026985 | Train loss: 0.9814 | Train acc: 50.91% | Val loss: 0.9025 | Val acc: 56.45% | LR: 0.000051
Epoch: 078 | MCC: 0.029677 | Train loss: 0.9796 | Train acc: 50.94% | Val loss: 0.9017 | Val acc: 56.58% | LR: 0.000050
Epoch: 079 | MCC: 0.030172 | Train loss: 0.9788 | Train acc: 51.02% | Val loss: 0.9012 | Val acc: 56.58% | LR: 0.000049
Epoch: 080 | MCC: 0.029019 | Train loss: 0.9808 | Train acc: 50.91% | Val loss: 0.9034 | Val acc: 56.52% | LR: 0.000048
Epoch: 081 | MCC: 0.034540 | Train loss: 0.9799 | Train acc: 50.98% | Val loss: 0.9014 | Val acc: 56.79% | LR: 0.000047
Epoch: 082 | MCC: 0.034271 | Train loss: 0.9801 | Train acc: 50.98% | Val loss: 0.9002 | Val acc: 56.79% | LR: 0.000046
Epoch: 083 | MCC: 0.032366 | Train loss: 0.9791 | Train acc: 51.00% | Val loss: 0.8993 | Val acc: 56.67% | LR: 0.000045
Epoch: 084 | MCC: 0.032081 | Train loss: 0.9812 | Train acc: 50.91% | Val loss: 0.8989 | Val acc: 56.70% | LR: 0.000044
Epoch: 085 | MCC: 0.032826 | Train loss: 0.9799 | Train acc: 51.03% | Val loss: 0.8979 | Val acc: 56.64% | LR: 0.000043
Epoch: 086 | MCC: 0.031167 | Train loss: 0.9812 | Train acc: 50.88% | Val loss: 0.8971 | Val acc: 56.56% | LR: 0.000041
Epoch: 087 | MCC: 0.025447 | Train loss: 0.9784 | Train acc: 51.06% | Val loss: 0.9012 | Val acc: 56.42% | LR: 0.000040
Epoch: 088 | MCC: 0.027661 | Train loss: 0.9796 | Train acc: 51.00% | Val loss: 0.8970 | Val acc: 56.59% | LR: 0.000039
Epoch: 089 | MCC: 0.031279 | Train loss: 0.9798 | Train acc: 50.97% | Val loss: 0.8962 | Val acc: 56.71% | LR: 0.000038
Epoch: 090 | MCC: 0.031335 | Train loss: 0.9809 | Train acc: 50.93% | Val loss: 0.8953 | Val acc: 56.77% | LR: 0.000037
Epoch: 091 | MCC: 0.033221 | Train loss: 0.9804 | Train acc: 51.02% | Val loss: 0.8945 | Val acc: 56.90% | LR: 0.000036
Epoch: 092 | MCC: 0.037123 | Train loss: 0.9799 | Train acc: 51.00% | Val loss: 0.8940 | Val acc: 57.13% | LR: 0.000035
Epoch: 093 | MCC: 0.044410 | Train loss: 0.9810 | Train acc: 50.96% | Val loss: 0.8936 | Val acc: 57.45% | LR: 0.000034
Epoch: 094 | MCC: 0.044337 | Train loss: 0.9784 | Train acc: 51.14% | Val loss: 0.8932 | Val acc: 57.42% | LR: 0.000033
Epoch: 095 | MCC: 0.048603 | Train loss: 0.9778 | Train acc: 51.17% | Val loss: 0.8928 | Val acc: 57.64% | LR: 0.000032
Epoch: 096 | MCC: 0.044305 | Train loss: 0.9807 | Train acc: 50.91% | Val loss: 0.8921 | Val acc: 57.68% | LR: 0.000031
Epoch: 097 | MCC: 0.041586 | Train loss: 0.9800 | Train acc: 51.01% | Val loss: 0.9890 | Val acc: 57.61% | LR: 0.000030
Epoch: 098 | MCC: 0.031106 | Train loss: 0.9806 | Train acc: 50.95% | Val loss: 0.8934 | Val acc: 57.74% | LR: 0.000029
Epoch: 099 | MCC: 0.042131 | Train loss: 0.9817 | Train acc: 50.84% | Val loss: 0.8928 | Val acc: 58.04% | LR: 0.000028
Epoch: 100 | MCC: 0.057262 | Train loss: 0.9783 | Train acc: 51.12% | Val loss: 0.8961 | Val acc: 58.54% | LR: 0.000027
Epoch: 101 | MCC: 0.052616 | Train loss: 0.9777 | Train acc: 51.12% | Val loss: 0.8894 | Val acc: 58.27% | LR: 0.000026
Epoch: 102 | MCC: 0.048593 | Train loss: 0.9785 | Train acc: 51.12% | Val loss: 0.8938 | Val acc: 58.15% | LR: 0.000025
Epoch: 103 | MCC: 0.050129 | Train loss: 0.9793 | Train acc: 51.00% | Val loss: 0.8899 | Val acc: 58.15% | LR: 0.000024
Epoch: 104 | MCC: 0.057472 | Train loss: 0.9805 | Train acc: 50.88% | Val loss: 0.8891 | Val acc: 58.18% | LR: 0.000023
Epoch: 105 | MCC: 0.049453 | Train loss: 0.9795 | Train acc: 51.03% | Val loss: 0.8889 | Val acc: 58.20% | LR: 0.000022
Epoch: 106 | MCC: 0.039579 | Train loss: 0.9798 | Train acc: 50.98% | Val loss: 0.8897 | Val acc: 58.04% | LR: 0.000021
Epoch: 107 | MCC: 0.045526 | Train loss: 0.9778 | Train acc: 51.12% | Val loss: 0.8892 | Val acc: 58.10% | LR: 0.000021
Epoch: 108 | MCC: 0.045526 | Train loss: 0.9777 | Train acc: 51.08% | Val loss: 0.8884 | Val acc: 58.10% | LR: 0.000020
Epoch: 109 | MCC: 0.046909 | Train loss: 0.9797 | Train acc: 50.94% | Val loss: 0.8898 | Val acc: 58.04% | LR: 0.000019
Epoch: 110 | MCC: 0.047161 | Train loss: 0.9788 | Train acc: 51.03% | Val loss: 0.8877 | Val acc: 58.13% | LR: 0.000018
Epoch: 111 | MCC: 0.046582 | Train loss: 0.9790 | Train acc: 51.10% | Val loss: 0.8876 | Val acc: 58.05% | LR: 0.000017
Epoch: 112 | MCC: 0.046582 | Train loss: 0.9790 | Train acc: 51.02% | Val loss: 0.8874 | Val acc: 58.05% | LR: 0.000016
Epoch: 113 | MCC: 0.047069 | Train loss: 0.9789 | Train acc: 51.06% | Val loss: 0.8909 | Val acc: 58.10% | LR: 0.000016
Epoch: 114 | MCC: 0.047069 | Train loss: 0.9798 | Train acc: 50.94% | Val loss: 0.8875 | Val acc: 58.10% | LR: 0.000015
Epoch: 115 | MCC: 0.047607 | Train loss: 0.9784 | Train acc: 51.04% | Val loss: 0.8869 | Val acc: 58.10% | LR: 0.000014
Epoch: 116 | MCC: 0.047365 | Train loss: 0.9784 | Train acc: 51.08% | Val loss: 0.8867 | Val acc: 58.05% | LR: 0.000013
Epoch: 117 | MCC: 0.048477 | Train loss: 0.9792 | Train acc: 50.99% | Val loss: 0.8864 | Val acc: 58.05% | LR: 0.000013
Epoch: 118 | MCC: 0.046971 | Train loss: 0.9779 | Train acc: 51.08% | Val loss: 0.8865 | Val acc: 58.03% | LR: 0.000012
Epoch: 119 | MCC: 0.048221 | Train loss: 0.9777 | Train acc: 51.12% | Val loss: 0.8863 | Val acc: 58.10% | LR: 0.000011
Epoch: 120 | MCC: 0.049727 | Train loss: 0.9787 | Train acc: 51.07% | Val loss: 0.8862 | Val acc: 58.13% | LR: 0.000011
Epoch: 121 | MCC: 0.049265 | Train loss: 0.9784 | Train acc: 51.11% | Val loss: 0.8882 | Val acc: 58.10% | LR: 0.000010
Epoch: 122 | MCC: 0.058970 | Train loss: 0.9797 | Train acc: 50.98% | Val loss: 0.8837 | Val acc: 58.11% | LR: 0.000009
Epoch: 123 | MCC: 0.048568 | Train loss: 0.9790 | Train acc: 51.02% | Val loss: 0.8880 | Val acc: 58.01% | LR: 0.000009
Epoch: 124 | MCC: 0.060991 | Train loss: 0.9799 | Train acc: 50.97% | Val loss: 0.8832 | Val acc: 58.17% | LR: 0.000008
Epoch: 125 | MCC: 0.061387 | Train loss: 0.9800 | Train acc: 50.99% | Val loss: 0.8831 | Val acc: 58.22% | LR: 0.000008
Epoch: 126 | MCC: 0.062240 | Train loss: 0.9788 | Train acc: 51.11% | Val loss: 0.8831 | Val acc: 58.25% | LR: 0.000007
Epoch: 127 | MCC: 0.061779 | Train loss: 0.9788 | Train acc: 51.12% | Val loss: 0.8874 | Val acc: 58.22% | LR: 0.000007
Epoch: 128 | MCC: 0.059918 | Train loss: 0.9801 | Train acc: 51.01% | Val loss: 0.8853 | Val acc: 58.11% | LR: 0.000006
Epoch: 129 | MCC: 0.059918 | Train loss: 0.9795 | Train acc: 51.02% | Val loss: 0.8884 | Val acc: 58.11% | LR: 0.000006
Epoch: 130 | MCC: 0.060991 | Train loss: 0.9795 | Train acc: 51.05% | Val loss: 0.8829 | Val acc: 58.17% | LR: 0.000005
Epoch: 131 | MCC: 0.060991 | Train loss: 0.9782 | Train acc: 51.13% | Val loss: 0.8829 | Val acc: 58.17% | LR: 0.000005
Epoch: 132 | MCC: 0.060991 | Train loss: 0.9783 | Train acc: 51.10% | Val loss: 0.8829 | Val acc: 58.17% | LR: 0.000004
Epoch: 133 | MCC: 0.060991 | Train loss: 0.9793 | Train acc: 51.05% | Val loss: 0.8829 | Val acc: 58.17% | LR: 0.000004
Epoch: 134 | MCC: 0.060991 | Train loss: 0.9782 | Train acc: 51.10% | Val loss: 0.8829 | Val acc: 58.17% | LR: 0.000004
Epoch: 135 | MCC: 0.060991 | Train loss: 0.9782 | Train acc: 51.15% | Val loss: 0.8831 | Val acc: 58.17% | LR: 0.000003
Epoch: 136 | MCC: 0.060991 | Train loss: 0.9772 | Train acc: 51.19% | Val loss: 0.8837 | Val acc: 58.17% | LR: 0.000003
Epoch: 137 | MCC: 0.059484 | Train loss: 0.9776 | Train acc: 51.14% | Val loss: 0.8856 | Val acc: 58.15% | LR: 0.000003
Epoch: 138 | MCC: 0.059484 | Train loss: 0.9776 | Train acc: 51.18% | Val loss: 0.8840 | Val acc: 58.15% | LR: 0.000002
Epoch: 139 | MCC: 0.060591 | Train loss: 0.9788 | Train acc: 51.07% | Val loss: 1.4513 | Val acc: 58.21% | LR: 0.000002
Epoch: 140 | MCC: 0.059484 | Train loss: 0.9787 | Train acc: 51.05% | Val loss: 0.8910 | Val acc: 58.15% | LR: 0.000002
Epoch: 141 | MCC: 0.060591 | Train loss: 0.9786 | Train acc: 51.10% | Val loss: 0.8843 | Val acc: 58.21% | LR: 0.000002
Epoch: 142 | MCC: 0.059484 | Train loss: 0.9784 | Train acc: 51.08% | Val loss: 0.9214 | Val acc: 58.15% | LR: 0.000002
Epoch: 143 | MCC: 0.059484 | Train loss: 0.9784 | Train acc: 51.11% | Val loss: 0.8883 | Val acc: 58.15% | LR: 0.000001
Epoch: 144 | MCC: 0.059484 | Train loss: 0.9783 | Train acc: 51.12% | Val loss: 0.8846 | Val acc: 58.15% | LR: 0.000001
Epoch: 145 | MCC: 0.057849 | Train loss: 0.9798 | Train acc: 51.02% | Val loss: 0.8841 | Val acc: 58.12% | LR: 0.000001
Epoch: 146 | MCC: 0.057849 | Train loss: 0.9789 | Train acc: 51.08% | Val loss: 0.8841 | Val acc: 58.12% | LR: 0.000001
Epoch: 147 | MCC: 0.059484 | Train loss: 0.9777 | Train acc: 51.18% | Val loss: 0.8848 | Val acc: 58.15% | LR: 0.000001
Epoch: 148 | MCC: 0.059484 | Train loss: 0.9778 | Train acc: 51.12% | Val loss: 0.8849 | Val acc: 58.15% | LR: 0.000001
Epoch: 149 | MCC: 0.059484 | Train loss: 0.9786 | Train acc: 51.04% | Val loss: 0.8844 | Val acc: 58.15% | LR: 0.000001

[I 2025-10-05 09:08:21,622] Trial 15 finished with value: 0.059484380297362804 and parameters: {'lr': 0.00010869232436634049, 'hidden_size': 79, 'dropout': 0.3067058747224604, 'weight_decay': 0.021104198105615157}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.011691 | Train loss: 0.9995 | Train acc: 50.27% | Val loss: 1.0021 | Val acc: 47.88% | LR: 0.000102
Epoch: 001 | MCC: 0.018956 | Train loss: 0.9988 | Train acc: 50.27% | Val loss: 1.0019 | Val acc: 48.16% | LR: 0.000102
Epoch: 002 | MCC: 0.022678 | Train loss: 0.9975 | Train acc: 50.45% | Val loss: 1.0014 | Val acc: 48.31% | LR: 0.000102
Epoch: 003 | MCC: 0.028238 | Train loss: 0.9972 | Train acc: 50.30% | Val loss: 1.0007 | Val acc: 48.74% | LR: 0.000102
Epoch: 004 | MCC: 0.038667 | Train loss: 0.9965 | Train acc: 50.39% | Val loss: 0.9998 | Val acc: 49.69% | LR: 0.000102
Epoch: 005 | MCC: 0.039007 | Train loss: 1.0163 | Train acc: 50.21% | Val loss: 0.9990 | Val acc: 50.04% | LR: 0.000102
Epoch: 006 | MCC: 0.029700 | Train loss: 0.9963 | Train acc: 50.37% | Val loss: 0.9986 | Val acc: 49.70% | LR: 0.000102
Epoch: 007 | MCC: 0.031164 | Train loss: 0.9956 | Train acc: 50.55% | Val loss: 0.9979 | Val acc: 50.11% | LR: 0.000102
Epoch: 008 | MCC: 0.039241 | Train loss: 0.9951 | Train acc: 50.57% | Val loss: 0.9970 | Val acc: 51.16% | LR: 0.000102
Epoch: 009 | MCC: 0.041902 | Train loss: 0.9937 | Train acc: 50.61% | Val loss: 0.9958 | Val acc: 51.72% | LR: 0.000101
Epoch: 010 | MCC: 0.032097 | Train loss: 0.9949 | Train acc: 50.84% | Val loss: 0.9938 | Val acc: 52.08% | LR: 0.000101
Epoch: 011 | MCC: 0.039131 | Train loss: 0.9934 | Train acc: 50.57% | Val loss: 0.9926 | Val acc: 53.09% | LR: 0.000101
Epoch: 012 | MCC: 0.040985 | Train loss: 0.9932 | Train acc: 50.83% | Val loss: 0.9915 | Val acc: 53.44% | LR: 0.000101
Epoch: 013 | MCC: 0.028404 | Train loss: 0.9922 | Train acc: 51.03% | Val loss: 0.9895 | Val acc: 54.05% | LR: 0.000100
Epoch: 014 | MCC: 0.034519 | Train loss: 0.9929 | Train acc: 50.90% | Val loss: 0.9892 | Val acc: 54.68% | LR: 0.000100
Epoch: 015 | MCC: 0.038546 | Train loss: 0.9910 | Train acc: 50.94% | Val loss: 0.9879 | Val acc: 55.11% | LR: 0.000100
Epoch: 016 | MCC: 0.034764 | Train loss: 0.9916 | Train acc: 50.85% | Val loss: 0.9825 | Val acc: 55.01% | LR: 0.000099
Epoch: 017 | MCC: 0.035155 | Train loss: 0.9893 | Train acc: 50.87% | Val loss: 0.9830 | Val acc: 55.11% | LR: 0.000099
Epoch: 018 | MCC: 0.031474 | Train loss: 0.9905 | Train acc: 50.79% | Val loss: 0.9803 | Val acc: 55.22% | LR: 0.000098
Epoch: 019 | MCC: 0.030386 | Train loss: 0.9899 | Train acc: 50.93% | Val loss: 0.9745 | Val acc: 55.17% | LR: 0.000098
Epoch: 020 | MCC: 0.024068 | Train loss: 0.9892 | Train acc: 50.88% | Val loss: 0.9707 | Val acc: 55.04% | LR: 0.000098
Epoch: 021 | MCC: 0.034120 | Train loss: 0.9851 | Train acc: 50.99% | Val loss: 0.9675 | Val acc: 55.39% | LR: 0.000097
Epoch: 022 | MCC: 0.032967 | Train loss: 0.9831 | Train acc: 50.91% | Val loss: 0.9625 | Val acc: 55.52% | LR: 0.000097
Epoch: 023 | MCC: 0.029080 | Train loss: 0.9849 | Train acc: 50.91% | Val loss: 0.9578 | Val acc: 55.39% | LR: 0.000096
Epoch: 024 | MCC: 0.028599 | Train loss: 0.9856 | Train acc: 50.85% | Val loss: 0.9525 | Val acc: 55.60% | LR: 0.000096
Epoch: 025 | MCC: 0.031016 | Train loss: 0.9830 | Train acc: 51.05% | Val loss: 0.9484 | Val acc: 55.77% | LR: 0.000095
Epoch: 026 | MCC: 0.029650 | Train loss: 0.9820 | Train acc: 51.05% | Val loss: 0.9459 | Val acc: 55.75% | LR: 0.000095
Epoch: 027 | MCC: 0.028481 | Train loss: 0.9851 | Train acc: 50.87% | Val loss: 0.9418 | Val acc: 55.67% | LR: 0.000094
Epoch: 028 | MCC: 0.030343 | Train loss: 1.0942 | Train acc: 50.85% | Val loss: 0.9400 | Val acc: 55.66% | LR: 0.000093
Epoch: 029 | MCC: 0.028576 | Train loss: 1.0014 | Train acc: 50.80% | Val loss: 0.9570 | Val acc: 55.13% | LR: 0.000093
Epoch: 030 | MCC: 0.033710 | Train loss: 0.9897 | Train acc: 50.92% | Val loss: 0.9390 | Val acc: 55.30% | LR: 0.000092
Epoch: 031 | MCC: 0.029575 | Train loss: 0.9881 | Train acc: 50.88% | Val loss: 0.9342 | Val acc: 55.49% | LR: 0.000091
Epoch: 032 | MCC: 0.031671 | Train loss: 0.9896 | Train acc: 50.86% | Val loss: 0.9340 | Val acc: 55.50% | LR: 0.000091
Epoch: 033 | MCC: 0.023979 | Train loss: 0.9909 | Train acc: 50.84% | Val loss: 0.9353 | Val acc: 55.32% | LR: 0.000090
Epoch: 034 | MCC: 0.020177 | Train loss: 0.9877 | Train acc: 50.83% | Val loss: 1.0023 | Val acc: 55.15% | LR: 0.000089
Epoch: 035 | MCC: 0.028771 | Train loss: 0.9865 | Train acc: 50.98% | Val loss: 0.9357 | Val acc: 55.40% | LR: 0.000089
Epoch: 036 | MCC: 0.025757 | Train loss: 1.0021 | Train acc: 50.97% | Val loss: 0.9278 | Val acc: 55.50% | LR: 0.000088
Epoch: 037 | MCC: 0.020098 | Train loss: 0.9873 | Train acc: 50.98% | Val loss: 0.9315 | Val acc: 55.41% | LR: 0.000087
Epoch: 038 | MCC: 0.028535 | Train loss: 0.9831 | Train acc: 51.01% | Val loss: 0.9286 | Val acc: 55.51% | LR: 0.000086
Epoch: 039 | MCC: 0.028322 | Train loss: 0.9880 | Train acc: 50.85% | Val loss: 0.9407 | Val acc: 55.75% | LR: 0.000086
Epoch: 040 | MCC: 0.024188 | Train loss: 0.9830 | Train acc: 50.96% | Val loss: 0.9278 | Val acc: 55.74% | LR: 0.000085
Epoch: 041 | MCC: 0.032382 | Train loss: 0.9827 | Train acc: 50.90% | Val loss: 0.9276 | Val acc: 55.86% | LR: 0.000084
Epoch: 042 | MCC: 0.029076 | Train loss: 0.9833 | Train acc: 50.94% | Val loss: 0.9291 | Val acc: 55.73% | LR: 0.000083
Epoch: 043 | MCC: 0.027048 | Train loss: 0.9823 | Train acc: 50.94% | Val loss: 0.9317 | Val acc: 55.83% | LR: 0.000082
Epoch: 044 | MCC: 0.031972 | Train loss: 0.9834 | Train acc: 50.96% | Val loss: 0.9270 | Val acc: 55.78% | LR: 0.000082
Epoch: 045 | MCC: 0.035996 | Train loss: 0.9825 | Train acc: 50.93% | Val loss: 0.9239 | Val acc: 56.00% | LR: 0.000081
Epoch: 046 | MCC: 0.034307 | Train loss: 0.9827 | Train acc: 50.96% | Val loss: 0.9273 | Val acc: 56.02% | LR: 0.000080
Epoch: 047 | MCC: 0.035132 | Train loss: 0.9821 | Train acc: 50.98% | Val loss: 0.9181 | Val acc: 56.16% | LR: 0.000079
Epoch: 048 | MCC: 0.033952 | Train loss: 0.9810 | Train acc: 51.08% | Val loss: 0.9601 | Val acc: 55.79% | LR: 0.000078
Epoch: 049 | MCC: 0.033336 | Train loss: 0.9807 | Train acc: 51.08% | Val loss: 0.9533 | Val acc: 55.82% | LR: 0.000077
Epoch: 050 | MCC: 0.046578 | Train loss: 0.9833 | Train acc: 51.01% | Val loss: 0.9206 | Val acc: 56.26% | LR: 0.000076
Epoch: 051 | MCC: 0.039402 | Train loss: 0.9804 | Train acc: 51.06% | Val loss: 0.9456 | Val acc: 56.14% | LR: 0.000075
Epoch: 052 | MCC: 0.039870 | Train loss: 0.9857 | Train acc: 50.71% | Val loss: 0.9282 | Val acc: 55.99% | LR: 0.000074
Epoch: 053 | MCC: 0.036228 | Train loss: 0.9824 | Train acc: 50.93% | Val loss: 0.9333 | Val acc: 56.10% | LR: 0.000073
Epoch: 054 | MCC: 0.034782 | Train loss: 0.9835 | Train acc: 50.88% | Val loss: 0.9596 | Val acc: 56.28% | LR: 0.000072
Epoch: 055 | MCC: 0.029140 | Train loss: 0.9840 | Train acc: 50.84% | Val loss: 0.9271 | Val acc: 56.05% | LR: 0.000071
Epoch: 056 | MCC: 0.030149 | Train loss: 0.9847 | Train acc: 50.88% | Val loss: 0.9176 | Val acc: 56.21% | LR: 0.000070
Epoch: 057 | MCC: 0.035607 | Train loss: 0.9842 | Train acc: 50.93% | Val loss: 0.9194 | Val acc: 56.24% | LR: 0.000069
Epoch: 058 | MCC: 0.028442 | Train loss: 0.9829 | Train acc: 50.91% | Val loss: 0.9198 | Val acc: 56.12% | LR: 0.000068
Epoch: 059 | MCC: 0.030230 | Train loss: 0.9822 | Train acc: 50.85% | Val loss: 0.9176 | Val acc: 56.28% | LR: 0.000067
Epoch: 060 | MCC: 0.028268 | Train loss: 0.9829 | Train acc: 50.90% | Val loss: 0.9171 | Val acc: 56.05% | LR: 0.000066
Epoch: 061 | MCC: 0.031179 | Train loss: 0.9827 | Train acc: 50.90% | Val loss: 0.9161 | Val acc: 56.19% | LR: 0.000065
Epoch: 062 | MCC: 0.028539 | Train loss: 0.9843 | Train acc: 50.79% | Val loss: 0.9205 | Val acc: 56.19% | LR: 0.000064
Epoch: 063 | MCC: 0.031971 | Train loss: 0.9849 | Train acc: 50.84% | Val loss: 0.9141 | Val acc: 56.33% | LR: 0.000063
Epoch: 064 | MCC: 0.032433 | Train loss: 0.9829 | Train acc: 50.94% | Val loss: 0.9127 | Val acc: 56.37% | LR: 0.000062
Epoch: 065 | MCC: 0.040107 | Train loss: 0.9817 | Train acc: 50.95% | Val loss: 0.9130 | Val acc: 56.36% | LR: 0.000061
Epoch: 066 | MCC: 0.032492 | Train loss: 0.9853 | Train acc: 50.92% | Val loss: 0.9141 | Val acc: 56.14% | LR: 0.000060
Epoch: 067 | MCC: 0.033553 | Train loss: 0.9836 | Train acc: 50.87% | Val loss: 0.9121 | Val acc: 56.12% | LR: 0.000059
Epoch: 068 | MCC: 0.033059 | Train loss: 0.9827 | Train acc: 50.92% | Val loss: 0.9160 | Val acc: 56.09% | LR: 0.000058
Epoch: 069 | MCC: 0.026246 | Train loss: 0.9819 | Train acc: 51.06% | Val loss: 0.9159 | Val acc: 55.83% | LR: 0.000057
Epoch: 070 | MCC: 0.033243 | Train loss: 0.9860 | Train acc: 50.83% | Val loss: 0.9156 | Val acc: 55.91% | LR: 0.000056
Epoch: 071 | MCC: 0.034204 | Train loss: 0.9832 | Train acc: 50.85% | Val loss: 0.9209 | Val acc: 55.91% | LR: 0.000055
Epoch: 072 | MCC: 0.032574 | Train loss: 0.9833 | Train acc: 50.85% | Val loss: 0.9210 | Val acc: 55.85% | LR: 0.000054
Epoch: 073 | MCC: 0.034932 | Train loss: 0.9809 | Train acc: 50.99% | Val loss: 0.9155 | Val acc: 55.93% | LR: 0.000053
Epoch: 074 | MCC: 0.035950 | Train loss: 0.9828 | Train acc: 50.89% | Val loss: 0.9140 | Val acc: 56.02% | LR: 0.000052
Epoch: 075 | MCC: 0.034727 | Train loss: 0.9828 | Train acc: 50.83% | Val loss: 0.9155 | Val acc: 55.98% | LR: 0.000051
Epoch: 076 | MCC: 0.033653 | Train loss: 0.9886 | Train acc: 50.84% | Val loss: 0.9233 | Val acc: 55.90% | LR: 0.000050
Epoch: 077 | MCC: 0.039775 | Train loss: 0.9828 | Train acc: 50.87% | Val loss: 0.9155 | Val acc: 56.08% | LR: 0.000049
Epoch: 078 | MCC: 0.044751 | Train loss: 0.9819 | Train acc: 50.92% | Val loss: 0.9123 | Val acc: 56.32% | LR: 0.000047
Epoch: 079 | MCC: 0.041217 | Train loss: 0.9814 | Train acc: 50.96% | Val loss: 0.9139 | Val acc: 56.13% | LR: 0.000046
Epoch: 080 | MCC: 0.038967 | Train loss: 0.9838 | Train acc: 50.83% | Val loss: 0.9156 | Val acc: 55.96% | LR: 0.000045
Epoch: 081 | MCC: 0.036578 | Train loss: 0.9815 | Train acc: 50.93% | Val loss: 0.9178 | Val acc: 56.03% | LR: 0.000044
Epoch: 082 | MCC: 0.042891 | Train loss: 0.9823 | Train acc: 50.90% | Val loss: 0.9116 | Val acc: 56.17% | LR: 0.000043
Epoch: 083 | MCC: 0.034698 | Train loss: 0.9822 | Train acc: 50.93% | Val loss: 0.9205 | Val acc: 55.93% | LR: 0.000042
Epoch: 084 | MCC: 0.028242 | Train loss: 0.9839 | Train acc: 50.85% | Val loss: 0.9285 | Val acc: 55.56% | LR: 0.000041
Epoch: 085 | MCC: 0.035252 | Train loss: 0.9820 | Train acc: 51.00% | Val loss: 0.9181 | Val acc: 56.10% | LR: 0.000040
Epoch: 086 | MCC: 0.034850 | Train loss: 0.9841 | Train acc: 50.79% | Val loss: 0.9142 | Val acc: 56.12% | LR: 0.000039
Epoch: 087 | MCC: 0.031598 | Train loss: 0.9808 | Train acc: 50.98% | Val loss: 0.9161 | Val acc: 55.99% | LR: 0.000038
Epoch: 088 | MCC: 0.035931 | Train loss: 0.9821 | Train acc: 50.91% | Val loss: 0.9168 | Val acc: 56.06% | LR: 0.000037
Epoch: 089 | MCC: 0.037654 | Train loss: 0.9826 | Train acc: 50.84% | Val loss: 0.9123 | Val acc: 56.17% | LR: 0.000036
Epoch: 090 | MCC: 0.035422 | Train loss: 0.9832 | Train acc: 50.77% | Val loss: 0.9160 | Val acc: 56.07% | LR: 0.000035
Epoch: 091 | MCC: 0.037369 | Train loss: 1.0120 | Train acc: 50.90% | Val loss: 0.9127 | Val acc: 56.23% | LR: 0.000034
Epoch: 092 | MCC: 0.033334 | Train loss: 0.9824 | Train acc: 50.87% | Val loss: 0.9270 | Val acc: 56.01% | LR: 0.000033
Epoch: 093 | MCC: 0.034856 | Train loss: 0.9834 | Train acc: 50.81% | Val loss: 0.9144 | Val acc: 56.02% | LR: 0.000032
Epoch: 094 | MCC: 0.037636 | Train loss: 0.9812 | Train acc: 50.96% | Val loss: 0.9118 | Val acc: 56.17% | LR: 0.000031
Epoch: 095 | MCC: 0.037668 | Train loss: 0.9805 | Train acc: 51.03% | Val loss: 0.9118 | Val acc: 56.20% | LR: 0.000030
Epoch: 096 | MCC: 0.037205 | Train loss: 0.9833 | Train acc: 50.75% | Val loss: 0.9130 | Val acc: 56.18% | LR: 0.000029
Epoch: 097 | MCC: 0.034465 | Train loss: 0.9823 | Train acc: 50.88% | Val loss: 0.9132 | Val acc: 56.09% | LR: 0.000028
Epoch: 098 | MCC: 0.033910 | Train loss: 0.9850 | Train acc: 50.76% | Val loss: 0.9124 | Val acc: 56.04% | LR: 0.000027
Epoch: 099 | MCC: 0.035028 | Train loss: 0.9846 | Train acc: 50.72% | Val loss: 0.9121 | Val acc: 56.12% | LR: 0.000026
Epoch: 100 | MCC: 0.034104 | Train loss: 0.9823 | Train acc: 50.95% | Val loss: 0.9125 | Val acc: 56.06% | LR: 0.000025
Epoch: 101 | MCC: 0.035740 | Train loss: 0.9806 | Train acc: 50.96% | Val loss: 0.9128 | Val acc: 56.14% | LR: 0.000025
Epoch: 102 | MCC: 0.038199 | Train loss: 0.9813 | Train acc: 50.99% | Val loss: 0.9093 | Val acc: 56.31% | LR: 0.000024
Epoch: 103 | MCC: 0.037276 | Train loss: 0.9822 | Train acc: 50.82% | Val loss: 0.9110 | Val acc: 56.21% | LR: 0.000023
Epoch: 104 | MCC: 0.034117 | Train loss: 0.9844 | Train acc: 50.69% | Val loss: 0.9147 | Val acc: 56.08% | LR: 0.000022
Epoch: 105 | MCC: 0.033629 | Train loss: 0.9826 | Train acc: 50.87% | Val loss: 0.9132 | Val acc: 56.10% | LR: 0.000021
Epoch: 106 | MCC: 0.035929 | Train loss: 0.9819 | Train acc: 50.80% | Val loss: 0.9106 | Val acc: 56.20% | LR: 0.000020
Epoch: 107 | MCC: 0.034990 | Train loss: 0.9805 | Train acc: 50.97% | Val loss: 0.9711 | Val acc: 56.15% | LR: 0.000019
Epoch: 108 | MCC: 0.028167 | Train loss: 0.9799 | Train acc: 50.91% | Val loss: 0.9174 | Val acc: 55.91% | LR: 0.000019
Epoch: 109 | MCC: 0.028477 | Train loss: 0.9817 | Train acc: 50.81% | Val loss: 0.9149 | Val acc: 55.88% | LR: 0.000018
Epoch: 110 | MCC: 0.032517 | Train loss: 0.9819 | Train acc: 50.91% | Val loss: 0.9129 | Val acc: 56.19% | LR: 0.000017
Epoch: 111 | MCC: 0.031056 | Train loss: 0.9841 | Train acc: 50.91% | Val loss: 0.9118 | Val acc: 56.09% | LR: 0.000016
Epoch: 112 | MCC: 0.031040 | Train loss: 0.9818 | Train acc: 50.83% | Val loss: 0.9124 | Val acc: 56.07% | LR: 0.000015
Epoch: 113 | MCC: 0.034935 | Train loss: 0.9813 | Train acc: 50.90% | Val loss: 0.9134 | Val acc: 56.12% | LR: 0.000015
Epoch: 114 | MCC: 0.035100 | Train loss: 0.9831 | Train acc: 50.79% | Val loss: 0.9126 | Val acc: 56.12% | LR: 0.000014
Epoch: 115 | MCC: 0.036040 | Train loss: 0.9824 | Train acc: 50.92% | Val loss: 0.9198 | Val acc: 56.14% | LR: 0.000013
Epoch: 116 | MCC: 0.030029 | Train loss: 0.9812 | Train acc: 50.89% | Val loss: 0.9124 | Val acc: 56.01% | LR: 0.000013
Epoch: 117 | MCC: 0.034000 | Train loss: 0.9814 | Train acc: 50.82% | Val loss: 0.9124 | Val acc: 56.07% | LR: 0.000012
Epoch: 118 | MCC: 0.030233 | Train loss: 0.9802 | Train acc: 50.89% | Val loss: 0.9138 | Val acc: 56.01% | LR: 0.000011
Epoch: 119 | MCC: 0.027941 | Train loss: 0.9807 | Train acc: 50.90% | Val loss: 0.9239 | Val acc: 55.93% | LR: 0.000011
Epoch: 120 | MCC: 0.031059 | Train loss: 0.9801 | Train acc: 50.91% | Val loss: 0.9104 | Val acc: 56.09% | LR: 0.000010
Epoch: 121 | MCC: 0.030233 | Train loss: 0.9805 | Train acc: 50.90% | Val loss: 0.9171 | Val acc: 56.01% | LR: 0.000009
Epoch: 122 | MCC: 0.032190 | Train loss: 0.9822 | Train acc: 50.82% | Val loss: 0.9110 | Val acc: 56.12% | LR: 0.000009
Epoch: 123 | MCC: 0.031059 | Train loss: 0.9815 | Train acc: 50.84% | Val loss: 0.9111 | Val acc: 56.09% | LR: 0.000008
Epoch: 124 | MCC: 0.030285 | Train loss: 0.9823 | Train acc: 50.75% | Val loss: 0.9126 | Val acc: 56.04% | LR: 0.000008
Epoch: 125 | MCC: 0.030285 | Train loss: 0.9815 | Train acc: 50.76% | Val loss: 0.9127 | Val acc: 56.04% | LR: 0.000007
Epoch: 126 | MCC: 0.031565 | Train loss: 0.9807 | Train acc: 50.87% | Val loss: 0.9147 | Val acc: 56.12% | LR: 0.000007
Epoch: 127 | MCC: 0.034834 | Train loss: 0.9812 | Train acc: 50.88% | Val loss: 1.0045 | Val acc: 56.14% | LR: 0.000006
Epoch: 128 | MCC: 0.031663 | Train loss: 0.9826 | Train acc: 50.72% | Val loss: 0.9120 | Val acc: 56.14% | LR: 0.000006
Epoch: 129 | MCC: 0.031663 | Train loss: 0.9830 | Train acc: 50.74% | Val loss: 0.9120 | Val acc: 56.14% | LR: 0.000005
Epoch: 130 | MCC: 0.030285 | Train loss: 0.9827 | Train acc: 50.77% | Val loss: 0.9137 | Val acc: 56.04% | LR: 0.000005
Epoch: 131 | MCC: 0.030575 | Train loss: 0.9804 | Train acc: 50.92% | Val loss: 0.9170 | Val acc: 56.04% | LR: 0.000005
Epoch: 132 | MCC: 0.030634 | Train loss: 0.9816 | Train acc: 50.89% | Val loss: 0.9221 | Val acc: 56.06% | LR: 0.000004
Epoch: 133 | MCC: 0.036819 | Train loss: 0.9810 | Train acc: 50.83% | Val loss: 0.9096 | Val acc: 56.21% | LR: 0.000004
Epoch: 134 | MCC: 0.030285 | Train loss: 0.9802 | Train acc: 50.87% | Val loss: 0.9480 | Val acc: 56.06% | LR: 0.000003
Epoch: 135 | MCC: 0.035876 | Train loss: 0.9806 | Train acc: 50.91% | Val loss: 0.9099 | Val acc: 56.16% | LR: 0.000003
Epoch: 136 | MCC: 0.035876 | Train loss: 0.9800 | Train acc: 50.98% | Val loss: 0.9099 | Val acc: 56.16% | LR: 0.000003
Epoch: 137 | MCC: 0.035876 | Train loss: 0.9798 | Train acc: 50.89% | Val loss: 0.9097 | Val acc: 56.16% | LR: 0.000003
Epoch: 138 | MCC: 0.035876 | Train loss: 0.9791 | Train acc: 50.98% | Val loss: 0.9097 | Val acc: 56.16% | LR: 0.000002
Epoch: 139 | MCC: 0.034935 | Train loss: 0.9813 | Train acc: 50.85% | Val loss: 0.9215 | Val acc: 56.12% | LR: 0.000002
Epoch: 140 | MCC: 0.034935 | Train loss: 0.9831 | Train acc: 50.84% | Val loss: 0.9286 | Val acc: 56.12% | LR: 0.000002
Epoch: 141 | MCC: 0.030691 | Train loss: 0.9812 | Train acc: 50.86% | Val loss: 0.9357 | Val acc: 56.06% | LR: 0.000002
Epoch: 142 | MCC: 0.034935 | Train loss: 0.9805 | Train acc: 50.89% | Val loss: 0.9381 | Val acc: 56.12% | LR: 0.000002
Epoch: 143 | MCC: 0.030691 | Train loss: 0.9822 | Train acc: 50.90% | Val loss: 0.9163 | Val acc: 56.06% | LR: 0.000001
Epoch: 144 | MCC: 0.029547 | Train loss: 0.9803 | Train acc: 50.90% | Val loss: 0.9172 | Val acc: 56.01% | LR: 0.000001
Epoch: 145 | MCC: 0.030691 | Train loss: 0.9835 | Train acc: 50.78% | Val loss: 0.9175 | Val acc: 56.06% | LR: 0.000001
Epoch: 146 | MCC: 0.030837 | Train loss: 0.9807 | Train acc: 50.85% | Val loss: 0.9139 | Val acc: 56.06% | LR: 0.000001
Epoch: 147 | MCC: 0.031777 | Train loss: 0.9805 | Train acc: 50.95% | Val loss: 0.9135 | Val acc: 56.10% | LR: 0.000001
Epoch: 148 | MCC: 0.031777 | Train loss: 0.9802 | Train acc: 50.88% | Val loss: 0.9134 | Val acc: 56.10% | LR: 0.000001
Epoch: 149 | MCC: 0.031777 | Train loss: 0.9800 | Train acc: 50.88% | Val loss: 0.9140 | Val acc: 56.10% | LR: 0.000001

[I 2025-10-05 09:10:36,702] Trial 16 finished with value: 0.03177729249000549 and parameters: {'lr': 0.00010241227157999414, 'hidden_size': 79, 'dropout': 0.3226668133931244, 'weight_decay': 0.07855891701728943}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: -0.010896 | Train loss: 1.0026 | Train acc: 49.30% | Val loss: 1.0007 | Val acc: 49.43% | LR: 0.000259
Epoch: 001 | MCC: -0.013566 | Train loss: 1.0011 | Train acc: 49.68% | Val loss: 0.9988 | Val acc: 50.45% | LR: 0.000259
Epoch: 002 | MCC: -0.010830 | Train loss: 0.9996 | Train acc: 50.10% | Val loss: 0.9948 | Val acc: 53.51% | LR: 0.000258
Epoch: 003 | MCC: 0.022328 | Train loss: 0.9986 | Train acc: 50.89% | Val loss: 0.9921 | Val acc: 56.05% | LR: 0.000258
Epoch: 004 | MCC: 0.024143 | Train loss: 0.9971 | Train acc: 51.20% | Val loss: 0.9901 | Val acc: 57.15% | LR: 0.000258
Epoch: 005 | MCC: 0.028531 | Train loss: 0.9955 | Train acc: 51.06% | Val loss: 0.9862 | Val acc: 57.71% | LR: 0.000258
Epoch: 006 | MCC: 0.020085 | Train loss: 0.9948 | Train acc: 50.99% | Val loss: 0.9821 | Val acc: 56.87% | LR: 0.000257
Epoch: 007 | MCC: 0.032245 | Train loss: 0.9931 | Train acc: 50.88% | Val loss: 0.9764 | Val acc: 57.02% | LR: 0.000257
Epoch: 008 | MCC: 0.031203 | Train loss: 0.9905 | Train acc: 50.98% | Val loss: 0.9696 | Val acc: 56.31% | LR: 0.000256
Epoch: 009 | MCC: 0.030474 | Train loss: 0.9893 | Train acc: 50.92% | Val loss: 0.9643 | Val acc: 56.45% | LR: 0.000256
Epoch: 010 | MCC: 0.030589 | Train loss: 0.9857 | Train acc: 50.94% | Val loss: 0.9560 | Val acc: 56.63% | LR: 0.000255
Epoch: 011 | MCC: 0.030736 | Train loss: 0.9841 | Train acc: 50.96% | Val loss: 0.9520 | Val acc: 56.71% | LR: 0.000255
Epoch: 012 | MCC: 0.027476 | Train loss: 0.9853 | Train acc: 50.80% | Val loss: 0.9438 | Val acc: 56.64% | LR: 0.000254
Epoch: 013 | MCC: 0.020354 | Train loss: 0.9842 | Train acc: 50.86% | Val loss: 0.9371 | Val acc: 56.34% | LR: 0.000253
Epoch: 014 | MCC: 0.021782 | Train loss: 0.9824 | Train acc: 50.95% | Val loss: 0.9312 | Val acc: 56.46% | LR: 0.000252
Epoch: 015 | MCC: 0.018694 | Train loss: 0.9838 | Train acc: 50.78% | Val loss: 0.9239 | Val acc: 56.32% | LR: 0.000252
Epoch: 016 | MCC: 0.017788 | Train loss: 0.9829 | Train acc: 50.86% | Val loss: 0.9182 | Val acc: 56.36% | LR: 0.000251
Epoch: 017 | MCC: 0.021852 | Train loss: 0.9828 | Train acc: 50.85% | Val loss: 0.9137 | Val acc: 56.63% | LR: 0.000250
Epoch: 018 | MCC: 0.035012 | Train loss: 0.9801 | Train acc: 51.07% | Val loss: 0.9125 | Val acc: 57.04% | LR: 0.000249
Epoch: 019 | MCC: 0.032261 | Train loss: 0.9808 | Train acc: 51.07% | Val loss: 0.9071 | Val acc: 57.71% | LR: 0.000248
Epoch: 020 | MCC: 0.042830 | Train loss: 0.9816 | Train acc: 50.97% | Val loss: 0.9037 | Val acc: 57.74% | LR: 0.000246
Epoch: 021 | MCC: 0.041525 | Train loss: 0.9800 | Train acc: 51.08% | Val loss: 0.8989 | Val acc: 57.88% | LR: 0.000245
Epoch: 022 | MCC: 0.045460 | Train loss: 0.9811 | Train acc: 51.09% | Val loss: 0.8980 | Val acc: 57.95% | LR: 0.000244
Epoch: 023 | MCC: 0.040166 | Train loss: 0.9798 | Train acc: 51.13% | Val loss: 0.8912 | Val acc: 57.67% | LR: 0.000243
Epoch: 024 | MCC: 0.039050 | Train loss: 0.9816 | Train acc: 50.99% | Val loss: 0.8854 | Val acc: 57.72% | LR: 0.000241
Epoch: 025 | MCC: 0.023011 | Train loss: 0.9791 | Train acc: 51.15% | Val loss: 0.8860 | Val acc: 56.89% | LR: 0.000240
Epoch: 026 | MCC: 0.026857 | Train loss: 0.9780 | Train acc: 51.18% | Val loss: 0.8823 | Val acc: 56.96% | LR: 0.000239
Epoch: 027 | MCC: 0.008359 | Train loss: 0.9785 | Train acc: 51.11% | Val loss: 0.8798 | Val acc: 56.65% | LR: 0.000237
Epoch: 028 | MCC: -0.002047 | Train loss: 0.9782 | Train acc: 51.17% | Val loss: 0.8803 | Val acc: 56.03% | LR: 0.000236
Epoch: 029 | MCC: 0.000878 | Train loss: 0.9781 | Train acc: 51.27% | Val loss: 0.8768 | Val acc: 56.25% | LR: 0.000234
Epoch: 030 | MCC: 0.013905 | Train loss: 0.9764 | Train acc: 51.32% | Val loss: 0.8789 | Val acc: 56.47% | LR: 0.000232
Epoch: 031 | MCC: 0.007716 | Train loss: 0.9785 | Train acc: 51.19% | Val loss: 0.8670 | Val acc: 57.22% | LR: 0.000231
Epoch: 032 | MCC: 0.021672 | Train loss: 0.9766 | Train acc: 51.23% | Val loss: 0.8776 | Val acc: 56.76% | LR: 0.000229
Epoch: 033 | MCC: 0.012008 | Train loss: 0.9773 | Train acc: 51.24% | Val loss: 0.8781 | Val acc: 56.54% | LR: 0.000227
Epoch: 034 | MCC: 0.013940 | Train loss: 0.9744 | Train acc: 51.31% | Val loss: 0.8764 | Val acc: 56.54% | LR: 0.000226
Epoch: 035 | MCC: 0.003740 | Train loss: 0.9745 | Train acc: 51.28% | Val loss: 0.8680 | Val acc: 56.74% | LR: 0.000224
Epoch: 036 | MCC: 0.000700 | Train loss: 0.9748 | Train acc: 51.29% | Val loss: 0.8645 | Val acc: 57.49% | LR: 0.000222
Epoch: 037 | MCC: 0.002499 | Train loss: 0.9750 | Train acc: 51.23% | Val loss: 0.8577 | Val acc: 57.93% | LR: 0.000220
Epoch: 038 | MCC: 0.000036 | Train loss: 0.9750 | Train acc: 51.34% | Val loss: 0.8649 | Val acc: 56.98% | LR: 0.000218
Epoch: 039 | MCC: -0.000450 | Train loss: 0.9733 | Train acc: 51.40% | Val loss: 0.8664 | Val acc: 57.03% | LR: 0.000216
Epoch: 040 | MCC: 0.016885 | Train loss: 0.9750 | Train acc: 51.28% | Val loss: 0.8567 | Val acc: 58.03% | LR: 0.000214
Epoch: 041 | MCC: -0.000354 | Train loss: 0.9743 | Train acc: 51.30% | Val loss: 0.8604 | Val acc: 57.35% | LR: 0.000212
Epoch: 042 | MCC: 0.031367 | Train loss: 0.9745 | Train acc: 51.27% | Val loss: 0.8390 | Val acc: 58.88% | LR: 0.000210
Epoch: 043 | MCC: 0.026124 | Train loss: 0.9726 | Train acc: 51.43% | Val loss: 0.8438 | Val acc: 58.47% | LR: 0.000208
Epoch: 044 | MCC: 0.027480 | Train loss: 0.9739 | Train acc: 51.33% | Val loss: 0.8360 | Val acc: 58.86% | LR: 0.000206
Epoch: 045 | MCC: 0.057097 | Train loss: 0.9714 | Train acc: 51.51% | Val loss: 0.8435 | Val acc: 58.76% | LR: 0.000203
Epoch: 046 | MCC: 0.043521 | Train loss: 0.9721 | Train acc: 51.42% | Val loss: 0.8270 | Val acc: 59.54% | LR: 0.000201
Epoch: 047 | MCC: 0.028463 | Train loss: 0.9721 | Train acc: 51.44% | Val loss: 0.8338 | Val acc: 59.13% | LR: 0.000199
Epoch: 048 | MCC: 0.061461 | Train loss: 0.9727 | Train acc: 51.36% | Val loss: 0.8419 | Val acc: 58.74% | LR: 0.000197
Epoch: 049 | MCC: 0.025741 | Train loss: 0.9724 | Train acc: 51.42% | Val loss: 0.8307 | Val acc: 59.02% | LR: 0.000194
Epoch: 050 | MCC: 0.055435 | Train loss: 0.9705 | Train acc: 51.51% | Val loss: 0.8285 | Val acc: 59.32% | LR: 0.000192
Epoch: 051 | MCC: 0.017217 | Train loss: 0.9728 | Train acc: 51.33% | Val loss: 0.8383 | Val acc: 58.53% | LR: 0.000190
Epoch: 052 | MCC: 0.017744 | Train loss: 0.9726 | Train acc: 51.31% | Val loss: 0.8573 | Val acc: 57.74% | LR: 0.000187
Epoch: 053 | MCC: 0.046340 | Train loss: 0.9726 | Train acc: 51.40% | Val loss: 0.8390 | Val acc: 58.70% | LR: 0.000185
Epoch: 054 | MCC: 0.022257 | Train loss: 0.9718 | Train acc: 51.39% | Val loss: 0.8495 | Val acc: 58.03% | LR: 0.000182
Epoch: 055 | MCC: 0.022055 | Train loss: 0.9760 | Train acc: 51.10% | Val loss: 0.8377 | Val acc: 58.81% | LR: 0.000180
Epoch: 056 | MCC: 0.028639 | Train loss: 0.9713 | Train acc: 51.46% | Val loss: 0.8438 | Val acc: 58.44% | LR: 0.000177
Epoch: 057 | MCC: 0.063172 | Train loss: 0.9707 | Train acc: 51.43% | Val loss: 0.8180 | Val acc: 59.91% | LR: 0.000175
Epoch: 058 | MCC: 0.037401 | Train loss: 0.9701 | Train acc: 51.52% | Val loss: 0.8204 | Val acc: 59.85% | LR: 0.000172
Epoch: 059 | MCC: 0.036053 | Train loss: 0.9698 | Train acc: 51.56% | Val loss: 0.8191 | Val acc: 59.85% | LR: 0.000170
Epoch: 060 | MCC: 0.019987 | Train loss: 0.9690 | Train acc: 51.59% | Val loss: 0.8323 | Val acc: 58.87% | LR: 0.000167
Epoch: 061 | MCC: 0.026779 | Train loss: 0.9716 | Train acc: 51.39% | Val loss: 0.8318 | Val acc: 59.22% | LR: 0.000165
Epoch: 062 | MCC: 0.060067 | Train loss: 0.9693 | Train acc: 51.59% | Val loss: 0.8221 | Val acc: 59.54% | LR: 0.000162
Epoch: 063 | MCC: 0.029524 | Train loss: 0.9695 | Train acc: 51.49% | Val loss: 0.8326 | Val acc: 59.04% | LR: 0.000159
Epoch: 064 | MCC: 0.050952 | Train loss: 0.9687 | Train acc: 51.55% | Val loss: 0.8294 | Val acc: 59.10% | LR: 0.000157
Epoch: 065 | MCC: 0.056441 | Train loss: 0.9690 | Train acc: 51.58% | Val loss: 0.8445 | Val acc: 58.32% | LR: 0.000154
Epoch: 066 | MCC: 0.023336 | Train loss: 0.9709 | Train acc: 51.46% | Val loss: 0.8514 | Val acc: 57.98% | LR: 0.000151
Epoch: 067 | MCC: 0.022258 | Train loss: 0.9697 | Train acc: 51.45% | Val loss: 0.8357 | Val acc: 58.80% | LR: 0.000149
Epoch: 068 | MCC: 0.052224 | Train loss: 0.9703 | Train acc: 51.46% | Val loss: 0.8093 | Val acc: 60.35% | LR: 0.000146
Epoch: 069 | MCC: 0.026374 | Train loss: 0.9705 | Train acc: 51.42% | Val loss: 0.8288 | Val acc: 59.26% | LR: 0.000143
Epoch: 070 | MCC: 0.034747 | Train loss: 0.9677 | Train acc: 51.61% | Val loss: 0.8223 | Val acc: 59.61% | LR: 0.000141
Epoch: 071 | MCC: 0.035459 | Train loss: 0.9695 | Train acc: 51.48% | Val loss: 0.8177 | Val acc: 59.90% | LR: 0.000138
Epoch: 072 | MCC: 0.034268 | Train loss: 0.9691 | Train acc: 51.46% | Val loss: 0.8196 | Val acc: 59.65% | LR: 0.000135
Epoch: 073 | MCC: 0.029526 | Train loss: 0.9696 | Train acc: 51.56% | Val loss: 0.8233 | Val acc: 59.51% | LR: 0.000133
Epoch: 074 | MCC: 0.036867 | Train loss: 0.9681 | Train acc: 51.61% | Val loss: 0.8207 | Val acc: 59.78% | LR: 0.000130
Epoch: 075 | MCC: 0.033587 | Train loss: 0.9695 | Train acc: 51.44% | Val loss: 0.8243 | Val acc: 59.44% | LR: 0.000127
Epoch: 076 | MCC: 0.026695 | Train loss: 0.9687 | Train acc: 51.50% | Val loss: 0.8283 | Val acc: 59.17% | LR: 0.000124
Epoch: 077 | MCC: 0.066270 | Train loss: 0.9674 | Train acc: 51.60% | Val loss: 0.8139 | Val acc: 59.90% | LR: 0.000122
Epoch: 078 | MCC: 0.026695 | Train loss: 0.9674 | Train acc: 51.59% | Val loss: 0.8284 | Val acc: 59.17% | LR: 0.000119
Epoch: 079 | MCC: 0.030575 | Train loss: 0.9682 | Train acc: 51.55% | Val loss: 0.8195 | Val acc: 59.56% | LR: 0.000116
Epoch: 080 | MCC: 0.034587 | Train loss: 0.9693 | Train acc: 51.48% | Val loss: 0.8212 | Val acc: 59.63% | LR: 0.000114
Epoch: 081 | MCC: 0.036436 | Train loss: 0.9670 | Train acc: 51.55% | Val loss: 0.8201 | Val acc: 59.70% | LR: 0.000111
Epoch: 082 | MCC: 0.031993 | Train loss: 0.9667 | Train acc: 51.63% | Val loss: 0.8173 | Val acc: 59.73% | LR: 0.000108
Epoch: 083 | MCC: 0.030482 | Train loss: 0.9692 | Train acc: 51.46% | Val loss: 0.8247 | Val acc: 59.36% | LR: 0.000106
Epoch: 084 | MCC: 0.030029 | Train loss: 0.9654 | Train acc: 51.65% | Val loss: 0.8295 | Val acc: 59.22% | LR: 0.000103
Epoch: 085 | MCC: 0.031555 | Train loss: 0.9676 | Train acc: 51.58% | Val loss: 0.8243 | Val acc: 59.34% | LR: 0.000100
Epoch: 086 | MCC: 0.034137 | Train loss: 0.9681 | Train acc: 51.44% | Val loss: 0.8199 | Val acc: 59.63% | LR: 0.000098
Epoch: 087 | MCC: 0.049109 | Train loss: 0.9668 | Train acc: 51.54% | Val loss: 0.8257 | Val acc: 59.24% | LR: 0.000095
Epoch: 088 | MCC: 0.026315 | Train loss: 0.9737 | Train acc: 51.44% | Val loss: 0.8293 | Val acc: 59.14% | LR: 0.000093
Epoch: 089 | MCC: 0.030946 | Train loss: 0.9679 | Train acc: 51.55% | Val loss: 0.8188 | Val acc: 59.52% | LR: 0.000090
Epoch: 090 | MCC: 0.032192 | Train loss: 0.9680 | Train acc: 51.54% | Val loss: 0.8255 | Val acc: 59.39% | LR: 0.000087
Epoch: 091 | MCC: 0.052057 | Train loss: 0.9668 | Train acc: 51.53% | Val loss: 0.8212 | Val acc: 59.48% | LR: 0.000085
Epoch: 092 | MCC: 0.059842 | Train loss: 0.9685 | Train acc: 51.47% | Val loss: 0.8150 | Val acc: 59.80% | LR: 0.000082
Epoch: 093 | MCC: 0.075497 | Train loss: 0.9689 | Train acc: 51.42% | Val loss: 0.8088 | Val acc: 60.31% | LR: 0.000080
Epoch: 094 | MCC: 0.062672 | Train loss: 0.9690 | Train acc: 51.45% | Val loss: 0.8180 | Val acc: 59.74% | LR: 0.000077
Epoch: 095 | MCC: 0.071301 | Train loss: 0.9684 | Train acc: 51.43% | Val loss: 0.8100 | Val acc: 60.19% | LR: 0.000075
Epoch: 096 | MCC: 0.030340 | Train loss: 0.9685 | Train acc: 51.43% | Val loss: 0.8231 | Val acc: 59.39% | LR: 0.000073
Epoch: 097 | MCC: 0.052661 | Train loss: 0.9658 | Train acc: 51.68% | Val loss: 0.8197 | Val acc: 59.56% | LR: 0.000070
Epoch: 098 | MCC: 0.057654 | Train loss: 0.9675 | Train acc: 51.51% | Val loss: 0.8198 | Val acc: 59.57% | LR: 0.000068
Epoch: 099 | MCC: 0.055427 | Train loss: 0.9666 | Train acc: 51.58% | Val loss: 0.8267 | Val acc: 59.32% | LR: 0.000065
Epoch: 100 | MCC: 0.032275 | Train loss: 0.9664 | Train acc: 51.53% | Val loss: 0.8248 | Val acc: 59.34% | LR: 0.000063
Epoch: 101 | MCC: 0.028509 | Train loss: 0.9655 | Train acc: 51.68% | Val loss: 0.8293 | Val acc: 59.14% | LR: 0.000061
Epoch: 102 | MCC: 0.029211 | Train loss: 0.9689 | Train acc: 51.42% | Val loss: 0.8285 | Val acc: 59.22% | LR: 0.000059
Epoch: 103 | MCC: 0.057161 | Train loss: 0.9665 | Train acc: 51.57% | Val loss: 0.8220 | Val acc: 59.45% | LR: 0.000056
Epoch: 104 | MCC: 0.031301 | Train loss: 0.9661 | Train acc: 51.63% | Val loss: 0.8269 | Val acc: 59.29% | LR: 0.000054
Epoch: 105 | MCC: 0.031590 | Train loss: 1.0067 | Train acc: 51.43% | Val loss: 0.8270 | Val acc: 59.29% | LR: 0.000052
Epoch: 106 | MCC: 0.032053 | Train loss: 1.0718 | Train acc: 51.37% | Val loss: 0.8272 | Val acc: 59.34% | LR: 0.000050
Epoch: 107 | MCC: 0.030577 | Train loss: 1.0292 | Train acc: 51.62% | Val loss: 0.8271 | Val acc: 59.29% | LR: 0.000048
Epoch: 108 | MCC: 0.033682 | Train loss: 1.0092 | Train acc: 51.40% | Val loss: 0.8272 | Val acc: 59.36% | LR: 0.000046
Epoch: 109 | MCC: 0.030942 | Train loss: 0.9899 | Train acc: 51.58% | Val loss: 0.8292 | Val acc: 59.24% | LR: 0.000044
Epoch: 110 | MCC: 0.027436 | Train loss: 1.0086 | Train acc: 51.49% | Val loss: 0.8293 | Val acc: 59.12% | LR: 0.000042
Epoch: 111 | MCC: 0.032252 | Train loss: 0.9900 | Train acc: 51.47% | Val loss: 0.8247 | Val acc: 59.36% | LR: 0.000040
Epoch: 112 | MCC: 0.031455 | Train loss: 0.9816 | Train acc: 51.55% | Val loss: 0.8272 | Val acc: 59.29% | LR: 0.000038
Epoch: 113 | MCC: 0.029382 | Train loss: 1.0293 | Train acc: 51.48% | Val loss: 0.8283 | Val acc: 59.22% | LR: 0.000036
Epoch: 114 | MCC: 0.033401 | Train loss: 0.9834 | Train acc: 51.44% | Val loss: 0.8266 | Val acc: 59.34% | LR: 0.000034
Epoch: 115 | MCC: 0.033445 | Train loss: 0.9777 | Train acc: 51.54% | Val loss: 0.8259 | Val acc: 59.39% | LR: 0.000032
Epoch: 116 | MCC: 0.032665 | Train loss: 0.9789 | Train acc: 51.33% | Val loss: 0.8262 | Val acc: 59.34% | LR: 0.000031
Epoch: 117 | MCC: 0.031064 | Train loss: 0.9816 | Train acc: 51.46% | Val loss: 0.8258 | Val acc: 59.26% | LR: 0.000029
Epoch: 118 | MCC: 0.030232 | Train loss: 0.9834 | Train acc: 51.47% | Val loss: 0.8272 | Val acc: 59.22% | LR: 0.000027
Epoch: 119 | MCC: 0.028974 | Train loss: 0.9748 | Train acc: 51.54% | Val loss: 0.8274 | Val acc: 59.22% | LR: 0.000026
Epoch: 120 | MCC: 0.028572 | Train loss: 0.9834 | Train acc: 51.57% | Val loss: 0.8267 | Val acc: 59.19% | LR: 0.000024
Epoch: 121 | MCC: 0.030548 | Train loss: 0.9744 | Train acc: 51.60% | Val loss: 0.8270 | Val acc: 59.24% | LR: 0.000023
Epoch: 122 | MCC: 0.032976 | Train loss: 0.9782 | Train acc: 51.62% | Val loss: 0.8253 | Val acc: 59.36% | LR: 0.000021
Epoch: 123 | MCC: 0.033826 | Train loss: 0.9736 | Train acc: 51.59% | Val loss: 0.8259 | Val acc: 59.36% | LR: 0.000020
Epoch: 124 | MCC: 0.034353 | Train loss: 0.9734 | Train acc: 51.59% | Val loss: 0.8252 | Val acc: 59.44% | LR: 0.000018
Epoch: 125 | MCC: 0.034353 | Train loss: 0.9736 | Train acc: 51.54% | Val loss: 0.8250 | Val acc: 59.44% | LR: 0.000017
Epoch: 126 | MCC: 0.033445 | Train loss: 0.9734 | Train acc: 51.53% | Val loss: 0.8255 | Val acc: 59.39% | LR: 0.000016
Epoch: 127 | MCC: 0.033005 | Train loss: 0.9737 | Train acc: 51.58% | Val loss: 0.8264 | Val acc: 59.36% | LR: 0.000014
Epoch: 128 | MCC: 0.033588 | Train loss: 0.9740 | Train acc: 51.49% | Val loss: 0.8253 | Val acc: 59.39% | LR: 0.000013
Epoch: 129 | MCC: 0.033849 | Train loss: 0.9728 | Train acc: 51.54% | Val loss: 0.8260 | Val acc: 59.36% | LR: 0.000012
Epoch: 130 | MCC: 0.033588 | Train loss: 0.9779 | Train acc: 51.65% | Val loss: 0.8256 | Val acc: 59.39% | LR: 0.000011
Epoch: 131 | MCC: 0.033849 | Train loss: 0.9724 | Train acc: 51.51% | Val loss: 0.8258 | Val acc: 59.36% | LR: 0.000010
Epoch: 132 | MCC: 0.034513 | Train loss: 0.9735 | Train acc: 51.57% | Val loss: 0.8257 | Val acc: 59.41% | LR: 0.000009
Epoch: 133 | MCC: 0.033927 | Train loss: 0.9754 | Train acc: 51.46% | Val loss: 0.8258 | Val acc: 59.36% | LR: 0.000008
Epoch: 134 | MCC: 0.033766 | Train loss: 0.9737 | Train acc: 51.50% | Val loss: 0.8254 | Val acc: 59.39% | LR: 0.000007
Epoch: 135 | MCC: 0.032923 | Train loss: 0.9719 | Train acc: 51.57% | Val loss: 0.8257 | Val acc: 59.34% | LR: 0.000006
Epoch: 136 | MCC: 0.034353 | Train loss: 0.9711 | Train acc: 51.65% | Val loss: 0.8250 | Val acc: 59.44% | LR: 0.000006
Epoch: 137 | MCC: 0.033002 | Train loss: 0.9754 | Train acc: 51.34% | Val loss: 0.8257 | Val acc: 59.34% | LR: 0.000005
Epoch: 138 | MCC: 0.033831 | Train loss: 0.9727 | Train acc: 51.53% | Val loss: 0.8255 | Val acc: 59.39% | LR: 0.000004
Epoch: 139 | MCC: 0.032237 | Train loss: 0.9739 | Train acc: 51.49% | Val loss: 0.8258 | Val acc: 59.29% | LR: 0.000004
Epoch: 140 | MCC: 0.033909 | Train loss: 0.9750 | Train acc: 51.55% | Val loss: 0.8256 | Val acc: 59.39% | LR: 0.000003
Epoch: 141 | MCC: 0.033993 | Train loss: 0.9727 | Train acc: 51.61% | Val loss: 0.8259 | Val acc: 59.36% | LR: 0.000003
Epoch: 142 | MCC: 0.033843 | Train loss: 0.9732 | Train acc: 51.40% | Val loss: 0.8257 | Val acc: 59.36% | LR: 0.000002
Epoch: 143 | MCC: 0.033993 | Train loss: 0.9715 | Train acc: 51.55% | Val loss: 0.8258 | Val acc: 59.36% | LR: 0.000002
Epoch: 144 | MCC: 0.033843 | Train loss: 0.9730 | Train acc: 51.46% | Val loss: 0.8257 | Val acc: 59.36% | LR: 0.000002
Epoch: 145 | MCC: 0.033066 | Train loss: 0.9733 | Train acc: 51.42% | Val loss: 0.8257 | Val acc: 59.34% | LR: 0.000001
Epoch: 146 | MCC: 0.033066 | Train loss: 0.9713 | Train acc: 51.47% | Val loss: 0.8257 | Val acc: 59.34% | LR: 0.000001
Epoch: 147 | MCC: 0.033066 | Train loss: 0.9755 | Train acc: 51.58% | Val loss: 0.8256 | Val acc: 59.34% | LR: 0.000001
Epoch: 148 | MCC: 0.033066 | Train loss: 0.9703 | Train acc: 51.63% | Val loss: 0.8256 | Val acc: 59.34% | LR: 0.000001
Epoch: 149 | MCC: 0.033066 | Train loss: 0.9723 | Train acc: 51.50% | Val loss: 0.8256 | Val acc: 59.34% | LR: 0.000001

[I 2025-10-05 09:12:39,723] Trial 17 finished with value: 0.03306639660149813 and parameters: {'lr': 0.0002587160879747491, 'hidden_size': 53, 'dropout': 0.421993881799862, 'weight_decay': 0.03630391434028882}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.038407 | Train loss: 1.0064 | Train acc: 50.19% | Val loss: 1.0295 | Val acc: 49.87% | LR: 0.000107
Epoch: 001 | MCC: 0.034423 | Train loss: 0.9985 | Train acc: 50.46% | Val loss: 1.0024 | Val acc: 49.28% | LR: 0.000107
Epoch: 002 | MCC: 0.029142 | Train loss: 0.9989 | Train acc: 50.45% | Val loss: 1.0018 | Val acc: 49.01% | LR: 0.000107
Epoch: 003 | MCC: 0.025314 | Train loss: 0.9971 | Train acc: 50.51% | Val loss: 1.0004 | Val acc: 49.50% | LR: 0.000107
Epoch: 004 | MCC: 0.024167 | Train loss: 0.9945 | Train acc: 50.56% | Val loss: 1.0009 | Val acc: 48.76% | LR: 0.000107
Epoch: 005 | MCC: 0.021855 | Train loss: 1.0214 | Train acc: 50.29% | Val loss: 1.0003 | Val acc: 48.64% | LR: 0.000107
Epoch: 006 | MCC: 0.013768 | Train loss: 1.0055 | Train acc: 50.46% | Val loss: 1.0015 | Val acc: 48.38% | LR: 0.000107
Epoch: 007 | MCC: 0.016831 | Train loss: 1.0041 | Train acc: 50.65% | Val loss: 1.0050 | Val acc: 48.36% | LR: 0.000107
Epoch: 008 | MCC: 0.031479 | Train loss: 1.0634 | Train acc: 50.45% | Val loss: 1.0003 | Val acc: 48.89% | LR: 0.000106
Epoch: 009 | MCC: 0.039452 | Train loss: 1.0028 | Train acc: 50.44% | Val loss: 1.0016 | Val acc: 48.85% | LR: 0.000106
Epoch: 010 | MCC: 0.037705 | Train loss: 0.9972 | Train acc: 50.75% | Val loss: 1.0005 | Val acc: 48.96% | LR: 0.000106
Epoch: 011 | MCC: 0.043907 | Train loss: 0.9964 | Train acc: 50.77% | Val loss: 1.0011 | Val acc: 49.46% | LR: 0.000106
Epoch: 012 | MCC: 0.033177 | Train loss: 0.9959 | Train acc: 50.83% | Val loss: 1.0009 | Val acc: 49.53% | LR: 0.000105
Epoch: 013 | MCC: 0.025979 | Train loss: 0.9946 | Train acc: 50.99% | Val loss: 1.0008 | Val acc: 49.27% | LR: 0.000105
Epoch: 014 | MCC: 0.034857 | Train loss: 0.9940 | Train acc: 50.86% | Val loss: 1.0009 | Val acc: 49.33% | LR: 0.000105
Epoch: 015 | MCC: 0.028085 | Train loss: 0.9939 | Train acc: 50.91% | Val loss: 1.0004 | Val acc: 49.11% | LR: 0.000104
Epoch: 016 | MCC: 0.031288 | Train loss: 0.9923 | Train acc: 50.93% | Val loss: 1.0000 | Val acc: 49.25% | LR: 0.000104
Epoch: 017 | MCC: 0.027147 | Train loss: 0.9933 | Train acc: 50.77% | Val loss: 0.9994 | Val acc: 49.21% | LR: 0.000104
Epoch: 018 | MCC: 0.042935 | Train loss: 0.9928 | Train acc: 50.80% | Val loss: 0.9995 | Val acc: 50.19% | LR: 0.000103
Epoch: 019 | MCC: 0.053663 | Train loss: 0.9919 | Train acc: 50.76% | Val loss: 0.9992 | Val acc: 51.28% | LR: 0.000103
Epoch: 020 | MCC: 0.044265 | Train loss: 0.9909 | Train acc: 50.77% | Val loss: 0.9979 | Val acc: 51.90% | LR: 0.000102
Epoch: 021 | MCC: 0.044830 | Train loss: 0.9915 | Train acc: 50.67% | Val loss: 0.9971 | Val acc: 52.65% | LR: 0.000102
Epoch: 022 | MCC: 0.049148 | Train loss: 0.9904 | Train acc: 50.68% | Val loss: 0.9965 | Val acc: 53.58% | LR: 0.000101
Epoch: 023 | MCC: 0.040035 | Train loss: 0.9970 | Train acc: 50.75% | Val loss: 0.9938 | Val acc: 53.64% | LR: 0.000101
Epoch: 024 | MCC: 0.047366 | Train loss: 0.9883 | Train acc: 50.85% | Val loss: 0.9901 | Val acc: 54.13% | LR: 0.000100
Epoch: 025 | MCC: 0.048880 | Train loss: 0.9884 | Train acc: 50.94% | Val loss: 0.9864 | Val acc: 54.59% | LR: 0.000100
Epoch: 026 | MCC: 0.050437 | Train loss: 0.9872 | Train acc: 50.71% | Val loss: 0.9934 | Val acc: 53.82% | LR: 0.000099
Epoch: 027 | MCC: 0.038959 | Train loss: 0.9884 | Train acc: 50.59% | Val loss: 0.9935 | Val acc: 53.29% | LR: 0.000098
Epoch: 028 | MCC: 0.039283 | Train loss: 0.9874 | Train acc: 50.83% | Val loss: 0.9941 | Val acc: 53.29% | LR: 0.000098
Epoch: 029 | MCC: 0.045681 | Train loss: 0.9876 | Train acc: 50.76% | Val loss: 0.9892 | Val acc: 53.83% | LR: 0.000097
Epoch: 030 | MCC: 0.034289 | Train loss: 0.9864 | Train acc: 50.71% | Val loss: 0.9917 | Val acc: 53.40% | LR: 0.000097
Epoch: 031 | MCC: 0.039935 | Train loss: 0.9847 | Train acc: 50.77% | Val loss: 0.9925 | Val acc: 53.47% | LR: 0.000096
Epoch: 032 | MCC: 0.041247 | Train loss: 0.9852 | Train acc: 50.73% | Val loss: 0.9912 | Val acc: 53.54% | LR: 0.000095
Epoch: 033 | MCC: 0.036777 | Train loss: 0.9837 | Train acc: 50.82% | Val loss: 0.9938 | Val acc: 53.37% | LR: 0.000094
Epoch: 034 | MCC: 0.037906 | Train loss: 0.9830 | Train acc: 50.96% | Val loss: 0.9904 | Val acc: 53.37% | LR: 0.000094
Epoch: 035 | MCC: 0.040640 | Train loss: 0.9827 | Train acc: 50.90% | Val loss: 0.9910 | Val acc: 53.43% | LR: 0.000093
Epoch: 036 | MCC: 0.038945 | Train loss: 0.9837 | Train acc: 50.85% | Val loss: 0.9903 | Val acc: 53.66% | LR: 0.000092
Epoch: 037 | MCC: 0.038161 | Train loss: 0.9826 | Train acc: 50.85% | Val loss: 0.9880 | Val acc: 53.70% | LR: 0.000091
Epoch: 038 | MCC: 0.037680 | Train loss: 0.9818 | Train acc: 50.96% | Val loss: 0.9894 | Val acc: 53.61% | LR: 0.000091
Epoch: 039 | MCC: 0.028950 | Train loss: 0.9841 | Train acc: 50.89% | Val loss: 0.9982 | Val acc: 53.02% | LR: 0.000090
Epoch: 040 | MCC: 0.035872 | Train loss: 0.9927 | Train acc: 50.71% | Val loss: 0.9894 | Val acc: 53.47% | LR: 0.000089
Epoch: 041 | MCC: 0.041266 | Train loss: 0.9833 | Train acc: 50.88% | Val loss: 0.9894 | Val acc: 53.73% | LR: 0.000088
Epoch: 042 | MCC: 0.041569 | Train loss: 0.9837 | Train acc: 50.80% | Val loss: 1.0952 | Val acc: 53.84% | LR: 0.000087
Epoch: 043 | MCC: 0.040402 | Train loss: 0.9829 | Train acc: 50.91% | Val loss: 0.9897 | Val acc: 53.91% | LR: 0.000086
Epoch: 044 | MCC: 0.046954 | Train loss: 0.9810 | Train acc: 50.90% | Val loss: 0.9893 | Val acc: 54.27% | LR: 0.000085
Epoch: 045 | MCC: 0.044899 | Train loss: 0.9813 | Train acc: 50.92% | Val loss: 0.9882 | Val acc: 54.09% | LR: 0.000085
Epoch: 046 | MCC: 0.041768 | Train loss: 0.9821 | Train acc: 50.78% | Val loss: 0.9857 | Val acc: 54.29% | LR: 0.000084
Epoch: 047 | MCC: 0.042941 | Train loss: 0.9803 | Train acc: 50.96% | Val loss: 0.9863 | Val acc: 54.10% | LR: 0.000083
Epoch: 048 | MCC: 0.043574 | Train loss: 0.9836 | Train acc: 50.72% | Val loss: 0.9894 | Val acc: 54.12% | LR: 0.000082
Epoch: 049 | MCC: 0.048699 | Train loss: 0.9812 | Train acc: 50.92% | Val loss: 0.9847 | Val acc: 54.41% | LR: 0.000081
Epoch: 050 | MCC: 0.043614 | Train loss: 0.9822 | Train acc: 50.78% | Val loss: 0.9931 | Val acc: 54.38% | LR: 0.000080
Epoch: 051 | MCC: 0.046684 | Train loss: 0.9858 | Train acc: 50.79% | Val loss: 1.0949 | Val acc: 54.32% | LR: 0.000079
Epoch: 052 | MCC: 0.049898 | Train loss: 0.9949 | Train acc: 50.77% | Val loss: 0.9910 | Val acc: 54.63% | LR: 0.000078
Epoch: 053 | MCC: 0.047636 | Train loss: 0.9818 | Train acc: 50.90% | Val loss: 0.9871 | Val acc: 54.55% | LR: 0.000077
Epoch: 054 | MCC: 0.044317 | Train loss: 0.9812 | Train acc: 50.91% | Val loss: 0.9827 | Val acc: 54.43% | LR: 0.000076
Epoch: 055 | MCC: 0.052455 | Train loss: 0.9813 | Train acc: 50.94% | Val loss: 0.9822 | Val acc: 54.69% | LR: 0.000075
Epoch: 056 | MCC: 0.050902 | Train loss: 0.9828 | Train acc: 50.88% | Val loss: 0.9820 | Val acc: 54.74% | LR: 0.000074
Epoch: 057 | MCC: 0.046039 | Train loss: 0.9821 | Train acc: 50.83% | Val loss: 0.9808 | Val acc: 54.82% | LR: 0.000073
Epoch: 058 | MCC: 0.044226 | Train loss: 0.9834 | Train acc: 50.85% | Val loss: 0.9856 | Val acc: 54.74% | LR: 0.000072
Epoch: 059 | MCC: 0.043955 | Train loss: 1.0163 | Train acc: 50.90% | Val loss: 0.9777 | Val acc: 54.92% | LR: 0.000071
Epoch: 060 | MCC: 0.043980 | Train loss: 0.9845 | Train acc: 50.84% | Val loss: 0.9785 | Val acc: 55.01% | LR: 0.000070
Epoch: 061 | MCC: 0.051262 | Train loss: 0.9818 | Train acc: 50.90% | Val loss: 0.9776 | Val acc: 55.16% | LR: 0.000068
Epoch: 062 | MCC: 0.046137 | Train loss: 0.9822 | Train acc: 50.79% | Val loss: 0.9779 | Val acc: 54.72% | LR: 0.000067
Epoch: 063 | MCC: 0.049051 | Train loss: 0.9821 | Train acc: 50.90% | Val loss: 0.9777 | Val acc: 55.07% | LR: 0.000066
Epoch: 064 | MCC: 0.050319 | Train loss: 0.9821 | Train acc: 50.93% | Val loss: 0.9764 | Val acc: 55.11% | LR: 0.000065
Epoch: 065 | MCC: 0.046012 | Train loss: 0.9803 | Train acc: 50.96% | Val loss: 0.9769 | Val acc: 54.97% | LR: 0.000064
Epoch: 066 | MCC: 0.042680 | Train loss: 0.9843 | Train acc: 51.03% | Val loss: 0.9774 | Val acc: 54.79% | LR: 0.000063
Epoch: 067 | MCC: 0.047564 | Train loss: 0.9820 | Train acc: 50.91% | Val loss: 0.9771 | Val acc: 55.11% | LR: 0.000062
Epoch: 068 | MCC: 0.048146 | Train loss: 0.9800 | Train acc: 51.03% | Val loss: 0.9747 | Val acc: 55.19% | LR: 0.000061
Epoch: 069 | MCC: 0.044867 | Train loss: 0.9810 | Train acc: 51.00% | Val loss: 0.9830 | Val acc: 54.90% | LR: 0.000060
Epoch: 070 | MCC: 0.038059 | Train loss: 0.9810 | Train acc: 50.99% | Val loss: 0.9788 | Val acc: 54.68% | LR: 0.000059
Epoch: 071 | MCC: 0.043309 | Train loss: 0.9814 | Train acc: 50.88% | Val loss: 0.9748 | Val acc: 54.87% | LR: 0.000058
Epoch: 072 | MCC: 0.039364 | Train loss: 0.9806 | Train acc: 51.00% | Val loss: 0.9744 | Val acc: 55.00% | LR: 0.000056
Epoch: 073 | MCC: 0.042067 | Train loss: 0.9815 | Train acc: 50.88% | Val loss: 0.9801 | Val acc: 55.25% | LR: 0.000055
Epoch: 074 | MCC: 0.041107 | Train loss: 0.9806 | Train acc: 50.95% | Val loss: 0.9744 | Val acc: 55.12% | LR: 0.000054
Epoch: 075 | MCC: 0.043980 | Train loss: 0.9810 | Train acc: 50.95% | Val loss: 0.9754 | Val acc: 55.36% | LR: 0.000053
Epoch: 076 | MCC: 0.045598 | Train loss: 0.9808 | Train acc: 50.97% | Val loss: 0.9749 | Val acc: 55.41% | LR: 0.000052
Epoch: 077 | MCC: 0.056721 | Train loss: 0.9816 | Train acc: 50.86% | Val loss: 0.9739 | Val acc: 55.91% | LR: 0.000051
Epoch: 078 | MCC: 0.044541 | Train loss: 0.9809 | Train acc: 50.89% | Val loss: 0.9731 | Val acc: 55.76% | LR: 0.000050
Epoch: 079 | MCC: 0.042788 | Train loss: 0.9808 | Train acc: 50.87% | Val loss: 0.9727 | Val acc: 55.37% | LR: 0.000049
Epoch: 080 | MCC: 0.043592 | Train loss: 0.9802 | Train acc: 50.98% | Val loss: 0.9729 | Val acc: 55.42% | LR: 0.000048
Epoch: 081 | MCC: 0.039580 | Train loss: 0.9801 | Train acc: 51.05% | Val loss: 0.9758 | Val acc: 55.09% | LR: 0.000046
Epoch: 082 | MCC: 0.040423 | Train loss: 0.9801 | Train acc: 50.97% | Val loss: 0.9749 | Val acc: 55.06% | LR: 0.000045
Epoch: 083 | MCC: 0.038251 | Train loss: 0.9811 | Train acc: 50.87% | Val loss: 0.9729 | Val acc: 55.15% | LR: 0.000044
Epoch: 084 | MCC: 0.032000 | Train loss: 0.9805 | Train acc: 50.95% | Val loss: 0.9722 | Val acc: 55.03% | LR: 0.000043
Epoch: 085 | MCC: 0.036967 | Train loss: 0.9810 | Train acc: 50.83% | Val loss: 0.9723 | Val acc: 55.14% | LR: 0.000042
Epoch: 086 | MCC: 0.037513 | Train loss: 0.9847 | Train acc: 50.97% | Val loss: 0.9727 | Val acc: 55.05% | LR: 0.000041
Epoch: 087 | MCC: 0.040811 | Train loss: 0.9845 | Train acc: 50.83% | Val loss: 0.9721 | Val acc: 55.05% | LR: 0.000040
Epoch: 088 | MCC: 0.038787 | Train loss: 0.9809 | Train acc: 50.84% | Val loss: 0.9722 | Val acc: 55.12% | LR: 0.000039
Epoch: 089 | MCC: 0.046149 | Train loss: 0.9806 | Train acc: 50.98% | Val loss: 0.9730 | Val acc: 55.35% | LR: 0.000038
Epoch: 090 | MCC: 0.037987 | Train loss: 0.9833 | Train acc: 50.92% | Val loss: 0.9714 | Val acc: 55.22% | LR: 0.000037
Epoch: 091 | MCC: 0.032572 | Train loss: 0.9795 | Train acc: 50.93% | Val loss: 0.9713 | Val acc: 54.94% | LR: 0.000036
Epoch: 092 | MCC: 0.040551 | Train loss: 0.9805 | Train acc: 50.97% | Val loss: 0.9705 | Val acc: 55.56% | LR: 0.000035
Epoch: 093 | MCC: 0.038039 | Train loss: 0.9804 | Train acc: 51.02% | Val loss: 0.9705 | Val acc: 55.25% | LR: 0.000034
Epoch: 094 | MCC: 0.034633 | Train loss: 0.9803 | Train acc: 50.91% | Val loss: 0.9712 | Val acc: 55.07% | LR: 0.000033
Epoch: 095 | MCC: 0.038137 | Train loss: 0.9844 | Train acc: 51.00% | Val loss: 0.9710 | Val acc: 55.13% | LR: 0.000032
Epoch: 096 | MCC: 0.035325 | Train loss: 0.9890 | Train acc: 51.04% | Val loss: 0.9700 | Val acc: 55.12% | LR: 0.000031
Epoch: 097 | MCC: 0.039926 | Train loss: 0.9851 | Train acc: 50.81% | Val loss: 0.9695 | Val acc: 55.50% | LR: 0.000030
Epoch: 098 | MCC: 0.038008 | Train loss: 0.9876 | Train acc: 51.12% | Val loss: 1.2158 | Val acc: 55.47% | LR: 0.000029
Epoch: 099 | MCC: 0.039150 | Train loss: 0.9807 | Train acc: 50.91% | Val loss: 0.9699 | Val acc: 55.52% | LR: 0.000028
Epoch: 100 | MCC: 0.039490 | Train loss: 0.9805 | Train acc: 50.83% | Val loss: 0.9700 | Val acc: 55.39% | LR: 0.000027
Epoch: 101 | MCC: 0.039219 | Train loss: 0.9804 | Train acc: 50.87% | Val loss: 0.9699 | Val acc: 55.42% | LR: 0.000026
Epoch: 102 | MCC: 0.038266 | Train loss: 0.9811 | Train acc: 50.89% | Val loss: 0.9700 | Val acc: 55.30% | LR: 0.000025
Epoch: 103 | MCC: 0.037726 | Train loss: 0.9797 | Train acc: 50.89% | Val loss: 0.9692 | Val acc: 55.41% | LR: 0.000024
Epoch: 104 | MCC: 0.039128 | Train loss: 0.9800 | Train acc: 50.90% | Val loss: 0.9692 | Val acc: 55.46% | LR: 0.000023
Epoch: 105 | MCC: 0.039490 | Train loss: 0.9794 | Train acc: 50.90% | Val loss: 0.9697 | Val acc: 55.39% | LR: 0.000022
Epoch: 106 | MCC: 0.039625 | Train loss: 0.9796 | Train acc: 51.00% | Val loss: 0.9696 | Val acc: 55.39% | LR: 0.000021
Epoch: 107 | MCC: 0.039634 | Train loss: 0.9796 | Train acc: 50.93% | Val loss: 0.9704 | Val acc: 55.45% | LR: 0.000020
Epoch: 108 | MCC: 0.040053 | Train loss: 0.9810 | Train acc: 50.78% | Val loss: 0.9692 | Val acc: 55.45% | LR: 0.000019
Epoch: 109 | MCC: 0.040761 | Train loss: 1.0055 | Train acc: 50.90% | Val loss: 0.9698 | Val acc: 55.53% | LR: 0.000019
Epoch: 110 | MCC: 0.039824 | Train loss: 0.9855 | Train acc: 51.02% | Val loss: 0.9685 | Val acc: 55.48% | LR: 0.000018
Epoch: 111 | MCC: 0.039824 | Train loss: 1.0771 | Train acc: 51.03% | Val loss: 0.9685 | Val acc: 55.48% | LR: 0.000017
Epoch: 112 | MCC: 0.040761 | Train loss: 1.0023 | Train acc: 51.03% | Val loss: 0.9685 | Val acc: 55.53% | LR: 0.000016
Epoch: 113 | MCC: 0.041248 | Train loss: 0.9814 | Train acc: 51.09% | Val loss: 0.9685 | Val acc: 55.59% | LR: 0.000015
Epoch: 114 | MCC: 0.042061 | Train loss: 0.9824 | Train acc: 51.27% | Val loss: 0.9681 | Val acc: 55.67% | LR: 0.000015
Epoch: 115 | MCC: 0.039128 | Train loss: 0.9909 | Train acc: 50.92% | Val loss: 0.9683 | Val acc: 55.46% | LR: 0.000014
Epoch: 116 | MCC: 0.039824 | Train loss: 0.9826 | Train acc: 51.04% | Val loss: 0.9680 | Val acc: 55.48% | LR: 0.000013
Epoch: 117 | MCC: 0.039035 | Train loss: 0.9896 | Train acc: 50.78% | Val loss: 0.9723 | Val acc: 55.40% | LR: 0.000013
Epoch: 118 | MCC: 0.042061 | Train loss: 0.9959 | Train acc: 50.86% | Val loss: 0.9681 | Val acc: 55.67% | LR: 0.000012
Epoch: 119 | MCC: 0.042061 | Train loss: 1.0335 | Train acc: 51.02% | Val loss: 0.9682 | Val acc: 55.67% | LR: 0.000011
Epoch: 120 | MCC: 0.042061 | Train loss: 0.9872 | Train acc: 50.74% | Val loss: 0.9682 | Val acc: 55.67% | LR: 0.000011
Epoch: 121 | MCC: 0.042131 | Train loss: 0.9808 | Train acc: 50.90% | Val loss: 0.9685 | Val acc: 55.64% | LR: 0.000010
Epoch: 122 | MCC: 0.042035 | Train loss: 1.0062 | Train acc: 50.77% | Val loss: 0.9686 | Val acc: 55.58% | LR: 0.000009
Epoch: 123 | MCC: 0.042061 | Train loss: 0.9910 | Train acc: 51.08% | Val loss: 0.9683 | Val acc: 55.67% | LR: 0.000009
Epoch: 124 | MCC: 0.041324 | Train loss: 0.9914 | Train acc: 50.73% | Val loss: 0.9683 | Val acc: 55.59% | LR: 0.000008
Epoch: 125 | MCC: 0.041324 | Train loss: 0.9795 | Train acc: 50.93% | Val loss: 0.9686 | Val acc: 55.59% | LR: 0.000008
Epoch: 126 | MCC: 0.042883 | Train loss: 0.9824 | Train acc: 51.22% | Val loss: 0.9684 | Val acc: 55.70% | LR: 0.000007
Epoch: 127 | MCC: 0.039418 | Train loss: 0.9810 | Train acc: 50.85% | Val loss: 0.9933 | Val acc: 55.55% | LR: 0.000007
Epoch: 128 | MCC: 0.041270 | Train loss: 0.9797 | Train acc: 51.01% | Val loss: 0.9888 | Val acc: 55.59% | LR: 0.000006
Epoch: 129 | MCC: 0.041500 | Train loss: 0.9803 | Train acc: 50.81% | Val loss: 0.9684 | Val acc: 55.65% | LR: 0.000006
Epoch: 130 | MCC: 0.040687 | Train loss: 0.9801 | Train acc: 50.90% | Val loss: 0.9685 | Val acc: 55.56% | LR: 0.000005
Epoch: 131 | MCC: 0.040538 | Train loss: 0.9790 | Train acc: 51.01% | Val loss: 0.9686 | Val acc: 55.50% | LR: 0.000005
Epoch: 132 | MCC: 0.041248 | Train loss: 0.9799 | Train acc: 50.96% | Val loss: 0.9683 | Val acc: 55.59% | LR: 0.000004
Epoch: 133 | MCC: 0.041248 | Train loss: 0.9799 | Train acc: 51.00% | Val loss: 0.9674 | Val acc: 55.59% | LR: 0.000004
Epoch: 134 | MCC: 0.039977 | Train loss: 0.9817 | Train acc: 50.76% | Val loss: 0.9698 | Val acc: 55.48% | LR: 0.000004
Epoch: 135 | MCC: 0.041248 | Train loss: 0.9805 | Train acc: 50.86% | Val loss: 0.9682 | Val acc: 55.59% | LR: 0.000003
Epoch: 136 | MCC: 0.040687 | Train loss: 0.9957 | Train acc: 50.88% | Val loss: 0.9683 | Val acc: 55.56% | LR: 0.000003
Epoch: 137 | MCC: 0.041500 | Train loss: 0.9797 | Train acc: 51.00% | Val loss: 0.9682 | Val acc: 55.65% | LR: 0.000003
Epoch: 138 | MCC: 0.041500 | Train loss: 0.9797 | Train acc: 50.97% | Val loss: 0.9682 | Val acc: 55.65% | LR: 0.000002
Epoch: 139 | MCC: 0.041634 | Train loss: 0.9804 | Train acc: 50.93% | Val loss: 0.9683 | Val acc: 55.65% | LR: 0.000002
Epoch: 140 | MCC: 0.041539 | Train loss: 0.9783 | Train acc: 50.99% | Val loss: 0.9683 | Val acc: 55.59% | LR: 0.000002
Epoch: 141 | MCC: 0.041634 | Train loss: 0.9790 | Train acc: 50.83% | Val loss: 0.9682 | Val acc: 55.65% | LR: 0.000002
Epoch: 142 | MCC: 0.041634 | Train loss: 0.9806 | Train acc: 51.01% | Val loss: 0.9682 | Val acc: 55.65% | LR: 0.000002
Epoch: 143 | MCC: 0.041634 | Train loss: 0.9797 | Train acc: 51.05% | Val loss: 0.9682 | Val acc: 55.65% | LR: 0.000001
Epoch: 144 | MCC: 0.041634 | Train loss: 0.9800 | Train acc: 50.87% | Val loss: 0.9682 | Val acc: 55.65% | LR: 0.000001
Epoch: 145 | MCC: 0.041500 | Train loss: 0.9827 | Train acc: 51.07% | Val loss: 0.9682 | Val acc: 55.65% | LR: 0.000001
Epoch: 146 | MCC: 0.041500 | Train loss: 0.9804 | Train acc: 51.06% | Val loss: 0.9683 | Val acc: 55.65% | LR: 0.000001
Epoch: 147 | MCC: 0.041500 | Train loss: 0.9799 | Train acc: 50.82% | Val loss: 0.9684 | Val acc: 55.65% | LR: 0.000001
Epoch: 148 | MCC: 0.042061 | Train loss: 0.9805 | Train acc: 50.94% | Val loss: 0.9678 | Val acc: 55.67% | LR: 0.000001
Epoch: 149 | MCC: 0.042061 | Train loss: 0.9801 | Train acc: 51.04% | Val loss: 0.9681 | Val acc: 55.67% | LR: 0.000001

[I 2025-10-05 09:14:55,564] Trial 18 finished with value: 0.04206083435565233 and parameters: {'lr': 0.00010735323059927405, 'hidden_size': 73, 'dropout': 0.467827072988595, 'weight_decay': 0.008990698707826155}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.034465 | Train loss: 1.0016 | Train acc: 49.71% | Val loss: 0.9979 | Val acc: 51.33% | LR: 0.000290
Epoch: 001 | MCC: 0.029600 | Train loss: 0.9977 | Train acc: 50.86% | Val loss: 0.9882 | Val acc: 53.79% | LR: 0.000290
Epoch: 002 | MCC: 0.029538 | Train loss: 1.0587 | Train acc: 50.61% | Val loss: 0.9817 | Val acc: 54.34% | LR: 0.000290
Epoch: 003 | MCC: 0.034827 | Train loss: 0.9923 | Train acc: 50.76% | Val loss: 0.9725 | Val acc: 54.92% | LR: 0.000290
Epoch: 004 | MCC: 0.034510 | Train loss: 0.9903 | Train acc: 50.82% | Val loss: 0.9577 | Val acc: 55.33% | LR: 0.000289
Epoch: 005 | MCC: 0.031007 | Train loss: 0.9849 | Train acc: 51.04% | Val loss: 0.9447 | Val acc: 55.40% | LR: 0.000289
Epoch: 006 | MCC: 0.022466 | Train loss: 0.9832 | Train acc: 50.96% | Val loss: 0.9479 | Val acc: 55.33% | LR: 0.000289
Epoch: 007 | MCC: 0.023625 | Train loss: 0.9846 | Train acc: 50.83% | Val loss: 0.9307 | Val acc: 55.62% | LR: 0.000288
Epoch: 008 | MCC: 0.019609 | Train loss: 0.9829 | Train acc: 50.96% | Val loss: 0.9279 | Val acc: 55.61% | LR: 0.000288
Epoch: 009 | MCC: 0.026282 | Train loss: 0.9829 | Train acc: 50.99% | Val loss: 0.9118 | Val acc: 55.90% | LR: 0.000287
Epoch: 010 | MCC: 0.035207 | Train loss: 0.9863 | Train acc: 50.95% | Val loss: 0.9156 | Val acc: 56.72% | LR: 0.000286
Epoch: 011 | MCC: 0.026022 | Train loss: 0.9839 | Train acc: 50.84% | Val loss: 0.9108 | Val acc: 55.23% | LR: 0.000286
Epoch: 012 | MCC: 0.022646 | Train loss: 0.9826 | Train acc: 50.89% | Val loss: 0.9256 | Val acc: 54.70% | LR: 0.000285
Epoch: 013 | MCC: 0.019766 | Train loss: 0.9868 | Train acc: 50.89% | Val loss: 0.9159 | Val acc: 55.05% | LR: 0.000284
Epoch: 014 | MCC: 0.007762 | Train loss: 0.9844 | Train acc: 50.86% | Val loss: 0.9119 | Val acc: 54.86% | LR: 0.000283
Epoch: 015 | MCC: 0.020455 | Train loss: 0.9860 | Train acc: 50.87% | Val loss: 0.9067 | Val acc: 55.17% | LR: 0.000282
Epoch: 016 | MCC: 0.021956 | Train loss: 0.9823 | Train acc: 50.97% | Val loss: 0.9193 | Val acc: 55.08% | LR: 0.000281
Epoch: 017 | MCC: 0.023991 | Train loss: 0.9821 | Train acc: 50.96% | Val loss: 0.9058 | Val acc: 55.08% | LR: 0.000280
Epoch: 018 | MCC: 0.024923 | Train loss: 0.9814 | Train acc: 50.95% | Val loss: 0.9073 | Val acc: 55.26% | LR: 0.000279
Epoch: 019 | MCC: 0.023755 | Train loss: 0.9823 | Train acc: 50.93% | Val loss: 0.9041 | Val acc: 55.15% | LR: 0.000278
Epoch: 020 | MCC: 0.018266 | Train loss: 0.9827 | Train acc: 50.94% | Val loss: 0.9033 | Val acc: 54.73% | LR: 0.000276
Epoch: 021 | MCC: 0.025423 | Train loss: 0.9806 | Train acc: 51.01% | Val loss: 0.9073 | Val acc: 54.77% | LR: 0.000275
Epoch: 022 | MCC: 0.011724 | Train loss: 0.9809 | Train acc: 50.99% | Val loss: 0.9115 | Val acc: 54.44% | LR: 0.000274
Epoch: 023 | MCC: 0.012731 | Train loss: 0.9829 | Train acc: 50.89% | Val loss: 0.9040 | Val acc: 54.74% | LR: 0.000272
Epoch: 024 | MCC: 0.020148 | Train loss: 0.9856 | Train acc: 50.94% | Val loss: 0.9029 | Val acc: 55.06% | LR: 0.000271
Epoch: 025 | MCC: 0.022924 | Train loss: 0.9800 | Train acc: 51.06% | Val loss: 0.9008 | Val acc: 55.24% | LR: 0.000269
Epoch: 026 | MCC: 0.015891 | Train loss: 0.9794 | Train acc: 51.07% | Val loss: 0.8993 | Val acc: 54.98% | LR: 0.000268
Epoch: 027 | MCC: 0.018105 | Train loss: 0.9809 | Train acc: 50.97% | Val loss: 0.8987 | Val acc: 55.16% | LR: 0.000266
Epoch: 028 | MCC: 0.013730 | Train loss: 0.9828 | Train acc: 50.88% | Val loss: 0.9007 | Val acc: 55.07% | LR: 0.000264
Epoch: 029 | MCC: 0.019995 | Train loss: 0.9824 | Train acc: 50.88% | Val loss: 0.9038 | Val acc: 55.17% | LR: 0.000263
Epoch: 030 | MCC: 0.022277 | Train loss: 0.9811 | Train acc: 51.00% | Val loss: 0.8962 | Val acc: 55.30% | LR: 0.000261
Epoch: 031 | MCC: 0.019685 | Train loss: 0.9803 | Train acc: 51.04% | Val loss: 0.8978 | Val acc: 55.26% | LR: 0.000259
Epoch: 032 | MCC: 0.014654 | Train loss: 0.9788 | Train acc: 51.16% | Val loss: 0.8977 | Val acc: 55.12% | LR: 0.000257
Epoch: 033 | MCC: -0.002708 | Train loss: 0.9808 | Train acc: 51.08% | Val loss: 0.8955 | Val acc: 55.15% | LR: 0.000255
Epoch: 034 | MCC: -0.010934 | Train loss: 0.9811 | Train acc: 50.95% | Val loss: 0.8980 | Val acc: 55.07% | LR: 0.000253
Epoch: 035 | MCC: -0.012714 | Train loss: 0.9803 | Train acc: 50.95% | Val loss: 0.8946 | Val acc: 55.24% | LR: 0.000251
Epoch: 036 | MCC: -0.009723 | Train loss: 0.9801 | Train acc: 51.05% | Val loss: 0.8997 | Val acc: 55.18% | LR: 0.000249
Epoch: 037 | MCC: -0.013968 | Train loss: 0.9776 | Train acc: 51.12% | Val loss: 0.8935 | Val acc: 55.19% | LR: 0.000247
Epoch: 038 | MCC: 0.014539 | Train loss: 0.9781 | Train acc: 51.13% | Val loss: 0.8899 | Val acc: 55.49% | LR: 0.000245
Epoch: 039 | MCC: -0.003941 | Train loss: 0.9816 | Train acc: 50.93% | Val loss: 0.8951 | Val acc: 55.22% | LR: 0.000242
Epoch: 040 | MCC: 0.007105 | Train loss: 0.9787 | Train acc: 51.13% | Val loss: 0.8948 | Val acc: 55.10% | LR: 0.000240
Epoch: 041 | MCC: 0.008928 | Train loss: 0.9805 | Train acc: 50.98% | Val loss: 0.8903 | Val acc: 55.43% | LR: 0.000238
Epoch: 042 | MCC: 0.014918 | Train loss: 0.9804 | Train acc: 51.00% | Val loss: 0.8867 | Val acc: 55.61% | LR: 0.000235
Epoch: 043 | MCC: -0.012402 | Train loss: 0.9802 | Train acc: 51.01% | Val loss: 0.8949 | Val acc: 55.30% | LR: 0.000233
Epoch: 044 | MCC: -0.012943 | Train loss: 0.9820 | Train acc: 51.00% | Val loss: 0.8975 | Val acc: 55.07% | LR: 0.000231
Epoch: 045 | MCC: -0.010091 | Train loss: 0.9795 | Train acc: 51.03% | Val loss: 0.8941 | Val acc: 55.29% | LR: 0.000228
Epoch: 046 | MCC: -0.013397 | Train loss: 0.9792 | Train acc: 51.10% | Val loss: 0.8960 | Val acc: 55.22% | LR: 0.000226
Epoch: 047 | MCC: -0.011171 | Train loss: 0.9785 | Train acc: 51.07% | Val loss: 0.8935 | Val acc: 55.30% | LR: 0.000223
Epoch: 048 | MCC: -0.010450 | Train loss: 0.9794 | Train acc: 51.03% | Val loss: 0.8910 | Val acc: 55.50% | LR: 0.000220
Epoch: 049 | MCC: -0.007833 | Train loss: 0.9779 | Train acc: 51.19% | Val loss: 0.8887 | Val acc: 55.62% | LR: 0.000218
Epoch: 050 | MCC: -0.004383 | Train loss: 0.9829 | Train acc: 50.90% | Val loss: 0.8805 | Val acc: 55.85% | LR: 0.000215
Epoch: 051 | MCC: -0.005634 | Train loss: 0.9796 | Train acc: 51.03% | Val loss: 0.9015 | Val acc: 55.69% | LR: 0.000213
Epoch: 052 | MCC: -0.007832 | Train loss: 0.9786 | Train acc: 51.02% | Val loss: 0.8952 | Val acc: 55.62% | LR: 0.000210
Epoch: 053 | MCC: -0.006836 | Train loss: 0.9785 | Train acc: 51.11% | Val loss: 0.9031 | Val acc: 55.36% | LR: 0.000207
Epoch: 054 | MCC: -0.008578 | Train loss: 0.9785 | Train acc: 51.07% | Val loss: 0.8984 | Val acc: 55.41% | LR: 0.000204
Epoch: 055 | MCC: -0.009297 | Train loss: 0.9795 | Train acc: 50.95% | Val loss: 0.8966 | Val acc: 55.19% | LR: 0.000202
Epoch: 056 | MCC: -0.003108 | Train loss: 0.9768 | Train acc: 51.21% | Val loss: 0.9014 | Val acc: 55.15% | LR: 0.000199
Epoch: 057 | MCC: 0.001412 | Train loss: 0.9774 | Train acc: 51.15% | Val loss: 0.8937 | Val acc: 55.75% | LR: 0.000196
Epoch: 058 | MCC: -0.005763 | Train loss: 0.9775 | Train acc: 51.17% | Val loss: 0.8950 | Val acc: 55.38% | LR: 0.000193
Epoch: 059 | MCC: -0.007935 | Train loss: 0.9806 | Train acc: 50.96% | Val loss: 0.8989 | Val acc: 54.95% | LR: 0.000190
Epoch: 060 | MCC: 0.002842 | Train loss: 0.9803 | Train acc: 50.96% | Val loss: 0.8937 | Val acc: 55.42% | LR: 0.000187
Epoch: 061 | MCC: -0.011174 | Train loss: 0.9765 | Train acc: 51.20% | Val loss: 0.8912 | Val acc: 55.36% | LR: 0.000184
Epoch: 062 | MCC: -0.003611 | Train loss: 0.9795 | Train acc: 50.98% | Val loss: 0.8997 | Val acc: 55.12% | LR: 0.000182
Epoch: 063 | MCC: -0.007968 | Train loss: 0.9774 | Train acc: 51.16% | Val loss: 0.8994 | Val acc: 54.93% | LR: 0.000179
Epoch: 064 | MCC: 0.000371 | Train loss: 0.9794 | Train acc: 51.05% | Val loss: 0.8932 | Val acc: 55.32% | LR: 0.000176
Epoch: 065 | MCC: 0.004921 | Train loss: 0.9777 | Train acc: 51.11% | Val loss: 0.8942 | Val acc: 55.51% | LR: 0.000173
Epoch: 066 | MCC: -0.004679 | Train loss: 0.9792 | Train acc: 51.02% | Val loss: 0.8967 | Val acc: 55.12% | LR: 0.000170
Epoch: 067 | MCC: -0.005819 | Train loss: 0.9780 | Train acc: 51.14% | Val loss: 0.8956 | Val acc: 55.15% | LR: 0.000167
Epoch: 068 | MCC: -0.004608 | Train loss: 0.9777 | Train acc: 51.15% | Val loss: 0.8911 | Val acc: 55.50% | LR: 0.000164
Epoch: 069 | MCC: -0.006503 | Train loss: 0.9771 | Train acc: 51.09% | Val loss: 0.8850 | Val acc: 55.70% | LR: 0.000161
Epoch: 070 | MCC: -0.009113 | Train loss: 0.9770 | Train acc: 51.10% | Val loss: 0.8748 | Val acc: 56.03% | LR: 0.000158
Epoch: 071 | MCC: -0.005297 | Train loss: 0.9784 | Train acc: 51.25% | Val loss: 0.8748 | Val acc: 56.23% | LR: 0.000155
Epoch: 072 | MCC: -0.011890 | Train loss: 0.9777 | Train acc: 51.18% | Val loss: 0.8817 | Val acc: 55.66% | LR: 0.000152
Epoch: 073 | MCC: -0.010914 | Train loss: 1.0003 | Train acc: 51.29% | Val loss: 0.8783 | Val acc: 55.93% | LR: 0.000149
Epoch: 074 | MCC: -0.008672 | Train loss: 0.9759 | Train acc: 51.28% | Val loss: 0.8737 | Val acc: 56.08% | LR: 0.000146
Epoch: 075 | MCC: -0.006419 | Train loss: 0.9820 | Train acc: 51.20% | Val loss: 0.8698 | Val acc: 56.30% | LR: 0.000143
Epoch: 076 | MCC: -0.009105 | Train loss: 0.9768 | Train acc: 51.19% | Val loss: 0.8770 | Val acc: 56.13% | LR: 0.000140
Epoch: 077 | MCC: -0.011263 | Train loss: 0.9783 | Train acc: 51.24% | Val loss: 0.8804 | Val acc: 55.81% | LR: 0.000137
Epoch: 078 | MCC: -0.007448 | Train loss: 0.9752 | Train acc: 51.23% | Val loss: 0.8819 | Val acc: 55.93% | LR: 0.000133
Epoch: 079 | MCC: -0.005539 | Train loss: 0.9762 | Train acc: 51.17% | Val loss: 0.8862 | Val acc: 55.76% | LR: 0.000130
Epoch: 080 | MCC: -0.002555 | Train loss: 0.9768 | Train acc: 51.18% | Val loss: 0.8860 | Val acc: 55.90% | LR: 0.000127
Epoch: 081 | MCC: -0.004289 | Train loss: 0.9764 | Train acc: 51.23% | Val loss: 0.8861 | Val acc: 55.99% | LR: 0.000124
Epoch: 082 | MCC: -0.004193 | Train loss: 0.9780 | Train acc: 51.20% | Val loss: 0.8879 | Val acc: 55.68% | LR: 0.000121
Epoch: 083 | MCC: -0.005803 | Train loss: 0.9737 | Train acc: 51.32% | Val loss: 0.8888 | Val acc: 55.55% | LR: 0.000118
Epoch: 084 | MCC: 0.003714 | Train loss: 0.9748 | Train acc: 51.25% | Val loss: 0.8850 | Val acc: 55.86% | LR: 0.000116
Epoch: 085 | MCC: -0.000726 | Train loss: 0.9756 | Train acc: 51.21% | Val loss: 0.8869 | Val acc: 55.61% | LR: 0.000113
Epoch: 086 | MCC: -0.000158 | Train loss: 0.9759 | Train acc: 51.27% | Val loss: 0.8877 | Val acc: 55.64% | LR: 0.000110
Epoch: 087 | MCC: -0.000646 | Train loss: 0.9759 | Train acc: 51.16% | Val loss: 0.8852 | Val acc: 55.61% | LR: 0.000107
Epoch: 088 | MCC: 0.001576 | Train loss: 0.9749 | Train acc: 51.19% | Val loss: 0.8852 | Val acc: 55.71% | LR: 0.000104
Epoch: 089 | MCC: 0.003546 | Train loss: 0.9748 | Train acc: 51.25% | Val loss: 0.8878 | Val acc: 55.78% | LR: 0.000101
Epoch: 090 | MCC: 0.002189 | Train loss: 0.9746 | Train acc: 51.24% | Val loss: 0.8875 | Val acc: 55.71% | LR: 0.000098
Epoch: 091 | MCC: -0.003878 | Train loss: 0.9742 | Train acc: 51.19% | Val loss: 0.8844 | Val acc: 55.56% | LR: 0.000095
Epoch: 092 | MCC: 0.001989 | Train loss: 0.9750 | Train acc: 51.28% | Val loss: 0.8863 | Val acc: 55.71% | LR: 0.000092
Epoch: 093 | MCC: 0.003663 | Train loss: 0.9751 | Train acc: 51.10% | Val loss: 0.8864 | Val acc: 55.78% | LR: 0.000090
Epoch: 094 | MCC: 0.001593 | Train loss: 0.9744 | Train acc: 51.19% | Val loss: 0.8834 | Val acc: 55.91% | LR: 0.000087
Epoch: 095 | MCC: 0.000361 | Train loss: 0.9739 | Train acc: 51.24% | Val loss: 0.8843 | Val acc: 55.83% | LR: 0.000084
Epoch: 096 | MCC: 0.003578 | Train loss: 0.9725 | Train acc: 51.30% | Val loss: 0.8850 | Val acc: 55.91% | LR: 0.000081
Epoch: 097 | MCC: -0.002121 | Train loss: 0.9728 | Train acc: 51.34% | Val loss: 0.8852 | Val acc: 55.71% | LR: 0.000079
Epoch: 098 | MCC: 0.000376 | Train loss: 0.9742 | Train acc: 51.27% | Val loss: 0.8811 | Val acc: 55.86% | LR: 0.000076
Epoch: 099 | MCC: -0.002558 | Train loss: 0.9749 | Train acc: 51.18% | Val loss: 0.8829 | Val acc: 55.83% | LR: 0.000073
Epoch: 100 | MCC: -0.001262 | Train loss: 0.9721 | Train acc: 51.30% | Val loss: 0.8821 | Val acc: 55.76% | LR: 0.000071
Epoch: 101 | MCC: -0.003101 | Train loss: 0.9734 | Train acc: 51.24% | Val loss: 0.8804 | Val acc: 55.73% | LR: 0.000068
Epoch: 102 | MCC: 0.000508 | Train loss: 0.9730 | Train acc: 51.33% | Val loss: 0.8832 | Val acc: 55.83% | LR: 0.000066
Epoch: 103 | MCC: 0.000009 | Train loss: 0.9719 | Train acc: 51.34% | Val loss: 0.8902 | Val acc: 55.83% | LR: 0.000063
Epoch: 104 | MCC: -0.002511 | Train loss: 0.9744 | Train acc: 51.30% | Val loss: 0.8906 | Val acc: 55.66% | LR: 0.000061
Epoch: 105 | MCC: 0.000915 | Train loss: 0.9730 | Train acc: 51.38% | Val loss: 0.8816 | Val acc: 55.83% | LR: 0.000058
Epoch: 106 | MCC: 0.000522 | Train loss: 0.9765 | Train acc: 51.24% | Val loss: 0.8815 | Val acc: 55.83% | LR: 0.000056
Epoch: 107 | MCC: 0.004014 | Train loss: 0.9727 | Train acc: 51.28% | Val loss: 0.8836 | Val acc: 55.86% | LR: 0.000053
Epoch: 108 | MCC: 0.004838 | Train loss: 0.9733 | Train acc: 51.44% | Val loss: 0.8834 | Val acc: 55.91% | LR: 0.000051
Epoch: 109 | MCC: 0.003072 | Train loss: 0.9739 | Train acc: 51.19% | Val loss: 0.8826 | Val acc: 55.83% | LR: 0.000049
Epoch: 110 | MCC: 0.003162 | Train loss: 0.9714 | Train acc: 51.41% | Val loss: 0.8822 | Val acc: 55.86% | LR: 0.000047
Epoch: 111 | MCC: 0.000607 | Train loss: 0.9716 | Train acc: 51.40% | Val loss: 0.8848 | Val acc: 55.78% | LR: 0.000044
Epoch: 112 | MCC: 0.001938 | Train loss: 0.9713 | Train acc: 51.33% | Val loss: 0.8844 | Val acc: 55.76% | LR: 0.000042
Epoch: 113 | MCC: 0.004494 | Train loss: 0.9782 | Train acc: 51.34% | Val loss: 0.8845 | Val acc: 55.88% | LR: 0.000040
Epoch: 114 | MCC: 0.001427 | Train loss: 0.9723 | Train acc: 51.38% | Val loss: 0.8831 | Val acc: 55.81% | LR: 0.000038
Epoch: 115 | MCC: 0.001472 | Train loss: 0.9726 | Train acc: 51.33% | Val loss: 0.8847 | Val acc: 55.81% | LR: 0.000036
Epoch: 116 | MCC: 0.001580 | Train loss: 0.9734 | Train acc: 51.21% | Val loss: 0.8841 | Val acc: 55.76% | LR: 0.000034
Epoch: 117 | MCC: 0.003070 | Train loss: 0.9722 | Train acc: 51.36% | Val loss: 0.8828 | Val acc: 55.88% | LR: 0.000032
Epoch: 118 | MCC: 0.002413 | Train loss: 0.9729 | Train acc: 51.25% | Val loss: 0.8834 | Val acc: 55.86% | LR: 0.000030
Epoch: 119 | MCC: 0.000819 | Train loss: 0.9706 | Train acc: 51.41% | Val loss: 0.8833 | Val acc: 55.78% | LR: 0.000029
Epoch: 120 | MCC: -0.000640 | Train loss: 0.9702 | Train acc: 51.40% | Val loss: 0.8836 | Val acc: 55.81% | LR: 0.000027
Epoch: 121 | MCC: -0.001699 | Train loss: 0.9718 | Train acc: 51.27% | Val loss: 0.8831 | Val acc: 55.76% | LR: 0.000025
Epoch: 122 | MCC: 0.000081 | Train loss: 0.9730 | Train acc: 51.22% | Val loss: 0.8820 | Val acc: 55.86% | LR: 0.000024
Epoch: 123 | MCC: -0.002274 | Train loss: 0.9722 | Train acc: 51.26% | Val loss: 0.8819 | Val acc: 55.73% | LR: 0.000022
Epoch: 124 | MCC: -0.003375 | Train loss: 0.9757 | Train acc: 51.31% | Val loss: 0.8815 | Val acc: 55.69% | LR: 0.000020
Epoch: 125 | MCC: -0.001745 | Train loss: 0.9718 | Train acc: 51.40% | Val loss: 0.8824 | Val acc: 55.76% | LR: 0.000019
Epoch: 126 | MCC: -0.003329 | Train loss: 0.9727 | Train acc: 51.32% | Val loss: 0.8819 | Val acc: 55.69% | LR: 0.000017
Epoch: 127 | MCC: -0.004833 | Train loss: 0.9719 | Train acc: 51.36% | Val loss: 0.8841 | Val acc: 55.64% | LR: 0.000016
Epoch: 128 | MCC: -0.000894 | Train loss: 0.9858 | Train acc: 51.23% | Val loss: 0.8823 | Val acc: 55.81% | LR: 0.000015
Epoch: 129 | MCC: -0.001765 | Train loss: 0.9709 | Train acc: 51.32% | Val loss: 0.8829 | Val acc: 55.76% | LR: 0.000014
Epoch: 130 | MCC: -0.001236 | Train loss: 0.9731 | Train acc: 51.36% | Val loss: 0.8852 | Val acc: 55.78% | LR: 0.000012
Epoch: 131 | MCC: -0.001765 | Train loss: 0.9746 | Train acc: 51.30% | Val loss: 0.8828 | Val acc: 55.76% | LR: 0.000011
Epoch: 132 | MCC: -0.003226 | Train loss: 0.9728 | Train acc: 51.22% | Val loss: 0.8850 | Val acc: 55.69% | LR: 0.000010
Epoch: 133 | MCC: -0.001765 | Train loss: 0.9718 | Train acc: 51.35% | Val loss: 0.8818 | Val acc: 55.76% | LR: 0.000009
Epoch: 134 | MCC: -0.003874 | Train loss: 0.9712 | Train acc: 51.28% | Val loss: 0.8821 | Val acc: 55.66% | LR: 0.000008
Epoch: 135 | MCC: -0.004851 | Train loss: 0.9756 | Train acc: 51.18% | Val loss: 0.8918 | Val acc: 55.64% | LR: 0.000007
Epoch: 136 | MCC: -0.003303 | Train loss: 0.9707 | Train acc: 51.29% | Val loss: 0.8819 | Val acc: 55.69% | LR: 0.000006
Epoch: 137 | MCC: -0.003874 | Train loss: 0.9713 | Train acc: 51.32% | Val loss: 0.8819 | Val acc: 55.66% | LR: 0.000006
Epoch: 138 | MCC: -0.001949 | Train loss: 0.9730 | Train acc: 51.19% | Val loss: 0.8821 | Val acc: 55.76% | LR: 0.000005
Epoch: 139 | MCC: -0.001949 | Train loss: 0.9715 | Train acc: 51.31% | Val loss: 0.8821 | Val acc: 55.76% | LR: 0.000004
Epoch: 140 | MCC: -0.002429 | Train loss: 0.9722 | Train acc: 51.27% | Val loss: 0.8830 | Val acc: 55.73% | LR: 0.000004
Epoch: 141 | MCC: -0.001949 | Train loss: 0.9691 | Train acc: 51.41% | Val loss: 0.8819 | Val acc: 55.76% | LR: 0.000003
Epoch: 142 | MCC: -0.001949 | Train loss: 0.9715 | Train acc: 51.31% | Val loss: 0.8820 | Val acc: 55.76% | LR: 0.000003
Epoch: 143 | MCC: -0.003407 | Train loss: 0.9704 | Train acc: 51.37% | Val loss: 0.8820 | Val acc: 55.71% | LR: 0.000002
Epoch: 144 | MCC: -0.002926 | Train loss: 0.9722 | Train acc: 51.23% | Val loss: 0.8820 | Val acc: 55.73% | LR: 0.000002
Epoch: 145 | MCC: -0.001949 | Train loss: 0.9715 | Train acc: 51.28% | Val loss: 0.8820 | Val acc: 55.76% | LR: 0.000002
Epoch: 146 | MCC: -0.001949 | Train loss: 0.9710 | Train acc: 51.22% | Val loss: 0.8820 | Val acc: 55.76% | LR: 0.000001
Epoch: 147 | MCC: -0.001995 | Train loss: 0.9710 | Train acc: 51.34% | Val loss: 0.8819 | Val acc: 55.76% | LR: 0.000001
Epoch: 148 | MCC: -0.001949 | Train loss: 0.9708 | Train acc: 51.25% | Val loss: 0.8819 | Val acc: 55.76% | LR: 0.000001
Epoch: 149 | MCC: -0.001949 | Train loss: 0.9710 | Train acc: 51.31% | Val loss: 0.8820 | Val acc: 55.76% | LR: 0.000001

[I 2025-10-05 09:17:16,837] Trial 19 finished with value: -0.0019486099481582642 and parameters: {'lr': 0.00029017420596770706, 'hidden_size': 94, 'dropout': 0.37918623305437177, 'weight_decay': 0.0012849761301601207}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: -0.015797 | Train loss: 1.0012 | Train acc: 49.90% | Val loss: 0.9968 | Val acc: 52.43% | LR: 0.000168
Epoch: 001 | MCC: -0.003675 | Train loss: 0.9996 | Train acc: 50.35% | Val loss: 0.9966 | Val acc: 52.68% | LR: 0.000168
Epoch: 002 | MCC: 0.008162 | Train loss: 0.9961 | Train acc: 50.57% | Val loss: 0.9962 | Val acc: 52.95% | LR: 0.000168
Epoch: 003 | MCC: 0.014538 | Train loss: 0.9920 | Train acc: 50.77% | Val loss: 0.9952 | Val acc: 53.40% | LR: 0.000168
Epoch: 004 | MCC: 0.005120 | Train loss: 0.9914 | Train acc: 50.75% | Val loss: 0.9928 | Val acc: 53.27% | LR: 0.000168
Epoch: 005 | MCC: 0.009143 | Train loss: 0.9961 | Train acc: 50.99% | Val loss: 0.9908 | Val acc: 53.49% | LR: 0.000168
Epoch: 006 | MCC: 0.018309 | Train loss: 0.9905 | Train acc: 50.83% | Val loss: 0.9892 | Val acc: 54.17% | LR: 0.000167
Epoch: 007 | MCC: 0.027241 | Train loss: 0.9888 | Train acc: 50.77% | Val loss: 0.9866 | Val acc: 54.67% | LR: 0.000167
Epoch: 008 | MCC: 0.024593 | Train loss: 0.9865 | Train acc: 50.92% | Val loss: 0.9821 | Val acc: 54.52% | LR: 0.000167
Epoch: 009 | MCC: 0.031400 | Train loss: 0.9860 | Train acc: 50.85% | Val loss: 0.9768 | Val acc: 54.97% | LR: 0.000166
Epoch: 010 | MCC: 0.023063 | Train loss: 0.9835 | Train acc: 50.88% | Val loss: 0.9720 | Val acc: 54.81% | LR: 0.000166
Epoch: 011 | MCC: 0.025186 | Train loss: 0.9828 | Train acc: 50.88% | Val loss: 0.9677 | Val acc: 55.14% | LR: 0.000166
Epoch: 012 | MCC: 0.026983 | Train loss: 0.9824 | Train acc: 50.98% | Val loss: 0.9609 | Val acc: 55.16% | LR: 0.000165
Epoch: 013 | MCC: 0.023281 | Train loss: 0.9830 | Train acc: 50.88% | Val loss: 0.9534 | Val acc: 55.24% | LR: 0.000165
Epoch: 014 | MCC: 0.029274 | Train loss: 0.9814 | Train acc: 50.98% | Val loss: 0.9459 | Val acc: 55.56% | LR: 0.000164
Epoch: 015 | MCC: 0.029359 | Train loss: 0.9816 | Train acc: 50.92% | Val loss: 0.9406 | Val acc: 55.43% | LR: 0.000164
Epoch: 016 | MCC: 0.009511 | Train loss: 0.9821 | Train acc: 50.89% | Val loss: 0.9364 | Val acc: 55.02% | LR: 0.000163
Epoch: 017 | MCC: 0.010804 | Train loss: 1.1108 | Train acc: 50.60% | Val loss: 0.9353 | Val acc: 55.10% | LR: 0.000162
Epoch: 018 | MCC: 0.012845 | Train loss: 0.9850 | Train acc: 51.03% | Val loss: 0.9370 | Val acc: 55.07% | LR: 0.000162
Epoch: 019 | MCC: 0.011870 | Train loss: 0.9835 | Train acc: 50.86% | Val loss: 0.9313 | Val acc: 55.16% | LR: 0.000161
Epoch: 020 | MCC: 0.014478 | Train loss: 0.9809 | Train acc: 50.95% | Val loss: 0.9271 | Val acc: 55.09% | LR: 0.000160
Epoch: 021 | MCC: 0.022001 | Train loss: 0.9816 | Train acc: 50.91% | Val loss: 0.9202 | Val acc: 55.62% | LR: 0.000160
Epoch: 022 | MCC: 0.016913 | Train loss: 0.9807 | Train acc: 50.91% | Val loss: 0.9183 | Val acc: 55.48% | LR: 0.000159
Epoch: 023 | MCC: 0.016877 | Train loss: 0.9807 | Train acc: 50.95% | Val loss: 0.9147 | Val acc: 55.61% | LR: 0.000158
Epoch: 024 | MCC: 0.020825 | Train loss: 0.9802 | Train acc: 50.96% | Val loss: 0.9115 | Val acc: 56.03% | LR: 0.000157
Epoch: 025 | MCC: 0.027065 | Train loss: 0.9790 | Train acc: 51.00% | Val loss: 0.9055 | Val acc: 56.22% | LR: 0.000156
Epoch: 026 | MCC: 0.042314 | Train loss: 0.9796 | Train acc: 51.02% | Val loss: 0.9027 | Val acc: 56.87% | LR: 0.000155
Epoch: 027 | MCC: 0.035074 | Train loss: 0.9785 | Train acc: 50.99% | Val loss: 0.8948 | Val acc: 56.88% | LR: 0.000154
Epoch: 028 | MCC: 0.033157 | Train loss: 0.9838 | Train acc: 50.98% | Val loss: 0.8917 | Val acc: 57.18% | LR: 0.000153
Epoch: 029 | MCC: 0.025846 | Train loss: 1.0087 | Train acc: 50.97% | Val loss: 0.8915 | Val acc: 57.22% | LR: 0.000152
Epoch: 030 | MCC: 0.029257 | Train loss: 0.9834 | Train acc: 51.01% | Val loss: 0.8874 | Val acc: 57.16% | LR: 0.000151
Epoch: 031 | MCC: 0.021057 | Train loss: 0.9796 | Train acc: 50.96% | Val loss: 0.8856 | Val acc: 56.72% | LR: 0.000150
Epoch: 032 | MCC: -0.000198 | Train loss: 0.9782 | Train acc: 51.09% | Val loss: 0.8782 | Val acc: 56.51% | LR: 0.000149
Epoch: 033 | MCC: 0.001556 | Train loss: 0.9783 | Train acc: 51.07% | Val loss: 0.8759 | Val acc: 56.41% | LR: 0.000148
Epoch: 034 | MCC: -0.002778 | Train loss: 0.9774 | Train acc: 51.10% | Val loss: 0.8729 | Val acc: 56.09% | LR: 0.000147
Epoch: 035 | MCC: -0.003039 | Train loss: 0.9760 | Train acc: 51.23% | Val loss: 0.8740 | Val acc: 56.24% | LR: 0.000146
Epoch: 036 | MCC: -0.001027 | Train loss: 0.9781 | Train acc: 51.22% | Val loss: 0.8743 | Val acc: 56.33% | LR: 0.000144
Epoch: 037 | MCC: 0.003147 | Train loss: 0.9750 | Train acc: 51.25% | Val loss: 0.8702 | Val acc: 57.32% | LR: 0.000143
Epoch: 038 | MCC: 0.027976 | Train loss: 0.9749 | Train acc: 51.07% | Val loss: 0.8680 | Val acc: 57.47% | LR: 0.000142
Epoch: 039 | MCC: 0.021114 | Train loss: 0.9744 | Train acc: 51.37% | Val loss: 0.8693 | Val acc: 57.15% | LR: 0.000141
Epoch: 040 | MCC: 0.016559 | Train loss: 0.9729 | Train acc: 51.51% | Val loss: 0.8518 | Val acc: 58.54% | LR: 0.000139
Epoch: 041 | MCC: 0.022133 | Train loss: 0.9841 | Train acc: 51.21% | Val loss: 0.8632 | Val acc: 57.64% | LR: 0.000138
Epoch: 042 | MCC: 0.027758 | Train loss: 1.0010 | Train acc: 51.73% | Val loss: 0.8485 | Val acc: 58.93% | LR: 0.000137
Epoch: 043 | MCC: 0.026911 | Train loss: 0.9707 | Train acc: 51.93% | Val loss: 0.8416 | Val acc: 58.74% | LR: 0.000135
Epoch: 044 | MCC: 0.020869 | Train loss: 0.9718 | Train acc: 51.26% | Val loss: 0.8605 | Val acc: 57.25% | LR: 0.000134
Epoch: 045 | MCC: 0.025342 | Train loss: 0.9716 | Train acc: 51.39% | Val loss: 0.8438 | Val acc: 58.42% | LR: 0.000132
Epoch: 046 | MCC: 0.024984 | Train loss: 0.9700 | Train acc: 51.69% | Val loss: 0.8461 | Val acc: 58.22% | LR: 0.000131
Epoch: 047 | MCC: 0.030346 | Train loss: 0.9707 | Train acc: 51.80% | Val loss: 0.8316 | Val acc: 59.15% | LR: 0.000129
Epoch: 048 | MCC: 0.029068 | Train loss: 0.9856 | Train acc: 51.91% | Val loss: 0.8234 | Val acc: 59.37% | LR: 0.000128
Epoch: 049 | MCC: 0.034183 | Train loss: 0.9753 | Train acc: 52.02% | Val loss: 0.8262 | Val acc: 59.52% | LR: 0.000126
Epoch: 050 | MCC: 0.033507 | Train loss: 0.9690 | Train acc: 51.98% | Val loss: 0.8326 | Val acc: 59.20% | LR: 0.000125
Epoch: 051 | MCC: 0.034206 | Train loss: 0.9688 | Train acc: 52.00% | Val loss: 0.8293 | Val acc: 59.30% | LR: 0.000123
Epoch: 052 | MCC: 0.050017 | Train loss: 0.9693 | Train acc: 52.02% | Val loss: 0.8381 | Val acc: 58.66% | LR: 0.000122
Epoch: 053 | MCC: 0.025389 | Train loss: 0.9710 | Train acc: 51.87% | Val loss: 0.8450 | Val acc: 58.21% | LR: 0.000120
Epoch: 054 | MCC: 0.019620 | Train loss: 0.9665 | Train acc: 52.20% | Val loss: 0.8442 | Val acc: 58.30% | LR: 0.000119
Epoch: 055 | MCC: 0.070608 | Train loss: 0.9684 | Train acc: 52.07% | Val loss: 0.8354 | Val acc: 59.35% | LR: 0.000117
Epoch: 056 | MCC: 0.024430 | Train loss: 0.9668 | Train acc: 52.14% | Val loss: 0.8527 | Val acc: 58.01% | LR: 0.000115
Epoch: 057 | MCC: 0.025547 | Train loss: 0.9676 | Train acc: 52.14% | Val loss: 0.8507 | Val acc: 58.03% | LR: 0.000114
Epoch: 058 | MCC: 0.047668 | Train loss: 0.9724 | Train acc: 52.14% | Val loss: 0.8342 | Val acc: 59.33% | LR: 0.000112
Epoch: 059 | MCC: 0.014877 | Train loss: 0.9668 | Train acc: 52.18% | Val loss: 0.8442 | Val acc: 58.41% | LR: 0.000110
Epoch: 060 | MCC: 0.014316 | Train loss: 0.9709 | Train acc: 52.09% | Val loss: 0.8599 | Val acc: 57.63% | LR: 0.000109
Epoch: 061 | MCC: 0.039523 | Train loss: 0.9667 | Train acc: 52.06% | Val loss: 0.8305 | Val acc: 59.44% | LR: 0.000107
Epoch: 062 | MCC: 0.014624 | Train loss: 0.9653 | Train acc: 52.20% | Val loss: 0.8586 | Val acc: 57.80% | LR: 0.000105
Epoch: 063 | MCC: 0.023231 | Train loss: 0.9665 | Train acc: 52.09% | Val loss: 0.8764 | Val acc: 58.07% | LR: 0.000104
Epoch: 064 | MCC: 0.053853 | Train loss: 0.9653 | Train acc: 52.11% | Val loss: 0.8526 | Val acc: 58.25% | LR: 0.000102
Epoch: 065 | MCC: 0.058921 | Train loss: 0.9635 | Train acc: 52.21% | Val loss: 0.8303 | Val acc: 59.35% | LR: 0.000100
Epoch: 066 | MCC: 0.021915 | Train loss: 0.9636 | Train acc: 52.18% | Val loss: 0.8419 | Val acc: 58.41% | LR: 0.000099
Epoch: 067 | MCC: 0.042091 | Train loss: 0.9717 | Train acc: 52.12% | Val loss: 0.8670 | Val acc: 57.10% | LR: 0.000097
Epoch: 068 | MCC: 0.050959 | Train loss: 0.9762 | Train acc: 51.94% | Val loss: 0.8575 | Val acc: 57.76% | LR: 0.000095
Epoch: 069 | MCC: 0.058185 | Train loss: 0.9735 | Train acc: 52.13% | Val loss: 0.8336 | Val acc: 59.04% | LR: 0.000093
Epoch: 070 | MCC: 0.047845 | Train loss: 0.9665 | Train acc: 52.09% | Val loss: 0.8337 | Val acc: 58.75% | LR: 0.000092
Epoch: 071 | MCC: 0.054124 | Train loss: 0.9637 | Train acc: 52.21% | Val loss: 0.8319 | Val acc: 58.88% | LR: 0.000090
Epoch: 072 | MCC: 0.026324 | Train loss: 0.9615 | Train acc: 52.25% | Val loss: 0.8519 | Val acc: 58.05% | LR: 0.000088
Epoch: 073 | MCC: 0.049531 | Train loss: 0.9644 | Train acc: 52.08% | Val loss: 0.8301 | Val acc: 58.78% | LR: 0.000086
Epoch: 074 | MCC: 0.025530 | Train loss: 0.9624 | Train acc: 52.17% | Val loss: 0.8390 | Val acc: 58.82% | LR: 0.000085
Epoch: 075 | MCC: 0.026965 | Train loss: 0.9632 | Train acc: 52.17% | Val loss: 0.8444 | Val acc: 58.61% | LR: 0.000083
Epoch: 076 | MCC: 0.023741 | Train loss: 0.9642 | Train acc: 52.23% | Val loss: 0.8393 | Val acc: 58.70% | LR: 0.000081
Epoch: 077 | MCC: 0.020648 | Train loss: 0.9622 | Train acc: 52.33% | Val loss: 0.8376 | Val acc: 58.63% | LR: 0.000079
Epoch: 078 | MCC: 0.022953 | Train loss: 0.9632 | Train acc: 52.21% | Val loss: 0.8402 | Val acc: 58.56% | LR: 0.000078
Epoch: 079 | MCC: 0.021426 | Train loss: 0.9648 | Train acc: 52.20% | Val loss: 0.8454 | Val acc: 58.39% | LR: 0.000076
Epoch: 080 | MCC: 0.024354 | Train loss: 0.9609 | Train acc: 52.34% | Val loss: 0.8427 | Val acc: 58.46% | LR: 0.000074
Epoch: 081 | MCC: 0.026477 | Train loss: 0.9628 | Train acc: 52.23% | Val loss: 0.8416 | Val acc: 58.54% | LR: 0.000072
Epoch: 082 | MCC: 0.053833 | Train loss: 0.9614 | Train acc: 52.23% | Val loss: 0.8335 | Val acc: 58.93% | LR: 0.000071
Epoch: 083 | MCC: 0.025346 | Train loss: 0.9582 | Train acc: 52.35% | Val loss: 0.8428 | Val acc: 58.58% | LR: 0.000069
Epoch: 084 | MCC: 0.022098 | Train loss: 0.9615 | Train acc: 52.19% | Val loss: 0.8456 | Val acc: 58.29% | LR: 0.000067
Epoch: 085 | MCC: 0.051085 | Train loss: 0.9652 | Train acc: 52.23% | Val loss: 0.8372 | Val acc: 58.74% | LR: 0.000066
Epoch: 086 | MCC: 0.062318 | Train loss: 0.9637 | Train acc: 52.27% | Val loss: 0.8412 | Val acc: 58.67% | LR: 0.000064
Epoch: 087 | MCC: 0.023129 | Train loss: 0.9614 | Train acc: 52.24% | Val loss: 0.8455 | Val acc: 58.45% | LR: 0.000062
Epoch: 088 | MCC: 0.023990 | Train loss: 0.9612 | Train acc: 52.20% | Val loss: 0.8448 | Val acc: 58.48% | LR: 0.000060
Epoch: 089 | MCC: 0.023507 | Train loss: 0.9601 | Train acc: 52.25% | Val loss: 0.8360 | Val acc: 58.78% | LR: 0.000059
Epoch: 090 | MCC: 0.022943 | Train loss: 0.9625 | Train acc: 52.15% | Val loss: 0.8457 | Val acc: 58.36% | LR: 0.000057
Epoch: 091 | MCC: 0.022364 | Train loss: 0.9613 | Train acc: 52.22% | Val loss: 0.8397 | Val acc: 58.56% | LR: 0.000055
Epoch: 092 | MCC: 0.022687 | Train loss: 0.9604 | Train acc: 52.23% | Val loss: 0.8435 | Val acc: 58.53% | LR: 0.000054
Epoch: 093 | MCC: 0.023656 | Train loss: 0.9751 | Train acc: 52.18% | Val loss: 0.8459 | Val acc: 58.42% | LR: 0.000052
Epoch: 094 | MCC: 0.022759 | Train loss: 0.9600 | Train acc: 52.24% | Val loss: 0.8382 | Val acc: 58.63% | LR: 0.000051
Epoch: 095 | MCC: 0.031755 | Train loss: 0.9827 | Train acc: 52.20% | Val loss: 0.8407 | Val acc: 58.91% | LR: 0.000049
Epoch: 096 | MCC: 0.024484 | Train loss: 0.9629 | Train acc: 52.15% | Val loss: 0.8386 | Val acc: 58.63% | LR: 0.000047
Epoch: 097 | MCC: 0.025350 | Train loss: 0.9593 | Train acc: 52.32% | Val loss: 0.8352 | Val acc: 58.80% | LR: 0.000046
Epoch: 098 | MCC: 0.025122 | Train loss: 0.9629 | Train acc: 52.11% | Val loss: 0.8358 | Val acc: 58.80% | LR: 0.000044
Epoch: 099 | MCC: 0.025118 | Train loss: 0.9589 | Train acc: 52.34% | Val loss: 0.8388 | Val acc: 58.70% | LR: 0.000043
Epoch: 100 | MCC: 0.024210 | Train loss: 0.9679 | Train acc: 52.45% | Val loss: 0.8401 | Val acc: 58.65% | LR: 0.000041
Epoch: 101 | MCC: 0.023270 | Train loss: 0.9621 | Train acc: 52.20% | Val loss: 0.8408 | Val acc: 58.58% | LR: 0.000040
Epoch: 102 | MCC: 0.023740 | Train loss: 0.9616 | Train acc: 52.22% | Val loss: 0.8393 | Val acc: 58.65% | LR: 0.000038
Epoch: 103 | MCC: 0.027894 | Train loss: 0.9591 | Train acc: 52.32% | Val loss: 0.8357 | Val acc: 58.92% | LR: 0.000037
Epoch: 104 | MCC: 0.025270 | Train loss: 0.9638 | Train acc: 52.27% | Val loss: 0.8414 | Val acc: 58.70% | LR: 0.000035
Epoch: 105 | MCC: 0.023366 | Train loss: 0.9752 | Train acc: 52.25% | Val loss: 0.8387 | Val acc: 58.68% | LR: 0.000034
Epoch: 106 | MCC: 0.021562 | Train loss: 0.9602 | Train acc: 52.30% | Val loss: 0.8419 | Val acc: 58.41% | LR: 0.000033
Epoch: 107 | MCC: 0.025658 | Train loss: 0.9603 | Train acc: 52.25% | Val loss: 0.8395 | Val acc: 58.75% | LR: 0.000031
Epoch: 108 | MCC: 0.023951 | Train loss: 0.9568 | Train acc: 52.41% | Val loss: 0.8389 | Val acc: 58.70% | LR: 0.000030
Epoch: 109 | MCC: 0.022905 | Train loss: 0.9612 | Train acc: 52.20% | Val loss: 0.8394 | Val acc: 58.65% | LR: 0.000029
Epoch: 110 | MCC: 0.024061 | Train loss: 0.9585 | Train acc: 52.36% | Val loss: 0.8412 | Val acc: 58.61% | LR: 0.000027
Epoch: 111 | MCC: 0.023214 | Train loss: 0.9835 | Train acc: 52.36% | Val loss: 0.8397 | Val acc: 58.61% | LR: 0.000026
Epoch: 112 | MCC: 0.022757 | Train loss: 0.9882 | Train acc: 52.24% | Val loss: 0.8400 | Val acc: 58.58% | LR: 0.000025
Epoch: 113 | MCC: 0.022793 | Train loss: 0.9671 | Train acc: 52.27% | Val loss: 0.8412 | Val acc: 58.61% | LR: 0.000024
Epoch: 114 | MCC: 0.022584 | Train loss: 0.9596 | Train acc: 52.27% | Val loss: 0.8392 | Val acc: 58.65% | LR: 0.000022
Epoch: 115 | MCC: 0.026401 | Train loss: 0.9593 | Train acc: 52.29% | Val loss: 0.8362 | Val acc: 58.87% | LR: 0.000021
Epoch: 116 | MCC: 0.024099 | Train loss: 0.9714 | Train acc: 52.26% | Val loss: 0.8362 | Val acc: 58.78% | LR: 0.000020
Epoch: 117 | MCC: 0.025886 | Train loss: 0.9609 | Train acc: 52.25% | Val loss: 0.8405 | Val acc: 58.68% | LR: 0.000019
Epoch: 118 | MCC: 0.025014 | Train loss: 0.9683 | Train acc: 52.21% | Val loss: 0.8380 | Val acc: 58.78% | LR: 0.000018
Epoch: 119 | MCC: 0.019961 | Train loss: 0.9597 | Train acc: 52.30% | Val loss: 0.8423 | Val acc: 58.41% | LR: 0.000017
Epoch: 120 | MCC: 0.020317 | Train loss: 0.9600 | Train acc: 52.26% | Val loss: 0.8405 | Val acc: 58.48% | LR: 0.000016
Epoch: 121 | MCC: 0.022572 | Train loss: 0.9599 | Train acc: 52.24% | Val loss: 0.8391 | Val acc: 58.68% | LR: 0.000015
Epoch: 122 | MCC: 0.022770 | Train loss: 0.9586 | Train acc: 52.35% | Val loss: 0.8402 | Val acc: 58.63% | LR: 0.000014

[I 2025-10-05 09:19:32,932] Trial 20 finished with value: 0.023085459135472775 and parameters: {'lr': 0.0001682330079703093, 'hidden_size': 120, 'dropout': 0.318804771961176, 'weight_decay': 0.039894776737215136}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.007572 | Train loss: 1.0002 | Train acc: 50.26% | Val loss: 0.9863 | Val acc: 54.79% | LR: 0.000653
Epoch: 001 | MCC: 0.010335 | Train loss: 0.9927 | Train acc: 50.91% | Val loss: 0.9737 | Val acc: 54.39% | LR: 0.000653
Epoch: 002 | MCC: 0.014297 | Train loss: 0.9872 | Train acc: 50.82% | Val loss: 0.9618 | Val acc: 54.56% | LR: 0.000653
Epoch: 003 | MCC: 0.020713 | Train loss: 0.9872 | Train acc: 51.01% | Val loss: 0.9489 | Val acc: 55.01% | LR: 0.000652
Epoch: 004 | MCC: 0.015045 | Train loss: 0.9854 | Train acc: 50.93% | Val loss: 0.9319 | Val acc: 55.13% | LR: 0.000652
Epoch: 005 | MCC: 0.018205 | Train loss: 0.9842 | Train acc: 50.91% | Val loss: 0.9266 | Val acc: 55.48% | LR: 0.000651
Epoch: 006 | MCC: 0.021676 | Train loss: 0.9840 | Train acc: 50.89% | Val loss: 0.9166 | Val acc: 55.70% | LR: 0.000650
Epoch: 007 | MCC: 0.036820 | Train loss: 0.9821 | Train acc: 50.96% | Val loss: 0.8995 | Val acc: 57.04% | LR: 0.000649
Epoch: 008 | MCC: 0.035685 | Train loss: 0.9839 | Train acc: 50.94% | Val loss: 0.8920 | Val acc: 57.39% | LR: 0.000648
Epoch: 009 | MCC: 0.018796 | Train loss: 0.9820 | Train acc: 50.98% | Val loss: 0.8841 | Val acc: 56.35% | LR: 0.000646
Epoch: 010 | MCC: 0.016316 | Train loss: 0.9786 | Train acc: 51.20% | Val loss: 0.8516 | Val acc: 58.57% | LR: 0.000645
Epoch: 011 | MCC: 0.017556 | Train loss: 0.9786 | Train acc: 51.15% | Val loss: 0.8400 | Val acc: 58.57% | LR: 0.000643
Epoch: 012 | MCC: -0.007829 | Train loss: 0.9774 | Train acc: 51.14% | Val loss: 0.8774 | Val acc: 56.43% | LR: 0.000641
Epoch: 013 | MCC: 0.013673 | Train loss: 0.9767 | Train acc: 51.16% | Val loss: 0.8412 | Val acc: 58.53% | LR: 0.000640
Epoch: 014 | MCC: 0.018205 | Train loss: 0.9752 | Train acc: 51.35% | Val loss: 0.8896 | Val acc: 55.65% | LR: 0.000637
Epoch: 015 | MCC: 0.032463 | Train loss: 0.9899 | Train acc: 50.31% | Val loss: 0.9312 | Val acc: 54.90% | LR: 0.000635
Epoch: 016 | MCC: 0.066956 | Train loss: 0.9792 | Train acc: 51.31% | Val loss: 0.8735 | Val acc: 58.23% | LR: 0.000633
Epoch: 017 | MCC: 0.072289 | Train loss: 0.9763 | Train acc: 51.08% | Val loss: 0.8556 | Val acc: 58.17% | LR: 0.000631
Epoch: 018 | MCC: 0.061936 | Train loss: 0.9758 | Train acc: 51.19% | Val loss: 0.8497 | Val acc: 58.11% | LR: 0.000628
Epoch: 019 | MCC: 0.057309 | Train loss: 0.9747 | Train acc: 51.11% | Val loss: 0.8577 | Val acc: 57.68% | LR: 0.000625
Epoch: 020 | MCC: 0.055635 | Train loss: 0.9767 | Train acc: 51.21% | Val loss: 0.8357 | Val acc: 58.71% | LR: 0.000622
Epoch: 021 | MCC: 0.040449 | Train loss: 0.9719 | Train acc: 51.79% | Val loss: 0.8521 | Val acc: 57.92% | LR: 0.000619
Epoch: 022 | MCC: 0.028573 | Train loss: 0.9708 | Train acc: 52.05% | Val loss: 0.8349 | Val acc: 58.88% | LR: 0.000616
Epoch: 023 | MCC: 0.031883 | Train loss: 0.9710 | Train acc: 52.10% | Val loss: 0.8488 | Val acc: 57.68% | LR: 0.000613
Epoch: 024 | MCC: 0.061139 | Train loss: 0.9746 | Train acc: 51.71% | Val loss: 0.8542 | Val acc: 57.62% | LR: 0.000610
Epoch: 025 | MCC: 0.021604 | Train loss: 0.9726 | Train acc: 51.80% | Val loss: 0.8770 | Val acc: 56.66% | LR: 0.000606
Epoch: 026 | MCC: 0.019870 | Train loss: 0.9706 | Train acc: 51.90% | Val loss: 0.8538 | Val acc: 57.65% | LR: 0.000603
Epoch: 027 | MCC: 0.026007 | Train loss: 0.9695 | Train acc: 51.98% | Val loss: 0.8565 | Val acc: 58.20% | LR: 0.000599
Epoch: 028 | MCC: 0.055192 | Train loss: 0.9720 | Train acc: 51.85% | Val loss: 0.8158 | Val acc: 59.99% | LR: 0.000595
Epoch: 029 | MCC: 0.051886 | Train loss: 1.0133 | Train acc: 51.76% | Val loss: 0.8519 | Val acc: 58.55% | LR: 0.000591
Epoch: 030 | MCC: 0.060414 | Train loss: 0.9732 | Train acc: 51.86% | Val loss: 0.8562 | Val acc: 57.72% | LR: 0.000587
Epoch: 031 | MCC: 0.027976 | Train loss: 0.9706 | Train acc: 51.95% | Val loss: 0.8779 | Val acc: 56.79% | LR: 0.000583
Epoch: 032 | MCC: 0.022265 | Train loss: 0.9717 | Train acc: 51.79% | Val loss: 0.8573 | Val acc: 57.82% | LR: 0.000579
Epoch: 033 | MCC: 0.062350 | Train loss: 0.9696 | Train acc: 51.86% | Val loss: 0.8458 | Val acc: 58.14% | LR: 0.000574
Epoch: 034 | MCC: 0.066292 | Train loss: 0.9682 | Train acc: 51.93% | Val loss: 0.8320 | Val acc: 58.88% | LR: 0.000570
Epoch: 035 | MCC: 0.054587 | Train loss: 0.9699 | Train acc: 51.80% | Val loss: 0.8412 | Val acc: 58.55% | LR: 0.000565
Epoch: 036 | MCC: 0.018724 | Train loss: 0.9650 | Train acc: 52.08% | Val loss: 0.8676 | Val acc: 56.85% | LR: 0.000560
Epoch: 037 | MCC: 0.042639 | Train loss: 0.9657 | Train acc: 52.13% | Val loss: 0.8477 | Val acc: 58.29% | LR: 0.000555
Epoch: 038 | MCC: 0.046951 | Train loss: 0.9711 | Train acc: 51.73% | Val loss: 0.8565 | Val acc: 57.52% | LR: 0.000551
Epoch: 039 | MCC: 0.032480 | Train loss: 0.9697 | Train acc: 51.75% | Val loss: 0.8822 | Val acc: 56.33% | LR: 0.000545
Epoch: 040 | MCC: 0.054123 | Train loss: 0.9628 | Train acc: 52.16% | Val loss: 0.8410 | Val acc: 58.54% | LR: 0.000540
Epoch: 041 | MCC: 0.044238 | Train loss: 0.9683 | Train acc: 51.87% | Val loss: 0.8526 | Val acc: 57.73% | LR: 0.000535
Epoch: 042 | MCC: 0.038861 | Train loss: 0.9644 | Train acc: 52.02% | Val loss: 0.8691 | Val acc: 58.40% | LR: 0.000530
Epoch: 043 | MCC: 0.036685 | Train loss: 0.9642 | Train acc: 51.98% | Val loss: 0.8753 | Val acc: 57.97% | LR: 0.000524
Epoch: 044 | MCC: 0.056596 | Train loss: 0.9620 | Train acc: 52.13% | Val loss: 0.8307 | Val acc: 58.94% | LR: 0.000519
Epoch: 045 | MCC: 0.043026 | Train loss: 0.9691 | Train acc: 51.78% | Val loss: 0.8678 | Val acc: 57.30% | LR: 0.000513
Epoch: 046 | MCC: 0.024204 | Train loss: 0.9679 | Train acc: 51.89% | Val loss: 0.8836 | Val acc: 56.00% | LR: 0.000508
Epoch: 047 | MCC: 0.036625 | Train loss: 0.9716 | Train acc: 51.67% | Val loss: 0.8596 | Val acc: 57.08% | LR: 0.000502
Epoch: 048 | MCC: 0.039723 | Train loss: 0.9634 | Train acc: 52.13% | Val loss: 0.8478 | Val acc: 58.34% | LR: 0.000496
Epoch: 049 | MCC: 0.030539 | Train loss: 0.9646 | Train acc: 52.07% | Val loss: 0.8417 | Val acc: 58.20% | LR: 0.000490
Epoch: 050 | MCC: 0.032651 | Train loss: 0.9623 | Train acc: 52.10% | Val loss: 0.8312 | Val acc: 59.27% | LR: 0.000484
Epoch: 051 | MCC: 0.039852 | Train loss: 0.9634 | Train acc: 52.07% | Val loss: 0.8935 | Val acc: 59.87% | LR: 0.000478
Epoch: 052 | MCC: 0.044830 | Train loss: 0.9623 | Train acc: 52.13% | Val loss: 0.8265 | Val acc: 59.24% | LR: 0.000472
Epoch: 053 | MCC: 0.047639 | Train loss: 0.9619 | Train acc: 52.21% | Val loss: 0.8210 | Val acc: 59.40% | LR: 0.000466
Epoch: 054 | MCC: 0.046280 | Train loss: 0.9628 | Train acc: 52.10% | Val loss: 0.8266 | Val acc: 59.24% | LR: 0.000460
Epoch: 055 | MCC: 0.028178 | Train loss: 0.9593 | Train acc: 52.24% | Val loss: 0.8295 | Val acc: 58.97% | LR: 0.000454
Epoch: 056 | MCC: 0.047999 | Train loss: 0.9612 | Train acc: 52.17% | Val loss: 0.8145 | Val acc: 59.74% | LR: 0.000447
Epoch: 057 | MCC: 0.000237 | Train loss: 0.9609 | Train acc: 52.18% | Val loss: 0.8564 | Val acc: 57.44% | LR: 0.000441
Epoch: 058 | MCC: 0.015208 | Train loss: 0.9659 | Train acc: 52.00% | Val loss: 0.8523 | Val acc: 57.83% | LR: 0.000434
Epoch: 059 | MCC: -0.007820 | Train loss: 0.9623 | Train acc: 52.10% | Val loss: 0.8521 | Val acc: 57.64% | LR: 0.000428
Epoch: 060 | MCC: -0.004371 | Train loss: 0.9614 | Train acc: 52.15% | Val loss: 0.8469 | Val acc: 58.12% | LR: 0.000421
Epoch: 061 | MCC: -0.000207 | Train loss: 0.9600 | Train acc: 52.15% | Val loss: 0.8412 | Val acc: 58.19% | LR: 0.000415
Epoch: 062 | MCC: 0.002601 | Train loss: 0.9585 | Train acc: 52.29% | Val loss: 0.8359 | Val acc: 58.83% | LR: 0.000408
Epoch: 063 | MCC: 0.016798 | Train loss: 0.9598 | Train acc: 52.20% | Val loss: 0.8308 | Val acc: 58.68% | LR: 0.000402
Epoch: 064 | MCC: 0.017038 | Train loss: 0.9588 | Train acc: 52.23% | Val loss: 0.8356 | Val acc: 59.25% | LR: 0.000395
Epoch: 065 | MCC: 0.016965 | Train loss: 0.9608 | Train acc: 52.13% | Val loss: 0.8260 | Val acc: 59.31% | LR: 0.000388
Epoch: 066 | MCC: 0.031722 | Train loss: 0.9607 | Train acc: 52.30% | Val loss: 0.8272 | Val acc: 59.27% | LR: 0.000382
Epoch: 067 | MCC: 0.023288 | Train loss: 0.9615 | Train acc: 52.26% | Val loss: 0.8403 | Val acc: 58.25% | LR: 0.000375
Epoch: 068 | MCC: 0.040756 | Train loss: 0.9619 | Train acc: 52.15% | Val loss: 0.8517 | Val acc: 58.29% | LR: 0.000368
Epoch: 069 | MCC: 0.003880 | Train loss: 0.9617 | Train acc: 52.18% | Val loss: 0.8720 | Val acc: 56.66% | LR: 0.000361
Epoch: 070 | MCC: -0.000681 | Train loss: 0.9592 | Train acc: 52.26% | Val loss: 0.8748 | Val acc: 56.21% | LR: 0.000355
Epoch: 071 | MCC: 0.011284 | Train loss: 0.9622 | Train acc: 52.10% | Val loss: 0.8546 | Val acc: 57.49% | LR: 0.000348
Epoch: 072 | MCC: 0.014374 | Train loss: 0.9585 | Train acc: 52.30% | Val loss: 0.8545 | Val acc: 57.59% | LR: 0.000341
Epoch: 073 | MCC: -0.004699 | Train loss: 0.9573 | Train acc: 52.35% | Val loss: 0.8799 | Val acc: 56.44% | LR: 0.000334
Epoch: 074 | MCC: 0.013625 | Train loss: 0.9588 | Train acc: 52.27% | Val loss: 0.8528 | Val acc: 57.72% | LR: 0.000327
Epoch: 075 | MCC: 0.016961 | Train loss: 0.9622 | Train acc: 52.08% | Val loss: 0.8553 | Val acc: 57.71% | LR: 0.000320
Epoch: 076 | MCC: 0.003230 | Train loss: 0.9614 | Train acc: 52.10% | Val loss: 0.8800 | Val acc: 56.46% | LR: 0.000314
Epoch: 077 | MCC: 0.015791 | Train loss: 0.9574 | Train acc: 52.37% | Val loss: 0.8348 | Val acc: 58.06% | LR: 0.000307
Epoch: 078 | MCC: -0.007940 | Train loss: 0.9586 | Train acc: 52.27% | Val loss: 0.8600 | Val acc: 57.35% | LR: 0.000300
Epoch: 079 | MCC: 0.018622 | Train loss: 0.9556 | Train acc: 52.44% | Val loss: 0.8355 | Val acc: 58.40% | LR: 0.000293
Epoch: 080 | MCC: 0.014922 | Train loss: 0.9555 | Train acc: 52.44% | Val loss: 0.8361 | Val acc: 58.31% | LR: 0.000286
Epoch: 081 | MCC: 0.028846 | Train loss: 0.9550 | Train acc: 52.46% | Val loss: 0.8282 | Val acc: 58.83% | LR: 0.000280
Epoch: 082 | MCC: 0.011075 | Train loss: 0.9573 | Train acc: 52.37% | Val loss: 0.8440 | Val acc: 58.06% | LR: 0.000273
Epoch: 083 | MCC: 0.020613 | Train loss: 0.9554 | Train acc: 52.38% | Val loss: 0.8381 | Val acc: 58.52% | LR: 0.000266
Epoch: 084 | MCC: 0.020584 | Train loss: 0.9570 | Train acc: 52.34% | Val loss: 0.8370 | Val acc: 58.62% | LR: 0.000259
Epoch: 085 | MCC: 0.015784 | Train loss: 0.9551 | Train acc: 52.43% | Val loss: 0.8380 | Val acc: 58.19% | LR: 0.000253
Epoch: 086 | MCC: 0.008734 | Train loss: 0.9550 | Train acc: 52.40% | Val loss: 0.8445 | Val acc: 57.98% | LR: 0.000246
Epoch: 087 | MCC: 0.020199 | Train loss: 0.9532 | Train acc: 52.52% | Val loss: 0.8501 | Val acc: 57.85% | LR: 0.000239
Epoch: 088 | MCC: 0.009974 | Train loss: 0.9562 | Train acc: 52.33% | Val loss: 0.8390 | Val acc: 58.21% | LR: 0.000233
Epoch: 089 | MCC: 0.015961 | Train loss: 0.9560 | Train acc: 52.37% | Val loss: 0.8391 | Val acc: 58.47% | LR: 0.000226
Epoch: 090 | MCC: 0.006969 | Train loss: 0.9539 | Train acc: 52.51% | Val loss: 0.8362 | Val acc: 58.41% | LR: 0.000220
Epoch: 091 | MCC: 0.016139 | Train loss: 0.9537 | Train acc: 52.55% | Val loss: 0.8353 | Val acc: 58.62% | LR: 0.000214
Epoch: 092 | MCC: 0.027095 | Train loss: 0.9549 | Train acc: 52.47% | Val loss: 0.8152 | Val acc: 59.30% | LR: 0.000207
Epoch: 093 | MCC: 0.007253 | Train loss: 0.9544 | Train acc: 52.49% | Val loss: 0.8347 | Val acc: 58.32% | LR: 0.000201
Epoch: 094 | MCC: 0.006119 | Train loss: 0.9551 | Train acc: 52.43% | Val loss: 0.8452 | Val acc: 58.06% | LR: 0.000195
Epoch: 095 | MCC: 0.005216 | Train loss: 0.9529 | Train acc: 52.56% | Val loss: 0.8493 | Val acc: 58.02% | LR: 0.000188
Epoch: 096 | MCC: 0.019267 | Train loss: 0.9521 | Train acc: 52.59% | Val loss: 0.8327 | Val acc: 58.91% | LR: 0.000182
Epoch: 097 | MCC: 0.012379 | Train loss: 0.9523 | Train acc: 52.59% | Val loss: 0.8331 | Val acc: 58.70% | LR: 0.000176
Epoch: 098 | MCC: 0.013563 | Train loss: 0.9534 | Train acc: 52.52% | Val loss: 0.8345 | Val acc: 58.84% | LR: 0.000170
Epoch: 099 | MCC: 0.023269 | Train loss: 0.9558 | Train acc: 52.40% | Val loss: 0.8295 | Val acc: 59.10% | LR: 0.000164
Epoch: 100 | MCC: 0.014687 | Train loss: 0.9557 | Train acc: 52.38% | Val loss: 0.8334 | Val acc: 58.81% | LR: 0.000158
Epoch: 101 | MCC: 0.002523 | Train loss: 0.9550 | Train acc: 52.40% | Val loss: 0.8612 | Val acc: 57.78% | LR: 0.000152
Epoch: 102 | MCC: 0.019339 | Train loss: 0.9535 | Train acc: 52.52% | Val loss: 0.8521 | Val acc: 58.60% | LR: 0.000147
Epoch: 103 | MCC: 0.019004 | Train loss: 0.9535 | Train acc: 52.47% | Val loss: 0.8318 | Val acc: 58.63% | LR: 0.000141
Epoch: 104 | MCC: 0.022690 | Train loss: 0.9508 | Train acc: 52.61% | Val loss: 0.8276 | Val acc: 58.84% | LR: 0.000135
Epoch: 105 | MCC: 0.023128 | Train loss: 0.9548 | Train acc: 52.38% | Val loss: 0.8341 | Val acc: 58.59% | LR: 0.000130
Epoch: 106 | MCC: 0.018782 | Train loss: 0.9538 | Train acc: 52.42% | Val loss: 0.8418 | Val acc: 58.54% | LR: 0.000125
Epoch: 107 | MCC: 0.017425 | Train loss: 0.9536 | Train acc: 52.46% | Val loss: 0.8444 | Val acc: 58.68% | LR: 0.000119
Epoch: 108 | MCC: 0.019185 | Train loss: 0.9526 | Train acc: 52.50% | Val loss: 0.8303 | Val acc: 58.72% | LR: 0.000114
Epoch: 109 | MCC: 0.002186 | Train loss: 0.9524 | Train acc: 52.55% | Val loss: 0.8370 | Val acc: 58.44% | LR: 0.000109
Epoch: 110 | MCC: 0.010576 | Train loss: 0.9523 | Train acc: 52.54% | Val loss: 0.9673 | Val acc: 58.32% | LR: 0.000104
Epoch: 111 | MCC: 0.024049 | Train loss: 0.9518 | Train acc: 52.57% | Val loss: 0.8201 | Val acc: 59.06% | LR: 0.000099
Epoch: 112 | MCC: 0.008690 | Train loss: 0.9502 | Train acc: 52.66% | Val loss: 0.8528 | Val acc: 58.49% | LR: 0.000094
Epoch: 113 | MCC: 0.019506 | Train loss: 0.9497 | Train acc: 52.66% | Val loss: 0.8337 | Val acc: 58.79% | LR: 0.000089
Epoch: 114 | MCC: 0.017643 | Train loss: 0.9511 | Train acc: 52.60% | Val loss: 0.8330 | Val acc: 58.68% | LR: 0.000085
Epoch: 115 | MCC: 0.017049 | Train loss: 0.9536 | Train acc: 52.46% | Val loss: 0.8446 | Val acc: 58.67% | LR: 0.000080
Epoch: 116 | MCC: 0.024247 | Train loss: 0.9510 | Train acc: 52.62% | Val loss: 0.8277 | Val acc: 58.94% | LR: 0.000076
Epoch: 117 | MCC: 0.024727 | Train loss: 0.9570 | Train acc: 52.57% | Val loss: 0.8408 | Val acc: 58.97% | LR: 0.000072
Epoch: 118 | MCC: 0.019886 | Train loss: 0.9511 | Train acc: 52.65% | Val loss: 0.8466 | Val acc: 58.65% | LR: 0.000067
Epoch: 119 | MCC: 0.019263 | Train loss: 0.9517 | Train acc: 52.56% | Val loss: 0.8643 | Val acc: 58.72% | LR: 0.000063
Epoch: 120 | MCC: 0.023282 | Train loss: 0.9513 | Train acc: 52.57% | Val loss: 0.8372 | Val acc: 58.87% | LR: 0.000059
Epoch: 121 | MCC: 0.020892 | Train loss: 0.9534 | Train acc: 52.52% | Val loss: 0.8424 | Val acc: 58.76% | LR: 0.000056
Epoch: 122 | MCC: 0.023788 | Train loss: 0.9516 | Train acc: 52.59% | Val loss: 0.8332 | Val acc: 59.00% | LR: 0.000052
Epoch: 123 | MCC: 0.019760 | Train loss: 0.9519 | Train acc: 52.59% | Val loss: 0.8794 | Val acc: 58.75% | LR: 0.000048
Epoch: 124 | MCC: 0.017783 | Train loss: 0.9508 | Train acc: 52.65% | Val loss: 0.8533 | Val acc: 58.68% | LR: 0.000045
Epoch: 125 | MCC: 0.024066 | Train loss: 0.9517 | Train acc: 52.57% | Val loss: 0.8337 | Val acc: 59.03% | LR: 0.000041
Epoch: 126 | MCC: 0.021485 | Train loss: 0.9523 | Train acc: 52.50% | Val loss: 0.8511 | Val acc: 58.84% | LR: 0.000038
Epoch: 127 | MCC: 0.019010 | Train loss: 0.9517 | Train acc: 52.55% | Val loss: 0.8420 | Val acc: 58.73% | LR: 0.000035
Epoch: 128 | MCC: 0.021750 | Train loss: 0.9517 | Train acc: 52.59% | Val loss: 0.8369 | Val acc: 58.85% | LR: 0.000032
Epoch: 129 | MCC: 0.018460 | Train loss: 0.9492 | Train acc: 52.70% | Val loss: 0.8415 | Val acc: 58.71% | LR: 0.000029
Epoch: 130 | MCC: 0.020147 | Train loss: 0.9529 | Train acc: 52.51% | Val loss: 0.8397 | Val acc: 58.74% | LR: 0.000026

[I 2025-10-05 09:21:57,770] Trial 21 finished with value: 0.0198727153474465 and parameters: {'lr': 0.0006534238559910209, 'hidden_size': 105, 'dropout': 0.20908390604947236, 'weight_decay': 0.011113700683347834}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.049322 | Train loss: 0.9971 | Train acc: 50.49% | Val loss: 0.9940 | Val acc: 53.53% | LR: 0.000491
Epoch: 001 | MCC: 0.038640 | Train loss: 0.9914 | Train acc: 50.66% | Val loss: 0.9935 | Val acc: 52.38% | LR: 0.000491
Epoch: 002 | MCC: 0.042758 | Train loss: 0.9848 | Train acc: 50.89% | Val loss: 0.9819 | Val acc: 54.15% | LR: 0.000490
Epoch: 003 | MCC: 0.038010 | Train loss: 0.9854 | Train acc: 50.82% | Val loss: 0.9829 | Val acc: 53.32% | LR: 0.000490
Epoch: 004 | MCC: 0.010407 | Train loss: 0.9927 | Train acc: 50.81% | Val loss: 0.9769 | Val acc: 54.14% | LR: 0.000490
Epoch: 005 | MCC: 0.012133 | Train loss: 0.9986 | Train acc: 50.90% | Val loss: 1.0029 | Val acc: 54.13% | LR: 0.000489
Epoch: 006 | MCC: 0.025749 | Train loss: 0.9841 | Train acc: 50.86% | Val loss: 0.9549 | Val acc: 54.43% | LR: 0.000488
Epoch: 007 | MCC: 0.013875 | Train loss: 1.0029 | Train acc: 51.07% | Val loss: 0.9478 | Val acc: 54.49% | LR: 0.000488
Epoch: 008 | MCC: 0.004786 | Train loss: 0.9861 | Train acc: 50.93% | Val loss: 0.9432 | Val acc: 53.93% | LR: 0.000487
Epoch: 009 | MCC: 0.007482 | Train loss: 0.9878 | Train acc: 50.77% | Val loss: 0.9410 | Val acc: 54.02% | LR: 0.000486
Epoch: 010 | MCC: 0.004453 | Train loss: 0.9825 | Train acc: 50.90% | Val loss: 0.9466 | Val acc: 53.35% | LR: 0.000484
Epoch: 011 | MCC: 0.009592 | Train loss: 0.9825 | Train acc: 50.88% | Val loss: 0.9494 | Val acc: 53.38% | LR: 0.000483
Epoch: 012 | MCC: 0.012697 | Train loss: 0.9859 | Train acc: 50.90% | Val loss: 0.9569 | Val acc: 54.06% | LR: 0.000482
Epoch: 013 | MCC: 0.014251 | Train loss: 0.9850 | Train acc: 50.80% | Val loss: 0.9402 | Val acc: 53.98% | LR: 0.000481
Epoch: 014 | MCC: 0.020405 | Train loss: 0.9820 | Train acc: 50.91% | Val loss: 0.9378 | Val acc: 53.96% | LR: 0.000479
Epoch: 015 | MCC: 0.013183 | Train loss: 0.9828 | Train acc: 50.77% | Val loss: 0.9420 | Val acc: 53.50% | LR: 0.000477
Epoch: 016 | MCC: 0.021666 | Train loss: 0.9829 | Train acc: 50.89% | Val loss: 0.9436 | Val acc: 53.52% | LR: 0.000476
Epoch: 017 | MCC: 0.022106 | Train loss: 0.9826 | Train acc: 50.94% | Val loss: 0.9487 | Val acc: 53.07% | LR: 0.000474
Epoch: 018 | MCC: 0.043316 | Train loss: 0.9830 | Train acc: 50.87% | Val loss: 0.9565 | Val acc: 53.52% | LR: 0.000472
Epoch: 019 | MCC: 0.034990 | Train loss: 0.9853 | Train acc: 50.72% | Val loss: 0.9519 | Val acc: 53.41% | LR: 0.000470
Epoch: 020 | MCC: 0.011145 | Train loss: 0.9838 | Train acc: 50.96% | Val loss: 0.9496 | Val acc: 52.48% | LR: 0.000468
Epoch: 021 | MCC: 0.024194 | Train loss: 0.9816 | Train acc: 50.96% | Val loss: 0.9444 | Val acc: 53.10% | LR: 0.000465
Epoch: 022 | MCC: 0.014582 | Train loss: 0.9833 | Train acc: 50.80% | Val loss: 0.9588 | Val acc: 52.92% | LR: 0.000463
Epoch: 023 | MCC: 0.000149 | Train loss: 0.9863 | Train acc: 50.75% | Val loss: 0.9596 | Val acc: 52.71% | LR: 0.000461
Epoch: 024 | MCC: -0.002315 | Train loss: 0.9824 | Train acc: 50.81% | Val loss: 0.9514 | Val acc: 52.53% | LR: 0.000458
Epoch: 025 | MCC: -0.011906 | Train loss: 0.9824 | Train acc: 50.99% | Val loss: 0.9624 | Val acc: 52.07% | LR: 0.000456
Epoch: 026 | MCC: 0.009218 | Train loss: 0.9834 | Train acc: 50.73% | Val loss: 0.9478 | Val acc: 53.12% | LR: 0.000453
Epoch: 027 | MCC: 0.014904 | Train loss: 0.9811 | Train acc: 50.87% | Val loss: 0.9418 | Val acc: 53.30% | LR: 0.000450
Epoch: 028 | MCC: 0.018341 | Train loss: 0.9818 | Train acc: 50.86% | Val loss: 0.9486 | Val acc: 53.55% | LR: 0.000447
Epoch: 029 | MCC: -0.002269 | Train loss: 1.0169 | Train acc: 50.84% | Val loss: 0.9568 | Val acc: 52.76% | LR: 0.000444
Epoch: 030 | MCC: -0.010788 | Train loss: 0.9850 | Train acc: 50.84% | Val loss: 0.9461 | Val acc: 52.38% | LR: 0.000441
Epoch: 031 | MCC: -0.009839 | Train loss: 0.9840 | Train acc: 50.75% | Val loss: 0.9587 | Val acc: 52.64% | LR: 0.000438
Epoch: 032 | MCC: 0.003081 | Train loss: 0.9841 | Train acc: 50.96% | Val loss: 0.9567 | Val acc: 53.32% | LR: 0.000435
Epoch: 033 | MCC: 0.014187 | Train loss: 1.0256 | Train acc: 51.06% | Val loss: 0.9566 | Val acc: 53.61% | LR: 0.000431
Epoch: 034 | MCC: 0.020151 | Train loss: 0.9812 | Train acc: 51.03% | Val loss: 0.9380 | Val acc: 54.00% | LR: 0.000428
Epoch: 035 | MCC: -0.001700 | Train loss: 0.9829 | Train acc: 51.02% | Val loss: 0.9377 | Val acc: 53.26% | LR: 0.000425
Epoch: 036 | MCC: -0.003665 | Train loss: 0.9810 | Train acc: 50.95% | Val loss: 0.9424 | Val acc: 52.90% | LR: 0.000421
Epoch: 037 | MCC: -0.005088 | Train loss: 0.9828 | Train acc: 50.81% | Val loss: 0.9440 | Val acc: 52.76% | LR: 0.000417
Epoch: 038 | MCC: -0.005597 | Train loss: 0.9841 | Train acc: 50.82% | Val loss: 0.9480 | Val acc: 52.95% | LR: 0.000414
Epoch: 039 | MCC: 0.016273 | Train loss: 0.9828 | Train acc: 50.88% | Val loss: 0.9675 | Val acc: 53.75% | LR: 0.000410
Epoch: 040 | MCC: 0.000813 | Train loss: 0.9812 | Train acc: 50.89% | Val loss: 0.9597 | Val acc: 53.45% | LR: 0.000406
Epoch: 041 | MCC: -0.002729 | Train loss: 0.9879 | Train acc: 51.02% | Val loss: 0.9338 | Val acc: 53.45% | LR: 0.000402
Epoch: 042 | MCC: 0.001199 | Train loss: 0.9823 | Train acc: 50.81% | Val loss: 0.9536 | Val acc: 53.41% | LR: 0.000398
Epoch: 043 | MCC: -0.002666 | Train loss: 0.9799 | Train acc: 51.28% | Val loss: 0.9378 | Val acc: 53.43% | LR: 0.000394
Epoch: 044 | MCC: 0.006395 | Train loss: 0.9798 | Train acc: 50.96% | Val loss: 0.9402 | Val acc: 53.92% | LR: 0.000390
Epoch: 045 | MCC: -0.006727 | Train loss: 0.9827 | Train acc: 50.95% | Val loss: 0.9527 | Val acc: 53.28% | LR: 0.000386
Epoch: 046 | MCC: -0.013421 | Train loss: 0.9794 | Train acc: 51.37% | Val loss: 0.9438 | Val acc: 52.99% | LR: 0.000382
Epoch: 047 | MCC: -0.000203 | Train loss: 0.9819 | Train acc: 51.68% | Val loss: 0.9319 | Val acc: 53.91% | LR: 0.000377
Epoch: 048 | MCC: 0.008578 | Train loss: 0.9781 | Train acc: 51.23% | Val loss: 0.9394 | Val acc: 54.13% | LR: 0.000373
Epoch: 049 | MCC: 0.000881 | Train loss: 0.9790 | Train acc: 50.98% | Val loss: 0.9293 | Val acc: 53.77% | LR: 0.000368
Epoch: 050 | MCC: 0.006944 | Train loss: 0.9799 | Train acc: 51.22% | Val loss: 0.9358 | Val acc: 54.12% | LR: 0.000364
Epoch: 051 | MCC: 0.002533 | Train loss: 0.9809 | Train acc: 51.17% | Val loss: 0.9385 | Val acc: 53.75% | LR: 0.000359
Epoch: 052 | MCC: 0.003280 | Train loss: 0.9782 | Train acc: 51.40% | Val loss: 0.9439 | Val acc: 53.80% | LR: 0.000355
Epoch: 053 | MCC: 0.005025 | Train loss: 0.9769 | Train acc: 51.41% | Val loss: 0.9523 | Val acc: 53.50% | LR: 0.000350
Epoch: 054 | MCC: 0.005114 | Train loss: 0.9795 | Train acc: 51.25% | Val loss: 0.9459 | Val acc: 53.53% | LR: 0.000346
Epoch: 055 | MCC: 0.007201 | Train loss: 0.9775 | Train acc: 51.58% | Val loss: 0.9792 | Val acc: 53.52% | LR: 0.000341
Epoch: 056 | MCC: 0.008967 | Train loss: 0.9783 | Train acc: 51.38% | Val loss: 0.9396 | Val acc: 53.78% | LR: 0.000336
Epoch: 057 | MCC: 0.013259 | Train loss: 0.9788 | Train acc: 51.71% | Val loss: 0.9519 | Val acc: 54.04% | LR: 0.000331
Epoch: 058 | MCC: 0.025463 | Train loss: 0.9784 | Train acc: 51.66% | Val loss: 0.9359 | Val acc: 54.47% | LR: 0.000327
Epoch: 059 | MCC: 0.024342 | Train loss: 0.9806 | Train acc: 51.64% | Val loss: 0.9371 | Val acc: 54.20% | LR: 0.000322
Epoch: 060 | MCC: 0.014152 | Train loss: 0.9777 | Train acc: 51.54% | Val loss: 0.9460 | Val acc: 53.70% | LR: 0.000317
Epoch: 061 | MCC: 0.011281 | Train loss: 0.9778 | Train acc: 51.62% | Val loss: 0.9440 | Val acc: 53.50% | LR: 0.000312
Epoch: 062 | MCC: 0.016227 | Train loss: 0.9787 | Train acc: 51.52% | Val loss: 0.9453 | Val acc: 53.68% | LR: 0.000307
Epoch: 063 | MCC: 0.016132 | Train loss: 0.9781 | Train acc: 51.57% | Val loss: 0.9409 | Val acc: 53.77% | LR: 0.000302
Epoch: 064 | MCC: 0.012128 | Train loss: 0.9786 | Train acc: 51.62% | Val loss: 0.9343 | Val acc: 53.79% | LR: 0.000297
Epoch: 065 | MCC: 0.015620 | Train loss: 0.9761 | Train acc: 51.64% | Val loss: 0.9402 | Val acc: 54.05% | LR: 0.000292
Epoch: 066 | MCC: 0.018867 | Train loss: 0.9750 | Train acc: 51.68% | Val loss: 0.9491 | Val acc: 54.10% | LR: 0.000287
Epoch: 067 | MCC: 0.022496 | Train loss: 0.9764 | Train acc: 51.57% | Val loss: 0.9360 | Val acc: 54.22% | LR: 0.000282
Epoch: 068 | MCC: 0.015161 | Train loss: 0.9762 | Train acc: 51.59% | Val loss: 0.9402 | Val acc: 53.88% | LR: 0.000277
Epoch: 069 | MCC: -0.003961 | Train loss: 0.9758 | Train acc: 51.63% | Val loss: 0.9666 | Val acc: 53.71% | LR: 0.000272
Epoch: 070 | MCC: 0.006058 | Train loss: 0.9749 | Train acc: 51.71% | Val loss: 0.9381 | Val acc: 53.86% | LR: 0.000266
Epoch: 071 | MCC: -0.008026 | Train loss: 0.9759 | Train acc: 51.58% | Val loss: 0.9643 | Val acc: 53.65% | LR: 0.000261
Epoch: 072 | MCC: -0.005181 | Train loss: 0.9758 | Train acc: 51.56% | Val loss: 0.9434 | Val acc: 53.98% | LR: 0.000256
Epoch: 073 | MCC: -0.003881 | Train loss: 0.9749 | Train acc: 51.47% | Val loss: 0.9336 | Val acc: 53.90% | LR: 0.000251
Epoch: 074 | MCC: -0.010548 | Train loss: 0.9734 | Train acc: 51.56% | Val loss: 0.9385 | Val acc: 53.74% | LR: 0.000246
Epoch: 075 | MCC: -0.003172 | Train loss: 0.9817 | Train acc: 51.59% | Val loss: 0.9289 | Val acc: 54.19% | LR: 0.000241
Epoch: 076 | MCC: 0.000752 | Train loss: 0.9739 | Train acc: 51.53% | Val loss: 0.9304 | Val acc: 53.99% | LR: 0.000236
Epoch: 077 | MCC: -0.004106 | Train loss: 0.9728 | Train acc: 51.71% | Val loss: 0.9364 | Val acc: 53.69% | LR: 0.000231
Epoch: 078 | MCC: -0.018684 | Train loss: 0.9740 | Train acc: 51.52% | Val loss: 0.9366 | Val acc: 53.15% | LR: 0.000225
Epoch: 079 | MCC: -0.018537 | Train loss: 0.9737 | Train acc: 51.55% | Val loss: 0.9452 | Val acc: 52.81% | LR: 0.000220
Epoch: 080 | MCC: -0.014324 | Train loss: 0.9755 | Train acc: 51.58% | Val loss: 0.9472 | Val acc: 52.69% | LR: 0.000215
Epoch: 081 | MCC: -0.017810 | Train loss: 0.9725 | Train acc: 51.66% | Val loss: 0.9457 | Val acc: 52.82% | LR: 0.000210
Epoch: 082 | MCC: -0.020460 | Train loss: 0.9728 | Train acc: 51.78% | Val loss: 0.9463 | Val acc: 52.72% | LR: 0.000205
Epoch: 083 | MCC: -0.017404 | Train loss: 0.9731 | Train acc: 51.51% | Val loss: 0.9465 | Val acc: 52.65% | LR: 0.000200
Epoch: 084 | MCC: -0.017280 | Train loss: 0.9727 | Train acc: 51.61% | Val loss: 0.9510 | Val acc: 52.32% | LR: 0.000195
Epoch: 085 | MCC: -0.023935 | Train loss: 0.9719 | Train acc: 51.67% | Val loss: 0.9548 | Val acc: 52.34% | LR: 0.000190
Epoch: 086 | MCC: -0.007740 | Train loss: 0.9707 | Train acc: 51.79% | Val loss: 0.9556 | Val acc: 52.77% | LR: 0.000185
Epoch: 087 | MCC: -0.005437 | Train loss: 0.9742 | Train acc: 51.65% | Val loss: 0.9412 | Val acc: 53.61% | LR: 0.000180
Epoch: 088 | MCC: -0.015943 | Train loss: 0.9717 | Train acc: 51.69% | Val loss: 0.9478 | Val acc: 52.74% | LR: 0.000175
Epoch: 089 | MCC: -0.016144 | Train loss: 0.9722 | Train acc: 51.77% | Val loss: 0.9531 | Val acc: 52.56% | LR: 0.000170
Epoch: 090 | MCC: -0.013723 | Train loss: 1.0250 | Train acc: 51.76% | Val loss: 0.9501 | Val acc: 52.43% | LR: 0.000165
Epoch: 091 | MCC: -0.016719 | Train loss: 1.0330 | Train acc: 51.77% | Val loss: 0.9539 | Val acc: 52.20% | LR: 0.000161
Epoch: 092 | MCC: -0.021776 | Train loss: 0.9729 | Train acc: 51.70% | Val loss: 0.9586 | Val acc: 52.11% | LR: 0.000156
Epoch: 093 | MCC: -0.024661 | Train loss: 0.9691 | Train acc: 51.86% | Val loss: 0.9554 | Val acc: 52.15% | LR: 0.000151
Epoch: 094 | MCC: -0.020169 | Train loss: 0.9702 | Train acc: 51.86% | Val loss: 0.9664 | Val acc: 52.11% | LR: 0.000146
Epoch: 095 | MCC: -0.010872 | Train loss: 0.9692 | Train acc: 51.90% | Val loss: 0.9555 | Val acc: 52.85% | LR: 0.000142
Epoch: 096 | MCC: -0.013984 | Train loss: 0.9704 | Train acc: 51.79% | Val loss: 0.9577 | Val acc: 52.38% | LR: 0.000137
Epoch: 097 | MCC: -0.008330 | Train loss: 0.9702 | Train acc: 51.76% | Val loss: 0.9744 | Val acc: 52.42% | LR: 0.000132
Epoch: 098 | MCC: -0.017918 | Train loss: 0.9701 | Train acc: 51.76% | Val loss: 0.9564 | Val acc: 52.47% | LR: 0.000128
Epoch: 099 | MCC: -0.009128 | Train loss: 0.9708 | Train acc: 51.77% | Val loss: 0.9600 | Val acc: 52.23% | LR: 0.000123
Epoch: 100 | MCC: -0.010633 | Train loss: 0.9759 | Train acc: 51.78% | Val loss: 0.9641 | Val acc: 52.48% | LR: 0.000119
Epoch: 101 | MCC: -0.007625 | Train loss: 0.9697 | Train acc: 51.76% | Val loss: 0.9533 | Val acc: 52.71% | LR: 0.000115
Epoch: 102 | MCC: -0.004352 | Train loss: 0.9701 | Train acc: 51.80% | Val loss: 0.9582 | Val acc: 52.85% | LR: 0.000110
Epoch: 103 | MCC: -0.012228 | Train loss: 0.9700 | Train acc: 51.87% | Val loss: 0.9592 | Val acc: 52.74% | LR: 0.000106
Epoch: 104 | MCC: -0.002614 | Train loss: 0.9706 | Train acc: 51.78% | Val loss: 0.9596 | Val acc: 52.91% | LR: 0.000102
Epoch: 105 | MCC: -0.011049 | Train loss: 0.9699 | Train acc: 51.85% | Val loss: 0.9558 | Val acc: 52.82% | LR: 0.000098
Epoch: 106 | MCC: -0.006897 | Train loss: 0.9736 | Train acc: 51.75% | Val loss: 1.0909 | Val acc: 52.99% | LR: 0.000094
Epoch: 107 | MCC: -0.014286 | Train loss: 0.9709 | Train acc: 51.71% | Val loss: 0.9841 | Val acc: 52.53% | LR: 0.000090
Epoch: 108 | MCC: -0.013341 | Train loss: 0.9746 | Train acc: 51.74% | Val loss: 0.9596 | Val acc: 52.58% | LR: 0.000086
Epoch: 109 | MCC: -0.013806 | Train loss: 0.9689 | Train acc: 51.83% | Val loss: 0.9648 | Val acc: 52.51% | LR: 0.000082
Epoch: 110 | MCC: -0.011936 | Train loss: 0.9700 | Train acc: 51.80% | Val loss: 0.9610 | Val acc: 52.65% | LR: 0.000078
Epoch: 111 | MCC: -0.009285 | Train loss: 0.9696 | Train acc: 51.81% | Val loss: 0.9638 | Val acc: 52.70% | LR: 0.000075
Epoch: 112 | MCC: -0.009860 | Train loss: 0.9701 | Train acc: 51.75% | Val loss: 0.9563 | Val acc: 52.64% | LR: 0.000071
Epoch: 113 | MCC: -0.013418 | Train loss: 0.9692 | Train acc: 51.84% | Val loss: 0.9631 | Val acc: 52.60% | LR: 0.000067
Epoch: 114 | MCC: -0.012164 | Train loss: 0.9682 | Train acc: 51.85% | Val loss: 0.9594 | Val acc: 52.61% | LR: 0.000064
Epoch: 115 | MCC: -0.015179 | Train loss: 0.9701 | Train acc: 51.78% | Val loss: 0.9687 | Val acc: 52.33% | LR: 0.000061
Epoch: 116 | MCC: -0.017175 | Train loss: 0.9695 | Train acc: 51.78% | Val loss: 0.9749 | Val acc: 52.18% | LR: 0.000057
Epoch: 117 | MCC: -0.013578 | Train loss: 0.9695 | Train acc: 51.78% | Val loss: 1.0479 | Val acc: 52.37% | LR: 0.000054
Epoch: 118 | MCC: -0.009672 | Train loss: 0.9744 | Train acc: 51.70% | Val loss: 0.9625 | Val acc: 52.70% | LR: 0.000051
Epoch: 119 | MCC: -0.014276 | Train loss: 0.9697 | Train acc: 51.74% | Val loss: 0.9608 | Val acc: 52.25% | LR: 0.000048
Epoch: 120 | MCC: -0.017457 | Train loss: 0.9694 | Train acc: 51.82% | Val loss: 0.9613 | Val acc: 52.20% | LR: 0.000045
Epoch: 121 | MCC: -0.010448 | Train loss: 0.9702 | Train acc: 51.79% | Val loss: 0.9892 | Val acc: 52.36% | LR: 0.000042
Epoch: 122 | MCC: -0.013534 | Train loss: 0.9697 | Train acc: 51.79% | Val loss: 0.9795 | Val acc: 52.58% | LR: 0.000039
Epoch: 123 | MCC: -0.012126 | Train loss: 0.9698 | Train acc: 51.78% | Val loss: 0.9589 | Val acc: 52.51% | LR: 0.000036
Epoch: 124 | MCC: -0.007962 | Train loss: 0.9698 | Train acc: 51.78% | Val loss: 0.9972 | Val acc: 52.66% | LR: 0.000034
Epoch: 125 | MCC: -0.008066 | Train loss: 0.9686 | Train acc: 51.89% | Val loss: 0.9624 | Val acc: 52.75% | LR: 0.000031
Epoch: 126 | MCC: -0.008195 | Train loss: 0.9683 | Train acc: 51.80% | Val loss: 0.9942 | Val acc: 52.70% | LR: 0.000029
Epoch: 127 | MCC: -0.007876 | Train loss: 0.9682 | Train acc: 51.92% | Val loss: 0.9641 | Val acc: 52.69% | LR: 0.000027
Epoch: 128 | MCC: -0.012290 | Train loss: 0.9695 | Train acc: 51.79% | Val loss: 0.9594 | Val acc: 52.50% | LR: 0.000024
Epoch: 129 | MCC: -0.012827 | Train loss: 0.9681 | Train acc: 51.91% | Val loss: 0.9581 | Val acc: 52.46% | LR: 0.000022
Epoch: 130 | MCC: -0.010171 | Train loss: 0.9692 | Train acc: 51.80% | Val loss: 0.9592 | Val acc: 52.62% | LR: 0.000020
Epoch: 131 | MCC: -0.008142 | Train loss: 0.9672 | Train acc: 51.89% | Val loss: 0.9647 | Val acc: 52.70% | LR: 0.000018
Epoch: 132 | MCC: -0.007704 | Train loss: 0.9702 | Train acc: 51.78% | Val loss: 0.9638 | Val acc: 52.80% | LR: 0.000016
Epoch: 133 | MCC: -0.005812 | Train loss: 0.9686 | Train acc: 51.84% | Val loss: 0.9599 | Val acc: 52.90% | LR: 0.000015
Epoch: 134 | MCC: -0.006099 | Train loss: 0.9691 | Train acc: 51.83% | Val loss: 0.9614 | Val acc: 52.84% | LR: 0.000013
Epoch: 135 | MCC: -0.006415 | Train loss: 0.9696 | Train acc: 51.82% | Val loss: 0.9682 | Val acc: 52.87% | LR: 0.000011
Epoch: 136 | MCC: -0.003571 | Train loss: 0.9727 | Train acc: 51.79% | Val loss: 0.9721 | Val acc: 53.05% | LR: 0.000010
Epoch: 137 | MCC: -0.004184 | Train loss: 0.9690 | Train acc: 51.80% | Val loss: 0.9684 | Val acc: 52.99% | LR: 0.000009
Epoch: 138 | MCC: -0.003883 | Train loss: 0.9688 | Train acc: 51.86% | Val loss: 0.9696 | Val acc: 53.03% | LR: 0.000007
Epoch: 139 | MCC: -0.003379 | Train loss: 0.9683 | Train acc: 51.87% | Val loss: 0.9620 | Val acc: 52.99% | LR: 0.000006
Epoch: 140 | MCC: -0.004233 | Train loss: 0.9685 | Train acc: 51.84% | Val loss: 0.9590 | Val acc: 52.95% | LR: 0.000005
Epoch: 141 | MCC: -0.005581 | Train loss: 0.9709 | Train acc: 51.69% | Val loss: 0.9590 | Val acc: 52.90% | LR: 0.000004
Epoch: 142 | MCC: -0.003728 | Train loss: 0.9687 | Train acc: 51.77% | Val loss: 0.9599 | Val acc: 52.97% | LR: 0.000004
Epoch: 143 | MCC: -0.006372 | Train loss: 0.9667 | Train acc: 51.92% | Val loss: 0.9666 | Val acc: 52.87% | LR: 0.000003
Epoch: 144 | MCC: -0.006148 | Train loss: 0.9671 | Train acc: 51.93% | Val loss: 0.9794 | Val acc: 52.90% | LR: 0.000002
Epoch: 145 | MCC: -0.006248 | Train loss: 0.9755 | Train acc: 51.84% | Val loss: 0.9701 | Val acc: 52.92% | LR: 0.000002
Epoch: 146 | MCC: -0.006248 | Train loss: 0.9662 | Train acc: 51.98% | Val loss: 0.9751 | Val acc: 52.92% | LR: 0.000001
Epoch: 147 | MCC: -0.006561 | Train loss: 0.9696 | Train acc: 51.69% | Val loss: 1.0063 | Val acc: 52.90% | LR: 0.000001
Epoch: 148 | MCC: -0.006561 | Train loss: 0.9691 | Train acc: 51.93% | Val loss: 1.0359 | Val acc: 52.90% | LR: 0.000001
Epoch: 149 | MCC: -0.006248 | Train loss: 0.9694 | Train acc: 51.74% | Val loss: 1.0137 | Val acc: 52.92% | LR: 0.000001

[I 2025-10-05 09:24:15,246] Trial 22 finished with value: -0.0062479239131789654 and parameters: {'lr': 0.000490971391090862, 'hidden_size': 81, 'dropout': 0.2782343523379707, 'weight_decay': 0.03206579741216858}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.026776 | Train loss: 0.9975 | Train acc: 50.44% | Val loss: 0.9807 | Val acc: 55.36% | LR: 0.000796
Epoch: 001 | MCC: 0.016263 | Train loss: 0.9884 | Train acc: 50.76% | Val loss: 0.9482 | Val acc: 54.99% | LR: 0.000796
Epoch: 002 | MCC: 0.021835 | Train loss: 0.9871 | Train acc: 50.76% | Val loss: 0.9502 | Val acc: 55.68% | LR: 0.000796
Epoch: 003 | MCC: 0.020031 | Train loss: 0.9956 | Train acc: 50.88% | Val loss: 0.9327 | Val acc: 56.18% | LR: 0.000795
Epoch: 004 | MCC: 0.011079 | Train loss: 0.9856 | Train acc: 50.85% | Val loss: 0.9451 | Val acc: 56.12% | LR: 0.000794
Epoch: 005 | MCC: 0.033796 | Train loss: 0.9807 | Train acc: 50.96% | Val loss: 0.9368 | Val acc: 57.80% | LR: 0.000793
Epoch: 006 | MCC: 0.016925 | Train loss: 0.9789 | Train acc: 51.75% | Val loss: 0.9091 | Val acc: 57.77% | LR: 0.000792
Epoch: 007 | MCC: 0.027696 | Train loss: 0.9769 | Train acc: 51.71% | Val loss: 0.8824 | Val acc: 58.30% | LR: 0.000791
Epoch: 008 | MCC: 0.028492 | Train loss: 0.9811 | Train acc: 51.74% | Val loss: 0.8715 | Val acc: 57.41% | LR: 0.000790
Epoch: 009 | MCC: 0.005054 | Train loss: 0.9756 | Train acc: 51.78% | Val loss: 0.8824 | Val acc: 57.02% | LR: 0.000788
Epoch: 010 | MCC: -0.021956 | Train loss: 0.9875 | Train acc: 51.84% | Val loss: 0.8703 | Val acc: 56.43% | LR: 0.000786
Epoch: 011 | MCC: 0.015772 | Train loss: 0.9730 | Train acc: 51.99% | Val loss: 0.8603 | Val acc: 57.93% | LR: 0.000784
Epoch: 012 | MCC: 0.004954 | Train loss: 0.9701 | Train acc: 52.00% | Val loss: 0.8707 | Val acc: 56.44% | LR: 0.000782
Epoch: 013 | MCC: 0.034699 | Train loss: 0.9676 | Train acc: 52.03% | Val loss: 0.8524 | Val acc: 58.44% | LR: 0.000780
Epoch: 014 | MCC: 0.021274 | Train loss: 0.9689 | Train acc: 51.95% | Val loss: 0.8598 | Val acc: 58.25% | LR: 0.000777
Epoch: 015 | MCC: 0.048206 | Train loss: 0.9690 | Train acc: 51.95% | Val loss: 0.8486 | Val acc: 58.22% | LR: 0.000774
Epoch: 016 | MCC: 0.008222 | Train loss: 0.9683 | Train acc: 51.91% | Val loss: 0.8614 | Val acc: 57.58% | LR: 0.000772
Epoch: 017 | MCC: 0.014938 | Train loss: 0.9672 | Train acc: 52.04% | Val loss: 0.8394 | Val acc: 58.69% | LR: 0.000769
Epoch: 018 | MCC: 0.045181 | Train loss: 0.9672 | Train acc: 52.01% | Val loss: 0.8272 | Val acc: 59.57% | LR: 0.000765
Epoch: 019 | MCC: 0.008379 | Train loss: 0.9667 | Train acc: 52.01% | Val loss: 0.8637 | Val acc: 57.08% | LR: 0.000762
Epoch: 020 | MCC: 0.030074 | Train loss: 0.9663 | Train acc: 51.98% | Val loss: 0.8492 | Val acc: 58.44% | LR: 0.000759
Epoch: 021 | MCC: 0.016933 | Train loss: 0.9653 | Train acc: 52.01% | Val loss: 0.8609 | Val acc: 57.86% | LR: 0.000755
Epoch: 022 | MCC: 0.005443 | Train loss: 0.9758 | Train acc: 52.06% | Val loss: 0.8909 | Val acc: 55.73% | LR: 0.000751
Epoch: 023 | MCC: 0.018591 | Train loss: 0.9692 | Train acc: 52.12% | Val loss: 0.8529 | Val acc: 57.71% | LR: 0.000747
Epoch: 024 | MCC: 0.017194 | Train loss: 0.9697 | Train acc: 52.16% | Val loss: 0.8746 | Val acc: 56.38% | LR: 0.000743
Epoch: 025 | MCC: 0.041010 | Train loss: 0.9671 | Train acc: 51.93% | Val loss: 0.8407 | Val acc: 58.18% | LR: 0.000739
Epoch: 026 | MCC: 0.006547 | Train loss: 0.9669 | Train acc: 51.90% | Val loss: 0.8622 | Val acc: 57.28% | LR: 0.000735
Epoch: 027 | MCC: 0.005260 | Train loss: 1.0289 | Train acc: 51.75% | Val loss: 0.8819 | Val acc: 56.16% | LR: 0.000730
Epoch: 028 | MCC: 0.021925 | Train loss: 0.9723 | Train acc: 51.81% | Val loss: 0.8682 | Val acc: 57.18% | LR: 0.000725
Epoch: 029 | MCC: 0.005720 | Train loss: 0.9689 | Train acc: 51.98% | Val loss: 0.9423 | Val acc: 55.74% | LR: 0.000721
Epoch: 030 | MCC: 0.015722 | Train loss: 0.9687 | Train acc: 51.97% | Val loss: 0.8684 | Val acc: 56.79% | LR: 0.000716
Epoch: 031 | MCC: 0.013785 | Train loss: 0.9670 | Train acc: 52.02% | Val loss: 0.8758 | Val acc: 56.48% | LR: 0.000711
Epoch: 032 | MCC: 0.022909 | Train loss: 0.9671 | Train acc: 51.95% | Val loss: 0.8581 | Val acc: 57.29% | LR: 0.000705
Epoch: 033 | MCC: 0.012798 | Train loss: 0.9670 | Train acc: 51.92% | Val loss: 0.8615 | Val acc: 57.23% | LR: 0.000700
Epoch: 034 | MCC: 0.019957 | Train loss: 0.9625 | Train acc: 52.21% | Val loss: 0.8669 | Val acc: 56.88% | LR: 0.000694
Epoch: 035 | MCC: 0.006992 | Train loss: 0.9672 | Train acc: 51.90% | Val loss: 0.8978 | Val acc: 55.30% | LR: 0.000689
Epoch: 036 | MCC: -0.010146 | Train loss: 0.9672 | Train acc: 51.87% | Val loss: 0.9053 | Val acc: 55.39% | LR: 0.000683
Epoch: 037 | MCC: -0.006142 | Train loss: 0.9695 | Train acc: 51.93% | Val loss: 0.8699 | Val acc: 57.00% | LR: 0.000677
Epoch: 038 | MCC: 0.025477 | Train loss: 0.9671 | Train acc: 51.92% | Val loss: 0.8301 | Val acc: 59.05% | LR: 0.000671
Epoch: 039 | MCC: 0.018131 | Train loss: 0.9672 | Train acc: 51.83% | Val loss: 0.8518 | Val acc: 58.30% | LR: 0.000665
Epoch: 040 | MCC: 0.032422 | Train loss: 0.9639 | Train acc: 52.01% | Val loss: 0.8403 | Val acc: 59.67% | LR: 0.000659
Epoch: 041 | MCC: -0.001479 | Train loss: 0.9690 | Train acc: 52.01% | Val loss: 0.9164 | Val acc: 57.18% | LR: 0.000652
Epoch: 042 | MCC: -0.003034 | Train loss: 0.9659 | Train acc: 52.08% | Val loss: 0.8901 | Val acc: 56.54% | LR: 0.000646
Epoch: 043 | MCC: 0.011280 | Train loss: 0.9677 | Train acc: 51.99% | Val loss: 0.8714 | Val acc: 56.75% | LR: 0.000639
Epoch: 044 | MCC: 0.012741 | Train loss: 0.9702 | Train acc: 51.80% | Val loss: 0.8741 | Val acc: 56.76% | LR: 0.000633
Epoch: 045 | MCC: 0.007522 | Train loss: 0.9670 | Train acc: 51.93% | Val loss: 0.8880 | Val acc: 55.79% | LR: 0.000626
Epoch: 046 | MCC: 0.025919 | Train loss: 0.9726 | Train acc: 51.79% | Val loss: 0.8849 | Val acc: 56.25% | LR: 0.000619
Epoch: 047 | MCC: -0.002698 | Train loss: 0.9687 | Train acc: 51.86% | Val loss: 0.9256 | Val acc: 56.11% | LR: 0.000612
Epoch: 048 | MCC: 0.025785 | Train loss: 0.9663 | Train acc: 51.94% | Val loss: 1.1884 | Val acc: 56.47% | LR: 0.000605
Epoch: 049 | MCC: -0.008119 | Train loss: 0.9657 | Train acc: 52.14% | Val loss: 0.9620 | Val acc: 56.44% | LR: 0.000598
Epoch: 050 | MCC: -0.016044 | Train loss: 0.9671 | Train acc: 52.04% | Val loss: 0.9921 | Val acc: 55.97% | LR: 0.000590
Epoch: 051 | MCC: -0.006641 | Train loss: 0.9691 | Train acc: 51.83% | Val loss: 0.8994 | Val acc: 58.39% | LR: 0.000583
Epoch: 052 | MCC: -0.019544 | Train loss: 0.9645 | Train acc: 52.06% | Val loss: 1.0954 | Val acc: 56.00% | LR: 0.000576
Epoch: 053 | MCC: -0.010927 | Train loss: 0.9602 | Train acc: 52.16% | Val loss: 0.9210 | Val acc: 56.61% | LR: 0.000568
Epoch: 054 | MCC: 0.052196 | Train loss: 0.9681 | Train acc: 51.92% | Val loss: 0.8556 | Val acc: 58.52% | LR: 0.000561
Epoch: 055 | MCC: -0.000114 | Train loss: 0.9647 | Train acc: 52.14% | Val loss: 0.9072 | Val acc: 58.46% | LR: 0.000553
Epoch: 056 | MCC: 0.006975 | Train loss: 0.9663 | Train acc: 52.02% | Val loss: 0.9028 | Val acc: 58.52% | LR: 0.000545
Epoch: 057 | MCC: 0.036826 | Train loss: 0.9638 | Train acc: 52.10% | Val loss: 0.8678 | Val acc: 57.99% | LR: 0.000537
Epoch: 058 | MCC: 0.023136 | Train loss: 0.9627 | Train acc: 52.11% | Val loss: 0.8653 | Val acc: 57.77% | LR: 0.000530
Epoch: 059 | MCC: 0.033958 | Train loss: 0.9642 | Train acc: 52.02% | Val loss: 0.8681 | Val acc: 57.96% | LR: 0.000522
Epoch: 060 | MCC: 0.021156 | Train loss: 0.9611 | Train acc: 52.14% | Val loss: 0.8843 | Val acc: 57.83% | LR: 0.000514
Epoch: 061 | MCC: 0.023444 | Train loss: 0.9615 | Train acc: 52.14% | Val loss: 0.8840 | Val acc: 57.06% | LR: 0.000506
Epoch: 062 | MCC: 0.015938 | Train loss: 0.9662 | Train acc: 52.08% | Val loss: 0.9080 | Val acc: 56.67% | LR: 0.000498
Epoch: 063 | MCC: 0.007024 | Train loss: 0.9703 | Train acc: 52.06% | Val loss: 0.9572 | Val acc: 58.50% | LR: 0.000490
Epoch: 064 | MCC: -0.000601 | Train loss: 0.9663 | Train acc: 52.03% | Val loss: 0.8851 | Val acc: 56.78% | LR: 0.000481
Epoch: 065 | MCC: 0.027718 | Train loss: 0.9652 | Train acc: 52.10% | Val loss: 0.8836 | Val acc: 57.87% | LR: 0.000473
Epoch: 066 | MCC: 0.034049 | Train loss: 0.9633 | Train acc: 52.15% | Val loss: 0.8599 | Val acc: 58.20% | LR: 0.000465
Epoch: 067 | MCC: 0.046175 | Train loss: 0.9620 | Train acc: 52.19% | Val loss: 0.8469 | Val acc: 59.13% | LR: 0.000457
Epoch: 068 | MCC: 0.040530 | Train loss: 0.9629 | Train acc: 52.09% | Val loss: 0.8617 | Val acc: 58.04% | LR: 0.000449
Epoch: 069 | MCC: 0.009635 | Train loss: 0.9649 | Train acc: 51.95% | Val loss: 0.8767 | Val acc: 58.47% | LR: 0.000440
Epoch: 070 | MCC: 0.015789 | Train loss: 0.9646 | Train acc: 51.94% | Val loss: 0.8985 | Val acc: 58.81% | LR: 0.000432
Epoch: 071 | MCC: 0.006202 | Train loss: 0.9618 | Train acc: 52.11% | Val loss: 0.8691 | Val acc: 58.53% | LR: 0.000424
Epoch: 072 | MCC: -0.022835 | Train loss: 0.9673 | Train acc: 51.99% | Val loss: 0.9031 | Val acc: 56.67% | LR: 0.000415
Epoch: 073 | MCC: -0.002795 | Train loss: 0.9642 | Train acc: 52.09% | Val loss: 0.8891 | Val acc: 57.46% | LR: 0.000407
Epoch: 074 | MCC: 0.065822 | Train loss: 0.9631 | Train acc: 52.13% | Val loss: 0.8612 | Val acc: 58.47% | LR: 0.000399
Epoch: 075 | MCC: 0.017993 | Train loss: 0.9645 | Train acc: 52.05% | Val loss: 0.8839 | Val acc: 58.33% | LR: 0.000390
Epoch: 076 | MCC: 0.043971 | Train loss: 0.9626 | Train acc: 52.09% | Val loss: 1.0350 | Val acc: 59.56% | LR: 0.000382
Epoch: 077 | MCC: 0.040253 | Train loss: 0.9626 | Train acc: 52.09% | Val loss: 0.9042 | Val acc: 58.39% | LR: 0.000374
Epoch: 078 | MCC: -0.000682 | Train loss: 0.9615 | Train acc: 52.10% | Val loss: 0.9396 | Val acc: 56.58% | LR: 0.000365
Epoch: 079 | MCC: 0.032498 | Train loss: 0.9629 | Train acc: 52.04% | Val loss: 0.9260 | Val acc: 58.09% | LR: 0.000357
Epoch: 080 | MCC: 0.046856 | Train loss: 0.9604 | Train acc: 52.15% | Val loss: 0.8612 | Val acc: 59.51% | LR: 0.000349
Epoch: 081 | MCC: 0.042396 | Train loss: 0.9598 | Train acc: 52.14% | Val loss: 0.8496 | Val acc: 59.36% | LR: 0.000341
Epoch: 082 | MCC: 0.019627 | Train loss: 0.9612 | Train acc: 52.10% | Val loss: 0.8841 | Val acc: 58.66% | LR: 0.000332
Epoch: 083 | MCC: 0.031644 | Train loss: 0.9621 | Train acc: 52.03% | Val loss: 0.8948 | Val acc: 58.49% | LR: 0.000324
Epoch: 084 | MCC: 0.025592 | Train loss: 0.9592 | Train acc: 52.22% | Val loss: 0.8569 | Val acc: 57.61% | LR: 0.000316
Epoch: 085 | MCC: 0.023262 | Train loss: 0.9606 | Train acc: 52.11% | Val loss: 0.8363 | Val acc: 58.87% | LR: 0.000308
Epoch: 086 | MCC: 0.018948 | Train loss: 0.9598 | Train acc: 52.17% | Val loss: 0.8486 | Val acc: 58.27% | LR: 0.000300
Epoch: 087 | MCC: 0.016536 | Train loss: 0.9625 | Train acc: 52.08% | Val loss: 0.8386 | Val acc: 58.49% | LR: 0.000292
Epoch: 088 | MCC: 0.044328 | Train loss: 0.9596 | Train acc: 52.19% | Val loss: 0.8361 | Val acc: 58.93% | LR: 0.000284
Epoch: 089 | MCC: 0.023910 | Train loss: 0.9622 | Train acc: 52.15% | Val loss: 0.8632 | Val acc: 57.32% | LR: 0.000276
Epoch: 090 | MCC: 0.021472 | Train loss: 0.9629 | Train acc: 52.11% | Val loss: 0.8455 | Val acc: 58.05% | LR: 0.000268
Epoch: 091 | MCC: 0.019445 | Train loss: 0.9615 | Train acc: 52.13% | Val loss: 0.8609 | Val acc: 57.35% | LR: 0.000260
Epoch: 092 | MCC: 0.021539 | Train loss: 0.9619 | Train acc: 52.06% | Val loss: 0.8572 | Val acc: 57.49% | LR: 0.000252

[I 2025-10-05 09:25:53,638] Trial 23 finished with value: 0.02533900737762451 and parameters: {'lr': 0.0007965601552368307, 'hidden_size': 114, 'dropout': 0.09885368684226686, 'weight_decay': 0.00939826687901045}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.013187 | Train loss: 0.9996 | Train acc: 50.60% | Val loss: 1.0079 | Val acc: 45.64% | LR: 0.000177
Epoch: 001 | MCC: 0.033971 | Train loss: 0.9984 | Train acc: 50.69% | Val loss: 1.0046 | Val acc: 45.75% | LR: 0.000177
Epoch: 002 | MCC: 0.032477 | Train loss: 0.9976 | Train acc: 50.59% | Val loss: 1.0035 | Val acc: 45.56% | LR: 0.000177
Epoch: 003 | MCC: 0.049069 | Train loss: 0.9962 | Train acc: 50.61% | Val loss: 1.0025 | Val acc: 46.31% | LR: 0.000177
Epoch: 004 | MCC: 0.046046 | Train loss: 0.9959 | Train acc: 50.60% | Val loss: 1.0020 | Val acc: 47.41% | LR: 0.000177
Epoch: 005 | MCC: 0.062959 | Train loss: 0.9939 | Train acc: 50.65% | Val loss: 1.0011 | Val acc: 48.52% | LR: 0.000177
Epoch: 006 | MCC: 0.054613 | Train loss: 0.9928 | Train acc: 50.49% | Val loss: 1.0013 | Val acc: 49.45% | LR: 0.000176
Epoch: 007 | MCC: 0.056119 | Train loss: 0.9908 | Train acc: 50.53% | Val loss: 0.9982 | Val acc: 50.50% | LR: 0.000176
Epoch: 008 | MCC: 0.042814 | Train loss: 0.9896 | Train acc: 50.66% | Val loss: 0.9972 | Val acc: 50.82% | LR: 0.000176
Epoch: 009 | MCC: 0.037270 | Train loss: 0.9906 | Train acc: 50.61% | Val loss: 0.9987 | Val acc: 51.75% | LR: 0.000175
Epoch: 010 | MCC: 0.035879 | Train loss: 0.9902 | Train acc: 50.68% | Val loss: 0.9943 | Val acc: 52.62% | LR: 0.000175
Epoch: 011 | MCC: 0.030910 | Train loss: 0.9896 | Train acc: 50.73% | Val loss: 0.9932 | Val acc: 53.19% | LR: 0.000174
Epoch: 012 | MCC: 0.038263 | Train loss: 0.9885 | Train acc: 50.78% | Val loss: 0.9927 | Val acc: 53.79% | LR: 0.000174
Epoch: 013 | MCC: 0.042382 | Train loss: 0.9876 | Train acc: 50.80% | Val loss: 0.9850 | Val acc: 53.90% | LR: 0.000173
Epoch: 014 | MCC: 0.041033 | Train loss: 0.9870 | Train acc: 50.85% | Val loss: 0.9853 | Val acc: 54.18% | LR: 0.000173
Epoch: 015 | MCC: 0.043189 | Train loss: 0.9851 | Train acc: 50.93% | Val loss: 0.9836 | Val acc: 54.49% | LR: 0.000172
Epoch: 016 | MCC: 0.038525 | Train loss: 0.9846 | Train acc: 50.93% | Val loss: 0.9801 | Val acc: 54.67% | LR: 0.000172
Epoch: 017 | MCC: 0.039744 | Train loss: 0.9857 | Train acc: 50.85% | Val loss: 0.9774 | Val acc: 54.75% | LR: 0.000171
Epoch: 018 | MCC: 0.037496 | Train loss: 0.9842 | Train acc: 50.96% | Val loss: 0.9753 | Val acc: 54.84% | LR: 0.000170
Epoch: 019 | MCC: 0.038831 | Train loss: 0.9854 | Train acc: 50.88% | Val loss: 0.9701 | Val acc: 54.98% | LR: 0.000170
Epoch: 020 | MCC: 0.039955 | Train loss: 0.9853 | Train acc: 50.85% | Val loss: 0.9661 | Val acc: 55.21% | LR: 0.000169
Epoch: 021 | MCC: 0.033699 | Train loss: 0.9827 | Train acc: 51.02% | Val loss: 0.9615 | Val acc: 55.11% | LR: 0.000168
Epoch: 022 | MCC: 0.030166 | Train loss: 0.9821 | Train acc: 51.04% | Val loss: 0.9557 | Val acc: 55.09% | LR: 0.000167
Epoch: 023 | MCC: 0.030381 | Train loss: 0.9810 | Train acc: 51.06% | Val loss: 0.9501 | Val acc: 55.39% | LR: 0.000166
Epoch: 024 | MCC: 0.032747 | Train loss: 0.9828 | Train acc: 50.95% | Val loss: 0.9449 | Val acc: 55.61% | LR: 0.000165
Epoch: 025 | MCC: 0.028213 | Train loss: 0.9819 | Train acc: 51.00% | Val loss: 0.9413 | Val acc: 55.47% | LR: 0.000164
Epoch: 026 | MCC: 0.027348 | Train loss: 0.9836 | Train acc: 50.84% | Val loss: 0.9379 | Val acc: 55.30% | LR: 0.000163
Epoch: 027 | MCC: 0.023750 | Train loss: 0.9821 | Train acc: 50.95% | Val loss: 0.9366 | Val acc: 55.61% | LR: 0.000162
Epoch: 028 | MCC: 0.026015 | Train loss: 0.9822 | Train acc: 50.93% | Val loss: 0.9341 | Val acc: 55.74% | LR: 0.000161
Epoch: 029 | MCC: 0.021627 | Train loss: 0.9816 | Train acc: 50.99% | Val loss: 0.9309 | Val acc: 55.75% | LR: 0.000160
Epoch: 030 | MCC: 0.017886 | Train loss: 0.9823 | Train acc: 50.84% | Val loss: 0.9286 | Val acc: 55.70% | LR: 0.000159
Epoch: 031 | MCC: 0.019249 | Train loss: 0.9821 | Train acc: 50.84% | Val loss: 0.9237 | Val acc: 55.84% | LR: 0.000158
Epoch: 032 | MCC: 0.020431 | Train loss: 0.9807 | Train acc: 50.98% | Val loss: 0.9210 | Val acc: 55.88% | LR: 0.000157
Epoch: 033 | MCC: 0.019676 | Train loss: 0.9811 | Train acc: 50.98% | Val loss: 0.9175 | Val acc: 55.92% | LR: 0.000156
Epoch: 034 | MCC: 0.023012 | Train loss: 0.9810 | Train acc: 50.90% | Val loss: 0.9150 | Val acc: 56.21% | LR: 0.000155
Epoch: 035 | MCC: 0.018262 | Train loss: 0.9821 | Train acc: 50.79% | Val loss: 0.9119 | Val acc: 56.12% | LR: 0.000153
Epoch: 036 | MCC: 0.020939 | Train loss: 0.9808 | Train acc: 50.87% | Val loss: 0.9089 | Val acc: 56.23% | LR: 0.000152
Epoch: 037 | MCC: 0.012084 | Train loss: 0.9806 | Train acc: 50.93% | Val loss: 0.9378 | Val acc: 56.20% | LR: 0.000151
Epoch: 038 | MCC: 0.023959 | Train loss: 0.9797 | Train acc: 50.99% | Val loss: 0.9035 | Val acc: 56.55% | LR: 0.000149
Epoch: 039 | MCC: 0.024136 | Train loss: 0.9812 | Train acc: 50.84% | Val loss: 0.8995 | Val acc: 56.72% | LR: 0.000148
Epoch: 040 | MCC: 0.029712 | Train loss: 0.9803 | Train acc: 50.92% | Val loss: 0.8981 | Val acc: 56.87% | LR: 0.000147
Epoch: 041 | MCC: 0.025992 | Train loss: 0.9798 | Train acc: 50.95% | Val loss: 0.8949 | Val acc: 56.84% | LR: 0.000145
Epoch: 042 | MCC: 0.026683 | Train loss: 0.9804 | Train acc: 50.90% | Val loss: 0.8917 | Val acc: 56.91% | LR: 0.000144
Epoch: 043 | MCC: 0.025901 | Train loss: 0.9801 | Train acc: 50.94% | Val loss: 0.8903 | Val acc: 56.99% | LR: 0.000142
Epoch: 044 | MCC: 0.045752 | Train loss: 0.9793 | Train acc: 51.01% | Val loss: 0.8873 | Val acc: 57.67% | LR: 0.000141
Epoch: 045 | MCC: 0.037894 | Train loss: 0.9785 | Train acc: 51.07% | Val loss: 0.8820 | Val acc: 57.94% | LR: 0.000139
Epoch: 046 | MCC: 0.049116 | Train loss: 0.9781 | Train acc: 51.10% | Val loss: 0.8802 | Val acc: 58.37% | LR: 0.000138
Epoch: 047 | MCC: 0.045365 | Train loss: 0.9787 | Train acc: 51.05% | Val loss: 0.8779 | Val acc: 58.35% | LR: 0.000136
Epoch: 048 | MCC: 0.050692 | Train loss: 0.9781 | Train acc: 51.05% | Val loss: 0.8743 | Val acc: 58.49% | LR: 0.000135
Epoch: 049 | MCC: 0.049559 | Train loss: 0.9789 | Train acc: 51.07% | Val loss: 0.8706 | Val acc: 58.29% | LR: 0.000133
Epoch: 050 | MCC: 0.042232 | Train loss: 0.9787 | Train acc: 51.11% | Val loss: 0.8690 | Val acc: 57.51% | LR: 0.000132
Epoch: 051 | MCC: 0.033954 | Train loss: 0.9779 | Train acc: 51.10% | Val loss: 0.8647 | Val acc: 57.75% | LR: 0.000130
Epoch: 052 | MCC: 0.035114 | Train loss: 0.9793 | Train acc: 51.04% | Val loss: 0.8650 | Val acc: 57.50% | LR: 0.000128
Epoch: 053 | MCC: 0.030088 | Train loss: 0.9770 | Train acc: 51.16% | Val loss: 0.8648 | Val acc: 56.91% | LR: 0.000127
Epoch: 054 | MCC: 0.024473 | Train loss: 0.9761 | Train acc: 51.19% | Val loss: 0.8640 | Val acc: 56.67% | LR: 0.000125
Epoch: 055 | MCC: -0.002248 | Train loss: 0.9759 | Train acc: 51.23% | Val loss: 0.8688 | Val acc: 56.18% | LR: 0.000123
Epoch: 056 | MCC: 0.003765 | Train loss: 0.9749 | Train acc: 51.23% | Val loss: 0.8689 | Val acc: 56.68% | LR: 0.000122
Epoch: 057 | MCC: 0.008724 | Train loss: 0.9766 | Train acc: 51.13% | Val loss: 0.8692 | Val acc: 57.03% | LR: 0.000120
Epoch: 058 | MCC: 0.005414 | Train loss: 0.9760 | Train acc: 51.23% | Val loss: 0.8736 | Val acc: 56.47% | LR: 0.000118
Epoch: 059 | MCC: 0.022059 | Train loss: 0.9767 | Train acc: 51.13% | Val loss: 0.9331 | Val acc: 56.85% | LR: 0.000116
Epoch: 060 | MCC: 0.016574 | Train loss: 0.9764 | Train acc: 51.16% | Val loss: 0.8755 | Val acc: 56.83% | LR: 0.000115
Epoch: 061 | MCC: 0.012355 | Train loss: 0.9742 | Train acc: 51.25% | Val loss: 0.8674 | Val acc: 57.20% | LR: 0.000113
Epoch: 062 | MCC: 0.021061 | Train loss: 0.9720 | Train acc: 51.45% | Val loss: 0.8743 | Val acc: 57.04% | LR: 0.000111
Epoch: 063 | MCC: -0.002708 | Train loss: 0.9733 | Train acc: 51.37% | Val loss: 0.8634 | Val acc: 56.91% | LR: 0.000109
Epoch: 064 | MCC: 0.017108 | Train loss: 0.9738 | Train acc: 51.29% | Val loss: 0.8612 | Val acc: 57.37% | LR: 0.000107
Epoch: 065 | MCC: 0.014726 | Train loss: 0.9732 | Train acc: 51.26% | Val loss: 0.8669 | Val acc: 56.83% | LR: 0.000106
Epoch: 066 | MCC: -0.001781 | Train loss: 0.9710 | Train acc: 51.41% | Val loss: 0.8645 | Val acc: 56.83% | LR: 0.000104
Epoch: 067 | MCC: 0.017340 | Train loss: 0.9728 | Train acc: 51.31% | Val loss: 0.8587 | Val acc: 57.81% | LR: 0.000102
Epoch: 068 | MCC: 0.013265 | Train loss: 0.9716 | Train acc: 51.38% | Val loss: 0.8567 | Val acc: 57.83% | LR: 0.000100
Epoch: 069 | MCC: 0.014986 | Train loss: 0.9745 | Train acc: 51.32% | Val loss: 0.8552 | Val acc: 57.93% | LR: 0.000098
Epoch: 070 | MCC: 0.021067 | Train loss: 0.9726 | Train acc: 51.35% | Val loss: 0.8423 | Val acc: 58.30% | LR: 0.000096
Epoch: 071 | MCC: 0.033383 | Train loss: 0.9708 | Train acc: 51.37% | Val loss: 0.8331 | Val acc: 59.20% | LR: 0.000095
Epoch: 072 | MCC: 0.031214 | Train loss: 0.9714 | Train acc: 51.36% | Val loss: 0.8294 | Val acc: 59.25% | LR: 0.000093
Epoch: 073 | MCC: 0.045935 | Train loss: 0.9710 | Train acc: 51.45% | Val loss: 0.8227 | Val acc: 60.06% | LR: 0.000091
Epoch: 074 | MCC: 0.029472 | Train loss: 0.9711 | Train acc: 51.33% | Val loss: 0.8279 | Val acc: 59.44% | LR: 0.000089
Epoch: 075 | MCC: 0.020059 | Train loss: 0.9696 | Train acc: 51.41% | Val loss: 0.8397 | Val acc: 58.44% | LR: 0.000087
Epoch: 076 | MCC: 0.019492 | Train loss: 0.9727 | Train acc: 51.36% | Val loss: 0.8463 | Val acc: 58.18% | LR: 0.000085
Epoch: 077 | MCC: 0.016024 | Train loss: 0.9728 | Train acc: 51.27% | Val loss: 0.8441 | Val acc: 58.13% | LR: 0.000084
Epoch: 078 | MCC: 0.012555 | Train loss: 0.9706 | Train acc: 51.38% | Val loss: 0.8413 | Val acc: 58.08% | LR: 0.000082
Epoch: 079 | MCC: 0.018234 | Train loss: 0.9712 | Train acc: 51.28% | Val loss: 0.8338 | Val acc: 58.52% | LR: 0.000080
Epoch: 080 | MCC: 0.025972 | Train loss: 0.9692 | Train acc: 51.49% | Val loss: 0.8274 | Val acc: 59.08% | LR: 0.000078
Epoch: 081 | MCC: 0.041008 | Train loss: 0.9686 | Train acc: 51.50% | Val loss: 0.8222 | Val acc: 59.71% | LR: 0.000076
Epoch: 082 | MCC: 0.039663 | Train loss: 0.9695 | Train acc: 51.41% | Val loss: 0.8278 | Val acc: 59.25% | LR: 0.000074
Epoch: 083 | MCC: 0.039154 | Train loss: 0.9689 | Train acc: 51.44% | Val loss: 0.8234 | Val acc: 59.35% | LR: 0.000073
Epoch: 084 | MCC: 0.040243 | Train loss: 0.9687 | Train acc: 51.41% | Val loss: 0.8207 | Val acc: 59.49% | LR: 0.000071
Epoch: 085 | MCC: 0.032595 | Train loss: 0.9685 | Train acc: 51.44% | Val loss: 0.8195 | Val acc: 59.40% | LR: 0.000069
Epoch: 086 | MCC: 0.029990 | Train loss: 0.9686 | Train acc: 51.43% | Val loss: 0.8260 | Val acc: 59.08% | LR: 0.000067
Epoch: 087 | MCC: 0.034635 | Train loss: 0.9669 | Train acc: 51.60% | Val loss: 0.8174 | Val acc: 59.57% | LR: 0.000065
Epoch: 088 | MCC: 0.034040 | Train loss: 0.9677 | Train acc: 51.56% | Val loss: 0.8159 | Val acc: 59.57% | LR: 0.000064
Epoch: 089 | MCC: 0.036828 | Train loss: 0.9668 | Train acc: 51.56% | Val loss: 0.8193 | Val acc: 59.45% | LR: 0.000062
Epoch: 090 | MCC: 0.028186 | Train loss: 0.9663 | Train acc: 51.58% | Val loss: 0.8196 | Val acc: 59.20% | LR: 0.000060
Epoch: 091 | MCC: 0.037521 | Train loss: 0.9674 | Train acc: 51.55% | Val loss: 0.8143 | Val acc: 59.80% | LR: 0.000058
Epoch: 092 | MCC: 0.035612 | Train loss: 0.9685 | Train acc: 51.45% | Val loss: 0.8265 | Val acc: 58.98% | LR: 0.000057
Epoch: 093 | MCC: 0.036423 | Train loss: 0.9689 | Train acc: 51.41% | Val loss: 0.8159 | Val acc: 59.54% | LR: 0.000055
Epoch: 094 | MCC: 0.033912 | Train loss: 0.9662 | Train acc: 51.51% | Val loss: 0.8174 | Val acc: 59.56% | LR: 0.000053
Epoch: 095 | MCC: 0.035702 | Train loss: 0.9653 | Train acc: 51.64% | Val loss: 0.8171 | Val acc: 59.59% | LR: 0.000052
Epoch: 096 | MCC: 0.038597 | Train loss: 0.9658 | Train acc: 51.53% | Val loss: 0.8139 | Val acc: 59.92% | LR: 0.000050
Epoch: 097 | MCC: 0.033666 | Train loss: 0.9663 | Train acc: 51.62% | Val loss: 0.8193 | Val acc: 59.37% | LR: 0.000048
Epoch: 098 | MCC: 0.034987 | Train loss: 0.9662 | Train acc: 51.60% | Val loss: 0.8191 | Val acc: 59.45% | LR: 0.000047
Epoch: 099 | MCC: 0.030063 | Train loss: 0.9653 | Train acc: 51.63% | Val loss: 0.8198 | Val acc: 59.34% | LR: 0.000045
Epoch: 100 | MCC: 0.033141 | Train loss: 0.9662 | Train acc: 51.56% | Val loss: 0.8206 | Val acc: 59.30% | LR: 0.000043
Epoch: 101 | MCC: 0.034587 | Train loss: 0.9673 | Train acc: 51.44% | Val loss: 0.8191 | Val acc: 59.45% | LR: 0.000042
Epoch: 102 | MCC: 0.027949 | Train loss: 0.9665 | Train acc: 51.48% | Val loss: 0.8190 | Val acc: 59.29% | LR: 0.000040
Epoch: 103 | MCC: 0.029619 | Train loss: 0.9667 | Train acc: 51.42% | Val loss: 0.8222 | Val acc: 59.13% | LR: 0.000039
Epoch: 104 | MCC: 0.033836 | Train loss: 0.9652 | Train acc: 51.60% | Val loss: 0.8187 | Val acc: 59.51% | LR: 0.000037
Epoch: 105 | MCC: 0.030687 | Train loss: 0.9659 | Train acc: 51.56% | Val loss: 0.8205 | Val acc: 59.39% | LR: 0.000036
Epoch: 106 | MCC: 0.027603 | Train loss: 0.9659 | Train acc: 51.51% | Val loss: 0.8203 | Val acc: 59.26% | LR: 0.000034
Epoch: 107 | MCC: 0.029290 | Train loss: 0.9654 | Train acc: 51.54% | Val loss: 0.8203 | Val acc: 59.29% | LR: 0.000033
Epoch: 108 | MCC: 0.028747 | Train loss: 0.9656 | Train acc: 51.60% | Val loss: 0.8187 | Val acc: 59.36% | LR: 0.000032
Epoch: 109 | MCC: 0.036702 | Train loss: 0.9672 | Train acc: 51.55% | Val loss: 0.8149 | Val acc: 59.73% | LR: 0.000030
Epoch: 110 | MCC: 0.030687 | Train loss: 0.9661 | Train acc: 51.53% | Val loss: 0.8207 | Val acc: 59.39% | LR: 0.000029
Epoch: 111 | MCC: 0.032030 | Train loss: 0.9644 | Train acc: 51.61% | Val loss: 0.8177 | Val acc: 59.53% | LR: 0.000027
Epoch: 112 | MCC: 0.031700 | Train loss: 0.9646 | Train acc: 51.58% | Val loss: 0.8190 | Val acc: 59.46% | LR: 0.000026
Epoch: 113 | MCC: 0.031842 | Train loss: 0.9639 | Train acc: 51.62% | Val loss: 0.8191 | Val acc: 59.46% | LR: 0.000025
Epoch: 114 | MCC: 0.035274 | Train loss: 0.9646 | Train acc: 51.52% | Val loss: 0.8188 | Val acc: 59.45% | LR: 0.000024
Epoch: 115 | MCC: 0.033725 | Train loss: 0.9650 | Train acc: 51.52% | Val loss: 0.8204 | Val acc: 59.30% | LR: 0.000022
Epoch: 116 | MCC: 0.027338 | Train loss: 0.9641 | Train acc: 51.63% | Val loss: 0.8171 | Val acc: 59.29% | LR: 0.000021
Epoch: 117 | MCC: 0.034508 | Train loss: 0.9643 | Train acc: 51.68% | Val loss: 0.8174 | Val acc: 59.51% | LR: 0.000020
Epoch: 118 | MCC: 0.031842 | Train loss: 0.9641 | Train acc: 51.67% | Val loss: 0.8186 | Val acc: 59.46% | LR: 0.000019
Epoch: 119 | MCC: 0.036349 | Train loss: 0.9661 | Train acc: 51.61% | Val loss: 0.8146 | Val acc: 59.73% | LR: 0.000018
Epoch: 120 | MCC: 0.034909 | Train loss: 0.9664 | Train acc: 51.45% | Val loss: 0.8184 | Val acc: 59.42% | LR: 0.000017
Epoch: 121 | MCC: 0.031868 | Train loss: 0.9663 | Train acc: 51.53% | Val loss: 0.8154 | Val acc: 59.56% | LR: 0.000016
Epoch: 122 | MCC: 0.029441 | Train loss: 0.9657 | Train acc: 51.54% | Val loss: 0.8184 | Val acc: 59.39% | LR: 0.000015
Epoch: 123 | MCC: 0.034909 | Train loss: 0.9649 | Train acc: 51.53% | Val loss: 0.8198 | Val acc: 59.40% | LR: 0.000014
Epoch: 124 | MCC: 0.032589 | Train loss: 0.9661 | Train acc: 51.43% | Val loss: 0.8168 | Val acc: 59.48% | LR: 0.000013
Epoch: 125 | MCC: 0.033260 | Train loss: 0.9637 | Train acc: 51.63% | Val loss: 0.8154 | Val acc: 59.53% | LR: 0.000012
Epoch: 126 | MCC: 0.035322 | Train loss: 0.9651 | Train acc: 51.57% | Val loss: 0.8173 | Val acc: 59.61% | LR: 0.000011
Epoch: 127 | MCC: 0.033179 | Train loss: 0.9657 | Train acc: 51.55% | Val loss: 0.8176 | Val acc: 59.48% | LR: 0.000010
Epoch: 128 | MCC: 0.033645 | Train loss: 0.9658 | Train acc: 51.55% | Val loss: 0.8171 | Val acc: 59.53% | LR: 0.000009
Epoch: 129 | MCC: 0.032589 | Train loss: 0.9654 | Train acc: 51.61% | Val loss: 0.8177 | Val acc: 59.48% | LR: 0.000009
Epoch: 130 | MCC: 0.034417 | Train loss: 0.9737 | Train acc: 51.54% | Val loss: 0.8172 | Val acc: 59.58% | LR: 0.000008
Epoch: 131 | MCC: 0.034477 | Train loss: 0.9658 | Train acc: 51.52% | Val loss: 0.8171 | Val acc: 59.56% | LR: 0.000007
Epoch: 132 | MCC: 0.034551 | Train loss: 0.9635 | Train acc: 51.73% | Val loss: 0.8175 | Val acc: 59.56% | LR: 0.000007
Epoch: 133 | MCC: 0.033779 | Train loss: 0.9644 | Train acc: 51.61% | Val loss: 0.8177 | Val acc: 59.51% | LR: 0.000006
Epoch: 134 | MCC: 0.033964 | Train loss: 0.9659 | Train acc: 51.49% | Val loss: 0.8171 | Val acc: 59.56% | LR: 0.000005
Epoch: 135 | MCC: 0.035322 | Train loss: 0.9653 | Train acc: 51.48% | Val loss: 0.8171 | Val acc: 59.61% | LR: 0.000005
Epoch: 136 | MCC: 0.034789 | Train loss: 0.9637 | Train acc: 51.61% | Val loss: 0.8169 | Val acc: 59.61% | LR: 0.000004
Epoch: 137 | MCC: 0.034016 | Train loss: 0.9648 | Train acc: 51.50% | Val loss: 0.8169 | Val acc: 59.56% | LR: 0.000004
Epoch: 138 | MCC: 0.034011 | Train loss: 0.9641 | Train acc: 51.66% | Val loss: 0.8179 | Val acc: 59.51% | LR: 0.000003
Epoch: 139 | MCC: 0.034011 | Train loss: 0.9642 | Train acc: 51.58% | Val loss: 0.8174 | Val acc: 59.51% | LR: 0.000003
Epoch: 140 | MCC: 0.034016 | Train loss: 0.9652 | Train acc: 51.59% | Val loss: 0.8168 | Val acc: 59.56% | LR: 0.000003
Epoch: 141 | MCC: 0.034011 | Train loss: 0.9643 | Train acc: 51.58% | Val loss: 0.8174 | Val acc: 59.51% | LR: 0.000002
Epoch: 142 | MCC: 0.034773 | Train loss: 0.9651 | Train acc: 51.56% | Val loss: 0.8170 | Val acc: 59.58% | LR: 0.000002
Epoch: 143 | MCC: 0.034016 | Train loss: 0.9630 | Train acc: 51.65% | Val loss: 0.8170 | Val acc: 59.56% | LR: 0.000002
Epoch: 144 | MCC: 0.033415 | Train loss: 0.9634 | Train acc: 51.72% | Val loss: 0.8169 | Val acc: 59.53% | LR: 0.000001
Epoch: 145 | MCC: 0.033415 | Train loss: 0.9639 | Train acc: 51.64% | Val loss: 0.8169 | Val acc: 59.53% | LR: 0.000001
Epoch: 146 | MCC: 0.033942 | Train loss: 0.9653 | Train acc: 51.57% | Val loss: 0.8170 | Val acc: 59.56% | LR: 0.000001
Epoch: 147 | MCC: 0.034773 | Train loss: 0.9641 | Train acc: 51.56% | Val loss: 0.8172 | Val acc: 59.58% | LR: 0.000001
Epoch: 148 | MCC: 0.034773 | Train loss: 0.9639 | Train acc: 51.67% | Val loss: 0.8171 | Val acc: 59.58% | LR: 0.000001
Epoch: 149 | MCC: 0.034773 | Train loss: 0.9637 | Train acc: 51.76% | Val loss: 0.8171 | Val acc: 59.58% | LR: 0.000001

[I 2025-10-05 09:28:26,455] Trial 24 finished with value: 0.03477336186915636 and parameters: {'lr': 0.00017719860315931424, 'hidden_size': 97, 'dropout': 0.2115612071168541, 'weight_decay': 0.0011749958957253317}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.011773 | Train loss: 1.0013 | Train acc: 49.36% | Val loss: 0.9944 | Val acc: 54.59% | LR: 0.000409
Epoch: 001 | MCC: 0.003573 | Train loss: 0.9988 | Train acc: 50.21% | Val loss: 0.9878 | Val acc: 54.76% | LR: 0.000409
Epoch: 002 | MCC: 0.010381 | Train loss: 0.9967 | Train acc: 50.25% | Val loss: 0.9915 | Val acc: 54.78% | LR: 0.000409
Epoch: 003 | MCC: -0.001993 | Train loss: 0.9948 | Train acc: 50.28% | Val loss: 0.9890 | Val acc: 54.73% | LR: 0.000409
Epoch: 004 | MCC: -0.017836 | Train loss: 0.9944 | Train acc: 50.12% | Val loss: 0.9857 | Val acc: 54.68% | LR: 0.000408
Epoch: 005 | MCC: -0.019596 | Train loss: 0.9899 | Train acc: 50.27% | Val loss: 0.9866 | Val acc: 54.47% | LR: 0.000408
Epoch: 006 | MCC: -0.005478 | Train loss: 0.9907 | Train acc: 50.52% | Val loss: 0.9837 | Val acc: 54.74% | LR: 0.000407
Epoch: 007 | MCC: 0.014558 | Train loss: 0.9898 | Train acc: 51.04% | Val loss: 0.9831 | Val acc: 54.91% | LR: 0.000407
Epoch: 008 | MCC: 0.017253 | Train loss: 0.9894 | Train acc: 50.79% | Val loss: 0.9822 | Val acc: 55.35% | LR: 0.000406
Epoch: 009 | MCC: 0.022713 | Train loss: 0.9884 | Train acc: 50.95% | Val loss: 0.9786 | Val acc: 55.47% | LR: 0.000405
Epoch: 010 | MCC: 0.026055 | Train loss: 0.9882 | Train acc: 50.90% | Val loss: 0.9713 | Val acc: 55.23% | LR: 0.000404
Epoch: 011 | MCC: 0.022100 | Train loss: 0.9845 | Train acc: 50.94% | Val loss: 0.9700 | Val acc: 55.13% | LR: 0.000403
Epoch: 012 | MCC: 0.033748 | Train loss: 0.9836 | Train acc: 51.00% | Val loss: 0.9596 | Val acc: 56.03% | LR: 0.000402
Epoch: 013 | MCC: 0.030879 | Train loss: 0.9839 | Train acc: 50.90% | Val loss: 0.9525 | Val acc: 56.26% | LR: 0.000401
Epoch: 014 | MCC: 0.028608 | Train loss: 0.9842 | Train acc: 50.86% | Val loss: 0.9451 | Val acc: 56.34% | LR: 0.000399
Epoch: 015 | MCC: 0.026133 | Train loss: 0.9835 | Train acc: 50.87% | Val loss: 0.9350 | Val acc: 56.35% | LR: 0.000398
Epoch: 016 | MCC: 0.018034 | Train loss: 0.9836 | Train acc: 50.87% | Val loss: 0.9346 | Val acc: 56.05% | LR: 0.000397
Epoch: 017 | MCC: 0.022676 | Train loss: 0.9834 | Train acc: 50.91% | Val loss: 0.9260 | Val acc: 56.09% | LR: 0.000395
Epoch: 018 | MCC: 0.032889 | Train loss: 0.9798 | Train acc: 51.07% | Val loss: 0.9214 | Val acc: 56.50% | LR: 0.000393
Epoch: 019 | MCC: 0.037511 | Train loss: 0.9820 | Train acc: 50.95% | Val loss: 0.9131 | Val acc: 56.87% | LR: 0.000392
Epoch: 020 | MCC: 0.053649 | Train loss: 0.9824 | Train acc: 50.90% | Val loss: 0.9156 | Val acc: 56.83% | LR: 0.000390
Epoch: 021 | MCC: 0.038711 | Train loss: 0.9816 | Train acc: 50.98% | Val loss: 0.9081 | Val acc: 57.39% | LR: 0.000388
Epoch: 022 | MCC: 0.010863 | Train loss: 0.9801 | Train acc: 51.03% | Val loss: 0.9015 | Val acc: 56.82% | LR: 0.000386
Epoch: 023 | MCC: -0.004777 | Train loss: 0.9800 | Train acc: 51.12% | Val loss: 0.8864 | Val acc: 56.39% | LR: 0.000384
Epoch: 024 | MCC: -0.004940 | Train loss: 0.9770 | Train acc: 51.30% | Val loss: 0.8889 | Val acc: 56.44% | LR: 0.000382
Epoch: 025 | MCC: 0.003322 | Train loss: 0.9778 | Train acc: 51.20% | Val loss: 1.1478 | Val acc: 56.98% | LR: 0.000380
Epoch: 026 | MCC: 0.000324 | Train loss: 0.9754 | Train acc: 51.30% | Val loss: 0.9663 | Val acc: 57.24% | LR: 0.000378
Epoch: 027 | MCC: 0.012901 | Train loss: 0.9748 | Train acc: 51.35% | Val loss: 0.8895 | Val acc: 56.66% | LR: 0.000375
Epoch: 028 | MCC: 0.009237 | Train loss: 0.9756 | Train acc: 51.22% | Val loss: 0.8732 | Val acc: 57.34% | LR: 0.000373
Epoch: 029 | MCC: 0.011174 | Train loss: 0.9745 | Train acc: 51.35% | Val loss: 0.8743 | Val acc: 56.99% | LR: 0.000370
Epoch: 030 | MCC: 0.030224 | Train loss: 0.9739 | Train acc: 51.28% | Val loss: 0.8837 | Val acc: 57.10% | LR: 0.000368
Epoch: 031 | MCC: 0.003343 | Train loss: 0.9740 | Train acc: 51.27% | Val loss: 0.8896 | Val acc: 56.30% | LR: 0.000365
Epoch: 032 | MCC: 0.033007 | Train loss: 0.9731 | Train acc: 51.35% | Val loss: 0.9960 | Val acc: 56.87% | LR: 0.000363
Epoch: 033 | MCC: 0.025056 | Train loss: 0.9732 | Train acc: 51.24% | Val loss: 0.8863 | Val acc: 56.10% | LR: 0.000360
Epoch: 034 | MCC: 0.000165 | Train loss: 1.0086 | Train acc: 51.14% | Val loss: 0.8689 | Val acc: 56.56% | LR: 0.000357
Epoch: 035 | MCC: 0.007855 | Train loss: 0.9770 | Train acc: 51.20% | Val loss: 0.8709 | Val acc: 56.68% | LR: 0.000354
Epoch: 036 | MCC: 0.025627 | Train loss: 0.9733 | Train acc: 51.34% | Val loss: 0.8637 | Val acc: 57.59% | LR: 0.000351
Epoch: 037 | MCC: -0.006292 | Train loss: 0.9742 | Train acc: 51.29% | Val loss: 0.8696 | Val acc: 57.02% | LR: 0.000348
Epoch: 038 | MCC: 0.016921 | Train loss: 0.9713 | Train acc: 51.44% | Val loss: 0.8726 | Val acc: 57.42% | LR: 0.000345
Epoch: 039 | MCC: 0.029447 | Train loss: 0.9755 | Train acc: 51.21% | Val loss: 0.8309 | Val acc: 59.88% | LR: 0.000342
Epoch: 040 | MCC: 0.014122 | Train loss: 0.9752 | Train acc: 51.22% | Val loss: 0.8984 | Val acc: 55.95% | LR: 0.000339
Epoch: 041 | MCC: 0.029393 | Train loss: 0.9748 | Train acc: 51.28% | Val loss: 0.8434 | Val acc: 58.68% | LR: 0.000335
Epoch: 042 | MCC: 0.016922 | Train loss: 0.9754 | Train acc: 51.20% | Val loss: 0.9050 | Val acc: 58.68% | LR: 0.000332
Epoch: 043 | MCC: -0.011755 | Train loss: 0.9744 | Train acc: 51.25% | Val loss: 0.9640 | Val acc: 56.64% | LR: 0.000329
Epoch: 044 | MCC: -0.002645 | Train loss: 0.9735 | Train acc: 51.31% | Val loss: 0.8675 | Val acc: 57.05% | LR: 0.000325
Epoch: 045 | MCC: -0.004806 | Train loss: 0.9734 | Train acc: 51.26% | Val loss: 0.8684 | Val acc: 57.71% | LR: 0.000322
Epoch: 046 | MCC: 0.039914 | Train loss: 0.9729 | Train acc: 51.29% | Val loss: 0.8612 | Val acc: 57.50% | LR: 0.000318
Epoch: 047 | MCC: 0.025891 | Train loss: 0.9719 | Train acc: 51.32% | Val loss: 0.8330 | Val acc: 59.23% | LR: 0.000315
Epoch: 048 | MCC: 0.020673 | Train loss: 0.9703 | Train acc: 51.46% | Val loss: 0.8500 | Val acc: 58.05% | LR: 0.000311
Epoch: 049 | MCC: 0.026203 | Train loss: 0.9718 | Train acc: 51.43% | Val loss: 0.8331 | Val acc: 59.15% | LR: 0.000307
Epoch: 050 | MCC: 0.024552 | Train loss: 0.9718 | Train acc: 51.33% | Val loss: 0.8261 | Val acc: 59.32% | LR: 0.000304
Epoch: 051 | MCC: 0.072347 | Train loss: 0.9710 | Train acc: 51.37% | Val loss: 0.8688 | Val acc: 59.52% | LR: 0.000300
Epoch: 052 | MCC: 0.031521 | Train loss: 0.9709 | Train acc: 51.31% | Val loss: 0.8462 | Val acc: 58.20% | LR: 0.000296
Epoch: 053 | MCC: 0.017646 | Train loss: 0.9709 | Train acc: 51.43% | Val loss: 0.8385 | Val acc: 58.20% | LR: 0.000292
Epoch: 054 | MCC: 0.074072 | Train loss: 0.9703 | Train acc: 51.44% | Val loss: 0.8284 | Val acc: 59.09% | LR: 0.000288
Epoch: 055 | MCC: 0.011610 | Train loss: 0.9706 | Train acc: 51.38% | Val loss: 0.8385 | Val acc: 58.32% | LR: 0.000284
Epoch: 056 | MCC: 0.086726 | Train loss: 0.9707 | Train acc: 51.36% | Val loss: 0.8214 | Val acc: 59.57% | LR: 0.000280
Epoch: 057 | MCC: 0.027004 | Train loss: 0.9703 | Train acc: 51.45% | Val loss: 0.8329 | Val acc: 58.80% | LR: 0.000276
Epoch: 058 | MCC: 0.022413 | Train loss: 0.9715 | Train acc: 51.33% | Val loss: 0.8712 | Val acc: 56.74% | LR: 0.000272
Epoch: 059 | MCC: 0.066208 | Train loss: 0.9721 | Train acc: 51.32% | Val loss: 0.8469 | Val acc: 58.02% | LR: 0.000268
Epoch: 060 | MCC: 0.062128 | Train loss: 0.9709 | Train acc: 51.42% | Val loss: 0.8251 | Val acc: 59.17% | LR: 0.000264
Epoch: 061 | MCC: 0.013032 | Train loss: 0.9696 | Train acc: 51.45% | Val loss: 0.8372 | Val acc: 58.34% | LR: 0.000260
Epoch: 062 | MCC: 0.041244 | Train loss: 0.9696 | Train acc: 51.44% | Val loss: 0.8315 | Val acc: 58.63% | LR: 0.000256
Epoch: 063 | MCC: 0.041189 | Train loss: 0.9713 | Train acc: 51.27% | Val loss: 0.8489 | Val acc: 57.66% | LR: 0.000252
Epoch: 064 | MCC: 0.060959 | Train loss: 0.9689 | Train acc: 51.49% | Val loss: 0.8334 | Val acc: 58.71% | LR: 0.000248
Epoch: 065 | MCC: 0.004595 | Train loss: 0.9688 | Train acc: 51.48% | Val loss: 0.8515 | Val acc: 57.56% | LR: 0.000243
Epoch: 066 | MCC: 0.056497 | Train loss: 0.9693 | Train acc: 51.46% | Val loss: 0.8193 | Val acc: 59.48% | LR: 0.000239
Epoch: 067 | MCC: 0.058132 | Train loss: 0.9705 | Train acc: 51.37% | Val loss: 0.8166 | Val acc: 59.56% | LR: 0.000235
Epoch: 068 | MCC: 0.017993 | Train loss: 0.9693 | Train acc: 51.41% | Val loss: 0.8303 | Val acc: 58.70% | LR: 0.000231
Epoch: 069 | MCC: 0.063563 | Train loss: 0.9676 | Train acc: 51.32% | Val loss: 0.8213 | Val acc: 59.53% | LR: 0.000227
Epoch: 070 | MCC: 0.037311 | Train loss: 0.9681 | Train acc: 51.55% | Val loss: 0.8433 | Val acc: 58.63% | LR: 0.000222
Epoch: 071 | MCC: 0.032192 | Train loss: 0.9682 | Train acc: 51.29% | Val loss: 0.8351 | Val acc: 58.52% | LR: 0.000218
Epoch: 072 | MCC: 0.011680 | Train loss: 0.9683 | Train acc: 51.73% | Val loss: 0.8383 | Val acc: 58.34% | LR: 0.000214
Epoch: 073 | MCC: 0.049770 | Train loss: 0.9692 | Train acc: 51.44% | Val loss: 0.8475 | Val acc: 58.19% | LR: 0.000209
Epoch: 074 | MCC: 0.047856 | Train loss: 0.9688 | Train acc: 51.51% | Val loss: 0.8455 | Val acc: 58.03% | LR: 0.000205
Epoch: 075 | MCC: 0.046865 | Train loss: 0.9668 | Train acc: 51.68% | Val loss: 0.8326 | Val acc: 58.95% | LR: 0.000201
Epoch: 076 | MCC: 0.045611 | Train loss: 0.9675 | Train acc: 51.37% | Val loss: 0.8438 | Val acc: 58.27% | LR: 0.000197
Epoch: 077 | MCC: 0.022652 | Train loss: 0.9675 | Train acc: 51.65% | Val loss: 0.8338 | Val acc: 58.41% | LR: 0.000192
Epoch: 078 | MCC: 0.016953 | Train loss: 0.9705 | Train acc: 51.15% | Val loss: 0.8438 | Val acc: 58.22% | LR: 0.000188
Epoch: 079 | MCC: 0.039592 | Train loss: 0.9668 | Train acc: 52.24% | Val loss: 0.8552 | Val acc: 57.71% | LR: 0.000184
Epoch: 080 | MCC: 0.034863 | Train loss: 0.9714 | Train acc: 51.89% | Val loss: 0.8743 | Val acc: 57.03% | LR: 0.000180
Epoch: 081 | MCC: 0.040235 | Train loss: 0.9705 | Train acc: 51.88% | Val loss: 0.8544 | Val acc: 57.74% | LR: 0.000175
Epoch: 082 | MCC: 0.073353 | Train loss: 0.9690 | Train acc: 52.08% | Val loss: 0.8315 | Val acc: 58.81% | LR: 0.000171
Epoch: 083 | MCC: 0.058924 | Train loss: 0.9681 | Train acc: 52.07% | Val loss: 0.8314 | Val acc: 58.85% | LR: 0.000167
Epoch: 084 | MCC: 0.086963 | Train loss: 0.9690 | Train acc: 51.93% | Val loss: 0.8243 | Val acc: 59.33% | LR: 0.000163
Epoch: 085 | MCC: 0.059622 | Train loss: 0.9678 | Train acc: 52.04% | Val loss: 0.8324 | Val acc: 58.80% | LR: 0.000159
Epoch: 086 | MCC: 0.083368 | Train loss: 0.9686 | Train acc: 52.02% | Val loss: 0.8227 | Val acc: 59.30% | LR: 0.000154
Epoch: 087 | MCC: 0.074534 | Train loss: 0.9698 | Train acc: 52.03% | Val loss: 0.8291 | Val acc: 59.18% | LR: 0.000150
Epoch: 088 | MCC: 0.024582 | Train loss: 0.9664 | Train acc: 52.15% | Val loss: 0.8435 | Val acc: 58.19% | LR: 0.000146
Epoch: 089 | MCC: 0.030246 | Train loss: 0.9666 | Train acc: 52.14% | Val loss: 0.8441 | Val acc: 58.12% | LR: 0.000142
Epoch: 090 | MCC: 0.042552 | Train loss: 0.9662 | Train acc: 52.11% | Val loss: 0.8394 | Val acc: 58.43% | LR: 0.000138
Epoch: 091 | MCC: 0.020515 | Train loss: 0.9658 | Train acc: 52.17% | Val loss: 0.8393 | Val acc: 58.39% | LR: 0.000134
Epoch: 092 | MCC: 0.026279 | Train loss: 0.9664 | Train acc: 52.14% | Val loss: 0.8404 | Val acc: 58.23% | LR: 0.000130
Epoch: 093 | MCC: 0.027846 | Train loss: 0.9659 | Train acc: 52.17% | Val loss: 0.8394 | Val acc: 58.25% | LR: 0.000126
Epoch: 094 | MCC: 0.027355 | Train loss: 0.9666 | Train acc: 52.17% | Val loss: 0.8424 | Val acc: 58.28% | LR: 0.000122
Epoch: 095 | MCC: 0.086437 | Train loss: 0.9672 | Train acc: 52.09% | Val loss: 0.8272 | Val acc: 59.18% | LR: 0.000118
Epoch: 096 | MCC: 0.075324 | Train loss: 0.9673 | Train acc: 52.10% | Val loss: 0.8285 | Val acc: 59.05% | LR: 0.000114
Epoch: 097 | MCC: 0.055771 | Train loss: 0.9661 | Train acc: 52.14% | Val loss: 0.8320 | Val acc: 58.85% | LR: 0.000111
Epoch: 098 | MCC: 0.028881 | Train loss: 0.9663 | Train acc: 52.13% | Val loss: 0.8392 | Val acc: 58.25% | LR: 0.000107
Epoch: 099 | MCC: 0.031202 | Train loss: 0.9657 | Train acc: 52.16% | Val loss: 0.8417 | Val acc: 58.24% | LR: 0.000103
Epoch: 100 | MCC: 0.029220 | Train loss: 0.9640 | Train acc: 52.33% | Val loss: 0.8418 | Val acc: 58.21% | LR: 0.000099
Epoch: 101 | MCC: 0.032278 | Train loss: 0.9656 | Train acc: 52.15% | Val loss: 0.8359 | Val acc: 58.53% | LR: 0.000096
Epoch: 102 | MCC: 0.029701 | Train loss: 0.9670 | Train acc: 52.12% | Val loss: 0.8387 | Val acc: 58.36% | LR: 0.000092
Epoch: 103 | MCC: 0.031277 | Train loss: 0.9653 | Train acc: 52.19% | Val loss: 0.8383 | Val acc: 58.41% | LR: 0.000089
Epoch: 104 | MCC: 0.035394 | Train loss: 0.9656 | Train acc: 52.14% | Val loss: 0.8346 | Val acc: 58.74% | LR: 0.000085
Epoch: 105 | MCC: 0.031705 | Train loss: 0.9642 | Train acc: 52.15% | Val loss: 0.8405 | Val acc: 58.39% | LR: 0.000082
Epoch: 106 | MCC: 0.036266 | Train loss: 0.9650 | Train acc: 52.22% | Val loss: 0.8320 | Val acc: 58.81% | LR: 0.000078
Epoch: 107 | MCC: 0.031019 | Train loss: 0.9658 | Train acc: 52.19% | Val loss: 0.8374 | Val acc: 58.39% | LR: 0.000075
Epoch: 108 | MCC: 0.035371 | Train loss: 0.9634 | Train acc: 52.32% | Val loss: 0.8358 | Val acc: 58.67% | LR: 0.000072
Epoch: 109 | MCC: 0.059521 | Train loss: 0.9644 | Train acc: 52.26% | Val loss: 0.8305 | Val acc: 58.97% | LR: 0.000069
Epoch: 110 | MCC: 0.059737 | Train loss: 0.9655 | Train acc: 52.17% | Val loss: 0.8295 | Val acc: 58.97% | LR: 0.000065
Epoch: 111 | MCC: 0.058872 | Train loss: 0.9650 | Train acc: 52.19% | Val loss: 0.8320 | Val acc: 58.87% | LR: 0.000062
Epoch: 112 | MCC: 0.071854 | Train loss: 0.9640 | Train acc: 52.25% | Val loss: 0.8298 | Val acc: 58.88% | LR: 0.000059
Epoch: 113 | MCC: 0.074153 | Train loss: 0.9665 | Train acc: 52.17% | Val loss: 0.8296 | Val acc: 58.93% | LR: 0.000056
Epoch: 114 | MCC: 0.036768 | Train loss: 0.9636 | Train acc: 52.33% | Val loss: 0.8326 | Val acc: 58.84% | LR: 0.000053
Epoch: 115 | MCC: 0.075152 | Train loss: 0.9643 | Train acc: 52.22% | Val loss: 0.8290 | Val acc: 59.03% | LR: 0.000051
Epoch: 116 | MCC: 0.029535 | Train loss: 0.9642 | Train acc: 52.22% | Val loss: 0.8380 | Val acc: 58.40% | LR: 0.000048
Epoch: 117 | MCC: 0.059344 | Train loss: 0.9640 | Train acc: 52.22% | Val loss: 0.8303 | Val acc: 58.95% | LR: 0.000045
Epoch: 118 | MCC: 0.075323 | Train loss: 0.9647 | Train acc: 52.18% | Val loss: 0.8289 | Val acc: 59.05% | LR: 0.000043
Epoch: 119 | MCC: 0.060120 | Train loss: 0.9633 | Train acc: 52.29% | Val loss: 0.8290 | Val acc: 59.07% | LR: 0.000040
Epoch: 120 | MCC: 0.058400 | Train loss: 0.9643 | Train acc: 52.27% | Val loss: 0.8302 | Val acc: 58.87% | LR: 0.000038
Epoch: 121 | MCC: 0.058696 | Train loss: 0.9619 | Train acc: 52.29% | Val loss: 0.8304 | Val acc: 58.92% | LR: 0.000035
Epoch: 122 | MCC: 0.058556 | Train loss: 0.9625 | Train acc: 52.28% | Val loss: 0.8313 | Val acc: 58.92% | LR: 0.000033
Epoch: 123 | MCC: 0.057782 | Train loss: 0.9617 | Train acc: 52.41% | Val loss: 0.8318 | Val acc: 58.87% | LR: 0.000031
Epoch: 124 | MCC: 0.074859 | Train loss: 0.9639 | Train acc: 52.24% | Val loss: 0.8280 | Val acc: 59.10% | LR: 0.000028
Epoch: 125 | MCC: 0.059744 | Train loss: 0.9638 | Train acc: 52.21% | Val loss: 0.8311 | Val acc: 58.97% | LR: 0.000026
Epoch: 126 | MCC: 0.058696 | Train loss: 0.9628 | Train acc: 52.27% | Val loss: 0.8305 | Val acc: 58.92% | LR: 0.000024
Epoch: 127 | MCC: 0.059090 | Train loss: 0.9619 | Train acc: 52.38% | Val loss: 0.8302 | Val acc: 58.95% | LR: 0.000022
Epoch: 128 | MCC: 0.059157 | Train loss: 0.9635 | Train acc: 52.31% | Val loss: 0.8298 | Val acc: 58.95% | LR: 0.000020
Epoch: 129 | MCC: 0.058539 | Train loss: 0.9600 | Train acc: 52.47% | Val loss: 0.8312 | Val acc: 58.87% | LR: 0.000019
Epoch: 130 | MCC: 0.057902 | Train loss: 0.9635 | Train acc: 52.21% | Val loss: 0.8303 | Val acc: 58.90% | LR: 0.000017
Epoch: 131 | MCC: 0.059157 | Train loss: 0.9646 | Train acc: 52.21% | Val loss: 0.8300 | Val acc: 58.95% | LR: 0.000015
Epoch: 132 | MCC: 0.074238 | Train loss: 0.9623 | Train acc: 52.28% | Val loss: 0.8307 | Val acc: 58.98% | LR: 0.000014
Epoch: 133 | MCC: 0.074742 | Train loss: 0.9619 | Train acc: 52.31% | Val loss: 0.8298 | Val acc: 59.03% | LR: 0.000012
Epoch: 134 | MCC: 0.057902 | Train loss: 0.9629 | Train acc: 52.30% | Val loss: 0.8302 | Val acc: 58.90% | LR: 0.000011
Epoch: 135 | MCC: 0.058652 | Train loss: 0.9639 | Train acc: 52.24% | Val loss: 0.8311 | Val acc: 58.90% | LR: 0.000010
Epoch: 136 | MCC: 0.058652 | Train loss: 0.9620 | Train acc: 52.31% | Val loss: 0.8310 | Val acc: 58.90% | LR: 0.000009
Epoch: 137 | MCC: 0.058248 | Train loss: 0.9619 | Train acc: 52.35% | Val loss: 0.8307 | Val acc: 58.90% | LR: 0.000007
Epoch: 138 | MCC: 0.057902 | Train loss: 0.9631 | Train acc: 52.28% | Val loss: 0.8302 | Val acc: 58.90% | LR: 0.000006
Epoch: 139 | MCC: 0.058248 | Train loss: 0.9629 | Train acc: 52.29% | Val loss: 0.8309 | Val acc: 58.90% | LR: 0.000005
Epoch: 140 | MCC: 0.058248 | Train loss: 0.9617 | Train acc: 52.33% | Val loss: 0.8306 | Val acc: 58.90% | LR: 0.000005
Epoch: 141 | MCC: 0.059090 | Train loss: 0.9634 | Train acc: 52.19% | Val loss: 0.8304 | Val acc: 58.95% | LR: 0.000004

[I 2025-10-05 09:30:33,096] Trial 25 finished with value: 0.058585542254149914 and parameters: {'lr': 0.0004094391615120603, 'hidden_size': 72, 'dropout': 0.1024364489229374, 'weight_decay': 0.021973370048213193}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: -0.022604 | Train loss: 1.0005 | Train acc: 50.11% | Val loss: 0.9902 | Val acc: 54.52% | LR: 0.000337
Epoch: 001 | MCC: 0.008930 | Train loss: 0.9980 | Train acc: 50.30% | Val loss: 0.9860 | Val acc: 54.83% | LR: 0.000337
Epoch: 002 | MCC: 0.006532 | Train loss: 0.9973 | Train acc: 50.21% | Val loss: 0.9822 | Val acc: 54.78% | LR: 0.000337
Epoch: 003 | MCC: 0.002486 | Train loss: 0.9940 | Train acc: 50.34% | Val loss: 0.9800 | Val acc: 54.86% | LR: 0.000337
Epoch: 004 | MCC: -0.010956 | Train loss: 0.9924 | Train acc: 50.46% | Val loss: 0.9770 | Val acc: 55.14% | LR: 0.000336
Epoch: 005 | MCC: 0.005513 | Train loss: 0.9889 | Train acc: 50.69% | Val loss: 0.9747 | Val acc: 55.05% | LR: 0.000336
Epoch: 006 | MCC: 0.013188 | Train loss: 0.9907 | Train acc: 50.76% | Val loss: 0.9722 | Val acc: 55.67% | LR: 0.000336
Epoch: 007 | MCC: -0.007958 | Train loss: 0.9891 | Train acc: 50.90% | Val loss: 0.9705 | Val acc: 55.49% | LR: 0.000335
Epoch: 008 | MCC: -0.015380 | Train loss: 0.9903 | Train acc: 50.99% | Val loss: 0.9672 | Val acc: 55.31% | LR: 0.000334
Epoch: 009 | MCC: -0.011114 | Train loss: 0.9885 | Train acc: 50.94% | Val loss: 0.9620 | Val acc: 55.30% | LR: 0.000334
Epoch: 010 | MCC: 0.007784 | Train loss: 0.9885 | Train acc: 50.85% | Val loss: 0.9586 | Val acc: 55.38% | LR: 0.000333
Epoch: 011 | MCC: 0.007057 | Train loss: 0.9860 | Train acc: 50.89% | Val loss: 0.9512 | Val acc: 55.26% | LR: 0.000332
Epoch: 012 | MCC: 0.010560 | Train loss: 0.9843 | Train acc: 50.96% | Val loss: 0.9437 | Val acc: 55.50% | LR: 0.000331
Epoch: 013 | MCC: 0.017698 | Train loss: 0.9829 | Train acc: 51.03% | Val loss: 0.9351 | Val acc: 55.73% | LR: 0.000330
Epoch: 014 | MCC: 0.020030 | Train loss: 0.9827 | Train acc: 50.95% | Val loss: 0.9293 | Val acc: 55.70% | LR: 0.000329
Epoch: 015 | MCC: 0.022926 | Train loss: 0.9824 | Train acc: 50.99% | Val loss: 0.9249 | Val acc: 56.01% | LR: 0.000328
Epoch: 016 | MCC: 0.026513 | Train loss: 0.9824 | Train acc: 50.94% | Val loss: 0.9212 | Val acc: 56.16% | LR: 0.000327
Epoch: 017 | MCC: 0.032439 | Train loss: 0.9827 | Train acc: 50.82% | Val loss: 0.9152 | Val acc: 56.41% | LR: 0.000326
Epoch: 018 | MCC: 0.032703 | Train loss: 0.9815 | Train acc: 50.88% | Val loss: 0.9116 | Val acc: 56.77% | LR: 0.000324
Epoch: 019 | MCC: 0.018284 | Train loss: 0.9815 | Train acc: 50.90% | Val loss: 0.9050 | Val acc: 56.74% | LR: 0.000323
Epoch: 020 | MCC: 0.031110 | Train loss: 0.9808 | Train acc: 50.90% | Val loss: 0.9007 | Val acc: 57.27% | LR: 0.000321
Epoch: 021 | MCC: 0.031771 | Train loss: 0.9790 | Train acc: 50.98% | Val loss: 0.8950 | Val acc: 57.38% | LR: 0.000320
Epoch: 022 | MCC: 0.027460 | Train loss: 0.9799 | Train acc: 50.97% | Val loss: 0.8900 | Val acc: 57.04% | LR: 0.000318
Epoch: 023 | MCC: 0.028024 | Train loss: 0.9974 | Train acc: 51.09% | Val loss: 0.8856 | Val acc: 57.08% | LR: 0.000317
Epoch: 024 | MCC: -0.004356 | Train loss: 0.9907 | Train acc: 51.05% | Val loss: 0.8840 | Val acc: 56.43% | LR: 0.000315
Epoch: 025 | MCC: -0.003349 | Train loss: 0.9805 | Train acc: 51.02% | Val loss: 0.8797 | Val acc: 56.26% | LR: 0.000313
Epoch: 026 | MCC: -0.006143 | Train loss: 0.9777 | Train acc: 51.24% | Val loss: 0.8799 | Val acc: 56.03% | LR: 0.000311
Epoch: 027 | MCC: -0.003058 | Train loss: 0.9784 | Train acc: 51.18% | Val loss: 0.8808 | Val acc: 56.11% | LR: 0.000309
Epoch: 028 | MCC: 0.000218 | Train loss: 0.9756 | Train acc: 51.30% | Val loss: 0.8809 | Val acc: 56.22% | LR: 0.000307
Epoch: 029 | MCC: 0.004441 | Train loss: 0.9770 | Train acc: 51.23% | Val loss: 0.8835 | Val acc: 56.37% | LR: 0.000305
Epoch: 030 | MCC: 0.001813 | Train loss: 0.9760 | Train acc: 51.28% | Val loss: 0.8830 | Val acc: 56.10% | LR: 0.000303
Epoch: 031 | MCC: 0.006638 | Train loss: 0.9760 | Train acc: 51.20% | Val loss: 0.8825 | Val acc: 56.30% | LR: 0.000301
Epoch: 032 | MCC: 0.003833 | Train loss: 0.9752 | Train acc: 51.24% | Val loss: 0.8804 | Val acc: 56.34% | LR: 0.000299
Epoch: 033 | MCC: 0.010790 | Train loss: 0.9765 | Train acc: 51.19% | Val loss: 0.8753 | Val acc: 56.86% | LR: 0.000297
Epoch: 034 | MCC: 0.010482 | Train loss: 0.9728 | Train acc: 51.46% | Val loss: 0.8766 | Val acc: 56.66% | LR: 0.000294
Epoch: 035 | MCC: 0.012718 | Train loss: 0.9745 | Train acc: 51.27% | Val loss: 0.8572 | Val acc: 58.08% | LR: 0.000292
Epoch: 036 | MCC: 0.008435 | Train loss: 0.9774 | Train acc: 51.04% | Val loss: 0.8576 | Val acc: 57.91% | LR: 0.000289
Epoch: 037 | MCC: 0.001371 | Train loss: 0.9753 | Train acc: 51.18% | Val loss: 0.8669 | Val acc: 57.12% | LR: 0.000287
Epoch: 038 | MCC: 0.007259 | Train loss: 0.9749 | Train acc: 51.18% | Val loss: 0.8861 | Val acc: 56.00% | LR: 0.000284
Epoch: 039 | MCC: 0.011129 | Train loss: 0.9745 | Train acc: 51.23% | Val loss: 0.8759 | Val acc: 56.59% | LR: 0.000282
Epoch: 040 | MCC: 0.005640 | Train loss: 0.9734 | Train acc: 51.31% | Val loss: 0.8712 | Val acc: 56.74% | LR: 0.000279
Epoch: 041 | MCC: 0.002722 | Train loss: 0.9743 | Train acc: 51.17% | Val loss: 0.8728 | Val acc: 56.47% | LR: 0.000276
Epoch: 042 | MCC: 0.013801 | Train loss: 0.9723 | Train acc: 51.32% | Val loss: 0.8611 | Val acc: 57.74% | LR: 0.000274
Epoch: 043 | MCC: 0.010744 | Train loss: 0.9724 | Train acc: 51.34% | Val loss: 0.8747 | Val acc: 56.78% | LR: 0.000271
Epoch: 044 | MCC: 0.013859 | Train loss: 0.9723 | Train acc: 51.29% | Val loss: 0.8655 | Val acc: 57.35% | LR: 0.000268
Epoch: 045 | MCC: 0.009996 | Train loss: 0.9723 | Train acc: 51.35% | Val loss: 0.8648 | Val acc: 57.42% | LR: 0.000265
Epoch: 046 | MCC: 0.003592 | Train loss: 0.9718 | Train acc: 51.35% | Val loss: 0.8588 | Val acc: 57.76% | LR: 0.000262
Epoch: 047 | MCC: 0.007951 | Train loss: 0.9734 | Train acc: 51.33% | Val loss: 0.8806 | Val acc: 56.47% | LR: 0.000259
Epoch: 048 | MCC: 0.008091 | Train loss: 0.9727 | Train acc: 51.27% | Val loss: 0.8604 | Val acc: 57.71% | LR: 0.000256
Epoch: 049 | MCC: 0.018395 | Train loss: 0.9738 | Train acc: 51.16% | Val loss: 0.8531 | Val acc: 58.20% | LR: 0.000253
Epoch: 050 | MCC: -0.003696 | Train loss: 0.9714 | Train acc: 51.33% | Val loss: 0.8682 | Val acc: 57.00% | LR: 0.000250
Epoch: 051 | MCC: 0.004152 | Train loss: 0.9722 | Train acc: 51.28% | Val loss: 0.8780 | Val acc: 56.52% | LR: 0.000247
Epoch: 052 | MCC: 0.025992 | Train loss: 0.9723 | Train acc: 51.32% | Val loss: 0.8723 | Val acc: 59.40% | LR: 0.000244
Epoch: 053 | MCC: -0.006550 | Train loss: 0.9728 | Train acc: 51.32% | Val loss: 0.8710 | Val acc: 56.88% | LR: 0.000241
Epoch: 054 | MCC: 0.007872 | Train loss: 0.9717 | Train acc: 51.41% | Val loss: 0.8584 | Val acc: 57.66% | LR: 0.000238
Epoch: 055 | MCC: 0.015124 | Train loss: 0.9710 | Train acc: 51.33% | Val loss: 0.8648 | Val acc: 57.52% | LR: 0.000234
Epoch: 056 | MCC: 0.011219 | Train loss: 0.9718 | Train acc: 51.30% | Val loss: 0.8564 | Val acc: 57.91% | LR: 0.000231
Epoch: 057 | MCC: 0.036507 | Train loss: 0.9700 | Train acc: 51.41% | Val loss: 0.8463 | Val acc: 58.61% | LR: 0.000228
Epoch: 058 | MCC: 0.024127 | Train loss: 0.9696 | Train acc: 51.45% | Val loss: 0.8472 | Val acc: 58.57% | LR: 0.000225
Epoch: 059 | MCC: 0.043681 | Train loss: 0.9704 | Train acc: 51.47% | Val loss: 0.8449 | Val acc: 58.64% | LR: 0.000221
Epoch: 060 | MCC: 0.010257 | Train loss: 0.9696 | Train acc: 51.39% | Val loss: 0.8523 | Val acc: 57.88% | LR: 0.000218
Epoch: 061 | MCC: 0.007765 | Train loss: 0.9751 | Train acc: 51.49% | Val loss: 0.9819 | Val acc: 56.49% | LR: 0.000214
Epoch: 062 | MCC: 0.031659 | Train loss: 0.9771 | Train acc: 51.30% | Val loss: 0.8893 | Val acc: 56.08% | LR: 0.000211
Epoch: 063 | MCC: -0.013458 | Train loss: 0.9790 | Train acc: 51.02% | Val loss: 0.9324 | Val acc: 54.20% | LR: 0.000208
Epoch: 064 | MCC: -0.034014 | Train loss: 0.9932 | Train acc: 50.37% | Val loss: 0.9827 | Val acc: 51.35% | LR: 0.000204
Epoch: 065 | MCC: -0.022339 | Train loss: 0.9884 | Train acc: 50.47% | Val loss: 0.9888 | Val acc: 51.08% | LR: 0.000201
Epoch: 066 | MCC: -0.022603 | Train loss: 0.9883 | Train acc: 50.51% | Val loss: 0.9851 | Val acc: 51.15% | LR: 0.000197
Epoch: 067 | MCC: -0.011803 | Train loss: 0.9858 | Train acc: 50.60% | Val loss: 0.9619 | Val acc: 52.67% | LR: 0.000194
Epoch: 068 | MCC: -0.009936 | Train loss: 0.9824 | Train acc: 50.82% | Val loss: 0.9562 | Val acc: 52.81% | LR: 0.000190
Epoch: 069 | MCC: -0.024377 | Train loss: 0.9843 | Train acc: 50.73% | Val loss: 0.9429 | Val acc: 53.22% | LR: 0.000187
Epoch: 070 | MCC: -0.020340 | Train loss: 0.9814 | Train acc: 50.82% | Val loss: 0.9195 | Val acc: 54.76% | LR: 0.000183
Epoch: 071 | MCC: -0.018302 | Train loss: 0.9789 | Train acc: 51.36% | Val loss: 0.8980 | Val acc: 55.73% | LR: 0.000180
Epoch: 072 | MCC: -0.002942 | Train loss: 0.9753 | Train acc: 51.42% | Val loss: 0.8819 | Val acc: 56.52% | LR: 0.000176
Epoch: 073 | MCC: -0.007756 | Train loss: 0.9756 | Train acc: 51.21% | Val loss: 0.8915 | Val acc: 56.05% | LR: 0.000173
Epoch: 074 | MCC: 0.005308 | Train loss: 0.9727 | Train acc: 51.28% | Val loss: 0.9090 | Val acc: 57.15% | LR: 0.000169
Epoch: 075 | MCC: 0.011036 | Train loss: 0.9728 | Train acc: 51.24% | Val loss: 0.8438 | Val acc: 58.49% | LR: 0.000166
Epoch: 076 | MCC: 0.028621 | Train loss: 0.9740 | Train acc: 51.26% | Val loss: 0.8382 | Val acc: 58.76% | LR: 0.000162
Epoch: 077 | MCC: 0.012104 | Train loss: 0.9731 | Train acc: 51.34% | Val loss: 0.8494 | Val acc: 58.01% | LR: 0.000159
Epoch: 078 | MCC: 0.004220 | Train loss: 0.9714 | Train acc: 51.34% | Val loss: 0.8448 | Val acc: 58.81% | LR: 0.000155
Epoch: 079 | MCC: 0.008488 | Train loss: 0.9737 | Train acc: 51.30% | Val loss: 0.8707 | Val acc: 58.94% | LR: 0.000152
Epoch: 080 | MCC: 0.015643 | Train loss: 0.9722 | Train acc: 51.37% | Val loss: 0.8359 | Val acc: 58.89% | LR: 0.000148
Epoch: 081 | MCC: 0.030436 | Train loss: 0.9725 | Train acc: 51.43% | Val loss: 0.8287 | Val acc: 59.30% | LR: 0.000145
Epoch: 082 | MCC: 0.018205 | Train loss: 0.9721 | Train acc: 51.38% | Val loss: 0.8309 | Val acc: 59.18% | LR: 0.000141
Epoch: 083 | MCC: 0.014405 | Train loss: 0.9733 | Train acc: 51.27% | Val loss: 0.8297 | Val acc: 59.36% | LR: 0.000138
Epoch: 084 | MCC: 0.008577 | Train loss: 0.9720 | Train acc: 51.21% | Val loss: 0.8614 | Val acc: 57.59% | LR: 0.000134
Epoch: 085 | MCC: -0.006354 | Train loss: 0.9716 | Train acc: 51.34% | Val loss: 0.8746 | Val acc: 56.81% | LR: 0.000131
Epoch: 086 | MCC: 0.009923 | Train loss: 0.9711 | Train acc: 51.37% | Val loss: 0.8759 | Val acc: 56.69% | LR: 0.000127
Epoch: 087 | MCC: 0.007573 | Train loss: 0.9725 | Train acc: 51.23% | Val loss: 0.8755 | Val acc: 56.71% | LR: 0.000124
Epoch: 088 | MCC: 0.010019 | Train loss: 0.9713 | Train acc: 51.23% | Val loss: 0.8775 | Val acc: 56.56% | LR: 0.000121
Epoch: 089 | MCC: 0.010851 | Train loss: 0.9697 | Train acc: 51.45% | Val loss: 0.8660 | Val acc: 57.12% | LR: 0.000117
Epoch: 090 | MCC: 0.006213 | Train loss: 0.9710 | Train acc: 51.45% | Val loss: 0.8738 | Val acc: 56.74% | LR: 0.000114
Epoch: 091 | MCC: 0.016424 | Train loss: 0.9716 | Train acc: 51.33% | Val loss: 0.8693 | Val acc: 56.93% | LR: 0.000111
Epoch: 092 | MCC: 0.013001 | Train loss: 0.9718 | Train acc: 51.20% | Val loss: 0.8775 | Val acc: 57.02% | LR: 0.000107
Epoch: 093 | MCC: 0.023034 | Train loss: 0.9709 | Train acc: 51.21% | Val loss: 0.8610 | Val acc: 57.60% | LR: 0.000104
Epoch: 094 | MCC: 0.023924 | Train loss: 0.9706 | Train acc: 51.31% | Val loss: 0.8587 | Val acc: 57.71% | LR: 0.000101
Epoch: 095 | MCC: 0.018655 | Train loss: 0.9710 | Train acc: 51.48% | Val loss: 0.8631 | Val acc: 57.69% | LR: 0.000098
Epoch: 096 | MCC: 0.023246 | Train loss: 0.9704 | Train acc: 51.41% | Val loss: 0.8690 | Val acc: 57.20% | LR: 0.000094
Epoch: 097 | MCC: 0.020869 | Train loss: 0.9708 | Train acc: 51.48% | Val loss: 0.8683 | Val acc: 57.05% | LR: 0.000091
Epoch: 098 | MCC: 0.023693 | Train loss: 0.9682 | Train acc: 51.73% | Val loss: 0.8611 | Val acc: 57.42% | LR: 0.000088
Epoch: 099 | MCC: 0.026375 | Train loss: 0.9703 | Train acc: 51.22% | Val loss: 0.8547 | Val acc: 58.08% | LR: 0.000085
Epoch: 100 | MCC: 0.012023 | Train loss: 0.9682 | Train acc: 51.82% | Val loss: 0.8471 | Val acc: 58.22% | LR: 0.000082
Epoch: 101 | MCC: 0.021587 | Train loss: 0.9682 | Train acc: 51.81% | Val loss: 0.8504 | Val acc: 58.08% | LR: 0.000079
Epoch: 102 | MCC: 0.025297 | Train loss: 0.9685 | Train acc: 51.22% | Val loss: 0.8527 | Val acc: 57.88% | LR: 0.000076
Epoch: 103 | MCC: 0.021629 | Train loss: 0.9695 | Train acc: 51.40% | Val loss: 0.8546 | Val acc: 57.68% | LR: 0.000073
Epoch: 104 | MCC: 0.021526 | Train loss: 0.9700 | Train acc: 51.65% | Val loss: 0.8532 | Val acc: 57.82% | LR: 0.000070
Epoch: 105 | MCC: 0.018335 | Train loss: 0.9684 | Train acc: 52.05% | Val loss: 0.8523 | Val acc: 57.83% | LR: 0.000068
Epoch: 106 | MCC: 0.021942 | Train loss: 0.9699 | Train acc: 51.70% | Val loss: 0.8498 | Val acc: 58.15% | LR: 0.000065
Epoch: 107 | MCC: 0.024980 | Train loss: 0.9677 | Train acc: 51.91% | Val loss: 0.8457 | Val acc: 58.37% | LR: 0.000062
Epoch: 108 | MCC: 0.015605 | Train loss: 0.9682 | Train acc: 52.05% | Val loss: 0.8496 | Val acc: 58.30% | LR: 0.000059
Epoch: 109 | MCC: 0.024064 | Train loss: 0.9674 | Train acc: 52.10% | Val loss: 0.8437 | Val acc: 58.69% | LR: 0.000057
Epoch: 110 | MCC: 0.050036 | Train loss: 0.9678 | Train acc: 51.87% | Val loss: 0.8367 | Val acc: 59.03% | LR: 0.000054
Epoch: 111 | MCC: 0.018354 | Train loss: 0.9667 | Train acc: 52.16% | Val loss: 0.8365 | Val acc: 58.78% | LR: 0.000052
Epoch: 112 | MCC: 0.066468 | Train loss: 0.9673 | Train acc: 51.59% | Val loss: 0.8351 | Val acc: 59.32% | LR: 0.000049
Epoch: 113 | MCC: 0.046423 | Train loss: 0.9703 | Train acc: 51.46% | Val loss: 0.8461 | Val acc: 58.49% | LR: 0.000047
Epoch: 114 | MCC: 0.052300 | Train loss: 0.9685 | Train acc: 51.24% | Val loss: 0.8386 | Val acc: 59.01% | LR: 0.000044
Epoch: 115 | MCC: 0.048484 | Train loss: 0.9682 | Train acc: 51.83% | Val loss: 0.8390 | Val acc: 58.88% | LR: 0.000042
Epoch: 116 | MCC: 0.047451 | Train loss: 0.9682 | Train acc: 52.10% | Val loss: 0.8381 | Val acc: 58.88% | LR: 0.000040
Epoch: 117 | MCC: 0.047100 | Train loss: 0.9655 | Train acc: 52.21% | Val loss: 0.8402 | Val acc: 58.81% | LR: 0.000037
Epoch: 118 | MCC: 0.062529 | Train loss: 0.9660 | Train acc: 51.71% | Val loss: 0.8354 | Val acc: 59.23% | LR: 0.000035
Epoch: 119 | MCC: 0.063142 | Train loss: 0.9673 | Train acc: 52.07% | Val loss: 0.8337 | Val acc: 59.40% | LR: 0.000033
Epoch: 120 | MCC: 0.069161 | Train loss: 0.9672 | Train acc: 51.90% | Val loss: 0.8350 | Val acc: 59.32% | LR: 0.000031
Epoch: 121 | MCC: 0.056272 | Train loss: 0.9681 | Train acc: 51.75% | Val loss: 0.8311 | Val acc: 59.28% | LR: 0.000029
Epoch: 122 | MCC: 0.077135 | Train loss: 0.9692 | Train acc: 52.04% | Val loss: 0.8326 | Val acc: 59.54% | LR: 0.000027
Epoch: 123 | MCC: 0.071245 | Train loss: 0.9677 | Train acc: 51.97% | Val loss: 0.8329 | Val acc: 59.42% | LR: 0.000025
Epoch: 124 | MCC: 0.060771 | Train loss: 0.9664 | Train acc: 52.18% | Val loss: 0.8330 | Val acc: 59.32% | LR: 0.000024
Epoch: 125 | MCC: 0.066672 | Train loss: 0.9670 | Train acc: 52.14% | Val loss: 0.8372 | Val acc: 59.36% | LR: 0.000022
Epoch: 126 | MCC: 0.072982 | Train loss: 0.9668 | Train acc: 51.98% | Val loss: 0.8333 | Val acc: 59.47% | LR: 0.000020
Epoch: 127 | MCC: 0.057736 | Train loss: 0.9662 | Train acc: 51.92% | Val loss: 0.8338 | Val acc: 59.31% | LR: 0.000019
Epoch: 128 | MCC: 0.064795 | Train loss: 0.9671 | Train acc: 52.09% | Val loss: 0.8348 | Val acc: 59.30% | LR: 0.000017
Epoch: 129 | MCC: 0.067876 | Train loss: 0.9664 | Train acc: 52.16% | Val loss: 0.8359 | Val acc: 59.41% | LR: 0.000016
Epoch: 130 | MCC: 0.063952 | Train loss: 0.9675 | Train acc: 51.33% | Val loss: 0.8349 | Val acc: 59.30% | LR: 0.000014
Epoch: 131 | MCC: 0.051180 | Train loss: 0.9670 | Train acc: 52.04% | Val loss: 0.8339 | Val acc: 59.11% | LR: 0.000013
Epoch: 132 | MCC: 0.055636 | Train loss: 0.9683 | Train acc: 51.94% | Val loss: 0.8340 | Val acc: 59.19% | LR: 0.000012
Epoch: 133 | MCC: 0.064637 | Train loss: 0.9668 | Train acc: 52.21% | Val loss: 0.8367 | Val acc: 59.38% | LR: 0.000010
Epoch: 134 | MCC: 0.067257 | Train loss: 0.9675 | Train acc: 51.97% | Val loss: 0.8336 | Val acc: 59.35% | LR: 0.000009
Epoch: 135 | MCC: 0.070277 | Train loss: 0.9670 | Train acc: 52.01% | Val loss: 0.8338 | Val acc: 59.40% | LR: 0.000008
Epoch: 136 | MCC: 0.070895 | Train loss: 0.9675 | Train acc: 52.08% | Val loss: 0.8339 | Val acc: 59.42% | LR: 0.000007
Epoch: 137 | MCC: 0.068888 | Train loss: 0.9665 | Train acc: 52.26% | Val loss: 0.8340 | Val acc: 59.32% | LR: 0.000006
Epoch: 138 | MCC: 0.054671 | Train loss: 0.9658 | Train acc: 51.81% | Val loss: 0.8340 | Val acc: 59.12% | LR: 0.000005
Epoch: 139 | MCC: 0.056813 | Train loss: 0.9678 | Train acc: 51.96% | Val loss: 0.8334 | Val acc: 59.29% | LR: 0.000005
Epoch: 140 | MCC: 0.052776 | Train loss: 0.9682 | Train acc: 52.14% | Val loss: 0.8337 | Val acc: 59.21% | LR: 0.000004
Epoch: 141 | MCC: 0.055671 | Train loss: 0.9678 | Train acc: 52.31% | Val loss: 0.8333 | Val acc: 59.22% | LR: 0.000003
Epoch: 142 | MCC: 0.055671 | Train loss: 0.9678 | Train acc: 51.78% | Val loss: 0.8332 | Val acc: 59.22% | LR: 0.000003
Epoch: 143 | MCC: 0.057722 | Train loss: 0.9649 | Train acc: 52.66% | Val loss: 0.8332 | Val acc: 59.34% | LR: 0.000002
Epoch: 144 | MCC: 0.057722 | Train loss: 0.9670 | Train acc: 51.97% | Val loss: 0.8332 | Val acc: 59.34% | LR: 0.000002
Epoch: 145 | MCC: 0.057722 | Train loss: 0.9668 | Train acc: 52.08% | Val loss: 0.8332 | Val acc: 59.34% | LR: 0.000002
Epoch: 146 | MCC: 0.057722 | Train loss: 0.9673 | Train acc: 51.97% | Val loss: 0.8332 | Val acc: 59.34% | LR: 0.000001
Epoch: 147 | MCC: 0.057722 | Train loss: 0.9664 | Train acc: 52.22% | Val loss: 0.8332 | Val acc: 59.34% | LR: 0.000001
Epoch: 148 | MCC: 0.056813 | Train loss: 0.9663 | Train acc: 52.13% | Val loss: 0.8332 | Val acc: 59.29% | LR: 0.000001
Epoch: 149 | MCC: 0.057476 | Train loss: 0.9679 | Train acc: 51.99% | Val loss: 0.8334 | Val acc: 59.34% | LR: 0.000001

[I 2025-10-05 09:32:45,803] Trial 26 finished with value: 0.0574760427698493 and parameters: {'lr': 0.0003374169403238193, 'hidden_size': 67, 'dropout': 0.11345986611893474, 'weight_decay': 0.028398908569221358}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: -0.011072 | Train loss: 0.9977 | Train acc: 50.69% | Val loss: 0.9950 | Val acc: 55.55% | LR: 0.000339
Epoch: 001 | MCC: 0.030448 | Train loss: 0.9954 | Train acc: 50.93% | Val loss: 0.9905 | Val acc: 56.14% | LR: 0.000339
Epoch: 002 | MCC: 0.023140 | Train loss: 0.9921 | Train acc: 51.00% | Val loss: 0.9833 | Val acc: 55.13% | LR: 0.000339
Epoch: 003 | MCC: 0.026658 | Train loss: 0.9880 | Train acc: 50.94% | Val loss: 0.9768 | Val acc: 54.91% | LR: 0.000338
Epoch: 004 | MCC: 0.026204 | Train loss: 0.9865 | Train acc: 50.97% | Val loss: 0.9723 | Val acc: 55.33% | LR: 0.000338
Epoch: 005 | MCC: 0.026816 | Train loss: 0.9835 | Train acc: 50.87% | Val loss: 0.9619 | Val acc: 55.47% | LR: 0.000338
Epoch: 006 | MCC: 0.028159 | Train loss: 0.9830 | Train acc: 50.93% | Val loss: 0.9546 | Val acc: 55.60% | LR: 0.000337
Epoch: 007 | MCC: 0.021328 | Train loss: 0.9819 | Train acc: 50.94% | Val loss: 0.9360 | Val acc: 55.34% | LR: 0.000337
Epoch: 008 | MCC: 0.009470 | Train loss: 0.9831 | Train acc: 50.83% | Val loss: 0.9228 | Val acc: 55.34% | LR: 0.000336
Epoch: 009 | MCC: 0.013957 | Train loss: 0.9818 | Train acc: 50.93% | Val loss: 0.9137 | Val acc: 55.67% | LR: 0.000335
Epoch: 010 | MCC: 0.023800 | Train loss: 0.9799 | Train acc: 50.99% | Val loss: 0.9082 | Val acc: 56.08% | LR: 0.000335
Epoch: 011 | MCC: 0.012911 | Train loss: 0.9797 | Train acc: 51.01% | Val loss: 0.9039 | Val acc: 55.88% | LR: 0.000334
Epoch: 012 | MCC: 0.021466 | Train loss: 0.9831 | Train acc: 50.85% | Val loss: 0.9010 | Val acc: 56.16% | LR: 0.000333
Epoch: 013 | MCC: 0.016053 | Train loss: 0.9800 | Train acc: 50.99% | Val loss: 0.8973 | Val acc: 56.03% | LR: 0.000332
Epoch: 014 | MCC: 0.023685 | Train loss: 0.9801 | Train acc: 51.04% | Val loss: 0.8934 | Val acc: 56.46% | LR: 0.000331
Epoch: 015 | MCC: 0.037119 | Train loss: 0.9786 | Train acc: 51.07% | Val loss: 0.8923 | Val acc: 57.22% | LR: 0.000330
Epoch: 016 | MCC: 0.032403 | Train loss: 0.9803 | Train acc: 50.99% | Val loss: 0.8901 | Val acc: 57.42% | LR: 0.000328
Epoch: 017 | MCC: 0.043358 | Train loss: 0.9804 | Train acc: 50.92% | Val loss: 0.8805 | Val acc: 57.81% | LR: 0.000327
Epoch: 018 | MCC: 0.042788 | Train loss: 0.9797 | Train acc: 50.97% | Val loss: 0.8805 | Val acc: 58.08% | LR: 0.000326
Epoch: 019 | MCC: 0.031273 | Train loss: 0.9790 | Train acc: 51.05% | Val loss: 0.8836 | Val acc: 57.88% | LR: 0.000324
Epoch: 020 | MCC: 0.032021 | Train loss: 0.9781 | Train acc: 51.13% | Val loss: 0.8744 | Val acc: 57.91% | LR: 0.000323
Epoch: 021 | MCC: 0.015090 | Train loss: 0.9786 | Train acc: 51.12% | Val loss: 0.8714 | Val acc: 56.95% | LR: 0.000321
Epoch: 022 | MCC: 0.016346 | Train loss: 0.9786 | Train acc: 51.06% | Val loss: 0.8694 | Val acc: 57.66% | LR: 0.000320
Epoch: 023 | MCC: 0.013235 | Train loss: 0.9753 | Train acc: 51.29% | Val loss: 0.8666 | Val acc: 57.35% | LR: 0.000318
Epoch: 024 | MCC: 0.002336 | Train loss: 0.9750 | Train acc: 51.38% | Val loss: 0.8679 | Val acc: 57.49% | LR: 0.000316
Epoch: 025 | MCC: 0.002209 | Train loss: 0.9763 | Train acc: 51.19% | Val loss: 0.8690 | Val acc: 57.34% | LR: 0.000315
Epoch: 026 | MCC: 0.015284 | Train loss: 0.9740 | Train acc: 51.35% | Val loss: 0.8695 | Val acc: 57.05% | LR: 0.000313
Epoch: 027 | MCC: 0.005232 | Train loss: 0.9736 | Train acc: 51.33% | Val loss: 0.8677 | Val acc: 57.42% | LR: 0.000311
Epoch: 028 | MCC: 0.012727 | Train loss: 0.9752 | Train acc: 51.14% | Val loss: 0.8758 | Val acc: 56.78% | LR: 0.000309
Epoch: 029 | MCC: 0.005221 | Train loss: 0.9732 | Train acc: 51.39% | Val loss: 0.8734 | Val acc: 56.58% | LR: 0.000307
Epoch: 030 | MCC: 0.016647 | Train loss: 0.9729 | Train acc: 51.36% | Val loss: 0.8653 | Val acc: 57.32% | LR: 0.000305
Epoch: 031 | MCC: 0.016399 | Train loss: 0.9745 | Train acc: 51.21% | Val loss: 0.8676 | Val acc: 57.35% | LR: 0.000303
Epoch: 032 | MCC: 0.008724 | Train loss: 0.9727 | Train acc: 51.36% | Val loss: 0.8768 | Val acc: 56.39% | LR: 0.000300
Epoch: 033 | MCC: -0.000718 | Train loss: 0.9738 | Train acc: 51.25% | Val loss: 0.8701 | Val acc: 56.76% | LR: 0.000298
Epoch: 034 | MCC: -0.006591 | Train loss: 0.9730 | Train acc: 51.24% | Val loss: 0.8630 | Val acc: 57.03% | LR: 0.000296
Epoch: 035 | MCC: -0.001546 | Train loss: 0.9730 | Train acc: 51.28% | Val loss: 0.8687 | Val acc: 56.86% | LR: 0.000293
Epoch: 036 | MCC: 0.008421 | Train loss: 0.9728 | Train acc: 51.31% | Val loss: 0.8796 | Val acc: 56.17% | LR: 0.000291
Epoch: 037 | MCC: -0.001919 | Train loss: 0.9716 | Train acc: 51.37% | Val loss: 0.8656 | Val acc: 57.32% | LR: 0.000288
Epoch: 038 | MCC: -0.002097 | Train loss: 0.9717 | Train acc: 51.44% | Val loss: 0.8703 | Val acc: 56.61% | LR: 0.000286
Epoch: 039 | MCC: 0.003315 | Train loss: 0.9719 | Train acc: 51.38% | Val loss: 0.8661 | Val acc: 57.13% | LR: 0.000283
Epoch: 040 | MCC: -0.002091 | Train loss: 0.9713 | Train acc: 51.31% | Val loss: 0.8589 | Val acc: 57.32% | LR: 0.000280
Epoch: 041 | MCC: -0.003031 | Train loss: 0.9782 | Train acc: 51.33% | Val loss: 0.8727 | Val acc: 56.49% | LR: 0.000278
Epoch: 042 | MCC: 0.007411 | Train loss: 0.9730 | Train acc: 51.21% | Val loss: 0.8813 | Val acc: 56.05% | LR: 0.000275
Epoch: 043 | MCC: -0.003918 | Train loss: 0.9726 | Train acc: 51.45% | Val loss: 0.8774 | Val acc: 56.20% | LR: 0.000272
Epoch: 044 | MCC: -0.004725 | Train loss: 0.9702 | Train acc: 51.45% | Val loss: 0.8698 | Val acc: 56.64% | LR: 0.000269
Epoch: 045 | MCC: 0.000828 | Train loss: 0.9719 | Train acc: 51.45% | Val loss: 0.8632 | Val acc: 57.10% | LR: 0.000267
Epoch: 046 | MCC: 0.002144 | Train loss: 0.9714 | Train acc: 51.37% | Val loss: 0.8618 | Val acc: 57.15% | LR: 0.000264
Epoch: 047 | MCC: 0.004014 | Train loss: 0.9702 | Train acc: 51.60% | Val loss: 0.8624 | Val acc: 57.15% | LR: 0.000261
Epoch: 048 | MCC: 0.001545 | Train loss: 0.9706 | Train acc: 51.52% | Val loss: 0.8667 | Val acc: 57.00% | LR: 0.000258
Epoch: 049 | MCC: 0.011066 | Train loss: 0.9716 | Train acc: 51.37% | Val loss: 0.8579 | Val acc: 57.57% | LR: 0.000255
Epoch: 050 | MCC: -0.007490 | Train loss: 0.9704 | Train acc: 51.45% | Val loss: 0.8751 | Val acc: 56.03% | LR: 0.000251
Epoch: 051 | MCC: -0.002622 | Train loss: 0.9725 | Train acc: 51.34% | Val loss: 0.8654 | Val acc: 56.88% | LR: 0.000248
Epoch: 052 | MCC: 0.004407 | Train loss: 0.9698 | Train acc: 51.29% | Val loss: 0.8566 | Val acc: 57.49% | LR: 0.000245
Epoch: 053 | MCC: 0.008653 | Train loss: 0.9703 | Train acc: 51.31% | Val loss: 0.8620 | Val acc: 57.25% | LR: 0.000242
Epoch: 054 | MCC: -0.003056 | Train loss: 0.9704 | Train acc: 51.47% | Val loss: 0.8704 | Val acc: 56.69% | LR: 0.000239
Epoch: 055 | MCC: 0.011403 | Train loss: 0.9716 | Train acc: 51.84% | Val loss: 0.8592 | Val acc: 57.47% | LR: 0.000236
Epoch: 056 | MCC: 0.009164 | Train loss: 0.9687 | Train acc: 52.14% | Val loss: 0.8660 | Val acc: 57.15% | LR: 0.000232
Epoch: 057 | MCC: 0.009649 | Train loss: 0.9699 | Train acc: 51.56% | Val loss: 0.8627 | Val acc: 57.35% | LR: 0.000229
Epoch: 058 | MCC: -0.007187 | Train loss: 0.9721 | Train acc: 51.27% | Val loss: 0.8704 | Val acc: 56.47% | LR: 0.000226
Epoch: 059 | MCC: 0.015597 | Train loss: 0.9702 | Train acc: 51.74% | Val loss: 0.8595 | Val acc: 57.61% | LR: 0.000222
Epoch: 060 | MCC: 0.021300 | Train loss: 0.9703 | Train acc: 51.82% | Val loss: 0.8596 | Val acc: 57.91% | LR: 0.000219
Epoch: 061 | MCC: 0.008210 | Train loss: 0.9692 | Train acc: 52.03% | Val loss: 0.8766 | Val acc: 56.74% | LR: 0.000215
Epoch: 062 | MCC: 0.008061 | Train loss: 0.9715 | Train acc: 52.19% | Val loss: 0.8748 | Val acc: 56.76% | LR: 0.000212
Epoch: 063 | MCC: 0.022494 | Train loss: 0.9706 | Train acc: 51.79% | Val loss: 0.8504 | Val acc: 58.44% | LR: 0.000209
Epoch: 064 | MCC: 0.018704 | Train loss: 0.9694 | Train acc: 51.84% | Val loss: 0.8568 | Val acc: 57.79% | LR: 0.000205
Epoch: 065 | MCC: 0.014274 | Train loss: 0.9698 | Train acc: 52.04% | Val loss: 0.8627 | Val acc: 57.49% | LR: 0.000202
Epoch: 066 | MCC: 0.012874 | Train loss: 0.9695 | Train acc: 52.06% | Val loss: 0.8550 | Val acc: 57.76% | LR: 0.000198
Epoch: 067 | MCC: 0.015757 | Train loss: 0.9701 | Train acc: 51.97% | Val loss: 0.8630 | Val acc: 57.47% | LR: 0.000195
Epoch: 068 | MCC: 0.020013 | Train loss: 0.9688 | Train acc: 52.06% | Val loss: 0.8589 | Val acc: 57.79% | LR: 0.000191
Epoch: 069 | MCC: 0.007861 | Train loss: 0.9700 | Train acc: 51.98% | Val loss: 0.8696 | Val acc: 56.96% | LR: 0.000188
Epoch: 070 | MCC: 0.011847 | Train loss: 0.9687 | Train acc: 52.08% | Val loss: 0.8688 | Val acc: 57.17% | LR: 0.000184
Epoch: 071 | MCC: 0.004696 | Train loss: 0.9694 | Train acc: 51.97% | Val loss: 0.8732 | Val acc: 56.64% | LR: 0.000181
Epoch: 072 | MCC: 0.009084 | Train loss: 0.9693 | Train acc: 52.07% | Val loss: 0.8680 | Val acc: 57.05% | LR: 0.000177
Epoch: 073 | MCC: 0.010276 | Train loss: 0.9698 | Train acc: 51.99% | Val loss: 0.8697 | Val acc: 57.08% | LR: 0.000174
Epoch: 074 | MCC: 0.013136 | Train loss: 0.9696 | Train acc: 52.03% | Val loss: 0.8682 | Val acc: 57.25% | LR: 0.000170
Epoch: 075 | MCC: 0.011487 | Train loss: 0.9686 | Train acc: 52.07% | Val loss: 0.8665 | Val acc: 57.27% | LR: 0.000166
Epoch: 076 | MCC: 0.005139 | Train loss: 0.9687 | Train acc: 52.11% | Val loss: 0.8752 | Val acc: 56.59% | LR: 0.000163
Epoch: 077 | MCC: 0.004939 | Train loss: 0.9688 | Train acc: 52.05% | Val loss: 0.8771 | Val acc: 56.66% | LR: 0.000159
Epoch: 078 | MCC: 0.004354 | Train loss: 0.9674 | Train acc: 52.10% | Val loss: 0.8701 | Val acc: 57.13% | LR: 0.000156
Epoch: 079 | MCC: -0.000105 | Train loss: 0.9685 | Train acc: 52.07% | Val loss: 0.8694 | Val acc: 57.10% | LR: 0.000152
Epoch: 080 | MCC: 0.011149 | Train loss: 0.9683 | Train acc: 52.14% | Val loss: 0.8731 | Val acc: 56.88% | LR: 0.000149
Epoch: 081 | MCC: 0.008209 | Train loss: 0.9696 | Train acc: 51.99% | Val loss: 0.8717 | Val acc: 57.03% | LR: 0.000145
Epoch: 082 | MCC: 0.002697 | Train loss: 0.9680 | Train acc: 52.05% | Val loss: 0.8756 | Val acc: 56.52% | LR: 0.000142
Epoch: 083 | MCC: 0.009057 | Train loss: 0.9681 | Train acc: 51.97% | Val loss: 0.8742 | Val acc: 56.88% | LR: 0.000138
Epoch: 084 | MCC: 0.004007 | Train loss: 0.9666 | Train acc: 52.15% | Val loss: 0.8746 | Val acc: 56.71% | LR: 0.000135
Epoch: 085 | MCC: 0.000508 | Train loss: 0.9666 | Train acc: 52.06% | Val loss: 0.8745 | Val acc: 56.74% | LR: 0.000131
Epoch: 086 | MCC: 0.014702 | Train loss: 0.9683 | Train acc: 51.95% | Val loss: 0.8659 | Val acc: 57.54% | LR: 0.000128
Epoch: 087 | MCC: 0.013626 | Train loss: 0.9677 | Train acc: 52.01% | Val loss: 0.8693 | Val acc: 57.27% | LR: 0.000125
Epoch: 088 | MCC: 0.002635 | Train loss: 0.9677 | Train acc: 52.05% | Val loss: 0.8772 | Val acc: 56.49% | LR: 0.000121
Epoch: 089 | MCC: -0.005728 | Train loss: 0.9671 | Train acc: 52.08% | Val loss: 0.8781 | Val acc: 56.42% | LR: 0.000118
Epoch: 090 | MCC: 0.009407 | Train loss: 0.9683 | Train acc: 52.03% | Val loss: 0.8721 | Val acc: 56.91% | LR: 0.000114
Epoch: 091 | MCC: 0.001358 | Train loss: 0.9690 | Train acc: 52.01% | Val loss: 0.8761 | Val acc: 56.59% | LR: 0.000111
Epoch: 092 | MCC: 0.013402 | Train loss: 0.9676 | Train acc: 52.03% | Val loss: 0.8707 | Val acc: 57.17% | LR: 0.000108
Epoch: 093 | MCC: 0.000097 | Train loss: 0.9659 | Train acc: 52.23% | Val loss: 0.8744 | Val acc: 56.71% | LR: 0.000105
Epoch: 094 | MCC: -0.001688 | Train loss: 0.9694 | Train acc: 52.00% | Val loss: 0.8775 | Val acc: 56.56% | LR: 0.000101
Epoch: 095 | MCC: -0.011887 | Train loss: 0.9674 | Train acc: 52.08% | Val loss: 0.8786 | Val acc: 56.22% | LR: 0.000098
Epoch: 096 | MCC: -0.012597 | Train loss: 0.9670 | Train acc: 52.15% | Val loss: 0.8779 | Val acc: 56.30% | LR: 0.000095
Epoch: 097 | MCC: -0.004480 | Train loss: 0.9680 | Train acc: 52.09% | Val loss: 0.8725 | Val acc: 57.00% | LR: 0.000092
Epoch: 098 | MCC: -0.003873 | Train loss: 0.9689 | Train acc: 52.01% | Val loss: 0.8733 | Val acc: 56.76% | LR: 0.000089
Epoch: 099 | MCC: -0.004099 | Train loss: 0.9690 | Train acc: 51.95% | Val loss: 0.8733 | Val acc: 57.15% | LR: 0.000086
Epoch: 100 | MCC: -0.003732 | Train loss: 0.9666 | Train acc: 52.22% | Val loss: 0.8683 | Val acc: 57.27% | LR: 0.000082
Epoch: 101 | MCC: -0.010092 | Train loss: 0.9669 | Train acc: 52.12% | Val loss: 0.8766 | Val acc: 56.47% | LR: 0.000079
Epoch: 102 | MCC: -0.002809 | Train loss: 0.9675 | Train acc: 52.05% | Val loss: 0.8746 | Val acc: 56.71% | LR: 0.000076
Epoch: 103 | MCC: -0.012153 | Train loss: 0.9682 | Train acc: 52.09% | Val loss: 0.8750 | Val acc: 56.69% | LR: 0.000074
Epoch: 104 | MCC: -0.013095 | Train loss: 0.9692 | Train acc: 51.98% | Val loss: 0.8726 | Val acc: 56.76% | LR: 0.000071
Epoch: 105 | MCC: -0.010566 | Train loss: 0.9663 | Train acc: 52.21% | Val loss: 0.8751 | Val acc: 56.78% | LR: 0.000068
Epoch: 106 | MCC: -0.004770 | Train loss: 0.9669 | Train acc: 52.10% | Val loss: 0.8689 | Val acc: 57.25% | LR: 0.000065
Epoch: 107 | MCC: -0.008431 | Train loss: 0.9678 | Train acc: 52.10% | Val loss: 0.8813 | Val acc: 56.88% | LR: 0.000062
Epoch: 108 | MCC: -0.010834 | Train loss: 0.9674 | Train acc: 52.11% | Val loss: 0.8743 | Val acc: 56.88% | LR: 0.000060
Epoch: 109 | MCC: -0.000288 | Train loss: 0.9659 | Train acc: 52.21% | Val loss: 0.8709 | Val acc: 57.30% | LR: 0.000057
Epoch: 110 | MCC: -0.013224 | Train loss: 0.9667 | Train acc: 52.17% | Val loss: 0.8759 | Val acc: 56.66% | LR: 0.000054
Epoch: 111 | MCC: -0.003165 | Train loss: 0.9670 | Train acc: 52.12% | Val loss: 0.8701 | Val acc: 57.25% | LR: 0.000052
Epoch: 112 | MCC: -0.004155 | Train loss: 0.9673 | Train acc: 52.11% | Val loss: 0.8893 | Val acc: 57.20% | LR: 0.000049
Epoch: 113 | MCC: -0.004859 | Train loss: 0.9664 | Train acc: 52.13% | Val loss: 0.8733 | Val acc: 57.17% | LR: 0.000047
Epoch: 114 | MCC: -0.005573 | Train loss: 0.9656 | Train acc: 52.16% | Val loss: 0.8779 | Val acc: 57.13% | LR: 0.000044
Epoch: 115 | MCC: -0.005790 | Train loss: 0.9671 | Train acc: 52.08% | Val loss: 0.8727 | Val acc: 57.15% | LR: 0.000042
Epoch: 116 | MCC: -0.004257 | Train loss: 0.9667 | Train acc: 52.15% | Val loss: 0.8718 | Val acc: 57.20% | LR: 0.000040
Epoch: 117 | MCC: -0.004209 | Train loss: 0.9677 | Train acc: 52.05% | Val loss: 0.8722 | Val acc: 57.17% | LR: 0.000038
Epoch: 118 | MCC: -0.007148 | Train loss: 0.9664 | Train acc: 52.17% | Val loss: 0.8719 | Val acc: 57.13% | LR: 0.000035
Epoch: 119 | MCC: -0.006453 | Train loss: 0.9669 | Train acc: 52.10% | Val loss: 0.8734 | Val acc: 57.10% | LR: 0.000033
Epoch: 120 | MCC: -0.007567 | Train loss: 0.9668 | Train acc: 52.09% | Val loss: 0.8732 | Val acc: 57.10% | LR: 0.000031
Epoch: 121 | MCC: -0.004988 | Train loss: 0.9653 | Train acc: 52.21% | Val loss: 0.8726 | Val acc: 57.13% | LR: 0.000029
Epoch: 122 | MCC: -0.004783 | Train loss: 0.9668 | Train acc: 52.16% | Val loss: 0.8718 | Val acc: 57.15% | LR: 0.000027
Epoch: 123 | MCC: -0.005070 | Train loss: 0.9657 | Train acc: 52.31% | Val loss: 0.8712 | Val acc: 57.17% | LR: 0.000025
Epoch: 124 | MCC: -0.004548 | Train loss: 0.9670 | Train acc: 52.08% | Val loss: 0.8713 | Val acc: 57.20% | LR: 0.000024
Epoch: 125 | MCC: -0.006492 | Train loss: 0.9660 | Train acc: 52.17% | Val loss: 0.8710 | Val acc: 57.13% | LR: 0.000022
Epoch: 126 | MCC: -0.003497 | Train loss: 0.9660 | Train acc: 52.26% | Val loss: 0.8717 | Val acc: 57.20% | LR: 0.000020
Epoch: 127 | MCC: -0.005439 | Train loss: 0.9676 | Train acc: 52.11% | Val loss: 0.8706 | Val acc: 57.17% | LR: 0.000019
Epoch: 128 | MCC: -0.004797 | Train loss: 0.9672 | Train acc: 52.04% | Val loss: 0.8703 | Val acc: 57.20% | LR: 0.000017
Epoch: 129 | MCC: -0.004456 | Train loss: 0.9671 | Train acc: 52.08% | Val loss: 0.8710 | Val acc: 57.20% | LR: 0.000016
Epoch: 130 | MCC: -0.004456 | Train loss: 0.9661 | Train acc: 52.10% | Val loss: 0.8709 | Val acc: 57.20% | LR: 0.000014
Epoch: 131 | MCC: -0.005266 | Train loss: 0.9669 | Train acc: 52.10% | Val loss: 0.8718 | Val acc: 57.15% | LR: 0.000013
Epoch: 132 | MCC: -0.004300 | Train loss: 0.9665 | Train acc: 52.18% | Val loss: 0.8716 | Val acc: 57.22% | LR: 0.000012
Epoch: 133 | MCC: -0.005343 | Train loss: 0.9658 | Train acc: 52.20% | Val loss: 0.8712 | Val acc: 57.17% | LR: 0.000010
Epoch: 134 | MCC: -0.005386 | Train loss: 0.9650 | Train acc: 52.21% | Val loss: 0.8706 | Val acc: 57.17% | LR: 0.000009
Epoch: 135 | MCC: -0.005266 | Train loss: 0.9675 | Train acc: 52.08% | Val loss: 0.8713 | Val acc: 57.15% | LR: 0.000008
Epoch: 136 | MCC: -0.005266 | Train loss: 0.9664 | Train acc: 52.10% | Val loss: 0.8708 | Val acc: 57.15% | LR: 0.000007
Epoch: 137 | MCC: -0.005343 | Train loss: 0.9674 | Train acc: 52.10% | Val loss: 0.8708 | Val acc: 57.17% | LR: 0.000006

[I 2025-10-05 09:34:39,460] Trial 27 finished with value: -0.005265904124826193 and parameters: {'lr': 0.00033906907422848176, 'hidden_size': 51, 'dropout': 0.07423005503177185, 'weight_decay': 0.0557540410041513}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.043247 | Train loss: 0.9957 | Train acc: 50.92% | Val loss: 0.9966 | Val acc: 54.60% | LR: 0.000540
Epoch: 001 | MCC: 0.039045 | Train loss: 0.9954 | Train acc: 50.87% | Val loss: 0.9925 | Val acc: 54.99% | LR: 0.000540
Epoch: 002 | MCC: 0.025282 | Train loss: 0.9894 | Train acc: 50.98% | Val loss: 0.9805 | Val acc: 54.87% | LR: 0.000540
Epoch: 003 | MCC: 0.036483 | Train loss: 0.9856 | Train acc: 50.91% | Val loss: 0.9661 | Val acc: 55.23% | LR: 0.000539
Epoch: 004 | MCC: 0.025174 | Train loss: 0.9851 | Train acc: 50.77% | Val loss: 0.9495 | Val acc: 55.12% | LR: 0.000539
Epoch: 005 | MCC: 0.034004 | Train loss: 0.9827 | Train acc: 50.91% | Val loss: 0.9417 | Val acc: 55.70% | LR: 0.000538
Epoch: 006 | MCC: 0.029944 | Train loss: 0.9824 | Train acc: 50.82% | Val loss: 0.9301 | Val acc: 55.88% | LR: 0.000538
Epoch: 007 | MCC: 0.033813 | Train loss: 0.9800 | Train acc: 50.87% | Val loss: 0.9175 | Val acc: 56.23% | LR: 0.000537
Epoch: 008 | MCC: 0.038363 | Train loss: 0.9791 | Train acc: 51.02% | Val loss: 0.9074 | Val acc: 56.60% | LR: 0.000536
Epoch: 009 | MCC: 0.031584 | Train loss: 0.9784 | Train acc: 50.97% | Val loss: 0.8982 | Val acc: 56.26% | LR: 0.000535
Epoch: 010 | MCC: 0.037580 | Train loss: 0.9803 | Train acc: 50.94% | Val loss: 0.8877 | Val acc: 57.09% | LR: 0.000533
Epoch: 011 | MCC: 0.043108 | Train loss: 0.9799 | Train acc: 50.71% | Val loss: 0.8837 | Val acc: 57.55% | LR: 0.000532
Epoch: 012 | MCC: 0.055548 | Train loss: 0.9784 | Train acc: 51.23% | Val loss: 0.8749 | Val acc: 58.72% | LR: 0.000530
Epoch: 013 | MCC: 0.049237 | Train loss: 0.9744 | Train acc: 51.71% | Val loss: 0.8666 | Val acc: 57.86% | LR: 0.000529
Epoch: 014 | MCC: 0.056008 | Train loss: 0.9760 | Train acc: 51.58% | Val loss: 0.8485 | Val acc: 59.08% | LR: 0.000527
Epoch: 015 | MCC: 0.027072 | Train loss: 0.9789 | Train acc: 51.72% | Val loss: 0.8717 | Val acc: 56.88% | LR: 0.000525
Epoch: 016 | MCC: 0.036257 | Train loss: 0.9748 | Train acc: 51.80% | Val loss: 0.8443 | Val acc: 59.53% | LR: 0.000523
Epoch: 017 | MCC: 0.028181 | Train loss: 0.9703 | Train acc: 51.96% | Val loss: 0.8456 | Val acc: 58.59% | LR: 0.000521
Epoch: 018 | MCC: 0.029941 | Train loss: 0.9680 | Train acc: 52.05% | Val loss: 0.8262 | Val acc: 59.47% | LR: 0.000519
Epoch: 019 | MCC: 0.027611 | Train loss: 0.9703 | Train acc: 51.80% | Val loss: 0.8501 | Val acc: 58.20% | LR: 0.000517
Epoch: 020 | MCC: 0.036769 | Train loss: 0.9691 | Train acc: 51.95% | Val loss: 0.8493 | Val acc: 58.22% | LR: 0.000515
Epoch: 021 | MCC: 0.037618 | Train loss: 0.9680 | Train acc: 52.00% | Val loss: 0.8200 | Val acc: 59.79% | LR: 0.000512
Epoch: 022 | MCC: 0.074678 | Train loss: 0.9798 | Train acc: 51.56% | Val loss: 0.8308 | Val acc: 60.89% | LR: 0.000510
Epoch: 023 | MCC: 0.043399 | Train loss: 0.9717 | Train acc: 51.91% | Val loss: 0.8317 | Val acc: 59.54% | LR: 0.000507
Epoch: 024 | MCC: 0.037418 | Train loss: 0.9679 | Train acc: 51.96% | Val loss: 0.8306 | Val acc: 58.86% | LR: 0.000504
Epoch: 025 | MCC: 0.020104 | Train loss: 0.9663 | Train acc: 52.07% | Val loss: 0.8430 | Val acc: 58.32% | LR: 0.000501
Epoch: 026 | MCC: 0.043543 | Train loss: 0.9653 | Train acc: 52.05% | Val loss: 0.8366 | Val acc: 59.03% | LR: 0.000498
Epoch: 027 | MCC: 0.067216 | Train loss: 0.9656 | Train acc: 52.00% | Val loss: 0.8221 | Val acc: 59.45% | LR: 0.000495
Epoch: 028 | MCC: 0.023147 | Train loss: 0.9915 | Train acc: 51.99% | Val loss: 0.8509 | Val acc: 57.87% | LR: 0.000492
Epoch: 029 | MCC: 0.026772 | Train loss: 0.9685 | Train acc: 51.99% | Val loss: 0.8571 | Val acc: 57.38% | LR: 0.000489
Epoch: 030 | MCC: 0.049209 | Train loss: 0.9694 | Train acc: 51.93% | Val loss: 0.8472 | Val acc: 58.14% | LR: 0.000486
Epoch: 031 | MCC: 0.066656 | Train loss: 0.9633 | Train acc: 52.14% | Val loss: 0.8206 | Val acc: 59.51% | LR: 0.000482
Epoch: 032 | MCC: 0.041566 | Train loss: 0.9626 | Train acc: 52.15% | Val loss: 0.8533 | Val acc: 57.77% | LR: 0.000479
Epoch: 033 | MCC: 0.021173 | Train loss: 0.9628 | Train acc: 52.06% | Val loss: 0.8407 | Val acc: 58.34% | LR: 0.000475
Epoch: 034 | MCC: 0.045017 | Train loss: 0.9626 | Train acc: 52.16% | Val loss: 0.8314 | Val acc: 58.74% | LR: 0.000471
Epoch: 035 | MCC: 0.038674 | Train loss: 0.9655 | Train acc: 51.96% | Val loss: 0.8300 | Val acc: 58.92% | LR: 0.000467
Epoch: 036 | MCC: 0.064671 | Train loss: 0.9658 | Train acc: 52.16% | Val loss: 0.8622 | Val acc: 57.32% | LR: 0.000463
Epoch: 037 | MCC: 0.017332 | Train loss: 0.9637 | Train acc: 52.06% | Val loss: 0.8401 | Val acc: 58.34% | LR: 0.000459
Epoch: 038 | MCC: 0.033881 | Train loss: 0.9669 | Train acc: 52.03% | Val loss: 0.8551 | Val acc: 57.68% | LR: 0.000455
Epoch: 039 | MCC: 0.060413 | Train loss: 0.9650 | Train acc: 52.01% | Val loss: 0.8354 | Val acc: 58.87% | LR: 0.000451
Epoch: 040 | MCC: 0.026157 | Train loss: 0.9633 | Train acc: 52.09% | Val loss: 0.8829 | Val acc: 57.54% | LR: 0.000447
Epoch: 041 | MCC: 0.015811 | Train loss: 0.9664 | Train acc: 51.89% | Val loss: 0.8471 | Val acc: 57.91% | LR: 0.000443
Epoch: 042 | MCC: 0.031806 | Train loss: 0.9646 | Train acc: 51.96% | Val loss: 0.8626 | Val acc: 58.31% | LR: 0.000438
Epoch: 043 | MCC: 0.077014 | Train loss: 0.9639 | Train acc: 51.98% | Val loss: 0.8148 | Val acc: 59.76% | LR: 0.000434
Epoch: 044 | MCC: 0.028149 | Train loss: 0.9619 | Train acc: 52.09% | Val loss: 0.8388 | Val acc: 58.64% | LR: 0.000429
Epoch: 045 | MCC: 0.015359 | Train loss: 0.9607 | Train acc: 52.11% | Val loss: 0.8646 | Val acc: 58.63% | LR: 0.000425
Epoch: 046 | MCC: 0.026905 | Train loss: 0.9603 | Train acc: 52.15% | Val loss: 0.8563 | Val acc: 58.21% | LR: 0.000420
Epoch: 047 | MCC: 0.007618 | Train loss: 0.9604 | Train acc: 52.17% | Val loss: 0.8636 | Val acc: 57.65% | LR: 0.000415
Epoch: 048 | MCC: 0.009342 | Train loss: 0.9606 | Train acc: 52.11% | Val loss: 0.9208 | Val acc: 57.75% | LR: 0.000410
Epoch: 049 | MCC: 0.042450 | Train loss: 0.9633 | Train acc: 52.13% | Val loss: 0.8894 | Val acc: 57.61% | LR: 0.000406
Epoch: 050 | MCC: 0.044674 | Train loss: 0.9612 | Train acc: 52.04% | Val loss: 0.8558 | Val acc: 58.37% | LR: 0.000401
Epoch: 051 | MCC: 0.050664 | Train loss: 0.9622 | Train acc: 52.03% | Val loss: 0.8474 | Val acc: 59.22% | LR: 0.000396
Epoch: 052 | MCC: 0.043167 | Train loss: 0.9600 | Train acc: 52.14% | Val loss: 0.8377 | Val acc: 58.56% | LR: 0.000391
Epoch: 053 | MCC: 0.041496 | Train loss: 0.9600 | Train acc: 52.17% | Val loss: 0.8481 | Val acc: 58.42% | LR: 0.000386
Epoch: 054 | MCC: 0.051318 | Train loss: 0.9584 | Train acc: 52.22% | Val loss: 1.2154 | Val acc: 58.71% | LR: 0.000380
Epoch: 055 | MCC: 0.047458 | Train loss: 0.9608 | Train acc: 52.10% | Val loss: 0.8505 | Val acc: 58.93% | LR: 0.000375
Epoch: 056 | MCC: 0.000887 | Train loss: 0.9593 | Train acc: 52.19% | Val loss: 1.3252 | Val acc: 57.86% | LR: 0.000370
Epoch: 057 | MCC: 0.062750 | Train loss: 0.9605 | Train acc: 52.10% | Val loss: 0.8241 | Val acc: 59.51% | LR: 0.000365
Epoch: 058 | MCC: 0.049653 | Train loss: 0.9610 | Train acc: 52.11% | Val loss: 0.8427 | Val acc: 58.54% | LR: 0.000359
Epoch: 059 | MCC: 0.045919 | Train loss: 0.9612 | Train acc: 52.07% | Val loss: 0.8356 | Val acc: 59.03% | LR: 0.000354
Epoch: 060 | MCC: 0.044929 | Train loss: 0.9608 | Train acc: 52.09% | Val loss: 0.8247 | Val acc: 59.08% | LR: 0.000349
Epoch: 061 | MCC: 0.043686 | Train loss: 0.9597 | Train acc: 52.15% | Val loss: 0.8372 | Val acc: 58.69% | LR: 0.000343
Epoch: 062 | MCC: 0.052428 | Train loss: 0.9604 | Train acc: 52.10% | Val loss: 0.8364 | Val acc: 58.76% | LR: 0.000338
Epoch: 063 | MCC: 0.040279 | Train loss: 0.9608 | Train acc: 52.08% | Val loss: 0.8442 | Val acc: 58.10% | LR: 0.000332
Epoch: 064 | MCC: 0.048655 | Train loss: 0.9593 | Train acc: 52.15% | Val loss: 0.8429 | Val acc: 57.98% | LR: 0.000327
Epoch: 065 | MCC: 0.053312 | Train loss: 0.9603 | Train acc: 52.14% | Val loss: 0.8261 | Val acc: 58.93% | LR: 0.000321
Epoch: 066 | MCC: 0.055166 | Train loss: 0.9590 | Train acc: 52.17% | Val loss: 0.8312 | Val acc: 58.79% | LR: 0.000316
Epoch: 067 | MCC: 0.056814 | Train loss: 0.9590 | Train acc: 52.19% | Val loss: 0.8165 | Val acc: 59.50% | LR: 0.000310
Epoch: 068 | MCC: 0.046534 | Train loss: 0.9605 | Train acc: 52.10% | Val loss: 0.8385 | Val acc: 58.27% | LR: 0.000304
Epoch: 069 | MCC: 0.055436 | Train loss: 0.9650 | Train acc: 51.86% | Val loss: 0.8231 | Val acc: 59.25% | LR: 0.000299
Epoch: 070 | MCC: 0.053345 | Train loss: 0.9596 | Train acc: 52.16% | Val loss: 0.8416 | Val acc: 58.64% | LR: 0.000293
Epoch: 071 | MCC: 0.051743 | Train loss: 0.9597 | Train acc: 52.15% | Val loss: 0.8328 | Val acc: 58.96% | LR: 0.000288
Epoch: 072 | MCC: 0.063068 | Train loss: 0.9624 | Train acc: 52.00% | Val loss: 0.8253 | Val acc: 59.27% | LR: 0.000282
Epoch: 073 | MCC: 0.068728 | Train loss: 0.9616 | Train acc: 52.04% | Val loss: 0.8324 | Val acc: 58.75% | LR: 0.000276
Epoch: 074 | MCC: 0.070429 | Train loss: 0.9618 | Train acc: 52.08% | Val loss: 0.8166 | Val acc: 59.85% | LR: 0.000271
Epoch: 075 | MCC: 0.022018 | Train loss: 0.9577 | Train acc: 52.26% | Val loss: 0.8326 | Val acc: 58.78% | LR: 0.000265
Epoch: 076 | MCC: 0.062652 | Train loss: 0.9587 | Train acc: 52.21% | Val loss: 0.8224 | Val acc: 59.49% | LR: 0.000259
Epoch: 077 | MCC: 0.048247 | Train loss: 0.9587 | Train acc: 52.21% | Val loss: 0.8306 | Val acc: 58.73% | LR: 0.000254
Epoch: 078 | MCC: 0.049253 | Train loss: 0.9609 | Train acc: 52.07% | Val loss: 0.8346 | Val acc: 58.54% | LR: 0.000248
Epoch: 079 | MCC: 0.052701 | Train loss: 0.9578 | Train acc: 52.24% | Val loss: 0.8206 | Val acc: 59.29% | LR: 0.000243
Epoch: 080 | MCC: 0.056392 | Train loss: 0.9586 | Train acc: 52.18% | Val loss: 0.8278 | Val acc: 58.98% | LR: 0.000237
Epoch: 081 | MCC: 0.060728 | Train loss: 0.9578 | Train acc: 52.25% | Val loss: 0.8261 | Val acc: 59.26% | LR: 0.000231
Epoch: 082 | MCC: 0.014873 | Train loss: 0.9598 | Train acc: 52.15% | Val loss: 0.8423 | Val acc: 58.31% | LR: 0.000226
Epoch: 083 | MCC: 0.032951 | Train loss: 0.9636 | Train acc: 51.95% | Val loss: 0.8427 | Val acc: 58.59% | LR: 0.000220
Epoch: 084 | MCC: 0.057805 | Train loss: 0.9604 | Train acc: 52.12% | Val loss: 0.8183 | Val acc: 59.97% | LR: 0.000215
Epoch: 085 | MCC: 0.065194 | Train loss: 0.9630 | Train acc: 51.98% | Val loss: 0.8164 | Val acc: 59.74% | LR: 0.000209
Epoch: 086 | MCC: 0.048421 | Train loss: 0.9610 | Train acc: 52.09% | Val loss: 0.8364 | Val acc: 58.49% | LR: 0.000204
Epoch: 087 | MCC: 0.023599 | Train loss: 0.9583 | Train acc: 52.23% | Val loss: 0.8400 | Val acc: 58.48% | LR: 0.000198
Epoch: 088 | MCC: 0.048918 | Train loss: 0.9597 | Train acc: 52.14% | Val loss: 0.8221 | Val acc: 59.31% | LR: 0.000193
Epoch: 089 | MCC: 0.025158 | Train loss: 0.9577 | Train acc: 52.26% | Val loss: 0.8340 | Val acc: 58.63% | LR: 0.000187
Epoch: 090 | MCC: 0.047896 | Train loss: 0.9590 | Train acc: 52.17% | Val loss: 0.8314 | Val acc: 58.74% | LR: 0.000182
Epoch: 091 | MCC: 0.051824 | Train loss: 0.9561 | Train acc: 52.32% | Val loss: 0.8312 | Val acc: 58.81% | LR: 0.000177
Epoch: 092 | MCC: 0.046672 | Train loss: 0.9587 | Train acc: 52.20% | Val loss: 0.8365 | Val acc: 58.64% | LR: 0.000171
Epoch: 093 | MCC: 0.051024 | Train loss: 0.9589 | Train acc: 52.20% | Val loss: 0.8352 | Val acc: 58.71% | LR: 0.000166
Epoch: 094 | MCC: 0.050919 | Train loss: 0.9590 | Train acc: 52.18% | Val loss: 0.8341 | Val acc: 58.74% | LR: 0.000161
Epoch: 095 | MCC: 0.022575 | Train loss: 0.9593 | Train acc: 52.14% | Val loss: 0.8335 | Val acc: 58.61% | LR: 0.000156
Epoch: 096 | MCC: 0.023559 | Train loss: 0.9591 | Train acc: 52.17% | Val loss: 0.8368 | Val acc: 58.61% | LR: 0.000151
Epoch: 097 | MCC: 0.051335 | Train loss: 0.9588 | Train acc: 52.19% | Val loss: 0.8316 | Val acc: 58.81% | LR: 0.000146
Epoch: 098 | MCC: 0.053590 | Train loss: 0.9558 | Train acc: 52.32% | Val loss: 0.8285 | Val acc: 58.96% | LR: 0.000141
Epoch: 099 | MCC: 0.028795 | Train loss: 0.9564 | Train acc: 52.32% | Val loss: 0.8360 | Val acc: 58.66% | LR: 0.000136
Epoch: 100 | MCC: 0.055265 | Train loss: 0.9558 | Train acc: 52.31% | Val loss: 0.8271 | Val acc: 59.13% | LR: 0.000131
Epoch: 101 | MCC: 0.050207 | Train loss: 0.9555 | Train acc: 52.34% | Val loss: 0.8270 | Val acc: 59.24% | LR: 0.000126
Epoch: 102 | MCC: 0.050279 | Train loss: 0.9562 | Train acc: 52.29% | Val loss: 0.8304 | Val acc: 59.07% | LR: 0.000121
Epoch: 103 | MCC: 0.066236 | Train loss: 0.9589 | Train acc: 52.19% | Val loss: 0.8151 | Val acc: 59.90% | LR: 0.000117
Epoch: 104 | MCC: 0.048037 | Train loss: 0.9576 | Train acc: 52.25% | Val loss: 0.8219 | Val acc: 59.39% | LR: 0.000112
Epoch: 105 | MCC: 0.045129 | Train loss: 0.9584 | Train acc: 52.22% | Val loss: 0.8287 | Val acc: 59.12% | LR: 0.000108
Epoch: 106 | MCC: 0.046505 | Train loss: 0.9561 | Train acc: 52.30% | Val loss: 0.8312 | Val acc: 58.82% | LR: 0.000103
Epoch: 107 | MCC: 0.050844 | Train loss: 0.9564 | Train acc: 52.31% | Val loss: 0.8364 | Val acc: 58.74% | LR: 0.000099
Epoch: 108 | MCC: 0.049425 | Train loss: 0.9605 | Train acc: 52.09% | Val loss: 0.8373 | Val acc: 58.57% | LR: 0.000094
Epoch: 109 | MCC: 0.028637 | Train loss: 0.9577 | Train acc: 52.25% | Val loss: 0.8307 | Val acc: 59.00% | LR: 0.000090
Epoch: 110 | MCC: 0.052211 | Train loss: 0.9581 | Train acc: 52.21% | Val loss: 0.8339 | Val acc: 58.76% | LR: 0.000086
Epoch: 111 | MCC: 0.047396 | Train loss: 0.9571 | Train acc: 52.28% | Val loss: 0.8314 | Val acc: 58.95% | LR: 0.000082
Epoch: 112 | MCC: 0.046215 | Train loss: 0.9566 | Train acc: 52.29% | Val loss: 0.8290 | Val acc: 59.14% | LR: 0.000078
Epoch: 113 | MCC: 0.043315 | Train loss: 0.9579 | Train acc: 52.23% | Val loss: 0.8312 | Val acc: 58.85% | LR: 0.000074
Epoch: 114 | MCC: 0.047851 | Train loss: 0.9572 | Train acc: 52.24% | Val loss: 0.8330 | Val acc: 58.76% | LR: 0.000070
Epoch: 115 | MCC: 0.057882 | Train loss: 0.9561 | Train acc: 52.32% | Val loss: 0.8154 | Val acc: 59.69% | LR: 0.000067
Epoch: 116 | MCC: 0.046699 | Train loss: 0.9553 | Train acc: 52.34% | Val loss: 0.8320 | Val acc: 59.00% | LR: 0.000063
Epoch: 117 | MCC: 0.042118 | Train loss: 0.9557 | Train acc: 52.33% | Val loss: 0.8353 | Val acc: 58.61% | LR: 0.000059

[I 2025-10-05 09:36:23,356] Trial 28 finished with value: 0.050927747040987015 and parameters: {'lr': 0.0005403952542783472, 'hidden_size': 70, 'dropout': 0.1316758956327077, 'weight_decay': 0.006639678601144102}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.031743 | Train loss: 0.9962 | Train acc: 50.55% | Val loss: 0.9935 | Val acc: 51.67% | LR: 0.001105
Epoch: 001 | MCC: 0.044154 | Train loss: 0.9900 | Train acc: 50.68% | Val loss: 0.9773 | Val acc: 54.52% | LR: 0.001105
Epoch: 002 | MCC: 0.042452 | Train loss: 0.9874 | Train acc: 50.74% | Val loss: 0.9658 | Val acc: 55.47% | LR: 0.001104
Epoch: 003 | MCC: 0.042047 | Train loss: 1.0081 | Train acc: 50.93% | Val loss: 0.9495 | Val acc: 55.46% | LR: 0.001103
Epoch: 004 | MCC: 0.024183 | Train loss: 0.9850 | Train acc: 50.93% | Val loss: 0.9295 | Val acc: 55.64% | LR: 0.001102
Epoch: 005 | MCC: 0.015730 | Train loss: 0.9821 | Train acc: 50.98% | Val loss: 0.9150 | Val acc: 55.71% | LR: 0.001101
Epoch: 006 | MCC: 0.020255 | Train loss: 0.9805 | Train acc: 50.93% | Val loss: 0.8953 | Val acc: 56.45% | LR: 0.001099
Epoch: 007 | MCC: 0.037435 | Train loss: 0.9800 | Train acc: 50.88% | Val loss: 0.8927 | Val acc: 58.25% | LR: 0.001098
Epoch: 008 | MCC: 0.033752 | Train loss: 0.9798 | Train acc: 51.19% | Val loss: 0.8798 | Val acc: 57.87% | LR: 0.001096
Epoch: 009 | MCC: 0.029572 | Train loss: 0.9793 | Train acc: 51.10% | Val loss: 0.8757 | Val acc: 57.41% | LR: 0.001093
Epoch: 010 | MCC: 0.016027 | Train loss: 0.9765 | Train acc: 51.17% | Val loss: 0.8589 | Val acc: 58.07% | LR: 0.001091
Epoch: 011 | MCC: 0.003772 | Train loss: 0.9753 | Train acc: 51.23% | Val loss: 0.8823 | Val acc: 57.59% | LR: 0.001088
Epoch: 012 | MCC: 0.013439 | Train loss: 0.9742 | Train acc: 51.28% | Val loss: 0.8581 | Val acc: 58.95% | LR: 0.001085
Epoch: 013 | MCC: 0.020365 | Train loss: 0.9737 | Train acc: 51.19% | Val loss: 0.8811 | Val acc: 56.25% | LR: 0.001082
Epoch: 014 | MCC: 0.032210 | Train loss: 0.9726 | Train acc: 51.44% | Val loss: 0.8664 | Val acc: 57.40% | LR: 0.001078
Epoch: 015 | MCC: 0.016597 | Train loss: 0.9771 | Train acc: 51.45% | Val loss: 0.8820 | Val acc: 56.28% | LR: 0.001075
Epoch: 016 | MCC: 0.028702 | Train loss: 0.9752 | Train acc: 51.24% | Val loss: 0.8461 | Val acc: 58.96% | LR: 0.001071
Epoch: 017 | MCC: 0.009261 | Train loss: 0.9733 | Train acc: 51.31% | Val loss: 0.8670 | Val acc: 57.20% | LR: 0.001067
Epoch: 018 | MCC: 0.012570 | Train loss: 0.9717 | Train acc: 51.68% | Val loss: 0.8526 | Val acc: 58.24% | LR: 0.001062
Epoch: 019 | MCC: 0.015950 | Train loss: 0.9751 | Train acc: 51.21% | Val loss: 0.8763 | Val acc: 56.76% | LR: 0.001058
Epoch: 020 | MCC: 0.014887 | Train loss: 0.9755 | Train acc: 51.41% | Val loss: 0.8561 | Val acc: 58.22% | LR: 0.001053
Epoch: 021 | MCC: -0.027794 | Train loss: 1.1718 | Train acc: 51.10% | Val loss: 0.8823 | Val acc: 56.04% | LR: 0.001048
Epoch: 022 | MCC: 0.011491 | Train loss: 0.9915 | Train acc: 51.31% | Val loss: 0.8565 | Val acc: 58.02% | LR: 0.001043
Epoch: 023 | MCC: 0.011729 | Train loss: 0.9738 | Train acc: 51.28% | Val loss: 0.8555 | Val acc: 57.48% | LR: 0.001037
Epoch: 024 | MCC: 0.016298 | Train loss: 0.9735 | Train acc: 51.40% | Val loss: 0.8727 | Val acc: 57.11% | LR: 0.001031
Epoch: 025 | MCC: 0.001684 | Train loss: 0.9704 | Train acc: 51.36% | Val loss: 0.8739 | Val acc: 56.52% | LR: 0.001026
Epoch: 026 | MCC: 0.023184 | Train loss: 0.9715 | Train acc: 51.26% | Val loss: 0.8769 | Val acc: 56.71% | LR: 0.001019
Epoch: 027 | MCC: 0.022441 | Train loss: 0.9728 | Train acc: 51.29% | Val loss: 0.8540 | Val acc: 58.58% | LR: 0.001013
Epoch: 028 | MCC: 0.032095 | Train loss: 0.9716 | Train acc: 51.46% | Val loss: 0.8710 | Val acc: 57.01% | LR: 0.001007
Epoch: 029 | MCC: 0.025689 | Train loss: 0.9696 | Train acc: 51.60% | Val loss: 0.8682 | Val acc: 56.60% | LR: 0.001000
Epoch: 030 | MCC: 0.028790 | Train loss: 0.9764 | Train acc: 51.10% | Val loss: 0.8656 | Val acc: 56.59% | LR: 0.000993
Epoch: 031 | MCC: 0.004196 | Train loss: 0.9747 | Train acc: 51.16% | Val loss: 0.8859 | Val acc: 55.96% | LR: 0.000986
Epoch: 032 | MCC: 0.005045 | Train loss: 0.9725 | Train acc: 51.38% | Val loss: 0.8477 | Val acc: 57.99% | LR: 0.000979
Epoch: 033 | MCC: 0.013010 | Train loss: 0.9745 | Train acc: 51.19% | Val loss: 0.8497 | Val acc: 58.14% | LR: 0.000971
Epoch: 034 | MCC: 0.011578 | Train loss: 0.9720 | Train acc: 51.36% | Val loss: 0.8443 | Val acc: 58.50% | LR: 0.000964
Epoch: 035 | MCC: 0.006743 | Train loss: 0.9712 | Train acc: 51.31% | Val loss: 0.8679 | Val acc: 57.17% | LR: 0.000956
Epoch: 036 | MCC: 0.011518 | Train loss: 0.9696 | Train acc: 51.40% | Val loss: 0.8631 | Val acc: 57.42% | LR: 0.000948
Epoch: 037 | MCC: 0.011017 | Train loss: 0.9758 | Train acc: 51.27% | Val loss: 0.8564 | Val acc: 57.72% | LR: 0.000940
Epoch: 038 | MCC: 0.024767 | Train loss: 0.9702 | Train acc: 51.44% | Val loss: 0.8611 | Val acc: 57.36% | LR: 0.000931
Epoch: 039 | MCC: 0.028235 | Train loss: 0.9676 | Train acc: 51.77% | Val loss: 0.8497 | Val acc: 58.29% | LR: 0.000923
Epoch: 040 | MCC: 0.023965 | Train loss: 0.9675 | Train acc: 51.48% | Val loss: 0.8558 | Val acc: 57.41% | LR: 0.000914
Epoch: 041 | MCC: 0.020612 | Train loss: 0.9652 | Train acc: 51.65% | Val loss: 0.8517 | Val acc: 57.68% | LR: 0.000905
Epoch: 042 | MCC: -0.000088 | Train loss: 0.9693 | Train acc: 51.44% | Val loss: 0.8764 | Val acc: 56.05% | LR: 0.000896
Epoch: 043 | MCC: 0.010803 | Train loss: 0.9684 | Train acc: 51.52% | Val loss: 0.8502 | Val acc: 58.17% | LR: 0.000887
Epoch: 044 | MCC: 0.022420 | Train loss: 0.9682 | Train acc: 51.94% | Val loss: 0.8664 | Val acc: 56.78% | LR: 0.000878
Epoch: 045 | MCC: 0.035145 | Train loss: 0.9667 | Train acc: 51.96% | Val loss: 0.8802 | Val acc: 56.22% | LR: 0.000868
Epoch: 046 | MCC: 0.038667 | Train loss: 0.9727 | Train acc: 51.80% | Val loss: 0.8484 | Val acc: 57.72% | LR: 0.000859
Epoch: 047 | MCC: 0.055424 | Train loss: 0.9734 | Train acc: 51.33% | Val loss: 0.8352 | Val acc: 58.75% | LR: 0.000849
Epoch: 048 | MCC: 0.059961 | Train loss: 0.9694 | Train acc: 51.67% | Val loss: 0.8403 | Val acc: 58.34% | LR: 0.000839
Epoch: 049 | MCC: 0.018085 | Train loss: 0.9675 | Train acc: 52.20% | Val loss: 0.8499 | Val acc: 57.86% | LR: 0.000829
Epoch: 050 | MCC: 0.013279 | Train loss: 0.9689 | Train acc: 52.14% | Val loss: 0.8650 | Val acc: 57.25% | LR: 0.000819
Epoch: 051 | MCC: 0.044980 | Train loss: 0.9722 | Train acc: 51.80% | Val loss: 0.8517 | Val acc: 58.04% | LR: 0.000809
Epoch: 052 | MCC: 0.056582 | Train loss: 0.9766 | Train acc: 51.76% | Val loss: 0.8190 | Val acc: 59.59% | LR: 0.000799
Epoch: 053 | MCC: 0.068102 | Train loss: 0.9776 | Train acc: 51.70% | Val loss: 0.8103 | Val acc: 60.38% | LR: 0.000788
Epoch: 054 | MCC: 0.057661 | Train loss: 0.9777 | Train acc: 51.63% | Val loss: 0.8267 | Val acc: 59.24% | LR: 0.000778
Epoch: 055 | MCC: 0.058017 | Train loss: 0.9762 | Train acc: 51.74% | Val loss: 0.8265 | Val acc: 59.94% | LR: 0.000767
Epoch: 056 | MCC: 0.071829 | Train loss: 0.9767 | Train acc: 51.69% | Val loss: 0.8193 | Val acc: 60.35% | LR: 0.000756
Epoch: 057 | MCC: 0.068071 | Train loss: 0.9781 | Train acc: 51.57% | Val loss: 0.8041 | Val acc: 60.40% | LR: 0.000746
Epoch: 058 | MCC: 0.066744 | Train loss: 0.9756 | Train acc: 51.70% | Val loss: 0.8130 | Val acc: 60.13% | LR: 0.000735
Epoch: 059 | MCC: 0.059529 | Train loss: 0.9781 | Train acc: 51.57% | Val loss: 0.8737 | Val acc: 56.84% | LR: 0.000724
Epoch: 060 | MCC: 0.055614 | Train loss: 0.9812 | Train acc: 51.46% | Val loss: 0.8620 | Val acc: 57.06% | LR: 0.000713
Epoch: 061 | MCC: 0.032985 | Train loss: 0.9769 | Train acc: 51.76% | Val loss: 0.8801 | Val acc: 56.51% | LR: 0.000702
Epoch: 062 | MCC: 0.018542 | Train loss: 0.9779 | Train acc: 51.44% | Val loss: 0.8724 | Val acc: 58.78% | LR: 0.000691
Epoch: 063 | MCC: -0.003001 | Train loss: 0.9750 | Train acc: 51.82% | Val loss: 0.8786 | Val acc: 57.69% | LR: 0.000679
Epoch: 064 | MCC: 0.002398 | Train loss: 0.9743 | Train acc: 51.88% | Val loss: 0.8533 | Val acc: 57.91% | LR: 0.000668
Epoch: 065 | MCC: 0.046064 | Train loss: 0.9700 | Train acc: 52.31% | Val loss: 0.8477 | Val acc: 58.92% | LR: 0.000657
Epoch: 066 | MCC: 0.041845 | Train loss: 0.9963 | Train acc: 51.09% | Val loss: 0.8648 | Val acc: 57.33% | LR: 0.000645
Epoch: 067 | MCC: 0.030770 | Train loss: 0.9756 | Train acc: 51.55% | Val loss: 0.8505 | Val acc: 58.20% | LR: 0.000634
Epoch: 068 | MCC: 0.034129 | Train loss: 0.9734 | Train acc: 51.57% | Val loss: 0.8460 | Val acc: 58.68% | LR: 0.000622
Epoch: 069 | MCC: 0.021296 | Train loss: 0.9739 | Train acc: 51.55% | Val loss: 0.8518 | Val acc: 58.32% | LR: 0.000611
Epoch: 070 | MCC: 0.029637 | Train loss: 0.9759 | Train acc: 51.49% | Val loss: 0.8347 | Val acc: 59.02% | LR: 0.000599
Epoch: 071 | MCC: 0.016707 | Train loss: 0.9732 | Train acc: 51.51% | Val loss: 0.8516 | Val acc: 58.14% | LR: 0.000588
Epoch: 072 | MCC: 0.022962 | Train loss: 0.9775 | Train acc: 51.27% | Val loss: 0.8532 | Val acc: 57.82% | LR: 0.000576
Epoch: 073 | MCC: 0.058087 | Train loss: 0.9705 | Train acc: 51.53% | Val loss: 0.8375 | Val acc: 58.76% | LR: 0.000565
Epoch: 074 | MCC: 0.025304 | Train loss: 0.9773 | Train acc: 51.23% | Val loss: 0.8433 | Val acc: 58.50% | LR: 0.000553
Epoch: 075 | MCC: 0.066761 | Train loss: 0.9705 | Train acc: 51.59% | Val loss: 0.8301 | Val acc: 59.18% | LR: 0.000542
Epoch: 076 | MCC: 0.094648 | Train loss: 0.9741 | Train acc: 51.40% | Val loss: 0.8097 | Val acc: 60.17% | LR: 0.000530
Epoch: 077 | MCC: 0.109039 | Train loss: 0.9771 | Train acc: 51.14% | Val loss: 0.8102 | Val acc: 60.81% | LR: 0.000519
Epoch: 078 | MCC: 0.067504 | Train loss: 0.9740 | Train acc: 51.35% | Val loss: 0.8291 | Val acc: 59.43% | LR: 0.000507
Epoch: 079 | MCC: 0.065087 | Train loss: 0.9734 | Train acc: 51.53% | Val loss: 0.8268 | Val acc: 59.43% | LR: 0.000495
Epoch: 080 | MCC: 0.079002 | Train loss: 0.9720 | Train acc: 51.49% | Val loss: 0.8229 | Val acc: 59.46% | LR: 0.000484
Epoch: 081 | MCC: 0.060591 | Train loss: 0.9748 | Train acc: 51.39% | Val loss: 0.8289 | Val acc: 59.31% | LR: 0.000473
Epoch: 082 | MCC: 0.052513 | Train loss: 0.9714 | Train acc: 51.45% | Val loss: 0.8307 | Val acc: 59.06% | LR: 0.000461
Epoch: 083 | MCC: 0.051204 | Train loss: 0.9750 | Train acc: 51.35% | Val loss: 0.8354 | Val acc: 58.73% | LR: 0.000450
Epoch: 084 | MCC: 0.036273 | Train loss: 0.9738 | Train acc: 51.44% | Val loss: 0.8349 | Val acc: 58.66% | LR: 0.000438
Epoch: 085 | MCC: 0.051876 | Train loss: 0.9714 | Train acc: 51.57% | Val loss: 0.8351 | Val acc: 58.99% | LR: 0.000427
Epoch: 086 | MCC: 0.063527 | Train loss: 0.9726 | Train acc: 51.46% | Val loss: 0.8208 | Val acc: 59.63% | LR: 0.000416
Epoch: 087 | MCC: 0.070630 | Train loss: 0.9737 | Train acc: 51.40% | Val loss: 0.8180 | Val acc: 59.62% | LR: 0.000405
Epoch: 088 | MCC: 0.057343 | Train loss: 0.9731 | Train acc: 51.43% | Val loss: 0.8284 | Val acc: 59.08% | LR: 0.000394
Epoch: 089 | MCC: 0.059285 | Train loss: 0.9713 | Train acc: 51.44% | Val loss: 0.8257 | Val acc: 59.35% | LR: 0.000383
Epoch: 090 | MCC: 0.045434 | Train loss: 0.9740 | Train acc: 51.43% | Val loss: 0.8384 | Val acc: 58.73% | LR: 0.000372
Epoch: 091 | MCC: 0.056115 | Train loss: 0.9713 | Train acc: 51.43% | Val loss: 0.8245 | Val acc: 59.44% | LR: 0.000361
Epoch: 092 | MCC: 0.038698 | Train loss: 0.9725 | Train acc: 51.44% | Val loss: 0.8305 | Val acc: 58.93% | LR: 0.000350
Epoch: 093 | MCC: 0.049893 | Train loss: 0.9717 | Train acc: 51.43% | Val loss: 0.8164 | Val acc: 59.75% | LR: 0.000339
Epoch: 094 | MCC: 0.048084 | Train loss: 0.9700 | Train acc: 51.57% | Val loss: 0.8286 | Val acc: 59.23% | LR: 0.000329
Epoch: 095 | MCC: 0.035104 | Train loss: 0.9687 | Train acc: 51.60% | Val loss: 0.8336 | Val acc: 58.71% | LR: 0.000318
Epoch: 096 | MCC: 0.030601 | Train loss: 0.9728 | Train acc: 51.44% | Val loss: 0.8460 | Val acc: 58.03% | LR: 0.000308
Epoch: 097 | MCC: 0.029441 | Train loss: 0.9751 | Train acc: 51.28% | Val loss: 0.8403 | Val acc: 58.29% | LR: 0.000297
Epoch: 098 | MCC: 0.027693 | Train loss: 0.9721 | Train acc: 51.47% | Val loss: 0.8483 | Val acc: 57.93% | LR: 0.000287
Epoch: 099 | MCC: 0.033088 | Train loss: 0.9707 | Train acc: 51.54% | Val loss: 0.8451 | Val acc: 58.14% | LR: 0.000277
Epoch: 100 | MCC: 0.042219 | Train loss: 0.9715 | Train acc: 51.56% | Val loss: 0.8403 | Val acc: 58.50% | LR: 0.000267
Epoch: 101 | MCC: 0.038396 | Train loss: 0.9726 | Train acc: 51.44% | Val loss: 0.8485 | Val acc: 57.93% | LR: 0.000257
Epoch: 102 | MCC: 0.044044 | Train loss: 0.9709 | Train acc: 51.50% | Val loss: 0.8355 | Val acc: 58.45% | LR: 0.000248
Epoch: 103 | MCC: 0.036856 | Train loss: 0.9717 | Train acc: 51.49% | Val loss: 0.8357 | Val acc: 58.59% | LR: 0.000238
Epoch: 104 | MCC: 0.029998 | Train loss: 0.9711 | Train acc: 51.49% | Val loss: 0.8377 | Val acc: 58.68% | LR: 0.000229
Epoch: 105 | MCC: 0.040790 | Train loss: 0.9684 | Train acc: 51.68% | Val loss: 0.8306 | Val acc: 58.89% | LR: 0.000219
Epoch: 106 | MCC: 0.045236 | Train loss: 0.9701 | Train acc: 51.53% | Val loss: 0.8338 | Val acc: 58.76% | LR: 0.000210
Epoch: 107 | MCC: 0.042102 | Train loss: 0.9716 | Train acc: 51.49% | Val loss: 0.8360 | Val acc: 58.68% | LR: 0.000201
Epoch: 108 | MCC: 0.033830 | Train loss: 0.9676 | Train acc: 51.69% | Val loss: 0.8316 | Val acc: 58.78% | LR: 0.000192
Epoch: 109 | MCC: 0.046484 | Train loss: 0.9689 | Train acc: 51.59% | Val loss: 0.8368 | Val acc: 58.72% | LR: 0.000184
Epoch: 110 | MCC: 0.046562 | Train loss: 0.9686 | Train acc: 51.65% | Val loss: 0.8349 | Val acc: 58.72% | LR: 0.000175
Epoch: 111 | MCC: 0.043661 | Train loss: 0.9693 | Train acc: 51.57% | Val loss: 0.8328 | Val acc: 58.84% | LR: 0.000167
Epoch: 112 | MCC: 0.045108 | Train loss: 0.9683 | Train acc: 51.62% | Val loss: 0.8338 | Val acc: 58.76% | LR: 0.000159
Epoch: 113 | MCC: 0.041566 | Train loss: 0.9695 | Train acc: 51.56% | Val loss: 0.8329 | Val acc: 58.79% | LR: 0.000151
Epoch: 114 | MCC: 0.044450 | Train loss: 0.9680 | Train acc: 51.63% | Val loss: 0.8308 | Val acc: 58.94% | LR: 0.000143
Epoch: 115 | MCC: 0.047700 | Train loss: 0.9685 | Train acc: 51.59% | Val loss: 0.8342 | Val acc: 58.83% | LR: 0.000135
Epoch: 116 | MCC: 0.038600 | Train loss: 0.9666 | Train acc: 51.73% | Val loss: 0.8345 | Val acc: 58.56% | LR: 0.000128
Epoch: 117 | MCC: 0.040460 | Train loss: 0.9690 | Train acc: 51.56% | Val loss: 0.8342 | Val acc: 58.60% | LR: 0.000120
Epoch: 118 | MCC: 0.043898 | Train loss: 0.9694 | Train acc: 51.62% | Val loss: 0.8311 | Val acc: 58.96% | LR: 0.000113
Epoch: 119 | MCC: 0.040923 | Train loss: 0.9691 | Train acc: 51.60% | Val loss: 0.8306 | Val acc: 58.84% | LR: 0.000106
Epoch: 120 | MCC: 0.030522 | Train loss: 0.9679 | Train acc: 51.68% | Val loss: 0.8338 | Val acc: 58.79% | LR: 0.000100
Epoch: 121 | MCC: 0.035522 | Train loss: 0.9694 | Train acc: 51.65% | Val loss: 0.8321 | Val acc: 58.63% | LR: 0.000093
Epoch: 122 | MCC: 0.049517 | Train loss: 0.9685 | Train acc: 51.63% | Val loss: 0.8317 | Val acc: 58.97% | LR: 0.000087
Epoch: 123 | MCC: 0.049269 | Train loss: 0.9669 | Train acc: 51.72% | Val loss: 0.8306 | Val acc: 59.00% | LR: 0.000081
Epoch: 124 | MCC: 0.046890 | Train loss: 0.9685 | Train acc: 51.67% | Val loss: 0.8297 | Val acc: 59.03% | LR: 0.000075
Epoch: 125 | MCC: 0.047630 | Train loss: 0.9677 | Train acc: 51.69% | Val loss: 0.8288 | Val acc: 59.11% | LR: 0.000069
Epoch: 126 | MCC: 0.052350 | Train loss: 0.9680 | Train acc: 51.65% | Val loss: 0.8299 | Val acc: 59.09% | LR: 0.000064
Epoch: 127 | MCC: 0.047259 | Train loss: 0.9668 | Train acc: 51.74% | Val loss: 0.8304 | Val acc: 59.12% | LR: 0.000059
Epoch: 128 | MCC: 0.050192 | Train loss: 0.9667 | Train acc: 51.67% | Val loss: 0.8312 | Val acc: 59.00% | LR: 0.000054
Epoch: 129 | MCC: 0.051900 | Train loss: 0.9660 | Train acc: 51.77% | Val loss: 0.8306 | Val acc: 59.07% | LR: 0.000049
Epoch: 130 | MCC: 0.041312 | Train loss: 0.9670 | Train acc: 51.78% | Val loss: 0.8316 | Val acc: 58.99% | LR: 0.000044
Epoch: 131 | MCC: 0.048857 | Train loss: 0.9688 | Train acc: 51.60% | Val loss: 0.8309 | Val acc: 59.07% | LR: 0.000040

[I 2025-10-05 09:38:20,750] Trial 29 finished with value: 0.044758185744285583 and parameters: {'lr': 0.0011053696396665612, 'hidden_size': 66, 'dropout': 0.13448399256854698, 'weight_decay': 0.02484889178703034}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.037190 | Train loss: 1.0058 | Train acc: 49.83% | Val loss: 0.9970 | Val acc: 51.17% | LR: 0.000362
Epoch: 001 | MCC: 0.031238 | Train loss: 1.0098 | Train acc: 49.87% | Val loss: 0.9898 | Val acc: 53.39% | LR: 0.000361
Epoch: 002 | MCC: 0.042094 | Train loss: 1.0058 | Train acc: 49.86% | Val loss: 0.9828 | Val acc: 54.49% | LR: 0.000361
Epoch: 003 | MCC: 0.032583 | Train loss: 0.9970 | Train acc: 49.86% | Val loss: 0.9697 | Val acc: 54.94% | LR: 0.000361
Epoch: 004 | MCC: 0.037221 | Train loss: 0.9935 | Train acc: 50.46% | Val loss: 0.9669 | Val acc: 55.15% | LR: 0.000361
Epoch: 005 | MCC: 0.022430 | Train loss: 0.9909 | Train acc: 51.12% | Val loss: 0.9468 | Val acc: 54.98% | LR: 0.000360
Epoch: 006 | MCC: 0.024956 | Train loss: 0.9879 | Train acc: 51.06% | Val loss: 0.9397 | Val acc: 55.33% | LR: 0.000360
Epoch: 007 | MCC: 0.016285 | Train loss: 0.9865 | Train acc: 50.87% | Val loss: 0.9342 | Val acc: 54.79% | LR: 0.000359
Epoch: 008 | MCC: 0.012197 | Train loss: 0.9830 | Train acc: 50.90% | Val loss: 0.9252 | Val acc: 54.71% | LR: 0.000358
Epoch: 009 | MCC: 0.010425 | Train loss: 0.9845 | Train acc: 50.85% | Val loss: 0.9188 | Val acc: 54.83% | LR: 0.000358
Epoch: 010 | MCC: 0.008748 | Train loss: 0.9791 | Train acc: 50.96% | Val loss: 0.9156 | Val acc: 55.04% | LR: 0.000357
Epoch: 011 | MCC: 0.012747 | Train loss: 0.9800 | Train acc: 50.95% | Val loss: 0.9105 | Val acc: 55.47% | LR: 0.000356
Epoch: 012 | MCC: 0.013790 | Train loss: 0.9808 | Train acc: 50.90% | Val loss: 0.9049 | Val acc: 55.77% | LR: 0.000355
Epoch: 013 | MCC: 0.016255 | Train loss: 0.9791 | Train acc: 50.90% | Val loss: 0.9010 | Val acc: 56.04% | LR: 0.000354
Epoch: 014 | MCC: 0.015817 | Train loss: 0.9783 | Train acc: 50.96% | Val loss: 0.8961 | Val acc: 56.35% | LR: 0.000353
Epoch: 015 | MCC: 0.028017 | Train loss: 0.9780 | Train acc: 50.92% | Val loss: 0.8926 | Val acc: 57.05% | LR: 0.000352
Epoch: 016 | MCC: 0.009976 | Train loss: 0.9764 | Train acc: 51.11% | Val loss: 0.8882 | Val acc: 56.84% | LR: 0.000350
Epoch: 017 | MCC: 0.015079 | Train loss: 0.9778 | Train acc: 51.00% | Val loss: 0.8824 | Val acc: 57.03% | LR: 0.000349
Epoch: 018 | MCC: 0.011023 | Train loss: 0.9766 | Train acc: 51.06% | Val loss: 0.8792 | Val acc: 56.96% | LR: 0.000348
Epoch: 019 | MCC: 0.005043 | Train loss: 0.9759 | Train acc: 51.11% | Val loss: 0.8751 | Val acc: 56.68% | LR: 0.000346
Epoch: 020 | MCC: -0.003226 | Train loss: 0.9748 | Train acc: 51.20% | Val loss: 0.8754 | Val acc: 56.47% | LR: 0.000344
Epoch: 021 | MCC: -0.010097 | Train loss: 0.9748 | Train acc: 50.98% | Val loss: 0.8767 | Val acc: 55.86% | LR: 0.000343
Epoch: 022 | MCC: 0.003758 | Train loss: 0.9738 | Train acc: 51.20% | Val loss: 0.8827 | Val acc: 56.08% | LR: 0.000341
Epoch: 023 | MCC: 0.002163 | Train loss: 0.9735 | Train acc: 51.66% | Val loss: 0.8861 | Val acc: 55.83% | LR: 0.000339
Epoch: 024 | MCC: -0.006822 | Train loss: 0.9708 | Train acc: 51.97% | Val loss: 0.8766 | Val acc: 56.40% | LR: 0.000337
Epoch: 025 | MCC: 0.003547 | Train loss: 0.9719 | Train acc: 51.97% | Val loss: 0.8831 | Val acc: 55.88% | LR: 0.000336
Epoch: 026 | MCC: 0.010588 | Train loss: 0.9703 | Train acc: 51.98% | Val loss: 0.8742 | Val acc: 56.83% | LR: 0.000334
Epoch: 027 | MCC: 0.002049 | Train loss: 0.9688 | Train acc: 52.02% | Val loss: 0.8791 | Val acc: 55.93% | LR: 0.000332
Epoch: 028 | MCC: -0.002581 | Train loss: 0.9708 | Train acc: 51.99% | Val loss: 0.8585 | Val acc: 57.30% | LR: 0.000329
Epoch: 029 | MCC: 0.009178 | Train loss: 0.9726 | Train acc: 51.81% | Val loss: 0.8699 | Val acc: 56.83% | LR: 0.000327
Epoch: 030 | MCC: 0.000206 | Train loss: 0.9691 | Train acc: 52.09% | Val loss: 0.8814 | Val acc: 56.05% | LR: 0.000325
Epoch: 031 | MCC: 0.000885 | Train loss: 0.9687 | Train acc: 51.99% | Val loss: 0.8965 | Val acc: 55.83% | LR: 0.000323
Epoch: 032 | MCC: 0.009118 | Train loss: 0.9685 | Train acc: 51.97% | Val loss: 0.8687 | Val acc: 56.96% | LR: 0.000320
Epoch: 033 | MCC: -0.000716 | Train loss: 0.9671 | Train acc: 52.00% | Val loss: 0.8816 | Val acc: 55.78% | LR: 0.000318
Epoch: 034 | MCC: 0.004905 | Train loss: 0.9678 | Train acc: 52.01% | Val loss: 0.8749 | Val acc: 56.49% | LR: 0.000315
Epoch: 035 | MCC: 0.001137 | Train loss: 0.9675 | Train acc: 52.01% | Val loss: 0.8756 | Val acc: 56.17% | LR: 0.000313
Epoch: 036 | MCC: -0.000393 | Train loss: 0.9667 | Train acc: 51.97% | Val loss: 0.8803 | Val acc: 56.08% | LR: 0.000310
Epoch: 037 | MCC: -0.007716 | Train loss: 0.9662 | Train acc: 52.06% | Val loss: 0.8727 | Val acc: 56.42% | LR: 0.000307
Epoch: 038 | MCC: 0.005763 | Train loss: 0.9672 | Train acc: 51.93% | Val loss: 0.8784 | Val acc: 56.34% | LR: 0.000305
Epoch: 039 | MCC: 0.000841 | Train loss: 0.9781 | Train acc: 52.02% | Val loss: 0.8804 | Val acc: 56.20% | LR: 0.000302
Epoch: 040 | MCC: 0.009105 | Train loss: 0.9791 | Train acc: 51.98% | Val loss: 0.8748 | Val acc: 56.71% | LR: 0.000299
Epoch: 041 | MCC: 0.003208 | Train loss: 1.0145 | Train acc: 51.74% | Val loss: 0.9369 | Val acc: 56.23% | LR: 0.000296
Epoch: 042 | MCC: 0.038991 | Train loss: 0.9777 | Train acc: 51.97% | Val loss: 0.8664 | Val acc: 60.61% | LR: 0.000293
Epoch: 043 | MCC: 0.043899 | Train loss: 0.9709 | Train acc: 51.99% | Val loss: 0.8561 | Val acc: 58.79% | LR: 0.000290
Epoch: 044 | MCC: -0.000691 | Train loss: 0.9680 | Train acc: 52.07% | Val loss: 0.8860 | Val acc: 57.10% | LR: 0.000287
Epoch: 045 | MCC: 0.002615 | Train loss: 0.9665 | Train acc: 52.04% | Val loss: 0.8886 | Val acc: 56.42% | LR: 0.000284
Epoch: 046 | MCC: 0.006781 | Train loss: 0.9678 | Train acc: 51.99% | Val loss: 0.8835 | Val acc: 56.44% | LR: 0.000281
Epoch: 047 | MCC: 0.006035 | Train loss: 0.9652 | Train acc: 52.10% | Val loss: 0.8791 | Val acc: 56.59% | LR: 0.000278
Epoch: 048 | MCC: 0.006951 | Train loss: 0.9676 | Train acc: 51.90% | Val loss: 0.8811 | Val acc: 56.64% | LR: 0.000275
Epoch: 049 | MCC: 0.006627 | Train loss: 0.9635 | Train acc: 52.12% | Val loss: 0.8804 | Val acc: 56.44% | LR: 0.000271
Epoch: 050 | MCC: -0.010001 | Train loss: 0.9653 | Train acc: 51.97% | Val loss: 0.8711 | Val acc: 56.54% | LR: 0.000268
Epoch: 051 | MCC: -0.009456 | Train loss: 0.9654 | Train acc: 51.96% | Val loss: 0.8760 | Val acc: 56.32% | LR: 0.000265
Epoch: 052 | MCC: -0.007796 | Train loss: 0.9650 | Train acc: 51.97% | Val loss: 0.8799 | Val acc: 56.32% | LR: 0.000261
Epoch: 053 | MCC: 0.003504 | Train loss: 0.9643 | Train acc: 52.05% | Val loss: 0.8811 | Val acc: 56.34% | LR: 0.000258
Epoch: 054 | MCC: 0.004942 | Train loss: 1.0065 | Train acc: 51.98% | Val loss: 0.8806 | Val acc: 56.39% | LR: 0.000255
Epoch: 055 | MCC: 0.004167 | Train loss: 0.9683 | Train acc: 51.94% | Val loss: 0.8856 | Val acc: 56.10% | LR: 0.000251
Epoch: 056 | MCC: -0.005781 | Train loss: 0.9666 | Train acc: 51.93% | Val loss: 0.8758 | Val acc: 56.54% | LR: 0.000248
Epoch: 057 | MCC: 0.006256 | Train loss: 0.9656 | Train acc: 52.00% | Val loss: 0.8837 | Val acc: 56.42% | LR: 0.000244
Epoch: 058 | MCC: -0.001261 | Train loss: 0.9708 | Train acc: 51.91% | Val loss: 0.8798 | Val acc: 56.20% | LR: 0.000241
Epoch: 059 | MCC: 0.007195 | Train loss: 0.9648 | Train acc: 51.95% | Val loss: 0.8820 | Val acc: 56.59% | LR: 0.000237
Epoch: 060 | MCC: 0.004929 | Train loss: 0.9660 | Train acc: 51.93% | Val loss: 0.8799 | Val acc: 56.52% | LR: 0.000233
Epoch: 061 | MCC: -0.008282 | Train loss: 0.9638 | Train acc: 52.08% | Val loss: 0.8759 | Val acc: 56.52% | LR: 0.000230
Epoch: 062 | MCC: 0.001759 | Train loss: 0.9642 | Train acc: 52.01% | Val loss: 0.8822 | Val acc: 56.32% | LR: 0.000226
Epoch: 063 | MCC: 0.002414 | Train loss: 0.9622 | Train acc: 52.07% | Val loss: 0.8802 | Val acc: 56.56% | LR: 0.000222
Epoch: 064 | MCC: -0.000771 | Train loss: 0.9603 | Train acc: 52.21% | Val loss: 0.8829 | Val acc: 56.17% | LR: 0.000219
Epoch: 065 | MCC: 0.004976 | Train loss: 0.9640 | Train acc: 52.05% | Val loss: 0.8841 | Val acc: 56.54% | LR: 0.000215
Epoch: 066 | MCC: 0.008600 | Train loss: 0.9661 | Train acc: 52.02% | Val loss: 0.8875 | Val acc: 56.49% | LR: 0.000211
Epoch: 067 | MCC: 0.003422 | Train loss: 0.9653 | Train acc: 51.98% | Val loss: 0.8828 | Val acc: 56.39% | LR: 0.000208
Epoch: 068 | MCC: -0.013895 | Train loss: 0.9641 | Train acc: 52.04% | Val loss: 0.8840 | Val acc: 56.03% | LR: 0.000204
Epoch: 069 | MCC: 0.007034 | Train loss: 0.9657 | Train acc: 51.92% | Val loss: 0.8813 | Val acc: 56.64% | LR: 0.000200
Epoch: 070 | MCC: 0.005865 | Train loss: 0.9640 | Train acc: 52.05% | Val loss: 0.8861 | Val acc: 56.39% | LR: 0.000196
Epoch: 071 | MCC: -0.010181 | Train loss: 0.9642 | Train acc: 52.03% | Val loss: 0.8793 | Val acc: 56.44% | LR: 0.000193
Epoch: 072 | MCC: -0.011168 | Train loss: 0.9638 | Train acc: 52.07% | Val loss: 0.8832 | Val acc: 56.27% | LR: 0.000189
Epoch: 073 | MCC: -0.013565 | Train loss: 0.9636 | Train acc: 52.07% | Val loss: 0.8794 | Val acc: 56.30% | LR: 0.000185
Epoch: 074 | MCC: 0.003773 | Train loss: 0.9640 | Train acc: 52.04% | Val loss: 0.8876 | Val acc: 56.30% | LR: 0.000181
Epoch: 075 | MCC: 0.005111 | Train loss: 0.9631 | Train acc: 52.04% | Val loss: 0.8838 | Val acc: 56.49% | LR: 0.000178
Epoch: 076 | MCC: -0.000980 | Train loss: 0.9628 | Train acc: 52.07% | Val loss: 0.8863 | Val acc: 56.22% | LR: 0.000174
Epoch: 077 | MCC: -0.008626 | Train loss: 0.9639 | Train acc: 52.14% | Val loss: 0.8833 | Val acc: 56.34% | LR: 0.000170
Epoch: 078 | MCC: -0.008373 | Train loss: 0.9652 | Train acc: 52.03% | Val loss: 0.8837 | Val acc: 56.32% | LR: 0.000166
Epoch: 079 | MCC: -0.010463 | Train loss: 0.9612 | Train acc: 52.23% | Val loss: 0.8851 | Val acc: 56.20% | LR: 0.000162
Epoch: 080 | MCC: -0.013212 | Train loss: 0.9633 | Train acc: 52.05% | Val loss: 0.8846 | Val acc: 56.13% | LR: 0.000159
Epoch: 081 | MCC: -0.014193 | Train loss: 0.9634 | Train acc: 52.07% | Val loss: 0.8850 | Val acc: 56.05% | LR: 0.000155
Epoch: 082 | MCC: -0.008346 | Train loss: 0.9624 | Train acc: 52.17% | Val loss: 0.8833 | Val acc: 56.30% | LR: 0.000151
Epoch: 083 | MCC: -0.013203 | Train loss: 0.9622 | Train acc: 52.13% | Val loss: 0.8825 | Val acc: 56.25% | LR: 0.000148
Epoch: 084 | MCC: -0.012418 | Train loss: 0.9643 | Train acc: 52.02% | Val loss: 0.8853 | Val acc: 56.10% | LR: 0.000144
Epoch: 085 | MCC: -0.014828 | Train loss: 0.9623 | Train acc: 52.10% | Val loss: 0.8856 | Val acc: 56.03% | LR: 0.000140
Epoch: 086 | MCC: -0.007887 | Train loss: 0.9624 | Train acc: 52.16% | Val loss: 0.8828 | Val acc: 56.49% | LR: 0.000136
Epoch: 087 | MCC: -0.011900 | Train loss: 0.9638 | Train acc: 52.01% | Val loss: 0.8847 | Val acc: 56.15% | LR: 0.000133
Epoch: 088 | MCC: -0.011653 | Train loss: 0.9605 | Train acc: 52.23% | Val loss: 0.8842 | Val acc: 56.17% | LR: 0.000129
Epoch: 089 | MCC: -0.003765 | Train loss: 0.9618 | Train acc: 52.17% | Val loss: 0.8846 | Val acc: 56.42% | LR: 0.000126
Epoch: 090 | MCC: -0.008783 | Train loss: 0.9601 | Train acc: 52.30% | Val loss: 0.8805 | Val acc: 56.44% | LR: 0.000122
Epoch: 091 | MCC: -0.003591 | Train loss: 0.9627 | Train acc: 52.15% | Val loss: 0.8843 | Val acc: 56.42% | LR: 0.000118
Epoch: 092 | MCC: -0.008229 | Train loss: 0.9625 | Train acc: 52.12% | Val loss: 0.8822 | Val acc: 56.34% | LR: 0.000115
Epoch: 093 | MCC: -0.007074 | Train loss: 0.9611 | Train acc: 52.18% | Val loss: 0.8830 | Val acc: 56.39% | LR: 0.000111
Epoch: 094 | MCC: -0.001126 | Train loss: 0.9626 | Train acc: 52.11% | Val loss: 0.8844 | Val acc: 56.52% | LR: 0.000108
Epoch: 095 | MCC: -0.002992 | Train loss: 0.9629 | Train acc: 52.11% | Val loss: 0.8831 | Val acc: 56.56% | LR: 0.000105
Epoch: 096 | MCC: -0.008859 | Train loss: 0.9631 | Train acc: 52.11% | Val loss: 0.8822 | Val acc: 56.30% | LR: 0.000101
Epoch: 097 | MCC: -0.006095 | Train loss: 0.9632 | Train acc: 52.11% | Val loss: 0.8836 | Val acc: 56.37% | LR: 0.000098
Epoch: 098 | MCC: -0.013321 | Train loss: 0.9596 | Train acc: 52.25% | Val loss: 0.8812 | Val acc: 56.22% | LR: 0.000094
Epoch: 099 | MCC: -0.010676 | Train loss: 0.9620 | Train acc: 52.15% | Val loss: 0.8825 | Val acc: 56.25% | LR: 0.000091
Epoch: 100 | MCC: -0.008440 | Train loss: 0.9611 | Train acc: 52.19% | Val loss: 0.8835 | Val acc: 56.25% | LR: 0.000088
Epoch: 101 | MCC: -0.009055 | Train loss: 0.9611 | Train acc: 52.17% | Val loss: 0.8797 | Val acc: 56.42% | LR: 0.000085
Epoch: 102 | MCC: -0.004239 | Train loss: 0.9609 | Train acc: 52.17% | Val loss: 0.8848 | Val acc: 56.39% | LR: 0.000082
Epoch: 103 | MCC: -0.006911 | Train loss: 0.9614 | Train acc: 52.16% | Val loss: 0.8814 | Val acc: 56.37% | LR: 0.000078
Epoch: 104 | MCC: -0.008782 | Train loss: 0.9618 | Train acc: 52.14% | Val loss: 0.8824 | Val acc: 56.30% | LR: 0.000075
Epoch: 105 | MCC: -0.007316 | Train loss: 0.9625 | Train acc: 52.12% | Val loss: 0.8804 | Val acc: 56.52% | LR: 0.000072
Epoch: 106 | MCC: -0.005805 | Train loss: 0.9622 | Train acc: 52.12% | Val loss: 0.8834 | Val acc: 56.37% | LR: 0.000069
Epoch: 107 | MCC: -0.006891 | Train loss: 0.9615 | Train acc: 52.14% | Val loss: 0.8815 | Val acc: 56.42% | LR: 0.000066
Epoch: 108 | MCC: -0.006707 | Train loss: 0.9608 | Train acc: 52.21% | Val loss: 0.8820 | Val acc: 56.39% | LR: 0.000063
Epoch: 109 | MCC: -0.006700 | Train loss: 0.9601 | Train acc: 52.24% | Val loss: 0.8827 | Val acc: 56.37% | LR: 0.000061
Epoch: 110 | MCC: -0.008025 | Train loss: 0.9630 | Train acc: 52.09% | Val loss: 0.8843 | Val acc: 56.22% | LR: 0.000058
Epoch: 111 | MCC: -0.006040 | Train loss: 0.9604 | Train acc: 52.23% | Val loss: 0.8816 | Val acc: 56.42% | LR: 0.000055
Epoch: 112 | MCC: -0.008496 | Train loss: 0.9611 | Train acc: 52.18% | Val loss: 0.8822 | Val acc: 56.30% | LR: 0.000052
Epoch: 113 | MCC: -0.007105 | Train loss: 0.9597 | Train acc: 52.24% | Val loss: 0.8807 | Val acc: 56.47% | LR: 0.000050
Epoch: 114 | MCC: -0.006344 | Train loss: 0.9608 | Train acc: 52.17% | Val loss: 0.8815 | Val acc: 56.47% | LR: 0.000047
Epoch: 115 | MCC: -0.006891 | Train loss: 0.9621 | Train acc: 52.14% | Val loss: 0.8816 | Val acc: 56.42% | LR: 0.000045
Epoch: 116 | MCC: -0.006344 | Train loss: 0.9614 | Train acc: 52.17% | Val loss: 0.8814 | Val acc: 56.47% | LR: 0.000042
Epoch: 117 | MCC: -0.007115 | Train loss: 0.9610 | Train acc: 52.18% | Val loss: 0.8817 | Val acc: 56.39% | LR: 0.000040

[I 2025-10-05 09:39:59,011] Trial 30 finished with value: -0.007509080693125725 and parameters: {'lr': 0.0003616302627220541, 'hidden_size': 62, 'dropout': 0.007254219081696531, 'weight_decay': 0.022704056119050867}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.017036 | Train loss: 1.0001 | Train acc: 50.06% | Val loss: 0.9830 | Val acc: 53.19% | LR: 0.000582
Epoch: 001 | MCC: 0.014647 | Train loss: 1.0107 | Train acc: 50.56% | Val loss: 0.9659 | Val acc: 54.19% | LR: 0.000582
Epoch: 002 | MCC: 0.023585 | Train loss: 0.9906 | Train acc: 50.88% | Val loss: 0.9460 | Val acc: 54.58% | LR: 0.000581
Epoch: 003 | MCC: 0.027487 | Train loss: 0.9884 | Train acc: 50.87% | Val loss: 0.9396 | Val acc: 55.13% | LR: 0.000581
Epoch: 004 | MCC: 0.019399 | Train loss: 0.9836 | Train acc: 50.93% | Val loss: 0.9262 | Val acc: 55.14% | LR: 0.000580
Epoch: 005 | MCC: 0.031544 | Train loss: 0.9856 | Train acc: 50.84% | Val loss: 0.9517 | Val acc: 55.80% | LR: 0.000580
Epoch: 006 | MCC: 0.025774 | Train loss: 1.0010 | Train acc: 51.01% | Val loss: 0.9374 | Val acc: 55.63% | LR: 0.000579
Epoch: 007 | MCC: 0.014400 | Train loss: 0.9896 | Train acc: 51.09% | Val loss: 0.9124 | Val acc: 54.84% | LR: 0.000578
Epoch: 008 | MCC: 0.008034 | Train loss: 0.9902 | Train acc: 50.84% | Val loss: 0.9136 | Val acc: 54.78% | LR: 0.000577
Epoch: 009 | MCC: 0.015793 | Train loss: 0.9832 | Train acc: 50.94% | Val loss: 0.9005 | Val acc: 55.60% | LR: 0.000575
Epoch: 010 | MCC: 0.012097 | Train loss: 0.9836 | Train acc: 50.80% | Val loss: 0.8965 | Val acc: 55.92% | LR: 0.000574
Epoch: 011 | MCC: -0.003002 | Train loss: 0.9847 | Train acc: 50.82% | Val loss: 0.9072 | Val acc: 55.67% | LR: 0.000573
Epoch: 012 | MCC: 0.011118 | Train loss: 0.9836 | Train acc: 50.85% | Val loss: 0.9076 | Val acc: 55.74% | LR: 0.000571
Epoch: 013 | MCC: -0.000050 | Train loss: 0.9832 | Train acc: 50.90% | Val loss: 0.9218 | Val acc: 54.86% | LR: 0.000569
Epoch: 014 | MCC: -0.003750 | Train loss: 0.9874 | Train acc: 50.75% | Val loss: 0.9286 | Val acc: 54.18% | LR: 0.000568
Epoch: 015 | MCC: -0.005363 | Train loss: 0.9847 | Train acc: 50.73% | Val loss: 1.0014 | Val acc: 50.33% | LR: 0.000566
Epoch: 016 | MCC: -0.005266 | Train loss: 0.9865 | Train acc: 50.67% | Val loss: 1.0051 | Val acc: 49.51% | LR: 0.000564
Epoch: 017 | MCC: 0.008256 | Train loss: 0.9934 | Train acc: 50.81% | Val loss: 1.0135 | Val acc: 49.90% | LR: 0.000561
Epoch: 018 | MCC: -0.018883 | Train loss: 0.9863 | Train acc: 50.69% | Val loss: 0.9884 | Val acc: 49.45% | LR: 0.000559
Epoch: 019 | MCC: -0.007533 | Train loss: 0.9886 | Train acc: 50.61% | Val loss: 0.9806 | Val acc: 49.35% | LR: 0.000557
Epoch: 020 | MCC: 0.011786 | Train loss: 0.9875 | Train acc: 50.51% | Val loss: 0.9920 | Val acc: 49.35% | LR: 0.000554
Epoch: 021 | MCC: 0.011751 | Train loss: 0.9895 | Train acc: 50.29% | Val loss: 0.9780 | Val acc: 51.29% | LR: 0.000552
Epoch: 022 | MCC: 0.019575 | Train loss: 0.9899 | Train acc: 50.38% | Val loss: 0.9645 | Val acc: 55.57% | LR: 0.000549
Epoch: 023 | MCC: 0.028721 | Train loss: 0.9869 | Train acc: 50.69% | Val loss: 0.9633 | Val acc: 56.13% | LR: 0.000546
Epoch: 024 | MCC: 0.035357 | Train loss: 1.0055 | Train acc: 50.64% | Val loss: 0.9480 | Val acc: 54.81% | LR: 0.000543
Epoch: 025 | MCC: 0.052024 | Train loss: 0.9848 | Train acc: 50.92% | Val loss: 0.9390 | Val acc: 55.15% | LR: 0.000540
Epoch: 026 | MCC: 0.058785 | Train loss: 0.9842 | Train acc: 50.84% | Val loss: 0.9349 | Val acc: 55.65% | LR: 0.000537
Epoch: 027 | MCC: 0.039194 | Train loss: 0.9869 | Train acc: 50.81% | Val loss: 0.9753 | Val acc: 53.91% | LR: 0.000533
Epoch: 028 | MCC: 0.050922 | Train loss: 0.9898 | Train acc: 51.00% | Val loss: 0.9414 | Val acc: 54.54% | LR: 0.000530
Epoch: 029 | MCC: 0.048906 | Train loss: 1.0023 | Train acc: 50.92% | Val loss: 0.9646 | Val acc: 53.86% | LR: 0.000526
Epoch: 030 | MCC: 0.054257 | Train loss: 0.9832 | Train acc: 51.06% | Val loss: 0.9524 | Val acc: 54.47% | LR: 0.000523
Epoch: 031 | MCC: 0.034736 | Train loss: 0.9826 | Train acc: 50.84% | Val loss: 0.9731 | Val acc: 53.54% | LR: 0.000519
Epoch: 032 | MCC: 0.044378 | Train loss: 0.9811 | Train acc: 51.01% | Val loss: 0.9574 | Val acc: 53.96% | LR: 0.000515
Epoch: 033 | MCC: 0.039692 | Train loss: 0.9826 | Train acc: 50.98% | Val loss: 0.9484 | Val acc: 53.96% | LR: 0.000511
Epoch: 034 | MCC: 0.034951 | Train loss: 0.9818 | Train acc: 50.73% | Val loss: 0.9614 | Val acc: 52.61% | LR: 0.000507
Epoch: 035 | MCC: 0.043753 | Train loss: 0.9810 | Train acc: 50.81% | Val loss: 0.9530 | Val acc: 53.51% | LR: 0.000503
Epoch: 036 | MCC: 0.043835 | Train loss: 0.9803 | Train acc: 51.00% | Val loss: 0.9477 | Val acc: 53.95% | LR: 0.000499
Epoch: 037 | MCC: 0.039032 | Train loss: 0.9821 | Train acc: 50.86% | Val loss: 0.9541 | Val acc: 54.12% | LR: 0.000495
Epoch: 038 | MCC: 0.045782 | Train loss: 0.9808 | Train acc: 51.05% | Val loss: 0.9449 | Val acc: 54.28% | LR: 0.000490
Epoch: 039 | MCC: 0.047647 | Train loss: 0.9812 | Train acc: 50.87% | Val loss: 0.9493 | Val acc: 54.27% | LR: 0.000486
Epoch: 040 | MCC: 0.032793 | Train loss: 0.9815 | Train acc: 50.88% | Val loss: 0.9721 | Val acc: 53.29% | LR: 0.000481
Epoch: 041 | MCC: 0.046789 | Train loss: 0.9826 | Train acc: 51.03% | Val loss: 0.9596 | Val acc: 53.37% | LR: 0.000477
Epoch: 042 | MCC: 0.050172 | Train loss: 0.9817 | Train acc: 50.83% | Val loss: 0.9449 | Val acc: 53.83% | LR: 0.000472
Epoch: 043 | MCC: 0.045265 | Train loss: 0.9814 | Train acc: 50.84% | Val loss: 0.9450 | Val acc: 53.75% | LR: 0.000467
Epoch: 044 | MCC: 0.046487 | Train loss: 0.9782 | Train acc: 51.19% | Val loss: 0.9364 | Val acc: 54.09% | LR: 0.000462
Epoch: 045 | MCC: 0.048474 | Train loss: 0.9797 | Train acc: 51.03% | Val loss: 0.9560 | Val acc: 53.33% | LR: 0.000457
Epoch: 046 | MCC: 0.054999 | Train loss: 0.9801 | Train acc: 51.19% | Val loss: 0.9358 | Val acc: 54.40% | LR: 0.000452
Epoch: 047 | MCC: 0.043523 | Train loss: 0.9810 | Train acc: 51.47% | Val loss: 0.9502 | Val acc: 52.51% | LR: 0.000447
Epoch: 048 | MCC: 0.041778 | Train loss: 0.9808 | Train acc: 51.53% | Val loss: 0.9506 | Val acc: 54.41% | LR: 0.000442
Epoch: 049 | MCC: 0.041536 | Train loss: 0.9801 | Train acc: 51.44% | Val loss: 0.9300 | Val acc: 55.15% | LR: 0.000437
Epoch: 050 | MCC: 0.047653 | Train loss: 0.9789 | Train acc: 51.70% | Val loss: 0.9352 | Val acc: 55.73% | LR: 0.000431
Epoch: 051 | MCC: 0.033355 | Train loss: 0.9791 | Train acc: 51.66% | Val loss: 0.9303 | Val acc: 54.31% | LR: 0.000426
Epoch: 052 | MCC: 0.042647 | Train loss: 0.9773 | Train acc: 51.70% | Val loss: 0.9240 | Val acc: 55.31% | LR: 0.000421
Epoch: 053 | MCC: 0.047865 | Train loss: 0.9794 | Train acc: 51.59% | Val loss: 0.9225 | Val acc: 55.60% | LR: 0.000415
Epoch: 054 | MCC: 0.042365 | Train loss: 0.9823 | Train acc: 51.70% | Val loss: 0.9769 | Val acc: 55.32% | LR: 0.000410
Epoch: 055 | MCC: 0.038969 | Train loss: 0.9821 | Train acc: 51.52% | Val loss: 0.9524 | Val acc: 54.36% | LR: 0.000404
Epoch: 056 | MCC: 0.035596 | Train loss: 0.9801 | Train acc: 51.54% | Val loss: 1.0262 | Val acc: 49.59% | LR: 0.000398
Epoch: 057 | MCC: 0.038406 | Train loss: 0.9823 | Train acc: 51.37% | Val loss: 1.0351 | Val acc: 48.90% | LR: 0.000393
Epoch: 058 | MCC: 0.033455 | Train loss: 0.9820 | Train acc: 51.33% | Val loss: 1.0163 | Val acc: 49.11% | LR: 0.000387
Epoch: 059 | MCC: 0.041432 | Train loss: 0.9804 | Train acc: 51.41% | Val loss: 1.0155 | Val acc: 49.70% | LR: 0.000381
Epoch: 060 | MCC: 0.039441 | Train loss: 0.9804 | Train acc: 51.45% | Val loss: 1.0061 | Val acc: 50.59% | LR: 0.000375
Epoch: 061 | MCC: 0.045758 | Train loss: 0.9800 | Train acc: 51.67% | Val loss: 0.9934 | Val acc: 52.92% | LR: 0.000370
Epoch: 062 | MCC: 0.041723 | Train loss: 0.9785 | Train acc: 51.55% | Val loss: 0.9869 | Val acc: 54.27% | LR: 0.000364
Epoch: 063 | MCC: 0.041271 | Train loss: 0.9801 | Train acc: 51.65% | Val loss: 0.9983 | Val acc: 54.15% | LR: 0.000358
Epoch: 064 | MCC: 0.044382 | Train loss: 0.9792 | Train acc: 51.67% | Val loss: 0.9956 | Val acc: 53.93% | LR: 0.000352
Epoch: 065 | MCC: 0.042851 | Train loss: 0.9791 | Train acc: 51.56% | Val loss: 0.9886 | Val acc: 53.99% | LR: 0.000346
Epoch: 066 | MCC: 0.034781 | Train loss: 0.9780 | Train acc: 51.70% | Val loss: 0.9817 | Val acc: 54.20% | LR: 0.000340
Epoch: 067 | MCC: 0.038341 | Train loss: 0.9775 | Train acc: 51.66% | Val loss: 0.9816 | Val acc: 54.57% | LR: 0.000334
Epoch: 068 | MCC: 0.039205 | Train loss: 0.9789 | Train acc: 51.54% | Val loss: 0.9777 | Val acc: 54.57% | LR: 0.000328
Epoch: 069 | MCC: 0.040709 | Train loss: 0.9788 | Train acc: 51.57% | Val loss: 0.9768 | Val acc: 54.76% | LR: 0.000322
Epoch: 070 | MCC: 0.041332 | Train loss: 0.9779 | Train acc: 51.64% | Val loss: 0.9709 | Val acc: 54.78% | LR: 0.000316
Epoch: 071 | MCC: 0.036972 | Train loss: 0.9779 | Train acc: 51.66% | Val loss: 1.0139 | Val acc: 54.55% | LR: 0.000310
Epoch: 072 | MCC: 0.038911 | Train loss: 0.9761 | Train acc: 51.75% | Val loss: 0.9996 | Val acc: 54.82% | LR: 0.000304
Epoch: 073 | MCC: 0.046681 | Train loss: 0.9769 | Train acc: 51.62% | Val loss: 0.9560 | Val acc: 55.03% | LR: 0.000298
Epoch: 074 | MCC: 0.043288 | Train loss: 0.9750 | Train acc: 51.73% | Val loss: 0.9674 | Val acc: 54.76% | LR: 0.000291
Epoch: 075 | MCC: 0.041942 | Train loss: 0.9744 | Train acc: 51.79% | Val loss: 0.9602 | Val acc: 54.79% | LR: 0.000285
Epoch: 076 | MCC: 0.041848 | Train loss: 0.9752 | Train acc: 51.74% | Val loss: 0.9590 | Val acc: 54.65% | LR: 0.000279
Epoch: 077 | MCC: 0.043861 | Train loss: 0.9759 | Train acc: 51.67% | Val loss: 0.9644 | Val acc: 54.61% | LR: 0.000273
Epoch: 078 | MCC: 0.038729 | Train loss: 0.9752 | Train acc: 51.72% | Val loss: 0.9494 | Val acc: 54.44% | LR: 0.000267
Epoch: 079 | MCC: 0.042753 | Train loss: 0.9752 | Train acc: 51.64% | Val loss: 0.9474 | Val acc: 54.76% | LR: 0.000261
Epoch: 080 | MCC: 0.041047 | Train loss: 0.9751 | Train acc: 51.75% | Val loss: 0.9486 | Val acc: 54.28% | LR: 0.000255
Epoch: 081 | MCC: 0.035474 | Train loss: 0.9745 | Train acc: 51.71% | Val loss: 0.9463 | Val acc: 54.18% | LR: 0.000249
Epoch: 082 | MCC: 0.033908 | Train loss: 0.9757 | Train acc: 51.69% | Val loss: 0.9616 | Val acc: 54.21% | LR: 0.000243
Epoch: 083 | MCC: 0.050009 | Train loss: 0.9738 | Train acc: 51.79% | Val loss: 0.9386 | Val acc: 54.95% | LR: 0.000237
Epoch: 084 | MCC: 0.044423 | Train loss: 0.9742 | Train acc: 51.79% | Val loss: 0.9348 | Val acc: 54.81% | LR: 0.000231

[I 2025-10-05 09:41:17,054] Trial 31 finished with value: 0.048993741045705974 and parameters: {'lr': 0.0005818458066048866, 'hidden_size': 71, 'dropout': 0.13333658539045307, 'weight_decay': 0.005737496429578633}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: -0.003352 | Train loss: 0.9978 | Train acc: 50.76% | Val loss: 1.0129 | Val acc: 45.27% | LR: 0.000507
Epoch: 001 | MCC: 0.012967 | Train loss: 0.9991 | Train acc: 50.65% | Val loss: 1.0603 | Val acc: 45.27% | LR: 0.000506
Epoch: 002 | MCC: 0.034150 | Train loss: 0.9923 | Train acc: 50.75% | Val loss: 1.0104 | Val acc: 45.80% | LR: 0.000506
Epoch: 003 | MCC: 0.034500 | Train loss: 0.9936 | Train acc: 50.68% | Val loss: 1.0103 | Val acc: 46.08% | LR: 0.000506
Epoch: 004 | MCC: 0.046426 | Train loss: 0.9901 | Train acc: 50.75% | Val loss: 1.0080 | Val acc: 47.29% | LR: 0.000505
Epoch: 005 | MCC: 0.049986 | Train loss: 0.9904 | Train acc: 50.65% | Val loss: 1.0089 | Val acc: 47.47% | LR: 0.000505
Epoch: 006 | MCC: 0.015117 | Train loss: 0.9891 | Train acc: 50.65% | Val loss: 1.0090 | Val acc: 47.41% | LR: 0.000504
Epoch: 007 | MCC: 0.031571 | Train loss: 0.9915 | Train acc: 50.59% | Val loss: 1.0069 | Val acc: 47.64% | LR: 0.000503
Epoch: 008 | MCC: 0.032479 | Train loss: 0.9854 | Train acc: 50.74% | Val loss: 1.0118 | Val acc: 47.88% | LR: 0.000502
Epoch: 009 | MCC: 0.051279 | Train loss: 0.9875 | Train acc: 50.61% | Val loss: 1.0053 | Val acc: 49.03% | LR: 0.000501
Epoch: 010 | MCC: 0.044325 | Train loss: 0.9864 | Train acc: 50.75% | Val loss: 1.0040 | Val acc: 49.22% | LR: 0.000500
Epoch: 011 | MCC: 0.043804 | Train loss: 0.9864 | Train acc: 50.77% | Val loss: 1.0037 | Val acc: 50.06% | LR: 0.000499
Epoch: 012 | MCC: 0.056752 | Train loss: 0.9841 | Train acc: 50.86% | Val loss: 0.9946 | Val acc: 53.06% | LR: 0.000497
Epoch: 013 | MCC: 0.052247 | Train loss: 0.9860 | Train acc: 50.86% | Val loss: 0.9997 | Val acc: 49.20% | LR: 0.000496
Epoch: 014 | MCC: 0.056639 | Train loss: 0.9860 | Train acc: 50.61% | Val loss: 1.0008 | Val acc: 49.91% | LR: 0.000494
Epoch: 015 | MCC: 0.038443 | Train loss: 0.9843 | Train acc: 50.82% | Val loss: 0.9946 | Val acc: 52.99% | LR: 0.000493
Epoch: 016 | MCC: 0.038271 | Train loss: 0.9853 | Train acc: 50.77% | Val loss: 0.9829 | Val acc: 53.92% | LR: 0.000491
Epoch: 017 | MCC: 0.041225 | Train loss: 0.9854 | Train acc: 50.93% | Val loss: 0.9765 | Val acc: 54.64% | LR: 0.000489
Epoch: 018 | MCC: 0.040928 | Train loss: 0.9862 | Train acc: 50.84% | Val loss: 0.9839 | Val acc: 53.61% | LR: 0.000487
Epoch: 019 | MCC: 0.047760 | Train loss: 0.9852 | Train acc: 50.69% | Val loss: 0.9971 | Val acc: 48.44% | LR: 0.000485
Epoch: 020 | MCC: 0.043299 | Train loss: 0.9861 | Train acc: 50.54% | Val loss: 0.9954 | Val acc: 48.33% | LR: 0.000483
Epoch: 021 | MCC: 0.046311 | Train loss: 0.9854 | Train acc: 50.57% | Val loss: 1.0007 | Val acc: 48.36% | LR: 0.000480
Epoch: 022 | MCC: 0.063139 | Train loss: 0.9827 | Train acc: 50.70% | Val loss: 0.9890 | Val acc: 49.73% | LR: 0.000478
Epoch: 023 | MCC: 0.047304 | Train loss: 0.9854 | Train acc: 50.68% | Val loss: 0.9815 | Val acc: 51.45% | LR: 0.000475
Epoch: 024 | MCC: 0.046080 | Train loss: 0.9839 | Train acc: 50.81% | Val loss: 0.9718 | Val acc: 53.35% | LR: 0.000473
Epoch: 025 | MCC: 0.056843 | Train loss: 0.9840 | Train acc: 50.84% | Val loss: 0.9621 | Val acc: 54.13% | LR: 0.000470
Epoch: 026 | MCC: 0.045641 | Train loss: 0.9830 | Train acc: 50.95% | Val loss: 0.9447 | Val acc: 55.83% | LR: 0.000467
Epoch: 027 | MCC: 0.047978 | Train loss: 0.9814 | Train acc: 51.03% | Val loss: 0.9288 | Val acc: 56.61% | LR: 0.000464
Epoch: 028 | MCC: 0.040399 | Train loss: 0.9806 | Train acc: 50.99% | Val loss: 0.9186 | Val acc: 57.00% | LR: 0.000461
Epoch: 029 | MCC: 0.042699 | Train loss: 0.9807 | Train acc: 51.06% | Val loss: 0.9111 | Val acc: 57.35% | LR: 0.000458
Epoch: 030 | MCC: 0.038449 | Train loss: 0.9820 | Train acc: 50.86% | Val loss: 0.9043 | Val acc: 57.14% | LR: 0.000455
Epoch: 031 | MCC: 0.048768 | Train loss: 0.9820 | Train acc: 50.93% | Val loss: 0.8964 | Val acc: 57.94% | LR: 0.000452
Epoch: 032 | MCC: 0.043440 | Train loss: 0.9818 | Train acc: 50.97% | Val loss: 0.8859 | Val acc: 57.46% | LR: 0.000449
Epoch: 033 | MCC: 0.053326 | Train loss: 0.9784 | Train acc: 51.12% | Val loss: 0.8764 | Val acc: 58.07% | LR: 0.000445
Epoch: 034 | MCC: 0.056073 | Train loss: 0.9784 | Train acc: 51.17% | Val loss: 0.8749 | Val acc: 57.95% | LR: 0.000442
Epoch: 035 | MCC: 0.057810 | Train loss: 0.9780 | Train acc: 51.20% | Val loss: 0.8541 | Val acc: 58.86% | LR: 0.000438
Epoch: 036 | MCC: 0.022660 | Train loss: 0.9784 | Train acc: 51.18% | Val loss: 0.8765 | Val acc: 56.73% | LR: 0.000434
Epoch: 037 | MCC: 0.030015 | Train loss: 0.9789 | Train acc: 51.25% | Val loss: 0.8789 | Val acc: 57.23% | LR: 0.000431
Epoch: 038 | MCC: 0.032090 | Train loss: 0.9763 | Train acc: 51.16% | Val loss: 0.8545 | Val acc: 58.12% | LR: 0.000427
Epoch: 039 | MCC: 0.027574 | Train loss: 0.9763 | Train acc: 51.22% | Val loss: 0.8503 | Val acc: 58.24% | LR: 0.000423
Epoch: 040 | MCC: 0.020518 | Train loss: 0.9719 | Train acc: 51.48% | Val loss: 0.8357 | Val acc: 59.34% | LR: 0.000419
Epoch: 041 | MCC: 0.032774 | Train loss: 0.9735 | Train acc: 51.31% | Val loss: 0.8501 | Val acc: 58.42% | LR: 0.000415
Epoch: 042 | MCC: 0.013847 | Train loss: 0.9767 | Train acc: 51.39% | Val loss: 0.8311 | Val acc: 58.96% | LR: 0.000411
Epoch: 043 | MCC: 0.016768 | Train loss: 0.9719 | Train acc: 51.52% | Val loss: 0.8848 | Val acc: 57.05% | LR: 0.000407
Epoch: 044 | MCC: 0.015235 | Train loss: 0.9735 | Train acc: 51.35% | Val loss: 0.8500 | Val acc: 58.43% | LR: 0.000402
Epoch: 045 | MCC: 0.033204 | Train loss: 0.9723 | Train acc: 51.43% | Val loss: 0.8608 | Val acc: 56.55% | LR: 0.000398
Epoch: 046 | MCC: 0.031550 | Train loss: 0.9739 | Train acc: 51.27% | Val loss: 0.8150 | Val acc: 60.13% | LR: 0.000394
Epoch: 047 | MCC: 0.034469 | Train loss: 0.9740 | Train acc: 51.28% | Val loss: 0.8499 | Val acc: 57.54% | LR: 0.000389
Epoch: 048 | MCC: 0.031861 | Train loss: 0.9718 | Train acc: 51.42% | Val loss: 0.8515 | Val acc: 58.50% | LR: 0.000385
Epoch: 049 | MCC: 0.020380 | Train loss: 0.9722 | Train acc: 51.40% | Val loss: 0.8529 | Val acc: 57.93% | LR: 0.000380
Epoch: 050 | MCC: 0.042061 | Train loss: 0.9733 | Train acc: 51.31% | Val loss: 0.8299 | Val acc: 58.97% | LR: 0.000376
Epoch: 051 | MCC: 0.031424 | Train loss: 0.9732 | Train acc: 51.32% | Val loss: 0.8337 | Val acc: 58.16% | LR: 0.000371
Epoch: 052 | MCC: 0.031166 | Train loss: 0.9722 | Train acc: 51.36% | Val loss: 0.8251 | Val acc: 58.52% | LR: 0.000366
Epoch: 053 | MCC: 0.036410 | Train loss: 0.9708 | Train acc: 51.46% | Val loss: 0.8333 | Val acc: 58.17% | LR: 0.000361
Epoch: 054 | MCC: 0.038946 | Train loss: 0.9733 | Train acc: 51.31% | Val loss: 0.8386 | Val acc: 57.86% | LR: 0.000357
Epoch: 055 | MCC: 0.036087 | Train loss: 0.9713 | Train acc: 51.46% | Val loss: 0.8302 | Val acc: 57.99% | LR: 0.000352
Epoch: 056 | MCC: 0.037347 | Train loss: 0.9682 | Train acc: 51.61% | Val loss: 0.8401 | Val acc: 57.51% | LR: 0.000347
Epoch: 057 | MCC: 0.026270 | Train loss: 0.9699 | Train acc: 51.47% | Val loss: 0.8384 | Val acc: 58.04% | LR: 0.000342
Epoch: 058 | MCC: 0.044946 | Train loss: 0.9720 | Train acc: 51.38% | Val loss: 0.8643 | Val acc: 56.63% | LR: 0.000337
Epoch: 059 | MCC: 0.045330 | Train loss: 0.9698 | Train acc: 51.52% | Val loss: 0.8736 | Val acc: 56.29% | LR: 0.000332
Epoch: 060 | MCC: 0.036808 | Train loss: 0.9780 | Train acc: 51.03% | Val loss: 0.8643 | Val acc: 56.89% | LR: 0.000327
Epoch: 061 | MCC: 0.054428 | Train loss: 0.9702 | Train acc: 51.48% | Val loss: 0.8268 | Val acc: 58.53% | LR: 0.000322
Epoch: 062 | MCC: 0.046649 | Train loss: 0.9707 | Train acc: 51.36% | Val loss: 0.8395 | Val acc: 58.47% | LR: 0.000317
Epoch: 063 | MCC: 0.025860 | Train loss: 0.9709 | Train acc: 51.39% | Val loss: 0.8744 | Val acc: 56.43% | LR: 0.000312
Epoch: 064 | MCC: 0.005146 | Train loss: 0.9711 | Train acc: 51.43% | Val loss: 0.8974 | Val acc: 54.94% | LR: 0.000306
Epoch: 065 | MCC: 0.029277 | Train loss: 0.9759 | Train acc: 51.10% | Val loss: 0.8504 | Val acc: 57.80% | LR: 0.000301
Epoch: 066 | MCC: 0.036505 | Train loss: 0.9728 | Train acc: 51.27% | Val loss: 0.8319 | Val acc: 58.78% | LR: 0.000296
Epoch: 067 | MCC: 0.026813 | Train loss: 0.9705 | Train acc: 51.45% | Val loss: 0.8271 | Val acc: 58.86% | LR: 0.000291
Epoch: 068 | MCC: 0.028996 | Train loss: 0.9698 | Train acc: 51.52% | Val loss: 0.8302 | Val acc: 58.48% | LR: 0.000285
Epoch: 069 | MCC: 0.040755 | Train loss: 0.9700 | Train acc: 51.45% | Val loss: 0.8309 | Val acc: 58.69% | LR: 0.000280
Epoch: 070 | MCC: 0.039219 | Train loss: 0.9709 | Train acc: 51.32% | Val loss: 0.8517 | Val acc: 57.78% | LR: 0.000275
Epoch: 071 | MCC: 0.035581 | Train loss: 0.9702 | Train acc: 51.44% | Val loss: 0.8362 | Val acc: 58.23% | LR: 0.000270
Epoch: 072 | MCC: 0.042813 | Train loss: 0.9703 | Train acc: 51.31% | Val loss: 0.8445 | Val acc: 58.00% | LR: 0.000264
Epoch: 073 | MCC: 0.025450 | Train loss: 0.9858 | Train acc: 51.35% | Val loss: 0.8689 | Val acc: 56.59% | LR: 0.000259
Epoch: 074 | MCC: 0.026043 | Train loss: 0.9728 | Train acc: 51.27% | Val loss: 0.8707 | Val acc: 56.51% | LR: 0.000254
Epoch: 075 | MCC: 0.044944 | Train loss: 0.9726 | Train acc: 51.23% | Val loss: 0.8536 | Val acc: 57.49% | LR: 0.000249
Epoch: 076 | MCC: 0.060328 | Train loss: 0.9701 | Train acc: 51.44% | Val loss: 0.8072 | Val acc: 59.80% | LR: 0.000243
Epoch: 077 | MCC: 0.044460 | Train loss: 0.9686 | Train acc: 51.46% | Val loss: 0.8377 | Val acc: 58.18% | LR: 0.000238
Epoch: 078 | MCC: 0.066805 | Train loss: 0.9674 | Train acc: 51.57% | Val loss: 0.8168 | Val acc: 59.61% | LR: 0.000233
Epoch: 079 | MCC: 0.046453 | Train loss: 0.9692 | Train acc: 51.51% | Val loss: 0.8325 | Val acc: 58.38% | LR: 0.000227
Epoch: 080 | MCC: 0.059797 | Train loss: 0.9691 | Train acc: 51.43% | Val loss: 0.8117 | Val acc: 59.79% | LR: 0.000222
Epoch: 081 | MCC: 0.052550 | Train loss: 0.9685 | Train acc: 51.46% | Val loss: 0.8238 | Val acc: 58.83% | LR: 0.000217
Epoch: 082 | MCC: 0.018377 | Train loss: 0.9694 | Train acc: 51.48% | Val loss: 0.8309 | Val acc: 58.28% | LR: 0.000212
Epoch: 083 | MCC: 0.018307 | Train loss: 0.9715 | Train acc: 51.27% | Val loss: 0.8288 | Val acc: 58.70% | LR: 0.000206
Epoch: 084 | MCC: 0.024063 | Train loss: 0.9697 | Train acc: 51.44% | Val loss: 0.8405 | Val acc: 57.98% | LR: 0.000201
Epoch: 085 | MCC: 0.030388 | Train loss: 0.9700 | Train acc: 51.38% | Val loss: 0.8395 | Val acc: 58.18% | LR: 0.000196
Epoch: 086 | MCC: 0.034611 | Train loss: 0.9698 | Train acc: 51.49% | Val loss: 0.8423 | Val acc: 57.89% | LR: 0.000191
Epoch: 087 | MCC: 0.046654 | Train loss: 0.9669 | Train acc: 51.68% | Val loss: 0.8238 | Val acc: 58.92% | LR: 0.000186
Epoch: 088 | MCC: 0.034187 | Train loss: 0.9664 | Train acc: 51.66% | Val loss: 0.8282 | Val acc: 58.65% | LR: 0.000181
Epoch: 089 | MCC: 0.038823 | Train loss: 0.9673 | Train acc: 51.57% | Val loss: 0.8303 | Val acc: 58.34% | LR: 0.000176
Epoch: 090 | MCC: 0.026535 | Train loss: 0.9650 | Train acc: 51.66% | Val loss: 0.8369 | Val acc: 57.86% | LR: 0.000171
Epoch: 091 | MCC: 0.037364 | Train loss: 0.9673 | Train acc: 51.46% | Val loss: 0.8316 | Val acc: 58.26% | LR: 0.000166
Epoch: 092 | MCC: 0.039398 | Train loss: 0.9651 | Train acc: 51.59% | Val loss: 0.8318 | Val acc: 58.14% | LR: 0.000161
Epoch: 093 | MCC: 0.032586 | Train loss: 0.9662 | Train acc: 51.62% | Val loss: 0.8381 | Val acc: 57.79% | LR: 0.000156
Epoch: 094 | MCC: 0.037944 | Train loss: 0.9670 | Train acc: 51.57% | Val loss: 0.8289 | Val acc: 58.32% | LR: 0.000151
Epoch: 095 | MCC: 0.031414 | Train loss: 0.9650 | Train acc: 51.52% | Val loss: 0.8289 | Val acc: 58.25% | LR: 0.000146
Epoch: 096 | MCC: 0.050440 | Train loss: 0.9652 | Train acc: 51.76% | Val loss: 0.8245 | Val acc: 58.75% | LR: 0.000141
Epoch: 097 | MCC: 0.043368 | Train loss: 0.9643 | Train acc: 51.70% | Val loss: 0.8302 | Val acc: 58.29% | LR: 0.000137
Epoch: 098 | MCC: 0.028516 | Train loss: 0.9645 | Train acc: 51.66% | Val loss: 0.8342 | Val acc: 57.89% | LR: 0.000132
Epoch: 099 | MCC: 0.034359 | Train loss: 0.9637 | Train acc: 51.68% | Val loss: 0.8313 | Val acc: 58.39% | LR: 0.000127
Epoch: 100 | MCC: 0.050991 | Train loss: 0.9647 | Train acc: 51.81% | Val loss: 0.8261 | Val acc: 58.96% | LR: 0.000123
Epoch: 101 | MCC: 0.041867 | Train loss: 0.9652 | Train acc: 51.62% | Val loss: 0.8325 | Val acc: 58.31% | LR: 0.000118
Epoch: 102 | MCC: 0.034976 | Train loss: 0.9659 | Train acc: 51.93% | Val loss: 0.8349 | Val acc: 58.11% | LR: 0.000114
Epoch: 103 | MCC: 0.034091 | Train loss: 0.9639 | Train acc: 52.33% | Val loss: 0.8351 | Val acc: 58.09% | LR: 0.000110
Epoch: 104 | MCC: 0.035668 | Train loss: 0.9630 | Train acc: 52.29% | Val loss: 0.8341 | Val acc: 58.21% | LR: 0.000105
Epoch: 105 | MCC: 0.033165 | Train loss: 0.9637 | Train acc: 52.29% | Val loss: 0.8330 | Val acc: 58.12% | LR: 0.000101
Epoch: 106 | MCC: 0.030335 | Train loss: 0.9610 | Train acc: 52.38% | Val loss: 0.8332 | Val acc: 58.04% | LR: 0.000097
Epoch: 107 | MCC: 0.033225 | Train loss: 0.9648 | Train acc: 52.40% | Val loss: 0.8347 | Val acc: 57.89% | LR: 0.000093
Epoch: 108 | MCC: 0.034341 | Train loss: 0.9631 | Train acc: 52.14% | Val loss: 0.8328 | Val acc: 58.25% | LR: 0.000089
Epoch: 109 | MCC: 0.032555 | Train loss: 0.9611 | Train acc: 52.71% | Val loss: 0.8339 | Val acc: 58.01% | LR: 0.000085
Epoch: 110 | MCC: 0.028614 | Train loss: 0.9624 | Train acc: 52.39% | Val loss: 0.8346 | Val acc: 58.03% | LR: 0.000081
Epoch: 111 | MCC: 0.039043 | Train loss: 0.9630 | Train acc: 52.34% | Val loss: 0.8339 | Val acc: 58.31% | LR: 0.000077
Epoch: 112 | MCC: 0.033448 | Train loss: 0.9612 | Train acc: 52.34% | Val loss: 0.8328 | Val acc: 58.06% | LR: 0.000073
Epoch: 113 | MCC: 0.037745 | Train loss: 0.9606 | Train acc: 52.38% | Val loss: 0.8318 | Val acc: 58.23% | LR: 0.000070
Epoch: 114 | MCC: 0.034388 | Train loss: 0.9616 | Train acc: 52.38% | Val loss: 0.8350 | Val acc: 58.06% | LR: 0.000066
Epoch: 115 | MCC: 0.040115 | Train loss: 0.9594 | Train acc: 52.42% | Val loss: 0.8322 | Val acc: 58.28% | LR: 0.000062
Epoch: 116 | MCC: 0.031722 | Train loss: 0.9601 | Train acc: 52.51% | Val loss: 0.8339 | Val acc: 58.03% | LR: 0.000059
Epoch: 117 | MCC: 0.039302 | Train loss: 0.9608 | Train acc: 52.47% | Val loss: 0.8314 | Val acc: 58.35% | LR: 0.000056
Epoch: 118 | MCC: 0.040960 | Train loss: 0.9623 | Train acc: 52.32% | Val loss: 0.8311 | Val acc: 58.43% | LR: 0.000052
Epoch: 119 | MCC: 0.045055 | Train loss: 0.9598 | Train acc: 52.46% | Val loss: 0.8306 | Val acc: 58.58% | LR: 0.000049
Epoch: 120 | MCC: 0.041235 | Train loss: 0.9685 | Train acc: 52.49% | Val loss: 0.8337 | Val acc: 58.26% | LR: 0.000046
Epoch: 121 | MCC: 0.044865 | Train loss: 0.9642 | Train acc: 52.50% | Val loss: 0.8307 | Val acc: 58.58% | LR: 0.000043
Epoch: 122 | MCC: 0.042143 | Train loss: 0.9612 | Train acc: 52.43% | Val loss: 0.8320 | Val acc: 58.38% | LR: 0.000040
Epoch: 123 | MCC: 0.044826 | Train loss: 0.9604 | Train acc: 52.38% | Val loss: 0.8319 | Val acc: 58.38% | LR: 0.000038
Epoch: 124 | MCC: 0.037010 | Train loss: 0.9703 | Train acc: 52.58% | Val loss: 0.8318 | Val acc: 58.26% | LR: 0.000035
Epoch: 125 | MCC: 0.044728 | Train loss: 1.0315 | Train acc: 52.54% | Val loss: 0.8309 | Val acc: 58.58% | LR: 0.000032
Epoch: 126 | MCC: 0.043117 | Train loss: 0.9601 | Train acc: 52.52% | Val loss: 0.8310 | Val acc: 58.45% | LR: 0.000030
Epoch: 127 | MCC: 0.044985 | Train loss: 0.9597 | Train acc: 52.52% | Val loss: 0.8305 | Val acc: 58.55% | LR: 0.000027
Epoch: 128 | MCC: 0.046363 | Train loss: 0.9598 | Train acc: 52.45% | Val loss: 0.8310 | Val acc: 58.55% | LR: 0.000025
Epoch: 129 | MCC: 0.047553 | Train loss: 0.9608 | Train acc: 52.47% | Val loss: 0.8307 | Val acc: 58.60% | LR: 0.000023
Epoch: 130 | MCC: 0.045545 | Train loss: 0.9583 | Train acc: 52.58% | Val loss: 0.8305 | Val acc: 58.53% | LR: 0.000021
Epoch: 131 | MCC: 0.046230 | Train loss: 0.9591 | Train acc: 52.51% | Val loss: 0.8315 | Val acc: 58.53% | LR: 0.000019
Epoch: 132 | MCC: 0.047310 | Train loss: 0.9709 | Train acc: 52.40% | Val loss: 0.8304 | Val acc: 58.62% | LR: 0.000017
Epoch: 133 | MCC: 0.047100 | Train loss: 0.9763 | Train acc: 52.51% | Val loss: 0.8306 | Val acc: 58.62% | LR: 0.000015
Epoch: 134 | MCC: 0.045233 | Train loss: 0.9678 | Train acc: 52.47% | Val loss: 0.8309 | Val acc: 58.53% | LR: 0.000013
Epoch: 135 | MCC: 0.045057 | Train loss: 0.9655 | Train acc: 52.60% | Val loss: 0.8308 | Val acc: 58.50% | LR: 0.000012
Epoch: 136 | MCC: 0.045057 | Train loss: 1.0018 | Train acc: 52.47% | Val loss: 0.8307 | Val acc: 58.50% | LR: 0.000010
Epoch: 137 | MCC: 0.045512 | Train loss: 0.9824 | Train acc: 52.37% | Val loss: 0.8308 | Val acc: 58.53% | LR: 0.000009
Epoch: 138 | MCC: 0.045512 | Train loss: 1.0022 | Train acc: 52.78% | Val loss: 0.8308 | Val acc: 58.53% | LR: 0.000008
Epoch: 139 | MCC: 0.045057 | Train loss: 0.9784 | Train acc: 52.36% | Val loss: 0.8308 | Val acc: 58.50% | LR: 0.000007
Epoch: 140 | MCC: 0.045057 | Train loss: 1.0374 | Train acc: 52.60% | Val loss: 0.8308 | Val acc: 58.50% | LR: 0.000005
Epoch: 141 | MCC: 0.045057 | Train loss: 0.9921 | Train acc: 52.50% | Val loss: 0.8308 | Val acc: 58.50% | LR: 0.000005
Epoch: 142 | MCC: 0.045057 | Train loss: 1.0231 | Train acc: 52.63% | Val loss: 0.8308 | Val acc: 58.50% | LR: 0.000004
Epoch: 143 | MCC: 0.045057 | Train loss: 1.0771 | Train acc: 52.57% | Val loss: 0.8308 | Val acc: 58.50% | LR: 0.000003
Epoch: 144 | MCC: 0.045057 | Train loss: 0.9750 | Train acc: 52.53% | Val loss: 0.8308 | Val acc: 58.50% | LR: 0.000002
Epoch: 145 | MCC: 0.045057 | Train loss: 1.0360 | Train acc: 52.36% | Val loss: 0.8308 | Val acc: 58.50% | LR: 0.000002
Epoch: 146 | MCC: 0.045057 | Train loss: 0.9836 | Train acc: 52.61% | Val loss: 0.8308 | Val acc: 58.50% | LR: 0.000001
Epoch: 147 | MCC: 0.045057 | Train loss: 1.0652 | Train acc: 52.63% | Val loss: 0.8309 | Val acc: 58.50% | LR: 0.000001
Epoch: 148 | MCC: 0.045057 | Train loss: 1.3211 | Train acc: 52.53% | Val loss: 0.8309 | Val acc: 58.50% | LR: 0.000001
Epoch: 149 | MCC: 0.045057 | Train loss: 1.0241 | Train acc: 52.53% | Val loss: 0.8309 | Val acc: 58.50% | LR: 0.000001

[I 2025-10-05 09:43:30,859] Trial 32 finished with value: 0.04505739430896938 and parameters: {'lr': 0.0005066006666308747, 'hidden_size': 75, 'dropout': 0.04743043131826963, 'weight_decay': 0.006893930923964586}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.014006 | Train loss: 0.9968 | Train acc: 50.53% | Val loss: 1.0032 | Val acc: 49.83% | LR: 0.000244
Epoch: 001 | MCC: 0.038030 | Train loss: 0.9943 | Train acc: 50.75% | Val loss: 1.0004 | Val acc: 49.43% | LR: 0.000244
Epoch: 002 | MCC: 0.042487 | Train loss: 0.9934 | Train acc: 50.78% | Val loss: 0.9968 | Val acc: 50.33% | LR: 0.000244
Epoch: 003 | MCC: 0.046251 | Train loss: 0.9913 | Train acc: 50.82% | Val loss: 0.9932 | Val acc: 53.14% | LR: 0.000244
Epoch: 004 | MCC: 0.042437 | Train loss: 0.9905 | Train acc: 50.70% | Val loss: 0.9890 | Val acc: 54.11% | LR: 0.000244
Epoch: 005 | MCC: 0.040770 | Train loss: 0.9984 | Train acc: 50.90% | Val loss: 0.9829 | Val acc: 55.07% | LR: 0.000243
Epoch: 006 | MCC: 0.042980 | Train loss: 0.9932 | Train acc: 50.81% | Val loss: 0.9726 | Val acc: 55.62% | LR: 0.000243
Epoch: 007 | MCC: 0.035148 | Train loss: 0.9915 | Train acc: 50.91% | Val loss: 0.9635 | Val acc: 55.84% | LR: 0.000243
Epoch: 008 | MCC: 0.032314 | Train loss: 0.9895 | Train acc: 51.01% | Val loss: 0.9573 | Val acc: 55.89% | LR: 0.000242
Epoch: 009 | MCC: 0.029716 | Train loss: 0.9874 | Train acc: 50.98% | Val loss: 0.9480 | Val acc: 56.21% | LR: 0.000242
Epoch: 010 | MCC: 0.031531 | Train loss: 0.9857 | Train acc: 50.94% | Val loss: 0.9378 | Val acc: 56.42% | LR: 0.000241
Epoch: 011 | MCC: 0.029224 | Train loss: 0.9829 | Train acc: 50.90% | Val loss: 0.9298 | Val acc: 56.38% | LR: 0.000241
Epoch: 012 | MCC: 0.020950 | Train loss: 0.9825 | Train acc: 50.86% | Val loss: 0.9226 | Val acc: 56.35% | LR: 0.000240
Epoch: 013 | MCC: 0.021003 | Train loss: 0.9810 | Train acc: 50.92% | Val loss: 0.9183 | Val acc: 56.35% | LR: 0.000239
Epoch: 014 | MCC: 0.021289 | Train loss: 0.9821 | Train acc: 50.84% | Val loss: 0.9152 | Val acc: 56.39% | LR: 0.000238
Epoch: 015 | MCC: 0.028220 | Train loss: 0.9820 | Train acc: 50.90% | Val loss: 0.9093 | Val acc: 56.68% | LR: 0.000238
Epoch: 016 | MCC: 0.025330 | Train loss: 0.9802 | Train acc: 51.05% | Val loss: 0.9055 | Val acc: 56.56% | LR: 0.000237
Epoch: 017 | MCC: 0.032628 | Train loss: 0.9800 | Train acc: 51.04% | Val loss: 0.9019 | Val acc: 57.07% | LR: 0.000236
Epoch: 018 | MCC: 0.046650 | Train loss: 0.9794 | Train acc: 51.06% | Val loss: 0.8963 | Val acc: 57.82% | LR: 0.000235
Epoch: 019 | MCC: 0.050977 | Train loss: 0.9793 | Train acc: 51.11% | Val loss: 0.8900 | Val acc: 58.02% | LR: 0.000234
Epoch: 020 | MCC: 0.052317 | Train loss: 0.9799 | Train acc: 51.01% | Val loss: 0.8873 | Val acc: 58.27% | LR: 0.000233
Epoch: 021 | MCC: 0.038803 | Train loss: 0.9785 | Train acc: 51.05% | Val loss: 0.8837 | Val acc: 58.06% | LR: 0.000232
Epoch: 022 | MCC: 0.035485 | Train loss: 0.9781 | Train acc: 51.11% | Val loss: 0.8788 | Val acc: 57.62% | LR: 0.000230
Epoch: 023 | MCC: 0.033550 | Train loss: 0.9780 | Train acc: 51.11% | Val loss: 0.8733 | Val acc: 57.38% | LR: 0.000229
Epoch: 024 | MCC: 0.000946 | Train loss: 0.9775 | Train acc: 51.10% | Val loss: 0.8738 | Val acc: 56.67% | LR: 0.000228
Epoch: 025 | MCC: 0.005447 | Train loss: 0.9781 | Train acc: 51.12% | Val loss: 0.8674 | Val acc: 56.91% | LR: 0.000227
Epoch: 026 | MCC: 0.006644 | Train loss: 0.9769 | Train acc: 51.18% | Val loss: 0.8661 | Val acc: 57.18% | LR: 0.000225
Epoch: 027 | MCC: -0.009627 | Train loss: 0.9758 | Train acc: 51.21% | Val loss: 0.8731 | Val acc: 56.44% | LR: 0.000224
Epoch: 028 | MCC: -0.011402 | Train loss: 0.9745 | Train acc: 51.44% | Val loss: 0.8843 | Val acc: 56.51% | LR: 0.000223
Epoch: 029 | MCC: 0.000186 | Train loss: 0.9797 | Train acc: 51.35% | Val loss: 0.8928 | Val acc: 56.49% | LR: 0.000221
Epoch: 030 | MCC: 0.033440 | Train loss: 0.9790 | Train acc: 51.28% | Val loss: 0.8449 | Val acc: 59.81% | LR: 0.000220
Epoch: 031 | MCC: 0.035344 | Train loss: 0.9858 | Train acc: 51.33% | Val loss: 0.8734 | Val acc: 57.10% | LR: 0.000218
Epoch: 032 | MCC: 0.009653 | Train loss: 0.9741 | Train acc: 51.28% | Val loss: 0.8678 | Val acc: 56.94% | LR: 0.000216
Epoch: 033 | MCC: 0.015616 | Train loss: 0.9752 | Train acc: 51.25% | Val loss: 0.8769 | Val acc: 56.66% | LR: 0.000215
Epoch: 034 | MCC: 0.011056 | Train loss: 0.9750 | Train acc: 51.26% | Val loss: 0.8787 | Val acc: 56.39% | LR: 0.000213
Epoch: 035 | MCC: 0.012245 | Train loss: 0.9756 | Train acc: 51.21% | Val loss: 0.8817 | Val acc: 56.30% | LR: 0.000211
Epoch: 036 | MCC: 0.005589 | Train loss: 0.9744 | Train acc: 51.34% | Val loss: 0.8789 | Val acc: 56.46% | LR: 0.000210
Epoch: 037 | MCC: 0.020264 | Train loss: 0.9762 | Train acc: 51.28% | Val loss: 0.8968 | Val acc: 55.98% | LR: 0.000208
Epoch: 038 | MCC: 0.007327 | Train loss: 0.9785 | Train acc: 51.12% | Val loss: 0.9024 | Val acc: 55.39% | LR: 0.000206
Epoch: 039 | MCC: 0.000368 | Train loss: 0.9788 | Train acc: 50.94% | Val loss: 0.9013 | Val acc: 54.95% | LR: 0.000204
Epoch: 040 | MCC: 0.010026 | Train loss: 0.9843 | Train acc: 50.70% | Val loss: 0.9060 | Val acc: 54.81% | LR: 0.000202
Epoch: 041 | MCC: 0.011848 | Train loss: 0.9808 | Train acc: 50.89% | Val loss: 0.8993 | Val acc: 55.08% | LR: 0.000200
Epoch: 042 | MCC: 0.004448 | Train loss: 0.9780 | Train acc: 51.03% | Val loss: 0.8954 | Val acc: 55.27% | LR: 0.000198
Epoch: 043 | MCC: -0.001222 | Train loss: 0.9883 | Train acc: 51.08% | Val loss: 0.8938 | Val acc: 55.22% | LR: 0.000196
Epoch: 044 | MCC: 0.000337 | Train loss: 0.9768 | Train acc: 51.06% | Val loss: 0.8899 | Val acc: 55.66% | LR: 0.000194
Epoch: 045 | MCC: 0.007710 | Train loss: 0.9753 | Train acc: 51.16% | Val loss: 0.8859 | Val acc: 55.67% | LR: 0.000192
Epoch: 046 | MCC: 0.009540 | Train loss: 0.9761 | Train acc: 51.04% | Val loss: 0.8854 | Val acc: 55.89% | LR: 0.000190
Epoch: 047 | MCC: 0.015587 | Train loss: 0.9753 | Train acc: 51.15% | Val loss: 0.8872 | Val acc: 55.89% | LR: 0.000188
Epoch: 048 | MCC: 0.020898 | Train loss: 0.9778 | Train acc: 51.00% | Val loss: 0.8874 | Val acc: 56.10% | LR: 0.000186
Epoch: 049 | MCC: 0.029454 | Train loss: 0.9764 | Train acc: 51.03% | Val loss: 0.8824 | Val acc: 56.16% | LR: 0.000183
Epoch: 050 | MCC: 0.040684 | Train loss: 0.9788 | Train acc: 50.93% | Val loss: 0.8795 | Val acc: 56.43% | LR: 0.000181
Epoch: 051 | MCC: 0.035337 | Train loss: 0.9813 | Train acc: 51.01% | Val loss: 0.8831 | Val acc: 56.31% | LR: 0.000179
Epoch: 052 | MCC: 0.037269 | Train loss: 0.9793 | Train acc: 51.05% | Val loss: 0.8822 | Val acc: 56.40% | LR: 0.000177
Epoch: 053 | MCC: 0.035125 | Train loss: 0.9758 | Train acc: 51.13% | Val loss: 0.8811 | Val acc: 56.28% | LR: 0.000174
Epoch: 054 | MCC: 0.033294 | Train loss: 0.9770 | Train acc: 51.09% | Val loss: 0.8804 | Val acc: 56.37% | LR: 0.000172
Epoch: 055 | MCC: 0.041733 | Train loss: 0.9739 | Train acc: 51.20% | Val loss: 0.8832 | Val acc: 56.40% | LR: 0.000170
Epoch: 056 | MCC: 0.022746 | Train loss: 0.9764 | Train acc: 51.14% | Val loss: 0.8999 | Val acc: 55.76% | LR: 0.000167
Epoch: 057 | MCC: 0.015813 | Train loss: 0.9735 | Train acc: 51.25% | Val loss: 0.8950 | Val acc: 55.64% | LR: 0.000165
Epoch: 058 | MCC: 0.017389 | Train loss: 0.9749 | Train acc: 51.14% | Val loss: 0.8915 | Val acc: 55.79% | LR: 0.000163
Epoch: 059 | MCC: 0.017854 | Train loss: 0.9756 | Train acc: 51.11% | Val loss: 0.8907 | Val acc: 55.79% | LR: 0.000160
Epoch: 060 | MCC: 0.013523 | Train loss: 0.9836 | Train acc: 51.09% | Val loss: 0.8908 | Val acc: 55.79% | LR: 0.000158
Epoch: 061 | MCC: 0.013508 | Train loss: 0.9746 | Train acc: 51.04% | Val loss: 0.8867 | Val acc: 55.77% | LR: 0.000155
Epoch: 062 | MCC: 0.015834 | Train loss: 0.9731 | Train acc: 51.22% | Val loss: 0.8905 | Val acc: 55.84% | LR: 0.000153
Epoch: 063 | MCC: 0.015318 | Train loss: 0.9763 | Train acc: 51.00% | Val loss: 0.8883 | Val acc: 55.82% | LR: 0.000150
Epoch: 064 | MCC: 0.013750 | Train loss: 0.9747 | Train acc: 51.16% | Val loss: 0.8883 | Val acc: 55.77% | LR: 0.000148
Epoch: 065 | MCC: 0.016538 | Train loss: 0.9761 | Train acc: 51.12% | Val loss: 0.8870 | Val acc: 55.89% | LR: 0.000145
Epoch: 066 | MCC: 0.014622 | Train loss: 0.9819 | Train acc: 51.05% | Val loss: 0.8911 | Val acc: 55.79% | LR: 0.000143
Epoch: 067 | MCC: 0.013415 | Train loss: 0.9845 | Train acc: 51.14% | Val loss: 0.8890 | Val acc: 55.77% | LR: 0.000140
Epoch: 068 | MCC: 0.013079 | Train loss: 0.9832 | Train acc: 51.14% | Val loss: 0.8881 | Val acc: 55.75% | LR: 0.000138
Epoch: 069 | MCC: 0.016355 | Train loss: 0.9767 | Train acc: 51.10% | Val loss: 0.8890 | Val acc: 55.88% | LR: 0.000135
Epoch: 070 | MCC: 0.013420 | Train loss: 0.9741 | Train acc: 51.20% | Val loss: 0.8895 | Val acc: 55.77% | LR: 0.000133
Epoch: 071 | MCC: 0.023683 | Train loss: 0.9758 | Train acc: 51.08% | Val loss: 0.8897 | Val acc: 55.78% | LR: 0.000130
Epoch: 072 | MCC: 0.012775 | Train loss: 0.9766 | Train acc: 50.95% | Val loss: 0.8921 | Val acc: 55.59% | LR: 0.000128
Epoch: 073 | MCC: 0.028826 | Train loss: 0.9743 | Train acc: 51.19% | Val loss: 0.8875 | Val acc: 55.98% | LR: 0.000125
Epoch: 074 | MCC: 0.017247 | Train loss: 0.9756 | Train acc: 51.10% | Val loss: 0.8887 | Val acc: 55.86% | LR: 0.000123
Epoch: 075 | MCC: 0.011931 | Train loss: 0.9751 | Train acc: 51.07% | Val loss: 0.8925 | Val acc: 55.45% | LR: 0.000120
Epoch: 076 | MCC: 0.011772 | Train loss: 0.9743 | Train acc: 51.19% | Val loss: 0.8930 | Val acc: 55.42% | LR: 0.000118
Epoch: 077 | MCC: 0.013179 | Train loss: 0.9757 | Train acc: 51.15% | Val loss: 0.8931 | Val acc: 55.50% | LR: 0.000115
Epoch: 078 | MCC: 0.013618 | Train loss: 0.9741 | Train acc: 51.14% | Val loss: 0.8924 | Val acc: 55.52% | LR: 0.000112
Epoch: 079 | MCC: 0.013160 | Train loss: 0.9731 | Train acc: 51.20% | Val loss: 0.8925 | Val acc: 55.42% | LR: 0.000110
Epoch: 080 | MCC: -0.002600 | Train loss: 0.9732 | Train acc: 51.24% | Val loss: 0.8945 | Val acc: 55.27% | LR: 0.000107
Epoch: 081 | MCC: 0.000999 | Train loss: 0.9743 | Train acc: 51.16% | Val loss: 0.8909 | Val acc: 55.61% | LR: 0.000105
Epoch: 082 | MCC: -0.001726 | Train loss: 0.9732 | Train acc: 51.22% | Val loss: 0.8922 | Val acc: 55.51% | LR: 0.000102
Epoch: 083 | MCC: -0.001542 | Train loss: 0.9741 | Train acc: 51.11% | Val loss: 0.9643 | Val acc: 55.54% | LR: 0.000100
Epoch: 084 | MCC: -0.000632 | Train loss: 0.9737 | Train acc: 51.21% | Val loss: 0.8918 | Val acc: 55.51% | LR: 0.000097
Epoch: 085 | MCC: -0.001442 | Train loss: 0.9738 | Train acc: 51.19% | Val loss: 0.8900 | Val acc: 55.68% | LR: 0.000095
Epoch: 086 | MCC: 0.012915 | Train loss: 0.9717 | Train acc: 51.46% | Val loss: 0.8860 | Val acc: 55.82% | LR: 0.000092
Epoch: 087 | MCC: 0.014409 | Train loss: 0.9746 | Train acc: 51.11% | Val loss: 0.8829 | Val acc: 56.08% | LR: 0.000090
Epoch: 088 | MCC: 0.010792 | Train loss: 0.9741 | Train acc: 51.21% | Val loss: 0.8827 | Val acc: 56.03% | LR: 0.000087
Epoch: 089 | MCC: 0.014733 | Train loss: 0.9733 | Train acc: 51.18% | Val loss: 0.8795 | Val acc: 56.30% | LR: 0.000085
Epoch: 090 | MCC: 0.012953 | Train loss: 0.9733 | Train acc: 50.99% | Val loss: 0.8807 | Val acc: 56.18% | LR: 0.000083
Epoch: 091 | MCC: 0.015266 | Train loss: 0.9734 | Train acc: 51.09% | Val loss: 0.8828 | Val acc: 56.13% | LR: 0.000080
Epoch: 092 | MCC: 0.012929 | Train loss: 0.9733 | Train acc: 51.00% | Val loss: 0.8830 | Val acc: 56.01% | LR: 0.000078
Epoch: 093 | MCC: 0.010231 | Train loss: 0.9737 | Train acc: 51.16% | Val loss: 0.8849 | Val acc: 55.84% | LR: 0.000076
Epoch: 094 | MCC: -0.001139 | Train loss: 0.9735 | Train acc: 51.17% | Val loss: 0.8846 | Val acc: 55.95% | LR: 0.000073
Epoch: 095 | MCC: -0.004378 | Train loss: 0.9727 | Train acc: 52.00% | Val loss: 0.8892 | Val acc: 55.78% | LR: 0.000071
Epoch: 096 | MCC: -0.004316 | Train loss: 0.9707 | Train acc: 51.68% | Val loss: 0.8872 | Val acc: 55.78% | LR: 0.000069
Epoch: 097 | MCC: -0.006459 | Train loss: 0.9732 | Train acc: 51.48% | Val loss: 0.8865 | Val acc: 55.71% | LR: 0.000066
Epoch: 098 | MCC: 0.009783 | Train loss: 0.9755 | Train acc: 51.68% | Val loss: 0.8868 | Val acc: 55.84% | LR: 0.000064
Epoch: 099 | MCC: 0.011392 | Train loss: 0.9734 | Train acc: 51.46% | Val loss: 0.8867 | Val acc: 55.86% | LR: 0.000062
Epoch: 100 | MCC: 0.011190 | Train loss: 0.9721 | Train acc: 51.88% | Val loss: 0.8854 | Val acc: 55.94% | LR: 0.000060
Epoch: 101 | MCC: 0.011691 | Train loss: 0.9738 | Train acc: 51.67% | Val loss: 0.8891 | Val acc: 55.94% | LR: 0.000057
Epoch: 102 | MCC: 0.009396 | Train loss: 0.9734 | Train acc: 51.71% | Val loss: 0.8866 | Val acc: 55.79% | LR: 0.000055
Epoch: 103 | MCC: 0.009059 | Train loss: 0.9741 | Train acc: 51.35% | Val loss: 0.8863 | Val acc: 55.77% | LR: 0.000053
Epoch: 104 | MCC: 0.011628 | Train loss: 0.9747 | Train acc: 51.69% | Val loss: 0.8851 | Val acc: 55.94% | LR: 0.000051

[I 2025-10-05 09:44:58,136] Trial 33 finished with value: 0.01026690483558923 and parameters: {'lr': 0.0002443276972042333, 'hidden_size': 54, 'dropout': 0.23369347181913985, 'weight_decay': 0.013660391976652581}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: -0.020610 | Train loss: 1.0025 | Train acc: 50.12% | Val loss: 0.9993 | Val acc: 50.26% | LR: 0.000410
Epoch: 001 | MCC: -0.012423 | Train loss: 1.0014 | Train acc: 50.39% | Val loss: 0.9988 | Val acc: 49.86% | LR: 0.000410
Epoch: 002 | MCC: 0.016910 | Train loss: 1.0052 | Train acc: 49.77% | Val loss: 0.9994 | Val acc: 51.24% | LR: 0.000410
Epoch: 003 | MCC: 0.036804 | Train loss: 1.0028 | Train acc: 50.26% | Val loss: 0.9965 | Val acc: 53.21% | LR: 0.000409
Epoch: 004 | MCC: 0.025641 | Train loss: 1.0002 | Train acc: 50.83% | Val loss: 0.9900 | Val acc: 54.15% | LR: 0.000409
Epoch: 005 | MCC: 0.043396 | Train loss: 0.9965 | Train acc: 50.95% | Val loss: 0.9858 | Val acc: 54.88% | LR: 0.000408
Epoch: 006 | MCC: 0.022936 | Train loss: 0.9899 | Train acc: 51.06% | Val loss: 0.9778 | Val acc: 54.32% | LR: 0.000408
Epoch: 007 | MCC: 0.027872 | Train loss: 0.9895 | Train acc: 50.89% | Val loss: 0.9649 | Val acc: 55.23% | LR: 0.000407
Epoch: 008 | MCC: 0.018864 | Train loss: 0.9882 | Train acc: 50.81% | Val loss: 0.9525 | Val acc: 54.86% | LR: 0.000406
Epoch: 009 | MCC: 0.020427 | Train loss: 0.9839 | Train acc: 50.99% | Val loss: 0.9420 | Val acc: 54.98% | LR: 0.000405
Epoch: 010 | MCC: 0.017948 | Train loss: 0.9832 | Train acc: 50.94% | Val loss: 0.9321 | Val acc: 55.03% | LR: 0.000405
Epoch: 011 | MCC: 0.022984 | Train loss: 0.9814 | Train acc: 51.02% | Val loss: 0.9193 | Val acc: 55.54% | LR: 0.000403
Epoch: 012 | MCC: 0.021010 | Train loss: 0.9828 | Train acc: 50.94% | Val loss: 0.9154 | Val acc: 55.63% | LR: 0.000402
Epoch: 013 | MCC: 0.020543 | Train loss: 0.9826 | Train acc: 50.90% | Val loss: 0.9094 | Val acc: 55.85% | LR: 0.000401
Epoch: 014 | MCC: 0.020510 | Train loss: 0.9824 | Train acc: 50.98% | Val loss: 0.9051 | Val acc: 55.92% | LR: 0.000400
Epoch: 015 | MCC: 0.024421 | Train loss: 0.9824 | Train acc: 50.97% | Val loss: 0.9009 | Val acc: 56.17% | LR: 0.000399
Epoch: 016 | MCC: 0.038291 | Train loss: 0.9809 | Train acc: 50.97% | Val loss: 0.8982 | Val acc: 56.79% | LR: 0.000397
Epoch: 017 | MCC: 0.015752 | Train loss: 0.9806 | Train acc: 51.05% | Val loss: 0.8898 | Val acc: 56.91% | LR: 0.000396
Epoch: 018 | MCC: 0.022749 | Train loss: 0.9806 | Train acc: 51.06% | Val loss: 0.8863 | Val acc: 57.02% | LR: 0.000394
Epoch: 019 | MCC: 0.011094 | Train loss: 1.0084 | Train acc: 51.04% | Val loss: 1.0671 | Val acc: 55.74% | LR: 0.000392
Epoch: 020 | MCC: 0.033861 | Train loss: 1.0362 | Train acc: 51.06% | Val loss: 0.9326 | Val acc: 57.86% | LR: 0.000390
Epoch: 021 | MCC: 0.051234 | Train loss: 0.9871 | Train acc: 51.19% | Val loss: 0.8949 | Val acc: 58.04% | LR: 0.000389
Epoch: 022 | MCC: 0.031576 | Train loss: 0.9813 | Train acc: 51.05% | Val loss: 0.8964 | Val acc: 57.03% | LR: 0.000387
Epoch: 023 | MCC: 0.033134 | Train loss: 0.9821 | Train acc: 50.95% | Val loss: 0.8831 | Val acc: 57.31% | LR: 0.000385
Epoch: 024 | MCC: 0.030424 | Train loss: 0.9808 | Train acc: 50.99% | Val loss: 0.8772 | Val acc: 57.42% | LR: 0.000383
Epoch: 025 | MCC: 0.041201 | Train loss: 0.9803 | Train acc: 51.11% | Val loss: 0.8710 | Val acc: 57.38% | LR: 0.000380
Epoch: 026 | MCC: 0.053556 | Train loss: 0.9800 | Train acc: 50.99% | Val loss: 0.8751 | Val acc: 57.93% | LR: 0.000378
Epoch: 027 | MCC: 0.042476 | Train loss: 0.9809 | Train acc: 51.04% | Val loss: 1.1297 | Val acc: 57.87% | LR: 0.000376
Epoch: 028 | MCC: 0.056022 | Train loss: 0.9819 | Train acc: 51.06% | Val loss: 0.8661 | Val acc: 57.97% | LR: 0.000373
Epoch: 029 | MCC: 0.030371 | Train loss: 0.9812 | Train acc: 51.16% | Val loss: 0.8757 | Val acc: 57.26% | LR: 0.000371
Epoch: 030 | MCC: 0.044357 | Train loss: 0.9824 | Train acc: 51.12% | Val loss: 0.8632 | Val acc: 57.75% | LR: 0.000368
Epoch: 031 | MCC: 0.055814 | Train loss: 0.9804 | Train acc: 51.04% | Val loss: 0.8580 | Val acc: 58.05% | LR: 0.000366
Epoch: 032 | MCC: 0.052702 | Train loss: 0.9811 | Train acc: 50.97% | Val loss: 0.8587 | Val acc: 57.97% | LR: 0.000363
Epoch: 033 | MCC: 0.043932 | Train loss: 0.9803 | Train acc: 50.97% | Val loss: 0.8585 | Val acc: 57.94% | LR: 0.000360
Epoch: 034 | MCC: 0.048185 | Train loss: 0.9793 | Train acc: 51.07% | Val loss: 0.8572 | Val acc: 58.00% | LR: 0.000357
Epoch: 035 | MCC: 0.048278 | Train loss: 0.9789 | Train acc: 51.10% | Val loss: 0.8574 | Val acc: 57.95% | LR: 0.000354
Epoch: 036 | MCC: 0.041015 | Train loss: 0.9800 | Train acc: 51.04% | Val loss: 0.8604 | Val acc: 57.76% | LR: 0.000352
Epoch: 037 | MCC: 0.060526 | Train loss: 0.9795 | Train acc: 51.06% | Val loss: 0.8636 | Val acc: 57.69% | LR: 0.000349
Epoch: 038 | MCC: 0.048300 | Train loss: 0.9793 | Train acc: 51.04% | Val loss: 0.8628 | Val acc: 57.75% | LR: 0.000345
Epoch: 039 | MCC: 0.044808 | Train loss: 0.9793 | Train acc: 51.02% | Val loss: 0.8629 | Val acc: 57.87% | LR: 0.000342
Epoch: 040 | MCC: 0.052774 | Train loss: 0.9797 | Train acc: 51.06% | Val loss: 0.8636 | Val acc: 57.95% | LR: 0.000339
Epoch: 041 | MCC: 0.040580 | Train loss: 0.9778 | Train acc: 51.17% | Val loss: 0.8642 | Val acc: 57.99% | LR: 0.000336
Epoch: 042 | MCC: 0.040418 | Train loss: 0.9830 | Train acc: 51.20% | Val loss: 0.8574 | Val acc: 58.06% | LR: 0.000332
Epoch: 043 | MCC: 0.043919 | Train loss: 0.9792 | Train acc: 51.02% | Val loss: 0.8569 | Val acc: 58.08% | LR: 0.000329
Epoch: 044 | MCC: 0.051271 | Train loss: 0.9799 | Train acc: 50.95% | Val loss: 0.8503 | Val acc: 58.46% | LR: 0.000326
Epoch: 045 | MCC: 0.054162 | Train loss: 0.9800 | Train acc: 51.04% | Val loss: 0.8466 | Val acc: 58.90% | LR: 0.000322
Epoch: 046 | MCC: 0.051292 | Train loss: 0.9950 | Train acc: 51.04% | Val loss: 0.8456 | Val acc: 59.17% | LR: 0.000319
Epoch: 047 | MCC: 0.046917 | Train loss: 0.9803 | Train acc: 51.00% | Val loss: 0.8479 | Val acc: 59.10% | LR: 0.000315
Epoch: 048 | MCC: 0.054867 | Train loss: 0.9789 | Train acc: 51.09% | Val loss: 0.8469 | Val acc: 59.00% | LR: 0.000311
Epoch: 049 | MCC: 0.045784 | Train loss: 0.9789 | Train acc: 51.05% | Val loss: 0.8574 | Val acc: 58.05% | LR: 0.000308
Epoch: 050 | MCC: 0.033556 | Train loss: 0.9980 | Train acc: 51.15% | Val loss: 0.8598 | Val acc: 57.70% | LR: 0.000304
Epoch: 051 | MCC: -0.004277 | Train loss: 0.9806 | Train acc: 51.02% | Val loss: 0.8596 | Val acc: 57.45% | LR: 0.000300
Epoch: 052 | MCC: 0.016560 | Train loss: 0.9777 | Train acc: 51.14% | Val loss: 0.8413 | Val acc: 58.62% | LR: 0.000296
Epoch: 053 | MCC: 0.024334 | Train loss: 0.9782 | Train acc: 51.07% | Val loss: 0.8483 | Val acc: 58.35% | LR: 0.000293
Epoch: 054 | MCC: 0.009258 | Train loss: 0.9782 | Train acc: 51.02% | Val loss: 0.8590 | Val acc: 57.43% | LR: 0.000289
Epoch: 055 | MCC: 0.006643 | Train loss: 0.9798 | Train acc: 51.02% | Val loss: 0.8734 | Val acc: 56.72% | LR: 0.000285
Epoch: 056 | MCC: 0.003514 | Train loss: 0.9799 | Train acc: 51.05% | Val loss: 0.8774 | Val acc: 56.14% | LR: 0.000281
Epoch: 057 | MCC: 0.006647 | Train loss: 0.9782 | Train acc: 50.99% | Val loss: 0.9105 | Val acc: 56.69% | LR: 0.000277
Epoch: 058 | MCC: 0.007121 | Train loss: 0.9767 | Train acc: 51.12% | Val loss: 0.8687 | Val acc: 56.72% | LR: 0.000273
Epoch: 059 | MCC: 0.001336 | Train loss: 0.9793 | Train acc: 50.92% | Val loss: 0.9656 | Val acc: 56.33% | LR: 0.000269
Epoch: 060 | MCC: 0.009215 | Train loss: 0.9775 | Train acc: 51.12% | Val loss: 0.8782 | Val acc: 56.62% | LR: 0.000265
Epoch: 061 | MCC: 0.007851 | Train loss: 0.9777 | Train acc: 51.06% | Val loss: 0.8812 | Val acc: 56.62% | LR: 0.000260
Epoch: 062 | MCC: 0.005250 | Train loss: 0.9783 | Train acc: 51.02% | Val loss: 0.8744 | Val acc: 56.50% | LR: 0.000256
Epoch: 063 | MCC: 0.007007 | Train loss: 0.9775 | Train acc: 51.11% | Val loss: 0.8763 | Val acc: 56.36% | LR: 0.000252
Epoch: 064 | MCC: 0.004463 | Train loss: 0.9759 | Train acc: 51.23% | Val loss: 0.8769 | Val acc: 56.12% | LR: 0.000248
Epoch: 065 | MCC: -0.008214 | Train loss: 0.9787 | Train acc: 51.03% | Val loss: 0.8785 | Val acc: 56.00% | LR: 0.000244
Epoch: 066 | MCC: 0.002483 | Train loss: 0.9766 | Train acc: 51.10% | Val loss: 0.8828 | Val acc: 55.97% | LR: 0.000240
Epoch: 067 | MCC: 0.001835 | Train loss: 0.9774 | Train acc: 51.10% | Val loss: 0.8884 | Val acc: 55.97% | LR: 0.000235
Epoch: 068 | MCC: 0.009311 | Train loss: 0.9766 | Train acc: 51.20% | Val loss: 0.8756 | Val acc: 56.55% | LR: 0.000231
Epoch: 069 | MCC: 0.006448 | Train loss: 0.9802 | Train acc: 51.00% | Val loss: 0.8696 | Val acc: 56.84% | LR: 0.000227
Epoch: 070 | MCC: 0.007185 | Train loss: 0.9773 | Train acc: 51.10% | Val loss: 0.8633 | Val acc: 57.26% | LR: 0.000223
Epoch: 071 | MCC: 0.005716 | Train loss: 0.9772 | Train acc: 51.21% | Val loss: 0.8653 | Val acc: 56.89% | LR: 0.000218
Epoch: 072 | MCC: 0.008722 | Train loss: 0.9769 | Train acc: 51.15% | Val loss: 0.8661 | Val acc: 57.01% | LR: 0.000214
Epoch: 073 | MCC: 0.007283 | Train loss: 0.9764 | Train acc: 51.19% | Val loss: 0.8694 | Val acc: 57.01% | LR: 0.000210
Epoch: 074 | MCC: 0.015746 | Train loss: 0.9778 | Train acc: 51.13% | Val loss: 0.8726 | Val acc: 56.72% | LR: 0.000205
Epoch: 075 | MCC: 0.007492 | Train loss: 0.9786 | Train acc: 50.92% | Val loss: 0.8769 | Val acc: 56.18% | LR: 0.000201
Epoch: 076 | MCC: 0.005856 | Train loss: 0.9774 | Train acc: 51.06% | Val loss: 0.8837 | Val acc: 56.21% | LR: 0.000197
Epoch: 077 | MCC: 0.004799 | Train loss: 0.9765 | Train acc: 51.13% | Val loss: 0.8783 | Val acc: 56.11% | LR: 0.000193
Epoch: 078 | MCC: 0.006793 | Train loss: 0.9777 | Train acc: 51.03% | Val loss: 0.8781 | Val acc: 56.21% | LR: 0.000188
Epoch: 079 | MCC: 0.006344 | Train loss: 0.9761 | Train acc: 51.16% | Val loss: 0.8780 | Val acc: 56.23% | LR: 0.000184
Epoch: 080 | MCC: -0.002196 | Train loss: 0.9764 | Train acc: 51.17% | Val loss: 0.8856 | Val acc: 56.33% | LR: 0.000180
Epoch: 081 | MCC: 0.004316 | Train loss: 0.9772 | Train acc: 51.04% | Val loss: 0.8751 | Val acc: 56.33% | LR: 0.000176
Epoch: 082 | MCC: 0.003541 | Train loss: 0.9759 | Train acc: 51.21% | Val loss: 0.8767 | Val acc: 56.18% | LR: 0.000171
Epoch: 083 | MCC: -0.006979 | Train loss: 0.9761 | Train acc: 51.16% | Val loss: 0.8841 | Val acc: 55.79% | LR: 0.000167
Epoch: 084 | MCC: 0.006465 | Train loss: 0.9775 | Train acc: 50.99% | Val loss: 0.8811 | Val acc: 56.11% | LR: 0.000163
Epoch: 085 | MCC: 0.005900 | Train loss: 0.9765 | Train acc: 51.02% | Val loss: 0.8858 | Val acc: 55.99% | LR: 0.000159
Epoch: 086 | MCC: -0.010271 | Train loss: 0.9762 | Train acc: 51.14% | Val loss: 0.8865 | Val acc: 55.53% | LR: 0.000155
Epoch: 087 | MCC: 0.005417 | Train loss: 0.9769 | Train acc: 51.05% | Val loss: 0.8787 | Val acc: 56.24% | LR: 0.000150
Epoch: 088 | MCC: 0.005746 | Train loss: 0.9774 | Train acc: 51.03% | Val loss: 0.8788 | Val acc: 56.19% | LR: 0.000146
Epoch: 089 | MCC: 0.002885 | Train loss: 0.9761 | Train acc: 51.12% | Val loss: 0.8808 | Val acc: 56.05% | LR: 0.000142
Epoch: 090 | MCC: 0.005523 | Train loss: 0.9775 | Train acc: 51.04% | Val loss: 0.8795 | Val acc: 56.22% | LR: 0.000138
Epoch: 091 | MCC: 0.004635 | Train loss: 0.9762 | Train acc: 51.21% | Val loss: 0.8824 | Val acc: 56.19% | LR: 0.000134
Epoch: 092 | MCC: 0.005627 | Train loss: 0.9776 | Train acc: 51.02% | Val loss: 0.8781 | Val acc: 56.22% | LR: 0.000130
Epoch: 093 | MCC: 0.000751 | Train loss: 0.9753 | Train acc: 51.13% | Val loss: 0.8813 | Val acc: 55.95% | LR: 0.000126
Epoch: 094 | MCC: 0.001528 | Train loss: 0.9759 | Train acc: 51.11% | Val loss: 0.8810 | Val acc: 55.90% | LR: 0.000122
Epoch: 095 | MCC: 0.006535 | Train loss: 0.9833 | Train acc: 50.98% | Val loss: 0.8810 | Val acc: 56.24% | LR: 0.000118
Epoch: 096 | MCC: 0.003132 | Train loss: 0.9786 | Train acc: 50.94% | Val loss: 0.8778 | Val acc: 56.12% | LR: 0.000115
Epoch: 097 | MCC: 0.006918 | Train loss: 0.9769 | Train acc: 50.96% | Val loss: 0.8757 | Val acc: 56.34% | LR: 0.000111
Epoch: 098 | MCC: 0.006456 | Train loss: 0.9765 | Train acc: 51.11% | Val loss: 0.8868 | Val acc: 56.24% | LR: 0.000107
Epoch: 099 | MCC: 0.006196 | Train loss: 0.9768 | Train acc: 51.06% | Val loss: 0.8835 | Val acc: 56.17% | LR: 0.000103
Epoch: 100 | MCC: 0.003662 | Train loss: 0.9779 | Train acc: 51.07% | Val loss: 0.8809 | Val acc: 56.00% | LR: 0.000100
Epoch: 101 | MCC: 0.005714 | Train loss: 0.9751 | Train acc: 51.16% | Val loss: 0.8806 | Val acc: 56.07% | LR: 0.000096
Epoch: 102 | MCC: 0.005714 | Train loss: 0.9758 | Train acc: 51.11% | Val loss: 0.8798 | Val acc: 56.07% | LR: 0.000092
Epoch: 103 | MCC: 0.003090 | Train loss: 0.9758 | Train acc: 51.19% | Val loss: 0.8801 | Val acc: 55.97% | LR: 0.000089
Epoch: 104 | MCC: 0.005411 | Train loss: 0.9765 | Train acc: 51.14% | Val loss: 0.8788 | Val acc: 56.12% | LR: 0.000085
Epoch: 105 | MCC: 0.004303 | Train loss: 0.9764 | Train acc: 51.16% | Val loss: 0.8811 | Val acc: 56.09% | LR: 0.000082
Epoch: 106 | MCC: 0.003236 | Train loss: 0.9786 | Train acc: 50.98% | Val loss: 0.8808 | Val acc: 56.07% | LR: 0.000078
Epoch: 107 | MCC: 0.005901 | Train loss: 0.9758 | Train acc: 51.17% | Val loss: 0.8779 | Val acc: 56.14% | LR: 0.000075
Epoch: 108 | MCC: 0.005017 | Train loss: 0.9758 | Train acc: 51.10% | Val loss: 0.8797 | Val acc: 56.07% | LR: 0.000072
Epoch: 109 | MCC: 0.003652 | Train loss: 0.9740 | Train acc: 51.21% | Val loss: 0.9086 | Val acc: 56.07% | LR: 0.000069
Epoch: 110 | MCC: 0.004025 | Train loss: 0.9811 | Train acc: 51.09% | Val loss: 0.8784 | Val acc: 56.05% | LR: 0.000065
Epoch: 111 | MCC: 0.003576 | Train loss: 0.9747 | Train acc: 51.22% | Val loss: 0.8807 | Val acc: 56.00% | LR: 0.000062
Epoch: 112 | MCC: 0.003869 | Train loss: 0.9755 | Train acc: 51.20% | Val loss: 0.8804 | Val acc: 55.95% | LR: 0.000059
Epoch: 113 | MCC: 0.005028 | Train loss: 0.9760 | Train acc: 51.10% | Val loss: 0.8807 | Val acc: 55.97% | LR: 0.000056
Epoch: 114 | MCC: 0.005070 | Train loss: 0.9740 | Train acc: 51.17% | Val loss: 0.8806 | Val acc: 55.97% | LR: 0.000054
Epoch: 115 | MCC: 0.005530 | Train loss: 0.9753 | Train acc: 51.16% | Val loss: 0.8802 | Val acc: 56.00% | LR: 0.000051
Epoch: 116 | MCC: 0.006285 | Train loss: 0.9761 | Train acc: 51.07% | Val loss: 0.8809 | Val acc: 56.07% | LR: 0.000048
Epoch: 117 | MCC: 0.005417 | Train loss: 0.9771 | Train acc: 50.98% | Val loss: 0.8851 | Val acc: 56.02% | LR: 0.000045
Epoch: 118 | MCC: 0.003949 | Train loss: 0.9751 | Train acc: 51.24% | Val loss: 0.8857 | Val acc: 55.95% | LR: 0.000043
Epoch: 119 | MCC: 0.003886 | Train loss: 0.9753 | Train acc: 51.12% | Val loss: 0.8794 | Val acc: 55.95% | LR: 0.000040
Epoch: 120 | MCC: 0.003660 | Train loss: 0.9768 | Train acc: 51.03% | Val loss: 0.8791 | Val acc: 55.97% | LR: 0.000038
Epoch: 121 | MCC: 0.002677 | Train loss: 0.9762 | Train acc: 51.08% | Val loss: 0.8872 | Val acc: 55.92% | LR: 0.000035
Epoch: 122 | MCC: -0.005704 | Train loss: 0.9770 | Train acc: 51.01% | Val loss: 0.8823 | Val acc: 55.95% | LR: 0.000033
Epoch: 123 | MCC: 0.003137 | Train loss: 0.9768 | Train acc: 51.06% | Val loss: 0.8789 | Val acc: 55.95% | LR: 0.000031
Epoch: 124 | MCC: 0.003660 | Train loss: 0.9765 | Train acc: 51.07% | Val loss: 0.8793 | Val acc: 55.97% | LR: 0.000028
Epoch: 125 | MCC: 0.003449 | Train loss: 0.9771 | Train acc: 50.98% | Val loss: 0.8790 | Val acc: 56.00% | LR: 0.000026
Epoch: 126 | MCC: 0.003995 | Train loss: 0.9765 | Train acc: 51.12% | Val loss: 0.8799 | Val acc: 56.02% | LR: 0.000024

[I 2025-10-05 09:46:42,404] Trial 34 finished with value: 0.0029867375269532204 and parameters: {'lr': 0.000409907020002607, 'hidden_size': 44, 'dropout': 0.13004307746614968, 'weight_decay': 0.05019673724365944}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.011301 | Train loss: 0.9971 | Train acc: 50.77% | Val loss: 0.9825 | Val acc: 54.62% | LR: 0.001349
Epoch: 001 | MCC: 0.030975 | Train loss: 0.9886 | Train acc: 50.82% | Val loss: 0.9539 | Val acc: 55.79% | LR: 0.001349
Epoch: 002 | MCC: 0.018950 | Train loss: 0.9860 | Train acc: 50.75% | Val loss: 0.9200 | Val acc: 55.96% | LR: 0.001348
Epoch: 003 | MCC: 0.028684 | Train loss: 0.9884 | Train acc: 50.80% | Val loss: 1.0318 | Val acc: 56.16% | LR: 0.001347
Epoch: 004 | MCC: 0.023078 | Train loss: 1.0060 | Train acc: 50.69% | Val loss: 0.9614 | Val acc: 54.22% | LR: 0.001346
Epoch: 005 | MCC: 0.020711 | Train loss: 1.0314 | Train acc: 50.96% | Val loss: 0.9547 | Val acc: 54.33% | LR: 0.001344
Epoch: 006 | MCC: 0.023120 | Train loss: 0.9879 | Train acc: 50.87% | Val loss: 0.9524 | Val acc: 54.39% | LR: 0.001342
Epoch: 007 | MCC: 0.030426 | Train loss: 0.9838 | Train acc: 50.93% | Val loss: 0.9426 | Val acc: 54.91% | LR: 0.001340
Epoch: 008 | MCC: 0.029073 | Train loss: 0.9834 | Train acc: 51.03% | Val loss: 0.9432 | Val acc: 54.41% | LR: 0.001338
Epoch: 009 | MCC: 0.034971 | Train loss: 0.9837 | Train acc: 50.85% | Val loss: 0.9331 | Val acc: 55.25% | LR: 0.001335
Epoch: 010 | MCC: 0.024674 | Train loss: 0.9817 | Train acc: 50.88% | Val loss: 0.9317 | Val acc: 54.62% | LR: 0.001332
Epoch: 011 | MCC: 0.023560 | Train loss: 0.9812 | Train acc: 51.02% | Val loss: 0.9318 | Val acc: 54.24% | LR: 0.001328
Epoch: 012 | MCC: 0.020910 | Train loss: 0.9846 | Train acc: 50.80% | Val loss: 0.9211 | Val acc: 54.14% | LR: 0.001325
Epoch: 013 | MCC: 0.023795 | Train loss: 0.9835 | Train acc: 50.90% | Val loss: 0.9238 | Val acc: 54.12% | LR: 0.001321
Epoch: 014 | MCC: 0.024015 | Train loss: 0.9817 | Train acc: 51.10% | Val loss: 0.9176 | Val acc: 54.93% | LR: 0.001317
Epoch: 015 | MCC: 0.023846 | Train loss: 0.9838 | Train acc: 51.06% | Val loss: 0.9010 | Val acc: 56.42% | LR: 0.001312
Epoch: 016 | MCC: 0.020841 | Train loss: 0.9814 | Train acc: 50.99% | Val loss: 0.9119 | Val acc: 55.70% | LR: 0.001307
Epoch: 017 | MCC: 0.021866 | Train loss: 0.9809 | Train acc: 50.91% | Val loss: 0.9031 | Val acc: 55.38% | LR: 0.001302
Epoch: 018 | MCC: 0.032588 | Train loss: 0.9814 | Train acc: 50.98% | Val loss: 0.9050 | Val acc: 55.34% | LR: 0.001297
Epoch: 019 | MCC: 0.025215 | Train loss: 0.9786 | Train acc: 51.30% | Val loss: 0.9008 | Val acc: 54.99% | LR: 0.001291
Epoch: 020 | MCC: 0.033559 | Train loss: 0.9778 | Train acc: 51.68% | Val loss: 0.9021 | Val acc: 54.84% | LR: 0.001285
Epoch: 021 | MCC: 0.015568 | Train loss: 0.9770 | Train acc: 51.64% | Val loss: 0.9176 | Val acc: 54.50% | LR: 0.001279
Epoch: 022 | MCC: 0.021048 | Train loss: 0.9776 | Train acc: 51.63% | Val loss: 0.9096 | Val acc: 54.54% | LR: 0.001273
Epoch: 023 | MCC: 0.012876 | Train loss: 0.9773 | Train acc: 51.63% | Val loss: 0.9130 | Val acc: 54.62% | LR: 0.001266
Epoch: 024 | MCC: 0.011001 | Train loss: 0.9768 | Train acc: 51.61% | Val loss: 0.9019 | Val acc: 54.88% | LR: 0.001259
Epoch: 025 | MCC: 0.013228 | Train loss: 0.9754 | Train acc: 51.64% | Val loss: 0.9094 | Val acc: 55.65% | LR: 0.001252
Epoch: 026 | MCC: 0.014408 | Train loss: 0.9770 | Train acc: 51.66% | Val loss: 0.9009 | Val acc: 55.68% | LR: 0.001245
Epoch: 027 | MCC: 0.022345 | Train loss: 0.9766 | Train acc: 51.71% | Val loss: 0.9076 | Val acc: 55.01% | LR: 0.001237
Epoch: 028 | MCC: 0.004269 | Train loss: 0.9768 | Train acc: 51.59% | Val loss: 0.9049 | Val acc: 55.80% | LR: 0.001229
Epoch: 029 | MCC: 0.007042 | Train loss: 0.9764 | Train acc: 51.73% | Val loss: 0.8991 | Val acc: 56.08% | LR: 0.001221
Epoch: 030 | MCC: 0.003462 | Train loss: 0.9745 | Train acc: 51.82% | Val loss: 0.9102 | Val acc: 56.06% | LR: 0.001212
Epoch: 031 | MCC: 0.009343 | Train loss: 0.9749 | Train acc: 51.77% | Val loss: 0.9085 | Val acc: 55.87% | LR: 0.001204
Epoch: 032 | MCC: 0.018035 | Train loss: 0.9828 | Train acc: 51.67% | Val loss: 0.8881 | Val acc: 55.77% | LR: 0.001195
Epoch: 033 | MCC: 0.013049 | Train loss: 0.9757 | Train acc: 51.85% | Val loss: 0.8809 | Val acc: 56.43% | LR: 0.001186
Epoch: 034 | MCC: 0.003795 | Train loss: 0.9774 | Train acc: 51.77% | Val loss: 0.8764 | Val acc: 56.34% | LR: 0.001176
Epoch: 035 | MCC: 0.018513 | Train loss: 0.9772 | Train acc: 51.69% | Val loss: 0.9199 | Val acc: 57.72% | LR: 0.001167
Epoch: 036 | MCC: 0.020435 | Train loss: 0.9789 | Train acc: 51.84% | Val loss: 0.8770 | Val acc: 57.58% | LR: 0.001157
Epoch: 037 | MCC: 0.011359 | Train loss: 0.9741 | Train acc: 51.78% | Val loss: 0.8770 | Val acc: 56.90% | LR: 0.001147
Epoch: 038 | MCC: -0.002879 | Train loss: 0.9744 | Train acc: 52.01% | Val loss: 0.8898 | Val acc: 56.27% | LR: 0.001137
Epoch: 039 | MCC: 0.011961 | Train loss: 0.9729 | Train acc: 51.98% | Val loss: 0.8845 | Val acc: 56.61% | LR: 0.001126
Epoch: 040 | MCC: 0.016149 | Train loss: 0.9742 | Train acc: 51.78% | Val loss: 0.9001 | Val acc: 56.27% | LR: 0.001116
Epoch: 041 | MCC: 0.015877 | Train loss: 0.9702 | Train acc: 52.04% | Val loss: 0.9027 | Val acc: 55.91% | LR: 0.001105
Epoch: 042 | MCC: 0.019182 | Train loss: 0.9804 | Train acc: 51.34% | Val loss: 0.9018 | Val acc: 55.90% | LR: 0.001094
Epoch: 043 | MCC: -0.001147 | Train loss: 0.9725 | Train acc: 51.88% | Val loss: 0.8875 | Val acc: 56.77% | LR: 0.001083
Epoch: 044 | MCC: 0.005901 | Train loss: 0.9705 | Train acc: 52.01% | Val loss: 0.8916 | Val acc: 56.92% | LR: 0.001072
Epoch: 045 | MCC: -0.003918 | Train loss: 0.9707 | Train acc: 52.12% | Val loss: 0.9262 | Val acc: 55.58% | LR: 0.001060
Epoch: 046 | MCC: -0.007399 | Train loss: 0.9712 | Train acc: 51.89% | Val loss: 0.9029 | Val acc: 55.83% | LR: 0.001048
Epoch: 047 | MCC: -0.000573 | Train loss: 0.9699 | Train acc: 52.01% | Val loss: 0.8919 | Val acc: 55.58% | LR: 0.001037
Epoch: 048 | MCC: 0.004484 | Train loss: 0.9696 | Train acc: 51.99% | Val loss: 0.8831 | Val acc: 56.16% | LR: 0.001025
Epoch: 049 | MCC: 0.000534 | Train loss: 0.9690 | Train acc: 51.97% | Val loss: 0.8952 | Val acc: 56.00% | LR: 0.001012
Epoch: 050 | MCC: 0.000320 | Train loss: 0.9763 | Train acc: 51.87% | Val loss: 0.9188 | Val acc: 55.03% | LR: 0.001000
Epoch: 051 | MCC: -0.005525 | Train loss: 0.9709 | Train acc: 51.87% | Val loss: 0.8812 | Val acc: 55.75% | LR: 0.000988
Epoch: 052 | MCC: 0.008959 | Train loss: 0.9797 | Train acc: 51.78% | Val loss: 0.8899 | Val acc: 57.07% | LR: 0.000975
Epoch: 053 | MCC: -0.004775 | Train loss: 0.9781 | Train acc: 52.05% | Val loss: 0.9033 | Val acc: 55.14% | LR: 0.000962
Epoch: 054 | MCC: -0.004139 | Train loss: 0.9726 | Train acc: 51.89% | Val loss: 0.8845 | Val acc: 55.68% | LR: 0.000950
Epoch: 055 | MCC: 0.003275 | Train loss: 0.9726 | Train acc: 51.90% | Val loss: 0.9151 | Val acc: 54.95% | LR: 0.000937
Epoch: 056 | MCC: 0.001262 | Train loss: 0.9866 | Train acc: 50.98% | Val loss: 0.9145 | Val acc: 54.95% | LR: 0.000923
Epoch: 057 | MCC: -0.011084 | Train loss: 0.9893 | Train acc: 50.91% | Val loss: 0.9122 | Val acc: 54.90% | LR: 0.000910
Epoch: 058 | MCC: 0.002249 | Train loss: 0.9827 | Train acc: 51.42% | Val loss: 0.9199 | Val acc: 53.24% | LR: 0.000897
Epoch: 059 | MCC: 0.022417 | Train loss: 0.9778 | Train acc: 51.74% | Val loss: 0.9273 | Val acc: 54.64% | LR: 0.000884
Epoch: 060 | MCC: 0.019052 | Train loss: 0.9785 | Train acc: 51.66% | Val loss: 0.9210 | Val acc: 55.80% | LR: 0.000870
Epoch: 061 | MCC: 0.009909 | Train loss: 0.9767 | Train acc: 51.73% | Val loss: 0.9178 | Val acc: 55.77% | LR: 0.000857
Epoch: 062 | MCC: 0.029432 | Train loss: 0.9792 | Train acc: 51.69% | Val loss: 0.9271 | Val acc: 57.30% | LR: 0.000843
Epoch: 063 | MCC: 0.010355 | Train loss: 0.9840 | Train acc: 51.45% | Val loss: 1.1607 | Val acc: 53.35% | LR: 0.000829
Epoch: 064 | MCC: 0.000619 | Train loss: 0.9982 | Train acc: 51.58% | Val loss: 0.9626 | Val acc: 55.77% | LR: 0.000815
Epoch: 065 | MCC: 0.021996 | Train loss: 0.9770 | Train acc: 51.90% | Val loss: 0.9183 | Val acc: 58.83% | LR: 0.000802
Epoch: 066 | MCC: 0.021717 | Train loss: 0.9775 | Train acc: 51.70% | Val loss: 0.8972 | Val acc: 59.16% | LR: 0.000788
Epoch: 067 | MCC: -0.006970 | Train loss: 0.9749 | Train acc: 51.84% | Val loss: 0.9099 | Val acc: 57.11% | LR: 0.000774
Epoch: 068 | MCC: -0.000914 | Train loss: 0.9743 | Train acc: 51.94% | Val loss: 0.9059 | Val acc: 55.69% | LR: 0.000760
Epoch: 069 | MCC: -0.003124 | Train loss: 0.9750 | Train acc: 51.94% | Val loss: 0.9368 | Val acc: 54.56% | LR: 0.000746
Epoch: 070 | MCC: -0.010458 | Train loss: 0.9761 | Train acc: 51.92% | Val loss: 0.9702 | Val acc: 52.07% | LR: 0.000732
Epoch: 071 | MCC: 0.016595 | Train loss: 0.9731 | Train acc: 52.00% | Val loss: 0.9041 | Val acc: 55.81% | LR: 0.000718
Epoch: 072 | MCC: 0.004897 | Train loss: 0.9712 | Train acc: 52.14% | Val loss: 0.9084 | Val acc: 55.90% | LR: 0.000704
Epoch: 073 | MCC: -0.007965 | Train loss: 0.9724 | Train acc: 51.97% | Val loss: 0.9153 | Val acc: 55.10% | LR: 0.000689
Epoch: 074 | MCC: -0.014636 | Train loss: 0.9718 | Train acc: 52.14% | Val loss: 0.9240 | Val acc: 54.51% | LR: 0.000675
Epoch: 075 | MCC: -0.011120 | Train loss: 0.9747 | Train acc: 51.89% | Val loss: 0.9071 | Val acc: 54.75% | LR: 0.000661
Epoch: 076 | MCC: -0.004274 | Train loss: 0.9719 | Train acc: 52.00% | Val loss: 0.9152 | Val acc: 55.18% | LR: 0.000647
Epoch: 077 | MCC: -0.007425 | Train loss: 0.9727 | Train acc: 52.01% | Val loss: 0.9074 | Val acc: 55.44% | LR: 0.000633
Epoch: 078 | MCC: -0.007461 | Train loss: 1.5696 | Train acc: 52.03% | Val loss: 0.9160 | Val acc: 55.41% | LR: 0.000619
Epoch: 079 | MCC: -0.011873 | Train loss: 0.9748 | Train acc: 52.00% | Val loss: 0.9113 | Val acc: 55.22% | LR: 0.000605
Epoch: 080 | MCC: -0.000192 | Train loss: 0.9760 | Train acc: 52.05% | Val loss: 0.9329 | Val acc: 54.49% | LR: 0.000591
Epoch: 081 | MCC: -0.004685 | Train loss: 0.9715 | Train acc: 51.96% | Val loss: 0.9339 | Val acc: 54.62% | LR: 0.000577
Epoch: 082 | MCC: 0.000469 | Train loss: 0.9686 | Train acc: 52.07% | Val loss: 0.9049 | Val acc: 55.80% | LR: 0.000563
Epoch: 083 | MCC: -0.000406 | Train loss: 0.9706 | Train acc: 52.07% | Val loss: 0.9081 | Val acc: 55.85% | LR: 0.000549
Epoch: 084 | MCC: -0.000016 | Train loss: 0.9692 | Train acc: 51.93% | Val loss: 0.9224 | Val acc: 55.69% | LR: 0.000535
Epoch: 085 | MCC: 0.002044 | Train loss: 0.9743 | Train acc: 52.04% | Val loss: 0.9574 | Val acc: 55.96% | LR: 0.000521
Epoch: 086 | MCC: 0.000431 | Train loss: 0.9740 | Train acc: 52.19% | Val loss: 0.9000 | Val acc: 56.71% | LR: 0.000508
Epoch: 087 | MCC: 0.005294 | Train loss: 0.9696 | Train acc: 52.00% | Val loss: 0.9232 | Val acc: 56.30% | LR: 0.000494
Epoch: 088 | MCC: 0.009261 | Train loss: 0.9677 | Train acc: 52.19% | Val loss: 0.8941 | Val acc: 57.28% | LR: 0.000480
Epoch: 089 | MCC: -0.001040 | Train loss: 0.9681 | Train acc: 52.10% | Val loss: 0.8919 | Val acc: 56.97% | LR: 0.000467
Epoch: 090 | MCC: 0.007259 | Train loss: 0.9690 | Train acc: 52.23% | Val loss: 0.8868 | Val acc: 57.17% | LR: 0.000454
Epoch: 091 | MCC: -0.004234 | Train loss: 0.9664 | Train acc: 52.12% | Val loss: 0.8954 | Val acc: 56.57% | LR: 0.000440
Epoch: 092 | MCC: -0.002600 | Train loss: 0.9678 | Train acc: 52.10% | Val loss: 0.8967 | Val acc: 56.18% | LR: 0.000427
Epoch: 093 | MCC: -0.005639 | Train loss: 0.9680 | Train acc: 52.09% | Val loss: 0.9063 | Val acc: 56.08% | LR: 0.000414
Epoch: 094 | MCC: -0.007833 | Train loss: 0.9668 | Train acc: 52.21% | Val loss: 1.0015 | Val acc: 54.82% | LR: 0.000401
Epoch: 095 | MCC: 0.001193 | Train loss: 0.9647 | Train acc: 52.24% | Val loss: 0.9052 | Val acc: 55.63% | LR: 0.000388
Epoch: 096 | MCC: 0.003650 | Train loss: 0.9684 | Train acc: 52.19% | Val loss: 0.9105 | Val acc: 55.31% | LR: 0.000375
Epoch: 097 | MCC: 0.009864 | Train loss: 0.9647 | Train acc: 52.23% | Val loss: 0.8977 | Val acc: 56.47% | LR: 0.000363
Epoch: 098 | MCC: 0.000570 | Train loss: 0.9735 | Train acc: 51.68% | Val loss: 0.9045 | Val acc: 55.88% | LR: 0.000350
Epoch: 099 | MCC: -0.005241 | Train loss: 0.9977 | Train acc: 51.71% | Val loss: 0.9160 | Val acc: 55.34% | LR: 0.000338
Epoch: 100 | MCC: -0.006381 | Train loss: 0.9781 | Train acc: 52.07% | Val loss: 0.9243 | Val acc: 55.44% | LR: 0.000326
Epoch: 101 | MCC: -0.001959 | Train loss: 0.9683 | Train acc: 52.25% | Val loss: 0.9174 | Val acc: 55.44% | LR: 0.000314
Epoch: 102 | MCC: -0.005327 | Train loss: 0.9676 | Train acc: 52.21% | Val loss: 0.9138 | Val acc: 55.05% | LR: 0.000302
Epoch: 103 | MCC: -0.000128 | Train loss: 0.9717 | Train acc: 52.21% | Val loss: 0.9342 | Val acc: 54.47% | LR: 0.000290
Epoch: 104 | MCC: 0.001457 | Train loss: 0.9661 | Train acc: 52.22% | Val loss: 0.9046 | Val acc: 55.61% | LR: 0.000279
Epoch: 105 | MCC: 0.003033 | Train loss: 0.9666 | Train acc: 52.08% | Val loss: 0.9193 | Val acc: 55.20% | LR: 0.000268
Epoch: 106 | MCC: -0.001111 | Train loss: 0.9660 | Train acc: 52.14% | Val loss: 0.9183 | Val acc: 55.27% | LR: 0.000256
Epoch: 107 | MCC: 0.007688 | Train loss: 0.9771 | Train acc: 52.08% | Val loss: 0.9295 | Val acc: 54.69% | LR: 0.000245
Epoch: 108 | MCC: -0.001780 | Train loss: 0.9661 | Train acc: 52.14% | Val loss: 0.9380 | Val acc: 54.29% | LR: 0.000235

[I 2025-10-05 09:48:19,647] Trial 35 finished with value: -0.0037042200565338135 and parameters: {'lr': 0.0013495611304095393, 'hidden_size': 66, 'dropout': 0.04537495580383072, 'weight_decay': 0.003958380532544073}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.035162 | Train loss: 0.9935 | Train acc: 50.69% | Val loss: 0.9988 | Val acc: 50.14% | LR: 0.000200
Epoch: 001 | MCC: 0.034198 | Train loss: 0.9901 | Train acc: 50.83% | Val loss: 1.0055 | Val acc: 52.66% | LR: 0.000200
Epoch: 002 | MCC: 0.035036 | Train loss: 0.9875 | Train acc: 50.85% | Val loss: 0.9857 | Val acc: 53.75% | LR: 0.000200
Epoch: 003 | MCC: 0.037727 | Train loss: 0.9851 | Train acc: 50.87% | Val loss: 0.9795 | Val acc: 54.29% | LR: 0.000200
Epoch: 004 | MCC: 0.039876 | Train loss: 0.9855 | Train acc: 50.82% | Val loss: 0.9758 | Val acc: 54.44% | LR: 0.000200
Epoch: 005 | MCC: 0.034384 | Train loss: 0.9854 | Train acc: 50.85% | Val loss: 0.9724 | Val acc: 54.54% | LR: 0.000199
Epoch: 006 | MCC: 0.031143 | Train loss: 0.9842 | Train acc: 50.93% | Val loss: 0.9592 | Val acc: 54.62% | LR: 0.000199
Epoch: 007 | MCC: 0.035568 | Train loss: 0.9844 | Train acc: 50.93% | Val loss: 0.9540 | Val acc: 54.86% | LR: 0.000199
Epoch: 008 | MCC: 0.022396 | Train loss: 0.9829 | Train acc: 50.98% | Val loss: 0.9500 | Val acc: 54.71% | LR: 0.000198
Epoch: 009 | MCC: 0.023458 | Train loss: 0.9836 | Train acc: 50.90% | Val loss: 0.9614 | Val acc: 54.81% | LR: 0.000198
Epoch: 010 | MCC: 0.029711 | Train loss: 0.9827 | Train acc: 50.89% | Val loss: 0.9442 | Val acc: 55.30% | LR: 0.000197
Epoch: 011 | MCC: 0.032263 | Train loss: 0.9814 | Train acc: 50.97% | Val loss: 0.9370 | Val acc: 55.35% | LR: 0.000197
Epoch: 012 | MCC: 0.032328 | Train loss: 0.9803 | Train acc: 51.06% | Val loss: 0.9315 | Val acc: 55.42% | LR: 0.000196
Epoch: 013 | MCC: 0.023446 | Train loss: 0.9812 | Train acc: 50.97% | Val loss: 0.9268 | Val acc: 55.27% | LR: 0.000196
Epoch: 014 | MCC: 0.023136 | Train loss: 0.9817 | Train acc: 50.88% | Val loss: 0.9222 | Val acc: 55.28% | LR: 0.000195
Epoch: 015 | MCC: 0.018312 | Train loss: 0.9789 | Train acc: 51.07% | Val loss: 0.9188 | Val acc: 55.46% | LR: 0.000195
Epoch: 016 | MCC: 0.017921 | Train loss: 0.9927 | Train acc: 50.90% | Val loss: 0.9127 | Val acc: 55.49% | LR: 0.000194
Epoch: 017 | MCC: 0.022453 | Train loss: 0.9812 | Train acc: 50.91% | Val loss: 0.9087 | Val acc: 55.75% | LR: 0.000193
Epoch: 018 | MCC: 0.024693 | Train loss: 0.9797 | Train acc: 50.99% | Val loss: 0.9049 | Val acc: 56.00% | LR: 0.000192
Epoch: 019 | MCC: 0.024721 | Train loss: 0.9805 | Train acc: 50.91% | Val loss: 0.9035 | Val acc: 56.06% | LR: 0.000191
Epoch: 020 | MCC: 0.023328 | Train loss: 0.9794 | Train acc: 50.87% | Val loss: 0.8995 | Val acc: 55.99% | LR: 0.000191
Epoch: 021 | MCC: 0.026478 | Train loss: 0.9843 | Train acc: 51.01% | Val loss: 0.9029 | Val acc: 56.33% | LR: 0.000190
Epoch: 022 | MCC: 0.023217 | Train loss: 0.9797 | Train acc: 50.93% | Val loss: 0.8957 | Val acc: 56.32% | LR: 0.000189
Epoch: 023 | MCC: 0.024099 | Train loss: 0.9787 | Train acc: 50.95% | Val loss: 0.8950 | Val acc: 56.52% | LR: 0.000188
Epoch: 024 | MCC: 0.027697 | Train loss: 1.0017 | Train acc: 50.75% | Val loss: 0.8926 | Val acc: 56.60% | LR: 0.000187
Epoch: 025 | MCC: 0.027362 | Train loss: 0.9830 | Train acc: 51.12% | Val loss: 0.8892 | Val acc: 56.62% | LR: 0.000186
Epoch: 026 | MCC: 0.028867 | Train loss: 0.9820 | Train acc: 50.45% | Val loss: 0.8964 | Val acc: 56.82% | LR: 0.000185
Epoch: 027 | MCC: 0.021873 | Train loss: 0.9849 | Train acc: 50.78% | Val loss: 0.8857 | Val acc: 56.56% | LR: 0.000183
Epoch: 028 | MCC: 0.024038 | Train loss: 0.9830 | Train acc: 50.80% | Val loss: 0.8864 | Val acc: 56.59% | LR: 0.000182
Epoch: 029 | MCC: 0.030336 | Train loss: 0.9813 | Train acc: 50.98% | Val loss: 0.8847 | Val acc: 56.84% | LR: 0.000181
Epoch: 030 | MCC: 0.023365 | Train loss: 0.9793 | Train acc: 50.91% | Val loss: 0.8822 | Val acc: 56.89% | LR: 0.000180
Epoch: 031 | MCC: 0.029097 | Train loss: 0.9779 | Train acc: 50.94% | Val loss: 0.8762 | Val acc: 57.53% | LR: 0.000179
Epoch: 032 | MCC: 0.055844 | Train loss: 0.9770 | Train acc: 51.10% | Val loss: 0.8700 | Val acc: 58.59% | LR: 0.000177
Epoch: 033 | MCC: 0.045771 | Train loss: 0.9771 | Train acc: 50.93% | Val loss: 0.8646 | Val acc: 58.76% | LR: 0.000176
Epoch: 034 | MCC: 0.039475 | Train loss: 0.9817 | Train acc: 51.03% | Val loss: 0.8644 | Val acc: 58.78% | LR: 0.000175
Epoch: 035 | MCC: 0.036159 | Train loss: 0.9815 | Train acc: 51.06% | Val loss: 0.8624 | Val acc: 58.39% | LR: 0.000173
Epoch: 036 | MCC: 0.033815 | Train loss: 0.9783 | Train acc: 51.24% | Val loss: 0.8575 | Val acc: 58.44% | LR: 0.000172
Epoch: 037 | MCC: 0.043504 | Train loss: 0.9781 | Train acc: 51.10% | Val loss: 0.8570 | Val acc: 58.49% | LR: 0.000170
Epoch: 038 | MCC: 0.024182 | Train loss: 0.9771 | Train acc: 51.19% | Val loss: 0.8561 | Val acc: 58.10% | LR: 0.000169
Epoch: 039 | MCC: 0.030825 | Train loss: 0.9781 | Train acc: 51.14% | Val loss: 0.8609 | Val acc: 57.73% | LR: 0.000167
Epoch: 040 | MCC: 0.031577 | Train loss: 0.9769 | Train acc: 51.24% | Val loss: 0.8615 | Val acc: 57.97% | LR: 0.000166
Epoch: 041 | MCC: 0.022533 | Train loss: 0.9769 | Train acc: 51.18% | Val loss: 0.8594 | Val acc: 57.95% | LR: 0.000164
Epoch: 042 | MCC: 0.035322 | Train loss: 0.9777 | Train acc: 51.12% | Val loss: 0.8705 | Val acc: 58.37% | LR: 0.000162
Epoch: 043 | MCC: 0.039134 | Train loss: 0.9762 | Train acc: 51.12% | Val loss: 0.8627 | Val acc: 58.91% | LR: 0.000161
Epoch: 044 | MCC: 0.036097 | Train loss: 0.9751 | Train acc: 51.31% | Val loss: 0.8474 | Val acc: 59.57% | LR: 0.000159
Epoch: 045 | MCC: 0.038880 | Train loss: 0.9735 | Train acc: 51.30% | Val loss: 0.8477 | Val acc: 59.23% | LR: 0.000157
Epoch: 046 | MCC: 0.033720 | Train loss: 0.9744 | Train acc: 51.19% | Val loss: 0.8408 | Val acc: 59.37% | LR: 0.000156
Epoch: 047 | MCC: 0.039778 | Train loss: 0.9736 | Train acc: 51.31% | Val loss: 0.8396 | Val acc: 59.67% | LR: 0.000154
Epoch: 048 | MCC: 0.038991 | Train loss: 0.9719 | Train acc: 51.29% | Val loss: 0.8401 | Val acc: 59.15% | LR: 0.000152
Epoch: 049 | MCC: 0.036290 | Train loss: 0.9709 | Train acc: 51.38% | Val loss: 0.8335 | Val acc: 59.62% | LR: 0.000150
Epoch: 050 | MCC: 0.027608 | Train loss: 0.9719 | Train acc: 51.30% | Val loss: 0.8274 | Val acc: 60.12% | LR: 0.000148
Epoch: 051 | MCC: 0.023469 | Train loss: 1.0710 | Train acc: 51.31% | Val loss: 0.8357 | Val acc: 58.89% | LR: 0.000147
Epoch: 052 | MCC: 0.018894 | Train loss: 0.9779 | Train acc: 51.19% | Val loss: 0.9569 | Val acc: 57.80% | LR: 0.000145
Epoch: 053 | MCC: 0.039422 | Train loss: 0.9750 | Train acc: 51.63% | Val loss: 0.8450 | Val acc: 60.17% | LR: 0.000143
Epoch: 054 | MCC: 0.023597 | Train loss: 0.9732 | Train acc: 51.43% | Val loss: 0.8196 | Val acc: 59.70% | LR: 0.000141
Epoch: 055 | MCC: 0.034512 | Train loss: 0.9706 | Train acc: 51.48% | Val loss: 0.8155 | Val acc: 60.53% | LR: 0.000139
Epoch: 056 | MCC: 0.036388 | Train loss: 0.9716 | Train acc: 51.51% | Val loss: 0.8182 | Val acc: 59.89% | LR: 0.000137
Epoch: 057 | MCC: 0.048796 | Train loss: 0.9703 | Train acc: 51.32% | Val loss: 0.8136 | Val acc: 60.07% | LR: 0.000135
Epoch: 058 | MCC: 0.049654 | Train loss: 0.9715 | Train acc: 51.44% | Val loss: 0.8143 | Val acc: 60.05% | LR: 0.000133
Epoch: 059 | MCC: 0.026696 | Train loss: 0.9685 | Train acc: 51.59% | Val loss: 0.9431 | Val acc: 59.05% | LR: 0.000131
Epoch: 060 | MCC: 0.054692 | Train loss: 0.9687 | Train acc: 51.52% | Val loss: 0.8095 | Val acc: 60.24% | LR: 0.000129
Epoch: 061 | MCC: 0.052116 | Train loss: 0.9685 | Train acc: 51.49% | Val loss: 0.8127 | Val acc: 59.87% | LR: 0.000127
Epoch: 062 | MCC: 0.053218 | Train loss: 0.9673 | Train acc: 51.64% | Val loss: 0.8096 | Val acc: 60.13% | LR: 0.000125
Epoch: 063 | MCC: 0.035808 | Train loss: 0.9674 | Train acc: 51.59% | Val loss: 0.8162 | Val acc: 59.53% | LR: 0.000123
Epoch: 064 | MCC: 0.028536 | Train loss: 0.9694 | Train acc: 51.45% | Val loss: 0.8175 | Val acc: 59.54% | LR: 0.000121
Epoch: 065 | MCC: 0.041095 | Train loss: 0.9708 | Train acc: 51.73% | Val loss: 0.8146 | Val acc: 59.72% | LR: 0.000119
Epoch: 066 | MCC: 0.029389 | Train loss: 0.9701 | Train acc: 51.45% | Val loss: 0.8146 | Val acc: 59.60% | LR: 0.000117
Epoch: 067 | MCC: 0.005565 | Train loss: 0.9688 | Train acc: 51.48% | Val loss: 0.8412 | Val acc: 58.34% | LR: 0.000115
Epoch: 068 | MCC: 0.023887 | Train loss: 0.9701 | Train acc: 51.34% | Val loss: 0.8230 | Val acc: 59.10% | LR: 0.000113
Epoch: 069 | MCC: 0.053848 | Train loss: 0.9666 | Train acc: 51.67% | Val loss: 0.8169 | Val acc: 59.68% | LR: 0.000111
Epoch: 070 | MCC: 0.049511 | Train loss: 0.9654 | Train acc: 51.68% | Val loss: 0.8070 | Val acc: 60.08% | LR: 0.000109
Epoch: 071 | MCC: 0.033573 | Train loss: 0.9664 | Train acc: 51.58% | Val loss: 0.8096 | Val acc: 59.74% | LR: 0.000107
Epoch: 072 | MCC: 0.051283 | Train loss: 0.9805 | Train acc: 51.67% | Val loss: 0.7990 | Val acc: 60.49% | LR: 0.000105
Epoch: 073 | MCC: 0.042860 | Train loss: 0.9765 | Train acc: 51.82% | Val loss: 0.8022 | Val acc: 60.20% | LR: 0.000103
Epoch: 074 | MCC: 0.048380 | Train loss: 0.9667 | Train acc: 51.51% | Val loss: 0.8014 | Val acc: 60.32% | LR: 0.000101
Epoch: 075 | MCC: 0.028740 | Train loss: 0.9642 | Train acc: 51.76% | Val loss: 0.8069 | Val acc: 59.72% | LR: 0.000098
Epoch: 076 | MCC: 0.038964 | Train loss: 0.9672 | Train acc: 51.44% | Val loss: 0.8074 | Val acc: 60.05% | LR: 0.000096
Epoch: 077 | MCC: 0.054092 | Train loss: 0.9650 | Train acc: 51.64% | Val loss: 0.8002 | Val acc: 60.52% | LR: 0.000094
Epoch: 078 | MCC: 0.039688 | Train loss: 0.9650 | Train acc: 51.65% | Val loss: 0.8076 | Val acc: 59.97% | LR: 0.000092
Epoch: 079 | MCC: 0.051872 | Train loss: 0.9652 | Train acc: 51.53% | Val loss: 0.8013 | Val acc: 60.42% | LR: 0.000090
Epoch: 080 | MCC: 0.034240 | Train loss: 0.9640 | Train acc: 52.09% | Val loss: 0.8087 | Val acc: 59.90% | LR: 0.000088
Epoch: 081 | MCC: 0.042384 | Train loss: 0.9641 | Train acc: 51.59% | Val loss: 0.8018 | Val acc: 60.12% | LR: 0.000086
Epoch: 082 | MCC: 0.030257 | Train loss: 0.9637 | Train acc: 51.63% | Val loss: 0.8067 | Val acc: 59.81% | LR: 0.000084
Epoch: 083 | MCC: 0.047717 | Train loss: 0.9649 | Train acc: 51.46% | Val loss: 0.8021 | Val acc: 60.22% | LR: 0.000082
Epoch: 084 | MCC: 0.034665 | Train loss: 0.9634 | Train acc: 52.09% | Val loss: 0.8074 | Val acc: 59.85% | LR: 0.000080
Epoch: 085 | MCC: 0.056990 | Train loss: 0.9635 | Train acc: 51.94% | Val loss: 0.8116 | Val acc: 60.25% | LR: 0.000078
Epoch: 086 | MCC: 0.045069 | Train loss: 0.9638 | Train acc: 52.34% | Val loss: 0.8065 | Val acc: 59.97% | LR: 0.000076
Epoch: 087 | MCC: 0.049889 | Train loss: 0.9617 | Train acc: 52.27% | Val loss: 0.8049 | Val acc: 60.20% | LR: 0.000074
Epoch: 088 | MCC: 0.042616 | Train loss: 0.9626 | Train acc: 52.23% | Val loss: 0.8050 | Val acc: 60.00% | LR: 0.000072
Epoch: 089 | MCC: 0.048684 | Train loss: 0.9645 | Train acc: 52.45% | Val loss: 0.8086 | Val acc: 59.98% | LR: 0.000070
Epoch: 090 | MCC: 0.049886 | Train loss: 0.9630 | Train acc: 52.26% | Val loss: 0.8081 | Val acc: 60.09% | LR: 0.000068
Epoch: 091 | MCC: 0.049520 | Train loss: 0.9659 | Train acc: 52.32% | Val loss: 0.8062 | Val acc: 60.15% | LR: 0.000066
Epoch: 092 | MCC: 0.045920 | Train loss: 0.9705 | Train acc: 52.05% | Val loss: 0.8062 | Val acc: 60.12% | LR: 0.000064
Epoch: 093 | MCC: 0.052630 | Train loss: 0.9705 | Train acc: 52.11% | Val loss: 0.8059 | Val acc: 60.24% | LR: 0.000062
Epoch: 094 | MCC: 0.046180 | Train loss: 0.9707 | Train acc: 51.78% | Val loss: 0.8075 | Val acc: 60.05% | LR: 0.000060
Epoch: 095 | MCC: 0.043647 | Train loss: 0.9703 | Train acc: 51.74% | Val loss: 0.8063 | Val acc: 60.06% | LR: 0.000058
Epoch: 096 | MCC: 0.050488 | Train loss: 0.9695 | Train acc: 51.68% | Val loss: 0.8099 | Val acc: 60.09% | LR: 0.000056
Epoch: 097 | MCC: 0.038083 | Train loss: 0.9689 | Train acc: 51.69% | Val loss: 0.8073 | Val acc: 60.02% | LR: 0.000054
Epoch: 098 | MCC: 0.044751 | Train loss: 0.9674 | Train acc: 51.77% | Val loss: 0.8067 | Val acc: 59.95% | LR: 0.000053
Epoch: 099 | MCC: 0.046164 | Train loss: 0.9660 | Train acc: 51.77% | Val loss: 0.8072 | Val acc: 59.97% | LR: 0.000051
Epoch: 100 | MCC: 0.039681 | Train loss: 0.9653 | Train acc: 51.74% | Val loss: 0.8085 | Val acc: 60.07% | LR: 0.000049
Epoch: 101 | MCC: 0.049156 | Train loss: 0.9646 | Train acc: 51.78% | Val loss: 0.8063 | Val acc: 60.12% | LR: 0.000047
Epoch: 102 | MCC: 0.050767 | Train loss: 0.9643 | Train acc: 51.77% | Val loss: 0.8072 | Val acc: 60.11% | LR: 0.000045
Epoch: 103 | MCC: 0.050160 | Train loss: 0.9663 | Train acc: 51.72% | Val loss: 0.8083 | Val acc: 60.14% | LR: 0.000044
Epoch: 104 | MCC: 0.044035 | Train loss: 0.9650 | Train acc: 51.85% | Val loss: 0.8065 | Val acc: 59.97% | LR: 0.000042
Epoch: 105 | MCC: 0.038777 | Train loss: 0.9671 | Train acc: 51.72% | Val loss: 0.8098 | Val acc: 59.88% | LR: 0.000040
Epoch: 106 | MCC: 0.050195 | Train loss: 0.9811 | Train acc: 51.77% | Val loss: 0.8089 | Val acc: 60.05% | LR: 0.000039
Epoch: 107 | MCC: 0.046578 | Train loss: 1.0060 | Train acc: 51.78% | Val loss: 0.8073 | Val acc: 60.05% | LR: 0.000037
Epoch: 108 | MCC: 0.047213 | Train loss: 0.9731 | Train acc: 51.66% | Val loss: 0.8084 | Val acc: 59.95% | LR: 0.000035
Epoch: 109 | MCC: 0.049740 | Train loss: 1.0038 | Train acc: 51.94% | Val loss: 0.8081 | Val acc: 60.09% | LR: 0.000034
Epoch: 110 | MCC: 0.048966 | Train loss: 0.9992 | Train acc: 51.99% | Val loss: 0.8081 | Val acc: 60.05% | LR: 0.000032
Epoch: 111 | MCC: 0.048512 | Train loss: 0.9965 | Train acc: 51.84% | Val loss: 0.8082 | Val acc: 60.02% | LR: 0.000031
Epoch: 112 | MCC: 0.048512 | Train loss: 1.0285 | Train acc: 51.96% | Val loss: 0.8083 | Val acc: 60.02% | LR: 0.000029
Epoch: 113 | MCC: 0.048512 | Train loss: 0.9879 | Train acc: 51.77% | Val loss: 0.8084 | Val acc: 60.02% | LR: 0.000028
Epoch: 114 | MCC: 0.048940 | Train loss: 0.9898 | Train acc: 51.84% | Val loss: 0.8081 | Val acc: 60.02% | LR: 0.000027
Epoch: 115 | MCC: 0.045544 | Train loss: 0.9799 | Train acc: 51.72% | Val loss: 0.8071 | Val acc: 59.97% | LR: 0.000025
Epoch: 116 | MCC: 0.047526 | Train loss: 0.9713 | Train acc: 51.76% | Val loss: 0.8072 | Val acc: 60.07% | LR: 0.000024
Epoch: 117 | MCC: 0.046568 | Train loss: 0.9679 | Train acc: 51.81% | Val loss: 0.8065 | Val acc: 60.07% | LR: 0.000023
Epoch: 118 | MCC: 0.050027 | Train loss: 0.9675 | Train acc: 51.83% | Val loss: 0.8065 | Val acc: 60.14% | LR: 0.000021
Epoch: 119 | MCC: 0.045960 | Train loss: 0.9717 | Train acc: 51.65% | Val loss: 0.8079 | Val acc: 59.88% | LR: 0.000020
Epoch: 120 | MCC: 0.045233 | Train loss: 0.9685 | Train acc: 51.64% | Val loss: 0.8068 | Val acc: 59.90% | LR: 0.000019
Epoch: 121 | MCC: 0.043477 | Train loss: 0.9820 | Train acc: 51.80% | Val loss: 0.8050 | Val acc: 59.92% | LR: 0.000018
Epoch: 122 | MCC: 0.043362 | Train loss: 0.9697 | Train acc: 51.82% | Val loss: 0.8060 | Val acc: 59.90% | LR: 0.000016
Epoch: 123 | MCC: 0.044485 | Train loss: 0.9747 | Train acc: 51.75% | Val loss: 0.8071 | Val acc: 59.92% | LR: 0.000015
Epoch: 124 | MCC: 0.045782 | Train loss: 0.9674 | Train acc: 51.72% | Val loss: 0.8081 | Val acc: 59.90% | LR: 0.000014
Epoch: 125 | MCC: 0.044917 | Train loss: 0.9672 | Train acc: 51.71% | Val loss: 0.8072 | Val acc: 59.88% | LR: 0.000013
Epoch: 126 | MCC: 0.043466 | Train loss: 0.9683 | Train acc: 51.79% | Val loss: 0.8065 | Val acc: 59.85% | LR: 0.000012
Epoch: 127 | MCC: 0.044231 | Train loss: 0.9689 | Train acc: 51.76% | Val loss: 0.8061 | Val acc: 59.95% | LR: 0.000011
Epoch: 128 | MCC: 0.045088 | Train loss: 0.9696 | Train acc: 51.88% | Val loss: 0.8066 | Val acc: 59.97% | LR: 0.000010
Epoch: 129 | MCC: 0.043756 | Train loss: 0.9655 | Train acc: 51.82% | Val loss: 0.8069 | Val acc: 59.85% | LR: 0.000010
Epoch: 130 | MCC: 0.043439 | Train loss: 0.9667 | Train acc: 51.75% | Val loss: 0.8072 | Val acc: 59.83% | LR: 0.000009
Epoch: 131 | MCC: 0.043439 | Train loss: 0.9678 | Train acc: 51.78% | Val loss: 0.8073 | Val acc: 59.83% | LR: 0.000008
Epoch: 132 | MCC: 0.042846 | Train loss: 0.9679 | Train acc: 51.78% | Val loss: 0.8073 | Val acc: 59.80% | LR: 0.000007
Epoch: 133 | MCC: 0.043232 | Train loss: 0.9663 | Train acc: 51.86% | Val loss: 0.8070 | Val acc: 59.83% | LR: 0.000007
Epoch: 134 | MCC: 0.042846 | Train loss: 0.9664 | Train acc: 51.78% | Val loss: 0.8072 | Val acc: 59.80% | LR: 0.000006
Epoch: 135 | MCC: 0.043756 | Train loss: 0.9667 | Train acc: 51.73% | Val loss: 0.8071 | Val acc: 59.85% | LR: 0.000005
Epoch: 136 | MCC: 0.042980 | Train loss: 0.9671 | Train acc: 51.78% | Val loss: 0.8074 | Val acc: 59.80% | LR: 0.000005
Epoch: 137 | MCC: 0.042529 | Train loss: 0.9653 | Train acc: 51.79% | Val loss: 0.8074 | Val acc: 59.78% | LR: 0.000004
Epoch: 138 | MCC: 0.042846 | Train loss: 0.9660 | Train acc: 51.87% | Val loss: 0.8072 | Val acc: 59.80% | LR: 0.000004
Epoch: 139 | MCC: 0.043439 | Train loss: 0.9663 | Train acc: 51.77% | Val loss: 0.8071 | Val acc: 59.83% | LR: 0.000003
Epoch: 140 | MCC: 0.042980 | Train loss: 0.9680 | Train acc: 51.63% | Val loss: 0.8072 | Val acc: 59.80% | LR: 0.000003
Epoch: 141 | MCC: 0.042846 | Train loss: 0.9655 | Train acc: 51.82% | Val loss: 0.8071 | Val acc: 59.80% | LR: 0.000002
Epoch: 142 | MCC: 0.044329 | Train loss: 0.9676 | Train acc: 51.70% | Val loss: 0.8070 | Val acc: 59.92% | LR: 0.000002
Epoch: 143 | MCC: 0.044329 | Train loss: 0.9660 | Train acc: 51.76% | Val loss: 0.8070 | Val acc: 59.92% | LR: 0.000002
Epoch: 144 | MCC: 0.043469 | Train loss: 0.9656 | Train acc: 51.94% | Val loss: 0.8070 | Val acc: 59.85% | LR: 0.000002
Epoch: 145 | MCC: 0.044601 | Train loss: 0.9669 | Train acc: 51.78% | Val loss: 0.8070 | Val acc: 59.90% | LR: 0.000001
Epoch: 146 | MCC: 0.044601 | Train loss: 0.9663 | Train acc: 51.78% | Val loss: 0.8069 | Val acc: 59.90% | LR: 0.000001

[I 2025-10-05 09:50:35,520] Trial 36 finished with value: 0.044601278263144195 and parameters: {'lr': 0.0002000821110151758, 'hidden_size': 86, 'dropout': 0.09314076007183697, 'weight_decay': 0.022052099970823982}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.009872 | Train loss: 0.9988 | Train acc: 50.23% | Val loss: 0.9932 | Val acc: 54.83% | LR: 0.000136
Epoch: 001 | MCC: -0.022102 | Train loss: 1.0006 | Train acc: 50.13% | Val loss: 0.9947 | Val acc: 54.50% | LR: 0.000136
Epoch: 002 | MCC: -0.022218 | Train loss: 0.9990 | Train acc: 50.14% | Val loss: 0.9957 | Val acc: 54.63% | LR: 0.000136
Epoch: 003 | MCC: -0.013569 | Train loss: 0.9992 | Train acc: 50.23% | Val loss: 0.9966 | Val acc: 54.88% | LR: 0.000136
Epoch: 004 | MCC: -0.015907 | Train loss: 0.9975 | Train acc: 50.11% | Val loss: 0.9945 | Val acc: 54.57% | LR: 0.000136
Epoch: 005 | MCC: 0.014087 | Train loss: 0.9970 | Train acc: 50.23% | Val loss: 0.9951 | Val acc: 54.98% | LR: 0.000136
Epoch: 006 | MCC: -0.010790 | Train loss: 0.9960 | Train acc: 50.28% | Val loss: 0.9930 | Val acc: 54.63% | LR: 0.000136
Epoch: 007 | MCC: 0.024625 | Train loss: 0.9943 | Train acc: 50.18% | Val loss: 0.9943 | Val acc: 54.93% | LR: 0.000135
Epoch: 008 | MCC: 0.028237 | Train loss: 0.9956 | Train acc: 50.23% | Val loss: 0.9973 | Val acc: 55.34% | LR: 0.000135
Epoch: 009 | MCC: 0.022861 | Train loss: 0.9922 | Train acc: 50.36% | Val loss: 0.9970 | Val acc: 55.24% | LR: 0.000135
Epoch: 010 | MCC: 0.002933 | Train loss: 0.9946 | Train acc: 50.20% | Val loss: 0.9974 | Val acc: 55.12% | LR: 0.000135
Epoch: 011 | MCC: -0.011201 | Train loss: 0.9939 | Train acc: 50.27% | Val loss: 0.9930 | Val acc: 54.59% | LR: 0.000134
Epoch: 012 | MCC: 0.003131 | Train loss: 0.9941 | Train acc: 50.36% | Val loss: 0.9960 | Val acc: 54.92% | LR: 0.000134
Epoch: 013 | MCC: 0.009812 | Train loss: 1.0029 | Train acc: 50.43% | Val loss: 0.9922 | Val acc: 55.02% | LR: 0.000134
Epoch: 014 | MCC: 0.017023 | Train loss: 0.9925 | Train acc: 50.67% | Val loss: 0.9918 | Val acc: 55.43% | LR: 0.000133
Epoch: 015 | MCC: 0.017587 | Train loss: 1.0086 | Train acc: 50.67% | Val loss: 0.9922 | Val acc: 54.64% | LR: 0.000133
Epoch: 016 | MCC: 0.000188 | Train loss: 0.9921 | Train acc: 50.65% | Val loss: 0.9913 | Val acc: 54.89% | LR: 0.000132
Epoch: 017 | MCC: -0.001554 | Train loss: 0.9921 | Train acc: 50.49% | Val loss: 0.9960 | Val acc: 54.70% | LR: 0.000132
Epoch: 018 | MCC: -0.002119 | Train loss: 0.9911 | Train acc: 50.87% | Val loss: 0.9934 | Val acc: 54.59% | LR: 0.000131
Epoch: 019 | MCC: -0.001614 | Train loss: 0.9968 | Train acc: 50.90% | Val loss: 0.9917 | Val acc: 53.75% | LR: 0.000131
Epoch: 020 | MCC: -0.009286 | Train loss: 0.9945 | Train acc: 50.80% | Val loss: 0.9936 | Val acc: 54.23% | LR: 0.000130
Epoch: 021 | MCC: -0.006532 | Train loss: 0.9929 | Train acc: 50.60% | Val loss: 0.9925 | Val acc: 53.99% | LR: 0.000129
Epoch: 022 | MCC: -0.011459 | Train loss: 0.9909 | Train acc: 50.85% | Val loss: 0.9991 | Val acc: 53.88% | LR: 0.000129
Epoch: 023 | MCC: 0.012718 | Train loss: 0.9928 | Train acc: 50.74% | Val loss: 0.9912 | Val acc: 54.31% | LR: 0.000128
Epoch: 024 | MCC: 0.024608 | Train loss: 0.9909 | Train acc: 50.72% | Val loss: 0.9903 | Val acc: 54.70% | LR: 0.000127
Epoch: 025 | MCC: 0.016183 | Train loss: 0.9905 | Train acc: 50.85% | Val loss: 1.0319 | Val acc: 54.54% | LR: 0.000127
Epoch: 026 | MCC: 0.003359 | Train loss: 0.9914 | Train acc: 50.74% | Val loss: 0.9906 | Val acc: 54.01% | LR: 0.000126
Epoch: 027 | MCC: 0.010096 | Train loss: 0.9907 | Train acc: 50.75% | Val loss: 0.9904 | Val acc: 54.23% | LR: 0.000125
Epoch: 028 | MCC: 0.021589 | Train loss: 0.9902 | Train acc: 50.91% | Val loss: 0.9904 | Val acc: 54.34% | LR: 0.000124
Epoch: 029 | MCC: 0.018203 | Train loss: 0.9922 | Train acc: 50.90% | Val loss: 0.9896 | Val acc: 54.23% | LR: 0.000123
Epoch: 030 | MCC: 0.024951 | Train loss: 0.9899 | Train acc: 50.83% | Val loss: 0.9937 | Val acc: 54.44% | LR: 0.000123
Epoch: 031 | MCC: 0.012053 | Train loss: 0.9905 | Train acc: 50.84% | Val loss: 0.9903 | Val acc: 54.11% | LR: 0.000122
Epoch: 032 | MCC: 0.016868 | Train loss: 0.9897 | Train acc: 50.94% | Val loss: 0.9901 | Val acc: 54.17% | LR: 0.000121
Epoch: 033 | MCC: 0.019890 | Train loss: 0.9888 | Train acc: 51.05% | Val loss: 0.9900 | Val acc: 54.27% | LR: 0.000120
Epoch: 034 | MCC: 0.014792 | Train loss: 0.9916 | Train acc: 50.68% | Val loss: 0.9897 | Val acc: 53.96% | LR: 0.000119
Epoch: 035 | MCC: 0.016053 | Train loss: 0.9895 | Train acc: 50.84% | Val loss: 0.9898 | Val acc: 53.99% | LR: 0.000118
Epoch: 036 | MCC: 0.016126 | Train loss: 0.9896 | Train acc: 51.03% | Val loss: 0.9894 | Val acc: 54.04% | LR: 0.000117
Epoch: 037 | MCC: 0.011675 | Train loss: 0.9905 | Train acc: 50.77% | Val loss: 0.9893 | Val acc: 53.80% | LR: 0.000116
Epoch: 038 | MCC: 0.013988 | Train loss: 0.9921 | Train acc: 50.73% | Val loss: 0.9890 | Val acc: 53.91% | LR: 0.000115
Epoch: 039 | MCC: 0.013292 | Train loss: 0.9887 | Train acc: 50.97% | Val loss: 0.9885 | Val acc: 53.83% | LR: 0.000114
Epoch: 040 | MCC: 0.010568 | Train loss: 0.9910 | Train acc: 50.70% | Val loss: 0.9883 | Val acc: 53.70% | LR: 0.000113
Epoch: 041 | MCC: 0.011504 | Train loss: 0.9900 | Train acc: 50.77% | Val loss: 0.9879 | Val acc: 53.80% | LR: 0.000112
Epoch: 042 | MCC: 0.010166 | Train loss: 0.9893 | Train acc: 50.82% | Val loss: 0.9878 | Val acc: 53.85% | LR: 0.000111
Epoch: 043 | MCC: 0.015524 | Train loss: 0.9901 | Train acc: 50.80% | Val loss: 0.9875 | Val acc: 53.88% | LR: 0.000110
Epoch: 044 | MCC: 0.017806 | Train loss: 0.9903 | Train acc: 50.79% | Val loss: 0.9871 | Val acc: 53.87% | LR: 0.000109
Epoch: 045 | MCC: 0.017148 | Train loss: 0.9885 | Train acc: 51.01% | Val loss: 0.9868 | Val acc: 53.97% | LR: 0.000107
Epoch: 046 | MCC: 0.015280 | Train loss: 0.9881 | Train acc: 50.85% | Val loss: 0.9862 | Val acc: 53.92% | LR: 0.000106
Epoch: 047 | MCC: 0.016763 | Train loss: 0.9888 | Train acc: 50.90% | Val loss: 0.9859 | Val acc: 53.99% | LR: 0.000105
Epoch: 048 | MCC: 0.015866 | Train loss: 0.9893 | Train acc: 50.89% | Val loss: 0.9854 | Val acc: 53.97% | LR: 0.000104
Epoch: 049 | MCC: 0.016688 | Train loss: 0.9889 | Train acc: 50.88% | Val loss: 0.9846 | Val acc: 54.02% | LR: 0.000103
Epoch: 050 | MCC: 0.016496 | Train loss: 0.9895 | Train acc: 50.81% | Val loss: 0.9842 | Val acc: 54.04% | LR: 0.000101
Epoch: 051 | MCC: 0.018954 | Train loss: 0.9887 | Train acc: 50.85% | Val loss: 0.9836 | Val acc: 54.19% | LR: 0.000100
Epoch: 052 | MCC: 0.020452 | Train loss: 0.9870 | Train acc: 50.89% | Val loss: 0.9825 | Val acc: 54.21% | LR: 0.000099
Epoch: 053 | MCC: 0.017330 | Train loss: 0.9885 | Train acc: 50.78% | Val loss: 0.9819 | Val acc: 54.08% | LR: 0.000098
Epoch: 054 | MCC: 0.019535 | Train loss: 0.9877 | Train acc: 50.82% | Val loss: 0.9811 | Val acc: 54.15% | LR: 0.000096
Epoch: 055 | MCC: 0.018910 | Train loss: 0.9888 | Train acc: 50.74% | Val loss: 0.9803 | Val acc: 54.13% | LR: 0.000095
Epoch: 056 | MCC: 0.020075 | Train loss: 0.9874 | Train acc: 50.80% | Val loss: 0.9795 | Val acc: 54.29% | LR: 0.000094
Epoch: 057 | MCC: 0.023739 | Train loss: 0.9883 | Train acc: 50.80% | Val loss: 0.9789 | Val acc: 54.43% | LR: 0.000092
Epoch: 058 | MCC: 0.025859 | Train loss: 0.9852 | Train acc: 51.01% | Val loss: 0.9780 | Val acc: 54.65% | LR: 0.000091
Epoch: 059 | MCC: 0.027276 | Train loss: 0.9865 | Train acc: 50.83% | Val loss: 0.9768 | Val acc: 54.72% | LR: 0.000090
Epoch: 060 | MCC: 0.028430 | Train loss: 0.9860 | Train acc: 50.83% | Val loss: 0.9759 | Val acc: 54.77% | LR: 0.000088
Epoch: 061 | MCC: 0.024519 | Train loss: 0.9864 | Train acc: 50.80% | Val loss: 0.9748 | Val acc: 54.57% | LR: 0.000087
Epoch: 062 | MCC: 0.027726 | Train loss: 0.9835 | Train acc: 51.03% | Val loss: 0.9743 | Val acc: 54.74% | LR: 0.000086
Epoch: 063 | MCC: 0.027680 | Train loss: 0.9847 | Train acc: 50.85% | Val loss: 0.9732 | Val acc: 54.78% | LR: 0.000084
Epoch: 064 | MCC: 0.028108 | Train loss: 0.9861 | Train acc: 50.81% | Val loss: 0.9724 | Val acc: 54.83% | LR: 0.000083
Epoch: 065 | MCC: 0.028205 | Train loss: 0.9843 | Train acc: 50.95% | Val loss: 0.9719 | Val acc: 54.83% | LR: 0.000081
Epoch: 066 | MCC: 0.030864 | Train loss: 0.9844 | Train acc: 50.99% | Val loss: 0.9712 | Val acc: 55.01% | LR: 0.000080
Epoch: 067 | MCC: 0.029334 | Train loss: 0.9845 | Train acc: 50.90% | Val loss: 0.9700 | Val acc: 54.91% | LR: 0.000079
Epoch: 068 | MCC: 0.029913 | Train loss: 0.9843 | Train acc: 50.83% | Val loss: 0.9690 | Val acc: 54.94% | LR: 0.000077
Epoch: 069 | MCC: 0.030427 | Train loss: 0.9857 | Train acc: 50.80% | Val loss: 0.9682 | Val acc: 54.96% | LR: 0.000076
Epoch: 070 | MCC: 0.031372 | Train loss: 0.9850 | Train acc: 50.88% | Val loss: 0.9673 | Val acc: 54.98% | LR: 0.000074
Epoch: 071 | MCC: 0.028581 | Train loss: 0.9853 | Train acc: 50.86% | Val loss: 0.9658 | Val acc: 54.87% | LR: 0.000073
Epoch: 072 | MCC: 0.024607 | Train loss: 0.9851 | Train acc: 50.85% | Val loss: 0.9645 | Val acc: 54.79% | LR: 0.000072
Epoch: 073 | MCC: 0.024614 | Train loss: 0.9840 | Train acc: 50.89% | Val loss: 0.9635 | Val acc: 54.77% | LR: 0.000070
Epoch: 074 | MCC: 0.024808 | Train loss: 0.9834 | Train acc: 50.96% | Val loss: 0.9625 | Val acc: 54.77% | LR: 0.000069
Epoch: 075 | MCC: 0.026655 | Train loss: 0.9848 | Train acc: 50.84% | Val loss: 0.9610 | Val acc: 54.77% | LR: 0.000067
Epoch: 076 | MCC: 0.024278 | Train loss: 0.9835 | Train acc: 50.99% | Val loss: 0.9603 | Val acc: 54.69% | LR: 0.000066
Epoch: 077 | MCC: 0.023989 | Train loss: 0.9832 | Train acc: 50.91% | Val loss: 0.9591 | Val acc: 54.64% | LR: 0.000064
Epoch: 078 | MCC: 0.024407 | Train loss: 0.9835 | Train acc: 50.94% | Val loss: 0.9582 | Val acc: 54.64% | LR: 0.000063
Epoch: 079 | MCC: 0.024022 | Train loss: 0.9842 | Train acc: 50.89% | Val loss: 0.9571 | Val acc: 54.62% | LR: 0.000062
Epoch: 080 | MCC: 0.023353 | Train loss: 0.9853 | Train acc: 50.86% | Val loss: 0.9560 | Val acc: 54.75% | LR: 0.000060
Epoch: 081 | MCC: 0.024585 | Train loss: 0.9845 | Train acc: 50.81% | Val loss: 0.9550 | Val acc: 54.93% | LR: 0.000059
Epoch: 082 | MCC: 0.026961 | Train loss: 0.9830 | Train acc: 50.91% | Val loss: 0.9543 | Val acc: 55.03% | LR: 0.000057
Epoch: 083 | MCC: 0.030520 | Train loss: 0.9827 | Train acc: 50.98% | Val loss: 0.9533 | Val acc: 55.12% | LR: 0.000056
Epoch: 084 | MCC: 0.031035 | Train loss: 0.9826 | Train acc: 50.88% | Val loss: 0.9525 | Val acc: 55.13% | LR: 0.000055
Epoch: 085 | MCC: 0.031371 | Train loss: 0.9839 | Train acc: 50.87% | Val loss: 0.9514 | Val acc: 55.17% | LR: 0.000053
Epoch: 086 | MCC: 0.032882 | Train loss: 0.9838 | Train acc: 50.89% | Val loss: 0.9505 | Val acc: 55.32% | LR: 0.000052
Epoch: 087 | MCC: 0.034169 | Train loss: 0.9841 | Train acc: 50.82% | Val loss: 0.9500 | Val acc: 55.40% | LR: 0.000051
Epoch: 088 | MCC: 0.033954 | Train loss: 0.9844 | Train acc: 50.86% | Val loss: 0.9491 | Val acc: 55.41% | LR: 0.000049
Epoch: 089 | MCC: 0.033954 | Train loss: 0.9839 | Train acc: 50.83% | Val loss: 0.9483 | Val acc: 55.41% | LR: 0.000048
Epoch: 090 | MCC: 0.033065 | Train loss: 0.9838 | Train acc: 50.85% | Val loss: 0.9477 | Val acc: 55.42% | LR: 0.000046
Epoch: 091 | MCC: 0.029302 | Train loss: 0.9841 | Train acc: 50.87% | Val loss: 0.9471 | Val acc: 55.39% | LR: 0.000045
Epoch: 092 | MCC: 0.029271 | Train loss: 0.9843 | Train acc: 50.84% | Val loss: 0.9465 | Val acc: 55.32% | LR: 0.000044
Epoch: 093 | MCC: 0.030689 | Train loss: 0.9812 | Train acc: 51.09% | Val loss: 0.9459 | Val acc: 55.37% | LR: 0.000042
Epoch: 094 | MCC: 0.029298 | Train loss: 0.9833 | Train acc: 50.93% | Val loss: 0.9452 | Val acc: 55.35% | LR: 0.000041
Epoch: 095 | MCC: 0.028358 | Train loss: 0.9825 | Train acc: 51.00% | Val loss: 0.9447 | Val acc: 55.34% | LR: 0.000040
Epoch: 096 | MCC: 0.027551 | Train loss: 0.9840 | Train acc: 50.82% | Val loss: 0.9443 | Val acc: 55.31% | LR: 0.000039
Epoch: 097 | MCC: 0.027749 | Train loss: 0.9833 | Train acc: 50.92% | Val loss: 0.9440 | Val acc: 55.31% | LR: 0.000037
Epoch: 098 | MCC: 0.021296 | Train loss: 0.9836 | Train acc: 50.88% | Val loss: 0.9433 | Val acc: 55.11% | LR: 0.000036
Epoch: 099 | MCC: 0.022127 | Train loss: 0.9826 | Train acc: 50.96% | Val loss: 0.9430 | Val acc: 55.20% | LR: 0.000035
Epoch: 100 | MCC: 0.022697 | Train loss: 0.9838 | Train acc: 50.90% | Val loss: 0.9425 | Val acc: 55.26% | LR: 0.000034
Epoch: 101 | MCC: 0.022268 | Train loss: 0.9817 | Train acc: 50.99% | Val loss: 0.9422 | Val acc: 55.28% | LR: 0.000032
Epoch: 102 | MCC: 0.022716 | Train loss: 0.9825 | Train acc: 51.06% | Val loss: 0.9419 | Val acc: 55.37% | LR: 0.000031
Epoch: 103 | MCC: 0.021937 | Train loss: 0.9824 | Train acc: 50.96% | Val loss: 0.9417 | Val acc: 55.32% | LR: 0.000030
Epoch: 104 | MCC: 0.022054 | Train loss: 0.9820 | Train acc: 51.03% | Val loss: 0.9414 | Val acc: 55.32% | LR: 0.000029
Epoch: 105 | MCC: 0.021719 | Train loss: 0.9817 | Train acc: 50.95% | Val loss: 0.9412 | Val acc: 55.35% | LR: 0.000028
Epoch: 106 | MCC: 0.023079 | Train loss: 0.9838 | Train acc: 50.85% | Val loss: 0.9410 | Val acc: 55.40% | LR: 0.000027
Epoch: 107 | MCC: 0.019603 | Train loss: 0.9830 | Train acc: 50.88% | Val loss: 0.9409 | Val acc: 55.24% | LR: 0.000026
Epoch: 108 | MCC: 0.021538 | Train loss: 0.9834 | Train acc: 50.85% | Val loss: 0.9407 | Val acc: 55.40% | LR: 0.000024
Epoch: 109 | MCC: 0.019828 | Train loss: 0.9838 | Train acc: 50.86% | Val loss: 0.9406 | Val acc: 55.28% | LR: 0.000023
Epoch: 110 | MCC: 0.021432 | Train loss: 0.9820 | Train acc: 50.99% | Val loss: 0.9404 | Val acc: 55.38% | LR: 0.000022
Epoch: 111 | MCC: 0.021537 | Train loss: 0.9829 | Train acc: 50.91% | Val loss: 0.9403 | Val acc: 55.38% | LR: 0.000021
Epoch: 112 | MCC: 0.020676 | Train loss: 0.9820 | Train acc: 50.90% | Val loss: 0.9402 | Val acc: 55.34% | LR: 0.000020
Epoch: 113 | MCC: 0.021837 | Train loss: 0.9817 | Train acc: 50.96% | Val loss: 0.9400 | Val acc: 55.41% | LR: 0.000019
Epoch: 114 | MCC: 0.020659 | Train loss: 0.9832 | Train acc: 50.89% | Val loss: 0.9400 | Val acc: 55.31% | LR: 0.000018
Epoch: 115 | MCC: 0.021591 | Train loss: 0.9817 | Train acc: 50.98% | Val loss: 0.9399 | Val acc: 55.38% | LR: 0.000017
Epoch: 116 | MCC: 0.021819 | Train loss: 0.9820 | Train acc: 50.89% | Val loss: 0.9397 | Val acc: 55.38% | LR: 0.000017
Epoch: 117 | MCC: 0.020888 | Train loss: 0.9816 | Train acc: 50.94% | Val loss: 0.9397 | Val acc: 55.29% | LR: 0.000016
Epoch: 118 | MCC: 0.023206 | Train loss: 0.9836 | Train acc: 50.86% | Val loss: 0.9396 | Val acc: 55.43% | LR: 0.000015
Epoch: 119 | MCC: 0.023592 | Train loss: 0.9819 | Train acc: 51.00% | Val loss: 0.9395 | Val acc: 55.46% | LR: 0.000014
Epoch: 120 | MCC: 0.022433 | Train loss: 0.9828 | Train acc: 50.93% | Val loss: 0.9395 | Val acc: 55.38% | LR: 0.000013
Epoch: 121 | MCC: 0.023592 | Train loss: 0.9827 | Train acc: 50.86% | Val loss: 0.9394 | Val acc: 55.46% | LR: 0.000012
Epoch: 122 | MCC: 0.022433 | Train loss: 0.9820 | Train acc: 50.93% | Val loss: 0.9394 | Val acc: 55.38% | LR: 0.000012
Epoch: 123 | MCC: 0.022277 | Train loss: 0.9829 | Train acc: 50.81% | Val loss: 0.9392 | Val acc: 55.36% | LR: 0.000011
Epoch: 124 | MCC: 0.022277 | Train loss: 0.9832 | Train acc: 50.89% | Val loss: 0.9391 | Val acc: 55.36% | LR: 0.000010
Epoch: 125 | MCC: 0.022277 | Train loss: 0.9839 | Train acc: 50.79% | Val loss: 0.9391 | Val acc: 55.36% | LR: 0.000009
Epoch: 126 | MCC: 0.022341 | Train loss: 0.9818 | Train acc: 50.93% | Val loss: 0.9390 | Val acc: 55.42% | LR: 0.000009
Epoch: 127 | MCC: 0.022341 | Train loss: 0.9820 | Train acc: 50.96% | Val loss: 0.9389 | Val acc: 55.42% | LR: 0.000008
Epoch: 128 | MCC: 0.022341 | Train loss: 0.9826 | Train acc: 50.92% | Val loss: 0.9388 | Val acc: 55.42% | LR: 0.000007
Epoch: 129 | MCC: 0.022341 | Train loss: 0.9834 | Train acc: 50.81% | Val loss: 0.9388 | Val acc: 55.42% | LR: 0.000007
Epoch: 130 | MCC: 0.024150 | Train loss: 0.9825 | Train acc: 50.94% | Val loss: 0.9388 | Val acc: 55.59% | LR: 0.000006
Epoch: 131 | MCC: 0.024150 | Train loss: 0.9828 | Train acc: 50.98% | Val loss: 0.9387 | Val acc: 55.59% | LR: 0.000006
Epoch: 132 | MCC: 0.024150 | Train loss: 0.9829 | Train acc: 50.88% | Val loss: 0.9386 | Val acc: 55.59% | LR: 0.000005
Epoch: 133 | MCC: 0.025069 | Train loss: 0.9832 | Train acc: 50.84% | Val loss: 0.9386 | Val acc: 55.67% | LR: 0.000005
Epoch: 134 | MCC: 0.025069 | Train loss: 0.9831 | Train acc: 50.92% | Val loss: 0.9386 | Val acc: 55.67% | LR: 0.000004
Epoch: 135 | MCC: 0.025300 | Train loss: 0.9832 | Train acc: 50.88% | Val loss: 0.9385 | Val acc: 55.67% | LR: 0.000004
Epoch: 136 | MCC: 0.025300 | Train loss: 0.9815 | Train acc: 51.04% | Val loss: 0.9385 | Val acc: 55.67% | LR: 0.000003
Epoch: 137 | MCC: 0.025300 | Train loss: 0.9829 | Train acc: 50.88% | Val loss: 0.9384 | Val acc: 55.67% | LR: 0.000003
Epoch: 138 | MCC: 0.025300 | Train loss: 0.9816 | Train acc: 50.93% | Val loss: 0.9384 | Val acc: 55.67% | LR: 0.000003
Epoch: 139 | MCC: 0.025403 | Train loss: 0.9816 | Train acc: 50.99% | Val loss: 0.9384 | Val acc: 55.67% | LR: 0.000002
Epoch: 140 | MCC: 0.025300 | Train loss: 0.9829 | Train acc: 50.97% | Val loss: 0.9383 | Val acc: 55.67% | LR: 0.000002
Epoch: 141 | MCC: 0.025877 | Train loss: 0.9833 | Train acc: 50.84% | Val loss: 0.9383 | Val acc: 55.69% | LR: 0.000002
Epoch: 142 | MCC: 0.025877 | Train loss: 0.9816 | Train acc: 50.99% | Val loss: 0.9383 | Val acc: 55.69% | LR: 0.000002
Epoch: 143 | MCC: 0.026109 | Train loss: 0.9813 | Train acc: 50.96% | Val loss: 0.9383 | Val acc: 55.69% | LR: 0.000002
Epoch: 144 | MCC: 0.026109 | Train loss: 0.9820 | Train acc: 50.90% | Val loss: 0.9383 | Val acc: 55.69% | LR: 0.000001
Epoch: 145 | MCC: 0.025635 | Train loss: 0.9820 | Train acc: 50.95% | Val loss: 0.9383 | Val acc: 55.67% | LR: 0.000001
Epoch: 146 | MCC: 0.025635 | Train loss: 0.9809 | Train acc: 50.97% | Val loss: 0.9383 | Val acc: 55.67% | LR: 0.000001
Epoch: 147 | MCC: 0.025635 | Train loss: 0.9817 | Train acc: 50.96% | Val loss: 0.9382 | Val acc: 55.67% | LR: 0.000001
Epoch: 148 | MCC: 0.025635 | Train loss: 0.9824 | Train acc: 50.89% | Val loss: 0.9382 | Val acc: 55.67% | LR: 0.000001
Epoch: 149 | MCC: 0.025635 | Train loss: 0.9834 | Train acc: 50.90% | Val loss: 0.9382 | Val acc: 55.67% | LR: 0.000001

[I 2025-10-05 09:52:37,263] Trial 37 finished with value: 0.025634825229644775 and parameters: {'lr': 0.00013642501952048473, 'hidden_size': 60, 'dropout': 0.29825579499950894, 'weight_decay': 0.05987839075062568}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.017456 | Train loss: 0.9990 | Train acc: 50.66% | Val loss: 1.0043 | Val acc: 49.86% | LR: 0.000301
Epoch: 001 | MCC: 0.003639 | Train loss: 0.9975 | Train acc: 50.71% | Val loss: 1.0043 | Val acc: 49.34% | LR: 0.000300
Epoch: 002 | MCC: 0.006799 | Train loss: 1.0013 | Train acc: 50.80% | Val loss: 1.0109 | Val acc: 49.46% | LR: 0.000300
Epoch: 003 | MCC: 0.011832 | Train loss: 1.0064 | Train acc: 50.73% | Val loss: 1.0055 | Val acc: 50.15% | LR: 0.000300
Epoch: 004 | MCC: 0.031141 | Train loss: 0.9975 | Train acc: 50.70% | Val loss: 1.0217 | Val acc: 50.50% | LR: 0.000300
Epoch: 005 | MCC: 0.038410 | Train loss: 0.9938 | Train acc: 50.61% | Val loss: 1.0028 | Val acc: 50.81% | LR: 0.000299
Epoch: 006 | MCC: 0.035584 | Train loss: 0.9925 | Train acc: 50.71% | Val loss: 0.9988 | Val acc: 49.91% | LR: 0.000299
Epoch: 007 | MCC: 0.030810 | Train loss: 0.9903 | Train acc: 50.74% | Val loss: 1.0000 | Val acc: 49.97% | LR: 0.000298
Epoch: 008 | MCC: 0.032999 | Train loss: 0.9883 | Train acc: 50.78% | Val loss: 0.9990 | Val acc: 49.69% | LR: 0.000298
Epoch: 009 | MCC: 0.040420 | Train loss: 0.9883 | Train acc: 50.79% | Val loss: 0.9961 | Val acc: 51.20% | LR: 0.000297
Epoch: 010 | MCC: 0.038944 | Train loss: 0.9896 | Train acc: 50.68% | Val loss: 0.9954 | Val acc: 51.25% | LR: 0.000297
Epoch: 011 | MCC: 0.045436 | Train loss: 0.9877 | Train acc: 50.82% | Val loss: 0.9948 | Val acc: 51.76% | LR: 0.000296
Epoch: 012 | MCC: 0.044593 | Train loss: 0.9883 | Train acc: 50.67% | Val loss: 0.9937 | Val acc: 52.07% | LR: 0.000295
Epoch: 013 | MCC: 0.037210 | Train loss: 0.9876 | Train acc: 50.76% | Val loss: 0.9920 | Val acc: 52.39% | LR: 0.000294
Epoch: 014 | MCC: 0.039033 | Train loss: 0.9869 | Train acc: 50.72% | Val loss: 0.9911 | Val acc: 52.80% | LR: 0.000293
Epoch: 015 | MCC: 0.027532 | Train loss: 0.9872 | Train acc: 50.71% | Val loss: 0.9892 | Val acc: 52.47% | LR: 0.000292
Epoch: 016 | MCC: 0.032682 | Train loss: 0.9844 | Train acc: 50.87% | Val loss: 0.9865 | Val acc: 53.10% | LR: 0.000291
Epoch: 017 | MCC: 0.032025 | Train loss: 0.9864 | Train acc: 50.91% | Val loss: 0.9849 | Val acc: 53.38% | LR: 0.000290
Epoch: 018 | MCC: 0.037380 | Train loss: 0.9867 | Train acc: 50.73% | Val loss: 0.9824 | Val acc: 53.68% | LR: 0.000289
Epoch: 019 | MCC: 0.040100 | Train loss: 0.9858 | Train acc: 50.72% | Val loss: 0.9810 | Val acc: 54.02% | LR: 0.000288
Epoch: 020 | MCC: 0.038118 | Train loss: 0.9844 | Train acc: 50.83% | Val loss: 0.9785 | Val acc: 54.16% | LR: 0.000286
Epoch: 021 | MCC: 0.044011 | Train loss: 0.9852 | Train acc: 50.82% | Val loss: 0.9758 | Val acc: 54.54% | LR: 0.000285
Epoch: 022 | MCC: 0.024413 | Train loss: 0.9843 | Train acc: 50.89% | Val loss: 0.9714 | Val acc: 54.43% | LR: 0.000284
Epoch: 023 | MCC: 0.031312 | Train loss: 0.9841 | Train acc: 50.83% | Val loss: 0.9667 | Val acc: 55.01% | LR: 0.000282
Epoch: 024 | MCC: 0.036587 | Train loss: 0.9836 | Train acc: 50.87% | Val loss: 0.9620 | Val acc: 55.23% | LR: 0.000281
Epoch: 025 | MCC: 0.035691 | Train loss: 0.9818 | Train acc: 51.02% | Val loss: 0.9557 | Val acc: 55.34% | LR: 0.000279
Epoch: 026 | MCC: 0.035343 | Train loss: 0.9815 | Train acc: 51.01% | Val loss: 0.9502 | Val acc: 55.40% | LR: 0.000277
Epoch: 027 | MCC: 0.031871 | Train loss: 0.9837 | Train acc: 50.86% | Val loss: 0.9452 | Val acc: 55.71% | LR: 0.000276
Epoch: 028 | MCC: 0.032088 | Train loss: 0.9823 | Train acc: 50.90% | Val loss: 0.9408 | Val acc: 55.94% | LR: 0.000274
Epoch: 029 | MCC: 0.018029 | Train loss: 0.9820 | Train acc: 50.89% | Val loss: 0.9355 | Val acc: 55.44% | LR: 0.000272
Epoch: 030 | MCC: 0.018933 | Train loss: 0.9808 | Train acc: 50.89% | Val loss: 0.9314 | Val acc: 55.84% | LR: 0.000270
Epoch: 031 | MCC: 0.020116 | Train loss: 0.9822 | Train acc: 50.85% | Val loss: 0.9305 | Val acc: 56.07% | LR: 0.000268
Epoch: 032 | MCC: 0.019962 | Train loss: 0.9807 | Train acc: 50.96% | Val loss: 0.9293 | Val acc: 55.93% | LR: 0.000266
Epoch: 033 | MCC: 0.018267 | Train loss: 0.9802 | Train acc: 51.01% | Val loss: 0.9269 | Val acc: 56.21% | LR: 0.000264
Epoch: 034 | MCC: 0.025268 | Train loss: 0.9799 | Train acc: 50.98% | Val loss: 0.9201 | Val acc: 56.47% | LR: 0.000262
Epoch: 035 | MCC: 0.024259 | Train loss: 0.9804 | Train acc: 50.97% | Val loss: 0.9140 | Val acc: 56.74% | LR: 0.000260
Epoch: 036 | MCC: 0.034768 | Train loss: 0.9814 | Train acc: 50.89% | Val loss: 0.9090 | Val acc: 57.37% | LR: 0.000258
Epoch: 037 | MCC: 0.041415 | Train loss: 0.9810 | Train acc: 50.94% | Val loss: 0.9058 | Val acc: 57.56% | LR: 0.000256
Epoch: 038 | MCC: 0.045573 | Train loss: 0.9791 | Train acc: 51.06% | Val loss: 0.8993 | Val acc: 57.70% | LR: 0.000253
Epoch: 039 | MCC: 0.043570 | Train loss: 0.9826 | Train acc: 51.06% | Val loss: 0.8938 | Val acc: 57.59% | LR: 0.000251
Epoch: 040 | MCC: 0.028998 | Train loss: 0.9831 | Train acc: 50.97% | Val loss: 0.8906 | Val acc: 57.18% | LR: 0.000249
Epoch: 041 | MCC: 0.021912 | Train loss: 0.9783 | Train acc: 51.23% | Val loss: 0.8853 | Val acc: 56.62% | LR: 0.000246
Epoch: 042 | MCC: 0.024581 | Train loss: 0.9762 | Train acc: 51.26% | Val loss: 0.8832 | Val acc: 56.79% | LR: 0.000244
Epoch: 043 | MCC: 0.032525 | Train loss: 0.9794 | Train acc: 51.03% | Val loss: 0.8761 | Val acc: 57.17% | LR: 0.000241
Epoch: 044 | MCC: 0.010339 | Train loss: 0.9780 | Train acc: 51.10% | Val loss: 0.8816 | Val acc: 56.66% | LR: 0.000239
Epoch: 045 | MCC: 0.007146 | Train loss: 0.9768 | Train acc: 51.19% | Val loss: 0.8834 | Val acc: 56.47% | LR: 0.000236
Epoch: 046 | MCC: 0.010355 | Train loss: 0.9765 | Train acc: 51.13% | Val loss: 0.8763 | Val acc: 56.56% | LR: 0.000234
Epoch: 047 | MCC: 0.013219 | Train loss: 0.9765 | Train acc: 51.15% | Val loss: 0.8790 | Val acc: 56.39% | LR: 0.000231
Epoch: 048 | MCC: 0.009294 | Train loss: 0.9763 | Train acc: 51.11% | Val loss: 0.8783 | Val acc: 56.49% | LR: 0.000228
Epoch: 049 | MCC: 0.016679 | Train loss: 0.9738 | Train acc: 51.33% | Val loss: 0.8691 | Val acc: 57.30% | LR: 0.000226
Epoch: 050 | MCC: 0.017686 | Train loss: 0.9740 | Train acc: 51.27% | Val loss: 0.8700 | Val acc: 57.27% | LR: 0.000223
Epoch: 051 | MCC: 0.015611 | Train loss: 0.9732 | Train acc: 51.31% | Val loss: 0.8652 | Val acc: 57.20% | LR: 0.000220
Epoch: 052 | MCC: 0.004807 | Train loss: 0.9779 | Train acc: 51.17% | Val loss: 0.8587 | Val acc: 57.49% | LR: 0.000217
Epoch: 053 | MCC: 0.001491 | Train loss: 0.9755 | Train acc: 51.22% | Val loss: 0.8589 | Val acc: 57.35% | LR: 0.000215
Epoch: 054 | MCC: 0.007193 | Train loss: 0.9719 | Train acc: 51.34% | Val loss: 0.8602 | Val acc: 57.59% | LR: 0.000212
Epoch: 055 | MCC: 0.015357 | Train loss: 0.9728 | Train acc: 51.21% | Val loss: 0.8719 | Val acc: 56.49% | LR: 0.000209
Epoch: 056 | MCC: 0.014668 | Train loss: 0.9713 | Train acc: 51.41% | Val loss: 0.8572 | Val acc: 57.61% | LR: 0.000206
Epoch: 057 | MCC: 0.023913 | Train loss: 0.9715 | Train acc: 51.32% | Val loss: 0.8546 | Val acc: 57.93% | LR: 0.000203
Epoch: 058 | MCC: 0.022517 | Train loss: 0.9713 | Train acc: 51.36% | Val loss: 0.8577 | Val acc: 57.81% | LR: 0.000200
Epoch: 059 | MCC: 0.012800 | Train loss: 0.9697 | Train acc: 51.36% | Val loss: 0.8611 | Val acc: 57.35% | LR: 0.000197
Epoch: 060 | MCC: 0.021929 | Train loss: 0.9710 | Train acc: 51.33% | Val loss: 0.8514 | Val acc: 57.88% | LR: 0.000194
Epoch: 061 | MCC: 0.027623 | Train loss: 0.9693 | Train acc: 51.45% | Val loss: 0.8333 | Val acc: 58.93% | LR: 0.000191
Epoch: 062 | MCC: 0.038233 | Train loss: 0.9723 | Train acc: 51.23% | Val loss: 0.8516 | Val acc: 57.88% | LR: 0.000188
Epoch: 063 | MCC: 0.026957 | Train loss: 0.9708 | Train acc: 51.26% | Val loss: 0.8398 | Val acc: 58.54% | LR: 0.000185
Epoch: 064 | MCC: 0.041813 | Train loss: 0.9690 | Train acc: 51.46% | Val loss: 0.8245 | Val acc: 59.62% | LR: 0.000182
Epoch: 065 | MCC: 0.041516 | Train loss: 0.9689 | Train acc: 51.36% | Val loss: 0.8270 | Val acc: 59.52% | LR: 0.000179
Epoch: 066 | MCC: 0.030485 | Train loss: 0.9690 | Train acc: 51.44% | Val loss: 0.8278 | Val acc: 59.03% | LR: 0.000176
Epoch: 067 | MCC: 0.052967 | Train loss: 0.9685 | Train acc: 51.37% | Val loss: 0.8325 | Val acc: 58.98% | LR: 0.000173
Epoch: 068 | MCC: 0.026092 | Train loss: 0.9666 | Train acc: 51.52% | Val loss: 0.8373 | Val acc: 58.44% | LR: 0.000170
Epoch: 069 | MCC: 0.026008 | Train loss: 0.9702 | Train acc: 51.20% | Val loss: 0.8394 | Val acc: 58.15% | LR: 0.000166
Epoch: 070 | MCC: 0.061653 | Train loss: 0.9681 | Train acc: 51.78% | Val loss: 0.8097 | Val acc: 60.10% | LR: 0.000163
Epoch: 071 | MCC: 0.030470 | Train loss: 0.9670 | Train acc: 51.94% | Val loss: 0.8259 | Val acc: 59.01% | LR: 0.000160
Epoch: 072 | MCC: 0.064296 | Train loss: 0.9667 | Train acc: 52.03% | Val loss: 0.8085 | Val acc: 60.18% | LR: 0.000157
Epoch: 073 | MCC: 0.040311 | Train loss: 0.9674 | Train acc: 52.02% | Val loss: 0.8131 | Val acc: 59.67% | LR: 0.000154
Epoch: 074 | MCC: 0.063240 | Train loss: 0.9650 | Train acc: 52.21% | Val loss: 0.8102 | Val acc: 59.84% | LR: 0.000151
Epoch: 075 | MCC: 0.060347 | Train loss: 0.9655 | Train acc: 52.14% | Val loss: 0.8123 | Val acc: 59.67% | LR: 0.000148
Epoch: 076 | MCC: 0.029316 | Train loss: 0.9678 | Train acc: 52.18% | Val loss: 0.8419 | Val acc: 58.01% | LR: 0.000145
Epoch: 077 | MCC: 0.054881 | Train loss: 0.9644 | Train acc: 52.20% | Val loss: 0.8251 | Val acc: 59.08% | LR: 0.000141
Epoch: 078 | MCC: 0.031069 | Train loss: 0.9668 | Train acc: 52.15% | Val loss: 0.8231 | Val acc: 59.05% | LR: 0.000138
Epoch: 079 | MCC: 0.034250 | Train loss: 0.9660 | Train acc: 52.18% | Val loss: 0.8160 | Val acc: 59.45% | LR: 0.000135
Epoch: 080 | MCC: 0.052723 | Train loss: 0.9663 | Train acc: 52.08% | Val loss: 0.8275 | Val acc: 58.74% | LR: 0.000132
Epoch: 081 | MCC: 0.029189 | Train loss: 0.9647 | Train acc: 52.18% | Val loss: 0.8141 | Val acc: 59.41% | LR: 0.000129
Epoch: 082 | MCC: 0.025269 | Train loss: 0.9655 | Train acc: 52.14% | Val loss: 0.8316 | Val acc: 58.48% | LR: 0.000126
Epoch: 083 | MCC: 0.043882 | Train loss: 0.9665 | Train acc: 52.14% | Val loss: 0.8135 | Val acc: 59.31% | LR: 0.000123
Epoch: 084 | MCC: 0.032583 | Train loss: 0.9626 | Train acc: 52.30% | Val loss: 0.8178 | Val acc: 59.41% | LR: 0.000120
Epoch: 085 | MCC: 0.036201 | Train loss: 0.9644 | Train acc: 52.16% | Val loss: 0.8257 | Val acc: 58.98% | LR: 0.000117
Epoch: 086 | MCC: 0.066622 | Train loss: 0.9635 | Train acc: 52.21% | Val loss: 0.8015 | Val acc: 60.23% | LR: 0.000114
Epoch: 087 | MCC: 0.061392 | Train loss: 0.9627 | Train acc: 52.25% | Val loss: 0.8093 | Val acc: 59.81% | LR: 0.000111
Epoch: 088 | MCC: 0.033846 | Train loss: 0.9638 | Train acc: 52.19% | Val loss: 0.8171 | Val acc: 59.29% | LR: 0.000107
Epoch: 089 | MCC: 0.034035 | Train loss: 0.9629 | Train acc: 52.14% | Val loss: 0.8156 | Val acc: 59.39% | LR: 0.000104
Epoch: 090 | MCC: 0.057783 | Train loss: 0.9635 | Train acc: 52.13% | Val loss: 0.8260 | Val acc: 58.81% | LR: 0.000102
Epoch: 091 | MCC: 0.051042 | Train loss: 0.9638 | Train acc: 52.13% | Val loss: 0.8278 | Val acc: 58.80% | LR: 0.000099
Epoch: 092 | MCC: 0.038423 | Train loss: 0.9627 | Train acc: 52.23% | Val loss: 0.8298 | Val acc: 58.74% | LR: 0.000096
Epoch: 093 | MCC: 0.031025 | Train loss: 0.9630 | Train acc: 52.18% | Val loss: 0.8208 | Val acc: 59.22% | LR: 0.000093
Epoch: 094 | MCC: 0.033131 | Train loss: 0.9629 | Train acc: 52.22% | Val loss: 0.8155 | Val acc: 59.41% | LR: 0.000090
Epoch: 095 | MCC: 0.031086 | Train loss: 0.9656 | Train acc: 52.07% | Val loss: 0.8220 | Val acc: 59.04% | LR: 0.000087
Epoch: 096 | MCC: 0.030761 | Train loss: 0.9631 | Train acc: 52.20% | Val loss: 0.8247 | Val acc: 58.97% | LR: 0.000084
Epoch: 097 | MCC: 0.028837 | Train loss: 0.9663 | Train acc: 52.17% | Val loss: 0.8218 | Val acc: 59.04% | LR: 0.000081
Epoch: 098 | MCC: 0.036607 | Train loss: 0.9625 | Train acc: 52.24% | Val loss: 0.8180 | Val acc: 59.34% | LR: 0.000079
Epoch: 099 | MCC: 0.028524 | Train loss: 0.9624 | Train acc: 52.20% | Val loss: 0.8235 | Val acc: 58.92% | LR: 0.000076
Epoch: 100 | MCC: 0.058948 | Train loss: 0.9615 | Train acc: 52.26% | Val loss: 0.8129 | Val acc: 59.49% | LR: 0.000073
Epoch: 101 | MCC: 0.052850 | Train loss: 0.9623 | Train acc: 52.15% | Val loss: 0.8056 | Val acc: 59.85% | LR: 0.000071
Epoch: 102 | MCC: 0.061894 | Train loss: 0.9620 | Train acc: 52.21% | Val loss: 0.8115 | Val acc: 59.74% | LR: 0.000068
Epoch: 103 | MCC: 0.032454 | Train loss: 0.9619 | Train acc: 52.18% | Val loss: 0.8205 | Val acc: 59.17% | LR: 0.000065
Epoch: 104 | MCC: 0.031565 | Train loss: 0.9626 | Train acc: 52.16% | Val loss: 0.8183 | Val acc: 59.24% | LR: 0.000063
Epoch: 105 | MCC: 0.028993 | Train loss: 0.9616 | Train acc: 52.21% | Val loss: 0.8223 | Val acc: 59.00% | LR: 0.000060
Epoch: 106 | MCC: 0.029667 | Train loss: 0.9614 | Train acc: 52.23% | Val loss: 0.8202 | Val acc: 59.14% | LR: 0.000058
Epoch: 107 | MCC: 0.031430 | Train loss: 0.9603 | Train acc: 52.28% | Val loss: 0.8197 | Val acc: 59.09% | LR: 0.000055
Epoch: 108 | MCC: 0.033402 | Train loss: 0.9602 | Train acc: 52.33% | Val loss: 0.8183 | Val acc: 59.17% | LR: 0.000053
Epoch: 109 | MCC: 0.029514 | Train loss: 0.9615 | Train acc: 52.20% | Val loss: 0.8188 | Val acc: 59.12% | LR: 0.000051
Epoch: 110 | MCC: 0.030153 | Train loss: 0.9617 | Train acc: 52.17% | Val loss: 0.8199 | Val acc: 59.04% | LR: 0.000048
Epoch: 111 | MCC: 0.028780 | Train loss: 0.9615 | Train acc: 52.18% | Val loss: 0.8195 | Val acc: 59.04% | LR: 0.000046
Epoch: 112 | MCC: 0.030755 | Train loss: 0.9594 | Train acc: 52.30% | Val loss: 0.8195 | Val acc: 59.07% | LR: 0.000044
Epoch: 113 | MCC: 0.031113 | Train loss: 0.9606 | Train acc: 52.25% | Val loss: 0.8188 | Val acc: 59.12% | LR: 0.000042
Epoch: 114 | MCC: 0.033312 | Train loss: 0.9613 | Train acc: 52.21% | Val loss: 0.8198 | Val acc: 59.14% | LR: 0.000039
Epoch: 115 | MCC: 0.029214 | Train loss: 0.9626 | Train acc: 52.11% | Val loss: 0.8184 | Val acc: 59.07% | LR: 0.000037
Epoch: 116 | MCC: 0.033294 | Train loss: 0.9623 | Train acc: 52.14% | Val loss: 0.8180 | Val acc: 59.17% | LR: 0.000035
Epoch: 117 | MCC: 0.030234 | Train loss: 0.9608 | Train acc: 52.23% | Val loss: 0.8192 | Val acc: 59.09% | LR: 0.000033
Epoch: 118 | MCC: 0.029361 | Train loss: 0.9608 | Train acc: 52.22% | Val loss: 0.8189 | Val acc: 59.07% | LR: 0.000031
Epoch: 119 | MCC: 0.029357 | Train loss: 0.9580 | Train acc: 52.41% | Val loss: 0.8187 | Val acc: 59.07% | LR: 0.000030
Epoch: 120 | MCC: 0.031591 | Train loss: 0.9596 | Train acc: 52.35% | Val loss: 0.8190 | Val acc: 59.12% | LR: 0.000028
Epoch: 121 | MCC: 0.029781 | Train loss: 0.9603 | Train acc: 52.23% | Val loss: 0.8188 | Val acc: 59.07% | LR: 0.000026
Epoch: 122 | MCC: 0.031536 | Train loss: 0.9598 | Train acc: 52.29% | Val loss: 0.8192 | Val acc: 59.09% | LR: 0.000024
Epoch: 123 | MCC: 0.028294 | Train loss: 0.9601 | Train acc: 52.22% | Val loss: 0.8193 | Val acc: 59.02% | LR: 0.000023
Epoch: 124 | MCC: 0.033498 | Train loss: 0.9622 | Train acc: 52.12% | Val loss: 0.8164 | Val acc: 59.26% | LR: 0.000021
Epoch: 125 | MCC: 0.031173 | Train loss: 0.9588 | Train acc: 52.32% | Val loss: 0.8184 | Val acc: 59.14% | LR: 0.000020
Epoch: 126 | MCC: 0.030782 | Train loss: 0.9601 | Train acc: 52.28% | Val loss: 0.8186 | Val acc: 59.09% | LR: 0.000018
Epoch: 127 | MCC: 0.028681 | Train loss: 0.9597 | Train acc: 52.32% | Val loss: 0.8184 | Val acc: 59.04% | LR: 0.000017
Epoch: 128 | MCC: 0.031625 | Train loss: 0.9592 | Train acc: 52.29% | Val loss: 0.8180 | Val acc: 59.17% | LR: 0.000015
Epoch: 129 | MCC: 0.031934 | Train loss: 0.9607 | Train acc: 52.22% | Val loss: 0.8176 | Val acc: 59.19% | LR: 0.000014
Epoch: 130 | MCC: 0.029501 | Train loss: 0.9595 | Train acc: 52.30% | Val loss: 0.8191 | Val acc: 59.04% | LR: 0.000013
Epoch: 131 | MCC: 0.028681 | Train loss: 0.9589 | Train acc: 52.37% | Val loss: 0.8182 | Val acc: 59.04% | LR: 0.000012
Epoch: 132 | MCC: 0.028375 | Train loss: 0.9597 | Train acc: 52.26% | Val loss: 0.8184 | Val acc: 59.02% | LR: 0.000010
Epoch: 133 | MCC: 0.031625 | Train loss: 0.9595 | Train acc: 52.31% | Val loss: 0.8180 | Val acc: 59.17% | LR: 0.000009
Epoch: 134 | MCC: 0.031625 | Train loss: 0.9592 | Train acc: 52.31% | Val loss: 0.8177 | Val acc: 59.17% | LR: 0.000008
Epoch: 135 | MCC: 0.030105 | Train loss: 0.9606 | Train acc: 52.23% | Val loss: 0.8186 | Val acc: 59.07% | LR: 0.000007
Epoch: 136 | MCC: 0.030867 | Train loss: 0.9598 | Train acc: 52.28% | Val loss: 0.8179 | Val acc: 59.12% | LR: 0.000007
Epoch: 137 | MCC: 0.031320 | Train loss: 0.9582 | Train acc: 52.39% | Val loss: 0.8181 | Val acc: 59.14% | LR: 0.000006
Epoch: 138 | MCC: 0.030867 | Train loss: 0.9601 | Train acc: 52.24% | Val loss: 0.8181 | Val acc: 59.12% | LR: 0.000005
Epoch: 139 | MCC: 0.031320 | Train loss: 0.9590 | Train acc: 52.36% | Val loss: 0.8184 | Val acc: 59.14% | LR: 0.000004
Epoch: 140 | MCC: 0.031320 | Train loss: 0.9606 | Train acc: 52.25% | Val loss: 0.8180 | Val acc: 59.14% | LR: 0.000004
Epoch: 141 | MCC: 0.031320 | Train loss: 0.9603 | Train acc: 52.20% | Val loss: 0.8184 | Val acc: 59.14% | LR: 0.000003
Epoch: 142 | MCC: 0.031320 | Train loss: 0.9588 | Train acc: 52.38% | Val loss: 0.8181 | Val acc: 59.14% | LR: 0.000003
Epoch: 143 | MCC: 0.031320 | Train loss: 0.9589 | Train acc: 52.35% | Val loss: 0.8181 | Val acc: 59.14% | LR: 0.000002
Epoch: 144 | MCC: 0.030263 | Train loss: 0.9585 | Train acc: 52.36% | Val loss: 0.8181 | Val acc: 59.09% | LR: 0.000002
Epoch: 145 | MCC: 0.031320 | Train loss: 0.9584 | Train acc: 52.37% | Val loss: 0.8182 | Val acc: 59.14% | LR: 0.000002
Epoch: 146 | MCC: 0.031320 | Train loss: 0.9588 | Train acc: 52.37% | Val loss: 0.8181 | Val acc: 59.14% | LR: 0.000001
Epoch: 147 | MCC: 0.031320 | Train loss: 0.9593 | Train acc: 52.31% | Val loss: 0.8181 | Val acc: 59.14% | LR: 0.000001
Epoch: 148 | MCC: 0.031320 | Train loss: 0.9584 | Train acc: 52.37% | Val loss: 0.8182 | Val acc: 59.14% | LR: 0.000001
Epoch: 149 | MCC: 0.030263 | Train loss: 0.9599 | Train acc: 52.27% | Val loss: 0.8181 | Val acc: 59.09% | LR: 0.000001

[I 2025-10-05 09:54:47,018] Trial 38 finished with value: 0.03026298899203539 and parameters: {'lr': 0.00030056842203109396, 'hidden_size': 69, 'dropout': 0.07085596200412234, 'weight_decay': 0.0019879064740203323}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: -0.003374 | Train loss: 1.0024 | Train acc: 50.53% | Val loss: 0.9952 | Val acc: 51.44% | LR: 0.001760
Epoch: 001 | MCC: 0.039814 | Train loss: 0.9927 | Train acc: 50.91% | Val loss: 0.9889 | Val acc: 54.39% | LR: 0.001760
Epoch: 002 | MCC: 0.047367 | Train loss: 0.9865 | Train acc: 50.92% | Val loss: 0.9675 | Val acc: 53.93% | LR: 0.001759
Epoch: 003 | MCC: 0.050323 | Train loss: 0.9836 | Train acc: 50.95% | Val loss: 0.9623 | Val acc: 54.28% | LR: 0.001758
Epoch: 004 | MCC: 0.049052 | Train loss: 0.9938 | Train acc: 50.79% | Val loss: 1.0269 | Val acc: 53.16% | LR: 0.001756
Epoch: 005 | MCC: 0.046315 | Train loss: 0.9951 | Train acc: 50.91% | Val loss: 0.9692 | Val acc: 53.14% | LR: 0.001754
Epoch: 006 | MCC: 0.044293 | Train loss: 0.9853 | Train acc: 50.88% | Val loss: 0.9591 | Val acc: 52.96% | LR: 0.001751
Epoch: 007 | MCC: 0.039601 | Train loss: 0.9820 | Train acc: 51.24% | Val loss: 0.9626 | Val acc: 52.01% | LR: 0.001748
Epoch: 008 | MCC: 0.044739 | Train loss: 0.9842 | Train acc: 50.96% | Val loss: 0.9463 | Val acc: 52.76% | LR: 0.001745
Epoch: 009 | MCC: 0.050467 | Train loss: 0.9804 | Train acc: 50.92% | Val loss: 0.9387 | Val acc: 53.81% | LR: 0.001741
Epoch: 010 | MCC: 0.049691 | Train loss: 0.9800 | Train acc: 51.04% | Val loss: 0.9286 | Val acc: 54.12% | LR: 0.001737
Epoch: 011 | MCC: 0.039837 | Train loss: 0.9832 | Train acc: 50.91% | Val loss: 0.9601 | Val acc: 53.40% | LR: 0.001733
Epoch: 012 | MCC: 0.015142 | Train loss: 0.9871 | Train acc: 50.95% | Val loss: 0.9712 | Val acc: 52.25% | LR: 0.001728
Epoch: 013 | MCC: 0.027646 | Train loss: 0.9852 | Train acc: 50.74% | Val loss: 0.9456 | Val acc: 52.80% | LR: 0.001723
Epoch: 014 | MCC: 0.030816 | Train loss: 0.9869 | Train acc: 50.88% | Val loss: 0.9387 | Val acc: 53.10% | LR: 0.001718
Epoch: 015 | MCC: 0.031013 | Train loss: 0.9807 | Train acc: 50.80% | Val loss: 0.9437 | Val acc: 53.07% | LR: 0.001712
Epoch: 016 | MCC: 0.027078 | Train loss: 0.9792 | Train acc: 50.99% | Val loss: 0.9418 | Val acc: 52.88% | LR: 0.001705
Epoch: 017 | MCC: 0.028065 | Train loss: 0.9779 | Train acc: 51.62% | Val loss: 0.9428 | Val acc: 53.33% | LR: 0.001699
Epoch: 018 | MCC: 0.043916 | Train loss: 0.9789 | Train acc: 51.52% | Val loss: 0.9372 | Val acc: 53.34% | LR: 0.001692
Epoch: 019 | MCC: 0.046131 | Train loss: 0.9767 | Train acc: 51.74% | Val loss: 0.9419 | Val acc: 53.23% | LR: 0.001685
Epoch: 020 | MCC: 0.040985 | Train loss: 0.9910 | Train acc: 50.41% | Val loss: 0.9383 | Val acc: 53.26% | LR: 0.001677
Epoch: 021 | MCC: 0.035479 | Train loss: 0.9888 | Train acc: 50.97% | Val loss: 0.9602 | Val acc: 52.75% | LR: 0.001669
Epoch: 022 | MCC: 0.036282 | Train loss: 0.9907 | Train acc: 50.79% | Val loss: 0.9553 | Val acc: 52.65% | LR: 0.001661
Epoch: 023 | MCC: 0.033669 | Train loss: 0.9888 | Train acc: 50.66% | Val loss: 0.9610 | Val acc: 53.08% | LR: 0.001652
Epoch: 024 | MCC: 0.015127 | Train loss: 1.0015 | Train acc: 49.75% | Val loss: 0.9745 | Val acc: 51.66% | LR: 0.001643
Epoch: 025 | MCC: 0.031824 | Train loss: 1.0003 | Train acc: 50.20% | Val loss: 1.0446 | Val acc: 45.92% | LR: 0.001633
Epoch: 026 | MCC: 0.041486 | Train loss: 0.9939 | Train acc: 50.45% | Val loss: 1.0376 | Val acc: 47.62% | LR: 0.001624
Epoch: 027 | MCC: 0.006633 | Train loss: 0.9952 | Train acc: 50.14% | Val loss: 1.0496 | Val acc: 46.63% | LR: 0.001614
Epoch: 028 | MCC: -0.055666 | Train loss: 0.9949 | Train acc: 50.37% | Val loss: 1.0558 | Val acc: 44.99% | LR: 0.001603
Epoch: 029 | MCC: 0.002211 | Train loss: 0.9885 | Train acc: 50.71% | Val loss: 0.9781 | Val acc: 56.10% | LR: 0.001593
Epoch: 030 | MCC: 0.017989 | Train loss: 0.9861 | Train acc: 51.12% | Val loss: 0.9100 | Val acc: 56.77% | LR: 0.001582
Epoch: 031 | MCC: 0.017619 | Train loss: 0.9849 | Train acc: 50.78% | Val loss: 0.9145 | Val acc: 55.90% | LR: 0.001570
Epoch: 032 | MCC: 0.015536 | Train loss: 0.9931 | Train acc: 51.06% | Val loss: 1.0054 | Val acc: 55.39% | LR: 0.001559
Epoch: 033 | MCC: 0.015658 | Train loss: 0.9878 | Train acc: 50.97% | Val loss: 0.9460 | Val acc: 55.53% | LR: 0.001547
Epoch: 034 | MCC: 0.021070 | Train loss: 0.9826 | Train acc: 51.07% | Val loss: 0.9147 | Val acc: 55.88% | LR: 0.001535
Epoch: 035 | MCC: 0.026983 | Train loss: 0.9848 | Train acc: 51.03% | Val loss: 0.9435 | Val acc: 56.69% | LR: 0.001522
Epoch: 036 | MCC: 0.012044 | Train loss: 0.9854 | Train acc: 50.99% | Val loss: 0.9239 | Val acc: 56.97% | LR: 0.001509
Epoch: 037 | MCC: 0.001957 | Train loss: 0.9879 | Train acc: 50.80% | Val loss: 0.8909 | Val acc: 56.35% | LR: 0.001496
Epoch: 038 | MCC: 0.015210 | Train loss: 0.9859 | Train acc: 50.82% | Val loss: 0.9099 | Val acc: 56.36% | LR: 0.001483
Epoch: 039 | MCC: 0.006385 | Train loss: 0.9833 | Train acc: 50.86% | Val loss: 0.9009 | Val acc: 56.84% | LR: 0.001470
Epoch: 040 | MCC: 0.018476 | Train loss: 0.9822 | Train acc: 50.85% | Val loss: 0.9054 | Val acc: 56.15% | LR: 0.001456
Epoch: 041 | MCC: 0.018944 | Train loss: 0.9831 | Train acc: 51.01% | Val loss: 0.8994 | Val acc: 56.74% | LR: 0.001442
Epoch: 042 | MCC: 0.016482 | Train loss: 0.9843 | Train acc: 50.79% | Val loss: 0.9129 | Val acc: 56.64% | LR: 0.001427
Epoch: 043 | MCC: 0.018207 | Train loss: 0.9812 | Train acc: 50.90% | Val loss: 0.9237 | Val acc: 56.02% | LR: 0.001413
Epoch: 044 | MCC: 0.016164 | Train loss: 0.9821 | Train acc: 50.92% | Val loss: 0.9165 | Val acc: 56.17% | LR: 0.001398
Epoch: 045 | MCC: 0.005932 | Train loss: 0.9878 | Train acc: 50.81% | Val loss: 0.9184 | Val acc: 56.77% | LR: 0.001383
Epoch: 046 | MCC: -0.000448 | Train loss: 0.9831 | Train acc: 50.83% | Val loss: 0.9235 | Val acc: 56.43% | LR: 0.001368
Epoch: 047 | MCC: -0.008204 | Train loss: 0.9842 | Train acc: 50.91% | Val loss: 0.9247 | Val acc: 55.16% | LR: 0.001352
Epoch: 048 | MCC: -0.004605 | Train loss: 0.9844 | Train acc: 50.91% | Val loss: 0.9376 | Val acc: 54.56% | LR: 0.001337
Epoch: 049 | MCC: -0.004625 | Train loss: 0.9826 | Train acc: 50.91% | Val loss: 0.9175 | Val acc: 55.18% | LR: 0.001321
Epoch: 050 | MCC: -0.004168 | Train loss: 0.9820 | Train acc: 50.95% | Val loss: 0.9236 | Val acc: 54.81% | LR: 0.001305
Epoch: 051 | MCC: -0.004566 | Train loss: 0.9819 | Train acc: 51.02% | Val loss: 0.9345 | Val acc: 55.23% | LR: 0.001288
Epoch: 052 | MCC: -0.009546 | Train loss: 0.9814 | Train acc: 50.95% | Val loss: 0.9233 | Val acc: 54.83% | LR: 0.001272
Epoch: 053 | MCC: -0.010561 | Train loss: 0.9808 | Train acc: 51.05% | Val loss: 0.9341 | Val acc: 55.36% | LR: 0.001255
Epoch: 054 | MCC: -0.011341 | Train loss: 0.9831 | Train acc: 50.83% | Val loss: 0.9186 | Val acc: 54.94% | LR: 0.001239
Epoch: 055 | MCC: 0.007336 | Train loss: 0.9781 | Train acc: 51.15% | Val loss: 0.9063 | Val acc: 57.61% | LR: 0.001222
Epoch: 056 | MCC: 0.012622 | Train loss: 0.9792 | Train acc: 51.15% | Val loss: 0.9201 | Val acc: 57.35% | LR: 0.001205
Epoch: 057 | MCC: -0.012455 | Train loss: 0.9831 | Train acc: 50.73% | Val loss: 0.9129 | Val acc: 56.58% | LR: 0.001188
Epoch: 058 | MCC: 0.059171 | Train loss: 0.9825 | Train acc: 50.97% | Val loss: 0.9029 | Val acc: 56.11% | LR: 0.001170
Epoch: 059 | MCC: 0.013604 | Train loss: 0.9795 | Train acc: 51.38% | Val loss: 0.8926 | Val acc: 57.31% | LR: 0.001153
Epoch: 060 | MCC: 0.002926 | Train loss: 0.9811 | Train acc: 51.04% | Val loss: 0.8915 | Val acc: 57.18% | LR: 0.001135
Epoch: 061 | MCC: 0.001605 | Train loss: 0.9802 | Train acc: 50.87% | Val loss: 0.8922 | Val acc: 57.04% | LR: 0.001117
Epoch: 062 | MCC: 0.029318 | Train loss: 0.9810 | Train acc: 50.91% | Val loss: 0.8973 | Val acc: 57.16% | LR: 0.001100
Epoch: 063 | MCC: 0.026427 | Train loss: 0.9830 | Train acc: 51.14% | Val loss: 0.8801 | Val acc: 56.97% | LR: 0.001082
Epoch: 064 | MCC: 0.025534 | Train loss: 0.9818 | Train acc: 50.97% | Val loss: 0.8787 | Val acc: 56.84% | LR: 0.001064
Epoch: 065 | MCC: 0.027691 | Train loss: 0.9794 | Train acc: 51.07% | Val loss: 0.8766 | Val acc: 57.24% | LR: 0.001046
Epoch: 066 | MCC: 0.030190 | Train loss: 0.9787 | Train acc: 51.04% | Val loss: 0.8665 | Val acc: 57.71% | LR: 0.001028
Epoch: 067 | MCC: 0.021163 | Train loss: 0.9795 | Train acc: 50.97% | Val loss: 0.8817 | Val acc: 57.13% | LR: 0.001009
Epoch: 068 | MCC: 0.026366 | Train loss: 0.9795 | Train acc: 51.08% | Val loss: 0.8665 | Val acc: 57.40% | LR: 0.000991
Epoch: 069 | MCC: 0.024571 | Train loss: 0.9806 | Train acc: 50.90% | Val loss: 0.8622 | Val acc: 57.30% | LR: 0.000973
Epoch: 070 | MCC: 0.000629 | Train loss: 0.9788 | Train acc: 51.03% | Val loss: 0.9647 | Val acc: 56.68% | LR: 0.000954
Epoch: 071 | MCC: 0.002400 | Train loss: 0.9803 | Train acc: 51.02% | Val loss: 0.8781 | Val acc: 56.68% | LR: 0.000936
Epoch: 072 | MCC: 0.007493 | Train loss: 0.9774 | Train acc: 51.11% | Val loss: 0.8721 | Val acc: 57.17% | LR: 0.000918
Epoch: 073 | MCC: 0.000638 | Train loss: 0.9772 | Train acc: 51.21% | Val loss: 0.8939 | Val acc: 56.17% | LR: 0.000899
Epoch: 074 | MCC: 0.001475 | Train loss: 0.9788 | Train acc: 51.00% | Val loss: 0.8752 | Val acc: 56.68% | LR: 0.000881
Epoch: 075 | MCC: 0.002193 | Train loss: 0.9783 | Train acc: 51.06% | Val loss: 0.9013 | Val acc: 56.74% | LR: 0.000862
Epoch: 076 | MCC: 0.002606 | Train loss: 0.9779 | Train acc: 51.11% | Val loss: 0.8976 | Val acc: 55.62% | LR: 0.000844
Epoch: 077 | MCC: -0.001929 | Train loss: 0.9804 | Train acc: 50.92% | Val loss: 0.8928 | Val acc: 55.69% | LR: 0.000826
Epoch: 078 | MCC: 0.000543 | Train loss: 0.9783 | Train acc: 50.98% | Val loss: 0.8759 | Val acc: 56.95% | LR: 0.000807
Epoch: 079 | MCC: 0.002845 | Train loss: 0.9805 | Train acc: 50.93% | Val loss: 0.8736 | Val acc: 56.93% | LR: 0.000789
Epoch: 080 | MCC: 0.002873 | Train loss: 0.9799 | Train acc: 51.00% | Val loss: 0.8726 | Val acc: 57.57% | LR: 0.000771
Epoch: 081 | MCC: 0.016950 | Train loss: 0.9774 | Train acc: 51.06% | Val loss: 0.8585 | Val acc: 57.90% | LR: 0.000752
Epoch: 082 | MCC: 0.026102 | Train loss: 0.9768 | Train acc: 51.02% | Val loss: 0.8557 | Val acc: 58.77% | LR: 0.000734
Epoch: 083 | MCC: 0.027223 | Train loss: 0.9784 | Train acc: 51.14% | Val loss: 0.8611 | Val acc: 58.94% | LR: 0.000716
Epoch: 084 | MCC: 0.036488 | Train loss: 0.9790 | Train acc: 51.10% | Val loss: 0.8572 | Val acc: 59.82% | LR: 0.000698
Epoch: 085 | MCC: 0.037779 | Train loss: 0.9787 | Train acc: 51.06% | Val loss: 0.8542 | Val acc: 59.55% | LR: 0.000680
Epoch: 086 | MCC: 0.034024 | Train loss: 0.9785 | Train acc: 50.96% | Val loss: 0.8543 | Val acc: 58.74% | LR: 0.000662
Epoch: 087 | MCC: 0.039531 | Train loss: 0.9747 | Train acc: 51.41% | Val loss: 0.8449 | Val acc: 59.09% | LR: 0.000644
Epoch: 088 | MCC: 0.035620 | Train loss: 0.9758 | Train acc: 51.22% | Val loss: 0.8473 | Val acc: 58.96% | LR: 0.000627
Epoch: 089 | MCC: 0.036100 | Train loss: 0.9738 | Train acc: 51.38% | Val loss: 0.8467 | Val acc: 58.89% | LR: 0.000609
Epoch: 090 | MCC: 0.041720 | Train loss: 0.9756 | Train acc: 51.19% | Val loss: 0.8313 | Val acc: 59.72% | LR: 0.000591
Epoch: 091 | MCC: 0.037041 | Train loss: 0.9756 | Train acc: 51.20% | Val loss: 0.8248 | Val acc: 59.77% | LR: 0.000574
Epoch: 092 | MCC: 0.023068 | Train loss: 0.9731 | Train acc: 51.35% | Val loss: 0.8184 | Val acc: 59.71% | LR: 0.000557
Epoch: 093 | MCC: 0.022653 | Train loss: 0.9755 | Train acc: 51.15% | Val loss: 0.8217 | Val acc: 59.55% | LR: 0.000540
Epoch: 094 | MCC: 0.020322 | Train loss: 0.9747 | Train acc: 51.16% | Val loss: 0.8411 | Val acc: 58.39% | LR: 0.000523
Epoch: 095 | MCC: 0.034780 | Train loss: 0.9743 | Train acc: 51.22% | Val loss: 0.8310 | Val acc: 59.22% | LR: 0.000506
Epoch: 096 | MCC: 0.040287 | Train loss: 0.9740 | Train acc: 51.30% | Val loss: 0.8156 | Val acc: 60.38% | LR: 0.000490
Epoch: 097 | MCC: 0.022099 | Train loss: 0.9742 | Train acc: 51.18% | Val loss: 0.8430 | Val acc: 59.79% | LR: 0.000473
Epoch: 098 | MCC: 0.036757 | Train loss: 0.9787 | Train acc: 51.14% | Val loss: 0.8221 | Val acc: 59.53% | LR: 0.000457
Epoch: 099 | MCC: 0.036306 | Train loss: 0.9728 | Train acc: 51.35% | Val loss: 0.8292 | Val acc: 59.33% | LR: 0.000441
Epoch: 100 | MCC: 0.029480 | Train loss: 0.9736 | Train acc: 51.35% | Val loss: 0.8288 | Val acc: 59.21% | LR: 0.000425
Epoch: 101 | MCC: 0.024481 | Train loss: 0.9721 | Train acc: 51.42% | Val loss: 0.8327 | Val acc: 58.92% | LR: 0.000409
Epoch: 102 | MCC: 0.039495 | Train loss: 0.9731 | Train acc: 51.28% | Val loss: 0.8369 | Val acc: 58.74% | LR: 0.000394
Epoch: 103 | MCC: 0.026100 | Train loss: 0.9742 | Train acc: 51.16% | Val loss: 0.8509 | Val acc: 57.87% | LR: 0.000379
Epoch: 104 | MCC: 0.023985 | Train loss: 0.9759 | Train acc: 51.02% | Val loss: 0.8479 | Val acc: 57.99% | LR: 0.000364
Epoch: 105 | MCC: 0.035390 | Train loss: 0.9742 | Train acc: 51.22% | Val loss: 0.8291 | Val acc: 59.43% | LR: 0.000349
Epoch: 106 | MCC: 0.029610 | Train loss: 0.9720 | Train acc: 51.49% | Val loss: 0.8291 | Val acc: 58.87% | LR: 0.000334
Epoch: 107 | MCC: 0.038043 | Train loss: 0.9756 | Train acc: 51.53% | Val loss: 0.8263 | Val acc: 59.14% | LR: 0.000320
Epoch: 108 | MCC: 0.035378 | Train loss: 0.9750 | Train acc: 51.37% | Val loss: 0.8275 | Val acc: 59.33% | LR: 0.000306
Epoch: 109 | MCC: 0.028064 | Train loss: 0.9733 | Train acc: 51.25% | Val loss: 0.8309 | Val acc: 59.14% | LR: 0.000292
Epoch: 110 | MCC: 0.029550 | Train loss: 0.9736 | Train acc: 51.70% | Val loss: 0.8384 | Val acc: 58.26% | LR: 0.000279
Epoch: 111 | MCC: 0.039480 | Train loss: 0.9746 | Train acc: 51.45% | Val loss: 0.8389 | Val acc: 58.47% | LR: 0.000265
Epoch: 112 | MCC: 0.025830 | Train loss: 0.9741 | Train acc: 51.24% | Val loss: 0.8321 | Val acc: 59.06% | LR: 0.000252
Epoch: 113 | MCC: 0.038236 | Train loss: 0.9743 | Train acc: 51.16% | Val loss: 0.8308 | Val acc: 58.99% | LR: 0.000239
Epoch: 114 | MCC: 0.034463 | Train loss: 0.9727 | Train acc: 51.23% | Val loss: 0.8343 | Val acc: 58.72% | LR: 0.000227
Epoch: 115 | MCC: 0.043232 | Train loss: 0.9730 | Train acc: 51.40% | Val loss: 0.8348 | Val acc: 58.54% | LR: 0.000215
Epoch: 116 | MCC: 0.046408 | Train loss: 0.9735 | Train acc: 51.13% | Val loss: 0.8269 | Val acc: 59.15% | LR: 0.000203
Epoch: 117 | MCC: 0.028854 | Train loss: 0.9730 | Train acc: 51.39% | Val loss: 0.8271 | Val acc: 58.96% | LR: 0.000191
Epoch: 118 | MCC: 0.026201 | Train loss: 0.9731 | Train acc: 51.23% | Val loss: 0.8293 | Val acc: 58.89% | LR: 0.000180
Epoch: 119 | MCC: 0.026673 | Train loss: 0.9762 | Train acc: 51.26% | Val loss: 0.8302 | Val acc: 58.96% | LR: 0.000169
Epoch: 120 | MCC: 0.028436 | Train loss: 0.9728 | Train acc: 51.28% | Val loss: 0.8302 | Val acc: 58.82% | LR: 0.000158
Epoch: 121 | MCC: 0.027510 | Train loss: 0.9730 | Train acc: 51.19% | Val loss: 0.8344 | Val acc: 58.62% | LR: 0.000148
Epoch: 122 | MCC: 0.032107 | Train loss: 0.9728 | Train acc: 51.21% | Val loss: 0.8293 | Val acc: 58.92% | LR: 0.000138
Epoch: 123 | MCC: 0.027140 | Train loss: 0.9723 | Train acc: 51.25% | Val loss: 0.8309 | Val acc: 58.92% | LR: 0.000128
Epoch: 124 | MCC: 0.027287 | Train loss: 0.9720 | Train acc: 51.40% | Val loss: 0.8354 | Val acc: 58.89% | LR: 0.000119
Epoch: 125 | MCC: 0.025785 | Train loss: 0.9728 | Train acc: 51.38% | Val loss: 0.8343 | Val acc: 58.57% | LR: 0.000110
Epoch: 126 | MCC: 0.033118 | Train loss: 0.9738 | Train acc: 51.21% | Val loss: 0.8290 | Val acc: 58.96% | LR: 0.000101
Epoch: 127 | MCC: 0.023240 | Train loss: 0.9702 | Train acc: 51.33% | Val loss: 0.8375 | Val acc: 58.45% | LR: 0.000093
Epoch: 128 | MCC: 0.020861 | Train loss: 0.9717 | Train acc: 51.37% | Val loss: 0.8367 | Val acc: 58.77% | LR: 0.000085
Epoch: 129 | MCC: 0.019861 | Train loss: 0.9720 | Train acc: 51.30% | Val loss: 0.8339 | Val acc: 58.72% | LR: 0.000077
Epoch: 130 | MCC: 0.023523 | Train loss: 0.9726 | Train acc: 51.28% | Val loss: 0.8342 | Val acc: 58.72% | LR: 0.000070
Epoch: 131 | MCC: 0.027616 | Train loss: 0.9715 | Train acc: 51.25% | Val loss: 0.8408 | Val acc: 58.74% | LR: 0.000063
Epoch: 132 | MCC: 0.024937 | Train loss: 0.9722 | Train acc: 51.45% | Val loss: 0.8366 | Val acc: 58.60% | LR: 0.000056
Epoch: 133 | MCC: 0.026823 | Train loss: 0.9722 | Train acc: 51.20% | Val loss: 0.8352 | Val acc: 58.67% | LR: 0.000050
Epoch: 134 | MCC: 0.023737 | Train loss: 0.9706 | Train acc: 51.51% | Val loss: 0.8365 | Val acc: 58.62% | LR: 0.000044
Epoch: 135 | MCC: 0.020925 | Train loss: 0.9724 | Train acc: 51.32% | Val loss: 0.8370 | Val acc: 58.45% | LR: 0.000039
Epoch: 136 | MCC: 0.028428 | Train loss: 0.9714 | Train acc: 51.42% | Val loss: 0.8371 | Val acc: 58.68% | LR: 0.000033
Epoch: 137 | MCC: 0.019301 | Train loss: 0.9712 | Train acc: 51.50% | Val loss: 0.8425 | Val acc: 58.29% | LR: 0.000029
Epoch: 138 | MCC: 0.022637 | Train loss: 0.9731 | Train acc: 51.10% | Val loss: 0.8389 | Val acc: 58.36% | LR: 0.000024
Epoch: 139 | MCC: 0.019585 | Train loss: 0.9718 | Train acc: 51.31% | Val loss: 0.8416 | Val acc: 58.38% | LR: 0.000020
Epoch: 140 | MCC: 0.020857 | Train loss: 0.9710 | Train acc: 51.35% | Val loss: 0.8435 | Val acc: 58.41% | LR: 0.000017
Epoch: 141 | MCC: 0.019198 | Train loss: 0.9720 | Train acc: 51.34% | Val loss: 0.8429 | Val acc: 58.33% | LR: 0.000013
Epoch: 142 | MCC: 0.019198 | Train loss: 0.9709 | Train acc: 51.49% | Val loss: 0.8747 | Val acc: 58.33% | LR: 0.000010
Epoch: 143 | MCC: 0.024594 | Train loss: 0.9706 | Train acc: 51.33% | Val loss: 0.8379 | Val acc: 58.49% | LR: 0.000008
Epoch: 144 | MCC: 0.024594 | Train loss: 0.9713 | Train acc: 51.37% | Val loss: 0.8380 | Val acc: 58.49% | LR: 0.000006
Epoch: 145 | MCC: 0.024594 | Train loss: 0.9708 | Train acc: 51.40% | Val loss: 0.8386 | Val acc: 58.49% | LR: 0.000004
Epoch: 146 | MCC: 0.020575 | Train loss: 0.9704 | Train acc: 51.38% | Val loss: 0.8624 | Val acc: 58.41% | LR: 0.000003
Epoch: 147 | MCC: 0.020575 | Train loss: 0.9716 | Train acc: 51.35% | Val loss: 0.8905 | Val acc: 58.41% | LR: 0.000002
Epoch: 148 | MCC: 0.020575 | Train loss: 0.9709 | Train acc: 51.41% | Val loss: 0.9060 | Val acc: 58.41% | LR: 0.000001
Epoch: 149 | MCC: 0.024594 | Train loss: 0.9700 | Train acc: 51.50% | Val loss: 0.8383 | Val acc: 58.49% | LR: 0.000001

[I 2025-10-05 09:57:02,043] Trial 39 finished with value: 0.024594431277364492 and parameters: {'lr': 0.0017606506982163902, 'hidden_size': 81, 'dropout': 0.2374718725205229, 'weight_decay': 0.030676586304125997}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.025882 | Train loss: 0.9981 | Train acc: 50.56% | Val loss: 0.9962 | Val acc: 52.87% | LR: 0.000768
Epoch: 001 | MCC: 0.030566 | Train loss: 0.9946 | Train acc: 50.81% | Val loss: 0.9925 | Val acc: 53.69% | LR: 0.000768
Epoch: 002 | MCC: 0.022332 | Train loss: 0.9916 | Train acc: 50.80% | Val loss: 0.9859 | Val acc: 53.93% | LR: 0.000768
Epoch: 003 | MCC: 0.030999 | Train loss: 0.9863 | Train acc: 50.91% | Val loss: 0.9810 | Val acc: 54.13% | LR: 0.000767
Epoch: 004 | MCC: 0.033496 | Train loss: 0.9845 | Train acc: 50.79% | Val loss: 0.9741 | Val acc: 54.73% | LR: 0.000766
Epoch: 005 | MCC: 0.031920 | Train loss: 0.9839 | Train acc: 50.80% | Val loss: 0.9629 | Val acc: 55.07% | LR: 0.000765
Epoch: 006 | MCC: 0.024947 | Train loss: 0.9820 | Train acc: 50.92% | Val loss: 0.9537 | Val acc: 55.13% | LR: 0.000764
Epoch: 007 | MCC: 0.020618 | Train loss: 0.9815 | Train acc: 50.93% | Val loss: 0.9417 | Val acc: 55.07% | LR: 0.000763
Epoch: 008 | MCC: 0.017325 | Train loss: 0.9811 | Train acc: 50.93% | Val loss: 0.9215 | Val acc: 55.32% | LR: 0.000762
Epoch: 009 | MCC: 0.019755 | Train loss: 0.9803 | Train acc: 50.91% | Val loss: 0.9110 | Val acc: 55.84% | LR: 0.000760
Epoch: 010 | MCC: 0.029255 | Train loss: 0.9788 | Train acc: 50.99% | Val loss: 0.9024 | Val acc: 56.27% | LR: 0.000758
Epoch: 011 | MCC: 0.032732 | Train loss: 0.9779 | Train acc: 51.09% | Val loss: 0.8949 | Val acc: 56.60% | LR: 0.000756
Epoch: 012 | MCC: 0.048795 | Train loss: 0.9780 | Train acc: 51.05% | Val loss: 0.8817 | Val acc: 58.00% | LR: 0.000754
Epoch: 013 | MCC: 0.056599 | Train loss: 0.9762 | Train acc: 51.21% | Val loss: 0.8761 | Val acc: 58.13% | LR: 0.000752
Epoch: 014 | MCC: 0.013574 | Train loss: 0.9773 | Train acc: 51.15% | Val loss: 0.8688 | Val acc: 56.77% | LR: 0.000750
Epoch: 015 | MCC: 0.004331 | Train loss: 0.9790 | Train acc: 51.14% | Val loss: 0.8616 | Val acc: 56.85% | LR: 0.000747
Epoch: 016 | MCC: 0.038497 | Train loss: 0.9846 | Train acc: 50.96% | Val loss: 0.9026 | Val acc: 56.18% | LR: 0.000744
Epoch: 017 | MCC: 0.024521 | Train loss: 0.9857 | Train acc: 51.39% | Val loss: 0.8890 | Val acc: 56.83% | LR: 0.000742
Epoch: 018 | MCC: 0.031216 | Train loss: 0.9892 | Train acc: 51.43% | Val loss: 0.8787 | Val acc: 56.97% | LR: 0.000739
Epoch: 019 | MCC: 0.035800 | Train loss: 0.9881 | Train acc: 51.21% | Val loss: 0.9122 | Val acc: 57.07% | LR: 0.000735
Epoch: 020 | MCC: 0.036324 | Train loss: 0.9863 | Train acc: 51.16% | Val loss: 0.9001 | Val acc: 56.48% | LR: 0.000732
Epoch: 021 | MCC: 0.020116 | Train loss: 0.9848 | Train acc: 50.77% | Val loss: 0.8857 | Val acc: 57.26% | LR: 0.000728
Epoch: 022 | MCC: 0.025391 | Train loss: 0.9924 | Train acc: 50.71% | Val loss: 0.8604 | Val acc: 58.09% | LR: 0.000725
Epoch: 023 | MCC: 0.022232 | Train loss: 0.9839 | Train acc: 50.93% | Val loss: 0.8609 | Val acc: 57.97% | LR: 0.000721
Epoch: 024 | MCC: 0.020373 | Train loss: 0.9808 | Train acc: 50.87% | Val loss: 0.8805 | Val acc: 57.70% | LR: 0.000717
Epoch: 025 | MCC: 0.019557 | Train loss: 0.9804 | Train acc: 50.86% | Val loss: 0.8872 | Val acc: 57.69% | LR: 0.000713
Epoch: 026 | MCC: 0.036675 | Train loss: 0.9798 | Train acc: 50.85% | Val loss: 0.9022 | Val acc: 58.74% | LR: 0.000709
Epoch: 027 | MCC: 0.043983 | Train loss: 0.9789 | Train acc: 51.09% | Val loss: 0.8887 | Val acc: 59.89% | LR: 0.000704
Epoch: 028 | MCC: 0.040252 | Train loss: 0.9805 | Train acc: 51.05% | Val loss: 0.8841 | Val acc: 59.34% | LR: 0.000700
Epoch: 029 | MCC: 0.026690 | Train loss: 0.9774 | Train acc: 51.24% | Val loss: 0.8765 | Val acc: 58.26% | LR: 0.000695
Epoch: 030 | MCC: 0.011138 | Train loss: 0.9760 | Train acc: 51.18% | Val loss: 0.8704 | Val acc: 57.21% | LR: 0.000690
Epoch: 031 | MCC: 0.015585 | Train loss: 0.9754 | Train acc: 51.18% | Val loss: 0.8963 | Val acc: 57.73% | LR: 0.000685
Epoch: 032 | MCC: 0.028346 | Train loss: 0.9744 | Train acc: 51.28% | Val loss: 0.8653 | Val acc: 57.30% | LR: 0.000680
Epoch: 033 | MCC: 0.011496 | Train loss: 0.9758 | Train acc: 51.23% | Val loss: 0.8715 | Val acc: 56.96% | LR: 0.000675
Epoch: 034 | MCC: 0.000691 | Train loss: 0.9746 | Train acc: 51.66% | Val loss: 0.8685 | Val acc: 57.47% | LR: 0.000670
Epoch: 035 | MCC: 0.010899 | Train loss: 0.9711 | Train acc: 51.86% | Val loss: 0.8586 | Val acc: 57.74% | LR: 0.000664
Epoch: 036 | MCC: 0.001331 | Train loss: 0.9705 | Train acc: 51.98% | Val loss: 0.8652 | Val acc: 57.10% | LR: 0.000659
Epoch: 037 | MCC: 0.024850 | Train loss: 0.9692 | Train acc: 52.02% | Val loss: 0.8504 | Val acc: 58.44% | LR: 0.000653
Epoch: 038 | MCC: 0.036065 | Train loss: 0.9743 | Train acc: 51.48% | Val loss: 0.8393 | Val acc: 59.03% | LR: 0.000647
Epoch: 039 | MCC: 0.037950 | Train loss: 0.9706 | Train acc: 51.40% | Val loss: 0.8487 | Val acc: 58.52% | LR: 0.000642
Epoch: 040 | MCC: 0.036682 | Train loss: 0.9717 | Train acc: 51.17% | Val loss: 0.8620 | Val acc: 57.61% | LR: 0.000635
Epoch: 041 | MCC: 0.016076 | Train loss: 0.9711 | Train acc: 51.31% | Val loss: 0.8439 | Val acc: 58.67% | LR: 0.000629
Epoch: 042 | MCC: 0.019838 | Train loss: 0.9696 | Train acc: 51.23% | Val loss: 0.8729 | Val acc: 56.88% | LR: 0.000623
Epoch: 043 | MCC: 0.017051 | Train loss: 0.9709 | Train acc: 51.66% | Val loss: 0.8468 | Val acc: 58.13% | LR: 0.000617
Epoch: 044 | MCC: 0.017114 | Train loss: 0.9689 | Train acc: 51.68% | Val loss: 0.8376 | Val acc: 58.52% | LR: 0.000610
Epoch: 045 | MCC: 0.034458 | Train loss: 0.9699 | Train acc: 52.01% | Val loss: 0.8933 | Val acc: 56.37% | LR: 0.000604
Epoch: 046 | MCC: 0.023009 | Train loss: 0.9711 | Train acc: 51.89% | Val loss: 0.8618 | Val acc: 57.25% | LR: 0.000597
Epoch: 047 | MCC: 0.040416 | Train loss: 0.9695 | Train acc: 51.93% | Val loss: 0.8594 | Val acc: 57.74% | LR: 0.000590
Epoch: 048 | MCC: 0.022383 | Train loss: 0.9678 | Train acc: 52.03% | Val loss: 0.8405 | Val acc: 59.20% | LR: 0.000584
Epoch: 049 | MCC: 0.022810 | Train loss: 0.9653 | Train acc: 52.19% | Val loss: 0.8509 | Val acc: 58.32% | LR: 0.000577
Epoch: 050 | MCC: 0.031329 | Train loss: 0.9669 | Train acc: 52.01% | Val loss: 0.8460 | Val acc: 58.69% | LR: 0.000570
Epoch: 051 | MCC: 0.040451 | Train loss: 0.9659 | Train acc: 52.05% | Val loss: 0.8138 | Val acc: 60.52% | LR: 0.000563
Epoch: 052 | MCC: 0.033737 | Train loss: 0.9668 | Train acc: 51.99% | Val loss: 0.8297 | Val acc: 59.30% | LR: 0.000555
Epoch: 053 | MCC: 0.043954 | Train loss: 0.9653 | Train acc: 52.06% | Val loss: 0.8215 | Val acc: 59.88% | LR: 0.000548
Epoch: 054 | MCC: 0.034190 | Train loss: 0.9665 | Train acc: 52.09% | Val loss: 0.8240 | Val acc: 59.23% | LR: 0.000541
Epoch: 055 | MCC: 0.011807 | Train loss: 0.9727 | Train acc: 52.03% | Val loss: 0.8535 | Val acc: 57.76% | LR: 0.000533
Epoch: 056 | MCC: 0.035427 | Train loss: 0.9627 | Train acc: 52.20% | Val loss: 0.8209 | Val acc: 60.06% | LR: 0.000526
Epoch: 057 | MCC: 0.026407 | Train loss: 0.9662 | Train acc: 51.96% | Val loss: 0.8252 | Val acc: 59.25% | LR: 0.000519
Epoch: 058 | MCC: 0.048604 | Train loss: 0.9656 | Train acc: 52.03% | Val loss: 0.8111 | Val acc: 60.81% | LR: 0.000511
Epoch: 059 | MCC: 0.010970 | Train loss: 0.9629 | Train acc: 52.13% | Val loss: 0.8754 | Val acc: 57.49% | LR: 0.000503
Epoch: 060 | MCC: 0.017703 | Train loss: 0.9645 | Train acc: 52.04% | Val loss: 0.8345 | Val acc: 59.20% | LR: 0.000496
Epoch: 061 | MCC: 0.020421 | Train loss: 0.9618 | Train acc: 52.18% | Val loss: 0.8414 | Val acc: 59.20% | LR: 0.000488
Epoch: 062 | MCC: 0.041280 | Train loss: 0.9634 | Train acc: 52.04% | Val loss: 0.8191 | Val acc: 60.10% | LR: 0.000480
Epoch: 063 | MCC: 0.024919 | Train loss: 0.9629 | Train acc: 52.07% | Val loss: 0.8693 | Val acc: 57.76% | LR: 0.000472
Epoch: 064 | MCC: 0.030632 | Train loss: 0.9633 | Train acc: 52.05% | Val loss: 0.8381 | Val acc: 59.37% | LR: 0.000465
Epoch: 065 | MCC: 0.020256 | Train loss: 0.9633 | Train acc: 52.01% | Val loss: 0.8406 | Val acc: 58.98% | LR: 0.000457
Epoch: 066 | MCC: 0.024345 | Train loss: 0.9627 | Train acc: 51.99% | Val loss: 0.8393 | Val acc: 59.08% | LR: 0.000449
Epoch: 067 | MCC: 0.020888 | Train loss: 0.9596 | Train acc: 52.18% | Val loss: 0.8448 | Val acc: 58.86% | LR: 0.000441
Epoch: 068 | MCC: 0.006204 | Train loss: 0.9624 | Train acc: 52.04% | Val loss: 0.8766 | Val acc: 57.05% | LR: 0.000433
Epoch: 069 | MCC: 0.014872 | Train loss: 0.9617 | Train acc: 52.06% | Val loss: 0.8802 | Val acc: 56.86% | LR: 0.000425
Epoch: 070 | MCC: 0.013691 | Train loss: 0.9605 | Train acc: 52.14% | Val loss: 0.8771 | Val acc: 57.03% | LR: 0.000417
Epoch: 071 | MCC: 0.016493 | Train loss: 0.9606 | Train acc: 52.10% | Val loss: 0.8742 | Val acc: 57.57% | LR: 0.000409
Epoch: 072 | MCC: 0.004412 | Train loss: 0.9615 | Train acc: 52.05% | Val loss: 0.8961 | Val acc: 56.15% | LR: 0.000401
Epoch: 073 | MCC: 0.012713 | Train loss: 0.9618 | Train acc: 52.02% | Val loss: 0.8719 | Val acc: 57.74% | LR: 0.000393
Epoch: 074 | MCC: 0.010680 | Train loss: 0.9589 | Train acc: 52.18% | Val loss: 0.8459 | Val acc: 58.44% | LR: 0.000385
Epoch: 075 | MCC: 0.017353 | Train loss: 0.9611 | Train acc: 52.07% | Val loss: 0.8450 | Val acc: 58.71% | LR: 0.000377
Epoch: 076 | MCC: 0.025145 | Train loss: 0.9598 | Train acc: 52.18% | Val loss: 0.8488 | Val acc: 58.88% | LR: 0.000369
Epoch: 077 | MCC: 0.007337 | Train loss: 0.9623 | Train acc: 51.98% | Val loss: 0.8863 | Val acc: 57.29% | LR: 0.000361
Epoch: 078 | MCC: 0.025658 | Train loss: 0.9633 | Train acc: 52.00% | Val loss: 0.8583 | Val acc: 58.49% | LR: 0.000353
Epoch: 079 | MCC: 0.030569 | Train loss: 0.9591 | Train acc: 52.14% | Val loss: 1.0568 | Val acc: 59.42% | LR: 0.000345
Epoch: 080 | MCC: 0.024231 | Train loss: 0.9574 | Train acc: 52.27% | Val loss: 0.8354 | Val acc: 59.42% | LR: 0.000337
Epoch: 081 | MCC: 0.028711 | Train loss: 0.9622 | Train acc: 51.97% | Val loss: 0.8385 | Val acc: 59.25% | LR: 0.000329
Epoch: 082 | MCC: 0.029390 | Train loss: 0.9608 | Train acc: 52.07% | Val loss: 0.8769 | Val acc: 58.37% | LR: 0.000321
Epoch: 083 | MCC: 0.018200 | Train loss: 0.9599 | Train acc: 52.12% | Val loss: 0.9013 | Val acc: 58.30% | LR: 0.000313
Epoch: 084 | MCC: 0.032316 | Train loss: 0.9578 | Train acc: 52.20% | Val loss: 0.8588 | Val acc: 58.35% | LR: 0.000305
Epoch: 085 | MCC: 0.019724 | Train loss: 0.9575 | Train acc: 52.25% | Val loss: 0.8772 | Val acc: 58.42% | LR: 0.000297
Epoch: 086 | MCC: 0.025704 | Train loss: 0.9678 | Train acc: 52.24% | Val loss: 0.8671 | Val acc: 58.27% | LR: 0.000289
Epoch: 087 | MCC: 0.026032 | Train loss: 0.9607 | Train acc: 52.12% | Val loss: 0.8733 | Val acc: 58.27% | LR: 0.000282
Epoch: 088 | MCC: 0.007975 | Train loss: 0.9584 | Train acc: 52.16% | Val loss: 0.8712 | Val acc: 57.69% | LR: 0.000274
Epoch: 089 | MCC: 0.009140 | Train loss: 0.9578 | Train acc: 52.24% | Val loss: 0.8677 | Val acc: 57.91% | LR: 0.000266
Epoch: 090 | MCC: 0.023965 | Train loss: 0.9593 | Train acc: 52.12% | Val loss: 0.8483 | Val acc: 59.19% | LR: 0.000259
Epoch: 091 | MCC: 0.021960 | Train loss: 0.9587 | Train acc: 52.16% | Val loss: 0.8515 | Val acc: 59.03% | LR: 0.000251
Epoch: 092 | MCC: 0.024902 | Train loss: 0.9587 | Train acc: 52.17% | Val loss: 0.8393 | Val acc: 59.42% | LR: 0.000243
Epoch: 093 | MCC: 0.018387 | Train loss: 0.9557 | Train acc: 52.34% | Val loss: 0.8573 | Val acc: 58.69% | LR: 0.000236
Epoch: 094 | MCC: 0.030125 | Train loss: 0.9575 | Train acc: 52.18% | Val loss: 0.8496 | Val acc: 59.32% | LR: 0.000229
Epoch: 095 | MCC: 0.026230 | Train loss: 0.9585 | Train acc: 52.14% | Val loss: 0.8504 | Val acc: 59.32% | LR: 0.000221
Epoch: 096 | MCC: 0.016529 | Train loss: 0.9587 | Train acc: 52.17% | Val loss: 0.8491 | Val acc: 59.30% | LR: 0.000214
Epoch: 097 | MCC: 0.018452 | Train loss: 0.9570 | Train acc: 52.23% | Val loss: 0.9312 | Val acc: 59.10% | LR: 0.000207
Epoch: 098 | MCC: 0.023767 | Train loss: 0.9550 | Train acc: 52.33% | Val loss: 0.8481 | Val acc: 59.36% | LR: 0.000200
Epoch: 099 | MCC: 0.021754 | Train loss: 0.9572 | Train acc: 52.26% | Val loss: 0.8481 | Val acc: 59.08% | LR: 0.000193
Epoch: 100 | MCC: 0.024998 | Train loss: 0.9573 | Train acc: 52.25% | Val loss: 0.8429 | Val acc: 59.35% | LR: 0.000186
Epoch: 101 | MCC: 0.015259 | Train loss: 0.9580 | Train acc: 52.21% | Val loss: 0.9021 | Val acc: 59.10% | LR: 0.000179
Epoch: 102 | MCC: 0.021284 | Train loss: 0.9578 | Train acc: 52.18% | Val loss: 0.8694 | Val acc: 59.35% | LR: 0.000172
Epoch: 103 | MCC: 0.016393 | Train loss: 0.9590 | Train acc: 52.12% | Val loss: 0.8472 | Val acc: 59.03% | LR: 0.000166
Epoch: 104 | MCC: 0.016045 | Train loss: 0.9803 | Train acc: 52.27% | Val loss: 0.8548 | Val acc: 59.13% | LR: 0.000159
Epoch: 105 | MCC: 0.021255 | Train loss: 0.9714 | Train acc: 52.18% | Val loss: 0.8533 | Val acc: 59.23% | LR: 0.000153
Epoch: 106 | MCC: 0.014157 | Train loss: 0.9578 | Train acc: 52.22% | Val loss: 0.8779 | Val acc: 59.15% | LR: 0.000146
Epoch: 107 | MCC: 0.028111 | Train loss: 0.9574 | Train acc: 52.22% | Val loss: 0.9139 | Val acc: 59.52% | LR: 0.000140
Epoch: 108 | MCC: 0.021147 | Train loss: 0.9560 | Train acc: 52.27% | Val loss: 0.8532 | Val acc: 59.27% | LR: 0.000134
Epoch: 109 | MCC: 0.017240 | Train loss: 0.9573 | Train acc: 52.22% | Val loss: 0.8673 | Val acc: 59.23% | LR: 0.000128
Epoch: 110 | MCC: 0.021751 | Train loss: 0.9548 | Train acc: 52.36% | Val loss: 0.8499 | Val acc: 59.18% | LR: 0.000122
Epoch: 111 | MCC: 0.022924 | Train loss: 0.9644 | Train acc: 52.23% | Val loss: 0.8476 | Val acc: 59.27% | LR: 0.000116
Epoch: 112 | MCC: 0.020762 | Train loss: 0.9588 | Train acc: 52.39% | Val loss: 0.8511 | Val acc: 59.23% | LR: 0.000111
Epoch: 113 | MCC: 0.015977 | Train loss: 0.9591 | Train acc: 52.25% | Val loss: 0.8490 | Val acc: 59.15% | LR: 0.000105
Epoch: 114 | MCC: 0.022758 | Train loss: 0.9609 | Train acc: 52.15% | Val loss: 0.8464 | Val acc: 59.37% | LR: 0.000100
Epoch: 115 | MCC: 0.021937 | Train loss: 0.9578 | Train acc: 52.33% | Val loss: 0.8482 | Val acc: 59.35% | LR: 0.000094
Epoch: 116 | MCC: 0.011124 | Train loss: 0.9569 | Train acc: 52.37% | Val loss: 0.8487 | Val acc: 59.05% | LR: 0.000089
Epoch: 117 | MCC: 0.014808 | Train loss: 0.9577 | Train acc: 52.28% | Val loss: 0.8710 | Val acc: 59.15% | LR: 0.000084
Epoch: 118 | MCC: 0.012719 | Train loss: 0.9581 | Train acc: 52.27% | Val loss: 0.9687 | Val acc: 59.13% | LR: 0.000079
Epoch: 119 | MCC: 0.011962 | Train loss: 0.9575 | Train acc: 52.32% | Val loss: 0.8494 | Val acc: 58.96% | LR: 0.000074
Epoch: 120 | MCC: 0.014621 | Train loss: 0.9578 | Train acc: 52.28% | Val loss: 0.8507 | Val acc: 59.20% | LR: 0.000070
Epoch: 121 | MCC: 0.011072 | Train loss: 0.9588 | Train acc: 52.26% | Val loss: 0.8515 | Val acc: 59.01% | LR: 0.000065
Epoch: 122 | MCC: 0.012192 | Train loss: 0.9546 | Train acc: 52.43% | Val loss: 0.8657 | Val acc: 59.03% | LR: 0.000061
Epoch: 123 | MCC: 0.023765 | Train loss: 0.9569 | Train acc: 52.32% | Val loss: 0.8841 | Val acc: 59.32% | LR: 0.000057
Epoch: 124 | MCC: 0.025596 | Train loss: 0.9580 | Train acc: 52.28% | Val loss: 0.9930 | Val acc: 59.37% | LR: 0.000052
Epoch: 125 | MCC: 0.022645 | Train loss: 0.9620 | Train acc: 52.28% | Val loss: 0.8471 | Val acc: 59.25% | LR: 0.000048
Epoch: 126 | MCC: 0.020612 | Train loss: 0.9623 | Train acc: 52.30% | Val loss: 0.8477 | Val acc: 59.20% | LR: 0.000045
Epoch: 127 | MCC: 0.026538 | Train loss: 0.9592 | Train acc: 52.44% | Val loss: 0.8521 | Val acc: 59.35% | LR: 0.000041
Epoch: 128 | MCC: 0.025698 | Train loss: 0.9612 | Train acc: 52.29% | Val loss: 0.8454 | Val acc: 59.35% | LR: 0.000038
Epoch: 129 | MCC: 0.024817 | Train loss: 0.9634 | Train acc: 52.21% | Val loss: 0.8530 | Val acc: 59.30% | LR: 0.000034
Epoch: 130 | MCC: 0.023007 | Train loss: 0.9607 | Train acc: 52.31% | Val loss: 0.8514 | Val acc: 59.27% | LR: 0.000031
Epoch: 131 | MCC: 0.031280 | Train loss: 0.9606 | Train acc: 52.35% | Val loss: 0.8556 | Val acc: 59.47% | LR: 0.000028
Epoch: 132 | MCC: 0.031280 | Train loss: 0.9579 | Train acc: 52.50% | Val loss: 0.8504 | Val acc: 59.47% | LR: 0.000025

[I 2025-10-05 09:58:49,688] Trial 40 finished with value: 0.02853795699775219 and parameters: {'lr': 0.0007684889068506155, 'hidden_size': 37, 'dropout': 0.14744373570659425, 'weight_decay': 0.007054637996229897}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.032520 | Train loss: 0.9999 | Train acc: 50.24% | Val loss: 1.0108 | Val acc: 45.57% | LR: 0.000585
Epoch: 001 | MCC: 0.022670 | Train loss: 0.9983 | Train acc: 50.68% | Val loss: 1.0118 | Val acc: 45.96% | LR: 0.000584
Epoch: 002 | MCC: 0.025000 | Train loss: 0.9956 | Train acc: 50.85% | Val loss: 1.0145 | Val acc: 45.87% | LR: 0.000584
Epoch: 003 | MCC: 0.036514 | Train loss: 1.1091 | Train acc: 50.58% | Val loss: 1.0097 | Val acc: 46.35% | LR: 0.000584
Epoch: 004 | MCC: 0.055273 | Train loss: 0.9909 | Train acc: 50.73% | Val loss: 1.0114 | Val acc: 47.47% | LR: 0.000583
Epoch: 005 | MCC: 0.046814 | Train loss: 0.9907 | Train acc: 50.64% | Val loss: 1.0126 | Val acc: 47.42% | LR: 0.000582
Epoch: 006 | MCC: 0.031784 | Train loss: 0.9898 | Train acc: 50.65% | Val loss: 1.0024 | Val acc: 47.63% | LR: 0.000582
Epoch: 007 | MCC: 0.049643 | Train loss: 0.9931 | Train acc: 50.61% | Val loss: 0.9992 | Val acc: 49.43% | LR: 0.000581
Epoch: 008 | MCC: 0.037026 | Train loss: 0.9889 | Train acc: 50.79% | Val loss: 1.0005 | Val acc: 47.98% | LR: 0.000579
Epoch: 009 | MCC: 0.046358 | Train loss: 0.9900 | Train acc: 50.64% | Val loss: 0.9984 | Val acc: 49.44% | LR: 0.000578
Epoch: 010 | MCC: 0.057625 | Train loss: 0.9888 | Train acc: 50.77% | Val loss: 0.9960 | Val acc: 51.17% | LR: 0.000577
Epoch: 011 | MCC: 0.056213 | Train loss: 0.9896 | Train acc: 50.76% | Val loss: 0.9944 | Val acc: 51.74% | LR: 0.000575
Epoch: 012 | MCC: 0.053356 | Train loss: 0.9881 | Train acc: 50.84% | Val loss: 0.9929 | Val acc: 52.14% | LR: 0.000574
Epoch: 013 | MCC: 0.041663 | Train loss: 0.9883 | Train acc: 50.84% | Val loss: 0.9895 | Val acc: 52.81% | LR: 0.000572
Epoch: 014 | MCC: 0.039455 | Train loss: 0.9860 | Train acc: 50.75% | Val loss: 0.9800 | Val acc: 53.91% | LR: 0.000570
Epoch: 015 | MCC: 0.042448 | Train loss: 0.9860 | Train acc: 51.00% | Val loss: 0.9751 | Val acc: 54.35% | LR: 0.000568
Epoch: 016 | MCC: 0.040851 | Train loss: 0.9862 | Train acc: 50.90% | Val loss: 0.9683 | Val acc: 54.58% | LR: 0.000566
Epoch: 017 | MCC: 0.031597 | Train loss: 0.9849 | Train acc: 50.99% | Val loss: 0.9625 | Val acc: 54.65% | LR: 0.000564
Epoch: 018 | MCC: 0.028794 | Train loss: 0.9855 | Train acc: 50.96% | Val loss: 0.9572 | Val acc: 54.64% | LR: 0.000562
Epoch: 019 | MCC: 0.038665 | Train loss: 0.9849 | Train acc: 50.93% | Val loss: 0.9479 | Val acc: 55.47% | LR: 0.000559
Epoch: 020 | MCC: 0.030060 | Train loss: 0.9850 | Train acc: 50.83% | Val loss: 0.9403 | Val acc: 55.27% | LR: 0.000557
Epoch: 021 | MCC: 0.029755 | Train loss: 0.9835 | Train acc: 50.94% | Val loss: 0.9324 | Val acc: 55.30% | LR: 0.000554
Epoch: 022 | MCC: 0.027969 | Train loss: 0.9813 | Train acc: 51.04% | Val loss: 0.9208 | Val acc: 55.78% | LR: 0.000551
Epoch: 023 | MCC: 0.029790 | Train loss: 0.9843 | Train acc: 50.88% | Val loss: 0.9159 | Val acc: 55.94% | LR: 0.000549
Epoch: 024 | MCC: 0.033679 | Train loss: 0.9826 | Train acc: 50.96% | Val loss: 0.9102 | Val acc: 56.25% | LR: 0.000546
Epoch: 025 | MCC: 0.033556 | Train loss: 0.9829 | Train acc: 50.94% | Val loss: 0.9023 | Val acc: 56.39% | LR: 0.000542
Epoch: 026 | MCC: 0.035283 | Train loss: 0.9820 | Train acc: 50.98% | Val loss: 0.8999 | Val acc: 56.84% | LR: 0.000539
Epoch: 027 | MCC: 0.027221 | Train loss: 0.9805 | Train acc: 51.01% | Val loss: 0.8966 | Val acc: 56.55% | LR: 0.000536
Epoch: 028 | MCC: 0.026024 | Train loss: 0.9808 | Train acc: 51.02% | Val loss: 0.8902 | Val acc: 56.92% | LR: 0.000532
Epoch: 029 | MCC: 0.035005 | Train loss: 0.9802 | Train acc: 51.04% | Val loss: 0.8870 | Val acc: 57.38% | LR: 0.000529
Epoch: 030 | MCC: 0.040459 | Train loss: 0.9819 | Train acc: 50.89% | Val loss: 0.8815 | Val acc: 57.84% | LR: 0.000525
Epoch: 031 | MCC: 0.031583 | Train loss: 0.9824 | Train acc: 50.92% | Val loss: 0.8806 | Val acc: 58.03% | LR: 0.000522
Epoch: 032 | MCC: 0.059394 | Train loss: 0.9824 | Train acc: 50.97% | Val loss: 0.8757 | Val acc: 59.92% | LR: 0.000518
Epoch: 033 | MCC: 0.047247 | Train loss: 0.9809 | Train acc: 51.21% | Val loss: 0.8659 | Val acc: 59.59% | LR: 0.000514
Epoch: 034 | MCC: 0.027898 | Train loss: 0.9795 | Train acc: 51.28% | Val loss: 0.8708 | Val acc: 59.65% | LR: 0.000510
Epoch: 035 | MCC: 0.033259 | Train loss: 0.9798 | Train acc: 51.14% | Val loss: 0.8539 | Val acc: 58.84% | LR: 0.000506
Epoch: 036 | MCC: 0.038786 | Train loss: 0.9797 | Train acc: 51.07% | Val loss: 0.8654 | Val acc: 57.99% | LR: 0.000501
Epoch: 037 | MCC: 0.034642 | Train loss: 0.9801 | Train acc: 51.30% | Val loss: 0.8751 | Val acc: 58.21% | LR: 0.000497
Epoch: 038 | MCC: 0.026564 | Train loss: 0.9783 | Train acc: 51.18% | Val loss: 0.8561 | Val acc: 58.09% | LR: 0.000493
Epoch: 039 | MCC: 0.030605 | Train loss: 0.9781 | Train acc: 51.30% | Val loss: 0.8390 | Val acc: 59.64% | LR: 0.000488
Epoch: 040 | MCC: 0.017488 | Train loss: 0.9760 | Train acc: 51.47% | Val loss: 0.8454 | Val acc: 58.62% | LR: 0.000483
Epoch: 041 | MCC: 0.038845 | Train loss: 0.9760 | Train acc: 51.26% | Val loss: 0.8640 | Val acc: 57.37% | LR: 0.000479
Epoch: 042 | MCC: 0.026713 | Train loss: 0.9772 | Train acc: 51.29% | Val loss: 0.8656 | Val acc: 57.37% | LR: 0.000474
Epoch: 043 | MCC: 0.021464 | Train loss: 0.9734 | Train acc: 51.39% | Val loss: 0.8605 | Val acc: 57.64% | LR: 0.000469
Epoch: 044 | MCC: 0.021451 | Train loss: 0.9742 | Train acc: 51.38% | Val loss: 0.8474 | Val acc: 58.20% | LR: 0.000464
Epoch: 045 | MCC: 0.043505 | Train loss: 0.9723 | Train acc: 51.45% | Val loss: 0.8627 | Val acc: 57.64% | LR: 0.000459
Epoch: 046 | MCC: -0.000944 | Train loss: 0.9891 | Train acc: 50.59% | Val loss: 0.9586 | Val acc: 52.68% | LR: 0.000454
Epoch: 047 | MCC: 0.013926 | Train loss: 0.9897 | Train acc: 50.51% | Val loss: 0.9492 | Val acc: 53.55% | LR: 0.000449
Epoch: 048 | MCC: 0.032049 | Train loss: 0.9829 | Train acc: 50.87% | Val loss: 0.9052 | Val acc: 55.70% | LR: 0.000444
Epoch: 049 | MCC: 0.032075 | Train loss: 0.9805 | Train acc: 50.98% | Val loss: 0.8815 | Val acc: 56.26% | LR: 0.000439
Epoch: 050 | MCC: 0.000812 | Train loss: 0.9774 | Train acc: 51.17% | Val loss: 0.8965 | Val acc: 55.23% | LR: 0.000433
Epoch: 051 | MCC: 0.014944 | Train loss: 0.9745 | Train acc: 51.28% | Val loss: 0.8418 | Val acc: 58.64% | LR: 0.000428
Epoch: 052 | MCC: 0.028371 | Train loss: 0.9733 | Train acc: 51.32% | Val loss: 0.8349 | Val acc: 58.86% | LR: 0.000423
Epoch: 053 | MCC: 0.027463 | Train loss: 0.9718 | Train acc: 51.40% | Val loss: 0.8557 | Val acc: 57.79% | LR: 0.000417
Epoch: 054 | MCC: 0.002857 | Train loss: 0.9753 | Train acc: 51.20% | Val loss: 0.8736 | Val acc: 56.47% | LR: 0.000412
Epoch: 055 | MCC: 0.010249 | Train loss: 0.9729 | Train acc: 51.32% | Val loss: 0.8479 | Val acc: 57.80% | LR: 0.000406
Epoch: 056 | MCC: 0.049527 | Train loss: 0.9694 | Train acc: 51.51% | Val loss: 0.8459 | Val acc: 58.09% | LR: 0.000400
Epoch: 057 | MCC: 0.041329 | Train loss: 0.9727 | Train acc: 51.30% | Val loss: 0.8335 | Val acc: 58.72% | LR: 0.000395
Epoch: 058 | MCC: 0.024868 | Train loss: 0.9714 | Train acc: 51.38% | Val loss: 0.8465 | Val acc: 57.59% | LR: 0.000389
Epoch: 059 | MCC: 0.054696 | Train loss: 0.9681 | Train acc: 51.62% | Val loss: 0.8355 | Val acc: 58.64% | LR: 0.000383
Epoch: 060 | MCC: 0.017605 | Train loss: 0.9710 | Train acc: 51.36% | Val loss: 0.8503 | Val acc: 57.99% | LR: 0.000377
Epoch: 061 | MCC: 0.020446 | Train loss: 0.9714 | Train acc: 51.38% | Val loss: 0.8649 | Val acc: 57.12% | LR: 0.000371
Epoch: 062 | MCC: 0.040974 | Train loss: 0.9729 | Train acc: 51.27% | Val loss: 0.8572 | Val acc: 57.71% | LR: 0.000365
Epoch: 063 | MCC: 0.029282 | Train loss: 0.9702 | Train acc: 51.44% | Val loss: 0.8367 | Val acc: 58.45% | LR: 0.000359
Epoch: 064 | MCC: 0.018099 | Train loss: 0.9701 | Train acc: 51.44% | Val loss: 0.8716 | Val acc: 56.61% | LR: 0.000353
Epoch: 065 | MCC: 0.030370 | Train loss: 0.9733 | Train acc: 51.23% | Val loss: 0.8520 | Val acc: 57.90% | LR: 0.000347
Epoch: 066 | MCC: 0.039247 | Train loss: 0.9713 | Train acc: 51.35% | Val loss: 0.8532 | Val acc: 57.86% | LR: 0.000341
Epoch: 067 | MCC: 0.037380 | Train loss: 0.9701 | Train acc: 51.41% | Val loss: 0.8566 | Val acc: 57.54% | LR: 0.000335
Epoch: 068 | MCC: 0.051556 | Train loss: 0.9734 | Train acc: 51.27% | Val loss: 0.8577 | Val acc: 57.59% | LR: 0.000329
Epoch: 069 | MCC: 0.039713 | Train loss: 0.9734 | Train acc: 51.26% | Val loss: 0.8401 | Val acc: 58.33% | LR: 0.000323
Epoch: 070 | MCC: 0.031049 | Train loss: 0.9697 | Train acc: 51.42% | Val loss: 0.8388 | Val acc: 58.53% | LR: 0.000317
Epoch: 071 | MCC: 0.050034 | Train loss: 0.9694 | Train acc: 51.45% | Val loss: 0.8621 | Val acc: 57.29% | LR: 0.000311
Epoch: 072 | MCC: 0.025076 | Train loss: 0.9712 | Train acc: 51.30% | Val loss: 0.8392 | Val acc: 58.68% | LR: 0.000305
Epoch: 073 | MCC: 0.050012 | Train loss: 0.9708 | Train acc: 51.36% | Val loss: 0.8199 | Val acc: 59.55% | LR: 0.000299
Epoch: 074 | MCC: 0.075404 | Train loss: 0.9677 | Train acc: 51.51% | Val loss: 0.8233 | Val acc: 59.43% | LR: 0.000293
Epoch: 075 | MCC: 0.026142 | Train loss: 0.9694 | Train acc: 51.35% | Val loss: 0.8558 | Val acc: 57.36% | LR: 0.000287
Epoch: 076 | MCC: 0.013122 | Train loss: 0.9707 | Train acc: 51.36% | Val loss: 0.8658 | Val acc: 56.85% | LR: 0.000281
Epoch: 077 | MCC: 0.023213 | Train loss: 0.9731 | Train acc: 51.19% | Val loss: 0.8751 | Val acc: 56.12% | LR: 0.000274
Epoch: 078 | MCC: 0.031218 | Train loss: 0.9699 | Train acc: 51.40% | Val loss: 0.8546 | Val acc: 57.42% | LR: 0.000268
Epoch: 079 | MCC: 0.028449 | Train loss: 0.9694 | Train acc: 51.42% | Val loss: 0.8456 | Val acc: 58.03% | LR: 0.000262
Epoch: 080 | MCC: 0.051191 | Train loss: 0.9699 | Train acc: 51.31% | Val loss: 0.8449 | Val acc: 58.25% | LR: 0.000256
Epoch: 081 | MCC: 0.034788 | Train loss: 0.9697 | Train acc: 51.38% | Val loss: 0.8562 | Val acc: 57.49% | LR: 0.000250
Epoch: 082 | MCC: 0.035848 | Train loss: 0.9696 | Train acc: 51.41% | Val loss: 0.8557 | Val acc: 57.59% | LR: 0.000244
Epoch: 083 | MCC: 0.037160 | Train loss: 0.9687 | Train acc: 51.36% | Val loss: 0.8477 | Val acc: 57.94% | LR: 0.000238
Epoch: 084 | MCC: 0.046403 | Train loss: 0.9698 | Train acc: 51.37% | Val loss: 0.8534 | Val acc: 57.80% | LR: 0.000232
Epoch: 085 | MCC: 0.049022 | Train loss: 0.9684 | Train acc: 51.44% | Val loss: 0.8342 | Val acc: 58.78% | LR: 0.000226
Epoch: 086 | MCC: 0.050749 | Train loss: 0.9685 | Train acc: 51.49% | Val loss: 0.8315 | Val acc: 58.87% | LR: 0.000220
Epoch: 087 | MCC: 0.043440 | Train loss: 0.9645 | Train acc: 51.67% | Val loss: 0.8370 | Val acc: 58.65% | LR: 0.000214
Epoch: 088 | MCC: 0.038137 | Train loss: 0.9661 | Train acc: 51.57% | Val loss: 0.8367 | Val acc: 58.63% | LR: 0.000208
Epoch: 089 | MCC: 0.046757 | Train loss: 0.9645 | Train acc: 51.63% | Val loss: 0.8380 | Val acc: 58.70% | LR: 0.000203
Epoch: 090 | MCC: 0.045859 | Train loss: 0.9646 | Train acc: 51.61% | Val loss: 0.8423 | Val acc: 58.39% | LR: 0.000197
Epoch: 091 | MCC: 0.037942 | Train loss: 0.9654 | Train acc: 51.56% | Val loss: 0.8371 | Val acc: 58.57% | LR: 0.000191
Epoch: 092 | MCC: 0.040929 | Train loss: 0.9644 | Train acc: 51.55% | Val loss: 0.8371 | Val acc: 58.50% | LR: 0.000185
Epoch: 093 | MCC: 0.059390 | Train loss: 0.9647 | Train acc: 51.63% | Val loss: 0.8341 | Val acc: 58.86% | LR: 0.000180
Epoch: 094 | MCC: 0.041754 | Train loss: 0.9655 | Train acc: 51.61% | Val loss: 0.8366 | Val acc: 58.62% | LR: 0.000174
Epoch: 095 | MCC: 0.057838 | Train loss: 0.9651 | Train acc: 51.49% | Val loss: 0.8254 | Val acc: 59.38% | LR: 0.000169
Epoch: 096 | MCC: 0.050447 | Train loss: 0.9658 | Train acc: 51.54% | Val loss: 0.8300 | Val acc: 58.92% | LR: 0.000163
Epoch: 097 | MCC: 0.040353 | Train loss: 0.9628 | Train acc: 51.65% | Val loss: 0.8340 | Val acc: 58.67% | LR: 0.000158
Epoch: 098 | MCC: 0.040367 | Train loss: 0.9623 | Train acc: 51.61% | Val loss: 0.8279 | Val acc: 58.96% | LR: 0.000152
Epoch: 099 | MCC: 0.050842 | Train loss: 0.9657 | Train acc: 51.73% | Val loss: 0.8328 | Val acc: 59.01% | LR: 0.000147
Epoch: 100 | MCC: 0.034823 | Train loss: 0.9634 | Train acc: 51.71% | Val loss: 0.8415 | Val acc: 58.34% | LR: 0.000142
Epoch: 101 | MCC: 0.038359 | Train loss: 0.9628 | Train acc: 51.59% | Val loss: 0.8350 | Val acc: 58.61% | LR: 0.000136
Epoch: 102 | MCC: 0.038467 | Train loss: 0.9635 | Train acc: 51.71% | Val loss: 0.8312 | Val acc: 58.92% | LR: 0.000131
Epoch: 103 | MCC: 0.035140 | Train loss: 0.9629 | Train acc: 51.78% | Val loss: 0.8303 | Val acc: 58.79% | LR: 0.000126
Epoch: 104 | MCC: 0.044812 | Train loss: 0.9604 | Train acc: 52.18% | Val loss: 0.8323 | Val acc: 58.76% | LR: 0.000121
Epoch: 105 | MCC: 0.037771 | Train loss: 0.9621 | Train acc: 52.48% | Val loss: 0.8290 | Val acc: 58.95% | LR: 0.000116
Epoch: 106 | MCC: 0.043257 | Train loss: 0.9593 | Train acc: 52.61% | Val loss: 0.8302 | Val acc: 59.06% | LR: 0.000112
Epoch: 107 | MCC: 0.046677 | Train loss: 0.9608 | Train acc: 52.26% | Val loss: 0.8328 | Val acc: 58.77% | LR: 0.000107
Epoch: 108 | MCC: 0.037695 | Train loss: 0.9607 | Train acc: 52.48% | Val loss: 0.8321 | Val acc: 58.88% | LR: 0.000102
Epoch: 109 | MCC: 0.041823 | Train loss: 0.9588 | Train acc: 52.58% | Val loss: 0.8335 | Val acc: 58.78% | LR: 0.000098
Epoch: 110 | MCC: 0.037435 | Train loss: 0.9600 | Train acc: 52.44% | Val loss: 0.8325 | Val acc: 58.90% | LR: 0.000093
Epoch: 111 | MCC: 0.045062 | Train loss: 0.9594 | Train acc: 52.51% | Val loss: 0.8339 | Val acc: 58.83% | LR: 0.000089
Epoch: 112 | MCC: 0.050148 | Train loss: 0.9588 | Train acc: 52.45% | Val loss: 0.8331 | Val acc: 58.88% | LR: 0.000084
Epoch: 113 | MCC: 0.037167 | Train loss: 0.9590 | Train acc: 52.46% | Val loss: 0.8348 | Val acc: 58.68% | LR: 0.000080
Epoch: 114 | MCC: 0.053353 | Train loss: 0.9594 | Train acc: 52.41% | Val loss: 0.8289 | Val acc: 59.19% | LR: 0.000076
Epoch: 115 | MCC: 0.049069 | Train loss: 0.9670 | Train acc: 52.55% | Val loss: 0.8296 | Val acc: 59.12% | LR: 0.000072
Epoch: 116 | MCC: 0.049692 | Train loss: 0.9583 | Train acc: 52.54% | Val loss: 0.8358 | Val acc: 58.71% | LR: 0.000068
Epoch: 117 | MCC: 0.037268 | Train loss: 0.9593 | Train acc: 52.52% | Val loss: 0.8307 | Val acc: 58.92% | LR: 0.000064
Epoch: 118 | MCC: 0.045515 | Train loss: 0.9584 | Train acc: 52.49% | Val loss: 0.8332 | Val acc: 58.85% | LR: 0.000060
Epoch: 119 | MCC: 0.048342 | Train loss: 0.9579 | Train acc: 52.54% | Val loss: 0.8322 | Val acc: 59.02% | LR: 0.000057
Epoch: 120 | MCC: 0.048191 | Train loss: 0.9578 | Train acc: 52.53% | Val loss: 0.8337 | Val acc: 58.88% | LR: 0.000053
Epoch: 121 | MCC: 0.040887 | Train loss: 0.9579 | Train acc: 52.61% | Val loss: 0.8329 | Val acc: 58.95% | LR: 0.000050
Epoch: 122 | MCC: 0.046781 | Train loss: 0.9581 | Train acc: 52.51% | Val loss: 0.8336 | Val acc: 58.90% | LR: 0.000046
Epoch: 123 | MCC: 0.049124 | Train loss: 0.9584 | Train acc: 52.45% | Val loss: 0.8320 | Val acc: 59.02% | LR: 0.000043
Epoch: 124 | MCC: 0.049606 | Train loss: 0.9550 | Train acc: 52.70% | Val loss: 0.8327 | Val acc: 59.00% | LR: 0.000040
Epoch: 125 | MCC: 0.043001 | Train loss: 0.9583 | Train acc: 52.45% | Val loss: 0.8338 | Val acc: 58.88% | LR: 0.000037
Epoch: 126 | MCC: 0.047432 | Train loss: 0.9562 | Train acc: 52.56% | Val loss: 0.8316 | Val acc: 58.97% | LR: 0.000034
Epoch: 127 | MCC: 0.058075 | Train loss: 0.9560 | Train acc: 52.64% | Val loss: 0.8322 | Val acc: 59.03% | LR: 0.000031
Epoch: 128 | MCC: 0.048287 | Train loss: 0.9694 | Train acc: 52.66% | Val loss: 0.8323 | Val acc: 58.97% | LR: 0.000029
Epoch: 129 | MCC: 0.048811 | Train loss: 0.9972 | Train acc: 52.60% | Val loss: 0.8321 | Val acc: 59.00% | LR: 0.000026
Epoch: 130 | MCC: 0.047263 | Train loss: 0.9723 | Train acc: 52.60% | Val loss: 0.8318 | Val acc: 58.95% | LR: 0.000024
Epoch: 131 | MCC: 0.049096 | Train loss: 0.9655 | Train acc: 52.59% | Val loss: 0.8318 | Val acc: 59.00% | LR: 0.000021
Epoch: 132 | MCC: 0.062690 | Train loss: 0.9576 | Train acc: 52.59% | Val loss: 0.8324 | Val acc: 59.11% | LR: 0.000019
Epoch: 133 | MCC: 0.058174 | Train loss: 0.9654 | Train acc: 52.60% | Val loss: 0.8324 | Val acc: 59.06% | LR: 0.000017
Epoch: 134 | MCC: 0.047404 | Train loss: 0.9609 | Train acc: 52.57% | Val loss: 0.8324 | Val acc: 58.95% | LR: 0.000015
Epoch: 135 | MCC: 0.047761 | Train loss: 0.9633 | Train acc: 52.64% | Val loss: 0.8320 | Val acc: 58.95% | LR: 0.000013
Epoch: 136 | MCC: 0.048170 | Train loss: 0.9751 | Train acc: 52.61% | Val loss: 0.8323 | Val acc: 59.00% | LR: 0.000012
Epoch: 137 | MCC: 0.048170 | Train loss: 0.9790 | Train acc: 52.60% | Val loss: 0.8324 | Val acc: 59.00% | LR: 0.000010
Epoch: 138 | MCC: 0.048170 | Train loss: 1.1634 | Train acc: 52.69% | Val loss: 0.8324 | Val acc: 59.00% | LR: 0.000009
Epoch: 139 | MCC: 0.047334 | Train loss: 1.6957 | Train acc: 52.61% | Val loss: 0.8324 | Val acc: 58.95% | LR: 0.000007
Epoch: 140 | MCC: 0.047334 | Train loss: 1.0593 | Train acc: 52.58% | Val loss: 0.8324 | Val acc: 58.95% | LR: 0.000006
Epoch: 141 | MCC: 0.047334 | Train loss: 0.9626 | Train acc: 52.62% | Val loss: 0.8323 | Val acc: 58.95% | LR: 0.000005
Epoch: 142 | MCC: 0.047334 | Train loss: 0.9581 | Train acc: 52.71% | Val loss: 0.8321 | Val acc: 58.95% | LR: 0.000004
Epoch: 143 | MCC: 0.047334 | Train loss: 0.9577 | Train acc: 52.68% | Val loss: 0.8320 | Val acc: 58.95% | LR: 0.000003
Epoch: 144 | MCC: 0.047334 | Train loss: 0.9623 | Train acc: 52.62% | Val loss: 0.8321 | Val acc: 58.95% | LR: 0.000003
Epoch: 145 | MCC: 0.047334 | Train loss: 0.9612 | Train acc: 52.66% | Val loss: 0.8321 | Val acc: 58.95% | LR: 0.000002
Epoch: 146 | MCC: 0.047334 | Train loss: 0.9578 | Train acc: 52.68% | Val loss: 0.8321 | Val acc: 58.95% | LR: 0.000002
Epoch: 147 | MCC: 0.047334 | Train loss: 0.9618 | Train acc: 52.57% | Val loss: 0.8321 | Val acc: 58.95% | LR: 0.000001

[I 2025-10-05 10:01:03,619] Trial 41 finished with value: 0.047333579044789076 and parameters: {'lr': 0.0005846361722310465, 'hidden_size': 75, 'dropout': 0.11538537928431307, 'weight_decay': 0.005697552972342883}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.042896 | Train loss: 0.9960 | Train acc: 50.87% | Val loss: 0.9970 | Val acc: 54.18% | LR: 0.000552
Epoch: 001 | MCC: 0.041282 | Train loss: 1.0078 | Train acc: 50.86% | Val loss: 0.9953 | Val acc: 53.89% | LR: 0.000552
Epoch: 002 | MCC: 0.033412 | Train loss: 0.9899 | Train acc: 51.02% | Val loss: 0.9853 | Val acc: 55.09% | LR: 0.000552
Epoch: 003 | MCC: 0.028881 | Train loss: 0.9871 | Train acc: 50.90% | Val loss: 0.9737 | Val acc: 54.74% | LR: 0.000551
Epoch: 004 | MCC: 0.039296 | Train loss: 0.9852 | Train acc: 50.79% | Val loss: 0.9594 | Val acc: 55.57% | LR: 0.000551
Epoch: 005 | MCC: 0.032398 | Train loss: 0.9837 | Train acc: 50.95% | Val loss: 0.9409 | Val acc: 55.81% | LR: 0.000550
Epoch: 006 | MCC: 0.023472 | Train loss: 0.9830 | Train acc: 50.87% | Val loss: 0.9323 | Val acc: 55.81% | LR: 0.000549
Epoch: 007 | MCC: 0.031168 | Train loss: 0.9802 | Train acc: 50.91% | Val loss: 0.9188 | Val acc: 56.33% | LR: 0.000548
Epoch: 008 | MCC: 0.035534 | Train loss: 0.9795 | Train acc: 51.05% | Val loss: 0.9063 | Val acc: 56.45% | LR: 0.000547
Epoch: 009 | MCC: 0.043721 | Train loss: 0.9798 | Train acc: 51.04% | Val loss: 0.8931 | Val acc: 57.82% | LR: 0.000546
Epoch: 010 | MCC: 0.047117 | Train loss: 0.9811 | Train acc: 50.99% | Val loss: 0.8783 | Val acc: 58.25% | LR: 0.000545
Epoch: 011 | MCC: 0.030784 | Train loss: 0.9810 | Train acc: 50.98% | Val loss: 0.8734 | Val acc: 56.90% | LR: 0.000544
Epoch: 012 | MCC: 0.036995 | Train loss: 0.9792 | Train acc: 51.09% | Val loss: 0.8737 | Val acc: 57.27% | LR: 0.000542
Epoch: 013 | MCC: 0.033920 | Train loss: 0.9763 | Train acc: 51.25% | Val loss: 0.8600 | Val acc: 58.03% | LR: 0.000541
Epoch: 014 | MCC: 0.030438 | Train loss: 0.9765 | Train acc: 51.20% | Val loss: 0.8445 | Val acc: 58.98% | LR: 0.000539
Epoch: 015 | MCC: 0.024364 | Train loss: 0.9743 | Train acc: 51.25% | Val loss: 0.8751 | Val acc: 56.88% | LR: 0.000537
Epoch: 016 | MCC: 0.030231 | Train loss: 0.9739 | Train acc: 51.28% | Val loss: 0.8616 | Val acc: 58.59% | LR: 0.000535
Epoch: 017 | MCC: 0.024789 | Train loss: 0.9723 | Train acc: 51.42% | Val loss: 0.8440 | Val acc: 58.64% | LR: 0.000533
Epoch: 018 | MCC: 0.038785 | Train loss: 0.9718 | Train acc: 51.28% | Val loss: 0.8394 | Val acc: 58.96% | LR: 0.000531
Epoch: 019 | MCC: 0.025474 | Train loss: 0.9730 | Train acc: 51.34% | Val loss: 0.8436 | Val acc: 59.10% | LR: 0.000528
Epoch: 020 | MCC: 0.031645 | Train loss: 0.9735 | Train acc: 50.65% | Val loss: 0.8549 | Val acc: 57.59% | LR: 0.000526
Epoch: 021 | MCC: 0.045229 | Train loss: 0.9736 | Train acc: 51.56% | Val loss: 0.8437 | Val acc: 58.38% | LR: 0.000524
Epoch: 022 | MCC: 0.057947 | Train loss: 4.2715 | Train acc: 51.82% | Val loss: 0.8238 | Val acc: 59.38% | LR: 0.000521
Epoch: 023 | MCC: 0.041808 | Train loss: 0.9764 | Train acc: 51.87% | Val loss: 0.8563 | Val acc: 57.38% | LR: 0.000518
Epoch: 024 | MCC: 0.019476 | Train loss: 0.9871 | Train acc: 50.83% | Val loss: 0.9055 | Val acc: 55.49% | LR: 0.000515
Epoch: 025 | MCC: 0.063617 | Train loss: 0.9807 | Train acc: 50.97% | Val loss: 0.8285 | Val acc: 59.19% | LR: 0.000512
Epoch: 026 | MCC: 0.038057 | Train loss: 0.9714 | Train acc: 51.40% | Val loss: 0.8565 | Val acc: 57.48% | LR: 0.000509
Epoch: 027 | MCC: 0.059834 | Train loss: 0.9717 | Train acc: 51.32% | Val loss: 0.8172 | Val acc: 59.56% | LR: 0.000506
Epoch: 028 | MCC: 0.040317 | Train loss: 0.9699 | Train acc: 51.48% | Val loss: 0.8431 | Val acc: 58.23% | LR: 0.000503
Epoch: 029 | MCC: 0.063439 | Train loss: 0.9692 | Train acc: 51.43% | Val loss: 0.8321 | Val acc: 58.87% | LR: 0.000500
Epoch: 030 | MCC: 0.031613 | Train loss: 0.9707 | Train acc: 51.35% | Val loss: 0.8498 | Val acc: 58.03% | LR: 0.000496
Epoch: 031 | MCC: 0.053607 | Train loss: 0.9692 | Train acc: 51.47% | Val loss: 0.8334 | Val acc: 59.15% | LR: 0.000493
Epoch: 032 | MCC: 0.067238 | Train loss: 0.9667 | Train acc: 51.57% | Val loss: 0.8255 | Val acc: 59.15% | LR: 0.000489
Epoch: 033 | MCC: 0.052532 | Train loss: 0.9680 | Train acc: 51.49% | Val loss: 0.8490 | Val acc: 57.85% | LR: 0.000485
Epoch: 034 | MCC: 0.037672 | Train loss: 0.9712 | Train acc: 51.45% | Val loss: 0.8729 | Val acc: 56.73% | LR: 0.000482
Epoch: 035 | MCC: 0.056083 | Train loss: 0.9713 | Train acc: 51.41% | Val loss: 0.8218 | Val acc: 59.70% | LR: 0.000478
Epoch: 036 | MCC: 0.044780 | Train loss: 0.9705 | Train acc: 51.46% | Val loss: 0.8397 | Val acc: 58.48% | LR: 0.000474
Epoch: 037 | MCC: 0.031104 | Train loss: 0.9683 | Train acc: 51.79% | Val loss: 0.8609 | Val acc: 57.59% | LR: 0.000470
Epoch: 038 | MCC: 0.016429 | Train loss: 0.9676 | Train acc: 52.05% | Val loss: 0.8497 | Val acc: 57.99% | LR: 0.000465
Epoch: 039 | MCC: 0.022428 | Train loss: 0.9677 | Train acc: 52.17% | Val loss: 0.8409 | Val acc: 58.16% | LR: 0.000461
Epoch: 040 | MCC: 0.017986 | Train loss: 0.9687 | Train acc: 52.07% | Val loss: 0.8579 | Val acc: 57.28% | LR: 0.000457
Epoch: 041 | MCC: 0.055658 | Train loss: 0.9699 | Train acc: 51.96% | Val loss: 0.8277 | Val acc: 58.86% | LR: 0.000452
Epoch: 042 | MCC: 0.048635 | Train loss: 0.9683 | Train acc: 52.05% | Val loss: 0.8317 | Val acc: 58.86% | LR: 0.000448
Epoch: 043 | MCC: 0.040603 | Train loss: 0.9679 | Train acc: 52.08% | Val loss: 0.8259 | Val acc: 59.12% | LR: 0.000443
Epoch: 044 | MCC: 0.042359 | Train loss: 0.9668 | Train acc: 52.15% | Val loss: 0.8186 | Val acc: 59.57% | LR: 0.000439
Epoch: 045 | MCC: 0.042424 | Train loss: 0.9632 | Train acc: 52.30% | Val loss: 0.8312 | Val acc: 58.81% | LR: 0.000434
Epoch: 046 | MCC: 0.046166 | Train loss: 0.9674 | Train acc: 52.05% | Val loss: 0.8274 | Val acc: 59.08% | LR: 0.000429
Epoch: 047 | MCC: 0.022676 | Train loss: 0.9652 | Train acc: 52.20% | Val loss: 0.8270 | Val acc: 58.95% | LR: 0.000424
Epoch: 048 | MCC: 0.041635 | Train loss: 0.9653 | Train acc: 52.16% | Val loss: 0.8226 | Val acc: 59.27% | LR: 0.000419
Epoch: 049 | MCC: 0.020880 | Train loss: 0.9666 | Train acc: 52.09% | Val loss: 0.8525 | Val acc: 57.66% | LR: 0.000414
Epoch: 050 | MCC: 0.031065 | Train loss: 0.9631 | Train acc: 52.23% | Val loss: 0.8261 | Val acc: 58.95% | LR: 0.000409
Epoch: 051 | MCC: 0.034824 | Train loss: 0.9646 | Train acc: 52.22% | Val loss: 0.8234 | Val acc: 59.03% | LR: 0.000404
Epoch: 052 | MCC: 0.038092 | Train loss: 0.9636 | Train acc: 52.25% | Val loss: 0.8224 | Val acc: 59.16% | LR: 0.000399
Epoch: 053 | MCC: 0.038399 | Train loss: 0.9678 | Train acc: 52.00% | Val loss: 0.8383 | Val acc: 58.12% | LR: 0.000394
Epoch: 054 | MCC: 0.026302 | Train loss: 0.9655 | Train acc: 52.24% | Val loss: 0.8263 | Val acc: 58.94% | LR: 0.000389
Epoch: 055 | MCC: 0.039274 | Train loss: 0.9636 | Train acc: 52.23% | Val loss: 0.8378 | Val acc: 58.87% | LR: 0.000383
Epoch: 056 | MCC: 0.039433 | Train loss: 0.9640 | Train acc: 52.21% | Val loss: 0.8377 | Val acc: 58.57% | LR: 0.000378
Epoch: 057 | MCC: 0.030256 | Train loss: 0.9639 | Train acc: 52.20% | Val loss: 0.8185 | Val acc: 59.45% | LR: 0.000373
Epoch: 058 | MCC: 0.041776 | Train loss: 0.9653 | Train acc: 52.06% | Val loss: 0.8358 | Val acc: 59.15% | LR: 0.000367
Epoch: 059 | MCC: 0.032624 | Train loss: 0.9631 | Train acc: 52.23% | Val loss: 0.8494 | Val acc: 58.46% | LR: 0.000362
Epoch: 060 | MCC: 0.045574 | Train loss: 0.9638 | Train acc: 52.19% | Val loss: 0.8256 | Val acc: 59.03% | LR: 0.000356
Epoch: 061 | MCC: 0.052638 | Train loss: 0.9618 | Train acc: 52.29% | Val loss: 0.8210 | Val acc: 59.37% | LR: 0.000351
Epoch: 062 | MCC: 0.052336 | Train loss: 0.9624 | Train acc: 52.29% | Val loss: 0.8300 | Val acc: 59.00% | LR: 0.000345
Epoch: 063 | MCC: 0.041988 | Train loss: 0.9619 | Train acc: 52.29% | Val loss: 0.8332 | Val acc: 58.71% | LR: 0.000340
Epoch: 064 | MCC: 0.056033 | Train loss: 0.9610 | Train acc: 52.32% | Val loss: 0.8281 | Val acc: 59.02% | LR: 0.000334
Epoch: 065 | MCC: 0.051387 | Train loss: 0.9622 | Train acc: 52.25% | Val loss: 0.8335 | Val acc: 58.84% | LR: 0.000328
Epoch: 066 | MCC: 0.045746 | Train loss: 0.9625 | Train acc: 52.17% | Val loss: 0.8299 | Val acc: 58.77% | LR: 0.000323
Epoch: 067 | MCC: 0.032007 | Train loss: 0.9586 | Train acc: 52.45% | Val loss: 0.8442 | Val acc: 57.98% | LR: 0.000317
Epoch: 068 | MCC: 0.051729 | Train loss: 0.9621 | Train acc: 52.25% | Val loss: 0.8276 | Val acc: 58.97% | LR: 0.000311
Epoch: 069 | MCC: 0.063105 | Train loss: 0.9631 | Train acc: 52.18% | Val loss: 0.8261 | Val acc: 58.97% | LR: 0.000305
Epoch: 070 | MCC: 0.046999 | Train loss: 0.9612 | Train acc: 52.29% | Val loss: 0.8243 | Val acc: 59.10% | LR: 0.000300
Epoch: 071 | MCC: 0.027565 | Train loss: 0.9616 | Train acc: 52.27% | Val loss: 0.8432 | Val acc: 57.86% | LR: 0.000294
Epoch: 072 | MCC: 0.043235 | Train loss: 0.9633 | Train acc: 52.11% | Val loss: 0.8349 | Val acc: 58.49% | LR: 0.000288
Epoch: 073 | MCC: 0.056934 | Train loss: 0.9611 | Train acc: 52.26% | Val loss: 0.8283 | Val acc: 58.97% | LR: 0.000282
Epoch: 074 | MCC: 0.043691 | Train loss: 0.9606 | Train acc: 52.33% | Val loss: 0.8292 | Val acc: 58.90% | LR: 0.000277
Epoch: 075 | MCC: 0.031449 | Train loss: 0.9578 | Train acc: 52.45% | Val loss: 0.8309 | Val acc: 58.61% | LR: 0.000271
Epoch: 076 | MCC: 0.032681 | Train loss: 0.9601 | Train acc: 52.36% | Val loss: 0.8256 | Val acc: 59.05% | LR: 0.000265
Epoch: 077 | MCC: 0.041148 | Train loss: 0.9577 | Train acc: 52.47% | Val loss: 0.8270 | Val acc: 59.02% | LR: 0.000259
Epoch: 078 | MCC: 0.042713 | Train loss: 0.9593 | Train acc: 52.38% | Val loss: 0.8221 | Val acc: 59.13% | LR: 0.000254
Epoch: 079 | MCC: 0.045508 | Train loss: 0.9589 | Train acc: 52.37% | Val loss: 0.8245 | Val acc: 58.94% | LR: 0.000248
Epoch: 080 | MCC: 0.046441 | Train loss: 0.9593 | Train acc: 52.32% | Val loss: 0.8249 | Val acc: 59.06% | LR: 0.000242
Epoch: 081 | MCC: 0.030753 | Train loss: 0.9576 | Train acc: 52.43% | Val loss: 0.8313 | Val acc: 58.73% | LR: 0.000236
Epoch: 082 | MCC: 0.028804 | Train loss: 0.9589 | Train acc: 52.36% | Val loss: 0.8341 | Val acc: 58.65% | LR: 0.000231
Epoch: 083 | MCC: 0.034655 | Train loss: 0.9588 | Train acc: 52.37% | Val loss: 0.8348 | Val acc: 58.80% | LR: 0.000225
Epoch: 084 | MCC: 0.033504 | Train loss: 0.9594 | Train acc: 52.33% | Val loss: 0.8334 | Val acc: 59.13% | LR: 0.000219
Epoch: 085 | MCC: 0.024994 | Train loss: 0.9604 | Train acc: 52.28% | Val loss: 0.8391 | Val acc: 58.39% | LR: 0.000214
Epoch: 086 | MCC: 0.041036 | Train loss: 0.9587 | Train acc: 52.34% | Val loss: 0.8212 | Val acc: 59.35% | LR: 0.000208
Epoch: 087 | MCC: 0.036926 | Train loss: 0.9592 | Train acc: 52.32% | Val loss: 0.8298 | Val acc: 58.95% | LR: 0.000203
Epoch: 088 | MCC: 0.028134 | Train loss: 0.9591 | Train acc: 52.34% | Val loss: 0.8257 | Val acc: 59.10% | LR: 0.000197
Epoch: 089 | MCC: 0.040916 | Train loss: 0.9601 | Train acc: 52.28% | Val loss: 0.8167 | Val acc: 59.28% | LR: 0.000191
Epoch: 090 | MCC: 0.048566 | Train loss: 0.9600 | Train acc: 52.22% | Val loss: 0.8174 | Val acc: 59.66% | LR: 0.000186
Epoch: 091 | MCC: 0.018121 | Train loss: 0.9570 | Train acc: 52.43% | Val loss: 0.8385 | Val acc: 58.27% | LR: 0.000181
Epoch: 092 | MCC: 0.016288 | Train loss: 0.9569 | Train acc: 52.46% | Val loss: 0.8395 | Val acc: 58.24% | LR: 0.000175
Epoch: 093 | MCC: 0.034331 | Train loss: 0.9576 | Train acc: 52.40% | Val loss: 0.8336 | Val acc: 58.66% | LR: 0.000170
Epoch: 094 | MCC: 0.032966 | Train loss: 0.9570 | Train acc: 52.41% | Val loss: 0.8320 | Val acc: 58.73% | LR: 0.000165
Epoch: 095 | MCC: 0.044121 | Train loss: 0.9583 | Train acc: 52.40% | Val loss: 0.8236 | Val acc: 59.11% | LR: 0.000159
Epoch: 096 | MCC: 0.040087 | Train loss: 0.9567 | Train acc: 52.44% | Val loss: 0.8263 | Val acc: 59.11% | LR: 0.000154
Epoch: 097 | MCC: 0.036149 | Train loss: 0.9571 | Train acc: 52.39% | Val loss: 0.8273 | Val acc: 58.89% | LR: 0.000149
Epoch: 098 | MCC: 0.043860 | Train loss: 0.9542 | Train acc: 52.58% | Val loss: 0.8266 | Val acc: 59.03% | LR: 0.000144
Epoch: 099 | MCC: 0.040882 | Train loss: 0.9558 | Train acc: 52.52% | Val loss: 0.8211 | Val acc: 59.44% | LR: 0.000139
Epoch: 100 | MCC: 0.037774 | Train loss: 0.9545 | Train acc: 52.52% | Val loss: 0.8240 | Val acc: 59.06% | LR: 0.000134
Epoch: 101 | MCC: 0.036900 | Train loss: 0.9532 | Train acc: 52.62% | Val loss: 0.8247 | Val acc: 59.20% | LR: 0.000129
Epoch: 102 | MCC: 0.035122 | Train loss: 0.9556 | Train acc: 52.52% | Val loss: 0.8239 | Val acc: 59.15% | LR: 0.000124
Epoch: 103 | MCC: 0.037650 | Train loss: 0.9583 | Train acc: 52.36% | Val loss: 0.8248 | Val acc: 59.01% | LR: 0.000119
Epoch: 104 | MCC: 0.039460 | Train loss: 0.9563 | Train acc: 52.48% | Val loss: 0.8227 | Val acc: 59.19% | LR: 0.000115
Epoch: 105 | MCC: 0.033942 | Train loss: 0.9564 | Train acc: 52.44% | Val loss: 0.8252 | Val acc: 58.93% | LR: 0.000110
Epoch: 106 | MCC: 0.036386 | Train loss: 0.9551 | Train acc: 52.54% | Val loss: 0.8231 | Val acc: 59.12% | LR: 0.000105
Epoch: 107 | MCC: 0.036287 | Train loss: 0.9546 | Train acc: 52.53% | Val loss: 0.8251 | Val acc: 59.11% | LR: 0.000101
Epoch: 108 | MCC: 0.028548 | Train loss: 0.9578 | Train acc: 52.38% | Val loss: 0.8243 | Val acc: 58.97% | LR: 0.000097
Epoch: 109 | MCC: 0.035818 | Train loss: 0.9555 | Train acc: 52.51% | Val loss: 0.8270 | Val acc: 58.90% | LR: 0.000092
Epoch: 110 | MCC: 0.032676 | Train loss: 0.9561 | Train acc: 52.42% | Val loss: 0.8255 | Val acc: 58.95% | LR: 0.000088
Epoch: 111 | MCC: 0.041097 | Train loss: 0.9542 | Train acc: 52.57% | Val loss: 0.8256 | Val acc: 59.14% | LR: 0.000084
Epoch: 112 | MCC: 0.029493 | Train loss: 0.9535 | Train acc: 52.57% | Val loss: 0.8256 | Val acc: 58.99% | LR: 0.000080
Epoch: 113 | MCC: 0.042779 | Train loss: 0.9554 | Train acc: 52.51% | Val loss: 0.8258 | Val acc: 59.17% | LR: 0.000076
Epoch: 114 | MCC: 0.034292 | Train loss: 0.9545 | Train acc: 52.53% | Val loss: 0.8252 | Val acc: 59.01% | LR: 0.000072
Epoch: 115 | MCC: 0.040144 | Train loss: 0.9547 | Train acc: 52.55% | Val loss: 0.8231 | Val acc: 59.14% | LR: 0.000068
Epoch: 116 | MCC: 0.035234 | Train loss: 0.9536 | Train acc: 52.60% | Val loss: 0.8219 | Val acc: 59.07% | LR: 0.000064
Epoch: 117 | MCC: 0.040373 | Train loss: 0.9530 | Train acc: 52.64% | Val loss: 0.8217 | Val acc: 59.21% | LR: 0.000061
Epoch: 118 | MCC: 0.037353 | Train loss: 0.9562 | Train acc: 52.45% | Val loss: 0.8225 | Val acc: 59.19% | LR: 0.000057
Epoch: 119 | MCC: 0.035773 | Train loss: 0.9557 | Train acc: 52.50% | Val loss: 0.8224 | Val acc: 59.13% | LR: 0.000054
Epoch: 120 | MCC: 0.037114 | Train loss: 0.9533 | Train acc: 52.65% | Val loss: 0.8227 | Val acc: 59.18% | LR: 0.000050
Epoch: 121 | MCC: 0.038128 | Train loss: 0.9544 | Train acc: 52.56% | Val loss: 0.8252 | Val acc: 59.00% | LR: 0.000047
Epoch: 122 | MCC: 0.038480 | Train loss: 0.9549 | Train acc: 52.55% | Val loss: 0.8231 | Val acc: 59.17% | LR: 0.000044
Epoch: 123 | MCC: 0.038019 | Train loss: 0.9549 | Train acc: 52.53% | Val loss: 0.8221 | Val acc: 59.22% | LR: 0.000041
Epoch: 124 | MCC: 0.037911 | Train loss: 0.9550 | Train acc: 52.51% | Val loss: 0.8226 | Val acc: 59.15% | LR: 0.000038
Epoch: 125 | MCC: 0.031413 | Train loss: 0.9535 | Train acc: 52.63% | Val loss: 0.8235 | Val acc: 58.93% | LR: 0.000035
Epoch: 126 | MCC: 0.037034 | Train loss: 0.9555 | Train acc: 52.54% | Val loss: 0.8233 | Val acc: 59.12% | LR: 0.000032
Epoch: 127 | MCC: 0.037979 | Train loss: 0.9541 | Train acc: 52.57% | Val loss: 0.8208 | Val acc: 59.23% | LR: 0.000030
Epoch: 128 | MCC: 0.041246 | Train loss: 0.9560 | Train acc: 52.47% | Val loss: 0.8225 | Val acc: 59.32% | LR: 0.000027
Epoch: 129 | MCC: 0.036192 | Train loss: 0.9534 | Train acc: 52.65% | Val loss: 0.8230 | Val acc: 59.09% | LR: 0.000025
Epoch: 130 | MCC: 0.036890 | Train loss: 0.9537 | Train acc: 52.63% | Val loss: 0.8224 | Val acc: 59.14% | LR: 0.000023
Epoch: 131 | MCC: 0.036890 | Train loss: 0.9514 | Train acc: 52.73% | Val loss: 0.8229 | Val acc: 59.14% | LR: 0.000020
Epoch: 132 | MCC: 0.035729 | Train loss: 0.9544 | Train acc: 52.57% | Val loss: 0.8224 | Val acc: 59.07% | LR: 0.000018
Epoch: 133 | MCC: 0.036748 | Train loss: 0.9548 | Train acc: 52.56% | Val loss: 0.8234 | Val acc: 59.16% | LR: 0.000016
Epoch: 134 | MCC: 0.039074 | Train loss: 0.9532 | Train acc: 52.64% | Val loss: 0.8226 | Val acc: 59.22% | LR: 0.000014
Epoch: 135 | MCC: 0.036051 | Train loss: 0.9538 | Train acc: 52.62% | Val loss: 0.8223 | Val acc: 59.12% | LR: 0.000013
Epoch: 136 | MCC: 0.038606 | Train loss: 0.9581 | Train acc: 52.40% | Val loss: 0.8223 | Val acc: 59.23% | LR: 0.000011
Epoch: 137 | MCC: 0.035054 | Train loss: 0.9523 | Train acc: 52.68% | Val loss: 0.8223 | Val acc: 59.03% | LR: 0.000010
Epoch: 138 | MCC: 0.034476 | Train loss: 0.9539 | Train acc: 52.62% | Val loss: 0.8227 | Val acc: 59.03% | LR: 0.000008
Epoch: 139 | MCC: 0.034476 | Train loss: 0.9534 | Train acc: 52.58% | Val loss: 0.8227 | Val acc: 59.03% | LR: 0.000007
Epoch: 140 | MCC: 0.035526 | Train loss: 0.9540 | Train acc: 52.59% | Val loss: 0.8227 | Val acc: 59.08% | LR: 0.000006
Epoch: 141 | MCC: 0.034796 | Train loss: 0.9559 | Train acc: 52.49% | Val loss: 0.8223 | Val acc: 59.07% | LR: 0.000005
Epoch: 142 | MCC: 0.035526 | Train loss: 0.9535 | Train acc: 52.62% | Val loss: 0.8227 | Val acc: 59.08% | LR: 0.000004
Epoch: 143 | MCC: 0.033221 | Train loss: 0.9536 | Train acc: 52.56% | Val loss: 0.8226 | Val acc: 58.99% | LR: 0.000003
Epoch: 144 | MCC: 0.034476 | Train loss: 0.9526 | Train acc: 52.66% | Val loss: 0.8227 | Val acc: 59.03% | LR: 0.000003
Epoch: 145 | MCC: 0.034932 | Train loss: 0.9549 | Train acc: 52.55% | Val loss: 0.8228 | Val acc: 59.06% | LR: 0.000002
Epoch: 146 | MCC: 0.034932 | Train loss: 0.9543 | Train acc: 52.60% | Val loss: 0.8228 | Val acc: 59.06% | LR: 0.000002
Epoch: 147 | MCC: 0.034932 | Train loss: 0.9531 | Train acc: 52.60% | Val loss: 0.8229 | Val acc: 59.06% | LR: 0.000001
Epoch: 148 | MCC: 0.034932 | Train loss: 0.9544 | Train acc: 52.56% | Val loss: 0.8230 | Val acc: 59.06% | LR: 0.000001
Epoch: 149 | MCC: 0.034932 | Train loss: 0.9529 | Train acc: 52.62% | Val loss: 0.8230 | Val acc: 59.06% | LR: 0.000001

[I 2025-10-05 10:03:15,857] Trial 42 finished with value: 0.03493190015433356 and parameters: {'lr': 0.0005523266135068981, 'hidden_size': 70, 'dropout': 0.07137848706508453, 'weight_decay': 0.018639894141338213}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: -0.002072 | Train loss: 1.0037 | Train acc: 49.87% | Val loss: 0.9771 | Val acc: 53.01% | LR: 0.000970
Epoch: 001 | MCC: -0.007382 | Train loss: 0.9999 | Train acc: 49.81% | Val loss: 0.9671 | Val acc: 53.65% | LR: 0.000970
Epoch: 002 | MCC: 0.026152 | Train loss: 0.9967 | Train acc: 50.65% | Val loss: 0.9681 | Val acc: 54.43% | LR: 0.000969
Epoch: 003 | MCC: 0.004482 | Train loss: 0.9902 | Train acc: 51.05% | Val loss: 1.0611 | Val acc: 55.58% | LR: 0.000969
Epoch: 004 | MCC: 0.012488 | Train loss: 0.9872 | Train acc: 51.04% | Val loss: 0.9366 | Val acc: 54.70% | LR: 0.000968
Epoch: 005 | MCC: 0.009644 | Train loss: 0.9845 | Train acc: 51.05% | Val loss: 0.9391 | Val acc: 54.79% | LR: 0.000966
Epoch: 006 | MCC: 0.003989 | Train loss: 0.9858 | Train acc: 50.89% | Val loss: 0.9295 | Val acc: 54.69% | LR: 0.000965
Epoch: 007 | MCC: -0.002077 | Train loss: 0.9900 | Train acc: 50.59% | Val loss: 0.9239 | Val acc: 55.19% | LR: 0.000963
Epoch: 008 | MCC: 0.007643 | Train loss: 0.9857 | Train acc: 50.87% | Val loss: 0.9278 | Val acc: 55.28% | LR: 0.000962
Epoch: 009 | MCC: -0.006195 | Train loss: 0.9859 | Train acc: 50.89% | Val loss: 0.9217 | Val acc: 54.87% | LR: 0.000960
Epoch: 010 | MCC: -0.009641 | Train loss: 0.9864 | Train acc: 50.95% | Val loss: 0.9192 | Val acc: 54.95% | LR: 0.000957
Epoch: 011 | MCC: 0.005221 | Train loss: 0.9861 | Train acc: 50.93% | Val loss: 0.9155 | Val acc: 54.68% | LR: 0.000955
Epoch: 012 | MCC: 0.013481 | Train loss: 0.9904 | Train acc: 50.88% | Val loss: 0.9132 | Val acc: 55.26% | LR: 0.000952
Epoch: 013 | MCC: 0.012739 | Train loss: 0.9839 | Train acc: 51.06% | Val loss: 0.9132 | Val acc: 55.22% | LR: 0.000950
Epoch: 014 | MCC: -0.006338 | Train loss: 0.9818 | Train acc: 51.04% | Val loss: 0.9060 | Val acc: 55.29% | LR: 0.000947
Epoch: 015 | MCC: 0.004035 | Train loss: 0.9980 | Train acc: 51.06% | Val loss: 0.9065 | Val acc: 55.56% | LR: 0.000943
Epoch: 016 | MCC: -0.000945 | Train loss: 0.9886 | Train acc: 51.21% | Val loss: 0.9016 | Val acc: 55.53% | LR: 0.000940
Epoch: 017 | MCC: 0.004172 | Train loss: 0.9874 | Train acc: 51.05% | Val loss: 0.8965 | Val acc: 55.86% | LR: 0.000936
Epoch: 018 | MCC: -0.005640 | Train loss: 0.9807 | Train acc: 51.20% | Val loss: 0.8933 | Val acc: 55.61% | LR: 0.000932
Epoch: 019 | MCC: -0.006072 | Train loss: 0.9805 | Train acc: 51.03% | Val loss: 0.8879 | Val acc: 55.68% | LR: 0.000928
Epoch: 020 | MCC: -0.009958 | Train loss: 0.9794 | Train acc: 51.02% | Val loss: 0.8838 | Val acc: 55.69% | LR: 0.000924
Epoch: 021 | MCC: -0.005488 | Train loss: 0.9780 | Train acc: 51.10% | Val loss: 0.8944 | Val acc: 55.12% | LR: 0.000920
Epoch: 022 | MCC: -0.002395 | Train loss: 0.9756 | Train acc: 51.25% | Val loss: 0.8868 | Val acc: 55.37% | LR: 0.000915
Epoch: 023 | MCC: 0.001970 | Train loss: 0.9761 | Train acc: 51.23% | Val loss: 0.8761 | Val acc: 55.86% | LR: 0.000910
Epoch: 024 | MCC: 0.025653 | Train loss: 0.9782 | Train acc: 51.05% | Val loss: 0.8764 | Val acc: 56.39% | LR: 0.000905
Epoch: 025 | MCC: 0.012519 | Train loss: 0.9751 | Train acc: 51.30% | Val loss: 0.8853 | Val acc: 55.59% | LR: 0.000900
Epoch: 026 | MCC: -0.001614 | Train loss: 0.9752 | Train acc: 51.22% | Val loss: 0.8723 | Val acc: 56.44% | LR: 0.000895
Epoch: 027 | MCC: -0.000104 | Train loss: 0.9757 | Train acc: 51.15% | Val loss: 0.8706 | Val acc: 56.68% | LR: 0.000889
Epoch: 028 | MCC: -0.015204 | Train loss: 0.9740 | Train acc: 51.26% | Val loss: 0.8852 | Val acc: 55.39% | LR: 0.000884
Epoch: 029 | MCC: -0.003940 | Train loss: 0.9735 | Train acc: 51.37% | Val loss: 0.8764 | Val acc: 56.17% | LR: 0.000878
Epoch: 030 | MCC: -0.010476 | Train loss: 0.9747 | Train acc: 51.18% | Val loss: 0.8919 | Val acc: 55.19% | LR: 0.000872
Epoch: 031 | MCC: 0.003933 | Train loss: 0.9728 | Train acc: 51.31% | Val loss: 0.8679 | Val acc: 56.61% | LR: 0.000865
Epoch: 032 | MCC: -0.007052 | Train loss: 0.9757 | Train acc: 51.11% | Val loss: 0.8790 | Val acc: 55.85% | LR: 0.000859
Epoch: 033 | MCC: -0.014813 | Train loss: 0.9730 | Train acc: 51.34% | Val loss: 0.8914 | Val acc: 55.17% | LR: 0.000852
Epoch: 034 | MCC: 0.004511 | Train loss: 0.9738 | Train acc: 51.19% | Val loss: 0.8983 | Val acc: 55.34% | LR: 0.000846
Epoch: 035 | MCC: -0.002254 | Train loss: 0.9724 | Train acc: 51.25% | Val loss: 0.8741 | Val acc: 56.29% | LR: 0.000839
Epoch: 036 | MCC: 0.009692 | Train loss: 0.9731 | Train acc: 51.27% | Val loss: 0.8986 | Val acc: 55.20% | LR: 0.000832
Epoch: 037 | MCC: -0.007823 | Train loss: 0.9768 | Train acc: 51.04% | Val loss: 0.8793 | Val acc: 55.62% | LR: 0.000825
Epoch: 038 | MCC: 0.000285 | Train loss: 0.9718 | Train acc: 51.38% | Val loss: 0.8845 | Val acc: 56.11% | LR: 0.000817
Epoch: 039 | MCC: 0.001366 | Train loss: 0.9738 | Train acc: 51.23% | Val loss: 0.8863 | Val acc: 55.78% | LR: 0.000810
Epoch: 040 | MCC: 0.000486 | Train loss: 0.9735 | Train acc: 51.26% | Val loss: 0.8845 | Val acc: 55.69% | LR: 0.000802
Epoch: 041 | MCC: -0.003822 | Train loss: 0.9738 | Train acc: 51.18% | Val loss: 0.8774 | Val acc: 55.90% | LR: 0.000795
Epoch: 042 | MCC: -0.001767 | Train loss: 0.9703 | Train acc: 51.44% | Val loss: 0.8778 | Val acc: 56.51% | LR: 0.000787
Epoch: 043 | MCC: -0.008433 | Train loss: 0.9728 | Train acc: 51.18% | Val loss: 0.8625 | Val acc: 57.28% | LR: 0.000779
Epoch: 044 | MCC: -0.013263 | Train loss: 0.9722 | Train acc: 51.22% | Val loss: 0.8634 | Val acc: 57.01% | LR: 0.000770
Epoch: 045 | MCC: -0.004902 | Train loss: 0.9720 | Train acc: 51.22% | Val loss: 0.8708 | Val acc: 56.44% | LR: 0.000762
Epoch: 046 | MCC: -0.003180 | Train loss: 0.9712 | Train acc: 51.39% | Val loss: 0.8716 | Val acc: 56.56% | LR: 0.000754
Epoch: 047 | MCC: -0.008300 | Train loss: 0.9716 | Train acc: 51.23% | Val loss: 0.8851 | Val acc: 55.83% | LR: 0.000745
Epoch: 048 | MCC: -0.006375 | Train loss: 0.9719 | Train acc: 51.27% | Val loss: 0.8745 | Val acc: 56.02% | LR: 0.000737
Epoch: 049 | MCC: -0.012073 | Train loss: 0.9705 | Train acc: 51.59% | Val loss: 0.8818 | Val acc: 55.56% | LR: 0.000728
Epoch: 050 | MCC: -0.011173 | Train loss: 0.9713 | Train acc: 51.50% | Val loss: 0.8810 | Val acc: 55.95% | LR: 0.000719
Epoch: 051 | MCC: -0.010078 | Train loss: 0.9708 | Train acc: 51.71% | Val loss: 0.8871 | Val acc: 55.61% | LR: 0.000710
Epoch: 052 | MCC: -0.006859 | Train loss: 0.9693 | Train acc: 51.87% | Val loss: 0.8872 | Val acc: 55.70% | LR: 0.000701
Epoch: 053 | MCC: -0.002222 | Train loss: 0.9751 | Train acc: 51.58% | Val loss: 0.8871 | Val acc: 55.32% | LR: 0.000692
Epoch: 054 | MCC: 0.004795 | Train loss: 0.9704 | Train acc: 51.30% | Val loss: 0.8922 | Val acc: 55.78% | LR: 0.000683
Epoch: 055 | MCC: 0.007718 | Train loss: 0.9691 | Train acc: 51.54% | Val loss: 0.8790 | Val acc: 56.64% | LR: 0.000673
Epoch: 056 | MCC: 0.002033 | Train loss: 0.9693 | Train acc: 51.45% | Val loss: 0.8836 | Val acc: 56.13% | LR: 0.000664
Epoch: 057 | MCC: -0.005485 | Train loss: 0.9693 | Train acc: 51.99% | Val loss: 0.8818 | Val acc: 56.53% | LR: 0.000655
Epoch: 058 | MCC: 0.007084 | Train loss: 0.9709 | Train acc: 51.97% | Val loss: 0.8755 | Val acc: 56.34% | LR: 0.000645
Epoch: 059 | MCC: -0.011187 | Train loss: 0.9690 | Train acc: 52.05% | Val loss: 0.8695 | Val acc: 56.74% | LR: 0.000635
Epoch: 060 | MCC: 0.001514 | Train loss: 0.9687 | Train acc: 51.99% | Val loss: 0.8683 | Val acc: 56.78% | LR: 0.000626
Epoch: 061 | MCC: -0.001669 | Train loss: 0.9684 | Train acc: 51.93% | Val loss: 0.8758 | Val acc: 56.69% | LR: 0.000616
Epoch: 062 | MCC: -0.010705 | Train loss: 0.9687 | Train acc: 52.04% | Val loss: 0.8776 | Val acc: 56.52% | LR: 0.000606
Epoch: 063 | MCC: -0.005482 | Train loss: 0.9686 | Train acc: 52.08% | Val loss: 0.8813 | Val acc: 56.15% | LR: 0.000596
Epoch: 064 | MCC: 0.002271 | Train loss: 0.9678 | Train acc: 52.05% | Val loss: 0.8853 | Val acc: 56.30% | LR: 0.000586
Epoch: 065 | MCC: 0.002272 | Train loss: 0.9686 | Train acc: 52.01% | Val loss: 0.8698 | Val acc: 57.05% | LR: 0.000576
Epoch: 066 | MCC: 0.006512 | Train loss: 0.9682 | Train acc: 52.10% | Val loss: 0.8794 | Val acc: 56.34% | LR: 0.000566
Epoch: 067 | MCC: -0.004878 | Train loss: 0.9681 | Train acc: 52.09% | Val loss: 0.8719 | Val acc: 56.56% | LR: 0.000556
Epoch: 068 | MCC: 0.000134 | Train loss: 0.9691 | Train acc: 52.03% | Val loss: 0.8749 | Val acc: 56.54% | LR: 0.000546
Epoch: 069 | MCC: 0.001882 | Train loss: 0.9688 | Train acc: 52.05% | Val loss: 0.8771 | Val acc: 56.44% | LR: 0.000536
Epoch: 070 | MCC: -0.002634 | Train loss: 0.9676 | Train acc: 52.03% | Val loss: 0.8798 | Val acc: 56.13% | LR: 0.000526
Epoch: 071 | MCC: 0.002319 | Train loss: 0.9668 | Train acc: 52.17% | Val loss: 0.8796 | Val acc: 56.22% | LR: 0.000516
Epoch: 072 | MCC: 0.003476 | Train loss: 0.9683 | Train acc: 52.00% | Val loss: 0.8763 | Val acc: 56.56% | LR: 0.000506
Epoch: 073 | MCC: 0.004222 | Train loss: 0.9674 | Train acc: 52.00% | Val loss: 0.8729 | Val acc: 56.54% | LR: 0.000496
Epoch: 074 | MCC: 0.010124 | Train loss: 0.9663 | Train acc: 52.07% | Val loss: 0.8702 | Val acc: 57.00% | LR: 0.000486
Epoch: 075 | MCC: 0.005112 | Train loss: 0.9657 | Train acc: 52.16% | Val loss: 0.8700 | Val acc: 57.05% | LR: 0.000475
Epoch: 076 | MCC: 0.007939 | Train loss: 0.9661 | Train acc: 52.07% | Val loss: 0.8753 | Val acc: 56.76% | LR: 0.000465
Epoch: 077 | MCC: 0.018722 | Train loss: 0.9654 | Train acc: 52.19% | Val loss: 0.8710 | Val acc: 57.22% | LR: 0.000455
Epoch: 078 | MCC: -0.002261 | Train loss: 0.9655 | Train acc: 52.16% | Val loss: 0.8720 | Val acc: 56.96% | LR: 0.000445
Epoch: 079 | MCC: 0.006000 | Train loss: 0.9650 | Train acc: 52.22% | Val loss: 0.8663 | Val acc: 57.35% | LR: 0.000435
Epoch: 080 | MCC: -0.002738 | Train loss: 0.9649 | Train acc: 52.19% | Val loss: 0.8770 | Val acc: 56.78% | LR: 0.000425
Epoch: 081 | MCC: 0.002068 | Train loss: 0.9663 | Train acc: 52.12% | Val loss: 0.8820 | Val acc: 56.49% | LR: 0.000415
Epoch: 082 | MCC: 0.007450 | Train loss: 0.9657 | Train acc: 52.13% | Val loss: 0.8708 | Val acc: 57.17% | LR: 0.000405
Epoch: 083 | MCC: 0.008999 | Train loss: 0.9635 | Train acc: 52.29% | Val loss: 0.8623 | Val acc: 57.79% | LR: 0.000395
Epoch: 084 | MCC: 0.017256 | Train loss: 0.9641 | Train acc: 52.26% | Val loss: 0.8662 | Val acc: 57.76% | LR: 0.000385
Epoch: 085 | MCC: -0.007181 | Train loss: 0.9639 | Train acc: 52.22% | Val loss: 0.8672 | Val acc: 57.61% | LR: 0.000375
Epoch: 086 | MCC: 0.017565 | Train loss: 0.9655 | Train acc: 52.17% | Val loss: 0.8752 | Val acc: 57.66% | LR: 0.000365
Epoch: 087 | MCC: 0.005334 | Train loss: 0.9631 | Train acc: 52.30% | Val loss: 0.8794 | Val acc: 57.20% | LR: 0.000355
Epoch: 088 | MCC: 0.006944 | Train loss: 0.9631 | Train acc: 52.29% | Val loss: 0.8839 | Val acc: 56.93% | LR: 0.000346
Epoch: 089 | MCC: 0.042305 | Train loss: 0.9632 | Train acc: 52.29% | Val loss: 0.8655 | Val acc: 58.04% | LR: 0.000336
Epoch: 090 | MCC: 0.018930 | Train loss: 0.9643 | Train acc: 52.14% | Val loss: 0.8723 | Val acc: 57.79% | LR: 0.000326
Epoch: 091 | MCC: 0.032671 | Train loss: 0.9620 | Train acc: 52.32% | Val loss: 0.8724 | Val acc: 57.53% | LR: 0.000317
Epoch: 092 | MCC: 0.013613 | Train loss: 0.9598 | Train acc: 52.48% | Val loss: 0.8801 | Val acc: 57.27% | LR: 0.000307
Epoch: 093 | MCC: 0.054340 | Train loss: 0.9609 | Train acc: 52.37% | Val loss: 0.8692 | Val acc: 57.84% | LR: 0.000298
Epoch: 094 | MCC: 0.046257 | Train loss: 0.9614 | Train acc: 52.37% | Val loss: 0.8607 | Val acc: 58.24% | LR: 0.000289
Epoch: 095 | MCC: 0.045642 | Train loss: 0.9614 | Train acc: 52.30% | Val loss: 0.8844 | Val acc: 57.21% | LR: 0.000279
Epoch: 096 | MCC: 0.017866 | Train loss: 0.9585 | Train acc: 52.47% | Val loss: 0.8755 | Val acc: 57.79% | LR: 0.000270
Epoch: 097 | MCC: 0.017137 | Train loss: 0.9575 | Train acc: 52.57% | Val loss: 0.8854 | Val acc: 57.30% | LR: 0.000261
Epoch: 098 | MCC: 0.049224 | Train loss: 0.9593 | Train acc: 52.46% | Val loss: 0.8603 | Val acc: 58.67% | LR: 0.000252
Epoch: 099 | MCC: 0.012916 | Train loss: 0.9601 | Train acc: 52.33% | Val loss: 0.8801 | Val acc: 57.66% | LR: 0.000243
Epoch: 100 | MCC: 0.050570 | Train loss: 0.9564 | Train acc: 52.55% | Val loss: 0.8758 | Val acc: 57.97% | LR: 0.000235
Epoch: 101 | MCC: 0.013584 | Train loss: 0.9579 | Train acc: 52.50% | Val loss: 0.8800 | Val acc: 57.74% | LR: 0.000226
Epoch: 102 | MCC: 0.052680 | Train loss: 0.9563 | Train acc: 52.59% | Val loss: 0.8795 | Val acc: 57.84% | LR: 0.000217
Epoch: 103 | MCC: 0.068744 | Train loss: 0.9579 | Train acc: 52.51% | Val loss: 0.8713 | Val acc: 58.47% | LR: 0.000209
Epoch: 104 | MCC: 0.055074 | Train loss: 0.9548 | Train acc: 52.67% | Val loss: 0.8771 | Val acc: 57.77% | LR: 0.000201
Epoch: 105 | MCC: 0.017162 | Train loss: 0.9581 | Train acc: 52.63% | Val loss: 0.8806 | Val acc: 57.64% | LR: 0.000193
Epoch: 106 | MCC: 0.056523 | Train loss: 0.9556 | Train acc: 52.61% | Val loss: 0.8781 | Val acc: 57.67% | LR: 0.000185
Epoch: 107 | MCC: 0.051497 | Train loss: 0.9546 | Train acc: 52.66% | Val loss: 0.8822 | Val acc: 57.87% | LR: 0.000177
Epoch: 108 | MCC: 0.059945 | Train loss: 0.9543 | Train acc: 52.67% | Val loss: 0.8832 | Val acc: 57.97% | LR: 0.000169
Epoch: 109 | MCC: 0.053941 | Train loss: 0.9563 | Train acc: 52.59% | Val loss: 0.8788 | Val acc: 58.04% | LR: 0.000161
Epoch: 110 | MCC: 0.060057 | Train loss: 0.9567 | Train acc: 52.55% | Val loss: 0.8805 | Val acc: 58.21% | LR: 0.000154
Epoch: 111 | MCC: 0.007514 | Train loss: 0.9569 | Train acc: 52.54% | Val loss: 0.8828 | Val acc: 57.53% | LR: 0.000147
Epoch: 112 | MCC: 0.055096 | Train loss: 0.9559 | Train acc: 52.56% | Val loss: 0.8880 | Val acc: 57.77% | LR: 0.000139
Epoch: 113 | MCC: 0.077851 | Train loss: 0.9557 | Train acc: 52.60% | Val loss: 0.8773 | Val acc: 58.50% | LR: 0.000132
Epoch: 114 | MCC: 0.066222 | Train loss: 0.9553 | Train acc: 52.60% | Val loss: 0.8847 | Val acc: 58.05% | LR: 0.000125
Epoch: 115 | MCC: 0.079505 | Train loss: 0.9550 | Train acc: 52.62% | Val loss: 0.8826 | Val acc: 58.30% | LR: 0.000119
Epoch: 116 | MCC: 0.077794 | Train loss: 0.9539 | Train acc: 52.66% | Val loss: 0.8815 | Val acc: 58.26% | LR: 0.000112
Epoch: 117 | MCC: 0.057234 | Train loss: 0.9560 | Train acc: 52.60% | Val loss: 0.8795 | Val acc: 58.04% | LR: 0.000106
Epoch: 118 | MCC: 0.046235 | Train loss: 0.9526 | Train acc: 52.81% | Val loss: 0.8840 | Val acc: 57.92% | LR: 0.000100
Epoch: 119 | MCC: 0.044581 | Train loss: 0.9536 | Train acc: 52.70% | Val loss: 0.8834 | Val acc: 57.82% | LR: 0.000094
Epoch: 120 | MCC: 0.060368 | Train loss: 0.9550 | Train acc: 52.63% | Val loss: 0.8819 | Val acc: 57.97% | LR: 0.000088
Epoch: 121 | MCC: 0.044500 | Train loss: 0.9528 | Train acc: 52.72% | Val loss: 0.8822 | Val acc: 57.78% | LR: 0.000082
Epoch: 122 | MCC: 0.047979 | Train loss: 0.9542 | Train acc: 52.68% | Val loss: 0.8846 | Val acc: 57.71% | LR: 0.000076
Epoch: 123 | MCC: 0.031778 | Train loss: 0.9523 | Train acc: 52.80% | Val loss: 0.8833 | Val acc: 57.46% | LR: 0.000071
Epoch: 124 | MCC: 0.034569 | Train loss: 0.9545 | Train acc: 52.61% | Val loss: 0.8848 | Val acc: 57.49% | LR: 0.000066
Epoch: 125 | MCC: 0.031965 | Train loss: 0.9526 | Train acc: 52.78% | Val loss: 0.8841 | Val acc: 57.39% | LR: 0.000061
Epoch: 126 | MCC: 0.027089 | Train loss: 0.9543 | Train acc: 52.64% | Val loss: 0.8853 | Val acc: 57.29% | LR: 0.000056
Epoch: 127 | MCC: 0.024046 | Train loss: 0.9510 | Train acc: 52.77% | Val loss: 0.8851 | Val acc: 57.15% | LR: 0.000052
Epoch: 128 | MCC: 0.036791 | Train loss: 0.9985 | Train acc: 52.72% | Val loss: 0.8831 | Val acc: 57.56% | LR: 0.000047
Epoch: 129 | MCC: 0.025198 | Train loss: 0.9527 | Train acc: 52.78% | Val loss: 0.8850 | Val acc: 57.22% | LR: 0.000043
Epoch: 130 | MCC: 0.025356 | Train loss: 0.9544 | Train acc: 52.65% | Val loss: 0.8858 | Val acc: 57.22% | LR: 0.000039
Epoch: 131 | MCC: 0.025507 | Train loss: 0.9514 | Train acc: 52.79% | Val loss: 0.8846 | Val acc: 57.27% | LR: 0.000035
Epoch: 132 | MCC: 0.023709 | Train loss: 0.9525 | Train acc: 52.73% | Val loss: 0.8843 | Val acc: 57.25% | LR: 0.000031
Epoch: 133 | MCC: 0.022826 | Train loss: 0.9532 | Train acc: 52.69% | Val loss: 0.8840 | Val acc: 57.15% | LR: 0.000028
Epoch: 134 | MCC: 0.020702 | Train loss: 0.9533 | Train acc: 52.69% | Val loss: 0.8850 | Val acc: 57.10% | LR: 0.000025
Epoch: 135 | MCC: 0.024300 | Train loss: 0.9517 | Train acc: 52.80% | Val loss: 0.8846 | Val acc: 57.22% | LR: 0.000022
Epoch: 136 | MCC: 0.022049 | Train loss: 0.9529 | Train acc: 52.68% | Val loss: 0.8847 | Val acc: 57.15% | LR: 0.000019
Epoch: 137 | MCC: 0.022244 | Train loss: 0.9530 | Train acc: 52.73% | Val loss: 0.8850 | Val acc: 57.17% | LR: 0.000016
Epoch: 138 | MCC: 0.022268 | Train loss: 0.9524 | Train acc: 52.78% | Val loss: 0.8847 | Val acc: 57.17% | LR: 0.000014
Epoch: 139 | MCC: 0.021991 | Train loss: 0.9527 | Train acc: 52.76% | Val loss: 0.8847 | Val acc: 57.15% | LR: 0.000012
Epoch: 140 | MCC: 0.022467 | Train loss: 0.9498 | Train acc: 52.85% | Val loss: 0.8846 | Val acc: 57.17% | LR: 0.000010
Epoch: 141 | MCC: 0.021933 | Train loss: 0.9521 | Train acc: 52.75% | Val loss: 0.8846 | Val acc: 57.15% | LR: 0.000008
Epoch: 142 | MCC: 0.021991 | Train loss: 0.9502 | Train acc: 52.86% | Val loss: 0.8846 | Val acc: 57.15% | LR: 0.000006
Epoch: 143 | MCC: 0.021875 | Train loss: 0.9551 | Train acc: 52.63% | Val loss: 0.8846 | Val acc: 57.15% | LR: 0.000005
Epoch: 144 | MCC: 0.022467 | Train loss: 0.9511 | Train acc: 52.83% | Val loss: 0.8845 | Val acc: 57.17% | LR: 0.000004
Epoch: 145 | MCC: 0.021735 | Train loss: 0.9527 | Train acc: 52.72% | Val loss: 0.8844 | Val acc: 57.15% | LR: 0.000003
Epoch: 146 | MCC: 0.021735 | Train loss: 0.9532 | Train acc: 52.69% | Val loss: 0.8845 | Val acc: 57.15% | LR: 0.000002
Epoch: 147 | MCC: 0.021933 | Train loss: 0.9535 | Train acc: 52.67% | Val loss: 0.8845 | Val acc: 57.15% | LR: 0.000001
Epoch: 148 | MCC: 0.021933 | Train loss: 0.9514 | Train acc: 52.77% | Val loss: 0.8845 | Val acc: 57.15% | LR: 0.000001
Epoch: 149 | MCC: 0.022467 | Train loss: 0.9512 | Train acc: 52.80% | Val loss: 0.8845 | Val acc: 57.17% | LR: 0.000001

[I 2025-10-05 10:05:18,556] Trial 43 finished with value: 0.022466816240921617 and parameters: {'lr': 0.0009702592945208086, 'hidden_size': 57, 'dropout': 0.02649326727549388, 'weight_decay': 0.003607698715066888}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: -0.035638 | Train loss: 0.9999 | Train acc: 50.54% | Val loss: 1.1111 | Val acc: 46.86% | LR: 0.000444
Epoch: 001 | MCC: -0.012584 | Train loss: 1.0055 | Train acc: 50.49% | Val loss: 1.0030 | Val acc: 47.08% | LR: 0.000444
Epoch: 002 | MCC: -0.003398 | Train loss: 1.0047 | Train acc: 50.54% | Val loss: 0.9998 | Val acc: 47.65% | LR: 0.000443
Epoch: 003 | MCC: 0.007690 | Train loss: 1.0355 | Train acc: 50.58% | Val loss: 1.0066 | Val acc: 47.26% | LR: 0.000443
Epoch: 004 | MCC: 0.032721 | Train loss: 0.9963 | Train acc: 50.73% | Val loss: 1.0018 | Val acc: 49.27% | LR: 0.000443
Epoch: 005 | MCC: 0.039399 | Train loss: 0.9957 | Train acc: 50.67% | Val loss: 0.9970 | Val acc: 51.53% | LR: 0.000442
Epoch: 006 | MCC: 0.012512 | Train loss: 0.9965 | Train acc: 50.67% | Val loss: 0.9959 | Val acc: 52.91% | LR: 0.000441
Epoch: 007 | MCC: 0.022632 | Train loss: 0.9955 | Train acc: 50.77% | Val loss: 0.9930 | Val acc: 53.78% | LR: 0.000441
Epoch: 008 | MCC: 0.009647 | Train loss: 0.9935 | Train acc: 50.94% | Val loss: 0.9893 | Val acc: 53.69% | LR: 0.000440
Epoch: 009 | MCC: 0.012781 | Train loss: 0.9978 | Train acc: 50.81% | Val loss: 0.9850 | Val acc: 53.85% | LR: 0.000439
Epoch: 010 | MCC: 0.014946 | Train loss: 0.9938 | Train acc: 50.92% | Val loss: 0.9831 | Val acc: 54.08% | LR: 0.000438
Epoch: 011 | MCC: 0.014951 | Train loss: 0.9931 | Train acc: 50.87% | Val loss: 0.9796 | Val acc: 54.11% | LR: 0.000437
Epoch: 012 | MCC: -0.001767 | Train loss: 0.9904 | Train acc: 51.01% | Val loss: 0.9759 | Val acc: 54.00% | LR: 0.000436
Epoch: 013 | MCC: 0.005228 | Train loss: 0.9892 | Train acc: 50.89% | Val loss: 0.9701 | Val acc: 54.56% | LR: 0.000434
Epoch: 014 | MCC: 0.013121 | Train loss: 0.9899 | Train acc: 50.89% | Val loss: 0.9633 | Val acc: 54.91% | LR: 0.000433
Epoch: 015 | MCC: 0.015982 | Train loss: 0.9880 | Train acc: 50.90% | Val loss: 0.9595 | Val acc: 55.23% | LR: 0.000431
Epoch: 016 | MCC: 0.022750 | Train loss: 0.9858 | Train acc: 50.93% | Val loss: 0.9609 | Val acc: 55.97% | LR: 0.000430
Epoch: 017 | MCC: 0.021054 | Train loss: 0.9850 | Train acc: 50.96% | Val loss: 0.9580 | Val acc: 55.73% | LR: 0.000428
Epoch: 018 | MCC: 0.013708 | Train loss: 0.9832 | Train acc: 50.98% | Val loss: 0.9521 | Val acc: 55.31% | LR: 0.000427
Epoch: 019 | MCC: 0.017608 | Train loss: 0.9846 | Train acc: 50.97% | Val loss: 0.9519 | Val acc: 54.98% | LR: 0.000425
Epoch: 020 | MCC: 0.023307 | Train loss: 0.9838 | Train acc: 50.94% | Val loss: 0.9448 | Val acc: 55.60% | LR: 0.000423
Epoch: 021 | MCC: 0.020878 | Train loss: 0.9887 | Train acc: 50.83% | Val loss: 0.9422 | Val acc: 55.90% | LR: 0.000421
Epoch: 022 | MCC: 0.023858 | Train loss: 0.9841 | Train acc: 51.07% | Val loss: 0.9326 | Val acc: 56.04% | LR: 0.000419
Epoch: 023 | MCC: 0.017733 | Train loss: 0.9856 | Train acc: 50.93% | Val loss: 0.9243 | Val acc: 56.53% | LR: 0.000416
Epoch: 024 | MCC: 0.020340 | Train loss: 0.9820 | Train acc: 51.05% | Val loss: 0.9281 | Val acc: 55.32% | LR: 0.000414
Epoch: 025 | MCC: 0.032751 | Train loss: 0.9835 | Train acc: 50.90% | Val loss: 0.9267 | Val acc: 55.84% | LR: 0.000412
Epoch: 026 | MCC: 0.033015 | Train loss: 0.9815 | Train acc: 50.98% | Val loss: 0.9170 | Val acc: 56.46% | LR: 0.000409
Epoch: 027 | MCC: 0.032512 | Train loss: 0.9823 | Train acc: 50.89% | Val loss: 0.9143 | Val acc: 56.74% | LR: 0.000407
Epoch: 028 | MCC: 0.030849 | Train loss: 0.9857 | Train acc: 50.74% | Val loss: 0.9125 | Val acc: 56.51% | LR: 0.000404
Epoch: 029 | MCC: 0.027348 | Train loss: 0.9810 | Train acc: 51.00% | Val loss: 0.9108 | Val acc: 56.70% | LR: 0.000402
Epoch: 030 | MCC: 0.037326 | Train loss: 0.9817 | Train acc: 50.92% | Val loss: 0.9091 | Val acc: 56.75% | LR: 0.000399
Epoch: 031 | MCC: 0.026268 | Train loss: 0.9822 | Train acc: 50.95% | Val loss: 0.9046 | Val acc: 56.47% | LR: 0.000396
Epoch: 032 | MCC: 0.029606 | Train loss: 0.9817 | Train acc: 51.00% | Val loss: 0.9053 | Val acc: 56.89% | LR: 0.000393
Epoch: 033 | MCC: 0.031397 | Train loss: 0.9829 | Train acc: 50.79% | Val loss: 0.9076 | Val acc: 56.94% | LR: 0.000390
Epoch: 034 | MCC: 0.031104 | Train loss: 0.9823 | Train acc: 50.89% | Val loss: 0.9044 | Val acc: 56.77% | LR: 0.000387
Epoch: 035 | MCC: 0.034414 | Train loss: 0.9810 | Train acc: 50.97% | Val loss: 0.9027 | Val acc: 57.07% | LR: 0.000384
Epoch: 036 | MCC: 0.033804 | Train loss: 0.9814 | Train acc: 50.90% | Val loss: 0.9020 | Val acc: 56.94% | LR: 0.000381
Epoch: 037 | MCC: 0.032491 | Train loss: 0.9952 | Train acc: 50.90% | Val loss: 0.9034 | Val acc: 56.90% | LR: 0.000377
Epoch: 038 | MCC: 0.033002 | Train loss: 0.9822 | Train acc: 50.92% | Val loss: 0.8982 | Val acc: 56.86% | LR: 0.000374
Epoch: 039 | MCC: 0.036661 | Train loss: 0.9815 | Train acc: 50.97% | Val loss: 0.9009 | Val acc: 56.24% | LR: 0.000371
Epoch: 040 | MCC: 0.032964 | Train loss: 0.9792 | Train acc: 51.13% | Val loss: 0.9034 | Val acc: 55.86% | LR: 0.000367
Epoch: 041 | MCC: 0.033986 | Train loss: 0.9835 | Train acc: 50.89% | Val loss: 0.9026 | Val acc: 55.88% | LR: 0.000364
Epoch: 042 | MCC: 0.036434 | Train loss: 0.9824 | Train acc: 50.90% | Val loss: 0.9048 | Val acc: 56.05% | LR: 0.000360
Epoch: 043 | MCC: 0.033716 | Train loss: 0.9800 | Train acc: 51.06% | Val loss: 0.9092 | Val acc: 56.19% | LR: 0.000356
Epoch: 044 | MCC: 0.027224 | Train loss: 0.9807 | Train acc: 50.99% | Val loss: 0.8955 | Val acc: 56.01% | LR: 0.000353
Epoch: 045 | MCC: 0.030581 | Train loss: 1.1736 | Train acc: 51.11% | Val loss: 0.8954 | Val acc: 56.15% | LR: 0.000349
Epoch: 046 | MCC: 0.029880 | Train loss: 0.9849 | Train acc: 51.05% | Val loss: 0.8960 | Val acc: 56.03% | LR: 0.000345
Epoch: 047 | MCC: 0.031617 | Train loss: 0.9850 | Train acc: 51.08% | Val loss: 0.9027 | Val acc: 56.25% | LR: 0.000341
Epoch: 048 | MCC: 0.032071 | Train loss: 1.0304 | Train acc: 51.01% | Val loss: 0.8945 | Val acc: 55.79% | LR: 0.000337
Epoch: 049 | MCC: 0.033071 | Train loss: 0.9818 | Train acc: 50.98% | Val loss: 0.8914 | Val acc: 56.02% | LR: 0.000333
Epoch: 050 | MCC: 0.036622 | Train loss: 0.9820 | Train acc: 50.89% | Val loss: 0.8926 | Val acc: 56.45% | LR: 0.000329
Epoch: 051 | MCC: 0.046450 | Train loss: 0.9802 | Train acc: 51.04% | Val loss: 0.8902 | Val acc: 57.03% | LR: 0.000325
Epoch: 052 | MCC: 0.035049 | Train loss: 0.9820 | Train acc: 50.94% | Val loss: 0.8838 | Val acc: 57.28% | LR: 0.000321
Epoch: 053 | MCC: 0.048111 | Train loss: 0.9785 | Train acc: 51.11% | Val loss: 0.8854 | Val acc: 57.26% | LR: 0.000317
Epoch: 054 | MCC: 0.045439 | Train loss: 0.9796 | Train acc: 51.07% | Val loss: 0.8888 | Val acc: 56.77% | LR: 0.000312
Epoch: 055 | MCC: 0.044189 | Train loss: 0.9794 | Train acc: 51.11% | Val loss: 0.8842 | Val acc: 56.95% | LR: 0.000308
Epoch: 056 | MCC: 0.043357 | Train loss: 0.9794 | Train acc: 51.07% | Val loss: 0.8788 | Val acc: 57.15% | LR: 0.000304
Epoch: 057 | MCC: 0.042622 | Train loss: 0.9785 | Train acc: 51.12% | Val loss: 0.8817 | Val acc: 56.80% | LR: 0.000300
Epoch: 058 | MCC: 0.043031 | Train loss: 0.9805 | Train acc: 51.05% | Val loss: 0.8812 | Val acc: 56.77% | LR: 0.000295
Epoch: 059 | MCC: 0.047465 | Train loss: 0.9788 | Train acc: 51.10% | Val loss: 0.8750 | Val acc: 57.88% | LR: 0.000291
Epoch: 060 | MCC: 0.046181 | Train loss: 0.9803 | Train acc: 50.98% | Val loss: 0.8717 | Val acc: 57.80% | LR: 0.000286
Epoch: 061 | MCC: 0.048344 | Train loss: 0.9787 | Train acc: 51.07% | Val loss: 0.8684 | Val acc: 57.80% | LR: 0.000282
Epoch: 062 | MCC: 0.045702 | Train loss: 0.9796 | Train acc: 51.14% | Val loss: 0.8709 | Val acc: 57.75% | LR: 0.000277
Epoch: 063 | MCC: 0.043676 | Train loss: 0.9790 | Train acc: 51.09% | Val loss: 0.8694 | Val acc: 57.79% | LR: 0.000273
Epoch: 064 | MCC: 0.039449 | Train loss: 0.9800 | Train acc: 51.03% | Val loss: 0.8716 | Val acc: 57.44% | LR: 0.000268
Epoch: 065 | MCC: 0.040931 | Train loss: 0.9782 | Train acc: 51.13% | Val loss: 0.8704 | Val acc: 57.52% | LR: 0.000264
Epoch: 066 | MCC: 0.044957 | Train loss: 0.9793 | Train acc: 51.17% | Val loss: 0.8702 | Val acc: 57.48% | LR: 0.000259
Epoch: 067 | MCC: 0.038008 | Train loss: 0.9801 | Train acc: 51.10% | Val loss: 0.8734 | Val acc: 57.14% | LR: 0.000255
Epoch: 068 | MCC: 0.038820 | Train loss: 0.9789 | Train acc: 51.11% | Val loss: 0.8692 | Val acc: 57.11% | LR: 0.000250
Epoch: 069 | MCC: 0.042242 | Train loss: 0.9783 | Train acc: 51.17% | Val loss: 0.8716 | Val acc: 57.38% | LR: 0.000246
Epoch: 070 | MCC: 0.041623 | Train loss: 0.9792 | Train acc: 51.06% | Val loss: 0.8754 | Val acc: 57.53% | LR: 0.000241
Epoch: 071 | MCC: 0.043983 | Train loss: 0.9800 | Train acc: 51.02% | Val loss: 0.8691 | Val acc: 57.62% | LR: 0.000236
Epoch: 072 | MCC: 0.031385 | Train loss: 0.9780 | Train acc: 51.17% | Val loss: 0.8719 | Val acc: 56.57% | LR: 0.000232
Epoch: 073 | MCC: 0.032790 | Train loss: 0.9783 | Train acc: 51.12% | Val loss: 0.8731 | Val acc: 56.43% | LR: 0.000227
Epoch: 074 | MCC: 0.039143 | Train loss: 0.9776 | Train acc: 51.15% | Val loss: 0.8691 | Val acc: 56.97% | LR: 0.000222
Epoch: 075 | MCC: 0.039348 | Train loss: 0.9771 | Train acc: 51.21% | Val loss: 0.8651 | Val acc: 57.36% | LR: 0.000218
Epoch: 076 | MCC: 0.038436 | Train loss: 0.9798 | Train acc: 51.09% | Val loss: 0.8688 | Val acc: 56.94% | LR: 0.000213
Epoch: 077 | MCC: 0.034707 | Train loss: 0.9780 | Train acc: 51.18% | Val loss: 0.8761 | Val acc: 56.40% | LR: 0.000209
Epoch: 078 | MCC: 0.039111 | Train loss: 0.9791 | Train acc: 51.09% | Val loss: 0.8764 | Val acc: 56.50% | LR: 0.000204
Epoch: 079 | MCC: 0.033697 | Train loss: 0.9772 | Train acc: 51.23% | Val loss: 0.8979 | Val acc: 56.43% | LR: 0.000199
Epoch: 080 | MCC: 0.036559 | Train loss: 0.9781 | Train acc: 51.20% | Val loss: 0.8765 | Val acc: 56.43% | LR: 0.000195
Epoch: 081 | MCC: 0.030660 | Train loss: 0.9775 | Train acc: 51.14% | Val loss: 0.8776 | Val acc: 56.09% | LR: 0.000190
Epoch: 082 | MCC: 0.032729 | Train loss: 0.9781 | Train acc: 51.06% | Val loss: 0.8785 | Val acc: 56.16% | LR: 0.000185
Epoch: 083 | MCC: 0.032479 | Train loss: 0.9772 | Train acc: 51.14% | Val loss: 0.8780 | Val acc: 56.14% | LR: 0.000181
Epoch: 084 | MCC: 0.025849 | Train loss: 0.9778 | Train acc: 51.17% | Val loss: 0.8800 | Val acc: 55.79% | LR: 0.000176
Epoch: 085 | MCC: 0.032964 | Train loss: 0.9799 | Train acc: 51.13% | Val loss: 0.8844 | Val acc: 55.84% | LR: 0.000172
Epoch: 086 | MCC: 0.029600 | Train loss: 0.9774 | Train acc: 51.12% | Val loss: 0.8863 | Val acc: 55.98% | LR: 0.000167
Epoch: 087 | MCC: 0.028123 | Train loss: 0.9794 | Train acc: 51.02% | Val loss: 0.8859 | Val acc: 55.85% | LR: 0.000163
Epoch: 088 | MCC: 0.027672 | Train loss: 0.9769 | Train acc: 51.27% | Val loss: 0.8877 | Val acc: 55.80% | LR: 0.000158
Epoch: 089 | MCC: 0.029177 | Train loss: 0.9793 | Train acc: 51.07% | Val loss: 0.8876 | Val acc: 55.85% | LR: 0.000154
Epoch: 090 | MCC: 0.021538 | Train loss: 0.9801 | Train acc: 51.07% | Val loss: 0.8878 | Val acc: 55.79% | LR: 0.000150
Epoch: 091 | MCC: 0.019179 | Train loss: 0.9781 | Train acc: 51.14% | Val loss: 0.8825 | Val acc: 55.85% | LR: 0.000145
Epoch: 092 | MCC: 0.038517 | Train loss: 0.9844 | Train acc: 51.12% | Val loss: 0.8778 | Val acc: 56.46% | LR: 0.000141
Epoch: 093 | MCC: 0.040621 | Train loss: 0.9759 | Train acc: 51.20% | Val loss: 0.8723 | Val acc: 56.93% | LR: 0.000137
Epoch: 094 | MCC: 0.035927 | Train loss: 0.9782 | Train acc: 51.12% | Val loss: 0.8737 | Val acc: 56.81% | LR: 0.000132
Epoch: 095 | MCC: 0.034384 | Train loss: 0.9780 | Train acc: 51.13% | Val loss: 0.8744 | Val acc: 56.73% | LR: 0.000128
Epoch: 096 | MCC: 0.037731 | Train loss: 0.9765 | Train acc: 51.24% | Val loss: 0.8719 | Val acc: 56.93% | LR: 0.000124
Epoch: 097 | MCC: 0.037553 | Train loss: 0.9783 | Train acc: 51.14% | Val loss: 0.8716 | Val acc: 56.88% | LR: 0.000120
Epoch: 098 | MCC: 0.035235 | Train loss: 0.9778 | Train acc: 51.14% | Val loss: 0.8730 | Val acc: 56.71% | LR: 0.000116
Epoch: 099 | MCC: 0.029214 | Train loss: 0.9785 | Train acc: 51.13% | Val loss: 0.8749 | Val acc: 56.44% | LR: 0.000112
Epoch: 100 | MCC: 0.030592 | Train loss: 0.9781 | Train acc: 51.06% | Val loss: 0.8742 | Val acc: 56.59% | LR: 0.000108
Epoch: 101 | MCC: 0.037207 | Train loss: 0.9759 | Train acc: 51.21% | Val loss: 0.8733 | Val acc: 56.85% | LR: 0.000104
Epoch: 102 | MCC: 0.033184 | Train loss: 0.9762 | Train acc: 51.25% | Val loss: 0.8739 | Val acc: 56.71% | LR: 0.000100
Epoch: 103 | MCC: 0.035052 | Train loss: 0.9789 | Train acc: 51.01% | Val loss: 0.8729 | Val acc: 56.73% | LR: 0.000096
Epoch: 104 | MCC: 0.037542 | Train loss: 0.9772 | Train acc: 51.16% | Val loss: 0.8715 | Val acc: 56.88% | LR: 0.000092
Epoch: 105 | MCC: 0.034731 | Train loss: 0.9774 | Train acc: 51.12% | Val loss: 0.8729 | Val acc: 56.73% | LR: 0.000089
Epoch: 106 | MCC: 0.035759 | Train loss: 0.9785 | Train acc: 51.09% | Val loss: 0.8729 | Val acc: 56.73% | LR: 0.000085
Epoch: 107 | MCC: 0.031471 | Train loss: 0.9757 | Train acc: 51.22% | Val loss: 0.8731 | Val acc: 56.59% | LR: 0.000081
Epoch: 108 | MCC: 0.035932 | Train loss: 0.9762 | Train acc: 51.20% | Val loss: 0.8733 | Val acc: 56.65% | LR: 0.000078
Epoch: 109 | MCC: 0.033485 | Train loss: 0.9767 | Train acc: 51.15% | Val loss: 0.8748 | Val acc: 56.60% | LR: 0.000074
Epoch: 110 | MCC: 0.033880 | Train loss: 0.9779 | Train acc: 51.09% | Val loss: 0.8762 | Val acc: 56.55% | LR: 0.000071
Epoch: 111 | MCC: 0.025104 | Train loss: 0.9804 | Train acc: 51.15% | Val loss: 0.8764 | Val acc: 56.45% | LR: 0.000067
Epoch: 112 | MCC: 0.036153 | Train loss: 0.9776 | Train acc: 51.11% | Val loss: 0.8730 | Val acc: 56.73% | LR: 0.000064
Epoch: 113 | MCC: 0.035127 | Train loss: 0.9802 | Train acc: 51.05% | Val loss: 0.8818 | Val acc: 56.73% | LR: 0.000061
Epoch: 114 | MCC: 0.038570 | Train loss: 0.9793 | Train acc: 51.09% | Val loss: 0.8701 | Val acc: 56.93% | LR: 0.000058
Epoch: 115 | MCC: 0.035018 | Train loss: 0.9790 | Train acc: 51.06% | Val loss: 0.8723 | Val acc: 56.66% | LR: 0.000055
Epoch: 116 | MCC: 0.033201 | Train loss: 0.9782 | Train acc: 51.10% | Val loss: 0.8795 | Val acc: 56.59% | LR: 0.000052
Epoch: 117 | MCC: 0.037545 | Train loss: 0.9769 | Train acc: 51.24% | Val loss: 0.8756 | Val acc: 56.77% | LR: 0.000049
Epoch: 118 | MCC: 0.034628 | Train loss: 0.9768 | Train acc: 51.17% | Val loss: 0.8743 | Val acc: 56.61% | LR: 0.000046
Epoch: 119 | MCC: 0.038598 | Train loss: 0.9775 | Train acc: 51.14% | Val loss: 0.8746 | Val acc: 56.74% | LR: 0.000043
Epoch: 120 | MCC: 0.038222 | Train loss: 0.9774 | Train acc: 51.13% | Val loss: 0.8748 | Val acc: 56.78% | LR: 0.000041
Epoch: 121 | MCC: 0.025784 | Train loss: 0.9787 | Train acc: 51.04% | Val loss: 0.8760 | Val acc: 56.69% | LR: 0.000038
Epoch: 122 | MCC: 0.025988 | Train loss: 0.9774 | Train acc: 51.18% | Val loss: 0.8795 | Val acc: 56.69% | LR: 0.000035
Epoch: 123 | MCC: 0.016889 | Train loss: 0.9794 | Train acc: 51.00% | Val loss: 0.8770 | Val acc: 56.52% | LR: 0.000033
Epoch: 124 | MCC: 0.031388 | Train loss: 0.9779 | Train acc: 51.07% | Val loss: 0.8755 | Val acc: 56.70% | LR: 0.000031
Epoch: 125 | MCC: 0.018368 | Train loss: 0.9779 | Train acc: 51.09% | Val loss: 0.8755 | Val acc: 56.62% | LR: 0.000028
Epoch: 126 | MCC: 0.018853 | Train loss: 0.9765 | Train acc: 51.17% | Val loss: 0.8760 | Val acc: 56.62% | LR: 0.000026
Epoch: 127 | MCC: 0.017939 | Train loss: 0.9770 | Train acc: 51.16% | Val loss: 0.8786 | Val acc: 56.57% | LR: 0.000024
Epoch: 128 | MCC: 0.018464 | Train loss: 0.9759 | Train acc: 51.20% | Val loss: 0.8768 | Val acc: 56.60% | LR: 0.000022
Epoch: 129 | MCC: 0.018457 | Train loss: 0.9775 | Train acc: 51.09% | Val loss: 0.8765 | Val acc: 56.60% | LR: 0.000020
Epoch: 130 | MCC: 0.017018 | Train loss: 0.9779 | Train acc: 51.03% | Val loss: 0.8768 | Val acc: 56.52% | LR: 0.000018
Epoch: 131 | MCC: 0.017939 | Train loss: 0.9764 | Train acc: 51.18% | Val loss: 0.8792 | Val acc: 56.57% | LR: 0.000017
Epoch: 132 | MCC: 0.017939 | Train loss: 0.9787 | Train acc: 51.09% | Val loss: 0.8784 | Val acc: 56.57% | LR: 0.000015
Epoch: 133 | MCC: 0.017478 | Train loss: 0.9750 | Train acc: 51.25% | Val loss: 0.8771 | Val acc: 56.55% | LR: 0.000013
Epoch: 134 | MCC: 0.017411 | Train loss: 0.9766 | Train acc: 51.13% | Val loss: 0.8764 | Val acc: 56.55% | LR: 0.000012
Epoch: 135 | MCC: 0.017411 | Train loss: 0.9776 | Train acc: 51.12% | Val loss: 0.8766 | Val acc: 56.55% | LR: 0.000010
Epoch: 136 | MCC: 0.017478 | Train loss: 0.9775 | Train acc: 51.14% | Val loss: 0.8786 | Val acc: 56.55% | LR: 0.000009
Epoch: 137 | MCC: 0.017803 | Train loss: 0.9768 | Train acc: 51.17% | Val loss: 0.8766 | Val acc: 56.57% | LR: 0.000008
Epoch: 138 | MCC: 0.017411 | Train loss: 0.9780 | Train acc: 51.05% | Val loss: 0.8767 | Val acc: 56.55% | LR: 0.000007
Epoch: 139 | MCC: 0.016953 | Train loss: 0.9779 | Train acc: 51.14% | Val loss: 0.8775 | Val acc: 56.52% | LR: 0.000006
Epoch: 140 | MCC: 0.017347 | Train loss: 0.9771 | Train acc: 51.12% | Val loss: 0.8778 | Val acc: 56.55% | LR: 0.000005
Epoch: 141 | MCC: 0.017478 | Train loss: 0.9769 | Train acc: 51.21% | Val loss: 0.8779 | Val acc: 56.55% | LR: 0.000004
Epoch: 142 | MCC: 0.018392 | Train loss: 0.9764 | Train acc: 51.20% | Val loss: 0.8766 | Val acc: 56.60% | LR: 0.000003
Epoch: 143 | MCC: 0.017478 | Train loss: 0.9775 | Train acc: 51.09% | Val loss: 0.8912 | Val acc: 56.55% | LR: 0.000003
Epoch: 144 | MCC: 0.017478 | Train loss: 0.9757 | Train acc: 51.22% | Val loss: 0.8780 | Val acc: 56.55% | LR: 0.000002
Epoch: 145 | MCC: 0.016953 | Train loss: 0.9777 | Train acc: 51.16% | Val loss: 0.8779 | Val acc: 56.52% | LR: 0.000002
Epoch: 146 | MCC: 0.017347 | Train loss: 0.9756 | Train acc: 51.23% | Val loss: 0.8783 | Val acc: 56.55% | LR: 0.000001
Epoch: 147 | MCC: 0.017347 | Train loss: 0.9764 | Train acc: 51.18% | Val loss: 0.8778 | Val acc: 56.55% | LR: 0.000001
Epoch: 148 | MCC: 0.016953 | Train loss: 0.9785 | Train acc: 51.01% | Val loss: 0.8779 | Val acc: 56.52% | LR: 0.000001
Epoch: 149 | MCC: 0.017347 | Train loss: 0.9784 | Train acc: 51.07% | Val loss: 0.8776 | Val acc: 56.55% | LR: 0.000001

[I 2025-10-05 10:07:21,405] Trial 44 finished with value: 0.01734691404271871 and parameters: {'lr': 0.000443806402062012, 'hidden_size': 46, 'dropout': 0.1524106425143133, 'weight_decay': 0.011462484749556915}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: -0.023035 | Train loss: 0.9981 | Train acc: 50.37% | Val loss: 1.0026 | Val acc: 53.61% | LR: 0.000224
Epoch: 001 | MCC: -0.042782 | Train loss: 1.0005 | Train acc: 50.00% | Val loss: 0.9978 | Val acc: 52.53% | LR: 0.000224
Epoch: 002 | MCC: -0.042705 | Train loss: 0.9950 | Train acc: 50.17% | Val loss: 0.9975 | Val acc: 52.57% | LR: 0.000224
Epoch: 003 | MCC: -0.027771 | Train loss: 0.9948 | Train acc: 50.08% | Val loss: 0.9971 | Val acc: 53.33% | LR: 0.000224
Epoch: 004 | MCC: 0.015087 | Train loss: 0.9901 | Train acc: 50.64% | Val loss: 0.9963 | Val acc: 55.31% | LR: 0.000223
Epoch: 005 | MCC: -0.011840 | Train loss: 0.9897 | Train acc: 50.90% | Val loss: 0.9953 | Val acc: 55.44% | LR: 0.000223
Epoch: 006 | MCC: 0.010404 | Train loss: 0.9906 | Train acc: 50.97% | Val loss: 0.9941 | Val acc: 54.79% | LR: 0.000223
Epoch: 007 | MCC: 0.030657 | Train loss: 0.9881 | Train acc: 51.04% | Val loss: 0.9936 | Val acc: 55.14% | LR: 0.000222
Epoch: 008 | MCC: 0.034088 | Train loss: 0.9896 | Train acc: 50.89% | Val loss: 0.9920 | Val acc: 55.03% | LR: 0.000222
Epoch: 009 | MCC: 0.035520 | Train loss: 0.9885 | Train acc: 50.93% | Val loss: 0.9905 | Val acc: 54.99% | LR: 0.000222
Epoch: 010 | MCC: 0.036316 | Train loss: 0.9884 | Train acc: 50.84% | Val loss: 0.9878 | Val acc: 54.79% | LR: 0.000221
Epoch: 011 | MCC: 0.037355 | Train loss: 0.9865 | Train acc: 50.95% | Val loss: 0.9860 | Val acc: 54.81% | LR: 0.000220
Epoch: 012 | MCC: 0.038700 | Train loss: 0.9851 | Train acc: 50.92% | Val loss: 0.9824 | Val acc: 54.96% | LR: 0.000220
Epoch: 013 | MCC: 0.038931 | Train loss: 0.9835 | Train acc: 50.92% | Val loss: 0.9779 | Val acc: 55.07% | LR: 0.000219
Epoch: 014 | MCC: 0.037537 | Train loss: 0.9833 | Train acc: 50.91% | Val loss: 0.9758 | Val acc: 55.08% | LR: 0.000218
Epoch: 015 | MCC: 0.035746 | Train loss: 0.9840 | Train acc: 50.80% | Val loss: 0.9712 | Val acc: 55.12% | LR: 0.000218
Epoch: 016 | MCC: 0.036002 | Train loss: 0.9825 | Train acc: 51.04% | Val loss: 0.9660 | Val acc: 55.55% | LR: 0.000217
Epoch: 017 | MCC: 0.031793 | Train loss: 0.9828 | Train acc: 50.91% | Val loss: 0.9609 | Val acc: 55.70% | LR: 0.000216
Epoch: 018 | MCC: 0.032188 | Train loss: 0.9832 | Train acc: 50.90% | Val loss: 0.9556 | Val acc: 55.77% | LR: 0.000215
Epoch: 019 | MCC: 0.023541 | Train loss: 0.9806 | Train acc: 51.03% | Val loss: 0.9499 | Val acc: 55.70% | LR: 0.000214
Epoch: 020 | MCC: 0.024650 | Train loss: 0.9827 | Train acc: 50.82% | Val loss: 0.9448 | Val acc: 55.79% | LR: 0.000213
Epoch: 021 | MCC: 0.030024 | Train loss: 0.9820 | Train acc: 50.84% | Val loss: 0.9355 | Val acc: 56.13% | LR: 0.000212
Epoch: 022 | MCC: 0.025190 | Train loss: 0.9812 | Train acc: 50.87% | Val loss: 0.9331 | Val acc: 56.00% | LR: 0.000211
Epoch: 023 | MCC: 0.012919 | Train loss: 0.9807 | Train acc: 50.97% | Val loss: 0.9248 | Val acc: 55.69% | LR: 0.000210
Epoch: 024 | MCC: 0.014261 | Train loss: 0.9809 | Train acc: 50.90% | Val loss: 0.9208 | Val acc: 55.80% | LR: 0.000209
Epoch: 025 | MCC: 0.022347 | Train loss: 0.9806 | Train acc: 50.91% | Val loss: 0.9182 | Val acc: 56.13% | LR: 0.000208
Epoch: 026 | MCC: 0.028009 | Train loss: 0.9796 | Train acc: 51.00% | Val loss: 0.9159 | Val acc: 56.29% | LR: 0.000207
Epoch: 027 | MCC: 0.024264 | Train loss: 0.9788 | Train acc: 51.05% | Val loss: 0.9111 | Val acc: 56.39% | LR: 0.000205
Epoch: 028 | MCC: 0.042284 | Train loss: 0.9786 | Train acc: 51.05% | Val loss: 0.9065 | Val acc: 57.18% | LR: 0.000204
Epoch: 029 | MCC: 0.037867 | Train loss: 0.9799 | Train acc: 50.94% | Val loss: 0.9014 | Val acc: 57.36% | LR: 0.000203
Epoch: 030 | MCC: 0.052537 | Train loss: 0.9802 | Train acc: 51.01% | Val loss: 0.8982 | Val acc: 57.69% | LR: 0.000201
Epoch: 031 | MCC: 0.039013 | Train loss: 0.9772 | Train acc: 51.07% | Val loss: 0.8952 | Val acc: 57.45% | LR: 0.000200
Epoch: 032 | MCC: 0.029154 | Train loss: 0.9779 | Train acc: 51.12% | Val loss: 0.8922 | Val acc: 57.08% | LR: 0.000198
Epoch: 033 | MCC: 0.014550 | Train loss: 0.9771 | Train acc: 51.08% | Val loss: 0.8885 | Val acc: 56.65% | LR: 0.000197
Epoch: 034 | MCC: -0.001920 | Train loss: 0.9821 | Train acc: 51.09% | Val loss: 0.8820 | Val acc: 56.56% | LR: 0.000195
Epoch: 035 | MCC: -0.003790 | Train loss: 0.9775 | Train acc: 51.23% | Val loss: 0.8839 | Val acc: 56.07% | LR: 0.000194
Epoch: 036 | MCC: -0.002013 | Train loss: 0.9761 | Train acc: 51.26% | Val loss: 0.8816 | Val acc: 56.08% | LR: 0.000192
Epoch: 037 | MCC: -0.004469 | Train loss: 0.9740 | Train acc: 51.30% | Val loss: 0.8752 | Val acc: 56.42% | LR: 0.000190
Epoch: 038 | MCC: 0.009179 | Train loss: 0.9736 | Train acc: 51.22% | Val loss: 0.8820 | Val acc: 56.44% | LR: 0.000189
Epoch: 039 | MCC: 0.001371 | Train loss: 0.9729 | Train acc: 51.29% | Val loss: 0.8777 | Val acc: 56.30% | LR: 0.000187
Epoch: 040 | MCC: 0.011525 | Train loss: 0.9734 | Train acc: 51.21% | Val loss: 0.8871 | Val acc: 56.17% | LR: 0.000185
Epoch: 041 | MCC: 0.003294 | Train loss: 0.9725 | Train acc: 51.25% | Val loss: 0.8697 | Val acc: 56.83% | LR: 0.000184
Epoch: 042 | MCC: 0.009530 | Train loss: 0.9728 | Train acc: 51.23% | Val loss: 0.8582 | Val acc: 57.61% | LR: 0.000182
Epoch: 043 | MCC: 0.006320 | Train loss: 0.9722 | Train acc: 51.25% | Val loss: 0.8618 | Val acc: 57.29% | LR: 0.000180
Epoch: 044 | MCC: 0.016246 | Train loss: 0.9716 | Train acc: 51.36% | Val loss: 0.8459 | Val acc: 58.73% | LR: 0.000178
Epoch: 045 | MCC: 0.017822 | Train loss: 0.9700 | Train acc: 51.36% | Val loss: 0.8513 | Val acc: 57.86% | LR: 0.000176
Epoch: 046 | MCC: 0.002550 | Train loss: 0.9714 | Train acc: 51.35% | Val loss: 0.8592 | Val acc: 57.19% | LR: 0.000174
Epoch: 047 | MCC: 0.001944 | Train loss: 0.9700 | Train acc: 51.35% | Val loss: 0.8556 | Val acc: 57.61% | LR: 0.000172
Epoch: 048 | MCC: 0.019451 | Train loss: 0.9735 | Train acc: 51.40% | Val loss: 0.8853 | Val acc: 56.39% | LR: 0.000170
Epoch: 049 | MCC: 0.014663 | Train loss: 0.9725 | Train acc: 51.25% | Val loss: 0.8761 | Val acc: 56.42% | LR: 0.000168
Epoch: 050 | MCC: -0.000068 | Train loss: 0.9740 | Train acc: 51.21% | Val loss: 0.9051 | Val acc: 55.26% | LR: 0.000166
Epoch: 051 | MCC: -0.002358 | Train loss: 0.9759 | Train acc: 50.95% | Val loss: 0.8983 | Val acc: 55.28% | LR: 0.000164
Epoch: 052 | MCC: -0.001591 | Train loss: 0.9751 | Train acc: 51.87% | Val loss: 0.8952 | Val acc: 55.25% | LR: 0.000162
Epoch: 053 | MCC: -0.004847 | Train loss: 0.9747 | Train acc: 51.47% | Val loss: 0.8976 | Val acc: 55.06% | LR: 0.000160
Epoch: 054 | MCC: -0.002542 | Train loss: 0.9737 | Train acc: 51.24% | Val loss: 0.8992 | Val acc: 55.17% | LR: 0.000158
Epoch: 055 | MCC: 0.003384 | Train loss: 0.9725 | Train acc: 51.74% | Val loss: 0.8895 | Val acc: 55.66% | LR: 0.000156
Epoch: 056 | MCC: 0.001976 | Train loss: 0.9744 | Train acc: 51.84% | Val loss: 0.8876 | Val acc: 55.67% | LR: 0.000154
Epoch: 057 | MCC: 0.000661 | Train loss: 0.9701 | Train acc: 51.92% | Val loss: 0.8736 | Val acc: 56.48% | LR: 0.000151
Epoch: 058 | MCC: 0.015905 | Train loss: 0.9728 | Train acc: 51.78% | Val loss: 0.8691 | Val acc: 56.68% | LR: 0.000149
Epoch: 059 | MCC: -0.005476 | Train loss: 0.9712 | Train acc: 51.87% | Val loss: 0.8863 | Val acc: 55.65% | LR: 0.000147
Epoch: 060 | MCC: -0.007115 | Train loss: 0.9699 | Train acc: 51.94% | Val loss: 0.8892 | Val acc: 55.48% | LR: 0.000145
Epoch: 061 | MCC: 0.005679 | Train loss: 0.9745 | Train acc: 51.19% | Val loss: 0.8973 | Val acc: 55.43% | LR: 0.000142
Epoch: 062 | MCC: -0.001894 | Train loss: 0.9725 | Train acc: 51.88% | Val loss: 0.8921 | Val acc: 55.43% | LR: 0.000140
Epoch: 063 | MCC: 0.000605 | Train loss: 0.9704 | Train acc: 51.91% | Val loss: 0.8895 | Val acc: 55.72% | LR: 0.000138
Epoch: 064 | MCC: -0.008233 | Train loss: 0.9703 | Train acc: 51.78% | Val loss: 0.8858 | Val acc: 55.68% | LR: 0.000136
Epoch: 065 | MCC: -0.006581 | Train loss: 0.9691 | Train acc: 52.01% | Val loss: 0.8860 | Val acc: 55.61% | LR: 0.000133
Epoch: 066 | MCC: -0.004821 | Train loss: 0.9698 | Train acc: 51.88% | Val loss: 0.8853 | Val acc: 55.63% | LR: 0.000131
Epoch: 067 | MCC: 0.000398 | Train loss: 0.9710 | Train acc: 51.93% | Val loss: 0.8881 | Val acc: 55.68% | LR: 0.000129
Epoch: 068 | MCC: 0.001412 | Train loss: 0.9708 | Train acc: 51.93% | Val loss: 0.8854 | Val acc: 55.70% | LR: 0.000126
Epoch: 069 | MCC: 0.000848 | Train loss: 0.9716 | Train acc: 51.84% | Val loss: 0.8966 | Val acc: 55.22% | LR: 0.000124
Epoch: 070 | MCC: 0.000988 | Train loss: 0.9726 | Train acc: 51.79% | Val loss: 0.8968 | Val acc: 55.22% | LR: 0.000122
Epoch: 071 | MCC: 0.000834 | Train loss: 0.9713 | Train acc: 51.87% | Val loss: 0.8946 | Val acc: 55.34% | LR: 0.000119
Epoch: 072 | MCC: -0.000120 | Train loss: 0.9735 | Train acc: 51.97% | Val loss: 0.8853 | Val acc: 55.65% | LR: 0.000117
Epoch: 073 | MCC: 0.004258 | Train loss: 1.0242 | Train acc: 51.88% | Val loss: 0.8843 | Val acc: 55.87% | LR: 0.000115
Epoch: 074 | MCC: 0.001085 | Train loss: 0.9697 | Train acc: 51.93% | Val loss: 0.8861 | Val acc: 55.65% | LR: 0.000112
Epoch: 075 | MCC: 0.006777 | Train loss: 0.9698 | Train acc: 51.96% | Val loss: 0.8908 | Val acc: 55.63% | LR: 0.000110
Epoch: 076 | MCC: 0.002523 | Train loss: 0.9697 | Train acc: 51.95% | Val loss: 0.8886 | Val acc: 55.63% | LR: 0.000108
Epoch: 077 | MCC: 0.002634 | Train loss: 0.9689 | Train acc: 51.91% | Val loss: 0.8871 | Val acc: 55.70% | LR: 0.000105
Epoch: 078 | MCC: 0.004613 | Train loss: 0.9695 | Train acc: 51.84% | Val loss: 0.8857 | Val acc: 55.80% | LR: 0.000103
Epoch: 079 | MCC: 0.017131 | Train loss: 0.9689 | Train acc: 51.92% | Val loss: 0.8739 | Val acc: 56.63% | LR: 0.000101
Epoch: 080 | MCC: 0.011975 | Train loss: 0.9706 | Train acc: 51.77% | Val loss: 0.8695 | Val acc: 56.68% | LR: 0.000098
Epoch: 081 | MCC: 0.007379 | Train loss: 0.9731 | Train acc: 51.88% | Val loss: 0.8695 | Val acc: 56.55% | LR: 0.000096
Epoch: 082 | MCC: 0.014115 | Train loss: 0.9695 | Train acc: 51.90% | Val loss: 0.8773 | Val acc: 56.44% | LR: 0.000094
Epoch: 083 | MCC: 0.009084 | Train loss: 0.9689 | Train acc: 51.92% | Val loss: 0.8784 | Val acc: 56.09% | LR: 0.000092
Epoch: 084 | MCC: 0.007415 | Train loss: 0.9698 | Train acc: 51.84% | Val loss: 0.8803 | Val acc: 56.02% | LR: 0.000089
Epoch: 085 | MCC: 0.004781 | Train loss: 0.9689 | Train acc: 51.88% | Val loss: 0.8850 | Val acc: 55.85% | LR: 0.000087
Epoch: 086 | MCC: 0.000223 | Train loss: 0.9702 | Train acc: 51.83% | Val loss: 0.8873 | Val acc: 55.61% | LR: 0.000085
Epoch: 087 | MCC: 0.001318 | Train loss: 0.9702 | Train acc: 51.90% | Val loss: 0.8859 | Val acc: 55.70% | LR: 0.000082
Epoch: 088 | MCC: -0.000460 | Train loss: 0.9675 | Train acc: 51.98% | Val loss: 0.8865 | Val acc: 55.65% | LR: 0.000080
Epoch: 089 | MCC: -0.000807 | Train loss: 0.9679 | Train acc: 51.91% | Val loss: 0.8867 | Val acc: 55.63% | LR: 0.000078
Epoch: 090 | MCC: 0.000075 | Train loss: 0.9687 | Train acc: 51.85% | Val loss: 0.8859 | Val acc: 55.73% | LR: 0.000076
Epoch: 091 | MCC: -0.001289 | Train loss: 0.9675 | Train acc: 51.94% | Val loss: 0.8842 | Val acc: 55.80% | LR: 0.000074
Epoch: 092 | MCC: 0.002382 | Train loss: 0.9692 | Train acc: 51.79% | Val loss: 0.8861 | Val acc: 55.85% | LR: 0.000071
Epoch: 093 | MCC: -0.005433 | Train loss: 0.9668 | Train acc: 51.94% | Val loss: 0.8865 | Val acc: 55.56% | LR: 0.000069
Epoch: 094 | MCC: -0.005153 | Train loss: 0.9689 | Train acc: 52.11% | Val loss: 0.8894 | Val acc: 55.65% | LR: 0.000067
Epoch: 095 | MCC: -0.003595 | Train loss: 0.9682 | Train acc: 51.91% | Val loss: 0.8864 | Val acc: 55.73% | LR: 0.000065
Epoch: 096 | MCC: -0.000253 | Train loss: 0.9679 | Train acc: 51.91% | Val loss: 0.8857 | Val acc: 55.78% | LR: 0.000063
Epoch: 097 | MCC: 0.001545 | Train loss: 0.9664 | Train acc: 51.94% | Val loss: 0.8811 | Val acc: 56.14% | LR: 0.000061
Epoch: 098 | MCC: -0.000389 | Train loss: 0.9705 | Train acc: 51.81% | Val loss: 0.8829 | Val acc: 56.02% | LR: 0.000059
Epoch: 099 | MCC: -0.002271 | Train loss: 0.9664 | Train acc: 51.94% | Val loss: 0.8832 | Val acc: 55.92% | LR: 0.000057
Epoch: 100 | MCC: 0.001509 | Train loss: 0.9674 | Train acc: 51.88% | Val loss: 0.8826 | Val acc: 56.14% | LR: 0.000055
Epoch: 101 | MCC: -0.001566 | Train loss: 0.9664 | Train acc: 51.93% | Val loss: 0.8851 | Val acc: 55.92% | LR: 0.000053
Epoch: 102 | MCC: -0.000570 | Train loss: 0.9660 | Train acc: 51.99% | Val loss: 0.8855 | Val acc: 55.87% | LR: 0.000051
Epoch: 103 | MCC: -0.003456 | Train loss: 0.9666 | Train acc: 51.95% | Val loss: 0.8852 | Val acc: 55.70% | LR: 0.000049
Epoch: 104 | MCC: -0.000723 | Train loss: 0.9675 | Train acc: 51.91% | Val loss: 0.8828 | Val acc: 56.00% | LR: 0.000047
Epoch: 105 | MCC: 0.001091 | Train loss: 0.9665 | Train acc: 51.92% | Val loss: 0.8832 | Val acc: 56.09% | LR: 0.000045
Epoch: 106 | MCC: 0.001054 | Train loss: 0.9662 | Train acc: 51.96% | Val loss: 0.8826 | Val acc: 56.09% | LR: 0.000043
Epoch: 107 | MCC: 0.006802 | Train loss: 0.9678 | Train acc: 51.93% | Val loss: 0.8794 | Val acc: 56.44% | LR: 0.000041
Epoch: 108 | MCC: 0.006354 | Train loss: 0.9674 | Train acc: 51.85% | Val loss: 0.8785 | Val acc: 56.51% | LR: 0.000040
Epoch: 109 | MCC: 0.005836 | Train loss: 0.9669 | Train acc: 51.87% | Val loss: 0.8783 | Val acc: 56.48% | LR: 0.000038
Epoch: 110 | MCC: 0.002911 | Train loss: 0.9662 | Train acc: 51.93% | Val loss: 0.8790 | Val acc: 56.36% | LR: 0.000036
Epoch: 111 | MCC: 0.002381 | Train loss: 0.9680 | Train acc: 51.85% | Val loss: 0.8777 | Val acc: 56.41% | LR: 0.000034
Epoch: 112 | MCC: 0.006224 | Train loss: 0.9670 | Train acc: 51.86% | Val loss: 0.8760 | Val acc: 56.58% | LR: 0.000033
Epoch: 113 | MCC: 0.012359 | Train loss: 0.9734 | Train acc: 51.94% | Val loss: 0.8797 | Val acc: 56.81% | LR: 0.000031
Epoch: 114 | MCC: 0.012359 | Train loss: 0.9699 | Train acc: 51.96% | Val loss: 0.8767 | Val acc: 56.81% | LR: 0.000030
Epoch: 115 | MCC: 0.007813 | Train loss: 0.9655 | Train acc: 52.01% | Val loss: 0.8842 | Val acc: 56.59% | LR: 0.000028
Epoch: 116 | MCC: 0.001872 | Train loss: 0.9678 | Train acc: 51.85% | Val loss: 0.8780 | Val acc: 56.36% | LR: 0.000027
Epoch: 117 | MCC: 0.007312 | Train loss: 0.9658 | Train acc: 51.97% | Val loss: 0.8763 | Val acc: 56.66% | LR: 0.000025
Epoch: 118 | MCC: 0.008529 | Train loss: 0.9662 | Train acc: 51.93% | Val loss: 0.8765 | Val acc: 56.63% | LR: 0.000024

[I 2025-10-05 10:09:15,516] Trial 45 finished with value: 0.008785041980445385 and parameters: {'lr': 0.00022394138121773036, 'hidden_size': 89, 'dropout': 0.20194552392814163, 'weight_decay': 0.0018966481406510849}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.039819 | Train loss: 0.9945 | Train acc: 50.58% | Val loss: 1.0012 | Val acc: 51.04% | LR: 0.000369
Epoch: 001 | MCC: 0.041598 | Train loss: 0.9924 | Train acc: 50.73% | Val loss: 0.9969 | Val acc: 53.48% | LR: 0.000369
Epoch: 002 | MCC: 0.034719 | Train loss: 0.9903 | Train acc: 50.84% | Val loss: 0.9916 | Val acc: 53.99% | LR: 0.000369
Epoch: 003 | MCC: 0.038353 | Train loss: 0.9883 | Train acc: 50.86% | Val loss: 0.9832 | Val acc: 54.59% | LR: 0.000368
Epoch: 004 | MCC: 0.046661 | Train loss: 0.9858 | Train acc: 50.92% | Val loss: 0.9801 | Val acc: 54.92% | LR: 0.000368
Epoch: 005 | MCC: 0.024422 | Train loss: 0.9837 | Train acc: 50.97% | Val loss: 0.9640 | Val acc: 54.47% | LR: 0.000368
Epoch: 006 | MCC: 0.032887 | Train loss: 0.9832 | Train acc: 50.86% | Val loss: 0.9453 | Val acc: 55.19% | LR: 0.000367
Epoch: 007 | MCC: 0.031775 | Train loss: 0.9804 | Train acc: 50.96% | Val loss: 0.9374 | Val acc: 55.21% | LR: 0.000367
Epoch: 008 | MCC: 0.026537 | Train loss: 0.9807 | Train acc: 50.89% | Val loss: 0.9296 | Val acc: 55.19% | LR: 0.000366
Epoch: 009 | MCC: 0.020146 | Train loss: 0.9814 | Train acc: 50.93% | Val loss: 0.9206 | Val acc: 55.33% | LR: 0.000365
Epoch: 010 | MCC: 0.033148 | Train loss: 0.9811 | Train acc: 50.87% | Val loss: 0.9144 | Val acc: 56.06% | LR: 0.000364
Epoch: 011 | MCC: 0.015664 | Train loss: 0.9791 | Train acc: 50.98% | Val loss: 0.9097 | Val acc: 55.54% | LR: 0.000363
Epoch: 012 | MCC: 0.018545 | Train loss: 0.9795 | Train acc: 50.93% | Val loss: 0.9048 | Val acc: 55.78% | LR: 0.000362
Epoch: 013 | MCC: 0.021061 | Train loss: 0.9786 | Train acc: 50.94% | Val loss: 0.8991 | Val acc: 56.02% | LR: 0.000361
Epoch: 014 | MCC: 0.029088 | Train loss: 0.9775 | Train acc: 50.99% | Val loss: 0.8931 | Val acc: 56.64% | LR: 0.000360
Epoch: 015 | MCC: 0.034249 | Train loss: 0.9799 | Train acc: 50.84% | Val loss: 0.8933 | Val acc: 57.14% | LR: 0.000359
Epoch: 016 | MCC: 0.023902 | Train loss: 0.9784 | Train acc: 50.94% | Val loss: 0.9313 | Val acc: 56.74% | LR: 0.000358
Epoch: 017 | MCC: 0.032207 | Train loss: 0.9785 | Train acc: 50.92% | Val loss: 0.8843 | Val acc: 56.38% | LR: 0.000356
Epoch: 018 | MCC: 0.035686 | Train loss: 0.9785 | Train acc: 50.95% | Val loss: 0.8740 | Val acc: 57.38% | LR: 0.000355
Epoch: 019 | MCC: 0.044778 | Train loss: 0.9797 | Train acc: 50.98% | Val loss: 0.8704 | Val acc: 58.69% | LR: 0.000353
Epoch: 020 | MCC: 0.049208 | Train loss: 0.9788 | Train acc: 50.99% | Val loss: 0.8622 | Val acc: 58.78% | LR: 0.000352
Epoch: 021 | MCC: 0.013898 | Train loss: 0.9766 | Train acc: 51.05% | Val loss: 0.8646 | Val acc: 57.40% | LR: 0.000350
Epoch: 022 | MCC: 0.038485 | Train loss: 0.9756 | Train acc: 51.25% | Val loss: 0.8629 | Val acc: 57.99% | LR: 0.000348
Epoch: 023 | MCC: 0.023516 | Train loss: 0.9766 | Train acc: 51.15% | Val loss: 0.8584 | Val acc: 57.82% | LR: 0.000346
Epoch: 024 | MCC: 0.016143 | Train loss: 0.9743 | Train acc: 51.20% | Val loss: 0.8556 | Val acc: 58.00% | LR: 0.000344
Epoch: 025 | MCC: 0.035264 | Train loss: 0.9734 | Train acc: 51.27% | Val loss: 0.8387 | Val acc: 59.88% | LR: 0.000342
Epoch: 026 | MCC: 0.044395 | Train loss: 0.9732 | Train acc: 51.29% | Val loss: 0.8275 | Val acc: 60.56% | LR: 0.000340
Epoch: 027 | MCC: 0.046983 | Train loss: 0.9709 | Train acc: 51.29% | Val loss: 0.8159 | Val acc: 60.67% | LR: 0.000338
Epoch: 028 | MCC: 0.035317 | Train loss: 0.9737 | Train acc: 51.66% | Val loss: 0.8344 | Val acc: 59.08% | LR: 0.000336
Epoch: 029 | MCC: 0.071244 | Train loss: 0.9730 | Train acc: 51.30% | Val loss: 0.8175 | Val acc: 59.57% | LR: 0.000334
Epoch: 030 | MCC: 0.029470 | Train loss: 0.9722 | Train acc: 51.38% | Val loss: 0.8491 | Val acc: 57.91% | LR: 0.000332
Epoch: 031 | MCC: 0.043650 | Train loss: 0.9712 | Train acc: 51.41% | Val loss: 0.8392 | Val acc: 58.51% | LR: 0.000329
Epoch: 032 | MCC: 0.062599 | Train loss: 0.9712 | Train acc: 51.24% | Val loss: 0.8374 | Val acc: 58.95% | LR: 0.000327
Epoch: 033 | MCC: 0.032760 | Train loss: 0.9690 | Train acc: 51.55% | Val loss: 0.8400 | Val acc: 58.91% | LR: 0.000324
Epoch: 034 | MCC: 0.025557 | Train loss: 0.9706 | Train acc: 51.37% | Val loss: 0.8442 | Val acc: 58.26% | LR: 0.000322
Epoch: 035 | MCC: 0.025496 | Train loss: 0.9691 | Train acc: 51.40% | Val loss: 0.8384 | Val acc: 58.45% | LR: 0.000319
Epoch: 036 | MCC: 0.032015 | Train loss: 0.9715 | Train acc: 51.33% | Val loss: 0.8008 | Val acc: 60.69% | LR: 0.000317
Epoch: 037 | MCC: 0.025135 | Train loss: 0.9723 | Train acc: 51.27% | Val loss: 0.8254 | Val acc: 59.31% | LR: 0.000314
Epoch: 038 | MCC: 0.038500 | Train loss: 0.9677 | Train acc: 51.70% | Val loss: 0.8400 | Val acc: 58.59% | LR: 0.000311
Epoch: 039 | MCC: 0.049386 | Train loss: 0.9693 | Train acc: 52.19% | Val loss: 0.8201 | Val acc: 59.71% | LR: 0.000308
Epoch: 040 | MCC: 0.026485 | Train loss: 0.9671 | Train acc: 51.63% | Val loss: 0.8328 | Val acc: 58.78% | LR: 0.000305
Epoch: 041 | MCC: 0.039730 | Train loss: 0.9693 | Train acc: 52.09% | Val loss: 0.8098 | Val acc: 60.25% | LR: 0.000302
Epoch: 042 | MCC: 0.046566 | Train loss: 0.9659 | Train acc: 52.23% | Val loss: 0.8110 | Val acc: 60.05% | LR: 0.000299
Epoch: 043 | MCC: 0.066209 | Train loss: 0.9653 | Train acc: 52.26% | Val loss: 0.8058 | Val acc: 60.65% | LR: 0.000296
Epoch: 044 | MCC: 0.031003 | Train loss: 0.9643 | Train acc: 52.34% | Val loss: 0.8516 | Val acc: 57.88% | LR: 0.000293
Epoch: 045 | MCC: 0.014445 | Train loss: 0.9700 | Train acc: 51.93% | Val loss: 0.8745 | Val acc: 56.46% | LR: 0.000290
Epoch: 046 | MCC: 0.037029 | Train loss: 0.9703 | Train acc: 51.86% | Val loss: 0.8255 | Val acc: 59.10% | LR: 0.000287
Epoch: 047 | MCC: 0.072732 | Train loss: 0.9644 | Train acc: 52.25% | Val loss: 0.8066 | Val acc: 60.45% | LR: 0.000284
Epoch: 048 | MCC: 0.048126 | Train loss: 0.9646 | Train acc: 52.22% | Val loss: 0.8009 | Val acc: 60.49% | LR: 0.000280
Epoch: 049 | MCC: 0.065794 | Train loss: 0.9652 | Train acc: 52.30% | Val loss: 0.8088 | Val acc: 60.38% | LR: 0.000277
Epoch: 050 | MCC: 0.034420 | Train loss: 0.9651 | Train acc: 52.22% | Val loss: 0.7989 | Val acc: 60.62% | LR: 0.000274
Epoch: 051 | MCC: 0.022716 | Train loss: 0.9649 | Train acc: 52.16% | Val loss: 0.8408 | Val acc: 58.64% | LR: 0.000270
Epoch: 052 | MCC: 0.072080 | Train loss: 0.9636 | Train acc: 52.20% | Val loss: 0.7971 | Val acc: 60.87% | LR: 0.000267
Epoch: 053 | MCC: 0.052802 | Train loss: 0.9620 | Train acc: 52.27% | Val loss: 0.7984 | Val acc: 60.30% | LR: 0.000263
Epoch: 054 | MCC: 0.023093 | Train loss: 0.9619 | Train acc: 52.31% | Val loss: 0.8437 | Val acc: 58.34% | LR: 0.000260
Epoch: 055 | MCC: 0.056813 | Train loss: 0.9644 | Train acc: 52.06% | Val loss: 0.8054 | Val acc: 59.99% | LR: 0.000256
Epoch: 056 | MCC: 0.056607 | Train loss: 0.9627 | Train acc: 52.11% | Val loss: 0.8082 | Val acc: 60.11% | LR: 0.000253
Epoch: 057 | MCC: 0.049179 | Train loss: 0.9641 | Train acc: 52.11% | Val loss: 0.8257 | Val acc: 59.00% | LR: 0.000249
Epoch: 058 | MCC: 0.059179 | Train loss: 0.9698 | Train acc: 52.18% | Val loss: 0.8063 | Val acc: 60.20% | LR: 0.000246
Epoch: 059 | MCC: 0.057090 | Train loss: 0.9602 | Train acc: 52.41% | Val loss: 0.8196 | Val acc: 59.40% | LR: 0.000242
Epoch: 060 | MCC: 0.049989 | Train loss: 0.9616 | Train acc: 52.23% | Val loss: 0.8364 | Val acc: 58.50% | LR: 0.000238
Epoch: 061 | MCC: 0.075946 | Train loss: 0.9593 | Train acc: 52.35% | Val loss: 0.7951 | Val acc: 60.55% | LR: 0.000235
Epoch: 062 | MCC: 0.052302 | Train loss: 0.9596 | Train acc: 52.29% | Val loss: 0.8052 | Val acc: 60.21% | LR: 0.000231
Epoch: 063 | MCC: 0.073647 | Train loss: 0.9603 | Train acc: 52.26% | Val loss: 0.8103 | Val acc: 60.02% | LR: 0.000227
Epoch: 064 | MCC: 0.054610 | Train loss: 0.9599 | Train acc: 52.27% | Val loss: 0.8010 | Val acc: 60.34% | LR: 0.000223
Epoch: 065 | MCC: 0.049260 | Train loss: 0.9601 | Train acc: 52.24% | Val loss: 0.8072 | Val acc: 60.04% | LR: 0.000220
Epoch: 066 | MCC: 0.057930 | Train loss: 0.9636 | Train acc: 52.11% | Val loss: 0.8326 | Val acc: 58.76% | LR: 0.000216
Epoch: 067 | MCC: 0.046232 | Train loss: 0.9603 | Train acc: 52.28% | Val loss: 0.8140 | Val acc: 59.73% | LR: 0.000212
Epoch: 068 | MCC: 0.065270 | Train loss: 0.9600 | Train acc: 52.30% | Val loss: 0.8033 | Val acc: 60.17% | LR: 0.000208
Epoch: 069 | MCC: 0.067090 | Train loss: 0.9579 | Train acc: 52.38% | Val loss: 0.8004 | Val acc: 60.50% | LR: 0.000204
Epoch: 070 | MCC: 0.050633 | Train loss: 0.9594 | Train acc: 52.31% | Val loss: 0.8244 | Val acc: 59.30% | LR: 0.000200
Epoch: 071 | MCC: 0.053601 | Train loss: 0.9623 | Train acc: 52.11% | Val loss: 0.8281 | Val acc: 58.87% | LR: 0.000197
Epoch: 072 | MCC: 0.050793 | Train loss: 0.9599 | Train acc: 52.23% | Val loss: 0.8215 | Val acc: 59.37% | LR: 0.000193
Epoch: 073 | MCC: 0.050657 | Train loss: 0.9570 | Train acc: 52.43% | Val loss: 0.8082 | Val acc: 59.92% | LR: 0.000189
Epoch: 074 | MCC: 0.052117 | Train loss: 0.9566 | Train acc: 52.46% | Val loss: 0.8049 | Val acc: 60.27% | LR: 0.000185
Epoch: 075 | MCC: 0.019199 | Train loss: 0.9619 | Train acc: 52.17% | Val loss: 0.8212 | Val acc: 58.93% | LR: 0.000181
Epoch: 076 | MCC: 0.053343 | Train loss: 0.9633 | Train acc: 52.05% | Val loss: 0.8175 | Val acc: 59.71% | LR: 0.000177
Epoch: 077 | MCC: 0.066191 | Train loss: 0.9583 | Train acc: 52.36% | Val loss: 0.8027 | Val acc: 60.37% | LR: 0.000173
Epoch: 078 | MCC: 0.046600 | Train loss: 0.9560 | Train acc: 52.44% | Val loss: 0.8151 | Val acc: 59.62% | LR: 0.000170
Epoch: 079 | MCC: 0.057271 | Train loss: 1.0094 | Train acc: 52.24% | Val loss: 0.8117 | Val acc: 59.93% | LR: 0.000166
Epoch: 080 | MCC: 0.066214 | Train loss: 0.9574 | Train acc: 52.36% | Val loss: 0.8052 | Val acc: 60.37% | LR: 0.000162
Epoch: 081 | MCC: 0.054833 | Train loss: 0.9558 | Train acc: 52.47% | Val loss: 0.8112 | Val acc: 59.96% | LR: 0.000158
Epoch: 082 | MCC: 0.052375 | Train loss: 0.9573 | Train acc: 52.41% | Val loss: 0.8113 | Val acc: 59.85% | LR: 0.000154
Epoch: 083 | MCC: 0.061594 | Train loss: 0.9591 | Train acc: 52.39% | Val loss: 0.8133 | Val acc: 60.00% | LR: 0.000151
Epoch: 084 | MCC: 0.054385 | Train loss: 0.9577 | Train acc: 52.39% | Val loss: 0.8187 | Val acc: 59.49% | LR: 0.000147
Epoch: 085 | MCC: 0.067283 | Train loss: 0.9555 | Train acc: 52.53% | Val loss: 0.8080 | Val acc: 60.12% | LR: 0.000143
Epoch: 086 | MCC: 0.066347 | Train loss: 0.9598 | Train acc: 52.24% | Val loss: 0.8160 | Val acc: 59.71% | LR: 0.000139
Epoch: 087 | MCC: 0.068001 | Train loss: 0.9552 | Train acc: 52.51% | Val loss: 0.8072 | Val acc: 60.24% | LR: 0.000136
Epoch: 088 | MCC: 0.056804 | Train loss: 0.9576 | Train acc: 52.34% | Val loss: 0.8206 | Val acc: 59.43% | LR: 0.000132
Epoch: 089 | MCC: 0.068300 | Train loss: 0.9559 | Train acc: 52.45% | Val loss: 0.8075 | Val acc: 60.17% | LR: 0.000128
Epoch: 090 | MCC: 0.047713 | Train loss: 0.9561 | Train acc: 52.41% | Val loss: 0.8253 | Val acc: 59.24% | LR: 0.000125
Epoch: 091 | MCC: 0.068266 | Train loss: 0.9570 | Train acc: 52.36% | Val loss: 0.7976 | Val acc: 60.60% | LR: 0.000121
Epoch: 092 | MCC: 0.064881 | Train loss: 0.9595 | Train acc: 52.21% | Val loss: 0.8200 | Val acc: 59.64% | LR: 0.000117
Epoch: 093 | MCC: 0.050701 | Train loss: 0.9583 | Train acc: 52.30% | Val loss: 0.8162 | Val acc: 59.51% | LR: 0.000114
Epoch: 094 | MCC: 0.048886 | Train loss: 0.9590 | Train acc: 52.45% | Val loss: 0.8145 | Val acc: 59.61% | LR: 0.000110
Epoch: 095 | MCC: 0.055819 | Train loss: 0.9563 | Train acc: 52.44% | Val loss: 0.8142 | Val acc: 59.64% | LR: 0.000107
Epoch: 096 | MCC: 0.058940 | Train loss: 0.9560 | Train acc: 52.43% | Val loss: 0.8086 | Val acc: 59.97% | LR: 0.000103
Epoch: 097 | MCC: 0.060651 | Train loss: 0.9561 | Train acc: 52.41% | Val loss: 0.8197 | Val acc: 59.68% | LR: 0.000100
Epoch: 098 | MCC: 0.052474 | Train loss: 0.9556 | Train acc: 52.43% | Val loss: 0.8084 | Val acc: 60.12% | LR: 0.000096
Epoch: 099 | MCC: 0.063518 | Train loss: 0.9552 | Train acc: 52.44% | Val loss: 0.8118 | Val acc: 59.93% | LR: 0.000093
Epoch: 100 | MCC: 0.057382 | Train loss: 0.9562 | Train acc: 52.36% | Val loss: 0.8137 | Val acc: 59.76% | LR: 0.000090
Epoch: 101 | MCC: 0.059066 | Train loss: 0.9560 | Train acc: 52.41% | Val loss: 0.8108 | Val acc: 59.92% | LR: 0.000086
Epoch: 102 | MCC: 0.060646 | Train loss: 0.9528 | Train acc: 52.54% | Val loss: 0.8091 | Val acc: 59.88% | LR: 0.000083
Epoch: 103 | MCC: 0.058322 | Train loss: 0.9549 | Train acc: 52.47% | Val loss: 0.8135 | Val acc: 59.78% | LR: 0.000080
Epoch: 104 | MCC: 0.065793 | Train loss: 0.9557 | Train acc: 52.41% | Val loss: 0.8081 | Val acc: 60.17% | LR: 0.000077
Epoch: 105 | MCC: 0.060586 | Train loss: 0.9530 | Train acc: 52.52% | Val loss: 0.8145 | Val acc: 59.80% | LR: 0.000074
Epoch: 106 | MCC: 0.064148 | Train loss: 0.9528 | Train acc: 52.59% | Val loss: 0.8100 | Val acc: 60.24% | LR: 0.000071
Epoch: 107 | MCC: 0.060793 | Train loss: 0.9543 | Train acc: 52.47% | Val loss: 0.8151 | Val acc: 59.78% | LR: 0.000068
Epoch: 108 | MCC: 0.065172 | Train loss: 0.9540 | Train acc: 52.49% | Val loss: 0.8094 | Val acc: 60.10% | LR: 0.000065
Epoch: 109 | MCC: 0.059792 | Train loss: 0.9539 | Train acc: 52.48% | Val loss: 0.8139 | Val acc: 59.80% | LR: 0.000062
Epoch: 110 | MCC: 0.059665 | Train loss: 0.9553 | Train acc: 52.46% | Val loss: 0.8110 | Val acc: 59.88% | LR: 0.000059
Epoch: 111 | MCC: 0.065599 | Train loss: 0.9549 | Train acc: 52.43% | Val loss: 0.8080 | Val acc: 60.24% | LR: 0.000056
Epoch: 112 | MCC: 0.058341 | Train loss: 0.9514 | Train acc: 52.59% | Val loss: 0.8108 | Val acc: 59.78% | LR: 0.000054
Epoch: 113 | MCC: 0.058502 | Train loss: 0.9542 | Train acc: 52.48% | Val loss: 0.8105 | Val acc: 59.83% | LR: 0.000051
Epoch: 114 | MCC: 0.061221 | Train loss: 0.9519 | Train acc: 52.61% | Val loss: 0.8100 | Val acc: 59.98% | LR: 0.000048
Epoch: 115 | MCC: 0.061748 | Train loss: 0.9541 | Train acc: 52.48% | Val loss: 0.8133 | Val acc: 59.90% | LR: 0.000046
Epoch: 116 | MCC: 0.055397 | Train loss: 0.9532 | Train acc: 52.52% | Val loss: 0.8114 | Val acc: 59.76% | LR: 0.000043
Epoch: 117 | MCC: 0.059251 | Train loss: 0.9533 | Train acc: 52.55% | Val loss: 0.8118 | Val acc: 59.80% | LR: 0.000041
Epoch: 118 | MCC: 0.055717 | Train loss: 0.9525 | Train acc: 52.55% | Val loss: 0.8112 | Val acc: 59.76% | LR: 0.000038
Epoch: 119 | MCC: 0.056376 | Train loss: 0.9535 | Train acc: 52.51% | Val loss: 0.8118 | Val acc: 59.78% | LR: 0.000036
Epoch: 120 | MCC: 0.057985 | Train loss: 0.9526 | Train acc: 52.54% | Val loss: 0.8086 | Val acc: 59.95% | LR: 0.000034
Epoch: 121 | MCC: 0.055478 | Train loss: 0.9544 | Train acc: 52.45% | Val loss: 0.8111 | Val acc: 59.76% | LR: 0.000032
Epoch: 122 | MCC: 0.054084 | Train loss: 0.9530 | Train acc: 52.55% | Val loss: 0.8097 | Val acc: 59.78% | LR: 0.000030
Epoch: 123 | MCC: 0.054624 | Train loss: 0.9557 | Train acc: 52.39% | Val loss: 0.8105 | Val acc: 59.73% | LR: 0.000028
Epoch: 124 | MCC: 0.057379 | Train loss: 0.9555 | Train acc: 52.41% | Val loss: 0.8102 | Val acc: 59.85% | LR: 0.000026
Epoch: 125 | MCC: 0.058589 | Train loss: 0.9520 | Train acc: 52.58% | Val loss: 0.8093 | Val acc: 59.95% | LR: 0.000024
Epoch: 126 | MCC: 0.053311 | Train loss: 0.9533 | Train acc: 52.50% | Val loss: 0.8112 | Val acc: 59.71% | LR: 0.000022
Epoch: 127 | MCC: 0.054994 | Train loss: 0.9530 | Train acc: 52.53% | Val loss: 0.8096 | Val acc: 59.80% | LR: 0.000020
Epoch: 128 | MCC: 0.055080 | Train loss: 0.9496 | Train acc: 52.70% | Val loss: 0.8112 | Val acc: 59.76% | LR: 0.000019
Epoch: 129 | MCC: 0.055536 | Train loss: 0.9553 | Train acc: 52.42% | Val loss: 0.8110 | Val acc: 59.78% | LR: 0.000017
Epoch: 130 | MCC: 0.054819 | Train loss: 0.9512 | Train acc: 52.62% | Val loss: 0.8108 | Val acc: 59.78% | LR: 0.000015
Epoch: 131 | MCC: 0.058822 | Train loss: 0.9539 | Train acc: 52.49% | Val loss: 0.8085 | Val acc: 60.02% | LR: 0.000014
Epoch: 132 | MCC: 0.053948 | Train loss: 0.9532 | Train acc: 52.53% | Val loss: 0.8113 | Val acc: 59.76% | LR: 0.000013
Epoch: 133 | MCC: 0.053697 | Train loss: 0.9522 | Train acc: 52.56% | Val loss: 0.8095 | Val acc: 59.73% | LR: 0.000011
Epoch: 134 | MCC: 0.054555 | Train loss: 0.9536 | Train acc: 52.49% | Val loss: 0.8126 | Val acc: 59.76% | LR: 0.000010
Epoch: 135 | MCC: 0.051964 | Train loss: 0.9544 | Train acc: 52.47% | Val loss: 0.8103 | Val acc: 59.68% | LR: 0.000009

[I 2025-10-05 10:11:21,789] Trial 46 finished with value: 0.05301601649262011 and parameters: {'lr': 0.00036907842265423334, 'hidden_size': 78, 'dropout': 0.12003456484071409, 'weight_decay': 0.005061031219313902}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.037549 | Train loss: 0.9946 | Train acc: 50.60% | Val loss: 1.0000 | Val acc: 51.08% | LR: 0.000131
Epoch: 001 | MCC: 0.035079 | Train loss: 0.9941 | Train acc: 50.77% | Val loss: 0.9986 | Val acc: 52.99% | LR: 0.000131
Epoch: 002 | MCC: 0.037489 | Train loss: 0.9927 | Train acc: 50.75% | Val loss: 0.9959 | Val acc: 54.27% | LR: 0.000131
Epoch: 003 | MCC: 0.034468 | Train loss: 0.9901 | Train acc: 50.84% | Val loss: 0.9933 | Val acc: 54.45% | LR: 0.000131
Epoch: 004 | MCC: 0.038017 | Train loss: 0.9897 | Train acc: 50.90% | Val loss: 0.9922 | Val acc: 54.37% | LR: 0.000131
Epoch: 005 | MCC: 0.035513 | Train loss: 0.9885 | Train acc: 50.90% | Val loss: 0.9879 | Val acc: 54.69% | LR: 0.000131
Epoch: 006 | MCC: 0.037359 | Train loss: 0.9874 | Train acc: 50.88% | Val loss: 0.9833 | Val acc: 54.79% | LR: 0.000131
Epoch: 007 | MCC: 0.036728 | Train loss: 1.0414 | Train acc: 50.88% | Val loss: 0.9793 | Val acc: 54.79% | LR: 0.000131
Epoch: 008 | MCC: 0.034630 | Train loss: 0.9943 | Train acc: 50.88% | Val loss: 0.9751 | Val acc: 54.67% | LR: 0.000130
Epoch: 009 | MCC: 0.021760 | Train loss: 0.9871 | Train acc: 50.98% | Val loss: 0.9704 | Val acc: 54.18% | LR: 0.000130
Epoch: 010 | MCC: 0.026582 | Train loss: 0.9863 | Train acc: 50.94% | Val loss: 0.9673 | Val acc: 54.40% | LR: 0.000130
Epoch: 011 | MCC: 0.026308 | Train loss: 0.9840 | Train acc: 51.05% | Val loss: 0.9581 | Val acc: 54.45% | LR: 0.000129
Epoch: 012 | MCC: 0.025788 | Train loss: 0.9865 | Train acc: 50.92% | Val loss: 0.9600 | Val acc: 54.67% | LR: 0.000129
Epoch: 013 | MCC: 0.023532 | Train loss: 0.9814 | Train acc: 50.95% | Val loss: 0.9556 | Val acc: 54.55% | LR: 0.000129
Epoch: 014 | MCC: 0.024700 | Train loss: 0.9800 | Train acc: 51.04% | Val loss: 0.9528 | Val acc: 54.72% | LR: 0.000128
Epoch: 015 | MCC: 0.023694 | Train loss: 0.9824 | Train acc: 50.88% | Val loss: 0.9500 | Val acc: 54.68% | LR: 0.000128
Epoch: 016 | MCC: 0.029534 | Train loss: 0.9814 | Train acc: 50.91% | Val loss: 0.9473 | Val acc: 55.15% | LR: 0.000127
Epoch: 017 | MCC: 0.031730 | Train loss: 0.9817 | Train acc: 50.94% | Val loss: 0.9440 | Val acc: 55.28% | LR: 0.000127
Epoch: 018 | MCC: 0.030920 | Train loss: 0.9814 | Train acc: 50.87% | Val loss: 0.9408 | Val acc: 55.13% | LR: 0.000126
Epoch: 019 | MCC: 0.033151 | Train loss: 0.9812 | Train acc: 50.91% | Val loss: 0.9391 | Val acc: 55.31% | LR: 0.000126
Epoch: 020 | MCC: 0.032083 | Train loss: 0.9820 | Train acc: 50.78% | Val loss: 0.9374 | Val acc: 55.19% | LR: 0.000125
Epoch: 021 | MCC: 0.030189 | Train loss: 0.9800 | Train acc: 50.90% | Val loss: 0.9367 | Val acc: 54.98% | LR: 0.000125
Epoch: 022 | MCC: 0.025097 | Train loss: 0.9797 | Train acc: 50.97% | Val loss: 0.9354 | Val acc: 54.97% | LR: 0.000124
Epoch: 023 | MCC: 0.024426 | Train loss: 0.9806 | Train acc: 50.86% | Val loss: 0.9335 | Val acc: 55.00% | LR: 0.000123
Epoch: 024 | MCC: 0.020049 | Train loss: 0.9810 | Train acc: 50.84% | Val loss: 0.9316 | Val acc: 54.98% | LR: 0.000123
Epoch: 025 | MCC: 0.020959 | Train loss: 0.9797 | Train acc: 50.95% | Val loss: 0.9295 | Val acc: 55.08% | LR: 0.000122
Epoch: 026 | MCC: 0.021444 | Train loss: 0.9806 | Train acc: 50.90% | Val loss: 0.9280 | Val acc: 55.12% | LR: 0.000121
Epoch: 027 | MCC: 0.022213 | Train loss: 0.9805 | Train acc: 50.87% | Val loss: 0.9263 | Val acc: 55.21% | LR: 0.000121
Epoch: 028 | MCC: 0.017762 | Train loss: 0.9807 | Train acc: 51.01% | Val loss: 0.9240 | Val acc: 55.42% | LR: 0.000120
Epoch: 029 | MCC: 0.020757 | Train loss: 0.9808 | Train acc: 50.91% | Val loss: 0.9217 | Val acc: 55.54% | LR: 0.000119
Epoch: 030 | MCC: 0.018630 | Train loss: 0.9788 | Train acc: 51.04% | Val loss: 0.9191 | Val acc: 55.43% | LR: 0.000118
Epoch: 031 | MCC: 0.019432 | Train loss: 0.9786 | Train acc: 50.94% | Val loss: 0.9165 | Val acc: 55.42% | LR: 0.000117
Epoch: 032 | MCC: 0.019211 | Train loss: 0.9790 | Train acc: 50.85% | Val loss: 0.9146 | Val acc: 55.40% | LR: 0.000117
Epoch: 033 | MCC: 0.019714 | Train loss: 0.9784 | Train acc: 51.01% | Val loss: 0.9129 | Val acc: 55.56% | LR: 0.000116
Epoch: 034 | MCC: 0.016914 | Train loss: 0.9794 | Train acc: 50.93% | Val loss: 0.9112 | Val acc: 55.56% | LR: 0.000115
Epoch: 035 | MCC: 0.016933 | Train loss: 0.9788 | Train acc: 50.93% | Val loss: 0.9096 | Val acc: 55.62% | LR: 0.000114
Epoch: 036 | MCC: 0.021191 | Train loss: 0.9787 | Train acc: 50.94% | Val loss: 0.9078 | Val acc: 55.86% | LR: 0.000113
Epoch: 037 | MCC: 0.021936 | Train loss: 0.9779 | Train acc: 51.00% | Val loss: 0.9063 | Val acc: 55.95% | LR: 0.000112
Epoch: 038 | MCC: 0.022836 | Train loss: 0.9779 | Train acc: 50.93% | Val loss: 0.9041 | Val acc: 56.09% | LR: 0.000111
Epoch: 039 | MCC: 0.021675 | Train loss: 0.9770 | Train acc: 51.00% | Val loss: 0.9022 | Val acc: 56.08% | LR: 0.000110
Epoch: 040 | MCC: 0.021517 | Train loss: 0.9764 | Train acc: 51.00% | Val loss: 0.9005 | Val acc: 56.08% | LR: 0.000109
Epoch: 041 | MCC: 0.021222 | Train loss: 1.0274 | Train acc: 50.77% | Val loss: 0.8994 | Val acc: 56.01% | LR: 0.000108
Epoch: 042 | MCC: 0.030662 | Train loss: 0.9776 | Train acc: 50.92% | Val loss: 0.8971 | Val acc: 56.45% | LR: 0.000107
Epoch: 043 | MCC: 0.031126 | Train loss: 0.9777 | Train acc: 50.85% | Val loss: 0.8962 | Val acc: 56.52% | LR: 0.000106
Epoch: 044 | MCC: 0.029954 | Train loss: 0.9767 | Train acc: 50.87% | Val loss: 0.8948 | Val acc: 56.37% | LR: 0.000105
Epoch: 045 | MCC: 0.028606 | Train loss: 0.9840 | Train acc: 50.89% | Val loss: 0.8932 | Val acc: 56.20% | LR: 0.000103
Epoch: 046 | MCC: 0.028280 | Train loss: 0.9776 | Train acc: 50.91% | Val loss: 0.8913 | Val acc: 56.37% | LR: 0.000102
Epoch: 047 | MCC: 0.026898 | Train loss: 0.9769 | Train acc: 50.90% | Val loss: 0.8888 | Val acc: 56.26% | LR: 0.000101
Epoch: 048 | MCC: 0.030804 | Train loss: 0.9770 | Train acc: 50.93% | Val loss: 0.8876 | Val acc: 56.44% | LR: 0.000100
Epoch: 049 | MCC: 0.030709 | Train loss: 0.9774 | Train acc: 50.79% | Val loss: 0.8855 | Val acc: 56.49% | LR: 0.000099
Epoch: 050 | MCC: 0.027836 | Train loss: 0.9769 | Train acc: 50.84% | Val loss: 0.8839 | Val acc: 56.57% | LR: 0.000098
Epoch: 051 | MCC: 0.036384 | Train loss: 0.9759 | Train acc: 50.99% | Val loss: 0.8820 | Val acc: 56.88% | LR: 0.000096
Epoch: 052 | MCC: 0.039309 | Train loss: 0.9752 | Train acc: 51.14% | Val loss: 0.8797 | Val acc: 57.21% | LR: 0.000095
Epoch: 053 | MCC: 0.044461 | Train loss: 0.9764 | Train acc: 50.84% | Val loss: 0.8790 | Val acc: 57.42% | LR: 0.000094
Epoch: 054 | MCC: 0.038838 | Train loss: 0.9757 | Train acc: 51.72% | Val loss: 0.8777 | Val acc: 57.58% | LR: 0.000093
Epoch: 055 | MCC: 0.043944 | Train loss: 0.9763 | Train acc: 51.75% | Val loss: 0.8760 | Val acc: 57.88% | LR: 0.000092
Epoch: 056 | MCC: 0.049398 | Train loss: 0.9745 | Train acc: 51.86% | Val loss: 0.8735 | Val acc: 58.13% | LR: 0.000090
Epoch: 057 | MCC: 0.036873 | Train loss: 0.9753 | Train acc: 51.68% | Val loss: 0.8731 | Val acc: 58.08% | LR: 0.000089
Epoch: 058 | MCC: 0.037535 | Train loss: 0.9745 | Train acc: 51.70% | Val loss: 0.8710 | Val acc: 58.20% | LR: 0.000088
Epoch: 059 | MCC: 0.039165 | Train loss: 0.9754 | Train acc: 51.91% | Val loss: 0.8703 | Val acc: 58.26% | LR: 0.000086
Epoch: 060 | MCC: 0.036340 | Train loss: 0.9764 | Train acc: 51.71% | Val loss: 0.8691 | Val acc: 58.18% | LR: 0.000085
Epoch: 061 | MCC: 0.036926 | Train loss: 0.9744 | Train acc: 51.81% | Val loss: 0.8677 | Val acc: 58.04% | LR: 0.000084
Epoch: 062 | MCC: 0.037238 | Train loss: 0.9741 | Train acc: 51.79% | Val loss: 0.8662 | Val acc: 58.16% | LR: 0.000082
Epoch: 063 | MCC: 0.036874 | Train loss: 0.9737 | Train acc: 51.73% | Val loss: 0.8647 | Val acc: 58.06% | LR: 0.000081
Epoch: 064 | MCC: 0.035157 | Train loss: 0.9756 | Train acc: 51.59% | Val loss: 0.8632 | Val acc: 58.06% | LR: 0.000080
Epoch: 065 | MCC: 0.036363 | Train loss: 0.9788 | Train acc: 51.78% | Val loss: 0.8622 | Val acc: 58.11% | LR: 0.000078
Epoch: 066 | MCC: 0.036426 | Train loss: 0.9739 | Train acc: 51.73% | Val loss: 0.8608 | Val acc: 58.18% | LR: 0.000077
Epoch: 067 | MCC: 0.036246 | Train loss: 0.9729 | Train acc: 51.85% | Val loss: 0.8604 | Val acc: 58.11% | LR: 0.000076
Epoch: 068 | MCC: 0.035280 | Train loss: 0.9731 | Train acc: 51.77% | Val loss: 0.8610 | Val acc: 57.99% | LR: 0.000074
Epoch: 069 | MCC: 0.008063 | Train loss: 0.9718 | Train acc: 51.87% | Val loss: 0.8701 | Val acc: 57.64% | LR: 0.000073
Epoch: 070 | MCC: 0.026745 | Train loss: 0.9757 | Train acc: 51.87% | Val loss: 0.8628 | Val acc: 58.18% | LR: 0.000072
Epoch: 071 | MCC: 0.009850 | Train loss: 0.9757 | Train acc: 51.77% | Val loss: 0.8662 | Val acc: 58.00% | LR: 0.000070
Epoch: 072 | MCC: 0.018053 | Train loss: 0.9731 | Train acc: 51.78% | Val loss: 0.8844 | Val acc: 57.86% | LR: 0.000069
Epoch: 073 | MCC: 0.011463 | Train loss: 0.9718 | Train acc: 51.83% | Val loss: 0.8602 | Val acc: 58.35% | LR: 0.000068
Epoch: 074 | MCC: 0.007746 | Train loss: 0.9796 | Train acc: 51.85% | Val loss: 0.8664 | Val acc: 58.13% | LR: 0.000066
Epoch: 075 | MCC: 0.030186 | Train loss: 0.9757 | Train acc: 51.79% | Val loss: 0.8575 | Val acc: 59.31% | LR: 0.000065
Epoch: 076 | MCC: 0.027589 | Train loss: 0.9754 | Train acc: 51.56% | Val loss: 0.8742 | Val acc: 58.77% | LR: 0.000064
Epoch: 077 | MCC: 0.031852 | Train loss: 0.9756 | Train acc: 51.66% | Val loss: 0.8486 | Val acc: 59.55% | LR: 0.000062
Epoch: 078 | MCC: 0.036748 | Train loss: 0.9722 | Train acc: 51.85% | Val loss: 0.8461 | Val acc: 59.67% | LR: 0.000061
Epoch: 079 | MCC: 0.031528 | Train loss: 0.9759 | Train acc: 51.64% | Val loss: 0.8505 | Val acc: 59.50% | LR: 0.000059
Epoch: 080 | MCC: 0.033469 | Train loss: 0.9753 | Train acc: 51.71% | Val loss: 0.8582 | Val acc: 59.04% | LR: 0.000058
Epoch: 081 | MCC: 0.034211 | Train loss: 0.9720 | Train acc: 51.81% | Val loss: 0.8482 | Val acc: 59.37% | LR: 0.000057
Epoch: 082 | MCC: 0.012110 | Train loss: 0.9806 | Train acc: 51.69% | Val loss: 0.8598 | Val acc: 59.03% | LR: 0.000055
Epoch: 083 | MCC: 0.030124 | Train loss: 0.9754 | Train acc: 51.70% | Val loss: 0.8509 | Val acc: 59.08% | LR: 0.000054
Epoch: 084 | MCC: 0.040756 | Train loss: 0.9922 | Train acc: 51.69% | Val loss: 0.8610 | Val acc: 59.76% | LR: 0.000053
Epoch: 085 | MCC: 0.026164 | Train loss: 0.9730 | Train acc: 51.75% | Val loss: 0.8544 | Val acc: 58.96% | LR: 0.000051
Epoch: 086 | MCC: 0.035699 | Train loss: 0.9776 | Train acc: 51.44% | Val loss: 0.8469 | Val acc: 59.44% | LR: 0.000050
Epoch: 087 | MCC: 0.029390 | Train loss: 0.9846 | Train acc: 51.62% | Val loss: 0.8497 | Val acc: 59.36% | LR: 0.000049
Epoch: 088 | MCC: 0.028279 | Train loss: 0.9906 | Train acc: 51.66% | Val loss: 0.8491 | Val acc: 59.31% | LR: 0.000047
Epoch: 089 | MCC: 0.034416 | Train loss: 0.9790 | Train acc: 51.68% | Val loss: 0.8454 | Val acc: 59.37% | LR: 0.000046
Epoch: 090 | MCC: 0.025439 | Train loss: 0.9803 | Train acc: 51.69% | Val loss: 0.8539 | Val acc: 59.09% | LR: 0.000045
Epoch: 091 | MCC: 0.025307 | Train loss: 0.9769 | Train acc: 51.67% | Val loss: 0.9188 | Val acc: 58.94% | LR: 0.000044
Epoch: 092 | MCC: 0.033718 | Train loss: 0.9739 | Train acc: 51.58% | Val loss: 0.8465 | Val acc: 59.32% | LR: 0.000042
Epoch: 093 | MCC: 0.024721 | Train loss: 0.9740 | Train acc: 51.65% | Val loss: 0.8539 | Val acc: 59.06% | LR: 0.000041
Epoch: 094 | MCC: 0.030562 | Train loss: 0.9737 | Train acc: 51.73% | Val loss: 0.8824 | Val acc: 59.09% | LR: 0.000040
Epoch: 095 | MCC: 0.018395 | Train loss: 0.9745 | Train acc: 51.63% | Val loss: 0.8457 | Val acc: 59.27% | LR: 0.000038
Epoch: 096 | MCC: 0.016135 | Train loss: 0.9741 | Train acc: 51.72% | Val loss: 0.8517 | Val acc: 59.08% | LR: 0.000037
Epoch: 097 | MCC: 0.014630 | Train loss: 0.9750 | Train acc: 51.61% | Val loss: 0.8562 | Val acc: 58.86% | LR: 0.000036
Epoch: 098 | MCC: 0.015991 | Train loss: 0.9740 | Train acc: 51.67% | Val loss: 0.8545 | Val acc: 59.17% | LR: 0.000035
Epoch: 099 | MCC: 0.015750 | Train loss: 0.9727 | Train acc: 51.77% | Val loss: 0.8495 | Val acc: 59.13% | LR: 0.000034
Epoch: 100 | MCC: 0.035228 | Train loss: 0.9846 | Train acc: 51.60% | Val loss: 0.8532 | Val acc: 59.34% | LR: 0.000032
Epoch: 101 | MCC: 0.030966 | Train loss: 0.9732 | Train acc: 51.66% | Val loss: 0.8975 | Val acc: 59.18% | LR: 0.000031
Epoch: 102 | MCC: 0.031495 | Train loss: 0.9721 | Train acc: 51.77% | Val loss: 0.8497 | Val acc: 59.26% | LR: 0.000030
Epoch: 103 | MCC: 0.030939 | Train loss: 0.9732 | Train acc: 51.58% | Val loss: 0.8494 | Val acc: 59.15% | LR: 0.000029
Epoch: 104 | MCC: 0.036660 | Train loss: 0.9740 | Train acc: 51.59% | Val loss: 0.8488 | Val acc: 59.40% | LR: 0.000028
Epoch: 105 | MCC: 0.032096 | Train loss: 0.9772 | Train acc: 51.68% | Val loss: 0.8672 | Val acc: 59.21% | LR: 0.000027
Epoch: 106 | MCC: 0.034449 | Train loss: 0.9709 | Train acc: 51.77% | Val loss: 0.8509 | Val acc: 59.31% | LR: 0.000026
Epoch: 107 | MCC: 0.032943 | Train loss: 0.9732 | Train acc: 51.59% | Val loss: 0.8518 | Val acc: 59.23% | LR: 0.000025
Epoch: 108 | MCC: 0.031012 | Train loss: 0.9735 | Train acc: 51.64% | Val loss: 0.8534 | Val acc: 59.11% | LR: 0.000024
Epoch: 109 | MCC: 0.029556 | Train loss: 0.9749 | Train acc: 51.62% | Val loss: 0.8542 | Val acc: 59.06% | LR: 0.000023
Epoch: 110 | MCC: 0.033639 | Train loss: 0.9742 | Train acc: 51.58% | Val loss: 0.8502 | Val acc: 59.26% | LR: 0.000022
Epoch: 111 | MCC: 0.032802 | Train loss: 0.9887 | Train acc: 51.68% | Val loss: 0.8508 | Val acc: 59.17% | LR: 0.000021
Epoch: 112 | MCC: 0.028887 | Train loss: 0.9850 | Train acc: 51.76% | Val loss: 0.8551 | Val acc: 58.99% | LR: 0.000020
Epoch: 113 | MCC: 0.030256 | Train loss: 0.9736 | Train acc: 51.72% | Val loss: 0.8503 | Val acc: 59.06% | LR: 0.000019
Epoch: 114 | MCC: 0.014670 | Train loss: 1.0644 | Train acc: 51.78% | Val loss: 0.8561 | Val acc: 58.85% | LR: 0.000018
Epoch: 115 | MCC: 0.014304 | Train loss: 1.2287 | Train acc: 51.70% | Val loss: 0.8581 | Val acc: 58.87% | LR: 0.000017
Epoch: 116 | MCC: 0.029966 | Train loss: 0.9744 | Train acc: 51.75% | Val loss: 0.8737 | Val acc: 59.06% | LR: 0.000016
Epoch: 117 | MCC: 0.029966 | Train loss: 0.9735 | Train acc: 51.74% | Val loss: 0.8513 | Val acc: 59.06% | LR: 0.000015
Epoch: 118 | MCC: 0.029736 | Train loss: 0.9730 | Train acc: 51.71% | Val loss: 0.8525 | Val acc: 59.06% | LR: 0.000014
Epoch: 119 | MCC: 0.029504 | Train loss: 0.9798 | Train acc: 51.64% | Val loss: 0.8512 | Val acc: 59.04% | LR: 0.000013
Epoch: 120 | MCC: 0.028577 | Train loss: 0.9738 | Train acc: 51.80% | Val loss: 0.8568 | Val acc: 58.96% | LR: 0.000013
Epoch: 121 | MCC: 0.028750 | Train loss: 0.9750 | Train acc: 51.60% | Val loss: 0.8520 | Val acc: 59.01% | LR: 0.000012
Epoch: 122 | MCC: 0.024774 | Train loss: 0.9731 | Train acc: 51.76% | Val loss: 0.8562 | Val acc: 58.84% | LR: 0.000011
Epoch: 123 | MCC: 0.027690 | Train loss: 0.9795 | Train acc: 51.61% | Val loss: 0.9488 | Val acc: 58.94% | LR: 0.000010
Epoch: 124 | MCC: 0.030160 | Train loss: 0.9814 | Train acc: 51.55% | Val loss: 0.8498 | Val acc: 59.09% | LR: 0.000010
Epoch: 125 | MCC: 0.029634 | Train loss: 0.9764 | Train acc: 51.67% | Val loss: 0.8582 | Val acc: 59.14% | LR: 0.000009
Epoch: 126 | MCC: 0.029997 | Train loss: 0.9839 | Train acc: 51.66% | Val loss: 0.8512 | Val acc: 59.11% | LR: 0.000008
Epoch: 127 | MCC: 0.028222 | Train loss: 0.9744 | Train acc: 51.65% | Val loss: 0.8615 | Val acc: 59.01% | LR: 0.000008
Epoch: 128 | MCC: 0.013177 | Train loss: 0.9715 | Train acc: 51.81% | Val loss: 0.8556 | Val acc: 58.93% | LR: 0.000007
Epoch: 129 | MCC: 0.014333 | Train loss: 0.9733 | Train acc: 51.59% | Val loss: 0.8504 | Val acc: 59.00% | LR: 0.000007
Epoch: 130 | MCC: 0.010413 | Train loss: 0.9720 | Train acc: 51.75% | Val loss: 0.8559 | Val acc: 58.78% | LR: 0.000006
Epoch: 131 | MCC: 0.012251 | Train loss: 0.9739 | Train acc: 51.62% | Val loss: 0.8609 | Val acc: 58.88% | LR: 0.000006
Epoch: 132 | MCC: 0.011652 | Train loss: 0.9724 | Train acc: 51.71% | Val loss: 0.8557 | Val acc: 58.83% | LR: 0.000005
Epoch: 133 | MCC: 0.012614 | Train loss: 0.9734 | Train acc: 51.68% | Val loss: 0.8546 | Val acc: 58.86% | LR: 0.000005
Epoch: 134 | MCC: 0.014154 | Train loss: 0.9732 | Train acc: 51.62% | Val loss: 0.8502 | Val acc: 58.95% | LR: 0.000004
Epoch: 135 | MCC: 0.012614 | Train loss: 0.9728 | Train acc: 51.60% | Val loss: 0.8542 | Val acc: 58.86% | LR: 0.000004
Epoch: 136 | MCC: 0.011766 | Train loss: 0.9728 | Train acc: 51.65% | Val loss: 0.8590 | Val acc: 58.81% | LR: 0.000003
Epoch: 137 | MCC: 0.009731 | Train loss: 0.9729 | Train acc: 51.62% | Val loss: 0.8583 | Val acc: 58.71% | LR: 0.000003
Epoch: 138 | MCC: 0.011766 | Train loss: 0.9730 | Train acc: 51.71% | Val loss: 0.8538 | Val acc: 58.81% | LR: 0.000003
Epoch: 139 | MCC: 0.011766 | Train loss: 0.9724 | Train acc: 51.72% | Val loss: 0.8526 | Val acc: 58.81% | LR: 0.000002
Epoch: 140 | MCC: 0.011766 | Train loss: 0.9717 | Train acc: 51.72% | Val loss: 0.8539 | Val acc: 58.81% | LR: 0.000002
Epoch: 141 | MCC: 0.010308 | Train loss: 0.9719 | Train acc: 51.77% | Val loss: 0.8569 | Val acc: 58.71% | LR: 0.000002
Epoch: 142 | MCC: 0.010308 | Train loss: 0.9722 | Train acc: 51.63% | Val loss: 0.8666 | Val acc: 58.71% | LR: 0.000002
Epoch: 143 | MCC: 0.010308 | Train loss: 0.9719 | Train acc: 51.67% | Val loss: 0.8617 | Val acc: 58.71% | LR: 0.000002
Epoch: 144 | MCC: 0.011617 | Train loss: 0.9726 | Train acc: 51.74% | Val loss: 0.8531 | Val acc: 58.78% | LR: 0.000001
Epoch: 145 | MCC: 0.011617 | Train loss: 0.9739 | Train acc: 51.59% | Val loss: 0.8526 | Val acc: 58.78% | LR: 0.000001
Epoch: 146 | MCC: 0.011617 | Train loss: 0.9725 | Train acc: 51.66% | Val loss: 0.8522 | Val acc: 58.78% | LR: 0.000001
Epoch: 147 | MCC: 0.011617 | Train loss: 0.9715 | Train acc: 51.75% | Val loss: 0.8523 | Val acc: 58.78% | LR: 0.000001
Epoch: 148 | MCC: 0.011617 | Train loss: 0.9712 | Train acc: 51.85% | Val loss: 0.8526 | Val acc: 58.78% | LR: 0.000001
Epoch: 149 | MCC: 0.011617 | Train loss: 0.9721 | Train acc: 51.66% | Val loss: 0.8526 | Val acc: 58.78% | LR: 0.000001

[I 2025-10-05 10:13:36,430] Trial 47 finished with value: 0.011617486365139484 and parameters: {'lr': 0.00013148540050234733, 'hidden_size': 78, 'dropout': 0.3686411805438962, 'weight_decay': 0.007883017640506841}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: -0.016386 | Train loss: 0.9986 | Train acc: 50.57% | Val loss: 1.0102 | Val acc: 44.97% | LR: 0.000343
Epoch: 001 | MCC: 0.001433 | Train loss: 0.9969 | Train acc: 50.63% | Val loss: 1.0156 | Val acc: 45.36% | LR: 0.000342
Epoch: 002 | MCC: -0.017789 | Train loss: 0.9959 | Train acc: 50.63% | Val loss: 1.0090 | Val acc: 45.01% | LR: 0.000342
Epoch: 003 | MCC: -0.013464 | Train loss: 1.0014 | Train acc: 50.65% | Val loss: 1.1076 | Val acc: 45.21% | LR: 0.000342
Epoch: 004 | MCC: 0.012779 | Train loss: 0.9925 | Train acc: 50.83% | Val loss: 1.0274 | Val acc: 45.42% | LR: 0.000342
Epoch: 005 | MCC: -0.000183 | Train loss: 0.9930 | Train acc: 50.62% | Val loss: 1.0119 | Val acc: 45.44% | LR: 0.000341
Epoch: 006 | MCC: 0.050981 | Train loss: 0.9905 | Train acc: 50.60% | Val loss: 1.0240 | Val acc: 49.88% | LR: 0.000341
Epoch: 007 | MCC: 0.033441 | Train loss: 0.9900 | Train acc: 50.72% | Val loss: 1.0008 | Val acc: 52.22% | LR: 0.000340
Epoch: 008 | MCC: 0.024420 | Train loss: 0.9892 | Train acc: 50.85% | Val loss: 0.9954 | Val acc: 53.41% | LR: 0.000340
Epoch: 009 | MCC: 0.029330 | Train loss: 0.9873 | Train acc: 50.90% | Val loss: 0.9872 | Val acc: 54.31% | LR: 0.000339
Epoch: 010 | MCC: 0.025398 | Train loss: 0.9890 | Train acc: 50.81% | Val loss: 0.9951 | Val acc: 54.11% | LR: 0.000338
Epoch: 011 | MCC: 0.023586 | Train loss: 0.9877 | Train acc: 50.85% | Val loss: 0.9956 | Val acc: 54.36% | LR: 0.000337
Epoch: 012 | MCC: 0.003583 | Train loss: 0.9858 | Train acc: 51.07% | Val loss: 0.9834 | Val acc: 53.42% | LR: 0.000336
Epoch: 013 | MCC: 0.013425 | Train loss: 0.9868 | Train acc: 51.02% | Val loss: 0.9795 | Val acc: 53.52% | LR: 0.000335
Epoch: 014 | MCC: 0.013468 | Train loss: 0.9843 | Train acc: 51.08% | Val loss: 0.9778 | Val acc: 53.44% | LR: 0.000334
Epoch: 015 | MCC: 0.025531 | Train loss: 0.9877 | Train acc: 50.92% | Val loss: 0.9841 | Val acc: 53.95% | LR: 0.000333
Epoch: 016 | MCC: 0.027054 | Train loss: 0.9845 | Train acc: 50.94% | Val loss: 0.9743 | Val acc: 53.82% | LR: 0.000332
Epoch: 017 | MCC: 0.027928 | Train loss: 0.9851 | Train acc: 51.01% | Val loss: 0.9720 | Val acc: 53.96% | LR: 0.000331
Epoch: 018 | MCC: 0.019592 | Train loss: 0.9845 | Train acc: 50.96% | Val loss: 0.9686 | Val acc: 53.69% | LR: 0.000329
Epoch: 019 | MCC: 0.019123 | Train loss: 0.9837 | Train acc: 50.95% | Val loss: 0.9657 | Val acc: 53.70% | LR: 0.000328
Epoch: 020 | MCC: 0.024781 | Train loss: 0.9831 | Train acc: 50.96% | Val loss: 0.9631 | Val acc: 53.90% | LR: 0.000326
Epoch: 021 | MCC: 0.025103 | Train loss: 0.9821 | Train acc: 50.97% | Val loss: 0.9622 | Val acc: 54.01% | LR: 0.000325
Epoch: 022 | MCC: 0.025566 | Train loss: 0.9831 | Train acc: 50.87% | Val loss: 0.9623 | Val acc: 53.96% | LR: 0.000323
Epoch: 023 | MCC: 0.025184 | Train loss: 0.9814 | Train acc: 51.02% | Val loss: 0.9596 | Val acc: 53.96% | LR: 0.000322
Epoch: 024 | MCC: 0.024876 | Train loss: 0.9806 | Train acc: 51.02% | Val loss: 0.9558 | Val acc: 54.03% | LR: 0.000320
Epoch: 025 | MCC: 0.030271 | Train loss: 0.9829 | Train acc: 50.81% | Val loss: 0.9519 | Val acc: 54.46% | LR: 0.000318
Epoch: 026 | MCC: 0.028332 | Train loss: 0.9798 | Train acc: 50.98% | Val loss: 0.9488 | Val acc: 54.39% | LR: 0.000316
Epoch: 027 | MCC: 0.021538 | Train loss: 0.9819 | Train acc: 50.85% | Val loss: 0.9446 | Val acc: 54.33% | LR: 0.000314
Epoch: 028 | MCC: 0.022512 | Train loss: 0.9819 | Train acc: 50.80% | Val loss: 0.9414 | Val acc: 54.45% | LR: 0.000312
Epoch: 029 | MCC: 0.017892 | Train loss: 0.9797 | Train acc: 51.02% | Val loss: 0.9386 | Val acc: 54.43% | LR: 0.000310
Epoch: 030 | MCC: 0.016742 | Train loss: 0.9797 | Train acc: 50.93% | Val loss: 0.9368 | Val acc: 54.41% | LR: 0.000308
Epoch: 031 | MCC: 0.017701 | Train loss: 0.9796 | Train acc: 50.95% | Val loss: 0.9289 | Val acc: 54.70% | LR: 0.000306
Epoch: 032 | MCC: 0.018243 | Train loss: 0.9801 | Train acc: 50.85% | Val loss: 0.9259 | Val acc: 55.03% | LR: 0.000303
Epoch: 033 | MCC: 0.021352 | Train loss: 0.9796 | Train acc: 50.92% | Val loss: 0.9230 | Val acc: 55.18% | LR: 0.000301
Epoch: 034 | MCC: 0.022367 | Train loss: 0.9801 | Train acc: 50.90% | Val loss: 0.9188 | Val acc: 55.34% | LR: 0.000299
Epoch: 035 | MCC: 0.023708 | Train loss: 0.9800 | Train acc: 50.93% | Val loss: 0.9184 | Val acc: 55.56% | LR: 0.000296
Epoch: 036 | MCC: 0.020212 | Train loss: 0.9791 | Train acc: 50.96% | Val loss: 0.9122 | Val acc: 55.52% | LR: 0.000294
Epoch: 037 | MCC: 0.029421 | Train loss: 0.9808 | Train acc: 50.78% | Val loss: 0.9111 | Val acc: 55.99% | LR: 0.000291
Epoch: 038 | MCC: 0.030589 | Train loss: 0.9801 | Train acc: 50.90% | Val loss: 0.9103 | Val acc: 55.94% | LR: 0.000289
Epoch: 039 | MCC: 0.027197 | Train loss: 0.9782 | Train acc: 50.97% | Val loss: 0.9124 | Val acc: 55.82% | LR: 0.000286
Epoch: 040 | MCC: 0.031766 | Train loss: 0.9783 | Train acc: 50.95% | Val loss: 0.9084 | Val acc: 55.75% | LR: 0.000283
Epoch: 041 | MCC: 0.031553 | Train loss: 0.9788 | Train acc: 50.82% | Val loss: 0.9074 | Val acc: 55.56% | LR: 0.000281
Epoch: 042 | MCC: 0.030814 | Train loss: 0.9789 | Train acc: 50.84% | Val loss: 0.9065 | Val acc: 55.54% | LR: 0.000278
Epoch: 043 | MCC: 0.028706 | Train loss: 0.9778 | Train acc: 50.93% | Val loss: 0.9076 | Val acc: 55.41% | LR: 0.000275
Epoch: 044 | MCC: 0.028561 | Train loss: 0.9775 | Train acc: 50.91% | Val loss: 0.9059 | Val acc: 55.36% | LR: 0.000272
Epoch: 045 | MCC: 0.027048 | Train loss: 0.9787 | Train acc: 50.94% | Val loss: 0.9062 | Val acc: 55.29% | LR: 0.000269
Epoch: 046 | MCC: 0.027545 | Train loss: 0.9778 | Train acc: 51.00% | Val loss: 0.9065 | Val acc: 55.29% | LR: 0.000266
Epoch: 047 | MCC: 0.032176 | Train loss: 0.9766 | Train acc: 51.09% | Val loss: 0.9047 | Val acc: 55.38% | LR: 0.000263
Epoch: 048 | MCC: 0.026674 | Train loss: 0.9765 | Train acc: 51.12% | Val loss: 0.9033 | Val acc: 55.49% | LR: 0.000260
Epoch: 049 | MCC: 0.029911 | Train loss: 0.9755 | Train acc: 51.11% | Val loss: 0.9004 | Val acc: 55.72% | LR: 0.000257
Epoch: 050 | MCC: 0.049837 | Train loss: 0.9767 | Train acc: 50.86% | Val loss: 0.8986 | Val acc: 57.06% | LR: 0.000254
Epoch: 051 | MCC: 0.040584 | Train loss: 0.9756 | Train acc: 51.11% | Val loss: 0.8986 | Val acc: 56.91% | LR: 0.000251
Epoch: 052 | MCC: 0.027682 | Train loss: 0.9759 | Train acc: 51.44% | Val loss: 0.8924 | Val acc: 56.89% | LR: 0.000248
Epoch: 053 | MCC: -0.001639 | Train loss: 0.9760 | Train acc: 51.71% | Val loss: 0.8950 | Val acc: 56.57% | LR: 0.000245
Epoch: 054 | MCC: -0.000272 | Train loss: 0.9738 | Train acc: 51.87% | Val loss: 0.8978 | Val acc: 56.59% | LR: 0.000241
Epoch: 055 | MCC: 0.004726 | Train loss: 0.9749 | Train acc: 51.80% | Val loss: 0.8924 | Val acc: 56.62% | LR: 0.000238
Epoch: 056 | MCC: 0.003890 | Train loss: 0.9743 | Train acc: 51.70% | Val loss: 0.9016 | Val acc: 56.36% | LR: 0.000235
Epoch: 057 | MCC: 0.007942 | Train loss: 0.9720 | Train acc: 51.85% | Val loss: 0.8880 | Val acc: 57.08% | LR: 0.000231
Epoch: 058 | MCC: -0.000476 | Train loss: 0.9732 | Train acc: 51.81% | Val loss: 0.8924 | Val acc: 56.75% | LR: 0.000228
Epoch: 059 | MCC: 0.007045 | Train loss: 0.9722 | Train acc: 51.87% | Val loss: 0.8920 | Val acc: 57.00% | LR: 0.000225
Epoch: 060 | MCC: 0.010466 | Train loss: 0.9706 | Train acc: 51.96% | Val loss: 0.8784 | Val acc: 57.66% | LR: 0.000221
Epoch: 061 | MCC: 0.003080 | Train loss: 0.9708 | Train acc: 51.84% | Val loss: 0.8770 | Val acc: 57.42% | LR: 0.000218
Epoch: 062 | MCC: 0.002143 | Train loss: 0.9695 | Train acc: 52.08% | Val loss: 0.8759 | Val acc: 57.39% | LR: 0.000214
Epoch: 063 | MCC: 0.007010 | Train loss: 0.9721 | Train acc: 51.97% | Val loss: 0.8710 | Val acc: 57.83% | LR: 0.000211
Epoch: 064 | MCC: 0.009553 | Train loss: 0.9721 | Train acc: 51.62% | Val loss: 0.8735 | Val acc: 57.74% | LR: 0.000207
Epoch: 065 | MCC: -0.000589 | Train loss: 0.9704 | Train acc: 51.34% | Val loss: 0.8735 | Val acc: 57.17% | LR: 0.000204
Epoch: 066 | MCC: -0.002037 | Train loss: 0.9694 | Train acc: 51.61% | Val loss: 0.8734 | Val acc: 57.22% | LR: 0.000200
Epoch: 067 | MCC: 0.003132 | Train loss: 0.9690 | Train acc: 51.20% | Val loss: 0.8624 | Val acc: 57.98% | LR: 0.000197
Epoch: 068 | MCC: -0.002953 | Train loss: 0.9687 | Train acc: 52.08% | Val loss: 0.8711 | Val acc: 57.35% | LR: 0.000193
Epoch: 069 | MCC: 0.000226 | Train loss: 0.9714 | Train acc: 51.74% | Val loss: 0.8635 | Val acc: 57.49% | LR: 0.000190
Epoch: 070 | MCC: -0.009068 | Train loss: 0.9683 | Train acc: 52.05% | Val loss: 0.8706 | Val acc: 57.00% | LR: 0.000186
Epoch: 071 | MCC: -0.005147 | Train loss: 0.9708 | Train acc: 52.02% | Val loss: 0.8670 | Val acc: 57.32% | LR: 0.000183
Epoch: 072 | MCC: -0.008059 | Train loss: 0.9667 | Train acc: 52.11% | Val loss: 0.8619 | Val acc: 57.39% | LR: 0.000179
Epoch: 073 | MCC: -0.012673 | Train loss: 0.9689 | Train acc: 51.97% | Val loss: 0.8659 | Val acc: 57.45% | LR: 0.000175
Epoch: 074 | MCC: -0.017463 | Train loss: 0.9678 | Train acc: 52.02% | Val loss: 0.8634 | Val acc: 57.18% | LR: 0.000172
Epoch: 075 | MCC: -0.003887 | Train loss: 0.9681 | Train acc: 52.04% | Val loss: 0.8450 | Val acc: 58.66% | LR: 0.000168
Epoch: 076 | MCC: -0.001517 | Train loss: 0.9672 | Train acc: 52.08% | Val loss: 0.8573 | Val acc: 57.90% | LR: 0.000165
Epoch: 077 | MCC: -0.002264 | Train loss: 0.9696 | Train acc: 52.12% | Val loss: 0.8468 | Val acc: 58.32% | LR: 0.000161
Epoch: 078 | MCC: -0.006198 | Train loss: 0.9693 | Train acc: 51.92% | Val loss: 0.8633 | Val acc: 57.66% | LR: 0.000158
Epoch: 079 | MCC: 0.004200 | Train loss: 0.9690 | Train acc: 52.02% | Val loss: 0.8455 | Val acc: 58.17% | LR: 0.000154
Epoch: 080 | MCC: -0.001587 | Train loss: 0.9678 | Train acc: 52.02% | Val loss: 0.8335 | Val acc: 58.97% | LR: 0.000150
Epoch: 081 | MCC: 0.000044 | Train loss: 0.9678 | Train acc: 51.96% | Val loss: 0.8483 | Val acc: 58.18% | LR: 0.000147
Epoch: 082 | MCC: -0.000907 | Train loss: 0.9653 | Train acc: 52.13% | Val loss: 0.8441 | Val acc: 58.37% | LR: 0.000143
Epoch: 083 | MCC: -0.000484 | Train loss: 0.9662 | Train acc: 52.03% | Val loss: 0.8473 | Val acc: 58.01% | LR: 0.000140
Epoch: 084 | MCC: -0.001832 | Train loss: 0.9646 | Train acc: 52.15% | Val loss: 0.8417 | Val acc: 58.44% | LR: 0.000136
Epoch: 085 | MCC: -0.001216 | Train loss: 0.9649 | Train acc: 52.12% | Val loss: 0.8443 | Val acc: 58.15% | LR: 0.000133
Epoch: 086 | MCC: -0.007349 | Train loss: 0.9660 | Train acc: 52.03% | Val loss: 0.8418 | Val acc: 58.26% | LR: 0.000129
Epoch: 087 | MCC: -0.000855 | Train loss: 0.9663 | Train acc: 52.04% | Val loss: 0.8465 | Val acc: 58.10% | LR: 0.000126
Epoch: 088 | MCC: 0.002681 | Train loss: 0.9635 | Train acc: 52.22% | Val loss: 0.8496 | Val acc: 58.25% | LR: 0.000122
Epoch: 089 | MCC: -0.009276 | Train loss: 0.9711 | Train acc: 52.33% | Val loss: 0.8448 | Val acc: 58.25% | LR: 0.000119
Epoch: 090 | MCC: -0.008764 | Train loss: 0.9646 | Train acc: 52.14% | Val loss: 0.8409 | Val acc: 58.34% | LR: 0.000116
Epoch: 091 | MCC: -0.009544 | Train loss: 0.9624 | Train acc: 52.28% | Val loss: 0.8410 | Val acc: 58.24% | LR: 0.000112
Epoch: 092 | MCC: 0.004216 | Train loss: 0.9641 | Train acc: 52.20% | Val loss: 0.8426 | Val acc: 58.15% | LR: 0.000109
Epoch: 093 | MCC: -0.008245 | Train loss: 0.9669 | Train acc: 52.03% | Val loss: 0.8442 | Val acc: 57.99% | LR: 0.000106
Epoch: 094 | MCC: 0.001447 | Train loss: 0.9651 | Train acc: 52.10% | Val loss: 0.8464 | Val acc: 58.26% | LR: 0.000102
Epoch: 095 | MCC: -0.002579 | Train loss: 0.9622 | Train acc: 52.23% | Val loss: 0.8477 | Val acc: 58.08% | LR: 0.000099
Epoch: 096 | MCC: -0.002967 | Train loss: 0.9641 | Train acc: 52.07% | Val loss: 0.8430 | Val acc: 58.15% | LR: 0.000096
Epoch: 097 | MCC: -0.001012 | Train loss: 0.9681 | Train acc: 52.01% | Val loss: 0.8403 | Val acc: 58.37% | LR: 0.000093
Epoch: 098 | MCC: 0.004553 | Train loss: 0.9642 | Train acc: 52.12% | Val loss: 0.8458 | Val acc: 58.27% | LR: 0.000090
Epoch: 099 | MCC: 0.001021 | Train loss: 0.9626 | Train acc: 52.17% | Val loss: 0.8448 | Val acc: 58.22% | LR: 0.000086
Epoch: 100 | MCC: 0.006372 | Train loss: 0.9638 | Train acc: 52.11% | Val loss: 0.8462 | Val acc: 58.18% | LR: 0.000083
Epoch: 101 | MCC: -0.003950 | Train loss: 0.9613 | Train acc: 52.19% | Val loss: 0.8392 | Val acc: 58.25% | LR: 0.000080
Epoch: 102 | MCC: 0.003606 | Train loss: 0.9619 | Train acc: 52.18% | Val loss: 0.8474 | Val acc: 58.20% | LR: 0.000077
Epoch: 103 | MCC: 0.000319 | Train loss: 0.9805 | Train acc: 52.16% | Val loss: 0.8427 | Val acc: 58.25% | LR: 0.000074
Epoch: 104 | MCC: 0.001723 | Train loss: 0.9714 | Train acc: 52.18% | Val loss: 0.8465 | Val acc: 58.18% | LR: 0.000071
Epoch: 105 | MCC: -0.000561 | Train loss: 0.9622 | Train acc: 52.13% | Val loss: 0.8448 | Val acc: 58.05% | LR: 0.000069
Epoch: 106 | MCC: -0.001417 | Train loss: 0.9603 | Train acc: 52.25% | Val loss: 0.8434 | Val acc: 58.15% | LR: 0.000066
Epoch: 107 | MCC: -0.002487 | Train loss: 0.9621 | Train acc: 52.14% | Val loss: 0.8450 | Val acc: 58.01% | LR: 0.000063
Epoch: 108 | MCC: -0.001035 | Train loss: 0.9609 | Train acc: 52.21% | Val loss: 0.8444 | Val acc: 58.10% | LR: 0.000060
Epoch: 109 | MCC: 0.000847 | Train loss: 0.9590 | Train acc: 52.30% | Val loss: 0.8464 | Val acc: 58.08% | LR: 0.000058
Epoch: 110 | MCC: -0.001169 | Train loss: 0.9608 | Train acc: 52.19% | Val loss: 0.8407 | Val acc: 58.13% | LR: 0.000055
Epoch: 111 | MCC: -0.001637 | Train loss: 0.9614 | Train acc: 52.13% | Val loss: 0.8432 | Val acc: 58.05% | LR: 0.000052
Epoch: 112 | MCC: 0.004055 | Train loss: 0.9595 | Train acc: 52.28% | Val loss: 0.8435 | Val acc: 58.27% | LR: 0.000050
Epoch: 113 | MCC: 0.000669 | Train loss: 0.9611 | Train acc: 52.19% | Val loss: 0.8389 | Val acc: 58.27% | LR: 0.000047
Epoch: 114 | MCC: 0.002731 | Train loss: 0.9608 | Train acc: 52.20% | Val loss: 0.8426 | Val acc: 58.25% | LR: 0.000045
Epoch: 115 | MCC: -0.000310 | Train loss: 0.9593 | Train acc: 52.25% | Val loss: 0.8420 | Val acc: 58.18% | LR: 0.000043
Epoch: 116 | MCC: 0.000151 | Train loss: 0.9604 | Train acc: 52.20% | Val loss: 0.8399 | Val acc: 58.22% | LR: 0.000040
Epoch: 117 | MCC: 0.000417 | Train loss: 0.9602 | Train acc: 52.17% | Val loss: 0.8415 | Val acc: 58.20% | LR: 0.000038
Epoch: 118 | MCC: 0.003651 | Train loss: 0.9582 | Train acc: 52.32% | Val loss: 0.8413 | Val acc: 58.27% | LR: 0.000036
Epoch: 119 | MCC: 0.003836 | Train loss: 0.9611 | Train acc: 52.15% | Val loss: 0.8400 | Val acc: 58.35% | LR: 0.000034
Epoch: 120 | MCC: 0.001094 | Train loss: 0.9612 | Train acc: 52.16% | Val loss: 0.8411 | Val acc: 58.22% | LR: 0.000032
Epoch: 121 | MCC: 0.003696 | Train loss: 0.9591 | Train acc: 52.28% | Val loss: 0.8391 | Val acc: 58.32% | LR: 0.000030
Epoch: 122 | MCC: 0.005225 | Train loss: 0.9595 | Train acc: 52.22% | Val loss: 0.8402 | Val acc: 58.37% | LR: 0.000028
Epoch: 123 | MCC: 0.003131 | Train loss: 0.9592 | Train acc: 52.25% | Val loss: 0.8401 | Val acc: 58.32% | LR: 0.000026
Epoch: 124 | MCC: 0.004269 | Train loss: 0.9607 | Train acc: 52.18% | Val loss: 0.8395 | Val acc: 58.35% | LR: 0.000024
Epoch: 125 | MCC: 0.004094 | Train loss: 0.9602 | Train acc: 52.19% | Val loss: 0.8399 | Val acc: 58.30% | LR: 0.000022
Epoch: 126 | MCC: 0.004981 | Train loss: 0.9585 | Train acc: 52.25% | Val loss: 0.8398 | Val acc: 58.35% | LR: 0.000020
Epoch: 127 | MCC: 0.005063 | Train loss: 0.9579 | Train acc: 52.30% | Val loss: 0.8397 | Val acc: 58.37% | LR: 0.000019
Epoch: 128 | MCC: 0.006676 | Train loss: 0.9606 | Train acc: 52.15% | Val loss: 0.8399 | Val acc: 58.35% | LR: 0.000017
Epoch: 129 | MCC: 0.010192 | Train loss: 0.9609 | Train acc: 52.13% | Val loss: 0.8388 | Val acc: 58.54% | LR: 0.000016
Epoch: 130 | MCC: 0.008092 | Train loss: 0.9580 | Train acc: 52.29% | Val loss: 0.8395 | Val acc: 58.42% | LR: 0.000014
Epoch: 131 | MCC: 0.008478 | Train loss: 0.9581 | Train acc: 52.28% | Val loss: 0.8390 | Val acc: 58.44% | LR: 0.000013
Epoch: 132 | MCC: 0.005774 | Train loss: 0.9587 | Train acc: 52.25% | Val loss: 0.8394 | Val acc: 58.37% | LR: 0.000012
Epoch: 133 | MCC: 0.007898 | Train loss: 0.9574 | Train acc: 52.33% | Val loss: 0.8390 | Val acc: 58.44% | LR: 0.000011
Epoch: 134 | MCC: 0.009272 | Train loss: 0.9578 | Train acc: 52.30% | Val loss: 0.8390 | Val acc: 58.47% | LR: 0.000009
Epoch: 135 | MCC: 0.009128 | Train loss: 0.9597 | Train acc: 52.18% | Val loss: 0.8390 | Val acc: 58.47% | LR: 0.000008
Epoch: 136 | MCC: 0.009128 | Train loss: 0.9589 | Train acc: 52.23% | Val loss: 0.8385 | Val acc: 58.47% | LR: 0.000007
Epoch: 137 | MCC: 0.009128 | Train loss: 0.9578 | Train acc: 52.30% | Val loss: 0.8387 | Val acc: 58.47% | LR: 0.000006
Epoch: 138 | MCC: 0.009128 | Train loss: 0.9585 | Train acc: 52.26% | Val loss: 0.8385 | Val acc: 58.47% | LR: 0.000006
Epoch: 139 | MCC: 0.010286 | Train loss: 0.9588 | Train acc: 52.23% | Val loss: 0.8379 | Val acc: 58.54% | LR: 0.000005
Epoch: 140 | MCC: 0.009517 | Train loss: 0.9583 | Train acc: 52.26% | Val loss: 0.8385 | Val acc: 58.44% | LR: 0.000004
Epoch: 141 | MCC: 0.009128 | Train loss: 0.9604 | Train acc: 52.17% | Val loss: 0.8383 | Val acc: 58.47% | LR: 0.000003
Epoch: 142 | MCC: 0.009128 | Train loss: 0.9581 | Train acc: 52.27% | Val loss: 0.8383 | Val acc: 58.47% | LR: 0.000003
Epoch: 143 | MCC: 0.009128 | Train loss: 0.9577 | Train acc: 52.31% | Val loss: 0.8382 | Val acc: 58.47% | LR: 0.000002
Epoch: 144 | MCC: 0.009128 | Train loss: 0.9591 | Train acc: 52.22% | Val loss: 0.8381 | Val acc: 58.47% | LR: 0.000002
Epoch: 145 | MCC: 0.009517 | Train loss: 0.9583 | Train acc: 52.26% | Val loss: 0.8381 | Val acc: 58.44% | LR: 0.000002
Epoch: 146 | MCC: 0.009128 | Train loss: 0.9579 | Train acc: 52.28% | Val loss: 0.8381 | Val acc: 58.47% | LR: 0.000001
Epoch: 147 | MCC: 0.009128 | Train loss: 0.9580 | Train acc: 52.28% | Val loss: 0.8380 | Val acc: 58.47% | LR: 0.000001
Epoch: 148 | MCC: 0.009128 | Train loss: 0.9589 | Train acc: 52.24% | Val loss: 0.8380 | Val acc: 58.47% | LR: 0.000001
Epoch: 149 | MCC: 0.009128 | Train loss: 0.9576 | Train acc: 52.31% | Val loss: 0.8380 | Val acc: 58.47% | LR: 0.000001

[I 2025-10-05 10:15:55,937] Trial 48 finished with value: 0.009128034580498934 and parameters: {'lr': 0.0003426305104429325, 'hidden_size': 84, 'dropout': 0.18061874007533268, 'weight_decay': 0.002640839650549126}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: -0.036872 | Train loss: 1.0000 | Train acc: 49.95% | Val loss: 1.0033 | Val acc: 46.93% | LR: 0.000402
Epoch: 001 | MCC: -0.032951 | Train loss: 0.9940 | Train acc: 50.34% | Val loss: 0.9998 | Val acc: 51.18% | LR: 0.000402
Epoch: 002 | MCC: -0.025147 | Train loss: 0.9928 | Train acc: 50.26% | Val loss: 0.9995 | Val acc: 52.33% | LR: 0.000401
Epoch: 003 | MCC: 0.020999 | Train loss: 0.9969 | Train acc: 50.30% | Val loss: 0.9977 | Val acc: 54.37% | LR: 0.000401
Epoch: 004 | MCC: 0.024600 | Train loss: 0.9930 | Train acc: 50.66% | Val loss: 0.9971 | Val acc: 53.78% | LR: 0.000401
Epoch: 005 | MCC: 0.031594 | Train loss: 0.9907 | Train acc: 50.65% | Val loss: 1.0447 | Val acc: 53.78% | LR: 0.000400
Epoch: 006 | MCC: 0.024671 | Train loss: 0.9896 | Train acc: 50.90% | Val loss: 0.9971 | Val acc: 53.49% | LR: 0.000400
Epoch: 007 | MCC: 0.027400 | Train loss: 0.9887 | Train acc: 51.06% | Val loss: 0.9921 | Val acc: 53.78% | LR: 0.000399
Epoch: 008 | MCC: 0.034529 | Train loss: 0.9899 | Train acc: 50.84% | Val loss: 0.9874 | Val acc: 54.52% | LR: 0.000398
Epoch: 009 | MCC: 0.032247 | Train loss: 0.9900 | Train acc: 51.00% | Val loss: 0.9806 | Val acc: 54.39% | LR: 0.000397
Epoch: 010 | MCC: 0.029619 | Train loss: 0.9876 | Train acc: 50.99% | Val loss: 0.9797 | Val acc: 54.32% | LR: 0.000397
Epoch: 011 | MCC: 0.019941 | Train loss: 0.9878 | Train acc: 50.93% | Val loss: 0.9724 | Val acc: 54.04% | LR: 0.000396
Epoch: 012 | MCC: 0.013273 | Train loss: 0.9868 | Train acc: 50.92% | Val loss: 0.9670 | Val acc: 53.60% | LR: 0.000394
Epoch: 013 | MCC: 0.003650 | Train loss: 0.9868 | Train acc: 50.96% | Val loss: 0.9584 | Val acc: 53.33% | LR: 0.000393
Epoch: 014 | MCC: -0.000351 | Train loss: 0.9862 | Train acc: 50.79% | Val loss: 0.9584 | Val acc: 53.23% | LR: 0.000392
Epoch: 015 | MCC: 0.003597 | Train loss: 0.9854 | Train acc: 50.90% | Val loss: 0.9561 | Val acc: 53.60% | LR: 0.000391
Epoch: 016 | MCC: 0.006536 | Train loss: 0.9862 | Train acc: 50.77% | Val loss: 0.9568 | Val acc: 53.92% | LR: 0.000389
Epoch: 017 | MCC: 0.013600 | Train loss: 0.9845 | Train acc: 50.79% | Val loss: 0.9554 | Val acc: 54.25% | LR: 0.000388
Epoch: 018 | MCC: 0.026451 | Train loss: 0.9819 | Train acc: 51.00% | Val loss: 0.9527 | Val acc: 55.10% | LR: 0.000386
Epoch: 019 | MCC: 0.021284 | Train loss: 0.9808 | Train acc: 51.00% | Val loss: 0.9517 | Val acc: 54.97% | LR: 0.000384
Epoch: 020 | MCC: 0.019656 | Train loss: 0.9819 | Train acc: 50.76% | Val loss: 0.9500 | Val acc: 54.92% | LR: 0.000383
Epoch: 021 | MCC: 0.020887 | Train loss: 0.9813 | Train acc: 50.91% | Val loss: 0.9460 | Val acc: 55.14% | LR: 0.000381
Epoch: 022 | MCC: 0.019975 | Train loss: 0.9802 | Train acc: 50.84% | Val loss: 0.9406 | Val acc: 55.28% | LR: 0.000379
Epoch: 023 | MCC: 0.021610 | Train loss: 0.9788 | Train acc: 51.05% | Val loss: 0.9389 | Val acc: 55.60% | LR: 0.000377
Epoch: 024 | MCC: 0.024234 | Train loss: 0.9794 | Train acc: 51.56% | Val loss: 0.9318 | Val acc: 55.80% | LR: 0.000375
Epoch: 025 | MCC: 0.022317 | Train loss: 0.9818 | Train acc: 51.56% | Val loss: 0.9284 | Val acc: 55.76% | LR: 0.000373
Epoch: 026 | MCC: 0.022490 | Train loss: 0.9791 | Train acc: 51.58% | Val loss: 0.9229 | Val acc: 56.01% | LR: 0.000371
Epoch: 027 | MCC: 0.018784 | Train loss: 0.9787 | Train acc: 51.51% | Val loss: 0.9159 | Val acc: 56.13% | LR: 0.000368
Epoch: 028 | MCC: 0.023015 | Train loss: 0.9774 | Train acc: 51.56% | Val loss: 0.9149 | Val acc: 56.47% | LR: 0.000366
Epoch: 029 | MCC: 0.024362 | Train loss: 0.9772 | Train acc: 51.60% | Val loss: 0.9048 | Val acc: 56.64% | LR: 0.000364
Epoch: 030 | MCC: 0.023993 | Train loss: 0.9770 | Train acc: 51.54% | Val loss: 0.9021 | Val acc: 56.79% | LR: 0.000361
Epoch: 031 | MCC: 0.032867 | Train loss: 0.9753 | Train acc: 51.61% | Val loss: 0.8992 | Val acc: 57.25% | LR: 0.000358
Epoch: 032 | MCC: 0.024341 | Train loss: 0.9756 | Train acc: 51.64% | Val loss: 0.8966 | Val acc: 57.21% | LR: 0.000356
Epoch: 033 | MCC: 0.020110 | Train loss: 0.9747 | Train acc: 51.63% | Val loss: 0.8918 | Val acc: 57.50% | LR: 0.000353
Epoch: 034 | MCC: 0.045172 | Train loss: 0.9739 | Train acc: 51.68% | Val loss: 0.8922 | Val acc: 58.27% | LR: 0.000350
Epoch: 035 | MCC: 0.041833 | Train loss: 0.9725 | Train acc: 51.84% | Val loss: 0.8856 | Val acc: 58.46% | LR: 0.000347
Epoch: 036 | MCC: 0.037249 | Train loss: 0.9733 | Train acc: 51.78% | Val loss: 0.8892 | Val acc: 58.39% | LR: 0.000345
Epoch: 037 | MCC: 0.039508 | Train loss: 0.9747 | Train acc: 51.62% | Val loss: 0.8850 | Val acc: 57.77% | LR: 0.000342
Epoch: 038 | MCC: 0.037125 | Train loss: 0.9768 | Train acc: 51.65% | Val loss: 0.8797 | Val acc: 58.03% | LR: 0.000339
Epoch: 039 | MCC: 0.037107 | Train loss: 0.9724 | Train acc: 51.66% | Val loss: 0.8772 | Val acc: 58.12% | LR: 0.000335
Epoch: 040 | MCC: 0.028165 | Train loss: 0.9708 | Train acc: 51.70% | Val loss: 0.8796 | Val acc: 58.04% | LR: 0.000332
Epoch: 041 | MCC: 0.022760 | Train loss: 0.9695 | Train acc: 51.77% | Val loss: 0.8831 | Val acc: 57.45% | LR: 0.000329
Epoch: 042 | MCC: 0.014707 | Train loss: 0.9711 | Train acc: 51.83% | Val loss: 0.8882 | Val acc: 57.50% | LR: 0.000326
Epoch: 043 | MCC: 0.014355 | Train loss: 0.9694 | Train acc: 51.90% | Val loss: 0.8768 | Val acc: 57.76% | LR: 0.000323
Epoch: 044 | MCC: 0.006071 | Train loss: 0.9667 | Train acc: 51.97% | Val loss: 0.8800 | Val acc: 57.49% | LR: 0.000319
Epoch: 045 | MCC: 0.027975 | Train loss: 0.9672 | Train acc: 51.93% | Val loss: 0.8708 | Val acc: 57.65% | LR: 0.000316
Epoch: 046 | MCC: 0.021512 | Train loss: 0.9647 | Train acc: 52.02% | Val loss: 0.8541 | Val acc: 58.49% | LR: 0.000312
Epoch: 047 | MCC: 0.019195 | Train loss: 0.9632 | Train acc: 52.13% | Val loss: 0.8630 | Val acc: 57.86% | LR: 0.000309
Epoch: 048 | MCC: 0.051230 | Train loss: 0.9660 | Train acc: 51.98% | Val loss: 0.8457 | Val acc: 58.84% | LR: 0.000305
Epoch: 049 | MCC: 0.027950 | Train loss: 0.9652 | Train acc: 51.93% | Val loss: 0.8442 | Val acc: 58.68% | LR: 0.000302
Epoch: 050 | MCC: 0.056821 | Train loss: 0.9630 | Train acc: 52.09% | Val loss: 0.8577 | Val acc: 58.50% | LR: 0.000298
Epoch: 051 | MCC: 0.013548 | Train loss: 0.9649 | Train acc: 52.02% | Val loss: 0.8413 | Val acc: 58.54% | LR: 0.000294
Epoch: 052 | MCC: 0.017394 | Train loss: 0.9710 | Train acc: 51.83% | Val loss: 0.9499 | Val acc: 57.32% | LR: 0.000291
Epoch: 053 | MCC: 0.034657 | Train loss: 0.9706 | Train acc: 51.79% | Val loss: 0.8430 | Val acc: 58.54% | LR: 0.000287
Epoch: 054 | MCC: 0.071790 | Train loss: 0.9653 | Train acc: 51.99% | Val loss: 0.8342 | Val acc: 58.78% | LR: 0.000283
Epoch: 055 | MCC: 0.056263 | Train loss: 0.9632 | Train acc: 52.09% | Val loss: 0.8302 | Val acc: 59.42% | LR: 0.000279
Epoch: 056 | MCC: 0.076637 | Train loss: 0.9628 | Train acc: 52.07% | Val loss: 0.8245 | Val acc: 59.70% | LR: 0.000275
Epoch: 057 | MCC: 0.043542 | Train loss: 0.9624 | Train acc: 52.05% | Val loss: 0.8591 | Val acc: 57.48% | LR: 0.000271
Epoch: 058 | MCC: 0.026710 | Train loss: 0.9660 | Train acc: 51.87% | Val loss: 0.8285 | Val acc: 58.96% | LR: 0.000267
Epoch: 059 | MCC: 0.026733 | Train loss: 0.9634 | Train acc: 52.08% | Val loss: 0.8362 | Val acc: 58.84% | LR: 0.000263
Epoch: 060 | MCC: 0.036281 | Train loss: 0.9653 | Train acc: 51.97% | Val loss: 0.8247 | Val acc: 59.34% | LR: 0.000259
Epoch: 061 | MCC: 0.056233 | Train loss: 0.9616 | Train acc: 52.13% | Val loss: 0.8163 | Val acc: 60.01% | LR: 0.000255
Epoch: 062 | MCC: 0.049859 | Train loss: 0.9613 | Train acc: 52.13% | Val loss: 0.8218 | Val acc: 59.50% | LR: 0.000251
Epoch: 063 | MCC: 0.060374 | Train loss: 0.9618 | Train acc: 52.09% | Val loss: 0.8210 | Val acc: 59.71% | LR: 0.000247
Epoch: 064 | MCC: 0.054848 | Train loss: 0.9620 | Train acc: 52.08% | Val loss: 0.8321 | Val acc: 58.77% | LR: 0.000243
Epoch: 065 | MCC: 0.077951 | Train loss: 0.9639 | Train acc: 51.97% | Val loss: 0.8342 | Val acc: 58.92% | LR: 0.000239
Epoch: 066 | MCC: 0.051928 | Train loss: 0.9599 | Train acc: 52.18% | Val loss: 0.8304 | Val acc: 58.91% | LR: 0.000235
Epoch: 067 | MCC: 0.029472 | Train loss: 0.9626 | Train acc: 52.02% | Val loss: 0.8466 | Val acc: 58.26% | LR: 0.000231
Epoch: 068 | MCC: 0.013746 | Train loss: 0.9633 | Train acc: 52.02% | Val loss: 0.8372 | Val acc: 58.46% | LR: 0.000227
Epoch: 069 | MCC: 0.031058 | Train loss: 0.9627 | Train acc: 52.03% | Val loss: 0.8260 | Val acc: 59.16% | LR: 0.000222
Epoch: 070 | MCC: 0.025340 | Train loss: 0.9640 | Train acc: 51.99% | Val loss: 0.8504 | Val acc: 58.13% | LR: 0.000218
Epoch: 071 | MCC: 0.028674 | Train loss: 0.9665 | Train acc: 51.83% | Val loss: 0.8516 | Val acc: 58.01% | LR: 0.000214
Epoch: 072 | MCC: 0.025209 | Train loss: 0.9610 | Train acc: 52.13% | Val loss: 0.8617 | Val acc: 57.47% | LR: 0.000210
Epoch: 073 | MCC: 0.019081 | Train loss: 0.9648 | Train acc: 51.96% | Val loss: 0.8528 | Val acc: 57.58% | LR: 0.000206
Epoch: 074 | MCC: 0.046137 | Train loss: 0.9619 | Train acc: 52.07% | Val loss: 0.8571 | Val acc: 57.56% | LR: 0.000201
Epoch: 075 | MCC: 0.043558 | Train loss: 0.9608 | Train acc: 52.12% | Val loss: 0.8555 | Val acc: 57.61% | LR: 0.000197
Epoch: 076 | MCC: 0.051029 | Train loss: 0.9615 | Train acc: 52.09% | Val loss: 0.8333 | Val acc: 58.81% | LR: 0.000193
Epoch: 077 | MCC: 0.045509 | Train loss: 0.9583 | Train acc: 52.28% | Val loss: 0.8334 | Val acc: 58.76% | LR: 0.000189
Epoch: 078 | MCC: 0.044222 | Train loss: 0.9593 | Train acc: 52.17% | Val loss: 0.8427 | Val acc: 58.25% | LR: 0.000185
Epoch: 079 | MCC: 0.071263 | Train loss: 0.9617 | Train acc: 52.09% | Val loss: 0.8274 | Val acc: 59.09% | LR: 0.000180
Epoch: 080 | MCC: 0.019999 | Train loss: 0.9604 | Train acc: 52.15% | Val loss: 0.8530 | Val acc: 57.82% | LR: 0.000176
Epoch: 081 | MCC: 0.048381 | Train loss: 0.9621 | Train acc: 52.04% | Val loss: 0.8299 | Val acc: 59.03% | LR: 0.000172
Epoch: 082 | MCC: 0.048227 | Train loss: 0.9600 | Train acc: 52.18% | Val loss: 0.8260 | Val acc: 59.14% | LR: 0.000168
Epoch: 083 | MCC: 0.070663 | Train loss: 0.9597 | Train acc: 52.18% | Val loss: 0.8302 | Val acc: 58.85% | LR: 0.000164
Epoch: 084 | MCC: 0.045156 | Train loss: 0.9578 | Train acc: 52.25% | Val loss: 0.8262 | Val acc: 59.27% | LR: 0.000160
Epoch: 085 | MCC: 0.048304 | Train loss: 0.9589 | Train acc: 52.23% | Val loss: 0.8362 | Val acc: 58.62% | LR: 0.000156
Epoch: 086 | MCC: 0.047665 | Train loss: 0.9601 | Train acc: 52.14% | Val loss: 0.8438 | Val acc: 58.40% | LR: 0.000152
Epoch: 087 | MCC: 0.020407 | Train loss: 0.9603 | Train acc: 52.16% | Val loss: 0.8393 | Val acc: 58.43% | LR: 0.000148
Epoch: 088 | MCC: 0.057789 | Train loss: 0.9589 | Train acc: 52.27% | Val loss: 0.8315 | Val acc: 59.05% | LR: 0.000143
Epoch: 089 | MCC: 0.063221 | Train loss: 0.9594 | Train acc: 52.21% | Val loss: 0.8210 | Val acc: 59.38% | LR: 0.000139
Epoch: 090 | MCC: 0.052949 | Train loss: 0.9595 | Train acc: 52.18% | Val loss: 0.8337 | Val acc: 58.71% | LR: 0.000135
Epoch: 091 | MCC: 0.044722 | Train loss: 0.9579 | Train acc: 52.24% | Val loss: 0.8334 | Val acc: 58.86% | LR: 0.000132
Epoch: 092 | MCC: 0.019516 | Train loss: 0.9625 | Train acc: 52.05% | Val loss: 0.8399 | Val acc: 58.61% | LR: 0.000128
Epoch: 093 | MCC: 0.070492 | Train loss: 0.9609 | Train acc: 52.12% | Val loss: 0.8262 | Val acc: 59.14% | LR: 0.000124
Epoch: 094 | MCC: 0.072200 | Train loss: 0.9609 | Train acc: 52.08% | Val loss: 0.8244 | Val acc: 59.28% | LR: 0.000120
Epoch: 095 | MCC: 0.053401 | Train loss: 0.9582 | Train acc: 52.24% | Val loss: 0.8347 | Val acc: 58.74% | LR: 0.000116
Epoch: 096 | MCC: 0.051800 | Train loss: 0.9706 | Train acc: 52.06% | Val loss: 0.8185 | Val acc: 59.45% | LR: 0.000112
Epoch: 097 | MCC: 0.065320 | Train loss: 0.9576 | Train acc: 52.32% | Val loss: 0.8234 | Val acc: 59.25% | LR: 0.000109
Epoch: 098 | MCC: 0.053452 | Train loss: 0.9596 | Train acc: 52.17% | Val loss: 0.8307 | Val acc: 58.96% | LR: 0.000105
Epoch: 099 | MCC: 0.070672 | Train loss: 0.9582 | Train acc: 52.22% | Val loss: 0.8250 | Val acc: 59.38% | LR: 0.000101
Epoch: 100 | MCC: 0.065954 | Train loss: 0.9593 | Train acc: 52.21% | Val loss: 0.8267 | Val acc: 59.25% | LR: 0.000098
Epoch: 101 | MCC: 0.058751 | Train loss: 0.9606 | Train acc: 52.14% | Val loss: 0.8238 | Val acc: 59.21% | LR: 0.000094
Epoch: 102 | MCC: 0.056962 | Train loss: 0.9602 | Train acc: 52.12% | Val loss: 0.8264 | Val acc: 59.30% | LR: 0.000091
Epoch: 103 | MCC: 0.056871 | Train loss: 0.9610 | Train acc: 52.07% | Val loss: 0.8253 | Val acc: 59.30% | LR: 0.000087
Epoch: 104 | MCC: 0.057120 | Train loss: 0.9604 | Train acc: 52.09% | Val loss: 0.8258 | Val acc: 59.35% | LR: 0.000084
Epoch: 105 | MCC: 0.056717 | Train loss: 0.9572 | Train acc: 52.27% | Val loss: 0.8297 | Val acc: 59.03% | LR: 0.000080
Epoch: 106 | MCC: 0.057609 | Train loss: 0.9578 | Train acc: 52.26% | Val loss: 0.8295 | Val acc: 59.10% | LR: 0.000077
Epoch: 107 | MCC: 0.070478 | Train loss: 0.9557 | Train acc: 52.38% | Val loss: 0.8212 | Val acc: 59.46% | LR: 0.000074
Epoch: 108 | MCC: 0.049690 | Train loss: 0.9575 | Train acc: 52.28% | Val loss: 0.8320 | Val acc: 58.79% | LR: 0.000070
Epoch: 109 | MCC: 0.053747 | Train loss: 0.9612 | Train acc: 52.06% | Val loss: 0.8358 | Val acc: 58.71% | LR: 0.000067
Epoch: 110 | MCC: 0.029460 | Train loss: 0.9597 | Train acc: 52.13% | Val loss: 0.8327 | Val acc: 58.80% | LR: 0.000064
Epoch: 111 | MCC: 0.054571 | Train loss: 0.9607 | Train acc: 52.08% | Val loss: 0.8276 | Val acc: 59.10% | LR: 0.000061
Epoch: 112 | MCC: 0.052932 | Train loss: 0.9582 | Train acc: 52.22% | Val loss: 0.8222 | Val acc: 59.40% | LR: 0.000058
Epoch: 113 | MCC: 0.053242 | Train loss: 0.9566 | Train acc: 52.31% | Val loss: 0.8221 | Val acc: 59.42% | LR: 0.000055
Epoch: 114 | MCC: 0.055695 | Train loss: 0.9589 | Train acc: 52.19% | Val loss: 0.8278 | Val acc: 59.27% | LR: 0.000052
Epoch: 115 | MCC: 0.053984 | Train loss: 0.9597 | Train acc: 52.17% | Val loss: 0.8238 | Val acc: 59.35% | LR: 0.000050
Epoch: 116 | MCC: 0.054002 | Train loss: 0.9580 | Train acc: 52.21% | Val loss: 0.8241 | Val acc: 59.30% | LR: 0.000047
Epoch: 117 | MCC: 0.052489 | Train loss: 0.9584 | Train acc: 52.20% | Val loss: 0.8263 | Val acc: 59.25% | LR: 0.000044
Epoch: 118 | MCC: 0.054593 | Train loss: 0.9593 | Train acc: 52.16% | Val loss: 0.8231 | Val acc: 59.37% | LR: 0.000042
Epoch: 119 | MCC: 0.054189 | Train loss: 0.9572 | Train acc: 52.27% | Val loss: 0.8263 | Val acc: 59.23% | LR: 0.000039
Epoch: 120 | MCC: 0.056282 | Train loss: 0.9578 | Train acc: 52.24% | Val loss: 0.8240 | Val acc: 59.35% | LR: 0.000037
Epoch: 121 | MCC: 0.057171 | Train loss: 0.9587 | Train acc: 52.22% | Val loss: 0.8242 | Val acc: 59.45% | LR: 0.000034
Epoch: 122 | MCC: 0.058950 | Train loss: 0.9575 | Train acc: 52.27% | Val loss: 0.8260 | Val acc: 59.32% | LR: 0.000032
Epoch: 123 | MCC: 0.056049 | Train loss: 0.9575 | Train acc: 52.27% | Val loss: 0.8235 | Val acc: 59.45% | LR: 0.000030
Epoch: 124 | MCC: 0.055910 | Train loss: 0.9589 | Train acc: 52.20% | Val loss: 0.8233 | Val acc: 59.45% | LR: 0.000028
Epoch: 125 | MCC: 0.056677 | Train loss: 0.9581 | Train acc: 52.22% | Val loss: 0.8235 | Val acc: 59.40% | LR: 0.000026
Epoch: 126 | MCC: 0.056845 | Train loss: 0.9577 | Train acc: 52.25% | Val loss: 0.8230 | Val acc: 59.47% | LR: 0.000024
Epoch: 127 | MCC: 0.056327 | Train loss: 0.9583 | Train acc: 52.21% | Val loss: 0.8242 | Val acc: 59.37% | LR: 0.000022
Epoch: 128 | MCC: 0.056836 | Train loss: 0.9575 | Train acc: 52.29% | Val loss: 0.8226 | Val acc: 59.45% | LR: 0.000020
Epoch: 129 | MCC: 0.056690 | Train loss: 0.9574 | Train acc: 52.26% | Val loss: 0.8237 | Val acc: 59.42% | LR: 0.000018
Epoch: 130 | MCC: 0.056690 | Train loss: 0.9592 | Train acc: 52.19% | Val loss: 0.8246 | Val acc: 59.42% | LR: 0.000017
Epoch: 131 | MCC: 0.056836 | Train loss: 0.9589 | Train acc: 52.20% | Val loss: 0.8232 | Val acc: 59.45% | LR: 0.000015
Epoch: 132 | MCC: 0.056890 | Train loss: 0.9605 | Train acc: 52.09% | Val loss: 0.8241 | Val acc: 59.40% | LR: 0.000014
Epoch: 133 | MCC: 0.056591 | Train loss: 0.9595 | Train acc: 52.17% | Val loss: 0.8234 | Val acc: 59.42% | LR: 0.000012
Epoch: 134 | MCC: 0.056690 | Train loss: 0.9596 | Train acc: 52.14% | Val loss: 0.8237 | Val acc: 59.42% | LR: 0.000011
Epoch: 135 | MCC: 0.056301 | Train loss: 0.9568 | Train acc: 52.30% | Val loss: 0.8238 | Val acc: 59.37% | LR: 0.000010

[I 2025-10-05 10:18:06,053] Trial 49 finished with value: 0.056836153380572796 and parameters: {'lr': 0.0004018003046121114, 'hidden_size': 92, 'dropout': 0.11628352818990358, 'weight_decay': 0.014590102998735713}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.027042 | Train loss: 1.0008 | Train acc: 49.79% | Val loss: 0.9956 | Val acc: 53.08% | LR: 0.000279
Epoch: 001 | MCC: 0.020553 | Train loss: 0.9986 | Train acc: 50.39% | Val loss: 0.9938 | Val acc: 53.47% | LR: 0.000279
Epoch: 002 | MCC: 0.013281 | Train loss: 0.9962 | Train acc: 51.40% | Val loss: 0.9913 | Val acc: 53.48% | LR: 0.000279
Epoch: 003 | MCC: 0.014089 | Train loss: 0.9936 | Train acc: 50.98% | Val loss: 0.9880 | Val acc: 54.17% | LR: 0.000279
Epoch: 004 | MCC: 0.022047 | Train loss: 1.0160 | Train acc: 50.81% | Val loss: 0.9843 | Val acc: 54.65% | LR: 0.000279
Epoch: 005 | MCC: 0.024505 | Train loss: 0.9950 | Train acc: 50.71% | Val loss: 0.9824 | Val acc: 54.84% | LR: 0.000278
Epoch: 006 | MCC: 0.030147 | Train loss: 0.9859 | Train acc: 50.97% | Val loss: 0.9728 | Val acc: 55.12% | LR: 0.000278
Epoch: 007 | MCC: 0.028134 | Train loss: 0.9832 | Train acc: 51.00% | Val loss: 0.9645 | Val acc: 55.31% | LR: 0.000277
Epoch: 008 | MCC: 0.033222 | Train loss: 0.9822 | Train acc: 50.96% | Val loss: 0.9839 | Val acc: 55.67% | LR: 0.000277
Epoch: 009 | MCC: 0.029813 | Train loss: 0.9897 | Train acc: 50.94% | Val loss: 0.9541 | Val acc: 55.66% | LR: 0.000276
Epoch: 010 | MCC: 0.024878 | Train loss: 0.9825 | Train acc: 50.90% | Val loss: 0.9441 | Val acc: 55.41% | LR: 0.000276
Epoch: 011 | MCC: 0.015647 | Train loss: 0.9811 | Train acc: 51.02% | Val loss: 0.9659 | Val acc: 55.18% | LR: 0.000275
Epoch: 012 | MCC: 0.024492 | Train loss: 0.9815 | Train acc: 50.92% | Val loss: 0.9620 | Val acc: 55.67% | LR: 0.000274
Epoch: 013 | MCC: 0.023131 | Train loss: 0.9798 | Train acc: 51.03% | Val loss: 0.9425 | Val acc: 55.83% | LR: 0.000273
Epoch: 014 | MCC: 0.014886 | Train loss: 0.9817 | Train acc: 50.79% | Val loss: 0.9515 | Val acc: 55.51% | LR: 0.000273
Epoch: 015 | MCC: 0.018341 | Train loss: 0.9795 | Train acc: 50.97% | Val loss: 0.9584 | Val acc: 55.64% | LR: 0.000272
Epoch: 016 | MCC: 0.022357 | Train loss: 0.9792 | Train acc: 51.02% | Val loss: 0.9324 | Val acc: 56.09% | LR: 0.000271
Epoch: 017 | MCC: 0.017803 | Train loss: 0.9823 | Train acc: 50.94% | Val loss: 0.9290 | Val acc: 55.97% | LR: 0.000270
Epoch: 018 | MCC: 0.022330 | Train loss: 0.9792 | Train acc: 50.91% | Val loss: 0.9230 | Val acc: 56.05% | LR: 0.000269
Epoch: 019 | MCC: 0.031727 | Train loss: 0.9791 | Train acc: 51.41% | Val loss: 0.9211 | Val acc: 56.32% | LR: 0.000267
Epoch: 020 | MCC: 0.026001 | Train loss: 0.9807 | Train acc: 51.57% | Val loss: 0.9132 | Val acc: 56.30% | LR: 0.000266
Epoch: 021 | MCC: 0.032888 | Train loss: 0.9771 | Train acc: 51.03% | Val loss: 0.9083 | Val acc: 56.42% | LR: 0.000265
Epoch: 022 | MCC: 0.028380 | Train loss: 0.9795 | Train acc: 50.73% | Val loss: 0.9020 | Val acc: 56.33% | LR: 0.000264
Epoch: 023 | MCC: 0.030256 | Train loss: 0.9783 | Train acc: 51.27% | Val loss: 0.9017 | Val acc: 56.00% | LR: 0.000262
Epoch: 024 | MCC: 0.044218 | Train loss: 0.9792 | Train acc: 51.69% | Val loss: 0.8983 | Val acc: 56.66% | LR: 0.000261
Epoch: 025 | MCC: 0.038360 | Train loss: 0.9771 | Train acc: 51.59% | Val loss: 0.8932 | Val acc: 56.81% | LR: 0.000259
Epoch: 026 | MCC: 0.041400 | Train loss: 0.9774 | Train acc: 51.62% | Val loss: 0.8921 | Val acc: 56.80% | LR: 0.000258
Epoch: 027 | MCC: 0.039859 | Train loss: 0.9761 | Train acc: 51.75% | Val loss: 0.8886 | Val acc: 56.85% | LR: 0.000256
Epoch: 028 | MCC: 0.020610 | Train loss: 0.9747 | Train acc: 51.75% | Val loss: 0.8808 | Val acc: 56.50% | LR: 0.000255
Epoch: 029 | MCC: 0.030395 | Train loss: 0.9750 | Train acc: 51.74% | Val loss: 0.8825 | Val acc: 56.23% | LR: 0.000253
Epoch: 030 | MCC: 0.004492 | Train loss: 0.9731 | Train acc: 51.88% | Val loss: 0.8832 | Val acc: 56.01% | LR: 0.000251
Epoch: 031 | MCC: 0.005380 | Train loss: 0.9793 | Train acc: 51.95% | Val loss: 0.8805 | Val acc: 56.11% | LR: 0.000249
Epoch: 032 | MCC: 0.004219 | Train loss: 0.9803 | Train acc: 51.87% | Val loss: 0.8940 | Val acc: 55.85% | LR: 0.000247
Epoch: 033 | MCC: 0.004948 | Train loss: 0.9764 | Train acc: 51.86% | Val loss: 0.8917 | Val acc: 55.55% | LR: 0.000246
Epoch: 034 | MCC: -0.006626 | Train loss: 0.9713 | Train acc: 51.92% | Val loss: 0.8981 | Val acc: 55.73% | LR: 0.000244
Epoch: 035 | MCC: 0.004593 | Train loss: 0.9699 | Train acc: 51.97% | Val loss: 0.9118 | Val acc: 55.69% | LR: 0.000242
Epoch: 036 | MCC: 0.004778 | Train loss: 0.9692 | Train acc: 51.94% | Val loss: 0.8789 | Val acc: 56.29% | LR: 0.000240
Epoch: 037 | MCC: 0.006082 | Train loss: 0.9713 | Train acc: 51.84% | Val loss: 0.8830 | Val acc: 56.03% | LR: 0.000238
Epoch: 038 | MCC: 0.013000 | Train loss: 0.9724 | Train acc: 51.72% | Val loss: 0.8784 | Val acc: 56.32% | LR: 0.000235
Epoch: 039 | MCC: 0.012238 | Train loss: 0.9667 | Train acc: 52.02% | Val loss: 0.8730 | Val acc: 56.59% | LR: 0.000233
Epoch: 040 | MCC: 0.005131 | Train loss: 0.9646 | Train acc: 52.02% | Val loss: 0.8812 | Val acc: 55.83% | LR: 0.000231
Epoch: 041 | MCC: 0.008251 | Train loss: 0.9791 | Train acc: 51.90% | Val loss: 0.8610 | Val acc: 57.59% | LR: 0.000229
Epoch: 042 | MCC: 0.011614 | Train loss: 0.9670 | Train acc: 51.96% | Val loss: 0.8540 | Val acc: 57.96% | LR: 0.000227
Epoch: 043 | MCC: 0.003236 | Train loss: 0.9665 | Train acc: 51.92% | Val loss: 0.8621 | Val acc: 57.25% | LR: 0.000224
Epoch: 044 | MCC: 0.027594 | Train loss: 0.9691 | Train acc: 51.85% | Val loss: 0.8428 | Val acc: 58.64% | LR: 0.000222
Epoch: 045 | MCC: 0.039738 | Train loss: 0.9664 | Train acc: 51.98% | Val loss: 0.8268 | Val acc: 59.86% | LR: 0.000220
Epoch: 046 | MCC: 0.034420 | Train loss: 0.9632 | Train acc: 52.09% | Val loss: 0.8417 | Val acc: 58.81% | LR: 0.000217
Epoch: 047 | MCC: 0.024719 | Train loss: 0.9659 | Train acc: 51.87% | Val loss: 0.8288 | Val acc: 59.18% | LR: 0.000215
Epoch: 048 | MCC: 0.027404 | Train loss: 0.9655 | Train acc: 51.98% | Val loss: 0.8322 | Val acc: 58.98% | LR: 0.000212
Epoch: 049 | MCC: 0.025692 | Train loss: 0.9653 | Train acc: 52.00% | Val loss: 0.8187 | Val acc: 59.65% | LR: 0.000210
Epoch: 050 | MCC: 0.007880 | Train loss: 0.9633 | Train acc: 52.05% | Val loss: 0.8677 | Val acc: 56.71% | LR: 0.000207
Epoch: 051 | MCC: 0.024970 | Train loss: 0.9699 | Train acc: 51.81% | Val loss: 0.8796 | Val acc: 56.20% | LR: 0.000205
Epoch: 052 | MCC: 0.044642 | Train loss: 0.9683 | Train acc: 51.98% | Val loss: 0.8067 | Val acc: 60.54% | LR: 0.000202
Epoch: 053 | MCC: 0.029147 | Train loss: 0.9645 | Train acc: 52.13% | Val loss: 0.8306 | Val acc: 59.25% | LR: 0.000199
Epoch: 054 | MCC: 0.038651 | Train loss: 0.9647 | Train acc: 52.11% | Val loss: 0.8111 | Val acc: 59.96% | LR: 0.000197
Epoch: 055 | MCC: 0.033539 | Train loss: 0.9654 | Train acc: 52.01% | Val loss: 0.8172 | Val acc: 59.54% | LR: 0.000194
Epoch: 056 | MCC: 0.028640 | Train loss: 0.9654 | Train acc: 52.08% | Val loss: 0.8274 | Val acc: 58.96% | LR: 0.000191
Epoch: 057 | MCC: 0.035476 | Train loss: 0.9691 | Train acc: 52.06% | Val loss: 0.8156 | Val acc: 59.79% | LR: 0.000189
Epoch: 058 | MCC: 0.067464 | Train loss: 0.9677 | Train acc: 51.96% | Val loss: 0.8069 | Val acc: 60.14% | LR: 0.000186
Epoch: 059 | MCC: 0.030356 | Train loss: 0.9611 | Train acc: 52.24% | Val loss: 0.8242 | Val acc: 59.08% | LR: 0.000183
Epoch: 060 | MCC: 0.030160 | Train loss: 0.9600 | Train acc: 52.25% | Val loss: 0.8260 | Val acc: 59.08% | LR: 0.000180
Epoch: 061 | MCC: 0.036226 | Train loss: 0.9620 | Train acc: 52.18% | Val loss: 0.8212 | Val acc: 59.53% | LR: 0.000178
Epoch: 062 | MCC: 0.026634 | Train loss: 0.9659 | Train acc: 52.04% | Val loss: 0.8427 | Val acc: 58.10% | LR: 0.000175
Epoch: 063 | MCC: 0.027988 | Train loss: 0.9635 | Train acc: 52.03% | Val loss: 0.8395 | Val acc: 58.29% | LR: 0.000172
Epoch: 064 | MCC: 0.023465 | Train loss: 0.9635 | Train acc: 52.04% | Val loss: 0.8440 | Val acc: 57.97% | LR: 0.000169
Epoch: 065 | MCC: 0.029263 | Train loss: 0.9644 | Train acc: 52.00% | Val loss: 0.8369 | Val acc: 58.65% | LR: 0.000166
Epoch: 066 | MCC: 0.025016 | Train loss: 0.9634 | Train acc: 52.23% | Val loss: 0.8212 | Val acc: 59.24% | LR: 0.000163
Epoch: 067 | MCC: 0.066653 | Train loss: 0.9657 | Train acc: 51.89% | Val loss: 0.8048 | Val acc: 60.30% | LR: 0.000161
Epoch: 068 | MCC: 0.028283 | Train loss: 0.9666 | Train acc: 51.90% | Val loss: 0.8098 | Val acc: 59.92% | LR: 0.000158
Epoch: 069 | MCC: 0.030794 | Train loss: 0.9624 | Train acc: 52.14% | Val loss: 0.8083 | Val acc: 59.95% | LR: 0.000155
Epoch: 070 | MCC: 0.028265 | Train loss: 0.9629 | Train acc: 52.05% | Val loss: 0.8221 | Val acc: 59.23% | LR: 0.000152
Epoch: 071 | MCC: 0.026430 | Train loss: 0.9628 | Train acc: 52.06% | Val loss: 0.8157 | Val acc: 59.51% | LR: 0.000149
Epoch: 072 | MCC: 0.059484 | Train loss: 0.9630 | Train acc: 52.07% | Val loss: 0.8279 | Val acc: 59.05% | LR: 0.000146
Epoch: 073 | MCC: 0.032775 | Train loss: 0.9637 | Train acc: 52.13% | Val loss: 0.8388 | Val acc: 58.46% | LR: 0.000143
Epoch: 074 | MCC: 0.057930 | Train loss: 0.9638 | Train acc: 52.06% | Val loss: 0.8259 | Val acc: 59.01% | LR: 0.000140
Epoch: 075 | MCC: 0.038863 | Train loss: 0.9618 | Train acc: 52.08% | Val loss: 0.8335 | Val acc: 58.75% | LR: 0.000137
Epoch: 076 | MCC: 0.028803 | Train loss: 0.9607 | Train acc: 52.13% | Val loss: 0.8264 | Val acc: 59.07% | LR: 0.000134
Epoch: 077 | MCC: 0.025794 | Train loss: 0.9605 | Train acc: 52.18% | Val loss: 0.8273 | Val acc: 58.92% | LR: 0.000131
Epoch: 078 | MCC: 0.026161 | Train loss: 0.9615 | Train acc: 52.16% | Val loss: 0.8271 | Val acc: 58.90% | LR: 0.000129
Epoch: 079 | MCC: 0.035091 | Train loss: 0.9586 | Train acc: 52.29% | Val loss: 0.8164 | Val acc: 59.62% | LR: 0.000126
Epoch: 080 | MCC: 0.037022 | Train loss: 0.9609 | Train acc: 52.12% | Val loss: 0.8068 | Val acc: 60.22% | LR: 0.000123
Epoch: 081 | MCC: 0.032918 | Train loss: 0.9617 | Train acc: 52.11% | Val loss: 0.8172 | Val acc: 59.45% | LR: 0.000120
Epoch: 082 | MCC: 0.028276 | Train loss: 0.9609 | Train acc: 52.14% | Val loss: 0.8141 | Val acc: 59.63% | LR: 0.000117
Epoch: 083 | MCC: 0.035517 | Train loss: 0.9576 | Train acc: 52.31% | Val loss: 0.8234 | Val acc: 59.27% | LR: 0.000114
Epoch: 084 | MCC: 0.029225 | Train loss: 0.9599 | Train acc: 52.16% | Val loss: 0.8124 | Val acc: 59.69% | LR: 0.000111
Epoch: 085 | MCC: 0.035926 | Train loss: 0.9606 | Train acc: 52.13% | Val loss: 0.8186 | Val acc: 59.53% | LR: 0.000108
Epoch: 086 | MCC: 0.029104 | Train loss: 0.9616 | Train acc: 52.21% | Val loss: 0.8167 | Val acc: 59.65% | LR: 0.000106
Epoch: 087 | MCC: 0.034002 | Train loss: 0.9605 | Train acc: 52.21% | Val loss: 0.8165 | Val acc: 59.45% | LR: 0.000103
Epoch: 088 | MCC: 0.037315 | Train loss: 0.9600 | Train acc: 52.24% | Val loss: 0.8162 | Val acc: 59.57% | LR: 0.000100
Epoch: 089 | MCC: 0.027426 | Train loss: 0.9598 | Train acc: 52.22% | Val loss: 0.8159 | Val acc: 59.56% | LR: 0.000097
Epoch: 090 | MCC: 0.030336 | Train loss: 0.9608 | Train acc: 52.14% | Val loss: 0.8246 | Val acc: 59.26% | LR: 0.000094
Epoch: 091 | MCC: 0.024648 | Train loss: 0.9597 | Train acc: 52.22% | Val loss: 0.8132 | Val acc: 59.63% | LR: 0.000092
Epoch: 092 | MCC: 0.022845 | Train loss: 0.9614 | Train acc: 52.14% | Val loss: 0.8170 | Val acc: 59.46% | LR: 0.000089
Epoch: 093 | MCC: 0.036304 | Train loss: 0.9609 | Train acc: 52.16% | Val loss: 0.8174 | Val acc: 59.49% | LR: 0.000086
Epoch: 094 | MCC: 0.023459 | Train loss: 0.9604 | Train acc: 52.16% | Val loss: 0.8172 | Val acc: 59.41% | LR: 0.000084
Epoch: 095 | MCC: 0.022909 | Train loss: 0.9592 | Train acc: 52.23% | Val loss: 0.8166 | Val acc: 59.46% | LR: 0.000081
Epoch: 096 | MCC: 0.037545 | Train loss: 0.9601 | Train acc: 52.22% | Val loss: 0.8162 | Val acc: 59.57% | LR: 0.000078
Epoch: 097 | MCC: 0.022886 | Train loss: 0.9582 | Train acc: 52.29% | Val loss: 0.8149 | Val acc: 59.53% | LR: 0.000076
Epoch: 098 | MCC: 0.035875 | Train loss: 0.9598 | Train acc: 52.21% | Val loss: 0.8125 | Val acc: 59.76% | LR: 0.000073
Epoch: 099 | MCC: 0.036555 | Train loss: 0.9581 | Train acc: 52.30% | Val loss: 0.8173 | Val acc: 59.35% | LR: 0.000071
Epoch: 100 | MCC: 0.037618 | Train loss: 0.9574 | Train acc: 52.33% | Val loss: 0.8142 | Val acc: 59.79% | LR: 0.000068
Epoch: 101 | MCC: 0.031592 | Train loss: 0.9588 | Train acc: 52.27% | Val loss: 0.8141 | Val acc: 59.61% | LR: 0.000066
Epoch: 102 | MCC: 0.039172 | Train loss: 0.9589 | Train acc: 52.26% | Val loss: 0.8143 | Val acc: 59.62% | LR: 0.000063
Epoch: 103 | MCC: 0.033676 | Train loss: 0.9597 | Train acc: 52.19% | Val loss: 0.8145 | Val acc: 59.64% | LR: 0.000061
Epoch: 104 | MCC: 0.038313 | Train loss: 0.9599 | Train acc: 52.18% | Val loss: 0.8157 | Val acc: 59.59% | LR: 0.000058
Epoch: 105 | MCC: 0.033353 | Train loss: 0.9609 | Train acc: 52.15% | Val loss: 0.8199 | Val acc: 59.15% | LR: 0.000056
Epoch: 106 | MCC: 0.028996 | Train loss: 0.9619 | Train acc: 52.33% | Val loss: 0.8121 | Val acc: 59.73% | LR: 0.000054
Epoch: 107 | MCC: 0.034791 | Train loss: 0.9582 | Train acc: 52.30% | Val loss: 0.8207 | Val acc: 59.23% | LR: 0.000051
Epoch: 108 | MCC: 0.028560 | Train loss: 0.9590 | Train acc: 52.23% | Val loss: 0.8186 | Val acc: 59.34% | LR: 0.000049
Epoch: 109 | MCC: 0.024323 | Train loss: 0.9599 | Train acc: 52.18% | Val loss: 0.8152 | Val acc: 59.53% | LR: 0.000047
Epoch: 110 | MCC: 0.036217 | Train loss: 0.9565 | Train acc: 52.37% | Val loss: 0.8173 | Val acc: 59.47% | LR: 0.000045
Epoch: 111 | MCC: 0.024899 | Train loss: 0.9583 | Train acc: 52.28% | Val loss: 0.8159 | Val acc: 59.48% | LR: 0.000043
Epoch: 112 | MCC: 0.028393 | Train loss: 0.9562 | Train acc: 52.38% | Val loss: 0.8171 | Val acc: 59.51% | LR: 0.000041
Epoch: 113 | MCC: 0.029759 | Train loss: 0.9580 | Train acc: 52.27% | Val loss: 0.8168 | Val acc: 59.53% | LR: 0.000039
Epoch: 114 | MCC: 0.023621 | Train loss: 0.9592 | Train acc: 52.21% | Val loss: 0.8153 | Val acc: 59.46% | LR: 0.000037
Epoch: 115 | MCC: 0.029229 | Train loss: 0.9599 | Train acc: 52.21% | Val loss: 0.8161 | Val acc: 59.51% | LR: 0.000035
Epoch: 116 | MCC: 0.035402 | Train loss: 0.9562 | Train acc: 52.40% | Val loss: 0.8152 | Val acc: 59.59% | LR: 0.000033
Epoch: 117 | MCC: 0.029767 | Train loss: 0.9590 | Train acc: 52.25% | Val loss: 0.8159 | Val acc: 59.56% | LR: 0.000031
Epoch: 118 | MCC: 0.030443 | Train loss: 0.9595 | Train acc: 52.22% | Val loss: 0.8158 | Val acc: 59.56% | LR: 0.000029
Epoch: 119 | MCC: 0.033875 | Train loss: 0.9579 | Train acc: 52.29% | Val loss: 0.8155 | Val acc: 59.57% | LR: 0.000028
Epoch: 120 | MCC: 0.033036 | Train loss: 0.9574 | Train acc: 52.31% | Val loss: 0.8158 | Val acc: 59.52% | LR: 0.000026
Epoch: 121 | MCC: 0.035191 | Train loss: 0.9578 | Train acc: 52.30% | Val loss: 0.8155 | Val acc: 59.59% | LR: 0.000024
Epoch: 122 | MCC: 0.022460 | Train loss: 0.9594 | Train acc: 52.23% | Val loss: 0.8163 | Val acc: 59.41% | LR: 0.000023
Epoch: 123 | MCC: 0.034637 | Train loss: 0.9624 | Train acc: 52.07% | Val loss: 0.8156 | Val acc: 59.57% | LR: 0.000021
Epoch: 124 | MCC: 0.027634 | Train loss: 0.9558 | Train acc: 52.44% | Val loss: 0.8169 | Val acc: 59.46% | LR: 0.000020
Epoch: 125 | MCC: 0.028620 | Train loss: 0.9577 | Train acc: 52.30% | Val loss: 0.8158 | Val acc: 59.48% | LR: 0.000018
Epoch: 126 | MCC: 0.024447 | Train loss: 0.9575 | Train acc: 52.32% | Val loss: 0.8159 | Val acc: 59.46% | LR: 0.000017
Epoch: 127 | MCC: 0.029314 | Train loss: 0.9569 | Train acc: 52.35% | Val loss: 0.8159 | Val acc: 59.53% | LR: 0.000016
Epoch: 128 | MCC: 0.029314 | Train loss: 0.9593 | Train acc: 52.24% | Val loss: 0.8161 | Val acc: 59.53% | LR: 0.000014
Epoch: 129 | MCC: 0.028167 | Train loss: 0.9596 | Train acc: 52.20% | Val loss: 0.8159 | Val acc: 59.46% | LR: 0.000013
Epoch: 130 | MCC: 0.034872 | Train loss: 0.9579 | Train acc: 52.29% | Val loss: 0.8156 | Val acc: 59.57% | LR: 0.000012
Epoch: 131 | MCC: 0.029459 | Train loss: 0.9580 | Train acc: 52.30% | Val loss: 0.8160 | Val acc: 59.53% | LR: 0.000011
Epoch: 132 | MCC: 0.029314 | Train loss: 0.9569 | Train acc: 52.35% | Val loss: 0.8157 | Val acc: 59.53% | LR: 0.000010
Epoch: 133 | MCC: 0.029459 | Train loss: 0.9593 | Train acc: 52.25% | Val loss: 0.8158 | Val acc: 59.53% | LR: 0.000009
Epoch: 134 | MCC: 0.028167 | Train loss: 0.9572 | Train acc: 52.35% | Val loss: 0.8160 | Val acc: 59.46% | LR: 0.000008
Epoch: 135 | MCC: 0.029314 | Train loss: 0.9571 | Train acc: 52.35% | Val loss: 0.8156 | Val acc: 59.53% | LR: 0.000007
Epoch: 136 | MCC: 0.029314 | Train loss: 0.9586 | Train acc: 52.29% | Val loss: 0.8158 | Val acc: 59.53% | LR: 0.000006
Epoch: 137 | MCC: 0.029314 | Train loss: 0.9587 | Train acc: 52.27% | Val loss: 0.8156 | Val acc: 59.53% | LR: 0.000005
Epoch: 138 | MCC: 0.029314 | Train loss: 0.9589 | Train acc: 52.27% | Val loss: 0.8158 | Val acc: 59.53% | LR: 0.000005
Epoch: 139 | MCC: 0.029393 | Train loss: 0.9582 | Train acc: 52.29% | Val loss: 0.8158 | Val acc: 59.53% | LR: 0.000004
Epoch: 140 | MCC: 0.029459 | Train loss: 0.9590 | Train acc: 52.22% | Val loss: 0.8158 | Val acc: 59.53% | LR: 0.000003
Epoch: 141 | MCC: 0.029314 | Train loss: 0.9573 | Train acc: 52.32% | Val loss: 0.8158 | Val acc: 59.53% | LR: 0.000003

[I 2025-10-05 10:20:21,950] Trial 50 finished with value: 0.029313739389181137 and parameters: {'lr': 0.00027940521669265453, 'hidden_size': 93, 'dropout': 0.10772017953079799, 'weight_decay': 0.015453643249030065}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.015160 | Train loss: 0.9989 | Train acc: 50.45% | Val loss: 0.9840 | Val acc: 53.54% | LR: 0.000404
Epoch: 001 | MCC: 0.008833 | Train loss: 0.9952 | Train acc: 50.92% | Val loss: 0.9801 | Val acc: 53.62% | LR: 0.000404
Epoch: 002 | MCC: 0.022476 | Train loss: 0.9942 | Train acc: 50.89% | Val loss: 0.9721 | Val acc: 54.81% | LR: 0.000404
Epoch: 003 | MCC: 0.027212 | Train loss: 1.0023 | Train acc: 50.99% | Val loss: 0.9632 | Val acc: 55.11% | LR: 0.000404
Epoch: 004 | MCC: 0.025068 | Train loss: 0.9879 | Train acc: 50.88% | Val loss: 0.9469 | Val acc: 55.12% | LR: 0.000403
Epoch: 005 | MCC: 0.032734 | Train loss: 0.9851 | Train acc: 50.86% | Val loss: 0.9405 | Val acc: 55.84% | LR: 0.000403
Epoch: 006 | MCC: 0.024433 | Train loss: 0.9841 | Train acc: 50.79% | Val loss: 0.9325 | Val acc: 55.48% | LR: 0.000402
Epoch: 007 | MCC: 0.014241 | Train loss: 0.9833 | Train acc: 50.83% | Val loss: 0.9251 | Val acc: 55.60% | LR: 0.000401
Epoch: 008 | MCC: 0.019623 | Train loss: 0.9826 | Train acc: 50.80% | Val loss: 0.9160 | Val acc: 55.71% | LR: 0.000401
Epoch: 009 | MCC: 0.019327 | Train loss: 0.9819 | Train acc: 50.92% | Val loss: 0.9092 | Val acc: 56.13% | LR: 0.000400
Epoch: 010 | MCC: 0.049327 | Train loss: 0.9794 | Train acc: 51.22% | Val loss: 0.9014 | Val acc: 57.29% | LR: 0.000399
Epoch: 011 | MCC: 0.042454 | Train loss: 0.9800 | Train acc: 51.07% | Val loss: 0.8932 | Val acc: 57.52% | LR: 0.000398
Epoch: 012 | MCC: 0.011759 | Train loss: 0.9785 | Train acc: 51.19% | Val loss: 0.8826 | Val acc: 57.15% | LR: 0.000397
Epoch: 013 | MCC: 0.001604 | Train loss: 0.9772 | Train acc: 51.12% | Val loss: 0.8771 | Val acc: 56.81% | LR: 0.000396
Epoch: 014 | MCC: 0.002698 | Train loss: 0.9762 | Train acc: 51.19% | Val loss: 0.8680 | Val acc: 57.03% | LR: 0.000394
Epoch: 015 | MCC: 0.008586 | Train loss: 0.9752 | Train acc: 51.28% | Val loss: 0.8711 | Val acc: 56.88% | LR: 0.000393
Epoch: 016 | MCC: 0.020201 | Train loss: 0.9742 | Train acc: 51.31% | Val loss: 0.8492 | Val acc: 58.35% | LR: 0.000392
Epoch: 017 | MCC: 0.023165 | Train loss: 0.9751 | Train acc: 51.18% | Val loss: 0.8549 | Val acc: 57.96% | LR: 0.000390
Epoch: 018 | MCC: 0.027370 | Train loss: 0.9735 | Train acc: 51.32% | Val loss: 0.8307 | Val acc: 59.54% | LR: 0.000388
Epoch: 019 | MCC: 0.021614 | Train loss: 0.9715 | Train acc: 51.43% | Val loss: 0.8542 | Val acc: 57.69% | LR: 0.000387
Epoch: 020 | MCC: 0.018245 | Train loss: 0.9721 | Train acc: 51.32% | Val loss: 0.8437 | Val acc: 58.25% | LR: 0.000385
Epoch: 021 | MCC: 0.019870 | Train loss: 0.9714 | Train acc: 51.43% | Val loss: 0.8652 | Val acc: 57.91% | LR: 0.000383
Epoch: 022 | MCC: 0.031855 | Train loss: 0.9755 | Train acc: 51.37% | Val loss: 0.8681 | Val acc: 56.81% | LR: 0.000381
Epoch: 023 | MCC: 0.017139 | Train loss: 0.9716 | Train acc: 51.30% | Val loss: 0.8416 | Val acc: 58.10% | LR: 0.000379
Epoch: 024 | MCC: 0.030334 | Train loss: 0.9742 | Train acc: 51.23% | Val loss: 0.8566 | Val acc: 57.58% | LR: 0.000377
Epoch: 025 | MCC: 0.028690 | Train loss: 0.9731 | Train acc: 51.35% | Val loss: 0.8662 | Val acc: 56.92% | LR: 0.000375
Epoch: 026 | MCC: 0.028263 | Train loss: 0.9731 | Train acc: 51.22% | Val loss: 0.8542 | Val acc: 57.58% | LR: 0.000373
Epoch: 027 | MCC: 0.045357 | Train loss: 0.9722 | Train acc: 51.04% | Val loss: 0.8630 | Val acc: 57.44% | LR: 0.000371
Epoch: 028 | MCC: 0.031265 | Train loss: 0.9710 | Train acc: 52.03% | Val loss: 0.8515 | Val acc: 58.01% | LR: 0.000368
Epoch: 029 | MCC: 0.017498 | Train loss: 0.9692 | Train acc: 52.12% | Val loss: 0.8427 | Val acc: 58.46% | LR: 0.000366
Epoch: 030 | MCC: 0.015991 | Train loss: 0.9700 | Train acc: 51.90% | Val loss: 0.8561 | Val acc: 57.71% | LR: 0.000363
Epoch: 031 | MCC: 0.045568 | Train loss: 0.9702 | Train acc: 52.00% | Val loss: 0.8481 | Val acc: 58.56% | LR: 0.000361
Epoch: 032 | MCC: 0.019988 | Train loss: 0.9689 | Train acc: 52.23% | Val loss: 0.8529 | Val acc: 57.76% | LR: 0.000358
Epoch: 033 | MCC: 0.029593 | Train loss: 0.9674 | Train acc: 52.12% | Val loss: 0.8437 | Val acc: 58.35% | LR: 0.000355
Epoch: 034 | MCC: 0.017430 | Train loss: 0.9657 | Train acc: 52.11% | Val loss: 0.8567 | Val acc: 57.32% | LR: 0.000352
Epoch: 035 | MCC: 0.018800 | Train loss: 0.9686 | Train acc: 51.90% | Val loss: 0.8574 | Val acc: 57.66% | LR: 0.000350
Epoch: 036 | MCC: 0.013032 | Train loss: 0.9669 | Train acc: 52.12% | Val loss: 0.8465 | Val acc: 58.09% | LR: 0.000347
Epoch: 037 | MCC: 0.035501 | Train loss: 0.9680 | Train acc: 52.18% | Val loss: 0.8471 | Val acc: 58.22% | LR: 0.000344
Epoch: 038 | MCC: 0.031286 | Train loss: 0.9661 | Train acc: 52.10% | Val loss: 0.8336 | Val acc: 58.88% | LR: 0.000341
Epoch: 039 | MCC: 0.067182 | Train loss: 0.9660 | Train acc: 52.06% | Val loss: 0.8318 | Val acc: 58.99% | LR: 0.000338
Epoch: 040 | MCC: 0.025103 | Train loss: 0.9660 | Train acc: 51.99% | Val loss: 0.8588 | Val acc: 57.64% | LR: 0.000334
Epoch: 041 | MCC: 0.029142 | Train loss: 0.9627 | Train acc: 52.16% | Val loss: 0.8488 | Val acc: 58.03% | LR: 0.000331
Epoch: 042 | MCC: 0.043843 | Train loss: 0.9647 | Train acc: 52.05% | Val loss: 0.8303 | Val acc: 58.99% | LR: 0.000328
Epoch: 043 | MCC: 0.025182 | Train loss: 0.9627 | Train acc: 52.19% | Val loss: 0.8480 | Val acc: 58.01% | LR: 0.000325
Epoch: 044 | MCC: 0.037380 | Train loss: 0.9638 | Train acc: 52.08% | Val loss: 0.8294 | Val acc: 59.35% | LR: 0.000321
Epoch: 045 | MCC: 0.042872 | Train loss: 0.9616 | Train acc: 52.26% | Val loss: 0.8306 | Val acc: 59.05% | LR: 0.000318
Epoch: 046 | MCC: 0.032522 | Train loss: 0.9656 | Train acc: 52.02% | Val loss: 0.8511 | Val acc: 57.93% | LR: 0.000314
Epoch: 047 | MCC: 0.023351 | Train loss: 0.9648 | Train acc: 52.05% | Val loss: 0.8586 | Val acc: 57.44% | LR: 0.000311
Epoch: 048 | MCC: 0.013206 | Train loss: 0.9622 | Train acc: 52.15% | Val loss: 0.8465 | Val acc: 58.07% | LR: 0.000307
Epoch: 049 | MCC: 0.012890 | Train loss: 0.9638 | Train acc: 52.11% | Val loss: 0.8436 | Val acc: 58.17% | LR: 0.000303
Epoch: 050 | MCC: 0.026604 | Train loss: 0.9608 | Train acc: 52.27% | Val loss: 0.8587 | Val acc: 57.37% | LR: 0.000300
Epoch: 051 | MCC: 0.054179 | Train loss: 0.9624 | Train acc: 52.16% | Val loss: 0.8319 | Val acc: 59.18% | LR: 0.000296
Epoch: 052 | MCC: 0.030172 | Train loss: 0.9615 | Train acc: 52.20% | Val loss: 0.8447 | Val acc: 58.20% | LR: 0.000292
Epoch: 053 | MCC: 0.032298 | Train loss: 0.9632 | Train acc: 52.11% | Val loss: 0.8398 | Val acc: 58.35% | LR: 0.000288
Epoch: 054 | MCC: 0.025972 | Train loss: 0.9624 | Train acc: 52.12% | Val loss: 0.8272 | Val acc: 59.01% | LR: 0.000285
Epoch: 055 | MCC: 0.024971 | Train loss: 0.9606 | Train acc: 52.25% | Val loss: 0.8412 | Val acc: 58.27% | LR: 0.000281
Epoch: 056 | MCC: 0.023617 | Train loss: 0.9617 | Train acc: 52.17% | Val loss: 0.8450 | Val acc: 58.05% | LR: 0.000277
Epoch: 057 | MCC: 0.036701 | Train loss: 0.9600 | Train acc: 52.28% | Val loss: 0.8226 | Val acc: 59.45% | LR: 0.000273
Epoch: 058 | MCC: 0.024303 | Train loss: 0.9619 | Train acc: 52.17% | Val loss: 0.8399 | Val acc: 58.30% | LR: 0.000269
Epoch: 059 | MCC: 0.030967 | Train loss: 0.9606 | Train acc: 52.19% | Val loss: 0.8220 | Val acc: 59.20% | LR: 0.000265
Epoch: 060 | MCC: 0.041924 | Train loss: 0.9674 | Train acc: 52.29% | Val loss: 0.8188 | Val acc: 59.84% | LR: 0.000261
Epoch: 061 | MCC: 0.026613 | Train loss: 0.9629 | Train acc: 52.28% | Val loss: 0.8416 | Val acc: 58.20% | LR: 0.000257
Epoch: 062 | MCC: 0.036344 | Train loss: 0.9630 | Train acc: 52.23% | Val loss: 0.8278 | Val acc: 59.03% | LR: 0.000253
Epoch: 063 | MCC: 0.025273 | Train loss: 0.9625 | Train acc: 52.20% | Val loss: 0.8361 | Val acc: 58.37% | LR: 0.000249
Epoch: 064 | MCC: 0.052615 | Train loss: 0.9626 | Train acc: 52.21% | Val loss: 0.8202 | Val acc: 59.51% | LR: 0.000245
Epoch: 065 | MCC: 0.023018 | Train loss: 0.9628 | Train acc: 52.12% | Val loss: 0.8272 | Val acc: 58.91% | LR: 0.000240
Epoch: 066 | MCC: 0.023036 | Train loss: 0.9640 | Train acc: 52.07% | Val loss: 0.8333 | Val acc: 58.69% | LR: 0.000236
Epoch: 067 | MCC: 0.029217 | Train loss: 0.9621 | Train acc: 52.12% | Val loss: 0.8424 | Val acc: 58.32% | LR: 0.000232
Epoch: 068 | MCC: 0.037578 | Train loss: 0.9617 | Train acc: 52.18% | Val loss: 0.8356 | Val acc: 58.62% | LR: 0.000228
Epoch: 069 | MCC: 0.027157 | Train loss: 0.9681 | Train acc: 52.27% | Val loss: 0.8419 | Val acc: 58.27% | LR: 0.000224
Epoch: 070 | MCC: 0.034724 | Train loss: 0.9609 | Train acc: 52.28% | Val loss: 0.8230 | Val acc: 59.30% | LR: 0.000219
Epoch: 071 | MCC: 0.044063 | Train loss: 0.9590 | Train acc: 52.30% | Val loss: 0.8165 | Val acc: 59.67% | LR: 0.000215
Epoch: 072 | MCC: 0.040133 | Train loss: 0.9615 | Train acc: 52.14% | Val loss: 0.8168 | Val acc: 59.59% | LR: 0.000211
Epoch: 073 | MCC: 0.024287 | Train loss: 0.9617 | Train acc: 52.19% | Val loss: 0.8357 | Val acc: 58.59% | LR: 0.000207
Epoch: 074 | MCC: 0.035506 | Train loss: 0.9594 | Train acc: 52.29% | Val loss: 0.8201 | Val acc: 59.40% | LR: 0.000203
Epoch: 075 | MCC: 0.025659 | Train loss: 0.9611 | Train acc: 52.18% | Val loss: 0.8347 | Val acc: 58.59% | LR: 0.000198
Epoch: 076 | MCC: 0.024999 | Train loss: 0.9608 | Train acc: 52.15% | Val loss: 0.8242 | Val acc: 58.98% | LR: 0.000194
Epoch: 077 | MCC: 0.059275 | Train loss: 0.9616 | Train acc: 52.15% | Val loss: 0.8162 | Val acc: 59.67% | LR: 0.000190
Epoch: 078 | MCC: 0.035747 | Train loss: 0.9615 | Train acc: 52.16% | Val loss: 0.8209 | Val acc: 59.40% | LR: 0.000186
Epoch: 079 | MCC: 0.036780 | Train loss: 0.9584 | Train acc: 52.40% | Val loss: 0.8177 | Val acc: 59.45% | LR: 0.000182
Epoch: 080 | MCC: 0.033041 | Train loss: 0.9616 | Train acc: 52.17% | Val loss: 0.8341 | Val acc: 58.57% | LR: 0.000177
Epoch: 081 | MCC: 0.046755 | Train loss: 0.9619 | Train acc: 52.09% | Val loss: 0.8325 | Val acc: 58.68% | LR: 0.000173
Epoch: 082 | MCC: 0.029142 | Train loss: 0.9592 | Train acc: 52.27% | Val loss: 0.8246 | Val acc: 59.13% | LR: 0.000169
Epoch: 083 | MCC: 0.029739 | Train loss: 0.9679 | Train acc: 52.32% | Val loss: 0.8219 | Val acc: 59.15% | LR: 0.000165
Epoch: 084 | MCC: 0.032299 | Train loss: 0.9611 | Train acc: 52.37% | Val loss: 0.8221 | Val acc: 59.13% | LR: 0.000161
Epoch: 085 | MCC: 0.028022 | Train loss: 0.9617 | Train acc: 52.18% | Val loss: 0.8249 | Val acc: 59.03% | LR: 0.000157
Epoch: 086 | MCC: 0.060292 | Train loss: 0.9612 | Train acc: 52.22% | Val loss: 0.8194 | Val acc: 59.47% | LR: 0.000152
Epoch: 087 | MCC: 0.031966 | Train loss: 0.9677 | Train acc: 52.33% | Val loss: 0.8262 | Val acc: 58.93% | LR: 0.000148
Epoch: 088 | MCC: 0.034547 | Train loss: 0.9601 | Train acc: 52.25% | Val loss: 0.8301 | Val acc: 59.05% | LR: 0.000144
Epoch: 089 | MCC: 0.053811 | Train loss: 0.9604 | Train acc: 52.24% | Val loss: 0.8207 | Val acc: 59.29% | LR: 0.000140
Epoch: 090 | MCC: 0.031873 | Train loss: 0.9610 | Train acc: 52.17% | Val loss: 0.8221 | Val acc: 59.20% | LR: 0.000136
Epoch: 091 | MCC: 0.053789 | Train loss: 0.9591 | Train acc: 52.26% | Val loss: 0.8178 | Val acc: 59.46% | LR: 0.000132
Epoch: 092 | MCC: 0.031472 | Train loss: 0.9583 | Train acc: 52.31% | Val loss: 0.8225 | Val acc: 59.20% | LR: 0.000128
Epoch: 093 | MCC: 0.039116 | Train loss: 0.9611 | Train acc: 52.15% | Val loss: 0.8240 | Val acc: 59.18% | LR: 0.000124
Epoch: 094 | MCC: 0.035715 | Train loss: 0.9589 | Train acc: 52.30% | Val loss: 0.8140 | Val acc: 59.62% | LR: 0.000121
Epoch: 095 | MCC: 0.037786 | Train loss: 0.9605 | Train acc: 52.18% | Val loss: 0.8251 | Val acc: 59.08% | LR: 0.000117
Epoch: 096 | MCC: 0.054715 | Train loss: 0.9604 | Train acc: 52.22% | Val loss: 0.8136 | Val acc: 59.65% | LR: 0.000113
Epoch: 097 | MCC: 0.030268 | Train loss: 0.9602 | Train acc: 52.22% | Val loss: 0.8318 | Val acc: 58.66% | LR: 0.000109
Epoch: 098 | MCC: 0.032028 | Train loss: 0.9589 | Train acc: 52.27% | Val loss: 0.8163 | Val acc: 59.53% | LR: 0.000105
Epoch: 099 | MCC: 0.033956 | Train loss: 0.9571 | Train acc: 52.38% | Val loss: 0.8239 | Val acc: 59.15% | LR: 0.000102
Epoch: 100 | MCC: 0.034570 | Train loss: 0.9592 | Train acc: 52.30% | Val loss: 0.8150 | Val acc: 59.58% | LR: 0.000098
Epoch: 101 | MCC: 0.034500 | Train loss: 0.9589 | Train acc: 52.28% | Val loss: 0.8238 | Val acc: 59.10% | LR: 0.000095
Epoch: 102 | MCC: 0.038787 | Train loss: 0.9588 | Train acc: 52.29% | Val loss: 0.8173 | Val acc: 59.52% | LR: 0.000091
Epoch: 103 | MCC: 0.039697 | Train loss: 0.9589 | Train acc: 52.31% | Val loss: 0.8235 | Val acc: 59.15% | LR: 0.000088
Epoch: 104 | MCC: 0.034720 | Train loss: 0.9564 | Train acc: 52.43% | Val loss: 0.8149 | Val acc: 59.61% | LR: 0.000084
Epoch: 105 | MCC: 0.040424 | Train loss: 0.9568 | Train acc: 52.40% | Val loss: 0.8189 | Val acc: 59.37% | LR: 0.000081
Epoch: 106 | MCC: 0.039261 | Train loss: 0.9597 | Train acc: 52.21% | Val loss: 0.8216 | Val acc: 59.23% | LR: 0.000077
Epoch: 107 | MCC: 0.039703 | Train loss: 0.9580 | Train acc: 52.33% | Val loss: 0.8185 | Val acc: 59.40% | LR: 0.000074
Epoch: 108 | MCC: 0.034042 | Train loss: 0.9552 | Train acc: 52.47% | Val loss: 0.8234 | Val acc: 59.05% | LR: 0.000071
Epoch: 109 | MCC: 0.036704 | Train loss: 0.9581 | Train acc: 52.33% | Val loss: 0.8254 | Val acc: 59.05% | LR: 0.000068
Epoch: 110 | MCC: 0.043523 | Train loss: 0.9545 | Train acc: 52.53% | Val loss: 0.8131 | Val acc: 59.76% | LR: 0.000065
Epoch: 111 | MCC: 0.036558 | Train loss: 0.9568 | Train acc: 52.39% | Val loss: 0.8214 | Val acc: 59.18% | LR: 0.000062
Epoch: 112 | MCC: 0.044622 | Train loss: 0.9586 | Train acc: 52.33% | Val loss: 0.8126 | Val acc: 59.79% | LR: 0.000059
Epoch: 113 | MCC: 0.037102 | Train loss: 0.9583 | Train acc: 52.32% | Val loss: 0.8209 | Val acc: 59.30% | LR: 0.000056
Epoch: 114 | MCC: 0.038315 | Train loss: 0.9552 | Train acc: 52.47% | Val loss: 0.8186 | Val acc: 59.37% | LR: 0.000053
Epoch: 115 | MCC: 0.038162 | Train loss: 0.9546 | Train acc: 52.51% | Val loss: 0.8168 | Val acc: 59.47% | LR: 0.000050
Epoch: 116 | MCC: 0.042241 | Train loss: 0.9555 | Train acc: 52.47% | Val loss: 0.8177 | Val acc: 59.52% | LR: 0.000047
Epoch: 117 | MCC: 0.040725 | Train loss: 0.9569 | Train acc: 52.39% | Val loss: 0.8188 | Val acc: 59.40% | LR: 0.000045
Epoch: 118 | MCC: 0.037925 | Train loss: 0.9554 | Train acc: 52.47% | Val loss: 0.8201 | Val acc: 59.25% | LR: 0.000042
Epoch: 119 | MCC: 0.039743 | Train loss: 0.9580 | Train acc: 52.33% | Val loss: 0.8200 | Val acc: 59.35% | LR: 0.000040
Epoch: 120 | MCC: 0.039657 | Train loss: 0.9549 | Train acc: 52.51% | Val loss: 0.8186 | Val acc: 59.40% | LR: 0.000037
Epoch: 121 | MCC: 0.042012 | Train loss: 0.9552 | Train acc: 52.45% | Val loss: 0.8173 | Val acc: 59.47% | LR: 0.000035
Epoch: 122 | MCC: 0.042398 | Train loss: 0.9562 | Train acc: 52.43% | Val loss: 0.8175 | Val acc: 59.57% | LR: 0.000032
Epoch: 123 | MCC: 0.036880 | Train loss: 0.9571 | Train acc: 52.38% | Val loss: 0.8178 | Val acc: 59.45% | LR: 0.000030
Epoch: 124 | MCC: 0.038493 | Train loss: 0.9548 | Train acc: 52.49% | Val loss: 0.8197 | Val acc: 59.30% | LR: 0.000028
Epoch: 125 | MCC: 0.043376 | Train loss: 0.9560 | Train acc: 52.44% | Val loss: 0.8172 | Val acc: 59.59% | LR: 0.000026
Epoch: 126 | MCC: 0.038493 | Train loss: 0.9548 | Train acc: 52.53% | Val loss: 0.8198 | Val acc: 59.30% | LR: 0.000024
Epoch: 127 | MCC: 0.043214 | Train loss: 0.9549 | Train acc: 52.50% | Val loss: 0.8150 | Val acc: 59.69% | LR: 0.000022
Epoch: 128 | MCC: 0.040347 | Train loss: 0.9592 | Train acc: 52.27% | Val loss: 0.8181 | Val acc: 59.42% | LR: 0.000020
Epoch: 129 | MCC: 0.040124 | Train loss: 0.9556 | Train acc: 52.47% | Val loss: 0.8157 | Val acc: 59.59% | LR: 0.000018
Epoch: 130 | MCC: 0.042166 | Train loss: 0.9556 | Train acc: 52.45% | Val loss: 0.8180 | Val acc: 59.52% | LR: 0.000017
Epoch: 131 | MCC: 0.043637 | Train loss: 0.9562 | Train acc: 52.52% | Val loss: 0.8176 | Val acc: 59.59% | LR: 0.000015
Epoch: 132 | MCC: 0.043637 | Train loss: 0.9574 | Train acc: 52.34% | Val loss: 0.8171 | Val acc: 59.59% | LR: 0.000014
Epoch: 133 | MCC: 0.044208 | Train loss: 0.9572 | Train acc: 52.33% | Val loss: 0.8168 | Val acc: 59.64% | LR: 0.000012
Epoch: 134 | MCC: 0.039933 | Train loss: 0.9554 | Train acc: 52.47% | Val loss: 0.8186 | Val acc: 59.37% | LR: 0.000011
Epoch: 135 | MCC: 0.039743 | Train loss: 0.9563 | Train acc: 52.43% | Val loss: 0.8184 | Val acc: 59.35% | LR: 0.000010
Epoch: 136 | MCC: 0.041898 | Train loss: 0.9569 | Train acc: 52.46% | Val loss: 0.8176 | Val acc: 59.49% | LR: 0.000008
Epoch: 137 | MCC: 0.041637 | Train loss: 0.9579 | Train acc: 52.35% | Val loss: 0.8177 | Val acc: 59.49% | LR: 0.000007
Epoch: 138 | MCC: 0.039933 | Train loss: 0.9556 | Train acc: 52.47% | Val loss: 0.8181 | Val acc: 59.37% | LR: 0.000006
Epoch: 139 | MCC: 0.043376 | Train loss: 0.9575 | Train acc: 52.37% | Val loss: 0.8174 | Val acc: 59.59% | LR: 0.000005
Epoch: 140 | MCC: 0.042806 | Train loss: 0.9543 | Train acc: 52.53% | Val loss: 0.8172 | Val acc: 59.54% | LR: 0.000005
Epoch: 141 | MCC: 0.041898 | Train loss: 0.9598 | Train acc: 52.45% | Val loss: 0.8175 | Val acc: 59.49% | LR: 0.000004
Epoch: 142 | MCC: 0.042806 | Train loss: 0.9551 | Train acc: 52.50% | Val loss: 0.8174 | Val acc: 59.54% | LR: 0.000003
Epoch: 143 | MCC: 0.042806 | Train loss: 0.9563 | Train acc: 52.42% | Val loss: 0.8174 | Val acc: 59.54% | LR: 0.000003
Epoch: 144 | MCC: 0.041898 | Train loss: 0.9562 | Train acc: 52.45% | Val loss: 0.8176 | Val acc: 59.49% | LR: 0.000002
Epoch: 145 | MCC: 0.041898 | Train loss: 0.9567 | Train acc: 52.43% | Val loss: 0.8174 | Val acc: 59.49% | LR: 0.000002
Epoch: 146 | MCC: 0.041898 | Train loss: 0.9566 | Train acc: 52.42% | Val loss: 0.8175 | Val acc: 59.49% | LR: 0.000001
Epoch: 147 | MCC: 0.042806 | Train loss: 0.9578 | Train acc: 52.33% | Val loss: 0.8173 | Val acc: 59.54% | LR: 0.000001
Epoch: 148 | MCC: 0.042806 | Train loss: 0.9554 | Train acc: 52.46% | Val loss: 0.8173 | Val acc: 59.54% | LR: 0.000001
Epoch: 149 | MCC: 0.041898 | Train loss: 0.9562 | Train acc: 52.49% | Val loss: 0.8175 | Val acc: 59.49% | LR: 0.000001

[I 2025-10-05 10:22:28,136] Trial 51 finished with value: 0.04189843591302633 and parameters: {'lr': 0.0004042507600113385, 'hidden_size': 63, 'dropout': 0.09040645876805864, 'weight_decay': 0.026551174436691763}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.038074 | Train loss: 1.0075 | Train acc: 50.48% | Val loss: 1.0008 | Val acc: 50.31% | LR: 0.000713
Epoch: 001 | MCC: 0.037848 | Train loss: 0.9920 | Train acc: 51.12% | Val loss: 0.9930 | Val acc: 53.92% | LR: 0.000712
Epoch: 002 | MCC: 0.039082 | Train loss: 0.9868 | Train acc: 51.01% | Val loss: 0.9825 | Val acc: 54.23% | LR: 0.000712
Epoch: 003 | MCC: 0.040578 | Train loss: 0.9857 | Train acc: 50.81% | Val loss: 0.9675 | Val acc: 54.73% | LR: 0.000711
Epoch: 004 | MCC: 0.023274 | Train loss: 0.9828 | Train acc: 51.02% | Val loss: 0.9489 | Val acc: 54.52% | LR: 0.000711
Epoch: 005 | MCC: 0.028062 | Train loss: 0.9815 | Train acc: 50.96% | Val loss: 0.9386 | Val acc: 55.37% | LR: 0.000710
Epoch: 006 | MCC: 0.024274 | Train loss: 0.9821 | Train acc: 50.89% | Val loss: 0.9269 | Val acc: 55.41% | LR: 0.000709
Epoch: 007 | MCC: 0.023441 | Train loss: 0.9807 | Train acc: 50.96% | Val loss: 0.9122 | Val acc: 55.86% | LR: 0.000708
Epoch: 008 | MCC: 0.037360 | Train loss: 0.9818 | Train acc: 50.84% | Val loss: 0.9032 | Val acc: 56.41% | LR: 0.000706
Epoch: 009 | MCC: 0.036085 | Train loss: 0.9811 | Train acc: 50.88% | Val loss: 1.0242 | Val acc: 56.80% | LR: 0.000705
Epoch: 010 | MCC: 0.032527 | Train loss: 0.9903 | Train acc: 50.94% | Val loss: 0.9443 | Val acc: 56.12% | LR: 0.000703
Epoch: 011 | MCC: 0.031466 | Train loss: 0.9882 | Train acc: 50.91% | Val loss: 0.9393 | Val acc: 56.31% | LR: 0.000702
Epoch: 012 | MCC: 0.029406 | Train loss: 0.9851 | Train acc: 51.08% | Val loss: 0.9362 | Val acc: 56.82% | LR: 0.000700
Epoch: 013 | MCC: 0.022557 | Train loss: 0.9870 | Train acc: 51.21% | Val loss: 0.9284 | Val acc: 55.81% | LR: 0.000698
Epoch: 014 | MCC: 0.039022 | Train loss: 0.9777 | Train acc: 51.64% | Val loss: 0.9167 | Val acc: 55.51% | LR: 0.000695
Epoch: 015 | MCC: 0.033841 | Train loss: 0.9777 | Train acc: 51.61% | Val loss: 0.9205 | Val acc: 55.20% | LR: 0.000693
Epoch: 016 | MCC: 0.033586 | Train loss: 0.9782 | Train acc: 51.59% | Val loss: 0.9172 | Val acc: 54.45% | LR: 0.000690
Epoch: 017 | MCC: 0.030737 | Train loss: 0.9774 | Train acc: 51.60% | Val loss: 0.9131 | Val acc: 54.44% | LR: 0.000688
Epoch: 018 | MCC: 0.026223 | Train loss: 1.0035 | Train acc: 51.47% | Val loss: 0.9163 | Val acc: 54.34% | LR: 0.000685
Epoch: 019 | MCC: 0.025053 | Train loss: 0.9804 | Train acc: 51.60% | Val loss: 0.9358 | Val acc: 54.84% | LR: 0.000682
Epoch: 020 | MCC: 0.029479 | Train loss: 0.9879 | Train acc: 51.51% | Val loss: 0.9187 | Val acc: 54.30% | LR: 0.000679
Epoch: 021 | MCC: 0.025588 | Train loss: 0.9809 | Train acc: 51.62% | Val loss: 0.9113 | Val acc: 53.97% | LR: 0.000676
Epoch: 022 | MCC: 0.025614 | Train loss: 1.0193 | Train acc: 51.54% | Val loss: 0.9191 | Val acc: 54.28% | LR: 0.000672
Epoch: 023 | MCC: 0.029914 | Train loss: 0.9818 | Train acc: 51.57% | Val loss: 0.9126 | Val acc: 54.48% | LR: 0.000669
Epoch: 024 | MCC: 0.033323 | Train loss: 0.9809 | Train acc: 51.66% | Val loss: 0.9065 | Val acc: 55.03% | LR: 0.000665
Epoch: 025 | MCC: 0.022175 | Train loss: 0.9818 | Train acc: 51.58% | Val loss: 0.9019 | Val acc: 54.46% | LR: 0.000661
Epoch: 026 | MCC: 0.030185 | Train loss: 0.9763 | Train acc: 51.81% | Val loss: 0.9035 | Val acc: 54.73% | LR: 0.000657
Epoch: 027 | MCC: 0.041728 | Train loss: 0.9806 | Train acc: 51.64% | Val loss: 0.9018 | Val acc: 55.72% | LR: 0.000653
Epoch: 028 | MCC: 0.017659 | Train loss: 0.9777 | Train acc: 51.73% | Val loss: 0.8948 | Val acc: 56.22% | LR: 0.000649
Epoch: 029 | MCC: 0.040893 | Train loss: 0.9784 | Train acc: 51.71% | Val loss: 0.8879 | Val acc: 58.71% | LR: 0.000645
Epoch: 030 | MCC: 0.029874 | Train loss: 0.9754 | Train acc: 51.80% | Val loss: 0.9095 | Val acc: 59.29% | LR: 0.000640
Epoch: 031 | MCC: 0.056304 | Train loss: 0.9742 | Train acc: 51.61% | Val loss: 0.8795 | Val acc: 58.57% | LR: 0.000636
Epoch: 032 | MCC: 0.017281 | Train loss: 0.9733 | Train acc: 51.80% | Val loss: 0.8755 | Val acc: 58.62% | LR: 0.000631
Epoch: 033 | MCC: 0.012386 | Train loss: 0.9729 | Train acc: 51.83% | Val loss: 0.8765 | Val acc: 57.94% | LR: 0.000626
Epoch: 034 | MCC: 0.018725 | Train loss: 0.9736 | Train acc: 51.71% | Val loss: 0.8708 | Val acc: 58.70% | LR: 0.000621
Epoch: 035 | MCC: 0.032986 | Train loss: 0.9722 | Train acc: 52.03% | Val loss: 0.8708 | Val acc: 58.67% | LR: 0.000616
Epoch: 036 | MCC: 0.016949 | Train loss: 0.9767 | Train acc: 51.77% | Val loss: 0.8772 | Val acc: 60.20% | LR: 0.000611
Epoch: 037 | MCC: 0.011392 | Train loss: 0.9770 | Train acc: 51.83% | Val loss: 0.8574 | Val acc: 57.89% | LR: 0.000606
Epoch: 038 | MCC: 0.039415 | Train loss: 0.9693 | Train acc: 51.92% | Val loss: 0.8392 | Val acc: 59.96% | LR: 0.000600
Epoch: 039 | MCC: 0.044494 | Train loss: 0.9682 | Train acc: 51.95% | Val loss: 0.8793 | Val acc: 57.10% | LR: 0.000595
Epoch: 040 | MCC: 0.014074 | Train loss: 0.9705 | Train acc: 52.09% | Val loss: 0.8490 | Val acc: 58.05% | LR: 0.000589
Epoch: 041 | MCC: 0.058775 | Train loss: 0.9682 | Train acc: 51.96% | Val loss: 0.8373 | Val acc: 59.69% | LR: 0.000584
Epoch: 042 | MCC: 0.032738 | Train loss: 0.9713 | Train acc: 51.80% | Val loss: 0.8421 | Val acc: 58.57% | LR: 0.000578
Epoch: 043 | MCC: 0.035289 | Train loss: 0.9667 | Train acc: 52.04% | Val loss: 0.8360 | Val acc: 58.88% | LR: 0.000572
Epoch: 044 | MCC: 0.032001 | Train loss: 0.9661 | Train acc: 52.08% | Val loss: 0.8356 | Val acc: 58.76% | LR: 0.000566
Epoch: 045 | MCC: 0.020695 | Train loss: 0.9665 | Train acc: 52.01% | Val loss: 0.8305 | Val acc: 59.03% | LR: 0.000560
Epoch: 046 | MCC: 0.024754 | Train loss: 0.9692 | Train acc: 51.85% | Val loss: 0.8521 | Val acc: 57.60% | LR: 0.000554
Epoch: 047 | MCC: 0.017043 | Train loss: 0.9662 | Train acc: 51.98% | Val loss: 0.8759 | Val acc: 56.63% | LR: 0.000548
Epoch: 048 | MCC: 0.029798 | Train loss: 0.9652 | Train acc: 52.11% | Val loss: 0.8523 | Val acc: 57.96% | LR: 0.000541
Epoch: 049 | MCC: 0.031400 | Train loss: 0.9685 | Train acc: 51.85% | Val loss: 0.8571 | Val acc: 57.46% | LR: 0.000535
Epoch: 050 | MCC: 0.034817 | Train loss: 0.9662 | Train acc: 51.92% | Val loss: 0.8283 | Val acc: 59.18% | LR: 0.000528
Epoch: 051 | MCC: 0.037877 | Train loss: 0.9647 | Train acc: 52.06% | Val loss: 0.8308 | Val acc: 58.68% | LR: 0.000522
Epoch: 052 | MCC: 0.066379 | Train loss: 0.9659 | Train acc: 51.98% | Val loss: 0.8143 | Val acc: 59.84% | LR: 0.000515
Epoch: 053 | MCC: 0.039068 | Train loss: 0.9642 | Train acc: 52.05% | Val loss: 0.8395 | Val acc: 58.42% | LR: 0.000508
Epoch: 054 | MCC: 0.050594 | Train loss: 0.9634 | Train acc: 52.07% | Val loss: 0.8274 | Val acc: 59.05% | LR: 0.000502
Epoch: 055 | MCC: 0.027309 | Train loss: 0.9649 | Train acc: 52.03% | Val loss: 0.8738 | Val acc: 56.76% | LR: 0.000495
Epoch: 056 | MCC: 0.031511 | Train loss: 0.9690 | Train acc: 51.79% | Val loss: 0.8670 | Val acc: 57.08% | LR: 0.000488
Epoch: 057 | MCC: 0.036825 | Train loss: 0.9665 | Train acc: 51.92% | Val loss: 0.8481 | Val acc: 58.01% | LR: 0.000481
Epoch: 058 | MCC: 0.026392 | Train loss: 0.9656 | Train acc: 51.93% | Val loss: 0.8754 | Val acc: 56.49% | LR: 0.000474
Epoch: 059 | MCC: 0.024549 | Train loss: 0.9669 | Train acc: 51.88% | Val loss: 0.8581 | Val acc: 57.44% | LR: 0.000467
Epoch: 060 | MCC: 0.032422 | Train loss: 0.9658 | Train acc: 51.86% | Val loss: 0.8549 | Val acc: 57.54% | LR: 0.000460
Epoch: 061 | MCC: 0.028150 | Train loss: 0.9648 | Train acc: 52.02% | Val loss: 0.8418 | Val acc: 58.25% | LR: 0.000453
Epoch: 062 | MCC: 0.044921 | Train loss: 0.9629 | Train acc: 52.13% | Val loss: 0.8227 | Val acc: 59.69% | LR: 0.000445
Epoch: 063 | MCC: 0.038652 | Train loss: 0.9631 | Train acc: 52.04% | Val loss: 0.8329 | Val acc: 58.74% | LR: 0.000438
Epoch: 064 | MCC: 0.043210 | Train loss: 0.9630 | Train acc: 52.05% | Val loss: 0.8365 | Val acc: 58.66% | LR: 0.000431
Epoch: 065 | MCC: 0.053915 | Train loss: 0.9617 | Train acc: 52.13% | Val loss: 0.8117 | Val acc: 59.92% | LR: 0.000424
Epoch: 066 | MCC: 0.042659 | Train loss: 0.9634 | Train acc: 52.02% | Val loss: 0.8104 | Val acc: 60.08% | LR: 0.000416
Epoch: 067 | MCC: 0.032108 | Train loss: 0.9631 | Train acc: 51.96% | Val loss: 0.8613 | Val acc: 57.24% | LR: 0.000409
Epoch: 068 | MCC: 0.033837 | Train loss: 0.9636 | Train acc: 52.01% | Val loss: 0.8339 | Val acc: 58.98% | LR: 0.000401
Epoch: 069 | MCC: 0.040786 | Train loss: 0.9659 | Train acc: 51.88% | Val loss: 0.8324 | Val acc: 58.95% | LR: 0.000394
Epoch: 070 | MCC: 0.037174 | Train loss: 0.9668 | Train acc: 51.80% | Val loss: 0.8500 | Val acc: 57.81% | LR: 0.000387
Epoch: 071 | MCC: 0.032787 | Train loss: 0.9640 | Train acc: 51.95% | Val loss: 0.8301 | Val acc: 58.91% | LR: 0.000379
Epoch: 072 | MCC: 0.032200 | Train loss: 0.9645 | Train acc: 51.93% | Val loss: 0.8639 | Val acc: 57.39% | LR: 0.000372
Epoch: 073 | MCC: 0.020799 | Train loss: 0.9632 | Train acc: 52.02% | Val loss: 0.8579 | Val acc: 57.48% | LR: 0.000364
Epoch: 074 | MCC: 0.023292 | Train loss: 0.9625 | Train acc: 52.04% | Val loss: 0.8461 | Val acc: 58.03% | LR: 0.000357
Epoch: 075 | MCC: 0.034113 | Train loss: 0.9595 | Train acc: 52.23% | Val loss: 0.8268 | Val acc: 59.43% | LR: 0.000349
Epoch: 076 | MCC: 0.033404 | Train loss: 0.9659 | Train acc: 51.90% | Val loss: 0.8388 | Val acc: 58.71% | LR: 0.000342
Epoch: 077 | MCC: 0.020497 | Train loss: 0.9598 | Train acc: 52.21% | Val loss: 0.8398 | Val acc: 58.67% | LR: 0.000335
Epoch: 078 | MCC: 0.004792 | Train loss: 0.9642 | Train acc: 51.90% | Val loss: 0.8495 | Val acc: 57.83% | LR: 0.000327
Epoch: 079 | MCC: 0.014647 | Train loss: 0.9644 | Train acc: 51.93% | Val loss: 0.8468 | Val acc: 57.89% | LR: 0.000320
Epoch: 080 | MCC: 0.036161 | Train loss: 0.9619 | Train acc: 52.03% | Val loss: 0.8338 | Val acc: 58.49% | LR: 0.000312
Epoch: 081 | MCC: 0.030419 | Train loss: 0.9650 | Train acc: 51.90% | Val loss: 0.8358 | Val acc: 58.59% | LR: 0.000305
Epoch: 082 | MCC: 0.034682 | Train loss: 0.9630 | Train acc: 51.98% | Val loss: 0.8700 | Val acc: 56.45% | LR: 0.000298
Epoch: 083 | MCC: 0.043470 | Train loss: 0.9674 | Train acc: 51.78% | Val loss: 0.8409 | Val acc: 58.11% | LR: 0.000290
Epoch: 084 | MCC: 0.032173 | Train loss: 0.9618 | Train acc: 52.09% | Val loss: 0.8307 | Val acc: 58.67% | LR: 0.000283
Epoch: 085 | MCC: 0.034215 | Train loss: 0.9612 | Train acc: 52.03% | Val loss: 0.8311 | Val acc: 58.81% | LR: 0.000276
Epoch: 086 | MCC: 0.044371 | Train loss: 0.9610 | Train acc: 52.11% | Val loss: 0.8444 | Val acc: 58.31% | LR: 0.000268
Epoch: 087 | MCC: 0.028348 | Train loss: 0.9628 | Train acc: 52.00% | Val loss: 0.8455 | Val acc: 58.16% | LR: 0.000261
Epoch: 088 | MCC: 0.035903 | Train loss: 0.9616 | Train acc: 52.06% | Val loss: 0.8516 | Val acc: 57.75% | LR: 0.000254
Epoch: 089 | MCC: 0.044800 | Train loss: 0.9618 | Train acc: 52.06% | Val loss: 0.8459 | Val acc: 57.98% | LR: 0.000247
Epoch: 090 | MCC: 0.061422 | Train loss: 0.9616 | Train acc: 52.05% | Val loss: 0.8260 | Val acc: 59.22% | LR: 0.000240
Epoch: 091 | MCC: 0.067135 | Train loss: 0.9635 | Train acc: 51.94% | Val loss: 0.8263 | Val acc: 59.09% | LR: 0.000233
Epoch: 092 | MCC: 0.037818 | Train loss: 0.9615 | Train acc: 52.06% | Val loss: 0.8382 | Val acc: 58.62% | LR: 0.000226
Epoch: 093 | MCC: 0.034567 | Train loss: 0.9589 | Train acc: 52.19% | Val loss: 0.8419 | Val acc: 58.09% | LR: 0.000219
Epoch: 094 | MCC: 0.046005 | Train loss: 0.9611 | Train acc: 52.13% | Val loss: 0.8358 | Val acc: 58.60% | LR: 0.000212
Epoch: 095 | MCC: 0.042901 | Train loss: 0.9591 | Train acc: 52.19% | Val loss: 0.8429 | Val acc: 58.10% | LR: 0.000205
Epoch: 096 | MCC: 0.043932 | Train loss: 0.9593 | Train acc: 52.18% | Val loss: 0.8402 | Val acc: 58.41% | LR: 0.000199
Epoch: 097 | MCC: 0.037974 | Train loss: 0.9591 | Train acc: 52.21% | Val loss: 0.8285 | Val acc: 58.89% | LR: 0.000192
Epoch: 098 | MCC: 0.025100 | Train loss: 0.9625 | Train acc: 51.98% | Val loss: 0.8301 | Val acc: 58.90% | LR: 0.000185
Epoch: 099 | MCC: 0.031857 | Train loss: 0.9556 | Train acc: 52.37% | Val loss: 0.8286 | Val acc: 59.22% | LR: 0.000179
Epoch: 100 | MCC: 0.032804 | Train loss: 0.9602 | Train acc: 52.16% | Val loss: 0.8268 | Val acc: 58.91% | LR: 0.000173
Epoch: 101 | MCC: 0.027326 | Train loss: 0.9626 | Train acc: 52.00% | Val loss: 0.8329 | Val acc: 58.61% | LR: 0.000166
Epoch: 102 | MCC: 0.037807 | Train loss: 0.9617 | Train acc: 52.06% | Val loss: 0.8354 | Val acc: 58.68% | LR: 0.000160
Epoch: 103 | MCC: 0.027110 | Train loss: 0.9625 | Train acc: 52.02% | Val loss: 0.8329 | Val acc: 58.77% | LR: 0.000154
Epoch: 104 | MCC: 0.025090 | Train loss: 0.9582 | Train acc: 52.28% | Val loss: 0.8328 | Val acc: 58.70% | LR: 0.000148
Epoch: 105 | MCC: 0.028873 | Train loss: 0.9579 | Train acc: 52.22% | Val loss: 0.8308 | Val acc: 58.85% | LR: 0.000142
Epoch: 106 | MCC: 0.030458 | Train loss: 0.9565 | Train acc: 52.33% | Val loss: 0.8287 | Val acc: 58.89% | LR: 0.000136
Epoch: 107 | MCC: 0.032145 | Train loss: 0.9582 | Train acc: 52.24% | Val loss: 0.8283 | Val acc: 58.95% | LR: 0.000130
Epoch: 108 | MCC: 0.038486 | Train loss: 0.9578 | Train acc: 52.28% | Val loss: 0.8307 | Val acc: 59.17% | LR: 0.000124
Epoch: 109 | MCC: 0.035277 | Train loss: 0.9601 | Train acc: 52.17% | Val loss: 0.8287 | Val acc: 59.02% | LR: 0.000119
Epoch: 110 | MCC: 0.027962 | Train loss: 0.9585 | Train acc: 52.19% | Val loss: 0.8317 | Val acc: 58.76% | LR: 0.000113
Epoch: 111 | MCC: 0.028117 | Train loss: 0.9613 | Train acc: 52.09% | Val loss: 0.8334 | Val acc: 58.80% | LR: 0.000108
Epoch: 112 | MCC: 0.031191 | Train loss: 0.9579 | Train acc: 52.27% | Val loss: 0.8308 | Val acc: 58.93% | LR: 0.000103
Epoch: 113 | MCC: 0.035797 | Train loss: 0.9591 | Train acc: 52.18% | Val loss: 0.8340 | Val acc: 58.67% | LR: 0.000097
Epoch: 114 | MCC: 0.036240 | Train loss: 0.9593 | Train acc: 52.19% | Val loss: 0.8361 | Val acc: 58.74% | LR: 0.000092
Epoch: 115 | MCC: 0.033710 | Train loss: 0.9585 | Train acc: 52.20% | Val loss: 0.8430 | Val acc: 58.14% | LR: 0.000087
Epoch: 116 | MCC: 0.034378 | Train loss: 0.9599 | Train acc: 52.14% | Val loss: 0.8415 | Val acc: 58.32% | LR: 0.000083
Epoch: 117 | MCC: 0.030690 | Train loss: 0.9582 | Train acc: 52.24% | Val loss: 0.8419 | Val acc: 58.08% | LR: 0.000078
Epoch: 118 | MCC: 0.033057 | Train loss: 0.9587 | Train acc: 52.19% | Val loss: 0.8392 | Val acc: 58.55% | LR: 0.000073
Epoch: 119 | MCC: 0.032292 | Train loss: 0.9586 | Train acc: 52.21% | Val loss: 0.8406 | Val acc: 58.43% | LR: 0.000069
Epoch: 120 | MCC: 0.030410 | Train loss: 0.9607 | Train acc: 52.11% | Val loss: 0.8394 | Val acc: 58.37% | LR: 0.000065
Epoch: 121 | MCC: 0.034174 | Train loss: 0.9578 | Train acc: 52.26% | Val loss: 0.8391 | Val acc: 58.55% | LR: 0.000060
Epoch: 122 | MCC: 0.034601 | Train loss: 0.9568 | Train acc: 52.30% | Val loss: 0.8400 | Val acc: 58.52% | LR: 0.000056
Epoch: 123 | MCC: 0.032305 | Train loss: 0.9580 | Train acc: 52.22% | Val loss: 0.8378 | Val acc: 58.55% | LR: 0.000052
Epoch: 124 | MCC: 0.034418 | Train loss: 0.9585 | Train acc: 52.20% | Val loss: 0.8372 | Val acc: 58.61% | LR: 0.000049
Epoch: 125 | MCC: 0.033923 | Train loss: 0.9567 | Train acc: 52.35% | Val loss: 0.8367 | Val acc: 58.66% | LR: 0.000045
Epoch: 126 | MCC: 0.032774 | Train loss: 0.9579 | Train acc: 52.24% | Val loss: 0.8414 | Val acc: 58.39% | LR: 0.000041
Epoch: 127 | MCC: 0.027446 | Train loss: 0.9599 | Train acc: 52.12% | Val loss: 0.8445 | Val acc: 58.08% | LR: 0.000038
Epoch: 128 | MCC: 0.030717 | Train loss: 0.9574 | Train acc: 52.29% | Val loss: 0.8405 | Val acc: 58.42% | LR: 0.000035
Epoch: 129 | MCC: 0.028322 | Train loss: 0.9585 | Train acc: 52.18% | Val loss: 0.8419 | Val acc: 58.20% | LR: 0.000032
Epoch: 130 | MCC: 0.031271 | Train loss: 0.9556 | Train acc: 52.37% | Val loss: 0.8407 | Val acc: 58.37% | LR: 0.000029
Epoch: 131 | MCC: 0.032663 | Train loss: 0.9567 | Train acc: 52.32% | Val loss: 0.8395 | Val acc: 58.50% | LR: 0.000026
Epoch: 132 | MCC: 0.034717 | Train loss: 0.9592 | Train acc: 52.22% | Val loss: 0.8383 | Val acc: 58.56% | LR: 0.000023
Epoch: 133 | MCC: 0.033057 | Train loss: 0.9581 | Train acc: 52.23% | Val loss: 0.8376 | Val acc: 58.48% | LR: 0.000021
Epoch: 134 | MCC: 0.035137 | Train loss: 0.9570 | Train acc: 52.29% | Val loss: 0.8379 | Val acc: 58.59% | LR: 0.000018
Epoch: 135 | MCC: 0.034167 | Train loss: 0.9584 | Train acc: 52.21% | Val loss: 0.8376 | Val acc: 58.58% | LR: 0.000016
Epoch: 136 | MCC: 0.034167 | Train loss: 0.9557 | Train acc: 52.38% | Val loss: 0.8374 | Val acc: 58.58% | LR: 0.000014
Epoch: 137 | MCC: 0.035619 | Train loss: 0.9579 | Train acc: 52.23% | Val loss: 0.8368 | Val acc: 58.71% | LR: 0.000012
Epoch: 138 | MCC: 0.034579 | Train loss: 0.9577 | Train acc: 52.29% | Val loss: 0.8371 | Val acc: 58.63% | LR: 0.000010
Epoch: 139 | MCC: 0.034735 | Train loss: 0.9570 | Train acc: 52.29% | Val loss: 0.8370 | Val acc: 58.63% | LR: 0.000009
Epoch: 140 | MCC: 0.035679 | Train loss: 0.9548 | Train acc: 52.40% | Val loss: 0.8367 | Val acc: 58.68% | LR: 0.000007

[I 2025-10-05 10:24:39,582] Trial 52 finished with value: 0.035754027136135846 and parameters: {'lr': 0.0007127102566384445, 'hidden_size': 77, 'dropout': 0.11667903192569347, 'weight_decay': 0.018825973360911127}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.010086 | Train loss: 0.9987 | Train acc: 50.68% | Val loss: 1.0092 | Val acc: 45.32% | LR: 0.000312
Epoch: 001 | MCC: 0.014284 | Train loss: 1.0091 | Train acc: 50.45% | Val loss: 1.0119 | Val acc: 45.35% | LR: 0.000312
Epoch: 002 | MCC: 0.031389 | Train loss: 0.9976 | Train acc: 50.60% | Val loss: 1.0083 | Val acc: 45.51% | LR: 0.000312
Epoch: 003 | MCC: 0.021954 | Train loss: 0.9961 | Train acc: 50.71% | Val loss: 1.0068 | Val acc: 45.49% | LR: 0.000312
Epoch: 004 | MCC: 0.015076 | Train loss: 0.9946 | Train acc: 50.79% | Val loss: 1.0118 | Val acc: 45.55% | LR: 0.000312
Epoch: 005 | MCC: 0.016810 | Train loss: 0.9944 | Train acc: 50.59% | Val loss: 1.0073 | Val acc: 45.42% | LR: 0.000311
Epoch: 006 | MCC: -0.006671 | Train loss: 0.9937 | Train acc: 50.65% | Val loss: 1.0049 | Val acc: 45.40% | LR: 0.000311
Epoch: 007 | MCC: 0.009435 | Train loss: 0.9928 | Train acc: 50.60% | Val loss: 1.0058 | Val acc: 45.33% | LR: 0.000310
Epoch: 008 | MCC: 0.004772 | Train loss: 0.9898 | Train acc: 50.64% | Val loss: 1.0037 | Val acc: 45.12% | LR: 0.000310
Epoch: 009 | MCC: 0.048060 | Train loss: 0.9886 | Train acc: 50.70% | Val loss: 1.0658 | Val acc: 46.32% | LR: 0.000309
Epoch: 010 | MCC: 0.055516 | Train loss: 0.9893 | Train acc: 50.67% | Val loss: 1.0036 | Val acc: 47.97% | LR: 0.000308
Epoch: 011 | MCC: 0.051525 | Train loss: 0.9916 | Train acc: 50.60% | Val loss: 1.0027 | Val acc: 48.34% | LR: 0.000307
Epoch: 012 | MCC: 0.052806 | Train loss: 0.9880 | Train acc: 50.82% | Val loss: 1.0046 | Val acc: 48.83% | LR: 0.000307
Epoch: 013 | MCC: 0.071343 | Train loss: 0.9885 | Train acc: 50.64% | Val loss: 0.9999 | Val acc: 48.82% | LR: 0.000306
Epoch: 014 | MCC: 0.055305 | Train loss: 0.9871 | Train acc: 50.73% | Val loss: 0.9992 | Val acc: 49.34% | LR: 0.000305
Epoch: 015 | MCC: 0.055231 | Train loss: 0.9882 | Train acc: 50.54% | Val loss: 1.0008 | Val acc: 49.74% | LR: 0.000304
Epoch: 016 | MCC: 0.044351 | Train loss: 0.9877 | Train acc: 50.59% | Val loss: 0.9990 | Val acc: 50.03% | LR: 0.000303
Epoch: 017 | MCC: 0.042745 | Train loss: 0.9872 | Train acc: 50.59% | Val loss: 0.9983 | Val acc: 50.10% | LR: 0.000301
Epoch: 018 | MCC: 0.044032 | Train loss: 0.9871 | Train acc: 50.65% | Val loss: 0.9976 | Val acc: 51.04% | LR: 0.000300
Epoch: 019 | MCC: 0.039165 | Train loss: 0.9887 | Train acc: 50.78% | Val loss: 0.9945 | Val acc: 51.68% | LR: 0.000299
Epoch: 020 | MCC: 0.039902 | Train loss: 0.9871 | Train acc: 50.80% | Val loss: 0.9899 | Val acc: 52.57% | LR: 0.000298
Epoch: 021 | MCC: 0.038211 | Train loss: 0.9851 | Train acc: 50.84% | Val loss: 0.9852 | Val acc: 53.09% | LR: 0.000296
Epoch: 022 | MCC: 0.037134 | Train loss: 0.9860 | Train acc: 50.86% | Val loss: 0.9807 | Val acc: 54.02% | LR: 0.000295
Epoch: 023 | MCC: 0.043875 | Train loss: 0.9832 | Train acc: 51.08% | Val loss: 1.1042 | Val acc: 54.40% | LR: 0.000293
Epoch: 024 | MCC: 0.042025 | Train loss: 0.9821 | Train acc: 51.08% | Val loss: 0.9776 | Val acc: 54.57% | LR: 0.000292
Epoch: 025 | MCC: 0.042626 | Train loss: 0.9854 | Train acc: 50.89% | Val loss: 0.9721 | Val acc: 54.80% | LR: 0.000290
Epoch: 026 | MCC: 0.045541 | Train loss: 0.9818 | Train acc: 51.12% | Val loss: 0.9654 | Val acc: 54.99% | LR: 0.000288
Epoch: 027 | MCC: 0.043203 | Train loss: 0.9833 | Train acc: 51.02% | Val loss: 0.9603 | Val acc: 55.00% | LR: 0.000286
Epoch: 028 | MCC: 0.039227 | Train loss: 0.9841 | Train acc: 50.87% | Val loss: 0.9836 | Val acc: 54.96% | LR: 0.000285
Epoch: 029 | MCC: 0.038521 | Train loss: 0.9815 | Train acc: 51.02% | Val loss: 0.9548 | Val acc: 55.12% | LR: 0.000283
Epoch: 030 | MCC: 0.038364 | Train loss: 0.9818 | Train acc: 51.01% | Val loss: 0.9605 | Val acc: 55.65% | LR: 0.000281
Epoch: 031 | MCC: 0.039073 | Train loss: 0.9815 | Train acc: 50.98% | Val loss: 0.9519 | Val acc: 55.82% | LR: 0.000279
Epoch: 032 | MCC: 0.036227 | Train loss: 0.9824 | Train acc: 50.85% | Val loss: 0.9473 | Val acc: 55.99% | LR: 0.000277
Epoch: 033 | MCC: 0.040272 | Train loss: 0.9821 | Train acc: 50.87% | Val loss: 1.2068 | Val acc: 56.34% | LR: 0.000275
Epoch: 034 | MCC: 0.045018 | Train loss: 0.9817 | Train acc: 50.85% | Val loss: 0.9354 | Val acc: 56.58% | LR: 0.000272
Epoch: 035 | MCC: 0.044398 | Train loss: 0.9815 | Train acc: 50.94% | Val loss: 0.9315 | Val acc: 56.61% | LR: 0.000270
Epoch: 036 | MCC: 0.026288 | Train loss: 0.9808 | Train acc: 50.91% | Val loss: 0.9266 | Val acc: 56.06% | LR: 0.000268
Epoch: 037 | MCC: 0.036338 | Train loss: 0.9835 | Train acc: 50.77% | Val loss: 0.9240 | Val acc: 56.56% | LR: 0.000266
Epoch: 038 | MCC: 0.022434 | Train loss: 0.9814 | Train acc: 50.88% | Val loss: 0.9249 | Val acc: 56.24% | LR: 0.000263
Epoch: 039 | MCC: 0.024777 | Train loss: 0.9797 | Train acc: 50.95% | Val loss: 0.9183 | Val acc: 56.42% | LR: 0.000261
Epoch: 040 | MCC: 0.024128 | Train loss: 0.9793 | Train acc: 51.00% | Val loss: 0.9141 | Val acc: 56.40% | LR: 0.000258
Epoch: 041 | MCC: 0.020582 | Train loss: 0.9802 | Train acc: 50.88% | Val loss: 0.9083 | Val acc: 56.42% | LR: 0.000256
Epoch: 042 | MCC: 0.019834 | Train loss: 0.9801 | Train acc: 50.85% | Val loss: 0.9055 | Val acc: 56.54% | LR: 0.000253
Epoch: 043 | MCC: 0.018047 | Train loss: 0.9791 | Train acc: 50.99% | Val loss: 0.9049 | Val acc: 56.91% | LR: 0.000251
Epoch: 044 | MCC: 0.027570 | Train loss: 0.9792 | Train acc: 51.01% | Val loss: 0.9005 | Val acc: 57.48% | LR: 0.000248
Epoch: 045 | MCC: 0.037828 | Train loss: 0.9801 | Train acc: 50.97% | Val loss: 0.8942 | Val acc: 57.97% | LR: 0.000246
Epoch: 046 | MCC: 0.042473 | Train loss: 0.9793 | Train acc: 51.06% | Val loss: 0.8893 | Val acc: 58.10% | LR: 0.000243
Epoch: 047 | MCC: 0.030096 | Train loss: 0.9775 | Train acc: 51.16% | Val loss: 0.8851 | Val acc: 58.06% | LR: 0.000240
Epoch: 048 | MCC: 0.026558 | Train loss: 0.9770 | Train acc: 51.20% | Val loss: 0.8784 | Val acc: 57.74% | LR: 0.000237
Epoch: 049 | MCC: 0.037100 | Train loss: 0.9765 | Train acc: 51.17% | Val loss: 0.8773 | Val acc: 57.90% | LR: 0.000235
Epoch: 050 | MCC: -0.002073 | Train loss: 0.9771 | Train acc: 51.11% | Val loss: 0.8718 | Val acc: 56.92% | LR: 0.000232
Epoch: 051 | MCC: -0.005365 | Train loss: 0.9754 | Train acc: 51.33% | Val loss: 0.8683 | Val acc: 56.86% | LR: 0.000229
Epoch: 052 | MCC: -0.002915 | Train loss: 0.9760 | Train acc: 51.25% | Val loss: 0.8618 | Val acc: 57.22% | LR: 0.000226
Epoch: 053 | MCC: -0.006376 | Train loss: 0.9745 | Train acc: 51.25% | Val loss: 0.8608 | Val acc: 57.32% | LR: 0.000223
Epoch: 054 | MCC: 0.018296 | Train loss: 0.9716 | Train acc: 51.42% | Val loss: 0.8544 | Val acc: 58.13% | LR: 0.000220
Epoch: 055 | MCC: 0.020923 | Train loss: 0.9722 | Train acc: 51.33% | Val loss: 0.8565 | Val acc: 58.05% | LR: 0.000217
Epoch: 056 | MCC: 0.024739 | Train loss: 0.9718 | Train acc: 51.43% | Val loss: 0.8663 | Val acc: 57.25% | LR: 0.000214
Epoch: 057 | MCC: 0.005650 | Train loss: 0.9708 | Train acc: 51.37% | Val loss: 0.8584 | Val acc: 57.27% | LR: 0.000211
Epoch: 058 | MCC: 0.003718 | Train loss: 0.9722 | Train acc: 51.29% | Val loss: 0.8609 | Val acc: 57.25% | LR: 0.000208
Epoch: 059 | MCC: 0.018957 | Train loss: 0.9709 | Train acc: 51.46% | Val loss: 0.8555 | Val acc: 57.66% | LR: 0.000205
Epoch: 060 | MCC: 0.017702 | Train loss: 0.9728 | Train acc: 51.37% | Val loss: 0.8429 | Val acc: 58.32% | LR: 0.000202
Epoch: 061 | MCC: 0.023513 | Train loss: 0.9705 | Train acc: 51.50% | Val loss: 0.8460 | Val acc: 58.25% | LR: 0.000199
Epoch: 062 | MCC: 0.034391 | Train loss: 0.9690 | Train acc: 51.51% | Val loss: 0.8460 | Val acc: 58.22% | LR: 0.000195
Epoch: 063 | MCC: 0.037041 | Train loss: 0.9712 | Train acc: 51.35% | Val loss: 0.8532 | Val acc: 57.80% | LR: 0.000192
Epoch: 064 | MCC: 0.036821 | Train loss: 0.9718 | Train acc: 51.33% | Val loss: 0.8438 | Val acc: 58.22% | LR: 0.000189
Epoch: 065 | MCC: 0.022354 | Train loss: 0.9703 | Train acc: 51.46% | Val loss: 0.8348 | Val acc: 58.69% | LR: 0.000186
Epoch: 066 | MCC: 0.022064 | Train loss: 0.9689 | Train acc: 51.41% | Val loss: 0.8569 | Val acc: 57.42% | LR: 0.000183
Epoch: 067 | MCC: 0.026111 | Train loss: 0.9704 | Train acc: 51.56% | Val loss: 0.8172 | Val acc: 59.59% | LR: 0.000179
Epoch: 068 | MCC: 0.014687 | Train loss: 0.9687 | Train acc: 51.48% | Val loss: 0.8462 | Val acc: 57.84% | LR: 0.000176
Epoch: 069 | MCC: 0.014313 | Train loss: 0.9766 | Train acc: 51.30% | Val loss: 0.8550 | Val acc: 57.62% | LR: 0.000173
Epoch: 070 | MCC: 0.018996 | Train loss: 0.9723 | Train acc: 51.33% | Val loss: 0.8454 | Val acc: 58.13% | LR: 0.000170
Epoch: 071 | MCC: 0.025091 | Train loss: 0.9695 | Train acc: 51.41% | Val loss: 0.8459 | Val acc: 58.10% | LR: 0.000166
Epoch: 072 | MCC: 0.033235 | Train loss: 0.9685 | Train acc: 51.43% | Val loss: 0.8418 | Val acc: 58.20% | LR: 0.000163
Epoch: 073 | MCC: 0.027666 | Train loss: 0.9699 | Train acc: 51.38% | Val loss: 0.8399 | Val acc: 58.25% | LR: 0.000160
Epoch: 074 | MCC: 0.031251 | Train loss: 0.9690 | Train acc: 51.42% | Val loss: 0.8402 | Val acc: 58.32% | LR: 0.000157
Epoch: 075 | MCC: 0.029438 | Train loss: 0.9699 | Train acc: 51.40% | Val loss: 0.8224 | Val acc: 59.32% | LR: 0.000153
Epoch: 076 | MCC: 0.038261 | Train loss: 0.9689 | Train acc: 51.45% | Val loss: 0.8476 | Val acc: 57.93% | LR: 0.000150
Epoch: 077 | MCC: 0.022236 | Train loss: 0.9697 | Train acc: 51.37% | Val loss: 0.8342 | Val acc: 58.35% | LR: 0.000147
Epoch: 078 | MCC: 0.024166 | Train loss: 0.9710 | Train acc: 51.39% | Val loss: 0.8197 | Val acc: 59.30% | LR: 0.000144
Epoch: 079 | MCC: 0.028953 | Train loss: 0.9693 | Train acc: 51.44% | Val loss: 0.8290 | Val acc: 58.71% | LR: 0.000140
Epoch: 080 | MCC: 0.034364 | Train loss: 0.9680 | Train acc: 51.47% | Val loss: 0.8214 | Val acc: 59.23% | LR: 0.000137
Epoch: 081 | MCC: 0.032137 | Train loss: 0.9697 | Train acc: 51.43% | Val loss: 0.8328 | Val acc: 58.44% | LR: 0.000134
Epoch: 082 | MCC: 0.030987 | Train loss: 0.9691 | Train acc: 51.37% | Val loss: 0.8304 | Val acc: 58.65% | LR: 0.000131
Epoch: 083 | MCC: 0.028779 | Train loss: 0.9693 | Train acc: 51.41% | Val loss: 0.8322 | Val acc: 58.42% | LR: 0.000128
Epoch: 084 | MCC: 0.022015 | Train loss: 0.9684 | Train acc: 51.41% | Val loss: 0.8363 | Val acc: 58.27% | LR: 0.000124
Epoch: 085 | MCC: 0.019379 | Train loss: 0.9665 | Train acc: 51.55% | Val loss: 0.8354 | Val acc: 58.27% | LR: 0.000121
Epoch: 086 | MCC: 0.020885 | Train loss: 0.9675 | Train acc: 51.54% | Val loss: 0.8302 | Val acc: 58.57% | LR: 0.000118
Epoch: 087 | MCC: 0.028127 | Train loss: 0.9692 | Train acc: 51.47% | Val loss: 0.8273 | Val acc: 58.79% | LR: 0.000115
Epoch: 088 | MCC: 0.026279 | Train loss: 0.9677 | Train acc: 51.41% | Val loss: 0.8406 | Val acc: 58.13% | LR: 0.000112
Epoch: 089 | MCC: 0.036278 | Train loss: 0.9674 | Train acc: 51.40% | Val loss: 0.8218 | Val acc: 59.30% | LR: 0.000109
Epoch: 090 | MCC: 0.023632 | Train loss: 0.9670 | Train acc: 51.57% | Val loss: 0.8295 | Val acc: 58.62% | LR: 0.000105
Epoch: 091 | MCC: 0.024534 | Train loss: 0.9668 | Train acc: 51.48% | Val loss: 0.8298 | Val acc: 58.66% | LR: 0.000102
Epoch: 092 | MCC: 0.025318 | Train loss: 0.9668 | Train acc: 51.50% | Val loss: 0.8406 | Val acc: 58.10% | LR: 0.000099
Epoch: 093 | MCC: 0.029318 | Train loss: 0.9674 | Train acc: 51.60% | Val loss: 0.8238 | Val acc: 59.03% | LR: 0.000096
Epoch: 094 | MCC: 0.023368 | Train loss: 0.9685 | Train acc: 51.46% | Val loss: 0.8331 | Val acc: 58.47% | LR: 0.000093
Epoch: 095 | MCC: 0.024003 | Train loss: 0.9659 | Train acc: 51.58% | Val loss: 0.8366 | Val acc: 58.37% | LR: 0.000090
Epoch: 096 | MCC: 0.022155 | Train loss: 0.9670 | Train acc: 51.61% | Val loss: 0.8210 | Val acc: 59.07% | LR: 0.000087
Epoch: 097 | MCC: 0.034917 | Train loss: 0.9681 | Train acc: 51.43% | Val loss: 0.8189 | Val acc: 59.32% | LR: 0.000085
Epoch: 098 | MCC: 0.029116 | Train loss: 0.9665 | Train acc: 51.55% | Val loss: 0.8278 | Val acc: 58.71% | LR: 0.000082
Epoch: 099 | MCC: 0.037078 | Train loss: 0.9666 | Train acc: 51.48% | Val loss: 0.8300 | Val acc: 58.79% | LR: 0.000079
Epoch: 100 | MCC: 0.028983 | Train loss: 0.9657 | Train acc: 51.66% | Val loss: 0.8276 | Val acc: 58.69% | LR: 0.000076
Epoch: 101 | MCC: 0.029735 | Train loss: 0.9651 | Train acc: 51.62% | Val loss: 0.8292 | Val acc: 58.64% | LR: 0.000073
Epoch: 102 | MCC: 0.032256 | Train loss: 0.9645 | Train acc: 51.69% | Val loss: 0.8308 | Val acc: 58.64% | LR: 0.000071
Epoch: 103 | MCC: 0.032262 | Train loss: 0.9661 | Train acc: 51.59% | Val loss: 0.8294 | Val acc: 58.69% | LR: 0.000068
Epoch: 104 | MCC: 0.029247 | Train loss: 0.9647 | Train acc: 51.66% | Val loss: 0.8280 | Val acc: 58.74% | LR: 0.000065
Epoch: 105 | MCC: 0.034498 | Train loss: 0.9656 | Train acc: 51.52% | Val loss: 0.8328 | Val acc: 58.64% | LR: 0.000063
Epoch: 106 | MCC: 0.032873 | Train loss: 0.9651 | Train acc: 51.57% | Val loss: 0.8381 | Val acc: 58.32% | LR: 0.000060
Epoch: 107 | MCC: 0.030393 | Train loss: 0.9665 | Train acc: 51.47% | Val loss: 0.8292 | Val acc: 58.62% | LR: 0.000057
Epoch: 108 | MCC: 0.032267 | Train loss: 0.9660 | Train acc: 51.43% | Val loss: 0.8300 | Val acc: 58.64% | LR: 0.000055
Epoch: 109 | MCC: 0.034457 | Train loss: 0.9635 | Train acc: 51.68% | Val loss: 0.8349 | Val acc: 58.42% | LR: 0.000053
Epoch: 110 | MCC: 0.033949 | Train loss: 0.9661 | Train acc: 51.53% | Val loss: 0.8311 | Val acc: 58.62% | LR: 0.000050
Epoch: 111 | MCC: 0.034882 | Train loss: 0.9658 | Train acc: 51.53% | Val loss: 0.8331 | Val acc: 58.52% | LR: 0.000048
Epoch: 112 | MCC: 0.028480 | Train loss: 0.9656 | Train acc: 51.46% | Val loss: 0.8298 | Val acc: 58.59% | LR: 0.000045
Epoch: 113 | MCC: 0.033575 | Train loss: 0.9643 | Train acc: 51.68% | Val loss: 0.8323 | Val acc: 58.52% | LR: 0.000043
Epoch: 114 | MCC: 0.030423 | Train loss: 0.9641 | Train acc: 51.66% | Val loss: 0.8302 | Val acc: 58.57% | LR: 0.000041
Epoch: 115 | MCC: 0.035347 | Train loss: 0.9639 | Train acc: 51.58% | Val loss: 0.8332 | Val acc: 58.57% | LR: 0.000039
Epoch: 116 | MCC: 0.032210 | Train loss: 0.9644 | Train acc: 51.82% | Val loss: 0.8288 | Val acc: 58.69% | LR: 0.000037
Epoch: 117 | MCC: 0.035287 | Train loss: 0.9640 | Train acc: 51.54% | Val loss: 0.8329 | Val acc: 58.59% | LR: 0.000035
Epoch: 118 | MCC: 0.033252 | Train loss: 0.9627 | Train acc: 52.02% | Val loss: 0.8312 | Val acc: 58.62% | LR: 0.000033
Epoch: 119 | MCC: 0.034297 | Train loss: 0.9658 | Train acc: 51.44% | Val loss: 0.8319 | Val acc: 58.52% | LR: 0.000031
Epoch: 120 | MCC: 0.034996 | Train loss: 0.9644 | Train acc: 51.51% | Val loss: 0.8321 | Val acc: 58.57% | LR: 0.000029
Epoch: 121 | MCC: 0.034621 | Train loss: 0.9632 | Train acc: 51.93% | Val loss: 0.8303 | Val acc: 58.66% | LR: 0.000027
Epoch: 122 | MCC: 0.034582 | Train loss: 0.9629 | Train acc: 52.19% | Val loss: 0.8339 | Val acc: 58.52% | LR: 0.000025
Epoch: 123 | MCC: 0.034386 | Train loss: 0.9638 | Train acc: 52.43% | Val loss: 0.8322 | Val acc: 58.54% | LR: 0.000024
Epoch: 124 | MCC: 0.035691 | Train loss: 0.9639 | Train acc: 51.84% | Val loss: 0.8315 | Val acc: 58.62% | LR: 0.000022
Epoch: 125 | MCC: 0.035542 | Train loss: 0.9639 | Train acc: 52.23% | Val loss: 0.8325 | Val acc: 58.59% | LR: 0.000020
Epoch: 126 | MCC: 0.034996 | Train loss: 0.9628 | Train acc: 52.35% | Val loss: 0.8323 | Val acc: 58.57% | LR: 0.000019
Epoch: 127 | MCC: 0.034386 | Train loss: 0.9624 | Train acc: 52.36% | Val loss: 0.8324 | Val acc: 58.54% | LR: 0.000017
Epoch: 128 | MCC: 0.035981 | Train loss: 0.9638 | Train acc: 52.24% | Val loss: 0.8318 | Val acc: 58.62% | LR: 0.000016
Epoch: 129 | MCC: 0.035631 | Train loss: 0.9642 | Train acc: 52.31% | Val loss: 0.8314 | Val acc: 58.62% | LR: 0.000014
Epoch: 130 | MCC: 0.034856 | Train loss: 0.9625 | Train acc: 52.44% | Val loss: 0.8319 | Val acc: 58.59% | LR: 0.000013
Epoch: 131 | MCC: 0.035378 | Train loss: 0.9635 | Train acc: 52.34% | Val loss: 0.8318 | Val acc: 58.62% | LR: 0.000012
Epoch: 132 | MCC: 0.035721 | Train loss: 0.9633 | Train acc: 52.34% | Val loss: 0.8319 | Val acc: 58.64% | LR: 0.000011
Epoch: 133 | MCC: 0.034676 | Train loss: 0.9630 | Train acc: 52.34% | Val loss: 0.8320 | Val acc: 58.54% | LR: 0.000010
Epoch: 134 | MCC: 0.035055 | Train loss: 0.9631 | Train acc: 52.53% | Val loss: 0.8320 | Val acc: 58.57% | LR: 0.000009
Epoch: 135 | MCC: 0.034765 | Train loss: 0.9636 | Train acc: 52.29% | Val loss: 0.8321 | Val acc: 58.57% | LR: 0.000008
Epoch: 136 | MCC: 0.035721 | Train loss: 0.9631 | Train acc: 52.36% | Val loss: 0.8316 | Val acc: 58.64% | LR: 0.000007
Epoch: 137 | MCC: 0.034617 | Train loss: 0.9632 | Train acc: 52.34% | Val loss: 0.8325 | Val acc: 58.54% | LR: 0.000006
Epoch: 138 | MCC: 0.035721 | Train loss: 0.9639 | Train acc: 52.26% | Val loss: 0.8317 | Val acc: 58.64% | LR: 0.000005
Epoch: 139 | MCC: 0.034676 | Train loss: 0.9634 | Train acc: 52.32% | Val loss: 0.8325 | Val acc: 58.54% | LR: 0.000004
Epoch: 140 | MCC: 0.034676 | Train loss: 0.9629 | Train acc: 52.32% | Val loss: 0.8324 | Val acc: 58.54% | LR: 0.000004
Epoch: 141 | MCC: 0.035721 | Train loss: 0.9638 | Train acc: 52.22% | Val loss: 0.8319 | Val acc: 58.64% | LR: 0.000003

[I 2025-10-05 10:26:50,989] Trial 53 finished with value: 0.035055072978138924 and parameters: {'lr': 0.00031236200339872374, 'hidden_size': 84, 'dropout': 0.1650858408887213, 'weight_decay': 0.004523789720476374}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.015923 | Train loss: 0.9965 | Train acc: 50.33% | Val loss: 0.9930 | Val acc: 53.73% | LR: 0.002702
Epoch: 001 | MCC: 0.000348 | Train loss: 0.9908 | Train acc: 50.87% | Val loss: 0.9963 | Val acc: 54.61% | LR: 0.002701
Epoch: 002 | MCC: -0.007116 | Train loss: 0.9919 | Train acc: 50.89% | Val loss: 0.9252 | Val acc: 54.55% | LR: 0.002699
Epoch: 003 | MCC: -0.002030 | Train loss: 0.9876 | Train acc: 50.82% | Val loss: 0.9703 | Val acc: 54.77% | LR: 0.002697
Epoch: 004 | MCC: -0.018234 | Train loss: 0.9855 | Train acc: 51.06% | Val loss: 0.9478 | Val acc: 54.96% | LR: 0.002695
Epoch: 005 | MCC: -0.002102 | Train loss: 0.9853 | Train acc: 50.97% | Val loss: 0.9278 | Val acc: 54.64% | LR: 0.002692
Epoch: 006 | MCC: 0.008160 | Train loss: 0.9860 | Train acc: 51.10% | Val loss: 0.9524 | Val acc: 53.84% | LR: 0.002688
Epoch: 007 | MCC: 0.020874 | Train loss: 0.9880 | Train acc: 51.10% | Val loss: 0.9510 | Val acc: 54.10% | LR: 0.002683
Epoch: 008 | MCC: 0.023077 | Train loss: 0.9827 | Train acc: 50.76% | Val loss: 0.9792 | Val acc: 53.46% | LR: 0.002678
Epoch: 009 | MCC: 0.031856 | Train loss: 0.9843 | Train acc: 50.85% | Val loss: 0.9173 | Val acc: 55.15% | LR: 0.002673
Epoch: 010 | MCC: 0.002360 | Train loss: 0.9820 | Train acc: 51.58% | Val loss: 0.9432 | Val acc: 54.89% | LR: 0.002666
Epoch: 011 | MCC: 0.010503 | Train loss: 0.9826 | Train acc: 51.34% | Val loss: 0.9568 | Val acc: 55.07% | LR: 0.002660
Epoch: 012 | MCC: -0.001335 | Train loss: 0.9842 | Train acc: 51.48% | Val loss: 0.9488 | Val acc: 54.02% | LR: 0.002652
Epoch: 013 | MCC: 0.012336 | Train loss: 0.9822 | Train acc: 51.50% | Val loss: 1.0759 | Val acc: 54.03% | LR: 0.002645
Epoch: 014 | MCC: 0.033186 | Train loss: 0.9813 | Train acc: 51.59% | Val loss: 0.9372 | Val acc: 54.47% | LR: 0.002636
Epoch: 015 | MCC: 0.016595 | Train loss: 0.9781 | Train acc: 51.67% | Val loss: 0.9388 | Val acc: 53.42% | LR: 0.002627
Epoch: 016 | MCC: 0.037001 | Train loss: 0.9806 | Train acc: 51.52% | Val loss: 0.9513 | Val acc: 53.61% | LR: 0.002617
Epoch: 017 | MCC: -0.004518 | Train loss: 0.9852 | Train acc: 51.52% | Val loss: 1.0038 | Val acc: 52.13% | LR: 0.002607
Epoch: 018 | MCC: 0.049444 | Train loss: 0.9827 | Train acc: 51.53% | Val loss: 0.9453 | Val acc: 54.95% | LR: 0.002597
Epoch: 019 | MCC: 0.041559 | Train loss: 0.9839 | Train acc: 51.57% | Val loss: 0.9880 | Val acc: 53.80% | LR: 0.002585
Epoch: 020 | MCC: 0.033614 | Train loss: 0.9824 | Train acc: 51.56% | Val loss: 0.9508 | Val acc: 54.09% | LR: 0.002574
Epoch: 021 | MCC: 0.026722 | Train loss: 0.9813 | Train acc: 51.53% | Val loss: 0.9505 | Val acc: 54.04% | LR: 0.002561
Epoch: 022 | MCC: 0.028799 | Train loss: 0.9751 | Train acc: 51.56% | Val loss: 0.9439 | Val acc: 54.22% | LR: 0.002548
Epoch: 023 | MCC: 0.015275 | Train loss: 0.9770 | Train acc: 51.57% | Val loss: 0.9367 | Val acc: 53.75% | LR: 0.002535
Epoch: 024 | MCC: 0.006163 | Train loss: 0.9783 | Train acc: 51.57% | Val loss: 0.9602 | Val acc: 53.16% | LR: 0.002521
Epoch: 025 | MCC: 0.007429 | Train loss: 0.9808 | Train acc: 51.61% | Val loss: 0.9679 | Val acc: 53.73% | LR: 0.002507
Epoch: 026 | MCC: 0.003407 | Train loss: 0.9794 | Train acc: 51.52% | Val loss: 0.9459 | Val acc: 53.65% | LR: 0.002492
Epoch: 027 | MCC: -0.005754 | Train loss: 0.9756 | Train acc: 51.71% | Val loss: 0.9473 | Val acc: 55.50% | LR: 0.002477
Epoch: 028 | MCC: 0.026848 | Train loss: 0.9777 | Train acc: 51.80% | Val loss: 0.9924 | Val acc: 53.28% | LR: 0.002461
Epoch: 029 | MCC: 0.018000 | Train loss: 0.9819 | Train acc: 51.27% | Val loss: 1.0506 | Val acc: 45.37% | LR: 0.002444
Epoch: 030 | MCC: 0.028298 | Train loss: 0.9765 | Train acc: 51.55% | Val loss: 0.9373 | Val acc: 54.42% | LR: 0.002427
Epoch: 031 | MCC: 0.010570 | Train loss: 0.9746 | Train acc: 51.58% | Val loss: 0.9662 | Val acc: 54.74% | LR: 0.002410
Epoch: 032 | MCC: 0.021949 | Train loss: 0.9766 | Train acc: 51.24% | Val loss: 0.9434 | Val acc: 54.89% | LR: 0.002392
Epoch: 033 | MCC: 0.015381 | Train loss: 0.9754 | Train acc: 51.57% | Val loss: 0.9214 | Val acc: 54.79% | LR: 0.002374
Epoch: 034 | MCC: 0.012341 | Train loss: 0.9727 | Train acc: 51.68% | Val loss: 0.9160 | Val acc: 54.94% | LR: 0.002355
Epoch: 035 | MCC: 0.026744 | Train loss: 0.9733 | Train acc: 51.74% | Val loss: 0.9599 | Val acc: 55.20% | LR: 0.002336
Epoch: 036 | MCC: 0.008102 | Train loss: 0.9729 | Train acc: 51.78% | Val loss: 0.9145 | Val acc: 54.94% | LR: 0.002317
Epoch: 037 | MCC: 0.019981 | Train loss: 0.9727 | Train acc: 51.58% | Val loss: 0.9447 | Val acc: 55.26% | LR: 0.002297
Epoch: 038 | MCC: 0.026429 | Train loss: 0.9736 | Train acc: 51.81% | Val loss: 0.9464 | Val acc: 54.96% | LR: 0.002276
Epoch: 039 | MCC: 0.016404 | Train loss: 0.9746 | Train acc: 51.69% | Val loss: 0.9140 | Val acc: 55.32% | LR: 0.002255
Epoch: 040 | MCC: 0.017299 | Train loss: 0.9766 | Train acc: 51.81% | Val loss: 0.9659 | Val acc: 54.74% | LR: 0.002234
Epoch: 041 | MCC: 0.016866 | Train loss: 0.9745 | Train acc: 51.81% | Val loss: 0.9559 | Val acc: 54.06% | LR: 0.002212
Epoch: 042 | MCC: 0.008426 | Train loss: 0.9753 | Train acc: 51.81% | Val loss: 0.9591 | Val acc: 54.14% | LR: 0.002190
Epoch: 043 | MCC: -0.010894 | Train loss: 0.9731 | Train acc: 51.80% | Val loss: 0.9774 | Val acc: 52.86% | LR: 0.002168
Epoch: 044 | MCC: 0.011465 | Train loss: 0.9736 | Train acc: 51.84% | Val loss: 0.9710 | Val acc: 54.50% | LR: 0.002145
Epoch: 045 | MCC: 0.011002 | Train loss: 0.9691 | Train acc: 52.00% | Val loss: 0.9097 | Val acc: 55.61% | LR: 0.002122
Epoch: 046 | MCC: 0.004869 | Train loss: 0.9679 | Train acc: 52.20% | Val loss: 0.9426 | Val acc: 54.53% | LR: 0.002099
Epoch: 047 | MCC: -0.000782 | Train loss: 0.9692 | Train acc: 51.77% | Val loss: 0.9878 | Val acc: 49.58% | LR: 0.002075
Epoch: 048 | MCC: 0.008381 | Train loss: 0.9644 | Train acc: 52.26% | Val loss: 0.9212 | Val acc: 55.94% | LR: 0.002051
Epoch: 049 | MCC: 0.015750 | Train loss: 0.9657 | Train acc: 52.21% | Val loss: 0.9153 | Val acc: 56.24% | LR: 0.002027
Epoch: 050 | MCC: 0.023316 | Train loss: 0.9642 | Train acc: 52.17% | Val loss: 0.9128 | Val acc: 56.59% | LR: 0.002002
Epoch: 051 | MCC: 0.026563 | Train loss: 0.9625 | Train acc: 52.29% | Val loss: 0.9270 | Val acc: 56.35% | LR: 0.001977
Epoch: 052 | MCC: 0.009215 | Train loss: 0.9639 | Train acc: 52.22% | Val loss: 0.9136 | Val acc: 56.12% | LR: 0.001952
Epoch: 053 | MCC: 0.042398 | Train loss: 0.9618 | Train acc: 52.32% | Val loss: 0.9138 | Val acc: 56.60% | LR: 0.001927
Epoch: 054 | MCC: 0.036837 | Train loss: 0.9604 | Train acc: 52.25% | Val loss: 0.9029 | Val acc: 56.91% | LR: 0.001901
Epoch: 055 | MCC: 0.023227 | Train loss: 0.9570 | Train acc: 52.54% | Val loss: 0.8961 | Val acc: 56.67% | LR: 0.001875
Epoch: 056 | MCC: 0.022665 | Train loss: 0.9629 | Train acc: 52.20% | Val loss: 0.9033 | Val acc: 56.97% | LR: 0.001849
Epoch: 057 | MCC: 0.032263 | Train loss: 0.9611 | Train acc: 52.30% | Val loss: 0.9172 | Val acc: 56.90% | LR: 0.001822
Epoch: 058 | MCC: 0.041409 | Train loss: 0.9609 | Train acc: 52.36% | Val loss: 0.8945 | Val acc: 56.83% | LR: 0.001796
Epoch: 059 | MCC: 0.028471 | Train loss: 0.9574 | Train acc: 52.47% | Val loss: 0.9031 | Val acc: 56.26% | LR: 0.001769
Epoch: 060 | MCC: 0.013496 | Train loss: 0.9582 | Train acc: 52.54% | Val loss: 0.9043 | Val acc: 56.37% | LR: 0.001742
Epoch: 061 | MCC: 0.036686 | Train loss: 0.9539 | Train acc: 52.65% | Val loss: 0.9024 | Val acc: 56.81% | LR: 0.001715
Epoch: 062 | MCC: 0.035149 | Train loss: 0.9553 | Train acc: 52.51% | Val loss: 0.9081 | Val acc: 56.36% | LR: 0.001687
Epoch: 063 | MCC: 0.004589 | Train loss: 0.9504 | Train acc: 52.74% | Val loss: 0.9168 | Val acc: 55.01% | LR: 0.001660
Epoch: 064 | MCC: 0.011080 | Train loss: 0.9510 | Train acc: 52.86% | Val loss: 0.9297 | Val acc: 54.57% | LR: 0.001632
Epoch: 065 | MCC: 0.011773 | Train loss: 0.9518 | Train acc: 52.60% | Val loss: 0.9234 | Val acc: 55.03% | LR: 0.001605
Epoch: 066 | MCC: 0.016240 | Train loss: 0.9542 | Train acc: 52.75% | Val loss: 0.9307 | Val acc: 53.95% | LR: 0.001577
Epoch: 067 | MCC: 0.001710 | Train loss: 0.9496 | Train acc: 52.94% | Val loss: 0.9365 | Val acc: 53.85% | LR: 0.001549
Epoch: 068 | MCC: -0.015907 | Train loss: 0.9503 | Train acc: 52.84% | Val loss: 0.9331 | Val acc: 53.94% | LR: 0.001521
Epoch: 069 | MCC: -0.006845 | Train loss: 0.9504 | Train acc: 52.76% | Val loss: 0.9396 | Val acc: 53.74% | LR: 0.001493
Epoch: 070 | MCC: -0.008598 | Train loss: 0.9490 | Train acc: 52.89% | Val loss: 0.9362 | Val acc: 54.26% | LR: 0.001465
Epoch: 071 | MCC: -0.012481 | Train loss: 0.9501 | Train acc: 52.78% | Val loss: 0.9380 | Val acc: 54.19% | LR: 0.001436
Epoch: 072 | MCC: -0.005431 | Train loss: 0.9467 | Train acc: 53.13% | Val loss: 0.9423 | Val acc: 53.82% | LR: 0.001408
Epoch: 073 | MCC: 0.001075 | Train loss: 0.9456 | Train acc: 53.07% | Val loss: 0.9517 | Val acc: 53.37% | LR: 0.001380
Epoch: 074 | MCC: 0.001342 | Train loss: 0.9445 | Train acc: 53.19% | Val loss: 0.9348 | Val acc: 54.89% | LR: 0.001352
Epoch: 075 | MCC: 0.001208 | Train loss: 0.9451 | Train acc: 53.23% | Val loss: 0.9490 | Val acc: 53.83% | LR: 0.001323
Epoch: 076 | MCC: -0.021915 | Train loss: 0.9423 | Train acc: 53.28% | Val loss: 0.9392 | Val acc: 53.91% | LR: 0.001295
Epoch: 077 | MCC: -0.008446 | Train loss: 0.9536 | Train acc: 53.45% | Val loss: 0.9558 | Val acc: 53.52% | LR: 0.001267
Epoch: 078 | MCC: -0.003712 | Train loss: 0.9433 | Train acc: 53.42% | Val loss: 0.9559 | Val acc: 53.18% | LR: 0.001239
Epoch: 079 | MCC: -0.011991 | Train loss: 0.9372 | Train acc: 53.59% | Val loss: 0.9517 | Val acc: 53.69% | LR: 0.001210
Epoch: 080 | MCC: -0.004208 | Train loss: 0.9367 | Train acc: 53.68% | Val loss: 0.9516 | Val acc: 53.88% | LR: 0.001182
Epoch: 081 | MCC: -0.015420 | Train loss: 0.9386 | Train acc: 53.40% | Val loss: 0.9525 | Val acc: 53.34% | LR: 0.001154
Epoch: 082 | MCC: -0.015758 | Train loss: 0.9362 | Train acc: 53.74% | Val loss: 0.9532 | Val acc: 53.83% | LR: 0.001126
Epoch: 083 | MCC: -0.023406 | Train loss: 0.9367 | Train acc: 53.67% | Val loss: 0.9571 | Val acc: 52.76% | LR: 0.001099
Epoch: 084 | MCC: -0.003862 | Train loss: 0.9378 | Train acc: 53.65% | Val loss: 0.9496 | Val acc: 53.83% | LR: 0.001071
Epoch: 085 | MCC: -0.013399 | Train loss: 0.9361 | Train acc: 53.66% | Val loss: 0.9533 | Val acc: 53.40% | LR: 0.001043
Epoch: 086 | MCC: -0.006721 | Train loss: 0.9339 | Train acc: 53.72% | Val loss: 0.9686 | Val acc: 53.19% | LR: 0.001016
Epoch: 087 | MCC: -0.009472 | Train loss: 0.9315 | Train acc: 53.94% | Val loss: 0.9496 | Val acc: 54.42% | LR: 0.000988
Epoch: 088 | MCC: -0.012194 | Train loss: 0.9327 | Train acc: 53.69% | Val loss: 0.9627 | Val acc: 53.30% | LR: 0.000961
Epoch: 089 | MCC: -0.003856 | Train loss: 0.9310 | Train acc: 53.90% | Val loss: 0.9581 | Val acc: 53.61% | LR: 0.000934
Epoch: 090 | MCC: -0.004523 | Train loss: 0.9306 | Train acc: 53.91% | Val loss: 0.9562 | Val acc: 53.36% | LR: 0.000907
Epoch: 091 | MCC: -0.014946 | Train loss: 0.9300 | Train acc: 53.89% | Val loss: 0.9515 | Val acc: 53.61% | LR: 0.000881
Epoch: 092 | MCC: -0.013673 | Train loss: 0.9288 | Train acc: 53.95% | Val loss: 0.9610 | Val acc: 53.22% | LR: 0.000854
Epoch: 093 | MCC: -0.000064 | Train loss: 0.9252 | Train acc: 54.16% | Val loss: 0.9670 | Val acc: 53.74% | LR: 0.000828
Epoch: 094 | MCC: -0.028185 | Train loss: 0.9242 | Train acc: 54.21% | Val loss: 0.9684 | Val acc: 52.39% | LR: 0.000802
Epoch: 095 | MCC: -0.014366 | Train loss: 0.9257 | Train acc: 54.21% | Val loss: 0.9652 | Val acc: 53.33% | LR: 0.000777
Epoch: 096 | MCC: -0.018681 | Train loss: 0.9226 | Train acc: 54.32% | Val loss: 0.9553 | Val acc: 53.47% | LR: 0.000751
Epoch: 097 | MCC: -0.014608 | Train loss: 0.9242 | Train acc: 54.15% | Val loss: 0.9574 | Val acc: 53.59% | LR: 0.000726
Epoch: 098 | MCC: -0.006398 | Train loss: 0.9217 | Train acc: 54.21% | Val loss: 0.9653 | Val acc: 53.85% | LR: 0.000701
Epoch: 099 | MCC: -0.021244 | Train loss: 0.9198 | Train acc: 54.45% | Val loss: 0.9641 | Val acc: 53.18% | LR: 0.000676
Epoch: 100 | MCC: -0.022498 | Train loss: 0.9197 | Train acc: 54.38% | Val loss: 0.9676 | Val acc: 52.98% | LR: 0.000652
Epoch: 101 | MCC: -0.013439 | Train loss: 0.9164 | Train acc: 54.65% | Val loss: 0.9696 | Val acc: 53.36% | LR: 0.000628
Epoch: 102 | MCC: -0.023357 | Train loss: 0.9181 | Train acc: 54.53% | Val loss: 0.9738 | Val acc: 52.94% | LR: 0.000604
Epoch: 103 | MCC: -0.028956 | Train loss: 0.9150 | Train acc: 54.67% | Val loss: 0.9796 | Val acc: 52.44% | LR: 0.000581
Epoch: 104 | MCC: -0.015091 | Train loss: 0.9163 | Train acc: 54.58% | Val loss: 0.9820 | Val acc: 52.68% | LR: 0.000558
Epoch: 105 | MCC: -0.018239 | Train loss: 0.9157 | Train acc: 54.67% | Val loss: 0.9823 | Val acc: 52.48% | LR: 0.000535
Epoch: 106 | MCC: -0.016158 | Train loss: 0.9139 | Train acc: 54.68% | Val loss: 0.9805 | Val acc: 52.66% | LR: 0.000513
Epoch: 107 | MCC: -0.019107 | Train loss: 0.9107 | Train acc: 54.89% | Val loss: 0.9847 | Val acc: 52.40% | LR: 0.000491
Epoch: 108 | MCC: -0.016408 | Train loss: 0.9123 | Train acc: 54.85% | Val loss: 0.9808 | Val acc: 52.56% | LR: 0.000469
Epoch: 109 | MCC: -0.013216 | Train loss: 0.9111 | Train acc: 54.96% | Val loss: 0.9840 | Val acc: 52.47% | LR: 0.000448
Epoch: 110 | MCC: -0.023008 | Train loss: 0.9103 | Train acc: 54.97% | Val loss: 0.9859 | Val acc: 52.42% | LR: 0.000427
Epoch: 111 | MCC: -0.028274 | Train loss: 0.9099 | Train acc: 54.99% | Val loss: 0.9781 | Val acc: 52.30% | LR: 0.000407
Epoch: 112 | MCC: -0.004406 | Train loss: 0.9077 | Train acc: 55.05% | Val loss: 0.9872 | Val acc: 52.53% | LR: 0.000387
Epoch: 113 | MCC: -0.002532 | Train loss: 0.9090 | Train acc: 55.00% | Val loss: 0.9893 | Val acc: 52.43% | LR: 0.000367
Epoch: 114 | MCC: -0.015694 | Train loss: 0.9068 | Train acc: 55.08% | Val loss: 0.9814 | Val acc: 52.64% | LR: 0.000348
Epoch: 115 | MCC: -0.012962 | Train loss: 0.9072 | Train acc: 55.12% | Val loss: 0.9878 | Val acc: 52.23% | LR: 0.000329
Epoch: 116 | MCC: -0.016119 | Train loss: 0.9063 | Train acc: 55.13% | Val loss: 0.9819 | Val acc: 52.63% | LR: 0.000311
Epoch: 117 | MCC: -0.016804 | Train loss: 0.9073 | Train acc: 55.06% | Val loss: 0.9875 | Val acc: 52.46% | LR: 0.000293
Epoch: 118 | MCC: -0.016750 | Train loss: 0.9062 | Train acc: 55.09% | Val loss: 0.9891 | Val acc: 52.43% | LR: 0.000276
Epoch: 119 | MCC: -0.010515 | Train loss: 0.9036 | Train acc: 55.21% | Val loss: 0.9875 | Val acc: 52.63% | LR: 0.000259
Epoch: 120 | MCC: -0.016150 | Train loss: 0.9055 | Train acc: 55.17% | Val loss: 0.9884 | Val acc: 52.49% | LR: 0.000243
Epoch: 121 | MCC: -0.005079 | Train loss: 0.9045 | Train acc: 55.20% | Val loss: 0.9957 | Val acc: 52.26% | LR: 0.000227
Epoch: 122 | MCC: -0.004345 | Train loss: 0.9043 | Train acc: 55.23% | Val loss: 0.9940 | Val acc: 52.38% | LR: 0.000211
Epoch: 123 | MCC: -0.008107 | Train loss: 0.9026 | Train acc: 55.36% | Val loss: 0.9917 | Val acc: 52.54% | LR: 0.000196
Epoch: 124 | MCC: -0.008683 | Train loss: 0.9039 | Train acc: 55.24% | Val loss: 0.9936 | Val acc: 52.32% | LR: 0.000182
Epoch: 125 | MCC: -0.007826 | Train loss: 0.9051 | Train acc: 55.17% | Val loss: 0.9984 | Val acc: 52.16% | LR: 0.000168
Epoch: 126 | MCC: -0.006147 | Train loss: 0.9032 | Train acc: 55.31% | Val loss: 0.9936 | Val acc: 52.73% | LR: 0.000155
Epoch: 127 | MCC: -0.007166 | Train loss: 0.9022 | Train acc: 55.29% | Val loss: 0.9985 | Val acc: 52.12% | LR: 0.000142
Epoch: 128 | MCC: -0.003156 | Train loss: 0.9008 | Train acc: 55.37% | Val loss: 0.9954 | Val acc: 52.44% | LR: 0.000130
Epoch: 129 | MCC: -0.007323 | Train loss: 0.9032 | Train acc: 55.22% | Val loss: 0.9957 | Val acc: 52.31% | LR: 0.000118
Epoch: 130 | MCC: -0.006423 | Train loss: 0.9011 | Train acc: 55.38% | Val loss: 0.9965 | Val acc: 52.31% | LR: 0.000107
Epoch: 131 | MCC: -0.003442 | Train loss: 0.9007 | Train acc: 55.42% | Val loss: 0.9973 | Val acc: 52.32% | LR: 0.000096
Epoch: 132 | MCC: -0.008593 | Train loss: 0.8993 | Train acc: 55.48% | Val loss: 0.9979 | Val acc: 52.03% | LR: 0.000086

[I 2025-10-05 10:29:10,656] Trial 54 finished with value: -0.010959991661366075 and parameters: {'lr': 0.0027021631613193845, 'hidden_size': 99, 'dropout': 0.03141323145027952, 'weight_decay': 0.011345742088439213}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: -0.026433 | Train loss: 1.0035 | Train acc: 49.30% | Val loss: 0.9889 | Val acc: 53.68% | LR: 0.000214
Epoch: 001 | MCC: 0.000589 | Train loss: 1.0005 | Train acc: 49.48% | Val loss: 0.9864 | Val acc: 54.20% | LR: 0.000214
Epoch: 002 | MCC: -0.012355 | Train loss: 1.0166 | Train acc: 50.24% | Val loss: 0.9863 | Val acc: 53.39% | LR: 0.000214
Epoch: 003 | MCC: -0.003960 | Train loss: 1.0020 | Train acc: 50.43% | Val loss: 0.9852 | Val acc: 53.34% | LR: 0.000214
Epoch: 004 | MCC: -0.013237 | Train loss: 0.9972 | Train acc: 50.67% | Val loss: 0.9859 | Val acc: 53.12% | LR: 0.000214
Epoch: 005 | MCC: 0.005328 | Train loss: 0.9959 | Train acc: 50.85% | Val loss: 0.9935 | Val acc: 53.06% | LR: 0.000213
Epoch: 006 | MCC: 0.018021 | Train loss: 0.9947 | Train acc: 50.82% | Val loss: 0.9827 | Val acc: 53.60% | LR: 0.000213
Epoch: 007 | MCC: 0.020706 | Train loss: 0.9930 | Train acc: 50.87% | Val loss: 0.9834 | Val acc: 54.23% | LR: 0.000213
Epoch: 008 | MCC: 0.023341 | Train loss: 0.9925 | Train acc: 50.80% | Val loss: 0.9802 | Val acc: 54.82% | LR: 0.000212
Epoch: 009 | MCC: 0.016311 | Train loss: 0.9886 | Train acc: 50.96% | Val loss: 0.9785 | Val acc: 54.69% | LR: 0.000212
Epoch: 010 | MCC: 0.003507 | Train loss: 0.9882 | Train acc: 50.95% | Val loss: 0.9775 | Val acc: 54.01% | LR: 0.000211
Epoch: 011 | MCC: 0.023513 | Train loss: 0.9864 | Train acc: 50.93% | Val loss: 1.0292 | Val acc: 54.69% | LR: 0.000211
Epoch: 012 | MCC: 0.021461 | Train loss: 0.9894 | Train acc: 50.89% | Val loss: 0.9728 | Val acc: 54.59% | LR: 0.000210
Epoch: 013 | MCC: 0.026169 | Train loss: 0.9828 | Train acc: 51.04% | Val loss: 0.9633 | Val acc: 54.90% | LR: 0.000210
Epoch: 014 | MCC: 0.029336 | Train loss: 0.9833 | Train acc: 50.90% | Val loss: 0.9537 | Val acc: 55.11% | LR: 0.000209
Epoch: 015 | MCC: 0.030285 | Train loss: 0.9826 | Train acc: 50.88% | Val loss: 0.9485 | Val acc: 55.17% | LR: 0.000208
Epoch: 016 | MCC: 0.024440 | Train loss: 0.9826 | Train acc: 50.80% | Val loss: 0.9450 | Val acc: 55.13% | LR: 0.000208
Epoch: 017 | MCC: 0.022619 | Train loss: 0.9823 | Train acc: 50.85% | Val loss: 0.9425 | Val acc: 55.36% | LR: 0.000207
Epoch: 018 | MCC: 0.021040 | Train loss: 0.9830 | Train acc: 50.97% | Val loss: 0.9414 | Val acc: 55.26% | LR: 0.000206
Epoch: 019 | MCC: 0.015270 | Train loss: 0.9818 | Train acc: 50.98% | Val loss: 0.9388 | Val acc: 55.29% | LR: 0.000205
Epoch: 020 | MCC: 0.017808 | Train loss: 0.9815 | Train acc: 50.85% | Val loss: 0.9306 | Val acc: 55.47% | LR: 0.000204
Epoch: 021 | MCC: 0.020234 | Train loss: 0.9815 | Train acc: 50.91% | Val loss: 0.9263 | Val acc: 55.65% | LR: 0.000203
Epoch: 022 | MCC: 0.022464 | Train loss: 0.9803 | Train acc: 50.96% | Val loss: 0.9221 | Val acc: 55.80% | LR: 0.000202
Epoch: 023 | MCC: 0.026623 | Train loss: 0.9810 | Train acc: 50.97% | Val loss: 0.9154 | Val acc: 56.01% | LR: 0.000201
Epoch: 024 | MCC: 0.030713 | Train loss: 0.9816 | Train acc: 50.83% | Val loss: 0.9139 | Val acc: 56.03% | LR: 0.000200
Epoch: 025 | MCC: 0.031689 | Train loss: 0.9800 | Train acc: 50.89% | Val loss: 0.9076 | Val acc: 56.04% | LR: 0.000199
Epoch: 026 | MCC: 0.026883 | Train loss: 0.9798 | Train acc: 50.99% | Val loss: 0.9040 | Val acc: 55.86% | LR: 0.000198
Epoch: 027 | MCC: 0.032153 | Train loss: 0.9798 | Train acc: 50.97% | Val loss: 0.8994 | Val acc: 56.29% | LR: 0.000196
Epoch: 028 | MCC: 0.034724 | Train loss: 0.9821 | Train acc: 50.82% | Val loss: 0.8970 | Val acc: 56.44% | LR: 0.000195
Epoch: 029 | MCC: 0.037971 | Train loss: 0.9798 | Train acc: 51.02% | Val loss: 0.8925 | Val acc: 56.92% | LR: 0.000194
Epoch: 030 | MCC: 0.033605 | Train loss: 0.9790 | Train acc: 50.99% | Val loss: 0.8871 | Val acc: 57.08% | LR: 0.000193
Epoch: 031 | MCC: 0.053621 | Train loss: 0.9786 | Train acc: 51.02% | Val loss: 0.8818 | Val acc: 57.59% | LR: 0.000191
Epoch: 032 | MCC: 0.042853 | Train loss: 0.9792 | Train acc: 50.98% | Val loss: 0.8781 | Val acc: 57.44% | LR: 0.000190
Epoch: 033 | MCC: 0.045247 | Train loss: 1.0129 | Train acc: 50.99% | Val loss: 0.8734 | Val acc: 57.76% | LR: 0.000188
Epoch: 034 | MCC: 0.029926 | Train loss: 1.0095 | Train acc: 51.15% | Val loss: 0.8717 | Val acc: 57.20% | LR: 0.000187
Epoch: 035 | MCC: 0.027853 | Train loss: 0.9809 | Train acc: 51.28% | Val loss: 0.9007 | Val acc: 57.01% | LR: 0.000185
Epoch: 036 | MCC: 0.030801 | Train loss: 0.9801 | Train acc: 51.09% | Val loss: 0.8682 | Val acc: 56.94% | LR: 0.000184
Epoch: 037 | MCC: -0.012904 | Train loss: 0.9774 | Train acc: 51.26% | Val loss: 0.9165 | Val acc: 55.77% | LR: 0.000182
Epoch: 038 | MCC: 0.005059 | Train loss: 0.9786 | Train acc: 51.16% | Val loss: 1.0034 | Val acc: 56.26% | LR: 0.000181
Epoch: 039 | MCC: 0.011049 | Train loss: 0.9785 | Train acc: 51.33% | Val loss: 0.9047 | Val acc: 54.95% | LR: 0.000179
Epoch: 040 | MCC: -0.002386 | Train loss: 0.9776 | Train acc: 51.32% | Val loss: 0.8623 | Val acc: 57.52% | LR: 0.000177
Epoch: 041 | MCC: -0.009098 | Train loss: 0.9804 | Train acc: 51.11% | Val loss: 0.8668 | Val acc: 57.11% | LR: 0.000176
Epoch: 042 | MCC: -0.001661 | Train loss: 0.9783 | Train acc: 51.12% | Val loss: 0.9089 | Val acc: 56.64% | LR: 0.000174
Epoch: 043 | MCC: -0.006803 | Train loss: 0.9781 | Train acc: 51.18% | Val loss: 0.8875 | Val acc: 55.78% | LR: 0.000172
Epoch: 044 | MCC: -0.006220 | Train loss: 0.9826 | Train acc: 51.21% | Val loss: 0.8760 | Val acc: 56.20% | LR: 0.000170
Epoch: 045 | MCC: 0.000211 | Train loss: 0.9924 | Train acc: 51.05% | Val loss: 0.8775 | Val acc: 56.29% | LR: 0.000169
Epoch: 046 | MCC: 0.003895 | Train loss: 0.9801 | Train acc: 51.08% | Val loss: 0.8631 | Val acc: 57.20% | LR: 0.000167
Epoch: 047 | MCC: 0.015782 | Train loss: 0.9810 | Train acc: 50.93% | Val loss: 0.8647 | Val acc: 57.55% | LR: 0.000165
Epoch: 048 | MCC: 0.009215 | Train loss: 0.9788 | Train acc: 51.02% | Val loss: 0.8770 | Val acc: 57.02% | LR: 0.000163
Epoch: 049 | MCC: 0.002269 | Train loss: 0.9815 | Train acc: 50.88% | Val loss: 0.8743 | Val acc: 56.52% | LR: 0.000161
Epoch: 050 | MCC: -0.002569 | Train loss: 0.9801 | Train acc: 51.11% | Val loss: 0.8871 | Val acc: 56.07% | LR: 0.000159
Epoch: 051 | MCC: -0.007792 | Train loss: 0.9778 | Train acc: 51.12% | Val loss: 0.8915 | Val acc: 55.70% | LR: 0.000157
Epoch: 052 | MCC: -0.004217 | Train loss: 0.9794 | Train acc: 51.07% | Val loss: 0.8849 | Val acc: 56.01% | LR: 0.000155
Epoch: 053 | MCC: -0.000939 | Train loss: 0.9776 | Train acc: 51.06% | Val loss: 0.8807 | Val acc: 56.13% | LR: 0.000153
Epoch: 054 | MCC: -0.004744 | Train loss: 0.9783 | Train acc: 51.05% | Val loss: 0.9120 | Val acc: 55.91% | LR: 0.000151
Epoch: 055 | MCC: 0.006789 | Train loss: 0.9799 | Train acc: 51.05% | Val loss: 0.8830 | Val acc: 56.02% | LR: 0.000149
Epoch: 056 | MCC: 0.007646 | Train loss: 0.9803 | Train acc: 50.89% | Val loss: 0.8810 | Val acc: 56.32% | LR: 0.000147
Epoch: 057 | MCC: 0.007128 | Train loss: 0.9803 | Train acc: 50.98% | Val loss: 0.8800 | Val acc: 56.56% | LR: 0.000145
Epoch: 058 | MCC: 0.002073 | Train loss: 0.9783 | Train acc: 51.05% | Val loss: 0.8750 | Val acc: 56.69% | LR: 0.000143
Epoch: 059 | MCC: 0.001544 | Train loss: 0.9784 | Train acc: 51.06% | Val loss: 0.8801 | Val acc: 56.17% | LR: 0.000141
Epoch: 060 | MCC: 0.001089 | Train loss: 0.9789 | Train acc: 50.93% | Val loss: 0.8796 | Val acc: 56.10% | LR: 0.000138
Epoch: 061 | MCC: 0.002407 | Train loss: 0.9786 | Train acc: 50.95% | Val loss: 0.8742 | Val acc: 56.65% | LR: 0.000136
Epoch: 062 | MCC: 0.004882 | Train loss: 0.9783 | Train acc: 50.99% | Val loss: 0.8749 | Val acc: 56.74% | LR: 0.000134
Epoch: 063 | MCC: -0.000390 | Train loss: 0.9789 | Train acc: 50.96% | Val loss: 0.8939 | Val acc: 56.09% | LR: 0.000132
Epoch: 064 | MCC: -0.002335 | Train loss: 0.9786 | Train acc: 50.93% | Val loss: 0.8794 | Val acc: 56.28% | LR: 0.000130
Epoch: 065 | MCC: -0.005740 | Train loss: 0.9764 | Train acc: 51.20% | Val loss: 0.8928 | Val acc: 56.01% | LR: 0.000128
Epoch: 066 | MCC: -0.009147 | Train loss: 0.9764 | Train acc: 51.08% | Val loss: 0.8896 | Val acc: 55.74% | LR: 0.000125
Epoch: 067 | MCC: -0.006266 | Train loss: 0.9762 | Train acc: 51.19% | Val loss: 0.8854 | Val acc: 55.75% | LR: 0.000123
Epoch: 068 | MCC: -0.001396 | Train loss: 0.9765 | Train acc: 51.09% | Val loss: 0.8753 | Val acc: 56.30% | LR: 0.000121
Epoch: 069 | MCC: -0.001099 | Train loss: 0.9782 | Train acc: 51.03% | Val loss: 0.8780 | Val acc: 56.60% | LR: 0.000119
Epoch: 070 | MCC: -0.002555 | Train loss: 0.9774 | Train acc: 51.02% | Val loss: 0.8781 | Val acc: 56.33% | LR: 0.000117
Epoch: 071 | MCC: -0.004963 | Train loss: 0.9762 | Train acc: 51.16% | Val loss: 0.8824 | Val acc: 55.91% | LR: 0.000114
Epoch: 072 | MCC: -0.003062 | Train loss: 0.9783 | Train acc: 51.01% | Val loss: 0.8793 | Val acc: 56.21% | LR: 0.000112
Epoch: 073 | MCC: 0.003652 | Train loss: 0.9781 | Train acc: 51.02% | Val loss: 0.8881 | Val acc: 56.11% | LR: 0.000110
Epoch: 074 | MCC: 0.004684 | Train loss: 0.9757 | Train acc: 51.12% | Val loss: 0.8776 | Val acc: 56.11% | LR: 0.000108
Epoch: 075 | MCC: -0.007143 | Train loss: 0.9774 | Train acc: 51.06% | Val loss: 0.8852 | Val acc: 55.73% | LR: 0.000105
Epoch: 076 | MCC: -0.010011 | Train loss: 0.9768 | Train acc: 51.24% | Val loss: 0.8835 | Val acc: 55.61% | LR: 0.000103
Epoch: 077 | MCC: -0.004920 | Train loss: 0.9747 | Train acc: 51.37% | Val loss: 0.8899 | Val acc: 55.80% | LR: 0.000101
Epoch: 078 | MCC: -0.003718 | Train loss: 0.9754 | Train acc: 51.30% | Val loss: 0.8861 | Val acc: 55.73% | LR: 0.000099
Epoch: 079 | MCC: -0.009326 | Train loss: 0.9791 | Train acc: 51.07% | Val loss: 0.8908 | Val acc: 55.46% | LR: 0.000097
Epoch: 080 | MCC: -0.009535 | Train loss: 0.9750 | Train acc: 51.34% | Val loss: 0.8884 | Val acc: 55.46% | LR: 0.000094
Epoch: 081 | MCC: -0.004907 | Train loss: 0.9760 | Train acc: 51.35% | Val loss: 0.8827 | Val acc: 55.78% | LR: 0.000092
Epoch: 082 | MCC: -0.007043 | Train loss: 0.9749 | Train acc: 51.28% | Val loss: 0.8868 | Val acc: 55.73% | LR: 0.000090
Epoch: 083 | MCC: -0.004859 | Train loss: 0.9767 | Train acc: 51.13% | Val loss: 0.8823 | Val acc: 55.77% | LR: 0.000088
Epoch: 084 | MCC: -0.002027 | Train loss: 0.9762 | Train acc: 51.18% | Val loss: 0.8903 | Val acc: 55.70% | LR: 0.000085
Epoch: 085 | MCC: -0.007810 | Train loss: 0.9758 | Train acc: 51.19% | Val loss: 0.8915 | Val acc: 55.43% | LR: 0.000083
Epoch: 086 | MCC: -0.006683 | Train loss: 0.9748 | Train acc: 51.28% | Val loss: 0.8906 | Val acc: 55.46% | LR: 0.000081
Epoch: 087 | MCC: -0.006686 | Train loss: 0.9762 | Train acc: 51.33% | Val loss: 0.8901 | Val acc: 55.53% | LR: 0.000079
Epoch: 088 | MCC: -0.005101 | Train loss: 0.9734 | Train acc: 51.41% | Val loss: 0.8904 | Val acc: 55.61% | LR: 0.000077
Epoch: 089 | MCC: -0.008378 | Train loss: 0.9765 | Train acc: 51.32% | Val loss: 0.8860 | Val acc: 55.48% | LR: 0.000075
Epoch: 090 | MCC: -0.005390 | Train loss: 0.9768 | Train acc: 51.01% | Val loss: 0.8888 | Val acc: 55.73% | LR: 0.000073
Epoch: 091 | MCC: -0.010152 | Train loss: 0.9748 | Train acc: 51.18% | Val loss: 0.8887 | Val acc: 55.39% | LR: 0.000070
Epoch: 092 | MCC: -0.006444 | Train loss: 0.9752 | Train acc: 51.25% | Val loss: 0.8850 | Val acc: 55.61% | LR: 0.000068
Epoch: 093 | MCC: -0.004409 | Train loss: 0.9755 | Train acc: 51.43% | Val loss: 0.9559 | Val acc: 55.78% | LR: 0.000066
Epoch: 094 | MCC: -0.011978 | Train loss: 0.9757 | Train acc: 50.97% | Val loss: 0.8869 | Val acc: 55.34% | LR: 0.000064
Epoch: 095 | MCC: -0.009368 | Train loss: 0.9753 | Train acc: 51.43% | Val loss: 0.8935 | Val acc: 55.39% | LR: 0.000062
Epoch: 096 | MCC: -0.008708 | Train loss: 0.9760 | Train acc: 51.15% | Val loss: 0.8926 | Val acc: 55.37% | LR: 0.000060
Epoch: 097 | MCC: -0.005372 | Train loss: 0.9758 | Train acc: 51.05% | Val loss: 0.8987 | Val acc: 55.59% | LR: 0.000058
Epoch: 098 | MCC: -0.004238 | Train loss: 0.9746 | Train acc: 51.27% | Val loss: 0.8904 | Val acc: 55.62% | LR: 0.000056
Epoch: 099 | MCC: -0.007236 | Train loss: 0.9737 | Train acc: 51.31% | Val loss: 0.8924 | Val acc: 55.47% | LR: 0.000054
Epoch: 100 | MCC: -0.006376 | Train loss: 0.9758 | Train acc: 51.32% | Val loss: 0.8879 | Val acc: 55.54% | LR: 0.000052
Epoch: 101 | MCC: -0.006824 | Train loss: 0.9740 | Train acc: 51.48% | Val loss: 0.8900 | Val acc: 55.54% | LR: 0.000051
Epoch: 102 | MCC: -0.008542 | Train loss: 0.9735 | Train acc: 51.76% | Val loss: 0.8899 | Val acc: 55.47% | LR: 0.000049
Epoch: 103 | MCC: -0.008184 | Train loss: 0.9972 | Train acc: 51.78% | Val loss: 0.8919 | Val acc: 55.52% | LR: 0.000047
Epoch: 104 | MCC: -0.007502 | Train loss: 1.0593 | Train acc: 51.74% | Val loss: 0.8900 | Val acc: 55.52% | LR: 0.000045
Epoch: 105 | MCC: -0.010959 | Train loss: 1.3365 | Train acc: 51.65% | Val loss: 0.8913 | Val acc: 55.37% | LR: 0.000043
Epoch: 106 | MCC: -0.008564 | Train loss: 1.0232 | Train acc: 51.44% | Val loss: 0.8899 | Val acc: 55.40% | LR: 0.000041
Epoch: 107 | MCC: -0.010648 | Train loss: 1.0178 | Train acc: 51.44% | Val loss: 0.8904 | Val acc: 55.32% | LR: 0.000040
Epoch: 108 | MCC: -0.010608 | Train loss: 1.0023 | Train acc: 51.42% | Val loss: 0.8905 | Val acc: 55.27% | LR: 0.000038
Epoch: 109 | MCC: -0.008986 | Train loss: 1.0101 | Train acc: 51.50% | Val loss: 0.9024 | Val acc: 55.42% | LR: 0.000036
Epoch: 110 | MCC: -0.009257 | Train loss: 0.9739 | Train acc: 51.57% | Val loss: 0.8892 | Val acc: 55.37% | LR: 0.000035
Epoch: 111 | MCC: -0.008422 | Train loss: 0.9744 | Train acc: 51.29% | Val loss: 0.8893 | Val acc: 55.37% | LR: 0.000033
Epoch: 112 | MCC: -0.007099 | Train loss: 0.9727 | Train acc: 51.52% | Val loss: 0.8911 | Val acc: 55.45% | LR: 0.000031
Epoch: 113 | MCC: -0.007759 | Train loss: 0.9714 | Train acc: 52.10% | Val loss: 0.8894 | Val acc: 55.42% | LR: 0.000030
Epoch: 114 | MCC: -0.007099 | Train loss: 0.9743 | Train acc: 51.37% | Val loss: 0.8903 | Val acc: 55.45% | LR: 0.000028

[I 2025-10-05 10:31:00,328] Trial 55 finished with value: -0.008305171504616737 and parameters: {'lr': 0.00021430340817423445, 'hidden_size': 91, 'dropout': 0.063483782817632, 'weight_decay': 0.04098481511479646}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: -0.000572 | Train loss: 0.9990 | Train acc: 50.01% | Val loss: 0.9864 | Val acc: 54.73% | LR: 0.000458
Epoch: 001 | MCC: -0.006086 | Train loss: 0.9939 | Train acc: 50.48% | Val loss: 0.9839 | Val acc: 54.92% | LR: 0.000458
Epoch: 002 | MCC: -0.002990 | Train loss: 0.9929 | Train acc: 50.54% | Val loss: 0.9799 | Val acc: 55.55% | LR: 0.000457
Epoch: 003 | MCC: -0.027463 | Train loss: 0.9906 | Train acc: 51.02% | Val loss: 0.9799 | Val acc: 54.59% | LR: 0.000457
Epoch: 004 | MCC: 0.004769 | Train loss: 0.9899 | Train acc: 50.90% | Val loss: 0.9759 | Val acc: 54.42% | LR: 0.000457
Epoch: 005 | MCC: 0.013499 | Train loss: 0.9847 | Train acc: 51.00% | Val loss: 0.9611 | Val acc: 54.80% | LR: 0.000456
Epoch: 006 | MCC: 0.020042 | Train loss: 0.9849 | Train acc: 50.94% | Val loss: 0.9496 | Val acc: 55.49% | LR: 0.000455
Epoch: 007 | MCC: 0.009592 | Train loss: 0.9835 | Train acc: 50.96% | Val loss: 0.9410 | Val acc: 55.41% | LR: 0.000455
Epoch: 008 | MCC: 0.015506 | Train loss: 0.9823 | Train acc: 51.04% | Val loss: 0.9284 | Val acc: 55.98% | LR: 0.000454
Epoch: 009 | MCC: 0.019695 | Train loss: 0.9832 | Train acc: 50.93% | Val loss: 0.9169 | Val acc: 56.10% | LR: 0.000453
Epoch: 010 | MCC: 0.024529 | Train loss: 0.9823 | Train acc: 50.82% | Val loss: 0.9102 | Val acc: 56.92% | LR: 0.000452
Epoch: 011 | MCC: 0.011321 | Train loss: 0.9809 | Train acc: 50.98% | Val loss: 0.9039 | Val acc: 56.87% | LR: 0.000451
Epoch: 012 | MCC: 0.019881 | Train loss: 0.9804 | Train acc: 51.00% | Val loss: 0.8946 | Val acc: 56.75% | LR: 0.000449
Epoch: 013 | MCC: -0.001129 | Train loss: 0.9798 | Train acc: 51.11% | Val loss: 0.8852 | Val acc: 56.28% | LR: 0.000448
Epoch: 014 | MCC: -0.010865 | Train loss: 0.9786 | Train acc: 51.18% | Val loss: 0.8828 | Val acc: 55.66% | LR: 0.000447
Epoch: 015 | MCC: -0.008492 | Train loss: 0.9785 | Train acc: 51.17% | Val loss: 0.8710 | Val acc: 56.25% | LR: 0.000445
Epoch: 016 | MCC: 0.006129 | Train loss: 0.9788 | Train acc: 51.20% | Val loss: 0.8901 | Val acc: 56.30% | LR: 0.000443
Epoch: 017 | MCC: 0.001248 | Train loss: 0.9787 | Train acc: 51.14% | Val loss: 0.8762 | Val acc: 56.44% | LR: 0.000442
Epoch: 018 | MCC: 0.005623 | Train loss: 0.9759 | Train acc: 51.25% | Val loss: 0.8888 | Val acc: 55.91% | LR: 0.000440
Epoch: 019 | MCC: -0.006574 | Train loss: 0.9778 | Train acc: 51.14% | Val loss: 0.8702 | Val acc: 56.59% | LR: 0.000438
Epoch: 020 | MCC: 0.003316 | Train loss: 0.9758 | Train acc: 51.26% | Val loss: 0.8758 | Val acc: 56.10% | LR: 0.000436
Epoch: 021 | MCC: -0.005498 | Train loss: 0.9751 | Train acc: 51.26% | Val loss: 0.8658 | Val acc: 57.10% | LR: 0.000434
Epoch: 022 | MCC: 0.003407 | Train loss: 0.9750 | Train acc: 51.24% | Val loss: 0.8691 | Val acc: 56.83% | LR: 0.000432
Epoch: 023 | MCC: -0.006902 | Train loss: 0.9737 | Train acc: 51.36% | Val loss: 0.8647 | Val acc: 57.08% | LR: 0.000430
Epoch: 024 | MCC: 0.004789 | Train loss: 0.9736 | Train acc: 51.31% | Val loss: 0.8668 | Val acc: 56.91% | LR: 0.000427
Epoch: 025 | MCC: 0.026993 | Train loss: 0.9750 | Train acc: 51.28% | Val loss: 0.8524 | Val acc: 58.25% | LR: 0.000425
Epoch: 026 | MCC: 0.032425 | Train loss: 0.9805 | Train acc: 50.95% | Val loss: 0.9121 | Val acc: 54.82% | LR: 0.000422
Epoch: 027 | MCC: 0.026994 | Train loss: 0.9790 | Train acc: 51.07% | Val loss: 0.8489 | Val acc: 58.55% | LR: 0.000420
Epoch: 028 | MCC: -0.004013 | Train loss: 0.9747 | Train acc: 51.29% | Val loss: 0.8686 | Val acc: 57.10% | LR: 0.000417
Epoch: 029 | MCC: 0.011441 | Train loss: 0.9748 | Train acc: 51.27% | Val loss: 0.8766 | Val acc: 56.83% | LR: 0.000414
Epoch: 030 | MCC: 0.017045 | Train loss: 0.9746 | Train acc: 51.27% | Val loss: 0.8626 | Val acc: 57.37% | LR: 0.000411
Epoch: 031 | MCC: 0.017291 | Train loss: 0.9731 | Train acc: 51.23% | Val loss: 0.8441 | Val acc: 58.25% | LR: 0.000408
Epoch: 032 | MCC: 0.022312 | Train loss: 0.9716 | Train acc: 51.40% | Val loss: 0.8466 | Val acc: 58.27% | LR: 0.000405
Epoch: 033 | MCC: 0.011599 | Train loss: 0.9730 | Train acc: 51.34% | Val loss: 0.8506 | Val acc: 57.74% | LR: 0.000402
Epoch: 034 | MCC: 0.023781 | Train loss: 0.9689 | Train acc: 51.63% | Val loss: 0.8474 | Val acc: 58.10% | LR: 0.000399
Epoch: 035 | MCC: 0.033864 | Train loss: 0.9716 | Train acc: 51.40% | Val loss: 0.8138 | Val acc: 59.98% | LR: 0.000396
Epoch: 036 | MCC: 0.022303 | Train loss: 0.9761 | Train acc: 51.21% | Val loss: 0.8449 | Val acc: 58.20% | LR: 0.000393
Epoch: 037 | MCC: 0.065672 | Train loss: 0.9718 | Train acc: 51.48% | Val loss: 0.8208 | Val acc: 59.67% | LR: 0.000389
Epoch: 038 | MCC: 0.020250 | Train loss: 0.9775 | Train acc: 51.14% | Val loss: 0.9121 | Val acc: 54.73% | LR: 0.000386
Epoch: 039 | MCC: 0.026711 | Train loss: 0.9808 | Train acc: 51.00% | Val loss: 0.9160 | Val acc: 54.19% | LR: 0.000382
Epoch: 040 | MCC: 0.000217 | Train loss: 0.9800 | Train acc: 50.93% | Val loss: 0.8832 | Val acc: 55.84% | LR: 0.000379
Epoch: 041 | MCC: 0.012322 | Train loss: 0.9754 | Train acc: 51.17% | Val loss: 0.8555 | Val acc: 57.76% | LR: 0.000375
Epoch: 042 | MCC: 0.015717 | Train loss: 0.9906 | Train acc: 51.24% | Val loss: 0.8708 | Val acc: 56.86% | LR: 0.000371
Epoch: 043 | MCC: 0.012021 | Train loss: 0.9722 | Train acc: 51.39% | Val loss: 0.8553 | Val acc: 57.57% | LR: 0.000367
Epoch: 044 | MCC: 0.010717 | Train loss: 0.9728 | Train acc: 51.38% | Val loss: 0.8524 | Val acc: 57.61% | LR: 0.000364
Epoch: 045 | MCC: 0.042858 | Train loss: 0.9728 | Train acc: 51.36% | Val loss: 0.8670 | Val acc: 57.05% | LR: 0.000360
Epoch: 046 | MCC: 0.034034 | Train loss: 0.9716 | Train acc: 51.44% | Val loss: 0.8178 | Val acc: 59.71% | LR: 0.000356
Epoch: 047 | MCC: 0.042509 | Train loss: 0.9730 | Train acc: 51.38% | Val loss: 0.8177 | Val acc: 59.68% | LR: 0.000352
Epoch: 048 | MCC: 0.054426 | Train loss: 0.9728 | Train acc: 51.35% | Val loss: 0.8123 | Val acc: 59.91% | LR: 0.000348
Epoch: 049 | MCC: 0.068934 | Train loss: 0.9740 | Train acc: 51.28% | Val loss: 0.8174 | Val acc: 59.94% | LR: 0.000344
Epoch: 050 | MCC: 0.013597 | Train loss: 0.9736 | Train acc: 51.27% | Val loss: 0.8543 | Val acc: 57.50% | LR: 0.000339
Epoch: 051 | MCC: 0.023043 | Train loss: 0.9763 | Train acc: 51.14% | Val loss: 0.8413 | Val acc: 58.26% | LR: 0.000335
Epoch: 052 | MCC: 0.039507 | Train loss: 0.9743 | Train acc: 51.23% | Val loss: 0.8170 | Val acc: 59.88% | LR: 0.000331
Epoch: 053 | MCC: 0.034442 | Train loss: 0.9712 | Train acc: 51.46% | Val loss: 0.8314 | Val acc: 58.76% | LR: 0.000327
Epoch: 054 | MCC: 0.064325 | Train loss: 0.9731 | Train acc: 51.37% | Val loss: 0.8257 | Val acc: 59.27% | LR: 0.000322
Epoch: 055 | MCC: 0.076527 | Train loss: 0.9726 | Train acc: 51.31% | Val loss: 0.8269 | Val acc: 59.21% | LR: 0.000318
Epoch: 056 | MCC: 0.041001 | Train loss: 0.9740 | Train acc: 51.26% | Val loss: 0.8205 | Val acc: 59.32% | LR: 0.000313
Epoch: 057 | MCC: 0.087019 | Train loss: 0.9709 | Train acc: 51.41% | Val loss: 0.8059 | Val acc: 60.23% | LR: 0.000309
Epoch: 058 | MCC: 0.082133 | Train loss: 0.9700 | Train acc: 51.50% | Val loss: 0.8050 | Val acc: 60.36% | LR: 0.000305
Epoch: 059 | MCC: 0.073542 | Train loss: 0.9700 | Train acc: 51.53% | Val loss: 0.8075 | Val acc: 60.33% | LR: 0.000300
Epoch: 060 | MCC: 0.036307 | Train loss: 0.9693 | Train acc: 51.51% | Val loss: 0.8178 | Val acc: 59.52% | LR: 0.000295
Epoch: 061 | MCC: 0.078666 | Train loss: 0.9695 | Train acc: 51.52% | Val loss: 0.8146 | Val acc: 59.70% | LR: 0.000291
Epoch: 062 | MCC: 0.041296 | Train loss: 0.9690 | Train acc: 51.57% | Val loss: 0.8177 | Val acc: 59.42% | LR: 0.000286
Epoch: 063 | MCC: 0.028746 | Train loss: 0.9724 | Train acc: 51.37% | Val loss: 0.8224 | Val acc: 59.49% | LR: 0.000282
Epoch: 064 | MCC: 0.029114 | Train loss: 0.9743 | Train acc: 51.18% | Val loss: 0.8105 | Val acc: 59.84% | LR: 0.000277
Epoch: 065 | MCC: 0.034978 | Train loss: 0.9707 | Train acc: 51.44% | Val loss: 0.8085 | Val acc: 60.17% | LR: 0.000272
Epoch: 066 | MCC: 0.034210 | Train loss: 0.9714 | Train acc: 51.42% | Val loss: 0.8396 | Val acc: 58.32% | LR: 0.000267
Epoch: 067 | MCC: 0.030820 | Train loss: 0.9727 | Train acc: 51.28% | Val loss: 0.8353 | Val acc: 58.54% | LR: 0.000263
Epoch: 068 | MCC: 0.032072 | Train loss: 0.9723 | Train acc: 51.34% | Val loss: 0.8265 | Val acc: 59.08% | LR: 0.000258
Epoch: 069 | MCC: 0.027007 | Train loss: 0.9708 | Train acc: 51.42% | Val loss: 0.8147 | Val acc: 59.53% | LR: 0.000253
Epoch: 070 | MCC: 0.077112 | Train loss: 0.9699 | Train acc: 51.48% | Val loss: 0.8053 | Val acc: 60.14% | LR: 0.000249
Epoch: 071 | MCC: 0.038594 | Train loss: 0.9687 | Train acc: 51.61% | Val loss: 0.8200 | Val acc: 59.40% | LR: 0.000244
Epoch: 072 | MCC: 0.058114 | Train loss: 0.9689 | Train acc: 51.49% | Val loss: 0.8089 | Val acc: 59.80% | LR: 0.000239
Epoch: 073 | MCC: 0.080470 | Train loss: 0.9704 | Train acc: 51.43% | Val loss: 0.8053 | Val acc: 60.09% | LR: 0.000234
Epoch: 074 | MCC: 0.030735 | Train loss: 0.9695 | Train acc: 51.43% | Val loss: 0.8179 | Val acc: 59.32% | LR: 0.000229
Epoch: 075 | MCC: 0.033449 | Train loss: 0.9706 | Train acc: 51.37% | Val loss: 0.8191 | Val acc: 59.40% | LR: 0.000225
Epoch: 076 | MCC: 0.061534 | Train loss: 0.9677 | Train acc: 51.57% | Val loss: 0.8029 | Val acc: 60.27% | LR: 0.000220
Epoch: 077 | MCC: 0.033090 | Train loss: 0.9699 | Train acc: 51.43% | Val loss: 0.8176 | Val acc: 59.40% | LR: 0.000215
Epoch: 078 | MCC: 0.038078 | Train loss: 0.9672 | Train acc: 51.60% | Val loss: 0.8099 | Val acc: 59.93% | LR: 0.000210
Epoch: 079 | MCC: 0.031944 | Train loss: 0.9693 | Train acc: 51.49% | Val loss: 0.8199 | Val acc: 59.37% | LR: 0.000206
Epoch: 080 | MCC: 0.038155 | Train loss: 0.9684 | Train acc: 51.55% | Val loss: 0.8044 | Val acc: 60.12% | LR: 0.000201
Epoch: 081 | MCC: 0.068465 | Train loss: 0.9675 | Train acc: 51.59% | Val loss: 0.7988 | Val acc: 60.54% | LR: 0.000196
Epoch: 082 | MCC: 0.040110 | Train loss: 0.9688 | Train acc: 51.51% | Val loss: 0.8061 | Val acc: 60.14% | LR: 0.000191
Epoch: 083 | MCC: 0.033386 | Train loss: 0.9685 | Train acc: 51.49% | Val loss: 0.8200 | Val acc: 59.32% | LR: 0.000187
Epoch: 084 | MCC: 0.035569 | Train loss: 0.9692 | Train acc: 51.37% | Val loss: 0.8180 | Val acc: 59.47% | LR: 0.000182
Epoch: 085 | MCC: 0.067117 | Train loss: 0.9685 | Train acc: 51.51% | Val loss: 0.8005 | Val acc: 60.43% | LR: 0.000177
Epoch: 086 | MCC: 0.058057 | Train loss: 0.9699 | Train acc: 51.39% | Val loss: 0.7995 | Val acc: 60.40% | LR: 0.000173
Epoch: 087 | MCC: 0.030279 | Train loss: 0.9699 | Train acc: 51.36% | Val loss: 0.8212 | Val acc: 59.27% | LR: 0.000168
Epoch: 088 | MCC: 0.034889 | Train loss: 0.9680 | Train acc: 51.49% | Val loss: 0.8116 | Val acc: 59.67% | LR: 0.000163
Epoch: 089 | MCC: 0.036956 | Train loss: 0.9655 | Train acc: 51.63% | Val loss: 0.8151 | Val acc: 59.71% | LR: 0.000159
Epoch: 090 | MCC: 0.031111 | Train loss: 0.9671 | Train acc: 51.53% | Val loss: 0.8200 | Val acc: 59.37% | LR: 0.000154
Epoch: 091 | MCC: 0.027710 | Train loss: 0.9670 | Train acc: 51.54% | Val loss: 0.8158 | Val acc: 59.44% | LR: 0.000150
Epoch: 092 | MCC: 0.028241 | Train loss: 0.9675 | Train acc: 51.49% | Val loss: 0.8115 | Val acc: 59.68% | LR: 0.000145
Epoch: 093 | MCC: 0.026344 | Train loss: 0.9678 | Train acc: 51.41% | Val loss: 0.8187 | Val acc: 59.34% | LR: 0.000141
Epoch: 094 | MCC: 0.025812 | Train loss: 0.9829 | Train acc: 51.64% | Val loss: 0.8182 | Val acc: 59.31% | LR: 0.000137
Epoch: 095 | MCC: 0.026527 | Train loss: 0.9851 | Train acc: 51.52% | Val loss: 0.8128 | Val acc: 59.58% | LR: 0.000132
Epoch: 096 | MCC: 0.026870 | Train loss: 0.9858 | Train acc: 51.48% | Val loss: 0.8150 | Val acc: 59.44% | LR: 0.000128
Epoch: 097 | MCC: 0.026134 | Train loss: 1.0017 | Train acc: 51.58% | Val loss: 0.8195 | Val acc: 59.26% | LR: 0.000124
Epoch: 098 | MCC: 0.026762 | Train loss: 0.9672 | Train acc: 51.61% | Val loss: 0.8164 | Val acc: 59.48% | LR: 0.000119
Epoch: 099 | MCC: 0.028882 | Train loss: 0.9702 | Train acc: 51.34% | Val loss: 0.8242 | Val acc: 59.18% | LR: 0.000115
Epoch: 100 | MCC: 0.054449 | Train loss: 0.9679 | Train acc: 51.49% | Val loss: 0.8158 | Val acc: 59.62% | LR: 0.000111
Epoch: 101 | MCC: 0.076472 | Train loss: 0.9672 | Train acc: 51.53% | Val loss: 0.8021 | Val acc: 60.29% | LR: 0.000107
Epoch: 102 | MCC: 0.068367 | Train loss: 0.9695 | Train acc: 51.40% | Val loss: 0.8063 | Val acc: 59.97% | LR: 0.000103
Epoch: 103 | MCC: 0.075156 | Train loss: 0.9694 | Train acc: 51.35% | Val loss: 0.8113 | Val acc: 59.82% | LR: 0.000099
Epoch: 104 | MCC: 0.073155 | Train loss: 0.9689 | Train acc: 51.47% | Val loss: 0.8089 | Val acc: 59.87% | LR: 0.000095
Epoch: 105 | MCC: 0.028254 | Train loss: 0.9683 | Train acc: 51.45% | Val loss: 0.8190 | Val acc: 59.29% | LR: 0.000091
Epoch: 106 | MCC: 0.024105 | Train loss: 0.9682 | Train acc: 51.49% | Val loss: 0.8206 | Val acc: 59.19% | LR: 0.000088
Epoch: 107 | MCC: 0.027380 | Train loss: 0.9672 | Train acc: 51.47% | Val loss: 0.8187 | Val acc: 59.46% | LR: 0.000084
Epoch: 108 | MCC: 0.023682 | Train loss: 0.9664 | Train acc: 51.54% | Val loss: 0.8184 | Val acc: 59.24% | LR: 0.000080
Epoch: 109 | MCC: 0.024003 | Train loss: 0.9666 | Train acc: 51.54% | Val loss: 0.8207 | Val acc: 59.26% | LR: 0.000077
Epoch: 110 | MCC: 0.027285 | Train loss: 0.9664 | Train acc: 51.57% | Val loss: 0.8155 | Val acc: 59.46% | LR: 0.000073
Epoch: 111 | MCC: 0.025165 | Train loss: 0.9647 | Train acc: 51.72% | Val loss: 0.8194 | Val acc: 59.29% | LR: 0.000070
Epoch: 112 | MCC: 0.025137 | Train loss: 0.9660 | Train acc: 51.60% | Val loss: 0.8176 | Val acc: 59.34% | LR: 0.000066
Epoch: 113 | MCC: 0.025939 | Train loss: 0.9688 | Train acc: 51.40% | Val loss: 0.8189 | Val acc: 59.34% | LR: 0.000063
Epoch: 114 | MCC: 0.023456 | Train loss: 0.9667 | Train acc: 51.59% | Val loss: 0.8189 | Val acc: 59.24% | LR: 0.000060
Epoch: 115 | MCC: 0.024710 | Train loss: 0.9670 | Train acc: 51.49% | Val loss: 0.8185 | Val acc: 59.29% | LR: 0.000057
Epoch: 116 | MCC: 0.023845 | Train loss: 0.9674 | Train acc: 51.48% | Val loss: 0.8188 | Val acc: 59.29% | LR: 0.000053
Epoch: 117 | MCC: 0.025269 | Train loss: 0.9649 | Train acc: 51.71% | Val loss: 0.8177 | Val acc: 59.34% | LR: 0.000050
Epoch: 118 | MCC: 0.024815 | Train loss: 0.9645 | Train acc: 51.62% | Val loss: 0.8189 | Val acc: 59.31% | LR: 0.000047
Epoch: 119 | MCC: 0.024323 | Train loss: 0.9658 | Train acc: 51.57% | Val loss: 0.8199 | Val acc: 59.24% | LR: 0.000045
Epoch: 120 | MCC: 0.024550 | Train loss: 0.9648 | Train acc: 51.65% | Val loss: 0.8191 | Val acc: 59.26% | LR: 0.000042
Epoch: 121 | MCC: 0.024296 | Train loss: 0.9647 | Train acc: 51.69% | Val loss: 0.8193 | Val acc: 59.26% | LR: 0.000039
Epoch: 122 | MCC: 0.024550 | Train loss: 0.9667 | Train acc: 51.52% | Val loss: 0.8185 | Val acc: 59.26% | LR: 0.000037
Epoch: 123 | MCC: 0.024323 | Train loss: 0.9648 | Train acc: 51.64% | Val loss: 0.8192 | Val acc: 59.24% | LR: 0.000034
Epoch: 124 | MCC: 0.023843 | Train loss: 0.9646 | Train acc: 51.64% | Val loss: 0.8193 | Val acc: 59.24% | LR: 0.000032
Epoch: 125 | MCC: 0.024323 | Train loss: 0.9647 | Train acc: 51.69% | Val loss: 0.8193 | Val acc: 59.24% | LR: 0.000029
Epoch: 126 | MCC: 0.024296 | Train loss: 0.9647 | Train acc: 51.59% | Val loss: 0.8191 | Val acc: 59.26% | LR: 0.000027
Epoch: 127 | MCC: 0.024391 | Train loss: 0.9647 | Train acc: 51.57% | Val loss: 0.8192 | Val acc: 59.26% | LR: 0.000025
Epoch: 128 | MCC: 0.024937 | Train loss: 0.9657 | Train acc: 51.57% | Val loss: 0.8196 | Val acc: 59.29% | LR: 0.000023
Epoch: 129 | MCC: 0.024391 | Train loss: 0.9649 | Train acc: 51.60% | Val loss: 0.8195 | Val acc: 59.26% | LR: 0.000021
Epoch: 130 | MCC: 0.024937 | Train loss: 0.9645 | Train acc: 51.66% | Val loss: 0.8195 | Val acc: 59.29% | LR: 0.000019
Epoch: 131 | MCC: 0.024323 | Train loss: 0.9647 | Train acc: 51.64% | Val loss: 0.8197 | Val acc: 59.24% | LR: 0.000017
Epoch: 132 | MCC: 0.024391 | Train loss: 0.9658 | Train acc: 51.63% | Val loss: 0.8198 | Val acc: 59.26% | LR: 0.000015
Epoch: 133 | MCC: 0.024391 | Train loss: 0.9641 | Train acc: 51.60% | Val loss: 0.8200 | Val acc: 59.26% | LR: 0.000014
Epoch: 134 | MCC: 0.024323 | Train loss: 0.9646 | Train acc: 51.64% | Val loss: 0.8198 | Val acc: 59.24% | LR: 0.000012
Epoch: 135 | MCC: 0.024391 | Train loss: 0.9641 | Train acc: 51.67% | Val loss: 0.8196 | Val acc: 59.26% | LR: 0.000011
Epoch: 136 | MCC: 0.024937 | Train loss: 0.9663 | Train acc: 51.51% | Val loss: 0.8195 | Val acc: 59.29% | LR: 0.000009
Epoch: 137 | MCC: 0.024323 | Train loss: 0.9643 | Train acc: 51.65% | Val loss: 0.8196 | Val acc: 59.24% | LR: 0.000008
Epoch: 138 | MCC: 0.024937 | Train loss: 0.9628 | Train acc: 51.74% | Val loss: 0.8196 | Val acc: 59.29% | LR: 0.000007
Epoch: 139 | MCC: 0.024937 | Train loss: 0.9662 | Train acc: 51.58% | Val loss: 0.8196 | Val acc: 59.29% | LR: 0.000006
Epoch: 140 | MCC: 0.024937 | Train loss: 0.9652 | Train acc: 51.67% | Val loss: 0.8197 | Val acc: 59.29% | LR: 0.000005
Epoch: 141 | MCC: 0.024937 | Train loss: 0.9657 | Train acc: 51.52% | Val loss: 0.8196 | Val acc: 59.29% | LR: 0.000004
Epoch: 142 | MCC: 0.024163 | Train loss: 0.9651 | Train acc: 51.59% | Val loss: 0.8197 | Val acc: 59.24% | LR: 0.000003
Epoch: 143 | MCC: 0.024391 | Train loss: 0.9629 | Train acc: 51.70% | Val loss: 0.8196 | Val acc: 59.26% | LR: 0.000003
Epoch: 144 | MCC: 0.024391 | Train loss: 0.9639 | Train acc: 51.72% | Val loss: 0.8195 | Val acc: 59.26% | LR: 0.000002
Epoch: 145 | MCC: 0.024937 | Train loss: 0.9644 | Train acc: 51.62% | Val loss: 0.8196 | Val acc: 59.29% | LR: 0.000002
Epoch: 146 | MCC: 0.024937 | Train loss: 0.9655 | Train acc: 51.49% | Val loss: 0.8196 | Val acc: 59.29% | LR: 0.000001
Epoch: 147 | MCC: 0.024937 | Train loss: 0.9648 | Train acc: 51.57% | Val loss: 0.8196 | Val acc: 59.29% | LR: 0.000001
Epoch: 148 | MCC: 0.024937 | Train loss: 0.9646 | Train acc: 51.61% | Val loss: 0.8196 | Val acc: 59.29% | LR: 0.000001
Epoch: 149 | MCC: 0.024937 | Train loss: 0.9653 | Train acc: 51.59% | Val loss: 0.8196 | Val acc: 59.29% | LR: 0.000001

[I 2025-10-05 10:33:15,747] Trial 56 finished with value: 0.024937394075095654 and parameters: {'lr': 0.0004578110865748036, 'hidden_size': 67, 'dropout': 0.26890276881661773, 'weight_decay': 0.012405068902832434}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.030978 | Train loss: 1.0030 | Train acc: 49.36% | Val loss: 1.0005 | Val acc: 47.24% | LR: 0.000119
Epoch: 001 | MCC: 0.044160 | Train loss: 1.0013 | Train acc: 49.28% | Val loss: 1.0010 | Val acc: 47.36% | LR: 0.000119
Epoch: 002 | MCC: 0.036907 | Train loss: 1.0001 | Train acc: 49.76% | Val loss: 1.0017 | Val acc: 46.85% | LR: 0.000119
Epoch: 003 | MCC: 0.041342 | Train loss: 1.0000 | Train acc: 50.14% | Val loss: 1.0043 | Val acc: 47.66% | LR: 0.000119
Epoch: 004 | MCC: 0.045828 | Train loss: 0.9995 | Train acc: 50.47% | Val loss: 0.9997 | Val acc: 48.24% | LR: 0.000119
Epoch: 005 | MCC: 0.027626 | Train loss: 0.9983 | Train acc: 50.66% | Val loss: 1.0004 | Val acc: 48.20% | LR: 0.000118
Epoch: 006 | MCC: 0.056415 | Train loss: 0.9984 | Train acc: 50.56% | Val loss: 0.9989 | Val acc: 48.67% | LR: 0.000118
Epoch: 007 | MCC: 0.054862 | Train loss: 0.9973 | Train acc: 50.88% | Val loss: 0.9999 | Val acc: 49.03% | LR: 0.000118
Epoch: 008 | MCC: 0.030508 | Train loss: 0.9972 | Train acc: 50.75% | Val loss: 1.0009 | Val acc: 47.30% | LR: 0.000118
Epoch: 009 | MCC: 0.035768 | Train loss: 0.9967 | Train acc: 50.73% | Val loss: 1.0053 | Val acc: 46.45% | LR: 0.000118
Epoch: 010 | MCC: 0.042565 | Train loss: 0.9967 | Train acc: 50.74% | Val loss: 1.0006 | Val acc: 47.63% | LR: 0.000117
Epoch: 011 | MCC: 0.054262 | Train loss: 0.9953 | Train acc: 50.73% | Val loss: 0.9996 | Val acc: 47.85% | LR: 0.000117
Epoch: 012 | MCC: 0.046560 | Train loss: 0.9940 | Train acc: 50.77% | Val loss: 1.0016 | Val acc: 47.26% | LR: 0.000117
Epoch: 013 | MCC: 0.045997 | Train loss: 0.9931 | Train acc: 50.72% | Val loss: 0.9994 | Val acc: 47.36% | LR: 0.000116
Epoch: 014 | MCC: 0.041606 | Train loss: 0.9947 | Train acc: 50.73% | Val loss: 0.9992 | Val acc: 47.21% | LR: 0.000116
Epoch: 015 | MCC: 0.060256 | Train loss: 0.9927 | Train acc: 50.70% | Val loss: 0.9997 | Val acc: 48.21% | LR: 0.000116
Epoch: 016 | MCC: 0.062169 | Train loss: 0.9925 | Train acc: 50.66% | Val loss: 0.9990 | Val acc: 49.08% | LR: 0.000115
Epoch: 017 | MCC: 0.058756 | Train loss: 0.9895 | Train acc: 50.78% | Val loss: 1.0000 | Val acc: 48.65% | LR: 0.000115
Epoch: 018 | MCC: 0.047211 | Train loss: 0.9910 | Train acc: 50.74% | Val loss: 0.9998 | Val acc: 48.97% | LR: 0.000114
Epoch: 019 | MCC: 0.051425 | Train loss: 0.9919 | Train acc: 50.57% | Val loss: 0.9997 | Val acc: 49.48% | LR: 0.000114
Epoch: 020 | MCC: 0.049208 | Train loss: 0.9902 | Train acc: 50.74% | Val loss: 0.9986 | Val acc: 49.55% | LR: 0.000113
Epoch: 021 | MCC: 0.051983 | Train loss: 0.9902 | Train acc: 50.60% | Val loss: 0.9991 | Val acc: 49.93% | LR: 0.000113
Epoch: 022 | MCC: 0.049206 | Train loss: 0.9884 | Train acc: 50.84% | Val loss: 1.0079 | Val acc: 50.11% | LR: 0.000112
Epoch: 023 | MCC: 0.042374 | Train loss: 0.9901 | Train acc: 50.64% | Val loss: 0.9966 | Val acc: 50.63% | LR: 0.000112
Epoch: 024 | MCC: 0.044822 | Train loss: 0.9913 | Train acc: 50.69% | Val loss: 0.9955 | Val acc: 51.00% | LR: 0.000111
Epoch: 025 | MCC: 0.055233 | Train loss: 0.9915 | Train acc: 50.73% | Val loss: 0.9964 | Val acc: 51.87% | LR: 0.000110
Epoch: 026 | MCC: 0.058996 | Train loss: 0.9881 | Train acc: 50.92% | Val loss: 0.9937 | Val acc: 52.49% | LR: 0.000110
Epoch: 027 | MCC: 0.059193 | Train loss: 0.9885 | Train acc: 50.86% | Val loss: 0.9933 | Val acc: 52.43% | LR: 0.000109
Epoch: 028 | MCC: 0.062460 | Train loss: 0.9885 | Train acc: 50.83% | Val loss: 0.9925 | Val acc: 52.63% | LR: 0.000108
Epoch: 029 | MCC: 0.064224 | Train loss: 0.9883 | Train acc: 50.74% | Val loss: 0.9913 | Val acc: 53.04% | LR: 0.000108
Epoch: 030 | MCC: 0.060098 | Train loss: 0.9877 | Train acc: 50.81% | Val loss: 0.9904 | Val acc: 53.33% | LR: 0.000107
Epoch: 031 | MCC: 0.053703 | Train loss: 0.9871 | Train acc: 50.85% | Val loss: 0.9891 | Val acc: 53.67% | LR: 0.000106
Epoch: 032 | MCC: 0.046939 | Train loss: 0.9876 | Train acc: 50.79% | Val loss: 0.9879 | Val acc: 53.55% | LR: 0.000105
Epoch: 033 | MCC: 0.045556 | Train loss: 0.9879 | Train acc: 50.76% | Val loss: 0.9867 | Val acc: 53.96% | LR: 0.000105
Epoch: 034 | MCC: 0.045902 | Train loss: 0.9865 | Train acc: 50.85% | Val loss: 0.9852 | Val acc: 54.11% | LR: 0.000104
Epoch: 035 | MCC: 0.042281 | Train loss: 0.9866 | Train acc: 50.75% | Val loss: 0.9835 | Val acc: 54.22% | LR: 0.000103
Epoch: 036 | MCC: 0.044362 | Train loss: 0.9858 | Train acc: 50.84% | Val loss: 0.9825 | Val acc: 54.39% | LR: 0.000102
Epoch: 037 | MCC: 0.041715 | Train loss: 0.9846 | Train acc: 50.95% | Val loss: 0.9809 | Val acc: 54.45% | LR: 0.000101
Epoch: 038 | MCC: 0.042101 | Train loss: 0.9860 | Train acc: 50.81% | Val loss: 0.9796 | Val acc: 54.51% | LR: 0.000100
Epoch: 039 | MCC: 0.044797 | Train loss: 0.9842 | Train acc: 50.94% | Val loss: 0.9782 | Val acc: 54.70% | LR: 0.000099
Epoch: 040 | MCC: 0.047373 | Train loss: 0.9846 | Train acc: 50.91% | Val loss: 0.9774 | Val acc: 54.79% | LR: 0.000098
Epoch: 041 | MCC: 0.047226 | Train loss: 0.9848 | Train acc: 50.93% | Val loss: 0.9757 | Val acc: 54.86% | LR: 0.000097
Epoch: 042 | MCC: 0.045773 | Train loss: 0.9842 | Train acc: 51.03% | Val loss: 0.9746 | Val acc: 54.79% | LR: 0.000097
Epoch: 043 | MCC: 0.041483 | Train loss: 0.9855 | Train acc: 50.90% | Val loss: 0.9722 | Val acc: 54.70% | LR: 0.000096
Epoch: 044 | MCC: 0.044206 | Train loss: 0.9847 | Train acc: 50.93% | Val loss: 0.9705 | Val acc: 54.93% | LR: 0.000095
Epoch: 045 | MCC: 0.042876 | Train loss: 0.9848 | Train acc: 51.01% | Val loss: 0.9684 | Val acc: 55.15% | LR: 0.000094
Epoch: 046 | MCC: 0.040299 | Train loss: 0.9854 | Train acc: 51.02% | Val loss: 0.9670 | Val acc: 55.30% | LR: 0.000093
Epoch: 047 | MCC: 0.035221 | Train loss: 0.9846 | Train acc: 51.00% | Val loss: 0.9649 | Val acc: 55.38% | LR: 0.000092
Epoch: 048 | MCC: 0.031483 | Train loss: 0.9830 | Train acc: 50.98% | Val loss: 0.9630 | Val acc: 55.57% | LR: 0.000090
Epoch: 049 | MCC: 0.034085 | Train loss: 0.9839 | Train acc: 51.00% | Val loss: 0.9611 | Val acc: 55.70% | LR: 0.000089
Epoch: 050 | MCC: 0.036127 | Train loss: 0.9851 | Train acc: 50.84% | Val loss: 0.9593 | Val acc: 55.83% | LR: 0.000088
Epoch: 051 | MCC: 0.035412 | Train loss: 0.9844 | Train acc: 50.94% | Val loss: 0.9586 | Val acc: 55.75% | LR: 0.000087
Epoch: 052 | MCC: 0.035331 | Train loss: 0.9832 | Train acc: 51.03% | Val loss: 0.9563 | Val acc: 55.88% | LR: 0.000086
Epoch: 053 | MCC: 0.038712 | Train loss: 0.9838 | Train acc: 50.89% | Val loss: 0.9541 | Val acc: 56.35% | LR: 0.000085
Epoch: 054 | MCC: 0.040255 | Train loss: 0.9835 | Train acc: 50.90% | Val loss: 0.9525 | Val acc: 56.46% | LR: 0.000084
Epoch: 055 | MCC: 0.035016 | Train loss: 0.9850 | Train acc: 50.73% | Val loss: 0.9500 | Val acc: 56.25% | LR: 0.000083
Epoch: 056 | MCC: 0.038663 | Train loss: 0.9839 | Train acc: 50.83% | Val loss: 0.9467 | Val acc: 56.56% | LR: 0.000082
Epoch: 057 | MCC: 0.035203 | Train loss: 0.9826 | Train acc: 50.85% | Val loss: 0.9459 | Val acc: 56.50% | LR: 0.000080
Epoch: 058 | MCC: 0.032659 | Train loss: 0.9826 | Train acc: 50.97% | Val loss: 0.9437 | Val acc: 56.50% | LR: 0.000079
Epoch: 059 | MCC: 0.024717 | Train loss: 0.9815 | Train acc: 50.92% | Val loss: 0.9468 | Val acc: 56.36% | LR: 0.000078
Epoch: 060 | MCC: 0.027520 | Train loss: 0.9829 | Train acc: 50.95% | Val loss: 0.9409 | Val acc: 56.47% | LR: 0.000077
Epoch: 061 | MCC: 0.031683 | Train loss: 0.9831 | Train acc: 50.99% | Val loss: 0.9387 | Val acc: 56.73% | LR: 0.000076
Epoch: 062 | MCC: 0.036219 | Train loss: 0.9833 | Train acc: 50.93% | Val loss: 0.9384 | Val acc: 56.86% | LR: 0.000075
Epoch: 063 | MCC: 0.034673 | Train loss: 0.9816 | Train acc: 50.91% | Val loss: 0.9400 | Val acc: 56.82% | LR: 0.000073
Epoch: 064 | MCC: 0.037713 | Train loss: 0.9897 | Train acc: 50.92% | Val loss: 0.9370 | Val acc: 56.97% | LR: 0.000072
Epoch: 065 | MCC: 0.037314 | Train loss: 1.0252 | Train acc: 50.85% | Val loss: 0.9354 | Val acc: 56.95% | LR: 0.000071
Epoch: 066 | MCC: 0.035610 | Train loss: 1.0002 | Train acc: 51.03% | Val loss: 0.9344 | Val acc: 56.90% | LR: 0.000070
Epoch: 067 | MCC: 0.040390 | Train loss: 0.9822 | Train acc: 50.94% | Val loss: 0.9321 | Val acc: 57.10% | LR: 0.000069
Epoch: 068 | MCC: 0.035300 | Train loss: 0.9813 | Train acc: 51.03% | Val loss: 0.9506 | Val acc: 56.79% | LR: 0.000067
Epoch: 069 | MCC: 0.031603 | Train loss: 0.9824 | Train acc: 50.97% | Val loss: 0.9372 | Val acc: 56.47% | LR: 0.000066
Epoch: 070 | MCC: 0.026823 | Train loss: 0.9831 | Train acc: 50.90% | Val loss: 0.9364 | Val acc: 56.35% | LR: 0.000065
Epoch: 071 | MCC: 0.025585 | Train loss: 0.9825 | Train acc: 50.86% | Val loss: 0.9402 | Val acc: 56.23% | LR: 0.000064
Epoch: 072 | MCC: 0.024666 | Train loss: 0.9813 | Train acc: 50.98% | Val loss: 0.9409 | Val acc: 56.18% | LR: 0.000062
Epoch: 073 | MCC: 0.023560 | Train loss: 0.9829 | Train acc: 50.83% | Val loss: 0.9349 | Val acc: 56.29% | LR: 0.000061
Epoch: 074 | MCC: 0.023592 | Train loss: 0.9828 | Train acc: 50.81% | Val loss: 0.9339 | Val acc: 56.44% | LR: 0.000060
Epoch: 075 | MCC: 0.022742 | Train loss: 0.9823 | Train acc: 50.90% | Val loss: 0.9322 | Val acc: 56.42% | LR: 0.000059
Epoch: 076 | MCC: 0.027504 | Train loss: 0.9821 | Train acc: 50.85% | Val loss: 0.9308 | Val acc: 56.57% | LR: 0.000057
Epoch: 077 | MCC: 0.026712 | Train loss: 0.9814 | Train acc: 50.84% | Val loss: 0.9288 | Val acc: 56.55% | LR: 0.000056
Epoch: 078 | MCC: 0.026885 | Train loss: 0.9808 | Train acc: 50.90% | Val loss: 0.9283 | Val acc: 56.53% | LR: 0.000055
Epoch: 079 | MCC: 0.027444 | Train loss: 0.9806 | Train acc: 50.91% | Val loss: 0.9272 | Val acc: 56.53% | LR: 0.000054
Epoch: 080 | MCC: 0.030538 | Train loss: 0.9830 | Train acc: 50.83% | Val loss: 0.9304 | Val acc: 56.70% | LR: 0.000053
Epoch: 081 | MCC: 0.033528 | Train loss: 0.9818 | Train acc: 50.86% | Val loss: 0.9260 | Val acc: 56.75% | LR: 0.000051
Epoch: 082 | MCC: 0.032518 | Train loss: 0.9813 | Train acc: 50.84% | Val loss: 0.9239 | Val acc: 56.75% | LR: 0.000050
Epoch: 083 | MCC: 0.033077 | Train loss: 0.9805 | Train acc: 50.93% | Val loss: 0.9229 | Val acc: 56.81% | LR: 0.000049
Epoch: 084 | MCC: 0.032585 | Train loss: 0.9816 | Train acc: 50.89% | Val loss: 0.9220 | Val acc: 56.71% | LR: 0.000048
Epoch: 085 | MCC: 0.031232 | Train loss: 0.9801 | Train acc: 50.96% | Val loss: 0.9208 | Val acc: 56.62% | LR: 0.000046
Epoch: 086 | MCC: 0.032969 | Train loss: 0.9803 | Train acc: 50.91% | Val loss: 0.9195 | Val acc: 56.74% | LR: 0.000045
Epoch: 087 | MCC: 0.031269 | Train loss: 0.9818 | Train acc: 50.87% | Val loss: 0.9193 | Val acc: 56.64% | LR: 0.000044
Epoch: 088 | MCC: 0.027961 | Train loss: 0.9797 | Train acc: 50.99% | Val loss: 0.9190 | Val acc: 56.57% | LR: 0.000043
Epoch: 089 | MCC: 0.027961 | Train loss: 0.9802 | Train acc: 51.05% | Val loss: 0.9172 | Val acc: 56.57% | LR: 0.000042
Epoch: 090 | MCC: 0.030444 | Train loss: 0.9828 | Train acc: 50.80% | Val loss: 0.9158 | Val acc: 56.68% | LR: 0.000041
Epoch: 091 | MCC: 0.030780 | Train loss: 0.9803 | Train acc: 51.01% | Val loss: 0.9154 | Val acc: 56.60% | LR: 0.000039
Epoch: 092 | MCC: 0.032246 | Train loss: 0.9797 | Train acc: 51.03% | Val loss: 0.9152 | Val acc: 56.65% | LR: 0.000038
Epoch: 093 | MCC: 0.032293 | Train loss: 0.9810 | Train acc: 50.84% | Val loss: 0.9140 | Val acc: 56.60% | LR: 0.000037
Epoch: 094 | MCC: 0.031637 | Train loss: 0.9796 | Train acc: 51.02% | Val loss: 0.9134 | Val acc: 56.55% | LR: 0.000036
Epoch: 095 | MCC: 0.031637 | Train loss: 0.9799 | Train acc: 50.99% | Val loss: 0.9131 | Val acc: 56.55% | LR: 0.000035
Epoch: 096 | MCC: 0.031637 | Train loss: 0.9792 | Train acc: 50.95% | Val loss: 0.9119 | Val acc: 56.55% | LR: 0.000034
Epoch: 097 | MCC: 0.028317 | Train loss: 0.9795 | Train acc: 51.08% | Val loss: 0.9114 | Val acc: 56.56% | LR: 0.000033
Epoch: 098 | MCC: 0.032813 | Train loss: 0.9799 | Train acc: 51.02% | Val loss: 0.9110 | Val acc: 56.76% | LR: 0.000032
Epoch: 099 | MCC: 0.035116 | Train loss: 0.9793 | Train acc: 51.01% | Val loss: 0.9105 | Val acc: 57.04% | LR: 0.000030
Epoch: 100 | MCC: 0.035427 | Train loss: 0.9812 | Train acc: 50.97% | Val loss: 0.9093 | Val acc: 57.05% | LR: 0.000029
Epoch: 101 | MCC: 0.030682 | Train loss: 0.9800 | Train acc: 50.98% | Val loss: 0.9092 | Val acc: 56.93% | LR: 0.000028
Epoch: 102 | MCC: 0.034155 | Train loss: 0.9801 | Train acc: 51.00% | Val loss: 0.9084 | Val acc: 57.05% | LR: 0.000027
Epoch: 103 | MCC: 0.035223 | Train loss: 0.9795 | Train acc: 50.99% | Val loss: 0.9073 | Val acc: 57.13% | LR: 0.000026
Epoch: 104 | MCC: 0.042475 | Train loss: 0.9780 | Train acc: 51.10% | Val loss: 0.9074 | Val acc: 57.43% | LR: 0.000025
Epoch: 105 | MCC: 0.045292 | Train loss: 0.9796 | Train acc: 50.98% | Val loss: 0.9066 | Val acc: 57.54% | LR: 0.000024
Epoch: 106 | MCC: 0.047999 | Train loss: 0.9786 | Train acc: 51.15% | Val loss: 0.9062 | Val acc: 57.65% | LR: 0.000023
Epoch: 107 | MCC: 0.053491 | Train loss: 0.9792 | Train acc: 51.02% | Val loss: 0.9057 | Val acc: 57.96% | LR: 0.000022
Epoch: 108 | MCC: 0.053487 | Train loss: 0.9788 | Train acc: 51.07% | Val loss: 0.9057 | Val acc: 58.02% | LR: 0.000021
Epoch: 109 | MCC: 0.052863 | Train loss: 0.9796 | Train acc: 51.15% | Val loss: 0.9055 | Val acc: 57.94% | LR: 0.000020
Epoch: 110 | MCC: 0.044619 | Train loss: 0.9786 | Train acc: 51.00% | Val loss: 0.9052 | Val acc: 57.79% | LR: 0.000020
Epoch: 111 | MCC: 0.050256 | Train loss: 0.9792 | Train acc: 50.98% | Val loss: 0.9043 | Val acc: 57.91% | LR: 0.000019
Epoch: 112 | MCC: 0.051270 | Train loss: 0.9793 | Train acc: 51.05% | Val loss: 0.9038 | Val acc: 57.93% | LR: 0.000018
Epoch: 113 | MCC: 0.050071 | Train loss: 0.9796 | Train acc: 50.91% | Val loss: 0.9032 | Val acc: 57.91% | LR: 0.000017
Epoch: 114 | MCC: 0.047528 | Train loss: 0.9785 | Train acc: 51.07% | Val loss: 0.9025 | Val acc: 57.86% | LR: 0.000016
Epoch: 115 | MCC: 0.048427 | Train loss: 0.9779 | Train acc: 51.06% | Val loss: 0.9024 | Val acc: 57.92% | LR: 0.000015
Epoch: 116 | MCC: 0.060041 | Train loss: 0.9800 | Train acc: 51.02% | Val loss: 0.9026 | Val acc: 58.09% | LR: 0.000015
Epoch: 117 | MCC: 0.059898 | Train loss: 0.9779 | Train acc: 51.04% | Val loss: 0.9018 | Val acc: 58.07% | LR: 0.000014
Epoch: 118 | MCC: 0.059438 | Train loss: 0.9789 | Train acc: 50.91% | Val loss: 0.9015 | Val acc: 58.04% | LR: 0.000013
Epoch: 119 | MCC: 0.059099 | Train loss: 0.9786 | Train acc: 51.09% | Val loss: 0.9015 | Val acc: 58.02% | LR: 0.000012
Epoch: 120 | MCC: 0.059099 | Train loss: 0.9770 | Train acc: 51.03% | Val loss: 0.9012 | Val acc: 58.02% | LR: 0.000012
Epoch: 121 | MCC: 0.059099 | Train loss: 0.9785 | Train acc: 51.04% | Val loss: 0.9009 | Val acc: 58.02% | LR: 0.000011
Epoch: 122 | MCC: 0.060187 | Train loss: 0.9773 | Train acc: 51.17% | Val loss: 0.9004 | Val acc: 58.08% | LR: 0.000010
Epoch: 123 | MCC: 0.060475 | Train loss: 0.9791 | Train acc: 50.95% | Val loss: 0.9002 | Val acc: 58.03% | LR: 0.000010
Epoch: 124 | MCC: 0.060475 | Train loss: 0.9771 | Train acc: 51.03% | Val loss: 0.9000 | Val acc: 58.03% | LR: 0.000009
Epoch: 125 | MCC: 0.060475 | Train loss: 0.9797 | Train acc: 50.92% | Val loss: 0.8998 | Val acc: 58.03% | LR: 0.000008
Epoch: 126 | MCC: 0.060475 | Train loss: 0.9791 | Train acc: 50.97% | Val loss: 0.8997 | Val acc: 58.03% | LR: 0.000008
Epoch: 127 | MCC: 0.061177 | Train loss: 0.9781 | Train acc: 50.98% | Val loss: 0.8995 | Val acc: 58.01% | LR: 0.000007
Epoch: 128 | MCC: 0.061177 | Train loss: 0.9792 | Train acc: 51.09% | Val loss: 0.8995 | Val acc: 58.01% | LR: 0.000007
Epoch: 129 | MCC: 0.061177 | Train loss: 0.9780 | Train acc: 51.04% | Val loss: 0.8993 | Val acc: 58.01% | LR: 0.000006
Epoch: 130 | MCC: 0.049330 | Train loss: 0.9775 | Train acc: 50.96% | Val loss: 0.8992 | Val acc: 57.85% | LR: 0.000006
Epoch: 131 | MCC: 0.049791 | Train loss: 0.9796 | Train acc: 50.89% | Val loss: 0.8991 | Val acc: 57.91% | LR: 0.000005
Epoch: 132 | MCC: 0.049791 | Train loss: 0.9790 | Train acc: 50.96% | Val loss: 0.8989 | Val acc: 57.91% | LR: 0.000005
Epoch: 133 | MCC: 0.049791 | Train loss: 0.9775 | Train acc: 51.11% | Val loss: 0.8989 | Val acc: 57.91% | LR: 0.000004
Epoch: 134 | MCC: 0.048937 | Train loss: 0.9792 | Train acc: 50.99% | Val loss: 0.8987 | Val acc: 57.86% | LR: 0.000004
Epoch: 135 | MCC: 0.048937 | Train loss: 0.9775 | Train acc: 51.11% | Val loss: 0.8985 | Val acc: 57.86% | LR: 0.000004
Epoch: 136 | MCC: 0.048937 | Train loss: 0.9782 | Train acc: 51.13% | Val loss: 0.8985 | Val acc: 57.86% | LR: 0.000003
Epoch: 137 | MCC: 0.048937 | Train loss: 0.9790 | Train acc: 50.96% | Val loss: 0.8985 | Val acc: 57.86% | LR: 0.000003
Epoch: 138 | MCC: 0.048937 | Train loss: 0.9793 | Train acc: 50.95% | Val loss: 0.8985 | Val acc: 57.86% | LR: 0.000003
Epoch: 139 | MCC: 0.049460 | Train loss: 0.9776 | Train acc: 51.17% | Val loss: 0.8984 | Val acc: 57.92% | LR: 0.000002
Epoch: 140 | MCC: 0.050341 | Train loss: 1.0006 | Train acc: 50.88% | Val loss: 0.8984 | Val acc: 57.94% | LR: 0.000002
Epoch: 141 | MCC: 0.050023 | Train loss: 0.9776 | Train acc: 51.11% | Val loss: 0.8984 | Val acc: 57.92% | LR: 0.000002
Epoch: 142 | MCC: 0.050023 | Train loss: 0.9785 | Train acc: 51.05% | Val loss: 0.8984 | Val acc: 57.92% | LR: 0.000002
Epoch: 143 | MCC: 0.050023 | Train loss: 0.9772 | Train acc: 51.04% | Val loss: 0.8984 | Val acc: 57.92% | LR: 0.000001
Epoch: 144 | MCC: 0.050023 | Train loss: 0.9772 | Train acc: 51.08% | Val loss: 0.8983 | Val acc: 57.92% | LR: 0.000001
Epoch: 145 | MCC: 0.048566 | Train loss: 0.9779 | Train acc: 50.94% | Val loss: 0.8983 | Val acc: 57.95% | LR: 0.000001
Epoch: 146 | MCC: 0.048566 | Train loss: 0.9782 | Train acc: 51.01% | Val loss: 0.8983 | Val acc: 57.95% | LR: 0.000001
Epoch: 147 | MCC: 0.048566 | Train loss: 0.9784 | Train acc: 51.08% | Val loss: 0.8983 | Val acc: 57.95% | LR: 0.000001
Epoch: 148 | MCC: 0.048566 | Train loss: 0.9792 | Train acc: 51.05% | Val loss: 0.8983 | Val acc: 57.95% | LR: 0.000001
Epoch: 149 | MCC: 0.048515 | Train loss: 0.9774 | Train acc: 51.09% | Val loss: 0.8982 | Val acc: 57.93% | LR: 0.000001

[I 2025-10-05 10:35:32,329] Trial 57 finished with value: 0.04851490817964077 and parameters: {'lr': 0.00011886624493695217, 'hidden_size': 74, 'dropout': 0.14795887354030055, 'weight_decay': 0.07374355125956891}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.039058 | Train loss: 0.9991 | Train acc: 50.42% | Val loss: 1.0028 | Val acc: 47.66% | LR: 0.000189
Epoch: 001 | MCC: 0.035086 | Train loss: 0.9973 | Train acc: 50.63% | Val loss: 1.0017 | Val acc: 48.28% | LR: 0.000189
Epoch: 002 | MCC: 0.043592 | Train loss: 0.9947 | Train acc: 50.78% | Val loss: 0.9969 | Val acc: 52.18% | LR: 0.000189
Epoch: 003 | MCC: 0.040649 | Train loss: 0.9925 | Train acc: 50.78% | Val loss: 0.9903 | Val acc: 53.35% | LR: 0.000189
Epoch: 004 | MCC: 0.037977 | Train loss: 0.9901 | Train acc: 50.74% | Val loss: 0.9815 | Val acc: 54.32% | LR: 0.000189
Epoch: 005 | MCC: 0.034619 | Train loss: 0.9848 | Train acc: 50.90% | Val loss: 0.9736 | Val acc: 54.47% | LR: 0.000188
Epoch: 006 | MCC: 0.042255 | Train loss: 0.9839 | Train acc: 50.82% | Val loss: 0.9673 | Val acc: 54.80% | LR: 0.000188
Epoch: 007 | MCC: 0.037607 | Train loss: 0.9823 | Train acc: 51.09% | Val loss: 0.9668 | Val acc: 54.58% | LR: 0.000188
Epoch: 008 | MCC: 0.035335 | Train loss: 0.9842 | Train acc: 50.95% | Val loss: 0.9580 | Val acc: 54.80% | LR: 0.000188
Epoch: 009 | MCC: 0.023666 | Train loss: 0.9848 | Train acc: 50.77% | Val loss: 0.9540 | Val acc: 54.58% | LR: 0.000187
Epoch: 010 | MCC: 0.023201 | Train loss: 0.9821 | Train acc: 50.93% | Val loss: 0.9549 | Val acc: 54.55% | LR: 0.000187
Epoch: 011 | MCC: 0.023559 | Train loss: 0.9822 | Train acc: 50.94% | Val loss: 0.9535 | Val acc: 54.66% | LR: 0.000186
Epoch: 012 | MCC: 0.029932 | Train loss: 0.9819 | Train acc: 50.92% | Val loss: 0.9490 | Val acc: 55.22% | LR: 0.000186
Epoch: 013 | MCC: 0.031455 | Train loss: 0.9828 | Train acc: 50.87% | Val loss: 0.9447 | Val acc: 55.31% | LR: 0.000185
Epoch: 014 | MCC: 0.031996 | Train loss: 0.9814 | Train acc: 50.95% | Val loss: 0.9423 | Val acc: 55.44% | LR: 0.000185
Epoch: 015 | MCC: 0.025832 | Train loss: 0.9821 | Train acc: 50.88% | Val loss: 0.9384 | Val acc: 55.23% | LR: 0.000184
Epoch: 016 | MCC: 0.027743 | Train loss: 0.9821 | Train acc: 50.91% | Val loss: 0.9342 | Val acc: 55.43% | LR: 0.000183
Epoch: 017 | MCC: 0.023517 | Train loss: 0.9815 | Train acc: 50.94% | Val loss: 0.9280 | Val acc: 55.43% | LR: 0.000183
Epoch: 018 | MCC: 0.025458 | Train loss: 0.9800 | Train acc: 51.02% | Val loss: 0.9248 | Val acc: 55.56% | LR: 0.000182
Epoch: 019 | MCC: 0.018263 | Train loss: 1.1704 | Train acc: 50.80% | Val loss: 0.9250 | Val acc: 55.39% | LR: 0.000181
Epoch: 020 | MCC: 0.018952 | Train loss: 0.9821 | Train acc: 51.05% | Val loss: 0.9179 | Val acc: 55.42% | LR: 0.000180
Epoch: 021 | MCC: 0.023777 | Train loss: 0.9801 | Train acc: 50.98% | Val loss: 0.9145 | Val acc: 55.93% | LR: 0.000179
Epoch: 022 | MCC: 0.022648 | Train loss: 0.9814 | Train acc: 50.91% | Val loss: 0.9111 | Val acc: 55.88% | LR: 0.000179
Epoch: 023 | MCC: 0.023695 | Train loss: 0.9815 | Train acc: 50.86% | Val loss: 0.9074 | Val acc: 55.94% | LR: 0.000178
Epoch: 024 | MCC: 0.019091 | Train loss: 0.9803 | Train acc: 50.86% | Val loss: 0.9058 | Val acc: 55.89% | LR: 0.000177
Epoch: 025 | MCC: 0.022879 | Train loss: 0.9782 | Train acc: 51.09% | Val loss: 0.9011 | Val acc: 56.22% | LR: 0.000176
Epoch: 026 | MCC: 0.026462 | Train loss: 0.9812 | Train acc: 50.76% | Val loss: 0.8967 | Val acc: 56.72% | LR: 0.000175
Epoch: 027 | MCC: 0.028745 | Train loss: 0.9795 | Train acc: 50.91% | Val loss: 0.8943 | Val acc: 56.83% | LR: 0.000173
Epoch: 028 | MCC: 0.030507 | Train loss: 0.9801 | Train acc: 50.85% | Val loss: 0.8969 | Val acc: 56.85% | LR: 0.000172
Epoch: 029 | MCC: 0.033077 | Train loss: 0.9794 | Train acc: 50.89% | Val loss: 0.8910 | Val acc: 56.76% | LR: 0.000171
Epoch: 030 | MCC: 0.027959 | Train loss: 0.9794 | Train acc: 50.94% | Val loss: 0.8879 | Val acc: 56.71% | LR: 0.000170
Epoch: 031 | MCC: 0.026945 | Train loss: 0.9801 | Train acc: 50.81% | Val loss: 0.8871 | Val acc: 56.96% | LR: 0.000169
Epoch: 032 | MCC: 0.031158 | Train loss: 0.9784 | Train acc: 50.94% | Val loss: 0.8837 | Val acc: 57.08% | LR: 0.000168
Epoch: 033 | MCC: 0.039600 | Train loss: 0.9787 | Train acc: 50.95% | Val loss: 0.8831 | Val acc: 57.53% | LR: 0.000166
Epoch: 034 | MCC: 0.041732 | Train loss: 0.9773 | Train acc: 51.08% | Val loss: 0.8766 | Val acc: 58.11% | LR: 0.000165
Epoch: 035 | MCC: 0.041291 | Train loss: 0.9779 | Train acc: 51.03% | Val loss: 0.8726 | Val acc: 58.49% | LR: 0.000164
Epoch: 036 | MCC: 0.029376 | Train loss: 0.9771 | Train acc: 51.13% | Val loss: 0.8707 | Val acc: 58.50% | LR: 0.000162
Epoch: 037 | MCC: 0.036061 | Train loss: 0.9791 | Train acc: 51.00% | Val loss: 0.8685 | Val acc: 58.28% | LR: 0.000161
Epoch: 038 | MCC: 0.027234 | Train loss: 0.9783 | Train acc: 51.03% | Val loss: 0.8686 | Val acc: 58.23% | LR: 0.000160
Epoch: 039 | MCC: 0.030527 | Train loss: 0.9773 | Train acc: 51.11% | Val loss: 0.8656 | Val acc: 58.26% | LR: 0.000158
Epoch: 040 | MCC: 0.026802 | Train loss: 0.9756 | Train acc: 51.19% | Val loss: 0.8640 | Val acc: 58.04% | LR: 0.000157
Epoch: 041 | MCC: 0.013349 | Train loss: 0.9745 | Train acc: 51.28% | Val loss: 0.8706 | Val acc: 57.19% | LR: 0.000155
Epoch: 042 | MCC: 0.015431 | Train loss: 0.9764 | Train acc: 51.10% | Val loss: 0.8706 | Val acc: 57.36% | LR: 0.000154
Epoch: 043 | MCC: 0.017001 | Train loss: 0.9744 | Train acc: 51.25% | Val loss: 0.8884 | Val acc: 57.21% | LR: 0.000152
Epoch: 044 | MCC: 0.021840 | Train loss: 0.9744 | Train acc: 51.25% | Val loss: 0.8753 | Val acc: 57.74% | LR: 0.000150
Epoch: 045 | MCC: -0.002043 | Train loss: 0.9762 | Train acc: 51.24% | Val loss: 1.0129 | Val acc: 57.39% | LR: 0.000149
Epoch: 046 | MCC: 0.027050 | Train loss: 0.9734 | Train acc: 51.27% | Val loss: 0.8752 | Val acc: 57.82% | LR: 0.000147
Epoch: 047 | MCC: 0.022439 | Train loss: 0.9727 | Train acc: 51.36% | Val loss: 0.8695 | Val acc: 58.05% | LR: 0.000146
Epoch: 048 | MCC: 0.014639 | Train loss: 0.9714 | Train acc: 51.46% | Val loss: 0.8745 | Val acc: 57.64% | LR: 0.000144
Epoch: 049 | MCC: 0.013786 | Train loss: 0.9721 | Train acc: 51.32% | Val loss: 0.8603 | Val acc: 58.30% | LR: 0.000142
Epoch: 050 | MCC: 0.016915 | Train loss: 0.9722 | Train acc: 51.39% | Val loss: 0.8617 | Val acc: 58.30% | LR: 0.000140
Epoch: 051 | MCC: 0.024918 | Train loss: 0.9701 | Train acc: 51.38% | Val loss: 0.8822 | Val acc: 57.81% | LR: 0.000139
Epoch: 052 | MCC: 0.010287 | Train loss: 0.9709 | Train acc: 51.40% | Val loss: 0.8507 | Val acc: 58.52% | LR: 0.000137
Epoch: 053 | MCC: 0.024906 | Train loss: 0.9696 | Train acc: 51.45% | Val loss: 0.9513 | Val acc: 58.05% | LR: 0.000135
Epoch: 054 | MCC: 0.026947 | Train loss: 0.9761 | Train acc: 51.19% | Val loss: 0.8462 | Val acc: 59.45% | LR: 0.000133
Epoch: 055 | MCC: 0.011962 | Train loss: 0.9696 | Train acc: 51.61% | Val loss: 0.8572 | Val acc: 58.39% | LR: 0.000132
Epoch: 056 | MCC: 0.016392 | Train loss: 0.9702 | Train acc: 51.43% | Val loss: 0.8435 | Val acc: 59.13% | LR: 0.000130
Epoch: 057 | MCC: 0.016828 | Train loss: 0.9727 | Train acc: 51.12% | Val loss: 0.8497 | Val acc: 58.49% | LR: 0.000128
Epoch: 058 | MCC: 0.016897 | Train loss: 0.9692 | Train acc: 51.42% | Val loss: 0.8430 | Val acc: 59.25% | LR: 0.000126
Epoch: 059 | MCC: 0.020266 | Train loss: 0.9695 | Train acc: 51.54% | Val loss: 0.8519 | Val acc: 58.57% | LR: 0.000124
Epoch: 060 | MCC: 0.016786 | Train loss: 0.9695 | Train acc: 51.38% | Val loss: 0.8398 | Val acc: 59.34% | LR: 0.000122
Epoch: 061 | MCC: 0.011192 | Train loss: 0.9677 | Train acc: 51.45% | Val loss: 0.8341 | Val acc: 59.73% | LR: 0.000120
Epoch: 062 | MCC: 0.024550 | Train loss: 1.0243 | Train acc: 51.39% | Val loss: 0.8353 | Val acc: 59.49% | LR: 0.000119
Epoch: 063 | MCC: 0.017565 | Train loss: 0.9945 | Train acc: 51.32% | Val loss: 0.8377 | Val acc: 59.60% | LR: 0.000117
Epoch: 064 | MCC: 0.023458 | Train loss: 0.9710 | Train acc: 51.66% | Val loss: 0.8338 | Val acc: 59.71% | LR: 0.000115
Epoch: 065 | MCC: 0.047015 | Train loss: 0.9693 | Train acc: 51.91% | Val loss: 0.8311 | Val acc: 60.01% | LR: 0.000113
Epoch: 066 | MCC: 0.055738 | Train loss: 0.9670 | Train acc: 52.17% | Val loss: 0.8337 | Val acc: 59.85% | LR: 0.000111
Epoch: 067 | MCC: 0.054462 | Train loss: 0.9671 | Train acc: 52.04% | Val loss: 0.8322 | Val acc: 59.68% | LR: 0.000109
Epoch: 068 | MCC: 0.082194 | Train loss: 0.9686 | Train acc: 52.00% | Val loss: 0.8230 | Val acc: 60.24% | LR: 0.000107
Epoch: 069 | MCC: 0.027753 | Train loss: 0.9660 | Train acc: 52.17% | Val loss: 0.8263 | Val acc: 59.64% | LR: 0.000105
Epoch: 070 | MCC: 0.033863 | Train loss: 0.9672 | Train acc: 52.07% | Val loss: 0.8347 | Val acc: 59.34% | LR: 0.000103
Epoch: 071 | MCC: 0.028720 | Train loss: 0.9671 | Train acc: 52.09% | Val loss: 0.8194 | Val acc: 60.22% | LR: 0.000101
Epoch: 072 | MCC: 0.029881 | Train loss: 0.9655 | Train acc: 52.12% | Val loss: 0.8351 | Val acc: 59.05% | LR: 0.000099
Epoch: 073 | MCC: 0.028551 | Train loss: 0.9662 | Train acc: 52.04% | Val loss: 0.8305 | Val acc: 59.32% | LR: 0.000097
Epoch: 074 | MCC: 0.023725 | Train loss: 0.9811 | Train acc: 52.10% | Val loss: 0.8268 | Val acc: 59.35% | LR: 0.000095
Epoch: 075 | MCC: 0.027873 | Train loss: 0.9695 | Train acc: 52.10% | Val loss: 0.8226 | Val acc: 59.79% | LR: 0.000093
Epoch: 076 | MCC: 0.021066 | Train loss: 0.9657 | Train acc: 52.10% | Val loss: 0.8315 | Val acc: 59.33% | LR: 0.000091
Epoch: 077 | MCC: 0.027300 | Train loss: 0.9665 | Train acc: 52.09% | Val loss: 0.8328 | Val acc: 59.13% | LR: 0.000089
Epoch: 078 | MCC: 0.031096 | Train loss: 0.9642 | Train acc: 52.15% | Val loss: 0.8306 | Val acc: 59.35% | LR: 0.000087
Epoch: 079 | MCC: 0.034289 | Train loss: 0.9673 | Train acc: 52.03% | Val loss: 0.8278 | Val acc: 59.64% | LR: 0.000085
Epoch: 080 | MCC: 0.023314 | Train loss: 0.9654 | Train acc: 52.16% | Val loss: 0.8280 | Val acc: 59.56% | LR: 0.000083
Epoch: 081 | MCC: 0.031516 | Train loss: 0.9643 | Train acc: 52.20% | Val loss: 0.8272 | Val acc: 59.59% | LR: 0.000081
Epoch: 082 | MCC: 0.034397 | Train loss: 0.9629 | Train acc: 52.30% | Val loss: 0.8279 | Val acc: 59.57% | LR: 0.000079
Epoch: 083 | MCC: 0.028775 | Train loss: 0.9653 | Train acc: 52.10% | Val loss: 0.8430 | Val acc: 58.81% | LR: 0.000077
Epoch: 084 | MCC: 0.025689 | Train loss: 0.9767 | Train acc: 52.05% | Val loss: 0.8270 | Val acc: 59.44% | LR: 0.000076
Epoch: 085 | MCC: 0.021690 | Train loss: 0.9655 | Train acc: 52.14% | Val loss: 0.8250 | Val acc: 59.63% | LR: 0.000074
Epoch: 086 | MCC: 0.029572 | Train loss: 0.9651 | Train acc: 52.21% | Val loss: 0.8316 | Val acc: 59.08% | LR: 0.000072
Epoch: 087 | MCC: 0.032989 | Train loss: 0.9640 | Train acc: 52.13% | Val loss: 0.8287 | Val acc: 59.40% | LR: 0.000070
Epoch: 088 | MCC: 0.025118 | Train loss: 0.9642 | Train acc: 52.19% | Val loss: 0.8308 | Val acc: 59.15% | LR: 0.000068
Epoch: 089 | MCC: 0.026574 | Train loss: 0.9643 | Train acc: 52.28% | Val loss: 0.8289 | Val acc: 59.37% | LR: 0.000066
Epoch: 090 | MCC: 0.019007 | Train loss: 0.9635 | Train acc: 52.23% | Val loss: 0.8338 | Val acc: 58.92% | LR: 0.000064
Epoch: 091 | MCC: 0.020180 | Train loss: 0.9640 | Train acc: 52.21% | Val loss: 0.8294 | Val acc: 59.17% | LR: 0.000062
Epoch: 092 | MCC: 0.044540 | Train loss: 0.9641 | Train acc: 52.18% | Val loss: 0.8326 | Val acc: 59.02% | LR: 0.000060
Epoch: 093 | MCC: 0.041852 | Train loss: 0.9648 | Train acc: 52.31% | Val loss: 0.8291 | Val acc: 59.12% | LR: 0.000059
Epoch: 094 | MCC: 0.044311 | Train loss: 0.9632 | Train acc: 52.31% | Val loss: 0.8291 | Val acc: 59.29% | LR: 0.000057
Epoch: 095 | MCC: 0.027395 | Train loss: 0.9630 | Train acc: 52.31% | Val loss: 0.8349 | Val acc: 58.69% | LR: 0.000055
Epoch: 096 | MCC: 0.046675 | Train loss: 0.9627 | Train acc: 52.28% | Val loss: 0.8328 | Val acc: 59.00% | LR: 0.000053
Epoch: 097 | MCC: 0.037822 | Train loss: 0.9635 | Train acc: 52.24% | Val loss: 0.8304 | Val acc: 59.19% | LR: 0.000052
Epoch: 098 | MCC: 0.045937 | Train loss: 0.9634 | Train acc: 52.25% | Val loss: 0.8312 | Val acc: 59.22% | LR: 0.000050
Epoch: 099 | MCC: 0.037453 | Train loss: 0.9626 | Train acc: 52.26% | Val loss: 0.8280 | Val acc: 59.22% | LR: 0.000048
Epoch: 100 | MCC: 0.031607 | Train loss: 0.9635 | Train acc: 52.34% | Val loss: 0.8340 | Val acc: 58.72% | LR: 0.000046
Epoch: 101 | MCC: 0.048236 | Train loss: 0.9667 | Train acc: 52.24% | Val loss: 0.8276 | Val acc: 59.34% | LR: 0.000045
Epoch: 102 | MCC: 0.039408 | Train loss: 0.9631 | Train acc: 52.26% | Val loss: 0.8326 | Val acc: 58.80% | LR: 0.000043
Epoch: 103 | MCC: 0.036025 | Train loss: 0.9634 | Train acc: 52.30% | Val loss: 0.8271 | Val acc: 59.19% | LR: 0.000041
Epoch: 104 | MCC: 0.024505 | Train loss: 0.9640 | Train acc: 52.20% | Val loss: 0.8341 | Val acc: 58.67% | LR: 0.000040
Epoch: 105 | MCC: 0.031769 | Train loss: 0.9617 | Train acc: 52.31% | Val loss: 0.8281 | Val acc: 59.14% | LR: 0.000038
Epoch: 106 | MCC: 0.040567 | Train loss: 0.9611 | Train acc: 52.33% | Val loss: 0.8295 | Val acc: 59.23% | LR: 0.000037
Epoch: 107 | MCC: 0.038236 | Train loss: 0.9631 | Train acc: 52.22% | Val loss: 0.8309 | Val acc: 59.03% | LR: 0.000035
Epoch: 108 | MCC: 0.043529 | Train loss: 0.9630 | Train acc: 52.24% | Val loss: 0.8298 | Val acc: 59.33% | LR: 0.000034
Epoch: 109 | MCC: 0.036469 | Train loss: 0.9630 | Train acc: 52.26% | Val loss: 0.8322 | Val acc: 58.97% | LR: 0.000032
Epoch: 110 | MCC: 0.034134 | Train loss: 0.9620 | Train acc: 52.27% | Val loss: 0.8278 | Val acc: 59.16% | LR: 0.000031
Epoch: 111 | MCC: 0.040601 | Train loss: 0.9609 | Train acc: 52.31% | Val loss: 0.8291 | Val acc: 59.21% | LR: 0.000029
Epoch: 112 | MCC: 0.034914 | Train loss: 0.9625 | Train acc: 52.30% | Val loss: 0.8285 | Val acc: 59.16% | LR: 0.000028
Epoch: 113 | MCC: 0.039099 | Train loss: 0.9613 | Train acc: 52.30% | Val loss: 0.8353 | Val acc: 58.94% | LR: 0.000027
Epoch: 114 | MCC: 0.033169 | Train loss: 0.9620 | Train acc: 52.32% | Val loss: 0.8304 | Val acc: 59.01% | LR: 0.000025
Epoch: 115 | MCC: 0.037259 | Train loss: 0.9608 | Train acc: 52.34% | Val loss: 0.8285 | Val acc: 59.19% | LR: 0.000024
Epoch: 116 | MCC: 0.033239 | Train loss: 0.9613 | Train acc: 52.31% | Val loss: 0.8307 | Val acc: 59.01% | LR: 0.000023
Epoch: 117 | MCC: 0.038801 | Train loss: 0.9614 | Train acc: 52.35% | Val loss: 0.8293 | Val acc: 59.13% | LR: 0.000021
Epoch: 118 | MCC: 0.034918 | Train loss: 0.9628 | Train acc: 52.23% | Val loss: 0.8296 | Val acc: 59.11% | LR: 0.000020
Epoch: 119 | MCC: 0.036663 | Train loss: 0.9660 | Train acc: 52.24% | Val loss: 0.8275 | Val acc: 59.31% | LR: 0.000019
Epoch: 120 | MCC: 0.034989 | Train loss: 0.9615 | Train acc: 52.34% | Val loss: 0.8298 | Val acc: 59.11% | LR: 0.000018
Epoch: 121 | MCC: 0.035007 | Train loss: 0.9622 | Train acc: 52.27% | Val loss: 0.8293 | Val acc: 59.14% | LR: 0.000017
Epoch: 122 | MCC: 0.036294 | Train loss: 0.9755 | Train acc: 52.28% | Val loss: 0.8278 | Val acc: 59.26% | LR: 0.000016
Epoch: 123 | MCC: 0.032562 | Train loss: 0.9650 | Train acc: 52.30% | Val loss: 0.8275 | Val acc: 59.18% | LR: 0.000015
Epoch: 124 | MCC: 0.034777 | Train loss: 0.9608 | Train acc: 52.27% | Val loss: 0.8296 | Val acc: 59.11% | LR: 0.000014
Epoch: 125 | MCC: 0.036317 | Train loss: 0.9612 | Train acc: 52.39% | Val loss: 0.8292 | Val acc: 59.23% | LR: 0.000013
Epoch: 126 | MCC: 0.036341 | Train loss: 0.9611 | Train acc: 52.35% | Val loss: 0.8296 | Val acc: 59.17% | LR: 0.000012
Epoch: 127 | MCC: 0.033238 | Train loss: 0.9599 | Train acc: 52.40% | Val loss: 0.8290 | Val acc: 59.09% | LR: 0.000011
Epoch: 128 | MCC: 0.034580 | Train loss: 0.9619 | Train acc: 52.25% | Val loss: 0.8285 | Val acc: 59.14% | LR: 0.000010
Epoch: 129 | MCC: 0.034667 | Train loss: 0.9600 | Train acc: 52.40% | Val loss: 0.8287 | Val acc: 59.16% | LR: 0.000009
Epoch: 130 | MCC: 0.034667 | Train loss: 0.9614 | Train acc: 52.29% | Val loss: 0.8288 | Val acc: 59.16% | LR: 0.000008
Epoch: 131 | MCC: 0.034280 | Train loss: 0.9598 | Train acc: 52.44% | Val loss: 0.8283 | Val acc: 59.14% | LR: 0.000008
Epoch: 132 | MCC: 0.035088 | Train loss: 0.9696 | Train acc: 52.21% | Val loss: 0.8285 | Val acc: 59.16% | LR: 0.000007
Epoch: 133 | MCC: 0.035896 | Train loss: 0.9613 | Train acc: 52.39% | Val loss: 0.8277 | Val acc: 59.23% | LR: 0.000006
Epoch: 134 | MCC: 0.035916 | Train loss: 0.9602 | Train acc: 52.37% | Val loss: 0.8287 | Val acc: 59.18% | LR: 0.000006
Epoch: 135 | MCC: 0.034846 | Train loss: 0.9618 | Train acc: 52.34% | Val loss: 0.8288 | Val acc: 59.14% | LR: 0.000005
Epoch: 136 | MCC: 0.035088 | Train loss: 0.9606 | Train acc: 52.33% | Val loss: 0.8284 | Val acc: 59.16% | LR: 0.000004
Epoch: 137 | MCC: 0.035896 | Train loss: 0.9606 | Train acc: 52.31% | Val loss: 0.8283 | Val acc: 59.23% | LR: 0.000004
Epoch: 138 | MCC: 0.035320 | Train loss: 0.9614 | Train acc: 52.36% | Val loss: 0.8290 | Val acc: 59.16% | LR: 0.000003
Epoch: 139 | MCC: 0.034634 | Train loss: 0.9603 | Train acc: 52.38% | Val loss: 0.8288 | Val acc: 59.14% | LR: 0.000003
Epoch: 140 | MCC: 0.036614 | Train loss: 0.9599 | Train acc: 52.39% | Val loss: 0.8287 | Val acc: 59.17% | LR: 0.000003
Epoch: 141 | MCC: 0.036614 | Train loss: 2.5198 | Train acc: 52.28% | Val loss: 0.8284 | Val acc: 59.17% | LR: 0.000002
Epoch: 142 | MCC: 0.036614 | Train loss: 0.9602 | Train acc: 52.36% | Val loss: 0.8285 | Val acc: 59.17% | LR: 0.000002
Epoch: 143 | MCC: 0.037229 | Train loss: 0.9591 | Train acc: 52.43% | Val loss: 0.8287 | Val acc: 59.19% | LR: 0.000002
Epoch: 144 | MCC: 0.037229 | Train loss: 0.9602 | Train acc: 52.42% | Val loss: 0.8286 | Val acc: 59.19% | LR: 0.000002
Epoch: 145 | MCC: 0.037229 | Train loss: 0.9608 | Train acc: 52.36% | Val loss: 0.8285 | Val acc: 59.19% | LR: 0.000001

[I 2025-10-05 10:37:47,190] Trial 58 finished with value: 0.03722886985633522 and parameters: {'lr': 0.0001892153010060451, 'hidden_size': 81, 'dropout': 0.18716001487017814, 'weight_decay': 0.009530428516320839}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.034883 | Train loss: 1.0093 | Train acc: 49.90% | Val loss: 0.9921 | Val acc: 55.37% | LR: 0.000384
Epoch: 001 | MCC: 0.028923 | Train loss: 1.0048 | Train acc: 50.32% | Val loss: 0.9772 | Val acc: 55.00% | LR: 0.000384
Epoch: 002 | MCC: 0.026749 | Train loss: 1.0122 | Train acc: 50.66% | Val loss: 0.9670 | Val acc: 55.00% | LR: 0.000383
Epoch: 003 | MCC: 0.023914 | Train loss: 0.9902 | Train acc: 50.91% | Val loss: 0.9462 | Val acc: 55.15% | LR: 0.000383
Epoch: 004 | MCC: 0.007974 | Train loss: 0.9870 | Train acc: 50.87% | Val loss: 0.9325 | Val acc: 54.90% | LR: 0.000383
Epoch: 005 | MCC: 0.005412 | Train loss: 0.9846 | Train acc: 50.84% | Val loss: 0.9279 | Val acc: 54.90% | LR: 0.000382
Epoch: 006 | MCC: 0.014123 | Train loss: 0.9836 | Train acc: 50.90% | Val loss: 0.9173 | Val acc: 55.67% | LR: 0.000382
Epoch: 007 | MCC: 0.013330 | Train loss: 0.9865 | Train acc: 50.80% | Val loss: 0.9079 | Val acc: 55.81% | LR: 0.000381
Epoch: 008 | MCC: 0.013944 | Train loss: 0.9828 | Train acc: 50.95% | Val loss: 0.9001 | Val acc: 56.16% | LR: 0.000380
Epoch: 009 | MCC: 0.029810 | Train loss: 0.9900 | Train acc: 50.94% | Val loss: 0.8980 | Val acc: 57.34% | LR: 0.000380
Epoch: 010 | MCC: 0.027119 | Train loss: 0.9826 | Train acc: 51.00% | Val loss: 0.8907 | Val acc: 57.41% | LR: 0.000379
Epoch: 011 | MCC: 0.037578 | Train loss: 0.9803 | Train acc: 51.09% | Val loss: 0.8859 | Val acc: 57.82% | LR: 0.000378
Epoch: 012 | MCC: 0.045974 | Train loss: 0.9825 | Train acc: 51.07% | Val loss: 0.8791 | Val acc: 57.91% | LR: 0.000377
Epoch: 013 | MCC: 0.027060 | Train loss: 0.9811 | Train acc: 51.06% | Val loss: 0.8743 | Val acc: 57.18% | LR: 0.000376
Epoch: 014 | MCC: 0.030549 | Train loss: 0.9783 | Train acc: 51.29% | Val loss: 0.8683 | Val acc: 57.38% | LR: 0.000374
Epoch: 015 | MCC: 0.033202 | Train loss: 0.9814 | Train acc: 51.05% | Val loss: 0.8609 | Val acc: 57.97% | LR: 0.000373
Epoch: 016 | MCC: 0.002255 | Train loss: 0.9795 | Train acc: 51.16% | Val loss: 0.8659 | Val acc: 56.91% | LR: 0.000372
Epoch: 017 | MCC: 0.002056 | Train loss: 0.9796 | Train acc: 51.17% | Val loss: 0.8701 | Val acc: 56.96% | LR: 0.000370
Epoch: 018 | MCC: 0.005177 | Train loss: 0.9778 | Train acc: 51.24% | Val loss: 0.8690 | Val acc: 56.93% | LR: 0.000369
Epoch: 019 | MCC: 0.015607 | Train loss: 0.9765 | Train acc: 51.28% | Val loss: 0.8534 | Val acc: 58.30% | LR: 0.000367
Epoch: 020 | MCC: -0.006321 | Train loss: 0.9775 | Train acc: 51.21% | Val loss: 0.8676 | Val acc: 56.81% | LR: 0.000366
Epoch: 021 | MCC: 0.018857 | Train loss: 0.9777 | Train acc: 51.25% | Val loss: 0.8355 | Val acc: 59.08% | LR: 0.000364
Epoch: 022 | MCC: -0.000958 | Train loss: 0.9738 | Train acc: 51.37% | Val loss: 0.8658 | Val acc: 56.64% | LR: 0.000362
Epoch: 023 | MCC: 0.030677 | Train loss: 0.9746 | Train acc: 51.33% | Val loss: 0.8259 | Val acc: 59.71% | LR: 0.000360
Epoch: 024 | MCC: 0.033785 | Train loss: 0.9740 | Train acc: 51.35% | Val loss: 0.8211 | Val acc: 59.67% | LR: 0.000358
Epoch: 025 | MCC: 0.017150 | Train loss: 0.9755 | Train acc: 51.28% | Val loss: 0.8343 | Val acc: 58.37% | LR: 0.000356
Epoch: 026 | MCC: 0.032862 | Train loss: 0.9731 | Train acc: 51.38% | Val loss: 0.8316 | Val acc: 58.95% | LR: 0.000354
Epoch: 027 | MCC: 0.059366 | Train loss: 0.9728 | Train acc: 51.36% | Val loss: 0.8121 | Val acc: 60.06% | LR: 0.000352
Epoch: 028 | MCC: 0.060784 | Train loss: 0.9723 | Train acc: 51.38% | Val loss: 0.8207 | Val acc: 59.40% | LR: 0.000350
Epoch: 029 | MCC: 0.027999 | Train loss: 0.9730 | Train acc: 51.36% | Val loss: 0.8183 | Val acc: 59.46% | LR: 0.000347
Epoch: 030 | MCC: 0.027016 | Train loss: 0.9723 | Train acc: 51.45% | Val loss: 0.8226 | Val acc: 59.29% | LR: 0.000345
Epoch: 031 | MCC: 0.020203 | Train loss: 0.9725 | Train acc: 51.50% | Val loss: 0.8378 | Val acc: 58.37% | LR: 0.000342
Epoch: 032 | MCC: 0.034976 | Train loss: 0.9720 | Train acc: 51.47% | Val loss: 0.8426 | Val acc: 58.20% | LR: 0.000340
Epoch: 033 | MCC: 0.053608 | Train loss: 0.9740 | Train acc: 51.40% | Val loss: 0.8203 | Val acc: 59.57% | LR: 0.000337
Epoch: 034 | MCC: 0.021489 | Train loss: 0.9745 | Train acc: 51.37% | Val loss: 0.8168 | Val acc: 59.57% | LR: 0.000335
Epoch: 035 | MCC: 0.019432 | Train loss: 0.9739 | Train acc: 51.31% | Val loss: 0.8492 | Val acc: 57.95% | LR: 0.000332
Epoch: 036 | MCC: 0.027752 | Train loss: 0.9709 | Train acc: 51.50% | Val loss: 0.8215 | Val acc: 59.41% | LR: 0.000329
Epoch: 037 | MCC: 0.060913 | Train loss: 0.9707 | Train acc: 51.50% | Val loss: 0.8182 | Val acc: 59.64% | LR: 0.000326
Epoch: 038 | MCC: 0.028216 | Train loss: 0.9721 | Train acc: 51.41% | Val loss: 0.8222 | Val acc: 59.29% | LR: 0.000323
Epoch: 039 | MCC: 0.049319 | Train loss: 0.9725 | Train acc: 51.37% | Val loss: 0.8220 | Val acc: 59.14% | LR: 0.000320
Epoch: 040 | MCC: 0.057118 | Train loss: 0.9729 | Train acc: 51.41% | Val loss: 0.8328 | Val acc: 58.81% | LR: 0.000317
Epoch: 041 | MCC: 0.027273 | Train loss: 0.9721 | Train acc: 51.38% | Val loss: 0.8320 | Val acc: 58.79% | LR: 0.000314
Epoch: 042 | MCC: 0.024427 | Train loss: 0.9761 | Train acc: 51.10% | Val loss: 0.8530 | Val acc: 57.47% | LR: 0.000311
Epoch: 043 | MCC: 0.015669 | Train loss: 0.9722 | Train acc: 51.35% | Val loss: 0.8404 | Val acc: 58.29% | LR: 0.000308
Epoch: 044 | MCC: 0.025978 | Train loss: 0.9712 | Train acc: 51.47% | Val loss: 0.8578 | Val acc: 57.49% | LR: 0.000305
Epoch: 045 | MCC: 0.023405 | Train loss: 0.9727 | Train acc: 51.32% | Val loss: 0.8584 | Val acc: 57.38% | LR: 0.000302
Epoch: 046 | MCC: 0.014050 | Train loss: 0.9726 | Train acc: 51.29% | Val loss: 0.8475 | Val acc: 58.04% | LR: 0.000298
Epoch: 047 | MCC: 0.030693 | Train loss: 0.9728 | Train acc: 51.31% | Val loss: 0.8577 | Val acc: 57.42% | LR: 0.000295
Epoch: 048 | MCC: 0.020834 | Train loss: 0.9722 | Train acc: 51.30% | Val loss: 0.8591 | Val acc: 57.54% | LR: 0.000292
Epoch: 049 | MCC: 0.033917 | Train loss: 0.9703 | Train acc: 51.49% | Val loss: 0.8619 | Val acc: 57.19% | LR: 0.000288
Epoch: 050 | MCC: 0.015545 | Train loss: 0.9703 | Train acc: 51.36% | Val loss: 0.8520 | Val acc: 57.79% | LR: 0.000285
Epoch: 051 | MCC: 0.049258 | Train loss: 0.9712 | Train acc: 51.37% | Val loss: 0.8205 | Val acc: 59.41% | LR: 0.000281
Epoch: 052 | MCC: 0.020160 | Train loss: 0.9705 | Train acc: 51.38% | Val loss: 0.8456 | Val acc: 58.18% | LR: 0.000277
Epoch: 053 | MCC: 0.019904 | Train loss: 0.9720 | Train acc: 51.27% | Val loss: 0.8576 | Val acc: 57.56% | LR: 0.000274
Epoch: 054 | MCC: 0.042832 | Train loss: 0.9695 | Train acc: 51.40% | Val loss: 0.8522 | Val acc: 58.00% | LR: 0.000270
Epoch: 055 | MCC: 0.037392 | Train loss: 0.9685 | Train acc: 51.46% | Val loss: 0.8488 | Val acc: 57.96% | LR: 0.000267
Epoch: 056 | MCC: 0.021697 | Train loss: 0.9664 | Train acc: 51.60% | Val loss: 0.8608 | Val acc: 57.36% | LR: 0.000263
Epoch: 057 | MCC: 0.022440 | Train loss: 0.9682 | Train acc: 51.58% | Val loss: 0.8585 | Val acc: 57.29% | LR: 0.000259
Epoch: 058 | MCC: 0.013245 | Train loss: 0.9695 | Train acc: 51.45% | Val loss: 0.8587 | Val acc: 57.36% | LR: 0.000255
Epoch: 059 | MCC: 0.032478 | Train loss: 0.9689 | Train acc: 51.40% | Val loss: 0.8601 | Val acc: 57.40% | LR: 0.000252
Epoch: 060 | MCC: 0.019321 | Train loss: 0.9684 | Train acc: 51.50% | Val loss: 0.8498 | Val acc: 57.95% | LR: 0.000248
Epoch: 061 | MCC: 0.033991 | Train loss: 0.9678 | Train acc: 51.57% | Val loss: 0.8496 | Val acc: 57.91% | LR: 0.000244
Epoch: 062 | MCC: 0.005126 | Train loss: 0.9708 | Train acc: 51.40% | Val loss: 0.8697 | Val acc: 56.61% | LR: 0.000240
Epoch: 063 | MCC: 0.028999 | Train loss: 0.9710 | Train acc: 51.36% | Val loss: 0.8613 | Val acc: 57.28% | LR: 0.000236
Epoch: 064 | MCC: 0.018008 | Train loss: 0.9696 | Train acc: 51.55% | Val loss: 0.8582 | Val acc: 57.54% | LR: 0.000232
Epoch: 065 | MCC: 0.025230 | Train loss: 0.9695 | Train acc: 51.36% | Val loss: 0.8585 | Val acc: 57.49% | LR: 0.000228
Epoch: 066 | MCC: 0.035313 | Train loss: 0.9689 | Train acc: 51.42% | Val loss: 0.8456 | Val acc: 58.14% | LR: 0.000224
Epoch: 067 | MCC: 0.038966 | Train loss: 0.9690 | Train acc: 51.26% | Val loss: 0.8398 | Val acc: 58.55% | LR: 0.000220
Epoch: 068 | MCC: 0.021237 | Train loss: 0.9654 | Train acc: 51.88% | Val loss: 0.8471 | Val acc: 58.02% | LR: 0.000216
Epoch: 069 | MCC: 0.016703 | Train loss: 0.9689 | Train acc: 51.62% | Val loss: 0.8519 | Val acc: 57.68% | LR: 0.000212
Epoch: 070 | MCC: 0.066195 | Train loss: 0.9651 | Train acc: 52.15% | Val loss: 0.8333 | Val acc: 58.81% | LR: 0.000208
Epoch: 071 | MCC: 0.056386 | Train loss: 0.9663 | Train acc: 52.13% | Val loss: 0.8461 | Val acc: 58.06% | LR: 0.000204
Epoch: 072 | MCC: 0.053366 | Train loss: 0.9651 | Train acc: 52.19% | Val loss: 0.8507 | Val acc: 57.73% | LR: 0.000200
Epoch: 073 | MCC: 0.033837 | Train loss: 0.9909 | Train acc: 52.11% | Val loss: 0.8535 | Val acc: 57.74% | LR: 0.000196
Epoch: 074 | MCC: 0.038935 | Train loss: 0.9673 | Train acc: 52.46% | Val loss: 0.8501 | Val acc: 57.91% | LR: 0.000192
Epoch: 075 | MCC: 0.054489 | Train loss: 0.9673 | Train acc: 52.13% | Val loss: 0.8502 | Val acc: 57.92% | LR: 0.000188
Epoch: 076 | MCC: 0.032636 | Train loss: 0.9668 | Train acc: 52.31% | Val loss: 0.8495 | Val acc: 57.88% | LR: 0.000184
Epoch: 077 | MCC: 0.021826 | Train loss: 0.9665 | Train acc: 51.85% | Val loss: 0.8483 | Val acc: 57.98% | LR: 0.000180
Epoch: 078 | MCC: 0.045661 | Train loss: 0.9666 | Train acc: 52.23% | Val loss: 0.8448 | Val acc: 58.12% | LR: 0.000176
Epoch: 079 | MCC: 0.059038 | Train loss: 0.9666 | Train acc: 52.24% | Val loss: 0.8449 | Val acc: 58.20% | LR: 0.000172
Epoch: 080 | MCC: 0.032349 | Train loss: 0.9675 | Train acc: 52.07% | Val loss: 0.8512 | Val acc: 57.86% | LR: 0.000168
Epoch: 081 | MCC: 0.049108 | Train loss: 0.9683 | Train acc: 51.81% | Val loss: 0.8498 | Val acc: 57.86% | LR: 0.000164
Epoch: 082 | MCC: 0.050991 | Train loss: 0.9675 | Train acc: 52.27% | Val loss: 0.8543 | Val acc: 57.77% | LR: 0.000160
Epoch: 083 | MCC: 0.059113 | Train loss: 0.9670 | Train acc: 51.97% | Val loss: 0.8457 | Val acc: 58.19% | LR: 0.000157
Epoch: 084 | MCC: 0.039651 | Train loss: 0.9666 | Train acc: 52.12% | Val loss: 0.8601 | Val acc: 57.34% | LR: 0.000153
Epoch: 085 | MCC: 0.028327 | Train loss: 0.9676 | Train acc: 52.11% | Val loss: 0.8524 | Val acc: 57.67% | LR: 0.000149
Epoch: 086 | MCC: 0.020149 | Train loss: 0.9663 | Train acc: 52.36% | Val loss: 0.8546 | Val acc: 57.51% | LR: 0.000145
Epoch: 087 | MCC: 0.022042 | Train loss: 0.9688 | Train acc: 51.93% | Val loss: 0.8464 | Val acc: 58.08% | LR: 0.000141
Epoch: 088 | MCC: 0.019815 | Train loss: 0.9660 | Train acc: 52.22% | Val loss: 0.8460 | Val acc: 58.05% | LR: 0.000137
Epoch: 089 | MCC: 0.024338 | Train loss: 0.9680 | Train acc: 52.02% | Val loss: 0.8508 | Val acc: 57.84% | LR: 0.000133
Epoch: 090 | MCC: 0.044205 | Train loss: 0.9664 | Train acc: 52.17% | Val loss: 0.8412 | Val acc: 58.20% | LR: 0.000129
Epoch: 091 | MCC: 0.050896 | Train loss: 0.9668 | Train acc: 52.17% | Val loss: 0.8409 | Val acc: 58.26% | LR: 0.000126
Epoch: 092 | MCC: 0.061818 | Train loss: 0.9656 | Train acc: 52.33% | Val loss: 0.8395 | Val acc: 58.25% | LR: 0.000122
Epoch: 093 | MCC: 0.068563 | Train loss: 0.9649 | Train acc: 52.26% | Val loss: 0.8346 | Val acc: 58.74% | LR: 0.000118
Epoch: 094 | MCC: 0.067334 | Train loss: 0.9644 | Train acc: 52.30% | Val loss: 0.8429 | Val acc: 58.22% | LR: 0.000115
Epoch: 095 | MCC: 0.065397 | Train loss: 0.9651 | Train acc: 52.32% | Val loss: 0.8426 | Val acc: 58.18% | LR: 0.000111
Epoch: 096 | MCC: 0.067577 | Train loss: 0.9644 | Train acc: 52.30% | Val loss: 0.8398 | Val acc: 58.37% | LR: 0.000107
Epoch: 097 | MCC: 0.053136 | Train loss: 0.9645 | Train acc: 52.37% | Val loss: 0.8416 | Val acc: 58.33% | LR: 0.000104
Epoch: 098 | MCC: 0.060124 | Train loss: 0.9650 | Train acc: 52.17% | Val loss: 0.8404 | Val acc: 58.36% | LR: 0.000100
Epoch: 099 | MCC: 0.028188 | Train loss: 0.9648 | Train acc: 52.21% | Val loss: 0.8477 | Val acc: 58.01% | LR: 0.000097
Epoch: 100 | MCC: 0.026022 | Train loss: 0.9657 | Train acc: 52.26% | Val loss: 0.8418 | Val acc: 58.26% | LR: 0.000093
Epoch: 101 | MCC: 0.033364 | Train loss: 0.9660 | Train acc: 52.22% | Val loss: 0.8421 | Val acc: 58.36% | LR: 0.000090

[I 2025-10-05 10:39:25,261] Trial 59 finished with value: 0.03089814353734255 and parameters: {'lr': 0.0003837492840926495, 'hidden_size': 87, 'dropout': 0.12821355734512052, 'weight_decay': 0.04516464049311071}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.000000 | Train loss: 1.0004 | Train acc: 50.09% | Val loss: 0.9792 | Val acc: 54.73% | LR: 0.000156
Epoch: 001 | MCC: -0.005484 | Train loss: 1.0003 | Train acc: 50.12% | Val loss: 0.9787 | Val acc: 54.71% | LR: 0.000156
Epoch: 002 | MCC: 0.000000 | Train loss: 0.9999 | Train acc: 50.27% | Val loss: 0.9787 | Val acc: 54.73% | LR: 0.000155
Epoch: 003 | MCC: 0.000000 | Train loss: 0.9994 | Train acc: 50.19% | Val loss: 0.9780 | Val acc: 54.73% | LR: 0.000155
Epoch: 004 | MCC: 0.000000 | Train loss: 0.9988 | Train acc: 50.30% | Val loss: 0.9775 | Val acc: 54.73% | LR: 0.000155
Epoch: 005 | MCC: 0.000000 | Train loss: 0.9986 | Train acc: 50.26% | Val loss: 0.9767 | Val acc: 54.73% | LR: 0.000155
Epoch: 006 | MCC: 0.000000 | Train loss: 0.9979 | Train acc: 50.16% | Val loss: 0.9760 | Val acc: 54.73% | LR: 0.000155
Epoch: 007 | MCC: 0.000000 | Train loss: 0.9975 | Train acc: 50.16% | Val loss: 0.9750 | Val acc: 54.73% | LR: 0.000155
Epoch: 008 | MCC: 0.000000 | Train loss: 0.9966 | Train acc: 50.31% | Val loss: 0.9744 | Val acc: 54.73% | LR: 0.000154
Epoch: 009 | MCC: 0.000000 | Train loss: 0.9965 | Train acc: 50.24% | Val loss: 0.9737 | Val acc: 54.73% | LR: 0.000154
Epoch: 010 | MCC: 0.000000 | Train loss: 0.9961 | Train acc: 50.34% | Val loss: 0.9726 | Val acc: 54.73% | LR: 0.000154
Epoch: 011 | MCC: 0.000000 | Train loss: 0.9957 | Train acc: 50.29% | Val loss: 0.9718 | Val acc: 54.73% | LR: 0.000153
Epoch: 012 | MCC: 0.000000 | Train loss: 0.9961 | Train acc: 50.23% | Val loss: 0.9705 | Val acc: 54.73% | LR: 0.000153
Epoch: 013 | MCC: 0.000000 | Train loss: 0.9957 | Train acc: 50.26% | Val loss: 0.9697 | Val acc: 54.73% | LR: 0.000152
Epoch: 014 | MCC: 0.000000 | Train loss: 0.9942 | Train acc: 50.27% | Val loss: 0.9684 | Val acc: 54.73% | LR: 0.000152
Epoch: 015 | MCC: 0.000000 | Train loss: 0.9937 | Train acc: 50.34% | Val loss: 0.9673 | Val acc: 54.73% | LR: 0.000151
Epoch: 016 | MCC: -0.007020 | Train loss: 0.9938 | Train acc: 50.26% | Val loss: 0.9656 | Val acc: 54.51% | LR: 0.000151
Epoch: 017 | MCC: -0.019597 | Train loss: 0.9936 | Train acc: 50.21% | Val loss: 0.9646 | Val acc: 54.33% | LR: 0.000150
Epoch: 018 | MCC: -0.019452 | Train loss: 0.9949 | Train acc: 50.44% | Val loss: 0.9643 | Val acc: 54.35% | LR: 0.000150
Epoch: 019 | MCC: -0.024211 | Train loss: 0.9954 | Train acc: 50.44% | Val loss: 0.9625 | Val acc: 54.23% | LR: 0.000149
Epoch: 020 | MCC: -0.021653 | Train loss: 0.9942 | Train acc: 50.58% | Val loss: 0.9612 | Val acc: 54.33% | LR: 0.000148
Epoch: 021 | MCC: -0.018614 | Train loss: 0.9937 | Train acc: 50.65% | Val loss: 0.9597 | Val acc: 54.45% | LR: 0.000148
Epoch: 022 | MCC: -0.014153 | Train loss: 0.9941 | Train acc: 50.47% | Val loss: 0.9582 | Val acc: 54.36% | LR: 0.000147
Epoch: 023 | MCC: -0.011554 | Train loss: 0.9923 | Train acc: 50.66% | Val loss: 0.9575 | Val acc: 54.40% | LR: 0.000146
Epoch: 024 | MCC: -0.001484 | Train loss: 0.9908 | Train acc: 51.01% | Val loss: 0.9559 | Val acc: 54.23% | LR: 0.000145
Epoch: 025 | MCC: 0.017439 | Train loss: 0.9922 | Train acc: 50.84% | Val loss: 0.9541 | Val acc: 54.32% | LR: 0.000144
Epoch: 026 | MCC: 0.007454 | Train loss: 0.9933 | Train acc: 51.14% | Val loss: 0.9527 | Val acc: 53.91% | LR: 0.000144
Epoch: 027 | MCC: 0.027217 | Train loss: 0.9994 | Train acc: 51.04% | Val loss: 0.9512 | Val acc: 54.26% | LR: 0.000143
Epoch: 028 | MCC: 0.017110 | Train loss: 0.9924 | Train acc: 50.98% | Val loss: 0.9486 | Val acc: 53.82% | LR: 0.000142
Epoch: 029 | MCC: 0.019315 | Train loss: 0.9913 | Train acc: 51.01% | Val loss: 0.9475 | Val acc: 53.98% | LR: 0.000141
Epoch: 030 | MCC: 0.016066 | Train loss: 0.9915 | Train acc: 50.80% | Val loss: 0.9450 | Val acc: 53.66% | LR: 0.000140
Epoch: 031 | MCC: 0.020315 | Train loss: 0.9909 | Train acc: 50.97% | Val loss: 0.9425 | Val acc: 54.06% | LR: 0.000139
Epoch: 032 | MCC: 0.017065 | Train loss: 0.9894 | Train acc: 50.95% | Val loss: 0.9403 | Val acc: 54.07% | LR: 0.000138
Epoch: 033 | MCC: 0.022379 | Train loss: 0.9898 | Train acc: 50.90% | Val loss: 0.9376 | Val acc: 54.29% | LR: 0.000137
Epoch: 034 | MCC: 0.025568 | Train loss: 0.9893 | Train acc: 50.97% | Val loss: 0.9358 | Val acc: 54.45% | LR: 0.000136
Epoch: 035 | MCC: 0.028849 | Train loss: 0.9903 | Train acc: 51.01% | Val loss: 0.9328 | Val acc: 54.69% | LR: 0.000135
Epoch: 036 | MCC: 0.027904 | Train loss: 0.9898 | Train acc: 50.94% | Val loss: 0.9300 | Val acc: 54.86% | LR: 0.000134
Epoch: 037 | MCC: 0.029265 | Train loss: 0.9876 | Train acc: 51.04% | Val loss: 0.9278 | Val acc: 55.06% | LR: 0.000132
Epoch: 038 | MCC: 0.030529 | Train loss: 1.0115 | Train acc: 50.58% | Val loss: 0.9244 | Val acc: 55.16% | LR: 0.000131
Epoch: 039 | MCC: 0.030733 | Train loss: 1.1135 | Train acc: 50.40% | Val loss: 0.9238 | Val acc: 55.17% | LR: 0.000130
Epoch: 040 | MCC: 0.030265 | Train loss: 1.0330 | Train acc: 50.37% | Val loss: 0.9239 | Val acc: 55.17% | LR: 0.000129
Epoch: 041 | MCC: 0.029203 | Train loss: 0.9959 | Train acc: 50.27% | Val loss: 0.9222 | Val acc: 55.23% | LR: 0.000128
Epoch: 042 | MCC: 0.030938 | Train loss: 1.0340 | Train acc: 50.06% | Val loss: 0.9210 | Val acc: 55.31% | LR: 0.000126
Epoch: 043 | MCC: 0.029610 | Train loss: 1.2115 | Train acc: 50.35% | Val loss: 0.9210 | Val acc: 55.26% | LR: 0.000125
Epoch: 044 | MCC: 0.031622 | Train loss: 0.9966 | Train acc: 50.24% | Val loss: 0.9192 | Val acc: 55.35% | LR: 0.000124
Epoch: 045 | MCC: 0.026996 | Train loss: 1.0679 | Train acc: 50.80% | Val loss: 0.9186 | Val acc: 55.28% | LR: 0.000122
Epoch: 046 | MCC: 0.025499 | Train loss: 1.0121 | Train acc: 50.95% | Val loss: 0.9184 | Val acc: 55.23% | LR: 0.000121
Epoch: 047 | MCC: 0.023879 | Train loss: 0.9930 | Train acc: 51.07% | Val loss: 0.9173 | Val acc: 55.18% | LR: 0.000120
Epoch: 048 | MCC: 0.025257 | Train loss: 0.9908 | Train acc: 51.17% | Val loss: 0.9149 | Val acc: 55.43% | LR: 0.000118
Epoch: 049 | MCC: 0.027042 | Train loss: 0.9886 | Train acc: 51.42% | Val loss: 0.9129 | Val acc: 55.57% | LR: 0.000117
Epoch: 050 | MCC: 0.026712 | Train loss: 0.9870 | Train acc: 51.66% | Val loss: 0.9105 | Val acc: 55.60% | LR: 0.000116
Epoch: 051 | MCC: 0.026020 | Train loss: 0.9871 | Train acc: 51.55% | Val loss: 0.9090 | Val acc: 55.67% | LR: 0.000114
Epoch: 052 | MCC: 0.025625 | Train loss: 0.9867 | Train acc: 51.20% | Val loss: 0.9079 | Val acc: 55.55% | LR: 0.000113
Epoch: 053 | MCC: 0.025625 | Train loss: 0.9863 | Train acc: 51.51% | Val loss: 0.9066 | Val acc: 55.55% | LR: 0.000111
Epoch: 054 | MCC: 0.024757 | Train loss: 0.9853 | Train acc: 51.42% | Val loss: 0.9053 | Val acc: 55.48% | LR: 0.000110
Epoch: 055 | MCC: 0.026479 | Train loss: 0.9855 | Train acc: 51.10% | Val loss: 0.9042 | Val acc: 55.60% | LR: 0.000108
Epoch: 056 | MCC: 0.029167 | Train loss: 0.9860 | Train acc: 50.95% | Val loss: 0.9035 | Val acc: 55.62% | LR: 0.000107
Epoch: 057 | MCC: 0.030024 | Train loss: 0.9852 | Train acc: 51.05% | Val loss: 0.9026 | Val acc: 55.66% | LR: 0.000105
Epoch: 058 | MCC: 0.029095 | Train loss: 0.9849 | Train acc: 51.14% | Val loss: 0.9012 | Val acc: 55.58% | LR: 0.000104
Epoch: 059 | MCC: 0.032190 | Train loss: 0.9839 | Train acc: 51.04% | Val loss: 0.9004 | Val acc: 55.61% | LR: 0.000102
Epoch: 060 | MCC: 0.029095 | Train loss: 0.9873 | Train acc: 51.30% | Val loss: 0.8995 | Val acc: 55.58% | LR: 0.000101
Epoch: 061 | MCC: 0.031208 | Train loss: 0.9837 | Train acc: 51.18% | Val loss: 0.8982 | Val acc: 55.71% | LR: 0.000099
Epoch: 062 | MCC: 0.031782 | Train loss: 0.9831 | Train acc: 51.08% | Val loss: 0.8977 | Val acc: 55.61% | LR: 0.000098
Epoch: 063 | MCC: 0.032458 | Train loss: 0.9832 | Train acc: 50.85% | Val loss: 0.8967 | Val acc: 55.63% | LR: 0.000096
Epoch: 064 | MCC: 0.029671 | Train loss: 0.9818 | Train acc: 51.14% | Val loss: 0.8950 | Val acc: 55.62% | LR: 0.000094
Epoch: 065 | MCC: 0.031177 | Train loss: 0.9823 | Train acc: 50.88% | Val loss: 0.8937 | Val acc: 55.62% | LR: 0.000093
Epoch: 066 | MCC: 0.031177 | Train loss: 0.9820 | Train acc: 51.09% | Val loss: 0.8927 | Val acc: 55.62% | LR: 0.000091
Epoch: 067 | MCC: 0.029737 | Train loss: 0.9818 | Train acc: 51.01% | Val loss: 0.8918 | Val acc: 55.47% | LR: 0.000090
Epoch: 068 | MCC: 0.030424 | Train loss: 0.9826 | Train acc: 50.94% | Val loss: 0.8907 | Val acc: 55.58% | LR: 0.000088
Epoch: 069 | MCC: 0.029547 | Train loss: 0.9820 | Train acc: 50.98% | Val loss: 0.8892 | Val acc: 55.48% | LR: 0.000086
Epoch: 070 | MCC: 0.024524 | Train loss: 0.9926 | Train acc: 51.15% | Val loss: 0.8885 | Val acc: 55.48% | LR: 0.000085
Epoch: 071 | MCC: 0.023041 | Train loss: 0.9904 | Train acc: 50.98% | Val loss: 0.8887 | Val acc: 55.39% | LR: 0.000083
Epoch: 072 | MCC: 0.024242 | Train loss: 0.9869 | Train acc: 51.16% | Val loss: 0.8889 | Val acc: 55.37% | LR: 0.000082
Epoch: 073 | MCC: 0.023169 | Train loss: 0.9817 | Train acc: 51.01% | Val loss: 0.8883 | Val acc: 55.25% | LR: 0.000080
Epoch: 074 | MCC: 0.022897 | Train loss: 0.9803 | Train acc: 51.03% | Val loss: 0.8872 | Val acc: 55.29% | LR: 0.000078
Epoch: 075 | MCC: 0.029152 | Train loss: 0.9785 | Train acc: 51.05% | Val loss: 0.8870 | Val acc: 55.56% | LR: 0.000077
Epoch: 076 | MCC: 0.036097 | Train loss: 0.9798 | Train acc: 51.05% | Val loss: 0.8861 | Val acc: 55.96% | LR: 0.000075
Epoch: 077 | MCC: 0.025668 | Train loss: 0.9801 | Train acc: 51.02% | Val loss: 0.8847 | Val acc: 56.20% | LR: 0.000073
Epoch: 078 | MCC: 0.031678 | Train loss: 0.9807 | Train acc: 50.98% | Val loss: 0.8841 | Val acc: 56.60% | LR: 0.000072
Epoch: 079 | MCC: 0.045102 | Train loss: 0.9787 | Train acc: 51.03% | Val loss: 0.8830 | Val acc: 57.03% | LR: 0.000070
Epoch: 080 | MCC: 0.045102 | Train loss: 0.9863 | Train acc: 51.09% | Val loss: 0.8829 | Val acc: 57.03% | LR: 0.000069
Epoch: 081 | MCC: 0.045217 | Train loss: 1.0247 | Train acc: 50.86% | Val loss: 0.8829 | Val acc: 57.03% | LR: 0.000067
Epoch: 082 | MCC: 0.046756 | Train loss: 0.9991 | Train acc: 51.00% | Val loss: 0.8829 | Val acc: 57.15% | LR: 0.000065
Epoch: 083 | MCC: 0.046756 | Train loss: 1.0413 | Train acc: 51.31% | Val loss: 0.8829 | Val acc: 57.15% | LR: 0.000064
Epoch: 084 | MCC: 0.047955 | Train loss: 0.9984 | Train acc: 50.97% | Val loss: 0.8828 | Val acc: 57.17% | LR: 0.000062
Epoch: 085 | MCC: 0.046613 | Train loss: 0.9797 | Train acc: 51.04% | Val loss: 0.8829 | Val acc: 57.27% | LR: 0.000061
Epoch: 086 | MCC: 0.051100 | Train loss: 0.9778 | Train acc: 51.09% | Val loss: 0.8819 | Val acc: 57.41% | LR: 0.000059
Epoch: 087 | MCC: 0.047198 | Train loss: 0.9784 | Train acc: 50.92% | Val loss: 0.8814 | Val acc: 57.35% | LR: 0.000058
Epoch: 088 | MCC: 0.046356 | Train loss: 0.9783 | Train acc: 50.99% | Val loss: 0.8806 | Val acc: 57.30% | LR: 0.000056
Epoch: 089 | MCC: 0.045621 | Train loss: 0.9779 | Train acc: 50.98% | Val loss: 0.8800 | Val acc: 57.28% | LR: 0.000054
Epoch: 090 | MCC: 0.044708 | Train loss: 0.9785 | Train acc: 51.02% | Val loss: 0.8800 | Val acc: 57.23% | LR: 0.000053
Epoch: 091 | MCC: 0.044252 | Train loss: 0.9766 | Train acc: 51.14% | Val loss: 0.8790 | Val acc: 57.21% | LR: 0.000051
Epoch: 092 | MCC: 0.040977 | Train loss: 0.9771 | Train acc: 51.10% | Val loss: 0.8782 | Val acc: 57.14% | LR: 0.000050
Epoch: 093 | MCC: 0.040562 | Train loss: 0.9766 | Train acc: 51.07% | Val loss: 0.8779 | Val acc: 57.09% | LR: 0.000048
Epoch: 094 | MCC: 0.041121 | Train loss: 0.9776 | Train acc: 50.93% | Val loss: 0.8778 | Val acc: 57.11% | LR: 0.000047
Epoch: 095 | MCC: 0.043164 | Train loss: 0.9766 | Train acc: 51.05% | Val loss: 0.8775 | Val acc: 57.17% | LR: 0.000045
Epoch: 096 | MCC: 0.038335 | Train loss: 0.9770 | Train acc: 50.96% | Val loss: 0.8771 | Val acc: 57.05% | LR: 0.000044
Epoch: 097 | MCC: 0.039793 | Train loss: 0.9772 | Train acc: 51.11% | Val loss: 0.8769 | Val acc: 57.07% | LR: 0.000042
Epoch: 098 | MCC: 0.032861 | Train loss: 0.9779 | Train acc: 50.98% | Val loss: 0.8769 | Val acc: 56.93% | LR: 0.000041
Epoch: 099 | MCC: 0.032493 | Train loss: 0.9762 | Train acc: 51.13% | Val loss: 0.8767 | Val acc: 56.88% | LR: 0.000040
Epoch: 100 | MCC: 0.032222 | Train loss: 0.9764 | Train acc: 51.15% | Val loss: 0.8766 | Val acc: 56.83% | LR: 0.000038
Epoch: 101 | MCC: 0.035496 | Train loss: 0.9759 | Train acc: 51.18% | Val loss: 0.8768 | Val acc: 56.90% | LR: 0.000037
Epoch: 102 | MCC: 0.035567 | Train loss: 0.9772 | Train acc: 51.02% | Val loss: 0.8765 | Val acc: 56.90% | LR: 0.000036
Epoch: 103 | MCC: 0.033448 | Train loss: 0.9753 | Train acc: 51.20% | Val loss: 0.8762 | Val acc: 56.88% | LR: 0.000034
Epoch: 104 | MCC: 0.034000 | Train loss: 0.9773 | Train acc: 50.99% | Val loss: 0.8759 | Val acc: 56.88% | LR: 0.000033
Epoch: 105 | MCC: 0.035496 | Train loss: 0.9771 | Train acc: 51.07% | Val loss: 0.8757 | Val acc: 56.90% | LR: 0.000032
Epoch: 106 | MCC: 0.033039 | Train loss: 0.9767 | Train acc: 51.15% | Val loss: 0.8761 | Val acc: 56.68% | LR: 0.000030
Epoch: 107 | MCC: 0.033619 | Train loss: 0.9758 | Train acc: 51.10% | Val loss: 0.8755 | Val acc: 56.81% | LR: 0.000029
Epoch: 108 | MCC: 0.033165 | Train loss: 0.9759 | Train acc: 51.02% | Val loss: 0.8752 | Val acc: 56.78% | LR: 0.000028
Epoch: 109 | MCC: 0.034089 | Train loss: 0.9755 | Train acc: 51.09% | Val loss: 0.8755 | Val acc: 56.71% | LR: 0.000027
Epoch: 110 | MCC: 0.034018 | Train loss: 0.9768 | Train acc: 51.12% | Val loss: 0.8754 | Val acc: 56.71% | LR: 0.000025
Epoch: 111 | MCC: 0.034018 | Train loss: 0.9764 | Train acc: 51.05% | Val loss: 0.8752 | Val acc: 56.71% | LR: 0.000024
Epoch: 112 | MCC: 0.034018 | Train loss: 0.9760 | Train acc: 51.15% | Val loss: 0.8752 | Val acc: 56.71% | LR: 0.000023
Epoch: 113 | MCC: 0.034018 | Train loss: 0.9769 | Train acc: 51.04% | Val loss: 0.8751 | Val acc: 56.71% | LR: 0.000022
Epoch: 114 | MCC: 0.034018 | Train loss: 0.9761 | Train acc: 51.05% | Val loss: 0.8749 | Val acc: 56.71% | LR: 0.000021
Epoch: 115 | MCC: 0.032742 | Train loss: 0.9761 | Train acc: 51.17% | Val loss: 0.8751 | Val acc: 56.61% | LR: 0.000020
Epoch: 116 | MCC: 0.030547 | Train loss: 0.9773 | Train acc: 50.95% | Val loss: 0.8751 | Val acc: 56.49% | LR: 0.000019
Epoch: 117 | MCC: 0.033767 | Train loss: 0.9767 | Train acc: 51.07% | Val loss: 0.8749 | Val acc: 56.60% | LR: 0.000018
Epoch: 118 | MCC: 0.031885 | Train loss: 0.9773 | Train acc: 51.11% | Val loss: 0.8750 | Val acc: 56.50% | LR: 0.000017
Epoch: 119 | MCC: 0.030521 | Train loss: 0.9760 | Train acc: 51.13% | Val loss: 0.8751 | Val acc: 56.43% | LR: 0.000016
Epoch: 120 | MCC: 0.035436 | Train loss: 0.9793 | Train acc: 51.05% | Val loss: 0.8748 | Val acc: 56.61% | LR: 0.000015
Epoch: 121 | MCC: 0.035260 | Train loss: 0.9762 | Train acc: 51.14% | Val loss: 0.8748 | Val acc: 56.58% | LR: 0.000014
Epoch: 122 | MCC: 0.035921 | Train loss: 0.9762 | Train acc: 51.05% | Val loss: 0.8747 | Val acc: 56.61% | LR: 0.000013
Epoch: 123 | MCC: 0.037567 | Train loss: 0.9751 | Train acc: 51.10% | Val loss: 0.8747 | Val acc: 56.68% | LR: 0.000012
Epoch: 124 | MCC: 0.037567 | Train loss: 0.9756 | Train acc: 51.15% | Val loss: 0.8746 | Val acc: 56.68% | LR: 0.000011
Epoch: 125 | MCC: 0.037044 | Train loss: 0.9764 | Train acc: 51.07% | Val loss: 0.8744 | Val acc: 56.66% | LR: 0.000011
Epoch: 126 | MCC: 0.036724 | Train loss: 0.9766 | Train acc: 50.99% | Val loss: 0.8745 | Val acc: 56.63% | LR: 0.000010
Epoch: 127 | MCC: 0.039467 | Train loss: 0.9758 | Train acc: 51.23% | Val loss: 0.8746 | Val acc: 56.67% | LR: 0.000009
Epoch: 128 | MCC: 0.038099 | Train loss: 0.9754 | Train acc: 51.11% | Val loss: 0.8744 | Val acc: 56.59% | LR: 0.000008
Epoch: 129 | MCC: 0.038622 | Train loss: 0.9769 | Train acc: 51.04% | Val loss: 0.8743 | Val acc: 56.62% | LR: 0.000008
Epoch: 130 | MCC: 0.038688 | Train loss: 0.9760 | Train acc: 51.13% | Val loss: 0.8744 | Val acc: 56.62% | LR: 0.000007
Epoch: 131 | MCC: 0.038232 | Train loss: 0.9747 | Train acc: 51.17% | Val loss: 0.8743 | Val acc: 56.59% | LR: 0.000006
Epoch: 132 | MCC: 0.038232 | Train loss: 0.9753 | Train acc: 51.15% | Val loss: 0.8743 | Val acc: 56.59% | LR: 0.000006
Epoch: 133 | MCC: 0.040437 | Train loss: 0.9757 | Train acc: 51.14% | Val loss: 0.8743 | Val acc: 56.64% | LR: 0.000005
Epoch: 134 | MCC: 0.039482 | Train loss: 0.9757 | Train acc: 51.02% | Val loss: 0.8743 | Val acc: 56.64% | LR: 0.000005
Epoch: 135 | MCC: 0.039024 | Train loss: 0.9763 | Train acc: 51.06% | Val loss: 0.8742 | Val acc: 56.62% | LR: 0.000004
Epoch: 136 | MCC: 0.027312 | Train loss: 0.9758 | Train acc: 51.14% | Val loss: 0.8742 | Val acc: 56.58% | LR: 0.000004
Epoch: 137 | MCC: 0.027312 | Train loss: 0.9757 | Train acc: 51.12% | Val loss: 0.8742 | Val acc: 56.58% | LR: 0.000003
Epoch: 138 | MCC: 0.027312 | Train loss: 0.9753 | Train acc: 51.12% | Val loss: 0.8742 | Val acc: 56.58% | LR: 0.000003
Epoch: 139 | MCC: 0.027312 | Train loss: 0.9759 | Train acc: 51.12% | Val loss: 0.8742 | Val acc: 56.58% | LR: 0.000003
Epoch: 140 | MCC: 0.027312 | Train loss: 0.9755 | Train acc: 51.11% | Val loss: 0.8741 | Val acc: 56.58% | LR: 0.000002
Epoch: 141 | MCC: 0.027377 | Train loss: 0.9746 | Train acc: 51.21% | Val loss: 0.8741 | Val acc: 56.58% | LR: 0.000002
Epoch: 142 | MCC: 0.027377 | Train loss: 0.9739 | Train acc: 51.17% | Val loss: 0.8741 | Val acc: 56.58% | LR: 0.000002
Epoch: 143 | MCC: 0.027377 | Train loss: 0.9760 | Train acc: 51.11% | Val loss: 0.8741 | Val acc: 56.58% | LR: 0.000002
Epoch: 144 | MCC: 0.027377 | Train loss: 0.9756 | Train acc: 51.12% | Val loss: 0.8741 | Val acc: 56.58% | LR: 0.000001
Epoch: 145 | MCC: 0.027377 | Train loss: 0.9747 | Train acc: 51.17% | Val loss: 0.8741 | Val acc: 56.58% | LR: 0.000001
Epoch: 146 | MCC: 0.027377 | Train loss: 0.9753 | Train acc: 51.13% | Val loss: 0.8741 | Val acc: 56.58% | LR: 0.000001
Epoch: 147 | MCC: 0.027377 | Train loss: 0.9759 | Train acc: 51.06% | Val loss: 0.8741 | Val acc: 56.58% | LR: 0.000001
Epoch: 148 | MCC: 0.010610 | Train loss: 0.9760 | Train acc: 51.15% | Val loss: 0.8741 | Val acc: 56.50% | LR: 0.000001
Epoch: 149 | MCC: 0.010610 | Train loss: 0.9746 | Train acc: 51.06% | Val loss: 0.8741 | Val acc: 56.50% | LR: 0.000001

[I 2025-10-05 10:41:19,951] Trial 60 finished with value: 0.010610341094434261 and parameters: {'lr': 0.00015563983693802716, 'hidden_size': 27, 'dropout': 0.08417430915541758, 'weight_decay': 0.032578523930506205}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.045290 | Train loss: 0.9959 | Train acc: 50.71% | Val loss: 0.9993 | Val acc: 49.20% | LR: 0.000572
Epoch: 001 | MCC: 0.053775 | Train loss: 0.9925 | Train acc: 50.76% | Val loss: 0.9977 | Val acc: 51.82% | LR: 0.000572
Epoch: 002 | MCC: 0.055285 | Train loss: 0.9899 | Train acc: 50.93% | Val loss: 0.9917 | Val acc: 54.87% | LR: 0.000571
Epoch: 003 | MCC: 0.044791 | Train loss: 0.9937 | Train acc: 51.01% | Val loss: 0.9849 | Val acc: 55.36% | LR: 0.000571
Epoch: 004 | MCC: 0.036876 | Train loss: 0.9880 | Train acc: 50.91% | Val loss: 0.9737 | Val acc: 55.44% | LR: 0.000570
Epoch: 005 | MCC: 0.030243 | Train loss: 0.9846 | Train acc: 50.89% | Val loss: 0.9641 | Val acc: 55.42% | LR: 0.000570
Epoch: 006 | MCC: 0.036663 | Train loss: 0.9848 | Train acc: 50.86% | Val loss: 0.9556 | Val acc: 56.27% | LR: 0.000569
Epoch: 007 | MCC: 0.031960 | Train loss: 0.9825 | Train acc: 50.91% | Val loss: 0.9418 | Val acc: 56.66% | LR: 0.000568
Epoch: 008 | MCC: 0.032022 | Train loss: 0.9811 | Train acc: 51.02% | Val loss: 0.9296 | Val acc: 56.57% | LR: 0.000567
Epoch: 009 | MCC: 0.030063 | Train loss: 0.9799 | Train acc: 50.97% | Val loss: 0.9191 | Val acc: 56.55% | LR: 0.000566
Epoch: 010 | MCC: 0.037295 | Train loss: 0.9814 | Train acc: 50.84% | Val loss: 0.9099 | Val acc: 56.97% | LR: 0.000564
Epoch: 011 | MCC: 0.033888 | Train loss: 0.9815 | Train acc: 50.77% | Val loss: 0.9065 | Val acc: 56.72% | LR: 0.000563
Epoch: 012 | MCC: 0.035096 | Train loss: 0.9808 | Train acc: 50.94% | Val loss: 0.9007 | Val acc: 57.39% | LR: 0.000561
Epoch: 013 | MCC: 0.043910 | Train loss: 0.9783 | Train acc: 51.06% | Val loss: 0.8882 | Val acc: 57.22% | LR: 0.000560
Epoch: 014 | MCC: 0.053267 | Train loss: 0.9781 | Train acc: 51.05% | Val loss: 0.8740 | Val acc: 57.88% | LR: 0.000558
Epoch: 015 | MCC: 0.034389 | Train loss: 0.9777 | Train acc: 51.15% | Val loss: 0.8675 | Val acc: 56.90% | LR: 0.000556
Epoch: 016 | MCC: 0.036545 | Train loss: 0.9753 | Train acc: 51.77% | Val loss: 0.8745 | Val acc: 57.82% | LR: 0.000554
Epoch: 017 | MCC: 0.043036 | Train loss: 0.9741 | Train acc: 51.66% | Val loss: 0.8702 | Val acc: 57.79% | LR: 0.000552
Epoch: 018 | MCC: 0.013734 | Train loss: 0.9754 | Train acc: 52.04% | Val loss: 0.8645 | Val acc: 56.81% | LR: 0.000550
Epoch: 019 | MCC: 0.030618 | Train loss: 0.9728 | Train acc: 51.92% | Val loss: 0.8552 | Val acc: 59.37% | LR: 0.000547
Epoch: 020 | MCC: 0.047317 | Train loss: 0.9857 | Train acc: 51.61% | Val loss: 0.8845 | Val acc: 58.37% | LR: 0.000545
Epoch: 021 | MCC: 0.050419 | Train loss: 0.9799 | Train acc: 51.54% | Val loss: 0.8632 | Val acc: 60.55% | LR: 0.000542
Epoch: 022 | MCC: 0.052796 | Train loss: 0.9776 | Train acc: 51.62% | Val loss: 0.8510 | Val acc: 59.95% | LR: 0.000539
Epoch: 023 | MCC: 0.057823 | Train loss: 0.9768 | Train acc: 51.64% | Val loss: 0.8501 | Val acc: 59.38% | LR: 0.000537
Epoch: 024 | MCC: 0.065638 | Train loss: 0.9763 | Train acc: 51.77% | Val loss: 0.8456 | Val acc: 58.79% | LR: 0.000534
Epoch: 025 | MCC: 0.068297 | Train loss: 0.9735 | Train acc: 51.78% | Val loss: 0.8454 | Val acc: 58.54% | LR: 0.000531
Epoch: 026 | MCC: 0.059918 | Train loss: 0.9719 | Train acc: 51.82% | Val loss: 0.8416 | Val acc: 58.58% | LR: 0.000527
Epoch: 027 | MCC: 0.066386 | Train loss: 0.9711 | Train acc: 51.78% | Val loss: 0.8425 | Val acc: 59.08% | LR: 0.000524
Epoch: 028 | MCC: 0.066790 | Train loss: 0.9691 | Train acc: 51.94% | Val loss: 0.8469 | Val acc: 59.03% | LR: 0.000521
Epoch: 029 | MCC: 0.074176 | Train loss: 0.9673 | Train acc: 51.97% | Val loss: 0.8385 | Val acc: 58.95% | LR: 0.000517
Epoch: 030 | MCC: 0.072767 | Train loss: 0.9721 | Train acc: 51.80% | Val loss: 0.8446 | Val acc: 58.86% | LR: 0.000514
Epoch: 031 | MCC: 0.083422 | Train loss: 0.9701 | Train acc: 51.91% | Val loss: 0.8342 | Val acc: 59.41% | LR: 0.000510
Epoch: 032 | MCC: 0.028044 | Train loss: 0.9722 | Train acc: 51.98% | Val loss: 0.8452 | Val acc: 58.49% | LR: 0.000506
Epoch: 033 | MCC: 0.028924 | Train loss: 0.9682 | Train acc: 51.95% | Val loss: 0.8312 | Val acc: 59.17% | LR: 0.000502
Epoch: 034 | MCC: 0.028173 | Train loss: 0.9674 | Train acc: 51.99% | Val loss: 0.8451 | Val acc: 58.27% | LR: 0.000499
Epoch: 035 | MCC: 0.035406 | Train loss: 0.9645 | Train acc: 52.02% | Val loss: 0.8343 | Val acc: 58.66% | LR: 0.000494
Epoch: 036 | MCC: 0.038671 | Train loss: 0.9630 | Train acc: 52.14% | Val loss: 0.8422 | Val acc: 58.30% | LR: 0.000490
Epoch: 037 | MCC: 0.025607 | Train loss: 0.9713 | Train acc: 51.89% | Val loss: 0.8526 | Val acc: 57.91% | LR: 0.000486
Epoch: 038 | MCC: 0.046442 | Train loss: 0.9648 | Train acc: 52.04% | Val loss: 0.8272 | Val acc: 59.57% | LR: 0.000482
Epoch: 039 | MCC: 0.063215 | Train loss: 0.9649 | Train acc: 52.02% | Val loss: 0.8443 | Val acc: 58.37% | LR: 0.000477
Epoch: 040 | MCC: 0.031883 | Train loss: 0.9624 | Train acc: 52.08% | Val loss: 0.8405 | Val acc: 58.42% | LR: 0.000473
Epoch: 041 | MCC: 0.066631 | Train loss: 0.9639 | Train acc: 51.98% | Val loss: 0.8163 | Val acc: 60.13% | LR: 0.000468
Epoch: 042 | MCC: 0.025719 | Train loss: 0.9636 | Train acc: 52.04% | Val loss: 0.8479 | Val acc: 58.12% | LR: 0.000464
Epoch: 043 | MCC: 0.052311 | Train loss: 0.9680 | Train acc: 51.98% | Val loss: 0.8307 | Val acc: 59.13% | LR: 0.000459
Epoch: 044 | MCC: 0.012753 | Train loss: 0.9648 | Train acc: 52.10% | Val loss: 0.8806 | Val acc: 57.62% | LR: 0.000454
Epoch: 045 | MCC: 0.025924 | Train loss: 0.9658 | Train acc: 51.96% | Val loss: 0.8436 | Val acc: 58.29% | LR: 0.000449
Epoch: 046 | MCC: 0.062537 | Train loss: 0.9654 | Train acc: 52.00% | Val loss: 0.8189 | Val acc: 59.49% | LR: 0.000444
Epoch: 047 | MCC: 0.048053 | Train loss: 0.9611 | Train acc: 52.19% | Val loss: 0.8469 | Val acc: 58.08% | LR: 0.000439
Epoch: 048 | MCC: 0.071885 | Train loss: 0.9630 | Train acc: 52.05% | Val loss: 0.8235 | Val acc: 59.11% | LR: 0.000434
Epoch: 049 | MCC: 0.027374 | Train loss: 0.9648 | Train acc: 51.91% | Val loss: 0.8129 | Val acc: 59.75% | LR: 0.000429
Epoch: 050 | MCC: 0.031624 | Train loss: 0.9633 | Train acc: 51.98% | Val loss: 0.8434 | Val acc: 58.14% | LR: 0.000424
Epoch: 051 | MCC: 0.045222 | Train loss: 0.9665 | Train acc: 51.97% | Val loss: 0.8466 | Val acc: 57.93% | LR: 0.000419
Epoch: 052 | MCC: 0.053640 | Train loss: 0.9636 | Train acc: 52.02% | Val loss: 0.8504 | Val acc: 58.02% | LR: 0.000413
Epoch: 053 | MCC: 0.028725 | Train loss: 0.9623 | Train acc: 52.08% | Val loss: 0.8447 | Val acc: 58.13% | LR: 0.000408
Epoch: 054 | MCC: 0.029803 | Train loss: 0.9605 | Train acc: 52.13% | Val loss: 0.8135 | Val acc: 59.68% | LR: 0.000403
Epoch: 055 | MCC: 0.035191 | Train loss: 0.9616 | Train acc: 52.05% | Val loss: 0.8280 | Val acc: 59.17% | LR: 0.000397
Epoch: 056 | MCC: 0.023247 | Train loss: 0.9609 | Train acc: 52.13% | Val loss: 0.8263 | Val acc: 59.14% | LR: 0.000391
Epoch: 057 | MCC: 0.045511 | Train loss: 0.9623 | Train acc: 52.13% | Val loss: 0.8236 | Val acc: 59.46% | LR: 0.000386
Epoch: 058 | MCC: 0.081137 | Train loss: 0.9617 | Train acc: 52.13% | Val loss: 0.8105 | Val acc: 60.12% | LR: 0.000380
Epoch: 059 | MCC: 0.030809 | Train loss: 0.9625 | Train acc: 52.08% | Val loss: 0.8324 | Val acc: 58.81% | LR: 0.000375
Epoch: 060 | MCC: 0.079964 | Train loss: 0.9626 | Train acc: 52.07% | Val loss: 0.8044 | Val acc: 60.36% | LR: 0.000369
Epoch: 061 | MCC: 0.058957 | Train loss: 0.9591 | Train acc: 52.20% | Val loss: 0.8276 | Val acc: 59.13% | LR: 0.000363
Epoch: 062 | MCC: 0.057862 | Train loss: 0.9628 | Train acc: 52.02% | Val loss: 0.8302 | Val acc: 58.81% | LR: 0.000357
Epoch: 063 | MCC: 0.079664 | Train loss: 0.9606 | Train acc: 52.13% | Val loss: 0.8192 | Val acc: 59.69% | LR: 0.000352
Epoch: 064 | MCC: 0.005018 | Train loss: 0.9622 | Train acc: 52.10% | Val loss: 0.8708 | Val acc: 56.32% | LR: 0.000346
Epoch: 065 | MCC: 0.050246 | Train loss: 0.9677 | Train acc: 51.81% | Val loss: 0.8338 | Val acc: 58.81% | LR: 0.000340
Epoch: 066 | MCC: 0.020108 | Train loss: 0.9605 | Train acc: 52.17% | Val loss: 0.8389 | Val acc: 58.31% | LR: 0.000334
Epoch: 067 | MCC: 0.057863 | Train loss: 0.9595 | Train acc: 52.22% | Val loss: 0.8175 | Val acc: 59.45% | LR: 0.000328
Epoch: 068 | MCC: 0.031476 | Train loss: 0.9628 | Train acc: 52.01% | Val loss: 0.8220 | Val acc: 59.16% | LR: 0.000322
Epoch: 069 | MCC: 0.025724 | Train loss: 0.9824 | Train acc: 51.88% | Val loss: 0.8352 | Val acc: 58.65% | LR: 0.000316
Epoch: 070 | MCC: 0.033495 | Train loss: 0.9611 | Train acc: 52.12% | Val loss: 0.8107 | Val acc: 59.83% | LR: 0.000310
Epoch: 071 | MCC: 0.074827 | Train loss: 0.9616 | Train acc: 52.05% | Val loss: 0.8067 | Val acc: 60.01% | LR: 0.000304
Epoch: 072 | MCC: 0.033193 | Train loss: 0.9618 | Train acc: 52.04% | Val loss: 0.8360 | Val acc: 58.66% | LR: 0.000298
Epoch: 073 | MCC: 0.070237 | Train loss: 0.9607 | Train acc: 52.12% | Val loss: 0.8097 | Val acc: 59.96% | LR: 0.000292
Epoch: 074 | MCC: 0.029338 | Train loss: 0.9611 | Train acc: 52.07% | Val loss: 0.8549 | Val acc: 58.10% | LR: 0.000286
Epoch: 075 | MCC: 0.030274 | Train loss: 0.9597 | Train acc: 52.13% | Val loss: 0.8309 | Val acc: 59.09% | LR: 0.000280
Epoch: 076 | MCC: 0.066539 | Train loss: 0.9580 | Train acc: 52.19% | Val loss: 0.8089 | Val acc: 60.01% | LR: 0.000274
Epoch: 077 | MCC: 0.058749 | Train loss: 0.9599 | Train acc: 52.11% | Val loss: 0.8260 | Val acc: 58.96% | LR: 0.000269
Epoch: 078 | MCC: 0.085375 | Train loss: 0.9602 | Train acc: 52.13% | Val loss: 0.8022 | Val acc: 60.41% | LR: 0.000263
Epoch: 079 | MCC: 0.025106 | Train loss: 0.9587 | Train acc: 52.17% | Val loss: 0.8231 | Val acc: 59.17% | LR: 0.000257
Epoch: 080 | MCC: 0.040472 | Train loss: 0.9609 | Train acc: 52.04% | Val loss: 0.8264 | Val acc: 59.03% | LR: 0.000251
Epoch: 081 | MCC: 0.041045 | Train loss: 0.9585 | Train acc: 52.14% | Val loss: 0.8061 | Val acc: 59.97% | LR: 0.000245
Epoch: 082 | MCC: 0.069271 | Train loss: 0.9589 | Train acc: 52.16% | Val loss: 0.8163 | Val acc: 59.76% | LR: 0.000239
Epoch: 083 | MCC: 0.027955 | Train loss: 0.9605 | Train acc: 52.04% | Val loss: 0.8227 | Val acc: 59.12% | LR: 0.000233
Epoch: 084 | MCC: 0.058937 | Train loss: 0.9599 | Train acc: 52.08% | Val loss: 0.8214 | Val acc: 59.69% | LR: 0.000227
Epoch: 085 | MCC: 0.035114 | Train loss: 0.9606 | Train acc: 52.10% | Val loss: 0.8259 | Val acc: 59.07% | LR: 0.000221
Epoch: 086 | MCC: 0.032804 | Train loss: 0.9607 | Train acc: 52.06% | Val loss: 0.8316 | Val acc: 59.02% | LR: 0.000215
Epoch: 087 | MCC: 0.071578 | Train loss: 0.9574 | Train acc: 52.25% | Val loss: 0.8258 | Val acc: 59.67% | LR: 0.000210
Epoch: 088 | MCC: 0.035112 | Train loss: 0.9598 | Train acc: 52.09% | Val loss: 0.8197 | Val acc: 59.46% | LR: 0.000204
Epoch: 089 | MCC: 0.036499 | Train loss: 0.9574 | Train acc: 52.24% | Val loss: 0.8171 | Val acc: 59.48% | LR: 0.000198
Epoch: 090 | MCC: 0.034252 | Train loss: 0.9592 | Train acc: 52.16% | Val loss: 0.8358 | Val acc: 58.80% | LR: 0.000193
Epoch: 091 | MCC: 0.083710 | Train loss: 0.9559 | Train acc: 52.31% | Val loss: 0.8154 | Val acc: 60.14% | LR: 0.000187
Epoch: 092 | MCC: 0.059083 | Train loss: 0.9596 | Train acc: 52.10% | Val loss: 0.8116 | Val acc: 59.93% | LR: 0.000181
Epoch: 093 | MCC: 0.082285 | Train loss: 0.9591 | Train acc: 52.14% | Val loss: 0.8063 | Val acc: 60.35% | LR: 0.000176
Epoch: 094 | MCC: 0.084091 | Train loss: 0.9599 | Train acc: 52.06% | Val loss: 0.8212 | Val acc: 60.04% | LR: 0.000170
Epoch: 095 | MCC: 0.035288 | Train loss: 0.9590 | Train acc: 52.13% | Val loss: 0.8284 | Val acc: 58.95% | LR: 0.000165
Epoch: 096 | MCC: 0.033487 | Train loss: 0.9585 | Train acc: 52.16% | Val loss: 0.8258 | Val acc: 59.04% | LR: 0.000160
Epoch: 097 | MCC: 0.029465 | Train loss: 0.9581 | Train acc: 52.18% | Val loss: 0.8436 | Val acc: 59.22% | LR: 0.000154
Epoch: 098 | MCC: 0.029997 | Train loss: 0.9553 | Train acc: 52.32% | Val loss: 0.8235 | Val acc: 59.26% | LR: 0.000149
Epoch: 099 | MCC: 0.058279 | Train loss: 0.9555 | Train acc: 52.34% | Val loss: 0.8284 | Val acc: 58.88% | LR: 0.000144
Epoch: 100 | MCC: 0.057186 | Train loss: 0.9567 | Train acc: 52.24% | Val loss: 0.8263 | Val acc: 58.98% | LR: 0.000139
Epoch: 101 | MCC: 0.027157 | Train loss: 0.9555 | Train acc: 52.32% | Val loss: 0.8303 | Val acc: 58.73% | LR: 0.000133
Epoch: 102 | MCC: 0.025828 | Train loss: 0.9560 | Train acc: 52.29% | Val loss: 0.8297 | Val acc: 58.78% | LR: 0.000128
Epoch: 103 | MCC: 0.058369 | Train loss: 0.9589 | Train acc: 52.14% | Val loss: 0.8241 | Val acc: 59.10% | LR: 0.000124
Epoch: 104 | MCC: 0.055449 | Train loss: 0.9570 | Train acc: 52.25% | Val loss: 0.8216 | Val acc: 59.08% | LR: 0.000119
Epoch: 105 | MCC: 0.024852 | Train loss: 0.9589 | Train acc: 52.15% | Val loss: 0.8276 | Val acc: 58.82% | LR: 0.000114
Epoch: 106 | MCC: 0.050427 | Train loss: 0.9563 | Train acc: 52.30% | Val loss: 0.8220 | Val acc: 59.13% | LR: 0.000109
Epoch: 107 | MCC: 0.030119 | Train loss: 0.9564 | Train acc: 52.28% | Val loss: 0.8298 | Val acc: 58.92% | LR: 0.000104
Epoch: 108 | MCC: 0.029036 | Train loss: 0.9601 | Train acc: 52.10% | Val loss: 0.8468 | Val acc: 58.85% | LR: 0.000100
Epoch: 109 | MCC: 0.056922 | Train loss: 0.9570 | Train acc: 52.25% | Val loss: 0.8241 | Val acc: 59.10% | LR: 0.000095
Epoch: 110 | MCC: 0.053429 | Train loss: 0.9583 | Train acc: 52.16% | Val loss: 0.8244 | Val acc: 58.96% | LR: 0.000091
Epoch: 111 | MCC: 0.058085 | Train loss: 0.9568 | Train acc: 52.26% | Val loss: 0.8209 | Val acc: 59.23% | LR: 0.000087
Epoch: 112 | MCC: 0.036327 | Train loss: 0.9571 | Train acc: 52.25% | Val loss: 0.8209 | Val acc: 59.36% | LR: 0.000082
Epoch: 113 | MCC: 0.055136 | Train loss: 0.9576 | Train acc: 52.20% | Val loss: 0.9144 | Val acc: 59.13% | LR: 0.000078
Epoch: 114 | MCC: 0.029412 | Train loss: 0.9560 | Train acc: 52.29% | Val loss: 0.8252 | Val acc: 58.95% | LR: 0.000074
Epoch: 115 | MCC: 0.033356 | Train loss: 0.9551 | Train acc: 52.33% | Val loss: 0.8217 | Val acc: 59.09% | LR: 0.000070
Epoch: 116 | MCC: 0.031474 | Train loss: 0.9543 | Train acc: 52.35% | Val loss: 0.8256 | Val acc: 58.90% | LR: 0.000067
Epoch: 117 | MCC: 0.060227 | Train loss: 0.9549 | Train acc: 52.35% | Val loss: 0.8212 | Val acc: 59.25% | LR: 0.000063
Epoch: 118 | MCC: 0.059084 | Train loss: 0.9591 | Train acc: 52.15% | Val loss: 0.8277 | Val acc: 59.08% | LR: 0.000059
Epoch: 119 | MCC: 0.030788 | Train loss: 0.9582 | Train acc: 52.17% | Val loss: 0.8275 | Val acc: 58.82% | LR: 0.000056
Epoch: 120 | MCC: 0.058010 | Train loss: 0.9558 | Train acc: 52.31% | Val loss: 0.8256 | Val acc: 59.08% | LR: 0.000052
Epoch: 121 | MCC: 0.030577 | Train loss: 0.9571 | Train acc: 52.22% | Val loss: 0.8254 | Val acc: 58.92% | LR: 0.000049
Epoch: 122 | MCC: 0.030687 | Train loss: 0.9572 | Train acc: 52.22% | Val loss: 0.8258 | Val acc: 58.90% | LR: 0.000045
Epoch: 123 | MCC: 0.030011 | Train loss: 0.9587 | Train acc: 52.15% | Val loss: 0.8274 | Val acc: 58.78% | LR: 0.000042
Epoch: 124 | MCC: 0.056390 | Train loss: 0.9583 | Train acc: 52.16% | Val loss: 0.8251 | Val acc: 58.98% | LR: 0.000039
Epoch: 125 | MCC: 0.030614 | Train loss: 0.9562 | Train acc: 52.30% | Val loss: 0.8263 | Val acc: 58.85% | LR: 0.000036
Epoch: 126 | MCC: 0.031345 | Train loss: 0.9582 | Train acc: 52.17% | Val loss: 0.8262 | Val acc: 58.87% | LR: 0.000033
Epoch: 127 | MCC: 0.031278 | Train loss: 0.9562 | Train acc: 52.27% | Val loss: 0.8256 | Val acc: 58.92% | LR: 0.000031
Epoch: 128 | MCC: 0.030069 | Train loss: 0.9585 | Train acc: 52.17% | Val loss: 0.8259 | Val acc: 58.87% | LR: 0.000028
Epoch: 129 | MCC: 0.029057 | Train loss: 0.9560 | Train acc: 52.31% | Val loss: 0.8251 | Val acc: 58.85% | LR: 0.000026
Epoch: 130 | MCC: 0.028918 | Train loss: 0.9561 | Train acc: 52.29% | Val loss: 0.8262 | Val acc: 58.85% | LR: 0.000023
Epoch: 131 | MCC: 0.028848 | Train loss: 0.9533 | Train acc: 52.42% | Val loss: 0.8255 | Val acc: 58.85% | LR: 0.000021
Epoch: 132 | MCC: 0.029581 | Train loss: 0.9571 | Train acc: 52.22% | Val loss: 0.8257 | Val acc: 58.87% | LR: 0.000019
Epoch: 133 | MCC: 0.029861 | Train loss: 0.9576 | Train acc: 52.21% | Val loss: 0.8260 | Val acc: 58.87% | LR: 0.000017
Epoch: 134 | MCC: 0.029724 | Train loss: 0.9558 | Train acc: 52.29% | Val loss: 0.8256 | Val acc: 58.87% | LR: 0.000015
Epoch: 135 | MCC: 0.030452 | Train loss: 0.9556 | Train acc: 52.31% | Val loss: 0.8251 | Val acc: 58.90% | LR: 0.000013
Epoch: 136 | MCC: 0.030088 | Train loss: 0.9614 | Train acc: 52.02% | Val loss: 0.8242 | Val acc: 58.92% | LR: 0.000012
Epoch: 137 | MCC: 0.030368 | Train loss: 0.9546 | Train acc: 52.36% | Val loss: 0.8241 | Val acc: 58.92% | LR: 0.000010
Epoch: 138 | MCC: 0.030168 | Train loss: 0.9564 | Train acc: 52.28% | Val loss: 0.8242 | Val acc: 58.90% | LR: 0.000009
Epoch: 139 | MCC: 0.056839 | Train loss: 0.9559 | Train acc: 52.28% | Val loss: 0.8235 | Val acc: 59.01% | LR: 0.000007
Epoch: 140 | MCC: 0.029331 | Train loss: 0.9559 | Train acc: 52.30% | Val loss: 0.8242 | Val acc: 58.85% | LR: 0.000006
Epoch: 141 | MCC: 0.029331 | Train loss: 0.9584 | Train acc: 52.16% | Val loss: 0.8241 | Val acc: 58.85% | LR: 0.000005
Epoch: 142 | MCC: 0.056839 | Train loss: 0.9556 | Train acc: 52.31% | Val loss: 0.8238 | Val acc: 59.01% | LR: 0.000004
Epoch: 143 | MCC: 0.056839 | Train loss: 0.9568 | Train acc: 52.25% | Val loss: 0.8237 | Val acc: 59.01% | LR: 0.000003
Epoch: 144 | MCC: 0.056839 | Train loss: 0.9549 | Train acc: 52.35% | Val loss: 0.8238 | Val acc: 59.01% | LR: 0.000003
Epoch: 145 | MCC: 0.056839 | Train loss: 0.9564 | Train acc: 52.26% | Val loss: 0.8238 | Val acc: 59.01% | LR: 0.000002
Epoch: 146 | MCC: 0.056839 | Train loss: 0.9567 | Train acc: 52.26% | Val loss: 0.8238 | Val acc: 59.01% | LR: 0.000002
Epoch: 147 | MCC: 0.030691 | Train loss: 0.9565 | Train acc: 52.27% | Val loss: 0.8238 | Val acc: 58.92% | LR: 0.000001
Epoch: 148 | MCC: 0.056839 | Train loss: 0.9566 | Train acc: 52.26% | Val loss: 0.8237 | Val acc: 59.01% | LR: 0.000001
Epoch: 149 | MCC: 0.056839 | Train loss: 0.9556 | Train acc: 52.31% | Val loss: 0.8237 | Val acc: 59.01% | LR: 0.000001

[I 2025-10-05 10:43:34,268] Trial 61 finished with value: 0.05683930218219757 and parameters: {'lr': 0.0005718464151612094, 'hidden_size': 70, 'dropout': 0.13494892838477793, 'weight_decay': 0.005023566542186916}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.010340 | Train loss: 0.9993 | Train acc: 50.20% | Val loss: 0.9813 | Val acc: 53.27% | LR: 0.000620
Epoch: 001 | MCC: 0.027823 | Train loss: 0.9985 | Train acc: 50.84% | Val loss: 0.9744 | Val acc: 54.61% | LR: 0.000620
Epoch: 002 | MCC: 0.028040 | Train loss: 0.9889 | Train acc: 50.80% | Val loss: 0.9618 | Val acc: 54.74% | LR: 0.000620
Epoch: 003 | MCC: 0.025040 | Train loss: 0.9875 | Train acc: 50.80% | Val loss: 0.9478 | Val acc: 54.91% | LR: 0.000619
Epoch: 004 | MCC: 0.016351 | Train loss: 0.9866 | Train acc: 50.90% | Val loss: 0.9284 | Val acc: 55.03% | LR: 0.000619
Epoch: 005 | MCC: 0.014124 | Train loss: 0.9853 | Train acc: 50.86% | Val loss: 0.9190 | Val acc: 55.17% | LR: 0.000618
Epoch: 006 | MCC: 0.014857 | Train loss: 0.9808 | Train acc: 50.96% | Val loss: 0.9085 | Val acc: 55.34% | LR: 0.000617
Epoch: 007 | MCC: 0.015433 | Train loss: 0.9794 | Train acc: 51.05% | Val loss: 0.8974 | Val acc: 55.92% | LR: 0.000616
Epoch: 008 | MCC: 0.029083 | Train loss: 0.9812 | Train acc: 50.98% | Val loss: 0.8857 | Val acc: 57.39% | LR: 0.000615
Epoch: 009 | MCC: 0.027742 | Train loss: 0.9811 | Train acc: 51.03% | Val loss: 0.8804 | Val acc: 57.75% | LR: 0.000614
Epoch: 010 | MCC: 0.013010 | Train loss: 0.9822 | Train acc: 51.06% | Val loss: 0.8878 | Val acc: 57.13% | LR: 0.000612
Epoch: 011 | MCC: 0.007109 | Train loss: 0.9804 | Train acc: 51.09% | Val loss: 0.8634 | Val acc: 57.96% | LR: 0.000611
Epoch: 012 | MCC: 0.007656 | Train loss: 0.9776 | Train acc: 51.24% | Val loss: 0.8942 | Val acc: 55.88% | LR: 0.000609
Epoch: 013 | MCC: -0.006764 | Train loss: 0.9762 | Train acc: 51.25% | Val loss: 0.8754 | Val acc: 57.06% | LR: 0.000607
Epoch: 014 | MCC: 0.006494 | Train loss: 0.9757 | Train acc: 51.22% | Val loss: 0.8875 | Val acc: 56.64% | LR: 0.000605
Epoch: 015 | MCC: 0.000851 | Train loss: 0.9741 | Train acc: 51.32% | Val loss: 0.8979 | Val acc: 56.10% | LR: 0.000603
Epoch: 016 | MCC: -0.000535 | Train loss: 0.9756 | Train acc: 51.24% | Val loss: 0.8866 | Val acc: 56.44% | LR: 0.000601
Epoch: 017 | MCC: 0.012813 | Train loss: 0.9745 | Train acc: 51.35% | Val loss: 0.8971 | Val acc: 56.03% | LR: 0.000599
Epoch: 018 | MCC: -0.005988 | Train loss: 0.9743 | Train acc: 51.21% | Val loss: 0.8733 | Val acc: 56.99% | LR: 0.000596
Epoch: 019 | MCC: 0.006084 | Train loss: 0.9726 | Train acc: 51.35% | Val loss: 0.8850 | Val acc: 56.77% | LR: 0.000594
Epoch: 020 | MCC: 0.005799 | Train loss: 0.9737 | Train acc: 51.35% | Val loss: 0.8833 | Val acc: 57.05% | LR: 0.000591
Epoch: 021 | MCC: 0.008557 | Train loss: 0.9718 | Train acc: 51.36% | Val loss: 0.8802 | Val acc: 57.99% | LR: 0.000588
Epoch: 022 | MCC: -0.000946 | Train loss: 0.9728 | Train acc: 51.33% | Val loss: 0.8866 | Val acc: 57.30% | LR: 0.000585
Epoch: 023 | MCC: -0.009107 | Train loss: 0.9724 | Train acc: 51.37% | Val loss: 0.8725 | Val acc: 57.87% | LR: 0.000582
Epoch: 024 | MCC: 0.001357 | Train loss: 0.9686 | Train acc: 51.50% | Val loss: 0.8729 | Val acc: 57.86% | LR: 0.000579
Epoch: 025 | MCC: -0.050080 | Train loss: 0.9709 | Train acc: 51.48% | Val loss: 0.8739 | Val acc: 56.89% | LR: 0.000576
Epoch: 026 | MCC: -0.014386 | Train loss: 0.9685 | Train acc: 51.51% | Val loss: 0.8698 | Val acc: 57.35% | LR: 0.000572
Epoch: 027 | MCC: -0.016814 | Train loss: 0.9663 | Train acc: 51.69% | Val loss: 0.8933 | Val acc: 56.20% | LR: 0.000569
Epoch: 028 | MCC: 0.001493 | Train loss: 0.9687 | Train acc: 51.48% | Val loss: 0.8941 | Val acc: 55.75% | LR: 0.000565
Epoch: 029 | MCC: 0.008767 | Train loss: 1.1679 | Train acc: 51.57% | Val loss: 0.8566 | Val acc: 57.48% | LR: 0.000561
Epoch: 030 | MCC: -0.036387 | Train loss: 0.9823 | Train acc: 50.91% | Val loss: 0.8903 | Val acc: 55.41% | LR: 0.000557
Epoch: 031 | MCC: 0.002361 | Train loss: 0.9777 | Train acc: 51.58% | Val loss: 0.8662 | Val acc: 56.90% | LR: 0.000553
Epoch: 032 | MCC: -0.015190 | Train loss: 0.9721 | Train acc: 51.71% | Val loss: 0.8975 | Val acc: 55.58% | LR: 0.000549
Epoch: 033 | MCC: -0.016304 | Train loss: 0.9704 | Train acc: 51.74% | Val loss: 0.8939 | Val acc: 55.97% | LR: 0.000545
Epoch: 034 | MCC: -0.032578 | Train loss: 0.9693 | Train acc: 51.78% | Val loss: 0.8850 | Val acc: 55.75% | LR: 0.000541
Epoch: 035 | MCC: -0.008590 | Train loss: 0.9717 | Train acc: 51.55% | Val loss: 0.9101 | Val acc: 54.77% | LR: 0.000537
Epoch: 036 | MCC: -0.019892 | Train loss: 0.9688 | Train acc: 51.72% | Val loss: 0.8785 | Val acc: 56.65% | LR: 0.000532
Epoch: 037 | MCC: -0.023296 | Train loss: 0.9698 | Train acc: 51.68% | Val loss: 0.9094 | Val acc: 55.00% | LR: 0.000527
Epoch: 038 | MCC: -0.027463 | Train loss: 0.9661 | Train acc: 51.83% | Val loss: 0.9012 | Val acc: 55.31% | LR: 0.000523
Epoch: 039 | MCC: 0.002595 | Train loss: 0.9684 | Train acc: 51.76% | Val loss: 0.9011 | Val acc: 56.19% | LR: 0.000518
Epoch: 040 | MCC: -0.012083 | Train loss: 0.9680 | Train acc: 51.74% | Val loss: 0.9049 | Val acc: 55.26% | LR: 0.000513
Epoch: 041 | MCC: -0.019251 | Train loss: 0.9676 | Train acc: 51.77% | Val loss: 0.9010 | Val acc: 55.38% | LR: 0.000508
Epoch: 042 | MCC: -0.003848 | Train loss: 0.9686 | Train acc: 51.71% | Val loss: 0.8866 | Val acc: 56.69% | LR: 0.000503
Epoch: 043 | MCC: -0.023712 | Train loss: 0.9676 | Train acc: 51.76% | Val loss: 0.9076 | Val acc: 55.09% | LR: 0.000498
Epoch: 044 | MCC: -0.021833 | Train loss: 0.9675 | Train acc: 51.81% | Val loss: 0.9116 | Val acc: 54.87% | LR: 0.000493
Epoch: 045 | MCC: -0.012775 | Train loss: 0.9638 | Train acc: 51.91% | Val loss: 0.8999 | Val acc: 55.34% | LR: 0.000488
Epoch: 046 | MCC: -0.004834 | Train loss: 0.9657 | Train acc: 51.85% | Val loss: 0.8886 | Val acc: 56.41% | LR: 0.000482
Epoch: 047 | MCC: -0.006247 | Train loss: 0.9640 | Train acc: 51.96% | Val loss: 0.9048 | Val acc: 55.36% | LR: 0.000477
Epoch: 048 | MCC: -0.020068 | Train loss: 0.9657 | Train acc: 51.87% | Val loss: 0.9147 | Val acc: 54.77% | LR: 0.000471
Epoch: 049 | MCC: -0.026298 | Train loss: 0.9638 | Train acc: 51.97% | Val loss: 0.9000 | Val acc: 55.18% | LR: 0.000466
Epoch: 050 | MCC: -0.018690 | Train loss: 0.9650 | Train acc: 51.88% | Val loss: 0.9140 | Val acc: 55.06% | LR: 0.000460
Epoch: 051 | MCC: -0.005575 | Train loss: 0.9656 | Train acc: 51.87% | Val loss: 0.9067 | Val acc: 55.29% | LR: 0.000454
Epoch: 052 | MCC: -0.015861 | Train loss: 0.9609 | Train acc: 52.12% | Val loss: 0.9006 | Val acc: 55.35% | LR: 0.000448
Epoch: 053 | MCC: -0.010784 | Train loss: 0.9651 | Train acc: 51.90% | Val loss: 0.8995 | Val acc: 55.45% | LR: 0.000443
Epoch: 054 | MCC: -0.010095 | Train loss: 0.9648 | Train acc: 51.88% | Val loss: 0.9086 | Val acc: 55.13% | LR: 0.000437
Epoch: 055 | MCC: -0.019008 | Train loss: 0.9609 | Train acc: 52.05% | Val loss: 0.9052 | Val acc: 55.43% | LR: 0.000431
Epoch: 056 | MCC: -0.009577 | Train loss: 0.9621 | Train acc: 52.01% | Val loss: 0.8910 | Val acc: 56.10% | LR: 0.000425
Epoch: 057 | MCC: -0.014928 | Train loss: 0.9631 | Train acc: 51.97% | Val loss: 0.9102 | Val acc: 55.36% | LR: 0.000419
Epoch: 058 | MCC: -0.000234 | Train loss: 0.9627 | Train acc: 52.00% | Val loss: 0.8936 | Val acc: 56.28% | LR: 0.000413
Epoch: 059 | MCC: -0.001154 | Train loss: 0.9613 | Train acc: 52.12% | Val loss: 0.8918 | Val acc: 56.13% | LR: 0.000406
Epoch: 060 | MCC: -0.018976 | Train loss: 0.9605 | Train acc: 52.13% | Val loss: 0.9059 | Val acc: 55.21% | LR: 0.000400
Epoch: 061 | MCC: -0.006529 | Train loss: 0.9614 | Train acc: 52.11% | Val loss: 0.8805 | Val acc: 56.76% | LR: 0.000394
Epoch: 062 | MCC: -0.019543 | Train loss: 0.9597 | Train acc: 52.21% | Val loss: 0.8953 | Val acc: 55.79% | LR: 0.000388
Epoch: 063 | MCC: -0.019742 | Train loss: 0.9631 | Train acc: 51.99% | Val loss: 0.8930 | Val acc: 55.88% | LR: 0.000381
Epoch: 064 | MCC: -0.016699 | Train loss: 0.9636 | Train acc: 52.01% | Val loss: 0.8916 | Val acc: 55.89% | LR: 0.000375
Epoch: 065 | MCC: -0.009749 | Train loss: 0.9608 | Train acc: 52.08% | Val loss: 0.8871 | Val acc: 56.22% | LR: 0.000369
Epoch: 066 | MCC: -0.020752 | Train loss: 0.9608 | Train acc: 52.12% | Val loss: 0.8917 | Val acc: 55.69% | LR: 0.000362
Epoch: 067 | MCC: -0.026983 | Train loss: 0.9635 | Train acc: 51.93% | Val loss: 0.9026 | Val acc: 55.30% | LR: 0.000356
Epoch: 068 | MCC: -0.017548 | Train loss: 0.9602 | Train acc: 52.16% | Val loss: 0.8876 | Val acc: 55.87% | LR: 0.000350
Epoch: 069 | MCC: -0.012425 | Train loss: 0.9603 | Train acc: 52.10% | Val loss: 0.8904 | Val acc: 56.00% | LR: 0.000343
Epoch: 070 | MCC: -0.025136 | Train loss: 0.9590 | Train acc: 52.23% | Val loss: 0.8913 | Val acc: 55.67% | LR: 0.000337
Epoch: 071 | MCC: -0.013388 | Train loss: 0.9602 | Train acc: 52.10% | Val loss: 0.8977 | Val acc: 55.45% | LR: 0.000330
Epoch: 072 | MCC: -0.022363 | Train loss: 0.9602 | Train acc: 52.15% | Val loss: 0.9005 | Val acc: 55.46% | LR: 0.000324
Epoch: 073 | MCC: -0.007257 | Train loss: 0.9588 | Train acc: 52.19% | Val loss: 0.8874 | Val acc: 56.41% | LR: 0.000317
Epoch: 074 | MCC: -0.017323 | Train loss: 0.9599 | Train acc: 52.17% | Val loss: 0.8958 | Val acc: 55.52% | LR: 0.000311
Epoch: 075 | MCC: -0.011505 | Train loss: 0.9586 | Train acc: 52.21% | Val loss: 0.8931 | Val acc: 55.67% | LR: 0.000304
Epoch: 076 | MCC: -0.008321 | Train loss: 0.9621 | Train acc: 52.04% | Val loss: 0.8857 | Val acc: 56.40% | LR: 0.000298
Epoch: 077 | MCC: -0.005893 | Train loss: 0.9573 | Train acc: 52.37% | Val loss: 0.8800 | Val acc: 56.39% | LR: 0.000291
Epoch: 078 | MCC: -0.014775 | Train loss: 0.9585 | Train acc: 52.24% | Val loss: 0.8870 | Val acc: 55.90% | LR: 0.000285
Epoch: 079 | MCC: -0.016603 | Train loss: 0.9586 | Train acc: 52.21% | Val loss: 0.8908 | Val acc: 55.76% | LR: 0.000278
Epoch: 080 | MCC: -0.016464 | Train loss: 0.9572 | Train acc: 52.26% | Val loss: 0.8940 | Val acc: 55.66% | LR: 0.000272
Epoch: 081 | MCC: -0.020311 | Train loss: 0.9577 | Train acc: 52.28% | Val loss: 0.8982 | Val acc: 55.38% | LR: 0.000265
Epoch: 082 | MCC: -0.003964 | Train loss: 0.9580 | Train acc: 52.25% | Val loss: 0.8912 | Val acc: 56.20% | LR: 0.000259
Epoch: 083 | MCC: -0.008338 | Train loss: 0.9569 | Train acc: 52.31% | Val loss: 0.8983 | Val acc: 55.80% | LR: 0.000253
Epoch: 084 | MCC: -0.024196 | Train loss: 0.9604 | Train acc: 52.20% | Val loss: 0.8856 | Val acc: 55.99% | LR: 0.000246
Epoch: 085 | MCC: -0.001098 | Train loss: 0.9613 | Train acc: 52.04% | Val loss: 0.8912 | Val acc: 56.02% | LR: 0.000240
Epoch: 086 | MCC: 0.005276 | Train loss: 0.9592 | Train acc: 52.21% | Val loss: 0.8909 | Val acc: 56.10% | LR: 0.000234
Epoch: 087 | MCC: -0.017180 | Train loss: 0.9590 | Train acc: 52.17% | Val loss: 0.8836 | Val acc: 56.09% | LR: 0.000227
Epoch: 088 | MCC: -0.009632 | Train loss: 0.9566 | Train acc: 52.31% | Val loss: 0.8910 | Val acc: 55.83% | LR: 0.000221
Epoch: 089 | MCC: -0.007408 | Train loss: 0.9583 | Train acc: 52.20% | Val loss: 0.8826 | Val acc: 56.47% | LR: 0.000215
Epoch: 090 | MCC: -0.015829 | Train loss: 0.9575 | Train acc: 52.26% | Val loss: 0.8877 | Val acc: 55.88% | LR: 0.000209
Epoch: 091 | MCC: -0.013205 | Train loss: 0.9588 | Train acc: 52.18% | Val loss: 0.8894 | Val acc: 55.99% | LR: 0.000203
Epoch: 092 | MCC: -0.009267 | Train loss: 0.9563 | Train acc: 52.29% | Val loss: 0.8903 | Val acc: 55.95% | LR: 0.000197
Epoch: 093 | MCC: -0.003031 | Train loss: 0.9576 | Train acc: 52.24% | Val loss: 0.8864 | Val acc: 56.40% | LR: 0.000191
Epoch: 094 | MCC: -0.012789 | Train loss: 0.9561 | Train acc: 52.36% | Val loss: 0.8926 | Val acc: 55.83% | LR: 0.000185
Epoch: 095 | MCC: -0.006803 | Train loss: 0.9568 | Train acc: 52.27% | Val loss: 0.8918 | Val acc: 55.89% | LR: 0.000179
Epoch: 096 | MCC: -0.006443 | Train loss: 0.9577 | Train acc: 52.24% | Val loss: 0.8879 | Val acc: 56.35% | LR: 0.000173
Epoch: 097 | MCC: -0.013585 | Train loss: 0.9563 | Train acc: 52.36% | Val loss: 0.8897 | Val acc: 55.89% | LR: 0.000167
Epoch: 098 | MCC: -0.010879 | Train loss: 0.9551 | Train acc: 52.39% | Val loss: 0.8867 | Val acc: 56.31% | LR: 0.000162
Epoch: 099 | MCC: -0.015554 | Train loss: 0.9558 | Train acc: 52.36% | Val loss: 0.8909 | Val acc: 56.06% | LR: 0.000156
Epoch: 100 | MCC: -0.012172 | Train loss: 0.9531 | Train acc: 52.53% | Val loss: 0.8880 | Val acc: 56.21% | LR: 0.000150
Epoch: 101 | MCC: -0.010222 | Train loss: 0.9561 | Train acc: 52.30% | Val loss: 0.8868 | Val acc: 56.32% | LR: 0.000145
Epoch: 102 | MCC: -0.009779 | Train loss: 0.9550 | Train acc: 52.43% | Val loss: 0.8890 | Val acc: 56.37% | LR: 0.000139
Epoch: 103 | MCC: -0.008694 | Train loss: 0.9561 | Train acc: 52.33% | Val loss: 0.8866 | Val acc: 56.16% | LR: 0.000134

[I 2025-10-05 10:45:08,677] Trial 62 finished with value: -0.010317224048776552 and parameters: {'lr': 0.0006204822449828433, 'hidden_size': 71, 'dropout': 0.10851090082456186, 'weight_decay': 0.004832819025913321}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.011924 | Train loss: 1.0031 | Train acc: 50.03% | Val loss: 0.9852 | Val acc: 54.03% | LR: 0.000869
Epoch: 001 | MCC: -0.001834 | Train loss: 0.9969 | Train acc: 50.85% | Val loss: 0.9789 | Val acc: 53.52% | LR: 0.000868
Epoch: 002 | MCC: -0.006934 | Train loss: 0.9930 | Train acc: 51.05% | Val loss: 1.0044 | Val acc: 53.71% | LR: 0.000868
Epoch: 003 | MCC: 0.007850 | Train loss: 0.9948 | Train acc: 50.97% | Val loss: 0.9787 | Val acc: 52.98% | LR: 0.000867
Epoch: 004 | MCC: -0.005845 | Train loss: 0.9854 | Train acc: 51.11% | Val loss: 0.9815 | Val acc: 53.20% | LR: 0.000866
Epoch: 005 | MCC: -0.008440 | Train loss: 0.9884 | Train acc: 50.87% | Val loss: 0.9936 | Val acc: 53.10% | LR: 0.000865
Epoch: 006 | MCC: -0.010381 | Train loss: 0.9898 | Train acc: 50.82% | Val loss: 0.9853 | Val acc: 53.43% | LR: 0.000864
Epoch: 007 | MCC: 0.009476 | Train loss: 0.9941 | Train acc: 50.69% | Val loss: 0.9789 | Val acc: 54.40% | LR: 0.000863
Epoch: 008 | MCC: 0.008596 | Train loss: 0.9873 | Train acc: 51.00% | Val loss: 0.9705 | Val acc: 54.18% | LR: 0.000861
Epoch: 009 | MCC: 0.030465 | Train loss: 0.9845 | Train acc: 50.85% | Val loss: 0.9730 | Val acc: 54.60% | LR: 0.000859
Epoch: 010 | MCC: 0.012002 | Train loss: 0.9867 | Train acc: 50.66% | Val loss: 0.9973 | Val acc: 51.72% | LR: 0.000857
Epoch: 011 | MCC: 0.001973 | Train loss: 0.9854 | Train acc: 50.67% | Val loss: 0.9977 | Val acc: 51.39% | LR: 0.000855
Epoch: 012 | MCC: -0.004173 | Train loss: 0.9844 | Train acc: 50.72% | Val loss: 0.9942 | Val acc: 51.36% | LR: 0.000853
Epoch: 013 | MCC: 0.005096 | Train loss: 0.9836 | Train acc: 50.86% | Val loss: 0.9883 | Val acc: 52.53% | LR: 0.000850
Epoch: 014 | MCC: -0.001954 | Train loss: 0.9833 | Train acc: 50.77% | Val loss: 0.9789 | Val acc: 53.35% | LR: 0.000847
Epoch: 015 | MCC: 0.002037 | Train loss: 0.9818 | Train acc: 50.86% | Val loss: 0.9739 | Val acc: 53.79% | LR: 0.000844
Epoch: 016 | MCC: -0.000742 | Train loss: 0.9824 | Train acc: 50.67% | Val loss: 0.9666 | Val acc: 54.28% | LR: 0.000841
Epoch: 017 | MCC: -0.007667 | Train loss: 0.9804 | Train acc: 50.80% | Val loss: 0.9595 | Val acc: 54.56% | LR: 0.000838
Epoch: 018 | MCC: 0.003535 | Train loss: 0.9787 | Train acc: 50.89% | Val loss: 0.9547 | Val acc: 55.21% | LR: 0.000835
Epoch: 019 | MCC: -0.002099 | Train loss: 0.9802 | Train acc: 50.88% | Val loss: 0.9452 | Val acc: 55.49% | LR: 0.000831
Epoch: 020 | MCC: -0.004638 | Train loss: 0.9789 | Train acc: 50.94% | Val loss: 0.9380 | Val acc: 55.82% | LR: 0.000827
Epoch: 021 | MCC: 0.001046 | Train loss: 0.9775 | Train acc: 51.03% | Val loss: 0.9257 | Val acc: 56.53% | LR: 0.000823
Epoch: 022 | MCC: -0.004774 | Train loss: 0.9772 | Train acc: 51.15% | Val loss: 0.9223 | Val acc: 55.70% | LR: 0.000819
Epoch: 023 | MCC: -0.005485 | Train loss: 0.9775 | Train acc: 51.01% | Val loss: 0.9119 | Val acc: 56.47% | LR: 0.000815
Epoch: 024 | MCC: -0.001870 | Train loss: 0.9770 | Train acc: 51.01% | Val loss: 0.9078 | Val acc: 56.38% | LR: 0.000810
Epoch: 025 | MCC: 0.003791 | Train loss: 0.9773 | Train acc: 51.08% | Val loss: 0.9008 | Val acc: 56.30% | LR: 0.000806
Epoch: 026 | MCC: -0.008629 | Train loss: 0.9751 | Train acc: 51.24% | Val loss: 0.8946 | Val acc: 56.63% | LR: 0.000801
Epoch: 027 | MCC: -0.017632 | Train loss: 0.9747 | Train acc: 51.12% | Val loss: 0.8950 | Val acc: 56.30% | LR: 0.000796
Epoch: 028 | MCC: -0.013765 | Train loss: 0.9734 | Train acc: 51.29% | Val loss: 0.8939 | Val acc: 56.86% | LR: 0.000791
Epoch: 029 | MCC: -0.019300 | Train loss: 0.9758 | Train acc: 51.18% | Val loss: 0.8932 | Val acc: 56.45% | LR: 0.000786
Epoch: 030 | MCC: -0.014332 | Train loss: 0.9748 | Train acc: 51.62% | Val loss: 0.8876 | Val acc: 56.65% | LR: 0.000780
Epoch: 031 | MCC: -0.009231 | Train loss: 0.9724 | Train acc: 51.58% | Val loss: 0.8891 | Val acc: 56.49% | LR: 0.000775
Epoch: 032 | MCC: -0.016306 | Train loss: 0.9744 | Train acc: 51.73% | Val loss: 0.8909 | Val acc: 55.88% | LR: 0.000769
Epoch: 033 | MCC: -0.006976 | Train loss: 0.9738 | Train acc: 51.77% | Val loss: 0.8995 | Val acc: 55.95% | LR: 0.000763
Epoch: 034 | MCC: -0.015163 | Train loss: 0.9720 | Train acc: 52.02% | Val loss: 0.8797 | Val acc: 56.76% | LR: 0.000757
Epoch: 035 | MCC: -0.009354 | Train loss: 0.9715 | Train acc: 51.97% | Val loss: 0.8889 | Val acc: 56.83% | LR: 0.000751
Epoch: 036 | MCC: 0.002077 | Train loss: 0.9718 | Train acc: 51.89% | Val loss: 0.9002 | Val acc: 55.73% | LR: 0.000745
Epoch: 037 | MCC: -0.004855 | Train loss: 0.9701 | Train acc: 52.02% | Val loss: 0.8876 | Val acc: 56.91% | LR: 0.000738
Epoch: 038 | MCC: -0.002236 | Train loss: 0.9700 | Train acc: 51.94% | Val loss: 0.8960 | Val acc: 55.93% | LR: 0.000732
Epoch: 039 | MCC: 0.003880 | Train loss: 0.9702 | Train acc: 51.97% | Val loss: 0.8935 | Val acc: 56.59% | LR: 0.000725
Epoch: 040 | MCC: -0.004952 | Train loss: 0.9709 | Train acc: 51.89% | Val loss: 0.8953 | Val acc: 56.27% | LR: 0.000718
Epoch: 041 | MCC: -0.003734 | Train loss: 0.9704 | Train acc: 51.86% | Val loss: 0.8848 | Val acc: 56.96% | LR: 0.000711
Epoch: 042 | MCC: 0.007806 | Train loss: 0.9686 | Train acc: 52.04% | Val loss: 0.8884 | Val acc: 56.91% | LR: 0.000704
Epoch: 043 | MCC: 0.005758 | Train loss: 0.9692 | Train acc: 52.01% | Val loss: 0.8939 | Val acc: 56.32% | LR: 0.000697
Epoch: 044 | MCC: -0.002016 | Train loss: 0.9673 | Train acc: 52.05% | Val loss: 0.8864 | Val acc: 56.83% | LR: 0.000690
Epoch: 045 | MCC: -0.000257 | Train loss: 0.9681 | Train acc: 52.01% | Val loss: 0.8834 | Val acc: 56.98% | LR: 0.000682
Epoch: 046 | MCC: 0.004012 | Train loss: 0.9675 | Train acc: 51.99% | Val loss: 0.8833 | Val acc: 57.13% | LR: 0.000675
Epoch: 047 | MCC: -0.010854 | Train loss: 0.9672 | Train acc: 52.04% | Val loss: 0.8915 | Val acc: 56.61% | LR: 0.000667
Epoch: 048 | MCC: -0.012654 | Train loss: 0.9682 | Train acc: 51.97% | Val loss: 0.8710 | Val acc: 57.60% | LR: 0.000660
Epoch: 049 | MCC: 0.003847 | Train loss: 0.9677 | Train acc: 51.90% | Val loss: 0.8786 | Val acc: 57.19% | LR: 0.000652
Epoch: 050 | MCC: -0.011082 | Train loss: 0.9681 | Train acc: 52.01% | Val loss: 0.8932 | Val acc: 56.54% | LR: 0.000644
Epoch: 051 | MCC: -0.013511 | Train loss: 0.9658 | Train acc: 52.07% | Val loss: 0.8884 | Val acc: 56.49% | LR: 0.000636
Epoch: 052 | MCC: -0.004621 | Train loss: 0.9645 | Train acc: 52.11% | Val loss: 0.8836 | Val acc: 56.74% | LR: 0.000628
Epoch: 053 | MCC: 0.001149 | Train loss: 0.9661 | Train acc: 52.01% | Val loss: 0.8737 | Val acc: 57.69% | LR: 0.000620
Epoch: 054 | MCC: -0.001164 | Train loss: 0.9657 | Train acc: 52.01% | Val loss: 0.8868 | Val acc: 56.66% | LR: 0.000611
Epoch: 055 | MCC: -0.005304 | Train loss: 0.9631 | Train acc: 52.09% | Val loss: 0.8824 | Val acc: 56.98% | LR: 0.000603
Epoch: 056 | MCC: -0.011487 | Train loss: 0.9608 | Train acc: 52.25% | Val loss: 0.8788 | Val acc: 57.20% | LR: 0.000594
Epoch: 057 | MCC: -0.010736 | Train loss: 0.9615 | Train acc: 52.08% | Val loss: 0.8808 | Val acc: 57.05% | LR: 0.000586
Epoch: 058 | MCC: 0.008934 | Train loss: 0.9627 | Train acc: 52.12% | Val loss: 0.8890 | Val acc: 57.35% | LR: 0.000577
Epoch: 059 | MCC: -0.008195 | Train loss: 0.9673 | Train acc: 52.12% | Val loss: 0.8872 | Val acc: 57.13% | LR: 0.000569
Epoch: 060 | MCC: -0.014199 | Train loss: 0.9642 | Train acc: 52.15% | Val loss: 0.8896 | Val acc: 56.88% | LR: 0.000560
Epoch: 061 | MCC: -0.010074 | Train loss: 0.9642 | Train acc: 52.14% | Val loss: 0.8875 | Val acc: 57.03% | LR: 0.000551
Epoch: 062 | MCC: -0.011435 | Train loss: 0.9626 | Train acc: 52.19% | Val loss: 0.8920 | Val acc: 56.74% | LR: 0.000543
Epoch: 063 | MCC: -0.007425 | Train loss: 0.9620 | Train acc: 52.19% | Val loss: 0.8878 | Val acc: 57.20% | LR: 0.000534
Epoch: 064 | MCC: -0.013857 | Train loss: 0.9607 | Train acc: 52.14% | Val loss: 0.8913 | Val acc: 56.90% | LR: 0.000525
Epoch: 065 | MCC: -0.012427 | Train loss: 0.9595 | Train acc: 52.19% | Val loss: 0.8888 | Val acc: 56.84% | LR: 0.000516
Epoch: 066 | MCC: 0.011960 | Train loss: 0.9587 | Train acc: 52.28% | Val loss: 0.8835 | Val acc: 57.59% | LR: 0.000507
Epoch: 067 | MCC: -0.007714 | Train loss: 0.9598 | Train acc: 52.27% | Val loss: 0.9037 | Val acc: 56.36% | LR: 0.000498
Epoch: 068 | MCC: -0.000183 | Train loss: 0.9607 | Train acc: 52.29% | Val loss: 0.8891 | Val acc: 57.29% | LR: 0.000489
Epoch: 069 | MCC: -0.013117 | Train loss: 0.9589 | Train acc: 52.32% | Val loss: 0.8938 | Val acc: 56.91% | LR: 0.000480
Epoch: 070 | MCC: -0.015654 | Train loss: 0.9583 | Train acc: 52.36% | Val loss: 0.9037 | Val acc: 55.99% | LR: 0.000471
Epoch: 071 | MCC: -0.011850 | Train loss: 0.9562 | Train acc: 52.52% | Val loss: 0.9026 | Val acc: 55.86% | LR: 0.000462
Epoch: 072 | MCC: -0.017652 | Train loss: 0.9574 | Train acc: 52.43% | Val loss: 0.9080 | Val acc: 55.56% | LR: 0.000453
Epoch: 073 | MCC: -0.006061 | Train loss: 0.9584 | Train acc: 52.29% | Val loss: 0.9059 | Val acc: 55.32% | LR: 0.000444
Epoch: 074 | MCC: 0.003433 | Train loss: 0.9617 | Train acc: 52.46% | Val loss: 0.8946 | Val acc: 55.57% | LR: 0.000435
Epoch: 075 | MCC: 0.007659 | Train loss: 0.9572 | Train acc: 52.56% | Val loss: 0.9106 | Val acc: 55.21% | LR: 0.000426
Epoch: 076 | MCC: -0.000413 | Train loss: 0.9572 | Train acc: 52.60% | Val loss: 0.9106 | Val acc: 55.08% | LR: 0.000417
Epoch: 077 | MCC: 0.003405 | Train loss: 0.9558 | Train acc: 52.55% | Val loss: 0.9073 | Val acc: 55.11% | LR: 0.000408
Epoch: 078 | MCC: 0.000598 | Train loss: 0.9539 | Train acc: 52.55% | Val loss: 0.9097 | Val acc: 54.71% | LR: 0.000399
Epoch: 079 | MCC: 0.009612 | Train loss: 0.9536 | Train acc: 52.60% | Val loss: 0.9116 | Val acc: 54.99% | LR: 0.000389
Epoch: 080 | MCC: -0.004745 | Train loss: 0.9542 | Train acc: 52.60% | Val loss: 0.9170 | Val acc: 54.46% | LR: 0.000380
Epoch: 081 | MCC: -0.004727 | Train loss: 0.9573 | Train acc: 52.33% | Val loss: 0.9155 | Val acc: 54.60% | LR: 0.000371
Epoch: 082 | MCC: 0.009017 | Train loss: 0.9554 | Train acc: 52.54% | Val loss: 0.9128 | Val acc: 55.12% | LR: 0.000362
Epoch: 083 | MCC: -0.006495 | Train loss: 0.9520 | Train acc: 52.61% | Val loss: 0.9161 | Val acc: 54.40% | LR: 0.000354
Epoch: 084 | MCC: -0.010353 | Train loss: 0.9540 | Train acc: 52.62% | Val loss: 0.9166 | Val acc: 54.46% | LR: 0.000345
Epoch: 085 | MCC: 0.000863 | Train loss: 0.9517 | Train acc: 52.69% | Val loss: 0.9155 | Val acc: 54.70% | LR: 0.000336
Epoch: 086 | MCC: -0.004633 | Train loss: 0.9562 | Train acc: 52.50% | Val loss: 0.9246 | Val acc: 54.33% | LR: 0.000327
Epoch: 087 | MCC: -0.005716 | Train loss: 0.9540 | Train acc: 52.60% | Val loss: 0.9155 | Val acc: 54.32% | LR: 0.000318
Epoch: 088 | MCC: 0.000642 | Train loss: 0.9533 | Train acc: 52.59% | Val loss: 0.9149 | Val acc: 54.79% | LR: 0.000309
Epoch: 089 | MCC: -0.007095 | Train loss: 0.9507 | Train acc: 52.77% | Val loss: 0.9248 | Val acc: 54.13% | LR: 0.000301
Epoch: 090 | MCC: -0.001550 | Train loss: 0.9524 | Train acc: 52.73% | Val loss: 0.9222 | Val acc: 54.26% | LR: 0.000292
Epoch: 091 | MCC: -0.017967 | Train loss: 0.9527 | Train acc: 52.56% | Val loss: 0.9185 | Val acc: 54.21% | LR: 0.000284
Epoch: 092 | MCC: 0.000075 | Train loss: 0.9517 | Train acc: 52.68% | Val loss: 0.9205 | Val acc: 54.33% | LR: 0.000275
Epoch: 093 | MCC: -0.014026 | Train loss: 0.9503 | Train acc: 52.77% | Val loss: 0.9186 | Val acc: 54.05% | LR: 0.000267
Epoch: 094 | MCC: -0.004627 | Train loss: 0.9506 | Train acc: 52.73% | Val loss: 0.9245 | Val acc: 54.15% | LR: 0.000258
Epoch: 095 | MCC: -0.000866 | Train loss: 0.9502 | Train acc: 52.75% | Val loss: 0.9255 | Val acc: 53.92% | LR: 0.000250
Epoch: 096 | MCC: -0.009887 | Train loss: 0.9497 | Train acc: 52.73% | Val loss: 0.9292 | Val acc: 53.51% | LR: 0.000242
Epoch: 097 | MCC: -0.018750 | Train loss: 0.9464 | Train acc: 52.95% | Val loss: 0.9329 | Val acc: 53.03% | LR: 0.000234
Epoch: 098 | MCC: -0.007531 | Train loss: 0.9496 | Train acc: 52.79% | Val loss: 0.9268 | Val acc: 53.71% | LR: 0.000226
Epoch: 099 | MCC: 0.001533 | Train loss: 0.9502 | Train acc: 52.70% | Val loss: 0.9236 | Val acc: 53.88% | LR: 0.000218
Epoch: 100 | MCC: -0.009804 | Train loss: 0.9482 | Train acc: 52.87% | Val loss: 0.9311 | Val acc: 53.67% | LR: 0.000210
Epoch: 101 | MCC: -0.009540 | Train loss: 0.9486 | Train acc: 52.83% | Val loss: 0.9304 | Val acc: 53.91% | LR: 0.000202
Epoch: 102 | MCC: 0.001618 | Train loss: 0.9473 | Train acc: 52.91% | Val loss: 0.9303 | Val acc: 54.21% | LR: 0.000195
Epoch: 103 | MCC: -0.001052 | Train loss: 0.9480 | Train acc: 52.86% | Val loss: 0.9274 | Val acc: 54.33% | LR: 0.000187
Epoch: 104 | MCC: 0.001766 | Train loss: 0.9452 | Train acc: 53.04% | Val loss: 0.9293 | Val acc: 54.18% | LR: 0.000180
Epoch: 105 | MCC: -0.002643 | Train loss: 0.9467 | Train acc: 52.93% | Val loss: 0.9329 | Val acc: 54.01% | LR: 0.000173
Epoch: 106 | MCC: -0.000902 | Train loss: 0.9469 | Train acc: 52.92% | Val loss: 0.9302 | Val acc: 54.24% | LR: 0.000165
Epoch: 107 | MCC: -0.005556 | Train loss: 0.9456 | Train acc: 52.97% | Val loss: 0.9321 | Val acc: 53.82% | LR: 0.000158
Epoch: 108 | MCC: 0.011228 | Train loss: 0.9464 | Train acc: 52.97% | Val loss: 0.9290 | Val acc: 54.53% | LR: 0.000151
Epoch: 109 | MCC: 0.000525 | Train loss: 0.9483 | Train acc: 52.91% | Val loss: 0.9278 | Val acc: 54.39% | LR: 0.000145
Epoch: 110 | MCC: -0.004088 | Train loss: 0.9494 | Train acc: 52.77% | Val loss: 0.9340 | Val acc: 53.97% | LR: 0.000138
Epoch: 111 | MCC: -0.002885 | Train loss: 0.9477 | Train acc: 52.92% | Val loss: 0.9340 | Val acc: 54.01% | LR: 0.000131
Epoch: 112 | MCC: -0.001306 | Train loss: 0.9484 | Train acc: 52.88% | Val loss: 0.9299 | Val acc: 54.09% | LR: 0.000125
Epoch: 113 | MCC: -0.004137 | Train loss: 0.9476 | Train acc: 52.92% | Val loss: 0.9337 | Val acc: 54.02% | LR: 0.000119
Epoch: 114 | MCC: -0.003860 | Train loss: 0.9482 | Train acc: 52.86% | Val loss: 0.9320 | Val acc: 54.04% | LR: 0.000112
Epoch: 115 | MCC: -0.008680 | Train loss: 0.9475 | Train acc: 52.90% | Val loss: 0.9298 | Val acc: 54.02% | LR: 0.000106
Epoch: 116 | MCC: -0.000895 | Train loss: 0.9459 | Train acc: 52.96% | Val loss: 0.9327 | Val acc: 54.13% | LR: 0.000101
Epoch: 117 | MCC: -0.003966 | Train loss: 0.9476 | Train acc: 52.86% | Val loss: 0.9325 | Val acc: 53.98% | LR: 0.000095
Epoch: 118 | MCC: -0.000484 | Train loss: 0.9442 | Train acc: 53.09% | Val loss: 0.9313 | Val acc: 54.07% | LR: 0.000089
Epoch: 119 | MCC: -0.003626 | Train loss: 0.9452 | Train acc: 53.03% | Val loss: 0.9334 | Val acc: 53.99% | LR: 0.000084
Epoch: 120 | MCC: -0.007608 | Train loss: 0.9466 | Train acc: 52.94% | Val loss: 0.9308 | Val acc: 54.01% | LR: 0.000079
Epoch: 121 | MCC: -0.002443 | Train loss: 0.9452 | Train acc: 52.99% | Val loss: 0.9302 | Val acc: 54.08% | LR: 0.000073
Epoch: 122 | MCC: -0.007384 | Train loss: 0.9473 | Train acc: 52.93% | Val loss: 0.9321 | Val acc: 53.95% | LR: 0.000069

[I 2025-10-05 10:46:51,582] Trial 63 finished with value: -0.0026675240078475326 and parameters: {'lr': 0.0008686023053820286, 'hidden_size': 57, 'dropout': 0.05420062195943218, 'weight_decay': 0.003356370820342756}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.024100 | Train loss: 0.9983 | Train acc: 50.45% | Val loss: 0.9764 | Val acc: 54.40% | LR: 0.000512
Epoch: 001 | MCC: 0.005623 | Train loss: 1.0377 | Train acc: 50.72% | Val loss: 0.9640 | Val acc: 53.88% | LR: 0.000512
Epoch: 002 | MCC: 0.017691 | Train loss: 1.0209 | Train acc: 50.72% | Val loss: 0.9720 | Val acc: 53.43% | LR: 0.000512
Epoch: 003 | MCC: 0.015633 | Train loss: 0.9987 | Train acc: 50.95% | Val loss: 0.9531 | Val acc: 53.70% | LR: 0.000511
Epoch: 004 | MCC: 0.011974 | Train loss: 1.0058 | Train acc: 50.89% | Val loss: 0.9544 | Val acc: 53.37% | LR: 0.000511
Epoch: 005 | MCC: 0.011066 | Train loss: 1.0020 | Train acc: 50.91% | Val loss: 0.9510 | Val acc: 53.50% | LR: 0.000510
Epoch: 006 | MCC: 0.024770 | Train loss: 0.9923 | Train acc: 50.81% | Val loss: 0.9528 | Val acc: 53.94% | LR: 0.000509
Epoch: 007 | MCC: 0.014259 | Train loss: 0.9904 | Train acc: 50.94% | Val loss: 0.9441 | Val acc: 53.67% | LR: 0.000509
Epoch: 008 | MCC: 0.019444 | Train loss: 0.9951 | Train acc: 50.88% | Val loss: 0.9466 | Val acc: 53.87% | LR: 0.000508
Epoch: 009 | MCC: 0.014849 | Train loss: 0.9889 | Train acc: 50.93% | Val loss: 0.9457 | Val acc: 53.76% | LR: 0.000507
Epoch: 010 | MCC: 0.012175 | Train loss: 0.9965 | Train acc: 50.87% | Val loss: 0.9463 | Val acc: 53.82% | LR: 0.000505
Epoch: 011 | MCC: 0.009679 | Train loss: 0.9879 | Train acc: 50.84% | Val loss: 0.9497 | Val acc: 53.86% | LR: 0.000504
Epoch: 012 | MCC: 0.016533 | Train loss: 0.9840 | Train acc: 50.95% | Val loss: 0.9467 | Val acc: 54.50% | LR: 0.000503
Epoch: 013 | MCC: 0.017583 | Train loss: 0.9836 | Train acc: 50.88% | Val loss: 0.9440 | Val acc: 54.57% | LR: 0.000501
Epoch: 014 | MCC: 0.021174 | Train loss: 0.9861 | Train acc: 50.71% | Val loss: 0.9464 | Val acc: 54.88% | LR: 0.000500
Epoch: 015 | MCC: 0.020173 | Train loss: 0.9825 | Train acc: 50.91% | Val loss: 0.9438 | Val acc: 55.04% | LR: 0.000498
Epoch: 016 | MCC: 0.017131 | Train loss: 0.9821 | Train acc: 50.98% | Val loss: 0.9393 | Val acc: 55.02% | LR: 0.000496
Epoch: 017 | MCC: 0.027985 | Train loss: 0.9824 | Train acc: 50.88% | Val loss: 0.9362 | Val acc: 55.30% | LR: 0.000494
Epoch: 018 | MCC: 0.022980 | Train loss: 0.9818 | Train acc: 50.97% | Val loss: 0.9321 | Val acc: 55.69% | LR: 0.000492
Epoch: 019 | MCC: 0.022494 | Train loss: 0.9825 | Train acc: 50.86% | Val loss: 0.9261 | Val acc: 55.78% | LR: 0.000490
Epoch: 020 | MCC: 0.021439 | Train loss: 0.9814 | Train acc: 50.88% | Val loss: 0.9220 | Val acc: 55.77% | LR: 0.000488
Epoch: 021 | MCC: 0.021690 | Train loss: 0.9811 | Train acc: 50.88% | Val loss: 0.9159 | Val acc: 55.83% | LR: 0.000486
Epoch: 022 | MCC: 0.027448 | Train loss: 0.9801 | Train acc: 50.87% | Val loss: 0.9113 | Val acc: 55.99% | LR: 0.000483
Epoch: 023 | MCC: 0.029093 | Train loss: 0.9792 | Train acc: 50.89% | Val loss: 0.9077 | Val acc: 56.31% | LR: 0.000481
Epoch: 024 | MCC: 0.024884 | Train loss: 0.9797 | Train acc: 50.85% | Val loss: 0.9051 | Val acc: 55.95% | LR: 0.000478
Epoch: 025 | MCC: 0.026969 | Train loss: 0.9801 | Train acc: 50.83% | Val loss: 0.9036 | Val acc: 56.46% | LR: 0.000475
Epoch: 026 | MCC: 0.028130 | Train loss: 0.9817 | Train acc: 50.87% | Val loss: 0.9018 | Val acc: 56.39% | LR: 0.000472
Epoch: 027 | MCC: 0.032374 | Train loss: 0.9793 | Train acc: 50.88% | Val loss: 0.8974 | Val acc: 56.59% | LR: 0.000470
Epoch: 028 | MCC: 0.027730 | Train loss: 0.9774 | Train acc: 51.13% | Val loss: 0.8952 | Val acc: 56.57% | LR: 0.000467
Epoch: 029 | MCC: 0.050863 | Train loss: 0.9785 | Train acc: 51.01% | Val loss: 0.8909 | Val acc: 57.88% | LR: 0.000463
Epoch: 030 | MCC: 0.059150 | Train loss: 0.9785 | Train acc: 50.92% | Val loss: 0.8870 | Val acc: 58.15% | LR: 0.000460
Epoch: 031 | MCC: 0.051845 | Train loss: 0.9818 | Train acc: 50.96% | Val loss: 0.8829 | Val acc: 58.75% | LR: 0.000457
Epoch: 032 | MCC: 0.038798 | Train loss: 0.9780 | Train acc: 51.06% | Val loss: 0.8821 | Val acc: 58.48% | LR: 0.000454
Epoch: 033 | MCC: 0.037809 | Train loss: 0.9770 | Train acc: 51.21% | Val loss: 0.8793 | Val acc: 58.11% | LR: 0.000450
Epoch: 034 | MCC: 0.038536 | Train loss: 0.9767 | Train acc: 51.21% | Val loss: 0.8744 | Val acc: 58.82% | LR: 0.000447
Epoch: 035 | MCC: 0.033943 | Train loss: 0.9769 | Train acc: 51.11% | Val loss: 0.8802 | Val acc: 57.65% | LR: 0.000443
Epoch: 036 | MCC: 0.015685 | Train loss: 0.9756 | Train acc: 51.24% | Val loss: 0.8846 | Val acc: 56.99% | LR: 0.000439
Epoch: 037 | MCC: -0.012812 | Train loss: 0.9767 | Train acc: 51.10% | Val loss: 0.8821 | Val acc: 56.88% | LR: 0.000435
Epoch: 038 | MCC: -0.024871 | Train loss: 0.9749 | Train acc: 51.33% | Val loss: 0.8863 | Val acc: 56.19% | LR: 0.000432
Epoch: 039 | MCC: -0.011215 | Train loss: 0.9810 | Train acc: 51.30% | Val loss: 0.8864 | Val acc: 56.89% | LR: 0.000428
Epoch: 040 | MCC: -0.001651 | Train loss: 0.9745 | Train acc: 51.20% | Val loss: 0.8728 | Val acc: 57.91% | LR: 0.000424
Epoch: 041 | MCC: 0.004124 | Train loss: 0.9839 | Train acc: 51.32% | Val loss: 0.8679 | Val acc: 58.13% | LR: 0.000420
Epoch: 042 | MCC: -0.019780 | Train loss: 0.9748 | Train acc: 51.35% | Val loss: 0.8681 | Val acc: 57.82% | LR: 0.000415
Epoch: 043 | MCC: 0.029754 | Train loss: 0.9738 | Train acc: 51.24% | Val loss: 0.8651 | Val acc: 58.11% | LR: 0.000411
Epoch: 044 | MCC: -0.004142 | Train loss: 0.9722 | Train acc: 51.34% | Val loss: 0.8784 | Val acc: 57.83% | LR: 0.000407
Epoch: 045 | MCC: 0.021088 | Train loss: 0.9706 | Train acc: 51.45% | Val loss: 0.8530 | Val acc: 59.37% | LR: 0.000403
Epoch: 046 | MCC: 0.001630 | Train loss: 0.9710 | Train acc: 51.41% | Val loss: 0.9356 | Val acc: 58.83% | LR: 0.000398
Epoch: 047 | MCC: -0.047043 | Train loss: 1.0179 | Train acc: 51.19% | Val loss: 1.2507 | Val acc: 51.66% | LR: 0.000394
Epoch: 048 | MCC: -0.039803 | Train loss: 1.0189 | Train acc: 50.39% | Val loss: 1.0024 | Val acc: 51.27% | LR: 0.000389
Epoch: 049 | MCC: -0.021703 | Train loss: 0.9876 | Train acc: 50.89% | Val loss: 0.9829 | Val acc: 54.59% | LR: 0.000384
Epoch: 050 | MCC: 0.000000 | Train loss: 0.9877 | Train acc: 50.49% | Val loss: 0.9127 | Val acc: 54.73% | LR: 0.000380
Epoch: 051 | MCC: 0.000000 | Train loss: 0.9869 | Train acc: 50.88% | Val loss: 0.9138 | Val acc: 54.73% | LR: 0.000375
Epoch: 052 | MCC: 0.000000 | Train loss: 0.9856 | Train acc: 50.76% | Val loss: 0.9167 | Val acc: 54.73% | LR: 0.000370
Epoch: 053 | MCC: 0.000000 | Train loss: 0.9841 | Train acc: 50.92% | Val loss: 0.9211 | Val acc: 54.73% | LR: 0.000365
Epoch: 054 | MCC: -0.017846 | Train loss: 0.9837 | Train acc: 51.02% | Val loss: 0.9283 | Val acc: 54.48% | LR: 0.000361
Epoch: 055 | MCC: 0.004168 | Train loss: 0.9825 | Train acc: 51.42% | Val loss: 0.9327 | Val acc: 55.09% | LR: 0.000356
Epoch: 056 | MCC: 0.013801 | Train loss: 0.9832 | Train acc: 51.62% | Val loss: 0.9428 | Val acc: 55.56% | LR: 0.000351
Epoch: 057 | MCC: 0.025844 | Train loss: 0.9844 | Train acc: 51.52% | Val loss: 0.9429 | Val acc: 56.41% | LR: 0.000346
Epoch: 058 | MCC: 0.017666 | Train loss: 0.9787 | Train acc: 51.66% | Val loss: 0.9448 | Val acc: 57.06% | LR: 0.000341
Epoch: 059 | MCC: 0.024158 | Train loss: 0.9766 | Train acc: 51.78% | Val loss: 0.9375 | Val acc: 57.49% | LR: 0.000336
Epoch: 060 | MCC: 0.033824 | Train loss: 0.9769 | Train acc: 51.64% | Val loss: 0.9351 | Val acc: 57.45% | LR: 0.000331
Epoch: 061 | MCC: 0.001441 | Train loss: 0.9782 | Train acc: 51.48% | Val loss: 0.9290 | Val acc: 57.22% | LR: 0.000325
Epoch: 062 | MCC: 0.038096 | Train loss: 0.9746 | Train acc: 51.81% | Val loss: 0.9240 | Val acc: 58.17% | LR: 0.000320
Epoch: 063 | MCC: 0.005410 | Train loss: 0.9752 | Train acc: 51.59% | Val loss: 0.9187 | Val acc: 57.62% | LR: 0.000315
Epoch: 064 | MCC: 0.007280 | Train loss: 0.9734 | Train acc: 51.71% | Val loss: 0.9108 | Val acc: 57.79% | LR: 0.000310
Epoch: 065 | MCC: 0.005151 | Train loss: 0.9715 | Train acc: 51.79% | Val loss: 0.9113 | Val acc: 57.67% | LR: 0.000305
Epoch: 066 | MCC: 0.007104 | Train loss: 0.9768 | Train acc: 51.61% | Val loss: 0.9058 | Val acc: 57.89% | LR: 0.000299
Epoch: 067 | MCC: 0.018457 | Train loss: 0.9747 | Train acc: 51.58% | Val loss: 0.9090 | Val acc: 57.82% | LR: 0.000294
Epoch: 068 | MCC: 0.012645 | Train loss: 0.9721 | Train acc: 51.83% | Val loss: 0.9011 | Val acc: 58.45% | LR: 0.000289
Epoch: 069 | MCC: 0.017946 | Train loss: 0.9721 | Train acc: 51.78% | Val loss: 0.9046 | Val acc: 57.66% | LR: 0.000283
Epoch: 070 | MCC: 0.020152 | Train loss: 0.9707 | Train acc: 51.91% | Val loss: 0.8997 | Val acc: 58.22% | LR: 0.000278
Epoch: 071 | MCC: -0.002734 | Train loss: 0.9687 | Train acc: 51.96% | Val loss: 0.9026 | Val acc: 57.96% | LR: 0.000273
Epoch: 072 | MCC: 0.019266 | Train loss: 0.9695 | Train acc: 51.98% | Val loss: 0.9075 | Val acc: 57.98% | LR: 0.000267
Epoch: 073 | MCC: 0.023796 | Train loss: 0.9699 | Train acc: 51.99% | Val loss: 0.9033 | Val acc: 58.03% | LR: 0.000262
Epoch: 074 | MCC: 0.006285 | Train loss: 0.9675 | Train acc: 51.95% | Val loss: 0.8819 | Val acc: 58.96% | LR: 0.000257
Epoch: 075 | MCC: 0.023727 | Train loss: 0.9684 | Train acc: 52.02% | Val loss: 0.8999 | Val acc: 58.13% | LR: 0.000251
Epoch: 076 | MCC: 0.017246 | Train loss: 0.9675 | Train acc: 52.03% | Val loss: 0.8808 | Val acc: 59.15% | LR: 0.000246
Epoch: 077 | MCC: 0.017572 | Train loss: 0.9664 | Train acc: 52.07% | Val loss: 0.8771 | Val acc: 59.59% | LR: 0.000241
Epoch: 078 | MCC: 0.029788 | Train loss: 1.0354 | Train acc: 51.95% | Val loss: 0.8642 | Val acc: 59.03% | LR: 0.000235
Epoch: 079 | MCC: 0.019955 | Train loss: 0.9749 | Train acc: 51.98% | Val loss: 0.8968 | Val acc: 57.30% | LR: 0.000230
Epoch: 080 | MCC: 0.016018 | Train loss: 0.9672 | Train acc: 52.10% | Val loss: 0.8957 | Val acc: 57.98% | LR: 0.000225
Epoch: 081 | MCC: 0.023085 | Train loss: 0.9675 | Train acc: 51.97% | Val loss: 0.8803 | Val acc: 59.31% | LR: 0.000219
Epoch: 082 | MCC: 0.022880 | Train loss: 0.9676 | Train acc: 52.09% | Val loss: 0.8725 | Val acc: 59.42% | LR: 0.000214
Epoch: 083 | MCC: 0.009104 | Train loss: 0.9661 | Train acc: 52.06% | Val loss: 0.8715 | Val acc: 59.51% | LR: 0.000209
Epoch: 084 | MCC: 0.036330 | Train loss: 0.9650 | Train acc: 52.13% | Val loss: 0.8729 | Val acc: 60.09% | LR: 0.000203
Epoch: 085 | MCC: 0.025162 | Train loss: 0.9644 | Train acc: 52.18% | Val loss: 0.8606 | Val acc: 59.67% | LR: 0.000198
Epoch: 086 | MCC: 0.042692 | Train loss: 0.9650 | Train acc: 52.18% | Val loss: 0.8742 | Val acc: 60.05% | LR: 0.000193
Epoch: 087 | MCC: 0.043464 | Train loss: 0.9657 | Train acc: 52.10% | Val loss: 0.8743 | Val acc: 59.69% | LR: 0.000188
Epoch: 088 | MCC: 0.039125 | Train loss: 0.9631 | Train acc: 52.22% | Val loss: 0.8568 | Val acc: 59.88% | LR: 0.000183
Epoch: 089 | MCC: 0.024880 | Train loss: 0.9654 | Train acc: 52.07% | Val loss: 0.8546 | Val acc: 59.16% | LR: 0.000178
Epoch: 090 | MCC: 0.025653 | Train loss: 0.9634 | Train acc: 52.20% | Val loss: 0.8587 | Val acc: 59.15% | LR: 0.000173
Epoch: 091 | MCC: 0.035055 | Train loss: 0.9633 | Train acc: 52.14% | Val loss: 0.8479 | Val acc: 59.03% | LR: 0.000168
Epoch: 092 | MCC: 0.036733 | Train loss: 0.9625 | Train acc: 52.25% | Val loss: 0.8655 | Val acc: 58.58% | LR: 0.000163
Epoch: 093 | MCC: 0.049126 | Train loss: 0.9661 | Train acc: 52.09% | Val loss: 0.8534 | Val acc: 59.05% | LR: 0.000158
Epoch: 094 | MCC: 0.045818 | Train loss: 0.9607 | Train acc: 52.35% | Val loss: 0.8492 | Val acc: 59.16% | LR: 0.000153
Epoch: 095 | MCC: 0.041574 | Train loss: 0.9621 | Train acc: 52.24% | Val loss: 0.8599 | Val acc: 59.12% | LR: 0.000148
Epoch: 096 | MCC: 0.042784 | Train loss: 0.9626 | Train acc: 52.21% | Val loss: 0.8516 | Val acc: 58.92% | LR: 0.000143
Epoch: 097 | MCC: 0.016158 | Train loss: 0.9616 | Train acc: 52.27% | Val loss: 0.8560 | Val acc: 58.51% | LR: 0.000138
Epoch: 098 | MCC: 0.043696 | Train loss: 0.9636 | Train acc: 52.12% | Val loss: 0.8498 | Val acc: 58.89% | LR: 0.000133
Epoch: 099 | MCC: 0.051271 | Train loss: 0.9622 | Train acc: 52.29% | Val loss: 0.8372 | Val acc: 59.47% | LR: 0.000129
Epoch: 100 | MCC: 0.040863 | Train loss: 0.9612 | Train acc: 52.23% | Val loss: 0.8465 | Val acc: 58.78% | LR: 0.000124
Epoch: 101 | MCC: 0.037704 | Train loss: 0.9629 | Train acc: 52.18% | Val loss: 0.8471 | Val acc: 58.81% | LR: 0.000120
Epoch: 102 | MCC: 0.046248 | Train loss: 0.9609 | Train acc: 52.25% | Val loss: 0.8442 | Val acc: 58.81% | LR: 0.000115
Epoch: 103 | MCC: 0.040845 | Train loss: 0.9592 | Train acc: 52.35% | Val loss: 0.8468 | Val acc: 58.70% | LR: 0.000111
Epoch: 104 | MCC: 0.043622 | Train loss: 0.9601 | Train acc: 52.36% | Val loss: 0.8405 | Val acc: 58.91% | LR: 0.000106
Epoch: 105 | MCC: 0.036136 | Train loss: 0.9605 | Train acc: 52.29% | Val loss: 0.8483 | Val acc: 58.66% | LR: 0.000102
Epoch: 106 | MCC: 0.039945 | Train loss: 0.9664 | Train acc: 52.16% | Val loss: 0.8415 | Val acc: 58.61% | LR: 0.000098
Epoch: 107 | MCC: 0.044040 | Train loss: 0.9572 | Train acc: 52.44% | Val loss: 0.8476 | Val acc: 58.63% | LR: 0.000094
Epoch: 108 | MCC: 0.027210 | Train loss: 0.9613 | Train acc: 52.20% | Val loss: 0.8437 | Val acc: 58.70% | LR: 0.000090
Epoch: 109 | MCC: 0.034424 | Train loss: 0.9570 | Train acc: 52.48% | Val loss: 0.8399 | Val acc: 58.76% | LR: 0.000086
Epoch: 110 | MCC: 0.033121 | Train loss: 0.9584 | Train acc: 52.34% | Val loss: 0.8383 | Val acc: 58.76% | LR: 0.000082
Epoch: 111 | MCC: 0.047178 | Train loss: 0.9616 | Train acc: 52.24% | Val loss: 0.8444 | Val acc: 58.68% | LR: 0.000078
Epoch: 112 | MCC: 0.050031 | Train loss: 0.9583 | Train acc: 52.37% | Val loss: 0.8312 | Val acc: 59.39% | LR: 0.000074
Epoch: 113 | MCC: 0.049737 | Train loss: 0.9586 | Train acc: 52.36% | Val loss: 0.8362 | Val acc: 59.05% | LR: 0.000070
Epoch: 114 | MCC: 0.048206 | Train loss: 0.9601 | Train acc: 52.29% | Val loss: 0.8345 | Val acc: 59.05% | LR: 0.000067
Epoch: 115 | MCC: 0.044272 | Train loss: 0.9588 | Train acc: 52.38% | Val loss: 0.8330 | Val acc: 59.01% | LR: 0.000063
Epoch: 116 | MCC: 0.049734 | Train loss: 0.9601 | Train acc: 52.29% | Val loss: 0.8337 | Val acc: 58.92% | LR: 0.000060
Epoch: 117 | MCC: 0.048370 | Train loss: 0.9610 | Train acc: 52.25% | Val loss: 0.8317 | Val acc: 59.11% | LR: 0.000056
Epoch: 118 | MCC: 0.045859 | Train loss: 0.9589 | Train acc: 52.37% | Val loss: 0.8347 | Val acc: 58.97% | LR: 0.000053
Epoch: 119 | MCC: 0.045871 | Train loss: 0.9581 | Train acc: 52.39% | Val loss: 0.8315 | Val acc: 59.26% | LR: 0.000050
Epoch: 120 | MCC: 0.044863 | Train loss: 0.9588 | Train acc: 52.38% | Val loss: 0.8306 | Val acc: 59.25% | LR: 0.000047
Epoch: 121 | MCC: 0.046368 | Train loss: 0.9615 | Train acc: 52.24% | Val loss: 0.8328 | Val acc: 58.87% | LR: 0.000044
Epoch: 122 | MCC: 0.051837 | Train loss: 0.9619 | Train acc: 52.24% | Val loss: 0.8314 | Val acc: 59.14% | LR: 0.000041
Epoch: 123 | MCC: 0.048105 | Train loss: 0.9606 | Train acc: 52.31% | Val loss: 0.8329 | Val acc: 58.92% | LR: 0.000038
Epoch: 124 | MCC: 0.052428 | Train loss: 0.9584 | Train acc: 52.44% | Val loss: 0.8287 | Val acc: 59.38% | LR: 0.000035
Epoch: 125 | MCC: 0.050990 | Train loss: 0.9601 | Train acc: 52.34% | Val loss: 0.8314 | Val acc: 59.24% | LR: 0.000033
Epoch: 126 | MCC: 0.046081 | Train loss: 0.9585 | Train acc: 52.45% | Val loss: 0.8318 | Val acc: 59.30% | LR: 0.000030
Epoch: 127 | MCC: 0.046559 | Train loss: 0.9602 | Train acc: 52.29% | Val loss: 0.8309 | Val acc: 59.02% | LR: 0.000028
Epoch: 128 | MCC: 0.043305 | Train loss: 0.9587 | Train acc: 52.42% | Val loss: 0.8319 | Val acc: 59.14% | LR: 0.000025
Epoch: 129 | MCC: 0.043028 | Train loss: 0.9572 | Train acc: 52.50% | Val loss: 0.8313 | Val acc: 59.20% | LR: 0.000023
Epoch: 130 | MCC: 0.046772 | Train loss: 0.9578 | Train acc: 52.45% | Val loss: 0.8312 | Val acc: 59.31% | LR: 0.000021
Epoch: 131 | MCC: 0.047508 | Train loss: 0.9605 | Train acc: 52.55% | Val loss: 0.8284 | Val acc: 59.34% | LR: 0.000019
Epoch: 132 | MCC: 0.047053 | Train loss: 0.9585 | Train acc: 52.41% | Val loss: 0.8290 | Val acc: 59.31% | LR: 0.000017
Epoch: 133 | MCC: 0.041074 | Train loss: 0.9580 | Train acc: 52.49% | Val loss: 0.8289 | Val acc: 59.13% | LR: 0.000015
Epoch: 134 | MCC: 0.045302 | Train loss: 0.9568 | Train acc: 52.53% | Val loss: 0.8286 | Val acc: 59.31% | LR: 0.000014
Epoch: 135 | MCC: 0.043861 | Train loss: 0.9568 | Train acc: 52.49% | Val loss: 0.8281 | Val acc: 59.26% | LR: 0.000012
Epoch: 136 | MCC: 0.045464 | Train loss: 0.9583 | Train acc: 52.41% | Val loss: 0.8283 | Val acc: 59.31% | LR: 0.000010
Epoch: 137 | MCC: 0.046954 | Train loss: 0.9589 | Train acc: 52.40% | Val loss: 0.8279 | Val acc: 59.31% | LR: 0.000009
Epoch: 138 | MCC: 0.047674 | Train loss: 0.9570 | Train acc: 52.46% | Val loss: 0.8276 | Val acc: 59.34% | LR: 0.000008
Epoch: 139 | MCC: 0.048267 | Train loss: 0.9570 | Train acc: 52.50% | Val loss: 0.8277 | Val acc: 59.36% | LR: 0.000007
Epoch: 140 | MCC: 0.045423 | Train loss: 0.9589 | Train acc: 52.39% | Val loss: 0.8273 | Val acc: 59.29% | LR: 0.000006
Epoch: 141 | MCC: 0.044323 | Train loss: 0.9570 | Train acc: 52.50% | Val loss: 0.8275 | Val acc: 59.26% | LR: 0.000005
Epoch: 142 | MCC: 0.044610 | Train loss: 0.9593 | Train acc: 52.47% | Val loss: 0.8275 | Val acc: 59.31% | LR: 0.000004
Epoch: 143 | MCC: 0.043475 | Train loss: 0.9586 | Train acc: 52.43% | Val loss: 0.8278 | Val acc: 59.24% | LR: 0.000003
Epoch: 144 | MCC: 0.043475 | Train loss: 0.9584 | Train acc: 52.46% | Val loss: 0.8277 | Val acc: 59.24% | LR: 0.000002
Epoch: 145 | MCC: 0.043475 | Train loss: 0.9579 | Train acc: 52.46% | Val loss: 0.8276 | Val acc: 59.24% | LR: 0.000002
Epoch: 146 | MCC: 0.043904 | Train loss: 0.9675 | Train acc: 52.43% | Val loss: 0.8276 | Val acc: 59.29% | LR: 0.000002
Epoch: 147 | MCC: 0.042762 | Train loss: 0.9574 | Train acc: 52.46% | Val loss: 0.8275 | Val acc: 59.24% | LR: 0.000001
Epoch: 148 | MCC: 0.043904 | Train loss: 0.9594 | Train acc: 52.39% | Val loss: 0.8275 | Val acc: 59.29% | LR: 0.000001
Epoch: 149 | MCC: 0.044566 | Train loss: 0.9600 | Train acc: 52.37% | Val loss: 0.8275 | Val acc: 59.31% | LR: 0.000001

[I 2025-10-05 10:48:56,618] Trial 64 finished with value: 0.044566284166648984 and parameters: {'lr': 0.0005122402450624669, 'hidden_size': 61, 'dropout': 0.1629720500176577, 'weight_decay': 0.01800251070060325}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.010339 | Train loss: 1.0015 | Train acc: 50.22% | Val loss: 0.9530 | Val acc: 54.35% | LR: 0.001209
Epoch: 001 | MCC: 0.012585 | Train loss: 0.9869 | Train acc: 50.85% | Val loss: 0.9464 | Val acc: 54.68% | LR: 0.001209
Epoch: 002 | MCC: 0.019727 | Train loss: 0.9854 | Train acc: 50.63% | Val loss: 0.9427 | Val acc: 55.23% | LR: 0.001208
Epoch: 003 | MCC: 0.010172 | Train loss: 0.9826 | Train acc: 50.81% | Val loss: 0.9230 | Val acc: 55.07% | LR: 0.001207
Epoch: 004 | MCC: 0.021070 | Train loss: 0.9826 | Train acc: 51.09% | Val loss: 0.9148 | Val acc: 55.98% | LR: 0.001206
Epoch: 005 | MCC: 0.029634 | Train loss: 1.0064 | Train acc: 51.06% | Val loss: 0.9171 | Val acc: 55.88% | LR: 0.001205
Epoch: 006 | MCC: 0.026920 | Train loss: 0.9795 | Train acc: 51.55% | Val loss: 0.8900 | Val acc: 56.58% | LR: 0.001203
Epoch: 007 | MCC: 0.042394 | Train loss: 0.9792 | Train acc: 51.58% | Val loss: 0.8820 | Val acc: 58.02% | LR: 0.001201
Epoch: 008 | MCC: 0.000026 | Train loss: 0.9780 | Train acc: 51.75% | Val loss: 0.8680 | Val acc: 56.73% | LR: 0.001199
Epoch: 009 | MCC: 0.001764 | Train loss: 0.9756 | Train acc: 51.80% | Val loss: 0.8815 | Val acc: 56.70% | LR: 0.001196
Epoch: 010 | MCC: 0.001101 | Train loss: 0.9767 | Train acc: 51.68% | Val loss: 0.8732 | Val acc: 56.65% | LR: 0.001193
Epoch: 011 | MCC: 0.006450 | Train loss: 0.9759 | Train acc: 51.80% | Val loss: 0.8877 | Val acc: 55.68% | LR: 0.001190
Epoch: 012 | MCC: 0.044255 | Train loss: 0.9792 | Train acc: 51.58% | Val loss: 0.8449 | Val acc: 58.83% | LR: 0.001187
Epoch: 013 | MCC: 0.028727 | Train loss: 0.9779 | Train acc: 51.68% | Val loss: 0.8577 | Val acc: 58.07% | LR: 0.001184
Epoch: 014 | MCC: 0.048995 | Train loss: 1.0080 | Train acc: 50.71% | Val loss: 1.0407 | Val acc: 46.19% | LR: 0.001180
Epoch: 015 | MCC: -0.004297 | Train loss: 0.9935 | Train acc: 50.76% | Val loss: 1.0195 | Val acc: 45.71% | LR: 0.001176
Epoch: 016 | MCC: 0.024133 | Train loss: 0.9873 | Train acc: 50.53% | Val loss: 1.0423 | Val acc: 46.42% | LR: 0.001171
Epoch: 017 | MCC: 0.036272 | Train loss: 0.9869 | Train acc: 50.67% | Val loss: 1.0132 | Val acc: 48.97% | LR: 0.001167
Epoch: 018 | MCC: -0.024384 | Train loss: 0.9886 | Train acc: 50.99% | Val loss: 1.0126 | Val acc: 47.65% | LR: 0.001162
Epoch: 019 | MCC: -0.013558 | Train loss: 0.9882 | Train acc: 50.83% | Val loss: 1.0203 | Val acc: 49.26% | LR: 0.001157
Epoch: 020 | MCC: 0.023182 | Train loss: 0.9947 | Train acc: 50.73% | Val loss: 1.0405 | Val acc: 47.47% | LR: 0.001152
Epoch: 021 | MCC: 0.029587 | Train loss: 0.9921 | Train acc: 50.77% | Val loss: 1.0135 | Val acc: 48.65% | LR: 0.001146
Epoch: 022 | MCC: 0.060271 | Train loss: 0.9906 | Train acc: 50.66% | Val loss: 0.9965 | Val acc: 51.51% | LR: 0.001141
Epoch: 023 | MCC: 0.041966 | Train loss: 0.9887 | Train acc: 50.98% | Val loss: 0.9545 | Val acc: 55.28% | LR: 0.001135
Epoch: 024 | MCC: 0.024185 | Train loss: 0.9861 | Train acc: 50.92% | Val loss: 0.9410 | Val acc: 55.21% | LR: 0.001128
Epoch: 025 | MCC: 0.018355 | Train loss: 0.9832 | Train acc: 50.86% | Val loss: 0.9179 | Val acc: 55.45% | LR: 0.001122
Epoch: 026 | MCC: 0.028812 | Train loss: 0.9861 | Train acc: 51.03% | Val loss: 0.9687 | Val acc: 55.09% | LR: 0.001115
Epoch: 027 | MCC: 0.013680 | Train loss: 0.9856 | Train acc: 51.04% | Val loss: 1.0327 | Val acc: 54.26% | LR: 0.001108
Epoch: 028 | MCC: 0.012189 | Train loss: 0.9859 | Train acc: 50.89% | Val loss: 0.9265 | Val acc: 54.20% | LR: 0.001101
Epoch: 029 | MCC: 0.018915 | Train loss: 0.9837 | Train acc: 50.98% | Val loss: 0.9276 | Val acc: 54.50% | LR: 0.001094
Epoch: 030 | MCC: 0.015687 | Train loss: 0.9835 | Train acc: 50.92% | Val loss: 0.9210 | Val acc: 54.31% | LR: 0.001086
Epoch: 031 | MCC: 0.019990 | Train loss: 0.9807 | Train acc: 50.99% | Val loss: 0.9175 | Val acc: 54.69% | LR: 0.001079
Epoch: 032 | MCC: 0.021580 | Train loss: 0.9796 | Train acc: 51.03% | Val loss: 0.9234 | Val acc: 54.34% | LR: 0.001071
Epoch: 033 | MCC: 0.016334 | Train loss: 0.9806 | Train acc: 50.99% | Val loss: 0.9192 | Val acc: 54.85% | LR: 0.001063
Epoch: 034 | MCC: 0.030280 | Train loss: 0.9794 | Train acc: 51.05% | Val loss: 0.9229 | Val acc: 55.25% | LR: 0.001054
Epoch: 035 | MCC: 0.029775 | Train loss: 0.9839 | Train acc: 50.87% | Val loss: 0.9702 | Val acc: 55.22% | LR: 0.001046
Epoch: 036 | MCC: 0.034863 | Train loss: 0.9875 | Train acc: 50.96% | Val loss: 0.9459 | Val acc: 55.53% | LR: 0.001037
Epoch: 037 | MCC: 0.040626 | Train loss: 0.9828 | Train acc: 50.90% | Val loss: 0.9226 | Val acc: 55.85% | LR: 0.001028
Epoch: 038 | MCC: 0.024049 | Train loss: 0.9809 | Train acc: 51.15% | Val loss: 0.9225 | Val acc: 55.29% | LR: 0.001019
Epoch: 039 | MCC: 0.031058 | Train loss: 0.9837 | Train acc: 50.94% | Val loss: 0.9175 | Val acc: 55.35% | LR: 0.001009
Epoch: 040 | MCC: 0.034441 | Train loss: 0.9820 | Train acc: 51.10% | Val loss: 0.9259 | Val acc: 55.23% | LR: 0.001000
Epoch: 041 | MCC: 0.039380 | Train loss: 0.9819 | Train acc: 50.91% | Val loss: 0.9132 | Val acc: 55.42% | LR: 0.000990
Epoch: 042 | MCC: 0.045990 | Train loss: 0.9797 | Train acc: 50.97% | Val loss: 0.8965 | Val acc: 56.42% | LR: 0.000980
Epoch: 043 | MCC: 0.028507 | Train loss: 0.9821 | Train acc: 50.90% | Val loss: 0.9302 | Val acc: 55.23% | LR: 0.000970
Epoch: 044 | MCC: 0.031101 | Train loss: 0.9829 | Train acc: 50.95% | Val loss: 0.9144 | Val acc: 55.37% | LR: 0.000960
Epoch: 045 | MCC: 0.026101 | Train loss: 0.9811 | Train acc: 50.92% | Val loss: 0.9081 | Val acc: 56.10% | LR: 0.000950
Epoch: 046 | MCC: 0.029750 | Train loss: 0.9789 | Train acc: 51.19% | Val loss: 0.9137 | Val acc: 56.45% | LR: 0.000939
Epoch: 047 | MCC: 0.016930 | Train loss: 0.9793 | Train acc: 51.07% | Val loss: 0.9243 | Val acc: 56.29% | LR: 0.000929
Epoch: 048 | MCC: 0.016953 | Train loss: 0.9778 | Train acc: 51.23% | Val loss: 0.9175 | Val acc: 56.14% | LR: 0.000918
Epoch: 049 | MCC: 0.016753 | Train loss: 0.9829 | Train acc: 50.95% | Val loss: 0.9223 | Val acc: 56.06% | LR: 0.000907
Epoch: 050 | MCC: 0.011159 | Train loss: 0.9811 | Train acc: 50.94% | Val loss: 0.9185 | Val acc: 55.70% | LR: 0.000896
Epoch: 051 | MCC: 0.014836 | Train loss: 0.9816 | Train acc: 51.07% | Val loss: 0.9149 | Val acc: 56.31% | LR: 0.000885
Epoch: 052 | MCC: -0.007359 | Train loss: 0.9797 | Train acc: 51.10% | Val loss: 0.9424 | Val acc: 54.51% | LR: 0.000874
Epoch: 053 | MCC: -0.020125 | Train loss: 0.9806 | Train acc: 50.93% | Val loss: 0.9269 | Val acc: 54.61% | LR: 0.000862
Epoch: 054 | MCC: -0.006183 | Train loss: 0.9794 | Train acc: 51.04% | Val loss: 0.9498 | Val acc: 54.46% | LR: 0.000851
Epoch: 055 | MCC: 0.044271 | Train loss: 0.9816 | Train acc: 50.94% | Val loss: 0.9177 | Val acc: 56.41% | LR: 0.000839
Epoch: 056 | MCC: 0.030836 | Train loss: 0.9773 | Train acc: 51.10% | Val loss: 0.9201 | Val acc: 55.81% | LR: 0.000828
Epoch: 057 | MCC: 0.002787 | Train loss: 0.9779 | Train acc: 51.05% | Val loss: 0.9046 | Val acc: 55.73% | LR: 0.000816
Epoch: 058 | MCC: -0.005347 | Train loss: 0.9783 | Train acc: 50.98% | Val loss: 0.9073 | Val acc: 54.37% | LR: 0.000804
Epoch: 059 | MCC: -0.012033 | Train loss: 0.9772 | Train acc: 51.15% | Val loss: 0.9135 | Val acc: 54.01% | LR: 0.000792
Epoch: 060 | MCC: -0.010698 | Train loss: 0.9780 | Train acc: 51.04% | Val loss: 0.9052 | Val acc: 54.32% | LR: 0.000780
Epoch: 061 | MCC: -0.007377 | Train loss: 0.9775 | Train acc: 51.13% | Val loss: 0.9072 | Val acc: 54.37% | LR: 0.000768
Epoch: 062 | MCC: -0.021557 | Train loss: 0.9767 | Train acc: 51.12% | Val loss: 0.9117 | Val acc: 53.92% | LR: 0.000755
Epoch: 063 | MCC: -0.021814 | Train loss: 0.9756 | Train acc: 51.25% | Val loss: 0.9170 | Val acc: 53.82% | LR: 0.000743
Epoch: 064 | MCC: -0.032590 | Train loss: 0.9796 | Train acc: 51.09% | Val loss: 0.9180 | Val acc: 53.12% | LR: 0.000731
Epoch: 065 | MCC: -0.030834 | Train loss: 0.9775 | Train acc: 50.99% | Val loss: 0.9288 | Val acc: 52.89% | LR: 0.000718
Epoch: 066 | MCC: -0.024206 | Train loss: 0.9770 | Train acc: 50.93% | Val loss: 0.9306 | Val acc: 53.60% | LR: 0.000706
Epoch: 067 | MCC: -0.027477 | Train loss: 0.9741 | Train acc: 51.47% | Val loss: 0.9208 | Val acc: 53.32% | LR: 0.000693
Epoch: 068 | MCC: -0.033374 | Train loss: 0.9755 | Train acc: 51.70% | Val loss: 0.9215 | Val acc: 53.21% | LR: 0.000681
Epoch: 069 | MCC: -0.026769 | Train loss: 0.9755 | Train acc: 51.45% | Val loss: 0.9510 | Val acc: 52.09% | LR: 0.000668
Epoch: 070 | MCC: -0.020473 | Train loss: 0.9756 | Train acc: 51.43% | Val loss: 0.9131 | Val acc: 53.47% | LR: 0.000656
Epoch: 071 | MCC: -0.021438 | Train loss: 0.9747 | Train acc: 51.98% | Val loss: 0.9136 | Val acc: 53.52% | LR: 0.000643
Epoch: 072 | MCC: -0.026245 | Train loss: 0.9763 | Train acc: 51.68% | Val loss: 0.9324 | Val acc: 52.59% | LR: 0.000630
Epoch: 073 | MCC: -0.013664 | Train loss: 0.9745 | Train acc: 51.93% | Val loss: 0.9315 | Val acc: 53.01% | LR: 0.000618
Epoch: 074 | MCC: -0.019832 | Train loss: 0.9736 | Train acc: 51.83% | Val loss: 0.9304 | Val acc: 53.40% | LR: 0.000605
Epoch: 075 | MCC: -0.025347 | Train loss: 0.9739 | Train acc: 51.84% | Val loss: 0.9245 | Val acc: 53.09% | LR: 0.000593
Epoch: 076 | MCC: -0.014744 | Train loss: 0.9751 | Train acc: 51.84% | Val loss: 0.9266 | Val acc: 53.48% | LR: 0.000580
Epoch: 077 | MCC: -0.012071 | Train loss: 0.9757 | Train acc: 51.14% | Val loss: 0.9153 | Val acc: 53.68% | LR: 0.000567
Epoch: 078 | MCC: -0.018570 | Train loss: 0.9752 | Train acc: 51.35% | Val loss: 0.9489 | Val acc: 52.54% | LR: 0.000555
Epoch: 079 | MCC: -0.000564 | Train loss: 0.9751 | Train acc: 51.52% | Val loss: 0.9128 | Val acc: 53.73% | LR: 0.000542
Epoch: 080 | MCC: -0.003397 | Train loss: 0.9779 | Train acc: 51.46% | Val loss: 0.9097 | Val acc: 54.16% | LR: 0.000529
Epoch: 081 | MCC: -0.007315 | Train loss: 0.9853 | Train acc: 51.73% | Val loss: 0.9228 | Val acc: 53.29% | LR: 0.000517
Epoch: 082 | MCC: -0.014742 | Train loss: 0.9791 | Train acc: 51.64% | Val loss: 0.9145 | Val acc: 53.36% | LR: 0.000504
Epoch: 083 | MCC: -0.009761 | Train loss: 0.9761 | Train acc: 51.48% | Val loss: 0.9135 | Val acc: 54.01% | LR: 0.000492
Epoch: 084 | MCC: -0.021715 | Train loss: 0.9751 | Train acc: 51.48% | Val loss: 0.9237 | Val acc: 52.96% | LR: 0.000480
Epoch: 085 | MCC: -0.009467 | Train loss: 0.9794 | Train acc: 51.80% | Val loss: 0.9115 | Val acc: 54.00% | LR: 0.000467
Epoch: 086 | MCC: -0.012938 | Train loss: 0.9757 | Train acc: 50.92% | Val loss: 0.9194 | Val acc: 53.49% | LR: 0.000455

[I 2025-10-05 10:50:28,845] Trial 65 finished with value: -0.012727059714961797 and parameters: {'lr': 0.001209319750161348, 'hidden_size': 104, 'dropout': 0.3341920490693431, 'weight_decay': 0.006911107708472125}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.019361 | Train loss: 0.9976 | Train acc: 50.81% | Val loss: 1.0079 | Val acc: 45.30% | LR: 0.000272
Epoch: 001 | MCC: 0.039449 | Train loss: 0.9960 | Train acc: 51.25% | Val loss: 1.0033 | Val acc: 48.27% | LR: 0.000272
Epoch: 002 | MCC: 0.039136 | Train loss: 0.9942 | Train acc: 50.79% | Val loss: 0.9961 | Val acc: 52.95% | LR: 0.000272
Epoch: 003 | MCC: 0.034594 | Train loss: 0.9911 | Train acc: 50.71% | Val loss: 0.9906 | Val acc: 53.62% | LR: 0.000271
Epoch: 004 | MCC: 0.035189 | Train loss: 0.9863 | Train acc: 50.98% | Val loss: 0.9801 | Val acc: 54.64% | LR: 0.000271
Epoch: 005 | MCC: 0.033820 | Train loss: 0.9845 | Train acc: 50.91% | Val loss: 0.9661 | Val acc: 55.15% | LR: 0.000271
Epoch: 006 | MCC: 0.027171 | Train loss: 0.9834 | Train acc: 50.79% | Val loss: 0.9557 | Val acc: 55.21% | LR: 0.000270
Epoch: 007 | MCC: 0.026200 | Train loss: 0.9815 | Train acc: 51.01% | Val loss: 0.9452 | Val acc: 55.46% | LR: 0.000270
Epoch: 008 | MCC: 0.023717 | Train loss: 0.9823 | Train acc: 50.82% | Val loss: 0.9407 | Val acc: 55.19% | LR: 0.000269
Epoch: 009 | MCC: 0.024255 | Train loss: 0.9795 | Train acc: 50.98% | Val loss: 0.9385 | Val acc: 55.52% | LR: 0.000269
Epoch: 010 | MCC: 0.021129 | Train loss: 0.9797 | Train acc: 51.04% | Val loss: 0.9360 | Val acc: 55.50% | LR: 0.000268
Epoch: 011 | MCC: 0.023173 | Train loss: 0.9793 | Train acc: 50.94% | Val loss: 0.9309 | Val acc: 55.73% | LR: 0.000268
Epoch: 012 | MCC: 0.019181 | Train loss: 0.9792 | Train acc: 50.98% | Val loss: 0.9248 | Val acc: 55.77% | LR: 0.000267
Epoch: 013 | MCC: 0.019403 | Train loss: 0.9777 | Train acc: 50.97% | Val loss: 0.9183 | Val acc: 55.89% | LR: 0.000266
Epoch: 014 | MCC: 0.015792 | Train loss: 0.9776 | Train acc: 50.93% | Val loss: 0.9140 | Val acc: 56.02% | LR: 0.000265
Epoch: 015 | MCC: 0.015455 | Train loss: 0.9780 | Train acc: 50.99% | Val loss: 0.9076 | Val acc: 55.99% | LR: 0.000264
Epoch: 016 | MCC: 0.014268 | Train loss: 0.9784 | Train acc: 50.84% | Val loss: 0.9007 | Val acc: 56.44% | LR: 0.000263
Epoch: 017 | MCC: 0.022803 | Train loss: 0.9763 | Train acc: 51.06% | Val loss: 0.9030 | Val acc: 56.68% | LR: 0.000262
Epoch: 018 | MCC: 0.044858 | Train loss: 0.9760 | Train acc: 51.08% | Val loss: 0.8951 | Val acc: 57.81% | LR: 0.000261
Epoch: 019 | MCC: 0.036070 | Train loss: 0.9759 | Train acc: 51.62% | Val loss: 0.8886 | Val acc: 58.04% | LR: 0.000260
Epoch: 020 | MCC: 0.045187 | Train loss: 0.9748 | Train acc: 51.74% | Val loss: 0.8794 | Val acc: 58.36% | LR: 0.000259
Epoch: 021 | MCC: 0.032334 | Train loss: 0.9743 | Train acc: 51.84% | Val loss: 0.8816 | Val acc: 57.96% | LR: 0.000258
Epoch: 022 | MCC: 0.031960 | Train loss: 0.9741 | Train acc: 51.84% | Val loss: 0.8728 | Val acc: 57.84% | LR: 0.000256
Epoch: 023 | MCC: 0.027888 | Train loss: 0.9742 | Train acc: 51.72% | Val loss: 0.8690 | Val acc: 57.65% | LR: 0.000255
Epoch: 024 | MCC: 0.014896 | Train loss: 0.9732 | Train acc: 51.78% | Val loss: 0.8663 | Val acc: 57.71% | LR: 0.000254
Epoch: 025 | MCC: 0.012630 | Train loss: 0.9742 | Train acc: 51.74% | Val loss: 0.8719 | Val acc: 57.57% | LR: 0.000252
Epoch: 026 | MCC: 0.007309 | Train loss: 0.9723 | Train acc: 51.75% | Val loss: 0.8712 | Val acc: 57.38% | LR: 0.000251
Epoch: 027 | MCC: 0.019932 | Train loss: 0.9741 | Train acc: 51.98% | Val loss: 0.8642 | Val acc: 57.77% | LR: 0.000249
Epoch: 028 | MCC: 0.015805 | Train loss: 0.9708 | Train acc: 52.03% | Val loss: 0.8696 | Val acc: 57.86% | LR: 0.000248
Epoch: 029 | MCC: 0.019628 | Train loss: 0.9719 | Train acc: 51.88% | Val loss: 0.8615 | Val acc: 58.54% | LR: 0.000246
Epoch: 030 | MCC: 0.027149 | Train loss: 1.0011 | Train acc: 51.93% | Val loss: 0.8662 | Val acc: 57.93% | LR: 0.000244
Epoch: 031 | MCC: 0.018150 | Train loss: 1.0222 | Train acc: 51.71% | Val loss: 0.8523 | Val acc: 58.52% | LR: 0.000243
Epoch: 032 | MCC: 0.020906 | Train loss: 0.9756 | Train acc: 51.96% | Val loss: 0.8565 | Val acc: 58.25% | LR: 0.000241
Epoch: 033 | MCC: 0.026715 | Train loss: 0.9704 | Train acc: 51.96% | Val loss: 0.8420 | Val acc: 59.01% | LR: 0.000239
Epoch: 034 | MCC: 0.031214 | Train loss: 0.9703 | Train acc: 51.94% | Val loss: 0.8508 | Val acc: 58.64% | LR: 0.000237
Epoch: 035 | MCC: 0.027054 | Train loss: 0.9690 | Train acc: 52.01% | Val loss: 0.8442 | Val acc: 58.74% | LR: 0.000235
Epoch: 036 | MCC: 0.046224 | Train loss: 0.9711 | Train acc: 52.05% | Val loss: 0.8345 | Val acc: 59.88% | LR: 0.000233
Epoch: 037 | MCC: 0.043281 | Train loss: 0.9681 | Train acc: 52.00% | Val loss: 0.8305 | Val acc: 59.76% | LR: 0.000231
Epoch: 038 | MCC: 0.022343 | Train loss: 0.9684 | Train acc: 52.18% | Val loss: 0.8340 | Val acc: 58.74% | LR: 0.000229
Epoch: 039 | MCC: 0.027079 | Train loss: 0.9812 | Train acc: 52.09% | Val loss: 0.8508 | Val acc: 57.91% | LR: 0.000227
Epoch: 040 | MCC: 0.024754 | Train loss: 0.9752 | Train acc: 51.89% | Val loss: 0.8572 | Val acc: 57.59% | LR: 0.000225
Epoch: 041 | MCC: 0.045227 | Train loss: 0.9692 | Train acc: 52.00% | Val loss: 0.8141 | Val acc: 60.42% | LR: 0.000223
Epoch: 042 | MCC: 0.064470 | Train loss: 0.9666 | Train acc: 52.07% | Val loss: 0.8161 | Val acc: 60.53% | LR: 0.000221
Epoch: 043 | MCC: 0.033539 | Train loss: 1.0105 | Train acc: 52.22% | Val loss: 0.8195 | Val acc: 59.75% | LR: 0.000218
Epoch: 044 | MCC: 0.056095 | Train loss: 0.9724 | Train acc: 52.03% | Val loss: 0.8103 | Val acc: 60.68% | LR: 0.000216
Epoch: 045 | MCC: 0.043367 | Train loss: 0.9658 | Train acc: 52.10% | Val loss: 0.8217 | Val acc: 59.69% | LR: 0.000214
Epoch: 046 | MCC: 0.056036 | Train loss: 0.9667 | Train acc: 51.99% | Val loss: 0.8280 | Val acc: 59.36% | LR: 0.000211
Epoch: 047 | MCC: 0.029844 | Train loss: 0.9673 | Train acc: 51.99% | Val loss: 0.8165 | Val acc: 59.83% | LR: 0.000209
Epoch: 048 | MCC: 0.055621 | Train loss: 0.9655 | Train acc: 52.14% | Val loss: 0.8191 | Val acc: 59.71% | LR: 0.000207
Epoch: 049 | MCC: 0.079540 | Train loss: 1.0178 | Train acc: 52.09% | Val loss: 0.8194 | Val acc: 60.17% | LR: 0.000204
Epoch: 050 | MCC: 0.018037 | Train loss: 0.9674 | Train acc: 52.09% | Val loss: 0.8295 | Val acc: 59.09% | LR: 0.000202
Epoch: 051 | MCC: 0.015315 | Train loss: 0.9710 | Train acc: 51.78% | Val loss: 0.8418 | Val acc: 58.32% | LR: 0.000199
Epoch: 052 | MCC: 0.026400 | Train loss: 0.9658 | Train acc: 52.11% | Val loss: 0.8423 | Val acc: 58.37% | LR: 0.000197
Epoch: 053 | MCC: 0.061331 | Train loss: 0.9651 | Train acc: 52.11% | Val loss: 0.8437 | Val acc: 58.35% | LR: 0.000194
Epoch: 054 | MCC: 0.025550 | Train loss: 0.9646 | Train acc: 52.11% | Val loss: 0.8173 | Val acc: 59.70% | LR: 0.000191
Epoch: 055 | MCC: 0.036501 | Train loss: 0.9783 | Train acc: 52.16% | Val loss: 0.8149 | Val acc: 59.79% | LR: 0.000189
Epoch: 056 | MCC: 0.025915 | Train loss: 0.9677 | Train acc: 52.18% | Val loss: 0.8206 | Val acc: 59.29% | LR: 0.000186
Epoch: 057 | MCC: 0.030707 | Train loss: 0.9643 | Train acc: 52.09% | Val loss: 0.8099 | Val acc: 60.05% | LR: 0.000184
Epoch: 058 | MCC: 0.030452 | Train loss: 0.9649 | Train acc: 52.14% | Val loss: 0.8120 | Val acc: 59.97% | LR: 0.000181
Epoch: 059 | MCC: 0.052976 | Train loss: 0.9643 | Train acc: 52.05% | Val loss: 0.8101 | Val acc: 60.19% | LR: 0.000178
Epoch: 060 | MCC: 0.030008 | Train loss: 0.9685 | Train acc: 52.11% | Val loss: 0.8239 | Val acc: 59.34% | LR: 0.000176
Epoch: 061 | MCC: 0.028450 | Train loss: 0.9892 | Train acc: 52.15% | Val loss: 0.8129 | Val acc: 59.70% | LR: 0.000173
Epoch: 062 | MCC: 0.030857 | Train loss: 0.9641 | Train acc: 52.14% | Val loss: 0.8288 | Val acc: 59.07% | LR: 0.000170
Epoch: 063 | MCC: 0.025663 | Train loss: 0.9642 | Train acc: 52.07% | Val loss: 0.8094 | Val acc: 59.90% | LR: 0.000167
Epoch: 064 | MCC: 0.024767 | Train loss: 0.9599 | Train acc: 52.30% | Val loss: 0.8168 | Val acc: 59.65% | LR: 0.000165
Epoch: 065 | MCC: 0.021765 | Train loss: 0.9678 | Train acc: 52.02% | Val loss: 0.8149 | Val acc: 59.68% | LR: 0.000162
Epoch: 066 | MCC: 0.041167 | Train loss: 0.9705 | Train acc: 52.21% | Val loss: 0.8163 | Val acc: 59.61% | LR: 0.000159
Epoch: 067 | MCC: 0.016991 | Train loss: 0.9855 | Train acc: 52.10% | Val loss: 0.8336 | Val acc: 58.56% | LR: 0.000156
Epoch: 068 | MCC: 0.020803 | Train loss: 1.0678 | Train acc: 52.13% | Val loss: 0.8336 | Val acc: 58.70% | LR: 0.000153
Epoch: 069 | MCC: 0.021052 | Train loss: 0.9693 | Train acc: 52.23% | Val loss: 0.8295 | Val acc: 58.92% | LR: 0.000151
Epoch: 070 | MCC: 0.026257 | Train loss: 0.9821 | Train acc: 52.15% | Val loss: 0.8308 | Val acc: 58.85% | LR: 0.000148
Epoch: 071 | MCC: 0.032990 | Train loss: 0.9625 | Train acc: 52.14% | Val loss: 0.8263 | Val acc: 59.09% | LR: 0.000145
Epoch: 072 | MCC: 0.046436 | Train loss: 0.9597 | Train acc: 52.28% | Val loss: 0.8152 | Val acc: 59.58% | LR: 0.000142
Epoch: 073 | MCC: 0.025427 | Train loss: 0.9624 | Train acc: 52.14% | Val loss: 0.8433 | Val acc: 58.04% | LR: 0.000139
Epoch: 074 | MCC: 0.052319 | Train loss: 0.9607 | Train acc: 52.18% | Val loss: 0.8137 | Val acc: 59.68% | LR: 0.000136
Epoch: 075 | MCC: 0.028432 | Train loss: 0.9634 | Train acc: 52.04% | Val loss: 0.8167 | Val acc: 59.41% | LR: 0.000134
Epoch: 076 | MCC: 0.029768 | Train loss: 0.9615 | Train acc: 52.09% | Val loss: 0.8228 | Val acc: 59.31% | LR: 0.000131
Epoch: 077 | MCC: 0.028416 | Train loss: 0.9600 | Train acc: 52.22% | Val loss: 0.8202 | Val acc: 59.39% | LR: 0.000128
Epoch: 078 | MCC: 0.028803 | Train loss: 0.9591 | Train acc: 52.24% | Val loss: 0.8216 | Val acc: 59.31% | LR: 0.000125
Epoch: 079 | MCC: 0.025090 | Train loss: 0.9590 | Train acc: 52.26% | Val loss: 0.8186 | Val acc: 59.34% | LR: 0.000122
Epoch: 080 | MCC: 0.030200 | Train loss: 0.9621 | Train acc: 52.08% | Val loss: 0.8218 | Val acc: 59.31% | LR: 0.000119
Epoch: 081 | MCC: 0.031151 | Train loss: 0.9596 | Train acc: 52.34% | Val loss: 0.8207 | Val acc: 59.48% | LR: 0.000117
Epoch: 082 | MCC: 0.029277 | Train loss: 0.9612 | Train acc: 52.14% | Val loss: 0.8214 | Val acc: 59.34% | LR: 0.000114
Epoch: 083 | MCC: 0.027715 | Train loss: 0.9595 | Train acc: 52.23% | Val loss: 0.8223 | Val acc: 59.26% | LR: 0.000111
Epoch: 084 | MCC: 0.028559 | Train loss: 0.9756 | Train acc: 52.25% | Val loss: 0.8227 | Val acc: 59.31% | LR: 0.000108
Epoch: 085 | MCC: 0.020999 | Train loss: 0.9606 | Train acc: 52.17% | Val loss: 0.8166 | Val acc: 59.50% | LR: 0.000105
Epoch: 086 | MCC: 0.028637 | Train loss: 0.9602 | Train acc: 52.18% | Val loss: 0.8235 | Val acc: 59.19% | LR: 0.000103
Epoch: 087 | MCC: 0.027888 | Train loss: 0.9594 | Train acc: 52.27% | Val loss: 0.8195 | Val acc: 59.44% | LR: 0.000100
Epoch: 088 | MCC: 0.025755 | Train loss: 0.9597 | Train acc: 52.25% | Val loss: 0.8232 | Val acc: 59.22% | LR: 0.000097
Epoch: 089 | MCC: 0.027288 | Train loss: 0.9593 | Train acc: 52.25% | Val loss: 0.8228 | Val acc: 59.17% | LR: 0.000095
Epoch: 090 | MCC: 0.026401 | Train loss: 0.9584 | Train acc: 52.27% | Val loss: 0.8233 | Val acc: 59.12% | LR: 0.000092
Epoch: 091 | MCC: 0.059056 | Train loss: 0.9589 | Train acc: 52.27% | Val loss: 0.7992 | Val acc: 60.45% | LR: 0.000089
Epoch: 092 | MCC: 0.023464 | Train loss: 0.9599 | Train acc: 52.20% | Val loss: 0.8206 | Val acc: 59.22% | LR: 0.000087
Epoch: 093 | MCC: 0.030060 | Train loss: 0.9604 | Train acc: 52.19% | Val loss: 0.8248 | Val acc: 59.17% | LR: 0.000084
Epoch: 094 | MCC: 0.025024 | Train loss: 0.9596 | Train acc: 52.28% | Val loss: 0.8238 | Val acc: 59.14% | LR: 0.000081
Epoch: 095 | MCC: 0.030297 | Train loss: 0.9580 | Train acc: 52.28% | Val loss: 0.8234 | Val acc: 59.29% | LR: 0.000079
Epoch: 096 | MCC: 0.031295 | Train loss: 0.9600 | Train acc: 52.18% | Val loss: 0.8226 | Val acc: 59.34% | LR: 0.000076
Epoch: 097 | MCC: 0.025985 | Train loss: 0.9576 | Train acc: 52.30% | Val loss: 0.8221 | Val acc: 59.22% | LR: 0.000074
Epoch: 098 | MCC: 0.032198 | Train loss: 0.9574 | Train acc: 52.31% | Val loss: 0.8273 | Val acc: 59.08% | LR: 0.000071
Epoch: 099 | MCC: 0.030454 | Train loss: 0.9602 | Train acc: 52.15% | Val loss: 0.8227 | Val acc: 59.34% | LR: 0.000069
Epoch: 100 | MCC: 0.025664 | Train loss: 0.9605 | Train acc: 52.16% | Val loss: 0.8220 | Val acc: 59.24% | LR: 0.000066
Epoch: 101 | MCC: 0.027415 | Train loss: 0.9580 | Train acc: 52.27% | Val loss: 0.8202 | Val acc: 59.46% | LR: 0.000064
Epoch: 102 | MCC: 0.027741 | Train loss: 0.9597 | Train acc: 52.20% | Val loss: 0.8225 | Val acc: 59.31% | LR: 0.000061
Epoch: 103 | MCC: 0.030125 | Train loss: 0.9603 | Train acc: 52.14% | Val loss: 0.8215 | Val acc: 59.36% | LR: 0.000059
Epoch: 104 | MCC: 0.027347 | Train loss: 0.9607 | Train acc: 52.14% | Val loss: 0.8262 | Val acc: 59.07% | LR: 0.000057
Epoch: 105 | MCC: 0.024942 | Train loss: 0.9592 | Train acc: 52.20% | Val loss: 0.8213 | Val acc: 59.24% | LR: 0.000055
Epoch: 106 | MCC: 0.028806 | Train loss: 0.9546 | Train acc: 52.43% | Val loss: 0.8255 | Val acc: 59.19% | LR: 0.000052
Epoch: 107 | MCC: 0.028586 | Train loss: 0.9582 | Train acc: 52.24% | Val loss: 0.8220 | Val acc: 59.34% | LR: 0.000050
Epoch: 108 | MCC: 0.031125 | Train loss: 0.9591 | Train acc: 52.22% | Val loss: 0.8222 | Val acc: 59.36% | LR: 0.000048
Epoch: 109 | MCC: 0.029277 | Train loss: 0.9593 | Train acc: 52.15% | Val loss: 0.8211 | Val acc: 59.36% | LR: 0.000046
Epoch: 110 | MCC: 0.027466 | Train loss: 0.9585 | Train acc: 52.24% | Val loss: 0.8245 | Val acc: 59.19% | LR: 0.000044
Epoch: 111 | MCC: 0.031192 | Train loss: 0.9606 | Train acc: 52.10% | Val loss: 0.8221 | Val acc: 59.41% | LR: 0.000042
Epoch: 112 | MCC: 0.029741 | Train loss: 0.9584 | Train acc: 52.23% | Val loss: 0.8216 | Val acc: 59.36% | LR: 0.000040
Epoch: 113 | MCC: 0.030803 | Train loss: 0.9573 | Train acc: 52.29% | Val loss: 0.8216 | Val acc: 59.44% | LR: 0.000038
Epoch: 114 | MCC: 0.028811 | Train loss: 0.9567 | Train acc: 52.31% | Val loss: 0.8230 | Val acc: 59.26% | LR: 0.000036
Epoch: 115 | MCC: 0.030806 | Train loss: 0.9573 | Train acc: 52.30% | Val loss: 0.8220 | Val acc: 59.39% | LR: 0.000034
Epoch: 116 | MCC: 0.029511 | Train loss: 0.9584 | Train acc: 52.26% | Val loss: 0.8221 | Val acc: 59.36% | LR: 0.000032
Epoch: 117 | MCC: 0.028671 | Train loss: 0.9551 | Train acc: 52.41% | Val loss: 0.8243 | Val acc: 59.26% | LR: 0.000030
Epoch: 118 | MCC: 0.029429 | Train loss: 0.9583 | Train acc: 52.24% | Val loss: 0.8230 | Val acc: 59.29% | LR: 0.000029
Epoch: 119 | MCC: 0.028755 | Train loss: 0.9556 | Train acc: 52.41% | Val loss: 0.8239 | Val acc: 59.24% | LR: 0.000027
Epoch: 120 | MCC: 0.030118 | Train loss: 0.9579 | Train acc: 52.28% | Val loss: 0.8219 | Val acc: 59.39% | LR: 0.000025
Epoch: 121 | MCC: 0.027960 | Train loss: 0.9592 | Train acc: 52.17% | Val loss: 0.8229 | Val acc: 59.29% | LR: 0.000024
Epoch: 122 | MCC: 0.028244 | Train loss: 0.9571 | Train acc: 52.31% | Val loss: 0.8243 | Val acc: 59.22% | LR: 0.000022
Epoch: 123 | MCC: 0.028748 | Train loss: 0.9597 | Train acc: 52.18% | Val loss: 0.8235 | Val acc: 59.26% | LR: 0.000021
Epoch: 124 | MCC: 0.026286 | Train loss: 0.9589 | Train acc: 52.22% | Val loss: 0.8243 | Val acc: 59.17% | LR: 0.000019
Epoch: 125 | MCC: 0.028811 | Train loss: 0.9578 | Train acc: 52.27% | Val loss: 0.8229 | Val acc: 59.26% | LR: 0.000018
Epoch: 126 | MCC: 0.028959 | Train loss: 0.9582 | Train acc: 52.25% | Val loss: 0.8224 | Val acc: 59.31% | LR: 0.000016
Epoch: 127 | MCC: 0.028811 | Train loss: 0.9587 | Train acc: 52.25% | Val loss: 0.8229 | Val acc: 59.26% | LR: 0.000015
Epoch: 128 | MCC: 0.029959 | Train loss: 0.9562 | Train acc: 52.34% | Val loss: 0.8224 | Val acc: 59.36% | LR: 0.000014
Epoch: 129 | MCC: 0.028120 | Train loss: 0.9580 | Train acc: 52.27% | Val loss: 0.8230 | Val acc: 59.26% | LR: 0.000013
Epoch: 130 | MCC: 0.028959 | Train loss: 0.9572 | Train acc: 52.32% | Val loss: 0.8224 | Val acc: 59.31% | LR: 0.000012
Epoch: 131 | MCC: 0.028959 | Train loss: 0.9576 | Train acc: 52.28% | Val loss: 0.8226 | Val acc: 59.31% | LR: 0.000011
Epoch: 132 | MCC: 0.027281 | Train loss: 0.9598 | Train acc: 52.18% | Val loss: 0.8235 | Val acc: 59.22% | LR: 0.000009
Epoch: 133 | MCC: 0.027513 | Train loss: 0.9559 | Train acc: 52.41% | Val loss: 0.8232 | Val acc: 59.24% | LR: 0.000009
Epoch: 134 | MCC: 0.028959 | Train loss: 0.9570 | Train acc: 52.32% | Val loss: 0.8225 | Val acc: 59.31% | LR: 0.000008
Epoch: 135 | MCC: 0.028274 | Train loss: 0.9552 | Train acc: 52.43% | Val loss: 0.8226 | Val acc: 59.29% | LR: 0.000007
Epoch: 136 | MCC: 0.028120 | Train loss: 0.9555 | Train acc: 52.42% | Val loss: 0.8229 | Val acc: 59.26% | LR: 0.000006
Epoch: 137 | MCC: 0.028959 | Train loss: 0.9552 | Train acc: 52.41% | Val loss: 0.8225 | Val acc: 59.31% | LR: 0.000005
Epoch: 138 | MCC: 0.028959 | Train loss: 0.9565 | Train acc: 52.38% | Val loss: 0.8226 | Val acc: 59.31% | LR: 0.000005
Epoch: 139 | MCC: 0.028120 | Train loss: 0.9563 | Train acc: 52.37% | Val loss: 0.8229 | Val acc: 59.26% | LR: 0.000004
Epoch: 140 | MCC: 0.028120 | Train loss: 0.9558 | Train acc: 52.41% | Val loss: 0.8230 | Val acc: 59.26% | LR: 0.000003
Epoch: 141 | MCC: 0.028120 | Train loss: 0.9570 | Train acc: 52.36% | Val loss: 0.8229 | Val acc: 59.26% | LR: 0.000003
Epoch: 142 | MCC: 0.028959 | Train loss: 0.9552 | Train acc: 52.41% | Val loss: 0.8226 | Val acc: 59.31% | LR: 0.000002
Epoch: 143 | MCC: 0.028120 | Train loss: 0.9572 | Train acc: 52.32% | Val loss: 0.8229 | Val acc: 59.26% | LR: 0.000002
Epoch: 144 | MCC: 0.028120 | Train loss: 0.9556 | Train acc: 52.41% | Val loss: 0.8228 | Val acc: 59.26% | LR: 0.000002
Epoch: 145 | MCC: 0.028959 | Train loss: 0.9578 | Train acc: 52.30% | Val loss: 0.8228 | Val acc: 59.31% | LR: 0.000001
Epoch: 146 | MCC: 0.028959 | Train loss: 0.9587 | Train acc: 52.26% | Val loss: 0.8228 | Val acc: 59.31% | LR: 0.000001
Epoch: 147 | MCC: 0.028959 | Train loss: 0.9544 | Train acc: 52.46% | Val loss: 0.8227 | Val acc: 59.31% | LR: 0.000001
Epoch: 148 | MCC: 0.028959 | Train loss: 0.9590 | Train acc: 52.24% | Val loss: 0.8228 | Val acc: 59.31% | LR: 0.000001
Epoch: 149 | MCC: 0.028959 | Train loss: 0.9568 | Train acc: 52.35% | Val loss: 0.8228 | Val acc: 59.31% | LR: 0.000001

[I 2025-10-05 10:52:38,675] Trial 66 finished with value: 0.028958906419575214 and parameters: {'lr': 0.00027180556711734974, 'hidden_size': 64, 'dropout': 0.30674181099730796, 'weight_decay': 0.014889214728223897}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.000000 | Train loss: 1.0214 | Train acc: 50.62% | Val loss: 1.0500 | Val acc: 45.27% | LR: 0.009293
Epoch: 001 | MCC: 0.053661 | Train loss: 1.0036 | Train acc: 50.36% | Val loss: 0.9926 | Val acc: 51.12% | LR: 0.009289
Epoch: 002 | MCC: 0.009322 | Train loss: 0.9931 | Train acc: 50.51% | Val loss: 0.9532 | Val acc: 54.95% | LR: 0.009284
Epoch: 003 | MCC: 0.040153 | Train loss: 0.9993 | Train acc: 50.58% | Val loss: 0.9973 | Val acc: 48.74% | LR: 0.009277
Epoch: 004 | MCC: 0.031498 | Train loss: 0.9926 | Train acc: 50.12% | Val loss: 0.9538 | Val acc: 56.11% | LR: 0.009268
Epoch: 005 | MCC: 0.010871 | Train loss: 0.9870 | Train acc: 51.16% | Val loss: 0.9486 | Val acc: 56.26% | LR: 0.009257
Epoch: 006 | MCC: -0.001534 | Train loss: 0.9886 | Train acc: 50.83% | Val loss: 0.9379 | Val acc: 54.83% | LR: 0.009244
Epoch: 007 | MCC: 0.020593 | Train loss: 1.0513 | Train acc: 49.86% | Val loss: 1.0060 | Val acc: 47.02% | LR: 0.009229
Epoch: 008 | MCC: 0.019692 | Train loss: 0.9971 | Train acc: 50.76% | Val loss: 0.9226 | Val acc: 54.54% | LR: 0.009211
Epoch: 009 | MCC: 0.027812 | Train loss: 0.9828 | Train acc: 51.47% | Val loss: 1.0082 | Val acc: 54.65% | LR: 0.009192
Epoch: 010 | MCC: 0.024708 | Train loss: 0.9922 | Train acc: 50.93% | Val loss: 1.0035 | Val acc: 53.63% | LR: 0.009171
Epoch: 011 | MCC: 0.034010 | Train loss: 0.9856 | Train acc: 50.91% | Val loss: 0.9643 | Val acc: 54.71% | LR: 0.009148
Epoch: 012 | MCC: 0.029359 | Train loss: 0.9845 | Train acc: 51.42% | Val loss: 0.9692 | Val acc: 54.37% | LR: 0.009122
Epoch: 013 | MCC: 0.024917 | Train loss: 0.9822 | Train acc: 51.63% | Val loss: 0.9169 | Val acc: 54.51% | LR: 0.009095
Epoch: 014 | MCC: 0.023911 | Train loss: 0.9803 | Train acc: 51.71% | Val loss: 0.9757 | Val acc: 52.63% | LR: 0.009066
Epoch: 015 | MCC: 0.039681 | Train loss: 0.9777 | Train acc: 51.66% | Val loss: 0.9286 | Val acc: 55.79% | LR: 0.009035
Epoch: 016 | MCC: 0.020063 | Train loss: 0.9802 | Train acc: 51.64% | Val loss: 0.9068 | Val acc: 55.51% | LR: 0.009002
Epoch: 017 | MCC: 0.021018 | Train loss: 0.9891 | Train acc: 50.86% | Val loss: 0.9126 | Val acc: 54.87% | LR: 0.008967
Epoch: 018 | MCC: 0.018376 | Train loss: 0.9842 | Train acc: 50.93% | Val loss: 0.9271 | Val acc: 55.34% | LR: 0.008931
Epoch: 019 | MCC: 0.039741 | Train loss: 0.9831 | Train acc: 51.46% | Val loss: 0.9290 | Val acc: 56.00% | LR: 0.008892
Epoch: 020 | MCC: 0.056798 | Train loss: 1.0020 | Train acc: 50.26% | Val loss: 0.9597 | Val acc: 55.56% | LR: 0.008851
Epoch: 021 | MCC: 0.035638 | Train loss: 1.0164 | Train acc: 50.18% | Val loss: 2.3666 | Val acc: 53.21% | LR: 0.008809
Epoch: 022 | MCC: 0.032021 | Train loss: 1.0172 | Train acc: 50.77% | Val loss: 0.9857 | Val acc: 53.62% | LR: 0.008765
Epoch: 023 | MCC: 0.029986 | Train loss: 1.0071 | Train acc: 50.64% | Val loss: 0.9534 | Val acc: 53.60% | LR: 0.008719
Epoch: 024 | MCC: 0.023113 | Train loss: 1.0068 | Train acc: 50.60% | Val loss: 0.9848 | Val acc: 55.05% | LR: 0.008671
Epoch: 025 | MCC: -0.026072 | Train loss: 1.0086 | Train acc: 50.16% | Val loss: 1.0353 | Val acc: 45.88% | LR: 0.008622
Epoch: 026 | MCC: 0.018213 | Train loss: 0.9998 | Train acc: 50.13% | Val loss: 0.9379 | Val acc: 55.82% | LR: 0.008570
Epoch: 027 | MCC: 0.036188 | Train loss: 0.9971 | Train acc: 50.70% | Val loss: 0.9277 | Val acc: 56.93% | LR: 0.008517
Epoch: 028 | MCC: 0.038080 | Train loss: 0.9923 | Train acc: 50.65% | Val loss: 0.9681 | Val acc: 53.47% | LR: 0.008463
Epoch: 029 | MCC: 0.023948 | Train loss: 1.0048 | Train acc: 50.15% | Val loss: 1.0278 | Val acc: 48.45% | LR: 0.008406
Epoch: 030 | MCC: 0.021310 | Train loss: 1.0936 | Train acc: 50.00% | Val loss: 1.1224 | Val acc: 45.77% | LR: 0.008348
Epoch: 031 | MCC: 0.000000 | Train loss: 1.0241 | Train acc: 50.31% | Val loss: 1.0466 | Val acc: 45.27% | LR: 0.008289
Epoch: 032 | MCC: 0.002734 | Train loss: 0.9991 | Train acc: 49.79% | Val loss: 1.0062 | Val acc: 46.59% | LR: 0.008227
Epoch: 033 | MCC: 0.024525 | Train loss: 0.9905 | Train acc: 50.76% | Val loss: 0.9969 | Val acc: 51.33% | LR: 0.008165
Epoch: 034 | MCC: 0.031910 | Train loss: 0.9934 | Train acc: 50.76% | Val loss: 0.9149 | Val acc: 54.76% | LR: 0.008100
Epoch: 035 | MCC: -0.005287 | Train loss: 0.9912 | Train acc: 50.69% | Val loss: 1.0231 | Val acc: 45.22% | LR: 0.008034
Epoch: 036 | MCC: 0.039509 | Train loss: 0.9894 | Train acc: 50.87% | Val loss: 0.9713 | Val acc: 55.01% | LR: 0.007967
Epoch: 037 | MCC: 0.045733 | Train loss: 0.9958 | Train acc: 50.39% | Val loss: 0.9816 | Val acc: 55.20% | LR: 0.007898
Epoch: 038 | MCC: -0.056927 | Train loss: 0.9928 | Train acc: 50.70% | Val loss: 1.0136 | Val acc: 45.73% | LR: 0.007828
Epoch: 039 | MCC: 0.020074 | Train loss: 0.9962 | Train acc: 50.37% | Val loss: 0.9935 | Val acc: 52.72% | LR: 0.007756
Epoch: 040 | MCC: -0.050155 | Train loss: 0.9909 | Train acc: 50.84% | Val loss: 1.0012 | Val acc: 47.09% | LR: 0.007683
Epoch: 041 | MCC: 0.036735 | Train loss: 0.9883 | Train acc: 51.09% | Val loss: 0.9198 | Val acc: 54.49% | LR: 0.007609
Epoch: 042 | MCC: 0.053375 | Train loss: 0.9912 | Train acc: 50.80% | Val loss: 0.9657 | Val acc: 55.53% | LR: 0.007533
Epoch: 043 | MCC: 0.005211 | Train loss: 0.9887 | Train acc: 51.14% | Val loss: 0.9839 | Val acc: 53.21% | LR: 0.007456
Epoch: 044 | MCC: 0.036185 | Train loss: 0.9931 | Train acc: 50.74% | Val loss: 0.9279 | Val acc: 55.05% | LR: 0.007378
Epoch: 045 | MCC: 0.027094 | Train loss: 0.9887 | Train acc: 51.20% | Val loss: 0.9355 | Val acc: 54.61% | LR: 0.007299
Epoch: 046 | MCC: 0.034213 | Train loss: 0.9963 | Train acc: 51.20% | Val loss: 0.9554 | Val acc: 54.96% | LR: 0.007219
Epoch: 047 | MCC: -0.002491 | Train loss: 0.9850 | Train acc: 51.35% | Val loss: 0.9821 | Val acc: 52.67% | LR: 0.007137
Epoch: 048 | MCC: 0.002753 | Train loss: 0.9850 | Train acc: 51.30% | Val loss: 0.9836 | Val acc: 53.65% | LR: 0.007054
Epoch: 049 | MCC: 0.011452 | Train loss: 0.9815 | Train acc: 51.40% | Val loss: 0.9928 | Val acc: 52.40% | LR: 0.006970
Epoch: 050 | MCC: 0.043488 | Train loss: 0.9882 | Train acc: 50.82% | Val loss: 0.9239 | Val acc: 55.48% | LR: 0.006886
Epoch: 051 | MCC: 0.046520 | Train loss: 0.9860 | Train acc: 51.18% | Val loss: 0.9509 | Val acc: 55.27% | LR: 0.006800
Epoch: 052 | MCC: 0.027309 | Train loss: 0.9817 | Train acc: 51.42% | Val loss: 0.9678 | Val acc: 54.44% | LR: 0.006713
Epoch: 053 | MCC: 0.044757 | Train loss: 0.9844 | Train acc: 51.57% | Val loss: 0.9141 | Val acc: 56.51% | LR: 0.006626
Epoch: 054 | MCC: 0.020339 | Train loss: 0.9813 | Train acc: 51.52% | Val loss: 0.9283 | Val acc: 56.34% | LR: 0.006537
Epoch: 055 | MCC: 0.035566 | Train loss: 0.9790 | Train acc: 51.60% | Val loss: 0.9156 | Val acc: 56.83% | LR: 0.006448
Epoch: 056 | MCC: 0.030046 | Train loss: 0.9758 | Train acc: 51.70% | Val loss: 0.9408 | Val acc: 55.68% | LR: 0.006358
Epoch: 057 | MCC: 0.011763 | Train loss: 0.9796 | Train acc: 51.29% | Val loss: 0.9449 | Val acc: 54.59% | LR: 0.006267
Epoch: 058 | MCC: 0.033823 | Train loss: 0.9759 | Train acc: 51.63% | Val loss: 0.9366 | Val acc: 56.04% | LR: 0.006175
Epoch: 059 | MCC: 0.002271 | Train loss: 0.9724 | Train acc: 51.84% | Val loss: 0.9338 | Val acc: 55.37% | LR: 0.006083
Epoch: 060 | MCC: -0.003515 | Train loss: 0.9699 | Train acc: 52.10% | Val loss: 0.9302 | Val acc: 55.15% | LR: 0.005990
Epoch: 061 | MCC: -0.022431 | Train loss: 0.9757 | Train acc: 52.11% | Val loss: 0.9501 | Val acc: 54.93% | LR: 0.005897
Epoch: 062 | MCC: -0.007312 | Train loss: 0.9691 | Train acc: 51.97% | Val loss: 0.9572 | Val acc: 54.51% | LR: 0.005803
Epoch: 063 | MCC: -0.010723 | Train loss: 0.9695 | Train acc: 52.13% | Val loss: 0.9545 | Val acc: 53.95% | LR: 0.005708
Epoch: 064 | MCC: -0.002139 | Train loss: 0.9646 | Train acc: 52.33% | Val loss: 0.9200 | Val acc: 55.24% | LR: 0.005613
Epoch: 065 | MCC: 0.018071 | Train loss: 0.9718 | Train acc: 51.99% | Val loss: 0.9473 | Val acc: 55.84% | LR: 0.005518
Epoch: 066 | MCC: -0.018898 | Train loss: 0.9658 | Train acc: 52.22% | Val loss: 0.9562 | Val acc: 53.22% | LR: 0.005422
Epoch: 067 | MCC: 0.000574 | Train loss: 0.9682 | Train acc: 52.26% | Val loss: 0.9259 | Val acc: 55.67% | LR: 0.005326
Epoch: 068 | MCC: -0.009898 | Train loss: 0.9614 | Train acc: 52.52% | Val loss: 0.9250 | Val acc: 54.82% | LR: 0.005230
Epoch: 069 | MCC: -0.019010 | Train loss: 0.9569 | Train acc: 52.68% | Val loss: 0.9512 | Val acc: 53.80% | LR: 0.005133
Epoch: 070 | MCC: -0.007064 | Train loss: 0.9583 | Train acc: 52.68% | Val loss: 0.9331 | Val acc: 55.10% | LR: 0.005036
Epoch: 071 | MCC: -0.022280 | Train loss: 0.9548 | Train acc: 52.87% | Val loss: 0.9938 | Val acc: 51.28% | LR: 0.004939
Epoch: 072 | MCC: -0.018254 | Train loss: 0.9547 | Train acc: 52.71% | Val loss: 0.9448 | Val acc: 54.12% | LR: 0.004842
Epoch: 073 | MCC: -0.013462 | Train loss: 0.9484 | Train acc: 53.26% | Val loss: 0.9512 | Val acc: 53.56% | LR: 0.004745
Epoch: 074 | MCC: -0.021039 | Train loss: 0.9457 | Train acc: 53.21% | Val loss: 0.9903 | Val acc: 51.27% | LR: 0.004647
Epoch: 075 | MCC: -0.014676 | Train loss: 0.9745 | Train acc: 51.68% | Val loss: 1.0138 | Val acc: 48.56% | LR: 0.004550
Epoch: 076 | MCC: 0.012989 | Train loss: 1.0304 | Train acc: 50.69% | Val loss: 0.9938 | Val acc: 51.63% | LR: 0.004453
Epoch: 077 | MCC: 0.006768 | Train loss: 1.0205 | Train acc: 50.42% | Val loss: 1.0295 | Val acc: 46.22% | LR: 0.004356
Epoch: 078 | MCC: -0.006426 | Train loss: 0.9900 | Train acc: 50.65% | Val loss: 0.9230 | Val acc: 54.61% | LR: 0.004258
Epoch: 079 | MCC: 0.024723 | Train loss: 0.9925 | Train acc: 50.79% | Val loss: 0.9473 | Val acc: 56.62% | LR: 0.004162
Epoch: 080 | MCC: 0.019714 | Train loss: 0.9837 | Train acc: 51.09% | Val loss: 0.9010 | Val acc: 57.72% | LR: 0.004065
Epoch: 081 | MCC: 0.018185 | Train loss: 0.9813 | Train acc: 51.12% | Val loss: 0.8940 | Val acc: 57.38% | LR: 0.003969
Epoch: 082 | MCC: 0.030709 | Train loss: 0.9804 | Train acc: 51.29% | Val loss: 0.8953 | Val acc: 58.66% | LR: 0.003872
Epoch: 083 | MCC: 0.020805 | Train loss: 0.9788 | Train acc: 51.27% | Val loss: 0.9304 | Val acc: 56.61% | LR: 0.003777
Epoch: 084 | MCC: 0.048676 | Train loss: 0.9773 | Train acc: 51.33% | Val loss: 0.8665 | Val acc: 59.42% | LR: 0.003681
Epoch: 085 | MCC: 0.039319 | Train loss: 0.9888 | Train acc: 50.92% | Val loss: 0.8830 | Val acc: 59.98% | LR: 0.003586
Epoch: 086 | MCC: 0.027512 | Train loss: 0.9806 | Train acc: 51.45% | Val loss: 0.8738 | Val acc: 58.66% | LR: 0.003492
Epoch: 087 | MCC: 0.031826 | Train loss: 0.9780 | Train acc: 51.46% | Val loss: 0.8884 | Val acc: 58.39% | LR: 0.003398
Epoch: 088 | MCC: 0.059891 | Train loss: 0.9730 | Train acc: 51.68% | Val loss: 0.8692 | Val acc: 59.76% | LR: 0.003304
Epoch: 089 | MCC: 0.064558 | Train loss: 0.9759 | Train acc: 51.62% | Val loss: 0.8906 | Val acc: 58.47% | LR: 0.003212
Epoch: 090 | MCC: 0.064545 | Train loss: 0.9769 | Train acc: 51.66% | Val loss: 0.8626 | Val acc: 59.52% | LR: 0.003119
Epoch: 091 | MCC: 0.056942 | Train loss: 0.9735 | Train acc: 51.60% | Val loss: 0.8764 | Val acc: 59.09% | LR: 0.003028
Epoch: 092 | MCC: 0.051952 | Train loss: 0.9724 | Train acc: 51.73% | Val loss: 0.8796 | Val acc: 58.41% | LR: 0.002937
Epoch: 093 | MCC: 0.064317 | Train loss: 0.9703 | Train acc: 51.86% | Val loss: 0.8715 | Val acc: 58.65% | LR: 0.002847
Epoch: 094 | MCC: 0.000633 | Train loss: 0.9713 | Train acc: 51.74% | Val loss: 0.9153 | Val acc: 56.58% | LR: 0.002757
Epoch: 095 | MCC: 0.074010 | Train loss: 0.9698 | Train acc: 51.81% | Val loss: 0.8603 | Val acc: 60.16% | LR: 0.002669
Epoch: 096 | MCC: 0.047473 | Train loss: 0.9706 | Train acc: 51.65% | Val loss: 0.8988 | Val acc: 57.32% | LR: 0.002581
Epoch: 097 | MCC: 0.045961 | Train loss: 0.9661 | Train acc: 51.93% | Val loss: 0.9029 | Val acc: 57.35% | LR: 0.002495
Epoch: 098 | MCC: 0.039813 | Train loss: 0.9667 | Train acc: 51.85% | Val loss: 0.8819 | Val acc: 57.98% | LR: 0.002409
Epoch: 099 | MCC: 0.038331 | Train loss: 0.9661 | Train acc: 52.13% | Val loss: 0.8887 | Val acc: 57.50% | LR: 0.002324
Epoch: 100 | MCC: 0.044178 | Train loss: 0.9647 | Train acc: 52.03% | Val loss: 0.9114 | Val acc: 57.24% | LR: 0.002240
Epoch: 101 | MCC: 0.014167 | Train loss: 0.9661 | Train acc: 51.96% | Val loss: 0.9099 | Val acc: 55.95% | LR: 0.002158
Epoch: 102 | MCC: 0.011297 | Train loss: 0.9665 | Train acc: 52.03% | Val loss: 0.9023 | Val acc: 56.20% | LR: 0.002076
Epoch: 103 | MCC: 0.039716 | Train loss: 0.9615 | Train acc: 52.16% | Val loss: 0.8970 | Val acc: 57.24% | LR: 0.001996
Epoch: 104 | MCC: 0.021159 | Train loss: 0.9621 | Train acc: 52.10% | Val loss: 0.8972 | Val acc: 56.35% | LR: 0.001916
Epoch: 105 | MCC: -0.002650 | Train loss: 0.9617 | Train acc: 52.17% | Val loss: 0.9026 | Val acc: 56.32% | LR: 0.001838
Epoch: 106 | MCC: 0.007494 | Train loss: 0.9614 | Train acc: 52.15% | Val loss: 0.8987 | Val acc: 56.68% | LR: 0.001761
Epoch: 107 | MCC: 0.010689 | Train loss: 0.9599 | Train acc: 52.26% | Val loss: 0.9092 | Val acc: 56.18% | LR: 0.001686
Epoch: 108 | MCC: 0.005251 | Train loss: 0.9591 | Train acc: 52.32% | Val loss: 0.9196 | Val acc: 55.94% | LR: 0.001611
Epoch: 109 | MCC: 0.007120 | Train loss: 0.9572 | Train acc: 52.42% | Val loss: 0.9124 | Val acc: 56.35% | LR: 0.001538
Epoch: 110 | MCC: -0.010124 | Train loss: 0.9551 | Train acc: 52.51% | Val loss: 0.9270 | Val acc: 54.86% | LR: 0.001467
Epoch: 111 | MCC: -0.005989 | Train loss: 0.9538 | Train acc: 52.62% | Val loss: 0.9139 | Val acc: 56.07% | LR: 0.001396
Epoch: 112 | MCC: -0.013069 | Train loss: 0.9547 | Train acc: 52.35% | Val loss: 0.9249 | Val acc: 54.63% | LR: 0.001328
Epoch: 113 | MCC: -0.023413 | Train loss: 0.9549 | Train acc: 52.25% | Val loss: 0.9582 | Val acc: 52.79% | LR: 0.001260
Epoch: 114 | MCC: -0.010599 | Train loss: 0.9538 | Train acc: 52.62% | Val loss: 0.9396 | Val acc: 54.20% | LR: 0.001194
Epoch: 115 | MCC: -0.009294 | Train loss: 0.9545 | Train acc: 52.48% | Val loss: 0.9323 | Val acc: 54.69% | LR: 0.001130
Epoch: 116 | MCC: -0.007800 | Train loss: 0.9497 | Train acc: 52.72% | Val loss: 0.9421 | Val acc: 54.44% | LR: 0.001067
Epoch: 117 | MCC: -0.007811 | Train loss: 0.9470 | Train acc: 52.84% | Val loss: 0.9397 | Val acc: 54.49% | LR: 0.001006
Epoch: 118 | MCC: -0.016827 | Train loss: 0.9453 | Train acc: 52.91% | Val loss: 0.9322 | Val acc: 54.16% | LR: 0.000946
Epoch: 119 | MCC: -0.013070 | Train loss: 0.9473 | Train acc: 52.79% | Val loss: 0.9424 | Val acc: 53.99% | LR: 0.000888
Epoch: 120 | MCC: -0.015712 | Train loss: 0.9449 | Train acc: 53.05% | Val loss: 0.9455 | Val acc: 53.68% | LR: 0.000832
Epoch: 121 | MCC: -0.007421 | Train loss: 0.9441 | Train acc: 53.00% | Val loss: 0.9461 | Val acc: 53.83% | LR: 0.000777
Epoch: 122 | MCC: -0.023713 | Train loss: 0.9428 | Train acc: 53.09% | Val loss: 0.9530 | Val acc: 53.06% | LR: 0.000724
Epoch: 123 | MCC: -0.009442 | Train loss: 0.9424 | Train acc: 53.24% | Val loss: 0.9585 | Val acc: 53.50% | LR: 0.000673
Epoch: 124 | MCC: 0.003269 | Train loss: 0.9427 | Train acc: 53.10% | Val loss: 0.9502 | Val acc: 53.91% | LR: 0.000623
Epoch: 125 | MCC: -0.006904 | Train loss: 0.9434 | Train acc: 53.09% | Val loss: 0.9466 | Val acc: 53.74% | LR: 0.000576
Epoch: 126 | MCC: -0.007479 | Train loss: 0.9413 | Train acc: 53.22% | Val loss: 0.9655 | Val acc: 53.38% | LR: 0.000530
Epoch: 127 | MCC: -0.012830 | Train loss: 0.9389 | Train acc: 53.40% | Val loss: 0.9587 | Val acc: 53.26% | LR: 0.000486
Epoch: 128 | MCC: -0.014828 | Train loss: 0.9389 | Train acc: 53.25% | Val loss: 0.9652 | Val acc: 52.84% | LR: 0.000443
Epoch: 129 | MCC: -0.005271 | Train loss: 0.9381 | Train acc: 53.38% | Val loss: 0.9551 | Val acc: 53.58% | LR: 0.000403
Epoch: 130 | MCC: -0.024335 | Train loss: 0.9377 | Train acc: 53.42% | Val loss: 0.9727 | Val acc: 52.34% | LR: 0.000364
Epoch: 131 | MCC: -0.009254 | Train loss: 0.9356 | Train acc: 53.47% | Val loss: 0.9599 | Val acc: 53.18% | LR: 0.000327
Epoch: 132 | MCC: -0.021493 | Train loss: 0.9362 | Train acc: 53.49% | Val loss: 0.9639 | Val acc: 52.91% | LR: 0.000292
Epoch: 133 | MCC: -0.026162 | Train loss: 0.9353 | Train acc: 53.50% | Val loss: 0.9660 | Val acc: 52.71% | LR: 0.000259
Epoch: 134 | MCC: -0.019586 | Train loss: 0.9356 | Train acc: 53.47% | Val loss: 0.9667 | Val acc: 52.67% | LR: 0.000228
Epoch: 135 | MCC: -0.014278 | Train loss: 0.9345 | Train acc: 53.62% | Val loss: 0.9656 | Val acc: 52.73% | LR: 0.000199
Epoch: 136 | MCC: -0.020239 | Train loss: 0.9350 | Train acc: 53.61% | Val loss: 0.9659 | Val acc: 52.50% | LR: 0.000172
Epoch: 137 | MCC: -0.019747 | Train loss: 0.9353 | Train acc: 53.54% | Val loss: 0.9697 | Val acc: 52.55% | LR: 0.000147
Epoch: 138 | MCC: -0.020142 | Train loss: 0.9333 | Train acc: 53.60% | Val loss: 0.9698 | Val acc: 52.44% | LR: 0.000124
Epoch: 139 | MCC: -0.027795 | Train loss: 0.9338 | Train acc: 53.61% | Val loss: 0.9680 | Val acc: 52.11% | LR: 0.000103
Epoch: 140 | MCC: -0.024190 | Train loss: 0.9314 | Train acc: 53.75% | Val loss: 0.9701 | Val acc: 52.24% | LR: 0.000083
Epoch: 141 | MCC: -0.024326 | Train loss: 0.9340 | Train acc: 53.51% | Val loss: 0.9710 | Val acc: 52.27% | LR: 0.000066
Epoch: 142 | MCC: -0.027098 | Train loss: 0.9328 | Train acc: 53.60% | Val loss: 0.9693 | Val acc: 52.16% | LR: 0.000051
Epoch: 143 | MCC: -0.025719 | Train loss: 0.9320 | Train acc: 53.76% | Val loss: 0.9703 | Val acc: 52.23% | LR: 0.000038
Epoch: 144 | MCC: -0.021084 | Train loss: 0.9315 | Train acc: 53.71% | Val loss: 0.9712 | Val acc: 52.31% | LR: 0.000026
Epoch: 145 | MCC: -0.024377 | Train loss: 0.9307 | Train acc: 53.78% | Val loss: 0.9710 | Val acc: 52.33% | LR: 0.000017
Epoch: 146 | MCC: -0.023534 | Train loss: 0.9323 | Train acc: 53.68% | Val loss: 0.9709 | Val acc: 52.36% | LR: 0.000010
Epoch: 147 | MCC: -0.024537 | Train loss: 0.9317 | Train acc: 53.70% | Val loss: 0.9710 | Val acc: 52.31% | LR: 0.000005
Epoch: 148 | MCC: -0.023695 | Train loss: 0.9325 | Train acc: 53.62% | Val loss: 0.9709 | Val acc: 52.33% | LR: 0.000002
Epoch: 149 | MCC: -0.023695 | Train loss: 0.9309 | Train acc: 53.67% | Val loss: 0.9709 | Val acc: 52.33% | LR: 0.000001

[I 2025-10-05 10:55:04,190] Trial 67 finished with value: -0.023694655275903642 and parameters: {'lr': 0.009293575553163513, 'hidden_size': 95, 'dropout': 0.22809570460939338, 'weight_decay': 0.00892618338855919}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.000000 | Train loss: 0.9982 | Train acc: 50.26% | Val loss: 1.0462 | Val acc: 45.27% | LR: 0.005597
Epoch: 001 | MCC: 0.051381 | Train loss: 0.9917 | Train acc: 50.65% | Val loss: 0.9863 | Val acc: 53.25% | LR: 0.005595
Epoch: 002 | MCC: 0.059090 | Train loss: 0.9890 | Train acc: 50.66% | Val loss: 0.9620 | Val acc: 55.53% | LR: 0.005592
Epoch: 003 | MCC: 0.062544 | Train loss: 0.9839 | Train acc: 51.65% | Val loss: 0.9744 | Val acc: 52.96% | LR: 0.005587
Epoch: 004 | MCC: 0.066327 | Train loss: 0.9849 | Train acc: 51.05% | Val loss: 0.9445 | Val acc: 56.29% | LR: 0.005582
Epoch: 005 | MCC: 0.041378 | Train loss: 0.9822 | Train acc: 51.06% | Val loss: 0.9702 | Val acc: 52.71% | LR: 0.005575
Epoch: 006 | MCC: 0.062778 | Train loss: 0.9815 | Train acc: 51.29% | Val loss: 0.8971 | Val acc: 59.10% | LR: 0.005567
Epoch: 007 | MCC: 0.027837 | Train loss: 0.9793 | Train acc: 51.67% | Val loss: 0.9699 | Val acc: 51.44% | LR: 0.005558
Epoch: 008 | MCC: 0.041303 | Train loss: 0.9823 | Train acc: 51.15% | Val loss: 0.8804 | Val acc: 58.78% | LR: 0.005548
Epoch: 009 | MCC: 0.034428 | Train loss: 0.9862 | Train acc: 51.14% | Val loss: 0.9060 | Val acc: 60.54% | LR: 0.005536
Epoch: 010 | MCC: 0.061505 | Train loss: 0.9852 | Train acc: 50.73% | Val loss: 0.9365 | Val acc: 60.29% | LR: 0.005523
Epoch: 011 | MCC: 0.039017 | Train loss: 0.9761 | Train acc: 51.81% | Val loss: 0.8749 | Val acc: 58.21% | LR: 0.005509
Epoch: 012 | MCC: 0.044625 | Train loss: 0.9770 | Train acc: 51.85% | Val loss: 0.8770 | Val acc: 58.75% | LR: 0.005494
Epoch: 013 | MCC: 0.018285 | Train loss: 0.9762 | Train acc: 51.61% | Val loss: 0.8859 | Val acc: 58.25% | LR: 0.005478
Epoch: 014 | MCC: 0.028576 | Train loss: 0.9723 | Train acc: 51.77% | Val loss: 0.8682 | Val acc: 58.80% | LR: 0.005460
Epoch: 015 | MCC: -0.013363 | Train loss: 0.9780 | Train acc: 51.48% | Val loss: 0.9350 | Val acc: 55.27% | LR: 0.005442
Epoch: 016 | MCC: 0.022707 | Train loss: 0.9869 | Train acc: 51.11% | Val loss: 0.9439 | Val acc: 54.36% | LR: 0.005422
Epoch: 017 | MCC: 0.017695 | Train loss: 0.9749 | Train acc: 51.99% | Val loss: 0.9345 | Val acc: 54.96% | LR: 0.005401
Epoch: 018 | MCC: 0.005128 | Train loss: 0.9883 | Train acc: 51.07% | Val loss: 0.9340 | Val acc: 55.83% | LR: 0.005379
Epoch: 019 | MCC: -0.026039 | Train loss: 0.9801 | Train acc: 51.47% | Val loss: 1.1888 | Val acc: 53.83% | LR: 0.005355
Epoch: 020 | MCC: -0.017986 | Train loss: 0.9800 | Train acc: 51.46% | Val loss: 0.9041 | Val acc: 55.36% | LR: 0.005331
Epoch: 021 | MCC: 0.004400 | Train loss: 0.9728 | Train acc: 52.08% | Val loss: 0.9527 | Val acc: 52.11% | LR: 0.005305
Epoch: 022 | MCC: -0.013971 | Train loss: 0.9738 | Train acc: 52.15% | Val loss: 0.9073 | Val acc: 55.54% | LR: 0.005279
Epoch: 023 | MCC: -0.000109 | Train loss: 1.0006 | Train acc: 50.40% | Val loss: 0.8981 | Val acc: 56.40% | LR: 0.005251
Epoch: 024 | MCC: 0.007323 | Train loss: 0.9896 | Train acc: 50.65% | Val loss: 1.0661 | Val acc: 45.49% | LR: 0.005222
Epoch: 025 | MCC: 0.032669 | Train loss: 0.9841 | Train acc: 50.75% | Val loss: 1.0190 | Val acc: 46.62% | LR: 0.005192
Epoch: 026 | MCC: 0.017164 | Train loss: 0.9895 | Train acc: 50.86% | Val loss: 1.0154 | Val acc: 46.79% | LR: 0.005162
Epoch: 027 | MCC: 0.037546 | Train loss: 0.9854 | Train acc: 50.85% | Val loss: 1.0138 | Val acc: 48.19% | LR: 0.005130
Epoch: 028 | MCC: 0.044204 | Train loss: 0.9836 | Train acc: 51.55% | Val loss: 0.9911 | Val acc: 51.76% | LR: 0.005097
Epoch: 029 | MCC: 0.037069 | Train loss: 0.9825 | Train acc: 51.12% | Val loss: 0.9635 | Val acc: 53.22% | LR: 0.005063
Epoch: 030 | MCC: 0.046368 | Train loss: 0.9815 | Train acc: 51.08% | Val loss: 0.9525 | Val acc: 54.25% | LR: 0.005028
Epoch: 031 | MCC: 0.046245 | Train loss: 0.9797 | Train acc: 51.13% | Val loss: 0.9608 | Val acc: 54.31% | LR: 0.004992
Epoch: 032 | MCC: 0.055973 | Train loss: 0.9818 | Train acc: 50.83% | Val loss: 0.9444 | Val acc: 55.91% | LR: 0.004955
Epoch: 033 | MCC: 0.048218 | Train loss: 0.9787 | Train acc: 51.38% | Val loss: 0.9485 | Val acc: 54.71% | LR: 0.004917
Epoch: 034 | MCC: 0.047056 | Train loss: 0.9805 | Train acc: 51.72% | Val loss: 0.9334 | Val acc: 55.59% | LR: 0.004878
Epoch: 035 | MCC: 0.045599 | Train loss: 0.9829 | Train acc: 51.51% | Val loss: 0.9245 | Val acc: 55.77% | LR: 0.004839
Epoch: 036 | MCC: 0.039804 | Train loss: 0.9791 | Train acc: 51.14% | Val loss: 0.9447 | Val acc: 56.54% | LR: 0.004798
Epoch: 037 | MCC: 0.052422 | Train loss: 0.9918 | Train acc: 51.13% | Val loss: 1.1118 | Val acc: 58.00% | LR: 0.004757
Epoch: 038 | MCC: 0.038136 | Train loss: 0.9815 | Train acc: 51.01% | Val loss: 0.9159 | Val acc: 56.24% | LR: 0.004715
Epoch: 039 | MCC: 0.037424 | Train loss: 0.9787 | Train acc: 51.89% | Val loss: 0.9111 | Val acc: 57.45% | LR: 0.004671
Epoch: 040 | MCC: 0.049736 | Train loss: 0.9791 | Train acc: 51.48% | Val loss: 0.9124 | Val acc: 57.58% | LR: 0.004627
Epoch: 041 | MCC: 0.029796 | Train loss: 0.9813 | Train acc: 51.35% | Val loss: 0.9034 | Val acc: 57.83% | LR: 0.004583
Epoch: 042 | MCC: -0.000086 | Train loss: 0.9761 | Train acc: 51.88% | Val loss: 0.9087 | Val acc: 56.56% | LR: 0.004537
Epoch: 043 | MCC: 0.047937 | Train loss: 0.9744 | Train acc: 51.36% | Val loss: 0.9397 | Val acc: 57.97% | LR: 0.004491
Epoch: 044 | MCC: -0.026952 | Train loss: 0.9925 | Train acc: 51.30% | Val loss: 1.8614 | Val acc: 55.12% | LR: 0.004444
Epoch: 045 | MCC: 0.016565 | Train loss: 0.9990 | Train acc: 50.32% | Val loss: 1.0391 | Val acc: 49.06% | LR: 0.004396
Epoch: 046 | MCC: 0.016632 | Train loss: 1.0106 | Train acc: 51.13% | Val loss: 1.2578 | Val acc: 55.69% | LR: 0.004348
Epoch: 047 | MCC: 0.005141 | Train loss: 1.0072 | Train acc: 50.64% | Val loss: 0.9519 | Val acc: 53.15% | LR: 0.004298
Epoch: 048 | MCC: 0.050414 | Train loss: 0.9925 | Train acc: 50.69% | Val loss: 0.9678 | Val acc: 55.39% | LR: 0.004249
Epoch: 049 | MCC: 0.022960 | Train loss: 0.9902 | Train acc: 51.05% | Val loss: 0.9262 | Val acc: 55.36% | LR: 0.004198
Epoch: 050 | MCC: 0.036374 | Train loss: 0.9935 | Train acc: 51.06% | Val loss: 0.9975 | Val acc: 52.88% | LR: 0.004147
Epoch: 051 | MCC: -0.028437 | Train loss: 1.0426 | Train acc: 50.79% | Val loss: 1.0359 | Val acc: 45.41% | LR: 0.004095
Epoch: 052 | MCC: -0.038275 | Train loss: 1.0052 | Train acc: 49.75% | Val loss: 1.0068 | Val acc: 47.43% | LR: 0.004043
Epoch: 053 | MCC: 0.031251 | Train loss: 0.9937 | Train acc: 50.61% | Val loss: 0.9682 | Val acc: 53.82% | LR: 0.003990
Epoch: 054 | MCC: -0.031330 | Train loss: 0.9925 | Train acc: 51.14% | Val loss: 1.0119 | Val acc: 48.37% | LR: 0.003937
Epoch: 055 | MCC: 0.050464 | Train loss: 0.9979 | Train acc: 50.74% | Val loss: 0.9363 | Val acc: 57.26% | LR: 0.003883
Epoch: 056 | MCC: 0.044686 | Train loss: 0.9989 | Train acc: 50.15% | Val loss: 0.9480 | Val acc: 57.34% | LR: 0.003829
Epoch: 057 | MCC: 0.045768 | Train loss: 0.9890 | Train acc: 51.22% | Val loss: 0.9366 | Val acc: 57.28% | LR: 0.003774
Epoch: 058 | MCC: 0.059230 | Train loss: 0.9857 | Train acc: 51.23% | Val loss: 0.9204 | Val acc: 58.22% | LR: 0.003719
Epoch: 059 | MCC: 0.019602 | Train loss: 0.9884 | Train acc: 51.24% | Val loss: 0.9196 | Val acc: 56.15% | LR: 0.003664
Epoch: 060 | MCC: 0.035780 | Train loss: 0.9856 | Train acc: 51.26% | Val loss: 0.9115 | Val acc: 57.50% | LR: 0.003608
Epoch: 061 | MCC: 0.045101 | Train loss: 0.9833 | Train acc: 51.38% | Val loss: 0.9010 | Val acc: 57.60% | LR: 0.003552
Epoch: 062 | MCC: 0.026882 | Train loss: 0.9790 | Train acc: 51.49% | Val loss: 0.9101 | Val acc: 56.67% | LR: 0.003495
Epoch: 063 | MCC: 0.044059 | Train loss: 0.9818 | Train acc: 51.60% | Val loss: 0.9150 | Val acc: 56.67% | LR: 0.003438
Epoch: 064 | MCC: 0.044110 | Train loss: 0.9820 | Train acc: 51.46% | Val loss: 0.9082 | Val acc: 57.22% | LR: 0.003381
Epoch: 065 | MCC: 0.031004 | Train loss: 0.9762 | Train acc: 51.62% | Val loss: 0.8958 | Val acc: 57.04% | LR: 0.003323
Epoch: 066 | MCC: 0.012843 | Train loss: 0.9805 | Train acc: 51.54% | Val loss: 0.9356 | Val acc: 55.21% | LR: 0.003266
Epoch: 067 | MCC: 0.050598 | Train loss: 0.9847 | Train acc: 51.35% | Val loss: 0.8881 | Val acc: 58.61% | LR: 0.003208
Epoch: 068 | MCC: 0.024364 | Train loss: 0.9832 | Train acc: 51.50% | Val loss: 0.9169 | Val acc: 57.36% | LR: 0.003150
Epoch: 069 | MCC: 0.061040 | Train loss: 0.9794 | Train acc: 51.61% | Val loss: 0.8913 | Val acc: 58.22% | LR: 0.003092
Epoch: 070 | MCC: 0.016419 | Train loss: 0.9768 | Train acc: 51.49% | Val loss: 0.8952 | Val acc: 57.14% | LR: 0.003033
Epoch: 071 | MCC: 0.032564 | Train loss: 0.9801 | Train acc: 51.61% | Val loss: 0.8927 | Val acc: 57.27% | LR: 0.002975
Epoch: 072 | MCC: 0.028763 | Train loss: 0.9761 | Train acc: 51.71% | Val loss: 0.8986 | Val acc: 57.27% | LR: 0.002916
Epoch: 073 | MCC: 0.019426 | Train loss: 0.9720 | Train acc: 51.97% | Val loss: 0.8889 | Val acc: 57.29% | LR: 0.002858
Epoch: 074 | MCC: 0.011683 | Train loss: 0.9710 | Train acc: 51.88% | Val loss: 0.9049 | Val acc: 55.97% | LR: 0.002799
Epoch: 075 | MCC: 0.034332 | Train loss: 0.9734 | Train acc: 52.04% | Val loss: 0.8938 | Val acc: 57.04% | LR: 0.002740
Epoch: 076 | MCC: 0.026027 | Train loss: 0.9734 | Train acc: 51.89% | Val loss: 0.9040 | Val acc: 56.69% | LR: 0.002682
Epoch: 077 | MCC: 0.032398 | Train loss: 0.9714 | Train acc: 51.86% | Val loss: 0.8997 | Val acc: 57.28% | LR: 0.002623
Epoch: 078 | MCC: 0.002308 | Train loss: 0.9670 | Train acc: 52.02% | Val loss: 0.9202 | Val acc: 55.41% | LR: 0.002565
Epoch: 079 | MCC: 0.011945 | Train loss: 0.9654 | Train acc: 52.12% | Val loss: 0.9059 | Val acc: 56.32% | LR: 0.002507
Epoch: 080 | MCC: 0.000359 | Train loss: 0.9716 | Train acc: 52.18% | Val loss: 0.9236 | Val acc: 55.58% | LR: 0.002448
Epoch: 081 | MCC: 0.002208 | Train loss: 0.9713 | Train acc: 52.64% | Val loss: 0.9298 | Val acc: 55.57% | LR: 0.002390
Epoch: 082 | MCC: 0.014290 | Train loss: 0.9702 | Train acc: 52.66% | Val loss: 0.9087 | Val acc: 56.76% | LR: 0.002332
Epoch: 083 | MCC: -0.002063 | Train loss: 0.9678 | Train acc: 52.20% | Val loss: 0.9246 | Val acc: 55.23% | LR: 0.002275
Epoch: 084 | MCC: 0.000849 | Train loss: 0.9616 | Train acc: 52.34% | Val loss: 0.9146 | Val acc: 56.09% | LR: 0.002217
Epoch: 085 | MCC: -0.004899 | Train loss: 0.9622 | Train acc: 52.28% | Val loss: 0.9233 | Val acc: 55.46% | LR: 0.002160
Epoch: 086 | MCC: -0.000889 | Train loss: 0.9574 | Train acc: 52.57% | Val loss: 0.9210 | Val acc: 55.32% | LR: 0.002103
Epoch: 087 | MCC: -0.014981 | Train loss: 0.9582 | Train acc: 52.50% | Val loss: 0.9257 | Val acc: 55.10% | LR: 0.002047
Epoch: 088 | MCC: -0.011583 | Train loss: 0.9628 | Train acc: 52.70% | Val loss: 0.9567 | Val acc: 53.48% | LR: 0.001990

[I 2025-10-05 10:56:27,472] Trial 68 finished with value: -0.014034536434337497 and parameters: {'lr': 0.005597178169294727, 'hidden_size': 78, 'dropout': 0.12175729429646552, 'weight_decay': 0.0006066816521001903}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.037528 | Train loss: 1.0008 | Train acc: 50.04% | Val loss: 1.0027 | Val acc: 46.95% | LR: 0.000330
Epoch: 001 | MCC: 0.030611 | Train loss: 0.9964 | Train acc: 50.47% | Val loss: 0.9941 | Val acc: 52.34% | LR: 0.000330
Epoch: 002 | MCC: 0.025993 | Train loss: 0.9919 | Train acc: 50.59% | Val loss: 0.9840 | Val acc: 54.28% | LR: 0.000330
Epoch: 003 | MCC: 0.027428 | Train loss: 0.9873 | Train acc: 50.84% | Val loss: 0.9734 | Val acc: 54.71% | LR: 0.000330
Epoch: 004 | MCC: 0.019067 | Train loss: 0.9863 | Train acc: 50.81% | Val loss: 0.9571 | Val acc: 54.70% | LR: 0.000329
Epoch: 005 | MCC: 0.025280 | Train loss: 0.9829 | Train acc: 50.93% | Val loss: 0.9411 | Val acc: 55.47% | LR: 0.000329
Epoch: 006 | MCC: 0.010658 | Train loss: 0.9832 | Train acc: 50.99% | Val loss: 0.9278 | Val acc: 55.16% | LR: 0.000329
Epoch: 007 | MCC: 0.012166 | Train loss: 0.9811 | Train acc: 51.06% | Val loss: 0.9205 | Val acc: 55.88% | LR: 0.000328
Epoch: 008 | MCC: 0.020572 | Train loss: 0.9821 | Train acc: 50.92% | Val loss: 0.9124 | Val acc: 56.19% | LR: 0.000327
Epoch: 009 | MCC: 0.012489 | Train loss: 0.9815 | Train acc: 50.83% | Val loss: 0.9050 | Val acc: 56.18% | LR: 0.000327
Epoch: 010 | MCC: 0.028116 | Train loss: 0.9802 | Train acc: 50.95% | Val loss: 0.8984 | Val acc: 56.74% | LR: 0.000326
Epoch: 011 | MCC: 0.017238 | Train loss: 0.9796 | Train acc: 50.94% | Val loss: 0.8925 | Val acc: 56.96% | LR: 0.000325
Epoch: 012 | MCC: 0.029804 | Train loss: 0.9801 | Train acc: 50.94% | Val loss: 0.8870 | Val acc: 57.36% | LR: 0.000324
Epoch: 013 | MCC: 0.000797 | Train loss: 0.9799 | Train acc: 51.03% | Val loss: 0.8871 | Val acc: 56.16% | LR: 0.000323
Epoch: 014 | MCC: 0.000642 | Train loss: 0.9788 | Train acc: 51.14% | Val loss: 0.8801 | Val acc: 56.26% | LR: 0.000322
Epoch: 015 | MCC: 0.010991 | Train loss: 0.9784 | Train acc: 51.06% | Val loss: 0.8777 | Val acc: 56.86% | LR: 0.000321
Epoch: 016 | MCC: -0.010309 | Train loss: 1.2138 | Train acc: 51.14% | Val loss: 0.8913 | Val acc: 55.71% | LR: 0.000320
Epoch: 017 | MCC: -0.008708 | Train loss: 0.9768 | Train acc: 51.19% | Val loss: 0.8806 | Val acc: 56.01% | LR: 0.000319
Epoch: 018 | MCC: -0.003053 | Train loss: 0.9748 | Train acc: 51.22% | Val loss: 0.8801 | Val acc: 56.38% | LR: 0.000317
Epoch: 019 | MCC: -0.018489 | Train loss: 0.9738 | Train acc: 51.32% | Val loss: 0.8742 | Val acc: 56.31% | LR: 0.000316
Epoch: 020 | MCC: 0.002221 | Train loss: 0.9758 | Train acc: 51.20% | Val loss: 0.8771 | Val acc: 56.54% | LR: 0.000315
Epoch: 021 | MCC: 0.004365 | Train loss: 0.9751 | Train acc: 51.10% | Val loss: 0.8589 | Val acc: 57.71% | LR: 0.000313
Epoch: 022 | MCC: -0.003363 | Train loss: 0.9743 | Train acc: 51.26% | Val loss: 0.8655 | Val acc: 56.86% | LR: 0.000312
Epoch: 023 | MCC: -0.010917 | Train loss: 0.9729 | Train acc: 51.36% | Val loss: 0.8740 | Val acc: 56.47% | LR: 0.000310
Epoch: 024 | MCC: -0.002441 | Train loss: 0.9731 | Train acc: 51.29% | Val loss: 0.8699 | Val acc: 56.88% | LR: 0.000308
Epoch: 025 | MCC: -0.001736 | Train loss: 0.9717 | Train acc: 51.29% | Val loss: 0.8643 | Val acc: 57.20% | LR: 0.000307
Epoch: 026 | MCC: 0.000497 | Train loss: 0.9714 | Train acc: 51.47% | Val loss: 0.8633 | Val acc: 57.22% | LR: 0.000305
Epoch: 027 | MCC: 0.007456 | Train loss: 0.9723 | Train acc: 51.53% | Val loss: 0.8588 | Val acc: 57.59% | LR: 0.000303
Epoch: 028 | MCC: -0.015604 | Train loss: 0.9719 | Train acc: 51.20% | Val loss: 0.8744 | Val acc: 56.37% | LR: 0.000301
Epoch: 029 | MCC: 0.006334 | Train loss: 0.9795 | Train acc: 51.94% | Val loss: 0.8673 | Val acc: 57.37% | LR: 0.000299
Epoch: 030 | MCC: 0.001576 | Train loss: 0.9700 | Train acc: 52.06% | Val loss: 0.8638 | Val acc: 57.13% | LR: 0.000297
Epoch: 031 | MCC: 0.002283 | Train loss: 0.9709 | Train acc: 52.03% | Val loss: 0.8636 | Val acc: 57.35% | LR: 0.000295
Epoch: 032 | MCC: -0.010348 | Train loss: 0.9713 | Train acc: 51.94% | Val loss: 0.8713 | Val acc: 56.59% | LR: 0.000293
Epoch: 033 | MCC: -0.005683 | Train loss: 0.9741 | Train acc: 52.24% | Val loss: 0.8694 | Val acc: 56.61% | LR: 0.000290
Epoch: 034 | MCC: -0.006158 | Train loss: 0.9699 | Train acc: 52.05% | Val loss: 0.8659 | Val acc: 56.96% | LR: 0.000288
Epoch: 035 | MCC: -0.005566 | Train loss: 0.9720 | Train acc: 51.93% | Val loss: 0.8649 | Val acc: 57.03% | LR: 0.000286
Epoch: 036 | MCC: -0.001909 | Train loss: 0.9696 | Train acc: 52.19% | Val loss: 0.8634 | Val acc: 57.08% | LR: 0.000283
Epoch: 037 | MCC: 0.001147 | Train loss: 0.9715 | Train acc: 51.96% | Val loss: 0.8628 | Val acc: 57.25% | LR: 0.000281
Epoch: 038 | MCC: 0.004248 | Train loss: 0.9704 | Train acc: 51.95% | Val loss: 0.8611 | Val acc: 57.66% | LR: 0.000278
Epoch: 039 | MCC: 0.007761 | Train loss: 0.9689 | Train acc: 52.05% | Val loss: 0.8531 | Val acc: 58.07% | LR: 0.000276
Epoch: 040 | MCC: -0.000382 | Train loss: 0.9681 | Train acc: 52.04% | Val loss: 0.8664 | Val acc: 57.15% | LR: 0.000273
Epoch: 041 | MCC: 0.017489 | Train loss: 1.0085 | Train acc: 51.80% | Val loss: 0.8564 | Val acc: 58.25% | LR: 0.000271
Epoch: 042 | MCC: 0.003467 | Train loss: 0.9838 | Train acc: 51.83% | Val loss: 0.8660 | Val acc: 57.44% | LR: 0.000268
Epoch: 043 | MCC: 0.007890 | Train loss: 0.9768 | Train acc: 51.84% | Val loss: 0.8616 | Val acc: 57.83% | LR: 0.000265
Epoch: 044 | MCC: 0.014435 | Train loss: 0.9761 | Train acc: 51.79% | Val loss: 0.8480 | Val acc: 58.78% | LR: 0.000262
Epoch: 045 | MCC: 0.011591 | Train loss: 0.9752 | Train acc: 51.88% | Val loss: 0.8617 | Val acc: 57.88% | LR: 0.000260
Epoch: 046 | MCC: 0.015110 | Train loss: 0.9758 | Train acc: 51.77% | Val loss: 0.8568 | Val acc: 58.32% | LR: 0.000257
Epoch: 047 | MCC: 0.014017 | Train loss: 0.9747 | Train acc: 51.84% | Val loss: 0.8545 | Val acc: 58.27% | LR: 0.000254
Epoch: 048 | MCC: 0.018940 | Train loss: 0.9741 | Train acc: 51.76% | Val loss: 0.8514 | Val acc: 58.62% | LR: 0.000251
Epoch: 049 | MCC: 0.005464 | Train loss: 0.9729 | Train acc: 51.92% | Val loss: 0.8662 | Val acc: 57.66% | LR: 0.000248
Epoch: 050 | MCC: 0.021775 | Train loss: 0.9737 | Train acc: 51.97% | Val loss: 0.8500 | Val acc: 58.86% | LR: 0.000245
Epoch: 051 | MCC: 0.017106 | Train loss: 0.9732 | Train acc: 51.82% | Val loss: 0.8507 | Val acc: 58.74% | LR: 0.000242
Epoch: 052 | MCC: 0.011846 | Train loss: 0.9717 | Train acc: 51.78% | Val loss: 0.8624 | Val acc: 58.03% | LR: 0.000239
Epoch: 053 | MCC: 0.016793 | Train loss: 0.9702 | Train acc: 51.93% | Val loss: 0.8553 | Val acc: 58.44% | LR: 0.000236
Epoch: 054 | MCC: 0.044935 | Train loss: 0.9714 | Train acc: 51.39% | Val loss: 0.8499 | Val acc: 59.01% | LR: 0.000233
Epoch: 055 | MCC: 0.008148 | Train loss: 0.9706 | Train acc: 51.47% | Val loss: 0.8528 | Val acc: 58.77% | LR: 0.000229
Epoch: 056 | MCC: 0.041457 | Train loss: 0.9707 | Train acc: 51.39% | Val loss: 0.8562 | Val acc: 58.71% | LR: 0.000226
Epoch: 057 | MCC: 0.004835 | Train loss: 0.9700 | Train acc: 51.50% | Val loss: 0.8622 | Val acc: 58.33% | LR: 0.000223
Epoch: 058 | MCC: 0.024685 | Train loss: 0.9679 | Train acc: 51.63% | Val loss: 0.8507 | Val acc: 59.17% | LR: 0.000220
Epoch: 059 | MCC: 0.054137 | Train loss: 0.9672 | Train acc: 51.65% | Val loss: 0.8628 | Val acc: 58.50% | LR: 0.000217
Epoch: 060 | MCC: 0.031414 | Train loss: 0.9700 | Train acc: 51.55% | Val loss: 0.8474 | Val acc: 59.29% | LR: 0.000213
Epoch: 061 | MCC: 0.023695 | Train loss: 0.9656 | Train acc: 51.75% | Val loss: 0.8551 | Val acc: 58.95% | LR: 0.000210
Epoch: 062 | MCC: 0.026836 | Train loss: 0.9659 | Train acc: 51.67% | Val loss: 0.8588 | Val acc: 58.59% | LR: 0.000207
Epoch: 063 | MCC: 0.016245 | Train loss: 0.9648 | Train acc: 51.71% | Val loss: 0.8534 | Val acc: 58.94% | LR: 0.000203
Epoch: 064 | MCC: 0.036835 | Train loss: 0.9645 | Train acc: 51.70% | Val loss: 0.8593 | Val acc: 58.37% | LR: 0.000200
Epoch: 065 | MCC: 0.034293 | Train loss: 0.9643 | Train acc: 51.73% | Val loss: 0.8411 | Val acc: 59.59% | LR: 0.000197
Epoch: 066 | MCC: 0.023378 | Train loss: 0.9643 | Train acc: 51.67% | Val loss: 0.8529 | Val acc: 58.99% | LR: 0.000193
Epoch: 067 | MCC: 0.029085 | Train loss: 0.9649 | Train acc: 51.69% | Val loss: 0.8482 | Val acc: 59.01% | LR: 0.000190
Epoch: 068 | MCC: 0.022339 | Train loss: 0.9630 | Train acc: 51.54% | Val loss: 0.8514 | Val acc: 58.89% | LR: 0.000186
Epoch: 069 | MCC: 0.041762 | Train loss: 0.9620 | Train acc: 51.95% | Val loss: 0.8435 | Val acc: 59.39% | LR: 0.000183
Epoch: 070 | MCC: 0.048747 | Train loss: 0.9625 | Train acc: 51.86% | Val loss: 0.8427 | Val acc: 59.53% | LR: 0.000179
Epoch: 071 | MCC: 0.048783 | Train loss: 0.9615 | Train acc: 51.77% | Val loss: 0.8399 | Val acc: 59.48% | LR: 0.000176
Epoch: 072 | MCC: 0.052870 | Train loss: 0.9620 | Train acc: 51.55% | Val loss: 0.8447 | Val acc: 59.25% | LR: 0.000173
Epoch: 073 | MCC: 0.054494 | Train loss: 0.9622 | Train acc: 52.01% | Val loss: 0.8355 | Val acc: 59.72% | LR: 0.000169
Epoch: 074 | MCC: 0.036543 | Train loss: 0.9606 | Train acc: 52.26% | Val loss: 0.8453 | Val acc: 59.13% | LR: 0.000166
Epoch: 075 | MCC: 0.044951 | Train loss: 0.9604 | Train acc: 52.04% | Val loss: 0.8465 | Val acc: 59.13% | LR: 0.000162
Epoch: 076 | MCC: 0.048722 | Train loss: 0.9609 | Train acc: 52.39% | Val loss: 0.8409 | Val acc: 59.42% | LR: 0.000159
Epoch: 077 | MCC: 0.043028 | Train loss: 0.9591 | Train acc: 52.64% | Val loss: 0.8404 | Val acc: 59.53% | LR: 0.000155
Epoch: 078 | MCC: 0.038077 | Train loss: 0.9594 | Train acc: 52.49% | Val loss: 0.8359 | Val acc: 59.53% | LR: 0.000152
Epoch: 079 | MCC: 0.038094 | Train loss: 0.9615 | Train acc: 52.36% | Val loss: 0.8409 | Val acc: 59.32% | LR: 0.000148
Epoch: 080 | MCC: 0.047646 | Train loss: 0.9601 | Train acc: 52.57% | Val loss: 0.8372 | Val acc: 59.60% | LR: 0.000145
Epoch: 081 | MCC: 0.049045 | Train loss: 0.9581 | Train acc: 52.59% | Val loss: 0.8398 | Val acc: 59.55% | LR: 0.000142
Epoch: 082 | MCC: 0.047348 | Train loss: 0.9596 | Train acc: 52.48% | Val loss: 0.8430 | Val acc: 59.38% | LR: 0.000138
Epoch: 083 | MCC: 0.045479 | Train loss: 0.9723 | Train acc: 52.48% | Val loss: 0.8315 | Val acc: 59.84% | LR: 0.000135
Epoch: 084 | MCC: 0.051298 | Train loss: 0.9634 | Train acc: 52.58% | Val loss: 0.8391 | Val acc: 59.69% | LR: 0.000131
Epoch: 085 | MCC: 0.049740 | Train loss: 0.9623 | Train acc: 52.46% | Val loss: 0.8414 | Val acc: 59.60% | LR: 0.000128
Epoch: 086 | MCC: 0.052629 | Train loss: 0.9605 | Train acc: 52.23% | Val loss: 0.8361 | Val acc: 59.72% | LR: 0.000125
Epoch: 087 | MCC: 0.044583 | Train loss: 0.9618 | Train acc: 51.90% | Val loss: 0.8395 | Val acc: 59.44% | LR: 0.000121
Epoch: 088 | MCC: 0.048509 | Train loss: 0.9611 | Train acc: 52.00% | Val loss: 0.8451 | Val acc: 59.38% | LR: 0.000118
Epoch: 089 | MCC: 0.043207 | Train loss: 0.9637 | Train acc: 52.00% | Val loss: 0.8366 | Val acc: 59.50% | LR: 0.000115
Epoch: 090 | MCC: 0.048546 | Train loss: 0.9621 | Train acc: 52.02% | Val loss: 0.8420 | Val acc: 59.55% | LR: 0.000112
Epoch: 091 | MCC: 0.045863 | Train loss: 0.9628 | Train acc: 51.98% | Val loss: 0.8374 | Val acc: 59.71% | LR: 0.000108
Epoch: 092 | MCC: 0.045967 | Train loss: 0.9622 | Train acc: 52.09% | Val loss: 0.8400 | Val acc: 59.54% | LR: 0.000105
Epoch: 093 | MCC: 0.046102 | Train loss: 0.9632 | Train acc: 51.88% | Val loss: 0.8402 | Val acc: 59.40% | LR: 0.000102
Epoch: 094 | MCC: 0.046872 | Train loss: 0.9615 | Train acc: 52.03% | Val loss: 0.8437 | Val acc: 59.35% | LR: 0.000099
Epoch: 095 | MCC: 0.034309 | Train loss: 0.9597 | Train acc: 52.11% | Val loss: 0.8412 | Val acc: 59.22% | LR: 0.000096
Epoch: 096 | MCC: 0.051544 | Train loss: 0.9616 | Train acc: 51.98% | Val loss: 0.8395 | Val acc: 59.64% | LR: 0.000092
Epoch: 097 | MCC: 0.041259 | Train loss: 0.9630 | Train acc: 51.98% | Val loss: 0.8390 | Val acc: 59.50% | LR: 0.000089
Epoch: 098 | MCC: 0.049772 | Train loss: 0.9628 | Train acc: 51.98% | Val loss: 0.8412 | Val acc: 59.63% | LR: 0.000086
Epoch: 099 | MCC: 0.043270 | Train loss: 0.9629 | Train acc: 51.94% | Val loss: 0.8409 | Val acc: 59.34% | LR: 0.000083
Epoch: 100 | MCC: 0.037839 | Train loss: 0.9601 | Train acc: 52.16% | Val loss: 0.8388 | Val acc: 59.42% | LR: 0.000080
Epoch: 101 | MCC: 0.049851 | Train loss: 0.9602 | Train acc: 52.05% | Val loss: 0.8397 | Val acc: 59.52% | LR: 0.000077
Epoch: 102 | MCC: 0.047725 | Train loss: 0.9620 | Train acc: 52.00% | Val loss: 0.8393 | Val acc: 59.54% | LR: 0.000075
Epoch: 103 | MCC: 0.049726 | Train loss: 0.9625 | Train acc: 51.89% | Val loss: 0.8405 | Val acc: 59.55% | LR: 0.000072
Epoch: 104 | MCC: 0.044879 | Train loss: 0.9603 | Train acc: 52.11% | Val loss: 0.8388 | Val acc: 59.51% | LR: 0.000069
Epoch: 105 | MCC: 0.048421 | Train loss: 0.9620 | Train acc: 51.93% | Val loss: 0.8421 | Val acc: 59.51% | LR: 0.000066
Epoch: 106 | MCC: 0.049477 | Train loss: 0.9612 | Train acc: 52.05% | Val loss: 0.8396 | Val acc: 59.66% | LR: 0.000063
Epoch: 107 | MCC: 0.049024 | Train loss: 0.9623 | Train acc: 51.96% | Val loss: 0.8398 | Val acc: 59.61% | LR: 0.000061
Epoch: 108 | MCC: 0.050389 | Train loss: 0.9617 | Train acc: 51.97% | Val loss: 0.8382 | Val acc: 59.68% | LR: 0.000058
Epoch: 109 | MCC: 0.047622 | Train loss: 0.9605 | Train acc: 52.06% | Val loss: 0.8395 | Val acc: 59.59% | LR: 0.000055
Epoch: 110 | MCC: 0.053206 | Train loss: 0.9611 | Train acc: 52.01% | Val loss: 0.8396 | Val acc: 59.72% | LR: 0.000053
Epoch: 111 | MCC: 0.051633 | Train loss: 0.9609 | Train acc: 52.02% | Val loss: 0.8396 | Val acc: 59.64% | LR: 0.000050
Epoch: 112 | MCC: 0.048357 | Train loss: 0.9591 | Train acc: 52.12% | Val loss: 0.8397 | Val acc: 59.59% | LR: 0.000048
Epoch: 113 | MCC: 0.048966 | Train loss: 0.9605 | Train acc: 52.02% | Val loss: 0.8396 | Val acc: 59.63% | LR: 0.000046
Epoch: 114 | MCC: 0.050802 | Train loss: 0.9603 | Train acc: 52.06% | Val loss: 0.8394 | Val acc: 59.62% | LR: 0.000043
Epoch: 115 | MCC: 0.051130 | Train loss: 0.9612 | Train acc: 52.01% | Val loss: 0.8392 | Val acc: 59.67% | LR: 0.000041
Epoch: 116 | MCC: 0.051057 | Train loss: 0.9590 | Train acc: 52.13% | Val loss: 0.8396 | Val acc: 59.67% | LR: 0.000039
Epoch: 117 | MCC: 0.051557 | Train loss: 0.9599 | Train acc: 52.08% | Val loss: 0.8396 | Val acc: 59.64% | LR: 0.000037
Epoch: 118 | MCC: 0.051402 | Train loss: 0.9612 | Train acc: 52.03% | Val loss: 0.8409 | Val acc: 59.64% | LR: 0.000035
Epoch: 119 | MCC: 0.050961 | Train loss: 0.9603 | Train acc: 52.11% | Val loss: 0.8392 | Val acc: 59.64% | LR: 0.000032
Epoch: 120 | MCC: 0.051035 | Train loss: 0.9591 | Train acc: 52.14% | Val loss: 0.8404 | Val acc: 59.64% | LR: 0.000030
Epoch: 121 | MCC: 0.050653 | Train loss: 0.9579 | Train acc: 52.22% | Val loss: 0.8402 | Val acc: 59.62% | LR: 0.000029
Epoch: 122 | MCC: 0.047907 | Train loss: 0.9604 | Train acc: 52.04% | Val loss: 0.8403 | Val acc: 59.59% | LR: 0.000027
Epoch: 123 | MCC: 0.046946 | Train loss: 0.9584 | Train acc: 52.20% | Val loss: 0.8402 | Val acc: 59.56% | LR: 0.000025
Epoch: 124 | MCC: 0.050249 | Train loss: 0.9600 | Train acc: 52.05% | Val loss: 0.8411 | Val acc: 59.57% | LR: 0.000023
Epoch: 125 | MCC: 0.050249 | Train loss: 0.9581 | Train acc: 52.20% | Val loss: 0.8410 | Val acc: 59.57% | LR: 0.000021
Epoch: 126 | MCC: 0.050249 | Train loss: 0.9593 | Train acc: 52.07% | Val loss: 0.8410 | Val acc: 59.57% | LR: 0.000020
Epoch: 127 | MCC: 0.049500 | Train loss: 0.9598 | Train acc: 52.11% | Val loss: 0.8409 | Val acc: 59.55% | LR: 0.000018
Epoch: 128 | MCC: 0.049500 | Train loss: 0.9599 | Train acc: 52.08% | Val loss: 0.8410 | Val acc: 59.55% | LR: 0.000017
Epoch: 129 | MCC: 0.048836 | Train loss: 0.9591 | Train acc: 52.09% | Val loss: 0.8410 | Val acc: 59.55% | LR: 0.000015
Epoch: 130 | MCC: 0.049500 | Train loss: 0.9598 | Train acc: 52.11% | Val loss: 0.8408 | Val acc: 59.55% | LR: 0.000014
Epoch: 131 | MCC: 0.048666 | Train loss: 0.9594 | Train acc: 52.09% | Val loss: 0.8408 | Val acc: 59.52% | LR: 0.000013
Epoch: 132 | MCC: 0.049007 | Train loss: 0.9589 | Train acc: 52.14% | Val loss: 0.8410 | Val acc: 59.57% | LR: 0.000011
Epoch: 133 | MCC: 0.048836 | Train loss: 0.9593 | Train acc: 52.12% | Val loss: 0.8409 | Val acc: 59.55% | LR: 0.000010
Epoch: 134 | MCC: 0.048836 | Train loss: 0.9602 | Train acc: 52.07% | Val loss: 0.8409 | Val acc: 59.55% | LR: 0.000009
Epoch: 135 | MCC: 0.049007 | Train loss: 0.9572 | Train acc: 52.26% | Val loss: 0.8412 | Val acc: 59.57% | LR: 0.000008
Epoch: 136 | MCC: 0.048836 | Train loss: 0.9584 | Train acc: 52.15% | Val loss: 0.8410 | Val acc: 59.55% | LR: 0.000007
Epoch: 137 | MCC: 0.048836 | Train loss: 0.9590 | Train acc: 52.13% | Val loss: 0.8408 | Val acc: 59.55% | LR: 0.000006
Epoch: 138 | MCC: 0.049291 | Train loss: 0.9577 | Train acc: 52.18% | Val loss: 0.8408 | Val acc: 59.57% | LR: 0.000005
Epoch: 139 | MCC: 0.049007 | Train loss: 0.9609 | Train acc: 51.98% | Val loss: 0.8411 | Val acc: 59.57% | LR: 0.000005
Epoch: 140 | MCC: 0.048836 | Train loss: 0.9584 | Train acc: 52.16% | Val loss: 0.8412 | Val acc: 59.55% | LR: 0.000004
Epoch: 141 | MCC: 0.048836 | Train loss: 0.9600 | Train acc: 52.06% | Val loss: 0.8410 | Val acc: 59.55% | LR: 0.000003
Epoch: 142 | MCC: 0.049291 | Train loss: 0.9594 | Train acc: 52.09% | Val loss: 0.8409 | Val acc: 59.57% | LR: 0.000003
Epoch: 143 | MCC: 0.049291 | Train loss: 0.9594 | Train acc: 52.14% | Val loss: 0.8409 | Val acc: 59.57% | LR: 0.000002
Epoch: 144 | MCC: 0.049291 | Train loss: 0.9579 | Train acc: 52.17% | Val loss: 0.8409 | Val acc: 59.57% | LR: 0.000002
Epoch: 145 | MCC: 0.049291 | Train loss: 0.9597 | Train acc: 52.08% | Val loss: 0.8408 | Val acc: 59.57% | LR: 0.000002
Epoch: 146 | MCC: 0.049291 | Train loss: 0.9588 | Train acc: 52.16% | Val loss: 0.8408 | Val acc: 59.57% | LR: 0.000001
Epoch: 147 | MCC: 0.049291 | Train loss: 0.9592 | Train acc: 52.16% | Val loss: 0.8408 | Val acc: 59.57% | LR: 0.000001
Epoch: 148 | MCC: 0.049291 | Train loss: 0.9600 | Train acc: 52.10% | Val loss: 0.8409 | Val acc: 59.57% | LR: 0.000001
Epoch: 149 | MCC: 0.049462 | Train loss: 0.9584 | Train acc: 52.13% | Val loss: 0.8408 | Val acc: 59.60% | LR: 0.000001

[I 2025-10-05 10:58:41,108] Trial 69 finished with value: 0.04946180758997798 and parameters: {'lr': 0.00033032520650050427, 'hidden_size': 68, 'dropout': 0.08442941437029183, 'weight_decay': 0.027399626910517633}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.035812 | Train loss: 1.0030 | Train acc: 49.70% | Val loss: 1.0020 | Val acc: 46.87% | LR: 0.000246
Epoch: 001 | MCC: 0.040994 | Train loss: 1.0008 | Train acc: 49.50% | Val loss: 0.9999 | Val acc: 47.38% | LR: 0.000246
Epoch: 002 | MCC: 0.051213 | Train loss: 0.9990 | Train acc: 50.56% | Val loss: 1.0021 | Val acc: 46.50% | LR: 0.000246
Epoch: 003 | MCC: 0.047709 | Train loss: 0.9982 | Train acc: 50.62% | Val loss: 1.0117 | Val acc: 46.88% | LR: 0.000246
Epoch: 004 | MCC: 0.051295 | Train loss: 0.9953 | Train acc: 50.72% | Val loss: 1.0029 | Val acc: 48.10% | LR: 0.000246
Epoch: 005 | MCC: 0.067377 | Train loss: 0.9941 | Train acc: 50.65% | Val loss: 1.0004 | Val acc: 49.69% | LR: 0.000245
Epoch: 006 | MCC: 0.045812 | Train loss: 0.9924 | Train acc: 50.63% | Val loss: 0.9969 | Val acc: 49.53% | LR: 0.000245
Epoch: 007 | MCC: 0.036347 | Train loss: 0.9898 | Train acc: 50.75% | Val loss: 1.0040 | Val acc: 49.74% | LR: 0.000245
Epoch: 008 | MCC: 0.053706 | Train loss: 0.9902 | Train acc: 50.73% | Val loss: 0.9935 | Val acc: 51.49% | LR: 0.000244
Epoch: 009 | MCC: 0.054629 | Train loss: 0.9900 | Train acc: 50.72% | Val loss: 0.9923 | Val acc: 51.85% | LR: 0.000244
Epoch: 010 | MCC: 0.048084 | Train loss: 0.9890 | Train acc: 50.71% | Val loss: 0.9863 | Val acc: 53.40% | LR: 0.000243
Epoch: 011 | MCC: 0.039021 | Train loss: 0.9868 | Train acc: 50.79% | Val loss: 0.9824 | Val acc: 54.21% | LR: 0.000243
Epoch: 012 | MCC: 0.041896 | Train loss: 0.9851 | Train acc: 50.94% | Val loss: 0.9792 | Val acc: 54.55% | LR: 0.000242
Epoch: 013 | MCC: 0.038715 | Train loss: 0.9843 | Train acc: 50.98% | Val loss: 0.9751 | Val acc: 54.79% | LR: 0.000241
Epoch: 014 | MCC: 0.035650 | Train loss: 0.9840 | Train acc: 51.02% | Val loss: 0.9718 | Val acc: 54.85% | LR: 0.000240
Epoch: 015 | MCC: 0.044697 | Train loss: 0.9845 | Train acc: 50.93% | Val loss: 0.9662 | Val acc: 55.61% | LR: 0.000240
Epoch: 016 | MCC: 0.035472 | Train loss: 0.9857 | Train acc: 50.93% | Val loss: 0.9588 | Val acc: 55.92% | LR: 0.000239
Epoch: 017 | MCC: 0.034834 | Train loss: 0.9829 | Train acc: 51.02% | Val loss: 0.9784 | Val acc: 55.97% | LR: 0.000238
Epoch: 018 | MCC: 0.035508 | Train loss: 0.9844 | Train acc: 50.93% | Val loss: 0.9489 | Val acc: 56.40% | LR: 0.000237
Epoch: 019 | MCC: 0.031843 | Train loss: 0.9849 | Train acc: 50.89% | Val loss: 0.9409 | Val acc: 56.89% | LR: 0.000236
Epoch: 020 | MCC: 0.034587 | Train loss: 0.9833 | Train acc: 50.95% | Val loss: 0.9349 | Val acc: 56.98% | LR: 0.000235
Epoch: 021 | MCC: 0.032008 | Train loss: 0.9836 | Train acc: 50.90% | Val loss: 0.9349 | Val acc: 56.73% | LR: 0.000234
Epoch: 022 | MCC: 0.028425 | Train loss: 0.9811 | Train acc: 50.96% | Val loss: 0.9309 | Val acc: 56.46% | LR: 0.000232
Epoch: 023 | MCC: 0.026592 | Train loss: 0.9829 | Train acc: 50.80% | Val loss: 0.9265 | Val acc: 56.53% | LR: 0.000231
Epoch: 024 | MCC: 0.025355 | Train loss: 0.9821 | Train acc: 50.92% | Val loss: 0.9210 | Val acc: 56.59% | LR: 0.000230
Epoch: 025 | MCC: 0.025782 | Train loss: 0.9822 | Train acc: 50.98% | Val loss: 0.9128 | Val acc: 56.78% | LR: 0.000229
Epoch: 026 | MCC: 0.038554 | Train loss: 0.9800 | Train acc: 51.14% | Val loss: 0.9084 | Val acc: 57.59% | LR: 0.000227
Epoch: 027 | MCC: 0.049684 | Train loss: 0.9805 | Train acc: 51.07% | Val loss: 0.9015 | Val acc: 58.21% | LR: 0.000226
Epoch: 028 | MCC: 0.050466 | Train loss: 0.9810 | Train acc: 50.99% | Val loss: 0.8970 | Val acc: 58.45% | LR: 0.000224
Epoch: 029 | MCC: 0.051787 | Train loss: 0.9809 | Train acc: 51.03% | Val loss: 0.8952 | Val acc: 58.39% | LR: 0.000223
Epoch: 030 | MCC: 0.035955 | Train loss: 0.9800 | Train acc: 51.01% | Val loss: 0.8882 | Val acc: 57.67% | LR: 0.000221
Epoch: 031 | MCC: -0.000191 | Train loss: 0.9779 | Train acc: 51.19% | Val loss: 0.8852 | Val acc: 56.74% | LR: 0.000220
Epoch: 032 | MCC: -0.006096 | Train loss: 0.9795 | Train acc: 51.06% | Val loss: 0.8879 | Val acc: 55.97% | LR: 0.000218
Epoch: 033 | MCC: -0.001965 | Train loss: 0.9786 | Train acc: 51.14% | Val loss: 0.8806 | Val acc: 56.41% | LR: 0.000217
Epoch: 034 | MCC: 0.015227 | Train loss: 0.9761 | Train acc: 51.20% | Val loss: 0.8879 | Val acc: 56.30% | LR: 0.000215
Epoch: 035 | MCC: 0.011324 | Train loss: 0.9774 | Train acc: 51.12% | Val loss: 0.8812 | Val acc: 56.69% | LR: 0.000213
Epoch: 036 | MCC: 0.010080 | Train loss: 0.9751 | Train acc: 51.31% | Val loss: 0.8822 | Val acc: 56.47% | LR: 0.000211
Epoch: 037 | MCC: 0.010285 | Train loss: 0.9736 | Train acc: 51.36% | Val loss: 0.8768 | Val acc: 56.93% | LR: 0.000210
Epoch: 038 | MCC: 0.006286 | Train loss: 0.9754 | Train acc: 51.20% | Val loss: 0.8596 | Val acc: 57.91% | LR: 0.000208
Epoch: 039 | MCC: 0.017848 | Train loss: 0.9754 | Train acc: 51.32% | Val loss: 0.8721 | Val acc: 57.03% | LR: 0.000206
Epoch: 040 | MCC: 0.007822 | Train loss: 0.9741 | Train acc: 51.27% | Val loss: 0.8626 | Val acc: 57.74% | LR: 0.000204
Epoch: 041 | MCC: 0.003481 | Train loss: 0.9731 | Train acc: 51.37% | Val loss: 0.8652 | Val acc: 57.27% | LR: 0.000202
Epoch: 042 | MCC: 0.018434 | Train loss: 0.9840 | Train acc: 51.34% | Val loss: 0.8550 | Val acc: 58.22% | LR: 0.000200
Epoch: 043 | MCC: 0.005598 | Train loss: 0.9737 | Train acc: 51.32% | Val loss: 0.8673 | Val acc: 57.10% | LR: 0.000198
Epoch: 044 | MCC: 0.007652 | Train loss: 0.9733 | Train acc: 51.32% | Val loss: 0.8768 | Val acc: 56.49% | LR: 0.000196
Epoch: 045 | MCC: 0.001603 | Train loss: 0.9735 | Train acc: 51.34% | Val loss: 0.8632 | Val acc: 57.32% | LR: 0.000194
Epoch: 046 | MCC: 0.010968 | Train loss: 0.9715 | Train acc: 51.50% | Val loss: 0.8766 | Val acc: 57.13% | LR: 0.000192
Epoch: 047 | MCC: 0.020565 | Train loss: 0.9728 | Train acc: 51.42% | Val loss: 0.8563 | Val acc: 57.96% | LR: 0.000189
Epoch: 048 | MCC: -0.002432 | Train loss: 0.9725 | Train acc: 51.33% | Val loss: 0.8721 | Val acc: 56.61% | LR: 0.000187
Epoch: 049 | MCC: 0.011270 | Train loss: 0.9723 | Train acc: 51.38% | Val loss: 0.8593 | Val acc: 57.54% | LR: 0.000185
Epoch: 050 | MCC: 0.016386 | Train loss: 0.9730 | Train acc: 51.25% | Val loss: 0.8596 | Val acc: 57.64% | LR: 0.000183
Epoch: 051 | MCC: 0.015630 | Train loss: 0.9728 | Train acc: 51.39% | Val loss: 0.8628 | Val acc: 57.64% | LR: 0.000181
Epoch: 052 | MCC: 0.013728 | Train loss: 0.9707 | Train acc: 51.54% | Val loss: 0.8407 | Val acc: 58.68% | LR: 0.000178
Epoch: 053 | MCC: 0.005848 | Train loss: 0.9926 | Train acc: 51.15% | Val loss: 0.8699 | Val acc: 56.88% | LR: 0.000176
Epoch: 054 | MCC: -0.001636 | Train loss: 0.9795 | Train acc: 51.05% | Val loss: 0.8471 | Val acc: 58.39% | LR: 0.000174
Epoch: 055 | MCC: 0.015708 | Train loss: 0.9873 | Train acc: 51.17% | Val loss: 0.8580 | Val acc: 57.88% | LR: 0.000171
Epoch: 056 | MCC: -0.012041 | Train loss: 0.9758 | Train acc: 51.26% | Val loss: 0.8513 | Val acc: 57.75% | LR: 0.000169
Epoch: 057 | MCC: 0.005348 | Train loss: 0.9778 | Train acc: 51.18% | Val loss: 0.8524 | Val acc: 58.03% | LR: 0.000166
Epoch: 058 | MCC: 0.015113 | Train loss: 0.9739 | Train acc: 51.38% | Val loss: 0.8579 | Val acc: 57.57% | LR: 0.000164
Epoch: 059 | MCC: -0.008233 | Train loss: 0.9737 | Train acc: 51.34% | Val loss: 0.8452 | Val acc: 58.12% | LR: 0.000162
Epoch: 060 | MCC: 0.017608 | Train loss: 0.9748 | Train acc: 51.34% | Val loss: 0.8548 | Val acc: 57.79% | LR: 0.000159
Epoch: 061 | MCC: 0.017117 | Train loss: 0.9719 | Train acc: 51.45% | Val loss: 0.8389 | Val acc: 58.48% | LR: 0.000157
Epoch: 062 | MCC: -0.000639 | Train loss: 0.9742 | Train acc: 51.31% | Val loss: 0.8577 | Val acc: 57.39% | LR: 0.000154
Epoch: 063 | MCC: 0.010141 | Train loss: 0.9731 | Train acc: 51.41% | Val loss: 0.8418 | Val acc: 58.42% | LR: 0.000152
Epoch: 064 | MCC: -0.002044 | Train loss: 0.9718 | Train acc: 51.51% | Val loss: 0.8508 | Val acc: 57.80% | LR: 0.000149
Epoch: 065 | MCC: 0.013419 | Train loss: 0.9739 | Train acc: 51.51% | Val loss: 0.8527 | Val acc: 57.82% | LR: 0.000147
Epoch: 066 | MCC: 0.009451 | Train loss: 0.9732 | Train acc: 51.44% | Val loss: 0.8459 | Val acc: 58.18% | LR: 0.000144
Epoch: 067 | MCC: 0.008830 | Train loss: 0.9723 | Train acc: 51.43% | Val loss: 0.8566 | Val acc: 57.34% | LR: 0.000142
Epoch: 068 | MCC: 0.007986 | Train loss: 0.9710 | Train acc: 51.58% | Val loss: 0.8473 | Val acc: 58.08% | LR: 0.000139
Epoch: 069 | MCC: -0.006483 | Train loss: 0.9721 | Train acc: 51.46% | Val loss: 0.8485 | Val acc: 57.82% | LR: 0.000137
Epoch: 070 | MCC: -0.015350 | Train loss: 0.9719 | Train acc: 51.50% | Val loss: 0.8493 | Val acc: 57.60% | LR: 0.000134
Epoch: 071 | MCC: 0.015744 | Train loss: 0.9707 | Train acc: 51.50% | Val loss: 0.8547 | Val acc: 57.50% | LR: 0.000131
Epoch: 072 | MCC: 0.013787 | Train loss: 0.9713 | Train acc: 51.46% | Val loss: 0.8559 | Val acc: 57.58% | LR: 0.000129
Epoch: 073 | MCC: -0.013215 | Train loss: 0.9726 | Train acc: 51.37% | Val loss: 0.8631 | Val acc: 57.05% | LR: 0.000126
Epoch: 074 | MCC: -0.013388 | Train loss: 0.9715 | Train acc: 51.38% | Val loss: 0.8504 | Val acc: 57.57% | LR: 0.000124
Epoch: 075 | MCC: 0.016796 | Train loss: 0.9697 | Train acc: 51.52% | Val loss: 0.8553 | Val acc: 57.69% | LR: 0.000121
Epoch: 076 | MCC: 0.014924 | Train loss: 0.9713 | Train acc: 51.44% | Val loss: 0.8340 | Val acc: 58.87% | LR: 0.000119
Epoch: 077 | MCC: 0.017537 | Train loss: 0.9710 | Train acc: 51.43% | Val loss: 0.8521 | Val acc: 57.74% | LR: 0.000116
Epoch: 078 | MCC: 0.018006 | Train loss: 0.9690 | Train acc: 51.54% | Val loss: 0.8488 | Val acc: 57.86% | LR: 0.000113
Epoch: 079 | MCC: 0.023406 | Train loss: 0.9685 | Train acc: 51.55% | Val loss: 0.8532 | Val acc: 58.08% | LR: 0.000111
Epoch: 080 | MCC: 0.014382 | Train loss: 0.9699 | Train acc: 51.46% | Val loss: 0.8439 | Val acc: 58.12% | LR: 0.000108
Epoch: 081 | MCC: 0.007630 | Train loss: 0.9692 | Train acc: 51.50% | Val loss: 0.8557 | Val acc: 57.66% | LR: 0.000106
Epoch: 082 | MCC: 0.017364 | Train loss: 0.9692 | Train acc: 51.49% | Val loss: 0.8475 | Val acc: 57.98% | LR: 0.000103
Epoch: 083 | MCC: 0.024404 | Train loss: 1.0029 | Train acc: 51.55% | Val loss: 0.8494 | Val acc: 58.01% | LR: 0.000101
Epoch: 084 | MCC: 0.023523 | Train loss: 0.9686 | Train acc: 51.55% | Val loss: 0.8444 | Val acc: 58.18% | LR: 0.000098
Epoch: 085 | MCC: 0.018438 | Train loss: 0.9687 | Train acc: 51.53% | Val loss: 0.8524 | Val acc: 57.96% | LR: 0.000096
Epoch: 086 | MCC: 0.020680 | Train loss: 0.9701 | Train acc: 51.46% | Val loss: 0.8485 | Val acc: 58.02% | LR: 0.000093
Epoch: 087 | MCC: 0.024849 | Train loss: 0.9697 | Train acc: 51.45% | Val loss: 0.8503 | Val acc: 57.96% | LR: 0.000091
Epoch: 088 | MCC: 0.015205 | Train loss: 0.9682 | Train acc: 51.57% | Val loss: 0.8450 | Val acc: 58.17% | LR: 0.000088
Epoch: 089 | MCC: 0.012173 | Train loss: 0.9684 | Train acc: 51.62% | Val loss: 0.8485 | Val acc: 57.82% | LR: 0.000086
Epoch: 090 | MCC: 0.024523 | Train loss: 0.9695 | Train acc: 51.49% | Val loss: 0.8514 | Val acc: 57.81% | LR: 0.000083
Epoch: 091 | MCC: -0.000352 | Train loss: 0.9682 | Train acc: 51.59% | Val loss: 0.8486 | Val acc: 57.97% | LR: 0.000081
Epoch: 092 | MCC: 0.027314 | Train loss: 0.9681 | Train acc: 51.57% | Val loss: 0.8531 | Val acc: 57.74% | LR: 0.000079
Epoch: 093 | MCC: 0.016125 | Train loss: 0.9690 | Train acc: 51.47% | Val loss: 0.8481 | Val acc: 57.99% | LR: 0.000076
Epoch: 094 | MCC: 0.022437 | Train loss: 0.9676 | Train acc: 51.59% | Val loss: 0.8476 | Val acc: 57.98% | LR: 0.000074
Epoch: 095 | MCC: 0.010482 | Train loss: 0.9681 | Train acc: 51.58% | Val loss: 0.8480 | Val acc: 57.82% | LR: 0.000071
Epoch: 096 | MCC: 0.018457 | Train loss: 0.9664 | Train acc: 51.62% | Val loss: 0.8499 | Val acc: 57.79% | LR: 0.000069
Epoch: 097 | MCC: 0.014817 | Train loss: 0.9678 | Train acc: 51.63% | Val loss: 0.8452 | Val acc: 58.14% | LR: 0.000067
Epoch: 098 | MCC: 0.026710 | Train loss: 0.9691 | Train acc: 51.51% | Val loss: 0.8548 | Val acc: 57.66% | LR: 0.000065
Epoch: 099 | MCC: 0.027279 | Train loss: 0.9689 | Train acc: 51.50% | Val loss: 0.8435 | Val acc: 58.37% | LR: 0.000062
Epoch: 100 | MCC: 0.026476 | Train loss: 0.9683 | Train acc: 51.55% | Val loss: 0.8540 | Val acc: 57.76% | LR: 0.000060
Epoch: 101 | MCC: 0.017122 | Train loss: 0.9685 | Train acc: 51.55% | Val loss: 0.8516 | Val acc: 57.98% | LR: 0.000058
Epoch: 102 | MCC: 0.028775 | Train loss: 0.9687 | Train acc: 51.53% | Val loss: 0.8507 | Val acc: 57.98% | LR: 0.000056
Epoch: 103 | MCC: 0.015848 | Train loss: 0.9669 | Train acc: 51.56% | Val loss: 0.8442 | Val acc: 58.17% | LR: 0.000054
Epoch: 104 | MCC: 0.026499 | Train loss: 0.9664 | Train acc: 51.62% | Val loss: 0.8488 | Val acc: 58.01% | LR: 0.000052
Epoch: 105 | MCC: 0.018717 | Train loss: 0.9672 | Train acc: 51.54% | Val loss: 0.8451 | Val acc: 58.21% | LR: 0.000050
Epoch: 106 | MCC: 0.018518 | Train loss: 0.9658 | Train acc: 51.66% | Val loss: 0.8416 | Val acc: 58.34% | LR: 0.000047
Epoch: 107 | MCC: 0.016993 | Train loss: 0.9679 | Train acc: 51.54% | Val loss: 0.8446 | Val acc: 58.21% | LR: 0.000045
Epoch: 108 | MCC: 0.023027 | Train loss: 0.9665 | Train acc: 51.67% | Val loss: 0.8513 | Val acc: 57.86% | LR: 0.000044
Epoch: 109 | MCC: 0.026894 | Train loss: 0.9681 | Train acc: 51.60% | Val loss: 0.8466 | Val acc: 58.18% | LR: 0.000042
Epoch: 110 | MCC: 0.020454 | Train loss: 0.9669 | Train acc: 51.56% | Val loss: 0.8493 | Val acc: 57.83% | LR: 0.000040
Epoch: 111 | MCC: 0.029227 | Train loss: 0.9677 | Train acc: 51.52% | Val loss: 0.8426 | Val acc: 58.37% | LR: 0.000038
Epoch: 112 | MCC: 0.028942 | Train loss: 0.9671 | Train acc: 51.55% | Val loss: 0.8474 | Val acc: 58.18% | LR: 0.000036
Epoch: 113 | MCC: 0.020309 | Train loss: 0.9677 | Train acc: 51.52% | Val loss: 0.8513 | Val acc: 57.76% | LR: 0.000034
Epoch: 114 | MCC: 0.024793 | Train loss: 0.9678 | Train acc: 51.55% | Val loss: 0.8467 | Val acc: 58.08% | LR: 0.000033
Epoch: 115 | MCC: 0.026129 | Train loss: 0.9660 | Train acc: 51.62% | Val loss: 0.8482 | Val acc: 58.10% | LR: 0.000031
Epoch: 116 | MCC: 0.023551 | Train loss: 0.9669 | Train acc: 51.63% | Val loss: 0.8484 | Val acc: 58.03% | LR: 0.000029
Epoch: 117 | MCC: 0.027018 | Train loss: 0.9659 | Train acc: 51.66% | Val loss: 0.8485 | Val acc: 58.05% | LR: 0.000028
Epoch: 118 | MCC: 0.025765 | Train loss: 0.9672 | Train acc: 51.57% | Val loss: 0.8444 | Val acc: 58.18% | LR: 0.000026
Epoch: 119 | MCC: 0.025422 | Train loss: 0.9662 | Train acc: 51.65% | Val loss: 0.8459 | Val acc: 58.10% | LR: 0.000024
Epoch: 120 | MCC: 0.026583 | Train loss: 0.9668 | Train acc: 51.61% | Val loss: 0.8479 | Val acc: 58.13% | LR: 0.000023
Epoch: 121 | MCC: 0.026652 | Train loss: 0.9658 | Train acc: 51.67% | Val loss: 0.8474 | Val acc: 58.13% | LR: 0.000021
Epoch: 122 | MCC: 0.027324 | Train loss: 0.9645 | Train acc: 51.76% | Val loss: 0.8462 | Val acc: 58.15% | LR: 0.000020
Epoch: 123 | MCC: 0.028397 | Train loss: 0.9678 | Train acc: 51.55% | Val loss: 0.8443 | Val acc: 58.30% | LR: 0.000019
Epoch: 124 | MCC: 0.022577 | Train loss: 0.9664 | Train acc: 51.59% | Val loss: 0.8449 | Val acc: 58.08% | LR: 0.000017
Epoch: 125 | MCC: 0.025429 | Train loss: 0.9692 | Train acc: 51.46% | Val loss: 0.8465 | Val acc: 58.05% | LR: 0.000016
Epoch: 126 | MCC: 0.026130 | Train loss: 0.9682 | Train acc: 51.47% | Val loss: 0.8465 | Val acc: 58.10% | LR: 0.000015
Epoch: 127 | MCC: 0.027103 | Train loss: 0.9680 | Train acc: 51.50% | Val loss: 0.8474 | Val acc: 58.18% | LR: 0.000014
Epoch: 128 | MCC: 0.025782 | Train loss: 0.9668 | Train acc: 51.60% | Val loss: 0.8467 | Val acc: 58.10% | LR: 0.000013
Epoch: 129 | MCC: 0.022406 | Train loss: 0.9670 | Train acc: 51.52% | Val loss: 0.8454 | Val acc: 58.08% | LR: 0.000012
Epoch: 130 | MCC: 0.026061 | Train loss: 0.9678 | Train acc: 51.51% | Val loss: 0.8450 | Val acc: 58.22% | LR: 0.000011
Epoch: 131 | MCC: 0.023974 | Train loss: 0.9682 | Train acc: 51.51% | Val loss: 0.8449 | Val acc: 58.15% | LR: 0.000010
Epoch: 132 | MCC: 0.025960 | Train loss: 0.9674 | Train acc: 51.52% | Val loss: 0.8457 | Val acc: 58.18% | LR: 0.000009
Epoch: 133 | MCC: 0.025960 | Train loss: 0.9661 | Train acc: 51.68% | Val loss: 0.8457 | Val acc: 58.18% | LR: 0.000008
Epoch: 134 | MCC: 0.025575 | Train loss: 0.9666 | Train acc: 51.62% | Val loss: 0.8459 | Val acc: 58.15% | LR: 0.000007
Epoch: 135 | MCC: 0.025960 | Train loss: 0.9669 | Train acc: 51.61% | Val loss: 0.8454 | Val acc: 58.18% | LR: 0.000006
Epoch: 136 | MCC: 0.025960 | Train loss: 0.9661 | Train acc: 51.65% | Val loss: 0.8455 | Val acc: 58.18% | LR: 0.000006
Epoch: 137 | MCC: 0.022113 | Train loss: 0.9676 | Train acc: 51.53% | Val loss: 0.8463 | Val acc: 58.08% | LR: 0.000005
Epoch: 138 | MCC: 0.022650 | Train loss: 0.9666 | Train acc: 51.60% | Val loss: 0.8465 | Val acc: 58.01% | LR: 0.000004
Epoch: 139 | MCC: 0.023953 | Train loss: 0.9668 | Train acc: 51.60% | Val loss: 0.8459 | Val acc: 58.13% | LR: 0.000004
Epoch: 140 | MCC: 0.025960 | Train loss: 0.9678 | Train acc: 51.52% | Val loss: 0.8457 | Val acc: 58.18% | LR: 0.000003
Epoch: 141 | MCC: 0.025960 | Train loss: 0.9659 | Train acc: 51.62% | Val loss: 0.8457 | Val acc: 58.18% | LR: 0.000003
Epoch: 142 | MCC: 0.025960 | Train loss: 0.9675 | Train acc: 51.59% | Val loss: 0.8455 | Val acc: 58.18% | LR: 0.000002
Epoch: 143 | MCC: 0.025960 | Train loss: 0.9673 | Train acc: 51.61% | Val loss: 0.8455 | Val acc: 58.18% | LR: 0.000002
Epoch: 144 | MCC: 0.025960 | Train loss: 0.9668 | Train acc: 51.54% | Val loss: 0.8452 | Val acc: 58.18% | LR: 0.000002
Epoch: 145 | MCC: 0.025960 | Train loss: 0.9668 | Train acc: 51.57% | Val loss: 0.8451 | Val acc: 58.18% | LR: 0.000001
Epoch: 146 | MCC: 0.025960 | Train loss: 0.9673 | Train acc: 51.51% | Val loss: 0.8453 | Val acc: 58.18% | LR: 0.000001
Epoch: 147 | MCC: 0.025960 | Train loss: 0.9672 | Train acc: 51.51% | Val loss: 0.8454 | Val acc: 58.18% | LR: 0.000001
Epoch: 148 | MCC: 0.025960 | Train loss: 0.9681 | Train acc: 51.55% | Val loss: 0.8453 | Val acc: 58.18% | LR: 0.000001
Epoch: 149 | MCC: 0.025960 | Train loss: 0.9661 | Train acc: 51.58% | Val loss: 0.8454 | Val acc: 58.18% | LR: 0.000001

[I 2025-10-05 11:00:56,792] Trial 70 finished with value: 0.025960358791053295 and parameters: {'lr': 0.0002463617878314253, 'hidden_size': 74, 'dropout': 0.14661195963564122, 'weight_decay': 0.02178657898840246}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.007775 | Train loss: 0.9993 | Train acc: 50.61% | Val loss: 1.0110 | Val acc: 49.65% | LR: 0.000328
Epoch: 001 | MCC: 0.014100 | Train loss: 0.9972 | Train acc: 50.71% | Val loss: 1.0007 | Val acc: 50.13% | LR: 0.000328
Epoch: 002 | MCC: 0.018560 | Train loss: 0.9946 | Train acc: 50.83% | Val loss: 1.0000 | Val acc: 50.71% | LR: 0.000328
Epoch: 003 | MCC: 0.026620 | Train loss: 0.9931 | Train acc: 50.65% | Val loss: 0.9988 | Val acc: 51.07% | LR: 0.000328
Epoch: 004 | MCC: 0.039428 | Train loss: 0.9904 | Train acc: 50.66% | Val loss: 1.0093 | Val acc: 51.41% | LR: 0.000328
Epoch: 005 | MCC: 0.029002 | Train loss: 0.9899 | Train acc: 50.59% | Val loss: 0.9997 | Val acc: 52.56% | LR: 0.000327
Epoch: 006 | MCC: 0.036503 | Train loss: 0.9891 | Train acc: 50.75% | Val loss: 0.9917 | Val acc: 52.67% | LR: 0.000327
Epoch: 007 | MCC: 0.027011 | Train loss: 0.9877 | Train acc: 50.69% | Val loss: 0.9929 | Val acc: 53.02% | LR: 0.000326
Epoch: 008 | MCC: 0.020871 | Train loss: 0.9848 | Train acc: 50.82% | Val loss: 0.9864 | Val acc: 53.08% | LR: 0.000326
Epoch: 009 | MCC: 0.033972 | Train loss: 0.9849 | Train acc: 50.87% | Val loss: 0.9815 | Val acc: 54.19% | LR: 0.000325
Epoch: 010 | MCC: 0.029915 | Train loss: 0.9859 | Train acc: 50.73% | Val loss: 0.9749 | Val acc: 54.45% | LR: 0.000324
Epoch: 011 | MCC: 0.028954 | Train loss: 0.9826 | Train acc: 50.96% | Val loss: 0.9694 | Val acc: 54.83% | LR: 0.000323
Epoch: 012 | MCC: 0.024300 | Train loss: 0.9838 | Train acc: 50.85% | Val loss: 0.9612 | Val acc: 55.20% | LR: 0.000322
Epoch: 013 | MCC: 0.031099 | Train loss: 0.9829 | Train acc: 50.88% | Val loss: 0.9524 | Val acc: 55.67% | LR: 0.000322
Epoch: 014 | MCC: 0.019647 | Train loss: 0.9836 | Train acc: 50.89% | Val loss: 0.9409 | Val acc: 55.52% | LR: 0.000320
Epoch: 015 | MCC: 0.011512 | Train loss: 0.9825 | Train acc: 50.90% | Val loss: 0.9271 | Val acc: 55.40% | LR: 0.000319
Epoch: 016 | MCC: 0.017021 | Train loss: 0.9810 | Train acc: 50.98% | Val loss: 0.9194 | Val acc: 56.07% | LR: 0.000318
Epoch: 017 | MCC: 0.023207 | Train loss: 0.9798 | Train acc: 50.97% | Val loss: 0.9157 | Val acc: 56.33% | LR: 0.000317
Epoch: 018 | MCC: 0.018179 | Train loss: 0.9821 | Train acc: 50.83% | Val loss: 0.9069 | Val acc: 56.37% | LR: 0.000316
Epoch: 019 | MCC: 0.026209 | Train loss: 0.9826 | Train acc: 50.85% | Val loss: 0.9012 | Val acc: 57.00% | LR: 0.000314
Epoch: 020 | MCC: 0.024859 | Train loss: 0.9804 | Train acc: 51.01% | Val loss: 0.8948 | Val acc: 57.39% | LR: 0.000313
Epoch: 021 | MCC: 0.042949 | Train loss: 0.9819 | Train acc: 51.00% | Val loss: 0.8882 | Val acc: 58.06% | LR: 0.000311
Epoch: 022 | MCC: 0.027805 | Train loss: 0.9818 | Train acc: 51.03% | Val loss: 0.8843 | Val acc: 57.43% | LR: 0.000310
Epoch: 023 | MCC: 0.024750 | Train loss: 0.9793 | Train acc: 51.07% | Val loss: 0.8775 | Val acc: 57.35% | LR: 0.000308
Epoch: 024 | MCC: 0.027720 | Train loss: 0.9773 | Train acc: 51.19% | Val loss: 0.8724 | Val acc: 57.44% | LR: 0.000307
Epoch: 025 | MCC: 0.006328 | Train loss: 0.9765 | Train acc: 51.23% | Val loss: 0.8746 | Val acc: 56.42% | LR: 0.000305
Epoch: 026 | MCC: 0.010656 | Train loss: 0.9760 | Train acc: 51.19% | Val loss: 0.8712 | Val acc: 56.90% | LR: 0.000303
Epoch: 027 | MCC: -0.000921 | Train loss: 0.9779 | Train acc: 51.01% | Val loss: 0.8679 | Val acc: 57.08% | LR: 0.000301
Epoch: 028 | MCC: 0.006187 | Train loss: 0.9754 | Train acc: 51.30% | Val loss: 0.8755 | Val acc: 56.56% | LR: 0.000299
Epoch: 029 | MCC: 0.008281 | Train loss: 0.9750 | Train acc: 51.29% | Val loss: 0.8700 | Val acc: 56.88% | LR: 0.000297
Epoch: 030 | MCC: 0.013092 | Train loss: 0.9740 | Train acc: 51.37% | Val loss: 0.8621 | Val acc: 57.47% | LR: 0.000295
Epoch: 031 | MCC: 0.026817 | Train loss: 0.9743 | Train acc: 51.23% | Val loss: 0.8586 | Val acc: 57.79% | LR: 0.000293
Epoch: 032 | MCC: 0.014822 | Train loss: 0.9726 | Train acc: 51.33% | Val loss: 0.8740 | Val acc: 56.64% | LR: 0.000291
Epoch: 033 | MCC: 0.009971 | Train loss: 0.9734 | Train acc: 51.40% | Val loss: 0.8628 | Val acc: 57.13% | LR: 0.000289
Epoch: 034 | MCC: 0.026219 | Train loss: 0.9713 | Train acc: 51.39% | Val loss: 0.8342 | Val acc: 59.10% | LR: 0.000286
Epoch: 035 | MCC: 0.047848 | Train loss: 0.9715 | Train acc: 51.42% | Val loss: 0.8339 | Val acc: 60.27% | LR: 0.000284
Epoch: 036 | MCC: 0.037442 | Train loss: 0.9739 | Train acc: 51.24% | Val loss: 0.8329 | Val acc: 59.15% | LR: 0.000282
Epoch: 037 | MCC: 0.029082 | Train loss: 0.9728 | Train acc: 51.23% | Val loss: 0.8263 | Val acc: 59.32% | LR: 0.000279
Epoch: 038 | MCC: 0.029701 | Train loss: 0.9700 | Train acc: 51.47% | Val loss: 0.8354 | Val acc: 59.03% | LR: 0.000277
Epoch: 039 | MCC: 0.058664 | Train loss: 0.9705 | Train acc: 51.40% | Val loss: 0.8170 | Val acc: 60.17% | LR: 0.000274
Epoch: 040 | MCC: 0.028812 | Train loss: 0.9704 | Train acc: 51.35% | Val loss: 0.8294 | Val acc: 59.03% | LR: 0.000272
Epoch: 041 | MCC: 0.064450 | Train loss: 0.9678 | Train acc: 51.52% | Val loss: 0.8319 | Val acc: 59.20% | LR: 0.000269
Epoch: 042 | MCC: 0.029228 | Train loss: 0.9710 | Train acc: 51.45% | Val loss: 0.8733 | Val acc: 56.52% | LR: 0.000266
Epoch: 043 | MCC: 0.010180 | Train loss: 0.9731 | Train acc: 51.20% | Val loss: 0.8724 | Val acc: 56.32% | LR: 0.000264
Epoch: 044 | MCC: 0.026251 | Train loss: 0.9719 | Train acc: 51.24% | Val loss: 0.8496 | Val acc: 57.93% | LR: 0.000261
Epoch: 045 | MCC: 0.063110 | Train loss: 0.9717 | Train acc: 51.37% | Val loss: 0.8219 | Val acc: 59.67% | LR: 0.000258
Epoch: 046 | MCC: 0.062660 | Train loss: 0.9703 | Train acc: 51.40% | Val loss: 0.8155 | Val acc: 60.11% | LR: 0.000255
Epoch: 047 | MCC: 0.029824 | Train loss: 0.9697 | Train acc: 51.37% | Val loss: 0.8292 | Val acc: 59.05% | LR: 0.000252
Epoch: 048 | MCC: 0.037891 | Train loss: 0.9696 | Train acc: 51.50% | Val loss: 0.8244 | Val acc: 59.49% | LR: 0.000250
Epoch: 049 | MCC: 0.048554 | Train loss: 0.9684 | Train acc: 51.42% | Val loss: 0.8144 | Val acc: 59.84% | LR: 0.000247
Epoch: 050 | MCC: 0.011532 | Train loss: 0.9694 | Train acc: 51.47% | Val loss: 0.8849 | Val acc: 56.03% | LR: 0.000244
Epoch: 051 | MCC: 0.012535 | Train loss: 0.9735 | Train acc: 51.61% | Val loss: 0.8858 | Val acc: 56.10% | LR: 0.000241
Epoch: 052 | MCC: 0.013962 | Train loss: 0.9703 | Train acc: 51.60% | Val loss: 0.8651 | Val acc: 57.03% | LR: 0.000238
Epoch: 053 | MCC: 0.024611 | Train loss: 0.9692 | Train acc: 51.47% | Val loss: 0.8355 | Val acc: 58.79% | LR: 0.000234
Epoch: 054 | MCC: 0.018312 | Train loss: 0.9688 | Train acc: 51.24% | Val loss: 0.8456 | Val acc: 57.93% | LR: 0.000231
Epoch: 055 | MCC: 0.066236 | Train loss: 0.9690 | Train acc: 51.52% | Val loss: 0.8282 | Val acc: 59.42% | LR: 0.000228
Epoch: 056 | MCC: 0.036912 | Train loss: 0.9689 | Train acc: 51.56% | Val loss: 0.8514 | Val acc: 57.91% | LR: 0.000225
Epoch: 057 | MCC: 0.029212 | Train loss: 0.9704 | Train acc: 51.89% | Val loss: 0.8623 | Val acc: 57.22% | LR: 0.000222
Epoch: 058 | MCC: 0.034090 | Train loss: 0.9705 | Train acc: 52.05% | Val loss: 0.8585 | Val acc: 57.42% | LR: 0.000219
Epoch: 059 | MCC: 0.029303 | Train loss: 0.9672 | Train acc: 52.18% | Val loss: 0.8363 | Val acc: 58.66% | LR: 0.000215
Epoch: 060 | MCC: 0.023155 | Train loss: 0.9679 | Train acc: 51.97% | Val loss: 0.8261 | Val acc: 59.05% | LR: 0.000212
Epoch: 061 | MCC: 0.037428 | Train loss: 0.9655 | Train acc: 52.26% | Val loss: 0.8368 | Val acc: 58.71% | LR: 0.000209
Epoch: 062 | MCC: 0.038170 | Train loss: 0.9686 | Train acc: 52.06% | Val loss: 0.8183 | Val acc: 59.59% | LR: 0.000205
Epoch: 063 | MCC: 0.058945 | Train loss: 0.9657 | Train acc: 52.31% | Val loss: 0.8215 | Val acc: 59.37% | LR: 0.000202
Epoch: 064 | MCC: 0.032836 | Train loss: 0.9671 | Train acc: 52.13% | Val loss: 0.8242 | Val acc: 59.37% | LR: 0.000199
Epoch: 065 | MCC: 0.005341 | Train loss: 0.9772 | Train acc: 51.66% | Val loss: 0.8869 | Val acc: 55.79% | LR: 0.000195
Epoch: 066 | MCC: 0.003612 | Train loss: 0.9742 | Train acc: 51.78% | Val loss: 0.8864 | Val acc: 55.92% | LR: 0.000192
Epoch: 067 | MCC: 0.009995 | Train loss: 0.9722 | Train acc: 51.84% | Val loss: 0.8743 | Val acc: 56.38% | LR: 0.000189
Epoch: 068 | MCC: 0.030014 | Train loss: 0.9678 | Train acc: 52.04% | Val loss: 0.8495 | Val acc: 58.05% | LR: 0.000185
Epoch: 069 | MCC: 0.038859 | Train loss: 0.9681 | Train acc: 52.04% | Val loss: 0.8295 | Val acc: 59.08% | LR: 0.000182
Epoch: 070 | MCC: 0.025555 | Train loss: 0.9658 | Train acc: 52.04% | Val loss: 0.8280 | Val acc: 59.09% | LR: 0.000178
Epoch: 071 | MCC: 0.034953 | Train loss: 0.9651 | Train acc: 52.17% | Val loss: 0.8332 | Val acc: 58.86% | LR: 0.000175
Epoch: 072 | MCC: 0.025831 | Train loss: 0.9661 | Train acc: 52.16% | Val loss: 0.8153 | Val acc: 59.57% | LR: 0.000172
Epoch: 073 | MCC: 0.042555 | Train loss: 0.9681 | Train acc: 52.02% | Val loss: 0.8188 | Val acc: 59.78% | LR: 0.000168
Epoch: 074 | MCC: 0.025718 | Train loss: 0.9665 | Train acc: 52.11% | Val loss: 0.8302 | Val acc: 59.09% | LR: 0.000165
Epoch: 075 | MCC: 0.019963 | Train loss: 0.9655 | Train acc: 52.17% | Val loss: 0.8166 | Val acc: 59.57% | LR: 0.000161
Epoch: 076 | MCC: 0.031659 | Train loss: 0.9648 | Train acc: 52.28% | Val loss: 0.8275 | Val acc: 59.29% | LR: 0.000158
Epoch: 077 | MCC: 0.030153 | Train loss: 0.9667 | Train acc: 52.21% | Val loss: 0.8193 | Val acc: 59.68% | LR: 0.000154
Epoch: 078 | MCC: 0.026388 | Train loss: 0.9636 | Train acc: 52.25% | Val loss: 0.8158 | Val acc: 59.92% | LR: 0.000151
Epoch: 079 | MCC: 0.028156 | Train loss: 0.9641 | Train acc: 52.28% | Val loss: 0.8384 | Val acc: 58.71% | LR: 0.000148
Epoch: 080 | MCC: 0.027039 | Train loss: 0.9666 | Train acc: 52.01% | Val loss: 0.8218 | Val acc: 59.46% | LR: 0.000144
Epoch: 081 | MCC: 0.036792 | Train loss: 0.9621 | Train acc: 52.30% | Val loss: 0.8241 | Val acc: 59.39% | LR: 0.000141
Epoch: 082 | MCC: 0.052951 | Train loss: 0.9634 | Train acc: 52.22% | Val loss: 0.8193 | Val acc: 59.64% | LR: 0.000137
Epoch: 083 | MCC: 0.059180 | Train loss: 0.9629 | Train acc: 52.28% | Val loss: 0.8218 | Val acc: 59.54% | LR: 0.000134
Epoch: 084 | MCC: 0.051868 | Train loss: 0.9615 | Train acc: 52.33% | Val loss: 0.8233 | Val acc: 59.49% | LR: 0.000131
Epoch: 085 | MCC: 0.028120 | Train loss: 0.9635 | Train acc: 52.21% | Val loss: 0.8269 | Val acc: 59.14% | LR: 0.000127
Epoch: 086 | MCC: 0.053607 | Train loss: 0.9623 | Train acc: 52.28% | Val loss: 0.8258 | Val acc: 59.23% | LR: 0.000124
Epoch: 087 | MCC: 0.051518 | Train loss: 0.9623 | Train acc: 52.27% | Val loss: 0.8211 | Val acc: 59.54% | LR: 0.000121
Epoch: 088 | MCC: 0.063707 | Train loss: 0.9632 | Train acc: 52.24% | Val loss: 0.8215 | Val acc: 59.62% | LR: 0.000117
Epoch: 089 | MCC: 0.063273 | Train loss: 0.9813 | Train acc: 52.18% | Val loss: 0.8229 | Val acc: 59.62% | LR: 0.000114
Epoch: 090 | MCC: 0.056835 | Train loss: 0.9714 | Train acc: 52.25% | Val loss: 0.8214 | Val acc: 59.53% | LR: 0.000111
Epoch: 091 | MCC: 0.054405 | Train loss: 0.9614 | Train acc: 52.35% | Val loss: 0.8208 | Val acc: 59.58% | LR: 0.000108
Epoch: 092 | MCC: 0.060659 | Train loss: 0.9593 | Train acc: 52.37% | Val loss: 0.8244 | Val acc: 59.52% | LR: 0.000104
Epoch: 093 | MCC: 0.047381 | Train loss: 0.9589 | Train acc: 52.34% | Val loss: 0.8238 | Val acc: 59.44% | LR: 0.000101
Epoch: 094 | MCC: 0.058085 | Train loss: 0.9591 | Train acc: 52.33% | Val loss: 0.8300 | Val acc: 59.13% | LR: 0.000098
Epoch: 095 | MCC: 0.059031 | Train loss: 0.9625 | Train acc: 52.16% | Val loss: 0.8253 | Val acc: 59.45% | LR: 0.000095
Epoch: 096 | MCC: 0.051038 | Train loss: 0.9594 | Train acc: 52.32% | Val loss: 0.8252 | Val acc: 59.39% | LR: 0.000092
Epoch: 097 | MCC: 0.052563 | Train loss: 0.9609 | Train acc: 52.20% | Val loss: 0.8238 | Val acc: 59.44% | LR: 0.000089
Epoch: 098 | MCC: 0.053097 | Train loss: 0.9593 | Train acc: 52.31% | Val loss: 0.8252 | Val acc: 59.46% | LR: 0.000086
Epoch: 099 | MCC: 0.057978 | Train loss: 0.9593 | Train acc: 52.30% | Val loss: 0.8268 | Val acc: 59.35% | LR: 0.000083
Epoch: 100 | MCC: 0.047758 | Train loss: 0.9583 | Train acc: 52.38% | Val loss: 0.8252 | Val acc: 59.48% | LR: 0.000080
Epoch: 101 | MCC: 0.055557 | Train loss: 0.9568 | Train acc: 52.41% | Val loss: 0.8266 | Val acc: 59.25% | LR: 0.000077
Epoch: 102 | MCC: 0.052973 | Train loss: 0.9580 | Train acc: 52.31% | Val loss: 0.8300 | Val acc: 59.31% | LR: 0.000074
Epoch: 103 | MCC: 0.057749 | Train loss: 0.9589 | Train acc: 52.28% | Val loss: 0.8245 | Val acc: 59.54% | LR: 0.000071
Epoch: 104 | MCC: 0.073537 | Train loss: 0.9597 | Train acc: 52.23% | Val loss: 0.8181 | Val acc: 59.88% | LR: 0.000069
Epoch: 105 | MCC: 0.045264 | Train loss: 0.9598 | Train acc: 52.22% | Val loss: 0.8288 | Val acc: 59.22% | LR: 0.000066
Epoch: 106 | MCC: 0.064479 | Train loss: 0.9577 | Train acc: 52.34% | Val loss: 0.8255 | Val acc: 59.52% | LR: 0.000063
Epoch: 107 | MCC: 0.048927 | Train loss: 0.9575 | Train acc: 52.36% | Val loss: 0.8273 | Val acc: 59.29% | LR: 0.000060
Epoch: 108 | MCC: 0.051130 | Train loss: 0.9564 | Train acc: 52.42% | Val loss: 0.8287 | Val acc: 59.34% | LR: 0.000058
Epoch: 109 | MCC: 0.059022 | Train loss: 0.9588 | Train acc: 52.29% | Val loss: 0.8226 | Val acc: 59.73% | LR: 0.000055
Epoch: 110 | MCC: 0.051350 | Train loss: 0.9597 | Train acc: 52.21% | Val loss: 0.8292 | Val acc: 59.39% | LR: 0.000053
Epoch: 111 | MCC: 0.049990 | Train loss: 0.9583 | Train acc: 52.28% | Val loss: 0.8269 | Val acc: 59.34% | LR: 0.000050
Epoch: 112 | MCC: 0.057248 | Train loss: 0.9564 | Train acc: 52.41% | Val loss: 0.8285 | Val acc: 59.40% | LR: 0.000048
Epoch: 113 | MCC: 0.046763 | Train loss: 0.9572 | Train acc: 52.36% | Val loss: 0.8278 | Val acc: 59.29% | LR: 0.000045
Epoch: 114 | MCC: 0.048822 | Train loss: 0.9586 | Train acc: 52.31% | Val loss: 0.8285 | Val acc: 59.29% | LR: 0.000043
Epoch: 115 | MCC: 0.049990 | Train loss: 0.9596 | Train acc: 52.24% | Val loss: 0.8284 | Val acc: 59.34% | LR: 0.000041
Epoch: 116 | MCC: 0.048683 | Train loss: 0.9590 | Train acc: 52.26% | Val loss: 0.8293 | Val acc: 59.26% | LR: 0.000039
Epoch: 117 | MCC: 0.050411 | Train loss: 0.9587 | Train acc: 52.30% | Val loss: 0.8308 | Val acc: 59.34% | LR: 0.000036
Epoch: 118 | MCC: 0.044642 | Train loss: 0.9575 | Train acc: 52.32% | Val loss: 0.8275 | Val acc: 59.29% | LR: 0.000034
Epoch: 119 | MCC: 0.050139 | Train loss: 0.9556 | Train acc: 52.50% | Val loss: 0.8284 | Val acc: 59.36% | LR: 0.000032
Epoch: 120 | MCC: 0.049911 | Train loss: 0.9560 | Train acc: 52.44% | Val loss: 0.8284 | Val acc: 59.31% | LR: 0.000030
Epoch: 121 | MCC: 0.049369 | Train loss: 0.9570 | Train acc: 52.36% | Val loss: 0.8288 | Val acc: 59.29% | LR: 0.000028
Epoch: 122 | MCC: 0.047109 | Train loss: 0.9577 | Train acc: 52.36% | Val loss: 0.8290 | Val acc: 59.24% | LR: 0.000026
Epoch: 123 | MCC: 0.049696 | Train loss: 0.9573 | Train acc: 52.38% | Val loss: 0.8287 | Val acc: 59.29% | LR: 0.000025

[I 2025-10-05 11:02:48,571] Trial 71 finished with value: 0.04704354517161846 and parameters: {'lr': 0.00032850906615020803, 'hidden_size': 69, 'dropout': 0.08372822066709895, 'weight_decay': 0.02471266953778741}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: -0.019851 | Train loss: 0.9994 | Train acc: 50.36% | Val loss: 0.9962 | Val acc: 54.34% | LR: 0.000383
Epoch: 001 | MCC: -0.013393 | Train loss: 0.9964 | Train acc: 50.34% | Val loss: 0.9973 | Val acc: 54.64% | LR: 0.000383
Epoch: 002 | MCC: 0.023077 | Train loss: 0.9933 | Train acc: 50.79% | Val loss: 0.9942 | Val acc: 54.28% | LR: 0.000382
Epoch: 003 | MCC: 0.025119 | Train loss: 0.9920 | Train acc: 50.67% | Val loss: 0.9936 | Val acc: 53.87% | LR: 0.000382
Epoch: 004 | MCC: 0.034285 | Train loss: 0.9917 | Train acc: 50.79% | Val loss: 0.9913 | Val acc: 54.36% | LR: 0.000382
Epoch: 005 | MCC: 0.036692 | Train loss: 0.9923 | Train acc: 50.79% | Val loss: 0.9886 | Val acc: 54.47% | LR: 0.000381
Epoch: 006 | MCC: 0.032219 | Train loss: 1.0062 | Train acc: 50.76% | Val loss: 0.9849 | Val acc: 54.37% | LR: 0.000381
Epoch: 007 | MCC: 0.033760 | Train loss: 0.9908 | Train acc: 50.82% | Val loss: 0.9819 | Val acc: 54.53% | LR: 0.000380
Epoch: 008 | MCC: 0.038701 | Train loss: 0.9866 | Train acc: 50.86% | Val loss: 0.9760 | Val acc: 54.93% | LR: 0.000379
Epoch: 009 | MCC: 0.035958 | Train loss: 0.9843 | Train acc: 50.84% | Val loss: 0.9670 | Val acc: 55.09% | LR: 0.000379
Epoch: 010 | MCC: 0.038441 | Train loss: 0.9814 | Train acc: 51.05% | Val loss: 0.9608 | Val acc: 55.27% | LR: 0.000378
Epoch: 011 | MCC: 0.039393 | Train loss: 0.9836 | Train acc: 50.86% | Val loss: 0.9545 | Val acc: 55.39% | LR: 0.000377
Epoch: 012 | MCC: 0.030362 | Train loss: 0.9819 | Train acc: 51.00% | Val loss: 0.9451 | Val acc: 55.52% | LR: 0.000376
Epoch: 013 | MCC: 0.029157 | Train loss: 0.9813 | Train acc: 50.91% | Val loss: 0.9370 | Val acc: 56.04% | LR: 0.000375
Epoch: 014 | MCC: 0.025247 | Train loss: 0.9805 | Train acc: 50.98% | Val loss: 0.9311 | Val acc: 55.90% | LR: 0.000373
Epoch: 015 | MCC: 0.021175 | Train loss: 0.9800 | Train acc: 50.94% | Val loss: 0.9294 | Val acc: 55.74% | LR: 0.000372
Epoch: 016 | MCC: 0.022127 | Train loss: 1.0236 | Train acc: 50.89% | Val loss: 0.9250 | Val acc: 55.78% | LR: 0.000371
Epoch: 017 | MCC: 0.029976 | Train loss: 0.9922 | Train acc: 50.93% | Val loss: 0.9922 | Val acc: 55.70% | LR: 0.000369
Epoch: 018 | MCC: 0.041891 | Train loss: 0.9827 | Train acc: 50.78% | Val loss: 0.9300 | Val acc: 55.59% | LR: 0.000368
Epoch: 019 | MCC: 0.037843 | Train loss: 0.9933 | Train acc: 50.76% | Val loss: 0.9484 | Val acc: 54.93% | LR: 0.000366
Epoch: 020 | MCC: 0.041533 | Train loss: 0.9851 | Train acc: 50.94% | Val loss: 0.9245 | Val acc: 55.77% | LR: 0.000365
Epoch: 021 | MCC: 0.038768 | Train loss: 0.9806 | Train acc: 50.97% | Val loss: 0.9176 | Val acc: 55.93% | LR: 0.000363
Epoch: 022 | MCC: 0.041137 | Train loss: 0.9843 | Train acc: 50.80% | Val loss: 0.9163 | Val acc: 55.06% | LR: 0.000361
Epoch: 023 | MCC: 0.047536 | Train loss: 0.9806 | Train acc: 50.81% | Val loss: 0.9331 | Val acc: 54.55% | LR: 0.000359
Epoch: 024 | MCC: 0.045223 | Train loss: 0.9830 | Train acc: 50.88% | Val loss: 0.9239 | Val acc: 54.52% | LR: 0.000357
Epoch: 025 | MCC: 0.050931 | Train loss: 0.9894 | Train acc: 50.91% | Val loss: 0.9207 | Val acc: 55.17% | LR: 0.000355
Epoch: 026 | MCC: 0.046425 | Train loss: 0.9801 | Train acc: 51.00% | Val loss: 0.9214 | Val acc: 54.79% | LR: 0.000353
Epoch: 027 | MCC: 0.055870 | Train loss: 0.9811 | Train acc: 50.93% | Val loss: 0.9210 | Val acc: 55.31% | LR: 0.000351
Epoch: 028 | MCC: 0.050088 | Train loss: 0.9804 | Train acc: 50.94% | Val loss: 0.9244 | Val acc: 54.94% | LR: 0.000349
Epoch: 029 | MCC: 0.047178 | Train loss: 0.9799 | Train acc: 50.86% | Val loss: 0.9188 | Val acc: 54.72% | LR: 0.000346
Epoch: 030 | MCC: 0.058658 | Train loss: 0.9849 | Train acc: 51.04% | Val loss: 0.9239 | Val acc: 54.65% | LR: 0.000344
Epoch: 031 | MCC: 0.047314 | Train loss: 0.9781 | Train acc: 51.09% | Val loss: 0.9255 | Val acc: 54.49% | LR: 0.000342
Epoch: 032 | MCC: 0.033558 | Train loss: 0.9795 | Train acc: 51.03% | Val loss: 0.9238 | Val acc: 54.06% | LR: 0.000339
Epoch: 033 | MCC: 0.041925 | Train loss: 0.9801 | Train acc: 50.90% | Val loss: 0.9168 | Val acc: 54.51% | LR: 0.000336
Epoch: 034 | MCC: 0.037247 | Train loss: 0.9798 | Train acc: 51.03% | Val loss: 0.9148 | Val acc: 54.43% | LR: 0.000334
Epoch: 035 | MCC: 0.040697 | Train loss: 0.9785 | Train acc: 50.86% | Val loss: 0.9139 | Val acc: 54.63% | LR: 0.000331
Epoch: 036 | MCC: 0.042899 | Train loss: 0.9769 | Train acc: 50.99% | Val loss: 0.9262 | Val acc: 54.26% | LR: 0.000328
Epoch: 037 | MCC: 0.052931 | Train loss: 0.9793 | Train acc: 50.97% | Val loss: 0.9142 | Val acc: 54.26% | LR: 0.000325
Epoch: 038 | MCC: 0.050467 | Train loss: 0.9820 | Train acc: 51.20% | Val loss: 0.9175 | Val acc: 54.19% | LR: 0.000323
Epoch: 039 | MCC: 0.053045 | Train loss: 0.9778 | Train acc: 51.18% | Val loss: 0.9178 | Val acc: 54.13% | LR: 0.000320
Epoch: 040 | MCC: 0.051571 | Train loss: 0.9761 | Train acc: 51.18% | Val loss: 0.9143 | Val acc: 54.10% | LR: 0.000317
Epoch: 041 | MCC: 0.047012 | Train loss: 0.9774 | Train acc: 51.19% | Val loss: 0.9087 | Val acc: 54.37% | LR: 0.000314
Epoch: 042 | MCC: 0.051260 | Train loss: 0.9754 | Train acc: 51.40% | Val loss: 0.8972 | Val acc: 54.82% | LR: 0.000310
Epoch: 043 | MCC: 0.050188 | Train loss: 0.9763 | Train acc: 51.10% | Val loss: 0.8995 | Val acc: 55.22% | LR: 0.000307
Epoch: 044 | MCC: 0.040839 | Train loss: 0.9794 | Train acc: 51.53% | Val loss: 0.9091 | Val acc: 55.57% | LR: 0.000304
Epoch: 045 | MCC: 0.041240 | Train loss: 0.9778 | Train acc: 51.60% | Val loss: 0.9079 | Val acc: 54.34% | LR: 0.000301
Epoch: 046 | MCC: 0.040249 | Train loss: 0.9775 | Train acc: 51.65% | Val loss: 0.9106 | Val acc: 54.50% | LR: 0.000298
Epoch: 047 | MCC: 0.057047 | Train loss: 0.9754 | Train acc: 51.63% | Val loss: 0.9175 | Val acc: 54.82% | LR: 0.000294
Epoch: 048 | MCC: 0.052351 | Train loss: 0.9759 | Train acc: 51.60% | Val loss: 0.9025 | Val acc: 54.86% | LR: 0.000291
Epoch: 049 | MCC: 0.051628 | Train loss: 0.9751 | Train acc: 51.68% | Val loss: 0.9019 | Val acc: 54.85% | LR: 0.000287
Epoch: 050 | MCC: 0.054679 | Train loss: 0.9763 | Train acc: 51.61% | Val loss: 0.9015 | Val acc: 54.87% | LR: 0.000284
Epoch: 051 | MCC: 0.053608 | Train loss: 0.9780 | Train acc: 51.55% | Val loss: 0.9010 | Val acc: 54.92% | LR: 0.000280
Epoch: 052 | MCC: 0.055683 | Train loss: 0.9758 | Train acc: 51.72% | Val loss: 0.9084 | Val acc: 55.05% | LR: 0.000277
Epoch: 053 | MCC: 0.048618 | Train loss: 0.9760 | Train acc: 51.65% | Val loss: 0.9064 | Val acc: 55.14% | LR: 0.000273
Epoch: 054 | MCC: 0.048002 | Train loss: 0.9743 | Train acc: 51.81% | Val loss: 0.9061 | Val acc: 54.86% | LR: 0.000270
Epoch: 055 | MCC: 0.043434 | Train loss: 0.9742 | Train acc: 51.75% | Val loss: 0.9066 | Val acc: 54.60% | LR: 0.000266
Epoch: 056 | MCC: 0.045187 | Train loss: 0.9749 | Train acc: 51.61% | Val loss: 0.9098 | Val acc: 54.71% | LR: 0.000262
Epoch: 057 | MCC: 0.047324 | Train loss: 0.9752 | Train acc: 51.72% | Val loss: 0.9114 | Val acc: 54.70% | LR: 0.000258
Epoch: 058 | MCC: 0.045282 | Train loss: 0.9744 | Train acc: 51.75% | Val loss: 0.9138 | Val acc: 54.42% | LR: 0.000255
Epoch: 059 | MCC: 0.044245 | Train loss: 0.9761 | Train acc: 51.76% | Val loss: 0.9124 | Val acc: 54.37% | LR: 0.000251
Epoch: 060 | MCC: 0.034596 | Train loss: 0.9752 | Train acc: 51.67% | Val loss: 0.9159 | Val acc: 53.82% | LR: 0.000247
Epoch: 061 | MCC: 0.048491 | Train loss: 0.9752 | Train acc: 51.51% | Val loss: 0.9124 | Val acc: 54.69% | LR: 0.000243
Epoch: 062 | MCC: 0.043499 | Train loss: 0.9723 | Train acc: 51.70% | Val loss: 0.9090 | Val acc: 55.00% | LR: 0.000239
Epoch: 063 | MCC: 0.044283 | Train loss: 0.9740 | Train acc: 51.61% | Val loss: 0.9069 | Val acc: 55.11% | LR: 0.000235
Epoch: 064 | MCC: 0.046523 | Train loss: 0.9729 | Train acc: 51.69% | Val loss: 0.9089 | Val acc: 54.83% | LR: 0.000232
Epoch: 065 | MCC: 0.042718 | Train loss: 0.9933 | Train acc: 51.57% | Val loss: 0.9116 | Val acc: 54.69% | LR: 0.000228
Epoch: 066 | MCC: 0.044698 | Train loss: 0.9781 | Train acc: 51.68% | Val loss: 0.9102 | Val acc: 54.80% | LR: 0.000224
Epoch: 067 | MCC: 0.043612 | Train loss: 0.9741 | Train acc: 51.66% | Val loss: 0.9098 | Val acc: 54.92% | LR: 0.000220
Epoch: 068 | MCC: 0.048292 | Train loss: 0.9736 | Train acc: 51.66% | Val loss: 0.9080 | Val acc: 55.17% | LR: 0.000216
Epoch: 069 | MCC: 0.044832 | Train loss: 0.9721 | Train acc: 51.69% | Val loss: 0.9206 | Val acc: 55.09% | LR: 0.000212
Epoch: 070 | MCC: 0.045873 | Train loss: 0.9727 | Train acc: 51.71% | Val loss: 0.9684 | Val acc: 55.02% | LR: 0.000208
Epoch: 071 | MCC: 0.047477 | Train loss: 0.9719 | Train acc: 51.68% | Val loss: 0.9129 | Val acc: 54.93% | LR: 0.000204
Epoch: 072 | MCC: 0.041422 | Train loss: 0.9729 | Train acc: 51.67% | Val loss: 0.9108 | Val acc: 54.76% | LR: 0.000200
Epoch: 073 | MCC: 0.042444 | Train loss: 0.9687 | Train acc: 51.87% | Val loss: 0.9162 | Val acc: 55.06% | LR: 0.000196
Epoch: 074 | MCC: 0.042313 | Train loss: 0.9731 | Train acc: 51.79% | Val loss: 0.9127 | Val acc: 55.19% | LR: 0.000192
Epoch: 075 | MCC: 0.050498 | Train loss: 0.9719 | Train acc: 51.63% | Val loss: 0.9138 | Val acc: 55.68% | LR: 0.000188
Epoch: 076 | MCC: 0.046781 | Train loss: 0.9714 | Train acc: 51.70% | Val loss: 0.9094 | Val acc: 55.61% | LR: 0.000184
Epoch: 077 | MCC: 0.048023 | Train loss: 0.9703 | Train acc: 51.71% | Val loss: 0.9111 | Val acc: 55.59% | LR: 0.000180
Epoch: 078 | MCC: 0.042583 | Train loss: 0.9733 | Train acc: 51.59% | Val loss: 0.9161 | Val acc: 55.49% | LR: 0.000176
Epoch: 079 | MCC: 0.045551 | Train loss: 0.9708 | Train acc: 51.69% | Val loss: 0.9145 | Val acc: 55.38% | LR: 0.000172
Epoch: 080 | MCC: 0.038826 | Train loss: 0.9692 | Train acc: 51.77% | Val loss: 0.9100 | Val acc: 55.07% | LR: 0.000168
Epoch: 081 | MCC: 0.045322 | Train loss: 0.9706 | Train acc: 51.71% | Val loss: 0.9235 | Val acc: 54.91% | LR: 0.000164
Epoch: 082 | MCC: 0.047166 | Train loss: 0.9707 | Train acc: 51.64% | Val loss: 0.9126 | Val acc: 54.85% | LR: 0.000160
Epoch: 083 | MCC: 0.039371 | Train loss: 0.9712 | Train acc: 51.68% | Val loss: 0.9167 | Val acc: 54.55% | LR: 0.000156
Epoch: 084 | MCC: 0.041827 | Train loss: 0.9710 | Train acc: 51.69% | Val loss: 0.9134 | Val acc: 55.28% | LR: 0.000152
Epoch: 085 | MCC: 0.041609 | Train loss: 0.9691 | Train acc: 51.75% | Val loss: 0.9119 | Val acc: 55.17% | LR: 0.000148
Epoch: 086 | MCC: 0.046503 | Train loss: 0.9698 | Train acc: 51.79% | Val loss: 0.9148 | Val acc: 55.28% | LR: 0.000144
Epoch: 087 | MCC: 0.043466 | Train loss: 0.9694 | Train acc: 51.75% | Val loss: 0.9096 | Val acc: 55.19% | LR: 0.000141
Epoch: 088 | MCC: 0.042884 | Train loss: 0.9717 | Train acc: 51.63% | Val loss: 0.9114 | Val acc: 55.14% | LR: 0.000137
Epoch: 089 | MCC: 0.047968 | Train loss: 0.9723 | Train acc: 51.69% | Val loss: 0.9202 | Val acc: 55.06% | LR: 0.000133
Epoch: 090 | MCC: 0.043504 | Train loss: 0.9683 | Train acc: 51.80% | Val loss: 0.9149 | Val acc: 54.80% | LR: 0.000129
Epoch: 091 | MCC: 0.044669 | Train loss: 0.9719 | Train acc: 51.58% | Val loss: 0.9175 | Val acc: 54.85% | LR: 0.000125
Epoch: 092 | MCC: 0.044564 | Train loss: 0.9707 | Train acc: 51.65% | Val loss: 0.9188 | Val acc: 54.90% | LR: 0.000122
Epoch: 093 | MCC: 0.043955 | Train loss: 0.9693 | Train acc: 51.75% | Val loss: 0.9176 | Val acc: 54.90% | LR: 0.000118
Epoch: 094 | MCC: 0.046049 | Train loss: 0.9688 | Train acc: 51.72% | Val loss: 0.9173 | Val acc: 55.03% | LR: 0.000114
Epoch: 095 | MCC: 0.044932 | Train loss: 0.9709 | Train acc: 51.65% | Val loss: 0.9153 | Val acc: 54.96% | LR: 0.000111
Epoch: 096 | MCC: 0.044227 | Train loss: 0.9706 | Train acc: 51.69% | Val loss: 0.9147 | Val acc: 55.12% | LR: 0.000107
Epoch: 097 | MCC: 0.040535 | Train loss: 0.9692 | Train acc: 51.75% | Val loss: 0.9177 | Val acc: 55.07% | LR: 0.000103
Epoch: 098 | MCC: 0.042203 | Train loss: 0.9688 | Train acc: 51.75% | Val loss: 0.9328 | Val acc: 55.05% | LR: 0.000100
Epoch: 099 | MCC: 0.044239 | Train loss: 0.9698 | Train acc: 51.69% | Val loss: 0.9228 | Val acc: 55.13% | LR: 0.000096
Epoch: 100 | MCC: 0.043338 | Train loss: 0.9710 | Train acc: 51.65% | Val loss: 0.9146 | Val acc: 55.12% | LR: 0.000093
Epoch: 101 | MCC: 0.040012 | Train loss: 0.9685 | Train acc: 51.76% | Val loss: 0.9147 | Val acc: 55.16% | LR: 0.000090
Epoch: 102 | MCC: 0.037801 | Train loss: 0.9689 | Train acc: 51.74% | Val loss: 0.9168 | Val acc: 54.97% | LR: 0.000086
Epoch: 103 | MCC: 0.039509 | Train loss: 0.9728 | Train acc: 51.63% | Val loss: 0.9143 | Val acc: 55.22% | LR: 0.000083
Epoch: 104 | MCC: 0.040163 | Train loss: 0.9725 | Train acc: 51.56% | Val loss: 0.9133 | Val acc: 55.21% | LR: 0.000080
Epoch: 105 | MCC: 0.041327 | Train loss: 0.9700 | Train acc: 51.68% | Val loss: 0.9182 | Val acc: 55.30% | LR: 0.000076
Epoch: 106 | MCC: 0.036853 | Train loss: 0.9679 | Train acc: 51.81% | Val loss: 0.9156 | Val acc: 55.05% | LR: 0.000073
Epoch: 107 | MCC: 0.039288 | Train loss: 0.9713 | Train acc: 51.67% | Val loss: 0.9174 | Val acc: 55.07% | LR: 0.000070
Epoch: 108 | MCC: 0.039417 | Train loss: 0.9844 | Train acc: 51.67% | Val loss: 0.9171 | Val acc: 55.03% | LR: 0.000067
Epoch: 109 | MCC: 0.040439 | Train loss: 0.9699 | Train acc: 51.66% | Val loss: 0.9115 | Val acc: 55.16% | LR: 0.000064
Epoch: 110 | MCC: 0.038395 | Train loss: 0.9687 | Train acc: 51.76% | Val loss: 0.9147 | Val acc: 55.02% | LR: 0.000061
Epoch: 111 | MCC: 0.038488 | Train loss: 0.9697 | Train acc: 51.73% | Val loss: 0.9163 | Val acc: 55.08% | LR: 0.000058
Epoch: 112 | MCC: 0.039306 | Train loss: 0.9726 | Train acc: 51.56% | Val loss: 0.9144 | Val acc: 55.16% | LR: 0.000056
Epoch: 113 | MCC: 0.038959 | Train loss: 0.9680 | Train acc: 51.82% | Val loss: 0.9285 | Val acc: 55.14% | LR: 0.000053
Epoch: 114 | MCC: 0.043180 | Train loss: 0.9703 | Train acc: 51.64% | Val loss: 0.9130 | Val acc: 55.12% | LR: 0.000050
Epoch: 115 | MCC: 0.039483 | Train loss: 0.9692 | Train acc: 51.74% | Val loss: 1.0579 | Val acc: 55.09% | LR: 0.000047
Epoch: 116 | MCC: 0.039987 | Train loss: 0.9700 | Train acc: 51.69% | Val loss: 0.9130 | Val acc: 55.18% | LR: 0.000045

[I 2025-10-05 11:04:37,004] Trial 72 finished with value: 0.03975858842022717 and parameters: {'lr': 0.0003828079267030232, 'hidden_size': 82, 'dropout': 0.10059646369094243, 'weight_decay': 0.028617311826303036}. Best is trial 15 with value: 0.059484380297362804.

Epoch: 000 | MCC: 0.002928 | Train loss: 0.9995 | Train acc: 50.05% | Val loss: 0.9884 | Val acc: 54.75% | LR: 0.000441
Epoch: 001 | MCC: 0.006771 | Train loss: 0.9950 | Train acc: 50.49% | Val loss: 0.9816 | Val acc: 55.03% | LR: 0.000440
Epoch: 002 | MCC: -0.002000 | Train loss: 0.9931 | Train acc: 50.54% | Val loss: 0.9754 | Val acc: 55.45% | LR: 0.000440
Epoch: 003 | MCC: -0.019021 | Train loss: 0.9910 | Train acc: 50.95% | Val loss: 0.9729 | Val acc: 55.10% | LR: 0.000440
Epoch: 004 | MCC: 0.009727 | Train loss: 0.9911 | Train acc: 50.89% | Val loss: 0.9681 | Val acc: 54.66% | LR: 0.000439
Epoch: 005 | MCC: 0.013462 | Train loss: 0.9875 | Train acc: 51.05% | Val loss: 0.9584 | Val acc: 54.65% | LR: 0.000439
Epoch: 006 | MCC: 0.012395 | Train loss: 0.9856 | Train acc: 50.93% | Val loss: 0.9478 | Val acc: 54.80% | LR: 0.000438
Epoch: 007 | MCC: 0.018157 | Train loss: 0.9838 | Train acc: 51.00% | Val loss: 0.9406 | Val acc: 54.92% | LR: 0.000438
Epoch: 008 | MCC: 0.005073 | Train loss: 0.9830 | Train acc: 50.98% | Val loss: 0.9322 | Val acc: 55.13% | LR: 0.000437
Epoch: 009 | MCC: 0.004527 | Train loss: 0.9838 | Train acc: 50.91% | Val loss: 0.9286 | Val acc: 54.81% | LR: 0.000436
Epoch: 010 | MCC: 0.003890 | Train loss: 0.9828 | Train acc: 50.95% | Val loss: 0.9193 | Val acc: 55.30% | LR: 0.000435
Epoch: 011 | MCC: 0.007382 | Train loss: 0.9816 | Train acc: 50.99% | Val loss: 0.9150 | Val acc: 55.45% | LR: 0.000434
Epoch: 012 | MCC: 0.023627 | Train loss: 0.9810 | Train acc: 50.96% | Val loss: 0.9051 | Val acc: 56.49% | LR: 0.000433
Epoch: 013 | MCC: 0.027109 | Train loss: 0.9811 | Train acc: 50.98% | Val loss: 0.8943 | Val acc: 56.97% | LR: 0.000431
Epoch: 014 | MCC: 0.038846 | Train loss: 0.9803 | Train acc: 51.07% | Val loss: 0.8905 | Val acc: 57.40% | LR: 0.000430
Epoch: 015 | MCC: 0.030383 | Train loss: 0.9804 | Train acc: 51.05% | Val loss: 0.8806 | Val acc: 57.38% | LR: 0.000428
Epoch: 016 | MCC: 0.021349 | Train loss: 0.9809 | Train acc: 50.99% | Val loss: 0.8740 | Val acc: 56.72% | LR: 0.000427
Epoch: 017 | MCC: -0.000469 | Train loss: 0.9805 | Train acc: 51.00% | Val loss: 0.8707 | Val acc: 56.75% | LR: 0.000425
Epoch: 018 | MCC: 0.008824 | Train loss: 0.9817 | Train acc: 51.11% | Val loss: 0.8748 | Val acc: 56.74% | LR: 0.000423
Epoch: 019 | MCC: 0.006328 | Train loss: 0.9794 | Train acc: 51.22% | Val loss: 0.8771 | Val acc: 56.61% | LR: 0.000422
Epoch: 020 | MCC: 0.009255 | Train loss: 0.9775 | Train acc: 51.23% | Val loss: 0.8741 | Val acc: 56.74% | LR: 0.000420
Epoch: 021 | MCC: 0.015003 | Train loss: 0.9756 | Train acc: 51.27% | Val loss: 0.8842 | Val acc: 56.61% | LR: 0.000418
Epoch: 022 | MCC: 0.015305 | Train loss: 0.9769 | Train acc: 51.26% | Val loss: 0.8697 | Val acc: 57.20% | LR: 0.000416
Epoch: 023 | MCC: 0.013222 | Train loss: 0.9743 | Train acc: 51.37% | Val loss: 0.8745 | Val acc: 56.98% | LR: 0.000413
Epoch: 024 | MCC: 0.007526 | Train loss: 0.9748 | Train acc: 51.32% | Val loss: 0.8727 | Val acc: 56.78% | LR: 0.000411
Epoch: 025 | MCC: -0.003083 | Train loss: 0.9764 | Train acc: 51.17% | Val loss: 0.8589 | Val acc: 57.47% | LR: 0.000409
Epoch: 026 | MCC: -0.001793 | Train loss: 0.9741 | Train acc: 51.36% | Val loss: 0.8531 | Val acc: 57.86% | LR: 0.000406
Epoch: 027 | MCC: 0.001952 | Train loss: 0.9750 | Train acc: 51.31% | Val loss: 0.8599 | Val acc: 57.61% | LR: 0.000404
Epoch: 028 | MCC: 0.015875 | Train loss: 0.9734 | Train acc: 51.34% | Val loss: 0.8517 | Val acc: 58.15% | LR: 0.000401
Epoch: 029 | MCC: 0.002234 | Train loss: 0.9744 | Train acc: 51.23% | Val loss: 0.8619 | Val acc: 57.49% | LR: 0.000399
Epoch: 030 | MCC: 0.024081 | Train loss: 0.9747 | Train acc: 51.39% | Val loss: 0.8375 | Val acc: 59.08% | LR: 0.000396
Epoch: 031 | MCC: 0.002357 | Train loss: 0.9726 | Train acc: 51.27% | Val loss: 0.8749 | Val acc: 56.61% | LR: 0.000393
Epoch: 032 | MCC: 0.011574 | Train loss: 0.9732 | Train acc: 51.29% | Val loss: 0.8556 | Val acc: 57.86% | LR: 0.000390
Epoch: 033 | MCC: 0.011784 | Train loss: 0.9739 | Train acc: 51.26% | Val loss: 0.8403 | Val acc: 58.70% | LR: 0.000387
Epoch: 034 | MCC: -0.000933 | Train loss: 0.9722 | Train acc: 51.44% | Val loss: 0.8629 | Val acc: 57.48% | LR: 0.000384
Epoch: 035 | MCC: -0.003457 | Train loss: 0.9739 | Train acc: 51.32% | Val loss: 0.8783 | Val acc: 56.48% | LR: 0.000381
Epoch: 036 | MCC: -0.000073 | Train loss: 0.9761 | Train acc: 51.20% | Val loss: 0.8713 | Val acc: 57.05% | LR: 0.000378
Epoch: 037 | MCC: 0.051996 | Train loss: 0.9718 | Train acc: 51.39% | Val loss: 0.8541 | Val acc: 58.65% | LR: 0.000375
Epoch: 038 | MCC: 0.009887 | Train loss: 0.9731 | Train acc: 51.28% | Val loss: 0.8508 | Val acc: 57.79% | LR: 0.000371
Epoch: 039 | MCC: 0.010911 | Train loss: 0.9715 | Train acc: 51.36% | Val loss: 0.8735 | Val acc: 57.12% | LR: 0.000368
Epoch: 040 | MCC: 0.015470 | Train loss: 0.9730 | Train acc: 51.35% | Val loss: 0.8609 | Val acc: 57.76% | LR: 0.000364
Epoch: 041 | MCC: 0.004511 | Train loss: 0.9752 | Train acc: 51.26% | Val loss: 0.8664 | Val acc: 57.20% | LR: 0.000361
Epoch: 042 | MCC: 0.002332 | Train loss: 0.9716 | Train acc: 51.39% | Val loss: 0.8693 | Val acc: 57.08% | LR: 0.000357
Epoch: 043 | MCC: 0.006836 | Train loss: 0.9716 | Train acc: 51.36% | Val loss: 0.8597 | Val acc: 57.65% | LR: 0.000354
Epoch: 044 | MCC: 0.006897 | Train loss: 0.9716 | Train acc: 51.17% | Val loss: 0.8623 | Val acc: 57.46% | LR: 0.000350
Epoch: 045 | MCC: 0.011294 | Train loss: 0.9725 | Train acc: 51.42% | Val loss: 0.8529 | Val acc: 58.07% | LR: 0.000346
Epoch: 046 | MCC: 0.027685 | Train loss: 0.9704 | Train acc: 51.32% | Val loss: 0.8695 | Val acc: 56.97% | LR: 0.000342
Epoch: 047 | MCC: 0.035116 | Train loss: 0.9706 | Train acc: 51.36% | Val loss: 0.8448 | Val acc: 58.49% | LR: 0.000339
Epoch: 048 | MCC: 0.027082 | Train loss: 0.9690 | Train acc: 51.91% | Val loss: 0.8764 | Val acc: 56.65% | LR: 0.000335
Epoch: 049 | MCC: 0.056501 | Train loss: 0.9726 | Train acc: 51.30% | Val loss: 0.8502 | Val acc: 58.41% | LR: 0.000331
Epoch: 050 | MCC: 0.052950 | Train loss: 0.9711 | Train acc: 52.15% | Val loss: 0.8569 | Val acc: 57.97% | LR: 0.000327
Epoch: 051 | MCC: 0.022155 | Train loss: 0.9695 | Train acc: 52.13% | Val loss: 0.8527 | Val acc: 58.05% | LR: 0.000323

In [ ]:
torch.manual_seed(42)
torch.cuda.manual_seed(42)

model = SLOT(
      input_size=len(price_features),
      hidden_size=hidden_size,
).to(device)

model.load_state_dict(torch.load(dataset_dir / "best_SLOT_model.pth", map_location=device))

test_loss = 0.0
test_acc = 0.0

model.eval()

with torch.inference_mode():
    for X_test, o_test, c_test, y_test in test_dataloader:

        X_test, o_test, c_test, y_test = X_test.to(device), o_test.to(device), c_test.to(device), y_test.to(device)

        logits = model(X_test, o_test, c_test)
        loss, acc = evaluate(logits, y_test)

        test_loss += loss.item()
        test_acc += acc


    test_loss /= len(test_dataloader)
    test_acc /= len(test_dataloader)

print(f"Test loss: {test_loss:.4f} | Test acc: {100*test_acc:.2f}%")

NameError: name 'torch' is not defined